### ISSUE TITLE
Why are addresses of a and b not equal? Need some more explanation.

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#10005]
If I add these lines to the end of the code, below, it prints "true".
string c = "hello";
Console.WriteLine((object)a == (object)c);

I understand it as CLR assigned the very same address for string variables which are initially assigned with the same content. But it did not assign the same address for string variables which modified to the same content. 
I kindly ask for some deeper explanation why the address of a and b are not the same.

string a = "hello";
string b = "h";
// Append to contents of 'b'
b += "ello";
Console.WriteLine(a == b);
Console.WriteLine((object)a == (object)b);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b95029-3bf2-c56d-48ab-be7ad1f43762
* Version Independent ID: a5f74e00-3f77-804d-f47d-26caa05bfc40
* Content: [string - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/string)
* Content Source: [docs/csharp/language-reference/keywords/string.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/string.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
The issue here, @volkan-yazilim, is that the code performs two different tests for equality. The first tests for the equality of two strings, and to do that it performs a test for value equality (it compares the individual characters in the two string objects). The second casts the strings to objects and compares them using the equals operator. The equals operator when used with reference types other than strings performs a test for reference equality. Since a and b are not the same object, the operator returns false.
 
Since I think this answers your question, I'll close this issue.

**Comment by volkan-yazilim** [comment]
Thank you for explanation. I actually wanted to ask something different.

As far as as I know, if the content of two string variables are the same at compile time, their references are the same. It means ReferenceEquals method returns true for them. Such as;
string a = "hello";
string c = "hello";
ReferenceEquals(a,c);   => returns true

if another string variable gets the very same string content on runtime, its reference would not be the same as the variables amentioned above. Such as;

string b = "h";
b += "ello";
ReferenceEquals(b,c);   => returns false

I wanted to ask this. Is it by design? Where can I find an explanation about it?

Thanks

**Comment by pkulikov** [comment]
@volkan-yazilim That might be due to string interning:
https://docs.microsoft.com/en-us/dotnet/api/system.string.intern?view=netframework-4.7.2#remarks

**Comment by rpetrusha** [comment]
Yes, the result is due to string interning (or rather to the way that string interning works). b isn'ttaken from the intern pool because it's built incrermentally using concatenation -- the string literal "hello" is never assigned to b.

**Comment by volkan-yazilim** [comment]
@rpetrusha  Thank you.
