### ISSUE TITLE
Include sample code for Building Docker .NET Images

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1000]
This topic https://github.com/dotnet/core-docs/blob/master/docs/core/docker/building-net-docker-images.md

docs not have the code it uses for its sample in the repo. It should.

The contributing guide references where to put samples, and based on those guidelines, this sample should go under samples/core.  I'll recommend making a new samples/core/docker directory for all the xplat Docker based samples.

The topic should provide a link to the GitHub folder where the sample code resides. That makes it easy for customers to download the sample, or explore any of the files online.

This would give a single directory where building samples may include building Docker images, or starting containers to execute tests.  Our CI system does not currently execute any Docker specific commands, but that has been requested.

In addition, where code has been included in the topic, we can replace the inline code with included regions from the sample code. (See the F# Tour or the C# Tour for examples of the syntax).

/cc @dend for discussion of any enhancements needed for the CI build system.

**Comment by mairaw** [comment]
We should have examples of using .NET and ASP.NET
