### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by brandon34343** [dotnet/docs#10011]
The list is alphabetical, it would be helpful if there was a guided path we can follow. Emphasize which one to start with and then a "next" link to the article that would logically be next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79095336-671c-ea61-f907-cc928fa66884
* Version Independent ID: d48a2bca-bccc-6c57-34fc-ea72c8e0b1c2
* Content: [Programming Concepts (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/)
* Content Source: [docs/csharp/programming-guide/concepts/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @brandon34343 

I've added this to our project backlog to update as we update these topics.
