### ISSUE TITLE
Missing creation of TrainFinalModel method

### ISSUE THREAD

**Issue by hobbit125** [dotnet/docs#10012]
This line occurs in this document:

"To save your model to a .zip file before returning, add the following code to call the SaveModelAsFile method as the next line in TrainFinalModel:"

And there is no prior instruction to create or call a TrainFinalModel method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @hobbit125, for that good catch. That was left over from an earlier addition that was removed. I've just updated the topic with the correct method reference and submitted a PR. #10014 Thanks again for your help!

**Comment by JRAlexander** [comment]
The PR was merged and the change should be live in a day or so.
