### ISSUE TITLE
Feedback from Customer: how to call native C++ code in Linux 

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1002]
See [here](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli#lf-content=167633667:567243362) for the issue.  

We should document how to work with native libraries in a cross-platform manner.

@terrajobst I haven't done this. Can you help me build the scenario and process?

/cc @richlander

**Comment by cpei-avalara** [comment]
I found some discussion here : https://github.com/dotnet/coreclr/issues/930#issuecomment-100675743

**Comment by BillWagner** [comment]
We have examples in the core codebase for this.  Pinging @stephentoub to help me find a good example to use for the customer example.

**Comment by stephentoub** [comment]
C APIs work on unix just as they do on Windows (C++ APIs are difficult to P/Invoke to on any platform due to name mangling), e.g.
https://github.com/dotnet/corefx/blob/9348997920c1ba782b45adb5e8ee9754149ab1e2/src/System.IO.FileSystem/tests/FileSystemTest.cs#L51

**Comment by BillWagner** [comment]
@stephentoub Thanks!  That's a great start.

What we want to do on the docs site to address this issue is to write a short topic explaining how to use P/Invoke, and reference examples from corefex.  That one above will be great for C.  Doe you know of a good example in C++? If not, I'll search and find one. 

Thanks again.

**Comment by stephentoub** [comment]
>Do you know of a good example in C++? If not, I'll search and find one.

Name mangling makes it near impossible to know the name of the function to invoke.  Even if you're doing the actual native implementation in C++, you typically want to use ```extern "C"``` to specify C linkage e.g.
https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_memory.cpp#L8

**Comment by conniey** [comment]
I was looking for a tutorial regarding this issue as well... and there seems to be a [Native Interoperability](https://docs.microsoft.com/en-us/dotnet/articles/standard/native-interop) document on our docs site that shows a Mac, Linux and Windows example.  Is this what they are looking for?

**Comment by raffaeler** [comment]
@stephentoub What about Reverse PInvoke? (the ability to call a .NET class method from a native program)
And how can I load the NetCore CLR if the process is bootstrapping from C / C++?
My target is to make this work x-plat.
Thank you

**Comment by stephentoub** [comment]
> What about Reverse PInvoke?

Reverse P/Invoke works on unix.

> And how can I load the NetCore CLR if the process is bootstrapping from C / C++?

The unixcorerun/coreconsole utilities here:
https://github.com/dotnet/coreclr/tree/master/src/coreclr/hosts
are examples of C/C++ programs that host coreclr.

**Comment by raffaeler** [comment]
Thank you @stephentoub 
I could successfully host the CLR and invoke the delegate for my function from C++.

How you compare the hosting solution to the Reverse P/Invoke? Which one is most convenient?

I also found [NativeCallableAttribute](https://github.com/dotnet/coreclr/blob/release/1.1.0/src/mscorlib/src/System/Runtime/InteropServices/NativeCallableAttribute.cs) which should ease the Reverse P/Invoke invocation.
I comes from [this discussion](https://github.com/dotnet/coreclr/pull/1566), has been merged and should be available but I could not find it in the System.Runtime nuget package.
Any samples/docs explaining how to use it?

Thank you!

**Comment by BillWagner** [comment]
closing as below the bar.
