### ISSUE TITLE
Examples Missing

### ISSUE THREAD

**Issue by Gammerz26** [dotnet/docs#10027]
The 3rd line says: "The following examples create single-dimensional, multidimensional, and jagged arrays:" yet there is only one example of a single-dimensional array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d7544-6f92-5582-9d28-7160a5bc916a
* Version Independent ID: 7e3f884a-94b6-ea27-70ea-060fe51f51c2
* Content: [Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/)
* Content Source: [docs/csharp/programming-guide/arrays/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/arrays/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @Gammerz26. We've opened PR #10104 to display the correct example.
