### ISSUE TITLE
So what if I want to write to a specific path...

### ISSUE THREAD

**Issue by BDTomasz** [dotnet/docs#10033]
So what if I want to write to a specific path within a web app? any useful links... anywhere? 2hrs browsing through the docs... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7d2312a-0b45-4d11-b3fb-11e9cdba3372
* Version Independent ID: ea715711-4ee9-08cf-f319-6b7e1eadd84e
* Content: [How to: Read Text from a File](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-read-text-from-a-file)
* Content Source: [docs/standard/io/how-to-read-text-from-a-file.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-read-text-from-a-file.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@BDTomasz The [how to write text to a file](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-write-text-to-a-file) doc has information about how to specify the path - what is it missing?
