### ISSUE TITLE
No solution name textbox

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#10032]
When I create the WCF Service Library project I don't see a Solution name textbox. Is that part unnecessary for VS 2017 and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e13437-f72d-8507-b1e6-e0b4dbc32008
* Version Independent ID: 525f628e-8880-1fcc-1314-dfd4e0779aa0
* Content: [WCF Client Overview](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-client-overview)
* Content Source: [docs/framework/wcf/wcf-client-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/wcf-client-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
@SimpleSamples Sorry for the delay on this. I'm unsure what you're referring to related to this article. I don't see a mention of a library project in the article. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow.

I'm going to close the issue. 

Thanks.
