### ISSUE TITLE
when conditional keyword not highlighted

### ISSUE THREAD

**Issue by HermannGruber** [dotnet/docs#10042]
I've just noticed that the conditional "when" keyword is not highlighted correctly when it appears as part of a "case" in a "switch" statement, like in this example:

public static double ComputeArea_Version4(object shape)
{
    switch (shape)
    {
        case Square s when s.Side == 0:
        case Circle c when c.Radius == 0:
        case Triangle t when t.Base == 0 || t.Height == 0:
        case Rectangle r when r.Length == 0 || r.Height == 0:
            return 0;

        case Square s:
            return s.Side * s.Side;
        case Circle c:
            return c.Radius * c.Radius * Math.PI;
        case Triangle t:
            return t.Base * t.Height / 2;
        case Rectangle r:
            return r.Length * r.Height;
        default:
            throw new ArgumentException(
                message: "shape is not a recognized shape",
                paramName: nameof(shape));
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by HermannGruber** [comment]
Besides, in this code snippet, the "when" is highlighted but in light blue instead of plain blue: 

static object CreateShape(string shapeDescription)
{
    switch (shapeDescription)
    {
        case "circle":
            return new Circle(2);

        case "square":
            return new Square(4);
        
        case "large-circle":
            return new Circle(12);

        case var o when (o?.Trim().Length ?? 0) == 0:
            // white space
            return null;
        default:
            return "invalid shape description";
    }            
}

**Comment by HermannGruber** [comment]
Also, "when" is not highlighted when used as a part of a "catch" expression, like here: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6

**Comment by svick** [comment]
As far as I can tell, this site uses [highlight.js](https://highlightjs.org/) for code highlighting, so fixing this would involve improving [this file](https://github.com/highlightjs/highlight.js/blob/master/src/languages/cs.js) and then updating the version of highlight.js used here.

Vaguely related issue: https://github.com/MicrosoftDocs/feedback/issues/641.

**Comment by BillWagner** [comment]
Thanks for pointing these out @HermannGruber 

As @svick mentioned, this needs to be fixed in the JS library that highlights the text. I've added notes on MicrosoftDocs/feedback#641 with the additional information you provided. I tagged you in that comment so you'll be notified of progress on that issue.

I'm closing this as a duplicate.
