### ISSUE TITLE
About this Example - Error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10050]
@jlzcardoso commented on [Fri Jan 18 2019](https://github.com/dotnet/docs.pt-br/issues/108)

The compiler complains about this line and do not compile.

  // Cause the OnRegionChange delegate to be called.
    elemHost.Region = new Region()

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 271ce87d-14af-50b6-4f7a-c6d86fff338b
* Version Independent ID: 98d164bb-5dff-af9c-beb0-441d750eb06d
* Content: [Instruções passo a passo: mapeando propriedades usando o controle ElementHost](https://docs.microsoft.com/pt-br/dotnet/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control)
* Content Source: [docs/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting an error in the example
best

**Comment by rpetrusha** [comment]
I can't reproduce this issue, @CeciAc; both the Visual Basic code and the C# code compile and execute as expected.
