### ISSUE TITLE
Clarify the definition of platform in this context

### ISSUE THREAD

**Issue by nsuchy** [dotnet/docs#10061]
"Your app uses a platform that doesn’t support .NET Core."

Could we clarify this sentence a bit? Does the article meaning an operating system or cpu architecture, if I recall correctly dotnet core just recently got Windows ARM support. Does it mean a database or package? An example would be helpful here :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server?view=aspnetcore-2.2#feedback)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@nsuchy Good question -- per the [.NET Glossary](https://docs.microsoft.com/en-us/dotnet/standard/glossary#platform), a platform is "An operating system and the hardware it runs on, such as Windows, macOS, Linux, iOS, and Android." The [.NET Core guide](https://docs.microsoft.com/dotnet/core/) clarifies that the platforms that support .NET Core are Windows, macOS, and Linux.
