### ISSUE TITLE
The Close() lines should not be in the using statement code examples

### ISSUE THREAD

**Issue by dustinmcmanus** [dotnet/docs#10067]
It begs the question, are the places that do not call Close() implemented incorrectly? The answer is no. It forces the programmer to do research to figure out implementation-specific details, only to find out that the end of the using block calls Dispose(), which calls Close(). (For StreamWriter, Close() calls Flush()). Then Close() calls Dispose(boolean), which was added for backwards compatibility.

Therefore, the Close() lines are unnecessary, and they create confusion. They should be removed, so that the code examples are consistent with the documentation at https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader?view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e20ec-96de-0340-0813-27968ae4ca89
* Version Independent ID: db8ef20b-08da-cbac-0d96-91dcef8abe56
* Content: [Using objects that implement IDisposable](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects)
* Content Source: [docs/standard/garbage-collection/using-objects.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/using-objects.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @dustinmcmanus, and for pointing out that the call to Close is confusing and unnecessary. Unless you'd like to submit a pull request to make the changes (see the [Contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) for more information), we'll update the documentation sometime later this month.
