### ISSUE TITLE
Please explain your over-engineered crap.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#10070]
What the hell is "attribute"? What am I getting an attribute of?

This crappy doc's reference to "attribute" is like walking into a bar and asking for a glass of liquor.

The generalized nomenclature you people use is worthless with a definition.

Please explain your over-engineered crap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a62174c-7cdd-54b7-6740-49caf6d5b043
* Version Independent ID: be1f8622-f6ea-5da9-d038-a4459b94c671
* Content: [Retrieving Information Stored in Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/retrieving-information-stored-in-attributes)
* Content Source: [docs/standard/attributes/retrieving-information-stored-in-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/retrieving-information-stored-in-attributes.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LJ9999** [comment]
Ignore that vitriol above. I was just made aware that people actually read this feedback. When did that begin?

Replace the above scream at the bottom of the ocean with this:

What is an execution context? What is a reflection-only context? What is an attribute? Why would anybody in the real world want to retrieve "Information Stored in Attributes"?

This document tells me how to bake a cake nobody will ever eat.

**Comment by NextTurn** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/#common-uses-for-attributes

**Comment by Thraka** [comment]
@LJ9999 Hi. I'm curious about how you arrived at the article?

**Comment by Thraka** [comment]
Looking at feedback data it looks like a lot of people get to this article searching for things that indicate they already understand attributes and want to know how to read a value out of it. The article could probably use some clarification the execution domains but I don't think it is that high of a priority. Sorry.

Thank you for leaving a comment about it though, it will be here (and the one you filed in site feedback) for when we take the opportunity to improve this section. 

I'm going to close this for now.

Thanks again.
