### ISSUE TITLE
This procedure does not work in the real world.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#10078]
I am validating an xml-serialized class against a schema. Microsoft inserts a targetNameSpace that is required for using XmlSchemaSet. But validation does not occur when I corrupt the xml in the same way that the sample is corrupted here. 

I think there's a bug in this procedure for more complex XML, ironically XML that is created by Microsoft.

Would you please provide me a phone number of an XML-oriented Support rep in Redmond to whom I can describe the details of this problem for the purpose of locating a workaround to this bug.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10b45fa-626c-1fbb-4193-1f8d8fce34c1
* Version Independent ID: f751fec1-76b0-f5c5-3cf3-4c50b2aa3d10
* Content: [How to: Validate Using XSD (LINQ to XML) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-validate-using-xsd-linq-to-xml)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-validate-using-xsd-linq-to-xml.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-validate-using-xsd-linq-to-xml.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@LJ9999 we don't have phone numbers to give out. You have to go through the proper channels either by calling support or opening product issues using the Product Feedback button instead of Content Feedback at the bottom of every article.

For that reason, I'm closing this issue.
