### ISSUE TITLE
SQLClientPermission

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/docs#10086]
Other documentation talks about the need to check for SQLClientPermission using a function similar to CanRequestSqlNotifications, but this example makes no reference to checking to see if one has appropriate permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bb20bc6-ec90-c5d1-8f40-5725f214122c
* Version Independent ID: 1160cca8-659f-c6d8-fb60-f65187a5a472
* Content: [Detecting Changes with SqlDependency](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/detecting-changes-with-sqldependency)
* Content Source: [docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@stevestein please check this ADO.NET content feedback.

**Comment by stevestein** [comment]
@AndyWDev - thanks for the feedback. Apologies for the delayed reply. A link to the information on enabling notifications is provided at the top of the article: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/enabling-query-notifications#query-notifications-permissions

Thanks
