### ISSUE TITLE
No longer applicable?

### ISSUE THREAD

**Issue by dchurch24** [dotnet/docs#10081]
This appears to be inaccurate as at Win10. I have Visual Studio installed, along with various DotNet frameworks. There is nothing listed under "NET Framework Setup" at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
It is applicable to Windows 10, @dchurch24. Are you sure that you're looking at the correct registry path -- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full:

![image](https://user-images.githubusercontent.com/10886961/51563739-16297000-1e42-11e9-8982-a2fff986b62b.png)

**Comment by mairaw** [comment]
Closing due to the lack of response. If @rpetrusha's answer doesn't help you, please let us know.
