### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10080]
@frgt10cs commented on [Sat Jan 19 2019](https://github.com/dotnet/docs.ru-ru/issues/164)

Я делал всё по документации, код полностью идентичен (даже копировал-вставлял), в итоге результаты не сходятся. Ваши выходные данные:
Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0.4585565
Sentiment: He is the best, and the article should say that. | Prediction: Not Toxic | Probability: 0.9924279
Мои:
Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0,5297049
Sentiment: He is the best, and the article should say that. | Prediction: Toxic | Probability: 0,9918675
Что не так? Почему различие?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Использование ML.NET для анализа тональности методом двоичной классификации](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis#machine-learning-workflow)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the user is having issues with the provided example
Rough translation:

> 
> I did everything according to the documentation, the code is completely identical (even copied-pasted), as a result, the results do not converge. Your output:
> Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0.4585565
> Sentiment: He is the best. | Prediction: Not Toxic | Probability: 0.9924279
> My:
> Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0.5297049
> Sentiment: He is the best. | Prediction: Toxic | Probability: 0.9918675
> What's wrong? Why the difference?

**Comment by JRAlexander** [comment]
Closing. Fixed with 11114
