### ISSUE TITLE
Call to ExecuteReader

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/docs#10088]
What relevance does the call to command.ExecuteReader have in this example (detecting changes in SqlDependency).  Is it necessary to query the data after setting up a notification handler - if so, why?

Also, in the OnDependencyChange, it would be good to see an example of handling the change.  For example, how to use SqlNotificationEventArgs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bb20bc6-ec90-c5d1-8f40-5725f214122c
* Version Independent ID: 1160cca8-659f-c6d8-fb60-f65187a5a472
* Content: [Detecting Changes with SqlDependency](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/detecting-changes-with-sqldependency)
* Content Source: [docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@stevestein please check this feedback regarding ADO.NET content

**Comment by stevestein** [comment]
@AndyWDev - thanks for the feedback.

Yes, not a very good example here. The command in the example should've changed data to trigger the notification.

We've created an internal work item (1756238) to look into updating this example.

Thanks.
