### ISSUE TITLE
Compiler option -errorendlocation present in csc.exe command-line help but not listed here

### ISSUE THREAD

**Issue by frizzr** [dotnet/docs#10083]
Before I added this issue, it does appear that csc.exe's command-line help does document -errorendlocation to the end user (see https://github.com/dotnet/roslyn/blob/79b9c406b348dd5c295365f5eebb9a35be24d330/src/Compilers/CSharp/Portable/CSharpResources.resx#L4663 , so I am assuming this newer option is here to stay. Could we add it to this page? Its current description is "Output line and column of the end location of each error."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b29fc27-0985-b3ea-e1d4-338c1dc126ed
* Version Independent ID: cc362e14-4bcb-0b38-36ce-9b8502e5e4e2
* Content: [C# Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-alphabetically.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-alphabetically.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jcouv** [comment]
This option was added a while back (before 2014), so I don't know its history. But this option (`errorendlocation`) and a related option (`fullpaths`) are indeed listed in `csc -help`. That means they are supported.

```
[...]
                       - ADVANCED -
[...]
-fullpaths                    Compiler generates fully qualified paths
[...]
-errorendlocation             Output line and column of the end location of
                              each error
[...]
```

**Comment by BillWagner** [comment]
Thanks @jcouv 

I've added this to our backlog. I've also added the up-for-grabs label and added this to our community project.

**Comment by Potapy4** [comment]
@jcouv @BillWagner After investigation, I found that there are several missing commands, such as `-errorlog:<file>`, `-reportanalyzer` and `-version` - I also added them.
