### ISSUE TITLE
C# 6 tutorial: New object initialization syntax section seems confusing

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#10085]
The [New object initialization syntax](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=9) section seems to miss some information.

It starts with
> New object initialization enables you to create methods that make it easier to initialize dictionaries, and other types.

First, it doesn't say explicitly what is new. As a result, it's difficult to reason what hides behind "other types". 

The example straight after the paragraph is good and helps as it makes me think that the topic is about indexer initializers. However, with that in mind, the sentence that follows the example:
> You can extend this syntax to any class that implements `IEnumerable` and has a publicly accessible `Add` method.

results in a question: What does it mean to "extend the syntax to a class"? 

Does it mean to "apply/use the syntax with a class"? With such a take and given that the example demonstrates indexer initializer, the sentence can be read in the following way:
> You can use index initializers with any class that implements `IEnumerable` and has a publicly accessible `Add` method.

To my knowledge, that way of reading it is not correct. So, either I misunderstand something/apply wrong reasoning or the phrasing of the section should be updated to avoid misinterpretation.

At last, the following also looks misleading:
> Try the following sample in the interactive window. It creates a `Path` class that implements `IEnumerable<Point3D>` and has a method to add points that takes three arguments. 

The only present following sample contains a `Path` class, but that class *doesn't* have a method that takes three arguments. It looks that the referred sample is missing, because the very last sample is introduced with the following words:
> This sample won't compile in the interactive experience because of sandbox limitations. 

So, I guess it's not the one recommended to be tried in the interactive window and the one recommended is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3686c2-4c73-5686-0da9-abc38c74aeec
* Version Independent ID: ca995f80-9375-e9ca-b855-6e6893581e23
* Content: [Explore C# 6 - Try the new features in C# 6 interactively, using your browser](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=10)
* Content Source: [docs/csharp/tutorials/exploration/csharp-6.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/exploration/csharp-6.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by markbjerke** [comment]
The example doesn't run, I tired supplying the missing Point3D class but then the extension Add method complained.

**Comment by noorulh06** [comment]
I don't under what they want to say by telling to use Extension class?
