### ISSUE TITLE
Reference to Termination()

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/docs#10087]
There is a reference to void Termination() in the code example, however, it does not appear to be called by anything and there is no indication that the Termination() method is or isnt part of SqlDependency.  This may be confusing to some people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bb20bc6-ec90-c5d1-8f40-5725f214122c
* Version Independent ID: 1160cca8-659f-c6d8-fb60-f65187a5a472
* Content: [Detecting Changes with SqlDependency](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/detecting-changes-with-sqldependency)
* Content Source: [docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/detecting-changes-with-sqldependency.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@stevestein please look at this feedback for ADO.NET content. Thanks!

**Comment by stevestein** [comment]
@AndyWDev - thanks for the feedback.

The example says: _The following code fragment shows the design pattern you would use to create a sample application._

So it's just showing at the end of the example how to stop and release the dependency. It's not intended to be a functioning example.

Thanks!
