### ISSUE TITLE
Document know optimizations the F# compiler performs

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#10097]
This is based on feedback from the FSSF community standup I have each Tuesday.

There are often times where you can write F# code that may seem like it needlessly allocates, but the compiler can optimize away various calls such that you get nicer compile-time benefits without paying the actual cost at runtime.

However, these patterns are not well-known. Perhaps it's worth documenting them.

**Comment by Liminiens** [comment]
It would be nice to have more information on what inline functions can do

**Comment by baronfel** [comment]
Information about what kinds of constant-folding the compiler can do would be nice, as well.

**Comment by Liminiens** [comment]
@dsyme it would be nice to have it in `docs` with some examples for better understanding :)
