### ISSUE TITLE
Why SDK and Runtime images not in sync?

### ISSUE THREAD

**Issue by seanfdnn** [dotnet/docs#10094]
Building with the SDK and then running the published binaries (via a Docker-multi-stage build) produces `The specified framework 'Microsoft.AspNetCore.All', version '2.1.1' was not found.`

```
FROM microsoft/dotnet:2.1-sdk-alpine as builder
... add code ...
RUN dotnet publish -c Release --framework netcoreapp2.1
FROM microsoft/dotnet:2.1-runtime-alpine
...
COPY --from=builder /src/bin/Release/netcoreapp2.1/publish /app/
CMD dotnet MyAssembly.dll
```

looking at the DockerHub tags -- the runtime and sdk seem to be on different versions? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [Docker images overview - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/docker/building-net-docker-images)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Closing due to no response.
