### ISSUE TITLE
Putting white space in documentation

### ISSUE THREAD

**Issue by THorting** [dotnet/docs#10093]
I am trying to add tabs to some of my comments.  \t just prints out and &lt;sig&gt; removes all white space.  I have not used list and that might be close to what I am looking for.  Just cannot find any reference to white space in the documentation.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The full list of supported tags is in the [C# spec](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/documentation-comments)  We should update this document to link to that section in the spec.

The other possible answer is to use well-formed HTML in your comments. the viewing tool may respect those.
