### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by aitc-h** [dotnet/docs#10091]
Minor mistake in the second sentence of the 'Using a Simple Collection' section.
"by using a or foreach statement." should be replaced with "by using a foreach statement."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0b88ff-d651-fd2f-a6e4-acfa1089b1f2
* Version Independent ID: bc5056d9-27ed-f1ce-bc7a-6e61121a578d
* Content: [Collections (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/collections#see-also)
* Content Source: [docs/csharp/programming-guide/concepts/collections.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/collections.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by ksratheesh** [comment]
@mairaw  , am a first timer , can i take this up.

**Comment by mairaw** [comment]
@ksratheesh sorry I missed your question. Someone just submitted a PR. 

Keep an eye on [easy](https://github.com/dotnet/docs/labels/easy) issues or if you'd like, I can ping you when a new easy one comes in. Just let me know!
