### ISSUE TITLE
Incorrect Toxic/NonToxic Prediction Value

### ISSUE THREAD

**Issue by lzinga** [dotnet/docs#10106]
After going through the documents for the text sentiment ML I wasn't getting the expected results as stated in the docs.  After a bit more testing I downloaded the actual files and came out with the same result.

> Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0.5297049
> Sentiment: He is the best, and the article should say that. | Prediction: Toxic | Probability: 0.9918675

These two lines are both predicting that the sentiments are "Toxic" however based on the docs and what 
should naturally be expected the second line should be considered "Non-Toxic" which is being shown as "Toxic" instead.

The below result is what the expectation would be if working correctly.

> Sentiment: This is a very rude movie | Prediction: Toxic | Probability: 0.4585565
> Sentiment: He is the best, and the article should say that. | Prediction: Not Toxic | Probability: 0.9924279
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mikkelbu** [comment]
It looks like part of this duplicates #9081.

**Comment by lzinga** [comment]
> 
> 
> It looks like part of this duplicates #9081.

Does look similar, after some more research and sending some messages turns out this is an issue with the dataset. The datasets are too small to effectively train the model and they are looking into a replacement.

**Comment by JRAlexander** [comment]
Closing. Fixed as part of #11114
