### ISSUE TITLE
Please cross referece From AOT to CoreRT

### ISSUE THREAD

**Issue by xtofs** [dotnet/docs#10101]
The CoreRT paragraph already talks and reference AOT but not the other way around which makes it sound like an abstract idea and not an actual feature in .NET

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa071095-4eb6-20c1-ca26-f34da6fcbdf8
* Version Independent ID: 2b2efd49-b0c8-9a13-525a-d04c802d2bef
* Content: [.NET Glossary](https://docs.microsoft.com/en-us/dotnet/standard/glossary)
* Content Source: [docs/standard/glossary.md](https://github.com/dotnet/docs/blob/master/docs/standard/glossary.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@xtofs Thanks for the suggestion - I've created a pull request to do that.
