### ISSUE TITLE
Document aspnet-codegenerator

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#10100]
After "The following commands are installed by default:"
Add tools that you need to install.

See https://github.com/aspnet/Docs/issues/3208

edit by @mairaw: updated the link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [.NET Core Command-Line Interface (CLI) Tools - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/index.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Rick-Anderson** [comment]
> add a new section here that briefly talks about global tools and links to docs.microsoft.com/en-us/dotnet/core/tools/global-tools for more info

I agree with that.

> recommends some to be installed

I don't know of any we would recommend.

add a new section after https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#find-a-net-core-global-tool  about ~recommended~ {commonly used or popular??} tools

**Comment by mairaw** [comment]
@Rick-Anderson this was scheduled for march, what's the new target?

**Comment by Rick-Anderson** [comment]
@mairaw I'll do it this sprint.

**Comment by mairaw** [comment]
Can this be closed @Rick-Anderson? I think you've handled with https://github.com/aspnet/AspNetCore.Docs/pull/13108, no?
