### ISSUE TITLE
Client Profile for .Net 3.5 / 4 is not mentioned

### ISSUE THREAD

**Issue by phil-the** [dotnet/docs#10114]
Framework 3.5 and 4.0 come as either the 'full' version or the client profile.
I believe Windows 7 for example only includes the client profile by default, so it would be extremely useful for the table to be updated with client profile and full versions separately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hello. Thank you for opening this issue. I've been going through these older issues that seemed to have gotten lost and I don't think it's currently a priority to add Windows 7 information.  Thank you though.
