### ISSUE TITLE
reading mode on Microsoft  windows 10 mobile egde 

### ISSUE THREAD

**Issue by jaymin93** [dotnet/docs#10126]
Hi we need reading mode compatible in windows 10 mobile edge browser while reading many docs on edge I found some time I can use reading mode and some time not eg currently I can not switch to reading mode as it is disable it is the not this topic related issue feel free to move to right place thanks looking forward for improvement that help 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d4015e-aa05-9193-e3f5-f273c86142c9
* Version Independent ID: ec47da08-f2b5-bc26-bf02-502ee83079bd
* Content: [Value types - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types)
* Content Source: [docs/csharp/language-reference/keywords/value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/value-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @jaymin93. I've transferred this issue to https://github.com/MicrosoftDocs/feedback/issues/1091 for our engineering team to take a look since this isn't specific to our content, but a site funcionality.
