### ISSUE TITLE
ReceiveFailure

### ISSUE THREAD

**Issue by mkumara20** [dotnet/docs#10123]
Thank you for providing wonderful article to help me understand the exceptions. I face an issue with ReceiveFailure status for my https request (DELETE request with response code: 400; Tested in Chrome browser and web service returns response 400 with JSON result); however http request works fine.

Can you please help or direct me to get more details about the below line: (Tried all other options)
If using SSL, make sure the server process has permission to access the Certificate store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ff7dca-7d70-7d8d-9430-e27691d6b150
* Version Independent ID: 9f783694-646d-ea89-9f58-2fff374a8d9e
* Content: [Understanding WebRequest Problems and Exceptions](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/understanding-webrequest-problems-and-exceptions)
* Content Source: [docs/framework/network-programming/understanding-webrequest-problems-and-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/understanding-webrequest-problems-and-exceptions.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@mkumara20 which part is not clear? The server (which is outside of scope of this document) has to have access to the Certificate store to be able to validate SSL certificate ...
