### ISSUE TITLE
A SOLUTION is also a valid argument

### ISSUE THREAD

**Issue by sebagomez** [dotnet/docs#10127]
Just like in the build command the main argument can be either a project file or a solution (sln) file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Leon99** [comment]
...and it would be good to explain the behaviour of `publish` with a solution file

**Comment by gzinger** [comment]
yes, especially with the -output parameter

**Comment by tdykstra** [comment]
Fixed by #17196
