### ISSUE TITLE
misspell

### ISSUE THREAD

**Issue by psphilli** [dotnet/docs#10120]
Please change 'certifiate' to 'certificate', thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a66361-c964-5a31-d284-0d752cfb4ec5
* Version Independent ID: 3e04cfca-df3e-199e-e51c-bfdff8c8de05
* Content: [How to: Configure a Port with an SSL Certificate](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate)
* Content Source: [docs/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thank you for your feedback @psphilli.

Would you like to open a pull request to fix this? You can find the examples that have that typo with the following search:
https://github.com/dotnet/samples/search?q=certifiate&unscoped_q=certifiate

**Comment by psphilli** [comment]
Will-do a @mariaw, thanks

**Comment by mikkelbu** [comment]
@mairaw This issue should be closed by dotnet/samples#593, but the linkage was wrong.

**Comment by mairaw** [comment]
Ah, thanks @mikkelbu! I've changed the link there and I'm closing this. Thanks @psphilli for catching that and fixing it.
