### ISSUE TITLE
Chapter X

### ISSUE THREAD

**Issue by donile** [dotnet/docs#10121]
The last sentence of the first paragraph references "Chapter X".  Is this supposed to be present?  If yes, what is Chapter X?  Seems like X is a variable for a document template system such as LaTex.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ba44f-bfb6-e9bf-0bba-b91ee867340d
* Version Independent ID: 789c8230-93ba-d484-edda-c8b2a9a8073c
* Content: [Test ASP.NET Core MVC apps](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md)
* Product: **dotnet**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Thanks, that should be chapter 4. I've fixed it in the soon-to-be-published 2.2 version of the eBook and will get it updated here soon as well.

**Comment by ardalis** [comment]
Fixed in https://github.com/dotnet/docs/pull/10174
