### ISSUE TITLE
Document the possible output column names in scored DataView

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#10136]
Right now, these column/field names are kind of "secret names" that you need to know.
I don't think this is documented "end-to-end" in docs.microsoft.com, neither in the HOW to / CookBook.

We should have the following info available:
---
The purpose of the output columns in scored IDataView depends on the specific learning task being used:

###  Regression
- Label: Original regression value of the example.
- Score: Predicted regression value.

###  Binary Classification
- Label: Original Label of the example.
- Score: Raw score from the learner (e.g. value before applying sigmoid function to get probability).
- Probability: Probability of being in certain class
- PredictedLabel: Predicted class.

###  Multi-class Classification
- Label: Original Label of the example.
- Score: Its an array whose length is equal to number of classes and contains probability for each class.
- PredictedLabel: Predicted class.

### Clustering
- Label: Original cluster Id of the example.
- Score: Its an array whose length is equal to number of clusters. It contains square distance from the cluster centeriod.
- PredictedLabel: Predicted cluster Id.

----------
This is related to the following issue requesting that info and raised at the ML.NET repo:
https://github.com/dotnet/machinelearning/issues/376

This additional issue might also be related:
https://github.com/dotnet/docs/issues/5640

**Comment by mairaw** [comment]
@JRAlexander @luisquintanilla FYI - I just tagged it with the ML.NET Guide

**Comment by shmoradims** [comment]
I believe this issue is already addressed as part of 1.0 API reference documentation. Now all trainers have a sub-section in their remarks called input/output columns, where the types and definition of the input/output columns are clearly explained. E.g.: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.averagedperceptrontrainer?view=ml-dotnet#input-and-output-columns

**Comment by JRAlexander** [comment]
Thanks, @shmoradims! I agree and am therefore closing.
