### ISSUE TITLE
Add the whole code for ProcessData() and BuildAndTrainModel() methods right after explaining them step-by-step.

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#10132]
It would be good to add the whole code for ProcessData() and BuildAndTrainModel() methods right after explaining them step-by-step.
Having an end-to-end vision of the whole code per method is important, otherwise the code is explained but too sparse in the tutorial to see the main processes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Use ML.NET in a GitHub issue multiclass classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
I've added the samples link to the top of the doc. Let's see how that works.
