### ISSUE TITLE
Code example fix

### ISSUE THREAD

**Issue by thedeoxen** [dotnet/docs#10130]
Looks like need to change this:

.Append(mlContext.BinaryClassification.Trainers.FastTree(numLeaves: 50, numTrees: 50, minDatapointsInLeaves: 20));

to :
pipeline.Append(mlContext.BinaryClassification.Trainers.FastTree(numLeaves: 50, numTrees: 50, minDatapointsInLeaves: 20));

in the code block "Choose a learning algorithm"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Использование ML.NET для анализа тональности методом двоичной классификации](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi @thedoxen, "pipeline" is only needed if you put a ";" on the previous line. Closing as I believe it's  resolved. Please reopen if this isn't the case.
