### ISSUE TITLE
Explain what Polly is

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#10146]
A link to https://github.com/App-vNext/Polly or http://www.thepollyproject.org/ at least, would be useful. A short explanation of what Polly is and how it relates to HttpClientFactory would be even better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#implement-your-typed-client-classes-that-use-the-injected-and-configured-httpclient)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
That's a good suggestion. @mvelosop @CESARDELATORRE can you please take a look?

**Comment by mvelosop** [comment]
Hi @IanKemp, @mairaw, Polly is explained in the article following the one referenced in this issue, that is: 
[Implement HTTP call retries with exponential backoff with HttpClientFactory and Polly policies](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly)

![image](https://user-images.githubusercontent.com/7357806/52858704-cd07cb80-3122-11e9-9e7a-b40b83592b93.png)

**Comment by mvelosop** [comment]
Hi @IanKemp, will improve this article and include the suggested mentions.
