### ISSUE TITLE
The article needs some modification about nullable reference types

### ISSUE THREAD

**Issue by sadqiang** [dotnet/docs#10141]
The article said that:

> Nullable types represent value-type variables that can be assigned the null value. You cannot create a nullable type based on a reference type. (Reference types already support the null value.)

Now in the incoming C# 8.0, a reference type can be a nullable type.
The article above needs some modification, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab99a9ea-4645-92cd-723a-4a38fbee371e
* Version Independent ID: 652ea928-6ded-800c-6bed-5b1f3f67fe3f
* Content: [Nullable types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/)
* Content Source: [docs/csharp/programming-guide/nullable-types/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @sadqiang We'll put this on the list of articles to update between now and the C# 8 general release.
