### ISSUE TITLE
Example Gives Exception

### ISSUE THREAD

**Issue by adamj537** [dotnet/docs#10140]
When I run the example on this page (by copying into a new project in Visual Studio), I get an InvalidOperationException on this line in Form1_Load method:

// Add a DemoCustomer to cause a row to be displayed.
this.customersBindingSource.AddNew();

The exception message is:  "Item cannot be added to a read-only or fixed-size list."

What might I check to see what's causing this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b44c5f-5be6-de8d-5ae1-028a523c9bec
* Version Independent ID: 0e806407-d3eb-039a-e19f-b2d46e1f402b
* Content: [How to: Customize Item Addition with the Windows Forms BindingSource](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-customize-item-addition-with-the-windows-forms-bindingsource)
* Content Source: [docs/framework/winforms/controls/how-to-customize-item-addition-with-the-windows-forms-bindingsource.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-customize-item-addition-with-the-windows-forms-bindingsource.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I'm afraid that I can't reproduce this issue, @adamj537; the VB and C# examples run successfully for me both from the command line and in Visual Studio. But if you'd like to submit a pull request to add the line of code, the samples are found in  https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataConnector.AddingNew/CS/form1.cs and https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataConnector.AddingNew/VB/form1.vb. Instructions on submitting a PR are [here](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).
