### ISSUE TITLE
Typo: OperationCancelledException should be OperationCanceledException

### ISSUE THREAD

**Issue by MaxG117** [dotnet/docs#10159]
One example says:

> Uncomment the `throw new OperationCancelledException` line to demonstrate what happens when you cancel an asynchronous process.

There is one "l" in `OperationCanceledException`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Good catch @MaxG117! Would you like to submit a fix for that?

You can find the instructions here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by MaxG117** [comment]
The instructions show:
![editicon](https://user-images.githubusercontent.com/26261605/51779443-40866200-20bc-11e9-8b32-2f795c5f5383.png)
But I see:
![fork-edit](https://user-images.githubusercontent.com/26261605/51779446-44b27f80-20bc-11e9-9c52-39ba7a5cb48e.png)
I'm not yet comfortable enough with github to know whether forking the project is the correct action for a simple edit.

**Comment by mairaw** [comment]
Resolved with PR #10161

**Comment by mairaw** [comment]
@MaxG117 I also created a PR to fix the confusing image issue:
https://github.com/MicrosoftDocs/Contribute/pull/183 

Thanks for letting us know about your experience when trying to contribute!
