### ISSUE TITLE
DerivedClass example comment bug?

### ISSUE THREAD

**Issue by addemko** [dotnet/docs#10151]
Is there a bug in the "DerivedClass" example that DOESN'T have a finalizer?

It seems to encourage having unmanaged resources with the "// Free any unmanaged objects here." comment. However, since this class doesn't have a finazlier (and the BaseClass isn't guaranteed to have one), couldn't this leak the unmanaged resource?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-derived-class)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@addemko Thanks for pointing that out. I've added this issue to our backlog for investigation.

**Comment by marchewek** [comment]
It's a valid finding for both "Using a safe handle..." examples. In case an unmanaged resource is used in any of the classes, this class needs to define a Finalizer - as mentioned earlier "[...] or an override to the Object.Finalize method." So the comments about unmanaged resources should be removed from the example in order not to confuse developers.
