### ISSUE TITLE
General Questions/observations

### ISSUE THREAD

**Issue by AlexSapple** [dotnet/docs#10150]
Hi,

I've started playing with ML.net and made a slightly modified version of this to suit data I had. exercise has given me a few questions (please bear in mind I am completely new to this type of thing). 

1. My dataset was from elastic search documents - I found that I could use CreateStreamingDataView() to work with this. All the examples seem to use text file datasets. are text file datasets more common? (I come from a database world). 

2. working with int's caused errors when training a model. I was getting the following error: "One or more errors occurred. (Column 'AdultCount' has values of I4which is not the same as earlier observed type of R4". 

I think "l4which" was intended to be "l4 which" but in any case without any other changes, if i changed data type to be float, no such error. I'm not sure what R4 and L4 refer to but something to do with datatypes? 

when I got my modified example working - evaluating test data gave a metric of: RSquared = -0.12 and a RMS of 92.02. Clearly these values are outside the parameters that they should be - but I don't know how to troubleshoot such things - are there any tutorials on identifying why a model is messed up? 

3. I had a datetime field in my data. It may be a relevant field for making predictions (in my case I was looking at predicting a result count for a search with a 3rd party, based on existing logged search data). I am curious about fields like dates and how they might play a role - but not sure how they might be encoded into the pipeline. I thought that a date may be a lot more use if it was transformed into a day of year (or similar) to capture a pattern of seasonality rather than the pure date. 

4. my predictions were absolutely miles out (but that was expected after looking at the score of the model). I was in some cases predicting result counts of negative numbers. 

overall, I'm really excited by having the framework available to dev with - but really need more learning resources!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Predict New York taxi fares using a regression learner with ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by kkho** [comment]
I get the same bug too, any updates? Maybe I was lazy to not read the documentation. But the namings can be messy and confusing as a developer... maybe its easier for those who have deep dive into statistics?

**Comment by JRAlexander** [comment]
Creating an issue over at [the ML.NET product repo](https://github.com/dotnet/machinelearning) for this.

**Comment by PakAtom** [comment]
Poorly written. Where is the predict method? Where to copy 
var prediction = predictionFunction.Predict(taxiTripSample);
Main cannot see
Console.WriteLine($"**********************************************************************");
Console.WriteLine($"Predicted fare: {prediction.FareAmount:0.####}, actual fare: 15.5");
Console.WriteLine($"**********************************************************************");

**Comment by JRAlexander** [comment]
Closing as companion issue is here and this is a product question. https://github.com/dotnet/machinelearning/issues/2514
