### ISSUE TITLE
Mixed Grouped Join

### ISSUE THREAD

**Issue by deadmann** [dotnet/docs#10166]
I wish i know if there is a way to fetch from multiple table and put in sub model...
For example, i have a list of tours, and for those tours, i have list of offers, which contains different prices informations, and those itself have information that are not listed in that table it self, so when i want to join, i'll use offer as group joined, and once i did that, i'm wonder how i can again join something to that offer, and actually, join to and place data inside of that "into" part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de690d2-fba4-ce90-964f-4a4eaa99e05f
* Version Independent ID: 28d797c1-3fe1-c867-fd17-dbacb6728109
* Content: [Perform grouped joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-grouped-joins)
* Content Source: [docs/csharp/linq/perform-grouped-joins.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/perform-grouped-joins.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by deadmann** [comment]
somehow i managed to do that, and not just that, but a nested one, and it's complex, but for reference...

private IQueryable<TourFullVM> GetQueryable(string calendar, string userGuid)
        {
            var user = _uow.All<HOzv>().FirstOrDefault(w => !w.IsDeleted && w.UserGuid == userGuid);
            if (user == null)
                throw Utility.GenerateResponseException(HttpStatusCode.Unauthorized, "User not found");

            var nerkhType = user.NerkhType;
            var queryable =
            (from tour in _uow.All<HTour>()

                join tourDat in _uow.All<HTourDat>()
                on tour.TourCod equals tourDat.TourCod

                join kargozarR in _uow.All<HKargozar>()
                on tourDat.KargozarCodR equals kargozarR.KargozarCod
                into kr
                from kargozarMasterR in kr.DefaultIfEmpty()

                join kargozarB in _uow.All<HKargozar>()
                on tourDat.KargozarCodR equals kargozarB.KargozarCod
                into kb
                from kargozarMasterB in kb.DefaultIfEmpty()

                join trip in _uow.All<HTrip>()
                on tourDat.Tripcod equals trip.Tripcod
                into tr
                from tripMaster in tr.DefaultIfEmpty()

                join monasebat in _uow.All<HMonasebat>()
                on tourDat.MonasebatCod equals monasebat.MonasebatCod
                into m
                from monasebatMaster in m.DefaultIfEmpty()

                join vasileR in _uow.All<HVasile>()
                on tourDat.VasileCodR equals vasileR.VasileCod
                into vr
                from vasileMasterR in vr.DefaultIfEmpty()

                join vasileB in _uow.All<HVasile>()
                on tourDat.VasileCodB equals vasileB.VasileCod
                into vb
                from vasileMasterB in vb.DefaultIfEmpty()



                join harkat in _uow.All<HHarkat>()
                on tourDat.HarkatCod equals harkat.HarkatCod
                into h
                from harkatMaster in h.DefaultIfEmpty()

                join food in _uow.All<HFood>()
                on tourDat.FoodCod equals food.FoodCod
                into f
                from foodMaster in f.DefaultIfEmpty()

                #region Pishnahad
                    //pishnahad
                    join offer in ( //GROUP JOIN PISHNAHAD BEGIN
                    from pishnahad in _uow.All<HTourDatPishnahad>()

                        #region PRICE
                        //Price
                    join pricing in ( //GROUP JOIN PRICE (ALL TABLES) BEGIN
                        //JOIN INSIDE A GROUP DATA
                        from pishnehadPrice in _uow.All<HTourDatPishanadPrice>()
                        join price in _uow.All<HTourPrice>()
                        on pishnehadPrice.PriceCod equals price.PriceCod
                        select new
                        {
                            Pishnehad = pishnehadPrice,
                            Price = price
                        }
                    )
                    on new
                    {
                        pishnahad.TourCod,
                        pishnahad.TourRow,
                        pishnahad.PishnahadCod

                    } equals new
                    {
                        pricing.Pishnehad.TourCod,
                        pricing.Pishnehad.TourRow,
                        pricing.Pishnehad.PishnahadCod
                    }
                    into masterPricing //GROUP JOIN PRICE (ALL TABLES) END
                    #endregion Price

                    select new
                    {
                        Offer = pishnahad,
                        //price
                        OfferPriceList = from data in masterPricing
                        select new OfferConditionDetailVM
                        {
                            Code = data.Price.PriceCod,
                            Description = data.Price.PriceNam,
                            Price = (nerkhType == 1
                                ? data.Pishnehad.PriceOnline
                                : nerkhType == 2
                                    ? data.Pishnehad.PriceAzhans1
                                    : nerkhType == 3
                                        ? data.Pishnehad.PriceAzhans2
                                        : nerkhType == 4
                                            ? data.Pishnehad.PriceSazman
                                            : data.Pishnehad.PriceOnline),
                            PriceOnline = data.Pishnehad.Price
                        }
                    }
                )
                on new
                {
                    TourCode = tourDat.TourCod,
                    TourRow = tourDat.TourRow
                }
                equals new
                {
                    TourCode = offer.Offer.TourCod,
                    TourRow = offer.Offer.TourRow
                }
                into offerMaster //GROUP JOIN PISHNAHAD BEGIN
                #endregion Pishnahad

             where
                //After Today Dates
                DbFunctions.TruncateTime((DateTime?) tourDat.StDat) >= DbFunctions.TruncateTime(DateTime.Now)
                && DbFunctions.TruncateTime((DateTime?) tourDat.EndDateFr) >= DbFunctions.TruncateTime(DateTime.Now)

                && (tourDat.Stat ?? 0) == 1

                select new
                {
                    //TABLES
                    T = tour,
                    TD = tourDat,
                    KR = kargozarMasterR,
                    KB = kargozarMasterB,
                    Tr = tripMaster,
                    M = monasebatMaster,
                    VR = vasileMasterR,
                    VB = vasileMasterB,
                    H = harkatMaster,
                    F = foodMaster,

                    TDP = offerMaster
                });


            var vms = queryable.Select(s =>
                new TourFullVM
                {
                    QueryableCalendar = calendar,

                    //HTour
                    TourCod = s.T.TourCod,
                    Description = s.T.Dsc,

                    //HTourDat
                    TimingCode = s.TD.TourRow,
                    Name = s.TD.TourNam,
                    QueryableStartDate = s.TD.StDat,
                    QueryableEndDate = s.TD.EndDat,
                    Day = s.TD.Rooz,
                    Night = s.TD.Shab,
                    GatewayTimeLeave = s.TD.TimeHozorR,
                    GatewayTimeReturn = s.TD.TimeHozorB,
                    TourOperatorLeave = s.KR != null ? s.KR.KargozarNam : null,
                    TourOperatorReturn = s.KB != null ? s.KB.KargozarNam : null,
                    DepartureTimeLeave = s.TD.TimeHarkatR,
                    DepartureTimeReturn = s.TD.TimeHarkatB,
                    TripNumberLeave = s.TD.HarkatNoR,
                    TripNumberReturn = s.TD.HarkatNoB,
                    TripDurationLeave = s.TD.TimeDurationR,
                    TripDurationReturn = s.TD.TimeDurationB,
                    ArrivalTimeLeave = s.TD.TimeHozorDesR,
                    ArrivalTimeReturn = s.TD.TimeHozorDesB,
                    TripName = s.Tr != null ? s.Tr.TripNam : null,
                    Event = s.M != null ? s.M.MonasebatNam : null,
                    VehicleLeave = s.VR != null ? s.VR.VasileNam : null,
                    VehicleReturn = s.VB != null ? s.VB.VasileNam : null,
                    GatewayLocation = s.H != null ? s.H.HarkatNam : null,
                    Food = s.F != null ? s.F.FoodNam : null,
                    QueryableSaleEndDate = s.TD.EndDateFr,
                    TourServices = s.TD.KhadamatTour,
                    CancelDsc = s.TD.CancelDsc,

                    OfferList = from offer in s.TDP
                                select new OfferVM
                                {
                                    OfferCode = offer.Offer.PishnahadCod,
                                    OfferDescription = offer.Offer.PishnahadNam,
                                    OfferPriceList = offer.OfferPriceList
                                }
                }
            );
            return vms;
        }

**Comment by BillWagner** [comment]
I'm glad you found the answer @deadmann 

I'll close this as resolved.
