### ISSUE TITLE
Works in debug but not failes when publish to ISS

### ISSUE THREAD

**Issue by timvtoo** [dotnet/docs#10169]
This was really helpful thank you, but im getting error 500 when i try to run it on my local windows 10 IIS. Runs fine debugging in visual studio.  
Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f10d016-86b9-fba6-1331-1fe3bc91a552
* Version Independent ID: e062e766-46c6-b44b-980f-4d8639ed3379
* Content: [Create an AJAX-Enabled WCF Service and an ASP.NET Client in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/create-an-ajax-wcf-asp-net-client)
* Content Source: [docs/framework/wcf/feature-details/create-an-ajax-wcf-asp-net-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/create-an-ajax-wcf-asp-net-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
@HongGit can your team look at this issue?
