### ISSUE TITLE
The coding formatting must be changed

### ISSUE THREAD

**Issue by Arash-Sabet** [dotnet/docs#10173]
As an example the following code snippet must be changed from:

TcpClient TCP = new TcpClient("localhost",11000);

To:

var tcp = new TcpClient("localhost",11000);

In modern programming days, it's discouraged to use capital cases for local variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee15f916-5406-85fa-b7fb-a9e69fcd3efb
* Version Independent ID: b6aae569-8a56-0a44-7b8e-e54491418baf
* Content: [Encrypting Data](https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data)
* Content Source: [docs/standard/security/encrypting-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/encrypting-data.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Arash-Sabet** [comment]
@rpetrusha I'd love to but I cannot make a commitment on when.

**Comment by rpetrusha** [comment]
We've added this to the backlog, @Arash-Sabet, as well as to the community contributor's project. You can submit a PR at your convenience.
