### ISSUE TITLE
Mouse Down/Up? 

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10177]
"For instance, a Windows Presentation Foundation (WPF) Button suppresses MouseLeftButtonDown and MouseLeftButtonDown bubbling events raised by the Button or its composite elements in favor of capturing the mouse and raising a Click event that is always raised by the Button itself."

Seems odd that MouseLeftButtonDown is mentioned twice in this sentence, should one of those be MouseLeftButtonUp? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc1b67b8-776a-6753-bc9e-92b5ddcf6be4
* Version Independent ID: 9a75a21c-db2e-a96f-41c0-28d445969f07
* Content: [Preview Events](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/preview-events)
* Content Source: [docs/framework/wpf/advanced/preview-events.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/preview-events.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Yes, it should be MouseRightButtonDown, @martingbrown. Would you like to submit a pull request to make the change, as well as to add "the" before MouseLeftButtonDown?
