### ISSUE TITLE
MS C# Programming Guide.PDF

### ISSUE THREAD

**Issue by baconblue** [dotnet/docs#10183]
Downloaded the MS C# PDF, (note it is UNTITLED with no file extension and does not find its way to my download folder) PDF will not open in MS Edge (or Word any other suitable app) Edge displays the path of the PDF on my PC - as if it were a URL and then tells me it cannot be found (of course). The MS pdf file is reported as being168Kb. Am logged in as elevated single user with a password not a pin - NOT in MS account as I believed this may be the cause of the problem. Have the latest Win10 version and all updates, all drivers are the latest, I am not on a network, its a single user single account machine, I am fairly competent technically and have used CPM, MS since DOS v1 thru win1,2,3,3.11,95,98,XP pro, Win 8.1 and now v10. - both as a C, C++, programmer and a network supervisor well used to installing and debugging  programs, applications & hardware. (v7,8 & vista were rubbish and thus avoided on my own PCs)
Have tried unblocking, changing ownership and changing attributes. Have downloaded the PDF multiple times but still no joy. 
I have since downloaded other PDF's with no problems - it this MS one which is problematic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Sorry @baconblue but I can't repro this issue. When I click on https://docs.microsoft.com/en-us/dotnet/opbuildpdf/csharp/programming-guide/toc.pdf?branch=live, the PDF file opens fine for me on Edge.

![image](https://user-images.githubusercontent.com/12971179/51870398-57b98f80-2308-11e9-9bd0-8ddc999b1a57.png)

If you're still having issues, please let us know and I'll transfer this issue to the https://github.com/Microsoftdocs/feedback repo to have our engineering team to look at this.
