### ISSUE TITLE
El artículo olvida mencionar que Parse y TryParse fallan cuando la cadena está vacía

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#10181]
@AlbertoPoblacion commented on [Sun Jan 27 2019](https://github.com/dotnet/docs.es-es/issues/78)

En la sección "ejemplo" se indican varios casos en los que fallan el Parse y TryParse debido a la presencia de espacios en blanco superfluos. Sin embargo, olvidan mencionar que también fallan cuando la cadena está vacía. He visto múltiples preguntas en los foros escritas por programadores noveles que se sorprendían al encontrar un error al aplicar el Parse o TryParse sobre el contenido de una caja de texto que se encontraba vacía. Al parecer, esperaban que el resultado fuera un cero en lugar de una excepción.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f91931f7-35de-15e0-4c20-53a3fa9246ec
* Version Independent ID: d9031bdc-890a-d5bd-c1ed-d767b0e27890
* Content: [Procedimiento Convertir una cadena en un número: Guía de programación de C#](https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/types/how-to-convert-a-string-to-a-number)
* Content Source: [docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hi team,
Here's a rough translation of the issue reported by the user: 

> In the "example" section, several cases are indicated in which the Parse and TryParse fail due to the presence of superfluous white spaces. However, they forget to mention that they also fail when the chain is empty. I have seen multiple questions in the forums written by novice programmers who were surprised to find an error when applying the Parse or TryParse on the contents of a text box that was empty. Apparently, they expected the result to be a zero instead of an exception.

Thanks!

**Comment by rpetrusha** [comment]
This is an important thing to add to the topic. The code is also fragmented, which makes it confusing. I've scheduled it for this sprint.
