### ISSUE TITLE
**SHA1 hash algorithm replacement**

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10196]
Replace mentions of using SHA1 with SHA256 (especially), SHA284, or SHA512. This involves:
- Conceptual documentation. 
- Reference documentation. This includes a note in the SHA1 documentation that it is not recommended, and that the suggested replacement is SHA256.
- Code. Usage of SHA1 should be replaced except for code for the SHA1 type in the managed reference documentation.

**Comment by rpetrusha** [comment]
This change involves selective replacement of SHA1 in conceptual and reference documentation, as well as in samples.

**Comment by tdykstra** [comment]
There were separate issues for MD5 (#10198) and SHA1, but the SHA1 work is being done for the MD5 issue, so I'm changing the MD5 issue to be for both and closing this one.
