### ISSUE TITLE
**Sample cleanup: RC2, DES, TripleDES, and Rijndael**

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10199]
Samples should not use any of the following cryptography types:
- [RC2](https://docs.microsoft.com/dotnet/api/system.security.cryptography.rc2)
- [DES](https://docs.microsoft.com/dotnet/api/system.security.cryptography.des)
- [TripleDES](https://docs.microsoft.com/dotnet/api/system.security.cryptography.tripledes)
- [Rijndael](https://docs.microsoft.com/dotnet/api/system.security.cryptography.rijndael)

As an alternative, they should reference [Aes](https://docs.microsoft.com/dotnet/api/system.security.cryptography.aes).

**Comment by mairaw** [comment]
@tdykstra as I'm going through the APIs for the .NET Interactive work, I still see examples using these algorithms

e.g. https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledes?view=net-5.0 

Have you decided to keep the examples on the API docs? /cc @bartonjs

**Comment by tdykstra** [comment]
In most cases, the samples that are illustrating the API itself, e.g., TripleDES sample for TripleDES API, were left in place. Usage of TripleDES in a sample illustrating a different API was removed.
