### ISSUE TITLE
Can't DIM AS DataRow

### ISSUE THREAD

**Issue by rlaracuente** [dotnet/docs#10191]
VBA doesn't seem to recognize this type and throws a compile error:

"User-defined type not defined"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 038abfac-5390-1746-2472-8d6eda0e0504
* Version Independent ID: 0de0c149-06ce-1931-697f-bbbd6f0bffe4
* Content: [Viewing Data in a DataTable](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/viewing-data-in-a-datatable#feedback)
* Content Source: [docs/framework/data/adonet/dataset-datatable-dataview/viewing-data-in-a-datatable.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/dataset-datatable-dataview/viewing-data-in-a-datatable.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for your feedback @rlaracuente but the content shown here is not VBA code but Visual Basic .NET. For this reason, I'm closing this issue.
