### ISSUE TITLE
**MD5 and SHA1 Hash algorithm replacement**

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10198]
Replace mentions of using MD5 or SHA1 with SHA256, SHA284, or SHA512. This involves:
- Conceptual documentation.
- Reference documentation. This includes a note in the MD5 and SHA1 documentation that it is not recommended, and that the suggested replacement is SHA256, etc.
- Code. Usage of MD5 or SHA1 should be replaced except for code for the MD5 and SHA1 types in the managed reference documentation.

**Comment by Thraka** [comment]
## Articles

Here is a list of articles that have the word `MD5` or `SHA1`.

- [ ] docs\csharp\language-reference\compiler-options\listed-alphabetically.md
- [ ] docs\csharp\language-reference\compiler-options\listed-by-category.md
- [ ] docs\framework\configure-apps\file-schema\runtime\appcontextswitchoverrides-element.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-element-of-nettcpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-element-of-ws2007federationhttpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-element-of-wsfederationhttpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-of-ws2007httpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-of-wsdualhttpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\message-of-wshttpbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\msmqtransportsecurity.md
- [ ] docs\framework\configure-apps\file-schema\wcf\netmsmqbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\security-of-custombinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\security-of-msmqintegrationbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\security-of-netmsmqbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\transport-of-msmqintegrationbinding.md
- [ ] docs\framework\configure-apps\file-schema\wcf\transport-of-netmsmqbinding.md
- [ ] docs\framework\configure-apps\map-algorithm-names-to-cryptography-classes.md
- [ ] docs\framework\migration-guide\retargeting\4.0-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.0-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.0-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.5-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.5-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.5-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.5.1-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.5.1-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.5.1-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.5.2-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.5.2-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.5.2-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.6-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.6-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.6-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.6.1-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.6.1-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.6.1-4.7.md
- [ ] docs\framework\migration-guide\retargeting\4.6.2-4.7.1.md
- [ ] docs\framework\migration-guide\retargeting\4.6.2-4.7.2.md
- [ ] docs\framework\migration-guide\retargeting\4.6.2-4.7.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.6.1.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.6.2.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.6.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.7.1.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.7.2.md
- [ ] docs\framework\migration-guide\runtime\4.0-4.7.md
- [ ] docs\framework\migration-guide\runtime\4.5-4.6.1.md
- [ ] docs\framework\migration-guide\runtime\4.5-4.6.md
- [ ] docs\framework\migration-guide\runtime\4.5-4.7.1.md
- [ ] docs\framework\migration-guide\runtime\4.5-4.7.2.md
- [ ] docs\framework\migration-guide\runtime\4.5-4.7.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.6.1.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.6.2.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.6.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.7.1.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.7.2.md
- [ ] docs\framework\migration-guide\runtime\4.5.1-4.7.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.6.1.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.6.2.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.6.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.7.1.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.7.2.md
- [ ] docs\framework\migration-guide\runtime\4.5.2-4.7.md
- [ ] docs\framework\migration-guide\mitigation-wcf-services-and-certificate-authentication.md
- [ ] docs\framework\migration-guide\net-framework-4-migration-issues.md
- [ ] docs\framework\network-programming\how-to-assign-user-information-to-group-connections.md
- [ ] docs\framework\network-programming\peer-names-and-pnrp-ids.md
- [ ] docs\framework\tools\al-exe-assembly-linker.md
- [ ] docs\framework\tools\certmgr-exe-certificate-manager-tool.md
- [ ] docs\framework\tools\mage-exe-manifest-generation-and-editing-tool.md
- [ ] docs\framework\tools\mageui-exe-manifest-generation-and-editing-tool-graphical-client.md
- [ ] docs\framework\tools\signtool-exe.md
- [ ] docs\framework\unmanaged-api\debugging\icordebugmergedassemblyrecord-getpublickeytoken-method.md
- [ ] docs\framework\wcf\diagnostics\exceptions-reference\identitymodel-exceptions.md
- [ ] docs\framework\wcf\extending\specifying-a-custom-crypto-algorithm.md
- [ ] docs\framework\wcf\feature-details\data-contract-schema-reference.md
- [ ] docs\framework\wcf\feature-details\http-transport-security.md
- [ ] docs\framework\wcf\feature-details\securing-messages-using-transport-security.md
- [ ] docs\framework\wcf\feature-details\transaction-protocols-version-1-0.md
- [ ] docs\framework\wcf\feature-details\transaction-protocols.md
- [ ] docs\framework\wcf\feature-details\wcf-security-terminology.md
- [ ] docs\framework\wcf\samples\authorization-policy.md
- [ ] docs\framework\wcf\samples\custom-binding-security.md
- [ ] docs\framework\wcf\samples\custom-token.md
- [ ] docs\framework\wcf\samples\discovery-security-sample.md
- [ ] docs\framework\wcf\samples\membership-and-role-provider.md
- [ ] docs\framework\wcf\samples\message-security-anonymous.md
- [ ] docs\framework\wcf\samples\message-security-certificate.md
- [ ] docs\framework\wcf\samples\message-security-over-message-queuing.md
- [ ] docs\framework\wcf\samples\message-security-user-name.md
- [ ] docs\framework\wcf\samples\saml-token-provider.md
- [ ] docs\framework\wcf\samples\supporting-tokens.md
- [ ] docs\framework\wcf\samples\token-authenticator.md
- [ ] docs\framework\wcf\samples\token-provider.md
- [ ] docs\framework\wcf\samples\trusted-facade-service.md
- [ ] docs\framework\wcf\samples\user-name-password-validator.md
- [ ] docs\framework\wcf\samples\x-509-certificate-validator.md
- [ ] docs\framework\whats-new\index.md
- [ ] docs\standard\security\cryptographic-services.md
- [ ] docs\standard\security\cryptographic-signatures.md
- [ ] docs\standard\security\ensuring-data-integrity-with-hash-codes.md
- [ ] docs\visual-basic\reference\command-line-compiler\compiler-options-listed-alphabetically.md
- [ ] docs\visual-basic\reference\command-line-compiler\compiler-options-listed-by-category.md

**Comment by tdykstra** [comment]
These are the article and API ref lists from the original comment, preserved here in a separate comment to make the original comment easier to work with while tracking work on snippets.

## Articles

- [x] docs\csharp\language-reference\compiler-options\listed-alphabetically.md
- [x] docs\csharp\language-reference\compiler-options\listed-by-category.md
- [x] docs\framework\configure-apps\file-schema\runtime\appcontextswitchoverrides-element.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-element-of-nettcpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-element-of-ws2007federationhttpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-element-of-wsfederationhttpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-of-ws2007httpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-of-wsdualhttpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\message-of-wshttpbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\msmqtransportsecurity.md
- [x] docs\framework\configure-apps\file-schema\wcf\netmsmqbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\security-of-custombinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\security-of-msmqintegrationbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\security-of-netmsmqbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\transport-of-msmqintegrationbinding.md
- [x] docs\framework\configure-apps\file-schema\wcf\transport-of-netmsmqbinding.md
- [x] docs\framework\configure-apps\map-algorithm-names-to-cryptography-classes.md
- [x] docs\framework\migration-guide\retargeting\4.0-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.0-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.0-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.5-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.5-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.5-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.5.1-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.5.1-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.5.1-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.5.2-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.5.2-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.5.2-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.6-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.6-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.6-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.6.1-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.6.1-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.6.1-4.7.md
- [x] docs\framework\migration-guide\retargeting\4.6.2-4.7.1.md
- [x] docs\framework\migration-guide\retargeting\4.6.2-4.7.2.md
- [x] docs\framework\migration-guide\retargeting\4.6.2-4.7.md
- [x] docs\framework\migration-guide\runtime\4.0-4.6.1.md
- [x] docs\framework\migration-guide\runtime\4.0-4.6.2.md
- [x] docs\framework\migration-guide\runtime\4.0-4.6.md
- [x] docs\framework\migration-guide\runtime\4.0-4.7.1.md
- [x] docs\framework\migration-guide\runtime\4.0-4.7.2.md
- [x] docs\framework\migration-guide\runtime\4.0-4.7.md
- [x] docs\framework\migration-guide\runtime\4.5-4.6.1.md
- [x] docs\framework\migration-guide\runtime\4.5-4.6.md
- [x] docs\framework\migration-guide\runtime\4.5-4.7.1.md
- [x] docs\framework\migration-guide\runtime\4.5-4.7.2.md
- [x] docs\framework\migration-guide\runtime\4.5-4.7.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.6.1.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.6.2.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.6.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.7.1.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.7.2.md
- [x] docs\framework\migration-guide\runtime\4.5.1-4.7.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.6.1.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.6.2.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.6.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.7.1.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.7.2.md
- [x] docs\framework\migration-guide\runtime\4.5.2-4.7.md
- [x] docs\framework\migration-guide\mitigation-wcf-services-and-certificate-authentication.md
- [x] docs\framework\migration-guide\net-framework-4-migration-issues.md
- [x] docs\framework\network-programming\how-to-assign-user-information-to-group-connections.md
- [x] docs\framework\network-programming\peer-names-and-pnrp-ids.md
- [x] docs\framework\tools\al-exe-assembly-linker.md
- [x] docs\framework\tools\certmgr-exe-certificate-manager-tool.md
- [x] docs\framework\tools\mage-exe-manifest-generation-and-editing-tool.md
- [x] docs\framework\tools\mageui-exe-manifest-generation-and-editing-tool-graphical-client.md
- [x] docs\framework\tools\signtool-exe.md
- [x] docs\framework\unmanaged-api\debugging\icordebugmergedassemblyrecord-getpublickeytoken-method.md
- [x] docs\framework\wcf\diagnostics\exceptions-reference\identitymodel-exceptions.md
- [x] docs\framework\wcf\extending\specifying-a-custom-crypto-algorithm.md
- [x] docs\framework\wcf\feature-details\data-contract-schema-reference.md
- [x] docs\framework\wcf\feature-details\http-transport-security.md
- [x] docs\framework\wcf\feature-details\securing-messages-using-transport-security.md
- [x] docs\framework\wcf\feature-details\transaction-protocols-version-1-0.md
- [x] docs\framework\wcf\feature-details\transaction-protocols.md
- [x] docs\framework\wcf\feature-details\wcf-security-terminology.md
- [x] docs\framework\wcf\samples\authorization-policy.md
- [x] docs\framework\wcf\samples\custom-binding-security.md
- [x] docs\framework\wcf\samples\custom-token.md
- [x] docs\framework\wcf\samples\discovery-security-sample.md
- [x] docs\framework\wcf\samples\membership-and-role-provider.md
- [x] docs\framework\wcf\samples\message-security-anonymous.md
- [x] docs\framework\wcf\samples\message-security-certificate.md
- [x] docs\framework\wcf\samples\message-security-over-message-queuing.md
- [x] docs\framework\wcf\samples\message-security-user-name.md
- [x] docs\framework\wcf\samples\saml-token-provider.md
- [x] docs\framework\wcf\samples\supporting-tokens.md
- [x] docs\framework\wcf\samples\token-authenticator.md
- [x] docs\framework\wcf\samples\token-provider.md
- [x] docs\framework\wcf\samples\trusted-facade-service.md
- [x] docs\framework\wcf\samples\user-name-password-validator.md
- [x] docs\framework\wcf\samples\x-509-certificate-validator.md
- [x] docs\framework\whats-new\index.md
- [x] docs\standard\security\cryptographic-services.md
- [x] docs\standard\security\cryptographic-signatures.md
- [x] docs\standard\security\ensuring-data-integrity-with-hash-codes.md
- [x] docs\visual-basic\reference\command-line-compiler\compiler-options-listed-alphabetically.md
- [x] docs\visual-basic\reference\command-line-compiler\compiler-options-listed-by-category.md

## API
- [x] xml\FrameworksIndex\dotnet-plat-ext-2.1.xml
- [x] xml\FrameworksIndex\dotnet-plat-ext-2.2.xml
- [x] xml\FrameworksIndex\dotnet-plat-ext-3.0.xml
- [x] xml\FrameworksIndex\dotnet-uwp-10.0.xml
- [x] xml\FrameworksIndex\netcore-1.0.xml
- [x] xml\FrameworksIndex\netcore-1.1.xml
- [x] xml\FrameworksIndex\netcore-2.0.xml
- [x] xml\FrameworksIndex\netcore-2.1.xml
- [x] xml\FrameworksIndex\netcore-2.2.xml
- [x] xml\FrameworksIndex\netcore-3.0.xml
- [x] xml\FrameworksIndex\netframework-1.1.xml
- [x] xml\FrameworksIndex\netframework-2.0.xml
- [x] xml\FrameworksIndex\netframework-3.0.xml
- [x] xml\FrameworksIndex\netframework-3.5.xml
- [x] xml\FrameworksIndex\netframework-4.0.xml
- [x] xml\FrameworksIndex\netframework-4.5.1.xml
- [x] xml\FrameworksIndex\netframework-4.5.2.xml
- [x] xml\FrameworksIndex\netframework-4.5.xml
- [x] xml\FrameworksIndex\netframework-4.6.1.xml
- [x] xml\FrameworksIndex\netframework-4.6.2.xml
- [x] xml\FrameworksIndex\netframework-4.6.xml
- [x] xml\FrameworksIndex\netframework-4.7.1.xml
- [x] xml\FrameworksIndex\netframework-4.7.2.xml
- [x] xml\FrameworksIndex\netframework-4.7.xml
- [x] xml\FrameworksIndex\netframework-4.8.xml
- [x] xml\FrameworksIndex\netstandard-1.1.xml
- [x] xml\FrameworksIndex\netstandard-1.2.xml
- [x] xml\FrameworksIndex\netstandard-1.3.xml
- [x] xml\FrameworksIndex\netstandard-1.4.xml
- [x] xml\FrameworksIndex\netstandard-1.6.xml
- [x] xml\FrameworksIndex\netstandard-2.0.xml
- [x] xml\FrameworksIndex\xamarinandroid-7.1.xml
- [x] xml\FrameworksIndex\xamarinios-10.8.xml
- [x] xml\FrameworksIndex\xamarinmac-3.0.xml
- [x] xml\Microsoft.Build.Tasks.Deployment.ManifestUtilities\BaseReference.xml
- [x] xml\Microsoft.Build.Tasks.Deployment.ManifestUtilities\SecurityUtilities.xml
- [x] xml\Mono.Security.Interface\CipherSuiteCode.xml
- [x] xml\Mono.Security.Interface\HashAlgorithmType.xml
- [x] xml\System.CodeDom\CodeChecksumPragma.xml
- [x] xml\System.Configuration.Assemblies\AssemblyHash.xml
- [x] xml\System.Configuration.Assemblies\AssemblyHashAlgorithm.xml
- [x] xml\System.IdentityModel\RsaEncryptionCookieTransform.xml
- [x] xml\System.IdentityModel\RsaSignatureCookieTransform.xml
- [x] xml\System.IdentityModel.Tokens\ComputedKeyAlgorithms.xml
- [x] xml\System.IdentityModel.Tokens\InMemorySymmetricSecurityKey.xml
- [x] xml\System.IdentityModel.Tokens\RsaSecurityKey.xml
- [x] xml\System.IdentityModel.Tokens\SecurityAlgorithms.xml
- [x] xml\System.IdentityModel.Tokens\SymmetricSecurityKey.xml
- [x] xml\System.IdentityModel.Tokens\X509AsymmetricSecurityKey.xml
- [x] xml\System.IO.Packaging\PackageDigitalSignatureManager.xml
- [x] xml\System.Messaging\DefaultPropertiesToSend.xml
- [x] xml\System.Messaging\HashAlgorithm.xml
- [x] xml\System.Messaging\Message.xml
- [x] xml\System.Messaging\MessageQueue.xml
- [x] xml\System.Net\HttpRequestHeader.xml
- [x] xml\System.Net\HttpResponseHeader.xml
- [x] xml\System.Net.Http.Headers\HttpContentHeaders.xml
- [x] xml\System.Reflection\Assembly.xml
- [x] xml\System.Reflection\AssemblyHashAlgorithm.xml
- [x] xml\System.Reflection\AssemblyName.xml
- [x] xml\System.Runtime.Intrinsics.Arm.Arm64\Sha1.xml
- [x] xml\System.Security.Authentication\HashAlgorithmType.xml
- [x] xml\System.Security.Cryptography\CngAlgorithm.xml
- [x] xml\System.Security.Cryptography\CryptoConfig.xml
- [x] xml\System.Security.Cryptography\DSACryptoServiceProvider.xml
- [x] xml\System.Security.Cryptography\DSASignatureFormatter.xml
- [x] xml\System.Security.Cryptography\ECDiffieHellmanCng.xml
- [x] xml\System.Security.Cryptography\ECDsaCng.xml
- [x] xml\System.Security.Cryptography\HashAlgorithm.xml
- [x] xml\System.Security.Cryptography\HashAlgorithmName.xml
- [x] xml\System.Security.Cryptography\HMAC.xml
- [x] xml\System.Security.Cryptography\HMACMD5.xml
- [x] xml\System.Security.Cryptography\HMACRIPEMD160.xml
- [x] xml\System.Security.Cryptography\HMACSHA1.xml
- [x] xml\System.Security.Cryptography\KeyedHashAlgorithm.xml
- [x] xml\System.Security.Cryptography\MD5.xml
- [x] xml\System.Security.Cryptography\MD5Cng.xml
- [x] xml\System.Security.Cryptography\MD5CryptoServiceProvider.xml
- [x] xml\System.Security.Cryptography\PKCS1MaskGenerationMethod.xml
- [x] xml\System.Security.Cryptography\Rfc2898DeriveBytes.xml
- [x] xml\System.Security.Cryptography\RIPEMD160.xml
- [x] xml\System.Security.Cryptography\RIPEMD160Managed.xml
- [x] xml\System.Security.Cryptography\RSACryptoServiceProvider.xml
- [x] xml\System.Security.Cryptography\RSAEncryptionPadding.xml
- [x] xml\System.Security.Cryptography\SHA1.xml
- [x] xml\System.Security.Cryptography\SHA1Cng.xml
- [x] xml\System.Security.Cryptography\SHA1CryptoServiceProvider.xml
- [x] xml\System.Security.Cryptography\SHA1Managed.xml
- [x] xml\System.Security.Cryptography\SignatureDescription.xml
- [x] xml\System.Security.Cryptography.Pkcs\CmsSigner.xml
- [x] xml\System.Security.Cryptography.X509Certificates\X509Certificate.xml
- [x] xml\System.Security.Cryptography.X509Certificates\X509Certificate2.xml
- [x] xml\System.Security.Cryptography.X509Certificates\X509ChainStatusFlags.xml
- [x] xml\System.Security.Cryptography.X509Certificates\X509SubjectKeyIdentifierHashAlgorithm.xml
- [x] xml\System.Security.Cryptography.Xml\Reference.xml
- [x] xml\System.Security.Cryptography.Xml\SignedInfo.xml
- [x] xml\System.Security.Cryptography.Xml\SignedXml.xml
- [x] xml\System.Security.Policy\Hash.xml
- [x] xml\System.ServiceModel\MsmqSecureHashAlgorithm.xml
- [x] xml\System.ServiceModel\MsmqTransportSecurity.xml
- [x] xml\System.ServiceModel.Security\Basic128SecurityAlgorithmSuite.xml
- [x] xml\System.ServiceModel.Security\Basic192SecurityAlgorithmSuite.xml
- [x] xml\System.ServiceModel.Security\Basic256SecurityAlgorithmSuite.xml
- [x] xml\System.ServiceModel.Security\SecurityKeyEntropyMode.xml
- [x] xml\System.ServiceModel.Security\TripleDesSecurityAlgorithmSuite.xml
- [x] xml\System.Web\HttpWorkerRequest.xml
- [x] xml\System.Web.Configuration\AuthenticationSection.xml
- [x] xml\System.Web.Configuration\FormsAuthenticationConfiguration.xml
- [x] xml\System.Web.Configuration\FormsAuthenticationCredentials.xml
- [x] xml\System.Web.Configuration\FormsAuthenticationUser.xml
- [x] xml\System.Web.Configuration\FormsAuthPasswordFormat.xml
- [x] xml\System.Web.Configuration\MachineKeyCompatibilityMode.xml
- [x] xml\System.Web.Configuration\MachineKeySection.xml
- [x] xml\System.Web.Configuration\MachineKeyValidation.xml
- [x] xml\System.Web.Configuration\MachineKeyValidationConverter.xml
- [x] xml\System.Web.Security\FormsAuthentication.xml
- [x] xml\System.Web.Security\MembershipPasswordFormat.xml
- [x] xml\System.Web.Security\SqlMembershipProvider.xml
- [x] xml\System.Workflow.ComponentModel.Compiler\WorkflowMarkupSourceAttribute.xml
- [x] xml\System.Workflow.Runtime.DebugEngine\IWorkflowDebugger.xml
