### ISSUE TITLE
SEO: Backlinks to a private website

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/docs#10200]
@guardrex, this page was referred by you in https://github.com/aspnet/Docs/issues/10668

In terms of SEO, the references section in this page acts as backlinks pointing to a private profitable website. See the above issue for more details.
These types of links are generating traffic and thus income to the linked website.
The links also drop Microsoft Docs in search engines because it is linking to non-famous or non-widely-recognized websites with a poor page rank.
It's highly recommend removing all such links, see https://moz.com/learn/seo/backlinks for more info about backlinks 

Edit by @Rick-Anderson 	: 5.8K PV, 15 reviews, 93% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829862b0-b51d-d4dd-d770-f875a588384f
* Version Independent ID: 4ab12fcc-7cc1-d40b-b5c4-d145fe25e98e
* Content: [Architectural principles](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/architectural-principles)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/architectural-principles.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/architectural-principles.md)
* Product: **dotnet**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by guardrex** [comment]
Correct, we've been linking to this page in some of our topics for architectural principles coverage.

**Comment by mairaw** [comment]
@ardalis @CESARDELATORRE can you comment on this issue?

Also, for SEO improvements, we'd need a better title for this page to make it rank better. Architecture principles seems a weak title if there are no additional keywords.

**Comment by ardalis** [comment]
DevIQ is a community reference site with definitions and examples for a ton of principles, patterns, and practices. Its reference section is separate from the home page and training courses site and predates it by many years. There are no third-party ads on the site and I often link to it from content I author as a quick way to provide readers with additional information on a general software development topic. In most cases, it's rare that Microsoft-owned content covers the topic as succinctly and at the time when I was authoring the docs links to things like Wikipedia were actively discouraged.

**Comment by Rick-Anderson** [comment]
This is a somewhat opinionated article. I'd be inclined to remove PI. Abstracting the DB when you know you're using SQL Azure can lead to unnecessarily complicated code.

**Comment by ardalis** [comment]
PI isn’t about abstracting the database, but about keeping the model decoupled (ie POCOs).

**Comment by Rick-Anderson** [comment]
Then is show say so:
(PI) refers to types that need to be persisted, **but whose code is unaffected by the choice of persistence technology**. Such types in .NET are sometimes referred to as Plain Old CLR Objects (POCOs), because they do not need to inherit from a particular base class or implement a particular interface. **Persistence ignorance is valuable because it allows the same business model to be persisted in multiple ways,** offering additional flexibility to the application. Persistence choices might change over time, **from one database technology to another,**

**Comment by Rick-Anderson** [comment]
Fixed via #10518
