### ISSUE TITLE
Make sure samples and guidance use MAC with symmetric encryption, in Encrypt-then-MAC sequence

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10207]
Always use ETM

**Comment by rpetrusha** [comment]
@bartonjs, this was one of the to do items from our security review meeting last year, but I'm not sure that my note is correct, and ETM doesn't correspond to a [padding mode]https://docs.microsoft.com/dotnet/api/system.security.cryptography.paddingmode).  Can you help?

**Comment by bartonjs** [comment]
"EtM" is "Encrypt then MAC".  So it's about combining two operations, in the correct way.

Partially it just means making sure we're consistent in examples that we don't do "E&M" (Encrypt and MAC), "MtE" (MAC then Encrypt), "EtD" (Encrypt then Digest), "D&E" (Digest and Encrypt) or "DtE" (Digest then Encrypt).  It's also that we need to be sure any topic/concept pages provide the right guidance around symmetric encryption (i.e. that it should be combined with a MAC in the EtM paradigm).

**Comment by tdykstra** [comment]
Closing per discussion with @bartonjs on 6/25 and incorporating into #10211
