### ISSUE TITLE
ICU libraries link is malformed

### ISSUE THREAD

**Issue by francocorreasosa** [dotnet/docs#10216]
It links to https://github.com/dotnet/docs/issues/http%22//icu-project.org and it should link to http://icu-project.org

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you for your feedback @francocorreasosa.

Would you like to submit a fix for this? Here's a topic on how to do that:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
