### ISSUE TITLE
Incorrect Debugging 

### ISSUE THREAD

**Issue by DeEpicDestr0yer** [dotnet/docs#10231]
I was using VB in computer class and for most of the class, the program was working very well I had no complaint. However, when the class was ending VB decided not to work correctly and kept on debugging the original copy, not the edited one. because of this issue, I have only scored 84% when I ham a 90s student. i am very disappointed and i hope this problem will be resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675b0c08-6b7f-b01b-4b1a-eda4618d6430
* Version Independent ID: db682cf0-c8e9-a054-7b24-3cc19aaf0a98
* Content: [Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/#feedback)
* Content Source: [docs/visual-basic/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
I am very sorry this happened. 

What were you using to edit your code? Visual Studio Code or Visual Studio full version?

**Comment by mairaw** [comment]
Closing due to the lack of response.
