### ISSUE TITLE
Something wrong with the date of this article.

### ISSUE THREAD

**Issue by PerryCodes** [dotnet/docs#10238]
An article that revolves around SQL Server 2005?  That wouldn't have been written on 07/19/2015.  What happened here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f8852e-4df3-d3ff-174a-86182b88c79d
* Version Independent ID: 09358ac9-475e-d3f0-7f04-10fa5e9ad31b
* Content: [Adding Printable Reports to Visual Studio Applications](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/printing/adding-printable-reports-to-visual-studio-applications)
* Content Source: [docs/visual-basic/developing-apps/printing/adding-printable-reports-to-visual-studio-applications.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/printing/adding-printable-reports-to-visual-studio-applications.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Potapy4** [comment]
Good catch! But it seems to be correct - because SQL Server Reporting Services was added in SQL Server 2005 and, of course, in future releases. I think we can remove this note block from the article so as not to confuse the readers

@mairaw @rpetrusha

**Comment by PerryCodes** [comment]
Thanks!

**Comment by Thraka** [comment]
@KathleenDollard I think we should remove this note. I don't think it's worth pointing out.

**Comment by mairaw** [comment]
Let's remove it! Also, to answer @PerryCodes question about date: the date shown here was an arbitrary date we had to pick when we migrated the content from MSDN to docs. So they're not super accurate for content that hasn't been revised since the migration (all changes done to this topic were global changes like metadata updates, etc.)
