### ISSUE TITLE
Document local tools

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#10245]
We have documentation for global tool installation, which also covers tool-path tools. We need to add documentation for local tools and change some titles and look at the tools story.

**Comment by Thraka** [comment]
Meeting with PU on Monday which pushes this to Aug sprint

**Comment by wli3** [comment]
Here is the "raw" document https://github.com/dotnet/cli/issues/10288

**Comment by tdykstra** [comment]
Closing this, as the issues directly related to local tools are done. Two related issues are outstanding:

* #16895 (add CLI to dependencies article) will be closed by #17245
* #16901 (salvage useful parts of extensibility article) will be addressed when #gewarren adds the content identified as still useful to [Customize the build](https://review.docs.microsoft.com/en-us/dotnet/core/project-sdk/overview?branch=master#customize-the-build)
