### ISSUE TITLE
Exclude glob is inaccurate

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#10249]
In [Default compilation includes in .NET Core projects](https://docs.microsoft.com/zh-cn/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects) section, it says the exclude globs are `**/*.user; **/*.*proj; **/*.sln; **/*.vssscc`.

Actually it also excludes `$(BaseOutputPath)/**` (*bin* **by default**) and `$(BaseIntermediateOutputPath)/**` (*obj* **by default**). src is [here](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L25).

I also recommend adding a hint that all of them can be reffered by `$(DefaultItemExcludes)` so that customize excluding would be easier.

And I don't know whether the hyphen in *Remove glob* of *None* is by design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for reporting this. I can fix this up pretty fast.
