### ISSUE TITLE
Error in the code example

### ISSUE THREAD

**Issue by mekomlusa** [dotnet/docs#10242]
First of all, thank you so much for providing the code example. As a newbie in C# I had a hard time trying to get the manufacturer information from image EXIF meta, and the code snippet provided here is a great starting point. However, this piece of code (checking manufacturer) seems to be working for images taken by iOS only. When I tested it on an image taken by OnePlus, it's not returning the string as expected. That's because the code currently has `string manufacturer = encoding.GetString(propItems[1].Value);`. Manufacturer information **does not** always shows as the first item in the `PropertyItems` list. It's associated with Id 271 though. So I think the code should be updated as `string manufacturer = encoding.GetString(image.GetPropertyItem(271).Value);`. I was able to see the manufacturer string of OnePlus images correctly then.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bc83945-4821-c06f-850b-cb53066c4164
* Version Independent ID: eb79d9a0-ed56-3989-c7e5-b9ddeef04fbb
* Content: [How to: Read Image Metadata](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-read-image-metadata)
* Content Source: [docs/framework/winforms/advanced/how-to-read-image-metadata.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-read-image-metadata.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @mekomlusa. Let me test your suggestion and we can get that implemented if it works.

**Comment by briangithex** [comment]
To add some supporting documentation for mekomlusa's correction request:

According to the EXIF spec ( https://www.exif.org/Exif2-2.PDF ), "Note that field Interoperability shall be recorded in sequence starting from the smallest tag number. There is no stipulation regarding the order or position of tag value (Value) recording. "

Also according to the spec, 271 (10F.H) is the correct tag for returning the "Make" (i.e., manufacturer) field.

So, assuming the suggestion works (I did not test it), it should be reliable.

**Comment by mairaw** [comment]
I'm having to move this to the backlog because of other priorities at the moment. Apologies on that.
