### ISSUE TITLE
the code of the second example is incorrect,

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#10258]
@hmuschett commented on [Thu Jan 31 2019](https://github.com/dotnet/docs.es-es/issues/80)

the code of the second example is incorrect, it has the same sentence as the first code

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 433a56c8-1c93-32fb-eb1d-8395a9760c65
* Version Independent ID: e3f35410-f243-4309-1436-89ade7a34d19
* Content: [Objetos: Guía de programación de C#](https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/classes-and-structs/objects)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/objects.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/programming-guide/classes-and-structs/objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@hmuschett commented on [Thu Jan 31 2019](https://github.com/dotnet/docs.es-es/issues/80#issuecomment-459464023)

el codigo del segundo ejemplo hace tiene  el mismo codigo que el el primero solo le cambian el nombre a los objetos. al final el comportamiento es el mismo

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported by the user.

Thanks!

**Comment by BillWagner** [comment]
The two samples are different because the `Person` type is a `class` in the first example, and a `struct` in the second example. The examples show that the behavior of assignment is different for `struct` and `class` types. 

I recommend closing this.

**Comment by dacruz007** [comment]
I also followed the tut, couldn't spot the difference in the class and the struct in there. I had to write the code using visual studio code, ran it and it still behaved like a reference type. I think the second code is wrong.

**Comment by imba-tjd** [comment]
@dacruz007 I see no error. `person1` was changed in the first example but remain unchanged in the second example.

**Comment by dacruz007** [comment]
@imba-tjd  In the example, the first object had a class reference. In the second example, it was supposed to be changed to STRUCT in the Person class definition.

**Comment by dacruz007** [comment]
@imba-tjd  You're right, I just had a second look at it again and saw it... tested it also and it behaved differently.
