### ISSUE TITLE
Parameter list of Visual Basic property setter method set_P

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#10252]
Please document in &lt;https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/type-members#set-accessor-declarations&gt; that the parameter list of the implicitly declared `set_P` method has the new value of the property as the last parameter.  This is sort-of implied by CLS Rule 27 in ECMA-335 6th ed. §I.8.11.3, but the rule applies only to CLS-compliant properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2969334-5417-50b9-c5c7-8cdfffde7837
* Version Independent ID: 0af206f7-8ce6-a3a7-c21b-ff99d33f76e5
* Content: [Type Members](https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/type-members#set-accessor-declarations)
* Content Source: [spec/type-members.md](https://github.com/dotnet/vblang/blob/master/spec/type-members.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@KalleOlaviNiemitalo That appears to be covered by the 2nd paragraph in the article you reference above:

> If a parameter list is specified, it must have one member, that member must have no modifiers except ByVal, and its type must be the same as the type of the property. The parameter represents the property value being set. If the parameter is omitted, a parameter named Value is implicitly declared.

Can you elaborate on what you think is missing here?

**Comment by mairaw** [comment]
Closing due to the lack of feedback. @KalleOlaviNiemitalo please let us know if we are missing anything.
