### ISSUE TITLE
Referential transparency and side effects

### ISSUE THREAD

**Issue by gyuwon** [dotnet/docs#10253]
This document says that a referentially transparent expression can be replaced with its output without affecting a program's behavior and also says that it does not have to be pure. I think that two sentences are contradictory. If an expression does not always return same value for same arguments it can't be replaced with its output. It's so clear. And if an expression has side effects it can't be replaced with its output too. Let me explain.

Let's assume some function that returns the length of the output stream.

```fs
let readOutputStreamLength = ...
```

This document defines `addOneToValue` function and we know that it has a side effect because it uses `printfn` function.

```fs
let addOneToValue x = 
    printfn "x is %d" x
    x + 1
```

Consider following program code.

```fs
let x = addOneToValue 1
readOutputStreamLength
```

Given that the output stream is empty before execute the program then the result will be `12`. But if replace `addOneToValue 1` with `2` the result of the program will be `0`. The program's behavior has been changed. That means `addOneToValue` function is referentially opaque. The reason why is that `addOneToValue` function has a side effect. So an expression should be pure to be referentially transparent. 

[The definition of referential transparency in Wikipedia](https://en.wikipedia.org/wiki/Referential_transparency) backs up my opinion.

>  An expression is called referentially transparent if it can be replaced with its corresponding value without changing the program's behavior. **This requires that the expression is pure**, that is to say the expression value must be the same for the same inputs and its evaluation must have no side effects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df55ba4-e543-c31c-ba44-e2ae6e78fd33
* Version Independent ID: c88d5609-718e-3df6-6ae5-613438fd8295
* Content: [Introduction to Functional Programming in F#](https://docs.microsoft.com/en-us/dotnet/fsharp/introduction-to-functional-programming/)
* Content Source: [docs/fsharp/introduction-to-functional-programming/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/introduction-to-functional-programming/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Hmmm, I think you're referring to something different here. The result of `x` will be the same no matter if it is generated by a call to `addOneToValue` or if it were given the value `2`, at least for the given definition of `addOneToValue`. That's what makes it referentially transparent.

In your example, the end result of the _program_ can still be different, because that depends on the output stream. But `x` is still always `2` when it is assigned the result of `addOneToValue 1`.

**Comment by gyuwon** [comment]
Yes, `x` is always `2` but the replacement affects a program's behavior. It violates the definition of referential transparency in the document, right?

> Referential Transparency - Referential Transparency is a property of expressions such that they can be replaced with their output **without affecting a program's behavior**.

So we can't say that `addOneToValue` function is referentially transparent if we follow the definition. And I think the definition has no controversy.

**Comment by cartermp** [comment]
So after re-reading this section, I think there may need to be an adjustment. It depends on what we want to consider referentially transparent.

The definition presented in that Wikipedia article is effectively the same as purity. But the definition of referential transparency doesn't derive from mathematics, it derives from linguistics, where it actually has a different meaning: something is referentially transparent if you can replace one expression with another that refers to the same thing.

You'll also find definitions online where referential transparency is effectively only the first part of purity - that you will get the same output for the same inputs - which means that the expression may be effectful, but the result doesn't depend on those effects. This is more in line with the example given in the article.

So, which is the more correct one? It seems that there's no actually agreed-upon definition. In the context of F#, which is an impure language, perhaps focusing just on getting the same output for the same inputs is a sufficient definition.

**Comment by gyuwon** [comment]
I already knew where referential transparency comes from originally. But it's not important. It's important that the document is self-contradictory. You know that I proved it. It's very easy to make an example that replacement of a function having a side effect affects a program's behavior.

So if you want to say that `addOneToValue` function is that referentially transparent you should change the definition of referential transparency in the document. `addOneToValue` function can be replaced with its output without affecting a program's behavior **in some context not any context**.

However if referential transparency works only in some context, it's useless. We can't get any advantage or satefy form that kind of referential transparency even in F#. We can't predict the outcome of replacement of a function with a side effect.

**Comment by cartermp** [comment]
> It's important that the document is self-contradictory.

Yes, this is why I agreed that it should be adjusted 🙂. When initially writing this article, I likely had a different definition in my head than what was written, which happens from time to time.

What I'm wondering is which definition to adhere to. I don't see much value in the, shall we day, blessed-by-haskell definition of referential transparency. It's simply a property of purity by that definition, and perhaps not worth documenting. The question in my mind is if it's valuable to distinguish between purity and referential transparency in light of the fact that F# is not a pure language.
