### ISSUE TITLE
"--include-source" implies "--include-symbols"

### ISSUE THREAD

**Issue by ugumba** [dotnet/docs#10265]
This documentation should mention that --include-symbols implies --include-symbols, and that the "src" folder is only added to the symbols package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @ugumba. I'm including this fix as part of some updates I'm making to the dotnet pack article.

**Comment by JVimes** [comment]
Sorry if I'm missing something obvious, but why are there two options? I can't see symbols being useful without source, or source being useful without symbols. Found this post searching for the difference.
