### ISSUE TITLE
Mistake in first code listing for the FileFoundArgs class

### ISSUE THREAD

**Issue by karlvonl** [dotnet/docs#10268]
The first listing for the FileFoundArgs class erroneously contains the line:

    public bool CancelRequested { get; set; }

This is erroneous for 2 reasons. 1) The paragraph following it indicates that the class is immutable, but it is clearly mutable since the CancelRequested property has a setter. 2) The same listing appears later in the article in the "Returning Values from Event Subscribers" section, but it claims that the CancelRequested property is newly added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc
* Version Independent ID: d2078536-1ee3-5b60-3872-f2635d245cc2
* Content: [Standard .NET event patterns](https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern)
* Content Source: [docs/csharp/event-pattern.md](https://github.com/dotnet/docs/blob/master/docs/csharp/event-pattern.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out. I've added this to our backlog to update this when we next visit this tutorial.
