### ISSUE TITLE
BuildAndTrainModel Creation code should be updated

### ISSUE THREAD

**Issue by nwiatrek** [dotnet/docs#10267]
The code should be copied over as such to show clarity
 public static void BuildAndTrainModel(IDataView trainingDataView, EstimatorChain&lt;ITransformer&gt; pipeline)
 {

 }
This will ensure that the reader knows that the two values need to be passed in from above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Use ML.NET in a GitHub issue multiclass classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification#extract-and-transform-the-data)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by nwiatrek** [comment]
EstimatorChain<KeyToValueMappingTransformer> as the return type instead of void

**Comment by JRAlexander** [comment]
Thanks for the feedback, @nwiatrek! I'm actually working on updating this tutorial today. You should see changes early next week.
