### ISSUE TITLE
Does not add any value

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#10277]
does not add any additional value as the quality of the model better would be to explain the values returned as well as point to Feature Contribution Calculation and permutation results and the differences between them. like this we have 3 types of validation and none is definitive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4da51a-ec5c-f744-5d10-331a5e8252ba
* Version Independent ID: 4a46d97c-8a37-1cbd-64b5-cf0d075d19be
* Content: [Calculate metrics to evaluate machine learning model quality - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/verify-model-quality-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/verify-model-quality-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/verify-model-quality-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for the feedback, @PeterPann23. I've added this to the backlog and to the ML.NET GitHub project.

**Comment by natke** [comment]
Closing, as we have refactored this article out of the set.
