### ISSUE TITLE
Default globs for Content

### ISSUE THREAD

**Issue by amybingzhao** [dotnet/docs#10272]
On the "[Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)" page, could you add what the default Include, Exclude, and Remove globs are for Content elements?

From our experience with converting projects over to the new project file format, it seems like cshtml files are Content elements by default but it's unclear what else is.

edit by @mairaw: added the topic info below
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@rainersigwald @KathleenDollard @livarcocc can you help with this feedback?

**Comment by rainersigwald** [comment]
No default `Content` glob is set in the .NET Core SDK. However, the ASP.NET Core SDK (`Microsoft.NET.Sdk.Web`) sets some:

* `**\*.cshtml` and `**\*.razor` (in the Razor SDK, specifically)
* `wwwroot\**`, `**\*.config`, and `**\*.json` from Web.ProjectSystem.props.

Ideally, these would be documented in ASP.NET docs somewhere, and linked to from this page with something along the lines of

> SDKs or NuGet packages can change the default inclusions. For example the web sdk adds `Content` items (link).

**Comment by mairaw** [comment]
Thanks @rainersigwald. @Rick-Anderson @scottaddie can we coordinate these changes?

**Comment by scottaddie** [comment]
@mairaw The work is being tracked in the aspnet/AspNetCore.Docs issue linked above. Do you want to close this issue?
