### ISSUE TITLE
example for C# does not work

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#10270]
@MinistrBob commented on [Fri Feb 01 2019](https://github.com/dotnet/docs.ru-ru/issues/168)

I corrected it
if (e.KeyCode == Keys.Return)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: dcd32f6d-4a54-b4a9-643e-1bfa30f98d4d
* Version Independent ID: f42b5de3-7407-4d1c-8504-f07620f57c04
* Content: [Как выполнить Обнаружить, когда нажата клавиша ВВОД](https://docs.microsoft.com/ru-ru/dotnet/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed)
* Content Source: [docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported.

Thanks!

**Comment by gusmally** [comment]
Hi Lisandro,

The current example works for System.Windows.Input.KeyEventArgs, since this is for WPF projects. Seems like you're using System.Windows.Forms.KeyEventArgs, which is for Winforms.

**Comment by mairaw** [comment]
I'm adding some suffix to the WPF and WinForms articles to make the distinction more clear.
Let us know if this didn't solve your issue @MinistrBob.
