### ISSUE TITLE
Unable to create prediction engine

### ISSUE THREAD

**Issue by an31146** [dotnet/docs#10289]
Edit: Can be closed, I was trying a different NaiveBayes predication engine, which doesn't apply here.
---------------
I'm getting the predictionFunction statement in this sample, failing to create the engine with:
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.ML.Data.dll
Can't bind the IDataView column 'PredictedLabel' of type 'Key&lt;U4, 0-1&gt;' to field or property 'Prediction' of type 'System.Boolean'.

Microsoft.ML v0.9.0 / Dotnet CoreApp 2.2.1

Is this a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#create-classes-and-define-paths)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for the update, @an31146. Let us know if you run into other issues.
