### ISSUE TITLE
Provide a more in depth example

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#10282]
This is a fairly academic example. Let's say we had something more complex.

```C#
class FullName
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

And let's say ``Cat`` had a name:

```C#
class Cat
{
    public FullName Name { get; set; }
    // ...
}
```

Methinks that ``Cat.Name`` needs to be initialized prior to being accessed via the *initializer list*, yes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efd6a6a-b52a-f6a2-d98b-f245b55115ff
* Version Independent ID: 95025282-20a0-ded8-c6d2-3b8ffff600c4
* Content: [Object and Collection Initializers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up.  

This is best addressed in the context of non-nullable types for C# 8. This is part of the "correct by construction" story.

**Comment by mwpowellhtx** [comment]
@BillWagner Just seems to me that the whole ``NRT`` issue has been a can of worms, especially for a language that already knows how  to deal with *null* values with operators such as ``??``, ``?.``, ``ReferenceEquals``, and so forth. I've even caught glimpses of ``NRT`` working its way out in seemingly unrelated discussions, such as during the ongoing *JSON serialization* design review. Case in which, if we're honest, *null* has a valid place in the midst of *JS* code, is stronger than *undefined*, for instance, and so on. Anyway, I think we need more substantive, less academic, examples around these kinds of issues. I'll want that before I am that convinced "null is an issue".

**Comment by BillWagner** [comment]
@mwpowellhtx Great comment!  We agree that `null` is the way to represent a missing value in C#. The value `null` is not the issue.

The issue NRT should address is expressing your design intent: Does your design intend that a variable *might be null* or does it intend for a variable to *never be null*. Both are valid design decisions. NRT lets you express your intent more clearly.

We haven't written the entire story, but we've started to provide background and two tutorials on nullable reference types. Start with [this overview](https://docs.microsoft.com/dotnet/csharp/nullable-references) and continue with the two tutorials referenced at the end of the article. If you have feedback on our current guidance and examples, let us know.

**Comment by mwpowellhtx** [comment]
@BillWagner The words are one thing; but I've yet to see anything but an academic example presented. 
It's not the compiler's job to dictate intent, nor would I trust any compiler to tell me that. And usually one that I can express using the null conditional operators or other language features that exist prior *NRT** being introduced`. I have not changed my mind about that, and would enforce a no-NRT policy in my business if I discovered that was taking place. Neither here nor there for purposes of the discussion, only to suggest that I have seen nothing but confusion consequently. Best case, I think NRT would be a valid analyzer, but that's about it.
