### ISSUE TITLE
Method [Main] Should read Method [Program]

### ISSUE THREAD

**Issue by jmerinoh** [dotnet/docs#10286]
Instruction says: 
Open Program.cs and replace the contents of the `Main` method.
It should read `Program` rather.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Getting started with .NET Core on macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by SurlyMae** [comment]
Hi @jmerinoh - in this case, we are replacing the contents of the `Main` method within the `Program` class. Since the `Main` method is the entry-point to the app, I believe the instructions here are correct.

**Comment by mairaw** [comment]
Indeed, that is correct @SurlyMae. Only the contents of the Main method should be replaced, not the entire Program.cs.
