### ISSUE TITLE
Create a doc describing how to find current issues/fixes

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/docs#1028]
With moving to GitHub, developers have access to the work items for .NET Core, CLR, and many others. However, the issues are spread across many repositories, which makes it difficult for users to easily search for an issue. Often an answer can be found fairly quickly if you're in the right repo, but finding that repo can be a challenge.

I think a document that lists the main technologies (including descriptions of what they include) and a link to the repo would be a great starting point for people who are trying to determine if an issue is known and a possible work around, or if it should be filed.

**Comment by svick** [comment]
Are you talking about something like [the list in this note](https://github.com/dotnet/core#net-core-home)?

**Comment by twsouthwick** [comment]
Yes - something like that, but visible from the docs.microsoft.com/dotnet

**Comment by mairaw** [comment]
Maybe we can tweak this .NET Core introduction topic?
https://docs.microsoft.com/en-us/dotnet/articles/core/index#composition

It already talks about the parts it just not clearly lists them as repos with their names. It's a bit subtle.

**Comment by BillWagner** [comment]
Does this belong on docs.microsoft.com, or on the .NET Foundation home page?

/cc @martinwoodward

**Comment by martinwoodward** [comment]
I think a page on docs.microsoft.com encouraging people to go to GitHub to file issues is a very good thing. That shouldn't be the only way Microsoft's customers can file bugs or log issues though - a Microsoft customer shouldn't have to care what project an issue is in, they should be able to get support for the product they got from Microsoft (i.e. a .NET Core binary in a VS "15")

The full detail of the content to help find the project  probably belongs to the core project with a link to that page from docs.microsoft.com (that is if all the projects needed - reference are indeed open source and are in the .NET Foundation).

**Comment by stevehoag** [comment]
So the problem today is that the only feedback mechanism for docs.microsoft.com is comments, and so far the response rate on comments has been underwhelming. As a hypothetical casual consumer of our docs, asking me to learn the intricacies of GitHub just to file a bug or complaint is a non-starter.

**Comment by martinwoodward** [comment]
So think I'm kinda agreeing with @stevehoag - there should be mechanism for end users of Microsoft products to easily file bugs / issues with products from Microsoft. (And the same is true for other vendors shipping .NET Core). What I don't want to see is "if you find an issue in VS, figure out what code is causing it and go track down the project that it came from and send in a PR to fix it and Microsoft will pull that change from upstream eventually". Microsoft still have to support their own product.

But equally, I would strongly encourage all vendors, especially Microsoft, to also encourage developers to investigate the code behind as I think @BillWagner is suggesting, file issues on GitHub when possible and generally get more involved in the open source community.

**Comment by BillWagner** [comment]
Reading all the comments, how about this for a proposal:

There is a single location on docs.microsoft.com that solicits bugs / issues with .NET products and docs. From there, readers can either:
1. File an issue, and MS folk will triage it and make an issue for the correct team.
2. Explore the list of Open Source repos that are part of the .NET ecosystem, and file an issue at the most likely project.

/cc @richlander 

Can folks respond with a +1, or an alternative?

**Comment by martinwoodward** [comment]
+1 with the caveat of:

1.5 Contact Support if this is a blocking issue or if you are having trouble figuring out what the problem is
1.6 For security bugs, don't forget the [BugBounty program](https://technet.microsoft.com/en-us/mt764065.aspx)

Not sure if this is relevant or not at this level of docs but mentioning it now just in case.

**Comment by rpetrusha** [comment]
+1, with @martinwoodward's additions

**Comment by stevehoag** [comment]
+1 to what Ron said...

**Comment by BillWagner** [comment]
ping @DuncanmaMSFT as this old thread has some interesting thoughts related to GitHub issues on docs.

Removing various docs labels & adding the external label.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
