### ISSUE TITLE
Link to archive.msdn.microsoft.com does not work

### ISSUE THREAD

**Issue by cjkeilig** [dotnet/docs#10293]
The link on the first purple note (goes to http://archive.msdn.microsoft.com/wpfsamples) does not work.

Page:
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/advanced-text-formatting#advanced-text-formatting-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86ab90b-662c-f6ef-9958-f7a27c0dfadb
* Version Independent ID: 8da01b55-70f2-0f5e-5479-3d08c647af62
* Content: [Advanced Text Formatting](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/advanced-text-formatting#advanced-text-formatting-1)
* Content Source: [docs/framework/wpf/advanced/advanced-text-formatting.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/advanced-text-formatting.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Potapy4** [comment]
It seems that now it is moved to GitHub: https://github.com/Microsoft/WPF-Samples

**Comment by mairaw** [comment]
Thanks for the feedback @cjkeilig. I've changed the target link to go to https://github.com/Microsoft/WPF-Samples/tree/master/PerMonitorDPI/TextFormatting.
