### ISSUE TITLE
How does one install fsharpi?

### ISSUE THREAD

**Issue by binil** [dotnet/docs#10295]
Many books and tutorials on F# encourage using `fsharpi`. Please include instructions to install it on the [Get started with F# with the .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line) page.

**Comment by binil** [comment]
I ran across [this issue](https://github.com/Microsoft/visualfsharp/issues/2407) in the tracker. Maybe this is not full implemented yet.

**Comment by mairaw** [comment]
@cartermp can you comment on this request?

**Comment by cartermp** [comment]
I don't think we'll do this here. Since `fsharpi` is the FSI in Mono, you need to install Mono to use it. Since this guide is strictly about .NET Core, it's not applicable.

Soon we'll have `dotnet fsi` supported for .NET Core, which we can include in this guide.

**Comment by ldwrs** [comment]
Any ETA on this?

**Comment by 2mol** [comment]
I think this can be closed now, no? `dotnet fsi` exists for me, tested on dotnet core 5.0.100.
