### ISSUE TITLE
What is a textfile

### ISSUE THREAD

**Issue by IBrooke** [dotnet/docs#10291]
I'd really like this page extending to define exactly what is a textfile, how is it formatted etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f987fd-0a70-4781-0810-20443b81fd63
* Version Independent ID: b6121095-795a-83cd-9d9f-f4b4c1ea4abc
* Content: [How to: Read Text from Files with a StreamReader (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/drives-directories-files/how-to-read-text-from-files-with-a-streamreader?view=netframework-4.7.2)
* Content Source: [docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-read-text-from-files-with-a-streamreader.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-read-text-from-files-with-a-streamreader.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Closing due to the lack of response.
