### ISSUE TITLE
Gives out wrong time and wrong date ...

### ISSUE THREAD

**Issue by DanielOberlechner** [dotnet/docs#10296]
Hi,
when I execute the first code Example it gives me a wrong week day and the wrong time...

Does anybody know why that is so?

Greets by Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@DanielOberlechner an observation: if I modify the snippet (a mere additional white space in the comment does the magic) and run it again, the result is as expected.

That might be related to the engine that executes the snippets: [try.dot.net](https://try.dot.net/).
/cc: @LadyNaggaga

**Comment by DanielOberlechner** [comment]
ah ok ... just wondered why the date isn't correct ...
Greets

**Comment by mairaw** [comment]
There might have some caching involved. @dend @jdanyow to take a look as well

**Comment by KexyBiscuit** [comment]
Related: https://github.com/dotnet/try/issues/92

**Comment by rpetrusha** [comment]
I don't think that the issue here is related to caching. It seems to me that the local time zone is UTC, and that the UTC offset is not retrieved from the user's browser settings.

**Comment by BillWagner** [comment]
closing in deference of dotnet/try#167
