### ISSUE TITLE
Could use an example of how to refer to a property get/set

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10306]
This Could use an example of how to refer to a property get/set

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdca83b7-2628-9b4b-8f3f-1049805e16cb
* Version Independent ID: 32c5a4d8-82f5-631a-04ce-9f976bca2ba3
* Content: [cref Attribute - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/cref-attribute)
* Content Source: [docs/csharp/programming-guide/xmldoc/cref-attribute.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/cref-attribute.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @martingbrown 

I've added it to our backlog to address when we next update this content.

**Comment by BillWagner** [comment]
reopening to fix as part of updating the XML section.

**Comment by BillWagner** [comment]
Fixed in #24705
