### ISSUE TITLE
Is ARM platform param forcing 32 or 64 bit mode? 

### ISSUE THREAD

**Issue by chrisgull** [dotnet/docs#10307]
Just like on x86 platform there might be a need to enforce 32/64 bit process on ARM when conbining with C++ libraries via interop. Please clarify. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca199d9-7c99-6fb5-d3db-5b6d0f5eee6e
* Version Independent ID: 6e8fecc4-9405-43cc-2ef2-ecfef9529c0f
* Content: [-platform (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/platform-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/platform-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/platform-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @chrisgull 

I've opened PR #10561 to add the **ARM64** parameter.  That would force 64-bit. The **ARM** would be 32 bit.
