### ISSUE TITLE
ServiceModel.DisableUsingServicePointManagerSecurityProtocols default value

### ISSUE THREAD

**Issue by argandhi05** [dotnet/docs#10305]
Above it is mentioned that, "For applications targeting .NET Framework 4.7 and later versions, this value defaults to false".  For a WCF Service using message security, it appears it is mandatory to set the following config values :

&lt;runtime&gt;
    &lt;AppContextSwitchOverrides value="Switch.System.ServiceModel.DisableUsingServicePointManagerSecurityProtocols=false;Switch.System.Net.DontEnableSchUseStrongCrypto=false" /&gt;
  &lt;/runtime&gt;

Refer MS Documentation : 
https://github.com/Microsoft/dotnet/blob/master/Documentation/compatibility/wcf-message-security-unable-to-use-tls1_1-and-tls1_2.md

If the default value is already false, then why is it required to set the value as false again in the config file. Without setting it explicitly the Message Security with certificate breaks on using TLS 1.2. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
From answering and researching other questions, I've found that you can't rely on the default value. This can sometimes change based on Operating System and/or .NET Framework version too. You're better off setting the value you want.
