### ISSUE TITLE
Command to generate self-signed certificate does not work.

### ISSUE THREAD

**Issue by roger-cruz** [dotnet/docs#10301]
The PoSH command used here to generate a self-signed certificate, which is then promoted to a trust root CA did not work for me.

$rootCert = New-SelfSignedCertificate -CertStoreLocation cert:\CurrentUser\My -DnsName "RootCA" -TextExtension @("1.3.6.1.4.1.311.21.10={text}1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.2")

Certificates signed with the above certificate will show a warning "The certificate is not valid for the selected purpose".  If you try to use these certificates, you will get invalid certificate errors from clients.

The way I was able to fix this is to provide a -KeyUsage that includes "Certificate Signing" and change the OIDs to use the extended key usage rather than application policies.   Once this was done for the root CA certificate, new certificates worked like a charm.

I suggest the command be changed to be like below.
$rootcert = New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName "RootCA" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.2") -KeyUsage CertSign,DigitalSignature,KeyEncipherment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416d3d78-0e61-097b-0bbe-c6cd331aa986
* Version Independent ID: 87242506-6036-9469-0166-0ae8890a96f8
* Content: [How to: Create Temporary Certificates for Use During Development](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development)
* Content Source: [docs/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by jafz** [comment]
I'm not even sure why the TextExtension is necessary at all, as long as the KeyUsage is done properly - but I'm not really a pro with certificates. It took me an hour to end up with the line below, that also worked:
$rootCert = New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName "RootCA" -KeyUsage CertSign,CRLSign -KeyUsageProperty Sign
It'd be great if this site that pops up pretty far in searches doesn't suggest non-working script arguments
