### ISSUE TITLE
Lacks example of calling from C# !

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#10308]
@vasil-1603 commented on [Sat Feb 02 2019](https://github.com/dotnet/docs.ru-ru/issues/169)

Очень не хватает примера возможных вызовов из C# !

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 678eaef3-eec4-dc52-1234-37e220f84682
* Version Independent ID: 38b09163-65d8-4d6c-1394-401e080ed6f0
* Content: [Маршалинг данных при вызове неуправляемого кода](https://docs.microsoft.com/ru-ru/dotnet/framework/interop/marshaling-data-with-platform-invoke)
* Content Source: [docs/framework/interop/marshaling-data-with-platform-invoke.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/interop/marshaling-data-with-platform-invoke.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Hi team,
Please check on the issue created. Rough translation: 

> The example of possible calls from C # is not enough!

Thanks!

**Comment by progalgo** [comment]
Translation.
>>Очень не хватает примера возможных вызовов из C# !
Lacks exapmle of calling from C# !

**Comment by Florent125** [comment]
Yes, how do we call it in C#?

**Comment by kirsan31** [comment]
@dotnet/docs
The doc still incomplete without c# examples.

**Comment by BartoszKlonowski** [comment]
@BillWagner @gewarren Please assign me to this item, so I will work on this.
