### ISSUE TITLE
Property or indexer 'BankAccount.Balance' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by ClaudiuFilip110** [dotnet/docs#10310]
I have an error that pops up whenever I try to change the getter for Balance. I've even copy pasted the code on this thread and it does not seem to go away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@ClaudiuFilip110 

This tutorial uses a read-only property to retrieve the balance. The design is to change the balance by calling either the `MakeDeposit` or `MakeWithdrawal` method.

I hope that helps.

**Comment by adamrubin** [comment]
For anyone running into this issue:

Once you've implemented the MakeDeposit and MakeWithdrawal methods, and have rewritten Balance to be read-only, you'll need to remove this from your BankAccount constructor:

this.Balance = initialBalance;

**Comment by yorgash** [comment]
When you implement the get / set on Balance, you will not be able to write into it.
You will have to use the transactions to achieve the same effect. So if you want to keep the initial balance, you will have to change the mentioned line
>this.Balance = initialBalance;
into
>this.MakeDeposit(initialBalance, DateTime.Now, "Initial balance upon creation");

This way the BankAccount constructor will still make use of and display your initialBalance properly.
