### ISSUE TITLE
Paragraph about [Conditional] attribute has a mistake.

### ISSUE THREAD

**Issue by ZeaGate** [dotnet/docs#10328]
Instead of 
"If that string matches a #define directive,"
it should say
"If that string does not matches a #define directive,".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0949aaa-0396-f42e-9228-36f63917fcbb
* Version Independent ID: 0ff9f93b-99f7-1d35-2521-1b9583f799be
* Content: [Attributes - C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/attributes#common-attributes-in-the-base-class-library-bcl)
* Content Source: [docs/csharp/tutorials/attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/attributes.md)
* Product: **dotnet-csharp**
* GitHub Login: @mgroves
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Would you like to submit a fix for this? You can find instructions on how to do this at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.

My only comment would be that the fix should be "If that string doesn't match..."
