### ISSUE TITLE
Samples - Add demo for Visio automation in .NET Core 3.0

### ISSUE THREAD

**Issue by JohnGoldsmith** [dotnet/docs#10323]
**Issue description**

Add sample for Visio automation in .NET Core 3.0 Preview 2.

I've created a Visio version of the [Excel Demo](https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo) over at the fork here:

https://github.com/JohnGoldsmith/samples/tree/visiodemo/core/extensions/VisioDemo

Am happy to submit pull-request if it would be useful, or not if it's just seen as duplication. 

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core 3.0 Preview 2
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by mairaw** [comment]
Thanks @JohnGoldsmith! @AaronRobinsonMSFT @richlander can you comment on this since you worked on the Excel demo?

**Comment by AaronRobinsonMSFT** [comment]
I think there is some duplication here, but it is also pretty cool to have examples for other Office applications. I also think that this sample follows the pattern and is consistent with the Excel one so it looks professional. The only caveat with accepting too many of these is the maintenance of ensuring they continue to work, but I am inclined to set that number as more than 3 so I am all for accepting this one if the doc owners are good with it.

Thanks @JohnGoldsmith!

cc @jeffschwMSFT @jkoritzinsky

**Comment by JohnGoldsmith** [comment]
@AaronRobinsonMSFT That's great - thank you.  I've submitted the PR so please let me know if I need to do anything else at this stage.
