### ISSUE TITLE
Consider joining the .NET Foundation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10325]
The .NET Foundation recently updated its governance model, and you can [become a member](https://dotnetfoundation.org/become-a-member)

If you have contributed to this (or a related) repository, considering becoming a member. The details are at the above link.

If you have questions, add a comment on this issue. 

/cc @jongalloway for visibility

**Comment by Potapy4** [comment]
How long does the application process take? 😊

**Comment by BillWagner** [comment]
@Potapy4 Filling out the form should take between 5 - 10 minutes. The .NET Foundation advisory council is reviewing applications regularly, and you should here back within a few days.

Thanks for your patience. We are working through the process for the first time. In doing so, we're going a little slower to make sure we are doing it right.

**Comment by BillWagner** [comment]
Closing this after 3 weeks of visibility.  

Thanks to all who applied!! 💯

**Comment by NextTurn** [comment]
The [dotnet](https://github.com/orgs/dotnet) organization has 373 people now. Is this the number of foundation members on GitHub?

**Comment by BillWagner** [comment]
@NextTurn No, the groups have two different purposes.  The dotnet organization on GitHub is used to manage access rights to repositories that belong to the org. The .NET Foundation provides services to the .NET ecosystem, including projects that are part of the foundation but not part of the dotnet org on GitHub.

tag @jongalloway and @terrajobst if they want to add more clarificaiton
