### ISSUE TITLE
Description of the intended semantics of applying Precision facet to a double property

### ISSUE THREAD

**Issue by robert-j-engdahl** [dotnet/docs#10322]
Doubles are listed as having 15 digits of precision.  I thought their precision were in bits like https://en.wikipedia.org/wiki/Double-precision_floating-point_format

Furthermore, the precision facet would seem like something that can be applied to double properties, but what does that even mean; again if the value is a floating point number, fixing the point makes little sense.

Perhaps I got to this page by mistake...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92016ffa-09c8-9719-f993-0e8a748a803f
* Version Independent ID: 8072603e-a68e-45f1-9778-50845776138e
* Content: [Entity Data Model: Primitive Data Types](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/entity-data-model-primitive-data-types)
* Content Source: [docs/framework/data/adonet/entity-data-model-primitive-data-types.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/entity-data-model-primitive-data-types.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
I think it's just different ways to think of the type.
Here's a doc that talks about number of bytes and precision:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types#characteristics-of-the-floating-point-types
