### ISSUE TITLE
Review usage of NorthWind database

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10329]
## Review usage of Northwind database

The Northwind sample database is used extensively in the .NET documentation, particularly in ADO.NET and WinForms. The database is not readily accessible, making the examples difficult for our customers to run. To address the problems with using examples that use the Northwind database, we should:
1. Assess the extent of the problem and determine whether a change is warranted. That is, is the continued use of Northwind viable? If not, should something else be used, such as the AdventureWorks database or, for examples that do not necessarily require data access from a database, more simple data structures such as arrays?
2. Assess the scope of the problem. Determine where the NorthWind database is used in the .NET documentation set.
3. Change examples so that they make use of the new solution.

@v-thepet, feel free to add any additional detail here.

**Comment by mairaw** [comment]
I've been thinking about this issue a lot. 

I think this applies not only Northwind but also AdventureWorks. According to https://github.com/Microsoft/sql-server-samples, there's a new sample database for the latest versions of SQL. I'm also thinking as I'm seeing the MSDN links revisions from @DennisLee-DennisLee that probably a good chunk of the ADO.NET content should be archived in favor of EF 6 and EF Core. 
Thoughts?

/cc @divega

**Comment by rpetrusha** [comment]
Thanks, @mairaw. I was completely unaware of <https://github.com/Microsoft/sql-server-samples>. Instead of AdventureWorks, we should probably standardize on the World Wide Importers sample database. 

And I agree about archiving large portions of the ADO.NET content.
 
//cc @v-thepet
