### ISSUE TITLE
Screenshots for choosing StackPanel or DockPanel

### ISSUE THREAD

**Issue by barakisbrown** [dotnet/docs#10336]
I love the example given by code but it would also be great if you could show a screenshot of the desired effect because that would also give the reader an idea what your trying to say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21fc139-0f0a-a988-d6c8-fb70196d5067
* Version Independent ID: 0534a45b-9111-afd4-08ed-4919e2784941
* Content: [How to: Choose Between StackPanel and DockPanel](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel)
* Content Source: [docs/framework/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @barakisbrown. I've added to our backlog and to our community contributions project.

**Comment by Potapy4** [comment]
@mairaw we already have an [image](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/panels-overview#stackpanel-vs-dockpanel) with a difference between `StackPanel` and`DockPanel`. Should we add the same image to this doc?

**Comment by Yomodo** [comment]
Yes, for completeness. XAML related should be accompanied with a visual. A pictures says...
