### ISSUE TITLE
Content Needs depth

### ISSUE THREAD

**Issue by WilMead** [dotnet/docs#10344]
I'm leaving with questions unanswered.  
a.  What are the rules for the directory setting? 
b.  can and how can a URL such as  \\server\maildrops\application be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b442ac-c502-6882-7307-2c9a537579f4
* Version Independent ID: 1b2fe919-4095-000b-6f87-c80eab926223
* Content: [&lt;specifiedPickupDirectory&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Yashuaaa** [comment]
Also, what about Azure. Can I use this with a Azure Storage Account?

**Comment by mairaw** [comment]
@karelz @davidsh can you help with these questions about \<specifiedPickupDirectory>?

**Comment by davidsh** [comment]
>I'm leaving with questions unanswered.
a. What are the rules for the directory setting?
b. can and how can a URL such as \server\maildrops\application be used

The rules for the directory setting are the same for both the app.config file settings as well as the SmtpClient property, [PickupDirectoryLocation](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.pickupdirectorylocation?view=netframework-4.8)

Rules:
* The directory specified must be an absolute path
* It can be either a local directory path or a UNC path

>Also, what about Azure. Can I use this with a Azure Storage Account?
No. Azure Storage Accounts cannot be used.

*Examples*

Local Path
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <specifiedPickupDirectory pickupDirectoryLocation="C:\Users\user1\Documents"/>
      </smtp>
    </mailSettings>
  </system.net>
</configuration>
```

UNC Path
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <specifiedPickupDirectory pickupDirectoryLocation="\\servername\sharename"/>
      </smtp>
    </mailSettings>
  </system.net>
</configuration>
```

**Comment by davidsh** [comment]
@mairaw I answered the questions in this issue. Should we close this issue now? Or have someone possible submit a docs-related PR somewhere to incorporate my answers perhaps in the 'Remarks' section of a relevant doc page?
