### ISSUE TITLE
Did the API change?

### ISSUE THREAD

**Issue by keimpema** [dotnet/docs#10340]
I followed all the steps but am having trouble getting the code to compile. I am targeting netcoreapp2.1 and

1. mlContext.Data.CreateTextReader should be mlContext.Data.CreateTextLoader I think.

2. mlContext.CreateStreamingDataView should be mlContext.Data.ReadFromEnumerable?

3. I can not get the following to work at all:

            var predictedResults = predictions.AsEnumerable<SentimentPrediction>(mlContext, reuseRowObject: false);

There does not seem to be an AsEnumerable (extension) method.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/nl-nl/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi, @keimpema! ML.NET 0.10 was released yesterday and there are some changes. We are in the process of updating the tutorials and should have them updated within the next few days.  Apologies for the inconvenience!

**Comment by JRAlexander** [comment]
We'll update this issue with the PR once it is submitted.

**Comment by luisquintanilla** [comment]
@keimpema . The documentation for the Sentiment Analysis tutorial has been updated in PR #10419 . Updates are already in the site as well. 

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis
