### ISSUE TITLE
Mistake in the Example

### ISSUE THREAD

**Issue by fmonteiro-pt** [dotnet/docs#10346]
' Pass the original values to the WHERE clause parameters.  
Dim parameter As SqlParameter = dataSet.UpdateCommand.Parameters.Add( _  
  "@oldCustomerID", SqlDbType.NChar, 5, "CustomerID")  
parameter.SourceVersion = DataRowVersion.Original  
parameter = adapter.UpdateCommand.Parameters.Add( _  
  "@oldCompanyName", SqlDbType.NVarChar, 30, "CompanyName")  
parameter.SourceVersion = DataRowVersion.Original  

In the first parameter assign you have "dataSet.UpdateCommand" (wrong), and in the second assign you have "adapter.UpdateCommand" (correct).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ae7d7c-e29d-f645-1247-71fbb52e28db
* Version Independent ID: cb27bf85-1f9d-a684-1de0-fd64c2e9b0c7
* Content: [Optimistic Concurrency](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/optimistic-concurrency)
* Content Source: [docs/framework/data/adonet/optimistic-concurrency.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/optimistic-concurrency.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for your feedback @fmonteiro-pt. Would you like to submit the fix for this?
We explain how in the following article:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
