### ISSUE TITLE
The phrasing of the explanation is incorrect

### ISSUE THREAD

**Issue by TWolverson** [dotnet/docs#10359]
"This error occurs when you declare a property or indexer with an access modifier that is less restrictive than the access modifier on one of its accessors."

If that were true, the common construction

public int Prop {get; private set;}

would not be permitted.

declare a property or indexer with an access modifier (public int Prop) that is less restrictive (public is the least restrictive) than the access modifier on one of its accessors (private set)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89f3d534-3326-3ecc-a9c2-a3faa5a1e5ef
* Version Independent ID: c0843e71-0af0-9177-d712-2335cb989e1d
* Content: [Compiler Error CS0273](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0273)
* Content Source: [docs/csharp/misc/cs0273.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0273.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your detailed feedback @TWolverson. I've opened PR #10433 to fix this.
