### ISSUE TITLE
How to find Path or Nuget_ID to uninstall templates

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/docs#10362]
`dotnet --list`  shows LongName shortName Language and Tags.
To uninstall I need either the Path or the Nuget_ID.
```
-u|--uninstall &lt;PATH|NUGET_ID&gt;
```
what command gives u the path or the NugetId of the installed templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your question @StevenTCramer. @KathleenDollard @livarcocc can you help with this question?

**Comment by adeconsulting** [comment]
Boiethios mentioned here https://github.com/dotnet/templating/issues/961 how to get the template names needed for the uninstall command, use "dotnet new -u".

```
> dotnet new -u

Template Instantiation Commands for .NET Core CLI

Currently installed items:
 Microsoft.DotNet.Common.ItemTemplates
 Microsoft.DotNet.Common.ProjectTemplates.2.1
 Microsoft.DotNet.Test.ProjectTemplates.2.1
 Microsoft.DotNet.Web.ItemTemplates
 Microsoft.DotNet.Web.ProjectTemplates.2.1
 Microsoft.DotNet.Web.Spa.ProjectTemplates
 NUnit3.DotNetNew.Template
```

**Comment by mairaw** [comment]
Thank you! I've added this as part of the PR that updates the dotnet-new docs: #14356
