### ISSUE TITLE
++i VS i++ in a for loop...

### ISSUE THREAD

**Issue by tcjohnson71** [dotnet/docs#10369]
In C++ class we were told to use "++i" and not to use "i++" because using "++i" will make the code run faster.  Does this also work in C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825860b-5966-26c4-72bb-9df62c7329f0
* Version Independent ID: 4cf67a2a-173d-7f55-910a-cf883fe4086e
* Content: [C# for statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/for)
* Content Source: [docs/csharp/language-reference/keywords/for.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/for.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by NextTurn** [comment]
No. They produce the same MSIL.
```
ldc.i4.1
add
```

**Comment by BillWagner** [comment]
As @NextTurn states, there is no perf difference between the prefix and postfix operators in C#.

Closing as answered.
