### ISSUE TITLE
It throws an compilation error.

### ISSUE THREAD

**Issue by MahmudX** [dotnet/docs#10361]
It doesn't work. LOL. 
When I add the 'in' keyword, it throws a red squiggly line and says - "identifier expected; 'in' is a keyword."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by aboveyou00** [comment]
There is no indication on this page that this feature is only for C# 7+.

**Comment by rpetrusha** [comment]
Thanks for your feedback, @MahmudX The `in` parameter modifier was added in [C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#safe-efficient-code-enhancements). For information on configuring the language version, see [Select the C# language version](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version).

This article, however, certainly should note that the feature was added only in C# 7.2. We've added it to our backlog, as well as to our community contributor's project.
