### ISSUE TITLE
Obsolete text: "In this first release of WPF..."

### ISSUE THREAD

**Issue by sabuncu** [dotnet/docs#10364]
Fourth paragraph under "System Windows.Dependency Object":  

"In this first release of WPF, the property expression system is closed, and the expressions are all provided as part of the framework."

The above sentence seems to be left over from the very first release of WPF.  Also, it is not clear whether the property expression system is now open as opposed to closed.  This part of the documentation needs to be re-evaluated. 

Thanks.

edit by @mairaw: added topic info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08cf280-bb74-6eab-3475-b42508967afc
* Version Independent ID: 2dfcc4dd-6241-84d6-994a-413a54a259ff
* Content: [WPF Architecture](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-architecture)
* Content Source: [docs/framework/wpf/advanced/wpf-architecture.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/wpf-architecture.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@sabuncu is this feedback for https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-architecture?

**Comment by sabuncu** [comment]
@mairaw 

Yes it is.

Sorry, I thought the GitHub system provided the link automatically.

I believe the documentation is based on a 2006 Microsoft blog post here: [https://blogs.msdn.microsoft.com/wpfsdk/2006/05/18/wpf-architectural-article/](https://blogs.msdn.microsoft.com/wpfsdk/2006/05/18/wpf-architectural-article/)

Thanks.
