### ISSUE TITLE
After upgrading to VS2017 15.9.6, All my .NET Core frameworks are removed from the target platform dropdown

### ISSUE THREAD

**Issue by MeltdownZA** [dotnet/docs#10372]
I had 15.9.1 installed. I installed .NET 2.2, but it never showed up in the target platform dropdown in project settings, only .NET 2.0 appeared. So I upgraded to VS 15.9.6, and now when I open my solution, all .NET Core items were removed from the target dropdown. How do I fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@leecow @KathleenDollard have you heard of this issue? 
@MeltdownZA have you tried reinstalling the SDK?

**Comment by KathleenDollard** [comment]
@MeltdownZA 

Could you go to a Visual Studio command prompt and type

```bash
> dotnet --info
```

Could you upload or paste it here?

**Comment by Thraka** [comment]
Closing due to lack of response.
