### ISSUE TITLE
Not working with asp.net application

### ISSUE THREAD

**Issue by Ashutosh-K-Singh** [dotnet/docs#10379]
Hi ,
I have tried this configuration for tracing http calls in standalone executable . It worked well and generated all the http calls in a log file. When i tried with an Asp.net application but it wasn't  working. This tracing is supposed to trace system.net http call in any .net based application but for Asp.net application it is only creating a log file with one line of  log as below.

System.Net Information: 0 : [4628] Current OS installation type is 'Client'.

I would like to know,  what other things need to  be done to get system.net tracing in Asp.Net ??

Thanks
Ashutosh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59ca4fa1-9891-3e18-8dfa-38bee00bd040
* Version Independent ID: 3d07a2fb-5bb4-5b84-18f3-61bc8cba1236
* Content: [How to: Configure Network Tracing](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing)
* Content Source: [docs/framework/network-programming/how-to-configure-network-tracing.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-configure-network-tracing.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
I believe that ASP.NET does not use machine.config, but has its own web.config.
I would recommend to check ASP.NET documentation how to configure it - e.g. something like this: https://docs.microsoft.com/en-us/previous-versions/ff400235(v=vs.140)
