### ISSUE TITLE
Too many results

### ISSUE THREAD

**Issue by JamesUKDEV** [dotnet/docs#10382]
Results are likely going to be too long.
Would be useful to include something like &gt; C:\output.txt in the example.
gacutil -l &gt;c:\output.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99a5ab4-3926-906c-14ff-ceaac4a7f0bf
* Version Independent ID: e0fcdf8e-cf42-4af5-0e90-1058a974e591
* Content: [How to: View the Contents of the Global Assembly Cache](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-view-the-contents-of-the-gac)
* Content Source: [docs/framework/app-domains/how-to-view-the-contents-of-the-gac.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/how-to-view-the-contents-of-the-gac.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by PhilippeProost-personal** [comment]
Or a simple use of findStr to find a specific assembly

**Comment by rowek** [comment]
gacutil -l >c:\output.txt 
Only way to easily navigate output

**Comment by mcopeland-clgx** [comment]
Many production servers do not have the developer command line installed. How are we to view the contents of the GAC in this situation?
