### ISSUE TITLE
Page talks about, but does not have links to,  linux installer packages

### ISSUE THREAD

**Issue by wblair** [dotnet/docs#10384]
This page says there are native ubuntu and Centos/RHEL install packages available but has no link or references to where they are found or the repositories once could use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Under https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions, the topic says "For download links and more information, see .NET Core 2.2 downloads or .NET Core 2.1 downloads."

So install packages would be on the downloads page. For this reason, I'm closing this issue.
