### ISSUE TITLE
Reference or tutorial?

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#10393]
Is this a reference or a tutorial? It looks like a tutorial. A reference page would be clear and precise, especially about the syntax. Note that in the list of what the from clause specifies the data source is listed first then the range variable second. Whereas the syntax is that the range variable is first and data source second, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937bf577-34fe-4fed-57d0-8d91672945d8
* Version Independent ID: 23268adb-ff34-08cc-baa9-0ea1bfdf05ce
* Content: [from clause - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/from-clause)
* Content Source: [docs/csharp/language-reference/keywords/from-clause.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/from-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the feedback @SimpleSamples 
This is one area where we are planning to update in the next wave.
