### ISSUE TITLE
ML.NET API for one-hot encoding - compilation errors with sample code

### ISSUE THREAD

**Issue by sdg002** [dotnet/docs#10399]
I am trying to reproduce the sample code on this page.
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-model-categorical-ml-net

I faced no problems in loading the data and displaying categorical and numerical columns
However, when it came to one-hot encoding, I am facing compilation errors.

-The type 'CategoricalTransform.OutputKind.Bag' is not found
-The class 'CountFeatureSelector' is not found

###Snipper of code
    // Build several alternative featurization pipelines.
    var dynamicPipeline =
    // Convert each categorical feature into one-hot encoding independently.
    mlContext.Transforms.Categorical.OneHotEncoding("CategoricalFeatures", "CategoricalOneHot")
    // Convert all categorical features into indices, and build a 'word bag' of these.
    .Append(mlContext.Transforms.Categorical.OneHotEncoding("CategoricalFeatures", "CategoricalBag",     
 CategoricalTransform.OutputKind.Bag))
    // One-hot encode the workclass column, then drop all the categories that have fewer than 10 instances in the train set.
    .Append(mlContext.Transforms.Categorical.OneHotEncoding("Workclass", "WorkclassOneHot"))
    .Append(new CountFeatureSelector(mlContext, "WorkclassOneHot", "WorkclassOneHotTrimmed", count: 10));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c298a5-b76f-25d9-beda-e298ac03cf35
* Version Independent ID: 392ab238-4442-015c-ec30-eae546794cc9
* Content: [Apply feature engineering for model training on categorical data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-model-categorical-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/train-model-categorical-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-model-categorical-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
@sdg002 Thanks for raising this issue. This code looks like it may be from the previous version of the documentation. An update went in as part of PR #10350 which uses the latest version (0.10) of Microsoft.ML. Give that a try and let us know if you still have are having problems. Thanks!

**Comment by JRAlexander** [comment]
@sdg002, closing as this appears to be resolved. If that isn't the case please reopen. Thanks!
