### ISSUE TITLE
Doesn't describe how to load data using JSON

### ISSUE THREAD

**Issue by tylerjgarland** [dotnet/docs#10398]
I can spot newtonsoft.json in the latest version of ML.NET 0.10 ,but I can't find a way to process JSON data in these docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72764a44-6802-52cc-0fde-4e77ea023ef1
* Version Independent ID: 4744f614-da6b-a15c-aebf-8a457f5549c8
* Content: [Load data from a text file for machine learning processing - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-from-text-file-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/load-data-from-text-file-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-data-from-text-file-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@tylergarland, I believe newtonsoft.json is used for internal processing.  @shmoradims or @sfilipi, do you have any feedback on this? You might try deserializing your JSON into a collection - like here: https://www.newtonsoft.com/json/help/html/SerializingCollections.htm#DeserializingCollections  then using ReadFromEnumerable from your deserialized collection and then prediction,etc from here:  https://github.com/dotnet/samples/blob/master/machine-learning/tutorials/SentimentAnalysis/Program.cs#L180

**Comment by JRAlexander** [comment]
Closing this as I believe it's been resolved. @tylerjgarland, please reopen if this is not the case. Thanks!
