### ISSUE TITLE
Above procedure to turn on nullable reference types for an entire project is incorrect for VS 2019 Preview 2

### ISSUE THREAD

**Issue by MichaelVach** [dotnet/docs#10408]
incorrect for VS 2019 Preview 2 "&lt;NullableReferenceTypes&gt;true&lt;/NullableReferenceTypes&gt;"
should be replaced with "&lt;NullableContextOptions&gt;enable&lt;/NullableContextOptions&gt;"

more info at https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#setting-project-level-nullable-context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This was fixed in #10381 
Closing as fixed.
