### ISSUE TITLE
Incorrect code example for Parameter Arrays

### ISSUE THREAD

**Issue by Mustard867** [dotnet/docs#10400]
The code example in the section "Parameter arrays" is incorrect. It doesn't define the function talked about in the text prior to it and it doesn't use the params keyword.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods#passing-parameters)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @Mustard867. This is clearly the wrong example. Unfortunately, the correct one seems to have been lost at some point in one of our content migrations, so a new one will need to be written. I've added this issue to our backlog, as well as to the community contributor's project.

**Comment by mairaw** [comment]
I think this is not a migrated topic, so maybe just an issue with the topic when it was created.
