### ISSUE TITLE
FrontEnd Help

### ISSUE THREAD

**Issue by coreys079** [dotnet/docs#10406]
I am having difficulty with network frontend, so what does the frontend consist of? Where do I begin? What c# sharp codes do I use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2662c2f7-e074-225a-d878-9e3cb6b9ff90
* Version Independent ID: 9f333c5a-3e53-5abf-8c09-d5f1f5b7c59b
* Content: [Network Programming in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/)
* Content Source: [docs/framework/network-programming/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/index.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Hi @coreys079, thanks for your question. You can use networking APIs with any kind of frontend supported in .NET, like web, console or desktop apps such as WPF or Winforms. If you're just trying to get started, probably the easier would be to start with a simple console application to implement the functionality you want to achieve.
