### ISSUE TITLE
checked doesn't work as expected with floating point

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#10405]
Seems odd that checked floating point code that overflows will quietly generate a Nan instead of throwing an exception. Needs to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbbcec4d-d8ff-d906-57ec-378689eb99a5
* Version Independent ID: 88e4ead1-3745-2be6-9cfb-0f02eeacf9c1
* Content: [checked keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked)
* Content Source: [docs/csharp/language-reference/keywords/checked.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/checked.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
@daveyostcom, **checked** applies only to arithmetic operations and conversions with integers; it does not apply to floating-point operations. I'll close this issue.

**Comment by daveyostcom** [comment]
Yeah, I noticed that when I actually read all of the words. ;-)
