### ISSUE TITLE
'Score column 'Score' not found

### ISSUE THREAD

**Issue by 7danny** [dotnet/docs#10417]
Following this tutorial using Microsoft.ML.0.10.0, I am getting an error on the Evaluate method(error below), this line:
var metrics = mlContext.BinaryClassification.Evaluate(predictions, "Label");

Train and Predict seam to work(at least compile) but score always 50%.

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Score column 'Score' not found
Parameter name: schema
  Source=Microsoft.ML.Core
  StackTrace:
   at Microsoft.ML.Data.RoleMappedSchema.MapFromNames(Schema schema, IEnumerable`1 roles, Boolean opt)
   at Microsoft.ML.Data.RoleMappedData..ctor(IDataView data, Boolean opt, KeyValuePair`2[] roles)
   at Microsoft.ML.Data.BinaryClassifierEvaluator.Evaluate(IDataView data, String label, String score, String probability, String predictedLabel)
   at SR.Program.Evaluate(MLContext mlContext, ITransformer model) in C:\Users\dd\Documents\Visual Studio 2017\Projects\SR\SR\Program.cs:line 104
   at SR.Program.Main() in C:\Users\dd\Documents\Visual Studio 2017\Projects\SR\SR\Program.cs:line 47

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by 7danny** [comment]
Disregard, was following outdated tutorial. Current working example: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis

**Comment by luisquintanilla** [comment]
@7danny You beat me to it. I was just writing a comment that seeing the time this issue was logged and when PR #10419 went in, it might be an outdated tutorial. Feel free to let us know if you have additional issues. Thanks!

**Comment by CamiloTerevinto** [comment]
Please reopen this. The tutorial [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis) is still not updated to work with 0.10. The same exception received by @7danny  is received when following the tutorial.

**Comment by luisquintanilla** [comment]
Hi @CamiloTerevinto . Sorry you're still experiencing issues. I have run the code which the tutorial is based on and was not able to replicate the issue. The changes currently in the Microsoft Docs website should reflect the latest v0.10 changes. Here is the code that the tutorial is based on

https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/SentimentAnalysis

If you try it with that code do you still experience the same issue?
