### ISSUE TITLE
Docker file COPY

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10416]
@rochar commented on [Sat Feb 09 2019](https://github.com/dotnet/docs.pt-br/issues/111)

In the Docker File the COPY instruction should be replace by the ADD for the latest docker version

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Colocar um aplicativo em contêiner com o Docker](https://docs.microsoft.com/pt-br/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **johnalex**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor made a suggestion on the code box
best

**Comment by MichaelSimons** [comment]
@rochar, what is your reasoning for replacing COPY with ADD?  Per the [Dockerfile Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy), COPY is generally preferred over ADD.

**Comment by rochar** [comment]
Hi Michael,

You are correct, sorry for the inconvenience.

Ricardo

**Comment by MichaelSimons** [comment]
Hi Ricardo,

No worries.

Michael
