### ISSUE TITLE
<RuntimeIdentifiers> is no longer needed inside the project file

### ISSUE THREAD

**Issue by psimoneau22** [dotnet/docs#10422]
The documentation on this page should be updated because the &lt;RuntimeIdentifiers&gt; element is no longer needed in the project file.

see this issue for further information:  https://github.com/dotnet/docs/issues/9239

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a901ae9f-cc78-b5de-a031-b4671c7a85ac
* Version Independent ID: 89276cf0-167d-c108-f9d6-f5bfe1317851
* Content: [Runtime roll forward for .NET Core self-contained app deployments. - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection#how-to-avoid-restore-during-publish)
* Content Source: [docs/core/deploying/runtime-patch-selection.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/runtime-patch-selection.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@KathleenDollard can you comment on this?
