### ISSUE TITLE
Fails to install with error 0x80070001

### ISSUE THREAD

**Issue by frogger081** [dotnet/docs#10423]
I recently did a fresh install of Windows 10 to the latest version. Unfortunately for me, some software I have uses .NET 3.5. The system will not install it.

I have tried "Turn Windows features on or off".
I have tried the .NET 3.5 installer.
I have tried the .NET 3.5 offline installer.
I have tried the Microsoft utility to automatically repair "problems that block programs for being installed".
I have tried the .NET repair tool.
I have tried the dism command.
I have tried going to "Windows Update".

Everything returns a useless "error 0x80070001".

Windows Update reports:
2019-01 Cumulative Update for .NET Framework 3.5 and 4.7.2 for Windows 10 Version 1809 for x64 (KB4481031) - Error 0x80070001

This is ridiculous. I'm trying to install a version of .NET that is supposed to still be supported and works in every other version of Windows I've had for the last 10+ years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by frogger081** [comment]
Incidentally, when I say "every version of Windows", I'm including previous installations of Windows 10.

**Comment by mairaw** [comment]
Have you tried the DISM technique as the article suggests if everything fails?
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism

/cc @vivmishra

**Comment by vivmishra** [comment]
cc: @NikolaMilosavljevic

**Comment by mairaw** [comment]
I'm closing this due to the lack of response.

**Comment by frogger081** [comment]
@mairaw Thank you.

For anyone that runs into this problem, I had to use DISM:

dism /Online /Enable-Feature /FeatureName:NetFx3 /Source:U:\sources\sxs /LimitAccess /All

Drive "U" is the USB installation media.

**Comment by mairaw** [comment]
Thanks for letting us know @frogger081. That's the recommended solution when nothing else works.
