### ISSUE TITLE
access modifier introduction version

### ISSUE THREAD

**Issue by rajanmishra18** [dotnet/docs#10437]
As I know you have introduced a new access modifier and that is private protected. But you have not mentioned anywhere that it was introduced after c# 7.0. Kindly mention that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faccde0-3626-7806-ad33-755cdb0657a1
* Version Independent ID: 9b5d452f-f104-5e24-3280-b721752fea95
* Content: [Access Modifiers - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/access-modifiers)
* Content Source: [docs/csharp/language-reference/keywords/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/access-modifiers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by kambleaa007** [comment]
yeah we need to distinguish between legacy keywords and newly added keywords separately,

**Comment by BillWagner** [comment]
I have two questions regarding what would make this useful, if we added this:

1. How far back is "reasonable" for adding this? 
1. How should we handle keywords that have new meanings in newer versions? See `when`, `where`, `in`, `ref` 

We do have both the history article, where much of this is covered and "What's new" summaries that cover each release.  There's also guidance in the newer C# compilers that say when a feature is available, if you're targeting an older version.

**Comment by BillWagner** [comment]
`private protected` has been added some time ago.

closing this.
