### ISSUE TITLE
Make threading issue easier to reproduce

### ISSUE THREAD

**Issue by joaoportela** [dotnet/docs#10436]
I think we can make the issue easier to reproduce: the threading issue triggered by not having the `volatile` keyword.

Inspired by what @Xenoprimate mentioned in issue #5763 and [this stackoverflow post](https://stackoverflow.com/a/10797326/86845) I have some suggestions to make to the example code:

Change DoWork to:
```
            public void DoWork()
            {
                bool work = false;
                while (!_shouldStop)
                {
                    work = !work; // simulate some work
                }

                Console.WriteLine("Worker thread: terminating gracefully.");
            }
```

Because doing IO on the worker thread seems to trigger fresh reads for some reason.

Then change the Thread.Sleep from `1` to `500`.

Now on to the good parts:
- Run the program in both debug and release. Everything works as expected. :)
- Now remove the `volatile` keyword:
  - In Debug mode the program still works
  - **In Release mode it hangs forever.**

As an interesting bonus:
When asking a friend to run this code he ran it as part of our unit testing system and the issue was triggered in debug and with a thread sleep of only 1. This confirms that some variation is possible and to be expected.

Hopefully this example helps trigger the behavior for the most number of people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d226514d-c7cb-0d1b-b9dc-fb791399dc47
* Version Independent ID: aa5d1078-7f89-98ce-7fdc-107c9ed3eebc
* Content: [volatile - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)
* Content Source: [docs/csharp/language-reference/keywords/volatile.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/volatile.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Well done @joaoportela !  I verified that behavior on my machine with .NET Core 2.2.

Do you want to submit a PR with this fix? If not, I'll add this to our backlog.
