### ISSUE TITLE
Missing XAML example

### ISSUE THREAD

**Issue by mlop3s** [dotnet/docs#10435]
It would be great to see how this is bound on XAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f738fdd-5b1d-211d-46e6-c5ba2fd1fcf8
* Version Independent ID: 6c181d15-2a5a-5d33-ef8e-f26d3b439a32
* Content: [Collection-Type Dependency Properties](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/collection-type-dependency-properties)
* Content Source: [docs/framework/wpf/advanced/collection-type-dependency-properties.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/collection-type-dependency-properties.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by AS-Transurb** [comment]
Up! Also, would it be possible to clarify the "read-write" usecase ?
