### ISSUE TITLE
Linux install script is different from main site install procedure

### ISSUE THREAD

**Issue by natenho** [dotnet/docs#10447]
- The Linux installation script is installing .NET Core 2.1 instead of 2.2
- The installation procedure described in the document is very different from the main .net web site at (e.g. https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current). Search engines often return this document for the keywords "dotnet install linux", and may cause confusion, since it seems not to be the recommended way to install dotnet on Linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@mairaw Who is in charge of the script?

**Comment by Thraka** [comment]
@natenho Hi! The script is intended for non-admin installs and automation scenarios. It says this in the first paragraphs of the article that you should go to the main install site. We can't really do anything about the search engine problem as the page title is accurate. 

We can contact the script author to update the script to 2.2 though 😄

**Comment by mairaw** [comment]
@johnbeisner is the owner AFAIK

**Comment by mairaw** [comment]
@natenho we'd need a bit more information in order to investigate this issue properly.

1. Is the first issue still happening? If so, which command exactly are you using? For product issues like that, it's probably easier to file an issue at https://github.com/dotnet/cli/issues, where the product team reviews them.
2. I cannot repro the issue of seeing this page over the marketing site results on a search engine, but I could add a sentence to this topic pointing to the main downloads site. Would that help?

**Comment by natenho** [comment]
1. Yes it is, I've just checked, here is the output:

```console
[root@centos-181 ~]# ./dotnet-install.sh
dotnet_install: Warning: Unable to locate libunwind. Probable prerequisite missing; install libunwind.
dotnet_install: Warning: Unable to locate libicu. Probable prerequisite missing; install libicu.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.701/dotnet-sdk-2.1.701-linux-x64.tar.gz
```

2. I could not reproduce the search engine behavior anymore. The first result is going to https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current

I think the description in the document could emphasize that the "regular way" of installing dotnet on linux and link to the download website. 

The current text of the description says:

> We recommend that you use the stable version that is hosted on .NET Core main website. The direct paths to the scripts are: 
[...]

IMHO, the recommendation is not very clear. Is it about the stable SDK or the stable installation scripts? At least I can't find those scripts in the main website, could you?

Thanks! :)

**Comment by mairaw** [comment]
Yes, I think we can improve the text. But it's about the stable version of the installation scripts.

For issue #1, as I mentioned earlier, I suggest you file an issue at https://github.com/dotnet/cli, so the product team can review that.

**Comment by natenho** [comment]
> Yes, I think we can improve the text. But it's about the stable version of the installation scripts.

So in this case it would be even better to put the actual link to the installation scripts download page. Where can we find it?

**Comment by johnbeisner** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
You can find the installation scripts' URLs under the 'Description' section.
