### ISSUE TITLE
Need to update Hosting documents to remove claim of 'side-by-side'

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#10440]
The following sentence should be changed:
Because .NET Core is able to run side-by-side with itself, it's even possible to create hosts which initialize and start multiple versions of the .NET Core runtime and execute apps on all of them in the same process.
To:
.NET Core is not supported to run side-by-side with itself.  If you are looking for assembly loading isolation consider AssemblyLoadContexts (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-2.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET Core runtime host - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by mjrousos** [comment]
@jeffschwMSFT, I can make the necessary update. I thought back in the Silverlight days it was possible to start more than on CoreCLR instance in-proc. I take it that has changed?

**Comment by mjrousos** [comment]
Looking at the doc in question, I don't think we need to address the side-by-side scenario at all. It looks like the only reason it was mentioned was as a cool 'extra' feature for people implementing advanced hosting scenarios. If this isn't a supported scenario, my proposed fix would be to just remove that sentence. Let me know if that makes sense.

**Comment by jeffschwMSFT** [comment]
Thanks @mjrousos, I agree removing the sentence looks like the right fix.
