### ISSUE TITLE
Working on cache objects

### ISSUE THREAD

**Issue by MohanKumarPrakash** [dotnet/docs#10453]
This was good information. I'm working on SAP right now but the .net documentation is way ahead and better. Good work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f884d92b-b068-2730-9946-6ce6aa638cca
* Version Independent ID: a4fbd192-8629-0aff-7d72-080de94e75cc
* Content: [Caching in .NET Framework Applications](https://docs.microsoft.com/en-us/dotnet/framework/performance/caching-in-net-framework-applications)
* Content Source: [docs/framework/performance/caching-in-net-framework-applications.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/caching-in-net-framework-applications.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your kind comments @MohanKumarPrakash. We really appreciate it!
