### ISSUE TITLE
Syntax Suggestion

### ISSUE THREAD

**Issue by rspain** [dotnet/docs#10460]
Given this is a tutorial, I feel it would be easier to follow if variables were explicitly typed.

i.e. var metrics = mlContext.Regression.Evaluate(predictions) could read 
RegressionMetrics metrics = mlContext.Regression.Evaluate(predictions) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Predict New York taxi fares using a regression learner with ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#train-the-model)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
@rspain Thanks for the feedback. We'll take that into account as we continue to improve our content.
