### ISSUE TITLE
ECMA C# and CLI Standards page is out of date

### ISSUE THREAD

**Issue by KexyBiscuit** [dotnet/docs#10469]
**Issue description**

[ECMA C# and CLI Standards page](https://visualstudio.microsoft.com/license-terms/ecma-c-common-language-infrastructure-standards/) is out of date.

**Comment by BillWagner** [comment]
Thanks for noting that @KexyBiscuit 

@gewarren Do you know who owns the page linked above? I can get them the updated links for the C# ECMA standard.

**Comment by gewarren** [comment]
@vicushin can you help route this to right person? The page that's out of date is https://visualstudio.microsoft.com/license-terms/ecma-c-common-language-infrastructure-standards/.

**Comment by vicushin** [comment]
Send this to @VSCOM Site Managers<mailto:VscomSiteMgr@microsoft.com>.

________________________________

**Comment by mairaw** [comment]
Have this been sent? Otherwise, I can. /cc @CarolEidt

**Comment by BillWagner** [comment]
@mairaw Not to my knowledge.

The C# 5.0 ECMA spec is available on the [ECMA site](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf)

**Comment by KexyBiscuit** [comment]
And [ISO/IEC 23270:2018](https://www.iso.org/standard/75178.html) is published. 

Well, [ECMA site](https://www.ecma-international.org/publications/standards/Ecma-334.htm) is a little out of date either.

**Comment by BillWagner** [comment]
@KexyBiscuit ISO voted to approve the ECMA 5.0 standard. Those two documents match.

**Comment by mairaw** [comment]
Is this still an issue?

**Comment by BillWagner** [comment]
Yes, most of the links 404 from the page referenced in the original issue. they should be updated to the correct downloads from [this ECMA hosted page](https://www.ecma-international.org/publications/standards/Stnindex.htm)

**Comment by vicushin** [comment]
Hi all,

I (and the VSCOM team) are not on point for licensing pages. Please check with @Paul Chapman<mailto:Paul.Chapman@microsoft.com>.

Thanks,
Victoria
________________________________

**Comment by mairaw** [comment]
I started an internal thread on this. Let's see if we can get this fixed!

**Comment by mairaw** [comment]
I added Paul to the thread. Let's see if we can get this fixed!

**Comment by paul** [comment]
Wrong @paul, though :stuck_out_tongue:

**Comment by BillWagner** [comment]
This has been fixed. The links are correct now.

**Comment by KexyBiscuit** [comment]
The file in Microsoft Implementation Specific Version paragraph requires Corporate account, is that expected?

**Comment by mairaw** [comment]
I don't think so @KexyBiscuit. I'm following up with the team.

**Comment by CarolEidt** [comment]
The file should be accessible to all - I presume it just needs to be relocated to a public location.
