### ISSUE TITLE
Compilation failure CS0151 leaves VS "Error List" window empty.

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#10477]
A C# "switch(x)" where x was of type "object" (actually an indexer invocation that returns object) led to build failing yet the Error List had only warning no errors, the output however window does include a message about CS0151, but hard to see it among all of the other stuff there.

This is on VS 2017 - 15.9.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97537fd-f0ed-e9d9-5661-5721e72ae704
* Version Independent ID: 21130e76-eb42-9eed-2c8f-32fae3dfcecc
* Content: [Compiler Error CS0151](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0151)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0151.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0151.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @Korporal 

That code would now be legal in C# 7, with the new [pattern matching](https://docs.microsoft.com/dotnet/csharp/pattern-matching) features.

**Comment by BillWagner** [comment]
closing as this syntax is now legal.
