### ISSUE TITLE
Licensing for signTool

### ISSUE THREAD

**Issue by Jack0falltech** [dotnet/docs#10478]
Can I include signtool.exe in my software for it to use ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a4dbac-a145-e79f-121d-3d8df67552b1
* Version Independent ID: 9ea61916-a9db-f23e-4c43-edc06650483d
* Content: [SignTool.exe (Sign Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe)
* Content Source: [docs/framework/tools/signtool-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/signtool-exe.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by RAJU2529** [comment]
yes you can include.
