### ISSUE TITLE
.Net Core with WCF Services

### ISSUE THREAD

**Issue by Alaa-Abubaqi** [dotnet/docs#10470]
I'm trying to consume wcf service from asp.net core web application.

but it keeps giving me errors, no matter what I try to do to make it works.

the main problem is that i need to use custom binding in my wcf service as follows

**Comment by Alaa-Abubaqi** [comment]
I'm trying to consume wcf service from asp.net core web application.

but it keeps giving me errors, no matter I try to do to make it works.

the main problem is that i need to use <custombinding> in my wcf service as follows

<customBinding>
        <binding name="ServiceBinding">
          <security authenticationMode="UserNameOverTransport" includeTimestamp="false" ></security>
          <textMessageEncoding messageVersion="Soap11">
            <readerQuotas maxDepth="32" maxStringContentLength="2147483647" maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
          </textMessageEncoding>
          <httpsTransport useDefaultWebProxy="true" maxBufferPoolSize="2147483647" maxBufferSize="2147483647" maxReceivedMessageSize="2147483647" />
        </binding>
      </customBinding>

**Comment by Alaa-Abubaqi** [comment]
<customBinding>
        <binding name="NURServiceBinding">
          <security authenticationMode="UserNameOverTransport" includeTimestamp="false" ></security>
          <textMessageEncoding messageVersion="Soap11">
            <readerQuotas maxDepth="32" maxStringContentLength="2147483647" maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
          </textMessageEncoding>
          <httpsTransport useDefaultWebProxy="true" maxBufferPoolSize="2147483647" maxBufferSize="2147483647" maxReceivedMessageSize="2147483647" />
        </binding>
      </customBinding>

**Comment by mairaw** [comment]
Thanks for your question @Alaa-Abubaqi. 
@glennc @Lxiamail @zhenlan is that something you can help with or is it more appropriate for a forum like StackOverflow?
