### ISSUE TITLE
This example needs expansion.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#10479]
This example is remedial and worthless because in the real world we often deal with group joins. How are the results of a nested group join stuffed in a strongly-typed IEnumerable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae961995-f9c7-4a1c-3817-9044952e35c7
* Version Independent ID: 83a03f82-2856-5f64-f270-5bf43a8cd153
* Content: [How to: Return a LINQ Query Result as a Specific Type (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/linq/how-to-return-a-linq-query-result-as-a-specific-type)
* Content Source: [docs/visual-basic/programming-guide/language-features/linq/how-to-return-a-linq-query-result-as-a-specific-type.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/linq/how-to-return-a-linq-query-result-as-a-specific-type.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by LJ9999** [comment]
Here is a sample group join that I am referring to (ignore the IEnumerable, it fails miserably).

IEnumerable<a> listGAA = (IEnumerable<a>) (from GE in db.GENRE
						join AL in db.ALBUM on GE.GENRE_ID equals AL.GENRE_ID into albumgenre
						orderby GE.NAME
						select new
						{
							GenreID = GE.GENRE_ID,
							GenreName = GE.NAME,
							albums = from AL in albumgenre
								    join AR in db.ARTIST on AL.ARTIST_ID equals AR.ARTIST_ID into albumartist
									orderby AL.NAME
									select new
									{
										AlbumID = AL.ALBUM_ID,
										AlbumName = AL.NAME,
										artist = from AR in albumartist
												select new
												{
													ArtistID = AR.ARTIST_ID,
													ArtistName = AR.NAME
												}
									}
						 }).ToList();

**Comment by BillWagner** [comment]
@LJ9999 I'm a bit confused by your question.

The article you reference explains how to map the results of a LINQ query to a class you've created. That would work the same whether a group join is involved or not.

The example you post returns anonymous types. (Both `select` statements are creating new anonymous types). Is that the issue, or is it something more about how the Group Join works in a LINQ query?

**Comment by mairaw** [comment]
Closing this issue due to the lack of response. @LJ9999 please get back to us if you can answer @BillWagner's question.
