### ISSUE TITLE
How does platform invoke detect the binary basis of the string that is passed to an API function

### ISSUE THREAD

**Issue by javadbayat** [dotnet/docs#10471]
In languages like c++, we have many different types of string, such as std::string, std::wstring, array of char, array of wchar_t, and BSTR. But in Visual Basic, in which PlnVoke is used, there is just one type of string named String:

Dim myStr As String

It reconciles any type of string defined in c++. I wonder how PlnInvoke detects the binary basis of a native VB String in order to pass it correctly to Unicode or Ansi version of an API. Let alone the api functions that expect a BSTR like SysFreeString.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e096b54c-f52f-1f8e-7148-5f46d9f5f23e
* Version Independent ID: 8e41580d-9236-4b24-6430-c7d413bb78b5
* Content: [Consuming Unmanaged DLL Functions](https://docs.microsoft.com/en-us/dotnet/framework/interop/consuming-unmanaged-dll-functions)
* Content Source: [docs/framework/interop/consuming-unmanaged-dll-functions.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/consuming-unmanaged-dll-functions.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by KalleOlaviNiemitalo** [comment]
This is described in [Default Marshaling for Strings](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings?view=netframework-4.7.2). If the default is not correct for the API function you are calling, you have to add the correct [MarshalAsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshalasattribute?view=netframework-4.7.2) to the parameter. In this way, you can get `char *`, `wchar_t *`, or `BSTR`.  The marshaling does not support `std::string` and `std::wstring`.

**Comment by gewarren** [comment]
The original question has been answered, so I'm closing this issue.
