### ISSUE TITLE
This is stupidly insane. 

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#10485]
Why don't you people ever use a highly complex sample so we can work it backwards if necessary? It's almost impossible to work a simple example forward because of the stupid insanity.

I need this rocket science to nest 3 levels, not 2, and I need to group multiple fields for each group.

How many bowls of weed will I have to smoke to achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b8960-bd9b-6e47-0697-1ede60319dcc
* Version Independent ID: f2080e9b-3a61-ec89-eb34-b61aff1641fa
* Content: [Create a nested group (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/create-a-nested-group)
* Content Source: [docs/csharp/linq/create-a-nested-group.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/create-a-nested-group.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LJ9999** [comment]
On second thought. Nevermind. The design pattern for this example is just wrong. I'll untangle it, though, and then apply for a job on this doc team under the condition that every existing person on it be fired :-)

**Comment by jongalloway** [comment]
@LJ9999 Your comments on this issue are both abusive and unprofessional, in direct violation of the .NET Foundation Code Of Conduct. Please consider this an official warning; future violation will result in your being barred from this repository. We value your interaction, as long as it is courteous and productive.
