### ISSUE TITLE
.Net Framework 3.5 referenced assembly not found

### ISSUE THREAD

**Issue by scorpio05** [dotnet/docs#10495]
[Fails to install with error 0x80073701]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by Akirus** [comment]
Same is happening to me.

**Comment by fazilsweet** [comment]
i to have the same problem like. Install the .NET Framework 3.5 on Demand. And Enable the .NET Framework 3.5 in Control Panel. But when I'm going to install this .Net framework 3.5, its apper "The following feature couldn't be installed:" and error code is 0*800736B3.
 please help me ASAP.

**Comment by asamatterof** [comment]
I am having the same problem I am trying to set up an ftp for my site please help

**Comment by deejerydoo** [comment]
Microsoft don't want to make it easy for you. They'd rather you just update to Windows 10. They have removed the source files from their servers.

**Comment by m-pollack** [comment]
Hey Microsoft we have old solutions we are trying to maintain and or update
we sill need to be able to get to these old frameworks to do so 

I know you all think you know how the entire world works but if you did you would not be on the way to a junk stock while apple surpassed you

**Comment by Thraka** [comment]
These are hard to troubleshoot as we're not technical support but just docs. Have you tried installing with the DISM method as linked to in the article? https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism

I did notice there was a new .NET download page for 3.1 SP1 (or just new to me?) https://dotnet.microsoft.com/download/dotnet-framework/net35-sp1 This has an offline installer but I don't know what OS it's designed for. Perhaps you can test with this?
