### ISSUE TITLE
API Gateway implementation?

### ISSUE THREAD

**Issue by ccalvarez** [dotnet/docs#10502]
Hi, is there an article of this series that covers the API Gateway implementation?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 376577d9-c559-9d5d-e263-ff9f0fb6ac27
* Version Independent ID: 29164c20-12a7-6bf2-a946-03ef2477d61b
* Content: [Creating a simple data-driven CRUD microservice](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by CESARDELATORRE** [comment]
Here:
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot

Also in the eBook .PDF (.NET Microservices), same chapter:
https://aka.ms/microservicesebook 

And this related/original Blog Post in my blog:
https://blogs.msdn.microsoft.com/cesardelatorre/2018/05/15/designing-and-implementing-api-gateways-with-ocelot-in-a-microservices-and-container-based-architecture/

Hope it helps. 👍
