### ISSUE TITLE
"Serializing a plain Exception object, such as the following..." - nothing follows

### ISSUE THREAD

**Issue by Compynerd255** [dotnet/docs#10509]
The final bullet point of "Differences in serializers" reads:

&gt; - Serializing a plain Exception object, such as the following, doesn't work well with DataContractSerializer and DataContractJsonSerializer:

However, the next section begins immediately and is entirely unrelated. What are the exceptions we can't serialize with these serializers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf5fdf4-e2bc-8719-8163-1f6cfbab6d44
* Version Independent ID: baef07a5-5fb9-3059-4782-0356d65ebb3a
* Content: [Migrating Your Windows Store App to .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/migrating-your-windows-store-app-to-net-native)
* Content Source: [docs/framework/net-native/migrating-your-windows-store-app-to-net-native.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/migrating-your-windows-store-app-to-net-native.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@Compynerd255 Looking through the history of that file, I can't find anything that would indicate something was there. Perhaps it should just be reworded.

@rpetrusha Do you remember anything about this? Perhaps we should just remove that "such as the following" clause and fix the punctuation at the end of the sentence?

**Comment by mairaw** [comment]
It looks like there was some bad code reference inherited from MSDN days. This is what it used to look like:

![image](https://user-images.githubusercontent.com/12971179/53380519-8b490300-3922-11e9-8db6-473015a63e94.png)

Probably Ron would know best what existed here before.

**Comment by rpetrusha** [comment]
Yes, I do remember a few of the details. The original code was somehow lost, possibly during one of our migrations, but more likely because of content loss in Parsnip. Some time later, when I realized that the code was missing, I couldn't find a local version to replace it. 
I'll remove the mention  of an example.

**Comment by Compynerd255** [comment]
The text "such as the following" is still there.

**Comment by Thraka** [comment]
@Compynerd255 I see the change in the PR, but not the live site. So it may just be a delay in publishing.
