### ISSUE TITLE
error with example

### ISSUE THREAD

**Issue by TRobins** [dotnet/docs#10516]
Put the first example into a new project and tried running it and got this response.. System.InvalidOperationException: 'Column's SortMode cannot be set to Automatic while the DataGridView control's SelectionMode is set to ColumnHeaderSelect.'

Am using vs2017, windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbc519c-e595-cfff-988b-b53e79bc03b7
* Version Independent ID: 6300d6ba-26a2-4dc3-0d1c-c7b06538b441
* Content: [How to: Customize Sorting in the Windows Forms DataGridView Control](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-customize-sorting-in-the-windows-forms-datagridview-control)
* Content Source: [docs/framework/winforms/controls/how-to-customize-sorting-in-the-windows-forms-datagridview-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-customize-sorting-in-the-windows-forms-datagridview-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @TRobins. This is in our backlog and we'll have to investigate what's going on.
