### ISSUE TITLE
DebugView returns a string

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#10521]
&gt; To better represent the content of expression trees, the `DebugView` property uses Visual Studio visualizers.

`DebugView` returns a `string`, and is no different than any other string in that respect, which can theoretically be examined using any visualizer that applies to `string` -- a custom visualizer, or any of the built-in visualizers that apply to `string` -- **Text**, **JSON**, **HTML**, **XML**.  (The built-in visualizers other than **Text** will not display any useful information.)

Now, a link to visualizers which target expression trees -- such as [ReadableExpressions](https://github.com/agileobjects/ReadableExpressions), or my own [ExpressionToString](https://github.com/zspitz/ExpressionToString) -- might be more useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd39193-a203-2326-7b45-79ea0015733f
* Version Independent ID: 76254616-be05-0da1-b706-6239941c2d20
* Content: [Debugging Expression Trees in Visual Studio (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @zspitz 

I've added it to our backlog. Do you want to create a PR to add these links and an example?

**Comment by zspitz** [comment]
@BillWagner I'd be willing, but is there some sort of official policy on links to third-party projects?

**Comment by BillWagner** [comment]
@zspitz We often refer to other open source projects in our docs. 

Make sure that the link text makes it clear that it is a 3rd party OSS project. Both licenses are MIT, which is one of the permissive licenses we support.

Finally, as you make the PR, make sure the focus remains *learning* not *selling your project*. 😸 Then, it's fine.

**Comment by zspitz** [comment]
@BillWagner 

> and an example

Do you mean a screenshot of one or both visualizers?

**Comment by BillWagner** [comment]
@zspitz Sorry that I didn't specify. I meant a code sample, with a screen shot of both visualizers.

Thanks for helping us improve the experience.

**Comment by zspitz** [comment]
@BillWagner Should the syntax used by `DebugView` be in a separate page?
