### ISSUE TITLE
Does not reflect the current release of ML.Net

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#10525]
Code sample does not reflect the API of the current NuGet package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925c8fe9-ba0b-bd2c-cea0-9d851ece8825
* Version Independent ID: 41cafff5-6418-2e54-3a0d-ee29fb1fca1f
* Content: [Cluster iris flowers using a clustering learner - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering)
* Content Source: [docs/machine-learning/tutorials/iris-clustering.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/iris-clustering.md)
* Product: **dotnet-ml**
* GitHub Login: @pkulikov
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@PeterPann23 what code sample do you refer to?

The [sample project](https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/IrisFlowerClustering) uses ML.NET v0.10; though it might skip using some latest additions.

**Comment by PeterPann23** [comment]
Hi pkulikov
I think that the Iris sample should be using the new API when mapping the class to the columns.

**Comment by pkulikov** [comment]
@PeterPann23 do you mean the `IrisData` class should use the [LoadColumn](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.loadcolumnattribute?view=ml-dotnet) attribute? That is, apply the approach from the [issue classification tutorial](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification). If yes, I think it's a good suggestion and I'll update the tutorial the next week.

@JRAlexander the price prediction tutorial also might use the `LoadColumn` attribute as the current usage of the `Column` attribute only specifies the source index and doesn't define the name of a column (which is not the case for the sentiment analysis tutorial).

**Comment by PeterPann23** [comment]
Yes, that's what I was thinking about, also to use the new method ( MLContext.Data.ReadFromTextFile<T>) that will actually throw you a null exception if you not add the annotation. Some annotations are needed for one and not for the other (textloaderarguments). A cleanup of the concept may be needed but that's a different topic. 

I feel for those that get introduced one should not learn the "old" way as well as understand the implications….

**Comment by pkulikov** [comment]
@PeterPann23 thanks for raising the issue; I've created two PRs that simplify data loading step as a result.

**Comment by pkulikov** [comment]
@PeterPann23 also it looks that the old API is going to be removed: dotnet/machinelearning#2593
