### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#10523]
I noticed in the third paragraph of Inheritance right after the example there is an omission. Destructors / finalizers can't be inherited either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Classes - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @Mandated 

I've added this to our backlog to address when we next update this content.
