### ISSUE TITLE
Broken .NET Framework feed link

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#10538]
https://nuget.org/api/v2/curated-feeds/dotnetframework/Packages/

https://github.com/dotnet/docs/blob/f1e3bca622a94e8e2055a5815fa209b4be43c449/docs/framework/get-started/the-net-framework-and-out-of-band-releases.md#L50

https://github.com/dotnet/docs/blob/f1e3bca622a94e8e2055a5815fa209b4be43c449/docs/framework/whats-new/index.md#L31

**Comment by Potapy4** [comment]
Same as #10465
