### ISSUE TITLE
Not working for UWP app

### ISSUE THREAD

**Issue by zipswich** [dotnet/docs#10530]
svcutil.exe /t:xmlSerializer MyUWPapp.exe  

throws the following error:

The file at: '...\MyUWPapp\bin\x64\Debug\MyUWPapp.exe' read via input argument'...\MyUWPapp\bin\x64\Debug\MyUWPapp.exe' does not appear to be an XML metadata file or a valid assembly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2e1125-4e7c-6f5a-2de2-ec7136dba025
* Version Independent ID: e103904c-569f-7fd1-5857-ae83e4871db4
* Content: [How to: Improve the Startup Time of WCF Client Applications using the XmlSerializer](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/startup-time-of-wcf-client-applications-using-the-xmlserializer)
* Content Source: [docs/framework/wcf/feature-details/startup-time-of-wcf-client-applications-using-the-xmlserializer.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/startup-time-of-wcf-client-applications-using-the-xmlserializer.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
This seems like product feedback, so closing. Please go to https://developercommunity.visualstudio.com/spaces/61/index.html to report product issues.
