### ISSUE TITLE
Why C#

### ISSUE THREAD

**Issue by Pianoman23** [dotnet/docs#10533]
Everything you do on this site is written in C#. I've been trying to find code in VB to write data retrieved from an Access database and viewed in a datagridview, back to the Access database after any changes have been made; but all I get on here is coding in C#!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c35134-b9f9-2dbb-d8b6-a94f5e827820
* Version Independent ID: 75c0290e-512f-f5aa-9f91-c9bcd16f43d9
* Content: [How to: Bind Objects to Windows Forms DataGridView Controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-bind-objects-to-windows-forms-datagridview-controls)
* Content Source: [docs/framework/winforms/controls/how-to-bind-objects-to-windows-forms-datagridview-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-bind-objects-to-windows-forms-datagridview-controls.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Hi @Pianoman23, the default language is C#, but if the page has the VB code available, you should be able to switch to it. This page does have the VB version as well.

![image](https://user-images.githubusercontent.com/12971179/52922950-b48de180-32d9-11e9-9e86-64c0cf2df9f2.png)

For this reason, I'm closing this issue. I hope this solves your issue!
