### ISSUE TITLE
'Fixed Value Buffer' page is incorrect regarding buffer overrun checks

### ISSUE THREAD

**Issue by john-h-k** [dotnet/docs#10545]
```
Note

Except for memory created by using stackalloc, the C# compiler and the common language runtime (CLR) do not perform any security buffer overrun checks. As with all unsafe code, use caution.

```
This is incorrect - fixed value buffer constructed types have the `UnsafeValueTypeAttribute` applied, and this invoked buffer overrun checks by the CLR, so they *do* have overrun checks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e17dd8-f60c-5a5d-517f-61bb95e94667
* Version Independent ID: c9d34513-107b-0b82-cf77-1dba0ee650cb
* Content: [Fixed Size Buffers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md)
* Product: **dotnet-csharp**
* GitHub Login: @johnkellyoxford
* Microsoft Alias: **johnkellyoxford**

**Comment by BillWagner** [comment]
Thanks for raising this issue @johnkellyoxford I've added to an upcoming sprint when we next update this topic.

**Comment by IEvangelist** [comment]
Hi @john-h-k,
This was a great observation and a good issue to post, I updated the docs accordingly in this pull: https://github.com/dotnet/docs/pull/18032 thank you!
