### ISSUE TITLE
C# conditional compilation

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#10546]
It seems that there is close to no explicit reference in any of the docs that discuss conditional compiler directives that these can be set in the Visual Studio "Conditional compilation symbols" input box. It may seem like nit picking but the documentation for #if really should mention this. It leaves the impression that we can only define these in the source code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for creating this issue @Korporal 

I've added it to our backlog to address when we next update that topic on a regular refresh cycle.

**Comment by Eddie-Hartman** [comment]
"Regular Refresh cycle" meaning over a year later.

**Comment by AraHaan** [comment]
@Eddie-Hartman more like meaning never.

**Comment by Rick-Anderson** [comment]
In Visual Studio, conditional compilation symbols can be defined on the **Build** tab of the project properties page. In the following image, the conditional compilation symbol `MULTI` is defined for the **DebugMulti** configuration:

![image](https://user-images.githubusercontent.com/3605364/79057100-0a69cb00-7bf9-11ea-87cc-cfcb5c6cc7d1.png)

From the preceding image, it looks like, at least for VS, the following statement in the doc is incorrect:

Other predefined symbols include the DEBUG and TRACE constants. You can override the values set for the project using `#define`. The DEBUG symbol, for example, is automatically set depending on your build configuration properties ("Debug" or "Release" mode).

@BillWagner let me know what you'd need for this, I might be able to PR it.

**Comment by matthew45052** [comment]
Isn't Visual Studio just a front-end?  Doesn't it ultimately invoke the command-line compiler csc.exe?  The mention of the -define compiler option above seems useful for defining preprocessor symbols across multiple files no matter what build system you're using, even a Unix-style "Makefile".
