### ISSUE TITLE
Private keys into source control?

### ISSUE THREAD

**Issue by cleberdantas** [dotnet/docs#10549]
The documentation states at the end:

"If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system."

Is it really a good thing to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee112577-3dfc-4963-fc1d-438f028b103b
* Version Independent ID: 881d4d7c-a8b4-4660-0f41-3aee640cf901
* Content: [Strong-Named Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies)
* Content Source: [docs/framework/app-domains/strong-named-assemblies.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/strong-named-assemblies.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by ed-karabinus** [comment]
I second this question. I have always thought that it is an exceptionally bad security practice to check any private cryptographic keys into a source control system (especially a publicly hosted one like GitHub), so I would like to see some persuasive rationale for this suggestion.

**Comment by mikedn** [comment]
See the warning near the top of the documentation page:

> Do not rely on strong names for security. They provide a unique identity only.

See also https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming. Perhaps this doc page should link to that.

**Comment by rokibullah** [comment]
I' lost my password

**Comment by djee-ms** [comment]
Ping - No matter what, checking in a private key is extremely bad practice. You are losing any kind of benefit here, even the unique identity, if anyone can grab the private key and sign a tempered assembly pretending to be the original one.

**Comment by mikedn** [comment]
> You are losing any kind of benefit here, even the unique identity, if anyone can grab the private key and sign a tempered assembly pretending to be the original one.

Strong naming isn't an anti tampering mechanism, except perhaps when using in conjunction with CAS. But CAS is dead.
