### ISSUE TITLE
Mention how to run the app after publishing

### ISSUE THREAD

**Issue by vivainio** [dotnet/docs#10543]
It's worth mentioning here that after "dotnet publish", you can run the app with "dotnet myapp.dll" (as it's non-obvious that "dotnet run" doesn't work anymore).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by HagenKnight** [comment]
In the Windows case, inside the \bin\dist\win folder, there's an exe file, just type the NameApplication and press enter in console mode.

**Comment by Thraka** [comment]
Why wouldn't `dotnet run` no longer work?

**Comment by Slaviusz** [comment]
`dotnet run` does not work in the published folder (or on remote server where only runtime is installed) as it expects a .csproj file and may try to build the project from sources.
`dotnet app.dll` or `dotnet exec app.dll` do work.

**Comment by Thraka** [comment]
ah yes, I failed to make the connection that it was being run in the published folder.
