### ISSUE TITLE
NavigationService error

### ISSUE THREAD

**Issue by kingshez021** [dotnet/docs#10540]
**Before you open an issue**

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

**Issue description**

    private void Button_Click(object sender, RoutedEventArgs e)
    {
        //View Expense Report
        ExpenseReportPage expenseReportPage = new ExpenseReportPage(); //Line 1
        this.NavigationService.Navigate(expenseReportPage); //Line 2
    }
Line 2 in above code gives following error for NavigationService:

'<invalid-global-code' does not contain a definition for 'NavigationService' and no accessible extention method 'NavigationService' accepting the first argument of type '<invalid-global-code>' could be found (are you missing a using directive or an assembly reference ?)

I have added the using System.Windows.Navigation;
I think the problem is coming from 'this' part of this.NavigationService.Navigate(expenseReportPage);

Please Help!

Thanks in advance.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [2.1 ] .NET Core
- [ 4.6.1] .NET Framework
- [x] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by mairaw** [comment]
Where are you seeing this @kingshez021?

**Comment by mairaw** [comment]
Closing this due to the lack of information @kingshez021. Please get back to us with information about the article where you're seeing this so we can follow up.
