### ISSUE TITLE
Metadata.FindNavigation - Add information about unstable API

### ISSUE THREAD

**Issue by martinkotula** [dotnet/docs#10552]
First of all thanks for the great guide it's really a great starting point for building applications.

One question though - according to the API documentation for Metadata.FindNavigation this method is not recommended to use in user code.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.internal.entitytype.findnavigation?view=efcore-2.1

 &gt; This API supports the Entity Framework Core infrastructure and is not intended to be used directly from your code. This API may change or be removed in future releases.

Could you elaborate on that or at least add a disclaimer in the guide that this feature is not yet stable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1c070c-b2ff-f29d-21df-bcc7bf9dd39d
* Version Independent ID: 975107e9-0fc2-b867-d917-595412cbe422
* Content: [Implementing the infrastructure persistence layer with Entity Framework Core](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@CESARDELATORRE @divega can you look at the feedback about one EF Core API being used in the microservices e-book?

**Comment by mvelosop** [comment]
Hi @martinkotula, thanks for the heads up!

You're right, that code snippet is obsolete will update it in a few days.

**Comment by mvelosop** [comment]
Closing this issue, as it was solved in the latest general book review.
