### ISSUE TITLE
CI Server cannot run this command, restore will not succeed

### ISSUE THREAD

**Issue by AndersBillLinden** [dotnet/docs#10553]
Running `dotnet build foo.sln` does not restore nuget packages successfully when running the command from a CI Server (using CruiseControl.net as administrator). Running the same command from a CLI works flawlessly.

Error being `error NU1100: Unable to resolve 'Serilog.AspNetCore (&gt;= 2.1.1)' for '.NETCoreApp,Version=v2.2'.`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [.NET Core Command-Line Interface (CLI) Tools - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/index.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by AndersBillLinden** [comment]
This line is only one of many in the same form. It seems like every nuget package results in an error.

**Comment by AndersBillLinden** [comment]
If I had am running this once in the CI Server

````
nuget sources add nuget.org
````

it will from now on succeed restoring packages.

**Comment by AndersBillLinden** [comment]
The conclusion is that dotnet.exe not necessarily is aware of nuget sources but can be assisted by the older nuget command to learn from where to fetch packages (it does not even know about nuget.org).

**Comment by Thraka** [comment]
Sounds like your CI server isn't configured for the nuget package source. You can create a [nuget config file](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) and deploy it with your app to the CI server. This would have the definition for the nuget server in it. that should solve your problem. 

If it doesn't please follow up! I'll close this issue. Thanks!
