### ISSUE TITLE
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

### ISSUE THREAD

**Issue by atifalibhatti** [dotnet/docs#10550]
I am getting following error when I try to execute dotnet svcutil --help/url/wsdl file or anyting.

Unable to generate deps.json, it may have been already generated. You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d ": C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [WCF svcutil tool overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
I can't seem to replicate this. Can you uninstall and install the tool again?

**Comment by Thraka** [comment]
Closing due to lack of response. Feel free to reopen when you get a chance to respond.

**Comment by 3bdulra7eem** [comment]
I suddenly faced the problem during working on the project

I already added some web services earlier but now I can't add any and getting the same error
I updated my sdk to latest (I'm using .net core 2.1)

.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]




I tried checking my %temp% path for any semicolons to be removed but still facing the issue
help me please

**Comment by Thraka** [comment]
@3bdulra7eem I discovered the team that made this tool has a repository at https://github.com/dotnet/wcf/issues where you could get help about this tool.
