### ISSUE TITLE
NOT Filter?

### ISSUE THREAD

**Issue by adam-geisen** [dotnet/docs#10556]
Is there a NOT operator for these filters?

Lets say that I mark *only* my integration tests with a test category. Could I specify a filter to run all tests that aren't TestCategory="Integration"?

It would be nice if there was a section that lists each operator and exactly what they do. It might seem basic but knowing that "&" is an AND filter and "|" is an OR filter would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb70526f-d02c-2b6c-3d34-0f4cac5809f0
* Version Independent ID: e4443d71-7131-ae9b-447d-9ac0762a99fc
* Content: [Running selective unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests)
* Content Source: [docs/core/testing/selective-unit-tests.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/selective-unit-tests.md)
* Product: **dotnet-core**
* GitHub Login: @smadala
* Microsoft Alias: **mairaw**

**Comment by kristiansamuelsson** [comment]
You can use the ! operator shown with FullyQualifiedName for TestCategory as well. For example:
dotnet test --filter TestCategory!=Integration

**Comment by Thraka** [comment]
@adam-geisen Does this answer your question? Thanks!

**Comment by adam-geisen** [comment]
Yes. It would still be nice for a table of the valid operators.

**Comment by Thraka** [comment]
I would think you might have better luck finding something like that in the testing framework or runner (like Visual Studio) docs. I did quick search and came up with this, I think this is what you're looking for 😄 

https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md

I'm going to close now. Thanks for the question :)

**Comment by adam-geisen** [comment]
I see, thank you. That is exactly the doc I was looking for. Didn't know what to search!

You learn new things every day 👍

**Comment by Thraka** [comment]
hehehe no worries!

**Comment by deivyd321** [comment]
But I want to ignore a specific project without adding categories on each test. Is there a "Does NOT contains" operator something like `!~`?
