### ISSUE TITLE
Handling exceptions in tasks, error

### ISSUE THREAD

**Issue by avifarah** [dotnet/docs#10569]
Your document under “Handling exceptions in tasks” points out that Task.WaitAny needs a try/catch.  This is an error.  Task.WaitAny does not throw an exception.  (Neither does Task.WhenAny.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050b2b8a-8b8d-c2de-f03d-b2ebb26a9c95
* Version Independent ID: 7d23f296-9a5e-ca0a-08c3-f718d0a90d94
* Content: [Task-based asynchronous programming - .NET](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming)
* Content Source: [docs/standard/parallel-programming/task-based-asynchronous-programming.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-based-asynchronous-programming.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your comment, @avifarah. The exceptions thrown by Task.WaitAny are documented at <https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.waitany>. Most are, admittedly, the result of developer error (including a null Task in the array, supplying a negative timeout interval, not passing an array of Tasks to the method, disposing of the Task), but nevertheless the method call is capable of throwing exceptions.
 I'll close this issue. If you disagree, please feel free to respond.

**Comment by avifarah** [comment]
Ron,

Thank you for your comments

Close is the correct action.
--Avi
