### ISSUE TITLE
Force vs to check if the value exist?

### ISSUE THREAD

**Issue by Layarion** [dotnet/docs#10562]
Anyway to have it output an error if the supplied value for the name doesn't exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb46beb-4fad-b7f9-443b-785037e2a6d8
* Version Independent ID: cda4b124-d708-842b-0ee6-87265652174d
* Content: [&lt;paramref&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/paramref)
* Content Source: [docs/csharp/programming-guide/xmldoc/paramref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/paramref.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Visual Studio will report these problems as warnings in the **Error List** pane
