### ISSUE TITLE
No good example

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10578]
@GYOERFT commented on [Tue Feb 19 2019](https://github.com/dotnet/docs.de-de/issues/126)

When overriding ToString at Derived the output would be the derived ToString. The example suggests "as" lets you act like handling the base class instead

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4bc2f58f-8fbc-9ff2-2312-8a5715536f1f
* Version Independent ID: 1dbd0d51-e1dc-8970-93f8-2a44fa71f7ba
* Content: [as – C#-Referenz](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/as)
* Content Source: [docs/csharp/language-reference/keywords/as.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/language-reference/keywords/as.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the user is making a comment about the example
best

**Comment by BillWagner** [comment]
The first example in this topic is not a good example. It's correct, but it's not a typical use of `as`. Futrhermore, it mixes type conversions with virtual and overridden methods in a way that's not enlightening for beginners.
