### ISSUE TITLE
What XSD standard does .net support? (1.0, 1.1 and so on)

### ISSUE THREAD

**Issue by himpatel** [dotnet/docs#10570]
Can't you write this clearly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2f743d-3bc8-6c82-1704-2b5096ff4d8e
* Version Independent ID: 59195d85-4748-4680-d310-7d761e5779c0
* Content: [Configuration file schema for the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/)
* Content Source: [docs/framework/configure-apps/file-schema/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/index.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
This article seems to be unrelated to this question as this is schema documentation for the config file. Doing a quick search on the web I found that .NET Framework only supports XSD 1.0. There are various other nuget packages that can support other versions.
