### ISSUE TITLE
Outdated in respect to various new automations done by Visual Studio

### ISSUE THREAD

**Issue by progalgo** [dotnet/docs#10573]
Running a client currently does not require starting a stand-alone server. Visual Studio will automatically host required services when you start a client. Everything just got a bit easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81879896-7161-3352-eecb-87a2158dc003
* Version Independent ID: 286eb468-4007-fc0d-1d33-76139225d565
* Content: [How to: Use a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-use-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-use-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-use-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I believe this is fixed in the tutorial series rewrite coming out today.
