### ISSUE TITLE
Repeated sentence.

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10581]
"So if a client unexpectedly terminates, by default the service will not be notified, or if a client unexpectedly terminates, the service will not be notified. " This sentence repeats itself.

I suspect this should read "So if a client unexpectedly terminates, by default the service will not be notified, or if a service unexpectedly terminates, the client will not be notified."

It would also be nice to know what happens if you call a callback method after the client has terminated. Do you get an exception? If so which one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745e854-3edd-3ae2-148c-2b93d287853d
* Version Independent ID: f5f63468-abd5-f8ad-8a06-07c0c6d986bc
* Content: [Duplex Services](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/duplex-services)
* Content Source: [docs/framework/wcf/feature-details/duplex-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/duplex-services.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!

**Comment by Thraka** [comment]
I fixed this in commit c3192ca

I'm going to open a PR to clarify the exception type
