### ISSUE TITLE
Missing Definition

### ISSUE THREAD

**Issue by GYOERFT** [dotnet/docs#10583]
Hey,
you never define the term "unmanaged type" within .NET documentation. The term itself is missleading since its implies that those types might not be managed by CLR as in case of unmanaged code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8e658d6-0283-e114-70a2-3fda367987e2
* Version Independent ID: 283ff73b-aa7f-dcf7-b476-9698b76ca68c
* Content: [sizeof - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sizeof)
* Content Source: [docs/csharp/language-reference/keywords/sizeof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/sizeof.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The definition for an *unmanaged* type is carefully hidden in the C# spec in the section on [pointer types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code#pointer-types)

The following text (taken from the spec) should be paraphrased and added here:

>An *unmanaged_type* is any type that isn't a *reference_type* or constructed type, and doesn't contain *reference_type* or constructed type fields at any level of nesting. In other words, an *unmanaged_type* is one of the following:

> *  `sbyte`, `byte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`, `char`, `float`, `double`, `decimal`, or `bool`.
> *  Any *enum_type*.
> *  Any *pointer_type*.
> *  Any user-defined *struct_type* that is not a constructed type and contains fields of *unmanaged_type*s only.
