### ISSUE TITLE
Missing description for the usage of ==

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10582]
@mcxtlong commented on [Wed Feb 20 2019](https://github.com/dotnet/docs.zh-cn/issues/336)

https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=6

这个教程中并没有介绍 ==的用法

edit by @mairaw: added topic info
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=6)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the user reports missing information in the original documentation
Rough translation:

> This tutorial does not describe the usage of ==

**Comment by NextTurn** [comment]
Why can't you change the issue title?

**Comment by BillWagner** [comment]
This should be updated to introduce the `==` (and likely `!=` tokens before the challenge.

In the section on `if`, a small sample should be added.

**Comment by mairaw** [comment]
@BillWagner I've updated the title to an English description of the problem
