### ISSUE TITLE
What is the default package directory? 

### ISSUE THREAD

**Issue by Matthew-Bonner** [dotnet/docs#10593]
There is mention of the ability to change the package directory but no mention of what the default location is. Could this be added to the documentation please. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by NextTurn** [comment]
`~/.nuget/packages/`
Both on Windows and Unix.

**Comment by NextTurn** [comment]
- Windows: `%userprofile%\.nuget\packages`
- Mac/Linux: `~/.nuget/packages`

[Managing the global packages, cache, and temp folders](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)

**Comment by Thraka** [comment]
I think at minimum a link to the nuget docs could be added: https://docs.microsoft.com/nuget/consume-packages/managing-the-global-packages-and-cache-folders

**Comment by Thraka** [comment]
@mairaw Should this be linked to #9256 ? Something you could pull in while you do the CLI?

**Comment by mairaw** [comment]
Sure, I've added to the next sprint and assigned it to myself.
