### ISSUE TITLE
Tab history behaves strangely in Firefox

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1059]
The tab history (what you see when you hold the back button) behaves strangely for me on docs.ms/dotnet in Firefox.

For example, I follow this workflow:
1. Open [the _dotnet command_ article](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet) in a new tab.
2. Click on a link to [the _dotnet-build_ article](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build).

After opening the _dotnet_ article and waiting for it to fully load, the history already contains two items:
1. dotnet command (current)
2. dotnet command

![](http://imgur.com/1BtRr6z.png)

When I click on the link to _dotnet-build_ and wait for it to load, the history now contains three items:
1. dotnet-build (current)
2. dotnet-build
3. dotnet command

![](http://imgur.com/vjt5lw1.png)

This makes navigation using the back and forward buttons hard.

I can observe this behavior in Firefox 48.0.2 on Windows 10, but Edge 38 or Internet Explorer 11 do not seem to have this issue.

**Comment by mairaw** [comment]
I've also opened an internal bug to track this.

**Comment by BillWagner** [comment]
@mairaw Can you check the internal issue to see if it's fixed?

**Comment by mairaw** [comment]
Bug is not fixed yet and I can still repro. Issue moved to https://github.com/MicrosoftDocs/feedback/issues/229.
