### ISSUE TITLE
Don't use Wait or WaitAll

### ISSUE THREAD

**Issue by fekberg** [dotnet/docs#10627]
Avoid using an example of Wait and WaitAll when discussing asynchronous principles. This can be very confusing to readers. Instead leverage the async and await keywords, as you can now use async main in C#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ee8ce8-e45b-c404-88a8-417a405989b9
* Version Independent ID: f186b087-b6f9-baae-c1f7-5244ac07269f
* Content: [Task Cancellation](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation)
* Content Source: [docs/standard/parallel-programming/task-cancellation.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-cancellation.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@fekberg Thank you for pointing this out. I've added this issue to the backlog and flagged it for community participation.
