### ISSUE TITLE
Comparing interfaces to abstract classes is missleading

### ISSUE THREAD

**Issue by earizon** [dotnet/docs#10631]
- Abstract classes are designed to define common behavior of     sub-classes (life-cycles hooks, ..)

- Interfaces are designed to define orthogonal and non-related functionality among them (security vs visualization vs persistence, ...), and most of the time declare one or very few methods. 

Newcomers will be confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 594cb1b7-c9c9-5f33-fca7-2f1872c095a9
* Version Independent ID: 2ed35b23-7ffd-0d95-a2f0-02e3ccc4f8a7
* Content: [How to: Explicitly Implement Members of Two Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces)
* Content Source: [docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@earizon

I agree with your comment, but I can't find any mention of abstract base classes on this page. Can you point out the text that will mislead newcomers?

**Comment by earizon** [comment]
@BillWagner: My fault!. (Too many open tabs at once). The incorrect URL was actually:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/inheritance 
("....An interface is a reference type that is somewhat similar to an abstract base class that consists of only abstract members....")
