### ISSUE TITLE
Integer not integral

### ISSUE THREAD

**Issue by glooms** [dotnet/docs#10632]
Under value types-simple types it says signed and unsigned integral which I assume is supposed to say integer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by glooms** [comment]
Seems that this is a consequent choice throughout the document. Why? Are integers called integrals in C#?

**Comment by NextTurn** [comment]
**Integral type** is a computer science terminology. An **integer** is an **integral type**.

**Comment by mairaw** [comment]
Some topics on this:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#integral-types
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/integral-types-table
