### ISSUE TITLE
VS intellisense with doc comments from `file` attribute?

### ISSUE THREAD

**Issue by deap82** [dotnet/docs#10633]
Is there any way to get docs included with the `file` attribute way to show up as "intellisense"in VS 2017/2019, as it does when the comments are directly in the code file? For example as a tooltip when hovering a member at the point of use. It does not work for me when the doc is in a referenced xml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a nice idea @deap82 

The very brief answer is that you'd have to build the XML file from the project to get the included text in the XML output. Then, if that file is delivered with the assembly, it gets displayed.

We should add a tutorial that covers ow to build this and consume it.

@gewarren Would this be something that should be covered in the VS docs, or is it better in the C# docs?

**Comment by gewarren** [comment]
@BillWagner It sounds like perhaps it makes more sense in the VS docs. I'll assign this to myself.

**Comment by BillWagner** [comment]
Thanks @gewarren.

can you mention me when you create the doc? I'll link to it from the pertinent docs in the C# Guide for better visibility.

**Comment by deap82** [comment]
@billwagner But what about a multi project solution where one of the projects has these included files and other projects in the solution uses it? Will that also work? 

My use case is not an assembly being distributed to others.

**Comment by BillWagner** [comment]
@deap82 I don't know the answer right now. @gewarren and I will investigate.

**Comment by gewarren** [comment]
@BillWagner Could you transfer this issue (use "Transfer issue" on right hand side) to MicrosoftDocs/visualstudio-docs? I don't seem to have permissions to transfer it.

**Comment by BillWagner** [comment]
@gewarren I can’t. I just looked and “transfer issue” doesn’t support transferring from one org (`dotnet`) to another (`MicrosoftDocs`)

We’ll have to do the old close and reopen. Do you want me to use Zendesk to do that?

**Comment by gewarren** [comment]
@billwagner - That would be great; thanks!

**Comment by BillWagner** [comment]
Crud. That's not supported either.  😞

**Comment by mairaw** [comment]
I think the only way is to manually move it between orgs, unfortunately.

**Comment by gewarren** [comment]
@jillre This work should be done in the VS docs. I'm not sure if you want to track it with this issue or create a new issue in the VS repo.

**Comment by deap82** [comment]
@gewarren Where can I find the updated docs? Will that also solve my concern in comment from March 5th; https://github.com/dotnet/docs/issues/10633#issuecomment-469544447 ?

**Comment by gewarren** [comment]
> @gewarren Where can I find the updated docs? Will that also solve my concern in comment from March 5th; #10633 (comment) ?

Sorry for the confusion; by "should be done" I meant "should happen". That is, it hasn't happened yet...

**Comment by gewarren** [comment]
Closing this issue since it's being tracked in the Visual Studio docs repo now. @deap82 You might want to subscribe to notifications on that issue.

![image](https://user-images.githubusercontent.com/24882762/68249424-a6046900-ffd3-11e9-80dc-5f8567f6724c.png)

**Comment by deap82** [comment]
@gewarren, I don't understand how to find that issue. Could you please provide a link?

**Comment by jillre** [comment]
@deap82 here's the issue in the visualstudio-docs repo: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4279
