### ISSUE TITLE
Pressing Enter in search text box in API reference should not refresh the page in Firefox

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1063]
When using the Search Reference text box in API reference, search results appear as I type, so pressing <kbd>Enter</kbd> at the end is not necessary. But when I do it anyway, out of habit, the whole page refreshes, which causes the search results to disappear. I don't think this should happen.

This happens in Firefox 49 on Windows 10. Edge 38 or Internet Explorer 11 do not have this issue.

**Comment by mairaw** [comment]
I've also opened an internal bug to track this.

**Comment by BillWagner** [comment]
@Mairaw can you check the internal issue to see if this is fixed?

**Comment by mairaw** [comment]
I can't find the bug anymore and I also cannot repro this. Maybe it was fixed. Can you still repro @svick?

**Comment by svick** [comment]
No, I can't repro this anymore, so I'm closing this.
