### ISSUE TITLE
Try Dot net

### ISSUE THREAD

**Issue by fredyadriano90** [dotnet/docs#10636]
https://try.dot.net/ is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3c4c67-250d-50ac-35e7-b11a20d13ba0
* Version Independent ID: 2dab9569-8748-1325-d9b7-78c3f728deef
* Content: [String interpolation in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation)
* Content Source: [docs/csharp/tutorials/string-interpolation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/string-interpolation.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I can't repro this. If you're still having issues, please open an issue at https://github.com/dotnet/try. Or are you talking about the experience on docs?
