### ISSUE TITLE
Remove redundant path segments from internal URLs

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#10653]
There are a number of `[](../)` relative links starting with redundant path segments. They were generated when articles were migrated from MSDN, and could be removed now to make links short and clear.

For example,

https://github.com/dotnet/docs/blob/b0eb506433d5c29cab3e07186aee3cd80e76ab80/docs/framework/wpf/advanced/properties-wpf.md#L17

can be changed to

```markdown
 - [Dependency Properties Overview](dependency-properties-overview.md)
```

Related to #9968

/cc @mairaw

**Comment by mairaw** [comment]
Thanks for filing this @NextTurn! There are a few examples on the repo where we've done this already. 

e.g. https://github.com/dotnet/docs/pull/9992

**Comment by NextTurn** [comment]
See #10660 for a **great** example.

**Comment by nemrism** [comment]
For the [framework] section, here is the remaining work:

Links | Files | Directory
------|-------|----------
2795 | 735 | ./docs/framework/unmanaged-api/debugging
533 | 182 | ./docs/framework/unmanaged-api/diagnostics
2578 | 461 | ./docs/framework/unmanaged-api/hosting
1233 | 284 | ./docs/framework/unmanaged-api/metadata
1810 | 288 | ./docs/framework/unmanaged-api/profiling
1686 | 417 | ./docs/framework/wcf/diagnostics/tracing
2283 | 373 | ./docs/framework/wcf/feature-details
921 | 204 | ./docs/framework/wcf/samples

I could handle those changes in the coming days, but it might generate around 30 more PRs of 100~ files to review.

@mairaw, would you like me to continue pushing them or hold on a bit?

**Comment by NextTurn** [comment]
@mairaw If we adopt an automated approach to complete the work, do you just need to review the scripts instead of the changes?

**Comment by nemrism** [comment]
Hi there,

@mairaw could you tell me/us what to do with the remaining work?

I'd like to continue to clean up the links path but was wondering how you prefer to get them packed in PRs.

**Comment by nemrism** [comment]
hi guys
still got PR #14064 open and no answer on what we do with the remaining work... are you still interested with this cleanup?

**Comment by NextTurn** [comment]
Take it easy. These changes take time to review.

**Comment by nemrism** [comment]
Yeah I totally understand, however the 15 other PRs were already merged
And it also takes time to resolve conflicts if the branch remains like this for months ;)

**Comment by nemrism** [comment]
> Take it easy. These changes take time to review.

And I just want to know if I continue working on this or take something else

**Comment by mairaw** [comment]
I started reviewing that one but got busy with other deliverables. Will try to finish the review soon. Apologies for the delay.

**Comment by mairaw** [comment]
You can choose whether you want to continue this one or work on something different.

**Comment by nemrism** [comment]
> I started reviewing that one but got busy with other deliverables. Will try to finish the review soon. Apologies for the delay.

I can totally understand with the core 3.0 launch ;)

**Comment by nemrism** [comment]
> You can choose whether you want to continue this one or work on something different.

I'll do what you prefer... I'm open to suggestions, but as you can see (https://github.com/dotnet/docs/issues/10653#issuecomment-525652922), there is kind of a hurricane coming if I batch work on this

**Comment by mairaw** [comment]
My suggestion since our team is still overwhelmed with PRs and behind on 3.0 work.
Let’s table this one for now and avoid tsunamis. 😊
Maybe do one of these per month to continue to make progress but not make them all at once.

**Comment by nemrism** [comment]
I've seen that others are also doing a great job on this, @NextTurn & @Youssef1313 for example.
I'll do as suggested and will do that as a background task.

Great to read you again @mairaw, have a great day all

**Comment by mairaw** [comment]
Yes @nemrism, you're all doing great contributions to our docs and we really appreciate it!
Smaller PRs are much easier for our team to review as well. So if you'd like to continue to make progress towards this one, file a couple of PRs that are smaller in size and they will probably get reviewed and merged much faster.

**Comment by IEvangelist** [comment]
Please feel free to use this new functionality from the Docs Authoring Pack when it is released tomorrow: https://github.com/microsoft/vscode-docs-authoring/pull/585

**Comment by NextTurn** [comment]
@IEvangelist How can I execute this command on all candidate files in a directory?

**Comment by IEvangelist** [comment]
> @IEvangelist How can I execute this command on all candidate files in a directory?

Hi @NextTurn - I'll see what I can do, but I originally didn't add that functionality. Although, that sounds like the desired way to do this.
