### ISSUE TITLE
TLS issue when running the samples

### ISSUE THREAD

**Issue by tudort-iquest** [dotnet/docs#10662]
For some reasons, at least under Windows 10, most samples run without error only after the following line is added at the beginning:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
Otherwise an WebException is thrown:
'The request was aborted: Could not create SSL/TLS secure channel.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2dd5bf-6e11-49e5-d88c-5858873770bc
* Version Independent ID: ae9cb1d8-4f64-43fa-e16d-1db60067a430
* Content: [Fine-Tuning Your Async Application (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/fine-tuning-your-async-application)
* Content Source: [docs/csharp/programming-guide/concepts/async/fine-tuning-your-async-application.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/fine-tuning-your-async-application.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That is an interesting problem @tudort-iquest 
We're not exactly sure why you're seeing that behavior. We'll be investigating.
