### ISSUE TITLE
Can I create a tool with .NET Framework?

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#10665]
If *dotnet tool* is actually a **nuget**, can I create a nuget compiled to **.NET Framework** and provide it as *dotnet global tool*?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET Core Global Tools - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard can you help with this question? Can a global tool have a netframework value as TFM?

**Comment by KathleenDollard** [comment]
We're not set up for that. Can you explain more about why you want to use .NET Framework for a tool?

**Comment by baruchiro** [comment]
It's simple. (And not).
I want to provide a tool, but the tool is compiled only in `.NET Framework`.

And you may say **Why? `.NET Core` is the best now!**, and I agree.
But, if we want to work against a `.csproj` files, we can use [`Microsoft.Build.Evaluation.Project`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project) that support `.NET Framework` only, or parse the `.csproj` file ourselves (which is very difficult, considering that most of the information is a default and not listed in `.csproj`.)
