### ISSUE TITLE
Property change notifications: Several language improvements can improve the code sample

### ISSUE THREAD

**Issue by jonasnordlund** [dotnet/docs#10675]
Several language improvements were made to C# that let the code sample become both cleaner and safer.

1. Use `OnPropertyChanged(nameof(PersonName))` rather than `OnPropertyChanged("PersonName")` to guard against misspelled names or changed variable names.

2. The entire OnPropertyChanged method body can now be rewritten as, which is also suggested by Visual Studio 2017:
```cs
    protected void OnPropertyChanged(string name)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
```

3. (as a tip?) Use the attribute `[CallerMemberName]` in the method argument, as in: `OnPropertyChanged([CallerMemberName] string name)`. In this case, you can simply call OnPropertyChanged() as such, with no arguments, and the calling property's name will be automatically filled in as a string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02332683-7d8a-ab31-6036-13748529a212
* Version Independent ID: 6892cbbc-eaae-f9a4-49df-0a6abb3a999a
* Content: [How to: Implement Property Change Notification](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-property-change-notification)
* Content Source: [docs/framework/wpf/data/how-to-implement-property-change-notification.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-implement-property-change-notification.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thank you for the suggested changes, @jonasnordlund. Would you like to submit a PR to make the changes? The source code is found in the dotnet/samples repo at <https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Wpf/SimpleBinding/CSharp/Person.cs> for C# and <https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_Wpf/SimpleBinding/VisualBasic/Person.vb> for Visual Basic. The instructions for submitting a PR are found in the [Contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).

**Comment by johnromby** [comment]
when using `[CallerMemberName]` remember to set a default value for the parameter.

Ex. `OnPropertyChanged([CallerMemberName] string name = null)`

**Comment by jfontsaballs** [comment]
I have also seen this other form, which allows for simpler getter/setter.

``` C#
using System.ComponentModel;

namespace SDKSample
{
  // This class implements INotifyPropertyChanged
  // to support one-way and two-way bindings
  // (such that the UI element updates when the source
  // has been changed dynamically)
  public class Person : INotifyPropertyChanged
  {
      private string name;
      // Declare the event
      public event PropertyChangedEventHandler PropertyChanged;

      public Person()
      {
      }

      public Person(string value)
      {
          this.name = value;
      }
      
      public string PersonName
      {
          get => name;
          set => OnPropertyChanged(ref name, value);
      }

      // Create the OnPropertyChanged method to raise the event
      protected void OnPropertyChanged<T>(ref T var, T value, [CallerMemberName] string name = null)
      {
            var = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
      }
  }
}
```

**Comment by IntegerMan** [comment]
I would like to take this on over the next few days as my first docs pull request.

I'm thinking of expanding it to show two examples, one using `nameof` in a similar vein to the current form and another using the more efficient but less beginner-friendly `OnPropertyChanged` with `CallerMemberName` that @jfontsaballs mentioned.
