### ISSUE TITLE
Error NETSDK1061, unclear what to do

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#10671]
I have a project targeting .NET Core 2.1. It builds fine on its own. My separate build script also performs a publish for a framework-dependent version, a stand-alone for win-x64 and a stand-alone for linux-arm. After running this build script with Visual Studio 2017 opened in the background, VS shows the error NETSDK1601, pointing to this page. After reading the entire article, I'm no wiser than before and cannot resolve the bug.

Here's the build script:

```
if exist bin\Release\netcoreapp2.1 rd /s /q bin\Release\netcoreapp2.1
dotnet clean -v m -c Release -nologo
dotnet publish -c Release -nologo
dotnet publish -c Release -r win-x64 -nologo
dotnet publish -c Release -r linux-arm -nologo
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a901ae9f-cc78-b5de-a031-b4671c7a85ac
* Version Independent ID: 89276cf0-167d-c108-f9d6-f5bfe1317851
* Content: [Runtime roll forward for .NET Core self-contained app deployments. - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection)
* Content Source: [docs/core/deploying/runtime-patch-selection.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/runtime-patch-selection.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Does [this](https://developercommunity.visualstudio.com/content/problem/324161/upgrade-breaks-the-build.html), @ygoe?

**Comment by ygoe** [comment]
@rpetrusha No, it doesn't provide a solution. I don't use the --no-restore option. I still don't know what's happening. It seems like the build tools get confused with all this version rolling.

**Comment by michaelveloz** [comment]
I'm also having the same 1061 Error. Easy to create: Using VS 2019, create a console .core solution. To that add a .core library. Make the app call a function in the library. Publish them for "stand alone". Get error 1061. I have uninstalled the one and only version of the .net core libraries on my PC and that didn't fix anything. After reading the docs above, it's still not clear what I should be doing, that I'm not.

**Comment by mairaw** [comment]
@KathleenDollard can you or your team help with this feedback?

**Comment by KathleenDollard** [comment]
@maira These look like either an SDK bug and should move to the github/dotnet/cli repo.

@michaelveloz and @ygoe we need more information, including the RID you are targeting (your .csproj file with anything you are uncomfortable sharing changed) and the results of 

```
dotnet --info
```

at the command line

**Comment by ygoe** [comment]
See also https://stackoverflow.com/questions/55456375/net-core-publish-and-version-errors

This is trivial to reproduce:

1. Open VS 2017 latest stable
2. Create a new .NET Core Console Application
3. Rebuild the solution to resolve any errors displayed in the editor/solution explorer
4. Create the file `build.cmd` next to the .sln file with the content below (adjust the project name in the `cd` line)
5. Run that build script

You can now see the error NETSDK1061 appear in Visual Studio (still open, don't close it).

```
@echo off
set TargetFramework=netcoreapp2.2

cd ConsoleApp6

:: Clean
if exist bin\Release\%TargetFramework% rd /s /q bin\Release\%TargetFramework% || goto error
dotnet clean -v m -c Release -nologo || goto error

:: Build
powershell write-host -fore Blue Building and publishing...
dotnet publish -c Release -nologo || goto error

powershell write-host -fore Blue Publishing for linux-arm...
dotnet publish -c Release -r linux-arm -nologo || goto error

:: Exit
powershell write-host -fore Green Build finished.
timeout /t 2 /nobreak >nul
exit /b

:error
pause
```

Here's the output of `dotnet --info`:

```
.NET Core SDK (gemäß "global.json"):
 Version:   2.2.202
 Commit:    8a7ff6789d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

This output is just from my home machine. The office machine has the same behaviour and may show other dotnet info.

**Comment by KathleenDollard** [comment]
@ygoe 

Thank you for the repro.

This isn't a docs issue but either a Visual Studio or an SDK issue.

I'm happy to route this for you, but you will lose the ability to track it. 

If you use the feedback item in the upper right of Visual Studio (an icon) and just paste this message in the will let you get feedback on the resolution and will allow them to contact you if they have a question. Please feel free to add @KathleenDollard if you'd like me to also keep an eye on it.

Because I think that will be a better experience for you, I will not move this unless you ask me to. 

Thanks again for taking the time to tell us about this.

**Comment by jeffschwMSFT** [comment]
@KathleenDollard this issue has come through the system and can be found here: https://developercommunity.visualstudio.com/content/problem/555208/netsdk1061-error-when-publishing-for-runtime.html.  I presume this issue can now be closed.

**Comment by KathleenDollard** [comment]
The docs issue can be closed.
