### ISSUE TITLE
Cosmetic(ish) - last/first name

### ISSUE THREAD

**Issue by f3** [dotnet/docs#10673]
Complete example has the labels for first and last names reversed in the `GetRandomEmployees` method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acea0dac-37dd-bea4-7545-3ee37556a033
* Version Independent ID: 4d4b3dbc-adf4-5f92-cec5-7393156a3535
* Content: [Walkthrough: Using BatchBlock and BatchedJoinBlock to Improve Efficiency](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-using-batchblock-and-batchedjoinblock-to-improve-efficiency)
* Content Source: [docs/standard/parallel-programming/walkthrough-using-batchblock-and-batchedjoinblock-to-improve-efficiency.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-using-batchblock-and-batchedjoinblock-to-improve-efficiency.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @f3 and good catch! 

We're adding this to our backlog and to our community contribution project.
That code can be found at
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Misc/tpldataflow_batchdatabase/cs/dataflowbatchdatabase.cs
and
https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_batchdatabase/vb/dataflowbatchdatabase.vb

**Comment by f3** [comment]
Closing - see dotnet/samples [#673](https://github.com/dotnet/samples/pull/673)
