### ISSUE TITLE
CS0649 only describes a field warning when it can be triggered by other cases

### ISSUE THREAD

**Issue by demacianult** [dotnet/docs#10698]
The warning CS0649 is a bit misleading. It only describes that a private or internal field declaration can trigger the warning when this case actually generates a CS0649 violation:

```c#
public class Foo
{
  private class Bar
  {
    public int baz;  // this line generates a CS0649 violation
  }
}
```

It is likely correct since `baz` can be definitively known to not be assigned since it exists in the same compilation unit. The warning should probably be updated to say something about any fields within the same compilation unit to include private class definitions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edc658f-d05a-33e2-4bf7-1bd36073124d
* Version Independent ID: f681c446-1e96-6cc3-3356-be13cdd1fda7
* Content: [Compiler Warning (level 4) CS0649](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0649)
* Content Source: [docs/csharp/misc/cs0649.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0649.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @demacianult 

For readers that don't already understand the scoping rules, that description would be confusing.
