### ISSUE TITLE
Featured content container in .NET Home page doesn't render properly

### ISSUE THREAD

**Issue by badersur** [dotnet/docs#1069]
In the [.NET Home page](https://docs.microsoft.com/en-us/dotnet/index), the **FEATURED CONTENT** section renders outside the page:

``` html
<section id="featured" class="container">
    <h2 class="section-heading"><span class="icon icon-lightbulb-checked"></span> Featured Content</h2>
    <div class="features row">
        <ul class="column-half">
            <li><a href="articles/core/index">Get started with .NET Core</a></li>
        </ul>
        <ul class="column-half">
            <li><a href="https://docs.asp.net">Get started with ASP.NET Core</a></li>
        </ul>
    </div>
</section>
```

Removing `width: 100%;` rule from the `container` class solves the issue!!

The issue occurs in Firefox 48 and Chromium 52.0.2743.116 (Developer Build). OS: Ubuntu 16.04 (64-bit)

**Comment by mairaw** [comment]
I could repro that.
@DuncanmaMSFT @adkinn can you please take a look? I'll be filing a bug internally to track this.

**Comment by mairaw** [comment]
@badersur can you test this again? The engineering team resolved our internal bug as fixed and we also have a new home page since last month. Thanks!

**Comment by badersur** [comment]
@mairaw Your new home page is awesome! Thanks for letting me know about it :)

**Comment by mairaw** [comment]
You're welcome! I'm glad you like it. I'm closing this issue then.
