### ISSUE TITLE
Hand waving of "major step"

### ISSUE THREAD

**Issue by bh4017** [dotnet/docs#10719]
In this document, you list the major steps for completion of the task.  The first major step is listed as "Obtain a list of all print servers".

The very first thing you do in this document is to wave away this first major step, citing the interests of simplicity.  Well, you may have achieved a simple document this way but it is incomplete because you've completely jumped over a step which you admit yourself is necessary for the rest of the task.  If you don't have a list of printservers in the first place, you can't do anything else.

I recommend that you add the information about obtaining a list of all print servers.  If it's complicated, well then the task is complicated whether you decide to add the information or not - but at least your document is complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95492a8f-e616-66a4-d4d7-b93e5333ee8a
* Version Independent ID: d8808bfb-69c2-2e96-56da-8e191537139e
* Content: [How to: Remotely Survey the Status of Printers](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-remotely-survey-the-status-of-printers#feedback)
* Content Source: [docs/framework/wpf/advanced/how-to-remotely-survey-the-status-of-printers.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-remotely-survey-the-status-of-printers.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by dmschlab** [comment]
I to would also like to comment on the lack of completeness. This is up there with not providing the list of using statements....particularly when A multiple references contain the same class names or B not providing the reference to link to so example code can work.
