### ISSUE TITLE
Abridged Reference: builtin types / Reference types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10729]
This article will include:

**Reference types**
- object
- dynamic
- string
- array
- delegate

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by BillWagner** [comment]
There isn't a keywords or operator page for arrays. 
I need to find where that's covered in the language reference.

**Comment by pkulikov** [comment]
> That should be addressed. It should be either on this new page, or in its own page in this section.

It might be a good idea to consolidate ALL the articles from the following programming guide part:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/index

**Comment by BillWagner** [comment]
I like that plan @pkulikov I’ll make a new issue for that in the language reference consolidation project.
