### ISSUE TITLE
Visual Basic code 

### ISSUE THREAD

**Issue by RichEme** [dotnet/docs#10727]
What is the VB code for Creating the class library project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826876cc-d286-3e10-515e-bba12d85f1f4
* Version Independent ID: 5dfbe5a8-f7be-617d-c9ff-db2fa2d6a396
* Content: [Build a C# .NET Standard library with  Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@RichEme Hi! It is the next article listed in the TOC on the left side. Here is a link: https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio

I'll close this issue as I think I've answered your question.

**Comment by RichEme** [comment]
Thanks. That fixed it.
