### ISSUE TITLE
Error in example of "One compilation creates a two-file assembly" for C++

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#10737]
In example of "One compilation creates a two-file assembly" for C++, was written example with two separate command vs on command (see part that begin from "(!)Note..").

And also the formatting for two variants of compiling "a two-file assembly" made isn't clear  (wrong).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d43111-f590-3f6b-7b5d-c4845a510679
* Version Independent ID: 0fb96825-06c5-b980-d683-da7c34d67ecc
* Content: [How to: Build a Multifile Assembly](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-build-a-multifile-assembly)
* Content Source: [docs/framework/app-domains/how-to-build-a-multifile-assembly.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/how-to-build-a-multifile-assembly.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thanks for reporting this. Seems like a quick and easy fix, I'll get this done.

**Comment by Thraka** [comment]
@DSivtsov Was there a wording problem with the doc or just formatting of the examples? I've fixed the formatting but I'm unsure if you were pointing out there was a problem with the explanation or something.

**Comment by DSivtsov** [comment]
Hi, Andy De George

Now It's Ok.
Thank you, good job
