### ISSUE TITLE
Abridged Reference: operators / relational operators

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10738]
The relational operators are:

- `<` (less than)
- `>` (greater than)
- `<=` (less than or equal)
- `>=` (greater than or equal)

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by pkulikov** [comment]
Regardless of the discussion in #10757, I think those six articles already might be consolidated into two: equality operators and relational operators. As equality covers much broader set of operand types than ordering, I would keep those two articles separate.
