### ISSUE TITLE
Abridged Reference: Operators / type testing and assignment

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10739]
The operators on this page are:

- `is` (and is with assignment)
- `as`
- `=` (assignment)
- `?` (nullable) `!` (null forgiveness)
- `typeof` operator
- `(T)` explicit cast

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by pkulikov** [comment]
@BillWagner could you please assign this issue to me, as I'm going to work on it next.

**Comment by pkulikov** [comment]
@BillWagner two thoughts about the content of the overview.

First, why did we include the `typeof` operator in this list? The assignment operator `=` makes up a good story with the cast `()` operator, which hooks the `as` operator, which chains the `is` operator. Ultimately, ending up with the `is` operator with the type pattern assignment. In this story, the `typeof` appears an outsider. Also, as far as I understand it's not a good idea to use `typeof` for type-testing as in
```csharp
object whatever = ...;

// NO!
if (whatever.GetType() == typeof(int))
{
  int x = (int)whatever;
  // ...
}

// Better:
if (whatever is int x)
{
  // ...  
}
```

Then, I suggest to exclude the `typeof` operator from this overview and consider it separately as in #10741. What do you think? What is the main use case for `typeof`? Reflection?

Second, how much to talk about the `is` operator? I mean: to cover ALL [pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#pattern-matching-with-is)? Or only the type pattern? By the way, there is currently a lot of duplication in the docs with regards to pattern matching. Compare the linked above section from the `is` article with this one from the `switch` article:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#-pattern-matching-with-the-switch-statement

Again, the type and constant patterns are described.

**Comment by BillWagner** [comment]
@pkulikov 

I'll start with the second question because it informs the others:

One scenario to use `typeof` is to get an exact match, rather than a looser check with `is`.  It can be important in checking equality:

```csharp
public class B
{
   private int counter; 

  public override bool Equals(object o)
 {
    return (o is B b) && (this.counter == b.counter);
  }
}

public class D : B
{
}

// incorrect behavior:

var d = new D();
var b = new B();

if (b.Equals(d))
  Console.WriteLine("They are different types. Probably shouldn't be equal!");
```

Instead, you'd want to check that the types match exactly:

```csharp
  public override bool Equals(object o)
 {
    if (o.GetType() != typeof(B))
      return false;
    return (o is B b) && (this.counter == b.counter);
  }
```

I think that because `is` and `typeof` are different tests, keeping them on the same article would help readers understand that better. That's a mild preference though. 

> Second, how much to talk about the is operator? I mean: to cover ALL pattern matching? Or only the type pattern? 

I would cover the type pattern. My first thought is to mention the constant pattern, but only in passing. I would not go into depth. (here too, a mild preference at best).

Happy to look at any outlines or drafts as you progress.

**Comment by pkulikov** [comment]
@BillWagner 

> One scenario to use `typeof` is to get an exact match, rather than a looser check with `is`.

Thanks for that insight. I'll keep `typeof` in then and cover this scenario.
