### ISSUE TITLE
Abridged Reference: operators / arithmetic operators

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10736]
The arithmetic operators are:

- `++` (prefix and postfix)
- `--` (prefix and postfix)
- `+` (unary and binary addition of numeric operands)
- `-` (unary and binary subtraction of numeric operands)
- `*` (multiplication)
- `/` (division)
- `%` (remainder)
- corresponding compound assignment operators
- `checked`/`unchecked`

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

As noted in the comments on #10731 this includes increment and decrement operators even though those are in the primary operators list in the spec.

**Comment by pkulikov** [comment]
@BillWagner as you've suggested, I start with this issue. As soon as the first draft is ready, I'll open a PR to get an early feedback on structure and direction.

One thing to clarify about `checked`/`unchecked`. I guess the [dedicated pages](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked-and-unchecked) for corresponding *keywords* stay as they are. Those are referenced from the overview, which covers [`checked`/`unchecked` operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#the-checked-and-unchecked-operators).

Also, the following section asks for the move to the overview:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#arithmetic-overflow
