### ISSUE TITLE
Abridged Reference: Statements / iteration statements

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10748]
This will cover the following statements:

- `do` / `while`
- `for`
- `foreach` /  `in`
- `while`

Sub-tasks are:

- [x] Create the new articles
- [x] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [x] Redirect existing content to the new articles.
- [x] Remove old articles.
- [x] Update all links in the .NET Content

**Comment by pkulikov** [comment]
@BillWagner now, as the operators and expressions are consolidated under https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/, I would like to consolidate the C# statements under the *language-reference/statements* folder. Is that something you would welcome?

**Comment by BillWagner** [comment]
@pkulikov 

> I would like to consolidate the C# statements under the language-reference/statements folder. Is that something you would welcome?

Yes! That would be fantastic. Thank you.

**Comment by pkulikov** [comment]
@BillWagner 

> Should I reopen this issue?

Yes, please. And the other two I've found as well: #10746 and #10749

So, the idea is like with the operators: consolidate similar statements into one article.
