### ISSUE TITLE
Abridged Reference: Operators / other operators and tokens

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10741]
These don't fit any group, and should have a single page for each operator.

- `?` `:` (conditional operator). Somehow, it feels out of tune with the logical operators.
- `??` (null coalescing). It also feels not in the logical operations group. Most probably, it's because I limit logical operations to those on `bool` operands.
- `+`, `+=` (string concatenation and delegate combination)
- `-`, `-=` (delegate removal)
- `::` (namespace alias qualifier)
- `nameof`
- `sizeof`
- `await`
- `new` operator
- `stackalloc` operator
- `=>` (lambda declaration)

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by BillWagner** [comment]
Operators that were missing in the first review that should be added:

- `new` operator
- `stackalloc` operator

**Comment by pkulikov** [comment]
@BillWagner to confirm: the listed operators should have a separate page for each of them.

Given that, I  suggest (they are already merged in the list in the issue text) to merge pages for the `+` and `+=` operators (`-` and `-=` pair as well) and put focus at these pages on the non-arithmetic behavior.

**Comment by BillWagner** [comment]
@pkulikov That would be perfect.

**Comment by pkulikov** [comment]
@BillWagner could you please assign this issue to me, as the half of it is already done.

The remaining operators to revise and move to the operators' TOC:

- [ ] `::` (namespace alias qualifier)
- [ ] `nameof`
- [ ] `sizeof`
- [ ] `await`
- [ ] `new` operator

Not in the original list, but should the following two also be included?

- [ ] `default`
- [ ] `delegate`
