### ISSUE TITLE
Abridged Reference: Operators /  logical operators

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10740]
The logical operators are:

- `&` (logical AND for `bool` operands)
- `|` (logical OR for `bool` operands)
- `^` (logical exclusive-OR for `bool` operands)
- `!` (logical negation)
- `&&` and `||` (conditional logical AND and OR operators)
- `true` and `false` operators (**note:** it's still might be a separate article on its own and only referenced from the overview) 
- corresponding compound assignment operators

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by pkulikov** [comment]
Should the xor-operator `^` be in the list as well?

I've seen the logical not `!` in the list of unary operators, but it would be confusing not to include this operator into the list of logical operators.
