### ISSUE TITLE
Abridged Reference: Compiler options

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10756]
This is a major consolidation task.  The current TOC has a page for each option. (59 in total). I propose consolidating into one larger page and using H2s for each option:
- [-addmodule](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/addmodule-compiler-option.md)
- [-appconfig](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/appconfig-compiler-option.md)
- [-baseaddress](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/baseaddress-compiler-option.md)
- [-bugreport](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/bugreport-compiler-option.md)
- [-checked](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/checked-compiler-option.md)
- [-codepage](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/codepage-compiler-option.md)
- [-debug](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/debug-compiler-option.md)
- [-define](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/define-compiler-option.md)
- [-delaysign](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/delaysign-compiler-option.md)
- [-deterministic](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/deterministic-compiler-option.md)
- [-doc](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/doc-compiler-option.md)
- [-errorreport](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/errorreport-compiler-option.md)
- [-filealign](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/filealign-compiler-option.md)
- [-fullpaths](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/fullpaths-compiler-option.md)
- [-help, -?](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/help-compiler-option.md)
- [-highentropyva](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/highentropyva-compiler-option.md)
- [-keycontainer](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/keycontainer-compiler-option.md)
- [-keyfile](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/keyfile-compiler-option.md)
- [-langversion](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/langversion-compiler-option.md)
- [-lib](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/lib-compiler-option.md)
- [-link](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/link-compiler-option.md)
- [-linkresource](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/linkresource-compiler-option.md)
- [-main](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/main-compiler-option.md)
- [-moduleassemblyname](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/moduleassemblyname-compiler-option.md)
- [-noconfig](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/noconfig-compiler-option.md)
- [-nologo](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/nologo-compiler-option.md)
- [-nostdlib](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/nostdlib-compiler-option.md)
- [-nowarn](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/nowarn-compiler-option.md)
- [-nowin32manifest](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/nowin32manifest-compiler-option.md)
- [-optimize](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/optimize-compiler-option.md)
- [-out](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/out-compiler-option.md)
- [-pathmap](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/pathmap-compiler-option.md)
- [-pdb](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/pdb-compiler-option.md)
- [-platform](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/platform-compiler-option.md)
- [-preferreduilang](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/preferreduilang-compiler-option.md)
- [-publicsign](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/publicsign-compiler-option.md)
- [-recurse](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/recurse-compiler-option.md)
- [-reference](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/reference-compiler-option.md)
- [-refout](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/refout-compiler-option.md)
- [-refonly](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/refonly-compiler-option.md)
- [-resource](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/resource-compiler-option.md)
- [-subsystemversion](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/subsystemversion-compiler-option.md)
- [-target](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-compiler-option.md)
- [-target:appcontainerexe](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-appcontainerexe-compiler-option.md)
- [-target:exe](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-exe-compiler-option.md)
- [-target:library](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-library-compiler-option.md)
- [-target:module](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-module-compiler-option.md)
- [-target:winexe](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-winexe-compiler-option.md)
- [-target:winmdobj](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/target-winmdobj-compiler-option.md)
- [-unsafe](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/unsafe-compiler-option.md)
- [-utf8output](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/utf8output-compiler-option.md)
- [-warn](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/warn-compiler-option.md)
- [-warnaserror](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/warnaserror-compiler-option.md)
- [-win32icon](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/win32icon-compiler-option.md)
- [-win32manifest](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/win32manifest-compiler-option.md)
- [-win32res](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/win32res-compiler-option.md)

**Comment by mairaw** [comment]
Should we add this to the vendor work items project? Or are you planning to do this yourself?

**Comment by BillWagner** [comment]
As part of this (or in conjunction with this task), there are eight options listed in the [compiler options by category](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-by-category) page that are not documented.  They are:

- modulename
- analyzer
- additionalfile
- embed (all source and specific files variants)
- ruleset
- parallel
- checksumalgorithm
- incremental (obsolete option)
