### ISSUE TITLE
BC40056 Namespace doesn't contain any public members

### ISSUE THREAD

**Issue by RichEme** [dotnet/docs#10758]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	BC40056	Namespace or type specified in the Imports 'UtilityLibraries' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	StringLibraryTest	C:\X_vb\ClassLibraryProjects\StringLibraryTest\UnitTest1.vb	3	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET Standard class library with .NET Core in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?tabs=vb)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Did you declare the classes in that library as `Public`?

**Comment by mgilligan173** [comment]
I had to replace Imports UtilityLibraries with Imports StringLibrary.UtilityLibraries -- then in the subroutine DirectCallWithNullorEmpty, replace StringLibrary.StartsWithUpper(word) to StringLibrary.UtilityLibraries.StartsWithUpper(word). I also used the release for the Project and the UnitTest (avoid using the debug). This solution worked for me.

**Comment by Thraka** [comment]
OK So this sounds like a bug. Thank you for filing it. I think the C# code is also wrong.

**Comment by tdykstra** [comment]
Fixed by #18557
