### ISSUE TITLE
Abridged Reference: Unsafe code

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10754]
Cover the following concepts:

- Unsafe contexts
- Pointer types
- Fixed and moveable variables
- Pointer conversions
- Pointers in expressions
- The fixed statement
- Fixed size buffers
- Stack allocation
- Dynamic memory allocation

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by pkulikov** [comment]
Notes:
- The fixed and moveable variables are covered in the section about the [address-of operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#address-of-operator-). That might be extracted from there.
- The whole "Pointers in expression" part can be a one-liner link to the [Pointer related operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators) article.
