### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by MaisamRazai** [dotnet/docs#10762]
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm glad this helped @MaisamRazai 

I'll close this as kudos.
