### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rsocol** [dotnet/docs#10779]
The link to the "draft nullable reference types" specification proposal on GitHub is broken; it is now pointing to https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types-specification.md#the-null-forgiving-operator (I think that page was moved to the ¨csharp-8.0¨ subfolder a few days ago).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @rsocol. I see the change in the following PR:
https://github.com/dotnet/csharplang/pull/2256/files

Would you like to submit a fix for this?
This page explains how: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
