### ISSUE TITLE
Entire source / project

### ISSUE THREAD

**Issue by leoseccia** [dotnet/docs#10777]
These examples are really good. It would be great if you provided the entire project / source for each one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80478f2-591c-b4f0-8d40-08ac381ea774
* Version Independent ID: 16483fde-0255-71b5-1c58-da8914640c6b
* Content: [Find and Highlight Text Using UI Automation](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/find-and-highlight-text-using-ui-automation)
* Content Source: [docs/framework/ui-automation/find-and-highlight-text-using-ui-automation.md](https://github.com/dotnet/docs/blob/master/docs/framework/ui-automation/find-and-highlight-text-using-ui-automation.md)
* Product: **dotnet-framework**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mairaw** [comment]
This is a good suggestion @leoseccia and I believe our engineering team has some plans on how to make it better to find where the sample is coming from.

But for now, if you look at the Markdown raw version for the article, you can try to discover where the samples are. They will be either inline or come from the dotnet/samples repo.

Like in this case, they come from this folder for C#:
https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_Wpf/FindText/CSharp

I hope this helps.
