### ISSUE TITLE
[NewTopic] Facade DLLs in the Publish Output

### ISSUE THREAD

**Issue by josalem** [dotnet/docs#1080]
# [NewTopic] Façade DLLs in the Publish Output

When you publish an application targeting the full framework from Visual Studio, you will end up with several `System.*` DLLs local to your application.  Most of them are sub 50 KB, and appear to only be facades for versions installed on the system.  I haven't found any documentation under ASP.NET Core or .NET Core that explains this behavior of the build system.  It can be confusing if you don't know how to check where those libraries are actually getting loaded from at runtime.
## Requests for new Topics
1. Tell us where this topic should go in the Table of Contents.
   - .Net Core Guide -> Deploying
2. Write an abstract
   - When deploying a .NET Core application that targets the full framework, you can expect there to be a set of `System.*` DLLs included local to the compiled application.  These are forwarder libraries for matching up .NET Standard APIs with their locations on the system.
3. Fill in an outline
   - What is included in the published output directory (e.g., where will these DLLs be)
   - Which DLLs are facades 
   - Explanation of why (e.g., .NET Standard -> .NET Framework or .NET Core)

**Comment by BillWagner** [comment]
I'm not sure how relevant this still is given all the investments made since it was written.

@josalem Do you think this is still needed? If not, can you close it?

**Comment by BillWagner** [comment]
@josalem @richlander Is this still relevant?
