### ISSUE TITLE
Self initialising setter

### ISSUE THREAD

**Issue by hhvdblom** [dotnet/docs#10814]
I don't know if this is the right place but I did put a question on stackoverflow like this : 
https://stackoverflow.com/questions/54801495/how-to-make-a-self-initialising-setter-set-accessor-without
May be the C# language can be extended with self initialising setters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I provided an answer to your StackOverflow question.  Closing here, as it's not something we'd directly address on docs.
