### ISSUE TITLE
How to migrate AssemblyTrademarkAttribute

### ISSUE THREAD

**Issue by DzonnyDZ** [dotnet/docs#10819]
This document does not mention ``AssemblyTrademarkAttribute``, nor I found anywhere mentioned how to handle it in the new project format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
From my research, it doesn't seem like it's supported anymore. However, I did find this workaround. Add this to your csproj. This sets an assembly attribute on your assembly at build time 👍 

```xml
<ItemGroup>
  <AssemblyAttribute Include="System.Reflection.AssemblyTrademarkAttribute">
    <_Parameter1>My Trademark</_Parameter1>
  </AssemblyAttribute>
</ItemGroup>
```
