### ISSUE TITLE
No way to install preview channel (3.0)?

### ISSUE THREAD

**Issue by goliat43** [dotnet/docs#10818]
The script doesn't seem to work for installing 3.0 preview.

Would be very useful to enable this in some way. I need to set up a build server (dockerized) that builds using 3.0 preview. Since this script doesn't work for 3.0  will have to create my own script. Once 3.0 is out of preview it seems very annoying to have to re-script the entire setup once again..

&gt;dotnet-install.ps1 -channel 3.0

Exception calling "Invoke" with "0" argument(s): "Failed to download https://dotnetcli.blob.core.windows.net/dotnet/Sdk /3.0/latest.version.  StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.', Version: 1.1, Content: Syste m.Net.Http.StreamContent, Headers:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@johnbeisner can you help with this feedback about the script not working to download 3.0 preview?

**Comment by secana** [comment]
Ran into the same problem. Support to install .Net Core 3.0 preview would be great.

**Comment by goliat43** [comment]
Tip is to use Chocolatey where there is a .NET core 3.0 preview since 1th of March.
https://chocolatey.org/packages/dotnetcore-sdk/3.0.100-preview3-010431

And latest 2.2
https://chocolatey.org/packages/dotnetcore-sdk/2.2.104

So 3.0 can be installed with:
choco install dotnetcore-sdk --pre
And latest 2.2 with:
choco install dotnetcore-sdk

Works like a charm. Pity Microsoft took the eyes of the ball and ended up outside the field instead. "Official" story about installing .NET core and sdk is a mess. Chocolatey works but seems to be a bit late with updates sometimes.

**Comment by secana** [comment]
@goliat43 works perfectly! Thx alot for the tip.

**Comment by shirhatti** [comment]
Just stumbled across this issue when searching for something else.

Use `dotnet-install.ps1 -Channel release/3.0.1xx` to install released 3.0 builds.
The names of all the channels are listed in this table- https://github.com/dotnet/core-sdk#installers-and-binaries

**Comment by mairaw** [comment]
Thanks @shirhatti. I'll review the docs to add some explanation about this next time I review it.
