### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by KIDr55** [dotnet/docs#10815]
I find the tutorials very well laid out and useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c598765c-1c4d-bf43-f5c6-a894f3af37ea
* Version Independent ID: 3b77a3ea-1d26-a462-05c5-40bb61919c97
* Content: [Build a Visual Basic .NET Standard class library in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio#next-step)
* Content Source: [docs/core/tutorials/vb-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/vb-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for your feedback, @KIDr55. We're pleased that you find the tutorials helpful.
