### ISSUE TITLE
framework 4.7.2 Link references not working on the content page

### ISSUE THREAD

**Issue by praveenkpamani** [dotnet/docs#10816]
we need advise, we are unable to upgrade .net framework 4.7.2 on Window server 2012RT. 
Installation always shows framework already installed, we couldnt verify the same. all our code builds are failing, pointing out that required framework unavailable. 

Instructions links on this page arent working. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f53be3-8485-2c49-060a-c9c05f1b979d
* Version Independent ID: 7bb3a7a3-1636-9787-0651-fb6811792559
* Content: [Install the .NET Framework on Windows 8.1](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-8-1)
* Content Source: [docs/framework/install/on-windows-8-1.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/on-windows-8-1.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@vivmishra can someone on your team help diagnose this?

@praveenkpamani were you able to determine which version you have installed by following these instructions?
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#find-net-framework-versions-45-and-later-in-the-registry

**Comment by SusLes** [comment]
Hi, @praveenkpamani …

To help us diagnose this, can you please provide us with the full install logs and let us know what OS platform you're trying to install on?

Thanks!

**Comment by praveenkpamani** [comment]
Hi Susan,

I didn't had issue in installing .net framework.

I believe they are Anchor Links which aren't working in documentation.


Thanks,
Praveen Pamani

________________________________

**Comment by mairaw** [comment]
Thanks for the information @praveenkpamani and apologies for the inconvenience.

@SusLes @vivmishra the FwLink 863255 is still pointing to Microsoft homepage. Can you please update that to the appropriate target?

**Comment by mairaw** [comment]
The link on the button though is still working: https://www.microsoft.com/net/download/thank-you/net472?utm_source=ms-docs&utm_medium=referral

You can use that one to download 4.7.2.

**Comment by mairaw** [comment]
This is issue was resolved. Thanks for letting us know @praveenkpamani!
