### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10826]
If you enter the code as described and compile in VS 2017 you get a couple of warnings about the Contract and Service name not being correct in the app.config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd7ff99-1ecd-5c6f-bf75-a5a777414d76
* Version Independent ID: 1b7f988f-92a0-ee09-7a0a-4d81ba918ac8
* Content: [How to: Implement a Windows Communication Foundation Service Contract](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-implement-a-wcf-contract)
* Content Source: [docs/framework/wcf/how-to-implement-a-wcf-contract.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-implement-a-wcf-contract.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Related to reviewing #9957
