### ISSUE TITLE
Visual Studio 2012! A little out of date maybe?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10823]
Visual Studio 2012! A little out of date maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fce5df1b-9bc6-23a5-0ace-de64c08b5fb1
* Version Independent ID: fc7d7802-e187-0e1e-cf7c-c79df19c4c90
* Content: [Getting Started Tutorial1](https://docs.microsoft.com/en-us/dotnet/framework/wcf/getting-started-tutorial)
* Content Source: [docs/framework/wcf/getting-started-tutorial.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/getting-started-tutorial.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I'm currently reviewing a rewrite to all of the articles in this tutorial. #9957

**Comment by Thraka** [comment]
This was fixed but the bug wasn't closed
