### ISSUE TITLE
Problem with AggregateException remark

### ISSUE THREAD

**Issue by andrewtyped** [dotnet/docs#10821]
At the bottom of the article we have 

```
In this example, AggregateException should never be thrown, but it is caught here because in real-world scenarios any other exceptions besides OperationCanceledException that are thrown from the task delegate are wrapped in a OperationCanceledException.
```

Should the second occurrence of `OperationCanceledException` instead be `AggregateException`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073f1486-9fa6-a17c-d649-d4ae5a36b8d8
* Version Independent ID: 55cc3625-d0a5-3422-0d27-945823a0c64b
* Content: [How to: Listen for Multiple Cancellation Requests](https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-multiple-cancellation-requests)
* Content Source: [docs/standard/threading/how-to-listen-for-multiple-cancellation-requests.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/how-to-listen-for-multiple-cancellation-requests.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Yes, it should be, @andrewtyped Would you like to submit a PR to make the correction? The instructions are in [the contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).
