### ISSUE TITLE
Last example.

### ISSUE THREAD

**Issue by DAllanCarr** [dotnet/docs#10830]
Is the last sample suppose to use stackalloc? Seems a little misleading if not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe1ee66-e839-82f5-16fa-fc1f9f66c787
* Version Independent ID: eeabec3f-826b-7d84-0d54-7a9df7e57d2a
* Content: [fixed Statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/fixed-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/fixed-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/fixed-statement.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @DAllanCarr 

You are correct. We'll update this when we next update this topic.
