### ISSUE TITLE
Improve SEO for our content

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1083]
We need to review our metadata (title, description, keywords), our topic title and first paragraph of each topic to make sure that our content is correctly tagged for search engines to find it.

Also need to ensure that our guidelines are complete in terms of SEO guidance.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
