### ISSUE TITLE
Mention the difference between double and Double.

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#10849]
This document should mention the types that differ from other types only in their capitalized first letter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables#feedback)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I think the best way to fix this is to add a link to the [built in types](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/built-in-types-table) table in the language reference.

I've added the "up-for-grabs" label and added this to our community project.

Thanks for pointing this out @daveyostcom Would you like to create a PR to address this?

**Comment by daveyostcom** [comment]
I'll leave this to those who are closer to it.

**Comment by jwwicks** [comment]
@daveyostcom If no one else has picked this up I can link the major bullet points to the Types section document mentioned by @BillWagner.

**Comment by jwwicks** [comment]
@BillWagner @rpetrusha @daveyostcom

Upon looking into this it's odd that there isn't a reference-types-table page. Any reason this doesn't exist?

![image](https://user-images.githubusercontent.com/702596/56076886-cdbb8780-5d8a-11e9-893b-a2b82f735e20.png)

**Comment by BillWagner** [comment]
I think the concern is that there are so many reference types that ship with any .NET Standard implementation.

We should consider one where the types are limited to those referenced in the C# language specification as being required for the language. That's a smaller sets, and fits in with the content in the C# Guide.

**Comment by jwwicks** [comment]
@BillWagner I opted out of creating a page in this instance but I think if we follow your suggestion and limit it to the ones in the spec we'll be golden. Should I create a page similar to the [value types table page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types-table) ? New ticket?

**Comment by BillWagner** [comment]
@jwwicks Thank you, and I like this idea:

> Should I create a page similar to the [value types table page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types-table) ? New ticket?

I think the right answer for this table is to limit it to the reference types which are synonyms for a C# keyword (for example, `string` is `System.String`,  `object` is `System.Object`, `delegate` is `System.Delegate` and so on, including `Array`.)  I'm debating if this section should call out all the types required by the language spec. That would include a number of `Attribute` classes, a number of exception types, and several interfaces. Those are all noted in language sections that pertain to the dependency, but aren't called out in a single location (other than the standard itself).

What are your thoughts?

**Comment by jwwicks** [comment]
> I think the right answer for this table is to limit it to the reference types which are synonyms for a C# keyword ...

@BillWagner I think that makes the most sense.

> I'm debating if this section should call out all the types required by the language spec. 
> What are your thoughts?

My only concern would be items like System.ValueType or System.Enum etc... where we have classes for the value types. We'd just need to include the same kind of [notes](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#the-systemvaluetype-type) I think.

As for Attributes, Interfaces and Exceptions if you think listing all of them would be helpful I'm game.
