### ISSUE TITLE
Calibration, normalizing, scoring missing from the glossary

### ISSUE THREAD

**Issue by sfilipi** [dotnet/docs#10846]
The glossary of machine learning terminology should have an entry for calibrating scores, normalizing(feature scaling) features and scoring models. 

[AB#1530397](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1530397)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156946fa-db1e-6ac6-af7b-ae84983f47bf
* Version Independent ID: 5c8df0fc-7076-f26c-7a61-71cc1510b4c2
* Content: [Machine learning glossary - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/glossary#transform)
* Content Source: [docs/machine-learning/resources/glossary.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/glossary.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @sfilipi. This has been added to the backlog.

**Comment by natke** [comment]
We have calibration, but not normalization and scoring
