### ISSUE TITLE
Can you rewrite the article?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#10852]
@x13xxxswatxxx commented on [Fri Mar 01 2019](https://github.com/dotnet/docs.ru-ru/issues/176)

For me personally, the article seemed complicated.
5 times (2 days), already tried to start over and just got more confused.
The beginning is more or less clear, but then comes the use of event, EventHandler &lt;class&gt;, creating classes for it, using lambda expressions for add, remove, as if we work with them every day.
why internal to create an extension?
It is not clear which class to insert search into.
where did lister come from and how to apply at all.

Лично для меня, статья показалась сложной.
5 раз (2-х дней),  уже пробовал начинать сначала и только больше запутался.
Начало более менее понятно, но далее идёт применение event, EventHandler&lt;class&gt;, создание классов под него, применение лямбда выражений для add, remove,  как будто мы работаем с ними каждый день.
зачем internal, чтобы создать расширение?
Непонятно в какой класс нужно вставлять search.
откуда взяли lister и как вообще применить.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc
* Version Independent ID: d2078536-1ee3-5b60-3872-f2635d245cc2
* Content: [Стандартные шаблоны событий .NET](https://docs.microsoft.com/ru-ru/dotnet/csharp/event-pattern#feedback)
* Content Source: [docs/csharp/event-pattern.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/event-pattern.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user's comment is about the original documentation
best

**Comment by Nick87Phillips** [comment]
Same, I wish this was clearer. I think too many assumptions are made by the writer about prior reader knowledge. Although, I've been reading through the C# concepts docs in order, it would still help a lot if individual bits of code here could be defined a bit better. Assume we are idiots please

**Comment by robloo** [comment]
I've made a new issue as well. This article does not follow the event conventions in .net (links below). The delegate name is very misleading and events are invoked directly instead of used an "OnFileFound" method for derived classes.

https://docs.microsoft.com/en-us/dotnet/standard/events/
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event

**Comment by SalFicara** [comment]
I agree with the other comments and the example isn't even correct as stated by robloo. Almost better to just remove it in the short-term.

**Comment by maxpavlov** [comment]
This article is simply terrible. Came here to refresh my knowledge of recommended patters in .NET and realized the previous MSDN article about this was way, way more clear and correct. Who proofreads this? It's like a main doc of the huge technology company, how come the quality is so poor. Imagine if the author writes more articles like this. @Microsoft, please re-assign the author for the official docs :)
