### ISSUE TITLE
Article on Type Signatures

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1086]
There should be an article on type signatures for F#.  It should explain what they are, describe general patterns, provide examples explaining what each example mean, and show how they're used.

**Comment by eriawan** [comment]
@cartermp I think I will take this :)
Could you tell me where to put this article? Under which section this type signature documentation should be located?

**Comment by cartermp** [comment]
@eriawan Awesome!  The article should go under the F# Language Reference section of the docs.  We can figure out a good position within that section when you make a PR.

**Comment by eriawan** [comment]
@cartermp  thanks! I'll create a WIP PR for F# type signature tomorrow 😄

**Comment by BillWagner** [comment]
@cartermp  Does [this article](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/signatures) fix this issue?

**Comment by cartermp** [comment]
@BillWagner Not quite. This covers signature files, which do contain F# signatures. The article should probably be renamed to "Signature Files". I think there is still value in having a separate article or section about type signatures.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
