### ISSUE TITLE
azure devOps build pipeline, VS Build Solution, Solution path

### ISSUE THREAD

**Issue by ChrisFg** [dotnet/docs#10876]
**\*.sln
Resolves to what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
I'm not sure that I understand your question, @ChrisFg. In the article, there are two file paths that refer to a *.sln file. The first is an absolute file path. The second (C:Projects\apilibrary\apilibrary.sln) is a relative path. The file path that it resolves to depends on the current directory on drive C:. For example, if c:\users\public\documents is the current directory, the path resolves to C:\user\public\documents\Projects\apilibrary\apilibrary.sln. Does that answer your question?

**Comment by ChrisFg** [comment]
I’m sorry Ron I didn’t provide sufficient context, plus there was a typo in the text string of my question.

I am working with Azure devOps, build pipeline, task Visual Studio Build, Solution
which shows a value of  **\*.sln.
As here:
[cid:image001.jpg@01D4D396.CA7F6A10]

I went to the page
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats
looking for an explanation of the **\*.sln format, specifically the left hand ** term but didn’t find the term listed, hence the question.

I thought that might be an omission.

Regards, Chris

**Comment by ChrisFg** [comment]
The description of the file match pattern **\*.sln is found here:
[](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml )

**Comment by ChrisFg** [comment]
The description for the file match pattern **\*.sln is found here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml
