### ISSUE TITLE
Unreal

### ISSUE THREAD

**Issue by IBrooke** [dotnet/docs#10888]
The example in this description is just so unreal.  I really cannot imagine a real-life scenario like this example, "Add a handler", "Cause the Event", "Remove the handler", it's just too fake.  How about showing a real example, where the code adds a handler, and the handler is removed sometime later either in a different routine or even in the handler itself, maybe after the code adding the handler has been called multiple times, because that's often what happens in real code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7771f230-ac9e-7310-e606-94bd9fc84f29
* Version Independent ID: 728dfc67-f3e9-64ea-8a91-c6d72c8cc54f
* Content: [AddHandler Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/addhandler-statement?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vb.AddHandler)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%3Bk(DevLang-VB)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [docs/visual-basic/language-reference/statements/addhandler-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/addhandler-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
As this is reference documentation to just see the `AddHandler` statement working, I think this is good enough to demonstrate that the handler code is called when you add it and if you remove the handler, it is not called.
