### ISSUE TITLE
Is IP the correct abbreviation for Identity Provider

### ISSUE THREAD

**Issue by mhewedy** [dotnet/docs#10883]
According to Wikipedia https://en.wikipedia.org/wiki/Identity_provider identity provider abbreviated as IdP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f91bc6-9650-142c-49c4-a40ad8a7aeee
* Version Independent ID: d902aad7-681f-5f05-426e-10385f2ab7af
* Content: [Claims-Based Identity Model](https://docs.microsoft.com/en-us/dotnet/framework/security/claims-based-identity-model)
* Content Source: [docs/framework/security/claims-based-identity-model.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/claims-based-identity-model.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I don't think so. I would just remove the abbreviation, it's not really saving any space in those three bullet points.
