### ISSUE TITLE
Change from stratification column to 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#10957]
The 'stratification column' concept mentioned above is wrong.
In fact, that parameter ''stratification column' was renamed to 'samplingKeyColumn' because stratification column means a very different thing:
Stratification Column: A Stratification column is important if the rows in the dataset should be divided evenly by some key column when sampling or producing split datasets, so it is a very different concept.

When moving the train/test split content to a different page, also say that you could use the 'samplingKeyColumn' for grouping rows. If two examples share the same value of the samplingKeyColumn, they are guaranteed to appear in the same subset (train or test). This can be used to ensure no label leakage from the train to the test set. If null no row grouping will be performed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df25ca43-b9af-7d37-1b6d-690183ab421d
* Version Independent ID: 3c593c29-8e2f-9c88-26f6-c54a7345b6c7
* Content: [Train a machine learning model using cross-validation - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-cross-validation-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/train-cross-validation-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-cross-validation-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Being worked on as part of #11792
