### ISSUE TITLE
Segregate the content for train-test split into a different page

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#10956]
It is confusing to do cross-validation and randomized 90/10 train-test split in the same page.
Please, move train-test split into a different page.

Also, cross-validation is usually done before the last training since it performs the same number of trains than the number of folds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df25ca43-b9af-7d37-1b6d-690183ab421d
* Version Independent ID: 3c593c29-8e2f-9c88-26f6-c54a7345b6c7
* Content: [Train a machine learning model using cross-validation - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-cross-validation-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/train-cross-validation-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-cross-validation-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Being worked on as part of #11792
