### ISSUE TITLE
Timer Callback missing

### ISSUE THREAD

**Issue by HerbertFeichtinger** [dotnet/docs#10961]
1. please include if async timer callback (System.Threading.Timer) should return void or Task&lt;&gt;. 
I use  System.Threading.Timer a lot for timeout issues.

2. I didn't find useful examples how to write an async TCP server handling multiple lines in parallel, reading with timeout and e.g. echoing back messages sent from a client to this client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async Return Types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@HerbertFeichtinger Regarding your first listed problem, System.Threading.Timer and the callback are already using their own thread and running in a loop in the background. It doesn't support the async/await pattern. I did find this blog entry that shows how (or use the nuget package) to create a new timer type based on the async/await pattern https://ikriv.com/blog/?p=2429 

Regarding your second problem listed, I think this is outside the scope of these tutorials. I would look at the documentation for whatever network stack you're using. They probably have an example there.

I'm going to close this issue, thanks!
