### ISSUE TITLE
dotnet new -i does not indicate success intuitively

### ISSUE THREAD

**Issue by mishrsud** [dotnet/docs#10960]
I followed the instructions to create a template.json and a nupkg but when I tried to install this custom template, the ```dotnet new -i /path/to/template.json``` just echoed back the help text. This lead me to believe that I got the syntax wrong, however, on running dotnet new --list, I could see my custom template installed. Is this behaviour by design? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ccd42dc-0af2-1fa1-130a-61aff2d0770c
* Version Independent ID: 612b5eb7-23b9-68cd-a184-df9268ddb768
* Content: [Create a custom template for dotnet new - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#use-file-system-distribution)
* Content Source: [docs/core/tutorials/create-custom-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/create-custom-template.md)
* Product: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by guardrex** [comment]
You didn't include the JSON file name in the path, right? It should be the **_path to the folder_** that contains the JSON template file (in theory ... something might have changed or broken since this topic was written).

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc can you help with this feedback? Maybe we should make more clear what the path should look like in https://docs.microsoft.com/dotnet/core/tools/dotnet-new?

**Comment by KathleenDollard** [comment]
cc: @mlorbetske

**Comment by mishrsud** [comment]
@guardrex I didn't include the JSON file name. This is how my command looked like: (I'm on Mac OSX)

```bash
# Folder structure:
# /Source/MyProject   -- contains the .template.config folder

dotnet new -i /Source/MyProject
```

**Comment by mairaw** [comment]
@mlorbetske can you help here?

**Comment by Thraka** [comment]
@mishrsud This feedback is already captured in the templates repo. dotnet/templating#1750

Thanks.
