### ISSUE TITLE
Should Close be called if a Terminating operation has been called?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#10997]
After reading this I'm curious what happens when one calls ICommunicationObject.Close after calling a method that is defined with IsTerminating = true. Does it throw an exception because the session is already closed? Would anything bad happen if closed wasn't called?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8905ebbe-cbad-1d93-30cc-a751ee4c725a
* Version Independent ID: dc89acf7-4b92-0367-e146-586825ef8f3b
* Content: [Using Sessions](https://docs.microsoft.com/en-us/dotnet/framework/wcf/using-sessions)
* Content Source: [docs/framework/wcf/using-sessions.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/using-sessions.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
@Lxiamail Perhaps you can answer this question?

**Comment by Lxiamail** [comment]
@martingbrown IsTerminating = true operation call will close the channel on client side.   ICommunicationObject.Close is not needed anymore. However. calling ICommunicationObject.Close  after it should be no-op without side effect.
