### ISSUE TITLE
How do I create similar program using .Net Framework?

### ISSUE THREAD

**Issue by kudlatiger** [dotnet/docs#11011]
How do I create similar program using .Net Framework?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
If you're looking for information related to how to create a .NET Framework application in Visual Studio Code, I don't think it is a supported scenario. However, some community members have provided detailed instructions on how to configure VSCode for .NET Framework, but only for 64-bit apps.

https://stackoverflow.com/questions/47707095/visual-studio-code-for-net-framework

I'm going to close this issue. Feel free to comment if I'm wrong in the assumption of what you wanted to do. 

Cheers!
