### ISSUE TITLE
How to use .Net Native with regular C# console app?

### ISSUE THREAD

**Issue by beppe9000** [dotnet/docs#11021]
The docs are unclear...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bdee785-1d27-e642-f93c-744777d0fc13
* Version Independent ID: b4201e2b-9979-6c48-b58b-df3f7d79b818
* Content: [Getting Started with .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/getting-started-with-net-native#feedback)
* Content Source: [docs/framework/net-native/getting-started-with-net-native.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/getting-started-with-net-native.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
The documentation doesn't mention C# console apps because they're not supported, @beppe9000. As the first step of the article notes, you begin with a UWP app that targets Windows 10.

I'll close this issue, but if you disagree, @beppe9000, feel free to let us know.
