### ISSUE TITLE
Remove Windows 95, Windows 98, or Windows Millennium references

### ISSUE THREAD

**Issue by nschonni** [dotnet/docs#11024]
Looks like there are a few references still to the Win 95 world:
- https://github.com/dotnet/docs/blob/95591611a8742bdc47413bd7235deeef1ddce795/docs/framework/unmanaged-api/debugging/icordebug-interface.md
- https://github.com/dotnet/docs/blob/95591611a8742bdc47413bd7235deeef1ddce795/docs/visual-basic/language-reference/data-types/ulong-data-type.md
- https://github.com/dotnet/docs/blob/95591611a8742bdc47413bd7235deeef1ddce795/docs/framework/unmanaged-api/hosting/getversionfromprocess-function.md
- https://github.com/dotnet/docs/blob/95591611a8742bdc47413bd7235deeef1ddce795/docs/framework/interop/specifying-a-character-set.md
- https://github.com/dotnet/docs/blob/83fa3b288d773d8ef055174737b66f639fe8ae00/docs/visual-basic/language-reference/statements/declare-statement.md

There are probably a few others, this was just using the GitHub code search after I had come across the reference in another PR https://github.com/dotnet/docs/search?p=2&q=Windows+95&unscoped_q=Windows+95

Maybe the Win XP is a separate discussion

**Comment by mairaw** [comment]
Thanks @nschonni. Yes, we definitely need to review the content for mentions of older versions of Windows. 

Do you say XP is a separate discussion because of this issue: #5199?

**Comment by nschonni** [comment]
Didn't see that other issue, it was more about the people that still cling on to XP, although I don't think there is even any more supper extra extended $$$ support anymore. Maybe it is still covered partially with Server 2003 still being under paid support though

**Comment by mairaw** [comment]
Not 100% sure as well but my guess is that it's out of support completely. So here's what I'll do. I'll change the title on that one because we really should be removing all these old Windows versions and closing this as a dupe. Ok?

**Comment by nschonni** [comment]
Fine with me
