### ISSUE TITLE
"Cancelation" used instead of "Cancellation" in WWF docs

### ISSUE THREAD

**Issue by nschonni** [dotnet/docs#11032]
Not sure if this is a product or docs bug https://github.com/dotnet/docs/search?q=Cancelation&type=Code
EX: TryCatchExceptionDuringCancelation

**Comment by mairaw** [comment]
Thanks @nschonni. Unfortunately, it does look like a product bug:
https://referencesource.microsoft.com/#System.Activities/TD.Designer.cs,244

I think the only one we could fix is the one where cancelation is a noun and not the API name.
