### ISSUE TITLE
M35452: Wrong formatting in Source on Website

### ISSUE THREAD

**Issue by v-makoud** [dotnet/docs#11054]
Hello @JRAlexander, @BillWagner, @mairaw, @rpetrusha,
Translator has reported possible source content issue.
Link to Github file: https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md
Row where the issue is located: 295
Comment: Please note that something went wrong with the formatting on the Website. 

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by JRAlexander** [comment]
@v-makoud - Investigating now. Was there any sort of error message? Will roll in changes to dataset update for this tutorial later today.

**Comment by mairaw** [comment]
I'm wondering if you need a line break between the code reference and the text line?

Also this looks weird (the lost "Deploy and Predict with a loaded model" sentence):
![image](https://user-images.githubusercontent.com/12971179/53831249-3ec08180-3f39-11e9-8490-57aeb8935665.png)

**Comment by JRAlexander** [comment]
@mairaw - that's exactly what I was thinking. I've implemented both changes as I'm updating the dataset.

**Comment by v-makoud** [comment]
@JRAlexander @mairaw thanks both of you, I will leave this issue open until the changes are merged.
