### ISSUE TITLE
Related methods do not exist

### ISSUE THREAD

**Issue by gilberto-ferreira** [dotnet/docs#11057]
Hey,

Please, replace this method json.GetStringValue for json.GetString and this json.GetBooleanValue by json.GetBoolean. 

Thanks, :)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [Novidades do .NET Core 3.0](https://docs.microsoft.com/pt-br/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@richlander Does this need to be fixed when you do your updates for preview 3?

**Comment by gilberto-ferreira** [comment]
Could you confirm?
I just copied the code...

![info](https://user-images.githubusercontent.com/24195085/53883360-86a5de00-3ff7-11e9-95da-67f1d93eaccb.PNG)
![csproj](https://user-images.githubusercontent.com/24195085/53883218-27e06480-3ff7-11e9-8e22-c47224eddc90.PNG)
![visualstudio](https://user-images.githubusercontent.com/24195085/53883219-2878fb00-3ff7-11e9-9af7-dee6a4572e33.PNG)
![codigo](https://user-images.githubusercontent.com/24195085/53883458-d1bff100-3ff7-11e9-86f7-75836e177736.PNG)

**Comment by gilberto-ferreira** [comment]
I think I'm in preview 2, Preview 3 is not available.

**Comment by Thraka** [comment]
@gilberto-ferreira I get the same error. @richlander is going to be updating this article when Preview 3 is released.

**Comment by Thraka** [comment]
This was fixed in april with the rewrite of the 3.0 notes.
