### ISSUE TITLE
.NET Framework Reference

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#11065]
How do I find the .NET Framework Reference? For example the following is for a previous version:

https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/xz702w3e(v=vs.100)

However I cannot find the .Net Framework Reference and I am totally unable to find the current version of that page by searching for it. You people often make it impossible to find the current version documentation; after doing many searches over many months I very often can only find documentation for previous versions of what I search for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04fb826-aa70-5a14-2a13-4eed6cbb304f
* Version Independent ID: 2835b981-f482-8fa2-df47-469291d93a5a
* Content: [.NET Framework 4.7, 4.6, and 4.5](https://docs.microsoft.com/en-us/dotnet/framework/)
* Content Source: [docs/framework/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@SimpleSamples when you say reference, do you mean that exact reference you're linking to?

@Rick-Anderson @scottaddie do you have that content somewhere else or just in the archive? We should perhaps look into enabling indexing for a few areas of the content on the archive that people still need it. I've downloaded some data from the previous-version content the other day and there are some that have surprisingly high traffic (most for ASP.NET config elements).

**Comment by Rick-Anderson** [comment]
> unable to find the current version of that page by searching for it.

[ASP.NET Page Syntax](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/fy30at8h(v%3dvs.100)) has not changed, so this is the current version.

Let's figure out a way to communicate that.

**Comment by SimpleSamples** [comment]
My intent was to ask about .Net Framework reference(s) generally. I attempted to post this where it is most appropriate for that. I used the specific page as an example. I hope my question is more useful as a general question about the reference(s) in general.

Since that documentation has not changed I think it would help if we can determine that. It seems confusing to say that something is no longer revised, implying it is old information, when in fact it is current. This is definitely not the first time I have been unable to find current documentation when the documentation I find implies it is not current.

**Comment by Thraka** [comment]
The link at the bottom of this page **.NET Framework Class Library** goes to the API. Maybe that should be named better? Perhaps it should use the words _API_ and/or _Reference_?

**Comment by gewarren** [comment]
The ask here is to clearly notate archived reference docs that are still current.

**Comment by SimpleSamples** [comment]
Yes, if documentation is still current then it should not be called archived.
