### ISSUE TITLE
Is lock section really required in this example?

### ISSUE THREAD

**Issue by saran-sasidharan** [dotnet/docs#11063]
In this particular example, only one thread is making use of the UpdateDelay function. So there is no scenario of multiple threads executing the locked section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a28322-944d-73c3-177c-d9bec577c08b
* Version Independent ID: 15ce52df-1eb1-7743-8440-dbef3169487c
* Content: [Console Application](https://docs.microsoft.com/en-in/dotnet/csharp/tutorials/console-teleprompter#feedback)
* Content Source: [docs/csharp/tutorials/console-teleprompter.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-teleprompter.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @saran-sasidharan 

You are correct. The lock is unnecessary.  I've added this to our community contribution project, and added the "Up for Grabs" label.  If you'd like to submit a PR, we'll look for it.
