### ISSUE TITLE
Mention explicitly that HttpClientFactory is provided through a Nuget package

### ISSUE THREAD

**Issue by matteocontrini** [dotnet/docs#11064]
The article says that the `HttpClientFactory` class is available by adding a reference to the `Microsoft.Extensions.Http` package, but it doesn't explicitly say that it's available through Nuget.

At some point, it also says:

>.NET Core 2.1 introduced a new HttpClientFactory

which might be confusing since it's not a "core" feature.

My suggestion would be to make the step of installing the library with Nuget more explicit.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#implement-your-typed-client-classes-that-use-the-injected-and-configured-httpclient)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @matteocontrini, thanks for the feedback.

I would've thought that just by saying "add a reference to XXX package" would make it clear that it's a NuGet package, but it looks like it's not, from the amount of thumbs up.

Will reword the mention.

**Comment by matteocontrini** [comment]
Thanks!

It's been some time but I remember that while reading it, the article gave the impression that it was a new feature of the framework, while it's actually a library that you need to install manually.

New users of the ecosystem might not know that the framework is extensible through Nuget packages, so saying it explicitly can't be bad :)
