### ISSUE TITLE
array

### ISSUE THREAD

**Issue by justin-romano** [dotnet/docs#11067]
array would be out of scope here. for (int i = 0; i &lt; 256; i++) Console.WriteLine(array[i]);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07855c98-23f4-3166-9bba-eff9b456f92f
* Version Independent ID: d423fd96-ab0b-1131-3aab-09d74ef4bd5f
* Content: [Unsafe code](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code#feedback)
* Content Source: [spec/unsafe-code.md](https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
You are right. And putting it in scope, I can't even get it to run correctly.. :(

**Comment by Thraka** [comment]
@BillWagner FYI

**Comment by NextTurn** [comment]
Opened docs/csharplang#2324

**Comment by NextTurn** [comment]
Who is responsible for the docs in `csharplang` repo?

**Comment by NextTurn** [comment]
Who is responsible for the docs in *csharplang* repo?

**Comment by NextTurn** [comment]
Pinging everyone here @mairaw @Thraka @BillWagner

**Comment by mairaw** [comment]
I pinged some folks on the PR

**Comment by gafter** [comment]
That PR is merged now.

**Comment by mairaw** [comment]
I'll close this one and rebuild our content to pull in the latest.
