### ISSUE TITLE
Error handling? 

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#11098]
It would be nice if this example had some exception handling in it. DiscoveryClient.Find likes to throw TargetInvocationExceptions instead of WCFs more common CommunicationException and TimeoutException. It would be nice to know how we are supposed to cope with that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362681e4-6f22-dcbd-dbbd-b90c6a9c52a9
* Version Independent ID: 35178e72-3c62-2e23-af3d-7d8765d201be
* Content: [How to: Programmatically Add Discoverability to a WCF Service and Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-programmatically-add-discoverability-to-a-wcf-service-and-client)
* Content Source: [docs/framework/wcf/feature-details/how-to-programmatically-add-discoverability-to-a-wcf-service-and-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-programmatically-add-discoverability-to-a-wcf-service-and-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
