### ISSUE TITLE
"If you want the called method to change the value of the parameter, you must pass it by reference"

### ISSUE THREAD

**Issue by phuctv95** [dotnet/docs#11103]
The original sentence:

> If you want the called method to change the value of **the parameter**, you must pass it by reference, using the `ref` or `out` keyword.

I'm not sure but I think it should be "*the argument*" instead of "*the parameter*".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4dcb4da-bdb8-853d-678a-9c5130921ecb
* Version Independent ID: 1dbe0544-77c2-c70f-8406-2bca85e914e8
* Content: [Passing Value-Type Parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-value-type-parameters#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/passing-value-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/passing-value-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mosri** [comment]
It means the same thing, but parameter is actually the correct term. Since in the implementation of the method, the argument may undergo change. The argument at the end of the method may not be the same as it was at the input. Parameter is more appropriate since it may be dynamically changing.
