### ISSUE TITLE
Constant values look wrong

### ISSUE THREAD

**Issue by aidtopia** [dotnet/docs#11109]
The values in the description of the dwOSPlatform ID are written in hexadecimal, but it seems they were supposed to be binary.  In particular, VER_PLATFORM_WIN32_NT is defined as 2, which would be 0b0010 not 0x0010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d952a4-1b40-a64c-67d6-ba1a721acf75
* Version Independent ID: ca1ce8d9-3697-2a58-c818-505d32f2ff3d
* Content: [OSINFO Structure](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/osinfo-structure#feedback)
* Content Source: [docs/framework/unmanaged-api/metadata/osinfo-structure.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/metadata/osinfo-structure.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@noahfalk can you look at this feedback?

**Comment by noahfalk** [comment]
Adding @sergiy-k, our tentative owner for metadata.

FWIW I think @aidtopia is correct, the constant should be documented as 2, or in binary 0b0010. Some of the other constants from our pal.h header:

```
#define VER_PLATFORM_WIN32_WINDOWS    1
#define VER_PLATFORM_WIN32_NT    2
#define VER_PLATFORM_UNIX    10
#define VER_PLATFORM_MACOSX    11
```

**Comment by Thraka** [comment]
Sent email to @sergiy-k

**Comment by sergiy-k** [comment]
@aidtopia is correct. The value of VER_PLATFORM_WIN32_NT is documented properly.
/cc: @davidwrighton
