### ISSUE TITLE
TEST_TEST

### ISSUE THREAD

**Issue by swpark7** [dotnet/docs#11108]
TEST_TEST_TEST

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc32151-058c-e82b-8654-bec1020afd9b
* Version Independent ID: e7d42142-da3f-8f5e-28ed-82ba61327361
* Content: [Get started with Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/)
* Content Source: [docs/visual-basic/getting-started/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Closing as test then.
