### ISSUE TITLE
I think it's missing the `in` keyword

### ISSUE THREAD

**Issue by phuctv95** [dotnet/docs#11106]
> However, you cannot change the value of the reference itself; for example, you cannot use the same reference to allocate memory for a new class and have it persist outside the method. To do that, pass the parameter using the `ref` or `out` keyword.

It mentions just the `ref` and `out` keyword, I think it's missing the `in`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79cbd9e8-6ef8-932b-24f7-90eff098b4f0
* Version Independent ID: 62fa8115-2692-7c9a-30ef-c4ecf92168e0
* Content: [Passing Reference-Type Parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@phuctv95 the current text looks correct. The cited paragraph is read in the following way:

> To do that (that is, to change the value of the reference itself; for example, to use the same reference to allocate memory for a new class and have it persist outside the method), pass the parameter using the `ref` or `out` keyword.

The docs for the [`in` parameter modifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier) state (emphasis is mine):

> The `in` keyword causes arguments to be passed by reference. It is like the `ref` or `out` keywords, except that **`in` arguments cannot be modified by the called method**. Whereas `ref` arguments may be modified, `out` arguments must be modified by the called method, and those modifications are observable in the calling context.

**Comment by phuctv95** [comment]
Ah, I got it, thank you for the explanation.

But I think it should still mention the `in` keyword, because `in` keyword is also used to pass by reference, like `ref` and `out`.
