### ISSUE TITLE
Memory Requirement Information Needed

### ISSUE THREAD

**Issue by codewithash** [dotnet/docs#11100]
Can you tell us minimum RAM required for the ASP.Net core runtime ...

**Comment by mairaw** [comment]
@leecow do we have this information anywhere?

**Comment by leecow** [comment]
@Eilon and @mikeharder who may have baseline working set data.

**Comment by Eilon** [comment]
It's not information we have readily available, though @sebastienros might have some idea on the absolute minimum.

In practice the minimum depends on many factors, including but not limited to: the OS, the platform, the architecture. But then there are various app-specific things such as various configuration settings and dependencies. "Minimum memory" also depends on what you're measuring: working set, private bytes, or some other measure?

So, the best way to answer this is really just to run a Hello World app in the desired environment and see how much memory it's using based on the metric you think is important.
