### ISSUE TITLE
TOC management

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1110]
Our TOC file is growing in size significantly. OPS also supports nested TOC files. Should we use that to make the TOC management a bit easier?

/cc @richlander @BillWagner @cartermp

**Comment by cartermp** [comment]
Yes!  That would be essential, especially since the F# docs effectively doubled the size of the file.

**Comment by BillWagner** [comment]
I think this is great idea. It would also minimize contention for the one shared file across all topics.

**Comment by BillWagner** [comment]
I'm working on a branch that will update the TOC (C# 7 feature outline). Should I just add this at the same time?

**Comment by BillWagner** [comment]
We've moved significantly toward sub-TOCs.  Closing this.
