### ISSUE TITLE
ISO 8601 output is wrong

### ISSUE THREAD

**Issue by haakoo** [dotnet/docs#11101]
Isn't the output produced by `"o"` (ISO 8601) wrong? It's now equivalent to `"yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzzz"`.

As far as I understand the ISO 8601 format should be: `"yyyy-MM-ddTHH:mm:ssZ"` for UTC. Why all the seconds fractions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52741095-f1fd-71b8-15f8-b526480f0d83
* Version Independent ID: 12b2c626-2479-1090-83fd-583c6d600ed8
* Content: [Standard Date and Time Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/standard-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-date-and-time-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by haakoo** [comment]
I guess this shouldn't be a Docs issue, but some .Net repo?

**Comment by tdykstra** [comment]
@haakoo Thanks for the question.  The ISO 8601 does permit fractions of seconds:

> Decimal fractions may be added to any of the three time elements. ... There is no limit on the number of decimal places for the decimal fraction. 

https://en.wikipedia.org/wiki/ISO_8601

We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by haakoo** [comment]
It's allowed, yes, but is it sensible? By having so many digits in the decimal the `"o"` option for `\ 
`DateTime.ToString()` makes it fairly useless. How often do you want 5+ decimal digits for the seconds?

This issue is really about changing the default to something sensible.
