### ISSUE TITLE
You can run the application...

### ISSUE THREAD

**Issue by chaim1221** [dotnet/docs#11122]
I am confused, I read the instructions for the Linux containers, did that, skipped over the Windows part, and landed on "you can use `dotnet publish`" and I don't understand what that has to do with the containers. What I would have wanted to see here is more information about how to configure the containers for production. Maybe I missed something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [Docker images overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Yes, this is very odd and feels out of place. I'll add this to the docker project. Thank you for bringing it up.

**Comment by Thraka** [comment]
I just published an update to this article that completely rewrites it. I tried to make it generic enough for windows or linux. If you look at the article you may be redirected to the overview. That means the article hasn't been published yet, so try again later.

Let me know if this helps.

Cheers!

**Comment by chaim1221** [comment]
You know, it has just been so long since I looked at this that I can't even remember what was wrong in the first place. But the process you describe seems to fit with what we did:

https://github.com/chaim1221/Machete/blob/master/dockerize.sh
https://github.com/chaim1221/Machete/blob/master/Dockerfile

...so that's good!

**Comment by Thraka** [comment]
I know.. sorry it takes time to get to these :) But your issues help us figure out ways to improve, so thanks :) :) :) :)

There was another issue with `dotnet publish` and I think that whole section of the original article was confusing. I simplified that part greatly.
