### ISSUE TITLE
Document additional GC configuration settings

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#11146]
## Document additional GC configuration settings

A number of GC configuration settings are currently undocumented but should be documented. They include:

- GCHeapCount
- GCNoAffinitize
- GCHeapAffinitizeMask

They can be added to the [Fundamentals of Garbage Collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#workstation-and-server-garbage-collection) article.

//cc @Maoni0

**Comment by gewarren** [comment]
Related to #13425
