### ISSUE TITLE
Comment about very large tuples

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#11171]
Should not the article provide a comment about very large tuples, for example:

var a1 = ("New York", 7891957, tete: 7781984, 7894862, 7071639, 7322564, 8008278, 7891957, 7781984,
                 7894862, 7071639, 7322564, 8008278, 7891957, tata: 7781984, 7894862, 7071639, 7322564,
                 8008278, 7891957, 7781984, 7071639, 7322564, 8008278, 7891957, 7781984, 7894862, 7071639,
                 7322564, 8008278, 7891957, 7781984, 7071639, 7322564, 8008278, 7891957, 7781984, 
                 toto: 7894862, 7071639, 7322564, 8008278, "string", 7781984, 7071639, 7322564, 8008278,
                 7891957, 7781984, 7894862, 7071639, 7322564, true, 7891957, 7781984, 7071639, 
                 7322564, 8008278, 7891957, 7781984, 7894862, 7071639, 7322564, 8008278, 7891957, 7781984,
                7894862, 7071639, 7322564, 8008278);

This kind of tuple handles internally sequencies of the 8th element &lt;TRest&gt;, so you can address any element directly, for example:

var a2 = a1.Item342;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @MarcioAB 
I've added it to our backlog.

**Comment by DocumentationLive** [comment]
Up until now in the C# Concepts section of the documentation we have not been introduced to "out parameters". I think it would be great if a brief description of what they do is included before being used as an example, as well as a link to read more on them. I was able to guess what was happening with some though, but I will need to go confirm my guesses.

**Comment by DocumentationLive** [comment]
I meant to leave that in a main thread, I don't have the power to remove it here. Opening a new comment. Sorry about that.
