### ISSUE TITLE
Port threading content from MSDN and review/revise it 

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1117]
The ease of writing asynchronous code had made multi-threaded code very common. Often, though, developers don't fully appreciate the fact that their code may be executing on multiple threads, and do not do not fully appreciate the need to synchronize access to resources. 

The documentation at [Managed Threading](https://msdn.microsoft.com/en-us/library/3e8s7xdd%28v=vs.110%29.aspx) should be ported, revised, reorganized, and expanded. A discussion of async and threading should be added where appropriate. In addition, portions of the documentation (particularly in the [Threading Objects and Features](https://msdn.microsoft.com/en-us/library/9xyf641a%28v=vs.110%29.aspx) section) should be moved into the API reference. Finally, examples should be added, as appropriate.

**Comment by mairaw** [comment]
Issue not needed anymore.

**Comment by sputier** [comment]
@rpetrusha I'd be glad to help you on this one ! Do you have any idea about the structure this part of the doc should have after the changes ? Actually, I think it is a it too overwhelmed, so it can be hard to find the exact thing we need, but I am not sure how to improve it.

**Comment by rpetrusha** [comment]
Thanks for the offer, @sputier. Actually, content has now all been ported from MSDN, and unfortunately it was ported in two stages. One was a port of threading docs to the VB and C# documentation, and the other was a port of the threading docs to the .NET Standard documentation. With a few exceptions (like `lock` and `SyncLock`, VB and C# don't actually offer threading support apart from .NET. So there's actually a triplication of content here. And this is an area that really should be addressed, so that all of the relevant information is in the .NET Standard section.
What I'd like to do is close the issue and open a new one that has a bit more detail about the scope of the work. I'll leave this open until I have the chance (probably early next week) to review the existing threading documentation, see how much of it is repetitive, and provide more detail to the issue. Does that sound OK?

**Comment by sputier** [comment]
@rpetrusha Of course, I'd like to help on it ! Don't hesitate to mention me when you open the new issue.

**Comment by rpetrusha** [comment]
Closing, since porting is complete and #3819 covers revisions necessitated by porting/migration.
