### ISSUE TITLE
Adding Releases and Tags to our repo

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1120]
We should add releases/tag to our repo similar to what Corefx does: https://github.com/dotnet/corefx/releases

**Comment by IEvangelist** [comment]
Hi @mairaw -- I think we might want to close this one. Not sure how valuable it is for docs and it's been around for a long time now. Are you okay with us closing it?

**Comment by mairaw** [comment]
For sure. We never implemented this.
