### ISSUE TITLE
Windows Azure Access Control Service is deprecated

### ISSUE THREAD

**Issue by MAJVeld** [dotnet/docs#11215]
The current page describes Windows Azure Access Control Service as one of the two STS solutions provided by Microsoft. 
However, Windows Azure Access Control Service is officially deprecated. 
See: https://azure.microsoft.com/nl-nl/blog/one-month-retirement-notice-access-control-service/ and https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration for more information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2185d691-61f0-6658-27e9-63240a3e1241
* Version Independent ID: 3d8a0a75-47af-1e4e-f5b1-0e27da020a53
* Content: [Building My First Claims-Aware ASP.NET Web Application](https://docs.microsoft.com/en-us/dotnet/framework/security/building-my-first-claims-aware-aspnet-web-app#feedback)
* Content Source: [docs/framework/security/building-my-first-claims-aware-aspnet-web-app.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/building-my-first-claims-aware-aspnet-web-app.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I believe this whole section is deprecated but we're blocked from moving this content to our archive right now. I'll add some warnings for now on a future sprint so people can at least know.

**Comment by mairaw** [comment]
Contacted the engineering team to see how we can archive this content.

**Comment by mairaw** [comment]
Archival tool is not ready yet. Pushing this to next month.

**Comment by mairaw** [comment]
Closing in favor of issue #14801. We have a pull request open already to archive this content.
