### ISSUE TITLE
OData and OAuth hyperlink in Caims auth section is broken

### ISSUE THREAD

**Issue by subhankars** [dotnet/docs#11216]
Source Page: https://docs.microsoft.com/en-us/dotnet/framework/data/wcf/securing-wcf-data-services

**Issue :** OData and OAuth hyperlink to https://blogs.msdn.microsoft.com/astoriateam/2011/01/20/odata-and-oauth-protecting-an-odata-service-using-oauth-2-0/ in Caims auth section is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ade3441-dea1-a2a0-0081-65b166529db8
* Version Independent ID: 01e6a3ee-609f-8f76-e0a7-144efd96f1ae
* Content: [Securing WCF Data Services](https://docs.microsoft.com/en-us/dotnet/framework/data/wcf/securing-wcf-data-services)
* Content Source: [docs/framework/data/wcf/securing-wcf-data-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/wcf/securing-wcf-data-services.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by rpetrusha** [comment]
Thanks for pointing out the broken links, @subhankars. We've addressed the issue in #11307.
