### ISSUE TITLE
This was very helpful 

### ISSUE THREAD

**Issue by maylortaylor** [dotnet/docs#11228]
I used it to help me detect which dotnet runtimes i had on my OSX machine and told me directly how to delete them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Remove the .NET Core runtime and SDK - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos#feedback)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm glad you found it helpful. Thank you.

Closing as kudos.
