### ISSUE TITLE
Suggested code change to CheckFor45PlusVersion()

### ISSUE THREAD

**Issue by brtmckn** [dotnet/docs#11240]
In one of the code samples, at the top of method CheckFor45PlusVersion(int releaseKey)
change these 2 lines:
    if (releaseKey &gt;= 461808)
      return "4.7.2 or later";

to this:
    if (releaseKey &gt; 461808)
      return "4.7.2 or later";
    if (releaseKey == 461808)
      return "4.7.2";

The reasons:
1) if releaseKey == 461808 then it is definitely 4.7.2, the "or later" is not required.
2) if you see "or later" in the output it is a flag to the coder that the code can now be updated to take into account a new known release number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @brtmckn. The code is correct and shouldn't be modified as long as .NET Framework 4.7.2 is the current version. With the release of .NET Framework 4.8, we'll modify the code as you've suggested, with a `>=` check. I've scheduled some time to do this in the next sprint.
