### ISSUE TITLE
Several download.pdf files fail.

### ISSUE THREAD

**Issue by WhiteStar-magic** [dotnet/docs#11242]
Hello, I have been attempting to download reference guides for off-line use and the current links to generate & download PDF results in an invalid certificate error and fails to continue.  The 3 addresses I attempted this from are shown below.  I have successfully downloaded some other pdf docs related to Visual Studio, so this seems related to a select few (well hopefully only a few).

Thanks in advance for your attention to this and Kudos for the great work everyone is doing here.

source addresses:  
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/ 
https://docs.microsoft.com/en-us/dotnet/csharp/index
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/index

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by KexyBiscuit** [comment]
All three work for me now... Could you try again downloading them?

**Comment by BillWagner** [comment]
@WhiteStar-magic I checked today, and they all work for me as well.

Can you verify, or are you still seeing the error?

**Comment by WhiteStar-magic** [comment]
Just opened all the pages and accessed the PDF files without issue.
