### ISSUE TITLE
Please mention the need to Wait for the result to be delivered

### ISSUE THREAD

**Issue by brewmanz** [dotnet/docs#11243]
Please mention the need to Wait for the promise of the result to be delivered. Many readers (even MVPs) don't understand that even though you mention 'asynchronously' and Task', and put 'Async' as a method name suffix, that they needed to Wait for the result. This comment applies to most of your other ...Async methods for this class. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664c7597-ddd6-d477-aa72-f341097940a2
* Version Independent ID: 06837dda-c127-0739-a3e6-b6b286b2b5d5
* Content: [Document.GetSemanticModelAsync(CancellationToken) Method (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.document.getsemanticmodelasync?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Document.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Document.xml)
* Product: **dotnet-roslyn-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello!

Thank you for suggesting this change. I don't think this is something we want to do, for the following reasons:

1. We don't want the overhead of having a note in every article that returns a Task to mention to check the Result or call Wait.
2. When you `await` an async method, you don't need to call Wait or Result.
3. Visual Studio and VSCode both give warnings about the scenario you're talking about.

I'm going to close this issue. Thanks!
