### ISSUE TITLE
Diagram needs to be updated to add WPF/WinForms to .NET Core

### ISSUE THREAD

**Issue by ghuntley** [dotnet/docs#11256]
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/media/cross-platform-targeting/platforms-netstandard.png is out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @ghuntley. We added this update to our .NET Core 3.0 project.

**Comment by mairaw** [comment]
@JamesNK @terrajobst do we have this diagram handy somewhere that can be easily updated? I imagine it probably lives in a PowerPoint somewhere. It would be nice to get this updated.

**Comment by mairaw** [comment]
Also pinging @BethMassi - she might be able to help

**Comment by JamesNK** [comment]
I got it off an old blog post that I can't remember.

**Comment by terrajobst** [comment]
One thing we could do is use the slide the Hunter used at Build:

![image](https://user-images.githubusercontent.com/5169960/64309376-26193e80-cf51-11e9-882b-11efdfcd1b96.png)
