### ISSUE TITLE
Comparing interfaces to abstract classes is missleading 

### ISSUE THREAD

**Issue by earizon** [dotnet/docs#11258]
The phrase "An interface is a reference type that is somewhat similar to an abstract base class that consists of only abstract members. When a class implements an interface, it must provide an implementation for all the members of the interface." will confuse newcomers.

- Abstract classes are designed to define common behavior of sub-classes (life-cycles hooks for examples).

- Interfaces are designed to define orthogonal and non-related functionality among them (security vs visualization vs persistence, ...), and most of the time declare one or very few methods.

It's also time to stop claiming the false claim "Inheritance, together with encapsulation and polymorphism, is one of the three primary characteristics of object-oriented programming". Inheritance has been probed an anti-pattern in many scenarios, and object delegation is a much better approach as of 2019. Only encapsulation and polymorphism are core to OOP. Maybe fail-fast at object construction ought to be the third primary characteristic of OOP since it warrant the correct object state after initialization. The number of buggy and un-maintanable code I have seen over the years because of the use and abuse of inheritance makes me thing that this word has to be "forbidden" for ever from computer literature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b81800f-976a-b7a9-e202-5e34fd2c9c67
* Version Independent ID: 801d99f4-b1f5-3e42-ae4e-ba18200577f0
* Content: [Inheritance - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/inheritance)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/inheritance.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rubbalbhusri** [comment]
Can you sight an example where inheritance leads to a buggy and un-maintainable code? It'll help to all the audience to understand more of this perspective.

**Comment by earizon** [comment]
Each and every time that a class inherits from another one, the code is claiming that the "inherited class *IS* a parent class".

This is extremely dangerous most of the time unless the code is treating with well defined mathematical entities for which it can be *MATHEMATICALLY PROBED* that inherited class actually *IS AND ALWAYS WILL BE* the parent class.

OOP introductory courses tends to use geometrical objects to explain inheritance with the typical example of the base parent shape class and inherited rectangle, triangle, ... classes where just by pure change most of the times it can be probe *mathematically probed* that inherited classes *are and always will be* of parent type class since geometry is a well studied subject since the ancient greeks.

Real code, specially ERP and CRM code for which C# is used most of the times, does NOT agree with the "IS AND ALWAYS WILL BE" claim for their parent-child relationships.

Actually  mathematical frameworks for which we can warrant the parent-child relationship are well studied and implemented in high-performance libraries that C# will just limit to consume (mathematical libraries).

Now take the example of some real problem that C# will tackle most of the times. Imagine some business-logic related code where we start defining some entities like Seller, Provider, Client, ....  A naïve approach will inherit all of them from the "LegalEntity" parent class entity and *THAT'S WHAT MOST DEVELOPERS ACTUALLY DO!!!!*.  As the software and business logic evolves it will soon appear many discrepancies about the life time of sellers, providers, clients, ... and its expected behaviour and the code will need to be patched "continuously" to adjust the parent "LegalEntity" to bear with the data-impedance.

The developer will be confronted with de-normalization of the parent class and forced to introduce null(undefined)-data with all the burden of related problems.

Those all problems disappear by just using aggregation and delegation. Make sellers, providers, clients, ... delegate to a "LegalEntity" when needed and force common behaviour through well defined interfaces.
This will avoid all denormalization problems of artificial parent classes.
As soon as an entity evolves developers will just need to "switch on/off" the implemented interfaces or aggregated classes.

**Comment by BillWagner** [comment]
Although your comment about the difference between interfaces and abstract classes is certainly accurate, presenting the definition as we have in this article seems to make the most sense, since interfaces are often misunderstood, and this comment focuses on implementation rather than function..

Closing.
