### ISSUE TITLE
statement not clear

### ISSUE THREAD

**Issue by mfascino** [dotnet/docs#11257]
I am not sure what this means. is it possible to restate this differently and clearly:
Types with more than one type parameter must have the appropriate number of commas in the specification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e46579c-383b-1049-fee9-59c27328f7ba
* Version Independent ID: e9a776dd-e2b4-a2b2-6db4-4de7a4a0baeb
* Content: [typeof - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/typeof)
* Content Source: [docs/csharp/language-reference/keywords/typeof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/typeof.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @mfascino. The specification is the argument supplied to the `typeof` operator. For an open generic type, a comma is used to separate each pair. For example, `Type t = typeof(Dictionary<,>);`. We'll add a one-line example that clarifies the meaning.
