### ISSUE TITLE
C# guide: duplicate articles about lambda expressions

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#11253]
C# guide contains two, almost identical, articles about lambda expressions:
- one is within the **Programming Guide**:
  https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions
- another is under the **C# concepts** TOC entry:
  https://docs.microsoft.com/en-us/dotnet/csharp/lambda-expressions

The one from the programming guide looks to be the "main" one: it fits in the structure of the programming guide with its own sub-articles, it's referenced from the `=>` operator article, it appears first in web search results.

However, the second article contains more information ([section about lambdas and tuples](https://docs.microsoft.com/en-us/dotnet/csharp/lambda-expressions#lambda-expressions-and-tuples)) and I think its introduction reads better than one of the article in the programming guide. Though, it also has its flaws: the [section about async lambdas](https://docs.microsoft.com/en-us/dotnet/csharp/lambda-expressions#async-lambdas) doesn't provide an example of an async lambda. Also, the code examples are a bit better in the second article (except mentioned async lambda case).

I suggest to merge two mentioned sections (introduction and one about tuples) into the programming guide article and delete the second article.

@BillWagner what do you think?

**Comment by BillWagner** [comment]
@pkulikov I agree with your analysis. That is a great plan.

Do you want me to assign this to you?

**Comment by pkulikov** [comment]
@BillWagner 
> Do you want me to assign this to you?

Yes, please.
