### ISSUE TITLE
Step 1 of 10: Code doesn't run inside the Focus Menu

### ISSUE THREAD

**Issue by citrusit** [dotnet/docs#11250]
I copy/pasted the Code in Step 1 of 10 in this tutorial, and the Focus Window complains there is an error. I think you would want to fix it. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3686c2-4c73-5686-0da9-abc38c74aeec
* Version Independent ID: ca995f80-9375-e9ca-b855-6e6893581e23
* Content: [Explore C# 6 - Try the new features in C# 6 interactively, using your browser](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=10#feedback)
* Content Source: [docs/csharp/tutorials/exploration/csharp-6.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/exploration/csharp-6.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for letting us know @citrusit. I can repro that https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=1.
@BillWagner @LadyNaggaga @jonsequitur is this related to the try.net changes? If I remove the using System statement, I get an OOM exception.

**Comment by jonsequitur** [comment]
@rchande

**Comment by mairaw** [comment]
Let me know if we should transfer this issue to the try.net repo.

**Comment by mairaw** [comment]
Closing this since a new issue was created under dotnet/try to track this problem:
https://github.com/dotnet/try/issues/174

**Comment by akilisosa** [comment]
this has still not been fixed. if you remove the import statement, and change Program to programs or something else it works.

**Comment by akilisosa** [comment]
i don't know how to fix it in focus mode, but hopefully you guys circle back to this problem.
