### ISSUE TITLE
Viewing declarations for types with many interfaces requires extensive scrolling

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1126]
When displaying a declaration for a type, all interfaces it implements are shown on a single line. For types that implement many interfaces, this means viewing all interfaces requires extensive scrolling. For example, [`Dictionary<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.dictionary-2):

![](http://imgur.com/NtrNw4C.png)

Compare with [MSDN](https://msdn.microsoft.com/en-us/library/xfhwa508%28v=vs.110%29.aspx), which seems to limit line lengths:

![](http://imgur.com/TCfLsEA.png)

I think docs.MS should do something similar.

cc: @mairaw

**Comment by mairaw** [comment]
I agree. When I was posting the answer to #809 yesterday, I've also noticed this. 😄 

I'll file a request for this.

/cc @DuncanmaMSFT @adkinn

**Comment by mairaw** [comment]
This is now fixed:
![image](https://cloud.githubusercontent.com/assets/12971179/19873989/42c5dfe8-9f7f-11e6-92f3-91fee99af2a7.png)
