### ISSUE TITLE
"dotnet tool install" should explain how to run dotnet cli commands installed using "--tool-path"

### ISSUE THREAD

**Issue by ashmind** [dotnet/docs#11265]
If I have `dotnet tool install Octopus.DotNet.Cli --global` I can call it using `dotnet octo ...`.
If I have `dotnet tool install Octopus.DotNet.Cli --tool-path tools` -- how can I call it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#feedback)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
`.\tools` would have to be in PATH for your OS. Please feel free to click on the edit button on the article and submit a change to include that information. However, I'm going to close this issue as I believe your question is answered.
