### ISSUE TITLE
Samples are too wide

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#11272]
Some of the samples on this page are both tall and wide. This means that the reader often needs to use a horizontal scroll bar that is off the bottom of the screen. Would it be possible to add some wrapping in to make them fit a bit better please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd35c7d9-2c89-45b8-24e3-c06c746e0260
* Version Independent ID: 98d24e04-582a-52fa-1b4b-63a514064cc9
* Content: [How to: Implement a Discoverable Service that Registers with the Discovery Proxy](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/discoverable-service-that-registers-with-the-discovery-proxy)
* Content Source: [docs/framework/wcf/feature-details/discoverable-service-that-registers-with-the-discovery-proxy.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/discoverable-service-that-registers-with-the-discovery-proxy.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for your comments @martingbrown.

Site feedback should be logged at https://aka.ms/sitefeedback.

But I think the samples on this page can be changed a bit to not rely on the need of scrollbars.

For example, 

```csharp
AnnouncementEndpoint announcementEndpoint = 
    new AnnouncementEndpoint(new NetTcpBinding(), new EndpointAddress(announcementEndpointAddress));
```

Would you like to submit a PR to change this?
