### ISSUE TITLE
sample code is not up to date w/ latest API

### ISSUE THREAD

**Issue by aguerot** [dotnet/docs#11273]
Intro states this sample works w/ `ML.NET version 0.10` which seems to not be the case.

input/output column parameters have been inverted instead of `mlContext.Transforms.Categorical.OneHotEncoding("CategoricalFeatures", "CategoricalOneHot")` you should use `mlContext.Transforms.Categorical.OneHotEncoding("CategoricalOneHot", "CategoricalFeatures")` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c298a5-b76f-25d9-beda-e298ac03cf35
* Version Independent ID: 392ab238-4442-015c-ec30-eae546794cc9
* Content: [Apply feature engineering for model training on categorical data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-model-categorical-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/train-model-categorical-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-model-categorical-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Fixed in #11613
