### ISSUE TITLE
Documentation needed for member selection

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/docs#11285]
There needs to be more of a discussion of the 'new' keyword and exactly how a member is selected when there are multiple derived interfaces with common base interfaces. For example, 

    interface A { int a(); }
    interface B: A {}
    interface C: A { new int a(); }
    interface D: B, C {}
    class concreteD: D { A.a() =&gt; 1; C.a() =&gt; 2; }
    D d = new concreteD();
    
Now if I call d.a(), do I get 1 or 2 ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 594cb1b7-c9c9-5f33-fca7-2f1872c095a9
* Version Independent ID: 2ed35b23-7ffd-0d95-a2f0-02e3ccc4f8a7
* Content: [How to: Explicitly Implement Members of Two Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces)
* Content Source: [docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @sjb-sjb 

I've added it to our backlog to address when we next update this topic.

**Comment by BillWagner** [comment]
To answer the question posed,
`d.a()` returns `2`; it calls the `C.a()` method.
