### ISSUE TITLE
Github links point to archived repos

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/docs#11282]
Throughout the docs there are references to GitHub repos. Many of them reference https://github.com/aspnet but this repo is archived and read only. Links should be updated to use correct repo locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 1bb011dd-a559-c0d7-b0cf-984fbb2d4bd3
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by TheBeardedLlama** [comment]
created a PR to update the link to the active repo
