### ISSUE TITLE
Typo in while

### ISSUE THREAD

**Issue by ILMTitan** [dotnet/docs#11297]
`{| while expr do cexpr |}` | `builder.While(fun () -> expr), builder.Delay({|cexpr |})`
Should probably be
`{| while expr do cexpr |}`| `builder.While(fun () -> expr, builder.Delay({|cexpr |}))`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247c440d-b855-0df1-f2db-076cd3393a0b
* Version Independent ID: 1cbccd4d-1721-e14f-7546-8fa868c965b1
* Content: [Computation Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions#feedback)
* Content Source: [docs/fsharp/language-reference/computation-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/computation-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by mairaw** [comment]
@cartermp can you take a look?
