### ISSUE TITLE
Nullable constraints

### ISSUE THREAD

**Issue by paulhickman-a365** [dotnet/docs#11301]
Can you consider adding the ability to constrain a generic type argument to "something that is nullable". e.g. "class c&lt;T&gt; where T : null".

This would allow the use of T? as a type in the class and allow access to .HasValue and .Value on objects of type T and would allow you to create variables of types c&lt;int?&gt; and c&lt;string&gt; but not c&lt;int&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea1e2ab-5517-b17c-4a65-7c7bae09261a
* Version Independent ID: 2a326631-709b-4461-6c15-a75a5087ef1d
* Content: [Nullable reference types in C# - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/nullable-reference-types)
* Content Source: [proposals/csharp-8.0/nullable-reference-types.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@paulhickman-a365 Thanks for raising this issues.  The docs repo is not the right location for this discussion. Instead, it should be on the [C# Language design](https://github.com/dotnet/csharplang#discussion) repository.  That link has advice on what the language design team asks in terms of new feature proposals.  

I'll close this, but you should consider opening an issue with a proposal on the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.
