### ISSUE TITLE
"Load and transform data" section in taxi fare tutorial describes dataset as from sentiment analysis tutorial

### ISSUE THREAD

**Issue by wrummler** [dotnet/docs#11309]
This is the paragraph:

&gt; In ML.NET, data is similar to a SQL view. It is lazily evaluated, schematized, and heterogenous. The object is the first part of the pipeline, and loads the data. For this tutorial, it loads a dataset with comments and corresponding toxic or non toxic sentiment. This is used to create the model, and train it.

Same paragraph from the other tutorial: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#load-the-data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Predict prices using a regression learner with ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#load-and-transform-data)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @wrummler, for your contribution. Good catch! We've fixed in the related PR and merged it. The changes should be live in the next day or two.
