### ISSUE TITLE
string

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11306]
@FreeXiaoSuYu commented on [Thu Mar 14 2019](https://github.com/dotnet/docs.zh-cn/issues/348)

能否出一个文档，从一个项目发布开始图文教学一下，其中需要下载的工具，工具如何部署，然后项目如何部署，再用个人感悟讲解这部分操作，不要用太多官方语言讲述，能出个这种图文教学吗。不能，也谢谢。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core 应用程序部署](https://docs.microsoft.com/zh-cn/dotnet/core/deploying/index#feedback)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is making a suggestion on new documentation
Rough translation:

> Can you make a document, start a graphic teaching from a project release, which needs to download the tools, how to deploy the tools, then how to deploy the project, and then use personal sentiment to explain this part of the operation, do not use too much official language to tell, can come out Is this kind of graphic teaching? No, thank you.

**Comment by rpetrusha** [comment]
Downloading and installing .NET Core is documented elsewhere and is not directly related to application deployment. In terms of application deployment, I don't think that the article will be improved significantly by the addition of graphics. Closing...
