### ISSUE TITLE
its, not it's

### ISSUE THREAD

**Issue by markdcarringer** [dotnet/docs#11315]
".NET Core 2.0 and later supports .NET Standard 2.0, and we will use it's libraries to demonstrate unit tests."

The possessive of it is its. it's is a contraction for "it is". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64f7e75-fbea-18ba-f290-3e5bb3ab0da7
* Version Independent ID: 24639c20-6c3a-738e-2ff8-9a6ee6f232dc
* Content: [Unit testing in .NET Core and .NET Standard - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/#feedback)
* Content Source: [docs/core/testing/index.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/index.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for letting us know @markdcarringer. Would you like to fix that?

The instructions on how to do this are here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
