### ISSUE TITLE
How to handle size of text?

### ISSUE THREAD

**Issue by murulimadhav** [dotnet/docs#11323]
Here, the text will scale with whole background area. how to keep text size medium and not out of shape?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d37d68-041e-34c3-5777-2927714012b5
* Version Independent ID: 211e9a60-c38c-86bd-0c84-36c1a819896d
* Content: [How to: Draw Text to a Control's Background](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-draw-text-to-a-control-background#feedback)
* Content Source: [docs/framework/wpf/advanced/how-to-draw-text-to-a-control-background.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-draw-text-to-a-control-background.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hi, thank you for the question. This article doesn't really go into that much depth. It would be better if you asked on a support forum stackoverflow.
