### ISSUE TITLE
That from-the-end syntax is very confusing

### ISSUE THREAD

**Issue by dorsalmo** [dotnet/docs#11324]
Why are the ranges "up to but not including"?  That is counter-intuitive.  Ranges are usually inclusive on both ends.  Zero from the end should be the last element just as zero from the beginning is the first element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This design was discussed during several C# Language Design Meetings. The final decision was made in [May 2018](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-05-14.md#index-and-range)

It was first discussed in [Jan 2018](https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/meetings/2018/LDM-2018-01-22.md#inclusive-or-exclusive).  
Later meetings included [Feb 14, 2018](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-02-14.md#ranges) and [Feb 26, 2018](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-02-26.md#ranges)

The documentation does accurately reflect those design choices.  

I am going to close this.  However, if you want to continue to advocate for a different design, consider commenting on the referenced design notes, or other issues on ranges in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.

**Comment by dorsalmo** [comment]
Interesting.  Thanks for forwarding the links.  I’ll probably refrain from using this feature to avoid confusing future readers.  Shame.  I’ve been wanting this for a while.
