### ISSUE TITLE
Public const should be in PascalCase, not camelCase

### ISSUE THREAD

**Issue by mycroes** [dotnet/docs#11322]
As evidenced by [searching for **public const** in AspNetCore](https://github.com/aspnet/AspNetCore/search?q=public+const&unscoped_q=public+const), the documentation incorrectly states that `public const` should be in camelCase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00bb2c0f-ca81-ae02-2dfa-d9ef8a6a9a97
* Version Independent ID: de79bd37-59d4-cb32-f7d7-13c999d7ff68
* Content: [const keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/const#feedback)
* Content Source: [docs/csharp/language-reference/keywords/const.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/const.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mycroes** [comment]
Actually, only AspNetCore might not constitute a guideline, so this is a [search for **public const** in DotNetCore](https://github.com/dotnet/core/search?p=2&q=public+const&unscoped_q=public+const) as well.

**Comment by NextTurn** [comment]
Thanks for pointing this out @mycroes. Would you like to create a PR to address this?

The instructions are here: https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents

**Comment by BillWagner** [comment]
Thanks for writing this up @mycroes 

I've added it to our backlog, and the project for community contributions.  

If you want to create the PR, as @NextTurn says, I'll help answer any questions you may have.
