### ISSUE TITLE
List of limitations in expression lambdas vs statement lambdas

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#11321]
Certain things cannot be used in expression lambdas, such as the null propagation operator, and `dynamic`. A list of such items would be useful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c8b202-5b65-9d30-d57e-dd060a507b9a
* Version Independent ID: 92cfc461-56ed-c046-bb03-cc5e46ebf5ba
* Content: [Lambda Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/lambda-expressions)
* Content Source: [docs/csharp/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
**Note.** By #11313, the referenced article was merged (and afterwards removed and redirected) into the following article:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions

**Comment by zspitz** [comment]
@pkulikov Do I need to move my feedback somewhere else?

**Comment by pkulikov** [comment]
Now, this issue is visible here, at GitHub, but not anymore on docs.microsoft.com. Would be "nice-to-have" to resubmit the issue under the actual existing article (and close this one in such a case).

By the way, as for the issue itself:
>Certain things cannot be used in expression lambdas, such as the null propagation operator, and `dynamic`. 

The following expression lambda is fine (compiles and runs):
```csharp
Func<string, int> test = s => s?.Length ?? 0;
Console.WriteLine(test("t"));
```

@zspitz do you mean expression lambdas that are to be converted into *expression trees*? The following
```csharp
System.Linq.Expressions.Expression<Func<string, int>> e = s => s?.Length ?? 0;
Console.WriteLine(e);
```

generates a compile-time error:
```
error CS8072: An expression tree lambda may not contain a null propagating operator.
```


If that's the case, then the article about expression trees might be more fitting one for the issue:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/index

**Comment by zspitz** [comment]
@pkulikov My understanding of the terminology is as follows:

* [**lambda expressions**](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions) means the actual syntax used by C# or VB.NET:

    (string s) => s.Length
    Function(s As String) s.Length

  Depending on context, this might either compile to an anonymous method, or to an expression tree.

* [**expression lambdas**](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions#expression-lambdas) are expression trees generated by writing **lambda syntax** in a place where an `Expression<TDelegate>` is expected:

    Expression<Func<string, int>> expr = (string s) => s.Length
    Dim expr As Expression(Of Func(Of String, Integer)) = Function(s As String) s.Length

* [**statement lambdas**](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions#statement-lambdas) are anonymous methods generated by writing **lambda syntax** in a place where it is interpreted as a delegate:

    Func<string, int> del = (string s) => s.Length
    Dim del = Function(s As String) s.Length

> If that's the case, then the article about expression trees might be more fitting one for the issue

Perhaps. If anything, it should be together with the section on [generating expression trees using lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/index#creating-expression-trees-from-lambda-expressions).

**Comment by svick** [comment]
@zspitz That's not correct, and the sections you linked to contradict what you're saying.

The section on expression lambdas says:

> A lambda expression with **an expression on the right side of the => operator** is called an expression lambda.

And it also lists `Action line = () => Console.WriteLine();` (a lambda that is converted to a delegate) as an example of expression lambda.

**Comment by zspitz** [comment]
@svick @pkulikov I stand corrected (not enough coffee...).
