### ISSUE TITLE
Enhancement: Tips And Tricks section for solutions to known scenarios

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1133]
There are a number of scenarios where customers have found idiomatic solutions that involve topics that aren't surfaced to easily found locations in our documents. A _Tips and Tricks_ section in each of the guides would be a location to document the known and preferred solutions to these issues.  

Known Examples include using extern alias when you must have two or more different classes in scope that have the same fully qualified name. @rpetrusha had another example in our discussions yesterday.

This could also be a great area to engage community contributions. MVPs and other customers have advice on different scenarios that could be included here.

_Proposal_

Add a _Tips and Tricks_ section to the bottom of each Guide (.NET Standard, .NET Core, .NET Framework, C#, F#). Add the index article, and include in that index a "call for submissions" for the community.

/cc @richlander @cartermp @stevehoag @rpetrusha @mairaw

**Comment by cartermp** [comment]
I like this idea; however, I think there are certainly two different categories which could crop up:

* Answers to some of the truly baffling corner cases of our technology
* Better ways to write code for some specific scenarios

I think that the former would be very good to have, but the latter is better suited towards StackOverflow.

**Comment by BillWagner** [comment]
@cartermp I agree. I think this is a section where we need to be very diligent about 'please write an issue describing what you want to cover' before submitting a PR. We'll need to steer community members to the correct location for those different categories.

**Comment by cartermp** [comment]
Sounds good!

**Comment by rpetrusha** [comment]
@BillWagner The issue that I had mentioned was using extension methods to write custom methods for an enumeration type.

**Comment by BillWagner** [comment]
@rpetrusha Thanks! I didn't write it down, because I was sure I'd remember. I was wrong about that.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
