### ISSUE TITLE
Review build warning fixes

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#11337]
Related to #3682

I came across [this commit](https://github.com/dotnet/docs/commit/ac469e0c0635fe864fbabff629486ca564ece318) in PR #10142 where I fixed three commented out links. Could you review the related changes to check if some commented out xref links can be fixed?

For example, the `TimeSpan` at

https://github.com/dotnet/docs/blob/ac469e0c0635fe864fbabff629486ca564ece318/docs/framework/configuring-apps/file-schema/wcf/net-pipe.md#L62

the latest at

https://github.com/dotnet/docs/blob/91339fc6956dd8715060819a5615090f3bc71f38/docs/framework/configure-apps/file-schema/wcf/net-pipe.md#L49

can be changed to `<xref:System.TimeSpan>`?

/cc @mairaw

**Comment by Thraka** [comment]
Yes, that could be changed. I'm not sure if it's case sensitive but it would be `.TimeSpan` not `.Timespan`

**Comment by Thraka** [comment]
I'm going to close this since I think this was just a question from you. Thank you for all of your contributions!!

**Comment by NextTurn** [comment]
I'm requesting to review all of the "build warning fixes". But I only know this commit.

**Comment by NextTurn** [comment]
They should have been fixed in #3682. But no one can find them out because there is no "zz" notation.

**Comment by Thraka** [comment]
Sorry I didn't see the list of errors. Would you like me to leave this open until @mairaw can respond? :)

**Comment by NextTurn** [comment]
Yes. I guess @mairaw might know how to find them.

**Comment by NextTurn** [comment]
I don't follow. Is there anything wrong with the [`<xref:System.TimeSpan>`](https://github.com/dotnet/docs/search?utf8=✓&q=xref%3ASystem.TimeSpan) links?

**Comment by Thraka** [comment]
I dont think so. I was referring to the xref links that were in the PR you linked to. WHere it was something like `[text](xref:system....)` where you don't use `< >`

**Comment by mairaw** [comment]
So when we were migrating from MSDN, the team was helping to clear some build warnings and was not super familiar at that time with the xref notation. If you come across those, we welcome your PR to add the link instead. Does that help?

**Comment by NextTurn** [comment]
How can I find all of the fixes then? The commits were not linked to any PR/issue.

**Comment by mairaw** [comment]
I can publish a list of files that were touched by this effort. Not sure how many they are at the moment.

**Comment by NextTurn** [comment]
No problem. I'll have a try with Regex.

**Comment by mairaw** [comment]
Anyway, I'm adding here the list of topics impacted by this if that helps:

[link-fixes.xlsx](https://github.com/dotnet/docs/files/2980934/link-fixes.xlsx)
