### ISSUE TITLE
List of limitations in expression lambdas when generating expression trees

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#11348]
Certain things cannot be used in expression lambdas when used to generate expression trees, such as the null propagation operator, and `dynamic`. A list of such items would be useful here, after the section **Creating Expression Trees from Lambda Expressions**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5f0dba-6178-976a-920d-b516afd5ec87
* Version Independent ID: 99636ce3-bdc3-52b9-7a26-36f11b70e42b
* Content: [Expression Trees (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/index)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by zspitz** [comment]
An excellent starting point would be Bart DeSmet's description of his [CSharpExpressions library](https://github.com/bartdesmet/ExpressionFutures/tree/master/CSharpExpressions#c-30) in which he adds a set of factory methods for creating expressions that were added in later versions of the language.

**Comment by BillWagner** [comment]
Thank you for pointing this out @zspitz 

I've added it to our backlog, and we'll address this when we next update this content.

**Comment by zspitz** [comment]
@dotnet/docs

I feel that a comprehensive list of C# syntax that cannot be used within a lambda expression has great value.

* null propagation
* `ref` and `out` variables
* `dynamic`

among others. Admittedly, the error message is rather straightforward; usually something to the effect that "you can't use feature x in a lambda expression", but I don't think that's a reason not to provide such a list.
