### ISSUE TITLE
How to execute something while setting the value.

### ISSUE THREAD

**Issue by faizidp** [dotnet/docs#11340]
Previously, we could execute some code while setting the value. 
For example:
    private double totalPurchases;
    public double TotalPurchases { 
    set{ totalPurchases = value; doSomething();}
    }
    void doSomething(){
    // Code
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d85f4d3-fbb1-2aba-9acb-a1b5122bc484
* Version Independent ID: 19163540-1a7d-2524-370a-8b20d5735d90
* Content: [Auto-Implemented Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/auto-implemented-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/auto-implemented-properties.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Auto-implemented properties exist specifically to make the case when you don't need to execute any other code while getting or setting property simpler. If you do need that, you should keep using regular properties, they're not obsolete.

**Comment by BillWagner** [comment]
Thanks for writing this @faizidp 

As @svick stated, writing `set` accessors (and `get` accessors) continue to be first class citizens in the C# language. Use them when you need them. Use auto-implemented properties when your property wraps a raw field, without additional validation or computation.

I'll close this as an answered question. If you have other questions, update this issue, or start a new discussion.
