### ISSUE TITLE
System.Collections.Generic.Dictionary lacks documentation

### ISSUE THREAD

**Issue by tpamula** [dotnet/docs#11341]
I've noticed several undocumented methods in that class: [EnsureCapacity](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.ensurecapacity?view=netcore-2.2) (mentioned in #7608), [TrimExcess](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trimexcess?view=netcore-2.2), [TryAdd](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=netcore-2.2).

**Comment by Thraka** [comment]
Closing this as a duplicate. All of the APIs for the type are in a single article, so when someone goes to edit the description of one method, they should add descriptions to all methods properties etc. I'll make sure the other bug is edited to clarify this 😄

**Comment by Thraka** [comment]
Duplicate #7608
