### ISSUE TITLE
mention how to get the default value for a given Type

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#11359]
Type t = typeof(int);
int foo = something t something;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d4015e-aa05-9193-e3f5-f273c86142c9
* Version Independent ID: ec47da08-f2b5-bc26-bf02-502ee83079bd
* Content: [Value types - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types)
* Content Source: [docs/csharp/language-reference/keywords/value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/value-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@daveyostcom I'm not sure what you mean by this:

```csharp
int foo = something t something;
```

Can you provide more details?

**Comment by daveyostcom** [comment]
int foo = Activator.CreateInstance(t);   // is this a robust approach?

**Comment by svick** [comment]
If you know the type `T` at compile-time, then you should use `default(T)`. (In your case, it seems you know that it's an `int`.)

If you only have a `Type` instance and you know that it's a regular value type, then `Activator.CreateInstance` is a reasonable choice.

Though I'm not sure any of this should be mentioned in the *Value types* article: `default(T)` is already explained in the linked [Default values table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default-values-table) and using `Activator.CreateInstance` this way is fairly advanced and should be quite rare.

**Comment by daveyostcom** [comment]
The question is what to at runtime. I set `t` only for the purposes of the example.

The reason to mention it on the page is because the page says how to get a default instance only at compile time; it should also cover runtime. That's what I was looking for on the page! The  Default Values Table article doesn't answer the question either. One of them should cover it; either will do.

Btw, you say only "a reasonable choice". What makes it nothing more? If there are gotchas with that choice, a full solution should be spelled out on one or the other of these pages.

**Comment by svick** [comment]
The gotchas that I'm aware of:

* `Activator.CreateInstance` is fairly slow, see https://github.com/dotnet/corefx/issues/31646.
* If you have a value type with a default constructor, `Activator.CreateInstance` will call it, which means it will not return the default value. Though it's not possible to create such types in C#, which is why they are extremely rare. But they are technically possible.

**Comment by BillWagner** [comment]
Thanks for the clarifications @daveyostcom (and the additional info @svick)

I've added this to our backlog for when we next update this page.
