### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by GuentherK** [dotnet/docs#11368]
The third position of the SDK version number communicates both the minor and patch number. The minor version is multiplied by 100. Minor version 1, patch version 2 would be represented as 102. The final two digits represent the patch number. For example, the release of .NET Core 2.2 may create releases like the following table:

| Change | .NET Core Runtime | .NET Core SDK (*) |
| -------- | --------------------- | -------------------- |
| Initial release | 2.2.0 | 2.2.100 |
| SDK Patch | 2.2.0 | 2.2.101 |
| Runtime and SDK Patch | 2.2.1 | 2.2.102 |
| SDK Feature change | 2.2.1 | 2.2.200 |

It's already late here thus i apologize in advance if I'm wrong, but 2*100 is still 200 not 100. Therefore the initial SDK release should be 2.2.200 and each patch would add +1 to it. Likewise the last line should have been 2.2.204. Seems like the explanation to your versioning is not correct.

Also check out the 2.2.X SDK versions of your own [download page](https://dotnet.microsoft.com/download/dotnet-core/2.2)  
Your example table does not match your own version page.

**UPDATE:** I propose following change to your versioning to be more logical:
- SKD patch version will be runtime patch version times 100 + 1 for each SDK patch
this would create following table:

| Change | .NET Core Runtime | .NET Core SDK (*) |
| -------- | --------------------- | -------------------- |
| Initial release | 2.2.0 | 2.2.000 |
| SDK Patch | 2.2.0 | 2.2.001 |
| Runtime and SDK Patch | 2.2.1 | 2.2.100 |
| SDK Feature change | 2.2.1 | 2.2.101 |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Core Runtime and SDK are versioned - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/#feedback)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/index.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello, thank you for your question :)

This is part talking about the versioning of the SDK, not the versioning of the Runtime. If you look at the paragraph before the one you quoted, it says this:

>The .NET Core SDK releases faster and its versions must communicate both the aligned runtime and the SDK's own minor and patch releases. The first two positions of the .NET Core SDK version are locked to the .NET Core Runtime it released with.

So in versioning the SDK, it follow this format: 

```
RM.Rm.SMmm

RM = Runtime Major
Rm = Runtime Minor
SM = SDK Major
mm = SDK Minor
```

Regarding suggestion a version number system change, you should make that request over on the core/sdk repos, like https://github.com/dotnet/core

I think this answers your question and I'm going to close this issue. Cheers!
