### ISSUE TITLE
Small text fix in Method Invocation

### ISSUE THREAD

**Issue by EricHusa** [dotnet/docs#11367]
Hi, I realize this is small but thought I'd point it out. 
A line in Method Invocation section says "static methods operate do not operate on instance data".
The first occurrence of the word 'operate' should be deleted, so it reads "static methods do not operate on instance data".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods#return-values)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for pointing this out @EricHusa 

I've implemented a fix. If you spot these in the future, you can create a PR to correct these.

Thanks again for helping us make docs better.
