### ISSUE TITLE
Looking for section on defining abstract indexer

### ISSUE THREAD

**Issue by glenbraun** [dotnet/docs#11372]
On the page: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties

It would be helpful to have a section describing how to define an indexer on an interface. (Assuming this is possible). 

I'm currently trying this:
type IFooHaveAnIndexer =
    interface
    abstract Item : int -> string with get, set  // I'm still experimenting if this works
    abstract SomeOtherIndexer : int -> string with get, set  // non-default indexer
    end

Since I don't know if one *can* define an interface that specifies the requirement of an indexer (default or not), I understand if you consider this documentation issue to be more of a support question. I'm sorry for that. Still, I did go to this page on indexers looking for information on how to define them on interfaces (or abstract classes). 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47d926c-72f6-0a8e-140d-7a31cd8e17d3
* Version Independent ID: 5d587fbe-7771-c826-7a72-75f69d61bc55
* Content: [Indexed Properties (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties)
* Content Source: [docs/fsharp/language-reference/members/indexed-properties.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/indexed-properties.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
In this case you need to just define `Item` on the interface.

```fsharp
type IFooHaveAnIndexer =
    abstract Item : int -> string with get, set

type C() =
    let items = [| "hey"; "there" |]
    interface IFooHaveAnIndexer with
        member __.Item
            with get(idx) = items.[idx]
            and set idx v = items.[idx] <- v

let c = C() :> IFooHaveAnIndexer
c.[0]
```

This prints: "hey".

**Comment by glenbraun** [comment]
Yes, thanks much for the response.
