### ISSUE TITLE
A section here on extensions would be nice.

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#11385]
Extensions need a Guide, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/index)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I think this is a good idea. Also, there is no `Methods` section either, seeing `Properties` and `Events`...

**Comment by Thraka** [comment]
@BillWagner Added this to the backlog and defaulted to P2.

**Comment by BillWagner** [comment]
@daveyostcom Just to clarify:  Do you mean "extension methods" or "extensions you can install in your editor or IDE"?

**Comment by daveyostcom** [comment]
extension methods

**Comment by pkulikov** [comment]
> I think this is a good idea. Also, there is no `Methods` section either, seeing `Properties` and `Events`...

It looks to be a TOC organization issue. Some type members can be found under "Classes and structs" TOC entry. For example, extension methods are there:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

Strange that "Indexers" and "Events" are on the same level as "Classes and structs", but not inside it.

**Comment by Thraka** [comment]
> > I think this is a good idea. Also, there is no `Methods` section either, seeing `Properties` and `Events`...
> 
> It looks to be a TOC organization issue. Some type members can be found under "Classes and structs" TOC entry. For example, extension methods are there:
> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods
> 
> Strange that "Indexers" and "Events" are on the same level as "Classes and structs", but not inside it.

Indeed :)
