### ISSUE TITLE
Clarify signature matching rules for event handlers

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#11389]
The docs currently say:

> The signature of the `eventhandler` procedure must match the signature of the `event` event.

As written, one can get the impression that the match must be exact and end up missing some handy features as shown in this code:

```vb
Public Module TestModule
  Public Event Foo(ArgValue As ArgumentNullException)

  Public Sub Test()
    AddHandler Foo,
      Sub()
        'handler does NOT have the ArgValue parameter in it's signature
        'but VB allows this.
      End Sub

    AddHandler Foo,
      Sub(ArgValue As Exception)
        'handler's ArgValue parameter's type does not match the Foo event type
        'but the types are compatible and this is perfectly legal.
      End Sub
  End Sub
End Module
```

If there is another document covering the signature matching rules that allow the above, I suggest it be linked to. If no such document exists, then it should be created (possibly extracting portions from the language spec) or perhaps an example similar to the code above could be added just to show what is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7771f230-ac9e-7310-e606-94bd9fc84f29
* Version Independent ID: 728dfc67-f3e9-64ea-8a91-c6d72c8cc54f
* Content: [AddHandler Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/addhandler-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/addhandler-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/addhandler-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
Thank you for pointing this out. I'm adding it to the backlog.
