### ISSUE TITLE
Correct interface summary definition

### ISSUE THREAD

**Issue by irinascurtu** [dotnet/docs#11388]
**Issue description**
https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md#interfaces-summary
"An interface is like an abstract base class."
should have more details, because this way is confusing.
The complete explanation should be:

"An interface is like an abstract base class with only abstract members"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for pointing this out.

I also think that this sentence should be removed:

>Therefore, by using interfaces, you can include behavior from multiple sources in a class.
