### ISSUE TITLE
 Opening VS Cmd Promt from with VS - Initial directory field, such as Project Directory

### ISSUE THREAD

**Issue by gperrego** [dotnet/docs#11381]
this is good info to say that we probably want to set the initial directory as Project Directory, but some more information on how to set the directory as project directory would be helpful.  I don't know how to do that currently.  

Thanks, 
Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs#feedback)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by TonySullivan** [comment]
Put $(ProjectDir) in the Inital Directory text box. Also click the triangle at the end of the text box for more options

**Comment by gperrego** [comment]
Okay can we update the documentation to include that?

**Comment by gperrego** [comment]
maybe state that we can use different variables and a link to what the standard variables are?

**Comment by jtbrower** [comment]
Each time I find myself on a foreign machine and my shortcut to the command prompt isn't available I ask myself, "Why don't they make this a built in command?".

**Comment by mairaw** [comment]
Thanks for your feedback @gperrego. I've created PR https://github.com/dotnet/docs/pull/16414 to fix this. 

@jtbrower if you haven't already, make a suggestion to the VS team using https://developercommunity.visualstudio.com/.
