### ISSUE TITLE
XAML 2009

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#11391]
I feel this section could use some details on why WPF uses XAML 2006 and not XAML 2009 and what the differences are between both those.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbd11a3-323a-64e8-e55d-3ce2cbc499f3
* Version Independent ID: bb64b751-8ace-5bfc-6b4d-7e77e392a31f
* Content: [XAML in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-in-wpf)
* Content Source: [docs/framework/wpf/advanced/xaml-in-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/xaml-in-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for the suggestion. I don't think discussing why the 2009 spec was not implemented is really appropriate for the documentation. From what I've gathered, the 2009 spec seems to have been created to support the XAML Services stuff.

However, understanding the differences would be helpful.
