### ISSUE TITLE
File Order

### ISSUE THREAD

**Issue by francisl** [dotnet/docs#11393]
For someone with experience with many different programming languages. I have wasted way to much time figuring out that I need to order my file in order of dependencies. This is a particular issue, especially when in the same namespace.

It would be nice if the page include a note about this. Or a link where it is explain. While looking to solve my problem this page seem logical to provide that information.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379f00ab-ebc1-50eb-6779-3a22ec41a80d
* Version Independent ID: 6f88dfb3-c9f9-3715-5121-83a1f22223b8
* Content: [Modules - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/modules#feedback)
* Content Source: [docs/fsharp/language-reference/modules.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/modules.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by baronfel** [comment]
Adding on to this, Phillip mentioned that this is really two suggestions:

* Notes that file ordering is a thing and explanations why that is the case
* suggestions for file ordering (particularly as a way of organizing project layouts)


As an example for the second point, it often comes about in F# code the the top-most files are very general. Perhaps they are extentions to BCL types, wrappers around BCL functions, or utility functions that the project uses, almost like a custom prelude.  Then follows the Domain layer, where the types representing your domain are defined and functions that operate on them are placed. Finally the composition root layer, where the domain types are hooked up, partial application comes into play, and the result is a runnable application or azure functions runnable endpoint, etc.
