### ISSUE TITLE
Epub format of https://docs.microsoft.com/en-us/dotnet/framework/data/index

### ISSUE THREAD

**Issue by ozkanb** [dotnet/docs#11390]
Can I somewhere download an epub version of all documentation in https://docs.microsoft.com/en-us/dotnet/framework/data/index ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0be085-e177-a711-c00c-9a994e40f3e7
* Version Independent ID: 6a508a11-62bb-eaff-c8ff-6c84ca35adc4
* Content: [Data and Modeling in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/data/index)
* Content Source: [docs/framework/data/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/index.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Sorry, these issues are for problems with the documentation and issues with the website are not something we can do anything about. I would use the link at the bottom of the page to give site feedback: https://aka.ms/sitefeedback

The site supports downloading as PDF (left bottom of the table of contents) and you could try using some sort of PDF to EPUB converter.
