### ISSUE TITLE
SyntaxError when executing code sample

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11413]
@MSeifert04 commented on [Wed Mar 20 2019](https://github.com/dotnet/docs.de-de/issues/129)

In  docs.de-de/docs/standard/base-types/standard-numeric-format-strings.md 

![Unbenannt](https://user-images.githubusercontent.com/14200878/54689268-7a557100-4b1f-11e9-8b50-5c849006cc02.png)

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor is reporting an error in the example code
best

**Comment by rpetrusha** [comment]
Thanks for reporting this issue, @MSeifert04 and for moving it to our repo, @CeciAc. We've opened issue dotnet/try#174 in the dotnet/try repo.
