### ISSUE TITLE
Clarity

### ISSUE THREAD

**Issue by crmckenzie** [dotnet/docs#11419]
I recently found this element in a production web.config. This article seems to imply but doesn't make it crisp that this element is not necessary in the production web.config and probably should not be included there. Am I understanding the article correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d587a1-f62f-3380-c005-e556a1c3a891
* Version Independent ID: c1aabcf4-9d2b-4167-2965-b30f70300cd9
* Content: [&lt;identity&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/identity#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/identity.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/identity.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
@Lxiamail

**Comment by Lxiamail** [comment]
@mconnew  can you help to clarify?

**Comment by mconnew** [comment]
I don't believe clarification is necessary for this documentation page as this page is primarily describing the configuration schema. The page title is \<identity> and the page is in the "WCF Configuration Schema" section so I believe it's quite clear the scope of this page. The page only talks about the behavior of WCF sufficient to give context for describing what values can be used in this section of config. In the first paragraph it's says for more information to follow a link to [Service Identity and Authentication](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/service-identity-and-authentication). That page provides a lot more information about how WCF behaves in relation to setting the identity. In the third section titled [Specifying Identity at the Service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/service-identity-and-authentication#specifying-identity-at-the-service) it says the following:

> Typically, you do not have to set the identity on a service because the selection of a client credential type dictates the type of identity exposed in the service metadata.

So the information is correctly documented and easily discoverable as the link to this is in the very first paragraph. Basically if more information is needed, it's helpful to follow the link for more information.

**Comment by Thraka** [comment]
@mconnew Thank you for the answer. Closing this issue.

**Comment by crmckenzie** [comment]
"This article seems to imply but doesn't make it crisp that this element is not necessary in the production web.config and probably should not be included there."
I have a team of experienced engineers who were confused on this point--and the quoted text does not directly address the question. Just FYI.

Our subsequent testing seems to indicate that this section is created by Visual Studio when you "Update Service Reference." It puts the developer's identity in the web.config. This showed up in production which we found alarming. It appears that this section is not used in production at run-time and that it's safe to delete it. The documentation does not address this point afaict. 

Thanks for listening.

**Comment by Thraka** [comment]
@crmckenzie I think what is being pointed out is that this is reference material to the schema. Perhaps in your scenario it is a pointless node, but the intent of the reference is to make sure the elements are documented. 

The intro does specifically state: 

>The identity element allows a client developer to specify at **design time** the expected identity of the service.

So design time would not be in a production environment 😄 However, we encourage users to click the edit button at the top of the page and add sentences to clarify things, you are free to do it, but I think we're just going to leave this as is.

Thanks again.
