### ISSUE TITLE
Why does a decimal get an "m" suffix?

### ISSUE THREAD

**Issue by Stormjack** [dotnet/docs#11423]
In this article, please indicate why the letter "m" was chosen as the suffix for the numeric string literal of a decimal. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e67d6d-6c88-b3ca-cbe1-0d8f0fb77ca0
* Version Independent ID: ef1559a2-dd3d-b204-fc1c-8422b8dfc445
* Content: [decimal keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/decimal#feedback)
* Content Source: [docs/csharp/language-reference/keywords/decimal.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/decimal.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by NextTurn** [comment]
https://stackoverflow.com/questions/977484/what-does-the-m-stand-for-in-c-sharp-decimal-literal-notation

**Comment by BillWagner** [comment]
Great question @Stormjack  The SO question reference by @NextTurn answers this well (as does the annotated C# spec). I'm closing this as resolved.
