### ISSUE TITLE
TLS 1.3 Support for .Net 3.5 and 4.0

### ISSUE THREAD

**Issue by AlMataMS** [dotnet/docs#11421]
Hi,

Looking for some guidance around below topic:
1.	What exactly does the TLS1.0/1.1 phase out mean? 
2.	Will Microsoft (MS) make breaking changes in future versions of .NET, IIS, IE, Windows OS to block TLS1.0/1.1?
3.	What will be the exact phase out mechanism?
4.	What will be the support strategy from MS regarding TLS1.3 for current and earlier versions of .NET – 3.5 & 4.0? 
5.	We have applications that cannot move away from .NET 3.5/4.0. Will there be TLS1.3 support for older versions of .NET? 3.5? 4.0?
6..	Other ways of supporting .NET3.5 & 4.0 ?

Thank You,
AM

**Comment by mairaw** [comment]
@blowdart is this something you can help with?

**Comment by blowdart** [comment]
This is something I'm not willing to comment on at this time.

**Comment by blowdart** [comment]
(And as it's not a docs issue, should probably be closed)

**Comment by mairaw** [comment]
Yes, I marked as a product question. Closing it then.

**Comment by AlMataMS** [comment]
Barry,

This request is coming from our partner Varian Medical for development of their future products.  We are in process of 25million dollar azure commit sales, having conversation with Ms on this topic would help.  Could you point me to someone who could talk to customer and team.

Thank you,

Al Mata
Application Development Manager
Microsoft, Corp. | 1065 La Avenida | Mountain View, Ca 94043<x-apple-data-detectors://0/1>
Phone: +1 (650) 693-3902<tel:+1%20(650)%20693-3902>
Email: almata@microsoft.com<mailto:almata@microsoft.com>
Premier Support: 1-800-936-3100<tel:1-800-936-3100>
https://premier.microsoft.com/
[cid:image003.jpg@01CDB6E2.87B89EE0]
“Share with me your vision and let me drive your breakthrough”

On Apr 1, 2019, at 4:59 PM, Barry Dorrans <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something I'm not willing to comment on at this time.
