### ISSUE TITLE
code and output for client do not match

### ISSUE THREAD

**Issue by zigfig21** [dotnet/docs#11437]
Defined output:
Add(100,15.99) = 115.99
Subtract(145,76.54) = 68.46
Multiply(9,81.25) = 731.25
Divide(22,7) = 3.14285714285714

Press <ENTER> to terminate client.

However the code should look something like
            //Step 3: Closing the client gracefully closes the connection and cleans up resources.
            Console.WriteLine();
            Console.WriteLine("Press <ENTER> to terminate client.");
            Console.WriteLine();
            Console.ReadLine();
            client.Close();
to achieve that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81879896-7161-3352-eecb-87a2158dc003
* Version Independent ID: 286eb468-4007-fc0d-1d33-76139225d565
* Content: [How to: Use a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-use-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-use-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-use-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I think the rewrite will fix this problem. It should be published today. Thank you for filing it.
