### ISSUE TITLE
Incorrect code to generate this warning

### ISSUE THREAD

**Issue by sjrsquared** [dotnet/docs#11432]
public class Test_CS0114
{
    /// Text
    public virtual void F()
    {
        throw new System.NotImplementedException();
    }
}
/// Text
public class Test_CS0114_2 : Test_CS0114
{
    /// TExt
    public virtual void F() // CS0114, hides base class member  
                    // try the following line instead  
                    // override public void F()  
    {
        throw new System.NotImplementedException();
    }    
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edea0025-50c8-e53f-67d1-895ee672c7cb
* Version Independent ID: 851e316c-73f6-691c-3165-42db55208736
* Content: [Compiler Warning (level 2) CS0114](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0114#feedback)
* Content Source: [docs/csharp/misc/cs0114.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0114.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
I'm not certain that I understand your comment, @sjrsquared. The code in the example produces CS0114, as does the code that you've supplied. I'm going to close this issue. Please feel free to respond, though, in the event that I've misunderstood.

**Comment by sjrsquared** [comment]
Ron

Thanks for the reply

I forgot to mention why I submitted the new code. My fault !

My new section JUST produces cs114. The code there produces that warning and also a fatal error. I wanted only the warning.

Sent from my mobile

Kind Regards,
Simon Rowe

Siemens HC Ltd MR Magnet Technology
SHS IT LE CFE
Tel +44 1189 471384
Mobile : +44 7921 243214
E-Mail simon.rowe@siemens-healthineers .com<mailto:simon.rowe@siemens.com>

 Important notice: This email and any attachment thereof contain corporate proprietary information. If you have received it by mistake, please notify us immediately by reply email and delete this email and its attachments from your system. Thank you.

On 26 Mar 2019, at 22:08, Ron Petrusha <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not certain that I understand your comment, @sjrsquared<https://github.com/sjrsquared>. The code in the example produces CS0114, as does the code that you've supplied. I'm going to close this issue. Please feel free to respond, though, in the event that I've misunderstood.
