### ISSUE TITLE
Getting Started with Ionide Improvements

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1143]
- [ ] Add a console app project which calls this code
- [ ] Debugging the code
- [ ] Show how to compile code (even without FAKE plugin - setup VSCode task `[tasks.json]` running `build.cmd` / `build.sh`)
- [x] Look at non-VS Windows installs and see if we can realize the fact that you need both MSBuild 2013 and MBuild 25

**Comment by mairaw** [comment]
@cartermp should this be a project? and what's the target milestone?

**Comment by cartermp** [comment]
Milestone is backlog.  Yes, a project would be appropriate.

**Comment by JRAlexander** [comment]
This isn't a project.

**Comment by cartermp** [comment]
A bit, yes. I plan on rewriting this in about two weeks when I'm traveling.

**Comment by BillWagner** [comment]
@cartermp This has languished. What should be the next steps?

**Comment by Krzysztof-Cieslak** [comment]
`Debugging the code` is not done yet.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
