### ISSUE TITLE
update to 0.11 release

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#11431]
with features in the latest release the estimators should be renamed, the code should be:

           var pipeline = mlContext.Transforms.Normalize(
            new NormalizingEstimator.MinMaxColumnOptions(inputColumnName: "Features", outputColumnName: "MinMaxNormalized", fixZero: true),
            new NormalizingEstimator.MeanVarColumnOptions(inputColumnName: "Features", outputColumnName: "MeanVarNormalized", fixZero: true),
            new NormalizingEstimator.BinningColumnOptions(inputColumnName: "Features", outputColumnName: "BinNormalized", numBins: 256));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035eb02-911d-e608-28b5-714af6f2fdad
* Version Independent ID: 96b429f0-6a04-91fe-bd77-e7a675c3bbd1
* Content: [Preprocess training data with normalizers to use in data processing - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/normalizers-preprocess-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/normalizers-preprocess-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/normalizers-preprocess-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Addressed as part of #11613
