### ISSUE TITLE
Screenshots are beneficial

### ISSUE THREAD

**Issue by BenEzard** [dotnet/docs#11430]
This (and other examples) could be greatly improved by adding a screenshot example. I shouldn't have to download from GitHub just to see what the code is going to give me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd0892f-7da6-17f8-efa2-3127f3597042
* Version Independent ID: e0b27f87-e253-738f-569f-e854094f1471
* Content: [How to: Create a Custom View Mode for a ListView](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-create-a-custom-view-mode-for-a-listview#feedback)
* Content Source: [docs/framework/wpf/controls/how-to-create-a-custom-view-mode-for-a-listview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-create-a-custom-view-mode-for-a-listview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. Back-filling screenshots is not a high priority for us right now. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by mairaw** [comment]
Also added this to our community project, in case someone is interested to help out with this issue.

**Comment by santoshyadav198613** [comment]
Hi @mairaw,
Will wok on it. 

Regards, 
Santosh
