### ISSUE TITLE
Options and nulls

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/docs#11459]
This should also discuss what happens when a null is placed inside an Option&lt;T&gt;. For example, say a C# function called `FSFunction( Option&lt;string&gt;.Some(null) )`. 

This is important because Some(null) does not equal None.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1e23a2-091b-38be-3bbe-b3b38aa06aa5
* Version Independent ID: 431e250a-3588-7741-dd43-8021d6c7ffa8
* Content: [Options - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/options)
* Content Source: [docs/fsharp/language-reference/options.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/options.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
`Some null` <> `None` because both are distinct cases in a discriminated union, which is consistent with how the F# type system works.

What kind of information are you looking to have documented here?

**Comment by Grauenwolf** [comment]
Just that. It's a rather technical point, but it should mention how `Some null` is a possibility. 

It's an unusual situation to be sure, but it can happen, especially when dealing with interopt between C#/VB and F#.
