### ISSUE TITLE
Improve code examples

### ISSUE THREAD

**Issue by SamirBanjanovic** [dotnet/docs#11455]
These code examples are very straight forward, however, I would argue they are more ore less encouraging poor practice.  Code such as `var (_, _, _, pop1, _, pop2) = QueryCityDataForYears("New York City", 1960, 2010);` would not pass most code reviews. A very good use case for discards is `TryAction` with `out` params. 
For early learners some of these code examples could encourage some bad behavior.

--Update: removed sentence inarticulately mentioning Linq. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards#feedback)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
I don't understand, how would you use LINQ, when the example doesn't have any collections?

**Comment by SamirBanjanovic** [comment]
sorry that's a mistake on my part. I was reading something else while typing this and didn't proofread this. I am mainly concerned about exposing new developers to discards in such a way that we'll see code everywhere as `var (_, _, _, someProperty1, _, someProperty2)` vs properly extracting code where our top level method has `var (someProperty1, someProperty2`. I recognize what the article is show, but it also needs to consider that a lot of new developers repeat what they see in these docs

**Comment by svick** [comment]
Would it help if the extra tuple elements were used elsewhere in the example? That way, those elements would not be unused.

**Comment by SamirBanjanovic** [comment]
@svick if we did that it would eliminate the discards example. What if the discards are moved to the calling method so the Main is as clean as possible? What would be the best approach to illustrate discards and keep the code clean?

**Comment by SamirBanjanovic** [comment]
After further evaluation I think this would make unnecessary changes to the example. Closing the issue.
