### ISSUE TITLE
Information on this

### ISSUE THREAD

**Issue by guerrajames** [dotnet/docs#11462]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 618121e9-bdd2-5db7-4d96-190a5978c5f5
* Version Independent ID: 28616eb2-03b0-c490-3671-e14cf3048a5d
* Content: [Additional class libraries and APIs](https://docs.microsoft.com/en-us/dotnet/framework/additional-apis/index)
* Content Source: [docs/framework/additional-apis/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/additional-apis/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Your issue seems incomplete @guerrajames so closing this one. Please let us know if you meant to ask something about this article.
