### ISSUE TITLE
Old or obsolete

### ISSUE THREAD

**Issue by kcrandall** [dotnet/docs#11466]
Many of the lines have errors that prevent the code from being run

1. loading data should be this couldn't find find the read method
 var data = reader.Load(new MultiFileSource(filePath));

2.
WordEmbeddingsExtractingTransformer.PretrainedModelKind.GloVeTwitter25D -&gt; WordEmbeddingsExtractingEstimator.PretrainedModelKind.GloVeTwitter25D is one of the fixes

3.
new WordBagEstimator -&gt; mlContext.Transforms.Text.ProduceWordBag

4 and 5
the other two errors are similar to issue 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b493301-c072-072c-f4cb-acc1a715be1a
* Version Independent ID: 1de67636-94b4-8c0a-b639-8e0a8d6bb244
* Content: [Apply feature engineering for model training on textual data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/train-model-textual-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/train-model-textual-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-model-textual-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi, @kcrandall, we are in process of updating these to v 1.0.0-preview.

**Comment by luisquintanilla** [comment]
Addressed in #11613
