### ISSUE TITLE
LoadData has wrong return type

### ISSUE THREAD

**Issue by Skybladev2** [dotnet/docs#11472]
The LoadData method has (IDataView trainSet, IDataView testSet) retrurn type in article text.
However, the returning variable has TrainCatalogBase.TrainTestData type.
So, the code is not compilable.
If we look at the sample code at github we'll see that it has correct return type: https://github.com/dotnet/samples/blob/master/machine-learning/tutorials/SentimentAnalysis/Program.cs#L56

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @Skybladev2, for the feedback! This has been fixed.
