### ISSUE TITLE
Using Stream.Close()

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#11479]
Is it OK to use Stream.Close() in the Symmetric Encryption example instead of Dispose()/using?

That's a fragment from the docs on Stream.Close Method:
You do not have to specifically call the Close method. Instead, ensure that every Stream object is properly disposed. You can declare Stream objects within a using block (or Using block in Visual Basic) to ensure that the stream and all of its resources are disposed, or you can explicitly call the Dispose method

(Sorry for not providing the link but don't see how to do it)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee15f916-5406-85fa-b7fb-a9e69fcd3efb
* Version Independent ID: b6aae569-8a56-0a44-7b8e-e54491418baf
* Content: [Encrypting Data](https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data#feedback)
* Content Source: [docs/standard/security/encrypting-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/encrypting-data.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
It's preferable to use a `using` statement, @user2150. Our code violates this best practice in numerous cases, though. If you'd like to submit a pull request to replace the call to Close in this example with a `using` statement, we'd welcome your PR. For more information, see our [contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).

**Comment by user2150** [comment]
Got it. Thanks.
