### ISSUE TITLE
Is it regarded as good practice to be this verbose

### ISSUE THREAD

**Issue by andybak** [dotnet/docs#11484]
Dictionary&lt;int, StudentName&gt; students = new Dictionary&lt;int, StudentName&gt;()

Reads like a parody of what's wrong with explicitly typed languages.

I would have thought this was a canonical use case for var?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e35585-87f4-f2da-1aa3-5a6b2182f45e
* Version Independent ID: d9b333b1-7e9b-2efe-3284-43ad82826820
* Content: [How to initialize a dictionary with a collection initializer - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by andybak** [comment]
Thankfully it seems like it contradicts the official C# style guide: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

**Comment by rpetrusha** [comment]
Thanks for pointing out the verbosity of the example, @andybak. We've modified it in dotnet/samples#1013.
