### ISSUE TITLE
Documentation out of sync?

### ISSUE THREAD

**Issue by seesharpdev** [dotnet/docs#11508]
The 'emailAddresses' collection contains "js@contoso.中国" but the result of the test shows "Valid: js@contoso.ä¸­å›½".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format#feedback)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @seesharpdev for your feedback. I've opened PR https://github.com/dotnet/samples/pull/750 to fix this.
