### ISSUE TITLE
Unclear infinite while loop

### ISSUE THREAD

**Issue by SjorsVanGelderen** [dotnet/docs#11502]
The first example has a while(true) loop without a break statement. The sentence "The client receives a message string and writes the message to the console." is confusing here, because the application keeps on doing this until some exception occurs. There doesn't seem to be a clean way to exit from the loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Using UDP Services](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services#feedback)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by rpetrusha** [comment]
@davidsh, it seems that our UDPClient examples all show either a single Receive call or a call in a loop with no exit condition. Is there a recommended practice for terminating a loop that calls UDPClient.Receive?

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @SjorsVanGelderen. We'll investigate to determine the recommended way to handle repeated Receive calls. In the meantime, I've added this issue to our backlog.
