### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11505]
@heyangmingUser commented on [Tue Mar 26 2019](https://github.com/dotnet/docs.zh-cn/issues/357)

[在此处输入反馈]

dotnet add reference ../PrimeService/PrimeService.csproj
link:https://docs.microsoft.com/zh-cn/dotnet/core/testing/unit-testing-with-dotnet-test?toc=/aspnet/core/toc.json&bc=/aspnet/core/breadcrumb/toc.json&view=aspnetcore-2.2
Path format error,Please correct it
---

#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [使用 dotnet test 和 xUnit 在 .NET Core 中进行 C# 代码单元测试](https://docs.microsoft.com/zh-cn/dotnet/core/testing/unit-testing-with-dotnet-test?toc=/aspnet/core/toc.json&bc=/aspnet/core/breadcrumb/toc.json&view=aspnetcore-3.0)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

---

@imba-tjd commented on [Tue Mar 26 2019](https://github.com/dotnet/docs.zh-cn/issues/357#issuecomment-476458477)

没看出哪里error了。你想说要用反斜杠，不用斜杠？

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor is reporting an error in the code.

There's also PR which appears to fix it, but just on the localized version. https://github.com/dotnet/docs/pull/11500
Please check if this is correct

**Comment by rpetrusha** [comment]
This is fixed by #11500. Closing.
