### ISSUE TITLE
"Layers" or "Layer" ?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [dotnet/docs#11507]
Regarding this line: 

`This COPY instruction copies the rest of the files into our container into new layers.`

Shouldn't it be "into a new layer"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Containerize an app with Docker - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/docker-basics-dotnet-core#feedback)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Yes. I'm currently rewriting this article. Thank you for pointing this out.
