### ISSUE TITLE
How to unlink one of many targets from a source?

### ISSUE THREAD

**Issue by lettucemode** [dotnet/docs#11513]
My app is reading data off of some hardware, which gets processed three or four times before showing up on a graph or in a datafile. I'm implementing this process using this Dataflow library (which is great, by the way).

The main dataflow network needs to persist throughout the app's lifetime. I also have a requirement that when the user clicks a button, the app should record the data that's flowing through until they click again, and then run some calculation on the recorded data. I'd like to implement this in my dataflow network class like so:

```
public void LinkToExample(ITargetBlock<double> tempTarget)
{
    this.ExampleBlockFromThePipeline.LinkTo(tempTarget);
}
```

My question is how to unlink this when I want to stop recording. The article above doesn't really answer the question. Can I just call Complete() on the temp target block? Will I run into a memory leak if I do that and a malicious user clicks the button repeatedly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ab5489-f298-dd0d-6812-68ed98365dc5
* Version Independent ID: de509e9a-3c3d-a485-4a41-3cb9ef6ff2a9
* Content: [How to: Unlink Dataflow Blocks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-unlink-dataflow-blocks#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-unlink-dataflow-blocks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-unlink-dataflow-blocks.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
The [LinkTo method](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.isourceblock-1.linkto?view=netcore-2.2) returns an `IDisposable` that, according to the referenced docs:
> ...upon calling `Dispose`, will unlink the source from the target.

@lettucemode worth a try?

**Comment by lettucemode** [comment]
Ah thanks, I missed that. I'll give it a shot.
