### ISSUE TITLE
R squared value should be better when closer to 1

### ISSUE THREAD

**Issue by atruskie** [dotnet/docs#11514]
&gt; R Squared is the variation percentage in the predicted 
&gt; values explained by your model. It's a value between 0
&gt; and 1, and the closer the value is to 0, the better the 
&gt; model is.

I'm used to the R Squared value being closer to 1 when the result is better http://blog.minitab.com/blog/adventures-in-statistics-2/regression-analysis-how-do-i-interpret-r-squared-and-assess-the-goodness-of-fit

If the stated paragraph is correct for ML.NET, it may help to explain why this R squared value is different from the others. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0888bc80-798f-ebdd-459a-7543be1efdad
* Version Independent ID: c24ded82-d56c-e8c7-fd6a-e39929227177
* Content: [Use ML.NET in a movie recommendation scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/movie-recommmendation#feedback)
* Content Source: [docs/machine-learning/tutorials/movie-recommmendation.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/movie-recommmendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hey @atruskie, this is a bug. Thanks for bringing this to our attention. We'll get it scheduled and updated.
