### ISSUE TITLE
Missing 394806 (4.6.2 on OSs other than Windows 10 Anniversary Update)

### ISSUE THREAD

**Issue by AlexInAk** [dotnet/docs#11516]
Based on the article [How to determine which versions and service pack levels of the Microsoft .NET Framework are installed](https://support.microsoft.com/en-us/help/318785/how-to-determine-which-versions-and-service-pack-levels-of-the-microso), 394806 is a valid value for 4.6.2. The table should probably be updated to reflect that.

I can confirm I get 394806 back from the registry on a Server 2012 R2 server with 4.6.2 installed. For a second I was worried that maybe I was running a preview version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for your feedback, @AlexInAk. [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) lists the minimum values of the **Release** DWORD for each version of the .NET Framework; it does not list platform values. These are found in the  [.NET Framework release keys and Windows operating system versions](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/release-keys-and-os-versions) article.

This is a recent change we've made to the **How to: Determine which .NET Framework versions are installed** article, and you're not the first person to be confused by it. Within the next several days, we'll revise it to list the platform-specific **Release** values in this article, and list the minimum **Release** values in a child article.

**Comment by AlexInAk** [comment]
Thanks, that'll probably make it a little less confusing. I got thrown off a little by the wording in the "Important" panel, I thought it was implying that any version not listed, was a pre-release or preview version
