### ISSUE TITLE
Should View Code in API reference link to master?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1152]
Currently, the _View Code_ link in API reference links to the master branch, for example [the page for `StatementCompletedEventArgs`](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.statementcompletedeventargs) links to https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/RecordsAffectedEventArgs.cs/#L12.

The problem with that is that corefx master changes faster than docs, so when a type is moved (that's what happened for the above type in https://github.com/dotnet/corefx/commit/7888677b3c53596085c2fa53860d9a0519eeecfd), _View Code_ links to a 404 page.

If the _View Code_ link instead pointed to the commit that was used to generate the docs (e.g. https://github.com/dotnet/corefx/blob/f3d05c5/src/System.Data.SqlClient/src/System/Data/RecordsAffectedEventArgs.cs/#L12, assuming the commit was https://github.com/dotnet/corefx/commit/f3d05c5380a6ba430e9151a5a51f71c77bc99392), this would not happen.

**Comment by cartermp** [comment]
Good point.  I think it should link to the current release, not master.  This is going to require proper versioning support in our docs.

**Comment by BillWagner** [comment]
When we reach the point where the docs build supports viewing docs for different versions of the product, it should link to the release being viewed (which may or may not be the current release).

**Comment by mairaw** [comment]
They have changed the API build process and it's now linking to release/1.1.0. Which one do we want to show while we don't have the versioning story on docs: latest (release/1.1.0) or stable (release/1.0.0)?

**Comment by rpetrusha** [comment]
I vote for stable.

**Comment by BillWagner** [comment]
I'd agree with stable, until we have versions for the docs site. Then, the show code link should go to the branch (or label) that matches the viewed branch.

**Comment by mairaw** [comment]
I agree. I'll talk to @chenkennt to change this then.

**Comment by mairaw** [comment]
We no longer have View Code for the API reference docs, so closing this one.
