### ISSUE TITLE
Progress not shown anymore

### ISSUE THREAD

**Issue by laurentkempe** [dotnet/docs#11522]
I think to be fair you should have your final code, show the progress like in the original one!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream#feedback)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good point @laurentkempe 

That can be done by modifying the final snippet as follows:

```csharp
int num = 0;
await foreach (var issue in runPagedQueryAsync(client, PagedIssueQuery, "docs"))
{
    Console.WriteLine(issue);
    num++;
    Console.WriteLine($"Received {num} issues in total");
}
```

The advantage of the async streams implementation is that the progress can be reported directly from the loop that's iterating the issue.

I've added this to the projects for community contributors, and added the "jump in" label.

**Comment by laurentkempe** [comment]
@BillWagner I would be interested to do it! Should you assign me to it?

**Comment by BillWagner** [comment]
Done. @laurentkempe Thank you.

**Comment by laurentkempe** [comment]
Thx! That was super fast!

**Comment by BillWagner** [comment]
Adding myself as an additional assignee so this shows up in my filters.

**Comment by BillWagner** [comment]
@laurentkempe Are you still interested in making a PR for this?

**Comment by laurentkempe** [comment]
Damn, yeah sorry @BillWagner it went out of my head!
