### ISSUE TITLE
No explanation what a moveable variable is

### ISSUE THREAD

**Issue by henke37** [dotnet/docs#11525]
This is unusable without an explanation of when the `fixed` statement is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14452873-5f06-e22b-535f-60ae89c6ee77
* Version Independent ID: 1b009b50-abb9-6171-93c5-f146e4790c72
* Content: [How to: obtain the address of a variable - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/how-to-obtain-the-address-of-a-variable)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/how-to-obtain-the-address-of-a-variable.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/how-to-obtain-the-address-of-a-variable.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @henke37. Do you think that adding a link to https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code#fixed-and-moveable-variables for more information would help in this case?

**Comment by henke37** [comment]
That's a great explanation for the rules. The link would definitively clear this up.

**Comment by mairaw** [comment]
Cool. I've created a PR to fix this: https://github.com/dotnet/docs/pull/11577
