### ISSUE TITLE
Does the restriction of the I/O operations in Windows Store Apps includes the Windows 10 Apps?

### ISSUE THREAD

**Issue by moyanming** [dotnet/docs#11536]
Hi,
Does the restriction of the [I/O operations in the Windows Store Apps](https://docs.microsoft.com/en-us/dotnet/standard/io/#io-operations-in-windows-store-apps) includes the Windows 10 Apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd6a361-0292-e278-b42c-1a471e829c8d
* Version Independent ID: 209859ee-4ee3-f3ac-0cc9-e4799be859e1
* Content: [File and Stream I/O - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/)
* Content Source: [docs/standard/io/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/index.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
No, that section is about restrictions unique to Windows Store apps.
