### ISSUE TITLE
Indeed a great article

### ISSUE THREAD

**Issue by Banani-Rath** [dotnet/docs#11548]
Indeed a great article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62fb2fc-295c-d837-7d89-0835702a75d9
* Version Independent ID: f57c1676-b294-bce7-6b71-e4939371e8bb
* Content: [C# Tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/index)
* Content Source: [docs/csharp/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Is this a test issue or real kudos @Banani-Rath?

**Comment by Banani-Rath** [comment]
It is real kudos @mairaw

**Comment by mairaw** [comment]
Ha, awesome! Thanks for letting us know @Banani-Rath!
