### ISSUE TITLE
BC30258	Classes can inherit only from other classes.	GettingStartedLib

### ISSUE THREAD

**Issue by michaelvlong** [dotnet/docs#11557]
**Source:**
[https://docs.microsoft.com/en-us/dotnet/framework/wcf/getting-started-tutorial](https://docs.microsoft.com/en-us/dotnet/framework/wcf/getting-started-tutorial)

[https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-implement-a-wcf-contract](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-implement-a-wcf-contract)

**Error:**
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30258	Classes can inherit only from other classes.	GettingStartedLib	
H:\Visual Studio 2017\Projects\GettingStartedLib\GettingStartedLib\Service1.vb	6	Active

**How I got this error message:**
Proceeding through the example of creating a new WCF Library ... using the documented steps in the tutorial, the very first compilation fails.  Please see Line 6 noted in message above with the attached Service1.vb in the zip.

To generate the VB code in my project, I copied from the tutorial document and used the C# to VB convertor found here:  [http://converter.telerik.com/](http://converter.telerik.com/)

**### VB Source Code:**
**IService1.vb**
attached in zip

**Service1.vb**
attached in zip

**App.config**
attached in aip

[GettingStartedLib.zip](https://github.com/dotnet/docs/files/3022482/GettingStartedLib.zip)

**Comment by mairaw** [comment]
@michaelvlong thanks for your feedback. 

I haven't looked at your code yet but we do have the tutorial in VB as well. You need to change the language on the top:
![image](https://user-images.githubusercontent.com/12971179/55266682-889c3f00-523b-11e9-971f-2daae6f69cc0.png)

Does that code match what you've done?
