### ISSUE TITLE
Document the bar for breaking changes

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docs#11566]
**Help us make content visible**

AFAIK we don’t have good documentation on our approach to breaking changes.

Most people have a very simplistic view on this matter which is usually one of two extremes: _only changes to contracts_ vs. _any changes that can break my code_. Neither is very helpful because it doesn't accurate capture how we approach this.

**Describe the new topic**

We have a few documents in CoreFx here:

* https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-changes.md
* https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md
* https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-definitions.md

I think a good topic would start with a description on my the extremes aren't useful and that it's a continuum, along the lines of the first document. The second doc can serve as a set of useful example although I don't think the docs need to be as exhaustive. Example probably suffice.

The last doc has some useful terms we might want to define in this topic as well.

TOC wise, I think it would be good somewhere here:

![image](https://user-images.githubusercontent.com/5169960/55254477-2af4fc00-5215-11e9-9deb-3a11f11200df.png)

@rpetrusha mentioned he'd be interested in helping getting this written.

/cc @mairaw

**Comment by svick** [comment]
Do I understand it correctly that the focus of this article would be on "what guarantees can I expect from future versions of .Net" and not on "what is the design process of .Net when it comes to breaking changes"? (I think the latter wouldn't belong in documentation targeted at regular users.)

**Comment by terrajobst** [comment]
Yes, it should be written from the perspective of a consumer.
