### ISSUE TITLE
This is great, why doesn't MS practice it consistently?

### ISSUE THREAD

**Issue by rdegrove** [dotnet/docs#11564]
Got this off a web API call today: {"error":{"code":"0x80040265","message":"","innererror":{"message":"","type":"System.ServiceModel.FaultException...]","stacktrace":"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.CreateInternal(Entity...

I came here to verify that including a message is in fact an MS best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea31f6-516f-100d-046e-1a0445d92824
* Version Independent ID: a713e8c9-8210-761d-9ae7-238793825ff3
* Content: [Best Practices for exceptions - .NET](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)
* Content Source: [docs/standard/exceptions/best-practices-for-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Sorry to hear that @rdegrove. Can you let me know what product you're using? I can try to pass on the feedback but I'll be closing this issue since this is product feedback and not a problem with our documentation.
