### ISSUE TITLE
Debug of hosted dotnet application

### ISSUE THREAD

**Issue by yalaas** [dotnet/docs#11563]
I'm trying to debug dotnet core assembly hosted in a C++ host running on Linux environment. With both gdb and lldb, I am able to step through the native code side but not the managed code side. I tried to use lldb SOS plugin as outlined here: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md  the plugin seems to expect an independent coreclr process rather then hosted coreclr. 

Any ideas on how to debug hosted dotnet core apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET Core runtime host - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#feedback)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@mjrousos can you comment on this?

**Comment by mjrousos** [comment]
I'll take a look.

**Comment by mjrousos** [comment]
I tried this out and I'm able to debug hosted processes successfully. Some things to check are to make sure that the libsosplugin you're using matches libcoreclr.so and that libcoreclr.so is loaded before using SOS commands. 

I tested using an Ubuntu 18.04.2 VM and version 2.2.202 of the dotnet SDK. The specific steps I took were:

```
lldb                                        // Start the debugger
target create "./bin/linux/SampleHost"      // Set the current exe to the HostWithCoreClrHost sample
process launch -s                           // Start the process and break on start
plugin load ./bin/linux/libsosplugin.so     // Load SOS (isn't usable yet)
breakpoint set -n coreclr_create_delegate   // Set bp for a point where I know libcoreclr.so is loaded
c                                           // Go until I hit the breakpoint
clrthreads                                  // At this point, SOS commands are working
bpmd ManagedLibrary.dll ManagedLibrary.ManagedWorker.DoWork
c                                           // Set a managed breakpoint and continue until we hit it
clrstack -a                                 // See the managed stack
dumpobj <object from clrstack parameter>    // View the state of a managed object
clru <address from clrstack output>         // View annotated disassembly of the current managed method
```

Example output:

```
(lldb) clrstack
OS Thread Id: 0x5910 (1)
        Child SP               IP Call Site
00007FFFFFFFD168 00007FFF7D7128D0 ManagedLibrary.ManagedWorker.DoWork(System.String, Int32, Int32, Double[], ReportProgressFunction) [/home/mikerou/source/dotnet/samples/core/hosting/HostWithCoreClrHost/src/ManagedLibrary/ManagedWorker.cs @ 33]
00007FFFFFFFD170 00007FFF7D71165B DomainBoundILStubClass.IL_STUB_ReversePInvoke(IntPtr, Int32, Int32, IntPtr, IntPtr)
```

**Comment by yalaas** [comment]
Thank you for the response Mike!  The steps above worked.

**Comment by mjrousos** [comment]
@yalaas, no problem! If you're interested in debugging from VS Code (in addition to lldb), that should also work pretty easily. The key there will be to use the [C# extension](https://marketplace.visualstudio.com/itemdetails?itemName=ms-vscode.csharp) in VS Code and to create a debugging configuration that launches your host as the "program". Here's an example of the VS Code debug configurations I created to debug managed code hosted by the HostedWithCoreClr sample host:

```json
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/bin/linux/SampleHost",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
```
