### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by mzoz** [dotnet/docs#11579]
`using NameSpace1;` and `using NameSpace2;` not necessary in NameSpace2 code block?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7569e51d-92c7-294a-2d5f-e1ab3c35fdf8
* Version Independent ID: 86a1c11a-1d3c-902b-6cf3-5c004c59a856
* Content: [using directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-directive.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-directive.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This was fixed in dotnet/samples#771
