### ISSUE TITLE
Consider the usecase for generated files

### ISSUE THREAD

**Issue by henke37** [dotnet/docs#11581]
This directive is clearly intended for scenarios where a file is pieced together from some set of "source files" by a preprocessor like program. But the documentation barely suggests at this usecase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc080f0-56a6-12fd-5d08-6ed710d5675b
* Version Independent ID: f70ad397-abb3-0925-f920-02db4f61cb05
* Content: [#line - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-line)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-line.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-line.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @henke37 I agree that the primary use for this directive is working with code generators.

I've added it to our backlog, an we'll update this when we next update this content. In the meantime, if your interested in creating a PR for this change, see [our contributor guide](https://docs.microsoft.com/Contribute/dotnet-contribute) for instructions.
