### ISSUE TITLE
Host startup hooks

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#11585]
*Host startup hooks* coverage for 3.0+

> For .NET Core 3+, we want to provide a low-level hook that allows injecting managed code to run before the main application's entry point. This hook will make it possible for the host to customize the behavior of managed applications during process launch, after they have been deployed.

https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/host-startup-hook.md

cc: @mairaw, I inquired with engineering (`Tratcher`) on this, and he said it should be slated for coverage in the .NET Core doc set. As far as is known today, we won't be covering it in ASP.NET Core topics.

**Comment by guardrex** [comment]
Note remarks here :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/13425#issue-299984310

Hooks, *I think*, are a 3.0 thing, but the *What's new* doc at https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-2#runtime has them as a 2.2 scearnio.

**Comment by shirhatti** [comment]
@BillWagner Can we please re-open this issue? I think it's an important scenario. The contents of the doc can be taken almost verbatim from the in-repo doc at https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md
