### ISSUE TITLE
Object or not

### ISSUE THREAD

**Issue by mzoz** [dotnet/docs#11580]
In the first paragraph it says '...the latter being known as objects. ' which implies that value types are not objects and somehow contradicted by later statement that 'Every type in C# directly or indirectly derives from the object class type, and object is the ultimate base class of all types. '.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Does this document help clarifies things?
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types

**Comment by mairaw** [comment]
Closing this due to the lack of information. Please let us know if that doesn't clarify or if we misunderstood your feedback @mzoz and we can reopen this.
