### ISSUE TITLE
Final example doesn't compile

### ISSUE THREAD

**Issue by jefffhaynes** [dotnet/docs#11595]
There seems to be an error in the final example where the IntPtr state is cast to MyCompletedCallbackState.  It would also be helpful if there could be some c/c++ code that shows what the corresponding unmanaged structs look like.  Overall a helpful example though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines#feedback)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@jefffhaynes Which line of code has the error and what is the nature of the error?

**Comment by omariom** [comment]
@tdykstra 

This line:
```C#
var actualState = (MyCompletedCallbackState)state;
```

**Comment by tdykstra** [comment]
cc @GrabYourPitchforks @adamsitnik @bartonjs

**Comment by GrabYourPitchforks** [comment]
I think that line is supposed to read:

```cs
var actualState = (MyCompletedCallbackState)(handle.Target);
```
