### ISSUE TITLE
.NET Core Version Selection/Framework dependent apps move forward

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#11593]
In the example, it seems "2.0.4 is required" should be "2.0 is specified".

I'm not making the change in case we overlooked the intent. The user can specify a patch, but that isn't discussed in this part of the article.

I think it would be confusing to add it to this section, but RuntimeFrameworkVersion is discussed only in the context of self-contained apps, which we should also probably fix - maybe a new section 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET Core version to use - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#feedback)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/selection.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello! 😄 I'll set this to P1 as it's something we really need to look at.

Are you saying that the phrase "is required" should be "is specified" on that list of scenarios?

**Comment by KathleenDollard** [comment]
So far in this article, it's been about target framework which only has two digits - just netcoreapp2.0. So, the big thing is removing the patch number from the "n is required", and also, I think specified might be nicer. 

If you specify a runtime version, then I'm not sure roll forward rules are the same. So, it makes sense to keep this to the common case.

**Comment by Thraka** [comment]
Looking at this again, I think you're right. I'll fix this up.

**Comment by Thraka** [comment]
Kicking this up as it's been pushed off too many times.

**Comment by KathleenDollard** [comment]
Do you need anything from me here?

**Comment by Thraka** [comment]
No. Thanks though 😄
