### ISSUE TITLE
Resolving classes with members

### ISSUE THREAD

**Issue by Calebyang93** [dotnet/docs#11597]
Are there any ways of calling methods that does not return a definition of the class with the method? I am interested in how can one resolve the void error for using members or handling other exceptions. Please advice.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea53666-05cb-db36-4dff-71053ac5dfa3
* Version Independent ID: 549f8b52-292d-ed17-12d6-0757f362ec26
* Content: [Compiler Error CS0111](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0111#feedback)
* Content Source: [docs/csharp/misc/cs0111.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0111.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Can you give me an example of what you mean? I don't understand your question.

**Comment by Calebyang93** [comment]
> Can you give me an example of what you mean? I don't understand your question.

I am trying to return a method with another class. Why does this work and the other not work? 

``` WRONG  XAML C# 
  public partial class AppHome : NavigationWindow
  {
    public partial AppHome()
    {
      InitializeComponent();
    }
```

``` CORRECT XAML C# 
  public partial class AppHome : NavigationWindow
  {
    public AppHome()
    {
      InitializeComponent();
    }
```

**Comment by svick** [comment]
@Calebyang93 There is no such thing as "partial constructor" in C#. [C# only supports partial types and partial methods.](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)

That also means there is no way to have the same constructor more than once in a class (even if it's `partial`). [And if you try to do that, you will correctly get error CS0111.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEDMACADgQysGHAGwxQCYMBBLLACQHsBbCAWACgBvdgSHSpobMAFAEoMHAL7spbdn1z5CJcvzpNWnHn2prhYydKA==)

**Comment by Calebyang93** [comment]
> @Calebyang93 There is no such thing as "partial constructor" in C#. [C# only supports partial types and partial methods.](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)
> 
> That also means there is no way to have the same constructor more than once in a class (even if it's `partial`). [And if you try to do that, you will correctly get error CS0111.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEDMACADgQysGHAGwxQCYMBBLLACQHsBbCAWACgBvdgSHSpobMAFAEoMHAL7spbdn1z5CJcvzpNWnHn2prhYydKA==)

Noted. Thanks a lot for your help and clarification!

**Comment by BillWagner** [comment]
Thanks @svick for the helpful answers.

Closing as answered.

**Comment by jaider** [comment]
I was thinking the error CS0111 should not be an error for cases when using static and non-static method.
```
// CS0111.cs  
class A  
{  
   public void Test() { }  
   public static void Test(){}   // CS0111  
  
   public static void Main() {}  
}  
```
The user can call `A.Test()` (static) or `new A().Test();` (non static) and the compiler should know which one is referring to.

The problem will be if the call happens inside of the class A, then, the error CS0111 make sense... for example:
``` 
class A  
{
//...  
   public void DoSomethingWithTest()  
   {  
      Test(); // which one?
   }
}
```
