### ISSUE TITLE
Example does not compile in Visual Studio Community 2019RC

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11608]
@SrDobrais commented on [Mon Apr 01 2019](https://github.com/dotnet/docs.es-es/issues/121)

Aunque si compila en Visual Studio Community 2017

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a86f6ff1-21bf-44ad-f603-e311648929a4
* Version Independent ID: 9b08428b-beba-0f94-6635-73e26d0de446
* Content: [Palabra clave class: Referencia de C#](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/class)
* Content Source: [docs/csharp/language-reference/keywords/class.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team, 
this one seems to be related to this one: https://github.com/dotnet/docs/issues/11607

Rough translation:
_Although it does compile in Visual Studio Community 2017_

**Comment by mairaw** [comment]
@SrDobrais ¿Nos puede dar más información sobre el error que está recibiendo?

No puedo reproducir este problema.

**Comment by SrDobrais** [comment]
El día de hoy.
Al volver a compilar ya trabaja.
En ambos ejemplos.

El Error era, si mal no recuerdo, algo de que no encontraba System.algo excepción unhandled IO.algo
Lo siento no guardé el texto del error.

Parece que al reiniciar el ordenador PC algo se arregló, puede haber sido problema del Visual Studio.
Bueno en unas horas esto será historia.
Visual Studio 2019 "Ha llegado" Probaremos en cuanto se libere 14 h.

**Comment by mairaw** [comment]
Que bueno. Así que cerraré ambos problemas, pero háganos saber si tiene algún problema en el futuro.

Muchas gracias!
