### ISSUE TITLE
Example does not compile in Visual Studio Community 2019RC

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11607]
@SrDobrais commented on [Mon Apr 01 2019](https://github.com/dotnet/docs.es-es/issues/120)

Aunque si compila en Visual Studio Community 2017

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Clases: Guía de programación de C#](https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since it looks like the example is not working in newer versions

**Comment by mairaw** [comment]
@SrDobrais ¿Nos puede dar más información sobre el error que está recibiendo?

No puedo reproducir este problema.
