### ISSUE TITLE
Range Patterns?

### ISSUE THREAD

**Issue by antmdvs** [dotnet/docs#11618]
> The previous method doesn't use pattern matching. It's clearer using a familiar cascade of `if` statements

Will it be possible to use ranges in pattern matches? I think this is arguably just as readable:

```csharp
private static TimeBand GetTimeBand(DateTime timeOfToll) => timeOfToll.Hour switch
{
    6..9   => TimeBand.MorningRush,
    10..15 => TimeBand.Daytime,
    16..19 => TimeBand.EveningRush,
    _      => TimeBand.Overnight,
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc5c533-a9ca-cc70-af20-21308e819082
* Version Independent ID: ef6af5d2-b640-0feb-d9d3-7aae0ca92264
* Content: [Use pattern matching features to extend data types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/pattern-matching#feedback)
* Content Source: [docs/csharp/tutorials/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/pattern-matching.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
You could test properties on a `Range` object. But, the test you want to make is to see if an `int` (or `Index`) is in a `Range`. I couldn't come up with a way to do that.

Maybe either @MadsTorgersen or @gafter have a suggestion.

**Comment by gafter** [comment]
This is something we are considering for the future.  See https://github.com/dotnet/csharplang/issues/2115

**Comment by BillWagner** [comment]
Closing this. dotnet/csharplang#2115 is a better choice for this discussion.
