### ISSUE TITLE
can not build locally with docfx

### ISSUE THREAD

**Issue by xiaoyaocao83** [dotnet/docs#11619]
[build.log](https://github.com/dotnet/docs/files/3032330/build.log)

**Comment by mairaw** [comment]
@superyyrrzz can you help with this issue of building our docs with docfx locally?

**Comment by superyyrrzz** [comment]
@xiaoyaocao83 It is not supported. Although you can see `docfx.json` in this repository, it need some private templates and plugins to support local build, which community users cannot access.

**Comment by mairaw** [comment]
Thanks @superyyrrzz for your response. It's unfortunate that community members can't do local builds.
