### ISSUE TITLE
Always uses default printer

### ISSUE THREAD

**Issue by Slugsie** [dotnet/docs#11624]
The code as provided always uses the default printer. There needs to be a:

PrintDocument1.PrinterSettings = PrintDialog1.PrinterSettings

just before the PrintDocument1.Print() otherwise the selected printer will be ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177e6a84-f4da-0944-b6dc-1029ae9d0e32
* Version Independent ID: 44d8535a-72b8-aa0a-91a4-14516d50d11b
* Content: [How to: Choose the Printers Attached to a User's Computer in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-choose-the-printers-attached-to-user-computer-in-windows-forms#feedback)
* Content Source: [docs/framework/winforms/advanced/how-to-choose-the-printers-attached-to-user-computer-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-choose-the-printers-attached-to-user-computer-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Slugsie** [comment]
In fact the page description talks about printing a text file, yet the code draws a rectangle.

**Comment by mairaw** [comment]
Thanks for your feedback @Slugsie and apologies for the delay in getting this triaged. It's currently in our backlog but we accept contributions from the community to fix this.
