### ISSUE TITLE
Typo in example comment

### ISSUE THREAD

**Issue by jc1001** [dotnet/docs#11621]
There is a typo in the last example code block on the page:
// However, itdoes cause a run-time error. 
Should be:
// However, it does cause a run-time error. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f669fa6b-11b2-4b97-898d-025018e76cd5
* Version Independent ID: e1745bae-146e-ae73-2c17-a5e16eaa303f
* Content: [dynamic - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/dynamic)
* Content Source: [docs/csharp/language-reference/keywords/dynamic.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/dynamic.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @jc1001 

I've added it to our backlog to fix when we next update this content.  If you'd like, you could submit a PR to make the change. I've added the "up for grabs" label on this issue.

**Comment by mairaw** [comment]
This was fixed with PR https://github.com/dotnet/samples/pull/783.
