### ISSUE TITLE
Typo in introduction.

### ISSUE THREAD

**Issue by salmodesign** [dotnet/docs#11623]
"For example, asynchronous service operations can be calling synchronously" - change to "called".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd01b43-edcc-0f18-c17e-0e7780d08907
* Version Independent ID: 456c83f7-171b-6c61-d2a9-9d9b948178c9
* Content: [How to: Implement an Asynchronous Service Operation](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-implement-an-asynchronous-service-operation#feedback)
* Content Source: [docs/framework/wcf/how-to-implement-an-asynchronous-service-operation.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-implement-an-asynchronous-service-operation.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for letting us know @salmodesign. @Potapy4 has fixed this issue with PR #11658.
