### ISSUE TITLE
Hello.cs(1,7): error CS0116: 

### ISSUE THREAD

**Issue by Ashish2019New** [dotnet/docs#11629]
Please provide error-list all type in your first execution  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22951aaa-bfb8-f6e5-5d08-d9fd758bc689
* Version Independent ID: 214492ea-f78e-e1b2-5767-ec3cf32cc54a
* Content: [Hello World -- Your first program - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/hello-world-your-first-program#feedback)
* Content Source: [docs/csharp/programming-guide/inside-a-program/hello-world-your-first-program.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/hello-world-your-first-program.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Ashish2019New** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-message

**Comment by BillWagner** [comment]
Thanks for raising this concern @Ashish2019New 

We're not going to provide a single page with all the compiler errors. The possible errors number in the thousands. Instead, we've optimized for search: if you search on any compiler error code, the appropriate docs page will be in the first page of results.

Closing as by-design.
