### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by m-sterspace** [dotnet/docs#11632]
I know there's generally a lack of them everywhere on docs, but for articles about UI controls and designs it's really helpful to have images to go along with the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5aefa4-c278-82f8-0957-6c8da2488b75
* Version Independent ID: 426da6e8-7930-a1a6-6b64-b96b52c7f565
* Content: [ScrollViewer Styles and Templates](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/scrollviewer-styles-and-templates#feedback)
* Content Source: [docs/framework/wpf/controls/scrollviewer-styles-and-templates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/scrollviewer-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That's a good suggestion @mastjaso. I've added this to our backlog and our community contribution project.
