### ISSUE TITLE
Insufficient information to run command to add external alias

### ISSUE THREAD

**Issue by skylerberg** [dotnet/docs#11647]
The document says to use `/r:GridV1=grid.dll` at a command line. This left me wondering the following:

- What command line are we using here? E.g., powershell, cmd, something visual studio specific?
- /r looks like an parameter for a command, but what command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42871bc9-b130-8acf-11e1-bca2ac6c33f8
* Version Independent ID: fc5187e6-8cad-b6b9-d5b4-fa5d847bcda9
* Content: [extern alias - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias)
* Content Source: [docs/csharp/language-reference/keywords/extern-alias.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/extern-alias.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
First, to answer your questions:

> What command line are we using here? E.g., powershell, cmd, something visual studio specific?

It does not matter, all of the above should work, as long as you can access the command.

> /r looks like an parameter for a command, but what command?

`csc`, the C# compiler.

That being said, the documentation should definitely be clarified to explain that it's talking about `csc`. 

Also, since most people don't use `csc` directly, it should explain how to do the same thing from Visual Studio by editing .csproj.

**Comment by skylerberg** [comment]
@svick, Thanks for the quick response! I agree that instructions for editing a .csproj file would be most helpful.

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @skylerberg And for the helpful suggestion @svick 

We should also include how to do this via the `dotnet build` command.

**Comment by nokcode** [comment]
How to do this in .csproj? I'm in the dark here. I need some examples with code... Unfortunally I don't figured out how to do this yet.

@BillWagner, has some progress with it? Can I help? Thank you.
