### ISSUE TITLE
make it simple 

### ISSUE THREAD

**Issue by vscodewinodws** [dotnet/docs#11642]
all example in generics are using nested class and other code which is I think not required for explanation of generics can some one from docs team can try to make it simple 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10128e58-1d97-6569-1045-533c8c158e9f
* Version Independent ID: 594ab796-792f-e8be-84ec-c6d5f3670099
* Content: [Introduction to Generics - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/introduction-to-generics#feedback)
* Content Source: [docs/csharp/programming-guide/generics/introduction-to-generics.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/introduction-to-generics.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @jaymins93 

That's a great idea, and something we should add.  I've tentatively scheduled it for this quarter.
