### ISSUE TITLE
Broken link  

### ISSUE THREAD

**Issue by programeralex** [dotnet/docs#11640]
there is a broken link in 
[Visual Basic Breaking Changes in Visual Studio](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/breaking-changes-in-visual-studio)

the link of When is a non-breaking language fix breaking? has been broken

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89020865-95e5-e769-c677-a731523be4f8
* Version Independent ID: 69fba3d1-977b-01ff-9b50-6448b45554af
* Content: [Visual Basic Breaking Changes in Visual Studio](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/breaking-changes-in-visual-studio)
* Content Source: [docs/visual-basic/getting-started/breaking-changes-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/breaking-changes-in-visual-studio.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
I'm closing this one as a duplicate of #9807. We're tracking all blogs broken links under that task.

Given there's a huge migration going on at the moment, we're still trying to determine which blogs will die and which ones are being redirected.
