### ISSUE TITLE
dependencies of .NET 4.7.2 under 1803 versus 1809

### ISSUE THREAD

**Issue by td47** [dotnet/docs#11657]
Please reconcile this info against the 1809 update list for .net 4.7.2 at:
https://support.microsoft.com/en-au/help/4489894
NOTE: The above link shows ONLY .net updates for  Windows 10 1809 and Server 2019, I CANNOT find any equivalent update KB documentaion for Windows 10 1803. If you have a link to cross-reference those (if available) that would be good/useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @td47 and apologies for the delay in getting this triaged.

@NKarnam15 can you please validate this feedback?

@td47 can you also give more information about what you're looking for? That KB doesn't seem related to .NET but I might be missing something.

**Comment by td47** [comment]
Hello, sorry about the incorrect patch reference, I suspect that I cut/paste the incorrect KB URL. 
I think it should have been this URL:
[https://support.microsoft.com/en-us/help/4466961/net-framework-update-history-for-windows-10-october-2018-update-and-wi](url) 
The issue was that one of my systems was stuck on Windows 10 1803, and I wanted to find the equivalent of the 1809 updates for .NET 4.7.2 (possibly KB4514366). However, now that I have moved on to 1809 and beyond now (1909 on all systems) I no longer have to worry about the .NET patches and levels, it seems that the Windows Updates correctly updates it automatically now OK. Earlier level users who are still on 1803 MIGHT still have issues trying to update .NET to secure levels though.

**Comment by td47** [comment]
Hi,

Sorry about the delay, have updated the GITHUB item for this. I had a typo (wrong URL) in the original post

 

Regards, Tony Davis

**Comment by td47** [comment]
Hello again, it seems that I messed up the URL (again)! The string is correct, but it seems to NOT have created it as a URL?  Hopefully this is correct:
[](https://support.microsoft.com/en-us/help/4466961/net-framework-update-history-for-windows-10-october-2018-update-and-wi)

**Comment by td47** [comment]
FYI: related to the reported issue, it seems that the "History of Cumulative Updates for .NET Framework for Windows 10" versions 1903 and 1909 referenced below, have NOT been updated since May last year, and yet I regularly get updates way after that date. It sees that the documents below have just been left as "place-holders" and never been updated to actually reflect the available updates.

https://support.microsoft.com/en-au/help/4502507/net-framework-update-history-for-windows-10-version-1903

https://support.microsoft.com/en-au/help/4522761/net-framework-update-history-for-windows-10-version-1909
