### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GregWoods** [dotnet/docs#11659]
If I follow the instructions as-is, I get 404 error
If I use VS2017 to set up a WCF Service project, and then follow the instructions, I get a 405 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0822f57-ffba-c196-a40b-2b661b0a0f8f
* Version Independent ID: 2499a5be-0643-bf0b-023e-6e4317637cd1
* Content: [How to: Host a WCF Service in IIS](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis#feedback)
* Content Source: [docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for your feedback @GregWoods and apologies for the delay on getting this triaged. @HongGit please review this feedback for a WCF article.
