### ISSUE TITLE
Title rendering is incorrect

### ISSUE THREAD

**Issue by gafter** [dotnet/docs#11650]
See https://github.com/dotnet/csharplang/issues/2386#issuecomment-479661574

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db525e8-2dfc-c8f9-a965-cccfb9e747ef
* Version Independent ID: 7bb03d89-be9a-9c28-3fa7-3f3084029346
* Content: [Indexing fixed fields should not require pinning regardless of the movable/unmovable context. - C# 7.3 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/indexing-movable-fixed-fields)
* Content Source: [proposals/csharp-7.3/indexing-movable-fixed-fields.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/indexing-movable-fixed-fields.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@sudeepku I think we're back where we started: This is a rendering error in the site, not a content error.

I agree with @gafter that MicrosoftDocs/feedback#1321 should be reopened.

**Comment by BillWagner** [comment]
Ping @dend

**Comment by mairaw** [comment]
@adkinn filed an internal bug to track this work: 

https://ceapex.visualstudio.com/Engineering/_workitems/edit/79880

**Comment by mairaw** [comment]
This has been fixed. Closing.
