### ISSUE TITLE
SqlCommand syntax doesn't match inheritance

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#11665]
**Issue description**

The .NET Core 2.2 docs for [SqlCommand](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand?view=netcore-2.2) show this syntax and inheritance:

``` c#
public sealed class SqlCommand : System.Data.Common.DbCommand, ICloneable, IDisposable
```
> Inheritance Object -> MarshalByRefObject -> Component -> SqlCommand
> Implements IDbCommand, ICloneable, IDisposable

They don't match. The syntax says that `DbCommand` is the base class, but the inheritance says that `Component` is the base class. Also, the implements line has an extra `IDbCommand` that's not in the syntax.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core
- [ ] .NET Framework - not checked
- [ ] .NET Standard - not checked

**Comment by mairaw** [comment]
@joelmartinez can you investigate this one?

It seems that at least part of the problem here is related to https://github.com/MicrosoftDocs/feedback/issues/616.

**Comment by joelmartinez** [comment]
@mairaw yes, you are correct … as with that issue, the metadata here contains the correct information:

```xml
  <Base>
    <BaseTypeName>System.Data.Common.DbCommand</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netframework-1.1">System.ComponentModel.Component</BaseTypeName>
  </Base>
```

This should be resolved with the SDP work … though it may take until phase 2 to fully reflect the differences in the interface implementations. However, from a feature support perspective, this will be covered and handled either way.

**Comment by mairaw** [comment]
Ok, thanks for confirming @joelmartinez. So closing this as duplicate since we already have an issue tracking this work,
