### ISSUE TITLE
Better startup debugging solution

### ISSUE THREAD

**Issue by nathankidd** [dotnet/docs#11661]
A much better OnStart debugging solution is to use gflags plus cdb -&gt; pipe -&gt; WinDbg.  https://bugslasher.net/2010/10/14/how-to-debug-a-windows-service/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bae17e7-e055-a81d-6297-da79e5b099a2
* Version Independent ID: fbbe5717-4d68-7e55-381e-397d9503e1cc
* Content: [How to: Debug Windows Service Applications](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-debug-windows-service-applications#feedback)
* Content Source: [docs/framework/windows-services/how-to-debug-windows-service-applications.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/how-to-debug-windows-service-applications.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for the suggestion. At this point we're not going to update the article. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
