### ISSUE TITLE
Possible to multitarget netstandard versions?

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#11668]
In particular, I want to target ``netstandard1.6`` and ``netstandard2.0`` if possible. However, my attempts to do so have been met with:

> Error	NETSDK1005	Assets file 'path\to\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.	GitDotNet C:\Program Files\dotnet\sdk\2.1.505\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
If you run `dotnet restore` does it fix your problem?

**Comment by mwpowellhtx** [comment]
The problem is, ``dotnet restore`` runs for one, but tries and fails to run for the second. This is baked into the ``MSBuild`` targets, is it not?

**Comment by Thraka** [comment]
Hrm, I see what you mean. I was thinking that you changed the target from 1.6 to 2.0, not targeting both.

Are you using the `TargetFrameworks` setting? or just the non-plural setting of `TargetFramework`?

**Comment by mwpowellhtx** [comment]
@Thraka Yes, as I understand it, ``TargetFrameworks`` is how you multi-target, no? Unless there is some other protocol I am unaware of (which is possible). Thanks!

**Comment by Thraka** [comment]
You are right. I changed my last post because I tested with `TargetFrameworks` and it didn't work either. So i knew you were doing it correctly 😃

**Comment by Thraka** [comment]
@peterhuene Perhaps you know?

**Comment by Thraka** [comment]
Pinged peter in email...

**Comment by peterhuene** [comment]
Sorry I missed this earlier!

What are the repro steps here?

I'm able to create a new classlib project, change to use `<TargetFrameworks>netstandard1.6;netstandard2.0</TargetFrameworks>` and have `dotnet build` successfully produce both `netcoreapp1.6` and `netcoreapp2.0` output.
