### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by flemingm** [dotnet/docs#11672]
Hosting a Windows Forms Control in WPF by Using XAML Sample

https://go.microsoft.com/fwlink/?LinkID=160000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c867d576-eb36-2ffe-d70e-392d2d76a19b
* Version Independent ID: cc6b28a6-9d9d-64a3-5e1a-5bc308b38e45
* Content: [Walkthrough: Hosting a Windows Forms Control in WPF by Using XAML](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml#feedback)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @flemingm. @SimonCropp took care of that in PR #11673
