### ISSUE TITLE
Is this page out of date?

### ISSUE THREAD

**Issue by AlexSapple** [dotnet/docs#11682]
Hi, 

The example in this page appears to be based on a a previous version of ML.Net (0.10) whereas current at time of writing is (0.11). The reader no longer appears to have a Read method and the DataKind enum appears to differ. 
thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72764a44-6802-52cc-0fde-4e77ea023ef1
* Version Independent ID: 4744f614-da6b-a15c-aebf-8a457f5549c8
* Content: [Load data from a text file for machine learning processing - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-from-text-file-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/load-data-from-text-file-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-data-from-text-file-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by bsoman3** [comment]
+1
.Load works instead of .Read.
Assuming R4->double, TX->String etc.

Msft alias: bhsoman

**Comment by JRAlexander** [comment]
Hi, @alexsapple, this was just updated for v 1.0.0 here: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net

**Comment by JRAlexander** [comment]
Closing as it's now resolved.
