### ISSUE TITLE
Interfaces may employ multiple inheritance. Fantastic design choice. No source to prove my words... LOL

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#11681]
Fantastic everything, good bye.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#feedback)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by dmarinescu** [comment]
Anders: another ugly thing (handy for compiler boys and girls but otherwise semantically divergent) is the use of new for value types.
Anders: and you know that the lack of all evil (gc & co) is the inability to chose between stack and heap allocation for all types. you did it in Delphi too (no wonder is extinct).

**Comment by svick** [comment]
> Anyway, it is not beneficial (these days) to twist well known terms. Inheritance means implementation inheritance (the only inheritance there is).

Can you provide any source for that claim?

Anyway, this is not the right place to complain about design choices of C#. If you want to discuss how to improve C# going forward (while keeping in mind that past choices are incredibly unlikely to be reversed, to maintain backwards compatibility), a better place would be [the csharplang repo](https://github.com/dotnet/csharplang/).

**Comment by dmarinescu** [comment]
>"can you provide any source for that claim?"
by all means, remove all my comments, you do not even understand what i was
talking about, thanks and only the best

**Comment by dmarinescu** [comment]
> > Anyway, it is not beneficial (these days) to twist well known terms. Inheritance means implementation inheritance (the only inheritance there is).
> 
> Can you provide any source for that claim?

Good One! 

> Anyway, this is not the right place to complain about design choices of C#. If you want to discuss how to improve C# going forward (while keeping in mind that past choices are incredibly unlikely to be reversed, to maintain backwards compatibility), a better place would be [the csharplang repo](https://github.com/dotnet/csharplang/).

You are right, my bad, thanks!

**Comment by Thraka** [comment]
Locking/marking this issue. While a valid complaint, the wrong venue. Considering the user edited the original comment and then deleted their user account, I will mark this as code-of-conduct.
