### ISSUE TITLE
Possibly incorrect comment in code sample

### ISSUE THREAD

**Issue by akeeton** [dotnet/docs#11686]
Is this comment in the Remarks code sample correct?

    // This object expression implements multiple interfaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db76e619-9fa5-bed5-8115-f8e95759623d
* Version Independent ID: f82139b7-e0b1-4dd8-f436-921f992af2f7
* Content: [Object Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/object-expressions#remarks)
* Content Source: [docs/fsharp/language-reference/object-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/object-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, I agree thios is confusing. I'll just remove that line.
