### ISSUE TITLE
Example for Members on DUs

### ISSUE THREAD

**Issue by TclasenITVT** [dotnet/docs#11683]
The Syntaxs shows that it is possible to add members to the DU but there is no code example for this on this page. It would be nice if it could be showcased here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6020749e-d91e-8a1b-5366-25b212baa31d
* Version Independent ID: 0f28f508-dc0f-c272-383e-ec768759fe16
* Content: [Discriminated Unions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/discriminated-unions)
* Content Source: [docs/fsharp/language-reference/discriminated-unions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/discriminated-unions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@TclasenITVT What kind of example would you be looking for? Property, method, etc.? I'll also happily accept a PR and work with you on it.

**Comment by TclasenITVT** [comment]
Yes I was thinking about an example that demonstrates the usefulness of the implementation of interfaces, methods and propertys on DUs. 
For interfaces I expierienced that the Library Argu has a real usage of interfaces on DU -> IArgParserTemplate
```
type PCCLIArgs =
    | Status of ParseResults<StatusArguments>
    |  Quit
with
    member this.Name = "PC CLI Arguments"

    member this.Parse (value:string) = 
        match value.ToUpper() with
        | "STATUS" -> Status
        | "QUIT" -> Quit

    interface IArgParserTemplate with
        member s.Usage =
            match s with
            | Status _ -> "Display the status of a PC!"
            | Quit -> "Exit the Personal Computer Manager!"
```
This example is from a personal project of mine and does not 100% work -> the this.Parse member in the STATUS case is missing its `ParseResults<StatusArguments>`.

**Comment by cartermp** [comment]
@TclasenITVT Thanks. I'm not entirely sold on doing an example quite like that, just because it's a bit complicated. But I did modify the document to add a DU that extends the `Shape` type to define a property and satisfy an interface. Hopefully that works!
