### ISSUE TITLE
Help needed in getting health check for smtp and memory using Asp.NetCore.HealthChecks.UI

### ISSUE THREAD

**Issue by RaminderRandhawa91** [dotnet/docs#11695]
Can you please provide example for displaying health check for smtp and memory using Asp.NetCore.HealthChecks.UI

**Comment by mairaw** [comment]
@Rick-Anderson would this belong in your repo?

**Comment by Rick-Anderson** [comment]
@RaminderRandhawa91  see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks
If that doesn't meet your needs, open an issue on that page.
