### ISSUE TITLE
Non working links

### ISSUE THREAD

**Issue by stjepan** [dotnet/docs#11705]
codebetter.com has been down for some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d83855-4370-90e8-024a-12c5ac8220e9
* Version Independent ID: 01be3db1-4a00-c8f2-aa59-59656f206b93
* Content: [Applying CQRS and CQS approaches in a DDD microservice in eShopOnContainers](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for letting us know @stjepan. 
@mvelosop @CESARDELATORRE We have three articles linking to that site. Ok to remove?

**Comment by mvelosop** [comment]
Hi @stjepan, thanks for the heads up, just tried contacting the author, let's wait for a few days.

**Comment by mvelosop** [comment]
Hi @stjepan, @mairaw, I got to chat with Greg Young and he didn't supplied a replacement for those articles. 

However, the one from https://cqrs.wordpress.com/ contains most of the material, so I'm updating this article now.
