### ISSUE TITLE
What about Azure?

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#11708]
Frustratingly there is no mention of publishing to a feed setup in Azure. Nor does anything in this article tell us HOW to actually perform a publish. I've spent hours trying to find out if I can publish a nuget package from inside Visual Studio 2019, I was asked this question a few days ago and I still have no answer, for all I know we must fiddle around with nuget command line stuff in power shell. Is there really - after all these years - no support in VS for right clicking a project and choosing "Publish to feed"???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e51d820-1f85-192c-9169-cd965581b4f1
* Version Independent ID: 9e7ea8c7-ae47-eda8-4ba0-d5f59a3ade3c
* Content: [Publishing a NuGet package](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/publish-nuget-package)
* Content Source: [docs/standard/library-guidance/publish-nuget-package.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/publish-nuget-package.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
I don't think this is the focus of this article @Korporal but tagging a few folks that might be able to help answer your question about publishing NuGet packages from VS 
@karann-msft @rrelyea

**Comment by karann-msft** [comment]
@Korporal unfortunately, there isn't a UI way to publish a nuget packages from VS today. I saw that you created a similar [issue in nuget docs](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1389) and since it is product feedback, I moved it to the product repo - [NuGet/Home/issues/7975](https://github.com/NuGet/Home/issues/7975).

**Comment by mairaw** [comment]
Thank you @karann-msft. Closing this one then.
