### ISSUE TITLE
ListViewItem(System.Windows.Controls) documentation lists all object elements under 'Constructors'

### ISSUE THREAD

**Issue by schulmaster** [dotnet/docs#11701]
This ListViewItem class documentation:
 https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.listviewitem?view=netframework-4.7.2 ...
has **ALL constructors, methods, and properties** under the single subtree heading of **'Constructors'**. The reference documentation for the analogous object in the Windows.Forms namespace(https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem?view=netframework-4.7.2) does NOT have this issue, nor does any other class reference I have yet encountered. As it stands, the Windows.Controls ListViewItem seems to have over 200 constructors, no methods, and no properties, while in reality, all categories are simply listed under Constructors. As of 4.7.2, ListViewItem only has a single default constructor, but also has many important methods and properties that should be categorized appropriately. 

To reiterate, it is only the class defined in System.Windows.Controls with this issue, NOT System.Windows.Forms.

edit by @mairaw: fix urls

**Comment by mairaw** [comment]
That's weird indeed @schulmaster. Thanks for letting us know. I'm following up with our engineer team.

**Comment by mairaw** [comment]
Our engineering team has pushed a fix today. Thanks for reporting this!

**Comment by schulmaster** [comment]
@mairaw No problem! the MSDN .NET docs are one of the best references since the manpages.

**Comment by mairaw** [comment]
Thank you for the kind words @schulmaster!
