### ISSUE TITLE
Unnecessary RowDefinitions in the "Data Templating" example?

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#11706]
"Data Templating" section -&gt; Example (XAML).

There are four RowDefinitions for the Grid while actually only first two are in use (except Grid.RowSpan="4" for the Polygon object, but this has no effect as the last two rows are empty).

I've tried removing two RowDefinitions and setting Grid.RowSpan="2" for the Polygon, the result is the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data Binding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview#feedback)
* Content Source: [docs/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-binding-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Decided this is not a critical bug and leaving it does not hurt the documentation in any way. I'm going to close this. Thanks for the suggestion though.
