### ISSUE TITLE
4.8 is missing

### ISSUE THREAD

**Issue by Namek** [dotnet/docs#11714]
The Release value found in the registry is 528040 for the Version 4.8.03752. I'm guessing the lower boundary for 4.8 in general would be 520000?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
We’re updating the articles for 4.8 now.
According to https://github.com/dotnet/samples/pull/789/files, the value will be 528049.

**Comment by rpetrusha** [comment]
The lower boundary will be 528040.
