### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by suBOTai3** [dotnet/docs#11715]
This page does not details which Import statements (Using System.Windows) is required for DependencyProperties to work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498209ff-67ff-d566-fa28-e0d64f8501be
* Version Independent ID: cd07ee35-fe18-8089-aede-5c1e4fac8880
* Content: [How to: Implement a Dependency Property](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-implement-a-dependency-property#feedback)
* Content Source: [docs/framework/wpf/advanced/how-to-implement-a-dependency-property.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-implement-a-dependency-property.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @suBOTai3. We've added this request to our backlog.
