### ISSUE TITLE
missing code snippet from "what's new in C#7"

### ISSUE THREAD

**Issue by SteveCarrollMSFT** [dotnet/docs#11710]
**Issue description**

There's a missing code snippet in the 'Ref locals and returns' section after the words: 
["You can declare the return value as a ref and modify that value in the matrix, as shown in the following code:"](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#ref-locals-and-returns)

**Comment by mairaw** [comment]
Thanks for letting us know @SteveCarrollMSFT. @Potapy4 has fixed this issue with PR #11722.
