### ISSUE TITLE
URL for info on configuring firewall Exception is not working

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#11717]
On configuring the firewall exception, the provided url is not working: https://go.microsoft.com/fwlink/?LinkId=239961

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9096dc31-bc97-a413-880f-962603bed316
* Version Independent ID: 68c92a65-812f-f665-7df2-24e1e1e65048
* Content: [Configuring HTTP and HTTPS](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-http-and-https)
* Content Source: [docs/framework/wcf/feature-details/configuring-http-and-https.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/configuring-http-and-https.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for letting us know @Bartolomeus-649. I've opened #11732 to fix this and also update the topic a bit. @Lxiamail please review that PR.
