### ISSUE TITLE
Mention the PATH where `dotnet` is installed.

### ISSUE THREAD

**Issue by bbaassssiiee** [dotnet/docs#11712]
I manage my $PATH, so maybe that is why I see "-bash: dotnet: command not found". Docs should provide info about the implicit path used.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core Guide](https://docs.microsoft.com/en-gb/dotnet/core/#feedback)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs/blob/master/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by bbaassssiiee** [comment]
I found some wisdom: https://wilsonmar.github.io/powershell-on-mac/

**Comment by Thraka** [comment]
Hi! 

I don't think this article is the appropriate one to document this. However, I think the root Getting Started article would be better. Would you like me to move your issue to that article?

**Comment by mairaw** [comment]
If we document this, I'd suggest adding this to the main dotnet topic instead: https://docs.microsoft.com/en-gb/dotnet/core/tools/dotnet

This is not a Getting started info.

**Comment by grupoKfk** [comment]
I agree half part with your comment, but it's necessary to refer where we can found more information about installation configs

**Comment by Thraka** [comment]
I think we can close this. The new install section has instructions for linux which talks about the path.
