### ISSUE TITLE
syntax error in Pattern matching example

### ISSUE THREAD

**Issue by mahdi-ataollahi** [dotnet/docs#11711]
In Pattern matching example code the case `null` is incorrect. It should be `case null:` not a standalone `null:`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [What's New in C# 7.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#feedback)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is fixed in #11754
