### ISSUE TITLE
404 Result for Algorithms` links

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11727]
@DmitriyBolgarov commented on [Sat Apr 06 2019](https://github.com/dotnet/docs.ru-ru/issues/190)

Good Day. Is it ok, that most of the links for Algorighms redirect me to 404 page? Could anybody please make them innactive if not exists yet.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Задачи машинного обучения. Использование ML.NET](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/resources/tasks#feedback)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hi team, 
the user is reporting these links lead to 404 pages.
![imagen](https://user-images.githubusercontent.com/26746247/55747712-3ca78200-5a13-11e9-9922-38533e466447.png)

Since it also repros in the en-us page I'm moving it here

Kind regards

**Comment by XamlBrewer** [comment]
On that same page the link to the RandomTrainer in the Binary classification Learners section may be removed, since that class was removed with Pull Request #2849 (https://github.com/dotnet/machinelearning/pull/2849).
