### ISSUE TITLE
"C# for Java developers" and similar articles?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#11720]
I just read [this discussion on Reddit](https://www.reddit.com/r/csharp/comments/bamw6g/how_to_learn_c_syntax_and_features_fast_as_a/) about learning C# for a developer who already knows other programming languages and realized there doesn't seem to be anything like that in the official documentation.

Somebody in that discussion linked to [the cheat sheet "C# for Java Developers"](https://download.microsoft.com/download/D/E/E/DEE91FC0-7AA9-4F6E-9FFA-8658AA0FA080/CSharp%20for%20Java%20Developers%20-%20Cheat%20Sheet.pdf), but it hasn't been updated since 2010 and both languages have changed significantly since then.

Would it be useful to have an article targeted specifically at developers of each popular programming language (say, Java, JavaScript, C++, Python), explaining the most prominent differences between those languages and C#?

**Comment by mairaw** [comment]
@BillWagner I tagged this as a doc-idea for C#. Please take a look.

**Comment by BillWagner** [comment]
I'm tagging this for discussion as well. 

We've generally avoided 1:1 comparisons with other languages in docs. We have made some very generic comparisons with "other object oriented languages" or "other C-based language syntax".

Is there value in direct comparisons? If so, vote 👍 on this comment. If not, vote 👎 on this comment. If there is value, we'll discuss which languages should be covered.

/cc @MadsTorgersen @jcouv @jaredpar @rowanmiller @BethMassi
