### ISSUE TITLE
Binder Class Methods View Code link in API Reference Link pointing wrong line

### ISSUE THREAD

**Issue by ThePiranha** [dotnet/docs#1173]
[Binder Class Methods](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder) under [Microsoft.CSharp.RuntimeBinder Namespace](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder#Microsoft_CSharp_RuntimeBinder), all method's view code link pointing same line, [Line 16](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L16). Which should be different line for each method.

[BinaryOperation(CSharpBinderFlags, Linq.Expressions.ExpressionType, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_BinaryOperation_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Linq_Expressions_ExpressionType_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 29](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L29)

[Convert(CSharpBinderFlags, Type, Type)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_Convert_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Type_System_Type_) is [Line 57](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L57)

[GetIndex(CSharpBinderFlags, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_GetIndex_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 83](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L16)

[GetMember(CSharpBinderFlags, String, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_GetMember_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_String_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 101](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L16)

[Invoke(CSharpBinderFlags, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_Invoke_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 120](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L120)

[InvokeConstructor(CSharpBinderFlags, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_InvokeConstructor_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 184](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L184)

[InvokeMember(CSharpBinderFlags, String, IEnumerable<Type>, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_InvokeMember_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_String_System_Collections_Generic_IEnumerable_System_Type__System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 147](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L147)

[IsEvent(CSharpBinderFlags, String, Type)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_IsEvent_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_String_System_Type_) is [Line 201](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L201)

[SetIndex(CSharpBinderFlags, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_SetIndex_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 218](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L218)

[SetMember(CSharpBinderFlags, String, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_SetMember_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_String_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 238](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L238)

[UnaryOperation(CSharpBinderFlags, Linq.Expressions.ExpressionType, Type, IEnumerable<CSharpArgumentInfo>)](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder_UnaryOperation_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_System_Linq_Expressions_ExpressionType_System_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo__) is [Line 259](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L259)

**Comment by svick** [comment]
As far as I can tell, type members don't have their own "View Code" link, there is just one link for the whole type.

I don't think the class "View Code" link should change when you're scrolling through the article (at least I think that's what you're suggesting). But maybe a separate "View Link" button for each member could make sense.

**Comment by mairaw** [comment]
Currently there's only the button for the entire class, not for the individual members as @svick said. 

/cc @DuncanmaMSFT @chenkennt 

@dend would you like people to start submitting these kind of site comments to the UserVoice site instead? You can find the ones submitted here by looking at the [external](https://github.com/dotnet/core-docs/labels/external) tags.I'd just have to change our contributing guide to point to the UV URL.

**Comment by mairaw** [comment]
We no longer have a View Code button for API reference docs, so closing this one.
