### ISSUE TITLE
Is the Information outdated now?

### ISSUE THREAD

**Issue by asloppyone** [dotnet/docs#11745]
I tested on my pc and find out that I can use a virtual Event in my base class ,and make the derived class to 
override it.Thus the correct result was yielded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48effe00-bf69-be72-bb9b-b343702de37b
* Version Independent ID: bd6b5366-556a-76e6-4ccd-e06ddaff1cd1
* Content: [How to: Raise Base Class Events in Derived Classes - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-raise-base-class-events-in-derived-classes)
* Content Source: [docs/csharp/programming-guide/events/how-to-raise-base-class-events-in-derived-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-raise-base-class-events-in-derived-classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by KalleOlaviNiemitalo** [comment]
The advice is not outdated. If a field-like event overrides a virtual event, then the derived class can raise the event, but the base class most likely cannot.

Consider the following sample:

```C#
using System;

namespace PR11745
{
    class Program
    {
        static void Main()
        {
            var obj = new Derived();
            obj.Event += (source, e) => Console.WriteLine("Event handler invoked.");
            obj.Demo1();
            obj.Demo2();
        }
    }

    class Base
    {
        public virtual event EventHandler<EventArgs> Event;

        public void Demo1()
        {
            Console.WriteLine("Base.Demo1 is raising Event.");
            this.Event?.Invoke(this, EventArgs.Empty);
            Console.WriteLine("Base.Demo1 finished.");
        }
    }

    class Derived : Base
    {
        public override event EventHandler<EventArgs> Event;

        public void Demo2()
        {
            Console.WriteLine("Derived.Demo2 is raising Event.");
            this.Event?.Invoke(this, EventArgs.Empty);
            Console.WriteLine("Derived.Demo2 finished.");
        }
    }
}
```

The output is:

```
Base.Demo1 is raising Event.
Base.Demo1 finished.
Derived.Demo2 is raising Event.
Event handler invoked.
Derived.Demo2 finished.
```

That is, the event handler in Main was not called when Base.Demo1 raised the event.

You can fix that by adding a method that raises the event, and using that instead of overriding the event:

```C#
using System;

namespace PR11745
{
    class Program
    {
        static void Main()
        {
            var obj = new Derived();
            obj.Event += (source, e) => Console.WriteLine("Event handler invoked.");
            obj.Demo1();
            obj.Demo2();
        }
    }

    class Base
    {
        public event EventHandler<EventArgs> Event;

        protected void RaiseEvent(EventArgs e)
        {
            this.Event?.Invoke(this, e);
        }

        public void Demo1()
        {
            Console.WriteLine("Base.Demo1 is raising Event.");
            this.RaiseEvent(EventArgs.Empty);
            Console.WriteLine("Base.Demo1 finished.");
        }
    }

    class Derived : Base
    {
        public void Demo2()
        {
            Console.WriteLine("Derived.Demo2 is raising Event.");
            this.RaiseEvent(EventArgs.Empty);
            Console.WriteLine("Derived.Demo2 finished.");
        }
    }
}
```

The output then is:

```
Base.Demo1 is raising Event.
Event handler invoked.
Base.Demo1 finished.
Derived.Demo2 is raising Event.
Event handler invoked.
Derived.Demo2 finished.
```

**Comment by BillWagner** [comment]
@KalleOlaviNiemitalo  Thanks for providing the answer to @asloppyone 's question.

I'll close this as an answered question.
