### ISSUE TITLE
Could the author add more details about BeginInvoke() and Invoke() methods .

### ISSUE THREAD

**Issue by asloppyone** [dotnet/docs#11740]
I couldn't find anything about the methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcd91a4-603a-feb9-cff2-94f1985417fc
* Version Independent ID: a86cde90-1eba-e1d5-2b42-2a3cd37f5499
* Content: [System.Delegate and the `delegate` keyword](https://docs.microsoft.com/en-us/dotnet/csharp/delegate-class)
* Content Source: [docs/csharp/delegate-class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by asloppyone** [comment]
Oh ,I just found them in"Calling Synchronous Methods Asynchronously".
No problems anymore.

**Comment by mairaw** [comment]
Thanks for letting us know @asloppyone. Closing the issue then.
