### ISSUE TITLE
Right-hand navigation now blocks content

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1175]
https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/query-expressions#comparison-of-transact-sql-and-f-query-expressions

<img width="796" alt="screen shot 2016-10-25 at 1 57 42 pm" src="https://cloud.githubusercontent.com/assets/6309070/19704067/24bd1c64-9abb-11e6-9c56-9c347c421421.png">

This is using latest Safari on macOS.

cc @DuncanmaMSFT

**Comment by BillWagner** [comment]
@cartermp I looked at this today, and I think you can close it. Do you want to verify?

**Comment by svick** [comment]
I think this still doesn't work well:

![](https://user-images.githubusercontent.com/287848/28339084-3b1ed7be-6c0b-11e7-8f70-cb050dbb990a.png)

There doesn't seem to be any way to access the content that's too wide.

**Comment by mairaw** [comment]
Moved issue to https://github.com/MicrosoftDocs/feedback/issues/227

**Comment by mairaw** [comment]
I'm reopening this issue. I think there's no way for the platform to handle such a wide content. So it might be better to rewrite on a different way @cartermp to address the issue.

**Comment by IEvangelist** [comment]
Recommended fix: instead of table, use new lines between code variants.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
