### ISSUE TITLE
Obsolete recommendation using WebRequest insted of HttpClient

### ISSUE THREAD

**Issue by schuelter** [dotnet/docs#11759]
WebRequest does not seems to be the recommended way of making web requests as can be seen in the REMARKS section https://docs.microsoft.com/en-us/dotnet/api/system.net.webreques, and https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be894d3-c542-1aa6-5d4a-9e1707069799
* Version Independent ID: b73a1104-2223-b28d-5ad6-3c05e6ec81e5
* Content: [Best Practices for System.Net Classes](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/best-practices-for-system-net-classes)
* Content Source: [docs/framework/network-programming/best-practices-for-system-net-classes.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/best-practices-for-system-net-classes.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @schuelter. @davidsh @karelz can you comment on this? I think it would be good to review this article to see if the best practices are still up to date.

**Comment by davidsh** [comment]
@scalablecory

**Comment by gewarren** [comment]
I'm going to make a small update to not recommend using WebRequest.

**Comment by gewarren** [comment]
@BillWagner I would have expected this issue to be marked as "Done" once the linked PR was merged, but it remained as "To do". Do you think that's because project was already closed?

**Comment by BillWagner** [comment]
> @BillWagner I would have expected this issue to be marked as "Done" once the linked PR was merged, but it remained as "To do". Do you think that's because project was already closed?

Yes. closing the project stops all automation. (My mistake. I must have had a filter on the tasks when I looked at the project to see if it was ready to close.)
