### ISSUE TITLE
Referenced page doesn't contain claimed content RE generic type member references

### ISSUE THREAD

**Issue by p--b** [dotnet/docs#11768]
This page states:
```
For more information on how to create a cref reference to a generic type, see <see>.
```

The linked page on `<see>` does not contain any information on how to create a cref reference to a generic type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6875be4b-b827-3d35-329a-be075fc98576
* Version Independent ID: ad0013b6-a77d-7072-10d2-dd505d154a2b
* Content: [&lt;exception&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/exception#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/exception.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/exception.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hi. Thank you for pointing that out. In that page I was let to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/cref-attribute which led me to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file and that contains the answer. I'll update the page to point to that.

Search https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file for generic and you'll find it 😄
