### ISSUE TITLE
References needed for code

### ISSUE THREAD

**Issue by sjboege** [dotnet/docs#11763]
I added PresentationCore to references and was then able to add 

using System.Windows.Media.Imaging;

But Visual Studio doesn't like the line 

Image myImage = new Image();

The error message is CS0144	Cannot create an instance of the abstract class or interface 'Image'

How can I resolve this?	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3170a4cb-5b5d-0709-710d-e6ea48787d09
* Version Independent ID: 5d1fcc07-6fa8-fb0b-2728-9f32aa06e578
* Content: [How to: Encode and Decode a WDP Image](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-wdp-image#feedback)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-wdp-image.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-wdp-image.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
You can see the entire sample at https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Wpf/WdpBitmapDecoderEncoder/CSharp/WDPEncoderDecoder.cs. See if that helps @sjboege!
