### ISSUE TITLE
Instruction to change the line in App.config is not clear

### ISSUE THREAD

**Issue by hinho** [dotnet/docs#11767]
In the section "Edit App.config" there are line numbers that should be changed (Like Change line 14, Change line 17, etc.) . But when I created my wcf lib like described in this tutorial I have these parts of code on different lines.
I suggest to change instruction based on section names better than line numbers (for example something like: In section "system.serviceModel - services" change service name to &lt;service name="GettingStartedLib.CalculatorService"&gt;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd7ff99-1ecd-5c6f-bf75-a5a777414d76
* Version Independent ID: 1b7f988f-92a0-ee09-7a0a-4d81ba918ac8
* Content: [Tutorial: Implement a Windows Communication Foundation service contract](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-implement-a-wcf-contract#feedback)
* Content Source: [docs/framework/wcf/how-to-implement-a-wcf-contract.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-implement-a-wcf-contract.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for your feedback @hinho and apologies for the delay in getting this triaged.
@HongGit can you please look at this feedback for one of the WCF articles?
