### ISSUE TITLE
Adding null delegates to dictionary costs more memory than field-like events would

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#11770]
The sample initializes the dictionary with null delegates as values:

```C#
    public PropertyEventsSample()
    {
        handlers = new Dictionary<string, Delegate>
        {
            [Event1Key] = null,
            [Event2Key] = null
        };
    }
```

This means the dictionary will always have an entry for each event, even if no event handlers are ever added. These entries cost even more memory than field-like events would, because each entry also keeps track of the key, hash code, and next entry in the chain. It is not useful in the situation claimed here:

> This is only useful if a type has many events, but you expect that most of the events will not be subscribed to.

To be actually useful, the entries would have to be allocated on demand, like `System.ComponentModel.EventHandlerList` does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2cb228-430f-43a7-4447-85d21d2de420
* Version Independent ID: 2af9e215-97f2-fb66-1090-591e83fbda92
* Content: [How to: use a dictionary to store event instances - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances#feedback)
* Content Source: [docs/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @KalleOlaviNiemitalo 

I think the best solution is to remove this article, and redirect traffic to a similar how-to article on the [EventHandlerList](https://docs.microsoft.com/dotnet/standard/events/how-to-handle-multiple-events-using-event-properties).

Thoughts @rpetrusha @mairaw ?

**Comment by rpetrusha** [comment]
I agree, @BillWagner. This is really a topic that's built around a dysfunctional example.
