### ISSUE TITLE
Tutorials document requires an update for ML version 1.0.0-preview

### ISSUE THREAD

**Issue by sthakuri** [dotnet/docs#11779]
The following three changes need to be required to work Price Prediction Tutorial work correctly,

#01. Install-Package Microsoft.ML.FastTree after creating the console application
On Create a console application, another ML package "Microsoft.ML.FastTree" need to be installed.

&gt;&gt; dotnet add package Microsoft.ML.FastTree 

#02. Save() function in SaveModelAsFile method will have an extra argument as null,

&gt;&gt;mlContext.Model.Save(model, fileStream)  to  mlContext.Model.Save(model, null, fileStream)

#03. Load() function in Method TestSinglePrediction will have extra argument

            ITransformer loadedModel; 
            Microsoft.ML.DataViewSchema inputSchema;          
            using (var stream = new FileStream(_modelPath, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                loadedModel = mlContext.Model.Load(stream,out inputSchema);
            } 

End

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Predict prices using a regression learner with ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#create-a-console-application)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @sthakuri! The tutorial is in process and will be updated soon.

**Comment by JRAlexander** [comment]
I'll add this to the PR when I submit it.

**Comment by ArchSerpo** [comment]
One other thing I have noticed 

`Console.WriteLine($"*       RMS loss:      {metrics.Rms:#.##}");`

Needs to be

`            Console.WriteLine($"*       RMS loss:      {metrics.RootMeanSquaredError:#.##}");`
