### ISSUE TITLE
Would an InvokeRequired check need to be done for reading a control value like text?

### ISSUE THREAD

**Issue by troglobytor** [dotnet/docs#11785]
Setting a value requires checking if InvokeRequired, what about reading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7944fe-6db1-0fe4-7a89-29f5594b2674
* Version Independent ID: 152ac482-0811-0869-addd-258b689fbe3f
* Content: [How to: Make thread-safe calls to Windows Forms controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls#feedback)
* Content Source: [docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Correct. As stated in the **Unsafe** section:

>It's unsafe to call a control directly from a thread that didn't create it.

So it's still unsafe to do anything with the control from a different thread.
