### ISSUE TITLE
WCF FaultException<T> - .NET Core 2.2

### ISSUE THREAD

**Issue by Henkolicious** [dotnet/docs#11786]
Is faultcontracts with FaultException< T > not supported in .NET Core 2.2?

I have a WCF service reference like so - this exact code is not tested, but simular works well in .NET Standard 4.6.2.

Server side:
<pre>
[OperationContract]
[FaultContract(typeof(MyErrorType))]
[WebInvoke(
      Method = "GET",
      UriTemplate = "/GetData?foo={foo}",
      BodyStyle = WebMessageBodyStyle.Bare,
      RequestFormat = WebMessageFormat.Json,
      ResponseFormat = WebMessageFormat.Json)]
ExpectedResultType GetData(int foo);
</pre>

<pre>
[DataContract]
[Serializable]
public class MyErrorType
{
    [DataMember]
    public int ErrorCode { get; set; }

    [DataMember]
    public string Description { get; set; }
}   
</pre>
<pre>
try {
   return GetData(123);
}
catch (Exception e)
{
    throw new FaultException< MyErrorType >(new MyErrorType() { ErrorCode  = 20,  Description = "Server side error message returning to client" });
}
</pre>

Client side

<pre>
try 
{
   _client.GetData(123);
}
catch (FaultException< MyErrorType > e)
{
  // NEVER ENDS UP HERE IN .NET Core 2.2
  // works fine in .NET Standard 4.6.2 
  Console.WriteLine(e.Details.ErrorCode);
  Console.WriteLine(e.Details.Description);
  throw e;
}
catch (Exception e)
{
  throw e;
}
</pre>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Add WCF Web Service Reference - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide#feedback)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
I believe so. You have to use the https://www.nuget.org/packages/System.ServiceModel.Primitives/ NuGet package to enable it though. They don't ship as part of Core directly.

Let me know if that works for you.

**Comment by Henkolicious** [comment]
@Thraka Nope, the NuGet did not do the trick.

**Comment by Thraka** [comment]
@Henkolicious Sorry that didn't work. I would edit the issue you opened and put all this detail into it. That will help them help you better.

**Comment by romuloteixeira** [comment]
The same issue, Isn't possible reference System.ServiceModel.Web (WebInvoke) on .Net Standard 2.0.
