### ISSUE TITLE
Typo in timespan format

### ISSUE THREAD

**Issue by JJoe2** [dotnet/docs#11787]
The timespan format in the syntax description is invalid: "d.hh.mm.ss"
Should be "d.hh:mm:ss"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b367d01a-e6c9-9854-a2cb-5c22fe4d7198
* Version Independent ID: 4dd28bc7-d0a1-0396-f1a1-4aa335239efe
* Content: [&lt;requestCaching&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/requestcaching-element-network-settings#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/network/requestcaching-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/requestcaching-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
@JJoe2 Thank you for reporting this. Sorry for the delay. I'll open this up to the community to fix.
