### ISSUE TITLE
Provide example without using DataSet/DataRelation classes and utilizing an object graph instead

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11789]
@rschindhelm-haba commented on [Thu Apr 11 2019](https://github.com/dotnet/docs.de-de/issues/136)

It would be great to see an example without the help of the DataSet and DataRelation classes and directed more towards a graph of business objects and their relations.

Make it clear that binding is only possible for properties directly owned by the object-to-be-bound and not for any of its contained objects' properties. Show a way of how to circumvent those restrictions.

Thank you.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f0f9f77-8ccd-3c8a-03db-cdc2bfcbf0dd
* Version Independent ID: b198318d-0b9f-920e-a8a3-1d95f98e8eae
* Content: [Vorgehensweise: Erstellen Sie ein Master / Detail-Formular mit zwei DataGridView-Steuerelementen in Windows Forms](https://docs.microsoft.com/de-de/dotnet/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews)
* Content Source: [docs/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is requesting for additional examples
best

**Comment by rschindhelm-haba** [comment]
Thanks @CeciAc. I always end up opening issues in the wrong place.
