### ISSUE TITLE
TrainTestData Method Does not exist

### ISSUE THREAD

**Issue by jstillings1** [dotnet/docs#11799]
I am recording my ML journey and I am on Linux Mint trying to follow along, I can not compile this.

 TrainTestData does not seem to be a method of TrainCatalogBase anymore.

Checking the resources it shows a 404 on this
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.traincatalogbase.traintestdata Does not exist

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#load-the-data)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi, @jstillings1! We are in the process of updating the tutorials for 1.0.0 preview. In the meantime, TrainTestData is now in DataOperationsCatalog: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.traintestdata?view=ml-dotnet. We apologize for the delay! Please let me know if you have any other questions. Thanks!

**Comment by JRAlexander** [comment]
The code sample here may be helpful as well: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.traintestsplit?view=ml-dotnet#Microsoft_ML_DataOperationsCatalog_TrainTestSplit_Microsoft_ML_IDataView_System_Double_System_String_System_Nullable_System_Int32__

**Comment by JRAlexander** [comment]
Closing as I believe this is resolved. @jstillings1 please let us know if that is not the case. The tutorial should be updated in a few days.

**Comment by jstillings1** [comment]
Thanks John I got caught up with today's projects and left ya hanging. I am sure this fixes it.

Email me at jstillings2@outlook.com
Phone is still down...

________________________________
