### ISSUE TITLE
Call out type extensions not being allowed on type abbreviations more prominently

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1179]
From #1178.  Currently, this tidbit of info is nestled away in a paragraph.  It should be more prominent.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
