### ISSUE TITLE
C# Language Reference: Add mnemonic device to ?: operator to help retention of how evaluation works

### ISSUE THREAD

**Issue by akmadian** [dotnet/docs#11802]
**Help us make content visible**
- Tell us what search terms you used and how you searched docs.
N/A

- Tell us what docs you found that didn't address your concern.
N/A

**Describe the new topic**
- Abstract:
I've always had trouble remembering how the ?: operator evaluates off the top of my head, and I've come up with a mnemonic device to help me remember this. I believe that this mnemonic device could be helpful to others. The mnemonic device I use is `is this cond true ? yes : no`, with the ? part acting as a question mark for the previous statement.

- Suggest a location in the Table of Contents
This change would go directly into [the existing page](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/conditional-operator.md) for the conditional operator.

A mnemonic device is defined as: any learning technique that aids information retention or retrieval in the human memory. Mnemonics make use of elaborative encoding, retrieval cues, and imagery as specific tools to encode any given information in a way that allows for efficient storage and retrieval.

I think that it would be helpful to others to add this mnemonic device to the documentation for this operator. I would be happy to work on this, and work on refining the language of the device as it is quite informal at the moment.

**Comment by BillWagner** [comment]
I like that idea @akmadian 

I've assigned this issue to you. Just @ - mention me if you have any questions as you work on a PR.

**Comment by akmadian** [comment]
@BillWagner Is there a specific branch I should be committing/ merging to? I assume this would not go directly into master.
