### ISSUE TITLE
Indenting in DUs

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/docs#11807]
Document currently reads
&gt; Indent | in type definition by 4 spaces:

Should probably be rephrased slightly to reflect the fact that people may not be using exactly four spaces (though generally they should be!).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
We're going with 4 as the canonical spacing in the document. It's mentioned at the top and recommended in other areas as well.
