### ISSUE TITLE
watermark.png : Norton indicates this has the Heur.AdvML.B virus

### ISSUE THREAD

**Issue by davefxy** [dotnet/docs#11812]
**Before you open an issue**

docs/docs/framework/wpf/getting-started/media/watermark.png

Norton indicates this has the Heur.AdvML.B virus

&lt;include description here&gt;

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework 4.7.1
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Thraka** [comment]
Hi. This is probably a false positive. Please submit the file to https://submit.symantec.com/false_positive/

**Comment by davefxy** [comment]
Yes you are correct. The warning went away very shortly after the second download.

**Comment by mairaw** [comment]
I also think it's a false positive but I'm following up internally already to be safe.
