### ISSUE TITLE
What happens in an async method

### ISSUE THREAD

**Issue by zivkan** [dotnet/docs#11817]
This page used to have a section titled "[What happens in an async method](https://web.archive.org/web/20190224053915/https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#BKMK_WhatHappensUnderstandinganAsyncMethod)".

I used to link to this when customers didn't appear to understand async very well, in particular when customers thought that calling an async method would always immediately start it on a background/threadpool thread. There is now a page titled "Control Flow in Async Programs", however it's far more verbose and less understandable than what used to be on this page. In fact, it's so long that I haven't even read the whole thing myself to confirm that it explain the same concept as what used to be on this page. I expect it explains things in more detail, but some people need quick evidence that making things async doesn't make it parallel, which the old docs were great for. Plus I'm aware that all those links I created in the past will take customers to a page that no longer has the anchor tag that I have in the URL, and therefore won't see the docs that I claimed was here, but that's a minor point.

Anyway, I would like to request that the old section be brought back to this page, or something equivalent (short, and explains that when you call an async method, it's still running on the same thread).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@zivkan it looks the whole page was moved to a new address:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model

In particular, the section you've mentioned:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model#BKMK_WhatHappensUnderstandinganAsyncMethod

**Comment by pkulikov** [comment]
>Plus I'm aware that all those links I created in the past will take customers to a page that no longer has the anchor tag that I have in the URL, and therefore won't see the docs that I claimed was here, but that's a minor point.

Yes, that's pity that the redirect cannot be setup to a new location (the index page was replaced with another page and it's not a good idea to redirect from the index page, I guess)

**Comment by mairaw** [comment]
Given that the same content still exists on a new location (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model#BKMK_WhatHappensUnderstandinganAsyncMethod as @svick pointed out), I think we can close this, but I'll let @BillWagner to decide since he put a lot of thought into this reorganization.

**Comment by zivkan** [comment]
I'm fine with it being closed. I didn't look at the "Task Asynchronous Programming Model" page, so I didn't know the content I like was moved there, although in hindsight that page is the second most likely to have what I was looking for, so I should have found it myself. Now I know, so I'll start using that link. Thanks @pkulikov for pointing it out to me, and apologies to the docs team for not finding it myself.
