### ISSUE TITLE
SynchronizationAttribute doesn't exist in .NET Core 3.0

### ISSUE THREAD

**Issue by reyou** [dotnet/docs#11811]
[Here ](https://docs.microsoft.com/en-us/dotnet/standard/threading/synchronizing-data-for-multithreading) it says:

> You can use the **SynchronizationAttribute** on any ContextBoundObject to synchronize all instance methods and fields. All objects in the same context domain share the same lock. Multiple threads are allowed to access the methods and fields, but only a single thread is allowed at any one time.

but it does not exist.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.remoting.contexts.synchronizationattribute?view=netframework-4.7.2&viewFallbackFrom=netcore-3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d747d4-9377-7cd7-8298-33dba6ebdf28
* Version Independent ID: ebe45308-f267-3f78-d4ea-1b1a71627ff4
* Content: [Synchronizing Data for Multithreading](https://docs.microsoft.com/en-us/dotnet/standard/threading/synchronizing-data-for-multithreading#feedback)
* Content Source: [docs/standard/threading/synchronizing-data-for-multithreading.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/synchronizing-data-for-multithreading.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
 GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out that SynchronizationAttribute is not supported on .NET Core, @reyou. We've opened #12323 to address this issue.
