### ISSUE TITLE
404 not found for link to "record types" GitHub.

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/docs#11829]
First paragraph, link on the text "record types" is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a3af6a-59dd-775a-a008-1530bba493f5
* Version Independent ID: 95639e9c-9432-b07b-5fc2-f30d7bab0123
* Content: [Recursive Pattern Matching - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#feedback)
* Content Source: [proposals/csharp-8.0/patterns.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you @VictorioBerra. I've opened a PR to fix this: https://github.com/dotnet/csharplang/pull/2439

**Comment by mairaw** [comment]
Ah, I just noticed that @Potapy4 had submitted a PR already.
