### ISSUE TITLE
Multiple constraints example

### ISSUE THREAD

**Issue by geoff-m** [dotnet/docs#11835]
The example for multiple constraints looks like this, in which we are to understand that all comma-separated constraints must be satisfied simultaneously:
`class EmployeeList<T> where T : Employee, IEmployee, System.IComparable<T>, new()`

Wouldn't `Employee` implement `IEmployee`? If so, isn't the `IEmployee` constraint (and/or others) redundant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on Type Parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#feedback)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @geoff-m 

That's not the best example. We'll revise that when we next update this article.

**Comment by geoff-m** [comment]
Issue has not been resolved and is still relevant. Therefore it should not be closed.

**Comment by BillWagner** [comment]
reopening per comment.

**Comment by geoff-m** [comment]
The new version is no less confusing than the old version. I opened a new issue at #40268
