### ISSUE TITLE
References to old packages

### ISSUE THREAD

**Issue by manchoz** [dotnet/docs#11839]
`open Microsoft.WindowsAzure.Storage` should be `open Microsoft.Azure.Storage` and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 043a5be5-cb8b-5dc2-864c-01da144ea3c3
* Version Independent ID: 2b8e917a-cbb1-1417-b051-37d45beec0f3
* Content: [Get started with Azure Blob storage using F#](https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-on-azure/blob-storage#feedback)
* Content Source: [docs/fsharp/using-fsharp-on-azure/blob-storage.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-on-azure/blob-storage.md)
* Product: **dotnet-fsharp**
* GitHub Login: @sylvanc
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Fixed in https://github.com/dotnet/samples/pull/942
