### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by TomBinford** [dotnet/docs#11832]
The bracket initialization of openFileDialog1 is invalid. The parentheses are not required and the property Filename does not exist (Probably meant FileName). It's unfortunate that these examples are created without even checking if they compile; I hope your practices improve in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9db6b2-ee5e-dffb-94ea-3c56ed18e34e
* Version Independent ID: 9a19956f-7670-1e75-feb7-8a8b2e71c31e
* Content: [How to: Open files with the OpenFileDialog component](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component#feedback)
* Content Source: [docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I think this was fixed. I tested the code and it works fine and the `Filename` property is `FileName` in the code. 

Sorry for the delay and thank you for filing the issue.
