### ISSUE TITLE
The last code snippet is broken

### ISSUE THREAD

**Issue by zhiliangxu** [dotnet/docs#11837]
The last code snippet of this page is broken. Seems it was removed unintentionally: https://github.com/dotnet/samples/commit/f092292ef86b3fa36a836f57c7a5faf4c8cd973f#diff-b78c98cf195561deb7e95a9023b01fc9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92991e4f-6d00-9e10-9a0d-1058ba06457f
* Version Independent ID: e26cd6f8-ba2c-b8df-919f-4f1ecfd80864
* Content: [Local functions vs. lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/local-functions-vs-lambdas)
* Content Source: [docs/csharp/local-functions-vs-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/csharp/local-functions-vs-lambdas.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for letting us know @zhiliangxu! I've opened a PR to fix this.
