### ISSUE TITLE
TcpListener constructor is deprecated

### ISSUE THREAD

**Issue by DL444** [dotnet/docs#11836]
This article is creating an instance of `TcpListener` with a deprecated constructor. It might be a good idea to update this article to use the current version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4eec82-3aed-b326-1927-9f3d606f9d6b
* Version Independent ID: 4cabdedf-e7e6-4964-2e7e-521d2ca63f48
* Content: [Using TCP Services](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-tcp-services)
* Content Source: [docs/framework/network-programming/using-tcp-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-tcp-services.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
That's a good suggestion @DL444. Adding this to our backlog.
