### ISSUE TITLE
You buried the "this won't work and won't emit an error message for this obscure reason" at the bottom of the page :-(

### ISSUE THREAD

**Issue by chrisfcarroll** [dotnet/docs#11847]
If you could see your way to moving the
"Web projects aren't packable by default. To override the default behavior, add the following property to your .csproj file:"
comment higher up the page, that might save a few of us a couple of hours of fruitless hunting.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-gb/dotnet/core/tools/dotnet-pack?tabs=netcore2x#feedback)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
That's a good suggestion @chrisfcarroll. I'll make this update as I make other changes to the CLI documentation this month.

**Comment by chrisfcarroll** [comment]
Oooh thank you!

**Comment by mairaw** [comment]
I've been behind on my CLI updates but I've opened a PR to fix this specific feedback. See #12409

**Comment by chrisfcarroll** [comment]
Again, thankyou :-)
