### ISSUE TITLE
clarification on virtual and abstract as applied to methods

### ISSUE THREAD

**Issue by dgibbs-at-uwsp** [dotnet/docs#11840]
“The virtual keyword is used to modify a method, property, indexer, or event declaration and allow for it to be overridden in a derived class.”
Very top of the page: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/abstract
	“Members marked as abstract, or included in an abstract class, must be implemented by classes that derive from the abstract class.”

A couple of paragraphs down that page: “An abstract method is implicitly a virtual method.”

So, an abstract method MUST be implemented by an subclass.  But an abstract method is implicitly virtual.  And a virtual method can be overridden by the subclass, but doesn’t necessarily have to be.

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89022fe7-b2e3-5fb5-4930-d6bc5284081a
* Version Independent ID: 6a4f3ec1-e2eb-e046-d840-1c442276b3fb
* Content: [virtual - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual#feedback)
* Content Source: [docs/csharp/language-reference/keywords/virtual.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/virtual.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I don't think you're missing anything. It seems like you understand 😄 I would think that the abstract article that lists the method as being implicitly virtual also then includes the further restrictions listed after that, which includes a statement that it must be overridden in a derived class.

**Comment by Thraka** [comment]
Let me know if this answers your question.

**Comment by Thraka** [comment]
Closing due to lack of response.

**Comment by geoff-m** [comment]
There is a problem on the page for 'abstract'. The sentence, "Members marked as abstract, or included in an abstract class, must be implemented by classes that derive from the abstract class," should say "by non-abstract classes", instead of "by classes".

**Comment by Thraka** [comment]
@geoff-m It's better to open a new issue so that it can be properly tracked. You can also submit a fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
