### ISSUE TITLE
Null deref in sample code

### ISSUE THREAD

**Issue by tromero** [dotnet/docs#11842]
columnBinding?.Path.Path 
Should be 
columnBinding?.Path?.Path 
to prevent dereferencing null if columnBinding is null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e47e2cf-6ecf-32c8-ee13-81af9711260c
* Version Independent ID: 09e85a4a-d6a6-7f11-0cea-5ffd3e9cea1c
* Content: [How to: Sort a GridView Column When a Header Is Clicked](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked#feedback)
* Content Source: [docs/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@tromero Sorry for the delay. We're working through categorizing our current issues and I found this one. Thank you for reporting it.

**Comment by tromero** [comment]
lmao all you had to do was add a single question mark and you couldn't even do that much

**Comment by tromero** [comment]
@dotnet/docs reopen
