### ISSUE TITLE
No C++ Doc

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11841]
@petacreepers23 commented on [Mon Apr 15 2019](https://github.com/dotnet/docs.es-es/issues/124)

Developing for UWP with C++, this kind of error occur, and there is no Documentation at all

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: be7944fe-6db1-0fe4-7a89-29f5594b2674
* Version Independent ID: 152ac482-0811-0869-addd-258b689fbe3f
* Content: [Filtrar Realizar llamadas seguras para subprocesos a controles de formularios Windows Forms](https://docs.microsoft.com/es-es/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls#feedback)
* Content Source: [docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the user is requesting aditional documentation
best regards

**Comment by mairaw** [comment]
This doesn't really belong to .NET docs and it's not related to the WinForms topic in question.

@mijacobs can you help with this feedback? The customer is asking about UWP development with C++.

**Comment by mijacobs** [comment]
Adding @stevewhims , who owns our C++ UWP docs

**Comment by stevewhims** [comment]
Hi, @petacreepers23, thanks for filing this issue. For Universal Windows Platform (UWP) development, there are several language projections to choose from, and the C++ language projection is [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/). C++/WinRT supersedes C++/CX. For info on making thread-safe calls in C++/WinRT, see [Programming with thread affinity in mind](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency#programming-with-thread-affinity-in-mind). Feel free to leave C++/WinRT-related feedback on any of the topics in the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/) set of documentation.

Thanks!
~Steve
