### ISSUE TITLE
Why does this page use the term Iterator when that isn't a .NET term?

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs#11849]
In .NET the term iterator isn't used, but instead enumerator. Why is this page titled Iterators and use the word iterator everywhere? I found it confusing that the docs say "iterator" when the code says "enumerator".

For example, this line:

```The return type of an iterator method or get accessor can be IEnumerable, IEnumerable&lt;T&gt;, IEnumerator, or IEnumerator&lt;T&gt;.```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56aa1016-e778-6bcc-2210-03c89ea6e43a
* Version Independent ID: 3a10fc33-b6e5-8459-9867-ae9f77f84a05
* Content: [Iterate through collections in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/iterators)
* Content Source: [docs/csharp/programming-guide/concepts/iterators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/iterators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @eerhardt 

The reason is historical: When C# was first released, the best way to explain this concept was to compare it to the C++ "itertor".

I've added this to our backlog to update when we next visit this topic.

**Comment by AshwaniT** [comment]
Iterator with yield keyword, how is it different than generators?
