### ISSUE TITLE
What is application exit code if console Main function has return type of void ?

### ISSUE THREAD

**Issue by tapika** [dotnet/docs#11857]
What is application exit code if console Main function has return type of void ?

Is it random value or 0 ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4298ec0-e39e-ad3f-70a3-2e7531d146ad
* Version Independent ID: 31c0c047-4a29-cee2-e4b8-9a9f4470f9cd
* Content: [Main() Return Values - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/main-return-values)
* Content Source: [docs/csharp/programming-guide/main-and-command-args/main-return-values.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/main-and-command-args/main-return-values.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Potapy4** [comment]
I think the default code for `void` is 0. But you can also specify your code using [Environment.Exit](https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit?view=netframework-4.7.2)

**Comment by tapika** [comment]
I need to know it precisely - we have application exiting with non zero code, but I suspect crash on native c++ side.

**Comment by BillWagner** [comment]
@tapika If the return type of `Main` is `void`, the exit code will be `0`.  See the second paragraph of [this section](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/basic-concepts#application-termination)  in the C# Specification.

This article should be updated to reflect that. I've added it to our backlog, and added the 'up for grabs' label.
