### ISSUE TITLE
Tutorial doesn't work in 1.0RC

### ISSUE THREAD

**Issue by mhectorgato** [dotnet/docs#11859]
The StochasticDualCoordinateAscent is not available in the RC. I was able to follow the tutorial, but going to version 0.10; and it works with 0.11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Use ML.NET in a GitHub issue multiclass classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification#load-the-data)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi, @mhectorgato! For the 1.0.0-preview update we are using [SDCALogisticRegressionBinaryTrainer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.sdcalogisticregressionbinarytrainer?view=ml-dotnet)
Here's the code line for that:
.Append(mlContext.BinaryClassification.Trainers.SdcaLogisticRegression(labelColumnName: "Label", featureColumnName: "Features"));

We are in process of updating the tutorial for 1.0.0-preview.  Here is the PR - https://github.com/dotnet/docs/pull/11816. I'm hoping it will be live in the next day or so. 

Also, here is the updated code sample PR: https://github.com/dotnet/samples/pull/817  

I hope this helps! -- John
