### ISSUE TITLE
May i get the named blocks in details?

### ISSUE THREAD

**Issue by xp44mm** [dotnet/docs#11858]
how to use the named blocks, and what characters do the name represent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for your question, @xp44mm. There is an example that uses two named blocks in a regular expression in the [Unicode Category or Unicode Block: \p{}](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#unicode-category-or-unicode-block-p) section. Each named block represents a contiguous range of Unicode code units. For example, the `IsGreek` named block matches U+0370, U+0371, U+0372 …U+03FF.
We'll add a note to the Supported Named Blocks section that notes the example earlier in the article.

**Comment by xp44mm** [comment]
thank you for letting me known!
