### ISSUE TITLE
mlContext.Clustering.Trainers.KMeans(featuresColumnName, numberOfClusters: 3) seems incorrect for 

### ISSUE THREAD

**Issue by kristianjaeger** [dotnet/docs#11854]
This code snippet seems to be incorrect Microsoft.ML version 0.11.0.  It is mentioned in section - https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering#create-a-learning-pipeline .  Thanks.
string featuresColumnName = "Features";
var pipeline = mlContext.Transforms
    .Concatenate(featuresColumnName, "SepalLength", "SepalWidth", "PetalLength", "PetalWidth")
    .Append(mlContext.Clustering.Trainers.KMeans(featuresColumnName, numberOfClusters: 3));

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1739	The best overload for 'KMeans' does not have a parameter named 'numberOfClusters'	IrisFlowerClustering	...\IrisFlowerClustering\IrisFlowerClustering\Program.cs	24	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925c8fe9-ba0b-bd2c-cea0-9d851ece8825
* Version Independent ID: 41cafff5-6418-2e54-3a0d-ee29fb1fca1f
* Content: [Cluster iris flowers using a clustering learner - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering#feedback)
* Content Source: [docs/machine-learning/tutorials/iris-clustering.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/iris-clustering.md)
* Product: **dotnet-ml**
* GitHub Login: @pkulikov
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@kristianjaeger the tutorial uses the latest ML.NET version, which is 1.0 Preview. So, it's expected that it might not work with the 0.11.0 version.

You can find the full sample project in the samples repo:
https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/IrisFlowerClustering

**Comment by kristianjaeger** [comment]
Thanks. My mistake. I'll try the preview when I have time. Cheers.

**Comment by kristianjaeger** [comment]
Thanks! That worked.  Might be helpful to callout that folks can use the Package Manager Console directly `Install-Package Microsoft.ML -Version 1.0.0-preview` .  Cheers.

**Comment by JRAlexander** [comment]
Closing as I believe this is resolved. Please reopen or comment if that's not the case. Thanks!
