### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ehosaini** [dotnet/docs#11868]
In the "Challenge - log all transactions" section, "Notes" should be replaced with "Note" in the following line of code.
report.AppendLine($"{item.Date.ToShortDateString()}\t{item.Amount}\t{item.Notes}");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@ehosaini I think it is supposed to be `.Notes` as the type, `Transaction` has a `Notes` property. The parameter used to fill the `Notes` property is `note` (non plural) which may be why you're confused?

**Comment by Thraka** [comment]
I'm going to close this, but if you think I'm wrong, please let me know 😄
