### ISSUE TITLE
path typo in add reference command line and xml

### ISSUE THREAD

**Issue by toyidong** [dotnet/docs#11866]
"dotnet add reference ../../NewTypes/NewTypes.csproj"

should be "dotnet add reference ../../src/NewTypes/NewTypes.csproj"

same issue in xml part, but it is correct in xml of NewTypesTests.csproj 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b54562-9072-a864-be3d-44ed7965c798
* Version Independent ID: a69ec985-ed05-90dd-a686-dc956b0cf5df
* Content: [Organizing and testing projects with the .NET Core command line - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#feedback)
* Content Source: [docs/core/tutorials/testing-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
