### ISSUE TITLE
Suggestion for new tutorial - Structural Time Series

### ISSUE THREAD

**Issue by kristianjaeger** [dotnet/docs#11864]
Please see https://medium.com/tensorflow/structural-time-series-modeling-in-tensorflow-probability-344edac24083 . Thank you!

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [.NET Machine learning tutorials - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @kristianjaeger. We've added this to the backlog. You may want to check out this sample: https://medium.com/tensorflow/structural-time-series-modeling-in-tensorflow-probability-344edac24083

**Comment by kristianjaeger** [comment]
Thanks @JRAlexander . That's the link I put in the issue :)

**Comment by JRAlexander** [comment]
Yes, it is. My bad. Sorry, meant to add a different link. Edited above to the Machinelearning/samples like I intended to recommend. :)

**Comment by kristianjaeger** [comment]
@JRAlexander Unfortunately, I get a 404 now for the link that you provided. Cheers.

**Comment by JRAlexander** [comment]
They moved the sample. Try this:  https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/AnomalyDetection_PowerMeterReadings

**Comment by kristianjaeger** [comment]
Thanks!  I saw a talk at MS Build that seemed similar.  Cheers.

**Comment by luisquintanilla** [comment]
Thanks for the suggestion @kristianjaeger. We've added it to our backlog.
