### ISSUE TITLE
Specify Nuget Server

### ISSUE THREAD

**Issue by ardalis** [dotnet/docs#11867]
My default nuget server is a local URL; how can I run this command and specify I want to use nuget.org as my server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#feedback)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Did you try the `--add-source <SOURCE>` parameter? Let me know if that works.

**Comment by Thraka** [comment]
Closing due to no response.
