### ISSUE TITLE
Add links to each of the tags in "In this article" 

### ISSUE THREAD

**Issue by djeec** [dotnet/docs#11861]
It would be nice to have links added to each of the tags in the "In this article" navbar.

For example, if I want to find the &lt;list&gt; tag, I have to scroll searching for it manually, or use Ctrl+F

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#feedback)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @djeec 

I think the best way to fix this is to update the headers for the different tags from `H3` to `H2`. Then, they would appear automatically.

I've added this to our backlog, and added the "up for grabs" label to this issue.

**Comment by drakegens** [comment]
Could I take a stab at this one?

**Comment by BillWagner** [comment]
Thank you @drakegens We'd appreciate that.  Just @ - mention me if you have any questions while you're working on a PR. You should find all the information you need in our [contributor guide](https://docs.microsoft.com/Contribute/dotnet-contribute)
