### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by PakAtom** [dotnet/docs#11872]
got these errors
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'TransformsCatalog' does not contain a definition for 'ScoreTensorFlowModel' and no accessible extension method 'ScoreTensorFlowModel' accepting a first argument of type 'TransformsCatalog' could be found (are you missing a using directive or an assembly reference?)	TransferLearningTF	C:\Users\Satti\Desktop\Migration\TransferLearningTF\TransferLearningTF\Program.cs	66	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Build an ML.NET custom image classifier with TensorFlow](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi PakAtom.   This tutorial is currently on v 0.10.0. We should have it updated to v 1.0.0-preview in the next few days. In the  meantime, please check out https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator which has been updated to 1.0.0. Thanks!

**Comment by PakAtom** [comment]
Thanks for the update. Looking forward for version 1.
js
