### ISSUE TITLE
Publish as self-contained app "side-by-side"

### ISSUE THREAD

**Issue by fleed** [dotnet/docs#11873]
Is it possible to use the command `dotnet publish -r win10-x64` on the same *csproj* file used to generate a tool?
Use case: I would like to generate both an executable and the dotnet tool.
If I try, I get the following error: * error NETSDK1053: Pack as tool does not support self contained.*

I tried it with SDK versions `2.2.106` and `2.2.203`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [How to create a .NET Core Global Tool - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Yes! Just turn off the `<PackAsTool>` property on the command line 😄 

```console
dotnet publish -r win10-x64 /p:PackAsTool=false
```

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
