### ISSUE TITLE
Change the name of `core-docs` to `docs`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1187]
The name `core-docs` made sense when this repo would be dedicated to the documentation for .NET Core. Its scope has grown, so its name should change.

When we change the repo name on GitHub, GitHub will issue 301 redirects for almost everything referenced with the existing name.  See [here](https://help.github.com/articles/renaming-a-repository/) for details. Remotes will automatically redirect, as will forks.

Community members with active forks can continue using them. However, when the reach a point where they don't have open work in progress, recreating the fork using the new repo name is advised.

Community members that have cloned the repo (not through a fork) can follow [these instructions](https://help.github.com/articles/changing-a-remote-s-url/) to update the remote URL.

**Comment by mairaw** [comment]
Rename is done and URLs on our content have been updated. External links will be redirected to the new repo name appropriately.
