### ISSUE TITLE
How to add a permanent source?

### ISSUE THREAD

**Issue by nikoudel** [dotnet/docs#11875]
`--add-source` specifies the source per request. Is it possible to add a source (of a private repository) permanently so it will not be necessary to mention it each time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [How to create a .NET Core Global Tool - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#feedback)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello! I believe you just need to create/edit a nuget config file: https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
