### ISSUE TITLE
Tuples as out variables

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [dotnet/docs#11874]
It can be a nice example to have tuples as out variables.
`

    Dictionary<int, (int min, int max)> ranges;

    ...

    if (ranges.TryGetValue(key, out (int min, int max)))
    // similar to dict.TryGetValue(key, out int value)
`
I could not make this work, and there are lots of classes applying this pattern. If it cannot work, it will be nice to indicate that it is not possible.

EDIT: 
I found out from [this StackOverflow answer](https://stackoverflow.com/questions/51050951/c7-out-variables-with-tuples) that one can use 
`
    ranges.TryGetValue(key, out (int, int) minMax)
`
or
`
    ranges.TryGetValue(key, out (int min, int max) minMax)
`
which may or may not be added as an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#feedback)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm glad you found the answer @zahirtezcan-bugs 

I've added this to our backlog, and the community contributions project. I've also added the "up for grabs" label to this issue.

If you'd like to submit a PR including the answer, I'll watch for it. If not, we'll add this sample when we next update this article.

Thanks for bringing this to our attention.

**Comment by zahirtezcan-bugs** [comment]
I think it is better if you add the sample.

Also it seems like there is also an option to use `var` keyword:

`ranges.TryGetValue(key, out var minMax)`
