### ISSUE TITLE
Document pattern: UnionCaseLabel(UnionCaseProperty=var)

### ISSUE THREAD

**Issue by tastyeggs** [dotnet/docs#11879]
There's this pattern I discovered in one github issue, and almost feels like a hidden Easter Egg in the language.

Assuming I have this union type:

```
type A =
| Case1 of Prop1: int * Prop2: string
| Case2 of Prop3: bool * Prop2: string
```

I will be able to pattern match a variable of this union type as follows:

```
match a with
| Case1(Prop2=prop2)
| Case2(Prop2=prop2) 
   -> printfn "Prop2 is %s" prop2
```

I don't even know what this pattern is called. Please name it, and document it. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3ed054-03c9-375f-403b-68f0356d5870
* Version Independent ID: 3c167003-13e8-359b-e919-693258e7f48b
* Content: [Pattern Matching - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#feedback)
* Content Source: [docs/fsharp/language-reference/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/pattern-matching.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by baronfel** [comment]
@tastyeggs can you check [this section](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#identifier-patterns) of the docs and see if that addresses it for you? Specifically the section starting with

> For discriminated unions that have named fields, you use the equals sign (=) to extract the value of a named field. For example, consider a discriminated union with a declaration like the following.

**Comment by tastyeggs** [comment]
Ah, I missed it, since its nested deep within the text. This works. 

Would be nice to have it in the examples up top, but I can't think of a good way of representing this example concisely.
