### ISSUE TITLE
Update Note

### ISSUE THREAD

**Issue by ehosaini** [dotnet/docs#11883]
With .NET Core 2.2 SDK, one only needs to run `dotnet run` after each code change. There is no need to run `dotnet build`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#processing-the-json-result)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by jwwicks** [comment]
@Thraka According to the note on this [page](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21) restore isn't even strictly required. 

I'll pick this up but would it be best to just git rid of the extra steps and put in a note section that specifies prior to 2.1 you should run restore and build explicitly.

**Comment by Thraka** [comment]
@jwwicks Do you mean prior to 2.0?

**Comment by jwwicks** [comment]
> @jwwicks Do you mean prior to 2.0?

Yeah note says 2.0, typo :)

**Comment by Thraka** [comment]
I think you can just delete the note. 1.x is about to fall out of LTS and the prereqs on this page make you download 2.2.
