### ISSUE TITLE
Doc typo for ICLRControl::GetCLRManager::GetCLRManager

### ISSUE THREAD

**Issue by thewilsonator** [dotnet/docs#11881]
[Enter feedback here]
Typo in docs for ICLRControl::GetCLRManager Method GetCLRManager:

...
* IID_ICLRTaskManager: _speciries_ that ppObject will be of type ICLRTaskManager.
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a601fe-7b35-60af-c8f0-3c7bee01f74e
* Version Independent ID: 87c6e76a-5fb9-cea5-8522-5123d9aa84b6
* Content: [ICLRControl::GetCLRManager Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/iclrcontrol-getclrmanager-method)
* Content Source: [docs/framework/unmanaged-api/hosting/iclrcontrol-getclrmanager-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/hosting/iclrcontrol-getclrmanager-method.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for noticing the typo, @thewilsonator. We've corrected it in #11882.

**Comment by thewilsonator** [comment]
No problem!

**Comment by mairaw** [comment]
You can also submit the changes when you find something like this:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by thewilsonator** [comment]
Noted, although I'll probably have forgotten about it when I could next make use of it.
