### ISSUE TITLE
Bot Cảm Xúc

### ISSUE THREAD

**Issue by thacamxuc** [dotnet/docs#11895]
https://thacamxuc.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865bd72b-8d26-ec50-4fc0-e3754a00c00c
* Version Independent ID: 5607825a-87ff-1138-3743-0f1fd8408b16
* Content: [Restricting Accessor Accessibility - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing as spam.
