### ISSUE TITLE
What does it mean to run a DLL?

### ISSUE THREAD

**Issue by qwertie** [dotnet/docs#11890]
The dotnet command page should explain what it means to run a DLL. Is it looking for a "public static void Main"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @qwertie. I'll address this once next time I update this page. But yes, it's looking for an entry point to run the app, which in the case of console apps is the `Main` method.
