### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by PakAtom** [dotnet/docs#11894]
1. return File.ReadAllLines(file) =file does not exist in the current contrxt.
2. var predictions = loadedModel.Transform(imageDataView);= imageDataView unreachable code
3. PairAndDisplayResults(imageData, imagePredictionData);= imageData, unreachable code

All in public static void ClassifyImages(...) method.

any suggrstion will be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Build an ML.NET custom image classifier with TensorFlow](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@PakAtom - This is in process of being updated. In the meantime, check out https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator. It's been updated to 1.0.0-preview.

**Comment by JRAlexander** [comment]
@PakAtom I just pushed the updated code sample for the tutorial. Here is the PR: https://github.com/dotnet/samples/pull/833
