### ISSUE TITLE
Fix description about --configuration

### ISSUE THREAD

**Issue by slado** [dotnet/docs#11896]
According to the documentation, the configuration supports only Debug and Release
-c|--configuration {Debug|Release}

But actually it supports any configuration, even user defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello! Thank you for filing this issue. We're in the middle of updating a lot of the CLI docs.

@mairaw I figured you could fix this during your other updates to the CLI docs. Assigning to you but leaving the project/milestone settings up to you.
