### ISSUE TITLE
SQL Azure MFA Support example

### ISSUE THREAD

**Issue by nickbeagley2** [dotnet/docs#11893]
This page links to .NET Blog claiming it has an example of how to use the new connection libraries for MFA.

"For more information and an example, see "SQL -- Azure AD Universal and Multi-factor Authentication Support" in the .Net blog https://devblogs.microsoft.com/dotnet/net-framework-4-7-2-developer-pack-early-access-build-3056-is-available/"

While that blog does claim to have an example, it does not. "The following sample shows how to instantiate the communication provider that is required to register it to a specific authentication method. It also shows creating connections to SQL database using the different authentication methods, of which two are existing ones: ActiveDirectoryPassword, ActiveDirectoryIntegrated and the latest ActiveDirectoryInteractive."  

Then there is no example.

Really, it is this page that should have that example that does not seem to exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702f3b92-45f6-2115-42fc-18331dc2c824
* Version Independent ID: f6dbce4e-fb64-9c95-5b6c-d1b5272c3078
* Content: [What's new in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/index#sql472)
* Content Source: [docs/framework/whats-new/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/whats-new/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
I do see an example there:
![image](https://user-images.githubusercontent.com/12971179/70304878-c03e8c00-17b7-11ea-942b-1fdaaee903b2.png)

I'm wondering if this was an issue while we were migrating the blogs to a new platform.

If your issue is not solved, please let us know.

**Comment by nickbeagley2** [comment]
Thanks @mairaw I can see it now, i'm certain that section was not there when I raised the issue.
