### ISSUE TITLE
Page is woefully out of date

### ISSUE THREAD

**Issue by sharpninja** [dotnet/docs#11903]
Please update this page to include Dotnet Core 2.1, 2.2 and 3.0 as well as .Net Framework 4.7.x.  There are people making bad assumptions based on it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello.

What assumptions are people making? The table is focused on the .net standard version and the intro to the table states that the versions listed are the **minimum** required.

**Comment by sharpninja** [comment]
> Hello.
> 
> What assumptions are people making? The table is focused on the .net standard version and the intro to the table states that the versions listed are the **minimum** required.

How do I get to the table.  The source file for the page links to net-standard-table.md which is not located in the repository.

**Comment by svick** [comment]
@sharpninja [The source for that page is in this repository.](https://github.com/dotnet/docs/blob/master/includes/net-standard-table.md) (GitHub version of the page does not understand the link, which is why the link is 404.)

**Comment by svick** [comment]
Since people still seem to be confused by the table, maybe it would make sense to add an explicit explanation before the table? Something along the lines of:

> If a newer version of a platform is not listed in the table, it means it supports the same version of .NET Standard as the last listed version of that platform.

**Comment by mairaw** [comment]
See if that helps: https://github.com/dotnet/docs/pull/11991

I'm also trying to think of a way where we could do the opposite of what this table does and would allow you to select what you wanna target and it would tell you what .NET Standard versions it supports. Not sure if I have many capabilities with the features we have on docs. Let me experiment.

**Comment by mairaw** [comment]
I'm testing a few different options here:
https://github.com/dotnet/docs/blob/ns-experiment/docs/standard/net-standard.md

What do you think of adding a table like this to that article? (using range or listing versions individually is an option; just wanted to test some things out)

![image](https://user-images.githubusercontent.com/12971179/56620305-503f1500-65dd-11e9-9038-64188cafe283.png)

Tagging @pkulikov since you commented on my PR as well

/cc @terrajobst

**Comment by terrajobst** [comment]
I was working with @rowanmiller to a get an interactive table hosted on dot.net. There is a design proposal we'll be reviewing soon.

**Comment by pkulikov** [comment]
@mairaw I think such an additional table would be of great help. Listing version is essential, I think. That makes it easier to understand.

One remark, though. Should .NET Core section contain two rows: .NET Core 1.0 and 1.1 don't support .NET Standard 2.0, but only .NET Standard 1.6

**Comment by Thraka** [comment]
@mairaw What about using this as a test for pivot zones?

**Comment by mairaw** [comment]
Yes, I know you are @terrajobst. But I thought it would be similar to the one you have in https://immo.landwerth.net/netstandard-versions/# which is different than I'm proposing here.
Or would you also allow to select a TFM and then tell me which .NET Standard versions are supported?

Good catch @pkulikov. I _think_ I fixed my table above.

@Thraka not in this case. You wanna see all versions and platforms together to choose the one that makes the most sense if you're multi-targeting, creating a .NET Standard library, etc.

**Comment by rowanmiller** [comment]
We just published the first version of the interactive table to https://dotnet.microsoft.com/platform/dotnet-standard

We landed on a design that is a little different from https://immo.landwerth.net/netstandard-versions/#, trying to make it clearer what the table is conveying. I *might* help with the confusion being discussed here.

**Comment by terrajobst** [comment]
I've update the link in the standard repo to point to the new table. I've also submitted https://github.com/dotnet/docs/pull/12354 to update the official docs.

**Comment by mairaw** [comment]
Awesome guys! So what do folks think? Would you still like to see a static version on our docs or can we consider this issue resolved?

**Comment by sharpninja** [comment]
@mairaw That looks fantastic!

**Comment by terrajobst** [comment]
> Awesome guys! So what do folks think? Would you still like to see a static version on our docs or can we consider this issue resolved?

I'd say resolved 😛

**Comment by JimInWA** [comment]
I don't have a screen reader handy, so this might already been taken care of in the new design but I wanted to raise it just in case - because the new design uses JavaScript to apply an image using CSS (label-danger or label-success) there is a strong possibility that a user with a screen reader won't get any of the additional details - meaning that they will just hear the numbers without any additional context.

Not sure if all of Docs (or associated sites that articles on Docs link to) needs to follow the Microsoft public web guidelines for accessibility, but figured I would point it out.

**Comment by rowanmiller** [comment]
@JimInWA you are correct - we'll get this fixed.

**Comment by rowanmiller** [comment]
@JimInWA just confirming that this is now fixed. We added additional "is supported"/"is not supported" text that is only rendered for screen readers.

**Comment by terrajobst** [comment]
Looks like this can be closed now.
