### ISSUE TITLE
please introduce  logpath

### ISSUE THREAD

**Issue by RAJU2529** [dotnet/docs#11902]
I need  a  the  verification of  log file , while  using  signtool.exe  .
for example  if  we  use  
signtool.exe verify /pa /v C:\Windows\system32\drivers\*.*

Above  command  verifies  all the  in the driver's folder , it keep running 
results  are  very fast  , I we could  not able  to see the results  .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a4dbac-a145-e79f-121d-3d8df67552b1
* Version Independent ID: 9ea61916-a9db-f23e-4c43-edc06650483d
* Content: [SignTool.exe (Sign Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe#feedback)
* Content Source: [docs/framework/tools/signtool-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/signtool-exe.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by RonnieWilkinsJr** [comment]
You can pipe the results to a log file by appending: > "LogFilePath\LogFileName.log"

**Comment by RonnieWilkinsJr** [comment]
Example:
signtool.exe verify /pa /v C:\Windows\system32\drivers*.* > "C:\Temp\SignToolVerification.log"

**Comment by RAJU2529** [comment]
RonnieWalksinsJr Thanks sir  for  your  logpath.  its  working fine .
I  have created some useful commands 


signtool.exe verify /pa /v C:\Windows\system32\drivers\*.* > "C:\Signtool-pa-v.log"
signtool.exe verify /pa /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-pa-ph.log"
signtool.exe verify /all /v C:\Windows\system32\drivers\*.* > "C:\Signtool-all.log"
signtool.exe verify /all /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-all-ph-v.log"
signtool.exe verify /ms /v C:\Windows\system32\drivers\*.* > "C:\Signtool-ms-v.log"
signtool.exe verify /ms /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-ms-ph-v.log"
signtool.exe verify /bp /v C:\Windows\system32\drivers\*.* > "C:\Signtool-bp-v.log"
signtool.exe verify /bp /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-bp-ph-v.log"
signtool.exe verify /enclave /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-enclave-ph-v.log"
signtool.exe verify /kp /v C:\Windows\system32\drivers\*.* > "C:\Signtool-kp.log"
signtool.exe verify /kp /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-kp-ph-v.log"
signtool.exe verify /all /bp /enclave /ph /v C:\Windows\system32\drivers\*.* > "C:\Signtool-all-bp-enclave-ph-v.log"

if you have free time., i am requesting to you  -analysis the  logfile 
I attached  thosefiles in onedrive
here is the link
https://1drv.ms/u/s!AmZoRRusRV59l2gKu6eJbVeRrkQy

**Comment by mairaw** [comment]
I feel like this issue is answered, so closing.
