### ISSUE TITLE
Short

### ISSUE THREAD

**Issue by Arthonor** [dotnet/docs#11906]
Extensions are a set of static methods, that attach to the classes of the namespace Using the Extensions. 
Imitating beeing a method of a different class.
If class get a method with same name, it will take precedence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Extension Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Closing as an annotation

@Arthonor Your comments will still be visible at the bottom of this article. They'll be on the "closed" issues tab.
