### ISSUE TITLE
Real usage

### ISSUE THREAD

**Issue by Arthonor** [dotnet/docs#11907]
Extensions is spoken about as an easy way to add general methods across types. but can not hold 
But there is other uses instead of laziness.

If you use Extensions in the matter they discourage here, you can use them as a safety net.
(well you usually would use an interface)
If you have multiple List types (some made by others), and you do not know if they all have a Sort() method.
You can add a Sort() Extension, and it will only be used, if the Lists are missing a Sort().

Lazy or not compare:
static class GeneralMethods
  int CountWords(ref string)

GeneralMethods.CountWords(ref myString) - Not Lazy
or
myString.CountWords() - Lazy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Extension Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
These are great comments @Arthonor 

Yes, you'll often create extension methods when you want to extend a type, but that type is from another assembly. You can build functionality from the existing public API to add new capabilities.

It's also correct that you'd likely extend the original class in cases where you have the source for that type.

Closing as an answered question.

**Comment by ManishaTayal** [comment]
Why is it compulsory for the extension method to be defined in static class?
