### ISSUE TITLE
using and namespace

### ISSUE THREAD

**Issue by Arthonor** [dotnet/docs#11905]
Notice in Visual Studio, Using statements are placed outside of namespace as default.
Here it seems Using is required to be inside the namespace. ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Extension Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The using statement can be either inside or outside a namespace.

Closing this as a question that has been answered.
