### ISSUE TITLE
An item with the same key has already been added. Key: Microsoft.NETCore.App

### ISSUE THREAD

**Issue by sguryev** [dotnet/docs#1190]
File [project.json](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json) of the test project contains 2 items with the same key on Lines [6](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json#L6) and [19](https://github.com/dotnet/docs/blob/master/samples/core/getting-started/unit-testing-using-dotnet-test/test/PrimeService.Tests/project.json#L19):

Visual Studio 2015 shows the following error:
![image](https://cloud.githubusercontent.com/assets/6978458/19828281/b090e7e0-9dca-11e6-93b9-bf44945cbd8a.png)

Here is the project.json file structure reference: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#frameworks

I think there should be only one dependency: either package-level or framework-specific.

**Comment by ovidiaconescu** [comment]
I ran into the same issue while upgrading a netcoreapp1.0 to netcoreapp1.1 from Nuget as well as manually changing the frameworks section to
`"frameworks": {
    "netcoreapp1.1": {
		  "dependencies": {
			  "Microsoft.NETCore.App": {
			    "type": "platform",
			    "version": "1.1.0"
			  }
		  },
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },`

I was left with a top level dependency on `"Microsoft.NETCore.App"` which spawned the error above.

**Comment by sguryev** [comment]
@ovidiaconescu agree with you. I did the same.
