### ISSUE TITLE
Project Does Not Compile - Invalid Definition

### ISSUE THREAD

**Issue by grecoe** [dotnet/docs#11908]
Repository: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis

Does not compile:

In the section Create a console application the third step:

“In Solution Explorer, right-click on your project and select Manage NuGet Packages. Choose "nuget.org" as the Package source, select the Browse tab, search for Microsoft.ML,”

When I do that, I got v 1.0.0-preview

I got to the section Initialize variables in Main before the issue arose with this line:

TrainCatalogBase.TrainTestData splitDataView = LoadData(mlContext);

The issue is that TrainTestData does not appear to be a member of TrainCatalogBase. A few steps further is another issue with BinaryClassification:

Severity | Code | Description | Project | File | Line | Suppression   State
-- | -- | -- | -- | -- | -- | --
Error | CS0426 | The   type name 'TrainTestData' does not exist in the type 'TrainCatalogBase' | Sentiment | C:\_MLNET\Sentiment\Sentiment\Program.cs | 30 | Active
Severity | Code | Description | Project | File | Line | Suppression   State
Error | CS1061 | 'BinaryClassificationCatalog'   does not contain a definition for 'TrainTestSplit' and no accessible   extension method 'TrainTestSplit' accepting a first argument of type   'BinaryClassificationCatalog' could be found (are you missing a using   directive or an assembly reference?) | Sentiment | C:\_MLNET\Sentiment\Sentiment\Program.cs | 33 | Active

**Comment by grecoe** [comment]
This might just be a doc issue, although it does not work with v1.0.0-preview. When telling the user to choose Microsoft.ML in NuGet, it doesn't clarify what version to get, it just says:

"In Solution Explorer, right-click on your project and select Manage NuGet Packages. Choose "nuget.org" as the Package source, select the Browse tab, search for Microsoft.ML, select that package in the list, and select the Install button. Select the OK button on the Preview Changes dialog and then select the I Accept button on the License Acceptance dialog if you agree with the license terms for the packages listed."

Which I did. Scrolling back up I see there is a requirement on v0.11. Uninstalling the latest and getting 0.11 seems to have resolved the issue. But it would be nice to update this to the latest version.

**Comment by JRAlexander** [comment]
HI @grecoe, thanks for your feedback. Adding the version to the NuGet instructions is a good idea, and I'll update that. We've now updated the tutorial to v 1.0.0-preview. Closing as I believe this is resolved.

**Comment by Ohmniox** [comment]
Fix: change mlContext.BinaryClassification.TrainTestSplit() to mlContext.Data.TrainTestSplit()
