### ISSUE TITLE
What is global proxy selection?

### ISSUE THREAD

**Issue by dombat** [dotnet/docs#11901]
This page should link to another page that details the "global proxy selection" and how it works with .NET. e.g. if you set it once what is the scope (assembly, whole computer, etc) how does it revert to a non overrriden state, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf40aa7-db58-02c0-e232-42d62c533ff6
* Version Independent ID: 4ef4e31a-9bc6-323a-6545-42229a0ce44b
* Content: [How to: Override a Global Proxy Selection](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-override-a-global-proxy-selection#feedback)
* Content Source: [docs/framework/network-programming/how-to-override-a-global-proxy-selection.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-override-a-global-proxy-selection.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
@karelz @davidsh I don't think we have any content that talks about global proxy selection. Should we?
Should this article use and link to https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.defaultwebproxy?

**Comment by davidsh** [comment]
>@karelz @davidsh I don't think we have any content that talks about global proxy selection. Should we?

Yes, we should update this topic.

>Should this article use and link to https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.defaultwebproxy?

But we should not use WebRequest.DefaultWebProxy as the best example. That is an API that is only used in .NET Framework.

In .NET Core 3.0, we added a new API, [HttpClient.DefaultProxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.0#System_Net_Http_HttpClient_DefaultProxy). In addition, in .NET Core 3.0, we also support environment variables across all OS platforms (Windows, Linux, Mac).
