### ISSUE TITLE
Very minimal example

### ISSUE THREAD

**Issue by BeMor81** [dotnet/docs#11913]
Very minimal example I'm afraid. How do you then access the data held within the parsed XML? No links really guiding you to the next stage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffa0043-9eab-b4cb-ff8f-d28403127422
* Version Independent ID: 357b7e7d-be95-39fc-902d-67258029294f
* Content: [How to: Parse a String (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-parse-a-string)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-parse-a-string.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-parse-a-string.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @BeMor81 We'll address this when we next update this article.
