### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by dgunderson** [dotnet/docs#11910]
Where does the "e" come from with the following code:

e.Graphics.DrawLine(pen, 0, 10, 200, 10);
e.Graphics.FillEllipse(linGrBrush, 0, 30, 200, 100);
e.Graphics.FillRectangle(linGrBrush, 0, 155, 500, 30);

The examples do not illustrate this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6ed473-9c2d-72c3-a08b-021bdd251254
* Version Independent ID: 8b755685-b1dc-18e6-bf7e-8320ebb39988
* Content: [How to: Create a Linear Gradient](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-create-a-linear-gradient#feedback)
* Content Source: [docs/framework/winforms/advanced/how-to-create-a-linear-gradient.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-create-a-linear-gradient.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @dgunderson. Certainly, the failure to provide any context for `e` is a major failure in these examples. As it happens, e is a PaintEventArgs instance, and this code either is in a Paint event handler or a method that is called by a Paint event handler.

We've opened dotnet/samples#827 to address this issue.
