### ISSUE TITLE
Where ??? !!!

### ISSUE THREAD

**Issue by serhioV** [dotnet/docs#11912]
"Run the project in the current directory:"

where should we run that command from the command line? is not really clear, should it be run from the VS .NET Console or the simple command line, and what path should we consider? "current directory" what current directory, the project one? the solution one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3f4227-cd9b-7b1c-7e1b-ffb3d42ae496
* Version Independent ID: 7e78f9f5-f77c-828d-ef76-8ef8593d5803
* Content: [dotnet run command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet-run.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-run.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by hrnsky** [comment]
Yes you are right, It's not clear, but as you see the code, dotnet run command requires the .csproj file, you can either pass the full path or run inside the folder where .csproj located.

**Comment by Thraka** [comment]
This article is reference for the command run from the command line, it's not a tutorial or conceptual article where you follow the steps. However, the initial description for the command says:

>The `dotnet run` command provides a convenient option to run your application from the source code with one command. It's useful for fast iterative development from the command line. The command depends on the dotnet build command to build the code. Any requirements for the build, such as that the project must be restored first, apply to dotnet run as well.

So the description of `dotnet run` where it says "run the project in the current directory" is talking about your terminal's current directory.

I think your question is answered and I'm going to close this issue. Please reply if you have more questions. Thanks!

**Comment by serhioV** [comment]
Is to say that the "current directory" sentence has no sense... 

Probably replace with "your project's directory", or the "directory containing the .*proj file" would have some sense...

**Comment by serhioV** [comment]
> as you see the code, dotnet run command requires the .csproj file

If I am newbie I don't see it at all...  Or the article is written only for the experts of the dotnet run command?

**Comment by Thraka** [comment]
There is no visual studio involved in the command line tools, so it's implied you're using a terminal of some sort and in the terminal you're always in some directory. The current directory is searched for a solution or project and is run if found, if not found it tells you:

>Couldn't find a project to run. Ensure a project exists in XXXX, or pass the path to the project using --project.

Where `XXXX` actually prints out the current directory.
