### ISSUE TITLE
4.8 min mistake

### ISSUE THREAD

**Issue by jenokizm** [dotnet/docs#11923]
If compare the information from the page where the minimum numbers and on the page where all the numbers, it becomes clear that there is an mistake. There is more than the minimum number for 4.8, that is 528040 but not 528049

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9ab3cb0-89c4-80f1-b6d0-b7039141d71e
* Version Independent ID: 69568665-c307-a59f-1ed4-00db35de5f70
* Content: [Minimum values of the Release DWORD for each .NET Framework version](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/minimum-release-dword#feedback)
* Content Source: [docs/framework/migration-guide/minimum-release-dword.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/minimum-release-dword.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks you so much for pointing this out, @jenokizm. I've opened #11956 to address it.
