### ISSUE TITLE
.NET Core 3.0 Feature - Large Pages in .NET Core

### ISSUE THREAD

**Issue by mjsabby** [dotnet/docs#11931]
**Help us make content visible**

- large pages .net core
- large pages coreclr
- huge pages .net core
- huge pages coreclr
- super pages .net core
- super pages coreclr

**Describe the new topic**

Large Pages in .NET Core

- Talk about what large pages are and how they help improve performance
- How to enable large pages in .NET Core
- Windows specific - acquiring `SeLockMemoryPrivilege`
- Linux specific - allocating the huge pages in the virtual file system
- macOS specific - need to research I don't know much
- Diagnosing startup issues like when the pages are unavailable due to memory fragmentation
- Recommendations on running this on server environments.
- Some discussion about GCHeapHardLimit (e.g. that the 2X the hard limit will be committed)
- Document that memory dump sizes will become larger since the memory is committed

#### EDIT 05/21/2019

- On Windows, since large page memory is not pageable it doesn't show up in the "usual" places (task manager, Windows API requesting memory info related to working set, i.e. private bytes reflect the commit charge accurately.)
- GC Heap Hard Limit calculator which needs to take into account number of cores, size requested and the fact that number is applied to each of the SOH and LOH

#### EDIT 05/28/2019

- Document that Large Pages can affect startup time of the application as the OS tries to find large pages, potentially running a defrag. Furthermore, zero'ing of the memory can take a considerable amount of time (~50ms per GB on a modern processor). All of this happens in the context of the kernel so CPU investigations only show this behavior when looking at a system view.

#### EDIT: ADDED BY ADEGEO
FYI current Garbage Collection settings (settings, not conceptual information) for .NET Core are described in https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj (bad place to describe it really)

**Comment by mjsabby** [comment]
The above is an outline that needs to be fleshed out. @Maoni0 @janvorli feel free to add to the outline.

**Comment by Maoni0** [comment]
sounds good; could also talk about using HW counters to monitor the TLB misses during steady state.

**Comment by mairaw** [comment]
Would this belong here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/memory-management-and-gc?

**Comment by Maoni0** [comment]
I think this should belong here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals where it mentions VirtualAlloc in "the managed heap" section.
