### ISSUE TITLE
can't install Microsoft.WindowsDesktop.App shared runtime

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/docs#11943]
this install script lets you install the `Microsoft.NETCore.App` and `Microsoft.AspNetCore.App` shared runtimes but not the `Microsoft.WindowsDesktop.App` shared runtime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your comment @stevenbrix. @KathleenDollard @johnbeisner can you comment on this feedback about using the dotnet-install scripts to install the Microsoft.WindowsDesktop.App shared runtime? Is that being worked on already?

**Comment by KathleenDollard** [comment]
@dsplaisted

**Comment by dsplaisted** [comment]
We have the following work item which tracks adding this support: https://github.com/dotnet/cli/issues/11115

Thanks,
Daniel

**Comment by mairaw** [comment]
Thanks @dsplaisted. I'll leave this in our backlog to update the article once the scripts have added the support then.
