### ISSUE TITLE
When is the custom attributes constructor called, and by whom?

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#11950]
Can't find any info on when a constructor of a custom attribute class is called, and by whom it's called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a62174c-7cdd-54b7-6740-49caf6d5b043
* Version Independent ID: be1f8622-f6ea-5da9-d038-a4459b94c671
* Content: [Retrieving Information Stored in Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/retrieving-information-stored-in-attributes)
* Content Source: [docs/standard/attributes/retrieving-information-stored-in-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/retrieving-information-stored-in-attributes.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hello!

This is answered on stackoverflow: https://stackoverflow.com/questions/12196647/when-are-attribute-instances-created

I'm going to close this issue. Thanks.
