### ISSUE TITLE
Replace "default constructor" with "parameterless constructor"

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#11957]
## Replace "default constructor" with "parameterless constructor"

For background, see #10517 and #11945 

The term "default constructor" is confusing because:
- It is similar to "implicit default constructor".
- It can be confused with a constructor that has default arguments.

It should be replaced with "parameterless constructor". This change should be made in:

- [ ] The Visual Basic documentation.
- [ ] The Managed Reference documentation (in dotnet/dotnet-api-docs).
- [ ] The .NET Guide.

**Comment by keysangyonthan** [comment]
> ## Replace "default constructor" with "parameterless constructor"
> For background, see #10517 and #11945
> 
> The term "default constructor" is confusing because:
> 
> * It is similar to "implicit default constructor".
> * It can be confused with a constructor that has default arguments.
> 
> It should be replaced with "parameterless constructor". This change should be made in:
> 
> * [ ]  The Visual Basic documentation.
> * [ ]  The Managed Reference documentation (in dotnet/dotnet-api-docs).
> * [ ]  The .NET Guide.

Where are the documents, I can't find "default constructor" anywhere in the docs I have seen, can you please provide more information and directory. Thanks

**Comment by alx168** [comment]
I'll do it.
