### ISSUE TITLE
Create "History of C#" topic

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1195]
We should create a "History of C#" section that provides an overview of each C# version. This would be a nice complement to the "What's new" topics, and the current "What's new" topics would provide content for this section in the future.

It should go in the C# Guide, near the What's new section.

/cc @madstorgersen @MeiChin-Tsai

**Comment by lextm** [comment]
That's going to be great. And what about history of .NET? I built [a timeline for .NET](http://corefx.strikingly.com/), but not sure if it helps

**Comment by svick** [comment]
[The History section of Wikipedia's C# article](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#History) could help with this.

**Comment by BillWagner** [comment]
@MeiChin-Tsai and also referenced this Java article as a good concept: https://en.wikipedia.org/wiki/Java_version_history

**Comment by BillWagner** [comment]
This would be great source material.  Thanks @gafter 

https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md

**Comment by pkulikov** [comment]
The current version of docs has the C# history article added in September 2017:
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history

**Comment by BillWagner** [comment]
@pkulikov Let's make the task to look at the reference from the csharplang repo and make sure nothing is missing from the topic you noted.  If nothing is missing, we can close this.
