### ISSUE TITLE
How access target type in custom attributes constructor?

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#11951]
I can't find any information on how you know which type, property and so on the custom attribute is applied to from within the constructor of the custom attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a62174c-7cdd-54b7-6740-49caf6d5b043
* Version Independent ID: be1f8622-f6ea-5da9-d038-a4459b94c671
* Content: [Retrieving Information Stored in Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/retrieving-information-stored-in-attributes)
* Content Source: [docs/standard/attributes/retrieving-information-stored-in-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/retrieving-information-stored-in-attributes.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@Thraka were you planning to address that yourself last month?

**Comment by Thraka** [comment]
Sorry, I must have accidentally marked this with the 3 other issues that were opened on the article at the same time 😄

I think the answer in #11950 is kind of related. It links to https://stackoverflow.com/questions/12196647/when-are-attribute-instances-created. This answer explains that attributes are created when you look for them from the outside, already knowing the type or member you're accessing. You wouldn't be looking at this information inside the constructor.
