### ISSUE TITLE
Reference Folder does not exist under GettingStartedHost

### ISSUE THREAD

**Issue by DKlaudt** [dotnet/docs#11953]
There is no reference folder under the GettingStartedHost project and cannot add the reference below. In VS 2019
In the Add Reference window, under Assemblies on the left side of the window, select Framework.

Select System.ServiceModel, and then select OK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8cbb16-05b1-a5f2-9031-1d7beb52efea
* Version Independent ID: 98092a9f-c19a-cca9-75d6-75b9c3d4cc0b
* Content: [Tutorial: Host and run a basic Windows Communication Foundation service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-host-and-run-a-basic-wcf-service#feedback)
* Content Source: [docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for your feedback @DKlaudt and apologies on the delay for getting this triaged. This item is on our backlog.
@HongGit to comment on any plans to update this to VS 2019. The article should also be more clear on what are the prerequisites.
