### ISSUE TITLE
Instructions not clear

### ISSUE THREAD

**Issue by jjclayborn** [dotnet/docs#11958]
On the page "modify list contents" it says to "Add the following code below the code you've already written:" but it doesn't say where. If I take this instruction literally and add this code at the end of the stuff I wrote on the "create lists" page, then there are two different sets of outputs, and I'm pretty sure that's not what is intended. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Data collections - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @jjclayborn 

I've added to the next sprint to update this.
