### ISSUE TITLE
Missing code snippet

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#11967]
2nd code block under **Ref locals and returns** is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [What's New in C# 7.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I'll file a bug for the eng team as well as @Thraka takes care of the root cause. OPS should flag bad snippet tags.
