### ISSUE TITLE
'DataOperationsCatalog' does not contain a definition for 'TrainTestSplit'

### ISSUE THREAD

**Issue by binishvbabu** [dotnet/docs#11970]
```
 IDataView dataView = mlContext.Data.LoadFromTextFile<SentimentData>(_dataPath, hasHeader: false);
 TrainTestData splitDataView = mlContext.Data.TrainTestSplit(dataView, testFraction: 0.2);
```
I am trying to do a sentiment analysis and trying to get TrainTestSplitData. Here I am getting an error.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'DataOperationsCatalog' does not contain a definition for 'TrainTestSplit' and no accessible extension method 'TrainTestSplit' accepting a first argument of type 'DataOperationsCatalog' could be found (are you missing a using directive or an assembly reference?)

I am following this tutorial- https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis

**Comment by JRAlexander** [comment]
What version of ML.NET are you using?

**Comment by binishvbabu** [comment]
> What version of ML.NET are you using?

@JRAlexander, I was using **0.11** version of ML.Net which I installed using Nuget package. Now I added **1.0.0-preview** using command prompt and solved the issue. Thanks for asking the right question.

the command I used-
`dotnet add package Microsoft.ML --version 1.0.0-preview`

**Comment by JRAlexander** [comment]
Glad it's resolved. Have a good day!
