### ISSUE TITLE
Try.NET link doesn't work

### ISSUE THREAD

**Issue by ashleyNoDeal** [dotnet/docs#11979]
the Try.NET link doesn't work . Just links to a empty white page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d710feeb-8f03-b211-a070-155938929d6b
* Version Independent ID: c980ea8e-ffb4-fbb1-1761-292858616cdd
* Content: [C# foreach statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in#feedback)
* Content Source: [docs/csharp/language-reference/keywords/foreach-in.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/foreach-in.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Ping @jonsequitur 

The samples on this page that use `Span<T>` fail because `Span<T>` is not found.  Other samples work correctly. 

Do you have insight on how we should fix this one?

**Comment by mairaw** [comment]
The issue reported here is different than what you're stating @BillWagner and it's very odd (although the samples are also broken and need to be fixed).

The issue is that when you click on the link that takes you to https://try.dot.net/, the page opens blank.

**Comment by jonsequitur** [comment]
@BillWagner We would have to set up a custom Try .NET package on the server or modify the default package to include `System.Memory`. 

@mairaw The link issue will take some more investigation. I suspect there's JavaScript running in the page that's falling afoul of some security mechanism on the Try .NET site. In any case, I think the link should possibly go here instead: https://dotnet.microsoft.com/platform/try-dotnet, which would make this moot.

**Comment by BillWagner** [comment]
@jonsequitur I think adding `System.Memory` would make sense.  I can think of a number of page where using `Span<T>` would be useful (stackalloc, ref locals, and so on...).  

Should I add an issue at dotnet/try?

**Comment by jonsequitur** [comment]
That sounds good. Thanks!
