### ISSUE TITLE
MethodImplAttribute with MethodImplOptions.Synchronized

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#11978]
1) "You can also decorate a method with a MethodImplAttribute and MethodImplOptions.Synchronized"

2) "Do not lock the type ... in order to protect static methods. Similarly, do not use this ... to lock instance methods"

Here's the description of the MethodImplOptions.Synchronized member:
Static methods lock on the type, whereas instance methods lock on the instance.
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netframework-4.8

Aren't 1) and 2) doing the same thing? If so, why the former is recommended while the latter is not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d747d4-9377-7cd7-8298-33dba6ebdf28
* Version Independent ID: ebe45308-f267-3f78-d4ea-1b1a71627ff4
* Content: [Synchronizing Data for Multithreading](https://docs.microsoft.com/en-us/dotnet/standard/threading/synchronizing-data-for-multithreading#feedback)
* Content Source: [docs/standard/threading/synchronizing-data-for-multithreading.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/synchronizing-data-for-multithreading.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@Anipik Can you answer this question?
