### ISSUE TITLE
Startup event order is different in Tablet Mode

### ISSUE THREAD

**Issue by markwaterman** [dotnet/docs#11976]
Form.Activated fires *before* Form.Load when Windows 10 is in Tablet Mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3a80d-9468-0283-435b-f45f4827b920
* Version Independent ID: c879f822-8677-5e20-bcc7-52e1595d8883
* Content: [Order of Events in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/order-of-events-in-windows-forms#feedback)
* Content Source: [docs/framework/winforms/order-of-events-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/order-of-events-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@OliaG Can you investigate this?

**Comment by OliaG** [comment]
@merriemcgaw is this expected? Should we update docs or create an issue in our repo?

**Comment by markwaterman** [comment]
Thanks for investigating. Somebody on CodeProject did a more thorough analysis [here](https://www.codeproject.com/Articles/1254193/Win10-TabletMode-WinForms-Net-Form-Event-Order), so it looks like I'm not the first to notice this.

**Comment by Thraka** [comment]
Assigning the issue to @merriemcgaw to wait for feedback.

**Comment by merriemcgaw** [comment]
@dreddy-work when you have some time can you debug into it and see what is making us change the order of events? It seems like this isn't a regression, but I'd really like to understand why.

**Comment by dreddy-work** [comment]
sure. I currently heads down on the designer work. hopefully get to this early next week.

**Comment by Thraka** [comment]
@dreddy-work ping

**Comment by dreddy-work** [comment]
Sorry, i was on vacation and overlooked this. Will take a look sometime today/tomorrow and update  this thread.

**Comment by dreddy-work** [comment]
Is this to document only?

**Comment by merriemcgaw** [comment]
Unless we get some strong feedback from customers that call this a major problem I think documenting only is just fine.

**Comment by merriemcgaw** [comment]
We can simply add a note that this is the case. I don't foresee us finding a way to change that - it's coming from Windows at this point.
