### ISSUE TITLE
Testing code example found here causes StackOverflowException : https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#other-function-members 

### ISSUE THREAD

**Issue by LiveToLearnRo** [dotnet/docs#11981]
Actually testing code example found here causes StackOverflowException : https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#other-function-members. 

Details : 

List<T> class in the example overrides operator ==
        public static bool operator ==(List<T> a, List<T> b)
        {
            return Equals(a, b);
        }

In Equals function there are a couple of null checks which simply send you back to the overriden == operator ... which just sends you back to the Equals function...and so on.

        static bool Equals(List<T> a, List<T> b)
        {
            if (a == null) return b == null;
            if (b == null || a._count != b._count) return false;
            for (int i = 0; i < a._count; i++)
            {
                if (!object.Equals(a._items[i], b._items[i]))
                {
                    return false;
                }
            }
            return true;
        }

If one creates a simple unit test from the Test code example found here: 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#operators  one will get a StackOverflowException.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @MadsTorgersen @agocke 

Should I fix this in the spec introduction? This section has been removed from the ECMA spec as of version 5.0.

**Comment by kinglionsz** [comment]
The code into the loop to die: “own goal”  🔄👎😥

**Comment by kinglionsz** [comment]
please update the code.[here is  ok.](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#other-function-members)

`
static bool Equals(List<T> a, List<T> b)
    {
        //if (a == null) return b == null;                            // The code into the loop to die: “own goal”👎😥
        //if (b == null || a.count != b.count) return false;
        //for (int i = 0; i < a.count; i++)
        //{
        //    if (!object.Equals(a.items[i], b.items[i]))
        //    {
        //        return false;
        //    }
        //}
        //return true;

        if (Object.ReferenceEquals(a, null)) return Object.ReferenceEquals(b, null);
        if (Object.ReferenceEquals(b, null) || a.count != b.count)
            return false;
        for (int i = 0; i < a.count; i++)
        {
            if (!object.Equals(a.items[i], b.items[i]))
            {
                return false;
            }
        }
        return true;
    }
`

<img width="907" alt="equal-ok" src="https://user-images.githubusercontent.com/51827261/64918190-8fa91080-d7cd-11e9-8885-4bf05a53ba47.png">
