### ISSUE TITLE
Suggestion about the use of TRIM

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11987]
@onieto07 commented on [Mon Apr 22 2019](https://github.com/dotnet/docs.es-es/issues/125)

En el ejemplo de uso de TRIM, se debería poner un punto al final de las oraciones para que se pueda visualizar bien el efecto de las diferentes sintaxis de TRIM, retomando el ejemplo mostrado podemos poner:

string greeting = "      Hello World!       ";
Console.WriteLine($"[{greeting}].");

string trimmedGreeting = greeting.TrimStart();
Console.WriteLine($"[{trimmedGreeting}].");

trimmedGreeting = greeting.TrimEnd();
Console.WriteLine($"[{trimmedGreeting}].");

trimmedGreeting = greeting.Trim();
Console.WriteLine($"[{trimmedGreeting}].");

Con este punto podemos ver el efecto de las diferentes variantes de trim sobre la cadena al ver desplazarse el punto final en la pantalla.

Saludos,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hola mundo: tutorial interactivo de introducción a C#](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the user is making a suggestion on the example code:

Rough translation:

In the example of using TRIM, a period should be placed at the end of the sentences so that the effect of the different TRIM syntaxes can be clearly visualized, returning the example shown we can put:

```
string greeting = "Hello World!";
Console.WriteLine ($ "[{greeting}].");

string trimmedGreeting = greeting.TrimStart ();
Console.WriteLine ($ "[{trimmedGreeting}].");

trimmedGreeting = greeting.TrimEnd ();
Console.WriteLine ($ "[{trimmedGreeting}].");

trimmedGreeting = greeting.Trim ();
Console.WriteLine ($ "[{trimmedGreeting}].");

```

With this period we can see the effect of the different variants of trim on the chain when watching the ending period on the screen.

Regards,

**Comment by BillWagner** [comment]
Thanks @CeciAc and @onieto07 for bringing this to our attention.

I've added it to our backlog, and we'll address this when we next update this article.

**Comment by DWAK-ATTK** [comment]
I don't get it.  The brackets show you the effect of Trim().  Why do we need two trailing characters?

**Comment by AnotherBlob** [comment]
Completely new on C# but... I don't get why you need to have square brackets at all, the example works just fine without them.
There's also no explanation why you need square brackets for this example (even though you apparently don't?)...

**Comment by aprilspeight** [comment]
The square brackets are included to help visualize the white space. Scott and Kendra provides an explanation in the C# video series on Channel 9. You can watch here starting at 3:56: https://channel9.msdn.com/Series/CSharp-101/CSharp-The-Basics-of-Strings

The brackets are used to show you where the whitespace starts and end. You could essentially replace the brackets with a different character (such as *).
