### ISSUE TITLE
Thread.Suspend is obsolete

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#11980]
The Thread.Suspend method is marked obsolete in https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.suspend?view=netframework-4.8

May be it makes sense to mention this here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb817bbc-df5f-6c70-322b-6e9ed10a7aba
* Version Independent ID: 9b1137da-f8a4-8419-334a-0ecd5b3b029e
* Content: [Thread.Suspend, Garbage Collection, and Safe Points](https://docs.microsoft.com/en-us/dotnet/standard/threading/thread-suspend-garbage-collection-and-safe-points)
* Content Source: [docs/standard/threading/thread-suspend-garbage-collection-and-safe-points.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/thread-suspend-garbage-collection-and-safe-points.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

@rpetrusha Assigning you since this is this probably needs a rewrite to use the suggested replacements such as the Monitor class.

@user2150 Thanks again!

**Comment by pkulikov** [comment]
@Thraka @rpetrusha what about merging (and possibly editing) the whole article into the API reference page for the `Thread.Suspend` method (because it's about the internals of this method)? After that the page can be removed from the docs with the redirect to the API page.

**Comment by rpetrusha** [comment]
I agree, @pkulikov. This entire article is really about Thread.Suspend and the consequences of calling it, so it's best placed in the API reference. I'll keep this assigned to myself, but if you'd like to open the PRs to remove this article and move its content, please assign the issue to yourself.

**Comment by pkulikov** [comment]
@rpetrusha first PR is submitted: dotnet/dotnet-api-docs#2368
