### ISSUE TITLE
Bug in sample code for detecting .NET 4.8

### ISSUE THREAD

**Issue by smarcantonio** [dotnet/docs#11982]
The "Release DWORD" table shows the following for the new .NET 4.8 release:
"On Windows 10 May 2019 Update: 528040
On all others Windows operating systems (including other Windows 10 operating systems): 528049"

The sample code for identifying .NET 4.8 uses the larger of these two numbers:
```
if (releaseKey &gt;= 528049)
            return "4.8 or later";
```

This will therefore fail on Windows 10 May 2019 Update.

It should be like this:
```
if (releaseKey &gt;= 528040)
            return "4.8 or later";
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
We'll get that fixed. Thanks for letting us know @smarcantonio.

**Comment by rpetrusha** [comment]
Thanks for reporting this, @smarcantonio, and thanks for fixing it so promptly while I was on vacation, @mairaw!
