### ISSUE TITLE
code formatting issue

### ISSUE THREAD

**Issue by jack147527** [dotnet/docs#11997]
There is one formatting issue in docs [How to: Parse Strings Using String.Split](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/parse-strings-using-split).
        string[] separatingChars = { "<<", "..." };  

        string text = "one<<two......three<four";  
        System.Console.WriteLine("Original text: '{0}'", text);  

        string[] words = text.Split(separatingChars, System.StringSplitOptions.RemoveEmptyEntries );  
        System.Console.WriteLine("{0} substrings in text:", words.Length);  

        foreach (var word in words)
        {
            System.Console.WriteLine(word);
        }
Should be like this

string text = "one<<two......three<four";  
System.Console.WriteLine("Original text: '{0}'", text);  

string[] words = text.Split(separatingChars, System.StringSplitOptions.RemoveEmptyEntries );  
System.Console.WriteLine("{0} substrings in text:", words.Length);  

foreach (var word in words)
{
 System.Console.WriteLine(word);
 }

This code should be in the same format as the previous two pieces of code. There should be no spaces before each line of code.

**Comment by mairaw** [comment]
Thanks for your feedback @jack147527. This was fixed in https://github.com/dotnet/samples/pull/847.
