### ISSUE TITLE
What does "throw from the implementation and offer capability APIs" mean?

### ISSUE THREAD

**Issue by kdawg14** [dotnet/docs#11994]
In the following section from https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting (with emphasis added on the part I'm not sure on):

>  CONSIDER targeting .NET implementations in addition to .NET Standard.
>
> Targeting .NET implementations allows you to call platform-specific APIs that are outside of .NET Standard.
>
> Do not drop support for .NET Standard when you do this. _Instead, throw from the implementation and offer capability APIs._ This way, your library can be used anywhere and supports runtime light-up of features.

I believe I understand the concept (define a common API, but potentially have different concrete implementations depending on the target), but I was wondering specifically about the wording in "throw from the implementation and offer capability APIs," as that doesn't seem to really jive well with what I thought was being recommended; throw what from what implementation, and what's a capability API and how does it differ from any other type of API?   Am I understanding correctly the gist of what's being recommended, or is there something else here that I'm not getting?

Thanks!

edit by @mairaw: add article details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@JamesNK @terrajobst can one of you comment on this? Maybe we have an example we can share from our own code?

**Comment by JamesNK** [comment]
I think an example would be useful. I don't know one from corefx. Immo probably knows of a good example.

**Comment by mairaw** [comment]
Thanks @JamesNK. @terrajobst can you help?

**Comment by deepak-agrwl** [comment]
Could anyone please comment on this ?

**Comment by henke37** [comment]
Looks clear enough to me, if you read the earlier section that has this text:
> Platform-specific APIs will fail on other platforms. For example, Microsoft.Win32.Registry will succeed on Windows and throw PlatformNotSupportedException when used on any other OS.

That both gives an example of an API that throws and states what to throw. The only thing missing is the capability api.

**Comment by terrajobst** [comment]
The idea is to offer a Boolean API that allows you write code that checks for that up front. For example, ideally `Registry` would have a static Boolean property `IsSupported` so you can avoid having to catch the exception or (worse) trying to do the check yourself (like checking for the OS). I'll submit a PR.

**Comment by terrajobst** [comment]
Submitted #13824 to address this.
