### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kyle0418** [dotnet/docs#12003]
Please check if there is a spelling error of "boxe" in the following comment:

        // All-purpose method for displaying a line of text in the
        // text boxe.
        private void DisplayLine(string line)
        {
            TextBoxOutput.AppendText(line);
            TextBoxOutput.AppendText(Environment.NewLine);
        }

Related doc:
[How to: Handle User Input Events in Windows Forms Controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-handle-user-input-events-in-windows-forms-controls)

**Comment by Thraka** [comment]
Thank you for opening this issue. Looks like it just got fixed. Thanks again!
