### ISSUE TITLE
dotnet new -i FILE_SYSTEM_PATH / dotnet new -u undocumented behaviour

### ISSUE THREAD

**Issue by kierenj** [dotnet/docs#12002]
The page here says, "The FILE_SYSTEM_DIRECTORY is the project folder containing the project and the .template.config folder".

However, it looks like I can `dotnet new -i ANY_FOLDER_HERE`, and all subfolders will be searched, and any templates found will be installed?

Furthermore, I cannot `dotnet new -i X` and then `dotnet new -u X`.  For uninstallation, the path must be the full/absolute/canonical path, not a relative one.

Further-furthermore, templates automatically installed from a parent folder can only be uninstalled using the canonical path of the parent folder - not their individual folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/custom-templates.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by RobertAcksel** [comment]
Confirmed. There is not even a message on the console which indicates what actually happens. In my case i see the usage appearing indicating that something went wrong. But there is no actual error message just the usage. So absolutely no indication of whats going on in this cases for the user.

**Comment by Thraka** [comment]
@RobertAcksel I know what you mean. The `dotnet` template commands aren't very helpful when there is a problem. There is a discussion about them over at https://github.com/dotnet/templating/issues/1750
