### ISSUE TITLE
Although I have granted the current user corresponding permiss, on my client side, it still prompts me that the process doesn't have the right access rights for the certificate private key.

### ISSUE THREAD

**Issue by YonglianQian** [dotnet/docs#12000]
Hi Product owner,
I ran into a problem when I use a certificate to authenticate the client.
On two virtual machines, I built a WCF application using certificates to authenticate each other based on message security. I created a WCF application on a vabqia593vm host, and hosted it on IIS, as shown in the above official example. 
I consume this WCF application in the console program by adding a service reference on the vabqia864vm host. 
The configuration file refers fully to the above official page configuration. 
Also, I used Powershell command New-selfsignedcertificate to create two self-signed certificates for each machine. 
New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -DnsName "vabqia593vm"
New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -DnsName "vabqia864vm" -KeyUs
age KeyEncipherment,DigitalSignature

On both certificates, I added some users to manage private key, such as Everyone, IIS_IUSRS,network service, in the certificate management interface(certlm.msc), but on the client side, the console application still prompted that the process might not have permission to access the certificate private key. 
Feel free to let me know if you need more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b00b30f3-a957-1073-1f86-37db1732b26f
* Version Independent ID: 76e7b7b4-058a-9668-ce02-c8811e3ba01d
* Content: [Message Security with a Certificate Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/message-security-with-a-certificate-client#feedback)
* Content Source: [docs/framework/wcf/feature-details/message-security-with-a-certificate-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/message-security-with-a-certificate-client.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by YonglianQian** [comment]
I didn’t solve the problem, the problem still exists. I am the moderator of the WCF MSDN forum (Microsoft service vendor), I also answer some questions related WCF on StackOverflow, I got stuck on this question for a long time, please give me some advice on this.

**Comment by Lxiamail** [comment]
@yujayee can you help with this question?

**Comment by yujayee** [comment]
@YonglianQian Could you try to see if adding the following line in your web.config works? The target framework should be 4.6.2 or above.
```
  <system.web>
    <httpRuntime targetFramework="4.7"/>
  </system.web>
```

**Comment by YonglianQian** [comment]
@Lxiamail  Thanks for your time and patience. @yujayee , It works, you are too tough. How would you know that?

**Comment by yujayee** [comment]
Glad that helps. Certificates created by powershell cmdlet are CNG certificates which were not supported at the beginning. When we fix this issue to support CNG, we quirk the code change to make it default turned on for framework version 4.6.2 and above.

**Comment by yujayee** [comment]
If there are no more questions to this issue, shall we close it?
