### ISSUE TITLE
Contributing guide needs to explain including snippets

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1204]
The current contributing guide explains how to include code using the 

```csharp
// code here
```

syntax.  However, we don't explain (and certainly don't say we prefer) using the snippet include syntax.  

We need to update the contributing guide, or make a separate short doc for code, that explains how we'd prefer to see code.

/cc @mairaw

**Comment by mairaw** [comment]
We have added some guidelines to the style guide but we still need to talk about the snippet inclusion guidelines such as line highlighting, using ranges, line numbers, etc.

**Comment by BillWagner** [comment]
Closing this. It's in the contributor guide, and future work will be in the [global contributor guide](https://github.com/MicrosoftDocs/Contribute)
