### ISSUE TITLE
Character issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/docs#12046]
Please check if there is extra character '_' in the following code.

    MessageBox.Show("Good morning " + User + ". You are connected to " _  
    + Domain)  

Here is the correspond document:
[System Information and Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/system-information-and-windows-forms).

**EDIT**: Added docs data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecf06c45-d775-5e56-7674-f85e81c5493a
* Version Independent ID: 6fde8a60-7ac8-c6fc-ad6b-0a5729f2448d
* Content: [System Information and Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/system-information-and-windows-forms)
* Content Source: [docs/framework/winforms/advanced/system-information-and-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/system-information-and-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @kyle0418 

You are correct the `_` should be removed in the C# sample.

Do you want to submit a PR for this fix?  (click the "edit" button on the document, and that takes you to the source on GitHub. You can edit in the browser, and save as a PR.)

If not, we'll address this.

Thanks again for bringing it to our attention.
