### ISSUE TITLE
Missing Step to Save Model and modification to _modelPath

### ISSUE THREAD

**Issue by Amorpheuz** [dotnet/docs#12048]
The step for saving model seems to be missing from this tutorial. I found one in Iris Flowers one though and followed that, should add it here. 

Also would modify _modelPath to be:
Path.Combine(Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.ToString(), "Data", "Model.zip");

As "Environment.CurrentDirectory" points to Solution\bin\debug\netcoreapp2.2\(folder\file) rather than in the data folder for vs2019... or add a note that it will be found in the bin directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @Amorpheuz!  We'll add a note about the bin directory.

**Comment by JRAlexander** [comment]
@Amorpheuz - Here's the link to the recently published save and load how-to article: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net
Closing this as I believe it's resolved. Please reopen if that's not the case. Thanks!
