### ISSUE TITLE
Broken links in dotnet test protocol article

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1205]
The article [.NET Core CLI test communication protocol](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/test-protocol) contains many links to files in the CLI repo. As far as I can tell, those links were broken by https://github.com/dotnet/cli/pull/4456, which removes project.json-related code from CLI.

Does this mean that in the msbuild-based future, this article should be deleted? Should something be done in the meantime, to make the links not broken (like linking to the commit just before https://github.com/dotnet/cli/pull/4456)?

**Comment by mairaw** [comment]
@blackdwarf do you know?

**Comment by blackdwarf** [comment]
@svick we should probably change the links to not point to rel/1.0.0 but to rel/1.0.0-preview2.

In Preview 3, the `dotnet test` has been significantly changed and the test protocol is different. Until I have a full document describing it, I think that for Preview 3 bits we should remove it (which is what I did in my PR #1233 ).
