### ISSUE TITLE
Wrong information about ListBoxItem implementing ICommandSource

### ISSUE THREAD

**Issue by TheFreezingChicken** [dotnet/docs#12057]
Quoting the first lines in the "Example" section: "WPF provides a number of classes which implement ICommandSource, such as Button, MenuItem, **and ListBoxItem**." and later "**A ListBoxItem invokes a command when it is double clicked**.".
These statements seem to be not true, as ListBoxItem does NOT implement ICommandSource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98816e48-1795-7dd1-8a2c-126452788282
* Version Independent ID: 35122282-6ddd-7c5f-caf8-9a9dade05e80
* Content: [How to: Implement ICommandSource](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-implement-icommandsource#feedback)
* Content Source: [docs/framework/wpf/advanced/how-to-implement-icommandsource.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-implement-icommandsource.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @TheFreezingChicken. I've fixed this in PR #16141. The change should be live within a day.
