### ISSUE TITLE
Value doesn't exist

### ISSUE THREAD

**Issue by virtualgithub** [dotnet/docs#12062]
"If you want to use implicit validation for a control, you must set that control's AutoValidate property to true." true is not a valid value for that property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a159347-c930-08cf-dfaf-aadb21db0a2b
* Version Independent ID: a3ae3e93-c90b-fbe3-961b-bfa0bbebdb3d
* Content: [User Input Validation in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/user-input-validation-in-windows-forms#feedback)
* Content Source: [docs/framework/winforms/user-input-validation-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/user-input-validation-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @virtualgithub for your feedback. This has been fixed and will be published live later today.
