### ISSUE TITLE
Code workflow image

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12079]
Can we make this picture a bit simpler. It's unclear in this description what are the various steps and which one comes first. Perhaps listing higher level steps
1. Prepare Data (1.1 Load Data 1.2 Extract Features)   will map to IDV
2. Build and Train (2.1 Train Model 2.2 Evaluate Model)  will map to IEstimator&lt;ITransformer&gt;
3. Run  (3.1 Model Consumption) will map to PredictionEngine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [How does ML.NET work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Can do @asthana86

**Comment by CESARDELATORRE** [comment]
Also remove HTML/XML "syntax" from the C# interface names, looks strange since it is C# not HTML/XML.
Just use CONSOLAS font. IT is clear that starting with 'I' is an interface. Then functions/methods like 'Fit()'

**Comment by JRAlexander** [comment]
Closing as I believe this is resolved.
