### ISSUE TITLE
Consistency: Machine Learning vs. Data Science. 

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12078]
ML.NET is specifically targeted for Applied machine learning problem, can we update this page to remove mention of data science and replace it with short videos which intro machine learning, in the absence of such material please use this channel 9 video:
https://www.youtube.com/watch?v=cCsOvzB3rK8

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23308b39-1791-d800-bb8a-9274787b2564
* Version Independent ID: 0f35fad6-2eee-0217-3308-bfb78d805c04
* Content: [What is machine learning? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/what-is-machine-learning)
* Content Source: [docs/machine-learning/what-is-machine-learning.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/what-is-machine-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @cjgronlund
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Closing this, as this article no longer contains this content.
