### ISSUE TITLE
Architecture 

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12080]
This might be a bit more verse for this page, but one piece of architecture perhaps might be worth a mention is that ML.NET as a framework is extensible and for DNN scenarios we have made TensorFlow ,ONNX operable within the same API set and concepts (e.g. estimators, transformers etc.)

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [How does ML.NET work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Good idea @asthana86

**Comment by jaymins93** [comment]
Hi , i want to use ML.Net in project and it uses data which i can not send over internet , i am aware ML.Net is offline processing the model and predicting results , but i can not find it on the web page mentioned , it is very useful for enterprise , can some one from Microsoft docs update the document or comment here that it is offline process it will really help.

**Comment by natke** [comment]
Resolved by #15714
