### ISSUE TITLE
 TransformerChain<TLastTransformer>

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12084]
Concepts introduced in this tutorial inconsistent with others. Concepts to introduce are IEstimator, ITransformer, IDV and PredictionEngine. Follow recommendation engine tutorial for reference. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
This should be resolved in the above PR.
