### ISSUE TITLE
What is Machine Learning?

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12081]
The applications of ML on this page in the first para make sense. What perhaps can be improved is why does a developer need ML, why can't they build logical (if/else) for performing predictions etc. 
A couple of examples we have used are: 
1. How do you write a function which predicts the price of a shirt based upon the description of the shirt? 

2. How do you write a function which detects whether a particular image has a human face in it or not? 

Even though you might not know where to start, what we do have is examples (i.e. images with human faces, and images with no human faces). Machine Learning algorithms allow learning from these examples and developing a function or a Machine Learning model which can then predict outcomes based upon the input fed into it. 

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23308b39-1791-d800-bb8a-9274787b2564
* Version Independent ID: 0f35fad6-2eee-0217-3308-bfb78d805c04
* Content: [What is machine learning? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/what-is-machine-learning)
* Content Source: [docs/machine-learning/what-is-machine-learning.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/what-is-machine-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @cjgronlund
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Addressed by #16809
