### ISSUE TITLE
Improve readibility by replacing text with images 

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12083]
Select the appropriate machine learning algorithm
Classification algorithm

These sections can be improved by using images versus text currently. My hypothesis would be it would help improve readibility. The other tutorials Sentiment Analysis and Recommendation are already using this technique. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
This should be resolved in the above PR.
