### ISSUE TITLE
Can we /reference COM objects?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [dotnet/docs#12088]
Because of cracks in the audio https://stackoverflow.com/questions/47951091 I need to use COM reference to `Microsoft Speech Object Library` - how can I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca28d0b-c090-90c3-5211-9f0c0642e441
* Version Independent ID: 1fa89150-3060-92aa-9418-9b67a6589b89
* Content: [-reference (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/reference-compiler-option#feedback)
* Content Source: [docs/csharp/language-reference/compiler-options/reference-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/reference-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@vitaly-zdanevich Thanks for raising this question.  You should find samples and instructions in our section on [interop](https://docs.microsoft.com/dotnet/csharp/programming-guide/interop/).

I'll close this as an answered question.
