### ISSUE TITLE
Document DOTNET_BUILD_VERSION env var

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#1208]
I don't see the DOTNET_BUILD_VERSION env var documented anywhere. The value of this env var will be substituted in for the `*` when you have a `-*` in you project version.

**Comment by mairaw** [comment]
Thanks @danroth27. I wasn't aware of that env var. It should probably go [here](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md#environment), right?

@blackdwarf, are we missing any other env vars?

**Comment by danroth27** [comment]
The .NET Core folks should probably decide how they want this documented. One idea is it could go with build, publish and pack where it discusses the --version-suffix option, which does something very similar.

**Comment by mairaw** [comment]
@danroth27 does this env var still exist? if so, i'd like to get it documented on my proposed location from before

**Comment by danroth27** [comment]
Not sure, @livarcocc do you know?

**Comment by livarcocc** [comment]
It does not.

**Comment by mairaw** [comment]
Thanks guys! Closing this issue then.
