### ISSUE TITLE
MapValueToKey not explained

### ISSUE THREAD

**Issue by asthana86** [dotnet/docs#12085]
MapValueToKey is not explained well. This section is a bit  complex to follow and understand: 

"
As we want to predict the Area GitHub label for a GitHubIssue, copy the Area column into the Label column. To do that, use the MLContext.Transforms.Conversion.MapValueToKey, which is a wrapper for the MapValueToKey transformation class. The MapValueToKey returns an EstimatorChain&lt;TLastTransformer&gt; that will effectively be a pipeline. Name this pipeline as you will then append the trainer to the EstimatorChain. Add the next line of code:
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Classify GitHub issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
I believe this is resolved with the above PR.
