### ISSUE TITLE
[IMPORTANT] Temporary default branch 

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#12094]
:warning: We have a temporary default branch we're targeting this week called **staging**.

We'll go back to the master default branch in a week and existing/new PRs will be merged to the staging branch throughout this week.

Publishing is also on hold except for a few [signed-off PRs](https://github.com/dotnet/docs/pulls?q=is%3Aopen+is%3Apr+label%3Asigned-off) and we'll resume publishing next week.

Apologies for any incovenience this may cause!

/cc @BillWagner @rpetrusha @Thraka @natke @luisquintanilla @JRAlexander @cartermp @mvelosop

**Comment by BillWagner** [comment]
Fixed in #12172
