### ISSUE TITLE
Error in "cMax" argument documentation

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/docs#12097]
"cMax = [in] The maximum size of the rImpls array."
Should this instead be "The maximum length of the rImpls array"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f4fab7-7d32-45c9-d772-d6773b52fe3d
* Version Independent ID: f45ee05d-fd6e-a897-617f-07b83db47768
* Content: [IMetaDataImport::EnumInterfaceImpls Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataimport-enuminterfaceimpls-method#feedback)
* Content Source: [docs/framework/unmanaged-api/metadata/imetadataimport-enuminterfaceimpls-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/metadata/imetadataimport-enuminterfaceimpls-method.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@tommcdon who do you think could help with this feedback for one of the metadata APIs?

**Comment by tommcdon** [comment]
@jeffschwMSFT is this owned by your team, if so can you take a look?
cc @davidwrighton

**Comment by jeffschwMSFT** [comment]
Thanks @r-ramesh for the feedback.  I agree, I think that the word "size" is ambiguous and not as correct as "length".  cMax is the maximum number of elements or the length of the array.
