### ISSUE TITLE
Bad example in GetHashCode

### ISSUE THREAD

**Issue by jackalvrus** [dotnet/docs#12091]
Hash codes should not be aggregated using simple XOR combination.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by douglasg14b** [comment]
@jackalvrus What is your proposed implementation?

**Comment by jackalvrus** [comment]
@douglasg14b  There are a number of well-designed algorithms out there. Here is an article that compares several (and demonstrates why XOR is not ideal): http://myeyesareblind.com/2017/02/06/Combine-hash-values/

These days I typically use `ValueTuple.GetHashCode` because it uses one of the good algorithms. For example:

```
public override int GetHashCode() {
    return (
        Prop1,
        Prop2,
        Prop3
    ).GetHashCode();
}
```

**Comment by douglasg14b** [comment]
Thanks! 

Would you consider it acceptable to instead use prime number multiplication?

**Example:**

```cs
public override int GetHashCode()
{
    unchecked
    {
        int hash = 13;
        foreach (object value in GetAtomicValues())
        {
            hash = hash * 23 + (value == null ? 0 : value.GetHashCode());
        }

        return hash;
    }
}
```

____________________________________________________________________

**LINQ Version:**

```cs
public override int GetHashCode()
{
    unchecked
    {
        return GetAtomicValues()
            .Select(x => x != null ? x.GetHashCode() : 0)
            .Aggregate(13, (result, item) => result * 23 + item);
    }
}
```

**Comment by mvelosop** [comment]
Hi @jackalvrus, @douglasg14b, thanks for your feedback,

Would some of you like to contribute a PR to the [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers/pulls/) to fix this?

Thanks.
