### ISSUE TITLE
Inverted Dependency Graph diagram

### ISSUE THREAD

**Issue by kaiza** [dotnet/docs#12102]
In the 'Compile Time' diagram on the left, shouldn't Class B reference Interface C? Why would Interface B reference Interface C?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829862b0-b51d-d4dd-d770-f875a588384f
* Version Independent ID: 4ab12fcc-7cc1-d40b-b5c4-d145fe25e98e
* Content: [Architectural principles](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/architectural-principles#feedback)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/architectural-principles.md](https://github.com/dotnet/docs/blob/staging/docs/standard/modern-web-apps-azure-architecture/architectural-principles.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Yeah, I think you're right. I'll get an update to it.
