### ISSUE TITLE
No need to check if a directory exists to create it

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/docs#12103]
In the first example, please remove the Exists() checking because CreateDirectory() is a safe method. It won't create a folder if it exists.

```csharp
if (!System.IO.Directory.Exists(targetPath))
{
    System.IO.Directory.CreateDirectory(targetPath);
}
```

See: https://stackoverflow.com/questions/9065598/if-a-folder-does-not-exist-create-it/9065716#9065716

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9502aff8-6d10-a8c9-1d9e-81a55eeed4cf
* Version Independent ID: 1c570d89-49a6-889f-08a5-8ef2d95f7f7e
* Content: [How to: Copy, Delete, and Move Files and Folders - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-copy-delete-and-move-files-and-folders)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-copy-delete-and-move-files-and-folders.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/file-system/how-to-copy-delete-and-move-files-and-folders.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

The sample is at https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_VBCSharp/csFilesAndFolders/CS/FileIteration.cs

Thanks again!
