### ISSUE TITLE
Overloads that differ by in, out, or ref

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#12105]
The page says, "You can't create overloads of a method that differ only in the presence of in, out, or ref." Yet it also talks about the case where "An overload exists that differs by the presence or absence of in." It's not clear which overloads are allowed and which are not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is a difficult concept, and the spec is the best language for it. We use the following language in the [language reference](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/ref#passing-an-argument-by-reference): 

> Members of a class can't have signatures that differ only by `ref`, `in`, or `out`. A compiler error occurs if the only difference between two members of a type is that one of them has a `ref` parameter and the other has an `out`, or `in` parameter. 

Two members are distinct if one of them has *none* of those modifiers.

We should add that language here.
