### ISSUE TITLE
Super helpfull!

### ISSUE THREAD

**Issue by bendras** [dotnet/docs#12113]
+    Thank you for this clear article describing how to enable autocomplete in PowerShell.
!    I'd like to see autocomplete enabled by default in future. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#feedback)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/staging/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
You're welcome! Thanks for commenting.

**Comment by AHLinJie** [comment]
![image](https://user-images.githubusercontent.com/10792685/69794827-edae9700-1205-11ea-9dc7-81c0732bb18a.png)

**Comment by Thraka** [comment]
@AHLinJie Please open up new issues.

You need to change your execution policy to allow scripts to run. `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine` see [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6#inputs) for more information.
