### ISSUE TITLE
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by jainmnsh** [dotnet/docs#12110]
Hello, I followed the document and it worked when a connection is made from the same server however if requests coming from a different machine in within same network then i get below error.

System.Net.WebException
  HResult=0x80131509
  Message=The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  Source=System.Web.Services
  StackTrace:
   at System.Web.Services.Protocols.WebClientProtocol.GetWebResponse(WebRequest request)
   at System.Web.Services.Protocols.HttpWebClientProtocol.GetWebResponse(WebRequest request)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
  
Inner Exception 1:
AuthenticationException: The remote certificate is invalid according to the validation procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f72fd38e-b65d-d059-1ce1-2e4e917b982f
* Version Independent ID: cd00b225-8f05-9146-bb71-0b0b3b7aeb64
* Content: [How to: Configure an IIS-hosted WCF service with SSL](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-configure-an-iis-hosted-wcf-service-with-ssl)
* Content Source: [docs/framework/wcf/feature-details/how-to-configure-an-iis-hosted-wcf-service-with-ssl.md](https://github.com/dotnet/docs/blob/staging/docs/framework/wcf/feature-details/how-to-configure-an-iis-hosted-wcf-service-with-ssl.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
@HongGit @mconnew can you help with this question?

**Comment by inikulshin** [comment]
Hi

I reproduced this one with 
`ServicePointManager.CheckCertificateRevocationList = true;`
and **expired** CRL

InnerException was 
HResult=0x80131501
Message=The remote certificate is invalid according to the validation procedure.

**Comment by mconnew** [comment]
@inikulshin, you need to look at the property ClientCredentials.ServiceCertificate.SslCertificateAuthentication. This will initially be null so you need to instantiate and set a new instance of [X509ServiceCertificateAuthentication](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.security.x509servicecertificateauthentication?view=netframework-4.8). There are multiple properties on this class to influence how the service certificate is validated. For example, you can change the revocation mode.
