### ISSUE TITLE
Small Issue in code

### ISSUE THREAD

**Issue by pwallner** [dotnet/docs#12116]
Change "Path=(Validation.Errors)[0].ErrorContent" to "Path=(Validation.Errors)/ErrorContent" to avoid errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81627319-aa78-1714-3aff-6ca7056a85a5
* Version Independent ID: 767c0a65-8b6b-0863-0e43-40d475f33908
* Content: [How to: Implement Binding Validation](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-binding-validation#feedback)
* Content Source: [docs/framework/wpf/data/how-to-implement-binding-validation.md](https://github.com/dotnet/docs/blob/staging/docs/framework/wpf/data/how-to-implement-binding-validation.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@pwallner did you mean to put the `/` in? I've never seen that in the xaml binding syntax.

**Comment by pwallner** [comment]
@thraka you are welcome
