### ISSUE TITLE
var no more

### ISSUE THREAD

**Issue by Delog-ru** [dotnet/docs#12111]
Please don't use "var" in tutorials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We use `var` in our samples when the context should make it clear the type of variables.

In this tutorial, we've met that standard. The use of `var` starts only later in the tutorial when the concepts have been discussed. 

I'll close this.
