### ISSUE TITLE
Access to local variables and passing parameters to lambda expressions

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12117]
"When you use a lambda expression to create a delegate, you have ACCESS TO ALL THE VARIABLES THAT ARE VISIBLE AT THAT POINT IN YOUR SOURCE CODE. However, in some cases, most notably within loops, a lambda doesn't capture the variable as expected. It only captures the final value, not the value as it mutates after each iteration. The following example illustrates the problem. It PASSES A LOOP COUNTER TO A LAMBDA EXPRESSION that instantiates a CustomData object and uses the loop counter as the object's identifier. As the output from the example shows, each CustomData object has an identical identifier."

1) Two different scenarios are confused:

case A: access in lambda expressions to the local variables in the enclosing scope (here the "final-value-capturing" issue does exist);

case B: passing parameters to lambda expressions (here everything is OK when the lambda uses the passed value which is not the case in the example).

2) In order to illustrate the case A, the authors announce an example which is supposed to use the case B.

3) But actually the example demonstrates the case A, not B, as the passed parameter (obj) is never used, and the value of the local variable from the enclosing scope (i) is captured instead.

4) In the second example the creation of object CustomData() {Name = i, CreationTime = DateTime.Now.Ticks} works but is redundant as it's enough to take the passed parameter value in the lambda, replacing the line
		var data = new CustomData() {Name = i, CreationTime = DateTime.Now.Ticks};
with
		var data = new CustomData() {Name = (int)obj, CreationTime = DateTime.Now.Ticks};

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050b2b8a-8b8d-c2de-f03d-b2ebb26a9c95
* Version Independent ID: 7d23f296-9a5e-ca0a-08c3-f718d0a90d94
* Content: [Task-based asynchronous programming - .NET](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming#feedback)
* Content Source: [docs/standard/parallel-programming/task-based-asynchronous-programming.md](https://github.com/dotnet/docs/blob/staging/docs/standard/parallel-programming/task-based-asynchronous-programming.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@BillWagner Can you determine what needs to be changed in the doc?
