### ISSUE TITLE
Why does the compile-time type matter, when using `is` for typechecking?

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#12120]
The description of the circumstances under which typechecking with `is` returns `true` should only relate to the runtime type, and not the compile-time type, e.g.:

&gt; The `is` statement is `true` if the runtime type of the instance at `expr` is:
&gt;
&gt; * the same as,
&gt; * inherits from, or
&gt; * implements
&gt; 
&gt; the _type_ type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3126aaa9-8f5f-04f3-2d75-96477b6273cd
* Version Independent ID: 3f4b3eac-11eb-2dd6-4f27-b24537367288
* Content: [is - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#feedback)
* Content Source: [docs/csharp/language-reference/keywords/is.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/language-reference/keywords/is.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The compile-time type matters because there are `is` expressions where the result is known to be `true` or `false` at compile time:

```csharp
var s = "abcd"; // compile time type is string
if (s is object)
    Console.WriteLine("this is known to be true at compile time").

var number = 25; // compile time type is int
if (number is string)
    Console.WriteLine("Never true.");
else
    Console.WriteLine("Known to be false at compile time.");
```

I'll close this as an answered question.
