### ISSUE TITLE
"cref" is not the only valid parameter - THIS DOCUMENTATION IS INCOMPLETE

### ISSUE THREAD

**Issue by dsorak** [dotnet/docs#12122]
Do you have any idea how frustrating incomplete documentation is to developers? I recently discovered that "langword" is also a valid parameter, as in: &lt;see langword="false" /&gt;  What else is there? PLEASE IMPROVE THIS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by dsorak** [comment]
Here is the more complete documentation: http://ndoc.sourceforge.net/content/tag_see.htm

**Comment by mairaw** [comment]
Thanks for your feedback @dsorak.  
For the href attribute, we have a discussion about it (see #4176) since VS doesn't show that as an option. But yes, we should at least add langword to this page.

**Comment by mairaw** [comment]
Moving to the backlog due to other high priority work at the moment. I'll put it back on a sprint, once I'm ready to start working on this.

**Comment by TobiasSekan** [comment]
Hello, 

When you extend the this documentation for `see langword` , please add the shortcut `CTRL+Space` for the auto-completion on langwords like `true`, `null` etc.

see https://github.com/dotnet/roslyn/issues/11489#issuecomment-289208450

thanks

**Comment by BillWagner** [comment]
reopening to address as part of the XML docs cleanup

**Comment by BillWagner** [comment]
Fixed in #24705
