### ISSUE TITLE
We're missing metrics for other supported MLTasks in ML.NET in addition to Binary-Classification, Multi-Class classification and Regression

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#12123]
I created this content for the CLI since it currently supports inary-Classification, Multi-Class classification and Regression. But if this page is targeting ML.NET as a whole, we need to add additional metrics here.

[AB#1588796](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588796)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d630b33e-2bb8-1535-8565-0608944b79ae
* Version Independent ID: a2d0bd27-61b8-7249-0af2-83cf10efcc55
* Content: [ML.NET metrics - ML.NET](https://review.docs.microsoft.com/en-us/dotnet-internal/machine-learning/resources/metrics?branch=pr-en-us-121#feedback)
* Content Source: [docs/machine-learning/resources/metrics.md](https://github.com/dotnet/docs-internal/blob/master/docs/machine-learning/resources/metrics.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **johalex**

**Comment by colbylwilliams** [comment]
This page should have (is missing) information for the following:
- [Anomaly Detection Metrics](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.anomalydetectionmetrics?view=ml-dotnet)
- [Ranking Metrics](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.rankingmetrics?view=ml-dotnet)
- [Clustering Metrics](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.clusteringmetrics?view=ml-dotnet)
