### ISSUE TITLE
Wrench in parent topics creates the impression there are no child topics

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1213]
# Issue Title

Wrench in parent topics creates the impression there are no child topics

# General

Because child nodes are not expanded by default, a wrench, which indicates that a topic has not been written but consists of boilerplate text only, creates the impression that child topics are similarly unwritten.

## Issues with Existing Topics

This applies to the following topics:

- docs/csharp/getting-started/index.md (C# [Getting Started](https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/)
- docs/csharp/concepts.md [C# Concepts](https://github.com/dotnet/docs/blob/master/docs/csharp/concepts.md)
- docs/csharp/methods-lambda-expressions.md [Methods and Lambda Expressions](https://docs.microsoft.com/en-us/dotnet/articles/csharp/methods-lambda-expressions). I wonder if this just could be eliminated and the Methods and Lambda Expressions topics moved up one level in the TOC.

**Comment by mairaw** [comment]
can we close this @rpetrusha?

**Comment by rpetrusha** [comment]
@mairaw Yes. I'm closing it now.
