### ISSUE TITLE
I don't see a config file like this in my project.

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12134]
I'm new to this. Apparently I need a config file that contains `<configuration><runtime><gcServer ... `, so I can control GC. But where does this file go? What is it called? I don't see a file like this anywhere in my netcoreapp2.2 app.

EDIT: Fix < > formatting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39c5030-7cdb-a2b4-4abf-0451ab4d8de4
* Version Independent ID: 4aae87fd-84b4-4cbf-aeec-4da9a43f4396
* Content: [Configuring Apps by using Configuration Files](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/index)
* Content Source: [docs/framework/configure-apps/index.md](https://github.com/dotnet/docs/blob/staging/docs/framework/configure-apps/index.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
_I believe this will answer your question. I'll close this and please feel free to reopen it if you wish._

This article is for .NET Framework projects, not .NET Core projects. .NET Core does not use the `app.config` file (which is what you're looking at). 

.NET Core provides two ways of setting the GC:

01. The `runtimeconfig.template.json` file at the same level as your project file

    ```json
    {
      "configProperties": {
        "System.GC.Concurrent": true,
        "System.GC.RetainVM": true,
        "System.Threading.ThreadPool.MinThreads": 4,
        "System.Threading.ThreadPool.MaxThreads": 25
      }
    }
    ```

    Note that the `System.GC.Server` setting cannot be set here and must be put into a `<PropertyGroup>` in the project file as the `<ServerGarbageCollection>` setting

    ```xml
    <PropertyGroup>
      <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>
    ```

02. The project file

    ```xml
    <PropertyGroup>
      <ServerGarbageCollection>true</ServerGarbageCollection>
      <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
      <RetainVMGarbageCollection>true</RetainVMGarbageCollection>
      <ThreadPoolMinThreads>4</ThreadPoolMinThreads>
      <ThreadPoolMaxThreads>25</ThreadPoolMaxThreads>
    </PropertyGroup>
    ```

Unfortunately we don't have a full tutorial about the `runtimeconfig.template.json` file, but we do have a bug filed for it #11266

The article that does document this is part of a migration article that was created when .NET Core moved from a `project.json` file format to the msbuild `project.csproj` format.

https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#runtimeoptions
