### ISSUE TITLE
Waiting for the task after it is finished?

### ISSUE THREAD

**Issue by dtdono0** [dotnet/docs#12132]
In the last breakfast example, when you do:
Task finished = await Task.WhenAny(allTasks);
Why do you need to then do:
var eggs = await eggsTask;
Isn't the result of the eggsTask already stored in finished?  
Also why say 'eggs are ready' before the await eggsTask if you are still waiting on that task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by blackblather** [comment]
At first when i read the article it seemed very clear, but then i read your comment and now I'm confused...

**Comment by user2150** [comment]
Do you mean why there is
var eggs = await eggsTask;
instead of
var eggs = eggsTask.Result;
?

**Comment by svick** [comment]
> Isn't the result of the eggsTask already stored in finished?

If the condition `finished == eggsTask` is true, then that means both variables refer to the same `Task`. But the type of `finished` is `Task`, not `Task<Eggs>`. This means it's valid (but pointless) to write `await finished;`, but you can't write `var eggs = await finished;`. Using `eggsTask` instead is the best option here. But if you really want to use `finished`, you can, though it requires a conversion: `var eggs = await (Task<Eggs>)finished;`.

**Comment by prakash-manit** [comment]
I was about to put a comment but saw that it's already added. The question is why you need to await at all after the task is finished and the message is printed. I am still not able to make out the real purpose of adding var eggs = await eggsTask; after printing Console.WriteLine("eggs are ready");

**Comment by prakash-manit** [comment]
I have also checked that adding var eggs = await eggsTask doesn't seem to be making any delay as the task is already completed and control simply goes to the next line. It seems a redundant code to me unless I am missing anything.

**Comment by svick** [comment]
>  I am still not able to make out the real purpose of adding var eggs = await eggsTask; after printing Console.WriteLine("eggs are ready");

That part of the code is indeed odd. One thing you could try to do would be to use the `eggs` variable, along with the other variables, in the following code to finish the breakfast. But you can't easily do that here, because the variables are in a nested block.

I guess this is where the metaphor of making breakfast breaks down, I'm not sure if there's a good way to fix that code.

**Comment by BillWagner** [comment]
This is really good feedback. Thanks all.

I'll see what I can do to make the code a bit better and more in line with the abstractions. It may still break down somewhere, but it can get better.

**Comment by mattumotu** [comment]
I'm assuming it's because `WhenAny` returns (in this example) `Task<Eggs>` but we don't want eggs to be of type `Task<Eggs>` we want type `Eggs`. 

Calling await on a `Task<TResult>` will return a `TResult`, if the task is completed then it just returns immediately.
