### ISSUE TITLE
App.Config??

### ISSUE THREAD

**Issue by Johan1974** [dotnet/docs#12136]
Hello,

I created the project following these instruction but i do not see a app.config file.  Am i missing a step ?

Johan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3469d675-7452-0f70-3ef1-eb4d353b7163
* Version Independent ID: 9e089f76-487e-1e22-c7f5-57db9944f279
* Content: [Tutorial: Define a Windows Communication Foundation service contract](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-define-a-wcf-service-contract#feedback)
* Content Source: [docs/framework/wcf/how-to-define-a-wcf-service-contract.md](https://github.com/dotnet/docs/blob/staging/docs/framework/wcf/how-to-define-a-wcf-service-contract.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Hello. We need more information about your environment and projects. I just used **Visual Studio 2019** and chose the **WCF Service Library template** and **.NET Framework 4.7.2** and I got the app.config file. What versions are you using?

![image](https://user-images.githubusercontent.com/2672110/57029053-87bd4b00-6bf5-11e9-844c-d8004f178009.png)
