### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by daviderb** [dotnet/docs#12135]
In “Creating the data set,” the line reading “you can create two sequences to represent suites and ranks” should read “suits” instead of “suites.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq#feedback)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this concern @daviderb 

If you'd like, when you find these types of errors, you can click the "edit" button to update the article and submit a PR. Otherwise, I've added this to our backlog to address when we next update this article.

**Comment by daviderb** [comment]
PR submitted, pending review. Thanks, Bill!
