### ISSUE TITLE
Exceptions when subscribing to focus changes

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12144]
Exceptions when subscribing to focus changes

I've tried the focus changes example in console and WPF applications (using a thread pool thread in WPF), and the following messages always appear in the output window during the Automation.AddAutomationFocusChangedEventHandler call:

Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll
Exception thrown: 'System.ArgumentException' in UIAutomationClientsideProviders.dll

Nevertheless the events come and everything seems ok.

What could be the reason? Should I bother about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d098ded-cc13-cf2d-e5e5-c7e1835f5cde
* Version Independent ID: 69ad9e88-ceef-39d8-296c-5647921a77f1
* Content: [Subscribe to UI Automation Events](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/subscribe-to-ui-automation-events#feedback)
* Content Source: [docs/framework/ui-automation/subscribe-to-ui-automation-events.md](https://github.com/dotnet/docs/blob/staging/docs/framework/ui-automation/subscribe-to-ui-automation-events.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I don't think so. Doing a quick search I find this from a decade ago talking about the same thing:

https://social.msdn.microsoft.com/Forums/en-US/e9ff109d-713b-448f-8fa4-6eb475baf562/automationaddautomationfocuschangedeventhandler-throws-an-exception

So I think it's just something going on underneith everything and because you're debugging, you're just seeing it happen.

I'm going to close this question. Thanks!
