### ISSUE TITLE
Calling dynamic object's property from string.

### ISSUE THREAD

**Issue by junpark12** [dotnet/docs#12150]
Hi This is very useful features.
Can i call dynamic object's property using string? 
So instead of this line  --&gt; string line in rFile.Customer
I want to access customer's property using string from user input or config file. Is this possible? 
--&gt; string line in rFile."Customer" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63fb701-91e9-5723-add6-33d2288431a3
* Version Independent ID: e9d33444-b5f7-96d4-9c33-dd29913349d5
* Content: [Walkthrough: Creating and Using Dynamic Objects (C# and Visual Basic)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects)
* Content Source: [docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@junpark12 The syntax is different, but you could do it.  It would look something like:

```csharp
string line in rFile["Customer"];
```

Then, you'd create an indexer that works similar to the `TryGetMember` in the example.

The [ExpandoObject](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject?view=netframework-4.8) may have exactly what you want.

I'll close this an an answered question.
