### ISSUE TITLE
does this work for entity framework core?

### ISSUE THREAD

**Issue by xtianus79** [dotnet/docs#12171]
want to know 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99913132-5ffb-14ac-8f7e-d12d0ac2fca2
* Version Independent ID: 62937617-3e72-4563-c615-30a782a113c2
* Content: [SqlMetal.exe (Code Generation Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sqlmetal-exe-code-generation-tool)
* Content Source: [docs/framework/tools/sqlmetal-exe-code-generation-tool.md](https://github.com/dotnet/docs/blob/staging/docs/framework/tools/sqlmetal-exe-code-generation-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@xtianus79 Would [EDM Generator](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/edm-generator-edmgen-exe) be a better tool for entity framework core?

@rowanmiller thoughts?

**Comment by rowanmiller** [comment]
cc @divega @ajcvickers who look after EF these days

**Comment by divega** [comment]
@xtianus79 @Thraka. This page refers to a command line tool for LINQ to SQL. EF Core has it's own set of command line tools, documented at https://docs.microsoft.com/ef/core/miscellaneous/cli/.

**Comment by divega** [comment]
@rowanmiller I have answered the question. I think this can be closed.

**Comment by xtianus79** [comment]
@divega thank you!
