### ISSUE TITLE
Startup event order is different

### ISSUE THREAD

**Issue by mdell-seradex** [dotnet/docs#12180]
VisibleChanged happens before Load when loaded using Show() or ShowDialog().
This is detected in Windows 10 targeting framework 4.5.2 and 4.6.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3a80d-9468-0283-435b-f45f4827b920
* Version Independent ID: c879f822-8677-5e20-bcc7-52e1595d8883
* Content: [Order of Events in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/order-of-events-in-windows-forms)
* Content Source: [docs/framework/winforms/order-of-events-in-windows-forms.md](https://github.com/dotnet/docs/blob/staging/docs/framework/winforms/order-of-events-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by smilekok** [comment]
And also activated runs before load event.

**Comment by mairaw** [comment]
@merriemcgaw @RussKie can you help validate what would be the right order of events in WinForms?

**Comment by RussKie** [comment]
The currently documented order is correct for a form launched via `Application.Run(form)` or `form.Show()`. 

For a form launched via `form.ShowDialog()` the order of events for the first time should be the same as the documented, e.g.:
```
form3: HandleCreated
form3: BindingContextChanged
form3: Load
form3: VisibleChanged
form1: Deactivate
form3: Activated
form3: Shown
```
For the 2nd and subsequent calls it will be:
```
form3: HandleCreated
form3: Load						<-- this call went off earlier
form3: BindingContextChanged
form3: VisibleChanged
form3: Activated
form3: Shown
```
This is due to different code flows resolving visibility. A form shown via `form.ShowDialog()` remains alive after being closed (`form1` and `form2` will be disposed once closed), and when it is shown again the order of events is different.
https://github.com/dotnet/winforms/blob/9bdd2e4e73ed5e9dd37e6e09a7d38143e64ec025/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L2329-L2375

### Test harness:

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        var form2 = new Form { Name = "form2" };
        BindEvents(form2);

        var form3 = new Form { Name = "form3" };
        BindEvents(form3);

        var button = new Button
        {
            Text = "Show form",
            Location = new System.Drawing.Point(8, 8),
            AutoSize = true
        };
        button.Click += (s, e) => form2.Show();

        var button2 = new Button
        {
            Text = "Show dialog",
            Location = new System.Drawing.Point(8, 40),
            AutoSize = true
        };
        button2.Click += (s, e) => form3.ShowDialog();

        this.Name = "form1";
        this.Controls.Add(button);
        this.Controls.Add(button2);

        BindEvents(this);
    }

    private void BindEvents(Form form)
    {
        form.HandleCreated += (s, e) => Debug.WriteLine($"{form.Name}: HandleCreated");
        form.BindingContextChanged += (s, e) => Debug.WriteLine($"{form.Name}: BindingContextChanged");
        form.Load += (s, e) => Debug.WriteLine($"{form.Name}: Load");
        form.VisibleChanged += (s, e) => Debug.WriteLine($"{form.Name}: VisibleChanged");
        form.Activated += (s, e) => Debug.WriteLine($"{form.Name}: Activated");
        form.Shown += (s, e) => Debug.WriteLine($"{form.Name}: Shown");
        form.Closing += (s, e) => Debug.WriteLine($"{form.Name}: Closing");
        form.FormClosing += (s, e) => Debug.WriteLine($"{form.Name}: FormClosing");
        form.FormClosed += (s, e) => Debug.WriteLine($"{form.Name}: FormClosed");
        form.Deactivate += (s, e) => Debug.WriteLine($"{form.Name}: Deactivate");
    }
}
```

Tested on net461;net472;netcoreapp3.0

**Comment by mdell-seradex** [comment]
That is very odd, because that is not what I experienced.  As I said, I saw VisibleChanged happen before Load.

**Comment by RussKie** [comment]
Without a repro and stack traces I am unable to provide further comments, sorry.

**Comment by mdell-seradex** [comment]
I will endeavour to provide this as soon as I can.

**Comment by mdell-seradex** [comment]
Sorry for not responding.  I have been very busy as of late.

**Comment by mairaw** [comment]
No problem @mdell-seradex. I've added the needs-more-info tag again. The issue will auto close in two weeks again.
