### ISSUE TITLE
Ephemeral Segment contains objects that survived a generation-0 garbage collection

### ISSUE THREAD

**Issue by rubbalbhusri** [dotnet/docs#12189]
Quote
"Each new segment acquired by the garbage collector becomes the new ephemeral segment and contains the objects that survived a generation 0 garbage collection. "
Does that mean ephemeral segment contains objects of generation-1 because it contains objects that survived garbage collection-0 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs/blob/staging/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
I believe you're correct but I'm adding @Maoni0 to confirm this.

**Comment by Maoni0** [comment]
correct

**Comment by mairaw** [comment]
Thanks @Maoni0!
