### ISSUE TITLE
Incorrect statement Interpolated Strings as next tutorial

### ISSUE THREAD

**Issue by carljfoster** [dotnet/docs#12186]
It says to click the Interpolated strings link for next tutorial but the next tutorial is list collection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @carljfoster for your feedback and @pkulikov for making the fix.
