### ISSUE TITLE
Updates for C# 8 needed.

### ISSUE THREAD

**Issue by UtkarshBais** [dotnet/docs#12188]
We need this page to be updated for C# 8 and Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#feedback)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

@BillWagner Not sure if you'll be updating this for C# 8 preview's but this issue can track that work.

Thanks again!

**Comment by UtkarshBais** [comment]
Yes. I'll add the details for the 8 preview and features.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Thraka** [comment]
@UtkarshBais Thank you for your commitment to making the docs better 😄 We're going to hold off on this as I we're not sure if we want to add preview information to the release information or wait until C# 8.0 is finished. @BillWagner will handle the updates. Thanks!

**Comment by UtkarshBais** [comment]
Oki doki !

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Thraka** [comment]
If you're interested in helping, you can always review the community project where we add issues that we need help. https://github.com/dotnet/docs/projects/35

**Comment by UtkarshBais** [comment]
Oh sure. I'll take a look. Always wanted to contribute. Thanks a ton !

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mylastsong18** [comment]
Since C# 8 is now released can you guys add it to the docs?
