### ISSUE TITLE
Where is the foreach loop?

### ISSUE THREAD

**Issue by carljfoster** [dotnet/docs#12185]
The for loop lesson doesn't teach anything about the foreach loop. Surely this should be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @carljfoster 

The fix should also be included in the [local version](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/branches-and-loops-local.md) of the same tutorial.

I've added this issue to our backlog, and added the "up for grabs" label.

**Comment by DameonL** [comment]
I can write this. However, collections are covered as the next topic (Lists/Collections), so there's some overlap if we cover foreach in the branches and loops tutorial. It's actually used early in the Lists tutorial, so a better solution might be to actually show how to iterate through a collection in the Lists tutorial, and then expand that to the foreach loop. Let me know, and I'll get writing.
