### ISSUE TITLE
Does Lazy(T)(LazyThreadSafetyMode) cache exceptions?

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#12196]
In the table the line
 Lazy(T)(LazyThreadSafetyMode)	User-specified	No	No
said , that exceptions are not cached, but in https://docs.microsoft.com/en-us/dotnet/api/system.threading.lazythreadsafetymode?view=netframework-4.8#System_Threading_LazyThreadSafetyMode_ExecutionAndPublication it said that ExecutionAndPublication and None modes cache exceptions. Who is wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c082508c-af74-1d6a-a954-e70aca02e1a4
* Version Independent ID: 85c92c40-9a7a-cd0f-fa63-53c87cb5febe
* Content: [Lazy Initialization](https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization)
* Content Source: [docs/framework/performance/lazy-initialization.md](https://github.com/dotnet/docs/blob/staging/docs/framework/performance/lazy-initialization.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback. @kouvel can you help with this feedback?
