### ISSUE TITLE
Code Access Security docs not shown in TOC

### ISSUE THREAD

**Issue by JimDaly** [dotnet/docs#12191]
There is no toc.yml file in the misc folder for these 20 or so topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b136e1b9-ac93-6fc4-616a-c24c6acf4945
* Version Independent ID: b8e47e7a-4e2e-fc0a-b0e3-20d219e97dac
* Content: [Code Access Security](https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security)
* Content Source: [docs/framework/misc/code-access-security.md](https://github.com/dotnet/docs/blob/master/docs/framework/misc/code-access-security.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
That’s by design but I should move the security articles into a different section.

**Comment by Thraka** [comment]
@mairaw I think these were moved. Should we close this issue?

**Comment by JimDaly** [comment]
As someone who has worked in the content space at MS for a long time, I disagree with the idea of intentionally not providing a TOC for content by design. Even if you don't want people to use the feature, doesn't mean it can't be provided in context with the disclaimers you have added. But it isn't my content, so you can do what you think is best. I just wanted to raise this in case it was unintentional.

**Comment by Thraka** [comment]
My mistake. The content is still there. This issue was created on the staging site and not on the production site so the edit link is broken. I'll fix that.

**Comment by mairaw** [comment]
We should somehow call out this is legacy content. My original plan for this was to move these under the security folder but have a separate header indicating this is obsolete somehow.

**Comment by tdykstra** [comment]
The articles have alert boxes at top of page -- see https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security -- we could add text noting that CAS applies only to Fx 3.5 and earlier.

**Comment by tdykstra** [comment]
Alert boxes updated by https://github.com/dotnet/docs/pull/19829
