### ISSUE TITLE
Validating Issuer Name Registry API Reference is empty

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#12192]
The page says: "This section contains the API Reference for the Validating Issuer Name Registry WIF Extension."
However, neither the page itself nor the table of contents lists any namespaces or types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff631de-6b0a-bef2-22dc-5567d51e57a5
* Version Independent ID: 86d9015e-eb09-e1d1-85ea-c3ad42a3ed33
* Content: [Validating Issuer Name Registry API Reference](https://docs.microsoft.com/en-us/dotnet/framework/security/validating-issuer-name-registry-api-reference#feedback)
* Content Source: [docs/framework/security/validating-issuer-name-registry-api-reference.md](https://github.com/dotnet/docs/blob/staging/docs/framework/security/validating-issuer-name-registry-api-reference.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll look into getting this fixed.

Thanks again!

@mairaw @rpetrusha There must be something missing with this article, almost as if there is another reference doc set that is supposed to be in the TOC here?

**Comment by KalleOlaviNiemitalo** [comment]
[JSON Web Token Handler API Reference](https://docs.microsoft.com/en-us/dotnet/framework/security/json-web-token-handler-api-reference) is listed in the TOC and redirects to [a wiki on GitHub](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki), as configured in [.openpublishing.redirection.json](https://github.com/dotnet/docs/blob/130c4180fac0f5bf19e76d3c68b9d60d97cd5ab4/.openpublishing.redirection.json). Is a similar redirection missing for the Validating Issuer Name Registry API Reference? I have no idea where it should redirect, though; the source code of VINR does not seem to be published on GitHub.

**Comment by KalleOlaviNiemitalo** [comment]
The Validating Issuer Name Registry API is documented in Previous Versions:

- [System.IdentityModel.Tokens Namespace](<https://docs.microsoft.com/en-us/previous-versions/ms581396(v=vs.115)> "System.IdentityModel.Tokens Namespace () | Microsoft Docs")
- [ValidatingIssuerNameRegistry Class (System.IdentityModel.Tokens)](<https://docs.microsoft.com/en-us/previous-versions/dn464225(v=vs.115)> "ValidatingIssuerNameRegistry Class (System.IdentityModel.Tokens) | Microsoft Docs")
- [IssuingAuthority Class (System.IdentityModel.Tokens)](<https://docs.microsoft.com/en-us/previous-versions/dn464228(v=vs.115)> "IssuingAuthority Class (System.IdentityModel.Tokens) | Microsoft Docs")

However, it is not part of the table of contents there, either.

If Windows Identity Foundation documentation still recommends using VINR, I suppose its documentation should be migrated out of Previous Versions.

**Comment by Thraka** [comment]
I'll bring this up at our team meeting this week. Thanks.

**Comment by brentschmaltz** [comment]
@KalleOlaviNiemitalo @Thraka VINR is not required or used by asp.net with OWIN or asp.net CORE. It is used by 4.5 asp.net apps.

**Comment by KalleOlaviNiemitalo** [comment]
@brentschmaltz Are you recommending that VINR references be deleted from WIF documentation? Note that it is part of .NET Framework Guide rather than .NET Core Guide.

VINR can be used for authenticating the users of an IIS web application with WS-Federation, just by having the correct web.config; the web application can consist of static files without any local executable code at all. I am not sure Microsoft.Owin.Security.WsFederation can similarly integrate with authentication in IIS, so I'll be a bit sad if VINR is deprecated.

**Comment by brentschmaltz** [comment]
@KalleOlaviNiemitalo I am not recommending the VINR ref be deleted from WIF documentation.

VINR was designed to work with AAD multitenant scenarios and is useful. 
For .Net Core, we are developing similar solutions.

**Comment by mairaw** [comment]
@Thraka you assigned this to the May milestone but nobody was actually assigned to this. Can you please review and update accordingly?

**Comment by Thraka** [comment]
- Resent email to @brentschmaltz 
- Assigned issue
- Changed milestone to Aug as it seems that will probably be when the issue gets resolved.

**Comment by brentschmaltz** [comment]
@Thraka what email did you use?

**Comment by Thraka** [comment]
@brentschmaltz Your work email. I replied to the thread we had going. However, **Identity DevEx Middleware Team** is on the email thread so maybe it got filed into a folder?

**Comment by mairaw** [comment]
We're no longer maintaining the WIF content and this article has been archived as-is. Apologies for the incovenience.
