### ISSUE TITLE
JSON serialization with .NET Core 3.0

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#12207]
.NET Core 3.0 Preview 5 implemented a full JSON serialization stack. We should document how to use the new JSON serializer to serialize and deserialize objects. Objects can be customized with attributes to control serialization. 

More information: https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/docs/SerializerProgrammingModel.md

[EDIT] This issue will cover the initial publication of an overview and how-to doc. Other issues will be created as the doc set is developed.

**Comment by devel112** [comment]
Can the default be to not **mangle** property names on serialization (keep whatever case the properties have)? Or at least make it really easy to set without fidling with varied option objects

**Comment by tdykstra** [comment]
@devel112 

>Can the default be to not mangle property names on serialization (keep whatever case the properties have)? Or at least make it really easy to set without fidling with varied option objects

That is in fact the default (keep the same case).  Feel free to review the initial [docs PR](https://github.com/dotnet/docs/pull/14208) and let me know if there are any other questions you have that the new how-to doc doesn't answer.
