### ISSUE TITLE
Document dotnet-publish single-file executable deployment

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#12206]
.NET Core 3.0 Preview 5 introduced single-file deployments. These are standalone executables that bundle all app assets and dependencies into a single-file that is self-extracting and forwards executable to the extracted exe. 

Design docs: https://github.com/dotnet/designs/tree/master/accepted/single-file

ALSO:
- Update https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

**Comment by swaroop-sridhar** [comment]
This is a dup if https://github.com/dotnet/docs/issues/13149

**Comment by Thraka** [comment]
If you guys want to take it, I'm fine with that. :)
