### ISSUE TITLE
Methods without parameters?

### ISSUE THREAD

**Issue by Narvey** [dotnet/docs#12205]
In order to avoid confusion with methods with 0 parameters, I propose code formatting be added to "out" in the title "Calls to methods with out parameters". Thus it would be:

## Calls to methods with `out` parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards#calls-to-methods-with-out-parameters)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Tagging @DuncanmaMSFT and @adkinn as an example of where code style in headers and TOC entries would be beneficial.

**Comment by BillWagner** [comment]
closing after transferring to MicrosoftDocs/feedback#2033
