### ISSUE TITLE
Need an example of using PermutationFeatureImportance with featurized text

### ISSUE THREAD

**Issue by dionoid** [dotnet/docs#12216]
There is documentation on explaining model predictions using Permutation Feature Importance [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net). It uses input data that is already featurized.

But if your input data contains a number of text-columns, and you featurize these text columns using mlContext.Transforms.Text.FeaturizeText, you will get a large number of features and also a large number of result-rows in the classificationMetricsStatistics, which are hard to map back to the originating text-column.

Adding an example of using PermutationFeatureImportance where the input data contains a few text columns that are going to be featurized, will be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1fb0dd-648b-26e9-7e4e-48824ab94160
* Version Independent ID: 689b6488-dadc-fd39-c432-ebf095a0299a
* Content: [Explain model predictions using Permutation Feature Importance - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Thanks for your feedback @dionoid . I will look into it and have also raised the question on the ML.NET repo. Feel free to follow that thread as well.

dotnet/machinelearning#3674

**Comment by JRAlexander** [comment]
Hi @dionoid! Here is the feedback from the team:
"this is indeed expected. The feature importance is calculated on the final features that the model trains on. You can inspect the output tokens to see which slot in the Features vector corresponds to which token. See [this example](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/FeaturizeTextWithOptions.cs) for more. "  Closing this as it is resolved. Thanks!
--
