### ISSUE TITLE
#if CSHARP_8_0

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12211]
I can't find documentation anywhere that talks about this. If it isn't supported, it should be! Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [Select the C# language version - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @jcouv for comment on this feature.

**Comment by jcouv** [comment]
I'm not aware of any such feature. I'm not sure when you would want to use that.

You should be able to get this behavior by defining your own constant in MSBuild:
```
<PropertyGroup Condition="'$(LangVersion)'=='8.0'">
   <DefineConstants>$(DefineConstants);CSHARP_8_0</DefineConstants>
</PropertyGroup>
```

**Comment by daveyostcom** [comment]
It's useful for those of us who love great new language features, those of us to refactor constantly, always looking for a better way to express things.  After you're sure you won't have to go back to the old compiler, you can remove the #if and the old crufty syntax.

Nice workaround!

**Comment by BillWagner** [comment]
I'll close this as answered.

Thanks @jcouv for the great workaround
