### ISSUE TITLE
Add missing explanations that are used for the predicted column (label), not only feature vector

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#12227]
there is no mention on preparing the label data. 
text (Git hub issue labeler)
int (iris)
double (taxi) 

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c298a5-b76f-25d9-beda-e298ac03cf35
* Version Independent ID: 392ab238-4442-015c-ec30-eae546794cc9
* Content: [Prepare Data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/prepare-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/prepare-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/prepare-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Great suggestion @PeterPann23.
