### ISSUE TITLE
The sample doesn't work

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12224]
I've downloaded the sample and am trying to run the QueueResults app.

When pressing the Start button it writes "Downloads failed." (Actually there's a HttpRequestException: An error occurred while sending the request.)

And the following messages are in the output:
	Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
	Exception thrown: 'System.ObjectDisposedException' in System.dll
	Exception thrown: 'System.Net.WebException' in System.dll
	Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll

And I've tried other samples in "The Task asynchronous programming model in C#" tutorial and none of them work.

I'm using a firewall and have opened it for the app.

And I've tried to connect to the same url via HttpClient.GetByteArrayAsync(url) in a separate test app, and it succeeds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9695aa2e-6d63-f36f-0e8e-b552ed0bf40a
* Version Independent ID: b06fb1c9-770c-4628-516e-7d661cf0bf29
* Content: [Handling Reentrancy in Async Apps (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/handling-reentrancy-in-async-apps#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/handling-reentrancy-in-async-apps.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/handling-reentrancy-in-async-apps.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by nemrism** [comment]
The samples actually work if you either:
- update the project to target .NET Framework 4.6 or newer.
- or specify to use TLS 1.2 as default connection with the following line of code:
`System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

**Comment by nemrism** [comment]
/cc @BillWagner

What do you suggest to fix the issue?

Updating the sample and/or adding a note mentioning that Tls12 needs to be enable if the targeted framework version is less than 4.6?

**Comment by BillWagner** [comment]
@nemrism I think the better fix is to update the sample. Would you agree?

**Comment by nemrism** [comment]
Definitely, so you recommend to add the instruction whatever .NET FX version the code is run against?

Would you like me to PR this change?

**Comment by BillWagner** [comment]
@nemrism I apologize for the late response. I missed this comment.

The main sample should be updated to recommend a version newer than framework 4.6. The 4.6 instructions should be included.

And yes, I'll watch for a PR if you want to submit one.

**Comment by nemrism** [comment]
Your lucky I still got somewhere in my phone a set of open webpages to handle this.
I'll try to work on this in the coming days and let you know.

**Comment by BillWagner** [comment]
We're lucky to have great community contributors. Thank you.

**Comment by nemrism** [comment]
Would you believe me if I told you that participating to msdocs on Github made me reconsider this part of my day-to-day job?
