### ISSUE TITLE
Installation fails because exe is in use

### ISSUE THREAD

**Issue by lonevvolf** [dotnet/docs#12229]
When trying to run this on a system where a version of dotnet is already installed, but I would like to update it to a newer version, I get:
The process cannot access the file 'C:\Program Files\dotnet\dotnet.exe' because it is being used by another process.
Shouldn't the script have a way to Force installation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@johnbeisner can you please review this issue about the installation scripts? Thanks!

**Comment by mairaw** [comment]
This is a hard problem to solve and it's been a known problem. The best advice we can give you right now is to wait about 15 minutes after using the product to modify it. If you'd like to discuss this in more detail with the product team, file an issue at https://github.com/dotnet/cli/issues.
