### ISSUE TITLE
various

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12221]
It's not clear hear exactly what it means to build against .Net Standard instead of core or other library. I gather that netstandard is just an indirection layer interposed in front of some real library, so that you can build against a common set of apis implemented by all of the various actual libraries. This should be explained.

A pointer to a page about preview releases would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@daveyostcom The best way to understand .NET Standard may be to follow a tutorial about how to create and use a .NET Standard class library -- I've added a link in the doc to https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio

**Comment by daveyostcom** [comment]
A tutorial is a great thing to have, but it doesn't clearly explain why to use standard as opposed to core.

**Comment by mairaw** [comment]
I think the answer to this is in the beginning of the article:
![image](https://user-images.githubusercontent.com/12971179/66969758-c0d06700-f03f-11e9-9073-038e32fdb793.png)

If you don't care about portability or cross-targeting, you should fine targeting .NET Core.

I'll add a second link to that topic that should help as well:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting
