### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by tedyyu** [dotnet/docs#12225]
Windows Azure Access Control Service (ACS) link is now broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb55b04-9cd6-e613-0b01-897b3fb6ad02
* Version Independent ID: f94109b2-5626-776c-4bca-e7380d7103fb
* Content: [Building My First Claims-Aware WCF Service](https://docs.microsoft.com/en-us/dotnet/framework/security/building-my-first-claims-aware-wcf-service)
* Content Source: [docs/framework/security/building-my-first-claims-aware-wcf-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/building-my-first-claims-aware-wcf-service.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I've created PR #12655 to fix the broken link but ACS was retired last year:
https://azure.microsoft.com/en-us/blog/one-month-retirement-notice-access-control-service/

**Comment by hemantkx** [comment]
I can't Install Identity and Access tool, your complete documentation is based on this tool. and It's not even supported in Visual Studio 2017 on Windows 10. Is there any alternative?
