### ISSUE TITLE
Create and consume COM components from .NET Core 3.0

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#12238]
On Windows you can now create COM-callable managed components.

Unlike .NET Framework where the *mscoree.dll* was used as the COM server, .NET Core will add a native launcher dll to the *bin* directory when you build your COM component.

For an example of how to create a COM component and consume it, see the [COM Demo](https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo).

This should be documented. There are project settings that you need to configure to enable this scenario, they are detailed in the example linked above.

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
An overview the .NET Core COM architecture is at https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/COM-activation.md. That document is a good starting point for official documentation.

**Comment by Thraka** [comment]
Thanks!
