### ISSUE TITLE
net core 3 preview 4 CORS problems

### ISSUE THREAD

**Issue by niconico49** [dotnet/docs#12234]
When I launch the app with
.AddCors()
.UseCors() 

inside StartUp
and add the attribute [EnableCors] 
in the Controller used by the CORS, obviously

but after the controller method calling by url the app gives this error:
The "<controller>" contains CORS metadata, but a middleware was not found that supports CORS. Add the .useCors() in the StartUp….. 

How you can see, we have done correctly the configuration (I Hope!!!) but what the source of this bug?

**Comment by mairaw** [comment]
To which topic is this referring to @niconico49?

**Comment by mairaw** [comment]
Closing due to the lack of response. Please get back to us with more information and we can reactivate the issue.

If this is a general question about .NET Core, maybe try asking your question on forums such as https://stackoverflow.com/.
