### ISSUE TITLE
Examples of ML.NET + Tensorflow for Binary and Multiclass Classification

### ISSUE THREAD

**Issue by danucalovj** [dotnet/docs#12231]
There is very little documentation on using ML.NET with pre-built Tensorflow models, with the exception of this one:

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification

Which is solely for Image Classification. No further documentation is provided on doing the same with other non-image related classifications.

**Comment by JRAlexander** [comment]
Hi, @danucalovj! Check out this sentiment analysis sample that uses TensorFlow. Hopefully this will get you close. https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs

**Comment by danucalovj** [comment]
Thanks @JRAlexander! This is very helpful.
