### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by the51craw** [dotnet/docs#12247]
I this valid for IIS 10 under Windows 10, or are some additional steps required? 

When trying http://localhost/IISHostedCalc/Service.svc I get the following report:

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /IISHostedCalc/Service.svc

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0822f57-ffba-c196-a40b-2b661b0a0f8f
* Version Independent ID: 2499a5be-0643-bf0b-023e-6e4317637cd1
* Content: [How to: Host a WCF Service in IIS](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis#feedback)
* Content Source: [docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by stevensrmiller** [comment]
I had the same problem until I took out the blank line the example includes at Line 1 of Web.config.

**Comment by stevensrmiller** [comment]
The so-called "complete" example is also missing what should be a closing curly bracket at Line 40. Now IIS complains that it can't find an implementation of IMetaDataExchange (which makes sense, since there isn't one).

**Comment by Thraka** [comment]
Sorry for the confusion. At this time we're not resourced to address the WCF documentation. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Sorry about that.

**Comment by DavidCBerry13** [comment]
I've updated the code samples in the article and tested them so everything should work now.
