### ISSUE TITLE
Update syntax colouring in docs to properly colourize interpolated expressions.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#12245]
When reading the source examples on interpolated strings, syntax colouring isn't as detailed as the one we have in the IDE. The very first example looks like this in my browser:

![interpolated_string_bad](https://user-images.githubusercontent.com/20465797/57343823-8fc53f80-714d-11e9-840b-c6be75dc3175.png)

...but in the IDE it renders like this:

![interpolated_string_good](https://user-images.githubusercontent.com/20465797/57343856-b4b9b280-714d-11e9-89a1-6808be21d150.png)

The important thing is that the interpolated expressions (i.e `name` and `hours`) are rendered in a different colour to the rest of the string contents making it easier to see them. It would be great if this was done in the docs too (currently, the entire string is one uniform colour).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f4b61b-ee05-3221-9a2c-0cdf31645f67
* Version Independent ID: b5ca0b9a-d789-d9a6-e5d5-1a4709879091
* Content: [Interpolated Strings (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/strings/interpolated-strings)
* Content Source: [docs/visual-basic/programming-guide/language-features/strings/interpolated-strings.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/strings/interpolated-strings.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by ericmutta** [comment]
Pinging @mairaw.

**Comment by ericmutta** [comment]
Pinging @mairaw.

**Comment by ericmutta** [comment]
Pinging @KathleenDollard

**Comment by KathleenDollard** [comment]
@mairaw What's the right way to do color in the docs? I thought we used the markdown colorizer.

**Comment by mairaw** [comment]
Sorry I missed this issue before. I just know it's not the same colorizer as VS.

@adkinn would you mind commenting here about the syntax coloring in docs?

**Comment by mairaw** [comment]
But just to clarify your question @KathleenDollard, the article correctly tags the code blocks with vb. So, if this is an issue that needs to be solved, we need to move this to https://github.com/microsoftdocs/feedback/issues, since we can't resolve this in the content. It needs to go to the docs engineering team.
