### ISSUE TITLE
Show rendering of examples

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12246]
Examples here and in the subpages should show how the text is normally rendered., with bold, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5aa865-b9d2-e977-a272-3886aa0a1111
* Version Independent ID: 353b1c44-b90a-e5cc-a193-7b42ec714290
* Content: [Recommended Tags for Documentation Comments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)
* Content Source: [docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This sample code is quite old. The URLs used have been redirected.

We should update this with a new set of URLs to query. That should fix this issue.

I've added this to our backlog, and added the "up for grabs" label, if the community wants to supply a pull request.

**Comment by BillWagner** [comment]
I like the suggestion for showing the output, but that presents an interesting problem. There are multiple tools that produce docs from the XML comments.

Should we show the XML output? a sample HTML rendering? What?

The XML output would be always correct, but might not be useful.

**Comment by daveyostcom** [comment]
A sample rendering is what I had in mind. These renderings will also serve as a recommendation to tool builders. SVG would be the way to go, something like [this](https://svgjs.com/docs/2.7/tutorials/).

**Comment by BillWagner** [comment]
@daveyostcom I'm going to close this as "won't fix". While I agree that a sample rendering would be useful, there are too many different tools that create docs from the XML output.  Each of those tools (docfx, sandcastle, doxygen) show example output.

StackOverflow periodically has questions and updated lists of recommended tools.
