### ISSUE TITLE
Train() referenced as LoadData()

### ISSUE THREAD

**Issue by outlookhazy** [dotnet/docs#12253]
Under section "Load and Transform Data", reader is instructed to add code as the first line to LoadData() 
This is not the method previously created, and this should instead refer to the Train() method. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using a regression algorithm - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @outlookhazy, for this feedback! We'll get it fixed straightaway, unless you are going to make the change. Either way is great!

**Comment by outlookhazy** [comment]
I don't have time to track down contribution guidelines etc at the moment - too many other things going on. Just wanted to make a note

**Comment by JRAlexander** [comment]
No worries, we'll get it resolved asap! Really appreciate the feedback, @outlookhazy! Have a great day.

**Comment by JRAlexander** [comment]
@outlookhazy - The PR above was merged just now. The changes should be live in a day or so.
