### ISSUE TITLE
Splitter/consolidator worker encountered exception while consuming source data

### ISSUE THREAD

**Issue by JagathPrasad** [dotnet/docs#12254]
while Fit() its showing the error, using the below code.
estimator.Fit(splitTrainSet);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Make sure that you set the file properties on the yelp_labelled.txt file in visual studio..

**Comment by JRAlexander** [comment]
Closing as I believe this is resolved - Please reopen if that isn't the case.

**Comment by cristozz** [comment]
I have a similar issue.

IEnumerable<int[]> probabilities = scoredData.GetColumn<int[]>(Yolov3ModelSettings.ModelOutput_Field_concat_2);

System.InvalidOperationException: 'Splitter/consolidator worker encountered exception while consuming source data'.
ArgumentException: Length of memory (519168) must match product of dimensions (3).

help!!
