### ISSUE TITLE
NuGet dependency missing

### ISSUE THREAD

**Issue by outlookhazy** [dotnet/docs#12252]
This tutorial and its associated sample will not compile without the additional NuGet package: Microsoft.ML.FastTree

Line 56: `.Append(mlContext.Regression.Trainers.FastTree());` fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using a regression algorithm - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Great catch, @outlookhazy! Thanks! We'll get it fixed straightaway unless you are making the change. Either way is great. Thanks again!
