### ISSUE TITLE
Show how to setup DI and use appsettings.json config

### ISSUE THREAD

**Issue by lnaie** [dotnet/docs#12267]
As it says, by default that part of app building should be showcased in a clear manner.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Build a C# Hello World application with .NET Core in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Rick-Anderson** [comment]
Recommend closing. DI is beyond the scope of this introduction.

**Comment by tdykstra** [comment]
>Recommend closing. DI is beyond the scope of this introduction.

Agreed
