### ISSUE TITLE
Remove or update Compiling the Code in how-tos

### ISSUE THREAD

**Issue by svick** [dotnet/docs#12268]
Several How-to guides in Parallel Programming in .NET, e.g. [*How to: Create Pre-Computed Tasks*](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-create-pre-computed-tasks#compiling-the-code), contain a section like the following:

> ## Compiling the Code  
>  Copy the example code and paste it in a Visual Studio project, or paste it in a file that is named `CachedDownloads.cs` (`CachedDownloads.vb` for Visual Basic), and then run the following command in a Developer Command Prompt for Visual Studio window.  
>   
>  Visual C#  
>   
>  **csc.exe CachedDownloads.cs**  
>   
>  Visual Basic  
>   
>  **vbc.exe CachedDownloads.vb**  

I believe this section is not useful: anyone who's looking into parallel programming in .Net should already understand how to compile code. In case you think such a section is actually useful, it should be updated to use `dotnet` instead of `csc` and `vbc`.

**EDIT** by Thraka: Add document header info for automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e64eba6-e183-dfd7-fc52-deaf8a717ed6
* Version Independent ID: f2135220-cdf6-a4bb-5f2a-9a5c0ac6fbdf
* Content: [How to: Create Pre-Computed Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-create-pre-computed-tasks)
* Content Source: [docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Agreed. I think it should be removed. @rpetrusha is the author of that article, what do you think?

**Comment by rpetrusha** [comment]
Yes. It should definitely be removed. In fact, this section should probably be removed in most of the instances in which it appears in our doc set.
