### ISSUE TITLE
command "dotnet tool install -g mlnet" is not working

### ISSUE THREAD

**Issue by myusrn** [dotnet/docs#12263]
I execute the command "> dotnet tool update -g mlnet" and it produces the following output. If this is just expected to work as the page suggests then it would seem a dependency or command parameter, e.g. --version #.#.# ,  is missing from the instructions.

```
d:\src\repos>dotnet --list-sdks
2.1.602 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

d:\src\repos>dotnet tool install -g mlnet
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\NuGet.targets(119,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/myusrn/_packaging/myfeed/nuget/v3/index.json. [d:\src\temp\z0qccm5x.r1m\restore.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\NuGet.targets(119,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\src\temp\z0qccm5x.r1m\restore.csproj]
The tool package could not be restored.
Tool 'mlnet' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

d:\src\repos>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200d7af-ea16-7b93-5263-6a1ce41ecb3b
* Version Independent ID: e1697ee4-9d3a-e1cc-b678-cab88f1b5f86
* Content: [How to install the ML.NET Command-Line Interface (CLI) tool - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli)
* Content Source: [docs/machine-learning/how-to-guides/install-ml-net-cli.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-ml-net-cli.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi, @myusrn. The prerequisites state that .NET Core 2.2 SDK is needed for this tool.  Retry it with 2.2 instead of 3.0 preview and you should be good to go. Closing as this issue is resolved. Thanks!

**Comment by myusrn** [comment]
Thanks for details.  Are you aware of how one tells the C:\Program Files\dotnet\dotnet.exe tool install command to use their 2.2.202 sdk installation and not the vs19 installed 3.0.100-preview# sdk installation?

**Comment by JRAlexander** [comment]
Try `dotnet tool update -g mlnet --framework netcoreapp2.2`

**Comment by myusrn** [comment]
Thanks for those details.  Doing more testing the issue was arising not from the vs19 installed dotnet core 3.0.100-preview sdk installed.  It was a result of the 401 accessed denied arising when the `dotnet tool install/update . . . ` command attempted to iterate through my set of defined nuget feeds and hit the one pointing at my azure devops nuget package feed where it appears there are no cached credentials in place.  I used vs19 | tools | options | nuget pacakage manager | package sources UI to uncheck/disable that package feed and after that the `dotnet tool install/update -g mlnet` command to succeed with dotnet core 3.0 sdk preview installed.
