### ISSUE TITLE
Figure contains two extra packages

### ISSUE THREAD

**Issue by dnutiu** [dotnet/docs#12272]
"MongoDB API for .NET is based on NuGet packages that you need to add to your projects, like in the Locations.API project shown in the following figure."

I believe that the mongocsharpdriver and Swashbuckle should not be included in the figure. Swashbuckle is for swagger and mongocsharpdriver's description says that is has been replaced by Mongo.Driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1e64c7-90e1-baec-014a-4da1e5465f92
* Version Independent ID: a8678959-883d-58f9-196d-939bfb73bea4
* Content: [Using NoSQL databases as a persistence infrastructure](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by dnutiu** [comment]
Maybe also suggest Mongo.Driver.Linq as a package

**Comment by mvelosop** [comment]
Hi @dnutiu, thanks for your feedback.

You're right.

Will drop the package and check everything keeps working and the update the image.
