### ISSUE TITLE
. delete me plz

### ISSUE THREAD

**Issue by jvanlangen** [dotnet/docs#12281]
A fixed size buffer cannot be passed as an array to a method. It's unsafe and for me it's useless..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e17dd8-f60c-5a5d-517f-61bb95e94667
* Version Independent ID: c9d34513-107b-0b82-cf77-1dba0ee650cb
* Content: [Fixed Size Buffers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers#feedback)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
I'll close this issue, @jvanlangen. Thanks for letting us know.
