### ISSUE TITLE
HttpClientFactory on WCF client

### ISSUE THREAD

**Issue by tabareh** [dotnet/docs#12288]
How can we apply HttpClientFactory and connection resiliency measures on this model? can it be a part of this document or a separate document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [WCF svcutil tool overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x#feedback)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@mlacouture can you comment on this?

**Comment by mlacouture** [comment]
@dasetser?

**Comment by dasetser** [comment]
@tabareh Take a look at the suggestion in https://github.com/dotnet/wcf/issues/3230. There's a feature that lets you control this. Since this document is just about a tool to generate the proxy and not about actually using WCF I don't think this is the correct place to document it.

**Comment by tabareh** [comment]
Thanks for the information!
