### ISSUE TITLE
Screenshots...

### ISSUE THREAD

**Issue by cgm-wmaisenhelder** [dotnet/docs#12289]
Some screenshots of how the tooltip is displayed, using the different XML documentation elements would be a great help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#feedback)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@gewarren Do you already show something like this in the Visual Studio docs? If so, I should link to it here.

**Comment by gewarren** [comment]
@BillWagner Unfortunately no, we don't.

**Comment by BillWagner** [comment]
This is a good idea @cgm-wmaisenhelder 

I've added it to our backlog for the next update to this article.
