### ISSUE TITLE
Docker links are broken

### ISSUE THREAD

**Issue by Megadesty** [dotnet/docs#12286]
Everything under `https://docs.microsoft.com/en-us/dotnet/framework/docker/` targets back to `https://docs.microsoft.com/en-us/dotnet/framework/`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04fb826-aa70-5a14-2a13-4eed6cbb304f
* Version Independent ID: 2835b981-f482-8fa2-df47-469291d93a5a
* Content: [.NET Framework documentation](https://docs.microsoft.com/en-us/dotnet/framework/)
* Content Source: [docs/framework/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by x10an14** [comment]
Can confirm this to be the case.

**Comment by Thraka** [comment]
This content was removed as running .NET Framework on Docker is well documented across the internet and we're not investing in this scenario (for docs) and instead working on improving the .NET Core Docker scenarios instead.

@mikkelbu has opened a PR to clean up some of this misleading links. Sorry about the confusion.
