### ISSUE TITLE
Missing line in the ch. 'The Individual Capture'

### ISSUE THREAD

**Issue by valakiBF** [dotnet/docs#12291]
Last line is missing from the last example. It should be read as:
'       Seattle               58

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5d0b23-de01-afd4-9f17-dda8a9d64c3f
* Version Independent ID: d404df32-7a2b-0598-76a2-8b3b67fe18a0
* Content: [The Regular Expression Object Model](https://docs.microsoft.com/en-us/dotnet/standard/base-types/the-regular-expression-object-model#feedback)
* Content Source: [docs/standard/base-types/the-regular-expression-object-model.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/the-regular-expression-object-model.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for reporting this issue, @valakiBF. We've corrected the output in dotnet/samples#893.
