### ISSUE TITLE
Mistake in page

### ISSUE THREAD

**Issue by kevinfoley** [dotnet/docs#12301]
"Returning from ref readonly members" includes this example:

    struct ImmutableArray<T>;
    {
        private readonly T[] array;

        public ref readonly T ItemRef(int i)
        {
            // returning a readonly reference to an array element
            return ref this.r1;
        }
    }

No field or property named 'r1' is defined, so this isn't valid code. Perhaps you meant "return ref array[i];"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ea814f-e453-a9df-2fc9-506c8ebdc051
* Version Independent ID: 110f7863-fd76-d621-e98f-b5b5c03f8af2
* Content: [Readonly references - C# 7.2 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.2/readonly-ref#feedback)
* Content Source: [proposals/csharp-7.2/readonly-ref.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for making that observation @kevinfoley 

You are correct. I've submitted a fix in dotnet/csharplang#2523
