### ISSUE TITLE
[New Topic] Documenting System.Data and System.Data.SqlClient

### ISSUE THREAD

**Issue by SpaceShot** [dotnet/docs#1230]
This idea came about when a developer asked me if .NET Core "supported ADO.NET".  I reviewed the code and saw System.Data.SqlClient.  I even tried it out.  Then I went looking for documentation similar to [ADO.NET Oveview](https://msdn.microsoft.com/en-us/library/h43ks021(v=vs.110).aspx).

I recognize that there is a reference to the APIs, perhaps autogenerated, such as [System.Data](https://docs.microsoft.com/en-us/dotnet/core/api/system.data) and [System.Data.SqlClient Namespace](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.sqlclient#System_Data_SqlClient)

I thought we could start talking about what a Working with Data section looks like in the dotnet docs.  There are links out to ASP.NET MVC docs (for Entity Framework) and the EF docs themselves, but samples and guidance for the System.Data portion of the framework is not there yet.

One thing that would be nice to address is exactly what to expect to be in .NET Core (System.Data.SqlClient for example) and what has been implemented by third parties or what will not be in the [dotnet/corefx](https://github.com/dotnet/corefx) repo.

This is a big topic, and while I thought there was a wealth of documentation on MSDN that is ripe to use as inspiration and copy, there would undoubtedly be changes.  I felt it was better to start a discussion and see what the guidance is today rather than suggest I am capable of providing a starting template.

For example:
Is the intent to no longer refer to direct System.Data usage as ADO.NET?
In what ways is System.Data (and what many people are looking for in System.Data.SqlClient) different from the .NET Framework?

**Comment by cartermp** [comment]
@mairaw is the ADO.NET overview part of the .NET Framework migration?

**Comment by mairaw** [comment]
yes @cartermp

**Comment by cartermp** [comment]
Awesome.  Closing this for now, @SpaceShot, since we are migrating over the ADO.NET documentation.
