### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#12305]
Hi the link in the section:
Experiments are highly configurable. See the AutoML API docs for a full list of configuration settings.
does not work and returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bb37d9-1c4d-5d5f-2ed6-2ef77f2cd627
* Version Independent ID: 80ed0d4d-63d3-49f0-ae42-d1f132137352
* Content: [How to use the ML.NET automated ML API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api)
* Content Source: [docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for the feedback, @PeterPann23! I've submitted the PR with the fix.
