### ISSUE TITLE
how to use the `dotnet build` to also compile typescript file like visual studio does?

### ISSUE THREAD

**Issue by John0King** [dotnet/docs#12303]
When use visual studio build a asp.net core web project , the typescript file with a `tsconfig.json` will be compile by the `tsc`.
How can I do it with `dotnet build` or `dotnet publish` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Is this supported @KathleenDollard @livarcocc?

**Comment by livarcocc** [comment]
This is not supported by dotnet.

**Comment by mairaw** [comment]
Closing then since this is a product question.
