### ISSUE TITLE
'RegressionCatalog.RegressionTrainers' does not contain a definition for 'FastTree' and no accessible extension method 'FastTree' accepting a first argument of type 'RegressionCatalog.RegressionTrainers' could be found.

### ISSUE THREAD

**Issue by sculptsoft-devs** [dotnet/docs#12314]
Getting following error while running machine-learning/tutorials/TaxiFarePrediction/Program.cs with ML.Net 1.0

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'RegressionCatalog.RegressionTrainers' does not contain a definition for 'FastTree' and no accessible extension method 'FastTree' accepting a first argument of type 'RegressionCatalog.RegressionTrainers' could be found (are you missing a using directive or an assembly reference?)	TaxiFarePrediction	E:\Demos\dotnet\mldotnet\TaxiFarePrediction\TaxiFarePrediction\Program.cs	56	Active

**Comment by JRAlexander** [comment]
Hi, @sculptsoft-devs! Add the NuGet package reference for **Microsoft.ML.FastTree** and you should be good to go. I've updated the tutorial with the above PR.

**Comment by Prasit5** [comment]
It still doesn;t work after adding Microsoft.ML.FastTree
