### ISSUE TITLE
Return Values from MemoryMappedFile.CreateViewStream & CreateViewAccessor

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#12319]
I see some not correct information on this page:

To obtain a _UnmanagedMemoryStream_ object for a sequentially accessed view to the memory-mapped file. | MemoryMappedFile.CreateViewStream method.

To obtain a _UnmanagedMemoryAccessor_ object for a random access view to a memory-mapped fie. | MemoryMappedFile.CreateViewAccessor method.

I think it must be corrected to next

To obtain a **MemoryMappedViewStream** object for a sequentially accessed view to the memory-mapped file. | MemoryMappedFile.CreateViewStream method.

To obtain a **MemoryMappedViewAccessor** object for a random access view to a memory-mapped fie. | MemoryMappedFile.CreateViewAccessor method.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc02010-ec28-4e04-0881-7cd1d9d8b148
* Version Independent ID: c5261008-5deb-2af9-647f-f07ec56d9e47
* Content: [Memory-Mapped Files](https://docs.microsoft.com/en-gb/dotnet/standard/io/memory-mapped-files)
* Content Source: [docs/standard/io/memory-mapped-files.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/memory-mapped-files.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@DSivtsov Thanks for reporting this error.  We'll put it on our backlog and get it fixed when it fits into our schedule.
