### ISSUE TITLE
Order of statements causing issue when we have to await

### ISSUE THREAD

**Issue by waratah** [dotnet/docs#12318]
I am writing this in an Async module and the specified order of statements has to change.  I have to push all the data to the transform block,  tell it to complete then await the countBytes.Completion. Not doing this causes my unit test to never complete.

      // Link the TransformBlock<string, int> object to the 
      // ActionBlock<int> object.
      countBytes.LinkTo(printResult);

     // Requests completion of the TransformBlock<string, int> object.
     countBytes.Complete();

      // Create a continuation task that completes the ActionBlock<int>
      // object when the TransformBlock<string, int> finishes.
      countBytes.Completion.ContinueWith(delegate { printResult.Complete(); });

      // Post the path to the temporary file to the 
      // TransformBlock<string, int> object.
      countBytes.Post(tempFile);

     

My Example in Async:

        private async Task<ValidationResult> ValidationResult(Application application)
        {
            var errors = new List<ValidationFailure>();

            var tb = new TransformBlock<IApplicationValidator, ValidationResult>(async (IApplicationValidator validator) => await validator.Validate(application), new ExecutionDataflowBlockOptions { MaxDegreeOfParallelism = 4});
            var ab = new ActionBlock<ValidationResult>(x => { errors.AddRange(x.Errors); } );
            tb.LinkTo(ab);

            foreach (var v in _validators)
            {
                tb.Post(v);
            }
            tb.Complete();

            await tb.Completion.ContinueWith( delegate  { ab.Complete(); });
            await ab.Completion;

            var result = new ValidationResult(errors);
            return result;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a6110b4-53f4-e659-4afa-2d2ac3094657
* Version Independent ID: 26a41489-10b7-d408-099c-48ee8d8ba085
* Content: [How to: Perform Action When a Dataflow Block Receives Data](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-perform-action-when-a-dataflow-block-receives-data#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-perform-action-when-a-dataflow-block-receives-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-perform-action-when-a-dataflow-block-receives-data.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
It's true that calling `Post` after `Complete` will not work. But as far as I can tell, this page never does that. Its code is:

```c#
      // Post the path to the temporary file to the 
      // TransformBlock<string, int> object.
      countBytes.Post(tempFile);

      // Requests completion of the TransformBlock<string, int> object.
      countBytes.Complete();
```

So I don't think this is actually an issue with this page.
