### ISSUE TITLE
PlatformNotSupportedException on .NET Core 2.2

### ISSUE THREAD

**Issue by anticrisis** [dotnet/docs#12313]
I know this is an old example, but I was just confused by it as I attempted to make a quick dotnet console app to try it out.

It may be worth noting that the ToXmlString API is not currently supported on .NET Core: https://github.com/dotnet/corefx/issues/23686

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf319632-8038-7d57-38ee-c6423c02c1d2
* Version Independent ID: b7f7eb2d-0422-0699-ff0d-143cce350731
* Content: [How to: Store Asymmetric Keys in a Key Container](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-store-asymmetric-keys-in-a-key-container)
* Content Source: [docs/standard/security/how-to-store-asymmetric-keys-in-a-key-container.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-store-asymmetric-keys-in-a-key-container.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Sorry about the confusion. As you can see from that linked bug, this is a pain point for multiple people. I'll add this to the backlog and see what we can do.

**Comment by tdykstra** [comment]
The sample code runs on .NET Core 3.1. I'll add a note to the alert box at the top of the page indicating that it requires 3.1.
