### ISSUE TITLE
UseModelWithBatchItems

### ISSUE THREAD

**Issue by garricknorthover** [dotnet/docs#12320]
Hi guys, just a typo.
The call to UseModelWithBatchItems from the main method includes model as an argument but the method definition just had mlContext as a parameter.

So I think
```
public static void UseModelWithBatchItems(MLContext mlContext)
{

}
```
needs to be 

```
public static void UseModelWithBatchItems(MLContext mlContext, ITransformer model)
{

}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @garricknorthover, we'll get this fixed asap. Good catch!
