### ISSUE TITLE
CardType is abstract

### ISSUE THREAD

**Issue by eeskildsen** [dotnet/docs#12326]
I think the sample class is incorrect:

    public abstract class CardType : Enumeration

If CardType is abstract, how can its members instantiate it:

    public static CardType Amex = new CardType(1, "Amex");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @eeskildsen, thanks for the heads up! 👍

You're right, that's not the actual code:

https://github.com/dotnet-architecture/eShopOnContainers/blob/1d0a66c21a783c9b8c6fb76b71b1301a3a63cff2/src/Services/Ordering/Ordering.Domain/AggregatesModel/BuyerAggregate/CardType.cs#L9-L15

It's some remnant from the previous code.

Thanks 😊
