### ISSUE TITLE
Wrong code snippet in chapter Classify images with a loaded model

### ISSUE THREAD

**Issue by coding4funrocks** [dotnet/docs#12330]
One of the code snippets for the ClassifyImages method is wrong, it should call ReadFromTsv and convert to IDataView, like this:

var imageDataView = mlContext.Data.LoadFromEnumerable(ReadFromTsv(dataLocation, imagesFolder));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Build an ML.NET custom image classifier with TensorFlow - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi! Thanks for the feedback, @coding4funrocks! Closing this as this issue was fixed earlier today with this PR: https://github.com/dotnet/docs/pull/12324. The changes should be live in the next day or so. Thanks!
