### ISSUE TITLE
Can't find info on machine.conf file considering deployment of ADO.NET providers

### ISSUE THREAD

**Issue by progalgo** [dotnet/docs#12345]
Is there a particular best practice on locking the file for editing while installing our in-house ADO.NET provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b87e17b-2c03-c2cd-b821-66d96ffc0616
* Version Independent ID: 74ab8406-068b-38d0-8948-39a93e4e3b1f
* Content: [Deploying the .NET Framework and Applications](https://docs.microsoft.com/en-us/dotnet/framework/deployment/)
* Content Source: [docs/framework/deployment/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/deployment/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello!

Sorry to say, but this article is not the right place to ask that question. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow.

I'm going to close the issue. 

Thanks.
