### ISSUE TITLE
Uppercase or lowercase for Tuple property names?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#12346]
What is the convention for naming tuple properties?

```csharp
(string Person, int Age)
```

or 

```csharp
(string person, int age)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [What's New in C# 7.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#tuples)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good question @weitzhandler 

I don't know that we've addressed his in our own codebases.  @jaredpar Is there an accepted practice for tuple member names and casing?

**Comment by jaredpar** [comment]
@terrajobst is driving the decision here. Not sure it's final final but the outcome is going to be that tuple names should be cased the same way you case property names.

**Comment by BillWagner** [comment]
Thanks @jaredpar 

>  tuple names should be cased the same way you case property names.

@terrajobst  If you're comfortably with that guidance, I'll add this issue to our "up for grabs" queue for community contributions.

**Comment by weitzhandler** [comment]
> tuple names should be cased the same way you case property names

I'd vote for that to. Public members should be pascal cased.

**Comment by BillWagner** [comment]
Thanks folks. I've added this to the backlog, and added the "up for grabs" label.

**Comment by weitzhandler** [comment]
Actually not that simple.
Local variables might have different behavior. If you're going to make an official documentation about it, it should have clear rules.

For instance:

```c#
int x = 5, y = 10;

var t = (x, y);

x = t.x;
y = t.y;
```

**Comment by terrajobst** [comment]
The decision that we landed on is indeed PascalCase.

**Comment by SeanKilleen** [comment]
@BillWagner I went through the referenced doc and it appears all of the associated samples are in line with this naming convention guidance as far as I can tell.

Is there anywhere explicitly that you'd like this guidance added additionally? If not, this can likely be closed at this point.

**Comment by BillWagner** [comment]
Thanks @SeanKilleen 

I'll close this. 

> Is there anywhere explicitly that you'd like this guidance added additionally? If not, this can likely be closed at this point.
