### ISSUE TITLE
Little change

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12347]
@campelo commented on [Tue May 14 2019](https://github.com/dotnet/docs.pt-br/issues/125)

In BasicFunctions
printfn "The result of applying the 2nd sample function to (6.5 + 4.5) is %f" result3
2nd should be changed by 3rd.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour do F#](https://docs.microsoft.com/pt-br/dotnet/fsharp/tour)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is making a suggestion in the code example
best regards

**Comment by rpetrusha** [comment]
@cartermp, could you take a look at this issue?
