### ISSUE TITLE
Wrong collection name in code snippet of BlockingCollection

### ISSUE THREAD

**Issue by mikaelmello** [dotnet/docs#12348]
The code snipper mentions a `numbers` collection while in fact the name of  the collection is `dataItems`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ab9298-8ed6-2a79-47c0-55021199ced6
* Version Independent ID: 32d003fc-b7de-37b7-02c5-0719a8878e2a
* Content: [BlockingCollection Overview](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/blockingcollection-overview)
* Content Source: [docs/standard/collections/thread-safe/blockingcollection-overview.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/blockingcollection-overview.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing out the incorrect variable name in the comment, @mikaelmello. We've corrected it in dotnet/samples#909.
