### ISSUE TITLE
Referenced Gartner article has controlled access

### ISSUE THREAD

**Issue by mvark** [dotnet/docs#12344]
While the outline of the Gartner article "How to Architect and Design Cloud-Native Applications" mentioned in this page looks very useful, it is accessible only to subscribers. Is there any chance Microsoft can make it available for general public?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c2ea442-b723-cf72-3444-4492f9f8ba1d
* Version Independent ID: 94020274-6eb7-f30d-7c5e-18a53af50d8c
* Content: [What about Cloud-Native applications?](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/what-about-cloud-native-applications#feedback)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/what-about-cloud-native-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/what-about-cloud-native-applications.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil please take a look at this feedback

**Comment by mvelosop** [comment]
Will change the link to the brand-new [Cloud Native](https://docs.microsoft.com/dotnet/architecture/cloud-native/definition) guide!
