### ISSUE TITLE
no isntructions how to check for linux

### ISSUE THREAD

**Issue by rbavery** [dotnet/docs#12356]
I need to debug my azure file explorer installation, which according to this issue means checking what .NET I have installed: https://github.com/microsoft/AzureStorageExplorer/issues/1205

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hello!

The .NET Framework is not available on Linux, you have to use either Mono or .NET Core. 

Looking at your linked issue it seems it's running .NET Core. You can see the list of available runtimes by calling `dotnet --list-runtimes`

I'm going to close this issue as I think I answered your question. Let me know if this doesn't work. Thanks!

**Comment by mairaw** [comment]
You should probably check out the article they linked from that issue as well: https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting
