### ISSUE TITLE
.NET Framework on Docker Guide

### ISSUE THREAD

**Issue by FimePradeep** [dotnet/docs#12364]
.NET Framework on Docker Guide - Navigating same page. no details about docker .net framework run and install guide. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04fb826-aa70-5a14-2a13-4eed6cbb304f
* Version Independent ID: 2835b981-f482-8fa2-df47-469291d93a5a
* Content: [.NET Framework documentation](https://docs.microsoft.com/en-gb/dotnet/framework/#feedback)
* Content Source: [docs/framework/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
That has been fixed by #12298 and goes live, most probably, within next 12 hours.

**Comment by Thraka** [comment]
Duplicate of #12298

**Comment by Thraka** [comment]
Duplicate of #12286
