### ISSUE TITLE
.NET language support? 

### ISSUE THREAD

**Issue by taiwoa** [dotnet/docs#12372]
Is there support for all .NET languages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-members-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by TheOneTrueTrench** [comment]
Are you asking if a C# language feature is supported by other languages?

Just want to make sure I understand your question.

**Comment by BillWagner** [comment]
@KathleenDollard and @cartermp would have to speak to the support for default interface members in VB and F#, respectively. There are also runtime considerations with @terrajobst can discuss.

Between now and .NET Core 3.0 release, we'll fill out the full story with other articles here and in the .NET Core section.

**Comment by KathleenDollard** [comment]
Consuming default interface methods are in our plans for Visual Basic.NET. 

At least initially, we plan to support consuming, but not creating them. There are higher priority features for Visual Basic.NET.

**Comment by taiwoa** [comment]
> Are you asking if a C# language feature is supported by other languages?
> 
> Just want to make sure I understand your question.

I am referring to the "default interface methods" feature specifically.

Thanks.

**Comment by taiwoa** [comment]
> Consuming default interface methods are in our plans for Visual Basic.NET.
> 
> At least initially, we plan to support consuming, but not creating them. There are higher priority features for Visual Basic.NET.

Thanks Kathleen. Please where may one find the list of the higher priority features planned for Visual Basic.NET?

Best regards!

**Comment by BillWagner** [comment]
I'm keeping this open to address the correct location for information on F# and VB support. Once we provide that info, I'll close this as the current article won't address those languages.

**Comment by BillWagner** [comment]
Closing.
