### ISSUE TITLE
Grammatical error in DatePicker States Descriptions

### ISSUE THREAD

**Issue by tf-egoldman** [dotnet/docs#12377]
"The HasError attached property is true has the control has focus." should be something like "When the HasError attached property is true it means the control has focus." or "The HasError attached property being true indicates that the control has focus."

The description for InvalidUnfocused is similarly wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd717a09-79f4-a8f9-b74d-35ee0315566c
* Version Independent ID: d4681169-14d4-309f-8998-4cbfdb360282
* Content: [DatePicker Styles and Templates](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/datepicker-styles-and-templates)
* Content Source: [docs/framework/wpf/controls/datepicker-styles-and-templates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/datepicker-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @tf-egoldman. I've opened PR #12875 to fix this.
