### ISSUE TITLE
Not good

### ISSUE THREAD

**Issue by tedyyu** [dotnet/docs#12370]
To be honest, WIF sample is scattered in many places and badly organized and kindof outdated (espeically embeddedSTS coupled with VS 2012). Try to learn from WCF samples and share some updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e2597b9-aff9-0810-01de-03c51e438deb
* Version Independent ID: 4cb0838d-2778-f634-d2ea-2a1b9b04240a
* Content: [WIF Code Sample Index](https://docs.microsoft.com/en-us/dotnet/framework/security/wif-code-sample-index)
* Content Source: [docs/framework/security/wif-code-sample-index.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/wif-code-sample-index.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
The WIF content hasn't been maintained for a long time and has now been archived as-is. Apologies for the inconvenience.
