### ISSUE TITLE
ResultsDirectory missing documentation

### ISSUE THREAD

**Issue by HoraceBury** [dotnet/docs#12371]
The `--ResultsDirectory` option is missing documentation. Does it have the alternative name `--results-directory` as accepted by `dotnet test`?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c66d2f-86f4-6472-a4c8-30e4203a10de
* Version Independent ID: 224583f2-3ca3-5c97-4cd4-fcd3d6a64f91
* Content: [dotnet vstest command - .NET Core CLI](https://docs.microsoft.com/en-gb/dotnet/core/tools/dotnet-vstest?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet-vstest.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-vstest.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Good catch @HoraceBury! We're missing this option indeed.

I'll update this topic as I review the CLI commands for 2.2 and 3.0 releases in the next few weeks.

@KathleenDollard @livarcocc can you comment on which option name can be used with that command? Are both `--ResultsDirectory` and `--results-directory` accepted?

**Comment by livarcocc** [comment]
`dotnet test` is actually owned by a separate team. I am not sure who over there could answer this questions.

@kendrahavens can you help point us to the right contact on the dotnet test team?

**Comment by kendrahavens** [comment]
@PBoraMSFT may be able to help

**Comment by prawalagarwal** [comment]
@mairaw --ResultsDirectory is the only accepted way with dotner vstest
