### ISSUE TITLE
A complete sample source file

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12383]
The best thing to do is to provide a complete sample source file with all examples, commented. There should be a file like that for every release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @daveyostcom 

Adding @LadyNaggaga to this discussion.

We are working on something like that, based on what was demoed at build.

**Comment by BillWagner** [comment]
Closing based on work in [dotnet/try-samples](https://github.com/dotnet/try-samples).  See https://github.com/dotnet/try-samples/tree/master/csharp8 for details.
