### ISSUE TITLE
Object Initialisation

### ISSUE THREAD

**Issue by SujanChristo** [dotnet/docs#12385]
In the ReadToObject method in the above example, is the initialization line "User deserializedUser = new User();" is needed provided we initialize the DataContractJsonSerializer as "DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(User));"? The reason is, we are instantiating a new User Instance and again to that assigning the serialized user. Is there any advantage in the above way of coding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ee09ba-3e07-b558-1e18-0af2afbd3809
* Version Independent ID: 93820b68-aa8a-7cdd-c952-60e5e4118252
* Content: [How to: Serialize and Deserialize JSON Data](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data)
* Content Source: [docs/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!

**Comment by Thraka** [comment]
@HongGit Can someone from your team validate that using the deserializer with `typeof` vs `obj.GetType()` matters? Unsure why `User deserializedUser = new User();` is created and used with `deserializedUser.GetType()` instead of just calling `typeof(User)`?

Here is the code we're referring to:

```csharp
// Create a User object and serialize it to a JSON stream.  
public static string WriteFromObject()  
{  
    //Create User object.  
    User user = new User("Bob", 42);  
  
    //Create a stream to serialize the object to.  
    MemoryStream ms = new MemoryStream();  
  
    // Serializer the User object to the stream.  
    DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(User));  
    ser.WriteObject(ms, user);  
    byte[] json = ms.ToArray();  
    ms.Close();  
    return Encoding.UTF8.GetString(json, 0, json.Length);  
}  
  
// Deserialize a JSON stream to a User object.  
public static User ReadToObject(string json)  
{  
    User deserializedUser = new User();  
    MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(json));  
    DataContractJsonSerializer ser = new DataContractJsonSerializer(deserializedUser.GetType());  
    deserializedUser = ser.ReadObject(ms) as User;  
    ms.Close();  
    return deserializedUser;  
}  
```

**Comment by dasetser** [comment]
@Thraka It should not matter which they use in this case. The obj.GetType() method is used to get the actual type at runtime, where typeof is you defining it at compile time. Calling GetType on an object that was initialized as a new User() right before will have the same result as using typeof(User). 

My guess is they wrote it this way to keep the steps of the Read method similar to the Write method since they kind of mirror each other. However, it would still be correct if you removed the first line of `ReadToObject()`, changed `deserializedUser.GetType()` to `typeof(User)`, and on the next line changed `deserializedUser =` to `User deserializedUser =`.

**Comment by Thraka** [comment]
Yeah, I figured that too. I just saw some info about ensuring some object gets deserialized as the appropriate derived class versus the base class so I wanted to just make sure that the example wasn't written in some specific way as a "best practice" in avoid some conflict or something..
