### ISSUE TITLE
just a fun little nit on the functional example...

### ISSUE THREAD

**Issue by radams0x** [dotnet/docs#12380]
I would fry the bacon first, so you can fry the eggs in the grease. And absolutely pour the coffee last, so it doesn't get cold ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @radams0x 

I think we can compromise and pour the coffee first, drink some while cooking, then warming it up before enjoying a great breakfast. 🥓 ☕️
