### ISSUE TITLE
Syntax Highlighting Missing

### ISSUE THREAD

**Issue by danysdragons** [dotnet/docs#12387]
Previously the documentation for C# had syntax-highlighting, but this seems to have disappeared recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0768b9b7-793f-db11-d109-7c0379b946b9
* Version Independent ID: 1d49e8c1-c610-d406-27da-5675380aecda
* Content: [How to: Query for Characters in a String (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-query-for-characters-in-a-string-linq#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-query-for-characters-in-a-string-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-query-for-characters-in-a-string-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @danysdragons 

It appears to have been fixed. Please let us know if you encounter this again.
