### ISSUE TITLE
Inaccurate description

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12399]
@bullipatty commented on [Wed May 08 2019](https://github.com/dotnet/docs.de-de/issues/140)

Ich lerne gerade VB und mindestens in der Deutschen und Englischen Version finde ich die folgende Zeile ungenau:
"Dieser Code ersetzt die bestehenden Anweisungen Console.WriteLine, Console.Write und Console.ReadKey."
Console.WriteLine, Console.Write und Console.ReadKey sind Methoden und keine kompletten/gültigen Anweisungen bzw Statements. Der Unterschied scheint nicht groß, hat mich aber trotzdem eben fast eine Minute verwirrt und stoppen lassen.
Besser wäre zum Beispiel:
"Dieser Code ersetzt den Inhalt der Main Methode." oder:
"Dieser Code ersetzt die bestehenden Aufrufe von Console.WriteLine, Console.Write und Console.ReadKey."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 10fd8911-61a3-05cb-4f72-ff128be2a632
* Version Independent ID: 9b8e4ffe-d069-f6f3-a326-c33c03f365b4
* Content: [„Hallo Welt“-Anwendung in Visual Basic mit .NET Core in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/de-de/dotnet/core/tutorials/vb-with-visual-studio#feedback)
* Content Source: [docs/core/tutorials/vb-with-visual-studio.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/tutorials/vb-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---

@CeciAc commented on [Wed May 08 2019](https://github.com/dotnet/docs.de-de/issues/140#issuecomment-490502873)

Hallo, @bullipatty 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team 

---

@CeciAc commented on [Thu May 16 2019](https://github.com/dotnet/docs.de-de/issues/140#issuecomment-493238640)

Issue moved to [dotnet/docs #12398](https://github.com/dotnet/docs/issues/12398) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is suggesting a change in the original documentation

Translation:
The sentence 

  This code replaces the existing Console.WriteLine, Console.Write, and Console.ReadKey statements.

should be replaced with either of the following:

  This code replaces the contents of the Main method.
  This code replaces the existing Console.WriteLine, Console.Write, and Console.ReadKey calls.

**Comment by mairaw** [comment]
Thank you for feedback @bullipatty. I've opened PR #12456 to fix this issue.
