### ISSUE TITLE
Incorrect sample code

### ISSUE THREAD

**Issue by mj1856** [dotnet/docs#12397]
There are three things wrong with the sample code here:

- The default buffer size is 2GB, not 64KB. There's no need to set it explicitly in most cases.
- HttpClient is meant to be created as a single instance and shared, not created for each request (or for each click of the button in this case).
- The line that calls downloadTasksQuery.ToArray() is unnecessary. Once you start awaiting tasks, they will start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702427b0-0bcc-1152-75a5-c909717723c0
* Version Independent ID: 0dbb92ca-4166-ceaf-1083-1280703a9c15
* Content: [How to: Extend the async Walkthrough by Using Task.WhenAll (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall)
* Content Source: [docs/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @mj1856 

The async area will be updated shortly. This is helpful to address these concerns.
