### ISSUE TITLE
Write examples to better fit in with GFM limitations

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#12393]
There are a few issues with the display of code examples on this page and on the corresponding [Visual Basic page](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio):

* Because GFM doesn't support code blocks within tables, multiple lines of code get written as inline code blocks on separate lines, which wreaks havoc with spacing; or is written entirely on one line.
* GFM doesn't support syntax highlighting for inline code.

The Visual Basic page places each VB code example, and each DebugView result, in a separate code block. That resolves these issues, but is extremely long.

I propose that each example should be in a code block, and the DebugView result should be in a comment underneath. Instead of:

|Expression|`DebugView` property|  
|----------------|--------------------------|  
|`LambdaExpression lambda =  Expression.Lambda<Func<int>>(Expression.Constant(1));`|`.Lambda #Lambda1<System.Func'1[System.Int32]>() {`<br /><br /> `1`<br /><br /> `}`|  
|`LambdaExpression lambda =  Expression.Lambda<Func<int>>(Expression.Constant(1), "SampleLambda", null);`|`.Lambda SampleLambda<System.Func'1[System.Int32]>() {`<br /><br /> `1`<br /><br /> `}`|  

write:

```csharp
LambdaExpression lambda = Expression.Lambda<Func<int>>(Expression.Constant(1));
/*
    .Lambda #Lambda1<System.Func`1[System.Int32]>() {
        1
    }
*/
LambdaExpression lambda = Expression.Lambda<Func<int>>(Expression.Constant(1), "SampleLambda", null);
/*
    .Lambda SampleLambda<System.Func`1[System.Int32]>() {
        1
    }
*/
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd39193-a203-2326-7b45-79ea0015733f
* Version Independent ID: 76254616-be05-0da1-b706-6239941c2d20
* Content: [Debugging Expression Trees in Visual Studio (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @zspitz 

I've added it to our next sprint to address.

**Comment by zspitz** [comment]
@BillWagner Is there any possible solution aside from what I've proposed -- putting the results as comments together with the code in a single code block?

**Comment by BillWagner** [comment]
@zspitz I like your solution. That's likely what I'll do in the next sprint. If you'd like to submit a PR before then, I'll watch for it, and review and merge it.

**Comment by zspitz** [comment]
@BillWagner I would be willing to do this, together with #12462 (if #12462 is a good idea).

**Comment by BillWagner** [comment]
@zspitz I like your proposal.

I'll assign both these issues to you, and I'll watch for upcoming PRs.

**Comment by zspitz** [comment]
@BillWagner Some questions:

1. What do I put as my Microsoft alias in the new page?
2. Should `ms.topic` be `reference`?
