### ISSUE TITLE
Train the model section is incomplete

### ISSUE THREAD

**Issue by rsrobbins** [dotnet/docs#12415]
The Train the model section of the tutorial only shows one line of code "var model = pipeline.Fit(dataView);" when you actually need five lines as code as found in the Program.cs file.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using a regression algorithm - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for the feedback @rsrobbins! Which five lines are you referring to?

**Comment by rsrobbins** [comment]
These five lines of code:

```
Console.WriteLine("=============== Create and Train the Model ===============");

var model = pipeline.Fit(dataView);

Console.WriteLine("=============== End of training ===============");
Console.WriteLine();

return model;
```

**Comment by JRAlexander** [comment]
Ahh, thanks. We were missing the return model. Good catch!!!! I've referenced the PR fix above.
