### ISSUE TITLE
Enum.ToString's X format option documentation does not match implementation

### ISSUE THREAD

**Issue by smbogan** [dotnet/docs#12414]
The X formatting option documentation indicates that the value is padded to 8 hexadecimal digits.  It appears that the actual code pads it to the size of the underlying data type - specifically, the number of bits divided by 4 (or, equivalently, sizeof(T) * 2).  It seems like the code's behavior is more sensible than the documentation.

For example: 
enum X : short { E = 28 }

X.E.ToString("X") gives "001C", not "0000001C" as the documentation indicates it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b9c332-da26-ff62-8669-5697d5b9aa56
* Version Independent ID: 0049d705-a8ca-a4b5-c51d-b4f88bdf27e3
* Content: [Enumeration format strings - .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/enumeration-format-strings?view=netframework-4.8)
* Content Source: [docs/standard/base-types/enumeration-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/enumeration-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing our the error in the documentation, @smbogan. The source code for .NET Framework and .NET CoreFx also confirms that the value is padded based on the size of the underlying numeric type. We'll update the documentation accordingly.
