### ISSUE TITLE
ml.net document sentiment-analysis

### ISSUE THREAD

**Issue by djary** [dotnet/docs#12410]
in this tutorial https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#how-the-data-was-prepared

> **SentimentPrediction** is the prediction class used after the model training. It inherits from **SentimentData** for displaying the **SentimentText** with the predictions. **SentimentPrediction** has a single **boolean** (Sentiment) and a **PredictedLabel** **ColumnName** attribute. The Label is used to create and train the model, and it's also used with the split out test dataset to evaluate the model. The **PredictedLabel** is used during prediction and evaluation. For evaluation, training data, the predicted values, and the model are used.

Mistake occurred or I do not understand?

**SentimentPrediction** class inherits from **SentimentData** for displaying the **SentimentText** with the predictions. it ok, but **SentimentPrediction**  class has a single **boolean** (Sentiment) and a **PredictedLabel** ColumnName attribute. ? if your mean  are **SentimentPrediction** class Regardless of inheritance the class has **Prediction** boolean with **PredictedLabel ColumnName attribute** instead of **Sentiment** (in **SentimentData** class). and if we consider inheritance in **SentimentPrediction** class we have two boolean properties **Sentiment** with **Label ColumnName attribute** and **Prediction** with **PredictedLabel ColumnName attribute**

Is the text explained right?

edit by @mairaw: added topic details

[AB#1530397](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1530397)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#how-the-data-was-prepared)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Thank you for the feedback @djary. @JRAlexander can you please have a look at the wording of this para, and clarify as needed.
