### ISSUE TITLE
Doesn't list breaking change to Nullable

### ISSUE THREAD

**Issue by heaths** [dotnet/docs#12417]
Originally, the MSBuild property was `NullableReferenceTypes`, then changed to `NullableContextOptions`, but now in Visual Studio 2019 16.2 Preview this is now `Nullable` and is a breaking change that should've been announced here. Not sure if this is a change to the .NET Core 3.0 SDKs (`dotnet --list-sdks` doesn't show anything newer) or the Microsoft.NET.SDK build targets, but certainly affects using C# 8.0 features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @heaths.  
@KathleenDollard @rainersigwald can you comment on this change? We also need to do a migration topic for 3.0.

**Comment by rainersigwald** [comment]
@jaredpar is probably the most interested party here.

This is a breaking change but only from the previous prerelease; not sure if that changes the severity/desired doc level.

**Comment by BillWagner** [comment]
The MSBuild property change would also need to be updated in the C# section on nullable reference types.  That would affect these three articles:

- [Express designs with nullable reference types](https://docs.microsoft.com/dotnet/csharp/tutorials/nullable-reference-types)
- [Migrate applications to nullable reference types](https://docs.microsoft.com/dotnet/csharp/tutorials/upgrade-to-nullable-references)
- [Overview of Nullable Reference Types](https://docs.microsoft.com/dotnet/csharp/nullable-references).

I can update those.  (The code samples would also need updating.

**Comment by heaths** [comment]
@rainersigwald it may be prerelease, but a lot of stuff in the docs are prerelease. Those of us dogfooding the prereleases need to be aware of breaking changes as well.

**Comment by BillWagner** [comment]
@Thraka 

See PR #12497  That updated all the docs for the C# Guide I referenced above.  Thanks @KexyBiscuit 

A quick check in the other .NET Core docs didn't find other occurrences of `NullableContextOptions`. If you agree, I think we can close this.
