### ISSUE TITLE
Add info on stopping app pool recycles, so that IWebHost doesn't die.

### ISSUE THREAD

**Issue by SteveKennedy** [dotnet/docs#12422]
It would be helpful if this document included more information to the reader around "...your host can be shut down because of app pool recycles."  Specifically, strategies around eliminating app pool recycles on hosted IIS.

As a reader, I would want to know, what is the setting changes I could do to an IIS hosted web application to ensure the app pool does not recylce (or recycle often), so that my hosted IWebHost background service doesn't die. What are the consequences of disabling recycling?

It is peculiar that this document doesn’t mention changing the app pool settings accordingly, when using hosted IIS.  It seems to direct readers toward containers. Not everyone uses containers. Not everyone is in the cloud. What is a simple IIS hosted solution?

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#deployment-considerations-and-takeaways

edit by @mairaw: added topic details and updated link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil can you look at this feedback?

**Comment by nishanil** [comment]
Hey @SteveKennedy Thanks for your feedback, This section in the documentation is part of our Architecture Guide/e-book: [.NET Microservices: Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/) and hence it focusses only on Containers and their deployment using orchestrators like Kuberenetes. In this context, when an app with a background task is deployed using orchestrator such as Kubenetes, they are guaranteed to be alive.  

IIS hosting scenario covering app pool recycling settings are beyond the scope of this book. Hence we only mention considering app recycle setting in case you decide to run the background task there.  Here's an article that I found may be useful to you: https://dev.to/ankitvijay/net-core--running-background-worker-on-iis-54ho

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
