### ISSUE TITLE
Another resource demonstrating subclassable typed enumeration classes using generics

### ISSUE THREAD

**Issue by TyreeJackson** [dotnet/docs#12431]
http://tyreejackson.com/subclassable-enums/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Good read. Thanks for sharing @TyreeJackson
