### ISSUE TITLE
Docs out of date?

### ISSUE THREAD

**Issue by Brian-Willoughby** [dotnet/docs#12432]
I am using Visual Studio on macOS. When I follow the instructions above to Enable automatic binding redirects, instead of "Unload Project," I see only "Unload." Then, instead of seeing "Edit [projectname.csproj]," I see an "Tools" submenu with an "Edit File" item. As a brand new user, I may have selected the wrong file at the start, but I did end up editing a file with the expected &lt;PropertyGroup&gt; tag, and when I added &lt;AutoGenerateBindingRedirects&gt;true, it did solve the build problem I was previously experiencing.

So, this page did solve my issue, but either this page is out of date or the macOS version of Visual Studio itself is out of date. My suggestion is that it would be helpful for macOS users if this page's instructions were in sync with what users will see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [Enable or disable autogenerated binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#feedback)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by IsaacLeeWebDev** [comment]
One year later, and Visual Studio for Mac is still not in sync with the docs.
