### ISSUE TITLE
missing using namespaces?

### ISSUE THREAD

**Issue by an31146** [dotnet/docs#12434]
For the uninitiated, this example should also include at the top:
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066ffeec-641e-58a8-d863-da3847b64535
* Version Independent ID: 8c3f9deb-6690-d4e8-e1d5-004b3e649f09
* Content: [How to: Implement Dynamic Partitions](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-implement-dynamic-partitions)
* Content Source: [docs/standard/parallel-programming/how-to-implement-dynamic-partitions.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-implement-dynamic-partitions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!

**Comment by Thraka** [comment]
@rpetrusha Ron, I was going to fix this but looking at the source it seems like it's a huge file with lots of different stuff in it. Is there a master .sln or .proj file for the source? This way I can break it out into a different file and make sure it compiles.

**Comment by rpetrusha** [comment]
No, @Thraka, there's not a master solution or project file for the source. This is a consistent problem with the async and parallel docs -- they were created as single source code files with an enormous number of examples. Where I've revised content, I'd tried to break them out into single files -- but for the most part this hasn't been touched since it was created.
