### ISSUE TITLE
Dotnet CLI usage data update

### ISSUE THREAD

**Issue by mholec** [dotnet/docs#12439]
Is it possible to update usage data for dotnet tool? https://github.com/dotnet/core/blob/master/release-notes/cli-usage-data.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c136055b-bb04-17b6-19b2-42d4610c1a70
* Version Independent ID: 50433ae5-4687-fe5f-75ab-a47e1a706777
* Content: [.NET Core SDK telemetry - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#feedback)
* Content Source: [docs/core/tools/telemetry.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/telemetry.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard can you comment on the status of having the temeletry data updated? Thanks!

**Comment by svick** [comment]
See also https://github.com/dotnet/core/issues/2213.

**Comment by mairaw** [comment]
Since there's a issue tracking that update in the dotnet/core repo, I'll close this issue on docs. PR #14076 has updated the topic to include the latest data available and we hope to post those now on a regular cadence.

/cc @KathleenDollard
