### ISSUE TITLE
Braces

### ISSUE THREAD

**Issue by fakeinc** [dotnet/docs#12430]
In Rider IDE settings, I've found that the use of braces in "if"/"for"/"foreach"/"while"/"do-while"/"using"/"lock"/"fixed" statements have not been discussed in this guideline. For example (from the Code Style Settings as well):
```csharp
public void Preview(int a, int b)
{
    var c = 0;
    for (var i = a; i < b; i++)
        c += System.Linq.Enumerable.Range(i, a + b).Sum();

    for (var i = a; i < b; i++)
    {
        c += System.Linq.Enumerable
            .Range(i, a + b)
            .Sum();
    }
}
```
Here should I add braces to the first for loop?

Thanks.

edit by @billwagner: code formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
These guidelines should be updated to reference the [Corefx codeing style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

That provides several guidelines, including that braces should be used in the first example above.

I've added this to our backlog and our community project.

**Comment by fakeinc** [comment]
> These guidelines should be updated to reference the [Corefx codeing style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)
> 
> That provides several guidelines, including that braces should be used in the first example above.
> 
> I've added this to our backlog and our community project.

Thx.

**Comment by AbhinavPradeep** [comment]
I don't see the above code sample on the page anymore. If it has been removed, should this issue be closed?

**Comment by fakeinc** [comment]
> 
> 
> I don't see the above code sample on the page anymore. If it has been removed, should this issue be closed? I don't see any material about braces too on this page.

Hi.

Thank you for your effort. However, this issue was written since the documentation did not specify the recommended coding convention for braces around single line statements and I'd like it to be added. It was not about the code snippet.

Maybe I should just start a pull request and add the convention according to the previously mentioned [Corefx coding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md).

**Comment by AbhinavPradeep** [comment]
Can I do it as my first PR please ? Will try my best :-). Any feedback will be appreciated.

**Comment by fakeinc** [comment]
> 
> 
> Can I do it as my first PR please ? Will try my best :-). Any feedback will be appreciated.

Of course. Just do it. Notice that I'm not part of the project team though.

**Comment by AbhinavPradeep** [comment]
Thanks, will do.
