### ISSUE TITLE
Confusing bullet point "Avoid the use of var in place of dynamic."

### ISSUE THREAD

**Issue by Swimburger** [dotnet/docs#12442]
I came across the following [page on C# Coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions), but the following bullet point is confusing me.
_"Avoid the use of var in place of dynamic."_

What is meant by this bullet point? Can this be rephrased to be more clear?
Maybe a code sample will make it more clear, but currently I'm unsure of the meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Yeah, I agree. The reason why should be clear.

I'm guessing it's because dynamic and var share the fact that they don't declare a type explicitly but they are used completely differently. You wouldn't want to just start converting your existing dynamic variables to var because you should have used dynamic for some specific purpose that won't be fulfilled by var.

I'll add this to the backlog.

**Comment by Swimburger** [comment]
Aha that makes sense. Thanks for taking a look at this.

**Comment by BillWagner** [comment]
To add a bit more clarification:

`var` means "The type of this variables matches the compile-time type of the right hand side of the initialization statement." That declares a static type for the variable.

`dynamic` means "The static type of this variable is `dynamic`."  That means any member access for that variable is allowed at compile time, and is resolved at runtime based on the runtime capabilities of the object the variable refers to.  

Using `var` to declare a `dynamic` variable can make it much harder to see that distinction.

**Comment by sageTimNewton** [comment]
An example would be useful to clarify the point.
