### ISSUE TITLE
Installing hosting bundle

### ISSUE THREAD

**Issue by cemkestek** [dotnet/docs#12440]
As far as I see, only SDK and runtime installations are supported. Is there a way to install ASP.NET Core Runtime Hosting Bundle via this script?

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Are you talking about this page https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script?

**Comment by cemkestek** [comment]
Yes exactly!

**Comment by mairaw** [comment]
@johnbeisner can you help with this question?

**Comment by mairaw** [comment]
No, it's not possible and there are no plans to support that, according to @johnbeisner. If you'd like to propose that, file an issue at https://github.com/dotnet/cli/issues.
