### ISSUE TITLE
Remove some of the marketing speak in Core vs Framework article

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1244]
#1239 merges an article which provides some guidance for using either .NET Core or .NET Framework for server applications.  It was adapted from an internal whitepaper, and thus has a bit of a marketing feel to it.  We should rewrite some of the pieces which feel like they're attempting to sell the technology, particularly .NET Core.

**Comment by mairaw** [comment]
Resolved with https://github.com/dotnet/docs/pull/2908
