### ISSUE TITLE
-p isn't mentioned anywhere

### ISSUE THREAD

**Issue by 3686** [dotnet/docs#12448]
An example shows you can use `-p` to set the build parameter, but it's not mentioned in the top section of parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @3686,
 
The possibility of passing MSBuild parameters is mentioned here: 
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild

I can just add a clarification to the example introduction that this is using a MSBuild option.
