### ISSUE TITLE
Missing HOW TO load/save datasets in .IDV binary format

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#12451]
We're missing here HOW TO load/save datasets in .IDV binary format.

See customer's issue requesting it:
https://github.com/dotnet/machinelearning/issues/3748

It should also explain when to use the .IDV format, such as when you need maximum performace (compared to .CSV or .TSV), etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52d4fbe-df9c-f410-85b4-786b139e94d3
* Version Independent ID: ce6265fd-1d0b-4d58-c60d-178d512486b4
* Content: [Load Data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/load-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Thank you @CESARDELATORRE. We have added this to the backlog.

**Comment by luisquintanilla** [comment]
To be worked on as part of AB#1596634. 

Thanks for the feedback @marchy. How you consume API's is up to you. As long as you're able to get the object(s) into IEnumerable format, then they can be loaded into an IDataView with the LoadFromEnumerable method. 

As far as databases, we're adding documentation on the preview version of the DatabaseLoader.
