### ISSUE TITLE
webHttpBinding, not wsHttpBinding

### ISSUE THREAD

**Issue by ram3ai** [dotnet/docs#12458]
&gt; Specifies the security requirements for an endpoint configured with a &lt;wsHttpBinding&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2324da6b-cace-7290-6e32-f5513173c30e
* Version Independent ID: 386f0671-dfaa-3a5d-4b53-fb036873a622
* Content: [&lt;security&gt; of &lt;webHttpBinding&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/security-of-webhttpbinding#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/security-of-webhttpbinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/security-of-webhttpbinding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
