### ISSUE TITLE
Split DebugView syntax into a separate topic

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#12462]
I think the syntax used by DebugView to represent expression trees should be on a separate page, perhaps a sub-page of this one. The same is true for the [corresponding Visual Basic page](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd39193-a203-2326-7b45-79ea0015733f
* Version Independent ID: 76254616-be05-0da1-b706-6239941c2d20
* Content: [Debugging Expression Trees in Visual Studio (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio#debugview-syntax)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
fixed in #12477
