### ISSUE TITLE
.NET Framework 4.7.2 is supported

### ISSUE THREAD

**Issue by stjepan** [dotnet/docs#12465]
.NET Framework 4.7.2 is installed on Azure Guest OS Family 6, which is the latest release (running Windows Server 2019).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#net-framework-47-is-not-installed-on-azure-guest-os-by-default)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
Is there public doc confirming that?
Can you please submit PR?

**Comment by stjepan** [comment]
https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix#family-6-releases

I think it would better be someone from you guys for this one, because it might be some other content editing related to the new fact.

**Comment by mairaw** [comment]
I've created a PR here: https://github.com/dotnet/docs/pull/12873

I've asked some folks to review it now.
