### ISSUE TITLE
loadedModel in PredictIssue

### ISSUE THREAD

**Issue by garricknorthover** [dotnet/docs#12464]
Hey guys,
Just another little typo.

The PredictIssue method is missing the declaration of loadedModel.

So 
```
            ITransformer loadedModel = _mlContext.Model.Load(_modelPath, out var modelInputSchema);
```
needs to be the first line in
```
private static void PredictIssue()
{

}
```

Cheers
Garrick
```


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @garricknorthover, unfortunately this is actually not needed as we removed the save and load and consolidated it into a How-To article. Apologies for the delay in responding!

**Comment by oatsoda** [comment]
@JRAlexander There is still a problem because the code references `loadedModel` which doesn't exist.  Are we supposed to use `_trainedModel` instead?

**Comment by Shah-Nisarg** [comment]
@JRAlexander Please see the comment above from @oatsoda . The code, as it is now, will not compile as the variable `loadedModel` is not declared. 

Also, some of the initial steps mention creating a "Models" folder. I assume that is also no longer needed given the save-and-load part is removed.
