### ISSUE TITLE
Documentation does not correspond to implementation behavior of system.runtime.caching.memorycache

### ISSUE THREAD

**Issue by anato-s** [dotnet/docs#12470]
**Issue:**
When `MemoryCache.Default` is initialized, it is not finding the following configuration as per documentation sample and sets default values

`<add name = "default" cacheMemoryLimitMegabytes="20" physicalMemoryLimitPercentage="0" pollingInterval="00:02:00" />`

**Culprit:**
This is either
1. incorrect documentation [https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings](url)
or
2. incorrect constant in the `MemoryCache`. Apparently, setting/attribute "name" is case-sensitive. The issue can be fixed by modifying configuration to `<add name = "Default" . . .`

**Target framework**

- [4.7.1] .NET Framework

PS: will there be any documentation on usage of `useMemoryCacheManager=""`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a67406db-e7fe-e4d3-1d5c-9a4d581f5ff6
* Version Independent ID: e70febe8-b1c1-187d-19f9-88f8c26cf07a
* Content: [&lt;system.runtime.caching&gt; Element (Cache Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@anato-s which article are you referring to regarding incorrect documentation?

**Comment by mairaw** [comment]
Closing due to the lack of response. Please get back to us with more information and we can reactivate the issue.

**Comment by anato-s** [comment]
@mairaw Sorry, for the delay. I am sure, this is the document 
[https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings](url)

**Comment by anato-s** [comment]
> 
> 
> Closing due to the lack of response. Please get back to us with more information and we can reactivate the issue.

Well, I was away. I posted the update. Thanks

**Comment by mairaw** [comment]
No worries. Reopening.

**Comment by mairaw** [comment]
@rpetrusha do you know how to find the owner of these config settings?

**Comment by rpetrusha** [comment]
@StephenMolloy and @HongGit, is the documentation correct? And is the name case-senstiive?

**Comment by StephenMolloy** [comment]
The name is case sensitive. https://referencesource.microsoft.com/#System.Runtime.Caching/System/Caching/MemoryCacheStatistics.cs,108 is where the lookup is done, and that collection of named caches is case sensitive. The example should be updated.
