### ISSUE TITLE
Shows how to create but not how to read the list and use it in a real life application.

### ISSUE THREAD

**Issue by edaymami** [dotnet/docs#12483]
Please stop using the "Console" and show examples in a desktop app or at least what the code would return. Lots of other article here show what the code returns. also fails to show when list contains a row with more than one data item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef7201b-e3d3-484c-c46f-0f2f257ddae3
* Version Independent ID: bc2b573a-40ac-a9fd-daa8-b5a5884b11c7
* Content: [Work with collections - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/arrays-and-collections)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/arrays-and-collections.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/arrays-and-collections.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We are going to build more tutorials that show different application workloads @edaymami 

To learn more about specific application types (such as desktop applications) check the sections about those workloads. Those will use C#, but focus more on the specific application styles. Let us know if those provide the information you need.

**Comment by CodeAddiction** [comment]
@BillWagner I look forward to the desktop app tutorials, @edaymami there are plenty of desktop tutorials that teach the same fibonacci method, heres an example https://www.c-sharpcorner.com/blogs/fibonacci-series-using-wpf

**Comment by BillWagner** [comment]
Changing the label from "get started" to "fundamentals". The new article will go in that section, as we explore different workloads.
