### ISSUE TITLE
XmlReader should be disposed

### ISSUE THREAD

**Issue by masterofimages** [dotnet/docs#12480]
Since XmlReader implements IDisposable, the XmlReader should be disposed after use, e.g.

    using (XmlReader books = XmlReader.Create("books.xml", booksSettings))
        while (books.Read()) { }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99bf3b5-3eb2-a0d3-2009-4fb2b9de3b76
* Version Independent ID: 8252e3d3-0718-9814-d685-852387f16afd
* Content: [XML Schema (XSD) Validation with XmlSchemaSet](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset#feedback)
* Content Source: [docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!
