### ISSUE TITLE
Should set bookSettings.ValidationFlags = XmlSchemaValidationFlags.ReportValidationWarnings

### ISSUE THREAD

**Issue by masterofimages** [dotnet/docs#12481]
Without the ValidationFlags property set to XmlSchemaValidationFlags.ReportValidationWarnings, no schema validation warnings are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99bf3b5-3eb2-a0d3-2009-4fb2b9de3b76
* Version Independent ID: 8252e3d3-0718-9814-d685-852387f16afd
* Content: [XML Schema (XSD) Validation with XmlSchemaSet](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset#feedback)
* Content Source: [docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@masterofimages Thanks for reporting this. We'll fix it the next time we update this article. If you'd like, you're welcome to submit a pull request to fix it as well.
