### ISSUE TITLE
Docket Community Version not available

### ISSUE THREAD

**Issue by mahavirsinhpadhiyar** [dotnet/docs#12482]
https://www.docker.com/community-edition link applied on Docker Community Edition (CE) text is not found as of now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befff27-c4fc-a699-90b3-903ce60234af
* Version Independent ID: 71ff10df-c0b0-9497-e448-82388ef1b1a1
* Content: [What is Docker?](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined#feedback)
* Content Source: [docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Thanks for the feedback @mahavirsinhpadhiyar. This is fixed in the referenced PR and will go live soon.
