### ISSUE TITLE
SafeHandlers - Linux

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/docs#12501]
Will these `SafeHandles` examples work for .NET Core applications running on Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#SafeHandles)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@AaronRobinsonMSFT, @jkoritzinsky Can you answer this question about System.Runtime.InteropServices.SafeHandle support on Linux?

**Comment by AaronRobinsonMSFT** [comment]
@garfbradaz I can't think of any reason that the abstract `SafeHandle` class can't be used in a cross platform manner. There could be issues with some of the existing sub-classes, but those wouldn't even exist on linux if there were issues.

**Comment by tdykstra** [comment]
@garfbradaz  We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
