### ISSUE TITLE
Not predicting but selecting closest static value

### ISSUE THREAD

**Issue by randallto** [dotnet/docs#12509]
I used the taxi cab example to get the first payment of a Graduated Student Loan. Those are not formulated like simple interest is the reason for using a prediction from machine learning. I have data with balances in 5k increments and interest rates in .5 increments. When I do a prediction using a known balance in the data and using 2% interest it is identical to 2.25%.  2.26% is the same as 2.5%. What is happening is it simply selecting a static value from the data and not attempting to determine something between 2% and 2.5%. So basically it is doing what I could do without using machine learning so what is the purpose? Do you know of possibly of a different way using ML.Net to achieve an actual prediction? 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using a regression algorithm - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by Thraka** [comment]
@JRAlexander Assigning to you just to get your thoughts on it. I don't know what article is being talked about but it sounds like it's in your realm (or shard, depending on your age 🎲). Feel free to remove yourself as assignee.

**Comment by mairaw** [comment]
@randallto can you paste a link to the article you're referring to?

**Comment by randallto** [comment]
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices
I think I may have found that FastTreeTweedie seems to be doing some actual estimating. The FastTree was simply just finding the closest record in the data and returning that exact payment value instead of doing an estimate.  That test was doing a prediction of values that were not identical to anything in the trained model's source data.

**Comment by natke** [comment]
@randallto, let us know if you solved your problem.

**Comment by natke** [comment]
@randalto Do you have enough information to solve your problem now?

**Comment by natke** [comment]
Closing this issue, as we did not hear back from you. Please reach out if you need more assistance.
