### ISSUE TITLE
Migrate .NET content team code samples from Code Gallery

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#12511]
The sample URLs already redirect to the new samples browser. If we can't recover the old samples, we should eliminate the links to them in existing documentation.

## Migrate .NET content team code samples from Code Gallery

There are currently five legacy samples created by the **CLR User Education team** that should be migrated to GitHub and modernized. They are:

- [x]  [.NET Framework 4 Formatting Utility](https://code.msdn.microsoft.com/NET-Framework-4-Formatting-9c4dae8d) (32,067 downloads)
  The utility is referenced multiple times in the date and time formatting documentation.
- [ ] [.NET Framework 4 Calendar Week Range Utility](https://code.msdn.microsoft.com/NET-Framework-4-Calendar-3360a84a) (5,627 downloads)
  The utility is referenced multiple times in the calendar documentation.
 - [ ] [ .NET Framework 4 Base64 Converter](https://code.msdn.microsoft.com/NET-Framework-4-Base64-1c3d9c03) (3,141 downloads)
  The utility is reference in the Convert.FromBase64String and ConvertToBase64String APIs.
- [x] [Cyrillic to Roman Transliteration Utility](https://code.msdn.microsoft.com/Cyrillic-to-Roman-f7e88b29) (1,998 downloads)
  The utility is referenced in the EncoderFallback and EncoderFallbackBuffer classes.
- [ ] [.NET Framework 4.5 Chainer Sample](https://code.msdn.microsoft.com/NET-Framework-45-Developer-e416a0ba) (4,623 downloads)
  The sample is referenced in [How to: Get progress from the .NET Framework 4.5 Installer](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-to-get-progress-from-the-dotnet-installer)

**Comment by tdykstra** [comment]
The sample URLs already redirect to the new samples browser. If we can't recover the old samples, we should eliminate the links to them in existing documentation.
