### ISSUE TITLE
Ability to add a package reference without a specific version added to .csproj file

### ISSUE THREAD

**Issue by rcollette** [dotnet/docs#12510]
For example, when adding Microsoft.AspNetCore.App to a test project that references a web api project, I need to add the package reference without a version number as per
https://github.com/dotnet/sdk/issues/2253

I am doing this with a shell script that creates a multi-project solution so I need to do it with `dotnet add package ..`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
You can specify the version of the package with the `-v` parameter. You can [NuGet version](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) notation to specify a version. That version will be put in the csproj. So in your case, what you want to do is 

```cmd
dotnet add package MyPackage -v *
```
