### ISSUE TITLE
DataSets in ADO.NET documentation

### ISSUE THREAD

**Issue by SabotageAndi** [dotnet/docs#12515]
**Issue description**

In the ADO.NET docs (https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/) are a lot of pages and mentions of DataSet and DataReader. As far as I know it isn't anymore recommended to use these.

If a newcomer reads the documentation, it looks like it is a good idea to use them.
I would like to see some banner or info, that these classes shouldn't be used for new projects.

**Comment by mairaw** [comment]
@stevestein another feedback regarding ADO.NET content

**Comment by stevestein** [comment]
@SabotageAndi - Thanks for raising this issue. Appreciate you calling this out as we know there is a need for this information. I've created an internal work item (#1570828) to get some info added to the related articles.

I'm going to go ahead and close this issue, but feel free to add additional comments if needed.

Thanks!
