### ISSUE TITLE
use best coding practises in ADO.NET samples

### ISSUE THREAD

**Issue by SabotageAndi** [dotnet/docs#12516]
The samples of using ADO.NET don't use best practices of C# coding.

If you look at one example from https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-data-using-a-datareader

``` csharp
static void HasRows(SqlConnection connection)
{
    using (connection)
    {
        SqlCommand command = new SqlCommand(
          "SELECT CategoryID, CategoryName FROM Categories;",
          connection);
        connection.Open();

        SqlDataReader reader = command.ExecuteReader();

        if (reader.HasRows)
        {
            while (reader.Read())
            {
                Console.WriteLine("{0}\t{1}", reader.GetInt32(0),
                    reader.GetString(1));
            }
        }
        else
        {
            Console.WriteLine("No rows found.");
        }
        reader.Close();
    }
}
```

I see following problems with this examples: 

 - There are missing `using` statements for SqlCommand and the SqlDataReader.
 - Connection is a parameter, but the `HasRows` method opens it and disposes it.  
  As the connection is created from the caller, it should also care about it's lifetime. 

I think this makes it hard for beginners to start with ADO.NET and learns them the wrong patterns.

**Comment by mairaw** [comment]
@stevestein tagging you since this feedback is referring to ADO.NET content.

**Comment by stevestein** [comment]
@SabotageAndi - Thanks for raising this issue. I've created an internal work item (#1570828) to track this.

I'm going to go ahead and close this issue, but feel free to add additional comments if needed.

FWIW - 
We welcome contributions to help us improve and complete the .NET docs. To contribute, see the [Projects for .NET Community Contributors](https://github.com/dotnet/docs/projects/35) for ideas. The [Contributing Guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) has instructions on procedures we use. Or, check the [issues list](https://github.com/dotnet/docs/issues) for tasks that interest you.

Thanks!
