### ISSUE TITLE
How does this helps scaling aspect of CQRS pattern?

### ISSUE THREAD

**Issue by metalhead44** [dotnet/docs#12514]
Wanted to know how does this helps scaling aspect of CQRS pattern? Both the models are part of the same microservice, so scaling the microservice is going to scale both read and write paths. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce115a1c-3cc0-c01d-4fb4-95105cfeda85
* Version Independent ID: 3469e63a-4c32-d38e-152a-28be75f2b056
* Content: [Applying simplified CQRS and DDD patterns in a microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi, @metalhead44, thanks for your feedback.

You're right when it comes to this specific microservice in eShopOnContainers. 

However in a more general case, CQRS allows you to split the load in different microservices, between query microservices and update microservices when it makes sense for the business.

A good example of this could be a real-life catalog microservice, where you'd probably have order-of-magnitude differences between queries and updates to the catalog items.

In this case you could have a few update microservices in an internal network, not accessible from the Internet, that would only be used by internal users. And have as many query microservices as you need, spread all over the world, so you can service your customers as fast as possible.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by crclz** [comment]
Having another finer grained data model for reading has many advantages. The way how data is organized in the write data model is good for handling business logic but maybe bad for querying for something you should display on the view (the screen). If you have a finer grained read model, you can implement more complex queries with SQL, you can implement GraphQL (using the read model), you can make use of In-Memory cache (usually Redis), which is crucial for most of the web apps. 
And do not worry about the complexity of maintaining two models.
