### ISSUE TITLE
Error in Program.vb code?

### ISSUE THREAD

**Issue by keithbfry** [dotnet/docs#12517]
I am new to vb.net and working through the tutorial. I received an error when trying to execute program.vb on the line "$"{If(input.StartsWithUpper(), "Yes", "No")} {vbCrLf}")", BC30456 'StartsWithUpper' is not a member of 'String'. Did I miss a step somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2fd1ea-abfe-ada0-ce7b-1d7f50819c18
* Version Independent ID: 4d918f89-02f2-dbf6-a701-c2efe9eb9a7d
* Content: [Consume a .NET Standard library in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/consuming-library-with-visual-studio?tabs=vb#feedback)
* Content Source: [docs/core/tutorials/consuming-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/consuming-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
There are two things that might account for the error you're seeing, @keithbfry.
- In your source code for the StringLibrary class (from <https://docs.microsoft.com/dotnet/core/tutorials/vb-library-with-visual-studio>), have you included the `<Extension>` attribute before the `StartsWithUpper` method? 
- Have you added a reference to the **StringLibrary** project in step 5?

**Comment by mairaw** [comment]
Closing due to the lack of response after two weeks or more.
