### ISSUE TITLE
This is not advanced topic but a "Basic" topic.

### ISSUE THREAD

**Issue by BrightFuture1029** [dotnet/docs#12527]
Why don't we change structure of entire document tree and name it as basic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1322e7-0e9c-56d4-bc95-4c071f44e89f
* Version Independent ID: 82ed1aa1-489f-88f5-b4da-4dc4ef2a59d5
* Content: [Advanced (Windows Presentation Foundation)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/#feedback)
* Content Source: [docs/framework/wpf/advanced/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello.

Can you clarify why you think this is basic information? I feel like basic information is more like the getting started stuff where you teach someone how to install or create a simple app but don't go into deeper knowledge stuff.

Maybe we could name it fundamentals as a better title/structure, and not try to specifically say that this information is advanced or basic?

**Comment by Thraka** [comment]
Going to close this issue. Either way we're not making changes to the existing WPF area. However, the details from this issue can be used in the new WPF desktop guide.
