### ISSUE TITLE
[ML.NET] Include Cache in HOW TOs at docs.microsoft.com for ML.NET

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#12521]
It’d be good to have a short HOW TO page explaining when to use cache, when not to use it, pros/cons, and the simple line of code on how to use it in the pipeline.

This is almost the only place in the reference talking about it, but it is not very clear:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.learningpipelineextensions.appendcachecheckpoint?view=ml-dotnet#Microsoft_ML_LearningPipelineExtensions_AppendCacheCheckpoint__1_Microsoft_ML_IEstimator___0__Microsoft_ML_Runtime_IHostEnvironment_

A HOW TO page should say that for small/medium datasets and algorithms that do multiple passes it improves performance, but for large datasets it can impact negatively since you might not have enough memory for loading the whole dataset and when the dataset is large it is better to read from the file streaming chunks of data as needed when training (automatically done by the reader).

**Comment by mairaw** [comment]
Tagging @natke since this is a request for a new ML.NET article.

**Comment by natke** [comment]
Thank you @CESARDELATORRE. We have added this to our backlog.
