### ISSUE TITLE
Bad layout - the 'Message' column leaks past the table view

### ISSUE THREAD

**Issue by MikeRosoft** [dotnet/docs#12520]
The tables are unreadable due to a bad layout; the 'Message' column leaks past the table view and requires horizontal scrolling (after which the type name can't be seen). Set maximum width for the 'Type' column and wrap the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc58564e-689c-1571-d59b-b40660d21cd5
* Version Independent ID: 2ee9ecb0-3089-4a84-bc52-c33295db9ed9
* Content: [Obsolete members - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/obsolete-members#mscorlib)
* Content Source: [docs/framework/whats-new/obsolete-members.md](https://github.com/dotnet/docs/blob/master/docs/framework/whats-new/obsolete-members.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. 

Thanks again!

**Comment by Thraka** [comment]
@mairaw What do we do about problems like this? We don't have a good way of presenting this information without a table, and the site hates tables... Is filing an LSI worth it or do we investigate some other presentation form?

**Comment by mairaw** [comment]
I'd probably post a question on the support channel to see if there's any way we could wrap these links.

**Comment by mairaw** [comment]
Did you find out anything about this @Thraka?

Tagging @gewarren who owns these now.

**Comment by gewarren** [comment]
I'll try wrapping it in this: https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#mx-tdbreakall

**Comment by Thraka** [comment]
I dont think so. I searched and didn't find much. @gewarren when you just said that, it reminded me of a bug or table fix that would make these better. I'll search my email.
