### ISSUE TITLE
sudo rm -rf `find Shortcut to remove old version

### ISSUE THREAD

**Issue by eostarman** [dotnet/docs#12536]
cd /usr/local/share/dotnet
sudo rm -rf `find . -name '2.1.*'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Remove the .NET Core runtime and SDK - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos#feedback)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jasonchester** [comment]
worked great for me
```
sudo rm -rf `find . -name '3.0.100-preview*'`
```
