### ISSUE TITLE
Available options

### ISSUE THREAD

**Issue by Emdot** [dotnet/docs#12538]
See the listing on the left at http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Options/Option%25601.cs,3b7f62d0e769f94b,references for the available options that are built into Roslyn.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e10330-6763-2858-9997-b0ac59a5c793
* Version Independent ID: 512356fd-6498-940a-6463-e2453a1709fc
* Content: [Document.GetOptionsAsync(CancellationToken) Method (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.document.getoptionsasync?view=roslyn-dotnet#Microsoft_CodeAnalysis_Document_GetOptionsAsync_System_Threading_CancellationToken_)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Document.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Document.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@BillWagner how do we handle suggestions for the Roslyn API docs?
