### ISSUE TITLE
[Bug] Race condition in idempotent mediator commands

### ISSUE THREAD

**Issue by lonix1** [dotnet/docs#12534]
In section entitled [Implement idempotent Commands](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#implement-idempotent-commands) there is a race condition - the code checks whether the command was already processed, and if not, processes it. Between the check and the database write another identical command could be processed.

A scenario in which multiple commands are fired is one where it is more probable than not that they are fired very close together in time. So this race condition is not an edge case, it's a bug waiting to happen.

I suggest an alternative where you try to perform the operation, and allow it to fail because of a unique key violation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3920c19-388e-0e84-960f-0bb0c8340fe0
* Version Independent ID: c728d4ba-50e8-798d-72a0-c4a5b6f13ca2
* Content: [Implementing the microservice application layer using the Web API](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#the-command-handler-class)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @lonix1, thanks for the feedback!

I think this leans more towards an edge case, because it'd happen if the same message was delivered twice in quick succession by RabbitMQ, but I agree that it can happen and when it does, it's the kind of bug that's extremely hard to reproduce and fix.

Would you like to submit a PR to the [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers/pulls/) with your proposed solution?
