### ISSUE TITLE
Move include files to a central location

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1253]
The export tool for the migrated content from MSDN had a weird behavior on where it'd put the include (token) files on the folder where the text was first used. We need to move the include files to a central location to be easier to find and use them.

**Comment by BillWagner** [comment]
This is marked as blocked because we are hoping an upgraded export tool can bulk move all the included snippets into the proper location.

**Comment by tompratt-AQ** [comment]
@mairaw Should we re-purpose this Issue for moving the include files? Or open a new issue?
