### ISSUE TITLE
Docker Community Edition (CE ) for Mac and Windows link is not valid any more

### ISSUE THREAD

**Issue by skewl84** [dotnet/docs#12539]
The new link for the Docker Community Edition (CE ) for Mac and Windows is 
https://hub.docker.com/search/?type=edition&offering=community

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ddab88-0658-98e6-ead1-2521359e417a
* Version Independent ID: 41efa23d-02b1-63e8-f240-ba5dbae21712
* Content: [Development Process for Docker Based Applications](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/#feedback)
* Content Source: [docs/standard/microservices-architecture/docker-application-development-process/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/docker-application-development-process/index.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Thank You @skewl84 for your feedback. These are fixed in the mentioned PR and will go live soon.
