### ISSUE TITLE
Goto is barred for 50 years

### ISSUE THREAD

**Issue by ILya-Lev** [dotnet/docs#12542]
Please do not use goto in your examples.
Ever! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc900853-b666-5815-9d69-e408af3e3900
* Version Independent ID: 77f3af83-d0ca-7d48-d06d-0f28f5f05a49
* Content: ["pattern-based using" and "using declarations" - C# 8.0 language proposals | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using#feedback)
* Content Source: [proposals/csharp-8.0/using.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/using.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by mikedn** [comment]
`goto` is a feature of the language and language proposals naturally have to discuss how new features interact with it.

**Comment by Thraka** [comment]
I'm going to close the issue as there is no real issue here 🍰

**Comment by StingyJack** [comment]
> no real issue here

article references `goto` statement, which the usage of has been frowned upon for decades now and would be flagged as "correction required" by any code review.

article talks about using declarations, which are a worse idea WRT definition of bounding scope than inline out parameters.

These are two **real** issues that promote coding practices/styles that make the code harder to read and/or increase likelihood of bugs.

**Comment by adegeo** [comment]
@StingyJack Sure, but this is the language specification article. It details the keywords and how they're used and essentially documents the language syntax.

**Comment by StingyJack** [comment]
The objection is with using `goto` in examples, because people copy example code from pages like this.  

The other note is related to this proposed feature.
