### ISSUE TITLE
dotnet command help missing --runtimeconfig option

### ISSUE THREAD

**Issue by dasMulli** [dotnet/docs#12543]
See https://github.com/dotnet/core-setup/blob/61f83f1f764a8a2840a21779e386c2ad11fca75d/src/corehost/cli/fxr/command_line.cpp#L22-L31 for the available options (https://github.com/dotnet/core-setup/blob/086e6eddfa2639f074f9512bf10e374391ffafde/src/corehost/cli/fxr/fx_muxer.cpp#L724-L742 for the 2.2 version).

The documentation is missing the `--runtimeconfig` option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore1x#feedback)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you @dasMulli for reporting this and opening the PR.
@KathleenDollard is this also a bug in `dotnet --help`, which also doesn't show those options (`--depsfile` and `--runtimeconfig`)?

/cc @vitek-karas @elinor-fung

**Comment by KathleenDollard** [comment]
* This fix is fine
* These should be in help under runtime-options
* The docs should split up runtime and sdk options in the way the help does. Strictly speaking the last four of the sdk-options are not executed by the SDK, but the muxor, so the real difference is that the "runtime-options" are that, and we list everything else under sdk-options. We might want to be a bit cleaner about that in the docs.
