### ISSUE TITLE
ConfigureAwait(false)

### ISSUE THREAD

**Issue by andhog** [dotnet/docs#12549]
Why isn't ConfigureAwait(false) considered to be the default when awaiting async calls? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thanaen** [comment]
For ASP.NET Webforms users (like me), calling ConfigureAwait(false) on an async mathod makes the Page.Context / HttpContext.Current unavailable for the following code. This could potentially break a lot of websites if you decided to make ConfigureAwait(false) the default case.

**Comment by BillWagner** [comment]
@andhog `ConfigureAwait(false)` provides better scaling or performance when it's safe. However, when it's not safe, `ConfigureAwait(false)` breaks application. 

The default choice always works, but may not be optimal. That's why it was chosen as the default

Closing as an answered question.
