### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by shavenwalrus** [dotnet/docs#12546]
Why break the concept of interface immutability? That's kind of the whole point of them.

What pressing need does this feature address that can't be accomplished with abstract classes or interface inheritance? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-members-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Tvde1** [comment]
Read https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md.

**Comment by BillWagner** [comment]
@shavenwalrus This features supports two key scenarios:
- version upgrades to interfaces.
- some traits like programming concepts.

This is not a docs question, but a language question. You can participate in discussions on language features in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository. closing this as product feedback.
