### ISSUE TITLE
DPI

### ISSUE THREAD

**Issue by mcsGregor** [dotnet/docs#12553]
I think the DPI graphics are in the wrong order.
If all the images have the same size (200 x 150 px), then the images become smaller with rising display sharpness (DPI) and not bigger.

BR,
Gregor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6893b273-ed23-a3b7-ccc8-1cf335df36f6
* Version Independent ID: 6b3732d4-6e7d-6867-9f5e-d8b6fb047d4c
* Content: [WPF Graphics Rendering Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/wpf-graphics-rendering-overview#feedback)
* Content Source: [docs/framework/wpf/graphics-multimedia/wpf-graphics-rendering-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/wpf-graphics-rendering-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I don't think so, not in this case. This paragraph is talking about how automatic scaling works and points out that the scaling in WPF is not handled like most applications are.

>WPF supports automatic scaling by using the device independent pixel as its primary unit of measurement, instead of hardware pixels; graphics and text scale properly without any extra work from the application developer. The following illustration shows an example of how WPF text and graphics are appear at different DPI settings.

This is why the image scales along with the text. So yes, in a traditional application something set to screenpixels of 200x100 would appear smaller as soon as you raise the DPI, in WPF things are not set in pixels but in device-independent pixels, which scales like text elements do.

I'm going to close this issue. Please let me know if it makes sense. Thanks!
