### ISSUE TITLE
No information about behaviour for multi framework projects

### ISSUE THREAD

**Issue by shoter** [dotnet/docs#12551]
There is no description on what happens when we are trying to test projects with multiple targeted frameworks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Greg-Smulko** [comment]
Spoiler: when you multitarget a test project, `dotnet test` just runs tests against all targets.

**Comment by captainjono** [comment]
@Greg-Smulko 

dotnet test "some.fullframework.dll" 

"no tests found"

vstest.console.exe "some.fullframework.dll"

"5 test pass"

Im building a tool that executes tests automatically against either of these frameworks. The doco is not clear here attempting to detect which framework i need to run a .dll against is not pretty.
