### ISSUE TITLE
Move snippets to the snippets location

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1255]
The snippets that were migrated were put in subfolders inside the content and broken down in several small snippets.
In order to get CI working and all, our snippet files need to be moved as a whole (like the original ones) to the [snippets folder](https://github.com/dotnet/samples/tree/master/snippets).

Query to find out how many are still left:
https://github.com/dotnet/docs/search?q=codesnippet&unscoped_q=codesnippet

**Comment by pkulikov** [comment]
@mairaw please update the link to the snippets folder, as it's different after the repo split.

**Comment by mairaw** [comment]
Done @pkulikov. Thanks!

**Comment by pkulikov** [comment]
@mairaw as I revise the articles about C# operators (PRs #8539 #8687 #8790 #8829 #8880 and more to come), I also move inner snippets into the samples repo. At the end, all operator-related snippets will be moved to the samples repo.

**Comment by mairaw** [comment]
That's great @pkulikov! Thanks.
