### ISSUE TITLE
Swap out author on topics

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#12556]
Would it be ok to swap me (guardrex) out for one of the regular authors on the repo in `author` metadata? It will help me with the ping load. I can do the PR if you let me know who the replacement author is.

**Comment by rpetrusha** [comment]
Yes, it would be OK, @guardrex. You can assign the .NET Core topics to @mairaw and the .NET Framework topics to @rpetrusha.

**Comment by guardrex** [comment]
Thanks @rpetrusha ... Will do.
