### ISSUE TITLE
Why use the TryReceive method?

### ISSUE THREAD

**Issue by aaronhudon-ts** [dotnet/docs#12560]
The `Robust Programming` example doesn't illustrate any benefit of using `TryReceive` compared to `Receive`.  The reason of "multiple consumers" should be expanded to show why `TryReceive` is more appropriate for multiple consumers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bea9235-8cf9-29aa-5136-a0af34725e2c
* Version Independent ID: b6c11689-a72b-1d55-f832-3f99d0edb628
* Content: [How to: Implement a Producer-Consumer Dataflow Pattern](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@aaronhudon-ts Thanks for the question. The reason it's more appropriate is explained in text that appears after the sample code:

>The TryReceive method returns False when no data is available. When multiple consumers must access the source block concurrently, this mechanism guarantees that data is still available after the call to OutputAvailableAsync.
