### ISSUE TITLE
Get Copy error after adding the 2 lines in dockefile

### ISSUE THREAD

**Issue by SwitchNikky** [dotnet/docs#12568]
Hi, I get a error when I run "docker build -t myimage ." after adding the 2 lines in dockerfile. "COPY failed: stat /var/lib/docker/tmp/docker-builder640341134/bin/Release/netcoreapp2.2/publish: no such file or directory" .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container#feedback)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Did you run `dotnet publish -c Release` specifically the `Release` parameter? Can you output the directory structure (tree) of the `.\app\bin\` folder?

Can you provide more information about your environment?

1. OS
2. Folder path you're working in (directory results for the folder would help)
3. Folder path to your app (directory results for the folder would help)
4. Dockerfile contents
5.

**Comment by walkerjian** [comment]
Just move the Dockerfile up one level to the root of the working directory and build your image again - I had the same problem!

**Comment by Thraka** [comment]
OK I think both of you may have missed the last part of the section where you create your app, which states:

> In your terminal, go up a directory to the working directory.

And then at the start of the **Create the Dockerfile** section, it says:

> Create a file named Dockerfile in your working directory

Can you both confirm that? Maybe I need to readjust how that is presented so it's not easily skipped?

**Comment by walkerjian** [comment]
You are correct, this is not plain enough either, I worked out what was wrong and fixed it up - quite an easy fix too, just move the docker file! but I would like to see more explicit explanation of exactly where files should go, and especially with docker - which locality you enter commands! The error is characteristic of the command not being able to find the file - I had another experience where the file was not called Dockerfile but another name that was referenced by a -f specifier on the command line. I worked it out as before, but it is always a good idea to document all switches used...

**Comment by Thraka** [comment]
Great feedback. I'll incorporate that 👍 thanks!

**Comment by SwitchNikky** [comment]
I agree with Walkerjian. As I do not like "default values" at all, I think the required folder hierarchy should be visible somewhere. Typically, my problem come from my hate of default values. Actually, I am not able to place the Dockerfile 1 level up. Because I changed my folder hierarchy without knowing the consequences on Docker.
