### ISSUE TITLE
Params, Splat, every language has a different term for this

### ISSUE THREAD

**Issue by Narvey** [dotnet/docs#12574]
If there is a generic term for splats (Ruby)/params parameters (C#, and the most vague way of referring to this concept I can imagine), please include it in this documentation for better searchability as well as general knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdb1f5e-a34b-6f30-2262-7c659e1ee466
* Version Independent ID: c985d741-8cf9-4486-d803-ddee5904faa1
* Content: [params keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params)
* Content Source: [docs/csharp/language-reference/keywords/params.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/params.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
The best I could find is **catch-all**.

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by BillWagner** [comment]
The only generic term I've heard is "parameter array". The term "params" has been used in most C based languages for this type of parameter. 

I'd suggest that the fix is to add "parameter array" to the title or H1 on this article.

Adding the "up for grabs" label.

**Comment by Admiralfeb** [comment]
in JS/TS the spread operator `... array` is the way to do this.
This was one of the first items in the list when I ran a google/bing search for "C# spread"
