### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by rsrobbins** [dotnet/docs#12577]
There is no code shown for "As you did previously, fit the model to the productSales data and return the trained model by adding the following as the next line of code in the DetectChangePoint() method:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0953823a-7d2a-a323-5365-d9a349385552
* Version Independent ID: 54ec317c-cfb9-0c2c-ccc2-4b90a5746e99
* Content: [Use ML.NET in a sales anomaly detection scenario - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sales-anomaly-detection)
* Content Source: [docs/machine-learning/tutorials/sales-anomaly-detection.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sales-anomaly-detection.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for this feedback, @rsrobbins! Good catch. I'll get it fixed straightaway and reference this issue in the PR fix.
