### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by alihassani1378** [dotnet/docs#12579]
lambda

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567260f8-0f94-b48c-8344-0d9780ab4448
* Version Independent ID: 1bebe367-5b93-0b83-72f5-bdf31d65ef5d
* Content: [Lambda expressions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions#feedback)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Closing as not actionable.
