### ISSUE TITLE
i'm confuse

### ISSUE THREAD

**Issue by sameeraviduranga** [dotnet/docs#12589]
i want to learn c# very clearly and correctly.are left side menu of this page correct order ? how i start c#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dff5a94-d9cd-e31b-4056-362abbe8d782
* Version Independent ID: cfb1ad21-e822-4075-2726-bd130ec2358d
* Content: [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/#feedback)
* Content Source: [docs/csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
To get started with C#, @sameeraviduranga, you can use the interactive tutorials in the [Introduction to C# interactive tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/#introduction-to-c-interactive-tutorials) section. They allow you to learn C# by using your browser, writing code, and executing it in your browser.
