### ISSUE TITLE
Review examples

### ISSUE THREAD

**Issue by brunoxweb** [dotnet/docs#12591]
Hi there! This document are suggesting the use of StringBuilder to concatenate strings. However we can see a bad example a few words later.

...append strings in loops, especially when you are working with large amounts of text, use a StringBuilder object.

```csharp
var phrase = "lalalalalalalalalalalalalalalalalalalalalalalalalalalalalala";
var manyPhrases = new StringBuilder();
for (var i = 0; i < 10000; i++)
{
    manyPhrases.Append(phrase);
}
//Console.WriteLine("tra" + manyPhrases);
```

And then we can see that:

```csharp
var syllable = "ha";
var laugh = "";
for (var i = 0; i < 10; i++)
{
    laugh += syllable;
    Console.WriteLine(laugh);
}
```

EDIT by @thraka to fix code blocks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#feedback)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Good catch. I think the content could actually just reuse the existing example for `StringBuilder`

**Comment by Potapy4** [comment]
@Thraka it looks like we can close this 🙂

**Comment by mairaw** [comment]
Good catch @Potapy4! Thanks.
