### ISSUE TITLE
\$ explanation is garbled

### ISSUE THREAD

**Issue by johnnzy1** [dotnet/docs#12590]
There's a bit of a glitch in the explanation for the \$ expression for example 3 which makes it more difficult to read. It's fairly obvious when you look at it. Maybe I can fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd8ae60-9b02-3e9e-2318-982f563710c2
* Version Independent ID: d167e261-eb1b-967b-5a6f-cbc2207cd32d
* Content: [.NET Framework Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expressions#feedback)
* Content Source: [docs/standard/base-types/regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by johnnzy1** [comment]
No, I don't think I can.

**Comment by rpetrusha** [comment]
Thanks for reporting this issue and trying to fix it, @johnnzy1. We appreciate it. I've opened #12593 which hopefully fixes the problem.
