### ISSUE TITLE
The class definition for eventLog1 is missing

### ISSUE THREAD

**Issue by Lukas34** [dotnet/docs#12592]
The sample code for "Add features to the service" looks to be missing the `EventLog` class when creating `eventLog1`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Tutorial: Create a Windows service app](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#feedback)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
That variable is created by adding the EventLog component in the Visual Designer. This is in step 2 under [Add custom event log functionality](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#add-custom-event-log-functionality).

Hope this helps.
