### ISSUE TITLE
Misleading default configuration value

### ISSUE THREAD

**Issue by dannarsavage** [dotnet/docs#12604]
This page indicates that the default configuration value is "Debug", but I removed the Debug configuration from my solution & all projects and my build server happily built using my new "Development" configuration after a simple "dotnet build [solution]".  Perhaps that note should instead indicate that dotnet will go with the first config it finds in the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. This does sound like the "default" in this case means when the setting is omitted from the command line, and there is no config defined in the project.

@KathleenDollard Please confirm.

Thanks again!

**Comment by KathleenDollard** [comment]
@livarcocc @dsplaisted

**Comment by mairaw** [comment]
@livarcocc @dsplaisted can you comment on this issue?

**Comment by dsplaisted** [comment]
The default configuration is defined by MSBuild and the .NET Core SDK.  If not specified elsewhere it will be Debug.  However, it is possible to override the default in custom MSBuild logic for your project.  So if you don't specify the configuration on the command line it will use whatever the default configuration for your project is, which will typically, but not always, be Debug.

**Comment by Thraka** [comment]
Just to clarify, the searching for the configuration is:

1. Check command line for parameters
2. Check the project for a configuration value, choose the first.
3. Use the MSBuild/Core SDK default, which is `Debug`
