### ISSUE TITLE
where is  &New  ToolStripMenuItem.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12603]
@evday commented on [Fri May 31 2019](https://github.com/dotnet/docs.zh-cn/issues/392)

10.Create an event handler for the Click event of the &New ToolStripMenuItem. 

did you mine &Open  not &New

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a725858d-20f4-bac2-d5f9-9eb0b03c5f0e
* Version Independent ID: 18e7e99b-9dc5-5668-6162-aaf261d045f7
* Content: [如何：将 MenuStrip 追加到 MDI 父窗口 （Windows 窗体）](https://docs.microsoft.com/zh-cn/dotnet/framework/winforms/controls/how-to-append-a-menustrip-to-an-mdi-parent-window-windows-forms)
* Content Source: [docs/framework/winforms/controls/how-to-append-a-menustrip-to-an-mdi-parent-window-windows-forms.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/winforms/controls/how-to-append-a-menustrip-to-an-mdi-parent-window-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is making a suggestion on the original document

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
