### ISSUE TITLE
PDF does not show wrenches correctly

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1261]
I just noticed that the documentation can be [downloaded as PDF](https://opbuildstorageprod.blob.core.windows.net/output-pdf-files/en-us/VS.core-docs/live/articles.pdf). When I opened that PDF, the first thing I noticed is that the wrench symbol does not show correctly.

Here is how it looks in Firefox:

![](http://imgur.com/zkTcGKX.png)

Here is how it looks in TWINUI:

![](http://imgur.com/aZP8MRL.png)

The Firefox screenshot shows that the PDF contains the codepoint U+E000 <Private Use, First>, when it should be U+1F527 WRENCH.

**Comment by mairaw** [comment]
@dend can you look at this?

**Comment by dend** [comment]
Am currently looking at this, thank you for bringing this to my attention.

**Comment by mairaw** [comment]
Since we're removing wrenches from our content, I'm closing this bug.
