### ISSUE TITLE
Would like to be able to download photo

### ISSUE THREAD

**Issue by quickbasic22** [dotnet/docs#12621]
Would like to be able to download photo used in code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86d28245-4d43-da40-4af8-197fa9b19bfd
* Version Independent ID: 62f98241-cb21-f323-b3dc-4a192c100f18
* Content: [How to: Use Interpolation Mode to Control Image Quality During Scaling](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-use-interpolation-mode-to-control-image-quality-during-scaling#feedback)
* Content Source: [docs/framework/winforms/advanced/how-to-use-interpolation-mode-to-control-image-quality-during-scaling.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-use-interpolation-mode-to-control-image-quality-during-scaling.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
You can save a copy of the image to your local system as follows, @quickbasic22:
1.  Select the **Edit** button at the top of the page. This takes you to the document in the dotnet/docs GitHub repo.
2. Navigate to the image, right-click on it, and select **Save picture as** in Chrome or **Save image as** in Edge.
