### ISSUE TITLE
When should dotnet build --runtime flag be used?

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#12623]
When should this runtime flag be used? Is it a general flag which applies to all use cases just to optimize the generated binaries for specific platform? Specifically, is it only used to build self-contained binaries or it can also be used to build app which runs on dotnet core SDK/Runtime?

EDIT by thraka to add doc metdata

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
According to the RID article linked, the runtime identifier helps the engine pick OS specific dependencies like nuget packages. I also think it generates the appropriate binary.
