### ISSUE TITLE
clarify the philosophy on using readonly keyword with list

### ISSUE THREAD

**Issue by vikneshrajsp** [dotnet/docs#12638]
unlike primitive types, we still allow modification on the readonly list; 

https://dotnetfiddle.net/mVkYQ8 (sample)

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly#feedback)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by EugeneKramer** [comment]
The `readonly` modifier does not make a collection immutable, instead it prevents variable reassignment.

For an immutable list, you could use [`ReadOnlyCollection<T>` or `IReadOnlyList`](https://blogs.msdn.microsoft.com/jaredpar/2008/04/22/immutability-and-readonlycollectiont/). For .NET Core, you could use `ImmutableList Class`.

It's a common gotcha that may be worth expounding in the documentation.

**Comment by Thraka** [comment]
@vikneshrajsp as Eugene stated, you cant reassign the variable. A statement to this affect may be worth adding. This creates an immutable variable but if the type is mutable, you have a potential conflict.

**Comment by vikneshrajsp** [comment]
@EugeneKramer Agreed we can use `IReadOnlyList `as you have mentioned. Shouldn't the compiler restrict usage of readonly keyword on mutable types like list?

**Comment by EugeneKramer** [comment]
@vikneshrajsp The documentation for [readonly has been clarified with an update](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly).

The compiler may (though not always) give a warning for using `readonly` on a mutable type, ["CA2104: Do not declare read only mutable reference types" 
](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types?view=vs-2019)

There are valid use-cases for a readonly mutable reference type and this feature is present in other OOP languages.
