### ISSUE TITLE
dotnet CLI

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#12637]
This page should include the `dotnet CLI` commands for a new project and installing packages and so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0888bc80-798f-ebdd-459a-7543be1efdad
* Version Independent ID: c24ded82-d56c-e8c7-fd6a-e39929227177
* Content: [Tutorial: Build a movie recommender - matrix factorization - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/movie-recommmendation)
* Content Source: [docs/machine-learning/tutorials/movie-recommmendation.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/movie-recommmendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Thank you for the feedback @baruchiro. The CLI doesn't currently support the recommendation task. Once it does, we will add documentation for it.

**Comment by bomeers** [comment]
@natke An ML.NET 1.1.0 tutorial for this would be nice as well. I believe it should have to do with the FieldAwareFactorizationMachineTrainer namespace.
