### ISSUE TITLE
Not enough examples to cover all bases, and generalized description not specific enough

### ISSUE THREAD

**Issue by mkstarr** [dotnet/docs#12634]
"Invalid expression" is very vague--it could mean anything. It basically says "you're  breaking a syntax rule" which is even vaguer than the error message itself.

Please define:
-character
-expression
-invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23958040-e5a6-2d3b-4764-d5b0b4126cc4
* Version Independent ID: 91eb2a64-43b2-f128-9170-b263878a3421
* Content: [Compiler Error CS1525](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1525#feedback)
* Content Source: [docs/csharp/misc/cs1525.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs1525.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@mkstarr Can you give me more details about what you were looking for on this page?

I'd like to find a solution, but I'm concerned that an exhaustive list isn't the best solution. There is a large list of tokens that are unexpected in different contexts. What was the original problem, and what led you to this page?

**Comment by BillWagner** [comment]
closing due to lack of response.
