### ISSUE TITLE
Lost the following code from HostSideView to Host

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12646]
@fbiwarning commented on [Mon Jun 03 2019](https://github.com/dotnet/docs.zh-cn/issues/397)

This page do not contain the code about HostSideView HostSideAdapter AddIn and Host. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0e6fd3c3-68eb-a164-f4cb-1ec07c7b233d
* Version Independent ID: da8b15c4-734d-6cc6-fa2d-5f26bb697164
* Content: [如何：创建作为 UI 的外接程序](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui#feedback)
* Content Source: [docs/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because it looks like the user is requesting aditional examples
best

**Comment by rpetrusha** [comment]
Thanks, @CeciAc. This is a case of some of the C# code and all of the Visual Basic code having been lost during a migration.
