### ISSUE TITLE
global not work

### ISSUE THREAD

**Issue by ma17961363** [dotnet/docs#12640]
Why in the following code error appears?!

```csharp
using global::System;

namespace System
{
    class Program
    {
        static void Main(string[] args)
        {
            global::System.Console.WriteLine("Hello World!"); // compiler gives warning conflic for Console and error for WriteLine undefined
        }
    }

    class Console
    {
        public static void T()
        {

        }
    }

    class Test1 : global::System.Console // warning conflict
    {
        public static void T1()
        {

        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9c78b1-4949-0bdb-43af-a9db6e5ebffa
* Version Independent ID: cfea46ac-3926-6274-b29e-4c48f1d3cd63
* Content: [How to: Use the Global Namespace Alias - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias)
* Content Source: [docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
The `global` keyword is useful when you want to disambiguate two entities with similar names, e.g. `System.Console` and `TestApp.Console` in the example. But you have two types with exactly the same name (`System.Console`) and `global` won't help you with that.

If you really want to make this work (and I hope you have a good reason for that, like learning more about C#), you should be able to use [the `extern alias` directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias) to disambiguate the two assemblies

**Comment by ma17961363** [comment]
Than you for the reply. And what is the difference between the followings?

colAlias::Hashtable test = new colAlias::Hashtable();

colAlias.Hashtable test = new colAlias.Hashtable();

**Comment by svick** [comment]
This is explained in [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#namespace-alias-qualifiers):

> Unlike the regular `.` qualifier, the left-hand identifier of the `::` qualifier is looked up only as an extern or using alias.

If you have an alias `colAlias`, `colAlias::Hashtable` is guaranteed to use that alias, while `colAlias.Hashtable` uses the full name lookup rules, which means it could be ambiguous.

You can see the difference in [the following code](https://sharplab.io/#v2:D4AQDABAYg9jEF4ICECGAnA3AWAFB4DtUBbAUwGcAHVAY1OjjwG88I2IQAmCAYQiYC+eIflxEyVWvTTpmrdl178RIvIoAqFAC5zc7BjABchvjQCMmCAHorEGAGtUAT3ltYMAHSnOlmxFLo6DCyuAJAA=):

```c#
using Foo = Bar;

namespace Foo
{
    class C {}
}

namespace Bar
{
    class C {}
}

class Test
{
    Foo::C c1; // okay
    Foo.C c2; // error
}
```

**Comment by Thraka** [comment]
Hello!

I think you will have a better chance of getting these types of questions answered if you post it on a forum such as [StackOverflow](https://stackoverflow.com/search?q=csharp+global+namespace). Though I think you did get it answered 😁 

I'm going to close the issue. 

I am interested though in why you arrived at this article. Are you coming from C++ so the `alias::type` syntax appealed to you?

Thanks.
