### ISSUE TITLE
How to use of A class static members? 

### ISSUE THREAD

**Issue by ma17961363** [dotnet/docs#12647]
In the above example:

namespace N
{
    public class A {}

    public class B {}
}

namespace N
{
    using A = System.IO;

    class X
    {
        A.Stream s1;            // Error, A is ambiguous

        A::Stream s2;           // Ok
    }
}

how is it possible to use A class static members? (A.[static member name])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a24e28e2-cfe0-4050-4a70-b75ae2764ee9
* Version Independent ID: 38ab5b3d-9b72-0c91-152f-fb09552e587f
* Content: [Namespaces - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#namespace-alias-qualifiers)
* Content Source: [spec/namespaces.md](https://github.com/dotnet/csharplang/blob/master/spec/namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
You'd call it just as you would call any static member, @ma17961363. Here, `A` defines no static members of its own, but it inherits `Equals(Object, Object)` and `ReferenceEquals(Object, Object)` from Object. So you could call `ReferenceEquals`, for example, as `A.ReferenceEquals(a, b)`.

**Comment by ma17961363** [comment]
The compiler gets an error that Namespace 'N' contains a definition conflicting with alias 'A'!

**Comment by rpetrusha** [comment]
That's expected, as the source code comment indicates. The code defines a class named `A` and an alias for the System.IO namespace named `A`. The compiler is unable to resolve a reference to `A` and so compilation fails.

**Comment by svick** [comment]
@ma17961363 In that example, the name `A` is ambiguous, but there are other ways to refer to the class that aren't, e.g. `N.A` or `global::N.A`.
