### ISSUE TITLE
Is it legal to decompile .NET Framework using tools like JetBrains dotPeek?

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12648]
Not sure whether this page is the right place for this question, sorry for possibly wrong choice.

My question is about debugging .NET Framework source code in Visual Studio. Sometimes it's impossible: for example, when the downloaded PDB is stripped we get "Source not available" message. There are tools like JetBrains dotPeek which can help, but is it legal? Almost every license agreement nowadays prohibits decompilation, and, if I'm not mistaken, the .NET Framework is no exception:

"You may not" ... "reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software;"

https://dotnet.microsoft.com/dotnet_library_license.htm

But at the same time the source code of .NET Framework is available, and decompilation doesn't add anything except the ability to debug.

So may we do it?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029b7b34-dc3b-f92f-6a63-3713472dc829
* Version Independent ID: ffff836e-3598-bad1-9626-26dc3183c56d
* Content: [Debugging, Tracing, and Profiling](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/#feedback)
* Content Source: [docs/framework/debug-trace-profile/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hi. Thank you for the question. But we cannot answer this; we cannot give any sort of legal advice. If you have legal questions, you should contact a lawyer.

**Comment by user2150** [comment]
Sorry, but my question is also about the debugging workflow: what shoud I do when I've followed all the instructions provided for debugging the sources but got a stripped PDB and still cannot debug? May be I'm missing something which could help without using legally questionable ways? Thanks.
