### ISSUE TITLE
Build "dotnet try" tutorials for C# 7.x

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#12642]
See #8206 for background.

Instead of creating an exploration tutorial for these features, a better and more forward looking plan is to use `dotnet try` to create a tutorial that can be installed and run from the .NET CLI.

The "what's new" articles would remain short, focuses overviews of the new features.  The current explorations https://docs.microsoft.com/dotnet/csharp/tutorials/exploration/csharp-6 and https://docs.microsoft.com/dotnet/csharp/tutorials/exploration/csharp-7 would be retired. Instead, the what's new articles would point readers to the package to try the tutorial using `dotnet try`

Questions that should be resolved:

1. What's the right granularity for the tutorials? Per feature? Per release? All up?
1. Where in the dotnet/samples repo to put code + markdown for the package? Suggestion: dotnet/samples/try/csharp
1. How much and where to adds install instructions for the `dotnet-try` global tool?

**Comment by jonsequitur** [comment]
Possibly helpful in thinking about how to make the experience of starting a tutorial as simple as possible: https://github.com/dotnet/try/issues/217.

**Comment by BillWagner** [comment]
Fixed in dotnet/try-samples#5
