### ISSUE TITLE
404

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12641]
@mcxtlong commented on [Sun Jun 02 2019](https://github.com/dotnet/docs.zh-cn/issues/396)

[在此处输入反馈]
http://www.contoso.com/default.html
404 not found

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6d0d3c05-6a37-ccb6-d897-a4c35beb2597
* Version Independent ID: a826593c-e1e0-2caa-c764-3e3f63322892
* Content: [如何：使用 WebRequest 类请求数据](https://docs.microsoft.com/zh-cn/dotnet/framework/network-programming/how-to-request-data-using-the-webrequest-class)
* Content Source: [docs/framework/network-programming/how-to-request-data-using-the-webrequest-class.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/network-programming/how-to-request-data-using-the-webrequest-class.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Hi team, 
the user is reporting a 404 link which is present in the original example
best

**Comment by karelz** [comment]
Can we please get translation to English, we do not support bug reports in other languages ...

**Comment by CeciAc** [comment]
Hi @karelz 
the reported segment is not localized, because is in the code box.
![imagen](https://user-images.githubusercontent.com/26746247/58824106-b2922900-8611-11e9-9e55-89ee1aa98238.png)

The chinese text in the comment is just a placeholder from the automatic template to logging issues (It just says "Feedback")
best

**Comment by mairaw** [comment]
Adding this feedback item to our community project and our backlog. 
Example could be changed to use a different URL.

Locations that have to be changed:
- https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-request-data-using-the-webrequest-class.md
- https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Network/RequestDataUsingWebRequest/cs/WebRequestGetExample.cs
- https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_Network/RequestDataUsingWebRequest/vb/WebRequestGetExample.vb
