### ISSUE TITLE
What about negative numbers?

### ISSUE THREAD

**Issue by PoulBak** [dotnet/docs#12653]
There's not a word about negative numbers and showing/hiding the plus/minus sign!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f543acea-d042-bbcf-5f83-de8b11644366
* Version Independent ID: 18c2ed9b-4015-109c-1ac2-b9b39ed19e8b
* Content: [Custom Numeric Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings?view=netframework-4.8#feedback)
* Content Source: [docs/standard/base-types/custom-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-numeric-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
There is no feature that allows the minus sign to be shown, @PoulBak. The only control over a plus/minus sign is provided by the **e+**_xx_ and **e-**_xx_ elements.
