### ISSUE TITLE
Examples with CultureInfo do not Run inline

### ISSUE THREAD

**Issue by RoyceLithgo** [dotnet/docs#12659]
Here is the output from pressing the Run button on the 2nd example:

(1,1): error CS0246: The type or namespace name 'CultureInfo' could not be found (are you missing a using directive or an assembly reference?)
(1,33): error CS0246: The type or namespace name 'CultureInfo' could not be found (are you missing a using directive or an assembly reference?)

Remaining examples on the page produce similar errors. Only the first example actually works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63f31e2-886a-e99b-bac1-71264b5d724f
* Version Independent ID: ab45c18d-53e8-c4df-0739-ce4d671fb57b
* Content: [How to: convert strings to DateTime](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-datetime#code-try-1)
* Content Source: [docs/standard/base-types/parsing-datetime.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/parsing-datetime.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for reporting this, @RoyceLithgo. We've added this issue to the **Interactive examples with try.dot.net** for monitoring.
