### ISSUE TITLE
Does not work when the extension is stored in separate dll

### ISSUE THREAD

**Issue by gsoftconsulting** [dotnet/docs#12650]
Works fine when used in the same assembly, but does not work from separate dll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d8ae3c-8c7e-9672-50b8-409c8be3ab73
* Version Independent ID: a7def2f3-beeb-16a4-d769-b9b5f269e6d3
* Content: [Extending the My Namespace in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/customizing-extending-my/extending-the-my-namespace#feedback)
* Content Source: [docs/visual-basic/developing-apps/customizing-extending-my/extending-the-my-namespace.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/customizing-extending-my/extending-the-my-namespace.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
None of the examples in this article have classes marked as `Public`. Can you verify that the extensions you deployed via a DLL are marked `Public`?

**Comment by gsoftconsulting** [comment]
Thank you for the good suggestion. I tested public methods and public modules. 
t looks like a systemic issue in Visual Basic.net My namespace. It does not work when linked from separate assembly.

**Comment by Thraka** [comment]
I played around with this and then read through some of the articles around this and I think **My** extensions are only deployed via code. They are not imported as compiled libraries. If you want to be able to add it as a **My Extension** in visual studio then you have to [register and publish your extension with Visual Studio](https://docs.microsoft.com/dotnet/visual-basic/developing-apps/customizing-extending-my/packaging-and-deploying-custom-my-extensions) which, when installed, will copy the code file into your project in a path similar to `.\yourapp\My Project\MyExtensions\MyExtensionFile.vb`

I'm going to close this issue as I feel your question is answered.
