### ISSUE TITLE
Sample for ranking task

### ISSUE THREAD

**Issue by marchy** [dotnet/docs#12656]
Could you please put up a sample of a ranking task?

The mentioned algorithms seem to require a 'groupId' field, but could not get this working despite a bunch of trial & error. The documentation for these wrongly state that the column is optional (ie: 'The optional groupID column that the ranking trainers expects.' - link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree.fasttreerankingtrainer?view=ml-dotnet)

Some insight on this would be much appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks#feedback)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **johalex**

**Comment by natke** [comment]
Thank you for this suggestion @marchy. We have added it to our backlog.

**Comment by marchy** [comment]
Thanks a lot @natke. For the time being we temporarily hacked around it by creating multiple independent binary classifiers for each rank – which we know is not really the way to go. Though it brings up a good point, is an approach like this roughly equivalent in effectiveness, or would a purpose-built ranking classifier always perform better?

(I ask because we are also simulating a multi-label classifier in a similar, aggregated way – since ML.NET doesn't yet seem to support any multi-label classifiers)

**Comment by JRAlexander** [comment]
@prathyusha12345 and @CESARDELATORRE - any feedback on this? Thanks!

**Comment by CESARDELATORRE** [comment]
We’re working on a sample for Ranking (Nicole Haugen). It’ll be ready in the upcoming days.
Thanks for the feedback! :)

**Comment by natke** [comment]
@marchy We should have the sample up soon. In terms of your approach of using multiple independent binary classifiers, can you elaborate a little more on the solution you used here? And did the results of this approach meet your requirements?

**Comment by natke** [comment]
@marchy The sample is up here: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Ranking_Web
