### ISSUE TITLE
The False method is not a member of the Assert class

### ISSUE THREAD

**Issue by gjaryczewski** [dotnet/docs#12661]
It looks that this line:
Assert.False(result, "1 should not be prime")
should be:
Assert.IsFalse(result, "1 should not be prime")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f3ccd5-7cf4-f401-4797-9d8ef182fe82
* Version Independent ID: 7168f552-cf3f-b1ee-dc3d-5a38aa093730
* Content: [Unit testing Visual Basic in .NET Core with dotnet test and MSTest - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-visual-basic-with-mstest#feedback)
* Content Source: [docs/core/testing/unit-testing-visual-basic-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-visual-basic-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for reporting this issue, @gjaryczewski. We've opened #12667 to correct the method name.
