### ISSUE TITLE
The FastTree algorithm is in separated nuget

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#12663]
We must add the `Microsoft.ML.FastTree` to use it

---
#### פרטי מסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using regression - ML.NET](https://docs.microsoft.com/he-il/dotnet/machine-learning/tutorials/predict-prices)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @baruchiro! This may be a localization issue. This issue was fixed a while back. Will follow up offline. Closing as I think this is resolved but will comment here if there are any updates.

**Comment by alex-dranoel** [comment]
Thanks @baruchiro, I had the same issue, and the same solution solved it. Would be nice to have it indicated in the tutorial.
