### ISSUE TITLE
SIMD docs

### ISSUE THREAD

**Issue by FIVIL** [dotnet/docs#12660]
I recently used SIMD capabilities of .net and I find it fascinating, however, the official documentation seems lagging in this regard -the only thing I could find is this [Numerics in .NET](https://docs.microsoft.com/en-us/dotnet/standard/numerics) which is not complete- so I wanted to create a complete SIMD documentation.
my proposed outline  contains:
1. What is SIMD
1. How we can use SIMD in .net
1. Caution and don'ts of SIMD
1. Maybe some benchmarks at the end

also, I did some docs contribution to .Net foundation projects not long ago, and I'm fairly familiar with the process.
https://github.com/aspnet/AspNetCore.Docs/issues/11770
https://github.com/aspnet/AspNetCore.Docs/pull/12108
https://github.com/aspnet/AspNetCore.Docs/pull/12137

**Comment by rpetrusha** [comment]
Thanks you, @FIVIL, for offering to provide some solid information on SIMD. We'd welcome your contribution, and your basic outline looks good. How would you like to proceed, and what sort of time frame are you looking at for submitting a PR?

@terrajobst, do you have any feedback about more detailed SIMD content?

**Comment by terrajobst** [comment]
@tannergooding would be the best person to provide feedback on this because he's been working heavily on all the intrinsics lately. We should probably talk about SIMD in general and then how we're exposing in the the BCL, as an abstraction (`Vector<T>`) and as a set of in `System.Runtime.Intrinsics`.

I like the idea of dos and dont's but that's definitely @tannergooding territory.

**Comment by tannergooding** [comment]
Adding conceptual docs for hardware intrinsics is on my list of backlog items to do for 3.0. However, I would be very happy if someone else wanted to start that work and would be happy to review and provide input as appropriate 😄 

Also CC. @danmosemsft

**Comment by rpetrusha** [comment]
Thanks, @tannergooding. Does the rough outline that @FIVIL provided sound good, with the possible addition of a section on SIMD and the underlying hardware?

**Comment by tannergooding** [comment]
Yes, the four sections listed look to cover what I would expect.

**Comment by FIVIL** [comment]
@rpetrusha , I'm planning to get the best of my free time by providing this tutorial, so I think maybe I can deliver it in a month or so, hope that's Ok, and after that, I'll be open to any note and comment and change needed in order to finalize it.  and also I think the best way to do this will be 2 separate articles the first one containing a simple definition and instruction and some simple code samples for starters. and the second article will be a deep dive into the concept of SIMD, underlying hardware, CPU, capabilities and the best practices for SIMD with some insights and of course, some benchmarks to demonstrate benefits of using SIMD.
I will `/cc` you in the PRs.

**Comment by FIVIL** [comment]
@tannergooding and @terrajobst  tnx for your insights.
also, I might need to ask some questions about some concepts during the process if that's OK.

**Comment by rpetrusha** [comment]
That sounds good, @FIVIL. We'll look forward to reviewing your PR in about a month.
