### ISSUE TITLE
false operator returns true

### ISSUE THREAD

**Issue by casdijkman** [dotnet/docs#12679]
&gt; [false operator](true-false-operators.md) - returns the [bool](../keywords/bool.md) value `true` to indicate that an operand is definitely false.

should be

&gt; [false operator](true-false-operators.md) - returns the [bool](../keywords/bool.md) value `false` to indicate that an operand is definitely false.

 In docs/docs/csharp/language-reference/operators/index.md  Unary operators section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators](https://docs.microsoft.com/en-in/dotnet/csharp/language-reference/operators/index#feedback)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@casdijkman The article is correct.  `operator false` answers the question "Is this false?" (Similarly, `operator true` answers the question "Is this true?" )

See [User defined logical operators](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#user-defined-conditional-logical-operators) in the C# language spec, and the referenced example.

**Comment by casdijkman** [comment]
@BillWagner Thanks for your reply. You are correct. I misinterpreted the false operator
