### ISSUE TITLE
Warn about carefully placing the --self-contained flag

### ISSUE THREAD

**Issue by akeeton** [dotnet/docs#12671]
When placed at the end of the options, the `--self-contained` flag will not work:

    dotnet publish --runtime win-x64 --configuration debug --self-contained project.fsproj
    [...]
    C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\target\Microsoft.NET.Sdk.targets(146,23): error MSB4030: "project.fsproj" is an invalid value for the "IsSelfContained" parameter of the "GenerateDepsFile" task. The "IsSelfContained" parameter is of type "System.Boolean".

The fix is either to supply `true` to `--self-contained`:

    dotnet publish --runtime win-x64 --configuration debug --self-contained true project.fsproj

or to rearrange the options:

    dotnet publish --self-contained --runtime win-x64 --configuration debug project.fsproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
I think it would be better to just specify `true|false` on the command line ref. Then you avoid the problem completely 😄

**Comment by mairaw** [comment]
That seems like a CLI bug to me. @KathleenDollard @livarcocc can you comment on this?

**Comment by KathleenDollard** [comment]
@livarcocc @jonsequitur
