### ISSUE TITLE
Links are confusing

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/docs#12689]
This is one of the most odd pages I've ever been to on Docs. 

First, the superscript tags are odd.
![image](https://user-images.githubusercontent.com/1784452/58974763-dfb51780-8788-11e9-9d86-1cd2d1796d0d.png)

A. It's strange to see footnotes that are more than just 1, 2, 3 or a, b, c. I can't think of anywhere else I've seen named footnotes.
B. All the links essentially go to the exact same spot on the page (since everything is close together), making them kind of useless.

Then, at the bottom, there are all these other odd links
![image](https://user-images.githubusercontent.com/1784452/58976073-3c660180-878c-11e9-8da9-91c321aba8ab.png)

When I first saw this, I couldn't even figure out what I was looking at. Specific issues:

1) The return arrow is an odd choice. I thought it was a typo. Is there a precedent for this?
2) Only the return arrow, links back up. The text portion of the links do nothing.
3) "CS80", for example, should probably be "C# 8.0"

In my opinion, every single one of these links (in both images) are completely useless and overkill.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3c8595-6bf5-61b0-fe12-f6cbbb1e2da8
* Version Independent ID: ac04cb00-0bfc-7bde-885d-c1dce0f35b4c
* Content: [-langversion (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option#FCS71)
* Content Source: [docs/csharp/language-reference/compiler-options/langversion-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/langversion-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @MisinformedDNA. Was this the design intent for this page, @BillWagner? I find it confusing as well.

**Comment by BillWagner** [comment]
Those superscripts should be removed. I think this was migrated strangely from MSDN.

I've added the "up for grabs" label and added this to our backlog.

**Comment by alx168** [comment]
I'll do it.
