### ISSUE TITLE
How to do this problematically?

### ISSUE THREAD

**Issue by leonmeijer** [dotnet/docs#12681]
How to do this problematically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0f416a-1b76-ac94-2fe5-45a163159624
* Version Independent ID: 50a5efbf-5ff0-d780-ab31-693de2f760e7
* Content: [Recommended Settings for Tracing and Message Logging](https://docs.microsoft.com/en-us/dotnet/framework/wcf/diagnostics/tracing/recommended-settings-for-tracing-and-message-logging)
* Content Source: [docs/framework/wcf/diagnostics/tracing/recommended-settings-for-tracing-and-message-logging.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/diagnostics/tracing/recommended-settings-for-tracing-and-message-logging.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I think you mean programmatically 😃 

Can you explain why you want to do this? This may help someone figure out what issue you're trying to solve. I believe the config is loaded at runtime and it's a lot harder to change. You need to manually load all your endpoints and provide manually created configs. 

For example: https://stackoverflow.com/questions/4041289/change-switchvalue-on-trace-listener-in-runtime

**Comment by Thraka** [comment]
Closing due to lack of response
