### ISSUE TITLE
Reconcile multiple gac / assembly topics

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#12680]
This started from a discussion on #12573 

Much of the important discussion is captured there. The fix for this issue should accomplish the following:

1. Content no longer necessary is retired.
1. Content still relevant is in an appropriate location in the .NET content. 
1. Relevant content is visible in the appropriate TOC.

This content is language independent, so the C# Guide and VB Guide are not good locations. Would it be better in the .NET Guide, or the .NET Framework guide?

**Comment by rpetrusha** [comment]
This work was completed by #13825 and #13851. Closing.
