### ISSUE TITLE
In Visual Studio, you set compiler options in the web.config file.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#12690]
Moved from #4192

@eduard-malakhov  wrote:
[This](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/) topic says "In Visual Studio, you set compiler options in the **web.config** file". Is that correct? I think this sentence is misleading as AFAIK _web.config_ only exists for web applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1ea586-7719-df69-7d8a-8a04cddb5543
* Version Independent ID: 691a6e9e-00ea-6210-c64a-659ba7930bec
* Content: [C# Compiler Options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/)
* Content Source: [docs/csharp/language-reference/compiler-options/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I'm assuming you're moving this to get the metadata and back on the radar? If so I'll close the other one and move the other assigned labels to this one too.

**Comment by Rick-Anderson** [comment]
•	Other customers can easily find the issue.
•	We can easily find the issue.
•	Makes it easy to find all issues for a doc when updating the doc.
* metadat

**Comment by mairaw** [comment]
I usually just edit the original issue to add the topic details.

**Comment by Rick-Anderson** [comment]
That misses all the advantages I listed. 

* Other customers can easily find the issue.
* We can easily find the issue.
* Makes it easy to find all issues for a doc when updating the doc.
* metadata rollup

**Comment by Rick-Anderson** [comment]
Customers are usually happy to move the issue. It's rare I need to move one. Given this was created so long ago I moved it.

**Comment by Rick-Anderson** [comment]
We've found out it really helps cut down on duplicate issues. Often the issue has work-arounds customers can find.

**Comment by Thraka** [comment]
I think she means we usually just copy/paste the metadata back into the original issue 😄 But that's harder to do if you don't have existing issues on the same article to copy/paste.

**Comment by Rick-Anderson** [comment]
But then it's not integrated - other customers can't see it from the doc page - right?

**Comment by mairaw** [comment]
It's not hard. I just visit the article and click here to copy the metadata:
![image](https://user-images.githubusercontent.com/12971179/58983269-4c311600-878b-11e9-8cbc-e414677ec207.png)

**Comment by mairaw** [comment]
@Rick-Anderson yes, it is integrated.

**Comment by Rick-Anderson** [comment]
closed and reopened #4192

**Comment by Thraka** [comment]
Ahhh cool, I didn't realize I could create it via that link. I've had to open and close an issue to get the metadata. NICE.
