### ISSUE TITLE
while (allTasks.Any()) runs all tasks multiple times?

### ISSUE THREAD

**Issue by AskYous** [dotnet/docs#12691]
Doesn't running `Task.WhenAny()` run **all** the tasks? Since the loop in the example runs 3 times, and `WhenAny()` runs 3 times inside that loop, it seems 3 + 2 + 1 asynchronous operations are run. This seems inefficient since some tasks are run multiple times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mattumotu** [comment]
`WhenAny` doesn't run the tasks passed to it, the tasks in `allTasks` are already running.

WhenAny creates a new task that will complete when any of the (existing, running) tasks it is given completes.

From [WhenAny MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenany?view=netframework-4.8)

>Creates a task that will complete when any of the supplied tasks have completed. ...
>The return task's Result is the task that completed.

So when any creates a new task which, when it completes, returns the first completed task from your list.

**Comment by AskYous** [comment]
Does it only complete when the first task complete, or every time any of the tasks complete?

**Comment by Mackiovello** [comment]
> Does it only complete when the first task complete, or every time any of the tasks complete?

It only completes when the first task completes.

**Comment by AskYous** [comment]
Ok thank you.

**Comment by Siddhu-cs** [comment]
@Askyous @Mackiovello Let's say you have started 10 tasks which return same data from different source. Now you want result from any of these 10, whoever gives you result first, for this purpose you can you Task.WhenAny(). If you want to wait for all task to complete then you can use Task.WhenAll()

**Comment by AskYous** [comment]
Thanks @Siddhu-cs. Very clear!
