### ISSUE TITLE
Is it the right types categorizing?

### ISSUE THREAD

**Issue by ma17961363** [dotnet/docs#12699]
type
    : managed_type (safe_type)
    | unmanaged_type (unsafe_type)
    ;

unmanaged_type
    : pointer_type
    | pointer_type '*'
    ;

pointer_type
    | simple_type '*'
    | enum_type '*'
    | unmanaged_user_defined_struct_type '*' 
    | void *
    ;

managed_type
    : value_type
    | reference_type
    | parameter_type
    ;

And the rest of the categorization is like the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de24f644-5e7c-d3de-fd13-5969bb3e4b78
* Version Independent ID: 9173876e-49be-6c60-634d-eeb1944ab2fc
* Content: [Types - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#default-constructors)
* Content Source: [spec/types.md](https://github.com/dotnet/csharplang/blob/master/spec/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by ma17961363** [comment]
Stars (pointer signs) in the pointer_type (simple_type and enum_type) was forgotten:

pointer_type
| simple_type '*'
| enum_type '*'
| unmanaged_user_defined_struct_type '*'
| void *
;

**Comment by BillWagner** [comment]
The spec is correct. The unmanaged types are in the section on Pointer types. 

Closing.
