### ISSUE TITLE
Doesn't work if you follow the instructions

### ISSUE THREAD

**Issue by RoyceLithgo** [dotnet/docs#12693]
On the previous step when changing the web properties for the site you need to change the url to http: instead of the default https. Otherwise when you launch the site as per instructions on this page you get an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0756f2f-e237-6d87-9c5b-f17d1f2561cd
* Version Independent ID: 3a3eaf22-93c6-cf57-42cc-84cf92ac0c94
* Content: [Accessing the Service from a Web Browser (WCF Data Services Quickstart)](https://docs.microsoft.com/en-us/dotnet/framework/data/wcf/accessing-the-service-from-a-web-browser-wcf-data-services-quickstart)
* Content Source: [docs/framework/data/wcf/accessing-the-service-from-a-web-browser-wcf-data-services-quickstart.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/wcf/accessing-the-service-from-a-web-browser-wcf-data-services-quickstart.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
This was fixed in passing by someone. No HTTPS is in the article or the previous article.
