### ISSUE TITLE
Naming of example Delegate types doesn't conform with Naming Guidelines 

### ISSUE THREAD

**Issue by Jonathan727** [dotnet/docs#12706]
The naming of example delegates in this document doesn't conform to rules listed in [Design Guidelines - Names of Common Types - Delegates](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#names-of-common-types) which state:
> √ DO add the suffix "EventHandler" to names of delegates that are used
> in events.  
> √ DO add the suffix "Callback" to names of delegates other
> than those used as event handlers.  
> X DO NOT add the suffix "Delegate" to a delegate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b07199-b747-9596-1d38-3257f43b4833
* Version Independent ID: d162375c-ef5a-41c1-fe26-2e6394bf1df1
* Content: [How to: Declare, Instantiate, and Use a Delegate - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate#feedback)
* Content Source: [docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. Good catch.

Thanks again!

**Comment by Jonathan727** [comment]
@BillWagner I wrote a pull request to at least partially resolve this issue. #22497
