### ISSUE TITLE
"Next" button link is returning 404

### ISSUE THREAD

**Issue by luisdeol** [dotnet/docs#12700]
When clicking on the "Next" button, which points to the "https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/docker-application-development-process" URL, a 404 page is returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4718315e-ee77-0d95-c46d-4eaada53f924
* Version Independent ID: 4e7f1467-9834-303c-135f-4c9ff39374f2
* Content: [Orchestrating microservices and multi-container applications for high scalability and availability](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications#feedback)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by rpetrusha** [comment]
Thank you for reporting this issue, @luisdeol. It was fixed by dotnet/docs#12683. Closing.
