### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rjdunnill** [dotnet/docs#12708]
"... that it does not supported …" should be "that it does not support ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0322d9b-3d55-5ed3-1ab5-8bdafff12f06
* Version Independent ID: 1f8d476b-ced0-d0cf-8c7a-4616d9e36222
* Content: [COM Callable Wrapper](https://docs.microsoft.com/en-us/dotnet/framework/interop/com-callable-wrapper#feedback)
* Content Source: [docs/framework/interop/com-callable-wrapper.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/com-callable-wrapper.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out the typo, @rjdunnill. We've opened #12710 to fix it.
