### ISSUE TITLE
Document how to have dotnet restore print which feed a package was resolved from

### ISSUE THREAD

**Issue by cdmihai** [dotnet/docs#12713]
Can't figure how to get nuget tell me which feed it resolved a package from. `-v diagnostic` cranks up msbuild's verbosity, but the nuget tasks still don't log that information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#feedback)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CleytonGoncalves** [comment]
It would be great to have this info.

**Comment by dsplaisted** [comment]
This would be a feature request for NuGet.  @tdykstra I think we should move it to NuGet/home.

**Comment by tdykstra** [comment]
Moved to https://github.com/NuGet/Home/issues/9479
