### ISSUE TITLE
Interface page documentation needs some cleanup

### ISSUE THREAD

**Issue by Naeso** [dotnet/docs#12721]
I am beyond shocked. 

Why calling ISampleInterface.SampleMethod() ???

Why not using a single line of code for getters and setters for x and y ?
int x{ get; set; }
It's just way simple to read that way.

Also, static void Main() ? Could someone explain to me what's going on here ?

I forgot probably some stuff but I don't think this is a good example for people that want to know how to use interfaces. It just creates bad practices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef21cb62-9cbd-84c8-cfae-6dd1a421180b
* Version Independent ID: d931e899-d6f0-55ff-ab3a-dfff6e31f5a2
* Content: [interface - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface#feedback)
* Content Source: [docs/csharp/language-reference/keywords/interface.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/interface.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Naeso This page is a reference page. It assumes some knowledge and experience with the C# language.

To get more background on the different elements of C#, along with guidance on how the different language components are used, I suggest our [tutorials](https://docs.microsoft.com/dotnet/csharp/tutorials/) section. In addition, the programming guide answers many of those questions. The first link in this article is the programming guide topic on [interfaces](https://docs.microsoft.com/dotnet/csharp/programming-guide/interfaces/index) which answers some of your questions.

I'm closing this, as these questions are better answered in our learning materials.
