### ISSUE TITLE
Not clear how the threading model works

### ISSUE THREAD

**Issue by parnesen** [dotnet/docs#12730]
I'm used to using a Promise pattern in a single-threaded GUI environment that has asynchronous calls to a REST server. Can I use async/await in a single-threaded environment or is it strongly connected to multi-threading? For example, does putting async in front of an async method kick off a new thread every time, or does it just execute that method on the same thread, and that method happens to return a Task, as with Promises? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@parnesen `async` and `await` do implement the promise pattern, and can be used in a single threaded application. An async method returns a `Task`, or `Task<T>`, which is the Promise.

closing as answered.

**Comment by Siddhu-cs** [comment]
@parnesen essential truth of async in its purest form: There is no thread
check out this link https://blog.stephencleary.com/2013/11/there-is-no-thread.html
