### ISSUE TITLE
The example does not compile

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12738]
The using list is incorrect.

Instead of

using System.Reflection;  
using System.IO;  

should be

using System.Reflection;
using System;
using System.Linq;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fb28f0f-fc14-b18a-54a4-ad9fe799807f
* Version Independent ID: 391c79a2-90e0-072c-5112-4790590b29a1
* Content: [How to: Query An Assembly's Metadata with Reflection (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-query-an-assembly-s-metadata-with-reflection-linq#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-query-an-assembly-s-metadata-with-reflection-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-query-an-assembly-s-metadata-with-reflection-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing out that the example doesn't compiler, @user2150. We've opened #12759 to correct both the C# and the Visual Basic code.
