### ISSUE TITLE
Link to Linq topic does not exists in C# page

### ISSUE THREAD

**Issue by miguelmateojp** [dotnet/docs#12739]
While this path is valid: https://docs.microsoft.com/en-us/dotnet/csharp/linq/, there is no link from https://docs.microsoft.com/en-us/dotnet/csharp/ left topic menu, I was personally expecting a link there to explain Linq in C#.

**Comment by svick** [comment]
It is there, it's just hidden under "C# Concepts":

![](https://user-images.githubusercontent.com/287848/59148746-2024c780-8a0d-11e9-886e-ec3fb9d26756.png)

**Comment by miguelmateojp** [comment]
By design, the menu is hidden under C# concepts ...
