### ISSUE TITLE
Self Contained Executable

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [dotnet/docs#12735]
We could use an example on running one of these examples as a self contained console app on linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa0c79e-1729-15f7-52e4-0c9afff43ec9
* Version Independent ID: 1c3c5d30-9690-8c4a-4e2c-2ce5f4386898
* Content: [Get started with .NET Core using the CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-with-xplat-cli#feedback)
* Content Source: [docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-with-xplat-cli.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Sure. I think we can add the commands to the end of the tutorial to publish a self-contained deployment and a framework-dependent deployment (which is the new default for core 3.0)

**Comment by Thraka** [comment]
As an interim, I've included publishing descriptions for the modes supported by .NET Core 2.1 which this article was written for. I'm going to file a new issue to track updating this article to 3.0 which would then include the self-contained executable publishing info.
