### ISSUE TITLE
Missing list elements

### ISSUE THREAD

**Issue by JesseTG** [dotnet/docs#12737]
It looks like there should be some list elements here, but they contain no text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5bd6ac-153c-0502-e8b6-2c53af0fab5e
* Version Independent ID: a1aa2ef3-554b-3dff-9b16-1f9f5e478cba
* Content: [ISymbol.HasUnsupportedMetadata Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol.hasunsupportedmetadata?view=roslyn-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/ISymbol.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/ISymbol.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for letting us know about this issue @JesseTG.

It seems that the content is in the source code. Not sure if it's an issue in our reflection tool or the tags being used. Need to investigate.

/cc @BillWagner @dendeli-msft @joelmartinez

**Comment by BillWagner** [comment]
See also dotnet/csharplang/#1765  This will need to get fixed in the source at this time.  /cc @sharwell

**Comment by sharwell** [comment]
@BillWagner it should be possible to update the documentation generation tool to allow this case without waiting for the language or compiler. This is the behavior already used by the IDE itself as well as tools like Sandcastle Help File Builder.

**Comment by BillWagner** [comment]
@dendeli-msft @joelmartinez Can you comment on Sam's suggestion?

**Comment by mairaw** [comment]
Opened PR to fix this in the Roslyn source code in the meantime: https://github.com/dotnet/roslyn/pull/36386

**Comment by dendeli-msft** [comment]
@mairaw this looks like a ECMA2YAML bug. Please open a bug for us to investigate 😄

**Comment by mairaw** [comment]
Will do. Thanks @dendeli-msft!

**Comment by BillWagner** [comment]
This has been fixed in dotnet/roslyn#36386 and delivered in the latest doc update.
