### ISSUE TITLE
Var pattern: Unfortunate code example makes the "var pattern" appear without purpose

### ISSUE THREAD

**Issue by elgonzo** [dotnet/docs#12736]
The example code given for the "_var pattern_":
````
object[] items = { new Book("The Tempest"), new Person("John") };
foreach (var item in items) {
    if (item is var obj)
        Console.WriteLine($"Type: {obj.GetType().Name}, Value: {obj}"); 
}
````
is just a needlessly complicated way of writing
````
object[] items = { new Book("The Tempest"), new Person("John") };
foreach (var item in items)
    Console.WriteLine($"Type: {item.GetType().Name}, Value: {item}"); 
````
thus inadvertently making it look like as if the "_var pattern_" has no useful function or purpose.

It would benefit the documentation if it would show an example code demonstrating the "_var pattern_" in a meaningful way. Perhaps something like the code snippet in this answer on StackOverflow: https://stackoverflow.com/a/50660530/2819245 (No, i am not nor otherwise related to the author of this answer.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3126aaa9-8f5f-04f3-2d75-96477b6273cd
* Version Independent ID: 3f4b3eac-11eb-2dd6-4f27-b24537367288
* Content: [is - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#var)
* Content Source: [docs/csharp/language-reference/keywords/is.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/is.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @elgonzo That's a good example to add.

Another use is to check for `null`.  Consider this slightly modified version of the original example:

```csharp
object[] items = { new Book("The Tempest"), null, new Person("John"), null };
foreach (var item in items) {
    if (item is var obj)
        Console.WriteLine($"Type: {obj.GetType().Name}, Value: {obj}"); 
}
```

The `is` check will be `false` for the `null` values, so it won't throw a `NullReferenceException`.

I've added the "up for grabs" label to this issue, and added it to our backlog for when we next update this article.

**Comment by elgonzo** [comment]
No, [that doesn't work](https://dotnetfiddle.net/Z47ndb). The var pattern cannot be used for `null` testing, as its result will always be `true`. The documentation for the var pattern already mentions this behavior, just before the code example my report is about.   :-)

**Comment by Potapy4** [comment]
@BillWagner @elgonzo 

what do you think if we add a check for `null` as follows:
```csharp
object[] items = { new Book("The Tempest"), null, new Person("John"), null };
foreach (var item in items) {
    if (item is var obj && obj != null)
        Console.WriteLine($"Type: {obj.GetType().Name}, Value: {obj}"); 
}
```

**Comment by BillWagner** [comment]
@Potapy4 I like it.

**Comment by elgonzo** [comment]
I apologize and i do not intend to offend, but the concern i expressed in my opening post would also apply to the code example in the last post, as (similarly to the original code example) is  just an needlessly complicated way of writing:
```
object[] items = { new Book("The Tempest"), null, new Person("John"), null };
foreach (var item in items) {
    if (item != null)
        Console.WriteLine($"Type: {item.GetType().Name}, Value: {item}"); 
}
```

**Comment by Countryen** [comment]
Hey there, have the same question/concern about this:
Is there any reason to write:

```
  object[] items = { new Book("The Tempest"), null, new Person("John"), null };
  foreach (var item in items) {
----> if (item is var obj && obj != null)
          Console.WriteLine($"Type: {obj.GetType().Name}, Value: {obj}"); 
  }
```

instead of:

```
  object[] items = { new Book("The Tempest"), null, new Person("John"), null };
  foreach (var item in items) {
----> if (item != null)
          Console.WriteLine($"Type: {item.GetType().Name}, Value: {item}"); 
  }
```

Also, is this the same, too?

`var obj = item;`
`item is var obj;`

If this is true:
>The result of the is expression is always true.

Why should I ever consider using it?
Is this just an error in the docs?

**Comment by mssteele** [comment]
Hi @BillWagner, I was going to have a go at this one but I'm not sure how to edit the code sample. Is it this one? https://github.com/dotnet/samples/blob/master/snippets/csharp/language-reference/keywords/is/is-var-pattern8.cs
If so do you edit that in a separate PR to the md file change?
Thanks

**Comment by BillWagner** [comment]
@mssteele Your comment above is correct. Editing that sample will update the code in this article.

Thanks! I'll watch for a PR.

**Comment by Denis535** [comment]
I think you could add a note for clarity that this expression is something like: `expr is not null value`

**Comment by elgonzo** [comment]
> 
> 
> > If expr evaluates to null, the is expression produces **true** and assigns null to varname.
> 
> Looks like a typo here. It should produce false when null.

No, it is not a typo. It produces `true`. Try it out... (for example on dotnetfiddle: https://dotnetfiddle.net/wnUlt0)

**Comment by Denis535** [comment]
Looks like it always produce ```true```.

**Comment by Denis535** [comment]
> var pattern, a match that **always succeeds** and binds the value of an expression to a new local variable.
It's testing nothing, just declare new variable.
