### ISSUE TITLE
Naming rule violations

### ISSUE THREAD

**Issue by RichEme** [dotnet/docs#12746]
You may want to fix the "Naming rule violations".
Also, do you know of a stand-alone that would go through all my projects and update to the Naming convention?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5154904d-b7d9-3eaa-7d2e-5ca8308f1f48
* Version Independent ID: 8b82f235-ec9c-5c72-d001-b761b491d400
* Content: [Handling Events (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/events/walkthrough-handling-events#feedback)
* Content Source: [docs/visual-basic/programming-guide/language-features/events/walkthrough-handling-events.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/events/walkthrough-handling-events.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

The source code used by this file is at https://github.com/dotnet/samples/tree/master/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbcnWalkthroughDeclaringAndRaisingEvents/VB/

Regarding applying all code styles, I think there is some basic stuff in Visual Studio if you right-click on the project and find something like *Analyze and apply fixes* and other plugins like resharper has this capability too.

Thanks again!

**Comment by RichEme** [comment]
Thanks.
