### ISSUE TITLE
Broken URL for contoso.com

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#12742]
Related to this [PR](https://github.com/dotnet/samples/pull/965):
I tried to get many places where the domain contoso.com is used. The list I've got is:

https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.net.networkcredential?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress.-ctor?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-client-sockets
https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example
https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.connection?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailmessage.from?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.syndication.syndicationfeed?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-client-sockets
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailmessage.bcc?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.web.mail.smtpmail?view=netframework-4.8
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.addweballowedobject
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-send-data-using-the-webrequest-class
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.security.x509certificateinitiatorclientcredential.setcertificate?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-send-data-using-the-webrequest-class
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?view=netframework-4.8
https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2
https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/working-with-certificates
https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.fragment?view=netframework-4.8
https://docs.microsoft.com/en-us/uwp/api/windows.networking.hostname
https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?view=netframework-4.8

I think there are still more than that, Should I keep searching more ? or these examples have contoso.com should remain the same ?

**Comment by rpetrusha** [comment]
There are also numerous occurrences in the dotnet/docs repo. Some can remain -- they probably should be replaced only if they're part of a working example. 

I'll add this to the community contributor's project for the moment, and assign it to the backlog.

**Comment by Youssef1313** [comment]
@BillWagner, It seems that Microsoft bought the contoso.com domain is it now redirects to microsoft.com. This should be closed now right ?
