### ISSUE TITLE
How do you completely avoid referencing the Infrastructure section in Startup.cs?

### ISSUE THREAD

**Issue by MP7373** [dotnet/docs#12744]
I was looking through the eShopOnWeb repo and I noticed that services.AddDbContext&lt;CatalogContext&gt; is called in Startup.cs and CatalogContext is from the Infrastructure part of the repo which ruins the entire point of them being separate (then I looked back here and saw the note saying that the example does reference infrastructure namespaces in the Startup.cs). I was going to make a sample ASP.NET project following this clean architecture but I want to do it correctly without cheating. How do I make the ASP.NET app have 0 compile time dependencies to the infrastructure section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: 9e50c3eb-ea4b-0390-4b72-ae1dae2de4d3
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/common-web-application-architectures#feedback)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/common-web-application-architectures.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Hi @MP7373 
This should put you on the right path, using Autofac as an example. The sample app doesn't do it this way because most developers expect to find the EF Core DI registration happening directly in ConfigureServices().
https://stackoverflow.com/a/50125393/13729

See also:
https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions
(which uses .NET, not .NET Core)

**Comment by MP7373** [comment]
Thanks for replying i'll read into those.

**Comment by Qyperion** [comment]
> Hi @MP7373
> This should put you on the right path, using Autofac as an example. The sample app doesn't do it this way because most developers expect to find the EF Core DI registration happening directly in ConfigureServices().
> https://stackoverflow.com/a/50125393/13729
> 
> See also:
> https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions
> (which uses .NET, not .NET Core)

It seems to me that using another IoC-container is a bit inconvenient. I implemented another option in the Net Core solution. I split the base UI project into two projects: UI and Host. The point is that in the Host project, only DI registration and other service things remain. And the new UI project is an ordinary class library, where I moved the Controllers, Views, wwwroot and all the rest UI things. As a result, the UI project has no links to the Infrastructure layer.
It looks something like this:
![Screen](https://user-images.githubusercontent.com/13679470/70861872-ca415700-1f3c-11ea-9da4-8df7dc9928bf.png)

I would be grateful for your @ardalis comment on such an implementation.

**Comment by ardalis** [comment]
That should work. I think it's a matter of choosing which is more inconvenient:

- Using a third-party IOC container like Autofac (which has more features than the built-in container)
- Adding another project to your solution to support app startup

I lean toward the former but if you prefer the latter I see no reason it won't work fine.
