### ISSUE TITLE
String concatenation output correction

### ISSUE THREAD

**Issue by TheOnlyMrCat** [dotnet/docs#12751]
The first line of the first example would print with two spaces between "Forgot" and "white space"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e31f06e-936e-d0c7-9dc0-9d10fd8a0dd9
* Version Independent ID: 43899711-a922-8180-25e6-d52af245846d
* Content: [+ and += operators - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-operator#feedback)
* Content Source: [docs/csharp/language-reference/operators/addition-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/addition-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@TheOnlyMrCat thanks for the notice.
