### ISSUE TITLE
Please explain how to debug unit tests.

### ISSUE THREAD

**Issue by AskYous** [dotnet/docs#12762]
I see how to debug the app, but it doesn't mention how to debug unit tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d01d28-eba7-401c-5716-1361edfa928d
* Version Independent ID: f235603a-edcc-257a-901e-b0709cf81053
* Content: [Building a complete .NET Core solution on macOS using Visual Studio for Mac - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution#creating-a-test-project)
* Content Source: [docs/core/tutorials/using-on-mac-vs-full-solution.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs-full-solution.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@AskYous I believe you need to open the context menu on the test and select Debug.

This is something we could note in this article though.

**Comment by AskYous** [comment]
Actually I found out the issue. It's that the sdk does not bring all the results. It only brings, perhaps, page 1 of the results. When I would edit the prompts of a qna set, it would push that qna set to the end of the list, and the SDK only returns page 1 of the list. I have also received the same results the [api console](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/knowledgebases_download/console).

In qnamaker.com, they add a query parameter to their URL: `?getFlattened=true`. That will return the entire knowledgebase, and not just page 1 of it.

**Comment by renanliberato** [comment]
Hey @Thraka , it seems that this issue is solved.  #16349 added some content, specially the last paragraph, about the debug feature.
https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution#see-also​​​​​​​

**Comment by Thraka** [comment]
Right you are. Thank you for noting that!
