### ISSUE TITLE
Publish the remaining language spec proposals for features released in C# 8.0

### ISSUE THREAD

**Issue by jcouv** [dotnet/docs#12772]
This is a follow-up on https://github.com/dotnet/docs/issues/10725

A few more features have been [implemented and shipped](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) in the C# 8.0 preview:
- default interface members (DIM)
- readonly members
- stackalloc in nested contexts
- unmanaged generic structs
- static local functions (with new shadowing rules)

Tagging @BillWagner 

Looking at the side-bar for the C# doc pages (such as https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/), I see a list of C# 8.0 proposals. We could add DIM and readonly members.

Those two proposals are now part of the csharp-8.0 folder (ie. their stable/final address): https://github.com/dotnet/csharplang/pull/2592

![image](https://user-images.githubusercontent.com/12466233/59304908-fad2cc00-8c4d-11e9-8453-989bb0181a77.png)

**Comment by BillWagner** [comment]
Thanks @jcouv I've added this to my task list.

What should we do with the spec-let for the [index and range changes](https://github.com/dotnet/csharplang/blob/master/proposals/index-range-changes.md)? Those are approved for C# 8, correct? 

It would read better if those changes were merged into the original spec, but I wouldn't want to do that until having two different docs isn't useful for the development efforts.

What are your thoughts?

**Comment by jcouv** [comment]
Thanks for calling out the Ranges doc. I'll move it to csharp-8.0 folder too.

**Comment by jcouv** [comment]
Here's the new link for Ranges changes doc: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/index-range-changes.md

**Comment by jcouv** [comment]
@agocke We have a proposal for Range and a proposal for Range Changes:
- https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.cs
- https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/index-range-changes.md

Feels like the latter should be merged into the former. Any objections?
