### ISSUE TITLE
Error in the description of the function REPLACE

### ISSUE THREAD

**Issue by ryanmajidi** [dotnet/docs#12773]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1600) by @GalicinD**

Error in the description of the function REPLACE.
now here https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/string-functions
is written:

Repeats a character expression for a specified number of times.

what corresponds to the REPLICATE function

**Comment by mairaw** [comment]
@stevestein please take a look at this ADO.NET issue.

**Comment by rpetrusha** [comment]
Thank you for reporting this issue, @GalicinD. We've opened #12799 to remove the duplication.
