### ISSUE TITLE
Method missing parameter

### ISSUE THREAD

**Issue by TravisStark** [dotnet/docs#12781]
The SaveModel() method in the tutorial is missing the parameter: DataViewSchema trainingDataViewSchema

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926fafd8-a07f-0857-f034-2a6ff15b4c87
* Version Independent ID: 43ca87d8-932f-4cd0-c446-b445557e3e7b
* Content: [Tutorial: Build a movie recommender - matrix factorization - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/movie-recommendation#feedback)
* Content Source: [docs/machine-learning/tutorials/movie-recommendation.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/movie-recommendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
I just merged the above PR with the fix. Should be live in a day or so. Thanks!
