### ISSUE TITLE
add an example of TestCaseFilter option

### ISSUE THREAD

**Issue by SychevIgor** [dotnet/docs#12788]
It's not clear how to filter tests based on Category for example
After 30 minutes recognize that this will work "--TestCaseFilter:TestCategory=Negative" even for NUnut, where instead of TestCategory used simple Category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c66d2f-86f4-6472-a4c8-30e4203a10de
* Version Independent ID: 224583f2-3ca3-5c97-4cd4-fcd3d6a64f91
* Content: [dotnet vstest command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-vstest.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-vstest.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
Thanks @SychevIgor . We should add links [here](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019) and [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md).
