### ISSUE TITLE
To improve performance ,disable concurrent GC

### ISSUE THREAD

**Issue by SilentCC** [dotnet/docs#12783]
In document [ fundamentals of garbage collection ](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals )

> To improve performance when several processes are running, disable concurrent garbage collection

I think concurrent GC is help to improve application performance.It reduce the pauses time when GC is running. Why disable concurrent garbage can improve performance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@rpetrusha  perhaps you can answer this question?

**Comment by rpetrusha** [comment]
@Maoni0, can you answer this question?

**Comment by Maoni0** [comment]
yeah, that should be changed. I actually wonder if we even want to keep this section anymore - this talks about the version of the concurrent GC before BGC and BGC has been in existence since .NET 4.0 so do we want to keep the doc for pre 4.0?

**Comment by rpetrusha** [comment]
I think we want to keep it for 3.5 and earlier, @Maoni0, but it clearly needs some fairly extensive revision. I'm about to start working on the other GC issues, so I'll do this at the same.
