### ISSUE TITLE
Complete official Docs

### ISSUE THREAD

**Issue by suloveoun** [dotnet/docs#12784]
I am new to learn C# and it's better to prepare the complete in one place to learn C# language. The complete and in once place documents can make me clear how to learn C# and easy to understand then a messy as professional looking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e4425-16b0-abfd-1e5a-927f07a8af69
* Version Independent ID: 040f0373-5f32-5132-2e26-adf03e4d6100
* Content: [Introduction to C# - interactive tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@suloveoun Thanks for the feedback. We agree, and we'll be continuously adding more learning materials here.

I'm going to close this. I agree with your feedback, and we'll keep adding content, but this issue doesn't represent a task-level work item.
