### ISSUE TITLE
the use of SendKeys.Send() with international multi keyboard scenario?

### ISSUE THREAD

**Issue by EKanadily** [dotnet/docs#12792]
"If your application is intended for international use with a variety of keyboards, the use of SendKeys.Send could yield unpredictable results and should be avoided."

so what should be used instead in this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b802e934-d9db-8920-edd1-f8128929cb9b
* Version Independent ID: ea6a2d6c-d97e-d406-e1b2-409d3eae5ba8
* Content: [How to: Simulate Mouse and Keyboard Events in Code](https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code)
* Content Source: [docs/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hi. I would guess that SendInput would be a choice. But I don't know. I think it's hinting that the codes may be different between keyboard layouts, so unless you're detecting the layout and then using SendKeys, you may have predictable results.
