### ISSUE TITLE
What about data store redundancy?

### ISSUE THREAD

**Issue by lukos** [dotnet/docs#12793]
It might be mentioned elsewhere but one of the challenges is that if we have e.g. 5 instances of a service, presumably they all share the same database but is that always the case? Is it simply a case of having a resilient engine like SQL Server Failover or do we also need to consider how each instance might conflict with another if both are attempting to modify the same data at the same time?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19862882-c106-afa7-660e-ead3b5dd880a
* Version Independent ID: fea4a2d6-8aa5-a400-4261-6098e76d362b
* Content: [Challenges and solutions for distributed data management](https://docs.microsoft.com/en-gb/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mikhail-putilov** [comment]
My opinion:

I would say, it is a database which must ensure data integrity and it is up to the developer to decide what to do if the database throws an exception. Must be evaluated case by case.

Prior databases people used plain files on a filesystem which wasn't secure enough. As far as I remember, Splunk doesn't use a database, they decided to write everything to a plain file.

**Comment by mvelosop** [comment]
Hi @lukos, thanks for your feedback, that's an interesting question!

In general, I prefer to have a single shared database. Specially if there's a chance that two microservices might conflict updating the same (logical) record in different DBs.

I general current databases scale well enough as to handle **very** large loads without problems, and you might consider some form of sharding, say by country, if there are really large volumes involved.

I'd try to avoid, as much as possible, an scenario with separate databases that can be updated from different sources and then have to be synchronized into a single logical set of data.

Although, perhaps, Event Sourcing might be a solution for that scenario.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
