### ISSUE TITLE
Docker image unavailable

### ISSUE THREAD

**Issue by Saintless** [dotnet/docs#12806]
**Issue description**

The "Create the Dockerfile" section refers to an image that is no longer available, resulting in the message, "no matching manifest for unknown in the manifest list entries" when following the steps given. The docs need to direct people to a resource where they can find a valid image to use, when the one in the example becomes outdated, or at least include information on what that message means.

**Comment by mairaw** [comment]
Are you referring to the following topic: https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?

**Comment by mairaw** [comment]
Closing the issue due to the lack of response. Please get back to us if you can confirm where you're seeing the issue @Saintless.
