### ISSUE TITLE
Text after example in Remarks section

### ISSUE THREAD

**Issue by geoff-m** [dotnet/docs#12809]
I don't understand how the part beginning "Virtual properties behave like abstract methods..." and ending with "...uses the override modifier" is true or relevant. In what way does a virtual property "behave" like an abstract method, or resemble it at all for that matter? If there is any, this page does not positively state it. Is this an error where a comparison between virtual properties and _virtual_ methods was instead intended? Whatever the intent, this first sentence is not clear, nor is it made clear by the bullet points that follow it, discussed below:

Aside from the basic and inherent differences between properties and methods, what reason is there to single out properties when discussing `virtual` and `override`? Certainly not what the two bullet points say, that `static` and `virtual` can't be mixed on properties (because this applies also to methods), and not that `override` can be used to override virtual inherited properties (because this also applies equally to methods).

If I am correct that the meaning of `virtual` does not change depending on whether it's applied to a property or to a method, then this little section has no place in this page. Any real inherent differences between properties and methods should be dealt with elsewhere, like on the page that defines what a property is.

If I am missing a subtlety and `virtual` really does mean something different for properties (that cannot be inferred from other knowledge about properties and methods), then this should be stated constructively and things which are the same (such as the prohibition of combining `static` and `virtual`) should not be presented as differences, or at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89022fe7-b2e3-5fb5-4930-d6bc5284081a
* Version Independent ID: 6a4f3ec1-e2eb-e046-d840-1c442276b3fb
* Content: [virtual - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual)
* Content Source: [docs/csharp/language-reference/keywords/virtual.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/virtual.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @geoff-m That section is confusing.  

The preceding sections should clarify that the behavior of `virtual` and the syntax rules are identical for methods, properties, indexers, and events. 

I'll add this to our backlog.

**Comment by BillWagner** [comment]
This was fixed in #15188
