### ISSUE TITLE
Timeouts seem not to be used on server side

### ISSUE THREAD

**Issue by pappasa** [dotnet/docs#12818]
The timeout values on the server side seem not to do anything. I host a WCF Service on IIS and have the following binding:

    &lt;bindings&gt;
      &lt;wsHttpBinding&gt;
        &lt;binding name="transactionalBinding" transactionFlow="true" sendTimeout="00:00:01" receiveTimeout="00:00:01" openTimeout="00:00:01" closeTimeout="00:00:01"&gt;
          &lt;security mode="Transport"&gt;
            &lt;transport clientCredentialType="None" proxyCredentialType="None" realm=""/&gt;
          &lt;/security&gt;
        &lt;/binding&gt;
      &lt;/wsHttpBinding&gt;
    &lt;/bindings&gt;

In my service method I sleep for 10 seconds. I do not get a timeout exception when calling my service method from a client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aefcf53-3c9e-b92c-2415-6be6777718ae
* Version Independent ID: 4c953f5d-43eb-6710-f7b4-4b437f94a05e
* Content: [Configuring Timeout Values on a Binding](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-timeout-values-on-a-binding)
* Content Source: [docs/framework/wcf/feature-details/configuring-timeout-values-on-a-binding.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/configuring-timeout-values-on-a-binding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by YonglianQian** [comment]
Please help, I encounter a similar issue, and the Timeout property would not work over https.

**Comment by Thraka** [comment]
@HongGit Can your team look at this issue please? Thanks
