### ISSUE TITLE
Enable https configuration is not clear

### ISSUE THREAD

**Issue by jaivsa** [dotnet/docs#12812]
Code between http and https is duplicated. It doesn't undestand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6133901-f087-25a1-77e6-ab37e2d1bcf6
* Version Independent ID: dcf239d3-4a85-00ed-b8ad-8f9a8e8ac983
* Content: [Configuring WCF Services in Code](https://docs.microsoft.com/en-us/dotnet/framework/wcf/configuring-wcf-services-in-code#feedback)
* Content Source: [docs/framework/wcf/configuring-wcf-services-in-code.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/configuring-wcf-services-in-code.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by gewarren** [comment]
@jaivsa Thanks for pointing this out. Fix is in progress.
