### ISSUE TITLE
Examples Do Not Provide Guidance on Chaining Successive/Sequential Children

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/docs#12815]
There seems to be missing example on how to chain successive child tasks.

If I understand correctly, the example given for adding tasks to a `List&lt;Task&gt;` and then calling `Task.WhenAll` will all execute in parallel.  

Consider the scenario where the developer would like to build 10 tasks and have each child task increment the current state by 1, awaiting the result to get the number 10 through the use of `ContinueWith`.

Thank you for any consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be073b14-6d0b-60be-7dff-4674bcb6c674
* Version Independent ID: a5fa3e78-73de-3360-1253-00545a2b4ef2
* Content: [Chaining Tasks by Using Continuation Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks#feedback)
* Content Source: [docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@Mike-EEE Apologies for late response to this.  Do you still need the successive tasks example or did you find it somewhere else?

**Comment by Mike-EEE** [comment]
Hi @tdykstra it's not me specifically who needs it but anyone wanting to do it via utilizing your documentation, correct? :)

**Comment by tdykstra** [comment]
@Mike-EEE We have limited resources and we have to prioritize our efforts in part on the basis of how common a given scenario is. Yours is the only question like this we've seen on this article, so if you have found your answer we're less likely to prioritize adding an additional scenario to the doc unless others ask the same question. That said, if you have your answer and would like to submit a pull request to add it to the doc, we'd be happy to work with you to validate it and get it published.

**Comment by Mike-EEE** [comment]
No one is using it because it's not known and documented?  Sounds like the crux of documentation to me, @tdykstra. 😆

**Comment by brunoalreis** [comment]
I also was looking for how to chain successive child tasks, and did not found.
