### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/docs#12817]
There is a formatting issue in the document [Graphics Paths in GDI+](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/graphics-paths-in-gdi).

```csharp
         Point[] myPointArray = {
    new Point(5, 30), 
    new Point(20, 40), 
    new Point(50, 30)};
```

Should be:

```csharp
     Point[] myPointArray = {
             new Point(5, 30), 
             new Point(20, 40), 
             new Point(50, 30)};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb917e6-c7e1-8094-6deb-355b69cbb9e3
* Version Independent ID: 404a6256-abc2-39f0-d572-1398c6af5fab
* Content: [Graphics Paths in GDI+](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/graphics-paths-in-gdi)
* Content Source: [docs/framework/winforms/advanced/graphics-paths-in-gdi.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/graphics-paths-in-gdi.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
