### ISSUE TITLE
Async programming recommendations are out of date

### ISSUE THREAD

**Issue by MarkCBB** [dotnet/docs#12823]
Looks like some recommendations for asynchronous programming are out of date, considering that this pattern is no longer the most recommended. I would suggest a review of this page.

In the page [Task-based asynchronous pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) you can find this: "(…) TAP is the recommended asynchronous design pattern for new development.(…)" but in this article:

•	"(…)In general, you should expose asynchronous features using the Event-based Asynchronous Pattern whenever possible.(…) "
•	"Use the event-based pattern as the default API to expose asynchronous behavior for your class."

Apart from this, the documentation/guide is really good and complete in contents ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd0266d-1086-d739-c153-08e527c6c790
* Version Independent ID: 8053b504-99d6-4851-4b46-371bf15eb1ab
* Content: [Deciding When to Implement the Event-based Asynchronous Pattern](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/deciding-when-to-implement-the-event-based-asynchronous-pattern#feedback)
* Content Source: [docs/standard/asynchronous-programming-patterns/deciding-when-to-implement-the-event-based-asynchronous-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/deciding-when-to-implement-the-event-based-asynchronous-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. I'm going to edit your title to be a bit more clearer as to the issue.

Thanks again!
