### ISSUE TITLE
The compiler isn't required to define a static constructor.

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#12827]
In the section on static constructors, this sentence is misleading:

&gt; If you don't provide a static constructor to initialize static fields, the C# compiler will supply a default static constructor that initializes static fields to their default value as listed in the Default Values Table.

The C# spec on [default values](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/variables#default-values) declares that the GC or runtime may be responsible for initializing fields (static or instance) to their default value. A compiler generated static constructor is not required.

The document on [type initialization exceptions](https://docs.microsoft.com/en-us/dotnet/api/system.typeinitializationexception?view=netframework-4.8#static-constructors-and-the-typeinitializationexception) should have a similar update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754eaea9-3482-4a69-5b65-ebe4a5065597
* Version Independent ID: 7f3cd611-9d80-4523-6ba5-17e1e9ab5c67
* Content: [Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors#static-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/constructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by EugeneKramer** [comment]
Thanks for [following through](https://github.com/dotnet/docs/pull/12733#discussion_r292499553) with the issue. A few other articles with similar phrasing:

[CA1810: Initialize reference type static fields inline](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1810-initialize-reference-type-static-fields-inline?view=vs-2019)
>When all static data is initialized inline and an explicit static constructor is not declared, Microsoft intermediate language (MSIL) compilers add the beforefieldinit flag and an implicit static constructor, which initializes the static data, to the MSIL type definition. 

[CA2207: Initialize value type static fields inline](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2207-initialize-value-type-static-fields-inline?view=vs-2019)
>If all static data is initialized inline and no explicit static constructor is declared, the C# and Visual Basic compilers add the beforefieldinit flag to the MSIL class definition. The compilers also add a private static constructor that contains the static initialization code. This private static constructor is guaranteed to run before any static fields of the type are accessed.
