### ISSUE TITLE
Incorrect signature for SaveModel method

### ISSUE THREAD

**Issue by cynicl12000** [dotnet/docs#12824]
As this tutorial is, the SaveModel method will not build & will report an error because it is missing an argument for trainingDataViewSchema.  The signature should be:
public static void SaveModel(MLContext mlContext, DataViewSchema trainingDataViewSchema, ITransformer model)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0888bc80-798f-ebdd-459a-7543be1efdad
* Version Independent ID: c24ded82-d56c-e8c7-fd6a-e39929227177
* Content: [Tutorial: Build a movie recommender - matrix factorization - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/movie-recommendation#feedback)
* Content Source: [docs/machine-learning/tutorials/movie-recommendation.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/movie-recommendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @cynicl12000! I've added this to the backlog and will get it resolved soon.

**Comment by JRAlexander** [comment]
I just merged the above PR with the fix. Should be live in a day or so. Thanks!
