### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/docs#12831]
In the document [How to: Create Thumbnail Images](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-create-thumbnail-images), the code is not aligned to the left.

    public bool ThumbnailCallback() {
            return true;
        }
   
        private void GetThumbnail(PaintEventArgs e)
        {

            // code omitted
        }

Should be,

    public bool ThumbnailCallback()
    {
        return true;
    }

    private void GetThumbnail(PaintEventArgs e)
    {
        // code omitted
    }

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38560ee-b36f-3f2a-6bfe-bf5470343119
* Version Independent ID: 837a9fd3-1cfe-1231-8b2b-d3256f9932d2
* Content: [How to: Create Thumbnail Images](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-create-thumbnail-images)
* Content Source: [docs/framework/winforms/advanced/how-to-create-thumbnail-images.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-create-thumbnail-images.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Moving this to our backlog and our community contribution project. The sample can be found here:
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Winforms/System.Drawing.WorkingWithImages/CS/Class1.cs#L188
