### ISSUE TITLE
TOC unusable in deeply nested articles

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1283]
Some of the recently imported articles are nested very deeply in the TOC structure, which makes the TOC unusable for them.

For example, this happens with the article [How to: Generate XML from CSV Files (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/articles/visual-basic/programming-guide/concepts/linq/how-to-generate-xml-from-csv-files):

![](http://imgur.com/6JhPNAz.png)

The article is in the TOC structure like this:

* Visual Basic Guide
* Programming Guide
* Programming Concepts
* Language-Integrated Query (LINQ)
* LINQ to XML
* Programming Guide (LINQ to XML)
* Querying XML Trees
* Projections and Transformations (LINQ to XML)
* How to: Generate XML from CSV Files (Visual Basic)

**Comment by mairaw** [comment]
I agree with you @svick. We haven't had time to review the TOC during the migration. @BillWagner, @stevehoag is that something you guys want to split between C# and VB and figure out what's best for those areas? I migrated the TOC as-is from MSDN.

**Comment by stevehoag** [comment]
Yes, thanks for pointing this out @svick . Looks like we need to flatten the TOC - what is the optimum number of levels to provide a good experience? We should set a standard and add it to the contributing guide.

**Comment by BillWagner** [comment]
Yes, this needs to change.

I can take on the C# portion.

**Comment by stevehoag** [comment]
And I'll take on VB.

**Comment by stevehoag** [comment]
Have we decided on a standard for number of TOC levels?

**Comment by BillWagner** [comment]
@stevehoag I don't think so. I proposed 3 levels which is clearly not sufficient. 6 (which we have now in some places) is too deep.

**Comment by cartermp** [comment]
The F# content is nested 3 deep at most, and it's pretty workable.  Maybe it's worth trying to get the language references of C# and VB flattened?  Since they're the worst offenders in this case, flattening them similar to how F# does it might be worthwhile.

**Comment by BillWagner** [comment]
I'd like to get the levels to 3, for many good reasons. We're at 6 levels with C# after the migration, so that's a lot of flattening. 

Because topics that aren't in the TOC are excluded from PDF download, I'd like to keep as many topics in the TOC as possible.

**Comment by BillWagner** [comment]
See PR #1318 for the C# changes.

**Comment by stevehoag** [comment]
Fixed all except language reference in #1348

**Comment by mairaw** [comment]
@stevehoag I checked the link that @svick pointed out in the issue above on staging and that topic has no TOC now. Can you check?
https://review.docs.microsoft.com/en-us/dotnet/articles/visual-basic/programming-guide/concepts/linq/how-to-generate-xml-from-csv-files?branch=master

**Comment by mairaw** [comment]
Submitted #1565 with some fixes to the TOC for that topic to see if that addresses the issue of that not being hooked up to the TOC anymore

**Comment by BillWagner** [comment]
Closed in #1318 and #1348 and #1565
