### ISSUE TITLE
Language Extensibility

### ISSUE THREAD

**Issue by solarkraft** [dotnet/docs#12830]
The .NET Compiler Platform is often listed as only supporting C# and VB. That this list includes F# makes me hopeful about extensibility, but I can't find information about it anywhere. 
Would it be possible to extend the .NET Compiler Platform (the analyzer part, anyway) with XAML support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6d898b-6040-87f7-92d3-40c959663e04
* Version Independent ID: 4bcbde71-e9ad-176e-9fa0-fd571274ae99
* Content: [LanguageNames Class (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.languagenames?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/LanguageNames.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/LanguageNames.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
You should ask the roslyn team https://github.com/dotnet/roslyn

Cheers!
