### ISSUE TITLE
Serialization (C#) - Add security considerations

### ISSUE THREAD

**Issue by EugeneKramer** [dotnet/docs#12853]
The _Serialization (C#)_ topic does not mention any security considerations, though serialization/deserialization are common attack vectors.

The topic is covered in part elsewhere:
* [Security Considerations for Data](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/security-considerations-for-data)
* [CA2300: Do not use insecure deserializer BinaryFormatter](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2300-do-not-use-insecure-deserializer-binaryformatter?view=vs-2019)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd80e70-d456-580a-86c0-451f933cc066
* Version Independent ID: 53894d4f-36fd-9b68-99fe-cfdbb7759beb
* Content: [Serialization (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/serialization/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is a good point @EugeneKramer 

Ping @blowdart to suggest a fix.

**Comment by blowdart** [comment]
@GrabYourPitchforks How would you address this? List all the unsafe ones? This isn't just for Core, it's a general serialization doc.

**Comment by BillWagner** [comment]
ping @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
I'd probably outline it as such:

 * How to craft types that are safe to receive deserialized data
 * A list of known-good deserializers and their known-good settings
 * Common pitfalls and anti-patterns when dealing with untrusted data in general

There is an absolutely _enormous_ amount that can be written about this. Hundreds and hundreds of pages worth of information. I don't know what scope anybody is looking for in such a document, so the outline above is just a first stab. And even of these three bullets above, all three are likely to be highly politically charged.

**Comment by BillWagner** [comment]
Thanks @GrabYourPitchforks 

I think for this issue, the right answer is to give an overview, and make developers aware of the issues. Then I think providing links to other industry resources where they can read more would be wise. 

As it's a very complex topic, complete coverage is outside of scope.

**Comment by irsdl** [comment]
I think deserializing untrusted data in general is problematic as we have seen several examples in ysoserial.net project and its linked references: https://github.com/pwntester/ysoserial.net/

It is possible to use special settings to make a safe deserialization process completely unsafe (e.g. when user can control the type in DataContract).

This article also lack basic information about other aspects of serialization such as type converters or JSON serialization which is similar to XML.

**Comment by EugeneKramer** [comment]
@GrabYourPitchforks I agree with your outline for this issue. Just looking to make devs more security conscious of common attack vectors when perusing the docs. 

A definitive, in-depth guide would be a separate project.

**Comment by tdykstra** [comment]
@GrabYourPitchforks Would a link to your new [binary serialization guidance](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide) doc address the need identified in this issue?
