### ISSUE TITLE
Unmanaged API reference - code blocks lack language identifier (cpp)

### ISSUE THREAD

**Issue by EugeneKramer** [dotnet/docs#12857]
Almost all code blocks in the unmanaged API reference lack a language identifier (and have no syntax highlighting). They should all be marked as `cpp`.

(Would it be worthwhile to submit a PR on this? This can be resolved with a regex replace.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26be196d-e1a9-0589-e39a-271478e66b8a
* Version Independent ID: 8d532104-dca0-f853-ad90-4be287ab567a
* Content: [Unmanaged API Reference](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/#feedback)
* Content Source: [docs/framework/unmanaged-api/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hi, thanks for opening this issue. I think it would be worth fixing via a PR.
