### ISSUE TITLE
Incomprehensible translation

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12861]
@sokrata commented on [Sat Jun 15 2019](https://github.com/dotnet/docs.ru-ru/issues/205)

The translation does not make it clear what the numbers are at the beginning of the line:
It has been shown that it has been the Font object.
There must be something like this:
The values returned by these methods are given in units of the font, so they do not depend on the size and units of measurement of a particular Font object.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: e3f6c7d6-a5a5-0cfa-45ed-23e99e236b6e
* Version Independent ID: cc28c628-46d6-520a-d5e5-c47682c59bc6
* Content: [Практическое руководство. Получение метрик шрифтов](https://docs.microsoft.com/ru-ru/dotnet/framework/winforms/advanced/how-to-obtain-font-metrics#feedback)
* Content Source: [docs/framework/winforms/advanced/how-to-obtain-font-metrics.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/winforms/advanced/how-to-obtain-font-metrics.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because even the contributor says it's a translation issue, they are suggesting changes in the original documentation

**Comment by Thraka** [comment]
@CeciAc What do we do about this kind of issue? I can't figure out what the user is specifically talking about. The translation is going from `article english -> article russian -> github issue russian -> github issue english` so it doesn't seem to make sense 😄

**Comment by CeciAc** [comment]
@Thraka zenhub copies the issue as is :)
the reported site would be https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-obtain-font-metrics

for what I could understand the user reports the numbers at the begining of the line are not explained.

**Comment by Thraka** [comment]
Yes, but because of the translation, I can't figure out what line that is 😄

**Comment by mairaw** [comment]
@Thraka that's our usual workflow for loc issues that are considered "source", but sometimes we challenge if it really is a source issue.

If I look at the original issue in Russian, it seems that line refers to this sentence:
The numbers returned by these methods are in font design units, so they are independent of the size and units of a particular font object.

Is it the suggestion that we change that sentence to the following @CeciAc?
The values returned by these methods are set in font units, so they don't depend on the size and measurements of a particular Font object.

**Comment by pkulikov** [comment]
@Thraka @mairaw 

> If I look at the original issue in Russian, it seems that line refers to this sentence:
> The numbers returned by these methods are in font design units, so they are independent of the size and units of a particular font object.

Yes, the original issue is about this line. However, it's about translation of the line. I've looked at the linked *.md* file in the `ru-ru` repo to check the translation. It's hard to make sense about. The author of the original issue says the same and *suggests* another translation of the line, which is much better. So, it seems to be a translation issue at first place.

As for the English text, I would only replace "numbers" with "values".

**Comment by mairaw** [comment]
I like your proposal @pkulikov! Would you like to make the PR? 

@CeciAc I think we should reopen the original issue and close this one.

**Comment by pkulikov** [comment]
> Would you like to make the PR?

@mairaw you meant this repo? Then: #12944

**Comment by mairaw** [comment]
Yes, that's what I meant. Thanks @pkulikov.

**Comment by CeciAc** [comment]
Thank you all, 
Closing this issue and following it up on the original post
