### ISSUE TITLE
Doesn't Show any Output

### ISSUE THREAD

**Issue by thearticles** [dotnet/docs#12865]
Its shows this:
C:\Program Files\dotnet\dotnet.exe (process 10752) exited with code -1073741795.
I am a beginner and came across a project that requires this functionality please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Retrain TensorFlow image classifier - transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks for the feedback, @thearticles! Can you give some more information? Thanks!

**Comment by thearticles** [comment]
I downloaded the project from git and tested it but its not giving any output
![image](https://user-images.githubusercontent.com/49184297/59852416-61fa2a00-938c-11e9-9db3-941ca09c1db6.png)

**Comment by natke** [comment]
@thearticles Did you download the project assets, as described in this step: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#prepare-your-data

**Comment by thearticles** [comment]
> @thearticles Did you download the project assets, as described in this step: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#prepare-your-data?

Yes did exactly like what was in the documentation

**Comment by natke** [comment]
@thearticles Can you please give us some information about your environment:
- O/S
- version of visual studio

I can see that you have an error code in your output. Is there any information in the visual studio output window that might be helpful?

**Comment by thearticles** [comment]
I run Visual Studio Community 2019 on a Windows 10 Pro PC
.NET Core 2.1
The output says "The program '[8340] dotnet.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'."

**Comment by natke** [comment]
@thearticles

Are you able to do a fresh clone of: https://github.com/dotnet/samples

Change directory into: machine-learning/tutorials/TransferLearningTF

Run the command `dotnet run`

And paste the output back in here. Thank you!

**Comment by thearticles** [comment]
F:\Code Examples\machine-learning\tutorials\TransferLearningTF>dotnet run

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
C:\Program Files\dotnet\sdk\2.1.800-preview-009696\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [F:\Code Examples\machine-learning\tutorials\TransferLearningTF\TransferLearningTF.csproj]

The build failed. Please fix the build errors and run again.

**Comment by natke** [comment]
It looks like you have the .NET 2.1 runtime installed. This tutorial targets 2.2. You can either update your .NET runtime to 2.2, or change the target framework setting in the  .csproj file to 2.1 (https://github.com/dotnet/samples/blob/master/machine-learning/tutorials/TransferLearningTF/TransferLearningTF.csproj#L5)

We will update the tutorial to clarify this. Thanks for bring it to our attention.
