### ISSUE TITLE
Missing Windows Versions in RID list

### ISSUE THREAD

**Issue by acornforth** [dotnet/docs#12864]
**Issue description**

List of RIDs for Windows incomplete.
I am building an app to deploy as SCD on Windows SBS 2011. It is not cleare from the docs which would be the correct RID to use. Can we please expand on this section to include the server versions that are currently missing?

Meanwhile I am assuming its the 2008R2 version and testing my deployment with this setting, please let me know if this is wrong, thanks :)

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET Core SDK (reflecting any global.json):
 Version:   2.1.700
 Commit:    c2ef055a0f

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.700/

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

.NET Core SDKs installed:
  1.0.0-preview2-003131 [/usr/share/dotnet/sdk]
  2.1.700 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

I looked on wikipedia for info about Windows SBS 2011 and it says it was based on 2008 R2 so I think you're right.

Thanks again!

**Comment by acornforth** [comment]
Hi @Thraka,
That's great news thanks, I would certainly consider making this fix myself and submitting a pull request, however I am only guessing as to which was the correct RID to use in my case. I was hoping someone with more expertise would clarify this for everyone, myself included :)

**Comment by Thraka** [comment]
@richlander Perhaps you can answer the question about RID for small business server?

**Comment by roothave** [comment]
That's great news thanks to ✔

**Comment by Thraka** [comment]
Pinged product group via email this time.

**Comment by richlander** [comment]
I would just use `win-x64`. I am unaware of any reason that anything different should be used. If you are using a 32-bit version of Windows, then `win-x86` is the right choice.

**Comment by Thraka** [comment]
Thanks! I'm closing this issue.
