### ISSUE TITLE
UWP?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#12869]
Are generic type arguments supported in UWP XAML as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65952d9f-041c-1f01-82ac-e9a9e99546c5
* Version Independent ID: 93abbfa7-14a3-2d2f-0a0c-6881b241225d
* Content: [Generics in XAML](https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/generics-in-xaml)
* Content Source: [docs/framework/xaml-services/generics-in-xaml.md](https://github.com/dotnet/docs/blob/master/docs/framework/xaml-services/generics-in-xaml.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Sorry, I don't know. You will probably have better luck asking that question in the UWP documentation repo: https://github.com/MicrosoftDocs/windows-uwp

**Comment by weitzhandler** [comment]
I've already found the answer and it's unfortunately negative.
Generic types aren't supported by UWP XAML.
