### ISSUE TITLE
No sample syntax?

### ISSUE THREAD

**Issue by JonPeltier** [dotnet/docs#12867]
How about a little bit of syntax here, so I don't have to follow another link to Dim:

Dim WithEvents app As Application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff11ae88-2fca-d4b4-71f8-8d0e36d40c40
* Version Independent ID: 86c34363-61f1-70c0-e8e7-02cec98629e3
* Content: [WithEvents (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/withevents#feedback)
* Content Source: [docs/visual-basic/language-reference/modifiers/withevents.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/withevents.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @JonPeltier. This was fixed by #12896.
