### ISSUE TITLE
Inspecting after a transform

### ISSUE THREAD

**Issue by famschopman** [dotnet/docs#12879]
How do I inspect a dataset after a transform which changes the schema?

var categoricalEstimator = lContext.Transforms.Categorical.OneHotEncoding("StringProperty");
ITransformer categoricalTransformer = categoricalEstimator.Fit(dataView);
IDataView transformedData = categoricalTransformer.Transform(dataView);

The following will fail because the schema has been updated with new vector types for the transformed dataset.

IEnumerable&lt;MyModel&gt; employeeDataEnumerable = mlContext.Data.CreateEnumerable&lt;MyModel&gt;(transformedData, reuseRowObject: true);
         
            
[AB#1530397](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1530397)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c846fa2-eecd-aab0-3ebf-a52f5c2db94e
* Version Independent ID: fd80b6d4-04c0-34a3-09b3-d2d773eef9a3
* Content: [Inspect intermediate data values during ML.NET processing - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/inspect-intermediate-data-ml-net#convert-idataview-to-ienumerable)
* Content Source: [docs/machine-learning/how-to-guides/inspect-intermediate-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/inspect-intermediate-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @famschopman ,

In order to inspect it, you can create a new class that defines your transformed schema. Using your example:

```csharp
// Original
public class MyModel
{
    public string StringProperty {get;set;}
}

// Transformed
public class MyTransformedModel
{
    public float StringProperty {get;set;}
}

var categoricalEstimator = lContext.Transforms.Categorical.OneHotEncoding("StringProperty");
ITransformer categoricalTransformer = categoricalEstimator.Fit(dataView);
IDataView transformedData = categoricalTransformer.Transform(dataView);

IEnumerable<MyTransformedModel> employeeDataEnumerable = mlContext.Data.CreateEnumerable<MyTransformedModel>(transformedData, reuseRowObject: true);
```

**Comment by JRAlexander** [comment]
Hi, @famschopman! This appears resolved so we're going to close. Please reopen or comment here if that isn't the case. Thanks!
