### ISSUE TITLE
How can I call C++ from C#?

### ISSUE THREAD

**Issue by turesnake** [dotnet/docs#12880]
Thanks for the tutorial.
But I need your help!
I have already embedded a CoreCLR in my native C++ app. 
Is there any way to call C++ function(unmanaged code) from C#(managed code) in this situation ? I mean, is there any way to let both sides communicate each other ?(not just call C# from C++)
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET Core runtime host - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#feedback)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by jkoritzinsky** [comment]
To call C++ from C# code, you should take a look at the [documentation on native interoperability](https://docs.microsoft.com/dotnet/standard/native-interop/). That should point you in the right direction for calling C++ from C# in common scenarios.

**Comment by johndaintree** [comment]
It looks like PInvoke can only be used to call code in a DLL. How does one (is it possible to) call a native function in the hosting native application (i.e EXE)?

**Comment by jkoritzinsky** [comment]
If you want to call a function in the hosting native application, there's a few ways to do it.

If you can get the handle for the EXE (through `GetModuleHandle(NULL)` on Windows or `dlopen(NULL)` on Linux/Mac) then you can use either [System.Runtime.InteropServices.NativeLibrary.SetDllImportResolver](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=netcore-3.0#System_Runtime_InteropServices_NativeLibrary_SetDllImportResolver_System_Reflection_Assembly_System_Runtime_InteropServices_DllImportResolver_) (preferable) or [System.Runtime.Loader.AssemblyLoadContext.ResolvingUnmanagedDll](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolvingunmanageddll?view=netcore-3.0) to map a DLL name of your choice to your hosting native EXE. For example, Mono uses the `"_Internal"` DLL name to map to the current host. Some other projects use `"*"` so as to not conflict with a possible DLL name.

Then you can use this DLL name in your P/Invokes as the name of the native library and the runtime will call your callback to resolve it.

**Comment by johndaintree** [comment]
Oh cool, thanks. I'll try that.
