### ISSUE TITLE
supernova

### ISSUE THREAD

**Issue by impbloody** [dotnet/docs#12903]
I just noticed this, on the first example, theres an empty class for supernova... nicely done guys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1766cac-6e34-c70b-0933-9d9def2344c4
* Version Independent ID: 38869398-bce4-0321-112d-4b44d558d7b1
* Content: [How to: safely cast by using pattern matching and the is and as operators](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators#feedback)
* Content Source: [docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think it's not a problem. The example just wants to show how to safely cast objects. so it doesn't matter what is inside the class for this example.

**Comment by Thraka** [comment]
Correct. It's used to create a new type that fails the testing done in `TestForMammals` and prints out a result indicating it.
