### ISSUE TITLE
Manifest not required?

### ISSUE THREAD

**Issue by frodofrod** [dotnet/docs#12922]
After much head-scratching I think I've discovered that with .Net 4.8 the WIndows 10 compatibility entry in the manifest is not only not required, it actually stops some dpi enhancements from working, eg checkbox sizing in a datagridview checkbox column, and checkboxes in a checked list control. I've removed the app.manifest from my solution and all now works fine -it  only needs the DPIAwareness key in the app.config to work fine on a high dpi display.

 I worked this out by reconstructing my very old VB app into a brand new solution only copying the app code itself, then adding in the various configuration files one at a time until it worked. Comparing with the original solution identified the manifest as the culprit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd152f5c-fb08-0400-5aa5-d46afe1d0473
* Version Independent ID: fe01fb3e-73bc-f90a-8862-719a440aa128
* Content: [High DPI support in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms#feedback)
* Content Source: [docs/framework/winforms/high-dpi-support-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/high-dpi-support-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@OliaG can you confirm this behavior?

**Comment by frodofrod** [comment]
[TestHighDpI.zip](https://github.com/dotnet/docs/files/3314111/TestHighDpI.zip)
I’ve done a bit more work to try and isolate the cause of this. For both my full app and a stripped down app built afresh, including the supportedOS tag for win10 causes small checkboxes, with it commented out they display correctly.

I’m using Win 10 1903, vs 2019 with .net 4.8 and VB, all fully updated. I think something changed with either 4.8 or win10 1903 updates recently applied, as it worked OK before then.

**Comment by OliaG** [comment]
app.manifest is not required. But as for different look of check boxes, @merriemcgaw, is this expected?
![image](https://user-images.githubusercontent.com/31997351/59953775-798ded00-9436-11e9-8858-ea6f85ad9c4e.png)

**Comment by merriemcgaw** [comment]
This seems odd to me. @dreddy-work can you take a look? It's almost like having the app manifest enabled has EnableVisualStyles disabled.

**Comment by frodofrod** [comment]
I realise app.manifest is not required for a simple project - I only added it to the project because this page advised me to!

" In addition, to configure high DPI support in your Windows Forms application, you must do the following:
Declare compatibility with Windows 10.
To do this, add the following to your manifest file:

<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
    
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
  </application>
</compatibility>"

Also it did work until recently, either .net4.8 or Win10 1903 broke it I think. Tried changing back to4.7.2 but the issue is still there. I'm not going to try and downgrade Win10 though!

In addition, to configure high DPI support in your Windows Forms application, you must do the following:
Declare compatibility with Windows 10.
To do this, add the following to your manifest file:
XML

Copy
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
    
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
  </application>
</compatibility>

**Comment by merriemcgaw** [comment]
Interesting. We fixed an issue a few months ago around EnableVisualStyles because Windows changed something underneath us and caused a problem. With 4.7.2 still having the problem it does seem like Windows broke it. @dreddy-work your fix wouldn't be on the latest OS until the servicing update goes out, right? Once it does the strange looking controls should be fixed. But not needing the OS compatibility setting is new to me. @Tanya-Solyanik any thoughts?

**Comment by dreddy-work** [comment]
-	I do not see that issue on my machine. I might have the latest runtime.
-	User can set DPiawareness either through app.manifest or app.config.
o	If they set it via app.manifest, they get windows high dpi improvements( if any) but may not get winforms high dpi improvements.
o	If they set it in app.config, they get winforms high dpi improvements along with windows( if any).
o	In both the cases, app need to target .NET 4.8 or User need to explicitly enable improvements via app.config flags.
-	Regarding windows 10 flag, I think we need it for PermonintorV2 (PMV) mode. Without it, we do not get PMV messages.

**Comment by dreddy-work** [comment]
Looks like this issue is specific to VB and only regressed in .NET 4.8. We need to take a look

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you help @dreddy-work investigate perhaps?

**Comment by mairaw** [comment]
Pinging @KlausLoeffelmann

**Comment by KlausLoeffelmann** [comment]
Thanks for the reminder. Taking a look over the weekend!

**Comment by mairaw** [comment]
Monday is fine too 😉

**Comment by Thraka** [comment]
Sent email

**Comment by KlausLoeffelmann** [comment]
All: I am sorry for the long delay. I am afraid, this need a bit more time to investigate, and my plan is to get an answer by the end of the month.

**Comment by Tanya-Solyanik** [comment]
@frodofrod - I suspect that when you remove manifest, your application is actually running as an unaware one. Unaware applications don't have DPI scaling issues.

**Comment by mairaw** [comment]
@KlausLoeffelmann any updates to this?

**Comment by merriemcgaw** [comment]
@Vino-Wang when you have some time can you check how this behaves now in 4.8 and 4.7.2? @dreddy-work  or @KlausLoeffelmann can answer any questions you have.
