### ISSUE TITLE
Abridged Reference: Operators / operator overloading

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#12924]
There are a number of articles in the current doc set that can be consolidated in the two following articles.

**Operator overloading**

This article should introduce the `operator` keyword and list the overloadable operators. The following articles are to be substituted with the new article:

- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/operator
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators

**User-defined conversion operators**

This article should show how to define custom conversion operators with the `implicit` and `explicit` keywords. The following articles (they share a lot now) are to be substituted with the new article:

- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/explicit
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/conversion-operators
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/using-conversion-operators
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-implement-user-defined-conversions-between-structs

@BillWagner what do you think? If that sounds like a fine plan, please assign this issue to me.

**Comment by BillWagner** [comment]
@pkulikov This is a great plan.  Thank you.

I've assigned it to you, and added it to our next sprint. (I added myself as an additional assignee so this stays in my daily list to 👀 at.
