### ISSUE TITLE
Provide examples as to why enums are a code smell that's not behind a paywall. 

### ISSUE THREAD

**Issue by pdylanross** [dotnet/docs#12933]
The page linked to at the top that claims that enums are a code smell simply links to a pluralsight course that supposedly justifies calling enums a code smell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by babin93** [comment]
This issue seems to be fixed. The link now targets https://deviq.com/code-smells/ . I think this issue could be closed.

**Comment by mvelosop** [comment]
Thanks @babin93.

Closing now.
