### ISSUE TITLE
TOC filter does not seem to work

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1294]
When I type something into the TOC filter, the result is always "No results", it seems it does not work at all.

![](http://imgur.com/sxtOLTX.png)

I have tried it on Firefox 50 and Edge 38.

**Comment by mairaw** [comment]
Yep, I can repro that. It used to work. @dend @DuncanmaMSFT who should look at this issue?

**Comment by mairaw** [comment]
This is now working for me again. Is it working for you again @svick ?

**Comment by svick** [comment]
Yeah, it is. Closing.
