### ISSUE TITLE
What is the counter to track the queued requests to handle 

### ISSUE THREAD

**Issue by saranyakavins** [dotnet/docs#12947]
In the Throttle concurrent requests per session, please specify the exact counter to track the queued request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6244a293-43f8-82ba-b7c9-aa85af3a4b15
* Version Independent ID: 95061aef-1917-4a1e-06c4-3d6b2d84dfd2
* Content: [Retargeting Changes for Migration from .NET Framework 4.5.2 to 4.7](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.2-4.7#feedback)
* Content Source: [docs/framework/migration-guide/retargeting/4.5.2-4.7.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/retargeting/4.5.2-4.7.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **ronpet**

**Comment by gewarren** [comment]
@scottaddie Would the counter name be `RequestQueueLimitPerSession`?

Breaking change in question: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.2-4.7#throttle-concurrent-requests-per-session
