### ISSUE TITLE
InBetween?

### ISSUE THREAD

**Issue by Mike-EEE** [dotnet/docs#12955]
This looks great, but finding trouble with how to use these ranges with basic methods like InBetween, etc.  I thought I saw these in a demo at one point but do not see any methods to do so now when examining this in Visual Studio.  Any guidance/assistance here would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The full list of methods for the `System.Range` type is in the [.NET Core API reference](https://docs.microsoft.com/en-us/dotnet/api/system.range?view=netcore-3.0).  

The methods you ask for aren’t part of the public API. You can open an issue on the corefx repo to consider adding new APIs.
