### ISSUE TITLE
Exception Filters Finally (C#) - Add security considerations

### ISSUE THREAD

**Issue by EugeneKramer** [dotnet/docs#12961]
Security considerations regarding filters should be documented. C#6 exception filters run before inner finally blocks, which can [create a security loophole](https://stackoverflow.com/a/39515027/389823) when running untrusted code.

Jon Skeet writes in _C# in Depth_ (p. 310)
> All of this means you shouldn't use `finally` for anything security sensitive.

It may be worth noting in the reference and [Best practices for exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83aef5d8-e02b-6b66-c4d4-9b3f93fa61f4
* Version Independent ID: 7daa053d-18e9-040f-aa4d-26b30b2d81f5
* Content: [try-catch-finally - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch-finally)
* Content Source: [docs/csharp/language-reference/keywords/try-catch-finally.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-catch-finally.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Ping @blowdart 

Do we already have guidance written for this where we can refer readers?

**Comment by blowdart** [comment]
No.
