### ISSUE TITLE
Incorrect registry value that AppContext for Japanese era

### ISSUE THREAD

**Issue by Azulea** [dotnet/docs#12968]
Example:
HKEY_LOCAL_MACHINE\Software\Microsoft.NETFramework\AppContext
Switch.System.Globalization.FormatJapaneseFirstYearAsANumber
Value 1

This registry value is not effected. (tested on Windows 10 1809)
Correct value is "true".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6585f784-ab83-1a98-acc0-a25351702686
* Version Independent ID: 61afd4f7-9445-ef3e-3061-9b4dc71aae6e
* Content: [Working with calendars](https://docs.microsoft.com/en-us/dotnet/standard/datetime/working-with-calendars#feedback)
* Content Source: [docs/standard/datetime/working-with-calendars.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/working-with-calendars.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @Azulea. We've opened #13052 to address this issue.
