### ISSUE TITLE
Error in Step 6

### ISSUE THREAD

**Issue by SeanDevoy** [dotnet/docs#12969]
Step 6 says:  
Stream dataStream = request.GetRequestStream()   
which is the C# syntax.  In VB it is  
Dim dataStream As Stream = request.GetRequestStream()
HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a7ce223-b955-7f50-6b53-15585c68f02d
* Version Independent ID: 78e4d95a-3a97-ec74-ebf4-843bad4efa7a
* Content: [How to: Send data by using the WebRequest class](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-send-data-using-the-webrequest-class#feedback)
* Content Source: [docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by rpetrusha** [comment]
Thank you for noticing and reporting the copy-and-paste error. We've fixed it in #12981.
