### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by LambertWM** [dotnet/docs#12964]
I came here to find practical info about using the OpenFileDialog class, but 98% of the information here is irrelevant (and confusing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9db6b2-ee5e-dffb-94ea-3c56ed18e34e
* Version Independent ID: 9a19956f-7670-1e75-feb7-8a8b2e71c31e
* Content: [How to: Open files with the OpenFileDialog component](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component)
* Content Source: [docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello. Sorry for the delay in responding.

It's hard to understand what is missing without fully understanding your scenario. Can you elaborate on "practical info?"

Does the https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/openfiledialog-component-overview-windows-forms article help?
