### ISSUE TITLE
HostWithHostFxr sample is confusing to use from Visual Studio

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/docs#12974]
**Issue description**

Using the sample https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr, it builds following the `.md` file correctly, but trying to look at its code from Visual Studio is confusing.

The sample doesn't have a solution file and opening one of the `csproj` files is weird:
* One only sees the managed component
* The other sees both managed and native component but it wraps the native component in a managed project

We should add a description into the `.md` file how the projects work and what is the best way to look at the code of the sample (people tend to look for a simple way to open it in VS, maybe we should provide a solution file even though it's not a cross platform way).

/cc: @elinor-fung

**Comment by mairaw** [comment]
@elinor-fung can I assign this one to you?

**Comment by elinor-fung** [comment]
This experience was improved with #1095.
