### ISSUE TITLE
What are the differences between "dotnet *.dll" and hosting app in IIS?

### ISSUE THREAD

**Issue by changhuixu** [dotnet/docs#12970]
The command `dotnet *.dll` serves the application. I am not sure if it misses some features as compared to hosting application in IIS.
Can anyone please elaborate on the differences? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
For information about hosting in IIS, see the [ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy).
