### ISSUE TITLE
Example doesn't demonstrate the usefulness of creating an AppDomain

### ISSUE THREAD

**Issue by miss-programgamer** [dotnet/docs#12972]
The given example doesn't showcase a useful use case for creating an AppDomain. It merely demonstrates that they can have different names, which hardly seems informative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68373d20-e532-ffbc-ecd7-3aef579e6861
* Version Independent ID: ae5aeddc-80aa-490d-6130-b18eef17d413
* Content: [How to: Create an Application Domain](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-create-an-application-domain#feedback)
* Content Source: [docs/framework/app-domains/how-to-create-an-application-domain.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/how-to-create-an-application-domain.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
I think this section is really a progressive how-to area. The next article in the TOC keeps doing more. However, the whole area is not presented as a tutorial series which is a bit confusing. I'll put this on the backlog for when we look into this area. But right now, we're not focusing on it.
