### ISSUE TITLE
useb parameter in Windows install script isn't documented

### ISSUE THREAD

**Issue by nschonni** [dotnet/docs#12994]
From https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1 it looks like it might be an undocumented form of "-UseBasicParsing`. It might be better to be explicit if that's the case

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-ca/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
I believe it is a PowerShell feature that you can shorten parameter names, as long as that shortening is still unique within that command. Though I couldn't find any official documentation about this.

**Comment by Thraka** [comment]
Correct, PowerShell will match a partial parameters as long as it can only resolve to a single parameter.
