### ISSUE TITLE
IEnumerable<T>

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/docs#13010]
Arrays do not implement IEnumerable&lt;T&gt; as can be seen via https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netcore-3.0 which is a real pain. They do implement IEnumerable via Array -&gt; IList -&gt; ICollection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d7544-6f92-5582-9d28-7160a5bc916a
* Version Independent ID: 7e3f884a-94b6-ea27-70ea-060fe51f51c2
* Content: [Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/index#feedback)
* Content Source: [docs/csharp/programming-guide/arrays/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/arrays/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello!

`Array` is an abstract base class, and as the base class for other arrays, it doesn't know the type being used. Hence, `IEnumerable<T>` doesn't need to be implemented on `Array` directly. When you create a typed array, such as `int[]`, they have the appropriate `IEnumerable<T>` interface implemented.

I'm going to close this issue. If your question is not answered, to leave a comment or reopen the issue. Thanks!

**Comment by davidhunter22** [comment]
The documentation for array states "Array types are reference types derived from the abstract base type Array. Since this type implements IEnumerable and IEnumerable<T>, you can use foreach iteration on all arrays in C#". The "Since this type" clearly refers to Array and states it implements IEnumerable<T> which is incorrect. You can use foreach on any derived type of Array because it does implement IEnumerable. 
All derived class may or may not implement IEnumerable<T> but that is a bit irrelevant. You can write code that takes an Array as an argument and based on the documentation expect it to implement IEnumerable<T> somehow.

**Comment by davidhunter22** [comment]
Actually I just had a thought about 2D arrays. I tried
```
            var a = new int[,] { };
            IEnumerable<int> x = a;
```
Which fails to compile. So your comment about derived classes implementing `IEnumerable<T>` seems to only apply to 1D array not multi dimensional arrays.
In general that brings up another issue with this page that it is not clear about what in Array works for 1D arrays versus multi dimensional arays.

**Comment by Thraka** [comment]
I can let @BillWagner decide what to do with this issue, but I don't think it's that important to document here. It is covered on the [remarks section of the Array API](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netcore-3.0#remarks) type. You can see an answer on stackoverflow about this specific question: https://stackoverflow.com/questions/2773740/why-do-arrays-in-net-only-implement-ienumerable-and-not-ienumerablet

It's something that happens at runtime automatically for you.

However, if you really do want this info explained or linked to, you can always work with @BillWagner 
 to submit an edit to the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub. 

We can reopen the bug.

**Comment by canton7** [comment]
Just a note that this [popped up on SO](https://stackoverflow.com/questions/66710635/is-the-c-sharp-programming-guide-right-on-pretending-that-arrays-implement-ienu?noredirect=1), with someone questioning the guide's accuracy, as it claimed that all arrays (even multi-dimensional ones) implement `IEnumerable<T>`.
