### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by jmsiyath** [dotnet/docs#13027]
Could you please explain with more sample codes like OnBuildTreeTopDown vs OnBuildTreeBottomUp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e843d09-52a6-777c-f57c-a89585aa954e
* Version Independent ID: 4ac53563-bbfb-1edc-ae56-2f7f4e8be00a
* Content: [Optimizing Performance: Layout and Design](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/optimizing-performance-layout-and-design#feedback)
* Content Source: [docs/framework/wpf/advanced/optimizing-performance-layout-and-design.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/optimizing-performance-layout-and-design.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello!

Thank you for the question. We're not going to update the documentation at this time. But this is referring to the order of adding children. The example demonstrated is how you should add children to a parent (when you're doing it programmatically of course), level by level starting at the highest parent. The opposite would be to start with the lowest child, create a parent, add the child to that parent, create another parent, add the previous parent to the new parent and repeat.
