### ISSUE TITLE
ASP.NET Core Web Api works locally but Fails VSBuild on Azure DevOps (ERROR NETSDK1061)

### ISSUE THREAD

**Issue by hiskensullivan** [dotnet/docs#13033]
In advance, I am new to aspnet core. 

I have an ASP.NET Core Web Api project that retrieves from my hosted mongodb that is then consumed by my React UI. Locally it works (albeit with several warnings) 

![image](https://user-images.githubusercontent.com/48420949/60156799-9c524400-9830-11e9-9db4-678beebff340.png)

but when I try to deploy it to my Azure DevOps Pipeline to get built, I get the following:

![image](https://user-images.githubusercontent.com/48420949/60156223-652f6300-982f-11e9-8750-52fd2100dfc2.png)

I have tried similar issues with the same NETSDK1061 error however it has lead me nowhere so I opened a new issue. My results of dotnet --info are as follows:

![image](https://user-images.githubusercontent.com/48420949/60156373-bdfefb80-982f-11e9-8e3b-9a2ad44f0b60.png)

I've already tried making changes to the targetframework (playing around with different versions of netcoreapp2.x), runtimeframeworkversion (tried 2.1.x and 2.2) and the targetlatestruntimepatch (both true and false), I've tried also clean restore publish and several other approaches. 

I'd appreciate whatever help I can get that isn't just a reference to another issue that doesn't really solve my problem.

**Comment by mairaw** [comment]
Hello @hiskensullivan! Thanks for creating an issue. Even though you have specifically asked us not to reference another issue and we try to answer all issues, this repo is not really for asking support or general .NET Core questions.

A few pointers that are related to your problem that could help you:
https://stackoverflow.com/questions/53720678/netsdk1061-the-project-was-restored-using-microsoft-netcore-app-version-1-0-0
https://github.com/dotnet/sdk/issues/2682

**Comment by hiskensullivan** [comment]
Hi @mairaw, thanks for getting back to me. Apologies, I didn't know you had to be a member to raise an issue. For anyone who might read this having a similar issue, I managed to get it built with a  repair of the .net framework and set the runtimeframeworkversion to <RuntimeFrameworkVersion>2.1.0</RuntimeFrameworkVersion> and ensured I had 2.2.104 SDK installed! 

Doesn't sound like a buggy or wonky at all, sorry for the general .NET Core question!

**Comment by mairaw** [comment]
No, you don't have to be a member at all! But unfortunately we have limited resources and can't help diagnose product issues. 

But I'm glad to heard you fixed your issue!
