### ISSUE TITLE
Make it so I can visually see examples. Not just ComboBox - but all of them.

### ISSUE THREAD

**Issue by jgfet** [dotnet/docs#13047]
See title...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528ddf4c-b257-050c-396b-074e2ff30954
* Version Independent ID: 264783aa-9520-4271-7d00-d85c6914680a
* Content: [ComboBox Control (Windows Forms)](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/combobox-control-windows-forms#feedback)
* Content Source: [docs/framework/winforms/controls/combobox-control-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/combobox-control-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for the suggestion; we're not currently updating this documentation with screenshots of types.
