### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by jwisener** [dotnet/docs#13056]
sample does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7b94e2-8239-bdc2-049b-fc69130f8889
* Version Independent ID: d02c6ff7-dc9a-d967-9b2c-02f9fcf44fca
* Content: [Shape of WordprocessingML Documents (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/shape-of-wordprocessingml-documents)
* Content Source: [docs/csharp/programming-guide/concepts/linq/shape-of-wordprocessingml-documents.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/shape-of-wordprocessingml-documents.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Can you give us more details here? What version, platform are you using? Which step in the tutorial?

**Comment by Thraka** [comment]
@jwisener Hello. As this has been a month without a response, I'm going to close this issue. Please feel free to reopen it when you have more information.

Cheers!
