### ISSUE TITLE
Why need such complex code instead of one line?

### ISSUE THREAD

**Issue by LeiYangGH** [dotnet/docs#13059]
myImage.Source = new BitmapImage(new Uri("smiley.png"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fdbaa6-085d-0162-2015-3661c60dd93b
* Version Independent ID: 399ebd64-229f-5684-4803-29de42008e80
* Content: [How to: Encode and Decode a PNG Image](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-png-image#feedback)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-png-image.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/how-to-encode-and-decode-a-png-image.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for the question. The point of the article is not to display the image, although it does show that, the point is to learn how to use the types related to decoding and encoding an image in PNG format.
