### ISSUE TITLE
Passing parameters...

### ISSUE THREAD

**Issue by jgfet** [dotnet/docs#13050]
It's all very well defining how to code this. But how the heck do I add parameters so that when I run code in IDE (VS2019), the launch process has the necessary arguments added. Need to reference this for IDE users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837b7255-3cfe-b480-ea07-298a24d96185
* Version Independent ID: 5645cc8e-aaee-25e3-b81a-afba7fd0fe9f
* Content: [Passing Parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-parameters#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/passing-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/passing-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@jgfet Thank you for filing this issue. I believe the C# programming guides focuses on the language instead of a specific IDE since there are three main IDEs available, Visual Studio, Visual Studio Code, and Visual Studio for Mac.

@BillWagner Should this be covered by the Visual Studio documentation? I'm shocked that I can't find it listed anywhere there. They really should have this covered and then we can link to it. Do you think we should file a doc request with them?

**Comment by pkulikov** [comment]
> Should this be covered by the Visual Studio documentation?

It's covered, but very silently here:
https://docs.microsoft.com/en-us/visualstudio/ide/reference/debug-page-project-designer?view=vs-2019#start-options

The .NET docs reference that page from this article (check the note at the bottom of the page):
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/command-line-arguments

**Comment by BillWagner** [comment]
cc @gewarren

**Comment by Thraka** [comment]
Indeed. I used both `arguments` and `parameters` in searching the vs docs and didn't see that page at all. It seems like it should be covered as part of the debugging conceptual topics instead of the UI reference.

**Comment by gewarren** [comment]
@Mikejo5000 Do you cover this anywhere in the debugger docs?

**Comment by BillWagner** [comment]
The content source should really be [this page](https://docs.microsoft.com/dotnet/csharp/programming-guide/main-and-command-args/command-line-arguments). The concern is about passing arguments to the main program.

That page should be updated with how to pass arguments using `dotnet run` for .NET Core. (You just add them after any options to `dotnet run`).

That page should also point to the relevant VS Code docs.

**Comment by gewarren** [comment]
> That page should also point to the relevant VS Code docs.
Do you mean Visual Studio docs?

**Comment by BillWagner** [comment]
@gewarren 

I meant both Visual Studio, and Visual Studio Code. Bonus points for Visual Studio for Mac, if that’s a different doc set. :)

**Comment by gewarren** [comment]
If this bug is reopened and fixed, we should include info about specifying debug arguments this way:

```
  static void Main(string[] args)
  {
#if DEBUG
    args = new[] { "--replace-redirects", "--lookback=90" };
#endif
    ...
  }
```

**Comment by sharwell** [comment]
Updating labels to match a resolving response in https://github.com/dotnet/docs/issues/13050#issuecomment-506038077
