### ISSUE TITLE
Is there a way to specify which nuget source to use?

### ISSUE THREAD

**Issue by minuz** [dotnet/docs#13066]
I've been reading the docs and I have an issue with the CLI that is: 

I'm trying to install a global tool using `dotnet tool install --g dotnet-outdated` and within my local nuget, I have a few nuget feed. Instead of trying to download from the `nuget.org` which is the default source, is trying to download from one of the private nuget feed. 

This private nuget feed only works within the company's network infrastructure and trying to download a tool that is completely unrelated to my workplace, it gets stuck on trying to download on the private feed instead of going to other sources. 

So the question is: Is there any way to specify which source to download it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#feedback)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your question @minuz. @KathleenDollard @livarcocc can you help with this question about dotnet tool install?

**Comment by KathleenDollard** [comment]
Adding @wli3

**Comment by wli3** [comment]
you could try one of
1. add `--ignore-failed-sources`, so even your private feed fails, it will continue to try other feed
2. create a new nuget.config in the directory you run the command (pwd directory). And specify the feed there
3. edit your global nuget config, to remove the private feed. Note, this will change all the feed configuration. Including your project's restore

%appdata%\NuGet\nuget.config on windows
 ~/.nuget/NuGet/NuGet.Config on mac

**Comment by minuz** [comment]
Thanks @wli3!! This is what I was looking!
