### ISSUE TITLE
`keywords` metadata item not created in migration

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1308]
# `keywords` metdata item not created in migration

## General
When VB and C# content was migrated to docs.microsoft.com, a `keywords` metadata field was not created. Since `keywords` is a field used by SEO, the result is that some VB and C# language topics do not surface even for very focused searches. For example, searching for "this keyword", 'this C#", or "this keyword C#" does not surface the `this keyword (C# reference)` topic.

## Issues with Existing Topics

There are several things we can do to address this issue:
- On a case by case basis, as we notice the problem, we can add the keywords field to a topic's metadata. (I'll open a PR for `this` and `base` now.)
- For language reference topics, create a script that looks at the language keyword and then programmatically adds a keywords metadata field along with some auto-generated keywords to the topic. For example, for `this`, the keywords might be " this C#", "this keyword C#", and "this (C# language reference)".
- Programmatically copy the keywords in the `helpviewer_keywords` metadata field to a new `keywords` field.
- Manually review and update sections of the documentation as time allows.

@mairaw @BillWagner

**Comment by mairaw** [comment]
Keywords is no longer needed. Only Bing used to use this information. SEO team is not even sure is still used, so their recommendation is to not worry about this one.
