### ISSUE TITLE
Add screen shots for how to install/ uninstall from VS

### ISSUE THREAD

**Issue by rustd** [dotnet/docs#13090]
Add screenshots of the steps listed.

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5692cfb5-52e1-b6b9-2b87-7ea0decc2882
* Version Independent ID: 2da762a6-5bc4-a8d1-afae-f1a8243eee33
* Content: [How to install Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-model-builder#feedback)
* Content Source: [docs/machine-learning/how-to-guides/install-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
@rustd Do you have a set of screenshots showcasing the expected functionality?
