### ISSUE TITLE
Retire topic: Packages, Metapackages and Frameworks

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1311]
Topic URL: https://docs.microsoft.com/en-us/dotnet/articles/core/packages

Comments on this topic indicate that people are confused and they don't understand the terminology used and the concepts introduced.

**Comment by DanielStolt** [comment]
Indeed. I think the main sources of confusion are:

- the meaning of the word "framework"
- the distinction between "framework" and "package based framework"
- above all, the apparent circular definition, how can a framework both *define* and *be defined by* the set of packages which target it

**Comment by majkinetor** [comment]
That topic needs **serious and complete** rewrite. It is the serious problem that the basics can't be outlined right.

**Comment by garfbradaz** [comment]
Agree wholeheartedly. We now have .NET Framework, .NET Core and now .NET Srandards. To make matters worse, we now can reference bits and pieces of these together. My head hurts reading the above link.

**Comment by AmirHasanzade** [comment]
The first time I read the article I was confused. But after reading docs for .NET standard (and the fact that it's just a definition of APIs and not an implementation) and article about deployment methods for .NET core I was able to understand the article.

Maybe it's better if some prerequisite material is defined at first. Or if a metaphor (like the LEGO metaphor in comments) is added to make it clearer.

**Comment by mairaw** [comment]
@tdykstra another one related to the terminology work

**Comment by DanielStolt** [comment]
@AmirHasanzade Metaphors rarely make technical concepts more understandable IMO, and the LEGO metaphor suggested by that comment is particularly vague and misaligned with what it tries to describe. Better IMO to explain the concepts in terms of what they really are, but clearly and exhaustively.

**Comment by IEvangelist** [comment]
Retire existing confusing doc. @tdykstra
