### ISSUE TITLE
Cannot run program "HelloSpark"

### ISSUE THREAD

**Issue by maggiepong** [dotnet/docs#13125]
I followed the instruction on the doc and tried submitting the HelloSpark dotnet core app.

btw, the doc says submit using Spark 2.4.   I read some doc that says I should use 2.3 and I installed spark-2.3.3-bin-hadoop2.7

I ran the following command in this directory and got error that it can't find HelloSpark.

PS C:\repos\HelloSpark\HelloSpark\bin\Debug\netcoreapp2.1> dir

    Directory: C:\repos\HelloSpark\HelloSpark\bin\Debug\netcoreapp2.1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/27/2019  12:50 PM           5909 HelloSpark.deps.json
-a----        6/27/2019  12:50 PM           4608 HelloSpark.dll
-a----        6/27/2019  12:50 PM            512 HelloSpark.pdb
-a----        6/27/2019  12:50 PM            236 HelloSpark.runtimeconfig.dev.json
-a----        6/27/2019  12:50 PM            154 HelloSpark.runtimeconfig.json
-a----         6/5/2019   4:18 PM         138846 microsoft-spark-2.3.x-0.3.0.jar
-a----         6/5/2019   4:18 PM         138868 microsoft-spark-2.4.x-0.3.0.jar
-a----         2/4/2019   7:48 AM             73 people.json

PS C:\repos\HelloSpark\HelloSpark\bin\Debug\netcoreapp2.1>spark-submit  --class org.apache.spark.deploy.DotnetRunner --master local microsoft-spark-2.3.x-0.3.0.jar  HelloSpark

2019-06-27 12:54:19 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-06-27 12:54:21 INFO  DotnetRunner:54 - Starting DotnetBackend with HelloSpark.
2019-06-27 12:54:24 INFO  DotnetRunner:54 - Port number used by DotnetBackend is 53580
2019-06-27 12:54:24 INFO  DotnetRunner:54 - Adding key=spark.jars and value=file:/C:/Users/mpong/repos/HelloSpark/HelloSpark/bin/Debug/netcoreapp2.1/microsoft-spark-2.3.x-0.3.0.jar to environment
2019-06-27 12:54:24 INFO  DotnetRunner:54 - Adding key=spark.app.name and value=org.apache.spark.deploy.DotnetRunner to environment
2019-06-27 12:54:24 INFO  DotnetRunner:54 - Adding key=spark.submit.deployMode and value=client to environment
2019-06-27 12:54:24 INFO  DotnetRunner:54 - Adding key=spark.master and value=local to environment
**2019-06-27 12:54:24 ERROR DotnetRunner:70 - Cannot run program "HelloSpark": CreateProcess error=2, The system cannot find the file specified
 [Ljava.lang.StackTraceElement;@7d898981**
2019-06-27 12:54:24 INFO  ShutdownHookManager:54 - Shutdown hook called

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started#feedback)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by maggiepong** [comment]
Found another doc that provides the correct command:

https://github.com/dotnet/spark/blob/master/docs/getting-started/windows-instructions.md

Which should  be

spark-submit --class org.apache.spark.deploy.DotnetRunner --master local microsoft-spark-2.3.x-0.3.0.jar dotnet HelloSpark.dll

**Comment by mamccrea** [comment]
Hi @maggiepong! Thank you for letting me know. I will update the doc.

**Comment by mamccrea** [comment]
@maggiepong - I've made changes to the article, so it'll be updated soon. You mentioned that you read to use Spark 2.3 instead of 2.4. Both are supported - did you have any issues with 2.4?

**Comment by maggiepong** [comment]
I didn't try spark 2.4.   I have 2.3 installed on my machine hence I use 2.3.  Thanks.

**Comment by mamccrea** [comment]
@maggiepong - I see. Thanks again!
