### ISSUE TITLE
.NET Core 3.0 IL Linker docs

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13147]
.NET Core 3.0 will include a new feature called an IL Linker.
This is intended as a high level task list for documenting that feature.

We need to document
  - [x] IL Linker key concepts.  What is it what does it do
  - [x] CLI options
  - [x] csproj setting.  What are they what do they do
  - [ ] Templates.  What's available.  What are they good for. Why are they preferred or not.
  - [ ] How to test to make sure IL Linked is functionally complete.
  - [ ] Relevant guidance
  - [ ] Gotchas
  - [ ] Debugging and resolving IL Linker failures
  - [x] Adding roots
  ~~- [ ] Where to provide feedback and request for features~~
  - [ ] Key links to articles and .NET Blog posts

/cc @sbomer

**Comment by sbomer** [comment]
Thanks for writing this up @sdmaclea. https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking has the high-level summary and usage, and a pointer to https://aka.ms/dotnet-illink with the msbuild settings and instructions for adding roots.
- Key concepts are documented
- There are no command-line flags to dotnet cli
- The csproj options are documented
- Templates - could you clarify what you'd like to see here?

I will be working on a section to include more information about testing, guidance, gotchas, debugging, etc.

**Comment by sdmaclea** [comment]
@sbomer Templates may be the wrong word.  I thought we were adding templates for certain specific use cases.  WPF, WinForms, ASP.NET.  They would adjust knobs as needed and roots as needed.
