### ISSUE TITLE
.NET Core 3.0 IJW C++/CLI support

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13152]
.NET Core 3.0 runtime will add support for IJW C++/CLI on Windows only

- [ ] Overview of how IJW works on .NET Core
- [ ] Overview of the IJW host
- [ ] Why not support other platforms? Need for a community supported x-plat compiler
- [ ] Minimum supported VS version (when known)
- [ ] Comparison to IJW on .NET framework
- [ ] Limitations
- [ ] Samples
- [ ] Tutorials
- [ ] Debugging tips
- [ ] Performance considerations
- [ ] Where to provide feedback and request additional features
- [ ] Relevant links

/cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
Do we want to put this in the .NET Guide or do we want to put it under https://github.com/MicrosoftDocs/cpp-docs/tree/master/docs/dotnet where the current C++/CLI documentation lives?

**Comment by eightcloud83** [comment]
any update?
Has this item been delayed to .Net Core 3.1?
Thanks.

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/

Livar Cunha  2019-09-06 18:50:23 
> Tadeas Lejsek: Can you please include details about C++/CLI suppo...

That's coming in .NET Core 3.1 and VS 16.4

**Comment by jkoritzinsky** [comment]
Yes this has been delayed to 3.1.

**Comment by miloszkukla** [comment]
@dotnet/docs Please reopen this issue. This is important for reasoning about C++/CLI programs behavior and for possible independent xplat implementation.

It would also be nice to have:
- process/threading/execution model described/drawn depending on how library is loaded/which entry point (native/managed) is used and how/when .net runtime is loaded in both scenarios
- description of mixed assembly PE layout

**Comment by miloszkukla** [comment]
Just in case somebody is looking:
https://github.com/dotnet/runtime/blob/main/docs/design/features/IJW-activation.md
https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/mixed-mode.md
