### ISSUE TITLE
.NET Core 3.0 hosting docs

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13154]
.NET Core hosting mechanism is not well documented

- [ ] Overview of hosting runtime 
- [ ] Role of hostfxr. Optional settings. Links to relevant docs
- [ ] Role of host policy. Optional settings. Links to relevant docs
- [ ] Role of deps.json. Optional settings. Links to relevant docs
- [ ] Role of runtimeconfig*json files. Optional settings. Links to relevant docs
- [ ] Role of global.json. Optional settings. Links to relevant docs
- [x] Settings passed to runtime
- [x] Accessing settings with runtime APIs
- [x] Role of TPA list. Links to .NET Core loader docs.

/cc @vitek-karas @elinor-fung

**Comment by vitek-karas** [comment]
I think we should keep this active - it's a hole in the docs which we should fill.

/cc @agocke @LakshanF
