### ISSUE TITLE
Is this document in the correct place?  

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13157]
This document is specifically about .NET Core unloadability yet it is in the .NET Guide.  Seems like it really belongs in .NET Core Guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3d455d-e22d-e9b4-b198-a698437fe2b1
* Version Independent ID: 1b8a0cfa-a921-1749-f8d0-aeac878e1f26
* Content: [How to use and debug assembly unloadability in .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto)
* Content Source: [docs/standard/assembly/unloadability-howto.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/unloadability-howto.md)
* Product: **dotnet**
* GitHub Login: @janvorli
* Microsoft Alias: **janvorli**

**Comment by mairaw** [comment]
@rpetrusha and I will be discussing the .NET Guide TOC soon.

.NET Guide is about the .NET Fundamentals concepts, so we felt that even though that topic is only for .NET Core, it belonged in the assembly section of the .NET Guide.

The .NET Core Guide is focused on a few keys aspects of the platform like what's new, deployment, SDK, CLI reference, etc. 

But we can discuss whether this makes sense or not.

**Comment by sdmaclea** [comment]
I didn't move this as part of #13799, but they probably belong in the same place.
