### ISSUE TITLE
Update for .NET Standard 2.1, .NET Core 2.2, and .NET Core 3.0

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13169]
The table in this section might want to be updated https://docs.microsoft.com/en-us/dotnet/core/versions/#relationship-to-net-standard-versions for .NET Standard 2.1, .NET Core 2.2, and .NET Core 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Core Runtime and SDK are versioned - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/index.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by sdmaclea** [comment]
I looked at this again. This doesn't seem important. Closing issue.

**Comment by mairaw** [comment]
Reopening since we do need to talk about 2.1 in there for the next release.

**Comment by eddynaka** [comment]
@mairaw @BillWagner i think we can close this.

**Comment by BillWagner** [comment]
Thanks @eddynaka Yes, we can close this.
