### ISSUE TITLE
Large portions of the .NET Framework development Guide should move

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13160]
Large portions of the .NET Framework development Guide should move to .NET Guide
Similar content required for .NET Core Guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf923cdb-38e5-90f3-0581-1d6079738635
* Version Independent ID: ee16343a-71f1-fcd7-cf76-384c40126f2c
* Content: [.NET Framework Development Guide](https://docs.microsoft.com/en-us/dotnet/framework/development-guide)
* Content Source: [docs/framework/development-guide.md](https://github.com/dotnet/docs/blob/master/docs/framework/development-guide.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
It will be better to call out which sections you think are still needed. Even for WPF and Winforms, that content is staying in the .NET Framework Guide and we're creating a new section for desktop development, where we'll be creating/updating very targeted high-pri content.

**Comment by sdmaclea** [comment]
We chatted briefly about this.
We need a general strategy.
Ultimately there needs to be a generic development guide that is not specifically tied to .NET Framework.

There are pieces which are specifically common and logically belong in the .NET Guide TOC.
There are pieces which are new for .NET Core.  It is not clear where they belong.
There are .NET Core to .NET Framework porting articles, which I guess belong in the .NET Core Guide.

**Comment by mairaw** [comment]
Porting docs belong in the .NET Core Guide but we cover Framework to Core only.

**Comment by rpetrusha** [comment]
The sections that we know need to move are (and I'm sure there's a good deal more):
- App domains and assemblies. (But we'd also like to remove the triplication in the docs -- there are also app domains and assemblies sections for C# and VB).
- Resources (see #8882)
- Portions of the Unmanaged API reference
- Interoperating with unmanaged code
- Dynamic programming
