### ISSUE TITLE
.NET Core Porting advice for Using AppDomains

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13173]
The .NET Core porting guide should probably address each of the scenarios in this guide.

Most of this content is very .NET Framework specific. So it is appropriate to stay here

Do we want to add any notes about porting to .NET Core as we add the porting guides?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22466224-0284-7845-1000-f76d59d09565
* Version Independent ID: 1bbd1b54-8042-02ca-28f8-ddb306586364
* Content: [Using Application Domains](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/use)
* Content Source: [docs/framework/app-domains/use.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/use.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gewarren** [comment]
Thanks @sdmaclea. We do have [this section](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#appdomains). Do you think further guidance is needed?

**Comment by sdmaclea** [comment]
That section seemed insufficient as we were getting lots of customer issues around porting to AssemblyLoadContext.

We have added lots of documentation in this area including #13799, #13960, dotnet/dotnet-api-docs#3056, dotnet/dotnet-api-docs#2549, dotnet/dotnet-api-docs#1975, dotnet/dotnet-api-docs#1353.

I am still not sure it is sufficient. We are still getting some customer issues.

/cc @vitek-karas @jeffschwMSFT
