### ISSUE TITLE
Flaw in "Optimisations" section

### ISSUE THREAD

**Issue by Shalin1234** [dotnet/docs#13177]
The logger function won't compile, since "File" gets a red squiggle unless the learner includes System.IO (which he/she probably does not know).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-za/dotnet/csharp/tutorials/working-with-linq#optimizations)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Shalin1234 That’s a good addition.

I’ve added this to our backlog, and to our community contributors project. We’ll update this when we next update this article. 

In the meantime, if you want to submit a PR with that additional information, I’ll help review and merge it.
