### ISSUE TITLE
Explaining reference types with pointers

### ISSUE THREAD

**Issue by elgonzo** [dotnet/docs#13180]
The page explains with regard to reference types:

> A reference type contains a pointer to another memory location that holds the data.

Some years back, Eric Lippert made a strong argument why references should not be explained as 
(memory) addresses. Link to blog post: https://blogs.msdn.microsoft.com/ericlippert/2009/02/17/references-are-not-addresses/

Sure the documentation page says a reference type _contains_ a pointer, not that a reference type _is_ a pointer. But often, readers will simply interpret this explanation to mean a reference type _is_ a pointer.  

In the end, how a reference is implemented close to the metal is an implementation detail of the runtime/JITter and shouldn't really be addressed (pun intended) on this documentation page, as trying to do so in an overly simplified manner would just invite misunderstandings and misconceptions about references, imo.

Also noteworthy is the C# counterpart of this page (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types). It avoids talking about references having/containing pointers or addresses entirely. This VB.NET page here should perhaps be organized in a similar manner as its C# counterpart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0e0036-37f7-9683-1a90-8700577b28dc
* Version Independent ID: 4ea79c95-78f2-4c2a-3070-afb6de4b7dbb
* Content: [Value Types and Reference Types](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/value-types-and-reference-types)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/value-types-and-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/data-types/value-types-and-reference-types.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
@elgonzo I think fixing this is a good improvement. The PR is here and it would be great if you get a chance to comment on my changes. 

Also, feel free to just make changes like this. There's an edit icon on the page, and editing should walk you through commit and creating a PR. We will review and get the fix in. Let us know if you find unnecessary friction in that process.
