### ISSUE TITLE
this documentation needs review

### ISSUE THREAD

**Issue by brcaswell** [dotnet/docs#13189]
Predefined code sample doesn't `return` like the document states, it assigns to a variable named `result`, which isn't defined in the sample code.

---

also, the section referencing to `ProducesResponseType` and `dynamic` usage being an issue for Swagger is little out of place, contextually speaking.  

It, as well as the `class OrderSummary` sample code defining the predefined type, should be moved to the top of `ViewModel as predefined type`, or a new section between `dynamic` type and `predefined` type that bridges\transitions from the concept of using `dynamic` to `predefined`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24f63ac2-6309-006c-0c94-1dd65194ca06
* Version Independent ID: c235e2be-f005-f889-51df-33e1b1cf0b7e
* Content: [Implementing reads/queries in a CQRS microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @brcaswell, thanks for heads up about the code.

Will fix it to also add an important aspect of using the `dynamic` type in queries.

However, I don't get to see an issue about including the reference to Swagger, as it's part of the pros and cons of dynamic vs static types.

Could you elaborate please?

Hope this helps.
