### ISSUE TITLE
SOA and Microservices in EShopOnContainer

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#13181]
Can you please elaborate on this below? The EShopOnContainer sample uses enterpise bus too, is it a SOA?

" Features like large central brokers, central orchestrators at the organization level, and the Enterprise Service Bus (ESB) are typical in SOA. "
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34002366-5bc1-226b-f617-adaca5185c67
* Version Independent ID: 017ea2e9-a055-392a-f4e8-72d2c6a3071f
* Content: [Service-oriented architecture](https://docs.microsoft.com/en-gb/dotnet/architecture/microservices/architect-microservice-container-applications/service-oriented-architecture)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/service-oriented-architecture.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/service-oriented-architecture.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @PingPongSet,

I'm not sure I get what you point to, eShopOnContainers doesn't use a centralized ESB it just uses queues for messaging, and you could even use different queues for different part of the system.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
