### ISSUE TITLE
Set<T> would be a useful addition

### ISSUE THREAD

**Issue by cskwg** [dotnet/docs#13183]
//
	public static class HasSetEx {
		//
		public static bool Set&lt;T&gt;( this HashSet&lt;T&gt; hash, T index ) {
			if ( hash.Contains( index ) ) return true;
			hash.Add( index ); return false;
		}
	}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bbd41f-9bad-bb7b-f0c9-68af6b8f4e81
* Version Independent ID: a78ad137-41d1-c0c6-f410-f427e2256e97
* Content: [Indexers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/#feedback)
* Content Source: [docs/csharp/programming-guide/indexers/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I’m going to close this as a product request.
