### ISSUE TITLE
Catalog and Basket: two Microservices or same Microservice

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#13186]
What are the factors that determines catalog and basket are separate microservices, instead of in the same microservice? 

If both are in the same microservice, it can still be automony in dev, deploy, scale.

Please elaborate if possible.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19862882-c106-afa7-660e-ead3b5dd880a
* Version Independent ID: fea4a2d6-8aa5-a400-4261-6098e76d362b
* Content: [Challenges and solutions for distributed data management](https://docs.microsoft.com/en-gb/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @PingPongSet, that's a good question!

I could mention a few differences that make them qualify as separate microservices, but there could be a lot more, as usual, depending on the context:

- They have a completely different set of requirements, so they could (should?) have different dev teams.
- For catalog you can actually still split it further to:
  - Have a microservice to display the catalog pages that will be used for (a lot of) customers and 
  - Another microservice to edit the catalog, that will be used by far-less internal users (orders-of-magnitude difference), so they will scale differently.
- You can also expect that there will be much more users browsing the catalog than actually buying and using the basket, so then again, scaling will probably be different.
- You could have catalog-editing microservices published in a restricted network, only available to company employees, but catalog-browsing microservices have to be facing the Internet.

So this are just a few sample conditions that point to them being separate microservices, probably enough to make the point.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
