### ISSUE TITLE
.NET Core API Browser Quick Filters not visible in dark mode theme

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#13199]
![image](https://user-images.githubusercontent.com/46974588/60454145-1738a780-9c01-11e9-8e52-d60916261a77.png)

**Issue description**

.NET API Browser Quick Filters are not visible in Dark Mode.

**Details**
OS: Windows 10
Browser: Edge & Edge (chromium)

**Comment by mairaw** [comment]
Since we can't control how those links are rendered with our content (source is [here](https://github.com/dotnet/docs/blob/master/api/index.md)), this needs to go to the engineering team.

**Comment by luisquintanilla** [comment]
Thanks. Closing the issue.
