### ISSUE TITLE
Link for Await Incorrect

### ISSUE THREAD

**Issue by SDWenzel** [dotnet/docs#13204]
The link for Await in paragraph 9 points to Async instead of Await.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a9a526-9135-db6b-f84b-ae52ab0876c4
* Version Independent ID: 550522d6-32ca-b8ba-7c37-5ad054102f0a
* Content: [Asynchronous Programming with Async and Await (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)
* Content Source: [docs/visual-basic/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/async/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Thanks @SDWenzel for reporting this issue. I've opened PR #13205 to fix this.

**Comment by SDWenzel** [comment]
@mairaw At first I thought the email notification of the update was spam because of the last name! Thanks for the quick fix. I don't think I've ever been notified of a correction before.

**Comment by mairaw** [comment]
Long lost relatives 😄
