### ISSUE TITLE
"End While" -> "Wend"

### ISSUE THREAD

**Issue by SMesser** [dotnet/docs#13202]
As of VBA 7.1, "End While" should be replaced by "Wend".
References: http://www.vbforums.com/showthread.php?715605-RESOLVED-Cannot-end-a-while-loop-Error-message
and 
Sub testWhile()
    Dim c As Integer
    c = 1
    While c &lt; 10
       Debug.Print "thing"
       c = c + 1
    Wend
End Sub

Please update the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfb301e-29f1-160e-09c7-03ec9f9b9e70
* Version Independent ID: d6110469-5073-8a3c-11e7-4a2f73b8c178
* Content: [While...End While Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/while-end-while-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/while-end-while-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/while-end-while-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
The link you attached is for vb6, but the docs is for vb.net.
The docs seems correct to me.

**Comment by BillWagner** [comment]
@SMesser When you tried the code above in VB.NET, you should have gotten an error message that "Wend is no longer supported. Use End While instead".  

The docs are correct. Closing this.
