### ISSUE TITLE
Request: Add links/pointers to “additional feedback mechanisms” for accessibility

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#13209]
The closing note states that using this component is not accessible, and points out that other, additional mechanisms will have to be used. It would be great if the note/this page could mention or point to (some of) those alternative/additional mechanisms.

> To make your application accessible when using this component, you must provide an additional, accessible feedback mechanism.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bed1d9b-9b7a-e4f1-71e6-8559b5f2ecac
* Version Independent ID: 7b0af150-7830-eef9-174b-1da5707a7bf3
* Content: [ErrorProvider Component Overview (Windows Forms)](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/errorprovider-component-overview-windows-forms)
* Content Source: [docs/framework/winforms/controls/errorprovider-component-overview-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/errorprovider-component-overview-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@merriemcgaw @OliaG can you help with this feedback?
