### ISSUE TITLE
Resiliently publishing to the event bus

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#13203]
Can anyone elaborate this below? I don't really understand the scenario.

"how to atomically update state in the original microservice while resiliently publishing its related integration event into the event bus"

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication#resiliently-publishing-to-the-event-bus

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ab515b-a39a-983d-2a09-13ca5ccf5125
* Version Independent ID: 82f66a0e-6ad3-c419-36cb-ecc985b9b192
* Content: [Asynchronous message-based communication](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication#resiliently-publishing-to-the-event-bus)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @PingPongSet,

Will try to help you get started with this.

"Update atomically" means that if there's an error while the transaction hasn't completed, then the state of the system is kept in a consistent state. Inconsistent means some of the operation-related tables updates but other not.

Most of the time that's solved with a database transaction.

However, what do we include in the scope of the transaction? 

Including the event publishing could impose a great delay in the transaction, and the message could fail before being received, so what do we do then? wait for all messages to be received... you might get to see where we are heading...

"Resiliently publishing" means that whatever happens, the message is, eventually, going to be published.

But the microservice (MS) might die right after committing but before publishing. So when the MS is restarted it should publish all messages pending for publishing.

As an alternative, there could be another MS checking a table for outgoing messages (the outbox pattern), to send them but, then again, that MS could also fail.

This analysis can get as complex as you want, but the chosen path in eShop was to save messages in table as "ready to send" within the scope of the "main" transaction. And then publish the event to the queue, after committing the transaction.

That's a very simple and non-resilient outbox pattern, that was considered good enough for the sake of a sample application, but it's certainly not even close to good enough for production.

So this is not a complete explanation but I hope it helps you get a broader view of this kind application communication system.

You might read more about failure modes in messaging systems here:
- https://multithreaded.stitchfix.com/blog/2017/08/21/handling-messaging-failures/
- https://www.rabbitmq.com/reliability.html

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
