### ISSUE TITLE
How about show mht in webbrowser?

### ISSUE THREAD

**Issue by szjfhb** [dotnet/docs#13219]
In C#/WPF, now I get issue about display the mht file.
in IE it's ok.
but in webbrowser, only give me a download notify. 
 the mht file was in the page we loaded and show in a iframe of page.
How can I resolve this?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc421c44-f66c-6e10-3413-00d6fee7ce81
* Version Independent ID: 6c375715-042f-f4e9-a0db-580b3df37320
* Content: [Security (WPF)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/security-wpf?view=netframework-4.8#feedback)
* Content Source: [docs/framework/wpf/security-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/security-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Sorry, I don't think we can help you with this question specifically. A lot of the WPF browser technology is built on older web standards and you'll probably need to upgrade to a newer browser control. I do know that if you look around WPF for .NET Core 3.0 you can find newer web browser controls. (at least I think I remember hearing about them)
