### ISSUE TITLE
Unable to load Feedback

### ISSUE THREAD

**Issue by Bluesman74** [dotnet/docs#13213]
I've tried reloading the page, but I'm always stuck with a spining wheel next to "Loading feedback"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/default-interface-members-versions)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I can’t reproduce this problem. If you continue to experience this issue, can you please click on the link called site feedback on the bottom of the page since this repo is for content issues only?

Thanks and I apologize for the inconvenience.
