### ISSUE TITLE
Incorrect link target for "Default WPF Themes"

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13216]
Hi team 
I'm moving this from here: https://github.com/dotnet/docs.fr-fr/issues/91
the user is refering to the original documentation

@gdurand commented 1 hour ago
The link https://go.microsoft.com/fwlink/?LinkID=158252 for "Default WPF Themes" redirects to https://github.com/microsoft/WPF-Samples/tree/master/Graphics/2DTransforms which does not seem to be the proper content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6821e183-9eb7-a22c-faa4-a4d19cdf10c5
* Version Independent ID: 234cafe7-028d-bb80-d0a2-0874cfda7c3c
* Content: [Customizing the Appearance of an Existing Control by Creating a ControlTemplate](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/customizing-the-appearance-of-an-existing-control?view=netframework-4.8)
* Content Source: [docs/framework/wpf/controls/customizing-the-appearance-of-an-existing-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/customizing-the-appearance-of-an-existing-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
Seems like a known issue.
https://github.com/dotnet/docs/issues/7408
https://github.com/dotnet/dotnet-api-docs/issues/821

**Comment by mairaw** [comment]
Correct. Closing as duplicate.
