### ISSUE TITLE
Move Step-by-Step Install Instructions for .NET Core to Docs

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/docs#1321]
# Move Step-by-Step Install Instructions for .NET Core to Docs

While the [install page for .NET Core](https://www.microsoft.com/net/core) provides a good landing site, users should have a place to look for more descriptive instructions on the basic installation process. These docs will also be a helpful place to provide better context on our tools.

# General

- Provides every subdivision of the [install page for .NET Core](https://www.microsoft.com/net/core) with an associated doc.
- Gives users a better way to provide feedback on install challenges.
- Allows us to provide more context on the install choices. (i.e. FTS vs. LTS, SDK vs. Runtime, msbuild vs. project.json)
- Does not force user to read deep-dive articles or lengthy blog posts just to get started.

## Requests for new Topics

1. TOC

   - Add Installation section under .NET Core Guide

2. Outline
    * Windows
      * VS 2015 Update 3 and .NET Core 1.01 Preview 2
      * VS 2017 RC
      * CLI and .NET Core 1.1 SDK
    * Linux
      * RHEL
      * Ubuntu, Mint
      * Debian
      * Fedora
      * CentOS, Oracle
      * OpenSUSE
    * macOS
      * 10.11 or higher and .NET Core 1.1
    * Docker
      * CLI
      * Visual Studio

3. Suggest reviewers

@mairaw @BillWagner @richlander

**Comment by mairaw** [comment]
@kendrahavens I'll also close the issue and we can always reopen this one if plans change.
