### ISSUE TITLE
Strong naming guidance needed for .NET Framework

### ISSUE THREAD

**Issue by dprothero** [dotnet/docs#13228]
[The article](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming) seems to indicate we should always strongly name our assemblies. It also says we shouldn't publish strong-named and non-strong-named versions. However, at the same time, it admits the many issues with strict assembly loading and the .NET Framework. Can we clarify the guidance here? Is strong-naming _still_ advised even in open source libraries published for .NET Framework?

Or, is this guidance specifically for .NET Core, Xamarin, UWP, and most other .NET implementations that don't have strict assembly loading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b392eb-c8a1-147f-e3fb-35b8ec702d53
* Version Independent ID: ffd3b865-f141-3f92-473b-fbfb9d32913b
* Content: [Strong naming and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#feedback)
* Content Source: [docs/standard/library-guidance/strong-naming.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/strong-naming.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@JamesNK @terrajobst can you help with this feedback related to strong naming? Thanks!

**Comment by JamesNK** [comment]
All the information you should know is already in the article.

There are reason you should strong name, and some reason why you shouldn't. The end decision on strong naming up to you which is why the recommendation is **consider** rather than **should**.

**Comment by terrajobst** [comment]
> Is strong-naming _still_ advised even in open source libraries published for .NET Framework?

Yes.

**Comment by terrajobst** [comment]
@mairaw I'm open to suggestions on how we could make this clearer. I second @JamesNK comment that the guidance should be clear.
