### ISSUE TITLE
Explanation of what "safeonly" actually means is missing

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docs#13227]
This document does not really explain what "safeonly" actually means. What are "safety nullability warnings" compared to regular nullability warnings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by 333fred** [comment]
@BillWagner we should just remove any references to safeonly, as it's no longer a valid option.

**Comment by BillWagner** [comment]
Closing, as we're already tracking removing "safeonly" in another issue.

**Comment by BillWagner** [comment]
My mistake on closing this. It's not a duplicate.
