### ISSUE TITLE
Maybe not updated?

### ISSUE THREAD

**Issue by virtualgithub** [dotnet/docs#13221]
"Does not support shortened syntax." Yes, it does https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/#expression-body-definitions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6c836c9-e05a-3fd3-b86d-32718679bcd3
* Version Independent ID: b7b2bba2-bd69-2c14-cf4d-48ea8cb6d57b
* Content: [Comparison Between Properties and Indexers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/comparison-between-properties-and-indexers#feedback)
* Content Source: [docs/csharp/programming-guide/indexers/comparison-between-properties-and-indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/comparison-between-properties-and-indexers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @virtualgithub 

Indexers do support *expression bodied members* for get only indexers. It’s still true that there is no equivalent of auto-implemented properties for indexers.

I’ve added this to our backlog, and added the *up-for-grabs* label for community contributors to consider.

**Comment by BloodyMettle** [comment]
> Indexers do support _expression bodied members_ for get only indexers. It’s still true that there is no equivalent of auto-implemented properties for indexers.

While looking at the docs, I might have gotten that wrong - but the [indexers main doc page](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/#expression-body-definitions) explicitly states that expression bodied members are supported for both, get and set in indexers since C# 7.0. So the restriction to "get only indexers" in the fix for this issue is not correct, is it?

**Comment by BillWagner** [comment]
@BloodyMettle I didn't state that well.  You can define separate expression bodied members for the `get` and `set` accessors, or you can define a single expression bodied member for a readonly indexer:

```csharp
public this[int arg]
{
   get => storage[arg];
   set => storage[arg] = value;
}

public this [string msg] => messages[msg];
```
