### ISSUE TITLE
Language reference consolidation: Arrays

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#13232]
There are a number of articles on [arrays](https://docs.microsoft.com/dotnet/csharp/programming-guide/arrays/index) in the programming guide. This topic is not covered at all in the current language reference.

See https://github.com/dotnet/docs/issues/10729#issuecomment-508248474 for background.

**Comment by TuayTong** [comment]
https://github.com/TuayTong/TuayTong-.gi

**Comment by TuayTong** [comment]
Sad  and very disappoint with my some one
