### ISSUE TITLE
Missing ThreadPoolWorkerThreadWait event

### ISSUE THREAD

**Issue by erhuan-msft** [dotnet/docs#13248]
Missing `ThreadPoolWorkerThreadWait` event with EventID `57` as described here on line 265: https://github.com/microsoft/perfview/blob/ebc8046a8a70853fa1276089f2e0a07ec14f14fa/src/TraceEvent/Ctf/CtfTraceEventSource.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbc41222-13f3-1b45-94bf-21f037f66b4a
* Version Independent ID: 4ca27a03-aa11-55bb-2b97-e2a76a8ed42d
* Content: [Thread Pool ETW Events](https://docs.microsoft.com/en-us/dotnet/framework/performance/thread-pool-etw-events#feedback)
* Content Source: [docs/framework/performance/thread-pool-etw-events.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/thread-pool-etw-events.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for filing this issue. I've added it to our backlog

**Comment by gewarren** [comment]
This has been documented now.
https://docs.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-thread-events#threadpoolworkerthreadwait-event
