### ISSUE TITLE
Security Grant Set

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#13240]
What is the formal definition for a security grant set?  I assume it is related to permissions that the admin can give an assembly, but I couldn't find anything else on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32ee8b9a-5eef-5fd4-0a0a-6aa581a63b2b
* Version Independent ID: deff4693-eea8-4699-cbdd-0b0e67863563
* Content: [Application domains](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/application-domains#feedback)
* Content Source: [docs/framework/app-domains/application-domains.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/application-domains.md)
* Product: **dotnet-framework**
* GitHub Login: 
* Microsoft Alias:

**Comment by Thraka** [comment]
Hello. I believe the "grant set" represents the permissions applied to the assembly.
