### ISSUE TITLE
Uninstalling template with version is not working

### ISSUE THREAD

**Issue by neman** [dotnet/docs#13241]
I've noticed that when I try to uninstall template with command `dotnet new -u NUGET_ID::VERSION_NO` it does not work.
It only works for `dotnet new -u NUGET_ID` when there is no version.
For example  `dotnet new -u MyTemplates::2.3.1`  wil show error `Could not find something to uninstall called 'MyTemplates::2.3.1'`
But if I try `dotnet new -u MyTemplates`  it will work. I think that this should be emphasized somewhere in docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore22)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you @neman. I'm including this information as part of my PR that updates the dotnet-new docs: #14356
