### ISSUE TITLE
Secure Coding Samples?

### ISSUE THREAD

**Issue by sometowngeek** [dotnet/docs#13256]
It would be nice if there were some examples for each of the secure coding guideline topics.
I'm familiar with Secure Coding in Java, but C# is different and having some samples would help speed up the research.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f89dddf-e9b5-b7c6-9ecc-a67b94f4412a
* Version Independent ID: d44fe46d-fce9-c72e-d035-a0c9c7f09353
* Content: [Secure coding guidelines for .NET](https://docs.microsoft.com/en-us/dotnet/standard/security/secure-coding-guidelines#feedback)
* Content Source: [docs/standard/security/secure-coding-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/secure-coding-guidelines.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@sometowngeek Thanks for the suggestion.  We'll look into adding examples the next time we're updating this article.
