### ISSUE TITLE
WebRequest No Longer Recommended for New Development

### ISSUE THREAD

**Issue by MichMP** [dotnet/docs#13253]
The WebRequest class page recommends System.Net.Http.HttpClient instead.  https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c889c1c8-bb73-b1d4-aa1d-66465edb2959
* Version Independent ID: 7876622b-bf91-4233-5d55-3319da8ae5f2
* Content: [How to: Enable a WebRequest to Use a Proxy to Communicate With the Internet](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-enable-a-webrequest-to-use-a-proxy-to-communicate-with-the-internet#feedback)
* Content Source: [docs/framework/network-programming/how-to-enable-a-webrequest-to-use-a-proxy-to-communicate-with-the-internet.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-enable-a-webrequest-to-use-a-proxy-to-communicate-with-the-internet.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
@MichMP Thank you for filing this issue. This is indeed the case. I'll put this on the backlog.

**Comment by gewarren** [comment]
Related to #11759.
