### ISSUE TITLE
Add reference to MetadataLoadContext

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13268]
Seems like the Processing Assemblies section should add a reference to the new MetadataLoadContext

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19439836-06e1-b407-04ae-444c395e1ecc
* Version Independent ID: 57e0f822-3287-3f29-530a-9aa1ccd1e862
* Content: [.NET Assembly File Format](https://docs.microsoft.com/en-us/dotnet/standard/assembly/file-format)
* Content Source: [docs/standard/assembly/file-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/file-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Is this related to .NET Core 3.0 @sdmaclea?

**Comment by sdmaclea** [comment]
It was added orthogonal to .NET Core 3.0, but in my mind it was added to provide a portable solution for reflection only load.

@vitek-karas @jkotas Can you confirm?

**Comment by jkotas** [comment]
MetadataLoadContext is a new API added in .NET Core 3.0 wave. It is a netstandard NuGet package.

I agree that it would be a good idea to mention it in this doc topic.
