### ISSUE TITLE
Overview of .NET Core needs to be updated for 3.0

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13266]
```
.NET Core is a cross-platform implementation of .NET and designed to handle server and cloud workloads at scale. 
```

This statement does not fully describe the scope of .NET Core....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba03a7c-8cbe-7670-c2e9-9b692556361c
* Version Independent ID: d085d268-bff6-f355-80b4-01c1023a5914
* Content: [.NET architectural components](https://docs.microsoft.com/en-us/dotnet/standard/components#feedback)
* Content Source: [docs/standard/components.md](https://github.com/dotnet/docs/blob/master/docs/standard/components.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.
