### ISSUE TITLE
Update guidance for MetadataLoadContext

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13267]
```
You can load an assembly only to inspect it by calling a method Assembly.ReflectionOnlyLoadFrom.
```
As I understand it the current preferred mechanism is to use MetadataLoadContext

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac305e0-d5f4-028e-d801-615e457c9c26
* Version Independent ID: 9abcd631-8133-0e05-b1b4-e22b5319ad1f
* Content: [Assemblies in .NET](https://docs.microsoft.com/en-us/dotnet/standard/assembly/)
* Content Source: [docs/standard/assembly/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/index.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Who could confirm this @sdmaclea?

**Comment by sdmaclea** [comment]
@mairaw I didn't work on MetadataLoadContext.  I think it was in progress when I joined Microsoft. I was under the impression that Assembly.ReflectionOnlyLoadFrom wasn't supported on .NET Core. MetaDataLoadContext was preferred because it worked efficiently on all .NET Standard platforms. As we were working through the .NET Core 3.0 ApDomain replacement story I had assumed `MetaDataLoadContext` was a key piece.

@vitek-karas or @jkotas should be able to confirm the guidance.

**Comment by jkotas** [comment]
ReflectionOnlyLoadFrom is not supported in .NET Core. MetaDataLoadContext is the recommended replacement technology for ReflectionOnlyLoadFrom API in .NET Core.

**Comment by vitek-karas** [comment]
`Assembly.ReflectionOnlyLoadFrom` will always throw on .NET Core. Is there a way to make this document show different content based on selection of .NET Core versus .NET Framework - or do we simply add two sections explicitly stating the difference?
