### ISSUE TITLE
Missing example code?

### ISSUE THREAD

**Issue by Dc9894** [dotnet/docs#13273]
Hi, it seems to me that I the "Integration testing ASP.NET Core apps" there is a reference to "An example of an integration test of a data access class is shown in the Integration Testing section earlier in this chapter."

I looked over that section but there is no code regarding a data access class integration test. Is the perhaps this related to the #8225 issue? I say this as in that issue I pointed out there is a code with no relation to the context in which it appears

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ba44f-bfb6-e9bf-0bba-b91ee867340d
* Version Independent ID: 789c8230-93ba-d484-edda-c8b2a9a8073c
* Content: [Test ASP.NET Core MVC apps](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@ardalis can you help with this feedback? Do you know what example code the text is referring to? Thanks!

**Comment by ardalis** [comment]
I'll look into it today.
