### ISSUE TITLE
Unicode literal range

### ISSUE THREAD

**Issue by tldrlol** [dotnet/docs#13271]
The documentation states that:

> ... or UTF-32 encodings that you can specify by using \U followed by a 32-bit hexadecimal code that represents any Unicode code point (00000000 - 00010FFFF).

However the upper bound seems wrong here, specifically the literal `"\U00010FFFF"` results in a 3 character string, with the third character being `'F'`.

Unless I'm mistaken,  the upper bound should be `0010FFFF`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3a3edd2-5887-40c7-4feb-0b0cd71f4b8a
* Version Independent ID: 031fc9cd-677b-25a5-f708-f2c2f991e61a
* Content: [Literals - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/literals#feedback)
* Content Source: [docs/fsharp/language-reference/literals.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/literals.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
This is fixed in #13257 - I don't think the merge to live went through yet.
