### ISSUE TITLE
Incorrect parameter in sql replication code 

### ISSUE THREAD

**Issue by MashaMSFT** [dotnet/docs#13279]
The value in ServerConnection does not match the comment in the c# example in this article:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.replication.subscription.publicationname?redirectedfrom=MSDN&view=sqlserver-2016#Microsoft_SqlServer_Replication_Subscription_PublicationName

 //Create a connection to the Publisher.
           ServerConnection conn = new ServerConnection(subscriberName);

(subscriberName) should be (publisherName). 

I couldn't find the file to submit a PR against - sorry :)

Thanks!

**Comment by mairaw** [comment]
@MashaMSFT sorry for the delay but I don't know how the SQL Server .NET SDK process works. 

You can find the right repo and source file by right clicking any Docs article and viewing source. The original_content_git_url metadata value will contain the location. Now whether this is hand-authored or self-generated I can't tell. We first need to find the owner to tell us that.

**Comment by mairaw** [comment]
@MashaMSFT the change you did is live (thanks @rothja for the help with publishing!). 

I just noticed that the change was only done to the C# version of the sample. You might want to fix the VB one too.

**Comment by MashaMSFT** [comment]
@mairaw , i did a quick scan of the VB script and did not notice the issue but maybe I missed it.. Did you see it?

Thanks!

**Comment by mairaw** [comment]
Yep
![image](https://user-images.githubusercontent.com/12971179/63474776-2bde3280-c42f-11e9-858b-99a56210d6b7.png)

**Comment by MashaMSFT** [comment]
thanks for catching that! I have no idea how I missed it :) it's been fixed... Thanks!
