### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Dc9894** [dotnet/docs#13272]
There is a typo I believe, it's in the first paragraph of the "Integration tests" section:

"(...) Thus, you should avoid testing things that could be *tests* with unit tests in integration tests."

Should say "tested", right?

Great content by the way, very clear and useful, love reading these docs!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ba44f-bfb6-e9bf-0bba-b91ee867340d
* Version Independent ID: 789c8230-93ba-d484-edda-c8b2a9a8073c
* Content: [Test ASP.NET Core MVC apps](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps#feedback)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think "avoid testing" is correct, not "avoid tested".

**Comment by Dc9894** [comment]
I meant that the typo was in the "tests" word:
Original:
"(...) that could be >tests< with unit tests (...)"

Shouldn't that word be "tested" instead?

**Comment by Youssef1313** [comment]
I'm not an English native speaker, but I think you're correct. Maybe you can make a Pull Request.

**Comment by mairaw** [comment]
Your suggestion looks correct @Dc9894. Would you like to submit the fix? 

The instruction on how to do this can be found at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by mairaw** [comment]
Fixed by PR #13288
