### ISSUE TITLE
Update documentation to reflect new Blazor template names

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/docs#13285]
**Issue description**
The following docs need to be updated to reflect [the rename of the Blazor templates](https://github.com/aspnet/AspNetCore/pull/11550).

- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/client-side?view=aspnetcore-3.0
- https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0
- https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio
- https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio

**Comment by Thraka** [comment]
These articles live in the ASP.NET Core docs repository. Please open an issue with the https://github.com/aspnet/AspNetCore.Docs repo
