### ISSUE TITLE
function?

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#13280]
"The AddressOf operator creates a function delegate" in Remarks says function but the example clearly uses a Sub. Big difference to a VB programmer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b816a20-38f9-53fd-0bf4-80ed1fa0e08b
* Version Independent ID: 9961ee03-00ea-f299-8303-f395b61e6189
* Content: [AddressOf Operator (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/addressof-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vb.AddressOf)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-VB)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [docs/visual-basic/language-reference/operators/addressof-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/addressof-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Fixed in #13290
