### ISSUE TITLE
Can't run a simple Hello Word in Alpine Linux (netcoreapp2.1)

### ISSUE THREAD

**Issue by AreYouQQ** [dotnet/docs#13287]
![virtualbox_2018-06-01_16-07-56](https://user-images.githubusercontent.com/37007704/40829754-038364d6-65b7-11e8-9841-b5b3ac262525.jpg)

SDK Version: 2.1.300
In Windows OS,I build it and It run OK, ( Tested it In Centos 7.0 it run OK )
But,
First, Alpine Linux use the newest Alpine version .net core runtime 
But I put all files in Release Directory to Alpine Linux,When I run it, I get a error (Top Picture)

**Comment by mairaw** [comment]
We should at least add the required dependencies to this part of the doc:
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore30#linux-distribution-dependencies

Can you help with that @janvorli?

**Comment by Thraka** [comment]
@janvorli @richlander I looked at the download page and I don't see the prereqs listed there yet. Are you tracking that work elsewhere since this issue was originally about that?

**Comment by Thraka** [comment]
@NikolaMilosavljevic This issue has been floating around for quite some time. Can we get a list of deps required for Alpine linux?

**Comment by NikolaMilosavljevic** [comment]
According the following page Alpine Linux 3.7+ is supported with .NET Core 2.1:

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md

@leecow is there an installation page for .NET Core 2.1 for Alpine Linux? It seems that there are additional dependencies that need to be documented.

**Comment by Thraka** [comment]
ping @leecow

**Comment by janvorli** [comment]
Let me at least put the list of runtime dependencies here (I've verified them with a bare bones Alpine docker image):

For .NET Core 2.1 and 3.1
```
icu-libs (this is not needed if globalization is disabled)
krb5-libs
libintl
libssl1.1 (for Alpine >= 3.9 or libssl 1.0 for older ones)
libstdc++
lttng-ust
numactl (optional, useful only for devices with NUMA enabled)
zlib
```

**Comment by janvorli** [comment]
> is there an installation page for .NET Core 2.1 for Alpine Linux?

There is a link to x64 Alpine installation page for 2.1 here: https://dotnet.microsoft.com/download/dotnet-core/2.1
Similar for 3.1 here: 
https://dotnet.microsoft.com/download/dotnet-core/3.1

However it doesn't list the dependencies.

**Comment by Thraka** [comment]
@rbhanda @leecow  Can you comment?

**Comment by janvorli** [comment]
I am going to update the https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore30#linux-distribution-dependencies. I am sorry, I've missed @mairaw pinging me  long time ago.
