### ISSUE TITLE
Example "Pack the project using a .nuspec file" has issues

### ISSUE THREAD

**Issue by tpeiffer** [dotnet/docs#13281]
There are multiple issues with this example.

First, this example uses /p: instead of the -p: used everywhere else, which is misleading.  It is valid syntax, but it is not consistent with the rest of the document, nor with the supporting document that it links to.

Second, the link that provides detail on how to pack the project using a .nuspec file says to use the following syntax for NuspecProperties:
`-p:NuspecProperties=\"key1=value1;key2=value2\"`

But the escape characters are not needed.  In fact, if you use the escape character in an Azure DevOps pipeline it will not pass the properties to the .nuspec file and the task will fail.

Example that fails from an Azure DevOps .NET core task:
`-p:NuspecProperties=\"version=$(build.buildNumber)\"`

The following works correctly in Azure DevOps and when running from the command line (Win 10):
`-p:NuspecProperties="version=$(build.buildNumber)"`

Please add a *valid* example of NuspecProperties to the example on this page.  It seems like this property would be used as much as NuspecBasePath.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tpeiffer** [comment]
And of course my comment stripped out the escape characters to you can't see the difference...

The failing task should have contained <backslash>"

-p:NuspecProperties=<backslash>"version=$(build.buildNumber)<backslash>"

**Comment by mairaw** [comment]
Thanks for your feedback @tpeiffer. @karann-msft @rohit21agrawal can you help with this request? Is the command we have for dotnet pack invalid here?

Also, can you check that the article referenced here (https://docs.microsoft.com/nuget/reference/msbuild-targets#packing-using-a-nuspec) is correct when it comes to NuspecProperties?

I'm taking care of the first issue, to make the option consistent by using -p.

**Comment by mairaw** [comment]
Friendly ping @karann-msft @rohit21agrawal

**Comment by brcaswell** [comment]
It's odd because I thought I had this working in VS2017 at some point, but in VS2019 I keep getting invalid form errors with it.. please show a valid example of using NugetProperties, not `<NuspecProperties>add nuspec properties here</NuspecProperties>`

**Comment by brcaswell** [comment]
ah.. I see.. I had htmlencoded characters in my description that was giving me false positives here; so that's a concern here...

![image](https://user-images.githubusercontent.com/967010/75631352-bf9b7300-5bb7-11ea-9b8f-033074ca6eab.png)

this built after removing the characters, so a good example could include separate lines for each key=value assignment. 

note that I'm attempting to use a single nuspec for both configuration (whereas I was using one for each with hardcoded values), so that is why I declared a property that is later used with the NuspecProperties property. .. this reflects what is automatically done when no nuspec is used, I think. 

---

Example of Local NuGet Feed using this package:
![image](https://user-images.githubusercontent.com/967010/75631445-8fa09f80-5bb8-11ea-9d22-af717f68871b.png)

**Comment by karann-msft** [comment]
@nkolev92 - can you please help here or open one on the nuget side.

**Comment by nkolev92** [comment]
I don't think the escaping is necessary in the example. 
Beyond that it's msbuild's parsing that can be tricky.

**Comment by brcaswell** [comment]
Pardon me, I don't want to confuse anyone... the issue regarding the encoding can be created on it's own; it was only relevant to explain why I had trouble implemented NuspecProperties and had to lookup an example of it's usage in the documentation (which was underwhelming).

the key=value (on each line) and nuspec variables as an example are what is relevant to this issue (at least the last issue raised in this issue workitem).

**Comment by brcaswell** [comment]
actually, my apologize.. I just realized this issue was related to the content of dotnet-pack command page.. my consideration was to [msbuild-targets #packing using a nuspec](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec) the referenced link in these comments.

sorry for the confusion.

**Comment by brcaswell** [comment]
in the following snippet on the page: 

> `dotnet pack ~/projects/app1/project.csproj -p:NuspecFile=~/projects/app1/project.nuspec -p:NuspecBasePath=~/projects/app1/nuget`

does `-p:NuspecProperties="id=$(PackageId)"` work?  

if unspecified (like the example does currently), does it use `NuspecProperties` in the csproj file? 

I think these are the considerations being raised on this page.

**Comment by sfoslund** [comment]
@tdykstra it sounds like this issue should be transfered to msbuild-targets article, per [this comment](https://github.com/dotnet/docs/issues/13281#issuecomment-593656024).

As for [this question](https://github.com/dotnet/docs/issues/13281#issuecomment-593658335), I don't know. @nkolev92 do you?

**Comment by nkolev92** [comment]
> As for this question, I don't know. @nkolev92 do you?

@brcaswell Yeah, that's an msbuild thing. 
Things passed on the cmd when invoking msbuild are considered global properties and override the project values. https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2019#global-properties
