### ISSUE TITLE
Getting Started With F# - Why are each version different

### ISSUE THREAD

**Issue by JimInWA** [dotnet/docs#13286]
I understand that each of the following pages is probably maintained by different people because they are using different tools / OSes, but in my mind each one should have same steps so that there is feature parity between each of them.  I would like feature parity as I like switching back and forth so that I understand the instructions using a variety of approaches / tools.

As of right now, the steps are radically different, with the "Get started with F# in Visual Studio" pages having the least amount of content (which is surprising to me but then again I have a bias because VS is my primary tool).

Here are the pages that I am referring to (using the titles that are displayed in the Table Of Contents):
- Get started with F# in Visual Studio
- Get started with F# in Visual Studio for Mac
- Get Started with F# in Visual Studio Code and Ionide
- Get started with F# with the .NET Core CLI

Thanks,
Jim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea0ea44-1b46-78cc-77b7-b5345a8b05ca
* Version Independent ID: ad1f303b-793c-6357-4ec0-1822468ca370
* Content: [Get started with F#](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/)
* Content Source: [docs/fsharp/get-started/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@JimInWA Each option is different because they are different environments. What you do in VS is not the same as what you'd do in VSCode or just with a command line tool. Hopefully this helps.
