### ISSUE TITLE
Proper way to resolve a client or a typed-client into a singleton?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#13291]
Based on my understanding of the info in [this](page) and in [this](https://github.com/aspnet/AspNetCore.Docs/issues/10963) issue, you should use the factory to create clients in a singleton, rather than reuse the same client.

My question is how do I generate a typed-client from the factory?

```c#
public class MyClient
{
  readonly HttpClient _HttpClient;
  public MyClient(HttpClient httpClient)
  {
    httpClient.BaseAddress = "https://mywebsite.com";
    _HttpClient = httpClient;    
  }

  public Task<string> GetMyValueAsync() => _HttpClient.GetStringAsync("route/action");  
}

public class MySingletonService : IMySingletonService
{
  readonly IHttpClientFactory _HttpClientFactory;
  public MySingletonService(IHttpClientFactory httpClientFactory)
  {
    _HttpClientFactory = httpClientFactory;
  }  
  
  public async Task DoStuffAsync()
  {
    var client = _HttpClientFactory.CreateClient<MyClient>();
    var myWebValue = await client.GetMyValueAsync();
    ...
  }
}
```

Should I just use `IServiceProvider` directly instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 1bb011dd-a559-c0d7-b0cf-984fbb2d4bd3
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by weitzhandler** [comment]
[This](https://www.stevejgordon.co.uk/ihttpclientfactory-patterns-using-typed-clients-from-singleton-services) article adds a lot.

**Comment by weitzhandler** [comment]
The simple way to do this is via `IServiceCollection.GetService<TClient>()`.

**Comment by Bosch-Eli-Black** [comment]
I've filed a suggestion for how to do this without using `IServiceCollection.GetService<TClient>()`. Would love feedback 🙂

https://github.com/dotnet/runtime/issues/64034
