### ISSUE TITLE
Migrating from `dotnet` and all other .NET Core project types

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1330]
We had multiple ways to create .NET Core projects prior to the MSBuild/csproj-based assets that are shipping for RTM of .NET Core tooling.  There were different project types in VS (xproj, PCL csproj with some packages) and different TFMs.  We need a doc which explains how each of the project types are obsolete, and what the upgrade path looks like for them.

This is motivated by a bug in TFS where a customer got bit my `dotnet` being deprecated when he upgraded some packages.

**Comment by mairaw** [comment]
@cartermp would this be added to https://docs.microsoft.com/en-us/dotnet/core/migration/? can you give us more info on this so we know how to proceed?

**Comment by cartermp** [comment]
I think this is pretty well-satisfied by that doc.  Closing!
