### ISSUE TITLE
Debugging in VS Code or Visual Studio

### ISSUE THREAD

**Issue by johndaintree** [dotnet/docs#13306]
I've successfully built a "host using NetHost.h and HostFxr.h" but I'm unable to configure VS 2019 to debug the managed side (ideally I want mixed mode debugging). In VS Code I can have "coreclr" configuration and a "cppvsbg" configuration, and debug one or the other, but again, is it possible to do mixed mode debugging there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET Core runtime host - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#feedback)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by johndaintree** [comment]
If I enable mixed mode debugging in VS 2019 I get the following in a message box:

"A fatal error has occurred........HRESULT=0x8000ffff, ErrorCode=0x0."

**Comment by Thraka** [comment]
@johndaintree Sorry for the delay in addressing this issue. I think you should ask that question at the VSCode community.
