### ISSUE TITLE
Please indicate if feature is available in .Net Framework

### ISSUE THREAD

**Issue by JesperNoerregaard** [dotnet/docs#13305]
Hi

It would be great if I could see if a given feature is available for .Net Framework or .Net Core only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @JesperNoerregaard 

@cartermp and I are working on this discussion now.

**Comment by BillWagner** [comment]
C# 8.0 was designed for .NET Core 3.0. We won’t stop anyone from using C# 8 on .NET Framework, that scenario isn’t officially supported.

Closing this without action.

**Comment by centreboard** [comment]
Could this statement about framework/core versions please be added to the text on the page?
