### ISSUE TITLE
What version of .NET Framework was gcAllowVeryLargeObjects introduced?

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#13311]
It would be nice to have a section that provides the minimal version of .NET Framework that this feature is required.

&gt; The maximum number of elements in an array is UInt32.MaxValue.

The max is Int32.MaxValue (not uint)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e093d16-79e3-e4eb-323f-4e4ef7fe677b
* Version Independent ID: f673a7d5-3db0-3bb2-5077-a3186871fc71
* Content: [&lt;gcAllowVeryLargeObjects&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@rpetrusha has a PR opened for this but @Maoni0 clarified that it is an unsigned integer. So only the requirements are being added.
