### ISSUE TITLE
Form1_Load

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#13317]
Part of the auto-generated code includes the line:  this.Load += new System.EventHandler(this.Form1_Load) - if it isn't commented out, it will cause an error.  This is a problem with many of the examples for WinForms that I've found in the API as well.

The error is:      CS1061	'Form1' does not contain a definition for 'Form1_Load' and no accessible extension method 'Form1_Load' accepting a first argument of type 'Form1' could be found (are you missing a using directive or an assembly reference?)	WinSound

Out of curiosity I tried adding the Form1_Load definition back in, but its EventArgs parameter causes a problem, so I'm not sure what the purpose of it is off-hand.  Still learning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb5db9ac-3cac-0b1a-5640-d1fd024cac8d
* Version Independent ID: c2621694-1e35-b17d-6985-8aaa103bca1f
* Content: [How to: Use Platform Invoke to Play a Wave File - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interop/how-to-use-platform-invoke-to-play-a-wave-file)
* Content Source: [docs/csharp/programming-guide/interop/how-to-use-platform-invoke-to-play-a-wave-file.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interop/how-to-use-platform-invoke-to-play-a-wave-file.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I've looked in that [article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interop/how-to-use-platform-invoke-to-play-a-wave-file) you opened the issue for, and couldn't find the line you refer:
` this.Load += new System.EventHandler(this.Form1_Load) `

**Comment by Thraka** [comment]
@Mandated @Youssef1313 

I'm going to guess that the author of the issue double-clicked on the form to open up the code file. Double clicking on an object automatically generates the code for the "default" event, which for the form is `Form_Load`.

I think the best way to handle this is to update the examples to include a benign `Form_Load` method.

```csharp
private void Form1_Load(object sender, EventArgs e) { }
```

**Comment by SeanKilleen** [comment]
I'll take this one on. I like @Thraka's suggestion here. Adding it in a PR along with an explanatory comment.
