### ISSUE TITLE
Consider adding a sample global.json that would only pin the major version

### ISSUE THREAD

**Issue by nphmuller** [dotnet/docs#13324]
I would like to automatically roll forward patch versions, so I want my global.json only to pin the feature release version of the SDK.
For example: I would like the latest `2.2.3xx` SDK version to be used. What would my global.json file look like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by IanKemp** [comment]
*deathly silence from Microsoft intensifies*

**Comment by IanKemp** [comment]
Ugh, wait, the behaviour I'm seeing is completely consistent with the "Matching rules" section. Glob support would remove all of this confusion...

**Comment by nguerrera** [comment]
It is actually possible now with https://github.com/dotnet/core-setup/pull/6953, I filed https://github.com/dotnet/docs/issues/14479 to document it.

You would pick a version, and then set rollForward to latestMinor if you always want latest minor version, and minor if you want the minor version you specified if available, else the next closest one. Major version differences would not be taken.

**Comment by mairaw** [comment]
I've added an example to PR #15382, but it uses `latestPatch` instead for this scenario.
