### ISSUE TITLE
MathJax formatting being applied to currency examples

### ISSUE THREAD

**Issue by ChrisRomp** [dotnet/docs#13335]
The docs page is injecting MathJax for formula formatting but is using only a single $ as an inline delimiter. This is causing the currency formatting examples to format incorrectly.

Suggested fix: Escape at least one of the $ chars.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard Numeric Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#feedback)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by ChrisRomp** [comment]
![image](https://user-images.githubusercontent.com/1683889/61005267-bf92ee00-a31c-11e9-8689-8d6fc90637da.png)

![image](https://user-images.githubusercontent.com/1683889/61005278-c4f03880-a31c-11e9-8950-1d0485c8ce3c.png)

**Comment by mairaw** [comment]
Saw on an internal forum that there's a way to escape the $ sign. Testing that with PR #14196.
