### ISSUE TITLE
Windows service and event log naming 

### ISSUE THREAD

**Issue by badcop666** [dotnet/docs#13339]
Hi, while I did manage to follow this tutorial and run a service, as soon as I changed the service name and/or event log source names, windows threw its toys and I am basically stuck. This (windows services) is incredibly fragile - error logging, exception logging is poor to say the least, this should me mentioned. Is there a dependancy on event log? What does visual studio do with the project name? is there some hidden dependency I can't see which continues to plague me?
Super disappointed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Tutorial: Create a Windows service app](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
It does sound like you're running into a conflict where the project name was used during code generation. I would do a FIND IN FILES in visual studio and look for the old project name. A faint memory makes me think that there is something with installing the service (which in debug mode, might happen for testing) and that install procedure creating an event log. When you changed the name, the old service is still registered with the system some how? I'm unsure.
