### ISSUE TITLE
Why I have to Fit before Transform?

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#13332]
## Intro

Hi, I want to do some data preparation actions, and the put the `DataView` to another method, or use it in multiple places.

So, I creating an `IEstimator&lt;ITransformer&gt;` object to hold the pipeline, for example:

```
var textEstimator = mlContext.Transforms.Text.NormalizeText("Description")
    .Append(mlContext.Transforms.Text.TokenizeIntoWords("Description"))
    .Append(mlContext.Transforms.Text.RemoveDefaultStopWords("Description"))
    .Append(mlContext.Transforms.Conversion.MapValueToKey("Description"))
    .Append(mlContext.Transforms.Text.ProduceNgrams("Description"))
    .Append(mlContext.Transforms.NormalizeLpNorm("Description"));
```
(Copied from [docs.microsoft][1])

But now, I want to get the `DataView`, and remember, this is **not** learning pipeline yet.

---

## The question

So why I have to `Fit` the pipeline before `Tranform`?

```csharp
// Fit data to estimator
// Fitting generates a transformer that applies the operations of defined by estimator
ITransformer textTransformer = textEstimator.Fit(data);

// Transform data
IDataView transformedData = textTransformer.Transform(data);
```

  [1]: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/prepare-data-ml-net#work-with-text-data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c298a5-b76f-25d9-beda-e298ac03cf35
* Version Independent ID: 392ab238-4442-015c-ec30-eae546794cc9
* Content: [Prepare data for building a model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/prepare-data-ml-net#work-with-text-data)
* Content Source: [docs/machine-learning/how-to-guides/prepare-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/prepare-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by baruchiro** [comment]
[Cross-reference to SO](https://stackoverflow.com/questions/56975461/ml-net-transform-data-without-fitting).

**Comment by luisquintanilla** [comment]
Hi @baruchiro ,

Thank you for your question. Because this is not a doc-related issue/question, can you please post this on the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo instead.
