### ISSUE TITLE
.NET Versions Cross-Reference

### ISSUE THREAD

**Issue by kburgoyne** [dotnet/docs#13340]
Here's an example of a documentation problem. Note my emphasis here is on documentation to clear the following up. Not that I need all this explained to me. I have a reasonable idea of what is going on. It's just the available documentation is very "messy". Particularly if one hasn't read some blog postings which explain some things independently of the reference documentation.

It's very difficult to sort through and associate/cross-reference all the different version numbers associated with ".NET" components and standards. For example, have a (UWP) project open in Visual Studio and try to figure out which .NET Core version it depends upon.

docs.microsoft.com conveniently indicates a given API is, for example, available for .NET Core Version 2.2. That part's GREAT. However NuGet will say the project is using Microsoft.NETCore.UniversalWindowsPlatform version 6.2.8 and that's the latest version.

Microsoft.NETCore.UniversalWindowsPlatform in NuGet will indicate it has a dependency on .NET Core 5.0. So now we have both a "NETCore" name using 6.2.8 and a ".NET Core" name using 5.0.  Neither of which is 2.2, and both are well beyond the latest .NET Core versions.

Using the "Project URL" link in NuGet for Microsoft.NETCore.UniversalWindowsPlatform brings one to a GitHub page which immediately starts talking about .NET Native, with .NET Native 2.2 being UWP 6.2.X.

So now one has travelled through the maze to at least find a version number correlation between 2.2 and 6.2.8. However the GitHub documentation is talking about .NET Native 2.2 and makes no reference to .NET Core 2.2.

Add in an additional bit of confusion provided by the documentation.  In the API reference one can select "UWP".  Might make sense in this case, right? Except then only version "10" is offered, not 2.2 or .NET Core UWP 2.2 or something like that.  Clearly the "10" is referring to UWP support on the Windows OS.

From having read some blogs, and assuming my memory is functioning sufficiently, I personally come to the conclusion the GitHub reference to .NET Native 2.2 is implying an implementation of a .NET Core 2.2 standard even though there is no such explicit indicator. Indeed, my conclusion could very well be wrong.

I also am concluding the underlying issue here is actual code build versions (such as Microsoft.NETCore.UniversalWindowsPlatform 6.2.8) versus standards versions (such as .NET Core 2.2 or .NET Standard 2.0). I did once find, probably using a Bing search, a Microsoft page someplace which provided some cross-references between version numbers, but that page was out of date.  It didn't include the latest versions. It also required the luck of a search to find it.

What would be extremely useful is a (relatively small) database driven cross-referencing page. The user tells the page what the user knows, and the page then provides the user with all the applicable associations.

For example, one could go to the page and tell it they know their project is using "Microsoft.NETCore.UniversalWindowsPlatform 6.2.8".  The page would then respond with all the associated versions such as ".NET Core 2.2", ".NET Native 2.2", "Windows 10.X.Y.Z" etc.  That additional information should probably include additional clarity. Such as indicating ".NET Core 2.2" is a standards number, not a build number.

Likewise, one could go to the page and tell it "UWP" and ".NET Core 2.2".  The page would then respond with things like "Microsoft.NETCore.UniversalWindowsPlatform 6.2.8  = .NET Native 2.2",  and "Windows 10.X.Y.Z".

Somewhere in the provided answers should also be which ".NET Standard" version can be used with libraries as part of the project.

**Comment by mairaw** [comment]
@kburgoyne a .NET Core dependency would be called "NETCoreApp" like you can see in the following package: https://www.nuget.org/packages/System.IO.Pipelines/

As shown in the following article:
https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions, netcore50 represents UWP. I don't know the reasoning behind these naming conventions. Perhaps @terrajobst or @rrelyea can chime in to help.

And as far as showing NuGet information on an API docs page, we have a backlog item that is related to https://github.com/MicrosoftDocs/feedback/issues/72 for that.

Does that help answer your questions?

**Comment by kburgoyne** [comment]
@mairaw -- Thanks for the links. Those will also likely be useful for anyone finding their way to this thread in the future.

For myself, my intention was just to provide examples to show why some kind of centralized cross-referencing is needed.  Superficially at least, it seems like these cross-references could be expressed and maintained within a tiny SQL database, and then a web page created which presented the database information in human readable. New release cross-references would be added to the database, and (hopefully) the existing web page would just continue working but with the new information.

The database structure would then suggest ways to let developers click on the web page presented table entires to get the references presented in different ways.

Example: The web page might initially have a table (or tables) showing .NET Standard versions. Clicking on .NET Standard 2.0 in the list would cause the page to display all the implementation versions that adhere to .NET Standard 2.0.

Thanks for the information!

**Comment by terrajobst** [comment]
`netcore50` was a very unfortuanted naming convention that originated before we launched .NET Core 1.0. `netcore45` was the API surface for UWP in Windows 8.

@kburgoyne is it fair to say that your issue is mostly about UWP and now it maps to .NET Core then?

**Comment by kburgoyne** [comment]
@terrajobst -- I'm just trying to suggest that a cross-reference web page documenting the relationships between standards versions, package versions, etc, for the various platforms would be very useful for developers.  See my comment above.

**Comment by terrajobst** [comment]
Since .NET Core 2.0/.NET Standard 2.0 we've removed the platform packages from the developer experience (they are implied). Projects shouldn't explicitly reference of them.

UWP is the outlier because their version of .NET Core (.NET Native) has snapped to an earlier build environment where these features still don't exist, hence my question.

**Comment by mairaw** [comment]
We just installed this new bot to test auto closing issues so apologies for that since you did reply back @kburgoyne.  But since this is a product naming convention that we can't change, I feel like there's nothing we can do here. Perhaps NuGet could help customers understand what the TFMs mean on their UI. So I'm closing this doc issue.
