### ISSUE TITLE
offline machine learning 

### ISSUE THREAD

**Issue by jaymins93** [dotnet/docs#13348]
Hi , i want to use ML.Net in project and it uses data which i can not send over internet , i am aware ML.Net is offline processing the model and predicting results , but i can not find it on the web page mentioned , it is very useful for enterprise , can some one from Microsoft docs update the document or comment here that it is offline process it will really help.  

[AB#1572600](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1572600)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [What is ML.NET and how does it work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by JRAlexander** [comment]
Hi @jaymins93 Yes, ML.NET can be used offline. You don't have to be connected to a network to use it for adding machine learning functionality to your .NET applications. We'll get this added more explicitly in the docs. Thanks! @asthana86 or @CESARDELATORRE - any other thoughts?

**Comment by CESARDELATORRE** [comment]
I Agree. We might highlight this capability even further since it is a differentiator compared to other Microsoft solutions only available in Azure.

**Comment by jaymins93** [comment]
Yes please highlight this point it will helpful for many enterprise user and happy to see your response hope , official documents will get updated soon about offline usage.
