### ISSUE TITLE
Detailed Tutorial is nedded

### ISSUE THREAD

**Issue by liugaocn** [dotnet/docs#13347]
When I tried to debug with your code, this came up:
No connection could be made because the target machine actively refused it 127.0.0.1:5567
Anyway, since there is no statement which package to use, I used Microsoft.Spark.Sql

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started#feedback)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by trongnguyenbinh** [comment]
try this for debuging in visual studio: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging
it work for me.
this is my command:
```
spark-submit --class org.apache.spark.deploy.DotnetRunner --master local bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.3.0.jar debug
```

**Comment by mamccrea** [comment]
Thanks @trongnguyenbinh - I have added this guidance to the docs.
