### ISSUE TITLE
"Event properties are not supported in Visual Basic."

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#13356]
It is not clear what this means: "Event properties are not supported in Visual Basic."

The page links to [How to: Declare Custom Events To Conserve Memory](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/events/how-to-declare-custom-events-to-conserve-memory), in which the example declares `Public Custom Event Click As EventHandler`, which looks like the same thing as the C# "event property" `public event MouseEventHandler MouseDown`.

(The VB example also declares an event-raising accessor, which C# does not support.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a5f33d-52b9-fd2a-ecd0-35582d462f2c
* Version Independent ID: 80c4a287-3ad7-6642-ed89-d63cc71e860b
* Content: [How to: Handle Multiple Events Using Event Properties](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-handle-multiple-events-using-event-properties#feedback)
* Content Source: [docs/standard/events/how-to-handle-multiple-events-using-event-properties.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-handle-multiple-events-using-event-properties.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for pointing this out. It looks like PR #12251 replaced the token which changed the wording from `Visual Basic 2005` to `Visual Basic`.

@rpetrusha We'll need to look through #12251 to make sure that there isn't anything else that is invalid by changing the name from VB 2005 to VB. 

@NextTurn FYI

**Comment by KalleOlaviNiemitalo** [comment]
> We'll need to look through #12251 to make sure that there isn't anything else that is invalid by changing the name from VB 2005 to VB.

Yes, several of those changes are problematic, e.g. the wording "Visual Basic and later versions".

If event accessor definitions are supported in later versions of Visual Basic but not in Visual Basic 2005, then perhaps that should be mentioned in [What's new for Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/whats-new) as well.  Currently, the only mention of events is in the section that introduces the `Nameof` operator.

**Comment by NextTurn** [comment]
This is probably my bad when I was replacing this token I didn't look into the actual text.
