### ISSUE TITLE
access to filtered columns

### ISSUE THREAD

**Issue by DrEight** [dotnet/docs#13352]
in the section 'Data pre-processing and featurization' it is not clear to me how I can access to the list of the used 'features'. Or if you prefer, how can access to the list of the dropped features ?

edit by @mairaw: add topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bb37d9-1c4d-5d5f-2ed6-2ef77f2cd627
* Version Independent ID: 80ed0d4d-63d3-49f0-ae42-d1f132137352
* Content: [How to use the ML.NET automated ML API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api)
* Content Source: [docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/how-to-use-the-automl-api.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
The only article I found that had such a section was a ML.NET one @natke. So I've added the article details here.

**Comment by DrEight** [comment]
@mairaw  sorry I opened the git ticket from the documentation page and I thought that the reference was added automatically.
Yes the article is the one you added.

**Comment by luisquintanilla** [comment]
Thanks for the feedback @DrEight. Unfortunately this is not currently possible. However, it's an upcoming feature.
