### ISSUE TITLE
Find version of installed .NETFramework

### ISSUE THREAD

**Issue by dinobu** [dotnet/docs#13353]
It is ridiculous what you need to do to find version of .NETFramework.  Here is another much better way I'd say you should add

Windows &gt; Search &gt; Visual Studio Installer &gt; for installed version of VS, tap on More &gt; Modify &gt; Individual Components and see it there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
It is indeed ridiculous and it is something solved with .NET Core (which will most likely transfer to .NET 5). However, using Visual Studio is a very limited way of detecting .NET Framework and the registry remains the prescribed way of detecting it. I'm going to close this issue, but thank you for the suggestion.
