### ISSUE TITLE
Then...

### ISSUE THREAD

**Issue by Ray-Wynn** [dotnet/docs#13363]
Having success with implementing the converter in a different namespace. Then, reverting to the local: converter implementation, this now magically works. NOTE: I have tried Rebuilding, Cleaning and even rebooting repeatedly before this solution appears to have resolved the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 747dba09-a143-8d47-b7db-9e94b9ad5d87
* Version Independent ID: a440e344-bde0-7360-e92d-45f9748d08ab
* Content: [How to: Convert Bound Data](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-convert-bound-data#feedback)
* Content Source: [docs/framework/wpf/data/how-to-convert-bound-data.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-convert-bound-data.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I'm sorry, I'm unsure what you're referencing or what this issue is about? Can you please clarify.

**Comment by Ray-Wynn** [comment]
The issue relates to converter for use in XAML and C# namespace. I found that creating the converter in the XAML local: namespace failed, yet worked if I moved converter to a new namespace. Then to test, reverting everything back using cut 'n' paste to the local: namespace now worked in the local: namespace? And yes, I tried rebuilding, restarting visual studio, rebooting before I got things working?

**Comment by Thraka** [comment]
In your XAML, the `local:` XAML namespace maps to a CODE namespace. It's whatever you have it set to. If your converter class is located in the same CODE namespace that is pointed to by the XAML `local:` namespace, then using `local:` in your XAML will work. If it's a different namespace then you'll have to create a new XAML namespace name to where the converter is located at.

Please see https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-namespaces-and-namespace-mapping-for-wpf-xaml for more information.

**Comment by Ray-Wynn** [comment]
Yes that's what I expected to happen. For some reason the local: / code namespace for the converter did not work at first attempt as the converter could not be found. Yet recompiling having changed namespaces did and then changing namespaces back then worked as you would think. I have noted on GitHub that others have had similar problems implementing converters, that appear to resolve after extensive debugging efforts yet with no obvious reason. I will investigate further to see if I can produce a repeatable example for you to try yourself.

**Comment by Ray-Wynn** [comment]
Well, that is strange! All perfectly fine since having initiated a Visual Studio repair in a paranoid moment of despair. Obviously something must have broken in Visual Studio, not that it was apparent in any other circumstance or in other projects. This I suspect will remain a mystery for a little longer. Anyway, thanks for you help.

**Comment by Thraka** [comment]
You're welcome :)
