### ISSUE TITLE
Document whether the format string is safe for untrusted input.

### ISSUE THREAD

**Issue by EamonNerbonne** [dotnet/docs#13367]
The ToString format string appears to be safe in the sense that untrusted user input may cause it to crash, but not to consume arbitrary amounts of time or memory, nor to corrupt other state.

Is that interpretation correct?  If so, it would be nice to have that documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings - .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@blowdart

**Comment by blowdart** [comment]
I'm not sure I'd be comfortable with that assertion. It would depend on the actual input, so no.

**Comment by tdykstra** [comment]
@EamonNerbonne  Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
