### ISSUE TITLE
Improve .NET Core Extensibility Story

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#13372]
Starting with .NET Core 2.0, .NET Core has provided users with various ways to extend the CLI and build process. This issue tracks how we will document that scenario.

Major extendable area:

* Project/Item templates
* .NET Core Tools (global/local/path)
* Project-reference tools
* MSBuild/Targets

### Current story
---

The current story for extensibility is buried in the CLI area. The current TOC structure looks like so:

* .NET Core CLI
  * Overview
  * Global Tools
    * Overview
    * Create a Global Tool
  * Elevated access
  * Extnsibility Model
  * Custom templates
  * Enable TAB completion
  * Telemetry
  * global.json overview
  * Reference
    * dotnet
    * dotnet build
    * ...

### Proposal
---

Todo

**Comment by tdykstra** [comment]
Closing per discussion with @thraka. May reopen in the future.
