### ISSUE TITLE
bug in 'create first test' step

### ISSUE THREAD

**Issue by stevebogar** [dotnet/docs#13381]
the code for creating the first test has a few typos.  this worked for me:

using Xunit;
using PrimeServices;

namespace PrimeServices.UnitTests
{
    public class PrimeService_IsPrimeShould
    {
        private readonly PrimeService _primeService;

        public PrimeService_IsPrimeShould()
        {
            _primeService = new PrimeService();
        }

        [Fact]
        public void ReturnFalseGivenValueOf1()
        {
            var result = _primeService.IsPrime(1);

            Assert.False(result, "1 should not be prime");
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test#feedback)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by stevebogar** [comment]
actually never mind i just noticed i only copied the function not the namespace from the earlier test my bad

**Comment by fwd079** [comment]
@stevebogar  then you should close this, confuses readers.

Regards

**Comment by BillWagner** [comment]
Thanks for the comment @fwd079 

I'll close as resolved.
