### ISSUE TITLE
What about the result?

### ISSUE THREAD

**Issue by alex75it** [dotnet/docs#13380]
How can I capture the result (Success|Error) when run into PowerShell ?
$result = dotnet publish 
$result conytains all the steps, is it a string or what ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21#feedback)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello!

Sorry to say, but this article is not the right place to ask that question. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. This question is about PowerShell. 

**HOWEVER** I do happen to know your answer :)  when you run something like `$variable = command` you're assigning the output of the command to the variable. The output in case is all of the text printing the `dotnet` command does. What you want to do is just run your command by itself and then check the `$LASTEXITCODE` variable for the error level set by the previous command.

```powershell
dotnet publish
$publish_result = $LASTEXITCODE
```

So in this example you can go on to check what `$publish_result` is. I tested a little and if the publish succeeds the value is `0` and if it fails it is `1` or some other number.

I'm going to close the issue. 

Thanks.
