### ISSUE TITLE
The use of "Task void" is a BAD programming choice, as DickBaker has also noticed.

### ISSUE THREAD

**Issue by Protiguous** [dotnet/docs#13389]
The code examples need to be updated with the correct async/await pattern to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3f3464-63e0-a40f-c645-59fad8a38b9f
* Version Independent ID: 412ed2a6-36f3-382d-1e8c-979eb80c2c0a
* Content: [Using Async for File Access (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/using-async-for-file-access#reading-text)
* Content Source: [docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Indeed. I'll add this to the backlog. Thank you for alerting us.
