### ISSUE TITLE
Where is the application?

### ISSUE THREAD

**Issue by jtosey** [dotnet/docs#13383]
I created a command-line application so that I can run it from the command-line.  My command-line application is called "itc".  I'm looking for something that I can run:

$ ./itc

Or

$ ./bin/itc

Where is it?

find . 
.
./.vs
./.vs/itc
./.vs/itc/xs
./.vs/itc/xs/UserPrefs.xml
./.vs/itc/xs/sqlite3
./.vs/itc/xs/sqlite3/storage.ide-shm
./.vs/itc/xs/sqlite3/storage.ide-wal
./.vs/itc/xs/sqlite3/storage.ide
./.vs/itc/xs/sqlite3/db.lock
./.vs/itc/xs/project-cache
./.vs/itc/xs/project-cache/itc-Debug.json
./.gitignore
./itc
./itc/obj
./itc/obj/itc.csproj.nuget.g.targets
./itc/obj/itc.csproj.nuget.g.props
./itc/obj/itc.csproj.nuget.dgspec.json
./itc/obj/project.assets.json
./itc/obj/itc.csproj.nuget.cache
./itc/obj/Debug
./itc/obj/Debug/netcoreapp2.2
./itc/obj/Debug/netcoreapp2.2/itc.csprojAssemblyReference.cache
./itc/obj/Debug/netcoreapp2.2/itc.csproj.CoreCompileInputs.cache
./itc/obj/Debug/netcoreapp2.2/itc.AssemblyInfo.cs
./itc/obj/Debug/netcoreapp2.2/itc.assets.cache
./itc/obj/Debug/netcoreapp2.2/itc.csproj.FileListAbsolute.txt
./itc/obj/Debug/netcoreapp2.2/itc.dll
./itc/obj/Debug/netcoreapp2.2/itc.AssemblyInfoInputs.cache
./itc/obj/Debug/netcoreapp2.2/itc.pdb
./itc/bin
./itc/bin/Debug
./itc/bin/Debug/netcoreapp2.2
./itc/bin/Debug/netcoreapp2.2/itc.runtimeconfig.json
./itc/bin/Debug/netcoreapp2.2/itc.dll
./itc/bin/Debug/netcoreapp2.2/itc.runtimeconfig.dev.json
./itc/bin/Debug/netcoreapp2.2/itc.pdb
./itc/bin/Debug/netcoreapp2.2/itc.deps.json
./itc/itc.csproj
./itc/Program.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f959274-7022-54cc-fc9e-bbc29ab007d7
* Version Independent ID: df72aa8e-42b8-0a76-5dbb-f78707fee65a
* Content: [Get started with .NET Core on macOS using Visual Studio for Mac - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs#feedback)
* Content Source: [docs/core/tutorials/using-on-mac-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by stagnu-m** [comment]
./itc is the program you've written

**Comment by Thraka** [comment]
For .NET Core 2.2 [the default publishing mode](https://docs.microsoft.com/dotnet/core/deploying/deploy-with-cli) is to generate a cross-platform dll, called a *Framework-dependent deployment*. You start this type of app with calling `dotnet path-to-dll` in this case you would either:

>1. Navigate to `./itc/obj/Debug/netcoreapp2.2`
>2. Run `dotnet itc.dll`
>
>\- or -
>
>Run `dotnet ./itc/obj/Debug/netcoreapp2.2/itc.dll`

You can publish a **Framework-dependent executable** by either upgrading to .NET Core 3.0 or by calling `dotnet publish -c Release -r <RID> --self-contained false` where `<RID>` is a value from the [RID catalog](https://docs.microsoft.com/dotnet/core/rid-catalog). The `<RID>` represents the platform you want to generate an executable for.

I hope this answers your question. Sorry for the delay in responding.
