### ISSUE TITLE
Error on code snippet

### ISSUE THREAD

**Issue by zecarlos2000** [dotnet/docs#13388]
On section "Example: Use the Invoke method with a delegate"
The code snippet with line:

`Invoke(d, new object[] { text });`
should actually be:

`textBox1.Invoke(d, new object[] { text });`

edit by @mairaw: added topic details 
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7944fe-6db1-0fe4-7a89-29f5594b2674
* Version Independent ID: 152ac482-0811-0869-addd-258b689fbe3f
* Content: [How to: Make thread-safe calls to Windows Forms controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls)
* Content Source: [docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @zecarlos2000. I've added this to our backlog.

If anyone wants to fix this, the source files are located at:
https://github.com/dotnet/samples/blob/master/snippets/winforms/thread-safe/example1/cs/form1.cs
https://github.com/dotnet/samples/blob/master/snippets/winforms/thread-safe/example1/vb/form1.vb

**Comment by MiguelSilva96** [comment]
Hi, I will fix this :)
