### ISSUE TITLE
dotnet-install.sh does not download correct version on RHEL 6 workstation

### ISSUE THREAD

**Issue by winnieryl** [dotnet/docs#13393]
https://dot.net/v1/dotnet-install.sh
this script, at line 151, it does not consider RHEL 6 Workstation, when I run this on rhel6 workstation, it downloads the wrong version fo dotnet runtime.

**Comment by Thraka** [comment]
Hello. Thank you for opening the issue. The install script is maintained by the product team. Please file a bug wit them at https://github.com/dotnet/cli/issues

Thanks!
