### ISSUE TITLE
Clarify prerequisites

### ISSUE THREAD

**Issue by rrvenki** [dotnet/docs#13395]
Under Prerequisites
&gt; Your project must be coded in C#.
Can the author justify "must" in this article? and Why? While there are so many .NET Core 3.0 WPF projects written in VB.NET and non C# why is this author insisting C# only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9a211f-0161-1e0c-a1e3-d4460fc4ec2b
* Version Independent ID: ef286ce7-d314-1aa1-7184-6f51efb5bfaf
* Content: [Port a WPF app to .NET Core 3.0 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/wpf#feedback)
* Content Source: [docs/core/porting/wpf.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/wpf.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue

At the time Visual Studio could only load the C# projects for WPF on .NET Core. I'll check and see if that is still the case.
