### ISSUE TITLE
Feature importance based on value

### ISSUE THREAD

**Issue by famschopman** [dotnet/docs#13390]
Let’s say you want to identify which features increase or decrease a specific metric in a dataset; ‘these features have impact on feature X being positive’ and ‘these features have impact on feature X being negative’. Is that possible with PFI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1fb0dd-648b-26e9-7e4e-48824ab94160
* Version Independent ID: 689b6488-dadc-fd39-c432-ebf095a0299a
* Content: [Explain model predictions using Permutation Feature Importance - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @famschopman,

Thank you for your question. Because this is not a doc-related issue/question, can you please post this on the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo instead.

**Comment by luisquintanilla** [comment]
AB#1572600
