### ISSUE TITLE
Add more documentation for dotnet test and dotnet vstest for Preview 3+ bits

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1339]
There are certain features that do not exist in the `dotnet test` and `dotnet vstest` docs that need to be added, such as the ability to use .runsettings files, how filtering of tests work etc. 

/cc @mairaw

**Comment by mairaw** [comment]
is this partly covered here: https://aka.ms/vstest-filtering? I also noticed that we don't have dotnet vstest documented. I'll add a new issue for that.

**Comment by dmccaffery** [comment]
Is code coverage supported outside of windows yet? thats another good thing to know.

**Comment by cartermp** [comment]
@dmccaffery No, I don't believe it is.

**Comment by dmccaffery** [comment]
@cartermp :feelsgood:

**Comment by sbaid** [comment]
https://aka.ms/vstest-filtering links now points to a doc page now /cc @samadala

**Comment by mairaw** [comment]
Closing this one in favor of #2382 that has specific action items for dotnet test docs.
