### ISSUE TITLE
Multiple machines

### ISSUE THREAD

**Issue by marinepix** [dotnet/docs#13399]
What would you suggest adding/changing in order to ensure the code here works when running on 2 separate machines, both looking to copy from one network location to another?
Using a try-catch has meant each of my machines manages to copy a proportion of the files, how would I know when the copy operation had completed? Thanks for your advice!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d050f686-38eb-bb76-5747-9e138f4da679
* Version Independent ID: 93b69d5a-5df1-c0e1-930d-2f5ee1c1fe6e
* Content: [How to: Copy directories](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories#feedback)
* Content Source: [docs/standard/io/how-to-copy-directories.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-copy-directories.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello!

Sorry to say, but this article is not the right place to ask that question as it's not really related to a problem with the code or article itself. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow where you can get a lot of people looking at your scenario. You may find that your question is already answered there too.

I'm going to close the issue. Thanks and sorry!

Thanks.
