### ISSUE TITLE
Incorrect logical operator?

### ISSUE THREAD

**Issue by mqudsi** [dotnet/docs#13404]
I believe in this quote:

&gt; Rank = 1, lower bound = 0. Size is known only if provided in the managed signature. Safe arrays that are not rank = 1 or lower bound = 0 cannot be marshaled as `SZARRAY`.

The text "Safe arrays that are not rank = 1 **or** lower bound = 0" should be "Safe arrays that are not rank = 1 **and** lower bound = 0"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445f0f55-f85d-7c3a-2986-746d2317b54b
* Version Independent ID: 577e2770-29d7-fb0c-e7d4-c59e9737c457
* Content: [Default Marshaling for Arrays](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-arrays)
* Content Source: [docs/framework/interop/default-marshaling-for-arrays.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/default-marshaling-for-arrays.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. Yes, I think you're correct. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
