### ISSUE TITLE
Server Core for .Net Framework Insufficient

### ISSUE THREAD

**Issue by bormm** [dotnet/docs#13409]
My ticket on the server core project, that .net framework is not full usable with the server core image was confirmed, but closed. So it will never fixed. So please add a hint that server core has only limited .net framework support.
See https://github.com/microsoft/dotnet-framework-docker/issues/299

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888b22d0-7261-c6fd-e4b3-07a4c1f66d06
* Version Independent ID: ddfcec03-a396-8851-49cd-629b9c7edc8a
* Content: [What OS to target with .NET containers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-container-os-targets)
* Content Source: [docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @bormm, 

Thanks for the heads up!

Will include a note about this issue.
