### ISSUE TITLE
installutil for c++

### ISSUE THREAD

**Issue by nixomose** [dotnet/docs#13400]
I have visual studio pro installed, I have a c++ service I want to install but no .net framework and therefore no installutil.exe
so what do I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b07b20b-5937-9784-082f-8655bad1acdd
* Version Independent ID: 22eda03b-36bf-e612-384f-af3a3d2725a6
* Content: [Installutil.exe (Installer Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/installutil-exe-installer-tool#feedback)
* Content Source: [docs/framework/tools/installutil-exe-installer-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/installutil-exe-installer-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by MSDN-WhiteKnight** [comment]
Installutil only installs services that are implemented as .NET assemblies. To install service implemented as native EXE/DLL you need to use [sc create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create) command. It should be included in all modern Windows versions, even client ones. See also https://support.microsoft.com/en-us/help/251192/how-to-create-a-windows-service-by-using-sc-exe

**Comment by nixomose** [comment]
gotchya, thanks. that worked.
