### ISSUE TITLE
NET Core supported Windows versions for netcore3

### ISSUE THREAD

**Issue by johnsimons** [dotnet/docs#13405]
Under https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-supported-windows-versions it says Windows Server 2008 R2 SP1 is supported but then in the next section https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-supported-operating-systems, the link to netcore3 (https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md) it is only Windows Server 2012 R2 SP1+.

So my question is which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#feedback)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up. I'm not sure which is correct so I'll ask around.

Thanks again!

**Comment by Thraka** [comment]
I found out that Windows 2008 is not going to be supported with Core 3.0. It is supported with 2.2 though.

**Comment by johnsimons** [comment]
Thank you
