### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by matkoliptak** [dotnet/docs#13411]
In the paragraph "Overriding a default", the link "-langversion compiler option." doesn't seem to take me anywhere upon clicking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#set-the-langversion-compiler-option)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/dotnet/docs/pull/13385

**Comment by rpetrusha** [comment]
Thanks for pointing out the broken link, @matkoliptak. Since it's already been fixed, I'll close this issue.
