### ISSUE TITLE
Wrong percentage and app name included in documentation

### ISSUE THREAD

**Issue by joehoppe** [dotnet/docs#13413]
The percentage in the screenshot is 71.24. Also, instead of referencing the "ConsoleAppFramework", it should reference "svcutil".

"The Portability Summary section of the report shows the the portability percentage for each assembly included in the run. In the previous example, 89.74%"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd8086b-9a95-38d5-160f-c12c653f954e
* Version Independent ID: 0f47d826-e3ef-8549-9d37-2e8afae29f46
* Content: [The .NET Portability Analyzer - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer)
* Content Source: [docs/standard/analyzers/portability-analyzer.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/portability-analyzer.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

@Lxiamail Can you take a look at this since you recently updated this article?

Thanks again!

**Comment by mairaw** [comment]
I'm assigning this one to me.

**Comment by Lxiamail** [comment]
@joehoppe Thanks for reporting the inconsistency in the document. That is right. Different application examples were used to capture the images. It is on purpose. The reason was that we want to show more complex and real world examples of the portability report data in each example. Hope this make sense to you.

**Comment by mairaw** [comment]
@Lxiamail I've opened a PR #13464 to fix the inconsistency. Can you please review? In this case, they don't make sense because the text refers to the previous image, which was changed.

**Comment by Lxiamail** [comment]
@joehoppe @mairaw Sorry, I missed the inconsistency between the text and the image. Thanks @mairaw for the quick fix.

**Comment by mairaw** [comment]
No worries @Lxiamail!
