### ISSUE TITLE
C# Language Reference: Update `?` operator (for nullable valuetypes)

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#13422]
The docs on `?` describe it as a way to create nullable value types (such as `int?`). This now applies to all reference types (such as `string?`).

**Comment by pkulikov** [comment]
@BillWagner strictly speaking, currently I don't see the dedicated page about the `?` symbol. Also, should it be referred to as an operator? It doesn't participate in expressions. To me, it's more like a token. Thus, the candidate location for the dedicated article (if it's necessary) would be:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/

That separate article would be very short with one link to the overview of the nullable value types, another one - to the nullable reference types.

Another possible resolution of this issue that doesn't require a separate page and speculations if the `?` symbol is an operator: two overviews (one about nullable value types, another about nullable reference types) should cross-reference each other.

Overview of the nullable value types:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/

Overview of the nullable reference types:
https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references
