### ISSUE TITLE
Language Reference: Document null forgiveness operator (`!`)

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#13420]
This should be done consistent with the consolidation of existing operators. Consider member access operators? Or the nullable conditional operators?

**Comment by pkulikov** [comment]
> Consider member access operators? Or the nullable conditional operators?

@BillWagner if by the "nullable conditional operators" you mean the `?.` and `?[]` operators, then those are in one overview with the member access operators:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators

So, the null-forgiveness operator either goes to that overview OR to the separate, its own page. As far as I understand, one can use the `!` operator not only when "member-accessing".

**Comment by BillWagner** [comment]
#14727 does mention the `!` operator, but doesn't completely address it. I'm reopening this issue.

I think this should be a separate page in the operators section. I'd put it after `?.` and `??=` in the TOC. Per the comment on #14727:

>  it's not only about member access and more about declaration rather than operation (as far as I understand, x and x! generate the same code at the end?)

That's correct, there's no runtime difference between `x` and `x!`. It's only going to affect static analysis. (One implication of that fact is that `null!` is legal, and sometimes the right solution).

**Comment by BillWagner** [comment]
Interesting GitHub side effect.  The phrase "I'd be happy to fix #nnnn" appears to have triggered the closing of this issue.

**Comment by pkulikov** [comment]
> I think this should be a separate page in the operators section. I'd put it after `?.` and `??=` in the TOC. 

@BillWagner thanks for the reply. Let it be a separate page. I can work on this next week. If it's fine with you, please assign this issue to me. 

> Interesting GitHub side effect. The phrase "I'd be happy to fix #nnnn" appears to have triggered the closing of this issue.

Indeed, next time I will be more careful with the word "fix" :)

**Comment by mairaw** [comment]
Yep, that's one of the magical words: https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references
