### ISSUE TITLE
C# Guide: update all occurrences of "Nullable Types", and "Nullable Value Types"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#13421]
We often used "nullable type" where we meant "nullable value type" (because all reference types were nullable). These should be checked, and we must clarify if it applies to all nullables, or only nullable value types.

**Comment by pkulikov** [comment]
One of the places to check is the current overview of the nullable value types:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/

Consider renaming both pages and articles in such a way that those include the "value" word.

**Comment by pkulikov** [comment]
@BillWagner I would like to revise the programming guide part of the docs:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/

Is it fine to do, or you're already in the middle of the work on this issue?

**Comment by BillWagner** [comment]
@pkulikov Thank you. I'd be thrilled to have you take this on. (I'm still working on some default interface members tutorials).

I've added you to the assigned list.
