### ISSUE TITLE
a minor mistake

### ISSUE THREAD

**Issue by LanderVe** [dotnet/docs#13433]
In the Spike Detection part
"Use the IidSpikeEstimator to train the model for spike detection. Add it to the DetectChangepoint() method with the following code:" --&gt; DetectChangepoint() must be DetectSpike()

[AB#1572600](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1572600)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0953823a-7d2a-a323-5365-d9a349385552
* Version Independent ID: 54ec317c-cfb9-0c2c-ccc2-4b90a5746e99
* Content: [Tutorial: Detect anomalies in product sales - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sales-anomaly-detection#spike-detection)
* Content Source: [docs/machine-learning/tutorials/sales-anomaly-detection.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sales-anomaly-detection.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @LanderVe! We'll get that fixed and I'll reference this in the PR to keep you in the loop. Thanks again for your help. Good catch
