### ISSUE TITLE
XOR (^) operator

### ISSUE THREAD

**Issue by ResQtee** [dotnet/docs#13434]
The ^ operator doesn't remove a Flag status, it will toggle the flag.
It is a subtle difference, if you try to "remove" a day that wasn't set it will set it (might be not what you envisioned).

meetingDays | day | ^ result
-------------- | ---- | ----------
0 | 1 | 1
1 | 1 | 0

**Comment by mairaw** [comment]
Hi @ResQtee! Is this related to an article we have here?

**Comment by Youssef1313** [comment]
> 
> 
> Hi @ResQtee! Is this related to an article we have here?

I think you missed the hyperlink for `here`. but anyways it seems that OP refers to [this article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types#enumeration-types-as-bit-flags).
* I didn't review it.
