### ISSUE TITLE
Samples loading Go built .dll's into C# using P/Invoke

### ISSUE THREAD

**Issue by johncburns1** [dotnet/docs#13430]
Hey all, so I recently started working with with C# and VisualStudio about 4 months ago.  Love the product(s).  Right now we are looking into loading shared-c libraries built from Golang code (using cgo) into our C# project.  There is not much documentation on how to import .dll's built from Golang code into .NET, so  I spent a little time working through this and constructed a pretty solid and varied array of examples that could be useful for others in the future looking to do the same thing.  Especially since Go is becoming more of a prominent tool as it matures.  

If you guys are interested in putting some samples out for the public to use, let me know.  Not looking for any ownership or anything, just think that it would be helpful to others looking to use P/Invoke to import Go built .dlls or other shared-c libraries into C# code.  

Repo is [here](https://github.com/johncburns1/Golang-.NET-SharedC)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf08b819-7446-dc6c-8040-d55ecccd317d
* Version Independent ID: 931f4809-51f0-5b61-30ec-760bcfe44cb8
* Content: [Platform Invoke (P/Invoke)](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke#feedback)
* Content Source: [docs/standard/native-interop/pinvoke.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/pinvoke.md)
* Product: **dotnet**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll float this by the team. We may have an area already for examples 

Thanks again!

**Comment by Thraka** [comment]
Status: Alerted author in email.

**Comment by johncburns1** [comment]
Great.  Just let me know, I'll watch the issue for any updates.

**Comment by adegeo** [comment]
Sent another email :(

**Comment by johncburns1** [comment]
> 
> 
> Sent another email :(

What is the status of this issue? Just wondering :)

**Comment by jkoritzinsky** [comment]
Sorry for not responding. This thread totally slipped of my radar. If you would like to add some samples in dotnet/samples and update the docs to have a mention of them, I think that would be a great contribution to the ecosystem!

**Comment by johncburns1** [comment]
> 
> 
> Sorry for not responding. This thread totally slipped of my radar. If you would like to add some samples in dotnet/samples and update the docs to have a mention of them, I think that would be a great contribution to the ecosystem!

Great! Yeah I think so as well.  We use shared-c golang libraries in production with a C# code base and I believe that this is becoming more popular as well.  Would you recommend replicating this issue in dotnet/samples repo and creating a pull request with the sample?

**Comment by jkoritzinsky** [comment]
Looks like you've already opened an issue on dotnet/samples. We can use this issue to track the doc updates to point to the sample and the other issue to track the sample itself.

**Comment by johncburns1** [comment]
Perfect! Thanks for the help!
