### ISSUE TITLE
.NET Core 2.2 dependencies for Windows 7

### ISSUE THREAD

**Issue by motias** [dotnet/docs#13431]
I would like to install .NET Core 2.2 via a .zip file on Windows 7.
Is it necessary to install everything below to get it working? Or should I install only KB2999226 and KB2533623?

- Microsoft Visual C++ 2015 Redistributable Update 3
- KB2999226
- KB2533623

I am confused by the following description. Are these two sentences dependent or independent?
I'm not sure if the second sentence applies to .NET Core 2.2.

> .NET Core 1.1 and earlier versions require the Visual C++ Redistributable when running on Windows versions earlier than Windows 10 and Windows Server 2016. This dependency is automatically installed by the .NET Core installer.

> Microsoft Visual C++ 2015 Redistributable Update 3 must be manually installed when:
> - Installing .NET Core via a .zip file. This can include build/CI/CD servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#feedback)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll make this a little clearer. Yes, all three are required. The .NET Core installers after 1.1 include the C++ Runtime. So if you're installing 1.1 or less, or manually installing via a zip (no matter the version) you have to install the C++ Runtime.

Thanks again!

**Comment by motias** [comment]
@Thraka I understand Universal C++ Runtime (UCRT) is required for .NET Core. 
But UCRT is contained in both "Microsoft Visual C++ 2015 Redistributable Update 3" and KB2999226. 
Is there any other reason to install both?

I experimentally tried the installation with the following combination on clean Windows 7 SP1. 
As a result, it seems to work properly with either combination.

- Microsoft Visual C++ 2015 Redistributable Update 3 and KB2533623
- KB2999226 and KB2533623

**Comment by Thraka** [comment]
Gotcha! I'll send an email out asking around. Thanks

**Comment by Thraka** [comment]
Update: Richard acknowledged the problem and said he's interested in getting it fixed. Assigning to him and Lee.

**Comment by leecow** [comment]
If KB2533623 contains both component sets and works correctly on Win7, then dropping KB2999226 from the guidance makes sense.

**Comment by pwen090** [comment]
The download link for Windows 7 x86 KB2999226 is returning 404. https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows.

Also for .net core 3.0 installing the relevant KB's I am still getting the error "Unable to load DLL 'api-ms-win-eventing-provider-l1-1-0.dll' or one of its dependencies: The specified module could not be found."
