### ISSUE TITLE
txt problem

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13442]
@Thousandyearsofwar commented on [Wed Jul 17 2019](https://github.com/dotnet/docs.zh-cn/issues/415)

[在此处输入反馈]

(?(n2)     | Test whether n2 was matched in the input string.

)\d{7}     | If n2 was matched, match seven decimal digits.

should be

(?(n2)    | Test whether n2 was matched in the input string.

\d{7}      | If n2 was matched, match seven decimal digits.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3af3731f-af2c-e8e6-cb90-51311eb350fb
* Version Independent ID: 3c03bf87-5592-d816-5b86-5b34b6595e6f
* Content: [.NET 正则表达式中的备用构造](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/alternation-constructs-in-regular-expressions#feedback)
* Content Source: [docs/standard/base-types/alternation-constructs-in-regular-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/alternation-constructs-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---

@srvbpigh commented on [Wed Jul 17 2019](https://github.com/dotnet/docs.zh-cn/issues/415#issuecomment-512131434)

Hello, @Thousandyearsofwar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here sice the user is making a suggestion on the original text
best regards

**Comment by mairaw** [comment]
PR opened to fix this #13443
