### ISSUE TITLE
Confusion about on error goto -1

### ISSUE THREAD

**Issue by daviddstubbs** [dotnet/docs#13449]
Documentation says "On Error GoTo -1 disables the exception in the current procedure."

Should it say, more precisely...

"On Error GoTo -1 disables an exception defined in a calling procedure (and so on back up the chain) from executing in the current procedure." ?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6084eed-4de2-830f-c53e-a8546d5ef97a
* Version Independent ID: a50deb55-d5a9-db11-0eeb-e03402dd356d
* Content: [On Error Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/on-error-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/on-error-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
That section itself seems malformed. It's not very clear with what -1 does. Also, it goes on to talk about exiting before the the code execution reaches the handler label. This info should be in its own section.
