### ISSUE TITLE
ZipArchiveEntry will no longer handle archives with inconsistent entry sizes

### ISSUE THREAD

**Issue by ericstj** [dotnet/docs#13448]
## ZipArchiveEntry will no longer handle archives with inconsistent entry sizes

Zip archives list both compressed size and uncompressed size in the central directory and local header.  The entry data itself also indicates its size.  In .NET Core 2.2 and earlier versions, these values were never checked for consistency; now they are.

### Version introduced

3.0

### Change description

Starting with .NET Core 3.0, the `ZipArchiveEntry.Open` method checks that local header and central header agree on compressed and uncompressed sizes of an entry.  If they do not, the method throws an `InvalidDataException`. When reading an entry, decompressed data is truncated to the uncompressed file size listed in the header.

#### Old behavior

In .NET Core 2.2 and earlier versions, `ZipArchiveEntry.Open` succeeds even if the local header disagrees with the central header of the zip file. Data is decompressed until the end of the compressed stream is reached, even if its length exceeds the uncompressed file size listed in the central directory/local header.

#### New behavior

Starting with .NET Core 3.0, `ZipArchiveEntry.Open` throws an `InvalidDataException` if the archive's local header and/or data descriptor list sizes that disagree with the central directory of the zip file.
When reading data in a ZipArchiveEntry, it is truncated to the size indicated in the central directory.

#### Reason for change

This change was made to ensure that a ZipArchiveEntry correctly represents the size of its data so that only that amount of data is read.

### Recommended action
Repackage any zip archive which exhibits these problems.

### Category
- CoreFx

### Affected APIs
System.IO.Compression.ZipArchiveEntry.Open
System.IO.Compression.ZipFileExtensions.ExtractToDirectory
System.IO.Compression.ZipFileExtensions.ExtractToFile
System.IO.Compression.ZipFile.ExtractToDirectory

#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some changes, @ericstj. Please review them.

**Comment by ericstj** [comment]
LGTM.  /cc @buyaa-n

**Comment by buyaa-n** [comment]
LGTM

**Comment by rpetrusha** [comment]
@ericstj, do we need to document the preview version in which this change was introduced?
