### ISSUE TITLE
FontConverter & FontUnitConverter changed to behave more like .NET Framework

### ISSUE THREAD

**Issue by ericstj** [dotnet/docs#13447]
## FontConverter changed to behave more like .NETFramework

In .NETCore 2.x. FontConverter had behavior that was different from its behavior in the .NET Framework. Starting with .NET Core 3.0 Preview 7, its behavior has changed to be more its behavior in the .NET Framework.

### Version introduced

3.0

### Change description

The following are the changes made to FontConverter:

- Up to .NET Core 2.x, the default unit for input size is Pixel; starting with .NET Core 3.0, it is Point.
- In .NET Core 2.x, there are no restrictions on the input style string, such as restrictions on its name or length, so that an input style string does not have to match a style. For example, "anyRandomGarbageBold" is considered to be a bold style. Starting with .NET Core 3.0, the input style string must match the style exactly.
- In .NET Core 2.x, if the Name string is empty, all remaining attributes are ignored. Starting with .NET Core 3.0, the remaining attributes are no longer ignored.
- In .NET Core 2.x, FontUnitConverter accepts a value of "Display". Starting with .NET Core 3.0, this value is no longer accepted.

#### Old behavior
The following is the behavior of FontConverter on .NET Core 2.x:
- Passing a string for a font that omits units for the size is considered to be in "Pixel" units.
- Passing a string for a font that contains a style is permitted as long as the string contains the style term anywhere within the string.
- Passing a string without a font name results in a default font, ignoring size, style, etc.
- FontUnitConverter allows a value of "Display".

#### New behavior
The following is the behavior of FontConverter starting with .NET Core 3.0:
- Passing a string for a font that omits units for the size is considered to be in "Point" units.
- Passing a string for a font that contains a style must exactly match the style, prefixed with `style=`.
- Passing a string without a font name honors the size and style, if they are specified.
- FontUnitConverter does not allow a value of "Display".

#### Reason for change
This changes were made to ensure compatibility with Windows Forms applications that are ported from .NET Framework to .NETCore and rely on these type converters.

### Recommended action
To handle this change:
- Ensure you specify units when passing in the font size.
- Ensure you specify the style exactly and avoid misspellings or additional text when specifying a font style.
- If you wish to have a default font, omit size and style.
- Avoid the use of "Display" with FontUnitConverter.

### Category

- CoreFx

### Affected APIs

System.Drawing.FontConverter
System.Drawing.FontConverter.FontUnitConverter

#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
@ericstj, I've made some edits to the issue. Please review them.

I'm also confused about what the original behavior applies to. We don't show FontConverter or FontUnitConverter as supported on .NET Core 2.2 and earlier:

![image](https://user-images.githubusercontent.com/10886961/62499193-9d16b800-b796-11e9-96a7-4cfd4033c717.png)

Do these changes apply to an earlier .NET Core preview release?

**Comment by ericstj** [comment]
Right you are: we added these types to .NETCore 3.0 in this release.  I guess this is just a difference between Preview6 and Preview7.  In that case I think we can just close this out.
