### ISSUE TITLE
A bit more guidance in the code

### ISSUE THREAD

**Issue by LanderVe** [dotnet/docs#13453]
I know this is a difficult topic and you can't explain everything, but the code needs some additional explanation. What is a Range? What is Variable exactly? How do these constraints impact the result?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 124ca204-cb12-1183-af0a-0e58a2f18862
* Version Independent ID: abec316c-f6e1-dea8-6bfa-5f4a9f9a98b3
* Content: [Create a game match up list app with Infer.NET and probabilistic programming - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/matchup-app-infer-net)
* Content Source: [docs/machine-learning/how-to-guides/matchup-app-infer-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/matchup-app-infer-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by usptact** [comment]
I strongly suggest you to go through the Infer.NET 101 PDF document. This should cover the basic building blocks. Also, a number of simpler examples are discussed in greater detail.

**Comment by natke** [comment]
Thanks @LanderVe. We do have updates for the Infer.NET documentation on our backlog. We will update this issue again when we are actively working in that area.
