### ISSUE TITLE
Document including runtime specific packages via runtime.json

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#1345]
From https://github.com/dotnet/cli/issues/5038#issuecomment-267517531:

> packages may contain a runtime.json file that contains references to runtime specific implementations. NuGet will only download these if you are restoring for a compatible runtime.

There is no documentation for this. It could be added to: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries

**Comment by BillWagner** [comment]
Raising priority since this has been bumped several times.

**Comment by tmds** [comment]
@mairaw @BillWagner feel free to close this.

**Comment by BillWagner** [comment]
closing per customer feedback.
