### ISSUE TITLE
Minimum target symbols

### ISSUE THREAD

**Issue by ensign-nemo** [dotnet/docs#13456]
Is there a way to assess a directive against a base target version?

i.e. say I want to declare a code block for ".NET Framework 4.0 or greater" - it seems today I'd need the expression 
#if (NET40 || NET45 || NET451 || NET452 || NET46 || NET461 || NET462 || NET47 || NET471 || NET472 || NET48)
and then update it if .NET 4.8.1 were released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Sorry, there is not. You are probably using SDK-style projects which means the target framework is added as a preprocessor symbol. While it [includes `NETFRAMEWORK`](https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries#how-to-multitarget) it doesn't have one that indicates 4.0 and greater. 

What you could do though is add a conditional to the project that you can define a symbol based on the target framework. Something like `NET4ABOVE`.

```xml
  <PropertyGroup Condition="'$(TargetFramework)' == 'net40' or $(TargetFramework)' == 'net45' or $(TargetFramework)' == 'net451'">
    <DefineConstants>NET4ABOVE</DefineConstants>
  </PropertyGroup>
```

Then in your code you can use 

```csharp
#if NET4ABOVE
code...
#endif
```

I'm going to close this issue as I think it answers your question.

**Comment by chucker** [comment]
If I understand the request correctly, some notion of "or greater" has now been added: https://github.com/dotnet/sdk/issues/14540
