### ISSUE TITLE
Missing MessageEncoder Class

### ISSUE THREAD

**Issue by shyamjiniranjan** [dotnet/docs#13454]
Hi,
i am trying to use the class CustomTextMessageEncoder which inherits the class MessageEncoder
but class MessageEncoder is not declared in this document, so from where i will get this class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec24f4ae-ebea-dd11-d149-e20ba10ea101
* Version Independent ID: 7c175ff3-d413-4144-bd73-da88f07bf14f
* Content: [Custom Message Encoder: Custom Text Encoder - WCF](https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/custom-message-encoder-custom-text-encoder#feedback)
* Content Source: [docs/framework/wcf/samples/custom-message-encoder-custom-text-encoder.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/samples/custom-message-encoder-custom-text-encoder.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add this to the backlog. The namespace is not mentioned in the article but it should be. to the backlog. This class is in the `System.ServiceModel.Channels;` namespace.

Thanks again!
