### ISSUE TITLE
CustomTextMessageEncoderFactory Implementation Issue

### ISSUE THREAD

**Issue by shyamjiniranjan** [dotnet/docs#13452]
As per below link
https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/custom-message-encoder-custom-text-encoder 
There is a class 
public class CustomTextMessageEncoder : MessageEncoder
{
}
but there is no more class MessageEncoder, so from where i will get this class declaration?

**Comment by Thraka** [comment]
duplicate of #13454
