### ISSUE TITLE
Change in semantics of `(string)null` in Utf8JsonWriter

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#13469]
## Change in semantics of `(string)null` in Utf8JsonWriter

In .NET Core 3.0 Preview 7 the null string is treated as the empty string in `Utf8JsonWriter`. Starting in .NET Core 3.0 Preview 8, the null string will throw an exception when used as a property name, and will emit the JSON null token when used as a value.

### Version introduced

3.0 Preview 8

### Change description

Previously, the `null` string was treated as `""` both when writing property names and when writing values.  A `null` property name now throws an `ArgumentNullException`, and a `null` value is treated as a call to `WriteNull` or `WriteNullValue`.

Consider the following code:

```C#
string propertyName1 = null;
string propertyValue1 = null;
string propertyName2 = "prop2";
string propertyValue2 = null;
string simpleValue1 = null;

using (Utf8JsonWriter writer = new Utf8JsonWriter(stream))
{
    writer.WriteStartArray();

    writer.WriteStartObject();
    writer.WriteString(propertyName1, propertyValue1);
    writer.WriteString(propertyName2, propertyValue2);
    writer.WriteEndObject();

    writer.WriteStringValue(simpleValue1);

    writer.WriteEndArray();
}
```

#### Old behavior

The writer would previously produce the following output:

```js
[{"":"","prop2":""},""]
```

#### New behavior

The call to `writer.WriteString(propertyName1, propertyValue1)` throws an `ArgumentNullException`.  If `propertyName1 = null` is replaced with `propertyName1 = string.Empty`, the output would now be:

```js
[{"":null,"prop2":null},null]
```

#### Reason for change

Better alignment with caller expectations for `null` values.

### Recommended action

* Ensure non-`null` strings are being used as property names.
  * If the previous behavior is desired, use a null coalescing invocation: `writer.WriteString(propertyName1 ?? "", propertyValue1)`
* If the behavior of writing a `null` literal for a `null` string value is not desired, use a null coalescing invocation: `writer.WriteString(propertyName2, propertyValue2 ?? "")`

### Category

CoreFx

### Affected APIs

* [Utf8JsonWriter.WriteBase64String(string, ReadOnlySpan\<byte\>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writebase64string?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteBase64String_System_String_System_ReadOnlySpan_System_Byte__)
* [Utf8JsonWriter.WriteBoolean(string, bool)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writeboolean?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteBoolean_System_String_System_Boolean_)
* [Utf8JsonWriter.WriteNull(string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenull?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNull_System_String_)
* [Utf8JsonWriter.WriteNumber(string, int)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_Int32_)
* [Utf8JsonWriter.WriteNumber(string, long)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_Int64_)
* [Utf8JsonWriter.WriteNumber(string, uint)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_UInt32_)
* [Utf8JsonWriter.WriteNumber(string, ulong)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_UInt64_)
* [Utf8JsonWriter.WriteNumber(string, float)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_Single_)
* [Utf8JsonWriter.WriteNumber(string, double)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_Double_)
* [Utf8JsonWriter.WriteNumber(string, decimal)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writenumber?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteNumber_System_String_System_Decimal_)
* [Utf8JsonWriter.WriteStartArray(string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestartarray?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteStartArray_System_String_)
* [Utf8JsonWriter.WriteStartObject(string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestartobject?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteStartObject_System_String_)
* [Utf8JsonWriter.WriteString(string, string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_String_)
* [Utf8JsonWriter.WriteString(string, ReadOnlySpan\<byte\>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_ReadOnlySpan_System_Byte__)
* [Utf8JsonWriter.WriteString(string, ReadOnlySpan\<char\>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_ReadOnlySpan_System_Char__)
* [Utf8JsonWriter.WriteString(string, JsonEncodedText)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_Text_Json_JsonEncodedText_)
* [Utf8JsonWriter.WriteString(string, DateTime)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_DateTime_)
* [Utf8JsonWriter.WriteString(string, DateTimeOffset)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_DateTimeOffset_)
* [Utf8JsonWriter.WriteString(string, Guid)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestring?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteString_System_String_System_Guid_)
* [Utf8JsonWriter.WriteStringValue(string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writestringvalue?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WriteStringValue_System_String_)
* [Utf8JsonWriter.WritePropertyName(string)](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writepropertyname?view=netcore-3.0#System_Text_Json_Utf8JsonWriter_WritePropertyName_System_String_)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some minor edits, @bartonjs. Please review them.

**Comment by ahsonkhan** [comment]
The last API can now be linked to the docs site:
[Utf8JsonWriter.WritePropertyName(string)](
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writepropertyname?view=netcore-3.0_)

**Comment by mairaw** [comment]
Ok, I've added the link. I also don't see any edits from @rpetrusha.

**Comment by rpetrusha** [comment]
This time my edits should be here, although they're minor, @bartonjs.

**Comment by bartonjs** [comment]
LGTM
