### ISSUE TITLE
Typo/wrong info

### ISSUE THREAD

**Issue by baharestani** [dotnet/docs#13476]
Under "Deconstructing user-defined types" you said "Non-tuple types do not offer built-in support for discards." What you probably meant was "built-in support for Deconstructing".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct#feedback)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
