### ISSUE TITLE
.NET Core 3.0 prefers OpenSSL 1.1.x to OpenSSL 1.0.x

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#13475]
## .NET Core 3.0 prefers OpenSSL 1.1.x to OpenSSL 1.0.x

The release of .NET Core for Linux, which works across multiple Linux distributions, can support both OpenSSL 1.0.x and OpenSSL 1.1.x.  .NET Core 2.1 and .NET Core 2.2 look for 1.0.x first, then fall back to 1.1.x; .NET Core 3.0 looks for 1.1.x first.

This change may impact libraries or applications that do platform interop with the OpenSSL-specific interop types in .NET Core.

### Version introduced

3.0

### Change description

The .NET Core 3.0 runtime prefers loading OpenSSL 1.1.x over OpenSSL 1.0.x.  This means that libraries and applications that interoperate with OpenSSL directly may have incompatible pointers with the .NET Core-exposed values when upgrading from .NET Core 2.1 or .NET Core 2.2.

#### Old behavior

The `IntPtr` and `SafeHandle` types for interop with OpenSSL are used with libcrypto.so.1.0.0 / libcrypto.so.1.0 / libcrypto.so.10 by preference.

#### New behavior

The `IntPtr` and `SafeHandle` types for interop with OpenSSL are used with libcrypto.so.1.1 / libcrypto.so.11 / libcrypto.so.1.1.0 / libcrypto.so.1.1.1 by preference.

#### Reason for change

This change was made to add support for new cryptographic standards.

### Recommended action

Libraries and applications that do direct operations with OpenSSL need to be careful to ensure they are using the same version as the .NET Core runtime.

All libraries or applications that use `IntPtr` or `SafeHandle` values from the .NET Core cryptographic types directly with OpenSSL should compare the version of the library they use with the new `System.Security.Cryptography.SafeEvpPkeyHandle.OpenSslVersion` property to ensure the pointers are compatible.

### Category

CoreFx

### Affected APIs

* [SafeEvpPkeyHandle constructors](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.safeevppkeyhandle.-ctor?view=dotnet-plat-ext-3.0)
* [RSAOpenSsl..ctor(IntPtr)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_RSAOpenSsl__ctor_System_IntPtr_)
* [RSAOpenSsl..ctor(SafeEvpPkeyHandle)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_RSAOpenSsl__ctor_System_Security_Cryptography_SafeEvpPKeyHandle_)
* [RSAOpenSsl.DuplicateKeyHandle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaopenssl.duplicatekeyhandle?view=dotnet-plat-ext-3.0)
* [DSAOpenSsl..ctor(IntPtr)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_DSAOpenSsl__ctor_System_IntPtr_)
* [DSAOpenSsl..ctor(SafeEvpPkeyHandle)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_DSAOpenSsl__ctor_System_Security_Cryptography_SafeEvpPKeyHandle_)
* [DSAOpenSsl.DuplicateKeyHandle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsaopenssl.duplicatekeyhandle?view=dotnet-plat-ext-3.0)
* [ECDsaOpenSsl..ctor(IntPtr)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_ECDsaOpenSsl__ctor_System_IntPtr_)
* [ECDsaOpenSsl..ctor(SafeEvpPkeyHandle)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsaopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_ECDsaOpenSsl__ctor_System_Security_Cryptography_SafeEvpPKeyHandle_)
* [ECDsaOpenSsl.DuplicateKeyHandle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsaopenssl.duplicatekeyhandle?view=dotnet-plat-ext-3.0)
* [ECDiffieHellmanOpenSsl..ctor(IntPtr)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellmanopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_ECDiffieHellmanOpenSsl__ctor_System_IntPtr_)
* [ECDiffieHellmanOpenSsl..ctor(SafeEvpPkeyHandle)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellmanopenssl.-ctor?view=dotnet-plat-ext-3.0#System_Security_Cryptography_ECDiffieHellmanOpenSsl__ctor_System_Security_Cryptography_SafeEvpPKeyHandle_)
* [ECDiffieHellmanOpenSsl.DuplicateKeyHandle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellmanopenssl.duplicatekeyhandle?view=dotnet-plat-ext-3.0)
* [X509Certificate.Handle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate.handle?view=netcore-3.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some minor edits, @bartonjs. Please review them.

**Comment by bartonjs** [comment]
Tweaked "reason for change", LGTM.

**Comment by rpetrusha** [comment]
@bartonjs, do we need to note the preview version in which this change was introduced?
