### ISSUE TITLE
Minimum size for RSA key generation on Linux has increased.

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#13470]
## Minimum size for RSAOpenSsl key generation has increased.

The minimum size for generating new RSA keys on Linux has increased from 384-bit to 512-bit.

### Version introduced

3.0

### Change description

The minimum legal key size reported by the LegalKeySizes property on RSA instances from `RSA.Create()`, `new RSAOpenSsl()` and `new RSACryptoServiceProvider()` on Linux has increased from 384 to 512.

#### Old behavior

`RSA.Create(384)` succeeds.

#### New behavior

`RSA.Create(384)` throws an exception indicating the size is too small.

#### Reason for change

OpenSSL, which performs the cryptographic operations on Linux, raised their minimum between 1.0.2 and 1.1.0.  .NET Core 3.0 prefers OpenSSL 1.1.x to 1.0.x, and the minimum reported version was raised to convey this new higher dependency limitation.

### Recommended action

* Ensure that keys are being generated of sizes no less than the provider minimum.
* Note that 384-bit RSA is already considered insecure (as is 512-bit RSA). Modern recommendations, such as [NIST Special Publication 800-57 Part 1 Revision 4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r4.pdf) suggest 2048-bit as the minimum size for newly generated keys.

### Category

CoreFx

### Affected APIs

* [AsymmetricAlgorithm.LegalKeySizes](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.asymmetricalgorithm.legalkeysizes?view=netcore-3.0#System_Security_Cryptography_AsymmetricAlgorithm_LegalKeySizes)
* [RSA.Create](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.create?view=netcore-3.0#System_Security_Cryptography_RSA_Create)
* [RSAOpenSsl constructors](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaopenssl.-ctor?view=dotnet-plat-ext-3.0)
* [RSACryptoServiceProvider constructors](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider.-ctor?view=netcore-3.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some minor edits to this issue, @bartonjs. Please review them.

**Comment by bartonjs** [comment]
@rpetrusha I don't see an Edited marker on the top post, but if you edited it and I just can't see the edits: LGTM.

**Comment by mairaw** [comment]
I can't see the edited marker either.

**Comment by rpetrusha** [comment]
Nor can I. Possibly what I thought were edits were lost when my laptop dropped my wireless Internet connection, which it does all too frequently. I've made some very minor edits now.

**Comment by bartonjs** [comment]
Edited version looks good to me, too :smile:

**Comment by rpetrusha** [comment]
@bartonjs, do we need to note the preview version in which this change was introduced?
