### ISSUE TITLE
.Net install from web thru PowerShell

### ISSUE THREAD

**Issue by Ayanmullick** [dotnet/docs#13479]
Is there documentation about the corresponding Nuget packages for each dotnet version? Microsoft has more than 4000 packages on Nuget. I couldn't find an easy way to search and identify the package name for dotnet 4.7.2 thru PowerShell.

`Register-PackageSource -Name MyNuGet -Location https://www.nuget.org/api/v2 -ProviderName NuGet -Verbose`
`Find-Package -Source MyNuGet -Name *dotnet*`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Are you trying to install .NET Framework? I'm not sure what you're trying to do exactly as the article is about installing the .NET Framework. Microsoft does not provide NuGet packages to install the .NET Framework and you should use the installers linked to on the page you filed this issue.

**Comment by Ayanmullick** [comment]
@Thraka , Yes I'm trying to install .Net Framework thru PowerShell. 
Something like `Install-Package -Name dotnet4.7.2 -ProviderName  Nuget-Verbose`

PFB the Microsoft Nuget packages.

https://www.nuget.org/profiles/Microsoft

**Comment by Thraka** [comment]
Sorry, I don't believe there is anything like that besides just downloading the installer and running it from PowerShell. Your other option is to use a package manager (not a developer package manager as NuGet is more used as) like Chocolatey, which you can install and then use to install .NET Framework: https://chocolatey.org/packages/dotnetfx/4.7.2.20180712

**Comment by Thraka** [comment]
I'm going to close this issue. Thanks.

**Comment by Ayanmullick** [comment]
There should be documentation around chocolatey installation thru PowerShell.

`Install-Package -Name dotnet4.7.2 -ProviderName Chocolatey -Verbose` 
This doesn't work either.
Error:  OSE: Total package yield:'0' for the specified package 'dotnet4.7.2'.
Install-Package : No match was found for the specified search criteria and package name 'dotnet4.7.2'. Try Get-PackageSource to see all available registered package sources.

**Comment by Thraka** [comment]
@Ayanmullick This installation method is not something we support directly, and we do not have control over it either. So we wouldn't document it as a way to install .NET framework as our suggested method is downloading and running the executable.

Any problems you have with chocolatey, you should bring up with them. I've only ever used the choco.exe tool by installing chocolatey directly and then using that to install packages.

**Comment by Ayanmullick** [comment]
@Thraka , I believe those are [Microsoft-owned packages on NuGet](https://www.nuget.org/profiles/Microsoft). And I feel Microsoft should document steps to do an online install of the .Net framework thru their native cli, PowerShell.

**Comment by Thraka** [comment]
Yes, that list of packages are Microsoft owned, but the majority are developer libraries, and none of them are the .NET Framework. Microsoft does not publish the .NET Framework to NuGet. 

The package I linked you to for **chocolatey** does install .NET Framework, but those are **not** Microsoft owned.

**Comment by Ayanmullick** [comment]
[.Net Core](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/) is listed on NuGet. .NetFramework should be too.
