### ISSUE TITLE
Add sources management to dotnet cli

### ISSUE THREAD

**Issue by delormej** [dotnet/docs#13489]
It's problematic to rely on yet another cli (nuget) in x-platform scenarios, for example doing builds inside containers, running on macOS, etc... It would be great if you could add remote sources (i.e. Azure DevOps Artifacts) using dotnet add package.  This currently fails with a 401 unauthorized unless you install nuget (which also requires mono) and a credential provider... not scalable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @delormej.  
@KathleenDollard @livarcocc this feels more like a product feedback. Should this issue be moved elsewhere?

**Comment by KathleenDollard** [comment]
@delormej Could you file this at GitHub.com/dotnet/cli, since it is a product feature.
