### ISSUE TITLE
The code for evaluating the model in the recommended movie has not been shown.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13486]
@ChungYork commented on [Fri Jul 19 2019](https://github.com/dotnet/docs.zh-cn/issues/416)

original:
Add the following code to EvaluateModel() to convert the Test data: [!code-csharpTransform]

[!code-csharpTransform]这里应该是
Console.WriteLine("=============== Evaluating the model ===============");
var prediction = model.Transform(testDataView);

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0888bc80-798f-ebdd-459a-7543be1efdad
* Version Independent ID: c24ded82-d56c-e8c7-fd6a-e39929227177
* Content: [教程：生成影片推荐系统 - 矩阵因子分解 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/movie-recommendation#next-steps)
* Content Source: [docs/machine-learning/tutorials/movie-recommendation.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/movie-recommendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

---

@imba-tjd commented on [Fri Jul 19 2019](https://github.com/dotnet/docs.zh-cn/issues/416#issuecomment-513102810)

https://github.com/dotnet/docs/pull/13446

---

@srvbpigh commented on [Fri Jul 19 2019](https://github.com/dotnet/docs.zh-cn/issues/416#issuecomment-513104777)

Hello, @ChungYork
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
This code line is broken in the localized versions
![imagen](https://user-images.githubusercontent.com/26746247/61555147-0d9ea480-aa35-11e9-868a-41bf865b1af8.png)

**Comment by Thraka** [comment]
@CeciAc This seems like an error with the translation program?

**Comment by CeciAc** [comment]
Hi @Thraka 
Let me investigate with the loc team.

**Comment by CeciAc** [comment]
Hi @Thraka
This was already fixed so I'm closing this issue
best regards
