### ISSUE TITLE
ML.NET Anomaly Detection Task output should include PredictedLabel

### ISSUE THREAD

**Issue by colbylwilliams** [dotnet/docs#13481]
The [Anomaly detection inputs and outputs](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks#anomaly-detection-inputs-and-outputs) section should have [`PredictedLabel` in addition to `Score`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.PCA/PcaTrainer.cs#L381-L385).  Note: There is an [issue](https://github.com/dotnet/machinelearning/issues/3990) with the current release of ML.NET where `PredictedLabel` always evaluates to `true`.

Additionally, the description for `Score` reads:
> The non-negative, unbounded score that was calculated by the anomaly detection model.

This does not indicate how the value returned by the model for `Score` should be interpreted.  Should higher scores be interpreted as anomalies, or scores closer to zero?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks#anomaly-detection)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **johalex**

**Comment by colbylwilliams** [comment]
Confirmed [here](https://github.com/dotnet/machinelearning/issues/3990#issuecomment-513409266), **Predictions that are anomalies will have higher scores than those that aren't anomalies**.

> What it is essentially computing is 1 minus the ratio of the length of the projected vector and the input vector. We expect the higher the scores the higher the chance of an anomaly because in case of no anomaly the data point should be able to be projected without changing the length much.

**Comment by colbylwilliams** [comment]
Confirmed [here](https://github.com/dotnet/machinelearning/issues/3990#issuecomment-513409266), **Predictions that are anomalies will have higher scores than those that aren't anomalies**.

> What it is essentially computing is 1 minus the ratio of the length of the projected vector and the input vector. We expect the higher the scores the higher the chance of an anomaly because in case of no anomaly the data point should be able to be projected without changing the length much.

**Comment by colbylwilliams** [comment]
Confirmed [here](https://github.com/dotnet/machinelearning/issues/3990#issuecomment-513409266), **Predictions that are anomalies will have higher scores than those that aren't anomalies**.

> What it is essentially computing is 1 minus the ratio of the length of the projected vector and the input vector. We expect the higher the scores the higher the chance of an anomaly because in case of no anomaly the data point should be able to be projected without changing the length much.

**Comment by colbylwilliams** [comment]
Confirmed [here](https://github.com/dotnet/machinelearning/issues/3990#issuecomment-513409266), **Predictions that are anomalies will have higher scores than those that aren't anomalies**.

> What it is essentially computing is 1 minus the ratio of the length of the projected vector and the input vector. We expect the higher the scores the higher the chance of an anomaly because in case of no anomaly the data point should be able to be projected without changing the length much.

**Comment by natke** [comment]
Thanks @colbylwilliams. We will add this as part of the updates for  #13880

**Comment by luisquintanilla** [comment]
AB#1596627
