### ISSUE TITLE
How would a prediction be made if the class contains properties which need to be transformed?

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [dotnet/docs#13491]
In this example the HousingData class contains only properties that do not need to be transformed, how would a prediction be made if the class contains properties which need to be transformed into vectors of float/Single values (such as strings)? 
The original class would still have string properties leading to an InvalidOperationException when creating the PredictionEngine because CreatePredictionEngine expects the properties to be the same as in the trained model which are float vectors whereas the original class would still have string properties. In other words, imagine HousingData had an Address property of type string, how would the prediction code look then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e7cf89-1a90-7693-db50-11b770c09160
* Version Independent ID: 21c26fd2-c6ad-2c2f-166b-03ac0590a1c2
* Content: [Make predictions with a trained model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @Ivan-Kouznetsov ,

Thanks for your question. I would suggest looking into the [Prepare Data How-To Guide](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/prepare-data-ml-net) for this information.
