### ISSUE TITLE
Missing screenshots

### ISSUE THREAD

**Issue by matthiasguentert** [dotnet/docs#13498]
Please provide screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c22a97-ab05-83b7-64c8-ba74e02f45e2
* Version Independent ID: 5f664967-d202-9a83-ca1b-f4636b67e438
* Content: [Walkthrough: Creating an Explorer Style Interface with the ListView and TreeView Controls Using the Designer](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/creating-an-explorer-style-interface-with-the-listview-and-treeview#feedback)
* Content Source: [docs/framework/winforms/controls/creating-an-explorer-style-interface-with-the-listview-and-treeview.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/creating-an-explorer-style-interface-with-the-listview-and-treeview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
