### ISSUE TITLE
COMPLUS_ProfAPI_ProfilerCompatibilitySetting

### ISSUE THREAD

**Issue by zowazHC5** [dotnet/docs#13492]
The note on this setting should document what the settings are, eg

set COMPlus_ProfAPI_ProfilerCompatibilitySetting=EnableV2Profiler

ref:
https://blogs.msdn.microsoft.com/davbr/2009/05/26/run-your-v2-profiler-binary-on-clr-v4/

and verified with a test profiler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e7ae61c-8879-e740-39c5-771d698e95b3
* Version Independent ID: 041510a3-e62f-082f-88c3-40c8be37652b
* Content: [Setting Up a Profiling Environment](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/setting-up-a-profiling-environment#feedback)
* Content Source: [docs/framework/unmanaged-api/profiling/setting-up-a-profiling-environment.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/setting-up-a-profiling-environment.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @zowazHC5 for your comment.
@tommcdon can you help with this feedback?
