### ISSUE TITLE
Item vs Project Template

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/docs#13509]
What are they?  Project template I think I get but what is an item template?  Maybe it is used when I add an item to my project?

Just found this useful nugget in VS:

![image](https://user-images.githubusercontent.com/14079228/61649360-547fda80-ac7f-11e9-9e03-49750eab9300.png)

It seems what they are should be discussed somewhere, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
.NET Core CLI templates are only for using the `dotnet` command line. Visual Studio does not import these and you cannot use them from Visual Studio.

Is there a way to improve the description of item template from the article?

>An item template is a specific type of template that contains one or more files. These types of templates are useful when you want to generate something like a config, code, or solution file. In this example, you'll create a class that adds an extension method to the string type.

**Comment by spottedmahn** [comment]
I see, thanks for the crazy quick response time! 👏
