### ISSUE TITLE
Throws an error while handling the report and video recording using MSTest Framework

### ISSUE THREAD

**Issue by divyarahavan** [dotnet/docs#13505]
While working with "Extent Report 3" and "Video Recording" using MSTest framework in C# language at the time it throws below errors,

System.BadImageFormatException: Could not load file or assembly 'Microsoft.Expression.Encoder, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. An attempt was made to load a program with an incorrect format.

System.TypeLoadException: System.TypeLoadException: Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified..

**Comment by mairaw** [comment]
This sounds like a product bug and not a content issue @divyarahavan. This repository is only about feedback for content hosted under https://docs.microsoft.com/en-us/dotnet/. 

Product bugs should be filed under https://developercommunity.visualstudio.com/spaces/61/index.html.
