### ISSUE TITLE
This registry key seems wrong.

### ISSUE THREAD

**Issue by jgfet** [dotnet/docs#13506]
After Setup, all I have is : Windows Workflow Foundation - no Windows Presentation Foundation - and there is no Version value.

There is a v4/Full/Version that has 4.7.03062 in my machine instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dc9d6f-8577-224a-33e8-0c8c5ea7efd0
* Version Independent ID: 4d020aa7-6da9-0eee-1420-4df9c6dd0000
* Content: [How to: Determine the Installed Version of WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/how-to-determine-the-installed-version-of-wpf#feedback)
* Content Source: [docs/framework/wpf/app-development/how-to-determine-the-installed-version-of-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/how-to-determine-the-installed-version-of-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jgfet. This is a pretty old article and I don't think WPF version is captured like this any longer.

@vatsan-madhavan @grubioe should we just remove this article?

**Comment by vatsan-madhavan** [comment]
You can probably qualify the article and say that it only applies to .NET Framework <=v3.5 . This registry value is still there in .NET 3.5. 

I have no context as to the history of this key or how it was used etc. I'm simply guessing that there is a small value in preserving the article since .NET 3.5 continues to be an actively supported version of the framework. 

I don't believe there is something similar for .NET 4.x, .NET Core etc.

**Comment by mairaw** [comment]
The article would still be preserved. There's already a version of it in the archive:
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/aa349641(v=vs.90)

We'd just remove from the current supported set that we actively maintain and redirect to that one instead.

Does that sound good @vatsan-madhavan?

**Comment by vatsan-madhavan** [comment]
That sounds good to me. Thanks!
