### ISSUE TITLE
The sample code has errors

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13508]
@xitangking commented on [Sat Jul 20 2019](https://github.com/dotnet/docs.zh-cn/issues/417)

[Flags]
enum Days
{
    None = 0x0,
    Sunday = 0x1,
    Monday = 0x2,
    Tuesday = 0x4,
    Wednesday = 0x8,
    Thursday = 0x10,
    Friday = 0x20,
    Saturday = 0x40
}
class MyClass
{
    Days meetingDays = Days.Tuesday | Days.Thursday;
}

should be :

    Thursday = 0x16,
    Friday = 0x32,
    Saturday = 0x64

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e72804b0-7d65-1585-67ea-863dc561124e
* Version Independent ID: 188ff9ab-de91-bf6a-d6a5-599389d2a76b
* Content: [枚举类型 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/enumeration-types#feedback)
* Content Source: [docs/csharp/programming-guide/enumeration-types.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/enumeration-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Sat Jul 20 2019](https://github.com/dotnet/docs.zh-cn/issues/417#issuecomment-513456246)

Hello, @xitangking
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@imba-tjd commented on [Sat Jul 20 2019](https://github.com/dotnet/docs.zh-cn/issues/417#issuecomment-513457209)

0x是16进制的意思，0x10就是十进制的16。代码是没有问题的。

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user made a suggestion about the code
best regards

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!

**Comment by pkulikov** [comment]
> I'll get this fixed up.

@Thraka please note that the suggested fix is not correct. It wants to use decimal literals, though all literals are in HEX (starting with `0x`).  So, the existing sample is correct, but it might have been less confusing if the binary literals (starting with `0b`) were used instead.

**Comment by pkulikov** [comment]
> I'll get this fixed up.

@Thraka please note that the suggested fix is not correct. It wants to use decimal literals, though all literals are in HEX (starting with `0x`).  So, the existing sample is correct, but it might have been less confusing if the binary literals (starting with `0b`) were used instead.

**Comment by Thraka** [comment]
Yes.. decimal literals. doh. How did I miss that.

**Comment by pkulikov** [comment]
Also, it looks to be a common point of confusion:
https://github.com/dotnet/docs/issues/12871

**Comment by Thraka** [comment]
I like the idea of binary literals.
