### ISSUE TITLE
The link to the code example is dead

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13510]
@joh397 commented on [Mon Jul 22 2019](https://github.com/dotnet/docs.de-de/issues/144)

The link to the example code (https://go.microsoft.com/fwlink/?LinkID=159996) is dead.
The link can be found in the last sentence of the first paragraph.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a377bf0b-fc73-2df8-e2b8-a8d1e0f688fb
* Version Independent ID: 7fc5b667-3df0-8d10-93fe-294218fc5135
* Content: [Exemplarische Vorgehensweise: Hosten eines zusammengesetzten WPF-Steuerelements in Windows Forms](https://docs.microsoft.com/de-de/dotnet/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms#feedback)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@srvbpigh commented on [Mon Jul 22 2019](https://github.com/dotnet/docs.de-de/issues/144#issuecomment-513763825)

Hello, @joh397
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the reported link doesn't work in the en-us page either
![imagen](https://user-images.githubusercontent.com/26746247/61650575-631fbf00-ac8a-11e9-9cb0-c22cb7dc00ba.png)

kind regards

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

The sample you're looking for is here: https://github.com/microsoft/WPF-Samples/blob/master/Migration%20and%20Interoperability/WpfHostingWindowsFormsControl/FormsControlLibrary/MyControl.cs

Thanks again!

**Comment by mairaw** [comment]
I've fixed the FwLink to go to the right sample and also created a PR to fix the title of that sample at https://github.com/microsoft/WPF-Samples/pull/97
