### ISSUE TITLE
Please mention that [Import] only works if it's inside an [Export] class

### ISSUE THREAD

**Issue by benhxy** [dotnet/docs#13515]
Hopefully with an example of a full class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139928b3-6a8e-47e3-9ada-7658d85b38a4
* Version Independent ID: 6da3467d-e35b-b3b5-df32-4c442523491f
* Content: [Managed Extensibility Framework (MEF)](https://docs.microsoft.com/en-us/dotnet/framework/mef/#feedback)
* Content Source: [docs/framework/mef/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/mef/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@benhxy Hi. I'm not seeing this as a requirement. In the other article it demonstrates this: https://docs.microsoft.com/en-us/dotnet/framework/mef/attributed-programming-model-overview-mef
