### ISSUE TITLE
Never use mutable structs as in in argument - is it **Never**

### ISSUE THREAD

**Issue by gmanvel** [dotnet/docs#13511]
Under the section [Never use mutable structs as in in argument](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#never-use-mutable-structs-as-in-in-argument) the reasoning is that in order to ensure _readonly-ness_ of mutable structs passed using _in_ modifier defensive copies had to be made.
This behavior doesn't seem to be consistent across different compiler versions.

If I use mutable struct, which is being passed with _in_ modifier, with _older_ versions of the compiler the defensive copy is indeed created. ([sharplab.io](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACh4AIYIOyoN6rpGYIBsmALOgLICGYAdgBRYAMA2gLrq0BOA5gGcAlKgCQBFMWnoAbn3QAHAPaNgCdAF50DAKYB3GgFdgtAEYRdABVUNgAZgAiTVgBp0bj8IDchGUXleJVtgOC0dA2NTC2sQpyYEd0T0BB9UP39A9AATMEFTBgBjXXCAYVoIQqMIWmBdRzyC4qZGYLVk1pU1ODSUMQBfDPQhxV4weTqScmzlIxj0csrq2vrG2iLdFoYo80sbNSc2uw7t6hNd2IPHI9DRPsl/Ihm5y3QADwaAM0/dXl0N8JdY4AOgAGugALQ3OBg3xSR7PeYATy+Pz+AO0QPUwIAmpDobi4Y8crN5gAvVG/f7FQEhBDAgBa+KxMIZcKG0hg2BotQAFsCAMoAR14wCYHzA3ypAIAVO9KeiaQBqdAoyVo6klOVqqWKkoqinq6U0uWG3Wa3oDVCDFCoGD2dD5XhGQrAHYxfZ2Jz4Ib2917OLORGvN7uYMlJFh0mvMl3aQPR7AXl5MHhN5ExPJwS48JIjP+JMppnaMn59A230O8PocF4dD8XTAbyOxvNm2cqvRkp4usNpst/vt4h+6tM3utgdt61AA==))

However, same code with recent version of Roslyn, compiles to IL where defensive copy is not made. ([sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAofAAhwIHZSBvU8pyggNkoBZyBZCNAOwAUVAAwBtALrkICAOZQAlKQCQDEsw3kAbjPIAHAPYCYBcgF5y/OAHceAVxgRgGOAAUj/GAGYAIoJFI5AFBCgDcjJpMOgj6HjB45pY29o7ObnG+ggSB2eQEYaQRkdHkACZosBD8AMZwiQDCEBjVdhgQ8D4VjjVwggKxxrn9hsZ4BSTKAL5F5DN6CGg68CzspQZ2aeSNza3tcJ2VPX38KU4u7sa+A55DJ9wOZ+mXPtfxShNqkUxrGy7kAB6dABmQMQcB6iRGNwAdAANcgAWleeDh4XUXx+mwAnsDQQhwbVIXECNCAJqI5FktFfMrrTYAL1xYIhFihJmhAC0KWyURy0TMNDhqDx2gALaEAZQAjggYIJAWgQczCQAqAFM/EQgDU5BxirxBLqar1Ss1hJ1jP1yqN5EtpsN4ympGmJFIOC85FgCDs1RgpzSF08vnoM3d/vOGT8mL+/0C0bqWLjdL+9PeGk+XxgooqcMS/2pmezUDJiSxBciWZzXIs9PL5BdoY98fI8Lo5FkcBgoU9ne7LsFTeTdXJbY7XZ74/7zDDza5o97E77zqAA==))

If mutable struct uses non-auto-properties, then defensive copies are made regardless of compiler version. ([sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAofAAhwIHZSBvU8pyggNkoBZyBZCNAOwAUVAAwBtALrkICAOZQAlKQCQDEsw3kAbjPIAHAPYCYBcgF5y/OAHceAVxgRgGOAAUj/GAGYAIoJFI5AFBCgDcjJpMOgj6HjB45pY29o7ObnG+ggSB2eQEYaQRkdHkACZosBD8AMZwiQDCEBjVdhgQ8D4VjjVwggKxxrn9hsZ4BSTKAL5F5DN6CGg68CzspQZ2aeSNza3tcJ2VPX38KU4u7sa+A55DJ9wOZ+mXPtfxShNqkUxrGy7kAB6dABmQMQcB6iRGNwAdAANcgAWleeDh4XUXx+mwAnsDQQhwbVIXECNCAJqI5FktFfMrrTYAL1xYIhFihJmhAC0KWyURy0TMNDhqDx2gALaEAZQAjggYIJAWgQczCQAqAFM/EQgDU5BxirxBLqar1Ss1hJ1jP1yqN5EtpsN4ympGmJFIOC85FgCDs1RgpzSF08vnocwWSzqmL+AH1/qFZuimO7/ecMn5I3V/oF07qs3S/vT3hpPl8YKKKtCY4lYwLmKXy+SLFjqSWy1BOYl6c2mC6Zkns/C6ORZHA/WYAHzkGNxqAj8wTysWHQYOxwOMuwUe7PkwfDmDTkdr3ubvN1Lk7g+ei8uyZAA=))

Btw, I can see this behavior in .NET Core 2.1 app (C# 7.3) created in VS 2019.

Is there some kind of optimization in place when auto-properties are used ? Is this behavior documented anywhere ? If so can we refer to it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#never-use-mutable-structs-as-in-in-argument)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Ping @jcouv 

Are there optimizations in place for the behavior described above?

I'm hesitant to update this article *unless* those optimizations are something we want to guarantee in future versions. Thoughts?

**Comment by jcouv** [comment]
Tagging @rikkigibson

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/csharplang/blob/1f8c618f4ba42e8962bd1acb5f18bf36c2c550a1/proposals/csharp-8.0/readonly-instance-members.md

> Readonly can be applied to some auto-implemented properties, but it won't have a meaningful effect. **The compiler will treat all auto-implemented getters as readonly** whether or not the readonly keyword is present.

This only applies when the project is built with C# 8 or later. Perhaps we should also revise the spec to be clear about this.

**Comment by gmanvel** [comment]
@RikkiGibson thanks for reference. From what I understand it applies to projects built with C# 8 or later, I can see this behavior in the .NET Core 2.1 project built with C# 7.3.

Reproducible code in [sharplab.io.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAofAAhwIHZSBvU8pyggNkoBZyBZCNAOwAUVAAwBtALrkICAOZQAlKQCQDEsw3kAbjPIAHAPYCYBcgF5y/OAHceAVxgRgGOAAUj/GAGYAIoJFI5AFBCgDcjJpMOgj6HjB45pY29o7ObnG+ggSB2eQEYaQRkdHkACZosBD8AMZwiQDCEBjVdhgQ8D4VjjVwggKxxrn9hsZ4BSTKAL5F5DN6CGg68CzspQZ2aeSNza3tcJ2VPX38KU4u7sa+A55DJ9wOZ+mXPtfxShNqkUxrGy7kAB6dABmQMQcB6iRGNwAdAANcgAWleeDh4XUXx+mwAnsDQQhwbVIXECNCAJqI5FktFfMrrTYAL1xYIhFihJmhAC0KWyURy0TMNDhqDx2gALaEAZQAjggYIJAWgQczCQAqAFM/EQgDU5BxirxBLqar1Ss1hJ1jP1yqN5EtpsN4ympGmJFIOC85FgCDs1RgpzSF08vnoM3d/vOGT8mL+/0C0bqWLjdL+9PeGk+XxgooqcMS/2pmezUDJiSxBciWZzXIs9PL5BdoY98fI8Lo5FkcBgoU9ne7LsFTeTdXJbY7XZ74/7zDDza5o97E77zqAA==)

**Comment by svick** [comment]
@gmanvel As I understand it, the copy is avoided if the *struct* was compiled using C# 8.0.

E.g.:

```c#
// lib:
public struct S
{
    public int X { get; set; }
}

// app:
class Program
{
    static int M(in S s) => s.X;
}
```

If I compile lib with C# 8.0 and app with C# 7.3, the IL for `M` is:

```il
    IL_0000: ldarg.0      // s
    IL_0001: call         instance int32 [lib]S::get_X()
    IL_0006: ret
```

If I compile lib with C# 7.3 and app with C# 8.0, the IL is:

```il
    IL_0000: ldarg.0      // s
    IL_0001: ldobj        [lib]S
    IL_0006: stloc.0      // V_0
    IL_0007: ldloca.s     V_0
    IL_0009: call         instance int32 [lib]S::get_X()
    IL_000e: ret
```

Maybe that's the situation you're in? If not, can you provide repro code? (SharpLab master uses C# 8.0, so that doesn't count.)

**Comment by gmanvel** [comment]
@svick no, not the same situation.

To reproduce:
Visual Studio Professional 2019 (version 16.1.6)
Create a new .NET Core 2.1 console application, set language to 7.3 (Project Properties -> Build -> Advanced -> Language version: C# 7.3)

```
namespace CSharpTestsVs2019
{
    using System;
    class Program
    {
        static void Main(string[] args)
        {
            var s = new S(0);
            
            PrintS(in s);
        }

        private static void PrintS(in S s)
        {
            Console.WriteLine(s.X);
        }
    }

    public struct S
    {
        public S(double x)
        {
            this.X = x;
        }

        public double X { get; set; }
    }
}
```

Generated IL I see (for _Release_ build):
```
.method private hidebysig static void
    Main(
      string[] args
    ) cil managed
  {
    .entrypoint
    .maxstack 2
    .locals init (
      [0] valuetype CSharpTestsVs2019.S s
    )

    // [8 13 - 8 30]
    IL_0000: ldloca.s     s
    IL_0002: ldc.r8       0.0
    IL_000b: call         instance void CSharpTestsVs2019.S::.ctor(float64)

    // [10 13 - 10 26]
    IL_0010: ldloca.s     s
    IL_0012: call         void CSharpTestsVs2019.Program::PrintS(valuetype CSharpTestsVs2019.S&)

    // [11 9 - 11 10]
    IL_0017: ret

  } // end of method Program::Main

  .method private hidebysig static void
    PrintS(
      [in] valuetype CSharpTestsVs2019.S& s
    ) cil managed
  {
    .param [1]
    .custom instance void [System.Runtime]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor()
      = (01 00 00 00 )
    .maxstack 8

    // [15 13 - 15 36]
    IL_0000: ldarg.0      // s
    IL_0001: call         instance float64 CSharpTestsVs2019.S::get_X()
    IL_0006: call         void [System.Console]System.Console::WriteLine(float64)

    // [16 9 - 16 10]
    IL_000b: ret

  } // end of method Program::PrintS
```

![screenshot](https://user-images.githubusercontent.com/11509911/62940127-28b1c980-bdd3-11e9-9b7e-1408c94fde36.JPG)

**Comment by svick** [comment]
@gmanvel Ok, I can reproduce that with Roslyn 3.1.0 (which is the version used by VS 16.1), but not in Roslyn 3.2.0 (which is used by VS 16.2).

As far as I can tell, this is a bug that was fixed by @RikkiGibson in https://github.com/dotnet/roslyn/pull/35213. If you want to see the correct behavior, you should update your version of Visual Studio.

**Comment by gmanvel** [comment]
@svick thank you, updating VS now shows the correct behavior. 
Closing the ticket.
