### ISSUE TITLE
hhhhh

### ISSUE THREAD

**Issue by 2333hh** [dotnet/docs#13517]
hi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9491cf7-9be8-f55d-1e55-cdfb4316fe86
* Version Independent ID: fd533ab6-173d-58a4-dac8-9eb6b5ef7c20
* Content: [Install the .NET Framework on Windows XP](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-xp?utm_source=getdotnet&utm_medium=referral#feedback)
* Content Source: [docs/framework/install/on-windows-xp.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/on-windows-xp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
No feedback comment was provided. Closing.
