### ISSUE TITLE
JsonEncodedText.Encode methods have an additional JavaScriptEncoder argument

### ISSUE THREAD

**Issue by steveharter** [dotnet/docs#13513]
Starting in .NET Core 3.0 Preview 8, the JsonEncodedText.Encode() methods contain an optional JavaScriptEncoder argument. 

This is a binary breaking change only: a re-compile will fix any runtime issues.

### Version introduced

.NET Core 3.0 Preview 8

#### Old behavior
```csharp
namespace System.Text.Json
{
    public readonly struct JsonEncodedText
    {
        public static JsonEncodedText Encode(ReadOnlySpan<byte> utf8Value);
        public static JsonEncodedText Encode(ReadOnlySpan<char> value);
        public static JsonEncodedText Encode(string value);
    }
}
```

#### New behavior
```csharp
namespace System.Text.Json
{
    public readonly struct JsonEncodedText
    {
        public static JsonEncodedText Encode(ReadOnlySpan<byte> utf8Value, JavaScriptEncoder encoder = null);
        public static JsonEncodedText Encode(ReadOnlySpan<char> value, JavaScriptEncoder encoder = null);
        public static JsonEncodedText Encode(string value, JavaScriptEncoder encoder = null);
    }
}
```

#### Reason for change

This change was made to allow for a different or custom encoder.

### Recommended action

Re-compile against Preview 8.

### Category
- CoreFx

### Affected APIs
[`JsonEncodedText.Encode(ReadOnlySpan<byte> utf8Value)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonencodedtext.encode?view=netcore-3.0#System_Text_Json_JsonEncodedText_Encode_System_ReadOnlySpan_System_Byte_)
[`JsonEncodedText.Encode(ReadOnlySpan<char> value)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonencodedtext.encode?view=netcore-3.0#System_Text_Json_JsonEncodedText_Encode_System_ReadOnlySpan_System_Char_)
[`JsonEncodedText.Encode(string value)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonencodedtext.encode?view=netcore-3.0#System_Text_Json_JsonEncodedText_Encode_System_String_)
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some minor changes to the issue, @steveharter. Please review them.

**Comment by ahsonkhan** [comment]
It's also worth mentioning that `JsonEncodedText` is a new type as part of .NET Core 3.0 and the breaking change described here is only breaking between **3.0 preview 7** and **3.0 preview8+** (and not between previous .NET Core versions that shipped and 3.0).

Similar to https://github.com/dotnet/docs/issues/13469

**Comment by mairaw** [comment]
We don't document breaking changes between previews.

**Comment by ahsonkhan** [comment]
> We don't document breaking changes between previews.

preview 7 was considered "go-live", so I was told we should document breaking changes between it and 3.0 RTM.

**Comment by mairaw** [comment]
Ok, I'll leave this to @rpetrusha to comment here since he's more familiar with this process than I am.
