### ISSUE TITLE
Reference, ProjectReference, FrameworkReference docs

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/docs#13521]
There should be documentation explaining the workings and usage for `Reference`, `PackageReference`, `ProjectReference`, `LibraryReference` and `FrameworkReference` items.

Are these on track for the .NET Core 3.0 docs update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8166ec-177f-67e5-7e98-2190ea82e0b0
* Version Independent ID: d6573a5f-4eb4-21c1-4d4f-50ef0f4723ae
* Content: [Packages, metapackages and frameworks - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/packages)
* Content Source: [docs/core/packages.md](https://github.com/dotnet/docs/blob/master/docs/core/packages.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
We have a long ongoing issue related pointing out that we need to document the CSPROJ settings related to MSBuild and the .NET Core SDKs #2642

**Comment by Thraka** [comment]
Closing this as I feel like this is covered by the linked issue. The issue you filed here is now linked to it.
