### ISSUE TITLE
Can't train with GPU and not nave progress status when training large data set 

### ISSUE THREAD

**Issue by pinyo-rungoral** [dotnet/docs#13523]
- I did replace data set with fruits 360 data set from kaggle web site and then try to training.  at Task-manager i see NVIDIA GPU not used to train.
- When training with large data set  i would like to see training progress like training with keras on python.Can you explain me about how to show it?

Yours Respectfully 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Retrain TensorFlow image classifier - transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Hi @pinyo-rungoral ,

Thanks for your question. Since this is more of a product question, I suggest asking these questions in the [dotnet/machinelearning repo](https://github.com/dotnet/machinelearning).
