### ISSUE TITLE
Undocumented prerequisite

### ISSUE THREAD

**Issue by pjt33** [dotnet/docs#13537]
I followed the "Individual components" instructions, and when I tried to create the project I received an error because

&gt; subtype "82b43b9b-a64c-4715-b499-d71e9ca2bd60" is unsupported

and so it couldn't create the MakeConst.Vsix project.

It turns out that in addition to the listed components, it's also necessary to install **Visual Studio SDK** from the "SDKs, libraries, and frameworks" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this and reporting it.

I've added it to our backlog to fix when we next update this article.
