### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by WangZixuan** [dotnet/docs#13532]
HelpAttribute class is declared while `[Help("...")]` is used in the example. It is an error, please fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adab8285-18b5-04e4-1070-6edf45b5b5db
* Version Independent ID: 395b4146-4601-558d-c94d-4997879f74d5
* Content: [C# Attributes - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/attributes#feedback)
* Content Source: [docs/csharp/tour-of-csharp/attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/attributes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @WangZixuan but that's not an error, attributes can be declared like this. For more information, see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-classes.
