### ISSUE TITLE
Add uninstall instructions installations done via dotnet-install scripts

### ISSUE THREAD

**Issue by atifaziz** [dotnet/docs#13535]
This page is missing instructions for installations done via [dotnet-install scripts]. Consider adding them please for each platform and when:

- the `-InstallDir ` option is used and the default behaviour otherwise (where it installs under `%LocalAppData%\Microsoft\dotnet` on Windows)
- the `-NoPath` option isn't specified (which I assume requires manual clean-up of the path)

[dotnet-install scripts]: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Remove the .NET Core runtime and SDK - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
