### ISSUE TITLE
.NET Core 3.0 disallows custom EncoderFallbackBuffer instances from falling back recursively

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/docs#13548]
## .NET Core 3.0 disallows custom EncoderFallbackBuffer instances from falling back recursively

Custom `EncoderFallbackBuffer` instances may no longer fall back recursively. The implementation of `EncoderFallbackBuffer.GetNextChar` must result in a character sequence that is convertible to the destination `Encoding`. Otherwise, an exception will occur.

### Version introduced

3.0

### Change description

In previous versions of .NET Core and .NET Framework, custom implementations of `EncoderFallbackBuffer.GetNextChar` could return character sequences that were not convertible to the destination encoding. The runtime would recursively call into the custom `EncoderFallbackInstance` until either the encoder produced a valid convertible sequence or the maximum stack depth was reached. 

In .NET Core 3.0, custom implementations of `EncoderFallbackBuffer.GetNextChar` must return character sequences that are convertible to the destination encoding, because the runtime will no longer make recursive calls back into this type.

This behavior _only_ applies when **all three** of the following conditions are met:

1. The runtime detects an ill-formed UTF-16 sequence or a UTF-16 sequence that cannot be converted to the target encoding.
2. A custom `EncoderFallback` has been specified.
3. The custom `EncoderFallback` attempts to substitute a new ill-formed or nonconvertible UTF-16 sequence.

#### Old behavior

During a chars-to-bytes transcoding operation, the runtime detects ill-formed or nonconvertible UTF-16 sequences and provides those characters to the `EncoderFallbackBuffer.Fallback` method. The `Fallback` method determines which characters should be substituted for the original nonconvertible data, and these characters are drained via calling `EncoderFallbackBuffer.GetNextChar` in a loop.

The runtime then attempts to transcode these substitution characters to the target `Encoding`. If this succeeds, the runtime continues transcoding from where it left off in the original input string. If the substituted characters cannot be transcoded to the target `Encoding`, the runtime invokes the `EncoderFallbackBuffer.Fallback` method once again with the substitution characters, expecting the `EncoderFallbackBuffer.GetNextChar` method to return a new substitution sequence.

This process continues until the runtime eventually sees a well-formed, convertible substitution or until a maximum recursion count is reached.

#### New behavior

During a chars-to-bytes transcoding operation, the runtime detects ill-formed or nonconvertible UTF-16 sequences and provides those characters to the `EncoderFallbackBuffer.Fallback` method. The `Fallback` method determines which characters should be substituted for the original nonconvertible data, and these characters are drained via calling `EncoderFallbackBuffer.GetNextChar` in a loop.

The runtime then attempts to transcode these substitution characters to the target `Encoding`. If this succeeds, the runtime continues transcoding from where it left off in the original input string. If the substituted characters cannot be transcoded to the target `Encoding`, an `ArgumentException` is thrown. The runtime does not make recursive calls into the `EncoderFallbackBuffer` instance.

#### Reason for change

This is part of a larger effort to improve UTF-8 and Unicode text handling throughout .NET.

### Recommended action

Most developers needn't take any action.

If an application uses a custom `EncoderFallback` and `EncoderFallbackBuffer` class, ensure the implementation of `EncoderFallbackBuffer.Fallback` populates the fallback buffer with well-formed UTF-16 data which is directly convertible to the target `Encoding` when the `Fallback` method is first invoked by the runtime.

### Category

Core

### Affected APIs

- [EncoderFallbackBuffer.Fallback](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoderfallbackbuffer.fallback)
- [EncoderFallbackBuffer.GetNextChar](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoderfallbackbuffer.getnextchar)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some edits, @GrabYourPitchforks. Could you review them, please?

**Comment by rpetrusha** [comment]
@GrabYourPitchforks, do we need to note the preview version in which this change was introduced?
