### ISSUE TITLE
Delimiter of PackageTags

### ISSUE THREAD

**Issue by jnyrup** [dotnet/docs#13553]
This page specifies that PackageTags should be semi-colon delimited.
whereas 
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#important-nuget-package-metadata
specifies that is should be space-delimited.

What the right way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packagetags)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Good catch @jnyrup! From what I can see [here](https://github.com/dotnet/machinelearning/pull/701/commits/d38c9d148eeae4fbb7bdf9c46e3ead957dd866c0), it seems the right one would be space-delimited. 

@karann-msft can you confirm?

**Comment by karann-msft** [comment]
NuGet docs say - space delimited
https://docs.microsoft.com/en-us/nuget/reference/nuspec#tags

**Comment by mairaw** [comment]
That article does but then this one doesn't https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target so I wasn't sure.

**Comment by karann-msft** [comment]
@nkolev92 do u know if tags in csproj are semi-colon or space-delimited?

**Comment by nkolev92** [comment]
It's inconsistent. 

Both are technically correct in their own use case. 

A bit of background.

The nuspec schema defines tags as just a string. They are a free form string that different galleries might handle differently. 
For example nuget.org splits on both spaces and semi-colons. 
The one thing we agree on is that tags are one word.

The tags in the nuspec are space separated, so multi word tags are not really a thing. 
The PackageTags element in the csproj will simply combine the semi colon delimited tags at pack time and generate something like "semver semantic versioning" from "semver;semantic versioning". The reason for the semi colon delimiter in csproj is driven by MSBuild's special character `@` https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019#special-characters that can help make an item group a string of ; concatenated values.

**Comment by mairaw** [comment]
Thanks @nkolev92. A bit confusing but I believe that both articles are then correct here and on NuGet docs. So I closed my PRs.
