### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by zodiacon** [dotnet/docs#13554]
The header where ICLRProfiling is defined is metahost.h
Also, it's worth mentioning the CLSID used to create the object implementing this interface (CLSID_CLRProfiling)

Pavel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5908f268-6791-5a9a-96e3-76af69eedb5f
* Version Independent ID: fe69a09f-7c94-19cb-9961-bd136587199c
* Content: [ICLRProfiling Interface](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/iclrprofiling-interface#feedback)
* Content Source: [docs/framework/unmanaged-api/profiling/iclrprofiling-interface.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/iclrprofiling-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @zodiacon. @tommcdon can you help with this feedback about one of the profiling unmanaged APIs?

**Comment by tommcdon** [comment]
@davmason can you take a look?
