### ISSUE TITLE
Why there is no extension method for this logic?

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#13550]
I expect something like this:

```csharp
public static async Task DoForEach<T>(this List<Task<T>> tasks, Action<T> action)
{
    var _tasks = new List<Task<T>>(tasks);

    while (_tasks.Count > 0)
    {
        var finished = await Task.WhenAny(_tasks);

        _tasks.Remove(finished);

        action(await finished);
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d15bb1b-5f7f-20f3-78c3-d2b5bce950ed
* Version Independent ID: 80bee493-257b-5c64-4f28-cfb4e9bae560
* Content: [Process asynchronous tasks as they complete](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete)
* Content Source: [docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hi,

Unfortunately this is not the place to make code suggestions as this repository is only related to documentation 😃 

You can always open up a pull request in the .NET Core repository. That repository is located at https://github.com/dotnet/corefx
