### ISSUE TITLE
Support for reference return values (Visual Basic)

### ISSUE THREAD

**Issue by lds0m01** [dotnet/docs#13566]
How will the function FindNext look in VB? Will it be:
Function FindNext(StartWithString as String, ByRef Found as boolean) as Ref String

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79aab2e-8c3d-2878-14ff-064e098db357
* Version Independent ID: 0b7fbd1d-eb37-c6f8-25cc-100a63e7623b
* Content: [Ref Return Values (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/ref-return-values#feedback)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/ref-return-values.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/ref-return-values.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
As the article states in the introduction:
"Visual Basic does not allow you to author methods with reference return values, but it does allow you to consume reference return values. "

So there's no VB equivalent for that.
