### ISSUE TITLE
Training progress 

### ISSUE THREAD

**Issue by timm2006** [dotnet/docs#13568]
Hello
With the Fit() training method, is it possible to get a progress event of the training so that a progress bar can be updated with an % estimate of the progress through the training. When training a model, I have no idea whether it will take a couple of mins or hours. Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf439ea-a2b3-1606-2b82-c65935af2c3f
* Version Independent ID: b4cefe23-d5cd-dd6a-93a0-3820f1314acc
* Content: [Train and evaluate a model - ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/train-machine-learning-model-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/train-machine-learning-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by JRAlexander** [comment]
Hi @timm2006,
Thanks for your question. Since this is more of a product question, I suggest asking these questions in the [dotnet/machinelearning repo](https://github.com/dotnet/machinelearning)..
