### ISSUE TITLE
optional named params?

### ISSUE THREAD

**Issue by drdamour** [dotnet/docs#13567]
any reason the section on overloads doesn't recommend or mention have cancellation and progress being implemeted as optional named params?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40c0699-0e7c-e20d-98c1-76f0520ab9c2
* Version Independent ID: 0fc31902-0055-f9e8-a228-e7a0ce384e35
* Content: [Task-based Asynchronous Pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap#feedback)
* Content Source: [docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@drdamour It's not clear to me what you're asking -- could you please elaborate?

**Comment by drdamour** [comment]
instead of having to implement 4 methods...why not recommend implementors use optional named parameters for cancellationToken (defaulting to https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.none?view=netframework-4.8) and progress defaulting to null.  These weren't options when this article was written back in older .net versions,  but now it's the easiest way to implement all 4 recommended signatures in a single method.

**Comment by tdykstra** [comment]
@drdamour Thanks for the suggestion -- I'm adding this to our backlog.
