### ISSUE TITLE
prediction.Area always null

### ISSUE THREAD

**Issue by jasonnator** [dotnet/docs#13574]
### Just trained model
[Line 126](https://github.com/dotnet/samples/blob/3384b4ebda383ac8305d8741125b7791d48c4ee4/machine-learning/tutorials/GitHubIssueClassification/Program.cs#L126)
```
            Console.WriteLine($"=============== Single Prediction just-trained-model - Result: {prediction.Area} ===============");
```
### Trained model loaded from disk
[Line 189](https://github.com/dotnet/samples/blob/3384b4ebda383ac8305d8741125b7791d48c4ee4/machine-learning/tutorials/GitHubIssueClassification/Program.cs#L189)
```
            Console.WriteLine($"=============== Single Prediction just-trained-model - Result: {prediction.Area} ===============");
```

[AB#1572600](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1572600)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Hi @jasonnator 

Is this still an issue? Could you provide more information? I was unable to replicate the issue. I would suggest comparing against the [completed sample](https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/GitHubIssueClassification).

**Comment by jasonnator** [comment]
It is. I have pulled the repo as a zip, compile, run, exact same problem. Other examples are working fine but both with the concatenate fail in the same way.

**Comment by luisquintanilla** [comment]
Thanks for that information. I tried pulling the repo as a zip and was still unable to replicate. Would you mind posting your code?
