### ISSUE TITLE
Getting started ... in what development environment?

### ISSUE THREAD

**Issue by rogercoder** [dotnet/docs#13578]
I am interested in writing a desktop Windows app and heard that Winforms is a good way to go. I came to this "Getting Started with Windows Forms" page hoping to get some info about how to start ... and yet I can't find where it even mentions a development environment. Do I need some version of Visual Studio? Help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82facee6-f1e6-f2aa-56c2-967708b2389f
* Version Independent ID: cb2a1803-98a7-7900-bf20-281b6c55197e
* Content: [Getting Started with Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/getting-started-with-windows-forms#feedback)
* Content Source: [docs/framework/winforms/getting-started-with-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/getting-started-with-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Yes, you need Visual Studio to develop WinForms applications. It's been available for many versions of Visual Studio if you want to use .NET Framework for your development. We're revisiting the WinForms documentation for the next release of .NET Core, so the prerequisites should be made more clear as well as having better get started materials.

For new development though, we do recommend that people use .NET Core to develop new applications with. @OliaG can you comment on the state of the designers on Visual Studio if folks want to develop a new WinForms app?
