### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#13580]
The example in the `How to: Use Finally Blocks` isn't really useful.
If I put the line in `finally` block outside the whole `try-catch-finally` block and remove the `finally` part, The control flow would be exactly the same. Currently, I can't get a good example to make a PR, but something that returns a value from a function in the `try` block seems better to me.

*Edit:* I think re-throwing the exception is even better than returning from the `try` to show how `finally` block can be useful.
I'm going to make a PR now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1202a39-a94a-c97d-ffb8-2d25a13245f4
* Version Independent ID: 4092d5d3-f69a-cf78-3164-0c423947d2eb
* Content: [How to: Use Finally Blocks](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-finally-blocks#feedback)
* Content Source: [docs/standard/exceptions/how-to-use-finally-blocks.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-use-finally-blocks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. Since you've already filed a PR I'll comment over there. Thanks!
