### ISSUE TITLE
Add an alternative to Fuslogvw.exe

### ISSUE THREAD

**Issue by awaescher** [dotnet/docs#13584]
I was wondering if the [docs to the Fuslogvw.exe Assembly Binding Log Viewer](https://docs.microsoft.com/en-gb/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) could also point to 3rd-party tools (free or even open source only, of course) helping the developers using the .NET platform to track down binding issues.

I wrote [Fusion++ here on GitHub](https://github.com/awaescher/Fusion) but did not promote it much. Back in May, Scott Hanselman [featured it on Twitter](https://twitter.com/shanselman/status/1126602908231819265) and added an update note to [his personal blog](https://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx). So I think it might be of interest to you and other developers as well.

![GitHubCover](https://user-images.githubusercontent.com/3630638/61956728-02f88800-afbe-11e9-89d6-2c26445aa9ef.png)

How to add that in the docs … hm … let’s see …

I don’t see a real table of content to add it to. So maybe there could be a hint just like Scott did it linking to the GitHub project. I just added a green “Note”-block in which a hint could be displayed.

![image](https://user-images.githubusercontent.com/3630638/61956286-135c3300-afbd-11e9-8b3d-8e0043e340c6.png)

I did not write anything into that block, because I don’t really think that you want to add GitHub projects to the docs. But if you don't categorically refuse to do it, I'm happy to help out.

Just let me know if you want me to continue.

Thanks 🥳

**Comment by rpetrusha** [comment]
Thanks for letting us know about Fusion++, @awaescher. Unfortunately, we don't link to external software from the official Microsoft documentation on docs.microsoft.com. We'd welcome a pull request to add it to the list of Open Source projects in [the Tools section of .NET Open Source Developer Projects](https://github.com/microsoft/dotnet/blob/master/dotnet-developer-projects.md#tools).

**Comment by awaescher** [comment]
I was expecting that and it's perfectly fine. I'm going to add it there, thanks.
