### ISSUE TITLE
When the object is eligible for finalization

### ISSUE THREAD

**Issue by adamshakhabov** [dotnet/docs#13583]
I am reading an article [Finalizers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors) right now that contains the following statement:

> When the object is **eligible** for finalization

It is mean "If object class **has defined finalizer**"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I think that is implied. Consider the paragraph above:

>The programmer has no control over when the finalizer is called because this is determined by the garbage collector. The garbage collector checks for objects that are no longer being used by the application. **If it considers an object eligible for finalization, it calls the finalizer (if any) and reclaims the memory used to store the object.**

I think eligibility is based on two things: (1) the object has a finalizer defined (2) the object is ready for garbage collection.

I think the description is accurate. Please let me know if this answered your question.

**Comment by adamshakhabov** [comment]
@Thraka, thanks for clearing that up!
