### ISSUE TITLE
[Code Gallery] Migrate Async Sample: Fine Tuning Your Application 

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13599]
## Migrate Async Sample: Fine Tuning Your Application 

Related to #12511 

**Sample URL**

https://code.msdn.microsoft.com/Async-Fine-Tuning-Your-a676abea

**Sample information**

The sample has 21,671 downloads and a 4.0 rating (as of 7/2019). 

It was last updated on 2/26/2013. The sample will need review and updating.

**Usage**

- docs\csharp\programming-guide\concepts\async\cancel-an-async-task-or-a-list-of-tasks.md
- docs\csharp\programming-guide\concepts\async\cancel-async-tasks-after-a-period-of-time.md
- docs\csharp\programming-guide\concepts\async\cancel-remaining-async-tasks-after-one-is-complete.md 
- docs\csharp\programming-guide\concepts\async\fine-tuning-your-async-application.md
- docs\csharp\programming-guide\concepts\async\start-multiple-async-tasks-and-process-them-as-they-complete.md
- docs\csharp\programming-guide\concepts\async\task-asynchronous-programming-model.md
- docs\visual-basic\programming-guide\concepts\async\index.md
- docs\visual-basic\programming-guide\concepts\async\cancel-an-async-task-or-a-list-of-tasks.md
- docs\visual-basic\programming-guide\concepts\async\cancel-async-tasks-after-a-period-of-time.md
- docs\visual-basic\programming-guide\concepts\async\cancel-remaining-async-tasks-after-one-is-complete.md
- docs\visual-basic\programming-guide\concepts\async\fine-tuning-your-async-application.md
- docs\visual-basic\programming-guide\concepts\async\start-multiple-async-tasks-and-process-them-as-they-complete.md

**Comment by Youssef1313** [comment]
Hi, @rpetrusha .
Can you guide me if this sample is available on github to make some changes to it ?
Or I should share them here in this issue ?

**Comment by rpetrusha** [comment]
Hi @Youssef1313. No, the sample is not available on github; it's only available in [CodeGallery](https://code.msdn.microsoft.com/Async-Fine-Tuning-Your-a676abea). This probably is as good a place as any, though, to list changes.

**Comment by Youssef1313** [comment]
@rpetrusha , I'm interested in updating this sample, can you give me a guide where it should exactly go in github ?
