### ISSUE TITLE
page contains self link

### ISSUE THREAD

**Issue by idbrii** [dotnet/docs#13594]
&gt; See also: [Working with XML Namespaces (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/namespaces-overview-linq-to-xml)

This is a link back to this page. A page that actually showed Working with XML Namespaces in C# would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289bcba9-b68b-ac37-3461-691215ef5860
* Version Independent ID: 45d26a2b-dcda-32ff-1c38-1550de29d034
* Content: [Namespaces Overview (LINQ to XML)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/namespaces-overview-linq-to-xml)
* Content Source: [docs/csharp/programming-guide/concepts/linq/namespaces-overview-linq-to-xml.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/namespaces-overview-linq-to-xml.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback. Opened PR #13597 to fix this.
