### ISSUE TITLE
EnvelopedCms defaults to AES-256 encryption

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#13598]
## EnvelopedCms defaults to AES-256 encryption

The default symmetric encryption algorithm used by EnvelopedCms has been changed from TripleDES to AES-256

### Version introduced

3.0 Preview 8 (System.Security.Cryptography.Pkcs 4.6.0)

### Change description

When EnvelopedCms is used to encrypt data without specifying a symmetric encryption algorithm via a constructor overload, the data was previously encrypted with the TripleDES/3DES/3DEA/DES3-EDE algorithm.

Starting with .NET Core 3.0 Preview 8 (via version 4.6.0 of the System.Security.Cryptography.Pkcs NuGet package), the default algorithm has been changed to AES-256 for algorithm modernization.

#### Old behavior

In this sample code, the data is encrypted with TripleDES

```C#
EnvelopedCms cms = new EnvelopedCms(content);
cms.Encrypt(recipient);
return cms.Encode();
```

#### New behavior

For the same sample, the data is encrypted with AES-256.

If a message recipient certificate has a (non-EC) Diffie-Hellman public key, the encryption operation may fail with a `System.Security.Cryptography.CryptographicException` due to limitations in the underlying platform.

#### Reason for change

Improving the security of default options.

### Recommended action

If you are negatively impacted by the change, you can restore TripleDES encryption by explicitly specifying the encryption algorithm identifier via an EnvelopedCms constructor, such as:

```C#
Oid tripleDesOid = new Oid("1.2.840.113549.3.7", null);
AlgorithmIdentifier tripleDesIdentifier = new AlgorithmIdentifier(tripleDesOid);
EnvelopedCms cms = new EnvelopedCms(content, tripleDesIdentifier);

cms.Encrypt(recipient);
return cms.Encode()l
```

### Category

CoreFx

### Affected APIs

[EnvelopedCms..ctor(ContentInfo)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs.envelopedcms.-ctor?view=netcore-3.0#System_Security_Cryptography_Pkcs_EnvelopedCms__ctor_System_Security_Cryptography_Pkcs_ContentInfo_)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some minor changes, @bartonjs. Could you review them, please?

**Comment by bartonjs** [comment]
LGTM
