### ISSUE TITLE
How to resolve assemblies for custom tool?

### ISSUE THREAD

**Issue by doctorcode-co** [dotnet/docs#13608]
Hi;
I create a custom tool like EF tool for generate javascript class from my c# models. I can find and build project then load final created assembly:
```
public int Build()
{
    AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve; ;

    var targetDir = Path.GetFullPath(Path.Combine(_projectDir, _outputPath));
    var startupTargetPath = Path.Combine(targetDir, _targetFileName);
    var assembly = Assembly.LoadFrom(startupTargetPath);
    var type = assembly.DefinedTypes.FirstOrDefault(t => t.IsClass && !t.IsAbstract && !t.IsGenericType && typeof(IDesignTimeStartup).IsAssignableFrom(t));

    if (type == null)
    {
        Reporter.WriteWarning($"No type that implements the `{typeof(IDesignTimeStartup)}` interface was found in Assembly `{assembly}`");
        return 0;
    }

    Reporter.WriteInformation($"The {type} found and will executed");

    var webHostBuilder = new WebHostBuilder();
    _webHost = webHostBuilder
        .UseContentRoot(_projectDir)
        .UseStartup(type)
        .Build();

    var moduleBuilder = _webHost.Services.GetRequiredService<IModuleBuilder>();
    moduleBuilder.Build();

    var templateBuilder = _webHost.Services.GetRequiredService<ITemplateBuilder>();
    templateBuilder.Build();

    return 0;
}
```
But when target assembly is loaded, none of its dependencies are resolved because there is no assembly in its directory. I use below code for resolve dependent assemblies:
```
private Assembly AssemblyResolve(object sender, ResolveEventArgs args)
{
    var targetDir = Path.GetFullPath(Path.Combine(_projectDir, _outputPath));
    var startupTargetPath = Path.Combine(targetDir, startupProject.TargetFileName);
    var assemblyName = new AssemblyName(args.Name);

    foreach (var extension in new[] { ".dll", ".exe" })
    {
        var path = Path.Combine(_startupTargetPath, assemblyName.Name + extension);
        if (File.Exists(path))
        {
            try
            {
                return Assembly.LoadFrom(path);
            }
            catch
            {
            }
        }
    }

    return null;
}
```
This is a complete log of run my tool:

> PS C:\Users\Alireza\Desktop\Karkoosh> mvcmagic build
> Search startup project in path: `C:\Users\Alireza\Desktop\Karkoosh`
> There are 2 projects in directory, Enter startup project index or press Enter key to exist:
> 0) DoctorCode.Karkoosh
> 1) DoctorCode.Karkoosh.Models
> 0
> 
> AssemblyName: DoctorCode.Karkoosh
> Language: C#
> OutputPath: bin\Debug\netcoreapp2.2\
> PlatformTarget: AnyCPU
> ProjectAssetsFile: C:\Users\Alireza\Desktop\Karkoosh\DoctorCode.Karkoosh\obj\project.assets.json
> ProjectDir: C:\Users\Alireza\Desktop\Karkoosh\DoctorCode.Karkoosh\
> ProjectName: DoctorCode.Karkoosh.csproj
> RootNamespace: DoctorCode.Karkoosh
> RuntimeFrameworkVersion:
> TargetFileName: DoctorCode.Karkoosh.dll
> TargetFrameworkMoniker: .NETCoreApp,Version=v2.2
> 
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.2.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by Thraka** [comment]
Hello!

I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. This question seems generic and not related to a specific documentation article.

I'm going to close the issue. 

Thanks.
