### ISSUE TITLE
Override in default interface members

### ISSUE THREAD

**Issue by prakash-manit** [dotnet/docs#13600]
I have learned that the default interface members are virtual under the hood. However, when I try to override them in concreate class, they are not recognized. Can someone suggest how these members can be overridden?

**Comment by Thraka** [comment]
Hello!

I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. Unfortunately this seems like a general support question and is not related to a documentation article.

I'm going to close the issue. 

Thanks.
