### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by glittle** [dotnet/docs#13609]
Need to specify the namespace needed to access Properties!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5addc541-9653-30b3-2b37-69efd88c897b
* Version Independent ID: f9889525-dea5-b822-dddf-32fca3a155f7
* Content: [How To: Read Settings at Run Time With C#](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-read-settings-at-run-time-with-csharp)
* Content Source: [docs/framework/winforms/advanced/how-to-read-settings-at-run-time-with-csharp.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-read-settings-at-run-time-with-csharp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
You shouldn't need to specify the namespace. When you create a project it uses the namespace that your project uses by default. As long as you are coding in a file that is using the same namespace as the project (the default namespace) then you don't need to specify the namespace. Otherwise, the namespace is the name of your project.

**Comment by glittle** [comment]
It would be good to mention that then. When using it in a razor file or files in a different namespace, the default namespace is not available. It was hard to find documentation that said to use the main assembly's namespace.

**Comment by Thraka** [comment]
OK. I'll open this issue back up and put it on the backlog.

However, this fix will be a low priority for us. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
