### ISSUE TITLE
Recommend to provide Deconstructor Overloads with distinct Number of Parameters and Discards

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/docs#13610]
Hi, in addition to warning about Deconstructor Overloads with the same Number of Parameters I would propose when a conflict happens to provide Overloads with more Parameters and discard them on deconstruction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct#feedback)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Closing as a product suggestion.
