### ISSUE TITLE
Setting nullable warnings context in csproj file

### ISSUE THREAD

**Issue by prakash-manit** [dotnet/docs#13617]
In tutorial: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types, There is mention of adding <Nullable>enable</Nullable> in csproj file? however its not clear if its nullable annotation context or nullable warnings context? Also, don't we have explicit ways to set both these contexts in csproj?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
It's based on the value you use for the `<Nullable>` 

https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

We generally don't cross link to a lot of reference or other material in a tutorial article as the point of the article is to stay in the context of the article and move on to the next steps. So it's not really appropriate to call out this information.

I'm going to close this issue. Thanks!
