### ISSUE TITLE
Create API topic for System.ValueTuple 

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1362]
There are a set of ValueTuple generic structures that are required to support the C# 7 Tuple language feature. These are currently delivered with the System.ValueTuple NuGet package. However, this assembly will be part of the application meta packages delivered with the RTM release of C# 7. 

This may be just a placeholder to ensure that we pull this class into the docs when we create the final API ref for this release. Or, we may need more work here.

/cc @mairaw @rpetrusha  @terrajobst

**Comment by rpetrusha** [comment]
[ValueTuple](https://msdnstage.redmond.corp.microsoft.com/en-us/library/system.valuetuple(v=vs.110).aspx), along with the generic [ValueType<>](https://msdnstage.redmond.corp.microsoft.com/en-us/library/system(v=vs.110).aspx) structures, are documented for the .NET Framework on the MSDN staging server. We should be able to migrate this content.

/cc @mairaw @rpetrusha @terrajobst

**Comment by jskeet** [comment]
Given that C# 7 has now fully shipped with VS 2017, I'd suggest expediting this migration.
(This has absolutely *nothing* to do with trying to write the 4th edition of C# in Depth and finding documentation easier to read than ildasm, of course. Perish the thought.)

**Comment by BillWagner** [comment]
@jskeet This would probably be easier than ILDASM: https://github.com/dotnet/corefx/tree/master/src/System.ValueTuple/src/System/ValueTuple

**Comment by jskeet** [comment]
Thanks on both counts :)

**Comment by rpetrusha** [comment]
These are now document on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-1.1.0&term=valuetuple).
