### ISSUE TITLE
Incorrect link - .NET Core link in prerequisites goes to a tutorial page

### ISSUE THREAD

**Issue by asajohnson** [dotnet/docs#13626]
The ".NET Core" link in the prerequisites page redirects to a .NET Hello World tutorial.

It's in this sentence:
You can find the installation instructions on the .NET Core page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq#feedback)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll investigate why it's forwarding to the tutorial and either fix this article or the forwarding link. Thanks!

Thanks again!

**Comment by Youssef1313** [comment]
From the right side in that hello world tutorial, there is a `Download and install` link and there is a choice for the OS, whether it's mac, windows or linux.
