### ISSUE TITLE
Download PDF error

### ISSUE THREAD

**Issue by PanosGeorgiadis** [dotnet/docs#13621]
The `Download PDF` link in the lower-left corner always renders the page with VB.NET code listings, never C#.
Browser is Firefox 68.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662955be-2dc4-6755-2009-5eee6a7be305
* Version Independent ID: 2826984a-02fa-0ba0-373d-c933ca7d0edc
* Content: [Passing Structures](https://docs.microsoft.com/en-us/dotnet/framework/interop/passing-structures#feedback)
* Content Source: [docs/framework/interop/passing-structures.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/passing-structures.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Youssef1313** [comment]
It has both C#, VB for me
![image](https://user-images.githubusercontent.com/31348972/62057916-cd070e00-b220-11e9-8cc6-a8a310bf1f88.png)

**Comment by PanosGeorgiadis** [comment]
agreed, i can see the c# code too
