### ISSUE TITLE
"In This Section" is not in sync with TOC

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#13631]
The linked topics under "In This Section" are not in sync with the current TOC. I suggest just removing "In This Section" or this entire topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1322e7-0e9c-56d4-bc95-4c071f44e89f
* Version Independent ID: 82ed1aa1-489f-88f5-b4da-4dc4ef2a59d5
* Content: [Advanced (Windows Presentation Foundation)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/#feedback)
* Content Source: [docs/framework/wpf/advanced/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @gewarren. Eventually, the page will be deleted as part of our work on modernizing the TOC. As a short-term measure, I've opened #13644 to update this topic so that it corresponds to the TOC.
