### ISSUE TITLE
Excellent page!!

### ISSUE THREAD

**Issue by thomasforth** [dotnet/docs#13636]
This is a really excellent page that has helped me improve the performance of my ML.NET models. It's a reminder of the power of great documentation. Thank you to all involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e7cf89-1a90-7693-db50-11b770c09160
* Version Independent ID: 21c26fd2-c6ad-2c2f-166b-03ac0590a1c2
* Content: [Make predictions with a trained model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by Thraka** [comment]
A big thank-you from Microsoft! 😄
