### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by hammamdiab** [dotnet/docs#13635]
In the PrimeService_IsPrimeShould.cs, the CreatePrimeService() methods returns a new instance of PrimerService class but the correct class name is PrimeService; in contains an extra 'r'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#feedback)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing out this code error, @hammamdiab. We've opened #13642 to fix it.
