### ISSUE TITLE
Events vague

### ISSUE THREAD

**Issue by fritzy** [dotnet/docs#13640]
The events section is rather vague, and doesn't contain any links to more information. For example, the EventHandler type itself is never described, the ?. operator isn't explained in this series at all IIRC, and the EventArgs type isn't described. If nothing else, a link to more information would be handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181f41d-b6ce-ad66-084e-8d2b514b87e2
* Version Independent ID: 494c4344-b752-4f86-5b66-1ef4b81c1e75
* Content: [Classes and Objects in C# - A tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#feedback)
* Content Source: [docs/csharp/tour-of-csharp/classes-and-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/classes-and-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue.

I'll assign this to @BillWagner as he's been revamping the C# language area. I'm not sure what he's going to do with the "Tour of C#" stuff, but a lot of it is duplicate information.

**If** this article stays around, it should definitely have links to more info under each concept section.
