### ISSUE TITLE
Error CS8701: Target runtime doesn't support default interface implementation.

### ISSUE THREAD

**Issue by markjprice** [dotnet/docs#13656]
This tutorial uses the term "library" repeatedly yet the sample repo on Github uses a Console App. This is a problem because as far as I can tell, the default interface implementation feature does not work with class libraries. I get error CS8701: Target runtime doesn't support default interface implementation when I try to use this feature in a class library. I am using .NET Core 3.0 Preview 7 on Windows and macOS. Since Microsoft has said that Preview 7 has a Go Live license, this worries me. Please update your tutorial to show that the interface can be in a class library as would be the case in the real world. Thank you.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/default-interface-members-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Can you share your csproj file?

**Comment by markjprice** [comment]
I have two .csproj files because I want the interface with a default implementation of one of its method in a class library (created with dotnet new classlib) and it will be used in a console app (created with dotnet new console).

Here is the .csproj file for the class library:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>

Note: I also tried netstandard2.1 and it gives the same compile error.

Here's the class:

using static System.Console;

namespace Packt.Shared
{
  public interface IPlayable
  {
    void Play();

    void Pause();

    //void Stop();

    // you cannot use default interface implementations in a class library (yet)
    void Stop()
    {
      WriteLine("Default implementation of Stop.");
    }
  }
}

In Visual Studio Code's Terminal:

$ dotnet --version
3.0.100-preview7-012821

$ dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 69.63 ms for /Users/markjprice/Code/Chapter06/PacktLibrary/PacktLibrary.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
IPlayable.cs(14,10): error CS8701: Target runtime doesn't support default interface implementation. [/Users/markjprice/Code/Chapter06/PacktLibrary/PacktLibrary.csproj]

Build FAILED.

IPlayable.cs(14,10): error CS8701: Target runtime doesn't support default interface implementation. [/Users/markjprice/Code/Chapter06/PacktLibrary/PacktLibrary.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.37

Here is the .csproj for the console app, but since I cannot even compile the class library I don't think it matters:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference 
      Include="..\PacktLibrary\PacktLibrary.csproj" />
  </ItemGroup>

</Project>

If it is not possible to use default interface implementations in .NET Standard 2.0 or 2.1 class libraries then this tutorial should say so, and stop using the term "library".

**Comment by Thraka** [comment]
Ahh yes. .NET Standard 2.0 doesn't support them either since that was locked down before they were introduced. You need to use .NET Standard 2.1

I do agree though, the tutorial should specify this requirement.

Thanks for filing the issue.

**Comment by markjprice** [comment]
No, I tried netstandard2.1 and that gives the same error as netstandard2.0.

**Comment by Thraka** [comment]
I just tried on preview 6 and 7 and sure enough, you're right. net standard 2.1 isn't working with that feature. I'll send an email asking about why this is so. I did get it to work in preview 8 (unreleased) so it's probably already fixed and only related to targeting standard 2.1. I'll send an email around just to double check.

However, I do think this tutorial should be clearer about what is required for targeting.

**Comment by markjprice** [comment]
That's great news that it works with Preview 8! It worried me that it didn't work with netstandard2.0 or 2.1 when Preview 7 was supposed to be Go Live. At least I now know that in a few weeks when Preview 8 is released it'll work. :)

**Comment by Thraka** [comment]
OK confirmed. 2.1 never supported the default interface members of c#8 and it's coming. it may not ship in preview 8, i can't really say that. 

Either way, we should note on this article the requirements 😄

**Comment by markjprice** [comment]
Thank you for your diligent work on this issue, Thraka. Microsoft's continuing openness really helps build trust in your platforms to everyone's benefit.

**Comment by Thraka** [comment]
Leaving this open so we can track getting that updated (whenever it comes to be)

**Comment by BillWagner** [comment]
I think we're good to close.

**Comment by RussKie** [comment]
Folks, the doc link is resulting in 404: https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8701)
![image](https://user-images.githubusercontent.com/4403806/194205517-2c7c260f-51ae-4fb6-a448-74c6dbfc10df.png)
