### ISSUE TITLE
Update HttpWebRequest to HttpClient

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#13658]
I think this article should be updated to use HttpClient, not HttpWebRequest.
This also applies to any article that uses HttpWebRequest, of course, not including the HttpWebRequest docs itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494fdee9-0e2c-55bc-dfc0-bc1e5809476f
* Version Independent ID: 3f6b5873-7f2c-a463-bcd3-8093f4af9a2a
* Content: [Walkthrough: Accessing the Web by Using async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await)
* Content Source: [docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
Related to #11759.
