### ISSUE TITLE
Unlike ServiceCredentials, ClientCredentials doesn't inherit from SecurityCredentialsManager class

### ISSUE THREAD

**Issue by tedyyu** [dotnet/docs#13655]
public class ClientCredentials : System.ServiceModel.Description.IEndpointBehavior

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecf81204-9954-e09a-5557-ad595b137ef9
* Version Independent ID: 93ced467-d94c-3f78-1adb-0348be9a4279
* Content: [Walkthrough: Creating Custom Client and Service Credentials](https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/walkthrough-creating-custom-client-and-service-credentials)
* Content Source: [docs/framework/wcf/extending/walkthrough-creating-custom-client-and-service-credentials.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/extending/walkthrough-creating-custom-client-and-service-credentials.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

I think the paragraph where this is mentioned just needs to be reworded to not mention a base class...

>Both the ClientCredentials and the ServiceCredentials classes inherit from the abstract SecurityCredentialsManager class that defines the contract for returning the SecurityTokenManager.

I think that paragraph can just be deleted.

Thanks again!
