### ISSUE TITLE
Bad link to "select the .NET Core version to use"

### ISSUE THREAD

**Issue by rrelyea** [dotnet/docs#13668]
there is a link labeled "Select the .NET Core version to use " that goes to https://docs.microsoft.com/en-us/versions/selection.md which is a 404 - Page not found with unhelpful suggested links.

@cthames found while discussing this issue: https://github.com/NuGet/docs.microsoft.com-nuget/issues/870

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d5789d-4edb-3d22-9a8a-fdad704b8384
* Version Independent ID: c92f0188-38cb-c658-5f1b-e2a3ce2d34e9
* Content: [.NET Core SDK overview](https://docs.microsoft.com/en-us/dotnet/core/sdk)
* Content Source: [docs/core/sdk.md](https://github.com/dotnet/docs/blob/master/docs/core/sdk.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
