### ISSUE TITLE
C# Language keywords: ; nameof

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1366]
The migrated C# Reference documentation does not include the nameof keyword. Added in C# 6 for name of a symbol.

What needs to happen here to support F1 support in Visual Studio or VS Code? /cc @pilchie @dustincampbell.

**Comment by mairaw** [comment]
And you need the F1 metadata added to the docs too.

**Comment by rpetrusha** [comment]
The C# reference documentation now does include `nameof``. However, it is a combined C#/VB topic. They should be separated into separate topics. 
I have, however, added the F1 metadata and opened a PR.
