### ISSUE TITLE
Cant run after creating MyClass.cs

### ISSUE THREAD

**Issue by usjbro** [dotnet/docs#13671]
Program.cs(9,13): error CS0246: The type or namespace name 'MyClass' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\usjbro\mycproject\mycproject.csproj]
Program.cs(9,30): error CS0246: The type or namespace name 'MyClass' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\usjbro\mycproject\mycproject.csproj]

The build failed. Please fix the build errors and run again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#feedback)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Can you share the `MyClass` code? There is a specific note in the documentation when you create that class:

>Add the code below to create your first class. **Make sure to include the correct namespace** so you can reference it from your Program.cs file.

Please double-check that the namespace defined in the MyClass code matches the namespace from the Program code.

**Comment by mairaw** [comment]
Closing due to the lack of response.
