### ISSUE TITLE
Add Pictures

### ISSUE THREAD

**Issue by ScottRidings** [dotnet/docs#13674]
It would be helpful to add pictures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eafdaf7-45eb-b74c-7d65-82cf8d4799f7
* Version Independent ID: bc6f6d06-d4af-7aa4-cb50-d629c2d6b856
* Content: [Walkthrough: Arranging Controls on Windows Forms Using a FlowLayoutPanel](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel#feedback)
* Content Source: [docs/framework/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
