### ISSUE TITLE
C# Language keywords: using static

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1367]
The C# language reference for `using` and for `static` does not include the features added in C# 6. Need to update the using keyword, and the static keyword.

Should F1 help go to a new page for 'using static' when that entire phrase is selected in a C# code file in Visual Studio? /cc @pilchie

**Comment by Pilchie** [comment]
Currently, F1 help basically ignores the selection, and just uses the [position of it's start](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/LanguageService/CSharpHelpContextService.cs,52) to trigger help.  We'd have do something to fix that if we were to address this.
