### ISSUE TITLE
Microsoft.VisualBasic.Constants.vbNewLine is Obsolete

### ISSUE THREAD

**Issue by cston** [dotnet/docs#13670]
## Microsoft.VisualBasic.Constants.vbNewLine is marked Obsolete

The `vbNewLine` constant is marked `[Obsolete]` starting with .NET Core 3.0 Preview 8. 

### Version introduced

.NET Core 3.0 Preview 8

### Change description

Starting with .NET Core 3.0 Preview 8, use of the `vbNewLine` constant produces a compiler warning. In previous releases of both .NET Core and .NET Framework, it was not marked as obsolete. 

### Reason for change

This change was made to support Visual Basic as a language for multi-platform development. The `vbNewLine` constant is equivalent to `\r\n`, the newline character sequence on Windows. On Unix-based systems, the newline character is `\n`.
 
### Recommended action

The `[Obsolete(…)]` attribute message on `vbNewLine` includes the following recommendation:

> For a carriage return and line feed, use vbCrLf.  For the current platform's newline, use System.Environment.NewLine.

### Category

Visual Basic

### Affected APIs

`Microsoft.VisualBasic.Constants.vbNewLine`

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
I've made some changes to the issue, @cston. Could you review them, please?

**Comment by cston** [comment]
@rpetrusha, the **Change description** looks good, thanks.

**Comment by rpetrusha** [comment]
//cc @KathleenDollard @cston
