### ISSUE TITLE
C# Language operators: ?.  Null Conditional operator

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1368]
The migrated content does not include the `?.` operator added in C# 6. The result is null if the LHS is null, right if LHS is not null.

**Comment by svick** [comment]
Isn't [this](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/operators/null-conditional-operators) that article? Though it could use cleanup to be consistent with the other operator articles. And probably splitting into a C# and a VB article. And possibly also splitting `?.` and `?[`.

**Comment by BillWagner** [comment]
@svick I also want to make sure that `??` is covered, or at least linked to as well.
