### ISSUE TITLE
spark-submit call is wrong

### ISSUE THREAD

**Issue by david-c-hunn** [dotnet/docs#13681]
--class org.apache.spark.deploy.DotnetRunner should be  --class org.apache.spark.deploy.dotnet.DotnetRunner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started#feedback)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Thank you, @david-c-hunn! I have updated the doc.
