### ISSUE TITLE
[Code Gallery] Migrate Async Sample: Asynchronous Programming with Async and Await

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13680]
## [Code Gallery] Migrate Async Sample: Asynchronous Programming with Async and Await

**Sample URL**

<https://code.msdn.microsoft.com/Async-Sample-Example-from-9b9f505c>

**Sample information**

The sample has 42,474 downloads and a 4-star rating (10 reviewers).

**Usage**

- docs\csharp\programming-guide\concepts\async\task-asynchronyous-programming-model.md
- docs\csharp\programming-guide\concepts\async\task-asynchronous-programming-model.md
- docs\visual-basic\programming-guide\concepts\async\index.md
- docs\visual-basic\programming-guide\concepts\async\index.md

**Migration Information**
- [x] **C# sample**: to be migrated to *samples/async-and-await/cs*  
- [x] **Visual Basic sample**: migrated to *samples/async-and-await/vb* by dotnet/samples#1380.

**Comment by rskar-git** [comment]
@rpetrusha

I have done a migration of this for visual basic - project is named AsyncFirstExampleVB.

It is placed under samples\concepts\asynchronous-programming\vb

Pull request: https://github.com/dotnet/samples/pull/1380

**Comment by rskar-git** [comment]
@rpetrusha

I have made the requested changes. I am new to github, and hope you've been aware by it - please let me know if there's something else I need to do to in github after making changes. Thx!
