### ISSUE TITLE
Completed sample project not working

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/docs#13683]
I downloaded the sample projects (MakeConst and MakeConstTestProject). Built them successfully.

But none of them generated the warning. I'm using VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#create-analyzer-registrations)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@gojanpaolo I tested the project with the latest VS 2019 build, and it works for me. Did you install the MakeConst analyzer as an add in? Or did you try the debug option to launch a second VS instance?

**Comment by mairaw** [comment]
Closing due to the lack of response.
