### ISSUE TITLE
"To create and initialize your trace source" - sample doesn't work

### ISSUE THREAD

**Issue by ohadschn** [dotnet/docs#13688]
Executing the code in the sample, nothing is written to the default trace listener (verified with DebugView / dbgview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0c9e88-396e-36c5-51e5-5a4c3bf66b94
* Version Independent ID: 3aa71a9b-c3ed-d9f0-29f7-618e9f1a4a31
* Content: [How to: Use TraceSource and Filters with Trace Listeners](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-use-tracesource-and-filters-with-trace-listeners)
* Content Source: [docs/framework/debug-trace-profile/how-to-use-tracesource-and-filters-with-trace-listeners.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/how-to-use-tracesource-and-filters-with-trace-listeners.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @ohadschn. This item is currently in our backlog.
