### ISSUE TITLE
Clarification on the important note at start of article

### ISSUE THREAD

**Issue by adjit** [dotnet/docs#13689]
"Use the same synchronization primitive instance to protect every access to a shared resource. Multiple threads can access a resource concurrently if you use different synchronization primitive instances to protect access to a resource or some parts of code access a resource directly." - the last part of that is unclear how it is written. Is it saying that multiple threads can access a shared resource concurrently by using different sync primitive instances directly on the resource a thread would be accessing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1782d18-fc41-cd33-39ed-813941fd9e73
* Version Independent ID: 356863d9-c1b2-8566-7d91-59a187607ca6
* Content: [Overview of synchronization primitives](https://docs.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives#feedback)
* Content Source: [docs/standard/threading/overview-of-synchronization-primitives.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/overview-of-synchronization-primitives.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
I believe so. Perhaps this explains it better?

>Use the same synchronization primitive instance to protect access of a shared resource. If you use different synchronization primitive instances to protect the same resource, you'll circumvent the protection provided by a synchronization primitive.

**Comment by adjit** [comment]
Yeah, I guess that makes more sense. Because you are using a different synch primitive it allows access to the resource in different ways that would not necessarily be allowed by a single primitive.
