### ISSUE TITLE
"C" locale mapping

### ISSUE THREAD

**Issue by tarekgh** [dotnet/docs#13693]
## "C" locale maps to the invariant locale

.NET Core 2.2 and earlier versions depend on the default ICU behavior, which maps the "C" locale to the en_US_POSIX locale. The en_US_POSIX locale has an undesirable collation behavior, because it doesn't support case-insensitive string comparisons. Because some Linux distributions set the "C" locale as the default locale, users were experiencing unexpected behavior. 

Starting with .NET Core 3.0, the "C" locale mapping has changed to use the Invariant locale instead of en_US_POSIX. The "C" locale to Invariant mapping is also applied to Windows for consistency.

### Version introduced

.NET Core 3.0

### Change description

The "C" locale maps to the Invariant culture instead of the en_US_POSIX culture on Unix-based systems.

#### Old behavior
The "C" locale mapped to the en_US_POSIX culture on Linux.

#### New behavior
The "C" locale maps to the Invariant culture on Unix-based systems. 

#### Reason for change
Mapping "C" to en_US_POSIX culture caused customer confusion, because en_US_POSIX doesn't support case insensitive sorting/searching string operations. Because the "C" locale is used as a default locale in some of the Linux distros, customers experienced this undesired behavior on these operating systems. 

### Recommended action

Nothing specific more than the awareness of this change.

### Category

- Globalization 

### Affected APIs

All collation and culture APIs is affected by this change.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
Could you review this please, @tarekgh. I've made some changes to the issue.

**Comment by tarekgh** [comment]
> The "C" locale maps to the Invariant culture on Unix-based systems.

This behavior will be applied on Windows systems too.

other than that, LGTM.

**Comment by rpetrusha** [comment]
@tarekgh, do we need to note the preview version in which this change was introduced?

**Comment by tarekgh** [comment]
I think it wouldn’t hurt to specify that but I am seeing this will be useful for short time only.

**Comment by mairaw** [comment]
the reason we ask is because we’ll have specific pages for preview7+ if the change was introduced in preview 7+. Can you just confirm whether it was before preview 7 or after?
