### ISSUE TITLE
testingscreen

### ISSUE THREAD

**Issue by ElsaAM4Y** [dotnet/docs#13705]
https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?tabs=csharp
Chapter:Adding and running unit test methods
nr 3:
On the menu bar, select Test > Run > All Tests. 
Should be:
rightclick StringLibraryTest in solution explorer
Run tests
or ctrl + r, a

Also getting a slightly other screen, no summary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET Standard class library with .NET Core in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello! Thank you for opening this issue. Can you tell me what version of Visual Studio you're using? Can you attach some screenshots

**Comment by mairaw** [comment]
Closing due to the lack of response.
