### ISSUE TITLE
Incorrect Image Representation

### ISSUE THREAD

**Issue by nujyp10** [dotnet/docs#13718]
In the ebook, the image# 4-14 has a missing 'Traditional Web App' box which is present in the earlier images from the same section i.e. image # 4-13 & 4-13.1. This makes some confusion because it looks like 'Client WebApp MVC' is not used by any external service/client. 

If my understanding of the image is incorrect & the image is correct, then there should be some description in the following paragraphs about why there is change in the image.
![image](https://user-images.githubusercontent.com/50941372/62439150-75a8f680-b768-11e9-96e5-ebb63f4ff38c.png)

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: b409992c-312e-639d-182b-2067e3561273
* Content: [The API gateway pattern versus the direct client-to-microservice communication](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil can you take a look at this feedback?

**Comment by mvelosop** [comment]
Hi @nujyp10, thanks for the heads up!

Will fix the image.

Cheers.
