### ISSUE TITLE
Exception User-Unhandled

### ISSUE THREAD

**Issue by higrass** [dotnet/docs#13713]
When I run the 1st example code in debug mode, it breaks at  

var task1 = Task.Run(() =&gt; { throw new CustomException("This exception is expected!"); });

And a window pops up with a title of "Exception User-Unhandled"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25bdb110-7ada-3817-bc40-9c11cab6513c
* Version Independent ID: 9476dc46-d4f0-e7f4-c21e-faaafe0433ea
* Content: [Exception handling (Task Parallel Library)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library#feedback)
* Content Source: [docs/standard/parallel-programming/exception-handling-task-parallel-library.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/exception-handling-task-parallel-library.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by higrass** [comment]
I am using .net Framework 4.7.2 for the project

**Comment by higrass** [comment]
This can be solved by changing the Visual debugging setting, found the solution here:https://devblogs.microsoft.com/pfxteam/faq-the-debugger-does-not-correctly-handle-task-exceptions/

**Comment by mairaw** [comment]
Isn't this related to the note on the article that says: "When "Just My Code" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says "exception not handled by user code." This error is benign. You can press F5 to continue and see the exception-handling behavior that is demonstrated in these examples. To prevent Visual Studio from breaking on the first error, just uncheck the Enable Just My Code checkbox under Tools, Options, Debugging, General."

**Comment by mairaw** [comment]
Closing due to the lack of response.
