### ISSUE TITLE
Readonly explanation needs rewording

### ISSUE THREAD

**Issue by Elaskanator** [dotnet/docs#13725]
Stated: "The FirstName and LastName properties can be set only in the body of a constructor"
Reality: A derived class constructor (which is "a constructor") can not set these readonly properties.
Suggestion: "... can be set only in the body of the same class"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fef60d-04e9-dc86-2e3f-134c10ea37bb
* Version Independent ID: 09b5aa7a-1b43-8bf9-9786-f10f457488dd
* Content: [What's New in C# 6 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#feedback)
* Content Source: [docs/csharp/whats-new/csharp-6.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-6.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
