### ISSUE TITLE
Health check on console app?

### ISSUE THREAD

**Issue by xiongc96** [dotnet/docs#13729]
How would you write Health Checks for console apps that are not web applications?  Are there any examples?

**Comment by Thraka** [comment]
Hello!

I'm sorry, I don't understand your question. This repository is for issues related to documentation published for .NET. 

I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow or Reddit.

I'm going to close the issue. Sorry again.

Thanks.
