### ISSUE TITLE
Typo? "Docker images" should be replaced with "Docker instances"

### ISSUE THREAD

**Issue by oleg-bronzhaiev** [dotnet/docs#13721]
Probably, the text "Docker images" should be replaced with "Docker instances"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#feedback)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by oleg-bronzhaiev** [comment]
I guess, I got it... The term "image" didn't mean "a drawing", but rather "a computer software image" (an immutable single unit)

**Comment by mairaw** [comment]
Correct @oleg-bronzhaiev. Here's an article from the Docker docs as well: https://docs.docker.com/v17.09/engine/userguide/storagedriver/imagesandcontainers/

And another one: https://www.tutorialspoint.com/docker/docker_images
