### ISSUE TITLE
Address type (IP address or DNS name)?

### ISSUE THREAD

**Issue by awarberg** [dotnet/docs#13738]
According to the &lt;add&gt; tag documentation the "address" attribute is an "IP address or DNS name". However, in the example you provide a URI "http://www.contoso.com". Does this mean that the connection is limited by the host (DNS name) of the URI, or does it apply to the path segment of the URI as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1ec0-1422-99cc-5f41-4da77740b459
* Version Independent ID: b6a958ef-1b4b-9a92-a921-a075c1c156c4
* Content: [&lt;connectionManagement&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
@davidsh @karelz can you help with this question?

**Comment by davidsh** [comment]
>Does this mean that the connection is limited by the host (DNS name) of the URI, or does it apply to the path segment of the URI as well?

The path segment of the URI is ignored. It is only the authority portion of the URI (i.e. the host name).

**Comment by davidsh** [comment]
And to be more specific, the scheme, host and port (if present) is used as the unique key.  So, for example, the following would be valid in the config section:

```xml
<configuration>  
  <system.net>  
    <connectionManagement>  
      <add address = "http://www.contoso.com" maxconnection = "4" />  
      <add address = "https://www.contoso.com" maxconnection = "5" />  
      <add address = "http://www.contoso.com:8080" maxconnection = "6" />  
      <add address = "*" maxconnection = "2" />  
    </connectionManagement>  
  </system.net>  
</configuration>  
```

So, these are separate limits:

* "http://www.contoso.com" maxconnection = "4" 
* "https://www.contoso.com" maxconnection = "5"
* "http://www.contoso.com:8080" maxconnection = "6"
