### ISSUE TITLE
C# Language Reference expressions: throw

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1373]
Starting in C# 7, `throw` can now be an expression as well as a statement.

**Comment by BillWagner** [comment]
@madstorgersen Is it correct to say that `throw` can be used both as a statement or an expression, or is it always an expression starting in C# 7?

**Comment by MadsTorgersen** [comment]
I believe we keep separate notions of throw expressions and throw statements. @gafter may be able to elaborate.

**Comment by gafter** [comment]
Yes, it is separately a statement and expression. The reason we keep the statement form is that it has unique reachability behavior that is different from other expression-statements. Specifically, its endpoint is not reachable.
