### ISSUE TITLE
[Code Gallery] Migrate Simple Calculator MEF Application

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13734]
## [Code Gallery] Simple Calculator MEF Application

**Sample URL**

<docs\framework\mef\index.md>

**Sample information**

38,931 downloads, with 5.0 rating (6 reviewers)

**Usage (in GitHub repos)**

- docs\framework\mef\index.md

**Comment by mairaw** [comment]
Is this a duplicate of #13733?

**Comment by rpetrusha** [comment]
Yes it is a duplicate. I have no idea of how that might have happened. I'll close this one.
