### ISSUE TITLE
Missing precise specification of method signatures and visibility

### ISSUE THREAD

**Issue by binki** [dotnet/docs#13730]
The method signatures should be clearly shown as `bool ShouldSerialize«PropertyName»()` and `void Reset«PropertyName»()`. It should be stated and shown that the members may be private (because the Designer will still see them).

For example, the members in https://github.com/binki/ShouldSerializeResetPropertyIde0051/blob/971f524e347c472da9157a6048c88335c82f5fe6/ShouldSerializeResetPropertyIde0051/UserControl1.cs are discovered by the designer properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e320c305-0aa7-0fd2-8c95-61c5409b00a9
* Version Independent ID: 6c4a2a9e-182d-74fc-fe35-add388561217
* Content: [Defining Default Values with the ShouldSerialize and Reset Methods](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods)
* Content Source: [docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

I agree there could be some clarifications there.

Thanks again!
