### ISSUE TITLE
dotnet test --filter FullyQualifiedName fails to work with generic test classes 

### ISSUE THREAD

**Issue by yshpakov** [dotnet/docs#13749]
`dotnet test --filter "FullyQualifiedName=MyNamespace.MyTestsClass<ParameterType1,ParameterType2>.MyTestMethod"
`
Error message:
```
MSBUILD : error MSB1006: Property is not valid.
Switch: ParameterType2>.MyTestMethod

For switch syntax, type "MSBuild -help"

```

There is no way to escape comma. So there is no way to pass full qualified name if the tests class is generic with multiple parameter types.
Either put into documentation the explanation how to accomplish that, or report a bug to .NET Core developers team.

I need it because I run the same UI Tests code under both AndroidDriver and IOSDriver which I provide as generics parameters.

edit by @mairaw: added topic details
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@rainersigwald @livarcocc can you help with this question about dotnet test?

**Comment by rainersigwald** [comment]
There is a way to [escape](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-escape-special-characters-in-msbuild?view=vs-2019) the comma in MSBuild command-line property definitions: replace it with `%2C`.

```sh-session
$ dotnet new mstest
...
$  dotnet test --filter "FullyQualifiedName=MyNamespace.MyTestsClass<ParameterType1,ParameterType2>.MyTestMethod"
MSBUILD : error MSB1006: Property is not valid.
Switch: ParameterType2>.MyTestMethod

For switch syntax, type "MSBuild -help"
$ dotnet test --filter "FullyQualifiedName=MyNamespace.MyTestsClass<ParameterType1%2CParameterType2>.MyTestMethod"
Test run for S:\repro\dotnet\docs\issues\13749\bin\Debug\netcoreapp3.0\13749.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-preview-20190808-04
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
No test matches the given testcase filter `FullyQualifiedName=MyNamespace.MyTestsClass<ParameterType1,ParameterType2>.MyTestMethod` in S:\repro\dotnet\docs\issues\13749\bin\Debug\netcoreapp3.0\13749.dll
```

It would be nice if `dotnet test` did this automatically when handling the `--filter` argument. I filed dotnet/cli#12233 to track that.

**Comment by yshpakov** [comment]
We probably need to leave some comments or references about special characters limitation / escaping into existing Documentation online.
