### ISSUE TITLE
"Security Overview1" in page title

### ISSUE THREAD

**Issue by joebates25** [dotnet/docs#13746]
"Security Overview1" appears in the page title. The "1" should not be there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54a2fcb-daad-26d9-5af8-4c648c602b92
* Version Independent ID: d397c914-11f1-4249-fc55-34cfa3f969f6
* Content: [Security Overview1](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/security-overview)
* Content Source: [docs/framework/wcf/feature-details/security-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/security-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you, I'll fix this up real fast.
