### ISSUE TITLE
[Code Gallery] Migrate 101 LINQ Samples

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13745]
## [Code Gallery] Migrate 101 LINQ Samples

**Sample URL**

<https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b>

**Sample information**

The sample has 345,699 downloads and a 5.0 rating (82 reviewers) as of 8/6/2019.

It was last updated on 9/27/2011.

**Usage**

- docs\standard\using-linq.md

**Comment by zspitz** [comment]
The current sample shows LINQ to SQL. Would it make sense as part of the migration to add samples of LINQ to Entity Framework (Core or 6)?

Showing LINQ to EF with a provider other than SQL Server (SQLite? SQL Server CE?) would mean the samples don't require a full installation of SQL Server.

**Comment by BillWagner** [comment]
This was fixed in dotnet/try-samples#47
