### ISSUE TITLE
Expression-bodied local functions

### ISSUE THREAD

**Issue by seppo498573908457** [dotnet/docs#13740]
It should be explicitly and clearly stated if local function definitions can be expression-bodied (arrow functions) or not, since the risk of confusion with lamda expressions is great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for creating this. I've added it to our backlog for the next update to this article.
