### ISSUE TITLE
"Get Started with the Management Libraries for .NET" link (https://msdn.microsoft.com/library/dn722415.aspx) is not working

### ISSUE THREAD

**Issue by Kiba-kun** [dotnet/docs#13741]
"Get Started with the Management Libraries for .NET" link (https://msdn.microsoft.com/library/dn722415.aspx) 
contained in "Deploying and Managing Azure Resources with F# Scripts" section seems not to be relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45bbacb9-52da-4b4e-1c68-2e582aab477d
* Version Independent ID: 9aa1c6f5-a9cc-3a51-7f02-36da483f0c4a
* Content: [Using F# on Azure](https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-on-azure/#deploying-and-managing-azure-resources-with-f-scripts)
* Content Source: [docs/fsharp/using-fsharp-on-azure/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-on-azure/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @sylvanc
* Microsoft Alias: **phcart**

**Comment by Thraka** [comment]
I'm not sure I see the reason for having that entire paragraph. VMs is already covered at the top for one, and the 2nd link can be rolled into the next paragraph.

@cartermp what do you think? Do you still work on this stuff? Is @sylvanc the appropriate person to contact?
