### ISSUE TITLE
Consider retiring or reducing this page and pointing people at another

### ISSUE THREAD

**Issue by lukepuplett** [dotnet/docs#13753]
To DRY up the docs and clear down some of the outstanding open issues, perhaps just point readers to this page?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @lukepuplett, thanks for your feedback!

The page makes sense as an introduction to the `HttpClientFactory` in the context of the Microservices Architecture guide.

This is also used to generate the related e-book (https://aka.ms/microservicesebook), where it's even more important for a unified content, so a simple link would juts not be enough.

However, the content will be improved based on the feedback.

Thanks.
