### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by JustAnotherG** [dotnet/docs#13757]
MathClass m = new MathClass();
What's the purpose of the above line of code in the example? Couldn't you have more easily just typed:
Del d = this.MultiplyNumbers;
or even:
Del d = MultiplyNumbers;

Please explain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495dca2a-dcd9-892f-21f0-e970589b543d
* Version Independent ID: 159fb3e3-66b4-6cdc-f921-4406447b98ca
* Content: [Delegates with Named vs. Anonymous Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods)
* Content Source: [docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @JustAnotherG  We should update this for a better sample.

The purpose is to demonstrate that delegates can be created from static methods or instance methods. A better instance method should be used for this example.

I've added it to our backlog for the next update to this article.
