### ISSUE TITLE
Wrong notes in "Required UI Automation Control Patterns" > "ControlPattern" > "ITextProvider"

### ISSUE THREAD

**Issue by ohelin2** [dotnet/docs#13751]
Hello,
The description of "ITextProvider" is the same as "IScrollProvider".
Thanks & regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47c7fe7-1981-ea27-bea2-90f692ff2288
* Version Independent ID: d4e86ad9-7914-6799-4fbb-0f8ded0b2c68
* Content: [UI Automation Support for the Document Control Type](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-support-for-the-document-control-type#feedback)
* Content Source: [docs/framework/ui-automation/ui-automation-support-for-the-document-control-type.md](https://github.com/dotnet/docs/blob/master/docs/framework/ui-automation/ui-automation-support-for-the-document-control-type.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @ohelin2. This item is currently in our backlog.

@merriemcgaw @vatsan-madhavan do you know who owns UI Automation?

**Comment by merriemcgaw** [comment]
@vatsan-madhavan @rladuca is this on your side? It's not WinForms.
