### ISSUE TITLE
This page should mention handedness

### ISSUE THREAD

**Issue by mikeminutillo** [dotnet/docs#13752]
We have had a long-standing issue with some drop-downs appearing in the wrong place on some machines and eventually we figured out it was related to the handedness setting found under Control Panel -&gt; Tablet PC Settings -&gt; Other -&gt; Handedness.

As this page has a table and lots of examples showing all of the  placement options and how they work, it should mention handedness and how that effects things.

You can see the code that determines points of interest and how it changes based on handedness [here](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs#L2470-L2564)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c649c8-b40a-bb58-79ce-b204031f05e2
* Version Independent ID: ab7d588a-67c0-5fbc-5819-5dc36e8ce635
* Content: [Popup Placement Behavior](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/popup-placement-behavior?view=netframework-4.8#feedback)
* Content Source: [docs/framework/wpf/controls/popup-placement-behavior.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/popup-placement-behavior.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
