### ISSUE TITLE
OpenFile example does not use OpenFile

### ISSUE THREAD

**Issue by agaures** [dotnet/docs#13762]
I believe the second example is meant to be: 
using (Stream s = openFileDialog1.OpenFile())

Also, the initialisation of 'openFileDialog1' includes an erroneous semicolon as well as the 'FileName' property having incorrect capitalisation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9db6b2-ee5e-dffb-94ea-3c56ed18e34e
* Version Independent ID: 9a19956f-7670-1e75-feb7-8a8b2e71c31e
* Content: [How to: Open files with the OpenFileDialog component](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component#feedback)
* Content Source: [docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-open-files-using-the-openfiledialog-component.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @agaures, for pointing out these issues with the example. We've opened dotnet/samples#1156 to address them.
