### ISSUE TITLE
Article Contradicts Itself

### ISSUE THREAD

**Issue by JustAnotherG** [dotnet/docs#13764]
"Note that expression can be a statement expression only if the member's return type is void, or if the member is a constructor, a finalizer, or a property set accessor."

And yet, in the above example, an expression bodied statement is used to define a member method that returns a string? Clarification is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a695fde2-da48-835f-423d-d34fb048d6ab
* Version Independent ID: e8eab8da-72ba-991a-c011-a41d2ed9939d
* Content: [=&gt; operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator#expression-body-definition)
* Content Source: [docs/csharp/language-reference/operators/lambda-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/lambda-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@JustAnotherG good catch, thanks!
