### ISSUE TITLE
This line is wrong grammatically and doesn't make any sense

### ISSUE THREAD

**Issue by WoodpeckerBaby** [dotnet/docs#13768]
"However, the called method can use the address to access the class members that both the original address and the copy reference."

FYI

URL: 
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4265e5ac-ef1c-7da2-fdf3-854494aa5a73
* Version Independent ID: 7c436200-ff45-5391-fefd-6c64f9ab91e6
* Content: [How to: Know the Difference Between Passing a Struct and Passing a Class Reference to a Method - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up. I think it's missing a few key words that will make it clearer. I've **emphasized** the added words:

>However, the called method can use the **copy** address to access the class members that both the original address and the copy **address** reference.

Does that make more sense?
