### ISSUE TITLE
Realistic example

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet/docs#13769]
Would be nice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47acd93c-2f52-dc26-8fba-cfbd41c748e1
* Version Independent ID: ebbbba0b-6ac3-b636-6564-e8a597498e7b
* Content: [Example COM Class - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interop/example-com-class)
* Content Source: [docs/csharp/programming-guide/interop/example-com-class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interop/example-com-class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We can improve this example, we do want to keep it small and focused.

I've added this to our backlog for when we next update this topic.

**Comment by yatagarasu25** [comment]
This example makes no sense to me. None of the parts in the example are covered in the article, as well example have nothing of what is mentioned in the article.
