### ISSUE TITLE
Consider using EasyNetQ for connecting to RabbitMQ

### ISSUE THREAD

**Issue by mikehadlow** [dotnet/docs#13770]
Implementing a reliable client for RabbitMQ is not-trivial. The open source EasyNetQ project provides a battle-tested client library that you can use in your application. Check out http://easynetq.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f590167-a388-94ac-e39b-463978a761b0
* Version Independent ID: 7f36b050-25b4-e998-26b7-bcf1ebc3d4aa
* Content: [Implementing an event bus with RabbitMQ for the development or test environment](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by dlidstrom** [comment]
Yeah, or why not MassTransit (or better yet, NServiceBus)? This sample is trivializing what is really a complex reality (supporting two messaging infrastructures) that anyone following this will soon have to deal with.

**Comment by mvelosop** [comment]
Thanks for your feedback @mikehadlow, @dlidstrom.

Will include references to production-ready offerings and highlight, once more, this is a learning resource.

This is certainly a complex topic, and the article is mainly educational. It also clearly states that this is for development or testing in the title and the very first paragraph... however it's also quite probable that the message is probably not going to get clear enough!

Thanks.
