### ISSUE TITLE
No mention of new project file convention

### ISSUE THREAD

**Issue by scottrudy** [dotnet/docs#13779]
I think it's worth mentioning the simple convention in dotnet core project files:

`&lt;GenerateDocumentationFile&gt;true&lt;/GenerateDocumentationFile&gt;`

This basically gives you the same as &lt;DocumentationFile&gt;bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml&lt;/DocumentationFile&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#feedback)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
