### ISSUE TITLE
BypassNGenAttribute needs AttributeTargetsAttribute

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13775]
@johannesvogel1 commented on [Thu Aug 08 2019](https://github.com/dotnet/docs.de-de/issues/148)

The Codesample for the BypassNGenAttribute is not valid, because the AttributeTarget is missing.

namespace System.Runtime
{
    **[AttributeUsage(AttributeTargets.Method)]**
    public class BypassNGenAttribute 
        : Attribute
    {
    }
}

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 085ecaf8-233f-82eb-c564-b05137c899b9
* Version Independent ID: e2088737-ec20-b083-0a26-c041003d12dd
* Content: [Ngen.exe (Native Image Generator)](https://docs.microsoft.com/de-de/dotnet/framework/tools/ngen-exe-native-image-generator#feedback)
* Content Source: [docs/framework/tools/ngen-exe-native-image-generator.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/tools/ngen-exe-native-image-generator.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---

@srvbpigh commented on [Thu Aug 08 2019](https://github.com/dotnet/docs.de-de/issues/148#issuecomment-519363415)

Hello, @johannesvogel1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is reporting an omision in the code sample
best regards

**Comment by rpetrusha** [comment]
Thanks for moving this issue, @CeciAc. I've opened dotnet/samples#1148 to address it.
