### ISSUE TITLE
Old Terminology

### ISSUE THREAD

**Issue by kduenke** [dotnet/docs#13772]
This document still references Document DB instead of the new Cosmos DB terminology.
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps#azure-documentdb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps#feedback)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @kduenke. There are other 4 articles in our repo (most from the e-books) that use that old terminology @mvelosop:
https://github.com/dotnet/docs/search?q=documentdb&unscoped_q=documentdb

**Comment by mvelosop** [comment]
Thanks @mairaw, will check with @ardalis, he may be updating some of these e-books/guides.
