### ISSUE TITLE
Nested Classes?

### ISSUE THREAD

**Issue by rcollina** [dotnet/docs#13773]
I might have missed this, but I wonder if this new feature also supports Nested Classes.
I would like to define input and output POCOs as part of a contract.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-members-versions)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@rcollina Hi, sorry for the delay on this. Can you provide more information about what you mean in regard to the nested classes? There is no restriction on nested classes implementing an interface.

**Comment by rcollina** [comment]
@Thraka no problem.
I mean nested classes within an interface declaration.

**Comment by Thraka** [comment]
So I did a test where I created a nested class in the interface. Classes that implement the interface do NOT get the nested class. The nested class seems independent of the interface, it just becomes the container for the class.

```csharp
namespace sharpeight
{
    class Program
    {
        static void Main(string[] args)
        {
            Car car = new Car();
            Car2 car2 = new Car2();
            ICar.ChildClass b = new ICar.ChildClass();
            Console.WriteLine(((ICar)car).Color);
            Console.WriteLine(car2.Color);
            Console.WriteLine(b.Name);
            Console.ReadKey();
        }
    }

    public interface ICar
    {
        string Color => "Blue";

        public class ChildClass
        {
            public string Name => "ChildClass Name";
        }
    }

    public class Car: ICar
    {

    }

    public class Car2 : ICar
    {
        public string Color => "Red";
    }
}
```

**Comment by Thraka** [comment]
I think this answers your question 😄  I'm going to close it.

**Comment by rcollina** [comment]
It does, thank you!
