### ISSUE TITLE
The ServicePointManager security protocol does not work on Windows 7

### ISSUE THREAD

**Issue by jozefizso** [dotnet/docs#13787]
&gt; If your app targets .NET Framework 4.7 or later versions
&gt; The following sections show how to verify you're not using a specific TLS or SSL version.

&gt; For HTTP networking
&gt; ServicePointManager, using .NET Framework 4.7 and later versions, defaults to the OS choosing the best security protocol and version. To get the default OS best choice, if possible, don't set a value for the SecurityProtocol property. Otherwise, set it to SystemDefault.

This recommendation does not work on Windows 7 Service Pack 1 with .NET Framework 4.7.2 and application targeting 4.7.2

In this configuration, the HttpClient will *not* connect to the TLS 1.2 server.

Downloading data with `HttpClient.GetStringAsync("https://docs.microsoft.com/")` on Windows 7 will fail:

```
Environment.Version: 4.0.30319.42000
ServicePointManager.SecurityProtocol: SystemDefault
Downloading from 'https://docs.microsoft.com/'

HttpRequestException: An error occurred while sending the request.
WebException: The underlying connection was closed: An unexpected error occurred on a send.
IOException: Authentication failed because the remote party has closed the transport stream.
```

Only solution is to set `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12` which defeats the purpose of *SystemDefault* setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-net-framework-47-or-later-versions)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
Is `TLS 1.2` enabled by default for your Windows 7 install? I've looked around online and on forums and it doesn't seem to indicate this is the default for the OS.

**Comment by jozefizso** [comment]
This is a fully patched Windows 7 SP1 machine which can correctly load TLS 1.2 sites.

PS: documentation clearly states it will select the most secure protocol version.

**Comment by Thraka** [comment]
I just noticed that the article has a link to a specific issue to discuss this. At the end of the issue is a recent comment: https://github.com/dotnet/docs/issues/4675#issuecomment-498772703

This states that even though TLS 1.2 is supported, its not set as the _default_ by the Windows 7 OS (probably so as to not instantly break all existing apps that expect a lower TLS?) and you'll still have to enable it.

Actually, at the end of the article it lists the problem I think you're running into specifically: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#support-for-tls-12

![image](https://user-images.githubusercontent.com/2672110/62798693-bf108300-ba93-11e9-845f-b58b3263030a.png)

**Comment by Thraka** [comment]
Specifically though, there is an engineer or support person on that linked thread, I would post there for help or clarification. They can also update the documentation if something isn't as clear as it should.

**Comment by jozefizso** [comment]
This is **utterly frustrating**. A simple, two line code will not work **by default** on Windows 7. Yet you document everywhere that .NET 4.7 is supposed to fix this mess.

Explanation why it does not work is nice, but in real world, it **just does not work** and that's totally stupid. A fix will make application **less** secure on all platforms, as TLS 1.2 may not be the default in the future.

In our code, we are connecting to a server that provides both TLS 1.1 and 1.2 - and this **does not work** on Windows 7 either. .NET Framework 4.7 is just insecure platform which forces TLS 1.0??? Without any explanation or notice in documentation.

This is not normal.

**Comment by jozefizso** [comment]
This is your guidance:

> The guidance given in our documentation is that for new code the recommendation is to use patterns such as SystemDefaultTlsVersions to let the OS make the best decision. For new .NET Framework applications targeting 4.7 and later, these registry keys are not needed and the equivalent "SystemDefault" values are used.

Yet, this does not work!

**Comment by Thraka** [comment]
Posting this here also in case others look at the thread. The issue is solved by following the "SystemDefault" registry key values. I created an Azure VM with Windows 7, installed Visual Studio, created a sample app, validated it didn't work, set these registry keys, validated it did work. 

Here is a .reg file that sets the keys

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001

```

**Comment by Thraka** [comment]
Additionally, the difference between .NET Framework 4.6 vs 4.7 is that the default of ` ServicePointManager.SecurityProtocol` changed to a new value the causes .NET Framework to default to the OS and allow the OS to tell it what security protocol to use. To replicate the 4.6 behavior, set the application to explicitly use TLS 1.0-1.2

```csharp
 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

**Comment by jozefizso** [comment]
The obvious point here is to **not** set TLS protocol versions in the application. How the application will support TLS 1.3 this way??

**Comment by jozefizso** [comment]
> This is a potential breaking change

This is a real breaking change which makes applications to silently switch to insecure TLS protocol just by re-targeting to .NET 4.7.1.

**Comment by jozefizso** [comment]
> allow the OS to tell it what security protocol to use

This is **false** - .NET 4.7.x app will **ignore** supported TLS protocols and it will connect **only** using the default protocol.
