### ISSUE TITLE
[Question] How to analyze sentiment comment that is from other language not english?

### ISSUE THREAD

**Issue by huanbd** [dotnet/docs#13786]
Can you help me, how to use ML.NET to analyze text, that is from other language not english (vietnamese). With my knowledge, I think have to preprocess data before train.
Can help me the steps to do that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Hi @huanbd ,

Thank you for your question. Since this is more of a product question, I'd encourage you to raise an issue on the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo.

**Comment by mairaw** [comment]
You used to have a separate project for ML.NET. Fine by me either way, just wanted to check which one you should be using. I think the August one for ML wasn't created yet. /cc @natke
