### ISSUE TITLE
offline book - C# content missing

### ISSUE THREAD

**Issue by ghogen** [dotnet/docs#13795]
The offline book in VS 2019 for C# is missing some of the C# reference content. This is because the TOC is in a form that the offline book build tool doesn't know how to deal with. The issue to be avoided is that when a parent TOC node references a topic in a sub-TOC in order to pull in the sub-TOC, the referenced topic must be the root node of the sub-TOC.  

So the fix here is to change the C# reference sub-TOC to eliminate the extra node at the top level and bring the topic referenced in the parent TOC to the root node.

**Comment by ghogen** [comment]
@BillWagner I have a PR to address this and will mention you on it.

**Comment by ghogen** [comment]
@rpetrusha @Thraka

**Comment by mairaw** [comment]
Does your PR closes this issue or is there more @ghogen?

**Comment by ghogen** [comment]
I would like to keep this open until we rebuild the book and verify that our fix worked.

**Comment by mairaw** [comment]
Sounds good! 👍

**Comment by BillWagner** [comment]
The referenced PR did fix this. We didn't close it in in a timely fashion.

Closing now.  /cc @ghogen
