### ISSUE TITLE
Missing data loading code?

### ISSUE THREAD

**Issue by jwood803** [dotnet/docs#13800]
The document mentions to "load the data into an `IDataView`". Is it missing the code that does this step?

[AB#1579020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579020)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1fb0dd-648b-26e9-7e4e-48824ab94160
* Version Independent ID: 689b6488-dadc-fd39-c432-ebf095a0299a
* Content: [Explain model predictions using Permutation Feature Importance - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @jwood803 ,

Thanks for the feedback. No missing code. This was done to leave it up to the user to load the data in whichever manner they prefer (file, from enumerable) although I can see how the wording can be confusing. Closing this issue and opening a new one to address similar language across the how-to guides to provide clarity.
