### ISSUE TITLE
movie recommendation system based location

### ISSUE THREAD

**Issue by caesar9319** [dotnet/docs#13810]
How can I implement a recommendation system based location in C# based this form, calculate the similarity whether cosine or pearson and how to predict 
And show for example 5 movies based on recommendation

[AB#1579020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579020)

**Comment by mairaw** [comment]
This seems a question regarding ML.NET. @natke can you take a look?

**Comment by natke** [comment]
Hi @caesar9319, can you provide us a little more information about what you are trying to achieve? Have you looked at the movie recommender tutorial? https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/movie-recommendation

**Comment by natke** [comment]
Closing as no response from @caesar9319. Please follow up again if you need more info.
