### ISSUE TITLE
Superb!! This is what I've long wanted to do on my own since 25 more years ago.

### ISSUE THREAD

**Issue by ComSpex** [dotnet/docs#13811]
Many customers of mine must have long wanted this to be realized much sooner.  However, I'm now turning 62 and almost retired as my every day is now almost like everybody's holiday ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the compliments.

Closing as kudos.
