### ISSUE TITLE
WCF Peer Channel is obsolete

### ISSUE THREAD

**Issue by aubiyko** [dotnet/docs#13820]
Apparently, WCF Peer Channel ([NetPeerTcpBinding](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.netpeertcpbinding?view=netframework-4.8) and related) is obsolete. I think this should be mentioned somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2007482-e488-432e-341d-35f475941487
* Version Independent ID: 3e64dd93-9e57-7c68-8665-aade3284245c
* Content: [Peer Channel Concepts](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/peer-channel-concepts)
* Content Source: [docs/framework/wcf/feature-details/peer-channel-concepts.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/peer-channel-concepts.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

@HongGit Perhaps you guys want to add something in here about it? Also, the https://docs.microsoft.com/en-us/dotnet/framework/wcf/system-provided-bindings section probably needs an update. I'll set this as P2 and put it on the backlog for when you have cycles to update this documentation.
