### ISSUE TITLE
Formatting of "this" in Indexers section

### ISSUE THREAD

**Issue by eugenern** [dotnet/docs#13826]
It may make sense for the word "this" in the sentence "An indexer is declared like a property except that the name of the member is this followed by…" to be formatted as code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181f41d-b6ce-ad66-084e-8d2b514b87e2
* Version Independent ID: 494c4344-b752-4f86-5b66-1ef4b81c1e75
* Content: [Classes and Objects in C# - A tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#feedback)
* Content Source: [docs/csharp/tour-of-csharp/classes-and-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/classes-and-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @eugenern 

I've created #13827 to fix this issue.
