### ISSUE TITLE
missing function definitions

### ISSUE THREAD

**Issue by markus27183** [dotnet/docs#13821]
It would help if you provided function definitions since this doens't compile. e.g. FryEggsAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
All the code is in our [samples repository](https://github.com/dotnet/samples/tree/master/snippets/csharp/tour-of-async)

Can you tell me which version doesn't compile? It would if it matches the samples repository.

**Comment by mairaw** [comment]
@BillWagner my interpretation of this is that @markus27183 is asking to see the FryEggsAsync definition like declared at https://github.com/dotnet/samples/blob/master/snippets/csharp/tour-of-async/AsyncBreakfast-V3/Program.cs#L73 or https://github.com/dotnet/samples/blob/master/snippets/csharp/tour-of-async/AsyncBreakfast-final/Program.cs#L84. 

Not sure if this implementation is not show on purpose or not.

**Comment by SeniorSSS** [comment]
Excelent!
Just when i finished trying to write mine own definitions i started to read comments but that was good thing.

Any way i noticed one irrelevant mistake in mine code and checked yours final - 
WHERE IS MY JUICE ? :D

**Comment by sdg002** [comment]
Hi 
I was unable to find the definitions for the methods `ApplyJam` and `ApplyButter`.  It is quite likely that all of these are implemented in the samples repository in Github.
While, I appreciate that you have put in efforts to provide the full source code via Github, I do not like the idea of frequently navigating out of the MSDN documentation. This destroys my mental model and makes my learning experience unproductive.

Thanks.

**Comment by sdg002** [comment]
This is how my experience was

- I begin reading through the article and encounter the first snippet of code
- I see a method `PourCofee`. I do a CTRL+F and I do not find anything on the page. 
- Ignore and move on
- I see methods FryEggs and FryBacon. Again do a CTRL+F and find nothing. I patiently move on to the next line
- Move on to next snippet. I see a method `ToastBreadAsync` but as usual no body .
- This experience keeps repeating over and over again.

The fragmented user experience left me so embittered that I abandoned reading the article and looked for other sources.

Again, putting all code is definitely a good idea, but I am out!

-

**Comment by suttonb** [comment]
@BillWagner if the code is in your samples repository that information would be helpful to put in the actual article instead of buried down in the comments section

**Comment by coosmiin** [comment]
@BillWagner, apparently the samples repository moved since the links provided here are broken. Can you provide the new location?

**Comment by tlynch001** [comment]
@BillWagner Link is broken...please provide new location for code

**Comment by kenwithee** [comment]
Took a little while to track down but looks like they moved to docs repo here: https://github.com/dotnet/docs/tree/master/samples/snippets/csharp/tour-of-async/AsyncBreakfast-final with the implementations in the Program.cs file here: https://github.com/dotnet/docs/blob/master/samples/snippets/csharp/tour-of-async/AsyncBreakfast-final/Program.cs
