### ISSUE TITLE
/namespace flag references fix for name collisions but I'm confused

### ISSUE THREAD

**Issue by dgbrown** [dotnet/docs#13831]
The description for the /namespace flag says "To make sure that the message contract name does not collide with operation name, you should either qualify the type reference with ::, or make sure the names are unique." but I don't understand how/where I'd qualify the type reference. Do you mean in the WSDL? What if its outside of my control? Do you mean to edit the proxy after its been generated? If so, how? I'm experiencing a collision issue with a .net core proxy generated for a third-party soap api. I've got my hopes up that this could be the fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0952b258-0ee3-950f-3193-4ed5635b1a6e
* Version Independent ID: 58aae6b7-c83c-40e8-530d-0848e9761919
* Content: [ServiceModel Metadata Utility Tool (Svcutil.exe)](https://docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe#feedback)
* Content Source: [docs/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
@HongGit @mconnew can you please look at this feedback?

**Comment by mconnew** [comment]
Here's a problematic scenario. You have a namespace called Animals which contains a class called Dog. You also have a class called Animals with a property called Dog in the namespace MyApp. In this code:
```c#
namespace MyApp
{
    public static class Program
    {
        public void Main(string[] args)
        {
            DoSomething(Animals.Dog);
        }
    }
}
```
How does the compiler resolve Animals.Dog? Is it the class Dog in the namespace Animals? Or is it the property Dog on the class Animals? One way is to use :: as per the documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/namespace-alias-qualifier) (which also provides more examples). If you mean the class Dog, you can use Animals::Dog. Basically the documentation is saying that when you provide a mapping between XML namespaces and CLR namespaces, you can end up with the "Is it a class or is it a namespace" ambiguity. If this happens, you can disambiguate which it is using the :: operator. An operation in a WSDL becomes a method on an interface. A message contract in a WSDL becomes a class definition. Sometimes this things end up with the same name.  
@dgbrown, if you are still stuck after this, open an issue in https://github.com/dotnet/wcf including the wsdl and a description of the problem you are having with the generated code.
