### ISSUE TITLE
`readonly set` example is a confusing practice

### ISSUE THREAD

**Issue by itowlson** [dotnet/docs#13841]
The following example confused a colleague:

```
readonly set
{
  this._store["Prop1"] = value;
}
```

The mutation of the contents of the `_store` member is certainly legal, because the `_store` reference itself is not changed.  But there is a sense in which a setter like this is changing the _content_ (value) of the object.  I would suggest:

1. A bit of explanatory text explaining why it is legal for a `readonly` member to call a mutating method on a reference member (because it is not changing the reference)
2. Guidance that mutating a reference member might surprise users of the object, who might expect a `readonly` type to be immutable, and advice on when it is reasonable to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221c58d8-4762-c228-92b5-14f44e2d4867
* Version Independent ID: 790ca059-c9c5-48e8-b50e-6e533549b974
* Content: [Readonly Instance Members - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members#feedback)
* Content Source: [proposals/csharp-8.0/readonly-instance-members.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/readonly-instance-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
FYI @BillWagner this article isn't in the TOC.

**Comment by BillWagner** [comment]
I'll handle this as part of the project to update and publish the remaining C# 8 specs.
