### ISSUE TITLE
Point out this only serves users of the MS DI container or ASP .NET Core.

### ISSUE THREAD

**Issue by SittenSpynne** [dotnet/docs#13850]
The only way to configure HttpClientFactory is through the MS DI container. If you are using any other DI container, that container is forced to support the MS DI container infrastructure or there is no way for you to use IHttpClientFactory yourself. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by SittenSpynne** [comment]
Documentation around the type frequently says it's for ".NET Core applications" but it specifically means ".NET Core applications that specifically use the Microsoft DI container."

**Comment by tdykstra** [comment]
cc @rynowak

**Comment by mvelosop** [comment]
Hi @SittenSpynne,

I'll add a note to on this guide so readers are aware of what you comment.

Perhaps you might find the discussion in issue https://github.com/aspnet/Extensions/issues/1345 useful to you.

Anyway, there's an issue (https://github.com/aspnet/AspNetCore.Docs/issues/11882) to include guidance on this topic.

Hope this helps.
