### ISSUE TITLE
`readonly ref` is written as `ref readonly` multiple times

### ISSUE THREAD

**Issue by cypressious** [dotnet/docs#13868]
According to Visual Studio 2019, `ref readonly struct` does not compile, only `readonly ref struct`.

![grafik](https://user-images.githubusercontent.com/1191816/63151565-153c7380-c00a-11e9-9325-6a897a2f8595.png)

The documentation contains multiple instances of `ref readonly`, they should probably be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref#ref-struct-types)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
You're right. Do you want to submit a Pull Request to fix this issue? (You can use the Edit button to make that easier, if you want to.)

**Comment by cypressious** [comment]
@svick done
