### ISSUE TITLE
Debian / Raspbian dependencies

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#13864]
Hi,

The following section could be added to the Linux distribution dependencies part. The dependencies are very similar but not the same as the Ubuntu ones. The Raspberry Pi (with Raspbian, based on Debian) is also great for running .NET Core.

While I think placing the codename behind the version (jessie, stretch & buster) makes it a bit ugly/crowded, it makes it easier to identify the correct version for less technical people. The RPi Foundation almost exclusively refers to Raspbian with "Raspbian Buster" and not "Raspbian 10".

Debian / Raspbian distributions require the following libraries installed:

- liblttng-ust0
- libcurl3 (for 8.x jessie and 9.x stretch)
- libcurl4 (for 10.x buster)
- libssl1.0.0 (for 8.x jessie)
- libssl1.0.2 (for 9.x stretch)
- libssl1.1 (for 10.x buster)
- libkrb5-3
- zlib1g
- libicu52 (for 8.x jessie)
- libicu57 (for 9.x stretch)
- libicu63 (for 10.x buster)

For versions earlier than .NET Core 2.1, following dependencies are also required:

- libunwind8
- libuuid1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@rowanmiller @richlander 

You two know more about this than I, I think :) Can you comment?

**Comment by rowanmiller** [comment]
+ @leecow

**Comment by xenogew** [comment]
Still got "No usable version of the libssl was found"

What should I fix?
I try to use it to copy "work.log" file into Azure File, and do it with gitlab-ci job with "image: python:3.7" (which base on Debian buster).

All I did is following your guide and install what you told me to install but still got the same message. Do you plan to upgrade use other version of libssl like 1.1+?

**Comment by goigle** [comment]
@xenogew The fix that worked for me was in this thread:
https://github.com/dotnet/corefx/issues/33179#issuecomment-509384528

`export CLR_OPENSSL_VERSION_OVERRIDE=1.1`
This forces it to use libssl1.1
