### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mikewesthad** [dotnet/docs#13863]
Looks like the link for Custom Radial Panel Sample (https://archive.msdn.microsoft.com/Project/Download/FileDownload.aspx?ProjectName=wpfsamples&DownloadId=7785) is broken. A quick Google for "Custom Radial Panel Sample" didn't turn up any msdn links that looked like the correct link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5e953b-fb20-c4e6-2ff4-cc8de60d63f3
* Version Independent ID: 0daa135b-5be3-5fee-c976-d3b02ba11e3d
* Content: [Layout](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/layout#feedback)
* Content Source: [docs/framework/wpf/advanced/layout.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/layout.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the broken link, @mikewesthad. I can't find the example either, so I've opened #13924 to remove it.

**Comment by mikewesthad** [comment]
@rpetrusha thanks!
