### ISSUE TITLE
Some C# operator articles have incorrect titles, file names and TOC entries

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1387]
It seems that when the content was migrated, some [C# Operators](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/operators/) articles didn't have their titles, file names and TOC entries migrated properly. Specifically (empty cells are fine):

| Operator | Title | File name | TOC entry |
|---|---|---|---|
| `[]` | Operator | | Operator1 |
| `-` | | | - Operator2 |
| `/` | | | - Operator1 |
| `-=` | | subtraction-assignment-operator-1 | -= Operator2 |
| `/=` | | subtraction-assignment-operator | -= Operator1 |

cc: @BillWagner

**Comment by svick** [comment]
Looks like VB is even worse, [its `\=` is very broken](https://docs.microsoft.com/en-us/dotnet/articles/visual-basic/language-reference/operators/subtraction-assignment-operator).

**Comment by BillWagner** [comment]
Adding @stevehoag for the VB discussion. Should we open a new issue for the VB.NET operator titles?

**Comment by svick** [comment]
@BillWagner Since #1389 is already merged, I don't see why (unless I missed something in that PR).

**Comment by BillWagner** [comment]
@svick I didn't see changes on the VB operator titles in this PR.  Did I miss them?

**Comment by svick** [comment]
@BillWagner I created two PRs: #1388 for C#, which you merged and #1389 for VB, which was merged by @stevehoag. So I think there's nothing else to do here, unless I am the one who is missing something.

**Comment by BillWagner** [comment]
@svick Thanks. I had not looked at #1389 and that's why I wondered. I'm glad it's all good
