### ISSUE TITLE
Intermittent "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by ianfallon** [dotnet/docs#13875]
I'm using this example code as the basis for a very simple client - server socket application (64 bit .NET Framework v4.6.1, C#) but I am seeing intermittent exceptions from the BeginSend() call.

I have been looking at the thread IDs of the handling code. The only pattern of failure I can see is it appears to fail if the async socket handling ends up handling a 2nd message on the _same_ thread rather than a _new_ thread.

Is there an issue in the example code where if this happens the send back to the calling client will fail with "An existing connection was forcibly closed by the remote host" ? I can't see I'm doing anything materially different from the example code in terms of the socket handling.

This is the exception:

Exception Information Details:
======================================
Exception Type: System.Net.Sockets.SocketException
Message: An existing connection was forcibly closed by the remote host
Error Code: 10054
Help Link: 
HResult: -2147467259
Native Error Code: 10054
Socket Error Code: ConnectionReset
Source: System
Target Site: System.IAsyncResult BeginSend(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.AsyncCallback, System.Object)
16/08/2019 16:55:34 : 15 : STACK:    at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example#feedback)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by bigrbuk** [comment]
Did you get anywhere with this? I'm having similar issues.

**Comment by mairaw** [comment]
Thanks for your feedback @ianfallon. @davidsh is this something you can help with?
