### ISSUE TITLE
Missing ML Tasks

### ISSUE THREAD

**Issue by bamurtaugh** [dotnet/docs#13880]
This page should include all the ML tasks supported by ML.NET. For instance, Time Series, Anomaly Detection.

[AB#1596627](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596627)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks#feedback)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Thanks for raising this @bamurtaugh . Anomaly Detection is there. We're working on Time Series and Deep Learning.

**Comment by JranZu** [comment]
What about reinforced learning?  Does ML.Net support that?
