### ISSUE TITLE
Serve Model in ASP.NET Core Web API - PowerShell Body Correction

### ISSUE THREAD

**Issue by JaimeStill** [dotnet/docs#13886]
In the [Serve a Model in ASP.NET Core Web API](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md) doc, the property set in the `-Body` argument of the PowerShell command should be `SentimentText`, not `Text`.

```ps
Invoke-RestMethod "https://localhost:5001/api/predict/predictSentiment" -Method Post -Body (@{SentimentText="This was a very bad steak"} | ConvertTo-Json) -ContentType "application/json"
```

Sending the above as `Text` populates `null` into the `SentimentText` property of the serialized `SentimentData` object, which would in turn yield a **Negative** response. Changing the above to `SentimentText="This was a very good steak"` yields a **Positive** response.

edit by @mairaw: added document details
 
[AB#1579020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579020)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dce49db-3548-7dad-bdb1-812efde7ac86
* Version Independent ID: 390a9c7a-2537-25ca-c041-0284c253acff
* Content: [Deploy a model in an ASP.NET Core Web API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Good catch @JaimeStill . Put in a PR for it and the changes should be reflected shortly. Thanks for bringing it up.
