### ISSUE TITLE
Meta description typo

### ISSUE THREAD

**Issue by DavidHogue** [dotnet/docs#13883]
The meta description doesn't match the content of the page. When I paste the link into Slack for example, I see this typo: "Data sovereignty per microservice is one of the kay point of microservices."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81283b66-f8c6-4d93-73c8-551e1681f51e
* Version Independent ID: c637cf8d-163a-4717-371f-2ff40d61f314
* Content: [Data sovereignty per microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice#feedback)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thank you for your feedback @DavidHogue. I've opened PR #13885 to fix this.
