### ISSUE TITLE
Update documentation related to CSPROJ Format to Include WPF Default Items

### ISSUE THREAD

**Issue by rladuca** [dotnet/docs#13884]
Updates for the following document:
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects

There need to be a new section for WPF projects on .NET Core.  In this section, we should expose the default items specific to WPF and what switches control them.

In the same vein as the `Default compilation includes .NET Core projects` section, probably named `Default includes in WPF on .NET Core projects`, we need the following:

* A similar table with the following data:
  * Element: ApplicationDefinition
    * Include Glob: App.xaml or Application.xaml (if exists)
    * Exclude Glob: N/A
    * Remove Glob: N/A
  * Element: Page
    * Include Glob: `**/*.xaml`
    * Exclude Glob: `**/*.user; **/*.*proj; **/*.sln; **/*.vssscc;` and `Any XAML included in ApplicationDefinition`
    * Remove Glob: N/A
  * Element: None
    * Include Glob: N/A
    * Exclude Glob: N/A
    * Remove Glob: `**/*.xaml`

Similar text that says something like:
```
If you have XAML globs in your project and you build with the latest SDK, you'll possibly get one (or both) of the following errors:

* Duplicate 'ApplicationDefinition' items were included.
* Duplicate 'Page' items were included.

In order to get around this error you can either remove the explicit `Page` or `ApplicationDefinition` items that match the ones listed on the previous table, or you can set `<EnableDefaultApplicationDefinition>` and/or `<EnableDefaultPageItems>` to false accordingly.  You can also set `<EnableDefaultItems>` to false to disable both at the same time, though this has other side effects as well.

Setting these to false will revert to the behaviors of previous SDKs where you had to specificy the default globs in your project.
```

I think that covers all of the globbing controls similarly to how .NET had previously done it.

@grubioe FYI
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
I feel this is related to P0 backlog item to document all the csproj tags not just for WPF: https://github.com/dotnet/docs/issues/2642

@Thraka I wouldn't like to add any more content to this current page and instead start the work to document the SDK-style project reference as we previously discussed.

Make sure you set priorities and milestone here since you've assigned this to yourself already.

**Comment by mairaw** [comment]
But it's fine to add here in this topic the default glob values.

**Comment by grubioe** [comment]
@Thraka - do you have an ETA on when [this document](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects) will be updated to reflect WPF default items?  Thanks

**Comment by Thraka** [comment]
@grubioe 

We're not adding any information to this article specifically. We're redesigning this article from the ground up. #2642 is tracking that work, when that happens, this would issue would be addressed as part of that work.

**Comment by grubioe** [comment]
Got it, thanks.  Based on the projects, assuming 2642 will be done in November?

**Comment by Thraka** [comment]
I just modified that as an optimistic choice. We do have another writer working on this stuff now so I'm hoping it will be done then 😄

**Comment by gewarren** [comment]
This default include/excludes info now lives here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-includes-and-excludes. @adegeo This is assigned to you; do you plan to add it or do you want me to?

**Comment by adegeo** [comment]
> This default include/excludes info now lives here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-includes-and-excludes. @adegeo Andy De George FTE This is assigned to you; do you plan to add it or do you want me to?

I'll add it, thanks!

**Comment by gewarren** [comment]
@adegeo Do you want to reopen this one?

**Comment by adegeo** [comment]
Thanks @gewarren 

@rladuca Can you just verify that this issue is still up-to-date with those values? I know it's been a year since it was filed.
