### ISSUE TITLE
Copy and paste with a shotgun

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/docs#13895]
Would it be possible to put this page in the correct order?
For instance, in "Create a display utility method", there is a sentence
"The Transform() method populated ImagePath in ImagePrediction along with the predicted fields."
We have, at that point, not seen the Transform() method, nor ImagePrediction.
This is not about the sentence in particular, but the whole structure(sic) of the page, which looks like a full program has been loaded into a shotgun and shot at the page, with random pieces of code all over the place. In order to try to follow we have to scroll up and down the page continuously.
This is one of the better described pages available, but I cannot follow what is going on logically.

[AB#1596621](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596621)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Retrain TensorFlow image classifier - transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment]
Thanks for the feedback @nfnpmc. 

This issue can be added to AB#1596621

**Comment by natke** [comment]
Fixed by #14531. @nfnpmc, we'd love if you would take another look at the tutorial and let us know what you think!

**Comment by nfnpmc** [comment]
Hi Nat,
Somebody has done a brilliant job of sorting out that page, thanks very much.

Regards, nfnpmc 

    On Friday, 27 September 2019, 22:58:43 BST, Nat Kershaw (MSFT) <notifications@github.com> wrote:  
 
 
Fixed by #14531. @nfnpmc, we'd love if you would take another look at the tutorial and let us know what you think!

**Comment by natke** [comment]
Thank you @nfnpmc!  That was me :-)
