### ISSUE TITLE
Need to create a Windows Forms guide for .NET Core

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13893]
## Need to create a Windows Forms guide for .NET Core

Currently, we don't have a place for .NET Core-specific content related to Windows Forms. One should be created. There are several existing candidates for inclusion:
- [Accessibility improvements in Windows Forms controls for .NET Core 3.0](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/windows-forms-accessibility-improvements.md). This is currently located in the .NET Framework Guide.
- [How to: Port a Windows Forms desktop app to .NET Core](https://github.com/dotnet/docs/blob/master/docs/core/porting/winforms.md). This is currently located in the **Porting from .NET Framework** section of the .NET Core Guide.

**Comment by Thraka** [comment]
@rpetrusha Issue #10648 is the planning issue for WinForms. Marked as on hold until the winforms designers are done.

**Comment by merriemcgaw** [comment]
Yep, I've been chatting with @Thraka today in fact.

**Comment by mairaw** [comment]
Removing milestone for now then.

**Comment by merriemcgaw** [comment]
We should try to have something to go for 5.0. That will give us enough time to implement the Designer work that we have to do.
