### ISSUE TITLE
Function list incomplete

### ISSUE THREAD

**Issue by valakiBF** [dotnet/docs#13903]
There are additional string functions in the String module (class)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b539a9b-fd9c-f976-39eb-f9ec93af4577
* Version Independent ID: e31c7343-4126-81b8-b976-5b7bb7d81a39
* Content: [String Functions (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/functions/string-functions)
* Content Source: [docs/visual-basic/language-reference/functions/string-functions.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/functions/string-functions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @valakiBF. Other than [GetChar](https://docs.microsoft.com/dotnet/api/microsoft.visualbasic.strings.getchar), what are the additional missing string functions?

**Comment by valakiBF** [comment]
> Thanks for submitting your feedback, @valakiBF. Other than GetChar, what are the additional missing string functions?
There are some functions in the String class of the System namespace that are more straightforward and easier to use than some corresponding functions in the Strings Module of the Microsoft.VisualBasic namespace. Namely:
IndexOfAny(Char(),...), LastIndexOfAny(Char(),...), Split(Char(),...), Split(String(),...), Trim/TrimEnd/TrimStart(Char())

**Comment by rpetrusha** [comment]
Thanks for the response and the clarification, @valakiBF. I've opened #14213 to clarify the focus of the article and link to System.String and its methods.
