### ISSUE TITLE
Missing data type 

### ISSUE THREAD

**Issue by heatherzurek** [dotnet/docs#13908]
The do .. while loop is missing the int on counter, its shown as counter = 0; but should be int counter = 0;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1138d70-1d83-a7e5-8549-72bf80dc5834
* Version Independent ID: 0811beda-ff7e-353a-aeb2-6bebe8947bcf
* Content: [Branches and loops - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops-local#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops-local.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/branches-and-loops-local.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I've opened a PR https://github.com/dotnet/docs/pull/13911 for that.
