### ISSUE TITLE
ByVal in VB samples

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#13912]
I think specifying `ByVal` for method arguments makes the code look noisy. It will be much cleaner to write:

```vb
Private Function FunctionName(arg1 As Type1, arg2 As Type2)
End function
```
instead of:

```vb
Private Function FunctionName(ByVal arg1 As Type1, ByVal arg2 As Type2)
End function
```

There are many code samples I've seen so far that has `ByVal` specified for method arguments.
Should you consider updating these samples ?

**Comment by rpetrusha** [comment]
Since `ByVal` is the default, it doesn't have to be explicitly specified. I agree with you, @Youssef1313, that is noisy. It also has the unfortunate effect, in my experience, of causing the occasional `ByRef` keyword to be overlooked. So it would be useful to remove it.
I'll add this item to our backlog and the Community Contributor's project. If you're interested in removing ByVal from some or all of the examples, try to submit PRs that touch a small subset (approximately 100 or so) of files at a time.

**Comment by paul1956** [comment]
There should be a CodeFix for removing ByVal and there may be third party tools that can do it for a whole project.

**Comment by Youssef1313** [comment]
@paul1956 , I thought of that. but I'm not sure if unintended removal could be done in an automated solution. For example, the ByVal article itself has a code example, `ByVal` should NOT be removed there.
I'm not sure if there could be other places where `ByVal` shouldn't be removed.

**Comment by paul1956** [comment]
A CodeFix only operates on "Code" and is smart enough to do the right thing, it can also be interactive.

**Comment by Youssef1313** [comment]
@paul1956 , I'll try to do that soon when I get free time and see if I could get good results.

**Comment by paul1956** [comment]
I would be happy to post/contribute a standalone remove ByVal analyzer and refactoring if you think its interesting. It is very small.

**Comment by Youssef1313** [comment]
Well, you can start that anytime and submit a **small** PRs ( as suggested by @rpetrusha ) if you want and they will review it, @paul1956 .

**Comment by paul1956** [comment]
I would like to start with correctly documenting line continuation in VB 16 I looked at the special character $ and has a line [!CODE-vb[interpolated-string-symbol](../../../../samples/snippets/visualbasic/language-reference/special-characters/dollar-sign1.vb)] which seems to do no where in the Doc GitHub repo. does [!Code-vb have some special meaning?

**Comment by Youssef1313** [comment]
[!code-lang....] is used in .md files to include a code sample.
That is how to refer to a code in the samples repo from the docs repo.
but I don't think you will find any [!code-lang...] in the samples repo. (Not very sure)

**Comment by paul1956** [comment]
Tried doing a Pull Request and I get Error 500
![image](https://user-images.githubusercontent.com/12789369/63509873-10584380-c492-11e9-89fd-052e8bc05388.png)

**Comment by paul1956** [comment]
I was working on the Doc Repo because I didn't see any VB code that needs work, The Doc's need updating for VB 16 and Core 3.0 and it seemed like a good place to start since there are lots of examples.

**Comment by paul1956** [comment]
Which Repo should I be looking at to find the VB code that needs moving? Can you provide a URL for the repo with 100  files that need ByVal removed it will only take a few minutes to do using a code fix I have.

**Comment by Youssef1313** [comment]
I think you may start with [samples](https://github.com/dotnet/samples/) repo, surely it has more than 100 files containing `ByVal`. But the work can be splitted into multiple PRs, each has about 100 files changed as suggested by @rpetrusha

**Comment by paul1956** [comment]
Many of the sample use older project formats, is it OK to upgrade to latest format? Eventually to get on Core will require format changes anyway.

**Comment by Thraka** [comment]
FYI The automatic code inserted by visual studio snippets and autocomplete insert ByVal.

**Comment by Youssef1313** [comment]
@Thraka, Do you mean the auto generated code like the designer file for winforms for example ?

If yes. Then, In most cases, no one looks at that code. The more important is the code that the developer write himself. It looks much nicer without the noise produced by `ByVal`.

**Comment by paul1956** [comment]
From what I understand the snippets in this repo are used to produce the product Snippets so my eliminating them here part of the issue is solved. I agree that eliminating them  in all in the templates and the "System." in the Form Boilerplate would be great, not sure where to report the issue.

**Comment by Thraka** [comment]
No I was thinking of something else, never mind :)
