### ISSUE TITLE
Please document the correct procedures for using C# 8's non-nullable reference types in EntityFramework and IOptions

### ISSUE THREAD

**Issue by BenjaminCharlton** [dotnet/docs#13914]
I was reading about the C# 8 language feature that allows you to specify whether a reference type variable expects null values or not, right here:

https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/upgrade-to-nullable-references

I liked the idea of getting compile-time warnings based on whether a type was intended to be nullable or not. I immediately started migrating my projects to C# 8 and enabling nullable reference types, but found a few cases where I got stuck. I would like the documentation to explain the correct pattern to follow in the following cases, please?

1. Using Entity Framework Core you are forced to have a parameterless constructor on the type even if you know it's bad practice. This is to allow EF to construct the type from the database for you. It is acceptable to have just a private constructor but it has to be there so you still see warning CS8618 about non-nullable properties not being instantiated properly. What should you do?

2. Using the IOptions<T> pattern for dependency injection you are forced to have a parameterless constructor on the type even if you know it's bad practice. I guess this is to allow the object to be scaffolded from appsettings.json and injected into your constructor by the runtime. Whatever the reason, it's mandatory. Unlike in Entity Framework, you can't make it private. It has to be public so you still see warning CS8618. What should you do?

3. Using AutoMapper also requires types to have a parameterless constructor.

Hope the feedback is helpful and hope to see some guidance on how to solve these issues.

Thank you!

Benjamin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dfe2629-7f0f-5ab7-6bf3-af84b050c425
* Version Independent ID: 17533d4f-fae1-0883-8838-4ba7c0727bc7
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/upgrade-to-nullable-references)
* Content Source: [docs/csharp/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
This seems like an important scenario to document, thank you for pointing it out.

**Comment by diryboy** [comment]
From https://stackoverflow.com/a/57343485/71312

> Whenever you want to tell the compiler "shut up, I know what I'm doing" in regards to nullable reference types, use the `!` operator.
`public DbSet<Probe> Probes { get; set; } = null!;`

**Comment by BillWagner** [comment]
tagging @ajcvickers @smitpatel and @roji 

Should this be addressed in the C# docs under nullable reference types, or in the EF Core docs? It's an important scenario, and we should address guidance based on plans for the evolution of the tools.

**Comment by smitpatel** [comment]
We have article in EF Core docs about NRT and guidance. https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types

Any feedback to improve it is welcomed. 😃

**Comment by BillWagner** [comment]
Thanks @smitpatel That article does answer all the questions I've seen related to NRT and EF Core.  The article referenced in this issue should link to [the EF guidance](https://docs.microsoft.com/ef/core/miscellaneous/nullable-reference-types) (Note the removal of the "en-us" locale so links direct readers to the correct culture for all readers.

I've added the "up for grabs" label for community members that might be interested in creating the PR.

**Comment by ajcvickers** [comment]
@BillWagner Note that statement 1 above is incorrect. EF Core supports parameterized constructors, although with some limitations.

What are the questions you have seen that are not addressed?

**Comment by BillWagner** [comment]
> What are the questions you have seen that are not addressed?

The most common question I received was relating to initializing the `DbContext` and `DbSet` in scenarios where developers are enabling NRT on an existing application. [This section](https://docs.microsoft.com/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset) in the article @smitpatel referenced answers it well.

**Comment by leotsarev** [comment]
Thanks, but we are still missing IOptions guidance....
