### ISSUE TITLE
Migrating Code Gallery examples to the Samples Browser

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13921]
## Migrating Code Galley examples to the Samples Browser

At some future point, [Code Gallery](https://code.msdn.microsoft.com/) will be retired. Samples that I worth preserving should be migrated to the new [Samples Browser](https://docs.microsoft.com/samples/browse). This issue outlines the steps in the migration.

All samples should be migrated as **.NET Core applications** rather than .NET Framework libraries or desktop applications. In addition, many examples combine C# and Visual Basic source code. The two languages should be separated so that they are independently downloadable.

### Migrating from Code Gallery to the Samples Browser

Migration involves the following steps:
1. Select a sample to be migrated from the existing open issues in the [Code Gallery Migration project](https://github.com/dotnet/docs/projects/88) and indicate in the issue that you are working on the migration. 

   Some of the samples are actually large collections of samples, with parallel samples in Visual Basic and C#. If you are interested in working on only one or more of these in a single language or in both languages, open an issue indicating that you are working on that individual sample's migration and refer to the parent issue in your issue.

   If there is a Code Gallery sample that is not listed in the project, you can create an issue to migrate it. We will add it to the **Under consideration** column of the project.

2. Some of the existing issues represent samples that consist of large numbers of samples. In most cases, these should be broken down into a smaller subset of examples. If you're migrating only a single example or subset of examples from a multi-example project, clearly indicate in the issue which examples you're migrating.

3. Once you've selected the examples you'd like to migrate, use the [.NET Portability Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) to identify issues that you'll have to address when converting a .NET Framework project to a .NET Core project.

4. Select where in the dotnet/samples repo the sample should go. The top-level directory should represent the general technology area of the sample, with any additional subdirectories serving to further identify it. For example, the [HttpClient sample](#13767) could be placed in */samples/networking/httpclient*.

5. If the sample has multiple versions, they should be placed in separate subdirectories (such as *cs* and *vb*) of this directory.
 
6. For information on porting individual project types from .NET Framework to .NET Core, see [Port your code from .NET Framework to .NET Core](https://docs.microsoft.com/dotnet/core/porting/).

7. Some of the code is quite old and doesn't follow current best practices. Where possible, modernize the code and, for C# code, take advantage of the latest language features if they are useful. For example, objects that implement `IDisposable` should be wrapped in a `using` statement. Interpolated strings should be used instead of composite format strings. 

8. Where possible, eliminate unused files and features. For example, assembly information is managed by .NET Core, so an *AssemblyInfo.cs* or *AssemblyInfo.vb* file can be removed. And if you're not using the `My` namespace in Visual Basic, its files can also be removed.

9. Create one *readme.md* file for each downloadable sample. The *readme.md file should be in the sample root directory and should describe the sample, explain how to use or run it, and contain any other pertinent information. For examples of the content that you might include in a *readme.md* file, see the individual tiles in the [Samples Browser](https://docs.microsoft.com/samples/browse). 

   The *readme.md* file also requires metadata to make it accessible to the Samples Browser. Metadata is placed at the beginning of the *readme.md* file. The metadata items are:

   - **languages**. Valid values are **csharp** for C# and **vb** for Visual Basic. For example:
      ```
      languages:
      - csharp
      - vb
      ```
   - **products**. Since all migrated samples should run on .NET Core, **dotnet-core** should always be used. For WPF, WinForms, and Windows-only apps, **windows** should also be used. For example:
      ```
      products:
      - dotnet-core
      - windows
      ``` 
   - **page_type**. This should always be `page_type: sample`.
   - **name**. The name of the sample. This should be as short as possible while uniquely identifying the sample. If there are multiple versions of the sample (for example, one for C# and one for Visual Basic), they should be clearly disambiguated by the name.
   -  **description**. A description of the sample, which must have fewer than 150 characters. This field is optional; if absent, the example description defaults to the first 150 characters of the level-1 head in the *readme.md* file.
   - **urlFragment**. The URI fragment of the sample. This field is optional, though it is generally a good idea to supply it. It is particularly important when there are two language versions of the same sample, For example, `urlFragment: "great-sample-cs"` defines a URI fragment that is clearly distinct from `urlFragment: "great-sample-vb"`.  <p />

   The following is an example of the metadata section, taken from the [WinForms Formatting Utility for C#](https://docs.microsoft.com/en-us/samples/dotnet/samples/winforms-formatting-utility-cs/):
      ```
      ---
      languages:
         - csharp
       products:
         - dotnet-core
         - windows
      page_type: sample
      name: ".NET Core WinForms Formatting Utility"
      urlFragment: "winforms-formatting-utility-cs"
      description: "A .NET Core Windows Forms application that allows you to apply standard or custom format strings."
      ---
      ```
1. Open a PR in the [dotnet/samples](https://github.com/dotnet/samples/pulls) repo to add the sample.

**Comment by rpetrusha** [comment]
//cc @KathleenDollard

**Comment by paul1956** [comment]
Looking for VB Samples to port and having trouble finding them, the link above takes you back to this page.

**Comment by rpetrusha** [comment]
The **To migrate** column of the [Code Gallery Migration project](https://github.com/dotnet/docs/projects/88) contains samples that we'd like to see migrated to the dotnet/samples repo, @paul1956.
