### ISSUE TITLE
Approx. half of the linked user stories result in 404 errors

### ISSUE THREAD

**Issue by UweKeim** [dotnet/docs#13932]
Looking at the user stories/customer stories over at [dotnet.microsoft.com/platform/customers](https://dotnet.microsoft.com/platform/customers), I discovered that approx. half of them lead to 404 pages.

E. g.:

- https://customers.microsoft.com/story/stacked-for-speed
- https://customers.microsoft.com/story/age-of-ascent-an-ultra-mmo-game-powered-by-azure

and possibly others. They all end on a page stating:

> The customer story you are looking for is no longer available.

My suggestion is to either fix the dead links or remove the user stories.

**Comment by Thraka** [comment]
Thank you for reporting. I've sent an email asking for this to be investigated.

**Comment by rowanmiller** [comment]
This is now resolved. Many thanks for reporting it.

**Comment by Thraka** [comment]
Thanks everyone
