### ISSUE TITLE
Language version Visual Studio 2017-2019

### ISSUE THREAD

**Issue by jlterheide** [dotnet/docs#13937]
The default has changed from latestMinor to latestMajor in VS 2019. This is a breaking change, Jenkins  build failed on c# 7.3 features.
If I change the version to 'latest major' in the project build properties the value in the project file is 'latestmajor' (note the lowercase 'm') but Jenkins recognizes neither casing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#feedback)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Please file a request with the [Visual Studio 2019 feedback](https://developercommunity.visualstudio.com/content/problem/689165/feedback-visual-studio-community-2019.html) and Jenkins.

@BillWagner Bill, would it be useful to list Visual Studio defaults? The support table is probably using .NET Core template defaults.

**Comment by KalleOlaviNiemitalo** [comment]
@jlterheide, I am curious how you can get an error where "Jenkins recognizes neither casing".  In our CI setup, Jenkins locates and runs MSBuild but does not itself attempt to recognize the language version settings in the C# project files.

**Comment by jlterheide** [comment]
I wil try to clarify:

What we had (VS 2019) was:
                var resultaat = insertActionlog(AvgLoggingActie.RelatieAanmaken,
                               medewerkernummer, gebruikersnaam: medewerkernummer.HasValue ? "vkg" : gebruikersnaam,
                               tekst,
                               adviseurnummer,
                               relatienummer);

This is a c# 7.2 feature and Jenkins complains:

AvgLogging.cs(62,5): error CS1738: Named argument specifications must appear after all fixed arguments have been specified. Please use language version 7.2 or greater to allow non-trailing named arguments. [C:\Gitlab-Runner\builds\sQzde1Ts\0\vkg-net\TOP\LevelDatabaseFuncties\LevelDatabaseFuncties.csproj]

So I changed the language version to de VS 2017 default “LatestMajor” (using the VS 2019 user interface) which should equal “7”. Now Jenkins complains as well:

CSC : error CS1617: Invalid option 'latestMajor' for /langversion. Use '/langversion:?' to list supported values. [C:\Gitlab-Runner\builds\sQzde1Ts\0\vkg-net\TOP\LevelDatabaseFuncties\LevelDatabaseFuncties.csproj]

Notice the lowercase in ‘latestMajor’. Changed that to ‘LatestMajor’ with a tekst editor (Notepad++) but get the same error, changed to ‘7’ and we are back to the first error (as expected, must change the code to be c# 7.0 compliant to work with the MSbuild version Jenkins uses).

The build command looks like this:

[32;1m$ "%CI_MSBUILD%" "%PROJECT_NAME%.sln" %MSBUILD_OPTIONS% /p:PublishProfile=Test /p:Configuration=Test[0;m

Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

I think it is not so much a Jenkins problem as a MSbuild issue. How can we tell Jenkins to use a newer MSbuild?

M.vr.gr.
Jan Luc.

________________________________
Van: KalleOlaviNiemitalo <notifications@github.com>
Verzonden: Tuesday, August 27, 2019 10:57:21 PM
Aan: dotnet/docs <docs@noreply.github.com>
CC: jlterheide <j.l.ter.heide@live.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [dotnet/docs] Language version Visual Studio 2017-2019 (#13937)


@jlterheide<https://github.com/jlterheide>, I am curious how you can get an error where "Jenkins recognizes neither casing". In our CI setup, Jenkins locates and runs MSBuild but does not itself attempt to recognize the language version settings in the C# project files.

**Comment by KalleOlaviNiemitalo** [comment]
@jlterheide, I don't use the [MSBuild plugin for Jenkins](https://plugins.jenkins.io/msbuild), originally because of [JENKINS-26948](https://issues.jenkins-ci.org/browse/JENKINS-26948 "\[JENKINS-26948\] Workflow compatibility for MsBuildBuilder - Jenkins JIRA"). Instead, I use a Jenkinsfile that runs vswhere.exe, reads the installation directory from the output, and runs MSBuild.exe from there. If the build servers had multiple versions of Visual Studio Build Tools installed and I needed to specify which version to use for the build, I think I would add the `-version` option to the vswhere.exe invocation.
