### ISSUE TITLE
Can not find the official download address of locbaml tool, the link inside is wrong!

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13946]
@jasonfint commented on [Tue Aug 20 2019](https://github.com/dotnet/docs.zh-cn/issues/435)

[Enter feedback here]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [如何：对应用程序进行本地化](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@srvbpigh commented on [Tue Aug 20 2019](https://github.com/dotnet/docs.zh-cn/issues/435#issuecomment-522874501)

你好，@jasonfint
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
the reported link is also broken in the en-us version
(The comment was Machine translated from zh-CN)

**Comment by pkulikov** [comment]
Fixed by #13934
