### ISSUE TITLE
#pragma warning - what is the COMPLETE list of possible values for the third term?

### ISSUE THREAD

**Issue by the-Arioch** [dotnet/docs#13949]
This page claims that there is only a binary choice of options

* #pragma warning disable NNNNN
* #pragma warning restore NNNNN

and there is no any other option for the third term neither given nor referenced outward.
So, the wording is that the choice is binary and no other options are allowed. 

However https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

In that article we also see two more options: "safeonly" and "enable".

That looks like a confusion if not contradiction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68010f2-39f6-6de9-43f8-342dc5bdfa36
* Version Independent ID: 002be4de-f321-1760-d4ec-2b729f149562
* Content: [#pragma warning - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello.

According to #13227 it looks like the safeonly stuff is no longer supported.

Are you asking what is available to put in the NNNNN part of your quote?

**Comment by KalleOlaviNiemitalo** [comment]
Support for `#pragma warning enable` was removed in <https://github.com/dotnet/roslyn/pull/37192>.

**Comment by BillWagner** [comment]
This is an area that hasn't been updated as well as we could. I've added to a project we're using to track requests and come up with a plan.

**Comment by the-Arioch** [comment]
yes, i think there should be an authoritative reference containing up to dat list of all possible NNNNN values/tokens/identifiers

**Comment by BillWagner** [comment]
The latest updates to the #nullable pragma have updated this so the `#pragma warning` only accepts `disable` and `restore`.

Closing as the product and the docs now match.
