### ISSUE TITLE
IMetaDataAssemblyImport::FindAssembliesByName - Usable or deprecated?

### ISSUE THREAD

**Issue by colin-higgins** [dotnet/docs#13957]
**Issue description**

Is the IMetaDataAssemblyImport::FindAssembliesByName method in a usable state or is it something that can't be relied on?
For context, this is on net45 and above that I have seen this behavior, but also netcore2.1

https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/metadata/imetadataassemblyimport-findassembliesbyname-method.md

In trying to call it in native code I only ever received `INVALID_POINTER` results from the HRESULT of the call.

```
hr = metadata_import->FindAssembliesByName(
        app_directory.c_str(), 
        private_bin, 
        assembly_name.c_str(),
        result_pointer, 
        max_matches, 
        matching_assembly_count);
```

I was looking for examples to figure out where I went wrong and ultimately had to abandon it as a solution.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

</details>

edit by @mairaw: added document details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dbb70b8-752c-c8ad-8daa-94766af14952
* Version Independent ID: 2ab9b0f4-a002-56d5-efad-17599b256f0b
* Content: [IMetaDataAssemblyImport::FindAssembliesByName Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataassemblyimport-findassembliesbyname-method)
* Content Source: [docs/framework/unmanaged-api/metadata/imetadataassemblyimport-findassembliesbyname-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/metadata/imetadataassemblyimport-findassembliesbyname-method.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@noahfalk can you help with this question?

**Comment by noahfalk** [comment]
It appears [unsupported]( https://github.com/dotnet/coreclr/blob/ef7767a3ba1c0a34b55cbd5496b799b17218ca14/src/md/compiler/assemblymd.cpp#L718) but I think @sergiy-k or @jeffschwMSFT teams would own that area and may know more details.

**Comment by jeffschwMSFT** [comment]
@colin-higgins do you have a small repro that we could take a look at?  What is the interaction with .NET Core - is the assembly you are looking for built targeting .NET Core?  Thanks
