### ISSUE TITLE
We should expand the existing documentation to include the new publish msbuild properties and their options

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#13980]
We should add details about the three new publishing options:
  &lt;PropertyGroup&gt;
    &lt;PublishTrimmed&gt;true&lt;/PublishTrimmed&gt;
    &lt;PublishReadyToRun&gt;true&lt;/PublishReadyToRun&gt;
    &lt;PublishSingleFile&gt;true&lt;/PublishSingleFile&gt;
  &lt;/PropertyGroup&gt;

In addition we should include all the optional configuration settings as well.
https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface
https://aka.ms/dotnet-illink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by swaroop-sridhar** [comment]
https://github.com/dotnet/docs/issues/13149

**Comment by mairaw** [comment]
It's fine @swaroop-sridhar. I'll review this article next as I update the CLI reference docs and then we can check what's left on the original issue.

**Comment by NextTurn** [comment]
What about the "old" property `PublishDir`? dotnet/cli#8405
