### ISSUE TITLE
Resource Name - Correction

### ISSUE THREAD

**Issue by nerobianchi** [dotnet/docs#13985]
Not Charles Richardson, Chris Richardson is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: b409992c-312e-639d-182b-2067e3561273
* Content: [The API gateway pattern versus the direct client-to-microservice communication](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern#feedback)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thank you for your feedback @nerobianchi. I've opened PR #13986 to fix this.

You can also edit our articles when you find something wrong. For more information about this, see https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
