### ISSUE TITLE
Confusing generic parameter name for `Unsubscriber<BaggageInfo>`

### ISSUE THREAD

**Issue by CoolBots** [dotnet/docs#13991]
The generic parameter name for class `Unsubscriber<BaggageInfo>` is, unfortunately (and, likely, inadvertently) named the same as the class `BaggageInfo`. To alleviate any confusion, may I suggest changing the generic parameter to `T`, or even to `TBaggageInfo`, if it is semantically important to show that the type is in fact meant to be of type `BaggageInfo` (although the `Unsubscriber<T>` looks pretty generic; perhaps, a `where` constraint can be used to limit the type, as the write-up does say "Unsubscriber(Of BaggageInfo)...).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8b6ec6-3773-879a-00e9-4bf113b9f362
* Version Independent ID: 5c46289d-8473-623f-eb42-8bda01c30c63
* Content: [Observer Design Pattern](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern#feedback)
* Content Source: [docs/standard/events/observer-design-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/observer-design-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@CoolBots Thanks for the suggestion, but we don’t have the resources to implement it, so we are closing the issue. If we get more 👍 responses to the issue, we’ll reconsider.
