### ISSUE TITLE
What "runtime exception will occur"?

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#13994]
&gt; If any code ever attempts to directly access the value-type member of such an object across an application domain, a runtime exception will occur.

What "runtime exception will occur"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7096ed39-e853-1bc5-e09b-ef7a8ddc0b7f
* Version Independent ID: 799c8d45-8770-6eaf-9195-7e4751bddff2
* Content: [Compiler Warning (level 1) CS1690](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1690)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1690.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs1690.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by KalleOlaviNiemitalo** [comment]
Normative text in ECMA-335 6th edition subclause III.4.11 (ldflda - load field address) says this instruction throws System.InvalidOperationException if attempting to load the address of a field of an object in another application domain.

Informative text in II.14.4 (Pointer types) also mentions that.

**Comment by paulomorgado** [comment]
Shouldn't this be added to the warning documentation, @KalleOlaviNiemitalo?

**Comment by KalleOlaviNiemitalo** [comment]
I don't know.  The warning itself is perhaps becoming obsolete, because .NET Core does not support remoting; it provides a MarshalByRefObject class for compatibility but you cannot get a transparent proxy that would cause a field access to throw the exception.

**Comment by KalleOlaviNiemitalo** [comment]
On the other hand, because ECMA-335 stipulates the type of the exception, it is not an implementation detail of .NET Framework and is unlikely to be ever changed, so there should be no problem with documenting it here too.

**Comment by BillWagner** [comment]
I'm fine adding the details of `InvalidOperationException` to this warning. I agree that it's unlikely to change.

I've added this to our backlog, and added the "up for grabs" label, if someone wants to submit a PR.

**Comment by paulomorgado** [comment]
This is the subject of other discussions, but here goes: is this a "runtime" error, a "run time" error or a "run-time" error?

**Comment by MSDN-WhiteKnight** [comment]
[Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/runtime) uses "runtime".

**Comment by paulomorgado** [comment]
I'm not a native English speaker, but that's just wrong! And with the added cost of making translations also wrong.

**Comment by mairaw** [comment]
Let's start a thread with the folks from the Microsoft style guide @paulomorgado.

**Comment by MSDN-WhiteKnight** [comment]
>I'm not a native English speaker, but that's just wrong! And with the added cost of making translations also wrong.

Why do you think so? And what exactly is "added cost"? For one, "runtime" when used as adjective seems to be more popular then other variants in internet, software GUI captions, etc. (I could understand "run time" if it were used like "exception happens at run time"). For a second, in russian version of article, this phrase is translated pretty OK. Actually, "run time" might be harder for machine translating, because "run" has over 10 meanings that map into different russian words, but "runtime" has only two or so.

**Comment by paulomorgado** [comment]
> The runtime performs run-time functions during run time.
