### ISSUE TITLE
Why is Newtonsoft.Json mentioned when discussing self-contained deployment with third-party dependencies?

### ISSUE THREAD

**Issue by jmoralesv** [dotnet/docs#14006]
Hello,
I'd like to know why Newtonsoft.Json is mentioned in the step 2, regarding self-contained deployments with third-party dependencies. Is that required in order to do a .NET Core self-contained app? When reading the phrase "with third-party dependencies", I think of Nuget packages that my .NET Core app depends on, is that what you meant here? If so, then Newtonsoft.Json is just an example and not a requirement. I think this should be explicitly written because it sounds confusing as is currently written. 

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [Deploy .NET Core apps with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs157#self-contained-deployment-with-third-party-dependencies)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Yes, Newtonsoft is just an example and you're correct that we could be more explicit about that. Adding this to our backlog.
