### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [dotnet/docs#14013]
The Link "Advanced COM Interoperability in .NET Framework" under "See also" does not work (404 - Page not found).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42777759-58fd-e99a-6c02-cb0d40abe879
* Version Independent ID: 8502b0df-6352-cd0f-49ea-9a0a68283131
* Content: [COM Wrappers](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-wrappers#feedback)
* Content Source: [docs/standard/native-interop/com-wrappers.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/com-wrappers.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Youssef1313** [comment]
Works for me
![image](https://user-images.githubusercontent.com/31348972/63607961-0a6a7b80-c5d4-11e9-9ce8-12644a7d87ed.png)

**Comment by Thraka** [comment]
It works for me too. @Science-and-Motion-Sports what locale are you browsing in? I'm on english, perhaps there is a broken link in the translation or something?

**Comment by Science-and-Motion-Sports** [comment]
Sorry, it was caused by a Firefox addon: https://github.com/Arasz/MicrosoftDocsLanguageChanger/issues/7
