### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [dotnet/docs#14014]
The link "Type Library to Assembly Conversion Summary" under "See also" does not work (404 - Page not found).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e12a8d-3503-db34-df9a-84ef6037e86d
* Version Independent ID: 964eee24-e711-8c41-b145-35948c20e774
* Content: [Runtime Callable Wrapper](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/runtime-callable-wrapper)
* Content Source: [docs/standard/native-interop/runtime-callable-wrapper.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/runtime-callable-wrapper.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Youssef1313** [comment]
Works for me
![image](https://user-images.githubusercontent.com/31348972/63607914-e9098f80-c5d3-11e9-9c9d-e325baec1ee9.png)

**Comment by Science-and-Motion-Sports** [comment]
Oh, it was caused by the "MicrosoftDocsLanguageChanger" addon for Firefox. it works when I disable it. Seems like this addon has issues with URLs that contain **/previous-versions/** instead of the language **/en-us/**.
