### ISSUE TITLE
Curly braces in the example code appear to violate C# conventions

### ISSUE THREAD

**Issue by Micteu** [dotnet/docs#14017]
This is the example for using the `when` keyword with catching exceptions from the page linked at the bottom of this post:

    using System;
    using System.Net.Http;
    using System.Threading.Tasks;
    
    class Program
    {
       static void Main()
       {
          Console.WriteLine(MakeRequest().Result);
       }
    
       public static async Task<string> MakeRequest()
       { 
           var client = new System.Net.Http.HttpClient();
           var streamTask = client.GetStringAsync("https://localHost:10000");
           try {
               var responseText = await streamTask;
               return responseText;
           } 
           catch (HttpRequestException e) when (e.Message.Contains("301")) {
               return "Site Moved";
           }
           catch (HttpRequestException e) when (e.Message.Contains("404")) {
               return "Page Not Found";
           }
           catch (HttpRequestException e) {
               return e.Message;
           }
       }
    }

Shouldn't the curly braces be on the next lines? I thought in C# curly braces either were generally recommended to be on their own lines or have themselves, their contents, and the previous line all in one line.

Very petty issue, I know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef10b29-fbf8-5af9-8f8b-a694a1416e33
* Version Independent ID: 15502bbc-5355-2add-0fa8-ae31dc01c122
* Content: [when contextual keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when)
* Content Source: [docs/csharp/language-reference/keywords/when.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/when.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Indeed! Thanks for letting us know. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by Youssef1313** [comment]
I think also there is a redundant `System.Net.Http` in http client declaration, as this namespace is imported by `using` statement. I'll fix both problems and submit PR.
