### ISSUE TITLE
Asynchronous rollback.

### ISSUE THREAD

**Issue by suwyace** [dotnet/docs#14029]
Hi - Is there any time line on when a asynchronous rollback can be supported? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776eaf68-72b6-5016-da55-0f328868cb47
* Version Independent ID: 2bdbad74-ffd7-d251-7af6-80ba1d754cae
* Content: [Implementing an Explicit Transaction using CommittableTransaction](https://docs.microsoft.com/en-us/dotnet/framework/data/transactions/implementing-an-explicit-transaction-using-committabletransaction#feedback)
* Content Source: [docs/framework/data/transactions/implementing-an-explicit-transaction-using-committabletransaction.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/transactions/implementing-an-explicit-transaction-using-committabletransaction.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@dasetser, @HongGit can you comment on this question related to Transactions content?

Also, should we move this content to the .NET Guide since it seems that .NET Core supports this too?

**Comment by dasetser** [comment]
@suwyace We don't have any plans to add an API to support doing an async rollback.

@mairaw System.Transactions on .NET Core only supports a small subset of the functionality, so much of this documentation does not apply to it.
