### ISSUE TITLE
Sign an XML file example from microsoft documention doesn't work

### ISSUE THREAD

**Issue by ahmediddma** [dotnet/docs#14034]
the example work fine on dot netframework 4.0 but with 4.5 and later will crush

```
public static void SignXml(XmlDocument xmlDoc, RSA rsaKey)
    {
        // Check arguments.
        if (xmlDoc == null)
            throw new ArgumentException(nameof(xmlDoc));
        if (rsaKey == null)
            throw new ArgumentException(nameof(rsaKey));

        // Create a SignedXml object.
        SignedXml signedXml = new SignedXml(xmlDoc);

        // Add the key to the SignedXml document.
        signedXml.SigningKey = rsaKey;

        // Create a reference to be signed.
        Reference reference = new Reference();
        reference.Uri = "";

        // Add an enveloped transformation to the reference.
        XmlDsigEnvelopedSignatureTransform env = new XmlDsigEnvelopedSignatureTransform();
        reference.AddTransform(env);

        // Add the reference to the SignedXml object.
        signedXml.AddReference(reference);

        // Compute the signature.
        signedXml.ComputeSignature();

        // Get the XML representation of the signature and save
        // it to an XmlElement object.
        XmlElement xmlDigitalSignature = signedXml.GetXml();

        // Append the element to the XML document.
        xmlDoc.DocumentElement.AppendChild(xmlDoc.ImportNode(xmlDigitalSignature, true));
    }
```

at that line

` signedXml.ComputeSignature();`

with exception 

> System.Security.Cryptography.CryptographicException: 'Invalid algorithm specified.

putting it in a dot net framework 4.0 own project and calling it from 4.5+ project will not trigger this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e583e0de-c711-8215-164b-78320c927588
* Version Independent ID: 00cc0659-90ee-b709-06a8-5bf6247bee58
* Content: [How to: Sign XML Documents with Digital Signatures](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-sign-xml-documents-with-digital-signatures#feedback)
* Content Source: [docs/standard/security/how-to-sign-xml-documents-with-digital-signatures.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-sign-xml-documents-with-digital-signatures.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@blowdart please review.

**Comment by blowdart** [comment]
@bartonjs

**Comment by ahmediddma** [comment]
??

**Comment by bartonjs** [comment]
@ahmediddma I copied and pasted the code from above exactly, and ran it with this driver:

```C#
using (RSA rsa = RSA.Create())
{
    XmlDocument doc = new XmlDocument();
    doc.LoadXml(@"<Root><Child>Text</Child></Root>");
    SignXml(doc, rsa);
    Console.WriteLine(doc.OuterXml);
}
```

and it worked fine. (Built against .NET Framework 4.7.2, executed on .NET Framework 4.7.2 on Windows Server 2012 R2).

If your application (whichever assembly has the `Main` method) is built against .NET Framework 4.7.1 or later the default digest algorithm for references in SignedXml is SHA256, and the default for RSA signatures is RSASSA-PKCS1-SHA256.  If your OS version does not support SHA256 you can change these back to SHA-1 (which is no longer considered secure in this context) you can set `reference.DigestMethod = SignedXml.XmlDsigSHA1Url;` (before AddReference) and `signedXml.SignedInfo.SignatureMethod = SignedXml.XmlDsigRSASHA1Url;` (before ComputeSignature).

**Comment by tdykstra** [comment]
@ahmediddma Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
