### ISSUE TITLE
ImageType

### ISSUE THREAD

**Issue by SperoSophia** [dotnet/docs#14041]
Can this also work with ImageType as input instead of Path, so we can work with in-memory images?

[AB#1579020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579020)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Retrain TensorFlow image classifier - transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @SperoSophia ,

It should be doable. See this sample for reference.

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ObjectDetection-Onnx/OnnxObjectDetectionWeb

[Input data class (schema)](https://github.com/dotnet/machinelearning-samples/blob/8d396bae84b8cf659a63bb04a2a62b3bb29427b8/samples/csharp/end-to-end-apps/ObjectDetection-Onnx/OnnxObjectDetection/ML/DataModels/ImageInputData.cs#L12)

[Create input data](https://github.com/dotnet/machinelearning-samples/blob/8d396bae84b8cf659a63bb04a2a62b3bb29427b8/samples/csharp/end-to-end-apps/ObjectDetection-Onnx/OnnxObjectDetectionWeb/Controllers/ObjectDetectionController.cs#L51)

[Pipeline](https://github.com/dotnet/machinelearning-samples/blob/8d396bae84b8cf659a63bb04a2a62b3bb29427b8/samples/csharp/end-to-end-apps/ObjectDetection-Onnx/OnnxObjectDetection/ML/OnnxModelConfigurator.cs#L21)
