### ISSUE TITLE
As of what version of C# and .Net framework does this apply?

### ISSUE THREAD

**Issue by remids** [dotnet/docs#14048]
I've used some tuple deconstruction, but I'm getting syntax errors currently using this feature. It's probably because some aspect of the feature isn't available given the version of C#/.Net Framework I'm using, but given the info on this page, I've no way to figure that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct#feedback)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for updating this @remids 

Yes, you'll need the `System.ValueTuple` package when targeting older versions of the .NET Framework. We do have that information in the [main article on tuples](https://docs.microsoft.com/dotnet/csharp/tuples), which is linked from this one. 

I'd like to know how you landed on this page without seeing that information first. That way we can make sure it's easier to find.

**Comment by BillWagner** [comment]
closing due to lack of response.

**Comment by remids** [comment]
I apologize; I don't monitor Github issues, and seem to have missed the original email notification for your comment @BillWagner .  Although the issue is closed, which is fine, I got there from a Google search for "Deconstructing Tuples".  FYI.
