### ISSUE TITLE
Is csc -baseaddress useful with ASLR?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#14040]
> For more information about when and why to use this option, see [Larry Osterman's WebLog](https://blogs.msdn.microsoft.com/larryosterman/2004/07/06/why-should-i-even-bother-to-use-dlls-in-my-system/).

Is the `-baseaddress` option of the C# compiler at all useful nowadays, when Address Space Layout Randomization (ASLR) will relocate DLLs anyhow? The linked weblog does not mention ASLR; it was written in 2004, and ASLR was released with Windows Vista in 2007.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52af077e-f7ef-921f-e603-8935e96dfc6a
* Version Independent ID: a2a23f7e-18d8-944a-3caa-1fb876f1997e
* Content: [-baseaddress (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/baseaddress-compiler-option#feedback)
* Content Source: [docs/csharp/language-reference/compiler-options/baseaddress-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/baseaddress-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good question @KalleOlaviNiemitalo 

@jcouv @jaredpar Do you know the answer, or where to track this information down?

**Comment by akochepasov** [comment]
One of our drivers is very old and crashes when ASLR enabled

**Comment by KalleOlaviNiemitalo** [comment]
@akochepasov, was that driver built with the C# compiler?

**Comment by akochepasov** [comment]
@KalleOlaviNiemitalo, no, it is a native DLL. However, it's loaded into C# exe.
