### ISSUE TITLE
Dead link to Dr. Watson 

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#14057]
> For more information about error debugger, see [Description of the Dr. Watson for Windows (Drwtsn32.exe) Tool](https://support.microsoft.com/help/308538/description-of-the-dr--watson-for-windows-drwtsn32-exe-tool).

That link redirects to &lt;https://support.microsoft.com/en-us/help/308538&gt;, which says "Sorry, page not found".

Searching for Dr. Watson in Microsoft Support finds these other pages:

- ["How to troubleshoot program faults with Dr. Watson"](https://support.microsoft.com/en-us/help/275481/how-to-troubleshoot-program-faults-with-dr-watson) discusses "Microsoft Windows 98, Windows 98 Second Edition, and Windows Millennium Edition (Me)", so it is completely out of date.
- ["Description of the Dr. Watson (Drwatson.exe) Tool"](https://support.microsoft.com/en-us/help/185837/description-of-the-dr-watson-drwatson-exe-tool) is still in the search results, even though that link is dead as well.

Perhaps this should link to [Windows Error Reporting - Windows applications | Microsoft Docs](https://docs.microsoft.com/windows/win32/wer/windows-error-reporting) instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0161652-e4a7-4092-e4d4-76046fac995a
* Version Independent ID: 73bebf0d-82e9-33ca-9d5a-1dfd22c9828e
* Content: [-errorreport (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errorreport-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/errorreport-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/errorreport-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Not sure if that helps, but here is the content of that dead link.

![image](https://user-images.githubusercontent.com/31348972/63948051-5015c100-ca78-11e9-9cf8-29ccdea172ea.png)

**Comment by KalleOlaviNiemitalo** [comment]
Huh, now that I look at the Roslyn source, the `-errorreport` option seems to have no effect at all; it does not even parse the argument. https://github.com/dotnet/roslyn/blob/5010ecae8b4890e4a655959e2b2612c33eb2bd7c/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L1180-L1181

Indeed, if I create an empty `hah.cs` and run `csc -errorreport:bogus -target:library hah.cs` in Developer Command Prompt for VS 2017, then Microsoft (R) Visual C# Compiler version 2.10.0.0 (b9fb1610) does not warn about the unrecognized "bogus" argument.

**Comment by BillWagner** [comment]
Thanks for reporting this @KalleOlaviNiemitalo 

That link should be removed. It isn't really relevant to how this option works. I've added ti to our backlog, and added the "up for grabs" label if you want to submit a PR that removes the link.

**Comment by Youssef1313** [comment]
@BillWagner, opened #14190 to fix that and remove extra whitespaces.
