### ISSUE TITLE
available problem

### ISSUE THREAD

**Issue by singsong2016** [dotnet/docs#14061]
system.range and system.index is only available in .net core 3.0 now, not in .net framework 4.8, why is that? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges#feedback)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the feedback @singsong2016 

The team has discussed this in various forums and presentations, and the documents are correct.

I'll close this.
