### ISSUE TITLE
MouseEventArgs and KeyEventArgs are not base types of EventArgs

### ISSUE THREAD

**Issue by keni1** [dotnet/docs#14062]
This page says: "This example demonstrates how delegates can be used with methods that have parameters of a type that are base types of the delegate signature parameter type"

But neither MouseEventArgs or KeyEventArgs are base types of EventArgs, but the opposite is true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da104-ca1b-7cc2-15d6-f6486c818e60
* Version Independent ID: 98d90b16-a4d0-d532-9fea-c51f6e262288
* Content: [Using Variance in Delegates (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-delegates#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-delegates.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-delegates.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I think the page is correct: in the example, the method in question is:

```c#
private void MultiHandler(object sender, System.EventArgs e)  
```

And the delegate signatures are:

```c#
public delegate void KeyEventHandler(object sender, KeyEventArgs e);
public delegate void MouseEventHandler(object sender, MouseEventArgs e);
```

So it's saying that `EventArgs` is the base type of `KeyEventArgs` and `MouseEventArgs`, which is correct.

Maybe the use of plural and singular is confusing? The text talks about "methods" and "delegate signature", but the example has a single method and multiple delegate signatures.
