### ISSUE TITLE
archive.msdn and fwlink

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#14065]
```
- [Networking Samples for .NET on MSDN Code Gallery](https://code.msdn.microsoft.com/Wiki/View.aspx?ProjectName=nclsamples)
- [HttpClient Sample](https://go.microsoft.com/fwlink/?LinkId=242550)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2662c2f7-e074-225a-d878-9e3cb6b9ff90
* Version Independent ID: 9f333c5a-3e53-5abf-8c09-d5f1f5b7c59b
* Content: [Network Programming in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/)
* Content Source: [docs/framework/network-programming/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @imba-tjd. We already have a PR open that will take care of this.
