### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by jason-hess** [dotnet/docs#14060]
I think the text "By default, an attribute applies to the element that it precedes." should be "By default, an attribute applies to the element that follows it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c570f1-2f76-be1b-410a-ed4bd67e33cc
* Version Independent ID: dd329ad3-ca29-61e5-8753-d57792a88516
* Content: [Attributes (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/index#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/attributes/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/attributes/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @jason-hess 

I think both wordings are correct, but your suggestion is more clear.

I've added this to our backlog to address when we next update this article. 

In the meantime, if you want to submit a PR with your suggestion, I'll watch for it.
