### ISSUE TITLE
Slightly dirty explanation of null.Equals(null)

### ISSUE THREAD

**Issue by briangithex** [dotnet/docs#14074]
The top of the guide has the following statement:
5.  x.Equals(null) returns false. However, null.Equals(null) throws an exception; it does not obey rule number two above.

This suffers from a few problems:

- `null.Equals(null)` is an example of a violation of rule 1.  An example of a violation of rule 2 is `null.Equals(x)`.
- `null.Equals(null)` won't even compile, unless the left side accessed via variable or is cast before usage.  As such, a beginner user attempting to try this example themselves may have a different experience than the guide predicts, but won't necessarily understand why.
- Personally, I feel like the rules would be better described as the "four guarantees of equivalence." Rule five is more of an exception to these rules than part of them.

As an alternative, we could add bullet points immediately below the guarantees:

- If `x` is `null`, `x.Equals(x)` throws an exception.  Rule number one does not apply.
- If `x` is `null`, `x.Equals(y)` throws an exception, even if y is `null`.  Rule number two does not apply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95b738e-a319-8947-c098-692068c24b9c
* Version Independent ID: 227a6999-9add-4a0a-98cb-c0c6624d6089
* Content: [How to: define value equality for a type - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type#feedback)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @briangithex Yes, that fifth point introduces a number of issues. I'll propose a different solution:

1. Add a statement before any guarantees: That says: "For the following rules, assume that `x`, `y` and `z` are not null.
1. Describe null separately as follows: "Any non-null value is not equal to null. However, the CLR checks for null on all method calls and throws a `NullReferenceException` if the `this` reference would be `null`. Therefore, `x.Equals(y)` throws an exception when `x` is null. That breaks rules 1 or 2, depending on the argument to `Equals`."

Thoughts?

**Comment by briangithex** [comment]
> Thanks for writing this @briangithex Yes, that fifth point introduces a number of issues. I'll propose a different solution:
> 
> 1. Add a statement before any guarantees: That says: "For the following rules, assume that `x`, `y` and `z` are not null.
> 2. Describe null separately as follows: "Any non-null value is not equal to null. However, the CLR checks for null on all method calls and throws a `NullReferenceException` if the `this` reference would be `null`. Therefore, `x.Equals(y)` throws an exception when `x` is null. That breaks rules 1 or 2, depending on the argument to `Equals`."
> 
> Thoughts?

Phrases like "the `this` reference" and "the CLR" strike me as more technical than the rest of that page.
