### ISSUE TITLE
The links to ECMA specs should be on the .NET docs pages

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#14077]
The links to the pertinent ECMA specs for the C# language and CLI are currently found on the [Visual Studio product site](https://visualstudio.microsoft.com/license-terms/ecma-c-common-language-infrastructure-standards/). This is not the best location. These links should be somewhere on the .NET docs site.

There are a couple open questions:

- [ ] Where should the CLI spec be linked from? Is the [.NET Standard](https://docs.microsoft.com/dotnet/standard/net-standard) location the best home? Should there be a page here that links to the standards?
- [ ] If not located at the .NET Standard page, where is better? .NET Core?
- [ ] The [C# Language Reference](https://docs.microsoft.com/dotnet/csharp/language-reference/) index page already has the link to the C# ECMA spec. Is that sufficient, or should there be additional links on the same page with the CLI specs?

Add comments for a proposal, and once we have consensus, we'll update the links.

**Comment by terrajobst** [comment]
I think after our big repo merge the obvious home would be dotnet/platform repo. However, we should also link to it from dotnet/docs.

**Comment by BillWagner** [comment]
@terrajobst 

> However, we should also link to it from dotnet/docs.

Yes, but from what page?

**Comment by terrajobst** [comment]
I'd probably mention it here: https://docs.microsoft.com/en-us/dotnet/standard/components

**Comment by CarolEidt** [comment]
What @terrajobst suggests makes sense to me, and in any event I defer to his judgment on this.

**Comment by MadsTorgersen** [comment]
I too am happy with @terrajobst's suggestion.

**Comment by terrajobst** [comment]
> and in any event I defer to his judgment on this

Awwww. "...in *any* event...". I think I'll add this to my business card ❤
