### ISSUE TITLE
Expand explanation on how to use the interactive code editor

### ISSUE THREAD

**Issue by thurstylark** [dotnet/docs#14078]
There lacks a clear set of instructions on how to open and use the code editor. A user might find their way into the editor if they have interacted with similar features before, but [as stated on the Intro to C# index page:](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/index.md#L15)

>  These first lessons assume no prior knowledge of programming or the C# language.

The first mention of using the code editor is here: https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/hello-world.yml#L21

> Run the following code in the interactive window. To do that, type the following code block in the interactive window and click the **Run** button:

The interactive window is not visible at this point, and won't be until one presses a button labeled "Enter Focus Mode", which is not mentioned anywhere in this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=1)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @thurstylark 

I've added this to our October milestone to address.

**Comment by BillWagner** [comment]
This can be addressed in the same update as #13345

**Comment by DWAK-ATTK** [comment]
So the letter of the request was met... but the intent was to make things simpler for the new user.  
Would something like this screenshot not be easier?  (matters of kerning and typography aside)

![image](https://user-images.githubusercontent.com/4431178/69169956-19b37500-0aae-11ea-826d-a4550d9def37.png)

I just copied the code for the sidebar button and pasted it into the paragraph.  It works just like the first button - no js changes needed (good job on that, js dev!).

What about adding some minor narrative as well.. like:  Any time you see this button [green button here], clicking it will open the interactive window.

The current wording gives instruction/orders.  The proposed change teaches about the tools.
