### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#14085]
I don't see many of these [coding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) from corefx repo anywhere in the docs. Shouldn't they be added somewhere ?
Whether in the [Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions) article or another separate article ?

/cc @rpetrusha , @BillWagner , @mairaw

**Comment by BillWagner** [comment]
I think this should be discussed before making these changes.  It may be wise to link to the CoreFx repo's coding style, but I don't think we should replicate them in the docs.

Thoughts?

**Comment by Youssef1313** [comment]
Linking to the corefx coding style seems good I think.
