### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by hanisani** [dotnet/docs#14083]
The information provided on this page is sufficient enough to understand on how to override ToString() method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd498a64-2c80-fe2f-4c27-19d8cf74730c
* Version Independent ID: b7461ce2-b286-3f6b-c87c-3d662a57fd53
* Content: [How to: Override the ToString Method - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @hanisani 

I'm glad this worked for you.  Closing as kudos.
