### ISSUE TITLE
Confusing article text

### ISSUE THREAD

**Issue by andyste1** [dotnet/docs#14082]
Near the start of the section "Examine Survey Responses", the article states "Because surveyResponses is a non-nullable reference type, no checks are necessary before de-referencing it", however surveyResponses *has* been declared as nullable in an earlier code snippet. This also means that the second line in the code snippet ("public string Answer(int index) =&gt; surveyResponses.GetValueOrDefault(index, "No answer")!;") should be checking for surveyResponse being null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types#feedback)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @andyste1 

You're correct, this portion of the article does need to change. I've added it to this month's sprint.

**Comment by MaxTranced** [comment]
Um.... N00bish, I cannot figure out how to submit a PR with https://github.com/MaxTranced/docs/commit/6319bcbae6e35e2252edf03457d83146f43309b6

**Comment by BillWagner** [comment]
@MaxTranced Thanks for doing the work for the fix.

From [this page](https://github.com/MaxTranced/dotnet-docs/tree/patch-1) You should see a button that says "new pull request". From there, you can edit the pull request title and description, then click "Submit". 

Thanks for working to help us improve our docs!
