### ISSUE TITLE
Line doesn't compile when calling DetectIidSpike

### ISSUE THREAD

**Issue by jamesjl** [dotnet/docs#14089]
All,

The line 

var iidSpikeEstimator = mlContext.Transforms.DetectIidSpike(outputColumnName: nameof(ProductSalesPrediction.Prediction), inputColumnName: nameof(ProductSalesData.numSales), confidence: 95, pvalueHistoryLength: docSize / 4);

in method DetectSpike doesn't compile.  There is no method DetectIidSpike in the Transforms property of mlContext.  I copied directly from this page into VS.

I made sure I have the Microsoft.ML dependancies and also looking on GitHub and NuGet but I can't seem to locate the library for this method call.  Any ideas?

Thanks.

[AB#1579020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579020)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0953823a-7d2a-a323-5365-d9a349385552
* Version Independent ID: 54ec317c-cfb9-0c2c-ccc2-4b90a5746e99
* Content: [Tutorial: Detect anomalies in product sales - ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/sales-anomaly-detection#feedback)
* Content Source: [docs/machine-learning/tutorials/sales-anomaly-detection.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sales-anomaly-detection.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by jamesjl** [comment]
Apologies.  I'd skipped over installing the NuGet package:

Microsoft.ML.TimeSeries

All seems ok now.

**Comment by luisquintanilla** [comment]
Great to hear it's working for you now @jamesjl.
