### ISSUE TITLE
C# 8.0 - unmanaged constructed types

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#14101]
dotnet/csharplang#1937

@BillWagner this is for the [C# 8 docs project](https://github.com/dotnet/docs/projects/58).
Could you please assign this issue to me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e5d75f-07a3-e7ee-2842-ac754bdd2e41
* Version Independent ID: 4a3622fb-7d09-78ec-ba38-b88001475018
* Content: [Unmanaged types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types)
* Content Source: [docs/csharp/language-reference/builtin-types/unmanaged-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/unmanaged-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Done. Thanks for helping to get these done.
