### ISSUE TITLE
No such sdk

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#14109]
Hi team, 
I'm moving this from here: https://github.com/dotnet/docs.zh-cn/issues/458
The user reports there's inconsistent instructions regarding this issue (as I understood)
*The following comments were Machine Translated.*

@xyfy commented 8 hours ago — with docs.microsoft.com

I installed vs, did not show very many runtimes and sdk in the control panel

----------------------------

@xyfy commented 7 hours ago
I mean, I have these SDKs, but there are no programs installed and uninstalled.

----------------------------
@xyfy commented 1 hour ago
The document says it can be unloaded by the program, and none of the actual installations appear in the program list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Remove the .NET Core runtime and SDK - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows#feedback)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@xyfy we'll need a little bit more information from you in order to try to help you.

Can you type dotnet --list-sdks on your console and tell us what you get?

Can you paste here what you get when you filter the SDKs you have installed in the Add/Remove programs? For example:
![image](https://user-images.githubusercontent.com/12971179/64057176-a2291600-cb4e-11e9-985c-55ce1ff53f2b.png)

**Comment by xyfy** [comment]
OK，l will try&nbsp;to capture the screenshot&nbsp; for&nbsp; you next Monday



---Original---

**Comment by mairaw** [comment]
No rush! Have a great weekend!

**Comment by xyfy** [comment]
I saw it,


the sdk is has error info with 3.0 only .


but if I want to uninstall the runtimes ,how can I do it ?




------------------ 原始邮件 ------------------
发件人: "Maira Wenzel"<notifications@github.com>; 
发送时间: 2019年8月31日(星期六) 上午10:48
收件人: "dotnet/docs"<docs@noreply.github.com>; 
抄送: "哈哈"<benguahao@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [dotnet/docs] No such sdk (#14109)




No rush! Have a great weekend!
 
&mdash;

**Comment by xyfy** [comment]
![image](https://user-images.githubusercontent.com/7838147/64093025-5f06b700-cd89-11e9-9210-f3ea227de48e.png)

**Comment by mairaw** [comment]
Thanks @xyfy. 
 
@KathleenDollard I think this is the issue with the SDK install that we discussed no?

**Comment by KathleenDollard** [comment]
This is a known issue that we are working on.

**Comment by mairaw** [comment]
Closing since this is a known product bug.
