### ISSUE TITLE
No Step Option for Ranges?

### ISSUE THREAD

**Issue by jonlave** [dotnet/docs#14129]
Maybe I'm missing something, but there's no mention of specifying a step or interval for a range. In F#, you could do 1..2..10 which produces {1, 3, 5, 7, 9}. How to accomplish that with the new Range?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> How to accomplish that with the new Range?

You can't, no such syntax will be supported by C# 8.0. Though there is a proposal to add it to a future version of C#: https://github.com/dotnet/csharplang/issues/2562.

**Comment by jonlave** [comment]
That would explain it. I figured that most other languages that have Ranges/Sequences also have a step option, so it's odd that they couldn't get it in together with Ranges.

**Comment by BillWagner** [comment]
Thanks for pointing to the proposal @svick 

The current documentation is correct, so I will close this. (We'll update it if the proposal is accepted and implemented. 😄
