### ISSUE TITLE
Invoking default interface method implementation from a selected interface

### ISSUE THREAD

**Issue by damirarh** [dotnet/docs#14127]
Let's say I have the following rather contrived scenario:

```
interface I0
{
    string Method()
    {
        return "I0";
    }
}

interface I1 : I0
{
    string I0.Method()
    {
        return "I1";
    }
}

interface I2 : I0
{
    string I0.Method()
    {
        return "I2";
    }
}
```

Now I want a class to implement both I1 and I2:

```
class C12 : I1, I2
{
}
```

As expected, I get the following compiler error:

&gt; Interface member 'I0.Method()' does not have a most specific implementation. Neither 'I1.I0.Method()', nor 'I2.I0.Method()' are most specific.

I can resolve this if I provide my own implementation. Inside it, how could I invoke the implementation from one of the interfaces, e.g. I1? I'm pretty sure the following syntax used to work in a previous preview:

```
class C12 : I1, I2
{
    string I0.Method()
    {
        return base(I1).Method();
    }
}
```

However, now the compiler complains:

&gt; Use of keyword 'base' is not valid in this context

What is the correct syntax to invoke the default method implementation in interface I1? I can't find it documented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c790425e-da4e-9a75-6a11-f72109ce8d6a
* Version Independent ID: 09298e41-8f5a-c3c3-a849-8de67f8efba1
* Content: [Safely update interfaces using default interface members in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-members-versions)
* Content Source: [docs/csharp/tutorials/default-interface-members-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-members-versions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @damirarh 

I'll make sure to get it updated this month.

I did a quick search, and I can't find the LDM notes where this was updated.  @agocke @jcouv Can you point me to the correct updates?

**Comment by jcouv** [comment]
Yes, the error for ambiguous implementation is expected ([notes](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-03-08.md#the-diamond-problem)).

For the `base(I1)` question, the functionality was removed from C# 8. Here's the [PR](https://github.com/dotnet/roslyn/pull/35456). This was decided in the [04-29 meeting](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-29.md#default-interface-implementations-and-base-calls). 
We have a [follow-up championed issue](https://github.com/dotnet/csharplang/issues/2337) (currently considered for C# 9).

**Comment by BillWagner** [comment]
Thanks @jcouv 

I'll review the doc carefully and make sure it reflects the current planning.

**Comment by BillWagner** [comment]
I did review the tagged article, and it's correct with respect to the C# 8.0 implementation.

Continued discussion should be related to the dotnet/csharplang#2337

Closing this as by-design.
