### ISSUE TITLE
Code sample is wrong

### ISSUE THREAD

**Issue by shunluo** [dotnet/docs#14123]
[Enter feedback here]
First line of code below should be 
**[DeveloperAttribute("Joan Smith", "1")]**

> You can apply this attribute using the full name, DeveloperAttribute, or using the abbreviated name, Developer, in one of the following ways.
> C#
> 
> Copy
> [Developer("Joan Smith", "1")]
> 
> -or-
> 
> [Developer("Joan Smith", "1", Reviewed = true)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7645edc8-46ad-431f-4f91-e77ba3941f17
* Version Independent ID: ff721860-b8e8-3c3d-aefa-f1ec3e00fa69
* Content: [Writing Custom Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/writing-custom-attributes)
* Content Source: [docs/standard/attributes/writing-custom-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/writing-custom-attributes.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you for your feedback @shunluo. But as the article states:

"You can apply this attribute using the full name, DeveloperAttribute, or using the abbreviated name, Developer,"

You can see more information about this and more examples that use the abbreviated name at https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/#using-attributes.

**Comment by shunluo** [comment]
My point is that according to description:

"in one of the following ways."
But actually both ways listed are the same. The sample is to demostrate the usage of full name or abbreviated name, however the sample all use abbreviated name.

[**Developer**("Joan Smith", "1")]
-or-
[**Developer**("Joan Smith", "1", Reviewed = true)]

**Comment by Youssef1313** [comment]
@shunluo , The two examples are meant to show the usage with only required parameters, and another time with both required and optional parameters.
And this statement:
> You can apply this attribute using the full name, DeveloperAttribute, or using the abbreviated name, Developer, in one of the following ways.
demonstrates that the usage of attribute with required params only or with both optional and required params can be done with either the full name or the abbreviated one.
