### ISSUE TITLE
csproj XML snippet needs to be updated

### ISSUE THREAD

**Issue by coffeecoder3peat** [dotnet/docs#14137]
XML shows 
```xml
&lt;TargetFramework&gt;netstandard1.4&lt;/TargetFramework&gt;
```
Should show 

```xml
&lt;TargetFramework&gt;netstandard2.0&lt;/TargetFramework&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Get started with .NET Core on macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos#feedback)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
You're right @coffeecoder3peat. Latest SDKs produce a 2.0 output. Opened PR #14137 to fix this.
