### ISSUE TITLE
Sample link is invalid

### ISSUE THREAD

**Issue by meziantou** [dotnet/docs#14136]
The link for "NumericUpDown Custom Control with Theme and UI Automation Support Sample" (https://go.microsoft.com/fwlink/?LinkID=160025) is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f082db11-a47c-222d-e0d4-112b9033249b
* Version Independent ID: 401d14cf-63e7-7fd1-618a-a7aca0f205cb
* Content: [UI Automation of a WPF Custom Control](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/ui-automation-of-a-wpf-custom-control#feedback)
* Content Source: [docs/framework/wpf/controls/ui-automation-of-a-wpf-custom-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/ui-automation-of-a-wpf-custom-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
I'm not familiar with that topic, so not sure if [This sample](https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_Wpf/CustomControlNumericUpDown/CSharp) is the one meant by that link.

**Comment by rpetrusha** [comment]
It's a version of it, @Youssef1313. Thanks for finding it!

**Comment by Youssef1313** [comment]
@rpetrusha, Thanks for confirming. I've opened https://github.com/dotnet/docs/pull/14188 to fix it.

**Comment by mairaw** [comment]
Thanks @Youssef1313. I've also updated the internal fwlink to point to the same location.

**Comment by mairaw** [comment]
Closing this one as fixed as seen on the following commit:
https://github.com/dotnet/docs/commit/240050fd40de6381f109d82788d6bf3dea5aeeeb#diff-8ad728aa3a36c439a0448df0c0182ad5
