### ISSUE TITLE
Fix the formatting, make examples simpler to follow

### ISSUE THREAD

**Issue by dinobu** [dotnet/docs#14135]
Examples are so over polluted by unnecessary detail, the formatting makes it even more difficult to see entire text.  So much needless scrolling for nothing.  Very poor explanation of problem by polluting example by irrelevant details, horrible formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be073b14-6d0b-60be-7dff-4674bcb6c674
* Version Independent ID: a5fa3e78-73de-3360-1253-00545a2b4ef2
* Content: [Chaining Tasks by Using Continuation Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks#feedback)
* Content Source: [docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@dinobu Thanks for the comment -- in general I agree with you that examples should be as simple as possible. However, I don't know which examples in this doc you're referring to or what parts of them you see as irrelevant details. I'm closing this issue now but you're welcome to reopen and provide more details to let us know which parts of the example code in this doc need work.
