### ISSUE TITLE
.net core 2.1 doesn't support XslCompiledTransform.Load(typeof(Transform))

### ISSUE THREAD

**Issue by intelisofts** [dotnet/docs#14148]
[throws below exception
Could not load file or assembly 'System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f147e9-9514-5507-ab52-d8fdb8bff053
* Version Independent ID: 753bfb60-0d0b-35dc-4a16-689aaefe5934
* Content: [How to: Perform an XSLT Transformation by Using an Assembly](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/how-to-perform-an-xslt-transformation-by-using-an-assembly#feedback)
* Content Source: [docs/standard/data/xml/how-to-perform-an-xslt-transformation-by-using-an-assembly.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/how-to-perform-an-xslt-transformation-by-using-an-assembly.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by intelisofts** [comment]
after adding missing assembly getting below
{"Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type."}

**Comment by intelisofts** [comment]
Any lunch

**Comment by gn11** [comment]
I am using .NET core console application and referenced the Transform.dll (example above) using Project -> Add Reference ->Path to Transform.dll  But i am getting 'Could not load file or assembly 'System.Data.SqlXml'. Is there something wrong am doing?

**Comment by Thraka** [comment]
@gn11 Did you add reference to `System.Data.SqlXml` in your project?
