### ISSUE TITLE
CS0837 applies to method groups as well?

### ISSUE THREAD

**Issue by codeganesh** [dotnet/docs#14146]
In Visual Studio 2019, when I used a method group on the left hand side of "is",I got a compiler error "The first operand of an 'is' or 'as' operator may not be a lambda expression, anonymous method, or **method group**". Is this new in this current version of C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946a6568-a1aa-4844-7959-263c79935bb3
* Version Independent ID: 5d65bbcc-bedc-b39b-feba-a184ce97926d
* Content: [Compiler Error CS0837](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0837#feedback)
* Content Source: [docs/csharp/misc/cs0837.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0837.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
This is certainly not new. In fact, in the addition of "method group" in this message was already there in the [first roslyn sources instance](https://github.com/dotnet/roslyn/blob/e315208fe33d43964fb649935e3bbff2275fa101/src/Compilers/CSharp/Portable/CSharpResources.resx#L2121) on Github (Jan 2015). VS 2017 outputs the same as well. But VS2012 with c# 5.0 compiles `if (Main is Delegate )`, just outputs warning that Main would never be of that type. (By the way, why? Method group should have implicit cast to delegate. And what is the actual type of method group?) So it was introduced somewhere in c# 5.x - 6.0. This article and example should be updated.

**Comment by codeganesh** [comment]
Thank you for the clarification!
