### ISSUE TITLE
Code example for topic 'Classes and Structs' is wrong

### ISSUE THREAD

**Issue by Treit** [dotnet/docs#1415]
On the following page there is a section called 'Example' that is wrong:
https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/index.md

The text of the topic says the following:

>Example
>In the following example, MyCustomClass is defined with three members at the top level of the ProgrammingGuide namespace. An instance (object) of MyCustomClass is created in the Main method in the Program class, and the object’s methods and properties are accessed by using dot notation. 
>[!code-cscsProgGuideObjects#88] 

The code sample that is linked to, however, is the following:
https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/codesnippet/CSharp/index_1.cs

This code snippet shows the IEquatable<T> interface and appears to have nothing to do with the topic.

I would try to fix this and submit a pull request but I'm not sure how to fix the code sample link.

**Comment by rpetrusha** [comment]
@Treit I'll take care of fixing it. Thanks for noticing it.
