### ISSUE TITLE
runtimeVersion needs to include magic string for .NET >= 4.0

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [dotnet/docs#14152]
I took me one hour to find out the reason why CoGetClassObject returned 0x8013101B (COR_E_NEWER_RUNTIME). The reason is that when you omit the runtimeVersion attribute of the &lt;clrClass&gt; element then COM starts the .NET 2.0 runtime in the C++ COM client process, even if the C# COM-Server-DLL was compiled for .NET v4.7. This documentation page does not tell you the magic strings required to specify that your DLL uses .NET 4.X. The magic string is apparently the following: runtimeVersion="v4.0.30319"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb156db0-a958-9978-c5a9-26c684fb9172
* Version Independent ID: 94881058-5e6c-cfce-b78f-38706b3c809b
* Content: [How to: Configure .NET Framework-Based COM Components for Registration-Free Activation](https://docs.microsoft.com/en-us/dotnet/framework/interop/configure-net-framework-based-com-components-for-reg)
* Content Source: [docs/framework/interop/configure-net-framework-based-com-components-for-reg.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/configure-net-framework-based-com-components-for-reg.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
