### ISSUE TITLE
nologo inconsistency

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#14163]
The synopsis says the switch is `--nologo`.

The arguments say it's only available since .NET Core 3.0, but `-nologo` (note single dash) works using .NET Core 2.2.6.

The arguments say it's `--no-logo` (note extra dash), but that doesn't work in any version (tested on 2.2.6 and 3.0.0 preview 8).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by imba-tjd** [comment]
`--no-logo` should be a typo.

`--nologo` is indeed added in 3.0: https://github.com/dotnet/cli/commit/afcf7604ffb32e6c50bb0d91463f6f2550d772e2#diff-b61ae302364b0e662a9b728d70221acc

The reason `-nologo` works is because msbuild uses it.

**Comment by IanKemp** [comment]
IMO, `--no-logo` makes sense in the context of `--no-build` and `--no-restore`.

**Comment by imba-tjd** [comment]
You need go to the cli repo opening a issue for that

**Comment by IanKemp** [comment]
@imba-tjd https://github.com/dotnet/cli/issues/12557
