### ISSUE TITLE
Typo in "Static Regular Expressions" section

### ISSUE THREAD

**Issue by stribizhev** [dotnet/docs#14164]
I think that "instance method calls" should read as "static method calls" in "Static regular expression methods are recommended as an alternative to repeatedly instantiating a regular expression object with the same regular expression. Unlike regular expression patterns used by regular expression objects, either the operation codes or the compiled Microsoft intermediate language (MSIL) from patterns used in **instance method calls** is cached internally by the regular expression engine."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14698b87-a995-290f-bdd7-9c2d6867704c
* Version Independent ID: f199cd3f-8dce-ad4e-9712-3545e35557e7
* Content: [Best Practices for Regular Expressions in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices#feedback)
* Content Source: [docs/standard/base-types/best-practices.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/best-practices.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for pointing this out, @stribizhev. The sentence should indeed read "static method calls" instead of "instance method calls". We've opened #14185 to correct the documentation.
