### ISSUE TITLE
DecryptFile incorrect Read lengths

### ISSUE THREAD

**Issue by DonaldRich** [dotnet/docs#14172]
The DecryptFile method reads only three bytes when reading the key and IV lengths but EncryptFile writes 4 bytes. This does not break because the fourth byte is zero with the values used, but it forces the use of Seeks where none are needed.

EncryptFile:

            outFs.Write(LenK, 0, 4);
            outFs.Write(LenIV, 0, 4);

DecryptFile:

        inFs.Seek(0, SeekOrigin.Begin);
        inFs.Seek(0, SeekOrigin.Begin);
        inFs.Read(LenK, 0, 3); 
        inFs.Seek(4, SeekOrigin.Begin);
        inFs.Read(LenIV, 0, 3);

If the correct size is used (4) in the calls to Read no Seek calls are needed. The duplicate seeks to the start of the file are not needed since the file is positioned at the first byte when opened.

There are also a number of file Close calls which are not needed as the files will be closed when the Using blocks are exited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Creating a Cryptographic Application](https://docs.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application#feedback)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. It does seem odd...

I'll add it to the backlog.

Thanks again!

**Comment by Herohtar** [comment]
There are a lot of issues in general with that example code... reading the wrong number of bytes, a bunch of unnecessary `Seeks`, variables declared that are never used (eg, `lenC` and `offset`), calling `Close` on the objects that were created with `using`...

The EncryptFile method has a few similar issues as well.
