### ISSUE TITLE
Minor - incorrect Figure number

### ISSUE THREAD

**Issue by MV10** [dotnet/docs#14203]
Second paragraph under "Stateless vs stateful microservices" references Figure 4-30 but the image is labeled 4-15.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1af44678-d848-00e7-6aed-ff3319f60395
* Version Independent ID: 1a4f5af6-0ce0-7946-6482-a3d15927a8b2
* Content: [Orchestrating microservices and multi-container applications for high scalability and availability](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/orchestrate-high-scalability-availability)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/orchestrate-high-scalability-availability.md](https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/orchestrate-high-scalability-availability.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @MV10. I've opened #14205 to fix this.

You can also edit our content when you find issues like that:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
