### ISSUE TITLE
Add migration doc from .NET Core 2.2 to 3.1

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#14218]
Similar to what we had from 2.0 -> 2.1
https://docs.microsoft.com/en-us/dotnet/core/migration/20-21

**Comment by mairaw** [comment]
Some comments around this on the skeleton PR I had previously created:
https://github.com/dotnet/docs/pull/14471#issuecomment-535197010
https://github.com/dotnet/docs/pull/14471#issuecomment-535214206

**Comment by BillWagner** [comment]
@Thraka Is this someone you should take on for the next sprint?

**Comment by Thraka** [comment]
Sure
