### ISSUE TITLE
Whats the default value for transferMode?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#14224]
All the other attributes have their default value stated, but transferMode does not. I assume it is Buffered but I don't know for sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 783b3c43-7fe5-5023-69e9-20b3f69ef548
* Version Independent ID: af2b80ce-e052-deaa-43a8-fcb0e5b062b7
* Content: [&lt;netTcpBinding&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/nettcpbinding#syntax)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/nettcpbinding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks @martingbrown. @HongGit can you confirm what's the default value? Information throughout API docs such as [here](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.transfermode?view=netframework-4.8#remarks) make it sound like Buffered is the default.
