### ISSUE TITLE
Does this also have an enables attribute?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#14225]
According to Visual Studio's intelisense this element also has an enabled attribute which this page does not mention. I'd like to know if that attribute is required and what the default value is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12300eca-40bd-35ad-8ba6-582084c62f22
* Version Independent ID: 4a4f2890-be60-8780-1fb9-8b28907925a2
* Content: [&lt;reliableSession&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/reliablesession)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/reliablesession.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/reliablesession.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Can you confirm @HongGit? I don't see that property under https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.reliablesessionelement.
