### ISSUE TITLE
C# 6 tutorial: missing require in `nameof` step

### ISSUE THREAD

**Issue by DavidS** [dotnet/docs#14226]
https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=8 requires an additional `require System.Collections.Generic` to work:

```
file.cs(10,9): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
file.cs(10,34): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3686c2-4c73-5686-0da9-abc38c74aeec
* Version Independent ID: ca995f80-9375-e9ca-b855-6e6893581e23
* Content: [Explore C# 6 - Try the new features in C# 6 interactively, using your browser](https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=10)
* Content Source: [docs/csharp/tutorials/exploration/csharp-6.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/exploration/csharp-6.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by nemrism** [comment]
@BillWagner, I just noticed that another step is missing a `using`:

In the step 5, [A better string format](https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=5), in order to use the following code:
`var wordLength = from word in phrase.Split(" ") select word.Length;`

We should add the following using: `using System.Linq`

How do you want to add this?

**Comment by BillWagner** [comment]
@nemrism I can do that. Or do you want to make a new PR?

**Comment by nemrism** [comment]
I'll let you add i directly @BillWagner 

You'll also need to change the line of code to:
`var wordLength = from word in phrase.Split(' ') select word.Length;`

It doesn't compile with a string parameter in the C#interactive experience!
