### ISSUE TITLE
Link to legacy page

### ISSUE THREAD

**Issue by Leon99** [dotnet/docs#14227]
Link to &lt;ProjectReference&gt; (https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items) points to a page that describes the old project file format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ab77c3-eba6-e947-8ffa-0fcda722f34b
* Version Independent ID: 48bbcb58-cfd1-b3d3-7a2a-319716541362
* Content: [dotnet-add reference command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference)
* Content Source: [docs/core/tools/dotnet-add-reference.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-reference.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you @Leon99 for your feedback. We need to create the reference for the new style first. So this is blocked until issue #2642 is taken care of.

**Comment by Leon99** [comment]
Thanks @mairaw, good to know this is aknowledged. I wonder if it would be better to remove that link in the meantime, to avoid confusion?

**Comment by mairaw** [comment]
Sure. PR #14241 created.

**Comment by marcpopMSFT** [comment]
@tdykstra is it worth just closing this one out as the original issue is resolved and 2642 is still active?

**Comment by tdykstra** [comment]
Agreed.
