### ISSUE TITLE
Soap versions supported

### ISSUE THREAD

**Issue by markpevans** [dotnet/docs#14223]
In the syntax section it has:-
envelopeVersion="None/Soap11/Soap12"
Whereas in the Attributes section it has:-
envelopeVersion	Specifies the version of SOAP that is used for messages that are processed by this binding. The only valid value is Soap11.
Clearly these both cannot be true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f13fe3-fc19-5741-40fc-a650ca68fb1a
* Version Independent ID: c17fd530-ad39-c8ae-78ac-6126307563db
* Content: [&lt;basicHttpBinding&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/basichttpbinding#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
