### ISSUE TITLE
Please explain when this warning gets issued more clearly

### ISSUE THREAD

**Issue by binki** [dotnet/docs#14231]
From reading this documentation, I would expect the following code to trigger this warning, but it doesn’t:

```csharp
public class C {
    public void M(IThing thing) {
        var needUpdateVariable = thing.DoSomething();
    }
    public interface IThing {
        object DoSomething();
    }
}
```

Please add documentation explain what is different about that code and why it doesn’t throw this warning.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34fc8443-8e5e-2e87-6ee5-fbab61709e1e
* Version Independent ID: 41a54122-d4f3-c233-7e67-6ee521af4338
* Content: [Compiler Warning (level 3) CS0219](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0219)
* Content Source: [docs/csharp/misc/cs0219.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0219.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
A simpler example than yours is:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var x = 5; // Gives warning
            var y = Test(); // Doesn't give warning
        }

        private static int Test()
        {
            return 5;
        }
    }
```

It seems like the compiler doesn't give this warning when the value is a function call.
I don't know if there is a specific reason for the compiler not to give the warning in that case or it's a bug in roslyn.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/issues/17154

**Comment by Youssef1313** [comment]
This one is also related to that issue: https://github.com/dotnet/roslyn/issues/15695

I think that docs should be updated.
