### ISSUE TITLE
Expand side-by-side explanation in Choosing between .NET Core - Framework

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#14237]
We could use an expanded side-by-side explanation in the topic:
Choosing between .NET Core and .NET Framework for server apps
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server#a-need-for-side-by-side-of-net-versions-per-application-level

We point to the side-by-side section of this topic from a number of other topics.  There has been some confusion over what side-by-side versioning means going forward with 3.0.  

An explanation that seems to resonate has been provided by David Fowler here: https://github.com/aspnet/AspNetCore/issues/2832.  So consider using that as a guideline.

Moved this out from original p1 issue https://github.com/aspnet/AspNetCore.Docs/issues/10559 when we relized we should just link to an updated verion of the  .NET Core and .NET Framework for server apps topic instead.

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server#a-need-for-side-by-side-of-net-versions-per-application-level)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Are you planning to address this @wadepickett? I was looking at this because it was still showing as Not Triaged. Otherwise, I can start on this right away. I'd probably also use a language that is similar to the one used in the marketing site:
https://dotnet.microsoft.com/learn/aspnet/what-is-aspnet-core

Multiple versions of ASP.NET Core can exist side-by-side on the same server. Meaning one app can adopt the latest version, while other apps keep running on the version they were tested on.

**Comment by wadepickett** [comment]
@mairaw, sorry I missed this, as the original issue branched to a few others I forgot about this one on the dotnet repo.  If you can take it, great. If not it will have to wait a few days for me to get to it.  I'm in the middle of working on two others.  Moved it to October.

**Comment by mairaw** [comment]
I'll let you handle this one unless we need help.

**Comment by wadepickett** [comment]
@mairaw ,  I missed that you were leaving this one for me, sorry. No, I can't get to it, I have a long list I am working through already right now on the AspNetCore.docs repo.  This one is up for grabs.  Sorry I mishandled this one.
