### ISSUE TITLE
Bad essay.

### ISSUE THREAD

**Issue by crclz** [dotnet/docs#14249]
Essay in 2008: Framework Design Guidelines, is still 99% useful and much better than your so-called "best practice".

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea31f6-516f-100d-046e-1a0445d92824
* Version Independent ID: a713e8c9-8210-761d-9ae7-238793825ff3
* Content: [Best Practices for exceptions - .NET](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)
* Content Source: [docs/standard/exceptions/best-practices-for-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
This content is (with permission) from that book.
