### ISSUE TITLE
How much information should go in an Integration Event?

### ISSUE THREAD

**Issue by LukePammant** [dotnet/docs#14248]
Should an integration event simply hold the AggregateID and the deltas of what changed in this event? Or should it publish the entirety of aggregate? In the example of `ProductPriceChangedIntegrationEvent` it looks like just the delta is published.

I could see the benefit of publishing the whole aggregate as it would allow any downstream consumers to take what ever information it needs from the event. If there are any view stores that may care about displaying data from the aggregate of a different service it could simply overwrite it's current projection of that aggregate. Perhaps adding an aggregate version # would make sure that you're not overwriting newer data with an older event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b037f198-3ee2-28f4-4d93-0999e5d3d3ef
* Version Independent ID: 9bd96308-c726-fcee-850e-a38fd22ff555
* Content: [Implementing event-based communication between microservices (integration events)](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @LukePammant, thanks for your feedback, it's an interesting question!

As usual, it depends, there's not a one-size-fits-all solution.

I can mention some criteria I've seen being used:

- What's the size of the aggregate and how large is the transaction rate? There can be bandwidth/cost restrictions.
- Does the size of the message fit in the queue implementation? The event might just carry an Id and minimum data, so you can get the aggregate from storage if more data is needed.
- Do you need to replicate the data or just work with the event information.

The above are just samples, but I think that help make the point.

You always have to adapt to your context.

My personal preference is to implement just what's required. The needs might include some future considerations, but not of the kind "send it all just case". But that's just a personal preference, not an absolute rule. 

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
