### ISSUE TITLE
OData links are broken

### ISSUE THREAD

**Issue by ciaran036** [dotnet/docs#14257]
The OData links for the System Query Operations section are broken. The links point to a 'It's moved...' page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02c1d3ca-d567-5b3c-d4f9-4329c403f6fa
* Version Independent ID: 8b343173-2a8b-521b-a6e1-56a5835ae4a5
* Content: [Accessing Data Service Resources (WCF Data Services)](https://docs.microsoft.com/en-us/dotnet/framework/data/wcf/accessing-data-service-resources-wcf-data-services#system-query-options)
* Content Source: [docs/framework/data/wcf/accessing-data-service-resources-wcf-data-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/wcf/accessing-data-service-resources-wcf-data-services.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Youssef1313** [comment]
I'll open a PR that updates it.
