### ISSUE TITLE
Document what's new in .NET Standard 2.1

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#14254]
2.1 is coming, We need to document what's new.

Should we cover in the same topic like we do for .NET Framework or split like we do for C# or .NET Core?

@terrajobst is this something you could help us put together? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de130a75-fed2-0567-6e3d-07a384900eec
* Version Independent ID: a2993c26-93f8-7281-d6ca-5fcc899e95f3
* Content: [What's new in the .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp)
* Content Source: [docs/standard/whats-new/whats-new-in-dotnet-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/whats-new/whats-new-in-dotnet-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
While updating for Core 3.1 I ran across this page. I've updated the comment metadata to remove ron.

**Comment by mairaw** [comment]
Thanks @Thraka. @terrajobst can you help to write the what's new in .net standard 2.1 content?

**Comment by mairaw** [comment]
Duplicate of #9221
