### ISSUE TITLE
Don't update thread-local variable in body of Parallel.For call. It has no non-local effect.

### ISSUE THREAD

**Issue by rablewis** [dotnet/docs#14293]
These lines for the loop body in the example are misleading/confusing:

    subtotal += nums[j];
    return subtotal;

Updating the thread-local variable has no effect in subsequent iterations. It is the return value that controls how the sum is reduced across multiple loop iterations. I suggest replacing the above two lines with something like this:

    long newSubtotal = subtotal + nums[j];
    return newSubtotal;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875f7621-16eb-0795-0c24-eb93201932f1
* Version Independent ID: 71775687-6f47-4152-5e83-82e31f323757
* Content: [How to: Write a Parallel.For Loop with Thread-Local Variables](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-parallel-for-loop-with-thread-local-variables)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-parallel-for-loop-with-thread-local-variables.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-write-a-parallel-for-loop-with-thread-local-variables.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@BillWagner thoughts?

**Comment by BillWagner** [comment]
@tdykstra The current code is correct, but as @rablewis points out, it could mislead customers to believe that `subTotal` is treated like a reference variable. That change is good. Or, it could be changed to be even more concise:

```csharp
Parallel.For<long>(0, nums.Length, () => 0, (j, loop, subtotal) => subtotal + nums[i],
            (x) => Interlocked.Add(ref total, x)
        );
```

Would you agree?

**Comment by tdykstra** [comment]
LGTM except `nums[i]` should be `nums[j]`.

**Comment by tdykstra** [comment]
The text doesn't seem to explain how this actually divides up the work among different threads -- how many threads get created?

**Comment by BillWagner** [comment]
@tdykstra We cover that in the introduction to PLINQ, starting with [this section](https://docs.microsoft.com/dotnet/standard/parallel-programming/introduction-to-plinq?view=netframework-4.8#execution-modes)

**Comment by tdykstra** [comment]
That explains it, thanks. Shall I PR this with your code or put it up-for-grabs?

**Comment by BillWagner** [comment]
I'd add up-for-grabs.  The fix is well defined:

- [ ] update the code per https://github.com/dotnet/docs/issues/14293#issuecomment-543828001, with your fix.
- [ ] Add a link to the [execution mode section](https://docs.microsoft.com/dotnet/standard/parallel-programming/introduction-to-plinq#execution-modes) of the introduction to PLINQ article.
