### ISSUE TITLE
C# 8.0: new index and range operators

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#14297]
New index-from-end (`^`) and range (`..`) operators should be added to the language reference. Short descriptions and examples and then reference already existing tutorials.

@BillWagner this is for the [C# 8 docs project](https://github.com/dotnet/docs/projects/58).
Could you please assign this issue to me?

Is the [Member access operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators) a proper article to mention new operators? If not, they get their own pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @pkulikov 

Assigned and labeled.
