### ISSUE TITLE
Incorrect hot keys used

### ISSUE THREAD

**Issue by jaaronb** [dotnet/docs#14290]
Since this is the macOS version of getting started a few changes need to happen.

Under the header Debug the Application, first paragraph it says to use F9 to insert a breakpoint.  On a mac users must use the combination fn+F9.  In the second paragraph, the hotkey combo listed to show the debug screen is Ctrl + Shift + D.  On a mac, it should be Cmd + Shift + D.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Get started with .NET Core on macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by Youssef1313** [comment]
I'm not sure about the `fn+` addition. I haven't used mac, but I think it could be `F9` or `fn+F9` depending on user settings. so I think `F9` is just enough. I'll open a PR now to replace `Ctrl` with `Cmd`, Reviewers with write-access can then suggest the addition of `fn+` if they see it's correct or just accept the PR with only `Ctrl` -> `Command`

**Comment by jaaronb** [comment]
Thank you.  By default mac users must use the fn key to access function keys.  Please see apple link referencing how to use function keys on a Mac.

https://support.apple.com/en-us/HT204436
