### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by AignerGames** [dotnet/docs#14298]
I tried to use this method, but the GetUnicastAddresses didn't return any IP addresses which had IsIPv6Teredo  true. Do I have to do anything else to "enable" this feature?
 
I started a TcpListener with AllowNatTraversal set to true and set it to listen before calling GetUnicastAddresses not sure if the order makes a difference in this case?

Does the TcpListener have to use a specific port for this method?

Is this still a recommend way to handle NAT in 2019 or are there newer methods/ways?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef99bd6-bf1a-7337-b135-9c515a387547
* Version Independent ID: 60f6f5ad-b128-14d3-9c81-ddb52694952b
* Content: [NAT Traversal using IPv6 and Teredo](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/nat-traversal-using-ipv6-and-teredo#feedback)
* Content Source: [docs/framework/network-programming/nat-traversal-using-ipv6-and-teredo.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/nat-traversal-using-ipv6-and-teredo.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
@davidsh can you help with these questions?

**Comment by davidsh** [comment]
>I tried to use this method, but the GetUnicastAddresses didn't return any IP addresses which had IsIPv6Teredo true. Do I have to do anything else to "enable" this feature?
I started a TcpListener with AllowNatTraversal set to true and set it to listen before calling GetUnicastAddresses not sure if the order makes a difference in this case?
Does the TcpListener have to use a specific port for this method?
Is this still a recommend way to handle NAT in 2019 or are there newer methods/ways?

IPv6Teredo is a transitional technology which was used to enable IPv6 connections over IPv4 networks. But in today's world, most routers, modems, and ISPs support both IPv4 and IPv6 directly. In those cases, you won't see any "Teredo" network interfaces listed at all when do you an "ipconfig /full" from the CMD.EXE window.

The use of the IPv6 teredo network interface is also subject to enterprise group policy depending on your network. There are ways to diagnose this.  See: https://social.technet.microsoft.com/Forums/windows/en-US/943a3542-67d7-4071-9a3f-f567a8f079f9/teredo-offline-how-to-enable-it

>Is this still a recommend way to handle NAT in 2019 or are there newer methods/ways?

NAT is a concept usually for local area networks and IPv4 networks only. But IPv6 doesn't really need NAT at all. That is why proper firewall configuration is important.
