### ISSUE TITLE
"dotnet publish" documentation does not tell you about how to use a saved XML profile

### ISSUE THREAD

**Issue by sdg002** [dotnet/docs#14301]
This is a feedback on the documentation of "dotnet publish" command found [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)

It was only after reading through https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.2 I got to know what you could pass the name of the XML file and have **dotnet publish** do the publishing without having to specify all the individual arguments.

Example:

> dotnet publish  c:\Work\SomeProject.csproj /p:PublishProfile=FolderProfile.pubxml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @sdg002. We have to make updates to this article for 3.0 and we'll consider your feedback when updating the article.
