### ISSUE TITLE
"dotnet publish" does not provide sufficient guidance when there is a private Nuget feed

### ISSUE THREAD

**Issue by sdg002** [dotnet/docs#14302]
This is feedback about the documentation of the "**dotnet publish**" command which is available on this [site](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21).

I have a simple CSPROJ which references a nuget package from a private feed. The **dotnet publish** command fails with the following error:

> C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\NuGet.targets(123,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/kiteedge/_packaging/apex/nuget/v3/index.json.
C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized)
---

I get a hint that **NUGET** is expecting credentials for the private **NUGET** feed.  However, the documentation provides no assistance to solve this problem.

You could provide additional links at the bottom of the page which directs the developer to the right source.  We have to understand that Visual Studio development and build is not something that can be taken lightly any more. 

While, I appreciate that Microsoft is giving the developer the opportunity to provide feedback through Github, this cannot be a substitute for sloppy in-house testing. Microsoft should take the responsibility of providing sensible documentation - documentation which has been tried and tested. 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by vasilp** [comment]
This docs updated still does not work:
https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md#implicit-restore
What we see is:

**Implicit restore**
[!INCLUDEdotnet restore note]    <---- the link goes nowhere (404) !
