### ISSUE TITLE
When use the when keyword in a catch expression the app crashes instead of do what the document says

### ISSUE THREAD

**Issue by walterlv** [dotnet/docs#14338]
## Issue

There is such a sentence here:

> The expression of the user-filtered clause is not restricted in any way. If an exception occurs during execution of the user-filtered expression, that exception is discarded and the filter expression is considered to have evaluated to false. In this case, the common language runtime continues the search for a handler for the current exception.

When there is an exception occurred in the when expression the exception will be ignored and the expression will return false.

But it only works in .NET Core 3.0 but not in .NET Framework 4.8.

## Demo

See such a demo below:

```csharp
try
{
    try
    {
        Console.WriteLine("Try");
        throw new FileNotFoundException();
    }
    catch (FileNotFoundException ex) when (ex.FileName.EndsWith(".png"))
    {
        Console.WriteLine("Catch 1");
    }
    catch (FileNotFoundException)
    {
        Console.WriteLine("Catch 2");
    }
}
catch (Exception)
{
    Console.WriteLine("Catch 3");
}
Console.WriteLine("End");
```

This is the output of .NET Core 3.0 and everything works fine:

![image](https://user-images.githubusercontent.com/9959623/64590498-437b5c00-d3da-11e9-895b-5494c5eee268.png)

But this is the output of .NET Framework 4.8 and we can notice that the app crashes:

![image](https://user-images.githubusercontent.com/9959623/64590536-5b52e000-d3da-11e9-9df9-b61aa020a5d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde724f2-477d-3b4c-b22c-d574f64fbd65
* Version Independent ID: 8ca8aff8-e528-67db-a7ed-a1baba927b16
* Content: [Using User-Filtered Exception Handlers](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers#feedback)
* Content Source: [docs/standard/exceptions/using-user-filtered-exception-handlers.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/using-user-filtered-exception-handlers.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Youssef1313** [comment]
It seems that the reason is `ex.FileName` being `null`.

I don't know the reason that makes it works on core but not .net framework. but the following should work on both.

`catch (FileNotFoundException ex) when (ex.FileName != null && ex.FileName.EndsWith(".png"))`

**Comment by Thraka** [comment]
Verified. This doesn't happen when you use a classic style project that targets 4.8, only when you use the newer SDK style projects that target 4.8 Please open a bug at https://github.com/dotnet/corefx/issues

Thanks.

**Comment by walterlv** [comment]
@Thraka Thanks.
