### ISSUE TITLE
example code error

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs#14342]
example code error: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/join-clause#example
error 1：
Console.WriteLine("GroupJoin3: {0} items in 1 group", totalItems, groupJoinQuery3.Count());
should update：
Console.WriteLine("GroupJoin3: {0} items in {1} group", totalItems, groupJoinQuery3.Count());

or：
Console.WriteLine("GroupJoin3: {0} items in 1 group", totalItems);

error 2：
Console.WriteLine("Group:", prodGrouping.Count());
should update：
Console.WriteLine("Group{0}:", prodGrouping.Count());
   
or：
Console.WriteLine("Group:");

so the output should update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f64bda9-3763-e0a0-fbb9-22f6fd50beca
* Version Independent ID: d552325f-7578-efb3-3f6d-927169181391
* Content: [join clause - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/join-clause#example)
* Content Source: [docs/csharp/language-reference/keywords/join-clause.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/join-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
A fix to this was done by @imba-tjd in https://github.com/dotnet/samples/pull/1444

**Comment by BillWagner** [comment]
closing as duplicate.

**Comment by kinglionsz** [comment]
> A fix to this was done by @imba-tjd in [dotnet/samples#1444](https://github.com/dotnet/samples/pull/1444)

Thank you for your reply but it seems that you have solved the issue which I found ,and not the repeat issue.

**Comment by kinglionsz** [comment]
> closing as duplicate.
> 
> @kinglionsz This PR was merged this morning. The updates should be live tomorrow, on our regular publishing cycle.

Thank you for your time .
