### ISSUE TITLE
OUTPUT ERROR:the code it's self  correct,but the output format is not expected

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs#14358]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-element-access-operator-

###  1, the issue:

the code it's self  correct,but the output format is not expected

`
unsafe
{
    char* pointerToChars = stackalloc char[123];

    for (int i = 65; i < 123; i++)
    {
        pointerToChars[i] = (char)i;
    }

    Console.Write("Uppercase letters: ");
    for (int i = 65; i < 91; i++)
    {
        Console.Write(pointerToChars[i]);
    }
}
// Output:
// Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ

`
### The above code  `   Console.Write(pointerToChars[i]);    ` output format is not  `  Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ  `  .in fact, this code output will be:

`
Uppercase letters:
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z

`

please see the screen snip:

<img width="422" alt="char_array_pointer_output_error" src="https://user-images.githubusercontent.com/51827261/64659900-addedb80-d470-11e9-9c84-72c903e68f86.png">

### 2, to obtain the expected ouput:

          Uppercase letters:
          ABCDEFGHIJKLMNOPQRSTUVWXYZ

### Reference code should be as follows:

`

        unsafe
        {
            char* pointerToChars = stackalloc char[123];

            for (int i = 65; i < 123; i++)
            {
                pointerToChars[i] = (char)i;
            }

            string ss = "";
            Console.WriteLine("Uppercase letters: ");
            for (int i = 65; i < 91; i++)
            {
                ss += pointerToChars[i];
            }
            Console.WriteLine(ss);
        }
        //  output:
        //  Uppercase letters:
        //  ABCDEFGHIJKLMNOPQRSTUVWXYZ
`
<img width="913" alt="char_array_pointer_output_ok" src="https://user-images.githubusercontent.com/51827261/64660603-b2f15a00-d473-11e9-8186-d933ff76ea39.png">

I hope that Microsoft DOCS International Team will correct the issue.
Thank you for your time .
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f615ca9-4bdb-38c9-26e2-21ed1218d524
* Version Independent ID: fc94240e-e933-efd2-263b-aa08d431dabb
* Content: [Pointer related operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-element-access-operator-)
* Content Source: [docs/csharp/language-reference/operators/pointer-related-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/pointer-related-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@kinglionsz interesting how you've got such an output?

If I copy the snippet to the following console program:

```csharp
using System;

public class Program
{
    public static void Main()
    {
        unsafe
        {
            char* pointerToChars = stackalloc char[123];

            for (int i = 65; i < 123; i++)
            {
                pointerToChars[i] = (char)i;
            }

            Console.Write("Uppercase letters: ");
            for (int i = 65; i < 91; i++)
            {
                Console.Write(pointerToChars[i]);
            }
        }
        // Output:
        // Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ
    }
}
```

and run it, the output is as expected:
![image](https://user-images.githubusercontent.com/15279990/64668848-82072a00-d45f-11e9-99d7-126d231ee412.png)

The *.csproj* file is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
```

Also, if I `dotnet run` the [complete project](https://github.com/dotnet/samples/tree/master/csharp/language-reference/operators) that contains that snippet (this one already targets .NET Core 3.0), the output would contain the following lines

```text
======= Pointer related operators examples =====
Value of the variable: 27
Address of the variable: 82623BE554
Value of the `letter` variable: A
Address of the `letter` variable: 82623BE554
Value of the `letter` variable after update: Z
(3, 4)
Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ
Value 10 at address 2663064309144
```

Note the second line from the bottom.

**Comment by imba-tjd** [comment]
@pkulikov It's because he doesn't know `Write`, only knows `WriteLine`. I have pointed it out but he refused to accept it 🤷‍♂

**Comment by kinglionsz** [comment]
Yes, It was my fault. I typed  `Console.WriteLine` instead of  `Console.Write` because I type the code with IntelliSense and not copy the snippet.

Thank you so much and  thank you for your time. @pkulikov

**Comment by kinglionsz** [comment]
> @pkulikov It's because he doesn't know `Write`, only knows `WriteLine`. I have pointed it out but he refused to accept it 🤷‍♂

I like code instead of copying the code

**Comment by pkulikov** [comment]
@kinglionsz cool that the mystery is resolved, thanks:). I guess this issue and related one in the loc repo might be closed.

**Comment by kinglionsz** [comment]
> @kinglionsz cool that the mystery is resolved, thanks:). I guess this issue and related one in the loc repo might be closed.

👌☕

**Comment by BillWagner** [comment]
I'm glad this was resolved.

Closing.

@imba-tjd @CeciAc Can one of you close the related loc issue? 'm not sure which repo it's in. Thank you

**Comment by kinglionsz** [comment]
> I'm glad this was resolved.
> 
> Closing.
> 
> @imba-tjd @CeciAc Can one of you close the related loc issue? 'm not sure which repo it's in. Thank you

👌☕Thank you for your time. @BillWagner @pkulikov @imba-tjd @CeciAc
