### ISSUE TITLE
Commanets are misleading

### ISSUE THREAD

**Issue by lucius-the** [dotnet/docs#14359]
"ByVal does not prevent changing the value of a field or property."
ByVal actually DOES prevent changing the value of a field or property (as seen clearly in output).

"ByVal does prevent changing the value of c1 itself."
ByVal actually does NOT prevent changing the value of c1 itself (as seen clearly in output).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3085184c-671d-92b5-b596-3af0a848b7c8
* Version Independent ID: 4b8973b8-47df-64cd-98ff-5b3ea17860cf
* Content: [ByVal (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/byval#feedback)
* Content Source: [docs/visual-basic/language-reference/modifiers/byval.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/byval.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
@lucius-the Hello. Reading through the code and the output it seems to be correct.

I've added some remarks:

```vb
' THRAKA: At this poiint c1.Field is 5
    ' ByVal does not prevent changing the value of a field or property.
    ChangeFieldValue(c1)
' THRAKA: The method has modified c1.Field to 500. ByVal didn't prevent that.
    Console.WriteLine(c1.Field)
    ' Output: 500
```

```vb
' THRAKA: At this poiint c1.Field is 500 from the previous method call
    ' ByVal does prevent changing the value of c1 itself. 
    ChangeClassReference(c1)
' THRAKA: The method call above changed the reference in the method to a new object. That did not affect this reference, c1.
    Console.WriteLine(c1.Field)
    ' Output: 500
