### ISSUE TITLE
Loan Object Interest rate issue.

### ISSUE THREAD

**Issue by Esjihn** [dotnet/docs#14367]
Please change interest rate property to 

  private double _interestRate;
        public double InterestRate
        {
            get { return _interestRate * 100;}
            set { _interestRate = value; }
        }

to calculate accurate percentage rates. This will make the interest rate in the testLoan object show up correctly. However, you will still have an issue with testLoan.InterestRate change this to be the same decimal format as the interest rate in the test loan object so

instead of 7.1 change it to 0.071. testLoan.InterestRate = 0.071;

Then when the application executes it will correctly show interest rate. 

New customer value: Henry Clay
7.5
7.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7bc5cfb-d247-62c8-2173-9403efe72b16
* Version Independent ID: 3fab702d-66a7-3338-6c61-f535b29d86a7
* Content: [Walkthrough: Persisting an Object using C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this issue @Esjihn 

I agree that referring to an "interest rate" not using a percentage is confusing. I'm going to make a different suggestion.  If it were updated as above, the result would be:

```csharp
loan.LoanAmount = 0.071;
Console.WriteLine(loan.LoanAmount); // displays "7.1".
```

What would you think of the following:
- [ ] Change the property and field name to `PercentageInterestRate` and `_percentageInterestRate` for clarity.
- [ ] Change the first initialization to use a percentage.

I've added this to our backlog, and added the "up for grabs" label. Would you like to submit a PR for these change?

**Comment by Esjihn** [comment]
Hello Bill,

The first initialization used the correct decimal amount of 0.075 and the
second one did not 7.1. Since there is no calculation for interest rate in
the property the only way you would get this result.

[image: image.png]

 is to either make the TestLoan object second parameter 7.5 or to calculate
the percentage and change the second interest rate to be an actual
percentage "0.071". Either way is fine. Ive never submitted a "PR". I only
thought there was this feed back option and if something got changed I
would be added to contributor list.

Either way I appreciate your time and thanks for all your communication.

Best Regards,

Matthew D. Miller
Information Systems Programmer
Florida Senate

**Comment by BillWagner** [comment]
@Esjihn This is fine for feedback. We'll update this sample as part of our regular updates.

Our docs are all Open Source, so anyone can make contributions. Those contributions are [Pull Requests](https://help.github.com/articles/creating-a-pull-request). The [Readme](https://github.com/dotnet/docs) on our repository has pointers to get started, if you are interested.

**Comment by Esjihn** [comment]
Hello Bill,

Oh a pull request. Sorry for not putting the two together. Alright, thanks
for the heads up and I appreciate the update.

Best Regards,

Matthew
Information Systems Programmer
Florida Senate

**Comment by SeanKilleen** [comment]
I'll take this one on -- seems straight-forward enough. Will open a PR shortly.
