### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by boskjoett** [dotnet/docs#14364]
[Enter feedback here]
The examples section contains a wrong example.
This line:
`dotnet test --logger:trx`
should have been:
`dotnet test --logger trx`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @boskjoett. I've opened PR #14374 to fix this issue.

You can also make edits to our content when you find issues. For more information, see https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
