### ISSUE TITLE
Creating loan object

### ISSUE THREAD

**Issue by Esjihn** [dotnet/docs#14366]
this.customer = customer;

should be 

this.Customer = customer

which uses the Customer property instead of directly calling and accessing (violating encapsulation) the private variable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7bc5cfb-d247-62c8-2173-9403efe72b16
* Version Independent ID: 3fab702d-66a7-3338-6c61-f535b29d86a7
* Content: [Walkthrough: Persisting an Object using C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Esjihn 

The sample is correct: In the constructor, you'd want to initialize the field without using the property.

**Comment by Esjihn** [comment]
Hello Bill,

Can you help me understand why the rest were initialized by their
properties (LoanAmount, InterestRate, and Term) and customer was not? I
want to be sure I do not make a mistake like this in the future.

Best Regards,

Matthew
Information Systems Programmer
Florida Senate

**Comment by BillWagner** [comment]
@Esjihn 

The other properties are [auto implemented properties](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties), where the compiler creates a backing field. The only way to initialize those is through the property. This property doesn't use that feature because it raises the `NotifyPropertyChanged` event in its setter.

I hope that helps.

**Comment by Esjihn** [comment]
Hello Bill,

So would initializing it through its property instead of the field not
cause the NotifyPropertyChanged event handler to send the event state to
its subscriber? I guess I don't understand what would be lost here by using
the same implementation as the other properties when initializing them
through the constructor. I appreciate your patience.

Best Regards,

Matthew
Information Systems Programmer
Florida Senate

**Comment by BillWagner** [comment]
@Esjihn In this example, there likely wouldn't be any difference between using the property or accessing the field directly. If I saw either version in a code review, I wouldn't recommend a change.

**Comment by Esjihn** [comment]
Thanks Bill for the clarification. Much appreciated.

Best Regards,

Matthew
Information Systems Programmer
Florida Senate
