### ISSUE TITLE
Mention Model Explainability

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#14379]
Mention the definition of Model Explainability here since feature importance with PFI is part of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1fb0dd-648b-26e9-7e4e-48824ab94160
* Version Independent ID: 689b6488-dadc-fd39-c432-ebf095a0299a
* Content: [Explain model predictions using Permutation Feature Importance - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
AB#1599455
