### ISSUE TITLE
Search doesn't work for symbols

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1439]
Search in the .NET Docs for `||>`.  

Expected: [F# Symbol and Operator Reference](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/symbol-and-operator-reference/) is in the results.

Actual: No results.  See: https://docs.microsoft.com/en-us/search/index?search=%7C%7C%3E&scope=.NET

Background:

Someone trying F# for the first time reported in the Functional Programming Slack that they came across some code using `||>` and didn't know what it was.  They tried searching in the docs and got the above results.  I imagine C# would have similar issues with tokens like `??` and `?.`.

**Comment by mairaw** [comment]
We probably need to file an internal bug for this one. 

I've seen other issues with search that would be good to follow-up.

/cc @EisenbergEffect @dend @bradygaster

**Comment by EisenbergEffect** [comment]
I'll create a bug to track this.

**Comment by EisenbergEffect** [comment]
I've created the bug in our system and alerted the engineering team that works on search of the issue. @cartermp Thanks for alerting us of the issue!

**Comment by cartermp** [comment]
Thanks!

**Comment by mairaw** [comment]
I'm keeping it in the backlog as external to track its completion.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/228
