### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by jonnybest** [dotnet/docs#14406]
I could really use an example here... or maybe a pointer to a tutorial where this is being used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef284edc-3711-7491-2d2e-fdda96b31471
* Version Independent ID: 703dd0e7-1c2a-daf0-994c-a66d5ee764c6
* Content: [LocalDeclarationStatementSyntax Class (Microsoft.CodeAnalysis.CSharp.Syntax)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.localdeclarationstatementsyntax?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/LocalDeclarationStatementSyntax.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/LocalDeclarationStatementSyntax.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jonnybest. @BillWagner are we adding samples to the Roslyn API docs?
