### ISSUE TITLE
Magic string values in argument

### ISSUE THREAD

**Issue by jonnybest** [dotnet/docs#14407]
Could you please document some of the expected values for "string language", 2nd argument? It's unclear what to put here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8122dc37-51db-e5ea-9c69-1b4703aba433
* Version Independent ID: 348c34f1-dc19-e571-a236-a7eec90e9047
* Content: [SyntaxGenerator.GetGenerator Method (Microsoft.CodeAnalysis.Editing)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.syntaxgenerator.getgenerator?view=roslyn-dotnet#Microsoft_CodeAnalysis_Editing_SyntaxGenerator_GetGenerator_Microsoft_CodeAnalysis_Workspace_System_String_)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.Editing/SyntaxGenerator.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.Editing/SyntaxGenerator.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
I think you should pass one of the constants defined in [LanguageNames](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.languagenames?view=roslyn-dotnet)

**Comment by jonnybest** [comment]
That's it! 

    var generator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);

Thanks so much. :)
