### ISSUE TITLE
API might get conflated

### ISSUE THREAD

**Issue by drdamour** [dotnet/docs#14408]
I *think* it's not intentional but the statement "can only be accessed via its microservice API" in practice in my experience makes people picture JSON over HTTP only.  Much later it's mentioned about websockets and AMPQ as other protocols i'd presume you build an API on...but Microservice API seems to have been generally equated to JSON over HTTP which is often incorrectly called REST.  

Said alternately, the statement "can only be accessed via its microservice API" makes it seem like there must be a client & request/response (pull) paradigm to access microservice data...when in fact it can be shared in more push paradigm as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81283b66-f8c6-4d93-73c8-551e1681f51e
* Version Independent ID: c637cf8d-163a-4717-371f-2ff40d61f314
* Content: [Data sovereignty per microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/data-sovereignty-per-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @drdamour, thanks for your feedback.

Honestly I think the "microservice API" is as abstract and technology agnostic as can be, I would've agreed with your if it had said "microservice REST API", but I don't see noting about the way the API is implemented.

Anyway, how do you think it could be better stated?

Hope this helps.

**Comment by drdamour** [comment]
I know that and u know that but 99/100 devs I run into don’t currently
think that way today.  Latter sections define apis as rest, ampq, binary,
and websockets.  I suggest denoting that here (eg “be they rest, websocket,
binary, message based, etc”)  and a link to those later sections that
explicitly define the encompassing term with examples beyond the current
group think.

I’ve found myself avoiding the term api as much as I can since it seems so
overloaded.  I usually say external services or interfaces.  IE “a
microservice encapsulates it’s data and functions only offering access to
it through its external interfaces.”  When I get in api discussions with
most they end up settling in the service death star distributed monolith
with a lot of cache.

**Comment by mvelosop** [comment]
Fair enough @drdamour, 

I'll add the clarification that can be any type of API such as...)

Thanks!
