### ISSUE TITLE
NuGet metadata properties is not up to date with the NuGet targets

### ISSUE THREAD

**Issue by nkolev92** [dotnet/docs#14411]
**Issue description**

https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties is not up to date with https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets

More specifically; 
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file

Should we maybe avoid duplication and link directly to the NuGet docs?

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
The plan is to actually create an entire reference for the SDK-style project and remove this information from this page, so I believe we'll need to keep the NuGet properties in our docs.
It would be weird to have all but the NuGet tags in the reference once we create that reference.

Thoughts?

**Comment by mairaw** [comment]
We haven't started this work yet so I don't have the author's name. But you can always ping me.

**Comment by nkolev92** [comment]
Sounds good. 
I'll communicate to the team to take the dotnet docs in account when making changes to docs that impact the CLI/SDK.

**Comment by mairaw** [comment]
Sounds great @nkolev92! I think this is a good workflow.

**Comment by georg-jung** [comment]
Any progress on this? I just fell into the "trap" of following the outdated part of this doc which lead me to https://aka.ms/deprecateIconUrl when trying to upload a package to nuget.org.

**Comment by tdykstra** [comment]
Closing this, as csproj.md was updated with PackageIcon/PackageIconURL information by #19745, and the [project SDK doc](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#package-properties) that will replace csproj.md already links to https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets
