### ISSUE TITLE
None of the links under "I want to watch some videos..." appear to go to pages with videos

### ISSUE THREAD

**Issue by bhalbright** [dotnet/docs#14418]
For example
"WCF Data Services Developer Videos" goes to sql server documentation.
"OData: Developers Web site" link is not valid anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a6ad7cb-5dcf-6c21-7f65-0c75174faa4b
* Version Independent ID: f09a1edc-8d2f-f060-5120-c5ff85257fa2
* Content: [WCF Data Services 4.5](https://docs.microsoft.com/en-us/dotnet/framework/data/wcf/index)
* Content Source: [docs/framework/data/wcf/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/wcf/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Youssef1313** [comment]
If the videos are really needed, I think I may be able to find them. Can you assign me ?
/cc @mairaw @rpetrusha

**Comment by mairaw** [comment]
Thanks @bhalbright for your comment and @Youssef1313 for your suggestion.

I don't think we need to create a new topic for this. The WCF documentation is badly outdated so I'll leave to @HongGit to decide to what to do with this article. Probably the easiest thing would be to remove the links we can't find anymore. I can't even see what those looked like before on MSDN like I can with other articles.

**Comment by Youssef1313** [comment]
@mairaw 
> Probably the easiest thing would be to remove the links we can't find anymore. I can't even see what those looked like before on MSDN like I can with other articles.

The content of this broken link isn't really lost ^_^

Here is how I was able to find it (it *may* help with other articles):
1. The link of the `Beginner's Guide to WCF Data Services` is <https://go.microsoft.com/fwlink/?LinkId=220864>
2. If you open it, it redirects to <https://docs.microsoft.com/en-us/dotnet/framework/wcf/index?redirectedfrom=MSDN>, but it is not really one redirect. It redirects to <http://msdn.microsoft.com/en-us/data/ee720180> first. (Got it from the `location` response header.
3. Search for <http://msdn.microsoft.com/en-us/data/ee720180> in `web.archive.org`.
4. Now, it's just a luck. The original content may or may not be found.
5. For the `Beginner's Guide to WCF Data Services` link, It's found at 24 Mar 2016. <https://web.archive.org/web/20150516084913/https://msdn.microsoft.com/en-us/data/ee720180>

Here is how the page looked at that time:
![image](https://user-images.githubusercontent.com/31348972/64893274-ee0fab00-d676-11e9-88e9-d79d51914d7e.png)

6. Clicking on `Building an OData Service (Part I)` link inside `web.archive` opened its content with a downloadable ZIP file for the video.

![image](https://user-images.githubusercontent.com/31348972/64893339-15ff0e80-d677-11e9-866a-339bf86ec9ba.png)

I tried to download the first and second videos and succeeded.

**Comment by bhalbright** [comment]
Thanks @Youssef1313!

**Comment by mairaw** [comment]
Oh yeah, forgot about trying the wayback machine!

**Comment by Thraka** [comment]
Sent email to Hong

**Comment by mairaw** [comment]
The links were removed in a recent PR. So closing this.
