### ISSUE TITLE
Retire this page

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#14422]
@davidsh I think this page could be retired in favor of the API docs (https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener).

Is the information about HTTP.SYS important to keep? If so, I'd move that to the remarks of the HttpListener class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8dbd5b-69c5-d83b-acb4-75eb2b74884e
* Version Independent ID: 0459b971-aea8-0217-cabe-3549b23d0834
* Content: [HttpListener](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/httplistener)
* Content Source: [docs/framework/network-programming/httplistener.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/httplistener.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by davidsh** [comment]
>@davidsh I think this page could be retired in favor of the API docs (https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener).

Yes, the page could be retired. I would keep the "HTTP.SYS" section though with the words

```
The HttpListener class is built on top of HTTP.sys, which is the kernel mode listener that handles all HTTP traffic for Windows. HTTP.sys provides connection management, bandwidth throttling, and Web server logging. Use the HttpCfg.exe tool to add SSL certificates. For more information, see the documentation on the HttpCfg.exe tool in the Server documentation."
``

You can edit it down but the key things to keep are about the HttpCfg.exe tool because it is required to be used in order to configure TLS/SSL usage of HttpListener.
