### ISSUE TITLE
Multiple instances of a type can be declared in the using statement

### ISSUE THREAD

**Issue by lopezroberto** [dotnet/docs#14420]
The code in the example produces error: CS0819: Implicitly-typed variables cannot have multiple declarators.

using (var font3 = new Font("Arial", 10.0f),
            font4 = new Font("Arial", 10.0f))
{
    // Use font3 and font4.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Oh, Embarassing. I've reviewed the file history and this bug was produced by me in https://github.com/dotnet/samples/pull/1042.

I've opened https://github.com/dotnet/samples/pull/1472 to fix that.
