### ISSUE TITLE
Interesting trade-off

### ISSUE THREAD

**Issue by sleette** [dotnet/docs#14435]
So by using asynchronous programming, your application can continue with other work while waiting for longer-running processes to complete. Sounds good, but I noticed two downsides:
1.  While using async and await definitely make the task-based model easier to understand than manipulating threads directly, it is still somewhat more complex than regular synchronous programming.
2. What's worse, it appears that orange juice is no longer available..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @sleette 

Yes, you're correct on the tradeoffs. Asynchronous programming *is* more complex than synchronous programming. While these features improve the situation, there's still complexity.

Closing as by-design.
