### ISSUE TITLE
Indices and ranges: supported sequence types

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#14449]
Not only the mentioned array and Span types support indices and ranges.

https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/index-range-changes.md (which is about to be merged into https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md) introduces the notion of countable types. That way, the support of indices and ranges might be pattern-based.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @pkulikov 

Do you want me to assign this to you?

**Comment by pkulikov** [comment]
> Do you want me to assign this to you?

@BillWagner yes, please. I'll address this issue as soon as #14451 is merged
