### ISSUE TITLE
Create doc on converters for System.Text.Json

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#14445]
Related to #12207

**Comment by vintzl** [comment]
@tdykstra 

Related to this:
 - https://github.com/aspnet/AspNetCore/issues/14254

Could you please provide us a general guidance, even as simple as [this doc](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.0), on how to write Custom JsonConverters **with inheritance**.

**Comment by tdykstra** [comment]
@vintzl The linked ASP.NET Core issue mentions this [custom converter example](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/CustomConverterTests.Polymorphic.cs) and suggests it does what you want.  Is it helpful?

**Comment by vintzl** [comment]
Not exactly, I was looking for some writer/reader usages, etc…
