### ISSUE TITLE
System.FormatException: 'Input string was not in a correct format.' #476

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs#14455]
the code run error: System.FormatException: 'Input string was not in a correct format.'

[https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#attributes](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#attributes)

`Console.WriteLine("  Url={0}, Topic={1}", a.Url, a.Topic);`

should be:

`Console.WriteLine($" Url= \"{a.Url}\" , Topic = \"{a.Topic}\" ");`

Please update.
Thanks.

<img width="960" alt="input format error" src="https://user-images.githubusercontent.com/51827261/64961532-51444c00-d8c8-11e9-82e9-a1ec4fb1baa6.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#other-function-members)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The code in the article is correct, You just have extra spaces, it should be `{0}` and `{1}` not `{ 0 }` and `{ 1 }`. Both lines should behave identically. However, the usage of string interpolation is more preferred as it makes the code more readable. I'll open a PR to add string interpolation

**Comment by kinglionsz** [comment]
Thank you so much firstly. Yes, I have tested with  {0} and {1},that's OK.

But I don't see why it's not OK with blank? (you say:" It should be {0} and {1} not { 0 } and { 1 }")

please note the following code is ok.

`            int i = 20;
            Console.WriteLine($" int i = { i }");`
`int i = 20;
Console.WriteLine("int i = {0}", i);`


but the following code is error:

` int i = 20;
Console.WriteLine("int i = { 0 }", i);`
 
please explain. Thank you for your time.

**Comment by Youssef1313** [comment]
In the first case:

```csharp
int i = 20;
Console.WriteLine($" int i = { i }");
```

which is also identical to:

```csharp
int i = 20;
Console.WriteLine($" int i = {i}");
```

This is called [string interpolation](https://docs.microsoft.com/dotnet/csharp/language-reference/tokens/interpolated) , it's a language feature that was introduced in C# 6.
It just provides a more readable syntax than the usage of `string.Format`. but the compiler just transforms it to a call to `string.Format` method.
You can say that it takes whatever inside the curly braces, put a number instead of it, and passes what was inside the curly braces to a the `string.Format`.
so spaces really doesn't matter here.

--------

In the second case:

```csharp
 int i = 20;
Console.WriteLine("int i = {0}", i);
```
Inside of the .NET Framework, the arguments of `Console.WriteLine` are passed to `string.Format`, and this is just how `string.Format` works.

-----------
In the third case:

```csharp
 int i = 20;
Console.WriteLine("int i = { 0 }", i);
```

Short answer: This is not how `string.Format` should work, `string.Format` expects `{number}` without any spaces. Nothing more, Nothing less.

Long answer: That will require going a little bit deep inside the .NET source code. The real magic that causes `string.Format` to really do its job is an internal method called `AppendFormatHelper`. That method was designed to expect a number between the curly braces without additional spaces.

**Comment by kinglionsz** [comment]
@Youssef1313 Thank you for your patient and careful answer.

I agree with what you said "That method was designed to expect a number between the curly braces without additional spaces."

`Console.WriteLine(" Url= { 0 }, Topic = { 1 }", a.Url, a.Topic);      // runtime error! System.FormatException: 'Input string was not in a correct format.`

`Console.WriteLine($" Url= { a.Url } , Topic = { a.Topic } ");           // run ok`

But for the same "the index between the curly braces with additional spaces",Why the above line code runtime error and the bottom line code run OK?

I think  they call the same method "The real magic that causes string.Format to really do its job is an internal method called AppendFormatHelper",But the results are different.

I look forward to your further answers and thank you for your time.☕😁

**Comment by Youssef1313** [comment]
@kinglionsz ,

```csharp
Console.WriteLine(" Url= { 0 }, Topic = { 1 }", a.Url, a.Topic);
Console.WriteLine($" Url= { a.Url } , Topic = { a.Topic } ");
```

Yes, both lines gets to `string.Format` in some way.
But with the second line, the compiler itself converts it to the the following:

```csharp
Console.WriteLine(string.Format(" Url= {0} , Topic = {1} ", a.Url, a.Topic));
```

**Comment by kinglionsz** [comment]
@Youssef1313 ，
I see. Thanks.

**Comment by BillWagner** [comment]
Thanks for questions, the answer, and the discussion. 

This article is part of C# 6 draft spec. We're not updating this while we work with the ECMA standards committee to reconcile the C# 6 draft with the official 5.0 standard. I'm going to close this while we finish that work. As pointed out above, the example is correct (while outdated). For now, we want to stay as close to the standard while we bring the two sources together.

**Comment by kinglionsz** [comment]
> Thanks for questions, the answer, and the discussion.
> 
> This article is part of C# 6 draft spec. We're not updating this while we work with the ECMA standards committee to reconcile the C# 6 draft with the official 5.0 standard. I'm going to close this while we finish that work. As pointed out above, the example is correct (while outdated). For now, we want to stay as close to the standard while we bring the two sources together.

Thank you very much! @BillWagner

**Comment by Ahmad-Rana** [comment]
How Can I resolve this issue In the C# Code Given Below? 

### Issue
(System.FormatException: 'Input string was not in a correct format.')

**Code**
               Grandbox.Text = (Convert.ToInt16(Grandbox.Text) + Convert.ToInt16(Totalbox.Text)).ToString();


> Details
Here Grandbox and Totalbox are textbox and other issue is that when I Start it and try to run it automatically close @Youssef1313 Youssef1313 @kinglionsz kinglionsz
