### ISSUE TITLE
typo in document

### ISSUE THREAD

**Issue by fkucuk** [dotnet/docs#14456]
there is a typo template.json file the property should be 
"shortName": "stringtext" 
not 
"shortName": "stringext"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
I think `stringext` is correct. `ext` is for `extension`. Look at the name in the previous line, it's `Example templates: string **extensions**`.

**Comment by Thraka** [comment]
Hi @fkucuk . Thank you for reporting this. @Youssef1313 is correct though. This is the short name for the example outlined in the article, string extensions. It's not a definition trying to tell you what value to put in there. Thanks though!
