### ISSUE TITLE
System.FormatException: 'Input string was not in a correct format.'

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#14457]
@kinglionsz commented on [Mon Sep 16 2019](https://github.com/dotnet/docs.zh-cn/issues/476)

https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/language-specification/introduction#attributes

the code run error: System.FormatException: 'Input string was not in a correct format.'

`Console.WriteLine("  Url={0}, Topic={1}", a.Url, a.Topic);`

should be:

`Console.WriteLine($" Url= \"{a.Url}\" , Topic = \"{a.Topic}\" ");`

Please update.
Thanks.

<img width="960" alt="input format error" src="https://user-images.githubusercontent.com/51827261/64961582-6f11b100-d8c8-11e9-880d-8a19505df209.png">

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [介绍Introduction - C# language specification](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang.zh-cn/blob/live/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Mon Sep 16 2019](https://github.com/dotnet/docs.zh-cn/issues/476#issuecomment-531759817)

Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is reporting an error in the original documentation
best

**Comment by kinglionsz** [comment]
> Hi team,
> I'm moving this here because the user is reporting an error in the original documentation
> best

 I'm sorry to subject you to this trouble, this report is same with the main report: https://github.com/dotnet/docs/issues/14455

Thank you for your  @CeciAc

**Comment by BillWagner** [comment]
Closing per comment on #14455
