### ISSUE TITLE
[Project] Update project.json content to msbuild projects

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1445]
This is a meta-issue for the [Update from project.json based projects to csproj based projects](https://github.com/dotnet/docs/projects/5) project.

Subtasks will be defined as this project is planned in full.

Comment below to suggest new content, or updates to existing content.

**Comment by mairaw** [comment]
Project is close to being done.

**Comment by BillWagner** [comment]
I added the up-for-grabs label to this project. The work that remains is to migrate several small projects that were originally created using project.json style projects. The `dotnet migrate` command will likely work on all of them.  See the 'Notes' column in the linked project for more information.
