### ISSUE TITLE
Add documentation for the new global.json options in 3.0

### ISSUE THREAD

**Issue by nguerrera** [dotnet/docs#14479]
See https://github.com/dotnet/core-setup/pull/6953 and https://github.com/dotnet/designs/pull/71

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#feedback)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for filing the issues for some of the CLI features @nguerrera. It's been in my backlog to do that. I'm adding this to our next sprint.
