### ISSUE TITLE
.NET Core 3 WPF and Windows Forms Support

### ISSUE THREAD

**Issue by AntonLandor** [dotnet/docs#14473]
The comparison with .NET Framework notes that [.NET Core 3 will support WPF and Windows Forms.](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/). However, the comparison with Mono does not mention this. Mentioning that .NET Core 3 will support WPF and Windows Forms and replacing ".NET Core doesn't support these" would be useful since the reader is not guaranteed to read both comparisons thoroughly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [About .NET Core](https://docs.microsoft.com/en-us/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs/blob/master/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @AntonLandor. I've opened #14487 to update that article.
