### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by rhlgupta1383** [dotnet/docs#14477]
Java 8 features are not accounted for in this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91388e65-01f7-d27c-38d0-4e2113cef43a
* Version Independent ID: ad74fdd5-880a-df4c-731c-235c8d42d7db
* Content: [Introduction to the C# Language and the .NET Framework](https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework#feedback)
* Content Source: [docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md](https://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @rhlgupta1383 
You are correct that the comparison to java has not been updated.

It's also true that the latest C# features are not mentioned in the comparison.

I've added it to the projects for C# 8 content and our next sprint. 

I've also added the up-for-grabs label for community members to update.
