### ISSUE TITLE
Add information about new global.json options in 3.0

### ISSUE THREAD

**Issue by nguerrera** [dotnet/docs#14480]
See also:

https://github.com/dotnet/docs/issues/14479
https://github.com/dotnet/core-setup/pull/6953
https://github.com/dotnet/designs/pull/71

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
It seems this would fold into this section correct where some of this info is already there:
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-roll-forward

**Comment by jnm2** [comment]
@mairaw It confused me at first, but `global.json`'s rollforward feature is about SDK selection at the time that you build the csproj and the runtime rollforward feature detailed at https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#major-version-roll-forward is about runtime selection at app startup time.
