### ISSUE TITLE
ComDefaultInterface 

### ISSUE THREAD

**Issue by DaveInCaz** [dotnet/docs#14493]
ComDefaultInterface attribute is missing from this page. This page seemed to be comprehensive and is easy to find, so it seems like it really should be added. https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comdefaultinterfaceattribute?view=netframework-4.8  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8ae5f1-0288-ac2a-052a-204243b0a79c
* Version Independent ID: 84680b6a-89b4-dc34-a446-47c24338e170
* Content: [Applying Interop Attributes](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/apply-interop-attributes#feedback)
* Content Source: [docs/standard/native-interop/apply-interop-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/apply-interop-attributes.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@AaronRobinsonMSFT, @jkoritzinsky please comment

**Comment by AaronRobinsonMSFT** [comment]
@tdykstra Sounds reasonable. PR created and referenced here.

**Comment by tdykstra** [comment]
Thanks @DaveInCaz  and @AaronRobinsonMSFT !
