### ISSUE TITLE
Update the csproj reference to be aligned with the latest csproj templates

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1449]
The current one in Preview 3 is out of date with respect to some things, especially the use of metadata as attributes instead of child elements.

**Comment by mairaw** [comment]
Can you give more details on this one? I'm not exactly sure which topic you're talking about here.

**Comment by blackdwarf** [comment]
@mairaw the csproj reference/additions document. I think we fixed this one in the latest batch of fixes.

**Comment by mairaw** [comment]
That's what I thought. Thanks for confirming @blackdwarf.

**Comment by mairaw** [comment]
Fixed with #1553
