### ISSUE TITLE
Windows logo key

### ISSUE THREAD

**Issue by Abedron** [dotnet/docs#14490]
With Dark theme is windows logo key icon unrecognised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @Abedron. You're right, the icon disappears. We should replace the icon with something that works in all themes.
