### ISSUE TITLE
Documentation for new dotnet new

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1450]
In RC3 we have added `dotnet new3` which will, in RTW, become `dotnet new`. It is a new way to create templates, much more powerful than previous `new`.

**Comment by sayedihashimi** [comment]
>“After this, the project is ready to be compiled and/or edited further.”
That’s not 100% accurate. The user has to run dotnet restore before it’s ready to be compiled.
 
>“The command contains a default list of templates; use dotnet new --help”
This should be changed to “dotnet new --list”
 
In the article I don’t see any usage of project template specific help. For example dotnet new mvc --help. We should include that.

**Comment by mairaw** [comment]
This is issue is already closed @sayedihashimi. can you open a new one please?

**Comment by sayedihashimi** [comment]
@mairaw https://github.com/dotnet/docs/issues/1623
