### ISSUE TITLE
upcast indeterminate on Casting Guide

### ISSUE THREAD

**Issue by PhilT** [dotnet/docs#14508]
When trying to change the following code:

```
let base1 = d1 :> Base1
```
to

```
let base1 = upcast d1
```
as instructed, I get the following error:

```
casting_and_conversions.fsx(106,13): error FS0013: The static coercion from type
    Derived1
to
    'a
 involves an indeterminate type based on information prior to this program point. Static coercions are not allowed on some types. Further type annotations are needed.
```

EDIT: I should point out I'm using .NET Core 3 Preview 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725e0bb1-2dcd-4e9e-2714-f0a56d248992
* Version Independent ID: e5eeed3a-2684-f465-7ced-a6122d478f0e
* Content: [Casting and Conversions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/casting-and-conversions)
* Content Source: [docs/fsharp/language-reference/casting-and-conversions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/casting-and-conversions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by PhilT** [comment]
Just for clarity here is the code copied from my FSI file:

```
type Base1() =
  abstract member F : unit -> unit
  default u.F() =
    printfn "F Base1"

type Derived1() =
  inherit Base1()
  override u.F() =
    printfn "F Derived1"

let d1 : Derived1 = Derived1()
let base1 = upcast d1 // Upcast to Base1 with type inference
```

**Comment by PhilT** [comment]
I get a similar problem with an example further up, `let color = enum 1` where it should infer the type as `Color`. Maybe this doesn't work in FSI?

**Comment by jdodds** [comment]
It doesn't work anymore outside of FSI in F# 4.7 either:

```fsharp
type Color =
  | Red = 1
  | Green = 2
  | Blue = 3

let col1 = enum 1 
``

```
Could not resolve the ambiguity in the use of a generic construct with an 'enum' constraint at or near this position

Type constraint mismatch when applying the default type 'obj' for a type inference variable. The type 'obj' is not a CLI enum type Consider adding further type constraints
```

**Comment by cartermp** [comment]
Updates snippets and the doc. I'm not sure if they were ever correct (some of this documentation is very old).
