### ISSUE TITLE
The version drop downs in the breaking changes page are almost invisible in dark theme

### ISSUE THREAD

**Issue by divega** [dotnet/docs#14517]
Text is black over dark gray background. Only the selection rect is visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0fe0b7-01c9-d11e-a432-b7ac4639f51c
* Version Independent ID: 9e7f5a4a-13dd-dc9a-9ba7-1208bdbe6c4f
* Content: [.NET Core breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/breaking-changes)
* Content Source: [docs/core/compatibility/breaking-changes.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/breaking-changes.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Good point @divega! I'll send this to our engineering team.

**Comment by gewarren** [comment]
They're unusable in the "high contrast" theme. Black text on a black background.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2369
