### ISSUE TITLE
"@ai" email address wont match

### ISSUE THREAD

**Issue by chao-master** [dotnet/docs#14511]
the .ai TLD has an MX record, allowing for email to be delivered to recipient@ai.
However this email regex will fail to match it as `(([0-9a-z][-0-9a-z]*[0-9a-z]*.)+[a-z0-9][\-a-z0-9]{0,22}[a-z0-9])` does not match "ai"
the correct regex would match the first group 0 or more times (`(([0-9a-z][-0-9a-z]*[0-9a-z]*\.)*`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format#feedback)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@ViktorHofer, @maryamariyan please comment
