### ISSUE TITLE
Tables Clipped off

### ISSUE THREAD

**Issue by dasMulli** [dotnet/docs#14519]
The tables are clipped off because they extend below the visible area of the main content and thus need horizontal scrolling to read.
Tested on latest Safari And Chrome on macOS 10.14, 15" MacBook Pro at full available screen width.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d476d66c-4f04-3742-cf90-4177aceb4138
* Version Independent ID: 482be47f-3dec-5470-5e83-88afd9c2bcca
* Content: [Retargeting Changes for Migration from .NET Framework 4.7.2 to 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.2-4.8#managed-cryptography-classes-do-not-throw-a-cryptographyexception-in-fips-mode)
* Content Source: [docs/framework/migration-guide/retargeting/4.7.2-4.8.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/retargeting/4.7.2-4.8.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **ronpet**

**Comment by dasMulli** [comment]
Screenshot:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/6129250/65274037-bf844b00-db22-11e9-8bc4-c8dd43030e44.png">

**Comment by mairaw** [comment]
I've opened #14559 to test if this new extension we have for docs would help.

**Comment by mairaw** [comment]
The first test failed: 😢 it still looks bad.

![image](https://user-images.githubusercontent.com/12971179/65362565-ba73da00-dbbc-11e9-88d5-bbd8cfcc0245.png)

**Comment by mairaw** [comment]
My tests unfortunately didn't work. We would probably need to move to a format similar to what we're doing in the .NET Core version to fix this:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0

@rpetrusha thoughts?

**Comment by dasMulli** [comment]
btw I hate tables anyway.. 🤣
