### ISSUE TITLE
Breaking change Identity UI AddDefaultUI(UIFramework) overload removed

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/docs#14526]
Original announcement https://github.com/aspnet/Announcements/issues/380

## Breaking change Identity UI AddDefaultUI(UIFramework) overload removed

In ASP.NET Core 3.0 we've moved Identity UI to use the new static web assets feature introduced in 3.0. As part of this move there are a few API breaking changes to note.

### Version introduced

3.0

### Old behavior

AddDefaultUI(UIFramework) overload existed in 2.2

### New behavior

AddDefaultUI(UIFramework) has been removed.

### Reason for change

Bootstrap4 is the default UI framework for Identity UI. (Bootstrap 3 has reached end of life and you should consider migrating to a supported version).

### Recommended action

Simply call `AddDefaultUI()` instead. If you are using Bootstrap3, additionally add the following line to your project file inside a PropertyGroup,

`<IdentityUIFrameworkVersion>Bootstrap3</IdentityUIFrameworkVersion>`

### Category

ASP.NET Core

### Affected APIs

[AddDefaultUI(UIFramework)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identitybuilderuiextensions.adddefaultui?view=aspnetcore-2.2#Microsoft_AspNetCore_Identity_IdentityBuilderUIExtensions_AddDefaultUI_Microsoft_AspNetCore_Identity_IdentityBuilder_Microsoft_AspNetCore_Identity_UI_UIFramework_)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by ajaybhargavb** [comment]
Closing as we won't need these here.

**Comment by mairaw** [comment]
Reopened as requested by Artak Mkrtchyan.

**Comment by robinwilson16** [comment]
Thanks, just came across this issue.
Have updated the instructions I put together here so adding link as a reference:
aspnet/AspNetCore.Docs#14817
