### ISSUE TITLE
Break down features by areas

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#14538]
One thing I've noticed while going through this doc today is that it's missing the usual breakdown of areas that we do for the what's new topics.
e.g. https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-0

I think it would be nice to organize the new features per area.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Yes. Due to how fast changes came through it was better to just detail everything so as people had a single area to look at for information. I always intended that this article should eventually be broken down, become smaller, and only feature the most important pieces.
