### ISSUE TITLE
Document the base CRUD commands (add/list/remove)

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1453]
The convention we have is to have `dotnet add/list/remove/update` verbs followed by a noun that "specifies"  what the verb will operate on. I think we should cover this convention somehow and explain it to people.

**Comment by blackdwarf** [comment]
@mairaw I was thinking that we may need several topics for this:

* A general introduction to the fact that CLI now offers CRUD commands and explaining the convention
* A reference for each command 

Thoughts?

**Comment by blackdwarf** [comment]
@spboyer are you working on this?

**Comment by spboyer** [comment]
I was working on the doc(s) for `reference` and `package` not the overall one.

**Comment by mairaw** [comment]
Should we remove this issue from PR #1569? Maybe this issue here can be covered with the additional updates we need to make to the main dotnet page?

**Comment by spboyer** [comment]
I'll defer to @blackdwarf

**Comment by mairaw** [comment]
I've removed it from the PR for now. I'll discuss this with @blackdwarf offline.

**Comment by mairaw** [comment]
We need to document those separately for commands such as `dotnet help add` to work.

**Comment by GuardRex** [comment]
@mairaw Are we doing this for add/list/remove/update separately (a paragraph to explain the convention in each description)? ... or just once (one paragraph) in the main `dotnet` cmd doc?

**Comment by mairaw** [comment]
let's discuss... people will be able to type dotnet help add for example and we need to think what's the experience we want. 

@richlander @livarcocc BTW, this is the reason why the command was not going anywhere the other day. we don't have those pages/aka.ms links created for these

**Comment by GuardRex** [comment]
We left our discussion on these points/possibilities ...
1. Adding a section to each CRUD command (add/list/remove/update) as opposed to only one section in the main `dotnet` command topic.
2. Along with the general description of the convention, add a note that explains that in the case of `dotnet help <command>` that "help" is the verb and "command" is the noun.

Is that guidance ok?

**Comment by mairaw** [comment]
I don't think we need specific pages for those and the aka.ms links are now set up accordingly.
