### ISSUE TITLE
How do I include dependancies.

### ISSUE THREAD

**Issue by BrianMinister** [dotnet/docs#14544]
I have gone through dozens of permutations, and it all acts like --no-dependencies is enabled when it isn't.
```dotnet pack src\My.Utilities.Web\Lcp.Utilities.Web.csproj -p:PackageVersion=%2  --output src\Lcp.Utilities.Web\bin\Release```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@BrianMinister Hello. Can you share your package references in your project file with me?

**Comment by BrianMinister** [comment]
You can close this. The project got defunded, since it was a roadblock to another project. We have resumed manual releases until we are past the go live date.

**Comment by BillWagner** [comment]
Thanks @BrianMinister I'll close it.
