### ISSUE TITLE
Add BeginInvoke and EndInvoke usage and example for delegates

### ISSUE THREAD

**Issue by AzimAnsari** [dotnet/docs#14541]
It would be nice if we have a separate topic of using BeginInvoke and EndInvoke methods for delegates. And dangers of not using EndInvoke methods is some cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b07199-b747-9596-1d38-3257f43b4833
* Version Independent ID: d162375c-ef5a-41c1-fe26-2e6394bf1df1
* Content: [How to: Declare, Instantiate, and Use a Delegate - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate#feedback)
* Content Source: [docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @AzimAnsari 

I've added it to our backlog to address when we next update this article.

**Comment by KalleOlaviNiemitalo** [comment]
.NET Core intentionally does not implement BeginInvoke and EndInvoke for delegates. dotnet/corefx#5940, <https://github.com/dotnet/coreclr/blob/922429db0144dd6f3b4324805464dae82857512a/src/vm/comdelegate.cpp#L1996-L2003>
