### ISSUE TITLE
The note in the "remarks" section of the "IsNot Operator" page is outdated

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/docs#14540]
&gt; The IsNot operator cannot be used to compare expressions returned from the TypeOf operator. Instead, you must use the Not and Is operators.

This is wrong. If you use VB 14.0 or higher, you can write `TypeOf ... IsNot ...`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4aecef0-c2d3-cc96-9068-fe2950a9c293
* Version Independent ID: fb5b21e0-be1d-a9bd-474d-4b8dcd8ec328
* Content: [IsNot Operator (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/isnot-operator)
* Content Source: [docs/visual-basic/language-reference/operators/isnot-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/isnot-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
I've already opened #14419 a while ago.

**Comment by mairaw** [comment]
Thanks @Youssef1313 and @Nukepayload2. We'll follow up on the active PRs soon.

**Comment by rpetrusha** [comment]
This has been fixed by #14419.
