### ISSUE TITLE
The NULL value is not checked correctly in the Tutorial.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#14542]
**The comment below was Machine translated** 

@lacostaplans commented on [Fri Sep 20 2019](https://github.com/dotnet/docs.es-es/issues/136)

The implementation, according to the documentation, of the Answer method (in SurveyResponse):

`        public string Answer(int index) => surveyResponses.GetValueOrDefault(index, "No answer")!;
`

Generates a warning CS8604.

The correct implementation would be (not to have the warning):

`   public string Answer(int index) => surveyResponses?.GetValueOrDefault(index, "No answer")!;
`

But with this implementation, the following code:

```
 var surveyResponse = new SurveyResponse(1);

string awswer = surveyResponse.Answer(1);

var length = answer.Length;

```

It does not generate a warning, but when executing, a ** NullReferenceException ** is started on the line:

`var length = answer.Length;
`

Since ** answer ** is NULL. However, the method signature is ** public string Answer **, not ** public string? Answer **

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Diseño con tipos de referencia que aceptan valores NULL](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/nullable-reference-types)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Fri Sep 20 2019](https://github.com/dotnet/docs.es-es/issues/136#issuecomment-533436365)

Hello, @lacostaplans
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team ,
I moved this here because the user is making suggestions on the code.
best regards

**Comment by ShowMeBillyJo** [comment]
I noticed this same error in the example. Additionally, the line...

> Because `surveyResponses` is a non-nullable reference type, no checks are necessary before de-referencing it.

...is incorrect. `surveyResponses` is a NULLABLE reference type in the example, and so needs to be dereferenced.
