### ISSUE TITLE
Dispose the internalTokenSource too? 

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docs#14589]
In the example `internalTokenSource` is  never disposed. Shouldn't it also be disposed? Readers may assume that `CreateLinkedTokenSource` will also dispose the linked sources of the linked tokens when `linkedCts`  gets disposed. Or maybe it actually does? If so, that would be worth a comment  above the `using` block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073f1486-9fa6-a17c-d649-d4ae5a36b8d8
* Version Independent ID: 55cc3625-d0a5-3422-0d27-945823a0c64b
* Content: [How to: Listen for Multiple Cancellation Requests](https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-multiple-cancellation-requests)
* Content Source: [docs/standard/threading/how-to-listen-for-multiple-cancellation-requests.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/how-to-listen-for-multiple-cancellation-requests.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@kouvel please comment

**Comment by kouvel** [comment]
Seems like it should be disposed, CC @tarekgh

**Comment by tarekgh** [comment]
yes internalTokenSource should get disposed. Even I don't think the initialization of it is needed as we initialize it anyway in the constructor. 

```C#
CancellationTokenSource internalTokenSource = new CancellationTokenSource();
```

CC @stephentoub

**Comment by stephentoub** [comment]
> Seems like it should be disposed

Technically, yes.  In practice, it won't currently matter as the Dispose in this case will end up being a nop.  Even so, it's good to do so.

> Even I don't think the initialization of it is needed as we initialize it anyway in the constructor.

Yes, the `internalTokenSource = new CancellationTokenSource();` line should be deleted; as the sample currently stands, the constructor will end up allocating this twice and just immediately overwriting one instance with the other.

**Comment by Hulkstance** [comment]
Garbage collector collects it, if you look at it with dnSpy.
