### ISSUE TITLE
How to create an instance of the class described in "where (generic type constraint) (C# Reference)"

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/docs#14582]
[In this document](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint)

This class is defined:

    public class AGenericClass<T> where T : IComparable<T> { }

And this statement is made:
> For example, you can declare a generic class, MyGenericClass, such that the type parameter T implements the IComparable<T> interface:

In the code below I am naming my example class Selector<T> instead of AGenericClass<T> 
and using interfacte ISelectable<T> instead of IComparable<T> { }
That is the only difference.

Can you please show me how to create an instance of `Selector` class using the same definition as `AGenericClass` shown in the c# documentation?

Again `AGenericClass` and `Selector` differ in name only:

    public class AGenericClass<T> where T : IComparable<T> { }

&nbsp;

    public class Selector<T> where T:ISelectable<T>    { }

&nbsp;

    public class Program2
    {

        public Program2()
        {
            Selector<Selectable<string>> stringSelector = new Selector<Selectable<string>>(); // does not build
        }
    }

    public interface ISelectable<T>
    {
        bool IsSelected { get; set; }
        T Item { get; set; }
    }

    public class Selectable<T> : ISelectable<T> 
    {
        public bool IsSelected { get; set; }
        public T Item { get; set; }
    }
  

    public class Selector<T> where T:ISelectable<T>    {    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74dfcde5-aa2b-1128-fa29-f198a6e437b7
* Version Independent ID: 59aeccf5-364c-77a8-88dc-cb529b76aebc
* Content: [where (generic type constraint) - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint)
* Content Source: [docs/csharp/language-reference/keywords/where-generic-type-constraint.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/where-generic-type-constraint.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@sam-wheat 

I made a few changes and this compiles for me:

```csharp
public class Program2
{

    public Program2()
    {
        Selector<Selectable> stringSelector = new Selector<Selectable>(); // does not build
    }
}

public interface ISelectable<T>
{
    bool IsSelected { get; set; }
    T Item { get; set; }
}

// This is the class that needs to change:
public class Selectable : ISelectable<Selectable> 
{
    public bool IsSelected { get; set; }
    public Selectable Item { get; set; }
}

public class Selector<T> where T:ISelectable<T>    {    }
```

I'll close this as answered.
