### ISSUE TITLE
out-of-order named arguments are invalid if they're followed by positional arguments.

### ISSUE THREAD

**Issue by SharunasBielskis** [dotnet/docs#14598]
I found that out-of-order named arguments are invalid if they are before positional arguments.
My examples with explanations of the tested code are in the StackOverflow page https://stackoverflow.com/questions/58005404/named-parameters-from-c-sharp-7-2/58061274#58061274 (user Sharunas Bielskis). Can you explain this case - is it error in this page text in in Visual Studio Editor note or I misunderstood something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e335f6e5-7d90-bfab-f95d-ab8ef3ba41fc
* Version Independent ID: 6be20f15-e5eb-0778-5fbe-38326d8e8f00
* Content: [Named and Optional Arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @SharunasBielskis The text in this article is misleading. Instead of the sentence: 

>However, out-of-order named arguments are invalid if they're followed by positional arguments.

A better phrasing is:

> Positional arguments that follow any out-of-order named arguments are invalid. 

I've added this to our backlog to address when we next update this article. I've also added the "up-for-grabs" label for community members to submit a PR with the above fix.
