### ISSUE TITLE
Reversed get/set requirements

### ISSUE THREAD

**Issue by ihorwill** [dotnet/docs#14591]
Against "Get" you have: "Optional. Required if the property is marked WriteOnly." This should say "Not required if..." or "Required unless..."  Similar mistake under "Set".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13cc422b-3c23-3fa9-4988-a98a57e3a19d
* Version Independent ID: 4ceca8d0-a7ae-ee9f-9b23-4862c4cb62c8
* Content: [Property Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/property-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/property-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/property-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
I think `WriteOnly` and `ReadOnly` just should be swapped between `Get` and `Set` and it will be correct. I'm opening a PR for this.
