### ISSUE TITLE
HttpRequestMessage default version

### ISSUE THREAD

**Issue by rafaelldi** [dotnet/docs#14611]
To enable HTTP/2, you need to set HttpRequestMessage version to the Version(2, 0). But the default version of HttpRequestMessage is already Version(2, 0). 
If the message version hasn't been set manually, what will be the protocol version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello. The default is 1.1.

Here is a test app:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var client = new HttpClient() { BaseAddress = new Uri("https://microsoft.com") };

        using (var response = client.GetAsync("/").Result)
            Console.WriteLine($"HTTP Version is: {response.Version}\n.NET Core Version: {System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription}");

        Console.ReadKey();
    }
}
```

The output:

```output
HTTP Version is: 1.1
.NET Core Version: .NET Core 3.0.0
```

Let me know if you have any other questions.

**Comment by rafaelldi** [comment]
Thank you, but the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=netcore-3.0#property-value) says, that default version of HttpRequestMessage is `2.0` since .NET Core 2.1. You showed that the default is `1.1`. I think there is a mistake in the docs.

**Comment by rafaelldi** [comment]
I've done the same example in the .NET Core 2.2 and .NET Core 3.0.
```
class Program
{
    static async Task Main(string[] args)
    {
        var client = new HttpClient() {BaseAddress = new Uri("https://microsoft.com")};

        using (var request = new HttpRequestMessage(HttpMethod.Get, "/") {Version = new Version(2, 0)})
        using (var response20 = await client.SendAsync(request))
            Console.WriteLine(
                $"Request version is {request.Version}\nHTTP Version is: {response20.Version}\n.NET Core Version: {System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription}");

        using (var request = new HttpRequestMessage(HttpMethod.Get, "/"))
        using (var response11 = await client.SendAsync(request))
            Console.WriteLine(
                $"Request version is {request.Version}\nHTTP Version is: {response11.Version}\n.NET Core Version: {System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription}");

        Console.ReadKey();
    }
}
```

Output in the .NET Core 3.0:
```
Request version is 2.0
HTTP Version is: 2.0
.NET Core Version: .NET Core 3.0.0
Request version is 1.1
HTTP Version is: 1.1
.NET Core Version: .NET Core 3.0.0
```

Output in the .NET Core 2.2:
```
Request version is 2.0
HTTP Version is: 1.1
.NET Core Version: .NET Core 4.6.28008.02
Request version is 2.0
HTTP Version is: 1.1
.NET Core Version: .NET Core 4.6.28008.02
```

So, the default version of request in the .NET Core 3.0 isn't a `2.0`.

**Comment by Thraka** [comment]
Awesome, thank you for linking to where you found that information. I'll look into it.
