### ISSUE TITLE
The ASP.net ebook preview link is broken

### ISSUE THREAD

**Issue by tauheedul** [dotnet/docs#14627]
The link to the ASP.net preview ebook is broken, it just takes you to the Microsoft shop page

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b96880e-76c7-c6f3-c45f-13d9301e77da
* Version Independent ID: 937c4b8a-8afc-98bb-ba22-02910a414656
* Content: [Blazor for ASP.NET Web Forms Developers](https://docs.microsoft.com/en-gb/dotnet/architecture/blazor-for-web-forms-developers/?utm_source=jeliknes&utm_medium=twitter&utm_campaign=link&WT.mc_id=link-twitter-jeliknes#feedback)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/index.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by scottaddie** [comment]
@tauheedul Thank you for reporting this problem. The aka.ms link is working now.
