### ISSUE TITLE
Unnecessarily unclear about greedy modifier used together with variable length quantifier

### ISSUE THREAD

**Issue by uKER** [dotnet/docs#14626]
In the description for these two
{n , }?
{n , m }?
the page is unnecessarily lengthy when all it should say is that they're both equal to {n}, matching exactly n times, as the question mark overrides any specification that the expression can match more than n elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#feedback)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Hi @uKER, thanks for your feedback.

I think on simple examples that might be true, but you also have to consider that regular expressions are used combined with other patterns. 

I just tested on a quick program and using those patterns in combination with others produces different results. So, I think we should keep the description as-is. 

Consider:

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
   public static void Main()
   {
      string input = "56 1234 637373 828";
      string pattern = @"\d{3}\s";

      foreach (Match match in Regex.Matches(input, pattern, RegexOptions.IgnoreCase))
         Console.WriteLine($"Match {match.Value} at position {match.Index}");
      //Match 234  at position 4
      //Match 373  at position 11

      pattern = @"\d{3}?\s";

      foreach (Match match in Regex.Matches(input, pattern, RegexOptions.IgnoreCase))
         Console.WriteLine($"Match {match.Value} at position {match.Index}");
      // Match 234  at position 4
      // Match 373  at position 11

      pattern = @"\d{3,}?\s";

      foreach (Match match in Regex.Matches(input, pattern, RegexOptions.IgnoreCase))
         Console.WriteLine($"Match {match.Value} at position {match.Index}");
      // Match 1234  at position 3
      // Match 637373  at position 8

      pattern = @"\d{3,5}?\s";

      foreach (Match match in Regex.Matches(input, pattern, RegexOptions.IgnoreCase))
         Console.WriteLine($"Match {match.Value} at position {match.Index}");
      // Match 1234  at position 3
      // Match 37373  at position 9

    }
}
```

You can give this code a try at https://try.dot.net/.
