### ISSUE TITLE
Windows Server 2008 SP2 seems to support .Net Framework 4.6.1

### ISSUE THREAD

**Issue by JulioNobre** [dotnet/docs#14625]
Recently, one of ours .Net Framework 4.6.1 dependent applications was succesfully installed on a Windows Server 2008 SP2 (not 2008 R2). Altough we had to remove all .Net installed frameworks and reinstall 4.6.1 package in order to start application successfully.
For this reason, I think that since .Net Frameowkr 4.6.1 installer supports Windows Server 2008, the above requirements should be revised according it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#feedback)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @JulioNobre. @jamshedd @vivmishra @NKarnam15 can one of you help to confirm this information for .NET Framework 4.6.1?

**Comment by jamshedd** [comment]
I recall the 4.6.1 installer had a bug and didn't correctly block on unsupported platforms. The customer should use the documentation as the definitive source of what is supported. Installing the 4.6.1 product on an unsupported platform will result in the machine not getting patched.

**Comment by JulioNobre** [comment]
Ok. We will stick upon documentation. Thanks for your clarification.
