### ISSUE TITLE
Possible Bug in Code for put_RiskRating()

### ISSUE THREAD

**Issue by limbioliong** [dotnet/docs#14624]
1. The code for the get_RiskRating() and put_RiskRating() methods may be erroneous. Both involve the management of the "RiskRating" member of the CLoan class which I assume is a BSTR. While it could be that "RiskRating" is an instance of a BSTR management class which performs automatic BSTR memory allocation/deallocation, this is not clear from the sample code.

2. In get_RiskRating(), "pVal", being an "out" parameter, should be given a copy of "RiskRating" instead of simply being assigned to point to "RiskRating". 

3. Hence I recommend that get_RiskRating() be re-written as follows :

```
STDMETHODIMP CLoan::get_RiskRating(BSTR* pVal)
{
	if (RiskRating != NULL)
	{
		// Make a copy of RiskRating and assign the copy
		// to the BSTR pointed to by pVal.
		*pVal = ::SysAllocString((const OLECHAR*)RiskRating);
	}
	else
	{
		*pVal = NULL;
	}

	return S_OK;
}
```

4. In put_RiskRating(), "RiskRating" is directly assigned "newVal" without first being freed. Furthermore, "RiskRating" should be made a copy of the newVal parameter instead of being assigned to newVal.

5. I recommend that put_RiskRating() be modified as follows :

```
STDMETHODIMP CLoan::put_RiskRating(BSTR newVal)
{
	// Note : must free the BSTR First.
	if (RiskRating != NULL)
	{
		::SysFreeString(RiskRating);
	}

        // And then make a copy of newVal.
	RiskRating = SysAllocString((const OLECHAR*)newVal);

	return S_OK;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ad12a5-1104-88ec-483c-f60966bade67
* Version Independent ID: 10b5b082-672a-e255-9d2c-300a7edf344f
* Content: [COM Interop Sample: .NET Client and COM Server](https://docs.microsoft.com/en-us/dotnet/framework/interop/com-interop-sample-net-client-and-com-server#feedback)
* Content Source: [docs/framework/interop/com-interop-sample-net-client-and-com-server.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/com-interop-sample-net-client-and-com-server.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for writing these @limbioliong 

I like your suggestion. You've specified what should change with enough detail that I've added the "up for grabs" label in case a community member wants to address it.

We'll address this when we next update this article.
