### ISSUE TITLE
What is the list of all F# warnings (number and description)?

### ISSUE THREAD

**Issue by TysonMN** [dotnet/docs#14629]
It would be helpful to me if there were a list of all possible F# warnings.  I have looked both within Microsoft's documentation as well as in general internet searches, but I have not found any such list.

The closest I have found to a list of #F warnings is the file [FSComp.txt](https://github.com/fsharp/fsharp/blob/6796cab77e804e8e16ac7693d1b1bd0fd071cd52/src/fsharp/FSComp.txt) in the F# source code, but it doesn't seem consistent with the few passing references to warnings in compiler options documentation (against which I have created this issue).

For example, the documentation for the compiler option `--warnon` says (in part)...
> ...the 1182 (unused variables) warning is off by default.

...which seems consistent with FSComp.txt since the warning number 1182 appears on [this line](https://github.com/fsharp/fsharp/blob/6796cab77e804e8e16ac7693d1b1bd0fd071cd52/src/fsharp/FSComp.txt#L1036).

On the other hand, the documentation for the compiler option `--warn` says (in part)...
> Level 5 warnings are: 21 (recursive use checked at runtime), 22 (let rec evaluated out of order), 45 (full abstraction), and 52 (defensive copy).

...which seems inconsistent with FSComp.txt since none of those warning numbers (21, 21, 45, and 52) appear on any line.

Is there documentation my Microsoft that lists all possible F# warnings?  If not, can such documentation be created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c40365d-5626-9a4f-4de3-15d14c40af2b
* Version Independent ID: 8fecd942-bbd7-7e61-092d-084896250876
* Content: [Compiler Options - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options)
* Content Source: [docs/fsharp/language-reference/compiler-options.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/compiler-options.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by abelbraaksma** [comment]
I seem to remember that these level 5 warnings are still in development. If so, the documentation is premature and should probably say so.
