### ISSUE TITLE
Protobuf should use snake_case, not camelCase

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs#14631]
re: https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-messages.md#property-names

https://developers.google.com/protocol-buffers/docs/proto3#simple

Should be updated here, and proto files throughout the book should be updated.

@markrendle @mairaw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed647fa-08e8-d503-74a2-097ac3c5022a
* Version Independent ID: 5087148f-07c4-8d4e-fe6b-d327f1b01532
* Content: [Protobuf messages - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-messages)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-messages.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-messages.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@shirhatti how is the process for getting these updates done? @markrendle can you take care of that?

**Comment by mairaw** [comment]
It seems #15271 is taking care of this issue already.
