### ISSUE TITLE
Very confusing for .Net Core

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#14630]
I thought that MemoryCache was compatible with .NET Core.  But this example of an unnamed XML file to configure the cache is confusing.

Where do I put this XML file?  What do I call it?  Or should I attempt to convert this to json and put it in my appsettings.json?

And is there a way to do this without having to use a file? 

The docs seem to say that using MemoryCache is a good option for apps migrating from the full .NET Framework.   And they seem to say that MemoryCache.Default is preferred if you only have one instance of a cache, but then it gets quite confusing to actually do it.

A good example of how to do this with .NET Core would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275f884-dbdc-645f-6ded-0a2fa0f16fa6
* Version Independent ID: d70654cc-2772-a302-b457-d962f6a82197
* Content: [&lt;memoryCache&gt; Element (Cache Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings?view=netframework-4.8)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Vaccano. @mconnew is this something you can help with?

**Comment by mconnew** [comment]
@StephenMolloy is the correct person for MemoryCache.
