### ISSUE TITLE
Blazor description is wrong

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/docs#14641]
The description of Blazor on this page is incorrect - Server side Blazor has nothing to do with WebAssembly.

Suggested edit:

> ASP.NET Core 3.0 introduces a new model for building rich, interactive, and composable UI called Blazor. Blazor server-side allows developers to build UI with C# and Razor on the server and for the UI to be interactively connected to the browser in real-time using a persistent SignalR connection. For more information about Blazor, see Get started with Blazor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad8df5d-9295-d659-a561-ec9cabd5b61f
* Version Independent ID: 7ee71103-d997-140e-2d35-d9f2a3913e09
* Content: [Choose between traditional web apps and single page apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @SQL-MisterMagoo for your feedback. 
@danroth27 @guardrex would you be able to help out with this feedback regarding Blazor?

**Comment by guardrex** [comment]
I'll yield to DR ... DR, let me know if you want me to help with this.

I'll cross-link our description ...

https://docs.microsoft.com/aspnet/core/blazor/

I recommend that the cross-link go to the *Overview*, not the *Get Started* topic. The *Overview* explains *what* it is much better.
