### ISSUE TITLE
Supported Linux Versions tab is still showing core 3 preview 1. 

### ISSUE THREAD

**Issue by thecodemonk** [dotnet/docs#14655]
This should be updated to reflect the release of core 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore30#feedback)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
PR #14315 will fix that.
