### ISSUE TITLE
Update Unit Testing using mstest with csproj based builds

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1467]
docs/core/testing/unit-testing-with-dotnet-test.md
docs/core/testing/using-mstest-on-windows.md

**Comment by mairaw** [comment]
can we close this one @BillWagner? PR seems to be merged into csproj

**Comment by BillWagner** [comment]
@mairaw Thanks for spotting.  Closing now.

This was fixed in PR# 1531
