### ISSUE TITLE
.NET API Browser should include when type is a ref struct

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#14688]
For example:

> public struct Utf8JsonReader

should be

> public ref struct Utf8JsonReader

`ref struct` can be used in more limited ways than regular `struct`, so it would be good if the documentation clearly shows the difference.

**Comment by BillWagner** [comment]
Ping @joelmartinez @dend 

This is an important suggestion from @tmds  We should add the `ref` modifier in our docs where applicable.

**Comment by joelmartinez** [comment]
@BillWagner indeed ... there is an existing issue to track this here:  
https://github.com/mono/api-doc-tools/issues/260

/cc @mimisasouvanh

**Comment by mairaw** [comment]
Closing this one then since it's an engineering bug and we have a tracking issue already.
