### ISSUE TITLE
Split Assembly Info Section into dedicated article

### ISSUE THREAD

**Issue by WilliamBerryiii** [dotnet/docs#14683]
Recommendation to split assembly info section into it's own article with solid SEO for developers looking to migrate from the "old" assembly info file to the csproj version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#assemblyinfo-properties)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
That's a great suggestion @WilliamBerryiii 

I've added it to our backlog to update when we next visit this aarticle.

**Comment by gewarren** [comment]
This was fixed by #22277.
