### ISSUE TITLE
Custom data in global.json

### ISSUE THREAD

**Issue by matkoch** [dotnet/docs#14687]
As the title says. Can I use global.json to persist custom data? Or will it be removed or cause a validation error at some point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
That's a good question @matkoch 

Adding @KathleenDollard who may know the answer.

**Comment by mairaw** [comment]
Adding @nguerrera to see if he can help with this question

**Comment by nguerrera** [comment]
I would generally recommend storing separate custom data in other files., but nothing will remove any custom data, and it will be skipped by the code that reads it in the .NET Core SDK. NuGet msbuild sdks and https://github.com/dotnet/arcade (infrastructure for building .NET repositories) already do this, in fact.

That said, there is no guarantee that future versions won't come along and use the same names as the "custom" data and that could cause unwanted results. So if you really want to do this, make sure to pick unique section names, etc.

**Comment by nguerrera** [comment]
I would not document this as an officially supported scenario.

**Comment by mairaw** [comment]
Appreciate your comments @nguerrera. Closing the issue then.

**Comment by matkoch** [comment]
@nguerrera thanks, that clarifies enough.
