### ISSUE TITLE
Loading and then Unloading DLL with dependency locks the DLL

### ISSUE THREAD

**Issue by winaterion** [dotnet/docs#14681]
I follow the .NET docs tutorial at:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability
and wanted to see if load/unload dll which has dependency will work.

I used AssemblyLoader with resolver:
```
class TestAssemblyLoadContext : AssemblyLoadContext
{
    private AssemblyDependencyResolver _resolver;

    public TestAssemblyLoadContext(string mainAssemblyToLoadPath) : base(isCollectible: true)
    {
        _resolver = new AssemblyDependencyResolver(mainAssemblyToLoadPath);
    }

    protected override Assembly Load(AssemblyName name)
    {
        string assemblyPath = _resolver.ResolveAssemblyToPath(name);
        if (assemblyPath != null)
        {
            return LoadFromAssemblyPath(assemblyPath);
        }

        return null;
    }
}
```

Then, I created 2 other projects, one is simple class without dependency, and the other is class that uses _newtonsoft json_ as dependency. then I publish those classes and put the DLL in a folder inorder to load it from my app. 
The first simple class which has no dependency, I loaded/unloaded with no problem, and able to delete the DLL.
The second DLL which has dependency was locked after unloading it, I try to wait for GC (as in the tutorial) , and loop forever, it never finishes. even if I try to delete the file after unload, it can't be deleted. seems like after running `LoadFromAssemblyPath `from my `TestAssemblyLoadContext`, some references are still in alive in the inner implementation of AssemblyLoadContext

Would be happy for some help, most of the people who use plugin probably has dependency, and not just a simple class i guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3283764-f15a-fa5f-5106-6f294c780f7b
* Version Independent ID: b03cedce-9074-9686-0b31-045b2b4c862d
* Content: [How to use and debug assembly unloadability in .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability)
* Content Source: [docs/standard/assembly/unloadability.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/unloadability.md)
* Product: **dotnet**
* GitHub Login: @janvorli
* Microsoft Alias: **janvorli**

**Comment by mairaw** [comment]
Thanks @winaterion. @janvorli can you help with this feedback?

**Comment by janvorli** [comment]
The problem is in the newtonsoft json, not in the plugin having dependencies in general. The newtonsoft json cannot be unloaded due to some of its internal implementation details. See the https://github.com/dotnet/coreclr/issues/26271 for more details.

**Comment by winaterion** [comment]
@janvorli I tried a different dependency, and it worked, **But**, I had to tweak the example in the documentation (at https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability) in order for it to work, Seems like when I publish my library which has dependencies (like SharpCompress for example), the example in documentation still locks the file, so instead of getting the assembly as said in the docs, I had to read the DLL from stream, and it would fix the DLL locking problem:
using (var fs = new FileStream(pluginLocation, FileMode.Open, FileAccess.Read))
{
    var pluginAssembly = loadContext.LoadFromStream(fs);
}

Thanks for the input though, newtonsoft would never work in any case, not even in stream ;)

**Comment by janvorli** [comment]
@winaterion you should not need to use the file stream trick, it should still work as is. I think the file lock is probably just a temporary thing. What you can try (just to verify that) is to keep a list of weak reference to all the assemblies loaded by the AssemblyLoadContext.Load method and modify the loop with GC.Collect / GC.WaitForPendingFinalizers so that it checks not only the weak reference to the assemblyloadcontext, but also all the weak references to the loaded assemblies and exit the loop only after all the weak references are not alive. That would prove whether there is a real problem in the runtime or whether it is a timing issue.

**Comment by winaterion** [comment]
@janvorli you are right, it seems to be working. I probably didn't clean some old DLLs because earlier when I run GC code, it went to infinite loop. All is perfect now, thanks for the support!  =)
