### ISSUE TITLE
Precedence of C# 8.0 switch expression

### ISSUE THREAD

**Issue by Janworks** [dotnet/docs#14698]
As discussed on [StackOverflow](https://stackoverflow.com/q/58088073/8528014), currently the documentation doesn't mention the precedence of the new `switch` expressions (which is between the categories `multiplicative` and `range`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#feedback)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I agree we should update the docs with this information. I checked the spec on recursive patterns, and I don't see confirmation for that decision. 

/cc @gafter to verify the suggestion above for precedence of the switch expression is correct.
