### ISSUE TITLE
Are bash uninstall commands comprehensive?

### ISSUE THREAD

**Issue by mrlife** [dotnet/docs#14701]
After running the bash commands on macOS for uninstalling SDKs and runtimes, running `dotnet --list-runtimes` still shows all the runtimes. The SDKs are gone.

Looks like this is how to remove a runtime, at least for versions prior to 3.0.0:

```
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.All/[version]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Remove the .NET Core runtime and SDK - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@mrlife 

I just tried on my machine, and those commands do remove everything. Can you add the output from `dotnet --info`, `dotnet --list-sdks` and `dotnet --list-runtimes` for us to understand what's going on?

**Comment by mrlife** [comment]
@BillWagner I believe this shows all the information. You can see that some things are installed in the `Microsoft.AspNetCore.All` folder, which is referenced in [Determine what is installed](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos#determine-what-is-installed) but not [Uninstalling .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos#uninstalling-net-core).

> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview8-013656/

> Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

> .NET Core SDKs installed:
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.300-preview1-008174 [/usr/local/share/dotnet/sdk]
  2.1.300-preview2-008533 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.1.701 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]
  3.0.100-preview6-012264 [/usr/local/share/dotnet/sdk]
  3.0.100-preview7-012821 [/usr/local/share/dotnet/sdk]
  3.0.100-preview8-013656 [/usr/local/share/dotnet/sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by BillWagner** [comment]
Adding @leecow 

When I did the following, all the preview 8 SDK and runtime elements (for example) were removed. I'm not sure what could be the issue here.

```bash
sudo rm -rf /usr/local/share/dotnet/sdk/3.0.100-preview8-013656
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0-preview8-28405-07
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.0.0-preview8.19405.7
sudo rm -rf /usr/local/share/dotnet/host/fxr/3.0.0-preview8.19405.7
```

You're right that for versions prior to 3.0, you also need to remove the asp.net core runtime from ***/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All***. We've removed that extra directory in the 3.0 wave instructions.

**Comment by leecow** [comment]
To be **_really_** clear, we're not talking about uninstalling, properly understood, in this thread; we're talking about manually deleting stuff from disk so understanding what's in the dotnet/ directory is rather important. Looks like the [Unistalling .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos#uninstalling-net-core) only talks about 1.0 and a number of things have changed since then. 

```bash
➜ tree /usr/local/share/dotnet -L 3 -d
/usr/local/share/dotnet
├── host
│   └── fxr
│       └── 3.0.0
├── packs
│   ├── Microsoft.AspNetCore.App.Ref
│   │   └── 3.0.0
│   ├── Microsoft.NETCore.App.Host.osx-x64
│   │   └── 3.0.0
│   ├── Microsoft.NETCore.App.Ref
│   │   └── 3.0.0
│   └── NETStandard.Library.Ref
│       └── 2.1.0
├── sdk
│   └── 3.0.100
│       ├── AppHostTemplate
│       ├── Current
│       ├── DotnetTools
│       ├── Extensions
│       ├── FSharp
│       ├── Microsoft
│       ├── Roslyn
│       ├── SdkResolvers
│       ├── Sdks
│       ├── TestHost
│       ├── cs
│       ├── de
│       ├── en
│       ├── es
│       ├── fr
│       ├── it
│       ├── ja
│       ├── ko
│       ├── pl
│       ├── pt-BR
│       ├── ref
│       ├── ru
│       ├── runtimes
│       ├── tr
│       ├── zh-Hans
│       └── zh-Hant
├── shared
│   ├── Microsoft.AspNetCore.All
│   │   └── 2.2.7
│   ├── Microsoft.AspNetCore.App
│   │   ├── 2.2.7
│   │   ├── 3.0.0
│   │   ├── 3.0.0-preview9.19424.4
│   │   └── 3.0.0-rc1.19457.4
│   └── Microsoft.NETCore.App
│       ├── 2.2.7
│       └── 3.0.0
└── templates
    └── 3.0.0

53 directories
```

**Comment by BillWagner** [comment]
Thanks for the details @leecow 

I've added this to our November sprint to make sure we update it before .NET Core 3.1 is released.

**Comment by mairaw** [comment]
@BillWagner should this be assigned to you and December milestone?

**Comment by IEvangelist** [comment]
Hi @mrlife,
This should be published later today, thanks for bringing it to our attention. I tested this out on my MacBook Pro and verified the updates that I made. Also, I added a but if clarification to the text.
