### ISSUE TITLE
Floating-point parsing operations no longer throw fail or throw an OverflowException

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#14705]
## Floating-point parsing operations no longer fail on overflows

The floating-point parsing methods no longer throw an `OverflowException` or return `false` when they parse a string whose numeric value is outside the range of the `Single` or `Double` floating point type.

### Version introduced

3.0

### Old behavior
In .NET Core 2.2 and earlier versions, the `Double.Parse` and `Single.Parse` methods throw an `OverflowException` for values that outside the range of their respective type. The `Double.TryParse` and `Single.TryParse` methods return `false` for the string representations of out-of-range numeric values.

### New behavior
Starting with .NET Core 3.0, the `Double.Parse`, `Double.TryParse`, `Single.Parse`, and `Single.TryParse` methods no longer fail when parsing out-of-range numeric strings. Instead, the `Double` parsing methods return `Double.PositiveInfinity` for values that exceed `Double.MaxValue`, and they return `Double.NegativeInfinity` for values that are less than `Double.MinValue`. Similarly, the `Single` parsing methods return `Single.PositiveInfinity` for values that exceed `Single.MaxValue`, and they return `Single.NegativeInfinity` for values that are less than `Single.MinValue`.

### Reason for change
This conforms to the expected behavior for floating-point types as defined in IEEE 754:2008. 

### Recommended action
This change can affect your code in either of two ways:
- Your code depends on the handler for the `OverflowException` to execute when an overflow occurs. In this case, you should remove the `catch` statement and place any necessary code in an `If` statement that tests whether `Double.IsInfinity` or `Single.IsInfinity` is `true`.
- Your code assumes that floating-point values are not Infinity. In this case, you should add the necessary code to check for floating-point values of PositiveInfinity and NegativeInfinity. 

### Category
- CoreFx

### Affected APIs
- [System.Double.Parse](https://docs.microsoft.com/dotnet/api/system.double.parse)
- [System.Double.TryParse](https://docs.microsoft.com/dotnet/api/system.double.tryparse)
- [System.Single.Parse](https://docs.microsoft.com/dotnet/api/system.single.parse)
- [System.Single.TryParse](https://docs.microsoft.com/dotnet/api/system.single.tryparse)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
//cc @tannergooding

**Comment by tannergooding** [comment]
Should it be documented that this was done for better IEEE 754:2008 compliance (which is the spec that defines the correct behavior for these operations)?

Does it need to be explicitly called out that it is not a value that is greater than `double.MaxValue` or less than `double.MinValue`, but rather a value that when rounded according to the IEEE rounding rules is closer to `double.Positive/NegativeInfinity`? More precisely, a value that is greater than `double.MaxValue + (double.MaxValue - Math.BitDecrement(double.MaxValue))` (where such a value actually representable) will round to `PostiveInfinity`. Values less than this, but still greater than `double.MaxValue` will round to `double.MaxValue` (Full Framework exhibits similar behavior for when deciding to `overflow`).

**Comment by tannergooding** [comment]
Otherwise, LGTM

**Comment by rpetrusha** [comment]
For the purpose of the breaking change, I don't think we need to be more precise about when parsing returns a value other than Infinity, @tannergooding. I will revise the PR that modifies the API documentation to note it, however.
