### ISSUE TITLE
preview?

### ISSUE THREAD

**Issue by khanhankkhan** [dotnet/docs#14718]
are there different TargetFramework's for the preview versions of each core #?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#feedback)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
@khanhankkhan 

No, the TFMs only change with new release numbers, not previews. That way, your project files don't need to be updated whenever a new preview comes out.

I'll close this as answered.
