### ISSUE TITLE
Incorrect url in an example

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#14714]
@Kezzya commented on [Thu Sep 26 2019](https://github.com/dotnet/docs.ru-ru/issues/225)

myClient.OpenRead("http://www.contoso.com/index.htm"); 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2cf9d0b8-7f12-9cda-abe9-35488f15296d
* Version Independent ID: 12edf729-7210-2644-6315-7f24a9ca1cc4
* Content: [Практическое руководство. Запрос веб-страницы и получение результатов в виде потока](https://docs.microsoft.com/ru-ru/dotnet/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream)
* Content Source: [docs/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/network-programming/how-to-request-a-web-page-and-retrieve-the-results-as-a-stream.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

---

@srvbpigh commented on [Thu Sep 26 2019](https://github.com/dotnet/docs.ru-ru/issues/225#issuecomment-535526524)

Hello, @Kezzya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
the user reports an error in the code.
best

**Comment by Youssef1313** [comment]
https://github.com/dotnet/docs/issues/12742 was already open for that. This broken URL is used in many places.
