### ISSUE TITLE
Please Elaborate gRPC Usage Patterns

### ISSUE THREAD

**Issue by kkadir** [dotnet/docs#14720]
From Figure 4-22, it is clear that front-end traffic is over REST and the back-end traffic is over gRPC. But it is not clear how this internal microservice-to-microservice or aggregator-to-microservice traffic happens. It would be wonderful if some concrete scenarios are covered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc86015f-c6c7-5fdc-ae0f-c69353afcb34
* Version Independent ID: 491d7006-ae8d-fb74-8b29-7e4b5031fcae
* Content: [REST and gRPC](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/rest-grpc#feedback)
* Content Source: [docs/architecture/cloud-native/rest-grpc.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/rest-grpc.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @kkadir. @robvet can you look at this feedback for the cloud native book?

**Comment by robvet** [comment]
Hello @kkadir, great observation. We are about to release an update to the gRPC material that provides more detail in this area.

**Comment by nishanil** [comment]
PR for gRPC is merged. Closing this issue now.
