### ISSUE TITLE
Misleading documentation for dotnet test

### ISSUE THREAD

**Issue by radiy** [dotnet/docs#14739]
I was looking for a way to run tests with net core on x86 and found link to .runsettings file [1], it says that I can use `<TargetPlatform>x86</TargetPlatform>` option which is wrong, on .net core it does nothing. You should just download .net core x86 and run tests from it.

[1] https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello, thank you for bringing this issue to our attention. In researching this issue I found microsoft/vstest#1128 which seems to confirm your issue. We should update this in the docs.
