### ISSUE TITLE
Obsolete method

### ISSUE THREAD

**Issue by mdraphelkabir** [dotnet/docs#14745]
Dns.Resolve is an obsolete method now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5814302a-7cde-f425-1060-ab0d71d4b8a7
* Version Independent ID: bfb8e3ba-eb8c-60d0-7f24-d0fda5f01691
* Content: [Listening with Sockets](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/listening-with-sockets#feedback)
* Content Source: [docs/framework/network-programming/listening-with-sockets.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/listening-with-sockets.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @mdraphelkabir. You're right. I've added this to our backlog for next time we revisit this article and to our community contribution project. We'll gladly accept PRs to update the code.
