### ISSUE TITLE
Underscores in test names

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#14747]
Code analysis rule [CA1707](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1707-identifiers-should-not-contain-underscores?view=vs-2019#feedback) flags method names that contain underscores. Yet this article shows an example with underscores in the name. Can we update the example to remove the underscores? This was originally noted in [this issue](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3971).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#feedback)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by jpreese** [comment]
My opinion would be that they do not need to change. I view Code Analysis rules as guidelines, and can be configured to however each team wants to leverage them.

I feel the current approach to naming is a good one, and there are a lot of .NET repos that leverage underscores in their test naming schemes.

If the majority feels otherwise, I can make the change

**Comment by Thraka** [comment]
I'm not sure this is a valid issue. Unit tests aren't meant to be public consumable code, hence they don't need to conform to the .NET Standard Naming Conventions.

**Comment by gewarren** [comment]
Here's a link to the .NET Standard naming conventions - https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#word-choice.

**Comment by gewarren** [comment]
@mavasani Do you want to weigh in on this one?

**Comment by mavasani** [comment]
CA1707 is meant only for production code, so should be explicitly turned off for test projects using https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#rule-severity

**Comment by Thraka** [comment]
For reference, the naming conversions is introduced with:

>Following a consistent set of naming conventions in the development of a framework can be a major contribution to the framework’s usability. It allows the framework to be used by many developers on widely separated projects. Beyond consistency of form, names of framework elements must be easily understood and must convey the function of each element.

(I added **my emphasis**) I think this description easily identifies unit tests as falling outside this scope.

**Comment by Youssef1313** [comment]
The `_` in unit test methods naming, in my opinion, seems like a convention specific to unit tests and I agree with @Thraka that it's outside of the scope of the general naming conventions.

Even the corefx repo uses it. [Example](https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/tests/ClaimsIdentityTests.cs)

**Comment by gewarren** [comment]
Thanks all for the clarification. Closing this issue and will ask OP to suppress the warning for test projects.
