### ISSUE TITLE
ResourceManagerWithCultureStringLocalizer class and WithCulture interface member marked Obsolete and will be removed

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/docs#14753]
## ResourceManagerWithCultureStringLocalizer class and WithCulture interface member marked Obsolete and will be removed

The [ResourceManagerWithCultureStringLocalizer](https://github.com/aspnet/Localization/blob/43b974482c7b703c92085c6f68b3b23d8fe32720/src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs#L18) class and [WithCulture](https://github.com/aspnet/Localization/blob/master/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L154-L170) interface member are often sources of confusion for users of Localization, especially if they want to create their own `IStringLocalizer` implementation. These items give the user the impression that we expect an `IStringLocalizer` instance to be "per-language, per-resource", when actually they should only be "per-resource", with the language searched for determined by the `CultureInfo.CurrentUICulture` at execution time. To remove this source of confusion and to avoid APIs which we don't want users to use we will be obsoleting these in 3.0.0-preview3, and they will be removed in a future release (4.0 or above). 

For context, see [here](https://github.com/aspnet/AspNetCore/issues/3324).

See aspnet/AspNetCore#7756 for discussion.

### Version introduced

3.0

### Old behavior

Methods were not `Obsolete`.

### New behavior

Methods are marked `Obsolete`.

### Reason for change

API represented a use case which is not recommended, and leads to confusion about the design of Localization.

### Recommended action

If you are using this we recommend that you use ResourceManagerStringLocalizer instead, and let the culture be set by the CurrentCulture. If that is not an option You may create a copy of [ResourceManagerWithCultureStringLocalizer](https://github.com/aspnet/Localization/blob/43b974482c7b703c92085c6f68b3b23d8fe32720/src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs#L18) in your own repo and use that.

### Category

- ASP.NET Core

### Affected APIs

- [ResourceManagerWithCultureStringLocalizer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.resourcemanagerwithculturestringlocalizer?view=aspnetcore-3.0)
- [ResourceManagerStringLocalizer.WithCulture](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.resourcemanagerstringlocalizer.withculture?view=aspnetcore-3.0#Microsoft_Extensions_Localization_ResourceManagerStringLocalizer_WithCulture_System_Globalization_CultureInfo_)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by joshfriend** [comment]
After upgrading to .net core 3.0 `IStringLocalizer.WithCulture` no longer works at all. I always get english strings returned now.

I've tried using `CultureInfo.CurrentUICulture` as suggested, but this doesn't work either.

**Comment by joshfriend** [comment]
Oh, it's because SharedResource stuff is broken since 3.0 https://github.com/dotnet/sdk/issues/4033
