### ISSUE TITLE
Example for compiler error BC32051 does not generate BC32051

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#14765]
## Example for compiler error BC32051 does not generate BC32051

The example for [BC32051](https://docs.microsoft.com/dotnet/visual-basic/misc/bc32051) generates BC36645 rather than BC32051.

The source code is:

```
Public Sub DoSomething(Of T)(arg1 As T(), arg2 As T)
End Sub

Public Sub Main()
    DoSomething(6, 42)
End Sub
```
The compiler output is:

> c:\Visual Studio Projects\bc32051\bc32051ex.vb(7) : error BC36645: Data type(s) of the type parameter(s) in method 'Public Sub DoSomething(Of T)(arg1 As T(), arg2 As T)' cannot be inferred from these arguments. Specifying the data type(s) explicitly might correct this error.
>
>   DoSomething(6, 42)
>   ~~~~~~~~~~~

**Comment by Youssef1313** [comment]
The error `32051` doesn't even exist in Roslyn repo. <https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Errors/Errors.vb>
