### ISSUE TITLE
Do I need to declare "disposed" field in each derived class ?

### ISSUE THREAD

**Issue by GreatFireWall** [dotnet/docs#14774]
Do I need to declare `bool disposed` field in each derived class when I implement the dispose pattern for a derived class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
That's a good question @GreatFireWall 

The answer is "it depends."  What you need to do in any derived class is to make sure that `Dispose` can be called multiple times without error. Whether you track that with a flag (as in these examples), or set internal fields to `null` is is entirely your design decision.

I'll close this as by-design.
