### ISSUE TITLE
Information under compilation of interpolated strings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#14777]
This article says:

&gt; If an interpolated string has the type string, it's typically transformed into a String.Format method call.

I'm wondering, when can `an interpolated string` doesn't have the type `string` ?
If an interpolated string is always having the type string, I think the previous statement should be changed to just:

&gt; An interpolated string is typically transformed into a String.Format method call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#code-try-4)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@Youssef1313 the section earlier in the article describes possible types of an interpolated strings:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#implicit-conversions-and-how-to-specify-iformatprovider-implementation

Also, the second paragraph from the quoted section:
> If an interpolated string has the type `IFormattable` or `FormattableString`, the compiler generates a call to the `FormattableStringFactory.Create` method.

**Comment by Youssef1313** [comment]
> 
> 
> @Youssef1313 the section earlier in the article describes possible types of an interpolated strings:
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#implicit-conversions-and-how-to-specify-iformatprovider-implementation
> 
> Also, the second paragraph from the quoted section:
> 
> > If an interpolated string has the type `IFormattable` or `FormattableString`, the compiler generates a call to the `FormattableStringFactory.Create` method.

Thanks, @pkulikov!
I was just going to close it now after I read the second paragraph :)
