### ISSUE TITLE
'Console' does not contain a definition for 'OpenStandardInput' (CS0117)

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs#14787]
Accessors
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#accessors

`
using System.IO;

public class Console
{
    private static TextReader reader;
    private static TextWriter writer;
    private static TextWriter error;

    public static TextReader In {
        get {
            if (reader == null) {
                reader = new StreamReader(Console.OpenStandardInput());
            }
            return reader;
        }
    }

    public static TextWriter Out {
        get {
            if (writer == null) {
                writer = new StreamWriter(Console.OpenStandardOutput());
            }
            return writer;
        }
    }

    public static TextWriter Error {
        get {
            if (error == null) {
                error = new StreamWriter(Console.OpenStandardError());
            }
            return error;
        }
    }
}
`

<img width="912" alt="CS0117-ERROR" src="https://user-images.githubusercontent.com/51827261/65825122-9fccef80-e2a5-11e9-8ff3-46c1a7dcdd66.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94b01ab-fe87-23fc-44b6-da9f3f627bd5
* Version Independent ID: a86008b1-2fdd-bbb9-3bbf-8fc8c51c1b71
* Content: [Classes - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#extension-methods)
* Content Source: [spec/classes.md](https://github.com/dotnet/csharplang/blob/master/spec/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by kinglionsz** [comment]
### If we change the class name to MyConsole and using System. run  the code will threw exception:

'((System.IO.ConsoleStream)((System.IO.StreamWriter)sw).BaseStream).Length' threw an exception of type 'System.NotSupportedException'
'((System.IO.ConsoleStream)((System.IO.StreamWriter)sw).BaseStream).Position' threw an exception of type 'System.NotSupportedException'
'((System.IO.StreamWriter)sw).BaseStream.ReadTimeout' threw an exception of type 'System.InvalidOperationException'
'((System.IO.StreamWriter)sw).BaseStream.WriteTimeout' threw an exception of type 'System.InvalidOperationException' 

### code is the following:

```
using System;
using System.IO;

public class MyConsole
//public class Console
{
    private static TextReader reader;
    private static TextWriter writer;
    private static TextWriter error;
    public static TextReader In
    {
        get
        {
            if (reader == null)
            {
                reader = new StreamReader(Console.OpenStandardInput());
            }
            return reader;
        }
    }
    public static TextWriter Out
    {
        get
        {
            if (writer == null)
            {
                writer = new StreamWriter(Console.OpenStandardOutput());
            }
            return writer;
        }
    }

    public static TextWriter Error
    {
        get
        {
            if (error == null)
            {
                error = new StreamWriter(Console.OpenStandardError());
            }
            return error;
        }
    }
}
public class Test
{
    
    public static void Main()
    {

        Console.Out.WriteLine("Hello,world.");      // ok

        MyConsole.Out.WriteLine("Hello,World!");    // nothing

    }
}

```

**Comment by BillWagner** [comment]
Thanks for raising this issue @kinglionsz 

Many of the samples in the C# Language Specification are meant to show one possible implementation to demonstrate how a language feature might be used. As such, they aren't meant to be run "as is" with the current .NET environment. Instead, these are meant to show how language features could be used to express a design.

The spec is not the best learning resource for C#. Instead, it's meant to be the definitive reference of the rules for what the language does, and why features were added to the language.

Our other resources would be more effective for finding example projects for C# programs.

I'll close this as by-design.

**Comment by kinglionsz** [comment]
> Thanks for raising this issue @kinglionsz
> 
> Many of the samples in the C# Language Specification are meant to show one possible implementation to demonstrate how a language feature might be used. As such, they aren't meant to be run "as is" with the current .NET environment. Instead, these are meant to show how language features could be used to express a design.
> 
> The spec is not the best learning resource for C#. Instead, it's meant to be the definitive reference of the rules for what the language does, and why features were added to the language.
> 
> Our other resources would be more effective for finding example projects for C# programs.
> 
> I'll close this as by-design.

Thank you very much! Thank you for your time.@BillWagner
