### ISSUE TITLE
Add docs on when null compilation might be returned from GetCompilationAsync

### ISSUE THREAD

**Issue by ashmind** [dotnet/docs#14784]
After upgrading to latest version of Roslyn, I can see that actual return time is `Task<Compilation?>`.
It uses nullable reference type to specify that compilation might be `null`.

However, looking at documentation, I can't see in what scenario this method returns `null` compilation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24aeac21-c836-3a56-3de5-69765aa53767
* Version Independent ID: d4a84dda-8e33-930c-58df-05766d11056e
* Content: [Project.GetCompilationAsync(CancellationToken) Method (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project.getcompilationasync?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Project.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Project.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @ashmind I've added it to our backlog to update.
