### ISSUE TITLE
Same description of two modes

### ISSUE THREAD

**Issue by sungam3r** [dotnet/docs#14781]
warnings: The nullable annotation context is disabled. The nullable warning context is enabled.

    Variables of a reference type are oblivious. All nullability warnings are enabled.

annotations: The nullable annotation context is enabled. The nullable warning context is disabled.

    Variables of a reference type are oblivious. All nullability warnings are enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @sungam3r 

This was fixed in #14750

It was merged yesterday, and should be live later today.
