### ISSUE TITLE
Default language version for .NET Standard 2.1

### ISSUE THREAD

**Issue by sveinungf** [dotnet/docs#14797]
Shouldn't the default language version be C# 8.0 for .NET Standard 2.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#feedback)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Checking with @cartermp to make sure we have the correct final design decision here.

**Comment by cartermp** [comment]
Yes, this should now be .NET Standard 2.1. For a time that was not true.
