### ISSUE TITLE
Review topics that use Visual Studio 2017 RC

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1480]
Some screenshots and instructions might have changed with the RC3 release.

**Comment by GuardRex** [comment]
@GuardRex: `csharp/getting-started/` but not `csharp/getting-started/with-visual-studio-2017`

**Comment by GuardRex** [comment]
@mairaw I'm ready to engage on this one at 12 noon PST. Is the renaming work on [VS2017 RTM initial update (#1663)](https://github.com/dotnet/docs/pull/1663/) done, or should I hold off this for a bit and work on [Fixup dotnet command line syntax (#1656)](https://github.com/dotnet/docs/issues/1656)?

**Comment by mairaw** [comment]
I've only renamed the topic I was touching and the images that it was using. You can rename the others on yours or I can rename all in mine and you make the other updates. Please let me know how you prefer @GuardRex. Thanks!

**Comment by GuardRex** [comment]
@mariraw *Deal!* 🤝 ... I'll take care of the rest of the VS2017 updates under `csharp/getting-started/` following your lead from #1663.
