### ISSUE TITLE
No mention of the new access modifiers in interfaces in C 8.0

### ISSUE THREAD

**Issue by tarikguney** [dotnet/docs#14803]
The 8.0 proposal is talking about the `private` and `internal` modifiers in  interfaces in 8.0 but no mention of them in what's new page. This is a big change, which I believe should have been mentioned in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @tarikguney 

Related: #12489 #12490 

I'll add this to the current sprint, as we'll add it while working on those issues.

**Comment by mattleibow** [comment]
I see I can also do `protected` and `virtual`...
