### ISSUE TITLE
Please check this example

### ISSUE THREAD

**Issue by mcastse** [dotnet/docs#14819]
Even when the several obvious errors are corrected it doesn't work at all.
(e.g. there is no SentimentRazorML.Model.DataModels just SentimentRazorML.Model,
services.AddPredictionEnginePool&lt;ModelInput, ModelOutput&gt;() needs a semicolon,
public IndexModel(PredictionEnginePool&lt;ModelInput, ModelOutput&gt; predictionEnginePool)
{
    _predictionEnginePool = predictionEnginePool;
} doesn't seem to want to coexist with the existing constructor referencing logging.

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cdb113e-14a4-7e96-2998-9bc42ddf9d7d
* Version Independent ID: 11857021-b820-ac38-307c-33f3f4a5065f
* Content: [Tutorial: Analyze sentiment - binary classification - ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by Youssef1313** [comment]
This line you referred to isn't really just missing a semi-colon.
It's referenced from `machinelearning-samples` by line number, and it seems like the file in `machinelearning-samples` was updated but the referencing in docs didn't change. That's what caused the issue.

![image](https://user-images.githubusercontent.com/31348972/65890799-ca04d700-e3a3-11e9-93f5-9bcc2f76cf4a.png)

I think it should be both 42 and 43.

@luisquintanilla , Can you confirm this ?

@rpetrusha, Can you please provide some more information about the *access-by-line.txt* file ? Will adding it in the `machinelearning-samples` repo solve such problems ?

**Comment by luisquintanilla** [comment]
@mcastse Sorry you're having trouble. Model Builder was recently updated and we're in the process of updating our docs to reflect those changes. 

@Youssef1313 Yes. The line references need to be updated. In the process of doing that.

**Comment by Youssef1313** [comment]
> 
> 
> @mcastse Sorry you're having trouble. Model Builder was recently updated and we're in the process of updating our docs to reflect those changes.
> 
> @Youssef1313 Yes. The line references need to be updated. In the process of doing that.

I've opened a PR for updating it already :)

**Comment by mcastse** [comment]
Thanks, now it works!
However, some responses are always surprising 😊, e.g. to Model Builder is neutral!

**Comment by luisquintanilla** [comment]
Great to hear it's now working for you @mcastse. If you'd like, you can try a different dataset for better results. 

https://github.com/dotnet/machinelearning-samples/tree/master/samples/modelbuilder/BinaryClassification_Sentiment_Razor#try-a-different-dataset

The updates to the tutorial will be reflected later today or tomorrow the latest. Thanks again for raising the issue.

**Comment by mcastse** [comment]
You might also like to check:

If you need to reference the Model Builder generated projects at a later time inside of another solution, you can find them inside the C:\Users\%USERNAME%\AppData\Local\Temp\MLVSTools directory.

I couldn’t find anything matching this, though, annoyingly, building the project has used rather a lot of valuable SSD boot disk space and I can’t tell exactly where the more than 1GB has gone.
