### ISSUE TITLE
Breaking change in SignInManager constructor (new parameter)

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/docs#14828]
## Breaking change in SignInManager constructor (new parameter)

As part of adding support for new email/confirmation flows in Identity(https://github.com/aspnet/AspNetCore/issues/8356), we added a new `IUserConfirmation<TUser>` argument to the constructor of `SignInManager`

### Version introduced

3.0

### Old behavior

`SignInManager` didn't require `IUserConfirmation` when constructing.

### New behavior

`SignInManager` requires an `IUserConfirmation`.

### Reason for change

Adding support for new email/confirmation flows

### Recommended action

If manually constructing a `SignInManager` pass in an implementation of `IUserConfirmation` or grab one from DI to pass in.

### Category

ASP.NET Core

### Affected APIs

[SignInManager.ctor](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1?view=aspnetcore-2.2)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by kvbutler** [comment]
Just wanted to drop comment in here for others, as this was a little confusing for me.

The Microsoft.NET.Sdk.Web SDK has AspNetCore.Identity package included now, but Nuget only has the package up to version 2.2. Visual Studio tries to automatically install that version (2.2) from Nuget if your library project targets the regular SDK (Microsoft.NET.Sdk). This has incompatibilities if you are then referencing that library project from for example a WebApi project.

The solution is to remove all Nuget dependencies in your library projects, open up the .csproj file, and change the SDK

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <!-- other configs -->
</Project>
```
