### ISSUE TITLE
Documentation provided in the "More information" link of the "One-Way Upgrade" dialog is inaccurate in the context of .NET Core and ASP.NET Core projects

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/docs#1482]
Copied over from https://github.com/dotnet/roslyn-project-system/issues/967 

Fix here is to add a pj->csproj migration related blurb to https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects and cross-link it to more info in .NET Core docs.

Suggest reviewers @morrisjoe

**Comment by mairaw** [comment]
@morrisjoe by reading the issue https://github.com/dotnet/roslyn-project-system/issues/967, it seems you want to actually update the docs for VS, not .NET, correct? If so, the appropriate place to file this would be: https://github.com/Microsoft/visualstudio-docs 

/cc @ghogen

**Comment by morrisjoe** [comment]
I did. See https://github.com/Microsoft/visualstudio-docs/issues/30 
But please note that there are 2 parts...Part1, which is a blurb the vsdocs will need to add to their content. Part2, which is a topic in .NET Core focused on IDE migration which vsdocs will link to from their content. 
So until Part2 is done, please don't close this issue in dotnetdocs

**Comment by mairaw** [comment]
Ah, gotcha!

**Comment by mairaw** [comment]
@morrisjoe can we close this one now?

**Comment by morrisjoe** [comment]
@balachir is the one who raised this issue and it's best if he close this.

**Comment by mairaw** [comment]
@balachir I believe this work item is done. https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects has been updated and has a link to our topic about migration: https://docs.microsoft.com/en-us/dotnet/articles/core/migration/#visual-studio-2017
