### ISSUE TITLE
Implement CI builds for PRs

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#14822]
This is step 2. It would optimize PR builds so that only those projects / solutions that are effected by a change would be built.

**Comment by Youssef1313** [comment]
@BillWagner, just a small note:

https://github.com/dotnet/samples/blob/master/snippets/csharp/tutorials/attributes/Program.cs#L134

Things like that, which are **intended compile errors**, will cause the CI build to fail.

```csharp
    // <AttributeGotcha2>
    [Gotcha(new Foo(), "test")] // does not compile
    public class AttributeFail
    {

    }
    // </AttributeGotcha2>
```

A solution will be needed for that.

**Comment by BillWagner** [comment]
@Youssef1313 We have thought about it, but haven't decided on a plan yet.  We're think through two approaches:

1. Mark some samples where "a successful CI build" has the expected errors.
1. Move non-compiling samples into inline code, where it isn't built by the CI system.

The advantage of the second is that it's easy. The advantage of the first is that if any new language updates change the expected error or add syntax, the CI system would find those for us.

/cc @Thraka

**Comment by Thraka** [comment]
I think #2 is the better way to go here.

**Comment by Youssef1313** [comment]
Well, If I found samples that has an intended compile-time error, should I open a PR that adds it directly in the md file and deletes it from samples repo ?
Or wait for this until the CI is done ?

**Comment by BillWagner** [comment]
@Youssef1313 We should be deciding which option within a few days. I'll update this comment once we've done that.

**Comment by BillWagner** [comment]
Update from meeting with @thraka on 5/4:

- The full build should issue a warning on code that's been found in folders without a *.*proj file.
- PR builds should issue an error on code (in the PR) that is in a folder without a *.*proj file. That forces each PR to ensure that code is in a project that builds.
