### ISSUE TITLE
Identify and remove samples that aren't used in any documentation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#14825]
We think there are many.

**Comment by Youssef1313** [comment]
Can you have a look at https://github.com/dotnet/samples/issues/1434, @BillWagner ?

**Comment by mairaw** [comment]
One comment I'd make regarding this. Please make a backup branch of the samples repo before running the clean-up. I still run into issues with samples dropout from previous migrations, so it would be good to have an easy way to recover samples, when needed.

**Comment by rpetrusha** [comment]
There is a utility that detects directories in the **dotnet/samples** repo whose files are not used in either the **dotnet/docs** or **dotnet/dotnet-api-docs** repos. It includes:
- The [C# source code](https://gist.github.com/rpetrusha/6a4479f4e02e72726357140b63fb1105).
- Information on the [configuration file](https://gist.github.com/rpetrusha/263039abeb5eedd148ba75576b00a1f4) used to customize operation of the utility. It can be compiled from the command line (e.g., `csc  unused-code.cs`.
- [Documentation](https://gist.github.com/rpetrusha/073a6ff367bc280fb9142fb41d8aff09) for using the utility.
- [Output](https://gist.github.com/rpetrusha/1485cccf2fa72b1bbac40d24a9c594e5) from the utility on 2019/10/04.

**Comment by Youssef1313** [comment]
@mairaw, Is there currently any on-going work on this ?

**Comment by Youssef1313** [comment]
A note when someone is working on this.
The output of the utility includes: `samples/snippets/fsharp/getting-started` which is used [here](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-with-visual-studio-for-mac.md). I couldn't review the code to know what caused it to output such a false positive. but this should be checked because there might be other false positives.

**Comment by BillWagner** [comment]
Also moving to the January milestone, based on the current pace of progress

/cc @Thraka .

**Comment by BillWagner** [comment]
replaced as part of #17297
