### ISSUE TITLE
Sample NamedPipeClient code results in Exception

### ISSUE THREAD

**Issue by AndrasHorinka** [dotnet/docs#14820]
**Issue description**

&lt;Unhandled Exception:Unhandled Exception: Unhandled Exception: Unhandled Exception:  System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.&gt;

**Target framework**: .NET Core 2.2.401

<details>
<strong>.NET Core SDK (reflecting any global.json):</strong>
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86675e7-4bfb-707d-fe36-c02da2023342
* Version Independent ID: ee821843-1cad-0455-f278-1194b88dd0b0
* Content: [How to: Use Named Pipes for Network Interprocess Communication](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-named-pipes-for-network-interprocess-communication)
* Content Source: [docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your comment @AndrasHorinka. Can you let us know where you're seeing this sample?

**Comment by AndrasHorinka** [comment]
@mairaw 
started: [here](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-named-pipes-for-network-interprocess-communication?view=netframework-4.8)

Referred to 
[here - and changed from framework to core2.2](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeclientstream?view=netcore-2.2)


Running it on .NET Framework 4.7 results in an System.OverflowException - because the file referred (c:\\textfile.txt) does not exists. Probably would worth to do a check if the file exists and if not create it.

Altering the file reference seems to fix it.

BR,

**Comment by Thraka** [comment]
I believe this was fixed and the article has been updated.
