### ISSUE TITLE
Wrong switch for R2R images?

### ISSUE THREAD

**Issue by ErikApption** [dotnet/docs#14833]
I'm not able to generate a R2R file with --self-contained true but /p:PublishSingleFile=true does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Given that you're providing a runtime identifier to that command, in theory, you wouldn't have to pass `--self-contained` since the default is true.

I'll fix that.

**Comment by ErikApption** [comment]
So after multiple tests,  --self-contained did not make any difference but /p:PublishSingleFile=true was necessary to make the R2R work.

**Comment by Thraka** [comment]
Is this a misunderstanding about what R2R is? It's not a single exe. The `/p:PublishSingleFile` switch is what generates a single exe, not --self-contained.

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables

**Comment by ErikApption** [comment]
Closed - got confused between the two features which we are using at the same time.

**Comment by mairaw** [comment]
Glad it was resolved. I'm still merging my changes since they improve the text a bit regarding self-contained flag.
