### ISSUE TITLE
Document default compiler defines 

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/docs#1483]
Moved from https://github.com/dotnet/sdk/issues/694 

Suggest reviewers @morrisjoe @ blackdwarf

**Comment by cartermp** [comment]
Note that there is a table [here](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/libraries.md#how-to-multitarget) which could likely be used.

**Comment by mairaw** [comment]
@morrisjoe can we sync to understand what exactly needs to be done here and where is the best place to put this information?

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
