### ISSUE TITLE
Needs update for 3.0

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#14849]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#synopsis
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#dotnet-commands
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#environment-variables

Sections specifically documents commands per version. .NET Core 2.2 and 3.0 are missing.  

Consider removing 2.0/1.x sections as these are out of support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#environment-variables)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @sdmaclea. Updating the CLI reference is in progress and tracked by issue #9893.
