### ISSUE TITLE
Install script is not creating registry values

### ISSUE THREAD

**Issue by Symbai** [dotnet/docs#14842]
The install script for Windows is not creating registry values like the Installer on dot.net does. This is a problem because I'm programmatically using these registry keys to determine if .NET Core is installed and use the script if not but since the script is not creating the registry keys its repeating itself.

Could it be the installing script just downloads the zipped binaries and copy them to a folder instead of downloading the installer and installs it? In this case the docs need to tell that and there should be an option to download the installers instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @Symbai. @johnbeisner can you please comment on this issue about the install scripts?

**Comment by johnbeisner** [comment]
@Symbai 
The install scripts do not create a registry key values. You are correct, the install scripts just downloads the zipped binaries and copies them to a folder. If you need the registry key values, use the .NET installers.

**Comment by mairaw** [comment]
Thanks for confirming @johnbeisner. Do you know what registry keys are we talking about here? I think it would be worth adding a note to the docs about this.

**Comment by Symbai** [comment]
Maybe it shouldn't be called install script then but download script. It is misleading to have a install script near installers where the script only downloads a zip and copies files where the installers do different things.

Sadly I can't use the installer as the "install" script is the only way to programatically "install" .NET Core because the Installers are only available with hardcoded links and might be invalid in the future.

@mairaw: The installer creates many keys at `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\dotnet\...` which gives information about the installed versions. I'm not sure if it creates more.

But it's not only the registry keys are missing. The whole "**dotnet**" command line API isn't available as well which should also be documented as this is often recommended as "fallback" detection method for retrieving the installed .NET Core versions.

So yeah, there is a huge difference between installers and script.

**Comment by redwyre** [comment]
These also don't have uninstall entries, and by default go to the user folder instead of program files which are both different to the installer. Mixing the two creates a kind of Frankenstein monster install.
