### ISSUE TITLE
Question regarding readonly

### ISSUE THREAD

**Issue by msauper** [dotnet/docs#14841]
I understand the error generated when Distance is not readonly.  I don't understand why you don't get new errors for X and Y not being readonly when you make Distance readonly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great question @msauper 

Making `Distance` a `readonly` method means that it cannot call a method or property accessor that isn't marked `readonly`. In the initial implementation, neither `X` nor `Y` had the modifier. Therefore, it must be added.

I'm adding this to our backlog to update the next time we visit this article. I've also added the "up for grabs" label for community contributors to address this, if anyone wants.

**Comment by Pyrobolser** [comment]
Maybe I am not understanding this properly, but I feel like the compiler is not doing what this sentence is saying:

> _The compiler doesn't assume `get` accessors do not modify state; you must declare readonly explicitly._

If you follow the example from the documentation and add **readonly** to `ToString()` and `Distance` you do not have an extra level of warning that asks you to specify that the `get` accessor is also **readonly**.  
You are however getting this warning if you implement the `get` accessor as an expression-bodied member instead of using an auto-implemented property.  

``` csharp
public struct Point
{
    private double _x;
    public double X
    {
        get => _x;         
        set => _x = value;
    }
    public double Y { get; set; }
    public readonly double Distance => Math.Sqrt(X * X + Y * Y);

    public readonly override string ToString() => $"({X}, {Y}) is {Distance} from the origin";
}
``` 

So it seems like the compiler is smart enough to understand that the auto-implemented property is not going to modify the state of the variable. Is that what is happening here?

**Comment by mssteele** [comment]
Hi, I've just submitted a PR for this. @Pyrobolser was correct, `X` and `Y` are auto-implemented properties and the readonly modifier is not required for these. See:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members

> Readonly can be applied to some auto-implemented properties, but it won't have a meaningful effect. The compiler will treat all auto-implemented getters as readonly whether or not the readonly keyword is present.

**Comment by msauper** [comment]
The problem is that both X and Y have public setters which would imply that they are not read only.

**Comment by mssteele** [comment]
Ah yes but readonly only applies to the getter part. Because it is an auto-property the compiler can be sure the getter isn't mutating anything.

From the same link as above:

> When readonly is applied to the property syntax, it means that all accessors are readonly.

**Comment by Pyrobolser** [comment]
@mssteele thank you for the documentation link and the confirmation 👍
