### ISSUE TITLE
Array size in visual basic examples.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#14856]
When declaring arrays in visual basic, we specify the `size - 1` not `size` as in C#.
It seems that there are many samples that **wrongly** specify `size` in visual basic.

An example PR that solves really small occurrences is dotnet/samples#1480

**Comment by mairaw** [comment]
Thanks for your feedback @Youssef1313. I'm adding this one to our backlog and our community contributor project. We'd love community contributions on this one!
