### ISSUE TITLE
What to do with the XML Documentation?

### ISSUE THREAD

**Issue by twocs** [dotnet/docs#14852]
This documentation is nice, and it's human readable. It allows us to create XML documentation from our code. But the XML documentation is not human readable. Thus, this documentation is missing the important next step:
How does the XML get used for actual documentation purposes (for humans)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71da79a-a782-7c7d-0091-e262c66b6fe4
* Version Independent ID: 1f662a67-3ade-26d7-c88a-aee7dd9f0320
* Content: [How to: Use the XML documentation features - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features#robust-programming)
* Content Source: [docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by twocs** [comment]
Actually I found that there's a sentence in the first page of this doc: "To create the final documentation based on the compiler-generated file, you can create a custom tool or use a tool such as DocFX or Sandcastle."
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/

It's easy to miss that so can there be something in the "See also"?

**Comment by BillWagner** [comment]
Thanks for creating this @twocs 

I submitted #14870 to address this issue.
