### ISSUE TITLE
Docs about <OutputType>

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#14859]
Some of the default values/behaviors are present only when `<OutputType>` is specified as `Exe`. For example, `dotnet build` doesn't produce a *.runtimeconfig.json* if `<OutputType>` is omitted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @NextTurn. @dsplaisted @livarcocc who would be a good person to talk to about the default behaviors for dotnet build? I wanna make sure the article is completely accurate, especially with the new changes introduced by 3.0.

**Comment by NextTurn** [comment]
From MSBuild targets

`<_IsExecutable Condition="'$(OutputType)' == 'Exe' or '$(OutputType)'=='WinExe'">true</_IsExecutable>`

`<HasRuntimeOutput>$(_IsExecutable)</HasRuntimeOutput>`

`<GenerateRuntimeConfigurationFiles Condition=" '$(GenerateRuntimeConfigurationFiles)' == '' and '$(TargetFrameworkIdentifier)' == '.NETCoreApp' and ('$(HasRuntimeOutput)' == 'true' or '$(EnableComHosting)' == 'true' or '$(EnableDynamicLoading)' == 'true') ">true</GenerateRuntimeConfigurationFiles>`
