### ISSUE TITLE
formatting-utility sample in wrong directory

### ISSUE THREAD

**Issue by Padanian** [dotnet/docs#14858]
Formatting-utility sample is in directory winforms instead of windowsforms

**Comment by mairaw** [comment]
@rpetrusha can you take a look at this?

**Comment by Padanian** [comment]
Issue is still present in latest commit.

**Comment by Youssef1313** [comment]
@BillWagner, Regarding this issue, can you look at this PR and my comment ? https://github.com/dotnet/samples/pull/1426#issuecomment-529100230
