### ISSUE TITLE
Declaring the variable inside the using is not needed

### ISSUE THREAD

**Issue by thomasfn** [dotnet/docs#14869]
For example, the following is valid:

```
using (new Font("Arial", 10.0f))
{
    // ...
}
```

In this case, the font is still disposed at the end of the scope as per the example, but the instance can't be accessed in code. This is not so useful for a font instance, but it's useful for objects whose functionality is entirely encapsulated in their lifecycle - for example, a lock on a mutex.

```
using (myMutex.LockRead())
{
    // mutex is locked during the block
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @thomasfn 

It is a good enhancement to this description.

I've added it to our backlog and we'll address this when we next update this article.

I've also added the "up for grabs" label for any community contributions.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by BillWagner** [comment]
@MetalDent I don't think anyone is working on it. Would you like to submit a PR?

**Comment by BillWagner** [comment]
@MetalDent  I would add an example like the one in this issue description. That helps explain why this is a useful feature.

**Comment by MetalDent** [comment]
@BillWagner in this also the links in [this](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md) are not found.

**Comment by BillWagner** [comment]
@MetalDent  Yes, these samples have the same dependencies as the other samples. The samples in this article are [here](https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_VBCSharp/csrefKeywordsNamespace/CS/) in the dotnet/samples repository.

**Comment by MetalDent** [comment]
@BillWagner according to the issue, don't you think we should change all the examples as they all are related to font?

**Comment by BillWagner** [comment]
@MetalDent I recommend keeping the current examples. I'd add a new example using the Mutex example from the issue description.

Most uses of a `using` declaration will assign the result to a variable.  Some cases (like the Mutex read) won't need the variable
