### ISSUE TITLE
Small issue with the IsValidEmail method

### ISSUE THREAD

**Issue by FrojdJocke** [dotnet/docs#14867]
[Enter feedback here]
Thanks for the IsValidEmail method. Helped me a lot!
There is a small issue though in the regex query, it allows the domain name to end with a hyphen (-). I modified that part of the regex as follows: 

([0-9a-z][-0-9a-z]*[0-9a-z]+|[0-9a-z]+\.)+

Thought you would appreciate the feedback.
Once again, thanks a million for the method!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@FrojdJocke Thanks for the kudos and the suggestion.

@rpetrusha Assigning to you since you love regex so much 😄

**Comment by Thraka** [comment]
Actually, @Youssef1313 are you interested in this one since you're working on another regex issue?

**Comment by Youssef1313** [comment]
@Thraka, I've tested the solution by @FrojdJocke and seems to be working. But not sure if there is a better way to do that. I also suspect that this part of regex is somehow not valid `?("")`. so I think @rpetrusha  is better to review this issue and the `?` that I'm suspecting it being invalid in this context.

regexr.com seems to agree too:

![image](https://user-images.githubusercontent.com/31348972/66119040-22241f00-e5d8-11e9-9bab-0ae97bcf1760.png)

**Comment by Thraka** [comment]
I think .NET's regex allows for some stuff that the online testers don't.

**Comment by mairaw** [comment]
@FrojdJocke can you give an example of an e-mail that you used that was considered valid?I just ran this code and tried a couple of e-mail addresses ending with a hyphen, and they were all considered invalid.

**Comment by Youssef1313** [comment]
> 
> 
> @FrojdJocke can you give an example of an e-mail that you used that was considered valid? I just ran this code and tried a couple of e-mail addresses ending with a hyphen, and they were all considered invalid.

@mairaw, Try `something@gmail-.com`

**Comment by FrojdJocke** [comment]
@mairaw I ran a test with the address ```test@mycompany-.com``` and that was considered to be valid.
