### ISSUE TITLE
JSON injection security vulnerability mittigation by signed json streams/ text files

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#14863]
**Feature Request**
I have noticed that some json streams/files are getting manipulated. in order to be able to identify manipulation at the moment we +self-sign+ the stream in a similar way that one signs a PowerShell script. Other developers that need to do this at the moment we have 3 choices: 

1. Pray that nobody manipulates files, injects or manipulates streams
2. Encrypt the json 
3. Calculate a hash and sign the stream/ file using a certificate and send the json and the checksum

There are 101 use-cases where SSL is good enough, however this is not always the case and not all json is used in SSL communication and JavaScript and DOM elements can easily be manipulated an the browser/postman. 

As .net now has a proprietary json parser one could use the same signature format in the json stream in much of the same way PowerShel is and one could have a exception if the checksum changed. One could provide a certificate that is used to sign the json either by adding it in the method or in the options.

I know that json does not allow comments however one could inject a special __property_GUID__ that contains the certificate generated checksum (how we do it)

`var json=System.Text.Json.Serialize(object, options, cerificate);`

I'm not aware that this would be a braking change other than that the "object from json" mappers are getting a property that makes no sense to keep.

**Comment by mairaw** [comment]
Thanks @PeterPann23. Can you take a look at this feedback @ahsonkhan? Should this be moved to the corefx repo?

**Comment by GrabYourPitchforks** [comment]
Hi @PeterPann23. JSON object signing is out of scope for the _System.Text.Json_ library. There are other libraries - such as JWT libraries - that have support for tamper-proofing JSON payloads. There are also existing and proposed standards for performing such signing. These standards often make the JSON text no longer readable by humans, as they generally prefer to avoid implementing complex text normalization routines.

If you're interested in learning more about these, the search terms "JWT", "JOSE", and "RFC 7515" should help get you started.
