### ISSUE TITLE
Broken Samples in Documentations

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/docs#14871]
Documentation broken here as Samples are not loaded:

https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/obtaining-a-dbproviderfactory.md

**Comment by mairaw** [comment]
@stevestein This is an incoming feedback for one of the ADO.NET topics. Please take a look!

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/obtaining-a-dbproviderfactory

**Comment by mairaw** [comment]
Oh now I'm wondering, @cheenamalhotra the source will look different than the rendered content. Are you saying that the published content has issues?

**Comment by Youssef1313** [comment]
@cheenamalhotra, Do you mean that you don't see the code in the markdown files in GitHub while it's seen in live docs ?
If so, it's not an issue at all. The code is referenced from another repository, the [Samples Repository](https://github.com/dotnet/samples). You can see the path clearly in the markdown, then go to the corresponding file in the samples repo.

**Comment by cheenamalhotra** [comment]
Yes rendering was my concern. I would imagine Sample content to be pulled in the markdown from dotnet/samples source, just like it happens on Microsoft Docs by setting root directory, wondering if there is a solution to do that here too?

It may need updating doc references to display content from GitHub repository dotnet/samples.

**Comment by cheenamalhotra** [comment]
Nvm, I was referring to rendering samples in github markdown view, but I just realized this is just dotnet/docs home. So its intended for https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/obtaining-a-dbproviderfactory only (which is fine).

Is there a way to link to docs.microsoft.com hosted URL from these github files, so one can render the view mode and see the samples loaded? It kind of confuses if it's official documentation (some repositories do that too) or just a source code of MS docs as in this case.

**Comment by Youssef1313** [comment]
Just replace `https://github.com/dotnet/docs/blob/master/docs/` with `https://docs.microsoft.com/dotnet/`.

**Comment by cheenamalhotra** [comment]
I'm fine with it since we work on publishing MS docs too, it just seems little off when redirected here from google search results instead of the official documentation :)

**Comment by mairaw** [comment]
Interesting. I asked Nat Friedman the other day about this as well because it causes SEO issues. I was going to start a thread with him and I'll include you and this issue as an example. My understanding is that master is indexed by default and I couldn't find a way to turn that off.

**Comment by cheenamalhotra** [comment]
One solution is to include examples inside docs with code blocks... without cs file reference, but I bet it will be huge work :)

**Comment by mairaw** [comment]
We definitely don't want to do that. We can't test code with a CI job like this, we can't reuse, etc.
