### ISSUE TITLE
Possible typo with inheritance flow

### ISSUE THREAD

**Issue by AzmL** [dotnet/docs#14895]
The page says: "you can assign an object of the IComparer(Of Person) type to an object of the IComparer(Of Employee) type without using any special conversion methods if Person inherits Employee."

I believe it should be "if Employee inherits Person". If not correct, then the example for covariant generic interfaces is confusing because String inherits Object, not the other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad707233-1d12-1e11-a1ac-b702b6d559c7
* Version Independent ID: 53e0d82b-0ead-5eb7-f409-6a4c1459240e
* Content: [In (Generic Modifier) (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/in-generic-modifier)
* Content Source: [docs/visual-basic/language-reference/modifiers/in-generic-modifier.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/in-generic-modifier.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Thank you for your feedback @AzmL. I've opened PR #14899 to fix this.
