### ISSUE TITLE
Running selective unit tests in VS using TestCaseFilter

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1489]
the dotnet test command links to https://aka.ms/vstest-filtering for more info on filtering support which is an old blog post (VS2012 timeframe) about using filters. We should have this information in our docs instead. Either as a new topic or as part of the dotnet test topic itself.

**Comment by GuardRex** [comment]
@mairaw Not an easy call ... It's an awful lot of content (long examples) to tack on to the command doc; and as a separate doc, where does it go? ... under `dotnet test` as a sub-doc?

What do you prefer?
