### ISSUE TITLE
What is a using statement?

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#14909]
I had this code:

			using (var controller = new GpioController())
			{
				controller.OpenPin(pin, PinMode.Output);
			}

And VS 16.3 suggested this instead:

			using var controller = new GpioController();
			controller.OpenPin(pin, PinMode.Output);

What does that mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @ygoe 

We do need to update this reference page for new syntax added in C# 8.  We do discuss this in the [what's new](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-8#using-declarations) article on C# 8. Until we get this article updated, you can learn more in that article.

I've added this to our backlog, and added the "up for grabs" label for any community contributes to create a PR for this change.

**Comment by BillWagner** [comment]
Fixed in #15201
