### ISSUE TITLE
Missing runtime ID for ARM 64 bit

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#14916]
I can install dotnet runtime 2.1 on Fedora ARM 64bit. What is the RID of that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello. The value you want is `fedora-arm64` and you can see a full list of RIDs in the source repo for Core 3.0: https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L309

However, it's not listed in the 2.1 branch: https://github.com/dotnet/corefx/blob/release/2.1/pkg/Microsoft.NETCore.Platforms/runtime.json#L642

So it may or may not work. You should upgrade to 3.0 😄
