### ISSUE TITLE
Build configuration for referenced projects?

### ISSUE THREAD

**Issue by waltdestler** [dotnet/docs#14919]
When I specify a build configuration using `-c|--configuration {Debug|Release}`, does it apply that same configuration to any referenced projects as well? (I assume yes, but the docs don't explicitly say so.) What happens if a referenced project doesn't have a build configuration by that name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
This value is passed into MSBuild which is then using that value to compile your project and also to compile any project references. If you're referencing the project directly, it would be carried over. If the referenced project **doesn't explicitly define** the build configuration supplied, it would use the fallback, which is `debug`.

If you're referencing a compiled dll, this wouldn't carry over and you get whatever was compiled into the existing dll.

I'm going to close this issue. Let me know if you need anything else. Thanks!

**Comment by waltdestler** [comment]
Thanks for the response! Is there any way to override this behavior and tell it to use a different build configuration for the referenced projects? (I asked [this question](https://stackoverflow.com/questions/58258842/how-to-specify-build-configuration-for-referenced-projects-when-using-dotnet-bu) on StackOverflow but haven't received a response.)

My current workaround is to build the whole solution, but that contains a couple dozen projects and takes far, far longer to build/publish the whole thing.

> If the referenced project doesn't explicitly define the build configuration supplied, it would use the fallback, which is debug.

This doesn't appear to be true. In my case, the referenced projects have Debug configurations that allow unsafe code, but when compiling my root project with a configuration that doesn't exist in those referenced projects, they generate unsafe code errors, so I'm 99% sure they're not using their Debug configurations.

**Comment by Thraka** [comment]
You would have to share more of your config to fully understand what you're experiencing.

@dsplaisted do you have any insights into using project references and msbuild configs?

**Comment by dsplaisted** [comment]
cc @rainersigwald and @nguerrera who are more familiar with this than I am

**Comment by rainersigwald** [comment]
`--configuration X` is a wrapper over specifying `-property:Configuration=X` to MSBuild directly, which sets a global property. Global properties are inherited by default. That's the behavior you're seeing with referenced projects not building in Debug.

There are two main ways to influence the configuration of referenced projects:
1. Build in the context of a solution using a _solution_ configuration that has mixed _project_ configurations.
2. Use `SetConfiguration="Configuration=ZZZ"` metadata on the `ProjectReference` items in the referencing project.

Both have drawbacks: 1 requires you to use a solution even when building individual projects, and 2 may require complicated logic to replicate the right set of fallbacks (for instance, you might want `Production` to map to `Release` but normal developer builds to have `Development` mapping to `Debug`).

**Comment by Thraka** [comment]
@rainersigwald Thank you for the info. I was also going to suggest that perhaps a build script would help here too. Keep the projects/solution simple and use a script to build individual projects with configs based on your scenario. That is another option.

@waltdestler I hope this answers your question. Please let us know if you need any more information. I'm going to close this.
