### ISSUE TITLE
URL has changed

### ISSUE THREAD

**Issue by spprtmechanic** [dotnet/docs#14911]
the URL for the text download is now http://www.gutenberg.org/cache/epub/16452/pg16452.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aeee012-d49e-e096-229c-44d38063b34f
* Version Independent ID: 86f4283b-fd68-22b5-c546-afe3c554d434
* Content: [Walkthrough: Creating a Dataflow Pipeline](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline#feedback)
* Content Source: [docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for writing this up @spprtmechanic and pointing to the updated location.

I've added this to our backlog, and added the "up for grabs" label is you or another community member wants to issue a PR to address this issue.

**Comment by mairaw** [comment]
For folks wanting to contribute, this is the location of the sample to edit the URL:
C# - https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Misc/tpldataflow_palindromes/cs/dataflowpalindromes.cs
VB - https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_palindromes/vb/dataflowpalindromes.vb
