### ISSUE TITLE
Duplication of C# and VB compiler messages and folders

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1491]
The C# compiler error messages are located in two different directories.

/docs/csharp/misc and /docs/csharp/language-reference/compiler-messages. 

They should all be in the 2nd directory, and we need to update the F1 help for Visual Studio to point to the correct location.

The same is true for VB:

/docs/visual-basic/misc

/docs/visual-basic/language-reference/error-messages

/cc @Pilchie

**Comment by Pilchie** [comment]
VS doesn't point to a directory - we just push the error message id, and the F1 help service does a lookup on the server.

**Comment by mairaw** [comment]
It would be interesting to talk with Bill Chiles and see if he knows why this was split. I see some that are in misc and not in compiler-messages and vice-versa. F1 help should just work since the F1 metadata is already present in the topics.

**Comment by rpetrusha** [comment]
When we move the files out of the misc directories, we can do a global redirect of all docs/<language>/misc URLs rather than add them one-by-one into the redirects file.

**Comment by Youssef1313** [comment]
One limitation I know that prevents to just easily move the files from one directory to another is that relative links may get broken. Are there other limitations to consider if I want to work on this issue ?

 @rpetrusha , @BillWagner, @mairaw

**Comment by BillWagner** [comment]
@Youssef1313 A quick search says there aren't a lot of relative links among these files.

The volume of files to move means the redirection fie will get a bit out of control, but by being careful we can manage it moving files in blocks of 10 - 20.

**Comment by IEvangelist** [comment]
Can we consolidate / categorize these messages into groups?

Problem statement:
- All the compiler message docs are low traffic
- They're not in the TOC
- Why are they in two different directories

De-prioritize

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
