### ISSUE TITLE
Is there some way to replace and use the capitalization of the input match

### ISSUE THREAD

**Issue by Caleb-D** [dotnet/docs#14924]
for example, one regex that matches and replaces all of these:
Pulse-&gt;Jump
pulse-&gt;jump
PULSE-&gt;JUMP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e4ab41-3d66-76f0-1ae8-a9818a199583
* Version Independent ID: b35b11b7-5c7f-0985-dd62-aecfd48d1490
* Content: [Substitutions in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions)
* Content Source: [docs/standard/base-types/substitutions-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/substitutions-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Youssef1313** [comment]
I don't think this can be achieved with regex **only**.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by miniksa** [comment]
I just arrived here attempting to do this exact thing. I want to specify something like $L1 to lowercase the capture from group 1. Some other utilities do this: https://www.regular-expressions.info/replacecase.html

Even if it's not possible/documented today, can you please file a feature request so the next Visual Studio might be able to do this?

**Comment by Youssef1313** [comment]
@miniksa, I don't think it's related to Visual Studio at all. It *could* be related to `dotnet/runtime`. Personally, I don't think this is possible, but you may open an issue in the `dotnet/runtime` repo and see what will be said.

**Comment by miniksa** [comment]
@Youssef1313, Hmmm, I was attemping to do this in the Visual Studio 2019 text editor Find/Replace window. Which I'm pretty sure is powered by whatever capabilities .NET has. So I'm sort of hoping Visual Studio, with its weight, could drive .NET upstream to introduce this feature such that everyone could make use of it. I thought I was on a Visual Studio help page, though, to be honest. Not one for .NET generally. But it's all sort of the same world. Sort of.

**Comment by Youssef1313** [comment]
Oh, I thought you were trying to do it by code. not by using the Find/Replace window. then it's not related by dotnet/runtime. but still, I don't think it's possible. Regex is not a Microsoft thing. so still, if there is no way to do that in regex, this can't be changed. If there is a way that I'm not aware of to do that in Regex, then it's a different story.

**Comment by miniksa** [comment]
I only bring up the possibility because:
1. I wanted to do it
2. Someone else has this problem
3. Just Great Software has a solution to this for their Regex implementation that I linked above. 

It seems like a decent idea that's just missing. I'd like to see .NET and/or VS at least consider it.

**Comment by tdykstra** [comment]
The feature has already been requested, and you can vote for it here:  https://developercommunity.visualstudio.com/content/idea/580810/case-preserving-search-replace.html
