### ISSUE TITLE
Running FastTree on this data set results in awful metrics

### ISSUE THREAD

**Issue by v3rt1go** [dotnet/docs#14927]
I've followed the tutorial line by line using the sample data provided above.
The resulted metrics look like this:

*************************************************
*       Model quality metrics evaluation
*------------------------------------------------
*       RSquared Score:      -1.48
*       Root Mean Squared Error:      15.1
**********************************************************************
Predicted fare: 0, actual fare: 15.5 

Did anyone else encounter this issue while using the .csv train and test data?
I've tried both FastTree and FastTreeTweedie algorithm, both provide awful results.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using regression - ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by v3rt1go** [comment]
Please disregard.
I've found the issue - I was missing the separatorChar from the: 
`_mlContext.Data.LoadFromTextFile<TaxiTrip>(_trainDataPath, hasHeader: true,  separatorChar: ',');`

It was defaulting to \t and messed up model. 
I suppose it would be useful to have the LoadFromTextFile method throw an exception if the column count doesn't match the schema.

**Comment by natke** [comment]
Thank you for the suggestion @v3rt1go. I will pass it on to the dev team, or you are very welcome to raise the issue yourself at https://github.com/dotnet/machinelearning/issues
