### ISSUE TITLE
UseSignalR and UseConnections are marked obsolete

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/docs#14928]
## UseSignalR and UseConnections are marked obsolete

The methods `UseConnections` and `UseSignalR`, and the classes `ConnectionsRouteBuilder` and `HubRouteBuilder` are being marked obsolete in 3.0.

### Version introduced

3.0

### Old behavior

SignalR hub routing was configured using `UseSignalR`, `UseConnections`.

### New behavior

The old way of configuring routing has been obsoleted and replaced with Endpoint routing.

### Reason for change

We're moving middleware to the new EndpointRouting system so we're obsoleting the old way of adding middleware.

### Recommended action

Replace `UseSignalR` with `UseEndpoints`,

Old code:
```c#
app.UseSignalR(routes =>
{
    routes.MapHub<SomeHub>("/path");
});
```
New code:
```c#
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<SomeHub>("/path");
});
```

### Category

ASP.NET Core

### Affected APIs

[Microsoft.AspNetCore.Builder.IApplicationBuilder.UseSignalR](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.signalrappbuilderextensions.usesignalr?view=aspnetcore-2.2#Microsoft_AspNetCore_Builder_SignalRAppBuilderExtensions_UseSignalR_Microsoft_AspNetCore_Builder_IApplicationBuilder_System_Action_Microsoft_AspNetCore_SignalR_HubRouteBuilder__)
[Microsoft.AspNetCore.Builder.IApplicationBuilder.UseConnections](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.connectionsappbuilderextensions.useconnections?view=aspnetcore-2.2#Microsoft_AspNetCore_Builder_ConnectionsAppBuilderExtensions_UseConnections_Microsoft_AspNetCore_Builder_IApplicationBuilder_System_Action_Microsoft_AspNetCore_Http_Connections_ConnectionsRouteBuilder__)
[Microsoft.AspNetCore.Http.Connections.ConnectionsRouteBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.connectionsroutebuilder?view=aspnetcore-2.2)
[Microsoft.AspNetCore.SignalR.HubRouteBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.hubroutebuilder?view=aspnetcore-2.2)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by omuleanu** [comment]
using the obsolete code, my webapp works (netcoreapp3.1),
but as soon as I use the new way, in my case:
`endpoints.MapHub<SyncHub>("/syncHub"); `
I get the error:
> VM68:16 Uncaught (in promise) Error: Failed to invoke 'Send' due to an error on the server.
    at _this.callbacks.<computed> (<anonymous>:16:35838)
    at HubConnection.processIncomingData (<anonymous>:16:38004)
    at WebSocketTransport.HubConnection.connection.onreceive (<anonymous>:16:27722)
    at WebSocket.webSocket.onmessage (<anonymous>:16:110678)
_this.callbacks.<computed> @ VM68:16
HubConnection.processIncomingData @ VM68:16
HubConnection.connection.onreceive @ VM68:16
webSocket.onmessage @ VM68:16

when calling `connection.invoke`

**Comment by omuleanu** [comment]
turns out using the new `endpoints.MapHub` you have to send the exact parameter type you defined in the `Hub`,
I was sending: `connection.invoke("Send", key) // key being int` 
and in the hub I have:
`public async Task Send(string key)`
so now I had to call `toString()` on `key` in js to make sure it is the same type as in the hub.
