### ISSUE TITLE
HttpRequestMessage.Version default changed from Core 2.2 to Core 3.0

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#14923]
## HttpRequestMessage.Version default changed between Core 2.2 and 3.0

HttpRequestMessage.Version was changed in Core 2.1 to be `2.0`. Core 3.0 then reverted this back to the value of `1.1`.

API docs are being updated: dotnet/dotnet-api-docs#3285

### Version introduced

.NET Core 3.0

### Old behavior

Value of this property was `2.0`

### New behavior

Value of this property is now `1.1`

### Reason for change

Unknown

### Recommended action

N/A

### Category

- Networking

### Affected APIs

[HttpRequestMessage.Version](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Thraka** [comment]
@rpetrusha Does this mean you put it in the migration guide for 2.1/2.2 -> 3.0?

**Comment by mairaw** [comment]
I'm reopening this one

**Comment by mairaw** [comment]
Now I see that there's a PR open that will solve this one: #14935 

We probably should tie breaking changes PRs to each issue in the future with the Closes keyword, for example.

**Comment by rpetrusha** [comment]
Yes, @Thraka. <https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0?branch=pr-en-us-14935#networking>
