### ISSUE TITLE
Incorrect method name

### ISSUE THREAD

**Issue by Bediruna** [dotnet/docs#14921]
Under the Evaluate Model section there is a line that says:
"Next, transform the Test data by adding the following code to EvaluateModel():"
When it should say:
"Next, transform the Test data by adding the following code to in the Evaluate method:"
I was a bit confused because that was the only mention of an EvaluateModel() method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using regression - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Thank you @Bediruna. I've fixed the typo in #14922
