### ISSUE TITLE
Code highlighting doesn't line up

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs#14936]
I don't know if this is the correct repo, but throughout docs.microsoft.com all code samples with a highlighted line(s) will be displayed incorrectly:

![image](https://user-images.githubusercontent.com/303201/66169184-05511f80-e69c-11e9-9c31-fcd79a9c804b.png)

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#keep-alive-timeout

Chrone. Windows 10. 125% scale.

**Comment by tdykstra** [comment]
@JamesNK Thanks for reporting this.  It's a known problem but has not been prioritized high enough to fix yet.  

The correct repo to create an issue in is https://aka.ms/sitefeedback

@Rick-Anderson FYI

**Comment by tdykstra** [comment]
I added a link to this issue in our internal bug tracking work item at https://icm.ad.msft.net/imp/v3/incidents/details/136852259/home
