### ISSUE TITLE
Missing .Net Framework version 4.8.03921 = release 0x00080f51 (528209)

### ISSUE THREAD

**Issue by verdy-p** [dotnet/docs#14931]
I see:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full]
"Version" =(REG_SZ) "4.8.03921"
"Release" =(DWORD) 0x00080f51 (528209)

Same values in:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you for your feedback @verdy-p. Let me check that with the release team.

My machine is still on version 4.8.03752.

@NKarnam15 can you confirm this and what conditions trigger this specific value?

Here's what we have right now:
![image](https://user-images.githubusercontent.com/12971179/66166936-89989980-e5ed-11e9-88a8-5a909e9255ef.png)

**Comment by verdy-p** [comment]
Note that I see these .Net versions/release numbers in Windows 10 Build 18990.vb_release (the candidate "Vibranium" prerelease for Insiders in the "Olympia" branch, i.e. users connected to the Azure-based "professional" account on Windows.com, which enforces stronger security parameters).
I can't affirm this is the value used in all installations of Windows 10, or just Windows 10 Pro, or just Insider branches, or all Pro users connected to a "professional" account, or just those in the Vibranium. Note that I'm in the "fast ring", but Microsoft has now many internal subrings within its base of Insider users, depending on their location, installed devices, CPU, memory, GPU, internet access type, and most probably according to their collected usage data.

.Net has numerous branches and versions and many settings, and Insiders are also spread across different branches to tests different configurations and scenarios (there are multiple policies settings applied in the Insider branches, managed directly by Microsoft, notably security settings which may be forced on or forced off, and that users are not allowed to change during these tests, until the next update. May be the releases 528040 and 528049 you speak about and the higher release 528209 that I have are in specific test branches. I suppose that the .net release 528209 (v 4.8.03921) is only tied to the Vibranium build 18990.

**Comment by mairaw** [comment]
That’s helpful to know @verdy-p!

**Comment by NKarnam15** [comment]
@verdy-p you are correct, 4.8.03921 is tied to the Vibranium build.

**Comment by verdy-p** [comment]
Also applies to further Vibranium builds (now build 18995)
