### ISSUE TITLE
Do you add xml comments to interfaces and classes?

### ISSUE THREAD

**Issue by zhenyar** [dotnet/docs#14930]
Do you suggest adding xml comments to both interfaces and classes or just one of them to avoid duplication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I'd suggest adding to both, especially if you're generating documentation based on that.

The .NET team doesn't historically adds /// comments everywhere, but you can see an example here:
https://source.dot.net/#System.Runtime/System/Collections/Generic/ISet.cs,24ab7bbfbae81f24
