### ISSUE TITLE
no need for class name on linux example

### ISSUE THREAD

**Issue by gshields** [dotnet/docs#14946]
on https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode for sharp
The 2nd example has PigLatin.toPigLatin "banana";; and it should be
toPigLatin "banana";;
using Ubuntu 19 and core 2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b07eeb2-d274-35da-78d4-b7d78c255590
* Version Independent ID: bf145620-7f23-eb4d-376d-f739562d9a79
* Content: [Get Started with F# in Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode#feedback)
* Content Source: [docs/fsharp/get-started/get-started-vscode.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-vscode.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by tulikavijay** [comment]
Hi, i would like to work on this.

**Comment by cartermp** [comment]
@gshields Which example are you referring to? `PigLatin.toPigLatin` is required when the function is in a class library.

**Comment by mairaw** [comment]
Added the needs-more-info label. The label gets automatically removed when the issue opener responds or closes the issue in two weeks if we don't get an answer.
