### ISSUE TITLE
ASP.NET Core Identity UI now uses "static web assets" feature

### ISSUE THREAD

**Issue by anurse** [dotnet/docs#14959]
## ASP.NET Core Identity UI now uses "static web assets" feature

In ASP.NET Core 3.0 we've moved Identity UI to use the new static web assets feature introduced in 3.0. As part of this move there are a few API breaking changes to note.

Bootstrap4 is the default UI framework for Identity UI. (Bootstrap 3 has reached end of life and you should consider migrating to a supported version).

Selecting the framework is done by using the IdentityUIFrameworkVersion property in your project file.

### Version introduced

3.0

### Old behavior

The default UI framework for Identity UI was **Bootstrap 3.0**. The UI framework could be configured using a parameter to the `.AddIdentityUI()` call in `Startup.ConfigureServices`.

### New behavior

The default UI framework for Identity UI is now **Bootstrap 4.0**. The UI framework must be configured in your csproj file, instead of the `.AddIdentityUI()` call, by adding the following MSBuild property to your csproj file:

```
<IdentityUIFrameworkVersion>Bootstrap3</IdentityUIFrameworkVersion>
```

### Reason for change

We updated the default UI framework to reflect a new version of Bootstrap. Because we use the new static web assets feature, the UI framework configuration moved to MSBuild since the decision on which framework to embed is a build-time decision not a run-time decision.

### Recommended action

Review your site UI to ensure the new Bootstrap 4.0 components are compatible. If necessary, use the `IdentityUIFrameworkVersion` MSBuild property to revert to 3.0.

### Category

- ASP.NET Core

### Affected APIs

[`IdentityBuilderUIExtensions.AddDefaultUI()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identitybuilderuiextensions.adddefaultui)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by serpent5** [comment]
FYI, the explanation for this announcement discusses `AddIdentityUI`, but the affected API is `AddDefaultUI`.

**Comment by scottaddie** [comment]
@serpent5 Thank you for letting me know. Looking at this right now.
