### ISSUE TITLE
What is the default verbosity?

### ISSUE THREAD

**Issue by benmccallum** [dotnet/docs#14952]
It'd be good if you need to add the verbosity switch to know what the default level is so you can bump it up explicitly as needed. Happy to PR if someone tells me what it is. Will go digging if I have time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
Default verbosity is minimal.  A PR to add that would be welcome!
