### ISSUE TITLE
ComputeSalesTax could be DRYer

### ISSUE THREAD

**Issue by DonaldRich** [dotnet/docs#14951]
The switch expression in the Property Patterns sample allows for less repetition by moving the multiplication of the tax by salePrice to before or after the switch expression:

public static decimal ComputeSalesTax(Address location, decimal salePrice) =&gt;
    salePrice * location switch
    {
        { State: "WA" } =&gt; 0.06M,
        { State: "MN" } =&gt; 0.75M,
        { State: "MI" } =&gt; 0.05M,
        // other cases removed for brevity...
        _ =&gt; 0M
    };

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by davidlfox** [comment]
@BillWagner up for grabs? feels like a layup

**Comment by Countryen** [comment]
Can the same be done for the "positional pattern" example with the tuples? Or do you have to repeat the destruction for every case?
