### ISSUE TITLE
How to create JsonObject  from Utf8JsonReader in .netCORE 3. Newtonsoft Json had Jobject class to load reader ?

### ISSUE THREAD

**Issue by RaminderRandhawa91** [dotnet/docs#14964]
## How to create JsonObject  from Utf8JsonReader in .netCORE 3. Newtonsoft Json had Jobject class to load reader ?

[Brief description of the change]

### .NetCore3

3.0

.NET Core 3

---
#### Issue metadata

* Issue type: breaking-change

**Comment by rpetrusha** [comment]
Thanks, @RaminderRandhawa91. Is this a breaking change between preview versions of .NET Core 3.0, @RaminderRandhawa91, or are you looking for information on handling differences between Newtonsoft Json and the JSon types in .NET Core 3.0?

**Comment by RaminderRandhawa91** [comment]
Looking for information on handling differences between Newtonsoft Json and the JSon types in .NET Core 3.0

**Comment by mairaw** [comment]
@ahsonkhan @JamesNK can you help with this question?

/cc @tdykstra - not sure if there's any doc impact from this

**Comment by ahsonkhan** [comment]
JObject in Newtonsoft.Json represents a "DOM" structure for a JSON object which gives you random access to its properties.

The type you are looking for, that's built-in to .NET Core 3.0, is `JsonDocument` (note: it is readonly).
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument?view=netcore-3.0
You can create a `JsonDocument` from a `Utf8JsonReader` by calling the `ParseValue` static method on `JsonDocument`.
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument.parsevalue?view=netcore-3.0#System_Text_Json_JsonDocument_ParseValue_System_Text_Json_Utf8JsonReader__

Hope that helps. Let me know if you have any more questions, and if so, please also share more details about your scenario/use case itself so I can get some context?

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
