### ISSUE TITLE
C# statements - yield example

### ISSUE THREAD

**Issue by manu-p-1** [dotnet/docs#14979]
Regarding the yield statement example, the parameter name, **from** is highlighted in a blue color. This color indicates that the name is reserved (in this case **from** is a clause keyword). Although, this is not a compile time error, the syntax highlight can make the example slightly confusing at first glance. I would recommend changing the names, **from** and **to** into something else (such as **start** and **end**).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017f9566-a4df-e294-d6e8-da9252469ca9
* Version Independent ID: 6665f9d5-24bf-ac0d-62f5-d63ed53132ed
* Content: [C# Statements - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/statements)
* Content Source: [docs/csharp/tour-of-csharp/statements.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/statements.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think an internal bug could be filed for that.
/cc @mairaw

**Comment by BillWagner** [comment]
I logged MicrosoftDocs/feedback#2008 to get the syntax highlighting updated.

That said, I'll leave this open. In an introductory text such as this, the variables should not be contextual keywords. That can lead to confusion for beginners.
