### ISSUE TITLE
Contradiction in Package version resolution

### ISSUE THREAD

**Issue by joostas** [dotnet/docs#14978]
Under [Version section](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#version) mentioned:
>The attribute respects the rules of the NuGet versioning scheme. The default behavior is an exact version match.

But referred [ NuGet versioning document](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) states that  if specified only number it applies rule `Minimum version, inclusive`, but not `Exact version match`.
```xml 
<!-- Accepts any version 6.1 and above. -->
<PackageReference Include="ExamplePackage" Version="6.1" />
```
Seems like contradiction. Either attribute doesn't respect the rules of NuGet versioning scheme or there is mistake in NuGet versioning documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#feedback)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
