### ISSUE TITLE
When does this installation take place?

### ISSUE THREAD

**Issue by TomGroszko** [dotnet/docs#14975]
After I follow the steps in this document when does the installation take place? How do I start the installation process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fdb6f36-c952-4317-669d-b4618505b688
* Version Independent ID: 69caa919-1a67-806e-172b-f20653ca32b3
* Content: [How to: Add Installers to Your Service Application](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-add-installers-to-your-service-application#feedback)
* Content Source: [docs/framework/windows-services/how-to-add-installers-to-your-service-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/how-to-add-installers-to-your-service-application.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This article goes about the process of installing the service: https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services
