### ISSUE TITLE
dotnet sln add with configuration mapping

### ISSUE THREAD

**Issue by selalerer** [dotnet/docs#14986]
How can I add a project to the solution and change the mapping of its configuration?

E.g., I want when the solution is build with Release configuration:
`dotnet buid MySln.sln -c Release`

That the project will be built with configuration MyRelease. In my csproj:

```
 <PropertyGroup>
    <Configurations>Debug;Release;DebugCore;ReleaseCore</Configurations>
    ....
  <PropertyGroup Condition="'$(Configuration)'!='MyRelease'">
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='MyRelease'">
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @selalerer, thanks for your feedback. We still have in our backlog an issue to describe targets and props that hopefully will go over some of these scenarios (#2642).

Adding @dsplaisted to help with these questions as well and confirm that my suggestions are correct.

I think there are a few possibilities here:
- Pass MyRelease as the value for -c in dotnet build
- Change your project config a bit to read like 
`<PropertyGroup Condition="$(Configuration.Contains('Release'))">` 

Do any of these work for you?

**Comment by selalerer** [comment]
Hi mairaw,

Thank you for these suggestions but I don't think they can help me achieve my goal.

I would like to run dotnet build for my sln file with Release configuration and have most csproj that are specified in this sln file run with the Release configuration. I would however want that a few csproj that are specified in the sln file run with a different configuration (e.g. MyRelease).

Thank you, Sela.

**Comment by dsplaisted** [comment]
I think you have to use the Visual Studio Configuration Manager UI if you want to change the mapping of solution configuration to project configuration.  @rainersigwald @nguerrera 

I'm not sure about the details of your scenario, but it might be a lot simpler to just use multitargeting and always build for both target frameworks, ie `<TargetFrameworks>net471;netcoreapp2.1</TargetFrameworks>`

**Comment by rainersigwald** [comment]
@selalerer you're right that solution-configuration manipulation isn't supported in `dotnet sln`. There's a feature request for that: dotnet/cli#11679.

**Comment by tdykstra** [comment]
Addressed by feature request, closing here.
