### ISSUE TITLE
Document Visual Studio 2017  edit of .csproj

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#1498]
@mairaw  assign to me and let me know where it should go

**Comment by mairaw** [comment]
None of the existing topics seem to fit this scenario. Maybe it should be a standalone tutorial? It'll be short though.

**Comment by mairaw** [comment]
@TerryGLee are you covering this in the VS docs?

**Comment by mairaw** [comment]
For us, we could probably add a sentence in the migration topic where we talk about migrating your project in VS and how you can edit the csproj.

**Comment by BillWagner** [comment]
@mairaw Can this be closed?  Is it covered in VS Docs? /cc @TerryGLee

**Comment by TerryGLee** [comment]
We have this page: 
https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects 
If this doesn't cover the initial request, please add @KraigB to the conversation.

**Comment by mairaw** [comment]
The request is about the following new option in VS to manually edit csproj files when you right click on your project:
![image](https://user-images.githubusercontent.com/12971179/28346867-87952896-6be8-11e7-9eea-95b14d5bbaf7.png)

I don't know if it only shows up for ,NET Core projects.

**Comment by mairaw** [comment]
I'd imagine we'd want to mention that in this topic perhaps: https://docs.microsoft.com/en-us/visualstudio/ide/managing-project-and-solution-properties?

/cc @TerryGLee @kraigb
