### ISSUE TITLE
"Publish" is overloaded

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#14999]
Due to the use of "publish" in the context of creating assets to deploy (building/pack), "publish" is overloaded because it's a NuGet concept, too.

I can't tell from the description if the project is built and the package is created (packed) or merely deployed (i.e., does one still perform a `dotnet pack` prior to using this command?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
This pushes a "NuGet package" to the server, effectively publishing it. I think the descriptions could be updated to indicate that it's a NuGet package.

**Comment by guardrex** [comment]
Sure, but I'm specifically asking about distinguishing it from packing (building; i.e., `dotnet pack`). A quick one-liner or even just a cross-link to `dotnet pack` might do the trick to make it clear that this is a deployment command, not a building/packing command and that building/packing must be performed separately (if that's the case).
