### ISSUE TITLE
in sample code, the method needs "static" keyword.

### ISSUE THREAD

**Issue by tonkusmustafa** [dotnet/docs#14993]
An object reference is required for the non-static field, method, or property 'Program.MethodWithCallback(int, int, Del)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5dba5b-eabc-8202-2854-6b1f4a7f971a
* Version Independent ID: 8b2e46f0-6d12-6ce9-944d-b883dcbe0808
* Content: [Using Delegates - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/using-delegates#feedback)
* Content Source: [docs/csharp/programming-guide/delegates/using-delegates.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/delegates/using-delegates.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
From the context, it's not obvious if this is in the context of an object instance.

I like your suggestion @tonkusmustafa 

I've added this to our backlog for when we next update this article. I've also added the "up for grabs" label for community members to submit a PR.
