### ISSUE TITLE
The way ranges work is very unnatural

### ISSUE THREAD

**Issue by cesee** [dotnet/docs#15013]
I would expect a 1..4 range to be 1 2 3 4. It shouldn't match a for loop structure.
Had it been 1.&lt;4 it would make more sense to not include the 4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-US/dotnet/csharp/whats-new/csharp-8?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-ew4QPuVv0QlOzexdTNjrfA&epi=je6NUbpObpQ-ew4QPuVv0QlOzexdTNjrfA&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__h1n1xivsukkfrxt2kk0sohz30m2xgknvrmc06asf00)(7593)(1243925)(je6NUbpObpQ-ew4QPuVv0QlOzexdTNjrfA)()&irclickid=_h1n1xivsukkfrxt2kk0sohz30m2xgknvrmc06asf00#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @cesee. I'll refer to [this comment](https://github.com/dotnet/docs/issues/11324#issuecomment-474112483) from @BillWagner when we've got a similar feedback:

The documentation does accurately reflect those design choices.  

I am going to close this.  However, if you want to continue to advocate for a different design, consider commenting on the referenced design notes, or other issues on ranges in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.

**Comment by SparkDustJoe** [comment]
This has already been closed, but I will say this behavior is consistent with other languages like Python, and in fact this syntax is very Python-like (as is the syntax to reverse-index through a range/array).
