### ISSUE TITLE
Prepend regex patterns in C# with @

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15011]
A couple of articles show the regex example without using the string literal special character (\@).

I find this harder to validate the pattern. So the article linked here as an example, you could change the line from

```csharp
"\\b(?<month>\\d{1,2})/(?<day>\\d{1,2})/(?<year>\\d{2,4})\\b",
```

to 

```csharp
@"\b(?<month>\d{1,2})/(?<day>\d{1,2})/(?<year>\d{2,4})\b",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516dbaa4-c048-ec08-1c3a-3ae241c07d0f
* Version Independent ID: 601553f5-07f6-8959-22e9-37e0b8085ca1
* Content: [Regular Expression Example: Changing Date Formats](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-example-changing-date-formats)
* Content Source: [docs/standard/base-types/regular-expression-example-changing-date-formats.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-example-changing-date-formats.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by MetalDent** [comment]
Hi, anyone is working on this issue?

**Comment by BillWagner** [comment]
@MetalDent No one is working on this yet. Do you want to submit a PR?  Either @mairaw or I can help with any questions.

**Comment by MetalDent** [comment]
@BillWagner you want to change the expressions in the specified article or others also (if present)?

**Comment by BillWagner** [comment]
@MetalDent I recommend starting with this article. @mairaw can point to others that should be updated as well.

**Comment by MetalDent** [comment]
@BillWagner the example links in the [Content-Source](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-example-changing-date-formats.md) link are not found. Should I update them?

**Comment by BillWagner** [comment]
@MetalDent Most of the sample code is in our [dotnet/samples](https://github.com/dotnet/samples) repository.  The docs build clones both repositories and combines them.  For example, the first sample in the content source is [here](https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR/RegularExpressions.Examples.ChangeDateFormats/cs/Example_ChangeDateFormats1.cs#L16-L29)

**Comment by eddynaka** [comment]
Hi @BillWagner , i was looking for the link that you sent before. I couldn't find anything else to change. Am I missing something? Thanks
