### ISSUE TITLE
aborted at 12

### ISSUE THREAD

**Issue by boebing** [dotnet/docs#15010]
I'd love to give valuable feedback but, I just
couldn't proceed beyond
12. In Solution Explorer, expand the Properties folder and select the AssemblyInfo.cs or AssemblyInfo.vb file. In the code editor, add the following attribute to the file:
because none of this is in my Solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16419eb7-66b4-751f-192a-a1f399942579
* Version Independent ID: 1364a74b-43ac-c3a7-4021-80e70cdd43db
* Content: [Walkthrough: Embed types from managed assemblies in Visual Studio](https://docs.microsoft.com/en-us/dotnet/standard/assembly/embed-types-visual-studio#feedback)
* Content Source: [docs/standard/assembly/embed-types-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/embed-types-visual-studio.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @boebing. We'll have to investigate what's wrong with this article. Adding to our backlog for now.
