### ISSUE TITLE
Unclear precedence statement for operators

### ISSUE THREAD

**Issue by Tbhesswebber** [dotnet/docs#15023]
`Except for the assignment operators, all binary operators are left-associative, meaning that operations are performed from left to right.` seems to contradict the following example of `For example, x + y * z first multiplies y by z and then adds the result to x`.

I feel like it should read: `Except for the assignment operators, all binary operators are left-associative, meaning that operations of equivalent precedence are performed from left to right.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d7bc71-c69e-55a3-2f4c-f3139b4b0e82
* Version Independent ID: a7fc6aa5-1ee2-d01b-b34f-090c83599df7
* Content: [C# Expressions - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/expressions#feedback)
* Content Source: [docs/csharp/tour-of-csharp/expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@BillWagner Thoughts?

**Comment by pkulikov** [comment]
@Tbhesswebber the first sentence you've quoted is the item of the list, which is preceded with the following sentence:

> When an operand occurs between two operators with the same precedence, the *associativity* of the operators controls the order in which the operations are performed:

So, the same precedence is from the context of the list.

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @Tbhesswebber 

As @pkulikov comments, the doc is correct as written. The sentence you quote is in a list specifying equal precedence.

That said, if you want to create a PR with wording you think makes it more clear, I'll watch for it.
