### ISSUE TITLE
Consider renaming "build an app" topics

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#15045]
Consider renaming "Build an app" topics to "Create an app" to clarify that they are not about building/compiling. This might also improve localizability.

If you type “build” in the TOC filter, the visible list of results is this, where “build” is actually used to mean “create”. I thought the first topic was about compiling console apps, but it's not at all.

![image](https://user-images.githubusercontent.com/24882762/66443069-78d39380-e9f2-11e9-8d74-701095bfe9b7.png)

**Comment by Grace3579** [comment]
Hello @gewarren, how do I update documentation for this issue?

**Comment by gewarren** [comment]
> Hello @gewarren, how do I update documentation for this issue?

The best thing to do would be to fork and clone the repo locally to your machine. That way you can edit more than one file in a single pull request. Otherwise, you'd have to edit each file separately. For example, here is where you'd update the table of contents (TOC) for the topics that are in the .NET Core guide: https://github.com/dotnet/docs/blob/master/docs/core/toc.yml. However, I think that the H1 heading of the topics should also be updated to match the TOC titles.

**Comment by Grace3579** [comment]
Thank you very much @gewarren.  I created pull requests for your review and approval. Thank you.

**Comment by gewarren** [comment]
@Grace3579 Sorry I missed this @ mention. It looks like you created your pull requests within your own fork. Instead, please create a pull request across forks from your working branch to the master branch of dotnet/docs.
