### ISSUE TITLE
How would you add a task as the program is running in the while loop

### ISSUE THREAD

**Issue by ancich** [dotnet/docs#15041]
To put in it the breakfast analogy terms:  As is, the program is running the tasks eggsTask, baconTask, toastTask.  But what if there is a new task that needs to be added like "hashbrown task"?  Is there a way to add this new task to the list "var allTasks = new List&lt;Task&gt;"?  Would something like allTasks.Add be legal?    What I am ultimately looking for is to somehow setup a queue of tasks, perhaps a pipeline of 12 tasks, where the pipeline gets filled as spaces come up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gabeluci** [comment]
> Would something like allTasks.Add be legal?

Absolutely. This:

    var allTasks = new List<Task>{eggsTask, baconTask, toastTask};

Is equivalent to this:

    var allTasks = new List<Task>();
    allTasks.Add(eggsTask);
    allTasks.Add(baconTask);
    allTasks.Add(toastTask);

**Comment by IEvangelist** [comment]
Hi @ancich,
I appreciate the issue posted here, however; it is beyond the scope of the intended article. The question really is asking about adding to collections in a while loop - which I agree is valuable to understand. But as @gabeluci, shows above this can be done by simply calling `.Add`.

```cs
static async Task Main(string[] args)
{
    Coffee cup = PourCoffee();
    Console.WriteLine("coffee is ready");

    var eggsTask = FryEggsAsync(2);
    var baconTask = FryBaconAsync(3);
    var toastTask = MakeToastWithButterAndJamAsync(2);

    Task<Hashbrown> hashbrownsTask = null;
    var breakfastTasks = new List<Task> { eggsTask, baconTask, toastTask };
    while (breakfastTasks.Count > 0)
    {
        Task finishedTask = await Task.WhenAny(breakfastTasks);
        if (finishedTask == eggsTask)
        {
            Console.WriteLine("eggs are ready");
        }
        else if (finishedTask == baconTask)
        {
            Console.WriteLine("bacon is ready");
        }
        else if (finishedTask == toastTask)
        {
            Console.WriteLine("toast is ready");
        }
        else if (finishedTask == hashbrownsTask)
        {
            Console.WriteLine("hashbrowns are ready");
        }

        if (hashbrownsTask == null)
        {
            hashbrownsTask = GetHashbrownsAsync();
            breakfastTasks.Add(hashbrownsTask);
        }
        breakfastTasks.Remove(finishedTask);
    }

    Juice oj = PourOJ();
    Console.WriteLine("oj is ready");
    Console.WriteLine("Breakfast is ready!");

    static async Task<Toast> MakeToastWithButterAndJamAsync(int number)
    {
        var toast = await ToastBreadAsync(number);
        ApplyButter(toast);
        ApplyJam(toast);
        return toast;
    }
}
```

I'm going to close this issue, but if you feel as though we need to continue the dialog - we can reopen it and discuss it here. Thank you
