### ISSUE TITLE
SignTool

### ISSUE THREAD

**Issue by transdigiware** [dotnet/docs#15048]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new article**

- Explain why this article is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this article will cover.
- Create an outline for the new article. We'll help review the outline and approve it before anyone writes the article.

**Comment by mairaw** [comment]
Not sure what you meant with this issue @transdigiware. We have an article about signtool here: https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe

If you have specific comments about that article, let us know.
