### ISSUE TITLE
Unrecognized element 'claimTypeRequired'

### ISSUE THREAD

**Issue by pavelsem** [dotnet/docs#15057]
Today I got the same error which got reported in past on this page - https://social.msdn.microsoft.com/Forums/vstudio/en-US/e466c55d-333e-4fb5-98d2-ee70cf3e56e2/claimtyperequired-in-a-wif-45-app. It seems this element is no longer available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b7bfc3-b2ca-3538-a215-2f0f06c49dde
* Version Independent ID: 00fe3278-8b74-6e2d-ab2b-272ac5c551a5
* Content: [&lt;claimTypeRequired&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/claimtyperequired#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/windows-identity-foundation/claimtyperequired.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/windows-identity-foundation/claimtyperequired.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
That content is being archived with issue #14801. It's not maintained any longer. So I'm closing this issue.

My guess is that it was in some older version of WIF and then removed.

**Comment by mairaw** [comment]
Not this set. We need to decide whether we want to retire the file schema config along with that. But that issue is just about the security folder under framework.

**Comment by Thraka** [comment]
Ahh ok.
