### ISSUE TITLE
For your confort: A simple command line tool to get the current installed versions

### ISSUE THREAD

**Issue by jmalarcon** [dotnet/docs#15053]
I've just developed a simple command line tool to get all the installed versions in your system, based on the code on this page with a few small tweaks. In this way, you can simply double-click it and get detailed information.

You can see the Source Code and download the .exe tool from "Releases" in GitHub: https://github.com/jmalarcon/DotNetVersions

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Another tool was posted in an issue also: https://github.com/EliteLoser/DotNetVersionLister

I'll see if we can update this page and link to these github repos.
