### ISSUE TITLE
Use internal certificate authority on Linux

### ISSUE THREAD

**Issue by paulkling** [dotnet/docs#1505]
# Use internal certificate authority on Linux

I want to configure dotnet (c#) to trust a internal CA. The command dotnet is being executed on linux centos computer. 

I need to be pointed in a direction on how to do this?

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc can you help with this question?

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
