### ISSUE TITLE
What about Service Fabric?

### ISSUE THREAD

**Issue by alindgren** [dotnet/docs#15055]
I came to this page from https://dotnet.microsoft.com/apps/aspnet/microservices which has a link "Explore options for hosting your microservices on Azure". I've been trying out Service Fabric but I am concerned whether or not it has a promising future if it is not being shown as an option for developing microservices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45be6d71-575d-5d8d-bcdc-b6885ddbb487
* Version Independent ID: 7c37b77a-63fc-4fb4-ae32-02ac9c09e1c8
* Content: [Choosing Azure compute platforms for container-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil who can help with this question?

**Comment by nishanil** [comment]
Kubernetes has become the de-facto orchestrator for building microservices in a cloud-agnostic way. Hence our guidances are focussed on Azure Kubernetes Service (AKS). However, Service Fabric is a proven platform and has been used internally by some of the largest services on Azure. You may choose Service Fabric over Kubernetes if your scenario fits their offering(for e.g. stateful services). I found this post from the past which does some comparisons. https://blogs.msdn.microsoft.com/azuredev/2018/08/15/service-fabric-and-kubernetes-comparison-part-1-distributed-systems-architecture/

**Comment by alindgren** [comment]
@nishanil - Thanks for the response. The post you linked to is very informative. I've been working with Service Fabric for about a month and really like it. To me (a .NET developer) it seems easy to use and very powerful. For this reason, I think it should be presented as an option for building microservices on Azure.

**Comment by mairaw** [comment]
I was going to follow up with a question on whether this should be added to the docs or not, but it seems someone already suggested that on issue #11362.

**Comment by masnider** [comment]
Hi @nishanil and @mairaw, I'm one of the product owners from Service Fabric and am happy to help fix up guidance to include SF where it is missing. I was pointed to one table earlier so please see the PR I just created for that. If there are other docs that you need/want help updating just point me at them and I can try to make some targeted fixes. Thanks for pointing this out @ndebrass and @alindgren !

**Comment by BillWagner** [comment]
Reopening per conversation.  See PR #21258 for a fix.
