### ISSUE TITLE
What type is returned by a sequence indexed by a range?

### ISSUE THREAD

**Issue by jkindwall** [dotnet/docs#15067]
What type is returned by a sequence indexed by a range?  Is it the same type as the source sequence?  Or is it some other standard type or interface?  This is not addressed anywhere in the article, and the repeated use of "var" in the examples makes it impossible to infer from reading the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes#feedback)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@jkindwall typically it's the same type: `string` for `string`, an array for an array, etc. You might see the following code with `Span`:

```csharp
var nums = new[] { 0, 1, 2 };
Span<int> part = nums[0..2];
part[0] = 10;
Console.WriteLine(string.Join(" ", nums));  // output: 0 1 2
foreach (var x in part)
{
    Console.Write($"{x} ");
}
// Output: 10 1
```

However, first, `nums[0..2]` produces an array, which is then implicitly converted to `Span<int>`. So, that `Span` instance is not the window to the original array. That is, changing that instance doesn't affect the array.

For more details about ranges support, see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges#implicit-range-support
