### ISSUE TITLE
Source declaration conflicts with itself

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#15076]
This page states

&gt; You specify additional feeds by creating your own nuget.config file in the project directory.  You also specify additional feeds per invocation at a command prompt.

But in the `-s` documentation it states:

&gt; This setting overrides all of the sources specified in the nuget.config files

The first makes it sound like it will add another feed when supplied at the command line.  The second makes it clear that it replaces all the ones found in the nuget.config.

This document should be updated to clarify which is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello!

I see where the confusion is. It's with this statement specifically:

>You also specify additional feeds per invocation at a command prompt.

Really this should state that you can **override** the feeds in a _nuget.config_ file with the `-s` command prompt parameter.

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
