### ISSUE TITLE
.NET Framework 3.5 missing from system requirements

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#15074]
See this page: https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#supported-server-operating-systems

I would expect 3.5 to be listed. It reads like it isn't supported.

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#supported-server-operating-systems)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
This is just a side effect of having different versions of the same topic on MSDN @richlander. 

But the article starts with 
![image](https://user-images.githubusercontent.com/12971179/66531406-88b9a900-eac0-11e9-9138-280ac9c9eb48.png)

Not enough?

**Comment by richlander** [comment]
Someone in Windows reached out to me asking with 3.5 wasn't on that page, and then I looked and could not figure it out either. So, I guess that was the usability test. I'm not defining any priority here, but is unfortunate that there are two overlapping pages.

**Comment by mairaw** [comment]
Ok. Adding as P2 to our backlog.
