### ISSUE TITLE
Why has the Dockerfile a copy sln and a copy all command?

### ISSUE THREAD

**Issue by Jeej** [dotnet/docs#15070]
Hi,

In the example dockerfile two copy commands are used. The first is to copy the solution files (COPY *.sln .), the second copy is to copy all the files (COPY . .).

Why are there two copy commands? The solution files will also be copied with the second copy dot command I guess?

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @Jeej, thanks for the heads up!

You're right, that's a bug, will remove.

or... you could do it yourself, if you wish, by editing the page and creating a PR! 😉
