### ISSUE TITLE
Update deployment overview article for .NET Core

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15081]
@richlander proposed that we update the main entry point that explain the different deployment options by breaking up into two options: framework-dependent apps and self-contained apps.
Inside those two options, we’d break down the two different options for single-file vs. multiple files instead of calling executable vs. deployments.

We also need to make sure the content is updated for .NET Core 3.0.

Some info can be found at https://review.docs.microsoft.com/en-us/dotnet/core/deploying/publish?branch=pr-en-us-14425 as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
>**NOTE**\
>3.0 allows you to disable the output of a build executable in the project with the following setting: `<ComputeNETCoreBuildOutputFiles>false</ComputeNETCoreBuildOutputFiles>`

**Comment by Thraka** [comment]
#16409 is related

**Comment by mairaw** [comment]
Moved this to January
