### ISSUE TITLE
Delete file async

### ISSUE THREAD

**Issue by Legends** [dotnet/docs#15085]
Can this be done with .net core 3.0?
`await File.DeleteAsync(path)`
If not, why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c1b292-9f8a-d512-e780-24cb865a2da2
* Version Independent ID: 731858ee-ae76-9477-2ddf-40277bf1bd71
* Content: [Asynchronous File I/O](https://docs.microsoft.com/en-us/dotnet/standard/io/asynchronous-file-i-o)
* Content Source: [docs/standard/io/asynchronous-file-i-o.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/asynchronous-file-i-o.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hello,

There is no `*Async` overload for `File.Delete` in any framework. As to why this decision was made, I cannot say. Doing some quick searching through I found some alternatives, such as an extension method: https://stackoverflow.com/questions/10606328/why-isnt-there-an-asynchronous-file-delete-in-net

**Comment by Elvin1492** [comment]
Strang that in 2023 still there is not such method

**Comment by turowicz** [comment]
Strang
