### ISSUE TITLE
Need to clear up confusion around run, build, and publish

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/docs#1509]
Our topics on how to build apps all need to be clearer that `dotnet build` and `dotnet run` just get you an intermediate outputs that are good for running on your local machine in development mode only. They are not meant to build a final output to run in production. We need to find a way to make that really clear and point people to how to publish their assets from the command line, in VS, and in VS Code.

**Comment by mairaw** [comment]
That's a good point @Petermarcu! So for topics such as the one I'm working on for PR #1507 (Getting Started with CLI), should we have dotnet publish in that topic or create a new topic on how to deploy .NET Core apps?

/cc @blackdwarf

**Comment by blackdwarf** [comment]
We already have a topic on how to deploy .NET Core apps. But we should start stringing this together. For instance, in the getting started, we should add that in order to get an app that runs on another machine, you should use publish. For full docs, please refer to deployment topic. And the like. 

Another thing we need to add is the overall table that has a split between dev-time and production-time usage of verbs.

**Comment by mairaw** [comment]
I see now that the [deploying topic](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/) has both the overview and step-by-step instructions.
But what I was thinking was more along the lines of continuing to build up on the Getting Started, similar to what was done for the VS topics: https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/publishing-with-visual-studio-2017, so you go on a progression.

**Comment by mairaw** [comment]
And I'll something about publishing to my PR pointing to the deployment topic for now.

**Comment by Petermarcu** [comment]
Ideally there is at least one place that takes me through all the way to the point where the app in my output folder is a real app that looks like an app I could run somewhere else. Not the one without my dependencies locally and depending on the nuget cache.
