### ISSUE TITLE
Missing JsonSerializerOptions

### ISSUE THREAD

**Issue by qbit86** [dotnet/docs#15105]
In section [Allow comments and trailing commas](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#allow-comments-and-trailing-commas) there is an example of using `JsonSerializerOptions`. But `options` actually is not passed to `Deserialize()` method:
```cs
var weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(json);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@qbit86 Thanks for reporting that! It is fixed in #15106
