### ISSUE TITLE
IAsyncRequestHandler should be replaced by IRequestHandler

### ISSUE THREAD

**Issue by pawel-zolty** [dotnet/docs#15104]
In 4th section under "Register the types used by MediatR" header, there is registered IAsyncRequestHandler interface in MediatR module. Since 4.0.1 MediatR have allowed to use only IRequestHandler. 
https://github.com/jbogard/MediatR/releases
https://github.com/jbogard/MediatR/issues/224

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3920c19-388e-0e84-960f-0bb0c8340fe0
* Version Independent ID: c728d4ba-50e8-798d-72a0-c4a5b6f13ca2
* Content: [Implementing the microservice application layer using the Web API](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by tjoudeh** [comment]
+1, spent some time comparing if IAsyncRequestHandler is still valid with MediatR 4.0.1, thanks @pawel-zolty for highlighting this.
