### ISSUE TITLE
GC balancing act

### ISSUE THREAD

**Issue by Miggleness** [dotnet/docs#15100]
My understanding of the statement quoted below is that the two are directly proportional to each other.  Wouldn't "giving the application sufficient working set and not letting the garbage collection take too much time" be a more accurate statement?

 "The CLR continually balances two priorities: not letting an application's working set get too big and not letting the garbage collection take too much time."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#feedback)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @Miggleness. @Maoni0 how do you feel about such proposed change?

**Comment by Maoni0** [comment]
"not letting an application's working set get too big" means not delaying GC by too much, so don't do too few GCs.
"not letting the garbage collection take too much time" means not doing GCs too often, so don't do too many GCs.
if you could explain what the confusion is it would help me understand why you wanted to change it.

**Comment by Miggleness** [comment]
@Maoni0 Your explanation makes it clear now.  My understanding were as follows.

"not letting an application's working set get too big" - I have the same understanding which is not to delay GC by too much

"not letting the garbage collection take too much time" - I took this as not letting a **single GC** run for too long, which would mean the same as above and not delay GC by too much.

**Comment by Miggleness** [comment]
I should've added a suggestion in my last message but had to run. Would the phrase below be clearer?

> The CLR continually balances two priorities: not letting an application's working set get too big by delaying garbage collection and not letting the garbage collection run too frequently

**Comment by Maoni0** [comment]
I'm fine with that.
