### ISSUE TITLE
Missing output

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/docs#15117]
The output for Array.tryFind shows:
```
Found an element: 1
Found an element: 729
```
but should show:
```
Found an element: 1
Found an element: 729
Failed to find a matching element.
```

Similarly, the output for Array.tryPick is missing the last line:
```
Found an element 1 with square root 1 and cube root 1.
Found an element 64 with square root 8 and cube root 4.
Found an element 729 with square root 27 and cube root 9.
Found an element 4096 with square root 64 and cube root 16.
Did not find an element that is both a perfect square and a perfect cube.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cda87e0-998a-086f-f5ed-2290d7a97966
* Version Independent ID: 45152c64-0643-3c5a-93cb-a2f689170887
* Content: [Arrays - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/arrays#feedback)
* Content Source: [docs/fsharp/language-reference/arrays.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/arrays.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by mairaw** [comment]
Thanks @BruceForstall for your comment, Would you like to submit a PR to fix this?

Here's more info on how to do this:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
