### ISSUE TITLE
Possible typo in 'Test the project template' section

### ISSUE THREAD

**Issue by semuserable** [dotnet/docs#15130]
First paragraph. 
Navigate to the test folder and create a new console application with `dotnet new console` - original

You probably meant `dotnet new consoleasync`, not `dotnet new console`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097102bb-f6d9-c469-5556-ae1f16fdc4fe
* Version Independent ID: 77b25381-6e0f-949f-5f96-b83e9b61e9fc
* Content: [Create a project template for dotnet new - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template#feedback)
* Content Source: [docs/core/tutorials/cli-templates-create-project-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-project-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by tulikavijay** [comment]
I would like to fix this.
