### ISSUE TITLE
How do you know if you have successfully opted-out?

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet/docs#15133]
See title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c136055b-bb04-17b6-19b2-42d4610c1a70
* Version Independent ID: 50433ae5-4687-fe5f-75ab-a47e1a706777
* Content: [.NET Core SDK telemetry - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#feedback)
* Content Source: [docs/core/tools/telemetry.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/telemetry.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Pinging @KathleenDollard in email too.

**Comment by KathleenDollard** [comment]
If the environmental variable is set, you are opted out (or we have what we would consider a very, very bad bug). I don't know how we could confirm this as we'd just check the environment variable that the user could check and probably be more confident in. 

If there is a suggestion for a feature, please make it at github.com/dotnet/cli

**Comment by Thraka** [comment]
Thank you for the reply. I'm going to close this.

**Comment by snuup** [comment]
I have set 

DOTNET_CLI_TELEMETRY_OPTOUT = 1

but running 

dotnet -d

returns:

"Telemetry is: Enabled"

Lokks like you have that very very bad bug?

**Comment by Thraka** [comment]
@snuup Sorry you're having a problem. I checked and it seems to be working for me. If you're having a problem, I would file an issue in the https://github.com/dotnet/core repository.

```
C:\Code\Work\dotnet\dotnet-docs\docs\core>dotnet -d
Telemetry is: Enabled
System.ArgumentException: cannot be empty (Parameter 'name')
   ...

C:\Code\Work\dotnet\dotnet-docs\docs\core>set DOTNET_CLI_TELEMETRY_OPTOUT=1

C:\Code\Work\dotnet\dotnet-docs\docs\core>dotnet -d
Telemetry is: Disabled
System.ArgumentException: cannot be empty (Parameter 'name')
   ....
```
