### ISSUE TITLE
Add docs for PipeReader/PipeWriter.Create(stream)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs#15147]
In the stream section we currently show `AsStream()` for going from PipeReader and PipeWriter to a `Stream` but we don't show the other way using PipeReader/PipeWriter.Create(stream).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5384a7-5e96-d977-7748-317a2c758f63
* Version Independent ID: 06e72212-a052-a351-0e0b-1b002ce214de
* Content: [I/O pipelines - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines)
* Content Source: [docs/standard/io/pipelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/pipelines.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jkotalik** [comment]
Assign @davidfowl as well.

**Comment by mairaw** [comment]
Done.
