### ISSUE TITLE
ASP.NET Core du routage éblouissant

### ISSUE THREAD

**Issue by vintzl** [dotnet/docs#15141]
French documentation says "éblouissant" instead of Blazor. It sucks…

- https://docs.microsoft.com/it-it/aspnet/core/blazor/routing?view=aspnetcore-3.0

For example, the Italian documentation do not have this problem…

- https://docs.microsoft.com/fr-fr/aspnet/core/blazor/routing?view=aspnetcore-3.0

**Comment by mairaw** [comment]
@JasonCard can you please take a look at this feedback for the ASP.NET Core localized docs? Is there a way to ensure that Blazor never gets translated in those docs since it's the product name?

/cc @guardrex @Rick-Anderson @scottaddie

**Comment by Rick-Anderson** [comment]
There must be a list of words not to translate, for the repo, org wide ?

**Comment by Rick-Anderson** [comment]
@vintzl  Ce sont des commentaires très précieux. Merci d'avoir pris le temps de créer un problème.

**Comment by JasonCard** [comment]
@mairaw Yes, we can follow up on this issue, so the product name "Blazor" won't get translated.
@DavidPrio could you please help to follow up on this loc issue reported in en-us repo?
cc @Rick-Anderson

**Comment by CeciAc** [comment]
Hello, @vintzl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@mairaw @JasonCard @Rick-Anderson 
We are working in this issue.
For a long term solution we suggest the term to be blocked in the source page to avoid its translation in the future.

@DavidPrio @Gonzalo-Salines

**Comment by Rick-Anderson** [comment]
@CeciAc  by blocked to you mean \`code fenced\`?

**Comment by mairaw** [comment]
Either that or the new no-loc feature.

**Comment by CeciAc** [comment]
@mairaw that's correct
https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings

**Comment by Rick-Anderson** [comment]
We should create a feature request to support a *.no-loc* file, like *.gitignore* that doesn't loc any of the words in the file.  `Blazor` is used thousands of times. We can't expect customers to know about this. Adding `Blazor` once to a *.no-loc* file file is an more elegant solution.

Alternative, add meta-data

```
---
no-loc: Blazor, foo, bar
title: the title
description: Get an 
author: rick-anderson
---
```

The ignore file approach seems best.

**Comment by Rick-Anderson** [comment]
Looks like that's supported

```
author: cillroy
no-loc: [Global, Strings, to be, Ignored]
```

**Comment by Rick-Anderson** [comment]
@CeciAc  once you approve https://github.com/aspnet/AspNetCore.Docs/pull/15171 we'll add that to all the Blazor docs via https://github.com/aspnet/AspNetCore.Docs/issues/15172

**Comment by DavidPrio** [comment]
Hi @Rick-Anderson @mairaw As long as all instances refer to "Product" named Blazor, this is not localizable. Linguistically speaking, there is no need to include the term in the localization HOs. If no technical issues, I believe you can go ahead with the change. However, I would like MS Loc PM @JasonCard to approve this. Thanks!
@SunnyDeng cc

**Comment by mairaw** [comment]
Not sure if I follow @DavidPrio. If it's not localizable, why is getting localized then?

**Comment by JasonCard** [comment]
I think @DavidPrio meant to say that product name should not be localizable, and recommends the use of no-loc metadata as long as long as all instances of "Blazor" is product name. 
@CeciAc The no-loc metadata syntax in [aspnet/AspNetCore.Docs#15171](https://github.com/aspnet/AspNetCore.Docs/pull/15171) looks correct, so please go ahead to approve. If it does not work for some reason, then we should follow up with a bug.
cc @Rick-Anderson @mairaw @SunnyDeng @bodhigautam

**Comment by vintzl** [comment]
Hi everyone.
You still have some bad outputs…
try this in Bing or Google:
> blazor site:docs.microsoft.com  éblouissant

here a sample:
- https://docs.microsoft.com/fr-fr/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1

**Comment by guardrex** [comment]
@vintzl I've moved that to https://github.com/aspnet/AspNetCore.Docs/issues/16273. We don't work closed issues. It's best to open a new issue using the **This page** feedback button+form at the bottom of any topic (English repo tho; otherwise, it goes to the localization team).
