### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by Daniel15** [dotnet/docs#15159]
The content of this page seems to overlap with the contents of https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern. Seems like these should be unified into a single page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e8321f-5516-e451-5429-750d49f0ebed
* Version Independent ID: 1fd093e9-f47c-ffdd-91e9-5039c3ccde61
* Content: [How to: Publish Events that Conform to .NET Framework Guidelines - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines)
* Content Source: [docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tulikavijay** [comment]
Hi, i would like to work on this. Can you guide me with the task?

**Comment by BillWagner** [comment]
Thanks for writing this @Daniel15 Yes, there is too much duplication here.

Based on the potential organization for this, the correct target would be https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern

@tulikavijay You can submit a PR for this, if you'd like.

There are two additional tasks to make sure we do while merging this.

The first is to redirect the article being removed. That's configured in our master [redirection file](https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json) The second is to update all internal links in this repository. It's larger than we'd normal recommend for a first-time contributor, but if you're interested, I'll watch for a PR.
