### ISSUE TITLE
Library publish behaviors

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#15152]
Similar to #14859

> If a runtime identifier is specified, its default value is `true`.

`--self-contained` is default to `false` for library projects even if a runtime identifier is specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @NextTurn. I'll look into this as I'm making the updates needed for 3.0 on this page. Adding to the backlog for now.
