### ISSUE TITLE
Implicitly-typed Arrays in Object Initializers 

### ISSUE THREAD

**Issue by embok345** [dotnet/docs#15166]
The section Implicitly-typed Arrays in Object Initializers states (emphasis mine)
> When you create an anonymous type that contains an array, the array **must** be implicitly typed in the type's object initializer.

But is this correct? Indeed, in the given example, we can explicitly type the inner array as
```csharp
var contacts = new[]
{
    new {
        Name = " Eugene Zabokritski",
        PhoneNumbers = new string[] { "206-555-0108", "425-555-0001" }
    },
    new {
        Name = " Hanying Feng",
        PhoneNumbers = new string[] { "650-555-0199" }
    }
};
```
On the other hand, the (admittedly rather contrived) example below gives a CS0826 compiler error, No best type found for implicitly typed array, so that the inner array must be explicitly typed, as double[] say (or casting the element(s) in the inner array to whatever type).
```csharp
var outerArray = new[]
{
    new {
        innerArray = new [] { 1 }
    },
    new {
        innerArray = new [] { 1.1 }
    }
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fd590e-0a81-e376-4b89-43c061f64037
* Version Independent ID: 0a8cfc8b-8e13-a88d-eb60-31b351f17891
* Content: [Implicitly Typed Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/implicitly-typed-arrays#feedback)
* Content Source: [docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/arrays/implicitly-typed-arrays.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Great comment @embok345 

This article doesn't define (or link to) implicitly typed variables. The point in this paragraph is that the following would be invalid:

```csharp
var contacts = new[]
{
    new {
        Name = " Eugene Zabokritski",
        string[] PhoneNumbers = new [] { "206-555-0108", "425-555-0001" }
    },
    new {
        Name = " Hanying Feng",
        string[] PhoneNumbers = new [] { "650-555-0199" }
    }
};
```

As you pointed out, the array initializer (on the right-hand-side of the assignment) can specify the type of the array.
