### ISSUE TITLE
Broken URL (404) for "Tiny YOLOv2 pre-trained model"

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#15168]
@Countryen commented on [Fri Oct 11 2019](https://github.com/dotnet/docs.de-de/issues/154)

Link to Pre-requisite "Tiny YOLOv2 pre-trained model" is not valid (404).
https://github.com/onnx/models/tree/master/tiny_yolov2

[AB#1608693](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1608693)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Erkennen von Objekten mithilfe von Deep Learning mit ONNX und ML.NET - ML.NET](https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/object-detection-onnx#feedback)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs.de-de/blob/live/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

---

@srvbpigh commented on [Fri Oct 11 2019](https://github.com/dotnet/docs.de-de/issues/154#issuecomment-541215431)

Hello, @Countryen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
the user reports this link leads to a 404 page, which is also repros in the en-us page
![imagen](https://user-images.githubusercontent.com/26746247/66774909-29311400-ee99-11e9-96bd-7e94385d11a3.png)

**Comment by luisquintanilla** [comment]
Hi @Countryen and @CeciAc ,

Thank you for reporting this. The links have been updated and changes should be reflected sometime later today or tomorrow.
