### ISSUE TITLE
"Banker's Rounding" is not a thing and introduces errors.

### ISSUE THREAD

**Issue by Philbo01** [dotnet/docs#15178]
"Fractional Parts. When you convert a nonintegral value to an integral type, the integer conversion functions (CByte, CInt, CLng, CSByte, CShort, CUInt, CULng, and CUShort) remove the fractional part and round the value to the closest integer.

If the fractional part is exactly 0.5, the integer conversion functions round it to the nearest even integer. For example, 0.5 rounds to 0, and 1.5 and 2.5 both round to 2. This is sometimes called banker's rounding, and its purpose is to compensate for a bias that could accumulate when adding many such numbers together."

How do I change this to normal mathematical rounding because this "banker's rounding" is incorrect and introducing errors.

BTW: There is no "bias" in always rounding 0.5 up to the nearest integer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a99b26-258b-eaed-a447-7aff1231f40c
* Version Independent ID: 2441bf7d-8315-fefa-9951-1ff3a95816b4
* Content: [Type Conversion Functions (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/functions/type-conversion-functions#feedback)
* Content Source: [docs/visual-basic/language-reference/functions/type-conversion-functions.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/functions/type-conversion-functions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Have you looked into the different options you have with Math.Round?
https://docs.microsoft.com/en-us/dotnet/api/system.math.round#remarks

But I'll close this issue since the content is correct. You can also find the explanation on why .NET uses this convention at https://stackoverflow.com/questions/311696/why-does-net-use-bankers-rounding-as-default/6562018#6562018.
