### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15173]
The link to Outbox pattern is broken. @mvelosop can you help figure out where it should go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ab515b-a39a-983d-2a09-13ca5ccf5125
* Version Independent ID: 82f66a0e-6ad3-c419-36cb-ecc985b9b192
* Content: [Asynchronous message-based communication](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/asynchronous-message-based-communication.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @mairaw, updated, used an equivalent link to a recent blog post.
