### ISSUE TITLE
gRPC book review

### ISSUE THREAD

**Issue by shirhatti** [dotnet/docs#15175]
I'm filing this issue to make an list of changes to the gRPC book, I'd like to see before we can remove the preview moniker:

I expect this list wouldn't be exhaustive and we may publish revisions/errata in the future.

I'm incorporating feedback from https://github.com/dotnet-architecture/eBooks/issues/4 in my issue as issues I'd like to see addressed before we publish

- [x] gRPC is based on Stubby. This incorrectly says Stubby has renamed to gRPC https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/grpc-overview.md#L18
- [x] Somewhat misleading since HTTP/2 isn't a network protocol, it's an application protocol that operates on TCP. gRPC can operate on other transports. It's just that grpc-dotnet doesn't support it today https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/approach.md#L23
- [x] https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/wcf-bindings.md#L20. I'm uncomfortable with the language here. It's fair to say BasicHttpBinding is slower than other bindings such as NetTCP. I'd avoid saying very slow and instead say it's slower than other bindings. I'd also rewrite this sentence to omit unnecessary adverbs. See https://docs.microsoft.com/style-guide/word-choice/use-simple-words-concise-sentences
- ~~[ ]  The Windows marketing approved way to refer to these OSes are Windows 10 October 2018 Update (for client) and Windows Server, version 1809. https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/wcf-bindings.md#L26. However, I'd omit mentioning this entirely OR mention that the grpc-dotnet client doesn't yet support this.~~
- [x] According the protobuf style-guide, field names should follow snake case. This needs to be updated- https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/protobuf-messages.md#L90
- [x] Metadata lives in the `Grpc.Core.Api` package. https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/metadata.md#L18
- [x] Replace "Modern .NET project files" with "[SDK-style .NET projects](https://docs.microsoft.com/dotnet/core/tools/csproj)" https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md#L216
- [x] The current section on generating client-code only mentions Visual Studio. For the sake of completeness, I'd mention non-VS users can use `dotnet-grpc` https://docs.microsoft.com/en-us/aspnet/core/grpc/dotnet-grpc?view=aspnetcore-3.0
- [x] Update link to sample code https://github.com/dotnet/docs/blame/master/docs/architecture/grpc-for-wcf-developers/docker.md#L12
- [ ] Remove preview note from book 😄

**Comment by markrendle** [comment]
I'll get all these fixed tomorrow.
