### ISSUE TITLE
AddHttpClient Example, Semi Colon is missing

### ISSUE THREAD

**Issue by ajaypathak** [dotnet/docs#15179]
For following code 
services.AddHttpClient<ICatalogService, CatalogService>(client =>
{
    client.BaseAddress = new Uri(Configuration["BaseUrl"])
})
    .AddPolicyHandler(GetRetryPolicy())
    .AddPolicyHandler(GetCircuitBreakerPolicy());

the semicolon is missing, I think the code should be 

services.AddHttpClient<ICatalogService, CatalogService>(client =>
            {
                client.BaseAddress = new Uri(Configuration["BaseUrl"]);

            }).AddPolicyHandler(GetRetryPolicy());

**Comment by mairaw** [comment]
Thanks for your feedback @ajaypathak! Can you let us know where did you see this problem?

**Comment by mairaw** [comment]
I think I found it: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#how-to-use-typed-clients-with-httpclientfactory

Please confirm.

**Comment by ajaypathak** [comment]
yes that is correct. thanks for fixing the doc bug.
