### ISSUE TITLE
Accessibility problems with the last image

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15181]
I see two accessibility issues with the last image:

- The image contains useful information that screen readers won't be able to read. Wouldn't be possible to convey the same information with a table instead?
- The image conveys information with color alone (https://docs.microsoft.com/en-us/style-guide/accessibility/colors-patterns-text-graphics-design). Usually you need to use a different pattern for images so you're not relying on users being able to distinguish colors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45be6d71-575d-5d8d-bcdc-b6885ddbb487
* Version Independent ID: 7c37b77a-63fc-4fb4-ae32-02ac9c09e1c8
* Content: [Choosing Azure compute platforms for container-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Yep, will redo the table in markdown.

This is a good candidate for the complex image tag for alt-text!
