### ISSUE TITLE
Fix the index.md page for the Core tools

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1518]
We need to make the following changes:

* List out the other commands (CRUD, SLN)
* List out the advanced commands and explain what they are
* Remove the section about migrating from DNX

@mairaw anything else?

**Comment by mairaw** [comment]
Ok, so we should be working on this version of the topic that doesn't mention DNX anymore:
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/

also, is there any path to update from post-preview2 topics to the latest?

**Comment by blackdwarf** [comment]
@mairaw not sure what you mean by the post-preview2 topics to the latest?

**Comment by mairaw** [comment]
@blackdwarf Preview3 to RC4 for example. hasn't csproj format changed in between releases?

**Comment by mairaw** [comment]
I think we should also enhance this section to introduce the two new terms and what they're about in a short form: https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/#types-of-application-portability

**Comment by blackdwarf** [comment]
We also need to add muxer options and general options to this page. 

@mairaw will be you be able to do this or do you want me to take a stab at it?

**Comment by mairaw** [comment]
I've started the changes here: https://github.com/dotnet/docs/blob/tools-index-page/docs/core/preview3/tools/index.md
But not done yet.

**Comment by blackdwarf** [comment]
OK, so @mairaw you will do this then. :)

**Comment by mairaw** [comment]
@GuardRex since I'm tied up with other things at the moment, please work on this one next. Thanks!

**Comment by GuardRex** [comment]
@mairaw I have an open PR that touches this doc for `dotnet vstest`, which includes enhancing the OOB command list. Any objection to rolling these changes into that PR?

**Comment by GuardRex** [comment]
@mairaw @blackdwarf 

RE: The update to include #1518

AFAICT the commands `index` doc only indirectly pertains to app types via the language on using the `dotnet` command to launch framework-dependent apps. That's documented here with a link to the app types doc. If you want more, let me know what you want and how you want it worked in here.

> add muxer options and general options to this page

I need clarification on what else is required to cover "muxer options" and "general options."

> List out the advanced commands and explain what they are

Do you want a one-sentence description added to the CLI commands section saying what each does? As I was working on this, I had two notions that dissuaded me from adding descriptions: (1) most of the commands are somewhat self-exclamatory, (2) devs really do need to look at these docs individually if they plan to work with .NET Core technology. Therefore, I was thinking perhaps it isn't very helpful to add descriptions and clutter up the list. Let me know if you want me to add the content tho, and I'll get it done.
