### ISSUE TITLE
Update for => operator

### ISSUE THREAD

**Issue by MatthewT123** [dotnet/docs#15190]
I suggest this page could be improved by updating the syntax to use the new =&gt; option for property method bodies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322a60f9-0bd8-b432-653a-069c477a93fe
* Version Independent ID: dbc29edd-b142-f2d7-4824-dec9951f32c7
* Content: [Using Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-properties.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for creating this @MatthewT123 We agree that using the modern syntax wherever possible is preferred.

I've added this to our C# update project, and added the "up for grabs" label if others are interested.

**Comment by vorphol** [comment]
I would like to pick this and submit a PR? Can I proceed?

**Comment by vorphol** [comment]
@BillWagner, can I submit PR? I am done with code snippet changes?

**Comment by BillWagner** [comment]
@vorphol Yes, submit the PR. I'll watch for it and merge it. I watch the dotnet/samples repo as well, for any code snippet changes.

**Comment by vorphol** [comment]
@BillWagner  submitted [PR](github.com/dotnet/samples/pull/1660)

**Comment by MatthewT123** [comment]
Thanks for doing this so quickly.  Oddly when I look at the original page (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties) it still shows the original content.  Is there a lag in updating the public site from changes made here?
