### ISSUE TITLE
Support for .Net Core 3.0?

### ISSUE THREAD

**Issue by Xirui** [dotnet/docs#15209]
When are we expected to see the cli tool supporting .Net Core 3.0? Thanks.

[AB#1608693](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1608693)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200d7af-ea16-7b93-5263-6a1ce41ecb3b
* Version Independent ID: e1697ee4-9d3a-e1cc-b678-cab88f1b5f86
* Content: [How to install the ML.NET Command-Line Interface (CLI) tool - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli#feedback)
* Content Source: [docs/machine-learning/how-to-guides/install-ml-net-cli.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-ml-net-cli.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @Xirui,

Thank you for your question. Since this is more of a product question, I would suggest asking it in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo
