### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by revolz** [dotnet/docs#15215]
Please provide download link for cars.csv and other datasets to make it easy for developer to follow through the sample code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d546f09c-1e0f-b036-5c93-b0640934bcdd
* Version Independent ID: dcce0234-fb4b-9622-a930-80518e6f50a3
* Content: [The auto-train command in the ML.NET CLI tool - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/reference/ml-net-cli-reference#feedback)
* Content Source: [docs/machine-learning/reference/ml-net-cli-reference.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/reference/ml-net-cli-reference.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Thank you for the suggestion @revolz. As this is a reference document, we would not generally provide a dataset. However we will look into whether we need more hands-on guidance.
