### ISSUE TITLE
Clarify if Microsoft Fakes package is still supported in .net core

### ISSUE THREAD

**Issue by mungojam** [dotnet/docs#15214]
Previously Microsoft Fakes was introduced with things like `ShimContext` that could be used to override `DateTime.Now`. I can't find any reference to how to use this with .net core or if it is still possible but web searches bring back lots of old pages:

https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#feedback)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello. I'm going to close this issue as I found this logged in the Visual Studio feedback area. https://developercommunity.visualstudio.com/idea/351467/support-microsoft-fakes-on-net-core.html

Please log your vote there and let them know how the lack of this feature impacts you. 👍

**Comment by Thraka** [comment]
@mungojam Gotcha!

You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

I'm unsure if it fits though. Suggesting that "X is not supported" when X isn't even referenced in the article feels awkward. 😄
