### ISSUE TITLE
Rewrite example using Task-based Asynchronous Pattern

### ISSUE THREAD

**Issue by gceaser** [dotnet/docs#15219]
Can this be re-written the same way the Client code we re-written to use the Task based Asynchronous Pattern?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example#feedback)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. Thanks again!

@BillWagner Would this be a good candidate for the async github project?

**Comment by BillWagner** [comment]
Good idea @Thraka  Added to the project.

**Comment by danvanderboom** [comment]
One approach to this on CodeProject. 
https://www.codeproject.com/Articles/1243360/TCP-Socket-Off-the-shelf-Revisited-with-Async-Awai
