### ISSUE TITLE
docs/core/tutorials/

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1522]
There are several related tutorials that need updating: 

- [x] target-dotnet-core-with-msbuild.
- [x] using-on-macos.md #1535 
- [x] using-on-windows.md
- [x] using-with-xplat-cli.md #1506 (See PR #1507)

**Comment by mairaw** [comment]
The one I'm updating with PR #1507 is the one under preview3 folder which in csproj should be redirected to the one you list above. So once that PR is merged, I can switch things around in csproj.

**Comment by mairaw** [comment]
The two remaining topics should just be redirected. We had done the redirection for some in csproj but somehow lost it.

**Comment by mairaw** [comment]
can you check if this one is now done @BillWagner?

**Comment by BillWagner** [comment]
Closing.  The old topics are both redirecting correctly.
