### ISSUE TITLE
Inconsistent switch usage for compiler options on links to those articles

### ISSUE THREAD

**Issue by lucasnobredev** [dotnet/docs#15222]
In "See also" section, there are two links with / in the name. I believe this is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16419eb7-66b4-751f-192a-a1f399942579
* Version Independent ID: 1364a74b-43ac-c3a7-4021-80e70cdd43db
* Content: [Walkthrough: Embed types from managed assemblies in Visual Studio](https://docs.microsoft.com/en-us/dotnet/standard/assembly/embed-types-visual-studio)
* Content Source: [docs/standard/assembly/embed-types-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/embed-types-visual-studio.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Hi @lucasnobredev! Yeah, it seems we renamed the title to use - but not the incoming links. Do you want to submit a PR to fix that?

It's not incorrect, but we settled on using - throughout our docs.

**Comment by mairaw** [comment]
This is the original PR for this work: https://github.com/dotnet/docs/pull/4138

**Comment by lucasnobredev** [comment]
Ok, @mairaw ! I found another one in [How to: Create signed friend assemblies
](https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-signed-friend). I'll try to find others to open a complete PR.

Do you prefer to continue this subject in this issue or re-open #4072?

**Comment by mairaw** [comment]
You'll probably find more by doing a search and replace on VS Code (or some other tool). Let's keep this work on this PR. I'll rename it.
