### ISSUE TITLE
Side by Side installs versus in-place updates for .NET Core

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15238]
From PR #14425 from @jamshedd 

https://review.docs.microsoft.com/en-us/dotnet/core/deploying/deployment-experiences?branch=pr-en-us-14425#side-by-side-installs-versus-in-place-updates

Not sure where to put that info now. It seems it should go somewhere under https://docs.microsoft.com/en-us/dotnet/core/versions/. 

/cc @KathleenDollard

**Comment by KathleenDollard** [comment]
I like the content!!!

Under versions seems fine.
