### ISSUE TITLE
Acquisition experiences for .NET Core

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15237]
Created based on PR #14425 from @jamshedd 

https://review.docs.microsoft.com/en-us/dotnet/core/deploying/acquisition-experiences?branch=pr-en-us-14425

@Thraka please check if this would fit the narrative you discussed with @richlander and @rowanmiller 

As-is, I don't think it fits into what we were planning.

**Comment by Thraka** [comment]
Not really. What we discussed was a rewrite of the prereqs articles to 

1. Consolidate information
2. Have the latest information
3. Point to how SDK and Runtime are different
4. Link out to the relative download/install docs.

**Comment by Thraka** [comment]
However, I was going to put those basic small sections of vs, vscode, vsmac that show the option dialogs.

**Comment by mairaw** [comment]
@richlander also mentioned articles like setting up different environments like set up your dev machine, and so forth. I think some of these would fit into that.
