### ISSUE TITLE
Package your .NET Core app

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15239]
Related to https://github.com/dotnet/docs/issues/13474

From PR #14425 from @jamshedd 

We need a new section in the .NET Core guide that talks about Packaging your app for deployment

**Comment by Thraka** [comment]
Wouldn't this just go under the Application Deployment section of the Core guide?

**Comment by mairaw** [comment]
I’m not firm on the TOC location yet. The next step would be for us to rethink the .NET Core TOC.

**Comment by Thraka** [comment]
Gotcha, and I agree.

I would assume though that this would stay with the other articles in that current section, yes?
