### ISSUE TITLE
Mention that PreBuiltEvent and PostBuildEvent shouldn't be used (since common macro properties don't work there)

### ISSUE THREAD

**Issue by mjrousos** [dotnet/docs#15248]
Docs about the new project file format should mention that macro properties like $(ProjectDir) [don't work](https://github.com/dotnet/sdk/issues/677#issuecomment-280164111) in PreBuildEvent and PostBuildEvent properties when using SDK-style projects. Instead, users should create new targets (using the 'exec' command) that run before or after the PreBuildEvent and PostBuildEvent targets.

Visual Studio has [already been updated](https://github.com/dotnet/project-system/issues/1569#issuecomment-360951567) so that any pre/post build commands entered through the project properties UI will create new targets instead of using PreBuildEvent/PostBuildEvent directly. We should add a note to the docs, though, explaining this so that users migrating old csproj file to the new SDK-style format know that they will need to change PreBuildEvent and PostBuildEvent usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by StingyJack** [comment]
An XSD would probably be useful for this.
