### ISSUE TITLE
Multiple switch cases?

### ISSUE THREAD

**Issue by donatasj87** [dotnet/docs#15241]
Is there any way to implement multiple switch statements?
Could not find any effective way to do it and the naturally looking code below does not seem to work:
```
colorBand switch
    {
        Rainbow.Red,
        Rainbow.Orange => new RGBColor(0xFF, 0x7F, 0x00),
        _              => throw new ArgumentException(message: "invalid enum value", paramName: nameof(colorBand)),
    };

```
But in the classic switch we could have done it like this:

```
 switch (colorBand)
    {
        case Rainbow.Red:
        case Rainbow.Orange:
            return new RGBColor(0xFF, 0x7F, 0x00);
        default:
            throw new ArgumentException(message: "invalid enum value", paramName: nameof(colorBand));
    };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
There currently isn't a way to do this, though one is planned for C# 9.0 (https://github.com/dotnet/csharplang/issues/2850):

```c#
colorBand switch
    {
        Rainbow.Red or Rainbow.Orange => new RGBColor(0xFF, 0x7F, 0x00),
        _ => throw new ArgumentException(message: "invalid enum value", paramName: nameof(colorBand)),
    };
