### ISSUE TITLE
Storing custom.config in %appdata%

### ISSUE THREAD

**Issue by DeltonLee** [dotnet/docs#15247]
If I want to store my custom.config file in the %appdata% folder how do I reference it within an app.config file?  Using %appdata% or ${AppData} does not seem to work.  This is a widely used environmental variable, so there really should be a way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea24ffb0-1e4a-4c73-c566-18b67e3bd69c
* Version Independent ID: 1d1c4a41-9dfd-82f9-ed0c-993c45b16b25
* Content: [&lt;appSettings&gt; element for &lt;configuration&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration)
* Content Source: [docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@DeltonLee 

Hello! The app.config file doesn't expand environment variables. The docs for `file` attribute point out the following:

>The path specified is relative to the main configuration file. For a Windows Forms application, this is the binary folder (such as /bin/debug), not the location of the application configuration file. For Web Forms applications, the path is relative to the application root, where the web.config file is located.

So this value has to be a relative path and an explicit value (not expanded via environment variables).

I'm going to close this question. Thanks!
