### ISSUE TITLE
How to compile multiple .txt or .resx files into a single binary .resources file?

### ISSUE THREAD

**Issue by HammondWen** [dotnet/docs#15261]
Hi,
I am wondering how to compile multiple .txt or .resx files into a single binary .resources file. Is there any Al.exe option to do that? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3ff457-56ee-b368-af21-d37bdea825b2
* Version Independent ID: 96d617db-6ad2-594e-643a-4006188de390
* Content: [Creating Satellite Assemblies for Desktop Apps](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-satellite-assemblies-for-desktop-apps#feedback)
* Content Source: [docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md](https://github.com/dotnet/docs/blob/master/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
It doesn't seem so. I would merge those into a single file. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow.

I'm going to close the issue. 

Thanks.
