### ISSUE TITLE
Where is the Juice.

### ISSUE THREAD

**Issue by hochl** [dotnet/docs#15281]
Later parts of this article, after "Await tasks efficiently", are missing pouring the juice:
    
    Juice oj = PourOJ();
    Console.WriteLine("oj is ready");

Does this mean a good asynchronous breakfast is missing juice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index#await-tasks-efficiently)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by santhoshrajr** [comment]
Can i take this issue?

**Comment by BillWagner** [comment]
@santhoshrajr Yes, you can take it. Thank you.  I'll watch for a pull request.

**Comment by santhoshrajr** [comment]
@BillWagner I was unable to find the path of code sample to update it. Can you help me on it. I was trying to navigate to the path in mark down but it throws a 404.
![image](https://user-images.githubusercontent.com/14833988/67162190-c1af1480-f32f-11e9-97c9-6a8c4aef9666.png)
![image](https://user-images.githubusercontent.com/14833988/67162197-d7243e80-f32f-11e9-83c4-dde30da7e561.png)

**Comment by BillWagner** [comment]
@santhoshrajr All the sample code is in our samples repository. The versions of this sample are all [in this folder](https://github.com/dotnet/samples/tree/master/snippets/csharp/tour-of-async)

**Comment by santhoshrajr** [comment]
@BillWagner Thanks. Sent out a PR for the fix
