### ISSUE TITLE
Some grammatical corrections

### ISSUE THREAD

**Issue by mgoldshteyn** [dotnet/docs#15319]
It may terminate the thread, it may terminate the program, or it may leave the program in an undetermined state. None of those are good outcomes.

Should read:

It may terminate the thread, the process that owns the thread, or leave the process in an indeterminate state. All of these potential outcomes are highly undesirable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cb74e28-b327-0f9f-5fa5-882a00d10ceb
* Version Independent ID: 645a8a12-a026-bee9-7501-e8ec4a32ce31
* Content: [The Updated .NET Core Event Pattern](https://docs.microsoft.com/en-us/dotnet/csharp/modern-events#feedback)
* Content Source: [docs/csharp/modern-events.md](https://github.com/dotnet/docs/blob/master/docs/csharp/modern-events.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @mgoldshteyn 
I've added this to our backlog for when we next update this article, and I've added the "up for grabs" label, if you'd like to submit a PR with those changes.
