### ISSUE TITLE
Well put together walkthrough of C#

### ISSUE THREAD

**Issue by Virtruvian1** [dotnet/docs#15327]
It walks you into the basics of C# that will later be used as the fundamentals for developing code. Compared to most coding tutorials this is one of the best ones that I have come across. If there is questions on the topics covered there are links leading the viewer to more information about it and they may go as deep as they want. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thanks again for the nice comments 😄 Glad these helped you!
