### ISSUE TITLE
Increased variety of type test pattern examples

### ISSUE THREAD

**Issue by bender2k14** [dotnet/docs#15329]
I was confused about the pattern matching case called type test pattern.  I mistakenly thought that `as identifier` was required because all the examples included that optional syntax.  Several people quickly responded [a related GitHub issue I created](https://github.com/dotnet/fsharp/issues/7740) to kindly point out my error.

Can the examples for type test pattern be expanded to include an example that does not include the optional `as identifier` syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3ed054-03c9-375f-403b-68f0356d5870
* Version Independent ID: 3c167003-13e8-359b-e919-693258e7f48b
* Content: [Pattern Matching - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching)
* Content Source: [docs/fsharp/language-reference/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/pattern-matching.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by bender2k14** [comment]
I left a comment on your most recently commit
https://github.com/dotnet/docs/commit/140b2328a804fffb16f48d32b51b29d63bd40f88#comments

**Comment by mairaw** [comment]
I've opened PR https://github.com/dotnet/docs/pull/15483 since the other one had been merged already
