### ISSUE TITLE
Awesome Tutorial!

### ISSUE THREAD

**Issue by Virtruvian1** [dotnet/docs#15328]
This is a good explanation of working with numbers in coding. Most documentation of coding leaves it with no explanation. This tutorial isn't meant to go more in depth as it's written for 'beginners.'  I believe there are a number of books listed on Amazon if you wish for much deeper explanations of how the coding work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thanks!
