### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by mcfowler** [dotnet/docs#15330]
Need an example of how using the Nullable element in the csproj file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @mcfowler 

That is covered in other article, but it should be here as well.  The element to add is:

```xml
<Nullable>enable</Nullable>
```

I've added the "up for grabs" if you want to submit a PR for this fix.
