### ISSUE TITLE
Review `dotnet build` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15331]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build

**Comment by Thraka** [comment]
@BillWagner @mairaw Was this label approved? Accidental add by @dsplaisted perhaps?

**Comment by BillWagner** [comment]
@Thraka I'm unaware of this label.

**Comment by dsplaisted** [comment]
The label is intentional.  The CLI team is going to go through the CLI documentation topics and review them to see if they're up-to-date, accurate, etc.  I discussed using a project in this repo to track this with @mairaw, though I don't know if I specifically discussed creating a new label.
