### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by dieselbanger** [dotnet/docs#15348]
I tried to follow this tutorial line by line, but I get the following exception when running the application:

DirectoryNotFoundException: Could not find a part of the path '...\bin\Debug\netcoreapp2.1\assets\images\tags.tsv'.
-&gt; on line: var model = pipeline.Fit(trainingData);

Correctly enough, there is no 'images' folder in the assets downloaded from the link in the beginning of the tutorial.

I tried copying the contents from the 'inputs-train\data' folder into an 'images' folder in the correct location, but this gives be another exception:
System.ArgumentException: 'Parameter is not valid.'
-&gt; on line: var prediction = predictor.Predict(imageData);

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Generate an ML.NET image classification model from a pre-trained TensorFlow model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Thank you for pointing this out @dieselbanger. The location of the assets zip file has been upated in #15357
