### ISSUE TITLE
unable to read file from Azure storage when running in local 

### ISSUE THREAD

**Issue by aruntyagiTutu** [dotnet/docs#15344]
exception 
java.io.IOException: No FileSystem for scheme: wasbs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed1a382-383b-fef6-18d0-80e3e5961224
* Version Independent ID: cd88f771-4c2b-6c9f-7b54-14c7f51f187a
* Content: [What is .NET for Apache Spark?](https://docs.microsoft.com/en-us/dotnet/spark/what-is-apache-spark-dotnet#feedback)
* Content Source: [docs/spark/what-is-apache-spark-dotnet.md](https://github.com/dotnet/docs/blob/master/docs/spark/what-is-apache-spark-dotnet.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by elvaliuliuliu** [comment]
@aruntyagiTutu Thanks for your question. Could you provide more details
 (such as command you use, a snippet of code you run, and the full log) for us to better troubleshoot? Thanks!
