### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Legends** [dotnet/docs#15364]
> The parent process then sends a user-supplied string to the child process. The string is displayed to the console in the child process.

When creating these two projects `server` and `client` I only have to start the `server` project as its `exe` calls the `client` process (client.exe).

The `client` process is the `child` process in my case, but this console app is not visible during execution, therefore the above sentence makes no sense here:

> The string is displayed to the console in the child process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8d1d0b-4416-60f7-d609-a0c2edf0756a
* Version Independent ID: d473211b-eeda-a0f6-1979-e8b12d3251ed
* Content: [How to: Use Anonymous Pipes for Local Interprocess Communication](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-anonymous-pipes-for-local-interprocess-communication)
* Content Source: [docs/standard/io/how-to-use-anonymous-pipes-for-local-interprocess-communication.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-use-anonymous-pipes-for-local-interprocess-communication.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@Legends The child process does not get a separate console, it uses the console of the parent process.  I just now ran the example to verify that it does work as described. I'm closing this issue now, but feel free to reopen if you have additional questions.
