### ISSUE TITLE
PreserveCompilationContext project property should be documented

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [dotnet/docs#15368]
There's a .NET Core-specific project property `PreserveCompilationContext`. It causes publish operation to copy used reference assemblies for the target platform into *ref* subdirectory of output directory (via SDK target [Microsoft.NET.PreserveCompilationContext.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PreserveCompilationContext.targets)). This is mostly used internally by ASP.NET, but sometimes people might want to set it manually in case they want to compile something at runtime and therefore will need reference assemblies.

It is included in [MSBuild common types schema](https://github.com/microsoft/msbuild/blob/master/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L1661):

```xml
<xs:element name="PreserveCompilationContext" substitutionGroup="msb:Property" type="msb:boolean">
 <xs:annotation>
  <xs:documentation>
     <!-- _locID_text="PreserveCompilationContext" _locComment="" -->
      Value indicating whether reference assemblies can be used in dynamic compilation
   </xs:documentation>
 </xs:annotation>
</xs:element>
```
This property should be documented in [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tdykstra** [comment]
@MSDN-WhiteKnight Thanks for the suggestion -- I'm adding the issue to our backlog.
