### ISSUE TITLE
.NET Framework Add-in model seems to be deprecated

### ISSUE THREAD

**Issue by pleonex** [dotnet/docs#15369]
This guidelines says _Consider Using the .NET Framework Add-In Model_ but in the link provided ([this](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/bb384200(v=vs.100))) it says that API is already deprecated (I guess in favor of MEF2). I think it should be updated or removed.

By reading the whole guideline, I have the feeling there is no solution to implement the use case of plugins. Because we don't know the full name of the external assemblies, we need to load them from a file / byte array but methods like LoadFrom and LoadFile are not recommended to use.

**Edit**: maybe recommend something as [Gendarme](https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.BadPractice.AvoidCallingProblematicMethodsRule(2.10)) says about getting the `AssemblyName` to do some validations like public key and then use `Assembly.Load`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8732511-e24f-2c9c-57c8-ce469c351e94
* Version Independent ID: 8806bdc9-6cf1-cbcb-0e47-f6edbdcfd59c
* Content: [Best Practices for Assembly Loading](https://docs.microsoft.com/en-us/dotnet/framework/deployment/best-practices-for-assembly-loading)
* Content Source: [docs/framework/deployment/best-practices-for-assembly-loading.md](https://github.com/dotnet/docs/blob/master/docs/framework/deployment/best-practices-for-assembly-loading.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@karelz Who could help with this issue?

**Comment by alexbuzzbee** [comment]
+1 for `AssemblyName` + `Assembly.Load`. `MetadataLoadContext` might or might not be handy too.
