### ISSUE TITLE
"List of behavioral changes/compat breaks and deprecated/legacy APIs at GitHub" haven't been provided

### ISSUE THREAD

**Issue by runceel** [dotnet/docs#15365]
CoreFx team decided to remove the document from them repo.
So, the link is breaking.

https://github.com/dotnet/corefx/issues/36057

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e44818-fc25-7210-c430-7c87b84825eb
* Version Independent ID: 2f40ef4c-ea4b-ccb5-3b7f-9d02c3b7ab82
* Content: [.NET Framework technologies unavailable on .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#feedback)
* Content Source: [docs/core/porting/net-framework-tech-unavailable.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/net-framework-tech-unavailable.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @runceel. Now that we've added breaking changes to the docs, we can update that link.
