### ISSUE TITLE
Error when running this example - .NET Core 3.1 console applications

### ISSUE THREAD

**Issue by Legends** [dotnet/docs#15367]
1. Start named pipe server.
2. Start named pipe client without `args`.

**Console output client process:**

```
*** Named pipe client stream with impersonation example ***

Spawning client processes...


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Unhandled Exception:Unhandled Exception: Unhandled Exception:  System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86675e7-4bfb-707d-fe36-c02da2023342
* Version Independent ID: ee821843-1cad-0455-f278-1194b88dd0b0
* Content: [How to: Use Named Pipes for Network Interprocess Communication](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-named-pipes-for-network-interprocess-communication)
* Content Source: [docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Legends** [comment]
I solved the error above by adding an app.config file to my client project:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
            <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.3.1.0" />
        </dependentAssembly>      
    </assemblyBinding>
</runtime>
```

**But now I get:**

> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

**Comment by Legends** [comment]
Installing `System.Runtime v.4.3.1.0` and adding this `app.config` to my client project also didn't help:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
      </dependentAssembly>      
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by tdykstra** [comment]
@JeremyKuhne, @carlossanlop Can you advise how to run this example?

**Comment by JeremyKuhne** [comment]
The code needs updated. `Environment.CommandLine` returns the name of the dll on .NET Core. This can be done by adding the following line in the client after getting the command line:

``` C#
currentProcessName = Path.ChangeExtension(currentProcessName, ".exe");
```

https://github.com/dotnet/coreclr/issues/20562 and https://github.com/dotnet/corefx/issues/29014 discuss this behavior.

cc: @jkotas

**Comment by tdykstra** [comment]
@Legends Thanks for closing the issue, but I'm going to reopen it to put it on our backlog as a reminder to update the doc.

**Comment by SumanjaliDamarla** [comment]
Hi @tdykstra 

I think the code needs to be changed [here](https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.IO.Pipes.NamedPipeClientStream_ImpersonationSample1/cs/Program.cs).
Can I proceed with making the changes?

**Comment by tdykstra** [comment]
@SumanjaliDamarla Yes, please do, thanks!
