### ISSUE TITLE
Thread-safe delegate invocation fix.

### ISSUE THREAD

**Issue by hochl** [dotnet/docs#15371]
I think the following example needs a fix:

var handler = this.PropertyChanged;
if (handler != null)
{
    handler.Invoke(...); // was: handler(…);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#feedback)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
`handler.Invoke(...)` is correct, but `handler(...)` is also correct and a shorter alternative. I believe if one doesn't use the null-conditional operator one usually uses the shorter syntax, as if calling a method or function

**Comment by BillWagner** [comment]
@pkulikov is correct. I'm leaving this open, as a preferred fix would be to use the more recent thread safe `?.` invocation:

```csharp
PropertyChanged?.Invoke(...);
```

I've added the up-for-grabs label if you want to submit a PR @hochl. We'll help you with the process. Otherwise, I've added this to our backlog to update when we next update this article.

**Comment by pkulikov** [comment]
@BillWagner the article uses the thread-safe way. That snippet shows how the things were done before the null-conditional operator. After that, the modern way is presented. I don't think the article needs updates

**Comment by pkulikov** [comment]
We are talking about this section:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#thread-safe-delegate-invocation

**Comment by BillWagner** [comment]
Thanks @pkulikov (I read the issue, but didn't check back at the content. 😞 )  

I'll close this. The current article is correct.

**Comment by BrayanKhosravian** [comment]
Could the team please add some more detailed explanation about the topic `thread-safe-delegate-invocation`
I mean thats a very interesting and essential topic imo. And there is only one line written:
`"Use the ?. operator to check if a delegate is non-null and invoke it in a thread-safe way (for example, when you raise an event), as the following code shows"`

Could the team explain why the `?.` operator makes the invocation thread safe?
Sincerely and thanks in advance.
