### ISSUE TITLE
WASM Description is wrong

### ISSUE THREAD

**Issue by roberto-t92** [dotnet/docs#15372]
> using a JavaScript library called WebAssembly

wasm isn't a javascript library

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad8df5d-9295-d659-a561-ec9cabd5b61f
* Version Independent ID: 7ee71103-d997-140e-2d35-d9f2a3913e09
* Content: [Choose between traditional web apps and single page apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps#feedback)
* Content Source: [docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@ardalis @mvelosop can you look at this feedback?

**Comment by roberto-t92** [comment]
> WebAssembly (abbreviated Wasm) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable target for compilation of high-level languages like C/C++/Rust

It is enough to just remove the javascript part

> ... this code to be delivered to the browser and executed client-side using WebAssembly

**Comment by mairaw** [comment]
Would you like to submit a pull request to fix that?

Instructions can be found at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.

**Comment by jaywahr** [comment]
@mairaw @roberto-t92  saw the `up-for-grabs` label. Can I submit a pull request for `Hacktoberfest`? New to open source.

**Comment by mvelosop** [comment]
Hi @jaywahr, thanks for the offering and nice that you targeted the `up-for-grabs`

There's already a PR for this issue, but you can always submit a PR for any other issue you feel like working on. They'll all be reviewed, so no need to worry 😉
