### ISSUE TITLE
DoStackSnapshot Support for .NET Core on Linux

### ISSUE THREAD

**Issue by vashisthaa** [dotnet/docs#15376]
Hi,

Is DoStackSnapshot supported for .NET Core on Linux? If not what is the plan for doing the same?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0d63b1-9436-33c5-6562-3c2821db32f5
* Version Independent ID: 24a21082-b959-d660-2522-32e06e7a307d
* Content: [ICorProfilerInfo2::DoStackSnapshot Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo2-dostacksnapshot-method#feedback)
* Content Source: [docs/framework/unmanaged-api/profiling/icorprofilerinfo2-dostacksnapshot-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/icorprofilerinfo2-dostacksnapshot-method.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your question @vashisthaa. @tommcdon this is related to e-mail I sent this morning about ownership and having native APIs identified for Core as well.

**Comment by tommcdon** [comment]
Adding @davmason who is the owner of the API

**Comment by davmason** [comment]
Hi @vashisthaa,

`DoStackSnapshot` is supported on Linux starting with coreclr 3.0. We added new apis `ICorProfilerInfo10::SuspendRuntime` and `ICorProfilerInfo10::ResumeRuntime` to pause the runtime without doing a GC, which will leave the threads in a walkable state.

The issue on Linux is that there is no equivalent of the `SuspendThread` api on Windows, so you cannot do async sampling in the same way you can on windows. The `ICorProfilerInfo10::SuspendRuntime` api lets you pause managed threads for sampling.

**Comment by vashisthaa** [comment]
Thank you for the confirmation! I would definitely try with .NET Core 3.0 and let you know if I face any issues.

**Comment by vashisthaa** [comment]
Hi @davmason , I see in another post/issue the attach support is resolved for .NET Core. However we are facing technical challenge. Can you please guide us on the following?
=========================
ReJIT after attach reports a success status but does not trigger a new JIT event for any methods. The new ReJIT API has the same issue.
ngen modules are already loaded which prevents some native methods from producing JIT events.
=======================================
https://github.com/dotnet/coreclr/commit/b314ed86b11756834b0936e56c3d841e7407f81d

**Comment by davmason** [comment]
Hi @vashisthaa, I created https://github.com/dotnet/coreclr/issues/27781 to talk about this, the docs repository is not the right place for this conversation but I am happy to help
