### ISSUE TITLE
Fail to run fsi.exe

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#15383]
@jkugiya commented on [Thu Oct 24 2019](https://github.com/dotnet/docs.ja-jp/issues/855)

&gt; To run F# Interactive from the console, run fsi.exe. 

&gt; Scripts use the file extension .fsx or .fsscript. Instead of compiling source code and then later running the compiled assembly, you can just run fsi.exe

Now you need to use `dotnet fsi`, right? I received the error message `%1 is not a valid win32 application` when I used `fsi.exe` directly.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3ea5b069-0d43-f577-3f95-fde5aaf919d5
* Version Independent ID: 0ea5685e-45cc-06d2-3985-cffb530f9e67
* Content: [F# Interactive (fsi.exe) のリファレンス - F#](https://docs.microsoft.com/ja-jp/dotnet/fsharp/tutorials/fsharp-interactive/#feedback)
* Content Source: [docs/fsharp/tutorials/fsharp-interactive/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/tutorials/fsharp-interactive/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

---

@srvbpigh commented on [Thu Oct 24 2019](https://github.com/dotnet/docs.ja-jp/issues/855#issuecomment-545723076)

Hello, @jkugiya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because it may be related to the original documentation
best

**Comment by cartermp** [comment]
This will require a bit of a think about how to structure the article, since it was written for a Windows-only/VS-installing audience: https://github.com/dotnet/docs/blob/master/docs/fsharp/tutorials/fsharp-interactive/index.md

**Comment by mairaw** [comment]
Maybe make that clear on the beginning who's your intended audience and what are the prereqs?
