### ISSUE TITLE
inside?

### ISSUE THREAD

**Issue by hochl** [dotnet/docs#15384]
"where a member is treated like a data item from outside the class, but like a method on the side."

-&gt;

"where a member is treated like a data item from outside the class, but like a method on the inside."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc06ead-fe51-85db-1340-87f6473db769
* Version Independent ID: 4f2c312e-609c-a643-4af6-c12c6cf74738
* Content: [Indexers](https://docs.microsoft.com/en-us/dotnet/csharp/indexers#feedback)
* Content Source: [docs/csharp/indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/indexers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this @hochl 

I've added it to our backlog to fix when we next update this article.

I've also added the "up for grabs" label. If you'd like, you can submit a PR that fixes this change. You can click the pencil icon on the article, and make edits directly in the browser to submit the fix. For small edits like these, that may be quicker than writing an issue.
