### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by rookie0jnr** [dotnet/docs#15390]
The article refers to "Collections in C#" link, but there isn't such link.
Moreover the next tutorial is not named "Collections in C#".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356f32d2-2574-9d48-a096-aef9fc21112d
* Version Independent ID: 49ae4e9d-cd57-917c-8795-71ad57858d5d
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/interpolated-strings?tutorial-step=5#feedback)
* Content Source: [docs/csharp/tutorials/exploration/interpolated-strings.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/exploration/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for spotting this @rookie0jnr 

That link and related sentences should be removed. This tutorial moved from the "introductory" section to the fundamentals sections and those no longer apply.
