### ISSUE TITLE
Great Article

### ISSUE THREAD

**Issue by dpbeaumont** [dotnet/docs#15394]
Covers a lot of bad practices I have seen previously, very informative and easy to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ed82a3-99c1-0893-4e81-d095b4757ecc
* Version Independent ID: 3765200b-43e5-441c-b290-709c34dd2f6d
* Content: [Asynchronous programming - C#](https://docs.microsoft.com/en-us/dotnet/csharp/async#feedback)
* Content Source: [docs/csharp/async.md](https://github.com/dotnet/docs/blob/master/docs/csharp/async.md)
* Product: **dotnet-csharp**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by cartermp** [comment]
Thanks!
