### ISSUE TITLE
Which is preferred?

### ISSUE THREAD

**Issue by PatrickRyder** [dotnet/docs#15393]
A link to a best-practises article explaining, say, when to use 'Object' and when to use 'object' would be extremely useful. I was always under the impression the built-in types were preferred unless an explicit type was required (e.g. I get a squiggle under 'String.Empty', telling me to simplify it to 'string.Empty'.  But lately, when Visual Studio inserts code (e.g. for an event handler), it uses the .NET types like this: 'MyObject_Changed( Object sender, EventArgs e ).  So I'm confused...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14c8f6f-352e-befa-a4a8-b1409b812a59
* Version Independent ID: c039d56c-a74b-a8ce-75f6-0f3b9196119a
* Content: [Built-in types table - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/built-in-types-table)
* Content Source: [docs/csharp/language-reference/keywords/built-in-types-table.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/built-in-types-table.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
It's a matter of style. Just be consistent and stick with one of the two ways.
You can see the styleguide for corefx [here](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

**Comment by BillWagner** [comment]
The style guide @Youssef1313 cites prefers the built-in types to the library names. We generally follow that in our docs. (There are some exceptions where the focus of the article is on the library type). 

Tagging @mikadumont on this issue. Should this be an issue on the cited refactoring?
