### ISSUE TITLE
Substring()?

### ISSUE THREAD

**Issue by SvendK** [dotnet/docs#15391]
Hi - what about substring?
Substring is a bit the opposite of Remove, as it instead of returning a substring from beginning to a position, it returns a substring from a position to the end (or x characters). But really, why a Remove-function. Substring is pretty known in a lot of languages and it can do the remove function easily.

Also, the paragraph under Remove about Replace, shouldn't this have it's own headline and table of contents item?

It would be great if this page showed a list of all string modification operations, that returns a substring (trim also returns a substring).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd91d4c1-d713-b8f1-958f-3547a5150428
* Version Independent ID: 0a6a2496-ca04-fc7e-777f-8d2ef7bef1a6
* Content: [Trimming and Removing Characters from Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/trimming)
* Content Source: [docs/standard/base-types/trimming.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/trimming.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@SvendK  Thanks for the question. Substring doesn't fit in this doc because it doesn't remove anything from the source string; it's not a string modification operation.

However Replace does deserve an H2 heading, and I've created a pull request to add that.
