### ISSUE TITLE
open statements

### ISSUE THREAD

**Issue by johnalgo** [dotnet/docs#15420]
"open Microsoft.Azure.Storage" does not work for me.

"open Microsoft.WindowsAzure.Storage" seems correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114a6d66-f77b-19a9-4e0d-ff46ced10228
* Version Independent ID: 60721783-7fa5-aed0-d823-3935ebc90b7b
* Content: [Get started with Azure Table storage using F#](https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-on-azure/table-storage#feedback)
* Content Source: [docs/fsharp/using-fsharp-on-azure/table-storage.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-on-azure/table-storage.md)
* Product: **dotnet-fsharp**
* GitHub Login: @sylvanc
* Microsoft Alias: **phcart**

**Comment by Youssef1313** [comment]
https://github.com/Azure/azure-storage-net/blob/master/Common/changelog.txt#L27

> Changes in 10.0.0:
> 
> - All: Namespace change from Microsoft.WindowsAzure.Storage.* to Microsoft.Azure.Storage.*, required for SxS with pre-9.4 versions of the library.

**Comment by Youssef1313** [comment]
I'm not much sure, but I think the error in the article is in the following:

> Next, use a package manager such as Paket or NuGet to install the WindowsAzure.Storage package and reference WindowsAzure.Storage.dll in your script using a #r directive. Do it again for Microsoft.WindowsAzure.ConfigurationManager in order to get the Microsoft.Azure namespace.

Did you try to install the following packages instead of `WindowsAzure.Storage` ?

```
Microsoft.Azure.Storage.Blob
Microsoft.Azure.Storage.File
Microsoft.Azure.Storage.Queue
```

**Comment by mairaw** [comment]
Yeah, it seems that the package reference should also be updated. @cartermp would know for sure.
