### ISSUE TITLE
Add parameter for tuning unbalanced datasets on binary and multiclass datasets

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#15423]
Some things are not addressed as they may not be possible in the current release. I feel that these might be important. 2 things come to mind

1. using the mlnet-cli allows to perform some "brute-force" hyperparameter tuning, however if one has an unbalanced dataset I feel that some options may be explored more efficiently. Having a parameter indicating that an unbalanced dataset is used may be important to get a better result.

2. Providing the metric to use when hyperparameter tuning could result in a better model. This option is available in the API, should be "easy" to add to the cli as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e15c3f-305d-8d73-5ad2-a39ae9af34d6
* Version Independent ID: 55c5d866-1a98-4add-e700-39c63a2c81bc
* Content: [How-To: Improve model accuracy - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/improve-machine-learning-model-ml-net)
* Content Source: [docs/machine-learning/resources/improve-machine-learning-model-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/improve-machine-learning-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @PeterPann23 ,

Great suggestions. Since these comments are more related to the product, I would recommend opening an issue in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo with these suggestions.

**Comment by PeterPann23** [comment]
actually, I'd like to see these as parameters at the cli, the api already supports it.

**Comment by luisquintanilla** [comment]
@CESARDELATORRE is the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo the best place to add these suggestions?

**Comment by CESARDELATORRE** [comment]
This issue should be open at the ML.NET repo:
https://github.com/dotnet/machinelearning/issues
