### ISSUE TITLE
Document why you might get “No executable found matching command “dotnet-migrate” error

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1543]
If you get an error, “No executable found matching command `dotnet-migrate`:
Run dotnet --version to see which version you are using. `dotnet-migrate` requires .NET Core CLI  RC3 or higher. 
You’ll get this error if you have a global.json file in the current or parent directory and the “sdk” version set to an older version.

/cc @blackdwarf @Rick-Anderson

**Comment by blackdwarf** [comment]
@mairaw should this be a part of the overall migration docs?

**Comment by mairaw** [comment]
Yes @blackdwarf. I envision this being part of the migration topic on a section about FAQ/commons issues/etc.
