### ISSUE TITLE
error in starting the windows service

### ISSUE THREAD

**Issue by darealagung** [dotnet/docs#15455]
I did compile/publish and install the windows service successfully but when i started it i got the following error:
"Error 2: The System cannot find the file specified" 
Also, what is the proper way in setting the eventlog inside appsettings.json? I added the following:
"EventLog": {
      "LogName": "MyLogName",
      "SourceName": "My App"
    }

is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c957b4-4da9-2cda-b08e-ce78e5333768
* Version Independent ID: 2bf00fa5-70c1-b1a0-45c2-5a201f597066
* Content: [Self-hosted gRPC applications - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/self-hosted#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/self-hosted.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/self-hosted.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @darealagung. @shirhatti can you look at this?
