### ISSUE TITLE
C# version 6.0 was released with 2015 not 2013.

### ISSUE THREAD

**Issue by marekr** [dotnet/docs#15463]
&gt;With version 6.0, released with Visual Studio 2013,

AFAI, this was with 2015 not 2013.

https://devblogs.microsoft.com/csharpfaq/new-features-in-c-6/
&gt;C# 6 is the version of C# that ships with VS 2015 Preview. 

and even

https://devblogs.microsoft.com/csharpfaq/no-new-c-and-vb-language-features-in-vs-2013/
&gt;No new C# and VB Language Features in VS 2013

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-60)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this @marekr 

You are correct. I've added this issue to our backlog, and added the "up for grabs" label. If you'd like to make a PR for this fix, I'll watch for it. Otherwise, I'll fix it later this month.
