### ISSUE TITLE
Field numbers in message

### ISSUE THREAD

**Issue by win32nipuh** [dotnet/docs#15464]
Is there really  1 and 1? May be the field numbers should be unique like 1 and 2?

```proto
message Order {
    message Attributes {
        map<string, string> values = 1;
    }
    repeated Attributes attributes = 1;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614ee70b-64d7-47c6-0069-fdc514cf54dc
* Version Independent ID: ccb7f8ce-85cd-f725-2dd9-3244f0da7689
* Content: [Protobuf maps for dictionaries - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-maps)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-maps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-maps.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @win32nipuh. @shirhatti can you look at this feedback?

**Comment by shirhatti** [comment]
The following lines only define the nested message type `Attributes`. The field number number for values only applies in the context of the `Attributes` message.
 
```proto
    message Attributes {
        map<string, string> values = 1;
    }
```

The field number used in a message should not be re-used in the same message. However, fields in different messages can have the same field number. Hence, the field number for the `attributes` field is perfectly legal in the `Order` message.

**Comment by Oleg26Dev** [comment]
@shirhatti Thank you, now it is clear.
