### ISSUE TITLE
Update .net Core 2.2 to 3.0

### ISSUE THREAD

**Issue by ivysrono** [dotnet/docs#15487]
- simple edit TFM
For example:
https://github.com/dotnet/samples/blob/master/csharp/classes-quickstart/classes.csproj#L5

`<TargetFramework>netcoreapp2.2</TargetFramework>`

- Incompatible
For example:
https://github.com/dotnet/samples/tree/master/csharp/getting-started/console-teleprompter

**Comment by mairaw** [comment]
@BillWagner what do you think given that 2

**Comment by ivysrono** [comment]
Maybe we need new issue that update .Net to newest like .Net Core3.1 or .Net 5.
