### ISSUE TITLE
Update for ASP.NET Core 3.x

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#15480]
Please update for ASP.NET Core 3.x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
This was completed in another PR.
