### ISSUE TITLE
Version of dotnet project for add command. 

### ISSUE THREAD

**Issue by borys86** [dotnet/docs#15495]
Is it possible to specify the version of dotnet core project using dotnet sln[] add project command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#feedback)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your question @borys86. The version is specified in the project not in the solution and the project needs to exist already in order for you to add, so the answer to this would be no.

I hope this helps.
