### ISSUE TITLE
Review `dotnet help` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15509]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd894ec4-7531-06dd-9ae8-26b7e6f0dcea
* Version Independent ID: 37b93f10-64fe-bf7a-6cf9-3b7172ebccd1
* Content: [dotnet help command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-help)
* Content Source: [docs/core/tools/dotnet-help.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-help.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@dsplaisted This issue didn't get added to the project at first, so it was missed when we reviewed the other articles.  There is very little content in [this article](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-help), and it won't take long to review.  Can you review it or recommend a reviewer?

**Comment by dsplaisted** [comment]
@tdykstra Looks good
