### ISSUE TITLE
Review `dotnet pack` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15518]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

**Comment by sfoslund** [comment]
Looks good overall- @KathleenDollard seems to have [a change](https://github.com/dotnet/docs/compare/KathleenDollard-patch-1) that will fix #9354. @KathleenDollard is that change ready to merge?

**Comment by tdykstra** [comment]
#13281 on this article is awaiting an answer.

**Comment by sfoslund** [comment]
Reading through the article everything looks good to me. There are 2 open issues but #13281 belongs on another area path (see my comment on that PR) and #17704 looks taken care of.
