### ISSUE TITLE
Review `dotnet publish` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15519]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

**Comment by tdykstra** [comment]
See #7568 issue raised on this doc, but applies to several CLI commands.  Need to add one or more examples illustrating setting MSBuild properties with -p:PropertyName=Value.

**Comment by sfoslund** [comment]
Reading through the article, everything looks fine. #7568 is the only open issue but it looks like it's been solved.
