### ISSUE TITLE
Review `dotnet restore` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15520]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

**Comment by tdykstra** [comment]
This article has two outstanding issues that are awaiting answers to questions:

* https://github.com/dotnet/docs/issues/12713 - can you get which feed a package was restored from
* https://github.com/dotnet/docs/issues/15942 - did -r get changed from passing in RuntimeIdentifiers to RuntimeIdentifier?
