### ISSUE TITLE
Review `dotnet test` documentation

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/docs#15524]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test

**Comment by tdykstra** [comment]
This article has several [outstanding issues](https://github.com/dotnet/docs/issues?utf8=%E2%9C%93&q=is:issue+is:open+61ca4064-7481-a263-60fc-c70127f2ad16+in:body). Some of them have enough information in the issue to update the doc -- the ones that need more info are:

* https://github.com/dotnet/docs/issues/13963 - filter not working with parameterized test cases
* https://github.com/dotnet/docs/issues/17135 - add nunit examples
* https://github.com/dotnet/docs/issues/17256 - document code coverage

**Comment by tdykstra** [comment]
@nohwnd does #18295 complete your review, i.e., can we close this issue?

**Comment by nohwnd** [comment]
@tdykstra This issue should wait for @pavelhorak to extend the info about the filtering issue, mentioned in the outstanding issue above.

**Comment by tdykstra** [comment]
@pavelhorak ping

**Comment by tdykstra** [comment]
>This issue should wait for @pavelhorak to extend the info about filtering, to provide a solution for the issue mentioned above.

#13963 is closed due to lack of response from the issue creator. Since that was the only thing left that this issue was waiting for, I'm closing this issue.
