### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by Lapwai** [dotnet/docs#15579]
Hi there,
I tried several times to reload this page, unfortunately, I am still not able to read this part of the tutorial, please check it.

Best Wishes,
Andy

**Comment by mairaw** [comment]
Which tutorial @Lapwai? And which part? 

Can you please share a link and a screenshot, if possible?

**Comment by Lapwai** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection

**Comment by mzkev** [comment]
@Lapwai  Please check again as i can read the tutorial in that link. Please see screenshot below.

![image](https://user-images.githubusercontent.com/25280476/67955231-914e5c80-fbf2-11e9-8c95-a7f45a0568f1.png)

**Comment by Lapwai** [comment]
Hi, I can read now, thanks.

**Comment by mairaw** [comment]
Thanks for letting us know. Not sure what was going on.
