### ISSUE TITLE
Sort redirection file automatically

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#15577]
Figure out a way to sort the .openpublishing.redirection.json file automatically. For example, by using Azure Pipelines to run a sorting script.

**Comment by BillWagner** [comment]
The reason we adopted the process of sorting the redirection file alphabetically was that this practice worked well to avoid merge conflicts in the redirection file. 

Before adopting this practice, each PR that added a redirection made the addition at the bottom of the file. That practice almost guaranteed merge conflicts.

This issue describes one way to avoid the work of manually sorting the redirection file when adding new redirects. Any other solution that makes it easy to add redirects anywhere would preserve the advantage we gain by enforcing this practice.
