### ISSUE TITLE
TOC order for CLI tools

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1557]
What should be the order we list the CLI commands on the TOC?

This is the current version:
![image](https://cloud.githubusercontent.com/assets/12971179/22951287/7bbc2316-f2bd-11e6-8e88-cd77a28e3585.png)
If I want to add dotnet-sln to this TOC, I don't know where to place it.

Should we instead list the tools alphabetically?
![image](https://cloud.githubusercontent.com/assets/12971179/22951322/9c85d2e0-f2bd-11e6-878d-50dec131d917.png)

/cc @blackdwarf @BillWagner @rpetrusha

**Comment by blackdwarf** [comment]
We should, I think, list the commands in their invocation order. So, `dotnet-new`, followed by `dotnet-restore` and then `dotnet-build` and all of that. Then we can put all of the CRUD commands, including the SLN command, after the "inner loop" ones.

**Comment by mairaw** [comment]
I just have a hard time sometimes trying to find the right command page. I think if it was alphabetical would make that easier.

**Comment by blackdwarf** [comment]
Can you not use the filter command for that?

**Comment by mairaw** [comment]
Yes, I use the filter when I'm not finding it.

**Comment by rpetrusha** [comment]
I'd prefer alphabetical. They're simply harder to scan if listed in any other order, and (unless you're familiar with all of the commands and their order of invocation) any other order just seems random.

**Comment by BillWagner** [comment]
I'd use alphabetical.  The 'inner loop' order can be highlighted in the main index file.

**Comment by blackdwarf** [comment]
OK, downvoted here. :) Alphabetical it is.

**Comment by mairaw** [comment]
Thanks for the feedback guys. I'll submit a PR then.
