### ISSUE TITLE
Errors adding/updating service reference since last update

### ISSUE THREAD

**Issue by richardscholten73** [dotnet/docs#15588]
Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://schemas.microsoft.com/dynamics/2011/01/services']/wsdl:portType[@name='AddressService']

Adding System.ServiceModel.Primitivesto theh project  via nuget did not solve the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Add WCF Web Service Reference - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide#feedback)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @dasetser
* Microsoft Alias: **mairaw**

**Comment by dasetser** [comment]
@richardscholten73 Since this appears to be a product issue rather than a problem with the documentation can you please report this using [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)? That helps us gather more information to investigate and track it correctly. When filing the new issue it would be helpful if you could include information about your project that you're adding the reference to including whether it happens for all project types, specific project types, or one specific project.

**Comment by richardscholten73** [comment]
> @richardscholten73 Since this appears to be a product issue rather than a problem with the documentation can you please report this using [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)? That helps us gather more information to investigate and track it correctly. When filing the new issue it would be helpful if you could include information about your project that you're adding the reference to including whether it happens for all project types, specific project types, or one specific project.

Ah, ok.
Thank you @dasetser 

For anyone reading this with the same problem, it appears that after the last vs2019 update and .net core 3.0 this error occurs when updating/creating wcf service references in .net core 2.2 (or lower?). Updating your project to .net core 3.0 solves the issue. We were planning this anyway, so not a big issue for us anymore.
