### ISSUE TITLE
Relationship to App Service

### ISSUE THREAD

**Issue by dlidstrom** [dotnet/docs#15590]
This page is explaining the containerization technology. This is then compared with virtual machine images, from a resource utilization and process isolation perspective. However, Azure allows other options for hosting ASP.NET Core applications: App Service. I'd love to see a discussion about why we need these small micro operating systems (containers) where we can just avoid the whole operating system concept by hosting directly in App Service. This guide is very prominent for .NET developers who are moving into Azure so I think it is fair it would cover the whole picture. It seems as though it is assumed that docker containers have already been chosen. Where and why has that decision been made?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba2da58-10b2-ac3d-83ea-df35ebe776dc
* Version Independent ID: eec71f65-f787-abdf-23fc-5ab25a3ab27e
* Content: [Introduction to Containers and Docker](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/container-docker-introduction/#feedback)
* Content Source: [docs/architecture/microservices/container-docker-introduction/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/container-docker-introduction/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @dlidstrom, thanks for your feedback!

I think you can probably find the information you're looking for in the Azure-specific quick-start guide for .NET developers, you can see in the [.NET & Azure Application Architecture](https://dotnet.microsoft.com/learn/azure/architecture) section from the [.NET Architecture Guides](https://dotnet.microsoft.com/learn/dotnet/architecture-guides) site.

In the .NET & Azure Application Architecture section you'll also find the brand-new [Architecting Cloud Native .NET Applications for Azure](https://docs.microsoft.com/dotnet/architecture/cloud-native/) that's completely Azure-specific and covers more options that just containers.

The intent of this guide is to focus on microservices and containers from a broader point of view and not as much Azure-specific. so it's probably not the best place to explore options different from containers or more focused on Azure.

Hope this helps.

**Comment by dlidstrom** [comment]
I’m reading it now. It is looking very promising, thanks!

**Comment by mvelosop** [comment]
Glad to know that @dlidstrom.

Closing this issue now but feel free to comment, will reopen if needed.
