### ISSUE TITLE
Missing information about defaults

### ISSUE THREAD

**Issue by lukos** [dotnet/docs#15591]
Although you specify something about what happens with the project argument is missing, some of the defaults are not obvious. It appears that the default output directory is TestResults or is that just added onto whatever the output directory is set to?

Standard format for any parameter descriptions should include what you already have and also what the default values are. Thx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for filing this issue, we'll add it to the backlog.

**Comment by brcaswell** [comment]
this consideration has been raised in https://github.com/dotnet/sdk/issues/10706 ... also, please ensure that this effort to document the defaults is included in "dotnet test -h".

**Comment by Thraka** [comment]
@brcaswell That issue seems to be about something else, to enable `Console.WriteLine` to appear in console output without specifying the `-v` parameter.

**Comment by brcaswell** [comment]
@Thraka that issue workitem raised a few points, one being in regards to this issue where "the docs, mentioning only v2.1 and dotnet test -h say nothing about the default value for verbosity"

**Comment by Thraka** [comment]
@tdykstra You were just in the test command docs. It seems the default values are missing. But I don't think they are even listed in the output of the command itself. Do you have a product group contact that can fill in the info?
