### ISSUE TITLE
Azure Import and Export pricing

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#15599]
@maku0119 commented on [Thu Oct 31 2019](https://github.com/dotnet/docs.ja-jp/issues/860)

There is "Transaction fee" in "Price details" of Azure import and export, but isn't it wrong for "Transaction fee"? Looks like it costs a special fee.

* Standard storage fee and transaction fee will be charged separately.
https://azure.microsoft.com/ja-jp/pricing/details/storage-import-export/

---

@srvbpigh commented on [Thu Oct 31 2019](https://github.com/dotnet/docs.ja-jp/issues/860#issuecomment-548308390)

Hello, @maku0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
@CeciAc I think this was added to the wrong repo. This would go to the azure docs repo https://github.com/MicrosoftDocs/azure-docs-pr
