### ISSUE TITLE
.NET API browser shows incorrect type descriptions

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#15592]
For example [SequenceReader<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1?view=netcore-3.0):

```
C++

generic <typename T>
 where T : value classpublic value class SequenceReader
```

**Comment by Thraka** [comment]
Thank you for letting us know. We'll investigate this.

**Comment by Thraka** [comment]
This issue was moved to mono/api-doc-tools#444
