### ISSUE TITLE
title metadata

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#15614]
In the current template.md, it's said:

> title: Appears in search engine results. The title shouldn't be identical to the title in your H1 heading, and it should contain 60 characters or less.

I think most articles has the title metadata identical to the H1 heading.

I also don't see the reason for the title metadata to be different than the H1 heading.
Should the articles be updated (or at least making sure that new articles follow this) ? or should the guidelines in template.md be changed ?

**Comment by tdykstra** [comment]
This guideline is a general rule of thumb that is not intended to apply rigidly to all articles. For some articles, having identical H1 and metadata title is fine. Each instance must be evaluated to determine whether varying the text in these two places has potential to help SEO.

 As we make major updates to existing articles, we may look at updates to improve the findability of an article. However, this is not a task that should be taken across the repository.
