### ISSUE TITLE
Review article - CSAT OKR

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15611]
Article needs to be reviewed because of low CSAT scores.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
Some ideas, based on verbatims I saw:

- add a link to the devenv commands - https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2019
- add a link to the msbuild reference - https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019
- add a link to vstest.console.exe reference - https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019

Also, should this topic live in the VS repo/docset?

**Comment by mairaw** [comment]
> should this topic live in the VS repo/docset?
This might be something worth pursuing although this linked frequently from here (45 files on this repo link to this topic)
