### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by DaddyBA** [dotnet/docs#15624]
The last name chosen here, although it may be a real name, dilutes the professional reputation of Microsoft. Change up the name a little and you have “Is a Bell Butt” which could probably turn up on Urban Dictionary with some lewd definition. Not a good name choice for the code sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb1d95e-a652-a965-f817-d49554a07388
* Version Independent ID: 05423053-63de-3e56-0929-2ae477d577df
* Content: [Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @DaddyBA 

We'll get this updated.
