### ISSUE TITLE
Code error in TestCase

### ISSUE THREAD

**Issue by auliakhilmi** [dotnet/docs#15623]
PrimeService need to be instanced. You need an additional line to instance it before called it with `var result`.
`PrimeService _primeService = CreatePrimeService();`
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#feedback)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **mairaw**

**Comment by Youssef1313** [comment]
In the samples repo, https://github.com/dotnet/samples/blob/master/core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService_IsPrimeShould.cs, the `_primeService` already exists as a private global variable, but unfortunately it's not referenced. Would referencing that `_primeService` is a private global variable fix your issue ?

**Comment by auliakhilmi** [comment]
Ah, I see. After looking at your overall code, surely it works for me. I just came to https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit then follow the tutorial and I got this issue.

**Comment by Youssef1313** [comment]
@auliakhilmi , When my PR gets reviewed and approved and would reflect the article in the docs.microsoft.com.

I've made a slight edit to the current code in samples repo, you can see it in my branch [here](https://github.com/Youssef1313/samples/blob/patch-3/core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService_IsPrimeShould.cs)

**Comment by auliakhilmi** [comment]
Ok, I think it's clearly resolved. Thank you.
