### ISSUE TITLE
Typo: readonly sturct

### ISSUE THREAD

**Issue by cskwg** [dotnet/docs#15620]
There is a typo: readonly sturct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @cskwg. Would you like to submit a pull request to fix this?

The process is explained here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by Youssef1313** [comment]
I've opened PR #15630 to address this.
