### ISSUE TITLE
Sr Consultant

### ISSUE THREAD

**Issue by samezyane** [dotnet/docs#15631]
Great code snippets and great illustrating examples!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3753657-9f0f-4e68-abde-5f461099cb6e
* Version Independent ID: f7bd9eb0-1653-15fd-5f0e-dc0ee5c3bf88
* Content: [Safely update interfaces using default interface methods in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-methods-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-methods-versions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the compliments @samezyane I'm glad it helped.

Closing as kudos.
