### ISSUE TITLE
Title of Page - The .NET Framework Analyzer or The .NET Security Analyzers

### ISSUE THREAD

**Issue by foundinhim** [dotnet/docs#15632]
I apperciate the work that goes into this documentation. I know it is challenging to keep updated. :smile:

It seems like this page is broadly about _The .NET Framework Analyzer_, but the HTML \<title\> is _The .NET Security Analyzers - .NET | Microsoft Docs_, and it also reads:

> The .NET Security Analyzers must be installed as a NuGet package on every project where you want them to run. Only one developer needs to add them to the project. The analyzer package is a project dependency and will run on every developer's machine once it has the updated solution.

Where is this package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171973c7-c225-a776-793f-cf67869ea0b8
* Version Independent ID: f26f0129-8073-cc7e-1b3a-0002ad3af932
* Content: [The .NET Security Analyzers - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/framework-analyzer)
* Content Source: [docs/standard/analyzers/framework-analyzer.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/framework-analyzer.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Good catch. I think that it's the same thing refereed in two different ways. Perhaps in the past it was referred to as the Security Analyzer. Other links going to this page do refer to it as the .NET Framework Analyzer.

We should probably remove reference to it as the .NET Security Analyzer.

https://www.nuget.org/packages/Microsoft.NetFramework.Analyzers/ is the package you're looking for.

**Comment by foundinhim** [comment]
@Thraka , thank you for the clarification regarding the Security Analyzer.
