### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#15648]
@realsonic commented on [Fri Nov 01 2019](https://github.com/dotnet/docs.ru-ru/issues/238)

"Configures the local directory for a Simple Mail Transport Protocol (SMTP) server." - as I understand, the configuration is for SMTP client, not a server.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 95b442ac-c502-6882-7307-2c9a537579f4
* Version Independent ID: 1b2fe919-4095-000b-6f87-c80eab926223
* Content: [Элемент &lt;specifiedPickupDirectory&gt; (параметры сети)](https://docs.microsoft.com/ru-ru/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

---

@srvbpigh commented on [Fri Nov 01 2019](https://github.com/dotnet/docs.ru-ru/issues/238#issuecomment-548758267)

Hello, @realsonic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
I believe this is for the server. When I search for this information on the internet I keep seeing people use this setting to have the **server** load emails to send from this directory.

So I believe the documentation is correct.

Please let me know if you still think otherwise.
