### ISSUE TITLE
Warn that group joins don't work with database

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#15649]
As discussed in aspnet/EntityFrameworkCore#17068, the examples on this page, while fine with LINQ to objects, don't work with LINQ to SQL because databases don't tend to support this type of query. Group joins kind of worked in older version of EF, but would mysteriously become slow because of silent client-side evaluation. EF Core 3 fortunately provides a runtime error, although its exception is confusing, leading to questions like [this](https://stackoverflow.com/q/58622571/145173).

A great big "don't try this at home" warning on this doc page with a clear explanation of EF's limitations would save a lot of developer headaches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de690d2-fba4-ce90-964f-4a4eaa99e05f
* Version Independent ID: 28d797c1-3fe1-c867-fd17-dbacb6728109
* Content: [Perform grouped joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-grouped-joins)
* Content Source: [docs/csharp/linq/perform-grouped-joins.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/perform-grouped-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @breyed Your notes are correct. I've added this to our next sprint to address.

If you'd like to submit a PR before then, I'll watch for it.

**Comment by smitpatel** [comment]
This could be referenced https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupjoin

**Comment by IEvangelist** [comment]
Hi @breyed,
Such a small world we live in, I see that you're a fellow Wisconsinite 🤘... I'm going to work on this issue by adding some clarifying statements about limitations, as you suggested. Thank you for your patience.
