### ISSUE TITLE
dotnet new command looks like it has two dots.

### ISSUE THREAD

**Issue by decafbad** [dotnet/docs#15656]
dotnet new console -n NumbersInCSharp -o . comes before sentence ending period. This makes it look like having two dots, therefore works in parent directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6905a9-e9ec-df6f-5733-dfb25a41b97a
* Version Independent ID: fe0e2716-651b-a883-6371-ded1ace94a11
* Content: [Numbers in C# - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @decafbad for your feedback. I've opened PR #15659 that should help with this.
