### ISSUE TITLE
Documentation incorrectly specifies that local functions cannot be static

### ISSUE THREAD

**Issue by allisonchou** [dotnet/docs#15654]
I believe this line is now outdated, since local functions can now be static:

"Including the static keyword generates compiler error CS0106, 'The modifier 'static' is not valid for this item.'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think you're correct. https://github.com/dotnet/roslyn/pull/32067

**Comment by BillWagner** [comment]
Thanks for writing this @allisonchou 

I've added this to the task for the next sprint. We should be finishing all the docs for C# 8 features by then.
