### ISSUE TITLE
Update for Dotnet core 3.0

### ISSUE THREAD

**Issue by Paul-Dempsey** [dotnet/docs#15653]
Needs maintenance to bring up to netcore 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore22)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Paul-Dempsey** [comment]
never mind -- I see this is a dupe of #9893, but that issue looks like it has been getting kicked down the road for many months.

**Comment by mairaw** [comment]
And I already have a PR in progress. It's just complicated because I'm redoing the entire article and lots of things going on. But I plan on finishing it soon.

PR #14356

**Comment by TomasB** [comment]
"I plan on finishing it soon" has been said 3 months ago

**Comment by mairaw** [comment]
Sorry, other things came up and I haven't finished that PR yet. As you can see, I moved the milestone to February.

**Comment by mairaw** [comment]
The PR is now ready and awaiting review.
