### ISSUE TITLE
It would be nice to see the entire code as well

### ISSUE THREAD

**Issue by kapiljain-128** [dotnet/docs#15662]
I had some confusion while reading this about which functions were added first to which classes. It would be great if we could see the final code for all the classes along with their members at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3753657-9f0f-4e68-abde-5f461099cb6e
* Version Independent ID: f7bd9eb0-1653-15fd-5f0e-dc0ee5c3bf88
* Content: [Safely update interfaces using default interface methods in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-methods-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-methods-versions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@kapiljain-128 The second paragraph from the end contains the links to the full code. Or it's not something you're looking for?

**Comment by Youssef1313** [comment]
As @pkulikov stated, the page says:

> You can see the entire finished code in our [samples repo on GitHub](https://github.com/dotnet/samples/tree/master/csharp/tutorials/default-interface-members-versions/finished/customer-relationship). You can get the starter application on our [samples repo on GitHub](https://github.com/dotnet/samples/tree/master/csharp/tutorials/default-interface-members-versions/starter/customer-relationship).

**Comment by BillWagner** [comment]
We do provide links to our samples repo on GitHub. I'll close this as answered.

**Comment by kapiljain-128** [comment]
Didn't see that, thanks!

**Comment by memark** [comment]
Well, it's still not optimal having to go to GitHub to see what the article is all about. The article contains numerous code example, why is the most important one the only one left out?
