### ISSUE TITLE
Can I publish to defined platform by using vs for mac?

### ISSUE THREAD

**Issue by naughtyGitCat** [dotnet/docs#15663]
It seems the example is using vs for win

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [Deploy .NET Core apps with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
We don't have a lot of documentation here for VS for Mac, something we do want to change. For immediate help, there may be some info in the Visual Studio for Mac IDE documentation here: https://docs.microsoft.com/en-us/visualstudio/mac/projects-and-solutions?view=vsmac-2019
