### ISSUE TITLE
This page needs examples of what the project file should look like for each section 

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#15664]
For example, what does a file look like that correctly implements some of the Nuget metadata properties or AssemblyInfo properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **mairaw**

**Comment by danieldiazastudillo** [comment]
There are lots of gray areas as docs concerned. Build targets, variable-like XML properties, pre-post build and or publishing... I just need to run a simple webpack task before publishing but there are lots of approaches over the web. Maybe a _kitchensink_ csproj would be great.

**Comment by StingyJack** [comment]
An example or even an XSD (with defaults) would still be appreciated

**Comment by tdykstra** [comment]
This article was retired and its URL now forwards to https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props 

cc @gewarren

**Comment by StingyJack** [comment]
@tdykstra  - thanks. I may open a new issue on the other one if I cant find the defaults that are used when the elements are omitted.
