### ISSUE TITLE
Deserialization without parameterless constructor

### ISSUE THREAD

**Issue by tb-mtg** [dotnet/docs#15675]
Why is Deserialization to reference types without a parameterless constructor not supported?

Can you please add support for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@tb-mtg The current release of System.Text.Json is the first release, and the dev team focused on maximizing performance over providing a comprehensive feature set. That said, you can work around that limitation by writing a custom converter.  There is an open Pull Request creating an article that explains how to create custom converters: #15113 
For more information, see https://github.com/dotnet/corefx/issues/38569
