### ISSUE TITLE
Usage inconsistency

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [dotnet/docs#15678]
Usage is inconsistent between synopsis and examples. In the synopsis, &lt;CACHE_LOCATION&gt; precedes commands such as --clear, but in the examples it comes after. Both formats work (at least as of 3.0), but some might find this confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5725b81-7ebf-e9c5-51b7-f6d1cf5d5dc2
* Version Independent ID: a69419b1-6994-3310-6bde-d787b87db13f
* Content: [dotnet nuget locals command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals#feedback)
* Content Source: [docs/core/tools/dotnet-nuget-locals.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-locals.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. You can always submit the fix yourself by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
