### ISSUE TITLE
Typo under Floating point types

### ISSUE THREAD

**Issue by gplindauer** [dotnet/docs#15679]
Under Value types, "Floating point types" in the fourth bullet, the phrase "and for double, 0 &lt; m &lt; 2^53 and 1075 &lt;= e &lt;= 970" should presumably read "-1075 &lt;= e &lt;= 970", I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de24f644-5e7c-d3de-fd13-5969bb3e4b78
* Version Independent ID: 9173876e-49be-6c60-634d-eeb1944ab2fc
* Content: [Types - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#feedback)
* Content Source: [spec/types.md](https://github.com/dotnet/csharplang/blob/master/spec/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this @gplindauer 

I've submitted dotnet/csharplang#2933 to fix this error.
