### ISSUE TITLE
Code samples defaulting to C++

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/docs#15683]
![image](https://user-images.githubusercontent.com/2813363/68142070-a98de680-ff26-11e9-91d4-5839cb5e6621.png)

I'm assuming this is unintentional, code samples are now defaulting to C++/CLI.

Example: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netcore-3.0

**Comment by Thraka** [comment]
Confirmed with in private browsing.
