### ISSUE TITLE
Java has not Lambda expression, enumeration, delegate, directly access memory are incorrect.

### ISSUE THREAD

**Issue by donhuvy** [dotnet/docs#15695]
> 
enumerations, delegates, lambda expressions and direct memory access, which are not found in Java. 

Java has 

- delegates ( not built-in, but can implement https://www.dummies.com/programming/java/how-to-use-the-delegation-pattern-in-java/ )
- enumerations ( https://docs.oracle.com/javase/7/docs/api/java/util/Enumeration.html )
- lambda expression ( https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html )
- directly access memory ( https://www.mkyong.com/java/java-write-directly-to-memory/ )
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91388e65-01f7-d27c-38d0-4e2113cef43a
* Version Independent ID: ad74fdd5-880a-df4c-731c-235c8d42d7db
* Content: [Introduction to the C# Language and the .NET Framework](https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework)
* Content Source: [docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md](https://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Yes @donhuvy You are correct. This page has not been updated for more modern Java features.

Related #14477 

For both issues, I think the best plan is to avoid a direct comparison with other languages. As these issues point out, it's hard to ensure we correctly compare all the developments in other languages in a timely fashion.
