### ISSUE TITLE
Too long, too little content

### ISSUE THREAD

**Issue by bittner** [dotnet/docs#15698]
What is a Cloud Native application? - An application that is resilient and can scale.

Resilient = ...
Can scale = ...

(Is this so difficult to get right?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03831099-3360-98e5-d35b-934a024f88e0
* Version Independent ID: 7bf71b44-4b61-9832-28c2-8f4881199829
* Content: [Defining Cloud Native](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/definition#feedback)
* Content Source: [docs/architecture/cloud-native/definition.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/definition.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by robvet** [comment]
Hello Bitner... My apologies for such a late response. Appreciate your input, but having hard time following it. It almost sounds like you're saying, "Hey, it's simple, Cloud Native apps are Resilient and Scalable. Period. End of conversation." Certain, you'll agree there is a little more to it than just that. Please help me understand your point. Thanks

**Comment by bittner** [comment]
I believe the definition is that simple. Implementing that is of course a different topic, this is hard work and requires attention to detail. My point it, I makes sense to keep documentation concise. Because people may just look for a definition. What do you think?

**Comment by robvet** [comment]
Getting back to this. Yes, you make good sense. Thinking about adding a paragraph that first concisely summarizes the characteristics of Cloud Native Apps. And, then follow it with the detail.

**Comment by robvet** [comment]
Suggest we close this issue now.
