### ISSUE TITLE
dotnet/docs/blob/master/styleguide/template.md is misleading in term of metadata rendering

### ISSUE THREAD

**Issue by aethaniel** [dotnet/docs#15691]
**Issue description**

https://github.com/dotnet/docs/blob/master/styleguide/template.md is misleading in term of metadata rendering.
I found this document very useful for my own purpose but in fact it may be outdated on one point:

> Metadata and Markdown Template
>
> This dotnet/docs template contains examples of Markdown syntax, as well as guidance on setting the metadata. To get the most of it, you must view both the raw Markdown and the rendered view (for instance, the raw Markdown shows the metadata block, **while the rendered view does not**).

As you can notice by viewing this file, it seems github renderer saw some unfortunate changes since this document has been written, leading to metadata being rendered against the initial will.

Do you know if this change will be reverted or fixed?

Best regards

**Comment by aethaniel** [comment]
Guys, you realize you didn't fix anything to the problem here?
You didn't fix the wrong GitHub renderer by changing a bit the documentation and the metadata is still rendered. Well, that's a kind a fix, though. I would have taken another approach to it.

**Comment by Thraka** [comment]
Can't. That is the way github renders YAML headers.

**Comment by aethaniel** [comment]
Indeed. Makes sense on some manner.
Thanks

**Comment by Thraka** [comment]
Really the point about checking both the preview and the source is to understand how the markdown syntax styles the output. The header note was definitely not needed. So thank you for pointing that out. 👍
