### ISSUE TITLE
NumberGuessWorkflowActivities section in step 17 is Incorrect

### ISSUE THREAD

**Issue by twburger** [dotnet/docs#15709]
17. Drag a ReadInt activity from the NumberGuessWorkflowActivities section of the Toolbox and drop it in the Sequence activity so that it follows the WriteLine activity.

It is the "Custom Activities" section when using Visual Studio 2012.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a93236-b0ab-b367-b086-deadf52a7c82
* Version Independent ID: 2e8a64e6-e2ce-cacd-bc6f-645bc95eaf49
* Content: [How to: Create an Activity](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-create-an-activity#feedback)
* Content Source: [docs/framework/windows-workflow-foundation/how-to-create-an-activity.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/how-to-create-an-activity.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wf**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
I've followed the instructions in the article and it seems the following statement is valid:

> Drag a ReadInt activity from the NumberGuessWorkflowActivities section of the Toolbox and drop it in the Sequence activity so that it follows the WriteLine activity.


![image](https://user-images.githubusercontent.com/31348972/68240675-02887800-0016-11ea-9c4a-b9f5c92d0f38.png)

**Comment by twburger** [comment]
Must be the older VS 2012 I'm using

**Comment by gewarren** [comment]
@Youssef1313 Thanks for checking.

**Comment by internatmc** [comment]
I even can not find the NumberGuessWorkflowActivities section or any <project name> section using Visual Studio 2022.

[https://1drv.ms/u/s!AnpT3iu206r2m7dZnNcRDjC9td847g?e=3FbiRa](url)
