### ISSUE TITLE
Process.Start changes

### ISSUE THREAD

**Issue by onovotny** [dotnet/docs#15703]
Process.Start changed too -- on .NET Framework, `UseShellExecute` defaulted to true and on .NET Core, it's false.

This means that programs that used `Process.Start("https://dot.net");` won't work anymore. They now need a `ProcessStartInfo`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f19516-254e-d701-1cd3-d2cf4ddac6e5
* Version Independent ID: dc951b71-083e-6127-99a6-e1278ce8c044
* Content: [Breaking changes, .NET Framework to .NET Core 3.0 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/framework-core)
* Content Source: [docs/core/compatibility/framework-core.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/framework-core.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **mairaw**

**Comment by danmosemsft** [comment]
This is correct. We did put a note in the API doc [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=netcore-3.0#property-value) and it should be in the list of breaks between .NET Framework and .NET Core.

Here's the template:

## Change in default value of UseShellExecute 

`UseShellExecute` on the `ProcessStartInfo` class has a default value of `false` on .NET Core. On .NET Framework, it defaults to `true`. 

### Version introduced

.NET Core v2.1. (In earlier versions of .NET Core, UseShellExecute was not implemented for Windows.)

### Old behavior

On Windows, `Process.Start(...)` could be used to launch an associated application indirectly. For example `Process.Start("mytextfile.txt")` might launch notepad, and `Process.Start("https://microsoft.com")` might launch the browser.

### New behavior

By default, associated applications cannot be launched in this way. You must pass to `Process.Start(...)` an explicit path to the executable file.

### Reason for change

This makes starting processes faster by default.

### Recommended action

If you rely on the old behavior, change your `Process.Start(..)` call to pass a `ProcessStartInfo` object with `UseShellExecute` set to true.

### Category

CoreFX

### Affected APIs

[Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netcore-3.0)
[ProcessStartInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=netcore-3.0)



---
#### Issue metadata

* Issue type: breaking-change

**Comment by mairaw** [comment]
We typically cover these sort of changes in the API docs. I think we should move this to the dotnet-api-docs repo since the breaking change doc was done specifically to cover some Winforms scenarios (you can see see it has already been moved and modified to make that more clear).

**Comment by danmosemsft** [comment]
@PriyaPurkayastha can you advise? This should be in the API docs linked above, yes, but it should also be in some grand "breaking changes from .NET Framework" topic and @PriyaPurkayastha was figuring out which that topic is.

This breaking change has come up numerous times so it should certainly be in such a centralized topic.

**Comment by PriyaPurkayastha** [comment]
I am working on a strategy to document .NET Framework->.NET Core breaking changes. There will be three aspects - finding existing documentation for APIs throwing PNSE(or generating a new list if the old list is no longer available), adding link to .NET Framework tech not available in .NET Core and adding new breaking changes(such as this Process.Start one) for newly created GitHub issues that are not covered by the earlier two existing docs. @mairaw I have chatted with @gewarren about this last week and told her that we will sync up again sometime this week or early next week. I will make sure to include you in that discussion. The .NET Framework to .NET Core 1.x/2.x was not on my radar until now, but with the new issues cropping up we might need to tweak the doc structure to accommodate these breaking changes.

**Comment by mairaw** [comment]
Sounds good @PriyaPurkayastha. As long as I know what's the plan, I'm good.
