### ISSUE TITLE
need more info

### ISSUE THREAD

**Issue by perlmaster** [dotnet/docs#15715]
how do we solve this error ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672e69a1-80bb-87cd-b3b8-bf104d8aa89e
* Version Independent ID: 1c66477a-2a97-4eff-1cd8-937f4e7880a0
* Content: [Compiler Error CS0120](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0120.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0120.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@perlmaster Is this error related to https://github.com/dotnet/docs/issues/15712#issuecomment-550362582? Let us know.
