### ISSUE TITLE
need more information on creating namespaces

### ISSUE THREAD

**Issue by perlmaster** [dotnet/docs#15710]
You need to specify in much more detail how to go about creating a C# source code file with my own personal namespace, how to compile it, and finally how to use this compiled namespace file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8208c493-a641-6d18-dcc7-2d6263e2c3d2
* Version Independent ID: 39fad50f-71ea-8e4f-ebd5-4555024d2424
* Content: [Namespaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/#feedback)
* Content Source: [docs/csharp/programming-guide/namespaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/namespaces/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@perlmaster Is this related to the information https://github.com/dotnet/docs/issues/15712#issuecomment-550362582?  Let us know if that information helped.
