### ISSUE TITLE
When publish creates Identity folder in wwwroot

### ISSUE THREAD

**Issue by RetsamSoft** [dotnet/docs#15716]
Hello, sorry for my bad English, when I publish my project I create a folder called "Identity" in the wwwroot folder.
I use my own layout in /Areas/Identity/Pages/_ViewStart.cshtml

```
@ {
    Layout = "/Views/Shared/_MyLayout.cshtml";
}
```

I don't want the "Identity" folder to be created automatically at wwwroot, thx.

- .NET Core 3.0

**Comment by Thraka** [comment]
Hello, I think this question is better suited for the ASP.NET Core team.

**Comment by Thraka** [comment]
This issue was moved to aspnet/AspNetCore.Docs#15556
