### ISSUE TITLE
need help with compiling and using a C# namespace file

### ISSUE THREAD

**Issue by perlmaster** [dotnet/docs#15712]
I am new to C# and I just developed a small CGI program&gt; I would like to create ore CGI programs and in order to keep down the amount of duplicated code I thought I would create a C# namespace file with code that could be used by all of my CGI programs. How do I compile a file without a "Main()" on my Windows 10 system?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc1ba33-60dd-1e44-2498-eb76f0d964c1
* Version Independent ID: a1404161-c48b-564b-03ea-d4340fe28c53
* Content: [Compiler Error CS5001](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs5001)
* Content Source: [docs/csharp/misc/cs5001.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs5001.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@perlmaster 

There are two introduction to C# tutorials that I think will answer all your questions.

First, the [introduction to classes](https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes) provides some of structure of C# programs.

Next, the .NET Core tutorial on [building a class library](https://docs.microsoft.com/dotnet/core/tutorials/library-with-visual-studio) explains how to build a reusable library. 

Let us know if those resources help.
