### ISSUE TITLE
Switch expression arms should use discards when appropriate

### ISSUE THREAD

**Issue by rgwood** [dotnet/docs#15728]
Some of the switch expression arms in this tutorial specify variable names unnecessarily, and this results in compiler warnings.

For example, this arm names the Bus object `b` even though `b` is never referenced:

```
Bus b => 5.00m,
```

In the latest version of VS Code+OmniSharp, that results in the following compiler warning: "Unnecessary assignment of a value to 'b' (IDE0059)"

Changing the arms to use discards fixes the error:

```
Bus _ => 5.00m,
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc5c533-a9ca-cc70-af20-21308e819082
* Version Independent ID: ef6af5d2-b640-0feb-d9d3-7aae0ca92264
* Content: [Use pattern matching features to extend data types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/pattern-matching#feedback)
* Content Source: [docs/csharp/tutorials/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for suggesting this. Tagging @BillWagner in case he wants to further categorize this.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by BillWagner** [comment]
This is a great suggestion. Thanks for pointing this out @rgwood
