### ISSUE TITLE
Use of arrows a bit confusing

### ISSUE THREAD

**Issue by anielsen** [dotnet/docs#15721]
In figure 5-8 solid arrows represent compile-time dependencies, while dashed arrows represents a runtime-only dependency. In figure 5-9 this is switched around which is a bit confusing :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by KrisPetkov** [comment]
I have noticed the same problem. Which figure represents the real/true connection between layers?

* Dashed arrow is *compile-time* dependency
* Solid arrow is *run-time* dependency

Or the other way around?

**Comment by ardalis** [comment]
I'll have a look and update the figures if nececessary.

**Comment by ardalis** [comment]
Ok I've looked at this and the issue isn't quite what's being described (but the confusion is real). In this image:
![image5-8](https://user-images.githubusercontent.com/782127/74371047-22ae9c80-4da6-11ea-95ea-eea361964346.png)

The dashed line represents an _optional_, not a compile-time vs. runtime, dependency. Probably this diagram would benefit from a legend, like figure 5-9 has.

Adding fixed images to existing PR
