### ISSUE TITLE
Wrong protobuf files examples

### ISSUE THREAD

**Issue by Ramin2c** [dotnet/docs#15720]
All the protobuf files miss ; from their first line, version declaration, i.e.:  syntax = "proto3";

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a41d02-3084-c31e-98ed-2bd786c7a301
* Version Independent ID: 31a20696-f326-63c3-77d1-f3cfc0aa589c
* Content: [Protobuf scalar data types - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **nanil**

**Comment by Thraka** [comment]
@markrendle can you look at this issue?

**Comment by mairaw** [comment]
Tagging @shirhatti here

**Comment by shirhatti** [comment]
I'll need to take another look at the language guide, but on cursory glance this issue seems right.

Self-assigning to take a look
