### ISSUE TITLE
Can this approach work for Image Classification of Pretrained Model

### ISSUE THREAD

**Issue by rossnoe** [dotnet/docs#15722]
Great article. I did this and got it to work. I tried to adapt this approach to my Image Classification model - which is named dnn_model.zip. For some reason I keep getting an error when I try to load the model. Below is my controller. Please provide recommendations. Thanks.

        [HttpPost]
        public ActionResult&lt;string&gt; Post([FromBody] ImageData input)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    // return BadRequest();
                    return Content("Invalid model.");
                }

                var context = new MLContext();

                ImagePrediction prediction = _predictionEnginePool.Predict(modelName: "ImageDnnModel", example: input);

                string imginfo = "Prediction value is: " + prediction.PredictedLabel.ToString() + ", Score is: " + prediction.Score.ToString();

                return Ok(imginfo);
            }
            catch (Exception e)
            {
                string errmsg = "Opps, an error happened: " + e.ToString();
                return Content(errmsg);
            }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dce49db-3548-7dad-bdb1-812efde7ac86
* Version Independent ID: 390a9c7a-2537-25ca-c041-0284c253acff
* Content: [Deploy a model in an ASP.NET Core Web API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @rossnoe 

It should work. I believe the issue you're facing is you're using the schema from `ImageData` which if you follow the image classification tutorial is meant for images stored on disk. The model expects image to be a `byte[]` so you can do one of two things. Either create a pipeline that includes the `LoadRawImageBytes` transform or convert the image to `byte[]` and use that as input. You can see this sample for reference.

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training/WebApp.Predict/Controllers/ImageClassificationController.cs

**Comment by rossnoe** [comment]
Thanks very much Luis! I will implement the sample tomorrow. It's great to see the improving capabilities of ML.net.
