### ISSUE TITLE
PackageIconUrl is deprecated and should not be recommended

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#15735]
https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl:

> iconUrl is deprecated. Use icon instead.

Also, https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file is helpful on how to do this properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#feedback)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@jnm2 Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
