### ISSUE TITLE
Double setting of the object to be tracked

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#15743]
"To establish a weak reference with an object, you create a WeakReference using the instance of the object to be tracked. You then set the Target property to that object and set the original reference to the object to null"

Why both passing the object to the WeakReference constructor and then setting the Target property to the same object?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49276dae-37a4-0972-353d-77979378be34
* Version Independent ID: e059fcc8-d462-a39f-4d75-b31ee63a221a
* Content: [Weak References](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/weak-references?redirectedfrom=MSDN#feedback)
* Content Source: [docs/standard/garbage-collection/weak-references.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/weak-references.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
This does seem like a bug in the documentation. Thanks for letting us know!

Code from the [example](https://docs.microsoft.com/en-us/dotnet/api/system.weakreference?view=netframework-4.8#examples) doesn't explicitly set Target:

for (int i = 0; i < count; i++) {
            _cache.Add(i, new WeakReference(new Data(i), false));
        }
