### ISSUE TITLE
Protobuf gen from WSDL

### ISSUE THREAD

**Issue by OzBob** [dotnet/docs#15748]
Is there a visual studio 'add Web service reference' that can take a WSDL definition and generate a protobuf and gRPC client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516a948a-db6d-f43f-e75c-54ab2166cf9e
* Version Independent ID: b67707f2-2a86-57de-1092-fb134fec1e40
* Content: [Interface Definition Language - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/interface-definition-language#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/interface-definition-language.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/interface-definition-language.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@shirhatti can you take a look at this question? Thanks!

**Comment by shirhatti** [comment]
Visual Studio provides no automated way to convert from WSDL to protobuf.

There is design-time tooling to generate a strongly-typed .NET client for gRPC if you already have authored a protobuf file
