### ISSUE TITLE
questions about `converting-a-local-time` section...

### ISSUE THREAD

**Issue by kodybrown** [dotnet/docs#15747]
When I run the last code example from the `converting-a-local-time` section, I get a different result than what is commented in the code.. And, I cannot figure out the difference between the two DateTimeOffset assignments.. Seriously, what am I missing?

``` csharp
// Convert time originating in a different time zone
originalDate = new DateTimeOffset(2008, 6, 18, 7, 0, 0, new TimeSpan(-5, 0, 0));
localDate = originalDate.LocalDateTime;
Console.WriteLine("{0} converted to {1} {2}", originalDate, localDate, localDate.Kind.ToString());
// Convert time originating in a different time zone 
// so local time zone's adjustment rules are applied
originalDate = new DateTimeOffset(2007, 11, 4, 4, 0, 0, new TimeSpan(-5, 0, 0));
localDate = originalDate.LocalDateTime;
Console.WriteLine("{0} converted to {1} {2}", originalDate, localDate, localDate.Kind.ToString());
```

Comment in example:

```
// The example displays the following output to the console:
//       6/19/2008 7:00:00 AM -05:00 converted to 6/19/2008 5:00:00 AM Local
//       11/4/2007 4:00:00 AM -05:00 converted to 11/4/2007 1:00:00 AM Local
```

Results when I run the example code:

``` dotnet core 3.0
06/18/2008 07:00:00 -05:00 converted to 06/18/2008 12:00:00 Local
11/04/2007 04:00:00 -05:00 converted to 11/04/2007 09:00:00 Local
```

``` .net 4.7.2
6/18/2008 7:00:00 AM -05:00 converted to 6/18/2008 12:00:00 PM Local
11/4/2007 4:00:00 AM -05:00 converted to 11/4/2007 9:00:00 AM Local
```

I just want to make sure it is a typo, or figure out what I'm doing wrong..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba03d8b-25fc-506f-6931-dddab382c3ef
* Version Independent ID: 109db4d3-f55a-29f3-8423-f787af34f5b9
* Content: [Converting between DateTime and DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/standard/datetime/converting-between-datetime-and-offset#feedback)
* Content Source: [docs/standard/datetime/converting-between-datetime-and-offset.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/converting-between-datetime-and-offset.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
I agree that the example is a bit confusing and lacks clarity, but I believe that the author intended to show the automatic adjustment for daylight savings time by using one date in summer (June) and one date in winter (November) - if you're in the northern hemisphere. It's possible that your local time zone doesn't use daylight savings time, in which case there wouldn't really be a difference between the two dates (June and November). This should be clarified in the doc.

Also, I do think that the first output shown in the doc is incorrect. It should be `6/18/2008` instead of `6/19/2008`.
