### ISSUE TITLE
Generic types

### ISSUE THREAD

**Issue by anturom** [dotnet/docs#15744]
I'm generating the XML documentation from a C# project with Visual Studio 2019. I have methods that take generic types as parameters, but they appear in the generated XML file other than described on this page. Namely, I was expecting backticks as suggested above, but my methods appear instead as:

`M:SomeLib.SomeClass.someMethod(System.Collections.Generic.List{System.String},System.String)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79307f9a-ba5a-b108-918b-917df121facd
* Version Independent ID: 6d011fb8-572e-cea9-4e4e-70720dd76251
* Content: [Processing the XML File - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/processing-the-xml-file.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/processing-the-xml-file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
the backticks represent a type that defines a generic parameter. In this case your method is accepting a type that defines a generic parameter, but you've filled in that parameter with a type. You would see the backticks on when you declare something like:

```csharp
public void someMethod<T>(string someParam, T input)
```

This would result in something like:

`M:SomeLib.SomeClass.someMethod``0(System.String,``1)`

Hope this answers your question.
