### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by cashgarman** [dotnet/docs#15757]
Fantastic summary of an otherwise complex topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f5f4b7-b600-d163-ccef-9cf4b0693419
* Version Independent ID: 6e986136-5b77-4abc-da4c-9366c10826d5
* Content: [How to: Create a Class Using CodeDOM](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom#feedback)
* Content Source: [docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md)
* Product: **dotnet-framework**
* GitHub Login: @Thraka
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
You're welcome!
