### ISSUE TITLE
Confusing to refer users to *Integration* testing for ASP .NET Core when this is a *unit* test page

### ISSUE THREAD

**Issue by cbrit** [dotnet/docs#15752]
The title of this page is "*Unit* testing C# in .NET Core...", but near the top of the page there is a line that reads:

"This article is about testing a .NET Core project. If you're testing an ASP.NET Core project, see [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests#test-app-prerequisites)."

If a user is on this page they are probably looking for a way to *unit* test ASP .NET Core (like me), not integration test. There are pages in the docs for unit testing Razor Pages and MVC apps, so shouldn't those be linked instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
This is true. The ASP.NET docset shouldn't be pulling this article into their TOC and instead should have their own article. /cc @Rick-Anderson

**Comment by ardalis** [comment]
To be fair, there's not much to unit test in an ASP.NET Core app that's specific to ASP.NET Core (not the app's business logic) and which isn't better-tested using integration tests outlined in the referenced doc article.

**Comment by Thraka** [comment]
Yes I know. But with how people find articles and the context they assume they are written in, add in the confusing ASP.NET Core vs .NET Core situation, and we need explicit contextual articles. Even if the only difference is titles and some wording or project names.

(Or have both contexts described in the same article)

**Comment by Rick-Anderson** [comment]
> The ASP.NET docset shouldn't be pulling this article into their TOC

**Unit testing C# in .NET Core using dotnet test and xUnit** doesn't belong in our TOC

>  and instead should have their own article. 

We do.

That link shouldn't be at the top of the page. At most, it should be at the bottom under **Additional resources**

**Comment by Rick-Anderson** [comment]
cc @guardrex
