### ISSUE TITLE
Mention the required target framework for C# 8.0

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#15765]
I've read in some GitHub issue comment (that I sadly can't find any more) that C# 8.0 is only officially supported in .NET Standard 2.1 and .NET Core 3.0 because of the new framework types it requires for some of its features. Also, older target frameworks don't use C# 8.0 by default (see [C# language versioning](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)). I think it would be good if that would be documented on this page too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by cremor** [comment]
I've found some information here: dotnet/csharplang#2877

**Comment by BillWagner** [comment]
This article should link to the detailed [version information](https://docs.microsoft.com/dotnet/csharp/language-reference/configure-language-version) article.

Adding the 'up for grabs' label for community members to consider making this fix.
