### ISSUE TITLE
Interpreted vs. compiled regular expressions

### ISSUE THREAD

**Issue by ajhmain** [dotnet/docs#15763]
The 2 paragraphs under this heading are extremely unclear and I would suggest plain wrong.  Compare these parapgraphs with what is written at: https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions

The first paragraph here clearly states non-compiled regex are converted to MSIL before executing.  According to the linked page this is plain wrong, non-compiled regex are interpreted from a instruction codes, not MSIL. 

The second paragraph also needs to be reviewed for clarity as it appears to just copy the process mentioned in the previous paragraph (actually the compiled process) and so may accidentally be more correct than the first paragraph.  

Overall the tone and language of these two paragraphs is unclear and needlessly wordy.  See the above linked page clearer article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14698b87-a995-290f-bdd7-9c2d6867704c
* Version Independent ID: f199cd3f-8dce-ad4e-9712-3545e35557e7
* Content: [Best Practices for Regular Expressions in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices#feedback)
* Content Source: [docs/standard/base-types/best-practices.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/best-practices.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **dotnetcontent**

**Comment by ajhmain** [comment]
The second paragraph is not actually correct either  For compiled expressions is says intemediary codes are created, once again according to the linked page, that is not correct, MSIL is generated.

**Comment by Thraka** [comment]
After reading it, and having a headache 😉, I agree. It's too verbose and confusing. I'll add this to our backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

**Comment by ajhmain** [comment]
Thanks for the response.  Regex are a major workflow component in our system and performance is very important, hence why I have been reading these articles carefully for learning.  Will see if I can come up with a fix for the wording.
