### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by jtbrower** [dotnet/docs#15762]
The documentation and product is great.  I was able to easily replace Newtonsoft without any struggle trying to determine how to handle enums as strings because you documented it so well!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@jtbrower Thanks for the feedback, and please let us know if you run into any scenarios that aren't documented yet!
