### ISSUE TITLE
Please document: How does the using statement work in combination with closures (e.g. lazy evaluated LINQ)?

### ISSUE THREAD

**Issue by deiruch** [dotnet/docs#15769]
It's not obvious what happens when the using-variable is captured by a closure. For example

using(var a = ...)
  return collection.Where(o =&gt; a.Contains(o));

IMHO, the documentation should discuss the result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by KSib** [comment]
Agreed, I'm not sure how this works either.

**Comment by KSib** [comment]
At least linking to this might help some others: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations 

The helpful bit is "It tells the compiler that the variable being declared should be disposed at the end of the enclosing scope."
