### ISSUE TITLE
Move F# Core Library Reference to docs.microsoft.com and update to 4.7

### ISSUE THREAD

**Issue by PhilT** [dotnet/docs#15779]
**Help us make content visible**

I Googled for `NativePtr` which sends you to msdn. However, this is outdated and didn't contain any references to newer functions such as `toVoidPtr`. The GitHub repo for it says it's being migrated to docs.microsoft.com but I've seen no evidence of this.

References to API docs on docs.microsoft.com all point to msdn with a warning saying the doc.microsoft.com reference is not complete. For example, https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/strings. Clicking Core.String Module at the bottom takes
you to https://msdn.microsoft.com/visualfsharpdocs/conceptual/core.string-module-%5bfsharp%5d

**Describe the new article**

I suggest, as a first pass, take the existing documentation and move it to docs.microsoft.com albeit in the required new format, but don't change the content. 

Once that is done, we can then begin the process of updating it.

As a newbie to the language and .NET framework I'm having having a hard time getting to grips with F# after being a Ruby dev for 15 years and having everything fully documented and searchable. Granted, the ecosystem is much larger but that's why it needs to be better.

I'm happy to help with the conversion process where I can.

**Comment by mairaw** [comment]
Adding @cartermp here. Thanks for your feedback @PhilT. 

We should start the migration of the F# MSDN articles soon. As you said, they will be first migrated as-is and then we can start updating the docs.

Thanks for volunteering to help. I think for now it's not needed.

**Comment by abelbraaksma** [comment]
@mairaw, is there by way we can already update the contents? It's hard to remember our keep track of everything one likes to improve and it really blocks us with contributing. In the referenced bug, I mention that both docs and msdn invite you to improve by adding pr's, but this seems to have left us with dozens of requests for msdn hanging in limbo for months.

Also, searching on either site doesn't work as expected and doesn't find even the most trivial articles. 

If the repo is already somewhere where we could make pr's against it would come a long way, as long as we know how to find article X from msdn in location Y in docs.

**Comment by cartermp** [comment]
You can find the latest generated reference here: https://fsharp.github.io/fsharp-core-docs/reference/fsharp-nativeinterop-nativeptrmodule.html

Closing this out since we'll be using the community-generated reference for the time being
