### ISSUE TITLE
Update ML.NET AutoML docs with the recommender task

### ISSUE THREAD

**Issue by natke** [dotnet/docs#15775]
The recommender task is now supported in the AutoML API: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.recommendationexperiment?view=ml-dotnet-preview

These docs need to be updated:
- https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api
- https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli

**Comment by mairaw** [comment]
Can I mark these as enhancement?

**Comment by natke** [comment]
Sure @mairaw
