### ISSUE TITLE
libgdiplus doesn't exist

### ISSUE THREAD

**Issue by micheleissa** [dotnet/docs#15786]
when trying to follow instructions regarding the installation of libgdiplus brew gives the following error message:
```
Error: No available formula with the name "libgdiplus" 
==&gt; Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==&gt; Searching for similarly named formulae...
This similarly named formula was found:
mono-libgdiplus ✔
To install it, run:
  brew install mono-libgdiplus ✔
==&gt; Searching taps...
==&gt; Searching taps on GitHub...
Error: No formulae found in taps.
```

So apparently the correct lib is mono-libgdiplus. I think the docs should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86dd5e9-34ef-44b5-242a-709f33bf0e1f
* Version Independent ID: 82f8b771-aab3-a14b-7056-7a967f121ab2
* Content: [Prerequisites for .NET Core on Mac](https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore30&source=docs#feedback)
* Content Source: [docs/core/macos-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/macos-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @micheleissa. @Thraka you might want to look at this since you're working on this article now. /cc @leecow
