### ISSUE TITLE
Code Smell link is broken

### ISSUE THREAD

**Issue by KoditkarVedant** [dotnet/docs#15783]
Link given for "Code Smell" is broken - https://deviq.com/code-smells/  - It displays the below error.

![image](https://user-images.githubusercontent.com/18693839/68534630-78654a00-035c-11ea-9904-7cdce05bf836.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil @mvelosop it seems that all deviq.com links that you use in the e-books are not working. Not sure if this is a temporary issue or not.

**Comment by mvelosop** [comment]
Thanks for the heads up @KoditkarVedant!

Will e-mail @ardalis about this!

**Comment by mvelosop** [comment]
This is fixed thanks to @ardalis!

So I'm closing this now.
