### ISSUE TITLE
need a link to download please

### ISSUE THREAD

**Issue by dlwiii** [dotnet/docs#15782]
need a link to download please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf0043f-baf5-d2ab-84a5-718f900c0e25
* Version Independent ID: c3fabde5-775f-63f9-6b22-425435e096d8
* Content: [.NET API analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer#feedback)
* Content Source: [docs/standard/analyzers/api-analyzer.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/api-analyzer.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @OliaG
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
As stated in the article, you need to reference the [Microsoft.DotNet.Analyzers.Compatibility](https://www.nuget.org/packages/Microsoft.DotNet.Analyzers.Compatibility/) package in your project to able to use it. I'll change the instructions a bit to make this a bit more clear.

**Comment by dlwiii** [comment]
Thank you.
