### ISSUE TITLE
Services Wont Start after "Tutorial: Create a Windows service app"

### ISSUE THREAD

**Issue by Cylis0509** [dotnet/docs#15804]
I followed the tutorial: Tutorial: Create a Windows service app from Microsoft and everything worked as it was supposed to but now my windows services will not start. It sits there with "Not Responding".

How do I fix this?

It comes up after about 10 minutes.

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Tutorial: Create a Windows service app](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Cylis0509. We'd have to investigate what's wrong with the article. This issue is in our backlog for now.
