### ISSUE TITLE
String List Error

### ISSUE THREAD

**Issue by MrKinetiCat** [dotnet/docs#15806]
Im having an issue with the var names = new List&lt;string&gt; line. It keeps saying list&lt;&gt; could not be found, I really hope this is just me being blind and not the program application. Am I supposed to enter a name for the list? Oh by the way I also checked out the local version too, same issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Data collections - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Make sure you add the following `using` directive:

```csharp
using System.Collections.Generic;
```

**Comment by gewarren** [comment]
It's working for me in the browser. Does your code look like this?

![image](https://user-images.githubusercontent.com/24882762/68627293-48b85e00-0492-11ea-8977-2f1ba4f35dd7.png)

**Comment by tylerlittle** [comment]
Make sure you are using `List<int>` and not `list<int>`.

**Comment by an31146** [comment]
The index offsets in the names List should be zero-based, in step=2 of Modify list contents:
<code>Console.WriteLine($"I've added {names[1]} and {names[2]} to the list.");</code>

**Comment by gewarren** [comment]
> The index offsets in the names List should be zero-based, in step=2 of Modify list contents:
> `Console.WriteLine($"I've added {names[1]} and {names[2]} to the list.");`

I think it's actually correct as written. The list originally contained your_name, Ana, and Felipe. Then we added Maria and Bill and removed Ana. So now the list is your_name 0, Felipe 1, Maria 2, Bill 3, and we want to output that we added Maria and Bill. So 2 and 3 are the correct indexes.

**Comment by gewarren** [comment]
I'm going to close this issue due to inactivity and since it seems likely that the cause was a user error, possibly due to lower case "list".
