### ISSUE TITLE
Code Sample Not Working: zip File being Downloaded

### ISSUE THREAD

**Issue by rich-newman** [dotnet/docs#15803]
**Issue description**

The URL provided downloads a zip file when used with HttpClient for me.  This means the code sample doesn't work, since it expects plain text.  The URL was updated recently by issue #14911. 

Am I missing something or is it broken?

- [X ] .NET Core 3.0
- [X ] .NET Framework 4.8
- [ ] .NET Standard

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aeee012-d49e-e096-229c-44d38063b34f
* Version Independent ID: 86f4283b-fd68-22b5-c546-afe3c554d434
* Content: [Walkthrough: Creating a Dataflow Pipeline](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline)
* Content Source: [docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @rich-newman. We'll have to look into this issue.

**Comment by johanwallenborg** [comment]
@rich-newman I also tried this example out tonight and changed the HttpClient-part to following as a quickfix:

HttpClientHandler handler = new HttpClientHandler()
{
   AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
};

return await new HttpClient(handler).GetStringAsync(uri);
