### ISSUE TITLE
[WinForms] deprecated controls removed

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#15813]
## Removal of deprecated controls

While preparing the support for Windows Forms applications in .NET Core, we've decided to remove a set of controls that are no longer supported and have had replacements since .NET Framework 2.0.  These controls will no longer exist in the .NET Core code base and Windows Forms developers should refer to below for the suitable replacements.

The following types are no longer available:

* `Menu`
* `MenuItemCollection`
* `MainMenu`
* `ContextMenu`
* `MenuItem` 
* `IMenuEditorService`
* `ToolBar`
* `ToolBarAppearance`
* `ToolBarButton`
* `ToolBarButtonCollection`
* `ToolBarButtonClickEventArgs`
* `ToolBarButtonClickEventHandler`
* `ToolBarButtonStyle`
* `ToolBarTextAlign`
* `DataGrid`
* `DataGridBoolColumn`
* `DataGridCell`
* `DataGridColumnCollection`
* `DataGridColumnStyle`
* `DataGridDefaultColumnWidthTypeConverter`
* `DataGridLineStyle`
* `DataGridParentRowsLabel`
* `DataGridParentRowsLabelStyle`
* `DataGridPreferredColumnWidthTypeConverter`
* `DataGridTableCollection`
* `DataGridTableStyle`
* `DataGridTextBox`
* `DataGridTextBoxColumn`
* `GridColumnStylesCollection`
* `GridTablesFactory`
* `GridTableStylesCollection`
* `IDataGridEditingService`
* `HitTestType`

### Version introduced

3.1

### Old behavior

The above controls and types were available.

### New behavior

The controls and types are no longer available.

### Reason for change

Since after .NET Framework 2, these set of controls have had replacements with updated design and support.  This list of controls has been removed from designer toolboxes for some time in favor of their replacements and we have observed customers using these newer controls.  In examining what areas of Windows Forms we will bring forward to .NET Core, it was decided that we should not carry forward deprecated APIs like this set in order to maintain support for areas like high DPI, accessibility, and reliability.

### Recommended action

Move to the replacement APIs for these controls and their scenarios:

| Old Control (API) 	| Recommended Replacement                  	| Other associated APIs removed    	|
|-------------------	|------------------------------------------	|----------------------------------	|
| DataGrid          	| DataGridView                             	| DataGridCell, DataGridRow, DataGridTableCollection, DataGridColumnCollection, DataGridTableStyle, DataGridColumnStyle, DataGridLineStyle, DataGridParentRowsLabel, DataGridParentRowsLabelStyle, DataGridBoolColumn, DataGridTextBox, GridColumnStylesCollection, GridTableStylesCollection, HitTestType      	|
| Toolbar           	| ToolStrip                                	| ToolBarAppearance |
| ToolBarButton         | ToolStripButton                           | ToolBarButtonClickEventArgs, ToolBarButtonClickEventHandler, ToolBarButtonStyle, ToolBarTextAlign	|
| ContextMenu       	| ContextMenuStrip                         	|                                  	|
| Menu              	| ToolStripDropDown, ToolstripDropDownMenu 	| MenuItemCollection                                 	|
| MainMenu          	| MenuStrip                                	|                                  	|
| MenuItem          	| ToolstripMenuItem                       	|                                  	|

### Category

- Windows Forms

### Affected APIs

* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu.menuitemcollection?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.mainmenu?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.contextmenu?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menuitem?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbar?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbarappearance?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbarbutton?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbar.toolbarbuttoncollection?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbarbuttonclickeventargs?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbarbuttonstyle?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolbartextalign?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagrid?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridboolcolumn?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridcell?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridcolumnstyle?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridlinestyle?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridparentrowslabelstyle?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridpreferredcolumnwidthtypeconverter?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridtablestyle?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridtextbox?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridtextboxcolumn?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.gridcolumnstylescollection?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.gridtablesfactory?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.gridtablestylescollection?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.idatagrideditingservice?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagrid.hittesttype?view=netcore-3.0
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.design.imenueditorservice?view=netcore-3.0

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
Documented here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls

**Comment by RussKie** [comment]
Thank you

**Comment by RussKie** [comment]
@mairaw @gewarren as mentioned in https://github.com/dotnet/winforms/issues/2614#issuecomment-570128217 the deprecated controls are marked as still applicable to .NET Core 3.1. 
E.g. 
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagrid?view=netframework-4.8#applies-to
* https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu?view=netframework-4.8#applies-to
![image](https://user-images.githubusercontent.com/4403806/71654848-01f72e00-2d88-11ea-8ede-ac7ee4021771.png)


How do we fix it?

**Comment by timheuer** [comment]
Good catch! @mairaw -- wonder if we can batch update all of these updates to the ref docs?

**Comment by RussKie** [comment]
Further realisation - we have removed a number of members on `Control` and descendant types. They were noted on the original PR, but I have failed to list them here:

- Remove the following members in `AxHost` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `Control` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
	* `void OnContextMenuChanged(EventArgs e)`
- Remove the following members in `Form` type:
	* `MainMenu Menu { get; set; }`
	* `MainMenu MergedMenu { get; }`
	* `void Control.OnContextMenuChanged(EventArgs e)`
- Remove the following members in `NotifyIcon` type:
	* `ContextMenu ContextMenu { get; set; }`
- Remove the following members in `PrintPreviewDialog` type:
	* `MainMenu Menu { get; set; }`
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `ToolStripDropDown` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `TreeNode` type:
	* `ContextMenu ContextMenu { get; set; }`
- Remove the following members in `UpDownBase` type:
	* `ContextMenu ContextMenu { get; set; }`


I'm happy to send a PR with the fix if you could point where corresponding pages for these are.

**Comment by gewarren** [comment]
@RussKie The file is here: https://github.com/dotnet/docs/blob/master/includes/core-changes/windowsforms/3.1/remove-controls-3.1.md

**Comment by RussKie** [comment]
I meant we need to update corresponding pages for each control, e.g. this has to be removed for .NET Core 3.1:
![image](https://user-images.githubusercontent.com/4403806/71699310-fc92f580-2e12-11ea-9638-bfec96da75a6.png)

**Comment by gewarren** [comment]
Okay, I'm not sure how to do that so we'll have to wait for @mairaw. Should I go ahead and update the breaking changes file I linked to?

**Comment by RussKie** [comment]
As [pointed on SO](https://stackoverflow.com/a/59552608/2338036) (thank you @mairaw for the link) we have another issue - all removed types still appear as available in 3.1.
E.g. this link shouldn't work: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu?view=netcore-3.1

**Comment by mairaw** [comment]
Thanks @RussKie. I've opened https://github.com/dotnet/dotnet-api-docs/issues/3738 to track this issue.

**Comment by gewarren** [comment]
@PriyaPurkayastha We have the removed types/controls listed [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls). Should we add the removed members on Control and descendant types to that same breaking change entry?

- Remove the following members in `AxHost` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `Control` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
	* `void OnContextMenuChanged(EventArgs e)`
- Remove the following members in `Form` type:
	* `MainMenu Menu { get; set; }`
	* `MainMenu MergedMenu { get; }`
	* `void Control.OnContextMenuChanged(EventArgs e)`
- Remove the following members in `NotifyIcon` type:
	* `ContextMenu ContextMenu { get; set; }`
- Remove the following members in `PrintPreviewDialog` type:
	* `MainMenu Menu { get; set; }`
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `ToolStripDropDown` type:
	* `ContextMenu ContextMenu { get; set; }`
	* `event EventHandler ContextMenuChanged`
- Remove the following members in `TreeNode` type:
	* `ContextMenu ContextMenu { get; set; }`
- Remove the following members in `UpDownBase` type:
	* `ContextMenu ContextMenu { get; set; }`

**Comment by PriyaPurkayastha** [comment]
Yes, I think the same breaking change entry may be updated but Winforms team (@RussKie @OliaG) can decide if they want a separate entry for it. 
@RussKie to be clear, we are saying that documentation will need to be updated in two locations - breaking change (https://github.com/dotnet/docs/blob/master/includes/core-changes/windowsforms/3.1/remove-controls-3.1.md) and API documentation that Maira is tracking via https://github.com/dotnet/dotnet-api-docs/issues/3738

**Comment by mairaw** [comment]
The API documentation was already sorted out earlier this week.

**Comment by RussKie** [comment]
I have a split mind about updating the breaking changes page. Personally I think the absence of members can now be easily inferred and looked up in the docs. Previously it wasn't the case.
Happy to send a PR with an update if you think it is worth adding.

**Comment by PriyaPurkayastha** [comment]
Thanks @mairaw
@RussKie please submit a PR for these changes.
