### ISSUE TITLE
Download links are dead

### ISSUE THREAD

**Issue by seantleonard** [dotnet/docs#15818]
Hello,

The links to all versions of .NET framework on this page, lead to 404 errors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9491cf7-9be8-f55d-1e55-cdfb4316fe86
* Version Independent ID: fd533ab6-173d-58a4-dac8-9eb6b5ef7c20
* Content: [Install the .NET Framework on Windows XP](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-xp)
* Content Source: [docs/framework/install/on-windows-xp.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/on-windows-xp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by Youssef1313** [comment]
I think the links should go to:

- For .NET Framework 4.0: <https://dotnet.microsoft.com/download/dotnet-framework/net40>
- For .NET Framework 4.0.3 : <https://www.microsoft.com/download/details.aspx?id=29053>
- For .NET Framework 3.5: <https://www.microsoft.com/download/confirmation.aspx?id=21>

**Comment by Youssef1313** [comment]
I'm seeing something strange:

![image](https://user-images.githubusercontent.com/31348972/68649925-7d78f380-052c-11ea-9915-88ae3f13c828.png)

The same fwlink is linked to .NET Framework 3.5 in an article, and to .NET Framework 4.0 in another article.

**Comment by Thraka** [comment]
I think we try to avoid FWLinks now. I would just update them to the direct links. It's what the contributors guide says to do.

@Youssef1313 I assigned you since you gathered the information already 😄

**Comment by Youssef1313** [comment]
@Thraka, In this comment, https://github.com/dotnet/docs/pull/15460#issuecomment-547121654, @mairaw says not to change fwlinks that point to downloads. That's why I suggested to update only the 4.0.3 version not to use fwlink, and keep the others with the fwlink but let you update it internally.
