### ISSUE TITLE
MetadataLoadContext is NOT inherent to coreclr however MetaDataReader is

### ISSUE THREAD

**Issue by KoromaruKoruko** [dotnet/docs#15824]
Target framework: .NET Core 3.0
Doc: https://github.com/dotnet/docs/blob/master/docs/standard/assembly/index.md

The Reference to System.Reflection.MetadataLoadContext is not a part of the .Net Core 3.0 runtime. and as such, I propose that the reference be changed to System.Reflection.MetaData.MetaDataReader or System.Reflection.MetaData.PEReader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac305e0-d5f4-028e-d801-615e457c9c26
* Version Independent ID: 9abcd631-8133-0e05-b1b4-e22b5319ad1f
* Content: [Assemblies in .NET](https://docs.microsoft.com/en-us/dotnet/standard/assembly/)
* Content Source: [docs/standard/assembly/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/index.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@dedady157 Our current guidance is to use MetadataLoadContext as the way to read assembly metadata without fully loading the assembly.

@sdmaclea Would you be able to comment as to why this is preferred?

**Comment by sdmaclea** [comment]
`MetadataLoadContext` was the new technology introduced during the .NET Core 3.0 investment to replace the unsupported `ReflectionOnlyLoad` feature. 

`MetadataLoadContext` is a cross platform .NET Standard solution and is a viable technology for .NET Framework, .NET Core, or .NET Standard...

I think the `MetadataLoadContext` interface is a better substitute for the scenarios we saw `ReflectionOnlyLoad` being used for. The other mentioned interfaces are lower level and will likely be harder to use.

Perhaps the language should be updated. "You can load an assembly just to inspect it by using the xref:System.Reflection.MetadataLoadContext class ~~in .NET Core~~"

**Comment by dedady157** [comment]
Ye after looking through the meta data reader/pe reader coding style, I would say keep the metadataloadcontext reference however I'd go a step and say that "it is the preferred/optimal method on both. Net Framework and .Net Core (available as platform extension on nuget)"

**Comment by gewarren** [comment]
Easy fix; reopening.
