### ISSUE TITLE
Unmanaged C++ library unloadability in C# example

### ISSUE THREAD

**Issue by Vinigas** [dotnet/docs#15838]
It would be great if there was examples not only how to load/unload c# libraries to AssemblyContext, but also how to do it with unmanaged libraries (e.g. written in C, C++, C++/CLI). Maybe including what modifications needs to be done in unmanaged library's source code for this feature to work. Better documentation in this area would open gates for more users to hook existing unmanaged code (which may be in-use for old closed-source industrial protocols, and remastering it not worth the cost) to .NET platform. Unmanaged code unloadability is useful, then you don't trust unmanaged code's ability to do multithreading properly, but you know that single-threaded scenarios are well-tested, so in this case it's cheaper to load multiple times the same unmanaged library as a C# disposable class instance to get the job done.

I may add some possible examples to this post then I do more research here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3283764-f15a-fa5f-5106-6f294c780f7b
* Version Independent ID: b03cedce-9074-9686-0b31-045b2b4c862d
* Content: [How to use and debug assembly unloadability in .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#feedback)
* Content Source: [docs/standard/assembly/unloadability.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/unloadability.md)
* Product: **dotnet**
* GitHub Login: @janvorli
* Microsoft Alias: **janvorli**

**Comment by mairaw** [comment]
Thanks for your suggestion @Vinigas. @janvorli can you comment on this request?

**Comment by janvorli** [comment]
If code loaded into an unloadable context uses pinvokes to call functions in a native shared library and then gets unloaded, the library stays in memory forever. 
If you want to be able to unload a native library when you don't need ti anymore, there is a new mechanism for explicit loading and freeing shared libraries and getting symbols from them - see https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.0. It is completely separate from the pinvoke mechanism. To call a native method using this mechanism, you'd get a function address using the NativeLibrary.GetExport method and pass it to the GetDelegateForFunctionPointer<TDelegate>(IntPtr) to get a managed delegate that you can call later.
