### ISSUE TITLE
Why all the delegates are multicast?

### ISSUE THREAD

**Issue by ernest-morariu** [dotnet/docs#15849]
"The original design considered making a distinction between delegates where only one target method could be attached and invoked, and delegates where multiple target methods could be attached and invoked. That distinction proved to be less useful in practice than originally thought."

I think it's worth to provide more details here. At least conceptually, a multicast delegate that returns some value doesn't make very much sense. In such case, the return value is the one returned by the last element in the invocation list. 
To me it seems that the effort spent to make this mechanism type safe contrasts with the decision of having such delegate returning a "casual" value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcd91a4-603a-feb9-cff2-94f1985417fc
* Version Independent ID: a86cde90-1eba-e1d5-2b42-2a3cd37f5499
* Content: [System.Delegate and the `delegate` keyword](https://docs.microsoft.com/en-us/dotnet/csharp/delegate-class#feedback)
* Content Source: [docs/csharp/delegate-class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
