### ISSUE TITLE
Verify single instance of a process

### ISSUE THREAD

**Issue by gerardgit** [dotnet/docs#15841]
Verify single instance of a process.

Hello,
I have a desktop application in .net framework 3.5 which runs from a shortcut providing a parameter in the command line.
This command is the full path of an .exe, for example: "c: \ app \ dirpath \ apptest.exe". Several instances of the application can be executed, but with another parameter in the command line.
What I need is to be able to verify that no more than one instance of the application is running at the same time.
I tried to do this validation like this:

`System.Diagnostics.Process thisProcessesInstance = System.Diagnostics.Process.GetCurrentProcess();

**var** enumProcess = System.Diagnostics.Process
									.GetProcessesByName(thisProcessesInstance.ProcessName)
									.**Where**(process => {
										**return** process.Id != thisProcessesInstance.Id &&
											   process.StartInfo.Arguments == **Environment**.CommandLine;
									});

**if** (enumProcess != null && 0 < enumProcess.Count())
	**return** **false**;`

but process.StartInfo.Arguments always comes empty,
Does anyone know how to obtain the parameters of the command line of a process?

regards

**Comment by Thraka** [comment]
Hello!

Sorry to say, but this repository is not the right place to ask that question, this is repo is for documentation problems. I think you will have a better chance of getting your question answered if you post it on a forum such as [StackOverflow](https://stackoverflow.com/).

I'm going to close the issue.
