### ISSUE TITLE
Improve 'Create a .NET Global Tool' doc

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#15857]
I've read https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create.

I have two questions after reading this which aren't covered by the document:

* If I want the tool to support multiple TargetFrameworks, e.g. .NET Core 2.1 and .NET Core 3.0. Should I add these `TargetFrameworks`? Or is there an automatic roll forward for tools?
* Should I add a `TargetLatestDotNetRuntime` `false` to my csproj?

cc @KathleenDollard @agc93

(edit by @Thraka:  adding the article details)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [How to create a .NET Core Global Tool - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Great questions. I'll add this issue to our backlog. When we get time to update these articles, we'll include this scenario. Perhaps @KathleenDollard can answer these questions now.

**Comment by tmds** [comment]
> If I want the tool to support multiple TargetFrameworks, e.g. .NET Core 2.1 and .NET Core 3.0. Should I add these TargetFrameworks? Or is there an automatic roll forward for tools?
Should I add a TargetLatestDotNetRuntime false to my csproj?

@KathleenDollard can you answer these two questions?

**Comment by Thraka** [comment]
@wli3 may know also

**Comment by wli3** [comment]
> If I want the tool to support multiple TargetFrameworks, e.g. .NET Core 2.1 and .NET Core 3.0. Should I add these TargetFrameworks? Or is there an automatic roll forward for tools?

You should add TargetFrameworks. There is no automatic roll forward.

> Should I add a TargetLatestDotNetRuntime false to my csproj?

Are you referring to "RollForward" property? https://github.com/dotnet/sdk/pull/3296

Just like any framework dependent deployment, you should test your application when you change TargetFramework. If you set RollForward, it will roll forward whenever there is a new runtime. And you will have the risk of your existing tools cannot run on the new runtime.

**Comment by tmds** [comment]
> Are you referring to "RollForward" property? dotnet/sdk#3296

I was referring to this:

https://github.com/aspnet/EntityFrameworkCore/blob/0d76bbf45a42148924b413ef8f37bf49c1ce10d3/src/ef/ef.csproj#L14

but I guess that's a no-op?

Do tools have require a minimal patch version of the runtime? Or will they work on any patch version?

**Comment by wli3** [comment]
It should be a no-op for other projects. It should be an internal property for EF repo's build system.

> minimal patch version of the runtime

Depends on target framework. We try to require the lowest compatible runtime version. Some of them are hard coded due to historical release. But mostly it is the MAJOR.MINOR.0 version of the runtime. 

The current list (this would change)

```
TargetFrameworkVersion="1.0" RequireRuntimeVersion="1.0.5" 
TargetFrameworkVersion="1.1" RequireRuntimeVersion="1.1.2" 
TargetFrameworkVersion="2.0" RequireRuntimeVersion="2.0.0"
TargetFrameworkVersion="2.1" RequireRuntimeVersion="2.1.0" 
TargetFrameworkVersion="2.2" RequireRuntimeVersion="2.2.0"
TargetFrameworkVersion="3.0" RequireRuntimeVersion="3.0.0"
```

You can reference the test 

https://github.com/dotnet/sdk/blob/b28a8efbfb30d84019351abb3aa9a2b15e008662/src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs#L38

and the core the generate that https://github.com/dotnet/core-sdk/blob/094772592cbca521dbb95ee6bacafa3add5f5957/src/redist/targets/GenerateBundledVersions.targets

**Comment by tmds** [comment]
Thank you @wli3 , this is the info I was looking for.
