### ISSUE TITLE
Web App deployed to IIS using SCD still require the hosting bundle in the target machine

### ISSUE THREAD

**Issue by norcino** [dotnet/docs#15859]
It is not mentioned anywhere that in order to be able to deploy a .net core Web App, you require in the target machine to have installed the Hosting Bundle and runtime which you are targeting, even when using SCD.
This is misleading, SCD and FDD are in practice behaving in the same way, or so it looks to me, when dealing with a Web App.

For example:
I have a server with hosting bundle 2.1, I tried to deploy a web app targeting 2.2 using SCD deployment, but the application is failing, either I downgrade the application targeting 2.1 or I install the hosting bundle 2.2 on the target machine.

Others with this issue:
https://stackoverflow.com/questions/54113388/net-core-self-contained-deployment-not-working
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/#feedback)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@norcino This is a tricky subject in that when you're building a web app, you're working with the ASP.NET Core SDK, not the .NET Core SDK. 

Is there something over at [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.0) or [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0) that help?

**Comment by norcino** [comment]
@Thraka 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.0
Does not mention that you need anyway the hosting bundle to be installed in the target machine, no matter if you use SCD or FDD deployment.

Here, https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0
there is on the very top a naked "Install the .NET Core Hosting Bundle" link, which is ok, but no where here either is mentioned that Hosting Bundle is needed and SCD and FDD make no difference in this type of deployment (beside side effects such payload of the deployable).

I might be wrong or missing something tough.

**Comment by Thraka** [comment]
FDD would need the runtime installed for sure, but SCD shouldn't.

@scottaddie Does ASP.NET Core apps need the hosting bundle installed even if you deploy as SCD?

**Comment by scottaddie** [comment]
@shirhatti Any ideas on this one?

**Comment by shirhatti** [comment]
SCD for .NET applications (including ASP.NET Core applications do not require any additional dependencies such as the hosting bundle).

Hosting ASP.NET applications in IIS, SCD or FDD require changes to IIS. The hosting bundle contains the IIS component required (IIS native module- ANCM) and .NET runtimes. There is no way around this. You need the IIS module to allow you to host ASP.NET Core applications in IIS.

If you wish not to install the .NET runtimes (say if you're doing SCD apps), you can pass the appropriate flags the hosting bundle exe to skip installing the shared runtimes and only install the native IIS module.

@guardrex Can speak to whether the ASP.NET docs already cover this and whether there's a candidate doc to cross-link to.

**Comment by guardrex** [comment]
We cover the switches in the hosting bundle installer section ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0#install-the-hosting-bundle

@shirhatti, would you like it to specify which switches to use for SCD-only. For `OPT_NO_RUNTIME=1` and `OPT_NO_SHAREDFX=1`, we can add ...

> Used when the server only hosts \[self-contained deployments (SCD)](/dotnet/core/deploying/#self-contained-deployments-scd).

**Comment by scottaddie** [comment]
Closing, as this issue was addressed in https://github.com/aspnet/AspNetCore.Docs/pull/15949.
