### ISSUE TITLE
Confusing description on DerivedClass

### ISSUE THREAD

**Issue by stcmz** [dotnet/docs#15864]
The section of *Implementing the dispose pattern for a derived class* doesn't mention why the pattern is to be applied.
IMHO, at least two understandings are possible:
1) because the derived class itself uses some unmanaged resources. That means if otherwise, there is no reason to apply the dispose pattern in the derived class.
2) because the base class implements IDisposable. If so, all subclasses of a disposable base class need to apply the dispose pattern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-base-class)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@stcmz #1 is correct. The intro paragraph would be clearer if it said "Instead, to release resources of a derived class..." rather than "Instead, to implement the dispose pattern for a derived class..."
