### ISSUE TITLE
Conflicting information for Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/docs#15866]
Conflicting information on the [doc page](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element?source=docs):

"`Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer`	... Controls whether custom `IList` indexers are used incorrectly (false) or **correctly (true)** by the `System.Windows.Data.Binding` class..."   

but [here](https://github.com/microsoft/dotnet/pull/968/files), it says the opposite... "...app must **opt in** to the change by adding the [switch] to the app config file and setting it to **false**"

see here...
https://github.com/microsoft/dotnet/pull/968/files#diff-400d80d469c7d4b228943e37d839dd5aR19-R29

So is the new behavior enabled via **true** or **false**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59350ee-7837-34f8-b50e-c9c136720155
* Version Independent ID: 19747ce7-da26-bf2e-5066-1df11e61b0d0
* Content: [&lt;AppContextSwitchOverrides&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element?source=docs)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @glenn-slayden.  
@vatsan-madhavan is this something you can help with?

**Comment by vatsan-madhavan** [comment]
From [`<AppContextSwitchOverrides>` Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element?source=docs) documentation: 

 Switch Name | Description | Introduced 
--- | ---|  --- |
Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer | Controls whether custom IList indexers are used incorrectly (false) or correctly (true) by the System.Windows.Data.Binding class. | .NET Framework 4.8

From [Data Binding improvement for KeyedCollection documentation](https://github.com/microsoft/dotnet/blob/master/Documentation/compatibility/wpf-databinding-should-use-key-not-indexer.md): 

>In order for the application to benefit from this change, it must run on the .NET Framework 4.7.2 or later, and it must opt in to the change by adding the following AppContext switch to the <runtime> section of the app config file and setting it to false
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7"/>
      </startup>
      <runtime>
        <!-- AppContextSwitchOverrides value attribute is in the form of 'key1=true|false;key2=true|false  -->
        <AppContextSwitchOverrides value="Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer=false" />
      </runtime>
    </configuration>
```

In general, `AppContext` based application compatibility flags (sometimes we call this a  *quirk*) in WPF, work like this: 

- The flag is only meaningful on a runtime >= _vFixIntroduced_ (v4.8 in this case)
- The value of the __flag_/_quirk_ depends on the _TargetFrameworkMoniker_ (TFM) of the application (i.e., the version of .NET that the app targets). 
  - The _default_ value of the _quirk_ is **false**. If the app's TFM>=vFixIntroduced, the _quirk) is set to **false** by default. (For e.g., when TFM=v4.8, the _quirk_ in discussion will get a default value of **false**). 
  - When TFM < _vFixIntroduced_, the _quirk_ gets a default value of **true**. (In this example, if the TFM of the app were 
4.7.2, then the _quirk_ in discussion would have a default value of **true**)
- Typically, the bug-fix is written in such a way that when _quirk_==**false**, the bug-fix is active, and when _quirk_==**true**, the bug-fix is turned-off. (yeah, a little bit of double-negative going on here... )
- The _quirk_ can be set to **true** or **false** regardless of TFM using `App.config` via the `AppContextSwitchOverrides` mechanism. 

What I've described above is the _general_ case. There are situations where the _quirk_'s default-initialization logic may be inverted, the _quirk_ may not be sensitive to TFM at all, etc. This is why each application compatibility flag gets its own documentation. 

From what I can tell, `Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer` follows the general pattern. 

@SamBent, does the documentation for  `Switch.System.Windows.Data.Binding.IListIndexerHidesCustomIndexer`  at [`<AppContextSwitchOverrides>` Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element?source=docs) have an error? I suspect that it inverts false/true...

**Comment by SamBent** [comment]
There are two errors.

First, the doc page for AppContext switches says:  
> Controls whether custom IList indexers are used incorrectly (false) or correctly (true) by the System.Windows.Data.Binding class.

The words 'false' and 'true' should be interchanged.

Second, the doc for "improvement for KeyedCollection" says
> In order for the application to benefit from this change, it must run on the .NET Framework 4.7.2 or later...

It should say
>In order for an application that targets an older version to benefit from this change, it must run on the .NET Framework 4.8 or later...
