### ISSUE TITLE
Voice tone doco

### ISSUE THREAD

**Issue by johnsimons** [dotnet/docs#1586]
Hi

I have read your [Voice and tone Guidelines](https://github.com/dotnet/docs/blob/master/styleguide/voice-tone.md) and I really like it. I like it so much that I would really love to use it for our own guidelines at https://github.com/octopusdeploy/docs.

Do you see any issues with us coping/pasting (modify ".NET core" with our own product name) the guidelines and publish as our own ? We would give credit to you of course.

**Comment by BillWagner** [comment]
@johnsimons Thank you for the kind words. I'm glad you liked it.  I've started an internal discussion to see what we can do here. I'll report back as soon as I can.

**Comment by johnsimons** [comment]
@billwagner here is what we are proposing https://github.com/OctopusDeploy/docs/pull/25

**Comment by BillWagner** [comment]
@johnsimons I like what you've written, and I've gotten the OK that you can use what we've published.

Thank you for asking.  I'll close this as resolved.
