### ISSUE TITLE
Is "compatibility" really the right term to use here?

### ISSUE THREAD

**Issue by madelson** [dotnet/docs#15860]
The docs say:

&gt; the C# language may have features that rely on types or runtime components that are not available in every .NET implementation. This also ensures that for whatever target your project is built against, you get the highest compatible language version by default.

This suggests that C# 8 is incompatible with older target frameworks, in that code compiled successfully with C# 8 against those frameworks might not run.

However, as far as I can tell, C# 8 will give an error if you try to use the incompatible features (e. g. if you try to write a default implementation for an interface method). Therefore, I'm not convinced that C# 8 is truly incompatible vs. being "more restricted" when targeting older frameworks.

Is my interpretation correct? If so, I would suggest changing the wording. If not, I would suggest clarifying the nature of the incompatibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @madelson 

We should clarify compile time compatibility vs. runtime compatibitily.

**Comment by cremor** [comment]
Related: dotnet/csharplang#2877
