### ISSUE TITLE
Windows Add/Remove Programs dialog box does not display all installed SDK versions

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#15865]
The comment below was Machine translated

@mshobohm commented on [Thu Nov 14 2019](https://github.com/dotnet/docs.de-de/issues/160)

With dotnet --list-sdks I get some old SDKs that I do not get displayed in the "Windows Add / Remove Programs dialog box". Consequently, they can probably only be deleted by deleting in the Explorer, I hope that is residue-free. The site could write something about this topic.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Entfernen von .NET Core Runtime und SDK - .NET Core](https://docs.microsoft.com/de-de/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows#uninstalling-net-core)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Fri Nov 15 2019](https://github.com/dotnet/docs.de-de/issues/160#issuecomment-554345763)

Hello, @mshobohm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The preceding is correct. Additionally, for the preview SDK versions it lists that VS installed, you get the following message

![image](https://user-images.githubusercontent.com/3605364/70363783-dab34c80-182d-11ea-997b-e6eb47bdbba1.png)

**Comment by Rick-Anderson** [comment]
cc @livarcocc

**Comment by yeahe83** [comment]
try reinstall the old version and then uninstall again.

**Comment by mshobohm** [comment]
Meanwhile I did a cure  by renaming  the c:\Program files\dotnet folder (3,7 GB) and installing only the latest SDK. My computer didnt explode, so I think these "irregular SDK  versions" can safely be deleted in the explorer. Perhaps one time we could have "dotnet --install-sdk" and "dotnet --remove-sdk"  harmonizing the download/installation/update on all operating systems, also for the runtime.
