### ISSUE TITLE
'dotnet sln todo.sln add **/*.csproj' - can't use glob pattern with command

### ISSUE THREAD

**Issue by Eilon** [dotnet/docs#15881]
I'm using .NET CLI `3.1.100-preview2-014569` and the glob pattern doesn't work with `dotnet sln add`.

```
C:\temp\b4&gt;dotnet sln b4.sln add *.csproj
Could not find project or directory `*.csproj`.
Usage: dotnet sln &lt;SLN_FILE&gt; add [options] &lt;PROJECT_PATH&gt;
...
```

It doesn't matter whether I specify the SLN name or not. Globbing just doesn't seem to be supported.

So, either the docs are wrong, or the product has a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@Eilon it seems you are on a Windows environment. The globbing only works on Unix/Linux shells. Do you think it's not clear the way it's described?

**Comment by Eilon** [comment]
Oh my, you are correct, it does say it all right there! I was looking only at the actual example code, not the text that was 50 pixels above it 😄

**Comment by dazinator** [comment]
I just made the same mistake :-(
