### ISSUE TITLE
Built-in vs simple vs primitive type semantics

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/docs#15883]
**Issue description** For example, in this article:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants

(Source: https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/constants.md)

> Only the C# **built-in** types (excluding System.Object) may be declared as const. For a list of the built-in types, see Built-In Types Table.

> All of the types in the table, except object and string, are referred to as **simple** types.

I find the choice of words here a bit confusing. Built-in to me can mean anything that is... well, built in, but the list of built-in types does not include things like `System.Numerics.Vector3` which comes built-in with .NET Core (though not .NET Framework or Mono). Also, "simple" is a fairly ambiguous term and I don't think it's helpful here.

I think it might make more sense to refer to these types as "primitive" types, since that is a common terminology that I hear a lot, and it's also used [here](https://docs.microsoft.com/en-us/dotnet/api/system.type.isprimitive). Thoughts?

**Target framework**

N/A, it's about general C# documentation.

**Comment by pkulikov** [comment]
> Built-in to me can mean anything that is... well, built in

The article talks about **C#** built-in types, which are all listed in the referenced table. I think it leaves little space for misinterpretations.

> Also, "simple" is a fairly ambiguous term and I don't think it's helpful here.

The "simple" term is defined here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types#simple-types

I agree, it's not very helpful in the article describing the built-in types.

> I think it might make more sense to refer to these types as "primitive" types, since that is a common terminology that I hear a lot, and it's also used [here](https://docs.microsoft.com/en-us/dotnet/api/system.type.isprimitive). Thoughts?

According to the [link](https://docs.microsoft.com/en-us/dotnet/api/system.type.isprimitive?view=netframework-4.8#remarks), the "primitive" types are **not** "these types". Primitive types include all simple types, *except* `decimal`, and additionally include the `IntPtr` and `UIntPtr` types.

So, the built-in, simple, and primitive types are three distinct type sets.

**Comment by pkulikov** [comment]
As for the example (about the constants), the better wording is in the [const article](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/const):

> Constants can be numbers, Boolean values, strings, or a null reference. 

It uses neither "built-in" nor "simple" terminology but merely lists the concrete types. I think it's simpler to comprehend.
