### ISSUE TITLE
Edit pass on grpc e-book content

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#15889]
Book content would benefit from an editorial review.

Here's the entry point for the book:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/index

**Comment by BillWagner** [comment]
@mairaw Has the edit pass for the entire book been completed? Should this be closed?

**Comment by BillWagner** [comment]
closing as all related PRs have been merged.
