### ISSUE TITLE
Include list of valid Main signatures

### ISSUE THREAD

**Issue by gabeluci** [dotnet/docs#15882]
Any chance this article could contain the list of all valid signatures, like what is in the blog post [C# 7 Series, Part 2: Async Main](https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/)?

All the signatures can be inferred from the information given in this article, but I just find it easier to pick out the one I want from a list rather than read through the points and figure it out. It would also help newcomers to C# who may not see the direct relation from those points to what the code should actually look like.

This is the list I'm talking about:

```
public static void Main();
public static int Main();
public static void Main(string[] args);
public static int Main(string[] args);
public static Task Main();
public static Task<int> Main();
public static Task Main(string[] args);
public static Task<int> Main(string[] args);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6280abc4-899a-187d-1de4-1ea629ac5419
* Version Independent ID: 24dbcd84-98c0-421e-d586-5d081ce2ec34
* Content: [Main() and command-line arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/)
* Content Source: [docs/csharp/programming-guide/main-and-command-args/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/main-and-command-args/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @gabeluci I agree, a list would be useful here.

I've added this to our backlog, and added the up-for-grabs label for any community members to address. If you'd like to submit a PR with the updates, I'll watch for it and help get it published.
