### ISSUE TITLE
incorrect annotation of AuctionItems image

### ISSUE THREAD

**Issue by turkycat** [dotnet/docs#15894]
near the top of this page the content reads:

"In the image above, the Group by category and Sort by category and date CheckBoxes are selected."

the image does not show the "sort by category and date" box checked as described. Display of the items does not match the description that follows (categories are not in alphabetical order).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data binding overview - WPF](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/data/data-binding-overview#feedback)
* Content Source: [docs/desktop-wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/desktop-wpf/data/data-binding-overview.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@turkycat Thank you for reporting this. I'll get it fixed up.
