### ISSUE TITLE
Update for .NET Core 3.0

### ISSUE THREAD

**Issue by tanukus** [dotnet/docs#15893]
Hello, Are there plans to update this guide for .NET Core 3.0?, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/index#feedback)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @tanukus,

Yes, it's in the plans, but first comes the 3.0 release for eShopOnContainers, you can take a peek in the [dotnet3-migration/dev-dotnet3](https://github.com/dotnet-architecture/eShopOnContainers/tree/dotnet3-migration/dev-dotnet3) branch.

Hope this helps.

**Comment by nishanil** [comment]
Hey @tanukus, We've updated the guidance and the referencing samples to 3.1. Thanks for your patience. Please do share your feedback on the content :)

Closing this issue.
