### ISSUE TITLE
Link broken to Sample

### ISSUE THREAD

**Issue by james1301** [dotnet/docs#15890]
The link is broken to Async Sample: Accessing the Web Walkthrough (C# and Visual Basic). Cannot find this sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494fdee9-0e2c-55bc-dfc0-bc1e5809476f
* Version Independent ID: 3f6b5873-7f2c-a463-bcd3-8093f4af9a2a
* Content: [Walkthrough: Accessing the Web by Using async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
There is a [project](https://github.com/dotnet/docs/projects/88) to migrate samples from code.msdn.microsoft.com, but now the code.msdn is retired. I'm not sure if there is a backup from the code somewhere to use it and migrate to samples repo.
/cc @mairaw @BillWagner

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @james1301 

@dend Do you know where I can find those assets to move them now that CodeGallery is retired?

**Comment by Youssef1313** [comment]
I've found the sample [here](https://github.com/GeorgeVan/Task_Async/tree/8c178c0abfe715d52accbe4c66ff1835b2e3d8d0/15_AsyncMisc). The 3 projects of the samples are `AsyncWalkthrough`, `AsyncWalkthrough_HttpClient`, and `SyncWalkthrough`.
