### ISSUE TITLE
Single spacing

### ISSUE THREAD

**Issue by tlhintoq** [dotnet/docs#15906]
Its worth noting AND THERE SHOULD BE EXAMPLES HERE - that &lt;para&gt; started being double spaced with VS2017 and continues to be doubled spaced in VS2019.  Several issues were raised on MSDN about it and all were closed with no solution provided for creating single-spaced XML intellisense comments in our C# and F# code. All just say "not on our current road map".

It is now necessary to add &lt;br/&gt; breaks at the end of each line you want to have single spaced.
For example, if you wanted to include a single spaced block of code to your method.

```csharp
        /// <summary>Gets the angle (0-360, 0 being North) between two points. The angle is the direction from point 1 to point 2.
        /// <code> <para>
        /// GetAngle(0, 0, 1, 0) = 0<br/>
        /// GetAngle(0, 0, -1, 0) = 180<br/>
        /// GetAngle(0, 0, -1, 0) = 180<br/>
        /// GetAngle(0, 0, 0, 1) = 90<br/>
        /// GetAngle(0, 0, 0, -1) = 270<br/>
        /// </para></code>
        /// </summary>
        /// <param name="lat1"></param>
        /// <param name="long1"></param>
        /// <param name="lat2"></param>
        /// <param name="long2"></param>
        /// <returns></returns>
```

edit by @billwagner: format sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fc95e1-59ca-895f-dc67-b7397363689a
* Version Independent ID: 8cbd9296-638d-5e83-24a6-569b497835e2
* Content: [&lt;para&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/para)
* Content Source: [docs/csharp/programming-guide/xmldoc/para.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/para.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for creating this issue @tlhintoq I've added it to our backlog for us to address when we next update this article.

I've also added the "up for grabs" and "good first issue" label for any community members that want to address this.

**Comment by tlhintoq** [comment]
I just wanted to say "thanks for the ACK" on my feedback.  I don't think
I've ever gotten that before from leaving feedback on the microsoft
documentation. 

Is it a new mechanism that leaving feedback generates a git issue?  Or
did you do that after reading the feedback? 

Regards, 

Clint

On 21.11.2019 11:19, Bill Wagner wrote:

> Thanks for creating this issue @tlhintoq [1] I've added it to our backlog for us to address when we next update this article. 
> 
> I've also added the "up for grabs" and "good first issue" label for any community members that want to address this. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/tlhintoq
[2]
https://github.com/dotnet/docs/issues/15906?email_source=notifications&amp;email_token=ACWTLUWPOE7HMF55OIDC6C3QU2YI3A5CNFSM4JPUXRN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE2ZIKY#issuecomment-557159467
[3]

**Comment by nemrism** [comment]
@tlhintoq Are you goingto create the according PR?

**Comment by BillWagner** [comment]
reopening to address as part of updating the XML section.
