### ISSUE TITLE
list available versions for update

### ISSUE THREAD

**Issue by OzBob** [dotnet/docs#15901]
Is there a way to list out the available versions of a tool for update?

e.g. dotnet tool update dotnet-ef -g --version 3.0.0
works, but I would like to know if there is a version 3.1.0.

What is the download endpoint of all the tools that could be queried with this command:
e.g.
dotnet tool info dotnet-ef --versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8171f4-8466-98ed-acb8-49563b864d16
* Version Independent ID: a1b7af2d-e2ba-bc4b-4d35-a8edbaa1249f
* Content: [dotnet tool update command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-update)
* Content Source: [docs/core/tools/dotnet-tool-update.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-update.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@OzBob Hello.

I don't believe so. You would want something that looks at the NuGet package feed, such as the standalone [nuget cli](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)

**Comment by OzBob** [comment]
Powershell magic to the rescue:

Find-Package "dotnet-ef" -AllVersions -IncludePrerelease -ExactMatch | % {$_.Versions | % {$_.Version}}
