### ISSUE TITLE
KBs needed on Windows 7 could be clearer

### ISSUE THREAD

**Issue by nguerrera** [dotnet/docs#15900]
See conversation on https://developercommunity.visualstudio.com/content/problem/805039/net-core-30-failed-to-load-dll.html?childToView=827105#comment-827105

When reading quickly, it is not especially obvious that the KB for Windows 8.1 is for Windows 7 too. It says "and earlier", but the eye skips past Windows 8.1 section onto the Windows 7 section when looking for Windows 7 prerequisites. Also, the X in "In addition to X" in the Windows 7 section isn't a link so it's less obvious that there are two things to install for Windows 7.

I suggest being more redundant between the two sections and calling out all the steps needed for Windows 7 explicitly. I also think a bulleted or number list of action items in each section would be easier to follow than these paragraphs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by nguerrera** [comment]
Cc @jeffschwMSFT

**Comment by mairaw** [comment]
@Thraka can you check this feedback as you're making updates to this article right now?

**Comment by Youssef1313** [comment]
@mairaw, I just noticed your comment. Should I close my PR and let @Thraka handles that ?

**Comment by mairaw** [comment]
Yeah, I think so. Otherwise, it would cause merge conflicts for #15569 since we're removing this file.

**Comment by Youssef1313** [comment]
Closed it.

**Comment by nguerrera** [comment]
Probably worth waiting for this discussion to reach a conclusion before addressing this:

https://developercommunity.visualstudio.com/content/problem/805039/net-core-30-failed-to-load-dll.htm

On the technical side, the problem is almost certainly that KB2533623 is missing, but the customer is having trouble installing it.

**Comment by Thraka** [comment]
We'll be making this section clearer when this update to the docs ships. The current text looks like the following:

![image](https://user-images.githubusercontent.com/2672110/69260389-a58fd480-0b74-11ea-9d56-d7baed3b81fa.png)
