### ISSUE TITLE
Migration of "Async Sample: Accessing the Web Walkthrough"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#15907]
The link for the code.msdn was updated in #15902 to a docs.microsoft article as a temporary fix for the 404 error of the old link. When the sample is migrated, the link should point to the samples browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494fdee9-0e2c-55bc-dfc0-bc1e5809476f
* Version Independent ID: 3f6b5873-7f2c-a463-bcd3-8093f4af9a2a
* Content: [Walkthrough: Accessing the Web by Using async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
Original issue for bad link is #15890

**Comment by Youssef1313** [comment]
Can this be added in the migration project so it's easier to track this issue ?
