### ISSUE TITLE
Unit Test tutorials need better description to get started

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1591]
Both of the unit testing tutorials for .NET Core start 'hot', without providing a good introduction on how to start working on the tutorial.

The affected files are https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md and https://github.com/dotnet/docs/blob/master/docs/core/testing/using-mstest-on-windows.md

The new introduction should show:
1. How to start by creating the working directory and getting ready to create the new projects as currently described.
2. How to explore the finished solution by downloading the code from the github repository.

It should also explain why you would choose one or the other: The first provides an interactive experience where readers can bulid the solution and see how the solution grows. The second enables a quicker path to see a full solutions.

Note: this is based on a LiveFyre comment on the dotnet test article.

**Comment by mairaw** [comment]
@GuardRex I think this is a good one for you to work on next!
