### ISSUE TITLE
Error messages make little sense and provide no recourse as to what one can do

### ISSUE THREAD

**Issue by ldiablo** [dotnet/docs#15928]
There is very little information about the error messages returned by Sn.exe. If I try to Sn -i pkey.snk KEY_XXX I see "Object already exists" if I try to sn -pc KEY_XXX I get "Key does not exist" The behaviour does not make any sense and no recourse or advise is provided. It is a terrible tool. Whoever wrote it should be ashamed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d65a40-0ea7-09ce-33fc-39525310b05e
* Version Independent ID: f6cbd1c2-7708-03aa-a935-0dbfa07e6177
* Content: [Sn.exe (Strong Name Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool#feedback)
* Content Source: [docs/framework/tools/sn-exe-strong-name-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sn-exe-strong-name-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@vivmishra Do you know who can help with documenting Sn.exe error messages?

**Comment by ldiablo** [comment]
Is there any design documentation about Sn.exe? Maybe Microsoft has some design documents that would help provide better error messages. I was partly joking about the authors should be ashamed. If I wrote error messages like that at my company I would be crucified.

**Comment by ardalis** [comment]
@tdykstra can you remove the guide - ASP.NET Core web apps label from this issue? Thanks.
