### ISSUE TITLE
Should `else if` be formatted differently?

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#15922]
The current section about formatting `if/else/elif` is a bit unclear what to do in case of `else if`.
Should it be formatted exactly the same way as `elif` sample?

Consider the following code:
```fsharp
if a then
    b
else
    if c then
        d
    else
        e
```
`a,b,c,d & e` are all long or multiline expressions.
Question is do the same rules apply as described in 
> Multiple conditionals with elif and else are indented at the same scope as the if

Should the formatting be:
```fsharp
if a then
    b
else if c then
    d
else
    e
```
??

Related discussion: https://github.com/fsprojects/fantomas/pull/557#issuecomment-555981469

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#feedback)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by kspeakman** [comment]
`elif` is shorthand for `else if`. So I would assume the same rules apply.

**Comment by knocte** [comment]
@nojaf: maybe fantomas should replace all `else if` elements with `elif`? Problem solved.
