### ISSUE TITLE
C# Compiler error: CS7003 is undocumented

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1593]
# C# Compiler error: CS7003 is undocumented

# General

The compiler error: `error CS7003: Unexpected use of an unbound generic name`

**Comment by mairaw** [comment]
Link to a helpful SO question related to this compiler error: https://stackoverflow.com/questions/34456200/cs7003-unexpected-use-of-an-unbound-generic-name

**Comment by sputier** [comment]
I just submitted the PR #3614 to fix this issue. Let me know if this needs rework.
