### ISSUE TITLE
(How) does indexing by range work with multidimensional arrays?

### ISSUE THREAD

**Issue by deiruch** [dotnet/docs#15946]
The examples show only single-dimensional arrays being used with Ranges. (How) does Range-indexing work with multi-dimensional arrays?

If it doesn't work, is there a plan to make it work? Are there workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @deiruch I do need to cover this scenario in this tutorial.

I've added it to the next sprint to address.
