### ISSUE TITLE
Mistyped docker hub url of redis package 

### ISSUE THREAD

**Issue by raminrahimzada** [dotnet/docs#15966]
Hi, There is docker link of redis package in content of the page which is mistyped and redirects to 404 , the reason is it has an extra character - (%5C as encoded) <br/>
https://hub.docker.com/%5C_/redis/
i think it should be like that:
https://hub.docker.com/_/redis/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50f6767-3560-f097-a3de-3d88ed02b5f5
* Version Independent ID: c986e70a-be0c-c375-ef5e-556fbd8629d6
* Content: [Using a database server running as a container](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/database-server-container#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/database-server-container.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/database-server-container.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @raminrahimzada, thanks for the heads up! 😊
