### ISSUE TITLE
[WIP] Issues in the code snippets in Interfaces and Indexers C# programming guide 

### ISSUE THREAD

**Issue by srikarplus** [dotnet/docs#1597]
1. Interfaces( C# programming guide) code snippets were missing but were linked to the Indexers at docs.microsoft.com
2. Indexers code snippets containing code for Interfaces.

Further inspection revealed that this might be because of issues in migrating from msdn.microsoft to docs.microsft.  
I will resolve this issues at the earliest.

**Comment by BillWagner** [comment]
Closed as it was fixed in PR #1598
