### ISSUE TITLE
PR and Issue review may be delayed over U.S. Thanksgiving

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#15974]
This Thursday (November 28) and Friday (November 29) are holidays for the .NET content team members in the United States. Many of the team members are also taking vacation during this week.

The result is that PR reviews / merging, and Issue response may be delayed during this week and the upcoming weekend.

**Comment by gewarren** [comment]
Oops sorry, I thought I was just hiding it for myself. Repinned.

**Comment by BillWagner** [comment]
closing and unpinning.  I hope everyone enjoyed the time off.
