### ISSUE TITLE
dotnet/corefx and dotnet/coreclr are now consolidated into dotnet/runtime

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#15982]
I believe that references to dotnet/corefx and dotnet/coreclr should be revised and updated to dotnet/runtime.

For example:
https://github.com/dotnet/docs/blob/d824d1f83613302a599467faf306aa724904382b/docs/core/build/index.md#build-the-clr-from-source

**Comment by Youssef1313** [comment]
@mairaw, Is there an internal way you have to check if there are fwlinks that redirects to the coreclr or corefx repos ?

**Comment by mairaw** [comment]
I might be able to check a few @Youssef1313.

**Comment by mairaw** [comment]
Didn't find many. I've deleted one FwLink that had 0 views this past year.
