### ISSUE TITLE
option strict

### ISSUE THREAD

**Issue by uranthos** [dotnet/docs#15999]
whats the type for this:
Dim writeline1 = Sub(x) Console.WriteLine(x)
when option strict is on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c990469-8bae-a58d-6b39-682bb50bcd49
* Version Independent ID: b29e59f9-24fb-4bee-88f1-fc4dcf5ad0a6
* Content: [Lambda Expressions - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/lambda-expressions)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/lambda-expressions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by samtrion** [comment]
[System.Action<T>](https://docs.microsoft.com/en-us/dotnet/api/system.action-1)

**Comment by BillWagner** [comment]
Thanks for asking this question @uranthos 

@samtrion has answered correctly. I'll close this as answered.
