### ISSUE TITLE
Structs and shallow copy

### ISSUE THREAD

**Issue by tchawla8** [dotnet/docs#15997]
Structs are copied on assignment. When a struct is assigned to a new variable, all the data is copied, and any modification to the new copy does not change the data for the original copy. This is important to remember when working with collections of value types such as Dictionary&lt;string, myStruct&gt;.

I found this line confusing since it does not mention anything about shallow copy and when we use List or Dictionary inside structs they will indeed be shallow copied. Maybe rephrasing the above mentioned paragraph would be better. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58203aa-f1ff-0741-72a7-dd865a69b08a
* Version Independent ID: 35ebe8a9-4465-280e-082c-b3f74d031ac0
* Content: [Structs - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/structs#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/structs.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/structs.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @tchawla8 We should add more clarification here.

I've added it to our backlog to update when we next update this article.
