### ISSUE TITLE
How to communicate a child component and parent component and vice versa 

### ISSUE THREAD

**Issue by sarathlalsaseendran** [dotnet/docs#16001]
Kindly guide me how to communicate between child component and parent component and vice versa. I am looking for @Input and @Output like parameters in Blazor. We are re-writing a production app from Angular to Blazor. Kindly help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c195c0-99f6-64f5-66a3-4e69109dc8ee
* Version Independent ID: 24368808-4b90-f75a-e887-eb72a1c85f5b
* Content: [Build reusable UI components with Blazor](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components#feedback)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/components.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/components.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by danroth27** [comment]
@sarathlalsaseendran To communicate from a parent component to a child component the parent can pass normal component parameters to the child component. 

To communicate from a child component to a parent component there are a number of ways:
- The child component can expose an event or a callback that the parent subscribes to
- The parent component can provide a cascading value that the child component binds to as a cascading parameter and then uses to communicate with the parent
- Use a service that is injected into both the parent and child components

**Comment by sarathlalsaseendran** [comment]
Thank you very much @danroth27 for the quick response.
