### ISSUE TITLE
powershell auto complete not work

### ISSUE THREAD

**Issue by AHLinJie** [dotnet/docs#16023]
![image](https://user-images.githubusercontent.com/10792685/69794988-3f572180-1206-11ea-9c5f-13bcb2b2da7a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#feedback)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/staging/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
You need to change your execution policy to allow scripts to run. `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine` see [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6#inputs) for more information.
