### ISSUE TITLE
Incorrect package referenced for ASP.NET Core Runtime

### ISSUE THREAD

**Issue by robberry** [dotnet/docs#16030]
In the ASP.NET Core Runtime section the package installed via YUM is the .NET Core Runtime.  The package should be "rh-dotnet30-aspnetcore-runtime-3.0", therefore:

yum install rh-dotnet30-aspnetcore-runtime-3.0 -y

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666b79de-bce8-4180-3ddf-b1806d3f3605
* Version Independent ID: 5719761e-925b-fd17-9fb1-bafcb03214fe
* Content: [Install .NET Core on Linux RHEL 7 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-rhel7#feedback)
* Content Source: [docs/core/install/linux-package-manager-rhel7.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-rhel7.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@robberry Can you confirm that the command actually works? From talking to the Red Hat folks, it seemed that they had a single package that installed both the .NET Core runtime and the ASP.NET Core runtime, so the command was the same for both flavors. I'm going to follow up with them again in email just to make sure.

**Comment by Thraka** [comment]
I heard back from RH and they do have different packages for each type, so I'll update this.

Related to #15948

**Comment by robberry** [comment]
Great @Thraka - thanks for following that through with Redhat and updating the docs.
