### ISSUE TITLE
Labeling the web.api project part of application layer in fig 7.5  is misleading.

### ISSUE THREAD

**Issue by cjjohansen** [dotnet/docs#16044]
Labeling the web.api project part of application layer in fig 7.5  is misleading.

One goal isn DDD layering is to keep the Domain Model ignorant of technical/infrastructure concerns. According to Clean architecture and PortsAndAdapters architecture ApplicationLayer is part of the  Domain Model.

Since a Web or Webapi project referencees alot of technical libraries and deals with infrastructure concerns like http it should naturally belong to the PortsAndAdapter layer aka the infratructure layer.

Having an Authoritative brand like Microsoft posting this, makes it really hard to get rid of such misunderstandings.

Best Wishes from here
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 5a30bea5-326b-ea72-59ae-dfef1e190e4a
* Content: [Designing a DDD-oriented microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @cjjohansen, thank you for your feedback. 

If you notice *Ordering microservice* (Fig 7-5 or [Code](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Ordering)) it has 3 separate layers of API, Domain and Infrastructure. 
Though these projects has logically been grouped together under one "ordering" directory but these are separate from each other. 
So, the Domin Model layer is actually ignorant of any technical details or implementation. 

Hope this helps !

**Comment by cjjohansen** [comment]
The domain model entities are ignorant of infrastructure yes. But not the command handlers i.e the application layer part which is normally considered part of the domain too.  So web API stuff which is infrastructure and command handlers which are domain related are mixed together.

**Comment by CESARDELATORRE** [comment]
I don't agree on that statement you said: "ApplicationLayer is part of the Domain Model."
In DDD, you can also read in Eric Evans book that the Application Layer is different to the DomainModel Layer and certainly, the Application Layer is not part of the Domain Model. You should have a Domain Model layer for that which is infrastructure ignorant.

We can consider the WebAPI artifacts as part of the Application Layer in the same way you can also consider the MVC Controllers are part of the Application Layer or any custom Application class/service.

**Comment by CESARDELATORRE** [comment]
Also, I consider Commands/CommandHandlers and Integration-Events/Integration-Event-Handlers as Application Layer artifacts in the same way they are in the Application Layer for a CQRS approach.

However, Domain-Events and Domain-Event-Handlers are part of the Domain Model Layer (in the same way than Aggregates/Entities and Domain Service classes) and fully independent (Infrastructure Ignorant) with no dependencies to the Application Layer and Infrastructure Layer.

This is also how I present it in the Microservices book, too, and aligned to DDD and CQRS approaches.

**Comment by cjjohansen** [comment]
@CESARDELATORRE  Yes that could be misunderstod. Traditionally the domain model layer (entities + more)  and application layers (Commands, CommandHandlers + more) are two layers. But Its my impression that they are both considered part of the domain, and they should both NOT reference infrastructure layers. Where we differ is that I don't think WebAPI and MVC controllers belong to the application layer, but to the PortsAndAdapters layer / infrastrcuture layer. By placing commands and commandHandlers in the webapi project it has to reference the infrastructure project. I Regard Keeping CommandHandlers and Event Handlers clean of infrastructure as an advantage. Robert C Marting calls it the usecase layer which to me indicates a close relationship with the domain or the problem space its trying to be a solution for. Not so much infrastructure.

**Comment by cjjohansen** [comment]
I Still think my argument stands :-)
