### ISSUE TITLE
Update .NET Core getting started docs to VS2019

### ISSUE THREAD

**Issue by BethMassi** [dotnet/docs#16046]
https://docs.microsoft.com/en-us/dotnet/core/get-started - all docs currently say/show Visual Studio 2017. These need to be updated to Visual Studio 2019

List of high-pri articles to be updated:

- [x] https://docs.microsoft.com/en-us/dotnet/core/get-started
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-with-visual-studio (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio (Maira)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/consuming-library-with-visual-studio (Maira)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution (Bill)
- [x] https://docs.microsoft.com/en-us/dotnet/core/tutorials/index
- [x] https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/ (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line (Bill)
- [x] https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nostdlib-compiler-option (Bill)
- [x] https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/install-fsharp (Genevieve)
- [x] https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-visual-studio (Genevieve)
- [x] TOC 

edit by @mairaw: added article list

**Comment by BillWagner** [comment]
Assigned to @mairaw and I for now. We can more to someone else, if appropriate.

**Comment by mairaw** [comment]
Thanks @BethMassi. This has been on my backlog but I didn't have a tracking issue. We also want to make sure it matches the content for the videos /cc @JaySing

**Comment by mairaw** [comment]
I've added a prioritized list above. I've started a release branch for this because a lot of the Core tutorials are intertwined. Other minor updates I'm making directly to master.

Articles I didn't add to the list above:
- Desktop tutorials in the framework folder (/cc @Thraka)
- Architecture guide pages - there are a few e-book articles that still cover VS 2017. @nishanil would have to comment on a plan for those.

**Comment by mairaw** [comment]
@cartermp I've added some F# articles to the list but let me know if you'd prefer a separate issue for those.

**Comment by BethMassi** [comment]
@nishanil let me know what guides need updating and we can get those commissioned via the vendors if necessary.

**Comment by mairaw** [comment]
Adding @gewarren to the effort as well.

**Comment by gewarren** [comment]
@mairaw I think it will work better if you specifically assign topics to each person that's working on this. For instance, I didn't know that you'd already updated the main get-started page, so I was working on that last night. Or should I just pick some and assign them to myself in the list above?

**Comment by BillWagner** [comment]
@gewarren Proposal: We can each add our name to any topic above by editing the issue. If we all do that when we start working, we should be good. 
Thoughts?

**Comment by gewarren** [comment]
> @gewarren Proposal: We can each add our name to any topic above by editing the issue. If we all do that when we start working, we should be good.
> Thoughts?

That works for me.

**Comment by mairaw** [comment]
@BillWagner could you take care of the ones involving a Mac?

**Comment by gewarren** [comment]
I believe my part of this issue is complete - the remaining articles are for Mac, C#, or F#. LMK if I should take any of those.

**Comment by mairaw** [comment]
Could you do the two F# ones as well @gewarren? It seems they would be simple to update.

**Comment by gewarren** [comment]
> Could you do the two F# ones as well @gewarren? It seems they would be simple to update.

Sure.

**Comment by BillWagner** [comment]
If have PRs open for Visual Studio for Mac: #16349 and C# compiler options #16368

**Comment by mairaw** [comment]
I have a samples PR https://github.com/dotnet/samples/pull/1867 and one for consuming open https://github.com/dotnet/docs/pull/16367

Working on the testing one next

**Comment by mairaw** [comment]
We should @gewarren. Last PR is ready for review #16371
