### ISSUE TITLE
Example 3 is wrong

### ISSUE THREAD

**Issue by DarinFlippo** [dotnet/docs#16041]
It claims to generate a default namespace and root tag, but the code produces a root tag with a namespace.  It's a duplicate of Example 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525bf456-96f9-3ec5-baa7-231213dff194
* Version Independent ID: e34d6fbd-8233-edcc-d253-def34d2c324f
* Content: [How to create a document with namespaces (C#) (LINQ to XML)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-create-a-document-with-namespaces-linq-to-xml#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-create-a-document-with-namespaces-linq-to-xml.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-create-a-document-with-namespaces-linq-to-xml.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @DarinFlippo 

I've added it to our backlog, to address when we next update this article.
