### ISSUE TITLE
How long is LowLatency suitable for?

### ISSUE THREAD

**Issue by VikoRifeo** [dotnet/docs#16040]
I assume it's implementation-dependent, but there must be a reliable rule of thumb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcebd46-8a64-9531-f6e1-3a330b61bb0f
* Version Independent ID: 7538a252-8fa8-4615-92df-f1c6d7d6a3e4
* Content: [Latency Modes](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/latency?view=netstandard-2.0#feedback)
* Content Source: [docs/standard/garbage-collection/latency.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/latency.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@Maoni0 Is there a rule of thumb for how long the low latency mode is suitable for?
