### ISSUE TITLE
Link does not open

### ISSUE THREAD

**Issue by programeralex** [dotnet/docs#16042]
Task-Based Asynchronous Pattern link fails to open

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de7019da-9f64-1dbe-0f5a-f3d0d167a693
* Version Independent ID: 65266630-6aab-8647-beeb-1abac1c5d97e
* Content: [Await Operator - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/await-operator#feedback)
* Content Source: [docs/visual-basic/language-reference/operators/await-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/await-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
Found that file using WayBack Machine. It's a word document written by @StephenToub.

[TAP.docx](https://github.com/dotnet/docs/files/3909851/TAP.docx)

@mairaw, Should this be uploaded somewhere and be linked in the article. I'd also like to check if @StephenToub can review the content and check if there is any outdated information because the file is written 7 years ago.

**Comment by stephentoub** [comment]
It's still here:
https://www.microsoft.com/en-us/download/details.aspx?id=19957

What part in particular are you concerned about being outdated?

**Comment by Youssef1313** [comment]
> 
> 
> It's still here:
> https://www.microsoft.com/en-us/download/details.aspx?id=19957
> 
> What part in particular are you concerned about being outdated?

Thanks for the link, I opened a PR with the link you provided.

I didn't mean a specific part, just in general as I noticed this file is old.

**Comment by mairaw** [comment]
@JasonCard I've fixed the Fwlink for en-us to go to the right location but I've noticed that are loc clones for those. Is your team responsible for updating those?
Link ID is 20484.

**Comment by JasonCard** [comment]
@mairaw Thank you for checking. I'll follow up to check if any action is needed for loc.

**Comment by JasonCard** [comment]
@mairaw I found that only English version is available for that download, so no action is needed for loc. You mentioned that previous FWLink (https://go.microsoft.com/fwlink/?LinkId=204847) was cloned for loc, but I actually could not find it anymore in this [Aka Link Management Tool](https://redirectiontool.trafficmanager.net/am/redirection/home?options=host:go.microsoft.com). Can you still find the cloned FWLink?

**Comment by mairaw** [comment]
Yep, still see them
![image](https://user-images.githubusercontent.com/12971179/70175399-7ce6ff00-168b-11ea-96f8-4d8838d70e29.png)

**Comment by JasonCard** [comment]
Thank you for the screenshot. I guess I don't have the permission to see those. Since those cloned FWLinks are no longer needed, I'll request our loc vendor to remove them.
