### ISSUE TITLE
Null conditional operator when accessing non-existent index

### ISSUE THREAD

**Issue by MikeCheel** [dotnet/docs#16047]
There should be a note explaining that accessing a non-existent array member still throws an IndexOutOfRangeException instead of returning null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @MikeCheel 

I've added it to our backlog, to address when we next update this article.  I've also added the "up for grabs" label, for community members who wish to submit a PR for this issue.

**Comment by pkulikov** [comment]
The current doc already contains that information implicitly. It says that `?[]` performs an element access, while the section about element access describes the behavior in the case of non-existent index.

**Comment by BillWagner** [comment]
@pkulikov I agree that the information is there. It could be more visible. It's not urgent, but it's a reasonable request.
