### ISSUE TITLE
'Un-obsolete' XslTransform class

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#16059]
During discussion at the PR dotnet/docs#4529 it was figured out that [XslTransform class](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xsl.xsltransform?view=netframework-4.7.1) is not so obsolete as it seems.

More background: https://github.com/dotnet/corefx/issues/25874

While 'un-obsoleting' this class numerous notes should be removed, for example, in those articles:
https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xslt-transformations
https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xslt-transformations-with-the-xsltransform-class

cc: @mairaw @pjanotti

**Comment by mairaw** [comment]
Transferring this back to dotnet/docs. This is about the notes on the conceptual docs.
