### ISSUE TITLE
Dupe content

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#16062]
@Thraka while reviewing a PR tonight, I realized that the content in this article is duplicated of what we already had in https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows#determine-what-is-installed. We should decide what to do about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2842ce-ee53-ec35-90c6-791a952dfc3b
* Version Independent ID: 79ec96d5-9c2c-1eaa-feb8-40b0afee6a30
* Content: [Check installed .NET Core versions on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions)
* Content Source: [docs/core/install/how-to-detect-installed-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/install/how-to-detect-installed-versions.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hrm.. changing the TOC entry from `Setup` to `Install` kind of excludes including `Uninstall` instructions 😢  I do think that all of these management tasks related to install/uninstall/versioning are fit to be together though. Perhaps we should change the TOC entry title to be more inclusive to these tasks and then include all of the versioning articles? I kind of have a task related to this in 
 #15948 `Review existing articles in repo to see if they can be moved here`

**Comment by gewarren** [comment]
I think it's fine to have uninstall info under an Install node. VS does that: https://docs.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2019
