### ISSUE TITLE
Are static methods allowed in Interfaces nowadays ?

### ISSUE THREAD

**Issue by rubbalbhusri** [dotnet/docs#16061]
I've read in a post at stackflow at the following link:
https://stackoverflow.com/questions/259026/why-doesnt-c-sharp-allow-static-methods-to-implement-an-interface
and also at the following the link:
https://dotnetfiddle.net/Lrzy6y
It's written that in C# version 8.0, static methods are allowed in an interface. Please confirm, is it so? if so, then it needs to be mentioned in this article as well, otherwise, it could be misleading and needs to be updated of the current situation as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97db038-978f-fff3-4e68-110619dc86f2
* Version Independent ID: 3c933595-0ec1-2632-55c9-934af6e72f5d
* Content: [static modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static#feedback)
* Content Source: [docs/csharp/language-reference/keywords/static.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/static.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for pointing this out @rubbalbhusri 

This is related to #12489 It should be fixed as part of that work.

**Comment by rubbalbhusri** [comment]
I've noticed you @BillWagner saying in #12489 that Interfaces are now changing and they'll also include method implementations. Is it True? It'll be great if you can point out all such changes that have come in Interfaces.

**Comment by BillWagner** [comment]
@rubbalbhusri Here are two tutorials that describe the new features in interfaces:

- [version interfaces with default interface members](https://docs.microsoft.com/dotnet/csharp/tutorials/default-interface-methods-versions)
- [create mixin functionality with default interface members](https://docs.microsoft.com/dotnet/csharp/tutorials/mixins-with-default-interface-methods)

I'll be updating the language reference for these features this month.

**Comment by rubbalbhusri** [comment]
My other question to you @BillWagner is: What is the need arisen for interfaces to have static members? and in another post, I saw that now interfaces are also allowed to have private and protected members. Why such changes are brought up? What kind of scenarios are coming where private and protected members will be required? Please share some examples to support the need of static, private and protected in interfaces.

**Comment by BillWagner** [comment]
The best information we have published today is the [feature spec](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods) for default interface members. We're working on updating the other material for this feature.
