### ISSUE TITLE
Will Web Forms ever be supported by .NET Core 3.0+ in VS 2019?

### ISSUE THREAD

**Issue by eshaseth** [dotnet/docs#16069]
I have an enterprise level web app based on Windows  Web Forms and Ajax and it runs on .NET Framework 4.5.1
I need to make it compatible to run on Linux and Windows(cross-platform), hence need to port to .NET Core 3.0.
Do I need to rewrite using Razor Pages(chtml,cs,js) or will Web Forms (aspx, cs and js) ever be supported by .NET Core 3.0? Also what should be used for AJAX in .NET Core 3.0 that will be cross platform compatible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca63e896-e1eb-9714-aeaf-67f56cf582ca
* Version Independent ID: 20fd8665-a5ef-eebe-d01a-9eaf1a60b023
* Content: [Port a Windows Forms app to .NET Core - .NET Core](https://docs.microsoft.com/en-in/dotnet/core/porting/winforms#feedback)
* Content Source: [docs/core/porting/winforms.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/winforms.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello @eshaseth 

Your questions are better suited for the ASP.NET Core teams. I did a little search and found this lengthy discussion <https://github.com/aspnet/AspNetCore/issues/1961>. There doesn't seem to be any plans to port WebForms. Many alternatives and tools to help port are suggested though. Additionally, it's pointed out that you can run it cross-platform in Mono.
