### ISSUE TITLE
Page with title “Compose streams” is missing an example of Stream composition

### ISSUE THREAD

**Issue by binki** [dotnet/docs#16072]
This page states that one can compose `Stream` objects together in a chain/pipeline. However, it does not give a concrete example.

This page does have examples of adapting `Stream`s to `TextReader`s by using `StreamReader` and `BinaryReader`. But no example of wrapping one `Stream` object with another.

In the text, I see:

&gt; Note that FileStreams are buffered by default.

It seems that the author of this page may have been trying to provide the [traditional Java example](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) of `try (BufferedReader br = new BufferedReader(new FileReader(path))) {}` but then, after some research, realized that this example makes no sense in .net because `FileStream` does buffering itself.

Please provide an actual example of `Stream` composition in this article.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/io/composing-streams

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/io/composing-streams.md

### Document Version Independent Id

a65a0e5a-124b-8575-4725-a4c81bc6f8ab

### Article author

@adegeo

### Metadata

* ID: 99c429ef-8912-ee30-d3bb-0a58551c68c7 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 253421](https://dev.azure.com/msft-skilling/Content/_workitems/edit/253421)

**Comment by Thraka** [comment]
I don't think that is true. At least I've never come across this functionality. I think when the author used the word "chain", they were just trying to indicate that you are chaining these objects to end up with a reader/writer:

`MemoryStream > StreamReader` 

I think it's a poor choice of word.

**Comment by binki** [comment]
@Thraka Yeah, that is exactly the example the article is missing—an example of wrapping multiple streams to perform transformations or add features (e.g., buffering (though it doesn’t make logical sense to add buffering to a `MemoryStream`)). That is an example of `Stream` composition. It even looks a lot like mathematical function composition. E.g., `using (var stream = new SomeCustomWrappingStream(new FileStream())) {}`.

**Comment by Thraka** [comment]
Ok. i'll add this to our backlog. If you would like to work on contributing an example, please feel free to do so. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub. Source code for the article is located in the [samples repo for csharp](https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_CLR_System/system.IO.StreamReader/CS/) and in the [samples repo for vb](https://github.com/dotnet/samples/tree/master/snippets/visualbasic/VS_Snippets_CLR_System/system.IO.StreamReader/VB/).

**Comment by binki** [comment]
@dotnet/docs @BillWagner @akoeplinger the article still is missing a concrete example of composing streams. So this issue is not resolved.

**Comment by adegeo** [comment]
- Converted the issue metadata to the new style
- Put this up in the next sprint
