### ISSUE TITLE
GC config knobs - two suggestions

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#16075]
Regarding https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector:

Feedback 1: I recommend adding an example of the config at the bottom, e.g. web.config, runtimeconfig.json (e.g. to answer "where in the JSON/.config does this go?")

Feedback 2: In the hex examples like "1D4C0", IMO "0x1D4C0" is a better/clearer recommendation

See https://twitter.com/Nick_Craver/status/1201686635043266561.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e544aba5-cfe6-1790-023e-bec738182ea8
* Version Independent ID: 8392a21a-8404-d352-ffb1-d6373bbbdd1b
* Content: [Garbage collector config settings](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector)
* Content Source: [docs/core/run-time-config/garbage-collector.md](https://github.com/dotnet/docs/blob/master/docs/core/run-time-config/garbage-collector.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Rick-Anderson** [comment]
@gewarren  don't you want to create an integrated issue so this is visible from the doc page?

Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
Normally you can convert an issue to integrated by opening an open or closed issue and copying the metadata. This page doesn't have any issues to copy.

**Comment by gewarren** [comment]
> @gewarren don't you want to create an integrated issue so this is visible from the doc page?

Good idea - I'll try and remember that next time!

**Comment by mairaw** [comment]
I've edited your issue to add that @gewarren.

**Comment by gewarren** [comment]
Thanks Maira!
