### ISSUE TITLE
Why static classes cannot implement interfaces?

### ISSUE THREAD

**Issue by rubbalbhusri** [dotnet/docs#16070]
It's written here in this article that static classes are not allowed to implement interfaces, however, it's not explained why it's made so? Can you @BillWagner elaborate more on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97db038-978f-fff3-4e68-110619dc86f2
* Version Independent ID: 3c933595-0ec1-2632-55c9-934af6e72f5d
* Content: [static modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static)
* Content Source: [docs/csharp/language-reference/keywords/static.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/static.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Rick-Anderson** [comment]
There's good answers to this question on SO that wouldn't fit into the doc.
