### ISSUE TITLE
System.Net.Http.UseSocketsHttpHandler setting not available for .NET 5

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#16088]
Update https://docs.microsoft.com/en-us/dotnet/core/run-time-config/networking to note that the `System.Net.Http.UseSocketsHttpHandler` setting is removed for .NET 5.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler also needs to be updated to be clear that internally it uses SocketsHttpHandler.

Devs reading the docs as they are today might spend time replacing HttpClientHandler with SocketsHttpHandler unnecessarily.
