### ISSUE TITLE
Link to CLR Profiler broken

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#16084]
In the **TraverseHeap** documentation, the link to the CLR Profiler (https://go.microsoft.com/fwlink/?LinkID=67325) is broken.

I found this (https://www.microsoft.com/en-us/download/details.aspx?id=16273), but I don't know if it's the latest one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e01c075-7a07-5850-d462-706675b545f1
* Version Independent ID: 0dd6c661-01a1-592c-ea53-8427412ff8d0
* Content: [SOS.dll (SOS Debugging Extension)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension?redirectedfrom=MSDN&source=docs#feedback)
* Content Source: [docs/framework/tools/sos-dll-sos-debugging-extension.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sos-dll-sos-debugging-extension.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @paulomorgado.

@vivmishra @terrajobst @tommcdon who could help me find out where is the latest version of CLR Profiler? 
In addition to the one that Paulo linked to in the downloads site, there seems to be this one:
https://github.com/microsoftarchive/clrprofiler/releases

**Comment by tommcdon** [comment]
Adding @brianrob and @PeterSolMS who might have know where the latest version of CLR Profiler is now.

**Comment by paulomorgado** [comment]
It has been now more than 1 year since this issue was open.

https://www.microsoft.com/en-us/download/details.aspx?id=16273 is now 404!
