### ISSUE TITLE
download slow

### ISSUE THREAD

**Issue by PicaPicaLX** [dotnet/docs#16090]
download so slow!
ip:202.201.9.67
Ubuntu server 18.04.3 LTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
@leecow @richlander not sure if there's anything that can be investigated here re. download speed? If you're still experiencing issues, I'd recommend you open an issue at https://github.com/dotnet/core/issues.

I'm closing this issue because it's not related to the content.

**Comment by shaojun** [comment]
could you provide a manual installation instruction for those expericing slow issue.
