### ISSUE TITLE
Are 3.1 requirements the same as 3.0?

### ISSUE THREAD

**Issue by PhilipHassialis** [dotnet/docs#16099]
If not can you at least update the page with a ".Net Core 3.0/3.1" title on the tab?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [.NET Core SDK and runtime dependencies - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?pivots=os-linux&tabs=netcore30)
* Content Source: [docs/core/install/dependencies.md](https://github.com/dotnet/docs/blob/master/docs/core/install/dependencies.md)
* Product: **dotnet-core**
* GitHub Login: @leecow
* Microsoft Alias: **leecow**

**Comment by leecow** [comment]
@Thraka

**Comment by Thraka** [comment]
This was fixed in #16112 and should be published some time tonight or tomorrow.
