### ISSUE TITLE
Arithmetic simplification example is confusing

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/docs#16102]
The Arithmetic simplification example is confusing and doesn't seem to be a complete example.

Can the example be clarified any further?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3f3f52-86a5-4cc9-ab1f-874cad72b821
* Version Independent ID: f69dc2c8-79bc-300c-5804-e1f7aa5c8352
* Content: [Pattern matching - C# 7.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/pattern-matching#feedback)
* Content Source: [proposals/csharp-7.0/pattern-matching.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I also find it confusing. Thank you for bringing this to our attention.
