### ISSUE TITLE
in AppWithPlugin,how to load aseembly with a config file

### ISSUE THREAD

**Issue by hey-hoho** [dotnet/docs#16106]
As this title says,
I want to load aseembly with a config file,such as .config or .json.how can I do it?
By the way, how can I get config options If it can be achieved

Thanks.

**Comment by mairaw** [comment]
Thanks @hey-hoho for your feedback.

@vitek-karas can you help with these questions about the AppWithPlugin sample?

**Comment by vitek-karas** [comment]
@hey-hoho I'm not really sure what is the ask here.

* You can read any JSON file using for example classes in the System.Text.Json namespace: https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=netcore-3.0
* If you want to work with the `.deps.json` for the plugin, you can use the `Microsoft.Extensions.DependencyModel` NuGet package which provides APIs to read it and to a certain degree process it.

What would help is to know what kind of config you're looking for...

**Comment by hey-hoho** [comment]
@vitek-karas Glad to receive your reply.
For example,I have a library Test.dll which depend on it's appsettings.json. Now I use AssemblyLoadContext and AssemblyDependencyResolver to load this library,I want to get config option like Configuration["XX"] rather than parse json file by myself.
In .NetFramework AppDomain,we can create AppDomainSetup instance,then appoint a confg file by  ConfigurationFile property,use System.Configuration.ConfigurationManager.AppSettings["xx"] to get option.
Can something like this be realized?
Thanks for your answer.

**Comment by vitek-karas** [comment]
As far as I know this is currently not possible with the statics based configuration APIs. Maybe @maryamariyan or @safern would know more.
