### ISSUE TITLE
Language of sample/snippet included in path redundantly

### ISSUE THREAD

**Issue by jpierson** [dotnet/docs#16105]
**Issue description**

In many places such as in the example below, the implementation language of a snippet or sample is redundantly stated in more than one segment of the directory path.
Example specifying both **csharp** and **CS** in the path:

snippets/**csharp**/VS_Snippets_CLR_Classic/classic Console Example/**CS**/source.cs

The problem with this way of organizing the source files is that it makes it difficult to compare and manage alternate language examples of similar source. For example if one were to look to see if there are VB and F# counterparts for a C# example one cannot simply look under `snippets/VS_Snippets_CLR_Classic/classic Console Example/VB` or `snippets/VS_Snippets_CLR_Classic/classic Console Example/FS` accordingly. Likewise it is more difficult to create a duplicate directory structure for each language and then maintain it consistently after it is created.

### Proposed Solution

My proposal would be to remove the high level language specific directories for such API doc samples such as the `csharp`, `fsharp`, and `visualbasic` and use those only for documentation about language unique features when necessary. By having the language specific folder only included the leaf most section for these examples it more inherent and consequently naturally enforced consistency between language implementations. Using the proposed method of organization should also allow newer contributors like myself to more efficiently contribute to fill gaps in missing documentation.

**Comment by mairaw** [comment]
Thanks for your feedback @jpierson. This weird structure was introduced by migrating the samples from MSDN to docs.microsoft.com. But I agree that it makes hard to find the equivalent samples.

Tagging @Thraka and @BillWagner to this issue since they're looking into our CI in the samples repo.

The reason why we split them that way is because we thought that setting up the CI per language would be easier at the time.

**Comment by Thraka** [comment]
@jpierson We're aware of how annoying this... 😁 we're working on redesigning this samples structure and projects over the coming months.

**Comment by jpierson** [comment]
@Thraka, thanks for your response. Please be aware that I'm currently working on helping to fill some gaps with missing F# samples. It would be great to get a little heads up before any restructuring begins so I can wrap up my merge request with my progress so far in the case that I'm incomplete.

Please see:
* https://github.com/dotnet/samples/pull/1809
* dotnet/dotnet-api-docs/issues/3571

**Comment by jpierson** [comment]
I've gone ahead with requesting review for the first round of additional F# samples in https://github.com/dotnet/samples/pull/1809. I'll try to keep the set of samples granular to the particular documentation page that I'm covering per merge request to avoid a long lived branch.

**Comment by jpierson** [comment]
This looks like a related discussion in this past merge request.
https://github.com/dotnet/samples/pull/1418

**Comment by jpierson** [comment]
@Thraka, is there any issue or PR that I could follow regarding the restructuring plans you mentioned above or are these discussion outside of GitHub as of now?

**Comment by Thraka** [comment]
This one is probably good. We had a meeting about this around the holidays.

**Comment by tdykstra** [comment]
The plan for structuring snippet files is published in the contributor guide, added by https://github.com/MicrosoftDocs/Contribute/pull/394-- see https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute

**Comment by Thraka** [comment]
We could probably close this issue now since we have a plan in place.
