### ISSUE TITLE
.NET Core 3.1?

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/docs#16100]
There are no instructions for installing .NET Core 3.1. Also doing `apt search dotnet-sdk` does not show any 3.1 package as being available to install:

```
root@Rehans-wks:/mnt/c/Users/rehan# apt search dotnet-sdk
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1/bionic 2.1.802-1 amd64
  Microsoft .NET Core SDK 2.1.802

dotnet-sdk-2.1.105/bionic 2.1.105-1 amd64
  Microsoft .NET Core SDK - 2.1.105

dotnet-sdk-2.1.200/bionic 2.1.200-1 amd64
  Microsoft .NET Core SDK - 2.1.200

dotnet-sdk-2.1.201/bionic 2.1.201-1 amd64
  Microsoft .NET Core SDK - 2.1.201

dotnet-sdk-2.1.202/bionic 2.1.202-1 amd64
  Microsoft .NET Core SDK - 2.1.202

dotnet-sdk-2.1.300-preview2-008533/bionic 2.1.300-preview2-008533-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.300-rc1-008673/bionic 2.1.300-rc1-008673-1 amd64
  Microsoft .NET Core SDK 2.1.300 - rc1

dotnet-sdk-2.2/bionic 2.2.402-1 amd64
  Microsoft .NET Core SDK 2.2.402

dotnet-sdk-3.0/bionic 3.0.101-1 amd64
  Microsoft .NET Core SDK 3.0.101
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1804#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
These updates are incoming and I'm tracking issue #16091. I just tested with

```bash
sudo apt update
apt search dotnet-sdk
```

And I see the 3.1 release is now available

```bash
$ apt search dotnet-sdk
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1/bionic 2.1.802-1 amd64
  Microsoft .NET Core SDK 2.1.802

dotnet-sdk-2.1.105/bionic 2.1.105-1 amd64
  Microsoft .NET Core SDK - 2.1.105

dotnet-sdk-2.1.200/bionic 2.1.200-1 amd64
  Microsoft .NET Core SDK - 2.1.200

dotnet-sdk-2.1.201/bionic 2.1.201-1 amd64
  Microsoft .NET Core SDK - 2.1.201

dotnet-sdk-2.1.202/bionic 2.1.202-1 amd64
  Microsoft .NET Core SDK - 2.1.202

dotnet-sdk-2.1.300-preview2-008533/bionic 2.1.300-preview2-008533-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.300-rc1-008673/bionic 2.1.300-rc1-008673-1 amd64
  Microsoft .NET Core SDK 2.1.300 - rc1

dotnet-sdk-2.2/bionic 2.2.402-1 amd64
  Microsoft .NET Core SDK 2.2.402

dotnet-sdk-3.0/bionic 3.0.101-1 amd64 [upgradable from: 3.0.100-1]
  Microsoft .NET Core SDK 3.0.100

dotnet-sdk-3.1/bionic 3.1.100-1 amd64
  Microsoft .NET Core SDK 3.1.100
```

**Comment by utsabshrestha** [comment]
**The trick is to first let the package manager know that it should include packages from ‘packages.microsoft.com’:**

_wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb_
_sudo dpkg -i packages-microsoft-prod.deb_
_sudo apt-get update_
_apt search dotnet-sdk_

reference [from](https://bartwullems.blogspot.com/2019/12/install-net-core-31-sdk-on-ubuntu-1804.html)
