### ISSUE TITLE
IsInitiating initiates a session if supported

### ISSUE THREAD

**Issue by rolfik** [dotnet/docs#16125]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42e6851-980f-68d9-2651-81276d3fb9bd
* Version Independent ID: 1b6160a8-af8e-b5e1-36d4-725db3ffa55d
* Content: [WCF endpoints and gRPC methods - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/wcf-endpoints-grpc-methods#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/wcf-endpoints-grpc-methods.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/wcf-endpoints-grpc-methods.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by shirhatti** [comment]
@rolfik What's the question here? I see that your issue description is empty

**Comment by rolfik** [comment]
No question.
That is my interpretation of IsInitiating instead of the one in the article:

> The IsInitiating property lets you indicate that a method within a ServiceContract can't be the first method called as part of a session
