### ISSUE TITLE
Add note about trailing second fraction zeros being omitted when writing DateTime[Offset]s in System.Text.Json

### ISSUE THREAD

**Issue by layomia** [dotnet/docs#16128]
**Issue description**

The section about how the serializer and writer produce these types doesn't provide this information: https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-formatting.

This [test data set](https://github.com/dotnet/runtime/blob/7ea817f30755079e44616b60bc09f0bb6857d6cd/src/libraries/System.Text.Json/tests/JsonDateTimeTestData.cs#L234-L250) shows how the omission is done.

**Comment by ahsonkhan** [comment]
I am assigning this to you @layomia since you wrote the doc. If you think this would be good for someone in the community to fix up, please mark is as up for grabs.
