### ISSUE TITLE
Wrong Information for Visual Studio for Mac Community 2017 

### ISSUE THREAD

**Issue by Garry-Anderson** [dotnet/docs#16135]
I would like to set a Command Prompt in the Tools menu to run Terminal.app in Mac.  The above instructions do not work because the Add Custom Tool procedure does not recognize *.app programs as valid entries for browsing those apps as commands.  What can be done to fix this impasse?  Since VS2017 is provided for both Win and Mac platforms, why does the Mac version not recognize *.app programs as commands?  Any insight would be much appreciated.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs#feedback)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Visual Studio for Mac is a separate product from Visual Studio for Windows. Meaning, they don't share the same code and user experience. I would ask your question on the Visual Studio for Mac support area: https://visualstudio.microsoft.com/vs/support/mac/#talktous

Sorry I couldn't help further.
