### ISSUE TITLE
I can't find dotnet-runtime-3.1

### ISSUE THREAD

**Issue by moulo1982** [dotnet/docs#16137]
moulo@linux-4eso:~&gt; sudo zypper search dotnet
Loading repository data...
Reading installed packages...

S | Name                      | Summary                                                    | Type   
--+---------------------------+------------------------------------------------------------+--------
  | dotnet-apphost-pack-3.0   | Microsoft.NETCore.App.Host 3.0.1                           | package
  | dotnet-apphost-pack-3.1   | Microsoft.NETCore.App.Host 3.1.0                           | package
  | dotnet-host               | Microsoft .NET Core Host - 3.1.0 Preview 3                 | package
  | dotnet-hostfxr-2.1        | Microsoft .NET Core Host FX Resolver - 2.1.14 2.1.14       | package
  | dotnet-hostfxr-2.2        | Microsoft .NET Core Host FX Resolver - 2.2.8 2.2.8         | package
  | dotnet-hostfxr-3.0        | Microsoft .NET Core Host FX Resolver - 3.0.1 3.0.1         | package
  | dotnet-runtime-2.1        | Microsoft .NET Core Runtime - 2.1.14 Microsoft.NETCore.App | package
  | dotnet-runtime-2.2        | Microsoft .NET Core Runtime - 2.2.8 Microsoft.NETCore.App  | package
  | dotnet-runtime-3.0        | Microsoft .NET Core Runtime - 3.0.1 Microsoft.NETCore.App  | package
  | dotnet-runtime-deps-2.1   | dotnet-runtime-deps-2.1 2.1.14                             | package
  | dotnet-runtime-deps-2.2   | dotnet-runtime-deps-2.2 2.2.8                              | package
  | dotnet-runtime-deps-3.0   | dotnet-runtime-deps-3.0 3.0.1                              | package
  | dotnet-runtime-deps-3.1   | dotnet-runtime-deps-3.1 3.1.0                              | package
  | dotnet-sdk-2.1            | Microsoft .NET Core SDK 2.1.802 2.1.802                    | package
  | dotnet-sdk-2.2            | Microsoft .NET Core SDK 2.2.402 2.2.402                    | package
  | dotnet-sdk-3.0            | Microsoft .NET Core SDK 3.0.101 3.0.101                    | package
  | dotnet-targeting-pack-3.0 | Microsoft.NETCore.App.Ref 3.0.1                            | package
  | ghc-dotnet-timespan       | .NET TimeSpan                                              | package
  | ghc-dotnet-timespan-devel | Haskell dotnet-timespan library development files          | package
moulo@linux-4eso:~&gt; sudo zypper install dotnet-runtime-deps-3.1

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Install .NET Core on openSUSE 15 - package manager - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-package-manager-opensuse15#feedback)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
@leecow @richlander is there a better repo for this feedback? Customer is reporting that they cannot find the

**Comment by leecow** [comment]
I'm tracking this at https://github.com/dotnet/core/issues/3960. The Linux repo owners are aware and I have to have this one ironed out this morning.

**Comment by mairaw** [comment]
Thanks @leecow. Closing this one then.
