### ISSUE TITLE
ggg

### ISSUE THREAD

**Issue by buocnhay** [dotnet/docs#16136]
rff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Not a valid feedback. Closing.
