### ISSUE TITLE
Linux ARM package installer support

### ISSUE THREAD

**Issue by fmcgarry** [dotnet/docs#16144]
Are there any plans on supporting Linux ARM64 .NET Core installs through a package manager?

I'm running .NET Core on a Debian 9 ARM64 system and it would be nice to be able to install/update it through the package manager instead of having to do manual installs every time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4fb70e-8d93-5890-a259-06ae5f37c994
* Version Independent ID: 8846709d-4f43-30f8-3b09-b61dee716b90
* Content: [Install .NET Core on Debian 9 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian9#feedback)
* Content Source: [docs/core/install/linux-package-manager-debian9.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-debian9.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
@leecow can you help with this question about Linux ARM package installer support?

**Comment by leecow** [comment]
@fmcgarry - producing installers for ARM64 is definitely on our list. Can't commit to when but we're in planning exercises for 5.0 now so we'll see if it will fit. 

/cc @dleeapho

**Comment by mairaw** [comment]
Is there a better repo I should transfer this issue to @leecow?

**Comment by Thraka** [comment]
Probably dotnet/core as other issues related to the linux installers are there.

**Comment by dleeapho** [comment]
Issue moved to [dotnet/core #3996](https://github.com/dotnet/core/issues/3996) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mairaw** [comment]
I'm closing this one then. We can also use the GitHub Transfer issue button to move issues across the dotnet org.
