### ISSUE TITLE
Documenation for DateTimeFormatInfo.ShortestDayNames needs to specify starting day

### ISSUE THREAD

**Issue by benstevens48** [dotnet/docs#16145]
**Issue description**
The docs do not say what day comes first in the list returned by `DateTimeFormatInfo.ShortestDayNames`. As far as I can tell it is Sunday for all cultures, but I'm not sure. Please could you clarify and update the docs.

**Target framework**
- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

**Comment by mairaw** [comment]
Thank you for your feedback @benstevens48. This has been fixed and the change will go live later today.

**Comment by benstevens48** [comment]
Hi @mairaw , thanks for the fix. Actually, I was looking at the DayNames property as well, and that says it can depend on the value of the Calendar property - so maybe ShortestDayNames does too? Although I haven't been able to fins a case where the first day isn't Sunday.

**Comment by mairaw** [comment]
Good question.

**Comment by mairaw** [comment]
Good question @benstevens48. @tarekgh can you comment on this and on the fix I made for #3645?

**Comment by tarekgh** [comment]
We always fill the day names array starting of Sunday regardless of the calendar. 

https://source.dot.net/#System.Private.CoreLib/CalendarData.Windows.cs,66

**Comment by benstevens48** [comment]
Thanks - in that case maybe also update the docs for DayNames and AbbreviatedDayNames to say this. I guess technically the names of the days could depend on the calendar, which is why the docs for these say they might depend on the calendar. But it would certainly be useful to know that Sunday is always the first entry.

**Comment by tarekgh** [comment]
I have created the issue https://github.com/dotnet/docs/issues/16558

**Comment by mairaw** [comment]
Additional fixes are being tracked at https://github.com/dotnet/dotnet-api-docs/issues/3737.
