### ISSUE TITLE
Mutable function let bindings

### ISSUE THREAD

**Issue by brikken** [dotnet/docs#16159]
The syntax box suggests that function let bindings do not support `mutable`, which they in fact do.

```F#
type Test() =
  let mutable func = (+)
  member _.SetFunc(f) = func <- f
  member _.RunFunc(a,b) = func a b

let test = Test()
test.RunFunc(1,2) // 3
test.SetFunc((-)) // ()
test.RunFunc(1,2) // -1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 063de43a-67f5-346b-b2d2-860971b1303f
* Version Independent ID: 0ef81b90-874c-ad3d-da97-90650596e064
* Content: [let Bindings in Classes - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/let-bindings-in-classes)
* Content Source: [docs/fsharp/language-reference/members/let-bindings-in-classes.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/let-bindings-in-classes.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
The syntax block is actually correct, since you can't have mutable `let` bindings that are recursive. But the comments above them are wrong, since these are not "fields" are C# developers would be familiar with. So I've corrected the comments.

**Comment by cartermp** [comment]
This is resolved in the linked commit, sadly github didn't close this out
