### ISSUE TITLE
How can i print out all the  'Balance' in the transaction log??? 

### ISSUE THREAD

**Issue by ngocsang69** [dotnet/docs#16152]
[Enter feedback here]
We know the balance is changed after each transaction, so is there someway to retrieve it and add it into Transaction class as a property? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion for an enhancement to this tutorial @ngocsang69 

I've added this to our backlog to address when we next update this article. I've also added the "up-for-grabs" label in case community members want to address this issue.

**Comment by Youssef1313** [comment]
@BillWagner, this can be closed now as it's fixed in dotnet/samples#1843.

**Comment by DavidACraig75** [comment]
Is there a way to change the stringbuilder to add colour to the lines? i wanted to have anything with item.amount < 0 to have a Console.BackgroundColor = ConsoleColor.Red;

**Comment by BillWagner** [comment]
@DavidACraig75 That's a nice suggestion.

The `StringBuilder` class won't fix it. However, you could add other code using the `Console.BackgroundColor` property you mention to set and reset the color before writing the message. Those properties aren't platform independent, so we don't cover them in these introductory tutorials.

**Comment by BillWagner** [comment]
Closing per earlier comment. This was fixed in dotnet/samples#1843
