### ISSUE TITLE
Difficult to follow. No clear sequence of steps.

### ISSUE THREAD

**Issue by rightwayit** [dotnet/docs#16162]
Pretty poor for Microsoft. Dives in at the low level, yet fails to give us a clear sequence of steps that will get this thing up and running. I've been more than an hour trying to find out what this project is supposed to be called, because you don't mention it, and I can't find it in the samples. Very, very poor. Come on, Microsoft. Buck up!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @rightwayit 

We'll address this when we next update this article.

**Comment by zdrakec** [comment]
Wait, what? I thought this was, in contrast, remarkably easy to follow, and clear in its explanations. Had no trouble whatsoever getting it going...

**Comment by rightwayit** [comment]
More context, please. I criticise a lot of things, so you might have to refresh my memory on this one. At any rate, if I found it difficult to follow as a developer of some 35 years that learned and taught Python intermediate in 5 weeks, then other folks are going to find it that way too, so please try and humble up and let's get to the bottom of this, eh? I am on your side.


Best regards,


Graham

Graham Bennett (RightWay IT Limited) 07502 545702


[1510153075288_the-open-group-certified-togaf-9-certified.png]

________________________________

**Comment by zdrakec** [comment]
Ai I did not mean to be "un-humble" - I just kept thinking, as I worked through it, that for once the example was not only straightforward, but actually worked. I apologize for the tone, I see your point.

**Comment by rightwayit** [comment]
Well I'm not infallible, either, and I might have been a bit unkind. Did you or someone you know write this? If so, I'd be happy to explain the difficulty I had if I have a link to the page again.


Best regards,


Graham

Graham Bennett (RightWay IT Limited) 07502 545702


[1510153075288_the-open-group-certified-togaf-9-certified.png]

________________________________

**Comment by rightwayit** [comment]
Just for starters, it's entirely possible that you knew something I didn't, or got lucky with the things you tried. If so, then fair play to you. Your view is every bit as valid as mine. Probaby more so 🙂


Best regards,


Graham

Graham Bennett (RightWay IT Limited) 07502 545702


[1510153075288_the-open-group-certified-togaf-9-certified.png]

________________________________
