### ISSUE TITLE
Missing info that dotnet may use a different bitness

### ISSUE THREAD

**Issue by Symbai** [dotnet/docs#16165]
**Issue description**
About https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet it should be stated that using `dotnet` may runs a differently bitness and 32bit version of dotnet may not list up all runtimes using `dotnet --list-runtimes` 

It should also be documented which bitness is supposed to execute running `dotnet` command (i.e. last installed .NET runtime bitness OR preferring lower bitness OR preferring system bitness).

I'm not sure if this has other conflicts using other command line arguments.

See https://github.com/dotnet/runtime/issues/665 for more details.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core X.x
- [ ] .NET Framework
- [ ] .NET Standard

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @Symbai. @KathleenDollard @dsplaisted is this behavior expected? There would be a few places where we talk about this command where we'd have to mention this.

**Comment by dsplaisted** [comment]
It's true that the x86 and x64 versions of `dotnet` don't mix well.  Whichever one is on your path (which can depend on installation order) will be the one that is resolved from the command line, and it won't list SDKs or runtimes from the other bitness.

Generally I would recommend sticking to x64 if your machine supports that, if possible.

We should improve how the product works here, and in the meantime it would be good to have documentation on the current issues.
