### ISSUE TITLE
Failed the `dotnet pack` command in turorial.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#16178]
@hskwakr commented on [Sat Dec 07 2019](https://github.com/dotnet/docs.ja-jp/issues/937)

[フィードバックをこちらに入力してください]

## Introduction  

Please let me know if this contents is not an appropriate issue.  

Please let me know if there is any missing information in this message.
Also, please let me know if you have any helpful information on this issue.

## Issue  

I tried to this tutorial:  
https://docs.microsoft.com/ja-jp/dotnet/core/tutorials/cli-templates-create-template-pack

And I failed the `dotnet pack` command:  

```powershell
PS C:\...\working\templates> dotnet pack  
.NET Core 向け Microsoft (R) Build Engine バージョン 16.4.0+e901037fe  
Copyright (C) Microsoft Corporation.All rights reserved.  

C:\...\working\templates\templatepack.csproj : error NU1100: '.NETStandard,Version=v2.0' に対する 'NETStandard.Library (>= 2.0.3)' を解決できません 。  
C:\...\working\templates\templatepack.csproj の復元が 163.08 ms で失敗しました。  
```

I learned that `.NET Core 3.1` can use `.NET Standard 2.1`.  
https://docs.microsoft.com/ja-jp/dotnet/standard/net-standard#net-implementation-support

So I changed `netstandard2.0` to ` netstandard2.1` in `templatepack.csproj`.  
And I failed the `dotnet pack` command:  

```powershell
PS C:\...\working\templates> dotnet pack  
.NET Core 向け Microsoft (R) Build Engine バージョン 16.4.0+e901037fe  
Copyright (C) Microsoft Corporation.All rights reserved.  

C:\...\working\templates\templatepack.csproj の復元が 47.55 ms で完了しました。  
templatepack -> C:\...\working\templates\bin\Debug\netstandard2.1\templatepack.dll  
C:\Program Files\dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5017: 依存関係とコンテンツのないパッケージは作成できません。 [C:\...\working\templates\templatepack.csproj]  
```

## MEMO

I pushed my code to github:  
https://github.com/hskwakr/dotnetTutorials  

My development environment is this:  

```
Visual Studio (VSCode)  
Version: 1.40.2 (user setup)  
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520  
Date: 2019-11-25T14:54:45.096Z  
Electron: 6.1.5  
Chrome: 76.0.3809.146  
Node.js: 12.4.0  
V8: 7.6.303.31-electron.0  
OS: Windows_NT x64 10.0.18362  
```

```
dotnet --info  
.NET Core SDK (global.json を反映):  
Version:   3.1.100  
Commit:    cd82f021f4  
ランタイム環境:  
OS Name:     Windows  
OS Version:  10.0.18362  
OS Platform: Windows  
RID:         win10-x64  
Base Path:   C:\Program Files\dotnet\sdk\3.1.100\  
```

Thank you for reading.
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 64d0e779-2a93-d2b8-3fb0-8c88812a4fc7
* Version Independent ID: 2e4ef5da-1b4b-a1d7-7ec8-6169360bf315
* Content: [dotnet new 用のテンプレート パックを作成する - .NET Core](https://docs.microsoft.com/ja-jp/dotnet/core/tutorials/cli-templates-create-template-pack#feedback)
* Content Source: [docs/core/tutorials/cli-templates-create-template-pack.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/core/tutorials/cli-templates-create-template-pack.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

---

@srvbpigh commented on [Sat Dec 07 2019](https://github.com/dotnet/docs.ja-jp/issues/937#issuecomment-562846105)

Hello, @hskwakr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
@hskwakr Hello. Thank you for putting your project on GitHub! That makes it very easy to help. You created the template pack project in the _working\templates\\_ folder. This project should be created in the _working\\_ folder.

```
└─working
  │   Program.cs
  │   templatepack.csproj
  │
  └───templates
      ├───consoleasync
      │   │   consoleasync.csproj
      │   │   Program.cs
      │   │
      │   └───.template.config
      │           template.json
      └───extensions
          │   CommonExtensions.cs
          │
          └───.tmplate.config
                  template.json
```

Also, I noticed the _extensions\\.tmplate.config\\_ folder is named wrong. It should be _.t`e`mplate.config\\_

I will modify the tutorial slightly to make this clearer.

**Comment by hskwakr** [comment]
I completed tutorials with your support.
Thank you for everything.
