### ISSUE TITLE
No info how to create and use custom options

### ISSUE THREAD

**Issue by bugproof** [dotnet/docs#16172]
I would like to pass some custom options in `dotnet new` and use it in my template.

There's should be some example of how to do it and how to add it to template.json (with link to https://github.com/dotnet/templating/wiki/Reference-for-template.json#symbols-introduction)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097102bb-f6d9-c469-5556-ae1f16fdc4fe
* Version Independent ID: 77b25381-6e0f-949f-5f96-b83e9b61e9fc
* Content: [Create a project template for dotnet new - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template#feedback)
* Content Source: [docs/core/tutorials/cli-templates-create-project-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-project-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Great feedback!
