### ISSUE TITLE
What's "a compatible array type"?

### ISSUE THREAD

**Issue by mrmowji** [dotnet/docs#16176]
I think that'd be good if there's some explanation somewhere in C# docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @mrmowji 

Updating the tour of C# section is on our list of upcoming tasks. We'll address this as part of that work.

**Comment by ericlippert** [comment]
@mrmowji: To answer your question: C# allows unsafe array covariance in some cases. For example, a string[] reference may be stored in a variable of type object[] even though writing a non-string via the variable would crash.  Also, the CLR allows references to int[] to be stored in a variable of type uint[], and similarly for other integral types.
