### ISSUE TITLE
Using example is a bad representative

### ISSUE THREAD

**Issue by jeme** [dotnet/docs#16170]
While i understand the point of the using declaration, I think the example is awful.

I mentally and immediately just transformed it to the code below:
Which I would also say is more in line with the actual code of the "new" code.

And, in this case, is it really all that useful?...
----
    // We must declare the variable outside of the using block
    // so that it is in scope to be returned.
    using (var file = new System.IO.StreamWriter("WriteLines2.txt"))
    {
        int skippedLines = 0;
        foreach (string line in lines)
        {
            if (!line.Contains("Second"))
            {
                file.WriteLine(line);
            }
            else
            {
                skippedLines++;
            }
        }
        return skippedLines;
    } // file is disposed here
----

IMO not really, that being said, the "having to declare the variable outside the using" has hit me from time to time and annoyed me, so I can surely see the benefit. (I have not fully made up my mind on how "Clear" it makes to code to me though, readability)...

But there must be better examples that this to show of the usefulness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding your feedback @jeme 

This article gives a quick overview of the syntax of new features. As we update other tutorials you'll see more samples that show this feature in more real-world scenarios.

What we've found by examining C# projects is that the majority of using declarations are closed at the end of a scope (either a loop, an if block, or a method). In those cases, the new syntax is more concise for the most common cases.

I'll close this as answered.

**Comment by jeme** [comment]
I would have thought it was also suppose to "sell" the ideas, so I had hoped to see a better example in this case instead of something that seems completely pointless.

But that is ofc. your call to make, I have voiced my opinion on the matter, which was what was important for me to do.

**Comment by rneal4** [comment]
I agree with @Jeme. This doesn't really "sell" using the new syntax, unless there are other benefits. I honestly think this is almost worse as it means developers who declare multiple usings in a single scope with this syntax will have the life time of those resources far extended pass their actual use since they will not get disposed until they are no longer in scope.
