### ISSUE TITLE
Some examples would be nice

### ISSUE THREAD

**Issue by SuperNova911** [dotnet/docs#16174]
Like other LINQ articles, It would be nice to have some code examples
Can I make some code contribution for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da65be87-16ea-ebcb-e098-6dbf3579152f
* Version Independent ID: 045d5185-5b9c-effc-c542-75192e320d29
* Content: [Quantifier Operations (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/quantifier-operations.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/quantifier-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great idea @SuperNova911 !

I've added this to our backlog, and added the up-for-grabs label to this issue.  If you'd like to add the samples, I'll assign this issue to you.

**Comment by SuperNova911** [comment]
Thanks for comment @BillWagner 

I'd like to add some sample for this, please assign to me XD
