### ISSUE TITLE
Image labels

### ISSUE THREAD

**Issue by y2k4life** [dotnet/docs#16179]
Image labels don't show when using Dark or High Contrast theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8adaedc-37da-e381-a87e-6649bc6cb3c8
* Version Independent ID: 779340cf-274b-5af9-54f0-b9b90c54f143
* Content: [Tutorial: Automated visual inspection using transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning?wt.mc_id=docsexp6_personal-blog-marouill#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification-api-transfer-learning.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification-api-transfer-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by Youssef1313** [comment]
It seems that this problem is due to the background being transparent. Maybe converting these images from png to jpg do the trick.

**Comment by natke** [comment]
Hi @Youssef1313, I checked and I can see the images in dark mode and high contrast mode. Which O/S and browser are you using?

**Comment by Youssef1313** [comment]
![Screenshot_2019-12-12-05-02-06-046_com android chrome](https://user-images.githubusercontent.com/31348972/70679055-b2e43e80-1c9c-11ea-8fd0-332220beed0e.jpg)



![Screenshot_2019-12-12-05-01-51-602_com android chrome](https://user-images.githubusercontent.com/31348972/70679074-c55e7800-1c9c-11ea-875c-cbb78e465d53.jpg)

@natke, compare the previous screenshots. Some black text on transparent background won't be noticable in high contrast. and it will be hardly readable in dark mode.

**Comment by mairaw** [comment]
I can reproduce this problem. This is about some of the label colors, not the entire image. Using a non-transparent background usually solves this issue.

![image](https://user-images.githubusercontent.com/12971179/70679308-94a12300-1c49-11ea-9833-ca88a6a14b21.png)

**Comment by y2k4life** [comment]
My apologies I was not clear nor did I reference images I figured the page would be viewed in the various themes. I should have stated the labels in the images can't be seen.

**Comment by luisquintanilla** [comment]
@y2k4life thanks for raising this issue. The images have been updated and changes should be reflected shortly.
