### ISSUE TITLE
This page has no suggestions on automating assembly versioning

### ISSUE THREAD

**Issue by progalgo** [dotnet/docs#16186]
In age of DevOps there is a need for automated versioning. There are some custom solutions and shaky scripts but no particular seamless mechanism devised by Microsoft to specify assembly version during continuous integration. At least not on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3041cbd3-6a5e-515c-f261-e228bae5783a
* Version Independent ID: 2e1387a8-577b-19bb-f445-d3007fde88fe
* Content: [Assembly versioning](https://docs.microsoft.com/en-us/dotnet/standard/assembly/versioning?redirectedfrom=MSDN)
* Content Source: [docs/standard/assembly/versioning.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/versioning.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
I don't know of any default system. Generally this is based on your build system, such as Visual Studio. Various addins can do this too, such as 

- https://marketplace.visualstudio.com/items?itemName=PrecisionInfinity.AutomaticVersions&ssr=false#qna
- https://stackoverflow.com/questions/43019832/auto-versioning-in-visual-studio-2017-net-core

If anything, I would file a feature request with https://github.com/dotnet/sdk asking for this feature. They may be able to help you if that feature actually does exist, and then we could update the docs to describe it.

Sorry we can't be of more help here on the docs.
