### ISSUE TITLE
aspNetCompatibilityEnabled default value

### ISSUE THREAD

**Issue by 0shi** [dotnet/docs#16194]
The  description of the `aspNetCompatibilityEnabled` attribute states that it defaults to `false`, but the [linked article](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/wcf-services-and-aspnet) with more information states that it defaults to `true` - 
> This value defaults to "true" if not specified. Setting this value to "false" indicates that all WCF services running in the application will not run in ASP.NET Compatibility Mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210f3a6-54ec-b43a-2d19-aa73aba36469
* Version Independent ID: f0efb705-269c-98c6-25cd-ee45d4ab95bc
* Content: [&lt;serviceHostingEnvironment&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/servicehostingenvironment#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/servicehostingenvironment.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/servicehostingenvironment.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Sent email to @HongGit

**Comment by HongGit** [comment]
Correct, the default value for aspNetCompatibilityEnabled attribute is false, the [linked article](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/wcf-services-and-aspnet) needs to be updates, @Thraka .
