### ISSUE TITLE
Static != Readonly

### ISSUE THREAD

**Issue by grstearns** [dotnet/docs#16192]
In the CardType class, those static members should be `public static readonly CardType ...`. Otherwise, it's possible for someone to reassign something that everyone would assume to be unchanging.

Hate to pick nits, but I once read that "example code should be exemplary."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by gewarren** [comment]
The members are:

```
 public static CardType Amex = new CardType(1, "Amex");
 public static CardType Visa = new CardType(2, "Visa");
 public static CardType MasterCard = new CardType(3, "MasterCard");
```

**Comment by grstearns** [comment]
Which allows one to do this:

```C#
void Main()
{
	Console.WriteLine($"{CardType.Amex.Id}: {CardType.Amex.Name}");

//	// These are compile-time errors
//	CardType.Amex.Name = "something totally different";
//	CardType.Amex.Id = 42;
	
	// However, this is completely legal.
	CardType.Amex = new CardType(42, "something totally different");
	Console.WriteLine($"{CardType.Amex.Id}: {CardType.Amex.Name}");
}
```
```
1: Amex
42: something totally different
```

Marking it as 
```C#
public static readonly CardType Amex = new CardType(1, "Amex");
```
also makes the above change a compile-time error.

I will submit a PR shortly.

**Comment by grstearns** [comment]
https://github.com/dotnet/docs/pull/16339

**Comment by jess-rod** [comment]
I agree. Aren't you going to update the example?

**Comment by grstearns** [comment]
I linked a PR above, but it’s still in review.
