### ISSUE TITLE
Lacking important features

### ISSUE THREAD

**Issue by Allann** [dotnet/docs#16205]
Sounds awesome, but since you can't use it with EFCore due to navigation property circular references, or deserialization to immutable POCOs (private or internal setters) this library, or subobjects being ignored, this is near useless until .NET 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Allann Thanks for the comments.  For the latest information on reference handling, see issues [37786](https://github.com/dotnet/corefx/issues/37786) and [38579](https://github.com/dotnet/corefx/issues/38579). On private setters, see [38163](https://github.com/dotnet/corefx/issues/38163).  I don't understand the reference to "subobjects being ignored" -- could you clarify what you mean by that?

**Comment by Allann** [comment]
https://github.com/dotnet/corefx/issues/42515

**Comment by tdykstra** [comment]
These feature gaps are now documented in the Migrate from Newtonsoft.Json article. See the [section on Newtonsoft.Json features not supported in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#scenarios-that-jsonserializer-currently-doesnt-support).
