### ISSUE TITLE
Include information on Generic types

### ISSUE THREAD

**Issue by fiksen99** [dotnet/docs#16204]
If I want to include a reference to a generic type, the format isn't clear. The format should be of the form:
&lt;see cref="IDictionary{T, U}" /&gt;

We should document how to format this. Also (I'm unsure if possible), indicate how to reference T and U (in this example) as concrete type (when it is known at compile time what those types are).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @fiksen99 

I've added this to our backlog to address when we next update this article.

**Comment by BillWagner** [comment]
reopening to address as part of the XML doc cleanup
