### ISSUE TITLE
Not Helpful Unless Using Windows Update

### ISSUE THREAD

**Issue by jefferyp1138A** [dotnet/docs#16218]
Where is the download link to install the .Net 3.5.1 Windows Feature? I need to run the Wix installation tools with Visual Studio but can't because Windows Update is locked out. I can get this installed but it will take weeks if I wait for corporate IT. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@jefferyp1138A Does this link work? I just searched for a standalone installer. If it works, we'll update the article: https://www.microsoft.com/en-us/download/details.aspx?id=25150

**Comment by h167557** [comment]
The standalone installer from the link says it must download files with no option to install the downloaded file. The only two options are to download and cancel the install. This is terrible as I have devices that don't have access to a network. I tried using a hotspot and it's been downloading for over 30 minutes.

**Comment by mairaw** [comment]
The article links to https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism where it explains how to install 3.5 with no internet connectivity.

**Comment by eddiegutomo89** [comment]
saya tidak bisa memasang Instal .NET Framework 3.5 pada Windows 10, Windows 8.1, dan Windows 8
[https://docs.microsoft.com/id-id/dotnet/framework/install/dotnet-35-windows-10](url)

> #
