### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ManWithoutName** [dotnet/docs#16230]
How would you handle an error if, say the toaster burned the toast, didn't pop up, and caught fire?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/index#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great idea @ManWithoutName 

How exceptions are handled in async tasks is a large enough topic that it should be its own article. I hadn't thought about extending this with error conditions, but it is a great next step. 

I've added this to our backlog to address in an upcoming sprint.

**Comment by nunorelvao** [comment]
On my experience indeed this overview is good , but quite simplistic on real usage case, as mentioned by "ManWithoutName" i too thik that needs to talk also about Error Handling (How Exceptions are handled or should be, and how could you for example have a TASK function that is not "async" and inside how can you call another that is "async" . Beste practices with all possible scenarios (ERROR Handling, Task.Result vs Wait() for ex...)

**Comment by ManWithoutName** [comment]
Unless I'm still missing something, I still don't see any error handling... @dotnet/docs #16230
