### ISSUE TITLE
What's the point of having "var toast = await ToastBreadAsync(number);"?

### ISSUE THREAD

**Issue by c0dilla** [dotnet/docs#16238]
Even more generally speaking, whats the point of having an async task in another async task, where it is immediately awaited for?
considering the next code, When Main starts making the toast, it is already free to keep on running. When the toast is making the bread in hangs there anyway for the bread to be ready before applying the jam. So why would we make it an asynchronous task?

private async void main()
{
    var toast = async MakeToast()
    // ...
}

private async Task MakeToast()
{
    await MakeBread();
    applyJam();
}

private async Task MakeBread()
{
    // ...
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the question @c0dilla 

In this program, it's a step along the path to transform the initial synchronous sample to a fully asynchronous one.

In larger programs, this construct frees a thread resource to possible do other work. If a thread waits synchronously, it can't be used for other work. 

This is most common in web applications, where responding to a request often involves retrieving data from another service or a database. While that request is in flight, the thread can be active servicing other requests.

I didn't cover that in this article, both for length and to keep this as an introduction. Other articles in this section cover this information, and we'll be adding more in the futre.

I hope that answers your question. I'll close this, but if this didn't help, re-open the issue and add more questions.
