### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by SuperNova911** [dotnet/docs#16237]
Like other LINQ articles
Query expression syntax examples for `Join`, `GroupJoin` would be nice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc59b33-c264-8ccd-a0e3-e916d1ce676f
* Version Independent ID: 8f71c9ce-d29b-da24-8262-e1ab82fe4cc9
* Content: [Join Operations (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/join-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/join-operations.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/join-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great thought @SuperNova911 

As with the earlier examples, would you like me to assign this to you?

**Comment by SuperNova911** [comment]
@BillWagner Why not lol 😄

**Comment by BillWagner** [comment]
Thanks @SuperNova911 . I've assigned this to you.
