### ISSUE TITLE
Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2  

### ISSUE THREAD

**Issue by kumbasar** [dotnet/docs#16239]
Currently, it seems that your Debian Mirror is broken:

deb https://packages.cloudfoundry.org/debian stable main
Get:1 https://packages.microsoft.com/debian/10/prod buster InRelease [3959 B]
Get:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages [156 kB]
Err:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 Packages
  File has unexpected size (18556 != 156065). Mirror sync in progress? [IP: 13.80.10.205 443]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Hit:2 http://cdn-fastly.deb.debian.org/debian buster InRelease
Hit:4 http://security-cdn.debian.org/debian-security buster/updates InRelease
Hit:5 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease
Get:6 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease [2665 B]
Get:7 https://cf-cli-debian-repo.s3.amazonaws.com stable/main amd64 Packages [9831 B]
Fetched 16.5 kB in 1s (12.3 kB/s)
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/debian/10/prod buster InRelease (expected buster but got stable)
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (18556 != 156065). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

Could you please check out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9f32d7f-c8f4-b900-4c5d-ea736709dd2e
* Version Independent ID: 5c5ddf0e-0c21-2392-0245-0eb823f36fc2
* Content: [Install .NET Core on Debian 10 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian10#feedback)
* Content Source: [docs/core/install/linux-package-manager-debian10.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-debian10.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by nullseed** [comment]
I'm having the same problem with the ubuntu package:

```
Get:14 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [156 kB]
Err:14 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  Hash Sum mismatch
Fetched 88.5 kB in 0s (93.7 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ahzf** [comment]
I have the same problem with Debian 10 :(

**Comment by Thraka** [comment]
Looks like there is a bigger issue right now. https://github.com/dotnet/core/issues/3995 can you follow up on that thread? Some are reporting it's working again. I'm going to close this issue.
