### ISSUE TITLE
The .NET Core package-manager-based install page isn't as clear as the old site about only supporting x86-64

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#16245]
On the old site, there was a clear, bold message about the package repos only supporting x64. Along the lines of "Not using an x64 machine? Use the other install methods instead", linking to the download table.

It's very common for people using e.g. Raspberry Pi to try to download .NET Core with the package repo. The error message is extremely unclear, just saying it can't find the package, so it's important to make it very easy to spot in the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Install .NET Core on Ubuntu 19.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Agreed. I can link back to https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux#supported-operating-systems and at least put some quick information about the supported architectures on each page.

yes?

**Comment by evancg37** [comment]
Oh wow. Thanks for mentioning that, I was still trying to install it over and over with no luck on my PI.
