### ISSUE TITLE
Install script is not signed

### ISSUE THREAD

**Issue by jozefizso** [dotnet/docs#16242]
Why is the PowerShell script unsigned? How do we know we are running a legitimate script when it's downloaded from internet on each build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@jozefizso I'm going to move this issue to the cli repo where the source of the script is.

**Comment by Thraka** [comment]
This issue was moved to dotnet/cli#13159

**Comment by mairaw** [comment]
It should probably go to the sdk repo instead.
