### ISSUE TITLE
 Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Hash Sum mismatch

### ISSUE THREAD

**Issue by OnecodexGitHubAdmin** [dotnet/docs#16243]
Hi there

I tried to install dotnet core 3.1 on my debian 9 machine.
I did it exactly the same way as described here:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian9

When trying the sude apt-get update command it throws the following error:

Err:8 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Hashes of received file:
   - SHA512:a18b4df496d00477e52cf62e01c9f6c9534926ad0e3bf17f94fc28fc9bd91d5ee5e906b460477e2c1b280a5757a067937c9b2724bd6c72066e982a19306f28b8
   - SHA256:94e637dd6df186bbed5a19f2e7bdc2dcc8f7bb0feb2f1eaf93f05b45dd322cc4
   - SHA1:fb9e80e17952a577030e9266737b23269c8d878b [weak]
   - MD5Sum:4360374f4ec05159ef14908c0dbf4116 [weak]
   - Filesize:68668 [weak]
  Last modification reported: Fri, 13 Dec 2019 01:35:23 +0000
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000

Any idea what's going wrong, here?

Thanks in advance
Magnus

EDIT by @thraka - Adding doc details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4fb70e-8d93-5890-a259-06ae5f37c994
* Version Independent ID: 8846709d-4f43-30f8-3b09-b61dee716b90
* Content: [Install .NET Core on Debian 9 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian9)
* Content Source: [docs/core/install/linux-package-manager-debian9.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-debian9.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@ondrejstrouhal Can you provide the kernel version and architecture you're running on?

@leecow Can you confirm the download hash?

**Comment by Thraka** [comment]
@ondrejstrouhal Actually, I just discovered there is an outage. Your problem is probably related to that: https://github.com/dotnet/core/issues/3995

**Comment by OnecodexGitHubAdmin** [comment]
I recognized that there was a general issue with the repositories on several linux distributions.
[dotnet/core#3988](https://github.com/dotnet/core/issues/3988)
So my problem is already solved. 
Anyway thanks a lot for your response
