### ISSUE TITLE
C# Docs structure

### ISSUE THREAD

**Issue by mrmowji** [dotnet/docs#16255]
I'm checking [C# docs](https://docs.microsoft.com/en-us/dotnet/csharp); it's been a while. I've checked them before, but now, they're separated from .NET docs which is an improvement. But there are some issues I like to mention. Hope it helps, and brings more joy and more fluent experience to readers learning C# (or other .NET areas).

- I think everyone would agree on this one: **duplicate content**, which might be solved by solving the next issue.
- **Similar category under different names**. For example we have **Tutorials** and **How-To C# Topics**, which in my opinion are the same thing, or at least the difference is not that important to separate them. Maybe those two categories and **C# Concepts** could be merged into **C# Programming Guide**, so we have **one category instead of four**.
- **Tour of C#** could be under **Get Started**; that's a start thing.
- Some pages have their own docs tree; reader doesn't have access to the whole tree on those pages, they need to go back. For example see [Explore C# 6](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6).
- **Unimportant pages**. Under **How-To C# Topics** we have [Topic Index](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/) which is basically a collection of links to some articles. But that's why we have **Filter by Title**. From a learners' point of view, these kind of pages might be just stressing.
- **Knowing new concepts** is expected from the reader, even in some of the beginner's docs.
- **Walkthroughs** page is not necessary. Some links on that page, are from C# Programming Guide, and some of them are from different areas of .NET. It'd be better to simply direct the reader to the index pages of those areas, which is done in [the .NET docs index page](https://docs.microsoft.com/en-us/dotnet/). I mean the reader would understand where to go after learning C#; no need to provide some random articles.
- **The order**. Based on the previous suggested changes, I think the following order is a good start:
  - Get Started
  - What's new in C#
  - C# Programming Guide
  - The .NET Compiler Platform SDK (Roslyn APIs)
  - Language Reference

**Comment by BillWagner** [comment]
That's very good feedback @mrmowji 

We've started planning for many of the changes you've requested above.  I've summarized the plan in this [gist](https://gist.github.com/BillWagner/047cb97f6c0fe542d3a1299e994b2acd). We'll keeping working on making improvements.

Thanks for adding your thoughts.

**Comment by mrmowji** [comment]
@BillWagner Thanks. Towards better docs. I love it.

**Comment by BillWagner** [comment]
I'm closing this. Many of the suggestions have been taken. The others are captured in tasks in the updated TOC for #22552
