### ISSUE TITLE
libicu not found

### ISSUE THREAD

**Issue by giovanism** [dotnet/docs#16254]
libicu is named [icu](https://build.opensuse.org/package/show/openSUSE%3AFactory/icu) on both Leap 15.1 and Tumbleweed version of openSUSE. Any idea for new installation method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Install .NET Core on openSUSE 15 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15#feedback)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for reporting this problem. @dagood will take a look and get back to you. Thanks!

**Comment by dagood** [comment]
This seems to be caused by a change in Leap 15.1 to remove the `libicu` "provides" clause in the package build. This was previously limited to the Tumbleweed distro (which we don't support) but it looks like it's included in Leap 15.1 now. More description from https://github.com/dotnet/core/issues/3500#issuecomment-536331871

> This is unfortunate... in the past, packages like `libicu-suse64_2` had a "provides" clause for `libicu`, so the dependency `dotnet-runtime-deps` has on `libicu` was resolved by having that package installed. ("Provides" dependencies are a little hard to dig up, IIRC they work with `zypper install` but don't show up in `zypper search`.) This "provides" clause allowed the same RPM package to work on 15 and Tumbleweed. 
> 
> For now, I believe you can safely ignore the dependency (solution 2) because you have the `libicu-suse64_2` package installed.
> 
> It looks like the "provides" removal was an intentional change by the package's maintainers: https://build.opensuse.org/request/show/724944.
> 
> > Remove old obsoletes/provides for migration from very old
> > 6+  products, as they break our shared library policy

Since we do support Leap 15+, we need to change this now. This means we'll need to have separate dropdown entries per distro, and release a new deps package for each version. I've filed https://github.com/dotnet/runtime/issues/913 for this work.

---

> libicu is named [icu](https://build.opensuse.org/package/show/openSUSE%3AFactory/icu) on both Leap 15.1 and Tumbleweed version of openSUSE.

This isn't exactly true, the package we need has always been `libicu###`, it just used to be that we could depend on it as "`libicu`", as a kind of alias.

`icu` contains extra data that .NET Core doesn't need, so we shouldn't depend on it or else we'll be cluttering up people's machines.

> Any idea for new installation method?

You can install .NET Core manually, or install via the package manager and just ignore the dependency. (What's important is that libicu is installed, the package name doesn't need to be exact.)

For more info about the manual install, check out https://docs.microsoft.com/en-us/dotnet/core/install/sdk.

**Comment by dagood** [comment]
I'm not able to repro this, @giovanism can you confirm you're seeing an issue with the `sudo zypper install libicu` line on openSUSE Leap 15.1? This run in Docker is fine:

```
#> docker run -it --rm opensuse/leap:15.1 zypper install -y libicu
Building repository 'Non-OSS Repository' cache ...................................................................[done]
Building repository 'Main Repository' cache ......................................................................[done]
Building repository 'Main Update Repository' cache ...............................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..........................................................[done]
Loading repository data...
Reading installed packages...
'libicu' not found in package names. Trying capabilities.
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  libicu60_2 libicu60_2-ledata timezone
```

(The leap 15.1 Docker image might not represent the state of the "real" repo, or maybe you have different repos enabled?)

**Comment by giovanism** [comment]
Previously I checked via `zypper if libicu` on opensuse/leap:15.1. I cross checked to software.opensuse.org too to see the package but finds nothing. I am myself running tumbleweed, so I cant directly try it, but i stopped when I find
```Retrieving: netstandard-targeting-pack-2.1.0-x64.rpm ........................................................................................................................................................[done (294,8 KiB/s)]

Warning: Digest verification failed for file 'netstandard-targeting-pack-2.1.0-x64.rpm'
[/var/tmp/AP_0xKzJJL3/netstandard-targeting-pack-2.1.0-x64.rpm]

  expected 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480
  but got  fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41

Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.

However if you made certain that the file with checksum 'fa19..' is secure, correct
and should be used within this operation, enter the first 4 characters of the checksum
to unblock using this file on your own risk. Empty input will discard the file.

Unblock or discard? [fa19/...? shows all options] (discard): fa19
```

`zypper if` finds packages, not `capabilities`.
In short I was really stupid. Thanks and sorry to wasting your time.

**Comment by dagood** [comment]
Hey, no worries. This is definitely a rough spot on our packages. I've seen that Tumbleweed took this patch (causing our dependency not to work there) but I don't think I've really thought about how Leap will probably eventually take it as well. We should catch this when we try our packages on new Leap versions, good to have it in mind though.
