### ISSUE TITLE
Typo in the "Supported client operating systems" part

### ISSUE THREAD

**Issue by phuclv90** [dotnet/docs#16267]
There's a stray `|` in

&gt; On 64-bit operating systems, the .NET Framework supports both WOW64 (32-bit processing on a 64-bit machine) and| native 64-bit processing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#feedback)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks @phuclv90 I submitted a PR to fix this.

BTW, when you find small issues like this, you can submit a PR by clicking the "edit' button on the page.

**Comment by phuclv90** [comment]
Thanks. I've never notice that there's an edit button since it disappears when I scroll down. Will do that next time
