### ISSUE TITLE
Bad command line practice

### ISSUE THREAD

**Issue by carlosporter** [dotnet/docs#16262]
The commands used on this document are too redundant about the use of "apt-get update", you need to run the command only once after installing the package packages-microsoft-prod.deb which adds the Microsoft repository.

The same thing to command that installs that "universe" repository

And it's not necessary to run "apt-get update" before every single "apt-get install" command

You can take this:

```
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-3.1
```

And just replease it with this:

```
sudo apt-get update
sudo apt-get install apt-transport-https dotnet-sdk-3.1 -y
```

EDIT by Thraka. Moved the comment from below into this one and added the doc header

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Install .NET Core on Ubuntu 19.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by carlosporter** [comment]
The commands used on this document are too redundant about the use of "apt-get update", you need to run the command only once after installing the package packages-microsoft-prod.deb which adds the Microsoft repository.

The same thing to command that installs that "universe" repository

And it's not necessary to run "apt-get update" before every single "apt-get install" command

You can take this:

```
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-3.1
```

And just replease it with this:

```
sudo apt-get update
sudo apt-get install apt-transport-https dotnet-sdk-3.1 -y
```

**Comment by mairaw** [comment]
Thanks for your feedback @carlosporter. I imagine this is related to one of the Linux package manager articles, correct?

/cc @leecow

**Comment by carlosporter** [comment]
Hello,

The comment is in regards of the instructions provided on this document:

https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904

The same issue can be seen on https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

**Comment by dagood** [comment]
> ```
> sudo apt-get update
> sudo apt-get install apt-transport-https dotnet-sdk-3.1 -y
> ```

If our running theory on what's going on here is correct, we **do** need to update after installing `apt-transport-https`, because it allows the `update` against the Microsoft Linux package repo to work. Our repo uses https, so until apt-transport-https is installed, it will fail.

I'd argue that maybe it should say to install `apt-transport-https` before setting up the feed (to avoid potentially confusing errors showing up!). Keeping the number of command blocks down might be a factor, though. (Less back-and-forth copy-pasting.)

More info from https://github.com/dotnet/core/issues/3432#issuecomment-534190797:

> The `apt-transport-https` is required to download repo info from the Microsoft package repository, I believe, so I think you need another update in between [...]:
> 
> ```shell
> sudo add-apt-repository universe
> sudo apt-get update # In case you didn't have universe enabled.
> sudo apt-get install apt-transport-https
> sudo apt-get update # Get the Msft repo info behind an https url.
> sudo apt-get install dotnet-sdk-3.0
> ```

@scalablecory

**Comment by Thraka** [comment]
I'm going to close this as it seems there is no issue to fix in the docs.
