### ISSUE TITLE
Mistake in example

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/docs#16279]
In the example about the `switch` statement, after "can be reversed without affecting the behavior of the statement:", the label `case 2:` is missing.

Old:

```csharp
    switch (i) {
    default:
        CaseAny();
        break;
    case 1:
        CaseZeroOrOne();
        goto default;
    case 0:
        CaseZero();
        goto case 1;
    }
```

New:

```csharp
    switch (i) {
    default:
    case 2:
        CaseAny();
        break;
    case 1:
        CaseZeroOrOne();
        goto default;
    case 0:
        CaseZero();
        goto case 1;
    }
```

EDIT by Thraka: Add the code blocks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964ae3d9-f201-1331-2004-8ea5c3dac2ee
* Version Independent ID: 032b0ad6-855e-9af8-a118-d0131158dc2a
* Content: [Statements - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#feedback)
* Content Source: [spec/statements.md](https://github.com/dotnet/csharplang/blob/master/spec/statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I'm not sure if it was intentionally removed. The text doesn't make that clear. Functionally though, `case 2` still falls into `default` so I think it could be added back in for consistency.

I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
