### ISSUE TITLE
Wrong wording in documentation

### ISSUE THREAD

**Issue by Khaled-Janada** [dotnet/docs#16272]
The contract type should be "IMyAddin" not "IMyData" in the sentence:
"This class defines a custom attribute named MyAttribute with contract type IMyData"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1d105d-2214-236d-931d-b914fd891f22
* Version Independent ID: 9d0adb5b-f7c8-a856-f90d-5ea6763ab657
* Content: [Attributed Programming Model Overview (MEF)](https://docs.microsoft.com/en-us/dotnet/framework/mef/attributed-programming-model-overview-mef#feedback)
* Content Source: [docs/framework/mef/attributed-programming-model-overview-mef.md](https://github.com/dotnet/docs/blob/master/docs/framework/mef/attributed-programming-model-overview-mef.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Khaled-Janada. Would you like to submit a pull request to fix that?
Here's how: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
