### ISSUE TITLE
New topic: Debugging .NET Core on Unix over SSH

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#1627]
Need doc covering content on [team blog on this topic](https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/).

The blog states:  *you need to install the ‘ASP.NET and web development’ workload*
Is that still true?

Show how to debug a console app - shouldn't need ASP.NET Core.

@mairaw @Andrew-MSFT please review
Per Andrew: it would be good to add doc’ing how to remote debug to Linux from VS into our docs.  The

**Comment by mairaw** [comment]
I think it's a good idea. If it's a console application, what you need is the .NET Core cross-platform development workload.

**Comment by mairaw** [comment]
Never mind what I said earlier about the workload. I don't know the requirements for this particular scenario. I'll leave it up to @Andrew-MSFT. But it's a good topic, I think.

**Comment by Andrew-MSFT** [comment]
You need either the ASP.NET and web development workload or the .NET Core cross platform workload installed

**Comment by mairaw** [comment]
If the common scenario is ASP.NET, should we move this to aspnet then @Rick-Anderson?

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Docs/issues/2960
