### ISSUE TITLE
Sample code not found

### ISSUE THREAD

**Issue by marlonedu** [dotnet/docs#16274]
The source code for the project not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2dd5bf-6e11-49e5-d88c-5858873770bc
* Version Independent ID: ae9cb1d8-4f64-43fa-e16d-1db60067a430
* Content: [Fine-Tuning Your Async Application (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/fine-tuning-your-async-application#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/fine-tuning-your-async-application.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/fine-tuning-your-async-application.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
It's a known issue, https://github.com/dotnet/docs/issues/13599.

**Comment by Youssef1313** [comment]
Currently, the sample is archived [here](https://github.com/microsoftarchive/msdn-code-gallery-community-a-c/tree/master/Async%20Sample%20%20Fine%20Tuning%20Your%20Application%20(C%23%20and%20Visual%20Basic)).

**Comment by marlonedu** [comment]
Thank you!!

**Comment by BillWagner** [comment]
Thanks for adding the pointer @Youssef1313 

I'm glad that helped @marlonedu 

I'll close this as a duplicate.
