### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16283]
The link for *diagnostics tutorials* in https://docs.microsoft.com/samples/dotnet/samples/diagnostic-scenarios/ is broken.

cc: @sdmaclea

**Comment by Thraka** [comment]
@sdmaclea Do you remember where this link was supposed to go? I couldn't find anything in the git history that points to a file existing there.

**Comment by sdmaclea** [comment]
It is supposed to point at a file which will be introduced by https://github.com/dotnet/docs/pull/14110

**Comment by Youssef1313** [comment]
This PR doesn't have a file called *diagnostic-scenarios.md* under a *tutorial* directory. Is the work on this PR still in progress ?

**Comment by sdmaclea** [comment]
Yes it is still in progress.  The layout of the PR changed since the sample was added.  That file was removed and the content was placed in docs/core/diagnostics/index.md

**Comment by Youssef1313** [comment]
So, the link should be updated from *diagnostics/tutorials/diagnostic-scenarios.md* to *diagnostics/index.md* ?

**Comment by sdmaclea** [comment]
Yes.

**Comment by Youssef1313** [comment]
@sdmaclea, Thanks for confirmation. I've opened a PR in the samples repo. dotnet/samples#1855.

**Comment by Youssef1313** [comment]
Fixed.
