### ISSUE TITLE
See also\Types links to C# Keywords

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [dotnet/docs#16287]
The point Types in [See also](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/pointer-conversions#see-also) chapter links to [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a2663a9-16e5-31b7-4841-3f574871b047
* Version Independent ID: 471e5c1c-1f4a-a23a-b791-bbae59fe712d
* Content: [Pointer Conversions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/pointer-conversions)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/pointer-conversions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/pointer-conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Probably the best thing to do here is to replace this link with two links, the value types and reference types.

**Comment by BillWagner** [comment]
Thanks @Youssef1313 That is a good recommendation.
