### ISSUE TITLE
Contradictory info on String.CompareTo

### ISSUE THREAD

**Issue by spazmodius** [dotnet/docs#16286]
[How to compare strings in C#](/dotnet/docs/blob/master/docs/csharp/how-to/compare-strings.md)
contains conflicting information about `String.CompareTo()`

Under the heading **Default ordinal comparison**, it says
> By default... String.CompareTo... performs a case-sensitive ordinal comparison...

Yet, two paragraphs below that, it says
> the comparison methods perform a case-sensitive, culture-sensitive comparison using the current culture

Under the heading **Ordinal sorting and searching in collections**, it says
>The String.CompareTo method provides that comparison function. ... This sort operation uses an ordinal case sensitive sort.

The **Note** at the article's end says
>The String.CompareTo instance methods always perform an ordinal case-sensitive comparison

The linked documentation for [String.CompareTo](https://docs.microsoft.com/en-us/dotnet/api/system.string.compareto) says
> Both overloads of the CompareTo method perform culture-sensitive and case-sensitive comparison. You cannot use this method to perform culture-insensitive or ordinal comparisons.

EDIT by Thraka to add doc details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ecfc18-477b-f792-4136-2feb46bbc5d3
* Version Independent ID: 82f53ae8-a9d4-dea9-5acd-6d9202a40882
* Content: [How to compare strings - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings)
* Content Source: [docs/csharp/how-to/compare-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/compare-strings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Explaining the default behavior in different ways is indeed confusing. This should be the same sentence for each section where it is required to provide this information.
