### ISSUE TITLE
Fedora 31

### ISSUE THREAD

**Issue by Lightgazer** [dotnet/docs#16281]
There no page for fedora 31.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3e656d98-d9c6-3feb-c663-96894c813213
* Version Independent ID: 39aa858c-592b-d57f-eb78-759d5add5f35
* Content: [Install .NET Core on Fedora 30 - package manager - .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/install/linux-package-manager-fedora30#feedback)
* Content Source: [docs/core/install/linux-package-manager-fedora30.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-fedora30.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@leecow Should there be one?

**Comment by Lightgazer** [comment]
It latest release version. The instructions on the Fedora 30 page work but it could confuse people like there no support for 31.

**Comment by TrumanQ** [comment]
The repo file was just released here: https://packages.microsoft.com/config/fedora/31/.   
But when I tried to install the SDK with dnf, it shows
"Errors during downloading metadata for repository 'packages-microsoft-com-prod':
  - Status code: 404 for https://packages.microsoft.com/fedora/31/prod/repodata/repomd.xml (IP: 13.91.48.226)"

At least, It's coming~

**Comment by Thraka** [comment]
It is... Just bad timing with the holidays. Many people are out. 😄
