### ISSUE TITLE
This isn't the illustration you're looking for

### ISSUE THREAD

**Issue by ruvor** [dotnet/docs#16298]
The picture here in this article doesn't answer to the description in the paragraph below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958fc635-d7d3-8ac2-bfbb-d723c27d54b0
* Version Independent ID: 5ea85a53-54a5-3bd2-1623-c4d14d2e5e71
* Content: [Assembly contents](https://docs.microsoft.com/en-us/dotnet/standard/assembly/contents#feedback)
* Content Source: [docs/standard/assembly/contents.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/contents.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Thank you @ruvor. You are right, and I'll get this fixed.

**Comment by gewarren** [comment]
Note to self: https://github.com/dotnet/docs/blob/69f825f8b65a5c7eb67d552328ecca072a84924d/docs/framework/app-domains/assembly-contents.md is the original file.
