### ISSUE TITLE
regex fails on names that end with underscore

### ISSUE THREAD

**Issue by brucemcmillan** [dotnet/docs#16299]
I have created a test hotmail account

bruceweqweqwewqeqwe_@hotmail.com

it exists  but the regex fails it as a check, note the last char of the name is an underscore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to verify that strings are in valid email format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format?redirectedfrom=MSDN)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
What to do about this article is discussed in #9547
