### ISSUE TITLE
Add the dotnet/runtime .editorconfig to our samples repo

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#16302]
We've long stated that we generally follow the ]dotnet/runtime coding standard](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md).

They've not added an [.editorconfig](https://github.com/dotnet/runtime/blob/master/.editorconfig) that enforces these guidelines. 

We should add it to our samples repo.

**Comment by Youssef1313** [comment]
Can't the file just copied as it is ?
