### ISSUE TITLE
Service is created on windows but is not acessible anywhere...

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/docs#16305]
I was trying this aproach to see if this way i could expose a aspnet core 3.1 gRPC service to other aplications outside my machine. None of them can access the gRPC server. Only applications running on my machine can access the gRPC server at https://localhost:5001
I was hoping that running the aplication as a service would overcome the kastrel limiting the service on localhost..
What can i do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c957b4-4da9-2cda-b08e-ce78e5333768
* Version Independent ID: 2bf00fa5-70c1-b1a0-45c2-5a201f597066
* Content: [Self-hosted gRPC applications - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/self-hosted)
* Content Source: [docs/architecture/grpc-for-wcf-developers/self-hosted.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/self-hosted.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by shirhatti** [comment]
The Kestrel server in ASP.NET Core by default only to traffic on loopback. You'll need to configure your application to listen to external traffic. See the relevant Kestrel docs on how to [configure your endpoint](https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#endpoint-configuration).

**Comment by Ricardoaraujo00** [comment]
Thank you for your response @shirhatti 

I don't know why that isn't stated in thi explanation:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/self-hosted

I dont even know if the service i've created is running. Even if i do sc start myservice i cannot access it in local host in either ports(5000/5001). I get "localhost refused to establish connection".

Also that link you gave me has so many things that i don't understand that i'm really lost. Shouldn't there be a option as simple as "KESTREL SERVE TO OUTSIDE: true".

Nobody understands that explanation as there is not one single video tutorial on the internet explaining that. Or if you know please give me one because i cannot undertand what am i suposed to do with that explanation.

**Comment by Ricardoaraujo00** [comment]
Also i think that title of the explanation should refer WCF, because i'm following that explanation for a aspnet core gRPC service and it seems that that only applies to applications that uses WCF, wich achordin to this statment on stacoverflow:

`WCF is not supported in .NET Core since it's a Windows specific technology while .NET Core is supposed to be cross-platform`
https://stackoverflow.com/questions/48522849/what-replaces-wcf-in-net-core

 seems that core doesn't use WCF, so what to do? Where are the instructions on how to self host a aspnet core gRPC service? Do you know?

**Comment by shirhatti** [comment]
> I dont even know if the service i've created is running. Even if i do sc start myservice i cannot access it in local host in either ports(5000/5001). I get "localhost refused to establish connection".

Local refused to connect means that nothing is listening on the specified port. Either your service failed to start or failed to bind to the specified port.

> Also that link you gave me has so many things that i don't understand that i'm really lost. Shouldn't there be a option as simple as "KESTREL SERVE TO OUTSIDE: true".

It's specified in this section- https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#url-prefixes

Anything not recognized as a valid IP address or localhost binds to all IPv4 and IPv6 IPs. For e.g., `http://*:80/`
When localhost is specified, Kestrel attempts to bind to both IPv4 and IPv6 loopback interfaces

> seems that core doesn't use WCF, so what to do? Where are the instructions on how to self host a aspnet core gRPC service? Do you know?

Given that there is no server component of WCF on .NET Core, we're touting gRPC as a replacement. gRPC uses the same app model as ASP.NET. Self-hosting gRPC follows the same instructions as the rest of ASP.NET Core

**Comment by Ricardoaraujo00** [comment]
Hi @shirhatti 
Thank you for your reply and explanation.
A colleague of you gave me this appsettings and they work very well
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    },
    "EndPoints": {
      "Https": {
        "Url": "https://192.168.5.56:5001",
        "Certificate": {
          "Path": "c:\\test.pfx",
          "Password": "password1234"
        }
      }
    }
  }
}

```
