### ISSUE TITLE
How to install in a container such as PCF

### ISSUE THREAD

**Issue by sorvis** [dotnet/docs#16301]
I'm looking to install dotnet-trace in a container hosted by PCF. Following the directions I figured out these commands so far get dotnet-trace installed:
```
export PATH="$PATH:/home/vcap/deps/0/dotnet-sdk"
dotnet tool install --global dotnet-trace
ln -s /home/vcap/deps/0/dotnet-sdk/host/fxr/2.1.13/libhostfxr.so /home/vcap/.dotnet/tools/.store/dotnet-trace/3.1.57502/dotnet-trace/3.1.57502/tools/netcoreapp2.1/any/libhostfxr.so
export PATH="$PATH:/home/vcap/.dotnet/tools"
```

---

From here though running dotnet-trace results in:

> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /home/vcap/.dotnet/tools/.store/dotnet-trace/3.1.57502/dotnet-trace/3.1.57502/tools/netcoreapp2.1/any/
>   - Installing .NET Core prerequisites might help resolve this problem:
>       https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download

Any troubleshooting suggestions of how to get at the Microsoft.NETCore.App package? If we can figured this out a troubleshooting section at the bottom of the article may be helpful to others.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57216dad-d87d-eeef-adc8-82bfe4251343
* Version Independent ID: 3e7ab61f-5a06-b92c-5c74-0fae43adb35e
* Content: [dotnet-trace tool - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace)
* Content Source: [docs/core/diagnostics/dotnet-trace.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-trace.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by sdmaclea** [comment]
`Microsoft.NETCore.App` is the runtime. If you run `dotnet --info` the paths to the runtimes are listed in the output.  I would think the tool should run if there is a 2.1.0 or better runtime on the path.
