### ISSUE TITLE
.Net 3.1 hosting bundle installs the preview version of 3.1 runtime

### ISSUE THREAD

**Issue by sadjadbp** [dotnet/docs#16306]
Link to hosting bundle here https://dotnet.microsoft.com/download/dotnet-core/3.1 installs the preview version of 3.1 runtime

**Comment by mairaw** [comment]
@leecow is this tracked somewhere?

**Comment by dagood** [comment]
This is a known issue with 3.1.0, to be fixed with 3.1.1: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#310

Basically, this is a cosmetic issue--it doesn't actually install a preview.

**Comment by sadjadbp** [comment]
dotnet/core#3962
