### ISSUE TITLE
'sn' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by bzaar** [dotnet/docs#16303]
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.3.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>sn
'sn' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>sn.exe
'sn.exe' is not recognized as an internal or external command,
operable program or batch file.
```

The [SN tool documentation page](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool) says

> To start the tool, use the Developer Command Prompt 

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d65a40-0ea7-09ce-33fc-39525310b05e
* Version Independent ID: f6cbd1c2-7708-03aa-a935-0dbfa07e6177
* Content: [Sn.exe (Strong Name Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool#feedback)
* Content Source: [docs/framework/tools/sn-exe-strong-name-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sn-exe-strong-name-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
The *sn.exe* tool is located in *C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\*.

![image](https://user-images.githubusercontent.com/31348972/71014180-2f8e7700-20fa-11ea-93d6-74bdd2fc10d4.png)

**Comment by bzaar** [comment]
@Youssef1313, Thanks. Of course, I can find it and run it. The problem is the [SN tool documentation page](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool) says

> To start the tool, use the Developer Command Prompt 

And I used to be able to do so (although it was called "Visual Studio Command Prompt" back then).

Not sure if it is a problem with the documentation of my set up.

**Comment by Youssef1313** [comment]
@bzaar, On my machine, I can't run the sn command unless I'm in that directory. so I suspect it's a doc issue. but you may need to wait until the issue get reviewed and triaged.

**Comment by mairaw** [comment]
Not sure. I can run just fine just by opening the Command prompt:

![image](https://user-images.githubusercontent.com/12971179/71113849-56dd5680-2183-11ea-8a87-4a04238b1f67.png)

@vivmishra any clues?

**Comment by vivmishra** [comment]
VS developer command prompt should be able to locate .NET Framework SDK tools, so this is not a documentation problem. 
I was able to make this work on my box with VS 16.4.1. 

So, the next step would be to report this via VS Feedback tool (using **Send Feedback -> Report a Problem** from Help menu), if you have a consistent repro and repairing VS is unable to fix it. I would even recommend upgradng to 16.4 (as 16.3 is out of support) and see if it resolves this issue for you.

**Comment by Stuart88** [comment]
Problem still exists in 2023.
