### ISSUE TITLE
System.Xml.IgnoreEmptyKeySequences without Switch at the beggining

### ISSUE THREAD

**Issue by Taron-art** [dotnet/docs#16336]
In the table, all switches are written with Switch in the begging except System.Xml.IgnoreEmptyKeySequences. But in fact, we must write Switch.System.Xml.IgnoreEmptyKeySequences to make it work. Please fix this issue, we spend two days understanding why this does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59350ee-7837-34f8-b50e-c9c136720155
* Version Independent ID: 19747ce7-da26-bf2e-5066-1df11e61b0d0
* Content: [&lt;AppContextSwitchOverrides&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
My apologies for the inconvenience @Taron-art and thanks for letting us know. 
I've opened a PR to fix that: #16348

**Comment by mairaw** [comment]
You can also edit our documentation if you see errors like that:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
