### ISSUE TITLE
A Embedded Statements Problem

### ISSUE THREAD

**Issue by LuGuangguang** [dotnet/docs#16333]
Original web page ： An embedded statement that is not enclosed in {} brackets cannot be a declaration statement or a labeled statement. This is shown in the following example:

But I Runing without problem in following  codes(goto Statement: a labeled statement)  On VS2019
{
 A:
            bool pointB = true;
           
            if (pointB == true)
                goto A;
}
So,are not the goto statement  labeled statements?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0d7fd-3319-2d27-d89a-e92f6ce1285a
* Version Independent ID: b9a529ef-7ba1-6abf-55cf-c6e54935ae66
* Content: [Statements - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/statements#feedback)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/statements.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking this question @LuGuangguang 

The `goto` statement is not a labeled statement. The *destination* of the `goto` is the label (`A:` in your example above).

The article is correct. I'll close this as an answered question.

**Comment by LuGuangguang** [comment]
I have learned.Thank a lot for the answer
