### ISSUE TITLE
./samples/core/console-apps/NewTypes/global.json

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1635]
console-apps/Hello/project.json
console-apps/HelloNative/project.json
console-apps/NewTypes/src/NewTypes/project.json
console-apps/NewTypes/test/NewTypesTests/project.json

**Comment by mairaw** [comment]
Should we close this @rpetrusha? What's the PR number?

**Comment by rpetrusha** [comment]
@mairaw This is addressed by PR #1639
