### ISSUE TITLE
Invalid code for "mutable variation of the 3D point structure" example

### ISSUE THREAD

**Issue by Artur-Laskowski** [dotnet/docs#16362]
The example has invalid format because of: incorrect constructor content, redundant semicolons in properties and a invalid string interpolation structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#feedback)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this (and submitting the related PR) @Artur-Laskowski .  I'll review the PR now.
