### ISSUE TITLE
Console.Write requires a Console.WriteLine

### ISSUE THREAD

**Issue by rjrjack** [dotnet/docs#16373]
Dim salmons As New List(Of String)

salmons.Add("chinook")
salmons.Add("coho")
salmons.Add("pink")
salmons.Add("sockeye")

 '               Iterate through the list.
For Each salmon As String In salmons
        Console.Write(salmon & " ")
Next
Console.WriteLine()                                                ' ##########################
'               Output: chinook coho pink sockeye

In the above code (first example on this page) I had to add the line marked with ' ############  i.e., Console.write() by
itself isn't writing to the console - requires a Console.WriteLine() at the end...

The second example has the same issue. Haven't looked for any more.

Using .NET Framework 4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beec841-2fc0-e46f-b3da-9c921b22d427
* Version Independent ID: 988848ea-f798-3bec-aba0-a33e656ace82
* Content: [Collections - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/collections)
* Content Source: [docs/visual-basic/programming-guide/concepts/collections.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/collections.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
I'm not seeing this problem. What version of Visual Studio are you using, and what kind of project did you paste the code into? I pasted it into a VB .NET Framework console app, ran the program without debugging, and this is what I get:

![image](https://user-images.githubusercontent.com/24882762/71374480-b5ce1180-256f-11ea-9261-2ef837e990a1.png)

**Comment by rjrjack** [comment]
Sorry I haven't replied sooner, been away and just now saw this...

 

Using
Microsoft Visual Studio Community 2019
Version 16.4.2

 

Using

Microsoft .NET Framework

Verion 4.8.03752

 

Project was

Windows Forms App (.NET Framework), Visual Basic

 

 

 



Sent: Monday, December 23, 2019 at 12:33 PM

**Comment by gewarren** [comment]
I'm not sure how you printed to the console at all using a WinForms app. @Thraka Do you know what might be going on here?

We might add a note above the code sample to suggest running it in a console app.

**Comment by rjrjack** [comment]
I'm not actually seeing a console window, I am selecting View / Output / from Visual Studio menu and then

'Show output from Debug'

 

Sent: Monday, December 30, 2019 at 12:11 PM

**Comment by rjrjack** [comment]
My previous response may have answered the issue, but anyway here is the project.

Sent: Monday, December 30, 2019 at 12:11 PM

**Comment by Thraka** [comment]
Visual Studio reads the console output but doesn't print it to the output pane until a newline character is fed to it. In general, windows forms apps don't use `Console.Write[Line]` as it doesn't go anywhere when you run outside of visual studio. A **console application** will instantly display the `Console.Write` output.

**Comment by rjrjack** [comment]
That is the exact behaviour I experienced. Thank you for explanation.
 

Sent: Monday, January 06, 2020 at 6:21 PM

**Comment by Thraka** [comment]
@gewarren I think we can close this.
