### ISSUE TITLE
PR and issue review may be delayed over holidays

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#16372]
This time of the year is holiday season for the .NET content team members in the United States. Many of the team members are taking vacation during the next two weeks.

The result is that PR reviews / merging, and issue response may be delayed during this period.

I wish you all a happy holiday season and hope to see you around here in 2020! 🎆

Thank you for all your contributions in 2019! This community rocks! ❤️

**Comment by BillWagner** [comment]
I'm back working today, as are a few others on the team. Other folks are on holiday until this coming Monday.

**Comment by BillWagner** [comment]
closing as most people are back from the holidays today.
