### ISSUE TITLE
Think example code needs some correction.

### ISSUE THREAD

**Issue by footstep002** [dotnet/docs#16375]
There seems 3 places need to be corrected on the example source code.

'locale = locale.Substring(locale.IndexOf(';') -1);' to 
'locale = locale.Substring(0, locale.IndexOf(';'));'

'cultures[ctr] = new CultureInfo(Request.UserLanguages[ctr], false);' to
'cultures[ctr] = new CultureInfo(locale, false);'

'document.DateForm.DateInfo.value' to
'DateForm.DateInfo.value'

As I've tried these code need to be corrected in order to function properly. Please correct me if I'm wrong. Also have question about the last errata. Wonder why 'document' needs to be left out. Trying to put that in the code like the example did, it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c99d8f1-447a-84b2-9402-319745fc135b
* Version Independent ID: 13928dc4-d9e6-d0b5-022f-69b3e4611380
* Content: [How to: Display Localized Date and Time Information to Web Users](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-localized-date-and-time-information-to-web-users#feedback)
* Content Source: [docs/standard/base-types/how-to-display-localized-date-and-time-information-to-web-users.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-display-localized-date-and-time-information-to-web-users.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

The links to the sample directly are:

- C\#\
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR/Formatting.HowTo.ParseDateInput/cs/GetDateInfo.aspx

- VB\
https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_CLR/Formatting.HowTo.ParseDateInput/vb/GetDateInfo.aspx

Thanks again!
