### ISSUE TITLE
Need documentation on how to disable popup "Required assets to build and debug are missing..."

### ISSUE THREAD

**Issue by DavidPrio** [dotnet/docs#16399]
Hi writing team. I'm reporting documentation need as stated in https://github.com/dotnet/docs.de-de/issues/161.
Contributor reports "I have set ""csharp.suppressDotnetRestoreNotification": true," and still get this very annoying "Required assets ..." popup. As I am working in Monorepos most of the time, I would be grateful if you could give a hint on how to get rid of it."
Thanks in advance!
Microsoft DOCS International Team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Erste Schritte mit C# und Visual Studio Code - .NET Core](https://docs.microsoft.com/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: docs/core/tutorials/with-visual-studio-code.md
* Product: dotnet-core
* GitHub Login: @kendrahavens
* Microsoft Alias: tdykstra

**Comment by DavidPrio** [comment]
Dokumentdetails

⚠ Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.

    ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
    Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
    Content: Erste Schritte mit C# und Visual Studio Code - .NET Core
    Content Source: docs/core/tutorials/with-visual-studio-code.md
    Product: dotnet-core
    GitHub Login: @kendrahavens
    Microsoft Alias: tdykstra

**Comment by kendrahavens** [comment]
Thank you for filing feedback. The 'Don't Ask again' button on the left side of the notification should disable it from showing again.

![image](https://user-images.githubusercontent.com/8293542/71859456-d46df580-30a3-11ea-934c-9bdbe90bbc17.png)

Is this button not working for you? I'd be happy to open an issue on the product if the button is broken. Otherwise, I'm not sure if there is an option in Settings > Extensions > C# configuration that controls this. @JoeRobich

**Comment by DavidPrio** [comment]
@ARambazamba please see Kendra's comment above and contact her if any issues.
@CeciAc cc

**Comment by JoeRobich** [comment]
@DavidPrio This prompt is to generate launch.json and tasks.json files for the folder/workspace that you opened. If you choose 'Don't Ask Again', it will not ask for that folder/workspace again. If you would like to propose a new configuration option to suppress this prompt, then you can request one at https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!
