### ISSUE TITLE
SplashScreen and ApplicationInfo.VB

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#16392]
In Framework SplashScreen.VB gets it information from My.Application.Info and this is entered via VS under Properties/Application then a button called AssemplyInfo. This produces a class file called AssemblyInfo.VB. In Core the Application/AssemblyInfo is disabled and information is entered under Properties/Package but this information does not flow (at least at design time) to where Splash Screen expects it so you can't compile.

In the VS IDE all the information under Properties/Application and stored in Application.myapp creates Application.Designer.vb is missing. and if it is carried over from Framework you can't build your application. The setting that starts the startup screen is missing.
All this is a Breaking change

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8651cb33-a3f1-6af5-43cc-aa3e2e121f49
* Version Independent ID: 1f1f395f-0abc-8ef3-9a15-103315a1018a
* Content: [Breaking changes for WinForms - .NET Framework to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/winforms-breaking-changes?source=docs#feedback)
* Content Source: [docs/core/porting/winforms-breaking-changes.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/winforms-breaking-changes.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
@PriyaPurkayastha @Thraka Should this be documented as a breaking change?

**Comment by Thraka** [comment]
Is @OliaG still the PM for WinForms Core?

**Comment by paul1956** [comment]
@Thraka the form I showed is what Visual Studio and Winforms with Core 3.1 adds to a Core project and the comment in the form has instructions for setting the values those instructions don't work in Core. This is about a breaking change. If you just copy AssemblyInfo.vb from Framework (to get the values) that SpashScreen is looking for, you get errors about duplicate variable because in Core some of the items are somewhere else (another breaking change) and SplashScreen does not know how to find them. With proper documentation I think this could all be worked around but eventually SplashScreen for Core needs to be updated (separate issue) and that would be another breaking change.

**Comment by Thraka** [comment]
@paul1956 Can you provide more information about how you created the app? I cannot create vb.net core winforms apps in visual studio, only c# is provided in the templates. The same with the .net core templates in the Core CLI. Can you provide versions of visual studio and .net core?

**Comment by paul1956** [comment]
Start with Framework App use TryConvert (now works with VB) or manually convert project file. Once its a core app, add SplashScreen from Visual Studio 2019 Version 16.5.0 Preview 1.0, Menu if your app does not already have a SplashScreen. Ignoring the SplashScreen the way you get information about the has changed with Core. If I have an app that used AssemplyInfo.vb that has changed.
The code below is different between Core and Framework and it should be a breaking change.
```VB
My.Application.Info.Copyright
```

DotNet versions below.
```
  Microsoft.NETCore.App 5.0.0-alpha.1.19564.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-alpha.1.19625.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by paul1956** [comment]
This is partly fixed in current WinForms Master based on Core 5.0 with a new AssemplyInfo.vb but the way that class is populated has changed, some of the information like Title don't have a source what is enterable by a developer so the value it provides is not the same as Framework. I have entered a WinForm issue for this difference. I don't know when 5.0 comes out until then this is issue is a breaking change and the way/place you enter the information will always be a breaking change.

**Comment by Thraka** [comment]
@paul1956 Hi Paul. I'm back from vacation. I'll get to looking at this.

**Comment by Thraka** [comment]
@gewarren I think this should be noted on this page. However, it's (in a way) covered by https://docs.microsoft.com/en-us/dotnet/core/compatibility/visualbasic as that article details that the `Microsoft.VisualBasic.ApplicationServices` namespace is no longer available, which the splashscreen is designed to use. For VB.NET Windows Forms projects, they may be using the SplashScreen/About forms provided by the templates in Visual Studio. These use the `My` object model noted by the compatibility page I linked to.

@paul1956 There is a flag in the project file that will disable the auto assembly info generation and use an `assemblyinfo.vb` file instead. This is set by the **try-convert** tool with the `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` setting in the project file. But that doesn't solve the problem. The problem is that the splashscreen/aboutscreen templates use the VB.NET specific `My.Application` object which doesn't exist in .NET Core.

The windows forms templates for about/splashscreen in Visual Studio need to be updated for .NET Core.

/cc @KathleenDollard @OliaG

**Comment by paul1956** [comment]
@Thraka yes you can set the flag and you existing ApplicationInfo.vb will work with frozen values from FrameWork. In Core the most of the values you need are set in Package and will not flow to ApplicationInfo.vb. If you want to values in Package there needs to be documentation on how to get them. You could create a new ApplicationInfo.Vb, the file exists in current Master that gets most of the values. The only issue is Info.Title see above and https://github.com/dotnet/winforms/issues/2637

**Comment by Thraka** [comment]
Thank you for linking to that, it gives me a better picture of the overall state.

@gewarren I think this does warrant a breaking change update. Perhaps the content at https://docs.microsoft.com/en-us/dotnet/core/compatibility/visualbasic could be duplicated here but also mention that the `SplashScreen` and `About` forms provided by Visual Studio use these namespaces and the the `System.Reflection.Assembly.GetExecutingAssembly` method should be used to get the assembly information.

**Comment by gewarren** [comment]
@Thraka There's a specific template for breaking change issues. It's a process that Ron established with the product team. Usually someone from the product team fills out the [template](https://github.com/dotnet/docs/issues/new?template=doc-breaking-change.md). At that point, I can document it here. I'd then mark this issue as a dupe of that issue.

**Comment by Thraka** [comment]
@paul1956 @gewarren I filed #16655 to cover the breaking change aspect. I also included code that users can copy\paste over the code that was generated by the templates.

**Comment by paul1956** [comment]
I have commented there and will close this. Your solution will change again in Core 5.0 when a compatible AssemblyInfo comes back and the original code will work except for having a correct Title and covered https://github.com/dotnet/winforms/issues/2637.
