### ISSUE TITLE
Investigate steps for VS for Mac and VS Code

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#16391]
We’ve tested the article for Visual Studio. Need to check what would be needed to get IntelliSense for VS for Mac and VS Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b361b8e5-3b89-8e46-6356-ca420e468b69
* Version Independent ID: f66f7a1a-1ab7-dab7-696f-916950c4c518
* Content: [Install localized IntelliSense files](https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense#feedback)
* Content Source: [docs/core/install/localized-intellisense.md](https://github.com/dotnet/docs/blob/master/docs/core/install/localized-intellisense.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by kapsiR** [comment]
And please include the steps to disable it. 
I just got it automatically installed with a new C# project in VS Code. (I don't want localized IntelliSense!)

**Comment by mairaw** [comment]
@kapsiR just so I understand, you followed the steps in the article and then automatically got localized IntelliSense in VS Code?

**Comment by kapsiR** [comment]
@mairaw No. I opened a C# project with my VS Code installation, it installed a new version of Omnisharp in the background and from this time on, the fixes and hints were in the language of the OS. (VS Codes display language is `en` )
I'll try to reproduce and give you an update.
