### ISSUE TITLE
FDE - is this a `publish`-time feature or a `build`-time in .netcore 3.0?

### ISSUE THREAD

**Issue by Mikhail-msft** [dotnet/docs#16409]
This page is setup in a context of `application deployment`. However it appears that in .netcore 3.0 the exe is generated at build. It would be good to specify that starting from .netcore30 the exe is auto-generated on build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-executables-fde)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @Mikhail-msft. This page hasn't been updated for 3.0/3.1 yet. But we'll consider your comment when going through the updates, which should happen soon.

**Comment by Dean-NC** [comment]
I have the same question.  It's been another 2 months. When will you update this documentation?

**Comment by Thraka** [comment]
@Dean-NC I rewrote this article about half a month ago. I neglected to mention this. I'll do an update today about this. Building an app in 3.0+ always generates a runtime-dependent app, which may or may not include an executable. The executable generation is based on the `<apphost>` setting in the project (or passed on the command line)  which defaults to true for windows/linux and false for macos.
