### ISSUE TITLE
How to disable FDE generation for .netcore 3.0 application?

### ISSUE THREAD

**Issue by Mikhail-msft** [dotnet/docs#16407]
It's nice that FDE are now auto-generated. What `csproj` settings control the feature - how can we force disable FDE generation?
Is the a single place which describes all .netcore-specific msbuild settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/#feedback)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @Mikhail-msft. @KathleenDollard @dsplaisted @livarcocc is there a way to control deployment settings via MSBuild properties? I'm not aware of them.

In regards to having a single place that describes all .NET Corer specific MSBuild settings, we don't have that yet, but I think @gewarren will be able to start on this project this month. It's a high-pri backlog item for our team.

**Comment by dagood** [comment]
Happened to see this issue--this is answered over at https://github.com/dotnet/cli/issues/12716#issuecomment-535331850:

> Your app will still work as a FDD app. You can still run `dotnet program.dll`. The `program.exe` that is in the output can simply be ignored.
> 
> The type of app that gets built has not been changed.
> 
> If you don't want the exe generated because you don't want to pay the file cost for it, you can turn that off by setting `<UseAppHost>false</UseAppHost>`.

**Comment by mairaw** [comment]
Thanks @dagood. We'll add that info then in the MSBuild reference we're building and also to this article when we're reviewing it as part of the 3.0/3.1 updates.

**Comment by gewarren** [comment]
This has already been added to the [MSBuild property reference](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#useapphost) and to the [publishing overview article](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent).
