### ISSUE TITLE
Regarding the appveyor.yml

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16402]
Some small things I noticed about appveyor.yml (that might be wrong):

- It uses: `os: Visual Studio 2015` which is a bit old version.
- In the [*appveyor.yml* Reference](https://www.appveyor.com/docs/appveyor-yml/),  I see they use `image: ` instead of `os: `. I'm not sure if the usage of `os: ` was intended, or if it's something different than `image: `.
- There is a comment saying: `# so the `install` section is not required`, and after it, the `install: ` section is included in the file. That seems confusing.
- It seems that it uses .NET Core 1.0 (`  CLI_VERSION: 1.0.0-rc4-004771`) which is too old.
- The `  - ps: dotnet new console -lang f#` line catches my eye, why F# ?
- It seems that no builds related to appveyor are seen in PRs.

**Comment by gewarren** [comment]
This seems to be in reference to https://github.com/dotnet/docs/blob/master/appveyor.yml.

**Comment by Youssef1313** [comment]
> 
> 
> This seems to be in reference to https://github.com/dotnet/docs/blob/master/appveyor.yml.

Yes. That's the file I was referring to.

---

I found out that this file isn't actually used in CI system for this repo. But it's referenced in [this article](https://docs.microsoft.com/dotnet/core/tools/using-ci-with-cli#appveyor). So, it shouldn't be deleted. But both the appveyor.yml and the article need to be updated.
