### ISSUE TITLE
Possible intended duplicate example code

### ISSUE THREAD

**Issue by nicoleta-scrimint** [dotnet/docs#16417]
The second example for PerformLongRunningWork contains a lambda. Should it contain a local function instead?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92991e4f-6d00-9e10-9a0d-1058ba06457f
* Version Independent ID: e26cd6f8-ba2c-b8df-919f-4f1ecfd80864
* Content: [Local functions vs. lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/local-functions-vs-lambdas#feedback)
* Content Source: [docs/csharp/local-functions-vs-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/csharp/local-functions-vs-lambdas.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@nicoleta-scrimint I believe that this is a local function and not a lambda expression, but I'll let @BillWagner confirm.

```
async Task<string> longRunningWorkImplementation()
{
    var interimResult = await FirstWork(address);
    var secondResult = await SecondStep(index, name);
    return $"The results are {interimResult} and {secondResult}. Enjoy.";
}
```

**Comment by BillWagner** [comment]
Thanks for checking this @nicoleta-scrimint 

The previous comment by @gewarren is correct, that example is a local function.

I'll close this as answered.
