### ISSUE TITLE
Question: Translations

### ISSUE THREAD

**Issue by TheLifeGamingYT** [dotnet/docs#16429]
Hi .NET team,
First of all I’m deeply sorry for not using a template, but I couldn’t find one that fit with this type of issue. So I think you should add a template for questions I think, but this is up to you. So, back onto the topic, I remembered that it was possible to translate dotnet docs, but I can’t find anything that tells something about it, that’s why I’m asking here. I’m a native Italian speaker, and I often find errors in the automatic translation that can revolutionize totally the meaning of the article, so if you please can send here a link to where I can find such info, that would really help me, because I’d like to translate this docs.

Hope to hear back soon,
TheLifeGamingYT

**Comment by Youssef1313** [comment]
There is localized versions of the documentation. But I think all of them are automatically generated.
You can find the italian version [here](https://docs.microsoft.com/it-it/).

**Comment by TheLifeGamingYT** [comment]
I know, but I want to translate them manually to make it more correct

**Comment by Youssef1313** [comment]
Oh, I misunderstood and thought you want the link to the localized version. However, I don't know if it's available for the manual changes to localized articles.

/cc @JasonCard

**Comment by Youssef1313** [comment]
@TheLifeGamingYT , I'd like also to ask, what kind of improvements you'd like to make to the translated content ?

If it's some words that are translated, while it shouldn't be translated. This can be done in this repository. By using either back ticks if that word is a language keyword for example. Or using the no-loc syntax in other scenarios.

**Comment by TheLifeGamingYT** [comment]
As we all know, automatic translators aren’t perfect. That’s why I want to
translate better what is already translated by a computer.
-- 
Andrea Giurgola

**Comment by svick** [comment]
I believe you can submit improved translations of the Italian version of the docs by using Pull Requests on [the dotnet/docs.it-it repo](https://github.com/dotnet/docs.it-it).

**Comment by JasonCard** [comment]
Hi @TheLifeGamingYT, cc @Youssef1313, @svick, @gewarren 

Thank you for your question and interest to improve our translation.
We do encourage our customers to contribute toward improving our human-translated content by open PRs using the "Edit" button. However, we are currently discouraging customers from opening PRs on all machine-translated content (automatic translation). We use our human-translated content to train and improve the machine translation engine. So it would be best to focus our efforts on the human translated topics, which will have much greater impact and improve the overall quality of all translation. For that reason, we have currently turned off the "Edit" button for machine-translated content only.  
We are also working to improve the machine-translated content and if you have any general feedback for common issues (for example, over-localized terms) found in machine-translated content, then please feel free to open a GitHub Issue for the localized repositories (for example, [dotnet/docs.it-it repo](https://github.com/dotnet/docs.it-it)).
 
Kind regards, 

Microsoft DOCS Global Experience Team

**Comment by TheLifeGamingYT** [comment]
Hi Jason, thank you for your exhaustive answer. I actually have an idea for the translations: you should make a Crowdin, Transifex or something else, so you can choose what articles are available to translate and what not. I think it's a more efficient approach than the PR one.

**Comment by JasonCard** [comment]
@TheLifeGamingYT Thank you again for your suggestion. Making part of our content available for translation by public is a possibility we are considering for the future. I'll pass on your suggestion for consideration.

Kind regards,
Microsoft DOCS Global Experience Team

**Comment by Thraka** [comment]
I feel like this issue has been resolved. I'm going to close it. Thanks!

**Comment by JasonCard** [comment]
I agree, thank you for closing.
