### ISSUE TITLE
dotnet sln add .sqlproj - Invalid Project

### ISSUE THREAD

**Issue by whibdev** [dotnet/docs#16420]
## dotnet sln add .sqlproj - Invalid Project

When using cli to add a SQL Server Database Project (.sqlproj) to a solution, error occurs:
Invalid project `[PathToProject].sqlproj`. The imported project "C:\Program Files\dotnet\sdk\3.1.100\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.100\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.

### Version introduced
Using v3.1.100

### Old behavior
Unknown

### New behavior
1. Create solution:
dotnet new sln mysln
2. Open Solution in Visual Studio IDE
3. Add new Sql Server Database Project using IDE to solution
4. Remove SQL Server Database Project from Solution
5. Use dotnet cli command to add sqlproj back to solution

### Recommended action
- Possible workarounds
Add sqlproj using Visual Studio IDE

### Category
- ASP.NET Core
- dotnet cli

### Affected APIs
[dotnet sln cli](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)

 

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@whibdev Did this work in previous versions of .NET Core?
@PriyaPurkayastha Is this a breaking change?

**Comment by whibdev** [comment]
@gewarren I'm not sure if this was working in previous versions of .net core

**Comment by PriyaPurkayastha** [comment]
Adding @livarcocc to find out whether he has any information on this issue.

**Comment by mairaw** [comment]
I'm not sure the CLI supports sqlproj. @KathleenDollard?

**Comment by wbagdon** [comment]
Also seeing the same issue.
To add some more details, when running a `dotnet.exe restore` on a sln file that includes a `sqlproj` file we see the following:
```
Project.sqlproj : warning NU1503: Skipping restore for project 'Project.sqlproj'. The project file may be invalid or missing targets required for restore.
```

**Comment by wli3** [comment]
This issue was moved to dotnet/sdk#10683
