### ISSUE TITLE
"Local functions vs. lambda expressions" article isn't well-organized

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16426]
The article seems un-organized to me.

- There are no level-2 headings. The existence of h2 headings makes it easier to read through the article. It also has the benefit of the main titles being rendered in the side-bar.

- The article contains the following sentence:

&gt; Third, the compiler can perform static analysis that enables local functions to definitely assign captured variables in the enclosing scope. Consider this example:

"Third" of what ? Where is "Second" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92991e4f-6d00-9e10-9a0d-1058ba06457f
* Version Independent ID: e26cd6f8-ba2c-b8df-919f-4f1ecfd80864
* Content: [Local functions vs. lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/local-functions-vs-lambdas#feedback)
* Content Source: [docs/csharp/local-functions-vs-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/csharp/local-functions-vs-lambdas.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Those are good comments @Youssef1313 

Do you want to make these updates? If so, I'll assign this issue to you.

**Comment by Youssef1313** [comment]
> 
> 
> Those are good comments @Youssef1313
> 
> Do you want to make these updates? If so, I'll assign this issue to you.

Not sure if I can get time for it soon. I think it might be good as up-for-grabs ?

**Comment by jmarkman** [comment]
Hi @BillWagner, mind if I take a stab at updating this? It's been hangin' around for a few months and it looks like there's a bit of opportunity to fine-tune some language and clarify syntax so it's not just an open-and-shut issue.
