### ISSUE TITLE
Wrong metadata in article

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16428]
The title and description metadata for this article seems to be copied from <https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dfe2629-7f0f-5ab7-6bf3-af84b050c425
* Version Independent ID: 17533d4f-fae1-0883-8838-4ba7c0727bc7
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/upgrade-to-nullable-references)
* Content Source: [docs/csharp/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Youssef1313 

I've submitted a PR with the fix.
