### ISSUE TITLE
Wrong word 'not'?

### ISSUE THREAD

**Issue by JeroenBos** [dotnet/docs#16427]
Quote from above: "Whether the project is executable or not is determined by the &lt;OutputType&gt; property in the project file." 
Yet immediately afterwards an example is given showing that it _is_ determined by the &lt;OutputType&gt; (or at least suggested to be).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
The example is executable because the OutputType is Exe. So, you look at the OutputType value. Then, based on that value, you determine whether it's executable or not.

That means, if you found something like:

```xml
<OutputType>Library</OutputType>
```

then it's **not** executable. But, if you found:

```xml
<OutputType>Exe</OutputType>
```

then it **is** executable.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
