### ISSUE TITLE
This class doesn't exist

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/docs#16422]
There is an interface called IHttpClientFactory and a DefaultHttpClientFactory but as far as I can tell there is no concrete class called HttpClientFactory. If I'm wrong please point to the actual NuGet/repo where this class exists. I've looked high and low for it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#feedback)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by tdykstra** [comment]
@MelbourneDeveloper You're correct, the way this article is written is misleading. I'm flagging it as a doc bug for correction.
