### ISSUE TITLE
Do you assign values to variables or variables to values?

### ISSUE THREAD

**Issue by v-kydela** [dotnet/docs#16437]
This issue is more about general terminology than the specific topic of this document (nullability). There are a few places in this document where the term "assign" is used like a value is being assigned to a variable:

> The variable can never be assigned the value null.

> These variables may be initialized with the default null value and may be assigned the value null in other code.

> Nonnullable: Null can't be assigned to variables of this type.

> Nullable: Null can be assigned to variables of this type.

However, there are other places in this document where it's like a variable is being assigned to a value:

> A reference can be null. No warnings are issued when a reference type is initialized to null, or later assigned to null.

> Oblivious: This is the pre-C# 8.0 state. Variables of this type can be dereferenced or assigned without warnings.

> All reference variables may be assigned to null.

I believe the correct way to use the term "assign" is as though values are assigned to variables. Consider [this other document](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types):

> When you assign a new value to a variable of a value type, that value is copied. When you assign a new value to a variable of a reference type, the reference is copied, not the object itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I've opened #16441 to fix that.
