### ISSUE TITLE
Useless article

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16443]
I don't think this article has any useful information. Maybe this can be retired and deleted ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89020865-95e5-e769-c677-a731523be4f8
* Version Independent ID: 69fba3d1-977b-01ff-9b50-6448b45554af
* Content: [Visual Basic Breaking Changes in Visual Studio - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/breaking-changes-in-visual-studio)
* Content Source: [docs/visual-basic/getting-started/breaking-changes-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/breaking-changes-in-visual-studio.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
Yes, I believe this article should be retired.

**Comment by Youssef1313** [comment]
@gewarren, Thanks for confirmation. I've opened a PR that retires it.
