### ISSUE TITLE
Explicit parameter names

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#16459]
There is one more workaround: explicit parameter names:
c.f(i: 1, 1);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f339384-b880-c9f3-380e-671f2971c7b8
* Version Independent ID: 078eb117-40d7-32e6-4229-68e13d3ed3b6
* Content: [Compiler Error CS0121](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0121#feedback)
* Content Source: [docs/csharp/misc/cs0121.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0121.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Tested on try.net and worked.

![image](https://user-images.githubusercontent.com/31348972/71592302-658b1c80-2b38-11ea-9f3d-915146e73ae8.png)

I've opened a PR to add this workaround.
