### ISSUE TITLE
Code Brevity

### ISSUE THREAD

**Issue by MustakimAlamMoon** [dotnet/docs#16455]
In the first code example where the "ArrayExample" class exists, the code snippet has two "for" loops. I used only one "for" loops and ran this code in my Visual Studio 2019. I just put the "Console.WriteLine" method in the first "for" loop and got the same output. I don't know why this example contains two "for" loops. If the second "for" loop is not much necessary then you may shorten the existing code. Thank you...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f269de-137f-a763-a4e2-f2f5b1ce9dd3
* Version Independent ID: ad83c8b9-a95a-e336-ff31-52fb1fdb4b14
* Content: [C# Arrays - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/arrays)
* Content Source: [docs/csharp/tour-of-csharp/arrays.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@MustakimAlamMoon You're right, the second loop is not necessary. @BillWagner may have separated the assignment and print-out into separate loops for clarity, but I think they could be combined.

**Comment by MustakimAlamMoon** [comment]
Thank you so much for the clarification madam. You can close this issue now...
