### ISSUE TITLE
CLI code snippet language tag consistency

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#16462]
For some .NET CLI commands, the code snippet block is tagged `dotnet cli`. For others, especially those that contain a mixed of dotnet and generic commands, `console` or `bash` are used.

Examples:

[Console](https://review.docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line?branch=master#write-a-console-application-that-consumes-the-class-library) (scroll down a bit)
[Bash](https://review.docs.microsoft.com/en-us/dotnet/core/tutorials/libraries?branch=master#how-to-test-libraries-on-net-core)

**Comment by Youssef1313** [comment]
I remember this was discussed in one of @v-thpra PRs, and @mairaw suggested to use dotnetcli when the snippet contains only .NET Core CLI commands.

**Comment by Youssef1313** [comment]
![image](https://user-images.githubusercontent.com/31348972/71644946-64452580-2cd9-11ea-9d08-318da36303c5.png)

The "cd" command gets highlighted correctly even if it's not a dotnetcli command, so I think dotnetcli is suitable more than console or bash in the case of mixed commands.
@gewarren, Can I work on a PR that unify the usage of dotnetcli where possible ? or you'd like to wait for @mairaw ?

**Comment by gewarren** [comment]
> The "cd" command gets highlighted correctly even if it's not a dotnetcli command, so I think dotnetcli is suitable more than console or bash in the case of mixed commands.

Do you mean "even if it *is* a dotnetcli command"?

I'm in favor of labeling them all dotnetcli, so I think it's fine to create a PR, and we can wait for Maira's approval before merging it.

> Do you know if this is the repository of the library used for highlighting in docs.microsoft.com?

I'm not sure, but I will ask.

**Comment by scottaddie** [comment]
In the ASP.NET Core docs, we use the `dotnetcli` dev lang any time a .NET Core CLI command appears in a snippet. It's nice to have the syntax highlighting for a tool we own.

**Comment by Youssef1313** [comment]
> Do you mean "even if it _is_ a dotnetcli command"?

No, I meant that "cd" is a generic command, not a dotnetcli specific one. But it gets highlighted correctly. That's why I suggested to use dotnetcli in the case of "mixed" commands.

I'll open a PR soon.

**Comment by scottaddie** [comment]
I'm in agreement with what @Youssef1313 stated above.

**Comment by gewarren** [comment]
> Do you know if this is the repository of the library used for highlighting in docs.microsoft.com ?

Received an official answer of YES it is.
