### ISSUE TITLE
IHostedService document difference

### ISSUE THREAD

**Issue by sertunc** [dotnet/docs#16472]
Hi,
I noticed that when I researched the working logic of method IHostedService StartAsync. Why is there a difference between two documents ?

**First document**
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#ihostedservice-interface

StartAsync(CancellationToken) – StartAsync contains the logic to start the background task. StartAsync is **called before**:
The app's request processing pipeline is configured (Startup.Configure).
The server is started and IApplicationLifetime.ApplicationStarted is triggered.

**Second Document** 
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#the-ihostedservice-interface

Specifically, start is called **after** the server has started and IApplicationLifetime.ApplicationStarted is triggered.

So I'm confused which one is right, Thank you

**Comment by sughosneo** [comment]
Hi @sertunc, thank you for the feedback. We are in the process of updating the doc. You should see the changes shortly.
