### ISSUE TITLE
SDK backwards compatability

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet/docs#16481]
I'd expect dotnet core SDK 3 to be capable of building dotnet core 2.2 apps. This statement in #versioning-details seems to support my expectation: "Each version of the SDK can create applications for this runtime or any lower version." 

I have however discovered that the SDK cannot build older major versions. At least, not when using the docker image provided by MS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Core Runtime and SDK are versioned - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/#feedback)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/index.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @carlin-q-scott. @KathleenDollard @livarcocc @dsplaisted can you comment on this? Is this a product issue or a documentation bug?
AFAIK the latest SDK should be able to build for any lower target.

**Comment by dsplaisted** [comment]
@carlin-q-scott Yes, the latest SDK should be able to build apps targeting previous versions of .NET Core.  Can you file an issue with details about how it's failing?  If the issue is Docker-specific, I think the place to file an issue is here: https://github.com/dotnet/dotnet-docker/issues

**Comment by carlin-q-scott** [comment]
@dsplaisted Before I create a separate issue for the SDK, can you tell me if the older SDK or runtime is required to build the app targetting the older .NET Core version? 

I suspect the Docker image is not including the older runtime, and that may be the source of my issue.

**Comment by dsplaisted** [comment]
@carlin-q-scott You shouldn't need the older SDK.  The older runtime should not be required to build the app, but will generally be required to run the app.

**Comment by carlin-q-scott** [comment]
I've troubleshot the issue some more and it seems to be an issue with ASP.NET 2.2. It tried to find the 2.0.9 SDK for some reason while generating code, but throws an error saying it can only find the 3.1 SDK

**Comment by carlin-q-scott** [comment]
I found an issue tracking this for asp.netcore: https://github.com/dotnet/aspnetcore/issues/16816
