### ISSUE TITLE
Description about hiding columns in ML.NET documentation

### ISSUE THREAD

**Issue by antoniovs1029** [dotnet/docs#16486]
**Issue description**
While looking into old open issues in the [ML.NET repository](https://github.com/dotnet/machinelearning), I found a couple of issues where it's not clear if the users understand how ML.NET works when hiding columns (i.e. when having multiple columns with the same name). For instance, this particular issue is specifically about that problem:

https://github.com/dotnet/machinelearning/issues/4023

So I tried to look into the documentation of ML.NET to share them a link so they can read about it, but I couldn't find any documentation about it. The only place where I've seen the process of hiding columns being explained is here:
https://github.com/dotnet/machinelearning/blob/master/docs/code/IDataViewDesignPrinciples.md#transformers

But I think those docs there are not very visible, I believe they're not updated, and most importantly, they're not under [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/machine-learning/). And since hiding columns is a basic topic, and its done by many transforms by default, I believe it should be explained somewhere in the docs.

I wouldn't know if a whole new article would be necessary.

For instance, the user on issue 4023 I posted above, referred to this How-to guide, but didn't find answers there:
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/inspect-intermediate-data-ml-net

So perhaps changing the example in that guide so to include a transform that hides columns might be a good idea.

And/or perhaps adding a note or example showing how columns are hidden in this other article might also be helpful:
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work#data-models-and-schema

**Comment by luisquintanilla** [comment]
Thanks for the suggestion @antoniovs1029 . We've added this to our backlog.

**Comment by luisquintanilla** [comment]
AB#1660657

**Comment by luisquintanilla** [comment]
Reopening issue

**Comment by antoniovs1029** [comment]
Having this doc would also be useful to point [this user](https://github.com/dotnet/machinelearning/issues/5459#issuecomment-723391760) into why his outputSchema has got two columns of different type with the same name.
