### ISSUE TITLE
Update tutorials/using-on-macos.md for MSBuild/csproj

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#1648]
Getting started with .NET Core on macOS, using Visual Studio Code
* https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos
* https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md

xref https://github.com/dotnet/docs/issues/1574 (includes `dotnet new` commands)

**Comment by mairaw** [comment]
I'm thinking that this topic should later be broken into sections similar to what we did with the Visual Studio topics @BillWagner. What do you think? I can open a new issue for our backlog for that work.

**Comment by BillWagner** [comment]
@mairaw Yes, I agree. As part of updating the Getting Started topics, we should make them smaller and easier to consume.

**Comment by mairaw** [comment]
Ok, awesome. I'll open a new issue for the Getting Started experience!
