### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by 333fred** [dotnet/docs#16488]
The attributes section is missing `DoesNotReturn` and `DoesNotReturnIf`: https://source.dot.net/#System.Private.CoreLib/NullableAttributes.cs,4cd15111d8d6eed4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17290c4d-73f0-5ae1-e8ba-c039fe9fe9ca
* Version Independent ID: 59e0e3bb-b2e5-3ced-72d9-42e641b3897f
* Content: [Upgrade APIs for nullable reference types with attributes that define expectations for null values](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes)
* Content Source: [docs/csharp/nullable-attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @cartermp 

What are your thoughts here?

**Comment by cartermp** [comment]
It's definitely worth adding. These attributes are mostly handy in things like exception helpers.

**Comment by BillWagner** [comment]
I spent some time investigating what to do here. This is the tip of a larger gap in our coverage. None (or almost none) of the attributes that the compiler interprets and uses are in the language reference (other than the spec).

There is one page in the programming guide for [caller information](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/caller-information), and a page that covers [`AttributeUsage](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/attributeusage)

These are missing:
- `ConditionalAttribute`
- `ObsoleteAtribute`

And, all nullable attributes are missing.

I'll do the following:

- Add a new node in the "Language Reference" for attributes that are interpreted by the compiler. There will be three pages:

- A "general" page that covers `Conditional` and `Obsolete`, in addition to `AttributeUsage` (moved content)
- A "caller info" page that is basically a port of the existing caller info page.
- A nullable attribute page that takes the information from the existing page, including attributes added in this issue.

The existing pages will be removed, except for the nullable one. That will be trimmed, with a link to these new pages.
