### ISSUE TITLE
Mutually Recursive Functions and Tail recursion

### ISSUE THREAD

**Issue by oleksandr-bilyk** [dotnet/docs#16495]
In "Mutually Recursive Function" section (https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/recursive-functions-the-rec-keyword#mutually-recursive-functions)
You use sample:
let rec Even x = 
    if x = 0 then true 
    else Odd (x-1) 
and Odd x = 
    if x = 0 then false 
    else Even (x-1)

That sample is Mutually Recursive and it also looks like Tail Recursive because all functions in group last operation is calling function from group. 
But why F# in VS2019 in Debug mode doesn't recognize it as tail recursive? When I debug it I see that each call increases my call-stack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029d87c5-6502-8151-c903-dec53a570b0a
* Version Independent ID: 4aececf7-7876-3bc1-f722-1004b25fe05d
* Content: [Recursive Functions: The rec Keyword - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/recursive-functions-the-rec-keyword)
* Content Source: [docs/fsharp/language-reference/functions/recursive-functions-the-rec-keyword.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/functions/recursive-functions-the-rec-keyword.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by oleksandr-bilyk** [comment]
I think I have found the solution. I had to select "Generate tail calls" checkbox in project Build settings. You should mention about this in the article.
![image](https://user-images.githubusercontent.com/17872879/71664503-0f44f600-2d51-11ea-9b63-1c044e26f41e.png)

**Comment by cartermp** [comment]
@oleksandr-bilyk This is set by default when compiling in release mode. We don't turn on optmizations in debug with F# tooling because it can significantly impact tooling performance (builds are done in the background to populate IntelliSense) and debug time. For trivial code samples it ends up not mattering, but for larger codebases it does have an impact. I don't think we should recommend turning this on in the article because of that.

**Comment by oleksandr-bilyk** [comment]
@cartermp Tail recursion is enabled by "Generate tail call", not by "Optimize code" option. Optimization should not affect tail generation because optimization should not modify the logic. Anyway, thank you for reply.
