### ISSUE TITLE
"You can't declare readonly static members." is confusing

### ISSUE THREAD

**Issue by madelson** [dotnet/docs#16502]
This bullet makes sense in the context of the readonly members feature, but as a standalone phrase it is confusing because structs can definitly have static readonly fields, which in my understanding are also members (at least the Reflection API considers them to be members).

It might help to add (other than fields) to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly#feedback)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This was fixed in #16515 (This issue was not tagged at that time.)
