### ISSUE TITLE
Update Docker Images in the table to latest (3.1)

### ISSUE THREAD

**Issue by svemuri-dev** [dotnet/docs#16500]
Update Docker Images in the table to latest (3.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888b22d0-7261-c6fd-e4b3-07a4c1f66d06
* Version Independent ID: ddfcec03-a396-8851-49cd-629b9c7edc8a
* Content: [What OS to target with .NET containers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-container-os-targets#feedback)
* Content Source: [docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
The book is still covering .NET Core 2.2. @nishanil can comment whether there's a plan to update the entire book.

**Comment by nishanil** [comment]
Yes, there is a WIP PR to update the entire book. https://github.com/dotnet/docs/pull/16202

**Comment by nishanil** [comment]
The PR is merged. Closing this one.
