### ISSUE TITLE
Add .Net WebAssembly (Blazor) to the support table

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/docs#16509]
Should the .Net WebAssembly implementation be added to the ".NET implementation support" table?
AFAIK it supports .Net Standard up to version 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback. @terrajobst can you comment on this request?

**Comment by terrajobst** [comment]
@paolofulgoni 

The way to think about web asssembly is more similar to how think about x64/x86. Sure, there is a dedicated runtime (in the same way that there is a dedicated JIT/runtime for different CPU architectures) but we don't expose this a separate .NET implementation.

**Comment by paolofulgoni** [comment]
Thanks a lot for the explanation!
