### ISSUE TITLE
C# 8.0 readonly members vs. "Never use mutable structs as in"

### ISSUE THREAD

**Issue by zvizesna** [dotnet/docs#16510]
I think the documentation might contain conflicting or confusing statements about using mutable structs as in arguments.

The section [Declare readonly members when a struct can't be immutable
](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#declare-readonly-members-when-a-struct-cant-be-immutable) informs that:
> In C# 8.0 and later, when a struct type is mutable, you should declare members that don't cause mutation to be readonly.
> ...
> Adding the readonly modifier to members that don't mutate state provides two related benefits. First, the compiler enforces your intent. That member can't mutate the struct's state, nor can it access a member that isn't also marked readonly. Second, **the compiler won't create defensive copies of in parameters when accessing a readonly member**. The compiler can make this optimization safely because it guarantees that the struct is not modified by a readonly member.

However, the section [Never use mutable structs as in in argument](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#never-use-mutable-structs-as-in-in-argument) then says the following:
> The techniques described above explain how to avoid copies by returning references and passing values by reference. These techniques work best when the argument types are declared as readonly struct types. Otherwise, the compiler must create defensive copies in many situations to enforce the readonly-ness of any arguments.
> ...
> On first examination, you may have thought these accesses were safe. After all, a get accessor shouldn't modify the state of the object. **But there's no language rule that enforces that. It's only a common convention.** Any type could implement a get accessor that modified the internal state. **Without some language guarantee, the compiler must create a temporary copy of the argument before calling any member.**

From my point of view, the reader could be confused about whether or not the defensive copies are made, and what the best practice is. Moreover, the _Never use mutable structs as in in argument_ section references the `Point3D` definition, which has already been enhanced with `readonly` modifiers in the previous section.

Also, the latter section mentions that
> You shouldn't pass a nullable value type as an in argument. The Nullable\<T\> type isn't declared as a read-only struct.

I would like to ask if there have been any changes to this behavior with C# 8.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#declare-readonly-members-when-a-struct-cant-be-immutable)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by DaseinPhaos** [comment]
In addition, the generated IL suggests that when directly accessing member fields, the compiler won't generated defensive copies.

Defensive copys are only generated when you're trying to access a property/method from the struct, see the sharplib example:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQhGOSABNhTgOyEDehZTFAzGQM4AuUArmJ2QAKEAJYA7TiwAi9RswxsAJhB7AANjDIANANxymCsstUayATT0FmrIyvWaAWpevX9N4/bIBxGJy10yAHNfMgCMam0dAF8owjcScg9TKRF2ACEATwAxERg1RQAKcSFRCWkyAAdSzhwAGjJi4XFJKUrqrABKNwYrFyYkzQQUgDNhmFgxME0AXjbmnAA6LTI4OYksJec+2xNNDJGxiamyWar5hbMVtc4NizdrAbIALwPxmEmZ68WHK7P1haccV6fXCZAAsgBDTgACwWAGUAI5QTgFIYiUZvD5kABUZDRGKOmgA1GR9ujDu9jriyQTKcTnq9CTiGeTMVMOlsmLFgS54qQdp4UukMoIoBAKuNOBkimISs1yn8avVGtUFe0ujyetsBaZ8RSsadqosfH5fu1NvdmI8afrjobzpdVorbpyXI8XqymfaJN8zc0NoCiDzrKDITD4UiUXq2ZpcdGmSSbTHmUmEyzaVjcR6M+zXdz80A===

I think the documentation should be clearer on this behavior as well. The "Never" part seems to be too strong a statement.
