### ISSUE TITLE
PackageIconUrl

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/docs#16514]
What is there no deprecation mentioning about PackageIconUrl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#feedback)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
Thanks for your feedback @kwaazaar.

@karann-msft @nkolev92 can you comment on this issue and what is the replacement for PackageIconUrl? 
There are a few other articles that also talk about this property:
https://github.com/dotnet/docs/search?q=PackageIconUrl&unscoped_q=PackageIconUrl

**Comment by karann-msft** [comment]
PackageIconUrl is being deprecated in favor of PackageIcon - https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl

PackageLicenseUrl is being deprecated in favor of PackageLicenseFile and PackageLicenseExpression - https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
