### ISSUE TITLE
First Example Precision

### ISSUE THREAD

**Issue by BLMeltdown** [dotnet/docs#16511]
using System;
using System.Threading;
using System.Threading.Tasks;

public class Example
{
   public static void Main()
   {
      Thread.CurrentThread.Name = "Main";

      // Define and run the task.
      Task taskA = Task.Run( () =&gt; Console.WriteLine("Hello from taskA."));

      // Output a message from the calling thread.
      Console.WriteLine("Hello from thread '{0}'.", 
                          Thread.CurrentThread.Name);
      taskA.Wait();
   }
}
// The example displays output like the following:
//       Hello from thread 'Main'.
//       Hello from taskA.

&gt;&gt; this is inexact, actually, the messages in Console may be in any order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050b2b8a-8b8d-c2de-f03d-b2ebb26a9c95
* Version Independent ID: 7d23f296-9a5e-ca0a-08c3-f718d0a90d94
* Content: [Task-based asynchronous programming - .NET](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming#feedback)
* Content Source: [docs/standard/parallel-programming/task-based-asynchronous-programming.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-based-asynchronous-programming.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The comment says:  "// The example displays output **like** the following:"
