### ISSUE TITLE
Break down the VS Code tutorial into several topics

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1651]
Topic: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos

There's also this topic on a similar subject:
https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-code

We should follow a similar pattern we did for the VS topics: https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Tutorial: Create a .NET Core solution in macOS using Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Fixed by #18701
