### ISSUE TITLE
Cost

### ISSUE THREAD

**Issue by wwy12321** [dotnet/docs#16523]
So the memory cost is 1 bit or what.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfcc3e5e-dc3b-433d-71d8-e92c462e1b02
* Version Independent ID: 80e8f0fc-4d4c-925f-0f1f-2038a5a3c24d
* Content: [bool type - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/bool#feedback)
* Content Source: [docs/csharp/language-reference/builtin-types/bool.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/bool.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I don't think that any data type can take memory of "bits", Any data type will always be a byte and multiple of bytes. Referring to the table in [sizeof operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/sizeof) article, It says that bool takes **one byte**.

**Comment by BillWagner** [comment]
As @Youssef1313 states, the `sizeof` operator will give the correct answer here. We won't update this article, because the memory storage can depend on the natural boundaries for the machine CPU, and can be manipulated with some attributes.

Closing as answered.
