### ISSUE TITLE
Creating a docker image using examples outputs error

### ISSUE THREAD

**Issue by brunomartinspro** [dotnet/docs#16520]
Creating a .net core app 2.2 using the latest version of visual studio, publishing it, creating a dockerfile and building and running it with the documentation examples gives the error:

```powershell
> docker run -it --rm dotnettest
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

Structure:
- app
   - dll
   - etc
- Dockerfile

Publish:
```powershell
dotnet publish -c Release
```

Dockerfile:
```dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:2.2

COPY app/ app/

ENTRYPOINT ["dotnet", "app/dotnetdocker.dll"]
```

Docker Build output:
```powershell
> docker build -t dotnettest .

Sending build context to Docker daemon  253.4kB
Step 1/3 : FROM mcr.microsoft.com/dotnet/core/runtime:2.2

2.2: Pulling from dotnet/core/runtime
aeef11c1b4a6: Pull complete
23fe2f038b8c: Pull complete
387742226d59: Pull complete
e0a2ea1e070c: Pull complete
4d87f9f02f57: Pull complete
3c66e7836469: Pull complete
Digest: sha256:51f94ecc723ee098a03d84e10bd9d871fc4b817736c63362854c3c8bfad6e498
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/runtime:2.2
 ---> 6c8e89ae9506
Step 2/3 : COPY app/ app/
 ---> 3435379caf06
Step 3/3 : ENTRYPOINT ["dotnet", "app/dotnetdocker.dll"]
 ---> Running in 7ce2007a1ae0
Removing intermediate container 7ce2007a1ae0
 ---> b35900c7bbb8
Successfully built b35900c7bbb8
Successfully tagged dotnettest:latest
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container#feedback)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by brunomartinspro** [comment]
The documentation on step [Create The Dockerfile](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container#create-the-dockerfile) specified:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:2.2
```
But when looking into the [docker documentation](https://docs.docker.com/engine/examples/dotnetcore/) i managed to get it running by using:
```dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
```

Which of these options is the correct one?
Shouldn't the runtime be enough to run a dotnet core app?

**Comment by Thraka** [comment]
If you created an ASP.NET Core app you need **aspnet**. If you created a .NET Core app the **runtime** value is sufficient.

What does your .csproj say it's SDK value is? (its the first line in the file)

**Comment by brunomartinspro** [comment]
@Thraka this is the csproj, so if i understand correctly when creating a web project (ASP.NET Core) you can't use the runtime.
```powershell
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  </ItemGroup>

</Project>

```

**Comment by Thraka** [comment]
@brunomartinspro Perhaps I should update the tutorial to have a link in the introduction to the ASP.NET Core doc's tutorial? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1

Does that cover your scenario?
