### ISSUE TITLE
Where MakeConstTestProject is used

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16537]
Is https://github.com/dotnet/samples/tree/master/csharp/roslyn-sdk/Tutorials/MakeConstTestProject used anywhere or it can be deleted ?

/cc @BillWagner

**Comment by Youssef1313** [comment]
Also, have a look at this one too (<https://github.com/dotnet/samples/tree/master/framework/libraries/pcl-library>).
It seems it's not referenced anywhere, and it has a compile error.

![image](https://user-images.githubusercontent.com/31348972/71782916-4aad2200-2fe8-11ea-8ecf-3af97a01575e.png)


TargetFramework value isn't recognized

**Comment by BillWagner** [comment]
I know that the "Make Const test project" should stay. While the code isn't displayed in the article, it is discussed in the tutorial that builds the MakeConst refactoring.

I'm not sure about the PCL one. We'll look at that as we finish getting the build system in place.
