### ISSUE TITLE
whats-new samples are scattered in two different directories

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16538]
For .NET Core 3.0: <https://github.com/dotnet/samples/tree/master/snippets/core/whats-new/>
For .NET Core 2.1: <https://github.com/dotnet/samples/tree/master/core/whats-new/>

It's better to have both of them in one directory.

**Comment by BillWagner** [comment]
Thanks for noting this @Youssef1313 
We agree, and we'll get to that later this quarter.

**Comment by Youssef1313** [comment]
#please-review

**Comment by Youssef1313** [comment]
> 
> 
> #please-review

This was a test related to https://github.com/dotnet/docs/pull/16378#issuecomment-575538391
Wanted to see if that rule was set to issues instead of PRs by mistake. But seems that it doesn't work at all.

**Comment by Youssef1313** [comment]
@BillWagner, which directory do you prefer? I can work on this if you want.
