### ISSUE TITLE
Renaming a copied Public class CHANGES original Class to NEW name. in Blend Visual Studio 2019

### ISSUE THREAD

**Issue by MJackson9595** [dotnet/docs#16539]
I copied one public class then repasted it in same folder and global namespace.

expected this error.  to show BEFORE I renamed the public class I copied to a different name.

WHAT I did NOT expect was Visual Studio 2019  to HELP by changing BOTH the public class and name of the member StartProgram () in the Original class to match the renamed class.

Blend for visual studios 2019 seems to be determined to change EVERY occurrence of a global namespace and member of that namespace to whatever I changed the COPIED names to.  Unable to find any way to tell Visual Studio blend 2019 to in this case do NOT change every occurrence of name in the project.   It is a great feature, when you realize you have just come up with a much better "name" then the one you  have been using so far.  But that is not the case here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62919633-6041-2d18-0b0c-ff1c8e690495
* Version Independent ID: 19a252b9-f0d8-ec57-1014-00ad6e5de9b3
* Content: [Compiler Error CS0101](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0101#feedback)
* Content Source: [docs/csharp/misc/cs0101.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0101.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Issue moved to [dotnet/roslyn #40779](https://github.com/dotnet/roslyn/issues/40779) via [**ZenHub**](https://www.zenhub.com/)
