### ISSUE TITLE
Compile error in a sample

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16536]
The sample in https://github.com/dotnet/samples/blob/master/core/json/Program.cs has a compile error.

![image](https://user-images.githubusercontent.com/31348972/71779681-e32fac00-2fc0-11ea-817a-486462dafc55.png)

I think it was put recently in the samples repository, but not yet consumed in any articles.

See https://github.com/dotnet/corefx/pull/38928 For more information.

I'm wondering if the sample should even be completely deleted as it's not used ?

/cc @ahsonkhan

**Comment by BillWagner** [comment]
ping @tdykstra Can you look at this?

**Comment by tdykstra** [comment]
It's old code that was broken by an API change.  I'm not sure how best to fix it to use the current API, @ahsonkhan would know. When it does get fixed I'll incorporate the code into one of the System.Text.Json docs, so I'm not sure this needs to stay in the samples folder.

**Comment by ahsonkhan** [comment]
I can take a look at fixing the sample, some time this week.

**Comment by Youssef1313** [comment]
@ahsonkhan, I've tried to fix it, it compiled successfully but threw an exception.

https://github.com/Youssef1313/samples/commit/f9f0895dd6c6792576dff99af71a8ae3aafe5fa2

![image](https://user-images.githubusercontent.com/31348972/71884687-74c62780-3141-11ea-8871-c9c3c20d8910.png)

Is it a known issue currently with System.Text.Json ?

I also suggest to put the project in a cs or csharp sub directory when you work on that issue. That will allow to easily add a vb sample later.

**Comment by Youssef1313** [comment]
> When it does get fixed I'll incorporate the code into one of the System.Text.Json docs, so I'm not sure this needs to stay in the samples folder.

This part of the issue is still not addressed I think.

The sample isn't consumed in any articles. It'll need to be moved from dotnet/samples to this repo and added to one of the System.Text.Json articles.
