### ISSUE TITLE
Ukrainian localization for docs repo

### ISSUE THREAD

**Issue by v-tsymbalistyi** [dotnet/docs#16540]
Hello!

Is there Ukrainian localization for docs repo? I couldn't find a relevant repository. 
If there is none, how can it get created? I would like to contribute to that once in a while. And I might be able to find some people to help me with this.)

**Comment by Youssef1313** [comment]
I've searched and didn't find an Ukrainian version.

---

>  If there is none, how can it get created? I would like to contribute to that once in a while. And I might be able to find some people to help me with this.)

I think @JasonCard may answer this.

**Comment by JasonCard** [comment]
Hi @v-tsymbalistyi, cc @Youssef1313, 

Thank you for your question and interest to contribute to our Docs translation.
Unfortunately, we currently do not localize .NET Docs into Ukrainian and do not have plans to do so. 
Our content is also currently not available for translation by public, but it's a possibility we are considering for the future. I'll pass on your suggestion for consideration.

Kind regards,
Microsoft DOCS Global Experience Team

**Comment by v-tsymbalistyi** [comment]
@JasonCard thank you.

I am a bit surprised that I can contribute code, docs but not the translation.
Also, I hope you'll reconsider adding Ukrainian. 

I can see that it might be difficult for you to verify the quality if you don't have native speakers in the stuff. But people who bother submitting translation will not usually commit rubbish and simple google translation should give you a pretty good idea about the content in general. 

Maybe it makes sense to give it a try on one of the missing languages? You could share with the publicity your general policies about the translation and maybe three to five public reviews would produce good enough quality. English original will always be available. And a way to correct mistakes as well.

Also, it would be a good way for people to learn and explore dotnet and make it available to the broader community. I know a lot of people who would like to learn to program but are unable to do so because documentation in their language is very limited. And it is true for all the technologies and platforms. So this way dotnet can be the only (and the best I hope) choice for people to enter the software development world.

**Comment by JasonCard** [comment]
@v-tsymbalistyi Thank you again for further input on this topic. We do encourage community contribution to improve our existing translation by opening GitHub PR using the "Edit" button. We have a team to review those PRs by linguistic moderators. However, resources are limited, and it's not an efficient process for major translation work. So unfortunately this current process is not supported for Ukrainian.
We do see the benefit of open-source localization and we hope to make this possible in the future. That would also make it easier to add more languages including Ukrainian.

Kind regards,
Microsoft DOCS Global Experience Team

**Comment by v-tsymbalistyi** [comment]
@JasonCard Thank you for considering it.
It would be great.

**Comment by podarok** [comment]
We have a team of translators for the Drupal.
If you need help, let us know

**Comment by JasonCard** [comment]
@podarok Thank you, that's good to know.
