### ISSUE TITLE
@ $ Is invalid

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#16552]
**The comment below was machine-translated**

@dsaewq321 commented on [Mon Jan 06 2020](https://github.com/dotnet/docs.zh-cn/issues/518)

Regarding "$ @" ... "and @ $" ... "are valid interpolated verbatim strings." Among them, @ $ is invalid. Although I saw someone write this, I will get an error when I pull it down Up:
-Error CS8401 To use "@ $" instead of "$ @" for interpolated verbatim strings, use language version 8.0 or later.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5e3c4c67-250d-50ac-35e7-b11a20d13ba0
* Version Independent ID: 2dab9569-8748-1325-d9b7-78c3f728deef
* Content: [C# 中的字符串内插](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/string-interpolation#feedback)
* Content Source: [docs/csharp/tutorials/string-interpolation.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/string-interpolation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

---

@imba-tjd commented on [Mon Jan 06 2020](https://github.com/dotnet/docs.zh-cn/issues/518#issuecomment-570992084)

你还必须证明你用的是8.0，否则你的无效是无效的

---

@srvbpigh commented on [Mon Jan 06 2020](https://github.com/dotnet/docs.zh-cn/issues/518#issuecomment-570993495)

Hello, @dsaewq321
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by pkulikov** [comment]
I don't know how it's translated, but the English version of the article specifies that the token order is not important starting with C# 8.0.

**Comment by BillWagner** [comment]
Thanks for forwarding this @CeciAc 

As @pkulikov points out, either order is valid starting with C# 8.0

I'll close this as by-design.
