### ISSUE TITLE
Good but a little unclear

### ISSUE THREAD

**Issue by savaged** [dotnet/docs#16569]
A really helpful guide, however it's not clear whether one needs to install the sdk and then the runtime. Are both required or just one?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1804#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for the feedback. When we get to updating this soon, I'll put a sentence in each that describes that the sdk = developing+running apps and the runtime = running apps.
