### ISSUE TITLE
I never heard of fibonacci numbers; should be explained better

### ISSUE THREAD

**Issue by AnotherBlob** [dotnet/docs#16567]
Wikipedia and this tutorial don't give a good explanation on how fibonacci numbers work but after writing down random numbers and using this method in pratice made me realize that you could explain it in a way that's very easy to follow.
"You start off with 3 values. The first two values are 0 and 1. You'll need to add them together to make the third value.
Scroll the numbers upwards now so that the first value has the second number, the second value has the third number and the third value has the new first value + the new second value added together. Repeat until you have 20 results for the third value."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Data collections - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Some consider that it starts with 0 1 and some consider it starts with 1 1.
In the article, it's said that it starts with 1 1

> The Fibonacci Sequence, a sequence of numbers, starts with two 1s. Each next Fibonacci number is found by taking the sum of the previous two numbers.

**Comment by BillWagner** [comment]
Thanks for writing this @AnotherBlob 

As @Youssef1313 says, the Fibonacci sequence is defined in the article. I'll close this as provided.
