### ISSUE TITLE
Should be updated to indicate that only ASP.NET Core 2.1 is still supported on .NET Framework

### ISSUE THREAD

**Issue by Pilchie** [dotnet/docs#16571]
This page should be updated to mention that ASP.NET Core 2.1 is supported on .NET Framework, but later versions are either out of support  (2.2), or don't support .NET Framework, and won't in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie can you help address this issue? I think you'd know better the language we're using for this scenario.

**Comment by scottaddie** [comment]
Where possible, we should probably direct customers to the [.NET Core support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) in the docs. That will allow us to keep our docs generic.

**Comment by Rick-Anderson** [comment]
@scottaddie  I'll do that in the update.
