### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by adamny** [dotnet/docs#16579]
[Enter feedback here]

I installed Visual Studio 2019 for Mac (community edition) and followed these steps to create a project.  However, clicking the "Create" button doesn't do anything (it appears unclickable). 
("Cancel" and "Previous" buttons work.) 
I installed Visual Studio twice and both times have this problem.
What do go wrong?

<img width="906" alt="Screen Shot 2020-01-07 at 2 50 34 PM" src="https://user-images.githubusercontent.com/50718721/71924675-74d42080-315d-11ea-9ca5-2c63d491dee0.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f959274-7022-54cc-fc9e-bbc29ab007d7
* Version Independent ID: df72aa8e-42b8-0a76-5dbb-f78707fee65a
* Content: [Get started with .NET Core using Visual Studio for Mac - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs#feedback)
* Content Source: [docs/core/tutorials/using-on-mac-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
Thanks for your feedback @adamny. Given this is a product issue you're having and not a problem with our documentation, please report it using the appropriate channel: https://developercommunity.visualstudio.com/content/problem/post.html?space=41
