### ISSUE TITLE
"l" standard date/time format?

### ISSUE THREAD

**Issue by IGx89** [dotnet/docs#16578]
Under the "Custom support" section it says "one of the "R", "l", "O", or "G" standard date and time format strings". I found every one except "l" (lowercase L) in the link it references (https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings). I'm wondering if that's a typo, or if it's missing from the standard format strings document and should be documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41b02f-8fe9-44a1-544f-b6016f1ff4b3
* Version Independent ID: 77358796-3ee2-9b86-7e0a-92c60ebc371a
* Content: [DateTime and DateTimeOffset support in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#custom-support-for--and-)
* Content Source: [docs/standard/datetime/system-text-json-support.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/system-text-json-support.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @layomia
* Microsoft Alias: **laakinri**

**Comment by layomia** [comment]
@tannergooding , @tarekgh it seems that the ["l" format](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Date.cs#L27)  used by the Utf8Parser/Formatter is not a documented [standard format specifier](https://docs.microsoft.com/dotnet/standard/base-types/standard-date-and-time-format-strings), but a convenient way to use lowercase'd RFC 1123 strings. Should the format be formally documented and supported with other DateTime(Offset) processing types, e.g [`System.DateTime`](https://dotnetfiddle.net/2A2wGH)?

The alternative is for the [JSON DateTime doc](https://docs.microsoft.com/dotnet/standard/datetime/system-text-json-support#using--and-) and the [Utf8Parser/Formatter docs](https://docs.microsoft.com/dotnet/api/system.buffers.text.utf8parser.tryparse?view=netcore-3.1#System_Buffers_Text_Utf8Parser_TryParse_System_ReadOnlySpan_System_Byte__System_DateTimeOffset__System_Int32__System_Char_) to note that the "l" format is recognized only by the Utf8Parser/Formatter types.

**Comment by tarekgh** [comment]
> Should the format be formally documented and supported with other DateTime(Offset) processing types, e.g System.DateTime?

The documentation should clarify this format is supported only for Utf8Parser. In the future, we can support the format with DateTime/Offset but I am not seeing any needed rush for doing that.
