### ISSUE TITLE
Update samples to use solution-based project

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#16582]
update article to use the new sample location and add the same for VB as well:
dotnet/samples#1867

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2fd1ea-abfe-ada0-ce7b-1d7f50819c18
* Version Independent ID: 4d918f89-02f2-dbf6-a701-c2efe9eb9a7d
* Content: [Consume a .NET Standard library in Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/consuming-library-with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/consuming-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/consuming-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment]
I'm closing this, as we decided this is not the direction we're taking the samples.

**Comment by BillWagner** [comment]
I misread this, reopening
