### ISSUE TITLE
Default interface methods page is not up to date

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/docs#16597]
The status on top of the page is not up to date.
Should it be removed?
Also, since the feature was actually released, there could be a link to the related page: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#default-interface-methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17012c83-0313-919b-eb8b-04fae8f4df4a
* Version Independent ID: 05252e5a-e53c-5ce5-84b3-671faad0549c
* Content: [Default interface methods - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods)
* Content Source: [proposals/csharp-8.0/default-interface-methods.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @paolofulgoni 

This page is correct. The language reflects the difference between "shipping a feature" and "updating the standard".

You are correct that default interface members shipped with C# 8.0, and is available.

We use the term "proposal" here to reflect that these features are proposed for the ECMA C# standard, but have not yet been incorporated into the standard. The standards committee will be working to update the standard using the reference implementation Microsoft provided in C# 8.

This distinction is explained [here](https://docs.microsoft.com/dotnet/csharp/language-reference/).

I'll close this as the docs accurately reflect the standardization process.

**Comment by paolofulgoni** [comment]
Thanks for the detailed answer.

I was a little confused by this:
![image](https://user-images.githubusercontent.com/5703017/72088270-1dbf7e80-330a-11ea-8588-6b879b555759.png)

But now I understood it's about the standard, not the reference implementation.
