### ISSUE TITLE
Code translation to F#

### ISSUE THREAD

**Issue by sunitjoshi** [dotnet/docs#16593]
Would translation to F# be pretty straightforward?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @sunitjoshi,

Thanks for your question. The short answer is yes. You can see this sample from the [dotnet/machinelearning-samples repo](https://github.com/dotnet/machinelearning-samples/blob/master/samples/fsharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.fs). Although the sample is not specific to the tutorial, it shows what the F# syntax would look like.
