### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#16602]
Better names , meaningful names of items (properties, methods, events) would promote good programming habits for new developers, they see these names and must think this is okay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec67c37-012f-17cc-f53d-cf9db2784e69
* Version Independent ID: f6f3bc0f-f768-71a0-ddba-79477edf6997
* Content: [Creating and Implementing Interfaces - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/interfaces/walkthrough-creating-and-implementing-interfaces)
* Content Source: [docs/visual-basic/programming-guide/language-features/interfaces/walkthrough-creating-and-implementing-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/interfaces/walkthrough-creating-and-implementing-interfaces.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
Yes, agreed. This would be a good improvement.
