### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#16600]
The download link goes to the landing page for code samples, not for the associated project download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd4de30-625f-5f9f-3217-48f40caf725a
* Version Independent ID: 8cd0c08d-fe9d-ebb3-0aa0-07651578e13a
* Content: [Cancel Async Tasks after a Period of Time - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time)
* Content Source: [docs/visual-basic/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
Thanks for reporting this. We'll get it fixed.

**Comment by gewarren** [comment]
I'm not exactly sure where the sample lives now. This one is not correct: https://docs.microsoft.com/samples/dotnet/samples/async-and-await-vb/

**Comment by mairaw** [comment]
I don't think this one has been migrated to samples browser yet. It's archived here:
https://github.com/microsoftarchive/msdn-code-gallery-community-a-c/tree/master/Async%20Sample%20%20Fine%20Tuning%20Your%20Application%20(C%23%20and%20Visual%20Basic)
