### ISSUE TITLE
Control names

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#16601]
Rather than Button1 and Button2 e.g. StartButton or ButtonStart or btnStart. I see developers on various forums using default control names and when they get stuck with tons of controls, well its hard to figure out and I think promoting good naming of controls will go along way in the devs future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543b0ddd-a641-0cb9-6285-81399497d237
* Version Independent ID: 11c815f5-7fd2-8a4f-f2f9-02848a2e3d8d
* Content: [Declaring and Raising Events - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/events/walkthrough-declaring-and-raising-events)
* Content Source: [docs/visual-basic/programming-guide/language-features/events/walkthrough-declaring-and-raising-events.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/events/walkthrough-declaring-and-raising-events.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
Good idea!
