### ISSUE TITLE
Runtime Requirement

### ISSUE THREAD

**Issue by AnanthaSubramanian** [dotnet/docs#16619]
Could you please document if there are runtime available and what runtime is required for successful compilation of analyzer source code. This I am asking from perspective of what is required on build server for building the source code as nuget package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bd716a-906d-983b-141c-4a4e2e2a79ec
* Version Independent ID: debed50c-98ce-ec0e-bcf6-0170a4e60fcc
* Content: [The .NET Compiler Platform SDK (Roslyn APIs)](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/)
* Content Source: [docs/csharp/roslyn-sdk/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @AnanthaSubramanian 

I think we have some of the information you're seeking, but I'd like some clarification on where you need more references:

Is it to build (compile / package) an analyzer in your CI system?
Is it to create a NuGet package for your analyzer?
Is it to run analyzers delivered as NuGet packages as part of your CI build for other applications? 

Let me know which you're seeking, and I'll add more pointers.

**Comment by AnanthaSubramanian** [comment]
Build an analyzer in CI system.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BillWagner** [comment]
@AnanthaSubramanian 

The [Microsoft.CodeAnalysis](https://www.nuget.org/packages/Microsoft.CodeAnalysis/3.5.0-beta2-final) contains everything you should need to build an analyzer in your CI system.

I hope that helps.

I'll close this as answered.
