### ISSUE TITLE
More courses about Domain-Driven Design

### ISSUE THREAD

**Issue by KarenTazayan** [dotnet/docs#16621]
There are some great courses in Pluralsight by Vladimir Khorikov.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f07c375-8e96-f4ab-e8d6-30c3553ecb85
* Version Independent ID: 421277e8-7085-809b-9e13-1061008470d8
* Content: [Tackling Business Complexity in a Microservice with DDD and CQRS Patterns](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/?source=docs#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by scottaddie** [comment]
@nishanil I assume DDD will receive some coverage in the proposed Microsoft Learn learning path for microservices. Thoughts?

@KarenTazayan Is there specific DDD content that you hope to see? In the meantime, I also recommend the Pluralsight DDD course from @julielerman.

**Comment by KarenTazayan** [comment]
@scottaddie yes, [Domain-Driven Design in Practice
by Vladimir Khorikov](https://app.pluralsight.com/library/courses/domain-driven-design-in-practice/table-of-contents).

**Comment by nishanil** [comment]
@scottaddie Yes, that's the plan.
