### ISSUE TITLE
Missing C# 8 documentation

### ISSUE THREAD

**Issue by powerlord** [dotnet/docs#16634]
C# 8 adds an additional return type: IAsyncEnumerable&lt;T&gt; as long as you're using yield return instead of just return.

See the "What's new in C# 8" documentation under Asynchronous Streams: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async Return Types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for pointing this out @powerlord 

I've added this to our next sprint, as we continue to update our content for all the C# 8 features.
