### ISSUE TITLE
Clarification asked

### ISSUE THREAD

**Issue by lpedromachado** [dotnet/docs#16645]
Please clarify this sentence:
"You have everything ready for breakfast at the same time except the toast."

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/pt-pt/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Can you add a bit more context to your question @lpedromachado? I'm not sure what needs clarification here.

**Comment by lpedromachado** [comment]
@BillWagner: Well, I don't understand why one has everything ready except the toast, since one has also to wait for the eggs and the bacon to fry. We don't know _a priori_ by which order the three items become ready.

**Comment by tsigdel-idc** [comment]
![9636toronto-flag 2](https://user-images.githubusercontent.com/13853828/72585416-052c0700-38bc-11ea-9451-4ee0f01b9586.jpg)

**Comment by xenophilios** [comment]
It seems that at this point in the text, the toast is ready before the juice, which is ready before the eggs and the bacon. Is that correct?
