### ISSUE TITLE
Idea: Articles about SOLID principles

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16643]
SOLID principles is one of the fundamental concepts in any OOP language. I'd expect to see articles about the 5 principles in the documentation.

**Comment by tdykstra** [comment]
Given that these are general concepts that apply across the board to OOP in general, aren't they covered adequately elsewhere? Are they needed in the .NET documentation set?

**Comment by Youssef1313** [comment]
There is an article on polymorphism for example, which is a general concept too. So, I thought it might be good to have some basic idea on SOLID too.

**Comment by mairaw** [comment]
I agree with @tdykstra that this doesn't seem something we should cover in the .NET docs. @BillWagner any thoughts?
