### ISSUE TITLE
Analyze Project Portability reports false positives

### ISSUE THREAD

**Issue by DavidThi808** [dotnet/docs#16653]
The tool reports the following as not supported in .NET Core 3.0

M:System.IO.FileStream.#ctor(System.String,System.IO.FileMode,System.Security.AccessControl.FileSystemRights,System.IO.FileShare,System.Int32,System.IO.FileOptions)
M:System.IO.FileStream.#ctor(System.String,System.IO.FileMode,System.Security.AccessControl.FileSystemRights,System.IO.FileShare,System.Int32,System.IO.FileOptions,System.Security.AccessControl.FileSecurity)

But they are supported. People depend on the results of this tool so false positives can lead to a lot of unnecessary extra work.

**Comment by gewarren** [comment]
I think this issue should be transferred [here](https://github.com/Microsoft/dotnet-apiport/issues). @mairaw Is that correct?

**Comment by mairaw** [comment]
I think so @gewarren. @Lxiamail @terrajobst I don't have the right permissions to transfer this issue there. Can you help?

**Comment by mairaw** [comment]
@DavidThi808 I checked the file on our API docs that lists all the DocIDs for the 3.0 release and those overloads are actually not supported. So the tool is correct.
https://raw.githubusercontent.com/dotnet/dotnet-api-docs/master/xml/FrameworksIndex/netcore-3.0.xml

![image](https://user-images.githubusercontent.com/12971179/72848111-be8e3200-3c58-11ea-85a5-9feb8d455555.png)

So where exactly are you seeing those as being supported in 3.0?

**Comment by Lxiamail** [comment]
@mairaw Thanks for looking into this.  Yes, I got the same conclusion.

**Comment by DavidThi808** [comment]
According to a comment in https://stackoverflow.com/questions/59704285/what-is-the-net-core-replacement-for-new-filestream

>  I am failing to see your issue here, .net core have all those above listed methods. You can check it directly here [source.dot.net/#System.Private.CoreLib/…](https://source.dot.net/#System.Private.CoreLib/FileStream.cs,e23a38af5d11ddd3) all the enums as well. While a tool that analyzes something can be helpful you should not rely entirely on it and actually step forward and test things!

**Comment by Lxiamail** [comment]
@DavidThi808 If you look into [source.dot.net/#System.Private.CoreLib/…](https://source.dot.net/#System.Private.CoreLib/FileStream.cs,e23a38af5d11ddd3) , it doesn't contain the two overloads that you listed in this issue. It has the overloads with [FileAccess](https://apisof.net/catalog/System.IO.FileAccess) instead of [FileSystemRights](https://apisof.net/catalog/System.Security.AccessControl.FileSystemRights). I don't see a problem with the Analyze Project Portability report.

**Comment by carlossanlop** [comment]
@DavidThi808 , we added [this extension method to .NET Core in 3.1](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemaclextensions.create?view=dotnet-plat-ext-3.1#System_IO_FileSystemAclExtensions_Create_System_IO_FileInfo_System_IO_FileMode_System_Security_AccessControl_FileSystemRights_System_IO_FileShare_System_Int32_System_IO_FileOptions_System_Security_AccessControl_FileSecurity_) as the replacement for the FileStream constructor that takes an ACL security object in Framework.

**Comment by mairaw** [comment]
Thanks @carlossanlop. Closing this since the question was answered and the tool is behaving correctly.

**Comment by DavidThi808** [comment]
Thank you all for looking at this and explaining it. And sorry for the false report.

**Comment by carlossanlop** [comment]
No need to apologize, @DavidThi808 , happy to help! Let us know if you have any more questions.
