### ISSUE TITLE
Shift Left/Right greater than size of underlying integer results in undefined behaviour

### ISSUE THREAD

**Issue by NichUK** [dotnet/docs#16652]
According to the spec (and in practice) shifting left/right greater than the number of bits in the underlying integer results in strange results, rather than the 0 that you might expect. It would be useful if this page called that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa
* Version Independent ID: 2410c828-0c66-9efe-ae87-9b07708aa731
* Content: [Bitwise and shift operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#feedback)
* Content Source: [docs/csharp/language-reference/operators/bitwise-and-shift-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@NichUK could you please provide an example of such a behavior

**Comment by pkulikov** [comment]
Currently, the *actual* number of bits to shift is described in the article in this section:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators

**Comment by BillWagner** [comment]
@NichUK Have you checked the text in the preceding comment? I think the linked reference addresses your concern.

I believe this can be closed as addressed, I'll close it, but if you think there should be more clarification, reopen it and add your thoughts.

**Comment by NichUK** [comment]
Thanks Bill, I hadn't noticed the section at the bottom of the document. It might be sensible to move it directly adjacent to the shift left/right sections, as it's important information which should really be read as part of those sections.
Also, since it's a potential pain point if it's missed, personally I'd pull it out and make the meaning a little more obvious, but I agree that there is sufficient info there if the reader examines it carefully.

**Comment by pkulikov** [comment]
@NichUK what do you think of changes in #16656? Rather than moving the section, I've referenced it from the beginnings of the shift operator sections.
