### ISSUE TITLE
Possibly incorrect NuGet package referenced

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/docs#16651]
Example 1 indicates contains the following text:

"If you get the build error "The name 'ZipFile' does not exist in the current context," add a reference to the System.IO.Compression.FileSystem assembly to your project."

NuGet does not contain a Microsoft-published package titled System.IO.Compression.FileSystem, but there's one with a description that sounds similar to the intended goal here called System.IO.Compression.ZipFile (https://www.nuget.org/packages/System.IO.Compression.ZipFile) which reads "Provides classes that support the compression and decompression of streams using file system paths."

Likely, this message should instead reference System.IO.Compression.ZipFile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af6b41b-7150-27fe-c926-f4985fda911e
* Version Independent ID: 87b1df75-cc5c-de8c-4693-e29158ac6683
* Content: [How to: Compress and extract files](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-compress-and-extract-files)
* Content Source: [docs/standard/io/how-to-compress-and-extract-files.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-compress-and-extract-files.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
