### ISSUE TITLE
Add ML.NET doc to explain GPU set up for training in Model Builder

### ISSUE THREAD

**Issue by briacht** [dotnet/docs#16654]
-It's a really complicated process to set up GPU correctly for image classification training in Model Builder. We don't have anything in our own Docs to help users with this, and we'd like to link users from Model Builder to a Docs page (maybe Model Builder > How To guide?) that can walk them through the process.

The main available info for this is in the repo below, but it there's not enough detail / it's not specific to Model Builder.
https://github.com/dotnet/machinelearning/blob/master/docs/api-reference/tensorflow-usage.md

[AB#1667093](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1667093)

**Comment by natke** [comment]
We've added this to the internal backlog. Closing for now until GPU support is added to Model Builder
