### ISSUE TITLE
improvements to install steps.

### ISSUE THREAD

**Issue by anandkulkarnisg** [dotnet/docs#16661]
replace this 
sudo wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/30/prod.repo
with the below.
dnf config-manager --add-repo https://packages.microsoft.com/config/fedora/30/prod.repo
It is a better practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e656d98-d9c6-3feb-c663-96894c813213
* Version Independent ID: 39aa858c-592b-d57f-eb78-759d5add5f35
* Content: [Install .NET Core on Fedora 30 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-fedora30)
* Content Source: [docs/core/install/linux-package-manager-fedora30.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-fedora30.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@dagood thoughts?

**Comment by dagood** [comment]
It is a recommended method in the docs:

* https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/package-management/DNF/#sec-Managing_DNF_Repositories
* https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/package-management/DNF/#sec-Managing_DNF_Repositories
* https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/package-management/DNF/#sec-Managing_DNF_Repositories

However it doesn't work for me without installing more stuff:

```
$ sudo dnf config-manager --add-repo https://packages.microsoft.com/config/fedora/30/prod.repo
No such command: config-manager. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(config-manager)'"

$ sudo dnf install -y 'dnf-command(config-manager)'
...

$ sudo dnf config-manager --add-repo https://packages.microsoft.com/config/fedora/30/prod.repo
Adding repo from: https://packages.microsoft.com/config/fedora/30/prod.repo
```

Admittedly I'm working in a `fedora:30` Docker container, which may have a reduced set of packages installed. I don't know if we aim to support my scenario with our docs, or if we can expect people to follow the error message well enough to resolve it themselves.

**Comment by anandkulkarnisg** [comment]
You are right. You need dnf plugins rpm package as evident from below. yum manager and manual file maintenance is a deprecated usage and not recommended for repo management anymore under fedora.

anand@akhost ~]$rpm -ql dnf-plugins-core-4.0.12-1.fc31.noarch | grep -i config
/usr/share/man/man8/dnf-config-manager.8.gz
[anand@ldnpsr2937 ~]$

**Comment by dagood** [comment]
> yum manager and manual file maintenance is a deprecated usage and not recommended for repo management anymore under fedora.

I'm curious about this, do you maybe have a reference? The docs I linked seem to say adding files is acceptable, mentioning `/etc/yum.repos.d/` explicitly:

> To define a new repository, you can either add a [repository] section to the /etc/dnf/dnf.conf file, or to a .repo file in the /etc/yum.repos.d/ directory.

**Comment by anandkulkarnisg** [comment]
https://www.linux.com/tutorials/what-you-need-know-about-fedoras-switch-yum-dnf/
Anyway yum is still kept there for some compatibility reasons but neverthless dnf 
usage is encouraged.

"Inside the Article"
Yum command has been deprecated, use dnf instead.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run 'dnf migrate'

**Comment by dagood** [comment]
I don't think it's correct to say we're using yum. `dnf config-manager --add-repo` itself puts the repo info into `/etc/yum.repos.d/` too, just with a slightly different filename (missing `microsoft-`):

```
$ dnf repolist -v
...
Repo-id            : fedora
...
Repo-filename      : /etc/yum.repos.d/fedora.repo
...
Repo-id            : packages-microsoft-com-prod
...
Repo-filename      : /etc/yum.repos.d/prod.repo
```

**Comment by anandkulkarnisg** [comment]
Either way i leave the decision to you. Its a minor - nothing thingie :). If you see all documentations of fedora in past 22 and below people used to manage repository settings manually editing and creating repo files. dnf tool changed that off late and what you see in above links you pasted above for docs reflects the proper usage.

**Comment by dagood** [comment]
Sure, thanks for raising the conversation, it's interesting to learn about this! I'm just very cautious about taking changes to these instructions because we have people using them in all sorts of situations. (It just happens to be that I'm someone who would be impacted by this change in this particular case.)

Placing the file manually still seems to be *ok* by the docs, and since going with the nice command brings in a dependency, I don't think we should switch to it without a pretty good reason. I'm closing this issue because I don't think it's worth doing at this point, but definitely open to more discussion. (Maybe it makes sense to do for a future Fedora release where the command is more standard?)
