### ISSUE TITLE
netcore with a DB

### ISSUE THREAD

**Issue by BDTomasz** [dotnet/docs#16675]
Any references to how to setup webapi with Docker that uses MSSQL DB?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-nz/dotnet/core/docker/build-container)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Have you read through the ASP.NET Core tutorial with Docker? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1

Asking questions on that article would be more useful as this article is very basic and geared towards deploying a console app. I'm going to close this issue.
