### ISSUE TITLE
CLR

### ISSUE THREAD

**Issue by tarapoto2006** [dotnet/docs#16672]
It couldn't hurt to add (Common Language Runtime) after CLR for the purpose of clarity in case someone doesn't know what it means. Not everyone reads the guide in order; some read it topically. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a88bb6-664f-99b3-07be-22a666888d11
* Version Independent ID: bea53588-8e8d-5f80-d572-178cd8ba48cb
* Content: [Boxing and Unboxing - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing)
* Content Source: [docs/csharp/programming-guide/types/boxing-and-unboxing.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/boxing-and-unboxing.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@tarapoto2006 Thanks, agreed. Technically, the first mention of CLR should be "common language runtime (CLR)" with the acronym at the end.

**Comment by Youssef1313** [comment]
I've opened a PR that fixes this issue.
