### ISSUE TITLE
Add comment about feed instability due to deb/rpm package publish in "Troubleshoot the package manager"

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#16670]
We should mention that the feed becomes unstable when packages get published: what are the symptoms and how long are you expected to have to wait for it to resolve itself? (At which point you should file an issue on dotnet/core.)

Example on Ubuntu:

```
  File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.91.48.226 443]
```

I think this notice should be added to all Deb and RPM pages. I believe the delay is different between Deb and RPM.

Idea from @drk-mtr over at https://github.com/dotnet/core/issues/4116#issuecomment-574311268.

@leecow @vivmishra @dleeapho 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Install .NET Core on Ubuntu 19.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@dagood Are they fixing the issue behind the scenes? Is this going to keep happening? As someone pointed out in those threads, it really should just work, the repos shouldn't be suddenly crippled for days when a new release comes up. It completely breaks CI and automation.

cc @rbhanda

**Comment by dagood** [comment]
> Are they fixing the issue behind the scenes?

No, it's considered a normal aspect of the service. Yes, it seems pretty absurd.

**Comment by dagood** [comment]
@dleeapho has been trying to work with the team, especially regarding the aftermath of the way more impactful 3.1.0 issues. https://github.com/dotnet/core/issues/3995
