### ISSUE TITLE
Can nullable aware libraries be used in C# 7 projects?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/docs#16679]
If a C# 8 library changes ones of its function signatures from `string GetNullString();` to `string? GetNullString();`, can the function in the library still be consumed by a C# 7 project?

I think it might be good to note this under the "Should nullable warnings introduce breaking changes?" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17290c4d-73f0-5ae1-e8ba-c039fe9fe9ca
* Version Independent ID: 59e0e3bb-b2e5-3ced-72d9-42e641b3897f
* Content: [Upgrade APIs for nullable reference types with attributes that define expectations for null values](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes#should-nullable-warnings-introduce-breaking-changes)
* Content Source: [docs/csharp/nullable-attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Bosch-Eli-Black 

I've added this to our list of issues to address regarding nullable references.

In the meantime, yes, nullable aware libraries can be used by nullable oblvious applications. The compiler will not provide any warnings when compiling the nullable oblivious application, but they will compile and run. 

This is one reason we recommend leaving the null-checks in place when upgrading libraries to use nullable references.

**Comment by Bosch-Eli-Black** [comment]
Okay, makes sense. Thanks, @BillWagner!
