### ISSUE TITLE
apt instead of apt-get

### ISSUE THREAD

**Issue by DrPepperBianco** [dotnet/docs#16687]
As far as I know, today it is better to use "apt" instead of "apt-get". Maybe examples should be changed accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11fe7d1f-129f-d626-fb88-d1bf02a061bf
* Version Independent ID: e277d775-6ce7-a6f7-ac41-ef738f20326a
* Content: [Install .NET Core on Ubuntu 16.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1604#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1604.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1604.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@DrPepperBianco Thank you for the suggestion. Doing some searching I really didn't find a compelling reason to change the commands on all pages that use `apt-get`. Both commands interact with the APT library. The newer `apt` command is just a more user-friendly version of `apt-get`. And it does work as it is right now. I'll remain aware of the `apt` command though. 

Thanks again for the suggestion.
