### ISSUE TITLE
Add real life comparisons to Access Modifiers

### ISSUE THREAD

**Issue by Foxtrek64** [dotnet/docs#16686]
**Issue description**

On the [Accessibility Levels](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels) page, we provide very textbook definitions of each of the access modifiers. Some of these definitions are very technical and can leave newer programmers wondering what they just read.

This issue is rectified by clicking on each of the access modifiers and reading the page on each, though sometimes a more at-a-glance view will help those wanting to make a decision on which 
to use or those who just want a quick, non-technical comparison to aid in understanding.

As such, I propose two additions to this listing, perhaps both on the language reference page linked above and the associated [Access Modifiers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers) page.

First, an at-a-glance table replicating this screenshot:
![Access Modifier Table](https://cdn.discordapp.com/attachments/143867839282020352/642022238601609257/IXnye.png)
([source](https://stackoverflow.com/questions/585859/what-is-the-difference-between-protected-and-protected-internal))

Second, a third column added to the table on the Accessibility Levels page, linked above.

|      Modifier      |                                                                 Meaning                                                                  |                                  Example                                   |
|--------------------|------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------|
| public             | Access is not restricted.                                                                                                                | A public park. Anyone can go there and use any of the facilities provided. |
| protected          | Access is limited to the containing class or types derived from the current class.                                                       | Family car. Available to anyone in the immediate household family.         |
| internal           | Access is limited to the current assembly.                                                                                               | Apartment facility pool. Available to residents of the apartments.         |
| protected internal | Access is limited to the current assembly or types derived from the containing class.                                                    | Household restroom. Available to family members and guests in the home.    |
| private            | Access is limited to the containing type.                                                                                                | Your sister's room. Keep out.                                              |
| private protected  | Access is limited to the containing type or types derived from the containing class within the current assembly. Available since C# 7.2. | The basement storage room. Homeowners and their children only.             |

These examples are pretty tongue-in-cheek and may not be appropriate in their current state. I merely jotted them down in order to help a novice developer understand them. If this is something we are interested in, I would like to take suggestions for better examples, whether more accurate or correct, or more business-oriented.

**Comment by gewarren** [comment]
Cute examples, @Foxtrek64! @BillWagner can you take a look at this idea?

**Comment by john-h-k** [comment]
I find these funny, but at the same time, they help me exactly nought in understanding the access modifiers

**Comment by pkulikov** [comment]
I think the overview table would be useful, also that fits the plan for all those pages to be combined into one overview page.

I like non-technical examples as well, but as a blog content. The metaphors and analogies might be misleading. Moreover, those might be interpreted differently in different cultures. What fits and clicks in one part of the world, doesn't make sense or foreign in another. In the official docs, I would prefer to be puzzled by the precise technical definition and wonder for a while, clearly knowing that I don't understand something. With analogies, there is risk that I would get into the trap of the false understanding.

**Comment by Foxtrek64** [comment]
I think you bring up a very good point, @pkulikov. I hadn't intended these to be perfect examples, but I had failed to consider the cultural/regional side of this documentation.

I'm open to hearing alternatives or scrapping the non-technical example piece entirely. The end goal with this was to provide an at-a-glance understanding of what each access modifier does and guidance on which one to choose. I think the overview table satisfies this goal, and though it still may bring up questions like "what is the difference between a declared class and a derived class," this question is far more searchable than "what did I just read?"
