### ISSUE TITLE
The decryption of database does not work

### ISSUE THREAD

**Issue by raV720** [dotnet/docs#16684]
PRAGMA rekey = NULL
This statement does not work in sqlite - throws "near "NULL": syntax error", so it is not possible do decrypt the database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904359df-95a7-d86a-6339-3d76f423ce26
* Version Independent ID: 888d3d8a-77c8-bd1d-1713-b16f25798521
* Content: [Encryption - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/encryption?tabs=netcore-cli)
* Content Source: [docs/standard/data/sqlite/encryption.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/sqlite/encryption.md)
* Product: **dotnet**
* Technology: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Does an empty string work? If not, it looks like you'll need to use the [sqlcipher_export](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) function.

**Comment by bricelam** [comment]
It looks like an empty string is more generally supported across the different encryption technologies. We should update the docs to use that and call out sqlcipher_export if that's the only way to do it on SQLCipher.

**Comment by raV720** [comment]
The statement with empty string (pragma rekey = '') does not work neither. It executes but has no effect.
