### ISSUE TITLE
Remove "Dependency error with .NET Core 3.1" section on openSUSE 15 now that .NET Core 3.1.1 is released

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#16691]
3.1.1 is released, so the `Dependency error with .NET Core 3.1` section is no longer needed.

Details: https://github.com/dotnet/docs/issues/16330#issuecomment-568578706

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Install .NET Core on openSUSE 15 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks @dagood. @Thraka something for you to look at.

**Comment by Thraka** [comment]
@dagood Is 3.1.1 installed with `install dotnet-sdk-3.1` or does `install dotnet-sdk-3.1.1` need to be specified?

**Comment by dagood** [comment]
> does `install dotnet-sdk-3.1.1` need to be specified?

No--a few reasons to give some context:
* The package name is `dotnet-sdk-3.1`, and you get the latest version in that product band. The unique package name per product band lets you install `dotnet-sdk-3.1` and `dotnet-sdk-3.0` side by side, for example. Commands like `yum update` will update your installed SDKs automatically from the package feed.
* The SDK version is `3.1.101`, not `3.1.1`.
* To install a specific version using RPM package managers, you have to attach the version to the package name with `-`, so `dotnet-sdk-3.1-3.1.101`. (With Debian package managers, you use `=`.)

**Comment by Thraka** [comment]
Ok thanks. I figured as much but wanted to make sure.
