### ISSUE TITLE
The SLES 12 install instructions don't work in a Docker container

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#16697]
I'm trying to run these under a Docker container, to see if installing from a fresh start is working.

```
$ sudo docker run -it --rm registry.suse.com/suse/sles12sp4
# zypper install -y sudo wget
```

My first error happens when I try to install the feed setup package:

```
# sudo rpm -Uvh https://packages.microsoft.com/config/sles/12/packages-microsoft-prod.rpm
Retrieving https://packages.microsoft.com/config/sles/12/packages-microsoft-prod.rpm
error: skipping https://packages.microsoft.com/config/sles/12/packages-microsoft-prod.rpm - transfer failed
😢
```

I can work around that by downloading then installing:

```
# wget https://packages.microsoft.com/config/sles/12/packages-microsoft-prod.rpm
# rpm -Uvh packages-microsoft-prod.rpm
👌
``` 

Then I hit an error trying to refresh the feed:

```
# sudo zypper install dotnet-sdk-3.1
Refreshing service 'container-suseconnect-zypp'.
Retrieving repository 'packages-microsoft-com-prod' metadata --------------------------------------------------------------------------------------------------------------------[\]
Warning: File 'repomd.xml' from repository 'packages-microsoft-com-prod' is signed with an unknown key 'EB3E94ADBE1229CF'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'packages-microsoft-com-prod' is signed with an unknown key 'EB3E94ADBE1229CF'. Continue? [yes/no] (no):
😢
```

I can work around that by downloading the signing key and importing it (based on the openSUSE instructions):

```
# wget https://packages.microsoft.com/keys/microsoft.asc
# rpm --import microsoft.asc
# sudo zypper install dotnet-sdk-3.1
...
Welcome to .NET Core!
👌 
```

I don't know if this is caused by my setup being incorrect or a bug in `packages-microsoft-prod.rpm`... or if the instructions should just be changed to include the workarounds.

@vivmishra @dleeapho @leecow 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107de651-82e4-f603-e8fb-0b351c276438
* Version Independent ID: bc2d5019-9ec4-538b-4396-6b2b5154b0f8
* Content: [Install .NET Core on SLES 12 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-sles12)
* Content Source: [docs/core/install/linux-package-manager-sles12.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-sles12.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@rbhanda
