### ISSUE TITLE
Document Roslyn Diagnostics Security Analyzers

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#1669]
Real mail from a customer today:

> One of our security requirements is to run static analysis on our product’s code. The code analysis tool in VS 2015 can’t analyze .net core projects. What would be the best tool for this? We are currently using .net core 1.1

Our docs need to answer this question. This is our guidance: https://blogs.msdn.microsoft.com/secdevblog/2016/03/30/roslyn-diagnostics-security-analyzers-overview/

**Comment by GuardRex** [comment]
@BillWagner @mairaw The Roslyn area hasn't been composed yet (and it was likely pulled from the TOC back when these empty topics were set aside until written).

https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn/index.md

How do you wish to proceed? Should I craft an index page, add an analyzers topic in this area, and get the the two on the TOC?

**Comment by mairaw** [comment]
I don't think this should go to the C# area. This should be a more generic topic about .NET and code analysis no?

**Comment by GuardRex** [comment]
I thought that it *might be ok* because the index currently lists "links to samples on the roslyn-analyzers repository;" however, yeah, that does just say "link to samples."

If it's a more generic topic on .NET and code analysis, would it be for the *.NET Core Guide* then?

**Comment by BillWagner** [comment]
I think there are a couple sections that relate to Roslyn Analyzers. @richlander writes above about an issue that can be solved by installing and using an existing roslyn based analyzer.

The section @GuardRex mentions will be an introduction to building your own analyzer.  I expect that the audience for using existing analyzers is much greater than for building them.  

You can run analyzers from Visual Studio, or as part of a command line build. The analyzers Microsoft builds and ships should be findable in both of those areas. That suggests the Visual Studio docs, and .NET docs where we discuss the build process.

Building analyzers will be under the C# section.

**Comment by GuardRex** [comment]
> and .NET docs where we discuss the build process.

Under https://docs.microsoft.com/dotnet/core/tools/ and linked into in the `dotnet-build` command topic?

> the Visual Studio docs

... and a VS approach over in the VS docs? (If so, do we need an issue in https://github.com/MicrosoftDocs/visualstudio-docs/issues to cover the VS-side?)

**Comment by mairaw** [comment]
Let's focus on the issue that @richlander opened here. This one is about running analyzers on .NET code, right? I'd expect to find that in the platform guide.

**Comment by GuardRex** [comment]
Cool ... a free topic under *docs/standard/* + mentioned/linked in the index there + mentioned/linked from the `dotnet build` topic in its *See also* section.

I'll come back here and float the title and outline before I start.

**Comment by GuardRex** [comment]
@mairaw I won't get to this by Monday night, so I'm unassigning now.

**Comment by BillWagner** [comment]
I updated the milestone to Q3. I'll handle this as part of the Roslyn API conceptual documentation.

**Comment by BillWagner** [comment]
It's probably not a P0, but the PR is already there.
