### ISSUE TITLE
Changing OpenSSL dependencies on macOS

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#16696]
## Changing OpenSSL dependencies on macOS

.NET Core 3.0 and 3.1 runtimes on macOS will now prefer OpenSSL 1.1.x to OpenSSL 1.0.x for the for the AesCcm, AesGcm, DSAOpenSsl, ECDiffieHellmanOpenSsl, ECDsaOpenSsl, RSAOpenSsl, and SafeEvpPKeyHandle classes.

The .NET Core 2.1 runtime now supports OpenSSL 1.1.x, but will still prefer OpenSSL 1.0.x.

### Version introduced

2.1.16, 3.0.3, 3.1.2

### Old behavior

Previously, the .NET Core runtime would only use OpenSSL 1.0.x for the types that interact with OpenSSL.

### New behavior

The .NET Core 3.0 and 3.1 runtimes will use OpenSSL 1.1.x, if available, and will fall back to OpenSSL 1.0.x if there's no 1.1.x available.  Callers using the OpenSSL Interop types with custom P/Invokes need to follow the guidance from [SafeEvpPKeyHandle.OpenSslVersion](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.safeevppkeyhandle.opensslversion?view=dotnet-plat-ext-3.1#System_Security_Cryptography_SafeEvpPKeyHandle_OpenSslVersion)

The .NET Core 2.1 runtime will use OpenSSL 1.0.x, if available, and will fall back to OpenSSL 1.1.x if there's no 1.0.x available (the reverse of 3.0 and 3.1). This is because the `OpenSslVersion` static property does not exist in .NET Core 2.1, so the OpenSSL version cannot be reliably determined at runtime.

### Reason for change

OpenSSL 1.0.2, the last OpenSSL 1.0.x version, went out of support. Allowing the runtime to move to a newer version keeps the OpenSSL-utilizing types on supported versions.

### Recommended action

* Remove OpenSSL 1.0.2 if it is no longer needed.
* Install OpenSSL 1.1.x if you need any of the AesCcm, AesGcm, DSAOpenSsl, ECDiffieHellmanOpenSsl, ECDsaOpenSsl, RSAOpenSsl, or SafeEvpPKeyHandle classes.
* Follow the guidance from from [SafeEvpPKeyHandle.OpenSslVersion](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.safeevppkeyhandle.opensslversion?view=dotnet-plat-ext-3.1#System_Security_Cryptography_SafeEvpPKeyHandle_OpenSslVersion) if you use the OpenSSL interop types with custom P/Invokes.

### Category

CoreFX

### Affected APIs

* [System.Security.Cryptography.AesCcm](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesccm?view=netcore-3.1)
* [System.Security.Cryptography.AesGcm](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=netcore-3.1)
* [System.Security.Cryptography.DSAOpenSsl](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsaopenssl?view=dotnet-plat-ext-3.1)
* [System.Security.Cryptography.ECDiffieHellmanOpenSsl](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdiffiehellmanopenssl?view=dotnet-plat-ext-3.1)
* [System.Security.Cryptography.ECDsaOpenSsl](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsaopenssl?view=dotnet-plat-ext-3.1)
* [System.Security.Cryptography.RSAOpenSsl](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaopenssl?view=dotnet-plat-ext-3.1)
* [System.Security.Cryptography.SafeEvpPKeyHandle](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.safeevppkeyhandle?view=dotnet-plat-ext-3.1)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by bartonjs** [comment]
FYI, this is about an unreleased change planned for the February releases.  Not the January release that just happened.

**Comment by gewarren** [comment]
@bartonjs Is this actually a breaking change? Since the runtimes will fall back to the older versions of OpenSSL if the newer versions aren't available, I don't get how it's a breaking change.

**Comment by bartonjs** [comment]
@gewarren If (a) 1.1.0 is present, (b) you are doing interop with pointers, (c) you are using .NET Core 3.0 or 3.1, and (d) you didn't check the OpenSslVersion value; your program will probably crash.

It's a minuscule risk (I expect no impact in the wild), but it's there (and since it involves platform interop it's easy to get wrong from one machine to the next; and it involves pointers).
