### ISSUE TITLE
Mention Visual Studio "Paste JSON as Classes" feature

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#16695]
Add a tip box mentioning this feature as a way to make it easier to use JsonSerializer.Deserialize instead of using JsonDocument and JsonElement. It's not a System.Text.Json feature, but it's a useful tool that many developers who need to deserialize JSON may not be aware of.

https://www.c-sharpcorner.com/article/how-to-paste-json-as-classes-or-xml-as-classes-in-visual-stu/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Does it exist somewhere in Visual Studio documentation ?
Perhaps a link to it, if it exists, is sufficient.

**Comment by tdykstra** [comment]
I wasn't able to find it in the VS docs.
