### ISSUE TITLE
Should openSUSE 15 "rpm --import {url}" be changed to something more robust?

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#16692]
Whenever I try to run this command in `opensuse/leap:15` in Docker, this happens:

```
$ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
error: https://packages.microsoft.com/keys/microsoft.asc: import read failed(2).
```

Then, I later have to manually accept the signing key on my first attempt to use the repo.

If I instead do this:

```
$ wget https://packages.microsoft.com/keys/microsoft.asc
$ sudo rpm --import microsoft.asc
```

then the key imports fine, and the repo works on my first attempt without any second-guessing.

I don't know if maybe the error occurs because I'm missing some package, or something works differently in Docker than on a "real" openSUSE Leap 15 machine.

As far as I know, I haven't seen any other users report an issue with this.

/cc @leecow @vivmishra @dleeapho 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Install .NET Core on openSUSE 15 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@rbhanda

**Comment by leecow** [comment]
For some reason which I have not been able to determine, the rpm command does not like to be pointed at an http endpoint when run from a Docker container. We could alter the general instructions to something that works everywhere (download the .asc then import) or add a caveat for Docker.

**Comment by YoshiRulz** [comment]
FWIW `sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc` does not error on OpenSUSE WSL. I first tried `curl -o - https://packages.microsoft.com/keys/microsoft.asc | sudo rpm --import -` but it seems `rpm` does not understand that `-` means stdin.

**Comment by Thraka** [comment]
@leecow thoughts on the post above?

**Comment by mluna1001** [comment]
Hi bro! I had the same error. You need update the certificates in OpenSUSE to solve this. Please, run the next comand for update

`$ sudo update-ca-certificates`

Next, run the rpm --import and later you can install net core

**Comment by Dutchglory** [comment]
"libicu"  not available on  opensuse repositories and/or this one ...

**Comment by dagood** [comment]
@Dutchglory see https://github.com/dotnet/runtime/issues/33672 for the status on that. It's specifically an issue in openSUSE 15.2+. We're asking openSUSE to add `libicu` back to the repo, but we might end up needing to switch things up on our side. (Details in that issue.) Not related to this thread, though.
