### ISSUE TITLE
Disappointed.

### ISSUE THREAD

**Issue by robauer** [dotnet/docs#16701]
So sad that whoever did this - didn't take the time to actually make the code work. When you are trying to learn something, you need to see it work. 

Working code can also be tested and tweaked and played with so that the student learn what is really going on. Showing a bunch of non functional code is worse than not having anything at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@robauer This article is an overview that uses a contrived example to explain the syntax and the concepts of async / await. We've had a number of requests for this kind of a conceptual overview.

Here are a set of walkthroughs and tutorials that you may prefer:

- [Using async / await to access the web](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await).
- [Create a Webclient console app that reads data from the web](https://docs.microsoft.com/dotnet/csharp/tutorials/console-webapiclient).
- [Create a console app that demonstrates many C# features](https://docs.microsoft.com/dotnet/csharp/tutorials/console-teleprompter).
- [How to make multiple web requests in parallel using async / await](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/how-to-make-multiple-web-requests-in-parallel-by-using-async-and-await).

Let us know if that helps you find samples to experiment with.

**Comment by robauer** [comment]
Thank you for your reply!

 

This is very helpful.

 

Rob

**Comment by BillWagner** [comment]
I'm glad that helps @robauer 

I'll close this as answered.
