### ISSUE TITLE
.NET 5 breaking change: StringInfo and TextElementEnumerator classes are now UAX29-compliant

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/docs#16702]
## .NET 5's `System.Globalization.StringInfo` and `System.Globalization.TextElementEnumerator` classes now follow UAX29 guidelines for extended grapheme enumeration

Unicode has the concept of a "[grapheme](https://www.unicode.org/glossary/#grapheme)", which roughly approximates what the user perceives as a single display character. In [UAX#29](https://www.unicode.org/reports/tr29/tr29-35.html#Grapheme_Cluster_Boundaries), this is properly formalized as a concept called an "[extended grapheme cluster](https://www.unicode.org/glossary/#extended_grapheme_cluster)".

Consider the string containing the Thai character _kam_ (`"กำ"`). This string actually consists of two `char`s:

 * `' ก '` (= `'\u0e01'`) THAI CHARACTER KO KAI, followed by
 * `' ำ '` (= `'\u0e33'`) THAI CHARACTER SARA AM

When displayed to the user, the operating system combines them to form the single display character (or _grapheme_) _kam_, or __กำ__.

This is also of use when displaying emoji. Consider the string containing the emoji _Woman Shrugging: Medium Skin Tone_ (`"🤷🏽‍♀️"`). This string actually consists of seven `char`s: `[ '\ud83e', '\udd37', '\ud83c', '\udffd', '\u200d', '\u2640', '\ufe0f' ]`. But the operating system will combine all seven of these together and display them as a single unit.

In .NET, the [`System.Globalization.StringInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo) and [`System.Globalization.TextElementEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.textelementenumerator) classes allow developers to inspect a string and to get information about the graphemes it contains. Prior to this change, the `StringInfo` and `TextElementEnumerator` types contained legacy logic that didn't properly handle all grapheme clusters. With this change, these two types process grapheme clusters according to the latest version of the Unicode Standard.

The .NET documentation sometimes uses the term "text element" when referring to a grapheme.

### Version introduced

Introduced in .NET 5. The original tracking issue is https://github.com/dotnet/corefx/issues/41324.

### Old behavior

In .NET Framework (all versions) and .NET Core 3.x and earlier, the `StringInfo` and `TextElementEnumerator` types implemented custom logic that handled certain combining classes but did not fully comply with the Unicode Standard.

```cs
using System.Globalization;

static void Main(string[] args)
{
    PrintGraphemes("กำ");
    PrintGraphemes("🤷🏽‍♀️");
}

static void PrintGraphemes(string str)
{
    Console.WriteLine($"Printing graphemes of \"{str}\"...");
    int i = 0;

    TextElementEnumerator enumerator = StringInfo.GetTextElementEnumerator(str);
    while (enumerator.MoveNext())
    {
        Console.WriteLine($"Grapheme {++i}: \"{enumerator.Current}\"");
    }

    Console.WriteLine($"({i} grapheme(s) total.)");
    Console.WriteLine();
}
```

Output:

```txt
Printing graphemes of "กำ"...
Grapheme 1: "ก"
Grapheme 2: "ำ"
(2 grapheme(s) total.)

Printing graphemes of "🤷🏽‍♀️"...
Grapheme 1: "🤷"
Grapheme 2: "🏽"
Grapheme 3: "‍"
Grapheme 4: "♀️"
(4 grapheme(s) total.)
```

In the case of the single Thai character _kam_, the `StringInfo` and `TextElementEnumerator` classes incorrectly split the character back into its constituent components instead of keeping them together.

In the case of the emoji character, the `StringInfo` and `TextElementEnumerator` classes incorrectly split the emoji character into four clusters: person shrugging, skin tone modifier, gender modifier, and an invisible combiner. All of these should have been kept together as a single grapheme.

### New behavior

Starting with .NET 5, the `StringInfo` and `TextElementEnumerator` classes follow the Unicode Standard exactly. In particular, they now return [_extended grapheme clusters_](https://www.unicode.org/glossary/#extended_grapheme_cluster). Their logic implements the standard as defined by [Unicode Standard Annex \#29, rev. 35](https://www.unicode.org/reports/tr29/tr29-35.html), sec. 3.

Re-running the sample program above now gives the correct output:

```txt
Printing graphemes of "กำ"...
Grapheme 1: "กำ"
(1 grapheme(s) total.)

Printing graphemes of "🤷🏽‍♀️"...
Grapheme 1: "🤷🏽‍♀️"
(1 grapheme(s) total.)
```

Visual Basic's [`StrReverse`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.strings.strreverse) function is also updated to follow the standardized logic.

### Reason for change

This change is part of a wider set of Unicode and UTF-8 improvements being made to .NET Core. It also provides a proper "extended grapheme cluster" enumeration API to complement the "Unicode scalar value" enumeration APIs which were introduced in .NET Core 3.0 with the [`System.Text.Rune`](https://docs.microsoft.com/en-us/dotnet/api/system.text.rune) type.

### Recommended action

No action is needed on the part of developers. Developers should find that their applications now behave in a more standards-compliant fashion in a wider variety of globalization-related scenarios.

### Category

 - Globalization

### Affected APIs

 - [`System.Globalization.StringInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo)
 - [`System.Globalization.TextElementEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.textelementenumerator)
 - [`Microsoft.VisualBasic.Strings.StrReverse`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.strings.strreverse)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Serentty** [comment]
This is a small nitpick, but a grapheme and a grapheme cluster are not the same. .NET's ``TextElement``s are clusters, as opposed to individual graphemes. A cluster might be made up of many graphemes, but Unicode doesn't make any sort of judgement as to exactly how many.

**Comment by StelleSand** [comment]
Hi, folks, actually I've met the issue caused by this change when upgrading from netcore3.1 to Net6.
The same issue as mentioned at https://github.com/dotnet/runtime/issues/64489.
I want to know is there any API to replace the class TextElementEnumerator and StringInfo and get the same behavior? Or I have to migrate source code of these 2 classes from netframework to Net6?

**Comment by gewarren** [comment]
@tarekgh Can you answer @StelleSand 's question?

**Comment by tarekgh** [comment]
@StelleSand can you clarify your question more? What are you trying to achieve? Are you looking for getting old behavior before .NET 6.0 change? if so, why?

**Comment by StelleSand** [comment]
My project processs strings with NetFX version of StringInfo and TextElementEnumerator then persist the output (consider it an encoding process). The new version of StringInfo and TextElementEnumerator will cause Net5+ version program didn't work in the persistent data (consider it a decoding process). Persistent data is so huge that I have to find some way to be compliant with the old data. Now I'm blocked by this breaking change when migrating to Net6, and need some method to fix this. 
Any suggestion would be appreciated, :).

**Comment by tarekgh** [comment]
> Persistent data is so huge that I have to find some way to be compliant with the old data. 

Do you have the option to migrate the data to make it work with .NET 6.0. I know it is huge, but a small tool can just read the data and re-encode it with .NET 6.0. 

> Now I'm blocked by this breaking change when migrating to Net6, and need some method to fix this.

I'll help as much as possible to unblock you. Let's see first find out if my previous suggestion for migrating the data is viable or not.

**Comment by StelleSand** [comment]
Migrating the data would not be an option cause the effort is too large to take (Data across over 20 years with over 10 million of users). The only option I have is to be compliant with the old data. Code transplant would do for this option, but I want to know if there is any other solution to accomplish this.

**Comment by tarekgh** [comment]
> I want to know if there is any other solution to accomplish this.

The other option would be picking up the code from .NET Framework. This is not too difficult to do but the issue here is you are going to be stuck with the old Unicode behavior. It is better to pay the cost one time now instead of paying some cost forever moving forward. Let me know if you need any help either way and I'll be happy to provide it.

**Comment by StelleSand** [comment]
I picked the following files:
- System\Globalization\BidiCategory.cs
- System\Globalization\CharUnicodeInfo.cs
- System\Globalization\CharUnicodeInfoData.cs
- System\Globalization\stringinfo.cs
- System\Globalization\textelementenumerator.cs
- System\Globalization\UnicodeCategory.cs
- Resources\Strings.resx
It seems these files is enough for my migration. In case anyone have the same problem as me, transplanting these files would recover the behavior class StringInfo & TextElementEnumerator.

Sincere Thanks for @tarekgh's kindly suggestion!
