### ISSUE TITLE
xrefs for generic types in Visual Basic articles

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16709]
An xref to a generic type will always display in C# syntax, for example, Task<TResult>.

This is something that Visual Basic developers might not be familiar with, it's better to have them as Task(Of TResult).

**Comment by BillWagner** [comment]
This is a good point @Youssef1313 

Adding @KathleenDollard and @cartermp  How should we address this throughout the docs?

**Comment by cartermp** [comment]
This is mostly fine for F# since developers are so used to using C# as well. The key difference is `T` vs `'T` for how they're specified, but everything else is the same. Though if there were a feature to toggle the syntax based on language set that would be neat too :D

**Comment by gewarren** [comment]
This seems like a holistic site issue to me, and not something we should spend a lot of effort on working around. Should we transfer this to https://github.com/microsoftdocs/feedback?

**Comment by mairaw** [comment]
I think so @gewarren

**Comment by gewarren** [comment]
@Youssef1313 Since we can't transfer the issue directly (different organization) do you want to create a new issue over at https://github.com/microsoftdocs/feedback?

**Comment by mairaw** [comment]
I use a tool to do that. I'll transfer.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2395
