### ISSUE TITLE
Using System.Text.Json.Serialization statement required

### ISSUE THREAD

**Issue by qvlethe** [dotnet/docs#16729]
It should be noted in the 'Controlling Serialization' section that you need to include the `using System.Text.Json.Serialization` statement before you add the `[JsonPropertyName]` attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @qvlethe 

I've added this to our backlog. I've also added the "up for grabs" and "good first issue" labels, if you or another community member wants to submit a PR to address this.

Thanks again.
