### ISSUE TITLE
The null-forgiving operator is not listed as a C# 8 feature

### ISSUE THREAD

**Issue by lcsondes** [dotnet/docs#16720]
"What's new in C# 8" doesn't mention the null-forgiving operator anywhere, which is documented on its own page as being available in C# 8.0 or later. Although there are links to learn more about NRT I feel that an entirely new operator is worth a mention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @lcsondes 

I've added this to the next sprint, when I'll update the what's new page as we finish all the C# 8.0 content throughout the C# guide.

**Comment by LeftofZen** [comment]
How long are your sprints? It isn't updated yet.
