### ISSUE TITLE
must be added to PATH?

### ISSUE THREAD

**Issue by samboustani** [dotnet/docs#16739]
'dotnet-core-uninstall' is not recognized as an internal or external command, operable program or batch file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289d3b2b-8b21-d0a0-10fa-9a8b3fdb62ce
* Version Independent ID: 3145ef37-2a19-e3ca-ba78-95c2f1a41a6b
* Content: [Uninstall Tool - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows#feedback)
* Content Source: [docs/core/additional-tools/uninstall-tool.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/uninstall-tool.md)
* Product: **dotnet-core**
* GitHub Login: @sfoslund
* Microsoft Alias: **mairaw**

**Comment by sfoslund** [comment]
The PATH should be updated by the MSI if you follow the instructions for installation found [here](https://github.com/dotnet/cli-lab/releases) (also linked in the [installation section](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows#install-the-tool) of the docs). Are you still having this issue after following these instructions (noting that you need to open a new command prompt after something is added to the PATH)?

**Comment by mikekilkenny** [comment]
This still appears to be an issue.
