### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by alex-dranoel** [dotnet/docs#16744]
Hello .NET guys, thanks for the tutorial, it's very useful. I've spotted an inconsistency between the text and the code.
On page "Include different data types", the code for formatting the price includes the currency format specifier "C2", this should not be there at that moment. However on the next page, "Control the formatting of interpolation expressions", the code does not include it while the text is referring to it.

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356f32d2-2574-9d48-a096-aef9fc21112d
* Version Independent ID: 49ae4e9d-cd57-917c-8795-71ad57858d5d
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/interpolated-strings?tutorial-step=5#feedback)
* Content Source: [docs/csharp/tutorials/exploration/interpolated-strings.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I've opened #16747 to fix this.
