### ISSUE TITLE
"Build .NET Core from source" article is outdated

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16745]
The `dotnet/cli` repository has moved. I'm not sure if only changing the link will solve the issue. The instructions to build might have some changes.

The same applies to the first heading ("Build the CLR from source"), the repository link has been updated to the new `dotnet/runtime`, but I'm not sure if the instructions to build has changed or not.

I also think the article should have a heading "Build libraries from source". The `dotnet/runtime` repository has now the CLR and the libraries. Current layout has "Build the CLR" but not "Build libraries".
cc: @jkotas 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b95543-2043-fa28-08f1-54fceeec1301
* Version Independent ID: 945584fb-faa9-140d-c193-69ea9c646b51
* Content: [Build .NET Core from source - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/build/#build-the-cli-from-source)
* Content Source: [docs/core/build/index.md](https://github.com/dotnet/docs/blob/master/docs/core/build/index.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by jkotas** [comment]
We should not be duplicating the repo build instructions in the docs. The repo build instructions are constantly changing, and so the docs copy is going to be always outdated.

If we want to have this mentioned in the docs, I think it should just link to the instructions in the repo.

**Comment by mairaw** [comment]
Should we delete this article @jkotas? This article hasn't been maintained and I'm not sure why it was created in the first place. The only downside is that repo instructions are not localized.

**Comment by jkotas** [comment]
Yes, I think this article should be deleted.

**Comment by mairaw** [comment]
I'll do that then.

**Comment by Youssef1313** [comment]
> The only downside is that repo instructions are not localized.

For this reason, why not use the [!INCLUDE] syntax ? This will make the article always matching the dotnet/runtime instructions, and also localized versions will exist.

**Comment by jkotas** [comment]
The .NET docs at https://docs.microsoft.com/ are targeted at people using .NET. 99.9+% of them won't ever build their own .NET runtime.

Building your own .NET runtime or making modifications in it are advanced scenarios. We have extensive documentation for that in dotnet/runtime that is separate from  https://docs.microsoft.com/ on purpose.
