### ISSUE TITLE
"Compile with" comments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16748]
In <https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/private-protected.md> (Just one example, there are many)

The code snippet starts with:

```csharp
// Assembly1.cs  
// Compile with: /target:library 
```

I'm not sure which tool this compile option is related to, but I think it's not related to .NET Core, so this kind of comments can just be removed.

**Comment by BillWagner** [comment]
That's a good point @Youssef1313 

I've added this as one of the items we should address across our samples.

**Comment by NextTurn** [comment]
> I'm not sure which tool this compile option is related to, but I think it's not related to .NET Core

It's one of the *csc* options. There is *csc* for .NET Core too.

https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/target-compiler-option
