### ISSUE TITLE
The first sentence of the second paragraph is clunky.

### ISSUE THREAD

**Issue by KalinBowden** [dotnet/docs#16757]
"The examples in this topic show how to work with events." should probably read "The examples in this topic shows how to work with events."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89598b6d-6319-fc9e-d7b7-3335f40e9506
* Version Independent ID: e074b827-7416-3c43-7fde-0244c61bb35c
* Content: [How to: Raise and Consume Events](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events#feedback)
* Content Source: [docs/standard/events/how-to-raise-and-consume-events.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-raise-and-consume-events.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@KalinBowden Thanks for the feedback, however, I disagree with the rewrite.  would say "the examples show", not "the examples shows", since examples is plural.
