### ISSUE TITLE
ExponentialBackoff throws due to negative delays

### ISSUE THREAD

**Issue by dasMulli** [dotnet/docs#16754]
An integer overflow bug in the `ExponentialBackoff` struct causes the code to throw an exception on Task.Delay() when the code is retried more than 24 times. This is because the expression `m_delayMilliseconds * (m_pow - 1) / 2` overflows using the default delay of 200ms on the 24th call to `Delay()`. If `m_delyMilliseconds` is 2, the expression overflows on the 31st retry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67be79f-76ed-d9f0-a97e-3f60235bd773
* Version Independent ID: 1556554c-95c2-1d16-7fad-01eb8bf1c034
* Content: [Explore custom HTTP call retries with exponential backoff](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/explore-custom-http-call-retries-exponential-backoff)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/explore-custom-http-call-retries-exponential-backoff.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/explore-custom-http-call-retries-exponential-backoff.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil @mvelosop there are also some interesting comments/questions on @CESARDELATORRE's gist around license and other issues, in addition to the one brought up by @dasMulli. Shouldn't the code be moved to another repo where there's a clear license?
https://gist.github.com/CESARDELATORRE/6d7f647b29e55fdc219ee1fd2babb260

**Comment by dasMulli** [comment]
Also, backoffs could now use an `IAsyncEnumerable` for fun and good measure (`await foreach(var retryIndex in delayEnumerable) { ... perform retry... }`.. i'm using something like that but copied the delay calculation from this doc to find out it becomes negative after some retries)
