### ISSUE TITLE
toc localization issue

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16767]
![image](https://user-images.githubusercontent.com/31348972/72786648-c5a44880-3c36-11ea-8b85-c2eeb173a84d.png)

static keyword shouldn't be localized in the toc.
I see the other keywords aren't localized in there is no special thing done for them.

cc: @JasonCard

**Comment by JasonCard** [comment]
I checked with @bodhigautam and unfortunately the [no-loc feature](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings) does not work on yml files.
Our loc vendor will follow up on this issue.

@DavidPrio Could you please help to follow up on this issue?
Live: https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/static 
Loc repo: https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/toc.yml
Reported issue is that "static" is over-localized as "statique" in fr-fr, but it looks like there more keywords that are over-localized (e.g. "événement"). 
It's also over-localized for [es-es](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/static), [it-it](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/static), [ko-kr](https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/keywords/static), [zh-cn](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/static), and [zh-tw](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/static).
Could you please help to have this entire TOC.yml reviewed for over-localization of keywords in all languages?

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs.fr-fr #101](https://github.com/dotnet/docs.fr-fr/issues/101) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ticianaciminari** [comment]
Hello, @Youssef1313,

Your feedback is much appreciated. 

Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one. 

Please review the status of this issue here [MOR to add link to the loc repo issue]. 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
#pleaseclose
