### ISSUE TITLE
Missing discussion of scope of warning suppression

### ISSUE THREAD

**Issue by binki** [dotnet/docs#16763]
From the example, it looks like the suppression starts on the line after the `#pragma warning disable` and lasts until the line after the `#pragma warning restore`. But that’s not explicitly stated. It should be.

Also, even the example leaves me with an unanswered question. Does the suppression end at the end of the compilation unit or can it affect other files that are being compiled together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68010f2-39f6-6de9-43f8-342dc5bdfa36
* Version Independent ID: 002be4de-f321-1760-d4ec-2b729f149562
* Content: [#pragma warning - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @binki 

I've added this to our backlog, and  added the up-for-grabs label for interested community members to address.

On this question:

> Does the suppression end at the end of the compilation unit or can it affect other files that are being compiled together?

The suppression does end at the end of the compilation unit.

**Comment by binki** [comment]
@dotnet/docs @BillWagner @akoeplinger This issue is still not resolved.
