### ISSUE TITLE
Need Some Related Links

### ISSUE THREAD

**Issue by dpm39560** [dotnet/docs#16769]
It would be VERY HELPFUL to have links near the end of this article directing us to other articles that tell us how to SET a specific bit in a byte; and how to READ a specific bit in a byte. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d3fe63-2f2e-bf75-653b-9bbbe35683a2
* Version Independent ID: 10ef5387-22c6-564f-05f0-4210fcf51e23
* Content: [Byte Data Type - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/byte-data-type#feedback)
* Content Source: [docs/visual-basic/language-reference/data-types/byte-data-type.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/data-types/byte-data-type.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Thanks for your suggestion @dpm39560. This issue is now on our backlog.
