### ISSUE TITLE
code reference syntax has changed

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16768]
Code reference syntax has changed.
New syntax is explained in https://docs.microsoft.com/contribute/how-to-write-use-markdown#snippet-syntax-reference

At the time of writing this issue, that causes 10,001 build suggestions:

![image](https://user-images.githubusercontent.com/31348972/72788442-9bed2080-3c3a-11ea-9b6d-ee10c915ee9f.png)

The build suggestion message says:

> The legacy code snippet inclusion will be deprecated at a later date. Please use the new code extension. (http://aka.ms/codesnippet)

I also think that the new interactive modes will allow much more samples to be interactive 🎉 🎉 🎉 .

**Comment by BillWagner** [comment]
@Youssef1313 Yes, that's been changed in the most recent deployment.

We'll be updating these under a few different tasks over the next month or two. 

For the moment, we'd prefer not updating these outside of those tasks. We evaluating many of the samples to include interactive capability where it's applicable.

**Comment by mairaw** [comment]
The warnings are unexpected though. I thought both would still be supported equally.
