### ISSUE TITLE
Work with syntax

### ISSUE THREAD

**Issue by Karl15** [dotnet/docs#16773]
I have been frustrated with the tools that are available for electronic chip logic design/FPGA and the C# SyntaxWalker makes it possible to design and debug the logic using C#.

The hardware design input can be formatted can be formatted using the nodes from the syntax walker.

This would reduce the difficulty and frustration that MS Research encountered with Project Catapult when using the traditional hardware design tool chain or any other hardware logic
design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af3ae43-b958-0576-168e-539936d2ba81
* Version Independent ID: 6a1490ae-78b2-d8ba-07f1-df1c22f7a830
* Content: [Use the .NET Compiler Platform SDK syntax model](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/work-with-syntax)
* Content Source: [docs/csharp/roslyn-sdk/work-with-syntax.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/work-with-syntax.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm glad you're interested in the syntax walker @Karl15 

I hope it helps in your project.

closing as kudos.

**Comment by Karl15** [comment]
Thanks, Bill
I started out parsing the source and using the Shunting Yard algorithm.
Verification was going to be a problem.
Now I read the source, build the AST and get all the nodes in the correct sequence.

In effect what I end up with is a "new" computer that does if, else, for, while, dowhile, and assignments without compiling to an ISA.
