### ISSUE TITLE
Call .exe within .NET framework tools from powershell

### ISSUE THREAD

**Issue by sajisV5Framework** [dotnet/docs#16771]
**Help us make content visible**

- access .NET framework tools from powershell  - found no  useful documentation regarding this.
- Want to achieve the following :
   - Need to use/call CorFlags.exe from powershell script. 
   - As of today , we are hard coding the path where CorFlags.exe to be found and this is not an optinal solution.  The intended solution is automate the following process by powershell:
      - Check if .NET framework tools is installed in the system 
      - If not installed , then install it and locate the file and path to CorFlags.exe
      - Use the .exe to create nuget package from a .msi file.       

edit by @mairaw: added related article details  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60439c92-7612-ef8a-c00a-1a1869300d5e
* Version Independent ID: 8b6d240f-aca1-646b-d0a5-b9a783e2c3da
* Content: [.NET Framework Tools](https://docs.microsoft.com/en-us/dotnet/framework/tools/)
* Content Source: [docs/framework/tools/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/index.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
@vivmishra do you have any suggestions here? The developer command prompt sets some things behind the scenes for users to be able to access the .NET Framework tools directly.

**Comment by vivmishra** [comment]
cc: @richlander 

.NET Framework SDK installer sets the following registry hive where you can get to the InstallationFolder value for every SDK product version, but not sure what you can use from the Dev command prompt.

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK
