### ISSUE TITLE
Wrong path to the published executable

### ISSUE THREAD

**Issue by fieldgrey** [dotnet/docs#16770]
The wrong file got executed.

It reads:
```bash
.\bin\Debug\netcoreapp3.1\Hello.exe

Hello World!
```

But in reality the file path must be:
```bash
bin/Debug/netcoreapp3.1/publish/Hello

Hello World!
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa0c79e-1729-15f7-52e4-0c9afff43ec9
* Version Independent ID: 1c3c5d30-9690-8c4a-4e2c-2ce5f4386898
* Content: [Get started with .NET Core using the CLI - .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-create-console-app#feedback)
* Content Source: [docs/core/tutorials/cli-create-console-app.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-create-console-app.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thanks for letting us know, I'll get this fixed!
