### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by paulh-rnd** [dotnet/docs#16779]
I'm getting an `InvalidCastException` on the following line, when using the code unmodified from this documentation:

            LinearRegressionModelParameters originalModelParameters =
                ((ISingleFeaturePredictionTransformer&lt;object&gt;)trainedModel).Model as LinearRegressionModelParameters;

The full exception message is:

    System.InvalidCastException: 'Unable to cast object of type 'Microsoft.ML.Data.TransformerChain`1[Microsoft.ML.ITransformer]' to type 'Microsoft.ML.ISingleFeaturePredictionTransformer`1[System.Object]'.'

I'm using Microsoft.ML v1.4.0 in a .Net Core 2.1 console app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0366cc46-bc07-44fd-72d9-d37b40bd5eca
* Version Independent ID: 5c20d041-f946-d7c8-b0b5-7bee96e90282
* Content: [Re-train a model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/retrain-model-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/retrain-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @paulh-rnd ,

Sorry to hear you're running into issues. I was not able to replicate the exception mentioned in this issue. One thing I would mention is, not all trainers can be retrained. In the article there is a list of the ones you can retrain. Here is working code that aligns with the samples in the how-to guide.

.NET SDK Version: 2.1
ML.NET Version: 1.4.0

## Data Schema

```csharp
class HousingData
{
    public float Size { get; set; }
    [VectorType(3)]
    public float[] HistoricalPrices { get; set; }
    [ColumnName("Label")]
    public float CurrentPrice { get; set; }
}
```

## Main Program

```csharp
static void Main(string[] args)
{
    // Create MLContext
    MLContext mlContext = new MLContext();

    // Train and Save Model
    TrainAndSaveModel(mlContext);

    // Retrain model
    RetrainModel(mlContext);
}
```

## TrainAndSaveModel Method

```csharp
static void TrainAndSaveModel(MLContext mlContext)
{
    HousingData[] housingData = new HousingData[]
    {
        new HousingData
        {
            Size = 600f,
            HistoricalPrices = new float[] { 100000f, 125000f, 122000f },
            CurrentPrice = 170000f
        },
        new HousingData
        {
            Size = 1000f,
            HistoricalPrices = new float[] { 200000f, 250000f, 230000f },
            CurrentPrice = 225000f
        },
        new HousingData
        {
            Size = 1000f,
            HistoricalPrices = new float[] { 126000f, 130000f, 200000f },
            CurrentPrice = 195000f
        }
    };
    
    // Load Data
    IDataView data = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);

    // Define data preparation estimator
    IEstimator<ITransformer> dataPrepPipeline =
        mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
            .Append(mlContext.Transforms.NormalizeMinMax("Features"));

    // Fir data preparation estimator to data
    ITransformer preprocessor = dataPrepPipeline.Fit(data);

    // Define model training pipeline
    var trainingPipeline = mlContext.Regression.Trainers.OnlineGradientDescent();

    // Preprocess data
    IDataView preprocessedData = preprocessor.Transform(data);

    // Train model
    ITransformer trainedModel = trainingPipeline.Fit(preprocessedData);

    // Save data preparation pipeline
    mlContext.Model.Save(preprocessor, data.Schema, "data_preparation_pipeline.zip");

    // Save trained model
    mlContext.Model.Save(trainedModel, preprocessedData.Schema, "ogd_model.zip");
}
```

## RetrainModel Method

```csharp
static void RetrainModel(MLContext mlContext)
{
    // Load saved data prep pipeline
    ITransformer dataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out DataViewSchema dataPrepPipelineSchema);

    // Load trained model
    ITransformer trainedModel = mlContext.Model.Load("ogd_model.zip", out DataViewSchema modelSchema);

    // Extract trained model parameters
    LinearRegressionModelParameters originalModelParameters =
        ((ISingleFeaturePredictionTransformer<object>)trainedModel).Model as LinearRegressionModelParameters;

    // Create new data
    HousingData[] housingData = new HousingData[]
    {
        new HousingData
        {
            Size = 850f,
            HistoricalPrices = new float[] { 150000f,175000f,210000f },
            CurrentPrice = 205000f
        },
        new HousingData
        {
            Size = 900f,
            HistoricalPrices = new float[] { 155000f, 190000f, 220000f },
            CurrentPrice = 210000f
        },
        new HousingData
        {
            Size = 550f,
            HistoricalPrices = new float[] { 99000f, 98000f, 130000f },
            CurrentPrice = 180000f
        }
    };

    // Load new data into an IDataView
    IDataView newData = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);

    // Apply data prep transforms to new data
    IDataView transformedNewData = dataPrepPipeline.Transform(newData);

    // Use the new data to train a new model
    var retrainedModel = mlContext.Regression.Trainers.OnlineGradientDescent().Fit(transformedNewData, originalModelParameters);

    // Extract Model Parameters of retrained model
    LinearRegressionModelParameters retrainedModelParameters = retrainedModel.Model as LinearRegressionModelParameters;

    // Inspect change in weights after retraining
    var weightDiffs =
        originalModelParameters.Weights.Zip(
            retrainedModelParameters.Weights, (original, retrained) => original - retrained).ToArray();

    Console.WriteLine("Original | Retrained | Difference");
    for (int i = 0; i < weightDiffs.Count(); i++)
    {
        Console.WriteLine($"{originalModelParameters.Weights[i]} | {retrainedModelParameters.Weights[i]} | {weightDiffs[i]}");
    }
}
```

Running this program should yield output similar to that below:

```text
Original | Retrained | Difference
33039.86 | 56293.76 | -23253.9
29099.14 | 49586.03 | -20486.89
28938.38 | 48609.23 | -19670.85
30484.02 | 53745.43 | -23261.41
```

**Comment by maolin-kooboo** [comment]
> Hi @paulh-rnd ,
> 
> Sorry to hear you're running into issues. I was not able to replicate the exception mentioned in this issue. One thing I would mention is, not all trainers can be retrained. In the article there is a list of the ones you can retrain. Here is working code that aligns with the samples in the how-to guide.
> 
> .NET SDK Version: 2.1
> ML.NET Version: 1.4.0
> 
> ## Data Schema
> ```cs
> class HousingData
> {
>     public float Size { get; set; }
>     [VectorType(3)]
>     public float[] HistoricalPrices { get; set; }
>     [ColumnName("Label")]
>     public float CurrentPrice { get; set; }
> }
> ```
> 
> ## Main Program
> ```cs
> static void Main(string[] args)
> {
>     // Create MLContext
>     MLContext mlContext = new MLContext();
> 
>     // Train and Save Model
>     TrainAndSaveModel(mlContext);
> 
>     // Retrain model
>     RetrainModel(mlContext);
> }
> ```
> 
> ## TrainAndSaveModel Method
> ```cs
> static void TrainAndSaveModel(MLContext mlContext)
> {
>     HousingData[] housingData = new HousingData[]
>     {
>         new HousingData
>         {
>             Size = 600f,
>             HistoricalPrices = new float[] { 100000f, 125000f, 122000f },
>             CurrentPrice = 170000f
>         },
>         new HousingData
>         {
>             Size = 1000f,
>             HistoricalPrices = new float[] { 200000f, 250000f, 230000f },
>             CurrentPrice = 225000f
>         },
>         new HousingData
>         {
>             Size = 1000f,
>             HistoricalPrices = new float[] { 126000f, 130000f, 200000f },
>             CurrentPrice = 195000f
>         }
>     };
>     
>     // Load Data
>     IDataView data = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);
> 
>     // Define data preparation estimator
>     IEstimator<ITransformer> dataPrepPipeline =
>         mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
>             .Append(mlContext.Transforms.NormalizeMinMax("Features"));
> 
>     // Fir data preparation estimator to data
>     ITransformer preprocessor = dataPrepPipeline.Fit(data);
> 
>     // Define model training pipeline
>     var trainingPipeline = mlContext.Regression.Trainers.OnlineGradientDescent();
> 
>     // Preprocess data
>     IDataView preprocessedData = preprocessor.Transform(data);
> 
>     // Train model
>     ITransformer trainedModel = trainingPipeline.Fit(preprocessedData);
> 
>     // Save data preparation pipeline
>     mlContext.Model.Save(preprocessor, data.Schema, "data_preparation_pipeline.zip");
> 
>     // Save trained model
>     mlContext.Model.Save(trainedModel, preprocessedData.Schema, "ogd_model.zip");
> }
> ```
> 
> ## RetrainModel Method
> ```cs
> static void RetrainModel(MLContext mlContext)
> {
>     // Load saved data prep pipeline
>     ITransformer dataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out DataViewSchema dataPrepPipelineSchema);
> 
>     // Load trained model
>     ITransformer trainedModel = mlContext.Model.Load("ogd_model.zip", out DataViewSchema modelSchema);
> 
>     // Extract trained model parameters
>     LinearRegressionModelParameters originalModelParameters =
>         ((ISingleFeaturePredictionTransformer<object>)trainedModel).Model as LinearRegressionModelParameters;
> 
>     // Create new data
>     HousingData[] housingData = new HousingData[]
>     {
>         new HousingData
>         {
>             Size = 850f,
>             HistoricalPrices = new float[] { 150000f,175000f,210000f },
>             CurrentPrice = 205000f
>         },
>         new HousingData
>         {
>             Size = 900f,
>             HistoricalPrices = new float[] { 155000f, 190000f, 220000f },
>             CurrentPrice = 210000f
>         },
>         new HousingData
>         {
>             Size = 550f,
>             HistoricalPrices = new float[] { 99000f, 98000f, 130000f },
>             CurrentPrice = 180000f
>         }
>     };
> 
>     // Load new data into an IDataView
>     IDataView newData = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);
> 
>     // Apply data prep transforms to new data
>     IDataView transformedNewData = dataPrepPipeline.Transform(newData);
> 
>     // Use the new data to train a new model
>     var retrainedModel = mlContext.Regression.Trainers.OnlineGradientDescent().Fit(transformedNewData, originalModelParameters);
> 
>     // Extract Model Parameters of retrained model
>     LinearRegressionModelParameters retrainedModelParameters = retrainedModel.Model as LinearRegressionModelParameters;
> 
>     // Inspect change in weights after retraining
>     var weightDiffs =
>         originalModelParameters.Weights.Zip(
>             retrainedModelParameters.Weights, (original, retrained) => original - retrained).ToArray();
> 
>     Console.WriteLine("Original | Retrained | Difference");
>     for (int i = 0; i < weightDiffs.Count(); i++)
>     {
>         Console.WriteLine($"{originalModelParameters.Weights[i]} | {retrainedModelParameters.Weights[i]} | {weightDiffs[i]}");
>     }
> }
> ```
> 
> Running this program should yield output similar to that below:
> 
> ```
> Original | Retrained | Difference
> 33039.86 | 56293.76 | -23253.9
> 29099.14 | 49586.03 | -20486.89
> 28938.38 | 48609.23 | -19670.85
> 30484.02 | 53745.43 | -23261.41
> ```

Hi @luisquintanilla ,
how can I use this model, when I create Prediction Engine from it, throws exception
```cs
mlContext.Model.CreatePredictionEngine<HousingData, HousingDataPrediction>(trainedModel);
```
![image](https://user-images.githubusercontent.com/38514356/74699173-047bed00-523b-11ea-8888-45a6513a6599.png)

**Comment by luisquintanilla** [comment]
Hi @maolin-kooboo,

I suspect you're having this issue because you called your column "Feature" instead of "Feature**s**".

**Comment by maolin-kooboo** [comment]
Hi @luisquintanilla ,
I was using the sample you provided above and added one line in the TrainAndSaveModel method after Train model, and I think the column is called 'Features' on the line 'Define data preparation estimator'.
```cs
static void TrainAndSaveModel(MLContext mlContext)
{
    // ....

    // Train model
    ITransformer trainedModel = trainingPipeline.Fit(preprocessedData);

    var engine = mlContext.Model.CreatePredictionEngine<HousingData, HousingDataPrediction>(trainedModel);

    // Save data preparation pipeline
    mlContext.Model.Save(preprocessor, data.Schema, "data_preparation_pipeline.zip");

    // Save trained model
    mlContext.Model.Save(trainedModel, preprocessedData.Schema, "ogd_model.zip");
}
```
```cs
        class HousingDataPrediction
        {
            float PredictedLabel { get; set; }

            float Score { get; set; }
        }
```

**Comment by luisquintanilla** [comment]
I see what you mean @maolin-kooboo 

The reason that's happening is because the `CreatePredictionEngine` uses the classes `HousingData` and `HousingDataPrediction` to determine the schema of the input / output columns. Since the model is trained on the preprocessed data, the input schema no longer matches `HousingData`. Therefore, you have to create a new class that defines this new input schema. 

```csharp
class PreprocessedHousingData
{
    [VectorType(4)]
    public float[] Features { get; set; }
}
```

This new schema contains the `Features` column created as part of our `dataPrepPipeline` which is a vector of size 4 (Size + 3 Historical Prices). 

Once you have this new class defining the schema for your preprocessed data, all you have to do is replace the input schema in the `CreatePredictionEngine` method with `PreprocessedHousingData`.

```csharp
var engine = mlContext.Model.CreatePredictionEngine<PreprocessedHousingData, HousingDataPrediction>(trainedModel);
```

**Comment by luisquintanilla** [comment]
I see what you mean @maolin-kooboo 

The reason that's happening is because the `CreatePredictionEngine` uses the classes `HousingData` and `HousingDataPrediction` to determine the schema of the input / output columns. Since the model is trained on the preprocessed data, the input schema no longer matches `HousingData`. Therefore, you have to create a new class that defines this new input schema. 

```csharp
class PreprocessedHousingData
{
    [VectorType(4)]
    public float[] Features { get; set; }
}
```

This new schema contains the `Features` column created as part of our `dataPrepPipeline` which is a vector of size 4 (Size + 3 Historical Prices). 

Once you have this new class defining the schema for your preprocessed data, all you have to do is replace the input schema in the `CreatePredictionEngine` method with `PreprocessedHousingData`.

```csharp
var engine = mlContext.Model.CreatePredictionEngine<PreprocessedHousingData, HousingDataPrediction>(trainedModel);
```

**Comment by maolin-kooboo** [comment]
@luisquintanilla , Thanks, it is working.
