### ISSUE TITLE
Missleading/Contradicting Documentation

### ISSUE THREAD

**Issue by dominikviererbe** [dotnet/docs#16778]
Under Default Options ist says:
"The ^ and $ language elements match the beginning and end of the input string."

Which is not entirely correct. As the folling Microsoft Documentation sates: $ "By default, the match must occur at the end of the string or before \n at the end of the string; in multiline mode, it must occur before the end of the line or before \n at the end of the line." (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference?view=netframework-4.8#anchors)

$ can also match before \n at the end of the input string.

This reddit post shows that many developers are not aware about this fact (including myself).
https://www.reddit.com/r/ProgrammerHumor/comments/erxnk2/i_think_someone_had_a_realy_bad_day_d/

Maybe you should add this pice of information oder link to the other documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9b6611-d08f-2fe9-216b-e0658d7f1553
* Version Independent ID: 3d3be892-b9b5-ca0b-1193-9fa49716decb
* Content: [Regular Expression Options](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options?view=netframework-4.8#feedback)
* Content Source: [docs/standard/base-types/regular-expression-options.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-options.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@dominikviererbe I think the documentation is correct. I'm not sure why the user in the reddit post is having a problem, but reading through the comments and examining what I can of that screenshot, it seems they are just missing something in their regex.

By default (not multiline mode) `$` represents the end of the string. This is what the article is stating in that list of facts, the default `None` options behavior.

Or maybe I'm not understanding what you mean? 😄 Can you provide me more information about what you mean?

**Comment by dominikviererbe** [comment]
@Thraka By Default `$` matches not just the end of input string, but also __before__ `\n` at the end of input string.

According to "The ^ and $ language elements match the beginning and end of the input string."

`System.Text.RegularExpressions.Regex.IsMatch("abc", "abc$")`
returns true

and

`System.Text.RegularExpressions.Regex.IsMatch("abc\n", "abc$")`
returns false

but in reality it also returns true.

**Comment by Thraka** [comment]
OK so the doc should be updated to clarify that case with something like:

```
The ^ and $ language elements match the beginning and end of the input string. The end of the input string can be a new line character.
```

**Comment by Youssef1313** [comment]
@adegeo Consider reopening this.

**Comment by adegeo** [comment]
Agreed. Thanks for bringing this back up.
