### ISSUE TITLE
Update F# Language Reference for F# 4.1 constructs

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1677]
F# 4.1 adds a lot of smaller things, mostly augmenting existing features.  There were also changes in the core library, but those are not documented here because they are part of an API reference.

### Struct stuff

- [x] Struct Tuples - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/tuples
- [x] Struct Records - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/records
- [x] Struct DUs - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/discriminated-unions
- [x] Structs (talk about the above and link to them) - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/structures

### Literals

- [x] Numeric Literals - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/values/

### Keywords

- [x] `fixed` support (perhaps new article)- https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/keyword-reference
- [x] Result (new article)
- [x] `namespace rec` and `module rec` - namespaces, modules, and perhaps new article about recursive definitions
- [x] Consuming `ref` returns - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/reference-cells
- [x] Optional Arguments (`Optional` and `DefaultValueParameter` attrs) - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/functions/ ??
- [x] SRTP (use type name in definition) - https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/generics/statically-resolved-type-parameters

### Misc
 - [x] `CallerInfo` argument attributes

**Comment by pblasucci** [comment]
In the discussion on structs, it might be worth noting when one can, or can _not_, explicitly control the layout of the struct. This technique is often used when inter-operating with unmanaged code (i.e. Platform/Invoke). It also makes for a very simple binary (de)serializer. From my informal tests, this is mostly a "gotcha" with multiple-case struct unions (as reported in #2647). However, I've not tested single-case struct unions or struct tuples. Meanwhile, struct records and struct classes (is that the correct term?) seem to behave as expected.

**Comment by cartermp** [comment]
#1916

**Comment by mairaw** [comment]
@cartermp is this done? all subtasks are marked as done.

**Comment by cartermp** [comment]
Yup!
