### ISSUE TITLE
Which version of Visual Studio supports SDK-style projects?

### ISSUE THREAD

**Issue by bhardwajs** [dotnet/docs#16787]
This question came up in an issue with CMake team. https://gitlab.kitware.com/cmake/cmake/issues/20227

CMake has generators for different versions of Visual Studio (VS, e.g., VS 2017, 2019, etc.) Which versions of VS support SDK-style projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks?source=docs#feedback)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Really this is a Visual Studio question but I remember them showing up in VS 2017. If it was a specific release within that year though, I don't know. Looking at the [whats new in VS 2017](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2017?view=vs-2017#net-core) it looks like .NET Core 2.0 was introduced in VS 2017 v15.3.

But you should know there are a few components to the SDK-style project. The SDK-style project is just a file format that Visual Studio, Visual Studio for Mac, and VSCode (among other IDEs) understand and use MSBuild to compile projects. You also have the target SDK and target framework, both indicated by the project file.

The SDK being used with Visual Studio is also dependent on a a specific version. The project shown in your CMake link is an SDK-style project, which is supported on VS 2017. However, the target framework is `netcoreapp3.1` which requires the .NET Core 3.1 SDK which is only supported by VS 2019 (and other IDEs have other specific version requirements)

I think that answers your question. If you have more, you may have a better chance getting a direct answer from the [Visual Studio Docs](https://github.com/MicrosoftDocs/visualstudio-docs/issues) github repo.
