### ISSUE TITLE
The second and third paragraphs

### ISSUE THREAD

**Issue by lbargaoanu** [dotnet/docs#16790]
I found those hard to read and understand.
I guess the second paragraph talks about .Net Standard, not about the Windows Compatibility Pack, because otherwise, it just seems wrong.
About the third paragraph. 

> not being able to use Windows-only technologies is only a migration hurdle with no architectural benefits.

 A sort of double negation here. Tricky :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf48b3f-5550-679d-4462-aeca2961b56e
* Version Independent ID: 18e36ec0-029d-804c-f500-aa9248af865a
* Content: [Use the Windows Compatibility Pack to port code to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack#feedback)
* Content Source: [docs/core/porting/windows-compat-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/windows-compat-pack.md)
* Product: **dotnet-core**
* GitHub Login: @terrajobst
* Microsoft Alias: **phcart**

**Comment by terrajobst** [comment]
Thanks for the feedback. I've submitted #16793 to address that.

**Comment by terrajobst** [comment]
Sorry, didn't see that @gewarren already submitted a suggestion. Will close mine.
