### ISSUE TITLE
update organizing your code topic to VS 2017

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1680]
The topic https://docs.microsoft.com/en-us/dotnet/articles/core/porting/project-structure still talks about xproj and VS 2015.

@conniey is that something you can help to update?

**Comment by mairaw** [comment]
And these are the related samples:
- https://github.com/dotnet/docs/tree/master/samples/framework/libraries/migrate-library/ (upgrade to VS 2017?)
- https://github.com/dotnet/docs/tree/master/samples/framework/libraries/migrate-library-xproj/
- https://github.com/dotnet/docs/tree/master/samples/framework/libraries/migrate-library-xproj-keep-csproj/
- https://github.com/dotnet/docs/tree/master/samples/framework/libraries/migrate-library-pcl

**Comment by conniey** [comment]
Hi @mairaw , is there a deadline for this document? I am currently working on a couple of other tasks but I can definitely update this.

**Comment by mairaw** [comment]
No, there's not a specific deadline. We're just trying to get everything moved to VS 2017/csproj land throughout the site. I can add a warning at the top of the page for now to say this hasn't been updated yet to the latest tooling. And please let me know if anything changes re. your availability. Thanks!
