### ISSUE TITLE
The example does not reveal the essence of "private set;" # 248

### ISSUE THREAD

**Issue by ticianaciminari** [dotnet/docs#16807]
@vctrro commented on [Wed Jan 22 2020](https://github.com/dotnet/docs.ru-ru/issues/248)

In this example, there is no difference between {get; } and {get; private set; }

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d549e670-9c25-f742-f146-699ba15e39e5
* Version Independent ID: 88fce03f-2ce8-0dd6-ae04-4676fcbb864d
* Content: [Практическое руководство. Реализация облегченного класса с автоматически реализуемыми свойствами (руководство по программированию на C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Wed Jan 22 2020](https://github.com/dotnet/docs.ru-ru/issues/248#issuecomment-577068547)

Hello, @vctrro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team, can you please check user's comment? Thanks in advance!

Microsoft DOCS International Team

**Comment by BillWagner** [comment]
This example isn't very compelling. Thanks for noting this.

The sample should be updated to include a mutable property with a private set to illustrate how other class members may modify state in those cases.

**Comment by ticianaciminari** [comment]
@vctrro FYI
