### ISSUE TITLE
Value Tag

### ISSUE THREAD

**Issue by wabtec-tcos-jpenrod** [dotnet/docs#16800]
How does the &lt;value&gt; tag differ from the &lt;summary&gt; tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71da79a-a782-7c7d-0091-e262c66b6fe4
* Version Independent ID: 1f662a67-3ade-26d7-c88a-aee7dd9f0320
* Content: [How to use the XML documentation features - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the question @wabtec-tcos-jpenrod 

The [value tag](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/value) is used for properties only, and is similar to the remarks tag.

Let me know if you want more information.
