### ISSUE TITLE
On Visual Studio 2019 .NET console app project, [View Application Events] button is not Available

### ISSUE THREAD

**Issue by ticianaciminari** [dotnet/docs#16804]
@egplantman commented on [Tue Jan 21 2020](https://github.com/dotnet/docs.ja-jp/issues/1662)

In the section "To log unhandled exceptions":

The "View Application Events" button was not available for .NET Framework console app projects created in Visual Studio 2019.

Also, the ApplicationEvents.vb file was not found in the project folder. I'd like to know the location of this file.

"To log an unhandled exception" section:
On my .NET Framework console application project, [View Application Events] button is not available.

Also, in my project folder, "ApplicationEvents.vb" is missing.
Could you tell us the file path?

I am sorry that I am not good at English, and not good at Github ...

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33c50630-612b-c8d8-7438-fd7219d66fc5
* Version Independent ID: 2a3eb119-d2c9-dbd9-23c1-30654751f24d
* Content: [方法: 例外をログに記録する - Visual Basic](https://docs.microsoft.com/ja-jp/dotnet/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions#to-log-an-unhandled-exception)
* Content Source: [docs/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

---

@srvbpigh commented on [Wed Jan 22 2020](https://github.com/dotnet/docs.ja-jp/issues/1662#issuecomment-576987897)

Hello, @egplantman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi team, can you please check user's comment? Thanks in advance!

Microsoft DOCS International Team

**Comment by mairaw** [comment]
@KathleenDollard can you please take a look at this feedback for one of the VB articles?
