### ISSUE TITLE
Merge the what's new in C# topics

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1682]
We currently have two what's new topics:
- https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/whats-new (migrated from msdn, not hookedup to the toc)
- https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new (new one created for the site)

We should merge the content of the two into the second one.

**Comment by BillWagner** [comment]
When you merge, let's keep this in reverse order: newest at the top, and previous versions below.

We should also move (and redirect) all those files to a 'whats-new' directory. (We should do this when we re-organize content and incorporate the migrated MSDN content).

**Comment by BillWagner** [comment]
Closing per PR #1757
