### ISSUE TITLE
Linux ARM support under linux-x64?

### ISSUE THREAD

**Issue by fvgithub** [dotnet/docs#16839]
Is the statement"Linux x64 can be used to compile Linux ARM32 and ARM64 images." on this page correct?
I would assume linux x64 is for intel x64 architecture and not ARM?
In any case: my linux x64 build does not work on ARM64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @fvgithub. @Thraka @richlander can you please take a look at this issue?

**Comment by Thraka** [comment]
@fvgithub This is saying you can use Linux x64 (intel) to compile a **ReadyToRun** binary that is built for Linux ARM32/64, but you wouldn't be able to build a Windows binary from Linux.

Put simply, for ReadyToRun images you have these restrictions:
- You can use Windows x64 to produce a Windows x64/ARM32/ARM64 binary.
- You can use Linux x64 to produce a Linux x64/ARM32/ARM64 binary.

But a normal non-ReadyToRun build can produce Linux binary from Windows or macOS. Or, Windows binary from Linux/macOS, etc.

You are still producing a binary that targets a specific platform. You can't use a binary produced for one OS/Platform on another. I'm in the middle of clarifying some of this information related to publishing, but you can find more information at https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

If you produce a binary with `dotnet publish -c Release` and no other options, a *dll* file is produced that can be used across platforms. However, any platform specific dependencies may be unavailable unless you also copy those to the target platform.

Does this answer your question?

**Comment by fvgithub** [comment]
Indeed, it looks clear to me now.

Your documentation and the RID info page was useful.

FYI: My confusion originated from the fact that I did not find 
linux-arm64 in the studio GUI (see screenshot)
And the linux-arm runtime target does not work on my arm64 jetson nano.
Commandline however the -r linux-arm64 builds the correct binary.
Is there a way to get that target in the VS GUI?

One sidenote: For my dotnetcore 3.1 sdk version the publish command 
seems to build FDD (.dll) and not FDE (.exe) as the documentation
https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli 
indicates.



Regards,
Frederic

|E:\tmp\testCSharpPlatformDepApp>dotnet publish --self-contained true -r 
linux-arm64 Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET 
Core Copyright (C) Microsoft Corporation. All rights reserved. Restore 
completed in 48.11 ms for 
E:\tmp\testCSharpPlatformDepApp\testCSharpPlatformDepApp.csproj. 
testCSharpPlatformDepApp -> 
E:\tmp\testCSharpPlatformDepApp\bin\Debug\netcoreapp3.1\linux-arm64\testCSharpPlatformDepApp.dll 
testCSharpPlatformDepApp -> 
E:\tmp\testCSharpPlatformDepApp\bin\Debug\netcoreapp3.1\linux-arm64\publish\ 
|

**Comment by Thraka** [comment]
Unfortunately the screenshots don't appear if you use an email reply.

On 3.0/3.1 publish will produce both the executable and dll file.

**Comment by Thraka** [comment]
I don't know much about configuring Visual Studio for that specific target, but you can always specify a default compile target (that isn't your current OS) with the `<RuntimeIdentifier>RIDVALUE</RuntimeIdentifier>` setting which is the same as specifying the `dotnet publish -r ` command line parameter.

**Comment by Thraka** [comment]
I'll close this issue now. If you have any more questions, feel free to ask!

**Comment by fvgithub** [comment]
OK, Thanks for the clarifications

Regards,
Frederic
