### ISSUE TITLE
Include expression to add or remove multiple projects on Windows

### ISSUE THREAD

**Issue by hectormartinezdev** [dotnet/docs#16838]
Hi!

I think that it will be useful to include the expression that is equivalent to `dotnet sln todo.sln remove **/*.csproj` in Windows, which is: `dotnet sln todo.sln remove (ls **/*.csproj)`. And also the one equivalent to the `add` example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#feedback)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@hectormartinezdev the command `dotnet sln todo.sln remove (ls **/*.csproj)` doesn't work on Windows. Is there a variant of it that you have seen work on Windows?

**Comment by hectormartinezdev** [comment]
I seen it working on PowerShell, not CMD. I do not know how to get it working on CMD.
