### ISSUE TITLE
machine-learning folder in samples repo

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16844]
I think the [machine-learning folder](https://github.com/dotnet/samples/tree/master/machine-learning) in samples repo isn't in the right place given that there is already a dedicated [machinelearning-samples](https://github.com/dotnet/machinelearning-samples/) repo. The folder isn't big. So, I think it makes sense to move that folder to the machinelearning-samples repo.

**Comment by luisquintanilla** [comment]
Hi @Youssef1313,

Thanks for the suggestion. This is definitely something we're planning on doing and have added it to our backlog.
