### ISSUE TITLE
[SUGGESTION] Use region for referencing code snippets

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16842]
Looking at https://github.com/dotnet/samples/blob/master/csharp/safe-efficient-code/ref-readonly-struct/Program.cs, a part of the file is referenced with the region name just like the commonly used way by comments (`// <SnippetName>`). I think regions is much better.

If you agree that regions is better, then there are two options:

1. If this can be automated, then one big PR that uses it everywhere would be okay.
2. If can't be automated, then my opinion is to use it for **new** samples and when **updating** old samples. Multiple PRs that only does this change don't look good I think.

Benefits:
1. More comfortable to external readers who see the code on GitHub and don't know how the code is referenced. Those comments will look strange to them, unlike the region which wouldn't seem strange.
2. ML.NET team currently uses reference by line numbers for the previous reason. By using region, - if the team liked it -, this will make things more maintainable than specifying line numbers, and will make the sample easier to read in GitHub. (https://github.com/dotnet/docs/pull/15837#issuecomment-553747161) cc: @luisquintanilla @natke 

@mairaw, Can you confirm that region would still work with the new syntax?

**Comment by mairaw** [comment]
The new guidance can be found here:
https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#code-include-references

Adding @rloutlaw to comment if the new syntax supports regions or not. We could test if there are any existing snippets that use region.
