### ISSUE TITLE
Link to e-book of this guide is missing

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/docs#16847]
In this page, a link is included for the _other_ e-book. I thought it was the e-book for this guide, so it took me some time to find the e-book that's actually published on GitHub [here](https://github.com/dotnet-architecture/eShopOnWeb/tree/master/docs).

I think it would be cool to include a link to that, as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae811ba0-e87d-2569-5b1d-e8493d933fa3
* Version Independent ID: 6fe4be5f-f5a5-7bb6-b78f-e4e5a758e540
* Content: [Architect modern web applications with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/)
* Content Source: [docs/architecture/modern-web-apps-azure/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/index.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@tiesmaster would something similar to this help? https://docs.microsoft.com/en-us/dotnet/architecture/microservices/#action-links

**Comment by tiesmaster** [comment]
@mairaw Absolutely, didn't see that section on the page for that book, but that's exactly what would be very nice to add. I'd put in a PR to update the docs, but I don't think I can make `aka.ms` shortening links, right?

**Comment by mdonatas** [comment]
Links to 3.1 version of the ebook can be found here: https://github.com/dotnet-architecture/eShopOnWeb/

**Comment by birbilis** [comment]
is this the direct link?
https://raw.githubusercontent.com/dotnet-architecture/eShopOnWeb/master/docs/Architecting%20Modern%20Web%20Applications%20with%20ASP.NET%20Core%20and%20Azure.pdf

**Comment by tiesmaster** [comment]
@birbilis I'd rather link to the link I provided in the issue description: https://github.com/dotnet-architecture/eShopOnWeb/tree/master/docs. Since that contains also other format (like epub, and mobi), besides the PDF you've linked.

@mdonatas I known where to find the e-book, I eventually found it. The nature of my issue is the discoverability of it. @mairaw suggested to do the same as the other Microservices book has: Action links. However, they contain `aka.ms` shortener links, which [I cannot make](https://techcommunity.microsoft.com/t5/it-resources-training/aka-ms-how-to/m-p/102039/highlight/true#M431), if I'm not mistaken. @mairaw Can you maybe make that happen?

**Comment by birbilis** [comment]
actually I commented since I couldn't find any action links like in that other book either:
1) could find an MS employee as it says to make the aka.ms link for you (if action links can only contain such, do they require so?)
2) could try reverse searching somehow to see if somebody has already created an aka.ms link for that url. Wonder if such a service is available by MS (a reverse search, aka (sic) get an already issued aka.ms link from a given URL) or if google/bind search could be used for that

**Comment by birbilis** [comment]
...so I searched in Google for
"with ASP.NET Core and Azure" site:aka.ms
and found https://aka.ms/webappebook
will that do?

**Comment by tiesmaster** [comment]
Ah, nice 😂 Good thinking :)

I suppose so. Thinking about it, the other one also only links to the PDF, and then the other line links to the repo where you can find all the ebooks. The other one also links to a Channel9 video, by changing `ebook` on the link to `-video`, so I also tried that, but that one didn't work unfortunately 😅 

Making a PR now ;)
