### ISSUE TITLE
Lack of table of contents severely hurts this page

### ISSUE THREAD

**Issue by tboby** [dotnet/docs#16853]
This page is very hard to read/navigate without the table of contents that was present in the original: 
https://fsharp.org/specs/component-design-guidelines/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b185b377-3bc4-49fe-fcc2-63500cc9d29e
* Version Independent ID: 5bd70365-b75b-5439-eb86-6a22e4f05684
* Content: [F# component design guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#appendix)
* Content Source: [docs/fsharp/style-guide/component-design-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/component-design-guidelines.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
The right-hand TOC is autogenerated by the docs system. I think the best course of action here is to request that it generates one level of markdown headings deeper (either automatically, on hover, or when clicking a `##`-level item in the right-hand TOC):

```
## This title will show today
### This subtitle will not
```

@gewarren can a request of that nature be made, or is there a duplicate feedback item we can tack on to?

**Comment by gewarren** [comment]
Interesting idea @cartermp. Let me put out some feelers. In the past, I've always manually created a "table of contents" for H3 headings when it's proven necessary - e.g. https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1#aspnet-core.

**Comment by mairaw** [comment]
Removed one of the labels since we can only have one org label per issue (olive color ones).

We had requested this before: https://github.com/MicrosoftDocs/feedback/issues/446
