### ISSUE TITLE
Figure 7-2 lost

### ISSUE THREAD

**Issue by chrsas** [dotnet/docs#16852]
Figure 7-2 lost

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d83855-4370-90e8-024a-12c5ac8220e9
* Version Independent ID: 672b1fcf-9f2d-de01-4ee1-e8a4d5418ff4
* Content: [Applying CQRS and CQS approaches in a DDD microservice in eShopOnContainers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice?source=docs#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
@nishanil maybe we could include a sentence about the figure being on the previous article? It can be a bit confusing if someone lands on this page from search.
