### ISSUE TITLE
8.0 specification

### ISSUE THREAD

**Issue by pareshjoshi** [dotnet/docs#16889]
Can you please upload latest language specification for C# (I guess version 8.0). What I can see here are proposals rather than specification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/#feedback)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I think that they are still proposals since the standard hasn't been updated yet, even though they have been implemented in C# 8. But I'll let @BillWagner confirm.

**Comment by pareshjoshi** [comment]
It will be good if specs are updated. For example, interface can now have default implementation for its methods.

**Comment by BillWagner** [comment]
We are working to update them. There's quite a backlog, so it will take some time.
