### ISSUE TITLE
Substituting the Entire Match

### ISSUE THREAD

**Issue by DonFrazier** [dotnet/docs#16882]
This section shows the plain text without any special characters matching the output.  Seems like there should be some ampersands in the original

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e4ab41-3d66-76f0-1ae8-a9818a199583
* Version Independent ID: b35b11b7-5c7f-0985-dd62-aecfd48d1490
* Content: [Substitutions in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions)
* Content Source: [docs/standard/base-types/substitutions-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/substitutions-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@DonFrazier Can you be more specific about which section/example you're talking about? If you have an idea of a fix, you can also submit a fix directly by clicking the edit button on the article's top-right area.

**Comment by DonFrazier** [comment]
URL: https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions
Heading on Page: Substituting the Entire Match
Direct Link: https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions#substituting-the-entire-match

```
using System;
using System.Text.RegularExpressions;

public class Example
{
   public static void Main()
   {
      string pattern = @"^(\w+\s?)+$";
      string[] titles = { "A Tale of Two Cities",  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                          "The Hound of the Baskervilles", 
                          "The Protestant Ethic and the Spirit of Capitalism", 
                          "The Origin of Species" };
      string replacement = "\"$&\""; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      foreach (string title in titles)
         Console.WriteLine(Regex.Replace(title, pattern, replacement));
   }
}
// The example displays the following output:
//       "A Tale of Two Cities" <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
//       "The Hound of the Baskervilles"
//       "The Protestant Ethic and the Spirit of Capitalism"
//       "The Origin of Species"
```

The original strings don't have any occurrences of the character being replaced.  The "following output" is an exact copy of the input.

**Comment by Thraka** [comment]
Reading the paragraph it says 

>The following example uses the $& substitution to **add quotation marks at the beginning and end** of book titles stored in a string array.

I tested the code and " is added to the start and end of the string.

Prior to that it indicates that 

>The $& substitution includes the entire match in the replacement string

So the example isn't going to add & the $& represents the matched string. Try changing the code to be `string replacement = "ABC $& ABC"` and you'll see the output become:

```
ABC A Tale of Two Cities ABC
ABC The Hound of the Baskervilles ABC
ABC The Protestant Ethic and the Spirit of Capitalism ABC
ABC The Origin of Species ABC
```

I'm going to close this issue as I think your question is answered. Let me know if you have further questions.
