### ISSUE TITLE
Retire Extensibility model article but salvage useful parts

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#16901]
Related to #10245

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb01ddcf-dbb2-5af4-e283-9801c9b0dd4c
* Version Independent ID: 00852544-b692-b981-63b9-fc3a9ec048af
* Content: [.NET Core CLI extensibility model - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#feedback)
* Content Source: [docs/core/tools/extensibility.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/extensibility.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by wli3** [comment]
The only useful part is [custom-targets](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#custom-targets) section. Although some detail is still outdated.

At the same time, I have a [feature request](https://github.com/microsoft/msbuild/issues/5068) in msbuild to make this experience less manual. cc @KathleenDollard @rainersigwald
