### ISSUE TITLE
Additional deployment information needed

### ISSUE THREAD

**Issue by vlkuznet** [dotnet/docs#16904]
There are a few elements we may wish to note here to assure that the application works properly when deployed to Azure:
+The demo app must be run in 64 bit mode, and Functions will default to 32 bit. 
+In my experimentation, I was only able to get this running in Azure when building in "self-contained" mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a62e0b-bb0f-3bee-1842-aac9e0a158cd
* Version Independent ID: f93d20ff-ceff-eb17-f53e-1f473b19c2af
* Content: [Deploy a model to Azure Functions - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-serverless-azure-functions-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/serve-model-serverless-azure-functions-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-serverless-azure-functions-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @vlkuznet ,

Sorry to hear you ran into issues. When you deployed did you do it through Visual Studio? If so, which version were you using (2017 or 2019)?

**Comment by vlkuznet** [comment]
Hi @luisquintanilla ,

This was done in VS 2019 Enterprise. I briefly discussed this with you over Teams - I believe you were not able to confirm that self-contained mode was required; but you did confirm that 64-bit _was_ required. 

I would think that a one-sentence addition noting that this requires x64 would be prudent here. 

Let me know if I'm missing something regarding self-contained deployment, or if I can do anything further to help with investigating that front.

Thanks,
Vlad
