### ISSUE TITLE
Add this link to check installs ?

### ISSUE THREAD

**Issue by stephenhauck** [dotnet/docs#16911]
https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#install-the-net-core-sdk)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thanks, I'll add this.
