### ISSUE TITLE
Add output to show results of code example

### ISSUE THREAD

**Issue by scottb-isp** [dotnet/docs#16917]
It would be helpful if the example code above was followed by examples of the output scenarios.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b82de3-3121-209c-6dc4-6267f726dcfe
* Version Independent ID: 7c19d7e6-f241-2f7e-9dad-737df8328663
* Content: [nameof operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof#feedback)
* Content Source: [docs/csharp/language-reference/operators/nameof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/nameof.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@scottb-isp could you please elaborate? The example code contains the output.

**Comment by scottb-isp** [comment]
Oh. I see the output as comments now that you state it. I looked _underneath_ each of the examples thinking to find the output in a separate block. Perhaps a more standard approach would be to have an output block following the example. I guess this works as comments. I missed them.

**Comment by pkulikov** [comment]
Both ways are used throughout the docs. To me, comments on the same line are easier to match with the code.

By the way, there is the Run button at the top right corner of the code block, so you also can run the code yourself.

**Comment by scottb-isp** [comment]
Too funny, I looked for that too and missed it! I was actually focused on the Property example on the lower portion if the page where there's no output to demonstrate the example, and no Run button.  Everything I wanted is at the top of the page but my eye skipped it.

**Comment by BillWagner** [comment]
Thanks for writing this.

We typically use comments for the output, because code won't be localized when docs are translated into different languages. That way, the output matches the code. 

I'll close this as answered.
