### ISSUE TITLE
Contradicting documentation for dotnet test

### ISSUE THREAD

**Issue by toqueteos** [dotnet/docs#16912]
The documentation displayed at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test does not match the one that get's shown when you do `dotnet test --help`.

The webpage states that options go AFTER the project filepath:
![image](https://user-images.githubusercontent.com/699969/73540655-cdcb6780-4430-11ea-8ef6-b969508723aa.png)

The CLI states that options go BEFORE the project filepath:
![image](https://user-images.githubusercontent.com/699969/73540685-e20f6480-4430-11ea-9980-f96524d17d8f.png)

Also, the project is shown as optional in the webpage and mandatory in the CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21#examples)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@toqueteos Thanks for pointing that out. We'll investigate and fix it.

**Comment by tdykstra** [comment]
Options can go before or after the project file path, so it's just a difference in format between help text and doc.

The help text doesn't put the PROJECT|SOLUTION argument in brackets but the text explains that it could be omitted.

I did find some discrepancies in the options listed in help vs. the doc -- #17264 will fix those.

**Comment by toqueteos** [comment]
Thank you! I'll recheck why my test were not running.
