### ISSUE TITLE
The order of GradeLevel is not correct

### ISSUE THREAD

**Issue by JeffgLiu** [dotnet/docs#16928]
We have declared:
protected enum GradeLevel { FirstYear = 1, SecondYear, ThirdYear, FourthYear };
Why is the result in the order of SecondYear, ThirdYear, FirstYear, FourthYear?
Should it be FirstYear, SecondYear, ThirdYear, FourthYear? Is this a bug? What should I do if I want it in the declared enum order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b8960-bd9b-6e47-0697-1ede60319dcc
* Version Independent ID: f2080e9b-3a61-ec89-eb34-b61aff1641fa
* Content: [Create a nested group (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/create-a-nested-group#feedback)
* Content Source: [docs/csharp/linq/create-a-nested-group.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/create-a-nested-group.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JeffgLiu** [comment]
Never mind, I have fixed it. But the original one does have a bug. Here is the solution:

var queryNestedGroups = from student in students
				 	group student by student.Year into newgroup
					from interiorGroup in
						(from orderedStudent in newgroup
						group orderedStudent by orderedStudent.LastName)
					group interiorGroup by newgroup.Key into outerGroup
					orderby outerGroup.Key
					select outerGroup;

This orderby clause will force the outer group to be ordered according to FirstYear, SecondYear, ThirdYear, FourthYear.

**Comment by BillWagner** [comment]
Thanks for posting the solution @JeffgLiu 

I'll close this as answered.
