### ISSUE TITLE
It is not mentioned that co(ntra)variance is not supported in value types.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/docs#16925]
https://stackoverflow.com/questions/12454794/why-covariance-and-contravariance-do-not-support-value-type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72dc0c-5129-34c5-7ddb-49b1e38c0990
* Version Independent ID: 9bd5372c-c461-dbcd-1acc-6e03451b49c7
* Content: [Covariance and Contravariance (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/covariance-contravariance/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this and providing the link @teo-tsirpanis 

I've added this to our  backlog, and added the "up for grabs" label because this is a good issue for interested community members to consider.
