### ISSUE TITLE
Examples in Vb.NET

### ISSUE THREAD

**Issue by afrahimi** [dotnet/docs#16926]
Can you please provide the examples in VB.NET?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @afrahimi 

Thank you for your suggestion. Unfortunately this is not part of our roadmap at the moment. The current C# samples should translate conceptually to VB syntax. Feel free to let us know if there's a specific scenario you run into problems with.
