### ISSUE TITLE
Provide guidelines for choosing RIDs when building a library

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#1693]
The section "How to use native dependencies" at https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries says:

> Specifying a Runtime Identifier (RID) in a runtimes section.

with a reference to the RID catalog: https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog.

Some things worth covering are.
- packages with native dependencies should use an rid that includes an architecture (e.g osx-x64, not osx)
- users should try to target the highest RID in the graph they can. When they target a leaf (e.g. ubuntu.14.04-x64) it means their package will only work on that specific system. So it should have a specific dependency.
- the c-library dependency of linux rids should be explained (cfr https://github.com/dotnet/coreclr/issues/9208)

Suggestion:
Perhaps this can be explained with an example of when to use `linux`, `linux-x64`, `ubuntu.14.04.x64`.
Then the glibc dependency of linux-x64 can then be explained. And the other c-library RIDs can be mentioned as well.
This documentation could be in the _libraries_ document. The list of all c-library RIDs could be in he _rid-catalog_.

CC @Petermarcu

**Comment by BillWagner** [comment]
closing as much of this is added in .NET standard discussions.
