### ISSUE TITLE
Publish roslyn API docs from the roslyn wiki

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#16930]
The roslyn wiki has a number of useful resources for developers starting to write analyzers and code fixes. These should move to docs under the .NET Compiler SDK node.

The two most important would be the [FAQ](https://github.com/dotnet/roslyn/blob/master/docs/wiki/FAQ.md). Each code-related question in this FAQ pointed to a sample unit test demonstrating how to solve some problem using Roslyn APIs. The samples have been removed, but still exist in the source history – https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Samples/CSharp/APISampleUnitTests/FAQ.cs (there’s an equivalent FAQ.vb in a parallel location in the source tree).

/cc @jmarolf

**Comment by jmarolf** [comment]
These samples now live here: https://github.com/dotnet/roslyn-sdk/blob/master/samples/CSharp/APISamples/FAQ.cs
