### ISSUE TITLE
New method to find .NET global tools

### ISSUE THREAD

**Issue by marcusturewicz** [dotnet/docs#16933]
I have created a free open source website to specifically search for .NET global tools:

https://www.toolget.net

Source code: https://github.com/marcusturewicz/toolget

If deemed useful, it would be worth listing this in the section "Find a .NET Core Global Tool".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET Core Global Tools - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#feedback)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
Thank you @marcusturewicz for your suggestion. @KathleenDollard what do you think?

**Comment by marcusturewicz** [comment]
Here's a blog post I did on it for more context https://dev.to/marcusturewicz/search-for-net-global-tools-with-toolget-3d7d.

**Comment by KathleenDollard** [comment]
Adding @wli3 

First cool! Yes, let's add this to the find tools section! Nice site and thanks for letting us know. 

Second, I think we are rewriting this page, and I could not find the link. Let's make sure it makes both places. 

Marcus, so you're not surprised, we are working on `dotnet tool search` for .NET 5. We were waiting for NuGet to do an API update for us. That update is now live, and you may be using it (which is awesome). Once that is out, you can decide if it removes the need for your tool. I don't think it does, at least until/unless NuGet puts package type in their search. 

Also, we are gradually moving away from the phrase ".NET global tools" to ".NET Tools". In the beginning, the most important thing was differentiating them from DotNetCliToolReference (nor deprecated) and now we are leaning into helping people understand that it is one kind of tool that can be installed three ways: global, local and tool-path. You can incorporate that thinking/naming as you like going forward.

**Comment by wli3** [comment]
It is checked in https://github.com/dotnet/sdk/issues/10620

**Comment by marcusturewicz** [comment]
Thanks Kathleen, glad it seems useful! I will update the phrasing in the repo, live site and blog post to refer to ".NET Tools".

I'll keep the site live running for now and see what happens with NuGet Gallery in terms of .NET Tools search functionality. If they incorporate that, I will likely shut down my site.

**Comment by mairaw** [comment]
@tdykstra is working on the updates but I created a quick PR to add this tool and a note about the new command: #17055
