### ISSUE TITLE
Missing C# compiler warnings

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#16943]
id: CS1998
title: Async method lacks 'await' operators and will run synchronously

id: CS8600
title: Converting null literal or possible null value to non-nullable type.

id: CS8601
title: Possible null reference assignment.

id: CS8602
title: Dereference of a possibly null reference.

id: CS8604
title: Possible null reference argument.

id: CS8610
title: Nullability of reference types in type of parameter doesn't match overridden member.

id: CS8611
title: Nullability of reference types in type of parameter doesn't match partial method declaration.

id: CS8613
title: Nullability of reference types in return type doesn't match implicitly implemented member.

id: CS8618
title: Non-nullable field is uninitialized. Consider declaring as nullable.

id: CS8619
title: Nullability of reference types in value doesn't match target type.

id: CS8621
title: Nullability of reference types in return type doesn't match the target delegate.

id: CS8622
title: Nullability of reference types in type of parameter doesn't match the target delegate.

id: CS8625
title: Cannot convert null literal to non-nullable reference type.

id: CS8632
title: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

id: CS8634
title: The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'class' constraint.

id: CS8655
title: The switch expression does not handle some null inputs.

id: CS8667
title: Partial method declarations have inconsistent nullability in constraints for type parameter

id: CS8670
title: Object or collection initializer implicitly dereferences possibly null member.

id: CS8714
title: The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.

id: CS8762
title: Parameter may not have a null value when exiting in some condition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc586192-534e-0108-d265-c4f2f6947c57
* Version Independent ID: 4d39f536-5d78-335b-3525-d4b581c28fdc
* Content: [C# Compiler Errors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/)
* Content Source: [docs/csharp/language-reference/compiler-messages/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Hi @paulomorgado Thank you for pointing out these gaps in our documentation. If you have more to report, please put them all in one issue, as that will be a more efficient way to keep track of them.

**Comment by mairaw** [comment]
I was thinking the same. Should we close them all and keep just one with a list of all missing?

**Comment by tdykstra** [comment]
That's a good idea, wish I thought of it sooner. 😄

**Comment by paulomorgado** [comment]
I'm OK with that.

@BillWagner didn't seem to mind.

**Comment by tdykstra** [comment]
@paulomorgado I can do the consolidation, unless you would rather do it.

**Comment by paulomorgado** [comment]
No problem! go ahead and do it.

**Comment by BillWagner** [comment]
Thanks team.  I like the 1 issue plan (I was getting to the airport, so hadn't commented.

**Comment by mairaw** [comment]
I'm glad you approved it 😄

**Comment by shubhdevf** [comment]
Is there an estimate for when the documentation on these issues will be available here?

**Comment by tdykstra** [comment]
Not yet. We've been focusing on higher-priority issues.
