### ISSUE TITLE
Add more information to the Frameworks and Targets topic

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1694]
Topic: https://docs.microsoft.com/en-us/dotnet/articles/standard/frameworks

Proposal:
Rename that topic to Target Frameworks
Add list of supported TFMs (similar to what we have in this topic over in the [NuGet docs](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks))
Link to this topic where we mention the target framework, TFMs, etc. For example, a bunch of commands like dotnet-build, dotnet-run have the framework option.

**Comment by GuardRex** [comment]
@mairaw 

> Rename that topic to Target Frameworks

Just the topic title, correct? I can leave the file name (`frameworks.md`) as it is, correct?

> Link to this topic where we mention the target framework, TFMs, etc. For example, a bunch of commands like dotnet-build, dotnet-run have the framework option.

Assuming the file name and URL don't change here (just the title), would you like me to run back over to #1705 and add links to this doc before that PR goes in? If so, I'll do that first (now).
