### ISSUE TITLE
Missing the real advantage of finally

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#16942]
I think the most advantage of the `finally` block is to run even if the `try` block includes a `return` statement, or if the `catch` block `throw`s the exception, etc'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd59701-079e-fdda-0c47-290f24f9eb4e
* Version Independent ID: a6f2953b-0da7-19fd-e121-aaeb65f60b17
* Content: [try-finally - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally?source=docs#feedback)
* Content Source: [docs/csharp/language-reference/keywords/try-finally.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-finally.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Thanks for the suggestion. We'll add a note about that the next time we update the try-finally or try-catch-finally articles.
