### ISSUE TITLE
NotNullAttribute on generic type parameter?

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet/docs#16940]
Let's say I have a function that simply removes all `null` values from a `IEnumerable<T>`
``` C#
IEnumerable<T> RemoveNull<T>(IEnumerable<T> enumerable)
{
    foreach (var item in enumerable)
    {
        if (!(item is null)) yield return item;
    }
}

```

How do i indicate that `T` in the return value is never `null`?
I tried indicating the return value as `IEnumerable<[NotNull]T>` and `IEnumerable<T!>` but both gave me an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17290c4d-73f0-5ae1-e8ba-c039fe9fe9ca
* Version Independent ID: 59e0e3bb-b2e5-3ced-72d9-42e641b3897f
* Content: [Upgrade APIs for nullable reference types with attributes that define expectations for null values](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes)
* Content Source: [docs/csharp/nullable-attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @cartermp Do you know the answer here?

**Comment by cartermp** [comment]
Currently there's no way to do this. It's the same problem as `Task<T>`-returning APIs. The work to solve this is slated for .NET 5, though.

**Comment by gtbuchanan** [comment]
I just ran into this issue myself. Good to see an official response. ReSharper has traditionally handled this with [`ItemNotNullAttribute`](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ItemNotNullAttribute) so hopefully, we'll have a similar option in .NET 5.
