### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by ticianaciminari** [dotnet/docs#16965]
@carmineelia commented on [Sun Feb 02 2020](https://github.com/dotnet/docs.it-it/issues/76)

It would seem that
the code 

services.AddDbContext&lt;CatalogContext&gt;(options =&gt;

must be replaced by

services.AddDbContext&lt;DbContext&gt;(options =&gt;

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 376577d9-c559-9d5d-e263-ff9f0fb6ac27
* Version Independent ID: ab3bbb06-6a80-d6d7-8060-9b93ad8b1f3e
* Content: [Creazione di un microservizio CRUD semplice basato sui dati](https://docs.microsoft.com/it-it/dotnet/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice.md](https://github.com/dotnet/docs.it-it/blob/live/docs/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

---

@srvbpigh commented on [Sun Feb 02 2020](https://github.com/dotnet/docs.it-it/issues/76#issuecomment-581189700)

Hello, @carmineelia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check the report from user?

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by jalal-sh** [comment]
@carmineelia nope, the code is correct, you should specify exactly which DbContext you're injecting (CatalogContext in this case)

**Comment by Thraka** [comment]
The problem may be that the paragraphs introducing the code speak in both generalities and in specifics.

>In the example above of the `CatalogController` class, we are injecting an object of `CatalogContext` type plus other objects through the `CatalogController()` constructor.
>
>An important configuration to set up in the Web API project is the `DbContext` class registration into the service's IoC container. You typically do so in the Startup class by calling the `services.AddDbContext<DbContext>()` method inside the `ConfigureServices()` method, as shown in the following example:

It does talk about `CatelogContext` but then starts talking about `DbContext` but then mixes both the generic `DbContext` with the specific variable of `services`: `services.AddDbContext<DbContext>()`

Really that inline code should be changed to `services.AddDbContext<CatalogContext>()` and then demonstrated in the code block that follows.

**Comment by sughosneo** [comment]
Hi @ticianaciminari, @Thraka , thank you for the feedback. 
We are in the process of updating the doc. You should see the changes shortly.
