### ISSUE TITLE
Document that "f" and "F" cannot be used in combination.

### ISSUE THREAD

**Issue by midspace** [dotnet/docs#16968]
I would have hoped that I could display a date time with a minimum of 3 digits of milliseconds and a maximum of 6 digits, but unfortunately this doesn't appear to be supported.

mm:fff will produce:
2009-06-15T13:45:30.6174000 -&gt; 30:617

As the documentation doesn't indicate, the expected result of mm:fffFFF could well have been, but isn't:
2009-06-15T13:45:30.6174000 -&gt; 30:6174
2009-06-15T13:45:30.6100000 -&gt; 30:610

Instead, mm:fffFFF will produce:
2009-06-15T13:45:30.6174000 -&gt; 30:617617

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
I don't think you can use anything in "combination" in that way. Formatting a string means using it as a template. Wherever f is in the string it replaces it with the seconds fraction. Wherever F is, it replaces it with the seconds fraction.

Also, F says that it trims trailing 0's so it wouldn't work for you even if you could combine them some how. 😞
