### ISSUE TITLE
HashAlgorithm.Create(string) no longer throws

### ISSUE THREAD

**Issue by pushkin-** [dotnet/docs#16978]
`HashAlgorithm.Create(string)` is apparently supported now as per [this PR](https://github.com/dotnet/corefx/pull/28385), but the docs still say that it will throw.

Either the docs should be updated, or we might need multiple docs for different .NET Core version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6487cae-3320-584d-6c27-fc712ec03e72
* Version Independent ID: 846981e7-bc47-0df8-8621-22282de18ef3
* Content: [Unsupported APIs on .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis#feedback)
* Content Source: [docs/core/compatibility/unsupported-apis.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/unsupported-apis.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@pushkin- Thanks for noting this. If I understand [the code](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs#L21) correctly, Create() still throws PNSE but Create(String) doesn't. @bartonjs Could you confirm?

**Comment by bartonjs** [comment]
That is correct.  There's no "platform default HashAlgorithm", but `Create(string)` calls into CryptoConfig like .NET Framework did
