### ISSUE TITLE
Typo in the See also section

### ISSUE THREAD

**Issue by bjeans** [dotnet/docs#16972]
How to dsplay command line arguments - spelling mistake in the word display.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 799f3460-8d63-76ac-0f6b-8dc09840da09
* Version Independent ID: 777bcccf-fc8b-5a95-114f-9a2e74e33318
* Content: [Command-Line Arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/command-line-arguments#feedback)
* Content Source: [docs/csharp/programming-guide/main-and-command-args/command-line-arguments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/main-and-command-args/command-line-arguments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @bjeans I just submitted a PR to address the issue.

In the future, if you see these small issues, you can click the pencil icon to submit the fix, which may save you time in getting this fixed.
