### ISSUE TITLE
An attempt at some humor

### ISSUE THREAD

**Issue by xenophilios** [dotnet/docs#16989]
I notice that sixteen people have contributed to this article. Isn't there a proverb about too many cooks...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by WilliamVannuffelen** [comment]
Hah, you made me chuckle at least.
Though I will say I found this article to be particularly well-written. The too many cooks principle doesn't apply imho!

**Comment by xenophilios** [comment]
Hi William,

 

I didn't mean to imply that the article was bad. I was just referring to the example of cooking breakfast. I should have been more careful to avoid this misunderstanding. Sorry!

 

With best regards,

 

Eric

**Comment by BillWagner** [comment]
I like it @xenophilios 

I'm glad you found this helpful. 

Just to clarify, the list of contributors includes everyone in the commit history for an article. That includes edits that made it better once the original version was published. We are making sure to recognize the community contributors that spot and fix issues.

I'll close this as kudos.

**Comment by xenophilios** [comment]
Kudos is a good interpretation of my intentions. I was trying to be funny in connection with the example of cooking breakfast with three or four cooks working in parallel.
