### ISSUE TITLE
Initial extension member example is incorrect

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/docs#16983]
```
[<Extension>]
type Extensions() =
    [static] member self-identifier.extension-name (ty: typename, [args]) =
        body
    ...
```
static is not optional and each member should be annotated with [&lt;Extension&gt;]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640cc89f-e2da-021c-daf3-68f6772ffabf
* Version Independent ID: 1df801b1-3a11-0aa5-44d7-78c5e2751393
* Content: [Type Extensions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/type-extensions#feedback)
* Content Source: [docs/fsharp/language-reference/type-extensions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/type-extensions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by NinoFloris** [comment]
Thanks @cartermp

**Comment by cartermp** [comment]
yeet
