### ISSUE TITLE
Mix up of covariant and contravariant in example for Generic Delegates with Variant Type Parameters

### ISSUE THREAD

**Issue by mahmoudkassem** [dotnet/docs#16982]
According to the definitions given at the top of the page 

```
Covariance :

Enables you to use a more derived type than originally specified.

You can assign an instance of IEnumerable<Derived> (IEnumerable(Of Derived) in Visual Basic) to a variable of type IEnumerable<Base>.
```

```
Contravariance :

Enables you to use a more generic (less derived) type than originally specified.

You can assign an instance of Action<Base> (Action(Of Base) in Visual Basic) to a variable of type Action<Derived>.
```

They have been mixed up in this example:

```cs
public class Base {}
public class Derived : Base {}

public class Program
{
    public static Derived MyMethod(Base b)
    {
        return b as Derived ?? new Derived();
    }

    static void Main() 
    {
        Func<Base, Derived> f1 = MyMethod;

        // Covariant return type.
        Func<Base, Base> f2 = f1;
        Base b2 = f2(new Base());

        // Contravariant parameter type.
        Func<Derived, Derived> f3 = f1;
        Derived d3 = f3(new Derived());

        // Covariant return type and contravariant parameter type.
        Func<Derived, Base> f4 = f1;
        Base b4 = f4(new Derived());
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e47b2d-ee75-bd2e-4857-7704af641a2a
* Version Independent ID: 8055442b-8ecf-e869-3e48-a5c4ee5207a1
* Content: [Covariance and Contravariance in Generics](https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance)
* Content Source: [docs/standard/generics/covariance-and-contravariance.md](https://github.com/dotnet/docs/blob/master/docs/standard/generics/covariance-and-contravariance.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mahmoudkassem** [comment]
Sorry, the mixup was on my part.

**Comment by BillWagner** [comment]
No worries @mahmoudkassem 

I'm glad you got it sorted. (I still have to look it up when delegates are involved. This is a complicated concept.)

**Comment by mahmoudkassem** [comment]
Thank you for being considerate.
