### ISSUE TITLE
Add a portion on why c# has checked and unchecked exceptions for people new to C#, just to make things more clear. 

### ISSUE THREAD

**Issue by jasonalls** [dotnet/docs#16994]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbca89d-149d-f904-bbec-71446bfa5506
* Version Independent ID: 6ce3ce8d-a80c-81aa-2d16-b2fec0d8a89a
* Content: [Checked and Unchecked - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked-and-unchecked)
* Content Source: [docs/csharp/language-reference/keywords/checked-and-unchecked.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/checked-and-unchecked.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
reopening. (I clicked the wrong button) 🤦‍♂
