### ISSUE TITLE
.Net Core versions wrong

### ISSUE THREAD

**Issue by jmichas** [dotnet/docs#16993]
You state "This is temporary, because all Azure services will eventually use .NET Core.". This contradicts the Azure Mobile Server SDK stating it will not be upgrading to .Net Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd6c575-bd46-941d-138a-c705043f16e6
* Version Independent ID: 5b6081ff-c221-851f-a3fb-63d4f2aa1b44
* Content: [When to choose .NET Framework for Docker containers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-framework-container-scenarios#feedback)
* Content Source: [docs/architecture/microservices/net-core-net-framework-containers/net-framework-container-scenarios.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/net-core-net-framework-containers/net-framework-container-scenarios.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
@jmichas Thank you for the heads up! We have rephrased the sentence in the PR. Closing this issue now.
