### ISSUE TITLE
WebClient.CancelAsync doesn't work in .NET Core

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#16990]
Add WebClient.CancelAsync to this page as a breaking change.

See https://github.com/dotnet/dotnet-api-docs/issues/3777.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b64784-415c-7d00-3c44-aa3de496a54f
* Version Independent ID: 3d9c2faa-a7d7-ee5f-6f3c-87da5782a5cb
* Content: [Breaking changes - .NET Framework to .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core)
* Content Source: [docs/core/compatibility/fx-core.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/fx-core.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I don't actually have enough info to document this breaking change yet, for example which version of .NET Core it was introduced in. @karelz Could you or someone else fill out the [breaking change template](https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md)?

**Comment by karelz** [comment]
I am pretty sure, this originated with .NET Core 1.0.
@aik-jahoda can you please help to document this difference once you get to documentation changes? Thanks!

**Comment by karelz** [comment]
@aik-jahoda can you please confirm and help to fill the breaking change template? https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md
Thanks!

**Comment by aik-jahoda** [comment]
@karelz I will fill it

**Comment by aik-jahoda** [comment]
There is the breaking change issue: https://github.com/dotnet/docs/issues/18250

**Comment by gewarren** [comment]
Closing this. Thanks for adding the BC!
