### ISSUE TITLE
Missing information about nullable value type equality comparison

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/docs#16998]
The MSDN page http://msdn.microsoft.com/en-us/library/2cf62fcy.aspx documents what happens with comparison operators and nullable value types, but doesn't explicitly call out what happens with equality operators.

[This StackOverflow answer](https://stackoverflow.com/a/15777768/88374) links to the page with a snippet that has been removed:

> When you perform comparisons with nullable types, if the value of one of the nullable types is `null` and the other is not, all comparisons evaluate to `false` except for `!=`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e65a97-5e33-ab78-cd40-b20c3219ca2f
* Version Independent ID: 1ae0aed9-e565-44ae-aebe-c55a0a02c2c5
* Content: [Nullable value types - C# reference](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/builtin-types/nullable-value-types#lifted-operators)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/nullable-value-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@citizenmatt thanks for reporting; I'll update the page accordingly.

**Comment by BillWagner** [comment]
Thanks for reporting that @citizenmatt 

I reviewed that update, and missed that change.
Thanks @pkulikov for offering to address this.
