### ISSUE TITLE
There is no example in Span<T>.GetPinnableReference()

### ISSUE THREAD

**Issue by aybe** [dotnet/docs#17002]
The example is right above in fact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe1ee66-e839-82f5-16fa-fc1f9f66c787
* Version Independent ID: eeabec3f-826b-7d84-0d54-7a9df7e57d2a
* Content: [fixed Statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/fixed-statement?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(fixed_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue#feedback)
* Content Source: [docs/csharp/language-reference/keywords/fixed-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/fixed-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @aybe 

I'll add this to our backlog to update this article.

**Comment by pkulikov** [comment]
@BillWagner I think the API page of `Span<T>` should be updated, not this article about `fixed`.

The article says:
> Any type that implements a method named GetPinnableReference can be pinned. The GetPinnableReference must return a ref variable of an unmanaged type. The .NET types System.Span<T> and System.ReadOnlySpan<T> introduced in .NET Core 2.0 make use of this pattern and can be pinned. This is shown in the following example:
> ...
>If you are creating types that should participate in this pattern, see Span<T>.GetPinnableReference() for an example of implementing the pattern.

However, [Span<T>.GetPinnableReference()](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.getpinnablereference?view=netcore-3.1#System_Span_1_GetPinnableReference) has no example of how to implement the pattern.

@aybe do I understand you correctly?

**Comment by BillWagner** [comment]
@pkulikov Do you think the example would be better in this article, or in the API reference article?

**Comment by aybe** [comment]
@pkulikov yes

**Comment by pkulikov** [comment]
> @pkulikov Do you think the example would be better in this article, or in the API reference article?

I think the example would fit better in this article about the `fixed` keyword, as it introduces and talks about the pattern.

Also, what about linking the *actual* implementation:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Span.cs#L259-L270

Or that would be too advanced?

Another example implementation (for `Utf8String`):
https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Utf8String.cs#L267-L275
