### ISSUE TITLE
Missing Service

### ISSUE THREAD

**Issue by RaParker** [dotnet/docs#17010]
You say to run dotnet-svcutil http://contoso.com/SayHello.svc

The url http://contoso.com/SayHello.svc does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [WCF svcutil tool overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x#feedback)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **mairaw**

**Comment by MatGhp** [comment]
contoso is only an example. 
Try to use your own service.
