### ISSUE TITLE
How to capture a single point in time snapshot of dotnet-counters to a file?

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#17017]
How to capture a single point in time snapshot of dotnet-counters to a file? `dotnet collect` seems to want to stay alive and continue capturing whereas we want it to come up, take a single snapshot, save to a file and then exit. Sort of how linux `free` works. How can we do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4dadb56-569e-b390-b118-57c3b0225c13
* Version Independent ID: 50cf6a7e-e95e-a29b-67fd-26747f4440c1
* Content: [dotnet-counters - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#dotnet-counters-monitor)
* Content Source: [docs/core/diagnostics/dotnet-counters.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-counters.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by noahfalk** [comment]
We don't have the capability to do that right now, but I recorded a feature request in our backlog [here](https://github.com/dotnet/diagnostics/issues/811). If you wanted something in the meantime you could write your own tool using the public API in NuGet packages Microsoft.Diagnostics.NetCore.Client and TraceEvent. There is some documentation [here](https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/diagnostics-client-library.md) and the full source of dotnet-counters is available as a reference [here](https://github.com/dotnet/diagnostics/tree/master/src/Tools/dotnet-counters)

**Comment by mairaw** [comment]
Thank you @noahfalk. So closing this doc issue for now.

**Comment by preeder** [comment]
If you need something right now, you could use my tool that supplies this snapshot functionality:

https://github.com/preeder/dotnet-counters-snapshot
