### ISSUE TITLE
document the replacement of the PerformanceCounter and how to use it.

### ISSUE THREAD

**Issue by John0King** [dotnet/docs#17027]
The `PerformanceCounter` doesn't cross platform,   and the `EventCounter` is the future. There already some document on github , but not exits on http://docs.microsft.com .
The original issue is here https://github.com/dotnet/runtime/issues/31921

**Comment by Thraka** [comment]
@sdmaclea Checking https://docs.microsoft.com/en-us/dotnet/core/diagnostics/logging-tracing I don't see really a mention of `EventCounter` although you do reference tools that can read that data, there is nothing that describes using it to capture counters.

**Comment by sdmaclea** [comment]
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters is the document.  We have scenario we have to revise to conform to docs.microsoft.com standards.  https://github.com/dotnet/diagnostics/blob/master/documentation/tutorial/app_running_slow_highcpu.md.  I have a draft, but it still needs a few days work.

**Comment by sdmaclea** [comment]
We are also probably missing documentation on how to use the API from C# code.  i.e. the API.

**Comment by Thraka** [comment]
Yes that was what I was talking about, using the API from C#. The github tutorial linked at the end of **dotnet-counters** has that information.

**Comment by cshung** [comment]
Probably should move this one to an appropriate home too.
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md

**Comment by Rick-Anderson** [comment]
@sdmaclea  writes:
> https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters is the document.

That's the doc on the performance monitoring tool, not `EventCounter`. The following GitHub Readme.MD files need to be migrated to docs on this repo:

* [EventCounters in .NET Core 3.0](https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/eventcounters.md)
* [Introduction Tutorial: How to measure performance for very frequent events using EventCounters}(https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md) as suggested by @cshung 

The following links provide additional info:

* [Introducing diagnostics improvements in .NET Core 3.0](https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/)
* [ Diagnostics in .Net Core 3: Event Counters](https://im5tu.io/article/2020/01/diagnostics-in-.net-core-3-event-counters/)
* [.NET Core Counters internals: how to integrate counters in your monitoring pipeline](https://medium.com/criteo-labs/net-core-counters-internals-how-to-integrate-counters-in-your-monitoring-pipeline-5354cd61b42e)

@Thraka  can we get this work scheduled? I need to document the [EventCounters emitted by ASP.NET Core](https://github.com/dotnet/AspNetCore.Docs/issues/18272)

**Comment by shirhatti** [comment]
> I have a draft, but it still needs a few days work.

@sdmaclea I'd be happy to jump in and help if you can point me to your draft

**Comment by sywhang** [comment]
@sdmaclea @shirhatti I can also help out with any documentation work regarding this space. Please let me know if any extra hands are needed

**Comment by sdmaclea** [comment]
I found the old branch and resurrected it here.

https://github.com/sdmaclea/docs/tree/scenarios_rebase

+ I was trying to add the three tutorials in one PR and the review was taking too long.  
+ I dropped the two tutorials so we could focus on a single tutorial.
+ The memory leak tutorial which is on tip was cleaned up and now we have a sample of what these need to become.

I spent a few minutes doing the simple & obvious things I remember from the memory leak review.

I think there are likely a few things left to do with these.

+ Replace screen shot images with sample text from recent actual tool usage.
+ Split code from text which should be translated.  Do not put instructional text in code blocks...
+ Fix broken links (stuff moved around as part of the review)
+ Conform to the tone and style of docs/core.  Use the memory-leak tutorial as an example.  And docs cited by @mairaw in https://github.com/dotnet/docs/pull/14110#discussion_r336278247.

We are also missing docs and or tutorials for 
+ `dotnet sos` - should be fairly simple /cc @mikem8361 
+ `dotnet-gcdump` - I haven't looked /cc @josalem 
+ `perfview`
+ `Linux perf w/ and w/o jitdump`
+ There are probably others....

**Comment by John0King** [comment]
When will the document available on  docs.microsoft.com ?
by the way , I suggest to add a new section  of   "ObsolateApi and replacement" Section on .net core docs

**Comment by noahfalk** [comment]
I don't think #19534 has resolved the need for this documentation. #19354 has some nice scenario walkthroughs, including one which looks at the CPU perf counter, but I don't expect one example of usage to adequately describe the overall feature for most of our customers. Customers are also unlikely to think to read a scenario about CPU usage if their goal is to learn about EventCounter. These are some questions I anticipate customers would ask us and hope to find in our documentation:

1. If want to collect metrics what tools does .Net Core provide? (the walkthrough touches on this one)
2. If I want to create my own custom metrics, how can I do that?
3. If I want to integrate these metrics into existing metric collection pipelines and dashboards, how can I do that? (it wouldn't be straightforward today)
4. What happened to performance counters? Can I still use them? Why use EventCounter instead?
5. What metrics does .Net Core provide out-of-the-box?

[The comment above](https://github.com/dotnet/docs/issues/17027#issuecomment-627579699) had links to a bunch of relevant info in this area.

**Comment by IEvangelist** [comment]
> I don't think #19534 has resolved the need for this documentation. #19534 has some nice scenario walkthroughs, including one which looks at the CPU perf counter, but I don't expect one example of usage to adequately describe the overall feature for most of our customers. Customers are also unlikely to think to read a scenario about CPU usage if their goal is to learn about EventCounter. These are some questions I anticipate customers would ask us and hope to find in our documentation:
> 
> 1. If want to collect metrics what tools does .Net Core provide? (the walkthrough touches on this one)
> 2. If I want to create my own custom metrics, how can I do that?
> 3. If I want to integrate these metrics into existing metric collection pipelines and dashboards, how can I do that? (it wouldn't be straightforward today)
> 4. What happened to performance counters? Can I still use them? Why use EventCounter instead?
> 5. What metrics does .Net Core provide out-of-the-box?
> 
> [The comment above](https://github.com/dotnet/docs/issues/17027#issuecomment-627579699) had links to a bunch of relevant info in this area.

Hi @noahfalk - thanks for keeping me honest, good catch! I'll add these articles too. 👍
