### ISSUE TITLE
Missing section before Active Patterns Example?

### ISSUE THREAD

**Issue by jdodds** [dotnet/docs#17025]
Section says "Expanding the previous example ..." , followed by some code that looks like it's referencing an example that doesn't exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour of F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tour#feedback)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, looks like that was missed.
