### ISSUE TITLE
method parameter example

### ISSUE THREAD

**Issue by arm000** [dotnet/docs#17030]
The text on this page says "The following example shows how to apply attributes to methods, method parameters, and method return values in C#." but the example does not show how to apply attributes to method parameters, only methods and return values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c570f1-2f76-be1b-410a-ed4bd67e33cc
* Version Independent ID: dd329ad3-ca29-61e5-8753-d57792a88516
* Content: [Attributes (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/attributes/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/attributes/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @arm000 I've added it to our backlog to address when this article is next updated.
