### ISSUE TITLE
Remove EOL 2.2 from Linux package manager install instructions. Add 3.1

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#17034]
In "How to install other versions", it lists these versions as examples:

> version
> The version of the SDK or runtime to install. This article will always give the instructions for the latest supported version. Valid options are any released version, such as:
> * 3.0
> * 2.2
> * 2.1

2.2 is EOL, so we should remove it from this list. (Additionally, it doesn't exist on Ubuntu 19.10, causing confusion.)

3.1 should be added. It isn't an "other" version, however the section lists sdk vs. runtime and aspnetcore vs. dotnet, so IMO it's misleading not to include 3.1.

/cc @NikolaMilosavljevic

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Just curious, did 2.2 ever exist for Ubuntu 19.10? It was on the original list for supported OS. That seems like a bad trap to fall in. You make your app with .NET Core 2.2 and Ubuntu users on 19.10 can't install or run it.

**Comment by dagood** [comment]
Something that puts an interesting twist on it is that we didn't have a 19.10 repository for a while--the 19.04 repo was used to install in 19.10. I'm not actually sure when we started using a 19.10-specific repo. I wouldn't be surprised to hear that we only started using that repo after 2.2 was EOL, causing this confusing timeline.

/cc @leecow

**Comment by dagood** [comment]
Huh, yeah, the 19.10-specific page was added 25 days ago. https://github.com/dotnet/docs/pull/16715. Unexpected from what I know of the POR, keeping the number of unnecessary pages low, because it costs the release team time/effort to push to additional repos.

**Comment by Thraka** [comment]
I'm going to update those instructions on installing other versions to have a link to https://docs.microsoft.com/en-gb/dotnet/core/install/dependencies?pivots=os-linux which is where I have listed that 2.2 is supported on 19.XX (which I'll also fix).

**Comment by leecow** [comment]
19.xx are not listed in https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md, which I would expect. Sorry if I gave you bad info!
