### ISSUE TITLE
Relation between .NET Standard and ECMA 335 Partition IV

### ISSUE THREAD

**Issue by cfbao** [dotnet/docs#17032]
> ECMA 335 continues to establish uniformity for .NET implementation behavior, but there's no similar spec for the .NET Base Class Libraries (BCL) for .NET library implementations.

^ This sentence confuses me to no end.

BCL is one of the 9 CLI standard libraries specified in [ECMA 335](https://www.ecma-international.org/publications/standards/Ecma-335.htm) Partition IV, so why does it say that there's no similar spec for it? If there's already a spec for CLI libraries (not just the BCL), then what is the purpose of .NET Standard?

I'm not suggesting that .NET Standard is pointless. I see that it covers a lot more APIs than ECMA 335, and takes a very different approach to assemblies (i.e. the clever use of `netstandard.dll` as explained [here](https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-2.0/README.md)). But I'd really appreciate some clarifications on .NET Standard's relation to ECMA 335 Partition IV, especially since this page already mentions ECMA 335.

Is .NET Standard trying to side step ECMA 335 Partition IV to be a more extensive and flexible spec?
Should ECMA 335 Partition IV be considered a legacy spec with diminishing relevance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
ping @CarolEidt.  Can you address this question?

**Comment by CarolEidt** [comment]
@cfbao - can you tell me where the sentence came from that you quote above?

> BCL is one of the 9 CLI standard libraries specified in ECMA 335 Partition IV, so why does it say that there's no similar spec for it?

The BCL specified in ECMA 335 Partition IV is a minimal set, while .NET Standard covers a broader set of APIs. It would be great to see the set of APIs specified in the  ECMA standard broadened, and I would hope to see that happen in future. 

> Is .NET Standard trying to side step ECMA 335 Partition IV to be a more extensive and flexible spec?

I would say that "side step" is a bit strong, but certainly .NET Standard is taking a more agile approach to specifying and promoting a broadly usable API set.

**Comment by cfbao** [comment]
@CarolEidt Thanks for the reply.

The quoted sentence is the last sentence of the first paragraph on [this page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), or [this document](https://github.com/dotnet/docs/blob/6c6f63c76afed80c6ea85e23ddb88812506120b4/docs/standard/net-standard.md) (as linked in "Content Source" in my original post).

I realize that .NET Standard is much broader than (not only BCL but) all of Standard Libraries in ECMA 335. I think it'd be more appropriate to say that there's no spec for the _broader_ (but still widely used) .NET libraries/APIs, instead of "BCL" (or even Standard Libraries). The latter phrasing isn't technically correct, hence my confusion.

I said "side step" because ECMA 335 Partition IV specifies that most classes/APIs (e.g. `System.Object`) should be in `mscorlib.dll`, whereas if an app/library is to target .NET Standard, it should reference `netstandard.dll` for most classes (including `System.Object`).
A .NET implementation can support/conform to both standards by means of type forwarding, but an app can only choose one. Whether this is "side stepping" or not, I don't really mind either way.

The main point I'd like to make, again, is the distinction of
* .NET Standard being the first ever spec for .NET libraries (as implied in that quoted sentence, incorrectly, I think)
vs.
* .NET Standard being a _new_ spec that encompasses a _broader_ range of .NET APIs, compared to ECMA 335

**Comment by Thraka** [comment]
It does seem that the statement in this article about there being "no spec for the BCL" is erroneous since the ECMA page does have a zip download of the XML ref that defines the standard. It's similar to these specs for .NET Standard: https://github.com/dotnet/standard/tree/master/docs/versions

**Comment by CarolEidt** [comment]
I agree with the comments - I think the page should be edited to reflect something along the lines of @cfbao's second bullet above, e.g. replace:

> but there's no similar spec for the .NET Base Class Libraries (BCL) for .NET library implementations

with something like:

> and while ECMA 335 specifies a small set of standard libraries, .NET Standard encompasses a broader range of .NET APIs.

Does that seem reasonable?

**Comment by cfbao** [comment]
That looks good to me 👍

**Comment by CarolEidt** [comment]
@BillWagner - who would be the right person to ping to make this kind of change?

**Comment by BillWagner** [comment]
@CarolEidt I'll take care of it.  Thanks for helping us resolve the language.
