### ISSUE TITLE
Add more details on how to handle cancellation tokens with async streams.

### ISSUE THREAD

**Issue by laura-rodriguez** [dotnet/docs#17036]
Is it possible to add more details of how to use cancellation tokens with async streams? In this example, the initial cancellation token approach is removed, but it is not explained how to use the cancellation token that developers can pass to the `GetAsyncEnumerator(CancellationToken cancellationToken = default)` method. It's still not clear how this token works in this case. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @laura-rodriguez 

My experience is that I haven't used the CancellationToken with an async stream. I've found it more natural for consumers to simply stop enumerating the results. Resource cleanup is handled by the IAsyncDisposable that's a base interface for IAsyncEnumerable.

I'd like @stephentoub to weigh in on this.  Have you found scenarios where you'd recommend async streams combined with the CancellationToken? If so, we'll add them. If not, I'll expand on why it's not needed with async streams.

**Comment by laura-rodriguez** [comment]
Actually @BillWagner , resource cleanup is another good point to add more details. What's the recommended practice here? Should developers dispose resources manually by calling `DisposeAsync` when stop enumerating the results (either manually or via cancellation token)? 

I couldn't find any content that explains what the recommended practice is for cancellation tokens & dispose. It would be great if you guys can add more details about it in this article. I find super useful the way you show here how to refactor an existent piece code to make it works with async streams, but it would be even better if you can add these missing points.

Thanks!

**Comment by stephentoub** [comment]
See https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8.  There's a whole section on CancellationToken with IAsyncEnumerables.
