### ISSUE TITLE
What abut the equals operator?

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/docs#17045]
Nice Article but usualle people use the equals operator to compare strings. e.g. strA == strB so maybe a word about this would be nice. Also what about trimming? I often see things like strA.ToLower().Trim() == strB.ToLower().Trim() because this also translates to EF. If those things should not be done it should be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dead2df6-1ec5-b55c-89aa-d05a7a75a0eb
* Version Independent ID: fe538551-dcfc-c244-3f16-864d3f6c2a6e
* Content: [Best Practices for Using Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#feedback)
* Content Source: [docs/standard/base-types/best-practices-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/best-practices-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello. Thank you for opening this issue.

The equality operator is mentioned in the [string.equals](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#stringequals) section, but using it isn't a best practice as (per the section) it's not using an explicit `StringComparison` value.

The enhancement to the docs you suggest will be a low priority. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
