### ISSUE TITLE
C# Dev type reference

### ISSUE THREAD

**Issue by CurbYourStrangeness** [dotnet/docs#17049]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0948cf18-9971-b2d4-4f59-e045838e6e5f
* Version Independent ID: e2c7e9c5-ebd3-ed68-d2cc-6d8929c654e8
* Content: [Value types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types#main-features-of-value-types)
* Content Source: [docs/csharp/language-reference/builtin-types/value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/value-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Toumash** [comment]
What do you mean?

**Comment by Thraka** [comment]
I'm guessing this was opened by mistake.

Closing.
