### ISSUE TITLE
Install Scripts Fail on MacOS and Ubuntu

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/docs#17057]
I'm trying to run the install scripts in appeyor in https://github.com/RehanSaeed/Schema.NET/pull/138 but they [fail on MacOS and Ubuntu but work on Windows](https://ci.appveyor.com/project/RehanSaeed/schema-net/builds/30755253).

```yml
- pwsh: |
    if ($isWindows) {
      Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1";
      & ./dotnet-install.ps1 -JSonFile global.json;
    } elseif ($isLinux) {
      sudo apt update
      sudo apt install -y apt-transport-https
    } else {
      brew update
      brew install mono-libgdiplus
    }
- sh: sudo curl https://dot.net/v1/dotnet-install.sh --location --fail-early --silent --show-error | bash -s -- --jsonfile global.json
```

The PowerShell Core code runs first. This installs all of the dependencies required for .NET Core to work depending on the platform. The last line is the bash script that runs on MacOS and Ubuntu only.

On MacOS, the following error is thrown:

> sudo curl https://dot.net/v1/dotnet-install.sh --location --fail-early --silent --show-error | bash -s -- --jsonfile global.json
> tput: No value for $TERM and no -T specified

On Ubuntu the following error is returned:

> sudo curl https://dot.net/v1/dotnet-install.sh --location --fail-early --silent --show-error | bash -s -- --jsonfile global.json
> dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.(B
> dotnet-install:(B Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestMajor/dotnet-sdk-3.1.101rollForward:latestMajor-linux-x64.tar.gz
> curl: (22) The requested URL returned error: 404 
> dotnet-install:(B Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestMajor/dotnet-sdk-3.1.101rollForward:latestMajor-linux-x64.tar.gz
> dotnet-install:(B Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestMajor/dotnet-dev-ubuntu.18.04-x64.3.1.101rollForward:latestMajor.tar.gz
> curl: (22) The requested URL returned error: 404 
> dotnet-install:(B Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101rollForward:latestMajor/dotnet-dev-ubuntu.18.04-x64.3.1.101rollForward:latestMajor.tar.gz
> dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.1.101rollForward:latestMajor(B
> dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support(B
> Command exited with code 1

This is my `global.json` file:

```json
{
  "sdk": {
    "version": "3.1.101",
    "rollForward": "latestMajor"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Thraka** [comment]
The Ubuntu problem may be that the script isn't parsing the global.json file correctly (or the file is malformed in some way). I think that you should file an issue on https://github.com/dotnet/core/issues for that problem. This is where the scripts are managed.

The macOS problem seems to be related to this Q/A: <https://stackoverflow.com/questions/29979966/tput-no-value-for-term-and-no-t-specified-error-logged-by-cron-process>. The script is using `tput` and that wants a value for the $TERM variable which doesn't seem to exist. You'll have to create that prior to running the script.

Let me know if this helps and please close the issue when you're ready to. Thanks!

**Comment by RehanSaeed** [comment]
It seems the `dotnet-install.sh` script fails to find the latest .NET Core SDK `3.1.101` on `Ubuntu 18.04` https://github.com/dotnet/sdk/issues/4198. It seems to work on MacOS.

**Comment by Thraka** [comment]
I'm going to close this issue as you commented on an open issue in the sdk repo and I think your problem is better handled over there.

Thanks!

**Comment by RehanSaeed** [comment]
I found yet another issue with the script, you cannot specify the `dotnet-install.sh` script fails When `global.json` contains `rollForward` https://github.com/dotnet/sdk/issues/10650.

**Comment by Thraka** [comment]
Yeah, that's the error I saw originally in your issue here. Hopefully they get that fixed soon :) of course, you can modify the script in the meantime too and get that fixed manually.
