### ISSUE TITLE
Figure 5-10. The CAP theorem

### ISSUE THREAD

**Issue by yannify** [dotnet/docs#17059]
The Venn diagram indicates that RDMS is Consistent and Partition Tolerant.  Shouldn't it be Consistent and Available?   Below the diagram after the definition of CAP Theorem the text reads:  

"Relational databases typically provide consistency and availability, but not partition tolerance."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e80a45b-7084-c3c3-149a-d891dc8de9be
* Version Independent ID: 983d417d-b9d9-7b86-5e46-cc40cc3127c7
* Content: [Relational vs. NoSQL data](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/relational-vs-nosql-data#feedback)
* Content Source: [docs/architecture/cloud-native/relational-vs-nosql-data.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/relational-vs-nosql-data.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by robvet** [comment]
Excellent catch.

The text beneath describes correctly, but the graphic does not.

Will fix.


Rob Vettor  | Principal Cloud-Native Application Architect
                      | ASD IP Architect
                      | CNCF (Cloud-Native Computing Foundation) Speaker Bureau<https://www.cncf.io/speaker/robvet/>
                      | Developer Advisory Services for Azure

[cid:image001.jpg@01D5E1B8.F03DED40]

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image004.jpg@01D5E1B8.F03DED40]  www.thinkingincloudnative.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.thinkingincloudnative.com%2F&data=02%7C01%7Crobvet%40microsoft.com%7Ca0ad6989676c41a1c02208d7659ff0d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637089609919099893&sdata=Ih3VA8PbdEeYpmeYsH5jWzaoZX6Ys5Rwtpw3UlpdIVA%3D&reserved=0>

Co-Author of…
[cid:image005.png@01D5E1B8.F03DED40]<https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/>
