### ISSUE TITLE
Breaking change in UriBuilder.Query and UriBuilder.Fragment

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#17063]
See https://github.com/dotnet/dotnet-api-docs/issues/3699.

Breaking change between .NET Framework and .NET Core.

**Comment by karelz** [comment]
@MihaZupan can you please help document the breaking change -- fill this: https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md

**Comment by MihaZupan** [comment]
Opened #18161

**Comment by gewarren** [comment]
Breaking change has been documented.
