### ISSUE TITLE
dotnet-install-script.md too windows centric

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/docs#17064]
https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md documents the default installation directory only for windows, and not for linux.

Edited to add Document Details for linking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Thraka do you know the default installation directory for Linux?
