### ISSUE TITLE
c# 8.0 'var' pattern matching not presented

### ISSUE THREAD

**Issue by CodeIsLie** [dotnet/docs#17067]
Hi, i don't see reference to new pattern matching presented in latest version of C#:
for example:

state = (state, transition) switch
{
    (State.Running, Transition.Suspend)     =&gt; State.Suspended,
    (State.Suspended, Transition.Resume)    =&gt; State.Running,
    (State.Suspended, Transition.Terminate) =&gt; State.NotRunning,
    (State.NotRunning, Transition.Activate) =&gt; State.Running,
    _ =&gt; throw new InvalidOperationException()
};

and some other examples with this syntax would be very helpful on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching#feedback)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @CodeIsLie 

There are a few examples like this in [this tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/pattern-matching)  The best plan is to add a link to that article here.

I've added the "up for grabs" label for any community members to make this addition.
