### ISSUE TITLE
Stopping IHostedService gracefully

### ISSUE THREAD

**Issue by KrzysztofBranicki** [dotnet/docs#17071]
It looks like code snippet example that showcases implementation of `GracePeriodManagerService` is little bit misleading in case of stopping the hosted service. 
Line of code at the end of the `ExecuteAsync` method will never be called `_logger.LogDebug($"GracePeriod background task is stopping.");`. This is because `await Task.Delay(_settings.CheckUpdateTime, stoppingToken);` Will throw `TaskCanceledException` when the `stoppingToken` gets cancelled.
This may be misleading example for people that want to implement some cleanup logic after the while loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @KrzysztofBranicki, thanks for the feedback.

You're right, that line will never be executed!

I'll also add a try-catch to the actual code to showcase how to properly handle the `TaskCancelledException`

Hope this helps.

**Comment by gbjbaanb** [comment]
agree, but apart from the problem of an exception being used for unexceptional program flow (sigh) shouldn't any cleanup code be put in the StopAsync method?
