### ISSUE TITLE
Creating a .Net Standard library in Visual Studio

### ISSUE THREAD

**Issue by amit2510kr** [dotnet/docs#17087]
The code given for testing is in C#,and it is not working for vb.net.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Build a .NET Standard class library in Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio?tabs=vb#feedback)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
Thanks for your feedback.

I see the code in Visual Basic. Are you saying that VB code is not working @amit2510kr?
