### ISSUE TITLE
[WinForms] API validate input parameters and throw ANE

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#17085]
## Selected API validate input parameters and throw `ArgumentNullException`.

Selected API now validate input parameters and throw `ArgumentNullException` where previously a `NullReferenceException` could be thrown, if APIs were invoked with `null` input arguments.
Throwing `ArgumentException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Old behavior

The listed API would throw `NullReferenceException` if invoked with `null` input arguments.

### New behavior

The listed API would throw `ArgumentNullException` if invoked with `null` input arguments.

### Reason for change

Throwing `ArgumentNullException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Recommended action

- Review and, if necessary, update the code to prevent passing `null` input arguments in the listed API.
- If the code is handling `NullReferenceException` replace (or supplement) it with handling `ArgumentNullException`.

### Category

- Windows Forms

#### Affected APIs

* [Control.ControlCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.control.controlcollection)
	- [x] [Control.ControlCollection(Control) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.control.controlcollection.-ctor), parameter `owner`
* [TabControl ](https://docs.microsoft.com/dotnet/api/system.windows.forms.tabcontrol)
	- [x] [GetToolTipText(Object)](https://docs.microsoft.com/dotnet/api/system.windows.forms.tabcontrol.gettooltiptext), parameter `item`
* [TableLayoutControlCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.tablelayoutcontrolcollection)
	- [x] [TableLayoutControlCollection(TableLayoutPanel) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.tablelayoutcontrolcollection.-ctor), parameter `container`
* [ToolStripRenderer](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer)
	- [x] [OnRenderArrow(ToolStripArrowRenderEventArgs)](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer.onrenderarrow), parameter `e`
	- [x] [OnRenderItemImage(ToolStripItemImageRenderEventArgs)](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer.onrenderitemimage), parameter `e`
	- [x] [OnRenderItemCheck(ToolStripItemImageRenderEventArgs)](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer.onrenderitemcheck), parameter `e`
	- [x] [OnRenderItemText(ToolStripItemTextRenderEventArgs)](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer.onrenderitemtext), parameter `e`
	- [x] [OnRenderStatusStripSizingGrip(ToolStripRenderEventArgs)](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstriprenderer.onrenderstatusstripsizinggrip), parameter `e`

#### Affected APIs

* [DataGridViewComboBoxEditingControl](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcomboboxeditingcontrol)
	- [x] [ApplyCellStyleToEditingControl(DataGridViewCellStyle)](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcomboboxeditingcontrol.applycellstyletoeditingcontrol), parameter `dataGridViewCellStyle`
* [RichTextBox](https://docs.microsoft.com/dotnet/api/system.windows.forms.richtextbox)
	- [x] [LoadFile(Stream, RichTextBoxStreamType)](https://docs.microsoft.com/dotnet/api/system.windows.forms.richtextbox.loadfile#System_Windows_Forms_RichTextBox_LoadFile_System_IO_Stream_System_Windows_Forms_RichTextBoxStreamType_), parameter `data`

#### Affected APIs

* [ListViewGroup](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroup)
	- [x] [ISerializable.GetObjectData(SerializationInfo, StreamingContext)](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroup.system-runtime-serialization-iserializable-getobjectdata), parameter `info`
* [VisualStyleRenderer](https://docs.microsoft.com/dotnet/api/system.windows.forms.visualstyles.visualstylerenderer)
	- [x] [VisualStyleRenderer(String, Int32, Int32)](https://docs.microsoft.com/dotnet/api/system.windows.forms.visualstyles.visualstylerenderer.-ctor#System_Windows_Forms_VisualStyles_VisualStyleRenderer__ctor_System_String_System_Int32_System_Int32_), parameter `className`
* [ListBox.IntegerCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.integercollection)
	- [x]  [ListBox.IntegerCollection(ListBox) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.integercollection.-ctor), parameter `owner`
	- [x] [ListBox.IntegerCollection.CopyTo(Array, int)](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.integercollection.copyto), parameter `destination`

#### Affected APIs

* [ListBox.ObjectCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection)
	- [x] [ListBox.ObjectCollection(ListBox) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.-ctor#System_Windows_Forms_ListBox_ObjectCollection__ctor_System_Windows_Forms_ListBox_), parameter `owner`
	- [x] [ListBox.ObjectCollection(ListBox, Object[]) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.-ctor#System_Windows_Forms_ListBox_ObjectCollection__ctor_System_Windows_Forms_ListBox_System_Object___), parameter `owner`
	- [x] [ListBox.ObjectCollection(ListBox, Object[]) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.-ctor#System_Windows_Forms_ListBox_ObjectCollection__ctor_System_Windows_Forms_ListBox_System_Object___), parameter `value`
	- [x] [ListBox.ObjectCollection(ListBox, ListBox+ObjectCollection) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.-ctor#System_Windows_Forms_ListBox_ObjectCollection__ctor_System_Windows_Forms_ListBox_System_Windows_Forms_ListBox_ObjectCollection_), parameter `owner`
	- [x] [ListBox.ObjectCollection(ListBox, ListBox+ObjectCollection) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.-ctor#System_Windows_Forms_ListBox_ObjectCollection__ctor_System_Windows_Forms_ListBox_System_Windows_Forms_ListBox_ObjectCollection_), parameter `value`
	- [x] [ListBox.ObjectCollection.AddRange(Object[])](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.addrange#System_Windows_Forms_ListBox_ObjectCollection_AddRange_System_Object___), parameter `value`
	- [x] [ListBox.ObjectCollection.AddRange(ListBox+ObjectCollection)](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.addrange#System_Windows_Forms_ListBox_ObjectCollection_AddRange_System_Windows_Forms_ListBox_ObjectCollection_), parameter `value`
	- [x] [ListBox.ObjectCollection.CopyTo(Object[], Int32)](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.copyto), parameter `destination`
	- [x] [ListBox.ObjectCollection.ICollection.CopyTo(Array, Int32)](https://docs.microsoft.com/dotnet/api/system.windows.forms.listbox.objectcollection.system-collections-icollection-copyto), parameter `destination`

#### Affected APIs

* [ListView.SelectedIndexCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.selectedindexcollection)
	- [x] [ListView.SelectedIndexCollection(ListView) Constructor](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.selectedindexcollection.-ctor), parameter `owner`

#### Affected APIs

* [TreeNodeCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.treenodecollection)
	- [x] [TreeNodeCollection.Find(String, Boolean) Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.treenodecollection.find), parameter `key` is `null` or empty.

#### Affected APIs

* [ListViewItemCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.listviewitemcollection)
	- [x] [ListViewItemCollection.Find(String, Boolean) Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.listviewitemcollection.find), parameter `key` is `null` or empty.
* [ScrollableControl](https://docs.microsoft.com/dotnet/api/system.windows.forms.scrollablecontrol)
	- [x] [ScrollableControl.OnPaintBackground(PaintEventArgs) Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.scrollablecontrol.onpaintbackground), parameter `e` is `null`.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by RussKie** [comment]
@gewarren sadly GitHub flavoured markup doesn't allow checkboxes in a table. So we'll have to edit the markup once each entry is processed.

Few options:
- We replace the table with a list with checkboxes, or
- Edit the markup and add something like `:heavy_check_mark:` to indicate an entry was processed.

Please let me know which way you prefer, or feel free to edit to the way you wan it, and I'll then follow the chosen style.

**Comment by gewarren** [comment]
@RussKie Shoot! I think the checklist will be easier since you don't have to edit the markdown.

**Comment by RussKie** [comment]
Too easy, checkbox list it is then

**Comment by RussKie** [comment]
Will I need new issues for the same thing going forward?

**Comment by gewarren** [comment]
No, I'll reopen this one.

**Comment by RussKie** [comment]
I'll have new ones opened for 6.0 😉
Thank you for your help.
