### ISSUE TITLE
SQUARE and SQRT function issue (SSMS)

### ISSUE THREAD

**Issue by Zyean** [dotnet/docs#17095]
Hello, I'm noticing an issue in SQL server where 

Squaring 2147483647 using the SQUARE function returns 4611686014132420608
However, 2147483647 * 2147483647 = 4611686014132420609

```
DECLARE @x BIGINT = 2147483647
DECLARE @squared BIGINT = SQUARE(@x)

SELECT @squared
SELECT @x * @x
```

Could this be an issue related to how the SQUARE function returns a float? 
A similar issue happens on the SQRT function, where FLOOR(SQRT(4611686016279904209)) = 2147483648, however this should return 2147483647
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd81284-a82c-13d7-9225-74e895aed6ec
* Version Independent ID: e448bf2a-af9b-1733-677f-601d176df72d
* Content: [SQUARE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/square-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/square-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/square-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by BillWagner** [comment]
@mikeRayMSFT Should this issue be in a different repository? I'm not sure how it found its way to .NET docs.

**Comment by Thraka** [comment]
This issue was moved to MicrosoftDocs/sql-docs#4166
