### ISSUE TITLE
The NET Framework Setup subkey in the registry path does not begin with a period.

### ISSUE THREAD

**Issue by ortymd** [dotnet/docs#17090]
Please explain whetehr there is any logical reason for "The NET Framework Setup subkey in the registry path does not begin with a period." thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
Hello,

Are you asking about the note or about the specific name? The reason the note points this out is that that people are used to typing `.NET Framework` with a `.` at the start, so the note points out this discrepancy.

I'm going to close this. If this didn't answer your question, please follow up. Thanks!
