### ISSUE TITLE
Numbers in C#: step 5 is misleading

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#17103]
Step 5, [Work with fixed point types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=5), states that the `decimal` type is the fixed-point type. However, it's not: `decimal` is a floating-point type.

Rather than fixing that, I suggest to remove the whole step 5 from the tutorial. @BillWagner what do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@pkulikov I think it's worth fixing this page rather than removing it.  Beginners would see `decimal` early in learning C#. It's good to cover it here.

**Comment by pkulikov** [comment]
@BillWagner indeed, would be ideal if the tutorial described use cases for those types.
Then, this issue becomes related to #8804.

**Comment by pkulikov** [comment]
Related: #17191
