### ISSUE TITLE
net core 3.1 default publish config is release not debug

### ISSUE THREAD

**Issue by MHDuke** [dotnet/docs#17110]
am using dotnet core 3.1 and dotnet publish would default to /bin/release/netcoreapp3.1/publish. unlike what is stated in this documentation. it seems the release configuration is the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee36626-0fc2-20d8-81c5-a3cd212244b2
* Version Independent ID: 044ba93c-9ad9-80c7-dc5c-27a80c9bd921
* Content: [Publish apps with the .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli)
* Content Source: [docs/core/deploying/deploy-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by MHDuke** [comment]
that was inaccurate. i was publishing using visual studio. using the CLI though, I noticed the appsettings.json, appsettings.Development.json are published, but not  appsettings.production.json.  so appsettings.production.json is left out using the CLI but is included using visual studio publish.

**Comment by Thraka** [comment]
I'll close this issue as it seems you have answered your question yourself 😄
