### ISSUE TITLE
What happens when build?

### ISSUE THREAD

**Issue by DrGriff** [dotnet/docs#17116]
If I create a project with multiple frameworks as described above, and then compile it [F6] then does it compile multiple times (once for each framework specified)?

We have the FxCop Roslyn analysers installed and set to treat all warnings as errors when in RELEASE mode - does this work properly with multiple frameworks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
@DrGriff Hello. When you use the .NET Core CLI to build, it will build each targeted framework. I'm not sure if Visual Studio does that. Regarding FxCop analyzers, I'm unsure about that too. I don't have any test projects that are setup like that to see if it builds. If you have projects that use FxCop, you should be able to easily test that. You could also ask on the https://github.com/MicrosoftDocs/visualstudio-docs/issues docs.

@gewarren may have some info, she used to work on the Visual Studio docs.

**Comment by gewarren** [comment]
@ghogen may be able to comment on the F6 functionality in Visual Studio.

**Comment by ghogen** [comment]
In Visual Studio, you can either do a regular build (Ctrl+Shift+B) to build the active configuration and platform shown in the toolbar, or if you want to build all or multiple configurations, you can choose Build > Batch Build.

**Comment by Thraka** [comment]
I think this question is answered. I'll close it. Please feel free to comment if you have a follow up question.
