### ISSUE TITLE
Ocelot dependency

### ISSUE THREAD

**Issue by TheElectricCo** [dotnet/docs#17115]
Hi, the latest version of Ocelot (14.0.9) does not target .net standard 2.0, but only .net core 3.1. This version cannot be used with the full .net framework unfortunately

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @TheElectricCo, thanks for the heads up 😊

Fixing it now.
