### ISSUE TITLE
Method names should be PascalCase

### ISSUE THREAD

**Issue by bradleypatton** [dotnet/docs#17128]
The method names getLength and getWidth should be GetLength and GetWidth to follow standard C# styles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae0353c5-ba87-4095-b638-1f462bcbb627
* Version Independent ID: ecd0839f-58a7-19ca-eeff-ace97a6112ed
* Content: [How to explicitly implement interface members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/how-to-explicitly-implement-interface-members#feedback)
* Content Source: [docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-interface-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-interface-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this @bradleypatton 

I've added it to our backlog to update when we next update this article. I've also added the "up ofr grabs" label if anyone wants to submit a PR before we make this change.
