### ISSUE TITLE
Out of date example for attribute on return?

### ISSUE THREAD

**Issue by jdodds** [dotnet/docs#17122]
```fsharp
let function1 x : [<return: Obsolete>] int = x + 1
```

gives me `This attribute is not valid for use on this language element`  on F# 4.7 + dotnet core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aace421d-61eb-5fc0-ec1b-41f3848625f5
* Version Independent ID: e237e964-3f9d-ceb9-8ff6-5cc0813718de
* Content: [Attributes - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/attributes)
* Content Source: [docs/fsharp/language-reference/attributes.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/attributes.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
I don't think this was ever supported (at least certainly as of F# 4.0). The documentation is a bit old, so I'll remove that from the table and file an issue on the F# repo.

**Comment by cartermp** [comment]
Sorry, to clarify - `Obsolete` isn't supported for that target. So the table is just bad.
