### ISSUE TITLE
NUnit filter example is not covered

### ISSUE THREAD

**Issue by alex-piccione** [dotnet/docs#17135]
In the section with list of example it is covered only _MSTest_ and _xUnit_.   
I'd like to see also _NUnit_.  
For example I don't know how to filter tests with the **CategoryAttribute**.  
Should I use **Category**=mycategory or **Trait** or **Traits** ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion, the next time we update this article we'll look into adding NUnit examples.
