### ISSUE TITLE
Aggregate() example(s)

### ISSUE THREAD

**Issue by NickPea** [dotnet/docs#17137]
Everything else is pretty straight-foward, but a good demonstration of the arguments that the Aggregate method takes would be stellar!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec460a44-db5a-47a5-2086-0a754104211f
* Version Independent ID: c0a63095-e4ad-52b9-978b-eafea54f6e92
* Content: [Aggregation Operations (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/aggregation-operations#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/aggregation-operations.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/aggregation-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @NickPea 

This is one of the more complicated LINQ methods. I've added this to our backlog to update when we next update this article.

**Comment by BillWagner** [comment]
I checked the destination links, and the `Aggregate` page does have several examples.

Closing as fixed.
