### ISSUE TITLE
Add dotnet-vstest to dotnet command topic

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#1713]
Blocked by #1698 (`dotnet-vstest.md` doesn't exist yet) & #1705 (`dotnet.md` is undergoing revision)

**Comment by mairaw** [comment]
This kind of merge conflict would be easy to solve if you wanna handle that in the vstest PR

**Comment by GuardRex** [comment]
> easy to solve

"Famous last words?" :grinning: ... I must be getting "conflict averse" in my old age. lol
