### ISSUE TITLE
Misleading explanation of default value initialization as relates to constructor

### ISSUE THREAD

**Issue by timjen3** [dotnet/docs#17149]
This document explains that "If a class does not have a constructor, a parameterless constructor is automatically generated and default values are used to initialize the object fields. For example, an int is initialized to 0." This is misleading. Fields are initialized to default values regardless of which constructor is used. As stated more accurately in the "Fields (C# Programming Guide)" documentation: "Fields are initialized immediately before the constructor for the object instance is called. If the constructor assigns the value of a field, it will overwrite any value given during field declaration."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbf6206-5332-f844-ba6a-66b58090f686
* Version Independent ID: 93775018-00ba-2c71-e9e8-da1792f35f9b
* Content: [Instance Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/instance-constructors#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/instance-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/instance-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @timjen3 
I've added this to our backlog to update when we next update this article.

I agree with your recommendation to fix this issue. I've also added the "up for grabs" label. That way, any community members that want to can apply the fix.

thanks again.
