### ISSUE TITLE
Best practice for disposing of IAsyncEnumerable

### ISSUE THREAD

**Issue by udlose** [dotnet/docs#17151]
I'd like to know what the suggested pattern for cleanup is when working with `IAsyncEnumerable`. 

I know that `Task` implements `IDisposable` but it's not necessary to use `Dispose` in that case based on @stephentoub 's excellent article - https://devblogs.microsoft.com/pfxteam/do-i-need-to-dispose-of-tasks/. Is it the same case for `IAsyncEnumerable` (i.e. don't worry about disposing) ?

Any suggestions are appreciated! TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream?WT.mc_id=anthonychuca-blog-antchu#feedback)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by stephentoub** [comment]
IAsyncEnumerator is an IAsyncDisposable, just as IEnumerator is an IDisposable. And you want to dispose it at similar times. await foreach will dispose the async enumerator it gets just at foreach will dispose the enumerator it gets. Etc. Just as IEnumerable isn't IDisposable, IAsyncEnumerable isn't either.

https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8

**Comment by BillWagner** [comment]
Thanks for adding this issue @udlose 

@stephentoub's comment is the right fix.

I've added this to our backlog, and I've added the up-for-grabs label for any community members that wish to make a contribution to address this.

**Comment by udlose** [comment]
> IAsyncEnumerator is an IAsyncDisposable, just as IEnumerator is an IDisposable. And you want to dispose it at similar times. await foreach will dispose the async enumerator it gets just at foreach will dispose the enumerator it gets. Etc. Just as IEnumerable isn't IDisposable, IAsyncEnumerable isn't either.
> 
> https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8

Thanks for pointing out the error in my question as well.  I was incorrectly asking about `IAsyncEnumerable` being disposable - not `IAsyncEnumerator`.  I completely forgot that `IEnumerator` is an `IDisposable` - doh! I probably didn't remember since I don't remember having to create a custom `IEnumerator`.  The `foreach` totally makes it "black-box" for the user (which makes it so much easier to use).

Now the parallels between the async and non-async versions make sense. Thanks for clarifying.

**Comment by John0King** [comment]
I'm still a little confued, because `IAsyncEnumerable<T>`  normally hold the connection from the network(eg. database, mq connection)  , and may be infinity （for example , mq queen）,  so that will never call finish.

```C#
var queen = mq.GetAsyncEnumerable();

// if I get the quee as IEnumberable, and passed to another method,
// then  how can the another method close the connection immediately for some reason ?

DoProcessQueen(queen)

async Task  DoProcessQueen(IAsyncEnumerable<QueenTime> queen)
{
      await foreach(var item in queen)
      {
          cancelToken.ThrowIfCanceled(); //   this will not be called  if there no queen item been dispatch
           await processAsync(item)
      }
}

```

**Comment by stephentoub** [comment]
> // if I get the quee as IEnumberable, and passed to another method,
> // then  how can the another method close the connection immediately for some reason ?

```C#
await foreach(var item in queen.WithCancellation(cancelToken)
```
