### ISSUE TITLE
Mac Publish

### ISSUE THREAD

**Issue by srinigudimella** [dotnet/docs#17156]
Not able to see the .exe file in publish folder in MAC OS. The folder showing only below files.
helloworld.deps.json
helloworld.dllhelloworld.pdb
helloworld.runtimeconfig.json
Anything missed to follow or there will be separate process to publish for MAC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449b8ce2-80b3-9bfa-6d7f-3e8ac8a86e16
* Version Independent ID: 31264b07-1aeb-b3f0-1126-f25e578f6d50
* Content: [Publish your .NET Core Hello World application with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio#feedback)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/publishing-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
macOS doesn't use/produce .exe files like windows does. It's an extensionless file named after your project.

**Comment by tdykstra** [comment]
@Thraka When I run `dotnet publish` on macOS, I don't get an extensionless executable file, I get the executable only on Windows and Linux.  I do get the .dll on all platforms.

**Comment by Thraka** [comment]
@tdykstra It would depend on your publishing mode. Self-contained would give you an executable or if the AppHost setting was turned on (which is now defaulted to off in one of the latest patch releases for mac)

@srinigudimella As Tom pointed out, there is a .dll file which is your app. You need to run it with `dotnet yourfilename.dll`.
