### ISSUE TITLE
Broken link to sample

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#17153]
And this article also doesn't seem connected to the TOC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce840080-2d1b-6eab-df07-5adddb1d44c1
* Version Independent ID: c951952f-e5d9-2286-fea9-35cffa06d5ae
* Content: [Interpret ML.NET models with Generalized Additive Models - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/use-gams-for-model-explainability)
* Content Source: [docs/machine-learning/how-to-guides/use-gams-for-model-explainability.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/use-gams-for-model-explainability.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Thanks for raising this issue @mairaw . I was already working on this but now we have an issue to track the work item to :)

**Comment by luisquintanilla** [comment]
AB#1667151
