### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#17167]
"ContentControl and ItemsControl" section:
"Likewise, an ItemsPresenter that is in the ControlTemplate of an ItemsControl will automatically bind to the Items and ItemsPresenter properties."

ItemsPresenter ... bind to ... ItemsPresenter

It seems that instead of the second ItemsPresenter there should be ItemTemplate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dfc55ee-0061-cd98-fd01-ad6156f8d155
* Version Independent ID: 594e424a-30ed-9f1e-dac7-e56acdd022e0
* Content: [Styles and templates - WPF](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/fundamentals/styles-templates-overview#feedback)
* Content Source: [docs/desktop-wpf/fundamentals/styles-templates-overview.md](https://github.com/dotnet/docs/blob/master/docs/desktop-wpf/fundamentals/styles-templates-overview.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for reporting this.
