### ISSUE TITLE
same Value Object instance in two aggregates not work

### ISSUE THREAD

**Issue by ArthDevRepo** [dotnet/docs#17161]
If two aggregates have the same instance of an value object, always throws an exception.
How to solve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @ArthDevRepo, 

Value objects (VO) are not supposed to be shared, so don't, Use different instances.

If you need to share it, then don't use a VO.

Hope this helps.

Closing this issue now as it's not related to the guide.
