### ISSUE TITLE
Missing read line...

### ISSUE THREAD

**Issue by hamdam121** [dotnet/docs#17172]
Where is the ConsoleRead in your example? This ex returns nothing!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 799f3460-8d63-76ac-0f6b-8dc09840da09
* Version Independent ID: 777bcccf-fc8b-5a95-114f-9a2e74e33318
* Content: [Command-Line Arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/command-line-arguments)
* Content Source: [docs/csharp/programming-guide/main-and-command-args/command-line-arguments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/main-and-command-args/command-line-arguments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@humdam121 Perhaps you can elaborate as to why you expected a `Console.Read` line? This article is demonstrating reading the command line arguments and printing them out. This means that you call the executable with an input value:

`myfile.exe argument` where **argument** is the value you pass to the executable and read through the `args` array.
