### ISSUE TITLE
About nuget pack localized IntelliSense

### ISSUE THREAD

**Issue by hjkl950217** [dotnet/docs#17177]
About localized IntelliSense,For file from .net core 3.1 's nuget,Need to do the following：
1.Merge the xml file in the IntelliSense file you just downloaded into the zh-hans folder.
2.Navigate to the .NET Core installation folder. By default, it's under %ProgramFiles%\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app.
3.select Select the latest version
4. copy zh-hans folder to "%ProgramFiles%\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\{you version}\ref\netcoreapp{latest version}". eg: C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.2.0\ref\netcoreapp2.2\zh-hans\Accessibility.xml

If you do not do this, many IntelliSense will not take effect, and many dlls do not read the XML file from the SDK itself, but read the nuget file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b361b8e5-3b89-8e46-6356-ca420e468b69
* Version Independent ID: f66f7a1a-1ab7-dab7-696f-916950c4c518
* Content: [Install localized IntelliSense files](https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense#feedback)
* Content Source: [docs/core/install/localized-intellisense.md](https://github.com/dotnet/docs/blob/master/docs/core/install/localized-intellisense.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@hjkl950217 Are you doing this for SDK 2.2? This article is for 3.0+

**Comment by hjkl950217** [comment]
yes,Just after doing this, 2.2 can also use localized files

**Comment by Thraka** [comment]
Thank you for the suggestion, but we'll leave the article the way it is, as it's talking about 3.0+. Cheers!
