### ISSUE TITLE
Revert note about translating code comments

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#17173]
Revert PR #17129 at the end of April

**Comment by Thraka** [comment]
@Rick-Anderson @JasonCard

How did the test go?

**Comment by Rick-Anderson** [comment]
We need more data. No one has complained about the include so I suggest we keep it for a year.

**Comment by tdykstra** [comment]
If it takes a year to gather enough data I don't think it will ever be enough to counter all the negatives inherent in trying to translate code comments.  I think we should concede that it isn't going to fly.

**Comment by Rick-Anderson** [comment]
That's my guess, but I'd still like to solicit comments for a year. @JasonCard  for his opinion.

I agree with @Thraka , when he stated "this is obviously something non-english speakers want". I'd like to understand why we're not getting more feedback.

**Comment by JasonCard** [comment]
I'm also wondering why we're not getting more feedback. I'd be curious to see how many requests there would be in a year. But maybe most people who look at code examples can generally understand the code comments. Honestly, I think localizing code comments is nice to have, but low priority request that's probably not worth the trouble.

**Comment by adegeo** [comment]
@Rick-Anderson is it time to revert this? It's been a few years now and I assume the data has been collected.

**Comment by Rick-Anderson** [comment]
sure
