### ISSUE TITLE
Incorrect reference?

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#17171]
The very last sentence (before "See also"): "If you are creating a theme for your custom control, see the External control library section of the Control authoring overview."

There is no "External control library" section in the "Control authoring overview" page.
https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/control-authoring-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dfc55ee-0061-cd98-fd01-ad6156f8d155
* Version Independent ID: 594e424a-30ed-9f1e-dac7-e56acdd022e0
* Content: [Styles and templates - WPF](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/fundamentals/styles-templates-overview#feedback)
* Content Source: [docs/desktop-wpf/fundamentals/styles-templates-overview.md](https://github.com/dotnet/docs/blob/master/docs/desktop-wpf/fundamentals/styles-templates-overview.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for reporting this.
