### ISSUE TITLE
I don't think .NET's regex engine is based on NFAs

### ISSUE THREAD

**Issue by jtheisen** [dotnet/docs#17182]
> In general, a Nondeterministic Finite Automaton (NFA) engine like .NET regular expression engine places the responsibility for crafting efficient, fast regular expressions on the developer.

I think that's wrong.

An NFA implementation would be linear in both the regular expression length and the input length [as argued here](https://swtch.com/~rsc/regexp/regexp1.html): The NFA's number of states is linear in the length of the regex.

It's the implementations that are written as a recursive-descent-parser that are vulnerable to catastrophic backtracking - and since .NET's is, it's presumably one of those.

The whole notion of "backtracking" is a recursive-descent thing, not an automaton thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce579cf-f3af-6050-895b-d00ae083c26b
* Version Independent ID: 89943c6e-1d5e-737d-cac8-ef87e8d42cf6
* Content: [Backtracking in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#feedback)
* Content Source: [docs/standard/base-types/backtracking-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/backtracking-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@jtheisen Hello. Does the intro at https://docs.microsoft.com/en-us/dotnet/standard/base-types/details-of-regular-expression-behavior describe it better?

>The .NET Framework regular expression engine is a backtracking regular expression matcher that incorporates a traditional Nondeterministic Finite Automaton (NFA) engine such as that used by Perl, Python, Emacs, and Tcl.

I feel like this description should be adapted to this article.

**Comment by jtheisen** [comment]
I think it's incorrect, and it contradicts the article I linked.

It also contradicts everything I know from university about finite automatons. Neither DFAs nor NFAs do backtracking, the latter can merely be in multiple states at ones.

I'm pretty sure that the author didn't know what an automaton is.

If I'm wrong I bow my head in shame, but I don't think I am.

**Comment by Thraka** [comment]
I'm unsure really. I don't have enough knowledge either way. I just noticed that the difference between the two descriptions of the engine are pretty substantial in the wording. The link I linked to describes it as this first:

> The .NET Framework regular expression engine is a **backtracking regular expression matcher**

Then it goes on to say that it *also* does this:

> **incorporates** a traditional Nondeterministic Finite Automaton (NFA) engine

While the article you filed this issue on seems to describe the .NET Regex system as an NFA *first and foremost*, which seems to be the description problem.

@ViktorHofer can you shed some light?

**Comment by jtheisen** [comment]
You could argue it's a description problem. NDAs cannot be executed literally after all, though I would argue that if you simulate them naively, you get the linear algorithm and there's still no backtracking involved.

**Comment by Thraka** [comment]
@maryamariyan can you help here?

**Comment by eerhardt** [comment]
I believe the wording could be updated from

> In general, a Nondeterministic Finite Automaton (NFA) engine like .NET regular expression engine places the responsibility for crafting efficient, fast regular expressions on the developer.

To

> In general, a _**backtracking**_ Nondeterministic Finite Automaton (NFA) engine like .NET regular expression engine places the responsibility for crafting efficient, fast regular expressions on the developer.

to better describe the engine. The article linked above (https://swtch.com/~rsc/regexp/regexp1.html), describes an approach using NFAs in a non-backtracking way: by tracking all the possible states at the same time. So yes, it is possible to use NFAs, but not use backtracking. Just because an engine is using NFAs doesn't necessarily mean it can have exponential runtime.

cc @pgovind @stephentoub

**Comment by stephentoub** [comment]
Right, it's a question of how you handle the ability to be in multiple states at the same time.  You can try one thing and if it fails backtrack to try the next, or you can keep track of all of the possible states you're in at each step.  The latter is often referred to as a "Thompson NFA".

**Comment by jtheisen** [comment]
@stephentoub Well, the second implementation still is an *automaton*, ie. a program of finite state (for each given regex). That includes all state, including all stack and heap required for the implementation that isn't directly representing the NFA states. The first implementation may be "based" on an automaton, but it's not actually an automaton as it requires the additional bookkeeping required for backtracking, which can be linear in the input size.

So the "Thompson NFA" is itself a proper automaton, the "NFA-based backtracker" isn't.

The fact that the latter can catastrophically backtrack is a reflection of that, as that can't happen with proper automatons. (That's what makes my point here not merely an academic one.)

Perhaps a sentence like "the backtracking NFA implementation is not an automaton in the strict theoretical sense" somewhere in or along the paragraph quoted by @eerhardt could help those poor souls that are confused by what they've thought they learned about automatons in compsci classes 20 years ago.

**Comment by stephentoub** [comment]
I think this is splitting hairs.  The terminology as it applies to regular expressions is well-accepted.  If we're going to go by strict theoretical terminology, these aren't regular expressions, either, in that they can be used to describe things that aren't possible in regular languages.

**Comment by jtheisen** [comment]
You have a link to another source calling backtrackers "NFA implementations"?

I don't doubt you, I'm just curious.

While you may be right in that it's generally accepted terminology by regex-pros, we're talking about documentation targeting a much more general audience. With your argument you could probably drop a lot more. What I generally like about much of the MS docs is that they often give the necessary overview that is usually neglected.

**Comment by stephentoub** [comment]
Sure, e.g. Jeffrey E. F. Friedl's Mastering Regular Expressions, considered by many to be the regex bible.

**Comment by jtheisen** [comment]
He indeed even calls backtracking "the essence of an NFA engine".

I'm closing now and be on my way, thanks for listening.
