### ISSUE TITLE
Notes on GC.KeepAlive are confusing

### ISSUE THREAD

**Issue by oleg-bronzhaiev** [dotnet/docs#17189]
The following statement from the post is confusing and not true:
> The code example provided for the GC.KeepAlive method shows how aggressive garbage collection can cause a finalizer to run while a member of the reclaimed object is still executing. It is a good idea to call the KeepAlive method at the end of a lengthy Dispose method.

The code example provided for the [GC.KeepAlive](https://docs.microsoft.com/en-us/dotnet/api/system.gc.keepalive) shows that GC doesn't know that Unmanaged Resource references Managed Object. Thus, it may make sense to utilize GC.KeepAlive to keep managed object in memory.

So, in particular, the statement below
> garbage collection can cause a finalizer to run while a member of the reclaimed object is still executing

may confuse the reader in a way the one may think GC can cause a finalizer to run while its **instance**-member is still executing (e.g. Dispose method). This is not true, of course.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-base-class)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
@oleg-bronzhaiev Thank you for filing this issue. If I understand it correctly, you're saying saying that the clause should really state something more similar to

> garbage collection can cause a finalizer to run while an unmanaged reference to the object is still in use.

Yes?

**Comment by oleg-bronzhaiev** [comment]
@Thraka Thanks for response. I'd rewrite the entire paragraph:
> The code example provided for the GC.KeepAlive method shows how garbage collection can cause a finalizer to run while an unmanaged reference to the object or its members is still in use. It may make sense to utilize GC.KeepAlive to make the object ineligible for garbage collection from the start of the current routine to the point where this method is called.

Editorial Notes:
- "aggressive" word has been removed, since it may confuse. Finalizer may run even when scheduled/planned garbage collection takes place.
- "lengthy Dispose method" have been removed, since it has nothing to do with Dispose method. The mentioned issue may happen in any method.
- The last sentence is heavily based on description in [GC.KeepAlive page](https://docs.microsoft.com/en-us/dotnet/api/system.gc.keepalive)
- links to [GC.KeepAlive](https://docs.microsoft.com/en-us/dotnet/api/system.gc.keepalive) page should be inserted in my version of the text.

**Comment by Thraka** [comment]
If you would like to contribute a change, which can be reviewed by the team, you can submit an edit to the original article. Click on the **Content Source** link at the bottom of the first issue comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

**Comment by oleg-bronzhaiev** [comment]
Ok, thanks. I may submit for review, so I'm closing the issue.

**Comment by Milek7** [comment]
> may confuse the reader in a way the one may think GC can cause a finalizer to run while its **instance**-member is still executing (e.g. Dispose method). This is not true, of course.

What was not true there? Object can be eligible for garbage collection and have it finalizer called before member method returns. https://devblogs.microsoft.com/oldnewthing/20100810-00/?p=13193 That's why wrapper classes that have finalizer that release native resources usually need to have `GC.KeepAlive(this)` at the end of methods that call native code. https://learn.microsoft.com/en-us/visualstudio/code-quality/ca2115?view=vs-2022
