### ISSUE TITLE
IIS Details Needed

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#17190]
How does this work in relation to IIS?

You cannot run self contained applications in IIS without also installing the target framework. (It complains about bad modules). 

It would be useful to have a walkthrough of how IIS libraries are selected when multiple versions of the framework are installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET Core version to use - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#feedback)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/selection.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
We can add a note and point to the https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1 article. From that article it's noted that:

>ASP.NET Core doesn't adopt roll-forward behavior for patch releases of shared framework packages. After upgrading the shared framework by installing a new hosting bundle, restart the system or execute the following commands in a command shell:
