### ISSUE TITLE
Add argument validation use case to discard documentation

### ISSUE THREAD

**Issue by julealgon** [dotnet/docs#17198]
I think it would be helpful to add another use case to the standalone discard documentation for simplified argument validation.

From:
```csharp
if (arg is null)
{
    throw new ArgumentNullException(nameof(arg));
}
```

To:
```csharp
_ = arg ?? throw new ArgumentNullException(nameof(arg));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @julealgon I've added it to our backlog to address.

Would you expect to find this under "discards", or "null checks"? I'd like to make sure this idiom is found once we add it.

**Comment by julealgon** [comment]
Just checked the documentation again and i don't see any mentions of the scenario suggested in this issue.

Should it be reopened @dotnet/docs ?
