### ISSUE TITLE
Dos and don'ts of stackalloc

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#17207]
The `stackalloc` article might be updated according to the following blog post:
https://vcsjones.dev/2020/02/24/stackalloc/

@vcsjones are you fine with that? If yes, @BillWagner could you please assign this issue to me. I'll try to add one-two new paragraphs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecde487e-96e5-85c2-ff87-227994f705ad
* Version Independent ID: f77588b3-9b31-f8ce-fad5-bf937337eb8c
* Content: [stackalloc operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc)
* Content Source: [docs/csharp/language-reference/operators/stackalloc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/stackalloc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by vcsjones** [comment]
My normal [licensing][1] for my blog posts is Creative Commons Attribution 4.0 International License, but I am happy to make any explicit grants or consents to get any useful content in to Microsoft's own documentation so that attribution is not required.

[1]: https://github.com/vcsjones/vcsjones.com/blob/master/README.md

**Comment by BillWagner** [comment]
Thanks @pkulikov and @vcsjones. I've assigned this to @pkulikov 

In the PR, I'd like to make sure it links to @vcsjones 's blog. We should be explicit about citing the original work. (On our side, we have some tools to make sure the links resolve to a reasonable place in the future...).

I'd also like to make sure we tag @vcsjones in the PR so he can review it.

Thanks again!
