### ISSUE TITLE
There is some findings when I install .NET Core in Windows Server 2016

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [dotnet/docs#17205]
Hi Team,
I'm trying to install .NET Core 3.1.1 in Windows Server 2016. I tested several times and found that VC++2015 distributable is also the prerequisites on Windows Server 2016. 

Additionally, the PowerShell automation method is not working for Windows Server 2016.
I get error message as "dotnet-install.ps1 is not digitally signed. You cannot run this script on the current system." But it could work well in my Win10 1903.

Hope this information is helpful for you. Waiting for your confirmation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1200f60-5ad1-2b1e-067d-07f2dd442915
* Version Independent ID: 0e53d9c7-32ca-1341-f89a-a901a5636a9d
* Content: [.NET Core SDK and runtime dependencies - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows#feedback)
* Content Source: [docs/core/install/dependencies.md](https://github.com/dotnet/docs/blob/master/docs/core/install/dependencies.md)
* Product: **dotnet-core**
* GitHub Login: @leecow
* Microsoft Alias: **leecow**

**Comment by AlexChongMicrosoft** [comment]
An update. I test 1 more time. In my personal Win2016, the PowerShell script worked. But in a new Azure VM with the same OS, It didn't work.

More specifically,  using the installer, I can run it successfully and after installation, I can find it in the C:\Program Files\dotnet\sdk. But without VC++ 2015 redis, the dotnet couldn't be recognized in PowerShell.

**Comment by Thraka** [comment]
Hi @AlexChongMicrosoft welcome to the repo! The PowerShell signing requirement has to do with a security setting on the machine via the `Set-ExecutionPolicy` command. There is an open issue to get the script signed: dotnet/sdk#10581 which avoids this completely. Also, depending on how you downloaded the scirpt, you may need to run the `Unblock-File` command too.

Regarding the the VC runtime, what was the error you got on WinServer that alerted you to the runtime? It just failed to install?
