### ISSUE TITLE
Include Multidimensional Jagged Arrays

### ISSUE THREAD

**Issue by Dragon-God** [dotnet/docs#17202]
I think it would be helpful if an example of a multidimensional jagged array were added, perhaps something like the below:
```cs
int[,][] multiJagged = new int[2, 3][] {
   {
      new int[4], new int[5], new int[2]
   },
   {
      new int[1], new int[9], new int[32]
   }
};
```

An example of a jagged multidimensional array was provided, so I think including an example of a multidimensional jagged array would provide completion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 357a5abc-d84b-f514-101d-b2ca52c6f268
* Version Independent ID: 5936482c-bdcc-f97b-7232-d167eec804e9
* Content: [Jagged Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/jagged-arrays)
* Content Source: [docs/csharp/programming-guide/arrays/jagged-arrays.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/arrays/jagged-arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Dragon-God 

I think I see where you're going, but I'm curious where you've used a multi-dimensional jagged arrays? I'd like to map this feature to real uses.

**Comment by Dragon-God** [comment]
> Thanks for writing this @Dragon-God
> 
> I think I see where you're going, but I'm curious where you've used a multi-dimensional jagged arrays? I'd like to map this feature to real uses.

I actually just started learning C# recently (mostly from the docs). I haven't written much practical code with it yet.

**Comment by BillWagner** [comment]
Thanks for the clarification. For now, I'll close this without action. Readers can infer this capability from the other examples. I'm also not sure how useful this is in practice.

**Comment by ragabmoh** [comment]
Thanks
