### ISSUE TITLE
Not-allowed readonly example in .NET Standard 2.0

### ISSUE THREAD

**Issue by liuxinjia** [dotnet/docs#17214]
**Issue description**

If the property only has a get accessor will cause an error.
```
// Allowed
public readonly int Prop4 { get; }
public int Prop5 { readonly get; }     // It's not allowed in  .NET Standard 2.0
public int Prop6 { readonly get; set; }
```

**Target framework**

- [ ] .NET Standard 2.0

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
CS8664  C# '': 'readonly' can only be used on accessors if the property or indexer has both a get and a set accessor
</details>

**Comment by BillWagner** [comment]
Thanks for writing this @liuxh0 

This is working correctly. C# 8.0 is not supported with .NET standard 2.0. You could edit the csproj by hand to get the C# 8.0 behavior.  See [this article](https://docs.microsoft.com/dotnet/csharp/language-reference/configure-language-version) for more details.

I'll close this as by-design.

**Comment by liuxh0** [comment]
Hi @BillWagner , I think you tagged the wrong person 😅
