### ISSUE TITLE
The PackageIconUrl element is deprecated

### ISSUE THREAD

**Issue by jozefizso** [dotnet/docs#17229]
When I build my package, I get this warning:

```
C:\Program Files\dotnet\sdk\3.1.102\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```

This page documents **PackageIconUrl ** element only. There is no information about **PackageIcon**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for letting us know. We'll update the page, and until that is done you can find the information about `PackageIcon` at https://aka.ms/deprecateIconUrl

**Comment by gewarren** [comment]
Related PR: https://github.com/NuGet/docs.microsoft.com-nuget/pull/2271.

This entire article will be gone tomorrow, with https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props in its place.
