### ISSUE TITLE
missing dotnet-counters commands

### ISSUE THREAD

**Issue by eddynaka** [dotnet/docs#17220]
this page is missing the following commands:
- collect
- ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4dadb56-569e-b390-b118-57c3b0225c13
* Version Independent ID: 50cf6a7e-e95e-a29b-67fd-26747f4440c1
* Content: [dotnet-counters - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#feedback)
* Content Source: [docs/core/diagnostics/dotnet-counters.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-counters.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by sdmaclea** [comment]
The `-p|--process-id` option was renamed to `ps` after the initial release. The documatation was never updated.

/cc @dotnet/dotnet-diag

**Comment by sywhang** [comment]
-p is not the same as ps. It’s —list-processes that was renamed to ps.

**Comment by eddynaka** [comment]
i will create a PR to update the docs, but, probably i will need some help with the "wording"

**Comment by sywhang** [comment]
https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-counters-instructions.md should have some of the wording you are looking for.

**Comment by eddynaka** [comment]
thanks @sywhang ! that will help a lot!
