### ISSUE TITLE
Default versions incorrect for older versions

### ISSUE THREAD

**Issue by chipplyman** [dotnet/docs#17235]
A recent change removed important text "The C# compilers that are part of the Visual Studio 2017 installation or earlier .NET Core SDK versions target C# 7.0 by default."

IMO this text should be re-added, as well as information about langversion defaults for older VS versions.  According to https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing, VS2017 is still supported through 2027 and 2010 is still supported through July of this year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#issue-13937-body)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @chipplyman We should add that back in.

I've added it to our next sprint, and I've added the "up for grabs" label. You've included the text that should be restored in the description of this issue. If community members are interested in submitting a PR for this, we'll watch for it.
