### ISSUE TITLE
Tabs are only for up to V2.1 need 3.1

### ISSUE THREAD

**Issue by djaus2** [dotnet/docs#17242]
**Issue description**

The .NET Core documentation, eg dotnet publish command, only is for V2.1 and below. Need a 3.1 tab, even if nothing is changed.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core  3.1
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>Update documentation for V3.1</strong></summary>
</details>

**Comment by tdykstra** [comment]
@djaus2  The .NET Core CLI documentation was recently updated for 3.1.  Which articles does this issue refer to that aren't yet updated?

**Comment by djaus2** [comment]
OK,
I must have had some older version in my browser cache ??
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
Is updated.

**Comment by djaus2** [comment]
OK
Checked https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
That is OK
