### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by KitPatterson** [dotnet/docs#17248]
What does this property mean? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d82018-baca-ba95-f165-1c8c5be8f45b
* Version Independent ID: 4451cff1-8f80-7350-2c09-7e44b9ee8039
* Content: [AdhocWorkspace.CanOpenDocuments Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.adhocworkspace.canopendocuments?view=roslyn-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/AdhocWorkspace.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/AdhocWorkspace.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
ping @jinujoseph 

Who should I route this toward?

**Comment by jinujoseph** [comment]
Should be roslyn @jasonmalinowski  will you help doc this API

**Comment by BillWagner** [comment]
Issue moved to [dotnet/roslyn #42092](https://github.com/dotnet/roslyn/issues/42092) via [**ZenHub**](https://www.zenhub.com/)
