### ISSUE TITLE
Thread-safe?

### ISSUE THREAD

**Issue by Enigmativity** [dotnet/docs#17253]
This code doesn't appear to be thread-safe and that's an important part of Rx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9b221a-156f-fcbb-f853-374b8a567ea8
* Version Independent ID: 8c32046d-1f4d-7328-de46-d578e250aa83
* Content: [How to: Implement a Provider](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-implement-a-provider#feedback)
* Content Source: [docs/standard/events/how-to-implement-a-provider.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-implement-a-provider.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Joeppie** [comment]
Agreed, perhaps a ConcurrentBag<> is a viable alternative to the use of List<> here.
