### ISSUE TITLE
Missing details on using ref packs, which greatly impacts building projects that target .NET Framework from non-Windows platforms including Linux and MacOS

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs#17265]
The .NET Core SDK will fail when trying to build projects that target a .NET Framework TFM from a non-Windows machine, due to missing reference assemblies. It prints an error which includes a link to this page to acquire a ref pack, but this page doesn't mention acquiring or using ref packs from non-Windows machines, via the newly released ref pack NuGet packages, e.g. Microsoft.NETFramework.ReferenceAssemblies. We update this page and the page at https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies to document the process of using the new ref pack packages for .NET Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers#feedback)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by richlander** [comment]
The scenario isn't really non-windows. This equally applies to Windows machines where you didn't install the right targeting pack.

**Comment by DamianEdwards** [comment]
Indeed, however in that case I believe the URL in the error message would at least direct someone to a page where they can download a Windows ref pack. For non-Windows platforms they land somewhere with no detail on how to fix their problem.

**Comment by richlander** [comment]
This assumes it would be convenient for them to install (what I assumed is an MSI) it. For example, even with Windows DevOps agents, this approach is way more convenient. In any case, I'm pretty sure we agree.

**Comment by DamianEdwards** [comment]
If you're implying that our primary guidance on getting reference assemblies for .NET Framework should be updated to to equally recommend (or even primarily recommend) the new ref pack NuGets, I don't disagree.

**Comment by Thraka** [comment]
@richlander @DamianEdwards What error is this? I feel like if you're using .NET Core to compile a .NET Framework TFM and receive an error, the page that it points to should be in the context of .NET Core, not .NET Framework. Is this error shared by a non-SDK project targeting .NET Framework that is missing?

**Comment by DamianEdwards** [comment]
It's the error that's shown in the build output when targeting a .NET Framework TFM from an SDK-style project. I agree that whatever page it refers to should be relevant to the context in which the error is shown.

**Comment by Thraka** [comment]
OK, re-reading all of this, I think we should update both the pages with something related to this scenario.

However, we should also have the build error point to a troubleshooting page about this specific error, not this conceptual material. Do you want to create an issue on the SDK repo for that?

**Comment by DamianEdwards** [comment]
@Thraka done dotnet/sdk#11243
