### ISSUE TITLE
Local functions cannot be overloaded

### ISSUE THREAD

**Issue by ClickRick** [dotnet/docs#17275]
A method cannot contain two local functions with the same name but different parameters. That is, overloaded local functions are not supported.

void MyMethod()
{
    void MyLocalMethod(int n) { /*...*/ }
    void MyLocalMethod(double d) { /*...*/ } // CS0128
}

The article did not make this clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @ClickRick 

I'd like your thoughts on this. We typically don't exhaustively document what *can't* be done. In the case of local functions, we also didn't mention the following restrictions:
- local functions can't be virtual or abstract
- (related) local functions can't be marked override or sealed
- local functions can't have access modifiers

The restriction on overloads is different, but I'm curious what led you to think overloaded local functions would be supported.

**Comment by ClickRick** [comment]
Virtual/abstract/override/sealed only make sense in certain contexts, most notably in a class, so a stand-alone function wouldn't make sense with those modifiers. 
The article specifically _did_ mention that local functions can't have access modifiers.
Generics are supported. Optional parameters are supported (unsurprisingly).
I came across the case because I found a use for it (one taking an int, and a second one taking a string) and tried to use it, and encountered the compiler error. I worked around it with a rename, which isn't a big deal, but only after first checking here that I wasn't missing something.

**Comment by BillWagner** [comment]
Thanks for adding those remarks @ClickRick 

I've added this to the list of issues we'll address when we next update this article.

**Comment by alexanderdudko** [comment]
This looks very similar to syntax sugar for defining local variables of Func<...> and Action<...>. And that makes it very clear why there cannot be multiple functions with the same name differing only by argument types.
You cannot compile following code:
void MyMethod()
{
var MyLocalMethod = new Action<int>(n => { /.../ });
var MyLocalMethod = new Action<double>(d => { /.../ }); // error
}

**Comment by geoff-m** [comment]
I was just surprised to discover this.

**Comment by Memphizzz** [comment]
I just ran into this issue, the bot seems to have closed this as wont-fix, can we get this reopened @dotnet/docs?
