### ISSUE TITLE
There is no information on how to update to latest patch release

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [dotnet/docs#17274]
For instance, I have 3.1.1 installed, 3.1.2 is out, apt update, apt dist-upgrade does nothing.

Please add documentation on how to update to latest patch release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by BillWagner** [comment]
ping @Thraka

**Comment by Thraka** [comment]
@dagood Does the latest patch release automatically update? Or is everything (no matter what) just treated standalone all the time?

**Comment by dagood** [comment]
Updates from the Microsoft deb package feeds are automatic to the same degree as any other deb package feeds being used by the system. After running `apt update` to fetch new metadata, the system sees that a new version is available, and you can run `apt upgrade` or use your UI to update as you would with any other package.

You can also simply run the instructions again to upgrade. `apt install dotnet-sdk-3.1` will upgrade to the latest version.

`apt dist-upgrade` should also work (it essentially does a "stronger" upgrade).

---

@AlirezaHaghshenas, is it possible you have an out-of-support feed still registered on your machine? (E.g. you originally used .NET Core on Ubuntu 16.10, which set up that feed, and it never got updated to 19.10?)

Can you run this diagnosis step and share the results?

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
```

**Comment by Thraka** [comment]
I'm going to close this as I feel it is resolved. I just tested this and simply rerunning the install instructions (for the appropriate distro) allowed me to upgrade too.

Please feel free to reopen it if you don't feel this is resolved. Thanks!

**Comment by AlirezaHaghshenas** [comment]
@dagood Sorry, I missed the replies to this. Yes the problem was on my side (wrong apt source). But I think if that was written explicitly in the document, I'd be sure where (not) to look.

Thanks

**Comment by dagood** [comment]
That's a good point, I think it would make sense to point out that upgrades *should* work with the Linux package repos, and mention that re-running the repo install code can help fix version divergence (in particular after a distro upgrade).

Actually, since upgrades are a big reason to use the Linux package repos in the first place (rather than installing from binaries), it might be worth calling out even just for that reason.

/cc @NikolaMilosavljevic @leecow

**Comment by Thraka** [comment]
Sounds good. I'll add this to the sprint.
