### ISSUE TITLE
Linux package overview

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#17278]
The download link from https://dotnet.microsoft.com/download for Linux is https://docs.microsoft.com/dotnet/core/install/linux-package-managers.

This gets mapped to 'Ubuntu 19.04':

https://github.com/dotnet/docs/blob/14e406d374236160b3715f453843deb979ff38ff/.openpublishing.redirection.json#L165-L166

This is a bit opinionated. Maybe there can be a page that list different Linux distros?

The left menu for 'Linux package managers' has distros in alphabetical order, except for Ubuntu which sits at the top. Maybe these list could be completely alphabetical?

**Comment by BillWagner** [comment]
Thanks for writing this up @tmds 

ping @Thraka I think this is a side-effect of an accessibility change made a while ago that changed how cascading menus operator. Where should this go?

**Comment by Thraka** [comment]
I have to choose at least one page. I believe we chose alphabetic but kept the most popular at the top. One of the ubuntu articles gets 40,000+ page views while all the others get around 3000 or less.
