### ISSUE TITLE
How to Generate the Docs Locally?

### ISSUE THREAD

**Issue by lazaridiscom** [dotnet/docs#17272]
I like the documentation very much, especially the full-toc-pdf dowload and the MD-source usage:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/

Me trying to convince the isocpp cpp guideline-project to adopt this style of docs (https://github.com/isocpp/CppCoreGuidelines/issues/1575).

Yet it seems that the documentation-generator is not publicly available.

Any chances to get access?

## Project Related

Of course this would be good for this project, too, as contributors could verify their changes locally.

**Comment by BillWagner** [comment]
cc @dend @rloutlaw Should this issue be moved to MicrosoftDocs/Feedback?

**Comment by lazaridiscom** [comment]
(General Remark: github is not the right place for documentation workflow, especially not for an organization of the size of Microsoft. Even the "Repository Listing" does not work for organizations like MS => Missing sub-organizations)

Now, my issues affects "Contribution Process Mentioned within this Repo", namely to "provide the means to generate the docs locally" => developer related.

Whereas "MicrosoftDocs/Feedback" **"is the place to provide any comments, suggestions or ideas on docs.microsoft.com site functionality."**, thus user related.

Looks like my issue should be processed here.

**Comment by Thraka** [comment]
The generator is available at <https://github.com/dotnet/docfx>. However the theme and site design that docs.microsoft.com uses I don't think is publicly available. If you wanted that, you would probably need to request it at the suggested MicrosoftDocs/Feedback.

Being able to preview suggested changes to the docs is something that is still in review by the MicrosoftDocs/Feedback team. Public review is something our team has requested and brought up a lot. Our .NET documentation is built and published in the MicrosoftDocs pipeline that Microsoft has set up. These suggestions have to be implemented by the MicrosoftDocs team.

I hope that helps.

**Comment by lazaridiscom** [comment]
> I hope that helps.

Yes, very much. I guess https://github.com/dotnet/docfx was what i was looking for.

So, I'm good (please feel free to close).
