### ISSUE TITLE
interface members can't have a defination

### ISSUE THREAD

**Issue by VilasMahalle** [dotnet/docs#17276]
public interface IControl
{
    void Paint() => Console.WriteLine("Default Paint method");
}
interface members can't have a defination, please remove above code lines.

**Comment by svick** [comment]
They can, starting with C# 8.0/.Net Core 3.0, thanks to [default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#default-interface-methods). Though I think the article could be clearer that this is a new feature and provide a link with more information.

**Comment by svick** [comment]
cc @BillWagner (who [added this code](https://github.com/dotnet/docs/pull/17093) to [the article in question](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation))

**Comment by BillWagner** [comment]
Thanks for writing this @VilasMahalle 
As @svick points out, interfaces may define a default implementation for some member types starting in C# 8.

I've add this issue to the current sprint to clarify that this feature is only available in C# 8, and to link to the other articles where this is discussed.
