### ISSUE TITLE
Incorrect function reference?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#17273]
"Some of these Run methods, such as the Task.Run(Func&lt;Task&gt;) overload, exist as shorthand for the TaskFactory.StartNew method. Other overloads, such as Task.Run(Func&lt;Task&gt;),"

The same method is referenced twice here. I'm not sure that makes sense.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabcc3ba-9033-c65f-8969-482a436d510b
* Version Independent ID: a74714e2-d059-e33f-a8c6-591d988ef2a4
* Content: [Consuming the Task-based Asynchronous Pattern](https://docs.microsoft.com/en-gb/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern)
* Content Source: [docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @martingbrown 

I've added it to our backlog to address when we next update this article.
