### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by paulmarshall** [dotnet/docs#17280]
Is there an option to download the tool locally (as a package) and to install from that package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
You can download the .nupkg file from Nuget.org to a local directory and point to that directory with the `--add-source` option. For an example of installing from a local directory, see the [local tools](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use) or [global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-use) tutorials.
