### ISSUE TITLE
Breaking change not listed.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/docs#17293]
Looks like this is a breaking change not listed for 3.1: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcoptions.suppressimplicitrequiredattributefornonnullablereferencetypes?view=aspnetcore-3.1

which change the behavoir of previously non `[Required]` properties. More info:
https://github.com/aspnet/jquery-validation-unobtrusive/issues/121 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e30db5-f35e-a132-1711-db051ca1d719
* Version Independent ID: da256018-fd78-2eb5-4c6c-7a6e93eaeda6
* Content: [Breaking changes, version 2.2 to 3.1 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1)
* Content Source: [docs/core/compatibility/2.2-3.1.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/2.2-3.1.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@scottaddie This sounds like a change in ASP.NET Core. Can you take a look to see if it needs to be documented here?

**Comment by scottaddie** [comment]
@ryanbrandenburg Should there be a corresponding breaking change issue in the aspnet/Announcements repo?

**Comment by ryanbrandenburg** [comment]
I'm not 100% sure I understand the context here but I suspect this wasn't a change in Asp.NET Core so much as a side-effect of upgrading to C# 8. @mkArtakMSFT did we have a C#8/nullable point-person?

**Comment by gewarren** [comment]
@BillWagner is our C# writer.

**Comment by Bartmax** [comment]
@ryanbrandenburg yes, you are correct. This is a side-effect of upgrading to nullable c#8. An unexpected one, but not "really" a breaking chance on itself. 

Not sure what's the best place for visibility so one knows about it. 

Is there a doc with all the side effects after moving to c#8? Maybe we can collect all those in one place? I know ef core have some recommendations.

**Comment by Bartmax** [comment]
I was referring to this doc

https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types

**Comment by pranavkm** [comment]
The feature is documented out as part of https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute. `Required` in MVC means non-null. Marking a property as non-null is effectively equivalent to applying a `RequiredAttribute` on it. 

From your other issue

> (the enabled one is marked as required on client-side validation) but will not trigger an error on the server/binding side)

Can you file an issue in https://github.com/dotnet/AspNetCore with a minimal repro app that exhibits this behavior? Required validation should be applied both on the server and the client by default.

**Comment by scottaddie** [comment]
@Bartmax As requested by Pranav ☝️ , please open an issue in the ASP.NET Core engineering repo. Closing this issue, as the behavior is already documented.
