### ISSUE TITLE
NuGet.config: globalPackagesFolder coverage

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#1730]
Opened per https://github.com/dotnet/docs/pull/1725

Per @Redgwell: Adds a new *NuGet.Config* section which includes the otherwise undocumented behaviour of `dotnet restore` with the `globalPackagesFolder` setting.

This is an alternative to users who rely upon the previous repositoryPath behaviour.

```
NuGet.Config

Restore obeys some values from the NuGet.Config file in the solution folder.

Config key: globalPackagesFolder

Usage:

<config>
  <add key="globalPackagesFolder" value="./packages" />
</config>

Adding the `globalPackagesFolder` config value to the solution NuGet.Config file will place 
the restored nuget packages in the specified folder. This is an alternative to specifying the 
`--packages` command line argument.
```

We prob need a better spot for NuGet.config documentation than added to the end of the `dotnet restore`; however, linking to this from the command doc is a good idea imo.

**Comment by Redgwell** [comment]
I'm happy to write this up in an appropriate place - just let me know where it should go.

**Comment by GuardRex** [comment]
@Redgwell I've spent more time with the ASP.NET Core docs, so I'm just getting my bearings over here. @mairaw will definitely know if/where we have anything on *NuGet.config* or if there's a plan to get something over here on it. In the end, this might end up right back where you had it, but let's see if there's a good spot (or a spot coming up with a new doc in the future).

**Comment by mairaw** [comment]
There is a doc on that file on the Nuget docs: https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

I think we should mention that the behavior of the `dotnet restore` command can be affected by the settings on that file and link to that topic?

@blackdwarf any thoughts on that?

**Comment by Redgwell** [comment]
In addition, in that linked doc it states:

> globalPackagesFolder applies only to projects using project.json.

So that should probably be amended.

**Comment by mairaw** [comment]
I'll open an issue for that one in their repo.

**Comment by GuardRex** [comment]
@mairaw @blackdwarf If you decide you like this link/comment in the `dotnet restore` doc, I can still squeeze it in on the commands PR.

**Comment by Redgwell** [comment]
I've created a PR for that issue raised against the docs.microsoft.com-nuget repo.

**Comment by GuardRex** [comment]
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file will get updated from PJ to csproj soon-ish I imagine.

@mairaw Do you want me to add a reference to the `globalPackagesFolder` to `dotnet restore` command now while we still have the commands PR in the bullpen?

It'll get an issue closed here if we do. :+1:

**Comment by Redgwell** [comment]
The nuget docs have been [updated with my PR](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file).

**Comment by mairaw** [comment]
The topic in NuGet is still mentioning project.json and the row for the globalPackagesFolder still says project.json only. @kraigb are you guys removing project.json references from the NuGet docs? 

Let's add some info with a link to that topic in NuGet from dotnet restore @GuardRex. Thanks!

**Comment by GuardRex** [comment]
@Redgwell Thanks for flagging us on this! :rocket:

**Comment by kraigb** [comment]
We'll be maintaining project.json for the foreseeable future, because it's still used in legacy project types and the NuGet docs need to cover all versions.

**Comment by GuardRex** [comment]
@kraigb The spot in the table where it states "(`project.json` only)" ... should that say something like "(`project.json` and VS 2017 projects only)"?
