### ISSUE TITLE
Metadata object serialization

### ISSUE THREAD

**Issue by aramacciotti** [dotnet/docs#17313]
Is it possible to add a typed object to Metadata? Otherwise, how it has to be serialized/deserialized to be compliant with System.ServiceModel.Channels.MessageHeader?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6abff99-6bed-86bc-be01-440e8ef690f7
* Version Independent ID: 198fbbc5-8def-53ca-179a-5efa2f1476f9
* Content: [Metadata - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/metadata)
* Content Source: [docs/architecture/grpc-for-wcf-developers/metadata.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/metadata.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by shirhatti** [comment]
There's no first class of adding a typed object to metadata. We do however allow you to supply a byte[] as the metadata value.

What are you trying to accomplish?

cc @JamesNK

**Comment by JamesNK** [comment]
Metadata is placed in HTTP headers which are string based. If you want to send a typed object in a header then you will need to serialize and deserialize it yourself.

**Comment by aramacciotti** [comment]
Thanks, I got that. What I was asking is a suggestion about how they are serialized by a WCF client in order to correctly deserialize in a gRCP service

**Comment by aramacciotti** [comment]
> There's no first class of adding a typed object to metadata. We do however allow you to supply a byte[] as the metadata value.
> 
> What are you trying to accomplish?
> 
> cc @JamesNK

I need to migrate a WCF service to a .Net Core service without requiring any change in the multiple WCF clients that currently consume them. I'm checking if gRPC is a possible solution and at the moment I see as a possible issue the fact that such WCF services are expecting some objects in the headers (obviously they are serialized and deserialized but it happens in background by the .Net Framework).
I'm asking if you already analyzed that and can suggest a way to manage
