### ISSUE TITLE
Update use of HttpClientHandler to SocketsHttpHandler

### ISSUE THREAD

**Issue by valleyjo** [dotnet/docs#17322]
Looks like starting with .net core 2.1+ the preferred HttpMessageHandler implementation is SocketsHttpHandler not HttpClientHandler  as listed in this page's example.

This page should be updated to reflect this guidance.

Source: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1&viewFallbackFrom=netframework-4.8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63bd3e95-13d1-59d1-a317-85eae2fb4fae
* Version Independent ID: 6728699b-f527-2f98-35ec-425dca05b7cd
* Content: [Channel credentials - gRPC for WCF Developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/channel-credentials#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/channel-credentials.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/channel-credentials.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by shirhatti** [comment]
Starting with .NET Core 2.1, the `HttpClientHandler` by default uses `SocketsHttpHandler`. There's no need to explicitly new up a `SocketsHttpHandler`. The supplied code sample is reflective of this guidance

**Comment by shirhatti** [comment]
Feel free to re-open if you have follow-up questions

**Comment by valleyjo** [comment]
Got it thanks for the explanation.
