### ISSUE TITLE
Unit tests project creation does not work at all

### ISSUE THREAD

**Issue by glestwid** [dotnet/docs#17339]
VS2019 v16.4.5, generated unit tests based on MSTest:
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FinService.MSTests
{
    [TestCase]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
        }
    }
}
Tried to build it - got these errors:
1&gt;  UnitTest1.cs(5,6,5,14): error CS0246: The type or namespace name 'TestCaseAttribute' could not be found (are you missing a using directive or an assembly reference?)
1&gt;  UnitTest1.cs(5,6,5,14): error CS0246: The type or namespace name 'TestCase' could not be found (are you missing a using directive or an assembly reference?)
1&gt;Done building target "CoreCompile" in project "FinService.MSTests.csproj" -- FAILED.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET Standard class library with .NET Core in Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio#feedback)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
@glestwid I verified the behavior you saw as well. This seems like a problem in the MSTest project template in Visual Studio. To resolve the problem, I opened the NuGet package manager (right-click on the Packages node under Dependencies, and then choose Manage NuGet Packages), went to the Updates tab, selected all the packages, and then clicked Update.

I'm closing this issue now since it's not a documentation issue, but let us know if the above steps don't solve the problem for you. Hopefully this will be fixed in a future version of Visual Studio.

**Comment by glestwid** [comment]
Yes, I can confirm that these steps fixed the issue. But I would like to have it fixed in the corresponding project template instead.

**Comment by gewarren** [comment]
@glestwid I don't actually see an existing issue for this on Developer Community, so could you create one there? https://developercommunity.visualstudio.com/content/problem/post.html?space=8

**Comment by glestwid** [comment]
@gewarren here's the link - [https://developercommunity.visualstudio.com/content/problem/939146/vs2019-cant-create-a-unit-test-project-for-net-cor.html](url)

**Comment by gewarren** [comment]
@glestwid Thanks very much! I hope they fix it soon!
