### ISSUE TITLE
Documentation should specify Timer Coalescing Behaviour, if any

### ISSUE THREAD

**Issue by lokitoth** [dotnet/docs#17336]
Right now, someone interested in whether they can use the built-in Timer to take advantage of Timer coalescing on systems that support it have to navigate a fair ways into the dotnet/runtime repo to track this down:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Threading.Timer/src/System.Threading.Timer.csproj

to 

https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Timer.CoreCLR.cs

to 

https://github.com/dotnet/runtime/blob/58ee1305580774e6791ad1b31d01f7f7effb5780/src/coreclr/src/vm/comthreadpool.cpp

to

https://github.com/dotnet/runtime/blob/f30ea373a5650cb17deb3df3657e644513410fd7/src/coreclr/src/vm/win32threadpool.cpp

And even then it is not immediately obvious what the answer is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a121a52-2dce-2b42-feba-2d859c7cea39
* Version Independent ID: f537cd9c-3f14-c794-143b-62c679ad81c8
* Content: [Timers](https://docs.microsoft.com/en-us/dotnet/standard/threading/timers#feedback)
* Content Source: [docs/standard/threading/timers.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/timers.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@lokitoth It doesn't seem like this is exposed to the user and wouldn't be something we document. 

@kouvel Perhaps you can shed some light on this scenario.

**Comment by lokitoth** [comment]
It is a question of whether, for being good citizens with respect to battery life developers can just use the Timer class in the class library, or whether they have to do per-platform invocations to OS' underlying coalesced timers to do so, likely via P/Invoke.

It is not about whether this is exposed to the user as much as it is whether they get used automatically. (At the same time, developers who do not want this behaviour probably would like a way to disable it)

**Comment by kouvel** [comment]
The current implementation does not use timer coalescing capabilities of the system. There aren't any plans currently that I'm aware off to add it.

**Comment by lokitoth** [comment]
Thanks for confirming
