### ISSUE TITLE
Example is misleading. + operator now permitted in C# 8.

### ISSUE THREAD

**Issue by DurdSoft** [dotnet/docs#17332]
With C# 8, this is now permitted in the form:
```
public interface IA
{
    public static int operator +(IA aa, int bb) => bb;
}
```

A better example may be:

```
public interface IA
{
    public static implicit operator int (IA a) => 0;
}
```

The issue description doesn't match the VS warning either:
`CS0567	Interfaces cannot contain conversion, equality, or inequality operators`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d079b75c-4681-ea98-0d2b-1cabcd3cc81b
* Version Independent ID: dc8cf226-d055-a965-7372-f69090d423ad
* Content: [Compiler Error CS0567](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0567)
* Content Source: [docs/csharp/misc/cs0567.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0567.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @DurdSoft  I like your suggested example.

I've added this to our backlog to address when we next update this article.

I've also added the "up for grabs" label, if you or others want to submit a PR for this issue before we update the article.
