### ISSUE TITLE
Problem loading appsettings.json

### ISSUE THREAD

**Issue by bruzkovsky** [dotnet/docs#17331]
I followed this tutorial to setup my Dockerfile like this:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
COPY host/iCL.Workflows.HttpApi.Host/bin/Release/netcoreapp3.1/publish/ app/

ENTRYPOINT ["dotnet", "app/iCL.Workflows.HttpApi.Host.dll"]
```

I noticed that the appsettings.json was not loaded. Then I found this answer on SO:
https://stackoverflow.com/a/43644916/13005218

The proposed solution is to copy the appsettings.json into the root directory, but I found that setting the `WORKDIR /app` instruction will also work. Could you update this in the documentation?

Final Dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
COPY app/bin/Release/netcoreapp3.1/publish/ app/
WORKDIR /app

ENTRYPOINT ["dotnet", "myapp.dll"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container#feedback)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
This article is for .NET Core console apps, not ASP.NET Core. At the start of the article there is a tip bubble. I'm curious if your eyes glanced past it? Perhaps I should change the message or make it a warning instead?

![image](https://user-images.githubusercontent.com/2672110/76113321-c996ea80-5f98-11ea-8ff8-272e6eff558d.png)

**Comment by bruzkovsky** [comment]
You are right I totally missed that one! Maybe it is more visible as a warning, but maybe it was just too late in the night =_= :-)
