### ISSUE TITLE
Value types are objects!

### ISSUE THREAD

**Issue by ericlippert** [dotnet/docs#17335]
Hey Bill and the rest of the team, 

I am not super happy with how this page treats "object". It strongly implies that variables of value type are not "real" objects, but they are; you can call methods on them without boxing, for instance. It's not the case that in C# an int "becomes an object on demand". It already is an object; values of value type are objects in the C# type system. (The C# type system is of course implemented on top of the CLR's type system, which does make a stronger distinction in the type system, but this documentation is about the C# type system, not its implementation details.)

A more accurate way to describe the C# type system here is that *sometimes you need to convert a value of value type to a value of a reference type, and in those cases the value will automatically be boxed*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for spotting this @ericlippert I agree!

I've added this to our next sprint to address.  (I reviewed this last month, and I should have spotted this myself, but I was focusing on other outdated content.)
