### ISSUE TITLE
No Auto-generate binding redirects option

### ISSUE THREAD

**Issue by afbarksd** [dotnet/docs#17346]
The article tells us "If you have Visual Studio 2017 version 15.7 or later, you can easily disable autogenerated binding redirects in the project's property pages.", "Right-click the project in Solution Explorer and select Properties.", and "On the Application page, uncheck the Auto-generate binding redirects option."  I have Visual Studio 2017 version 15.7.2 and tried to follow these steps for a VB.NET project.  The Application page lacks a Auto-generate binding redirects option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [Enable or disable autogenerated binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#feedback)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
@afbarksd It should appear something like this. Do you still not see it? If so, what kind of project did you create?

![image](https://user-images.githubusercontent.com/24882762/76068035-14186700-5f99-11ea-8022-0cb825de2194.png)

**Comment by afbarksd** [comment]
It is a WPF application.  I attach files with excerpts from the About box and Application tab.
![VS2017About](https://user-images.githubusercontent.com/17550264/76097119-c0a01c00-5f8c-11ea-9460-569653c96aa8.png)
![VS2017About](https://user-images.githubusercontent.com/17550264/76097139-c85fc080-5f8c-11ea-8751-3ca979b25e7f.png)

**Comment by gewarren** [comment]
I'm not sure if the option is supposed to be present for WPF projects. @thraka Do you know? As a workaround, you could add the following to the .csproj file manually:

```
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

**Comment by afbarksd** [comment]
Thanks. I already tried adding AutoGenerateBindingRedirects and GenerateBindingRedirectsOutputType manually, and they didn't seem to do anything.  For the time being, I worked around the problem by rebuilding everything in my development with the same versions of the DLLs.

**Comment by Thraka** [comment]
I checked the latest Visual Studio 2019 VB WPF and CS WPF projects and both have that UI option. I'm guessing there must have been a restriction with VB at the time/version of Visual Studio you're using. Can you upgrade to 2017 15.9? That is the latest supported release for 2017. Otherwise you may want to ask the Visual Studio team.
