### ISSUE TITLE
Link to Samples doesnt show anything related at all

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/docs#17342]
Since the destination has been redirected, there are no more samples for Parallel Programming shown. One might want to dig through hundreds of Azure topics to possibly find something related to parallel...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978ca292-3e23-29fe-1ffc-3c2235ade37a
* Version Independent ID: 764db72b-40c8-5f13-1941-b6c022f006f9
* Content: [Task Parallel Library (TPL)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl)
* Content Source: [docs/standard/parallel-programming/task-parallel-library-tpl.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-parallel-library-tpl.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
See #13649

The right fix here is to follow the instructions in #13921 to update and load these samples in the new [Samples browser](https://docs.microsoft.com/samples) experience.
