### ISSUE TITLE
Format for KB, MB, GB, etc.

### ISSUE THREAD

**Issue by LukeChung** [dotnet/docs#17353]
The format #,#, is nice for adjusting by 1000. Is there a way to adjust 1024 to turn bytes into KB (and more)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f543acea-d042-bbcf-5f83-de8b11644366
* Version Independent ID: 18c2ed9b-4015-109c-1ac2-b9b39ed19e8b
* Content: [Custom numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings?redirectedfrom=MSDN)
* Content Source: [docs/standard/base-types/custom-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-numeric-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello!

I'm sorry, but I don't know. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow.

I'm going to close the issue. 

Thanks.
