### ISSUE TITLE
Split out strategies for approach nullability from the attributes themselves

### ISSUE THREAD

**Issue by davkean** [dotnet/docs#17356]
I hit this page last night looking for some attributes to fix some nullable warnings I hit, and skipped it because the first bullet was "Choosing a nullable strategy" with the thinking that I'd already picked one so this page wasn't going to help me. I've been since pointed out this was the page that was going to help me. I think we should pull the attributes out separately from the approach because you are going to use them at different points in the lifecycle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17290c4d-73f0-5ae1-e8ba-c039fe9fe9ca
* Version Independent ID: 59e0e3bb-b2e5-3ced-72d9-42e641b3897f
* Content: [Upgrade APIs for nullable reference types with attributes that define expectations for null values](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-attributes#conclusions)
* Content Source: [docs/csharp/nullable-attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @davkean 

This month, my focus is to finish all things related to C# 8.  I've added this to the current sprint.

**Comment by Bosch-Eli-Black** [comment]
I just ran into this issue, too :)  I had read through the documentation and seen that there were attributes that affected nullability, but when I went back through the documentation later, I had a hard time finding them.

**Comment by BillWagner** [comment]
I wrote the plan on https://github.com/dotnet/docs/issues/16488#issuecomment-611189456
