### ISSUE TITLE
It's an enum, not a bool

### ISSUE THREAD

**Issue by rdeago** [dotnet/docs#17357]
"true if documentation comments are parsed, false otherwise" looks like a leftover from some previous version when there was no DocumentationMode enum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54a9904-6b24-ebe4-bf78-04d85c4dc7c0
* Version Independent ID: 2f4c9571-4085-8153-198e-abd4ec120f3a
* Content: [ParseOptions.DocumentationMode Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.parseoptions.documentationmode?view=roslyn-dotnet#Microsoft_CodeAnalysis_ParseOptions_DocumentationMode)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/ParseOptions.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/ParseOptions.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@rdeago Thanks for noticing this discrepancy!
