### ISSUE TITLE
Missing nullable class constraint 

### ISSUE THREAD

**Issue by davkean** [dotnet/docs#17355]
This is missing the nullable constraint:

``` C#
#nullable enable

public class Foo<T>
        where T : class?
    {
    }
```

I think it also incorrectly talks about the `class` constraint, under nullable, it becomes "The type argument must be a non-nullable reference type.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on type parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters?source=docs)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @davkean I had missed this. 

I've added it to our April sprint.
