### ISSUE TITLE
Where are the Result (and all other) module docs?

### ISSUE THREAD

**Issue by jhugard** [dotnet/docs#17369]
Having extreme difficulty locating documentation for all F# Module functions, such as `Result.map`, `List.map`, `Seq.cast`, and everything else needed to use F# types!

Where, oh where, have they all gone?

For `List.map`, found the following link but (a) it's marked as deprecated and (b) the navigation tree is broken and cannot be used to navigate to individual module functions:
* https://msdn.microsoft.com/visualfsharpdocs/conceptual/collections.list-module-%5bfsharp%5d

E.g., clicking on `Collections.List.map` links to the root of F# language reference, and no ability to actually find ANY documentation on `List.map`!
* https://docs.microsoft.com/en-us/dotnet/fsharp/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eede22c-dda8-85ec-d896-0a03b31a0116
* Version Independent ID: 5fa25041-c976-7751-07da-60aab9e97ae5
* Content: [Results - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/results#feedback)
* Content Source: [docs/fsharp/language-reference/results.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/results.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by canndrew** [comment]
Same problem here. I'm fairly new to F# and all the docs I need to do my job have disappeared :/

**Comment by jhugard** [comment]
Push comes to shove, you _could_ browse the `FSharp.Core` .fsi interface files:

* https://github.com/fsharp/fsharp/tree/master/src/fsharp/FSharp.Core

E.g., the `List` module is here:

* https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/list.fsi

Still.  Those clearly should be be linked somewhere here in these docs...

**Comment by cartermp** [comment]
You can find the full API reference here: https://fsharp.github.io/fsharp-core-docs/

I'm in the process of updating docs to point to it
