### ISSUE TITLE
Just a code line fix

### ISSUE THREAD

**Issue by Rimbik** [dotnet/docs#17377]
In the event sourcing example line below, a typo for eyes&gt;

integrationEventLogService.MarkEventAsPublishedAsync(
                                                priceChangedEvent); 
to be
_integrationEventLogService.MarkEventAsPublishedAsync(
                                                priceChangedEvent);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 384e5c2c-d3ba-b5ba-260b-65b8e900b78e
* Version Independent ID: 534541bb-0ffe-f7d6-8cc3-22da784c96a6
* Content: [Subscribing to events](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/subscribe-events.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/subscribe-events.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by gewarren** [comment]
Typo is in this section: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#implementing-atomicity-when-publishing-integration-events-through-the-event-bus

**Comment by cloudn9** [comment]
@gewarren Hello, is this open for contribution ? Thank you.

**Comment by gewarren** [comment]
@cloudn9 Yes, it is, thanks!
