### ISSUE TITLE
"dotnet nuget push" can be used for local feeds, but not mentioned

### ISSUE THREAD

**Issue by vivainio** [dotnet/docs#17378]
Currently, it is suggested to use "nuget add -Source c:\mydir" to publish items to local feed for testing.

As it appears, "dotnet nuget push -s c:\mydir" can do this as well. This should be documented here. If this is the currently recommended way to publish to local feeds, it should be highlighted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

**Comment by yangrongwei** [comment]
https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

But .. are these two commands having same folder layout ?

**Comment by vivainio** [comment]
@yangrongwei not currently, but I filed a bug on NuGet on this https://github.com/NuGet/Home/issues/9281
