### ISSUE TITLE
Can't deploy to osx or linux

### ISSUE THREAD

**Issue by ihorbond** [dotnet/docs#17374]
Hi I've created a new win forms .net core 3.1 application without adding any new code, just what was generated by VS. I can publish this app and run on windows with no issues but when trying to publish to either linux or osx I get an error: 

> Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
> System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---
> 
> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
> 
> ===================

My publish config:
Configuration: Release
Target Framework: netcoreapp3.1
Target Runtime: osx-x64

Tried to publish in both: 
Microsoft Visual Studio Enterprise 2019 Preview Version 16.5.0 Preview 4.0
Microsoft Visual Studio Enterprise 2019 Version 16.4.5

Running on Windows 10 Pro

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [Deploy .NET Core apps with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello. Windows Forms app only work on Windows because they use the Desktop SDK which is only supported on Windows.

**Comment by ihorbond** [comment]
@Thraka thank you I see now that cross platform works only for console and web apps but why does visual studio give me the option to publish win forms app to osx or linux then? it's misleading

**Comment by Thraka** [comment]
I guess it must be an oversight in Visual Studio. .NET Core can produce cross-platform binaries, the problem is that the **desktop sdk** referenced doesn't provide those.

You can send feedback to Visual Studio easily by clicking the feedback button in the IDE

![image](https://user-images.githubusercontent.com/2672110/76261255-d6c10d00-6216-11ea-9506-27d2eb62c042.png)
