### ISSUE TITLE
The parent page https://dotnet.microsoft.com/platform/dotnet-standard has not been updated to include .NET Core 3.1

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#17381]
There isn't a way for the community to contribute to the https://dotnet.microsoft.com/platform/dotnet-standard page, is there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jnm2 I don't think there's a community contributor option to update that page, but @mairaw should be able to update it.

**Comment by jnm2** [comment]
Okay, thank you!

**Comment by mairaw** [comment]
Thank you @jnm2. I've opened an issue for us to fix that in the website.

**Comment by gewarren** [comment]
The website has been updated, so I'm closing this issue.
