### ISSUE TITLE
case insensitive use of character classes is unreliable

### ISSUE THREAD

**Issue by jszabo98** [dotnet/docs#17382]
Note that case insensitive use of character classes is unreliable.  Some upper case foreign characters can map to lower case english characters.  For example, the uppercase Turkish `İ` is linked with the lowercase English `i`.  I don't see this being resolved quickly.

```powershell
# powershell
[regex]::ismatch('i', '\P{IsBasicLatin}', 'ignorecase') # non-ascii
True

[regex]::ismatch('İ', '\p{IsBasicLatin}', 'ignorecase') # ascii
True

'i','I' | select-string '\P{IsBasicLatin}'  # non-ascii

i
I
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello. I don't really understand what you're suggesting be changed in the article. The powershell you provided doesn't seem to demonstrate how something isn't working. If it's case insensitive than either an upper I or lower i would be a match for whichever the turkish i mapped to. Yes?

**Comment by jszabo98** [comment]
If my culture was "en-US", I don't understand why powershell would link the English small i or English capital I to the Turkish or "tr-TR" `İ`(0x130) in a case insensitive regular expression test.  

```powershell
'i' -match '[\x80-\uffff]' 
True

'I' -match '[\x80-\uffff]'
True
```

There's also the Kelvin symbol K (0x212a) whose lower case is the regular English small k, but that doesn't present a similar problem:

```powershell
'k' -match '[\x80-\uffff]'
False

'K' -match '[\x80-\uffff]'
False
```

I'm just suggesting that the docs mention to use case sensitive comparisons with these classes.

**Comment by Thraka** [comment]
I'm unsure I'm not an expert in string culture stuff. Even copying your example into a notepad replacement named notepad2 caused the text pasted to transform the turkish i into an english i. So there is something probably in the OS level that is doing this translation, not .NET.

You may have get a bigger audience looking at this question on stackoverflow. These issues are better geared towards some specific addition, problem, or request related to the documentation, but they are prioritized accordingly. So getting an answer to this question may take some time; and stackoverflow may get you that answer sooner.
