### ISSUE TITLE
Bad practice in Log method

### ISSUE THREAD

**Issue by Cyl18** [dotnet/docs#17391]
// An acceptable implementation.
static void Log(ReadOnlyMemory&lt;char&gt; message)
{
    string defensiveCopy = message.ToString();
    // Run in the background so that we don't block the main thread while performing IO.
    Task.Run(() =&gt; {
        StreamWriter sw = File.AppendText(@".\input-numbers.dat");
        sw.WriteLine(defensiveCopy);
        sw.Flush();
    });
}

this method is not thread-safe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines#feedback)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @GrabYourPitchforks @adamsitnik @bartonjs

**Comment by GrabYourPitchforks** [comment]
@Cyl18 What is the problem with the sample?

**Comment by Cyl18** [comment]
> @Cyl18 What is the problem with the sample?

It's not thread-safe, this would lead noobs to do that
umm I think to add a comment says "this is not thread-safe" is ok

**Comment by GrabYourPitchforks** [comment]
The point of the sample wasn't to demonstrate how to write a thread safe method. It was to demonstrate how to write a method that doesn't use the incoming Memory instance after returning. I think including a disclaimer (ostensibly because of the file system access) would complicate the sample and confuse matters.

**Comment by Cyl18** [comment]
> The point of the sample wasn't to demonstrate how to write a thread safe method. It was to demonstrate how to write a method that doesn't use the incoming Memory instance after returning. I think including a disclaimer (ostensibly because of the file system access) would complicate the sample and confuse matters.

maybe my understanding is wrong... thanks
