### ISSUE TITLE
Section on Assembly File Version is a little bit confusing

### ISSUE THREAD

**Issue by JohnH-Work** [dotnet/docs#17393]
It says use the format Major.Minor.Build.Revision, but all of the examples use the format Major.Minor.Revision.Build (taking it literally). Windows software traditionally uses Major.Minor.Build.Revision (e.g. current VS2019 version is 16.4.29806.167), so is the recommendation to stop using that format or are either formats fine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa1275e-9f51-c83e-7cbd-9dfc8abb6dea
* Version Independent ID: 899c196e-4aad-515f-2d04-525719244c69
* Content: [Versioning and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning)
* Content Source: [docs/standard/library-guidance/versioning.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/versioning.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by tdykstra** [comment]
@JamesNK Can you answer this question?
