### ISSUE TITLE
SemaphoreSlim example for using WaitHandle is misleading

### ISSUE THREAD

**Issue by gkarabin** [dotnet/docs#17406]
The SemaphoreSlim example for using WaitHandle with await is not ideal. SemaphoreSlim includes a WaitAsync() method of its own, and the example uses it, rather than using the WaitOneAsync method defined in this article. I think I understand what to do with this in my code, but it makes a poor reference for communication/discussion with others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3690f5e-7d05-118a-3f52-4f5ad92bf94d
* Version Independent ID: 25ae1988-eefb-c34a-cd6a-c134abba46e8
* Content: [Interop with Other Asynchronous Patterns and Types](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types#from-wait-handles-to-tap)
* Content Source: [docs/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @stephentoub for the correct guidance here.

**Comment by stephentoub** [comment]
The content is misleading.  It first introduces this WaitOneAsync method, which is fine, but then it suggests that's somehow useful with SemaphoreSlim... but the SemaphoreSlim example doesn't use this WaitOneAsync method, nor should it.  Everything from "For example, if you want to throttle" to the end of that section should just be deleted.

**Comment by Thraka** [comment]
@BillWagner I added the category, I'll let you add a priority. Cheers!
