### ISSUE TITLE
Reuse the model created in the price prediction (regression) example

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17402]
Hi team, 
I moved this from here: https://github.com/dotnet/docs.ko-kr/issues/233

@jangsungLee commented 23 hours ago — with docs.microsoft.com
Hi. I was looking for a library to make machine learning with C#, and I found Microsoft.ML
I ran the example you gave me, and the problem is that I want to make a file of the model, like "Model.zip," and then recreate, load, and relearn the model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predict prices using regression - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Thanks @CeciAc 

@jangsungLee please take a look at the following Docs.

- Save and load the model: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net
- Use the model to make predictions: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net
- Retrain a model: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net
- Deploy to ASP.NET Core Web API: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net
- Deploy to Azure Functions: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-serverless-azure-functions-ml-net

Also, here's more samples (although step-by-step documentation on how to build them is limited). However, you can reference the concepts from Microsoft Docs.

- ML.NET Samples: https://github.com/dotnet/machinelearning-samples
