### ISSUE TITLE
Add source code for example project in guide (most importantly SeedWork)

### ISSUE THREAD

**Issue by stefan-schweiger** [dotnet/docs#17418]
This guide contains many code samples, but it would be great to have the source code for the complete sample project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea0ea53-3bb6-a0ea-9674-384c68a77c2e
* Version Independent ID: 30de872f-039f-02c1-c8a0-27b5d10a13f5
* Content: [Seedwork (reusable base classes and interfaces for your domain model)](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @stefan-schweiger , you can refer [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) for the complete sample project.

**Comment by nishanil** [comment]
Closing this issue. Please feel free to re-open if the above mentioned project is not what you were looking for.
