### ISSUE TITLE
Mention how "private protected" works with InternalsVisibleTo

### ISSUE THREAD

**Issue by mstefarov** [dotnet/docs#17412]
It is not clear based on this page whether or not InternalsVisibleTo works with "private protected" members

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5e6972-0f7a-8bb7-9f5a-0ba75909f9d8
* Version Independent ID: 618c0361-38a0-4d6f-f46a-881db2e4b399
* Content: [private protected - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected#feedback)
* Content Source: [docs/csharp/language-reference/keywords/private-protected.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/private-protected.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @mstefarov 

I'll have to look this up. I've added it to our next sprint.
