### ISSUE TITLE
error NETSDK1004: Assets file project.assets.json' not found

### ISSUE THREAD

**Issue by chandanch** [dotnet/docs#17429]
Following the docs as given here: [https://docs.microsoft.com/en-us/dotnet/core/](https://docs.microsoft.com/en-us/dotnet/core/) 

1. `dotnet new console`
2. `dotnet run`

results in the following error:

_C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'E:\proj\donproj\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [E:\csharp projects\donet-cli-proj\donet-cli-proj.csproj]

The build failed. Fix the build errors and run again._

**Comment by sbittam** [comment]
I am getting same error, would please let me know how to fix it
