### ISSUE TITLE
Error regarding variance

### ISSUE THREAD

**Issue by aidigital** [dotnet/docs#17426]
The Generic interface IEnumerable&lt;T&gt; is covariant.
The article states "Generic interfaces can inherit from non-generic interfaces if the generic interface is contravariant". It should be "[...] if the generic interface is covariant".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0a00a9-fd5d-3aae-9788-d6b324f17599
* Version Independent ID: d54ecf19-fccb-3d6b-d990-81529acf44c3
* Content: [Generic Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-interfaces#feedback)
* Content Source: [docs/csharp/programming-guide/generics/generic-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/generic-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @aidigital 

Yes, that paragraph is incorrect. I've added it to our backlog to update in the near future.
