### ISSUE TITLE
Apparent error in code segment

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17446]
The comments below were machine-translated

@jfcardenas commented on [Wed Feb 26 2020](https://github.com/dotnet/docs.es-es/issues/156)

In "Use the model" section
    var size = new HouseData() { Size = 2.5F };
    var predEngine = mlContext.CreatePredictionEngine&lt;HouseData, Prediction&gt;(model);
    var price = predEngine.Predict(size);
I think the second line should be (Model property missing):
    var predEngine = mlContext.Model.CreatePredictionEngine&lt;HouseData, Prediction&gt;(model);
Since it produces an error as it is.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [¿Qué es ML.NET y cómo funciona? - ML.NET](https://docs.microsoft.com/es-es/dotnet/machine-learning/how-does-mldotnet-work#feedback)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs.es-es/blob/live/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

---

@srvbpigh commented on [Thu Feb 27 2020](https://github.com/dotnet/docs.es-es/issues/156#issuecomment-591771593)

Hello, @jfcardenas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by luisquintanilla** [comment]
Hi @CeciAc 

Thanks for opening this issue. There is no error in this article. Other than the *Hello ML.NET World* snippet, the other snippets are just meant to illustrate the different parts of ML.NET and are not intended to be a guided end-to-end example of how to run your first program. We'll take a look to see how we can make this more clear.

**Comment by luisquintanilla** [comment]
No immediate action on this at the moment. Closing it for now. Feel free to reopen if there are additional issues.
