### ISSUE TITLE
Error when including XML

### ISSUE THREAD

**Issue by mshinnie** [dotnet/docs#17447]
So when moving the XML to its separate page I get this warning on all of my includes 

Unable to include XML fragment 'docs/members[@name="math"]/Math/*' of file 'docs.xml' -- References to XML documents are not supported.
Any advice on resolving this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@mshinnie I'd need more context and specifics on what you did to help resolve this

Another suggestion is to ask this on StackOverflow, or see if a similar question has already been asked and answered.

**Comment by mshinnie** [comment]
I am running it on VS Code after running the dotnet new console command i copied and pasted the Math and docs.xml file.  I am using dotnet version 3.1.101.  Which other information would be helpful for troubleshooting?
