### ISSUE TITLE
The theme is a bit less colored

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17458]
The comments below were machine-translated

@Elliot-zjy commented on [Fri Mar 13 2020](https://github.com/dotnet/docs.zh-cn/issues/536)

The black and white words are too bright, all white pages are very tired, high contrast and more dazzling, I hope to add a few more mild colors, such as light green sheepskin volume

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 13c78b71-c023-5c22-f2de-accd4a6fa7e5
* Version Independent ID: 73a112db-0e66-0697-b4a3-9b88cbd981fc
* Content: [C# 委托 - C# 语言介绍](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/delegates#feedback)
* Content Source: [docs/csharp/tour-of-csharp/delegates.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tour-of-csharp/delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Fri Mar 13 2020](https://github.com/dotnet/docs.zh-cn/issues/536#issuecomment-598665273)

Hello, @Elliot-zjy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
@CeciAc  This is about the site experience. I'll move to the MicrosoftDocs feedback repo.

**Comment by tdykstra** [comment]
This issue was moved to MicrosoftDocs/feedback#2850
