### ISSUE TITLE
Update reducing package dependencies for csproj or remove it?

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1745]
I was looking at a tweet from a customer about this topic:
https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/reducing-dependencies
and I've noticed this article has been completely out of the radar because it wasn't linked from the TOC. 

This needs to be updated for csproj and added to TOC, or removed. 

@dsplaisted @livarcocc who could help with this? is it still applicable given the fact that the NetStandard.Library metapackage is implicitly referenced when you're targeting netstandard?

**Comment by livarcocc** [comment]
This is for project.json, so I don't think we should do anything about it. As for msbuild and 2.0. The packages won't be metapackages anymore.

**Comment by mairaw** [comment]
@livarcocc We're removing or upgrading all topics related to project.json from our docs. So I'm guessing we should remove this one then.

**Comment by mairaw** [comment]
@ericstj would you know? should https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/reducing-dependencies be replaced with what's in this topic https://github.com/dotnet/standard/blob/master/Microsoft.Packaging.Tools/docs/trimming.md?

**Comment by lostmsu** [comment]
@mairaw Microsoft.Packaging.Tools does not seem to be available in Nuget.org

**Comment by cartermp** [comment]
We should just remove it.  It's unlinked from the TOC anyways because it's a somewhat controversial topic.

**Comment by atifaziz** [comment]
> it's a somewhat controversial topic

@cartermp Care to expand on the why?

**Comment by ericstj** [comment]
We do plan to release some version of Microsoft.Packaging.Tools along with NETCore 2.0.  Eventually it will get better with some of the linker work that's going on, which may impact how you interact with it in the future.  
@Petermarcu do you think we should put the docs for trimming on docs.microsoft.com?

**Comment by leftler** [comment]
@cartermp the page might not be in the TOC but it is linked to from https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/managing-package-dependency-versions in the section "Are you trimming your NETStandard.Library or Microsoft.NETCore.App metapackage dependencies?" and that managing versions page is highly ranked on google.

**Comment by droyad** [comment]
For those looking for the trimming doc mentioned above: https://github.com/dotnet/standard/blob/master/Microsoft.Packaging.Tools.Trimming/docs/trimming.md

**Comment by mairaw** [comment]
Pinging @ericstj and @Petermarcu on this one again to see if anything changed since last time this issue was discussed.

**Comment by Petermarcu** [comment]
We should sync up with the folks working on the Linker https://github.com/dotnet/announcements/issues/30 to figure out when docs would be appropriate. The Trimming tooling is effectively now merged into the Linker so that will be where it eventually ships.

**Comment by BillWagner** [comment]
closed due to lack of action.
