### ISSUE TITLE
Add test cases to the examples

### ISSUE THREAD

**Issue by theprash** [dotnet/docs#17457]
Please can you add edge case test cases to the examples, so we can see specific SDK versions that are allowed and disallowed by the global.json restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#feedback)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Please clarify what you mean by "edge test cases."  What scenarios are you referring to?

**Comment by theprash** [comment]
For example:

> For the above global.json, v3.1.199 is not allowed, v3.1.200 is allowed, and v3.1.300 is not allowed.

Concrete examples make it easy to quickly understand the difference between `latestPatch` and `latestFeature` without carefully parsing the definitions.
