### ISSUE TITLE
Example code is always helpful.

### ISSUE THREAD

**Issue by afbarksd** [dotnet/docs#17452]
Example code is always helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81cff694-3fc8-6aa0-77a0-6dbd34835bc8
* Version Independent ID: 5d017478-4c9b-a772-dc37-4f41b8e9f51a
* Content: [Generic Delegates for Manipulating Arrays and Lists](https://docs.microsoft.com/en-us/dotnet/standard/generics/delegates-for-manipulating-arrays-and-lists)
* Content Source: [docs/standard/generics/delegates-for-manipulating-arrays-and-lists.md](https://github.com/dotnet/docs/blob/master/docs/standard/generics/delegates-for-manipulating-arrays-and-lists.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
FYI The individual methods are links to the API reference. Each of the reference pages have examples.

These could easily be ported to this article to enhance the readability.
