### ISSUE TITLE
Resiliency difficult to read

### ISSUE THREAD

**Issue by Jester98x** [dotnet/docs#17451]
Under the intro to Resiliency is this sentence "What happens when Service C becomes up temporarily unavailable and other services calling it stack and degrade system performance?"
It looks like "up" is not needed and I don't know what "... calling it stack and degrade system performance?" means. Are there some words missing here or is the word stack the wrong word?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03831099-3360-98e5-d35b-934a024f88e0
* Version Independent ID: 7bf71b44-4b61-9832-28c2-8f4881199829
* Content: [Defining Cloud Native](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/definition)
* Content Source: [docs/architecture/cloud-native/definition.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/definition.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by robvet** [comment]
Jester, thanks so much for your feedback. We will revisit that section and adjust accordingly based on your observations.

**Comment by robvet** [comment]
This was corrected when we refactored this chapter.

Let's close this issue.
