### ISSUE TITLE
Document that "MMM" and "MMMM" have somewhat different behavior for some locale such as Japanese

### ISSUE THREAD

**Issue by Kryptos-FR** [dotnet/docs#17455]
**Issue description**

Some locale such as Japanese ("ja-JP") or Chinese ("zh") have suprising rules for "MMM" and "MMMM".
I think the documentation should include a note or warning in  `docs/docs/standard/base-types/custom-date-and-time-format-strings.md`.

For example:

```csharp
WriteLine(string.Format(CultureInfo.GetCultureInfo("ja-JP"), "{0:dd-MM-yy}", DateTime.Now));
// 13-03-20
WriteLine(string.Format(CultureInfo.GetCultureInfo("ja-JP"), "{0:dd-MMM-yy}", DateTime.Now));
// 13-3-20
WriteLine(string.Format(CultureInfo.GetCultureInfo("ja-JP"), "{0:dd-MMMM-yy}", DateTime.Now));
//13-3月-20

WriteLine(string.Format(CultureInfo.GetCultureInfo("zh"), "{0:dd-MM-yy}", DateTime.Now));
//13-03-20
WriteLine(string.Format(CultureInfo.GetCultureInfo("zh"), "{0:dd-MMM-yy}", DateTime.Now));
//13-3月-20
WriteLine(string.Format(CultureInfo.GetCultureInfo("zh"), "{0:dd-MMMM-yy}", DateTime.Now));
//13-三月-20
```

As a non-Japanese working in Japan, I was bitten by that exception a few times. Especially, I noticed it late (once in QA testing) since my own machine use US locale, but Japanese users use their own locale.

I don't think the documentation should include an example for every single exceptions, but acknowledging that there are some would at least be informative.

One could possibly argue that "3" is the abbreviated version of "3月" but it is still surprising to find a digit here, especially since it might be ambiguous with other format such "dd-M-yy"
 or "MM-d-yy". At the very least, that would be more useful than the "fr-FR" example (and I'm French 😉 ).

**Target framework**

Any and all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
Thanks for the suggestion. We've added this to our backlog and will address it the next time we update the relevant article.
