### ISSUE TITLE
Finalizer is not reliably called regardless of .NET Core or .NET Framework

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/docs#17463]
According to the page:
> In .NET Framework applications (but not in .NET Core applications), finalizers are also called when the program exits.

However, given the following code, it appears the finalizer doesn't reliably get called before the program shuts down regardless of whether .NET Core (netcoreapp3.1) or .NET Framework (net46) is used.  Adding the Collect() triggers the finalizer in both cases.

```c#
    class Program
    {
        static void Main(string[]? args)
        {
            DoSomething();
            // System.GC.Collect();
        }

        static void DoSomething()
        {
            Thing thing = new Thing();
        }
    }

    class Thing
    {
        ~Thing()
        {
            Console.WriteLine("Executing finalizer...");
        }
    }
```

Admittedly, there is likely some "timing" explanation but seemingly it isn't working as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @MarkMichaelis 

Ping @richlander @karelz  Who would be best to help me correctly describe the behavior of finalizers across the .NET CLR implementations?

**Comment by karelz** [comment]
@Maoni0 will know probably best ...

**Comment by Maoni0** [comment]
there are various timeouts for running finalizers. on .net this was something like 40 seconds total for process shutdown and 2 seconds total for each finalizer. there's also a different timeout for AD shutdown. I'd have to check the src to verify. there's also the distinction between critical finalizers vs non critical finalizers. I can't remember if the timeouts apply to the critical finalizers or not. @jkotas do you remember off the top of your head? 

on .net core, based on a cursory look, no one is calling `FinalizerThreadWait` with an arg which means the timeout is infinite. so looks like no timeouts anymore.

**Comment by jkotas** [comment]
This is described in detail in https://docs.microsoft.com/en-us/dotnet/api/system.object.finalize?view=netframework-4.8#how-finalization-works

**Comment by jkotas** [comment]
And in even more detail here: https://devblogs.microsoft.com/cbrumme/finalization/

**Comment by BillWagner** [comment]
When we updated the C# standard for version 5, we softened the language specific to finalizers as follows:

> Prior to an application’s termination, an implementation should make every reasonable effort to call finalizers (§15.13) for all of its objects that have not yet been garbage collected, unless such cleanup has been suppressed (by a call to the library method GC.SuppressFinalize, for example). The implementation should document any conditions under which this behavior cannot be guaranteed.

For this article, that language should be adopted, with the additional details @Maoni0 added (because this article *is* about the Microsoft implementations).

I've added this to an upcoming sprint to fix.

**Comment by MarkMichaelis** [comment]
What I was hoping for was a clearer explanation for why the finalizer was not getting called and, more importantly, what I could do to ensure - under normal shutdown scenarios (e.g. not running under the debugger and stopping the execution) - the finalizer would get called.

**Comment by jkotas** [comment]
If you need to do cleanup during shutdown, the best way to do that is to register for `AppDomain.ProcessExit` event and do not depend on finalizers.

For any non-trivial real-world app, there is a significant chance that the shutdown finalization gets stuck due to deadlock or aborted due to timeout. For example, Visual Studio does not depend on the shutdown finalization at all (it actually terminates the process after the graceful shutdown cleanup is done but before shutdown finalizers start executing).

**Comment by MarkMichaelis** [comment]
Thanks.  That is helpful for the application developer.  I don't see that as working or a "library" vendor, however.  If the code calling my API knows cleanup is necessary, the just call Dispose() and all is fine.  The issue here is for when the users of your library forget to or don't realize the Dispose pattern.  Finalizers are for this scenario I thought.  Also, the code example I have above doesn't have anything exceptional about it.  It seems like the most basic of scenarios and yet finalizers are (seemingly?) not called.

**Comment by jkotas** [comment]
The finalizers are never called during shutdown in .NET Core. This is the expected for .NET Core.

For .NET Framework, your repro prints "Executing finalizer..." reliably for me. It is possible that the Console finalizer is running before your finalizer on your machine, and the console is non-functional by the time your finalizer is called. Ie your finalizer is called but you do not see it on the console.

**Comment by MSDN-WhiteKnight** [comment]
>Thanks. That is helpful for the application developer. I don't see that as working or a "library" vendor, however.

But the library could still subscribe to AppDomain.ProcessExit event on first API invocation, maintain the static collection of all disposable objects undisposed by user and dispose them in event handler. Why wouldn't that work for library vendor?

>For any non-trivial real-world app, there is a significant chance that the shutdown finalization gets stuck due to deadlock or aborted due to timeout.

Indeed, for OleDB classes, or any STA COM objects in general, shutdown finalizer deadlocks are common in .NET Framework.

**Comment by MarkMichaelis** [comment]
I confess it didn't occur to me that the library could also subscribe to the `AppDomain.ProcessExit` event and I hadn't seen that in guidelines for finalization type scenarios before.  I didn't see them outlined in the finalization docs either.  I'll go ahead and draft something and make a recommendation for the documentation for your review. Thanks for the insights!

**Comment by BillWagner** [comment]
@MarkMichaelis 

> I'll go ahead and draft something and make a recommendation for the documentation for your review.

Are you interested and have time to make the draft? If not, I'll start on this tomorrow, and ping you for review.

**Comment by MarkMichaelis** [comment]
@BillWagner 

Sorry... lame.  Distracted with some other writing activities that you are aware of. :)

I can take a look at this in a couple of weeks if that works? I understand if it is more critical and you want to do it sooner.  

Mark

**Comment by BillWagner** [comment]
@MarkMichaelis Thanks. I'm excited to see the results of your other writing. :)

This can wait a couple weeks. I'll work on the other items I have.

**Comment by MarkMichaelis** [comment]
@BillWagner and @jkotas 
Before I update the documentation, could you please review the sample `Program.cs` code below.  There are a couple of things to notice specifically:
- It is necessary to use a WeakReference when registering with ProcessExit or else the resource will always have a reference so never get GC'd until the process exits.
- Seemingly, invoking `GC.Collect(); GC.WaitForPendingFinalizers();` before exiting `Main()` will accomplish the same thing as registering for `AppDomain.ProcessExit` - at least in my simple test.  However, this isn't viable from a library project.
- If registering for `AppDomain.ProcessExit` it seems like one should unregister when `Dispose()` and/or the finalized runs.
- Question: Would it be preferable to have a real unmanaged resource rather than just WriteLines() simulation such?

Thoughts? 

Feedback welcome and appreciated.

```
using System;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using static ConsoleLogger;

public static class Program
{
    public static void Main(string[] args)
    {
        WriteLine("Starting...");
        StartProcess();
        if(args.Any(arg => arg.ToLower() == "-gc"))
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
        WriteLine("Exiting...");
    }

    // ...
    public static void StartProcess()
    {
        WriteLine("Starting...");
        SampleUnmanagedResource sampleUnmanagedResource =
            new SampleUnmanagedResource();

        // Use temporary file stream
        // ...

        if (Environment.GetCommandLineArgs().Any(arg => arg.ToLower() == "-dispose"))
        {
            sampleUnmanagedResource.Dispose();
        }

        // ...
        WriteLine("Exiting...");
    }
}

class SampleUnmanagedResource : IDisposable
{
    public SampleUnmanagedResource(string fileName)
    {
        WriteLine("Starting...", $"{nameof(SampleUnmanagedResource)}.ctor");

        WriteLine("Creating managed stuff...", $"{nameof(SampleUnmanagedResource)}.ctor");        
        WriteLine("Creating unmanaged stuff...", $"{nameof(SampleUnmanagedResource)}.ctor");

        var weakReferenceToSelf = new WeakReference<IDisposable>(this);
        ProcessExitHandler = (_, __) =>
        {
            WriteLine("Starting...", "ProcessExitHandler");
            if (weakReferenceToSelf.TryGetTarget(out IDisposable? self))
            {
                self.Dispose();
            }
            WriteLine("Exiting...", "ProcessExitHandler");
        };
        AppDomain.CurrentDomain.ProcessExit
            += ProcessExitHandler;
        WriteLine("Exiting...", $"{nameof(SampleUnmanagedResource)}.ctor");
    }

    // Stores the process exit delegate so that we can remove it
    // if Dispose() or Finalize() is called already.
    private EventHandler ProcessExitHandler { get; }

    public SampleUnmanagedResource()
        : this(Path.GetTempFileName()) { }

    ~SampleUnmanagedResource()
    {
        WriteLine("Starting...");
        Dispose(false);
        WriteLine("Exiting...");
    }

    #region IDisposable Members
    public void Dispose()
    {
        Dispose(true);
    }
    #endregion
    public void Dispose(bool disposing)
    {
        WriteLine("Starting...");

        // Do not dispose of an owned managed object (one with a 
        // finalizer) if called by member finalize,
        // as the owned managed objects finalize method 
        // will be (or has been) called by finalization queue 
        // processing already
        if (disposing)
        {
            WriteLine("Disposing managed stuff...");

            // Unregister from the finalization queue.
            System.GC.SuppressFinalize(this);
        }
            
        AppDomain.CurrentDomain.ProcessExit -= ProcessExitHandler;

        WriteLine("Disposing unmanaged stuff...");

        WriteLine("Exiting...");
    }
}

public static class ConsoleLogger
{
    public static void WriteLine(string? message = null, [CallerMemberName] string? name = null)
        => Console.WriteLine($"{$"{name}: " }{ message ?? ": Executing" }");
}
```

**Comment by jkotas** [comment]
> It is necessary to use a WeakReference when registering with ProcessExit

For performance reasons, libraries typically choose to subscribe to the ProcessExit just once and then manage list of what needs to be cleaned up. Here is an example from Microsoft.Data.SqlClient: https://github.com/dotnet/SqlClient/blob/7a2120d82919f5ed6173906110cca87103a23a20/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionPoolCounters.cs#L180

> invoking GC.Collect(); GC.WaitForPendingFinalizers(); before exiting Main() will accomplish the same thing

It won't accomplish the same thing. For example, if the object reference is stored in a static variable, the object won't be finalized by running `GC.Collect(); GC.WaitForPendingFinalizers();`.

> Can I assume that ProcessExit is the final and only thread such that no synchronization is required?

No. Other managed threads will be still running while ProcessExit executes. It needs synchronization.

**Comment by MarkMichaelis** [comment]
Thasnk @jkotas!  I appreciate the feedback.

Below is an updated code listing.  Note the following:
- I have a single `AppDomain.ProcessExit` subscriber for all `IDisposable` objects (that register), not one per object type.
- I use the keys in the `ConcurrentDictionary` but ignore the values.  Is there another concurrent collection I should consider that will give me fast retrieval of the object only?
- I agree wholeheartedly with your point that `GC.Collect();GC.WaitForPendingFinalizers()` would not work for static objects.  I wasn't considering that in my code sample.  I have removed that code.
- Even if there are no objects in the `DisposableObjectsForProcessExitManager` (for which a better name is needed), I don't unsubscribe from process.


```
    using System;
    using System.Collections.Concurrent;
    using System.IO;
    using System.Linq;
    using System.Runtime.CompilerServices;
    using static ConsoleLogger;

    public static class Program
    {
        public static void Main(string[] args)
        {
            WriteLine("Starting...");
            DoStuff();
            WriteLine("Exiting...");
        }

        public static void DoStuff()
        {
            // ...

            WriteLine("Starting...");

            SampleUnmanagedResource? sampleUnmanagedResource = null;
            try
            {
                sampleUnmanagedResource =
                    new SampleUnmanagedResource();

                // Use unmanaged resource.
                // ...
            }
            finally
            {
                if (Environment.GetCommandLineArgs().Any(
                    arg => arg.ToLower() == "-dispose"))
                {
                    sampleUnmanagedResource?.Dispose();
                }
            }

            WriteLine("Exiting...");

            // ...

        }
    }

    class SampleUnmanagedResource : IDisposable
    {
        public SampleUnmanagedResource(string fileName)
        {
            WriteLine("Starting...",
                $"{nameof(SampleUnmanagedResource)}.ctor");

            WriteLine("Creating managed stuff...",
                $"{nameof(SampleUnmanagedResource)}.ctor");
            WriteLine("Creating unmanaged stuff...",
                $"{nameof(SampleUnmanagedResource)}.ctor");

            WeakReferenceToSelf = 
                DisposableObjectsForProcessExitManager.Register(this);

            WriteLine("Exiting...",
                $"{nameof(SampleUnmanagedResource)}.ctor");
        }

        // Save the weak reference in order to unregister it
        // during Dispose().
        private WeakReference<IDisposable> WeakReferenceToSelf { get; }

        public SampleUnmanagedResource()
            : this(Path.GetTempFileName()) { }

        ~SampleUnmanagedResource()
        {
            WriteLine("Starting...");
            Dispose(false);
            WriteLine("Exiting...");
        }

        #region IDisposable Members
        public void Dispose()
        {
            Dispose(true);
        }
        #endregion
        public void Dispose(bool disposing)
        {
            WriteLine("Starting...");

            // Do not dispose of an owned managed object 
            // (one with a finalizer) if called by member finalize,
            // as the owned managed objects finalize method 
            // will be (or has been) called by finalization queue 
            // processing already
            if (disposing)
            {
                WriteLine("Disposing managed stuff...");

                // Unregister from the finalization queue.
                System.GC.SuppressFinalize(this);
            }

            WriteLine("Disposing unmanaged stuff...");

            DisposableObjectsForProcessExitManager.Unregister(WeakReferenceToSelf);

            WriteLine("Exiting...");
        }
    }

    public static class DisposableObjectsForProcessExitManager
    {
        static DisposableObjectsForProcessExitManager()
        {
            AppDomain.CurrentDomain.ProcessExit += ProcessExitHandler;
        }

        private static EventHandler ProcessExitHandler { get; } =
            (_, __) =>
            {
                WriteLine("Starting...", "ProcessExitHandler");
                foreach (WeakReference<IDisposable> item in Instances.Keys)
                {
                    if (item.TryGetTarget(
                            out IDisposable? self))
                    {
                        self.Dispose();
                    }
                }
                WriteLine("Exiting...", "ProcessExitHandler");
            };
        private static ConcurrentDictionary<WeakReference<IDisposable>, WeakReference<IDisposable>> Instances { get; } =
            new ConcurrentDictionary<WeakReference<IDisposable>, WeakReference<IDisposable>>();
        public static WeakReference<IDisposable> Register(IDisposable disposableInstance)
        {
            WriteLine();
            var weakReferenceToSelf =
                new WeakReference<IDisposable>(disposableInstance);
            Instances.TryAdd(weakReferenceToSelf, weakReferenceToSelf);
            return weakReferenceToSelf;
        }
        public static void Unregister(WeakReference<IDisposable> weakReference)
        {
            WriteLine();
            if (!Instances.TryRemove(weakReference, out WeakReference<IDisposable> _))
            {
                throw new ArgumentException("Item not registered", nameof(weakReference));
            }
        }
    }

    public static class ConsoleLogger
    {
        public static void WriteLine(
            string? message = null,
            [CallerMemberName] string? name = null)
            => Console.WriteLine(
                $"{name}: { message ?? "Executing..." }");
    }
```

**Comment by MarkMichaelis** [comment]
@BillWagner, @jkotas 

Do you have any further feedback on the code or the bullets above?  I will be basing the documentation on this so I want to be sure it is right before I begin writing. Thanks!

**Comment by BillWagner** [comment]
@MarkMichaelis 

I like what you've put together.

To your earlier question:  You could use the `ConcurrentBag` instead of the `ConcurrentDictionary`, if you wanted. I don't have strong feelings there.

Thanks for all the research and discussion putting this together.

**Comment by BillWagner** [comment]
@MarkMichaelis Are you going to have time to work on this? If not, I'll unassign and more into our backlog.

**Comment by MarkMichaelis** [comment]
@BillWagner Sure... This month.

**Comment by MarkMichaelis** [comment]
Sorry @BillWagner... I'm travelling for the remainder of the month and can't get this done before I leave.  I have scheduled the time in for next month so that it won't happen again. :(

**Comment by MarkMichaelis** [comment]
@BillWagner - I am actively working on this but I need to check with you on how you want it addressed.

Update text below to indicate that is it not reliably called (since it is true both with .NET Framework and .NET Core there is no point in mentioning either).  
Original Text:
> In .NET Framework applications (but not in .NET Core applications), finalizers are also called when the program exits.
Becomes:
> Finalizers are not reliably called when the program exits. To achieve this, you need to register the cleanup in a subscription to `AppDomain.CurrentDomain.ProcessExit`.

Given the complete finalization example I mentioned earlier in the thread, should I include the example on this page or should it appear elsewhere?

**Comment by MSDN-WhiteKnight** [comment]
>since it is true both with .NET Framework and .NET Core there is no point in mentioning either.

I think there's a point, per above:

> For any non-trivial real-world app, there is a significant chance that the shutdown finalization gets stuck due to deadlock or aborted due to timeout.
>Indeed, for OleDB classes, or any STA COM objects in general, shutdown finalizer deadlocks are common in .NET Framework.

People would need to know why these deadlocks are happening. Docs should tell that .NET Framework attempts to call finalizers on shutdown, but timeouts if they take too long (except for CriticalFinalizerObject's which don't timeout); and on .NET Core / .NET 5 it does not attempt it. But the exact details should probably be checked with CLR devs. Bad thing that all important info about finalizers seems to be on blogs which are gone now.

**Comment by IEvangelist** [comment]
Hi friends, just circling around on this open issue - is this something that you'll be able to get to @MarkMichaelis? If not, and you have code with a general description - I'd be happy to make it happen, just let me know.

**Comment by BillWagner** [comment]
See dotnet/csharpstandard#309 for the updated text in the C# standard (draft for version 6)
