### ISSUE TITLE
Additional Resources links broken

### ISSUE THREAD

**Issue by oneor11** [dotnet/docs#17462]
Links in Additional Resources return 404s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245ea389-75e9-1321-3be4-dc8d8e47a925
* Version Independent ID: 1db547e8-a0b0-cf44-dba4-b65786c576fe
* Content: [Testing ASP.NET Core services and web apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps#additional-resources-1)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Thanks @oneor11 
We've fixed this as part of PR https://github.com/dotnet/docs/pull/19901 Closing this issue.
