### ISSUE TITLE
Where is the matching code?

### ISSUE THREAD

**Issue by bdnts** [dotnet/docs#17465]
WHERE IS THE MATCHING CODE?!!!  Has everyone been fired from the MS Documentation department?  Because there are absolutely no standards left, and Docs are all over the place.  No consistency.  This article is a wonderful explanation of typed clients, but then trying to implement the guidance, the examples are just snippets, creating more questions than they clarify.  I go looking for the accompanying code on Github, and the referenced code is the source for the implementation of the factory!  Useless!  I'm mad because this is a good article about best practices, and victory has been thrown into the jaws of defeat because this wasn't finished off with the matching code.  Anyone reading this will forego implementation, just as I'm about to, because the additional research will consume hours of googling and reading dozens of pages to put this jigsaw of an explanation into practical use.  The #1 and inviolate rule of writing is "Never forget your audience."  This article is being written to an audience who doesn't know or understand the benefits of IHttpClientFactory, else there would be no reason to write it.  But it wasn't finished off with clear next steps so the audience implements these best practices.  Consequently, this fails to deliver on its intentions.  Disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#additional-resources)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @bdnts, thank you for your feedback. 

All the reference examples mentioned in *.NET microservices - Architecture guide* are part of one single application, which is [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers)

Here is the [CatalogController](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Controllers/CatalogController.cs) class which shows the usage of `Typed Client`

Hope this helps !

**Comment by sughosneo** [comment]
Hi @bdnts, I am closing this issue as of now. 
If you have further questions, please feel free to reopen it. 

Thank you.
