### ISSUE TITLE
To Learn .Net Core Do We Have To Learn C#, F# and Visual Basic, Or Just One Of The Languages?

### ISSUE THREAD

**Issue by GabriellaLaPlace** [dotnet/docs#17467]
To Learn .Net Core Do We Have To Learn C#, F# and Visual Basic, Or Just One Of The Languages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582
* Version Independent ID: aeb94c3f-50e0-eb84-e469-f6eb778bad62
* Content: [Debug your Hello World .NET Core application with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio?tabs=csharp#feedback)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/debugging-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by svick** [comment]
Learning just one of the languages is enough to use .Net. Though most of the documentation, examples, articles and Q&A answers are in C#, so your choices are more like:

1. Learn just C#.
2. Learn F# or VB and also basics of C#, so that you can understand the code that's out there and translate it into the language you're using.

**Comment by GabriellaLaPlace** [comment]
Thanks, I'm doing the tutorials on Microsoft's website. Do you know any
other websites that teach .Net Core. I'm learning C# on Sololearn.com, but
I don't know where I can specifically learn .Net Core. , Step - By - Step.

**Comment by tdykstra** [comment]
> learn .Net Core. , Step - By - Step

See the list of tutorials here:  https://docs.microsoft.com/en-us/dotnet/core/tutorials/
