### ISSUE TITLE
is the is an is with no null or an as with null

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#17469]
The first sample includes:

static void TestForMammals(object o)
    {
        // Alternatively, use the as operator and test for null
        // before referencing the variable.
        if (o is Mammal m)
        {
            Console.WriteLine(m.ToString());
        }
        else
        {
            // variable 'm' is not in scope here, and can't be used.
            Console.WriteLine($"{o.GetType().Name} is not a Mammal");
        }
    }

I see no as operator, only an is. And I do not see a test for null. I am very confused by that. Perhaps the code is doing exactly as intended and the comment is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1766cac-6e34-c70b-0933-9d9def2344c4
* Version Independent ID: 38869398-bce4-0321-112d-4b44d558d7b1
* Content: [How to safely cast by using pattern matching and the is and as operators](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators?source=docs)
* Content Source: [docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
> I see no as operator, only an is. And I do not see a test for null. I am very confused by that. Perhaps the code is doing exactly as intended and the comment is wrong.

@SimpleSamples I see that the comment can be confusing and interpreted in several ways. I think the intended interpretation of the comment as follows.

The comment
```
// Alternatively, use the as operator and test for null
// before referencing the variable.
```

should read as
```
// Alternatively to the following code that uses the is operator, 
// you can use the as operator and test for null
// before referencing the variable.
```

If you wonder how to use the `as` operator:
```csharp
m = o as Mammal;
if (m != null)
{

}
```

**Comment by BillWagner** [comment]
Thanks for noting this @SimpleSamples and for the explanation @pkulikov 

It looks like the code was updated without context. From the surrounding text, the second sample should be modified to use the `as` operator (which is shown at the end of the previous comment).

**Comment by SimpleSamples** [comment]
All that sounds good to me.
