### ISSUE TITLE
Suggestion on the capitalisation of true and false

### ISSUE THREAD

**Issue by s-williams** [dotnet/docs#17479]
On the [Hello world tutorial, part 5, Search strings](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=5), it is stated that:

> a boolean stores either a `true` or a `false` value

However, when you run the code sample, which involves writing two bools to the console, the output is:

> True
> False

Note the differing capitalisation of true and false in the console output and in the documentation. This discrepancy threw me for a split second and I thought for a moment the code sample had done something to change the capitalisation of the console output.

My suggested change is to amend the documentation so that it reads, with corrected capitalisation:

> a boolean stores either a `True` or a `False` value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
> A Boolean variable might store the `True` value.

That would imply that the following code is correct:

```csharp
bool test = True;
```

While it's not

**Comment by BillWagner** [comment]
Thanks for writing this @s-williams 

Because this content is for beginners, a clarifying comment could be added. I suggest:

> A boolean stores either a `true` or `false` value. When displayed as text output, they are capitalized: `True` and `False`, respectively.

I've added this to our backlog, and added the *up-for-grabs* label.

**Comment by cloudn9** [comment]
@BillWagner Hello Bill, could I merge the PR, or should I await for an approval ?
Thank you.

**Comment by BillWagner** [comment]
This was fixed in #17483
