### ISSUE TITLE
When I Build The Program, when release is selected, it tells me I'm still debugging and I don't know why?

### ISSUE THREAD

**Issue by GabriellaLaPlace** [dotnet/docs#17478]
When I Build The Program, when release is selected, it tells me I'm still debugging and I don't know why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582
* Version Independent ID: aeb94c3f-50e0-eb84-e469-f6eb778bad62
* Content: [Debug your Hello World .NET Core application with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/debugging-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment]
@GabriellaLaPlace thanks for asking.

In Visual Studio, the "run" button defaults to running the debugger. You can learn more, and try some of the Visual Studio tutorials for .NET core at the [Visual Studio](https://docs.microsoft.com/visualstudio/windows/?view=vs-2019) documentation.

I'll close this as answered. If you have more concerns, you can reopen this and add them here.
