### ISSUE TITLE
StaticAssets not included when pack the project using a .nuspec file

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/docs#17495]
Hello guys,

Thanks in advance..

i have faced the issue in nuget pack generation by dotnet pack using .nuspec file.

I have scripts and styles in my project's wwwroot folder and nupec file for my project. These folder is shipped into the package as staticassets when i am run the command **`"dotnet pack ~/projects/app1/project.csproj"`**.

But my project's nuspec file not shipped in to pack. The packed content have default dotnet nuspec file.

So i have pack my project using .nuspec file by **`"dotnet pack ~/projects/app1/project.csproj -p:NuspecFile=~/projects/app1/project.nuspec -p:NuspecBasePath=~/projects/app1/nuget"`**. 

It allows to shipped my local nuspec file but my wwwroot files are not shipped in to the package.

Actual issues:

1 . Local .nuspec not shipped in to package when we run **`"dotnet pack ~/projects/app1/project.csproj"`**. But wwwroot folder shipped as static assets.

2. Static assets folder is not shipped in to package when we run **`"dotnet pack ~/projects/app1/project.csproj -p:NuspecFile=~/projects/app1/project.nuspec -p:NuspecBasePath=~/projects/app1/nuget"`**. But local nuspec shipped.

is this issue?

Can any one please help me on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@karann-msft @rohit21agrawal can you help with this request?

**Comment by kmuthukumar23** [comment]
Hi Guys,

Any suggestions? I am waiting on this. :(

**Comment by karann-msft** [comment]
@kmuthukumar23 - this is not a docs issue and sounds like product feedback. Please file an issue on the nuget/home repo - https://github.com/nuget/home/issues
