### ISSUE TITLE
Confusing sentence at at start

### ISSUE THREAD

**Issue by m-brooks** [dotnet/docs#17494]
"An interface may provide a default implementation for any or all of its declared instance members."
This confuses me because the article goes on to say:
"An interface can't contain instance fields, instance constructors, or finalizers". 
I.e. the first quoted sentence says we can declare instance members, but the second says we can't, or at least we can't for certain types of member. I suppose that leaves instance methods as permissible, but the article also stated that the interface could define a static method (implying that it can't define an instance method's implementation).
Should the first sentence perhaps say "An interface may provide a default implementation for any or all of its declared STATIC members"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The first sentence should be replaced with:

> Beginning with C# 8.0, an interface may define a default implementation for members. 

The later sentence correctly specifies which members can be implemented in an interface.

I've added this to the current sprint, and added the "up for grabs" label in case community members want to implement the fix.

**Comment by m-brooks** [comment]
Thanks Bill- that helps. 🙂

________________________________
