### ISSUE TITLE
Excellent Topic Coverage

### ISSUE THREAD

**Issue by JohnP-Identiv** [dotnet/docs#17499]
This entry is concise, well laid out, and very clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@JohnP-Identiv Thank you for this positive feedback!

**Comment by Aspire0ne** [comment]
public:   no restriction | any assembly
internal: no restriction | current assembly
protected internal: no restriction | current assembly OR derived class in another assembly
private:  current class | current assembly
private protected: current & derived class | current assembly
protected: current & derived class | any assembly
