### ISSUE TITLE
Remove '-q' from wget in linux package repo setup for better initial diagnosis of mirror issues

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#17504]
I suggest removing `-q` from `wget -q https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb` on all applicable pages to get more information upon initial user reports.

Recently there have been issues (and apparent issues) with the packages.microsoft.com distributed mirrors getting out of sync from the repo state. The repo admins are currently unable to diagnose these without knowing the IP of the mirror that was hit, so we have to ask people to run some command that gives us the IP the domain resolves to. If we let `wget` run without quiet mode, it contains the IP, and there's a chance users reporting issues will include it so we can skip this round trip.

/cc @NikolaMilosavljevic @leecow @nakarnam 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by leecow** [comment]
Sounds like a good change.

**Comment by Thraka** [comment]
OK. I have an open PR already on changing some things, I'll add this to the list of stuff
