### ISSUE TITLE
Avoid Wait() on asynchronous operations

### ISSUE THREAD

**Issue by fekberg** [dotnet/docs#17507]
Please change `ExecuteAsyncMethods().Wait();` to `await ExecuteAsyncMethods()` to follow the best practices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards#feedback)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@fekberg Hello.

I'm assuming you're also suggesting that the entry point be changed to an asynchronous entry point too? Without that change, the current code is actually acceptable and works as intended.

**Comment by fekberg** [comment]
@Thraka That is correct.

It would end up like this instead:

```
static async Task Main(string[] args)
{
    await ExecuteAsyncMethods();
}

private static async Task ExecuteAsyncMethods()
{
    Console.WriteLine("About to launch a task...");
    _ = Task.Run(() => {
        var iterations = 0;
        for (int ctr = 0; ctr < int.MaxValue; ctr++)
            iterations++;
        Console.WriteLine("Completed looping operation...");
        throw new InvalidOperationException();
    });
    await Task.Delay(5000);
    Console.WriteLine("Exiting after 5 second delay");
}
```

I mainly suggest it as using `Wait()` or `Result` is often the cause of deadlocks, and it's bad practice.

Is there a reason not to make `Main` asynchronous and leverage `async` and `await` all the way?

**Comment by Thraka** [comment]
I don't think there is a reason. It was either an oversight, created before `async main` was available, or just the fact that the `dotnet new` template doesn't create one.

Please feel free to open up a PR.

Cheers!

**Comment by fekberg** [comment]
@Thraka Done! :) Thanks for the help
