### ISSUE TITLE
Explanation in the following link is much better than this page.

### ISSUE THREAD

**Issue by storm999** [dotnet/docs#17518]
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-client-socket-example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87c349f-3592-3f62-315d-e85db695041b
* Version Independent ID: efce9f39-4ba4-a61d-4330-e60dcfaf99ca
* Content: [Using an Asynchronous Client Socket](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-an-asynchronous-client-socket?view=netframework-4.8#feedback)
* Content Source: [docs/framework/network-programming/using-an-asynchronous-client-socket.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-an-asynchronous-client-socket.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@storm999 why is it better - it is just code. This page has text.
Are any of the samples incorrect?
Or is it just personal preference to see full code vs. reading text?

**Comment by storm999** [comment]
full code is easier to understand for me. also easier for copy pasting. 
In your page, i didnt understand what "connectDone" is even if you explained it verbally.

**Comment by karelz** [comment]
@storm999 different people prefer different things - some prefer text explanations over longer code. The full code sample is linked, so all should be good IMO.
