### ISSUE TITLE
xunit dotnet core page should point to dotnet docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#1752]
This is the "home page" for xUnit for .NET Core. It should point to docs. 

https://xunit.github.io/docs/getting-started-dotnet-core.html

Linked from: https://github.com/xunit/xunit/blob/master/README.md

We should ensure that we have a page that Brad and co would be happy linking to and then ask them to do that from the page linked above.

/cc @bleroy

**Comment by lucasnobredev** [comment]
@mairaw can I help?

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.
