### ISSUE TITLE
Worker runtime

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/docs#17529]
This doc seems to imply there are more available runtimes than the 3 listed: https://docs.microsoft.com/azure/azure-functions/functions-versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae537e7-1e78-ce81-3107-19c07c04913e
* Version Independent ID: a6e0f4d9-a02d-c3da-6fb9-927edd6b2891
* Content: [Combining containers and serverless approaches](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/combine-containers-serverless-approaches)
* Content Source: [docs/architecture/cloud-native/combine-containers-serverless-approaches.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/combine-containers-serverless-approaches.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Since the book focuses on `dotnet` specifically, I am asking @robvet to modify the text this way: https://gist.github.com/nishanil/27687b0a6255d46c87c66c528c0e0f23 
The linked tutorial walks through other languages. Hope that helps.
