### ISSUE TITLE
Replace placeholder with actual spec

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/docs#17539]
I can't find this feature documented elsewhere.  Please fill in this placeholder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec6109e-cc53-d680-ff97-79f6c1330691
* Version Independent ID: 01fb2712-1de7-b9da-f62a-fd2513bbe3b4
* Content: [Unconstrained type parameter in null coalescing operator - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/unconstrained-null-coalescing)
* Content Source: [proposals/csharp-8.0/unconstrained-null-coalescing.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/unconstrained-null-coalescing.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We agree @ChainReactive 

We'll be updating these shortly.

**Comment by pkulikov** [comment]
@ChainReactive @BillWagner I believe this feature is already documented, but not in this placeholder.

For example, in the [feature proposal for `??=`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/null-coalescing-assignment):

> As part of this proposal, we will also loosen the type requirements on ?? to allow an expression whose type is an unconstrained type parameter to be used on the left-hand side.

AND

> For the relaxation of the type requirements of `??`, we update the spec where it currently states that, given `a ?? b`, where `A` is the type of `a`:
>
> > If `A` exists and is not a nullable type or a reference type, a compile-time error occurs.
>
>We relax this requirement to:
>
> > If `A` exists and is a non-nullable value type, a compile-time error occurs.
>
> This allows the null coalescing operator to work on unconstrained type parameters, as the unconstrained type parameter `T` exists, is not a nullable type, and is not a reference type.

That change is also reflected in the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator):

>  In particular, beginning with C# 8.0, you can use the null-coalescing operators with unconstrained type parameters:

@BillWagner is that the correct feature?

**Comment by BillWagner** [comment]
As noted above, this feature is covered in two other spec areas.

Closing as addressed.
