### ISSUE TITLE
Title: gRPC instead of REST?

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/docs#17532]
The title says REST and gRPC but REST is only mentioned in the intro and the rest (pardon the pun) is gRPC. I think the title could better reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc86015f-c6c7-5fdc-ae0f-c69353afcb34
* Version Independent ID: 491d7006-ae8d-fb74-8b29-7e4b5031fcae
* Content: [REST and gRPC](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/rest-grpc)
* Content Source: [docs/architecture/cloud-native/rest-grpc.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/rest-grpc.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by robvet** [comment]
Hey Jeremy.

Excellent feedback. We are making the change.

Would love any feedback from you.

Rob Vettor  | Principal Cloud-Native Application Architect
                      | ASD IP Architect
                      | CNCF (Cloud-Native Computing Foundation) Speaker Bureau<https://www.cncf.io/speaker/robvet/>
                      | Developer Advisory Services for Azure

[cid:image001.jpg@01D5FEE3.6C6F9160]

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image004.jpg@01D5FEE3.6C6F9160]  www.thinkingincloudnative.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.thinkingincloudnative.com%2F&data=02%7C01%7Crobvet%40microsoft.com%7Ca0ad6989676c41a1c02208d7659ff0d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637089609919099893&sdata=Ih3VA8PbdEeYpmeYsH5jWzaoZX6Ys5Rwtpw3UlpdIVA%3D&reserved=0>

Co-Author of…
[cid:image005.png@01D5FEE3.6C6F9160]<https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/>
