### ISSUE TITLE
Book conclusion?

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/docs#17535]
It feels like we end abruptly with no wrap-up or summarization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa81c9f2-63af-3f51-9585-86fbdd9dfe32
* Version Independent ID: 81a92552-aebf-3704-315d-aa00d6894308
* Content: [Cloud Native Application Bundles](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/application-bundles)
* Content Source: [docs/architecture/cloud-native/application-bundles.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/application-bundles.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Thanks, Jeremy. Summary added as part of https://github.com/dotnet/docs/pull/17971 
Closing this.
