### ISSUE TITLE
Use IDisposable prefix for methods that implement this interface?

### ISSUE THREAD

**Issue by LambertWM** [dotnet/docs#17543]
Wouldn't it be clearer (from an educational perspective, as well as from a readability perspective) if the IDisposable prefix was used for the Dispose( ) method, as in:

   // Public implementation of Dispose pattern callable by consumers.
   public void IDisposable.Dispose()
   { 
      Dispose(true);
      GC.SuppressFinalize(this);           
   }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LambertWM** [comment]
minus the "public" :)

// implementation of Dispose pattern callable by consumers.
void IDisposable.Dispose()
{
    Dispose(true);
    GC.SuppressFinalize(this);
}

**Comment by gewarren** [comment]
@LambertWM By adding the interface prefix to the method, you'd create an [explicit interface implementation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) (EII), and the Dispose() method would no longer be callable on members of the class. EII's can only be called by interface references. Adding @BillWagner who can correct me if I'm wrong.

**Comment by LambertWM** [comment]
Thanks, I happened to learn this after posting my feedback, but couldn't find a way to "undo" the post ;)
