### ISSUE TITLE
Update REST client tutorial?

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#17545]
@BillWagner `System.Text.Json.JsonSerializer` is able to parse the timestamp string into a `DateTime` value, so no additional action is required.

https://github.com/dotnet/docs/blob/a87a04817a847efe4c64621529a60e1a8478a222/docs/csharp/tutorials/console-webapiclient.md#L358

**Comment by BillWagner** [comment]
That is a great suggestion @NextTurn Do you want to make this change? (If so, I'll assign it to you). If not, I'll address it shortly.

**Comment by NextTurn** [comment]
@BillWagner OK I'll take it.

**Comment by NextTurn** [comment]
@BillWagner I took a look at the [response](https://developer.github.com/v3/repos/#response) format and didn't find any field that can't be directly parsed. Do we just end up with removing the whole two paragraphs?

**Comment by BillWagner** [comment]
> Do we just end up with removing the whole two paragraphs?

@NextTurn Yes, I like that plan. We should updated the code to match the updated application.
