### ISSUE TITLE
Update .NET Native docs

### ISSUE THREAD

**Issue by ChainReactive** [dotnet/docs#17548]
Whereas .NET Native itself is actively developed, these docs don't appear to be following suit.  They use old product names like Windows 8 and Windows Store apps.  I can replace those terms in my mind with Windows 10 and UWP apps, but I'm unsure how much I can trust the doc contents.

Currently, how reliable are these docs given their age?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06fd94b-aaba-d65f-1fc7-7131d6ff892f
* Version Independent ID: 3de244c3-d43b-be7a-bad3-b5e04a1c2fd8
* Content: [Compiling Apps with .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/)
* Content Source: [docs/framework/net-native/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/index.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
@ChainReactive I think this is highly related to #6068 which has a query out to the UWP folks to see if we should move these articles over there.

I'll close this issue. Thanks for filing it!

**Comment by gewarren** [comment]
We are meeting in late April to discuss next steps for the .NET Native docs.
