### ISSUE TITLE
Multiple output regression

### ISSUE THREAD

**Issue by hoksource** [dotnet/docs#17546]
Do you guys have a multiple output regression? Lets say input is (x^0,...,x^n) output is (y^0,...,y^m), where the training table consists of (x^0,...,x^n,y^0,...,y^m, someother stuffs)

Or do you guys have matrix utilities like svd svm mat inverse etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008a45d2-e86b-1ea9-ef79-10f79f6cba40
* Version Independent ID: 94c0d9c3-3c9e-8b9c-2288-6215f9f8c122
* Content: [Tutorial: Predict prices using regression with Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder)
* Content Source: [docs/machine-learning/tutorials/predict-prices-with-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/predict-prices-with-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @hoksource 

Thank you for your question. ML.NET currently does not support this scenario. What you can do is something like the following sample. 

https://github.com/zeahmed/DeepLearningWithMLdotNet/tree/master/NYCTaxiMultiOutputRegression

If you have a TensorFlow / ONNX model that performs this task, you can use that model inside ML.NET. Keep in mind, this sample was created before version 1.0 of the API, so a few things may not work when you use the current version of ML.NET. However, the concepts should still apply.

I would encourage raising an issue on the [dotnet/machinelearning repository](https://github.com/dotnet/machinelearning) requesting this feature.

**Comment by hoksource** [comment]
Thank you for the response. Looking forward for this feature within the year or 2.
