### ISSUE TITLE
"Related Links" to modules corresponding to collection types are broken

### ISSUE THREAD

**Issue by aggieben** [dotnet/docs#17557]
The F♯ core library reference is gone.  I opened an issue here: https://github.com/MicrosoftDocs/feedback/issues/2536

However, that also affects this page because links to the reference documentation are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0694330-a4e4-5a07-2b6b-8259b57e319a
* Version Independent ID: 71e9da59-27a1-6194-3a69-09b9d3a383d4
* Content: [Collection Types - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types#feedback)
* Content Source: [docs/fsharp/language-reference/fsharp-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/fsharp-collection-types.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by jhigdon** [comment]
any luck fixing this?

**Comment by cartermp** [comment]
this is fixed in https://github.com/dotnet/docs/pull/20055
