### ISSUE TITLE
Suggestion: Change 'Register Microsoft key and feed'

### ISSUE THREAD

**Issue by sedlund** [dotnet/docs#17553]
The use of the word Register is misleading and offputting.

---
### Register Microsoft key and feed
Before installing .NET, you'll need to:

* Register the Microsoft key.
* Register the product repository.
* Install required dependencies.
---

The use of the word Register is misleading and offputting.

Upon first glance of the document I thought I was going to be required to register a software product with a long process like login to a Microsoft account and request a product key.  I initially closed the page thinking this would be a tedious involved process to access the dotnet package.
After navigating away and then coming back I realized the process is typical for adding a 3rd party software repository.

I suggest changing the verbiage to something along the lines of :

---
### Add Microsoft repository key and feed
Before installing .NET, you'll need to:

* Add the Microsoft package signing key to the list of trusted keys.
* Add the repository to the package manager.
* Install required dependencies.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello! That's a great suggestion! I'll flag @dagood for some feedback on that suggestion

**Comment by dagood** [comment]
Yeah "register" raised an eyebrow for me as well early on. Technically you're registering the feed with the apt package management system, but doesn't leave a perfect first impression. "Add" plus the extra info about what's actually being done sounds good to me.

/cc @leecow @nakarnam @NikolaMilosavljevic @dleeapho

**Comment by leecow** [comment]
LGTM
