### ISSUE TITLE
link to "specification of the compatibility pack" is dead.

### ISSUE THREAD

**Issue by rjvdboon** [dotnet/docs#17554]
In the Package Contents section, in the sentence "For more information, see the specification of the compatibility pack." the link is dead. I get a 404 from github.
The correct link is https://github.com/dotnet/designs/blob/master/accepted/2018/compat-pack/compat-pack.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf48b3f-5550-679d-4462-aeca2961b56e
* Version Independent ID: 18e36ec0-029d-804c-f500-aa9248af865a
* Content: [Use the Windows Compatibility Pack to port code to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack#feedback)
* Content Source: [docs/core/porting/windows-compat-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/windows-compat-pack.md)
* Product: **dotnet-core**
* GitHub Login: @terrajobst
* Microsoft Alias: **phcart**

**Comment by tdykstra** [comment]
@rjvdboon Thanks for reporting that!
