### ISSUE TITLE
Sample is a dead link

### ISSUE THREAD

**Issue by danzel** [dotnet/docs#17570]
https://github.com/dotnet/samples/blob/master/snippets/standard/data/sqlite/InMemorySample/Program.cs

Looks like it did exist at one stage
https://github.com/dotnet/samples/commit/939a22570827f8c9fcf24acab28ccf75442e55f0#diff-93d46eb2e4a2862ff79e0e31074f8a9b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c8d1aa-2bc2-f031-212b-627f2f1549e7
* Version Independent ID: bbf0aafd-8231-73ae-c8a8-a6e10c917641
* Content: [In-memory databases - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/in-memory-databases#feedback)
* Content Source: [docs/standard/data/sqlite/in-memory-databases.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/sqlite/in-memory-databases.md)
* Product: **dotnet**
* Technology: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by Thraka** [comment]
The new link is `https://github.com/dotnet/docs/blob/master/samples/snippets/standard/data/sqlite/InMemorySample/Program.cs`

Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
