### ISSUE TITLE
Should remove or improve on the notion of this being a bot example and improve Test the application section

### ISSUE THREAD

**Issue by brcaswell** [dotnet/docs#17576]
This program echos arguments with console write.  At best, it's an example of Logging but is more like an example of ConsoleWrite.  

also, why is there an unnecessary reference to an argument\command `botsay &lt;message&gt;` for usage?

Additionally, you should include\state the expectation of running those three Tests, and they should be three separate code snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [Tutorial: Create a .NET Core tool - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thank you for the suggestions. The purpose of this tutorial is to show how to create and use a tool. Writing to the console is done here as a simple hello-world-type example to keep the program code simple so the tutorial can focus on what needs to be done for a tool.

The command with argument is an example showing the syntax to invoke the tool.

We don't typically split up consecutive CLI commands into separate code blocks. These in particular are so simple that I think it's better to keep them as one code block.

**Comment by tdykstra** [comment]
Closing, as comments have been addressed. If you would like to continue the discussion, feel free to reopen.
