### ISSUE TITLE
No VB Examples on page 

### ISSUE THREAD

**Issue by tigerg2002** [dotnet/docs#17581]
Following the tutorial and on page "Test a .NET Standard library with .NET Core in Visual Studio". The page says that this can be done in C# or VB. I don't see a selection for VB code. The examples are all C#. I'm interested in VB so I guess the translation from C# to VB code is left up to the student. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET Standard class library with .NET Core in Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio#feedback)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
There's a language selector at the top of the page. Look to the right of the breadcrumbs and click the **^** symbol to the right of **C#** to switch to VB.
