### ISSUE TITLE
Missing Documentation for PublishSingleFile property

### ISSUE THREAD

**Issue by JeremyCaney** [dotnet/docs#17583]
The [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0) document includes a section, "[Single-file executables](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables)", which provides basic instructions on using the `PublishSingleFile` property, either as part of the `dotnet publish` command (using `-p:PublishSingleFile=true`), or as a property in a project file (e.g., a `<PublishSingleFile>true</PublishSingleFile>` element in a `csproj` file). 

The release notes then link to a single-file bundler design document at [the following GitHub URL](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md): 
```
/dotnet/designs/blob/master/accepted/single-file/design.md
```
This URL is out-of-date, however, and returns a 404 Not Found error. Instead, this should link to [the new GitHub URL](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md):
```
/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md
```

This issue is compounded by the fact that this new location doesn't _appear_ to be picked up by Google, nor was I able to find any other official documentation on the property. For example, [Googling "PublishSingleFile" on docs.microsoft.com](https://www.google.com/search?q=%22PublishSingleFile%22+site%3Adocs.microsoft.com) only returns the above release notes for .NET Core 3.0, as well as an update for Visual Studio 2019 16.5.

There are a lot of nuances and considerations to using the `PublishSingleFile` property, so it's important that developers are able to easily find reliable, first-party documentation. At minimum, the release notes for .NET Core 3.0 need to be updated to reference the correct link. Ideally, Microsoft should ensure that the new location is properly indexed in Google or cross-referenced in the official .NET Core 3.0 documentation so it can be easily discovered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by JeremyCaney** [comment]
@Thraka: Oh, I really should have just started with that, and especially for such a small request! I've proposed that change. I'll be sure to just submit pull requests for small changes like this in the future, instead of cluttering up your issues.
