### ISSUE TITLE
Request to add detail on the maximum limit of CASEs and efficiency.

### ISSUE THREAD

**Issue by jagerschmidt** [dotnet/docs#17595]
I could not find this information.  What is the maximum limit to the number of CASEs that can be inside a single SWITCH block?  And what are the perfomance implications, if the maximum is large?  i.e.: dozens of Cases versus hundreds of cases? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d9cc47-5caf-184a-0ad6-cb968850be7a
* Version Independent ID: f058bf17-04e9-9e23-05c7-66c1864445ad
* Content: [C# switch statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#feedback)
* Content Source: [docs/csharp/language-reference/keywords/switch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/switch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jagerschmidt The official specification does not declare a limit. There are logical limits based on the type used: If the expression is a `byte`, there are only 256 possible values. 

My opinion is that you'll reach the limit of readability before you observe any performance issues. 

/cc @jcouv @stephentoub  to check on any performance considerations.
