### ISSUE TITLE
How to use a Current User installation of the SDK instead of the Local Machine installation?

### ISSUE THREAD

**Issue by axhussain** [dotnet/docs#17593]
I have a non-admin account on a PC which has the .NET Core 2.1 SDK previously installed. I have installed .NET Core 3.1 SDK using the Powershell install script into my user profile's AppData folder.

But when I try to debug an application in VS Code, it tries to use the 2.1 SDK, instead of my local 3.1 SDK.

I have a global.json file in the project folder and have set the Path and DOTNET_ROOT env variable from VS Code's integrated terminal but that has not worked.

Are there any other variables that I need to set? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET Core version to use - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#feedback)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/selection.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@axhussain Sorry you're running into this problem. I think setting `DOTNET_ROOT` into the integrated terminal just sets that for any process you start within the terminal, not VSCode itself. However, the docs for [`DOTNET_ROOT`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables) specifies that it only applies to running .NET Core apps, so it may not apply to the SDK.

Have you tried adding the `dotnet\` directory you installed to the `appdata` folder to the `PATH` variable?

**Comment by axhussain** [comment]
@Thraka thanks for replying. Yes, I have set the path as well. Interestingly enough, if I run cli commands from the integrated terminal it does use 3.1.

**Comment by Thraka** [comment]
1. What does your global.json contain? 
2. What does your csproj contain?

**Comment by axhussain** [comment]
global.json:
{
  "sdk": {
    "version": "3.1.102", 
    "rollForward": "latestPatch"
  }
}

csproj (just a simple Console App):
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>

**Comment by axhussain** [comment]
I have noticed that instead of just adding `%LocalAppData%\Microsoft\dotnet` to the end of the Path, if I completely rewite it removing `C:\Program Files\dotnet` from the Path then VS Code stops complaining about unresolved references and the red underlines disappear. But I am still unable to debug. :(

**Comment by axhussain** [comment]
On further examination it appears the problem is with the VSCode's OmniSharp extension, and not .NET Core, so I am closing this issue.

**Comment by Thraka** [comment]
I was thinking that it may be the plugin. Perhaps it wasn't doing further searches for the appropriate SDK. Odd. Hope you get it fixed soon! Cheers.
