### ISSUE TITLE
GetAwaiter is not enough for generalized async return types

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#17592]
> Starting with C# 7.0, any type that has an accessible `GetAwaiter` method. The object returned by the `GetAwaiter` method must implement the [System.Runtime.CompilerServices.ICriticalNotifyCompletion](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.icriticalnotifycompletion) interface.

The listed requirements may suffice for an `await` expression, but they are not enough for defining an `async` function; the compiler will report error CS1983 unless the type also has an [AsyncMethodBuilderAttribute](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.asyncmethodbuilderattribute) attribute.

```C#
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

public struct Awaiter : ICriticalNotifyCompletion
{
    public void OnCompleted(Action action) => throw new NotImplementedException();

    public void UnsafeOnCompleted(Action action) => throw new NotImplementedException();
}

public struct ReturnType
{
    public Awaiter GetAwaiter() => throw new NotImplementedException();
}

public class Demo
{
    public async ReturnType RunAsync()
    {
        await Task.Yield();
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async Return Types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @KalleOlaviNiemitalo 

/cc @gafter This should also be part of the 7.0 spec updates for ValueTask and generalized async return types.
