### ISSUE TITLE
Please add the version numbers to the stupid update names

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#17591]
Nobody knows what version the "november update" or "anniversary update" was. You have to look up at wikipedia for that: https://en.wikipedia.org/wiki/Windows_10_version_history
Please write 1511, 1607, an so on instead, or at least add these version numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#feedback)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by TobiasKnauss** [comment]
The issue has been closed. When will the changes become visible?

**Comment by gewarren** [comment]
The docs are published nightly PST, so this change should be visible tomorrow morning by 10 am PST.
