### ISSUE TITLE
Steps to notarize

### ISSUE THREAD

**Issue by akshaybabloo** [dotnet/docs#17597]
It will be good to have the steps to get an application notarize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab295263-1911-add9-0388-4d43a2ffcf3f
* Version Independent ID: cff6c791-597a-ab01-6c91-3c8d24cccdaf
* Content: [Working with macOS Catalina Notarization](https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues#feedback)
* Content Source: [docs/core/install/macos-notarization-issues.md](https://github.com/dotnet/docs/blob/master/docs/core/install/macos-notarization-issues.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for the suggestion. I'll add a link to Apple's documentation.
