### ISSUE TITLE
Suggestion For DateTime Offset

### ISSUE THREAD

**Issue by Emeka-NMC** [dotnet/docs#17603]
[Suggestion To Add Unique Format-Specifiers For DateTime Offset]

DateTime-FormatString doesn't have unique characters that represents the _offset-hour_ and _offset-minutes_. Instead it uses the following format/convention:
 
| # | Offset Format specifier | Offset Format |
|:---|:---|:---|
| 1 | z | +-H  |
| 2 | zz | +-HH  |
| 3 | zzz | +-HH:mm  |
 
Can we create unique specifiers for offset-hour and another for offset-minute?
For example:
| # | Offset Format specifier | Offset Format |
|:---|:---|:---|
| 1 | r<sup>1</sup> | H  |
| 2 | rr | HH  |
| 4 | n<sup>1</sup> | +/- |
| 4 | e<sup>1</sup> | m |
| 5 | ee | mm |
 
_<sup>1</sup> I chose the last characters in Hou(r), Sig(n), and Minut(e) to represent the offset specifiers._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Sorry, we're just documentation for how it currently works. You should make your suggestion at https://github.com/dotnet/runtime/issues. I'll move this issue there.

**Comment by Thraka** [comment]
This issue was moved to dotnet/runtime#34145
