### ISSUE TITLE
Should update examples to use new C# invoke pattern that's clearer

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#17601]
i.e. `ThresholdReached?.Invoke(this, e)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89598b6d-6319-fc9e-d7b7-3335f40e9506
* Version Independent ID: e074b827-7416-3c43-7fde-0244c61bb35c
* Content: [How to: Raise and Consume Events](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events)
* Content Source: [docs/standard/events/how-to-raise-and-consume-events.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-raise-and-consume-events.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@michael-hawker Thanks for the suggestion!

**Comment by michael-hawker** [comment]
@gewarren of course, I was actually starting to try and update the sample directly, but it was harder to do on GitHub as they're spread out across multiple cs files. I'm not sure if they support batching for the quick edits yet, I'd have to dig further.

Do the samples get compiled during a PR CI build? I know that was the big move to separate them so they could be validated.

**Comment by gewarren** [comment]
> Do the samples get compiled during a PR CI build? I know that was the big move to separate them so they could be validated.

@thraka is working on that, I think it is expected in the next couple weeks.

**Comment by Thraka** [comment]
This next sprint we'll focus on coming up with a PR CI system.
