### ISSUE TITLE
Typo in Regasm.exe (Assembly Registration Tool)

### ISSUE THREAD

**Issue by rjdunnill-atwork** [dotnet/docs#17609]
[Enter feedback here]
Type: "If you use the /tlb option to registered a type library, you can use /tlb option with the /unregister option to unregistered the type library." "Registered" should be 'register."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63700a34-9f68-4f17-bfb6-21b1f5ee340c
* Version Independent ID: ee5f7263-0985-3624-d51f-fe23dd36a280
* Content: [Regasm.exe (Assembly Registration Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/regasm-exe-assembly-registration-tool)
* Content Source: [docs/framework/tools/regasm-exe-assembly-registration-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/regasm-exe-assembly-registration-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@rjdunnill-atwork Thanks for reporting that. It will be fixed by #17611.

**Comment by rjdunnill-atwork** [comment]
Thank you!
