### ISSUE TITLE
Unmanaged resources section is confusing

### ISSUE THREAD

**Issue by akhelms** [dotnet/docs#17602]
&gt;Some objects reference unmanaged resources. Unmanaged resources are resources that aren't automatically maintained by the .NET runtime.

I think you need to be more explicit here that you are referring to garbage collection, as "resources that aren't automatically maintained" is so vague that it's almost impossible to understand the connection to GC if you aren't already familiar with it. This is especially true because this is an entirely separate section from the garbage collection section, so there's no direct connection between the two in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350a9ca4-1407-4f80-0e3c-05609687c014
* Version Independent ID: 6ae6a540-0822-5e2d-cf75-97f064fa0961
* Content: [Tour of .NET](https://docs.microsoft.com/en-us/dotnet/standard/tour#feedback)
* Content Source: [docs/standard/tour.md](https://github.com/dotnet/docs/blob/master/docs/standard/tour.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@akhelms Hi!

I wonder if adding a tiny clause at the end fixes that?

>Some objects reference unmanaged resources. Unmanaged resources are resources that aren't automatically maintained by the .NET runtime and aren't collected by the garbage collector.
