### ISSUE TITLE
Null conditional operator ?. needs explicit ValueType impact clarification

### ISSUE THREAD

**Issue by redmondgiant** [dotnet/docs#17618]
### Null conditional operator ?. needs explicit ValueType impact clarification

The current docs have an aside following the example in the **Null-conditional operators ?. and ?[]** section following the example:

> The preceding example also uses the null-coalescing operator ?? to specify an alternative expression to evaluate in case the result of a null-conditional operation is null.

I suggest more explicit guidance for ValueType T comparisons, lifted up into the main part of the explanation of the section:

> When a ValueType field or property (int, bool, struct, etc.) is preceded by the ?. operator, you should consider either:
> 
> - Using '??' to supply a default value T to compare with, if value-oriented comparison is intended.
> 
> - Comparing to null instead of some value T, if merely checking if the preceding operation chain is fully-defined (and value-oriented comparison does not also matter).

Examples:
```c#
int[ ] a = null;
// all of these are perfectly fine with the compiler
if (a?.Length == 0) return; // WRONG! looks right, but only works when a is defined, not when a is null
if (a?.Length == null) return; // works, but only if you care whether a is defined and not its value
if (a?.Length == null || a?.Length == 0) return; // works as both definition and value check, but worse than the original code 'a == null || a.length == 0' 
if ((a?.Length??0) == 0) return;  // works as value check and maybe an implicit definition check, hence this whole doc comment
```

I realize you can make the transitive argument that the '?.' doc leads to Nullable<T>, and Nullable<T> behavior is separately documented; but this is a definite case where no compiler warning will happen and it will merrily cause you a lot of grief if this gets by the eyeball test while coding and debugging (assuming your eyeballs even realize it is a problem). It also flies in the face of C#, in that usually the most elegant, simple representation does what you think it does. Here, it does not. Just look above at the example that doesn't work, which is the most likely result of a dev using '?.' instead of the old 'a == null || a.Length == 0' clause. Many devs would simply remove the 'a == null ||' and add the '?'.

Try this:
```c#
if (a == null || a.Length == 0) return;
```
Edit it the simplest way that looks like it should work:
```c#
if (a?.Length == 0) return;
```
A dev new to this feature will do this and it is incorrect.

This related issue [C# Language operators: ?. Null Conditional operator #1368](https://github.com/dotnet/docs/issues/1368) reinforces the need for more explicit guidance, just look at how this has to be worded in talking about it:

> The result is null if the LHS is null, right if LHS is not null.

**Comment by pkulikov** [comment]
How big is it an issue? If one writes `if (a?.Length == 0) return;`, most probably on the next run or unit test, one gets `NullReferenceException` and quickly learns that `a?.Length` returns `null`, though it's already in the docs.

Also what is an issue here? Is it the specific described case or broader? Should we also consider other operators, not only equality ones:

```csharp
int[] a = null;
var b = a?.Length + 3;
```

@redmondgiant 
> just look at how this has to be worded in talking about it:
>
>>The result is null if the LHS is null, right if LHS is not null.

Do you suggest to include the quoted text into the docs or something else?  [That part is already described in the docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)

@BillWagner what do you think?

**Comment by redmondgiant** [comment]
I'll try to clarify by showing what I wish the compiler offered (and that docs can help mitigate the lack of).

### Summary
Expression T chains (where T is a ValueType) that _only_ use implied nullability (via ?. for example) should at least offer guidance that includes remaining as an expression T such as using '??' instead of converting to T?. This guidance bias becomes stronger with extra info like having adjacent operands of T and assignment to T around the offending expression. Future consideration in compiler errors or warnings such as CS0266 would be even better.

Note: If you use T? or Nullable<T> explicitly, that's direct intent and not part of this. Also, 'var' has nothing to do with this, other than any obscuring to the naked eye about which of these cases are actually present (if anything, making guidance more valuable due to the additional obscuring).

I see two genres of cases in my own code that would have greatly benefited by having this guidance, to ensure that I check that any effects were indeed what I intended:

- silent conversion *out* of nullability back into a ValueType, but with an incorrect answer due to silent conversion rules that can go unnoticed. bool conditions are an example of this:
```
// the silent conversions going on here aren't readily apparent
// no compiler or runtime errors
// all 3 examples eval as false
int[ ] a = null;
bool fa = (a?.Length == 0);
int[ ] b = new int[0];
bool fb = (a?.Length == 0);
int[ ] c = new int[1];
bool fc = (a?.Length == 0);
Console.WriteLine($"fa={fa} fb={fb} fc={fc}");
// output: fa=false fb=false fc=false
```

- T = ternary and T = T + T expressions that are converted to use '?.' to more elegantly handle short-circuiting null checks has inadvertently also turned them into T? + T choices for the compiler to decide. And since there is no syntax to decorate the ValueType field or property itself to indicate dev intent, it sides with T?
```
// ternary conversion to use ?. 
int[ ] a = null;
bool b = (a != null ? a.Length : 0) + 3;   // old code before ?.
bool b = a?Length + 3;                     // CS0266, should at least suggest using '??' as well
bool b = (a?.Length??0) + 3;               // what is actually intended by the dev
```
```
// compiler assumes T? + T should be T?, and error if you try to say you want T
// CS0266 Cannot implicitly convert type 'int?' to 'int'. ...
// T? when introduced from ?. chains should at least offer guidance that you can use '??' to remain T
int[] a = null;
int? i = a?.Length;     // could warn '?. introduces a Nullable<T>, use '??' to ensure a T result
int? i = a?.Length + 3; // same, or the '3' is useless for what the dev thinks is the default case
int i = a?.Length + 3;  // CS0266 Cannot implicitly convert type 'int?' to 'int'...
is led to do in 99% of cases:
int i = (a?Length??0) + 3; // by compiler or docs guidance, this is what the dev intended 
```
The CS0266 examples above are the most obvious place for '??' guidance: an implicit-only T? and T as operands and a lhs of T as well, and still the compiler doesn't offer that the intent is to just remain as a T and not introduce nullability.

I know this is a tricky area, as there are many rules and pitfalls, and no one answer is likely ever correct in all cases. And that is where docs can help clarify and guide.

HTH

**Comment by pkulikov** [comment]
@redmondgiant thanks for the summary. Indeed, the current docs don't say about the jump to nullability explicitly.

Do you think something like that would be useful?

> If expression `a.x` has non-nullable value type `T`, expression `a?.x` has type `T?`. If you need an expression to have type `T`, use the null-coalescing operator `??` to specify the value for the `null` case: `a?.x ?? fallback`, as the following example shows:...

**Comment by redmondgiant** [comment]
Yes, thanks.

One more aspect to go with that, if it can be worked into the text; something to the effect of reminding developers about converting existing code that clearly was not nullable-aware before the use of '?.':

> Using '?? to provide a fallback value T is common when converting existing code to use '?.', to ensure that the improved short-circuiting is confined to the converted code and that nullability is not unintentionally introduced to surrounding code which is not expecting it.
>
> Subtle differences in expression results may result otherwise.
>
> Example:

```
bool b1 = a?.Length == 0;        // false if a == null, otherwise compares Length and 0
bool b2 = a?.Length??0 == 0     // true is a == null, but for the wrong reason - due to precedence since it evals as a?.Length??(0 == 0)
bool b2 = (a?.Length??0) == 0    // true if a == null, otherwise compares Length and 0, this is what dev intended
```

> Note the need for ( ) when using ??, since the precedence of ?? is lower than most other operators including conditional operators like == and &&.

Thanks again for the solid docs btw, I only noticed this through experience with extensively converting my code, and noticing the pain points where extra debugging unexpectedly popped up.

**Comment by pkulikov** [comment]
@redmondgiant thanks for the discussion. By the way, the compiler also does a good job of informing. For example, `a?.Length ?? 0 == 0` doesn't compile at all.

**Comment by BillWagner** [comment]
This is a great discussion. Thanks @redmondgiant and @pkulikov 

I agree that the additions suggested https://github.com/dotnet/docs/issues/17618#issuecomment-605452399 and https://github.com/dotnet/docs/issues/17618#issuecomment-605695740 would help.

I've added labels, including the "up for grabs" label. Would either of you want to submit a PR for this? If not, we'll address it as we update this article.

**Comment by pkulikov** [comment]
@BillWagner I would like to submit the PR
