### ISSUE TITLE
<inheritdoc> is missing in the "Documentation tag reference"

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#17612]
There page for &lt;inheritdoc&gt; is not linked in the "Documentation tag reference" section. Please add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5aa865-b9d2-e977-a272-3886aa0a1111
* Version Independent ID: 353b1c44-b90a-e5cc-a193-7b42ec714290
* Content: [Recommended tags for documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @TobiasKnauss 

The `<inheritdoc>` tag is listed in the table on this page for recommended tags. It is missing the TOC for the C# guide, and should be added there.

We'll get this fixed.

I've added the "up for grabs" label to this issue for community members who may want to address this before we get to it.
