### ISSUE TITLE
Unavailable Technologies incomplete

### ISSUE THREAD

**Issue by fowl2** [dotnet/docs#17621]
Eg.  This page doesn't list Workflow Foundation or WCF

WCF is available as part of the [Windows Compatibility Pack](https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack) - although I doubt it's a complete drop-in replacement as app.config is gone, etc.

Workflow is just gone though as far as I can tell.

Additionally, the second paragraph is obsolete as [no more Framework APIs are to be ported to Core](https://github.com/dotnet/announcements/issues/130). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e44818-fc25-7210-c430-7c87b84825eb
* Version Independent ID: 2f40ef4c-ea4b-ccb5-3b7f-9d02c3b7ab82
* Content: [.NET Framework technologies unavailable on .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable)
* Content Source: [docs/core/porting/net-framework-tech-unavailable.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/net-framework-tech-unavailable.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by StingyJack** [comment]
@fowl2 FWIW you can still use an app.config in a netcore app, if you use the System.Configuration package.  I use it often. 

For data interchange, Json > XML (most of the time). 
For configuration, XML > Json (all of the time, for the simple reason of built in commenting)

**Comment by jeremy-waguet** [comment]
And what about ClickOnce not available with .NET Core

**Comment by StingyJack** [comment]
This should be reopened
