### ISSUE TITLE
Syntax description missing

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#17625]
The example shows that "cref=" can be used. This is not written in the description itself. So I wonder whether the syntax includes other possible constructs that are not described. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04441bbc-7e98-d6df-2c5a-20e816d79dc7
* Version Independent ID: ba155807-a2b0-8982-abe7-fac1e2b51a7d
* Content: [&lt;inheritdoc&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/inheritdoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/inheritdoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
/cc @mikadumont 

Do you know the right fix for this question?

**Comment by mikadumont** [comment]
Adding @sharwell who may know.

**Comment by BillWagner** [comment]
reopening to address as part of updating the XML section.
