### ISSUE TITLE
Local functions vs Lambda expressions: Incorrect information

### ISSUE THREAD

**Issue by RichardD2** [dotnet/docs#1763]
https://docs.microsoft.com/en-us/dotnet/articles/csharp/local-functions-vs-lambdas
https://github.com/dotnet/docs/blob/master/docs/csharp/local-functions-vs-lambdas.md

The first difference states:

> First, for lambda expressions, the compiler must create an anonymous class and an instance of that class to store any variables captured by the closure. The closure for this lambda expression contains the address, index and name variables.

However, the compiler has to do *exactly* the same thing for local functions.

**Comment by svick** [comment]
> However, the compiler has to do *exactly* the same thing for local functions.

Not really. There are cases where the compiler can create an anonymous *struct* for a local function, even though it would have to create a class for a lambda, thus avoiding a heap allocation.

Though [looking at the decompiled code](https://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUKSWRFDAOgBUALAJ1QEMATQiukAaxB1zwjvVRAAHOgGNUMCKgDuAfUgyA7HgDeeGOpiDgAIwA2YETBG7WIGAEEQCCCIDqAe2ps1G1bg0eYAYlpQw9iBgAJgBOGXJWNgBRAA8+QV1UF09NHX1DCPYAHhRqQgA+GAAFVGoAM0d0ABkAqAAlYAgIQgcnAApcwhhGBloQEAAaGEhkYYgGVBihzugJPlQASmTPNxSUsDKYDuQ86FIASRAAOWBdXQB5altKMDQ4YTE2nr6QBaX3Nc/kGnspCWkLNQoMB+BBkLExIJkP4IG1+P06FBUAAuGAAInMgWeAjMYDMtAAjsAwLQGGihsJqHwjvNUbx+PYyk8GL0cW8uJ8PBstpAJjEYFkYAAGd6ctbfai/f5/cxAkGoMHnYDIc5lOp0aCoCGoKEwtqU6m0uYMpm8yYLIbwkCIlHoqjiM389CgUbacQQAIAWkkUDo0IAbqg0QsOWLhpttrsoAdjqcLlcbncHqg2vTFqKwx4JVLJDK5aDwTFIdCAnCcTbUWiAJr2YAwZ0oGAgYCCBIIbrGoMUuhU9A0/h0+aM1Pzdl4ZafWjIYDUQK6WoNJotRxsfboBIYBXIP16kPjj5i1jWDKRHI7AowefQRfNaCtVfrxIFneljNi1aZjT+ntjNB5dB1AIpyjAAvN0Uh0LcMAAGIkig97Mqy/R7gen7ftQTaoCIAQMIBza6KB4GQaMcBYThcBoIIbSOkMaYoZ+GhTjOgQACRovaMB9MBZg9uIygjKUYAAUBBEAL7dOMMDKCAZHjHhwGiaQMBRBAABW9gIKQaKhmKokThoemoR4XgKqyfgBPunyCHk35oN0Vg2DAmRsGeUaFKR2HjBROptPsYIAMxBGMfJDBRUadm+Kz6SkdAQVBzmkAAIqgJgIG0ACsIo6ZyTGznaNxmNhpwMDAbodhU1DoH6TbntA2nRTAhkNdZYC2eIR6Oc5WQjIUsHUPBK5tGFXTYshDUfoecWjAlyWpW0ACMQpZQ1Hi5YEAAsQTZR4TVGRoPioOZgT+QAbOEkRVHw2gMHQsTxIkzVpAYTmnjMUCFCU5SVDU16NLeUD3pd6DXXQkYjSyLxDCMwWTNMtWwHR40rRo3Jg3shwnGclzXLcqD3KIKaja8kWZtmfy5oCwIFtquqllaFbopi3QQziwz4qgRIkqgZLdr2/a2mmw5E2Oe3rBGjoCsKJNhmT0qU/KirKqq6qajTJawgafZGoLprjOalrlkilYcRLDauu6Xo+jugbBttayo29MaY/GONJgTI78G8yMpLLFOylTW5q3q9NG+iNZ1mbTYtm2HZpuSmg9oaA6dsOdEod7MGNCIWRdW9+SFFe9R/cuThrhuz7qzAYEdYYbQLFX+QZxNaE/gJ/7yQRVdEVBfUDe0wt22K6GYZ5uEiYRsXEfAskMN5VE0RFg85ag055WxHFcQRPG0FJbdCR3yDiRqJXSTPB+KcpakaVpS87VwGdrZeC7F3eK5l0+W4vrC9FrIZnwmeMXwMJliGUMkAA==), this is not one of those cases.

Considering that the "third" point has its own example, and that the "first" point does not apply to this example, maybe the main example could be removed and each point could have its own? Or something along those lines.

cc: @BillWagner

**Comment by RichardD2** [comment]
> There are cases where the compiler can create an anonymous struct for a local function, even though it would have to create a class for a lambda, thus avoiding a heap allocation.

That's interesting - I didn't know it could do that. 👍 

But, as you say, this example isn't one of those cases. Perhaps it would be better to have an example where that *does* happen. :)
