### ISSUE TITLE
Influence of Date on the prediction output

### ISSUE THREAD

**Issue by asif48** [dotnet/docs#17636]
Hi Author ...Excellent stuff...
I wounder If we can include a Date column in the input feature to have its influence on the predicted output ?

I modified the TaxiFairExample to include a Date column to predict whether a taxi is likely to puncture or not on the coming day  but an error arose "System.ArgumentOutOfRangeException: 'Could not determine an IDataView type for member Date Parameter name: rawType' ".

If you an help on this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e7cf89-1a90-7693-db50-11b770c09160
* Version Independent ID: 21c26fd2-c6ad-2c2f-166b-03ac0590a1c2
* Content: [Make predictions with a trained model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @asif48 ,

I see you've raised this issue in the dotnet/machinelearning repo.

dotnet/machinelearning#4980

I'd keep an eye on that issue since it's more related to the product.
