### ISSUE TITLE
The code sample for GetLoadContext isn't correct

### ISSUE THREAD

**Issue by elezar42** [dotnet/docs#17632]
The code sample in the "Debugging type conversion issues" section doesn't have the correct namespace for the calls to GetLoadContext(). The "Loader" part of the namespace is missing.  It should be:

System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(a.GetType().Assembly)
System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(b.GetType().Assembly)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c83628c-7002-9045-9c72-f8d97b784eb0
* Version Independent ID: a761a83d-5aa8-958a-d210-6eb8f7929ff2
* Content: [Understanding AssemblyLoadContext - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#feedback)
* Content Source: [docs/core/dependency-loading/understanding-assemblyloadcontext.md](https://github.com/dotnet/docs/blob/master/docs/core/dependency-loading/understanding-assemblyloadcontext.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by tdykstra** [comment]
@elezar42 Thanks for reporting that!
