### ISSUE TITLE
Loading multiple files with star (*) is not supported more.

### ISSUE THREAD

**Issue by mehtanilay10** [dotnet/docs#17637]
Due to below Pull request, loading multiple files with start pattern is no more supported.
Either need to add it back or update documentation for remove its example.

Ref: https://github.com/dotnet/machinelearning/pull/4665

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52d4fbe-df9c-f410-85b4-786b139e94d3
* Version Independent ID: ce6265fd-1d0b-4d58-c60d-178d512486b4
* Content: [Load data from files and other sources - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/load-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
dotnet/machinelearning#4982

**Comment by luisquintanilla** [comment]
Hi @mehtanilay10 

Thank you for your feedback. At the moment, the Docs use the latest stable version of the API 1.4.0. When the next stable version is released, we'll update our docs to reflect these changes.
