### ISSUE TITLE
doc syntax for calling named properties from an int indexer would be nice

### ISSUE THREAD

**Issue by troglobytor** [dotnet/docs#17639]
I had a small number(12) named properties with enough code inside of each that I only wanted to call the property from a numbered index so there would be only one place to maintain.Get was easy, but set is vexing me. It would be nice to see how to do such from a switch index.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc06ead-fe51-85db-1340-87f6473db769
* Version Independent ID: 4f2c312e-609c-a643-4af6-c12c6cf74738
* Content: [Indexers](https://docs.microsoft.com/en-us/dotnet/csharp/indexers)
* Content Source: [docs/csharp/indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/indexers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by troglobytor** [comment]
`OK,` it's simple but maybe others could have brain gas occasionally:
```public: property String^ default[int]{
  String ^ get(int i) { return aRow[i]; }
  void set(int i, String ^ s) {
    switch (i) {
    case 0:
        SYMBOL = s; break;
    case 1:
        NAME = s; break;
    case 2:
        LASTSALE = s; break;
    case 3:
        MARKETCAP = s; break;
//....`

**Comment by BillWagner** [comment]
I'm glad you solved this @troglobytor 

I'll close this. If you have further issues, you can reopen this, or create a new issue.
