### ISSUE TITLE
Sprinkle ".NET Core CLI" throughout .NET Core Tools docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#1764]
A user said that they searched on ".NET CLI" and didn't find the right docs. We don't use this term much in the docs, but we do in other places. I don't suggest moving to this term, generally. It's essentially a colloquial term. It is however, a good idea, to conservatively (as opposed to liberally) sprinkle it in some key docs that that people searching for it are more likely to get to some useful docs and not just blog posts.

**Comment by mairaw** [comment]
We do have CLI in the keywords metadata, but I think we could actually add that to the title of the .NET Core CLI commands. 

For example: 
dotnet-migrate command | Microsoft Docs ->
dotnet-migrate command - .NET Core CLI | Microsoft Docs
