### ISSUE TITLE
Settings File

### ISSUE THREAD

**Issue by mjhillman** [dotnet/docs#17641]
You should include information about how to replace the settings file as the project template does not include a startup file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca63e896-e1eb-9714-aeaf-67f56cf582ca
* Version Independent ID: 20fd8665-a5ef-eebe-d01a-9eaf1a60b023
* Content: [Port a Windows Forms app to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/winforms#feedback)
* Content Source: [docs/core/porting/winforms.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/winforms.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@OliaG Can you comment on the settings file?

**Comment by mjhillman** [comment]
So normally you would use appsettings.json in lieu of the settings file which would be configured in startup.cs.  The project template results in an application without a startup.cs file so the developer using this project template who is unfamiliar with .Net core applications will have no clues about how to replace the settings file normally present in a WinForm application.

**Comment by Thraka** [comment]
I wonder if the [try-convert](https://github.com/dotnet/try-convert) tool handles this?
