### ISSUE TITLE
Lock could be held for a shorter period of time

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#17642]
In general, it's a good idea to hold a lock for as short a time as possible, so that one thread doesn't have to wait for another thread to perform potentially slow operations that have nothing to do with the locked resource.

The console I/O in the example code, for instance, is an example of a potentially slow operation (much slower than simple arithmetic calculations).  There's no need for the console write calls that display the old and new balance to be performed with the lock held.  Instead, the two balance values could be copied to temporary local variables (while holding the lock) and then printed only after releasing the lock, something like this (for the debit case):

public decimal Debit(decimal amount)
{
    decimal return_value;

    // These must be declared outside the lock so that they can still be
    // accessed after the lock is released.
    decimal old_balance, new_balance;

    // Hold the lock for as short a period of time as possible, only long
    // enough to perform the arithmetic.
    lock (balanceLock)
    {
        old_balance = balance;

        if (old_balance &gt;= amount)
        {
            new_balance = old_balance - amount;
            balance = new_balance;
            return_value = amount;
        }
        else
        {
            new_balance = old_balance;
            // (no change to balance)
            return_value = 0;
        }
    }

    Console.WriteLine($"Balance before debit :{old_balance, 5}");
    Console.WriteLine($"Amount to remove     :{amount, 5}");
    Console.WriteLine($"Balance after debit  :{new_balance, 5}");

    return return_value;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b544eeb3-082e-1c67-eb76-f5ce0acee45e
* Version Independent ID: d4765a2e-ac77-e947-165c-5a0f88f4e8e2
* Content: [lock statement - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/lock-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/lock-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
> In general, it's a good idea to hold a lock for as short a time as possible, so that one thread doesn't have to wait for another thread to perform potentially slow operations that have nothing to do with the locked resource.

That's right. I think the note about that would be useful. However, I'm afraid that modifying the example would make it unnecessary complicated.

**Comment by matthew45052** [comment]
... at the cost of teaching poor software design techniques.

**Comment by BillWagner** [comment]
Thanks for writing this @matthew45052 And thanks for the discussion @pkulikov 

I have another suggestion for updating the sample: With some refactoring, the `WriteLine` statements can be moved into (static) helper routines that take the balance as an argument. Because the balance is a value type, it's copied, and could be called outside the lock. Yes, this does create a few one line methods (or expression bodied members), but it is both improved and not too complicated.

Thoughts?

**Comment by pkulikov** [comment]
> Because the `balance` is a value type, it's copied, and could be called outside the lock.

The `balance` field can still be updated by another thread between the call to the helper routine and entering the lock. Thus, the helper routine would output not correct value. Have I missed anything @BillWagner?

**Comment by pkulikov** [comment]
@BillWagner @matthew45052 all in all, I would remove all the `Console.WriteLine` calls and update the test application in the following way:

1. create the routine that changes the balance in the known way (not random), let's say by `change`
1. run 100 such routines in parallel

The output is known, that is, `new_balance` = `old_balance` + 100 * `change`

**Comment by BillWagner** [comment]
@pkulikov I like that plan.

**Comment by pkulikov** [comment]
> @pkulikov I like that plan.

Then I can submit the PR
