### ISSUE TITLE
Link to List Module is broken

### ISSUE THREAD

**Issue by Jawvig** [dotnet/docs#17656]
The hyperlink to the List Module leads to a broken page: 
https://msdn.microsoft.com/library/a2264ba3-2d45-40dd-9040-4f7aa2ad9788
This may have been down for days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc3b624-2978-8ae2-8ad0-0ae1613395af
* Version Independent ID: 0632dadf-1f15-d3ed-9751-b5b1d100df44
* Content: [Lists - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists)
* Content Source: [docs/fsharp/language-reference/lists.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/lists.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
Same underlying issue as #17557.

**Comment by cartermp** [comment]
We're working with the team that does redirects on this one. The core issue is a small handful of links needed redirection, but something went awry and the whole reference was redirected. It's apparently a little tricky.

**Comment by Jawvig** [comment]
Good luck with it, and thanks for the update.

**Comment by gewarren** [comment]
Thanks for reporting this. Closing as a duplicate.
