### ISSUE TITLE
Example is not valid

### ISSUE THREAD

**Issue by bitm0de** [dotnet/docs#17651]
The SerializeOverride() method is defined to be a class where the class in the code example is used like a method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f78552f8-0bb2-0a65-e19e-85b432b09890
* Version Independent ID: 81a339ab-2e79-4be7-8a9f-b18a1a86a1a0
* Content: [How to: Specify an Alternate Element Name for an XML Stream](https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-specify-an-alternate-element-name-for-an-xml-stream?view=netframework-4.8#feedback)
* Content Source: [docs/standard/serialization/how-to-specify-an-alternate-element-name-for-an-xml-stream.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/how-to-specify-an-alternate-element-name-for-an-xml-stream.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@bitm0de Thanks for reporting that.
