### ISSUE TITLE
Document behavior differences in StrongName assembly binding between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by ryandle** [dotnet/docs#17668]
These internal docs seem to collectively cover how DLL version comes in to play for loading strong named assemblies:

- https://github.com/dotnet/runtime/blob/master/docs/design/features/host-probing.md 
- https://github.com/dotnet/runtime/blob/master/docs/design/features/host-component-dependencies-resolution.md 
- https://github.com/dotnet/runtime/blob/master/docs/design/features/assembly-conflict-resolution.md

But I don't see any guidance on docs.microsoft.com that tells developers how assembly binding behaviors changed between Full Framework & Core. 

Essentially what I'm looking for is "What's difference between [this behavior in full framework](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies) and the new behavior in Core."

Here's a scenario that I would like to have explained as part of the documentation:

> Setup:
> * My library depends on A & B
> * A depends on C Version 1.0.0
> * B depends on C Version 1.1.0
> * I deploy C version 1.1.0

If I do this in full framework, I'll get a binding failure when we can't find A's dependency on C 1.0.0. But on Core I think this will just work? Explaining *why* it just works, i.e. the algorithm changes, is what I'm looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73a9cdd-9378-bc27-fcda-8804ebb9c9ce
* Version Independent ID: bd57feac-b27d-e56c-aad4-a637505a9206
* Content: [Default probing - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#feedback)
* Content Source: [docs/core/dependency-loading/default-probing.md](https://github.com/dotnet/docs/blob/master/docs/core/dependency-loading/default-probing.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by vitek-karas** [comment]
I think this article https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/overview describes the details of the assembly loading process in .NET Core which might answer your question. If there are still unanswered issues, please let us know by  probably filing an issue against one of those articles (as the change should very likely be made in them).

**Comment by sharwell** [comment]
Updating labels per the response in https://github.com/dotnet/docs/issues/17668#issuecomment-766900397
