### ISSUE TITLE
Where did JsonSerializerSettings.CheckAdditionalContent go?

### ISSUE THREAD

**Issue by CreepyGnome** [dotnet/docs#17666]
There is mappings for the other JsonSerializerSettings that there seems to be one not documented that didn't get migrated as to its status and that is JsonSerializerSettings.CheckAdditionalContent.

Where did this go, is there a workaround, or does System.Text.Json do this by default now and if you where setting it to true we have nothing to be concerned about?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @layomia @Jozkee

**Comment by tdykstra** [comment]
@layomia @Jozkee Would you recommend a custom converter to do what Newtonsoft [CheckAdditionalContent](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_CheckAdditionalContent.htm) does?

**Comment by layomia** [comment]
Taking a look at the scenario now. @CreepyGnome, can you provide an example of when this is useful?

**Comment by ryan-morris** [comment]
We use `CheckAdditionalContent` to help validate POST body content. If user sends up additional unknown attributes we want it to be clear that value has no meaning.
