### ISSUE TITLE
"See also" documentation links are broken

### ISSUE THREAD

**Issue by timoffex** [dotnet/docs#17662]
E.g. "Control.Event Module" links to https://msdn.microsoft.com/visualfsharpdocs/conceptual/control.event-module-%5bfsharp%5d which unhelpfully displays

"Error

Sorry, this page is unavailable. Please try again later."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78397d09-6174-74aa-6fe7-7aa7e87b44a6
* Version Independent ID: 3291294d-3965-0662-a2e0-410be6b69817
* Content: [Events - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/events#feedback)
* Content Source: [docs/fsharp/language-reference/members/events.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/events.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
Same underlying issue as #17557.

**Comment by cartermp** [comment]
We're working with the team that does redirects on this one. The core issue is a small handful of links needed redirection, but something went awry and the whole reference was redirected. It's apparently a little tricky.

**Comment by gewarren** [comment]
Closing as a duplicate. Thanks for reporting this.
