### ISSUE TITLE
Documentation Duplication Between .NET Projects

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#1767]
Porting https://github.com/dotnet/corefx/issues/5899

- Move dotnet/corefx/Documentation/project-docs/glossary.md to dotnet/core-docs
- Follow @cartermp's advice and add new TOC entry "Glossary" under "Understanding the .NET Platform"

@cartermp

**Comment by danmosemsft** [comment]
@blackdwarf

**Comment by mairaw** [comment]
@tdykstra this is related to our glossary and terminology discussion
