### ISSUE TITLE
AssemblyDependencyResolver not referenced

### ISSUE THREAD

**Issue by markolbert** [dotnet/docs#17677]
I don't see a link to AssemblyDependencyResolver from where it's used in the source code example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3283764-f15a-fa5f-5106-6f294c780f7b
* Version Independent ID: b03cedce-9074-9686-0b31-045b2b4c862d
* Content: [How to use and debug assembly unloadability in .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#feedback)
* Content Source: [docs/standard/assembly/unloadability.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/unloadability.md)
* Product: **dotnet**
* GitHub Login: @janvorli
* Microsoft Alias: **janvorli**

**Comment by markolbert** [comment]
There's something weird going on when I try to use AssemblyDependencyResolver: it shows up in the Object Browser in VS 2019, so I know I've installed the System.Runtime.Loader package correctly. But IntelliSense fails to recognize the class and you can't reference the class in source code. Bizarre.

**Comment by gewarren** [comment]
Related to #17676.

**Comment by markolbert** [comment]
Apologies I must've missed the notifications that this issue had gotten more comments/discussion. My bad.

Short answer: it was my mistake because I was using the class in a NetStandard2.1 library. When I changed it to being a NetCore3.1 library (I didn't know you could do that) the problem went away. I'll close the issue.
