### ISSUE TITLE
What if a microservice prefer strong consistency over availability?

### ISSUE THREAD

**Issue by topnessman** [dotnet/docs#17673]
Thanks very much for this great article! It provides a really good overview about common challenges when working with microservices. However, regarding Challenge #3, I wonder how people in the industry are doing generally in order to achieve strong consistency and availability is less favored? I have a use case where microservice A manages its own data that is directly coming from clients. But microservice B must know the most up-to-date data/updates in microservices A, otherwise it would cause wrong information to be shown at the client side, or in other word, data in microservice A is very critical and it has to be real-time from microservice B's perspective. And one constraint is A and B services cannot be merged. It would be good if there are some discussions around this "uncommon" use case. Thanks very much in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19862882-c106-afa7-660e-ead3b5dd880a
* Version Independent ID: fea4a2d6-8aa5-a400-4261-6098e76d362b
* Content: [Challenges and solutions for distributed data management](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management#feedback)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/distributed-data-management.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Thanks @topnessman for reaching out.

To my opinion it depends on what is important for the business requirement. As you have pointed out data consistency is preferred than availability you can follow a design pattern 
like [Saga](https://microservices.io/patterns/data/saga.html). For e.g : [Event driven saga](https://microservices.io/patterns/data/event-driven-architecture.html)

Along with that I would like to consider the purpose of the microservices. For an example let's say there is an aggregated views in microservices architecture where you use some aggregate pattern to collate data from various microservices and then display them in a UI which has requirement to display composite views from various individual microservices (like in a grid etc.). 
In such scenario if I have to update data in realtime, I may choose to use SignalR to update the details.

And in terms of challenges you may want to have a quick look into [Data Considerations for microservices](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/data-considerations)

**Comment by topnessman** [comment]
@sughosneo Thanks for the reply. After reading through couple articles and blogs these months, I've learnt that what my team is doing might not be real micro-services, but instead Service Orientated Architecture (SOA). So I'm guessing whatever applies to micro-services may not be applicable here?

**Comment by sughosneo** [comment]
Hi @topnessman, yes that's true. The approaches what you take in microservices architecture pattern, are different than the monolith. If you are planning to migrate them to microservices there you can refer this [migrate-monolith](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith)

Thank you.

**Comment by topnessman** [comment]
Thanks for the guide! I'm closing this issue as it doesn't apply any more.
