### ISSUE TITLE
isCollectible doesn't seem to exist

### ISSUE THREAD

**Issue by markolbert** [dotnet/docs#17676]
The latest version of AssemblyLoadContext in Net Core 3.1 doesn't seem to have a constructor taking a boolean value for isCollectible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3283764-f15a-fa5f-5106-6f294c780f7b
* Version Independent ID: b03cedce-9074-9686-0b31-045b2b4c862d
* Content: [How to use and debug assembly unloadability in .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#feedback)
* Content Source: [docs/standard/assembly/unloadability.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/unloadability.md)
* Product: **dotnet**
* GitHub Login: @janvorli
* Microsoft Alias: **janvorli**

**Comment by janvorli** [comment]
@markolbert I've seen your other problem with AssemblyDependencyResolver not being recognized during compilation / by intellisense in VS. Are you sure you have your project set to use .NET Core 3.1? In the project properties on the Application page, there is "Target framework". Does it show ".NET Core 3.1" for your problematic project?
Also, if you download the demo project for unloadability from https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading and open it in your Visual Studio, does it also fail to build?

**Comment by markolbert** [comment]
Apologies I must've missed the notifications that this issue had gotten more comments/discussion. My bad.

Short answer: it was my mistake because I was using the class in a NetStandard2.1 library. When I changed it to being a NetCore3.1 library (I didn't know you could do that) the problem went away. I'll close the issue.

**Comment by gewarren** [comment]
No worries, thanks for following up!
