### ISSUE TITLE
The code can work well on .net fx 4.7 but not on dotnetcore3.1

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17683]
@jinsh2019 commented on [Thu Apr 02 2020](https://github.com/dotnet/docs.de-de/issues/175)

The code can work well on .net fx 4.7 but not on dotnetcore3.1
The error msg:
System.PlatformNotSupportedException:“Operation is not supported on this platform.”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c5f5f4b7-b600-d163-ccef-9cf4b0693419
* Version Independent ID: 6e986136-5b77-4abc-da4c-9366c10826d5
* Content: [如何：使用 CodeDOM 创建类](https://docs.microsoft.com/zh-cn/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom#feedback)
* Content Source: [docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/reflection-and-codedom/how-to-create-a-class-using-codedom.md)
* Product: **dotnet-framework**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

---

@srvbpigh commented on [Thu Apr 02 2020](https://github.com/dotnet/docs.de-de/issues/175#issuecomment-607630355)

Hello, @jinsh2019
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by gewarren** [comment]
It's noted [here](https://docs.microsoft.com/dotnet/core/compatibility/unsupported-apis#systemcodedomcompiler), but would be good to note in _this_ article that it doesn't work on .NET Core.

**Comment by Thraka** [comment]
I'm unsure what our messaging strategy will be. This article is in the .NET Framework area and not the .NET Standard (common) area, so we should assume this section is specific to .NET Framework.
