### ISSUE TITLE
Sample Applications link does not work

### ISSUE THREAD

**Issue by ChrisFoggDelta-T** [dotnet/docs#17682]
https://docs.microsoft.com/en-gb/dotnet/visual-basic/sample-applications
Get 404 error

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc32151-058c-e82b-8654-bec1020afd9b
* Version Independent ID: e7d42142-da3f-8f5e-28ed-82ba61327361
* Content: [Get started - Visual Basic](https://docs.microsoft.com/en-gb/dotnet/visual-basic/getting-started/#feedback)
* Content Source: [docs/visual-basic/getting-started/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by gewarren** [comment]
Should we link here instead?

https://docs.microsoft.com/samples/browse/?languages=vb
