### ISSUE TITLE
File doesn't build

### ISSUE THREAD

**Issue by TangledTessellations** [dotnet/docs#17684]
In the step above `Select Build &gt; Build All from the menu.` I don't see anything in the build Menu.
I've selected "Build Output" Several times, and just see two blank boxes below. 0 errors, 0 warnings, 0 messages.

Using Visual Studio for Mac Community, V 8.5.1 (build 42)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d01d28-eba7-401c-5716-1361edfa928d
* Version Independent ID: f235603a-edcc-257a-901e-b0709cf81053
* Content: [Build a complete .NET Core solution using Visual Studio for Mac - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution#feedback)
* Content Source: [docs/core/tutorials/using-on-mac-vs-full-solution.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs-full-solution.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment]
Thanks for writing this @TangledTessellations 

Can you add a screenshot of what you see? I think the problem is that the output pane is too short to display more of the text output, but I'm not sure.

Thanks.
