### ISSUE TITLE
dotnet test tests/WebApi.IntegrationTests --filter "DisplayName\!~WebApi.IntegrationTests.Controllers.Manage"

### ISSUE THREAD

**Issue by hamidullov** [dotnet/docs#17681]
After execute command on macOs I got this error

 [xUnit.net 00:00:01.14] WebApi.IntegrationTests: Exception filtering tests: Incorrect format for TestCaseFilter Error: Invalid Condition 'DisplayName!~WebApi.IntegrationTests.Controllers.Manage'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
No test is available in /tests/WebApi.IntegrationTests/bin/Debug/netcoreapp3.1/WebApi.IntegrationTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

I have many tests whose not contain DisplayName WebApi.IntegrationTests.Controllers.Manage

**Target framework**

- [ ] .NET Core

<details>
<summary><strong>dotnet --info output</strong>

```console
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]


```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@hamidullov What is the URL of the documentation article this question is about?

**Comment by hamidullov** [comment]
> @hamidullov What is the URL of the documentation article this question is about?

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details

**Comment by tdykstra** [comment]
See the note at the top of this page:  https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests

**Comment by hamidullov** [comment]
All available tests
`dotnet test -t tests/WebApi.IntegrationTests`
```terminal
The following Tests are available:
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_ReturnsSuccess
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByPassportData
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByNameAndBirthDay
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByNameAndBirthDayLevenshteinDist1
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByNameAndBirthDayLevenshteinDist2
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_SuccessByNameAndBirthDayLevenshteinDist3
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_ByBlackPassports
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByNameAndLicenseNumber
    WebApi.IntegrationTests.Controllers.Validate.ValidateTest.ValidatePersonalData_FailedByName
    WebApi.IntegrationTests.Controllers.Manage.UploadTest.UploadRuFinMonitoringSuccess
    WebApi.IntegrationTests.Controllers.Manage.UploadTest.UploadUsFinMonitoringSuccess
    WebApi.IntegrationTests.Controllers.Manage.UploadTest.UploadRuFmsBlackPassportsSuccess
    WebApi.IntegrationTests.Controllers.BlackLists.GetAllTest.Get_Success
```
I ran with various `--filter` options
```
dotnet test tests/WebApi.IntegrationTests --filter FullyQualifiedName\!~Manage
dotnet test tests/WebApi.IntegrationTests --filter FullyQualifiedName\!~WebApi.IntegrationTests.Controllers.Manage
dotnet test tests/WebApi.IntegrationTests --filter FullyQualifiedName\!~WebApi.IntegrationTests.Controllers.Manage.UploadTest.UploadUsFinMonitoringSuccess

All of these return error message `No test is available ...`

I don't see here https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests#xunit  filter expression with option !~. Should it work?

**Comment by tdykstra** [comment]
@smadala Should `!~` work with xUnit?

**Comment by tdykstra** [comment]
@kendrahavens who can help with this question?

**Comment by nohwnd** [comment]
Works for me on Mac (sorry for the Czech output): 

```shell
nohwnd@nohwnds-MacBook-Pro xunit1 % dotnet test --filter "DisplayName\!~WebApi.IntegrationTests.Controllers.Manage"
Testovací běh pro: /Users/nohwnd/xunit1/bin/Debug/netcoreapp3.1/xunit1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool verze 16.5.0
Copyright (c) Microsoft Corporation. Všechna práva vyhrazena.

Začínají se provádět testy, počkejte prosím...

Celkový počet testovacích souborů, které odpovídají zadanému vzoru: 1

Testovací běh byl úspěšný.
Celkový počet testů: 1
     Úspěšné: 1
 Celkový čas: 1,3798 Sekundy




nohwnd@nohwnds-MacBook-Pro xunit1 % dotnet test                                
Testovací běh pro: /Users/nohwnd/xunit1/bin/Debug/netcoreapp3.1/xunit1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool verze 16.5.0
Copyright (c) Microsoft Corporation. Všechna práva vyhrazena.

Začínají se provádět testy, počkejte prosím...

Celkový počet testovacích souborů, které odpovídají zadanému vzoru: 1

Testovací běh byl úspěšný.
Celkový počet testů: 2
     Úspěšné: 2
 Celkový čas: 1,2849 Sekundy



nohwnd@nohwnds-MacBook-Pro xunit1 % dotnet --version
3.1.200
```

**Comment by tdykstra** [comment]
@hamidullov We are unable to repro `!~` not working.  The documentation is correct, as it includes a `!~` example, so I'll close this docs issue.

If you'd like this to be investigated as a possible product bug, let me know and I'll transfer the issue to the sdk repo.  You might also try posting a question on a support forum such as StackOverflow.

**Comment by mausch** [comment]
I just ran into this, had to upgrade the `Microsoft.NET.Test.Sdk` nuget package.
Apparently version 15.5.0 doesn't support `!~` (?), upgrading to 16.11.0 fixed it.
