### ISSUE TITLE
Not able to install on WSL

### ISSUE THREAD

**Issue by cyboashu** [dotnet/docs#17693]
**Not able to install on WSL**

I am trying to install dot net core using on WSL (Ubuntu 18.04) from this page https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

**Issue description**

I have tried all the options mentioned on the page. 

But every time I get this Error:

> Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                       
Reading package lists... Done                                                                                          
E: The repository 'https://packages.microsoft.com/ubuntu/18.04/prod bionic Release' does not have a Release file. 

How can I resolve this?

[Edit by gewarren to include document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@rbhanda can you comment?

**Comment by rbhanda** [comment]
I am unable to repro this. I followed the steps on https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804 and I was able to install dotnet sdk 3.1 on wsl.

```
_root@user:/mnt/e/test# sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-runtime-3.1 dotnet-host dotnet-hostfxr-3.1 dotnet-runtime-3.1
The following NEW packages will be installed:
  aspnetcore-runtime-3.1 dotnet-host dotnet-hostfxr-3.1 dotnet-runtime-3.1 dotnet-sdk-3.1
0 upgraded, 5 newly installed, 0 to remove and 28 not upgraded.
Need to get 32.6 kB/70.7 MB of archives.
After this operation, 269 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 dotnet-host amd64 3.1.3-1 [32.6 kB]
Fetched 32.6 kB in 11s (3053 B/s)
Selecting previously unselected package dotnet-host.
(Reading database ... 30488 files and directories currently installed.)
Preparing to unpack .../dotnet-host_3.1.3-1_amd64.deb ...
Unpacking dotnet-host (3.1.3-1) ...
Selecting previously unselected package dotnet-hostfxr-3.1.
Preparing to unpack .../dotnet-hostfxr-3.1_3.1.3-1_amd64.deb ...
Unpacking dotnet-hostfxr-3.1 (3.1.3-1) ...
Selecting previously unselected package dotnet-runtime-3.1.
Preparing to unpack .../dotnet-runtime-3.1_3.1.3-1_amd64.deb ...
Unpacking dotnet-runtime-3.1 (3.1.3-1) ...
Selecting previously unselected package aspnetcore-runtime-3.1.
Preparing to unpack .../aspnetcore-runtime-3.1_3.1.3-1_amd64.deb ...
Unpacking aspnetcore-runtime-3.1 (3.1.3-1) ...
Selecting previously unselected package dotnet-sdk-3.1.
Preparing to unpack .../dotnet-sdk-3.1_3.1.201-1_amd64.deb ...
Unpacking dotnet-sdk-3.1 (3.1.201-1) ...
Setting up dotnet-host (3.1.3-1) ...
Setting up dotnet-hostfxr-3.1 (3.1.3-1) ...
Setting up dotnet-runtime-3.1 (3.1.3-1) ...
Setting up aspnetcore-runtime-3.1 (3.1.3-1) ...
Setting up dotnet-sdk-3.1 (3.1.201-1) ...
This software may collect information about you and your use of the software, and send that to Microsoft.
Please visit http://aka.ms/dotnet-cli-eula for more information.
Welcome to .NET Core!_
```

**Comment by mtttcgcg** [comment]
I am not able to install on WSL, but I get a different error.
When I run:

wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

I get:
packages-microsoft-prod.deb: Permission denied

Even with sudo.

**Comment by Thraka** [comment]
Odd, I installed WSL 2 yesterday and did Ubuntu 1804 and installed without a problem. 😢

**Comment by adegeo** [comment]
I'm going to close this as I can't find a problem to fix.
