### ISSUE TITLE
Update the WinForms porting doc to the latest changes

### ISSUE THREAD

**Issue by OliaG** [dotnet/docs#17694]
We need to update the https://docs.microsoft.com/en-us/dotnet/core/porting/  according to the latest changes that are described here
About try-convert tool:
1.	https://www.codemag.com/Article/1911032/Upgrading-Windows-Desktop-Applications-with-.NET-Core-3
About the latest WinForms Core designer
2.	https://devblogs.microsoft.com/dotnet/updates-on-net-core-windows-forms-designer/

**Comment by gewarren** [comment]
@Thraka I think this is for you.

https://docs.microsoft.com/en-us/dotnet/core/porting/winforms

**Comment by adegeo** [comment]
This was fixed in the desktop repo.
