### ISSUE TITLE
dotnet pack with nuspec/project file

### ISSUE THREAD

**Issue by asklar** [dotnet/docs#17704]
I need to be able to specify which files to include, and I haven't found how to do that with the csproj file, only with the nuspec file. On the other hand, the version number is set dynamically in the csproj file (it includes the date), and the nupkg can't do that. How can I get both behaviors? How do I tell dotnet pack to only include the files I want, through the csproj?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x#feedback)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@wli3 Who can help with this question?

**Comment by wli3** [comment]
@rrelyea and @nkolev92

**Comment by nkolev92** [comment]
There are some examples in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec & https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#advanced-extension-points-to-create-customized-package

**Comment by tdykstra** [comment]
Thanks @nkolev92 -- I'll add these links to the doc.
