### ISSUE TITLE
AspNetCore.Diagnostics.HealthChecks

### ISSUE THREAD

**Issue by landerah** [dotnet/docs#17708]
AspNetCore.Diagnostics.HealthChecks is not (yet?) supported in .NET Core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98bdd99-d89d-8720-9018-25f73dcfdbd8
* Version Independent ID: 61a8ff5d-02ea-ec2b-2624-b8afa66f44d0
* Content: [Health monitoring](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health#feedback)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hey @landerah - Yes, **AspNetCore.Diagnostics.HealthChecks** nuget package is supported in ASP.NET core 3.1. https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks

Was that the question ? Or did you try to mean something else ?

Thanks.

**Comment by sughosneo** [comment]
Hi @landerah closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
