### ISSUE TITLE
Downloadable?

### ISSUE THREAD

**Issue by willWashington** [dotnet/docs#17709]
Do you offer a way to download these keywords in XML/JSON or something like that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9865f7-b92a-c118-c697-9e090132ba51
* Version Independent ID: b454ba01-b5ea-1265-c572-8509458d3bca
* Content: [Statements - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
There isn't an XML or JSON download for statements. There is for PDF.

I'll close as an answered issue.
