### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by jimarledge** [dotnet/docs#17716]
This page is out of date and has nothing about the need to manually edit .json files, etc.  Visual Studio is the best development system on the planet.  

Why not simplify the use of "Code" a little, but at least FFS update the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#feedback)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **tdykstra**

**Comment by JoeRobich** [comment]
> It looks like we no longer load the debugger configuration by default. I believe the extension generated the launch.json automatically before if one was missing. @JoeRobich Did we stop doing that intentionally?

@kendrahavens You may have run into a bug we just fixed where we weren't generating the launch.json file when the project targeted 'net5.0'. Let me know if you were targeting 3.x and I can investigate.

**Comment by kendrahavens** [comment]
@JoeRobich I was indeed targeting 3.1, specifically 3.1.300-preview-015048. I also ran  dotnet new console -f netcoreapp3.0 --force and a launch.json was not created either.

**Comment by tdykstra** [comment]
I wasn't able to repro launch.json not getting created. but I updated the tutorial.
