### ISSUE TITLE
Using Tasks in Web Applications

### ISSUE THREAD

**Issue by ozanyasindogan** [dotnet/docs#17715]
Hello! I recently started to get involved with web application development, Asp.Net Core Razor Pages precisely. I'm a classical desktop application developer and I understand when I should use a new thread separated than the main thread which process window messages (painting, updating gui etc..) I really wonder why in today's web application practices it is often used Tasks and await keyword when actually you can't continue to work until that task completes. As far as I'm aware of IIS handles every request in a separate thread in its thread pool already and this unique client thread is not blocking any message processing when runs a heavy task on its own unlike the desktop apps which actually blocks the message processing. So why are we asking .net to create another thread (task) if all we do is to wait for it to complete? Aren't we consuming unnecessary resources and thread creation - killing time while doing that? Or the compiler just smartly restructures all these on its own? Or IIS is using thread / client sharing.. I really don't understand why otherwise it is necessary. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @scottaddie Is this topic covered in the asp.net core docs? If so, it would make sense for me to add a link here.

**Comment by scottaddie** [comment]
@BillWagner We have an extensive performance overview doc. One section within it that pertains to this discussion is https://docs.microsoft.com/aspnet/core/performance/performance-best-practices#avoid-blocking-calls.

**Comment by ozanyasindogan** [comment]
Thank you gentlemen for your swift response. I read the performance overview and this looks like the answer to me;

> Do not: Call Task.Run and immediately await it. ASP.NET Core already runs app code on normal Thread Pool threads, so calling Task.Run only results in extra unnecessary Thread Pool scheduling. Even if the scheduled code would block a thread, Task.Run does not prevent that.

What I understand from that is;
Basically if I need to read some information from the database and can only process that information in the following statements, I don't need to make an asynchronous call because I would be waiting for it to complete anyway. But if I want to update the database and next statements does not rely on this update's some unpredictable results, I can make an asynchronous update call and should not wait for it to be completed allowing other statements to run.

If my conclusion is true than why Visual Studio generates such code with "Api Controller with actions, using Entity Framework" template?:

`
[HttpGet]
        public async Task<ActionResult<IEnumerable<SiteUser>>> GetSiteUser()
        {
            return await _context.SiteUser.ToListAsync();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<SiteUser>> GetSiteUser(int id)
        {
            var siteUser = await _context.SiteUser.FindAsync(id);

            if (siteUser == null)
            {
                return NotFound();
            }

            return siteUser;
        }`

**Comment by BillWagner** [comment]
First on this issue: This article should link to the section referenced in Scott's comment.

Second, on the question: The paragraph @ozanyasindogan cites uses `Task.Run`. That API offloads work to another thread in the same process. That's why it's not typically recommended for web applications. The later examples you show retrieving information from a database are different: The work done is often performed by another process, or even on another machine. Making that call `async` frees up a thread to respond to requests. In most deployment scenarios, that's preferred. That's why the templates create async methods.

I'll add this to our backlog to update with a link to the referenced article.

**Comment by ozanyasindogan** [comment]
Thank you Bill for the information. Under the light of your recommendations I have read some other articles as well as written for c++ and device drivers programming. I see that async code execution is far more complicated than running a separate thread like I was thinking before. It's handling of I/O completion ports, context switching, interrupt handling, signal / APC synchronising and many other concepts of parallelism applied together with a single keyword. This is the real power of .Net framework over modern operating systems which allows us to use system resources much more efficiently. Now I can follow the instructions in Scott's recommended article without any questions in my mind. Thank you gentlemen.
