### ISSUE TITLE
Add manual entry for `System.Net.WebClient.OnWriteStreamClosed`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#17713]
The base class for `System.Net.WebClient` was sealed in .NET Framework 1.1 (and only that version). As a result, the build system doesn't publish API information for protected APIs. 

To fix this, we need to add a manual entry in the [additional APIs](https://github.com/dotnet/docs/tree/master/docs/framework/additional-apis) folder. The API is obsolete, so this could be a stub.

In addition, we'd want to update the [missing API](https://github.com/dotnet/docs/blob/master/_zip/missingapi.yml) mapping to provide a mapping for this API.

**Comment by gewarren** [comment]
@BillWagner This API is appearing now, probably due to the fix in https://dev.azure.com/ceapex/Engineering/_workitems/edit/271376.

See https://docs.microsoft.com/dotnet/api/system.net.webclient.onwritestreamclosed?view=net-6.0.
