### ISSUE TITLE
Rest of the specification

### ISSUE THREAD

**Issue by eatmorepies-dev** [dotnet/docs#17727]
Where can I find the rest of the specification? I can only find the introduction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction?source=docs#feedback)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@eatmorepies-dev Click on any of the links in the table of contents on the left. Each represents a different chapter of the spec.

I'll close this as an answered question.

**Comment by eatmorepies-dev** [comment]
Thanks. I was viewing the page on portrait mode on a mobile device, so I didn't see it.

I would like to make a suggestion that https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/
send the user to an "In this section" for the specification instead of the introductory page, just as the base language reference page does.

**Comment by BillWagner** [comment]
@eatmorepies-dev We do reference sections in paces, and we're adding more whenever we update articles. As you find more, you can create a new issue or submit a PR to help us in that work. There are a lot of references, and many date from when the spec was a single word doc and a link to the spec was preferred.
