### ISSUE TITLE
Check IoT Core

### ISSUE THREAD

**Issue by druske** [dotnet/docs#17722]
The dotnet command is apparently not present on Windows 10 IoT Core, either through the command line or Powershell. It would be helpful to either provide some guidance as to how to check the installed .NET Core version on IoT Core, or provide a link to such information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2842ce-ee53-ec35-90c6-791a952dfc3b
* Version Independent ID: 79ec96d5-9c2c-1eaa-feb8-40b0afee6a30
* Content: [Check installed .NET Core versions on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows)
* Content Source: [docs/core/install/how-to-detect-installed-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/install/how-to-detect-installed-versions.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
yes, I think adding some info about what folders would commonly be found if you were trying to determine if it was installed. Thanks for the suggestion.
