### ISSUE TITLE
Can't download as a a PDF

### ISSUE THREAD

**Issue by eatmorepies-dev** [dotnet/docs#17728]
The Android versions of Adobe Acrobat and even Microsoft Word are throwing errors about it being an unsupported file format.

What is the recommended way to access the PDF of the language spec on a mobile device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @dend

**Comment by herohua** [comment]
+ @cillroy
