### ISSUE TITLE
Multitargeting topic should include guidance on testing and debugging against a specific target

### ISSUE THREAD

**Issue by bleroy** [dotnet/docs#1772]
The [multitargeting topic](https://docs.microsoft.com/en-us/dotnet/articles/core/porting/project-structure) currently has no information on how to debug or test against a specific target. While the Visual Studio support for the feature doesn't exist yet, it would still be good to explain what the behavior in VS is (the first specified TFM is picked for F5 and testing). The topic should be expanded to explain how to target a specific TFM from the command-line. The debugging story in VS Code should also be clarified.

@mairaw @wadepickett

**Comment by mairaw** [comment]
@morrisjoe are you the right person for us to determine how this works in VS so we can start this task?

**Comment by morrisjoe** [comment]
@mairaw Yes, I can help. But I would be leaning on the feature team who owns these technologies (which is the engineering team in India, whose PM is Pratap Lakshman <pratapl@microsoft.com>

**Comment by IEvangelist** [comment]
Closing this as well
