### ISSUE TITLE
how types (classes) can be protected?

### ISSUE THREAD

**Issue by harpalsingh1993** [dotnet/docs#17720]
> protected: The type or member can be accessed only by code in the same class, or in a class that is derived from that class.

I am just confused about these statements, how a type can be protected, only members can be protected. can you please correct me if I am wrong. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@harpalsingh1993 A nested class can be declared `protected`. This is covered in detail in the language reference and specification.

It's not a common scenario, so it's not covered in detail in the programming guide. It is allowed, so we won't change the language here.

I'll close this as an answered question.
