### ISSUE TITLE
2019 WPF Tutorial not documented properly

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#17726]
_From @squin on Monday, February 3, 2020 12:12:17 PM_

There is what looks like a useful tutorial called "Create your first WPF application in Visual Studio 2019". Having worked down through this tutorial I got about halfway down where the users were added in a list, the title is "Add Controls". Scroll down to the next section "Add an image and a title" and the whole section is changed. There are "<Grid.Resources>" added and the names section completely re-worked with no comment as to why. I gave up on using it at this point, what a pity!

_Copied from original issue: MicrosoftDocs/feedback#2469_

**Comment by gewarren** [comment]
_From @welcome[bot] on Monday, February 3, 2020 12:12:18 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
_From @docs-product on Wednesday, February 5, 2020 12:54:51 AM_

@squin - could you please provide a link to the article in question?

**Comment by gewarren** [comment]
_From @squin on Wednesday, February 5, 2020 10:55:53 AM_

https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application

Regards.....

**Comment by gewarren** [comment]
_From @gewarren on Thursday, March 26, 2020 11:05:51 PM_

@thraka FYI

**Comment by gewarren** [comment]
_From @mairaw on Friday, April 3, 2020 8:43:44 AM_

@gewarren should this be transferred to the dotnet/docs repo instead?

**Comment by gewarren** [comment]
_From @Thraka on Friday, April 3, 2020 4:25:34 PM_

@mairaw Sure!

**Comment by Thraka** [comment]
@squin I've identified the problem. I think the snippet included was too expressive and pulled from a later portion of the article. It should be an easy fix.
