### ISSUE TITLE
Remove redirected files from repo

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1773]
We have some topics in the repo that are no longer applicable. Instead of keeping them in the repo, the redirection metadata should be moved to the [.openpublishing.redirection.json](https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json) file and the files deleted.

**Comment by tompratt-AQ** [comment]
@mairaw I can take this one on. 
From what I can see, all of the redirected files have a "redirect_url:" in their metadata (and usually no other content beyond the metadata). I can make the appropriate entries in .openpublishing.redirection.json and delete the files.

**Comment by mairaw** [comment]
Thanks @tompratt-AQ. I've assigned this one to you.

**Comment by mairaw** [comment]
@tompratt-AQ let us know when you can work on this.

**Comment by tompratt-AQ** [comment]
This issue was closed last week by PR #1890 (I made the new PR to replace PR#1790 that is referenced above). The old PR had gotten out of date and it was just easier to make a new one.

**Comment by BillWagner** [comment]
Closing. Fixed in #1890
