### ISSUE TITLE
Mystery server?

### ISSUE THREAD

**Issue by sotomo** [dotnet/docs#17737]
Is "http://localhost:15839/wsFederationSTS/Issue" an ADFS server running on the local machine?  No way of knowing since it's just parts of the config, no explanation given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 727349dd-9a84-1ac7-a808-2c6b334162cb
* Version Independent ID: 49464913-6fdc-306d-5208-11371b0b5b24
* Content: [&lt;federationConfiguration&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/federationconfiguration#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/windows-identity-foundation/federationconfiguration.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/windows-identity-foundation/federationconfiguration.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello. That snippet is just a sample of that parent node, if you go into the [docs for `<wsFederation>`](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/wsfederation#attributes) you get more information:

>**Issuer**\
The URI of the intended token issuer. Sets the base URL of WS-Federation sign-in requests and sign-out requests Required.

So you could use ADFS as that I'm sure.

I think that answers your question, I'll close this issue.

Cheers
