### ISSUE TITLE
Example Link is broken

### ISSUE THREAD

**Issue by madhub** [dotnet/docs#17740]
Example Link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4a1a18-d470-6a2e-30d3-8f89a82aaaf8
* Version Independent ID: f1e8d3e4-e92e-f8e4-85fd-666101347b2f
* Content: [How to: Inspect assembly contents using MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext#feedback)
* Content Source: [docs/standard/assembly/inspect-contents-using-metadataloadcontext.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/inspect-contents-using-metadataloadcontext.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @MSDN-WhiteKnight
* Microsoft Alias: **gewarren**

**Comment by MSDN-WhiteKnight** [comment]
Yeah, for some reason new added .NET samples weren't pulled to sample browser. I've filed the related Docs site bug recently: https://github.com/MicrosoftDocs/feedback/issues/2595 This is probably the same issue; the sample is merged into live branch, but not available on site both by direct URL and by searching keywords in sample browser. FYI, the Github link for this sample is https://github.com/dotnet/samples/tree/master/core/assembly/MetadataLoadContext

//cc @gewarren @BillWagner
