### ISSUE TITLE
Avoid generating documentation for private and internal members

### ISSUE THREAD

**Issue by arivoir** [dotnet/docs#17742]
Is there any way to avoid generating the documentation of the private and internal members?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc?source=docs#feedback)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@arivoir I don't think so. You can choose not to document them, it won't affect anything. If your generating a website using at tool tool of some sort, you'll want to consult their guidance on the matter. I'm going to close this question. Thanks for opening it, cheers!

**Comment by arivoir** [comment]
It's a pity. The internal and private comments are added for the sake of clarity and well documented code, but we don't want them to be translated(We offer localized intelli-sense), so it would be desired those comments not to be generated. It would be a good feature to add. I've seen people requesting it in other places.
