### ISSUE TITLE
Package support information seems outdated

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/docs#17754]
The documentation reads :
&gt; .NET Core 2.0, 2.1, and 2.2
While, in my opinion, it should be
&gt; .NET Core 2.0 and later versions

Or is there a specific reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#jsondocument-and-jsonelement-compared-to-jtoken-like-jobject-jarray)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@jeremyVignelles That refers to the NuGet package. For 3.0 and later System.Text.Json is included in the runtime, so the NuGet package is not used.
