### ISSUE TITLE
Edit for confusion 

### ISSUE THREAD

**Issue by jonab12** [dotnet/docs#17764]
On the line:

"protected: The type or member can be accessed only by code in the same class, or in a class that is derived from that class".

Please amend to:

"protected: The type or member can be accessed only by code in the same class, or in a class that is derived from that class for the current assembly".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jonab12 I'm going to close this. The suggested change is incorrect. It describes the `private protected` access, not `protected` access. The current text is correct.
