### ISSUE TITLE
Event handlers are corrupted in memory.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17761]
@nathan130200 commented on [Tue Apr 07 2020](https://github.com/dotnet/docs.de-de/issues/179)

When i declare:

`public Action MyEvent;` first time i add an handler to event, works fine, the second and other handles that i try to add, corrupt event handler, and i cannot raise and manage this event. In debugger displays "Failed to ready memory" when i point cursor over event. An workaround i created List of event handlers manually to handle that. I need manually add EventHandlerList each event by key? Or is supposed to compile automatically generate protected field with EventHandlerList and add/remove in this?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: caf84f7a-743b-867a-2ac5-2ab815f10c45
* Version Independent ID: 9b1d1a8a-5151-8e4d-2365-7c859e1bacd8
* Content: [Manipulando e acionando eventos](https://docs.microsoft.com/pt-br/dotnet/standard/events/#feedback)
* Content Source: [docs/standard/events/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/events/index.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---

@srvbpigh commented on [Tue Apr 07 2020](https://github.com/dotnet/docs.de-de/issues/179#issuecomment-610675548)

Hello, @nathan130200
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@nathan130200 commented on [Tue Apr 07 2020](https://github.com/dotnet/docs.de-de/issues/179#issuecomment-610682949)

Note: i'm using .net core 3.1

```log
SDK do .NET Core (refletindo qualquer global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I created an example code to demostrat the problem:
```cs
using System;
using System.Diagnostics;

namespace EventHandlerCorruption
{
	static class Program
	{
		static void Main(string[] args)
		{
			var example = new ExampleEventClass();
			
			example.AddFirstHandler();
			Debugger.Break();

			example.AddMoreHandlers();
			Debugger.Break();
		}
	}

	public class ExampleEventClass
	{
		public event Action MyEvent;

		public ExampleEventClass()
		{

		}

		public void AddFirstHandler()
		{
			this.MyEvent += this.ExampleEventClass_MyEvent;
		}

		public void AddMoreHandlers()
		{
			this.MyEvent += this.ExampleEventClass_MyEvent1;
			this.MyEvent += this.ExampleEventClass_MyEvent2;
			this.MyEvent += this.ExampleEventClass_MyEvent3;

		}

		private void ExampleEventClass_MyEvent()
		{

		}

		private void ExampleEventClass_MyEvent1()
		{

		}

		private void ExampleEventClass_MyEvent2()
		{

		}

		private void ExampleEventClass_MyEvent3()
		{

		}
	}
}

```

First `Debugger.Break` all fine (Watch window in VS 2019):
![image](https://user-images.githubusercontent.com/14365254/78731095-1746a000-7915-11ea-9aeb-e00149be6bab.png)

Second `Debugger.Break` got problem (i added more handlers to `MyEvent` event):
![image](https://user-images.githubusercontent.com/14365254/78731143-38a78c00-7915-11ea-9121-94f2cdbd890f.png)

Now i cannot fire this event anymore.

**Comment by Thraka** [comment]
This is an error in the Visual Studio watch/debugger.

01. The code works, if you add a method in your class to trigger the event, all four methods are triggered:
    ```csharp
    public void TriggerEvent() => MyEvent?.Invoke();
    ```

01. If you use VSCode you can add it to the watch and it doesn't get corrupted and you can debug it.

This makes me think it's a **bug in Visual Studio**. I would file a feedback item with them

![image](https://user-images.githubusercontent.com/2672110/78910664-24a97a80-7a3a-11ea-9b5c-0a7c88423224.png)
