### ISSUE TITLE
Suggestions for "Build your first analyzer and code fix" tutorial

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#17779]
1. In [this section](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#find-local-declarations-that-could-be-const), this sentence has an extra "of" word:

> A [Microsoft.CodeAnalysis.SemanticModel](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.semanticmodel) represents ~~of~~ all semantic information in a single source file.

2. I think the code examples should declare variables with the explicit type instead of `var` (basically, apply `IDE10008`. It would make it easier to understand what a method is returning, instead of having to guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#find-local-declarations-that-could-be-const)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @carlossanlop 

I'll address it when I next update this article.

**Comment by Youssef1313** [comment]
@carlossanlop I have addressed this while updating the article and the sample. The only occurrences that I left using `var` are existing from the template :(

The template in roslyn-sdk repository will need this to get updated first.

**Comment by BillWagner** [comment]
Fixed in #23066
