### ISSUE TITLE
UInt32 is missing

### ISSUE THREAD

**Issue by tzehetner** [dotnet/docs#17784]
The type mapping for UInt32 is missing in the type table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d377275c-52cb-2aec-79a1-a627b4ce539f
* Version Independent ID: 4532a56f-717d-1c0e-c3a4-1417e71f5630
* Content: [Data types - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/types#feedback)
* Content Source: [docs/standard/data/sqlite/types.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/sqlite/types.md)
* Product: **dotnet**
* Technology: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by Thraka** [comment]
According to the link at the bottom (https://www.sqlite.org/datatype3.html) it says that the `INTEGER` type in SQLite is **signed**. It wouldn't make sense to list the **unsigned** variants.

**Comment by tzehetner** [comment]
It makes sense to list the unsigned .NET types, even if SQLite stores only signed integers. ;)

The documentation page says, that .NET types UInt16 and UInt64 are mapped to SQLite type INTEGER. UInt32 is missing, which is also mapped to INTEGER.

**Comment by bricelam** [comment]
It is missing. I'll add it.

**Comment by bricelam** [comment]
@Thraka An unsigned 32-bit integer fits just fine into SQLite's 64-bit integer type

**Comment by tzehetner** [comment]
@bricelam Thanks!

**Comment by Thraka** [comment]
@tzehetner @bricelam HA! sorry about that. I think my brain just saw the three Int* items and thought you were referring to that. Thank's for following up!
