### ISSUE TITLE
Guidelines on which are infrastructure framework not to be referenced in Domain Models 

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#17783]
Since there are increasing number of framework packages and increasing dependency on these packages to speed up application development, which packages are considered infrastructure and which are considered acceptable to be referenced in Domain Models class library project? The discussion here only limits to ORM and data persistence. It would be good to provide a scope and/or general guidelines and/or best practices on this topic to understand what packages are off-limits to the Domain Models class library projects. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c9fdb0-f078-2030-204d-67d016b22c8d
* Version Independent ID: 43bd7af4-f92e-f866-6725-b3c1b4e6afdb
* Content: [Implementing a microservice domain model with .NET Core](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @khteh, thank you for reaching out.

Your persistance data store may get changed based on the requirement you have. If you are following microservices pattern then it may also be different from one another.
But for ORM you could use Entity Framework Core which has many supported providers already. Here is the list of [Database Providers](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli) for your reference. Along with that you can also use "Repository" pattern in your project to avoid direct dependencies on the data store.  

Hope this helps !

**Comment by sughosneo** [comment]
Hi @khteh, we are closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
