### ISSUE TITLE
Step 5: decimal type and PI

### ISSUE THREAD

**Issue by wofguy** [dotnet/docs#17788]
The challenge asks you to find the area of a circle and recommends using Math.PI. Since it just covered the decimal data type, I instinctively tried to use those in the equation. However, Math.PI is a double and can't innately be used with the decimal data type. I think that this needs to be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @wofguy 
Yes, that should be specified.  I've added it to our next sprint to address.
