### ISSUE TITLE
80/5000 Matrix [10] contains 11 elements instead of 10 as stated in the explanation above

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17793]
The comments below were machine-translated
@NiceShot commented on [Fri Apr 10 2020](https://github.com/dotnet/docs.de-de/issues/184)

An array actually stores in memory since [0]. In the example above, the array with the value of [10] reserves 11 elements in memory.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 64f269de-137f-a763-a4e2-f2f5b1ce9dd3
* Version Independent ID: ad83c8b9-a95a-e336-ff31-52fb1fdb4b14
* Content: [Matrizes em C# - um tour pela linguagem C#](https://docs.microsoft.com/pt-br/dotnet/csharp/tour-of-csharp/arrays#feedback)
* Content Source: [docs/csharp/tour-of-csharp/arrays.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/tour-of-csharp/arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Fri Apr 10 2020](https://github.com/dotnet/docs.de-de/issues/184#issuecomment-611880912)

Hello, @NiceShot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
@CeciAc I'm closing this because the content is correct. A declaration of `array[10]` declares an array with 10 elements. They are indexed with 0..9. In other words, the largest valid index is one less than the length of the array.
