### ISSUE TITLE
Document the <PublishDir> property

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#17795]
See https://github.com/dotnet/sdk/issues/9012#issuecomment-358496376.

A search showed that two issues that mentioned this have been closed.

https://github.com/dotnet/docs/issues?q=is%3Aissue+publishdir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@NextTurn The `dotnet publish` CLI ref article already mentions `-p:PublishDir` as an alternative to `--output`. What more do you think needs to be said?

**Comment by NextTurn** [comment]
@tdystra AFAIK this property is not specific to .NET Core 3.x SDK and later. But I'm fine with it if you think it's good enough.

**Comment by tdykstra** [comment]
@livarcocc Per your comment about improving the documentation in https://github.com/dotnet/sdk/issues/9012#issuecomment-358496376 should we say anything additional about the `PublishDir` property in the `dotnet publish` article beyond what we added for https://github.com/dotnet/docs/issues/12486, i.e., a note about differences between `--output` and `-p:PublishDir` in 3.x.

**Comment by NextTurn** [comment]
At least it has been there since .NET Core 2.0 according to dotnet/sdk#9012.

**Comment by tdykstra** [comment]
@sfoslund This issue wasn't attached to the `dotnet publish` article when you reviewed the doc for #15519.  Should we say anything about the `PublishDir` property in the `dotnet publish` article other than the note about differences between `--output` and `-p:PublishDir` in 3.x?

**Comment by sfoslund** [comment]
@tdykstra I think what's there already is sufficient. Not sure what else we would add unless we want to explicitly call `PublishDir` out as a relevant property (similar to what we do for `PublishReadyToRun` and `PublishSingleFile`, listing them as options). Again, not sure this will add any clarity so might not be necessary. 

Also, so you're aware Livar (livarcocc) left the team several months ago.

**Comment by tdykstra** [comment]
Thanks, @sfoslund !
