### ISSUE TITLE
Escaping <>

### ISSUE THREAD

**Issue by jo3w4rd** [dotnet/docs#17796]
You really should discuss all the ways that &lt;&gt;'s need to be escaped in various situations. For example, in crefs, in normal comment text, in &lt;code&gt; and &lt;c&gt; elements, etc. You examples all conveniently sidestep this constant irritant. The move to DocFX adds additional complexity since it allows markdown in comments, and markdown has its own, often conflicting escaping rules for &lt;&gt;'s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f92e76-2785-188b-6046-ec741144fcd0
* Version Independent ID: 8708e9f1-a45f-4106-6ba2-bf2e56f76aab
* Content: [&lt;example&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/example#feedback)
* Content Source: [docs/csharp/programming-guide/xmldoc/example.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/example.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @jo3w4rd 

I think this entire section will need to be updated. It was written for different tools than are typically used today.
