### ISSUE TITLE
Finalizers

### ISSUE THREAD

**Issue by allanvas** [dotnet/docs#17798]
In the following text, the word Finalizers should be changed as shown:
Finalizers
Finalizers are used to destruct instances of classes. In the .NET Framework, the garbage collector automatically manages the allocation and release of memory for the managed objects in your application. However, you may still need finalizers to clean up any unmanaged resources that your application creates. There can be only one finalizers for a class.

Instance 1 -- no change
Instance 2 -- "Finalizers are" to "A finalizer is" 
instance 3 -- no change
instance 4 -- "finalizers" to "finalizer" 

As a consequence, the corrected text will read as follows:

Finalizers
A finalizer is used to destruct instances of classes. In the .NET Framework, the garbage collector automatically manages the allocation and release of memory for the managed objects in your application. However, you may still need finalizers to clean up any unmanaged resources that your application creates. There can be only one finalizer for a class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/object-oriented-programming#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/object-oriented-programming.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @allanvas The suggested wording would be better.

I've added this to our backlog, and added the "up for grabs" and "good first issue" labels if any community member wants to address this before we update it.
