### ISSUE TITLE
pointless complexity

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#17799]
in the ComputeArea_Version3 .. ComputeArea_Version5 examples it is completely unnecessary to make all the special cases rather than just let the simple multiplications happen (which will return 0 anyway). Would be better if you could find a more interesting [if slightly more complex] case with a different outcome.
Please don't try to justify by performance (uSec) considerations, when the developer brain-cycles run to secs/minutes to understand all the artificial special cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @DickBaker 

I am always thinking about better examples that demonstrate features. I'll add this to our backlog to continue thinking on this one.

**Comment by BillWagner** [comment]
This sample was redone. Closing.
