### ISSUE TITLE
Parse

### ISSUE THREAD

**Issue by eatmorepies-dev** [dotnet/docs#17804]
Why isn't Parse and TryParse mentioned here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f6afe5-2dd3-b300-c755-d7776e6240be
* Version Independent ID: e0d5233a-c5ac-c9d7-965b-26f3b162775c
* Content: [Type Conversion in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/standard/base-types/type-conversion#feedback)
* Content Source: [docs/standard/base-types/type-conversion.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/type-conversion.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hi @eatmorepies-dev 

I don't think `Parse` and `TryParse` really fit here. That's not really converting one type to another. It's interpreting a string to generate a type. However, it's covered in the [Parse strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-numeric) area.

I'm going to closet his issue, please feel free to follow up.
