### ISSUE TITLE
Don't be specific about VS Code

### ISSUE THREAD

**Issue by 333fred** [dotnet/docs#17807]
This can be used for either VS or VS Code, we shouldn't be specific here. I'd guess there are other locations as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c53405a4-8bde-8e99-db91-75f4b76ab6eb
* Version Independent ID: acba9d21-cfb1-29da-bcce-58155f707396
* Content: [#region - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region#feedback)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-region.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-region.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I believe the article is actually talking about the Code Editor of Visual Studio, notice that the "outlining" link goes to VS-specific documentation. Though it's definitely confusing as it is now and should be rewritten.

**Comment by BillWagner** [comment]
Good points.

I suggest replacing "Visual Studio Code Editor" with "code editor".

I've added the up for grabs and good first issue label to this issue.
