### ISSUE TITLE
How "thread-safe" ?

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#17806]
This is just a request for clarification.  When the comment in the example says, "Raise the event in a thread-safe manner using the ?. operator." what exactly does "thread-safe" mean in this situation?  (I don't want to assume the C# language is taking care of every detail.)  For instance, if a subscriber of an event unsubscribes, is it guaranteed that the event will never be raised again?

Or could there be a race between the subscriber's event handler running and an unsubscribe operation finishing?  In other words, is this possible:

Publisher reads event delegate.
Subscriber unsubscribes from event delegate.
Subscriber exits, shuts down, is disposed, etc.
Publisher raises subscriber's event, which causes unpredictable behavior.

Would the subscriber need its own internal flag (that it accesses using some interlocked mechanism) to prevent its event handler from doing anything after the unsubscribe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f782a9c5-2dc8-d8d1-b17d-246ab8524863
* Version Independent ID: f6f825c5-c64b-d13b-1c7e-a01bfb93093d
* Content: [event - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event)
* Content Source: [docs/csharp/language-reference/keywords/event.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/event.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@matthew45052 That's a great question. Of the scenarios you point out, the only one that is possible is the disposed scenario. The `?.` syntax guarantees that the subscriber list is evaluated exactly once. That means if a subscriber is present when the subscriber list is checked against null, that subscriber list is not null when the event is raised.

A well-written subscriber would be safe: the unsubscribe code won't execute until the event has been raised and handled. However, a subscriber that could be disposed before unsubscribing would have a potential issue.

I'll close this as an answered question.
