### ISSUE TITLE
Inaccurate statement about installation directory

### ISSUE THREAD

**Issue by ToMakeSense** [dotnet/docs#17812]
> This tool is automatically installed with Visual Studio. By default, the file is located at drive:\Program Files\Microsoft SDKs\Windows\vn.nn\bin

The statement above is inaccurate.  **TLDR**, Visual studio is an 32-bit application, the installation directory depends on the bits of Windows system. if it's installed on 64-bit version of Windows. it's **drive:\Program Files (x86)**, if on a 32-bit version of Windows. it's **drive:\Program File**

On a 32-bit version of Windows, you just have a “C:\Program Files” folder. This contains all your installed programs, all of which are 32-bit. On a 64-bit version of Windows, 64-bit programs are stored in the “C:\Program Files” folder and 32-bit programs are stored in the “C:\Program Files (x86)” folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99913132-5ffb-14ac-8f7e-d12d0ac2fca2
* Version Independent ID: 62937617-3e72-4563-c615-30a782a113c2
* Content: [SqlMetal.exe (Code Generation Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sqlmetal-exe-code-generation-tool)
* Content Source: [docs/framework/tools/sqlmetal-exe-code-generation-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sqlmetal-exe-code-generation-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@ToMakeSense Thanks for pointing that out.  We'll fix it the next time we update this article.
