### ISSUE TITLE
Consumed vs. Observed vs. Unobserved in PipeReader.AdvanceTo 

### ISSUE THREAD

**Issue by aalmada** [dotnet/docs#17822]
I think in the following sentence from the PipeReader section,  the portion after the comma should be negated:

"Any other value will make the next call to PipeReader.ReadAsync return immediately with the observed and unobserved data, but data that has already been consumed."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5384a7-5e96-d977-7748-317a2c758f63
* Version Independent ID: 06e72212-a052-a351-0e0b-1b002ce214de
* Content: [I/O pipelines - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines#feedback)
* Content Source: [docs/standard/io/pipelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/pipelines.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gewarren** [comment]
"but **not** data that has already been consumed"? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@gewarren  I think you're correct. Do you want to PR this?
