### ISSUE TITLE
Sse/Sse2 CompareGreaterThan intrinsics behavior changed for .NET 5

### ISSUE THREAD

**Issue by tannergooding** [dotnet/docs#17838]
## Sse/Sse2 CompareGreaterThan intrinsics behavior changed for .NET 5

The following methods have been fixed to properly handle `NaN` inputs and match the hardware behavior of equivalent functions exposed in `Avx`:
* `CompareGreaterThan`
* `CompareGreaterThanOrEqual`
* `CompareNotGreaterThan`
* `CompareNotGreaterThanOrEqual`
* `CompareScalarGreaterThan`
* `CompareScalarGreaterThanOrEqual`
* `CompareScalarNotGreaterThan`
* `CompareScalarNotGreaterThanOrEqual`

### Version introduced

.NET 5

### Old behavior

For NaN inputs the above methods would return an incorrect result and differ in result from the corresponding method on the `Avx` class.

### New behavior

The above methods will now correctly handle NaN inputs and will return the same result as the corresponding method on the `Avx` class.

### Reason for change

The Sse/Sse2 ISAs do not provide direct hardware support for these methods and instead they are handled in software for convenience. However, the methods were being improperly handled and as such would not handle NaN inputs correctly. As an example, for regular integers you can implement `CompareNotGreaterThan(x, y)` as `CompareLessThanOrEqual(x, y)`, however once `NaN` becomes a consideration this will compute the wrong result. Instead, you have to use `CompareNotLessThan(y, x)` so that it still does the correct comparison and takes NaN inputs into consideration.

This incorrect behavior has the chance of introducing bugs for code ported from native and may result in a difference of behavior if using the equivalent methods on the `Avx` class for a 256-bit code path.

### Recommended action

Determine if the previous behavior was desired or a bug. If the previous behavior was a bug no change is required. If the previous behavior was desired, the relevant invocation can be changed as follows to maintain the .NET Core 3.1 behavior:
* `CompareGreaterThan(x, y)` -> `CompareNotLessThanOrEqual(x, y)`
* `CompareGreaterThanOrEqual(x, y)` -> `CompareNotLessThan(x, y)`
* `CompareNotGreaterThan(x, y)` -> `CompareLessThanOrEqual(x, y)`
* `CompareNotGreaterThanOrEqual(x, y)` -> `CompareLessThan(x, y)`
* `CompareScalarGreaterThan(x, y)` -> `CompareScalarNotLessThanOrEqual(x, y)`
* `CompareScalarGreaterThanOrEqual(x, y)` -> `CompareScalarNotLessThan(x, y)`
* `CompareScalarNotGreaterThan(x, y)` -> `CompareScalarLessThanorEqual(x, y)`
* `CompareScalarNotGreaterThanOrEqual(x, y)` -> `CompareScalarLessThan(x, y)`

### Category

CoreFx

### Affected APIs

[Sse.CompareGreaterThan(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparegreaterthan?view=net-5.0)
[Sse.CompareGreaterThanOrEqual(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparegreaterthanorequal?view=net-5.0)
[Sse.CompareNotGreaterThan(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparenotgreaterthan?view=net-5.0)
[Sse.CompareNotGreaterThanOrEqual(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparenotgreaterthanorequal?view=net-5.0)
[Sse.CompareScalarGreaterThan(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparescalargreaterthan?view=net-5.0)
[Sse.CompareScalarGreaterThanOrEqual(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparescalargreaterthanorequal?view=net-5.0)
[Sse.CompareScalarNotGreaterThan(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparescalarnotgreaterthan?view=net-5.0)
[Sse.CompareScalarNotGreaterThanOrEqual(Vector128<Single>, Vector128<Single>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse.comparescalarnotgreaterthanorequal?view=net-5.0)

[Sse2.CompareGreaterThan(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparegreaterthan?view=net-5.0#System_Runtime_Intrinsics_X86_Sse2_CompareGreaterThan_System_Runtime_Intrinsics_Vector128_System_Double__System_Runtime_Intrinsics_Vector128_System_Double__)
[Sse2.CompareGreaterThanOrEqual(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparegreaterthanorequal?view=net-5.0)
[Sse2.CompareNotGreaterThan(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparenotgreaterthan?view=net-5.0)
[Sse2.CompareNotGreaterThanOrEqual(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparenotgreaterthanorequal?view=net-5.0)
[Sse2.CompareScalarGreaterThan(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparescalargreaterthan?view=net-5.0)
[Sse2.CompareScalarGreaterThanOrEqual(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparescalargreaterthanorequal?view=net-5.0)
[Sse2.CompareScalarNotGreaterThan(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparescalarnotgreaterthan?view=net-5.0)
[Sse2.CompareScalarNotGreaterThanOrEqual(Vector128<Double>, Vector128<Double>)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse2.comparescalarnotgreaterthanorequal?view=net-5.0)

#### Issue metadata

* Issue type: breaking-change

**Comment by tannergooding** [comment]
This will become relevant once https://github.com/dotnet/runtime/pull/34204 is merged

**Comment by gewarren** [comment]
@tannergooding Which preview is this going out in?

**Comment by tannergooding** [comment]
It is in for preview 4

**Comment by gewarren** [comment]
@tannergooding Do the API docs for those methods need to add a note to say that the behavior has changed?

**Comment by tannergooding** [comment]
Yes, that would probably be worthwhile. I'll see about getting a PR up that adds one.

**Comment by gewarren** [comment]
@tannergooding One more question, is it all the overloads of the Sse2 methods, or just the ones that accept `Vector128<Double>`?

**Comment by tannergooding** [comment]
Just the methods that take `float` (SSE) or `double` (SSE2)
