### ISSUE TITLE
Serializable attribute seems optional

### ISSUE THREAD

**Issue by zerocoins** [dotnet/docs#17832]
"An exception is thrown if you attempt to serialize but the type doesn't have the SerializableAttribute attribute"
I just created a simple example to test xml serialization and it all went well without exception being thrown, although I didn't mark my test class with Serializable attribute. It appears that it is optional, not mandatory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd80e70-d456-580a-86c0-451f933cc066
* Version Independent ID: 53894d4f-36fd-9b68-99fe-cfdbb7759beb
* Content: [Serialization (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/serialization/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by zerocoins** [comment]
Also it appears that xml serializer ignores NonSerialized attribute and it expects XmlIgnore.

**Comment by BillWagner** [comment]
Thanks for writing these up @zerocoins 
This article should be updated to improve the distinctions between XML and binary serialization. 

I've added this it to our backlog to update when we next update this area.
