### ISSUE TITLE
cannot refer to class's member with cref

### ISSUE THREAD

**Issue by binhnguyen1984** [dotnet/docs#17833]
I have a class with a class's property named X. I want to inherit this property's documentation in a constructor's parameter, but it does not work. This case-study was not shown in this website.

**Comment by BillWagner** [comment]
Thanks for the question @binhnguyen1984 

Have you checked [here](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/cref-attribute)? That shows several examples of `cref`, including some for properties.

**Comment by binhnguyen1984** [comment]
@BillWagner I have seen that one. But the cref refers to the whole method. There is also no param tag as in my case. I have checked inheritdoc with cref when using outside of param tag. It works fine. But whenever I put it inside the param tag to document the parameter, it shows nothing.

**Comment by Thraka** [comment]
I'm pretty sure that inheritdoc is for the whole member, meaning, you want to just use their description of the entire member or thing, not a particular piece of the member. You can't inject another member's documentation inline with yours, you have to supply all of the documentation for the member. If you want to inherit the documentation of the base class for the *same* member, that is what `inheritdoc` is for, but you have to use it for the entire member.

```csharp
public class Person : Thing
{
    /// <summary>
    /// full description
    /// </summary>
    /// <param name="firstName">full description</param>
    /// <param name="lastName">full description</param>
    public Person(string firstName, string lastName): base(firstName, lastName) { }
}
```

Or

```csharp
public class Person : Thing
{
    /// <inheritdoc/>
    public Person(string firstName, string lastName): base(firstName, lastName) { }
}
```
