### ISSUE TITLE
Typo with --interactive in Synopsis?

### ISSUE THREAD

**Issue by bitobrian** [dotnet/docs#17840]
[Synopsis](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore#synopsis) shows `-interactive` instead of `--interactive`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198e4c22-ac0b-61de-3ae1-221a73957843
* Version Independent ID: 0873ec7c-9134-138c-97dd-ef96ca31ef23
* Content: [dotnet tool restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore#feedback)
* Content Source: [docs/core/tools/dotnet-tool-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that!
