### ISSUE TITLE
Not able to install dotnet-sdk-3.1

### ISSUE THREAD

**Issue by shivanshi18** [dotnet/docs#17849]
When I try to run the command apt-get install dotnet-sdk-3.1

I am getting the error : 
E: Unable to locate package dotnet-sdk-3.1
E: Couldn't find any package by glob 'dotnet-sdk-3.1'
E: Couldn't find any package by regex 'dotnet-sdk-3.1'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9f32d7f-c8f4-b900-4c5d-ea736709dd2e
* Version Independent ID: 5c5ddf0e-0c21-2392-0245-0eb823f36fc2
* Content: [Install .NET Core on Debian 10 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian10)
* Content Source: [docs/core/install/linux-package-manager-debian10.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-debian10.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@shivanshi18 did you register the feed and key as the article says to do? I'm not sure how you validate that it was successful registering it.

**Comment by shivanshi18** [comment]
Yes, I registered the feed as they were suggesting.

**Comment by shivanshi18** [comment]
There was some issue with sudo command for me. I installed sudo again on debian, executed commands again and the issue got resolved.

**Comment by Thraka** [comment]
Ok. I'll close this issue then.
