### ISSUE TITLE
No code snippet

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17845]
Hi team, 
this is reported in the zh-cn page but I checked it replicates in the other locales too, 
It looks like an issue with the code boxes which get corrupted when translated

the comments below were machine-translated

@zyd2001 commented on [Tue Apr 14 2020](https://github.com/dotnet/docs.de-de/issues/189)

All code snippets on this page are not displayed

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using 语句 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Tue Apr 14 2020](https://github.com/dotnet/docs.de-de/issues/189#issuecomment-613652376)

Hello, @zyd2001
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
@LadyNaggaga @dend Can you investigate?

**Comment by JasonCard** [comment]
@DavidPrio @CeciAc please help to follow up on this issue.

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zyd2001
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/using-statement#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
