### ISSUE TITLE
ProcessNameFormat should get value 2 when process ID is requested

### ISSUE THREAD

**Issue by eremmel** [dotnet/docs#17858]
In this article the value of 1 is used to change the naming schema from myapp#NN to myapp_PPPPP. But the value should be 2. The value 1 is the same as not having the value ProcessNameFormat in your registry.
I tested this with W10 64-bit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d7e7169-1d20-ca2a-1693-80dd82133f8f
* Version Independent ID: d5631331-f903-6989-643e-08bd9494772e
* Content: [Performance Counters and In-Process Side-By-Side Applications](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/performance-counters-and-in-process-side-by-side-applications#feedback)
* Content Source: [docs/framework/debug-trace-profile/performance-counters-and-in-process-side-by-side-applications.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/performance-counters-and-in-process-side-by-side-applications.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by gewarren** [comment]
It would be good to verify if this is an intentional change with someone on the product team. @anipik Would that be you?

**Comment by gewarren** [comment]
@sywhang Are you familiar with the `ProcessNameFormat` registry value?

**Comment by eremmel** [comment]
I just did a quick test to help you out (W10, x64).
I added my registry, started Performance Monitor and select adding Processes. This are the two screenshots that hopefully prove it for you:
![ProcessNameFormat=1](https://user-images.githubusercontent.com/1874108/106022128-cf704f80-60c5-11eb-9af5-df0a418d2481.png)
![ProcessNameFormat=2](https://user-images.githubusercontent.com/1874108/106022141-d26b4000-60c5-11eb-99a5-335b63472867.png)

**Comment by gewarren** [comment]
@eremmel Thank you for taking the time to do that! I will update the doc, or you can too if you like.

**Comment by eremmel** [comment]
As you can see it is not only the value '2' but also the format that comes with value '2'. The format is <process>_<pid>, but the article states a third part...
(I'm not a native English writer to I like to stay away from editing 'official' pages...

**Comment by sywhang** [comment]
@gewarren I can verify that the `ProcessNameFormat` registry value needs to be 2. I can follow up with a PR to address this. Thanks for reporting this and taking the time to investigate it @eremmel!

**Comment by gewarren** [comment]
Thank you @sywhang !
