### ISSUE TITLE
Where are we supposed to type dotnet run? Also, There is no option for my code to run in Visual Studio, and when I click debug it just opens an empty JSON file?

### ISSUE THREAD

**Issue by GabriellaLaPlace** [dotnet/docs#17859]
Where are we supposed to type dotnet run? Also, There is no option for my code to run in Visual Studio, and when I click debug it just opens an empty JSON file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @GabriellaLaPlace 

You can issue the `dotnet run` command from the command line (either CMD, or Powershell) in the current directory. 

If you are using Visual Studio, the "Run without Debugging" item on the "Run" menu builds and runs the current app.

We'll update this article with more details on both those steps. I've added the "up for grabs" label if others want to make the edits sooner.

**Comment by GabriellaLaPlace** [comment]
I don't see a run menu. The are where there is an option to run, does not
let me select anything to run. It's nice that you guys are going to redo
the article. Also, I'm planning on watching the c# .net tutorials by
Microsoft on YouTube. I might try that dotnet run commands on the page,
later also.

**Comment by GabriellaLaPlace** [comment]
I was trying to say. There is an option to choose something to run. But it
doesn't work. When I downloaded Visual Studio, I choose the .Net Option.
There is no run menu, in my visual studio.
