### ISSUE TITLE
DateTime.Parse is locale sensitive

### ISSUE THREAD

**Issue by emsteenbrink** [dotnet/docs#17860]
Entering "date = DateTime.Parse("11/16/2019 5:25 PM")" in the immediate window will result in an error for countries that adopt the dd/mm/yy notation instead of the mm/dd/yy notation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582
* Version Independent ID: aeb94c3f-50e0-eb84-e469-f6eb778bad62
* Content: [Debug your Hello World .NET Core application with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio?tabs=csharp#feedback)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/debugging-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@emsteenbrink Thanks for reporting that, we'll fix it the next time we update this tutorial.
