### ISSUE TITLE
Need more details for what can go wrong when using newer LangVersion than TargetFramework default

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [dotnet/docs#17861]
I think it's pretty cool that I can build with MSBuild 16 and use a lot of the C# 8 features even if still targeting an old framework like .NET 4.6.1 for backwards compatibility.

However, the docs say:

> Choosing a language version newer than the default can cause hard to diagnose compile-time and runtime errors.

It's a bit weird for the tools to *allow* to use a newer language version than default, and the recommendation to be not to do it, without providing too many details on *why*.

Can you please provide more context on what are the "hard to diagnose compile-time and runtime errors" that can occur when using a newer language version?

> This default choice also ensures you don't use a language that requires types or runtime behavior not available in your target framework.

Shouldn't the compiler enforce this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I understand your concern @andrei-epure-sonarsource 

The article does mention the main areas of concern:

> - Default interface member implementation requires new features in the .NET Core 3.0 CLR.
> - Async streams require the new types <xref:System.IAsyncDisposable?displayProperty=nameWithType>, <xref:System.Collections.Generic.IAsyncEnumerable%601?displayProperty=nameWithType>, and <xref:System.Collections.Generic.IAsyncEnumerator%601?displayProperty=nameWithType>.
> - Indexes and Ranges require the new types <xref:System.Index?displayProperty=nameWithType> and <xref:System.Range?displayProperty=nameWithType>.
> - Nullable reference types make use of several [attributes](../nullable-attributes.md) to provide better warnings. Those attributes were added in .NET Core 3.0. Other target frameworks haven't been annotated with any of these attributes. That means nullable warnings may not accurately reflect potential issues.

It's an unsupported scenario. The above notes are enough to know where and how you might be affected.

I'll close this as answered.

**Comment by andrei-epure-sonarsource** [comment]
Thanks @BillWagner . So it's only the well-known and well-communicated differences between .NET Framework support for C# 8 and all the other frameworks with full support.

Basically the first 3 issues in the docs are detected by the compiler, and the error messages are pretty clear and expected.

And only the last issue ("<Nullable>enable</Nullable>") can lead to weird runtime behaviors on .NET Framework because it doesn't have all the necessary attributes for a nice usage.
