### ISSUE TITLE
Importance of Using

### ISSUE THREAD

**Issue by afbarksd** [dotnet/docs#17873]
The note about using Using as an alternative to Try/Finally to avoid resource leakage is useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870ea49c-ad84-f940-8d27-17c8b25beb97
* Version Independent ID: 285ef531-525a-8703-0f16-73a3c9e497b0
* Content: [Try...Catch...Finally statement - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/try-catch-finally-statement)
* Content Source: [docs/visual-basic/language-reference/statements/try-catch-finally-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/try-catch-finally-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
Thanks!
