### ISSUE TITLE
Remove/redirect NIB links from the content

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1787]
We have several old links that go to retired topics that will start with NIB or Not in Build. We should review the content to see whether those links should be removed or replaced.

- [ ] https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=nib&type= (current count: 439)
- [ ] https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=notinbuild&type= (current count 15)
- [ ] https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22not+in+build%22&type= (current count 13)

**Comment by rpetrusha** [comment]
In addition to removing or replacing the links, a third option is to restore the original topic. In some cases, the decision to remove a topic from the doc set was based purely on page views over a specified time period, which is not necessarily a very good way to assess the importance of a topic.

**Comment by pkulikov** [comment]
The status update: not a lot of links left.

**dotnet/docs** repo:
- https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=nib&type= (current count: 28)
- https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=notinbuild&type= (current count: 1)
- no `NOT IN BUILD` links

**dotnet/dotnet-api-docs** repo:
- https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=nib&type= (current count: 31)
- https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=notinbuild&type= (current count: 14, but it's one unique link to replace)
- https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=%22not+in+build%22&type= (current count: 1)

@mairaw it's fine with me if you update the issue text with those new counts and delete this comment.

**Comment by eddynaka** [comment]
@BillWagner is this still an issue? looking at the old links, its all done.

**Comment by BillWagner** [comment]
@eddynaka  It looks like there are still three instances to address:  https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=nib&type=

Do you want to submit a PR for this?

**Comment by pkulikov** [comment]
There are three left:
https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=nib&type=

**Comment by eddynaka** [comment]
@BillWagner just created! Thanks

**Comment by BillWagner** [comment]
Thanks @eddynaka 

I just reviewed the changes, and made one repeated suggestion to remove the locale `en-us` from the links. That way, readers will be directed to the correct language and culture based on their machine's settings.  Once you accept those suggestions, I'll merge the PR.

Thanks for helping us improve the docs!
