### ISSUE TITLE
没有翻译成中文

### ISSUE THREAD

**Issue by www741147** [dotnet/docs#17878]
没有翻译成中文

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a9c4bf74-8064-6c45-d5c8-2bbdb0113895
* Version Independent ID: 3250ed35-9410-87f6-ba3e-258c85fbc7f1
* Content: [Nullable reference types - C# reference](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/nullable-reference-types#feedback)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by TakaSoap** [comment]
Check this: [https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/builtin-types/nullable-reference-types.md](url)
