### ISSUE TITLE
Getting error:  Resource file "**/*.resx" cannot be found. [/ConsoleApp1.csproj]  

### ISSUE THREAD

**Issue by shivanshi18** [dotnet/docs#17874]
Not able to build the csproj as I am getting the error: 
dotnet run
/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(3032,5): error MSB3552: Resource file "**/*.resx" cannot be found. [/ConsoleApp1.csproj]

The build failed. Fix the build errors and run again.
If the issue is:

- A simple typo or similar correction, consider submitting a PR to fix it instead of logging an issue. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

**Issue description**

&lt;include description here&gt;

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Thraka** [comment]
Hello  @shivanshi18  Can you provide more information about the article you're reading?
