### ISSUE TITLE
It does it wrong when converting from float to int.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#17889]
Hi team, 
I moved this from here: https://github.com/dotnet/docs.tr-tr/issues/17

the comments below were machine-translated
@XLIVE99 commented on Thu Apr 16 2020

(int) returns the result (2.02f * 100) 201, but returns the result (int) (2.02001f * 100) 202.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91266ab9-071d-067c-df52-8a297045af24
* Version Independent ID: 1d378928-4bb5-6bcf-49ca-2026768ab2aa
* Content: [Casting and type conversions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions#feedback)
* Content Source: [docs/csharp/programming-guide/types/casting-and-type-conversions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/casting-and-type-conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@CeciAc Do you have any more details on this issue? The testing I did shows the correct result, and the documentation matches the behavior.

**Comment by XLIVE99** [comment]
When i try it on online compiler, result is wrong.
![Res](https://user-images.githubusercontent.com/30470295/79762449-78b23a00-832b-11ea-920b-a07114588da6.png)

**Comment by svick** [comment]
I get the output "1, 2" [on .Net Framework in 32-bit mode](https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiATgVzAHwAICYCMAsAFAl4AEAwiQN4nkPnb4BsTALOQLICGAlmAAUASnqM6xRlPIwANgHseUcj3zkAvOQAMAOi24YAbjHSZCpStwbte3Fvv4jJ6QOX81mwa+GDV5AFTk+PbCxpKm5K4qfFae3r5WgcFaoc5SzACcvnz4qeGmmdm4eVIAviSlQA==), but "2, 2" [on .Net Framework 64-bit](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWACgicACAYSIG8jS7TNcIGpSBZAQwEtUAKASlr0ahemNIAzADYB7DnFIdcpALykADADp12CQG4h4ybPmLsqjduzqbufYfE8F3ZWt5P+vJaQBUpXDb8BqJGpE6KXOZuHl7mfgHqQQ5ijACcXly4SSFGaRnY2WIAvkRFQA==) and [on .Net Core](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoa0gAgGFqBvau9uospTlOgWQCGASzwAKAJRsOrKh3l0AZgBsIgjHUFk6AXjoAGAHT6SigNzSFS1es0ldB4yX0uy5ywtEaR2vWK8SYlp0AFR0ZC4SFnJWdF6awvZ+AUH2YRH6UR7yXACcQcJkWTFWeQUkxfIAvtRVQA===) (both in 32-bit and 64-bit mode).

So I think that this is a .Net Framework bug, but one that's probably not going to be fixed.
