### ISSUE TITLE
Monthly chores - May 2020

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#17890]
- [x] Check broken links report for [dotnet/docs](https://ops.microsoft.com/#/repos/a3bda507-3390-de91-8f7f-26f90f4e5fc8?tabName=brokenlinks)
- [x] Check broken links report for [dotnet/dotnet-api-docs](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks)
- [x] Check github.com/microsoftdocs/feedback/issues for .NET issues
- [x] Run [CATS tests](https://contentqacats.azurewebsites.net/create_docs_content_validation_run) on the .NET repo (docset == "core-docs")
- [x] Run CleanRepo and check for orphaned articles
- [x] Run CleanRepo and delete orphaned images
- [x] Run CleanRepo and fix up links (redirects, site-relative)

**Comment by BillWagner** [comment]
@gewarren Should this be closed?

**Comment by gewarren** [comment]
> @gewarren Should this be closed?

Yes, thank you!
