### ISSUE TITLE
Add remark about @-identifiers

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/docs#17907]
I miss the information of how @-identifiers are serialized as there are two possibilities that would make sense:

Results `nameof(@new)` in "@new" or "new"?
(The correct answer is "new")
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b82de3-3121-209c-6dc4-6267f726dcfe
* Version Independent ID: 7c19d7e6-f241-2f7e-9dad-737df8328663
* Content: [nameof expression - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof)
* Content Source: [docs/csharp/language-reference/operators/nameof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/nameof.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @HugoRoss 

I've added it to our backlog to address. I've also added the "up for grabs" label for any community members interested in making this enhancement.p
