### ISSUE TITLE
Docs incorrectly claim that decimal is fixed point

### ISSUE THREAD

**Issue by reflectronic** [dotnet/docs#17903]
This documentation seems to insinuate that `decimal` represents a fixed point number, when really it is a floating-point number like `double` and `float`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb6905a9-e9ec-df6f-5733-dfb25a41b97a
* Version Independent ID: fe0e2716-651b-a883-6371-ded1ace94a11
* Content: [Numbers in C# - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local#work-with-fixed-point-types)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
Related (for the interactive tutorial): #17103

**Comment by BillWagner** [comment]
We also have this issue in the standard. We're planning to address it there, so I'm happy to see us fix it here as well.
