### ISSUE TITLE
Needs more explanation

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#17906]
Explicit implementation could use more explanation as to why `public` has the effect that it does in the given example as well as in the other possible variations:
```
  // ok
  class Middle0 : ILeft, IRight
  {
    int IRight.P() { return 0; }
    int ILeft.P { get { return 0; } }
  }

  // ok
  class Middle1 : ILeft, IRight
  {
    int IRight.P() { return 0; }
    public int P { get { return 0; } }
  }
  
  // ok
  class Middle2 : ILeft, IRight
  {
    public int P() { return 0; }
    int ILeft.P { get { return 0; } }
  }

  // compile error:
  // The modifier 'public' is not valid for explicit interface implementation.
  class Middle3 : ILeft, IRight
  {
    public int IRight.P() { return 0; }
    public int ILeft.P { get { return 0; } }
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Explicit Interface Implementation - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @daveyostcom 

The language prohibits any access modifiers on any explicit interface member implementation. This article should add that, and reference the language reference or specification.
