### ISSUE TITLE
Do not generally recommend DateTime for Databases

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/docs#17909]
The following is written in the DateTime section

> Retrieve date and time information from sources outside of .NET, such as SQL databases. Typically, these sources store date and time information in a simple format that is compatible with the DateTime structure.

And as a hint:

> When saving or sharing DateTime data, UTC should be used and the DateTime value's Kind property should be set to DateTimeKind.Utc.

The section of DateTimeOffset contains the following:

> These uses for DateTimeOffset values are much more common than those for DateTime values. As a result, DateTimeOffset should be considered the default date and time type for application development.

The problem I keep seeing is that the developers continue to use DateTime and don't care about the timezone.

DateTime has many disadvantages when used in the database, including
- DateTimeOffset is SQL Compliant, DateTime is not
- DateTimeOffset has a date range from 0001 to 9999, DateTime from 1753
- The accuracy of DateTimeOffset is higher

And especially important: DateTimeOffset respects the time zone.

So I think it is appropriate that DateTime is not recommended for direct use to exchange times in APIs, files or databases - but DateTimeOffset.

Since DateTimeOffset is generally the recommended way anyway - it is already mentioned in the documentation - the whole section DateTimeOffset should be moved up.
Otherwise people will only read DateTime and not the very important rest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b64d1f3-174c-fffe-d2e6-59a0b62de797
* Version Independent ID: 832e5ebc-6fc0-e596-5827-51034a3f89ab
* Content: [Choosing between DateTime, DateTimeOffset, TimeSpan, and TimeZoneInfo](https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime#feedback)
* Content Source: [docs/standard/datetime/choosing-between-datetime.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/choosing-between-datetime.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by tarekgh** [comment]
> DateTimeOffset has a date range from 0001 to 9999, DateTime from 1753
> The accuracy of DateTimeOffset is higher

I don't think either of these statements is true. could you please clarify from where did you get this information?

**Comment by BenjaminAbt** [comment]
> I don't think either of these statements is true. could you please clarify from where did you get this information?

You quoted my paragraph that referred to the use of DateTime in databases.

- In the past `System.Datetime` used to use T-SQL `datetime`. Newer stuff (like EF Core Migrations) takes `datetime2`. 
- `System.DateTimeOffset` equivalent is `datetimeoffset`
[Date and Time Data Types and Functions (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15)

In the wild, you unfortunately still see many many developers using `DateTime` with T-SQL `datetime` because it "works" and the developers are not aware of the differences - apart from the missing time zone support, range and accuracy. Besides EF Migrations, [Fluent Migrator](https://github.com/fluentmigrator/fluentmigrator/) is also very common in .NET; and here again the use of [AsDateTime()](https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator/Builders/ExpressionBuilderWithColumnTypesBase.cs#L113) instead of `AsDateTime2()` or even better `AsDateTimeOffset()` is unfortunately also very common.

It is very important that the documentation finally speaks a clear language why the use of `DateTimeOffset` is so important and sustainable.

**Comment by tarekgh** [comment]
@BenjaminAbt your comments may apply to databases but not applying to the runtime. Your original comment was not clear about that. Maybe modifying the database docs would be more reasonable here.
