### ISSUE TITLE
Confusing statements 

### ISSUE THREAD

**Issue by adibiton** [dotnet/docs#17908]
'Main must be static and it need not be public. '

And:
'public static void Main() { }'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6280abc4-899a-187d-1de4-1ea629ac5419
* Version Independent ID: 24dbcd84-98c0-421e-d586-5d081ce2ec34
* Content: [Main() and command-line arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/#feedback)
* Content Source: [docs/csharp/programming-guide/main-and-command-args/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/main-and-command-args/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @adibiton 

This is misleading, and we should add the following text after the list of valid signatures

> The preceding examples all use the `public` accessor modifier. That is typical, but not required.

I've added this to our backlog, and I've added the "up-for-grabs" label for any community members who want to make this update.

**Comment by m-sekhon** [comment]
@BillWagner I've added the required sentence and submitted a PR. Please approve if it looks ok.
