### ISSUE TITLE
.NET 5 target framework

### ISSUE THREAD

**Issue by WebFreak001** [dotnet/docs#17911]
The predefined symbols inside the Remarks "Target Frameworks" sections don't include any information for .NET 5

Will it be
```cs
#if NET50
```
or
```cs
#if NETCOREAPP5_0
```
or something else? Will `NETFRAMEWORK`, `NETSTANDARD` or `NETCOREAPP` be defined with .NET 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if#feedback)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @WebFreak001 

I don't think a final decision has been made. I've added this to our list of articles to update for the .NET 5 wave.

**Comment by NN---** [comment]
NET5_0

**Comment by WebFreak001** [comment]
oh yeah looks documented now, thanks
