### ISSUE TITLE
How to rasie the Event

### ISSUE THREAD

**Issue by infinitylight** [dotnet/docs#17916]
[Enter feedback here]
I afarid there is something is not good enough.
There is "The publisher determines when an event is raised; the subscribers determine what action is taken in response to the event."
and  "Events that have no subscribers are never raised.".
You known:
Event raised by  publisher,and whether there are subscribers only determines the subsequent operations(Whether to execute the corresponding method).
For example:
   class Program
    {
        public delegate void StopMachineryDelegate();
        public event StopMachineryDelegate MachieneOverheating;
        private void Notify()
        {
            if (this.MachieneOverheating !=null)
            {
                this.MachieneOverheating();
            }
        }

        static void Main(string[] args)
        {
            Program p1 = new Program();
            p1.Notify();
        }

}
Thank you in advance for reply!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3145839a-13de-a6a4-7128-ad3dae869022
* Version Independent ID: 949b38e6-6398-73c5-034c-7ee683b468d0
* Content: [Events - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/)
* Content Source: [docs/csharp/programming-guide/events/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @infinitylight,

Thank you for reaching out and posting this clarifying statement. I typed up a quick example of what you're asking, and modified it a bit. With that said, I agree with the original documentation as it states that "events that have no subscribers are never raised".

With your example, when we call `.Notify()` the method does a `null` check on the `event` member. If there is not an subscribers the field is `null`, thus the event is not raised. Does that make sense?

```csharp
class Program
{
    public delegate void StopMachineryDelegate();

    public event StopMachineryDelegate MachieneOverheating;

    private void Notify() => MachieneOverheating?.Invoke();

    static void Main(string[] args)
    {
        var program = new Program();
        program.Notify();
    }
}
```
