### ISSUE TITLE
CoreFX

### ISSUE THREAD

**Issue by HeinziAT** [dotnet/docs#17910]
What does the "FX" stand for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa071095-4eb6-20c1-ca26-f34da6fcbdf8
* Version Independent ID: 2b2efd49-b0c8-9a13-525a-d04c802d2bef
* Content: [.NET Glossary](https://docs.microsoft.com/en-us/dotnet/standard/glossary#corefx)
* Content Source: [docs/standard/glossary.md](https://github.com/dotnet/docs/blob/master/docs/standard/glossary.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I believe it stands for "framework".

"CoreFX is the foundational class libraries for .NET Core. It includes types for collections, file systems, console, JSON, XML, async and many others."

**Comment by HeinziAT** [comment]
Well, I thought so, too, but there is no "x" in Framework.

Since the stated goal of the glossary is to _"clarify meanings of selected terms and acronyms that appear frequently in the .NET documentation"_, I think that this information (after it has been discovered) should be added here.

**Comment by gewarren** [comment]
Sure, I can add that info to the glossary. I think that "x" is commonly used to shorten a word. For example, doctors write "Tx" as shorthand for treatment.

Here's another example of Fx being used to mean "framework": https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview

@mairaw Can you officially state if the "Fx" in CoreFx means "framework"?

**Comment by mairaw** [comment]
I think so. @karelz @danmosemsft can you confirm?

**Comment by karelz** [comment]
Yes, FX stands for Framework.

**Comment by danmosemsft** [comment]
Yes, but we don't use the CoreFX term any more. We use "core .NET Libraries". It's OK to have it in a glossary as it comes up from time to time.

**Comment by gewarren** [comment]
@danmosemsft Should we update the title and TOC name for this page then?

https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx

**Comment by danmosemsft** [comment]
@gewarren good point, yes please (I hadn't seen this doc before). I suggest "Core .NET Libraries"
