### ISSUE TITLE
Misleading return types for range indexing: sub-array vs span

### ISSUE THREAD

**Issue by petrroll** [dotnet/docs#17912]
The document doesn't explicitely mention the implications of range indexing for arrays (that are used in examples): that it creates a subarray that's a copy and not just a view (slice) while the used language `creates subrange` IMO hints that it's creating the latter.

This is further worsened by one of the examples `Span<int> x_y = numbers[x..y];` that suggests the idea that in this case a Slice is returned. But [in reality](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBkCWAdgI4DcyyUAzJjOgMLoDey6bmNUALOgLIAUASmat2YogBcA2gF10hAK4BbAEYBTAE4BndAF50AUUVLNAQxUAbNdgBKpwgHM1/VABp0cVKkHYAKgHsAQQ0NUwBPIXIkMTEAZQAHewAeSQA+dAAPAH0wvXlldW0pHGwAVhkosQBfZCqgA==) a subarray (i.e. copy) is returned and then it's implicitly converted to `Span`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes#feedback)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @petrroll 

We'll investigate and make updates

/cc @stephentoub for runtime and library details.

**Comment by stephentoub** [comment]
> This is further worsened by one of the examples Span&lt;int&gt; x_y = numbers[x..y]; that suggests the idea that in this case a Slice is returned. But in reality a subarray (i.e. copy) is returned and then it's implicitly converted to Span.

Correct, this is one of the reasons I personally didn't want slicing on arrays (or alternatively wanted them to return spans).  It's way too easy to make this mistake.  We've just added an analyzer to help catch such issues:
https://github.com/dotnet/roslyn-analyzers/pull/3464
cc: @bartonjs
