### ISSUE TITLE
.NET Framework 4.8 Windows 10 1909 Release Key

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/docs#17921]
The document shows two different release keys for Windows 10 1909 (aka November 2019 Update)
```
On Windows 10 May 2019 Update and Windows 10 November 2019 Update: 528040
On Windows 10 and Windows Server, version 1909: 528209
```

Can this be rewritten to be clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed?redirectedfrom=MSDN#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Thraka It looks like you added that info in response to https://github.com/dotnet/docs/issues/14931.  Should it say this instead?

`On Windows 10 and Windows Server, version 2004: 528209`

**Comment by Thraka** [comment]
I would venture to guess that it should say this:

```
On Windows 10 May 2019: 528040
On Windows 10 and Windows Server, version 1909: 528209
On all other Windows operating systems (including other Windows 10 operating systems): 528049
```

**Comment by gewarren** [comment]
From my understanding, 528209 is for the Vibranium release, so it's not for 1909.

**Comment by Thraka** [comment]
HA whoops I was thinking Vibranium was 1909... doh!
