### ISSUE TITLE
Coalescing getters

### ISSUE THREAD

**Issue by kfsone** [dotnet/docs#17922]
There is a mundane use-case where getters do not currently help: a default-null property where null represents a fall-thru to a default value in another value/property:

```
public string Name { get; set; }
string _preferredName = null;
public string PreferredName
{
  get => _preferredName ?? Name;
  set;
}
```

Here, "PreferredName" is presumed to be the Name unless it is overridden with a non-null value.

This seems like a case that can be greatly simplified with a "coalescing get":

```
public string Name { get; set; }
public string PreferredName { get ??= Name; set; }
```

Using `??=` this way allows for a very succinct syntax, implying the backing variable as the initial value.

For a less-trivial case where the property is balancing two different named values, this is already covered:

```
//  CONTRIVED
public string FamilyName;
public string Title;
public string TitledName { get => Title.Length > 0 ? $"{Title} ${FamilyName}" : null; }
public string Surname { get => TitledName ?? FamilyName };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb1d95e-a652-a965-f817-d49554a07388
* Version Independent ID: 05423053-63de-3e56-0929-2ae477d577df
* Content: [Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is an interesting idea @kfsone 

I'm closing this issue because the docs accurately reflect the current C# features. If you want the design team to consider this idea, you should open an issue and proposal in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository. That's where the team considers new features.
