### ISSUE TITLE
Adjust callback section (recursive call note)

### ISSUE THREAD

**Issue by Zastai** [dotnet/docs#17924]
The document says not to pass through the options passed to a custom converter when recursively calling back into the serializer.

Looking at the current (4.7.1) code, not passing options (or passing null) ends up using some set of defaults, That to me means the recursive call may behave incorrectly (ignoring naming convention etc. set by the caller).
So perhaps the suggestion should be to remove `this` from the `Converters` collection for the duration of the call? Something like
```csharp
  options.Converters.Remove(this);
  try {
    JsonSerializer.Deserialize(ref reader, typeof(Foo), options);
  }
  finally {
    options.Converters.Add(this);
  }
```

Plus, even if you were asking for a type your converter handles, there is no real guarantee that there would be an infinite recursion. That would depend entirely on what yor custom converter is doing. So the documentation should perhaps just warn to take care when passing `options` along, suggesting the code above to avoid infinite recursion scenarios.

Another thing would be to add a `Clone()`-like method to `JsonSerializerOptions`. Currently, to pass along a different instance, you have to explicitly set values, so you cannot be future-proof and preserve values for properties you do not list (because they might not exist yet).

Possibly even `WithConverter()` and `WithoutConverter()` convenience methods (which clone + add/remove from Converters), so that the code above could just be:
```csharp
  JsonSerializer.Deserialize(ref reader, typeof(Foo), options.WithoutConverter(this));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#callbacks)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @layomia @steveharter @Jozkee

**Comment by Zastai** [comment]
(In fact, the not about future-proof option copying already applies, give .NET 5 is adding new ones. But perhaps that needs a dotnet/runtime ticket?)

**Comment by tdykstra** [comment]
Closing this issue, as additional guidance on recursively calling Serialize/Deserialize was added by PR #19375 for issue #19268
Feel free to reopen if more discussion is needed.
