### ISSUE TITLE
Consider using more standard English

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#17935]
This is just a small nitpick, nothing technical, but I've seen it more than once in the documentation, the awkward phrase "You also can ..."

To a native English speaker who grew up in America (where I think Microsoft is headquartered), it grates on my ears whenever I read those words.  I'm 99% certain the normal order is "You can also ..." as in "You can also use the null-forgiving operator ..."  Try doing a Web search for the phrase "you also can" vs. the phrase "you can also".  Notice the second phrase returns about 40 times more results, because it's much more common to write/speak English that way.

Is this petty?  This is the documentation for a programming language.  C# is a language.  English is a language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0471f98c-f5cd-00d2-a705-396682f73bcb
* Version Independent ID: a24b862d-c462-a040-8470-9771c74c4e6f
* Content: [! (null-forgiving) operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving#feedback)
* Content Source: [docs/csharp/language-reference/operators/null-forgiving.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/null-forgiving.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this up @matthew45052 

Before I take action, I'd like to get more information on why this was done.

**Comment by pkulikov** [comment]
> Before I take action, I'd like to get more information on why this was done.

If I search the docs, the "you can also" version is more popular than the "you also can" version. Furthermore, about the half of all "you also can" have been introduced by me. Also, I remember that @mairaw once corrected my "you also can" into "you can also". After that, I think I've corrected my wording in the new articles, but not in the existing ones.

**Comment by BillWagner** [comment]
@pkulikov I'm almost certain you're correct. I just want to verify before merging.

**Comment by BillWagner** [comment]
@matthew45052 @pkulikov 

Everyone agrees, and any reason for using "you also can" has been lost to history.

Let's make this change.  @pkulikov There's one merge conflict in your PR that I just resolved. I'll approve it and :shipit: now.
