### ISSUE TITLE
i likwe this alot

### ISSUE THREAD

**Issue by austinHeisleyCook** [dotnet/docs#17937]
great optic good exampel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1503ba-55b3-177f-fb47-204bd5b19a64
* Version Independent ID: 241d90b0-13b9-ae00-276a-3f8b31db7fbe
* Content: [Command-line build with csc.exe](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/command-line-building-with-csc-exe#feedback)
* Content Source: [docs/csharp/language-reference/compiler-options/command-line-building-with-csc-exe.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/command-line-building-with-csc-exe.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you. Closing as kudos.
