### ISSUE TITLE
code snippets are for a different topic

### ISSUE THREAD

**Issue by dev-eric-ernst** [dotnet/docs#17949]
The code examples provided seem to be examples of StringReader or how to define multiline strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @dev-eric-ernst 

The snippets are correct. We chose the `StringReader` as the example class because it implements `IDisposable` and it's a common type. The declarations that initialize a `StringReader` all use the `using` statement.

Closing as by-design.
