### ISSUE TITLE
Help on targeting UWP

### ISSUE THREAD

**Issue by DanieleScipioni** [dotnet/docs#17943]
In section Multi-targeting there is this example:
```
#if NET461
        return CallDotNetFramworkApi();
#elif WINDOWS_UWP
        return CallUwpApi();
#else
```
I tried to set these targets for UWP and net461 in csproj file in this way:
` TargetFrameworks>netstandard2.0;net461;uap10.0</TargetFrameworks>`
I found `uap10.0` listed at [Supported target framework versions](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions)
but the build fails with error 
` error NETSDK1013: The TargetFramework value 'uap10.0' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.`

Which is the correct way to target uap10.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by DanieleScipioni** [comment]
Maybe I found, this seems to work
```
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461;uap10.0</TargetFrameworks>
  </PropertyGroup>

  [...]

  <PropertyGroup Condition="'$(TargetFramework)'=='uap10.0'">
    <NugetTargetMoniker>UAP,Version=v10.0</NugetTargetMoniker>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
    <TargetFrameworkIdentifier>.NETCore</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
    <DefineConstants>$(DefineConstants);UAP10_0</DefineConstants>
    <DefaultLanguage>en-US</DefaultLanguage>
    <LanguageTargets>$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets</LanguageTargets>
  </PropertyGroup>

  [...]

  <ItemGroup Condition="'$(TargetFramework)'=='uap10.0'">
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.10" />
  </ItemGroup>
```

Maybe the docs need to be updated

**Comment by Thraka** [comment]
Doing some searching I found this issue which indicates this isn't a supported scenario: https://github.com/dotnet/sdk/issues/1408

However, it's noted in the issue that https://github.com/novotnyllc/MSBuildSdkExtras should get you over some hurdles.

I see you targeted .NET Standard 2.0 and some other frameworks, it was noted in the article that you shouldn't target standard along with the other frameworks because when adding the library via NuGet, the .NET Standard version will be the default.

Since this isn't a supported scenario, I'll close this issue. Hopefully the SDK Extras package helps out.

Have a good day!
