### ISSUE TITLE
List actions that cause Task fault to be "observed"

### ISSUE THREAD

**Issue by mstefarov** [dotnet/docs#17946]
This page makes it clear that exceptions thrown from Tasks should be "observed", but it is not clear what actions actually "observe" it.  As far as I know, the list of ways includes :
- `await`ing a task
- Calling Wait()
- Accessing Result property
- Accessing Exception property

@stephentoub's original TPL-in-net45 announcement (https://devblogs.microsoft.com/pfxteam/task-exception-handling-in-net-4-5/) gives some examples but does not have a complete list.  Is there more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25bdb110-7ada-3817-bc40-9c11cab6513c
* Version Independent ID: 9476dc46-d4f0-e7f4-c21e-faaafe0433ea
* Content: [Exception handling (Task Parallel Library)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library?view=netframework-4.8#observing-exceptions-by-using-the-taskexception-property)
* Content Source: [docs/standard/parallel-programming/exception-handling-task-parallel-library.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/exception-handling-task-parallel-library.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by stephentoub** [comment]
It's anything that provides the exception to the consumer, which means direct access via Task.Exception or the propagation of the exception via .Wait/.Result/await/.GetAwaiter().GetResult().

**Comment by mstefarov** [comment]
Another doc page mentions that _standalone discard_ also observes/suppresses task exceptions, is that correct? https://github.com/dotnet/docs/blob/b5ad8e857b35819d5b6a071bed1e4cc4da56495e/docs/csharp/discards.md#a-standalone-discard

**Comment by stephentoub** [comment]
> Another doc page mentions that standalone discard also observes/suppresses task exceptions, is that correct?

If it means:
```C#
_ = task;
```
then, no, the doc is wrong.  If it means:
```C#
_ = task.Exception;
```
then, yes, that's fine, but it has nothing to do with the discard, but rather the access to `Exception`.
