### ISSUE TITLE
Meaning of <NetStandardImplicitPackageVersion> element

### ISSUE THREAD

**Issue by gkeongit** [dotnet/docs#17951]
The statement "...you can use the &lt;NetStandardImplicitPackageVersion&gt; element in your project file to specify a framework version that is **lower** than the metapackage version." is a little bit confusing, especially, as the following example uses the element to specify a higher version. 

If I got it right, it means, the element allows to specify a framework version that is **higher** than the target framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8166ec-177f-67e5-7e98-2190ea82e0b0
* Version Independent ID: d6573a5f-4eb4-21c1-4d4f-50ef0f4723ae
* Content: [Packages, metapackages, and frameworks - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/packages#feedback)
* Content Source: [docs/core/packages.md](https://github.com/dotnet/docs/blob/master/docs/core/packages.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@gkeongit The wording is confusing, I agree. I think what it's trying to say is that by adding the `NetStandardImplicitPackageVersion` element, it allows you to specify different versions for the target framework and referenced metapackage. And the target framework can be lower than the metapackage version. Perhaps it should be reworded to:

`By adding the <NetStandardImplicitPackageVersion> element to your project file, which specifies a metapackage version, you can specify a framework version that's lower than the metapackage version.`

**Comment by gkeongit** [comment]
Yes, that would be clear, I think.
