### ISSUE TITLE
Incorrect versions in latest.version this script refers to

### ISSUE THREAD

**Issue by aannenko** [dotnet/docs#17952]
dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1/latest.version - returns 2.1.16, latest is 2.1.17 (same is true for dotnetcli.azureedge.net; dotnet/aspnetcore/Runtime/2.1/latest.version correctly returns 2.1.17)

dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1/latest.version - returns 2.1.804, latest is 2.1.805 (same is true for dotnetcli.azureedge.net)

dotnetcli.blob.core.windows.net/dotnet/Runtime/2.2/latest.version - returns 2.2.7, latest is 2.2.8 (same is true for dotnetcli.azureedge.net; dotnet/aspnetcore/Runtime/2.2/latest.version correctly returns 2.2.8)

dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/Current/latest.version - returns 3.1.0, latest is 3.1.3 (same is true for dotnetcli.azureedge.net source; dotnet/Runtime/Current/latest.version correctly returns 3.1.3)

dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/LTS/latest.version - returns 3.1.0, latest is 3.1.3 (same is true for dotnetcli.azureedge.net source; dotnet/Runtime/LTS/latest.version correctly returns 3.1.3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by aannenko** [comment]
dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2/latest.version - returns 2.2.402, not sure if the latest version is this one or 2.2.207

**Comment by aannenko** [comment]
All the above makes my script, which is based on this script, download non-latest versions: https://github.com/aannenko/dotnet-download

**Comment by tdykstra** [comment]
@wli3 who can help with this?

**Comment by wli3** [comment]
Issue moved to [dotnet/sdk #11356](https://github.com/dotnet/sdk/issues/11356) via [**ZenHub**](https://www.zenhub.com/)
