### ISSUE TITLE
Review outdated content mentioning old versions of VS

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1795]
There are a lot of topics that still mention old versions of Visual Studio.

For example, see this query for Visual Studio 2010:
https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=visual+studio+2010&type=

When we can, we should avoid talking about a specific version unless we're saying when a feature was introduced or showing version history. 

Also note that topics can be using the token file (for example, [vs_dev10_long_md.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interop/includes/vs_dev10_long_md.md)) instead of having the text in the topic itself.

We'll be redirecting the latest version of C# and VB topics from MSDN to docs soon, so topics can be applicable to VS 2015 and 2017.

**Comment by GuardRex** [comment]
**WIP** until a final pass is made after the three PR's are merged.
