### ISSUE TITLE
Not able to execute at Linux-arm running at i.MX28 env

### ISSUE THREAD

**Issue by heautio** [dotnet/docs#17959]
I'm facing segmentation fault when executing .Net (linux-arm) at openwrt running at imx28 env.

My development env is Ubuntu 18.04.3 LTS and I'm able to cross compile other applications to the same target but not the Hello Word example from .Net. So I think my dev env is ok. I tried also the runtime binaries but the same issue is faced. 

Here is the issue at target board:

root@openwrt:/usr/bin/dotnet/publish# echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# echo $DOTNET_ROOT
/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# ./dotnet --info
Segmentation fault
root@openwrt:/usr/bin/dotnet/publish# LD_TRACE_LOADED_OBJECTS=1 /lib/ld-linux.so.3
./dotnet
        libpthread.so.0 =&gt; /lib/libpthread.so.0 (0xb6ed0000)
        libdl.so.2 =&gt; /lib/libdl.so.2 (0xb6ebd000)
        libstdc++.so.6 =&gt; /usr/lib/libstdc++.so.6 (0xb6daa000)
        libm.so.6 =&gt; /lib/libm.so.6 (0xb6ce6000)
        libgcc_s.so.1 =&gt; /lib/libgcc_s.so.1 (0xb6cc9000)
        libc.so.6 =&gt; /lib/libc.so.6 (0xb6b84000)
        ld-linux-armhf.so.3 =&gt; /lib/ld-linux-armhf.so.3 (0xb6b52000)
        /lib/ld-linux-armhf.so.3 =&gt; /lib/ld-linux.so.3 (0xb6efb000)
root@openwrt:/usr/bin/dotnet/publish#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
I think this issue should really be on the dotnet/sdk repository. I'll clone the issue over there.

**Comment by Thraka** [comment]
This issue was moved to dotnet/sdk#11492
