### ISSUE TITLE
The template instructions can use a csproj

### ISSUE THREAD

**Issue by nkolev92** [dotnet/docs#17967]
Moving from https://github.com/NuGet/Home/issues/7389
by @PureKorne

Hi 👋 

I'm trying to see if it's possible to package a nuget from a `.csproj` where the package type is a `Template`.

---

NuGet product used: `VS UI` | `dotnet.exe`
dotnet.exe --version: `2.1.403`
VS version: `15.8.7`
OS version (i.e. win10 v1803 (17134.345)):

So I'm trying to [create a new custom template using the `dotnet new` template](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template). Part of the steps include creating a `.nupkg`. [The example documentation](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#pack-the-template-into-a-nuget-package) says to do this using `nuget pack <nuspec file>`.

I'm trying to do this with `dotnet pack` instead. `nuget.exe` isn't in my path (yes, I know I can download it, etc) so I'm trying to do with the existing tools possible / least amount of friction.

In the `.nuspec` file it says we need to define the nuget package to be a  `template` like:

```
<packageTypes>
  <packageType name="Template" />
</packageTypes>
```

Is there a way we can define this in a `.csproj` file, so then I might be able to use `dotnet pack` instead?

by @rrelyea 
It looks like setting the csproj property "PackageType" will be persisted as a PackageType when dotnet pack is used. NuGet.Build.Tasks.Pack.Targets defines a Target named "GenerateNuspec" which will pass $(PackageType) into the PackTask.

If this works well, or even better, please consider doing a doc PR or a doc issue to "The example documentation" page you link to in your initial comment.

[Edited by gewarren to add document details below.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
This was already completed with the rewrite of the tutorials a while back. Cheers!
