### ISSUE TITLE
Split mixed C# and VB topics 

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1797]
On MSDN, there were topics for C# and VB that were combined: https://msdn.microsoft.com/en-us/library/hh334523.aspx

There was a big effort to split them but some continue to be mixed even though they're under a specific guide. For example: [Null-conditional Operators (C# and Visual Basic)](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/null-conditional-operators.md) is under the C# Guide.

@BillWagner do you think this should become a project and we review each topic separately?

/cc @GuardRex @tompratt-AQ

**Comment by tompratt-AQ** [comment]
If the goal is to completely split these topics into both languages, then it makes sense to review each one and do that. What is the argument for not doing it? Is there a worry that it will lead to too much duplication? Or, there won't be enough content for one language vs. the other?

**Comment by rpetrusha** [comment]
I don't think that we need to review each topic separately -- or, to put it another way, the review in the PR should be adequate. We mostly need to identify them. 
I've also added an [interpolated string identifier](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/tokens/interpolated) topic for C# that should have a VB equivalent but doesn't. The topics would be identical (both use $"..." to indicate an interpolated string) except for the VB code example.

**Comment by mairaw** [comment]
Ok, so let's work on putting a list together first.

**Comment by BillWagner** [comment]
There's another project underneath (and later) under this. The migration split the topic, but copied them into both destination trees. I think we'll see C# explanations in the VB version and vice-versa in the markdown text. While less of a problem, that should eventually be addressed. 

The first batch should be identifying where a topic moved to one guide but did not make it into the other language.

**Comment by mairaw** [comment]
@tompratt-AQ let's first come up with the list of articles for the first batch and work on those!

**Comment by tompratt-AQ** [comment]
I created the attached list by looking at all C# files that contained Visual Basic, VB, or ```vb, all Visual Basic files that contained C# or ```csharp, and all files that contained "C# and Visual Basic". 

From those I came up with the following sections in this spreadsheet: Two files that give us a clue to files we should look at for separation, the "first batch" as described in this PR, files that have a C#, VB and a combined topic that still exists, and files with possible separation problems and/or things to fix.  
[First Batch and Beyond.xlsx](https://github.com/dotnet/docs/files/883547/First.Batch.and.Beyond.xlsx)

**Comment by rpetrusha** [comment]
@tompratt-AQ I commented on the items in your spreadsheet but wasn't able to add it to your existing spreadsheet, so I'm attaching it here.
[First.Batch.and.Beyond Comments.xlsx](https://github.com/dotnet/docs/files/883803/First.Batch.and.Beyond.Comments.xlsx)

**Comment by mairaw** [comment]
A few additional comments (some refer to @rpetrusha's comments):
- https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/keywords/nameof still has VB in it
- https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/interop/walkthrough-office-programming: perhaps should this be moved to [vsto](https://docs.microsoft.com/en-us/visualstudio/vsto/create-vsto-add-ins-for-office-by-using-visual-studio) docs and we just link to them from our docs? /cc @kempb 
- https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/concepts/linq/how-to-retrieve-a-single-child-element-linq-to-xml - if we do this, it should be done across the board for all that section. This content used to be under the Framework content back in the day: https://msdn.microsoft.com/en-us/library/bb397926(v=vs.90).aspx. It seems to make sense to move this to the cross-plat section instead. But it would be a major task.
