### ISSUE TITLE
using static is not a keyword.  It is two keywords.

### ISSUE THREAD

**Issue by gafter** [dotnet/docs#17970]
The list at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ is not correct because it lists `using static` as a keyword.

`using static` is not a keyword.  It is two keywords. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/#feedback)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @gafter,
Thanks for posting this issue, I've created a pull request to [update the docs accordingly](https://github.com/dotnet/docs/pull/17982) and will let you know once they're updated.
