### ISSUE TITLE
Struct example

### ISSUE THREAD

**Issue by FrankHileman** [dotnet/docs#17981]
I would like to see an example using a struct as well as a class. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref#reference-return-values)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @FrankHileman,
Thank you for raising this concern and posting an issue. I do see that ref returns show the syntax for how to signify a return value is a ref - and it is showing a `Decimal` which is a `struct`. I assume
