### ISSUE TITLE
Document GCHeapStats_V2 Runtime Event

### ISSUE THREAD

**Issue by sywhang** [dotnet/docs#17995]
The GC now has a "Pinned Object Heap" which will be reported as part of the GCHeapStats_V2 event. The current section on https://docs.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events#gcheapstats_v1-event only documents the V1 Event and doesn't include the V2 event payload. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e864e1e3-c8ed-a993-8e72-372e30f6610c
* Version Independent ID: eb24522a-de26-44e6-75fc-4a332fe45501
* Content: [Garbage Collection ETW Events](https://docs.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events#gcheapstats_v1-event)
* Content Source: [docs/framework/performance/garbage-collection-etw-events.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/garbage-collection-etw-events.md)
* Product: **dotnet-framework**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@sdmaclea This article is in the framework area, but is this work related to .net core/5 only?

**Comment by sdmaclea** [comment]
Yes.  It is probably part of our .NET Core documentation debt.
