### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by MaddHatters** [dotnet/docs#17999]
In the Specifying assembly binding in configuration files section, the configuration for myThirdAssembly states that the Publisher policy can be set only in the app configuration file. Can it also be set in the machine configuration file?

See snippet below: [edited by gewarren to add code fencing for readability]

```
&lt;configuration&gt;
  &lt;runtime&gt;
    &lt;assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"&gt;
...
...
...
      &lt;dependentAssembly&gt;
      &lt;assemblyIdentity name="myThirdAssembly"
        publicKeyToken="32ab4ba45e0a69a1"
        culture="en-us" /&gt;

This can also be set in the machine configuration file correct?

        &lt;!-- Publisher policy can be set only in the app
          configuration file. --&gt;
        &lt;publisherPolicy apply="no" /&gt;
      &lt;/dependentAssembly&gt;
    &lt;/assemblyBinding&gt;
  &lt;/runtime&gt;
&lt;/configuration&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5bf2185-770f-598c-157b-784bfca2d888
* Version Independent ID: 7568b276-9bdf-946b-3f2e-3096922a6886
* Content: [Redirecting Assembly Versions](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions#specifying-assembly-binding-in-configuration-files)
* Content Source: [docs/framework/configure-apps/redirect-assembly-versions.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/redirect-assembly-versions.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@maryamariyan Can the [publisherPolicy element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/publisherpolicy-element) be specified in a machine.config file or just an app.config file?
