### ISSUE TITLE
Some read-only properties can be assigned to

### ISSUE THREAD

**Issue by v-kydela** [dotnet/docs#17996]
The wording here is confusing because it doesn't specify that the reason it can't be assigned to is that it's not an auto-property. If you're using a getter-only auto-property then you can assign to it in a constructor even though it's also "read only."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a48ba32c-fe4e-343a-61c7-2bc83cc28bed
* Version Independent ID: 9fdc77d6-4be6-5255-c7df-f45aea0777ff
* Content: [Compiler Error CS0200](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0200)
* Content Source: [docs/csharp/misc/cs0200.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0200.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @v-kydela,
Thank you for raising this concern and posting an issue. I'll take a look at clarifying this a bit more.

**Comment by v-kydela** [comment]
I'm happy this was addressed so quickly but it looks like the error message itself wasn't changed at all

**Comment by pkulikov** [comment]
> the error message itself wasn't changed at all

Do you mean the very first sentence in the article? Then it's not the docs that can change that message. That message is the compiler error message. If you think that message should be changed, submit the issue in the Roslyn (C# compiler) repo: https://github.com/dotnet/roslyn
