### ISSUE TITLE
Document the C# compiler /pathmap command line flag

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1800]
Replacing https://github.com/dotnet/roslyn/issues/18071

Please see that issue for details on the new flag.

The new documentation should be under this directory https://github.com/dotnet/docs/tree/master/docs/csharp/language-reference/compiler-options

/cc @gafter

**Comment by GuardRex** [comment]
@mairaw They still haven't started work on the revised syntax for the switch; therefore, I suspect this is going to run out past next week. Do u want to re-assign?
