### ISSUE TITLE
String concatenation tolerates null strings

### ISSUE THREAD

**Issue by jbnx42** [dotnet/docs#18005]
It might be worth a quick mention that the string concatenation operator will tolerate a null string for either operand and will treat it as an empty string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e31f06e-936e-d0c7-9dc0-9d10fd8a0dd9
* Version Independent ID: 43899711-a922-8180-25e6-d52af245846d
* Content: [+ and += operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-operator#feedback)
* Content Source: [docs/csharp/language-reference/operators/addition-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/addition-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@BillWagner could you please assign this to me
