### ISSUE TITLE
"Project file does not exist" when running "dotnet run"

### ISSUE THREAD

**Issue by tkhalifeh** [dotnet/docs#18008]
"dotnet run --project sample1" should be "dotnet run --project sample1.csproj"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2
* Version Independent ID: fdb655a4-cff4-6c67-7244-673760379663
* Content: [Get started with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/get-started?tabs=windows#feedback)
* Content Source: [docs/core/get-started.md](https://github.com/dotnet/docs/blob/master/docs/core/get-started.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @tkhalifeh,

Thank you so much for posting this issue, in looking at the docs - they seem to be accurate. I was testing this out and found that the only way that the *.csproj* is required is when you're scoped to the subdirectory that the `dotnet run` command creates. For example, if you were to `cd` into the created directory -- you would then need to provide the `*.csproj*. Have a look here, if you agree -- I'll close this issue. Thanks

![image](https://user-images.githubusercontent.com/7679720/80237645-b3192100-8622-11ea-95e9-70e18348bc8c.png)

**Comment by tkhalifeh** [comment]
Hi,

Thanks for the detailed explanation, I totally agreed, will close the issue.
