### ISSUE TITLE
Is it possible to disable default interface methods with a compiler flag?

### ISSUE THREAD

**Issue by adamstyl** [dotnet/docs#18010]
I have seen some awful (Java) code abusing default interface methods. It's sad to see this making it to C# 8 but now it's done. Is there any way to tell the compiler to not support default methods? Produce an error instead or anything similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3753657-9f0f-4e68-abde-5f461099cb6e
* Version Independent ID: f7bd9eb0-1653-15fd-5f0e-dc0ee5c3bf88
* Content: [Safely update interfaces using default interface methods in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-methods-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-methods-versions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
/cc @jcouv 

Is there a feature flag for DIM?

**Comment by jcouv** [comment]
No, the only ways to prohibit DIM are to stay in C# 7, or to implement an syntax analyzer.

**Comment by BillWagner** [comment]
Thanks @jcouv 

I'll close this as an answered question.

**Comment by adamstyl** [comment]
@jcouv @BillWagner thanks for the input.
