### ISSUE TITLE
Review `dotnet-install scripts` documentation

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#18016]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by tdykstra** [comment]
This article has several [outstanding issues](https://github.com/dotnet/docs/issues?utf8=%E2%9C%93&q=is:issue+is:open+a2e484a9-5e0c-eb3e-1413-7b507c4fa07d+in:body).

**Comment by marcpopMSFT** [comment]
@donJoseLuis I believe the install script documentation was reviewed relatively recently but I figured I'd ping you in case you wanted to take a look.  There are a couple of issues linked to these docs that we can help investigate or you can just close this issue out and rely on the previous review.

**Comment by tdykstra** [comment]
@donJoseLuis ping

**Comment by tdykstra** [comment]
@marcpopMSFT Is there someone else who could review this doc?

**Comment by marcpopMSFT** [comment]
@tdykstra, @donJoseLuis owns the install script now and I think his team should review the documentation.  Will on my team can help if needed.

**Comment by tdykstra** [comment]
cc @dotnet/install-scripts-maintainers

**Comment by bozturkMSFT** [comment]
I commented on the issues. Besides those, docs look good to me.

**Comment by tdykstra** [comment]
Thanks @bozturkMSFT! I'll address the other issues as needed and close this one.
