### ISSUE TITLE
Bad practices in example

### ISSUE THREAD

**Issue by sdanyliv** [dotnet/docs#18023]
The following function calls may enumerate sequence more than twice.
if (source.Count() == 0) ...
sortedList.Count()
sortedList.ElementAt(itemIndex) ...

I think it is not good to expose for beginners such ineffective realization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9dc3a1f-945b-18b4-d962-467f7ca49d95
* Version Independent ID: 5cf4ba6d-9afc-77bd-0a70-4ffd8e9526c0
* Content: [How to add custom methods for LINQ queries (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @sdanyliv 

I'll add it to the next sprint. A similar sample is in the [VB guide](https://docs.microsoft.com/dotnet/visual-basic/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries) and should also be updated at the same time.

**Comment by BillWagner** [comment]
This issue was fixed in #18560

**Comment by sdanyliv** [comment]
@BillWagner, I hope you have not missed my comment https://github.com/dotnet/docs/pull/18560#issuecomment-637022362

**Comment by BillWagner** [comment]
Thanks @sdanyliv 

Reopening, and assigning to me.
