### ISSUE TITLE
The use of data type "string?" in the examples seems very unnecessary

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#18042]
Correct me if I'm wrong, but I thought an ordinary "string" was already a reference type, which means it can already be assigned a value of null.  Therefore, the idea of a nullable "string?" in the examples is redundant, unnecessary, and confusing.

It only makes sense for value types like "int" or "bool" to be nullable as "int?" or "bool?", since the ordinary versions of those data types cannot be null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jvandertil** [comment]
Looks like they are using C# 8 nullable reference types in the example documentation, for details you can check: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types

**Comment by BillWagner** [comment]
Thanks for asking this @matthew45052 

We are using the new C# 8 nullable reference feature in that sample, as @jvandertil points out.

I'll close this as an answered question.
