### ISSUE TITLE
Ternary In Interpolated String Doesn't Work As Expected

### ISSUE THREAD

**Issue by rich-newman** [dotnet/docs#18066]
The code below is from this page (in several places):
```csharp
public override string ToString() => $"The light is {isOn: \"on\", \"off\"}";
```
It outputs 'The light is True' or 'The light is False', in .NET Core 3.1 (C# 8.0) and .NET Framework 4.8 (C# 7.3).  

I don't think there is a way of fixing this using that syntax (?).  If we want it to say 'The light is on' or 'The light is off' we need:
```csharp
public override string ToString() => $"The light is {(isOn ? "on" : "off")}";
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 646641fc-f698-5633-5f6b-2eb5f0c03d7f
* Version Independent ID: c6e0d402-962e-4b6c-b1f4-4e91eb585692
* Content: [Create mixin types using default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/mixins-with-default-interface-methods)
* Content Source: [docs/csharp/tutorials/mixins-with-default-interface-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/mixins-with-default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @rich-newman You are correct. 

I've added this to the current sprint to address.
