### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#18062]
"... at unspecified time ..."

was probably meant to be:

"... at an unspecified time ..."

or:

"... at some unspecified time ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdb964-4c04-d174-e879-e3a2d176809b
* Version Independent ID: 96df2e76-70b0-4873-4acc-d6bae51986b4
* Content: [new operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator)
* Content Source: [docs/csharp/language-reference/operators/new-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/new-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @matthew45052 I've submitted a PR to fix this.

As an aside, when you find these, you can click the "edit" icon on the page (it looks like a pencil) and submit the PR yourself. This is useful when the fix takes no more time than describing the issue.
