### ISSUE TITLE
Enhancements to the dotnet new command docs

### ISSUE THREAD

**Issue by Forgind** [dotnet/docs#18078]
NUnit 3 Test Item, Razor Component, MVC ViewStart, dotnet gitignore file, NuGet Config file, dotnet local tool manifest file, Web Config, and Solution File are lacking links from the table to a more concrete description of how to use it. I think the reason is that they have no parameters the way others do, but it would be good to say that explicitly so people aren't confused.

ASP .NET Core in the table mentions an alternate short name, but although that at least does something, that isn't listed as an option when running `dotnet new --help`.

`-i` is often used to make something interactive. That isn't an option for `dotnet new`, but that might confuse some people.

Should commands with optional parameters have that specified somehow? I was looking, for example, at ``list`, which takes an optional name for templates it should try to match. This is especially relevant since some, like --uninstall, list the optional parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by IEvangelist** [comment]
Hi @Forgind,
Thank you for posting this issue. Could you please provide a bit more information?

I believe that you're referring to this document - is that correct?
https://docs.microsoft.com/dotnet/core/tools/dotnet-new

If so, you're asking specifically for examples of the items that do not currently have examples. Additionally, you're asking whether the commands should specify optional parameters somehow - is that right?

**Comment by Forgind** [comment]
> I believe that you're referring to this document - is that correct?
> https://docs.microsoft.com/dotnet/core/tools/dotnet-new

Yes
 
> If so, you're asking specifically for examples of the items that do not currently have examples. Additionally, you're asking whether the commands should specify optional parameters somehow - is that right?

Almost. I know the ones I listed shouldn't have optional parameters listed, which means they're easier to use, but if I want to know how `dotnet new wpf` works, for example, I click on `wpf`, and it tells me about the optional parameters. For those without optional parameters, a user might wonder if there are optional parameters that were missed or if there are no optional parameters, so my (poorly articulated) suggestion is to add a section at the bottom for those that don't currently have links. That section can specify that there are no optional parameters. In other words, I imagined every entry in the table looking the same, just with some options pointing to a section that affirms that there is no more information to be had.

The four paragraphs in my issue are unrelated, so the fourth is more in line with what you asked. I was thinking `dotnet new --list` could look more like `dotnet new --list <TEMPLATE>` or `dotnet new --list <TEMPLATE?>` or `dotnet new --list <OPTIONAL_TEMPLATE>`.

**Comment by IEvangelist** [comment]
As for the doc suggestions, I would encourage you to create a pull request add a reference to this issue - as those changes are minor. As for the suggestion about changing how the `dotnet new --list` functionality might be improved, you'd have to open an issue in their repo: https://github.com/dotnet/sdk.
