### ISSUE TITLE
PublishSingleFile can't run as windows service

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18072]
@cnzhnet commented on [Fri Apr 24 2020](https://github.com/dotnet/docs.zh-cn/issues/569)

When I use PublishSingleFile mode to publish an application,  the application cann't run as Windows Service: method UseWindowsService() does not work

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [.NET Core 3.0 的新增功能](https://docs.microsoft.com/zh-cn/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

---

@srvbpigh commented on [Fri Apr 24 2020](https://github.com/dotnet/docs.zh-cn/issues/569#issuecomment-618947826)

Hello, @cnzhnet
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by IEvangelist** [comment]
Hi @cnzhnet,
Thank you for posting this issue, I'll investigate this and get back to you soon.

**Comment by cnzhnet** [comment]
> Hi @cnzhnet,
> Thank you for posting this issue, after investigating this - I cannot recreate the issue. It seems to work perfectly.
> 
> I created a new worker project:
> 
> ```
> dotnet new worker -o Work.It
> ```
> 
> Changed directories into the newly created project and opened Visual Studio Code:
> 
> ```
> cd Work.It && code .
> ```
> 
> Change the _Work.It.cspoj_ file to look like this:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Worker">
> 
>   <PropertyGroup>
>     <TargetFramework>netcoreapp3.1</TargetFramework>
>     <PublishSingleFile>true</PublishSingleFile>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.3" />
>     <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.3" />
>     <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="3.1.3" />
>   </ItemGroup>
> </Project>
> ```
> 
> Update the _Program.cs_ to look like this:
> 
> ```cs
> using System.Threading.Tasks;
> using Microsoft.Extensions.DependencyInjection;
> using Microsoft.Extensions.Hosting;
> using Microsoft.Extensions.Logging;
> 
> namespace Work.It
> {
>     public class Program
>     {
>         public static Task Main(string[] args) =>
>             CreateHostBuilder(args).Build().RunAsync();
> 
>         public static IHostBuilder CreateHostBuilder(string[] args) =>
>             Host.CreateDefaultBuilder(args)
>                 .UseWindowsService()
>                 .ConfigureLogging(loggerFactory => loggerFactory.AddEventLog())
>                 .ConfigureServices((hostContext, services) =>
>                 {
>                     services.AddHostedService<Worker>();
>                 });
>     }
> }
> ```
> 
> Publish the file, like this:
> 
> ```
> dotnet publish Work.It.csproj -r win-x64 -p:PublishSingleFile=true
> ```
> 
> Then create the Windows Service, open Services and start it... logs ended up in the Event Viewer - so this must be working.
> 
> ```
> sc create TestWorkerService binPath=.\Work.It\bin\Debug\netcoreapp3.1\win-x64\publish\Work.It.exe
> [SC] CreateService SUCCESS
> ```
> 
> ![image](https://user-images.githubusercontent.com/7679720/80532412-baf9fd80-8961-11ea-9eb6-02a90b1b9e68.png)

I use Microsoft.NET.Sdk.Web instead of Microsoft.NET.Sdk.Worker. I want to deploy the asp.net core mvc project to Windows Service while using the PublishSingleFile mode to make the file structure look less complicated

![image](https://user-images.githubusercontent.com/13212598/81673649-8c5e4580-947e-11ea-8497-18b3c1b492af.png)

![image](https://user-images.githubusercontent.com/13212598/81673772-b7e13000-947e-11ea-82b9-b4cc5fa2a42f.png)

**Comment by cnzhnet** [comment]
Above code, when I close PublishSingleFile, Windows Service can work.

**Comment by IEvangelist** [comment]
> Above code, when I close PublishSingleFile, Windows Service can work.

Hi @cnzhnet - does this mean that it is now working for you?

**Comment by cnzhnet** [comment]
I'm not sure that a web app based on the Razor Pages and MVC framework with the Microsoft.NET.Sdk.Worker SDK will work correctly, as Microsoft doesn't specify. So there's no attempt to change to the Microsoft.NET Sdk.Worker SDK.  So at the moment I can only cancel ThePublicSingleFile mode for it to work properly!

**Comment by IEvangelist** [comment]
Hi @cnzhnet,

I believe I have a better understanding now - thank you for your patience. If you have a Razor Pages and MVC framework application, it cannot be a Windows Service (to my knowledge). This is only applicable for a Worker. Now, publishing as a single file for a worker is demonstrated above. We're going to close this issue for now, but if you still have questions feel free to ask. Thank you
