### ISSUE TITLE
How necessary is the Dispose() null check?

### ISSUE THREAD

**Issue by matthew45052** [dotnet/docs#18085]
This is another question about null values, something I've been curious about for a long time ago.  It's about the expansion of "using" into "try { } finally".  Why the null check before calling Dispose()?

Doesn't the "new" operator always return non-null?  If a class constructor fails or if there's not enough memory to allocate an object, won't an exception be thrown?  In the "finally" example above, would it be safe to simply call:

reader.Dispose();

Does "using" only perform a null check before calling Dispose() in case it is used (no pun intended) on some arbitrary value that may not have been returned by a class constructor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
If you were writing the `finally` version yourself, yes, you could omit the null check. But the compiler also has to handle situations where the `using` statement is used with something other than the `new` operator, and in those cases, the `null` check becomes useful.

The compiler could probably omit the null check in this specific case, but I'm not sure if that optimization would be worth implementing.

**Comment by BillWagner** [comment]
Thanks for asking this question @matthew45052 
As @svick says, this example shows the code as implemented by the compiler.

I'll close this as an answered question.
