### ISSUE TITLE
Move docs repos to their own org

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/docs#1809]
Because of all the language versions of the docs (docs.zh-CN for example) the docs repos are taking over the dotnet org. I suggest moving them to their own org.

**Comment by richlander** [comment]
Good issue. 

We had the same problem in the Microsoft org. All of those docs repos moved out into their own org for this same reason. I'd like to see this repo stay in the dotnet org and for all the others to move out. If they need to move all together, then this repo can be forked into that org.

Thoughts @mairaw ?

**Comment by mairaw** [comment]
@EisenbergEffect I thought we were looking into solutions to minimize the number of localization repos needed. Is that something we still want to pursue or do we need to move the docs to a different place?

/cc @nokura

**Comment by EisenbergEffect** [comment]
Please email me and I'll fill you in.

**Comment by richlander** [comment]
From a process standpoint, we need an answer (and positive outcome) to this quite legitimate question from the community. That doesn't have to happen today, but we do need to report back on this issue in the foreseeable future.

**Comment by mairaw** [comment]
We're trimming the backlog and I'll be closing this issue since it's not a content issue. There are no plans to move the loc repos out of the dotnet org for now. But happy to bring this up with the loc and engineering team again if we have enough votes/feedback to consider this.

/cc @JasonCard

**Comment by JasonCard** [comment]
@mairaw Thank you for cc'ing me on this. I had not heard there was this request, but I see it was opened over 2.5 years ago, so hopefully this is no longer a concern. We would like to avoid having to move all the loc repos to different org if not necessary.

**Comment by mairaw** [comment]
Yes, this discussion happened before you joined the team @JasonCard.
