### ISSUE TITLE
Does UWP have a dedicated flag?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#18097]
[This](https://stackoverflow.com/a/47290509/75500) says `WINDOWS_UWP`, which does work, but can't seem to find it anywhere in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @jcouv for the answer.

**Comment by jcouv** [comment]
There is no reference to `WINDOWS_UWP` in the roslyn codebase. 
Search for that exact string on stackoverflow yield [some results](https://stackoverflow.com/search?q=%22WINDOWS_UWP%22) that may help.

**Comment by weitzhandler** [comment]
It's [here](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation#universal-windows-platform-uwp) and [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting) ([credit](https://stackoverflow.com/a/47290509/75500)).

**Comment by BillWagner** [comment]
ping @davidbritch Do you know more about the UWP flag here?

**Comment by weitzhandler** [comment]
Related: https://github.com/dotnet/docs/issues/4657.
