### ISSUE TITLE
Retrieving supported target framework versions programatically

### ISSUE THREAD

**Issue by holc-tkomp** [dotnet/docs#18105]
Is there a way to retrieve the #supported-target-framework-versions list programatically in .NET (C#)?
I'd prefer to avoid hard-coding this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
Hi @holc-tkomp,
Thank you for asking this question, and reaching out through an issue. This is a good question, and I agree - that I would rather not hard-code this lookup data either. Unfortunately, I do not believe that this is available programmatically. I'll ask around a bit, and report back - but could you please clarify how you might imagine this being available? Are you thinking exposed through some types with static data or something?

**Comment by holc-tkomp** [comment]
I would like to see some helper class, maybe within one of the `Microsoft.NETCore.*` namespaces, with static methods such as
```c#
public static string[] GetSupportedTargetFrameworks();
public static string[] GetDeprecatedTargetFrameworks();
```

Similar thing could be considered for the [Runtime identifiers](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) ([runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json)).

**Comment by IEvangelist** [comment]
Adding @terrajobst - what do you think about the idea ☝️ ?

**Comment by IEvangelist** [comment]
This issue was moved to dotnet/runtime#35671
