### ISSUE TITLE
F# API reference

### ISSUE THREAD

**Issue by Tweega** [dotnet/docs#18100]
In the new F# documentation, is there somewhere that I can find the equivalent of the API reference found at the link bellow?  I don't often need it, but when I do it can be a lifesaver.

https://github.com/MicrosoftDocs/visualfsharpdocs/tree/master/docs/conceptual

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a34c541d-29fa-6497-c851-17a7d605edc1
* Version Independent ID: 90ab1d8a-0195-e8c2-0f8d-fea3c3539098
* Content: [Language Reference - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/#feedback)
* Content Source: [docs/fsharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Yes, you can find it here: https://fsharp.github.io/fsharp-core-docs/

I will update the conceptual docs to point to it
