### ISSUE TITLE
No information provided on how to actually use the stored values

### ISSUE THREAD

**Issue by ckapilla** [dotnet/docs#18118]
It doesn't do much good to know how to store configuration values if there is no information provided on how to actually use the stored values at runtime!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa7bda7-581d-9654-c7c5-5ff0292ddfb3
* Version Independent ID: 7f32162e-ec95-0a16-7618-14b7a7c80cff
* Content: [Run-time config options - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/#feedback)
* Content Source: [docs/core/run-time-config/index.md](https://github.com/dotnet/docs/blob/master/docs/core/run-time-config/index.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks for the feedback. The articles below that page in the table of contents contain the information about the actual settings. Is that what you're looking for? For example, the compilation settings are here: https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation. Perhaps we need to point them out in the page you were looking at.

**Comment by ckapilla** [comment]
I misunderstood the purpose of this documentation. I am trying to find information on how to configure user settings in Core 3.1 and came to this page by mistake. I see now this page is about settings for the .net runtime itself and not for application settings at runtime.

**Comment by ckapilla** [comment]
Hi Genevieve,

 

thanks for your speedy reply. 

 

I see now that the page in question is about configuring the .net runtime itself, and thus the runtime itself is responsible for reading those values. 

 

I got to this page in the process of porting a .net 2x windows app to .net core 3.1 and am trying to figure out how to implement app.config and/or user settings in the 3.1 environment.

 

I have closed my issue, but if by chance you could point me to information on how to migrate app.config and/or user settings in the 3.1 environment, that would be great.

 

Chris

**Comment by gewarren** [comment]
Hi Chris, it sounds like the [ConfigurationManager](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager?view=dotnet-plat-ext-3.1) class will do what you want.

**Comment by ckapilla** [comment]
yes perfect -- thank you!
