### ISSUE TITLE
confusing navigation on mobile

### ISSUE THREAD

**Issue by natiox** [dotnet/docs#18119]
I read this page on mobile and it's not very intuitive to find the table of contents in the dropdown.  I read the page and thought, "Nice intro.  Where's the info?"  With some back-and-forth between the desktop and mobile version I was able to find the table of contents dropdown. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/#feedback)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by tdykstra** [comment]
This issue was moved to MicrosoftDocs/feedback#2851
