### ISSUE TITLE
Expression trees can't represent some new C# syntax elements

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#18134]
See https://github.com/dotnet/docs/issues/17988#issuecomment-620759030

Some of the new language elements aren't translated into expression trees. The null forgiving operator `!` is one. The null propagating operator `?.` is another. I think pattern matching switch expressions are also affected.

We should update this section to include unsupported language elements, and guidance on general use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67627978-50fb-0575-fc71-d61e124fd9db
* Version Independent ID: fef5fa5e-1fc3-d1d3-d27d-2084ec41d17f
* Content: [Expression Trees](https://docs.microsoft.com/en-us/dotnet/csharp/expression-trees)
* Content Source: [docs/csharp/expression-trees.md](https://github.com/dotnet/docs/blob/master/docs/csharp/expression-trees.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by AntonLapounov** [comment]
Expression trees have many restrictions, see all those `Error()` calls in https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs.

**Comment by Joe4evr** [comment]
Related: dotnet/csharplang#158
