### ISSUE TITLE
"null as Foo" to initialize with null.

### ISSUE THREAD

**Issue by ShadowsInRain** [dotnet/docs#18142]
Just saying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11b0afbe-c9dc-b5c7-5d0b-f1bebbfc7b1a
* Version Independent ID: fd6f943b-5bc5-7bef-a0db-16242369598b
* Content: [Anonymous Types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/anonymous-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/anonymous-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @ShadowsInRain That's one way to initialize a null value. We've generally recommended the `default` expression.

I'll close this.
