### ISSUE TITLE
Methods not inherited by  inherit the EmployeeListNotFoundException

### ISSUE THREAD

**Issue by naughtyGitCat** [dotnet/docs#18147]
```c#
class EmployeeListNotFoundException1 : EmployeeListNotFoundException
{
}
throw new EmployeeListNotFoundException1("test");

the vs for mac ide suggest " the  EmployeeListNotFoundException1 class do not have one parameter constructor function"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041f6b4c-2b7e-5332-f24e-12af7a5b07aa
* Version Independent ID: e9c2287f-1c4e-ee07-a1ff-77a3f07ce1a4
* Content: [How to: Create User-Defined Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions)
* Content Source: [docs/standard/exceptions/how-to-create-user-defined-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-create-user-defined-exceptions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Add constructor(s) to EmployeeListNotFoundException1 as shown in the example for EmployeeListNotFoundException.

**Comment by naughtyGitCat** [comment]
I am new to c#, when I use the Python3, son class can just inherit the __init___ class from the parent class. Is there a simple way to bypass define all the constructors again and again

**Comment by tdykstra** [comment]
No, you have to define the constructors but you don't have to duplicate the code in them, as constructors in the derived class can call the base class constructor.  See the discussion in [this StackOverflow post](https://stackoverflow.com/questions/3873343/can-i-inherit-constructors).

**Comment by naughtyGitCat** [comment]
Thank you very much , big help
