### ISSUE TITLE
Encoding.GetChars is used instead of Encoding.GetString

### ISSUE THREAD

**Issue by moerwald** [dotnet/docs#18149]
Docu states: "The following example illustrates the difference between using the Encoding.GetChars and Decoder.GetChars methods for decoding a Unicode byte array. The example encodes a string that contains some Unicode characters to a file, and then uses the two decoding methods to decode them ten bytes at a time. Because a surrogate pair occurs in the tenth and eleventh bytes, it is decoded in separate method calls. As the output shows, the Encoding.GetChars method"

But the code sample uses Encoding.GetString. So the above paragraph needs to be fixed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed8d30e-1432-8cd7-cd54-b96be94d91ca
* Version Independent ID: e79a1fd9-cac4-53e6-1dd7-de4e70503410
* Content: [How to use character encoding classes in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding#feedback)
* Content Source: [docs/standard/base-types/character-encoding.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-encoding.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
