### ISSUE TITLE
These are not equivalent (for value types):  `E as T`    `E is T ? (T)(E) : (T)null`

### ISSUE THREAD

**Issue by 2jacobtan** [dotnet/docs#18157]
The following do not seem equivalent (for value types?). Contrary to what is said in the article.

`E as T`
`E is T ? (T)(E) : (T)null`

![image](https://user-images.githubusercontent.com/12626411/80624063-ba568980-8a7d-11ea-9fe7-0ecb0a8168a6.png)

![image](https://user-images.githubusercontent.com/12626411/80624277-06093300-8a7e-11ea-998c-3ffe81dc716d.png)
https://repl.it/@JacobTan3/null-comparison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9004a524-b8b1-ba5e-4bc9-cacb19c5ba09
* Version Independent ID: 1bb17efe-3503-5e10-aa3e-5f29ac57a274
* Content: [Type-testing operators and cast expression - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#as-operator)
* Content Source: [docs/csharp/language-reference/operators/type-testing-and-cast.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/type-testing-and-cast.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
> The following do not seem equivalent (for value types?).

@2jacobtan why not? The following:
```csharp
using System;

class MainClass {
  public static void Main (string[] args) 
  {
      int i = 1;
      var a = i as long?;
      var b = i is long? ? (long?)i : (long?)null;
      Console.WriteLine(a == b);
  }
}
```

[outputs `True`](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ7EAICyBDASygGEAbPAZwqwG90ss4BmRpANkYBZdCosAKOEgAMAbQC6WPGADmFAJRZ6tZQwZFgWAlgC8WJAG5VagG7SpurVOqkA9lBkB+I2jWnzAI0vaCN+06xHATsHR3ltEGD/MKgIUlIXNwYhAE5+PF09D3lErABfdDygA===) (in sharplab)

If you run the same code in [try.dot.net](https://try.dot.net/), it also produces `True`.

Those use Roslyn compiler.

However, it looks like that Mono C# compiler version 4.6.2.0 produces `False`.

**Comment by IEvangelist** [comment]
Hi @2jacobtan,

Thank you for posting this issue, in taking a quick look I am seeing different result than you. The [results that I am seeing](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcDMACR2DC2A3utmbggsaebQJZTDZ3YC82SA3DbWXEgE4AFABIARCzoBnbABsA9lADmAfjbYAOmKKSZC5SoC+WsQEpuaXuX7DxLAIZ7Fq9Vp3ZHc50ZPmevG1EJZicDbDUhfVVTFhBsSO9TKAhZWVdtISFdLwNTcPiolRjsOITc5NTTYzEzC1pDdEMgA===) seem to indicate that the they do function the same.

```csharp
using System;
public class Program 
{
    public static void Main() 
    {
        int i = 1;
        Console.WriteLine($"i is long? = \"{i is long?}\"");
        Console.WriteLine($"i as long? = \"{i as long?}\"");
        Console.WriteLine($"i is long? ? (long?)i : (long?)null = \"{((i is long?) ? (long?)i : (long?)null)}\"");
    }
}
```

This is what is output:

```
i is long? = "False"
i as long? = ""
i is long? ? (long?)i : (long?)null = ""
```

**Comment by 2jacobtan** [comment]
I just tried on my computer (dotnet core) and it is fine.

Indeed, looks like this issue is specific to the Mono compiler.

(Thanks for the quick and informative response!!)

**Comment by IEvangelist** [comment]
Hi @2jacobtan,

No worries, thank you. I'm going to close this issue now. If you experience anything else that is puzzling or concerning, by all means - please post an issue.
