### ISSUE TITLE
Good to see lots of examples

### ISSUE THREAD

**Issue by theREALdebater** [dotnet/docs#18177]
After a bit of prompting from an issue, it is excellent that there are multiple examples here illustrating the typical usage of this construct, and pointing out the potential confusion it can cause (in nested situations). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b4ba4c-b602-9335-97d1-3b8ac23e6cb3
* Version Independent ID: c53ac7c0-56f8-06cb-0f06-fdfc389358bd
* Content: [break statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/break?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(break_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/keywords/break.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/break.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank for leaving this comment @theREALdebater We appreciate it.

Closing as kudos.
