### ISSUE TITLE
[discussion] Breaking up the docs repo

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#18170]
## Problem statement

As we continue to onboard more technology and areas into our repo, the size and management of the repo continues to grow. By having a lot of technologies in the repo, we limit the features of the docs platform we can use, such as versioning. The amount of content, coupled with the requirement to engage and triage every issue, means there is a lot of noise generated in areas we don't necessarily work in. Anytime we configure the docs product, change labels, or edit templates, we may impact the workflow of another team, group, or technology.

## Current repo

Right now, the repo is currently comprised of the following technology areas, represented by a folder in the `/docs` folder:

- architecture
- azure
- core
- csharp
- desktop-wpf
- framework
- fsharp
- machine-learning
- spark
- standard
- visual-basic
- whats-new

There are some other folders but they represent repo config or assets.

I'm going to try to group the folders to similar technologies.

#### Sorted by folder

| Folder           | Group         |
|------------------|---------------|
| architecture     | Books         |
| azure            | .NET (other)  |
| core             | .NET          |
| csharp           | Code Language |
| desktop-wpf      | .NET          |
| framework        | .NET          |
| fsharp           | Code Language |
| machine-learning | ML/AI        |
| spark            | ML/AI        |
| standard         | .NET          |
| visual-basic     | Code Language |

#### Sorted by group

| Folder           | Group         |
|------------------|---------------|
| architecture     | Books         |
| csharp           | Code Language |
| fsharp           | Code Language |
| visual-basic     | Code Language |
| azure            | .NET (other)  |
| core             | .NET          |
| desktop-wpf      | .NET          |
| framework        | .NET          |
| standard         | .NET          |
| machine-learning | ML/AI        |
| spark            | ML/AI        |

### Breaking up the repo

The following sections represent new repos that would be created based on the content of this repo:

### Group: Books

_To do: someone with knowledge of this area._

### Group: Code Language

_To do: someone with knowledge of this area._

The .NET language documentation is not necessarily replated to any other technology group. While versions of .NET implement specific language versions, the language isn't dependent on the documentation of .NET.

This area could be moved to its own repo.

### Group: .NET

This repo remains here and the other content groups are moved into other repos.

As .NET moves on and and .NET Framework (v4)/.NET Standard 2.0 are frozen and away from .NET Standard, .NET 5 becomes the latest .NET design, further leaving .NET Framework behind. As no new features go into .NET Framework and .NET Standard, yet they remain supported, future documentation efforts will be done on areas supported by .NET 5 (or .NET Latest).

As a team, we are currently focused on writing content for:

- .NET Core/5
- .NET Core/5 Desktop: WPF/WinForms
- Azure integration

We aren't focused on:

- .NET Framework
- .NET Framework Desktop: WPF/WinForms

Regarding the `standard` folder which represents common concepts shared both by .NET Framework and .NET 5/Core. This content will be handled by the .NET 5 content planning, but my thoughts are listed here: The `standard` folder content moves into .NET Core/5 (or is renamed something other than standard to lessen confusion with .NET Standard) and is focused in that context. The areas where this content is different in .NET Framework is called out and annotated.

The Azure area is currently small and could probably continue to exist in this repo as our team is the primary owner of it.

We can also implement versioning for the CLI Reference in the repo. This way we can keep copies of the CLI commands by version of the CLI instead of having massive tables and tabs, and potentially erasing content about old versions we don't necessarily care about. Further, conceptual information can be versioned based on the CLI version if required.

One area where this would have been useful is the change from .NET Core 1.x to 2.x where a lot of the project files and references were all changed to a new system. While 1.x is not supported and we recommend customers move away from it to the latest version, some of that content is useful to some customer somewhere who will be abandoned when we remove it. With versioning, we don't need to remove content and we can ensure customers that the documentation won't abandon them.

### Group: ML/AI

_To do: someone with knowledge of this area._

## Thoughts

There are currently a few projects in progress that we need to consider.

1. Consolidation of the LINQ to XML content from language areas to the .NET area.
2. Snippets are being further migrated from the _samples/snippets_ folder to a folder near the article referencing the snippet.

Until in the projects listed above are completed, it wouldn't be a good time to break up the repo. However, we can continue to discuss.

## Outstanding questions

- Maybe more issue feeds can be created and used (links to issue queries based on labels). This still requires that we have a feed that omits results from the other feeds and someone watches those feeds.

## Benefits

- It's possible that with individual repos, those repos could be versioned along with the product they are documenting, for example, versioning CLI reference content.

- Less noise (issues/PRs/alerts) for members of the individual repos.

**Comment by mairaw** [comment]
The only drawback I can think of is during consolidation efforts like the LINQ to XML project that we're doing right now. Instead of dealing with PRs in a single repo, now you'd have to coordinate massive content moves between different repos. And because the content is not on the same docset, the BI data cannot flow to the redirected articles.

But I see the appeal to have smaller repo sizes and versioning turned on.

**Comment by Thraka** [comment]
@mairaw Thank you for pointing that out. I've appended that information to the original comment.

**Comment by Thraka** [comment]
ping for thoughts @luisquintanilla @natke

**Comment by tdykstra** [comment]
There's a lot of overlap/interconnections between the .NET and Code Languages areas.  What would be the downside of keeping those together in one repo? If versioning is the main motivation for splitting them, I'm not sure that the benefits of splitting them outweigh the disadvantages.

**Comment by luisquintanilla** [comment]
Thanks for the mention @Thraka . Removed Natalie, since she's no longer with us :(. I'll take a look and provide my thoughts.

**Comment by BillWagner** [comment]
First, I like the way you've presented this @Thraka 

I have one major concern with splitting the repo in general: We've learned (sometimes through painful experience) that coordinating work across repositories has a high overhead. While @jffriend can answer better, I don't think that's going to get easier. That will become a particular pain point on any changes to the .NET hub pages and overview sections.

If that concern can be addressed, I like having more smaller repos, and I like the general organization you've presented.
