### ISSUE TITLE
Authentication to wcf service using dotnet-svcutil tool

### ISSUE THREAD

**Issue by bekakst** [dotnet/docs#18178]
Do you have and CLI command where it is possible to provide username and password credentials to connect and add service reference to project? Thanks

[Edited by gewarren to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [WCF svcutil tool overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@bekakst The article indicates that you should leave feedback on https://github.com/dotnet/wcf/issues/new
