### ISSUE TITLE
.NET core hosting: how to instantiate objects, call members functions ?

### ISSUE THREAD

**Issue by gabrieldevillers** [dotnet/docs#18174]
The [current](https://github.com/dotnet/docs/blob/08a439eeacd39afb057107afa9b38caf32aee441/docs/core/tutorials/netcore-hosting.md) documentation does not tell whether instantiating objects and calling member functions is impossible or just out of scope for this tutorial. I searched a lot online and found no more information on that.

This is something which is possible to do with Mono (using `mono_object_new` and `mono_runtime_invoke` according to https://www.mono-project.com/docs/advanced/embedding/).

Is this something that is not currently possible with .NET core ? Do you think this will be possible in the future, and when approximately would you expect it to be implemented ?

This feature is appealing because embedding C# is the best option I found to call C# from C++ in a cross-platform way: 

- COM and /clr are Windows only
- reverse P-Invoke seems convoluted
- [.NET DllExport](https://github.com/3F/DllExport) does [support .NET core](https://github.com/3F/DllExport/issues/90) but it is not an official dotnet component (problematic for long term maintenance) and it is [not obvious]([https://github.com/3F/DllExport/issues/63) that it is usable/used on Linux
- (edited 2020-06-09) CoreRT could also be a candidate but it is [not clear it will be maintained](https://github.com/dotnet/corert/issues/7200) in the long term, nor if it [actually can build native DLLs ?](https://github.com/dotnet/corert/issues/1285)

Thanks in advance. 

[Edited by gewarren to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET Core runtime host - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **tdykstra**

**Comment by Thraka** [comment]
@mjrousos Perhaps you can comment?

**Comment by gabrieldevillers** [comment]
@mjrousos I would be really helped by any comment, even just "that's not planned" or "that's not a good idea, look at X instead".

**Comment by maapp** [comment]
Any news? I'd also be interested :)

**Comment by Thraka** [comment]
Sent an email to @mjrousos

**Comment by mjrousos** [comment]
I believe .NET Core hosting APIs can only call static managed methods, but I haven't worked on hosting recently so it's possible things have changed. @AaronRobinsonMSFT, are you the right person to ask if this is still the case or if there are now ways to instantiate managed objects directly from .NET Core hosting APIs?

As far as I know, the recommendation would be to have a static managed entry point that does the necessary object instantiation, calling of instance methods, etc.

**Comment by AaronRobinsonMSFT** [comment]
>As far as I know, the recommendation would be to have a static managed entry point that does the necessary object instantiation, calling of instance methods, etc.

@mjrousos Yes. That recommendation is still correct. As @gabrieldevillers mentions there is the COM/`IUnknown` approach but that is presently only supported for Windows. The new `ComWrappers` API in .NET 5.0 has been [requested to be supported cross-platform](https://github.com/dotnet/runtime/issues/36582). That would enable the `IUnknown` ABI in a cross-platform way.

/cc @jkoritzinsky @elinor-fung

**Comment by gabrieldevillers** [comment]
I updated my initial comment to mention CoreRT which might also be a possibility to call C# from C++ in a cross-platform way (I do not know what @MichalStrehovsky  or @jkotas would think of this idea). Droping reflection could be an acceptable tradeoff for us given that we would write new code.

**Comment by AaronRobinsonMSFT** [comment]
@gabrieldevillers The problem isn't necessarily calling C# from C++, but rather interacting with an object in a "natural" (read OOP) manner that is troublesome. An example of consuming C# from native code is https://github.com/AaronRobinsonMSFT/DNNE or loading the CLR manually and getting a delegate - see https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr/src.

The ability to interact with objects in a "natural" way would require some kind of embedding API or building up an `IUnknown` type of solution. Mono's embedding API is similar to JNI which is a valid approach. We are still considering what options make sense for CoreCLR. CoreRT does contain some interesting tech that tends to migrate into CoreCLR so something out of there is also an option.

**Comment by gabrieldevillers** [comment]
Thanks for these explanations, they are very helpful. I will try to go with (2) and maybe do some benchmarks when I have time to see the impact of the pinning on the C# performance (but I suspect this will be very application-specific).

Do you think that the pinning cost could be reduced by adding 1 level of indirection in C# made of small objects holding the reference to the "real" C# objects ? An pool of arbitrary size of these small objects could be created at the very beginning of the program and then be recycled as the "real" C# objects are deleted/created. This way the "real" C# objects would never be pinned and could be moved around in memory to protect the cache, only the "small objects" would be pinned and (supposedly) the performance cost would be lower as they would be tightly packed and at the "start" of the memory.

**Comment by jkotas** [comment]
There should be no pinning involved when passing GCHandles around. The code snippet above has a bug. The `NewFoo` method should be:

```
public static IntPtr NewFoo()
{
    return GCHandle.ToIntPtr(GCHandle.Alloc(new Foo()));
}
```

The GCHandles are very similar to your pinned small object idea. They are small, never move around, and allocated in a different part of memory than regular objects to avoid impacting performance.

**Comment by gabrieldevillers** [comment]
Thanks @jkotas  So to be sure I understood: pinning is not needed in this case, but still useful in other cases like I/O to a C# buffer from C ?

**Comment by jkotas** [comment]
Right.
