### ISSUE TITLE
transitive dependencies order

### ISSUE THREAD

**Issue by VikasAgarwal1984** [dotnet/docs#18175]
What will be the order of transitive dependencies displayed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8400fd6a-d987-1056-283f-9364fbce3c86
* Version Independent ID: 3d4b052c-33fa-cc83-4df6-4a3341f12763
* Content: [dotnet list package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package#feedback)
* Content Source: [docs/core/tools/dotnet-list-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-list-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@nkolev92 Do you know the answer to this question?

**Comment by VikasAgarwal1984** [comment]
What i found was that they are sorted alphabetically and currently did not get hierarchical view. I am not sure if there is some other tooling around to get hierarchical view.

**Comment by nkolev92** [comment]
It's always alphabetical.

@VikasAgarwal1984 the tree creation would need to be it's own feature :) 

You can file an issue at NuGet/Home for that.
