### ISSUE TITLE
C# compiler language version missing "default" value

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/docs#18176]
The page describing language version chosen by the compiler includes `latest`, `latestMajor`, but does not describe `default`. AIUI, this is equivalent to `latestMajor`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
See also https://developercommunity.visualstudio.com/content/problem/989490/langversion-default-for-framework-projects-might-u.html?childToView=1004377#comment-1004377
