### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by chetan21k** [dotnet/docs#18182]
Nice. Can be little bit pictorial if possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [A Tour of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/#feedback)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @chetan21k  I'm planning on updates to this content this month. I'll look into ways to enhance this.
