### ISSUE TITLE
Polymorphic deserialization example fails on valid JSON

### ISSUE THREAD

**Issue by Ecroyd** [dotnet/docs#18201]
The Polymorphic deserialization example on the following url fails on valid JSON

> Title: How to write custom converters for JSON serialization - .NET
> URL: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?view=netcore-3.0#feedback

In JSON, An object is an unordered set of name/value pairs (ref https://www.json.org/json-en.html). This means that the JSON from the example:
`[
  {
    "TypeDiscriminator": 1,
    "CreditLimit": 10000,
    "Name": "John"
  },
  {
    "TypeDiscriminator": 2,
    "OfficeNumber": "555-1234",
    "Name": "Nancy"
  }
]`
Is equivalent to the following:
`[
  {
    "CreditLimit": 10000,
    "TypeDiscriminator": 1,
    "Name": "John"
  },
  {
    "OfficeNumber": "555-1234",
    "TypeDiscriminator": 2,
    "Name": "Nancy"
  }
]`
This is because the order of the properties in the object does not matter in JSON. Javascript implementations are fully entitled to take in the first example and return the second example and expect it to be valid.

However the example code will throw an exception if the first property name is not "TypeDiscriminator". 

Please add a warning that the example code requires JSON object name/value pairs to stay in order even though this is not required in JSON, or amend the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?view=netcore-3.0#feedback)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Ecroyd Thanks for pointing this out, we'll add a note about this limitation of the code.

@steveharter FYI
