### ISSUE TITLE
Nullable Boolean logical operators

### ISSUE THREAD

**Issue by gosiaborzecka** [dotnet/docs#18204]
*  Operator '&' is ambiguous on operands of type '&lt;null&gt;' and '&lt;null&gt;'
*  Operator '|' is ambiguous on operands of type '&lt;null&gt;' and '&lt;null&gt;'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d2d3240-ed65-94f2-335b-3ea483c51a5d
* Version Independent ID: 91eaa72e-c2fc-e0d3-ca11-994aadf02271
* Content: [Boolean logical operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#feedback)
* Content Source: [docs/csharp/language-reference/operators/boolean-logical-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/boolean-logical-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this @gosiaborzecka 

I need more information about what you think should change here. I don't see the ambiguity.  This article includes the table from [Nullable boolean operators](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#nullable-boolean-logical-operators) clause in the standard. The result would be `null` when both operands are `null`. 

Can you elaborate?

**Comment by pkulikov** [comment]
@BillWagner the following code produces the CS0034 error mentioned in the first message:

```csharp
var c = null & null;
```

However, the following compiles:

```csharp
bool? a = null;
var c = a & null;
```

And with another type as well:
```csharp
int? a = null;
var c = a & null;
```

So, I guess that in the first case (with two `null` literal values`), the compiler cannot infer the type of the operands. By the way, the compiler error message seems to be buggy.

@gosiaborzecka is this the way you've got those messages?

**Comment by gosiaborzecka** [comment]
I was looking only at the table and don't remember this text before:
```
bool? operator &(bool? x, bool? y);
bool? operator |(bool? x, bool? y);
```

The error is showing when you, for example, use simple 
`Console.WriteLine(null | null);`
