### ISSUE TITLE
Error while adding WSDL service Asp.net Core 3.1 web api

### ISSUE THREAD

**Issue by kuntalbose** [dotnet/docs#18203]
I am trying to add a service in a .net core 3.1 application .I share my steps with screen shots.

The following is from **.csproj**

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>


</Project>
```

**Step 1**
![image](https://user-images.githubusercontent.com/7402233/80788699-75c70d00-8ba7-11ea-97cb-f10cad472d9a.png)

**Step 2**
![image](https://user-images.githubusercontent.com/7402233/80788812-cd657880-8ba7-11ea-8479-6f6b57557ec2.png)

**Step 3**

![image](https://user-images.githubusercontent.com/7402233/80788880-fede4400-8ba7-11ea-8a27-1661a038b8ad.png)

**Step 4**

![image](https://user-images.githubusercontent.com/7402233/80788946-36e58700-8ba8-11ea-9dce-0ba1d7d56d71.png)

**Step 5**

![image](https://user-images.githubusercontent.com/7402233/80789031-74e2ab00-8ba8-11ea-9f6d-afa2f5e5920b.png)

[Edited by gewarren to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Add WCF Web Service Reference - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @dasetser
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@kuntalbose Have you tried using the dotnet-svcutil command instead? Just a thought.

https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x

**Comment by Thraka** [comment]
@gewarren Don't forget to remove the not triaged label when categorizing 😄

**Comment by dasetser** [comment]
@kuntalbose This looks like a bug in the tool where it doesn't work if you only have the .NET Core 3.x SDK installed. We'll work on fixing it, but for now I would suggest installing the .NET Core 2.1 SDK on your machine, which should allow this to run.

**Comment by kuntalbose** [comment]
@dasetser Thanks for your suggestion .I already report [here](https://developercommunity.visualstudio.com/content/problem/1015110/error-while-adding-wsdl-service-aspnet-core-31-web.html) .If I install 2.1 SDK on my local machine to do this ,is it need to install in server?If so then its not help full for me .Because application hosted in a shared hosting and I have no access.

**Comment by dasetser** [comment]
@kuntalbose No, you don't need to install it on the server too. You can continue to use .NET Core 3.1 on your client app as well. The only reason to install the 2.1 SDK is because that's what the tool needs to run. It won't impact the proxy that the tool generates.

**Comment by kuntalbose** [comment]
Hi @gewarren I tried with bellow code

svcutil.exe /t:code /d:C:\Users\XXXX\Desktop\SOAP\WebApplication1\WebApplication1  http://ws.jobdiva.com/axis2/services/BIData?wsdl

And its generate the code file ([BIData.zip](https://github.com/dotnet/docs/files/4605182/BIData.zip)) and required methods when when I call a method bellow error occurred

![image](https://user-images.githubusercontent.com/7402233/81491187-c4ac2b00-92a8-11ea-8604-61d9f6922dd2.png)

Can you please help me?whats going wrong

**Comment by gewarren** [comment]
@kuntalbose I see [you asked the question in the WCF repo](https://github.com/dotnet/wcf/issues/2219), which is a better place to ask the question.  I will go ahead and close this documentation issue.
