### ISSUE TITLE
Add example showing SQLitePCLRaw.provider.sqlite3

### ISSUE THREAD

**Issue by bricelam** [dotnet/docs#18215]
Using the system version of SQLite just got easier in SQLitePCLRaw version 2.0.3. We should add an example showing how to use the SQLitePCLRaw.provider.sqlite3 NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bd2bd-59d9-15dc-244c-458f3de8aa37
* Version Independent ID: c9f7dd88-1824-3935-1063-95009a8a8db1
* Content: [Custom SQLite versions - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/custom-versions?tabs=netcore-cli#feedback)
* Content Source: [docs/standard/data/sqlite/custom-versions.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/sqlite/custom-versions.md)
* Product: **dotnet**
* Technology: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by IEvangelist** [comment]
Hi @bricelam,
Thank you for posting this issue. I'll try to incorporate this into the doc.

**Comment by bricelam** [comment]
Yes, that’s the exception you’ll get on Windows since it doesn’t have a system-wide version on SQLite. On iOS, macOS, and Linux it should work.

**Comment by bricelam** [comment]
Also, I probably should have assigned this issue to myself. 🙂 But I’m happy to review it if you still want to write something.
