### ISSUE TITLE
dotnet add package returns local source not found

### ISSUE THREAD

**Issue by varunmankal** [dotnet/docs#18216]
I have added my private source to NuGet.config file. when I run `dotnet nuget list source` it displays the following sources:
* nuget.org
* myprivate

Now, If I want to install a package from myprivate source then I try to run the following command:
`dotnet add package <packageName> -s myprivate`
then it returns an error saying the source `myprivate` not found.
If I run the same command using the myprivate URL instead of source name then it works.

How can I use source name instead of URL in the above command.

**Target framework**

- [3.1.2 ] .NET Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package#options)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Thraka** [comment]
I don't believe this is the way it operates. I'm moving your issue to the nuget repository.

**Comment by Thraka** [comment]
This issue was moved to NuGet/Home#9511
