### ISSUE TITLE
顺序写反了 (The order is the opposite.)

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18210]
_From @SuperBeana on Tuesday, April 28, 2020 7:31:34 PM_

https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=3
此示例新引入了另外一个运算符。 ++ 变量后面的 counter 是增量运算符。 它负责用计数器值加 1，并将计算后的值存储在计数器变量中。

_Copied from original issue: MicrosoftDocs/feedback#2708_

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [分支和循环 - C# 交互教程简介](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=3)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
_From @gewarren on Friday, May 1, 2020 7:22:53 PM_

Translation:

This example introduces another operator. The counter after the variable is the delta operator. It is responsible for adding 1 with the counter value and storing the calculated value in the counter variable.

**Comment by BillWagner** [comment]
I'm making updates in this area now, so I'll add this to the current sprint.

**Comment by BillWagner** [comment]
I looked at the current english text, and the `++` operator is explained correctly. @JasonCard is this a translation issue?

**Comment by JasonCard** [comment]
Yes, it looks like suggestion for possible translation issue.
@DavidPrio please help to follow up on this.

Source file: [https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
Source string: The `++` after the `counter` variable is the **increment** operator.
Current zh-cn translation: `counter` 变量后面的 `++` 是增量运算符。
Back translation: The counter after the variable is the delta operator.
Suggested zh-cn translation: `++` 变量后面的 `counter` 是增量运算符。

**Comment by srvbpigh** [comment]
Hello, @gewarren
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.zh-cn #585](https://github.com/dotnet/docs.zh-cn/issues/585) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
#please-close
