### ISSUE TITLE
Merge expression tree sections

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#1821]
Merge sections ...

https://docs.microsoft.com/en-us/dotnet/articles/csharp/expression-trees
https://github.com/dotnet/docs/blob/master/docs/csharp/expression-trees.md

and 

https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/concepts/expression-trees/
https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/index.md

**Comment by mairaw** [comment]
Just to be clear, we need to merge those two sections. @BillWagner should the final destination be the programming guide one?

**Comment by BillWagner** [comment]
I'd prefer moving topics out of the migrated Programming Guide section into a new tree. 

However, the new topics are all in one directory, which won't work as more content is updated. So, I'd like put this in a /concepts directory under the chsarp directory when it's updated.

Does that make sense?

**Comment by mairaw** [comment]
Yep, at least to me. 😄
