### ISSUE TITLE
顺序写反了

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18211]
_From @SuperBeana on Tuesday, April 28, 2020 7:16:13 PM_

https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=2
只有当条件的测试结果为 else 时，才执行 false 关键字后面的语句。 将 if、else 与布尔条件相结合，可以实现所需的一切目标。

_Copied from original issue: MicrosoftDocs/feedback#

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [分支和循环 - C# 交互教程简介](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
_From @welcome[bot] on Tuesday, April 28, 2020 7:16:15 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by BillWagner** [comment]
The original text translate to this:

> Only when the test result of the condition is else, the statement following the false keyword is executed. Combining if, else and Boolean conditions, you can achieve all the goals you need.

@JasonCard Could this be a translation issue?

**Comment by JasonCard** [comment]
Yes, this appears to be translation issue. It looks like "else" and "false" should be reversed in the translation.
@DavidPrio could you please help to follow up on this issue?

**Comment by srvbpigh** [comment]
Hello, @gewarren
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs.zh-cn #263](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/263) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.zh-cn #580](https://github.com/dotnet/docs.zh-cn/issues/580) via [**ZenHub**](https://www.zenhub.com/)

**Comment by BillWagner** [comment]
closing this as a translation issue.  Thanks all for following up.
