### ISSUE TITLE
Additional Advice: ConfigureAwait and ValueTask

### ISSUE THREAD

**Issue by daniel134256** [dotnet/docs#18225]
Great article!

I found the last section (Important Info and Advice) particularly useful. I was wondering if there's a place for adding the case for ConfigureAwait and ValueTask (separately) as well.

From my experience, although async/await and tasks are powerful abstractions, and developers adopt them fast, some threat them as "magic" and sooner or later find themselves in a bind. I think your opinionated advice helps put the spotlight on important pitfalls and guide developers in the right direction for further inquiry. I wish I would have stumbled across this article when I started writing asynchronous code. Good job!

---
#### פרטי המסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 07ed82a3-99c1-0893-4e81-d095b4757ecc
* Version Independent ID: 3765200b-43e5-441c-b290-709c34dd2f6d
* Content: [Asynchronous programming - C#](https://docs.microsoft.com/he-il/dotnet/csharp/async#feedback)
* Content Source: [docs/csharp/async.md](https://github.com/dotnet/docs/blob/master/docs/csharp/async.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by cartermp** [comment]
@daniel134256 good feedback! Yes, some guidance on `ConfigureAwait` and `ValueTask` would be a good thing to add.

**Comment by BillWagner** [comment]
Note on title update: I added the note on APIs so I can find this easier.
