### ISSUE TITLE
Step 4: Work with the double type.

### ISSUE THREAD

**Issue by kirkula** [dotnet/docs#18233]
Near the end, you write "You know that 0.3 repeating is not exactly the same as 1/3." This is not correct. 0.3 repeating IS exactly 1/3, just as 0.9 repeating equals 1. That being said, using the code to come up with 0.333333333333333 does show that it doesn't provide exact accuracy. I believe using 2/3 would be better suited though, as that answer would print out as 0.666666666666667, which is more visibly obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good point @kirkula I updated that description in #18248 to fix this.
