### ISSUE TITLE
The file should be named App.config if added to a C# or VB project

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#18234]
> 1. Add or locate the configuration file for the .NET Framework project. The configuration file for an app is in the same directory and has the same name as the app, but has a .config extension. For example, for an app named MyExecutable.exe, the application configuration file is named MyExecutable.exe.config.
>
>    To add a configuration file, on the Visual Studio menu bar, choose **Project**, **Add New Item**. Choose **General** from the left pane, and then choose **Configuration File**. Name the configuration file *appName*.exe.config. These menu choices are not available for Windows Store app or Windows phone app projects, because you cannot change the activation policy on those platforms.

If you are adding an application configuration file to a C# or Visual Basic project, then you should name it App.config rather than *appName*.exe.config, and the item type should be None or Content. This is because the FindAppConfigFile task in MSBuild specifically checks for the App.config name (case insensitive) and those item types. If you use a different name, then the build system neither recognizes nor generates binding redirects in the file, and does not copy it to the output directory by default.

* https://docs.microsoft.com/visualstudio/msbuild/findappconfigfile-task?view=vs-2017
* https://github.com/microsoft/msbuild/blob/v15.9.21.664/src/Tasks/FindAppConfigFile.cs
* https://github.com/microsoft/msbuild/blob/v15.9.21.664/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1115-L1124 

You would use the *appName*.exe.config name if you were creating a configuration file for a previously installed application and not intending to rebuild it, but because this article talks about "your desktop app", I think it is reasonable to assume that you have the source code and intend to build the application again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5b3494-855e-321c-5da3-258218ba50e0
* Version Independent ID: a6f40f48-c59f-2f2e-57ad-c124cd04ecb9
* Content: [How to: Configure an app to support .NET Framework 4 or later versions](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5#feedback)
* Content Source: [docs/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
