### ISSUE TITLE
Please publish Dotnet core install instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by pavangayakwad** [dotnet/docs#18235]
Please update document to help us install Dotnet core on Ubuntu 20.04. As of now 19.10 commands on Ubuntu 20.04 are failing.

![image](https://user-images.githubusercontent.com/1834890/80912189-e3ff0180-8d58-11ea-8a08-a01a95ba973e.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by pavangayakwad** [comment]
duplicate issue. sorry, closing it.

**Comment by Thraka** [comment]
Duplicate of #17638
