### ISSUE TITLE
Auto.ML.0.16.0 and System.Memory 4.0.1.0

### ISSUE THREAD

**Issue by ericdransfeldt** [dotnet/docs#18232]
Hi,

I love the Microsoft.ML and AutoML platforms but am having an issue when I upgraded my AutoML version via NuGet. When I upgraded from Microsoft.ML.AutoML from version 0.15.0 to 0.16.0 I started getting an error when I ran my code. Nothing changed in my source code except to recompile. It seems like it can't find System.Memory 4.0.1.0.

Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified., Stack:    at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(String name, Type rawType, IEnumerable`1 attributes, Boolean& isVector, Type& itemType)
   at Microsoft.ML.Data.InternalSchemaDefinition.GetVectorAndItemType(MemberInfo memberInfo, Boolean& isVector, Type& itemType)
   at Microsoft.ML.Data.SchemaDefinition.Create(Type userType, Direction direction)
   at Microsoft.ML.Data.DataViewConstructionUtils.CreateFromEnumerable[TRow](IHostEnvironment env, IEnumerable`1 data, SchemaDefinition schemaDefinition)

I went back to the older version and it worked fine. No dependency issues.. Any ideas..?

Thanks for any help or ideas!

Cheers,
Eric

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f39c5a-b353-4a50-9719-06074465e800
* Version Independent ID: 6e8ac4b9-43a0-84d7-35d2-b9f1bc88a4d9
* Content: [Install extra ML.NET dependencies - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies)
* Content Source: [docs/machine-learning/how-to-guides/install-extra-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-extra-dependencies.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @ericdransfeldt ,

Sorry to hear you're having trouble. Thanks for raising this issue. Since this is more of a product question, I've moved it to the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo. You can track the discussion at dotnet/machinelearning#5086

For future reference when raising issues:

- ML.NET/AutoML related issues & questions: https://github.com/dotnet/machinelearning
- Docs related issues & questions: https://github.com/dotnet/docs

Closing this issue for now.

**Comment by ericdransfeldt** [comment]
Thanks Luis!

I thought I was in the product area. Which area did I post to?

Thanks for your help!

Cheers,
Eric

**Comment by luisquintanilla** [comment]
You were in the right product but you raised the issue on Docs repo. Docs related issues are something like there's a typo in a tutorial or the code is wrong in a sample. This is more of a product related issue, so the dotnet/machinelearning repo is the best place for it. From Docs, if you click **This product** it should take you to the right place and if not, feel free to let us know 😃 . 

![image](https://user-images.githubusercontent.com/46974588/80932420-4d006c80-8d8d-11ea-91bb-fddfb33c165e.png)

**Comment by ericdransfeldt** [comment]
Great, thank you! 

Cheers,
Eric
