### ISSUE TITLE
Is this article update for .net core 3.1?

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/docs#18230]
AppContext.GetData("APP_PATHS") returns null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73a9cdd-9378-bc27-fcda-8804ebb9c9ce
* Version Independent ID: bd57feac-b27d-e56c-aad4-a637505a9206
* Content: [Default probing - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing?source=docs)
* Content Source: [docs/core/dependency-loading/default-probing.md](https://github.com/dotnet/docs/blob/master/docs/core/dependency-loading/default-probing.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by sdmaclea** [comment]
I believe the default host fully populated `TRUSTED_PLATFORM_ASSEMBLIES`, but does not configure any default probing paths.  So `APP_PATHS` is likely `null`

/cc @vitek-karas @elinor-fung

**Comment by vitek-karas** [comment]
@sdmaclea is correct. `APP_PATHS` and `APP_NI_PATHS` are not populated by default. They are present mostly for backward compatible reasons, any recent apps should not need the runtime to perform any probing (as in searching through folders to find assembly) and should solely rely on `TRUSTED_PLATFORM_ASSEMBLIES`.

I created https://github.com/dotnet/docs/pull/18265 to add a note that these two properties are most likely `null`.

**Comment by nvmkpk** [comment]
If I want to add additional folders to the probing path what is the recommended way to set it up?

**Comment by vitek-karas** [comment]
The recommended way is to not add additional probing paths but instead provide code which resolves assemblies. The easiest way is to register a handler to `AppDomain.Current.ResolveAssembly`. In the event handler you get the name of the assembly which is being resolved - you then perform whatever code to find the assembly file on disk and load it, ideally via `AssemblyLoadContext.Default.LoadFromAssemblyPath`, but `Assembly.LoadFrom` would also work. And then return the `Assembly` object from the event handler.

This gives you more options to provide assembly resolution than a simple list of paths.

Just me being curious: What is the scenario where you need to load assemblies from other locations? Is it something like a "plugin", or some other case? How do you build those other assemblies?

**Comment by nvmkpk** [comment]
Yes, I am doing something similar right now. But I am handling `AssemblyLoadContext.Default.Resolving`. Do you think that is ok or should I do it via `AppDomain`?

My scenario is kind of similar to plugin. I have an asp.net core web application that serves multiple subdomains routing the incoming requests to its corresponding web application. I am trying to run each subdomain's web application from its own bin folder to fix missing static web assets xml file. This is only needed for development environment.

**Comment by vitek-karas** [comment]
If you don't have custom `AssemblyLoadContext` then it doesn't matter if you use `AssemblyLoadContext.Default.Resolving` or `AppDomain.Current.ResolveAssembly`, in that case they're basically the same thing.

As for your scenario, this will work if there are no problems with different dependencies by the different web applications. Since you're loading everything into the default load context, if two of the web apps would have a dependency on the same assembly but different version then it might break.

**Comment by nvmkpk** [comment]
At this time I do not have references to different versions of same assembly. I will definitely create multiple `AssemblyLoadContext` instances if that changes. But I am wondering how multiple `AssemblyLoadContext` instances affect the memory usage of the application when same framework assemblies are loaded into each of them.

**Comment by vitek-karas** [comment]
With the typical usage of `AssemblyLoadContext` framework assemblies should not be loaded multiple times. In fact loading framework assemblies multiple times is not really supported and we know about several cases where it will cause problems (and it will definitely cause lot of confusion).
Typical usage of `AssemblyLoadContext` is to isolate NuGet (or similar) dependencies - for example one "plugin" using `Newtonsoft.Json, version=10.0.0.0` while another uses `Newtonsoft.Json, version=11.0.0.0` - using multiple ALCs it's possible to make these work side-by-side.

So unless the plugins will have lot of assemblies+dependencies which are large and will get loaded multiple times, memory usage should not be a concern.

**Comment by nvmkpk** [comment]
>With the typical usage of AssemblyLoadContext framework assemblies should not be loaded multiple times.

By this, do you mean I should not load framework assemblies in multiple `AssemblyLoadContext` or any attempt to load them in multiple  `AssemblyLoadContext` instances will cause issues or fail and is not supported? Last when I tried multiple `AssemblyLoadContext` instances, I ran into issues when I tried to avoid loading the Asp.net core assemblies into multiple times. Asp.net core does `Assembly.Load(env.ApplicationName)` this in many places and made it a standard practice. It attempted to load my main assembly for the non-default `AssemblyLoadContext` instance in default `AssemblyLoadContext` instance and failed.

**Comment by vitek-karas** [comment]
It's perfectly fine to call `secondaryAssemblyLoadContext.LoadFromAssemblyName("System.Runtime")`, but it should NOT cause the assembly to be loaded into the secondary ALC. Any secondary ACL should fallback to the default for framework assemblies. This typically means that `AssemblyLoadContext.Load` should return `null` for framework assemblies.

The above will make sure that framework assemblies are only ever loaded once.

There's an important distinction: AssemblyLoadContext provides assembly resolution isolation, that is the logic how to resolve assembly dependencies can differ between various ALCs. It can also provide assembly isolation in that it's possible to load assembly of the same name into multiple contexts, while it's not possible to load more than one assembly of the same name to any given ALC. BUT it doesn't say that the resolution logic must return assemblies from the same ALC. It's perfectly valid to return `Assembly` loaded into any ALC from any other ALC.

So for framework assemblies any ALC should resolve framework assemblies using the Default ALC (simplest way to achieve this is to return `null` from ALC.Load for framework assemblies).

The ASP.NET case is problematic for multiple reasons, but in short, ASP.NET as such has not been designed to work in secondary ALC - it's not ALC aware really. There are possible workarounds like [`CurrentContextualReflectionContext`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.currentcontextualreflectioncontext?view=netcore-3.1) but there's no guarantee that these will work for ASP.NET. This is one of the current limitations of ALC, that not all framework code plays nice with it.

**Comment by lindexi** [comment]
> Just me being curious: What is the scenario where you need to load assemblies from other locations?

@vitek-karas  The client application development scenario will need to load assemblies from other locations. 

Such as it be used to the multiple process development models, or it be used to help the application to update.

## Updating

This is helpful when updating the application.

The file layout as below

│  A.deps.json
│  A.dll
│  A.exe
│  A.runtimeconfig.json
│
├─1.0.0
│      Business.dll
│
└─1.0.2
        Business.dll

When we update to 1.0.2 version, we just download the new version file to the 1.0.2 folder. And the entry point A.exe will auto select the version Business.dll to run.

**Comment by adegeo** [comment]
The bot reopened this when it should have remained closed
