### ISSUE TITLE
Mention target framework requirements for nullability attributes to work

### ISSUE THREAD

**Issue by tzkhan** [dotnet/docs#18237]
The documentation mentions the assumption for C# 8.0 and enabled nullable context in order to use the various nullability attributes (`AllowNull`, `DisallowNull`, etc).

It should also however, specify the target frameworks required to use them:
- NET 5 Preview 1
- .NET Core 3.1 3.0
- .NET Standard 2.1

Someone trying to use these attributes within a .NET Standard 2.0 class library for instance, will find it hard to figure out due to the potentially confusing error message _'The type of namespace name 'NotNullWhen' could not be found (are you missing a using directive or an assembly reference)'_ even if they have included a `using System.Diagnostics.CodeAnalysis;` directive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @tzkhan That's a good point.

I think the right plan is to expand the fix for this issue to add a note on all C# 8 related content that C# 8 is supported only on those TFMs.

Thoughts @cartermp @MadsTorgersen ?

**Comment by cartermp** [comment]
I think that's reasonable, yes
