### ISSUE TITLE
Using the <inheritdoc /> Tag

### ISSUE THREAD

**Issue by asm2025** [dotnet/docs#18236]
Hello,

I want to thank you for the new updates of Visual Studio IDE and all the shiny .netCore. I think the documentation is not cathing up though and might need to be updated to reflect some basic use-case scenarios.

Comparing Microsoft's documentation link:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc
to something like:
https://tunnelvisionlabs.github.io/SHFB/docs-master/SandcastleBuilder/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm
For example, it's not obvious there can be nested inheritance in the above link #Nested

or the new feature such as the quick info style support for XML comments and using
<c>code<c><em>emphasis</em><strong>strong</strong>
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.3#16.3.0

is not reflected in
https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04441bbc-7e98-d6df-2c5a-20e816d79dc7
* Version Independent ID: ba155807-a2b0-8982-abe7-fac1e2b51a7d
* Content: [&lt;inheritdoc&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc)
* Content Source: [docs/csharp/programming-guide/xmldoc/inheritdoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/inheritdoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @mikadumont to discuss the correct fix for this.
