### ISSUE TITLE
Changed cancelation behavior of WebClient.CancelAsync()

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/docs#18250]
## Changed behavior of WebClient. CancelAsync()

Changed cancelation behavior of `WebClient.CancelAsync()`.

### Version introduced

2.0

### Old behavior

`WebClient.CancelAsync()` cancels the request immediately.

### New behavior

`WebClient.CancelAsync()` cancels the request immediately only when the response didn't start to fetch yet. When the response starts to fetch the cancellation happens after a complete response is read.

### Reason for change

WebClient is considered as a deprecated API and it is reimplemented using HttpClient.

### Recommended action

Use the HttpClient instead of the WebClient.

### Category

- Core .NET libraries
- Networking

### Affected APIs

 [WebClient.CancelAsync()](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.cancelasync?view=netcore-2.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
Thank you Jan!
