### ISSUE TITLE
How to inpect fixed buffers in the debugger ?

### ISSUE THREAD

**Issue by NJSFC** [dotnet/docs#18257]
In your example
internal unsafe struct Buffer
{
    public fixed char fixedBuffer[128];
}

how can i watch  the fixedBuffer[128] contents  In the debugger ??
only shows the first value.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e17dd8-f60c-5a5d-517f-61bb95e94667
* Version Independent ID: c9d34513-107b-0b82-cf77-1dba0ee650cb
* Content: [Fixed Size Buffers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers#feedback)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking this @NJSFC 

You can add an index operator to the expression and examine any single value:

`fixedBuffer[5]` will show the value at index 5.  

I'll close this as an answered question. If you have more questions, add a comment and reopen the issue.

**Comment by NJSFC** [comment]
Thanks for your response
What i meant was to inspect the contents as array not a single value at time.
if i need to do that i spent more time debbuging than fixing the errors.
Its not viable to inspect  all the array elements one by one.
