### ISSUE TITLE
Error in UdpClient example

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18251]
@decvs commented on [Sat May 02 2020](https://github.com/dotnet/docs.de-de/issues/195)

The example leads to the error: You must call the Bind method before performing this operation.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Verwenden von UDP-Diensten](https://docs.microsoft.com/de-de/dotnet/framework/network-programming/using-udp-services)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

---

@srvbpigh commented on [Sat May 02 2020](https://github.com/dotnet/docs.de-de/issues/195#issuecomment-622851266)

Hello, @decvs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@karelz commented on [Mon May 04 2020](https://github.com/dotnet/docs.de-de/issues/195#issuecomment-623549360)

I couldn't reproduce the error -- I just tried the example (both listener and sender) from https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services and it worked just fine on .NET Core 3.1.

**Comment by gewarren** [comment]
It worked for me using .NET Framework too.

**Comment by gewarren** [comment]
I'm going to close this issue as not reproducible. @decvs If you still believe there's a problem in the documentation, please comment here.
