### ISSUE TITLE
An example and a further explanation would be nice

### ISSUE THREAD

**Issue by dgkoris** [dotnet/docs#18256]
This help page doesn't say much about what the #pragma does and it would be nice to have at least an example. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b6c1f4-889c-fef4-f15d-b32e3a714c10
* Version Independent ID: 7ef6f711-b7bc-63d1-cab8-34242edd619f
* Content: [#pragma - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma#feedback)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reaching out @dgkoris 

This page is a landing page for the two `#pragma` directives supported by C#. Both links are on this page for more details. 

I'll close this as an answered question.
