### ISSUE TITLE
ServiceLayer.exe

### ISSUE THREAD

**Issue by Angelo69767** [dotnet/docs#18254]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0ad4c6-13f4-9fb3-e4e9-5d70a6cde5fc
* Version Independent ID: 39ac04e7-703a-2e91-7272-4f3af2ba9a59
* Content: [ServiceLayer Class (Microsoft.CodeAnalysis.Host.Mef)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.host.mef.servicelayer?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.Host.Mef/ServiceLayer.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.Host.Mef/ServiceLayer.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@Angelo69767 Could you provide some more info on the issue at hand?

**Comment by Angelo69767** [comment]
I was going to look for software for my Nokia 5800. That's it.

**Comment by gewarren** [comment]
Okay, I will close this issue since it sounds like you didn't mean to create an issue.
