### ISSUE TITLE
Link to the 'other' page?

### ISSUE THREAD

**Issue by runemoberg** [dotnet/docs#18264]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests was more useful to me. Perhaps shorten this page and provide a link to the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#feedback)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @runemoberg, thank you for your feedback. 

This page `Use IHttpClientFactory to implement resilient HTTP requests` shows how a typed client can be used in microservices with `IHttpClientFactory`. 
And that's the reason it talks about  `HttpClient` and `IHttpClientFactory`, before explaining `Typed Client`. 

Yes, [Make HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1) is a very good reference to understand the details
about the different usage pattern of `IHttpClientFactory` and it has already been referred under section [Multiple ways to use IHttpClientFactory](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#multiple-ways-to-use-ihttpclientfactory)

Also, If you want to refer the entire code base for `eShopOnContainers` please visit the [github](https://github.com/dotnet-architecture/eShopOnContainers)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @alexdrenea, considering the original question has been addressed, I am closing this issue as of now. 
If you have any further questions, please feel free to reopen it. 

Thank you.
