### ISSUE TITLE
Tab Completions for CMD?

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/docs#18263]
Is there any way to provide custom tab completions for `CMD` too? Is it even possible?

Can anyone from commandline team comment on this? /cc @zadjii-msft @cinnamon-msft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by zadjii-msft** [comment]
Pretty much no, `cmd.exe` doesn't support anything like this. CMD is a pretty legacy piece of software, if you'd like a shell with modern CLI features on Windows, the guidance is largely just "use PowerShell or WSL"

**Comment by IEvangelist** [comment]
Hi @Nirmal4G,

Thank you for asking this question, and thank you @zadjii-msft for the quick reply. I'm going to close this now as it seems a though it has been resolved.
