### ISSUE TITLE
dotnet gitignore file

### ISSUE THREAD

**Issue by crnegule** [dotnet/docs#18262]
Update documentation to include details about "dotnet gitignore file" command. It would be nice to have a short description and example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?source=docs#feedback)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. We'll add this the next time we update the doc.

**Comment by Youssef1313** [comment]
@tdykstra This was already fixed and can be closed.
