### ISSUE TITLE
GitHub Action is opting this project into semver-breaking changes to markdownlint-cli

### ISSUE THREAD

**Issue by DavidAnson** [dotnet/docs#18275]
Running a command like `npm i -g markdownlint-cli` always pulls the latest version of that package, _including_ when it has a semver-breaking change:
https://github.com/dotnet/docs/blob/5860bb8a257b581fe809710c51de8662598edd2d/.github/workflows/markdownlint.yml#L26

Doing that from a continuous integration script makes it likely that breaking changes will show up as part of a completely different change to the project - whichever happens to run CI first after a new version is published. A more predictable pattern is to specify a particular version of the package to install.

Here's how Google addressed this issue in their code: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/34

**Comment by IEvangelist** [comment]
Thank you @DavidAnson, this was very helpful. We've addressed this issue in #18280

**Comment by DavidAnson** [comment]
Wonderful, thank you!
