### ISSUE TITLE
Confusing on statements

### ISSUE THREAD

**Issue by JulianLao** [dotnet/docs#18277]
On this page, it's told that “In C#, derived classes can contain methods with the same name as base class methods. The base class method must be defined virtual.” But on the page of [new modifier (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier), it seems like this statement is wrong. None of bass classes in the examples has a virtual key word in the declaration of members that have duplication of name in the derived class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc0929c-f565-df82-43d0-0a1066b42ca3
* Version Independent ID: ab208ff8-7478-564f-9f24-5fdee99d1643
* Content: [Versioning with the Override and New Keywords - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @JulianLao 

That statement should be amended. `virtual` and `new` have different purposes and different behavior. The incorrect statement should be removed. Instead, we should describe how `virtual` and `override` work together, and refer to the page on the `new` operator for its use and behavior.
