### ISSUE TITLE
Required Attribute

### ISSUE THREAD

**Issue by Mark-Phillipson** [dotnet/docs#18279]
The starship model has the Required attribute set for the ProductionDate and the IsValidatedDesign. Given that these data types are not nullable I presume the attributes have no actual effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b44a252f-fda0-acc2-e672-630386674d70
* Version Independent ID: 5d880efd-cdab-3739-545d-709ab48eb94d
* Content: [Forms and validation](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/forms-validation#feedback)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/forms-validation.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/forms-validation.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by VaishaliRaval** [comment]
Hi @Mark-Phillipson, thank you for reaching out.
Though the datatypes of ProductionDate and IsValidatedDesign are not nullable, the Required attribute is used for validation purpose.
The [RequiredAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=net-6.0) attribute specifies that when a field on a form is validated, the field must contain a value. A validation exception is raised if the property is null, contains an empty string (""), or contains only white-space characters.

I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.

**Comment by Mark-Phillipson** [comment]
✔️
