### ISSUE TITLE
Inconsistent definition of constant_pattern

### ISSUE THREAD

**Issue by ILMTitan** [dotnet/docs#18271]
The definition of `constant_pattern` is inconsistent.

In the main block it is defined as
```andlr
constant_pattern
    : expression
    ;
```

but in its own section, it is defined as
```andlr
constant_pattern
    : constant_expression
    ;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a3af6a-59dd-775a-a008-1530bba493f5
* Version Independent ID: 95639e9c-9432-b07b-5fc2-f30d7bab0123
* Content: [Recursive pattern matching - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#switch-expression)
* Content Source: [proposals/csharp-8.0/patterns.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @gafter

**Comment by gafter** [comment]
It turns out *constant_expression* and *expression* are the same (the former is defined as the latter).  I suggest using *constant_expression* for clarity.

**Comment by gafter** [comment]
Fixed in the source.

**Comment by BillWagner** [comment]
Fixed in https://github.com/dotnet/csharplang/commit/a17f4c8ba82ed19fdad8b9f86ac151a443c89b08
