### ISSUE TITLE
Could review.docs.microsoft.com become public?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1827]
As far as I can tell, CI in this repo publishes each PR to https://review.docs.microsoft.com/, where it presumably looks the same as it will look on https://docs.microsoft.com/. This would be especially useful, since building with `docfx` locally has issues (the template is very different; getting API reference right is hard; it's slow).

But, it's not accessible to me (and I assume everyone else outside MS): when I try to access it, I get a 403 error (after logging in).

A recent example where I would use this are [changes to package.md](https://github.com/dotnet/docs/pull/1825/files#diff-d250c069c8de97e94a2a93f8feef136c) in https://github.com/dotnet/docs/pull/1825. I suspect it has issues, but it's hard for me to check, since I can't access https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1825 (I found the URL in [the publicly accessible CI log](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C30%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201703300314080611-1825%5Cworkflow_report.html)).

Another reason why this is annoying is that CI sends emails to the PR author, containing links to https://review.docs.microsoft.com/, effectively saying "hey, come check that your PR looks okay", which the author is unable to do, if they are not from MS.

Since I don't see any reason for this limitation (all the information in the PRs is public anyway), could https://review.docs.microsoft.com/ become public?

**Comment by mairaw** [comment]
I understand your frustration @svick. Yes, that site only works with Microsoft credentials. 
We've had discussions around this internally but not sure if we made any decisions or progress on that. I'll follow-up with the team.

/cc @dend @Rick-Anderson @danroth27

**Comment by BillWagner** [comment]
Also, @richlander was part of those discussions as well.

**Comment by GuardRex** [comment]
The docs build locally on the ASP.NET Core side. Is it just a tweak to make them build over here? I'd love to be able to build locally ... it is sooooooo much faster 🏃 over there when you want to see what they look like to build locally.

**Comment by mairaw** [comment]
Moved issue to https://github.com/MicrosoftDocs/feedback/issues/533
