### ISSUE TITLE
ICryptoTransform.TransformBlock does not mention that inputCount has to be a multiple of InputBlockSize

### ISSUE THREAD

**Issue by mvacha** [dotnet/docs#1828]
I think it's pretty important information, because the method throws exeption if the condition is not satisfied. The only place you can find out about it is in the [ICryptoTransform source](https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/ICryptoTransform.cs/#L29).

I wasn't able to locate the correct .md doccument with the docs, so that's why I'm not sending a PR (I assume this page is generated from the old docs).

**Comment by mairaw** [comment]
Thanks for your feedback @mvacha. Yes, that page is still generated from the old docs but soon we'll ship a new API ref experience and we'll open source that content too.
