### ISSUE TITLE
 Ubuntu page is not available.

### ISSUE THREAD

**Issue by kgopi1** [dotnet/docs#18289]
Hi, when we running ansible playbook for downloading the deb file, URL shows page not found.
It is due to ansible_distribution resolves to Ubuntu , but virtual directory shows as ubuntu   ( u in lowercase). 
So can you update virtual directory name accordingly to the os name. 

my ansible tasks is 
    https://packages.microsoft.com/config/{{ ansible_distribution }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
This issue was moved to dotnet/sdk#11597
