### ISSUE TITLE
Error en variable

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18288]
@jams6 commented on [Wed May 06 2020](https://github.com/dotnet/docs.es-es/issues/162)

[Que tal
tengo error en la siguiente instrucción
 string? item;]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using (Instrucción, Referencia de C#)](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Wed May 06 2020](https://github.com/dotnet/docs.es-es/issues/162#issuecomment-624808835)

Hello, @jams6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
@CeciAc Can you ask for more details on this issue? From the translation, I can't figure out what the concern is.
