### ISSUE TITLE
Incorrect "struct" link?

### ISSUE THREAD

**Issue by PeterConstable** [dotnet/docs#18293]
Under "Custom types", the "struct" link actually points to the Classes page. Should it point to this?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1144c44-369d-fd62-fad9-3d07d229f04e
* Version Independent ID: c0189b06-4720-0a7e-b459-20cef88e31a5
* Content: [Basic Types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/basic-types)
* Content Source: [docs/csharp/basic-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/basic-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @PeterConstable I've opened a PR to fix this.

In the future, if you spot these small issues, you can click the "edit" button (it looks like a pencil) to edit the source and submit a PR. For these issues, it can save us both time.
