### ISSUE TITLE
Location of code in [Class Summary]

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18291]
@Misaki0306 commented on [Wed May 06 2020](https://github.com/dotnet/docs.ja-jp/issues/1699)

I could not find where to write the code of [Class Summary].

It is not clear whether the code is written in Program.cs or Transaction.cs.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [クラスおよびオブジェクト - C# チュートリアルの概要](https://docs.microsoft.com/ja-jp/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Wed May 06 2020](https://github.com/dotnet/docs.ja-jp/issues/1699#issuecomment-624503438)

Hello, @Misaki0306
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
thanks for bringing this to our attention. 

I looked for which sample you were referring to, and I'm not sure which one you mean. That points to a fix: For each new code sample, we should add clear instructions for which class needs to be modified for the new code.
