### ISSUE TITLE
char type has been omitted

### ISSUE THREAD

**Issue by pkpjpm** [dotnet/docs#18308]
The `char` type is an integral type according to the specification, but it's not included in this section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a22464d-b60c-36c0-e4e8-b209a33b0219
* Version Independent ID: cb500323-82a3-09ea-0468-dd16c9e13675
* Content: [Integral numeric types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#feedback)
* Content Source: [docs/csharp/language-reference/builtin-types/integral-numeric-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/integral-numeric-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @pkpjpm,

Thank you for posting this issue and raising this concern. The doc in question is for "integral numeric types", not just "integral types" - it is with that specificity that the doc intends to detail integral types that are intended for use with numeric intent. And while I agree that `char` is an integral type and even [implicitly convertible to most numeric integral types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/char#conversions), I do not believe it belongs in this doc. It is covered here, in [Intergral types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#integral-types). Does that make sense - if so, please feel free to close this issue. Thank you

**Comment by pkpjpm** [comment]
That makes sense, but now that I understand the distinction, I see that the heading and reference links in [this section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators#decrement-operator---) are wrong. Specifically, this:

> Those operators are supported by all integral and floating-point numeric types

Seems that "numeric" is wrong in this context, and the link should point to the spec you've quoted and not the page referenced in this thread. In case you're wondering the context of this confusion, see [this stackoverflow thread](https://stackoverflow.com/questions/61668344/where-is-the-char-struct-operator-defined-in-net) where the issue came up. This was a question from a programmer who is learning C# and was trying to understand operators that apply to the `System.Char` type.

I understand that this is a different content source that the page this issue refers to. If you'd like me to close this and open another issue on the page in question, no problem.

**Comment by pkulikov** [comment]
> Seems that "numeric" is wrong in this context, and the link should point to the spec you've quoted and not the page referenced in this thread.

I wouldn't call that sentence "wrong". It's technically incomplete and has omitted the `char` type intentionally as it seems to be not a typical/common use case. What is the product of two letters?

Operations with `char` don't look like operations with `char`. That is, because `char` is implicitly convertible to `int`, ANY operator that supports `int` operands also accepts `char` operands. (So, some operators support `char` not because the `char` type overloads those operators, but because `char` is implicitly convertible to `int`.) Those `char` operands are converted to `int` before the operation. The result of such operations has type `int` (or `bool` in the case of comparison operators). For example, the following code produces numbers not letters:

```csharp
Console.WriteLine('a' | 'c');  // output: 99
Console.WriteLine(-'a');  // output: -97
Console.WriteLine('f' * 'm');  // output: 11118
```

I'm not sure that this edge case is something to present on the page about arithmetic (or logical) operators.

That said, maybe it's worth to update the [char article](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/char) with the information about operators that accept `char` operands.

**Comment by pkpjpm** [comment]
Thanks for indulging this topic, I agree "wrong" is probably too strong an assessment. It may interest you to know that the expression `'c'--` evaluates to type `System.Char`, not `System.Int32`. I will confess that in 30 years of professional experience, I don't recall ever using character arithmetic in production code, however it's not uncommon to need this technique in answering coding interview questions. Closing since it's past time for us all to get back to work!

**Comment by pkulikov** [comment]
> It may interest you to know that the expression `'c'--` evaluates to type `System.Char`, not `System.Int32`

@pkpjpm that's right, I'm working on the PR to update the docs accordingly.

**Comment by IEvangelist** [comment]
Hi @pkpjpm,

Ah, yes - you are correct that the [arithmetic operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators) document could be improved upon to also mention that while a `char` is not considered an integral numeric type, it also exposes these arithmetic operators.

```csharp
using System;

class Program
{
    static void Main()
    {
        var a = (char)97;
        var b = 'b'; // 98

        a++; // 98

        Console.WriteLine($"a == b: {a == b}");
        Console.WriteLine($"a % b: {a % b}");
        --a;
        Console.WriteLine($"a % b: {a % b}");

        var c = b / 2;
        Console.WriteLine($"b / c: {b / c}");
        Console.WriteLine($"a * b: {a * b}");

        Console.ReadLine();
    }
}

// a == b: True
// a % b: 0
// a % b: 97
// b / c: 2
// a * b: 9506
```

Feel free to create a pull request to update the doc with these changes, or I'll look to capture this effort in the near future. Thank you.
