### ISSUE TITLE
Add WinForms sizing and layout topics back to documentation set

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1830]
# Add WinForms sizing and layout topics back to documentation set

Prior to CAPS migration, most of the topics in the [Getting Started with Windows Forms](https://msdn.microsoft.com/en-us/library/ms229601(v=vs.100).aspx) section of the Windows Forms documentation were removed from the documentation set. Some of the topics, particularly those related to form layout and sizing, continue to remain important. Therefore, these topics should be restored to the doc set.

Doing this requires the following:

1. The topics need to be retrieved from DxStudio, our legacy authoring system. (They were not migrated to CAPS, our current authoring system.)
2. The content needs to be ported from the DxStudio XML format to markdown.
3. They should be included in the Windows Forms documentation set.

These topics include:
- [How to Set the Screen Location of Windows Forms](https://msdn.microsoft.com/en-us/library/52aha046(v=vs.100).aspx), which was deleted from DxStudio and would need to be recreated from the MSDN page.
- [How to: Create Nonrectangular Windows Forms](https://msdn.microsoft.com/en-us/library/6k15y9et(v=vs.100).aspx)), which was deleted from DxStudio and would need to be recreated from the MSDN page.
- [How to: Make a Startup Windows Form Invisible](https://msdn.microsoft.com/en-us/library/754w18dd(v=vs.100).aspx))), which was deleted from DxStudio and would need to be recreated from the MSDN page.
- [How to: Enable Windows XP Visual Styles](https://msdn.microsoft.com/en-us/library/5d1acks5(v=vs.100).aspx), which was deleted from DxStudio. Its content needs to be incorporated into the Windows Forms documentation elsewhere, including into the Application.EnableVisualStyles MREF topic.

**Comment by mairaw** [comment]
Can you add a few examples @rpetrusha?

**Comment by rpetrusha** [comment]
I've updated my original comment to reflect some of the deleted topics.

**Comment by IEvangelist** [comment]
Ping @adegeo - thoughts on this? Leave it as a P1, or deprioritize it? Also, let's put it in the correct project.

**Comment by adegeo** [comment]
I think we can close this. We're not investing time into the older story for WinForms. The new story for WinForms is highly trimmed content and as of right now, none of this falls into what would be published.
