### ISSUE TITLE
dotnet store - explain --skip-optimization option

### ISSUE THREAD

**Issue by sensslen** [dotnet/docs#18317]
It is currently not clear what the "optimization phase" does so it is not clear what can be enabled/diabled by the --skip-optimization command line option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc238c72-c1eb-a09f-5b7b-801722924d38
* Version Independent ID: dbfcef0a-1079-0a2c-6bda-d2b57445ec29
* Content: [dotnet store command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store)
* Content Source: [docs/core/tools/dotnet-store.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-store.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@rrelyea @nkolev92 can you explain what effects `--skip-optimization` has?

**Comment by rrelyea** [comment]
As we mentioned on a parallel thread... `dotnet store` is owned by the dotnet sdk team or asp.net team. NuGet team doesn't know what it is...other than it was built in .net core 2.x timeframe for reasons.

**Comment by tdykstra** [comment]
As noted in [this comment](https://github.com/dotnet/docs/issues/18316#issuecomment-626271774) on #18316, it may take some time to research and answer this question.
