### ISSUE TITLE
Sample VBA code for optional parameters with default values does not seem to work on Word 2016

### ISSUE THREAD

**Issue by kaanchan** [dotnet/docs#18315]
The sample code for optional parameters with default value does not appear to work in Word 2016. The sub does not show in list of macros when the default value is given in the sub declaration. Removing the default value makes sub appear on macros list.

```
Sub notify(ByVal company As String, Optional ByVal office As String = "QJZ")
    If office = "QJZ" Then
        Debug.WriteLine("office not supplied -- using Headquarters")
        office = "Headquarters"
    End If
    ' Insert code to notify headquarters or specified office.
End Sub
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d7e221-57bc-3524-1f74-490d5bbfaf26
* Version Independent ID: bac92a76-a343-ac1f-2e90-01e19ae7963a
* Content: [Optional Parameters - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/optional-parameters#feedback)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/optional-parameters.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/optional-parameters.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
@kaanchan VBA isn't the same as VB.NET. You should read the article related to VBA that I found: https://docs.microsoft.com/en-us/office/vba/Language/Concepts/Getting-Started/understanding-named-arguments-and-optional-arguments

However, the end of the article says to use this link for support: https://docs.microsoft.com/en-us/office/vba/articles/feedback-support
