### ISSUE TITLE
Process.StartInfo changes

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#18310]
Reading the `StartInfo` property of a process that you did not start (within the current process, using `Process.Start`) will throw `InvalidOperationException`

### Version introduced

.NET Core v1.0

### Old behavior

In .NET Framework, it will return a dummy `ProcessStartInfo` object. This object will return default values from all its properties, except `EnvironmentVariables`, which will return the current process's environment variables.

However, it is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.startinfo?view=netcore-3.1#remarks) not to do this:  "You should only access the StartInfo property on a Process object returned by the Start method. For example, you should not access the StartInfo property on a Process object returned by GetProcesses. Otherwise, on .NET Core the StartInfo property will throw an InvalidOperationException and on .NET Framework it will return a dummy ProcessStartInfo object."

### New behavior

It throws `InvalidOperationException`

### Reason for change

The object returned was a dummy object, with no value; it was also documented that it should not be gotten.

### Recommended action

Stop calling this property getter.

### Category

CoreFX

### Affected APIs

[Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netcore-3.0)
[ProcessStartInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=netcore-3.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@BillWagner @Thraka Any idea why this didn't automatically get a breaking-change label?

**Comment by Thraka** [comment]
Unsure. Github has been a bit strange lately with the bot.

**Comment by Thraka** [comment]
@gewarren There is supposed to be a blank line at the end of the metadata, it must have been removed by accident. After restoring it, it was fixed.

**Comment by gewarren** [comment]
I see, thanks for looking into it!

**Comment by danmosemsft** [comment]
This should go into https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core presumably

**Comment by qryt** [comment]
问题出在System.Diagnostics.Process.StartInfo的get方法中，不应该简单地throw null。
![image](https://user-images.githubusercontent.com/40115795/141388745-dbbd2923-cbf9-4c90-9229-c05d5c23dbf0.png)
.net framework中则是对它进行了初始化处理，所以不会抛出异常。
![image](https://user-images.githubusercontent.com/40115795/141388782-8b083da5-0388-42db-99e7-aae15245540d.png)

**Comment by gewarren** [comment]
Translation:

The problem is that in the get approach of System.Diagnostics.Process.StartInfo, it shouldn't simply throw null.
It is initialized in .NET Framework, so no exception is thrown.

**Comment by gewarren** [comment]
@qryt I'm not sure what the concern is or where the code you pasted comes from. For .NET Core 1.0, the code doesn't say `throw null` in the getter. See https://github.com/dotnet/corefx/blob/96ae037b9359e2ab220bc5c370bf952b4234a039/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L482-L494.

**Comment by danmoseley** [comment]
Somehow you are executing a reference assembly. How are you creating this project? Can you paste in the project file? Does it repro if you use just the command line?
