### ISSUE TITLE
dotnet store - explain usage of --framework option

### ISSUE THREAD

**Issue by sensslen** [dotnet/docs#18316]
According to this documentation there are three required parameters but not all of them are specified in the examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc238c72-c1eb-a09f-5b7b-801722924d38
* Version Independent ID: dbfcef0a-1079-0a2c-6bda-d2b57445ec29
* Content: [dotnet store command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store)
* Content Source: [docs/core/tools/dotnet-store.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-store.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@rrelyea @nkolev92  `--framework` is listed as a required option but it doesn't actually seem to be required on the command line, and the text for it says "The target framework has to be specified in the project file." What is the use case  for specifying `--framework` on the command line?

**Comment by rrelyea** [comment]
`dotnet store` is not a nuget concept. Don't know if the sdk team or asp.net team own, but we have no idea about it.

**Comment by tdykstra** [comment]
@wli3 Who can help with `dotnet store`?

**Comment by wli3** [comment]
It should be on SDK team. However, no one is very familiar with _dotnet store_, since we inherited it. So there will be a long delay for answering the questions
