### ISSUE TITLE
{"The remote server returned an error: (530) Not logged in."}

### ISSUE THREAD

**Issue by deepru2608** [dotnet/docs#18313]
{"The remote server returned an error: (530) Not logged in."} please send me the resolution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a421182a-dac9-c619-b501-240dd2aafd7b
* Version Independent ID: 30940ebd-4501-8580-2efc-c6abf522fe93
* Content: [How to: Upload files with FTP](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-upload-files-with-ftp#feedback)
* Content Source: [docs/framework/network-programming/how-to-upload-files-with-ftp.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-upload-files-with-ftp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@deepru2608 it is not clear to me what is your report about -- did the sample fail for you?
Which version of .NET are you using? Did you check that the FTP server works correctly?

**Comment by deepru2608** [comment]
Hi, 

I have check my FTP server and I am doing some thing with my FTP server but now it’s working fine and file is uploading on FTP.

Thanks
Deepanshu

**Comment by karelz** [comment]
OK, looks like there is no problem to track here then.
