### ISSUE TITLE
Potential issue with Quick Reference documentation

### ISSUE THREAD

**Issue by MWToivonen** [dotnet/docs#18322]
I think there's a mistake in the "miscellaneous constructs" section of the regular expression quick reference.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#miscellaneous-constructs

The "# [to end of line] style of comment shows a comment being added by appending "#Matches..." directly to the end of a regex, with no whitespace.

![image](https://user-images.githubusercontent.com/65036064/81430629-972e7880-9114-11ea-9dc2-7f61a3d5602b.png)

I don't think this is correct. In my own project I have regular expressions being generated with the following options set:

RegexOptions regexOptions = regex.Contains("#any") ?
                RegexOptions.IgnorePatternWhitespace : // regex includes comment
                RegexOptions.None;

This is treating any '#' character directly attached to a regex as a literal '#' character and not the beginning of a comment. Elsewhere, I have regexs that use the '#' separated by a whitespace, and it's being treated as the beginning of a comment. These look similar to the following:

string pattern = @"\{\d+(,-*\d+)*(\:\w{1,4}?)*\}(?x) # Looks for a composite format item.";

(However, this example was taken from your documentation rather than my source code. https://docs.microsoft.com/en-us/dotnet/standard/base-types/miscellaneous-constructs-in-regular-expressions#end-of-line-comment)

Based on what I'm seeing, there's either a typo in the quick reference or there's some missing information about how the regular expression engine differentiates a literal '#' as part of a regex or a '#' as the start of a comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#miscellaneous-constructs)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello!

So are you saying that the regex needs the whitespace around `#` to treat it like a comment? Do you have some code I can run for reproducing the behavior?
