### ISSUE TITLE
1061

### ISSUE THREAD

**Issue by 7778858** [dotnet/docs#18333]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c946d7-649b-44e4-49a9-543565904d18
* Version Independent ID: df4263c1-477a-3c32-9abe-3fcb850e6c1b
* Content: [Compiler Error CS1061](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1061.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs1061.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @7778858,
We're going to need more information on this issue in order to help out. It seems like this might have been created in error - if not please let us know. Otherwise this will automatically close out in 14 days.
