### ISSUE TITLE
State Changes section example

### ISSUE THREAD

**Issue by SoyUnEmilio** [dotnet/docs#18332]
```csharp
public class AppState
{
    public string Message { get; }

    // Lets components receive change notifications
    public event Action OnChange;

    public void UpdateMessage(string message)
    {
        shortlist.Add(itinerary);
        NotifyStateChanged();
    }

    private void NotifyStateChanged() => OnChange?.Invoke();
}
```

Where does shortlist and itinerary comes from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c195c0-99f6-64f5-66a3-4e69109dc8ee
* Version Independent ID: 24368808-4b90-f75a-e887-eb72a1c85f5b
* Content: [Build reusable UI components with Blazor](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components#feedback)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/components.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/components.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by danroth27** [comment]
Looks like `shortlist.Add(itinerary);` should be replaced with `Message = message;`.
