### ISSUE TITLE
Update Sample for 3.1 to WebApp or WebApi

### ISSUE THREAD

**Issue by ARambazamba** [dotnet/docs#18331]
It would be great if you could update the sample to something more practical like WebApp or WebApi ... Console Apps is not what most people do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Thraka** [comment]
@ARambazamba The intro points out that there is an ASP.NET specific tutorial available at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1
