### ISSUE TITLE
Version #2 should rename methods to have Async

### ISSUE THREAD

**Issue by crawfis** [dotnet/docs#18339]
Great article @BillWagner. One confusing part was the version 2 where you call what appears to be the same method from the starter (e.g., FryEggs(2)), but suddenly add the await keyword before it and assign it like the sample. I guess this is a feature, the method provider can make these asynchronous, but the caller only has to add the await keyword (or do they?). Should these methods be FryEggsAsync at this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/?WT.mc_id=EducationalAdvancedCsharp-c9-niner#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by crawfis** [comment]
Sorry. Just realized this was contributed to by 16 people not just Bill. Thanks all.

**Comment by BillWagner** [comment]
No worries @crawfis (I wrote this originally, but as Open Source, it's open to contributions)

I like your thoughts here. The method names should match the `*Async` convention once they return tasks. That would help reader's understanding of the convention.

I'll add this to our backlog and address it when we next update this article.
