### ISSUE TITLE
Add instructions to diagnose/fix errors caused by mixing Microsoft and source-built Linux packages

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#18347]
Now that source-built .NET Core is becoming more widespread (Fedora 32 and CentOS 8 semi recently), people are hitting issues when some packages on their machines come from the Microsoft repos and others from the distro archive. They don't mix well: they have different dotnet roots, `/usr/share/dotnet` vs. `/usr/lib64/dotnet`.

Instances:

* https://github.com/dotnet/core/issues/4605#issuecomment-618524478
* https://github.com/dotnet/core/issues/4655
* https://github.com/dotnet/installer/issues/9254
* https://github.com/dotnet/core/issues/5746
* https://github.com/dotnet/sdk/issues/15476
* https://github.com/dotnet/core/issues/5018#issuecomment-757400170
* https://bugzilla.redhat.com/show_bug.cgi?id=1847206
* https://stackoverflow.com/q/65422998
* https://old.reddit.com/r/Fedora/comments/kspz8i/troubles_with_installing_net
* https://github.com/dotnet/sdk/issues/15785
* https://github.com/dotnet/sdk/issues/15863

Related (how to mix source-built 3.1 with Msft 2.1, intentionally):

* https://github.com/dotnet/docs/pull/18070#issuecomment-620680909

Related (tracking non-doc fixes/mitigations):

* https://github.com/dotnet/runtime/issues/47500

Our docs should probably help people get past these problems since we're maintaining instructions for both Microsoft and source-built .NET Core. (I believe the direction will usually if not always be from Microsoft => source-build.)

/cc @omajid @NikolaMilosavljevic @dleeapho @MichaelSimons @leecow @Thraka 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14a3e31-58b4-557e-20d8-57c81ed95296
* Version Independent ID: 9a7a2a48-910f-17ce-5388-27f068f427f9
* Content: [Install .NET Core on Fedora 32 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-fedora32)
* Content Source: [docs/core/install/linux-package-manager-fedora32.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-fedora32.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
FYI lowering priority for this and pushing this out. If a team member wants to step up and document this, feel free to do so, but otherwise we'll pick up this in Sept.
