### ISSUE TITLE
Migration issue from DotNet Core 2.2 to DotNet Core 3.1

### ISSUE THREAD

**Issue by naveenaggarwal1** [dotnet/docs#18359]
I am trying to migrate my Dot net core 2.2 API to Dot net core 3.1 

Error	CS1061	'HttpContext' does not contain a definition for 'RequestEnableRewind' and no accessible extension method 'RequestEnableRewind' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)	

Error	CS0234	The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AspNetCore.Http' (are you missing an assembly reference?)	

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e30db5-f35e-a132-1711-db051ca1d719
* Version Independent ID: da256018-fd78-2eb5-4c6c-7a6e93eaeda6
* Content: [Breaking changes, version 2.2 to 3.1 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1)
* Content Source: [docs/core/compatibility/2.2-3.1.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/2.2-3.1.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@naveenaggarwal1 Can you provide the lines of code that are causing the errors?

**Comment by naveenaggarwal1** [comment]
Thanks @gewarren  below commented line was causing the error

//Allows re-usage of the stream
//httpContextAccessor.HttpContext.RequestEnableRewind();

I have replaced it with and now able to compile the project 
                  HttpRequestRewindExtensions.EnableBuffering(httpContextAccessor.HttpContext.Request);

**Comment by gewarren** [comment]
Thanks @naveenaggarwal1. @scottaddie It looks like this is a [known issue](https://github.com/dotnet/aspnetcore/issues/12505), but I'm not sure if a breaking change was logged for it?
