### ISSUE TITLE
Task compatibility

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18350]
The comments below were machine-translated

@DimTrdr commented on [Mon May 11 2020](https://github.com/dotnet/docs.ru-ru/issues/284)

You have everything ready for breakfast at the same time except the toast. Making the toast is the composition of an asynchronous operation (toasting the bread), and synchronous operations (adding the butter and the jam). Updating this code illustrates an important concept:

The composition of an asynchronous operation followed by synchronous work is an asynchronous operation. Stated another way, if any portion of an operation is asynchronous, the entire operation is asynchronous.

Tell me if the whole operation is asynchronous
async Task <Toast> MakeToastWithButterAndJamAsync (int number)
{
var toast = await ToastBreadAsync (number);
ApplyButter (toast);
ApplyJam (toast);
return toast;
}
then why use several await inside the async method when, after the first await, the operation will be asynchronous?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Асинхронное программирование на C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Mon May 11 2020](https://github.com/dotnet/docs.ru-ru/issues/284#issuecomment-626695791)

Hello, @DimTrdr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by IEvangelist** [comment]
Hi @DimTrdr,
The whole operation is considered asynchronous because if any part of it is asynchronous, all of it is. This demonstrates composition, which shows both synchronous and asynchronous together, as the toasting the bread is `async Task<Toast>` and then once the toast is toasted, you can then synchronously `ApplyButter` and `ApplyJam`. But since the entire function is `async`, the whole operation is considered asynchronous.
