### ISSUE TITLE
"the value referenced by handler remains unaffected" is ugly

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#18353]
in the doc "https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-" there is text
"the value referenced by handler remains unaffected"

I am disturbed by that proximity/competition/confusion of "value" and "reference" and suggest that phrase be rewritten unambiguously as appropriate being either a value type or a reference type but please don't jumble meaning.

BTW I was surprised that the "Null-conditional operators ?. and ?[]" did not appear in the left-hand tree and took some search digging to find relevant docs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@DickBaker 

> took some search digging to find relevant docs

Have you searched through this textbox? ("Filter by title" is not correct description, as typing `?.` there finds the proper article.)
![image](https://user-images.githubusercontent.com/15279990/81600468-ef41d500-93c9-11ea-869d-3bf0b8320dde.png)

**Comment by BillWagner** [comment]
Thanks for pointing this out @DickBaker 

I'll suggest the following re-wording:

> Because delegate instances are immutable, no thread can change the *object* referenced by the handler local variable. In particular, if the code executed by another thread unsubscribes from the PropertyChanged event and PropertyChanged becomes null before handler is invoked, the *object* referenced by handler remains unaffected. 

[Emphasis mine to illustrate the changed word]

On searching, we have an SEO concern around most operators: The characters used for operators don't perform well in search. We use the names of the operators, combined with the title filtering @pkulikov mentions above. We hope that helps. How can we better surface that feature?
