### ISSUE TITLE
Explain what happen if you override event variable before the event is fired!

### ISSUE THREAD

**Issue by Lelegithub** [dotnet/docs#18356]
Explain what happen if you override event variable before the event is fired!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc
* Version Independent ID: d2078536-1ee3-5b60-3872-f2635d245cc2
* Content: [Standard .NET event patterns](https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern#feedback)
* Content Source: [docs/csharp/event-pattern.md](https://github.com/dotnet/docs/blob/master/docs/csharp/event-pattern.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking the question @Lelegithub 

Can you provide a small example for what you mean? I want to make sure we update this to address your question.
