### ISSUE TITLE
Remove reference to fibers

### ISSUE THREAD

**Issue by davkean** [dotnet/docs#18363]
As per https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-and-unmanaged-threading-in-windows#threads-and-fibers, .NET Framework does not support Fibers, therefore the following paragraph is misleading and should be removed:

> Specifically, a sophisticated host can use the Fiber API to schedule many managed threads against the same operating system thread, or to move a managed thread among different operating system threads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e267fd4-6615-49ca-c77f-c97ecdbacb9b
* Version Independent ID: 95febe7e-6407-4be4-484d-1621db41c5e7
* Content: [Managed and Unmanaged Threading in Windows](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-and-unmanaged-threading-in-windows#threads-and-fibers)
* Content Source: [docs/standard/threading/managed-and-unmanaged-threading-in-windows.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/managed-and-unmanaged-threading-in-windows.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by richlander** [comment]
Reference: https://twitter.com/JanKotas7/status/1260023082720227328
