### ISSUE TITLE
Not updated for latest version of Driver files and .NET Core 3.1

### ISSUE THREAD

**Issue by sanket-t-shah** [dotnet/docs#18366]
.NET Core 3.1 driver is released, but this page does not cover it. Would it be possible to update the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09d9935-2cc4-e579-dd1e-120569030ccd
* Version Independent ID: 3a4307d6-10e4-546e-9cf5-ad59b62ea8f1
* Content: [Deploy a .NET for Apache Spark application to Databricks](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment)
* Content Source: [docs/spark/tutorials/databricks-deployment.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/databricks-deployment.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Thanks for bringing this to our attention, @sanket-t-shah. I've updated the doc. It should go live by tomorrow.
