### ISSUE TITLE
Chech version which is already installed

### ISSUE THREAD

**Issue by zedzhu** [dotnet/docs#18367]
How do I check which version which my computer already has?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cef2db-41a9-f3e0-7387-98611e9d1158
* Version Independent ID: 2726f502-0742-4715-4fc3-18f882178429
* Content: [Install the .NET Framework on Windows 10](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10#feedback)
* Content Source: [docs/framework/install/on-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/on-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@zedzhu This article provides the information you're looking for:

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

We should add a "See also" link to that page.
