### ISSUE TITLE
xml tag content was accidentally translated

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18360]
_From @Flithor on Monday, May 11, 2020 1:58:13 AM_

Title
> &lt;gcAllow非常大的对象&gt;元素

and tree
```
<配置>
  <运行时>
    <gcAllow 非常大的对象>
```
this issues was existed in all of sub item in page:
https://docs.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/runtime/

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2e093d16-79e3-e4eb-323f-4e4ef7fe677b
* Version Independent ID: f673a7d5-3db0-3bb2-5077-a3186871fc71
* Content: [&lt;gcAllowVeryLargeObjects&gt; 元素](https://docs.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element?view=netcore-3.1)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

_Copied from original issue: dotnet/docs.zh-cn#589_

**Comment by gewarren** [comment]
_From @srvbpigh on Monday, May 11, 2020 7:15:58 AM_

Hello, @Flithor
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by gewarren** [comment]
_From @gewarren on Monday, May 11, 2020 5:40:05 PM_

@Flithor Thanks for letting us know. Loc team - the best solution here might be to put the XML inside a code fence.

**Comment by gewarren** [comment]
_From @CeciAc on Monday, May 11, 2020 7:27:55 PM_

Hello @Flithor 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by gewarren** [comment]
_From @gewarren on Monday, May 11, 2020 7:41:34 PM_

@CeciAc This is an issue of text that shouldn't have been translated, so I'll move it to the main (English) repo so we can put the XML in code fencing. Can you reopen the issue so I can move it to dotnet/docs?

**Comment by gewarren** [comment]
_From @JasonCard on Monday, May 11, 2020 11:19:22 PM_

@gewarren I agree, code fencing would work to block XML tags from localization. Reopening the issue to move to dotnet/docs.
cc @CeciAc

**Comment by gewarren** [comment]
It looks like the request to have the localization transformer ignore anything inside `\<>` is [about to be rolled out](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/150755), so we can either change these to code blocks (and lose the linkability), or wait for this feature to be rolled out.

**Comment by JasonCard** [comment]
@gewarren Thank you for finding [that feature](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/150755) and it's status. Yes, we'll have to wait until after the Build event for roll out, but that sounds like the best solution.

**Comment by JasonCard** [comment]
@gewarren The feature has been deployed and I've confirmed with [this example in the feature](https://docs.microsoft.com/ja-jp/dotnet/framework/configure-apps/file-schema/network/specifiedpickupdirectory-element-network-settings) that it works after I re-uploaded the source file and file was re-localized. Now I need to re-upload all source files that are affected. It looks like most files under <https://github.com/dotnet/docs/tree/live/docs/framework/configure-apps> folder are affected, but do you know of any other folders/articles that are using escaped xml tags?

**Comment by gewarren** [comment]
@JasonCard Now that this is implemented, I'm wondering about the places we're using the "escaped XML syntax" to signify something other than XML, and where we *do* want that text to be localized. For example, it's very often (~1500 occurrences in this repo) used to represent placeholder text, like a version or a directory path. There's an example in [this file](https://raw.githubusercontent.com/dotnet/docs/master/docs/csharp/language-reference/keywords/switch.md) (look for `\<case label>`). In that case, we *do* want the text to be localized. We could switch to using [] brackets, which I thing is actually the preferred syntax for placeholder text, but it would be a LOT of work to do this throughout the repo. What are your thoughts?

Question: If there is whitespace following the `\<`, is that text ignored, i.e., will it still be localized? Hopefully the answer is yes, e.g. for the `<` entry in [this table](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/xaml-services/xml-character-entities#xml-character-entities).

Here are some other places we use the escaped XML tags to actually mean XML and that should be re-localized:

- https://docs.microsoft.com/ja-jp/dotnet/csharp/misc/cs1570 (localization looks pretty bad)
- https://github.com/dotnet/docs/tree/master/docs/framework/net-native directory (this content will be moving to Windows though)
- https://github.com/dotnet/docs/tree/master/docs/standard/serialization directory

**Comment by JasonCard** [comment]
@gewarren Thank you for the info. We're not aware that "escaped XML syntax" are used for localizable text, so I'll discuss this internally and get back to you. 

Yes, if there is whitespace following the `\<`, then text after that will be localized.

**Comment by JasonCard** [comment]
@gewarren I've confirmed the affected topics are now fixed. We can continue the discussion offline on the feature and examples of localizable text, but do you agree to close this issue as resolved?

**Comment by gewarren** [comment]
Yes, thanks, I'll close this issue now.
