### ISSUE TITLE
Need to clarify RegistryKey.FromHandle will always set the KeyName to empty string

### ISSUE THREAD

**Issue by tarekgh** [dotnet/docs#18370]
**Issue description**

When creating RegisteryKey from a handle using [RegistryKey.FromHandle](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.fromhandle?view=dotnet-plat-ext-3.1), the key name is always set to empty string. The documentation need to explicitly mention that.

This issue reported on the [community portal](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109953?src=WorkItemMention&src-action=artifact_link).

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core
- [ x] .NET Framework
- [ x] .NET Standard

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4221
