### ISSUE TITLE
Example for reading from IoT Hub?

### ISSUE THREAD

**Issue by sanket-t-shah** [dotnet/docs#18378]
Is there any possibility to have sample for reading from IoT / Event Hub? Both of them are suitable cases for Structured Streaming on Databricks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa17b96-900b-e157-153d-54635d864a76
* Version Independent ID: 66df9360-02ad-8c7f-9f97-d24efbfef8af
* Content: [Structured Streaming with .NET for Apache Spark tutorial](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/streaming)
* Content Source: [docs/spark/tutorials/streaming.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/streaming.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by IEvangelist** [comment]
@CamSoper is this something that you're familiar with, or might have an existing doc to point to?

**Comment by mamccrea** [comment]
Here are some resources:
[Connect your Apache Spark application with Azure Event Hubs](https://docs.microsoft.com/azure/event-hubs/event-hubs-kafka-spark-tutorial)

https://github.com/dotnet/spark/issues/325#issuecomment-552536623

We'll work on adding this scenario to our docs.

**Comment by sanket-t-shah** [comment]
Thanks.. Am working on the same as you'll be able to see from comments. Probably can contribute to create sample too. Need some help on that question.

If it's not too much to ask, can you please help to resolve error am getting there?

Best,

Sanket Tarun Shah | +91 98793 56075
________________________________

**Comment by mamccrea** [comment]
Hi @sanket-t-shah - It appears your question was resolved in the other thread, so I will proceed to close this issue. Please reopen the issue if you have any additional questions.

**Comment by sanket-t-shah** [comment]
I resolved issue on my own as didn't got any support. That's the strangest thing to have from Microsoft.
