### ISSUE TITLE
Maybe add simple example?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18372]
@Devoleksiy commented on [Tue May 12 2020](https://github.com/dotnet/docs.ru-ru/issues/285)

I need example)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [Форматы путей к файлам в системах Windows](https://docs.microsoft.com/ru-ru/dotnet/standard/io/file-path-formats#feedback)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

---

@srvbpigh commented on [Tue May 12 2020](https://github.com/dotnet/docs.ru-ru/issues/285#issuecomment-627163805)

Hello, @Devoleksiy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
@Devoleksiy Hello! I looked at the article and I see a few examples. Can you tell me what exactly you need an example of? Thanks!
