### ISSUE TITLE
Solution files containing one C# and one VB project

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18386]
In the `samples\snippets\desktop-guide\wpf`, there are currently 3 folders that are **inconsistent**.

- `data-binding-overview`, and `styles-and-templates-intro`: each one has two separate projects with one solution file containing them.

- `styles-templates-create-apply-template`: has two separate projects, but without a solution file.

One of two suggestions can be applied:

1. Remove the two sln files, because none of the projects calls the other.
1. Add a sln file to `styles-templates-create-apply-template` to be consistent.

Which of the two options do you prefer?

**Comment by IEvangelist** [comment]
Hi @Youssef1313,
I think that we should do option 1. If you create a pull request we'd happily review.

**Comment by BillWagner** [comment]
I'm assigning this to @Thraka for the moment. We should get his opinion before making a PR.

**Comment by Thraka** [comment]
Yeah removing them is fine.
