### ISSUE TITLE
Missing Reference to System.Collections.Generic;

### ISSUE THREAD

**Issue by goshmiller** [dotnet/docs#18389]
During the step where you add
using System.Text.Json;
we also need to add
using System.Collections.Generic;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @goshmiller We appreciate it.

I've added this to our backlog, and added the "up for grabs" label in case community members want to address this before we do.

Thanks again.
