### ISSUE TITLE
C# and VB samples of the same article are in different directories

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18383]
https://github.com/dotnet/docs/blob/ba436c714a692f286582d1eb8052b89174b58127/docs/core/tutorials/library-with-visual-studio.md

```
   [!CODE-csharp[ClassLib#1](../../../samples/snippets/csharp/getting_started/with_visual_studio_2017/classlib.cs)]
   [!CODE-vb[ClassLib#1](../../../samples/snippets/core/tutorials/vb-library-with-visual-studio/stringlibrary.vb)]
```

which one should be moved where?
I also think it's good to unify the file name because the code is the same.

**Comment by BillWagner** [comment]
Thanks for writing this @Youssef1313 

[This section of the contributor guide](https://docs.microsoft.com/contribute/dotnet/dotnet-contribute#example-structure) highlights the new structure. Both samples should move under the folder where this article is located.

I've added the "up for grabs" label. If you want to submit a PR for this issue, let me know, and I'll assign it to you.

**Comment by Youssef1313** [comment]
@BillWagner, does that mean that at a later time, there shouldn't be a *samples* directory in the root of the repo? because all the samples will be within the same article directory?

**Comment by BillWagner** [comment]
@Youssef1313 

> does that mean that at a later time, there shouldn't be a samples directory in the root of the repo? because all the samples will be within the same article directory?

Yes, that's the direction we're heading.

**Comment by Youssef1313** [comment]
That's much better than before. Happy to see docs improving :heart:

**Comment by tdykstra** [comment]
I'm starting on the Visual Studio Code version of this tutorial, which will use the same code, so I'll take care of moving these snippets in the same PR.
