### ISSUE TITLE
explain how to do this directly in the .csproj file

### ISSUE THREAD

**Issue by timrobinson33** [dotnet/docs#18395]
For the increasing numbers of people using Visual Studio Code or the dotnet command line, who need to edit the csproj file directly, it would be useful to explain how to do this:

&lt;PropertyGroup&gt;
    &lt;StartupObject&gt;xxx&lt;/StartupObject&gt;
  &lt;/PropertyGroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5453dbc-08db-b9b2-5198-50bff608b5c8
* Version Independent ID: f182cda3-c40b-4216-6614-49da5eb0e3c8
* Content: [-main (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/main-compiler-option#feedback)
* Content Source: [docs/csharp/language-reference/compiler-options/main-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/main-compiler-option.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @timrobinson33 

I've added this to our todo list. I've also added the "up for grabs" label, in case community members want to create a PR for this.
