### ISSUE TITLE
Missing csproj files

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18396]
Samples that are missing proj files are:

- *docs\\samples\\snippets\\standard\\datetime\\json\\csharp* (except *datetime-converter-examples*)
- *docs\\samples\\snippets\\standard\\interop*
- *docs\\samples\\snippets\\standard\\io\\file-names*
- *docs\\samples\\snippets\\standard\\reflection*

**Comment by IEvangelist** [comment]
Hi @Youssef1313,
Thank you for raising this issue. I've added the `up-for-grabs` label so that any community contributor can create a pull request to add these, in the meantime - we'll prioritize this work accordingly.
