### ISSUE TITLE
Duplicated pattern explanation

### ISSUE THREAD

**Issue by IvanBil** [dotnet/docs#18401]
"(\s)?	Match zero or one white-space character" is duplicated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#PositiveGroup)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @IvanBil,
Thank you for posting this issue. Could you please share the revised code that you're suggesting? Where would this be duplicated, what portion of the Regex? I've created a [sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0AKgKYAew+ASsQOYQA2AhmAKKkAOYxAztwJYB7KNwDc6dHADMuBNjaMAtu3rF0Ab3TYtiBJq0a0Wo7iQ52jYMGJgo2ALy44AIgA6AIwAUL9moCS3AHEuYgBrAF8Aai9uAEoAfhiI7zUABQATMJduLx9/ACFGfgBjABkLPigwxKcxQ2MTHAr2CGB7bCdALOBARuBAEeAu7EAc4C7ADuBhrsB64EB+4EBe4GwAWmxCAAtibACBbnZiemwBADNsAFkLYBWAdxrxOuM8AE4PahoyfH9j4CKljyaWgBpsc0s1igMRiImwAHpwdgACJ8TZMACe3EWkGI+D02DC6DCQA=) and naively removed the last occurrence - is this what you're referring to?

**Comment by IvanBil** [comment]
I mean the text appears 2 times in the article
![image](https://user-images.githubusercontent.com/39484335/81824271-f4279580-953d-11ea-93c9-d562aa260f7c.png)

**Comment by Thraka** [comment]
@IvanBil This is just the way the breakdown is explaining the regex. It's walking you through each piece of the regex, even if something appears twice (as it does in the actual regex).
