### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by raupes** [dotnet/docs#18402]
sampleMethod() is a method an normally written in capital letters. When or why did this change? Should not be the case here.
same for doSomething() in the interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/object-oriented-programming#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/object-oriented-programming.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @raupes,
Thank you for posting this, it is a valid concern - and I'm happy to address this.
