### ISSUE TITLE
Samples Repo Archived?

### ISSUE THREAD

**Issue by antmdvs** [dotnet/docs#18421]
There are 2 references to https://github.com/dotnet/dotnet-template-samples on this page. The repo has a banner that reads "This repository has been archived by the owner. It is now read-only." which causes me to question whether some of it's content is out-of-date. Is that the case? Has it been moved/superseded? Is it still relevant, just read-only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/custom-templates.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **tdykstra**

**Comment by antmdvs** [comment]
@sayedihashimi

**Comment by sayedihashimi** [comment]
@vijayrkn owns the samples now, I am now working in a different area.

**Comment by vijayrkn** [comment]
@grinrag and team maintains the templating repo and related content. The samples repo is currently not actively maintained so some of the contents can go out of date easily with template engine product changes.

**Comment by antmdvs** [comment]
Thanks. Do you think there should be a disclaimer to that effect on the docs page in question?

**Comment by vijayrkn** [comment]
@antmdvs - I would hope so.

**Comment by Thraka** [comment]
@vijayrkn I would seriously consider updating this repo and maintaining it. It's a gold mine for examples of creating templates and as soon as it goes out of date it's going to be completely worthless.
