### ISSUE TITLE
macOS "Download and manually install" steps should use tar.gz, not manually extract the installer (pkg)

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#18428]
The macOS "Download and manually install" steps use the installer (`pkg`), not the tar.gz that should normally be used for manual install.

```
sudo installer -pkg ~/Downloads/dotnet-sdk.pkg -target $HOME/dotnet
```

In the table, on the left you get the pkg, on the right the tar.gz:

![image](https://user-images.githubusercontent.com/12819531/81890446-9c078800-956b-11ea-974f-a99bcf5f5f39.png)

The instructions say to download a binary release (tar.gz), so at the moment they're telling you to download the right thing, but the script uses the wrong thing.

(The Linux pivot directs to and uses tar.gz files as expected.)

/cc @mairaw @NikolaMilosavljevic 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac255410-47e8-7c14-b14f-06dfe3e424f9
* Version Independent ID: 09a819ef-b5af-43f7-e744-60ca6f667a45
* Content: [Install .NET Core SDK on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-macos)
* Content Source: [docs/core/install/sdk.md](https://github.com/dotnet/docs/blob/master/docs/core/install/sdk.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for noticing that.
