### ISSUE TITLE
Missing documentation on how to run .NET Core unit tests sequentially

### ISSUE THREAD

**Issue by binhnguyen1984** [dotnet/docs#18432]
I want to run unit tests sequentially in .net core but could not find any solutions. The solutions available on the Internet do not work for me. I would expect a detailed discussion on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb70526f-d02c-2b6c-3d34-0f4cac5809f0
* Version Independent ID: e4443d71-7131-ae9b-447d-9ac0762a99fc
* Content: [Running selective unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests#feedback)
* Content Source: [docs/core/testing/selective-unit-tests.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/selective-unit-tests.md)
* Product: **dotnet-core**
* GitHub Login: @smadala
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @binhnguyen1984,
Thank you for posting this issue, I will work on adding these details as part of the docs / guidance.
