### ISSUE TITLE
Removal of Microsoft.DotNet.PlatformAbstractions Package

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs#18438]
## Removal of Microsoft.DotNet.PlatformAbstractions Package

We will stop building new versions of [Microsoft.DotNet.PlatformAbstractions](https://www.nuget.org/packages/Microsoft.DotNet.PlatformAbstractions/) in .NET 5

### Version introduced

.NET 5.0 Preview 6

### Old behavior

New versions of the `Microsoft.DotNet.PlatformAbstractions` library were produced alongside new versions of .NET Core.

### New behavior

New functionality and major versions of this library will no longer be produced.

### Reason for change

As part of the [ongoing repository consolidation effort](https://github.com/dotnet/announcements/issues/119) in .NET 5, we have been examining the libraries that were previously in [dotnet/core-setup](https://github.com/dotnet/core-setup) and deciding on their long-term strategy/goals.

The [Microsoft.DotNet.PlatformAbstractions](https://www.nuget.org/packages/Microsoft.DotNet.PlatformAbstractions/) library has considerable overlap with APIs that are already established in the System.* namespaces. Also, some PlatformAbstractions APIs were not designed with the same level of scrutiny and long-term supportability that the rest of the System.* APIs are designed. For example, PlatformAbstractions uses an enum named `Platform` to describe the current Operating System Platform. This design was explicitly rejected when designing `RuntimeInformation.IsOSPlatform(OSPlatform)` to allow for new platforms and to allow the most flexibility in the future.

To resolve this situation, we have ensured that the scenarios enabled by `Microsoft.DotNet.PlatformAbstractions` are now possible without it and plan to stop building new versions of `Microsoft.DotNet.PlatformAbstractions` in .NET 5. The existing versions will continue to work, even in .NET 5, and be serviced along with previous versions of .NET Core. But new functionality won't be added to the library. New functionality will be added through other libraries and APIs.

### Recommended action

You can continue to use older versions of the library if they meet your requirements.

When the older version no longer meets your requirements, you can replace usages of the PlatformAbstractions APIs with the recommended API in the following table.

| PlatformAbstractions API                   | Recommended Replacement                                       |
|--------------------------------------------|---------------------------------------------------|
| ApplicationEnvironment.ApplicationBasePath | [AppContext.BaseDirectory][1]                     |
| HashCodeCombiner                           | [System.HashCode][2]                              |
| RuntimeEnvironment.GetRuntimeIdentifier()  | [RuntimeInformation.RuntimeIdentifier][3]         |
| RuntimeEnvironment.OperatingSystemPlatform | [RuntimeInformation.IsOSPlatform(OSPlatform)][4]  |
| RuntimeEnvironment.RuntimeArchitecture     | [RuntimeInformation.ProcessArchitecture][5]       |
| RuntimeEnvironment.OperatingSystem         | [RuntimeInformation.OSDescription][6] ** See Note |
| RuntimeEnvironment.OperatingSystemVersion  | [RuntimeInformation.OSDescription][6] and [Environment.OSVersion.Version][7] ** See Note |

[1]: https://docs.microsoft.com/dotnet/api/system.appcontext.basedirectory
[2]: https://docs.microsoft.com/dotnet/api/system.hashcode
[3]: https://github.com/dotnet/runtime/pull/34206
[4]: https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform
[5]: https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture
[6]: https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.osdescription
[7]: https://docs.microsoft.com/dotnet/api/system.environment.osversion

#### Note on OperatingSystem and OperatingSystemVersion

The majority of use cases for these APIs are for display purposes: displaying to a user, logging, telemetry, etc. Making runtime decisions on an operating system version (especially one that is of type `string`) is not a recommended practice. We have made enhancements to `Environment.OSVersion.Version` to return the correct version for Windows and macOS Operating Systems. However, for most Unix distributions, what is considered to be the "OS Version" is not as straight-forward. Do you want the Linux kernel version? The distro version? etc. For most Unix platforms, `Environment.OSVersion.Version` and `RuntimeInformation.OSDescription` continue to return the version returned by [uname](https://www.unix.com/man-page/sunos/2/uname/). For getting Linux distro name and version information, the recommended approach is to read the [`/etc/os-release`](http://man7.org/linux/man-pages/man5/os-release.5.html) file.

### Category

- Core .NET libraries

### Affected APIs

All under the `Microsoft.DotNet.PlatformAbstractions` namespace.

* ApplicationEnvironment.ApplicationBasePath
* HashCodeCombiner
* RuntimeEnvironment.GetRuntimeIdentifier()
* RuntimeEnvironment.OperatingSystemPlatform
* RuntimeEnvironment.RuntimeArchitecture
* RuntimeEnvironment.OperatingSystem
* RuntimeEnvironment.OperatingSystemVersion

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@eerhardt Do you know which preview version this change will be introduced in?

**Comment by eerhardt** [comment]
I just opened the PR that removes the library - https://github.com/dotnet/runtime/pull/36707. Assuming the PR gets merged in the next few days, it will be in `5.0.0-preview.5`.
