### ISSUE TITLE
found an error on this page. lol

### ISSUE THREAD

**Issue by SumDjurc** [dotnet/docs#18440]
In the example box (i &lt; 9) the sign should be changed to &gt; to get that output.
no problem! I love the site. It's helping me learn. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5b436f-bd9b-e6c5-9859-f71cf9ee71bc
* Version Independent ID: f384b21d-5bee-6a14-d0c8-aadf61691c1e
* Content: [continue statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/continue#feedback)
* Content Source: [docs/csharp/language-reference/keywords/continue.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/continue.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mccap079** [comment]
Actually `<` is correct in order to get the output: 
```
/*
Output:
9
10
*/
```
While `i` is less than `9`, execute `continue`, thus skipping the call to print the index value. So the index value will only begin printing once `i` is no longer less than `9`.

**Comment by IEvangelist** [comment]
Hi @SumDjurc,
Thank you for posting this issue. However, it is not incorrect. Checkout this [sharplab.io instance](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ6oEMC2BTAZwAcsBjPAAgA0L0BvdCpixCgITDywGsAVQ4I2YM0zMSyQA2FgBYKAWSwBLKAAoAlEPEUR27QDMA9mAqqVwCkooBeCkgDcligB5bSAAyOlAam+bRemK6gXpK+qZWzhQAnP4hesHxgaSGUMAqEHj2WklMAL45uXBI0Wbq2QHxBRiVIQD0dRQA0nh4RBTAABaUKVAEhgA2lIZEeFCW4wAmeABGEADmFDiG0wB0hXrFpQBEAAqcBAQUWFAAnhTceOfAhhR4AB5KwKvb5Rv5OdV5QA) with the code and output. Take care
