### ISSUE TITLE
Inconsistency in example output

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#18449]
This is a trivial thing, but I thought I would mention it anyway. The example for the Inline Options section has two peieces of output. The first without inline options set the second with them set. The idea is to show the difference between the two.

The example has been written to surround the output of the second set with single quotes, where as the first has not. This makes it look to someone skim reading like the single quotes are part of the effect of the options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86649f60-e90f-a5ea-a9f3-f12fb9d0a561
* Version Independent ID: a4dd6724-5bd6-c83b-8256-1a68e718eb8f
* Content: [Miscellaneous Constructs in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/miscellaneous-constructs-in-regular-expressions#feedback)
* Content Source: [docs/standard/base-types/miscellaneous-constructs-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/miscellaneous-constructs-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!
