### ISSUE TITLE
VB.NET is incorrectly omitted

### ISSUE THREAD

**Issue by InteXX** [dotnet/docs#18443]
The documentation fails to mention that *.vbproj files are supported as well.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Easy enough to fix, but before that, I'll wait someone to confirm if **only** vbproj is missing, or fsproj is missing too.
cc: @cartermp Can you confirm if dotnet pack works for fsproj files or not?

**Comment by cartermp** [comment]
Yes, `dotnet pack` works for all project files (csproj, vbproj, fsproj)

**Comment by Youssef1313** [comment]
@cartermp, Thanks. Opened #18446
