### ISSUE TITLE
Combine existing Framework Libraries doc with migrated equivalent doc

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#1844]
Existing doc: https://docs.microsoft.com/dotnet/articles/standard/framework-libraries
Equivalent doc being migrated will be at: https://docs.microsoft.com/dotnet/articles/standard/class-library-overview

- [ ] Incorporate content from the migrated doc in the existing one
- [ ] Retire the migrated doc

**Comment by CarinaClaesson** [comment]
Commenting as part of the Docs Sprint.
