### ISSUE TITLE
.NET Core project files

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18447]
Does the information in [Additions to the csproj format for .NET Core](https://docs.microsoft.com/dotnet/core/tools/csproj) applies to vbproj and fsproj as well?

If yes, then the article needs to be updated and mention that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#feedback)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @gewarren, you're going to be replacing this article, right?

**Comment by gewarren** [comment]
Yes, see #18198.
