### ISSUE TITLE
Output folders do not nest anymore

### ISSUE THREAD

**Issue by adhaliwal34** [dotnet/docs#18451]
There is a line which says:
> In a web project, if the output folder is in the project folder, successive `dotnet publish` commands result in nested output folders.

This doesn't seem to happen anymore and the suggested fix is not necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#feedback)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Which SDK version are you using?

**Comment by adhaliwal34** [comment]
`dotnet publish --configuration Release --runtime ubuntu.18.04-x64 --self-contained false`

project `.csproj` file:
`<TargetFramework>netcoreapp3.1</TargetFramework>`

```
C:\Users\user>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```

**Comment by tdykstra** [comment]
Is your project a web project? Nesting only happens on a web project, and I verified it still happens in 3.1.202 in a web project.

**Comment by adhaliwal34** [comment]
It is a web project `.csproj` has this:
`<Project Sdk="Microsoft.NET.Sdk.Web">`

I re-read the doc and I think all is well the issue can be closed.

The doc says `To avoid nesting publish folders, specify a publish folder that is not directly under the project folder`. My publish folder is not **directly** under the project folder so the behaviour is correct.

I assume you tested with `<project folder>\publish`?

Steps to reproduce:
I already have this folder from a previous publish `<project folder>\bin\Release\netcoreapp3.1\ubuntu.18.04-x64\publish`

I run this `dotnet publish --configuration Release --runtime ubuntu.18.04-x64 --self-contained false`

is there a `<project folder>\bin\Release\netcoreapp3.1\ubuntu.18.04-x64\publish\publish`? No.

Make some changes to the project.

I run this `dotnet publish --configuration Release --runtime ubuntu.18.04-x64 --self-contained false`

Any `<project folder>\bin\Release\netcoreapp3.1\ubuntu.18.04-x64\publish\publish` now? Still no.

**Comment by adhaliwal34** [comment]
Apologies for the bother :)

**Comment by tdykstra** [comment]
No problem 😄 The word "directly" is easy to miss, so to help avoid misunderstandings in the future I'll put that word in bold.

**Comment by adhaliwal34** [comment]
Good idea, thank you!
