### ISSUE TITLE
[C# Guide] Explain that `null` is a constant pattern, and won't match any type

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1845]
Our samples on pattern matching are correct, and we mention that `null` doesn't match any type in an `is` or `case` pattern matching expression.  

[this topic](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md) should add a paragraph or two explaining the behavior for `null`. We can expand with the justifications:

1. The existing `is` expression always returned `false` for `null`. It is more consistent for the new extensions to have the same semantics on null.
2. Having `null` never match a type means that developers do not need the explicit null check after matching a pattern. That is a factor in favor of this design.
3. *If* non-nullable types are added to the language, this decision will make everyone happy.

**Comment by cartermp** [comment]
What about the default case?

```csharp
var foo = SomethingWhichReturnsNull();
switch (foo)
{
    case Bar: ...
    case Baz: ...
    case Qux: ...
    default: ... // I'd expect code to execute here
}

In general this seems like the problem we have in F# when we pattern match on objects and test for the subtype, but the resultant type could still be null.  You can't be exhaustive with this, but it still results in the need to have a "gotta catch the null" bucket if you don't have a preceding check.  Well, either that or a bug in the code.  It's a pretty strong motivation for different types than those which can be implicitly null.

**Comment by BillWagner** [comment]
There might be different semantics. We should discuss to make sure we point out the distinctions. 

Consider this (very contrived) C#:

```csharp
var s = MethodWhichReturnsStringOrNull();
switch (s)
{
    case string str: 
        Console.WriteLine($"{str} is not null");
        break;
    case null:
        Console.WriteLine("method returned null");
    case default:
        Console.WriteLine("won't get here in this example.");
}
```
