### ISSUE TITLE
Unable to install on raspberry pi

### ISSUE THREAD

**Issue by minecraftchest1** [dotnet/docs#18459]
I am able to follow the guide successfully, until I install the sdk. I am able to select the sdk with the tab key at the bash prompt. However, it says it can't find the package.
Here is the output.
pi@raspberrypi:~ $ sudo apt install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Dani21** [comment]
At the beginning of the guide:

> Package manager installs are only supported on the x64 architecture. Other architectures, such as ARM, must [manually install the .NET Core SDK](https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux#download-and-manually-install)  or [manually install the .NET Core Runtime](https://docs.microsoft.com/en-us/dotnet/core/install/runtime?pivots=os-linux#download-and-manually-install).

The processor is ARM, so you’ll need to do it manually.

**Comment by reyesje08** [comment]
I encountered this issue and resolved myself - https://github.com/dotnet/docs/issues/18352

**Comment by IEvangelist** [comment]
Hi @minecraftchest1,

Thank you for posting an issue. Based on comments from @reyesje08 (#18352) and @Dani21, it seems as though you this is expected behavior and you should be able to resolve this. If you still need assistance, we can reopen this issue. I'm going to close the issue for now.
