### ISSUE TITLE
Diagrams don't display well in browser dark theme

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#18453]
https://github.com/dotnet/runtime/issues/36425#issuecomment-629242079

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66
* Version Independent ID: d53a0764-9f27-16b3-c40a-9627dd1bcc0d
* Content: [Introduction to character encoding in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction#feedback)
* Content Source: [docs/standard/base-types/character-encoding-introduction.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-encoding-introduction.md)
* Product: **dotnet**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
@tdykstra, May you assign this to me? I'll get time to fix that by tomorrow.

**Comment by tdykstra** [comment]
I already have the revised image files from the artist, I just need to make a PR.
