### ISSUE TITLE
error in code sample

### ISSUE THREAD

**Issue by ericsampson** [dotnet/docs#18465]
In the code sample that shows the compiler-generated equivalent, the scope-creating outer braces that are called out*, are missing in the code.

 " The code example earlier expands to the following code at compile time (*note the extra curly braces to create the limited scope for the object):"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @ericsampson for pointing this out.

I've opened #18480 to address this.
