### ISSUE TITLE
C# 8: Positional patterns: First example given even works with C# 7

### ISSUE THREAD

**Issue by jaliyaudagedara** [dotnet/docs#18468]
The following sample given under C# 8 Positional patterns, even works with C# 7.
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#more-patterns-in-more-places

> Some types include a Deconstruct method that deconstructs its properties into discrete variables. When a Deconstruct method is accessible, you can use positional patterns to inspect properties of the object and use those properties for a pattern. Consider the following Point class that includes a Deconstruct method to create discrete variables for X and Y:
```
public class Point
{
    public int X { get; }
    public int Y { get; }

    public Point(int x, int y) => (X, Y) = (x, y);

    public void Deconstruct(out int x, out int y) =>
        (x, y) = (X, Y);
}
```
- .csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>7.0</LangVersion>
  </PropertyGroup>
</Project>
```

**Comment by svick** [comment]
It does, because that sample doesn't actually use any C# 8.0 features. It's the `GetQuadrant` method that uses the C# 8.0 feature "positional patterns" and the `Point` class is necessary for that to work.

**Comment by jaliyaudagedara** [comment]
I see, I was a bit confused with the documentation. All good, thanks for the clarification!
