### ISSUE TITLE
Method signature

### ISSUE THREAD

**Issue by aaltayyar** [dotnet/docs#18463]
In Methods section it's written "The signature of a method doesn't include the return type.", but on C# concepts -&gt; Types (C# Programming Guide) page, it's written "The types of method parameters and return values are specified in the method signature.".
My question: is the method signature includes return type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181f41d-b6ce-ad66-084e-8d2b514b87e2
* Version Independent ID: 494c4344-b752-4f86-5b66-1ef4b81c1e75
* Content: [Classes and Objects in C# - A tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#feedback)
* Content Source: [docs/csharp/tour-of-csharp/classes-and-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/classes-and-objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
In the [C# specification](https://github.com/dotnet/csharplang/blob/892af9016b3317a8fae12d195014dc38ba51cf16/spec/basic-concepts.md):

> The signature of a method consists of the name of the method, the number of type parameters and the type and kind (value, reference, or output) of each of its formal parameters, considered in the order left to right.
