### ISSUE TITLE
[C# Guide] `goto` in switch statement patterns must go to a constant label

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1846]
This restriction seemed arbitrary to people. It feels like an arbitrary restriction. 

But, it becomes hard to understand what it would actually mean to `goto` a non-constant label. It seems arbitrary, and could inadvertently cause coding errors, including infinite loops. 

We should clearly state that this isn't allowed, and have a brief explanation about why

**Comment by BillWagner** [comment]
I moved this to the backlog and added @rpetrusha as an assignee.  We should cover this when we update the language reference pages for `switch` and `case`.

**Comment by BillWagner** [comment]
@rpetrusha I moved this to the July milestone. I can update the referenced pages. Let me know if that's already in progress for you, or if I should do this one.

**Comment by rpetrusha** [comment]
@BillWagner, it's not in progress, though I think that I still can get it done in time.
