### ISSUE TITLE
More code samples needed

### ISSUE THREAD

**Issue by PeterHuberSg** [dotnet/docs#18478]
After using c# for 15 years, I am usually able to understand most new language features. But giving just the syntax of the Recursive Pattern Matching, I can't imaging how the resulting code looks like. Please add code samples to every case you describe here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a3af6a-59dd-775a-a008-1530bba493f5
* Version Independent ID: 95639e9c-9432-b07b-5fc2-f30d7bab0123
* Content: [Recursive pattern matching - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#feedback)
* Content Source: [proposals/csharp-8.0/patterns.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@PeterHuberSg This document is the language spec for pattern matching. Its purpose is to describe the language changes needed to support pattern matching.

We've added [this article](https://docs.microsoft.com/dotnet/csharp/tutorials/pattern-matching) that I think provides all the examples you're looking for.  If so, we'll close this. If not, let me know what information you still need.

Thanks again.

**Comment by PeterHuberSg** [comment]
Agreed. I didn't follow that link, sorry.

Thanks for your swift response.
