### ISSUE TITLE
Using List.Length instead of List.Any()

### ISSUE THREAD

**Issue by ZeVS777** [dotnet/docs#18477]
Do you recommend using allTasks.Any() instead of allTasks.Length &gt; 0? I think that documentation must provide the right path to write code in programming guide. Why not to use Length where it is possible? People learning this languages then face the job interviews and failed at this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Do you mean `Count`, not `Length`? I think List<T> doesn't have a `Length` property but have `Count`.

I'll try to run a benchmark test against both cases.

**Comment by Youssef1313** [comment]
Count seem to be faster:

![image](https://user-images.githubusercontent.com/31348972/82206206-176c8f00-9908-11ea-8d58-bfeb3e1f5d50.png)

But let me ping @stephentoub before I make a PR.

**Comment by pkulikov** [comment]
Dancing away: what if to move the Console.WriteLine calls inside the corresponding async methods? Then, code in general would be shorter. In particular, tasks.WhenAll becomes possible without existing while loop?

**Comment by Youssef1313** [comment]
@pkulikov, I like that!
While moving the `Console.WriteLine` calls to the corresponding async method, The issue https://github.com/dotnet/docs/issues/16987 will get fixed too.

**Comment by stephentoub** [comment]
If a type exposes Length/Count, from a micro-optimization perspective it's preferable to use that instead of Any(); from a reasonability perspective, I expect developer's opinions reasonably differ about which is more clear. In this code sample, I highly doubt the difference in throughout will be meaningful; even so, it's fine to change from my perspective.

**Comment by BillWagner** [comment]
I'm fine will all the changes @pkulikov and @Youssef1313 have suggested.

Thanks all.

**Comment by pkulikov** [comment]
@Youssef1313 my guess is that you wanted to submit a PR?

**Comment by Youssef1313** [comment]
@pkulikov I haven't started on it yet, I'm okay if you want to take it. If not, inform me and I'll try to start soon.

**Comment by pkulikov** [comment]
@Youssef1313 no, I don't want to take it, please proceed.

**Comment by Youssef1313** [comment]
> In particular, tasks.WhenAll becomes possible without existing while loop?

While working on the issue, I found that WhenAll was already explained, then WhenAny was introduced as another option. So, I'll keep the code as-is for this part. and just move the snippets, make minor changes, and use .Count instead of .Any().
