### ISSUE TITLE
dotnet nuget add source doesnt' exist...

### ISSUE THREAD

**Issue by Tyler-IN** [dotnet/docs#18476]
> `dotnet add nuget source "https://repo.url/here/index.json" --name wtf --username wtf --password wtf --store-password-in-clear-text --configfile nuget.config`

```
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
```

Have .NET Core SDKs for 2.0 up to 3.1.2 installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a08a1fa5-6267-3122-a377-5ba5b8503a07
* Version Independent ID: 1d2f0343-bda9-7e7a-34a9-f097635ff155
* Content: [dotnet nuget add source command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source#feedback)
* Content Source: [docs/core/tools/dotnet-nuget-add-source.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-add-source.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Try `dotnet nuget` add instead of `dotnet add nuget`.

**Comment by Sojaner** [comment]
> Try `dotnet nuget` add instead of `dotnet add nuget`.

Not working.

**Comment by tdykstra** [comment]
I can't repro the failure.  When I use the command you show in the description but reverse the order of "nuget" and "add", it works.  What output do you see?

**Comment by Sojaner** [comment]
As you can see in the following picture, the `dotnet add nuget` command requires a project to work, however, I'm trying to add the source globally.

![image](https://user-images.githubusercontent.com/1634835/82646487-f613e780-9c14-11ea-8822-3decfbdba7cf.png)

The `dotnet nuget add` is not recognized either as you can see.

And I can't install the nuget tool either. See here:

![image](https://user-images.githubusercontent.com/1634835/82647097-f8c30c80-9c15-11ea-9a0c-6e8a81140640.png)

**Comment by tdykstra** [comment]
As this is a NuGet command and there doesn't seem to be an error in the dotnet documentation, I'm  moving this issue to the nuget/home repo -- https://github.com/NuGet/Home/issues/9597

**Comment by JeFFBlanco** [comment]
I encountered the same issue; just make sure you're on the latest/greatest version of the [.NET Core SDK](https://dotnet.microsoft.com/download) -- I just downloaded .NET Core SDK `3.1.300` and `dotnet nuget` now has `add` command:

```sh
$ dotnet nuget

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.300

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
NuGet Command Line 5.6.0.5

Usage: dotnet nuget [options] [command]

Options:
  -h|--help  Show help information
  --version  Show version information

Commands:
  add      Add a NuGet source.
  delete   Deletes a package from the server.
  disable  Disable a NuGet source.
  enable   Enable a NuGet source.
  list     List configured NuGet sources.
  locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
  push     Pushes a package to the server and publishes it.
  remove   Remove a NuGet source.
  update   Update a NuGet source.

Use "dotnet nuget [command] --help" for more information about a command.
```

**Comment by Sojaner** [comment]
> I encountered the same issue; just make sure you're on the latest/greatest version of the [.NET Core SDK](https://dotnet.microsoft.com/download) -- I just downloaded .NET Core SDK `3.1.300` and `dotnet nuget` now has `add` command:
> 
> ```shell
> $ dotnet nuget
> 
> Welcome to .NET Core 3.1!
> ---------------------
> SDK Version: 3.1.300
> 
> Telemetry
> ---------
> The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
> 
> Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
> 
> ----------------
> Explore documentation: https://aka.ms/dotnet-docs
> Report issues and find source on GitHub: https://github.com/dotnet/core
> Find out what's new: https://aka.ms/dotnet-whats-new
> Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
> Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
> Write your first app: https://aka.ms/first-net-core-app
> --------------------------------------------------------------------------------------
> NuGet Command Line 5.6.0.5
> 
> Usage: dotnet nuget [options] [command]
> 
> Options:
>   -h|--help  Show help information
>   --version  Show version information
> 
> Commands:
>   add      Add a NuGet source.
>   delete   Deletes a package from the server.
>   disable  Disable a NuGet source.
>   enable   Enable a NuGet source.
>   list     List configured NuGet sources.
>   locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
>   push     Pushes a package to the server and publishes it.
>   remove   Remove a NuGet source.
>   update   Update a NuGet source.
> 
> Use "dotnet nuget [command] --help" for more information about a command.
> ```

Great! Will give it a try soon. Thanks!
