### ISSUE TITLE
.Net Framework docs don't have correct TOCs

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1848]
It seems docs.ms contains a new set of .Net Framework documentation, but the TOC does not behave correctly for them:

For the [main article](https://docs.microsoft.com/en-us/dotnet/articles/framework/index), the TOC shows only the pre-existing Docker articles:

![](https://cloud.githubusercontent.com/assets/287848/24728888/291d8a98-1a5c-11e7-86b4-741b00330738.png)

For other articles, like [Getting Started](https://docs.microsoft.com/en-us/dotnet/articles/framework/get-started/index), the TOC contains a seemingly random set of just 4 articles:

![](https://cloud.githubusercontent.com/assets/287848/24728955/6e417864-1a5c-11e7-96c5-3d949588bb71.png)

**Comment by BillWagner** [comment]
@svick Thanks for pointing this out.

The changes for that didn't make the last publishing wave. They are coming soon.

**Comment by mairaw** [comment]
We did improve the TOC but we still have content missing from there. We need to review this.
