### ISSUE TITLE
data-binding-overview project generates warnings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18488]
The data-binding-overview sample project in desktop-wpf generates warnings:

```
AuctionItem.cs(10,50): warning CS0067: The event 'AuctionItem.PropertyChanged' is never used
ManualBinding.cs(9,24): warning CS0649: Field 'ManualBinding.myText' is never assigned to, and will always have its default value null
```

Also, the C# sample has some unused files that doesn't exist in the equivalent vb sample. It also has some extra unused fields:

```csharp
        public int StartPrice { get; set; } = 50;

        public DateTime StartDate { get; set; } = DateTime.Now;
```

**Comment by Thraka** [comment]
Are you referring to the files in the snippets folder here in this repo? If so, these aren't meant for general consumption, they're purely for compiling the snippets used via docs. The separation of samples and snippets we made earlier in the year was to reinforce this idea.

**Comment by Youssef1313** [comment]
@Thraka, [This](https://github.com/dotnet/docs/tree/master/samples/snippets/desktop-guide/wpf/data-binding-overview) is the folder I was referring to. Good to know they're not meant for general consumption. But still wondering why the C# folder isn't in-sync with the VB one?

Also, some files there are not referenced in the article, is there an on-going work to include them in the article? if not, is there a reason for their existence of they can be deleted safely?

**Comment by Youssef1313** [comment]
To be more specific, here are the files that exists in the C# folder but not the VB one:

- AutoConvertPropertyToColor.xaml
- AutoConvertPropertyToColor.xaml.cs
- DataValidation.xaml
- DataValidation.xaml.cs
- DateConverter.cs
- EmptyBinding.xaml
- EmptyBinding.xaml.cs
- SpecialFeatures.cs

The files that're not in sync

- App.xaml vs Application.xaml (different StartupUri)
- AuctionItem (more properties in the C# version)

**Comment by Thraka** [comment]
The xaml displayed isn't cs/vb specific so I only need to code it once for validation, in the cs project. Snippets are only used to validate that code compiles correctly, that is all. So in instances where very little is used, I don't need to recreate it across all languages. For example, `AuctionItem` demonstrated shows `CurrentPrice` in the article for code (code only, not when it's used in xaml) and therefor the vb project doesn't need the other properties to compile the code.

https://docs.microsoft.com/en-us/dotnet/desktop-wpf/data/data-binding-overview#filtering

Snippets may have all sorts of supporting files to make sure the projects compile, and so they all don't need to be referenced by the articles.
