### ISSUE TITLE
Ugly monkey see, monkey do

### ISSUE THREAD

**Issue by orcmid** [dotnet/docs#18489]
This elaborate process is not something I find heartening about simply wanting to explore F#.  I got through it successfully.  I immediately ran into two disturbing facets, apart from the elaborate dance with dotnet commands.

 1. I wanted to break down those long strings into something that fit more nicely into my VS Code editor window.  
 2. The lack of punctuation and reliance on offside-spacing for everything is distressing.  Reading Don Syme, I understand that is meant to be a feature.  I find it distressing with regard to wanting code to be beautiful.

As a fan of functional programming, I am distressed by how unappealing this is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836d726d-1f95-51e7-c5c3-a7200adc5772
* Version Independent ID: 3e9e6e89-7017-7a7c-faea-4c0e76cef442
* Content: [Get started with F# with command-line tools](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line)
* Content Source: [docs/fsharp/get-started/get-started-command-line.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-command-line.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
https://github.com/dotnet/docs/pull/20087 addresses some of the quirks with the long lines. Your other points are inherent to the design of the .NET CLI and F#, so they're not really actionable.

**Comment by orcmid** [comment]
> #20087 addresses some of the quirks with the long lines. Your other points are inherent to the design of the .NET CLI and F#, so they're not really actionable.

I was thinking of the inexplicable dependencies, especially for a rarefied purpose that is unlikely to be useful on the learning curve of an F# novice/learner.  If you say that is for a fluent C# user who understands those dependencies and usages, it would be valuable to say something about it.
