### ISSUE TITLE
out parameters could be explained to help the reader understand the example better

### ISSUE THREAD

**Issue by DocumentationLive** [dotnet/docs#18495]
Up until now in the C# Concepts section of the documentation we have not been introduced to "out parameters". I think it would be great if a brief description of what they do is included before being used as an example, as well as a link to read more on them. I was able to guess what was happening with some thought, but I will need to go confirm my guesses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#tuple-projection-initializers)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @DocumentationLive 

This article should link to the reference on `out` parameters. That way those readers unfamiliar with that topic can find the more detailed information they need easily.
