### ISSUE TITLE
There is no reason for constructors to have two TOC entries in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1850]
It seems the TOC for members of a type in the new API reference is always two levels: first level for the kind of member (properties, methods, etc.) and second level for distinct names of mebers (if the member has overloads, they share a single page and thus also a second-level TOC entry).

This makes sense for members with actual names, but I think it doesn't make sense for constructors. Constructors of a type are not distinguished by name, only by overloads, so there will always be at most one page for constructors. Because of that, I think it would make sense to remove the second level entry for constructors and keep only the first level one.

Example:

![](https://cloud.githubusercontent.com/assets/287848/24749179/693ab18a-1ac2-11e7-802e-b4b2822c4430.png)

**Comment by rpetrusha** [comment]
I agree with you, @svick. Thanks for opening this issue. I've created an internal feature request -- #965346: "Remove extra constructor-related entry from TOC", which will allow us to track the issue internally.

**Comment by mairaw** [comment]
They now changed to one level:
https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.-ctor?view=netframework-4.7

I still think they should have just kept the word constructors and not add the type name in that entry. It looks noisy with long type names:
![image](https://user-images.githubusercontent.com/12971179/30459472-bd29ec30-9965-11e7-86e0-d90d9f5c018c.png)

What do you guys think? @rpetrusha @svick

**Comment by svick** [comment]
@mairaw I agree. It's better this way, but it would be even better without the type name.

**Comment by mairaw** [comment]
I'll keep this one open then until that is fixed. I'll need to open a new separate request for them.

**Comment by mairaw** [comment]
Noting here the bug ID for the additional request: 1156157

**Comment by mairaw** [comment]
The engineering team completed the work. Thanks!
