### ISSUE TITLE
\n in MSDN example turns into newline in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1851]
[The example for `Activator.CreateInstance(Type)` on MSDN](https://msdn.microsoft.com/en-us/library/wccyzw83(v=vs.110).aspx#Anchor_3) contains this code:

```c#
        Console.WriteLine("\nObjects and their default values:\n");
```

[The same example in the new API reference](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netframework-4.7#System_Activator_CreateInstance_System_Type_) contains instead:

```c#
        Console.WriteLine("
Objects and their default values:
");
```

It looks like `\n`s in the MSDN example were turned to actual newlines in the API reference. I think this should be fixed, especially considering that the API reference example is not valid C# code.

**Comment by rpetrusha** [comment]
@svick Thanks so much for noticing this. I've opened a bug with the build team. So that we can track it, the internal bug number is #9653451 -- '"\n" character combination rendered as a line feed in source code"

**Comment by svick** [comment]
Another example of this: `string path = @"c:\temp\MyTest.txt";` in [snippet](https://github.com/dotnet/docs/blob/7341cfd/samples/snippets/csharp/VS_Snippets_CLR/StrmReader%20Peek/CS/strmreader%20peek.cs#L10) is [rendered as](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.peek?view=netstandard-1.3#examples) `string path = @"c:    emp\MyTest.txt";`.

**Comment by mairaw** [comment]
@svick this has been fixed. So I'm closing this issue. Thanks again for reporting this!
