### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mr-intj** [dotnet/docs#18514]
&gt; DO only use LayoutKind.Explicit in marshaling when your native struct is also has an explicit layout, such as a union.

"is also has"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693350de-e55a-32d9-80fb-14aee1434800
* Version Independent ID: 9fb68cd6-ce65-ac2e-05b4-74a8c9172627
* Content: [Customizing structure marshaling - .NET](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/customize-struct-marshaling)
* Content Source: [docs/standard/native-interop/customize-struct-marshaling.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/customize-struct-marshaling.md)
* Product: **dotnet**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
