### ISSUE TITLE
Would it be possible to have a machine-readable format for at least the Minimum versions?

### ISSUE THREAD

**Issue by FISHMANPET** [dotnet/docs#18529]
I have an automated process that checks to verify that the `latest` version of .Net has been installed, and I'd like to make the determination on what is `latest` a little more dynamic.  Currently I can grab the source of this page, and do some string magic against the raw markdown to read the data in the Minimum Version table, but any changes to the formatting of this page would probably break whatever I write.  Maybe there could be a JSON file committed with the source repo that has the minimum version info?  It could be manually updated, same as when this page is updated, but then I know I could just grab that file and convert it from JSON and get the values from there, instead of relying on parsing this document.

Maybe there might be a use for the 1.0-4.0 data, and the table of all the release values as well could be useful in JSON?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@BillWagner or @thraka Any thoughts on this one? This would be unusual to include a JSON file in the docs repo.

**Comment by BillWagner** [comment]
Adding @leecow 

I think there may be a machine readable format of this info in one of the product repositories.

**Comment by FISHMANPET** [comment]
To be clear I don't think it needs to be in this repo specifically, or be JSON specifically even, those were just some suggestions.

**Comment by leecow** [comment]
With every release, we publish files that can be used for keeping up with the latest. The following redirect URLs are all pointed at the respective asset on https://dotnetcli.blob.core.windows.net/dotnet/release-metadata. Alternatively, these files can be accessed from github.com/dotnet/core/release-notes. 

https://aka.ms/dotnet/releases/index/json
https://aka.ms/dotnet/releases/latest/lts
https://aka.ms/dotnet/releases/latest/current
https://aka.ms/dotnet/releases/2.1/json
https://aka.ms/dotnet/releases/3.1/json
https://aka.ms/dotnet/releases/5.0/json

**Comment by FISHMANPET** [comment]
@leecow Those are all .Net Core, I'm interested in the .Net Framework, which is what this page is about.

This isn't particularly important in the grand scheme of things, major .net releases are pretty infrequent, and I know the next major release will be the cross platform 5.0 (which will come with a whole new way of detecting the version!).  I don't know if there will ever be a .Net Framework 4.9, but I wouldn't be surprised if there ends up being a 4.8.1

**Comment by leecow** [comment]
@FISHMANPET, sorry for missing that. I'm not aware of a similar mechanism for .NET Frame and, as you say, Framework updates are becoming quite rare. With respect to .NET 5.0, that is already included in the assets I listed.

**Comment by adegeo** [comment]
I'm going to close this is as out of scope. Sorry.
