### ISSUE TITLE
`--deprecated` option not documented

### ISSUE THREAD

**Issue by Zastai** [dotnet/docs#18534]
The current .NET Core 3.1 SDK (3.1.300) includes the following in `dotnet list package -h`:
```
--deprecated                              Lists packages that have been deprecated.
```

However, this option is not included in the documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8400fd6a-d987-1056-283f-9364fbce3c86
* Version Independent ID: 3d4b052c-33fa-cc83-4df6-4a3341f12763
* Content: [dotnet list package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package)
* Content Source: [docs/core/tools/dotnet-list-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-list-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Zastai Thanks for reporting that, we'll add the missing option the next time we update the doc.
