### ISSUE TITLE
Fix compile

### ISSUE THREAD

**Issue by v-radelg** [dotnet/docs#18539]
@cdalmasso commented 7 hours ago — with docs.microsoft.com

To compile when using List&lt;Repository&gt; it is necessary to add
using System.Collections.Generic;
using WebAPIClient;
in order to compile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @cdalmasso 

I've added this to our backlog, and added the "up for grabs" label if community members want to submit a PR for this.

**Comment by bergerb** [comment]
#18612 

Fixing how we create the project addresses this issue in the tutorial.  Sorry I added this to another PR.
