### ISSUE TITLE
dotnet list reference does not support solutions as advertised

### ISSUE THREAD

**Issue by Zastai** [dotnet/docs#18532]
The documentation (both this help page and the tool's built-in usage text) claims that you can pass a solution.
However, when you do so, it errors out with
```
PS ...> dotnet list xxx.sln reference
Project `xxx.sln` is invalid.
Usage: dotnet list <PROJECT | SOLUTION> reference [options]

Arguments:
  <PROJECT | SOLUTION>   The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.
```

Similarly, when run in a directory containing a solution but not a project, you get:
```
PS ...> dotnet list reference
Could not find any project in `...`.
Usage: dotnet list <PROJECT | SOLUTION> reference [options]

Arguments:
  <PROJECT | SOLUTION>   The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.
```

Note: this is with the just-released 3.1.300 SDK.
A quick test with 5.0-preview4 shows the same behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22484a57-f15f-8d0c-6f18-ccc96a5b7215
* Version Independent ID: 90ddffec-4bfd-d7ea-6923-567ea6683c47
* Content: [dotnet list reference command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-reference)
* Content Source: [docs/core/tools/dotnet-list-reference.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-list-reference.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that - I'll remove the reference to Solution as an argument. When I run the command with the --help option it already omits reference to Solution.
