### ISSUE TITLE
Minor typo in docs for --output-directory

### ISSUE THREAD

**Issue by Zastai** [dotnet/docs#18552]
> `dotnet test` always _run_ tests from the output directory.

That should probably be

> `dotnet test` always _runs_ tests from the output directory.

instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#feedback)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Thraka** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by Zastai** [comment]
I considered doing that but assumed there would be procedures in place etc, which is why I created a ticket instead.
PR entered now. I didn't touch the ms.date line; I assume that's maintained by tooling. Incidentally, what tooling is used to process things like the <xref>s?

**Comment by tdykstra** [comment]
ms.date updates are manual but we don't always update it for small changes -- it's mainly for significant updates or when we've done a review to verify that the doc is up-to-date.

> what tooling is used to process things like the s?

If you mean how do we correct typos like that, it's by creating a PR, having someone review it, and having someone merge it -- it's all a manual process.

**Comment by Zastai** [comment]
Ah github removed the tag - I was referring to the xrefs etc that get resolved to links on docs.ms.com

**Comment by tdykstra** [comment]
That's done automatically when the Markdown files are converted to HTML by OPS (the Open Publishing System).
