### ISSUE TITLE
Source has spaces

### ISSUE THREAD

**Issue by WinformsWizard** [dotnet/docs#18554]
How to remove a source if it's name has spaces? I tried typing it with spaces but it didn't work.
I also tried removing the spaces, and replacing them with underscores

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb4bcff-70ad-2655-f246-9e586940119a
* Version Independent ID: 168ac3d5-8a09-5584-c4c6-78cabbe39818
* Content: [dotnet nuget remove source command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-remove-source)
* Content Source: [docs/core/tools/dotnet-nuget-remove-source.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-remove-source.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Put the name in quotes, eg.:  `dotnet nuget remove source "name with space"`

**Comment by WinformsWizard** [comment]
thank you!
