### ISSUE TITLE
Link to Affected APIs goes to incorrect location

### ISSUE THREAD

**Issue by mrlife** [dotnet/docs#18551]
The "Affected APIs" at the end of this paragraph should go to the first #affected-apis anchor after the link but goes to the first #affected-apis anchor on the page, since #affected-apis is repeated and not unique.

> SignalR: UseSignalR and UseConnections methods removed
In ASP.NET Core 3.0, SignalR adopted endpoint routing. As part of that change, the UseSignalR, UseConnections, and some related methods were marked as obsolete. In ASP.NET Core 5.0, those obsolete methods were removed. For the full list of methods, see **Affected APIs**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f68af3a-3848-48ef-c24b-cf33b880ca1b
* Version Independent ID: 580c061d-20e5-248c-a24f-7a48a684c7e3
* Content: [Breaking changes, version 3.1 to 5.0 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#affected-apis)
* Content Source: [docs/core/compatibility/3.1-5.0.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/3.1-5.0.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mrlife Good catch, thank you. @scottaddie Can you fix this one? Maybe add an explicit anchor or something.

**Comment by gewarren** [comment]
I verified this is working now. https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/signalr-usesignalr-useconnections-removed
