### ISSUE TITLE
a little fault about instructions in the  struct "Char"`s functions

### ISSUE THREAD

**Issue by wybgsn** [dotnet/docs#18564]
**Visual Studio Version**:
16.5.5
**Summary**:
There`s a little fault in System.Char, a lot of functions` instructions written by Chinese in that file  
discribe the name of parameter as "true“, actually it should be "c" or "s".

**Steps to Reproduce**:

1. 

2. 

3. 

**Expected Behavior**:
如果 c 是一个字母，则为 true；否则为 false。(Others all like this)
**Actual Behavior**:
![1](https://user-images.githubusercontent.com/57448396/82557918-3042a200-9b9f-11ea-85da-bf6a79825d24.png)
**User Impact**:
uhhh... just a little misunderstand or .. funny?

**Comment by wybgsn** [comment]
> Thanks for the issue.
> 
> Looks like this should be transferred to runtime. That repo doesn't come up in the list for me. Can anyone on this repo do that?

https://docs.microsoft.com/zh-cn/dotnet/api/system.char.isletter?view=netframework-4.8
I'm sorry, but I'm just a beginner. I saw this only occasionally, and I didn't know how to get in touch with the people who managed it. I would appreciate it very much if you could help me to tell them about it.

**Comment by BillWagner** [comment]
Issue moved to [dotnet/runtime #37012](https://github.com/dotnet/runtime/issues/37012) via [**ZenHub**](https://www.zenhub.com/)
