### ISSUE TITLE
dotnet-install.ps1 doesn't have parameter -Help

### ISSUE THREAD

**Issue by abatishchev** [dotnet/docs#18563]
Steps to reproduce the issue:

1. Download the script:
```powershell
Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
```
2. Run the script with parameter `-Help` per the doc
```powershell
 ./dotnet-install.ps1 -Help
```

Actual behavior:

&gt;dotnet-install.ps1: A parameter cannot be found that matches parameter name 'Help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@donJoseLuis can you help with this?

**Comment by abatishchev** [comment]
@donJoseLuis can you help with this?

**Comment by abatishchev** [comment]
@donJoseLuis ping.

**Comment by bozturkMSFT** [comment]
We should remove `-Help` switch from the docs.
Proper way to get help on a powershell scripts is:
``` pwsh
Get-Help ./dotnet-install.ps1
```

**Comment by tdykstra** [comment]
Thanks @bozturkMSFT -- What about the bash script?

**Comment by bozturkMSFT** [comment]
For bash `--help` is a valid option. So we should keep it in the docs.
