### ISSUE TITLE
clarification on content

### ISSUE THREAD

**Issue by ranjan-ranjan** [dotnet/docs#18572]
Under [Test the asynchronous solution](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await#test-the-asynchronous-solution), its given that 

> In the synchronous version, the text box is cleared just before the counts appear for the second time, when the downloads are completed and the UI thread is free to do other work. In the asynchronous version, the text box clears immediately after you choose the **Start** button.

I think it's not possible as we have already used
`// Disable the button until the operation is  #complete.
startButton.IsEnabled = false;`
and
`// Reenable the button in case you want to run the operation again.
startButton.IsEnabled = true;`

So, how can we click on the **Start** button, when it is disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494fdee9-0e2c-55bc-dfc0-bc1e5809476f
* Version Independent ID: 3f6b5873-7f2c-a463-bcd3-8093f4af9a2a
* Content: [Walkthrough: Accessing the Web by Using async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await#convert-startbutton_click-to-an-asynchronous-method)
* Content Source: [docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @ranjan-ranjan 

The purpose of using async calls in UI applications is to enable the UI to remain responsive. That's true in this application. But, the only action in the UI is to start the same action again. The sample should be expanded to have other actions possible while the download takes place. Possibly a timer, or some other action that could happen while the download is in progress.
