### ISSUE TITLE
ADO.NET

### ISSUE THREAD

**Issue by larinlonappan** [dotnet/docs#18574]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0be085-e177-a711-c00c-9a994e40f3e7
* Version Independent ID: 6a508a11-62bb-eaff-c8ff-6c84ca35adc4
* Content: [Data and modeling - .NET](https://docs.microsoft.com/en-us/dotnet/framework/data/)
* Content Source: [docs/framework/data/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/index.md)
* Product: **dotnet-framework**
* GitHub Login: @stevestein
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@larinlonappan Can you provide some more information about the issue?
