### ISSUE TITLE
ml.net

### ISSUE THREAD

**Issue by abdelzahermohamed** [dotnet/docs#18595]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4185570-21cc-dcdb-62fd-d05bceb62f81
* Version Independent ID: 4f0fe52a-a771-d044-593d-2bb65df15e0d
* Content: [Data transformations - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/transforms)
* Content Source: [docs/machine-learning/resources/transforms.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/transforms.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @abdelzahermohamed 

Is there any specific feedback or something you wanted to mention with regards to this document?

**Comment by luisquintanilla** [comment]
Closing this issue since there's no feedback or response. Feel free to open another issue if you have additional feedback @abdelzahermohamed
