### ISSUE TITLE
Change "ID" to "Id"

### ISSUE THREAD

**Issue by robloo** [dotnet/docs#18607]
Identifier should be abbreviated "Id" instead of "ID" following Microsoft's naming guidelines. 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d85f4d3-fbb1-2aba-9acb-a1b5122bc484
* Version Independent ID: 19163540-1a7d-2524-370a-8b20d5735d90
* Content: [Auto-Implemented Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/auto-implemented-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/auto-implemented-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This was fixed in #18610.  

While I agree with the comment that "there may be other occurrences", a quick search didn't turn any up.
