### ISSUE TITLE
Affect instead effect

### ISSUE THREAD

**Issue by AlexZazu** [dotnet/docs#18618]
Not big deal. Just a confusion with the word affect and effect in the first paragraph at the beginning of the page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4dcb4da-bdb8-853d-678a-9c5130921ecb
* Version Independent ID: 1dbe0544-77c2-c70f-8406-2bca85e914e8
* Content: [Passing Value-Type Parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-value-type-parameters)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/passing-value-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/passing-value-type-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Do you want to submit a Pull Request to make the change? If you do and don't know how, you can follow [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).

**Comment by AlexZazu** [comment]
Ok, I will try. I am a beginner, I just joined GitHub recently, but I will see if I can do it. I first will read the guide below.

Thanks for your suggestion!!
Alex Zazueta.


________________________________

**Comment by IEvangelist** [comment]
Closed by #18626
