### ISSUE TITLE
Another non-existent constant and .NET class?

### ISSUE THREAD

**Issue by mr-intj** [dotnet/docs#18616]
This time it's the mapping of HRESULT constant (preprocessor symbol) `COR_E_VTABLECALLSNOTSUPPORTED` and .NET exception class `VTableCallsNotSupportedException`.

I can't find any definition for either symbol or class, either by searching the SDK header files, or by searching online sites and source control repositories.

I can't find any evidence that a `VTableCallsNotSupportedException` class exists in .NET.

Once again, I do find a few references to both of these online, but only to the extent that they are mentioned as mapping to one another (so probably copied from this page), but never with any value for `COR_E_VTABLECALLSNOTSUPPORTED` or additional namespace information for the VTableCallsNotSupportedException type.

When `COR_E_VTABLECALLSNOTSUPPORTED` does appear in a source file (among a list of other HRESULT constants), it is _always_ commented out. No one else appears to be able to identify an actual value for this supposed constant either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2763c768-604b-2d58-7d5f-048a95657ebe
* Version Independent ID: c9755c11-4c6a-9ae6-9e74-99f52a177ff9
* Content: [How to: Map HRESULTs and Exceptions](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-map-hresults-and-exceptions)
* Content Source: [docs/framework/interop/how-to-map-hresults-and-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/how-to-map-hresults-and-exceptions.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by jeffschwMSFT** [comment]
I searched .NET Framework's source and did not find it either.  

cc @davidwrighton @jkotas

**Comment by jkotas** [comment]
This doc must have been written in early .NET Framework 1.0 days and not updated since then. There are number of exception types that we present in early .NET Framework 1.0 previews and removed for .NET Framework 1.0 release (e.g. `MulticastNotSupportedException`, `WeakReferenceException`). 

Also, the doc says that the table provides complete mapping between exceptions and `HRESULT`s. That is also incorrect. The table is far from complete.

**Comment by jkotas** [comment]
This should be addressed

**Comment by jkotas** [comment]
PR #22487
