### ISSUE TITLE
Another vapor-constant and class?

### ISSUE THREAD

**Issue by mr-intj** [dotnet/docs#18615]
The table on this page maps the HRESULT identified by the `COR_E_WEAKREFERENCE` preprocessor symbol to the .NET `WeakReferenceException` exception class.

I can't find any definition for that preprocessor symbol (either by searching the SDK header files, or by searching online sites and source control repositories.

I can't find any evidence that a `WeakReferenceException` class exists in .NET.

Again, I can find references to both of these online, but only to the extent that they are mentioned as mapping to one another (so probably copied from this page), but never with any value for `COR_E_WEAKREFERENCE` or additional namespace information for the WeakReferenceException type.

It's interesting to note that when the `COR_E_WEAKREFERENCE` symbol appears in source files (among a list of other HRESULT constants), it is _always_ commented out. No one else appears to be able to identify an actual value for this supposed constant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2763c768-604b-2d58-7d5f-048a95657ebe
* Version Independent ID: c9755c11-4c6a-9ae6-9e74-99f52a177ff9
* Content: [How to: Map HRESULTs and Exceptions](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-map-hresults-and-exceptions)
* Content Source: [docs/framework/interop/how-to-map-hresults-and-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/how-to-map-hresults-and-exceptions.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
I only found it in mono, [here](https://github.com/mono/mono/blob/85056b086f950799b79a8f999e9a3edd406b0785/mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs#L1788), but it's commented. And the class doesn't exist. Just commented with that link in case it can help for further investigation.

**Comment by Thraka** [comment]
@jeffschwMSFT could you comment on this?

**Comment by jeffschwMSFT** [comment]
I searched .NET Framework's source and did not find it either.

cc @davidwrighton @jkotas

**Comment by davidwrighton** [comment]
Agreed. This is a documentation error. That HRESULT does not appear to exist anywhere.

**Comment by adegeo** [comment]
This was fixed by #22487
