### ISSUE TITLE
EventHandler is not a handler and neither is handler

### ISSUE THREAD

**Issue by pdschuller** [dotnet/docs#18624]
The delegate, EventHandler is not a handler at all, in the sense of "a method that handles an event".  So I think there should be a paragraph near the top that helps the reader wrap their head around this:

_Microsoft has used the name EventHandler for the delegate name and this can be confusing for those new to this topic.  An instance of the EventHandler delegate creates/publishes the event and has the method that fires the event.  It should not be confused with the method that handles the event._

Also the example uses this line:

`   EventHandler<CustomEventArgs> handler = RaiseCustomEvent;`

Which piles on the confusion.  This is another case where the word handler is used for something that is not a handler.

Otherwise a very helpful example/tutorial.  I definitely notice MS improving in this area.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e8321f-5516-e451-5429-750d49f0ebed
* Version Independent ID: 1fd093e9-f47c-ffdd-91e9-5039c3ccde61
* Content: [How to publish events that conform to .NET Framework Guidelines - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines)
* Content Source: [docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @pdschuller 

We should change the name of the `handler` variable, and add a note similar to the text you've suggested.
