### ISSUE TITLE
Place parameters on a new line for long member definitions advice can lead to compiler warnings

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#18637]
Following up on https://github.com/fsprojects/fantomas/issues/868, the style guide mentions 

> Place parameters on a new line for long member definitions
If you have a very long member definition, place the parameters on new lines and indent them one scope.
This also applies to constructors:

```fsharp
type C(
    aVeryLongType: AVeryLongTypeThatYouNeedToUse
    aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse
    aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse) =
    // ... the body of the class follows
```
(this sample is also missing `,` after each parameter)

but if you put this in practice the following example leads to a compiler warning:
```fsharp
type VersionMismatchDuringDeserializationException (
    message: string,
    innerException: Exception)
    =
    inherit Exception(message, innerException)
```

```
  <Fantomas>\FakeHelpers.fs:4916 Possible incorrect indentation: this token is offside of context started at position (148:52). Try indenting this token further or using standard formatting conventions.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#place-parameters-on-a-new-line-for-long-member-definitions)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, the indentation is actually off in that sample since it should be a few spaces to the right

**Comment by nojaf** [comment]
@cartermp thanks for clarifying this.
Where would the return type be placed if there is one?
And does the equal sign always follow the closing `)`?

I would assume it would be something like:

```fsharp
type VersionMismatchDuringDeserializationException(message: string,
                                                   innerException: System.Exception) =
    inherit System.Exception(message, innerException)

type C() =
    member _.LongMethodWithLotsOfParameters(aVeryLongType: int,
                                            aSecondVeryLongType: int,
                                            aThirdVeryLongType: int) : int =
        aVeryLongType + aSecondVeryLongType + aThirdVeryLongType 
```

**Comment by cartermp** [comment]
In this case, the return type should probably be as you specified it, yes.

**Comment by cartermp** [comment]
Updated the PR.

**Comment by nojaf** [comment]
Many thanks for this @cartermp!
