### ISSUE TITLE
Add visuals to better illustrate timing of task execution

### ISSUE THREAD

**Issue by arielvsp** [dotnet/docs#18632]
[Enter feedback here]
A nice introduction, but using a timeline drawing for each one of the examples would be a great help for understanding of differences in the execution. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Ping @IEvangelist Are you still working on updating this article?

If not, let's add it to the backlog.

**Comment by IEvangelist** [comment]
> Ping @IEvangelist Are you still working on updating this article?
> 
> If not, let's add it to the backlog.

I am not, this was mentioned as part of that effort - but it was out of scope. I agree, we should add it to the backlog.
