### ISSUE TITLE
optimization not right

### ISSUE THREAD

**Issue by trivalik** [dotnet/docs#18653]
The hint to use the static Regex.IsMatch does not improve anything, since the cache is updated in the constructor of Regex class. Hint should be removed or updated that cache size influence last stored regex's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14698b87-a995-290f-bdd7-9c2d6867704c
* Version Independent ID: f199cd3f-8dce-ad4e-9712-3545e35557e7
* Content: [Best Practices for Regular Expressions in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices)
* Content Source: [docs/standard/base-types/best-practices.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/best-practices.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Browsing through the code I'm not seeing what you're talking about. Can you elaborate? I cannot find where the regex class is adding to the cache. Just browsing through the code of both the cache and the regex constructor, I see more overhead on the regex constructor.

**Comment by trivalik** [comment]
The static calls "IsMatch" ... do also just call the constructor. The only exception I see is the constructor with no arguments, for this is no optimiziation done, but this is not public.
