### ISSUE TITLE
COMPlus_gcConcurrent environment variable incorrect values

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docs#18656]
The `COMPlus_gcConcurrent` environment variable documentation says the values should be `false` and `true`, even though all other boolean environment variables require `0` and `1`. 

I believe the documentation for `COMPlus_gcConcurrent` should also say `0` and `1`.

Cheers,
Kristian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e544aba5-cfe6-1790-023e-bec738182ea8
* Version Independent ID: 8392a21a-8404-d352-ffb1-d6373bbbdd1b
* Content: [Garbage collector config settings - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector)
* Content Source: [docs/core/run-time-config/garbage-collector.md](https://github.com/dotnet/docs/blob/master/docs/core/run-time-config/garbage-collector.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I see what you are saying. @Maoni0 Can you confirm if the values for the `COMPlus_gcConcurrent` environment variable should be `0` and `1`?

**Comment by Maoni0** [comment]
that is correct, @gewarren. or we if want to be pedantic :smile: we could say if you set COMPlus_gcConcurrent to a non zero value it will enable concurrent GC. you could set it to 4 and it also enables concurrent GC. I'm fine with saying 1 or 0 though so it's easier to remember.
