### ISSUE TITLE
dotnet restore example with path didn't work

### ISSUE THREAD

**Issue by bhanuteja-dev** [dotnet/docs#18652]
[Enter feedback here]
I have tried the following command from 1 level up.
dotnet restore ~/projects/app1/app1.csproj

It kept on complaining the  error MSB1009: Project file does not exist.

But when I tried the following
dotnet restore ./projects/app1/

it was able to restore.

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

Please let me know if you require more details.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
What platform are you on?

If you run `ls ~/projects/app1` from the same command prompt does it show the project file?

**Comment by bhanuteja-dev** [comment]
I am currently on Windows 10, tried the below on cmd and new terminal. 

when I tried `dir "~/projects/app1"`, it appends ~ to the file path like this.
D:\repos\dotnet\~\projects\app1 and complains File not found.

When I try dir `"./projects/app1"` it lists out all the folders in the app1 folder.

I tried your command on WSL, and it works.

**Comment by tdykstra** [comment]
The tilde doesn't work in Windows the way it works in Linux.  Why are you trying to use it instead of `./projects/app1/`?

**Comment by bhanuteja-dev** [comment]
It's just the habit of mine coming from ASP.NET referencing image and content files, where ~ refers to the root of the application directory. :)

I usually use Visual Studio and not cmd. Recently started using cmd and WSL.

My feedback would be to mention along the lines of "Use `~` in linux and `.` for windows" above the example to not trip the users who are not CMD users.

**Comment by tdykstra** [comment]
Good point, that example needs clarification, I'll put this in the backlog so we address it next time the article is updated.
