### ISSUE TITLE
Comment Tags missing

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#18659]
There are more tags than described here and in the spec.
Please add the tags, which are not yet documented, into the spec and and to the documentation tag reference (a sub-page of this).
So far I found: &lt;e&gt;, &lt;i&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306c4f25-192e-0980-c663-d829f38ef7c4
* Version Independent ID: 8918a37b-cbfa-33f1-21e2-6bf5ea3ccb54
* Content: [XML documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/)
* Content Source: [docs/csharp/programming-guide/xmldoc/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mr-intj** [comment]
Isn't that just HTML?

I think HTML tags are valid within XMLDoc, but they're not XMLDoc tags...

**Comment by TobiasKnauss** [comment]
@mr-intj: possible, I don't know much about HTML. Where does the documentation say that HTML is allowed? And I doubt that all HTML is possible, it likely is just a small subset.

**Comment by svick** [comment]
@TobiasKnauss 

[Here:](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)

> The compiler will process any tag that is valid XML. The following tags provide generally used functionality in user documentation.

**Comment by TobiasKnauss** [comment]
@svick Thanks for the explanation, that makes sense. However, this should be written in that page also.
And I still would like to know which tags are supported by Visual Studio itself when showing the intellisence docu in tooltips. This actually was my intention for writing the first post, but I didn't recall the external documentation tools because we only use our XML docu inside VS so far.

**Comment by BillWagner** [comment]
Great discussion here.

What we've traditionally done in this area is cover the rules the compiler follows for C# documentation comments. There's a small set of recommended tags, and as pointed out, any valid XML tag can be used.  That's correct, but not as helpful.

We'll be constantly chasing other innovations if we try to update this page with an exhaustive list of tags used by different tools (some by Microsoft, others by community) to build documentation. Instead, in the programming guide, I recommend we link to the docs on the most popular tools where they cover what tags each supports.  My initial list would be 

- Sandcastle
- DocFx

Are there others?

**Comment by svick** [comment]
@BillWagner 

> Are there others?

As mentioned above: VS/Roslyn. The VS QuickInfo for C#, which is powered by Roslyn, supports quite a few HTML-like tags (e.g. `<b>` or `<i>`), which are not mentioned in the spec or in the document we're talking about. If anyone is interested, [here is the relevant Roslyn code](https://github.com/dotnet/roslyn/blob/ffbb9c7e/src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs#L321).

**Comment by TobiasKnauss** [comment]
@svick  I have found
- "br"
- "i" / "em"
- "u"
- "b" / "strong"

Are there others that I have missed?
Please add them to the documentation, and (@BillWagner) I suggest you also add them to the spec, because they are part of the code.

**Comment by svick** [comment]
@TobiasKnauss Apart from the ones you listed, there's also a and tt. AFAAICT, that's all of them.

**Comment by TobiasKnauss** [comment]
@svick yes, I've seen them, but they are "just" alternatives for other tag names, which are documented already. Nevertheless, they should also appear in the documentation.
