### ISSUE TITLE
What are the functions of local services?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18667]
The comments below were machine-translated

@DragonLord17 commented on [Tue May 26 2020](https://github.com/dotnet/docs.es-es/issues/166)

What are the functions of local services?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ac412e65-fc71-0072-ba33-e532be0e94b5
* Version Independent ID: 5b7e0817-b120-8a45-054f-6f13161dbbf8
* Content: [Desarrollar aplicaciones de servicios de Windows](https://docs.microsoft.com/es-es/dotnet/framework/windows-services/)
* Content Source: [docs/framework/windows-services/index.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/windows-services/index.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

---

@srvbpigh commented on [Wed May 27 2020](https://github.com/dotnet/docs.es-es/issues/166#issuecomment-634721240)

Hello, @DragonLord17
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
😦 I can't find anything the page that uses the word "local". I unfortunately don't know what this issue is referring to. I think translation is losing something here. :(
