### ISSUE TITLE
Comment Tags missing

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#18660]
see https://github.com/dotnet/docs/issues/18659

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e862820-a044-b4e5-63de-9c84778a3b2c
* Version Independent ID: d0b7bf75-d2c3-5960-a4ca-0e560839045b
* Content: [Documentation comments - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments)
* Content Source: [spec/documentation-comments.md](https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm closing this based on these thoughts: https://github.com/dotnet/docs/issues/18659#issuecomment-635401173

In the language spec, we should continue to scope the discussion to the language rules only.
