### ISSUE TITLE
Cannot be executed according to the steps in the tutorial

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18670]
The comments below were machine-translated

@cnazev commented on [Wed May 27 2020](https://github.com/dotnet/docs.zh-cn/issues/606)

Follow the tutorial steps
The debugging section is inconsistent with the screenshot in the tutorial
There is a prompt Open a file which can be debugged or run.
The Run and Debug buttons below are not available.

In addition, the title of this tutorial is ‘Creating a .NET Core solution in macOS using Visual Studio Code’
But the article is basically the same as the development under cli, only in the built-in terminal of Visual Studio Code.
There is no mention of how to open a multi-project solution in Visual Studio Code and how to open a project in the solution.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [教程：使用 Visual Studio Code 在 macOS 中创建 .NET Core 解决方案 - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---

@srvbpigh commented on [Wed May 27 2020](https://github.com/dotnet/docs.zh-cn/issues/606#issuecomment-634739123)

Hello, @cnazev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by tdykstra** [comment]
@CeciAc The observations are all correct. I am in the process of creating a new series of Visual Studio Code tutorials that will parallel the existing sequence of Visual Studio 2019 tutorials, and the new tutorials will replace this one.  When the replacements are published, I'll add links to them in this issue.

**Comment by tdykstra** [comment]
PR #18701 has created a new series of VS Code tutorials that work with a solution file and can be used on macOS as well as Linux and Windows:

* https://docs.microsoft.com/dotnet/core/tutorials/library-with-visual-studio-code
* https://docs.microsoft.com/dotnet/core/tutorials/testing-library-with-visual-studio-code
