### ISSUE TITLE
Explain variable naming constaints

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#18672]
I recommend adding a section that identifies variable naming constraints. Something along the lines of "You should avoid using these reserved words in a variable name: <bulleted list or link to doc here>. If you have to for interoperability with another language, prefix the variable name with `@`".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this. I'm updating the tour now, so I'll add this to those tasks.
