### ISSUE TITLE
The asset pick-publish-target.png contains a visual artifact on the top left corner

### ISSUE THREAD

**Issue by AngelosP** [dotnet/docs#18687]
The asset pick-publish-target.png contains a visual artifact on the top left corner. Looks like a leftover from a copy/paste operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449b8ce2-80b3-9bfa-6d7f-3e8ac8a86e16
* Version Independent ID: 31264b07-1aeb-b3f0-1126-f25e578f6d50
* Content: [Publish your .NET Core Hello World application with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/publishing-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Thanks for reporting that, I'll include a fix with some other changes I'm making in that tutorial now.
