### ISSUE TITLE
.NET Framework 4.8 Windows 10 2004 Release Key

### ISSUE THREAD

**Issue by elyoh** [dotnet/docs#18684]
The documentation currently gives `528209` as the value of the release key for the Windows 10 May 2020 Update.  This does not match with the release key in the actual release which is `528372`.

![win10](https://user-images.githubusercontent.com/14054078/83157633-bf017280-a0fb-11ea-91e9-1cb61d3605a8.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you @elyoh .

**Comment by gewarren** [comment]
@nakarnam Can you confirm that the Release value for .NET Framework 4.8 for Vibranium changed from 528209 to 528372? I'm seeing the latter on my machine too.
