### ISSUE TITLE
Invalid Remarks section in System.IO.BinaryWriter.Flush Method

### ISSUE THREAD

**Issue by mcpiroman** [dotnet/docs#18694]
**Issue description**

https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.flush#System_IO_BinaryWriter_Flush 

Flush section seems to be copy-pasted from `System.IO.StreamWriter.Flush`. Especially, it mentions ` AutoFlush` property, which  `System.IO.BinaryWriter` does not have.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core
- [X] .NET Framework
- [X] .NET Standard

**Comment by Thraka** [comment]
@carlossanlop can you comment?

**Comment by tdykstra** [comment]
This issue was moved to dotnet/dotnet-api-docs#4589
