### ISSUE TITLE
Accessing IOptions<> configurations from DI in HttpClient configuration

### ISSUE THREAD

**Issue by rollandjb** [dotnet/docs#18693]
The following pattern (example in the article) is commonly found in documentation and articles on service configuration.

```csharp
services.AddHttpClient<ICatalogService, CatalogService>(client =>
{
    client.BaseAddress = new Uri(Configuration["BaseUrl"]);
})
```

It would be most helpful to include links that show how to use DI to to obtain configuration parameters accessible via `IOptions<T>` for use in configuring delegates like the one above.

If configuration info is sourced from multiple configuration sections, using `Configuration["..."]` easily results in sections being deserialised multiple times, which `IOptions` and `IConfigureOptions` allows one to avoid.

For example, if `Poly` related configuration is to be shared across a number of dedicated `HttpClient`s, one needs the `"Poly"` section as well as the client-specify config (such as `baseUrtl` in the configuration of each client.

I know that there **is** an overload for `AddHttpClient` that provides an `IServiceProvider` as an argument to the delegate. If that is the recommended approach, an example would be helpful.

If not, some guidance on best practice in production solutions would be helpful.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @rollandjb, you may want to refer this [Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)

Also, you can check out [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) to see how configurations can be handled in real scenarios. 

Thank you.

**Comment by sughosneo** [comment]
Hi @rollandjb, we are closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
