### ISSUE TITLE
Replace .NET Framework with .NET (C# folders)

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18697]
Replace .NET Framework with .NET (where appropriate) in docs/csharp folders.

Folders:

- [ ] csharp/getting-started
- [ ] csharp/how-to
- [ ] csharp/language-reference
- [ ] csharp/linq
- [x] csharp/programming-guide
- [ ] csharp/roslyn-sdk
- [ ] csharp/tour-of-csharp
- [ ] csharp/tutorials
- [ ] csharp/whats-new

**Comment by ossCodeJourney** [comment]
I want to work on this. Should i get my name added to the contributors list in order to do so. First timer, please excuse if the question is silly.

**Comment by gewarren** [comment]
@ossCodeJourney Thanks for your help! No need to get your name added as a contributor, you can just go ahead and submit a pull request when you're ready. It will probably ask you to sign a contributor's license agreement once you submit the PR.
