### ISSUE TITLE
--all-but <VERSIONS> syntax is not explained

### ISSUE THREAD

**Issue by v-radelg** [dotnet/docs#18707]
@smuehlst commented 1 hour ago

There is no description of the form in which you have to specify if you want to specify several versions:

--all-but <VERSIONS>

Removes all .NET Core SDKs and runtimes, except those versions specified.

It doesn't work to separate the versions with commas:

> dotnet-core-uninstall dry-run --all-but 2.1.514,2.1.202 --sdk
The specified version is not valid: "2.1.514,2.1.202".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289d3b2b-8b21-d0a0-10fa-9a8b3fdb62ce
* Version Independent ID: 3145ef37-2a19-e3ca-ba78-95c2f1a41a6b
* Content: [Uninstall Tool - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows)
* Content Source: [docs/core/additional-tools/uninstall-tool.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/uninstall-tool.md)
* Product: **dotnet-core**
* GitHub Login: @sfoslund
* Microsoft Alias: **dotnetcontent**

**Comment by sfoslund** [comment]
The format for specifying multiple versions is detailed in [the VERSION argument description](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows#arguments). I'm not sure it's worth adding this note in every option description, but it might make sense to make it more visible.

**Comment by smuehlst** [comment]
I see. The confusion on my side then came from the fact that I was looking for an explanation of the  `VERSIONS` argument, while the explanation can be found under the VERSION argument description. So in my view it would be better to list the option as `--all-but <VERSION>`.

**Comment by Thraka** [comment]
I think the syntax for VERSION should be clearer `--all-but <VERSION>[,<VERSION>...] what is the delimiter for example?
