### ISSUE TITLE
Mini Tutorial

### ISSUE THREAD

**Issue by bugaevski** [dotnet/docs#18704]
This is great example. Very clearly written. And works right away. Several mini-tutorials in one example. I learned a lot from this page.
Michael. (35+ years in IT)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcfe22a9-486f-f4d4-2611-94dc2b76e4d0
* Version Independent ID: 71ebda9d-6cb2-2927-d009-58d984bebce8
* Content: [How to: Use Parallel.Invoke to Execute Parallel Operations](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations)
* Content Source: [docs/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @bugaevski - thank you for your kind words, much appreciated!

**Comment by bugaevski** [comment]
Sorry, I did not want to "open a ticket", but have not found other way to
simply provide feedback.

I am going through a lots of Microsoft articles lately. Most of them are
over complicated and do not have "working" examples.
So - I really appreciate that page and the code example. I wish Microsoft
"writers" learn from your example.

I learned "Oblomov" in school...



My best regards.



Michael



________________________________

Michael Bugaevski

mikejm618@gmail.com

https://www.bugaevski.com/  - resume and more
