### ISSUE TITLE
Missing backtick screwing up formatting

### ISSUE THREAD

**Issue by nlehnert1** [dotnet/docs#18709]
Missing a back-tick ` in your markdown for the last code snippet on this page. You can tell it's intended to be closed after the double back-ticks, but instead the code block ends up continuing until
it is closed properly after the ICitizen bit. I assume the markdown looks something like this:

\`\`\`csharp
string IEmployee.this[int index]
{
}
**\`\`**

implements the indexer on the `IEmployee` interface, while the following declaration:

\```csharp
string ICitizen.this[int index]
{
}
\`\`\`

EDIT: Sorry, it's hard to format this when markdown is supported in comments too :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1a968a-b313-2540-360e-7bba683a7033
* Version Independent ID: c816daea-0924-c293-a35e-ceca1aa24004
* Content: [Indexers in Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/indexers-in-interfaces)
* Content Source: [docs/csharp/programming-guide/indexers/indexers-in-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/indexers-in-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Do you want to submit a Pull Request that fixes that? For simple changes like this one, you can do it all from your browser (and if you don't know how to do that, you can follow [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents)).

> Sorry, it's hard to format this when markdown is supported in comments too :(

You can use 4 backticks for that. This:

`````
````
```csharp
string ICitizen.this[int index]
{
}
```
````
`````

renders as:

````
```csharp
string ICitizen.this[int index]
{
}
```
````

**Comment by IEvangelist** [comment]
Hi @nlehnert1, I made this `up-for-grabs`. Please feel free to [follow the guidance](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for simple updates like this. Thank you @svick for helping out here too, much appreciated.

**Comment by nlehnert1** [comment]
Apologies; I got very much wrapped up in the events of this weekend and totally forgot about this until just now. Created a PR and linked it to this issue.
