### ISSUE TITLE
mod operator

### ISSUE THREAD

**Issue by Thorcik1704** [dotnet/docs#18719]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e0d8d3-ed1e-7e9d-d0dc-3d577c286f60
* Version Independent ID: 6961eaa7-db11-5794-746e-42fb6e4a964b
* Content: [Mod Operator - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/mod-operator)
* Content Source: [docs/visual-basic/language-reference/operators/mod-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/mod-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Can you provide more details here @Thorcik1704 ?
