### ISSUE TITLE
Standard numeric format strings: advice on "R" doesn't apply to .NET 3.0

### ISSUE THREAD

**Issue by canton7** [dotnet/docs#18717]
The section on "R" says:

> For Double values, the "R" format specifier in some cases fails to successfully round-trip the original value. For both Double and Single values, it also offers relatively poor performance. Instead, we recommend that you use the "G17" format specifier for Double values and the "G9" format specifier to successfully round-trip Single values.

Since .NET Core 3.0 is released, this advice no longer applies ([link](https://github.com/dotnet/runtime/issues/8655#issuecomment-459855176)). Maybe add a note to this paragraph that "R" is fine in .NET Core 3.0+?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@tannergooding would you be able to submit a doc change for this?
