### ISSUE TITLE
The CS0246 error can cause by the framework target. For example, if your reference target is 4.6 added to the 4.5.2 target build .Net then you expect to get the same error CS

### ISSUE THREAD

**Issue by HanifKarimi** [dotnet/docs#18713]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0067cc97-4a34-364c-ff91-7864bca5c3e1
* Version Independent ID: 902901c2-f8b6-c58c-c2e8-f93aab2487c9
* Content: [Compiler Error CS0246](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0246.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0246.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Can you give us more details here @HanifKarimi ?
