### ISSUE TITLE
Undocumented C# Keyword

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18714]
Reading through [CA2230](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2230?view=vs-2019), it mentions `__arglist` as a C# Keyword. I never knew the existence of such keyword in C#.
Searching through the documentation doesn't give any results (To be accurate, only results in [error messages](https://github.com/dotnet/docs/search?q=__arglist&unscoped_q=__arglist), not actual documentation for the keyword).

So, I suspect the documentation is missing this keyword.

The documentation for that keyword should also include a note that it's preferred to use `params`.

**Comment by svick** [comment]
I believe `__arglist` (and keywords related to it) is intentionally undocumented, because it shouldn't be used. That's also why it starts with double underscore. I don't think there's any reason to start documenting it now.

**Comment by Youssef1313** [comment]
@svick, Thanks for answering. But are there any rare scenarios where one would use __arglist? for interop with C/C++ for example? or it's **always** bad to use it?

**Comment by BillWagner** [comment]
The last section of [identifies](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers) in the C# spec has the following text:

> Identifiers containing two consecutive underscore characters (`U+005F`) are reserved for use by the implementation. For example, an implementation might provide extended keywords that begin with two underscores.

I think that is sufficient. I recommend closing this.
