### ISSUE TITLE
"API layers" section in compiler API model is unclear

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18727]
The [API layers](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/compiler-api-model#api-layers) section is confusing.

First, it mentions:

> The .NET compiler SDK consists of **two** main layers of APIs: compiler APIs and workspaces APIs.

But after that, it shows an image that contains "**three** layers", the two previously mentioned and the "Features APIs" layer.

Then, there are **four** sub-headings: "Compiler APIs", "Diagnostic APIs", "Scripting APIs", and "Workspaces APIs".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778268e6-e64f-9743-bce1-5142ef19425b
* Version Independent ID: 40aefcd8-e806-bee3-4895-e7f038b58bc9
* Content: [.NET Compiler Platform SDK concepts and object model](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/compiler-api-model)
* Content Source: [docs/csharp/roslyn-sdk/compiler-api-model.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/compiler-api-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is pretty clearly outdated. Thanks for writing this @Youssef1313 

We'll look into it.
