### ISSUE TITLE
What is needed for ActivatorUtilities.CreateInstance to work with .NET Native?

### ISSUE THREAD

**Issue by mc0re** [dotnet/docs#18729]
The following code runs fine without Native compilation, but fails with it. What do I miss?

```
var services = new ServiceCollection();
services
    .AddAutoMapper(typeof(DtoMappingProfile))
    .AddLogging(configure => configure.AddSerilog(dispose: true))
    .AddSingleton<IHashCalculator, HashCalculator>()
    .AddSingleton<IMyHttpClient, MyHttpClient>()
    .AddSingleton<IPropertySet>(ApplicationData.Current.LocalSettings.Values)
    ;

// This is a field in the page class
mServices = services.BuildServiceProvider();
ActivatorUtilities.CreateInstance<AuthViewModel>(mServices)
```

`AuthViewModel` has the following contructor:
```
public AuthViewModel(IMyHttpClient client, IPropertySet settings)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010e4a46-847d-169c-0945-4c81eb073fa7
* Version Independent ID: 1fee9ab9-4ca3-0c4e-0c52-e7be3ea3e62d
* Content: [APIs That Rely on Reflection - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/apis-that-rely-on-reflection)
* Content Source: [windows-apps-src/dotnet-native/apis-that-rely-on-reflection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/dotnet-native/apis-that-rely-on-reflection.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mc0re** [comment]
I figured by trial and error that replacing `IPropertySet` with its parent class `ApplicationDataContainer` solves the issue. So the approach that can run is:
```
    .AddSingleton<ApplicationDataContainer>(ApplicationData.Current.LocalSettings)
```
and change the `AuthViewModel` constructor accordingly.
But then I can't make any test case for `AuthViewModel`, as I can't really instantiate a test version of `ApplicationDataContainer`.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/windows-uwp#3375
