### ISSUE TITLE
dotnet new is missing blazorwasm template

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18721]
Information about blazorwasm template aren't included in the dotnet new documentation. This should be added.

It should be stated that the minimum supported version is 3.1.300.

(See https://github.com/dotnet/AspNetCore.Docs/issues/18593#issuecomment-636495103)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Youssef1313 Thanks for reporting this.  If you'd like to submit a PR on it, let me know and I'll assign the issue to you.

**Comment by Youssef1313** [comment]
@tdykstra Ok, I'll submit a PR soon.
