### ISSUE TITLE
the update is not applicable on this computer

### ISSUE THREAD

**Issue by skchinna7** [dotnet/docs#18723]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new article**

- Explain why this article is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this article will cover.
- Create an outline for the new article. We'll help review the outline and approve it before anyone writes the article.

**Comment by skchinna7** [comment]
after the update of .net core sdk vscode does not execute c sharp code

**Comment by Thraka** [comment]
@skchinna7 Hello. This repo is for documentation bugs, we can't really triage your problem.

I would think you need to [ask on VSCode](https://github.com/Microsoft/vscode/wiki/Feedback-Channels) why it's not detecting .NET Core. I've never had this problem, but I would troubleshoot your own dotnet install (Can you run `dotnet.exe` from the command prompt?) first. If .NET Core isn't working, look at reinstalling it, if it's still not working, open a bug with the [.NET Core repo](https://github.com/dotnet/core/issues).
