### ISSUE TITLE
Duplicate Paragraphs - Leveraging containers and orchestrators

### ISSUE THREAD

**Issue by theterminalguy** [dotnet/docs#18722]
<img width="1438" alt="Screen Shot 2020-05-31 at 4 05 45 PM" src="https://user-images.githubusercontent.com/17008072/83361660-b8236b80-a358-11ea-8bbe-dc3362e9ec6a.png">

**_This entire section on the page is also repeated twice._** 

<img width="810" alt="Screen Shot 2020-05-31 at 4 07 18 PM" src="https://user-images.githubusercontent.com/17008072/83361676-d4270d00-a358-11ea-9b8f-50a5019a38d4.png">

https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/leverage-containers-orchestrators

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde870f6-e7e3-f7e7-0044-df7bc7097516
* Version Independent ID: fca65eda-a53e-a20b-26df-9bea6d8216c5
* Content: [Leveraging containers and orchestrators](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/leverage-containers-orchestrators)
* Content Source: [docs/architecture/cloud-native/leverage-containers-orchestrators.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/leverage-containers-orchestrators.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
Thanks, @theterminalguy We have a PR that will fix it. https://github.com/dotnet/docs/pull/18720
