### ISSUE TITLE
All the diagrams in this page are the same general AzMonitor overview visual. 

### ISSUE THREAD

**Issue by sameergMS** [dotnet/docs#18738]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a749bf08-a45c-e441-6125-8a2bfbe7a75e
* Version Independent ID: f2fca24c-5b4e-bbf9-45d5-f7af0149ac5a
* Content: [Azure Monitor](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/azure-monitor)
* Content Source: [docs/architecture/cloud-native/azure-monitor.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/azure-monitor.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Thraka** [comment]
@sameergMS Great catch.

**Comment by tdykstra** [comment]
Low pri as traffic for this doc is extremely low.
