### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SamBehner** [dotnet/docs#18733]
In the example, this is the code
```cs
public class SampleEventArgs
{
    public SampleEventArgs(string s) { Text = s; }
    public String Text { get; } // readonly
}

public class Publisher
{
    // Declare the delegate (if using non-generic pattern).
    public delegate void SampleEventHandler(object sender, SampleEventArgs e);

    // Declare the event.
    public event SampleEventHandler SampleEvent;

    // Wrap the event in a protected virtual method
    // to enable derived classes to raise the event.
    protected virtual void RaiseSampleEvent()
    {
        // Raise the event in a thread-safe manner using the ?. operator.
        SampleEvent?.Invoke(this, new SampleEventArgs("Hello"));
    }
}
```

On line 4, there is an issue. String is capitalized when it shouldn't be.
```cs
public String Text { get; } // readonly
```
It should be
```cs
public string Text { get; }; // readonly
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f782a9c5-2dc8-d8d1-b17d-246ab8524863
* Version Independent ID: f6f825c5-c64b-d13b-1c7e-a01bfb93093d
* Content: [event - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event)
* Content Source: [docs/csharp/language-reference/keywords/event.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/event.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @SamBehner - thank you for posting this issue. As long as there was a `using System;` at the top of the C# file - it is fine to use `String`, as `string` is an alias to the proper `System` type. But I agree, and I do prefer `string`. I've marked this issue as "up-for-grabs", feel free to create a pull request to address this issue and we'll happily review it.

Also, one small correction - you added an extra `;` at the end which is not needed. Should be this:

```csharp
public string Text { get; } // readonly
```

**Comment by SamBehner** [comment]
Oh, I was not aware oh this. I think it would be better to use `string` though as it seems more common, and it would match most of the other examples in the documentation
