### ISSUE TITLE
Indicate which tags show in intellisense

### ISSUE THREAD

**Issue by AppFzx** [dotnet/docs#18730]
I can find no list of which tags are formatted into intellisense help and how. e.g. Through trial and error, I know <remarks> is a useless tag because it doesn't go into intellisense. It would be nice to have that documented somewhere reachable from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5aa865-b9d2-e977-a272-3886aa0a1111
* Version Independent ID: 353b1c44-b90a-e5cc-a193-7b42ec714290
* Content: [Recommended tags for documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)
* Content Source: [docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> I can find no list of which tags are formatted into intellisense help and how. e.g. Through trial and error, I know `<remarks>` is a useless tag because it doesn't go into intellisense. It would be nice to have that documented somewhere reachable from this page.

Related: https://github.com/dotnet/docs/issues/18659. Though that issue is pretty much the opposite: document which tags do affect Visual Studio, even though they are not listed.
