### ISSUE TITLE
Problem with syntax highlighting

### ISSUE THREAD

**Issue by uldercarrilho** [dotnet/docs#18744]
In the last example of this page, the syntax highlighting of C# code is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1a968a-b313-2540-360e-7bba683a7033
* Version Independent ID: c816daea-0924-c293-a35e-ceca1aa24004
* Content: [Indexers in Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/indexers-in-interfaces)
* Content Source: [docs/csharp/programming-guide/indexers/indexers-in-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/indexers-in-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by uldercarrilho** [comment]
I checked the source code [indexers-in-interfaces.md](https://raw.githubusercontent.com/dotnet/docs/master/docs/csharp/programming-guide/indexers/indexers-in-interfaces.md) and is right, but the [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/indexers-in-interfaces) display wrong. See the printscreen of attachment.
![indexers-in-interfaces](https://user-images.githubusercontent.com/11797286/83525937-0f8e1c80-a4bc-11ea-8292-b48fe0bcf7db.png)

**Comment by BillWagner** [comment]
@uldercarrilho I looked at this page, and the rendering is correct to me (and different than your screenshot. 

Can you check again, and close this if it is already fixed?

**Comment by uldercarrilho** [comment]
@BillWagner I checked again and now is rendering correctly. See the attachment.

Thanks.

![indexers-in-interfaces-correct](https://user-images.githubusercontent.com/11797286/83702471-2e3b0300-a5e3-11ea-80dd-a650c1a594cf.png)
