### ISSUE TITLE
Add discards to What's new in C# 7

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1875]
When looking at the code of [What's new in C# 7](https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/csharp-7), I noticed this comment:

```html
<!-- Add wildcards here, if they are in C# 7
-->
```

Since wildcards (renamed to discards) are in C# 7, I think they should be included in the article.

cc: @BillWagner

**Comment by BillWagner** [comment]
@svick Yes, this needs to be added.  If you want to add it in your current PR, I would appreciate it. 

If not, I'll get to it soon.

**Comment by BillWagner** [comment]
Adding @rpetrusha since this is in the deconstruction topic you're adding now. Ping me if you want more information.
