### ISSUE TITLE
 GetRetryPolicy() sample

### ISSUE THREAD

**Issue by alexdrenea** [dotnet/docs#18765]
On the page, you present a sample `GetRetryPolicy` method.
What is the use case to ever retry on a 404 not found error? It's not like a missing URL will magically appear in the next seconds?
```
static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()
{
    return HttpPolicyExtensions
        .HandleTransientHttpError()
        .OrResult(msg => msg.StatusCode == System.Net.HttpStatusCode.NotFound)
        .WaitAndRetryAsync(6, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));
}
```
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @alexdrenea, thanks for your feedback. Yes, with HttpStatusCode 404 `GetRetryPolicy()` might not be of much help. 
But in distributed systems like microservices-based applications, there is always a possibility of partial failure.

For e.g : Let's consider you have deployed one service in kubernetes and then for some reason if the kubernets pod goes down. It would always take some time to get back up. During that recovery period, `GetRetryPolicy()` is a useful method to have for the client to try, until the services comes back up.

For more details, you can refer [handle-partial-failure](https://docs.microsoft.com/dotnet/architecture/microservices/implement-resilient-applications/handle-partial-failure)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @alexdrenea, considering the original question has been addressed, I am closing this issue as of now. 
If you have any further questions, please feel free to reopen it. 

Thank you.
