### ISSUE TITLE
How to identify a nullable reference type

### ISSUE THREAD

**Issue by jasonycw** [dotnet/docs#18767]
In C# 8, is there a recommended way to identify a **nullable reference type**?

For **nullable value type**, there is a section dedicated to it.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#how-to-identify-a-nullable-value-type

We already have `notnull` as constraint 
``` C#
public static bool NotNullableMethod<T>() where T : notnull
```
But seems like we don't have an easy way to determine if generic type is nullable or not. 

We are trying to do optional null check according to the generic type
``` C#
public static Result<T> Create<T>(T value)
{
   if (typeof(T).IsNotNullable() && value is null)
      throw new ArgumentNullException(nameof(value));

   // Do something
}
```
So it will throw exception when
``` C#
Create<Something>(null);
```
But allow
``` C#
Create<Something?>(null);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @jasonycw 

I'm not sure of a way to accomplish this. Ping @agocke @jaredpar for possible answers.

**Comment by jaredpar** [comment]
Are you asking this in the context of reflection? Essentially how to determine if a given `System.Type` is a nullable reference type or not? If so there is no way to do this yet but here is the issue discussing whether or not it should be added https://github.com/dotnet/runtime/issues/29723

**Comment by BillWagner** [comment]
Closing as "product question".
