### ISSUE TITLE
Add an example when actual object you want to deserialize is wrapped in non essential layers

### ISSUE THREAD

**Issue by gkalnytskyi** [dotnet/docs#18763]
I had hard time deserializing the list of objects wrapped in several non-essential layers. I couldn't understand why I was getting `JsonException` with "read too much, or not enough" message (more details [here](https://stackoverflow.com/questions/62147178/system-text-json-deserialization-fails-with-jsonexception-read-to-much-or-not-e)).

I finally got an explanation on [Stackoverflow](https://stackoverflow.com/a/62155881/761755), but I believe the requirement "When reading an object, JsonConverter<T>.Read() must leave the Utf8JsonReader positioned on the EndObject token of the object where it was originally positioned." should be added to this page to help other developers, when they face similar issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion, I'm adding this to our backlog.
