### ISSUE TITLE
Ocelot renamed ReRoutes to Routes. /dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot is outdated

### ISSUE THREAD

**Issue by worming004** [dotnet/docs#18761]
Hello,

Since version 16.0, Ocelot use Routes property instead of ReRoutes. See commit https://github.com/ThreeMammals/Ocelot/commit/3439be89271bb37b170429d69ca74978c941432e

This document describe an Ocelot usage with ReRoutes property that do not work with latest ocelot version.

Could you update this document please ?

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @worming004, Thank you for notifying us about this change.

With 3.0 version release we have moved away from Ocelot API gateway. Instead of that we use now Envoy proxy. Though it's been specified in book but unfortunately in the actual `eShopOnContainers` project we don't maintain the code anymore. If you have old branch reference with you would be feasible for you to send us PR ? We can review and merge the changes.

**Comment by worming004** [comment]
Hello @sughosneo ,

To ensure to follow the instruction, does the PR is about to update eShopOnContainers, or about the documentation ?

As eShopOnContainer is not using ocelot anymore, I am not sure what I am suppose to do.
If it is about the documentation, I could prepare a PR

**Comment by sughosneo** [comment]
Hi @worming004 , thanks for your response and sorry for the confusion. I could have been more clear on that :)
If you could create a PR on the [docs](https://github.com/dotnet/docs) repo for us to review.

Thank you.

**Comment by worming004** [comment]
Hi @sughosneo , no problem for that :)
It's my first PR to docs. Feel free to tell me if anything is wrong.

Regards
