### ISSUE TITLE
Public signing cannot be enabled using the the project property page

### ISSUE THREAD

**Issue by a-ctor** [dotnet/docs#18772]
The page indicates that it is possible to set `-publicsign` in Visual Studio by modifying the __Delay sign only__ property. This does not work as it enables delay signing (`-delaysign`) instead.

To enable public signing the .csproj file has to be edited to include the `PublicSign` property:

```xml
<PublicSign>true</PublicSign>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7871f3-e680-0424-01fe-9fd91b154275
* Version Independent ID: b2f4b5bd-d13b-36b2-a064-9b4d519c4348
* Content: [-publicsign (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/publicsign-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/publicsign-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/publicsign-compiler-option.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this, and creating such a detailed description. 

We'll address this when we next update this page. In the meantime, I've added the "up for grabs" label if community members want to submit a PR.
