### ISSUE TITLE
Set the attribute of the aspNetCore element in web.config

### ISSUE THREAD

**Issue by kamikyo** [dotnet/docs#18771]
You know, when we use the `dotnet publish ...` , a web.config file is generated. How can I set the attribute of aspNetCore element by dotnet command line. 
This is very useful when using jenkins for CI/CD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@wli3 do you know the answer to this question?

**Comment by wli3** [comment]
@vijayrkn do you own web.config?

**Comment by vijayrkn** [comment]
yes, we own the web.config generation and transformation as part of publish. 

@kamikyo - When you say as part of "dotnet" , do you mean as a part of "dotnet new"? this functionality is already part of "dotnet" through "dotnet publish".

**Comment by kamikyo** [comment]
Sorry, i didn't make this clear.
When i use the command like this:
`dotnet publish -o "C:\jenkins_publish\xxxx" --packages xxxx`
I will get the web.config like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="209715200" />
      </requestFiltering>
    </security>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\xxxx.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout">
......
    </aspNetCore>
  </system.webServer>
</configuration>
```
Now, I can use additional parameters (/p:xxxx) to make some changes to my web.config.
Like this:
`dotnet publish -o "C:\jenkins_publish\xxxx" --packages xxxx /p:EnvironmentName=Staging`
Now, The web.config look like this:
```
...
<aspNetCore processPath="dotnet" arguments=".\xxxx.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Staging" />
      </environmentVariables>
    </aspNetCore>
...
```
Yes, the environment variable's value is 'Staging' now.
I was wondering if there are some magical parameters. For example like this:
`dotnet publish -o "C:\jenkins_publish\xxxx" --packages xxxx /p:EnvironmentName=Staging /attr:requestTimeout='00:10:00'`
It can set the attribute's value of the aspNetCore element (eg. requestTimeout).
The final web.config file should look like this:
```
...
<aspNetCore ... requestTimeout="00:10:00">
     ...
</aspNetCore>
...
```
Of course, ideally, I hope the dotnet publish command can configure more items.
For example, all these [Asp.net Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#attributes-of-the-aspnetcore-element)

Looking forward to your reply, thanks. @vijayrkn
