### ISSUE TITLE
Animal or Mammal?

### ISSUE THREAD

**Issue by JvdBossche** [dotnet/docs#18779]
In the last piece of sample code, `Test()` has an object called `a` of class `Animal` as parameter.
It is this `Animal a` that gets casted to `Reptile` and which is stored as `Reptile r`. (which supposedly fails)
But the comment is not in line with the code: the comment sais that a *Mammal* can not be converted into a Reptile. No Mammal is used in the code!

Either
* adapt the comment to say that an _Animal_ can not be converted into a Reptile (of which I'm not sure, by the way)
* or adapt the code to create a `Mammal` called `m` as parameter of `Test()` and try to cast that: `Reptile r = (Reptile)m;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91266ab9-071d-067c-df52-8a297045af24
* Version Independent ID: 1d378928-4bb5-6bcf-49ca-2026768ab2aa
* Content: [Casting and type conversions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions)
* Content Source: [docs/csharp/programming-guide/types/casting-and-type-conversions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/casting-and-type-conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @JvdBossche We'll take a look and get this addressed.

**Comment by BillWagner** [comment]
closed accidentally. Reopening
