### ISSUE TITLE
I needed to add a NuGet Package "Microsoft.ML.OnnxRuntime".

### ISSUE THREAD

**Issue by tfukumori** [dotnet/docs#18785]
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx#create-a-console-application

In the above section, I also needed the following as a NuGet Package to add

- Microsoft.ML.OnnxRuntime[1.3.0]

If not added, a "System.DllNotFoundException" error was raised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @tfukumori 

Sorry to hear you ran into these issues. We're in the process of updating our samples to the latest version. Feel free to track this issue for updates.
