### ISSUE TITLE
Broken markup in article 'switch (C# reference)'

### ISSUE THREAD

**Issue by abatishchev** [dotnet/docs#18784]
Starting section [The case statement and the when clause](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#-the-case-statement-and-the-when-clause) the markup is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d9cc47-5caf-184a-0ad6-cb968850be7a
* Version Independent ID: f058bf17-04e9-9e23-05c7-66c1864445ad
* Content: [C# switch statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch)
* Content Source: [docs/csharp/language-reference/keywords/switch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/switch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for alerting us @abatishchev 

I've updated the doc to fix the bad markup. See PR #18790
