### ISSUE TITLE
Definition of a type should include links to implemented interfaces in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1878]
Currently, it seems the definition of a type contains links to base types, derived types and attributes. Those are all nice, but what's missing is links to interfaces the type implements.

For example, the links for [`Dictionary`](https://docs.microsoft.com/en-us/dotnet/api/System.Collections.Generic.Dictionary-2?view=netframework-4.7#definition):

![](https://cloud.githubusercontent.com/assets/287848/24915734/43bf8f38-1ed8-11e7-879c-2aea48ae0877.png)

Currently, there does not seem to be a simple way to get from that page to the page for for example `IDictionary<TKey, TValue>`. I think there should be one.

**Comment by svick** [comment]
The situation is better now, but it still doesn't seem completely fixed:

![](https://cloud.githubusercontent.com/assets/287848/25551995/aaf6130c-2c8e-11e7-99d1-8bff3a9760aa.png)

Notice that generic interfaces are not links.

**Comment by mairaw** [comment]
Opened internal bug to track this: #988142

**Comment by mairaw** [comment]
Now we do have for some generic interfaces, but others have dropped from the list and we got now duplicated values:
![image](https://user-images.githubusercontent.com/12971179/27376849-30ae6ea0-5628-11e7-8583-a5277bc2b2cc.png)

**Comment by mairaw** [comment]
@svick this seems to be fixed now. Can you check? Thanks!

**Comment by svick** [comment]
@mairaw Almost there, just one question: why does the list of implemented interfaces not include the non-generic interfaces `System.Collections.IEnumerable` and `System.Collections.ICollection`?

If this is the expected behavior, because those interfaces are inherited from other interfaces, then yes, this would be fixed.

**Comment by mairaw** [comment]
I've opened a separate internal bug for this a while back. I need to discuss this further with @joelmartinez, @dend and @terrajobst. That was the explanation I was given, not sure if that's what we want to do.

**Comment by mairaw** [comment]
That was the decision made by the engineering team in regards to the list of interfaces. So I'm considering this one fixed. Thanks!
