### ISSUE TITLE
What happened to the suffixes from the type table? Please put them back.

### ISSUE THREAD

**Issue by megaritzmom** [dotnet/docs#18780]
You removed the suffix from the types table. That was required reading for my C# students (I teach C# at Tulsa Community College). I'm now going to have to make a table myself, but yours was SO much more informative. Please put the suffixes back in the type table.

I have attached what it used to look like.
[ValueTypesTable(1) (1).pdf](https://github.com/dotnet/docs/files/4726271/ValueTypesTable.1.1.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de24f644-5e7c-d3de-fd13-5969bb3e4b78
* Version Independent ID: 9173876e-49be-6c60-634d-eeb1944ab2fc
* Content: [Types - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types)
* Content Source: [spec/types.md](https://github.com/dotnet/csharplang/blob/master/spec/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@megaritzmom Can you be more specific? Looking at the history of that file (https://github.com/dotnet/csharplang/commits/master/spec/types.md) It's only been updated once in the last 2 years and I don't see anything removed.

😢

**Comment by pkulikov** [comment]
@megaritzmom that table doesn't exist anymore. The information about suffixes was moved to the sections about literals:
- [Real literals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types#real-literals)
- [Integer literals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#integer-literals)

**Comment by Thraka** [comment]
I think this answers the question. Thanks @pkulikov
