### ISSUE TITLE
Try / catch example has issues 

### ISSUE THREAD

**Issue by dougedmunds** [dotnet/docs#18803]
Reference the page in the tutorial. I attempted surrounding the  bank account entry, the one with the positive 1000 opening balance, with the try /catch code used for "invalidAccount'.  I expected try to succeed, which it does.  But by putting the 'new' bank account inside a try/catch, the last line of code in the sample, to print the account history, is flagged as trying to reference a variable that does not exist.   Apparently "new" is masked by the try/catch code.   

Effectively the 'invalidAccount' try/catch is not usable code.

What is the work-around?   
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Does that mean your code looked something like the following?

```c#
try
{
    var account = new BankAccount("<name>", 1000);
}
catch (ArgumentOutOfRangeException e)
{
    Console.WriteLine("Exception caught creating account with negative balance");
    Console.WriteLine(e.ToString());
}
Console.WriteLine(account.GetAccountHistory());
```

This doesn't work, because in C#, a variable declared inside braces is not visible outside of those braces.

Ti fix it, you can instead write the following:

```c#
BankAccount account;
try
{
    account = new BankAccount("<name>", 1000);
}
catch (ArgumentOutOfRangeException e)
{
    Console.WriteLine("Exception caught creating account with negative balance");
    Console.WriteLine(e.ToString());
    return;
}
Console.WriteLine(account.GetAccountHistory());
```

It declares the `account` variable outside braces (and without `var`) and also uses `return` to make sure the `GetAccountHistory` line only executes if there is no `ArgumentOutOfRangeException` exception.

Though I'm not sure if any of this should be mentioned in the article.

**Comment by IEvangelist** [comment]
Hi @dougedmunds - @svick is correct and I was assuming that you were experiencing the problem as was detailed. Does the suggestion solve your problem?

**Comment by dougedmunds** [comment]
I now understand what you are saying about scope of variables inside braces.  I would suggest revising the 'invalidaccount'  try/catch code to something similar to the fix provided by @svick.
