### ISSUE TITLE
Stopping an infinite loop

### ISSUE THREAD

**Issue by dougedmunds** [dotnet/docs#18801]
I didn't write the for loop correctly and there was no way to stop infinite loop I created in the interactive repl, short of closing the browser down.   If there is another way , include information about it in the 'interactive loop'  tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=8)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for alerting us @dougedmunds 

I'm investigating this now. (We had a timeout configured that would stop running your code, but that isn't working now. We'll figure it out.)

**Comment by BillWagner** [comment]
timeout is back on .NET interactive. Closing.
