### ISSUE TITLE
Guidance on long function signatures

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#18806]
Is there any guidance what to do with long function signatures?
Consider the following example:
```
let fold (funcs : ResultFunc<'Input, 'Output, 'TError> seq) (input : 'Input) (input2: 'Input) (input3: 'Input) : Result<'Output list, 'TError list> =
    let mutable anyErrors = false
    let mutable collectedOutputs = []
    let mutable collectedErrors = []

    let runValidator (validator : ResultFunc<'Input, 'Output, 'TError>) input =
        let validatorResult = validator input
        match validatorResult with
        | Error error ->
            anyErrors <- true
            collectedErrors <- error :: collectedErrors
        | Ok output -> collectedOutputs <- output :: collectedOutputs
    funcs |> Seq.iter (fun validator -> runValidator validator input)
    match anyErrors with
    | true -> Error collectedErrors
    | false -> Ok collectedOutputs
```

Putting the whole `let fold ...` on one line is getting unreadable.
Fantomas ([example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzW68YAFLgK4B20AzmGgEqLVnpYBil0APAOQCSFAA5ksAGjA8A8iOFiJAFQCiAJ2WxlAPjDVEARwCUJAJZCRdCQNmHiJ2QCY0-U1mu2RAZkeWRhhkxZYvNJYsmDoRtRyPEqq6mERWFoAvAA6yikUEBCYOAC2IgCGAEaYYAUUAJ4qasq0SXgF6DppGVlh2GD5WMWlcOiY0FiI8MGydWAA2gC6LZlZOZ2FJYhgfQND8NXq49Ozs20LypQAao1G8AVYccQAbmcXV8rmjMysHFS83lGjIuLRW5pDG4cKl0nM2tkOndwg91C8AmB6tDzpc4sD9hCILlLtAABZgZGw5Tw1hgADuRiwuIxmIAPmAAWBELEngBaDQ0zFZcpVFm0LissBYI6ITlc1YEdbDAH8wXMmp0NBrRCDaV8sVZemSADWYFgMjM7Il-RVGx%2BWFleoNOBQSslpuG5uonPIVFotK0AGU9AA6SnMkiugn3VFsrRHCinGGh4PRx5gYH6TnYrB4sqVGXkynUsFtenCsgrI2M5Wqzbq3OahpNItaHXGqUja3USCicBQHRYLAmADmLbQE3bEFAmMgABIsBVBMg0JATFhW0OsuPoYXUJMl20AAxt8WQARIChYT2CArQRAAOTIuUX4oALJuwFMlwBfXdZEcQ8eT6frudH28vzHVcZw3cUAEZ31HAAFAoe0QAB1c4qUAzFwLsLdH2fNo3yXT82m-KdQMgIpYAIVDl2Axo1wHR8IDsKCv29XIjD6WAKAAQSwRQKBGXAABkTGQRi2lwRodCw19GPwyif2I0jyJEqAqPQGiwK5dwlIgSATzPRAACFEHwZREFg5QClybBmQotoC0QSScOkx9CN-WcFPQGzlJA9dB3vLSoF089DOMxB%2BNgMlmWgAodAEG5YCi7t2M8iA7IcrJcLaGTtInIi-3czyV2o0DfK5ABWfydNPIKjPURAAFVBGnZQopiig4oSowkv8sSazSiAMo-ZyctcqB8qUwrVOKuiwAANgqwKDJqkyAGF0Gi6hlvYyIjkGdRkurCTMWw9KnNHYb5LIjzxpUtSSsxAB2eaqsWkKAFlEFyIprO68T7KOqS8KGuS8sugqbqm8UAA4nr04Las29AuumnrDohY7%2BtOoDgbc0Hru82jxQAThh88ONwIZlE23JsX21L-scwGzux0bcaG-H1LQndpsq2GlsQZjWIIJHxRRv60YBzKgdynHFLZoqfOm8DIO5hayYpgW2IoWmRT6sABuHKWRpI1mzvZu6IXQiqD0QI9JAoeRlAqJCUJ%2B3r6ZOxmsellnZdN%2BWCa5cDNJV56OLUSh4AAEUQcIWIp7XC11-WwCy5Tmf-Bc8f9jmLbvCrXoKAAPPhcHkXEbcUGtPVxdQsCQ%2BAXemu9MPdjHPYI86-3nMGzcV8ruYL4uKFwIxC8kJrQ0UQvBBM6hqE6rX-NKlvxYZyWme9jOe%2Bz822nAuaB6Lxg4GUeB68b%2B8V7adG9cxjv0%2B7rPJoViDHsPwuw-MipJGUQTInP3E%2B1m5JzvrJTej85bPwDmhaG79%2BLYH0iYeAvYAFAKvlkG%2BydU4uQur7ICvcILEwHgEIw4QKAGURtAbU%2BlzJUOwNQO2noLKIARteReyNfogPbmAo2Y1IG3WmhhCqF5EBkjIYtLAEUbbyCItHEeFBKQLw4rxd6n1mQtldqja%2BEtBob14SbfBO9BHKz3AAaUQIgQQJcy42wEEwyyglyH7VFlw9eXt9F4I7gQrkdgGIq2FKxLAr0EDCQ4W7Ve6V2xTHfHOagbB57rhcS%2BIAA)) would now format this to

```fsharp
let fold
    (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
    (input: 'Input)
    (input2: 'Input)
    (input3: 'Input)
    : Result<'Output list, 'TError list>
    =
```

But after seeing the outcome of https://github.com/dotnet/docs/issues/18637, I'm curious what the guidelines would say in this case? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by knocte** [comment]
> But after seeing the outcome of #18637, I'm curious what the guidelines would say in this case?

Good point. In my opinion, to be consistent with the style from #18637, this should be the format:

```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
         (input: 'Input)
         (input2: 'Input)
         (input3: 'Input)
         : Result<'Output list, 'TError list>
         =
```

**Comment by cartermp** [comment]
agreed @knocte

**Comment by nojaf** [comment]
@cartermp @knocte how does this look like when there is no return type?
Where does the equal sign go? Is it similar to the [PR of members](https://github.com/dotnet/docs/pull/18793/files#diff-eed63f6624dbb527e2e9533697f1ff6bR112)?

**Comment by knocte** [comment]
IMO this should be the way for each case (note the slight difference from my previous snippet):

With return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
         (input: 'Input)
         (input2: 'Input)
         (input3: 'Input)
         : Result<'Output list, 'TError list> =
```

Without return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
         (input: 'Input)
         (input2: 'Input)
         (input3: 'Input)
         =
```

This way:
- 1st snippet (with return type) matches better with the PR that fixes https://github.com/dotnet/docs/issues/18637.
- 2nd snippet (with no return type) allows diffs to be only 1loc change if adding one extra parameter to the function.

**Comment by nojaf** [comment]
If you have the equal sign here on a new line anyways, I'd then go for the same behavior in [the member binding](https://github.com/dotnet/docs/pull/18793/files#diff-eed63f6624dbb527e2e9533697f1ff6bR103).

**Comment by knocte** [comment]
> I'd then go for the same behavior in the member binding.
> And have it there on a new line as well.

But in that example, having the equals sign in the next line doesn't help diff noise (cause being a tuple you still need to add comma to the previously-last parameter). Maybe it helps on currified params for members though.

**Comment by knocte** [comment]
In case you guys are a bit lost now, I'm going to write all combinations of my proposal.

Member, tuple (non-currified), with return type:
```
    member _.LongMethodWithLotsOfParameters(aVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                            aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                            aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                            : AVeryLongReturnType =
```

Member, tuple (non-currified), with no return type:
```
    member _.LongMethodWithLotsOfParameters(aVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                            aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse,
                                            aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse) =
```

Member, currified (non-tuple), with return type:
```
    member _.LongMethodWithLotsOfParameters(aVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           (aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           (aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           : AVeryLongReturnType =
```

Member, currified (non-tuple), with no return type:
```
    member _.LongMethodWithLotsOfParameters(aVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           (aSecondVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           (aThirdVeryLongType: AVeryLongTypeThatYouNeedToUse)
                                           =
```

Let, currified (non-tuple), with return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
         (input: 'Input)
         (input2: 'Input)
         (input3: 'Input)
         : Result<'Output list, 'TError list> =
```

Let, currified (non-tuple), with no return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq)
         (input: 'Input)
         (input2: 'Input)
         (input3: 'Input)
         =
```

Let, tuple (non-currified), with return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq,
          input: 'Input,
          input2: 'Input,
          input3: 'Input)
          : Result<'Output list, 'TError list> =
```

Let, tuple (non-currified), with no return type:
```
let fold (funcs: ResultFunc<'Input, 'Output, 'TError> seq,
          input: 'Input,
          input2: 'Input,
          input3: 'Input) =
```

**Comment by nojaf** [comment]
Thanks for writing this summary @knocte.
I didn't know known that there is a difference between `tuple (non-currified), with no return type` and `tuple (non-currified), with no return type`. Is that canon @cartermp or just a proposal here?
It feels a bit odd that in two of the eight cases, the equal sign isn't on the next line.

**Comment by knocte** [comment]
> there is a difference between tuple (non-currified), with no return type and tuple (non-currified), with no return type

Did you write a typo above? both cases read the same to me

**Comment by nojaf** [comment]
Yup, talking about:
![image](https://user-images.githubusercontent.com/2621499/86885127-03b5fb80-c0f5-11ea-9af3-483a3bb810d9.png)

**Comment by knocte** [comment]
Yes, the motivation for the latter is so that you can add parameters with only a 1LOC change in the diff instead of 2.

**Comment by cartermp** [comment]
I think this looks good. Would you like to submit a PR?

**Comment by knocte** [comment]
Sure, can do. But I think it's better to get this merged first: https://github.com/dotnet/docs/pull/18793 to build on top of it.

**Comment by cartermp** [comment]
#18793 is now merged!

**Comment by cartermp** [comment]
@knocte are you still interested in submitting a PR? Happy to do it otherwise

**Comment by knocte** [comment]
@cartermp done, thanks for the reminder, sorry for the delay:

https://github.com/dotnet/docs/pull/20129
