### ISSUE TITLE
List<T> can not use System.Ranges, but the example code use a list, it's misleading

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/docs#18812]
This is my code:

```cs
var x = new List<int> { 1, 2, 3, 4, 5 };
var y = x[1..2]; // Cannot convert from 'System.Range' to 'int'
```

This is the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges):

![image](https://user-images.githubusercontent.com/4510984/83891533-e56c8100-a77f-11ea-9c9e-6da95e470085.png)

The same question on [stackoverflow](https://stackoverflow.com/questions/62217074/c-sharp-8-listt-can-not-use-system-ranges).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges and indices - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges#adding-index-and-range-support-to-existing-library-types)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for alerting us @GF-Huang 

We do need to update these proposals to reflect several of the decisions made during LDM meeting. 

I'll add this to our backlog to address as part of updating the C# standard.
