### ISSUE TITLE
Clean up xmldoc articles

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18818]
For example, `<seealso>` must be outside the `<summary>` tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337464b6-c9f4-87ee-f774-5f4509c3830e
* Version Independent ID: 9626e965-109d-5e3c-eb42-ef8fbccf2fb4
* Content: [&lt;seealso&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/seealso)
* Content Source: [docs/csharp/programming-guide/xmldoc/seealso.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/seealso.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sharwell** [comment]
If we also want an analyzer for this and have an appropriate package to place it in, I have one implemented. 😄

**Comment by gewarren** [comment]
> If we also want an analyzer for this and have an appropriate package to place it in, I have one implemented. 😄

That sounds awesome! @carlossanlop It sounds like this analyzer might tie in with your doc comment porting tool.
