### ISSUE TITLE
Any context as to why would one use the new keyword for hiding

### ISSUE THREAD

**Issue by jvelezc** [dotnet/docs#18815]
If the compiler errors had some context in regards to why one would choose one over the other, it would provide much added value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52797d6c-c245-a61d-f4f6-8ef064577271
* Version Independent ID: ae6523de-e0c6-3f66-1790-c6a723f5fd94
* Content: [Compiler Warning (level 2) CS0108](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0108.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0108.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
```csharp
using System;

public class clx
{
    public int i = 1;
}

public class cly : clx
{
    public static int i = 2;   // CS0108, use the new keyword

    public static void Main()
    {
        Console.WriteLine(i);
    }
}
```

The previous code has **exactly** the same behavior and IL as using the `new` keyword:

```csharp
using System;

public class clx
{
    public int i = 1;
}

public class cly : clx
{
    public new static int i = 2;   // CS0108, use the new keyword

    public static void Main()
    {
        Console.WriteLine(i);
    }
}
```

So, why should you use `new`?

- By using `new`, the compiler warning won't show.
- By using `new`, you show to anyone who reads your code that you **intentionally** want to hide the base class member.

And, you shouldn't use `new` if:

- Your intention wasn't to hide the base class member, in that case, you either rename it or use the base class member (the two are different things, you should be able to determine that in your code).

**Comment by BillWagner** [comment]
I'd like to close this. 

These articles are meant to be a quick answer to why a warning is generated. They point to more conceptual articles on the decisions you would make to remove any warnings. (This article does refer to articles on the `new` operator to find that information.) The reason we choose that organization is that these articles are meant to be found when searching for the error or warning. They get very little traffic from other sources. The linked articles have a much wider audience.

If you didn't find the information in the linked article, reopen this issue, and I'll attach it to that article.
