### ISSUE TITLE
Missing ValueOption docs — how to pass ValueOption as optional parameters?

### ISSUE THREAD

**Issue by haf** [dotnet/docs#18810]
No mention of F# ValueOption; if there's a `defaultValueArg` shouldn't there be docs on how to construct objects without heap allocations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eda5d0f-e44a-e1d0-f006-0397174b530c
* Version Independent ID: 89a7b529-756f-0ecd-a564-4602f149d966
* Content: [Constructors - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/constructors)
* Content Source: [docs/fsharp/language-reference/members/constructors.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/constructors.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Not sure I quite understand the question here. Unfortunately it's not possible to use `ValueOption` in place of `Option` when using F# optional parameters. Unless/until there is a type-directed rule involved then that's just how it is. Perhaps that could be a language suggestion? This one seems relevant, but not specific to the situation: https://github.com/fsharp/fslang-suggestions/issues/874

As for this:

> shouldn't there be docs on how to construct objects without heap allocations?

Not sure how to interpret this, but there isn't a way to construct things without heap allocations unless everything involved is a struct/valuetype. This unfortunately does leave F# optional parameters in a tricky position.

**Comment by cartermp** [comment]
In this case there is no ability to do that. Perhaps the `Optional; DefaultValue` attributes could help out here, but F# optional parameters do allocate today.
