### ISSUE TITLE
In section Virtual members a miscopy error (wrong text of code)

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#18825]
[In section Virtual members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/polymorphism#virtual-members) the second example is wrong - it fully repeat previous example from this section (i think it's a miscopy error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ebd197-8f01-b8d7-45d6-1a7afba572b4
* Version Independent ID: 0790b314-a794-6ce3-15f0-37281faa00a6
* Content: [Polymorphism - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/polymorphism)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/polymorphism.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/polymorphism.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @DSivtsov I've opened #18856 to address this.
