### ISSUE TITLE
"Use previews of the .NET Core SDK" does not exist in VS 2019 16.7 Preview 2

### ISSUE THREAD

**Issue by AceHack** [dotnet/docs#18834]
The documentation is incorrect for the latest version of visual studio preview VS 2019 16.7 Preview 2

`If you are in Visual Studio, it uses the prerelease status requested. That is, if you're using a Preview version of Visual Studio or you set the Use previews of the .NET Core SDK option (under Tools > Options > Environment > Preview Features), prerelease versions are considered; otherwise, only release versions are considered.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#matching-rules)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The use of the option is relevant only if you're not using a preview version of VS:

> if you're using a Preview version of Visual Studio ... prerelease versions are considered [that is, no option setting is necessary]

> or [that is, if you're not using a Preview version] you set the Use previews of the .NET Core SDK option ..., prerelease versions are considered
