### ISSUE TITLE
Unicode codepoint is wrong in one example.

### ISSUE THREAD

**Issue by dada2048** [dotnet/docs#18835]
"U+0065 LATIN SMALL LETTER A"
is wrong.
It should say "U+0061 LATIN SMALL LETTER A", like it does a bit earlier in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66
* Version Independent ID: d53a0764-9f27-16b3-c40a-9627dd1bcc0d
* Content: [Introduction to character encoding in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction)
* Content Source: [docs/standard/base-types/character-encoding-introduction.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-encoding-introduction.md)
* Product: **dotnet**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
@dada2048 Thanks for reporting that.

**Comment by hotenov** [comment]
You corrected HEX representation, but didn't correct DECIMAL.
Should be 97 (not '65' as now, according to Windows Programmer Calculator and this site: https://unicode-table.com/en/#0061 😎 )

**Comment by tdykstra** [comment]
@hotenov Thanks for reporting that!
