### ISSUE TITLE
What is relationship of dotnet-install and Install-Dotnet in Powershell?

### ISSUE THREAD

**Issue by Liturgist** [dotnet/docs#18843]
The PowerShell build.psm1 module contains Install-Dotnet.

What is its relationship to the dotnet-install command mentioned on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Where are you getting build.psm1 from?

**Comment by Liturgist** [comment]
build.psm1 is in the project directory of the PowerShell project from github.

**Comment by Liturgist** [comment]
build.psm1 is in the clone of 7.1.0-preview.3 from github. Yesterday, I could not build pwsh. It reported that I did not have dotnet SDK 5.0.100-preview.5.20279.10. Today,. it appears that I do have it. I do not have an explanation. Sorry for wasting your time.
