### ISSUE TITLE
Why No Dynamic as Reference Types?

### ISSUE THREAD

**Issue by gungunfebrianza** [dotnet/docs#18849]
Hello, is dynamic considered as reference type? if yes, i saw no dynamic as part of reference type?

thank you, correct me if i was wrong
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe245daf-f6b8-1100-3786-b15feefe137b
* Version Independent ID: c031bb57-cb5b-f953-4711-a0ed054dab3f
* Content: [Built-in types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types)
* Content Source: [docs/csharp/language-reference/builtin-types/built-in-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/built-in-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @gungunfebrianza The `dynamic` type is included in reference types in the [C# spec](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/types#the-dynamic-type). We should do the same here.

**Comment by gungunfebrianza** [comment]
hi bill i am programming book author for indonesian people, i just saw something is missing here. tq for attention
