### ISSUE TITLE
Lacking information on .NET architectural components docs page

### ISSUE THREAD

**Issue by sauravbhattacharya001** [dotnet/docs#18847]
When I see "architectural components" in the title of a page, I expect there to be information about the first order segments that make up .NET. Maybe info about the Object hierarchy, some important namespaces, and some common extensions for IO, web, etc. This information is lacking in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba03a7c-8cbe-7670-c2e9-9b692556361c
* Version Independent ID: d085d268-bff6-f355-80b4-01c1023a5914
* Content: [.NET architectural components](https://docs.microsoft.com/en-us/dotnet/standard/components)
* Content Source: [docs/standard/components.md](https://github.com/dotnet/docs/blob/master/docs/standard/components.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Most of the info you requested is included on the [Intro page](https://docs.microsoft.com/dotnet/core/introduction). I have a PR to delete the article you referenced since it duplicates much of the Intro article.
