### ISSUE TITLE
Add more use-cases for explicit interface implementation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18840]
This [SO answer](https://stackoverflow.com/a/62209451/5108631) by @jskeet explains a use-case for explicit interface implementation, other than the only mentioned use-case in the article.

I think another use-case for explicit interface implementation is allowing sub-classes to override the implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Explicit Interface Implementation - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
My recommendation is not to add either of these use cases.

Referring to the SO answer: [This proposal](https://github.com/dotnet/csharplang/blob/master/proposals/covariant-returns.md) would be a better choice in time. 

Referring to allowing sub-classes classes to override interface methods: A better solution would be for the base class to declare the interface methods as `virtual`.

I'll close this, but re-open if you disagree.
