### ISSUE TITLE
Definition of an 'axis method' should be referenced

### ISSUE THREAD

**Issue by valakiBF** [dotnet/docs#18865]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6d45570-8398-1fc5-8f61-4ff917344e9c
* Version Independent ID: 49e74b32-af4f-c320-8ff4-51592904eea8
* Content: [How to write a LINQ to XML axis method (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-write-a-linq-to-xml-axis-method)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-write-a-linq-to-xml-axis-method.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-write-a-linq-to-xml-axis-method.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @valakiBF 

I've opened #18867 to address this.
