### ISSUE TITLE
I was looking for how to set a Tuple, I.E public Tuple<int, int> homeCity; = ?????

### ISSUE THREAD

**Issue by Kadjai** [dotnet/docs#18876]
This page didn't seem to use tuple syntax, more of Tuple as a concept, so very not useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Kadjai what kind of an example do you miss? Also, do you mean Tuple type or ValueTuple type? This article is about value tuples.
