### ISSUE TITLE
Overload: links render incorrecectly in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1887]
The description of [the `EventSource.WriteEventCore` method](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource.writeeventcore?view=netframework-4.7#System_Diagnostics_Tracing_EventSource_WriteEventCore_System_Int32_System_Int32_System_Diagnostics_Tracing_EventSource_EventData__) says:

> Creates a new erload:System.Diagnostics.Tracing.EventSource.WriteEvent overload by using the provided event identifier and event data.

The [source code](https://github.com/dotnet/docs/blob/9f5b8eb/xml/System.Diagnostics.Tracing/EventSource.xml#L2446) is:

```xml
<summary>Creates a new <see cref="Overload:System.Diagnostics.Tracing.EventSource.WriteEvent" /> overload by using the provided event identifier and event data.</summary>
```

Notice that what's supposed to be a link is rendered as "erload:".

**Comment by rpetrusha** [comment]
Thanks, @svick, for opening the issue and bringing this to our attention. I'm not sure how extensive it is yet, but we'll investigate and correct all the occurrences.

**Comment by tompratt-AQ** [comment]
This is extensive - as many as 717 instances in 233 files. I've checked a wide sample, and they all render incorrectly.  The suggestion is to fix them with <xref> and adding ?displayProperty=fullName> to fully qualify the name. I agree, but there are many instances where the name probably wasn't intended to be fully qualified.

**Comment by mairaw** [comment]
Internal bug opened to track this:  979991

Not sure if they can support overload links or not. But using the xref syntax in this case doesn't work because this needs to be in the ECMAXML format.

**Comment by BillWagner** [comment]
@svick I tested this today, and it appears fixed.  Can you verify and close if you agree?

**Comment by svick** [comment]
Yeah, this indeed seems to be fixed, closing.
