### ISSUE TITLE
Code for step 3 in .NET Core VS Code tutorial is not visible

### ISSUE THREAD

**Issue by jmerle** [dotnet/docs#18906]
Step 3 in [Tutorial: Create a .NET Core console application using Visual Studio Code > Enhance the app](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#enhance-the-app) starts off with:

> Replace the contents of the `Main` method in Program.cs, which is the line that calls `Console.WriteLine`, with the following code:
>
> This code displays "What is your name?" in the console window and waits until the user enters a string followed by the <kbd>Enter</kbd> key.

It seems like there is code missing between "with the following code:" and "This code displays".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET Core console application using Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, I'm working on it now.  Meanwhile until it's fixed you can find the missing code here:  https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio#enhance-the-app  Make sure the language switcher at the top of the page is set to C#
