### ISSUE TITLE
Code example not compliant with guideline

### ISSUE THREAD

**Issue by kthy** [dotnet/docs#18900]
Page says:

> Do not use implicit typing to determine the type of the loop variable in foreach loops.
> 
> The following example uses explicit typing in a foreach statement.
> 
> ```
> foreach (var ch in laugh)
> {
>    if (ch == 'h')
> ...
> ```

The first line of the code example should read `foreach (char ch in laugh)` according to the guideline text right above it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @kthy 

I'll review the PR for this issue shortly.
