### ISSUE TITLE
Confusion regarding Claims

### ISSUE THREAD

**Issue by DrGriff** [dotnet/docs#18924]
**Issue description**

--------------------
I originally opened here: https://github.com/dotnet/AspNetCore.Docs/issues/18723, but was requested to open a new request in this forum...
--------------------

Been reading up on Identity Claims, and came across two Microsoft articles that seemingly conflict:

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1

> A claim is a name value pair that represents what the subject is, not what the subject can do.

https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/managing-claims-and-authorization-with-the-identity-model#claims

> A claim is the expression of a right with respect to a particular value. A right could be something like "Read", "Write", or "Execute."

So in the first example, the claim is about the user's date-of-birth. It's a fact about the user. An eCommerce website can take this claim and determine whether the user may buy alcohol. A games website can take the same claim and determine whether the user may access age-restricted content. What they can do is determined by the consuming application.

For the second example, the Claim is telling the consuming program what the user can and cannot do, e.g. this user may view pricing, but they can not edit it. Okay, the example is in respect to WCF, but it's still using Claims.

When trying to ascertain "best practice" for Claims, these documents appear to conflict in their approach. My suggestion would be to update the one that doesn't adhere to Microsoft's current view of "best practice" (which I'm guessing is that the Claim is a "fact" and not a "right").

Thanks

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Thraka** [comment]
@DrGriff Hello. I don't really see a conflict. In reading the articles (because I don't know much about it so to help answer your question, I have to research it too) I find that they are describing how those particular frameworks are using claims. They aren't guiding you on how to design your own claims system, so I wouldn't be looking to them as "best practices" in that sense.
