### ISSUE TITLE
checksumalgorithm

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18925]
The comments below were machine-translated

@jams6 commented on [Fri Jun 05 2020](https://github.com/dotnet/docs.es-es/issues/167)

373/5000
There are inconsistencies in these 2 categories, for example:

In the category
C # compiler options, by category - checksumalgorithm: <alg>
Says the default value is SHA1 (default)

But in the category
C # compiler options, in alphabetical order - -checksumalgorithm: <alg>
Says the default value is SHA256 (default value)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8a3026d8-a871-b6a5-04dd-393212fdf331
* Version Independent ID: 29b22a16-f7dd-9c66-4393-2a8ea09b3ae8
* Content: [Opciones del compilador de C#, por categoría](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/compiler-options/listed-by-category)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-by-category.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/compiler-options/listed-by-category.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Fri Jun 05 2020](https://github.com/dotnet/docs.es-es/issues/167#issuecomment-639649429)

Hello, @jams6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Fri Jun 12 2020](https://github.com/dotnet/docs.es-es/issues/167#issuecomment-639770438)

Hola, @jams6 :

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?
La documentación dice:

> Especifique el algoritmo para calcular la suma de comprobación del archivo de origen almacenada en el archivo PDB. Los valores admitidos son: SHA1 (predeterminado) o SHA256.
> Debido a problemas de colisión con SHA1, Microsoft recomienda SHA256.

Atentamente,
Equipo internacional de Microsoft DOCS

---

@jams6 commented on [Sat Jun 06 2020](https://github.com/dotnet/docs.es-es/issues/167#issuecomment-640005015)

When you switch pages to:
C # compiler options, in alphabetical order
now it says the default is SHA256 (default) and not SHA1.

-checksumalgorithm: <alg>
Specifies the algorithm to calculate the checksum of the source file stored in the PDB file. Supported values are: SHA256 (default) or SHA1.
Due to collision issues with SHA1, Microsoft recommends SHA256.

**Comment by BillWagner** [comment]
Thanks for reporting this @jams6

I've opened PR #18956 to fix this issue.
