### ISSUE TITLE
missing link to debian install instructions.

### ISSUE THREAD

**Issue by Spongman** [dotnet/docs#18921]
missing link to debian install instructions.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET Core and Linux Distributions](https://docs.microsoft.com/en-us/dotnet/core/install/linux#debian)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by dagood** [comment]
You can follow the link in the table to get to the page:

![image](https://user-images.githubusercontent.com/12819531/84515456-1bcf6200-ac92-11ea-927e-f4697a4332d9.png)

Or you can navigate to the section directly in the left sidebar.

But I do think we should add the "For more information, see *Install .NET Core on Debian*" sentence. (Also for openSUSE, Red Hat, and SLES.) Thanks for pointing this out.
