### ISSUE TITLE
Code of Example not fully efficient, it can be more elegant

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#18920]
Current Code
```
int[] numbers = { 1, 4, 7, 10 };
int product = numbers.Aggregate(1, (interim, next) => interim * next);
Console.WriteLine(product);   // output: 280
```
In this code used not right variant of  Enumerable.Aggregate Method() :
`Aggregate<TSource,TAccumulate>(IEnumerable<TSource>, TAccumulate, Func<TAccumulate,TSource,TAccumulate>)`, because `TAccumulate` value in this case not demanded , because first element `=1`

In this case more correct will be more useful more simple variant of Aggregate Method(), final code will be (with the same result): 
```
int[] numbers = { 1, 4, 7, 10 };
int product = numbers.Aggregate((interim, next) => interim * next); // without "1,"
Console.WriteLine(product);   // output: 280
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a695fde2-da48-835f-423d-d34fb048d6ab
* Version Independent ID: e8eab8da-72ba-991a-c011-a41d2ed9939d
* Content: [=&gt; operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)
* Content Source: [docs/csharp/language-reference/operators/lambda-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/lambda-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @DSivtsov - thank you for posting this suggestion. I agree that the results are the same, and that this version is more elegant. I labeled this issue as "up-for-grabs", if you do create a pull request please add details as to why the overload is used. Thank you

**Comment by pkulikov** [comment]
@IEvangelist is it necessary to explain the choice of the overload? This is the example of multiple input parameters to a lambda expression. I'm afraid the discussion about the choice of the overload would be out of topic. If such a discussion is necessary, I would update the example to such where it's not necessary.

**Comment by IEvangelist** [comment]
> @IEvangelist is it necessary to explain the choice of the overload? This is the example of multiple input parameters to a lambda expression. I'm afraid the discussion about the choice of the overload would be out of topic. If such a discussion is necessary, I would update the example to such where it's not necessary.
> 
> Or you've meant PR description, not the article?

I meant for the PR description... I should have made that more obvious. Good call out.

**Comment by DSivtsov** [comment]
Was glad to be helpful. Will i must close the ticket?
P.S> What is mean "PR description."? Is it a internal code ;)?

**Comment by pkulikov** [comment]
@DSivtsov If you want, you can submit pull request to this repository. The code is in the following file:
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/snippets/LambdaOperator.cs

**Comment by DSivtsov** [comment]
I submitted the pull request.
Because currently used the Func<TAccumulate,TSource,TAccumulate>) variant is more interesting that i was propose early, i decided that will be more appropriate not change method,  but change initial data (the result which showing in comments doesn't change).

**Comment by DSivtsov** [comment]
:) I hope from second time, I made correct PR (I thought that "PR" is a secret internal code :) )
