### ISSUE TITLE
Csharp

### ISSUE THREAD

**Issue by pdunbard** [dotnet/docs#18938]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=1)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@pdunbard Is there an issue here? Can you supply any details?

**Comment by pdunbard** [comment]
HI I am sorry Ms. Wagner, it was inadvertently sent...
Peter

**Comment by BillWagner** [comment]
thanks @pdunbard I'll close this
