### ISSUE TITLE
ICorDebugHeapSegmentEnum references COR_HEAPOBJECT instead of COR_SEGMENT

### ISSUE THREAD

**Issue by WilliamXieMSFT** [dotnet/docs#18930]
Looks like a copy-paste error from ICorDebugHeapEnum interface.
ICordebugHeapSegmentEnum enumerates COR_SEGMENTs, not COR_HEAPOBJECT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b094cf-11e0-03ce-bf79-435b2129c0b4
* Version Independent ID: 1184c70b-6899-9de2-37ce-23e62e1b6a08
* Content: [ICorDebugHeapSegmentEnum Interface](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugheapsegmentenum-interface)
* Content Source: [docs/framework/unmanaged-api/debugging/icordebugheapsegmentenum-interface.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/icordebugheapsegmentenum-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by tommcdon** [comment]
@hoyosjs
