### ISSUE TITLE
Missing docs for dotnet-gcdump

### ISSUE THREAD

**Issue by giggio** [dotnet/docs#18935]
Either a new page should be created, or it should be refererenced on this page.

See https://devblogs.microsoft.com/dotnet/collecting-and-analyzing-memory-dumps/
for more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a269a64-0a27-27d3-a509-47b9a0d114bf
* Version Independent ID: 49ff97ff-b39a-5ae8-e4b8-81a4f8eab50c
* Content: [dotnet-dump - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump)
* Content Source: [docs/core/diagnostics/dotnet-dump.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-dump.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by sdmaclea** [comment]
We need a new page.  @shirhatti @josalem
