### ISSUE TITLE
Please document the DisableImplicitFrameworkReferences property

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#18946]
I couldn't remember what it was called. It took running `msbuild /pp` and poring over the output to spot it.

Same as https://github.com/dotnet/docs/issues/18945.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Helpful links:

https://github.com/dotnet/sdk/pull/633#issuecomment-272515440
https://github.com/dotnet/docs/commit/6e2133811b33efcaf281aa0895c2b75c8f29d6b1

**Comment by dsplaisted** [comment]
@jnm2 FYI, try using binlogs and MSBuild Structured Log Viewer to investigate this type of thing in the future: https://msbuildlog.com/

**Comment by jnm2** [comment]
@dsplaisted Thanks for the tip! That's actually what I used to generate the log and preprocess.

**Comment by dsplaisted** [comment]
@jnm2 With the log viewer, generally I don't need to preprocess a project unless I'm confused about evaluation order.  The "Find in Files" tab usually works well for me for figuring out what a property does or where logic is that does something specific.

**Comment by jnm2** [comment]
How did I never see that tab!? You made my day, thank you!
