### ISSUE TITLE
Provide example for usage of generic type constraints with interface or class inheritance

### ISSUE THREAD

**Issue by yb1997** [dotnet/docs#18948]
Need example for syntax of declaring a class that implements an interface or inherits a class and also uses generic type constraint.
Following code can be shown as an example:
```csharp
public class MyClass<T>: IEnumerable where T : class { }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74dfcde5-aa2b-1128-fa29-f198a6e437b7
* Version Independent ID: 59aeccf5-364c-77a8-88dc-cb529b76aebc
* Content: [where (generic type constraint) - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint)
* Content Source: [docs/csharp/language-reference/keywords/where-generic-type-constraint.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/where-generic-type-constraint.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @yb1997 

I've added this to our backlog to address when we next update this article.

I've also add the "up for grabs" label if a community member wants to submit a fix.
