### ISSUE TITLE
Please document the DisableImplicitFrameworkReferences property

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#18945]
I couldn't remember what it was called. It took running `msbuild /pp` and poring over the output to spot it.

This was added alongside the other properties on the page that add default items to the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
This will be covered by #18946.
