### ISSUE TITLE
Change default ActivityIdFormat to W3C

### ISSUE THREAD

**Issue by shirhatti** [dotnet/docs#18953]
## Change default ActivityIdFormat to W3C

The W3C ActivityIdFormat was introduced as an alternative to the hierarchical ActivityIdFormat in .NET Core 3.0. In an attempt to preserve compatibility this format wasn't made as the default format.

In .NET 5.0, we are changing the default format.

### Version introduced

.NET 5

Any app targeting any platform other than .NET 5.0 will not get this change and will experience the old behavior which is setting the default ActivityIdFormat to `Hierarchical`. This will include the platforms net45+, netstandard1.1+, and netcoreapp (1.x, 2.x, and 3.x)

### Old behavior

The default identifier format used for activity was the hierarchical activity format.

```C#
Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical
```

### New behavior

The default identifier format used for activity is the W3C activity format.

```C#
Activity.DefaultIdFormat = ActivityIdFormat.W3C
```

### Reason for change

However, as the [W3C format has been ratified](https://www.w3.org/TR/trace-context/) and [gains traction across multiple language implementations](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md) it makes sense to change the default `ActivityIdFormat` to `W3C`. 

### Recommended action

Given that libraries such as ASP.NET Core can consume, and HttpClient can propagate both versions of the `ActivityIdFormat`, there is no recommended action if the user's application is agnostic to the identifier used for distributed tracing.

Assuming interoperability with existing systems is required **OR** the current systems rely on the format of the identifier, there are a few options to preserve existing behavior.

1. Use the existing public API, `Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical`
2. Set an AppContext switch to revert to the old behavior, this can be done using one of the following options:
    - in the project 
```XML
        <ItemGroup>
            <RuntimeHostConfigurationOption Include="System.Diagnostics.DefaultActivityIdFormatIsHierarchial" Value="true" />
        </ItemGroup>
```
    - in runtimeconfig.json file

```JSON
        {
            "runtimeOptions": {
                "configProperties": {
                    "System.Diagnostics.DefaultActivityIdFormatIsHierarchial": true
                }
            }
        }
```
    - Setting the environment variable value `DOTNET_SYSTEM_DIAGNOSTICS_DEFAULTACTIVITYIDFORMATISHIERARCHIAL` to true or 1.

### Category

Core .NET libraries

### Affected APIs

https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.defaultidformat

---
#### Issue metadata

* Issue type: breaking-change

**Comment by shirhatti** [comment]
cc @tarekgh

**Comment by gewarren** [comment]
@shirhatti Which preview will this go out in?

**Comment by tarekgh** [comment]
@gewarren if we'll merge this PR this week, it will be part of Preview 7.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/34787
https://github.com/dotnet/runtime/pull/37686

**Comment by gewarren** [comment]
Is the runtimeconfig.json example correct?

```
        {
            "runtimeOptions": {
                "configProperties": {
                    "System.Globalization.Invariant": true
                }
            }
        }
```

**Comment by tarekgh** [comment]
@gewarren good catch. it is not. we should use `System.Diagnostics.DefaultActivityIdFormatIsHierarchial`. I'll try to edit it.

**Comment by tarekgh** [comment]
done!
