### ISSUE TITLE
[WinForms] Incorrect default value for `ListView.HideSelection` since net48

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#18952]
**Issue description**

In net48 as part of accessibility enhancement work the default value for [`ListView.HideSelection` property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.hideselection?view=netframework-4.8#remarks) has changed to `false` unless a user opted out of accessibility enhancements introduced in net48 (i.e. `Switch.UseLegacyAccessibilityFeatures.3=false`). More information can be found here: https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility

In .NET Core 3.x and .NET 5 onwards the accessibility quirks available in .NET Framework were removed, and the default value is `false`.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4385
