### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by laurametzner** [dotnet/docs#18967]
When trying to run the application, I get this error:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

When doing an internet search, I find the following:

In Visual Studio's menu, go to Tool > NuGet Package Manager > Manage NuGet Packages for Solution...

Unfortunately, in order to get this option, I have to find the solution, and those listed don't seem to be what I'm looking for:

![image](https://user-images.githubusercontent.com/66390271/84719485-58b88480-af30-11ea-83bc-000d9cf15540.png)

Please help!

Thanks,
Laura Metzner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hello @laurametzner 

Have you compared your code to the version [here in our sample repository](https://github.com/dotnet/samples/tree/master/csharp/getting-started/console-webapiclient)? That should help find any differences. That version does run correctly, and should be able to help you diagnose the issue.

If you have further questions, let us know.

**Comment by laurametzner** [comment]
Okay, I'm trying this again. Removed the repository I cloned yesterday. Went to https://github.com/dotnet/samples, clicked the green Clone or download button, go into Visual Studio 2019, and clicked on Clone a repository. Left clicked on File, Open, Open from Github, then pressed the Clone button.Then went to Solution Explorer. Navigated to console-webapiclient. Double-click on webapiclient.csproj. I don't see an option to run the program, so I go into Package Manager Console and type dotnet restore. I get the following output:
...
--------------------------------------------------------------------------------------MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.PM> pwd
Path                                      ----                                      C:\Users\lgh19\source\repos\dotnet\samples
PM> dotnet rundotnet : Couldn't find a project to run. Ensure a project exists in C:\Users\lgh19\source\repos\dotnet\samples, or pass the path to the project using --project.At line:1 char:1+ dotnet run+ ~~~~~~~~~~    + CategoryInfo          : NotSpecified: (Couldn't find a...sing --project.:String) [], RemoteException    + FullyQualifiedErrorId : NativeCommandError PM> 
What now?    On Tuesday, June 16, 2020, 08:11:55 AM PDT, Bill Wagner <notifications@github.com> wrote:  
 
 


Hello @laurametzner

Have you compared your code to the version here in our sample repository? That should help find any differences. That version does run correctly, and should be able to help you diagnose the issue.

If you have further questions, let us know.

**Comment by laurametzner** [comment]
Okay, I navigated to C:\Users\lgh19\source\repos\dotnet\samples\csharp\getting-started\console-webapiclient. Did a dotnet restore and dotnet run. I got this:
PM> dotnet restore  Determining projects to restore...  All projects are up-to-date for restore.PM> dotnet runBenchmarkDotNetPowerful .NET library for benchmarkinghttps://github.com/dotnet/BenchmarkDotNethttps://benchmarkdotnet.org/54086/16/2020 6:16:27 AM
reactiveThe Reactive Extensions for .NEThttps://github.com/dotnet/reactivehttp://reactivex.io/43866/14/2020 11:15:34 PM
efcoreEF Core is a modern object-database mapper for .NET. It supports LINQ queries, change tracking, updates, and schema migrations.https://github.com/dotnet/efcorehttps://docs.microsoft.com/ef/91796/16/2020 12:04:52 PM
aspnetcoreASP.NET Core is a cross-platform .NET framework for building modern cloud-based web applications on Windows, Mac, or Linux.https://github.com/dotnet/aspnetcorehttps://asp.net/179366/16/2020 12:43:27 PM
ScaffoldingCode generators to speed up development.https://github.com/dotnet/Scaffolding
3336/11/2020 9:50:28 PM
Docker.DotNet:whale: .NET (C#) Client Library for Docker APIhttps://github.com/dotnet/Docker.DotNethttps://www.nuget.org/packages/Docker.DotNet/11875/9/2020 3:03:30 AM...
Is this the expected output?
Thanks,Laura Metzner    On Tuesday, June 16, 2020, 12:46:46 PM PDT, Laura Metzner <lgh1963@sbcglobal.net> wrote:  
 
  Okay, I'm trying this again. Removed the repository I cloned yesterday. Went to https://github.com/dotnet/samples, clicked the green Clone or download button, go into Visual Studio 2019, and clicked on Clone a repository. Left clicked on File, Open, Open from Github, then pressed the Clone button.Then went to Solution Explorer. Navigated to console-webapiclient. Double-click on webapiclient.csproj. I don't see an option to run the program, so I go into Package Manager Console and type dotnet restore. I get the following output:
...
--------------------------------------------------------------------------------------MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.PM> pwd
Path                                      ----                                      C:\Users\lgh19\source\repos\dotnet\samples
PM> dotnet rundotnet : Couldn't find a project to run. Ensure a project exists in C:\Users\lgh19\source\repos\dotnet\samples, or pass the path to the project using --project.At line:1 char:1+ dotnet run+ ~~~~~~~~~~    + CategoryInfo          : NotSpecified: (Couldn't find a...sing --project.:String) [], RemoteException    + FullyQualifiedErrorId : NativeCommandError PM> 
What now?    On Tuesday, June 16, 2020, 08:11:55 AM PDT, Bill Wagner <notifications@github.com> wrote:  
 
 


Hello @laurametzner

Have you compared your code to the version here in our sample repository? That should help find any differences. That version does run correctly, and should be able to help you diagnose the issue.

If you have further questions, let us know.
