### ISSUE TITLE
HEAvy SHift FInger

### ISSUE THREAD

**Issue by hobozero** [dotnet/docs#18969]
I'm glad I'm not the only one who does this in documentation. There is a small typo on the first line:

Runtime I**_D_**entifier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
Thanks for reporting that!
