### ISSUE TITLE
Option STRICT IS ERRONEOUS

### ISSUE THREAD

**Issue by Nigelino** [dotnet/docs#18962]
Tried this but it only produces an error "Expected base or Compare"
Is this outdated? 
![20201506Option bug](https://user-images.githubusercontent.com/62855676/84699930-afcf5100-af52-11ea-9fc6-0ebf13401017.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d661f3-f79b-5886-5fc9-5e9dc88886a7
* Version Independent ID: 85ed7310-c84b-0b76-c94c-5cbdd7cf86da
* Content: [Object variable or With block variable not set - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set)
* Content Source: [docs/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
@Nigelino I looked at the screenshot you've attached, and it looks like you are [Visual Basic for Applications](https://docs.microsoft.com/office/vba/api/overview/), not Visual Basic.

The reference above should help you address this. Let us know if that helps.

**Comment by Nigelino** [comment]
Thanks

There just had to be a simple explanation. That’s what you get for
following Microsoft prompts!

    Nigel

**Comment by tdykstra** [comment]
Closing, as the question was answered.
