### ISSUE TITLE
Documentation for  ICorDebugHeapSegmentEnum::Next simply duplicates documentation for ICorDebugHeapEnum::Bext

### ISSUE THREAD

**Issue by delmyers** [dotnet/docs#18963]
It looks like the documentation for this page is incorrect and is simply a duplicate of this page:

https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugheapenum-next-method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 981b9449-a085-8015-5612-2f01ba3d7d4b
* Version Independent ID: 738fc0ea-5425-56a4-fc0d-cf6dd97d038a
* Content: [ICorDebugHeapSegmentEnum::Next Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugheapsegmentenum-next-method)
* Content Source: [docs/framework/unmanaged-api/debugging/icordebugheapsegmentenum-next-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/icordebugheapsegmentenum-next-method.md)
* Product: **dotnet-framework**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by hoyosjs** [comment]
Hey Del, I think I just fixed the types also described in #18930 (COR_SEGMENT, rather than COR_HEAPOBJECT). Although you seem to point out that there's some content issue?

**Comment by delmyers** [comment]
It looks like this bug is just a duplicate of the other one. The fix that you have for #18930 is sufficient.
