### ISSUE TITLE
How can I reference classes from this other project? "using" odes not seems to work.

### ISSUE THREAD

**Issue by Schekn** [dotnet/docs#18966]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ab77c3-eba6-e947-8ffa-0fcda722f34b
* Version Independent ID: 48bbcb58-cfd1-b3d3-7a2a-319716541362
* Content: [dotnet add reference command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference)
* Content Source: [docs/core/tools/dotnet-add-reference.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-reference.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See the tutorial https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code 

It uses the CLI to set a project reference and the code uses classes from the referenced project.

**Comment by Schekn** [comment]
Not sure why this is closed. **using** does not work. I need to add nemspace before the class name.

**Comment by tdykstra** [comment]
Did you try following the tutorial I referred to?
