### ISSUE TITLE
CLR Profiling API docs: clarify which versions of .NET Framework and .NET Core the ICorProfilerInfo* interfaces support

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/docs#18973]
**Issue description**

The [doc for ICorProfilerInfo10](https://github.com/dotnet/docs/blob/e5fccd84b508544367433ce6a825946cbdfc0123/docs/framework/unmanaged-api/profiling/icorprofilerinfo10-interface.md) states that it is available starting .NET Core 3.0, but doesn't specify if it also made it into .NET Framework.

The [doc for ICorProfilerInfo9](https://github.com/dotnet/docs/blob/e5fccd84b508544367433ce6a825946cbdfc0123/docs/framework/unmanaged-api/profiling/icorprofilerinfo9-interface.md) states that it is available starting .NET Core 2.2, but doesn't specify if it also made it into .NET Framework.

The [doc for ICorProfilerInfo8](https://github.com/dotnet/docs/blob/e5fccd84b508544367433ce6a825946cbdfc0123/docs/framework/unmanaged-api/profiling/icorprofilerinfo8-interface.md) states that it is available starting .NET Framework 4.7.2, but doesn't specify what version of .NET Core it's supported on.

These details would be very useful for profiler implementors to have. I'd be very happy to send in a PR for this, but I couldn't find an authoritative answer to these question anywhere online. Appreciate any help. /cc @davmason 

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [-] .NET Core
- [-] .NET Framework
- [ ] .NET Standard

Edited by gewarren to add document details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300d73c8-1422-946d-89c7-5e6a666d98aa
* Version Independent ID: 4f7358ea-7eff-ad82-c306-592b15c52948
* Content: [ICorProfilerInfo Interface](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-interface)
* Content Source: [docs/framework/unmanaged-api/profiling/icorprofilerinfo-interface.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/icorprofilerinfo-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by davmason** [comment]
Hi @OmerRaviv 

ICorProfilerInfo8 and ICorProfilerCallback9 are currently the last interfaces supported on .net framework. It is very unlikely given the servicing policy of 4.8 that any future ICorProfiler interfaces will appear on .net framework.

ICorProfiler9/ICorProfilerCallback10 (and future additions) are only on .net core.
