### ISSUE TITLE
Member links should include type in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1897]
Currently, it seems that standard links to type members in API reference render as just the method name, which can cause confusion.

For example, consider [the `Regex.Split(string, string)` method in docs.ms](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.split?view=netframework-4.7#System_Text_RegularExpressions_Regex_Split_System_String_System_String_):

![](https://cloud.githubusercontent.com/assets/287848/25027494/51e9b026-20ad-11e7-926b-8725112342cf.png)

[On MSDN](https://msdn.microsoft.com/en-us/library/8yttk7sy(v=vs.110).aspx#Remarks):

![](https://cloud.githubusercontent.com/assets/287848/25027516/724ac79c-20ad-11e7-9d6a-a297dadc7c4a.png)

Notice how on MSDN, it's clear that the first sentence talks about the difference between `Regex.Split` and `String.Split`, while on docs.ms, this is not clear at all.

I think the solution would be to make member links render similarly as on MSDN on all docs.ms API reference.

Another option, in case it's deemed that the shorter version (without type name) is preferable where it doesn't cause confusion, would be to manually fix just the problematic articles (like `Regex.Split`).

**Comment by rpetrusha** [comment]
Thanks for noticing this, @svick. This is a rendering bug. The spec for the `<xref>` tag, which is used to define API links, supports a `displayProperty=fullName` key/value pair to control the display of the API. In the case of the RegexSplit overloads, the <xref> tags for Regex.Split and String.Split that are correctly formed (in three overloads, they are not -- I'll correct them) all contain the `displayProperty=fullName` key\value pair, indicating that they should render as type name followed by method name. 

I've opened an internal bug, #971093, to track this issue. Hopefully, it will be fixed soon.

**Comment by svick** [comment]
It looks like this was changed, but now the links include the namespace, which I don't think is necessary:

![](https://cloud.githubusercontent.com/assets/287848/25048270/d0611df2-213b-11e7-92b0-84b50400a0aa.png)

**Comment by mairaw** [comment]
I agree @svick. It should only contain Type.MemberName. I'm following up on the bug with the engineering team.

**Comment by mairaw** [comment]
This has been fixed now. Closing the issue.

![image](https://cloud.githubusercontent.com/assets/12971179/25594929/a63e208a-2e77-11e7-8276-6d60fd456614.png)
