### ISSUE TITLE
Can we include a link to documentation for creating/testing a new Project Sdk?

### ISSUE THREAD

**Issue by andyhopp** [dotnet/docs#18977]
I would like to create a custom project SDK, but do not know how to get started or how to test my .targets/.props. Is there a set of instructions for how to get started and how to test without submitting to NuGet first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET Core project SDK overview](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/overview.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@BillWagner This sounds like a good suggestion to me. Can you re-open?

**Comment by BillWagner** [comment]
reopening per feedback.

**Comment by gewarren** [comment]
@dsplaisted Do you know of any existing guidance around creating a custom project SDK?

**Comment by dsplaisted** [comment]
No, I don't think we have anything.  This page gives a little more info: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022

Also, this repo has several SDKs so you can see how they are built: https://github.com/Microsoft/MSBuildSdks

/cc @jeffkl

**Comment by gewarren** [comment]
@ghogen Do you plan to add any documentation along these lines?

**Comment by ghogen** [comment]
@gewarren This has been discussed, but in consultation with @rainersigwald, it was given a very low priority.

**Comment by gewarren** [comment]
Thanks. In that case, I'm going to close this issue (again).

**Comment by ghogen** [comment]
@andyhopp In the linked GitHub issue in the Visual Studio docs repo, you can find some hints on this.
