### ISSUE TITLE
Incorrect statement about value types

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/docs#18987]
The page reads:

"Value types are typically copied when passed to a method or returned from a method. **This behavior includes copying the value of `this` when calling members of a value type.**"

The highlighted section is incorrect for instance methods of a struct:

```cs
public struct S
{
    public int I;

    public void Method() => I++;
}

S s = default;
Assert.AreEqual(0, s.I);
s.Method();
Assert.AreEqual(1, s.I);
```

If `this` within `Method` was a copy of the struct, then the second assertion would fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @WizardBrony 

This statement does need to be fixed. There are some subtleties to the fix, see the C# language specification, in the section for [this access](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#this-access).  The pertinent points are (highlights mine):

>- When this is used in a primary_expression within an instance method or instance accessor of a struct, it is classified as a variable. The type of the variable is the instance type (The instance type) of the struct within which the usage occurs.
>   - If the method or accessor is not an iterator (Iterators), *the `this` variable represents the struct for which the method or accessor was invoked, and behaves exactly the same as a ref parameter of the struct type*.
>  - If the method or accessor is an iterator, *the `this` variable represents a copy of the struct for which the method or accessor was invoked, and behaves exactly the same as a value parameter of the struct type*.

The statement is correct for iterator methods, but not for other struct members.

**Comment by WizardBrony** [comment]
@BillWagner 

For completeness, it should be noted that the `this` variable represents a copy of the struct within both iterators _**and**_ async instance methods of structs:

```cs
public struct S
{
    public int I;

    public void Method() => I++;

    public IEnumerable<int> IteratorMethod()
    {
        yield return I++;
    }

    public async Task MethodAsync() => I++;
}

S s = default;
Assert.AreEqual(0, s.I);
s.Method();
Assert.AreEqual(1, s.I);

s.IteratorMethod().ToList();
await s.MethodAsync();
Assert.AreEqual(1, s.I);
```
