### ISSUE TITLE
Czech words in german text

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#18992]
---
**Issue moved from MicrosoftDocs/feedback#2799**
- Please respond to @oo-dev17.

---

_From @oo-dev17 on Friday, May 29, 2020 8:03:21 AM_

**Describe the bug**
On the page
https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem
suddenly the words "nastaven NA hodnotu" appear, that are not german (but czech)

**To Reproduce**
1. Go to https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem
3. Scroll down to the lower half of the page

**Expected behavior**
The text shoulod be german

**Screenshots**
![image](https://user-images.githubusercontent.com/6067255/83236194-6aa9d180-a193-11ea-9547-bdf3c5b1ce58.png)

**Desktop (please complete the following information):**
 - Browser  chrome 
 - Version 83

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#2799**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Friday, May 29, 2020 8:03:22 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
cc @JasonCard

**Comment by srvbpigh** [comment]
Hello @gewarren:

We are evolving our internal process and engineering pipeline. Unfortunately, this is resulting in delays to processing your feedback.

We truly appreciate your contribution to our articles and we are looking forward to your continuous support and understanding.


Microsoft DOCS Global Experience Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.de-de #202](https://github.com/dotnet/docs.de-de/issues/202) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @gewarren 

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/dotnet/docs.de-de/issues/202

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
#please-close
