### ISSUE TITLE
Wrong syntax in protobuf sample code

### ISSUE THREAD

**Issue by papajames** [dotnet/docs#19000]
The stock proto file contained invalid syntax.

The correct one should be
```protobuf
syntax = "proto3";

option csharp_namespace = "TraderSys";

message Stock {

    int32 id = 1;
    string symbol = 2;
    string display_name = 3;
    int32 market_id = 4;

} 
```

And the current one is
```protobuf
syntax "proto3";

option csharp_namespace = "TraderSys";

message Stock {

    int32 id = 1;
    string symbol = 2;
    string display_name = 3;
    int32 market_id = 4;

} 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed647fa-08e8-d503-74a2-097ac3c5022a
* Version Independent ID: 5087148f-07c4-8d4e-fe6b-d327f1b01532
* Content: [Protobuf messages - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-messages)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-messages.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-messages.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by IEvangelist** [comment]
Thank you @papajames for posting this issue. You're correct that the protobuff syntax is incorrect in the example, I have fixed it with #19002.
