### ISSUE TITLE
Redundant Cast : Virtual Member Section

### ISSUE THREAD

**Issue by clinton1994** [dotnet/docs#19013]
In the example illustrated [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/polymorphism#virtual-members) as

```
DerivedClass B = new DerivedClass();
B.DoWork();  // Calls the new method.

BaseClass A = (BaseClass)B;
A.DoWork();  // Also calls the new method.

```

to 
```
DerivedClass B = new DerivedClass();
B.DoWork();  // Calls the new method.

BaseClass A = B; // Explicit Cast not necessary 
A.DoWork();  // Also calls the new method.
```

[Explicit cast was not necessary]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ebd197-8f01-b8d7-45d6-1a7afba572b4
* Version Independent ID: 0790b314-a794-6ce3-15f0-37281faa00a6
* Content: [Polymorphism - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/polymorphism)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/polymorphism.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/polymorphism.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I agree that the cast is redundant @clinton1994 Thanks for starting this discussion.

When I last reviewed this code, I left the cast in place to illustrate that there is a conversion happening (an implicit conversion, so the cast isn't needed). Do you think the cast detracts from the explanation? If so, I'll add this to the backlog and get it addressed.

**Comment by clinton1994** [comment]
@BillWagner  I think so, because only explicit conversions require a _cast expression_ and maybe there is a bit of a chance for someone new to misinterpret that cast to actually mean explicit in their first go, unless they try out the code or take a second look at it. 

Or as an alternative a comment can be in place to denote that its an implicit conversion.
