### ISSUE TITLE
.NET Data hub page taxonomy

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/docs#19029]
A new .NET Data landing page will help .NET developers quickly navigate to the area of interest. Data spans multiple topics, so first it is important that the categories and topics are correct. Ultimately this may result in sub-category pages being created. Once the hierarchy and topics are approved, new issues will be created to track the categories and determine what documents can be linked to "as is", what documents will need to be updated and what new documents should be created.

Here is the draft outline (feedback welcome):

---

- Unstructured data 
    - Blob Storage 
    - Files 
- Semi-structured data 
    - Azure Cosmos DB 
    - Serializers (Json, Xml, etc.) 
- Structured and relational data 
    - SQL Server 
    - Azure hosted (SQL, MySQL, PostgreSQL, etc.) 
- ADO .NET 
    - Providers 
    - DataSet/Table/etc. 
- Common Data Services (CDS) 
- Cache 
    - Redis 
- Object mappers 
    - Dapper 
    - EF Core 
    - Linq to DB
    - Sqlite-net
- Queries and Expressions 
    - LINQ 
- Big Data and Machine Learning 
    - ML.Net 
    - Spark.Net 
    - Azure Cognitive Services 
    - Azure Data Lake 
    - Azure Synapse 
- Messaging and Streaming 
    - ServiceBus 
    - EventHub 
    - SignalR 
    - Azure Event Grid 
- Visualization 
    - Power BI 
- APIs 
    - REST 
    - OData 
    - GraphQL 
    - gRPC 
- Platform-specific 
    - ASP .NET Core 
    - WPF 
    - WinForms 
    - Xamarin
    - UWP 
    - Blazor 
- Migration 
    - On-prem to cloud PaaS 
    - Lift and shift 
    - Hybrid 
- End-to-end scenarios “I want to…” 
    - Build a web-based CRUD app 
    - Build a desktop Line of Business app 
    - Build an API for mobile or desktop or web clients 
        - Sync data from my mobile or desktop or web client to the API
---

**Comment by JeremyLikness** [comment]
@BillWagner can you tag this for the .NET wave and assign to the .NET Data project?

**Comment by Rick-Anderson** [comment]
EF and EF Core?

**Comment by JeremyLikness** [comment]
Hi, @Rick-Anderson. EF Core is listed and the legacy EF documentation will still exist. Rationale behind the platform-specific is thinking of "desktop platforms" (WPF, WinForms) verse. ASP.NET Core as the "web platform." The section may need a better name but the idea was if you are doing file->new (project type) that we have specific guidance for approaches to data with that project type.

**Comment by bricelam** [comment]
Some additional libraries that come to mind:
- [Azure Mobile Apps](https://docs.microsoft.com/previous-versions/azure/app-service-mobile/) (Discontinued)
- [CoreML in Xamarin.iOS](https://docs.microsoft.com/xamarin/ios/platform/introduction-to-ios12/coreml)
- [Dotmim.Sync](https://github.com/Mimetis/Dotmim.Sync)
- [LINQ to DB](https://linq2db.github.io/) (.NET Foundation)
- [Open RIA Services](https://github.com/OpenRIAServices/OpenRiaServices)
- [SQLite-net](https://github.com/praeclarum/sqlite-net)

**Comment by antosubash** [comment]
End-to-end scenarios “I want to…”

- Build an API for mobile or desktop clients.
- Sync data between my mobile or desktop client to the API

**Comment by joaosantana** [comment]
What about UWP?

**Comment by IEvangelist** [comment]
Hi @JeremyLikness - is this task to create a hub page or landing page, or both?

**Comment by JeremyLikness** [comment]
Both, I think

**Comment by JeremyLikness** [comment]
Addressing this effort in [dotnet/EntityFramework.Docs #3833](https://github.com/dotnet/EntityFramework.Docs/issues/3833)

**Comment by IEvangelist** [comment]
Closing this as it was addressed in https://github.com/dotnet/EntityFramework.Docs/issues/3833
