### ISSUE TITLE
Method signature in API reference missing params

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1902]
It seems that when a method has a `params` parameter, this is not reflected in its signature.

Compare [`Task.WhenAll()` on docs.ms](https://docs.microsoft.com/en-us/dotnet/api/System.Threading.Tasks.Task.WhenAll?view=netframework-4.7#System_Threading_Tasks_Task_WhenAll_System_Threading_Tasks_Task___):

![](https://cloud.githubusercontent.com/assets/287848/25042741/9a3bb1ae-211a-11e7-822d-a6cc714138e0.png)

And [on MSDN](https://msdn.microsoft.com/en-us/library/hh160374(v=vs.110).aspx), where it is shown:

![](https://cloud.githubusercontent.com/assets/287848/25042750/a8b5e8c6-211a-11e7-8ac4-fe52e05a5ea7.png)

Considering that `params` is an important part of method signature, I think it should be shown.

**Comment by BillWagner** [comment]
@DuncanmaMSFT Can you look into this?  It looks like something that happened during the migration.

**Comment by mairaw** [comment]
Opened internal bug #980013 to track this.

**Comment by eduard-malakhov** [comment]
@mairaw I just noticed that this issue was actually fixed [here](https://github.com/dotnet/docs/commit/7ec170f7b7e9d8e3c509a1e041a6dde802deed86#diff-bebdf20fd05294decc2c570402abddb5) and it's in production already.

**Comment by mairaw** [comment]
You're right @eduard-malakhov! It was resolved back in October. Thanks for bringing this to my attention.
