### ISSUE TITLE
Not working on raspberry pi with ubuntu 20.04

### ISSUE THREAD

**Issue by realivanjx** [dotnet/docs#19038]
Doesnt work on raspberry pi with ubuntu 64 bit. Says unable to locate package. Already tried the troubleshoting tips but none of them works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Can you provide more information? Please copy/paste the input/output from following the article steps. Also, provide information about the specific distro build you're using.

**Comment by dagood** [comment]
> Doesnt work on raspberry pi

Your Raspberry Pi uses the arm64 architecture, not x64, so you need to follow these instructions on that page:

> _Package manager installs are only supported on the **x64** architecture_. Other architectures, such as **ARM**, must manually install the .NET Core SDK or .NET Core Runtime. For more information, see the [manually install section](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#manual-install) below.

(I believe I suggested specifically calling out Raspberry Pi in this doc at some point--this question is a little evidence that would be helpful. 😄 It's a very common ARM device to run Linux on, especially for newcomers.)
