### ISSUE TITLE
Duplicate "Interface" links

### ISSUE THREAD

**Issue by YuxuanLin** [dotnet/docs#19035]
At the "See Also" section of the page there are two "Interface" links.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface#see-also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef21cb62-9cbd-84c8-cfae-6dd1a421180b
* Version Independent ID: d931e899-d6f0-55ff-ab3a-dfff6e31f5a2
* Content: [interface - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface)
* Content Source: [docs/csharp/language-reference/keywords/interface.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/interface.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @YuxuanLin 
I've submitted PR #19046 to fix this.
