### ISSUE TITLE
Generic and non-generic overloads of the same method have separate pages

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1903]
If a method has multiple overloads, some generic and some non-generic, it seems the generic overloads are put on one page and the non-generic overloads on another page.

For example, this happens with `Task.WhenAll`:

* [Non-generic overloads](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenall?view=netframework-4.7)
* [Generic overloads](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenall--1?view=netframework-4.7)

I don't see any reason to consider the two groups of overloads separately. In fact, I think doing it this way is going to be confusing: if I click on a link for `WhenAll(Task[])` and then scroll up to look at the overloads and don't find all of them.

**Comment by mairaw** [comment]
Filed internal bug to track this: #980593 

/cc @dend @DuncanmaMSFT @adkinn

**Comment by mairaw** [comment]
Looks like this was fixed. Closing.
