### ISSUE TITLE
Keywords that should not be localized

### ISSUE THREAD

**Issue by JasonCard** [dotnet/docs#19033]
This article contains keywords that should not be localized and some of those are being over-localized. It would be great if those keywords can be blocked from localization by using either in-line code, or [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2d0d24-a228-ab33-1c62-3b0a701ff318
* Version Independent ID: 9ef3c275-ce7b-808b-8acd-3d394296d897
* Content: [Keywords - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/keywords/)
* Content Source: [docs/visual-basic/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/keywords/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
The link for no-loc syntax seems to be only available for employees. I believe it's good to be available for contributors as well.

**Comment by srvbpigh** [comment]
Hello @JasonCard:

We are evolving our internal process and engineering pipeline. Unfortunately, this is resulting in delays to processing your feedback.

We truly appreciate your contribution to our articles and we are looking forward to your continuous support and understanding.


Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @Youssef1313, 
Thank you also for your suggestion to make the no-loc syntax available for external contributors. This suggestion has been passed on internally for consideration.
cc @meganbradley
