### ISSUE TITLE
C# tuple types: Example doesn't correspondence to text

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#19036]
In text
> A Student object now has two accessible Deconstruct methods: the extension method declared for Student types, and the member of the Person type. Both are in scope, and that enables a Student to be deconstructed into either two variables or three. If you assign a student to three variables, the first name, last name, and GPA are all returned. If you assign a student to two variables, only the first name and the last name are returned.

In code below
```
var s1 = new Student("Cary", "Totten", 4.5);
var (fName, lName, gpa) = s1;`
```
I didn't see the code corresponding to 

> If you assign a student to two variables, only the first name and the last name are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @DSivtsov 

It looks like the code and the article have gotten out of sync.  I've added this to the backlog to get addressed.
