### ISSUE TITLE
mlnet

### ISSUE THREAD

**Issue by kofsdsdj** [dotnet/docs#19040]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200d7af-ea16-7b93-5263-6a1ce41ecb3b
* Version Independent ID: e1697ee4-9d3a-e1cc-b678-cab88f1b5f86
* Content: [How to install the ML.NET Command-Line Interface (CLI) tool - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli)
* Content Source: [docs/machine-learning/how-to-guides/install-ml-net-cli.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-ml-net-cli.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @kofsdsdj 

Is there any specific feedback/issues you ran into with this document?

**Comment by luisquintanilla** [comment]
Hi @kofsdsdj ,

Closing this issue for now since it's unclear what the feedback with this document is based on this issue. If you have additional feedback, please feel free to open a new issue.
