### ISSUE TITLE
Consider adding word breaks in signatures in methods table

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1904]
If a method has a long name and long type of its first parameter, the result is that in the Methods table for a type, it will be shown with a line break inside a word. For example, this happens for [`Task.ContinueWith`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=netframework-4.7#methods_):

![](https://cloud.githubusercontent.com/assets/287848/25043063/69e846ae-211d-11e7-9b6e-c8611022a563.png)

Notice the line break Obje-ct. I think that allowing line break before the first parameter type would make it look slightly better:

![](https://cloud.githubusercontent.com/assets/287848/25043088/9aebcf3c-211d-11e7-91a1-b4242cf6d457.png)

As far as I can tell, this can be achieved either using the `<wbr>` tag or the  U+200B ZERO WIDTH SPACE character.

This happens for me in Firefox, but not in Edge or IE (which break the line before the opening parenthesis).

**Comment by mairaw** [comment]
Can you still repro this @svick?

**Comment by svick** [comment]
@mairaw It's better, but I think it could still be improved. What I see now is:

![](https://user-images.githubusercontent.com/287848/37338668-6b4fb260-26b8-11e8-93f2-d4b79208dcac.png)

Notice how the line breaks are often inside a name, even though it's not necessary.

The HTML currently is (after JS runs, i.e. you can see it in F12 tools, but not in View source):

```html
Continue<wbr>With(Action&lt;Task,Object&gt;, Object, Cancellation<wbr>Token, Task<wbr>Continuation<wbr>Options, Task<wbr>Scheduler)
```

When I think it would be better if line breaks were not allowed within a name, but were allowed between words:

```html
ContinueWith(<wbr>Action&lt;<wbr>Task,<wbr>Object&gt;, Object, CancellationToken, TaskContinuationOptions, TaskScheduler)
```

This would render as:

![](https://user-images.githubusercontent.com/287848/37338956-4be49692-26b9-11e8-8e05-8953e408524d.png)

Allowing line breaks within a name might still be useful in some cases, but maybe that could be reserved for very long names, or something like that?

**Comment by mairaw** [comment]
Sorry @svick, I keep losing track of this one. If this is still an issue, can you please log an issue at https://github.com/microsoftdocs/feedback since this is something for the docs engineering team to look at?
