### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/docs#19047]
I just tried to walk through this tutorial, and stumbled across **many** issues. 

1. The MyGet feed for one of the packages changed, so restore failed. The `Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest` package is now on  https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json instead of  https://dotnet.myget.org/F/roslyn/api/v3/index.json
2. The `AssemblyName` of the VSIX MakeConst.Vsix project is the same as the MakeConst project, which causes you to run into [this](https://github.com/NuGet/Home/issues/5621) issue.
3. The using statement on line 9 in the MakeConstUnitTest.cs file is incorrect and should be removed.
4. The sample tells you to call the `VerifyCSharpCodeFix` overload method, but doesn't tell you to create a base class that implements this method and then have your unit test derive from it.

The actual sample is located [here](https://github.com/dotnet/samples/blob/master/csharp/roslyn-sdk/Tutorials/MakeConst).

Here is a GitHub project that is the output of the new analyzer project that highlights all these issues: https://github.com/MadEste/MkConst

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MCCshreyas** [comment]
Yes, I am facing the same issue. I don't know when it gets fixed. 
@stevenbrix do you have the correct project that at least builds and run? because I need to create a sample analyzer but I am not able to do that because of these errors.

**Comment by stevenbrix** [comment]
@MCCshreyas the tutorial on GitHub has been updated: https://github.com/dotnet/samples/blob/master/csharp/roslyn-sdk/Tutorials/MakeConst

You can use that and everything should work

**Comment by MCCshreyas** [comment]
@stevenbrix Thanks. I will give a try with 16.7.
