### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by yaserbalaghi** [dotnet/docs#19045]
hi,
Is this sentence correct?
"Without creating unit tests for the code that you're writing, coupling may be less apparent."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Yes I believe it's correct. Usually, a tightly-coupled software is hard to test. So, attempting to write unit tests and finding any difficulty could be because of a tightly-coupled software. Without writing unit tests.

**Comment by yaserbalaghi** [comment]
> 
> 
> Yes I believe it's correct. Usually, a tightly-coupled software is hard to test. So, attempting to write unit tests and finding any difficulty could be because of a tightly-coupled software. Without writing unit tests, you might not notice that your software is tightly-coupled.

That's right. Thankful
