### ISSUE TITLE
Type parameters of methods are not described

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1905]
The documentation for generic methods does not seem to document their type parameters. For example, consider [`ExpressionVisitor.VisitAndConvert<T>(ReadOnlyCollection<T>, String)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressionvisitor.visitandconvert--1?view=netframework-4.7#System_Linq_Expressions_ExpressionVisitor_VisitAndConvert__1_System_Collections_ObjectModel_ReadOnlyCollection___0__System_String_). Its type parameter is [documented in the XML source](https://github.com/dotnet/docs/blob/b53b8ac/xml/System.Linq.Expressions/ExpressionVisitor.xml#L202) as:

```xml
<typeparam name="T">The type of the expression.</typeparam>
```

But this information is not shown on the API reference page for this method.

**Comment by mairaw** [comment]
Filed internal bug to track this: #980590

**Comment by mairaw** [comment]
They've added type parameters now. Closing this one. Thanks @svick!
