### ISSUE TITLE
TODO: WRITE SPEC : Missing specs for local functions

### ISSUE THREAD

**Issue by nishants** [dotnet/docs#19065]
There is a TODO items here `TODO: WRITE SPEC`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db893c0c-bc6f-93b5-752d-ca0c96a20fa9
* Version Independent ID: 084f20f8-439a-0b96-57dd-b33d8a33ba24
* Content: [Local functions - C# 7.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/local-functions)
* Content Source: [proposals/csharp-7.0/local-functions.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @nishants 

We're working with the ECMA committee to get these updated.

**Comment by BillWagner** [comment]
I'm going to close this.  PR dotnet/csharpstandard#104 will address it.

Moving this issue to csharpstandard won't provide value. This change is already on the list.
