### ISSUE TITLE
The language combobox shouldn't be shown if it doesn't do anything

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1906]
In API reference, it seems the combobox to choose between C#, VB and C++ is always shown, but doesn't seem to do anything.

If there are pages where the combobox works, it should be shown only on those pages, but nowhere else.

**Comment by svick** [comment]
It looks like the combobox does switch the language used in examples, but not in definition. Is that how it should behave?

**Comment by mairaw** [comment]
For now, we only support the C# definition, so that's why the definition language is not changed when you select a different language. Support for other languages in the definition is coming on a later date.

/cc @dend

**Comment by mairaw** [comment]
I'll close this since we've added the syntax for the other languages since then. I also just opened a related feedback re. the version selector on microsoftdocs/feedback:
https://github.com/MicrosoftDocs/feedback/issues/927
