### ISSUE TITLE
Wrong wording in example of * quantifier

### ISSUE THREAD

**Issue by jsilverm** [dotnet/docs#19075]
I checked carefully, this is the only instance of this mistake on this page:
"The following example illustrates this regular expression. Of the nine digits in the input string, five match the pattern and four (95, 929, 9219, and 9919) do not."

There are way more than nine digits in the input string.  The best word to use instead of 'digits' here is 'numbers', 'decimal integers' would be used by Vulcans and OCD programmers.  'Groups of digits' would also be correct but awkward and unusual.  The word "digit" is consistently used to mean one single decimal digit 0 to 9 everywhere else on this page.  One of the most common hallmarks of bad programming documentation is confusion of "digit" and "decimal integer literal" -- very rarely seen on these pages (except in this one spot).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254044f-fe8a-ff27-8e5e-4d01e5c4e58a
* Version Independent ID: a1d9ffdc-d888-68cb-ac05-dd5018c89c9c
* Content: [Quantifiers in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions)
* Content Source: [docs/standard/base-types/quantifiers-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/quantifiers-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@jsilverm Great points! What about

> Of the nine number groups in the input string, five match ...

**Comment by jsilverm** [comment]
That could be fine.  I came from an EE/CS background where we took pains to
never confuse numbers and component digits, so we would always use "number"
for each quantity and digit (or numeral but usually digit) for the two
concepts.  In contexts where hexadecimal, decimal and binary or octal were
all flying around, we would specify what kind of number or digit, but when
everything is decimal, just number and digit was fine.

For a mixed audience, probably "number groups" is the best choice to use in
that sentence.

**Comment by adegeo** [comment]
Reading some more descriptions on regex I think digit groups is more appropriate. If that is they way the items are referenced in regex, we should carry that same terminology over where it makes sense and doesn't detract from the concept. What about

> Of the nine regex-digit groups in the input string, five match ...

**Comment by jsilverm** [comment]
I rarely have ever used the full phrase "regex-digit groups", but am not
opposed to it.

I think extremely few people would be confused by "digit groups" by itself.

It is probably better than simply using the word "number" and shorter and
less pedantic than the phrase "decimal integer" (adding constant or literal
if found in source) which are the terms I have used since I was a kid,
former when everything was in decimal, the latter when there was hex, octal
or binary floating around in the mix.  I do think the original wording was
on the order of a typo, based on the phrasings found on the rest of that
page.  There are many who confuse the terms digit and number, but they
didn't write that page.

**Comment by adegeo** [comment]
Ok "digit group" sounds like the winner here. 😄
