### ISSUE TITLE
The .NET 3.5 Framework install directions are incorrect

### ISSUE THREAD

**Issue by patricktokeeffe** [dotnet/docs#19084]
This article has several problems. 

The section titled ***Enable the .NET Framework 3.5 in Control Panel*** contains the following instructions:

> 1. Press the Windows key Screenshot of the Windows key logo. on your keyboard, type "Windows Features", and press Enter. The Turn Windows features on or off dialog box appears.
> 2. Select the .NET Framework 3.5 (includes .NET 2.0 and 3.0) check box, select OK, and reboot your computer if prompted.

Neither of these steps involve the control panel. Why is "control panel" in the title if the control panel is not involved?

In fact, it is not possible to access the dialog shown in this article using the Windows Control Panel. There *is* a control panel link to "enable optional windows features" but that link does *not* open Windows Features and does *not* allow users to select optional components for installation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install .NET Framework 3.5 on Windows 10, 8.1, 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @patricktokeeffe - I'm not so sure... In fact, I was just able to do this following these very instructions on Windows 10.

![2020-06-24_14-09-50](https://user-images.githubusercontent.com/7679720/85617201-7e2a4a00-b624-11ea-9da8-41a76e49385f.gif)
