### ISSUE TITLE
Code comments still reference "phantom" greeting property

### ISSUE THREAD

**Issue by gzak** [dotnet/docs#19085]
This is likely the result of updating the example code in the document without also updating the code comments. It looks like the old property was "optionalGreeting" or "greeting" instead of "detailedDescription" or "details".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c4bf74-8064-6c45-d5c8-2bbdb0113895
* Version Independent ID: 3250ed35-9410-87f6-ba3e-258c85fbc7f1
* Content: [Nullable reference types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I see you've already fixed that in your branch. You can submit a PR with that branch to this repository.
