### ISSUE TITLE
System.Text.RegularExpressions.Regex link targets are incorrect

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#1909]
# System.Text.RegularExpressions.Regex link targets are incorrect

# General
Attempting to follow a link to any member of the Regex class appears to always lead to a single topic, [Regex.System.Runtime.Serialization.ISerializable.GetObjectData](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.system-runtime-serialization-iserializable-getobjectdata?view=netframework-4.7). This appears to happen regardless of the target platform, and also produces an unusual customer experience (large parts of the member list are highlighted in blue is the Light theme is used.

## Issues with Existing Topics

The issue arises by selecting any member from the [Regex class](https://docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.Regex?view=netframework-4.7) topic.   

## Related information
This issue was originally reported in PR #1899.
To address this issue, I've opened an internal bug #971397.

/cc @Banani-Rath @svick

**Comment by svick** [comment]
It's not just `Regex`, it affects many other types. And I'm pretty sure this wasn't an issue few hours ago (at least for `Regex`). Some more information is in my duplicate issue https://github.com/dotnet/docs/issues/1910.

**Comment by rpetrusha** [comment]
This issue has evidently been addressed; I can't repro this behavior for any of the types for which it was previously reported. Closing this issue.
