### ISSUE TITLE
TimeZoneInfo url is incorrect, points to the wrong document 

### ISSUE THREAD

**Issue by mduberstein** [dotnet/docs#1911]
## Issues with Existing Topics
Need to find help on TimeZoneInfo structure
https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.system-runtime-serialization-iserializable-getobjectdata?view=netframework-4.7

TimeZoneInfo.System.Runtime.Serialization.ISerializable.GetObjectData Method

is not TimeZoneInfo

**Comment by rpetrusha** [comment]
@mduberstein, thanks for opening this issue and reporting the problem with TimeZoneInfo. I've noted it in #1910, so I'm closing this issue.
