### ISSUE TITLE
Outdated tables/information

### ISSUE THREAD

**Issue by x10an14** [dotnet/docs#19196]
This table is now outdated (read: lacking information) with `dotnet 3.1` out and proclaimed as the recommended/LTS version.

Additionally, it would be nice if there could be some way from within PowerShell to specify/select which dotnet framework/version is utilized, so one can rely on the correct version of documentation.
A solution that is OS-agnostic (read: works on Linux/MacOS too, not just Windows - which all current solutions leveraging the Registry relies on).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Core Runtime and SDK are versioned - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/index.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @x10an14 - thank you for posting this issue. You're correct that this doc needs to updated. I'll make that happen.
