### ISSUE TITLE
Setting up local enviroment using Visual Studio

### ISSUE THREAD

**Issue by sgurukrupa** [dotnet/docs#19218]
Please include a link to the tutorial on setting up a local environment using Visual Studio: https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console. I am not referring to Visual Studio Code, here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @sgurukrupa 

I've added this to the wave of updates we'll make for .NET 5.
