### ISSUE TITLE
Misleading information about JSON

### ISSUE THREAD

**Issue by mindplay-dk** [dotnet/docs#19217]
Some of the information provided in [this section](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-all-characters) is misleading and wrong.

> Use the unsafe encoder only when it's known that the client will be interpreting the resulting payload as UTF-8 encoded JSON.

According to the [original JSON spec](https://www.json.org/json-en.html):

> A string *is* a sequence of zero or more Unicode characters

According to [RFC4627](https://www.ietf.org/rfc/rfc4627.txt), the standard for the `application/json` Media Type, section 3, on encoding:

> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8.

Note that it does not define the meaning of a `charset` option.

You also suggest using a `Content-Type: application/json; charset=utf-8` header, which is likely to cause more harm than good. Most clients and servers will ignore the `charset` parameter, but some frameworks aren't as error-tolerant and won't be able to parse this content-type and will [reject](https://stackoverflow.com/questions/9254891/what-does-content-type-application-json-charset-utf-8-really-mean) the request.

So encoding as anything other than Unicode in UTF-8 makes it non-valid JSON. Adding a non-standard `charset` option is misleading, as it might make someone think they can encode as JSON using other character sets or encodings, which is incorrect.

Encoding JSON correctly as Unicode in UTF-8 should have been the default - `UnsafeRelaxedJsonEscaping` isn't unsafe or relaxed, it's merely correct, and someone made a mistake (or ill-informed decision) when they designed this class.

You also highlight how "It doesn't escape HTML-sensitive characters" as a caution - this being a JSON-encoder, it shouldn't be doing anything related to HTML to begin with. That's is a concern for your view-layer, which might be responsible for injecting JSON into HTML - it's not a concern that has anything directly to do with JSON, and it definitely doesn't make sense as a default.

But since this feedback is about the documentation, I'd say there's no point in making matters worse by spreading incorrect information and misleading ideas about JSON.

It would be more honest and educational to explain in a highlighted warning box why the defaults might not make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-all-characters)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
We believe the recommendations here are appropriate given actual usage of JSON in real-world applications, including the frequent injection of JSON payloads into HTML response bodies.

**Comment by mindplay-dk** [comment]
I can't argue with your beliefs.

I believe you're creating unnecessary learning curve and complexity for inexperienced developers, making them learn things that aren't accurate, and then work harder to progressively unlearn with experience.

This feels dismissive and seems to ignore the problems created by enabling and condoning "actual usage of JSON" whether that happens to break or ignore the standards.

Just my opinion, but it's frustrating to see what this does to the progression of new developers.
