### ISSUE TITLE
messy

### ISSUE THREAD

**Issue by John-Blair** [dotnet/docs#19220]
messy - just show me stuff for web apps.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d476d66c-4f04-3742-cf90-4177aceb4138
* Version Independent ID: 482be47f-3dec-5470-5e83-88afd9c2bcca
* Content: [Retargeting Changes for Migration from .NET Framework 4.7.2 to 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.2-4.8)
* Content Source: [docs/framework/migration-guide/retargeting/4.7.2-4.8.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/retargeting/4.7.2-4.8.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks for letting us know. I've opened an [internal issue](https://portal.microsofticm.com/imp/v3/incidents/details/194060952/home) to get this addressed.

**Comment by adegeo** [comment]
Regarding web apps, I would look at the documentation for the specific web technology you're using, such as ASP.NET.
