### ISSUE TITLE
Unclear statement regarding redeploy or perhaps just application restart?

### ISSUE THREAD

**Issue by eriksendc** [dotnet/docs#19234]
Hi there,

The document https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net has a paragraph that at the time of my reading read as follows:

Machine learning models are not static. As new training data becomes available, the model is retrained and redeployed. One way to get the latest version of the model into your application is to redeploy the entire application. However, this introduces application downtime. The PredictionEnginePool service provides a mechanism to reload an updated model without taking your application down.

I'm curious, I get how using watchForChanges would allow the system to reload, but the statement "... is to redeploy the entire application." Wouldn't just a start and stop be sufficient, too? Redeploy to me (that word, redeploy) means a full-on deployment of a version of the application (copying files, e.g. "publish"). Restarting an application is a fairly trivial thing, and many applications restart themselves on a periodic basis to reload caches, etc. 

Anyways, I think that if restarting the application also reloads a new zip file that's copied into a production environment, I could see a production scenario where the web api (or web application) itself wouldn't be fully redeployed, just the zip file, and then an app restart would do the trick. If that's something that indeed would do the trick (which I do think it would) then I recommend reworking the paragraph to include that nuance. Some novice readers might not get that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dce49db-3548-7dad-bdb1-812efde7ac86
* Version Independent ID: 390a9c7a-2537-25ca-c041-0284c253acff
* Content: [Deploy a model in an ASP.NET Core Web API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Thanks for this feedback @eriksendc both of these scenarios (redeploy & restart) are valid and you're right, some distinction would be helpful.

**Comment by eriksendc** [comment]
I don't understand why this was closed for my lack of answering? I didn't understand if there was something I needed to answer. My original issue as documented stands.

**Comment by eriksendc** [comment]
If you have questions you want to ask for more information, I'm happy to help. But I (sort of strongly) believe the documentation is stating something incorrectly. In practice, in a real production situation, you do not need to republish an entire solution just to replace the model. You can replace just the model.zip file and restart the web application.

**Comment by luisquintanilla** [comment]
@eriksendc apologies for the confusion. The bot closed this automatically due to inactivity. This is already being tracked as a change that will be made. Thanks for reopening.
