### ISSUE TITLE
CS 

### ISSUE THREAD

**Issue by beidelberg** [dotnet/docs#19233]
A great getting started tutorial for ME's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=1)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @beidelberg 

Closing as kudos
