### ISSUE TITLE
mlnet cli --output-path changed to --output

### ISSUE THREAD

**Issue by voges316** [dotnet/docs#19235]
Using the latest mlnet cli tool, the documentation still references the previous option, --output-path, when it changed in 16.1.1 to --output.

Output path
--output-path | -o (string)

*should be*
Output path
--output | -o (string)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d546f09c-1e0f-b036-5c93-b0640934bcdd
* Version Independent ID: dcce0234-fb4b-9622-a930-80518e6f50a3
* Content: [ML.NET CLI Command Reference - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/reference/ml-net-cli-reference)
* Content Source: [docs/machine-learning/reference/ml-net-cli-reference.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/reference/ml-net-cli-reference.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @voges316 

Thanks for bringing this to our attention. I've made the updates and changes should be published shortly.
