### ISSUE TITLE
`MyMethod` should be `ProcessString`

### ISSUE THREAD

**Issue by toby5box** [dotnet/docs#19246]
> In the following example, the try block contains a call to the ProcessString method that may cause an exception. The catch clause contains the exception handler that just displays a message on the screen. When the throw statement is called from inside MyMethod

Looks like `MyMethod` should be `ProcessString`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch#exceptions-in-async-methods)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @toby5box I've opened #19256 to address this.

When you find these types of mistakes, you can click the "edit" button (it looks like a pencil) and propose the fix in a PR. That may take less time.

Thanks again.
