### ISSUE TITLE
Provide a code that uses Dependency Injection with MSTEST sample for DOTNET CORE

### ISSUE THREAD

**Issue by cilerler** [dotnet/docs#1925]
The samples provided in _MSTEST_ is extremely high level.  Common usage usually based on **Dependency Injection** and would like to see a full sample that covers it.

Reference https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md

**Comment by BillWagner** [comment]
@ghogen Should this move to your repository, covering MS Test in detail? We can provide links to any content that's already available there.

**Comment by ghogen** [comment]
@erickson-doug @alexhomer1 As the owners of test scenarios for VS, what do you think about where the MS Test content should go?

**Comment by IEvangelist** [comment]
This is covered... closing
