### ISSUE TITLE
Issue with Binding.ValidationRules wpf

### ISSUE THREAD

**Issue by rbkern99** [dotnet/docs#19255]
This page has an example
<TextBox Name="StartDateEntryForm" Grid.Row="3"
         Validation.ErrorTemplate="{StaticResource validationTemplate}" 
         Style="{StaticResource textStyleTextBox}" Margin="8,5,0,5" Grid.ColumnSpan="2">
    <TextBox.Text>
        <Binding Path="StartDate" UpdateSourceTrigger="PropertyChanged" 
                 Converter="{StaticResource dateConverter}" >
            <Binding.ValidationRules>
                <src:FutureDateRule />
            </Binding.ValidationRules>
        </Binding>
    </TextBox.Text>
</TextBox>

But what does src:   namespace refer to ? When I use the name space of my application, where the validation rule class lives, app will not compile:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'CashReportFoundByDateRule' does not exist in XML namespace 'clr-namespace:Restsys;assembly=RestsysWin'. Line 158 Position 46.	RestsysWin	C:\projects\Restsys\RestsysUI\MainWindow.xaml	158	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data binding overview - WPF](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/data/data-binding-overview)
* Content Source: [docs/desktop-wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/desktop-wpf/data/data-binding-overview.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
`src` would refer to the namespace that the `AuctionItem` type exists in.

If this doesn't answer your question please feel free to reopen it.
