### ISSUE TITLE
Additional step needed for spark to work

### ISSUE THREAD

**Issue by gopala000** [dotnet/docs#19250]
I had to do below steps to make `spark-submit --version` smoke test to work:

Add environment variable: JAVA_HOME=C:\Program Files\Java\jdk1.8.0_251
Add to Path env variable:  C:\Program Files\Java\jdk1.8.0_251\bin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @gopala000,

Thank you for your feedback. We're in the process of updating this document as part of PR #20264 . We'll make sure to add this feedback as part of the updates.

**Comment by luisquintanilla** [comment]
Hi @gopala000 I was unable to replicate this while making updates as part of #20264. Closing this issue for now. Please feel free to open another issue if you run into any additional problems.
