### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by HadyAllam** [dotnet/docs#19263]
[Enter feedback here]
The document is good but i noticed a spelling mistake at the beginning of the article. first sentence said "**There are numerous benefits to writing unit tests**". i think it should be "**There are numerous benefits to write unit tests**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @HadyAllam - thank you for posting this issue, however; this is proper English and the sentence structure is correct. I'm going to close this issue, but if you find anything else - by all means please open an issue. 

Thank you
