### ISSUE TITLE
Follow-up fixes

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#19264]
https://github.com/dotnet/docs/pull/18575#discussion_r429460593
#19260 https://github.com/dotnet/docs/pull/19260/commits/b79764ba3e15c3c65e74fe14adb6f2e74b2c8248

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 442d453e-38dd-ed79-741c-813429a41822
* Version Independent ID: 5f1f64a1-9d23-0010-b505-d3874041f8f2
* Content: [Get started with syntax transformation (Roslyn APIs)](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-transformation)
* Content Source: [docs/csharp/roslyn-sdk/get-started/syntax-transformation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/get-started/syntax-transformation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @NextTurn - I believe that this can be closed now, right?

**Comment by NextTurn** [comment]
No no, see the first code block in https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/get-started/syntax-transformation#create-nodes-with-factory-methods.

**Comment by IEvangelist** [comment]
> No no, see the first code block in https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/get-started/syntax-transformation#create-nodes-with-factory-methods.

Ah, yes. Ok, I'll fix that now. Thank you
