### ISSUE TITLE
Unclear how to get the book

### ISSUE THREAD

**Issue by Tomkaa** [dotnet/docs#19291]
It's not made entirely clear in the doc how to obtain this book. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89573850-fe00-e1a3-de51-57394b3ac131
* Version Independent ID: e5b1affd-a12a-bacb-f510-9abb242be819
* Content: [Architecting Cloud Native .NET Applications for Azure](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/)
* Content Source: [docs/architecture/cloud-native/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/index.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by ardalis** [comment]
The book is available online in the docs, or as a downloadable PDF. I assume you're saying it's hard to locate a download link for the PDF (since it appears you got here from the book's docs URL)?

**Comment by ardalis** [comment]
FYI, you can find the link to download here:
https://dotnet.microsoft.com/learn/azure/architecture
and the direct link is here:
https://dotnet.microsoft.com/download/e-book/cloud-native-azure/pdf

but I agree this should be linked from the docs page as well.

**Comment by IEvangelist** [comment]
Hi @Tomkaa - thank you for posting this issue. I see what you're saying, perhaps we could include a link on the index page to the downloadable PDF version, in case consumers want it that way? I've updated this issue by labeling it as "up-for-grabs", by all means please feel free to create a pull request to add the link.

Thank you

**Comment by Tomkaa** [comment]
> The book is available online in the docs, or as a downloadable PDF. I assume you're saying it's hard to locate a download link for the PDF (since it appears you got here from the book's docs URL)?

Yes, that exactly what I meant. Download link for the PDF from index page would be a very nice improvement.
