### ISSUE TITLE
running into access denied problem

### ISSUE THREAD

**Issue by ps2cheung** [dotnet/docs#19302]
[Enter feedback here]

Hi,
when I follow the instruction I got access denied problem
PS C:\Users\icheung\Desktop\azure_training\AZ204\docker\docker-working\App> dotnet run
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

If I don't use -n NetCore.Docker
I was able to run dotnet run successfully
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/build-container.md)
* Product: **dotnet-core**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @ps2cheung
Thank you so much for posting this issue. We really appreciate it. Were you running the PS instance as an admin? I'm not sure why this would have happened without addition context. I'll keep an eye on this issue and watch to see if others experience it too.

**Comment by ps2cheung** [comment]
Hi,
I am running PS as admin, what is strange is only when -n NetCore.Docker I have this problem, can you reproduce this issue on your side.
Thanks
Ivan

**Comment by IEvangelist** [comment]
> Hi,
> I am running PS as admin, what is strange is only when -n NetCore.Docker I have this problem, can you reproduce this issue on your side.
> Thanks
> Ivan

I'm unable to reproduce this issue. When I follow the instructions, even without my PS instance running as Admin - it still works.

**Comment by ps2cheung** [comment]
don't worry I swap to a new machine and don't have this issue anymore.
