### ISSUE TITLE
French Blazor documentation "éblouissant"

### ISSUE THREAD

**Issue by vintzl** [dotnet/docs#19309]
There are still pages in the French documentation that says "éblouissant" instead of Blazor (again, for instance, the Italian documentation does not have this problem).

- https://docs.microsoft.com/fr-fr/dotnet/architecture/blazor-for-web-forms-developers/introduction
- https://docs.microsoft.com/fr-fr/dotnet/architecture/blazor-for-web-forms-developers/project-structure

**Comment by Youssef1313** [comment]
@JasonCard, Do you think the no-loc extension should be used? or there is something to be done in the localization system to always completely prevent "Blazor" from being localized? I think it might be tedious and noisy to add Blazor to no-loc everywhere.

**Comment by JasonCard** [comment]
@Youssef1313 Yes, I'd recommend to use the [no-loc custom metadata](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings). for "Blazor" to resolve this issue. That's currently the best way to avoid over-localization of terms.
