### ISSUE TITLE
Please indicate where this file should be located

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#19301]
Hi,

I'm in a situation where I have .NET Native toolchain complain, and I have to make use of the _.rd.xml_ file. 
Though from the doc it's not clear where this file should be added to and how to make it recognizable.

Please update the docs to include this information.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137b4e5b-5a0d-938c-68be-9c11a06b4481
* Version Independent ID: 31ceb2b9-dfac-b233-d1cb-2aebe287bcfd
* Content: [Runtime Directives (rd.xml) Configuration File Reference](https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference)
* Content Source: [docs/framework/net-native/runtime-directives-rd-xml-configuration-file-reference.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/runtime-directives-rd-xml-configuration-file-reference.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by weitzhandler** [comment]
Found my answer [here](https://dotnet.github.io/native/troubleshooter/method.html), but anyway, I think it's worth including in the referenced docs page.

> Runtime Directives provide a way for you to describe what types and members your app needs to have available for reflection purposes. The directives are kept in an XML file with an RD.XML extension that is part of your application package. A default RD.XML file is added to all new universal app projects - look for it in the Properties node (My Project node for Visual Basic) of the Solution Explorer. You can add new runtime directives to it when needed.
> 
> If you're a library author that needs to describe the use of reflection within the library, you can embed a Runtime Directives files in your library. Simply add a file with an RD.XML extension to your library project, right-click the file in the Solution Explorer window and select Properties. Set the Build Action property to Embedded Resource and you're good to go.
> 
> To learn more about the RD.XML syntax, see RD.XML Reference.
> 
> Runtime Directive builder tool
> The builder below will help you create a directive that will solve the MissingMetadataException you're facing. Use the information in the MissingMetadataException message along with your knowledge of the code that hit the exception to pick the right answers. If the MissingMetadataException message doesn't have helpful information, make sure to rebuild in Debug mode with .NET Native optimization enabled.

![image](https://user-images.githubusercontent.com/2716316/86426891-843dbc00-bcf1-11ea-9a97-2101e7ff95f8.png)

**Comment by BartoszKlonowski** [comment]
I'll work on this.

**Comment by BartoszKlonowski** [comment]
@gewarren @BillWagner I believe that this issue is now outdated, as the original source of that page is no longer part of [dotnet/docs](https://github.com/dotnet/docs) repository, but [MicrosoftDocs/windows-dev-docs](https://github.com/MicrosoftDocs/windows-dev-docs). Of course I also can't find this text anywhere in the current repository so no way to actually modify it.
Can we close the issue and ask @weitzhandler to reopen it in windows-dev-docs where the text is now?

**Comment by gewarren** [comment]
@stevewhims Can you transfer this issue to MicrosoftDocs/windows-dev-docs? I don't seem to have permissions.

**Comment by stevewhims** [comment]
Hi, @weitzhandler, and thanks for filing this issue! I've published a fix to the topic just now.

For leaving feedback about a specific topic, as in this case, please scroll to the bottom of the topic and click **Submit and view feedback for** \> **This page**. That will cause the issue to be routed appropriately, and folks will have the right perms.

I don't have perms to close this issue, but it's now resolved. Perhaps somebody else could close it.

Thanks! :)
-Steve
