### ISSUE TITLE
Wrong Link?

### ISSUE THREAD

**Issue by RamblingGeekUK** [dotnet/docs#19310]
The Link at the bottom goes to the Mac version of the walk though... a bit jarring to say the least  😊

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6feb46a5-46de-a4ec-3549-3d4df790de03
* Version Independent ID: 5851a635-12ab-af94-2139-f217a63fd36a
* Content: [Publish a .NET Core console application using Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio-code)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/publishing-with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that!
