### ISSUE TITLE
My Issue

### ISSUE THREAD

**Issue by estiak001** [dotnet/docs#19311]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d03435-cc6c-1123-a86c-d5c3eacc24bd
* Version Independent ID: 460afd2b-383d-7b90-6804-4b900c3bc9b2
* Content: [Tutorial: Forecast bike rental demand - time series - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting)
* Content Source: [docs/machine-learning/tutorials/time-series-demand-forecasting.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/time-series-demand-forecasting.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @estiak001,

Is there any specific feedback / issues that you ran into? I don't see anything in the description. Can you please comment on the issue you ran into with this document (if any)?

**Comment by luisquintanilla** [comment]
Closing this issue due to no response. @estiak001 please feel free to open another issue if you are still running into issues with this document.
