### ISSUE TITLE
EF Core <auto-generated > tag

### ISSUE THREAD

**Issue by leotsarev** [dotnet/docs#19329]
EF Core outputs tag &lt;auto-generated />
https://github.com/dotnet/efcore/blob/97f8f51d8796eb61e5109a816574685d7f4f6269/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs#L131

However, it's not documented here.
That's a not-standard  tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
It starts with double slashes not triple, so I suspect it's just a normal comment.

**Comment by BillWagner** [comment]
Tag @JeremyLikness for confirmation.

**Comment by sharwell** [comment]
> It starts with double slashes not triple, so I suspect it's just a normal comment.

This is correct. The comment is recognized by code analysis tools so code style analysis will not be applied for the file (users would not be able to correct style violations because it is not a hand-edited file).

**Comment by leotsarev** [comment]
Thanks!

**Comment by BillWagner** [comment]
closing as an answered question.
