### ISSUE TITLE
Link that should be to an enum field is to the enum instead

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1932]
It seems that during API reference migration, some links to enum fields were changed to links to the enum type itself.

For example, compare the documentation for `MethodBase.Invoke(Object, Object[])` [on MSDN](https://msdn.microsoft.com/en-us/library/a89hcwhh(v=vs.110).aspx#Remarks), which talks about the `BindingFlags.Default` field as "Default":

![](https://cloud.githubusercontent.com/assets/287848/25103986/ed4bb42e-23be-11e7-9d73-f6ed0c3be83c.png)

While [docs.ms](https://docs.microsoft.com/en-us/dotnet/api/System.Reflection.MethodBase.Invoke?view=netframework-4.7#System_Reflection_MethodBase_Invoke_System_Object_System_Object___) talks about "BindingFlags" instead:

![](https://cloud.githubusercontent.com/assets/287848/25103514/27999b7a-23bd-11e7-8901-8cb711544868.png)

This is an issue with [the source](https://github.com/dotnet/docs/blob/17edc15/xml/System.Reflection/MethodBase.xml#L654), it does not contain any mention of `Default`.

The same issue happens again on the page with `ReflectionPermissionFlag`. Though `BindingFlags.Default` in parameters of the `MethodBase.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)` overload is fine.

**Comment by mairaw** [comment]
This seems to be an issue with the migration logic. The original was a link to F:System.Reflection.BindingFlags.Default, so the resulting migrated link should include the field name in the xref link. 

The content in the parameter section is a different migration code/format so that's probably why that one is working. I've opened an internal bug to keep track of this issue (#976235).

**Comment by mairaw** [comment]
Adding a new repro that used to have 25 links to enum fields before migration:
https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/wpf-windows-overview.md

@yishengjin1413 is working on a data fix for us
