### ISSUE TITLE
Core 3.1 SCD deploy to Linux

### ISSUE THREAD

**Issue by jdarundell** [dotnet/docs#19328]
Great

I follow the example and get a heap of files - not just in the folder but also in  .\publish and in .linux-x64 

I copy them to my Linux machine - how do I run the app??

I can run the exe in Windows explorer if I browse to it from windows . How do I run it in linux console ?

Most of us are new to installing Core apps on Linux - It can't just be me!!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [Deploy .NET Core apps with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Linux apps don't use extensions. So there should be an extension-less file with the same name as the project, that is the file you run on a linux/macos machine.
