### ISSUE TITLE
Potential missing detail

### ISSUE THREAD

**Issue by deliverystack** [dotnet/docs#19323]
Hello,

Parallel.Foreach documentation could discuss the issue of captured variables in a loop - whether each iteration gets its own variables or if the developer has any concerns about sharing. From the code example, it appears that the developer need not create their own copy of currentFile within the loop.

https://stackoverflow.com/questions/271440/captured-variable-in-a-loop-in-c-sharp

Best regards.

   -John

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25dcc671-50d5-032b-735c-2ac9b6a21338
* Version Independent ID: c70450e1-1006-7478-fcca-45c8bfbe2c09
* Content: [Write a simple parallel program using Parallel.ForEach](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop?redirectedfrom=MSDN)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @deliverystack - thank you for posting this issue. I appreciate the feedback on this.

As it pertains to closures, within the context of a `Parellel.ForEach` the collection being iterated over is provided as an argument to the lambda of the action. Thus, `currentFile` is the current file for that `body` execution, and is unique to the a single ordinal within the collection that is being iterated on. I could add a note mentioning closures, and the potential for variable sharing concerns. I'll have to think about how to do this without adding confusion. Thank you

**Comment by deliverystack** [comment]
I think it is worth adding this detail, not just to confirm my assumption, but to make more developers aware of the issue with for/for loops and lambdas. I had been coding .NET for about 20 years before this hit me (only recently started using lambdas and threading) and I have no idea how many bugs I may have introduced as a result. I understand that C# 5.0 addresses this issue (for for or foreach but I think not both?), but I think we should work on raising awareness, and this would be just one more pointer to some critical information that, without knowledge, can really cause problems that are difficult to diagnose.

Thanks for considering my suggestion and confirming my assumption! I guess it all might be obvious to a better coder.

   -John
