### ISSUE TITLE
Edit instructions

### ISSUE THREAD

**Issue by FunBobby1956** [dotnet/docs#19324]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-ca/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

Change "Add the following code to the line right above the Main method to specify those paths and the other variables:" to "Add the following code to the line directly above the Main method to specify those paths and the other variables:"

**Comment by luisquintanilla** [comment]
Hi @FunBobby1956 

Thanks for your suggestion. The updates should be published shortly.
