### ISSUE TITLE
png images

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19322]
The images in png format in this article are hard to see in dark and high contrast modes.
I think this issue can be kept open to review all png images, not just ones in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Not sure if it's possible, but would be good if the PR build flags a warning if the PR adds a png image.

**Comment by erjain** [comment]
Hi @ardalis, can you take care of this?

**Comment by ardalis** [comment]
The specific issue is with transparency in PNG files. If there's a way to detect that during PRs I would certainly be in favor of it. I'll update the 2 images that currently use transparent backgrounds so they use white instead, which will fix this issue. If someone wants to create another issue to track the idea of checking PNG transparency as part of the PR process, that would good (I wouldn't tie it to this issue).
