### ISSUE TITLE
Remove alert note in "Tutorial: Write your first analyzer and code fix"

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#19332]
Remove alert note in [**Tutorial: Write your first analyzer and code fix**](https://docs.microsoft.com/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix), when the Visual Studio 2019 version to fix the template bug is released.

Alert note was added in #19333

Related to:
https://github.com/dotnet/roslyn-sdk/issues/514
https://github.com/dotnet/roslyn-sdk/pull/531

**Comment by Youssef1313** [comment]
After 16.7 is released, I think the information would still be useful for developers who didn't update to latest versions. The note might just get updated from:

> The current Visual Studio template has a known bug in it and should be fixed in Visual Studio 2019 version 16.7. The templates will not compile unless the following changes are made:

to

> If you are using a version older than Visual Studio 2019 version 16.7. The template will not compile unless the following changes are made:

**Comment by IEvangelist** [comment]
Closed in #20070
