### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by AntonNalyvaiko** [dotnet/docs#19348]
Please, fix typo error, replace Single Spectrum Analysis(SSA) with Singular Spectrum Analysis(SSA)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d03435-cc6c-1123-a86c-d5c3eacc24bd
* Version Independent ID: 460afd2b-383d-7b90-6804-4b900c3bc9b2
* Content: [Tutorial: Forecast bike rental demand - time series - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting)
* Content Source: [docs/machine-learning/tutorials/time-series-demand-forecasting.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/time-series-demand-forecasting.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Thanks for raising this issue @AntonNalyvaiko . Changes will be published shortly.
