### ISSUE TITLE
Needs an example of when the ContinueWith lambda itself is asynchronous (returns a Task)

### ISSUE THREAD

**Issue by wizofaus** [dotnet/docs#19341]
If the continuationFunction parameter to ContinueWith is an asynchronous function (returning as Task), it's necessary to call .Unwrap() on the Task returned by ContinueWith, which isn't obvious from these examples.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be073b14-6d0b-60be-7dff-4674bcb6c674
* Version Independent ID: a5fa3e78-73de-3360-1253-00545a2b4ef2
* Content: [Chaining Tasks by Using Continuation Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks)
* Content Source: [docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @wizofaus
Thank you so much for posting this issue. We really appreciate it. I'll try to incorporate this into the article as an example.
