### ISSUE TITLE
Issues with enum pages in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1934]
Looking at [the API reference page for the `BindingFlags` enum](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.bindingflags?view=netframework-4.7), I have noticed two issues:

1. The list of fields is at the very bottom of the page, after examples and remarks. This might make sense for classes, but I think it's not appropriate for enums, where the list of fields and their meaning is usually the first thing I'm looking for. I think that for enums, the list of fields should be at the top of the page, right after the definition section.
2. Each field has its own page, which is linked from the TOC, but not from the body of the article itself. This page seems to duplicate the information in the fields section of the type. I don't think those pages should exist.

**Comment by mairaw** [comment]
I agree with you @svick. I've opened an internal issue to track this.

**Comment by mairaw** [comment]
This has now been resolved. Thanks again @svick!
