### ISSUE TITLE
.NET doc is not vendor neutral enough

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/docs#19346]
.NET doc is not vendor neutral enough because it is hosted at a vendor web site, docs.microsoft.com .
If .NET Foundation hosts .NET doc, it will be more vendor neutral.

**Comment by BillWagner** [comment]
That is an interesting suggestion for the long term @aaabbbcccddd00001111 

At this time, it's not practical for the .NET Foundation to host all the .NET docs. Any plan for that would be some time in the future.

Closing at this time.
