### ISSUE TITLE
Excelent

### ISSUE THREAD

**Issue by cexita** [dotnet/docs#19359]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Data collections - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=4)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @cexita. I'm glad this worked for you.

Closing as `kudos`
