### ISSUE TITLE
API reference pages for operators need special handling

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1935]
It seems that in API reference, operators are treated as if they were methods with names like `op_Addition`. That is how they are represented in IL, but not in C# and it's not how most users understand them.

For example, [the page for the addition operator on `decimal` on docs.ms](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.op_addition?view=netframework-4.7):

* is called "op_Addition" in title and TOC
* has definition shown incorrectly as:

   ```c#
   public static decimal op_Addition (decimal d1, decimal d2);
   ```

Whereas [the same page on MSDN](https://msdn.microsoft.com/en-us/library/system.decimal.op_greaterthanorequal(v=vs.110).aspx):

* is called Addition Operator
* has definition shown correctly as:

   ```c#
   public static decimal operator +(
           decimal d1,
           decimal d2
   )
   ```

**Comment by mairaw** [comment]
Opened internal bug #980586 to track this 

/cc @dend @DuncanmaMSFT @adkinn

**Comment by svick** [comment]
It seems this is better now, but still not completely fixed:

* The operator is now called "Addition" in title and TOC, so that's fixed.
* The definition keeps using `op_Addition`, so that's not fixed.

**Comment by mairaw** [comment]
This has been resolved @svick. Can you check? Thanks!

**Comment by mairaw** [comment]
I'm closing this one @svick . Let me know if this is not resolved for you and we can reopen this. Thanks for reporting this!
