### ISSUE TITLE
 ML.NET Model Builder - Issue Classification scenario does not exist among the templates

### ISSUE THREAD

**Issue by vikramhn** [dotnet/docs#19366]
[Enter feedback here]
i downloaded ML.NET Model Builder  from https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder and installed  with Visual studio 2019. Trying to follow the steps described. Issue Classification scenario does not exist among the templates.
see [here](https://ibb.co/tXjN05G)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7fff31d-9b11-e1f1-f4c1-d798a7d9b564
* Version Independent ID: 8c94de21-2cc2-fb08-314d-6a62af1f0421
* Content: [Tutorial: Classify health violations with Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/health-violation-classification-model-builder)
* Content Source: [docs/machine-learning/tutorials/health-violation-classification-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/health-violation-classification-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @vikramhn 

Sorry to hear you had trouble with this tutorial. We're in the process of updating our documentation to the latest version of Model Builder. In the meantime, you can try selecting the **Text Classification** scenario in the current UI. The rest of the steps should be similar.

![image](https://user-images.githubusercontent.com/46974588/86930526-22bc8980-c105-11ea-857b-fe889e03666b.png)

**Comment by vikramhn** [comment]
Thank you @luisquintanilla.
