### ISSUE TITLE
HTML Encoding gone bad.

### ISSUE THREAD

**Issue by jessehouwing** [dotnet/docs#19362]
Some XML/HTML seems to be stripped out because of missing encoded characters:

> The impact of this change on .ZIP files that are decompressed on the Windows operating system by APIs in the .NET Framework System.IO namespace should be minimal, since these APIs can seamlessly handle either a forward slash ("/") or a backslash **("")** as the path separator character.
If this change is undesirable, you can opt out of it by adding a configuration setting to the **< section** of your application configuration file. The following example shows both the <runtime> section and the Switch.System.IO.Compression.ZipFile.UseBackslash opt-out switch:

> If this change breaks communication with an existing server, you can disable sending the SCH_SEND_AUX_RECORD flag and restore the previous behavior of not splitting data into separate records by adding the following switch to the **< element in the < section** of your app configuration file:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6244a293-43f8-82ba-b7c9-aa85af3a4b15
* Version Independent ID: 95061aef-1917-4a1e-06c4-3d6b2d84dfd2
* Content: [Retargeting Changes for Migration from .NET Framework 4.5.2 to 4.7](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.2-4.7)
* Content Source: [docs/framework/migration-guide/retargeting/4.5.2-4.7.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/retargeting/4.5.2-4.7.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
Assuming you're talking about the link with text being "<" only, this should get fixed by #19364.
