### ISSUE TITLE
Missing argument --version

### ISSUE THREAD

**Issue by ThomasPiskol** [dotnet/docs#19368]
`dotnet tool update` supports also the `--version` argument.

See also [this comment](https://github.com/dotnet/cli/pull/10205#issuecomment-506847148).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8171f4-8466-98ed-acb8-49563b864d16
* Version Independent ID: a1b7af2d-e2ba-bc4b-4d35-a8edbaa1249f
* Content: [dotnet tool update command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-update)
* Content Source: [docs/core/tools/dotnet-tool-update.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-update.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
There are other options that seem to be missing from the article:

- `--local                   Update the tool and the local tool manifest.`
- `--version <VERSION>       The version range of the tool package to update to.`
- `--tool-manifest <PATH>    Path to the manifest file.`
- `--disable-parallel        Prevent restoring multiple projects in parallel.`
- `--ignore-failed-sources   Treat package source failures as warnings.`
- `--no-cache                Do not cache packages and http requests.`
- `--interactive             Allows the command to stop and wait for user input or action (for example to complete authentication).`
