### ISSUE TITLE
Document customizing MSI install location

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#19371]
With 3.1 (possibly 3.0) you can use a command line `dotnet-sdk-3.1.301-win-x64.exe DOTNETHOME_X64="F:\dotnet\x64" DOTNETHOME_X86="F:\dotnet\x86"` to install to a different location.

Related to dotnet/core#4819

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#download-and-manually-install)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Spiralis** [comment]
I don't think this is working any longer, is that correct? I just tried and it installed to `C:\Program Files\dotnet`
