### ISSUE TITLE
Additional Resource

### ISSUE THREAD

**Issue by krchome** [dotnet/docs#19378]
[Enter feedback here]
https://youtu.be/LfLFiAw7d28

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Hello. Thank you for the suggestion. I don't believe we're currently promoting community videos through the documentation. Sorry about that. However, if users view the closed issues on this article here in github, they will find your link. I'm going to closet his. Cheers!
