### ISSUE TITLE
Supported Windows versions are not clear

### ISSUE THREAD

**Issue by mthalman** [dotnet/docs#19384]
There are discrepancies around which versions of Windows are supported for .NET Core.  For example, for 3.1, the "Supported releases" section implies that .NET Core is only supported on Windows 10, version 1809+.  But then the "Dependencies" section says that it can be installed on things like Windows 8.1, Windows 10 (version 1609+), and Windows Server 2008 R2.  These discrepancies need to be resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hrmmm yes I think I do have some issues there, thank you for spotting that. Notes:

- Clarify with product group which versions of Windows are supported.
- Add other Windows versions to the initial list
- Correct initial list regarding which [version of Win10 are supported per release](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md) (current table used [EOL dates](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet) to determine supportability but that may be an incorrect assumption)
  For example, Windows 10 1703 was end of support on 2019-10-08 and .NET Core 3.1 was released 2019-12-03, so why is 1604 listed as the minimum? Wouldn't 1709 be the current minimum?

**Comment by leecow** [comment]
As long as a 1607 container image is offered, that will be our min for 2.1, 3.1 and 5.0. I've added notes directing customers to the Win Lifecycle page for Win 10 version details as well as entries in the "Out of support" section covering 1703.
