### ISSUE TITLE
Fix invalid xref links in dotnet-api-docs

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#19387]
Check any build report to see the warnings.

**Comment by mairaw** [comment]
Should this be in the dotnet-api-docs repo then?

**Comment by gewarren** [comment]
> Should this be in the dotnet-api-docs repo then?

I couldn't decide where to put it, but happy to move it there. I created it here so I could it add it to the July project and track my work in one place.

**Comment by mairaw** [comment]
Makes sense!

**Comment by gewarren** [comment]
[bad-xrefs-0720.xlsx](https://github.com/dotnet/docs/files/4933929/bad-xrefs-0720.xlsx)

**Comment by mairaw** [comment]
I also found broken links like the ones in https://github.com/dotnet/dotnet-api-docs/pull/4527 where the formatting made them not be recognized as links. Not sure how to find those in the content. I found them by accident while doing the Try .NET work,

**Comment by mairaw** [comment]
I guess there is 😢 

![image](https://user-images.githubusercontent.com/12971179/87722700-6b132180-c76d-11ea-99fe-8f02df97dc37.png)

**Comment by gewarren** [comment]
Remaining links:
[bad-xrefs-0720.xlsx](https://github.com/dotnet/docs/files/4940822/bad-xrefs-0720.xlsx)
