### ISSUE TITLE
Parameters and Type Parameters Missing from TOC Pages for Delegates

### ISSUE THREAD

**Issue by seandebutts** [dotnet/docs#194]
API pages for delegates with parameters are missing Parameters and Type Parameters. 

Example:
Compare the .NET Core API pages for Action<T1, T2> Delegate with the corresponding page on the .NET Framework Class Library
https://docs.microsoft.com/en-us/dotnet/core/api/system.action-2
https://msdn.microsoft.com/en-us/library/bb549311(v=vs.110).aspx

/cc @blackdwarf @chenkennt @pengbian

**Comment by mairaw** [comment]
@chenkennt @superyyrrzz this is still an issue at docs.microsoft.com

**Comment by mairaw** [comment]
This still repros. Opened internal bug to track this: 983076

**Comment by mairaw** [comment]
This is resolved now.
