### ISSUE TITLE
There is a contradiction in two sentences of this page

### ISSUE THREAD

**Issue by roxanadhz** [dotnet/docs#19403]
[Enter feedback here]
In the "NotNull Constraints" paragraph of this page, there is two sentences that seems like contradict each other.
At line 4 it says: 
The compiler generates a warning if you add the notnull constraint in a nullable oblivious context.

At line 8 it says:
If the code is compiled in a nullable oblivious context, the compiler doesn't generate any warnings or errors.

I believe line 4 should be corrected to : The compiler "doesn't" generates "any" warning if you add the notnull constraint in a nullable oblivious context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on type parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I've tried using "notnull" constraint in both `#nullable enable` and `#nullable disable`, and the compiler accepts the existence of "notnull" in both cases without a warning or error.

Based on that, I think a better phrasing, if my understanding is correct, would be:

> The compiler doesn't generates a warning or an error if you add the notnull constraint in either a `#nullable enable` context or a `#nullable disable` context.

**Comment by Youssef1313** [comment]
I'd also improve the other sentence that reads:

> Unlike other constraints, when a type argument violates the notnull constraint, the compiler generates a warning when that code is compiled in a nullable enable context. If the code is compiled in a nullable oblivious context, the compiler doesn't generate any warnings or errors.

to be something like the following, that explains what is different than other constraints:

> Unlike other constraints, when a type argument violates the notnull constraint, the compiler generates a warning **(not an error like other constraints)** when that code is compiled in a nullable enable context. If the code is compiled in a nullable oblivious context, the compiler doesn't generate any warnings or errors.

**Comment by BillWagner** [comment]
Thanks for writing this @roxanadhz That section is not written as clearly as it should be.

I think this article needs a table that explains the following for each attribute:

- How each attribute is interpreted on a method declaration in a nullable enabled context.
- How each attribute is interpreted on a method declaration in a nullable disabled context.
- How each attribute is interpreted on a call to a method in a nullable enabled context.
- How each attribute is interpreted on a call to a method in a nullable disabled context.
