### ISSUE TITLE
Inaccurate information about vbCrLf

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19409]
> The \n (vbCrLf in Visual Basic) represents a newline character.

vbCrLf is \r\n

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET Core console application using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
@BillWagner This is still an issue.

**Comment by adegeo** [comment]
I don't know that it's worth trying to explain that. Either way, the newline command is interpreted by modern terminals as \r\n anyway. The effect is the same. I'll adjust the text a little bit though to make it clear it's talking about the vb code not the vb command.
