### ISSUE TITLE
Question: Why it is named `xx_ByDefault_xx`

### ISSUE THREAD

**Issue by litao5454** [dotnet/docs#19402]
Hi Microsoft,

I'm currently reading your great document [Unit testing best practices with .NET Core and .NET Standard](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices), and I can see a few tests are being named in "{methodNameBeingTested}_ByDefault_{expectedResult}". e.g. https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#validate-private-methods-by-unit-testing-public-methods

My question is as to the "ByDefault",  I don't fully understand why  the `ByDefault` as part of method name of a test, that hopefully I can get an answer from your side.

Take the below code snippet took from your article as an example, where there is a Parser class that provided a public method `ParseLogLine`, it requires the string type parameter. In the test case, we pass " a " as the value of the parameter, but in the name of the test case method we call it `ByDefaut", this is the point I got confused as it somehow seems to be a bit of a violation of the principle of [Naming your tests](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#naming-your-tests) because "ByDefault" doesn't indicate what value you will pass.

From what I understand, we might need to name the test method "ParseLogLine_spaceA_ReturnsTrimmedResult".

Eventually, thank you for building the great document.

```csharp
[Fact]
public void ParseLogLine_ByDefault_ReturnsTrimmedResult()
{
    var parser = new Parser();

    var result = parser.ParseLogLine(" a ");

    Assert.Equals("a", result);
}
```
```csharp
class Parser
{
    public string ParseLogLine(string input)
    {
        var sanitizedInput = TrimInput(input);
        return sanitizedInput;
    }

    private string TrimInput(string input)
    {
        return input.Trim();
    }
}
```

[Edited to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I believe `ParseLogLine_ByDefault_ReturnsTrimmedResult` is not a good name.

> The name of your test should consist of three parts:
>
> - The name of the method being tested.
> - The scenario under which it's being tested.
> - The expected behavior when the scenario is invoked.

A good naming would be similar to `ParseLogLine_StartsAndEndsWithSpace_ReturnsTrimmedResult` or `ParseLogLine_ContainsSpacesAtStartAndEnd_ReturnsTrimmedResult`.

**Comment by litao5454** [comment]
> I believe `ParseLogLine_ByDefault_ReturnsTrimmedResult` is not a good name.
> 
> > The name of your test should consist of three parts:
> > 
> > * The name of the method being tested.
> > * The scenario under which it's being tested.
> > * The expected behavior when the scenario is invoked.
> 
> A good naming would be similar to `ParseLogLine_StartsAndEndsWithSpace_ReturnsTrimmedResult` or `ParseLogLine_ContainsSpacesAtStartAndEnd_ReturnsTrimmedResult`.

Thanks. This makes more sense than "ByDefault". 
Does my naming(CreateDefaultUser_None_ReturnsADefaultUserObject) make sense for the below production code to be tested?
```csharp
[Fact]
public void CreateDefaultUser_None_ReturnsADefaultUserObject()
{
    // Do something
}
```

Production code:
```csharp
public class SomeClass
{
    public static User CreateDefaultUser()
    {
         return new User();
    }
}
```

**Comment by Youssef1313** [comment]
@litao5454 As a personal opinion, I dont see there is really a testing scenario in your case, so I'd just name it `CreateDefaultUserTest`. It's not following the stated convention, but IMO it's reasonable.

**Comment by BillWagner** [comment]
tag @jpreese to weigh in on this discussion.

**Comment by litao5454** [comment]
> @litao5454 As a personal opinion, I dont see there is really a testing scenario in your case, so I'd just name it `CreateDefaultUserTest`. It's not following the stated convention, but IMO it's reasonable.

@Youssef1313  I agree. In general, what convention for naming we can follow to test some methods that are parameterless.

**Comment by Youssef1313** [comment]
@litao5454 I *think* it depends.

1. If you're working with a team that uses a specific-convention, even if it's not the same being mentioned in docs, I'd stick to the team's convention to maintain consistency.
2. For parameterless methods like the one you showed I'd name it `<MethodName>Test` (completely my personal opinion, I don't know if there is a *known* and widely-used specific convention for that case).
3. For a parameterless method that behaves differently based on a *state*, I'd treat it like any other method that have parameter and name the test for it like so: `MethodName_Scenario_ExpectedResult`, where the "Scenario" part tells the "state" under which the method is tested.

@tdykstra, Do you think the article should be extended for scenarios like the one provided by @litao5454 ? In that case, you may consider re-opening the issue.

**Comment by litao5454** [comment]
> @litao5454 I _think_ it depends.
> 
> 1. If you're working with a team that uses a specific-convention, even if it's not the same being mentioned in docs, I'd stick to the team's convention to maintain consistency.
> 2. For parameterless methods like the one you showed I'd name it `<MethodName>Test` (completely my personal opinion, I don't know if there is a _known_ and widely-used specific convention for that case).
> 3. For a parameterless method that behaves differently based on a _state_, I'd treat it like any other method that have parameter and name the test for it like so: `MethodName_Scenario_ExpectedResult`, where the "Scenario" part tells the "state" under which the method is tested.
> 
> @tdykstra, Do you think the article should be extended for scenarios like the one provided by @litao5454 ? In that case, you may consider re-opening the issue.

Thanks again @Youssef1313. I'd request @tdykstra to extend for such scenarios as it can help lots of developers who is new to unit test and want to follow the great doc to setup its knowledge.

**Comment by tdykstra** [comment]
I'll defer to @jpreese

**Comment by jpreese** [comment]
The `ByDefault` convention is more or less saying "given a good input, this is what the method under test will do".

Using the Parser as a concrete example, where all the Parser does is trim the input, we're saying:

ParseLogLine ByDefault ReturnsTrimmedResult -- the _default_ behavior, the _expected_ behavior of this method, by default (assuming no edge cases), will return a trimmed result.

That's the heart of the reasoning for putting ByDefault there. I think it detracts from the test to say "WhenInputIsSpaceA" because it detracts from what we're actually testing.

I could get on board with saying "ParseLogLine_SpaceOnLeftAndRight_ReturnsTrimmedString", but you could also use that `ByDefault` case to pass in other cases such as " A", "A ", and " A " -- so you're not writing many individual tests. In a production scenario, with many other cases to consider, its hard to say exactly what's right or wrong.

As @Youssef1313 mentioned, a lot of these naming conventions are examples of how to write good tests and how to name them. I wouldn't take them as hard and fast rules, and by changing the name, your test name isn't any worse if your team is able to understand its input and its output.

Just like when writing code, readability is in the eye of the beholder-- you can't dictate what's easier to read for every person out there. We can't say that a specific naming convention makes tests easier to read. But we can give you some ideas and thoughts as to what makes a good test name. But feel free to change them if it makes sense for your team.

**Comment by litao5454** [comment]
> 
> 
> The `ByDefault` convention is more or less saying "given a good input, this is what the method under test will do".
> 
> Using the Parser as a concrete example, where all the Parser does is trim the input, we're saying:
> 
> ParseLogLine ByDefault ReturnsTrimmedResult -- the _default_ behavior, the _expected_ behavior of this method, by default (assuming no edge cases), will return a trimmed result.
> 
> That's the heart of the reasoning for putting ByDefault there. I think it detracts from the test to say "WhenInputIsSpaceA" because it detracts from what we're actually testing.
> 
> I could get on board with saying "ParseLogLine_SpaceOnLeftAndRight_ReturnsTrimmedString", but you could also use that `ByDefault` case to pass in other cases such as " A", "A ", and " A " -- so you're not writing many individual tests. In a production scenario, with many other cases to consider, its hard to say exactly what's right or wrong.
> 
> As @Youssef1313 mentioned, a lot of these naming conventions are examples of how to write good tests and how to name them. I wouldn't take them as hard and fast rules, and by changing the name, your test name isn't any worse if your team is able to understand its input and its output.
> 
> Just like when writing code, readability is in the eye of the beholder-- you can't dictate what's easier to read for every person out there. We can't say that a specific naming convention makes tests easier to read. But we can give you some ideas and thoughts as to what makes a good test name. But feel free to change them if it makes sense for your team.

Thanks for the reply @jpreese. I appreciate you and @Youssef1313. After talking to both of you, I now consider a good naming converntion is the convention that the whole team can understand or it is the rule specified by the team. 

I'd to post a suggestion here that you to add an annotation to describe the `ByDefault` in the doc for people who may not know the meaning very well, just like me. The naming for other cases mentioend in the doc is perfect.

**Comment by litao5454** [comment]
Closing this ticket as I think I got everything I wanted. Thanks again for everyone who contribued to this.
