### ISSUE TITLE
Trailing R flagged as error in Excel Subscription O365 (# works)

### ISSUE THREAD

**Issue by HelmZalee** [dotnet/docs#19436]
[This ](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types) dated 2015 contains a table that seems to say VBA will interpret a digit string followed by R or # as a Double: Double | (none) | R or (_hash, which I cannot seem to enter here w/o getting a mystery message)_

My version of excel flags 1R as an error, but seems happy with 1#.  The context is as a comma-delimited argument in a function call:`DateAdd("d", 1#, theDate)` is ok, `DateAdd("d", 1R, theDate)` is not.  ("My version" is O365, automatically updated so presumably up to date.)

What am i missing?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253a0a34-7f04-76d1-fb6b-2fa0712778f7
* Version Independent ID: f136c7bc-5d7c-a984-90db-99badea1994a
* Content: [Constant and Literal Data Types - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types)
* Content Source: [docs/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
This documentation is for VB.NET not VBA.

**Comment by HelmZalee** [comment]
...and I was so careful at the wrong thing ;-(  Thank you!
