### ISSUE TITLE
StreamReader could not find file path

### ISSUE THREAD

**Issue by cyberTrebuchet** [dotnet/docs#19434]
Greetings,

I'm debugging (the F5 option) in Visual Studio 2019 on Windows 10 pro, and StreamReader here is throwing a runtime error, saying it can't find the path.
```c#
using (StreamReader sr = new StreamReader("TestFile.txt"))
```
 I've tried several paths now, including the one on the [StreamWriter doc page](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-write-text-to-a-file). Is this because I used the GUI to manipulate `TestFile.txt`??

Let me know if I can supply further information.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7d2312a-0b45-4d11-b3fb-11e9cdba3372
* Version Independent ID: ea715711-4ee9-08cf-f319-6b7e1eadd84e
* Content: [How to: Read text from a file](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-read-text-from-a-file)
* Content Source: [docs/standard/io/how-to-read-text-from-a-file.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-read-text-from-a-file.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
Are you sure the file exists in the same directory of the executable?

**Comment by cyberTrebuchet** [comment]
No, the file is in the default directory specified by the StreamReader
constructor: ~\project\bin\Debug\netcoreapp3.1\

I have also tried other paths, including ~\project\ and
~\OneDrive\Documents\

I actually don't see any executable anywhere in the project directory, not
even hidden. Is it only a temporary file when using Visual Studio's debug
feature for C#? I remember C++ overwrote a permanent .exe for each build,
but that's all I know...

Thompson

**Comment by IEvangelist** [comment]
Hi 👋 @cyberTrebuchet
Thank you so much for posting this issue. We really appreciate it. 

When you use a path like that `"TestFile.txt"`, it assumes that it is relative to the current directory in which the executable is running. In this case, would you be able to add some output debug details?

Just before the line that is the `using (StreamReader sr = new StreamReader("TestFile.txt"))`, add the following:

```csharp
Console.WriteLine(File.Exists("TestFile.txt"));
Console.WriteLine(Path.GetFullPath(Directory.GetCurrentDirectory()));
foreach (var file in Directory.EnumerateFiles(Directory.GetCurrentDirectory()))
{
	Console.WriteLine(file);
}
```

Then let me know what is output, I'll use this to try to help you and we'll go from there.

**Comment by cyberTrebuchet** [comment]
Here is the console output from your code:

```
False
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.deps.json
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.dll
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.exe
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.pdb
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.runtimeconfig.dev.json
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\factorer.runtimeconfig.json
C:\Users\cyber\source\repos\factorer\factorer\bin\Debug\netcoreapp3.1\TestFile.txt.txt
```

As you can see, the problem was indeed my use of the GUI to create my test
file. The GUI was hiding the extra file extension. Serves me right. Thanks
for your help!

Thompson

**Comment by Youssef1313** [comment]
@cyberTrebuchet, A small tip to avoid a problem similar to this later. From file explorer, click view, then check File name extensions.

![image](https://user-images.githubusercontent.com/31348972/87330317-b5f82380-c538-11ea-9e32-f76ba9c49ff1.png)

This will make the file appear when the full name with extensions.

**Comment by cyberTrebuchet** [comment]
Oh there it is! First time coding on Windows! Thanks again!

Thompson
