### ISSUE TITLE
Unable to add Microsoft package signing key to the list of trusted keys and add the package repository

### ISSUE THREAD

**Issue by SibeeshVenu** [dotnet/docs#19433]
The preceding command is always failing for me. 

`wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb`

![2020-07-11_15-36-19](https://user-images.githubusercontent.com/4262147/87225348-80aed280-c38c-11ea-9ada-2d8a8c867d8c.png)

As in the image, it always gives me the error "packages-microsoft-prod.deb: Permission denied". Am I missing anything here?

Note: Already tried with sudo.

I run Ubuntu 20.04 and WSL1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
Try to run `sudo wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb sudo dpkg -i packages-microsoft-prod.deb`

**Comment by SibeeshVenu** [comment]
Already tried that, sorry for not mentioning that. Updated the issue.

**Comment by adegeo** [comment]
your current directory shouldn't be system32, use `cd ~` to get to your home directory

**Comment by SibeeshVenu** [comment]
@adegeo Yeah, it was my mistake. Closing this issue. Thanks.
