### ISSUE TITLE
Reference a plugin interface from a NuGet package causes an exception.

### ISSUE THREAD

**Issue by doctorcode-co** [dotnet/docs#19448]
I create a simple modular system and use the concept of documents to implement the plugin interface. 
All things are right and I can load and use my plugins perfectly if I add a reference to original project. but when reference plugin interface from a NuGet package I get an error:

> 'Method 'ConfigureServices' in type 'DoctorCode.Club.Membership.MembershipConfigureServices' from assembly 'DoctorCode.Club.Membership, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

The NuGet package reference in plugin project:
```
<PackageReference Include="DoctorCode.AspNetCore.Modules.Abstrctions" Version="1.0.0">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
</PackageReference>
```
The plugin interface:
```
namespace DoctorCode.AspNetCore.Modules.Abstrctions
{
    public interface IModuleConfigureServices
    {
        void ConfigureServices(IServiceCollection services);
    }
}
```

The plugin implementation:
```
namespace DoctorCode.Club.Membership
{
    public class MembershipConfigureServices : IModuleConfigureServices
    {
        public MembershipConfigureServices(IConfiguration configuration)
        {
            Configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
                      
        }
    }
}
```

**Comment by IEvangelist** [comment]
Hi 👋 @doctorcode-co,
Thank you so much for posting this issue. We really appreciate it. This certainly doesn't seem to apply to the documentation, unless I'm missing something?

- What doc were you following?
- What does the contents of the package actually look like?
- Do you have the source in a repo that I could look at?

We're missing a lot of important details here that we'll need to help you. Thanks

**Comment by doctorcode-co** [comment]
Hi @IEvangelist 
Thanks to quick reply.

> What doc were you following?

The Microsoft official document: [link](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support)

> Do you have the source in a repo that I could look at?

yes, I create a new repository and upload a full sample at [link](https://github.com/doctorcode-co/ModularApi.git) to reproduce the error.
Thank you so much

**Comment by doctorcode-co** [comment]
I found the cause of this problem. 
Because **CopyLocalLockFileAssemblies** is enabled, all assemblies are copied along with their dependency on the output directory, which causes us to have different versions of an assembly. 
Is there a way to filter some assemblies like **Microsoft.Extensions.DependencyInjection.Abstractions** when creating output?

**Comment by IEvangelist** [comment]
> I found the cause of this problem.
> Because **CopyLocalLockFileAssemblies** is enabled, all assemblies are copied along with their dependency on the output directory, which causes us to have different versions of an assembly.
> Is there a way to filter some assemblies like **Microsoft.Extensions.DependencyInjection.Abstractions** when creating output?

@doctorcode-co, no - not that I'm aware of. Working through old issues this AM, I'm going to close this as your original issue has been resolved. Thank you.
