### ISSUE TITLE
Example Code does not build.

### ISSUE THREAD

**Issue by primerpop** [dotnet/docs#19450]
Is there any reasonable expectation that this code, when copied and pasted will actually work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by primerpop** [comment]
Specifically the final code from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/   Admitted not a C# expert and not accustomed the the flavor of voodoo required to get what seem to be straight forward examples to work.

**Comment by primerpop** [comment]
If the example is to be useful to those learning.  Please make it complete.

  class Coffee
    {
    }

    class Juice
    {
    }

    class Toast
    {
    }

    class Bacon
    {
    }

    class Egg
    {
    }

**Comment by Youssef1313** [comment]
@primerpop

Was your problem because of the missing classes?
There is a note in the article regarding these classes

![image](https://user-images.githubusercontent.com/31348972/87309572-15483a80-c51d-11ea-84b1-740228e671b7.png)

Was the note unclear to you that you need to create these empty classes?

@IEvangelist Do you think the article needs to be updated in some way?

**Comment by primerpop** [comment]
I suppose if I was going to teach this, I'd include the empty classes so that the copy and pasted example would work.   Yes, it states the classes are empty but their absence breaks the example.

I leave to Microsoft to choose the right thing to do in this case.   If you want to increase the quality of your examples, making them work is a good start.

**Comment by IEvangelist** [comment]
Hi @primerpop and @Youssef1313,

It might be worth looking into. I was thinking that we could potentially use Try.NET with these, and have it runnable from the browser. We'd need to improve the outputs a bit to better showcase the amount of time things take. Then it could include the classes.
