### ISSUE TITLE
Implicit conversion between ternary operator branches is sufficient

### ISSUE THREAD

**Issue by TysonMN** [dotnet/docs#19468]
This is a very minor point, but I thought I would share it anyway.

This documentation [says](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator#code-try-0:~:text=The%20type%20of%20consequent%20and%20alternative,from%20one%20type%20to%20the%20other.)
> The type of `consequent` and `alternative` must be the same, or there must be an implicit conversion from one type to the other.

It is unnecessary to explicitly mention the case of the types being the same since the [identity conversion is an implicit conversion](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#identity-conversion:~:text=An%20identity%20conversion%20converts%20from%20any%20type%20to%20the%20same%20type.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5379a49c-6a81-82a5-cca2-3ab71f432c5c
* Version Independent ID: 1a00e3ec-bec1-3030-9766-a788912bc3b9
* Content: [?: operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)
* Content Source: [docs/csharp/language-reference/operators/conditional-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/conditional-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for mentioning this @bender2k14 

Our intention with the language reference is to be more informative than normative. For that reason, this is a lower priority issue. I'll leave it in the backlog for consideration when we next update this article.

**Comment by Youssef1313** [comment]
@BillWagner, FYI, there is proposal to change that behavior.

https://github.com/dotnet/csharplang/issues/2460

And looks like it's implemented in https://github.com/dotnet/roslyn/pull/40604

If it ships with C# 9.0, the doc should certainly reflect that.

**Comment by pkulikov** [comment]
@bender2k14 @BillWagner That phrasing is by design. I prefer to emphasize the "same types" case, though it's unnecessary. I think that way it's more approachable to newcomers of the language (and requires less processing of the "implicit conversions" part; when I was new to the language, it helped me to omit thinking of the conversions parts, that way I went through basics faster). Also, `ref ternary` must have the same types of both parts. As it is now, the corresponding two sentences in the article play with each other nicely.
