### ISSUE TITLE
Error running code in tutorial "Read-only auto-properties enable read-only types"

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#19478]
---
**Issue moved from MicrosoftDocs/feedback#2886**
- Please respond to @calumtomeny.

---

_From @calumtomeny on Monday, June 22, 2020 2:26:11 PM_

Error when running C# code in focus mode when going through the tutorial: " "Read-only auto-properties enable read-only types".

1. Go to https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=1
2. Click on 'Enter focus mode'
3. Copy and paste code into the .Net editor as instructed 'Enter Focus mode, copy the preceding code into the C# interactive window. '

**Expected behavior**
There are no errors and the code executes.

**Error**: 
```
(1,1): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
(1,7): error CS0118: 'System' is a namespace but is used like a type
(1,13): error CS0210: You must provide an initializer in a fixed or using statement declaration
(1,13): error CS1001: Identifier expected
(1,1): error CS1513: } expected
(27,14): error CS0542: 'Program': member names cannot be the same as their enclosing type
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.8.90

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#2886**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Monday, June 22, 2020 2:26:12 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Youssef1313** [comment]
@gewarren, the labels in this issue (and the other two issues that were moved from feedback repo) doesn't match the labels used in docs.

**Comment by tdykstra** [comment]
Closing, as the tutorial https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=1 no longer exists. The URL redirects to https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7?tutorial-step=1
