### ISSUE TITLE
Unclear whether one has to do both or one. Maybe clarify it?

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#19477]
---
**Issue moved from MicrosoftDocs/feedback#2904**
- Please respond to @HubKing.

---

_From @HubKing on Saturday, June 27, 2020 10:44:03 AM_

**Describe the bug**
It says "to ..., you must do the following" and then it lists 3 bullet points. But I am not sure if I do all of them, or if the first bullet point is an obsolete one. The first one is editing the manifest file, the second one is editing the app.config file, and the third one is calling a method.
But there is an "Important" box at the end of the second bullet that says "In previous versions of the .NET Framework, you used the manifest to add high DPI support. This approach is no longer recommended, since it overrides settings defined on the app.config file." What exactly is "you used the manifest file to add"? Is that the thing in the first bullet or something else?

That is, is it saying that I should not do the thing that is described in the first bullet any more? In such case, why is it still in the same-level of bullet points? Shouldn't it be like:

* Do one of the following
  * Modify app.config
  * Modify manifest (deprecated) And the "Important" should be moved from "app.config" section to here.
* Call the method

Or I should do all of the three bullet points and the thing that is mentioned in the "important" box is something I do not have to care about now? In such case, probably it is better to be more specific what that use of manifest was, so that readers would not think it is the first bullet point.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms
2. Scroll down to Configuring your Windows Forms app for high DPI support

**Expected behavior**
Clear, unambiguous, up-to date information for setting up high DPI support.

**Comment by gewarren** [comment]
@hubking I agree this could be clearer. I think you still declare compatibility with Windows 10 in the manifest file, which is different to adding high DPI support in the manifest file (deprecated). But double checking with @KlausLoeffelmann .

**Comment by adegeo** [comment]
I'm closing this old feedback. If we see more confusion in the desktop repo, we'll reconsider it, but right now .NET Framework articles are a low priority.
