### ISSUE TITLE
Correction suggested on Interfaces page

### ISSUE THREAD

**Issue by jaison-git** [dotnet/docs#19470]
The line shown under section 'Interfaces summary' says, 'Optionally, an interface may define default implementations for some or all of its members'. Assume this is a typo, it should be 'Optionally, an abstract class may define default implementations for some or all of its members'

Jaison Ittoop
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The statement is correct. It was a new feature with C# 8.0 I think.
See [this blog](https://devblogs.microsoft.com/dotnet/default-implementations-in-interfaces/) for details.

I think the article needs to be updated to be clear about that and provide an example or a link to that blog.
