### ISSUE TITLE
Typo in Customizing Operations By Using Stored Procedures

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#19476]
---
**Issue moved from MicrosoftDocs/feedback#2926**
- Please respond to @adipuscasu.

---

_From @adipuscasu on Tuesday, July 7, 2020 8:13:31 PM_

**Describe the bug**
The Description section is mentioning the **Northwind** class (https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/customizing-operations-by-using-stored-procedures#code), but the class shown in the code example inherits the **Nortwnd** class (https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/customizing-operations-by-using-stored-procedures#code-1)

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/customizing-operations-by-using-stored-procedures#code' and read the name of the class.
2. Go to 'https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/customizing-operations-by-using-stored-procedures#code-1' and read the name of the inherited class.
3. See that the base class is named **Northwnd** instead of **Northwind**.

**Expected behavior**
The base class from the code example should be named **Northwind**

**Screenshots**
![image](https://user-images.githubusercontent.com/7973905/86837176-389b6180-c0a7-11ea-9c8c-d8b7aa4fdf86.png)
![image](https://user-images.githubusercontent.com/7973905/86837224-45b85080-c0a7-11ea-96db-273f8d342e98.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by Youssef1313** [comment]
@BillWagner @gewarren This needs to be addressed. Can you re open?
