### ISSUE TITLE
How do I find the address of stuff?

### ISSUE THREAD

**Issue by mrj001** [dotnet/docs#19483]
[Enter feedback here]
The DumpObj command "displays information about an object at a specified address".   Similar notes are found for each command.  However, I cannot find anything not this page about how I am supposed to find the address of a given object.

Similarly, how can I display the line of code that a particular stack frame is on?  Eg. If my function contains n calls to another function, I cannot determine which of the n calls is the one that lead to the next stack frame.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e01c075-7a07-5850-d462-706675b545f1
* Version Independent ID: 0dd6c661-01a1-592c-ea53-8427412ff8d0
* Content: [SOS.dll (SOS Debugging Extension)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension?redirectedfrom=MSDN)
* Content Source: [docs/framework/tools/sos-dll-sos-debugging-extension.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sos-dll-sos-debugging-extension.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Hello!

Sorry to say, but this article is not the right place to ask that question. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. This article is just the help information displayed by the tool, not a tutorial on how to use it. Doing a quick search I found http://www.dotnetspeak.com/debugging/inspecting-objects-using-windbg/ which mentions

>you can use !dumpheap command to look at each object and !dumpheap -MT to look at the instances of each type.  Once you get an object address from the output of !dumpheap -MT command, you can then type
>
>!dumpobj XXXX
>
>where XXXX is the object address.

I'm going to close the issue. 

Thanks.
