### ISSUE TITLE
Text after list is part of list incorrectly in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1951]
It seems that when API reference remarks were imported, all plain lines (i.e. those not part of a list, a blockquote or a heading) had a single leading space added. The problem with this is that when such a line is right after a list, it is considered part of the last item of the list in markdown.

Consider `MuxLogger` ([MSDN](https://msdn.microsoft.com/en-us/library/microsoft.build.utilities.muxlogger.aspx#Remarks), [docs.ms](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Build.Utilities.MuxLogger?view=netframework-4.7#remarks), [source](https://github.com/dotnet/docs/blob/deb15e7/xml/Microsoft.Build.Utilities/MuxLogger.xml#L22-L59)):

* The lines "The `MuxLogger` registers loggers in the following way:" and "The `MuxLogger` unregisters loggers in the following way:" are indented by one space, which causes them to be incorrectly considered part of the preceding list.
* Lines like "Any loggers registered before the build manager starts the build get the build-started event at the same time as the `MuxLogger`." are indented by 5 spaces and are correctly considered part of the preceding list. Changing the indentation to 4 spaces would not cause any issue.

I already have two PRs that deal with this issue (https://github.com/dotnet/docs/pull/1893, https://github.com/dotnet/docs/pull/1948), but it's so pervasive that I think a more global solution is needed.

My questions:

* Is this something worth fixing globally (considering it would change many files at once)?
* Should the indentation be fixed everywhere, or only where it causes an issue?
* Would a PR by me be welcome, or do you have a better way to deal with this?
* Would it make sense to fix other issues at the same time? If so, which ones?

I have also created a PR showing one possible solution: https://github.com/dotnet/docs/pull/1952.

**Comment by mairaw** [comment]
The engineering team has given us a different solution for us to tryi. I'll open a new PR to see the results and we can compare.

**Comment by mairaw** [comment]
My PR seemed to resolve the issue. Ok to close this @svick?

**Comment by svick** [comment]
Yeah, closing this issue and the PR.
