### ISSUE TITLE
Precisions on the "configfile" option on "dotnet restore"

### ISSUE THREAD

**Issue by loicmorvan-ansys** [dotnet/docs#19532]
Maybe I misread the article, but I did not get exactly what happens when specifying the switch "configfile" during a "dotnet restore".

"Restore" will use the specified configuration file but will it still use the configuration files in the scopes: solution, user and computer (as specified [here](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior))?

Also, when *not* specifying this option, will it still behave like expected in [the doc](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
>but will it still use the configuration files in the scopes: solution, user and computer (as specified here)?

`--configfile`  should override the other config files.

> when not specifying this option, will it still behave like expected in the doc?

It should.

Are you not seeing the expected behavior?

**Comment by loicmorvan-ansys** [comment]
I'm not really sure about what I see 😃 

I was just wondering if the NuGet repository `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\` defined in the file `C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config` is still used when specifying this option.

We have some issues on our build machines (running Azure DevOps build agents) with NuGet restore and the only difference I can see is that we do specify the `--configfile` option to our `NuGet.config` defined in our git repository through the Azure DevOps [Build, test, and deploy .NET Core apps](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops) while we just let *dotnet* does its magic finding the `NuGet.config` by itself on our Desktop environments.

**Comment by tdykstra** [comment]
>I was just wondering if the NuGet repository `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\` defined in the file `C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config` is still used when specifying this option.

@nkolev92 can you help with this question?

**Comment by nkolev92** [comment]
Whenever the ConfigFile option is used, it will use *only* that specific file and not the defaults from the folders mentioned.
