### ISSUE TITLE
Obsolete properties on ConsoleLoggerOptions

### ISSUE THREAD

**Issue by shirhatti** [dotnet/docs#19533]
## Obsolete properties on ConsoleLoggerOptions

As part of the changes introduced in https://github.com/dotnet/runtime/pull/38616, some properties present on `ConsoleLoggerOptions` have been obsoleted. With the introduction on new formatters, these properties now live on the individual formatters.

The properties obsoleted are:
 - `DisableColors`
- `IncludeScopes`
- `TimestampFormat`
- `UseUtcTimestamp`

- `Format`

### Version introduced

Any application targeting a version >= 5.0.0-preview8 of the `Microsoft.Extensions.Logging.Console` NuGet package or any application targeting a version >= 5.0.0-preview8 of the `Microsoft.AspNetCore.App` shared framework.

### Old behavior

N/A. Old APIs still work. They have marked obsolete for deletion in a future release.

### New behavior
 
N/A

### Reason for change

The `Format` property was a enum. An enum doesn't work well anymore given that it can't represent custom formatters. 

The remaining properties were set on the `ConsoleLoggerOptions` and applied to both the inbuilt formats for Console logs. However, with introduction of a new formatter API, it makes more sense for formatting concerns to be represented on the formatter-specific options. The new change better represent the separation of concerns between the logger and loggerformatters.

### Recommended action

The `Format` property has now been replaced by the `FormatterName` property.

```diff
loggingBuilder.AddConsole(options =>
{
-    options.Format = ConsoleLoggerFormat.Systemd;
+  options.FormatterName = ConsoleFormatterNames.Systemd;
});
```

These properties are now set on the individual formatter options. In the case of the in-built formatters, the types are:
- `Microsoft.Extensions.Logging.Console.JsonConsoleFormatterOptions`
- `Microsoft.Extensions.Logging.Console.SimpleConsoleFormatterOptions`

Assuming you're using the SimpleConsoleFormatter, instead of setting the `DisableColors` property on the `ConsoleLoggerOptions`

```csharp
loggingBuilder.AddConsole(options =>
{
    options.DisableColors = true;
});
```

you would now set it on the  `SimpleConsoleFormatterOptions`

```csharp
loggingBuilder.AddSimpleConsole(options =>
{
    options.DisableColors = true;
});
```

### Category

- ASP.NET Core
- Core .NET libraries

### Affected APIs

- https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions.disablecolors
- https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions.format
- https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions.includescopes
- https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.consoleloggeroptions.timestampformat

---
#### Issue metadata

* Issue type: breaking-change

**Comment by shirhatti** [comment]
@maryamariyan Can you please review?

**Comment by maryamariyan** [comment]
LGTM. Also note that enum ConsoleLoggerFormat itself is also getting Obsoleted.

**Comment by BrennanConroy** [comment]
Should probably also include what configuration changes are needed.

**Comment by maryamariyan** [comment]
> Should probably also include what configuration changes are needed.

The below properties obsoleted:

DisableColors
IncludeScopes
TimestampFormat
UseUtcTimestamp

were set via configuration:

Logging:Console:DisableColors
Logging:Console:IncludeScopes
Logging:Console:TimestampFormat
Logging:Console:UseUtcTimestamp
Logging:Console:

and now the get set via configuration:

Logging:Console:FormatterOptions:DisableColors
Logging:Console:FormatterOptions:IncludeScopes
Logging:Console:FormatterOptions:TimestampFormat
Logging:Console:FormatterOptions:UseUtcTimestamp

and since the obsoleted property "Format" has been replaced by FormatterName, now we set configuration to select formatter via:

Logging:Console:FormatterName



w
