### ISSUE TITLE
IFileInfo: don't use physical path anymore when serving from packfiles

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/docs#19562]
## IFileInfo: don't use physical path anymore when serving from packfiles

When serving content from packfiles, returning the path of the packfile in IFileInfo.PhysicalPath (for filesystem watcher) doesn't work anymore. It now serves from the physical path rather than the file stream it was given.

In reading the code, I'm convinced the change is intentional.

### Version introduced

3.0

### Old behavior

The fixed part of the static file server in Kestrel would serve the static file using the stream returned in IFileInfo whether or not the path is included. It looks like the path gets used for setting up a FileSystemWatcher that gets used for something though.

### New behavior

The fixed part of the static file server in Kestrel (Microsoft.AspNetcoer.StaticFiles.StaticFileContext ) would serve the static file using the stream returned in IFileInfo only if the path is null.

### Reason for change

Not known to me.

### Recommended action

Don't fill IFileInfo.PhysicalPath unless the physical path refers to a file that contains the exact content to return. Providing the path that could be used to derive the content (for If-Modified-Since or related things) doesn't work.

### Category

- ASP.NET Core

### Affected APIs

Microsoft.Extension.FileProviders.IFileInfo.PhysicalPath

---
#### Issue metadata

* Issue type: breaking-change

**Comment by danmosemsft** [comment]
@maryamariyan is this your area - can you review?

**Comment by maryamariyan** [comment]
yes. It's my area. OK.

**Comment by maryamariyan** [comment]
@jhudsoncedaron do you mind sharing a repro code for this?

**Comment by jhudsoncedaron** [comment]
[pacsrv.zip](https://github.com/dotnet/docs/files/4955730/pacsrv.zip)

Demonstration; see PackFileProvider.cs line 94.

**Comment by gewarren** [comment]
@scottaddie I just noticed this is an ASP.NET Core breaking change. Do you want to take it?

**Comment by IEvangelist** [comment]
Closing as this is dated back to a version that is out-of-support.
