### ISSUE TITLE
String output is different from the one shown

### ISSUE THREAD

**Issue by jegcode** [dotnet/docs#19578]
[Enter feedback here]

Hi Team, 

Thanks for providing these examples. They are quite clarifying. 

The output for the Area example is actually: 

```
Area for a circle with a radius of '1' = 3.14
Area for a circle with a radius of '2' = 12.57
Area for a circle with a radius of '3' = 28.27
```

instead of:

```
Area = 3.14
Area = 12.57
Area = 28.27
```

I think it's important to show the actual string generated by executing the query, especially for developers who are starting
to work with interpolated strings and method syntax. 

Thanks again!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a44517-d9a2-454d-90f3-90d9553ff4be
* Version Independent ID: f31a6959-8212-a49f-eeb4-43936dbfbadb
* Content: [Data Transformations with LINQ (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/data-transformations-with-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @jegcode I see that @Youssef1313 has already submitted a PR to address this issue. We'll get it merged and published shortly.

**Comment by jegcode** [comment]
> Thanks for pointing this out @jegcode I see that @Youssef1313 has already submitted a PR to address this issue. We'll get it merged and published shortly.

Thank you @BillWagner and thanks @Youssef1313 for the PR.
