### ISSUE TITLE
"Azure Storage Bus" a typo?

### ISSUE THREAD

**Issue by ChevronSoftware** [dotnet/docs#19574]
A very helpful article (thank you!) with a possible typo. Where it says:

"Azure **Storage Bus** offers more flexibility and is the recommended service for non-trivial messaging..."

I wonder if this was meant to be either Service Bus, or Storage Queues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25fb9c48-2622-22c2-0500-0c263f3e5568
* Version Independent ID: 31af4a9a-caab-e92d-0733-dc61ba386bbd
* Content: [Azure hosting recommendations for ASP.NET Core web apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/azure-hosting-recommendations-for-asp-net-web-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/azure-hosting-recommendations-for-asp-net-web-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/azure-hosting-recommendations-for-asp-net-web-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Thanks for reporting that!
