### ISSUE TITLE
sql-server-data-type-mappings.md SqlDbType enumeration and DbType enumeration not write.

### ISSUE THREAD

**Issue by OdaShinsuke** [dotnet/docs#1959]
SqlDbType enumeration is "SqlDbType" with all cell. and DbType enumeration is "DbType" with all cell.  
expected:https://msdn.microsoft.com/en-us/library/cc716729.aspx

**Comment by GuardRex** [comment]
@OdaShinsuke Thanks for reporting this. This happened when the doc migrated over to GitHub. I'm including it in our Migration Project, and we'll get it fixed ASAP.

**Comment by mairaw** [comment]
Thanks for working on a fix for this particular topic @GuardRex. But this is the same issue as #1932. I think all the links to enum fields got incorrectly migrated. I have an internal bug opened to track this.

**Comment by GuardRex** [comment]
No probs

**Comment by GuardRex** [comment]
@OdaShinsuke Thanks for reporting. This will get fixed on the PR @mairaw cited.
