### ISSUE TITLE
grammar correction

### ISSUE THREAD

**Issue by pstevlingson** [dotnet/docs#19606]
The designer of the derived class can different choices for the behavior of virtual methods:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ebd197-8f01-b8d7-45d6-1a7afba572b4
* Version Independent ID: 0790b314-a794-6ce3-15f0-37281faa00a6
* Content: [Polymorphism - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/polymorphism)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/polymorphism.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/polymorphism.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @pstevlingson I've opened a PR to fix this issue.

In the future, if you find issues like this, you can also open a PR with the fix. That might save us both time.

Thanks again for pointing this out.
