### ISSUE TITLE
Huge conceptual error on "How to use finally blocks" section.

### ISSUE THREAD

**Issue by Matayas-B** [dotnet/docs#19614]
*********** PLEASE, ATTEND TO THIS ISSUE BECAUSE IS CRITICAL ***********
Hello guys,

I have discovered that you have an giant redaction issue on the section "**How to use finally blocks**". In that part, you wrote a try-catch-finally block that makes no sense at all!

Let me explain further, take a look at the code from your page:

```
public static void Main()
    {
        int[] array1 = {0, 0};
        int[] array2 = {0, 0};

        try
        {
            Array.Copy(array1, array2, -1);  ----> Here is when the exception occurs
        }
        catch (ArgumentOutOfRangeException e)
        {
            Console.WriteLine("Error: {0}", e);
            throw; ----> And here, we are throwing the exception, which prevents the finally block to get executed!
        }
        finally
        {
            Console.WriteLine("This statement is always executed."); ----> **WRONG** This statement is never executed!
        }
    }
```
I hope you can make some time to edit this, because that actually sounded weird to me, and that was the reason I took some time to test it... But any naive or less-experienced developer can incur into mayor problems with this lack of knowledge.

Thank you and kind regards.

Matayas.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1202a39-a94a-c97d-ffb8-2d25a13245f4
* Version Independent ID: 4092d5d3-f69a-cf78-3164-0c423947d2eb
* Content: [How to: Use Finally Blocks](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-finally-blocks)
* Content Source: [docs/standard/exceptions/how-to-use-finally-blocks.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-use-finally-blocks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment]
@Matayas-B Thanks for raising this.

I did verify the code, and the sample is correct. The statement in the `finally` block does run.  I'll close this as an answered question.

**Comment by Matayas-B** [comment]
Hi again @BillWagner 

I tested the same code that was written above (the same that is on the official docs), and again I'm not being able to reach the _finally_ block when inside the _catch_ statement the exception is thrown. The only way to reach that finally block is by either returning any value within the function, or avoiding writting any _throw_ statement.

Below my examples:

class ArgumentOutOfRangeExample
	{
		public static int Test()
		{
			int[] array1 = { 0, 0 };
			int[] array2 = { 0, 0 };

			try
			{
				Array.Copy(array1, array2, -1); //----> Here is when the exception occurs
				return new Random().Next();
			}
			catch (ArgumentOutOfRangeException e)
			{
				Console.WriteLine("Error: {0}", e);
				return new Random().Next(); //----> This return statement DO allow the finally block to be executed
				throw; //----> But this throw statement prevents the finally block to get executed!
			}
			finally
			{
				Console.WriteLine("This statement is always executed."); //----> **WRONG * *This statement is never executed if the throw statement is called on the catch!
			}
		}

		static void Main(string[] args)
		{
			Test();
			Console.Read();
		}
	}

Thanks, and kindly regards.
