### ISSUE TITLE
ExecuteAsync now takes 4 arguments

### ISSUE THREAD

**Issue by mercer** [dotnet/docs#19631]
Looks like `ExecuteAsync` now takes 4 arguments, the example should be updated

```
        Task<TResult> ExecuteAsync<TState, TResult>(
            [CanBeNull] TState state,
            [NotNull] Func<DbContext, TState, CancellationToken, Task<TResult>> operation,
            [CanBeNull] Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded,
            CancellationToken cancellationToken = default);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57452ceb-e885-d193-d813-d7baf7291cbc
* Version Independent ID: 6ad8c3bc-fdef-1e24-175d-ca7c7b9a98ce
* Content: [Implement resilient Entity Framework Core SQL connections](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections#execution-strategies-and-explicit-transactions-using-begintransaction-and-multiple-dbcontexts)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @mercer ,the code snippet in the book is actually referring the `ResilientTransaction` class in [eShopOnContainers - ResilientTransaction](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/IntegrationEventLogEF/Utilities/ResilientTransaction.cs). 
Though there is a overload available for `IExecutionStrategy.ExecuteAsync` method which accepts 4 arguments but as the original code is not using that overload, there might not be need to update the reference code in the book. Your thoughts ?

Thanks.

**Comment by mercer** [comment]
Ok, I see. We can close this :+1:  thanks for answering
