### ISSUE TITLE
Wrong key

### ISSUE THREAD

**Issue by JerryWoods44** [dotnet/docs#19649]
Press Shift+F5 to compile and run the program without debugging.nter feedback here]
should be Ctrl+F5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Create a .NET Standard class library using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that!
