### ISSUE TITLE
Ubuntu 16.04 Support

### ISSUE THREAD

**Issue by amartens181** [dotnet/docs#19659]
The docs say it is supported, but the package does not exist at: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@rbhanda @leecow  Looks like the .deb package is missing. The parent folder lists it as if it should exist, but for some reason this specific file is no longer available.

**Comment by rbhanda** [comment]
I am following up with the Infra team and an [incident ](https://portal.microsofticm.com/imp/v3/incidents/details/197794190/home)has been created for this

**Comment by rbhanda** [comment]
As per the infrastructure team, this issue should be resolved now. I have also tested that the [package](https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb) is available

**Comment by adegeo** [comment]
@rbhanda Thanks!
@amartens181 Thanks for reporting the issue!
