### ISSUE TITLE
Need a better example

### ISSUE THREAD

**Issue by mdchafin** [dotnet/docs#19656]
While the example shows how async / await work the sample code "sucks"  Why?

The purpose of async / await is to allow processing to happen on multiple threads thus shortening the time it takes to complete the overall task (cook breakfast). Time of this is the same no matter the technique used, around 15.0xx seconds. 

It's nice to say that you don't want your eggs to be cold by the time breakfast is ready but has nothing to do with code processing.  The primary purpose of async / await is to overlap tasks and save time and keep the user in control. 

I've seen a lot of code where async / await is misused and has no benefit other than to make the code harder to read.

Please find a better example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @mdchafin 

We agree that we need more samples. A number are identified in [this project](https://github.com/dotnet/docs/projects/42).

That said, we are keeping this sample for a few reasons. Readers have like the analogy to an everyday task. In addition, it shows one of the important use cases for asynchronous programming: that of running multiple tasks that are not CPU bound, but rely on other processes or hardware to complete. Using async code for database calls, network I/O, and file I/O helps web applications scale. 

I'll close this.
