### ISSUE TITLE
first bullet in Interfaces Summary is peculiar

### ISSUE THREAD

**Issue by Patrick5** [dotnet/docs#19667]
It seems to me that the first bullet in the Interfaces Summary ([here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)) is kind of oddly worded.  Read in its entirety it essentially states:

> An Interface is like an abstract base class, or it is not like an abstract base class.

It could be re-written in a more linear fashion to read: 

> An Interface is like a base class. It can be abstract, or it can have default implementations for some or all methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Patrick5 That should be worded better.
I've added this to our backlog so that we updated it when we next update this article.
