### ISSUE TITLE
microsoft-spark-2.4.x-<version>.jar

### ISSUE THREAD

**Issue by fengzmgit** [dotnet/docs#19668]
[Enter feedback here]
Where is microsoft-spark-2.4.x-<version>.jar from? I do not see it in this guide.
Thank you.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-gb/dotnet/spark/tutorials/get-started)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @fengzmgit 

Thanks for your question. That file is created when you build your application and is located in your build output directory (i.e. `bin/Debug/netcoreapp3.1`). I'm in the process of updating the tutorial to make this more clear.

**Comment by fengzmgit** [comment]
Hi Lius,

Sorry for the late reply. Yes, I have found the file. Thank you very much
for following up.
Have a good day!

Regards,
Feng Zhemin

**Comment by luisquintanilla** [comment]
@fengzmgit Great! I'll keep this issue open until the updates to the tutorial are made. Feel free to raise another issue if you have any other doc related questions or issues.

**Comment by luisquintanilla** [comment]
AB#1766482
