### ISSUE TITLE
Remove duplicate common folders

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1966]
The common folder was copied to https://github.com/dotnet/docs/tree/master/samples/snippets/common and also to each individual language. I think we should only keep one copy of it.

**Comment by rpetrusha** [comment]
I agree.

**Comment by tompratt-AQ** [comment]
@mairaw  Unless you have something more pressing for me to work on, I'd like to take on this issue. Since I've already deleted a few of these in other PRs, I familiar with the issue and how to proceed while making sure that the \common files are truly dupes.
