### ISSUE TITLE
Comments say "// TODO: set large fields to null." - why?

### ISSUE THREAD

**Issue by Dave-Lowndes** [dotnet/docs#19674]
If there's a good reason for it, please document it, otherwise please remove the comments from this document and from any auto-generated code. It's clearly confusing people as you can see if you search online for an answer to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implement a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by imba-tjd** [comment]
It's already documented:

> Managed objects that consume large amounts of memory or consume scarce resources. Assign large managed object references to null to make them more likely to be unreachable. This releases them faster than if they were reclaimed non-deterministically.

But there is a conflict that this sentence is below 

> This block executes if the value of disposing is true. The managed resources that it frees can include

while the

> // TODO: set large fields to null.

is not inside `if (disposing)`.

**Comment by Dave-Lowndes** [comment]
OK, fair enough, I'd missed that. The conflict you mentioned aside though, I'd say that "to make them _more likely_ to be unreachable" is somewhat vague, and it's not mentioned in the generated code comments where people will likely encounter it and wonder why.
I assume you'll investigate the highlighted conflict?
