### ISSUE TITLE
dotnet test --list-tests description

### ISSUE THREAD

**Issue by jashley-sg** [dotnet/docs#19670]
Can it be made clearer that the `--list-tests` argument stops the tests from executing, please? This isn't obvious from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
@tdykstra The description in docs doesn't match with the CLI.

https://github.com/dotnet/sdk/blob/9b113feabec7e29d7a9ed437fe20a9702c6853dc/src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx#L133

> List the discovered tests instead of running the tests.

@jashley-sg If the above description is still not clear, It makes sense to me to update it in the CLI tool too, not only docs.

**Comment by jashley-sg** [comment]
@Youssef1313 The CLI looks pretty clear to me. Even that simple description would improve the docs.

**Comment by Youssef1313** [comment]
I'll open a PR soon and fix other issues with that doc page too.
