### ISSUE TITLE
dotnet publish with PublishProfile is incorrect

### ISSUE THREAD

**Issue by jamers99** [dotnet/docs#19677]
The instructions how to publish with a Publishing Profile is incorrect and does not work.
```
dotnet publish -p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml
```
The profile is disregarded and doesn't make any difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The command works as shown if the .pubxml file is found. You don't get an error message if the file is not found. Is it possible the path you're specifying isn't resolving to a .pubxml file? The path needs to be relative to the command prompt's folder, not the project folder if the command prompt isn't in the project folder.

**Comment by jamers99** [comment]
@tdykstra I created a new project and added a publishing profile from VS for a self contained app. I used the above command and it worked, generating the x86 app.

But, if I move the publishing profile and update my command to the new path, it doesn't work.  Attached is a repo, I used this command: `dotnet publish -p:PublishProfile=FolderProfile.pubxml`

[PublishApp.zip](https://github.com/dotnet/docs/files/4974129/PublishApp.zip)

**Comment by jamers99** [comment]
Interesting, if I leave the `.pubxml` file in the original folder (_Properties\PublishProfiles_), then use `dotnet publish -p:PublishProfile=FolderProfile.pubxml` it finds and uses the profile.

It seems like it doesn't use the directory of the argument to find the file, only the name of the file in the argument?

**Comment by tdykstra** [comment]
@sfoslund - If you specify `-p:PublishProfile=PathToFile\FileName.pubxml`, does MSBuild ignore the path and just look for the file name under <project folder>\Properties\PublishProfiles?

**Comment by jamers99** [comment]
Wow, this is strange! It completely ignores the directory and just uses the path.
![image](https://user-images.githubusercontent.com/20806279/88434536-62a29280-cdce-11ea-8392-a20da307c860.png)

**Comment by sfoslund** [comment]
Yes, I found the code [here](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportPublishProfile.targets#L19). It looks like the `PublishProfile` property is treated as a file name and the directory is constructed separately.

**Comment by tdykstra** [comment]
Thanks @sfoslund and @jamers99 -- I'll correct the doc.

**Comment by jamers99** [comment]
@tdykstra in my case I used PublishProfileFullPath (can't be relative).
