### ISSUE TITLE
Remove A/W probing for P/Invokes on non-Windows platforms

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/docs#19681]
## Remove A/W probing for P/Invokes on non-Windows platforms

The Windows [function convention](https://docs.microsoft.com/windows/win32/intl/conventions-for-function-prototypes) of having a A/W suffix is now only respected on the Windows platform. Both the CoreCLR and Mono runtimes have continued this probing on non-Windows platform where the A/W suffix is not a convention. With this change the automatic addition of a A/W suffix is no longer performed on non-Windows platforms. The semantics of both runtimes on the Windows platform remain unchanged.

See https://github.com/dotnet/runtime/issues/33246 for additional details.

### Version introduced

.NET 5.0

### Old behavior

During export discovery for P/Invokes an A/W prefix was added to the export name when probing. This was done on all platforms.

### New behavior

During export discovery for P/Invokes an A/W prefix was added to the export name when probing only on the Windows platform.

### Reason for change

This change was made to simplify the cross-platform probing. It is overhead that should not be incurred by the developer given non-Windows platforms don't contain this semantic.

### Recommended action

In order to mitigate this change, the user should manually add the desired prefix on non-Windows platforms.

In the example below, if the export on non-Windows was `FooW` the following declaration would previously suffice:

```CSharp
[DllImport(...)]
extern static void Foo();
```

It is now recommended the developer update the declaration with the desired prefix:

```CSharp
[DllImport(...)]
extern static void FooW();
```

### Category

- Interop

### Affected APIs

[DllImportAttribute](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute).

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@AaronRobinsonMSFT Is this for preview 8?

**Comment by jeffschwMSFT** [comment]
@gewarren this change has been in since an early preview of .NET 5... perhaps around Preview 3 or 4.
