### ISSUE TITLE
c# issues

### ISSUE THREAD

**Issue by Or-Ag** [dotnet/docs#19691]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb589056-4671-7088-a879-57000f96603c
* Version Independent ID: fece589b-c559-2d52-69e3-d82291520f0f
* Content: [Compiler Error CS1001](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1001)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1001.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs1001.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @Or_Ag
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@Or-Ag, Can you please provide more details about the problems you're facing?
