### ISSUE TITLE
Why use 'handler' in 'OnThresholdReached' method to refer the event 'ThresholdReached' instead of using it directly in the method?

### ISSUE THREAD

**Issue by BingchenLi** [dotnet/docs#19698]
[Enter feedback here]
In the code examples, why not directly use ThresholdReached? Any particular reasons of using a 'handler' to refer the event 'ThresholdReached'?
```
        protected virtual void OnThresholdReached(EventArgs e)
        {
            EventHandler handler = ThresholdReached;
            if (handler != null)
            {
                handler(this, e);
            }
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89598b6d-6319-fc9e-d7b7-3335f40e9506
* Version Independent ID: e074b827-7416-3c43-7fde-0244c61bb35c
* Content: [How to: Raise and Consume Events](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events)
* Content Source: [docs/standard/events/how-to-raise-and-consume-events.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-raise-and-consume-events.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @BingchenLi 
Thank you so much for posting this issue. We really appreciate it. 

We've been working at updating these examples, as there is a more common practice for checking whether or not the `handler` was `null`.

```csharp
protected virtual void OnThresholdReached(EventArgs e) =>
    ThresholdReached?.Invoke(this, e);
```

It can be expressed as a single line. This uses the [null conditional operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-). Does that make sense?
