### ISSUE TITLE
Adding 'callback' key word to clarify why listening to events is optional while delegate is not.

### ISSUE THREAD

**Issue by BingchenLi** [dotnet/docs#19702]
[Enter feedback here]
In the section "Listening to Event is Optional", it just says "you should do" without much explanation of "why".
Some supplement explanations like "design based on delegates when you need to implement callback ..." would be helpful to justify the point for some readers have experience with "callback".
Sometimes just a word can make knowledge connects and make it clearer.  

[edit by @BillWagner formatting text]

---
Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba0864-5fe4-a917-f09d-23f3535ac834
* Version Independent ID: 83c86812-6f94-443f-80b7-41f1275c9a76
* Content: [Delegates vs. events](https://docs.microsoft.com/en-us/dotnet/csharp/distinguish-delegates-events)
* Content Source: [docs/csharp/distinguish-delegates-events.md](https://github.com/dotnet/docs/blob/master/docs/csharp/distinguish-delegates-events.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @BingchenLi 

I've added this to our backlog to update when we next update this article. 

I've also added the "up for grabs" label if anyone in the community wishes to submit a PR in the interim.
