### ISSUE TITLE
CQRS in context of querying multiple databases

### ISSUE THREAD

**Issue by davelowndes** [dotnet/docs#19703]
Would appreciate discussion on querying multiple sources/databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce115a1c-3cc0-c01d-4fb4-95105cfeda85
* Version Independent ID: 3469e63a-4c32-d38e-152a-28be75f2b056
* Content: [Applying simplified CQRS and DDD patterns in a microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Thanks @davelowndes for reaching out.

For greater isolation there is a possibility to segregate the read data from the write data. Even you can use different data store for also for read and write respectively to achieve optimized performance. In such scenarios read database can use it's own set of schemas which are optimized for queries. For an example : it can store Materialized View of the data for avoiding complex joins. And materialized view can have data populated from one or more data sources. So it could be a good pattern to adopt for CQRS related queries on multiple data sources. 
You can [refer](https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view) for more details. 

Hope this helps !

**Comment by sughosneo** [comment]
Hi @davelowndes, we are closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
