### ISSUE TITLE
The command `dotnet-svcutil http://contoso.com/SayHello.svc` needs authentication but none are specified for the example 

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/docs#19701]
If I run the command `dotnet-svcutil http://contoso.com/SayHello.svc` the tool prompts me with
~~~
The server needs to authenticate your request.
Your credentials will be sent to the server in clear text.
Press the ENTER to accept or ESC to cancel:
~~~

but the example does not give any creds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [WCF svcutil tool overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
@Timo-Weike  This server address is an example, you can't actually use it. You need to point it to your own service.
