### ISSUE TITLE
Docs for What's new in C# 9.0

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#19705]
C# 9 feature status: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md

@BillWagner I think one year ago we've worked quite efficiently for C# 8.0 doc updates:

- You've created the main page for "What's new in C# 8.0" with the major new features described
- I've updated that page and the related reference doc with smaller new features

Would it work this year for C# 9.0? I'm thinking of updating the docs for `new` (target-typed new), the conditional operator (target-typed conditional), `foreach` (extension `GetEnumerator`), lambda expressions (discard parameters).

**Comment by BillWagner** [comment]
@pkulikov 

> Would it work this year for C# 9.0?

Yes! Thank you. I'll update the project for C# 9 content by early next week. That should include issues / notes for what needs to update.
