### ISSUE TITLE
`dotnet tool restore` <Package Name> Argument is Unclear

### ISSUE THREAD

**Issue by danielloganking** [dotnet/docs#19717]
I am quite confused by this section in the documentation for `dotnet tool restore`: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore#arguments.

Specifically:
> * PACKAGE_NAME
> Name/ID of the NuGet package that contains the .NET Core tool to install.

I had assumed this meant if I had a tools manifest like so:
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "swashbuckle.aspnetcore.cli": {
      "version": "5.3.1",
      "commands": [
        "swagger"
      ]
    }
  }
}
```

I could run `dotnet tool restore swashbuckle.aspnetcore.cli` to restore the version of `swashbuckle.aspnetcore.cli` specified in the tools file. However, that does not appear to be the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198e4c22-ac0b-61de-3ae1-221a73957843
* Version Independent ID: 0873ec7c-9134-138c-97dd-ef96ca31ef23
* Content: [dotnet tool restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore)
* Content Source: [docs/core/tools/dotnet-tool-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-restore.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
You're right, package_name doesn't belong there, I'll remove it.  The command finds the manifest file in scope or you can specify the manifest file with the `--tool-manifest` option.
