### ISSUE TITLE
"Tutorial: Get started on macOS" link broken

### ISSUE THREAD

**Issue by damonzocp** [dotnet/docs#19711]
**Before you open an issue**

If the issue is:

- A simple typo or similar correction, consider submitting a PR to fix it instead of logging an issue. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.

I probably know what the link should be but not 100% sure.  Also it looks like you want me to sign something before creating a PR.  I'm not doing that.

- A general support question, consider asking on a support forum site.

Not a general support question.

- A site design concern, create an issue at [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback/issues/new/choose).

Not a site concern.

- A problem completing a tutorial, compare your code with the completed sample.

Not a code sample.

- A duplicate of an open or closed issue, leave a comment on that issue.

After looking for 30s, it doesn't look like anyone has reported this yet.

**Issue description**

Steps to reproduce:
* Go to https://github.com/dotnet/docs/blob/master/docs/core/install/macos.md
* Under "Next Steps" click link "Tutorial: Get started on macOS."

Expected behavior:
* Taken to a new page

Actual behavior
* 404 when taken to https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-mac-vs.md

Perhaps link should go to https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-mac.md

[Edited by gewarren to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e
* Version Independent ID: 68d524f7-6cf1-2caa-56d5-f243952d1526
* Content: [Install .NET Core on macOS](https://docs.microsoft.com/en-us/dotnet/core/install/macos)
* Content Source: [docs/core/install/macos.md](https://github.com/dotnet/docs/blob/master/docs/core/install/macos.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
It looks like a redirect has been put in place, because this is working for me.

**Comment by adegeo** [comment]
@damonzocp Hi. Thank you for spotting this. The redirect is in place so this doesn't happen in the live site, only when you're browsing the source. However, the source should be updated. The thing you sign is a legal agreement between you and the .NET Foundation: https://cla.dotnetfoundation.org/ which basically says you allow any project of the .NET Foundation to use your contribution.

As that page says:

>We appreciate community contributions to code repositories open sourced by the .NET Foundation. By signing a contributor license agreement, we ensure that the community is free to use your contributions.

Anyway, I'll fix that up. Thanks again.
