### ISSUE TITLE
Does .Net Framework 4.7 support .Net Standard 1.6?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1974]
[The .NET platforms support table](https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support) says that .Net Standard 1.6 will be supported on a "vNext" version of .Net Framework, using 1.0 tooling. Well, .Net Framework 4.7 has been released, does it support .Net Standard 1.6? (I haven't updated Windows yet, so I can't test it myself. And I don't know where to look in source code to find out.)

In any case, I think the table should be updated:

* If .Net Framework 4.7 supports .Net Standard 1.6 using 1.0 tooling, the cell should say "4.7" instead of "vNext".
* If .Net Framework 4.7 does not support .Net Standard 1.6 using 1.0 tooling, and there are no plans for a future version of .Net Framework to do so, the the cell should be empty.
* In the unlikely case that it's planned that the next version of .Net Framework will support .Net Standard 1.6 using 1.0 tooling, then that cell should stay the same.

Also, as far as I can tell, 1.0 tooling does not allow you to reference a .Net Standard 2.0 library from a .Net Framework 4.6.1 project, so that cell should be removed.

Also also, whoever is fixing this should fix the "4.61" typo.

**Comment by mairaw** [comment]
Someone already submitted a PR for the 4.61 typo: https://github.com/dotnet/docs/pull/1975

I talked to @weshaggard and I'll remove the values from 1.6 and 2.0 from the 1.0 tooling line.

/cc @terrajobst @karelz

**Comment by terrajobst** [comment]
@svick 

The current state of the documentation reflects the shipped versions of .NET Standard and .NET Framework. Right now, .NET Framework 4.6.1 is understood by our tooling as supporting .NET Standard 1.4 only. Once we ship .NET Standard 2.0, this will change we'll treat .NET Framework 4.6.1 as supporting 2.0, which then also includes 1.5 and 1.6. However, since the necessary support hasn't changed the documentation is still up-to-date (and correct).

The upcoming state of the version table is reflected here:

https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by svick** [comment]
@terrajobst I don't understand. My suggestions are not about the upcoming changes in 2.0, that's already in the "with tooling 2.0" row of the table. It's specifically about what the current 1.0 tooling does with:

* .Net Framework 4.7 project referencing a .Net Standard 1.6 library.

   The table says it should work, assuming 4.7 = vNext. If I understand what @mairaw said correctly, then it doesn't, so the table shouldn't claim that it does.

* .Net Framework 4.6.1 project referencing a .Net Standard 2.0 library.

  I tried this one and it didn't work, even though the table says it should work with 1.0 tooling.

**Comment by terrajobst** [comment]
Sorry, I'm context switching way too much 😄 

> .Net Framework 4.7 project referencing a .Net Standard 1.6 library. The table says it should work, assuming 4.7 = vNext.

.NET Framework 4.7 supports also currently just supports .NET Standard 1.4. vNext should probably be labelled "future".

> .Net Framework 4.6.1 project referencing a .Net Standard 2.0 library.

To be expected, as our tooling hasn't been released yet.

**Comment by mairaw** [comment]
What I discussed with @weshaggard about the 1.0 tooling line is that I'd just remove the values for the 1.6 and 2.0 columns since it's not currently support and it seems I should also remove from 1.5. Will the 1.0 tooling for framework ever support something greater than NS 1.4 @terrajobst?

**Comment by svick** [comment]
@mairaw I tried it and it seems 1.0.3 tooling does support referencing Standard 1.5 from Framework 4.6.2. So I think that cell is fine.

I agree that the other two should be removed.

**Comment by terrajobst** [comment]
> Will the 1.0 tooling for framework ever support something greater than NS 1.4 @terrajobst?

I think until we shipped 2.0 I'd make the doc match this table, except:

* Use the entries that are in strikeout font
* Remove the 2.0 column

This way, it's clear that this is 1.x tooling situation. You can then add a *separate* table that is prefixed with something like:

> **Note:** The following table refers to the preview of .NET Standard 2.0. Unless you use the new tooling, the table from above applies.

**Comment by mairaw** [comment]
I agree @terrajobst. I had in my previous PR like that at some point (https://github.com/dotnet/docs/pull/1724), so it would show the current state and some people didn't like it. I'll change it then. 😄
