### ISSUE TITLE
I don't understand this part of the article

### ISSUE THREAD

**Issue by GoodzoneLo** [dotnet/docs#19758]
I dont get this part: Now, let's change how the Balance is reported. It can be found by summing the values of all transactions. Modify the declaration of Balance in the BankAccount class to the following:

```csharp
public decimal Balance
{
    get
    {
        decimal balance = 0;
        foreach (var item in allTransactions)
        {
            balance += item.Amount;
        }

        return balance;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @GoodzoneLo 

There's an error in the text. At that point in the tutorial, there isn't a `Balance` property on the `Account` class. Instead of "modify", the text should read:

> Now, let's add a property to report the `Balance`. The current balance can be found by summing the values of all transactions. Add a declaration for Balance in the BankAccount class. Add the following code inside the `BankAccount` class:

**Comment by jmarkman** [comment]
Hey @BillWagner, this looks like an easy "win" - mind if I clean this up?

**Comment by BillWagner** [comment]
Thanks @jmarkman That would be great. I'll watch for a PR.
