### ISSUE TITLE
Async Task senario

### ISSUE THREAD

**Issue by honeyhhv** [dotnet/docs#19768]
for the sake of preparing breakfast scenario to make more sense,  I suggest that change the order of these two method-calls in the main method:
first :  `Juice oj = PourOJ(); `
at the end:  `Coffee cup = PourCoffee(); ` ==> no one likes a cold coffee !!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi 👋 @honeyhhv
Thank you so much for posting this issue. We really appreciate it.

Coffee is always first, and sipped on during the making of breakfast - just not shown here. 😄 I'm going to close this, feel free to reopen it if you thing we'd need to make any other changes.
