### ISSUE TITLE
Broken link or missing documentation for F# Map collection

### ISSUE THREAD

**Issue by tuok** [dotnet/docs#19767]
I was browsing page https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types and clicked Links "Map" (https://msdn.microsoft.com/library/975316ea-55e3-4987-9994-90897ad45664) and "Map Module" (https://msdn.microsoft.com/library/bfe61ead-f16c-416f-af98-56dbcbe23e4f) in the collection type table.

Both links seem to be broken and I cannot seem to find documentation of F# Map even with Google.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0694330-a4e4-5a07-2b6b-8259b57e319a
* Version Independent ID: 71e9da59-27a1-6194-3a69-09b9d3a383d4
* Content: [Collection Types - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types)
* Content Source: [docs/fsharp/language-reference/fsharp-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/fsharp-collection-types.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
As a workaround you can use this: https://aka.ms/fsharp-core-reference
