### ISSUE TITLE
Add Link to "Permission Calculator"

### ISSUE THREAD

**Issue by InstanceFactory** [dotnet/docs#19770]
Hi All,

Reading the chapter "Checking access" (https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/azure-security#checking-access) I tried to find the mentioned "Permission Calculator". Not being an Azure pro, and therefor not aware of the fact that IAM is the access control tab of each resource, I was not able to find it. Searching the Internet for "azure permission calculator" did not returned any results (at least on the first pages). A colleague gave me the relevant hint.

I suggest to add the following link to the chapter to help others to quickly find the described functionality: https://docs.microsoft.com/en-us/azure/role-based-access-control/check-access.

Thanks,

Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8626fd64-2a32-4a87-3268-51df9a61e8ff
* Version Independent ID: 85cdc078-f5f9-670d-d5a7-8d1123239ab3
* Content: [Azure security for cloud-native apps](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/azure-security#deny)
* Content Source: [docs/architecture/cloud-native/azure-security.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/azure-security.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by InstanceFactory** [comment]
If you agree, I will update the doc (create a PR). I would just turn the first place of docs/architecture/cloud-native/azure-security.md where 'permissions calculator' is mentioned into a link. That's it.

Please let me know what you think.

Thanks,

Stefan

**Comment by robvet** [comment]
Absolutely. Perfect. If @InstanceFactory would submit a PR, we could approve.

@InstanceFactory - thanks for catch and fix!!

**Comment by InstanceFactory** [comment]
@robvet - You're welcome :-)
