### ISSUE TITLE
How to the settings get read by the program code?

### ISSUE THREAD

**Issue by nschuessler** [dotnet/docs#19774]
Is there a pointer to how you read the settings in your .Net console application for example?
I don't see a link to show how to do it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa7bda7-581d-9654-c7c5-5ff0292ddfb3
* Version Independent ID: 7f32162e-ec95-0a16-7618-14b7a7c80cff
* Content: [Run-time config options - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/)
* Content Source: [docs/core/run-time-config/index.md](https://github.com/dotnet/docs/blob/master/docs/core/run-time-config/index.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nschuessler I think you are trying to configure custom settings. If so, this article doesn't apply as it's about configuring the .NET Core runtime itself. Check out the examples at https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager?view=dotnet-plat-ext-3.1.

**Comment by gewarren** [comment]
Somewhat related to #19585.
