### ISSUE TITLE
MethodImplOptions.SecurityMitigations is undocumented.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/docs#19783]
.NET Framework 4.8 [added a new field](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netframework-4.8) in the `System.Runtime.CompilerServices.MethodImplOptions` named `SecurityMitigations`.

But it is _nowhere_ mentioned what this field does; even a Google search did not uncover anything.

What does `MethodImplOptions.SecurityMitigations` do?

**Comment by gewarren** [comment]
@teo-tsirpanis Are you looking for a description beyond the existing one?

"The JIT compiler should look for security mitigation attributes, such as the user-defined System.Runtime.CompilerServices.SecurityMitigationsAttribute. If found, the JIT compiler applies any related security mitigations."

**Comment by teo-tsirpanis** [comment]
Yes. What exactly are these "security mitigations"? I have found absolutely no documentation about them.

Googling `SecurityMitigationsAttribute` yields almost zero results.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4603
