### ISSUE TITLE
The options for dotnet-trace are not depndent on the runtime version.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19781]
The options for dotnet-trace are only dependent on the version of dotnet trace and _not_ the runtime.

_Originally posted by @josalem in https://github.com/dotnet/docs/pull/19730#issuecomment-667222518_

**Comment by Youssef1313** [comment]
@josalem, I think you meant that the following sentence isn't accurate?

> This article applies to: ✔️ .NET Core 3.0 SDK and later versions

**Comment by josalem** [comment]
No, that sentence is accurate.  The tool itself only works when the target application is running a runtime 3.0 or newer, but none of the options on the tool itself are dependent on a specific runtime version.  The other tools aren’t guaranteed to be the same.  For instance, dotnet-gcdump only works when collecting data from runtimes 3.1 or newer.

I didn’t see any discrepancies in the docs I looked at related to versions of the dotnet runtime.

**Comment by Youssef1313** [comment]
@josalem, Great. I seem to misunderstood things.

Closing this.
