### ISSUE TITLE
Incorrect figure number

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19782]
Figure 10-3 is mentioned, but none if the images is labeled with 10-3
Actually, all images are 9-x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8626fd64-2a32-4a87-3268-51df9a61e8ff
* Version Independent ID: 85cdc078-f5f9-670d-d5a7-8d1123239ab3
* Content: [Azure security for cloud-native apps](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/azure-security)
* Content Source: [docs/architecture/cloud-native/azure-security.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/azure-security.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Youssef1313 ,  Good catch 👍  Thank you for pointing that out. 

Yes, the statement would be - `It's typically found under the IAM tab in the portal, as shown in Figure 9-4`

Would you like to submit a PR to [docs repo](https://github.com/dotnet/docs/pulls) ?
