### ISSUE TITLE
Hello World example doesn't work

### ISSUE THREAD

**Issue by jthiesen2** [dotnet/docs#19786]
I installed the SDK, then tried
dotnet new console
which took about 5 minutes to run 'dotnet restore'
then
dotnet run
which produced error MSB3577: Two output file names resolved to the same output path  "obj\Debug\netcoreapp3.1\TestProject.Form1.resources" [C:\Users\thies\thies.csproj]

The build failed. Fix the build errors and run again.

How is it possible that your documentation is so wrong that the Hello World example fails?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad87897-30cc-e639-b91a-b3800269f7fe
* Version Independent ID: 9d3015b4-cba1-0956-9ec7-4154dbb74d93
* Content: [.NET Core intro and overview](https://docs.microsoft.com/en-us/dotnet/core/introduction)
* Content Source: [docs/core/introduction.md](https://github.com/dotnet/docs/blob/master/docs/core/introduction.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
>  which took about 5 minutes to run 'dotnet restore'

AFAIK, the restore process downloads some packages. So, this is dependent on your internet connection speed.

---

> MSB3577: Two output file names resolved to the same output path "obj\Debug\netcoreapp3.1\TestProject.Form1.resources" [C:\Users\thies\thies.csproj]

The path in the error contains "Form1", which indicates a WinForms app, not a Console app. Maybe you have tried creating two apps in the same directory which caused some problem?

Can you please try creating a new folder, and run the commands again from it?

I hope this fixes your problem. If it doesn't, please reply back and wait an official answer from a Microsoft employee.

**Comment by jthiesen2** [comment]
I found another example that was slightly different:
dotnet new console --output sample1
dotnet run --project sample1

This works fine, so apparently you have to give it a name.


________________________________

**Comment by Youssef1313** [comment]
Both examples should work I think.
Did you try a new empty folder?

**Comment by jthiesen2** [comment]
That's exactly how I started. I downloaded the SDK on a machine that hasn't had .NET Core on it before and then immediately tried to run the Hello World example and got the error messages.

Now later I created a new folder and tried again and didn't get the error but got the expected output, so I don't see what made the difference.


________________________________

**Comment by adegeo** [comment]
If no output folder is specified it uses the current directory. There must have been other files in the current directory of the terminal you had open at the time. I'll close this issue. Cheers!
