### ISSUE TITLE
Duplicated content 

### ISSUE THREAD

**Issue by DomenPigeon** [dotnet/docs#19787]
A lot of this content is duplicated in the previous chapter 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9b4b39-813f-ed23-3cb7-682766b3cfaa
* Version Independent ID: c3216a96-76a2-21aa-2072-0328725cd3cb
* Content: [Language independence and language-independent components](https://docs.microsoft.com/en-us/dotnet/standard/language-independence)
* Content Source: [docs/standard/language-independence.md](https://github.com/dotnet/docs/blob/master/docs/standard/language-independence.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tdykstra** [comment]
Fixed by #24320
