### ISSUE TITLE
InternalsVisibleTo isn't documented in csproj article

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19790]
I couldn't find anywhere in the docs a hint that `InternalsVisibleTo` can be used in csproj files, neither in this article nor any other article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
AFAIK it can't be without some fun trickery: https://www.meziantou.net/declaring-internalsvisibleto-in-the-csproj.htm

Are you saying it should be mentioned or noted? 😄

**Comment by Youssef1313** [comment]
> 
> 
> AFAIK it can't be without some fun trickery: https://www.meziantou.net/declaring-internalsvisibleto-in-the-csproj.htm
> 
> Are you saying it should be mentioned or noted? 😄

@adegeo I'm not sure what's the difference between it being mentioned or noted. But basically anything that at least shows its existence :smile:

A more neat example than unit testing would be:

Some company have "Team X" and "Team Y". "Team X" produces a library that's publicity available. But "Team Y" needs to make use of some specific internal APIs which shouldn't be public. This scenario is solvable using `InternalsVisibleTo`.

**Comment by cremor** [comment]
I think this can be closed, it is documented here: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#internalsvisibleto

**Comment by Youssef1313** [comment]
Thanks @cremor!
