### ISSUE TITLE
Document dotnet-format CLI tool

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19792]
The [dotnet-format](https://github.com/dotnet/format/) tool is missing in the documentation at https://docs.microsoft.com/en-us/dotnet/core/additional-tools/

**Comment by adegeo** [comment]
Generally it's up to the teams that work on these tools to add their documentation to the docs repo. 
@JoeRobich

**Comment by mikadumont** [comment]
@gewarren and @BillWagner where is the best place to add documentation for this?

**Comment by gewarren** [comment]
I think it would be where @Youssef1313 suggested: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/

**Comment by mikadumont** [comment]
Thanks @gewarren just wanted to double check!

**Comment by jmarolf** [comment]
This is no longer necessary as dotnet format now comes with the CLI
