### ISSUE TITLE
error reproducable

### ISSUE THREAD

**Issue by putriafebriana98** [dotnet/docs#19793]
I uncomment the first example on line 
      baseObject.myValue = 10;
but I don't get any error... could you verify this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650c563e-748e-7ad7-fea9-0504549a56ab
* Version Independent ID: ad6dac17-6e62-1447-e85d-e502ae39a343
* Content: [protected internal - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected-internal)
* Content Source: [docs/csharp/language-reference/keywords/protected-internal.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/protected-internal.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Do you have `BaseClass` and `DerivedClass` in the same assembly or in different assemblies?

They should be in different assemblies.

**Comment by putriafebriana98** [comment]
aha, I make it in one class,,,oke, so my mistake...thx for confirmation
