### ISSUE TITLE
[Discussion] Folder structure - cs vs csharp

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19791]
I don't remember which PR was the initial discussion with @IEvangelist.

The current folder structure uses vb, csharp, and fsharp folder names inside the snippets folder for each doc.

David was suggesting to use cs as it's shorter.

It looks like an automated tool could rename csharp to cs and update the articles to use it as well.

If you wish to use cs instead of csharp (and probably fs too?), a PR will be needed to update [this guide](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute#example-folder-structure), then I can try to write a tool to rename the current csharp files.

I'm personally with David's opinion, but I'd like consistency too.

@adegeo @BillWagner Opinions?

**Comment by Youssef1313** [comment]
Note: this doesn't apply to the *samples* folder in the repository root, but applies to *snippets* folders under *docs*.

**Comment by BillWagner** [comment]
@Youssef1313 In #17297 we standardized on `csharp`. We chose that because is the same as the language identifier we use in code fences.

/cc @IEvangelist

**Comment by IEvangelist** [comment]
> @Youssef1313 In #17297 we standardized on `csharp`. We chose that because is the same as the language identifier we use in code fences.
> 
> /cc @IEvangelist

I'm good with the naming.

**Comment by Youssef1313** [comment]
Great. One thing caught my eye is:

> These folders are not needed in the language guide area, where only one language is assumed.

This is not mentioned in https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute#example-folder-structure

I'll open a PR to clarify this, and make sure it's actually followed. Then close the issue.
