### ISSUE TITLE
Breaking change: Roslyn analyzer CA2247 - Argument passed to TaskCompletionSource constructor should be TaskCreationOptions enum instead of TaskContinuationOptions enum

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#19809]
## Breaking change: Roslyn analyzer CA2247 - Argument passed to TaskCompletionSource constructor should be TaskCreationOptions enum instead of TaskContinuationOptions enum

This new Roslyn analyzer will emit a warning if the user constructs a `System.Threading.Tasks.TaskCompletionSource` with a `System.Threading.Tasks.TaskContinuationOptions` enum value rather than a `System.Threading.Tasks.TaskCreationOptions` enum value.

Depending on the project's settings, the warning could show up as a build break.

### Version introduced

This analyzer is included in .NET 5 Preview 8 SDK and turned on by default.
It can be turn them off by setting the MSBuild flag `EnableNETAnalyzers` to `false`.

### Old behavior

The user could, without warning, construct a `System.Threading.Tasks.TaskCompletionSource` with a `System.Threading.Tasks.TaskContinuationOptions` enum value rather than a `System.Threading.Tasks.TaskCreationOptions` enum value.

### New behavior

The user will now see the CA2247 warning suggesting to replace the `System.Threading.Tasks.TaskContinuationOptions` enum value with the corresponding `System.Threading.Tasks.TaskCreationOptions` enum value.

### Reason for change

The `TaskCompletionSource` type has a constructor that accepts a `System.Threading.Tasks.TaskCreationOptions` enum value, and another constructor that accepts an `Object`. Accidentally passing a `System.Threading.Tasks.TaskContinuationOptions` enum value instead of a `System.Threading.Tasks.TaskCreationOptions` enum value will result in calling the `Object`-based constructor: it will compile and run, but it will not have the intended behavior.

### Recommended action

Replace the `System.Threading.Tasks.TaskContinuationOptions` enum value with the corresponding `System.Threading.Tasks.TaskCreationOptions` enum value. It is not recommended to suppress this warning, since this rule almost always highlights a bug in the calling code.

Refer to the documentation for rule CA2247 for a detailed explanation on when to expect this rule violation to be diagnosed and how/when to suppress the warnings.

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2247

### Category

- Core .NET libraries

### Affected APIs

Constructing a [`System.Threading.Tasks.TaskCompletionSource<TResult>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1) with a with a [`System.Threading.Tasks.TaskContinuationOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcontinuationoptions) enum value.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by carlossanlop** [comment]
cc @stephentoub @GrabYourPitchforks @jeffhandley

**Comment by jeffhandley** [comment]
LGTM
