### ISSUE TITLE
Breaking change: Roslyn analyzer CA2015 - Do not define finalizers for types derived from MemoryManager<T>

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#19808]
## Breaking change: Roslyn analyzer CA2015 - Do not define finalizers for types derived from MemoryManager<T>

This new Roslyn analyzer will emit a warning if a finalizer is defined for types derived from `MemoryManager<T>`.

Depending on the project's settings, the warning could show up as a build break.

### Version introduced

This analyzer is included in .NET 5 Preview 8 SDK and turned on by default.
It can be turn them off by setting the MSBuild flag `EnableNETAnalyzers` to `false`.

### Old behavior

The user could, without warning, add a finalizer to a type derived from `MemoryManager<T>`.

### New behavior

The user will now see the CA2015 warning suggesting to remove the finalizer definition.

### Reason for change

Adding a finalizer to a type derived from `MemoryManager<T>` is likely an indication of a bug, as it suggests a native resource that could have been handed out in a `Span<T>` is getting cleaned up and potentially while it is still in use by the `Span<T>`.

### Recommended action

Remove the finalizer definition.

Refer to the documentation for rule CA2015 for a detailed explanation on when to expect this rule violation to be diagnosed and how/when to suppress the warnings.

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2015

### Category

- Core .NET libraries

### Affected APIs

Finalizers defined in types that derive from [System.Buffers.MemoryManager&lt;T&gt;](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorymanager-1).

---
#### Issue metadata

* Issue type: breaking-change

**Comment by carlossanlop** [comment]
cc @buyaa-n @GrabYourPitchforks @jeffhandley

**Comment by jeffhandley** [comment]
LGTM
