### ISSUE TITLE
Breaking change: Roslyn analyzer CA2013 - Do not use ReferenceEquals with value types

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#19806]
## Breaking change: Roslyn analyzer CA2013 - Do not use ReferenceEquals with value types

This new Roslyn analyzer will emit a warning if it finds instances where the `System.Object.ReferenceEquals` method is used to test one or more value types for equality.

Depending on the project's settings, the warning could show up as a build break.

### Version introduced

This analyzer is included in .NET 5 Preview 8 SDK and turned on by default.
It can be turn them off by setting the MSBuild flag `EnableNETAnalyzers` to `false`.

### Old behavior

If the user compared two value types using `System.Object.ReferenceEquals`, they are boxed before they get passed to the method, which causes the method to return `false` even if they both represent the same instance of a value type.

### New behavior

The user will now see the CA2013 warning suggesting to instead use an appropriate equality operator, such as `==`.

### Reason for change

Using `System.Object.ReferenceEquals` to compare value types can lead to wrong results.

### Recommended action

Change the code to use an appropriate equality operator, such as `==`. This warning is not safe to suppress.

Refer to the documentation for rule CA2013 for a detailed explanation on when to expect this rule violation to be diagnosed.

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2013

### Category

- Core .NET libraries

### Affected APIs

[System.Object.ReferenceEquals](https://docs.microsoft.com/en-us/dotnet/api/system.object.referenceequals) when used to compare two value types.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by carlossanlop** [comment]
cc @buyaa-n @GrabYourPitchforks @jeffhandley

**Comment by jeffhandley** [comment]
LGTM
