### ISSUE TITLE
Keyboard shortcuts incorrect?

### ISSUE THREAD

**Issue by tonygreynolds** [dotnet/docs#19812]
Hello,

PR #18819 appears to have mixed up the keyboard commands and one of my students just spotted it.

On this page (https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio?tabs=csharp), in the "Run the app" and "Enhance the app" sections, it looks like the specified keyboard shortcuts are wrong (for Windows; dunno about VS for Mac or VSCode).

You can see the change in this diff (https://github.com/dotnet/docs/pull/18819/files#diff-c309a5b83770710ac4b63563ded67562).
Originally lines 78 and 104 specified F5.
Updated lines 76 and 100 specify Shift+F5, when they should say Ctrl+F5, since the former is to stop debugging.

Thanks,
Tony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET Core console application using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that!
