### ISSUE TITLE
Add docs for .NET 5.0 BinaryFormatter event source

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/docs#19810]
_Note to repo owners:_ As part of the [`BinaryFormatter` obsoletion strategy](https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), we introduced in .NET 5.0 an `EventSource` which allows apps to receive notification when objects are being serialized or deserialized using `BinaryFormatter`. The blurb below is a doc that describes this functionality and demonstrates how to hook it. Not sure where it would go - perhaps within the `BinaryFormatter` remarks section or as a sibling page to the API docs?

-----

## BinaryFormatter event source

Starting with .NET 5.0, [`BinaryFormatter`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) includes a built-in [`EventSource`](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventsource) that gives developers visibility into when an object serialization or deserialization is occurring. Apps can use [`EventListener`](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventlistener)-derived types to listen for these notifications and log them.

This functionality is not a substitute for a [`SerializationBinder`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.serializationbinder) or an [`ISerializationSurrogate`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iserializationsurrogate) and cannot be used to modify the data being serialized or deserialized. Rather, this eventing system is intended to provide insight into the types being serialized or deserialized. It can also be used to detect unintended calls into the `BinaryFormatter` infrastructure, such as those originating from third-party library code.

## Description of events

`BinaryFormatter`'s event source has the well-known name __`System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource`__. As of this writing, listeners may subscribe to 6 events.

### __SerializationStart__ event (id = `10`)

Raised when [`BinaryFormatter.Serialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.serialize) has been called and has started the serialization process. This is paired with the __SerializationEnd__ event. The __SerializationStart__ event can be called recursively if an object calls `BinaryFormatter.Serialize` within its own serialization routine.

This event does not contain a payload.

### __SerializationEnd__ event (id = `11`)

Raised when `BinaryFormatter.Serialize` has completed its work. Each occurrence of __SerializationEnd__ denotes the completion of the last unpaired __SerializationStart__ event.

This event does not contain a payload.

### __SerializingObject__ event (id = `12`)

Raised when `BinaryFormatter.Serialize` is in the process of serializing a non-primitive type. The `BinaryFormatter` infrastructure special-cases certain types (such as `string` and `int`) and will not raise this event when these types are encountered. This event will be raised for user-defined types and other types that `BinaryFormatter` does not natively understand.

This event may be raised zero or more times between __SerializationStart__ and __SerializationEnd__ events.

This event contains a payload with one argument.

* _typeName_ (`string`): The assembly-qualified name (see [`Type.AssemblyQualifiedName`](https://docs.microsoft.com/dotnet/api/system.type.assemblyqualifiedname)) of the type being serialized.

### __DeserializationStart__ event (id = `20`)

Raised when [`BinaryFormatter.Deserialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.deserialize) has been called and has started the deserialization process. This is paired with the __DeserializationEnd__ event. The __DeserializationStart__ event can be called recursively if an object calls `BinaryFormatter.Deserialize` within its own deserialization routine.

This event does not contain a payload.

### __DeserializationEnd__ event (id = `21`)

Raised when `BinaryFormatter.Deserialize` has completed its work. Each occurrence of __DeserializationEnd__ denotes the completion of the last unpaired __DeserializationStart__ event.

This event does not contain a payload.

### __DeserializingObject__ event (id = `22`)

Raised when `BinaryFormatter.Deserialize` is in the process of deserializing a non-primitive type. The `BinaryFormatter` infrastructure special-cases certain types (such as `string` and `int`) and will not raise this event when these types are encountered. This event will be raised for user-defined types and other types that `BinaryFormatter` does not natively understand.

This event may be raised zero or more times between __DeserializationStart__ and __DeserializationEnd__ events.

This event contains a payload with one argument.

* _typeName_ (`string`): The assembly-qualified name (see [`Type.AssemblyQualifiedName`](https://docs.microsoft.com/dotnet/api/system.type.assemblyqualifiedname)) of the type being deserialized.

### \[Advanced\] Subscribing to a subset of notifications

Listeners who wish to subscribe to only a subset of notifications can choose which keywords to enable.

* __Serialization__ = `(EventKeywords)1`: Raises the __SerializationStart__, __SerializationEnd__, and __SerializingObject__ events.
* __Deserialization__ = `(EventKeywords)2`: Raises the __DeserializationStart__, __DeserializationEnd__, and __DeserializingObject__ events.

If no keyword filters are provided during `EventListener` registration, all events will be raised.

See [the `EventKeywords` enum](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventkeywords) for more information.

## Sample code

The following code demonstrates:

- creating an `EventListener`-derived type that writes to `System.Console`,
- subscribing that listener to `BinaryFormatter`-produced notifications,
- serializing and deserializing a simple object graph using `BinaryFormatter`, and
- analyzing the events which have been raised.

```cs
using System;
using System.Diagnostics.Tracing;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace BinaryFormatterEventSample
{
    class Program
    {
        static EventListener _globalListener = null;

        static void Main(string[] args)
        {
            // First, set up the event listener.
            // Note: We assign it to a static field so that it doesn't get GCed.
            // We also provide a callback that subscribes this listener to all
            // events produced by the well-known BinaryFormatter source.

            _globalListener = new ConsoleEventListener();
            _globalListener.EventSourceCreated += (sender, args) =>
            {
                if (args.EventSource?.Name == "System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource")
                {
                    ((EventListener)sender).EnableEvents(args.EventSource, EventLevel.LogAlways);
                }
            };

            // Next, create the Person object and serialize it.

            Person originalPerson = new Person()
            {
                FirstName = "Logan",
                LastName = "Edwards",
                FavoriteBook = new Book()
                {
                    Title = "A Tale of Two Cities",
                    Author = "Charles Dickens",
                    Price = 10.25m
                }
            };

            byte[] serializedPerson = SerializePerson(originalPerson);

            // Finally, deserialize the Person object.

            Person rehydratedPerson = DeserializePerson(serializedPerson);

            Console.WriteLine($"Rehydrated person {rehydratedPerson.FirstName} {rehydratedPerson.LastName}");
            Console.WriteLine($"Favorite book: {rehydratedPerson.FavoriteBook.Title} by {rehydratedPerson.FavoriteBook.Author}, list price {rehydratedPerson.FavoriteBook.Price}");
        }

        private static byte[] SerializePerson(Person p)
        {
            MemoryStream memStream = new MemoryStream();
            BinaryFormatter formatter = new BinaryFormatter();
#pragma warning disable SYSLIB0011 // BinaryFormatter.Serialize is obsolete
            formatter.Serialize(memStream, p);
#pragma warning restore SYSLIB0011

            return memStream.ToArray();
        }

        private static Person DeserializePerson(byte[] serializedData)
        {
            MemoryStream memStream = new MemoryStream(serializedData);
            BinaryFormatter formatter = new BinaryFormatter();

#pragma warning disable SYSLIB0011 // Danger: BinaryFormatter.Deserialize is insecure for untrusted input
            return (Person)formatter.Deserialize(memStream);
#pragma warning restore SYSLIB0011
        }
    }

    [Serializable]
    public class Person
    {
        public string FirstName;
        public string LastName;
        public Book FavoriteBook;
    }

    [Serializable]
    public class Book
    {
        public string Title;
        public string Author;
        public decimal Price;
    }

    // A sample EventListener that writes data to System.Console.
    public class ConsoleEventListener : EventListener
    {
        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            base.OnEventWritten(eventData);

            Console.WriteLine($"Event {eventData.EventName} (id={eventData.EventId}) received.");
            if (eventData.PayloadNames != null)
            {
                for (int i = 0; i < eventData.PayloadNames.Count; i++)
                {
                    Console.WriteLine($"{eventData.PayloadNames[i]} = {eventData.Payload[i]}");
                }
            }
        }
    }
}
```

The output of this program will be:

```txt
Event SerializationStart (id=10) received.
Event SerializingObject (id=12) received.
typeName = BinaryFormatterEventSample.Person, BinaryFormatterEventSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Event SerializingObject (id=12) received.
typeName = BinaryFormatterEventSample.Book, BinaryFormatterEventSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Event SerializationStop (id=11) received.
Event DeserializationStart (id=20) received.
Event DeserializingObject (id=22) received.
typeName = BinaryFormatterEventSample.Person, BinaryFormatterEventSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Event DeserializingObject (id=22) received.
typeName = BinaryFormatterEventSample.Book, BinaryFormatterEventSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Event DeserializationStop (id=21) received.
Rehydrated person Logan Edwards
Favorite book: A Tale of Two Cities by Charles Dickens, list price 10.25
```

In this sample, the console-based `EventListener` logs that once serialization has started, instances of `Person` and `Book` are serialized, and then serialization completes. Similarly, once deserialization has started, instances of `Person` and `Book` are deserialized, and then deserialization completes.

The app then prints the values contained with the deserialized `Person` to demonstrate that the object did in fact serialize and deserialize properly.

## Further reading

For more information on using `EventListener` to receive `EventSource`-based notifications, see [the `EventListener` class](https://docs.microsoft.com/dotnet/api/system.diagnostics.tracing.eventlistener).

**Comment by gewarren** [comment]
I think this could either go in the Remarks section of the API docs, or in the conceptual docs with a link from the API docs. @tdykstra Is this your area?

**Comment by tdykstra** [comment]
If we had similar docs for other event sources I would put it with them but I don't see any place like that. My best guess is to put it next to the [BinaryFormatter security guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide) in the TOC.
