### ISSUE TITLE
Broken links to F# module references

### ISSUE THREAD

**Issue by objectx** [dotnet/docs#19835]
[Enter feedback here]

Link to module referrences seems to be broken.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0694330-a4e4-5a07-2b6b-8259b57e319a
* Version Independent ID: 71e9da59-27a1-6194-3a69-09b9d3a383d4
* Content: [Collection Types - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types)
* Content Source: [docs/fsharp/language-reference/fsharp-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/fsharp-collection-types.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
fixed by https://github.com/dotnet/docs/pull/20055

**Comment by cartermp** [comment]
@objectx in the meantime, you can browse here: https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections.html

**Comment by objectx** [comment]
@cartermp Thanks!
