### ISSUE TITLE
Installer-creation tools mentioned in the article

### ISSUE THREAD

**Issue by anadem** [dotnet/docs#19833]
This page does developers a disservice by recommending only Installshield for authoring installers. The Wix Toolset (https://wixtoolset.org/) is a better approach, and is also used by Microsoft's own products. (I have no relationship with wixtoolset but have used it happily for many years.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433b4c70-07c8-34c3-b567-22c80b71c5e2
* Version Independent ID: e3699917-899c-85fd-44f2-942b317cb8ff
* Content: [How to: Install and uninstall Windows services](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services)
* Content Source: [docs/framework/windows-services/how-to-install-and-uninstall-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/how-to-install-and-uninstall-services.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
@anadem Interestingly enough the link right after that suggestion takes you to info about WIX. I suspect it's just an over sight in this article when the WIX content was added. 

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
