### ISSUE TITLE
Add Blazor WebAssembly Startup content

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#19842]
Update the Startup doc with Blazor WebAssembly content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f78d94e-afb2-f0b0-6c54-aa2aca4e177d
* Version Independent ID: 8d8b1280-710e-1021-d59b-694e7c9be809
* Content: [App startup](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/app-startup)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/app-startup.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/app-startup.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by erjain** [comment]
The issue can be closed now.
