### ISSUE TITLE
у меня ошыбка в игре

### ISSUE THREAD

**Issue by bodaigra** [dotnet/docs#19840]
Assets\Scriptes\PlayerCntrl.cs(11,13): error CS0103: The name 'GetCompotent' does not exist in the current context

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCntrl : MonoBehaviour {

   public float speed = 20f;
   private Rigidbody2D rb;

   void Start () {
       rb = GetCompotent <Rigidbody2D> ();
   }

   void Update () {
       float moveX = Input.GetAxis ("Horizontal");
       rb.MovePosition (rb.position + Vector2.right * moveX * speed * Time.deltaTime);
   }
}
Вот код

**Comment by adegeo** [comment]
@bodaigra This repository is for .NET Documentation feedback and questions. Please use a Unity support forum.
