### ISSUE TITLE
A little translation issue in Chinese version

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#1985]
Hi,I wonder whether it is appropriate to create such a issue here.In this url:
https://docs.microsoft.com/zh-cn/dotnet/articles/csharp/getting-started/with-visual-studio

> 3.选择“确定” **** 按钮。

> 2.依次选择“生成”**** > “生成解决方案”****，编译此程序。

There are many asterisks which are not in the right position. They are supposed to bold the terms.

Actually, every pages under this url have the same issue:https://docs.microsoft.com/zh-cn/dotnet/articles/csharp/getting-started/

I hope you can fix it. Thanks.

**Comment by mairaw** [comment]
Hi @imba-tjd,

The right place to file this is in the Chinese docs repo: https://github.com/dotnet/docs.zh-cn/issues

 I'll move this to the other repo and close this one. Thanks!

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs.zh-cn #22](https://github.com/dotnet/docs.zh-cn/issues/22) via [**ZenHub**](https://www.zenhub.com/)
