### ISSUE TITLE
Storyboard.Target attached property not mentioned in storyboard overview

### ISSUE THREAD

**Issue by tonyhallett** [dotnet/docs#19865]
[Storyboard overview](https://github.com/dotnet/docs/blob/live/docs/framework/wpf/graphics-multimedia/storyboards-overview.md)
The attached property Storyboard.TargetName is mentioned but not Storyboard.Target which is useful when targeting a static resource.

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

**Comment by adegeo** [comment]
Moved to dotnet/docs-desktop#47
