### ISSUE TITLE
Not all triggerbase derivations mentioned as method of starting Storyboard

### ISSUE THREAD

**Issue by tonyhallett** [dotnet/docs#19862]
Table fails to mention other applicable TriggerBase derivations MultiDataTrigger and and MultiTrigger.
[link](https://github.com/dotnet/docs/blob/live/docs/framework/wpf/graphics-multimedia/storyboards-overview.md#how-to-apply-animations-with-a-storyboard)

Here is a MultiTrigger [example](https://docs.microsoft.com/en-us/dotnet/api/system.windows.multitrigger?view=netframework-4.7.2#examples) and a MultiDataTrigger [example](https://docs.microsoft.com/en-us/dotnet/api/system.windows.multidatatrigger?view=netframework-4.7.2#examples)

- [ ] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

**Comment by adegeo** [comment]
Moved to dotnet/docs-desktop#47
