### ISSUE TITLE
Advise use of a single options instance in a custom converter

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#19878]
See https://github.com/dotnet/runtime/issues/40072 and https://github.com/dotnet/runtime/issues/42167#issuecomment-691700983

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by layomia** [comment]
Another thing to avoid is passing numerous dynamically generated types to the serializer as this can lead to an `OutOfMemoryException`. An example of this can be found here - https://github.com/dotnet/aspnetcore/discussions/24230.
