### ISSUE TITLE
Requesting Extra Info About "CONSIDER adding a target for net461 when you're offering a netstandard2.0 target"

### ISSUE THREAD

**Issue by DrakeLambert** [dotnet/docs#19875]
I recently fixed an error I experienced when targeting a netstandard2.0 package from .NET 4.6.1 by adding a net461 target to the package. I don't know why this change fixed my error nor do I understand what the original error really was.

I am requesting more explanation be added to this section so that I may have a deeper understanding.

My original error was:

`System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=...' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.`

`System.ComponentModel.Annotations` is a package reference on the nuget package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by adegeo** [comment]
@DrakeLambert 

This error seems to be a can of worms. I did a quick web search and found https://github.com/dotnet/standard/issues/450 which shows there are all sorts of oddities regarding that error.

After reading through the article you made this issue about, I feel it's decent in it's explanation. It does call out there is a problem with 461 and using .NET Standard that you may end up running into and building directly for 461 fixes that. If your project is upgraded to 47 and uses the .NET Standard version, does the error also go away? If so, then you've hit the issue that was raised in the article.

I'm not sure what could be clarified ☹️ and I would venture a guess that the technical information about this problem won't really help someone completely know if they'll run into the problem. You just have to test for 461 if you are targeting .NET Standard with your library I guess. ☹️

**Comment by DrakeLambert** [comment]
@adegeo Thank you for the extra links. Given this issue really is a "can of worms", I can see why the author decided to keep this section brief.

I don't know enough about the exact issue, but I do wonder if it would be beneficial to include some link to an external resource. Of the links you gave, it seems like there are many separate issues and no "bug round up" page. That makes finding a good candidate for linking more difficult :/

**Comment by adegeo** [comment]
And I'm not sure either if any of the links I did find really clear anything up since the issue may be from something else. I'm going to close this issue as I don't think there is much we can do at this point that really adds any benefit without adding more confusion or possibly even misleading someone.
