### ISSUE TITLE
Missing example section in Discards article

### ISSUE THREAD

**Issue by z4ns4tsu** [dotnet/docs#19880]
The section on pattern matching mentions two uses of the discard, but only the use as a default condition in `switch` is actually presented with the usage with `is` missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for pointing this out @z4ns4tsu 

I've added it to our backlog to update when we next update this article.
