### ISSUE TITLE
ISO 8601

### ISSUE THREAD

**Issue by itthing** [dotnet/docs#19905]
[Can we please get an option under "s" Sortable for other ISO 8601 formats, such as when we only need the date?  The article makes it seem like there is only one ISO8601 format, yet the standard allows for different levels of detail and we as users need those other levels of detail. I know there is custom, but why not accomodate the ISO standard with more options?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52741095-f1fd-71b8-15f8-b526480f0d83
* Version Independent ID: 12b2c626-2479-1090-83fd-583c6d600ed8
* Content: [Standard date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings)
* Content Source: [docs/standard/base-types/standard-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by KalleOlaviNiemitalo** [comment]
Is this a request to improve the documentation by adding examples of custom date and time format strings that correspond to ISO 8601 formats? For example, document that you can use "yyyy'-'MM'-'dd" with InvariantCulture to get an ISO 8601 year-month-day date.

Or is this a request to define additional standard date and time format strings and make the .NET Runtime support them? For example, define "i" as a standard format string that results in an ISO 8601 year-month-day date.

(One could also define additional custom format specifiers for ISO 8601 purposes, such as a week of year, day of week as a digit, or day of year. <https://github.com/dotnet/runtime/issues/9364> discusses such formats. You don't seem to be requesting anything like that, though.)

**Comment by itthing** [comment]
> Is this a request to improve the documentation by adding examples of custom date and time format strings that correspond to ISO 8601 formats? For example, document that you can use "yyyy'-'MM'-'dd" with InvariantCulture to get an ISO 8601 year-month-day date.

No, I was able to use a custom format in the short term.  That's easy enough to figure out.
> 
> Or is this a request to define additional standard date and time format strings and make the .NET Runtime support them? For example, define "i" as a standard format string that results in an ISO 8601 year-month-day date.

I'd like to see an additional standard format or additional parameters for the /s option to take into account the various options within ISO8601.  I am not a coder, but my exposure to this is in using PowerApps & Power Automate, which is how I found this documentation. I'm not sure why ISO8601 needs to be "custom" when it is a very useful standard.

> 
> (One could also define additional custom format specifiers for ISO 8601 purposes, such as a week of year, day of week as a digit, or day of year. [dotnet/runtime#9364](https://github.com/dotnet/runtime/issues/9364) discusses such formats. You don't seem to be requesting anything like that, though.)

I don't need that, but perhaps others do. My needs right now are relatively simple.

**Comment by adegeo** [comment]
@itthing If I follow the conversation correctly, your request isn't to update the documentation, but for support for other ISO 8601 standard formats added. If so, the runtime repository linked to is where you should file a request. This repo is just documenting what is supported.

Please let me know if my assumption is correct. Cheers!

**Comment by KalleOlaviNiemitalo** [comment]
@itthing, are you using [Text function in Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-text#date-and-time-placeholders) to format the dates? That page mentions that `mm` means either the month or the minute, depending on nearby placeholders. In date and time format strings for .NET, [`mm`](https://docs.microsoft.com/dotnet/standard/base-types/custom-date-and-time-format-strings#mmSpecifier) always means the minute, never the month. It seems that Power Apps is using its own implementation of format strings, and if additional ISO 8601 formats were implemented in .NET, they might still not become available in Power Apps. The feature request might thus have to be filed in Power Apps specifically.

**Comment by adegeo** [comment]
Thanks for the help @KalleOlaviNiemitalo !!

**Comment by KalleOlaviNiemitalo** [comment]
On the other hand, [How to customize/format Date and Time values in a flow](https://support.microsoft.com/en-us/help/4534778/how-to-customize-format-date-and-time-values-in-a-flow) describes the `formatDateTime()` function of Power Automate and directly references the .NET documentation on format strings.

**Comment by itthing** [comment]
> @itthing, are you using [Text function in Power Apps](https://docs.microsoft.com/powerapps/maker/canvas-apps/functions/function-text#date-and-time-placeholders) to format the dates? That page mentions that `mm` means either the month or the minute, depending on nearby placeholders. In date and time format strings for .NET, [`mm`](https://docs.microsoft.com/dotnet/standard/base-types/custom-date-and-time-format-strings#mmSpecifier) always means the minute, never the month. It seems that Power Apps is using its own implementation of format strings, and if additional ISO 8601 formats were implemented in .NET, they might still not become available in Power Apps. The feature request might thus have to be filed in Power Apps specifically.

Yes, I'm using this to format the dates in Power Automate (my string manipulation is being done as part of a flow attached to a PowerApp). In practice, I had to use "MM" for month because "mm" yielded minutes.

The documentation I was using linked to the .NET documentation itself, which is how I wound up here.

**Comment by adegeo** [comment]
@itthing Hi! Can you please respond to my previous question? Thanks!

> @itthing If I follow the conversation correctly, your request isn't to update the documentation, but for support for other ISO 8601 standard formats added. If so, the runtime repository linked to is where you should file a request. This repo is just documenting what is supported.
>
> Please let me know if my assumption is correct. Cheers!

**Comment by itthing** [comment]
> @itthing If I follow the conversation correctly, your request isn't to update the documentation, but for support for other ISO 8601 standard formats added. If so, the runtime repository linked to is where you should file a request. This repo is just documenting what is supported.
> 
> Please let me know if my assumption is correct. Cheers!

Yes, I would like support for other ISO 8601 standard formats. 

Are you saying I should go to https://github.com/dotnet/runtime/issues/9364?

I believe I understand how to use custom formats, but my point is that ISO 8601 is not just one format and that one option that implements one format of 8601 isn't enough, considering a date-only 8601 format could be argued to be just as useful. I want to get that point across to Microsoft in hopes of making ISO 8601 formats a format that doesn't always need to be "custom". I envision lots of us would find an ISO 8601 date format useful, as well as an ISO 8601 date + time format. I'm trying to get away from US-format dates as much as possible, as ISO 8601 dates are more useful yet easy enough to understand for those from the US, yet aren't easily confused with other date formats.

**Comment by adegeo** [comment]
Gotcha. Yeah, if it's a change within .NET itself, I think the runtime repository is the place to go. It does seem like there is that issue you linked to and another one referenced in that issue. We can't really do anything over here, since this is purely documentation. The best bet is to get more dialog and more users talking about your suggestion, probably on that other issue you linked to. Considering that the user filed the issue in 2017 and no one else has commented on it, it doesn't seem like it's a big pain point for customers. So the more talking you get on that issue, the better.

I'm going to close this issue since there is nothing we can do here in docs about it. ☹️
