### ISSUE TITLE
Statements not skipped on every iteration

### ISSUE THREAD

**Issue by jdschwartz87** [dotnet/docs#19903]
"...the statements between continue and the end of the for body are skipped" but not for every iteration loop. On the final 2 iterations of the for loop, when i == 9 and i == 10, the statements are not skipped. The value of i is printed to the console. This document doesn't specify this detail incorrectly, it just may be helpful to clarify this fact. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5b436f-bd9b-e6c5-9859-f71cf9ee71bc
* Version Independent ID: f384b21d-5bee-6a14-d0c8-aadf61691c1e
* Content: [continue statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/continue)
* Content Source: [docs/csharp/language-reference/keywords/continue.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/continue.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @jdschwartz87 

I've added this to the backlog for when we next update this article.
