### ISSUE TITLE
Bug in Sample code in creating-satellite-assemblies-for-desktop-apps.md

### ISSUE THREAD

**Issue by zowazHC5** [dotnet/docs#19909]
[Enter feedback here]

The example under 'Satellite Assemblies: An Example' is incorrect. The instructions say to create resx (or text) files named Greeting.resx, etc.

The C# source creates a resource manager with:

ResourceManager rm = new ResourceManager("Example.Greetings",
                                                  typeof(Example).Assembly);

The file name 'Example.Greetings' should be 'Example.Greeting', e.g.

ResourceManager rm = new ResourceManager("Example.Greeting",
                                                  typeof(Example).Assembly);

Alternatively, you can change the resx file names to Greetings.resx, Greetings.fr-FR.resx, etc. to match the ResourceManager constructor.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3ff457-56ee-b368-af21-d37bdea825b2
* Version Independent ID: 96d617db-6ad2-594e-643a-4006188de390
* Content: [Creating Satellite Assemblies for Desktop Apps](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-satellite-assemblies-for-desktop-apps)
* Content Source: [docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md](https://github.com/dotnet/docs/blob/master/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
