### ISSUE TITLE
Remove wrench/unwritten topics from the published docs

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1990]
We have a few "wrench" topics (such as https://docs.microsoft.com/en-us/dotnet/articles/core/versions/servicing) or some unwritten topics like https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/.

We need to:
1 - Remove the topics from the repo
2 - Redirect them to a similar topic or a generic place a similar one cannot be found
3 - Make sure we have issues opened tracking the topics we were planning to do (some of them have links to the issue already)
4 - Remove them from the TOC file(s)

The F# tutorials one could probably be transformed in just a TOC node without content associated with it for now.

**Comment by BillWagner** [comment]
I'd recommend commenting out the 'wrench' topics in the TOC instead of deleting them. That way, community members who have cloned the repo would see the roadmap, but it would not affect other readers.

**Comment by mairaw** [comment]
If we do that, then the original issue reported by @dend would still exist: wrench topics are then part of the PDF and offline books, no?

**Comment by mairaw** [comment]
Ah do you mean @BillWagner, just comment out the entry in the TOC like Tom did in his PR (https://github.com/aspnet/Docs/pull/3264)? If so, yes, I agree.

**Comment by GuardRex** [comment]
Looks like the plan is ...
* Metadata redirects in the topics; topics remain
* Comment out in TOC
* Confirm open issue exists for each
