### ISSUE TITLE
Explain Exception Filters

### ISSUE THREAD

**Issue by PeterHuberSg** [dotnet/docs#19900]
Your documentation about `try catch` needs to be updated with Exception Filters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acadfa1a-becb-3492-8ca0-7cd581c4cd84
* Version Independent ID: 1432132f-4db6-84b7-0ba7-fe7f44e6f45c
* Content: [Handling and throwing exceptions in .NET](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/)
* Content Source: [docs/standard/exceptions/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/index.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. We'll add that the next time we update the article.

**Comment by Youssef1313** [comment]
There is an article in the See also section about user-filtered exception handlers, but it's currently VB only.

I think that article should be updated to be C# too, and avoid having duplicated content in 2 different places.

**Comment by tdykstra** [comment]
@Youssef1313 Thanks for the suggestion.  I self-assigned this issue, but you're welcome to it if you want to take it.
