### ISSUE TITLE
Code snippet throws ArgumentNullException for a positive scenario

### ISSUE THREAD

**Issue by akashmanoj213** [dotnet/docs#19919]
The code snippet for **Default Literal** section uses a **Display** method to show the output of the **InitializeArray** method. This works fine for all the examples mentioned in the code snippet however, the examples fail to test the path when length parameter for InitializeArray is negative. As per the code in InitializeArray, the method should return a **default value** when length is negative. However, since the default value for an **array is null**, the method returns a null value which then causes the Display method to throw a **System.ArgumentNullException**.

The case I used was `Display(InitializeArray<int>(-1));`.

I propose the following change to Display method to handle this scenario:
`static void Display<T>(T[] values) =>Console.WriteLine(values == null ? "null" : $"[ {string.Join(", ", values)} ]");`
The InitializeArray method which handles a negative length parameter by returning a default value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08344c62-6194-1057-e409-35d65fcab2cd
* Version Independent ID: 53f08a66-f8b6-7953-d260-e52694934613
* Content: [default value expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default)
* Content Source: [docs/csharp/language-reference/operators/default.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/default.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
I think the `InitializeArray` method should be corrected in the following way (yes, that removes one usage example of `default`, but there are three more in the snippet):
```csharp
    if (length < 0)
    {
        throw new ArgumentOutOfRangeException(nameof(length), "Array length must be nonnegative.");
    }
```

The name of the method implies that the method, if returns, produces an initialized array.

**Comment by akash-manoj** [comment]
Yes, that makes sense. So how do I actually get this change into the documentation? This is the first time that I am contributing and from reading the guide it seems like I need to get this approved and then raise a pull request with the above changes ?

**Comment by BillWagner** [comment]
> So how do I actually get this change into the documentation? This is the first time that I am contributing and from reading the guide it seems like I need to get this approved and then raise a pull request with the above changes ?

@akash-manoj @akashmanoj213  I've read through the conversation, and I'll accept a PR with the change described above.If you'd like to make the change, I'll watch for it. I can assign this issue to you, if you'd like.

**Comment by akashmanoj213** [comment]
@BillWagner , sure, you can assign it to @akashmanoj213 . I will raise a PR with the above changes.
