### ISSUE TITLE
"core" in distribution package names in .NET 5

### ISSUE THREAD

**Issue by omajid** [dotnet/docs#19930]
The [current distribution packaging guide](https://github.com/dotnet/docs/blame/master/docs/core/distribution-packaging.md#L113) includes packages with the "core" suffix: "aspnetcore-runtime-X.Y" and "aspnetcore-targeting-pack-X.Y". With the rename from ".NET Core" to ".NET" in the 5.0 timeframe, should these docs be updated to drop the "core"? The package names would become just "aspnet-runtime-X.Y" and "aspnet-targeting-pack-X.Y"?

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET 5
- [ ] .NET Framework
- [ ] .NET Standard

cc @tmds @dagood

**Comment by dagood** [comment]
As of 5.0 preview 7, the Microsoft deb/rpm aspnetcore packages still have "core" in the name:

```
aspnetcore-runtime-5.0.0-preview.7.20365.19-x64.deb
aspnetcore-targeting-pack-5.0.0-preview.7.20365.19.deb
```

It's also still called ASP.NET Core on [the download site](https://dotnet.microsoft.com/download/dotnet/5.0):

> Included runtimes
> .NET Runtime 5.0.0-preview.7.20364.11
> ASP.NET Core Runtime 5.0.0-preview.7.20364.11
> Desktop Runtime 5.0.0-preview.7.20364.11

@leecow @nakarnam @wtgodbe @NikolaMilosavljevic do you know if this is going to change for 5.0?
I'm not able to find any discussion about ASP.NET Core vs. the ".NET Core" => ".NET" rename.

**Comment by davidfowl** [comment]
There's no plan to change asp.net core to asp.net.

cc @glennc @DamianEdwards @LadyNaggaga

**Comment by omajid** [comment]
Thanks, that resolves my concerns.
