### ISSUE TITLE
Consolidate "What is Docker"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19935]
https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/container-docker-introduction/docker-defined.md

https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/what-is-docker.md

Related to #19929

**Comment by IEvangelist** [comment]
Closing this issue, justification noted here: https://github.com/dotnet/docs/pull/25630#issuecomment-900336524
