### ISSUE TITLE
Consolidate "State and data in Docker applications"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19932]
https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/docker-application-state-data.md
https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/state-and-data-in-docker-applications.md

These two articles seems to be nearly identical. I think they need to be consolidated into one.

Related to https://github.com/dotnet/docs/pull/19929

**Comment by Youssef1313** [comment]
Pinging @sughosneo in case you're interested to work on this. (Also #19933, #19934, and #19935). Each of these issues states an article that's duplicated in two places, and each article file was updated independently. The good news is that the articles haven't diverged that much. They're "mostly" the same.

**Comment by IEvangelist** [comment]
Closing this issue, justification noted here: https://github.com/dotnet/docs/pull/25630#issuecomment-900336524
