### ISSUE TITLE
API reference for Vector<T> missing

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1993]
The API reference for [`System.​Numerics.Vector<​T>`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector-1?view=netcore-1.1) and [`System.​Numerics.Vector`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector?view=netcore-1.1) seems to be missing all content. The API is there, but there aren't any descriptions.

Few other, potentially relevant observations:

* Other `System.​Numerics` types (including e.g. [`Vector2`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector2?view=netcore-1.1)) seem to be fine.
* The types seem to be present only on .Net Core, even though they are actually supported on .Net Framework.
* When I select .Net Framework in the dropdown, a message shows saying:

   > Liquid error: Can't find the localized string disclaimer.moniker for template Reference.

* Google offers two different MSDN pages when searching for e.g. "vector t count":

   * https://msdn.microsoft.com/en-us/library/dn877911(v=vs.111).aspx, which doesn't have any site navigation (doesn't show up in TOC, does not have breadcrumbs). It links to https://msdn.microsoft.com/en-us/library/system.numerics(v=vs.111).aspx as its namespace.
   * https://msdn.microsoft.com/en-us/library/mt598437(v=vs.111).aspx, which seems to work fine. It links to https://msdn.microsoft.com/en-us/library/mt598257(v=vs.111).aspx as its namespace.

**Comment by mairaw** [comment]
Yes, the content that was in the additional libraries section of our docs needs to be migrated here too:
https://msdn.microsoft.com/en-us/library/mt573284(v=vs.110).aspx

Only what was part of the .NET Framework Class library was migrated initially.

**Comment by mairaw** [comment]
Opened internal bug (#979781) to track this migration
