### ISSUE TITLE
Consolidate "Docker containers, images, and registries"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#19933]
https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/container-docker-introduction/docker-containers-images-registries.md

https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/docker-containers-images-and-registries.md

Related to #19929

**Comment by IEvangelist** [comment]
Closing this issue, justification noted here: https://github.com/dotnet/docs/pull/25630#issuecomment-900336524
