### ISSUE TITLE
Spell-check underlines in figure for article "Implementing API Gateways with Ocelot"

### ISSUE THREAD

**Issue by micahswitzer** [dotnet/docs#19943]
Figure 6-33 has text with spell-check underlines on them. I assume this is unwanted.

Relevant section: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot#using-a-single-docker-container-image-to-run-multiple-different-api-gateway--bff-container-types

Direct link to the image:
![Figure 6-33](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/media/implement-api-gateways-with-ocelot/reusing-single-ocelot-docker-image.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @micahswitzer, we are closing this issue as of now. If you have any further questions, please feel free to reopen it.
You may want to check out the PR #19980, where we have provided information information related to `Ocelot` version >= 16.

Thank you.

**Comment by nishanil** [comment]
Reopening this. The original issue related to red squiggles in the image. We can fix that!
