### ISSUE TITLE
API documentation for dynamically generating classes at runtime.

### ISSUE THREAD

**Issue by kieronlanning** [dotnet/docs#19955]
Are there any examples of building C# classes using this API on a statement by statement basis?

I'm dynamically building several large classes, and while it works there's an awful lot of string concatenation and they all end up generating a syntax tree via `CSharpSyntaxTree.ParseText`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af3ae43-b958-0576-168e-539936d2ba81
* Version Independent ID: 6a1490ae-78b2-d8ba-07f1-df1c22f7a830
* Content: [Use the .NET Compiler Platform SDK syntax model](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/work-with-syntax)
* Content Source: [docs/csharp/roslyn-sdk/work-with-syntax.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/work-with-syntax.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@kieronlanning 

Thanks for writing this. To be honest, when I'm writing an analyzer or refactoring that generates code, I create strings and use `ParseText()` as well. It's been the most productive way for me.

adding @jmarolf @sharwell in case they have more insight.

**Comment by jmarolf** [comment]
I recommend looking at http://roslynquoter.azurewebsites.net/ if you want to see how to generate syntax without using `CSharpSyntaxTree.ParseText`

**Comment by svick** [comment]
@jmarolf I agree that RoslynQuoter is a very useful tool. Do you think it should be linked from this article?

**Comment by kieronlanning** [comment]
@jmarolf That's exceptional. Thankyou!

**Comment by BillWagner** [comment]
We should update this article with the link @jmarolf mentions in https://github.com/dotnet/docs/issues/19955#issuecomment-671978548
