### ISSUE TITLE
What do the asterisks mean in the list of .NET Framework versions?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#19960]
The descriptions of [.NET Framework 3.5](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-35) and [.NET Framework 3.0](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-30) show asterisks next to some versions of Windows. What do the asterisks mean? I can't find an explanation when I search for "*" or "asterisk" on the page.

> ➕ Windows Server, version 1803*  
> ➕ Windows Server, version 1709*  
> ➕ 2016*  
> ➕ 2012 R2*  
> ➕ 2012*  
>
> ✔️2008 R2 SP1*  
>
> ➕ 2008 SP2  
> ➕ 2003

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework & Windows OS versions](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@KalleOlaviNiemitalo Thanks for bringing this up. Looking at an older version of the file, the asterisk means:

.NET Framework must be enabled on this operating system through Control Panel (for Windows) or the Server Manager (for Windows Server).

This should be re-added to the article.

**Comment by KalleOlaviNiemitalo** [comment]
Currently, the page also says:

> * The check mark icon ✔️ denotes OS versions on which .NET Framework is installed but must be enabled in Control Panel (for Windows) or through the Server Manager (for Windows Server).
> * The plus sign icon ➕ denotes OS versions on which .NET Framework doesn't come installed but can be installed.

Does the asterisk then mean the same thing as the check mark icon ✔️? The page lists other versions of Windows with both an asterisk and a plus sign icon ➕.

**Comment by KalleOlaviNiemitalo** [comment]
Or does it work like this:

|Icons|Meaning|
|---|---|
|✔️|Included in Windows and enabled by default|
|✔️*|Included in Windows but disabled by default; use Control Panel or Server Manager to enable|
|➕|Optional download from Windows Update or Download Center|
|➕*|What's that? 😮|

**Comment by gewarren** [comment]
Yes, I think that this text is actually incorrect: "The check mark icon ✔️ denotes OS versions on which .NET Framework is installed but must be enabled in Control Panel (for Windows) or through the Server Manager (for Windows Server)".

It should just be "The check mark icon ✔️ denotes OS versions on which .NET Framework is installed". For the ➕ OS versions, you have to install .NET Framework manually, and then for the * versions, there's an additional step of enabling it.
