### ISSUE TITLE
Uri Unc path recognition was changed in 5.0

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/docs#19966]
## Uri Unc path recognition was changed in 5.0

Uri now recognizes strings starting with two forward slashes as UNC on Unix to make behavior consistent across platforms.
Changed in dotnet/runtime#35050

### Version introduced

Net 5.0

### Old behavior

Input | Windows | Unix
-- | -- | --
\\\\foo | UNC | UNC
//foo | UNC | Absolute file path
file://\\\\foo | UNC | UNC
file:////foo | UNC | UNC

### New behavior

Paths starting with two forward slashes are now recognized as UNC on Unix as well.

Properties now behave according to Unc semantics
1. `Uri.IsUnc` returns true

2. Backslashes in the path are replaced with forward-slashes
- `//foo\bar` => `//foo/bar`

3. `Uri.LocalPath` does not percent-encode characters
- `//foo/\uFFF0` stays `//foo/\uFFF0` instead of being converted to `//foo/%EF%BF%B0`

### Reason for change

Make behavior more intuitive and consistent across platforms.

### Recommended action

- Document the change

### Category

- Core .NET libraries

### Affected APIs

Properties on Uris starting with two forward slashes on Unix systems.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@mihazupan The recommended action is for the developer - what is their recommended action, not Microsoft's. Can you help describe any changes they'd need to make in their code?
