### ISSUE TITLE
dotnet publish with PublishProfile example does not work

### ISSUE THREAD

**Issue by mheptinstall** [dotnet/docs#19961]
The example under the [MSBuild](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild) heading does not work.

Executing the command `dotnet publish -p:PublishProfile=FolderProfile` does not perform a publish using the settings contained in the FolderProfile.pubxml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See the related issue https://github.com/dotnet/docs/issues/19677 and the note about the PublishProfileFullPath property at the end of the MSBuild section.

**Comment by mheptinstall** [comment]
This appears to be SDK version specific. 

Using the latest .NET 3.1.401 SDK then the command `dotnet publish -p:PublishProfile=FolderProfile` works as expected.

I could not get this to work even when using `PublishProfileFullPath` with these installed as part of Visual Studio 2017 15.9.26:

- Microsoft .NET Core SDK 2.1.516 (x64)
- Microsoft .NET Core SDK 2.1.514 (x64)
- Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core

See https://github.com/dotnet/sdk/issues/12870 which suggests this applies from SDK 3.1

**Comment by tdykstra** [comment]
Thanks for following up, I'm updating the article.

**Comment by mrlife** [comment]
@tdykstra @BillWagner I'm seeing this exact issue in an ASP.NET Core 5 project. Are the docs correct?

This is the command I run in the project directory:

```
dotnet publish -p:PublishProfile=publish-profile
```

These are the .NET SDKs installed:

> 3.1.409 [/usr/local/share/dotnet/sdk]
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

**Comment by tdykstra** [comment]
Is your .pubxml file in the project directory? If you created it in VS it'll be in Properties/PublishProfiles, and if the file is named FolderProfile.pubxml, the command would be:

```
dotnet publish -p:PublishProfile=Properties\PublishProfiles\FolderProfile
```

**Comment by mrlife** [comment]
Hi @tdykstra, yes, it was created by VS for Mac and is in `Properties/PublishProfiles`. With the command you have there, I still get the same result as before, which is it is published to the project's `bin/Debug` folder.

**Comment by tdykstra** [comment]
What happens if you put something like `bin\Release\net5.0\publish\` instead of `artifact\` in `<PublishDir>`?

**Comment by tdykstra** [comment]
Or more likely, what if you rename the file to get rid of the embedded space in the file name?

**Comment by tdykstra** [comment]
Please disregard my last two comments, I was confusing your issue with that of the original creator of the dotnet/sdk issue you linked to. Can you provide the contents of your .pubxml file?

**Comment by mrlife** [comment]
@tdykstra Thank you, yes, here is the .pubxml:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <EnvironmentName>Staging</EnvironmentName>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>AnyCPU</LastUsedPlatform>
    <publishUrl>/Volumes/remote-server-path-to-folder</publishUrl>
    <DeleteExistingFiles>true</DeleteExistingFiles>
    <TargetFramework>net5.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <_IsPortable>true</_IsPortable>
  </PropertyGroup>
</Project>
```

**Comment by tdykstra** [comment]
@adegeo Can you help with this?

**Comment by adegeo** [comment]
I would ask on the SDK github again. I commented on the linked issue (someone else is also reporting it's still not working) that a new issue should be opened if there is still a problem with a newer SDK.
