### ISSUE TITLE
Description in the special Tags dont appear indocumentation

### ISSUE THREAD

**Issue by rakeshmotghare** [dotnet/docs#19976]
Why XML documentation tags don't appear in Controller_XmlDocument.xml file under the bin folder. None of the text written in XML comment tags except summary, param and returns tag appears in the XML document file. ApiDescriptions under description namespace don't have those tags. Maybe I am doing something wrong, but I didn't find any help anywhere with the issue I am facing. Please help.

namespace System.Web.Http.Description
{
    //
    // Summary:
    //     Defines the interface for getting a collection of System.Web.Http.Description.ApiDescription.
    public interface IApiExplorer
    {
        //
        // Summary:
        //     Gets the API descriptions.
        Collection<ApiDescription> ApiDescriptions { get; }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5aa865-b9d2-e977-a272-3886aa0a1111
* Version Independent ID: 353b1c44-b90a-e5cc-a193-7b42ec714290
* Content: [Recommended tags for documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)
* Content Source: [docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
In the sample you provided, you are not using triple slash comments, nor XML tags.

It should be:

```csharp
namespace System.Web.Http.Description
{
    /// <summary>
    /// Defines the interface for getting a collection of <see cref="System.Web.Http.Description.ApiDescription">.
    /// </summary>
    public interface IApiExplorer
    {
        /// <summary>
        /// Gets the API descriptions.
        /// </summary>
        Collection ApiDescriptions { get; } // Consider using a generic collection (Collection<ApiDescription>)
    }
}
```

**Comment by BillWagner** [comment]
Hello @rakeshmotghare 

I agree with @Youssef1313 's suggestion. That should fix the situation.

I'll close this. You can reopen with more details if that doesn't help the situation.
