### ISSUE TITLE
Write a document clarifying what .NET 5 is

### ISSUE THREAD

**Issue by davidfowl** [dotnet/docs#19979]
**Help us make content visible**
We don't have a document that clarifies what .NET 5 is and what is in it. This information is scattered in a couple of blog posts but there's no coherent article about it.

**Describe the new article**

- The article is needed because lots of people are under the impression that .NET 5 is compatible with .NET Framework 4.8 and thus think it will contain things like webforms, workflow, wcf server etc.
- What is .NET 5?
  - What about .NET Standard?
  - Compatibility matrix of frameworks (set of frameworks that work and don't where, WCF, WebForms, WinForms, Workflow etc)
  - Naming of ASP.NET Core and EntityFramework Core (still has the Core suffix)
  - Target framework compatibility (it's a successor to .NET Core, not .NET Framework) 

- https://devblogs.microsoft.com/dotnet/introducing-net-5/
- https://visualstudiomagazine.com/blogs/data-driver/2019/05/net-5-wcf.aspx
- https://stackoverflow.com/questions/40955459/is-net-core-net-framework-5

**Comment by Youssef1313** [comment]
I would like to see a section about mobile app development with .NET 5 too.

**Comment by welly87** [comment]
I think @migueldeicaza explain really awesome in [his uno presentation](https://youtu.be/acryVgY0O3E?t=959). It's explain the journey of .NET

Not sure if that's still valid. 

What i want to know is do we support 

1. WPF on Mac? Or we still use Xamarin?
2. How about webassembly, blazor etc?
3. F# future?
4. Polygot Programming .NET? Sort of like GraalVM? Is that also the aim?


I think that's what interesting to me till now. Overall it's a good stuff. Have been waiting for this Unified moment in .NET world. 

I working on XBAP, Silverlight, and other "stuff" before. :) Looking forward for the movement on lots of open source server side or Big Data platform using .NET 5

Cheers

**Comment by TeddyAlbina** [comment]
I think it's time to discriminate packages in nuget between Legacy Framework and .NET.

**Comment by davidfowl** [comment]
> I think it's time to discriminate packages in nuget between Legacy Framework and .NET.

That's been part of nuget since the beginning, it's called a target framework. Now nuget could do a better job about allowing filtering based on that compatibility.

**Comment by welly87** [comment]
@davidfowl is there any plan on VS for Mac to catch Windows VS version? Is that on the roadmap?

**Comment by welly87** [comment]
another one about c/c++ interoperability. I like the C++/CLI approach before we can just compile and call libs from C# with object oriented way

is this possible? @davidfowl

**Comment by davidfowl** [comment]
@welly87 the intent of this issue was to give feedback on the above doc proposal for .NET 5 (which is almost finished), not to discuss features or ask general questions about .NET as a whole.

**Comment by welly87** [comment]
@davidfowl ah, i'm really sorry for this. I will remove my previous comments then. 

Is there any place where i can put request or suggestion for .NET 5.0++. In [Energistics](https://www.energistics.org/witsml-developers-users/) we have lots of needs as lots of O&G running on .NET/Azure. 

Thanks

**Comment by davidfowl** [comment]
https://github.com/dotnet/runtime/discussions

**Comment by YairHalberstadt** [comment]
Various features described in those blog posts about .Net 5 have been dropped or pushed off (java interop? ,aot?). This should be clarified along with the future pipeline for these features.

**Comment by eulvik** [comment]
I would like to know how multi-platform development will be handled. I understand there will be a compatibility matrix with this overview, but will that matrix be implemented in nuget? Meaning if I mark a project as targeting linux and windows, will I still be able to install platform specific nuget packages.

**Comment by alefranz** [comment]
Spell out the support policy and the implications of not being LTS

e.g. if you adopt .NET 5 you have to plan to do the work to move to 5.1 by date X and then upgrade to 6 by date Y

This is quite a change for who is coming from framework so I think it needs to be highlighted to avoid surprises

**Comment by deanvr** [comment]
Does .net 5 = still follow the architectural layout of framework/standard/core e.g. would you mentioned .net core when speaking in the context of .net 5 and is C# 8 the go to language.
