### ISSUE TITLE
Change dependabot cadence to weekly

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#19973]
Now that we've caught up on the upgrades, I propose that we change the cadence when dependabot runs from daily to weekly.

We won't miss important updates, and we will have less noise in PRs.

Thoughts?

**Comment by mairaw** [comment]
My two cents... I’ve done the same for my projects  since the daily noise was a distraction after all the updates were done

**Comment by Youssef1313** [comment]
What about adding an auto-merge label for dependabot PR after they pass CI?

**Comment by SeanKilleen** [comment]
Pinging @BillWagner because it appears this cadence is indeed now weekly and this can likely be closed.
