### ISSUE TITLE
vs code & omnisharp: the sdk 'microsoft.net.sdk' specified could not be found ubuntu

### ISSUE THREAD

**Issue by Mahdi-Safari** [dotnet/docs#20007]
it should be mentioned that in Linux dists when you use vs code and omnisharp you should add
export MSBuildSDKsPath="/usr/share/dotnet/sdk/$(dotnet --version)/Sdks"
to you ~/.bashrc so then omnisharp know where is your sdk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET Core console application using Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
According to https://github.com/OmniSharp/omnisharp-vscode/issues/1727#issuecomment-323749402 this should be automatic:

>OmniSharp will attempt to locate the .NET Core SDK for your project using the "dotnet" that is on the path and set the "MSBuildSdksPath" to the appropriate folder under that.

In the event that doesn't work, the recommendation is to create an "omnisharp.json" file in your project folder to set MSBuildSdksPath, rather than an environment variable.
