### ISSUE TITLE
System.IO APIs throw exceptions for invalid paths only when used, not when normalizing

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20004]
## System.IO APIs throw exceptions for invalid paths only when used, not when normalizing

See https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek
See https://github.com/dotnet/runtime/issues/38487#issuecomment-650665737

I'll let a product team member writes this in a more organized way.

### Version introduced

.NET Core 2.1

### Old behavior

System.IO APIs used to throw exceptions for invalid paths when normalizing a path.

### New behavior

System.IO APIs are no longer throwing exceptions when normalizing a path. They only throw exceptions when *using* the path.

### Reason for change

Leaving this to the product team to write.

### Recommended action

Leaving this to the product team to write.

### Category

- Core .NET libraries

### Affected APIs

I don't have a complete list of the affected APIs.

### Note

The API reference (for example, for [FileInfo ctor](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=netcore-3.1)) is outdated. It states that it will throw an exception for invalid paths.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Youssef1313** [comment]
@gewarren, Do you know who can give more information on this?

**Comment by gewarren** [comment]
@carlossanlop and @Jozkee are listed as the owners.

**Comment by carlossanlop** [comment]
This is by design. If the user wants to manipulate made up paths, they should be able to. But once you make a call to the OS, that's when the exception should be thrown, since the path did not exist.

This is explained in Jeremy Kuhne's blog when the feature was announced:

> Exceptions for "bad" paths are thrown when used, not when normalizing (as we can't know what is "valid" without using them)

Exceptions for "bad" paths are thrown when used, not when normalizing (as we can't know what is "valid" without using them)

**Comment by gewarren** [comment]
@carlossanlop It might be by design, but it seems like we should document it as a breaking change?

**Comment by Youssef1313** [comment]
@carlossanlop, This issue is about missing documentation for the breaking change, and outdated API reference.

**Comment by Youssef1313** [comment]
@gewarren Can you please re-open so this doesn't get missed?

Pinging @carlossanlop @Jozkee

**Comment by carlossanlop** [comment]
> @carlossanlop It might be by design, but it seems like we should document it as a breaking change?

Yes, we need to document the breaking change, @gewarren.

We should also edit the documentation of Path APIs that have an exception when detecting invalid chars, and make sure to indicate they only throw in .NET Framework.
