### ISSUE TITLE
How to get generated assembly name?

### ISSUE THREAD

**Issue by WenyunZou** [dotnet/docs#20002]
Hi,

As I found no clues from the document, I'd really like your help.

**ProjectA** is a C# classic library project, whose project references include **ProjectB**. The output type of them both is 'assembly'. Say **a.dll** is compiled from A and **b.dll** is compiled from B.

By **dotnet build projectA**, I will get multiple assemblies in the output directory. Is there a way that I can distinguish which projects are they compiled from and get **a.dll** exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
I don't understand the question. If you know that ProjectA produces a.dll and ProjectB produces b.dll how is it that you can't distinguish which project a.dll or b.dll is compiled from?

**Comment by WenyunZou** [comment]
Thank you for your reply!

Sorry for not making it clear.  What I mean is that what if I don't know which produces which and just get a couple of files, how to distinguish them.

I just found that Microsoft.Build and Microsoft.Build.Locator may help to get 'AssemblyName' from a project. 

Thank you again!
