### ISSUE TITLE
Comparing ValueObject with Proxy of ValueObject from DBContext

### ISSUE THREAD

**Issue by magarbikram** [dotnet/docs#20010]
I was trying to compare a ValueObject with ValueObject from DBContext during unit test. The equality operator is not working is this correct?

Address address = Address.From(...);
Address shippingAddress = orderRepository.GetById(123).ShippingAddress;
Assert.Equal(address, shippingAddress), didn't pass though all the properties are same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @magarbikram, thank you for pointing that out. 

You may want to refer #7477 for the ongoing discussion on this topic.

**Comment by sughosneo** [comment]
We have also updated our reference application [`eShopOnContainers`](https://github.com/dotnet-architecture/eShopOnContainers/commit/921de69418e3e980bea1bf69c2c72a2cf90b50e2). Please refer the `dev` branch to take the latest. 

I am closing this issue as of now. If you have any further questions, please feel free to reopen it.
