### ISSUE TITLE
Errors in the struct example

### ISSUE THREAD

**Issue by Tschouns** [dotnet/docs#20015]
Hi

I believe there are some errors in the code example for structs (struct TwoDPoint):

1)
In the ctor x is assigned to both X and Y.

2)
The implementation of GetHashCode is simply "return X ^ Y;". This will produce the same hash code when X and Y are swapped which (unless X == Y) is wrong and inconsistent with the behaviour of Equals.
In the class examples this problem is solved by multiplying either component by a fixed number (e.g. "return X * 0x00010000 + Y;") which will probaly work fine in practice. Though, it might in theory produce some bad results due to possible overflows. Alternatively, one could bitwise rotate either X or Y by a number of bits.

It might actually be helpful to highlight the problem of "combining hash codes into one properly" in the article. My suspicion is that this is a very common mistake; I've seen it many times. Also it can cause some nasty bugs...

Other than that, I think the article is very helpful!

Thanks,
Jonas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95b738e-a319-8947-c098-692068c24b9c
* Version Independent ID: 227a6999-9add-4a0a-98cb-c0c6624d6089
* Content: [How to define value equality for a type - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Tschouns 

I've added this to our backlog for the .NET 5.0 release. When we address this issue, we should also update this article for `record` types.

**Comment by Tschouns** [comment]
Great, thanks Bill.
