### ISSUE TITLE
Ref not required at call site for COM

### ISSUE THREAD

**Issue by billybednar** [dotnet/docs#20020]
Consider noting that COM is an exception to rule that ref is required at the call site when using ref parameters. I was surprised when I first encountered the lack of an error in this case and could not find any explanation in the documentation or elsewhere. 

```C#
[ComImport, Guid("307472e7-d863-49e6-8275-e2dd7eb56e48")]
interface IComTest { void Test(ref object arg); }
interface ITest    { void Test(ref object arg); }
void Example(IComTest com, ITest notCom)
{
    object o = null;
    com.Test(o); // OK, ref not required for COM
    notCom.Test(o); // CS1620 Argument 1 must be passed with the 'ref' keyword
    notCom.Test(ref o); // OK
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @billybednar I've added it to our backlog to address when we next update this article.
