### ISSUE TITLE
Potential problems with f1 keywords for error messages

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20034]
The list of f1 keywords seem to be incomplete. As an example, CS8511 doesn't exist in this document, and it's also not documented.

If there is currently no internal tool for that, I can try writing a tool to auto generate the list of required f1_keywords for this article.

cc: @gewarren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error)
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Youssef1313 

Do you want to create a PR that adds the latest warnings to the list? If so, I'll assign this to you.

**Comment by Youssef1313** [comment]
@BillWagner, Sure.

It's a hard manual work, so I'll write a tool to do the job, and put the code in the PR for review.
