### ISSUE TITLE
Improvement for "Building Blocks of C# Programs" article

### ISSUE THREAD

**Issue by McPrescott** [dotnet/docs#20035]
Great article, appreciate the time that went into making it. Just a small change I would make in the Indexers category, the code shown doesn't actually show the use of, but an operator overload that is implemented in terms of it, however this is never actually specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @McPrescott 

I've just opened a PR to address this issue.
