### ISSUE TITLE
Dictionary to proto map does not seen to work without explicit casting

### ISSUE THREAD

**Issue by dgpshiva** [dotnet/docs#20044]
I tried this example and does not seem to work without explicitly casting 
`order.Attributes.Add((IEnumerable<Order.Types.Attributes>)attributes);`

Am  I missing something? I am on proto3.

```csharp
message Orders {
    map<string, string> values = 1;
}

public Orders CreateOrders(Dictionary<string, string> ordersDict)
{
    var orders = new Orders();
    orders.Values.Add(ordersDict);
    return orders;
}
```

This works. Just wanted to make sure my understanding is correct. Isn't the example wrong, since it is trying to map a "Dictionary" to a "repeated MapField" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614ee70b-64d7-47c6-0069-fdc514cf54dc
* Version Independent ID: ccb7f8ce-85cd-f725-2dd9-3244f0da7689
* Content: [Protobuf maps for dictionaries - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-maps)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-maps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/protobuf-maps.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by dgpshiva** [comment]
message Orders {
    map<string, string> values = 1;
}

public Orders CreateOrders(Dictionary<string, string> ordersDict)
{
    var orders = new Orders();
    orders.Values.Add(ordersDict);
    return orders;
}

This works. Just wanted to make sure my understanding is correct. Isn't the example wrong, since it is trying to map a "Dictionary" to a "repeated MapField" ?

**Comment by adegeo** [comment]
Sending email to @shirhatti

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
