### ISSUE TITLE
Hard to read table cells containing runtimes with line breaks

### ISSUE THREAD

**Issue by bender2k14** [dotnet/docs#20048]
This page contains a table with the runtimes of many operations for several data structures.  The longest such runtimes are communicated with about a dozen characters.  The longer runtimes include a line break or two (and one cell even has three line breaks).

I find it hard to read the runtimes that include line breaks.

Could the width of the columns containing runtimes be increased so that no runtime includes a line break?

To compensate, width of the description column (which intersections each row in a cell containing an explanatory paragraph) could be decreased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0694330-a4e4-5a07-2b6b-8259b57e319a
* Version Independent ID: 71e9da59-27a1-6194-3a69-09b9d3a383d4
* Content: [Collection Types - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types)
* Content Source: [docs/fsharp/language-reference/fsharp-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/fsharp-collection-types.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Unfortunately this is the docs website dictating the table, not the content. Not sure where to file that kind of feedback. @gewarren is there a good place for that?

**Comment by Youssef1313** [comment]
@cartermp, This feedback may be suitable in [MicrosoftDocs/feedback repository](https://github.com/MicrosoftDocs/feedback/).

**Comment by Youssef1313** [comment]
@cartermp, If there are no spaces in the runtimes, it won't be broken to multiple lines. For example, we can replace "O(Log N)" with "O(Log(N))". and something like "O(M * log N)", it will be "O(M*log(N))". If that's suitable, I'll open a PR so that you can confirm the fix on the staging.

**Comment by bender2k14** [comment]
No spaces would probably be more readable than line breaks.

What if `&nbsp;` is used for the spaces?
