### ISSUE TITLE
Missing C# compiler option

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20061]
The [doc](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md) from Roslyn's repository mentions the following compiler option, but they aren't mentioned in the article.:

- win32manifest (The option is [already documented](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/win32manifest-compiler-option), but just missing from this article.)
- nowin32manifest
- sourcelink (not documented at all) (**It's also missing in the ordered alphabetically article**)
- errorlog (not documented at all)
- reportanalyzer (not documented at all)
- errorendlocation (not documented at all)
- appconfig
- moduleassemblyname

The categories listed in the article are different than roslyn docs. I don't know if that was intentional or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3026d8-a871-b6a5-04dd-393212fdf331
* Version Independent ID: 29b22a16-f7dd-9c66-4393-2a8ea09b3ae8
* Content: [C# Compiler Options Listed by Category](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-by-category)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-by-category.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-by-category.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
/cc @jcouv 

Thanks for writing this @Youssef1313 

Before we work on this, I'd like the C# team to weigh in on which ones we should officially support (as opposed to options the team uses for internal diagnostics)

**Comment by jcouv** [comment]
When in doubt, I would rely on options that are listed in `csc -help` as the ones we support (I don't think we've been maintaining this [document](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md) as carefully).

Looking at `csc -help`, I see that all the options listed above are included, so I think they should be documented.

**Comment by IEvangelist** [comment]
> When in doubt, I would rely on options that are listed in `csc -help` as the ones we support (I don't think we've been maintaining this [document](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md) as carefully).
> 
> Looking at `csc -help`, I see that all the options listed above are included, so I think they should be documented.

Perhaps this is an area for improvement. Instead of trying to capture an exhaustive list of options, we should first focus on explaining the discoverability aspect of the CLI? How to consume help, learn about options, and consume them. Not necessarily saying that we shouldn't still try to cover all the options in the docs, just that we need to empower users when possible.

**Comment by BillWagner** [comment]
I like the previous proposal.

As part of the simplification of the C# Guide, I'd proposed consolidating the compiler options into a single page. All of them are quite short, and none have significant traffic.

**Comment by KalleOlaviNiemitalo** [comment]
`errorlog` was added in <https://github.com/dotnet/roslyn/pull/1272> before Visual Studio 2015, but the log format has been changed later and the history might be difficult to document accurately. There is some information about the current format in [Error Log Format.md](https://github.com/dotnet/roslyn/blob/15b43b33901c88f68ef43f8314b5a2457716780d/docs/compilers/Error%20Log%20Format.md).
