### ISSUE TITLE
Bad examples for using static

### ISSUE THREAD

**Issue by Elephant-Vessel** [dotnet/docs#20062]
In the remarks about the value of using statics, you write the following:

> Ordinarily, when you call a static member, you provide the type name along with the member name. Repeatedly entering the same type name to invoke members of the type can result in verbose, obscure code. For example, the following definition of a Circle class references a number of members of the Math class.

```csharp
using System;

public class Circle
{
   public Circle(double radius)
   {
      Radius = radius;
   }

   public double Radius { get; set; }

   public double Diameter
   {
      get { return 2 * Radius; }
   }

   public double Circumference
   {
      get { return 2 * Radius * Math.PI; }
   }

   public double Area
   {
      get { return Math.PI * Math.Pow(Radius, 2); }
   }
}
```

And then 

> By eliminating the need to explicitly reference the Math class each time a member is referenced, the using static directive produces much cleaner code:

```csharp
using System;
using static System.Math;

public class Circle
{
   public Circle(double radius)
   {
      Radius = radius;
   }

   public double Radius { get; set; }

   public double Diameter
   {
      get { return 2 * Radius; }
   }

   public double Circumference
   {
      get { return 2 * Radius * PI; }
   }

   public double Area
   {
      get { return PI * Pow(Radius, 2); }
   }
}
```

I understand that examples are best short and simple, but it doesn't feel like this is communicating the use case very well. The "verbose, obscure code" is nowhere to be seen and the "much cleaner code" initially feels more confusing when qualifications we are used to aren't present where we expect them.

Not trying to question the value of `using static`, just that the example used isn't showing that very well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef3971f-1004-6aa5-9554-d8e2fcd6ac68
* Version Independent ID: e73efd1b-c26c-c1f0-6018-02f11261bb64
* Content: [using static directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static)
* Content Source: [docs/csharp/language-reference/keywords/using-static.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-static.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I understand your point @Elephant-Vessel 

Do you have suggestions for a better example? For history:

- We tried using `Console.Writeline`, but we had several people copy the code snippet without the `static using`, and the sample didn't work. That's a worse experience.
- One of the most popular uses of the feature in our code bases is Roslyn-based analyzers and code fixes. That's a level of complexity that is too much for the language reference.

From those two, we chose a `System.Math` example. We have seen evidence that this is a popular use because many libraries make use of a number of the `Math` constants and members (`PI`, `E`, `Sin`, `Cos`, etc).

**Comment by Elephant-Vessel** [comment]
Thank you for the feedback @BillWagner, I'll put it in the front of mind and see if I'll be able to offer another suggestion.
