### ISSUE TITLE
The list of keywords is incomplete

### ISSUE THREAD

**Issue by lcsondes** [dotnet/docs#20068]
Documentation elsewhere (such as [this page](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2230)) as well as VS syntax highlighting both suggest that, e.g., `__arglist` is a keyword.

Others are missing, too: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs#L147

http://benbowen.blog/post/fun_with_makeref/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by lcsondes** [comment]
Actually a whole other bunch like `__makeref` https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs#L147

I understand not wanting to lead people to use double-underscore features, but they're there in the language and this is the documentation. I had to find out about __arglist the scenic way and I can't avoid it because for instance in my case I need to work with a native library that takes C `...` as an argument.

**Comment by Youssef1313** [comment]
The documentation for these is omitted **intentionally**, as they are discouraged and you shouldn't use them.

[CA2230](https://docs.microsoft.com/visualstudio/code-quality/ca2230) is to discourage the usage of \_\_arglist.

**Comment by BillWagner** [comment]
@lcsondes 

Any symbol that starts with two underscores (`__`) is a compiler reserved symbol. We've always considered those "implementation details", and not for use outside of the compiler. 

While we have a high bar for breaking changes (even when behavior isn't specified in the standard), we won't be formally adding docs on these symbols. 

I'll close this. That said, I did like your analysis in your blog, and all the research that went into it. 🙇 👍

**Comment by lcsondes** [comment]
(just for the record, that's not my blog)
