### ISSUE TITLE
Confusing words on Blazor hosting models

### ISSUE THREAD

**Issue by lextm** [dotnet/docs#20073]
># Blazor app hosting models
>Blazor apps **can be hosted in IIS just like ASP.NET Web Forms apps**. Blazor apps **can also be hosted in one of the following ways**:
> * Client-side in the browser on WebAssembly.
> * Server-side in an ASP.NET Core app.

It is confusing to describe in this way, because how many hosting models are there? Two or three? If there are only two hosting models (as the following of this article indicates), then the first two sentences should be revised to remove ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b45d194-8874-5bd1-31eb-767145461904
* Version Independent ID: 9817ff2d-afe1-8a5f-1e1a-7c7eadba5cf0
* Content: [Blazor app hosting models](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/hosting-models#feedback)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/hosting-models.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/hosting-models.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by adegeo** [comment]
Sending email to @danroth27
