### ISSUE TITLE
Unclear comment in discussion of yield! keyword

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/docs#20077]
With respect to this example (in the section on [yield!](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences#the-yield-keyword))

```fsharp
// Combine repeated values with their values
seq {
    for x in 1..10 do
        yield x
        yield! seq { for i in 1..x -> i}
}
```

The text right after the example says:

> Specifying only `x` in the previous example will result in the sequence generating no values.

It is not clear tot me what that statement is trying to say. Surely it doesn't mean that if you comment out `yield! seq { for i in 1..x -> I}` that you won't get any values; and I'm at a loss as to what else it would mean to "specify only `x`".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fae525-473a-3072-b024-6d91d0e033b9
* Version Independent ID: 6e162795-52bd-f9df-4105-6919c1c72c88
* Content: [Sequences - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences)
* Content Source: [docs/fsharp/language-reference/sequences.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/sequences.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, it's a pretty garbage sentence that doesn't make much sense. Will reword

**Comment by cartermp** [comment]
Addressed in https://github.com/dotnet/docs/pull/20057
