### ISSUE TITLE
Broken link leading to Collections.List model from Lists page

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/docs#20078]
At the end of the page on lists there is a section [Additional Operations](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists#additional-operations) which provides a broken link to Collections.List. It provides this url https://msdn.microsoft.com/visualfsharpdocs/conceptual/collections.list-module-%5bfsharp%5d 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc3b624-2978-8ae2-8ad0-0ae1613395af
* Version Independent ID: 0632dadf-1f15-d3ed-9751-b5b1d100df44
* Content: [Lists - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists)
* Content Source: [docs/fsharp/language-reference/lists.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/lists.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
fixed in https://github.com/dotnet/docs/pull/20058
