### ISSUE TITLE
The content does not match latest VS Blazor template

### ISSUE THREAD

**Issue by lextm** [dotnet/docs#20084]
"Bootstrap Blazor" section describes the following for Blazor WebAssembly app,

> The specific component to render is configured in the app's `Startup.Configure` method with a corresponding CSS selector indicating where the component should be rendered.

Sadly the latest Blazor WebAssembly template shipped with VS2019 16.7.1 no longer creates such as `Startup.cs` file. The logic has been incorporated into `Main` in `Program.cs` instead.

Therefore, this must be revised to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5831959-ac2f-ee91-f8c0-733901c76cf8
* Version Independent ID: 6248210d-e21c-2c4c-9972-8c981c1c521b
* Content: [Project structure for Blazor apps](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/project-structure)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/project-structure.md](https://github.com/dotnet/docs/blob/master/docs/architecture/blazor-for-web-forms-developers/project-structure.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by adegeo** [comment]
Sending email to @danroth27

**Comment by danroth27** [comment]
This content has already been updated to align with the .NET 5 version for the Blazor templates.
