### ISSUE TITLE
Inconsistent capitalization.

### ISSUE THREAD

**Issue by peterpi** [dotnet/docs#20080]
The constant `Months` has inconsistent capitalization.  In the code it is `Months`, but in the following paragraph it is `months`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2987a60-6760-a4f4-69cc-10ad3c38a0cc
* Version Independent ID: 1a416e9b-73cf-f2bd-cb5d-5acf6bf4f805
* Content: [Constants - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/constants.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/constants.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Do you want to submit a Pull Request that fixes this? If you do and don't know how, you can follow [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).
