### ISSUE TITLE
Is the "to" here in "Types and members", Tour of C# possibly unnecessary?

### ISSUE THREAD

**Issue by Xin-Shiyu** [dotnet/docs#20125]
In "Nullable types", there is a sentence:

> The compiler also provides warnings when non-nullable references are assigned to a value that may be null.

I'm trying to translate it into Chinese and I found it hard to understand when there is a "to". How can I assign a reference "to" a value? Should it be, "when non-nullable references are assigned a value", that is, a value is assigned to the references?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0b0e44dd-e0f2-9ace-006b-479a92fbf424
* Version Independent ID: 7811190e-6019-83d8-d504-c0b985368055
* Content: [Define types and their members - A tour of C#](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/types)
* Content Source: [docs/csharp/tour-of-csharp/types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think you're correct. (this is also related to https://github.com/dotnet/docs/issues/16437)

Would you like to open a PR to fix this? Click [here](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) to see how you do that.
