### ISSUE TITLE
System.Security.Cryptography.* Not Supported on Browser

### ISSUE THREAD

**Issue by steveisok** [dotnet/docs#20143]
## System.Security.Cryptography.* Not Supported on Browser

Because we are not able to ship OpenSSL and we also cannot use the browser's SubtleCrypto, we will not have support for any of the System.Security.Cryptography api's.  

### Version introduced

.NET 5.0

### Old behavior

Worked as expected

### New behavior

We will throw a PlatformNotSupportedException for all impacted types.

### Reason for change

We are unable to ship OpenSSL as a dependency in the Browser configuration.  We attempted to work around this by trying to integrate w/ the browser's SubtleCrypto API.  Unfortunately, we found it would require significant API changes and thus, deemed it not possible for 5.0.

### Recommended action

There are no good workarounds to suggest at this time. 

### Category

Cryptography

### Affected APIs

[System.Security.Cryptography Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography?view=net-5.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by PriyaPurkayastha** [comment]
cc @gewarren

**Comment by steveisok** [comment]
Sorry, I didn't know at what level to describe this.  I basically mean Blazor or anything else targeting WebAssembly (Browser).

**Comment by scottaddie** [comment]
@steveisok Does this breaking change ONLY affect ASP.NET Core apps?

**Comment by PriyaPurkayastha** [comment]
@steveisok I think you need to call out somewhere that this is applicable on Mono Runtime. Perhaps where you say "we" you can specify that on Mono runtime....

**Comment by steveisok** [comment]
@lewing Would it be better to say Blazor WebAssembly?  I definitely need guidance on the wording.

**Comment by marek-safar** [comment]
Blazor WebAssembly is the term we used for this configuration most often

**Comment by gewarren** [comment]
Related to #20283.

**Comment by gewarren** [comment]
I actually think this issue is a subset of https://github.com/dotnet/docs/issues/20283, the breaking change for the CA1416 (platform compatibility analyzer). Can I close it in favor of that?

**Comment by steveisok** [comment]
@gewarren I do agree the issue is a subset and we can probably close this one.

**Comment by gewarren** [comment]
@steveisok Actually I just reread it and now I think it is a separate breaking change. I thought this was just about adding the `UnsupportedOSPlatformAttribute` to these APIs, but now I see that the PNSE exceptions are new too. So I think this is separate. Even if you have code analysis or the platform compatibility analyzer suppressed, there is still a breaking change in that now you get a PNSE. Is that correct?

**Comment by steveisok** [comment]
Correct.  I was assuming that would be spelled out in your issue, but I guess that doesn't make any sense.
