### ISSUE TITLE
Replace dot with comma

### ISSUE THREAD

**Issue by mialkin** [dotnet/docs#20152]
Between two "á" you have the dot (**.**) but there should be a comma (,):

YOU HAVE  : Consider the string instances "a", **"á". "á"**, and "👩🏽‍🚒".
SHOULD BE: Consider the string instances "a", **"á", "á"**, and "👩🏽‍🚒".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66
* Version Independent ID: d53a0764-9f27-16b3-c40a-9627dd1bcc0d
* Content: [Introduction to character encoding in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction)
* Content Source: [docs/standard/base-types/character-encoding-introduction.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-encoding-introduction.md)
* Product: **dotnet**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
Do you want to submit a PR to fix this? Here is [how](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).

**Comment by mialkin** [comment]
I just did pull request. Never done it before for Microsoft documentation, thank you for your suggestion!
