### ISSUE TITLE
Specify what the default rollForward value is if not specified

### ISSUE THREAD

**Issue by benmccallum** [dotnet/docs#20150]
Would be great to know what the default rollForward value is if not specified. 

Would've thought it would be latestFeature, but it would seem not, so probably just latestPatch, which makes sense for security reasons, but isn't 100% obvious when the dotnet versioning is `x.y.znn` and z = feature bands. Whereas semantic versioning usually would have that last `znn` part be the whole patch version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The default behavior is described in the [Matching rules](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#matching-rules) section. If global.json specifies an SDK version, latestPatch is the default.

**Comment by benmccallum** [comment]
Sigh. My bad. Didn't realise it was so complicated so didn't look in that part. Must've looked everywhere else. Perhaps this can be made clearer/quicker to find when scanning.

**Suggestion 1**
Under the section on the `rollForward` setting, where you'd expect to see the default value described, point to the `Matching rules` section with something like: "The default value of `rollForward` is determined as per the [Matching rules](...)"

**Suggestion 2**
Under "Matching rules", the sentence "The matching rules for the latest installed version of the .NET Core Runtime are used when you have multiple runtimes installed side-by-side." is misleading as we don't have multiple instance of runtimes in our docker container, just a global.json with a version specified but these rules still came into effect.

Perhaps that wording could include " or you're using a global.json." on the end?

**Comment by tdykstra** [comment]
Great ideas, I'll put this issue on our backlog. If you're interested in making a PR for these updates that would be welcome as well.

**Comment by eriawan** [comment]
@tdykstra 

Could I take this issue with @benmccallum suggestion? I think both his suggestions should be the update of this global.json page.

PR for this is submitted: #21290

**Comment by nithinbandaru1** [comment]
@tdykstra I see in documentation it is mentioned as `patch` instead of `latestPatch` as you mentioned in comment. Can you confirm which is right?
