### ISSUE TITLE
Remove "compiler-option" suffix from file names

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20162]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option

The -compiler-option in the url is an unnecessary duplication. It's better to be just:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion

**Comment by BillWagner** [comment]
@Youssef1313 

You're right, but I'm going to advocate for a different change.

I think there is a case for creating one page that lists all the compiler options with a brief description. Each option would be an H2, so the right nav would be useful for finding each option. I think the page length would still be manageable. Finally, it would create one obvious location for explaining how to set compiler options using `dotnet build` or `msbuild`.

What do you think?
