### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by ordinaryorange** [dotnet/docs#20175]
Links on [this documentation page](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types) broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0694330-a4e4-5a07-2b6b-8259b57e319a
* Version Independent ID: 71e9da59-27a1-6194-3a69-09b9d3a383d4
* Content: [Collection Types - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-collection-types)
* Content Source: [docs/fsharp/language-reference/fsharp-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/fsharp-collection-types.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by Youssef1313** [comment]
These are being fixed in https://github.com/dotnet/docs/pull/20055

**Comment by cartermp** [comment]
Fixes in https://github.com/dotnet/docs/pull/20055
