### ISSUE TITLE
I believe i found a little mistake on documentation

### ISSUE THREAD

**Issue by leekr7070** [dotnet/docs#20181]
I made a post about it on stackoverflow
https://stackoverflow.com/questions/63480764/variance-safety-in-c-sharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2460f23d-9f92-866c-b814-920997233e6b
* Version Independent ID: 344fa873-bf0c-1c15-cac4-f262ad0162c8
* Content: [Interfaces - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces#variance-safety)
* Content Source: [spec/interfaces.md](https://github.com/dotnet/csharplang/blob/master/spec/interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I posted an answer [here](https://stackoverflow.com/a/63490299/5914677) 

This is fixed in the official standard, and it will be addressed as we update and merge the C# 6 spec with the C# 5 standard.

**Comment by leekr7070** [comment]
Thank you! This issue was bugging me. :)

**Comment by BillWagner** [comment]
Closing as this is fixed in the C# 6 version in dotnet/csharpstandard.
