### ISSUE TITLE
Outdated tutorial description

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20185]
> **[Writing .NET Core console apps using the .NET Core CLI: A step-by-step guide](../core/tutorials/cli-create-console-app.md)**
>
> This guide shows you how to use the .NET Core CLI tooling to build cross-platform console apps. It starts with a basic console app and eventually spans multiple projects, including testing. You add features step-by-step, building your knowledge as you go. The [completed sample](https://github.com/dotnet/samples/tree/master/core/console-apps) is available in the dotnet/samples repository on GitHub.

The description is outdated. The article was retired and a new article was re-written.

**Edit:** the next tutorial description looks outdated too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3caf351-18c6-5211-f2a2-bbdef5918629
* Version Independent ID: f13ef5fe-c17a-ecd1-2a2b-55b3b101da07
* Content: [.NET samples and tutorials](https://docs.microsoft.com/en-us/dotnet/samples-and-tutorials/)
* Content Source: [docs/samples-and-tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/samples-and-tutorials/index.md)
* Product: **dotnet**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
@Youssef1313 It looks like this was addressed, should this issue be closed?

**Comment by Youssef1313** [comment]
@tdykstra The description under "Writing Libraries with Cross Platform Tools" is still a bit outdated. Mostly, it looks good except for the sample link, which looks unrelated to the actual article.
