### ISSUE TITLE
misspeling indice -> index

### ISSUE THREAD

**Issue by amir4846** [dotnet/docs#20184]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@amir4846 Can you point out where in the article it mentions "indice"?
All the occurrences I found are "indices", which is the correct plural form of "index".

**Comment by BillWagner** [comment]
@amir4846 I found the same as @Youssef1313 

Can you point to the spelling error? In the meantime, I'll close this.
