### ISSUE TITLE
ISpecification does not exist on eShopOnWeb like it is mentioned in the article

### ISSUE THREAD

**Issue by miguelcrpinto** [dotnet/docs#20187]
Unlike what is mentioned in section "[Implement the Query Specification pattern](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implementation-entity-framework-core#implement-the-query-specification-pattern)" of the article, the ISpecification<T> interface and BaseSpecification<T> class do not exist in the eShopOnWeb project.

The project is instead using Ardalis.Specification nuget package to implement this pattern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8be69079-b229-819b-0408-fb6c6aa30b88
* Version Independent ID: 3657bdb9-00c1-bb97-3470-d4f8c7569676
* Content: [Implementing the infrastructure persistence layer with Entity Framework Core](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implementation-entity-framework-core)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implementation-entity-framework-core.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implementation-entity-framework-core.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by adegeo** [comment]
@nishanil @ardalis The book seems to reference a specification type in the linked repository but it doesn't exist anymore. As the user stated, it's now contained in a package. Perhaps it should either point to https://github.com/ardalis/Specification/ or the original commit within the github repository that contained this file?

**Comment by ardalis** [comment]
Good point. I can PR a quick update if you like. Please confirm.

**Comment by ardalis** [comment]
This is done and will be merged later this month.

**Comment by miguelcrpinto** [comment]
thank you!
