### ISSUE TITLE
Update sample to work with .NET 5 / .NET Core

### ISSUE THREAD

**Issue by sherland** [dotnet/docs#20182]
The example compiles without issues on .NET Core 3.1 but fail at runtime:
System.Xml.XslLoadException: 'XSLT compile error.'
Inner exception
PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported

If the functionality is not supported on .NET / .NET Core, the page should specify that this is only working on .NET Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08a4e69-6732-8758-b51c-d3e7078ddd46
* Version Independent ID: e0052fd1-9da9-84ad-c407-00a2b9c3f9b3
* Content: [Script Blocks Using msxsl:script](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/script-blocks-using-msxsl-script)
* Content Source: [docs/standard/data/xml/script-blocks-using-msxsl-script.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/script-blocks-using-msxsl-script.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@gewarren, Do you know if such a breaking change was documented? It should be documented if it's currently not, and the article may be moved to docs/framework instead of docs/standard.

**Comment by gewarren** [comment]
I don't see anything on [this page](https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core). @PriyaPurkayastha Can you help to figure out if we need to document this as a breaking change?

**Comment by PriyaPurkayastha** [comment]
Adding @jeffhandley @danmosemsft so that they can look into this and confirm where this needs to be documented and to create a breaking change issue accordingly.

**Comment by danmosemsft** [comment]
@krwq is it as simple as: in .NET Core we do not support compiling code embedded in XSL files, ie., we do not support `<msxsl:script>` tags at all? Or something more subtle.

We can certainly improve the docs..

**Comment by krwq** [comment]
@danmosemsft sorry, I just noticed this notification, I just checked and seems like we will always throw in some way if you use XSLT with msxsl:script regardless of the language you pick in the script
