### ISSUE TITLE
f1_keywords for subtraction isn't working

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20199]
<https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(-_CSharpKeyword);k(DevLang-csharp)&rd=true>
Currently, this just redirects to <https://docs.microsoft.com/en-us/>

I don't know if it's a temporary problem or not. I see that f1_keywords for "-_CSharpKeyword" already exists in subtraction operator article. The issue reason isn't clear to me.

**Comment by davidwengier** [comment]
@BillWagner Any idea who we can reach out to for this issue?

I'm seeing very intermittent results with the query service, and the link in the OP is much slower than any other link I try, and always fails.

**Comment by BillWagner** [comment]
I checked, and the site team thinks this is fixed in the new Docs F1 service. (Not yet released)

Adding @OsmondJiang for more details.

**Comment by Youssef1313** [comment]
@BillWagner Please ping me with the new service URL when released. If the new URL doesn't have a hard-coded version, this might fix the error-messages F1 in Roslyn.

**Comment by OsmondJiang** [comment]
add @junshi356 who is working on the new Docs F1 service, he will give a update once we rolled the new F1 Service which should also support this f1 keywords

**Comment by davidwengier** [comment]
Looks like this is now working, but a different link is failing. I'm seeing the same results as per this comment:

https://github.com/dotnet/roslyn/issues/46988#issuecomment-683149510

Is there anything we can do to fix this, or do we just wait for the new service?

**Comment by BillWagner** [comment]
@davidwengier I'm looking for the contact to put you in touch with.

**Comment by junshi356** [comment]
The behavior of https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(-_CSharpKeyword);k(DevLang-csharp)&rd=true is fine now. We believe that this issue is resolved.

**Comment by Youssef1313** [comment]
Thanks @junshi356, but the following one is not working :cry:

 https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(+_CSharpKeyword);k(DevLang-csharp)&rd=true

**Comment by junshi356** [comment]
Please encode the url before sending request. (The product like VisualStudio/SSMS will also encode the url)

https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(%2B_CSharpKeyword);k(DevLang-csharp)&rd=true
Just goes to the page you want, I guess.

**Comment by Youssef1313** [comment]
Works with encoding!
Thanks.
