### ISSUE TITLE
Mention the minimum officially supported TargetFramework for C# versions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20206]
I think C# 9.0, unlike previous versions, will only be **officially** supported in .NET 5.0 and later.
If this is correct, the page should mention this when it gets updated to C# 9.0.

@agocke This is per your comment in [this blog](https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/#comment-6107).

> Hey Steve, the current plan is that C# 9 will only be officially supported on .NET 5. However, in the current design records do not depend on any new CLR features, so many things may work in .NET Standard 2.0 in an unsupported fashion (similar to C# 8).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@BillWagner This was fixed in the PR that added "What's new in C# 9", but only small thing needs to be clarified.

For C# 8, it was clearly stated why it's only supported in .NET Core 3.x:

> Many of the newest features require library and runtime features introduced in .NET Core 3.x:

then it gives a list of the features that require new runtime capabilities.

Can you update the article the same way for C# 9?

It currently just says:

> C# 9.0 is supported only on .NET 5 and newer versions.

without clear explanation of "why", and what features requires .NET 5

**Comment by BillWagner** [comment]
I'm closing this with no further action.  The C# 8 article was updated to remove details on which features may work on earlier TFMs. C# 8 isn't supported on those earlier TFMs, so the docs won't make definitive statements about what features may work.
