### ISSUE TITLE
YouTube version of this tutorial

### ISSUE THREAD

**Issue by krchome** [dotnet/docs#20215]
[Enter feedback here]

YouTube version available at: https://www.youtube.com/playlist?list=PLnVvOWNfuhGUitwCXohN9kQlp4AMyRjjA
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cdb113e-14a4-7e96-2998-9bc42ddf9d7d
* Version Independent ID: 11857021-b820-ac38-307c-33f3f4a5065f
* Content: [Tutorial: Analyze sentiment - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder#add-the-code-to-make-predictions)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @krchome,

This is fantastic! Thanks for creating this video series. Since this is not a documentation issue, I am closing it for now. Thanks again for your contribution and we look forward to  seeing your future contributions 😊

**Comment by krchome** [comment]
> Hi @krchome,
> 
> This is fantastic! Thanks for creating this video series. Since this is not a documentation issue, I am closing it for now. Thanks again for your contribution and we look forward to seeing your future contributions 😊

Thanks very much. Can you make the video resources available at a central URL so that they have a more global outreach?

**Comment by luisquintanilla** [comment]
We're happy to. While it won't be part of Docs, I've added it to the GitHub machinelearning-samples Repo.

https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md

**Comment by krchome** [comment]
Thanks a ton, @luisquintanilla. 
Regards,
Kaushik
