### ISSUE TITLE
Instructions for setting AppContext switches via registry are incomplete

### ISSUE THREAD

**Issue by SamBent** [dotnet/docs#20241]
The AppContext [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=netcore-3.1#remarks), under subheading "AppContext for library consumers", describes several ways to set a switch.  The third method uses the registry.  The instructions there are incomplete.  They should mention that on a 64-bit OS you also need to add a string value (with the same name and value) to the key `HKLM\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\AppContext`.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core
- [ x] .NET Framework
- [ x] .NET Standard

all versions

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4770
