### ISSUE TITLE
Add information about IPv6 disabling and breakage of functionality and support status

### ISSUE THREAD

**Issue by agowa338** [dotnet/docs#20245]
Previously Microsoft has communicated, that disabling IPv6 will break things in unexpected ways and that disabling IPv6 is not a tested scenario.  I'm however unable to find any recent documentation about this. The only thing I found is from the [archive](https://docs.microsoft.com/en-us/archive/blogs/netro/arguments-against-disabling-ipv6). Does this still reflect the current status of IPv6 within Microsoft?

Within that archived blog post it explicitly says:
* "**Microsoft does not recommend** that customers disable IPv6"
* "If IPv6 is disabled on Windows Vista, Windows Server 2008, or later versions like Windows7 or Windows Server 2008 R2, **some components will not function**. Moreover, applications that you might not think are using IPv6—such as Remote Assistance, HomeGroup, DirectAccess, and Windows Mail—could be. Additionally the P2P APIs require IPv6, and those are public APIs. If IPv6 is disabled, programs that use the P2P APIs will break. This could impact application compatibility for third party apps."
* "**Therefore, Microsoft recommends that you leave IPv6 enabled, even if you do not have an IPv6-enabled network, either native or tunneled.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd48e88-8264-f6cb-3ac6-bcbe7fbed373
* Version Independent ID: 27c955c6-1790-599d-d604-f87446d3ca3c
* Content: [Internet Protocol Version 6](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/internet-protocol-version-6)
* Content Source: [docs/framework/network-programming/internet-protocol-version-6.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/internet-protocol-version-6.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by antonfirsov** [comment]
I don't think this is a .NET concern, if anything this is a question to Windows networking folks since it's very specific to the Windows stack. I don't believe it would be a good idea for us to document general OS-specific recommendations. This issue is hardly actionable for us in any other way than raising Windows networking team's awareness about the question.

**Comment by antonfirsov** [comment]
The statements of the linked blogpost are actually repeated in the [official Windows IPv6 docs](https://learn.microsoft.com/en-US/troubleshoot/windows-server/networking/configure-ipv6-in-windows#summary):

> Internet Protocol version 6 (IPv6) is a mandatory part of Windows Vista and Windows Server 2008 and newer versions. We do not recommend that you disable IPv6 or its components. If you do, some Windows components may not function.

> We recommend using Prefer IPv4 over IPv6 in prefix policies instead of disabling IPV6.

I have no reason to question that this statement. I'm closing this issue; we may consider adding a link to the Windows docs to our docs.
