### ISSUE TITLE
Not working for email addresses

### ISSUE THREAD

**Issue by andychangwalker** [dotnet/docs#20258]
This isn't working if the special character is at the beginning or end of the username section of the address.

e.g. _name@domain.com or name_@domain.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to verify that strings are in valid email format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by svick** [comment]
This is pretty much a duplicate of https://github.com/dotnet/docs/issues/16299.

**Comment by andychangwalker** [comment]
Sorry, it is a duplicate. I just clicked on the button at the bottom of the page "Submit and view feedback for" "This Page" and assumed as it opened me a "new" incident page that meant there was no feedback for the page. I didn't realise it expected me to then search myself.

I will close this.

**Comment by Youssef1313** [comment]
> 
> 
> Sorry, it is a duplicate. I just clicked on the button at the bottom of the page "Submit and view feedback for" "This Page" and assumed as it opened me a "new" incident page that meant there was no feedback for the page. I didn't realise it expected me to then search myself.
> 
> I will close this.

@adegeo Previously, there was links to all open issues for a specific article in live docs. What happened to that? Any idea?

Is that something applied globally to all docs.microsoft subsets or configured per repository?

**Comment by svick** [comment]
@andychangwalker I'd say it's nice if you do a quick search for duplicates first, but it's not required. So there is no need to apologize.

@Youssef1313 That button is still there:

![](https://user-images.githubusercontent.com/287848/91075326-2fa62580-e63e-11ea-822a-ac673839ad74.png)

(Though I think it was more prominent in the past.)

**Comment by adegeo** [comment]
no worries @andychangwalker we understand the current user experience with listing issues at the end of the article isn't ideal @Youssef1313 I believe they changed it because there was too much of a possibility someone puts up hate speech or other causes other legal problems or something, I don't know, but the design change was done everywhere.

**Comment by andychangwalker** [comment]
Ah. I totally missed that link down there. I would suggest moving it as a button next to the other 2.

**Comment by adegeo** [comment]
@andychangwalker I would love for you to give that feedback via https://aka.ms/sitefeedback (there is a link in the footer of the site on each doc page "Site Feedback" which is the link I just gave you) The more people we get to give feedback on that, hopefully the quicker they will make the experience better 👍
