### ISSUE TITLE
Async tutorials

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20270]
Previously, the VB guide for async was nearly a mirror of the C# one.
Recently, @IEvangelist made great updates to the C# async guide, but the VB is still the same.

There are two options to fix that:

1. Just update the VB guide to match the C# one.
2. Move the guide from language-specific guide to *dotnet/standard/async*, so we have just one article that explains the concept in both languages. (which is easier to maintain)

@BillWagner @IEvangelist What do you think?

**Comment by BillWagner** [comment]
Thanks for writing this @Youssef1313 

We identified this as part of our .NET 5 planning.  We agree that this content should move to the "fundamentals" section for .NET 5.

/cc @tdykstra

**Comment by Youssef1313** [comment]
Pinging @mairaw.
I believe you have an in-progress work with a vendor to consolidate LINQ guide. You may consider having it in "fundamentals" section before merging to master.

**Comment by mairaw** [comment]
I'm not up-to-date on plans for this repo. @BillWagner please advise

**Comment by BillWagner** [comment]
@Youssef1313 You'll start to see content moving and the TOC being updated shortly.  @tdykstra is starting that.

The async tutorials will be consolidated later. Let's leave this open without action until we finalize that plan.

**Comment by IEvangelist** [comment]
This continues to be de-prioritized due to time constraints and more pressing matters. Let's close this for now, and state clearly that we can always reopen this when/if time permits.
