### ISSUE TITLE
The code is blocking 

### ISSUE THREAD

**Issue by Danielovich** [dotnet/docs#20286]
The example is not working, since the while loop is blocking execution of the webhost.

Am I missing anything ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hello @Danielovich, thanks for reaching out. 

`BackgroundService` base class contains abstract method `ExecuteAsync` which actually gets overridden by any concrete class. The method `ExecuteAsync` is called when the IHostedService actually starts. 
The implementation represents the lifetime of the long-running operation(s) being performed. So in the concrete class should have the logic to run the task during the entire lifetime of the application. 
And that's the reason `while` loop has been introduced in there. It keeps on getting executed with the provided delay until `IsCancellationRequested` value gets set as True, where initial the value was False.

For an example: If you debug the actual application [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) from where the code snippet has been taken you would notice background task is keep on running with 
30 seconds of interval. If you put a break point in your local debugging environment you would notice it's keep hitting the breakpoint. As mentioned in below screenshot :


For more details about the background service you can refer [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @Danielovich, I am closing this issue as of now. If you have any further questions, please feel free to reopen this issue. 

Thank you.
