### ISSUE TITLE
members of readonly struct are not implicitly readonly

### ISSUE THREAD

**Issue by mikedamay** [dotnet/docs#20293]
The docs say ` In a readonly struct, every instance member is implicitly readonly`.  

Fields have to be made explicitly readonly or the following compiler error is generated: `error CS8340: Instance fields of readonly structs must be readonly`.

"implicitly" appears misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#readonly-struct)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@mikedamay methods are implicitly readonly, one doesn't need the modifier in a method declaration, if the whole structure is readonly

**Comment by pkulikov** [comment]
However, I see it can mislead more than help.

**Comment by mikedamay** [comment]
Thanks for looking at this.

Maybe if `member` is changed to `method` in this context that would help.
