### ISSUE TITLE
"in" parameter modifier: Contradiction in overload resolution

### ISSUE THREAD

**Issue by neonb** [dotnet/docs#20296]
The page says:

> The `in`, `ref`, and `out` keywords are not considered part of the method signature for the purpose of overload resolution

A few lines later, it says:

> Overloading based on the presence of `in` is allowed

In my understanding these statements can't both be true. If the `in` keyword is not considered part of the signature, then overloads based on its presence shouldn't be allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @neonb 

We had the same discussion updating the C# standard (for C# 5.0).  We changed the pertinent text in the standard as follows:

>Although `out` and `ref` parameter modifiers are considered part of a signature, members declared in a single type cannot differ in signature solely by `ref` and `out`. A compile-time error occurs if two members are declared in the same type with signatures that would be the same if all parameters in both methods with `out` modifiers were changed to `ref` modifiers. For other purposes of signature matching (e.g., hiding or overriding), `ref` and `out` are considered part of the signature and do not match each other.
>
>> *Note*: This restriction is to allow C# programs to be easily translated to run on the Common Language Infrastructure (CLI), which does not provide a way to define methods that differ solely in `ref` and `out`. *end note*

For later versions, when `in` is allowed, we should add something like the following:

>Although `in`, `out` and `ref` parameter modifiers are considered part of a signature, members declared in a single type cannot differ in signature solely by `in`,  `ref` and `out`. A compile-time error occurs if two members are declared in the same type with signatures that would be the same if all parameters in both methods with `out` or `in` modifiers were changed to `ref` modifiers. For other purposes of signature matching (e.g., hiding or overriding), `in`, `ref` and `out` are considered part of the signature and do not match each other.
>
>> *Note*: This restriction is to allow C# programs to be easily translated to run on the Common Language Infrastructure (CLI), which does not provide a way to define methods that differ solely in `in`, `ref` and `out`. *end note*

I've added this to our backlog to update when we next update this article. I've also added the `up-for-grabs` label in case any community members want to submit a PR in the meantime.

**Comment by rafcon-dev** [comment]
@BillWagner , I recon this one should be closed as you've already added the changes you mention in the discussion, correct?

**Comment by BillWagner** [comment]
Thanks @rafcon-dev This has been addressed. I'll close it.
