### ISSUE TITLE
Debian install - add "sudo" to "dpkg" when adding microsoft packages

### ISSUE THREAD

**Issue by petkahl** [dotnet/docs#20291]
In most cases, "sudo" is included in the commands to run, at least in the Installing section of this page, but in the first code snip, it's missing on the "dpkg -i package-microsoft-prod.deb" line. Should be added for consistency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET Core on Debian - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-debian.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
