### ISSUE TITLE
Use recursive flag in example of adding all projects to solution

### ISSUE THREAD

**Issue by angularsen** [dotnet/docs#20309]
Normally, project files are in subfolders so it makes sense to use the recursive flag `-r`.

Change the example:
```
# From
dotnet sln todo.sln add (ls **/*.csproj)

# To
`dotnet sln todo.sln add (ls -r **/*.csproj)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion -- we'll implement it the next time we update the article, or you're welcome to submit a PR if you'd like to make the change yourself.

**Comment by angularsen** [comment]
Created pull request #20321 .
