### ISSUE TITLE
 Service Fabric SDK and Tools for Visual Studio 2015 Does Not exist

### ISSUE THREAD

**Issue by mnguyen36** [dotnet/docs#20301]
Service Fabric SDK and Tools for Visual Studio 2015 does not exist in the Web Platform Installer, so I can't get VS 2015 to recognize sfproj. Any reason I can't see this product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eea9da8-546f-74ac-34f4-f7a39bea1a1c
* Version Independent ID: 4e064376-f7a9-0de3-9315-2873f9c3df4c
* Content: [Azure tools for Visual Studio 2015](https://docs.microsoft.com/en-us/dotnet/azure/vs2015-install)
* Content Source: [docs/azure/vs2015-install.md](https://github.com/dotnet/docs/blob/master/docs/azure/vs2015-install.md)
* Product: **azure-dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by tdykstra** [comment]
@CamSoper Is the first sentence of this article out of date?

>The quickest and easiest way to install the Azure SDK for Visual Studio 2015 and Service Fabric SDK and Tools for Visual Studio 2015 is using the Web Platform Installer.

**Comment by scottaddie** [comment]
Closing, as this doc has been retired. Related to https://github.com/dotnet/docs/pull/25306.
