### ISSUE TITLE
Can't read this

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/docs#20306]
[Enter feedback here]

There's quite a lot here that's not real English.

"Just for the example sake, you can see one of the above policies in the next code:"

and then it's followed by something that's quite irrelevant to what's being discussed, with some mentions of Polly which is also irrelevant in the context.

This has to be the longest sentence ever written:
"Up to this point, the code shown is just performing regular Http requests, but the 'magic' comes in the following sections where, just by adding policies and delegating handlers to your registered Typed Clients, all the HTTP requests to be done by HttpClient will behave taking into account resilient policies such as retries with exponential backoff, circuit breakers, or any other custom delegating handler to implement additional security features, like using auth tokens, or any other custom feature."

Humour me and actually read through it, now tell me what it's trying to say. I stopped reading after the first five hundred or so characters as I can't wrap my head around it.

The *only* thing I wanted to see is how to consume strongly typed clients - ie how to inject them into your named service (is it implicitly done when using the client factory in the appropriate service?). Either it's not here or it's lost in all the irrelevant and overly long sections.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Tommigun1980, thank you for your detailed feedback.

Once your typed client class is implemented and registered, it will be available to use in your application through DI. 

For example : once [`CatalogService`](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#implement-your-typed-client-classes-that-use-the-injected-and-configured-httpclient) class is registered, then it's available in the [`CatalogController`](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#use-your-typed-client-classes)

The entire application `eShopOnContainers` can be referred in [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Services/CatalogService.cs)

Hope this helps !
