### ISSUE TITLE
LDM acronym is used but not defined.

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#20303]
What is LDM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda9613d-f954-c8c1-ede0-e4dad3b7d399
* Version Independent ID: ebdd8e1f-85a0-af70-2493-d59edc2f816e
* Content: [Init only setters - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init)
* Content Source: [proposals/csharp-9.0/init.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/init.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@michael-hawker language design meeting

**Comment by BillWagner** [comment]
I'll close this as an answered question.

Not moving to csharpstandard, as the term "LDM" will be removed as part of standardizing any of the feature specs.
