### ISSUE TITLE
Package Health: Compiler Flags: Missing !, what does it mean and how to fix it

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#20300]
I have generated a package and there is a warning stating 
Package Health: Compiler Flags: Missing with a yellow! mark in the NugerPackage explorer.
There is a message claiming that I'm compiling without enough information... what to add and where to add it is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@rrelyea @nkolev92 Can you help with this?

**Comment by nkolev92** [comment]
@tdykstra 

The ask seems to refer to NuGetPackageExplorer which is a 3rd party tool. 
Don't have expertise there, https://github.com/NuGetPackageExplorer/NuGetPackageExplorer.

**Comment by tdykstra** [comment]
@nkolev92 Thanks!

@PeterPann23 For help with NuGetPackageExplorer, you might try creating an issue in that repo https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
