### ISSUE TITLE
TrimMode is difficult to determine proper values and provide on the command line

### ISSUE THREAD

**Issue by Mgamerz** [dotnet/docs#20302]
Looking over this documentation for the page, it states under `Trim your app - CLI`:

`The following example publishes an app in the aggressive trim mode where unused code within assemblies will be trimmed and trimmer warnings enabled.`

This 'aggressive' mode is not documented anywhere else on the page, or what this actually means in practice. I've looked around the internet and haven't seen any documentation on this feature either. It says it trims the assembly but that doesn't really mean anything to me beyond I know it's doing... something to reduce filesize. What options are there for TrimMode? How do you actually specify these on the command and not only in the csproj?

Additionally, this page says this is for the CLI - but the code blocks show XML... which is not really cli, is it? That's part of the csproj file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a6f297-c659-3770-42d9-d277895b5d25
* Version Independent ID: 3061aedd-2264-90da-b244-b8ed7bf416fc
* Content: [Trim self-contained applications - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained)
* Content Source: [docs/core/deploying/trim-self-contained.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/trim-self-contained.md)
* Product: **dotnet-core**
* GitHub Login: @jamshedd
* Microsoft Alias: **jamshedd**

**Comment by Mgamerz** [comment]
It's actually documented higher up the page in the wall of text, which makes it harder to figure out. I have a few other issues though, I will file issues on those if I determine it's a problem with .net core itself.

**Comment by jtschuster** [comment]
Docs have been updated and issues look to be addressed.
