### ISSUE TITLE
What is the vstest parameter /Framework value for .NET 5 unit tests?

### ISSUE THREAD

**Issue by mihail-vladov** [dotnet/docs#20311]
Hi,
I am trying to verify that our product is fully compatible with .NET 5 preview 8 as our clients are already asking if we are going to support .NET 5 when it is launched officially. To provide an accurate answer I would need to verify that all unit tests are executed against .NET 5. However, I can't find any information about the value of the /Framework value of vstest. Could you please share that information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c66d2f-86f4-6472-a4c8-30e4203a10de
* Version Independent ID: 224583f2-3ca3-5c97-4cd4-fcd3d6a64f91
* Content: [dotnet vstest command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest)
* Content Source: [docs/core/tools/dotnet-vstest.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-vstest.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Per the alert box at the top of this page,

> The `dotnet vstest` command is superseded by `dotnet test`, which can now be used to run assemblies. See [dotnet test](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test).

cc @nohwnd

**Comment by nohwnd** [comment]
For .NET Core 5.0 you can use net5.0. 

```
dotnet test --framework net5.0
Microsoft (R) Build Engine version 16.8.0-preview-20464-02+0220c5eae for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  UsePath -> C:\t\UsePath\bin\Debug\net5.0\UsePath.dll
Test run for C:\t\UsePath\bin\Debug\net5.0\UsePath.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 3 ms - UsePath.dll (net5.0)
```

**Comment by tdykstra** [comment]
Thanks, @nohwnd !

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
