### ISSUE TITLE
"Cancel a list of tasks (C#)" has code error

### ISSUE THREAD

**Issue by rvincent7** [dotnet/docs#20313]
The example at URL https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks contains an error in the following line:
byte[] content = await response.Content.ReadAsByteArrayAsync(token);
The Visual Studio IDE and compiler indicate that a ReadAsByteArrayAsync doesn't have any parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [Cancel a list of tasks (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
It has a CancellationToken parameter, but starting with .NET 5.0 and later.

@BillWagner @IEvangelist, What would be the correct way to do the same thing in previous versions?

**Comment by rvincent7** [comment]
Thanks. Yeah, I missed the .NET 5.0 prereq mentioned on the page. I was was still building a .NET Core 3.1 Console App as I did in previous examples I was doing and so I missed that. I now see that if I go to the Microsoft docs and select the .NET 5.0 doc page I see the version with Cancellation token.

**Comment by IEvangelist** [comment]
Alternatively, you could omit the `token` from the `ReadAsByteArrayAsync`. It's not a huge deal, more like a nice to have - otherwise cancellation requests that occur during the reading as a `byte[]` wouldn't be possible, and slightly delay the request. Also, yeah - the prerequisites call it out. Nothing to change here, closing this. If you need anything else @rvincent7 let me know.
