### ISSUE TITLE
A duplicated paragraph

### ISSUE THREAD

**Issue by renan-bg** [dotnet/docs#20320]
On the "Properties" topic, the following sentence appears twice: first as "When the property is the target of an assignment, or the operand of ++ or --, the set accessor is invoked.", then on the next paragraph as "When a property is referenced as the target of an assignment or as the operand of ++ or --, the set accessor is invoked with an argument that provides the new value.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks again @renan-bg I've opened #20336 to address this.
