### ISSUE TITLE
Stop is missing from the keywords list

### ISSUE THREAD

**Issue by SpaceOgre** [dotnet/docs#20329]
I get this warning:

> Rename virtual/interface member IFileWatcher.Stop() so that it no longer conflicts with the reserved language keyword 'Stop'. Using a reserved keyword as the name of a virtual/interface member makes it harder for consumers in other languages to override/implement the member.

But I can't find it on the list on this page, it should be updated (or the warning is wrong).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I don't think C# have a keyword named "Stop". It's a VB keyword.

The analyzer does seem to always lookup for all keywords regardless of the language.

https://github.com/dotnet/roslyn-analyzers/blob/0cbdd68e14722e911d50eee64ee95823b3ffa09c/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywords.cs#L239

@mavasani, Is this behavior intended?

**Comment by Youssef1313** [comment]
@svick Ahh, I didn't read the message till the end 😄 

@SpaceOgre I think you can do one of the following:

- Rename the method as suggested. This option might not always be actionable.
- Suppress the rule.

**Comment by mavasani** [comment]
Yes, this is by design.

**Comment by SpaceOgre** [comment]
Thank you for the clarification. It would be nice if this was added to the documentation then for the analyzer error code. Will create an issue for that over there.
