### ISSUE TITLE
Update for .NET 5

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#20326]
~@mkArtakMSFT~ @richlander how do you want to update this for .NET 5? Something like

```
::: moniker range=">= aspnetcore-5.0"
Prior to .NET 5, there were two versions of .NET:

* .NET Core 3 and prior: An  open-source, cross-platform framework .
* .NET Framework: Supports Web Forms, Web Apps, WCF services, Windows Workflow Foundation

For more information, see [the 3.1 version of this document](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server?view=aspnetcore-2.1]

.NET 5 is the next version of .NET Framework and .NET Core. For more information, see [Introducing .NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/)

<!-- Preceding link will be change to doc once that is published -->

::: moniker-end

::: moniker range="< aspnetcore-5.0"
// Original article here
::: moniker-end
```

Update, I don't think this repo supports monikers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
> Update, I don't think this repo supports monikers.

I think pivots is a similar thing:

https://github.com/dotnet/docs/blob/master/docs/zone-pivot-groups.yml

**Comment by tdykstra** [comment]
@Rick-Anderson This article was updated for .NET 5 after you created this issue - do you think it needs additional work or can we close the issue?
