### ISSUE TITLE
DWORD_PTR

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#20331]
What managed type should we use for DWORD_PTR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678eaef3-eec4-dc52-1234-37e220f84682
* Version Independent ID: 38b09163-65d8-4d6c-1394-401e080ed6f0
* Content: [Marshaling Data with Platform Invoke](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-data-with-platform-invoke)
* Content Source: [docs/framework/interop/marshaling-data-with-platform-invoke.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-data-with-platform-invoke.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Since it is an [unsigned long type](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/66d61dd8-2191-4a37-b963-e49bf0dc2579), use System.UInt32 (`uint` in C#).
