### ISSUE TITLE
unmanaged article is confusing

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20330]
> A type is an **unmanaged type** if it's any of the following types:
>
> - `sbyte`, `byte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`, `char`, `float`, `double`, `decimal`, or `bool`
> - Any [enum](enum.md) type
> - Any [pointer](../../programming-guide/unsafe-code-pointers/pointer-types.md) type
> - Any user-defined [struct](struct.md) type that contains fields of unmanaged types only and, in C# 7.3 and earlier, is not a constructed type (a type that includes at least one type argument)
>
> Beginning with C# 7.3, you can use the [`unmanaged` constraint](../../programming-guide/generics/constraints-on-type-parameters.md#unmanaged-constraint) to specify that a type parameter is a non-pointer, non-nullable unmanaged type.

The first paragraph indicates that "Any pointer" is "unmanaged". However, the second paragraph indicates that `unmanaged` constraint is used to specify a type parameter that is non-pointer type.

It feels like a contradiction to me (or probably misunderstanding?).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e5d75f-07a3-e7ee-2842-ac754bdd2e41
* Version Independent ID: 4a3622fb-7d09-78ec-ba38-b88001475018
* Content: [Unmanaged types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types)
* Content Source: [docs/csharp/language-reference/builtin-types/unmanaged-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/unmanaged-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Youssef1313 unmanaged constraint specifies only non-pointer unmanaged types (in general, pointer types don't play with c# type constraints), that is, a strict subset of all unmanaged types. There is no contradiction here, but not the best naming of the constraint and the type set. But this is what it is.

**Comment by Youssef1313** [comment]
@pkulikov Thanks for clearing it.

Do you think it's worth to change the wording or just keep as is and close this issue? Perhaps the following is more clear?

> Beginning with C# 7.3, you can use the unmanaged constraint to specify that a type parameter is a non-nullable unmanaged type (excluding pointer types).

**Comment by pkulikov** [comment]
To me, the current wording is clearer than the suggested one.
