### ISSUE TITLE
A typo.

### ISSUE THREAD

**Issue by renan-bg** [dotnet/docs#20334]
There's a typo on the topic "Virtual, override, and abstract methods": "<ins>Aa</ins> virtual method declaration introduces a new method."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#other-function-members)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for creating this @renan-bg 

I just opened a PR to fix this.  In the future, when you find these issues, you can click the "edit" button (it looks like a pencil), and submit a quick fix. That may save us both some time.
