### ISSUE TITLE
IAsyncDispose not clear when using mixing with owned resources that implement IDisposable only

### ISSUE THREAD

**Issue by davisnw** [dotnet/docs#20354]
The article / examples are not clear how to handle the case where you have multiple managed resources, but some implement both `IAsyncDisposable / IDisposable` and some only implement `IDisposable`.

For example suppose I'm implementing a custom `Stream`, that needs to wrap other diposable resources.  The base class is part of .net framework, so I don't have the option of simply omitting `IAsyncDisposable`.  Further suppose that I also don't control the code of any of the resources I rely on, so modifying the interfaces is not an option.

```csharp

//I don't control this code
public class SomeDisposableResource : IDisposable
{
    ...
]

//I don't control this code
public class SomeAsyncDisposableResource : IDisposable, IAsyncDisposable
{
  ....
}

//I only control this code in the derived class.  Stream implements both IDisposable and IAsyncDisposable
public class MyCustomStream : Stream
{
     private SomeDisposableResource someDisposableResource = new SomeDisposableResource();
     private SomeAsyncDisposableResource someAsyncDisposableResource = new SomeAsyncDisposableResource();

     //What is the proper way to dispose of both someDisposableResource  and someAsyncDisposableResource 
     //for the IDisposable and IAsyncDisposable methods?
     //Note also (probably because it is abstract) that Stream does not provide DisposeAsyncCore
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @davisnw
Thank you so much for posting this issue. We really appreciate it. I'll try to update the article to cover these details next month.
