### ISSUE TITLE
Horrible code example

### ISSUE THREAD

**Issue by CoastalData** [dotnet/docs#20358]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f9a6a9-2a5a-f348-7870-e533942b5291
* Version Independent ID: 4495d159-ef3f-1b8c-72f4-6933432fc628
* Content: [How to: Write Text to Files - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files)
* Content Source: [docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by IEvangelist** [comment]
Hi 👋 @CoastalData
Thank you so much for posting this issue. We welcome community contributions. If you would like to help us improve these examples, we'd be happy to review them. What improvements would you suggest? I'm marking this as "up-for-grabs".

**Comment by bnewcomb** [comment]
Is he referring to the inconsistency between the code snippet and the explanation?

This example writes the line "This is new text."
to 
This example writes the line "This is new text to be added."
