### ISSUE TITLE
Update .NET Core Docker Doc

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/docs#2035]
# Update .NET Core Docker Doc

This page needs to be updated: [Building .NET docker Images](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images)

## Needed fixes
- [ ] Update tags
  - [ ] There is no longer a `core` tag
  - [ ] There is no longer an `onbuild` tag
  - [ ] `core-deps` should change to `deps`
- [ ] Yeoman is out of date for current VS Code projects

## Overall Different Approach
-  Consider splitting Image documentation into a separate doc than VS Code and Docker use.
- Add links to aspnetcore images.
- Explain different OS base images better. Link to more Docker documentation on the different Docker clients (Mac, Linux, Windows).
- Add multi-stage build explanation for using both sdk and runtime images in Dockerfile
- Provide links at bottom for related .NET Framework images doc

**Comment by BillWagner** [comment]
@kendrahavens For the list task: do you mean the yeoman generator generates out-of-date assets, or that the referenced doc describes out of date assets?

**Comment by BillWagner** [comment]
We should probably wait until [this fix](https://github.com/dotnet/announcements/issues/14) is live before we update this. It will be much simpler.

cc @kendrahavens

**Comment by kendrahavens** [comment]
The yeoman generator itself is out of date. Could we make a doc just outlining what yeoman sets up?

The multi-arch change is now in the official .NET docker repo.

**Comment by JRAlexander** [comment]
Replaced with Revise Building Docker Images for .NET Core Applications Topic #2652
