### ISSUE TITLE
Document the difference between WarningLevel and AnalysisLevel

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20355]
The documentation for -warn compiler option should mention notes about AnalysisLevel, is it the same as WarningLevel? is it just a new name for it?

https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/

This blog mentions that the default value for AnalysisLevel is 5. However, the default value for WarningLevel is 4.

All these need to be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warninglevel)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This new article should cover all the information about warning waves.
