### ISSUE TITLE
obsolete sql server image in docker-compose.yml

### ISSUE THREAD

**Issue by pajabyte** [dotnet/docs#20353]
The docker.compose.yml displayed in the docs is not working. MS SQL docker image has been moved to: mcr.microsoft.com/mssql/server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: c8fefbe8-6f9b-209a-3563-2cb51384707c
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#step-4-define-your-services-in-docker-composeyml-when-building-a-multi-container-docker-application)
* Content Source: [docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by pajabyte** [comment]
Hey there, this seems like a small enough issue and I'd like to fix that. Can I work on this? I'd just substitute `mssql-server-linux:latest` for `mcr.microsoft.com/mssql/server:latest`

**Comment by netchkin** [comment]
Hey, this seems like a small issue, can I fix this? I'd just substitute `mssql-server-linux:latest` in the docs for `mcr.microsoft.com/mssql/server:latest`, which is the current address for sql server linux image.

**Comment by Youssef1313** [comment]
@netchkin Sure you can submit a PR to fix this. [Here is how](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).
