### ISSUE TITLE
Redundant Directory.Exists check

### ISSUE THREAD

**Issue by patgoull** [dotnet/docs#20350]
The following Directory.Exists check is redundant since Directory.CreateDirectory explicity states : Creates all directories and subdirectories in the specified path unless they already exist.
```csharp
// If the destination directory doesn't exist, create it.
        if (!Directory.Exists(destDirName))
        {
            Directory.CreateDirectory(destDirName);
        }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d050f686-38eb-bb76-5747-9e138f4da679
* Version Independent ID: 93b69d5a-5df1-c0e1-930d-2f5ee1c1fe6e
* Content: [How to: Copy directories](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories)
* Content Source: [docs/standard/io/how-to-copy-directories.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-copy-directories.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
