### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#20352]
[Enter feedback here]
Era 2017 describing future specs. Now we ARE 2020 and C# 8 is concrete reality. Update links!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Unfortunately, the article is correct and there are no links to update, because there are no specs for more recent versions of C#. Though work is being done to update the spec, with most recent activity at https://github.com/dotnet-foundation/projects/issues/90.

**Comment by BillWagner** [comment]
@DickBaker It's correct that the standardization effort has fallen behind. The ECMA committee is actively working on updating those. 

In the meantime, we have published the [design proposals](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-7.0/pattern-matching) for all features up to and including C# 9.0. While not the standard, we hope that helps in the interim.

**Comment by DickBaker** [comment]
thanks BillW - I like the P1 tag anyway !
- seems the https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/ redirects to C# v8 but that's ok for me now after all your work with motorway toll app.

**Comment by BillWagner** [comment]
Thanks @DickBaker 

I need to fix that redirect.  PR coming....
