### ISSUE TITLE
missing a note on get /set

### ISSUE THREAD

**Issue by sizzler-5g** [dotnet/docs#20362]
I think there should be a note explaining that public properties without {get;set;} accessors will be ignored. This seems a lot more important than [serializable] options.
I've spent quite some time realising this. especially when using Generics, it is not the first thing you would think of defining.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-gb/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
If you removed `{ get; set; }`, it will become a field not a property at all. The article states that fields are not supported.

**Comment by sizzler-5g** [comment]
Hi Victor,

Thanks for the feedback.
Indeed, I have missed the two mentions of fields not being supported for serialization and deserialization.
As I'm not a "native" C# speaker I don't yet make the distinction between fields and properties naturally. (this is definitely carved in now)
Maybe a link to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields on the fields word might help emphasize this to developer coming from other C-style languages transitioning to C#?

Warm regards,

Cyrille

________________________________
