### ISSUE TITLE
Add used nuget version numbers

### ISSUE THREAD

**Issue by FloP93** [dotnet/docs#20364]
I just followed this tutorial and after finishing it i get the error: 
"System.DllNotFoundException: Die DLL "onnxruntime": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden."

I first tried it with all the newes versions:
Microsoft.ML v1.5.1
Microsoft.ML.ImageAnalytics v1.5.1
Microsoft.ML.OnnxRuntime v1.4.0
Microsoft.ML.OnnxTransformer v1.5.1

but i get the error at the top.
I think this could be because i use the newest versions so it would be helpful to find which versions of the nuget packages were used so i can adjust my solution.

Unless this is a different error and it works for the newest versions, but then i have no idea where it comes from as i am not that experienced in onnx and ml.net just yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by FloP93** [comment]
I don't know if this helps but:
Today I updated my Visual Studio and added workloads for c++ and python and now the same code runs without problems.
I did NOT however change any of the nuget packages or anything on the code itself.

**Comment by luisquintanilla** [comment]
Hi @FloP93 

Great to hear you got it working! ML.NET 1.5.1 had a regression and although it's unclear whether that may have caused your issue, we suggest skipping that version and moving up to 1.5.2. Closing this issue for now.
