### ISSUE TITLE
Automatically infer WinExe output type for WPF and Winforms applications

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#20373]
## Automatically infer WinExe output type for WPF and Winforms applications

We are now automatically setting the OutputType to WinExe if the application is WPF or WindowsForms.  This will suppress any console windows that would start up if the OutputType was set to exe. https://github.com/dotnet/sdk/pull/12448 

### Version introduced

.NET 5 Preview 8

### Old behavior
We would use the value set in the project.

### New behavior
Default the OutputType value to WinExe

### Reason for change
We assume most users do not want a console window coming up during execution of a WPF or WindowsForms and with these application types using the .NET sdk instead of the WindowsDesktop SDK, we wanted to ensure the right default was set.  Further, when add support for targeting iOS and Android in .NET Core, it will make it easier to multi-target between multiple platforms if they all use the same output type.

### Recommended action
Set `<DisableWinExeOutputInference>true</DisableWinExeOutputInference>` in your project file to revert to the old behavior.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
@marcpopMSFT I've updated the description with my suggestions, most importantly by fixing a typo from `not` to `now`.

**Comment by Unknown6656** [comment]
Ahhh .... this explains the bug I am having.
(and which an other user has too: https://developercommunity.visualstudio.com/content/problem/1176945/console-app-broken-when-using-usewindowsforms-in-n.html)

**Comment by gewarren** [comment]
@marcpopMSFT Was this change intended to apply to projects that target .NET Framework as well? See #21952.
