### ISSUE TITLE
Replace msdn links with links to docs where possible

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2037]
- [ ] 1 - We have a lot of links that still go to MSDN:
  - [ ] **dotnet/docs:** https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22msdn.microsoft.com%22&type= (current count is at 154 links)
  - [ ] **dotnet/samples:** https://github.com/dotnet/samples/search?utf8=%E2%9C%93&q=%22msdn.microsoft.com%22&type= (current count is at 207 links)
  - [ ] **dotnet/dotnet-api-docs:** https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=%22msdn.microsoft.com%22&type= (current count is at 2466 links)
- [ ] 2 - Not to mention all the FwLinks that could possibly be going to msdn too:
https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=fwlink&type=- related issue #3391
- [ ] 3 - We need to start replacing any mentioning of MSDN/MSDN Library. For example:
  - [x] **dotnet/docs:** https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22msdn+library%22&type=  (current count for this search is 1)
  - [ ] **dotnet/samples:** https://github.com/dotnet/samples/search?utf8=%E2%9C%93&q=%22msdn+library%22&type=  (current count for this search is 2)
  - [ ] **dotnet/dotnet-api-docs:** https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=%22msdn+library%22&type=  (current count for this search is 229)
- [ ] 4 - Replace links that go to technet 
  - [ ] **dotnet/docs:** https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=technet&type= (current count is 9)
  - [x] **dotnet/dotnet-api-docs:** https://github.com/dotnet/dotnet-api-docs/search?utf8=%E2%9C%93&q=technet&type=

Can open new issues for each subitem. 

Last updated on 08/06/19.

**Comment by morrme** [comment]
Indeed a lot!

Would you like these changes submitted in batches?

**Comment by mairaw** [comment]
I have a coworker who's trying to work on an automated solution. Don't start anything yet @morrme.

**Comment by isaac2004** [comment]
@mairaw is this open? I did something similar in aspnet repo so I can take a look here

**Comment by mairaw** [comment]
Yes @isaac2004, still open. If you look at the search results, we still have a lot of those. We've done some automated changes related to this but they didn't take care of everything. It's okay to fix these in small chunks over time as well.

**Comment by ItsPugle** [comment]
Should this be closed now, since #3282 basically resolved this?

**Comment by isaac2004** [comment]
@ItsPugle this is a pretty large issue. I have been working through it but it will take a ton of time.

**Comment by mairaw** [comment]
@isaac2004 is right. It's a massive issue. It'll take quite a few PRs to fix those.
If you click on the links from the issue description, you'll see we still have thousands of links to fix @ItsPugle.

**Comment by mairaw** [comment]
Yes, I can create sub-issues for this for sure @isaac2004. Let me know what you'd like to tackle next and I'll create a sub-issue. There are many ways to break this down. FwLinks would be harder for the community to help since to change them, I need to access an internal tool. So I'd skip those.

**Comment by ItsPugle** [comment]
I'm slightly confused with all this. With the FwLinks, what are we trying to do with them all? Are we replacing them with their target links, or is their a different forwarder etc now?

Sorry if this is a stupid question; I'm looking for some projects for [Hacktober](https://hacktoberfest.digitalocean.com/) and I saw this as interesting. I'm not confident with any relevant language (other than Markdown) so I'm not sure I'm actually able to help with this.

**Comment by mairaw** [comment]
Cool! I wasn't familiar with the event @ItsPugle. As I said, you can skip the FwLink. What we'll have to do  is to scan the FwLinks and see if they are targeting MSDN links and then either replace them here with their targets or replace the FwLInk destination internally.

Would you like me to open an issue for the third item perhaps? I could open one targeting only the Markdown files like this: https://github.com/dotnet/docs/search?l=Markdown&q=%22msdn+library%22&type=&utf8=%E2%9C%93

**Comment by ItsPugle** [comment]
That'd be good if you could open that issue targeting Markdown :smile:! I can get to work with them straight afterwards :) I won't be the fastest with it, since I've got to edit using GitHub not my local IDE due to the 400MB lol

**Comment by isaac2004** [comment]
@ItsPugle highly recommend VS Code if you have the HDD space

**Comment by ItsPugle** [comment]
I've considered VSCode, but I've found that the GUI is too confusing for me as a basic "developer", if I can call myself that. I also switch back and forth between projects all the time, so the process for switching projects on VSCode is 👎  for me.

**Comment by mairaw** [comment]
@cartermp do you know when the F# content is migrating from MSDN? I've excluded the fsharp older from this wave of updates because we still have content hosted on MSDN.
