### ISSUE TITLE
[Placeholder] Change in deps.json impacting single file applications

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#20376]
### Version introduced

.NET Core SDK 5.0.100

### Old behavior

The MSBuild `PublishDepsFilePath` property would be the path to the app's deps.json path in the output directory for non single-file applications, and it would be a path in the intermediate directory for single file apps.

### New behavior

The PublishDepsFilePath is empty for single file applications and a new `IntermediateDepsFilePath` specifies the deps.json location in the intermediate directory.  Additionally, for non single-file applications, the deps.json file may not be copied to the output directory (the path specified by `PublishDepsFilePath`) until later in the build.

### Reason for change

Partly this was due a refactoring of the publish logic in order to support [improved single file apps](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md) in .NET 5.

Additionally, the `PublishDepsFilePath` property is empty for single file apps to help guard against targets that are supposed to rewrite the deps.json file doing so after the deps.json has already been bundled, thus silently not affecting the app.

### Recommended action

Targets that rewrite the deps.json file should generally do so using the `IntermediateDepsFilePath` property.

### More details

Discussion of these changes can be found in the following PRs:

https://github.com/dotnet/sdk/pull/11462
https://github.com/dotnet/sdk/pull/11527

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
@marcpopMSFT I've filled out the issue description

@dougbu @swaroop-sridhar Could you review this?

**Comment by dougbu** [comment]
@dsplaisted this looks good to me. Nits only:
1.
``` diff
- The PublishDepsFilePath is empty for single file applications.
+ The PublishDepsFilePath is empty for single file applications and a new `IntermediateDepsFilePath` specifies the deps.json location in the intermediate directory.
```
2.
``` diff
-  copied to the output directory (the path specified by PublishDepsFilePath until later in the build.
+  copied to the output directory (the path specified by PublishDepsFilePath) until later in the build.
```
3. If the terms "output directory" and "intermediate directory" might be misinterpreted, could be worth mentioning `$(OutputPath)` and `$(IntermediateOutputPath)` where they're interoduced.
