### ISSUE TITLE
Running XUnit tests requires a new version of XUnit

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#20370]
## Running XUnit tests with dotnet test requires a new version of XUnit
A new version of XUnit is required for running tests using the .NET CLI when targeting .NET 5.0

### Version introduced
.NET 5 SDK preview 8

### New behavior
`No test is available in <assembly> Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.`

### Recommended action
Update `xunit.runner.visualstudio` package to version 2.4.3

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
I believe that the breaking change was reverted in NuGet, so as of RC1 (I think) the old package should still work.  So probably we don't need to doc this for RTM.

Is this correct @nkolev92 @nohwnd?

**Comment by nkolev92** [comment]
@zivkan reverted it the change. 

Did we ever figure out how the test runner got that short folder value?
How are the new NuGet bits ingested?

**Comment by nohwnd** [comment]
@nkolev92 it was via TestPlatform, I fixed test platform to be able to work with the short value, and it got passed along to the adapter. 

I can confirm it works with the old adapter. Details of the affected builds are here in 1. and 2. https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md#preview-8-1

**Comment by gewarren** [comment]
@marcpopMSFT Can we close this issue?
