### ISSUE TITLE
WPF and Winforms applications will require a new sdk and TargetPlatform

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#20371]
## WPF and Winforms applications should use the .NET sdk and Target net5.0-windows

There is a new TFM in .net 5.0 which replaces `netcoreapp` and `netstandard`.  You can find more details on this change here: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md

Windows Forms and WPF projects which retarget to .NET 5.0 will need to change the `TargetFramework` to `net5.0-windows` instead of just net5.0.  It is also recommended to change the Project `Sdk` attribute on the first line of the project from `Microsoft.NET.Sdk.WindowsDesktop` to `Microsoft.NET.Sdk`.

### Version introduced

.NET 5.0 preview 8

### Old behavior
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>

```

### New behavior
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>

```
---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
@marcpopMSFT I've updated the issue description with my suggestions
