### ISSUE TITLE
[Placeholder] Directory.Packages.props is now imported by default

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#20374]
## Directory.Packages.props is now imported by default

NuGet's MSBuild .props files now automatically import a file named Directory.Packages.props if one is found in the project folder or any of its ancestors.

If there was previously a file with this name, this automatic import could change behavior of the build (for example importing the file when it wasn't before, or changing the ordering of when it is imported).

### Version introduced

.NET 5 preview 8

### Reason for change

Support central package versioning in NuGet.

### Recommended action

Rename the existing Directory.Packages.props file if it should not be imported automatically.

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
@rconard @cristinamanum Can you review this breaking change description, confirm when the automatic import of Directory.Packages.props was introduced, and provide a link to the docs for central package version management?
