### ISSUE TITLE
Incorrect Regex anchor code used in example

### ISSUE THREAD

**Issue by Gen-CA** [dotnet/docs#20384]
[Enter feedback here]

In the example immediately before the heading "Conditional matching with an expression" the last line ("End the match at a word boundary") uses "\d" as the anchor code. This is incorrect. It should be "\b".

This is on **line 57** of the file: alternation-constructs-in-regular-expressions.md:
|`\d`|End the match at a word boundary.|   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af3731f-af2c-e8e6-cb90-51311eb350fb
* Version Independent ID: 3c03bf87-5592-d816-5b86-5b34b6595e6f
* Content: [Alternation Constructs in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/alternation-constructs-in-regular-expressions?view=netcore-3.1#feedback)
* Content Source: [docs/standard/base-types/alternation-constructs-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/alternation-constructs-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by hiMinju** [comment]
I think so too.
I'll make a PR for this issue.
