### ISSUE TITLE
config files lost their inheritance look-and-feel and links

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2038]
I think it was not during this migration, but on the migration to our last tool, that our configuration docs lost some of its formatting.

Compare:
https://msdn.microsoft.com/en-us/library/7a151659-b803-4c27-b5ce-1c4aa0d5a823(v=vs.100)
https://docs.microsoft.com/en-us/dotnet/articles/framework/configure-apps/file-schema/compiler/compiler-element

![image](https://cloud.githubusercontent.com/assets/12971179/25472463/37656366-2ae0-11e7-9af8-9a968ede3fd4.png)
vs.
![image](https://cloud.githubusercontent.com/assets/12971179/25472481/483fedaa-2ae0-11e7-8c70-92372504342b.png)

I think it'd be good to restore that at some point.

**Comment by BillWagner** [comment]
I think this is now fixed.  Can you verify and close?

**Comment by BillWagner** [comment]
@rpetrusha Do you know of current examples? Or, can this be closed?

**Comment by rpetrusha** [comment]
@BillWagner, it's still a problem.

**Comment by nemrism** [comment]
These PRs should fix the issue for the whole configuration docs pages
