### ISSUE TITLE
[WinForms] DataGridView-related API validate state and throw IOE

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#20392]
## Selected DataGridView-related API validate object state and throw `InvalidOperationException`.

Selected API now validate object state and throw `InvalidOperationException` where previously a `NullReferenceException` could be thrown, if APIs were invoked without being constructing with a valid `Owner`.
Throwing `InvalidOperationException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Old behavior

The listed API would throw `NullReferenceException` if invoked with `null` input arguments.

### New behavior

The listed API would throw `InvalidOperationException` if invoked without having a valid `Owner` property value (in addition to the existing exceptions).

### Reason for change

Throwing `InvalidOperationException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Recommended action

- Review and, if necessary, update the code to prevent constructing the affected types with `Owner` as `null`.

### Category

- Windows Forms

#### Affected APIs

* [DataGridViewButtonCell.DataGridViewButtonCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewbuttoncell.datagridviewbuttoncellaccessibleobject)
    - [x]  [DataGridViewButtonCell.DataGridViewButtonCellAccessibleObject.DoDefaultAction Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewbuttoncell.datagridviewbuttoncellaccessibleobject.dodefaultaction), property `Owner`
* [DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcheckboxcell.datagridviewcheckboxcellaccessibleobject)
    - [x]  [DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.DefaultAction Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcheckboxcell.datagridviewcheckboxcellaccessibleobject.defaultaction), property `Owner`
    - [x]  [DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.State Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcheckboxcell.datagridviewcheckboxcellaccessibleobject.state), property `Owner`
    - [x]  [DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.DoDefaultAction Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcheckboxcell.datagridviewcheckboxcellaccessibleobject.dodefaultaction), property `Owner`
* [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject)
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.Bounds Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.bounds), property `Owner`
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.DefaultAction Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.defaultaction), property `Owner`
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.Name Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.name), property `Owner`
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.Parent Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.parent), property `Owner`
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.DoDefaultAction Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.dodefaultaction), property `Owner`
    - [x]  [DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.Navigate(AccessibleNavigation) Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewcolumnheadercell.datagridviewcolumnheadercellaccessibleobject.navigate), property `Owner`
* [DataGridViewImageCell.DataGridViewImageCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewimagecell.datagridviewimagecellaccessibleobject)
    - [x]  [DataGridViewImageCell.DataGridViewImageCellAccessibleObject.DoDefaultAction Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewimagecell.datagridviewimagecellaccessibleobject.dodefaultaction), property `Owner`
* [DataGridViewLinkCell.DataGridViewLinkCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewlinkcell.datagridviewlinkcellaccessibleobject)
    - [x]  [DataGridViewLinkCell.DataGridViewLinkCellAccessibleObject.DoDefaultAction Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewlinkcell.datagridviewlinkcellaccessibleobject.dodefaultaction), property `Owner`

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@RussKie Can these types of issues be closed now that .NET 5 is drawing to a close?

**Comment by RussKie** [comment]
Yes, I'll have new ones opened for 6.0 😉 
Thank you for your help.
