### ISSUE TITLE
'Build data driven tests' section does not mention the user-defined helper classes 'CodeFixVerifier' and 'DiagnosticVerifier'

### ISSUE THREAD

**Issue by vamuzumd** [dotnet/docs#20403]
The section '[Build data driven tests](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#build-data-driven-tests)' has code snippets for methods like 'VerifyCSharpDiagnostic(testCode)' and 'VerifyCSharpFix(test, fixTest);' belonging to user-defined class 'DiagnosticVerifier.cs' which are misconstrued to be built-in methods until I stumbled upon the compilation errors followed by [Github source code for MakeConst.](https://github.com/dotnet/samples/tree/master/csharp/roslyn-sdk/Tutorials/MakeConst) 
Perhaps a pointer github link to helper classes 'CodeFixVerifier' and 'DiagnosticVerifier' will be useful and time-saving while explaining these methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@adegeo This didn't get the correct label based on the bot config:

https://github.com/dotnet/docs/blob/b751bac821dbd7ad38fe625be2c7705a24363145/.ghal.rules.json#L343-L344

**Comment by BillWagner** [comment]
Thanks @vamuzumd  for pointing this out. I've added it to our backlog for when we next update this article.
