### ISSUE TITLE
#if directive page should mention csproj's <DefineConstants>

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20414]
The <DefineConstants> tag for csproj files isn't documented anywhere. It should be documented and linked in this page.

One of the most useful usages of <DefineConstants> along with #if directive is when a code file is referenced in multiple projects and a small part of the code needs to be different for each project (for example, due to one of these project not having access to a certain API).

```csharp
#if CONSTANT_DEFINED_IN_PROJECT1
    // Use API available to project1
#else
    // Use API available to project2
#endif
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Youssef1313 

Are you saying this page should provide information about how to set variables in the csproj file? If so, I agree.
