### ISSUE TITLE
Missing Libunwind

### ISSUE THREAD

**Issue by automateyournetwork** [dotnet/docs#20437]
**Issue description**

Trying to build TFS 2018 Agent on RHEL 8 

Run ./config.sh
libunwind.so.8 => not found
libunwind-x86_64.so.8 => not found
Dependencies is missing for Dotnet Core 2.0
Execute ./bin/installdependencies.sh to install any missing Dotnet Core 2.0 dependencies.

Run installdependencies.sh

No match for argument: libunwind

Error: Unable to find a match: libunwind
'yum' failed with exit code '0'
Can't install dotnet core dependencies.
You can manually install all required dependencies base on follwoing documentation
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

Follow the steps on the document about netcore2x - same issue - no reference to how to install the 2 libunwind dependancies 

**Target framework**

  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
@adegeo Can you look at this? It looks related to linux install.

**Comment by adegeo** [comment]
@automateyournetwork If you're on RHEL, .NET Core is installable directly without doing so manually. Here is the page for RHEL: https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel

Looking through RHELs documentation, I don't think 2.0 is available, it seems 2.1 is the lowest. I would try installing 2.1 and see if that fixes the problem.

I believe the command is:

```
sudo dnf install aspnetcore-runtime-2.1
```
of
```
sudo yum install dotnet-sdk-2.1 -y
```

**Comment by ItielBeeri** [comment]
I've tried the same - installing the TFS 2018 agent on CentOS 8, and got the very same results.
Indeed, dotnet core 2.0 seems to be unavailable. Installing 2.1 doesn't help, the original error keeps:
```
libunwind.so.8 => not found
libunwind-x86_64.so.8 => not found
Dependencies is missing for Dotnet Core 2.0
Execute ./bin/installdependencies.sh to install any missing Dotnet Core 2.0 dependencies.
```
I can replace neither the Linux distribution/version nor the TFS version.
Any ideas?

**Comment by bardie** [comment]
Installation:

sudo yum -y install epel-release

**Comment by marlonsingleton** [comment]
@BillWagner and @adegeo this issue is still ongoing. It looks like Red Hat made a decision to remove libunwind.so from their RHEL 8 build. 

Reference:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index

**Comment by adegeo** [comment]
Unfortunately I can't really answer that. I don't know where you would find the package. You can always post on the product group repo, they'll have better information. https://github.com/dotnet/runtime/issues

**Comment by DaniilShmelev** [comment]
Hi @automateyournetwork, @ItielBeeri! Could you please specify which versions of the agent caused issues for you? I've been able to use 2.166.1 and 2.186.1 without any issues.

**Comment by DaniilShmelev** [comment]
We've found that there are some issues when running 2.163.1 as a service, but it's not related to libunwind library missing. As a workaround you could use agent 2.163.1 in interactive mode or switch to a newer version of the agent (2.186.1 works fine both as a service and in the interactive mode).

**Comment by DaniilShmelev** [comment]
@automateyournetwork, @ItielBeeri have you tried running the newer versions of the agent?
