### ISSUE TITLE
Retries count in MSBuild Copy tasks

### ISSUE THREAD

**Issue by matkoch** [dotnet/docs#20434]
https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2019

<img width="590" alt="image" src="https://user-images.githubusercontent.com/5005566/92110761-7ee11880-edeb-11ea-92b3-2d24e788ae62.png">

**Comment by Youssef1313** [comment]
@matkoch This article doesn't seem to belong to this repository. You can use [this link](https://github.com/MicrosoftDocs/visualstudio-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20160a060d-7dc1-5826-8beb-f47097d0928f%0A*%20Version%20Independent%20ID%3A%20cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7%0A*%20Content%3A%20%5BCopy%20Task%20-%20Visual%20Studio%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fmsbuild%2Fcopy-task%3Fview%3Dvs-2019)%0A*%20Content%20Source%3A%20%5Bdocs%2Fmsbuild%2Fcopy-task.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fvisualstudio-docs%2Fblob%2Fmaster%2Fdocs%2Fmsbuild%2Fcopy-task.md)%0A*%20Product%3A%20**visual-studio-windows**%0A*%20Technology%3A%20**msbuild**%0A*%20GitHub%20Login%3A%20%40ghogen%0A*%20Microsoft%20Alias%3A%20**ghogen**) to open an issue in the correct repository.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5815
