### ISSUE TITLE
The statement "Fortunately, AspNetCore.Diagnostics.HealthChecks also provides AspNetCore.HealthChecks.UI" is flase, in my opinion

### ISSUE THREAD

**Issue by LiviuSosu** [dotnet/docs#20473]
Hi,

I will attach screenshots  so that you will see  that this package "AspNetCore.Diagnostics.HealthChecks" does not contain " AspNetCore.HealthChecks.UI". 

![HealthChecks_missing_aspNetCote Health3](https://user-images.githubusercontent.com/11800340/92305376-6f023980-ef8f-11ea-8790-672ca07db3e9.PNG)
![HeathChecks_missing_AspNetCore HealthChecks UI](https://user-images.githubusercontent.com/11800340/92305377-6f9ad000-ef8f-11ea-8822-175ee8a13575.PNG)
![HeathChecks_missing_AspNetCore HealthChecks2 UI](https://user-images.githubusercontent.com/11800340/92305378-70336680-ef8f-11ea-9136-8a73527f367f.PNG)

 perhaps you might whant to check.

As you can see, the line bellow:

`services.AddHealthChecksUI();`

Shoild I just change it to?

`services.AddHealthChecks();`

But I will not get the UI page, as I will not be abl to using this:

` app.UseHealthChecksUI(config => config.UIPath = "/hc-ui");`

Thanks,
Liviu
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98bdd99-d89d-8720-9018-25f73dcfdbd8
* Version Independent ID: 61a8ff5d-02ea-ec2b-2624-b8afa66f44d0
* Content: [Health monitoring](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hello @LiviuSosu, Thank you for reaching out. 

Yes, you will need to install `AspNetCore.HealthChecks.UI` nuget package separately to leverage the `HealthChecks UI` component in your application as it has been mentioned in the section [Use watchdogs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health#use-watchdogs)

Please note, all of these separate nuget packages originally belong to one project, called [`AspNetCore.Diagnostics.HealthChecks`](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks). 
You would require to install individual package based on the need of your application.

You can refer the [`WebStatus`](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Web/WebStatus) project under `eShopOnContainers` repo for actual implementation.

Hope this helps !

**Comment by LiviuSosu** [comment]
Hi @sughosneo ,

Thanks for your answer. I Just gave some feedbac, that I do not find the documentation 100% correct. I thought You may want to correct it.

**Comment by nishanil** [comment]
I see that this is already mentioned under the watchdog section: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health#use-watchdogs. The sample code also shows the extension method to be part of the AspNetCore.HealthChecks.UI package. If you see any particular statement in that page that is misleading, please let us know.
