### ISSUE TITLE
The visual diagrams not relate to actual timeline

### ISSUE THREAD

**Issue by harpalsingh1993** [dotnet/docs#20485]
I am not able to relate the 2nd visual diagram's timeline and its program. I am in confusion why the toast task has so much empty space in diagram(in program it has to complete 1/2 of time than egg or bacon).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @harpalsingh1993 - that is a good observation. I can see how that is confusing, I will update this image. Thank you.

**Comment by nms-snagle** [comment]
The code calls a method `ApplyButter(toast);` but the diagram does not show it. The diagram only shows a call to `ApplyJam(toast);`
