### ISSUE TITLE
Typo on `new()`?

### ISSUE THREAD

**Issue by umbarov** [dotnet/docs#20488]
Text from the page:

Another nice use for this feature is to combine it with init only properties to initialize a new object. The parentheses on new are optional:
```cs
WeatherStation station = new() { Location = "Seattle, WA" };
```

If we remove parentheses from `new()`, it will be an anonymous type? Not object of `WeatherStation`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@umbarov 

The article is correct. Because the variable is explicitly typed on the left side of the assignment, the variable *is* a type of `WeatherStation`. You can try it yourself by adding the following:

```csharp
Console.WriteLine(station.GetType());
```

I'll close this as an answered question.

**Comment by svick** [comment]
@BillWagner The code is correct, but the text isn't and should be changed. "The parentheses on `new` are optional" seems to imply that the following code would be also correct, but that's not true:

```c#
WeatherStation station = new { Location = "Seattle, WA" };
```

If that sentence is trying to say something else, then I have no idea what, and it should be rephrased.

**Comment by BillWagner** [comment]
Thanks for correcting me @svick 

I had misread the issue. Reopening and self-assigning.

**Comment by umbarov** [comment]
The code will not compile if we remove the parentheses.
![image](https://user-images.githubusercontent.com/28846397/92512710-7c2d5b80-f20f-11ea-9a35-9725d0682c85.png)
