### ISSUE TITLE
Wrong clerification of the terms statement and expression 

### ISSUE THREAD

**Issue by mpostol** [dotnet/docs#20483]
`T result = await SomeTaskMethodAsync<T>();` looks like statement but not expression.
`await SomeTaskMethodAsync()`` is rather an expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async return types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @mpostol This could be explained better.

The point is that `await` can be either an expression or a statement, depending on its operand. When the operand is a `Task`, `await` is parsed as a statement: there is no result.  When the operand is a `Task<T>`, `await` is parsed as an expression, and it's result is of type `T`.

I've added this to our backlog to update.

**Comment by pkulikov** [comment]
@BillWagner I think @mpostol refers to *declaration * statement `T result =...`. I think any expression may be at right

**Comment by mpostol** [comment]
To make sure the C# Language Specification must be revisited and referred to.  Sec. 1.4 and 1.5 provides a detailed description. Anyway if we have x=<something> we have an assignment statement.  The mentioned section numbers could change because I have noticed my specification is very old and cannot find a new one right now.
