### ISSUE TITLE
WPF documentation is not available anymore (sub https://docs.microsoft.com/en-us/dotnet/framework/wpf )

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/docs#20487]
**Issue description**
When using bing to get to the documentation for wpf with `wpf docs microsoft` as keywords, a nice summary with a couple of links is provided.
all those lead to sub-pages of https://docs.microsoft.com/en-us/dotnet/framework/wpf
but that page isn't found anymore.

this leads to people thinking wpf being (less /un)supported, which is not great.

I wasn't sure whether to create the issue here or at the docs.microsoft.com repo...

**Target framework**
- [ ] .NET Core
- [X] .NET Framework
- [ ] .NET Standard

**Comment by IEvangelist** [comment]
Tagging @adegeo

**Comment by adegeo** [comment]
This was fixed yesterday. Sorry for the confusion.
