### ISSUE TITLE
F# Style Guide

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#2049]
F# lacks an official style guide.  This is one of the main things people new to a language come to look for.  The lack of an F# style guide to help answer questions about "how do I write this stuff correctly?" is an inhibitor to F# adoption.

The [Fantomas](https://github.com/dungpa/fantomas/blob/master/docs/FormattingConventions.md) formatting conventions are a great starting point for this.

**Comment by cartermp** [comment]
@dungpa, would you be okay with me lifting content from [Formatting Conventions](https://github.com/dungpa/fantomas/blob/master/docs/FormattingConventions.md) document and adding them to these docs?

**Comment by dungpa** [comment]
Sure. Feel free to use it.

But beware that F# formatting is a controversial topic. I don't think we (F# community) have agreed on any set of concrete guidelines.

**Comment by cartermp** [comment]
Agreed, it's bound to be contentious.  This issue is actually created as a result of a long discussion in the FSSF slack (cc @mathias-brandewinder).

My takeaway from the discussion that was had is that we'll never make everyone happy, but having something in official guidance from Microsoft will be a bigger net benefit than having style be completely open.  And the fact that the docs are open source does mean that it's far easier for a motivated community member to make their case about something and initiate that change.

@dsyme I'm curious about your opinions here.

**Comment by dsyme** [comment]
I'm happy to help with a style guide.

**Comment by dsyme** [comment]
@cartermp (I worked a fair bit with @dungpa on default settings for Fantomas, so we're likely close to being on the same page :) )

**Comment by JRAlexander** [comment]
@cartermp - Does this need to move to Sprint 135? Thanks!

**Comment by cartermp** [comment]
@JRAlexander Yep!

**Comment by JRAlexander** [comment]
Done!

**Comment by BillWagner** [comment]
@cartermp I believe this was fixed in #5313. Closing.

If I'm incorrect, please reopen.
