### ISSUE TITLE
The range operator time complexity

### ISSUE THREAD

**Issue by KhaledSamir** [dotnet/docs#20492]
I want to ask you about the range operator ... It's not clear on the page either this runs as O(1) time complexity or O(N) or more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges and indices - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
The range operator itself is O(1), but I don't think that's what you're actually asking about.

When you index using it, it depends on the type you're indexing. For example, if it's a `string` or an array, then the result is a copy of the specified section of the input, so the time complexity is O(N) (where N is the length of the range). On the other hand, if it's a `Span<T>` or a `Memory<T>`, the result references the same backing store, which means there is no copy and the operation is O(1).

**Comment by BillWagner** [comment]
Thanks for asking this @KhaledSamir 

@svick 's comments above are correct. The time complexity depends on the underlying type.

I'll propose that we update not the spec, but the [language reference range page](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md#range-operator-) with that information.

**Comment by pkulikov** [comment]
@BillWagner I'm not sure that information fits the reference. The reference itself links the following page for more information about indices and ranges:
https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md

That linked page discusses type context with more details. I think the information about complexity might fit that page better. What do you think?

**Comment by KhaledSamir** [comment]
@svick I see, thanks for explaining this to me. I'm really happy that C# now has this feature cause it was one of the best things I see in Python.

@BillWagner Thanks, Bill!

**Comment by KhaledSamir** [comment]
I'm closing this ticket as no further updates needed. Thanks!
