### ISSUE TITLE
Update project SDKs for .NET 5

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#20508]
For example, WPF projects now target:

```
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>net5.0-windows</TargetFramework>
<UseWPF>true</UseWPF>
```

...instead of Microsoft.NET.Sdk.WindowsDesktop.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET Core project SDK overview](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/overview.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mairaw** [comment]
Just FYI, given that .NET Core 3.1 is still the LTS version, we won't be updating tutorials on the dot.net site to .NET 5 for now.
