### ISSUE TITLE
Breaking Change: Fix param name in ActivityContext..ctor (traceOptions -> traceFlags)

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/docs#20502]
## Fix param name in ActivityContext..ctor (traceOptions -> traceFlags)

The `ActivityContext` API was added earlier in .NET 5.0 Preview 4, but there was a mistake in the constructor's argument name where `traceOptions` was used instead of `traceFlags`.  The implementation is correct but the reference assembly was wrong. dotnet/runtime#41843 fixed the argument name and this fix will ship with .NET 5.0 RC2.

### Version introduced

.NET 5.0 RC2

### Old behavior

The previous constructor signature was the following, with an argument named `traceOptions`.

```csharp
public ActivityContext(System.Diagnostics.ActivityTraceId traceId, System.Diagnostics.ActivitySpanId spanId, System.Diagnostics.ActivityTraceFlags traceOptions, string? traceState = null)

```

### New behavior

The updated constructor signature is the following, with the argument renamed to `traceFlags`.

```csharp
public ActivityContext(System.Diagnostics.ActivityTraceId traceId, System.Diagnostics.ActivitySpanId spanId, System.Diagnostics.ActivityTraceFlags traceFlags, string? traceState = null, bool isRemote = false)
```

### Reason for change

This corrects a mistake in the argument name and will improve the API, avoiding confusion by users.

### Recommended action

If the argument was being used as a named argument, update calling code to correct the argument name to match the renamed `traceFlags` name.

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [x] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs

[ActivityContext(ActivityTraceId, ActivitySpanId, ActivityTraceFlags, String, Boolean)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.-ctor?view=net-5.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
I'm not sure we need to document breaking changes from earlier preview versions. @PriyaPurkayastha ?

**Comment by jeffhandley** [comment]
I thought we needed to document these since RC1 is Go-Live and these changes land in RC2.

**Comment by jeffhandley** [comment]
I updated the description to call out that the fix goes in with RC2.

**Comment by PriyaPurkayastha** [comment]
Yes, any change in behavior from Go-Live release should be documented. In this case, breaking change is being introduced in .NET 5 RC2. So Version introduced should mention .NET 5 RC2 (not the version in which the API was introduced).

**Comment by jeffhandley** [comment]
Thanks, @PriyaPurkayastha; I'll update that.
