### ISSUE TITLE
Alpine Linux

### ISSUE THREAD

**Issue by FeliciaXmL** [dotnet/docs#20512]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca
* Version Independent ID: f066a748-0a7d-7506-3b18-c422fef13293
* Content: [Install .NET Core on Alpine - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine#scripted-install)
* Content Source: [docs/core/install/linux-alpine.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-alpine.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@FeliciaXmL Hello. I'm not sure what issue you're reporting as you didn't add any details where it says `Enter feedback here`. Can you please elaborate?
