### ISSUE TITLE
Last code sample is incorrect

### ISSUE THREAD

**Issue by elninoisback** [dotnet/docs#20534]
Please check the last code sample given here. It should contain an explicitly declared variable. It seems like a classic copy-paste error.

string numberAsString = "1640";
// Missing the following line
// int number;
if (Int32.TryParse(numberAsString, out var number))
    Console.WriteLine($"Converted '{numberAsString}' to {number}");
else
    Console.WriteLine($"Unable to convert '{numberAsString}'");
// The example displays the following output:
//       Converted '1640' to 1640

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6c8480-77a7-7505-5224-0efe15b9b755
* Version Independent ID: 993250d1-108c-ab1a-886e-ca1bfa9104c7
* Content: [out parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/out-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/out-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking the question @elninoisback 

The comment by @JohyPark is correct. Starting with C# 7, the declaration can be inline where the variable is used.

I'll close this.
