### ISSUE TITLE
I noticed that HashSet and SortedSet are not mentioned on the page

### ISSUE THREAD

**Issue by waleedeissa** [dotnet/docs#20541]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee0b88ff-d651-fd2f-a6e4-acfa1089b1f2
* Version Independent ID: bc5056d9-27ed-f1ce-bc7a-6e61121a578d
* Content: [Collections (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/collections)
* Content Source: [docs/csharp/programming-guide/concepts/collections.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/collections.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 148958](https://dev.azure.com/msft-skilling/Content/_workitems/edit/148958)

**Comment by Youssef1313** [comment]
SortedDictionary and LinkedList are missing as well.

**Comment by BillWagner** [comment]
I'll keep this open. However, the fix is not for the C# guide to exhaustively list all the types in sections of the .NET libraries.

Rather, these pages should be updated to provide an overview, but send readers to the library documentation for more details.

**Comment by BillWagner** [comment]
Handling this as part of adding the language reference for collection expressions.
