### ISSUE TITLE
Interesting case to explain for CS0119

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20558]
I believe the example stated in https://github.com/dotnet/roslyn/issues/47589 should be added to the doc page. The doc page will need to be updated again if https://github.com/dotnet/roslyn/issues/47589 is fixed to indicate which version has this fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eec72ac2-345b-8257-9765-426726d3ac40
* Version Independent ID: 8f8bdfec-3503-2b36-8d67-aa4dbf253c3c
* Content: [Compiler Error CS0119](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0119)
* Content Source: [docs/csharp/misc/cs0119.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0119.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Youssef1313 The example in dotnet/roslyn#47589 is a better example for this error. We should update the page with that code.

Thanks for pointing it out.
