### ISSUE TITLE
Please add documentation that all four of the Accessibility switches are required

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/docs#20569]
In documentation https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#accessibility-switches, please make sure the following 2 points was mentioned.
1. The description for Switch.UseLegacyAccessibilityFeatures.4.
2. All four of the following switches are required, the only way we could make the switches work is if we made them build upon each other, so setting level 4 requires enabling all of the previous levels.

   "Switch.UseLegacyAccessibilityFeatures"
   "Switch.UseLegacyAccessibilityFeatures.2"
   "Switch.UseLegacyAccessibilityFeatures.3"
   "Switch.UseLegacyAccessibilityFeatures.4"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642b7f23-cc05-b8cb-5ec1-862fa6e62b8c
* Version Independent ID: 0d7236b7-8c64-7eb0-69c8-101c738f275a
* Content: [What's new in accessibility in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#accessibility-switches)
* Content Source: [docs/framework/whats-new/whats-new-in-accessibility.md](https://github.com/dotnet/docs/blob/master/docs/framework/whats-new/whats-new-in-accessibility.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by JeremyKuhne** [comment]
Note that https://support.microsoft.com/en-us/help/4569746/kb4569746-cumulative-update-for-net-framework contains some details on the `Switch.UseLegacyAccessibilityFeatures.4` switch.

**Comment by merriemcgaw** [comment]
I would honestly add the details contained in the doc @JeremyKuhne references to the primary doc about accessibility: [What's New in Accessibility](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility)
