### ISSUE TITLE
Consider documenting compiler warning waves as breaking change.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20560]
Currently, some CA analyzers are being documented as breaking changes.

You may consider documenting new warnings with level 5 as breaking change too for users who use `<WarningLevel>9999</WarningLevel>`

See https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Warnversion%20Warning%20Waves.md for a list of these warnings.

**Comment by BillWagner** [comment]
Adding @gewarren @jcouv @333fred 

I think we need to look at this more strategically in terms of warnings waves. I agree we need to make updates. I'll start a discussion with the folks tagged above to develop a long term plan. This issue will be part of that project and work.

**Comment by BillWagner** [comment]
We discussed, and the warning waves probably aren't good candidates for "breaking changes". 

A better organization for warning articles is around areas of the language and how they can be addressed. For example:
- All warnings related to null safety.
- Warnings based on inconsistent access modifiers.
- Warnings based on definite assignment.
- and so on.

We'll start a draft discussion on how to organize these after .NET 5 ships.

I'll close this as decided. We'll open a project and meta issue in November.
