### ISSUE TITLE
Add instructions for installing to VS for Mac

### ISSUE THREAD

**Issue by pajama** [dotnet/docs#20572]
VS for Mac installer does not have a modify option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bd716a-906d-983b-141c-4a4e2e2a79ec
* Version Independent ID: debed50c-98ce-ec0e-bcf6-0170a4e60fcc
* Content: [The .NET Compiler Platform SDK (Roslyn APIs)](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/)
* Content Source: [docs/csharp/roslyn-sdk/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jongalloway** [comment]
@jmarolf Can you help on this?

**Comment by jmarolf** [comment]
These tools are not available on VS for Mac as they have a different extensibility model.
