### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#20570]
Property initializers provide make it clear which value is setting which property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @daveyostcom I just opened #20575 to fix this.

When you find these, it might save both of us time to submit the PR yourself. You can click the edit button (it looks like a pencil) to edit the content in your browser.

**Comment by BillWagner** [comment]
Fixed in #20564
