### ISSUE TITLE
Language reference: Patterns

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#20584]
As of C# 9, the pattern expressions are robust enough to justify their own page in "expressions and operators". This should cover:

- type pattern
- constant pattern
- null pattern as a useful special case of the constant pattern
- range patterns (`<`, `>`, `<=`, `>=`)
- property pattern (`when` patterns)
- `and`, `or`, and `not` pattern

In addition, the `switch` and `is` pages should link to this new page. They can cover less of the pattern syntax which likely moves to this new page.

**Comment by pkulikov** [comment]
@BillWagner what about the `swtich` statement? Does it support all those patterns as well? If yes, the separate TOC node (just under the "Language reference" node) for "Pattern matching" is possible with individual articles per pattern. Any such article would present three examples of usage, then (with `switch` and `is` expressions and with `switch` statement). Placing patterns under "Expressions and operators" doesn't play well with the `switch` statement supporting them as well.

Anyway, I like a lot that a lot of duplication from `is`/`switch` articles would be consolidated.

**Comment by BillWagner** [comment]
This update should also cover the discard pattern (`_` as the switch arm in a `switch` expression).  See https://github.com/dotnet/docs/pull/21318/files#r516723654

**Comment by pkulikov** [comment]
@BillWagner I'm on fence about if it should be one article or multiple. Multiple articles suggest the separate TOC item and more visible structure/navigation among various patterns; however, with that approach some article can be very small (for example, one about discard pattern). What do you think?

**Comment by BillWagner** [comment]
@pkulikov I've been in that situation a few times myself.  

I'd recommend starting with one article.  If that gets too long, having all the content and examples in one place will often give us guidance on how best to break it up.

**Comment by pkulikov** [comment]
@BillWagner thank you; let's go on with one article. 

Original idea was to put it under "Expression and operators". Is it still the good location or there is a better one?

Also, I like to submit small PRs. So, it will be a PR per pattern. How do you want it to be arranged? Submit PRs directly to the master (so, the article would grow live), or submit PRs to the dedicated branch, that will be merged into the master at the end (or interim).

**Comment by BillWagner** [comment]
@pkulikov 

> Also, I like to submit small PRs. So, it will be a PR per pattern. How do you want it to be arranged? 

I think it would be better to publish them all at once. I'm concerned that each smaller PR might be less useful for readers.

I can think of two ways to do this.  One is as you suggest, where I make a feature branch on dotnet/docs, and you target that branch with each smaller PR. Once it's ready, I'll merge that into the main branch (not squashing that final merge).

The other is that you could create a feature branch in your fork. If you tag me for reviews on PRs targeting that branch, the workflow would be the same. Then, when we're both ready, you can create one PR from that feature branch into the dotnet/docs main branch.

Which do you think would work best?

**Comment by pkulikov** [comment]
@BillWagner 

> where I make a feature branch on dotnet/docs, and you target that branch with each smaller PR. Once it's ready, I'll merge that into the main branch (not squashing that final merge).

I think that would work better

**Comment by BillWagner** [comment]
@pkulikov I just created the [csharp-patterns-reference](https://github.com/dotnet/docs/tree/csharp-patterns-reference) branch. It's even with master right now.

**Comment by BillWagner** [comment]
@pkulikov Are you working on this? I haven't seen any PRs to review, and I wanted to make sure.

**Comment by pkulikov** [comment]
@BillWagner I've started to work on this. (Sorry for the delay. My January turned out to be busier than expected, but now I have more of my time back.)
