### ISSUE TITLE
Language Reference: Record types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#20585]
There are a few tasks here:

- [x] Update the "class & structs" article to include a short introductory section on `record` types.
- [x] Add `with` to keywords
- [x] Add an article that describes `with`-ers.
- [x] Add a new language reference article for `records`. This should include information on the compiler generated members, and how to override them. In addition, it should explain inheritance rules for records, primary constructors, with-ers, and deconstruction methods.
- [x] Update the "Programming Guide->Types->Use and define types" article to mention records.
- [x] Update the "Programming Guide -> Classes and structs" with an article on records. The new article should explain records and when to use them over class types.

**Comment by pkulikov** [comment]
@BillWagner I would like to add the article for the `with` expression (into the *operators* folder). If you're not working on it now, is that fine if I do that?

**Comment by BillWagner** [comment]
> I would like to add the article for the `with` expression (into the operators folder). If you're not working on it now, is that fine if I do that?

Thanks @pkulikov I appreciate it. I'm not working on this now, so I'd welcome a PR.

**Comment by BillWagner** [comment]
@pkulikov Are you working on this one? I want to make sure I haven't missed any PRs

**Comment by pkulikov** [comment]
@BillWagner, I'm not working on this one; the article about a `with` expression was my only intention for this issue.
