### ISSUE TITLE
Intro to F# on Binder link is bad

### ISSUE THREAD

**Issue by aszalacinski** [dotnet/docs#20614]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea0ea44-1b46-78cc-77b7-b5345a8b05ca
* Version Independent ID: ad1f303b-793c-6357-4ec0-1822468ca370
* Content: [Get started with F#](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/)
* Content Source: [docs/fsharp/get-started/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, will fix
