### ISSUE TITLE
Cryptographic key import section could provide the details of how to read RSA PCKS1 key

### ISSUE THREAD

**Issue by mulawam** [dotnet/docs#20612]
It would be good to just provide simple example how to transform PCKS1 certificate content to actually import it.

Generate key using openssl utility
`openssl genrsa -f4 -out private.txt 4096`

`var keyPath = ".\private.txt";
string keyBytesAsText = System.IO.File.ReadAllText(keyPath);
string keyBytesWithoutPEM = keyBytesAsText
                .Replace("-----BEGIN RSA PRIVATE KEY-----", "")
                .Replace("-----END RSA PRIVATE KEY-----", "");
var keyBytes = Convert.FromBase64String(keyBytesWithoutPEM);
using var rsa = RSA.Create();
rsa.ImportRSAPrivateKey(keyBytes, out int readBytes);
Console.WriteLine($"Read {keyBytesAsText.Length} chars, key bytes {keyBytes.Length}");
var parameters = rsa.ExportParameters(true);
Console.WriteLine($"{BitConverter.ToString(parameters.D)}");`

This sample describes nicely how to import crypto keys 
https://docs.hidglobal.com/auth-service/Content/pages/BuildingApps/Csharp/Read_different_certificate_key_file_formats_with_C_.htm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
@mulawam Thanks for the suggestion.

@bartonjs Should we link to the suggested URL in the [3.0 What's new](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#cryptographic-key-importexport), and  if so, are there other docs that should also have the link?

**Comment by bartonjs** [comment]
I wouldn't link to that, no.   Partially because I don't know how often we link out to third-party content, but definitely because their code samples use `RSACryptoServiceProvider` instead of `RSA.Create()`.

With .NET 5 the code is simpler:

```C#
string keyBytesAsText = System.IO.File.ReadAllText(keyPath);
RSA rsa = RSA.Create();
rsa.ImportFromPem(keyBytesAsText);
return rsa;
```
