### ISSUE TITLE
Missing ms.prod metadata

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#2061]
The required metadata for `ms.prod` is missing from [more than one doc](https://github.com/dotnet/docs/pull/1928#discussion_r114104766). Isolate docs with missing metadata and enforce compliance with company policy.

![cordo](https://cloud.githubusercontent.com/assets/1622880/25575945/f90d1fd4-2e20-11e7-9b9e-cc0ecf14f852.png)
*Praise the company!* - Citizen Cordo (Roy Macready), [Dr. Who: The Sun Makers](http://www.bbc.co.uk/doctorwho/classic/episodeguide/sunmakers/), ©1977 [BBC](http://www.bbc.com/)

**Comment by mairaw** [comment]
LOL! I have a list of topics.

**Comment by tompratt-AQ** [comment]
@mairaw Where do I find the list of topics?
(Unless you've used the TARDIS to go back in time and fix this already)

**Comment by mairaw** [comment]
I'll send you an email @tompratt-AQ
