### ISSUE TITLE
Calling Dispose(false) in DisposeAsync() seems pointless

### ISSUE THREAD

**Issue by lukacs-andras** [dotnet/docs#20629]
With the current sample implementation, it seems pointless to call Dispose(false) in DisposeAsync() because after DisposeAsyncCore() sets _disposed to true, Dispose(false) will return immediately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @lukacs-andras - ah, yes... good catch. You're not wrong, I'll fix this. Thank you
