### ISSUE TITLE
Unclear how to use a type derived from JsonConverterFactory

### ISSUE THREAD

**Issue by rummelsworth** [dotnet/docs#20638]
Suppose I've defined a `DictionaryTKeyEnumTValueConverter` just like the one in this doc page. How do I use it? Can I put its type object in a `JsonConverterAttribute` constructor? Or am I forced to always use the converters collection on the serializer objects I create? If the latter, and I'm supposed to call `CanConvert` and `CreateConverter` myself, what is an example of some code that does this?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
There's an example of code that uses this converter [here](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDictionaryTkeyEnumTValue.cs). The .csproj file for the project that runs it and the rest of the code examples for the System.Text.Json docs is [here](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/snippets/system-text-json-how-to/csharp/SystemTextJsonSamples.csproj). You can open and run the project if you clone or download the dotnet/docs repository.
