### ISSUE TITLE
advanced-linq-to-xml-programming.md is missing a redirect or unintentionally deleted

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20632]
It was deleted in https://github.com/dotnet/docs/pull/16969/
I can't find a redirect for it. I can't also find it in the new *standard/linq* folder.

The file wasn't adding much value, just links to other articles. So I think it's just missing a proper redirection.

cc: @mairaw

**Comment by mairaw** [comment]
We were removing nodes that were just a list of links to sub-articles. Let me check!

**Comment by BillWagner** [comment]
adding @gewarren who was working on some of this as well.

**Comment by BillWagner** [comment]
@mairaw Did you find anything? I can't find any article that points to it, or where it was. 

I'm wondering if we can close this with no action.

**Comment by mairaw** [comment]
We could point to https://docs.microsoft.com/en-us/dotnet/standard/linq/linq-xml-annotations, which is the first entry node of the advanced sub-menu.

**Comment by BillWagner** [comment]
Thanks @mairaw 

I've added the up for grabs label for the suggested fix of adding a redirect.

**Comment by Youssef1313** [comment]
@TheBlueSky Redirects are added in https://github.com/dotnet/docs/blob/main/.openpublishing.redirection.json. But I'm not sure if it's still necessary or if the issue can simply be closed. You could submit a PR for review.

**Comment by TheBlueSky** [comment]
Thank you, @Youssef1313.
Looks like the file is already in the redirection document ([here](https://github.com/dotnet/docs/blob/main/.openpublishing.redirection.json#L12851)).
It is under Visual Basic, however. Not sure if there was a C# (or other) version, but cannot see a file called `advanced-linq-to-xml-programming.md` in the repo or in #16969.

**Comment by Youssef1313** [comment]
Thanks for looking @TheBlueSky. Indeed the file is already having a redirect, no idea when I didn't find it at the time of writing the issue 😄 

I'm going to close the issue. Thanks again for looking.
