### ISSUE TITLE
Mutable value types don’t often introduce errors

### ISSUE THREAD

**Issue by Daynvheur** [dotnet/docs#20646]
Hello,

This quoted sentence is unclear for me:
>mutable value types don’t often introduce errors.

Does this say it will certainly introduce errors? Or will this be misused by developers? Or something else?
And when would those errors show up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
Looks like the sentence should be without "don't":

> mutable value types often introduce errors

The next sentence after that explains why:

>  Value type variables hold the values so changes are made to a copy of the original data when value types are passed to methods

**Comment by BillWagner** [comment]
related to #20601 

Thanks for pointing this out @Daynvheur The comment by @pkulikov is correct, although taking this in context with the related issue, this section likely gets larger updates that change or remove that sentence.

**Comment by Daynvheur** [comment]
Thanks @pkulikov & @BillWagner, everything makes better sense. :)
Seems the intro will have a hard time, I can't wait to read the new version.
