### ISSUE TITLE
Clarify semantics of rollForward:latestMajor

### ISSUE THREAD

**Issue by Naine** [dotnet/docs#20640]
The below is for SDK selection in `global.json`, but I believe this also applies to runtime selection in `.runtimeconfig.json`.

The description of `latestMajor` seems to imply something highly undesirable. Here is the current text, for convenience and posterity:

```
| `major`       | Uses the latest patch level for the specified major, minor, and feature band. <br> If not found, rolls forward to the next higher feature band within the same major/minor version and uses the latest patch level for that feature band. <br> If not found, rolls forward to the next higher minor and feature band within the same major and uses the latest patch level for that feature band. <br> If not found, rolls forward to the next higher major, minor, and feature band and uses the latest patch level for that feature band. <br> If not found, fails. |
| `latestMajor` | Uses the highest installed .NET Core SDK with a major that is greater or equal than the specified value. <br> If not found, fail. |
```

It is clear that "major" allows any version >= the specified version, with preference for the major/minor/feature closest to the specified version.

It's clear that "latestMajor" differs by giving preference to the highest available version instead. What's not clear, however, is whether the range of accepted versions is the same, or even that only versions >= the specified version are allowed. The description seems to indicate that all version components other than the major are ignored, which would actually permit a roll  _backward_ so long as the major version is a match. For example, this would mean that if "3.1.100" is specified, and only 3.0 is available, 3.0 will be used because the major component is equal, even though the version is actually lower.

The same also applies to "latestMinor" with respect to the feature level.

I've not been able to confirm whether the above interpretation matches the actual behaviour. If this is not the actual behaviour, the documentation should be updated to make clear that the full version must still be >= the specified version. ~~If this _is_ the actual behaviour, I think the potential minor downgrade is worth explicitly mentioning.~~

I can't seem to find where the corresponding documentation for `.runtimeconfig.json` lives, other than in [this "what's new" page](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md#major-version-runtime-roll-forward), but the same issue applies here and IMO is more critical than for `global.json`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Naine** [comment]
Just worth mentioning, the second example file shown on this page indicates that the above interpretation is incorrect, and that the minor/feature versions are not ignored and minor roll-back is indeed not allowed, but I do not think the presence of this example mitigates the need for clearer option descriptions.

**Comment by tdykstra** [comment]
Thanks for the suggestion. We'll make the option descriptions clearer the next time we update the article, or you're welcome to submit a PR if you'd like to make the change yourself.

**Comment by Naine** [comment]
Happy to submit a PR, though I may not get to it for a few days.
