### ISSUE TITLE
Performance of interpolated strings

### ISSUE THREAD

**Issue by pchandoria** [dotnet/docs#20669]
I started using interpolated string feature available in latest C# version. However I was curios what is performance improvement with new sugar coated format. In test it turns out it is 4 time slower then traditional method.

My Test:
```
[Benchmark(Baseline = true)]
        public string Test_StringFormat()
        {
            string msg = null;
            for (int i = 0; i < iterations; i++)
            {
                msg = "This is day" +  i + " for all of " + us;
            }

            return msg;
        }

        [Benchmark(Baseline = false)]
        public string Test_DollarString()
        {
            string msg = null;
            for (int i = 0; i < iterations; i++)
            {
                msg =$"This is day {i} for all of {us}";
            }
            return msg;
        }
    }
```
![image](https://user-images.githubusercontent.com/39146718/93380043-89e86f80-f813-11ea-8447-2a061b9f3899.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#compilation-of-interpolated-strings)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pchandoria** [comment]
.Net Version Core 2.2
so I think C# should be C# 7.3

**Comment by BillWagner** [comment]
Thanks for writing this @pchandoria 

In most cases, we don't write general performance guidance for language features. 

First, your test shows an absolute difference of 13us for 100 iterations. That is negligible. It would only be significant in hot paths with a large number of iterations. 

Next, the performance of code constructs like this are dependent on a large number of variables:
- Can the compiler perform any constant folding? 
- What allocations take place? How quickly do those objects become garbage?
- How close is the test to production conditions?
- What optimizations can the JIT make?

Finally, every release contains new performance improvements to different language constructs. 

For any low-level optimization like this, the consistent advice we give is to measure your application under important scenarios, and take action based on those results.

I don't think we should update this article. What specific advice would you want to see added here?
