### ISSUE TITLE
No null-terminating character at the end of a C# string

### ISSUE THREAD

**Issue by iSazonov** [dotnet/docs#20682]
> There is no null-terminating character at the end of a C# string

It confuses because null-terminating character is there. See https://github.com/dotnet/runtime/issues/42373

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'll close this based on https://github.com/dotnet/runtime/issues/42373#issuecomment-694200101
