### ISSUE TITLE
Database should be outside the docker container

### ISSUE THREAD

**Issue by nagkumar** [dotnet/docs#20706]
[Enter feedback here]

Would Database be inside of this? I suppose DB is outside of the docker container, if inside, multiple notes of this service can't update the same database, hence can lead to consistency issue as each instance of the same microservice has their own database copy and state updates.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce115a1c-3cc0-c01d-4fb4-95105cfeda85
* Version Independent ID: 3469e63a-4c32-d38e-152a-28be75f2b056
* Content: [Applying simplified CQRS and DDD patterns in a microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hello @nagkumar, thank you for reaching out. 

Yes, though the DB instance runs within the container but actual data gets saved outside the container and within the docker volume for multiple instances/replicas/containers of the same microservice to share data.
And in terms of consistency across multiple microservices - Yes, there is always a challenge to keep data consistent across multiple microservices as each microservice has it's own data store. In such scenarios, a good solution would be implementing "Asynchronous event-driven communication". For more details, you can refer [Consistency across multiple microservices](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management#challenge-3-how-to-achieve-consistency-across-multiple-microservices)

Hope this helps !

**Comment by nagkumar** [comment]
Thank you.

**Comment by sughosneo** [comment]
Closing this issue as of now. Please feel free to reopen it if you have any question.
