### ISSUE TITLE
Trying to find classifications in ML.NET tutorial and scores

### ISSUE THREAD

**Issue by chunky** [dotnet/docs#20712]
The document here explains how the scores are a vector of probability-like values:

"The scores of all classes. Higher value means higher probability to fall into the associated class. If the i-th element has the largest value, the predicted label index would be i. Note that i is zero-based index."

Two questions:

1) I can't actually figure out how to map what classification is in which column. I could infer it [I think] by running the model and assume that the classification is the highest probability, then run it a bunch of times and put the results together. It's not obvious that that's gauranteed to work, but I'd really rather just find the way to map the information directly in the schema

2) Is score actually a probability? Or is it some other metric?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @chunky,

Thanks for your questions.

1. Here is an [example](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Labeler.cs#L75) of how you can map a score to a label. 
2. Yes. The score is the probability.
