### ISSUE TITLE
$var should be $books?

### ISSUE THREAD

**Issue by peterclifford** [dotnet/docs#20710]
I think there might be an error in the text? $var should be $books?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28eedd05-fdc3-533c-4fa1-b13c9fbbee75
* Version Independent ID: 13dd5ee8-ac3f-9b33-7e72-6f7f91a7a335
* Content: [Support for the msxsl:node-set() Function](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/support-for-the-msxsl-node-set-function)
* Content Source: [docs/standard/data/xml/support-for-the-msxsl-node-set-function.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/support-for-the-msxsl-node-set-function.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Good catch! I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
