### ISSUE TITLE
Update Core get started for .NET 5

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#20725]
core/get-started.md --> Hello World
standard/get-started --> Link to get started tutorials for each app type and get-started docs for each language.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2
* Version Independent ID: fdb655a4-cff4-6c67-7244-673760379663
* Content: [Get started with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/get-started?tabs=windows)
* Content Source: [docs/core/get-started.md](https://github.com/dotnet/docs/blob/master/docs/core/get-started.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tukanggranit** [comment]
i have a problem about this

**Comment by tdykstra** [comment]
What is the problem you're having?
