### ISSUE TITLE
Additional Tutorials?

### ISSUE THREAD

**Issue by mgsassu** [dotnet/docs#20730]
This is a really great page, I've already learned a lot just by walking through the project. I am a bit confused with respect to training the model on new data. There is reference to being able to do this, but it's not clear to me how to set this up and my attempts to input new images into the pipeline have failed. Is there some documentation which walks through this portion in more detail? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @mgsassu 

Happy to hear you enjoyed this tutorial! You can train object detection models using your own data with [Model Builder](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder), a Visual Studio extension for ML.NET. We're in the process of updating our documentation to showcase this scenario as well as image classification. In the meantime, you can take a look at this guide to get an idea of how you can go about using Model Builder to train an object detection model.

https://www.arafattehsin.com/beyond-sentiment-analysis-object-detection-with-ml-net/
