### ISSUE TITLE
Remove useless snippet references from 

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2074]
Found this while reviewing a PR:
https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.FileDialog.Filter?view=netframework-4.7#examples

Seems silly to have an entry for using statements only. This could said in the example description and then just have the applicable snippets in the examples section.

**Comment by mairaw** [comment]
And we could probably update the screenshot to show a newer OS. 😄

**Comment by tompratt-AQ** [comment]
Since the namespace is listed at the top of the page as usual, I don't see why we need to mention it in the example description either. I'm just going to include the C# and VB snippets for each of the 8 examples and remove the (using Microsoft.Win32;) snippets.

**Comment by mairaw** [comment]
Sounds good @tompratt-AQ.
