### ISSUE TITLE
Broken C#6 tutorial

### ISSUE THREAD

**Issue by SVCLIII** [dotnet/docs#20753]
The Focus mode editor throws the following compiler errors from page one:

(1,1): error CS8652:t The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
(1,7): error CS0118: 'System' is a namespace but is used like a type
(1,13): error CS0210: You must provide an initializer in a fixed or using statement declaration
(1,13): error CS1001: Identifier expected
(1,1): error CS1513: } expected
(26,14): error CS0542: 'Program': member names cannot be the same as their enclosing type

Example code needs to be adjusted or focus mode editor needs to target the correct version.
The tutorial is functionally useless in its current state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3686c2-4c73-5686-0da9-abc38c74aeec
* Version Independent ID: ca995f80-9375-e9ca-b855-6e6893581e23
* Content: [Explore C# 6 - Try the new features in C# 6 interactively, using your browser](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=1)
* Content Source: [docs/csharp/tutorials/exploration/csharp-6.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/csharp-6.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @SVCLIII We'll look into this.

Ping @mimisasouvanh @rloutlaw

**Comment by rloutlaw** [comment]
@BillWagner The source for this tutorial appears to be using the legacy !code block consumption mechanism. Can you update it to use :::code with the correct scaffolding syntax?

CC: @mimisasouvanh

**Comment by BillWagner** [comment]
@rloutlaw The `:::code` syntax only works in md files, not YML files. Please advise.

CC @mimisasouvanh

**Comment by lamebrain** [comment]
We're investigating the issue /cc @adunndevster

**Comment by adunndevster** [comment]
@BillWagner @rloutlaw @SVCLIII - You may want to try the new triple colon ":::code..." syntax. [Here is an example](https://github.com/dotnet/docs/pull/20966/files#diff-cca4199c452150841f4f5c0d702cd330R22) of how it works.

And [here is the preview](https://review.docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=1&branch=pr-en-us-20966#code-try-0) showing it working.

Explanation: if you use the new ":::" syntax, and add the interactive="try-dotnet" attribute, it give the code snippet a "Try" button. When clicked, this wraps the snippet in all the proper framework needed to allow it to run.

cc @lamebrain
