### ISSUE TITLE
The image on this page is impossible for me to read

### ISSUE THREAD

**Issue by arcadianmonkey** [dotnet/docs#20757]
The image is fixed. I can't copy it into another application to zoom-in. Zooming-in with the browser increases the font size of everything but the image. I used the Magnifier app on my machine for the very first time, and the resolution of the image made the majority of the words unreadable.

It looks like the creator of this image took a lot of care to be thorough. It's too bad I could only maybe read it if my eyes were 20 years younger. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d740d43f-a1c2-e806-63cb-f8b6c7c4f4e7
* Version Independent ID: b3f34e06-f3dd-74df-79c7-4bfbf8f9670e
* Content: [WCF Configuration Schema](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Youssef1313** [comment]
If you open the image url directly from [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/media/index/windows-communication-foundation-configuration-schema.gif) does it look good?

**Comment by arcadianmonkey** [comment]
Much better. Much appreciation. Thanks!


Paul Harris
PerByte, Inc.

________________________________
