### ISSUE TITLE
https://aka.ms/dotnet-whats-new needs to be updated

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20763]
This is not really a doc issue, but I didn't know where to report this and thought you *may* have access to update this, or report it to the appropriate team.

Currently, the link <https://aka.ms/dotnet-whats-new> redirects to What's new in .NET Core 3.1 article. I think it should now redirect to "The evolution of .NET Core to .NET 5" article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8175dfa-c812-afef-c018-a5927995ef43
* Version Independent ID: 4fd72a98-c51f-cbd9-0578-d6448bab4749
* Content: [The evolution of .NET Core to .NET 5](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five)
* Content Source: [docs/core/dotnet-five.md](https://github.com/dotnet/docs/blob/master/docs/core/dotnet-five.md)
* Product: **dotnet-core**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @Youssef1313 - thanks for posting this. 

This is owned by @leecow - I'll ask if we can get that AKA link redirected as you suggest.

**Comment by rbhanda** [comment]
https://aka.ms/dotnet-whats-new now redirects to the [The evolution of .NET Core to .NET 5](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five)
