### ISSUE TITLE
possible deadlock

### ISSUE THREAD

**Issue by Houuse** [dotnet/docs#20765]
Hi, I'm not an expert so please forgive me if I'm wrong,
but the code example will produce a deadlock (maybe not always) and will cause the program to wait forever [Link 1](https://stackoverflow.com/questions/34995195/asyc-method-using-await-task-run-never-completes) [Link 2](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html),

source?: I've tried the same code with an old application couldn't be converted to use `async `atm and it's produced a deadlock

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bea9235-8cf9-29aa-5136-a0af34725e2c
* Version Independent ID: b6c11689-a72b-1d55-f832-3f99d0edb628
* Content: [How to: Implement a Producer-Consumer Dataflow Pattern](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern)
* Content Source: [docs/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-implement-a-producer-consumer-dataflow-pattern.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Houuse
Thank you so much for posting this issue. We really appreciate it. I'll take a look at fixing this soon.

**Comment by Houuse** [comment]
@IEvangelist thank you too 👍
