### ISSUE TITLE
MainClass4?

### ISSUE THREAD

**Issue by hsoJosh** [dotnet/docs#20773]
[Enter feedback here]
MainClass4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ac12d2-0496-d7df-491e-f75a0ff6beb5
* Version Independent ID: 6a8127dd-1d58-63e3-3963-685d9228f1ad
* Content: [public keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/public)
* Content Source: [docs/csharp/language-reference/keywords/public.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/public.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @hsoJosh 

The name `MainClass4` is valid, although somewhat atypical. I've added this to our backlog for when we next update this article.

I've also added the "up for grabs" label if someone wants to update this in the interim.

**Comment by Youssef1313** [comment]
@BillWagner I believe the issue here isn't whether the name is valid or not. The issue is the code using `MainClass4`, but the article text is using `MainClass` (text doesn't match code).

**Comment by hsoJosh** [comment]
@BillWagner .. That was it .. What @Youssef1313 said. I think it's just a minor typo but it doesn't really matter what it's called .. it's just referenced differently in the article text
