### ISSUE TITLE
API Breaking Changes When Publishing as Single-File in .NET 5 vs .NET Core 3.1

### ISSUE THREAD

**Issue by agocke** [dotnet/docs#20785]
## API Changes

Multiple APIs are known to have different behavior when run in a single-file publishing format:

### Version introduced

Change in behavior in .NET 5 from .NET Core 3.x

### Old behavior

- `Assembly.Location` returned extracted DLL file path
- `Assembly.CodeBase` returned extracted DLL file path
- `Assembly.GetFile` returns `null` for bundled assemblies
- `Environment.GetCommandLineArgs()[0]` is the name of the entry point DLL
- `AppContext.BaseDirectory` is the temporary extraction directory

### New behavior

- `Assembly.Location` for bundled assemblies returns empty string
- `Assembly.CodeBase` for bundled assemblies throws an exception
- `Assembly.GetFile(s)` throws for bundled assemblies
- `Environment.GetCommandLineArgs()[0]` is the name of the exe host
- `AppContext.BaseDirectory` is the containing directory of the executable

### Reason for change

In .NET 5 single-file publishing, bundled assemblies are loaded from memory, instead of being extracted to disk.

### Recommended action

Avoid dependency on the file location of assemblies when publishing as a single file.

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [X] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

---
#### Issue metadata

* Issue type: breaking-change

**Comment by agocke** [comment]
cc @LakshanF @vitek-karas

**Comment by PriyaPurkayastha** [comment]
cc @gewarren
