### ISSUE TITLE
Suggestion for clarification w.r.t using a discard to suppress an exception

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#20787]
Hi, I'm Rex Jaeschke, editor of the C# Standard, under contract to MS. I was confused by what this meant, so I asked Mads Torgersen of the C# Team @ MS to help clarify. Here's what he sent to me:

"No, discards have no exception-suppressing capabilities! Here’s what happens in the example:

- We Task.Run a lambda that ends by throwing an exception
- The result of the Task is therefore the exception
- If you await the exception, then that throws the exception in your code
- To deliberately avoid that exception, you might want to simply drop the Task on the floor and not await it
- But if you do, the compiler helpfully warns you saying hey, didn’t you forget to deal with this task?
- To show the compiler that you’re dealing with the Task, all you have to do is use it somehow, e.g. by assigning it to a variable.
- But now you have this dummy variable containing a Task that you specifically don’t want to touch again.
- Better to use a discard! Now you can’t accidentally touch the Task later, and you don’t have the variable name cluttering up your declaration space."

You might want to borrow some of his words to help improve this page.

Rex
rex@RexJaeschke.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards#a-standalone-discard)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @RexJaeschke 
I'll add this to our list to update.

**Comment by BillWagner** [comment]
When this is fixed, explain that the behavior exhibited is different when a debugger is attached. (With the debugger, the debugger forces the app to break when the exception is thrown and not caught. It will be discarded without a debugger attached).

/cc @kendaleiv
