### ISSUE TITLE
Nested class

### ISSUE THREAD

**Issue by NN---** [dotnet/docs#20784]
Please mention CA1034 diagnostic

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f0b79c-c255-2f25-9d68-ab7d2d3d4eb5
* Version Independent ID: a4f839af-8a03-6559-3fe7-79a1cf662688
* Content: [Nested Types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/nested-types)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/nested-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/nested-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BartoszKlonowski** [comment]
I would like to handle that change - @BillWagner Please assign me to this item so I can work on this.

**Comment by Youssef1313** [comment]
@BartoszKlonowski Are you still interested in taking this?

**Comment by BartoszKlonowski** [comment]
@Youssef1313  Yes, I am.  I have a rule that I don't work on items which I'm not assigned to, so I've missed that one, but it would be great if I could be assigned. @gewarren @BillWagner
