### ISSUE TITLE
Warning missing "why"

### ISSUE THREAD

**Issue by destinchfield** [dotnet/docs#20794]
The tutorials for ML are great!  However, the Warning and Notes often make blanket statements without describing the "why".  For example, in this page, there is a warning about using the cache.  The warning states that the cache should only be used for small/medium sized data sets only, never for large ones.  Why?  What does not provide a gauge to understand what is meant by small, medium, and large datasets? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification?source=docs)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @destinchfield 

Thanks for raising this issue. In this case, small/medium can depend. Typically what is meant is, can you fit it into memory. Would a statement like that help clarify the meaning?

**Comment by destinchfield** [comment]
> Hi @destinchfield
> 
> Thanks for raising this issue. In this case, small/medium can depend. Typically what is meant is, can you fit it into memory. Would a statement like that help clarify the meaning?

Yes, that would be good.  Thank you.

**Comment by destinchfield** [comment]
Yes, that would be good. Thank you.
