### ISSUE TITLE
Using Nullable struct for taking input in controller sets value to null even with valid value.

### ISSUE THREAD

**Issue by prashantchoudhary** [dotnet/docs#20795]
```
        public async Task<IActionResult> CreateMagic([FromBody] MagicInput post)
        {
                 // post.somefield will always be null
        }

        public class MagicInput
       {
           public string Title {get;set;}
           public SomeType? OptionalField;
       }
```

Here setting Optional field causes all the fields to be null. However documentation suggests this to be used as a workaround for Optional Json Serialisation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#conditionally-ignore-a-property)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **Dot net Core 3.1**
* GitHub Login: @prashantchoudhary
* Microsoft Alias: **get.prashant.007**

**Comment by tdykstra** [comment]
Please provide more information about the problem this issue is reporting.  From the title, it sounds like a product issue rather than a documentation issue, in which case we can transfer it to the [dotnet/runtime repo](https://github.com/dotnet/runtime/issues).
