### ISSUE TITLE
How is version being used as a named parameter in this code example?

### ISSUE THREAD

**Issue by marcospgp** [dotnet/docs#20809]
In the "[Creating Custom Attributes](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/creating-custom-attributes)" documentation page we have the following code example:

![image](https://user-images.githubusercontent.com/3464445/94454088-5ad5e480-01a9-11eb-92c6-c77b5902660c.png)

Followed by an example usage of the custom attribute declared above:

![image](https://user-images.githubusercontent.com/3464445/94454164-6e814b00-01a9-11eb-949b-1beb36bbddd5.png)

Except a named parameter `version` is included which is not present in the declaration of the constructor for the attribute class. The page says "Any public read-write fields or properties are named parameters. In this case, version is the only named parameter." but the value of the parameter is passed with an equals sign `=` instead of a colon `:`, which is what is commonly used when passing named parameters to a method call.

Is this a mistake or a feature of C# I'm not aware of?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5deee0dd-859f-1dc5-4cc1-b9366cf5220f
* Version Independent ID: 72041048-d399-cc42-a7f9-7ed4c9a0fbd0
* Content: [Creating Custom Attributes (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/creating-custom-attributes)
* Content Source: [docs/csharp/programming-guide/concepts/attributes/creating-custom-attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/attributes/creating-custom-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
That syntax for assigning a value to the named parameter is correct according to the [C# specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#positional-and-named-parameters). Maybe the syntax is different because it's an attribute instead of just calling a regular method. @BillWagner ?

**Comment by BillWagner** [comment]
Thanks for asking the question @marcospgp As @gewarren points out, the syntax for setting a named argument on an attribute is different than a named argument in a method. The syntax is more closely related to a property initializer.

I'll close this as an answered question.
