### ISSUE TITLE
[WinForms] `TextFormatFlags.ModifyString` is obsolete

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#20804]
### Version introduced

.NET 5.0 RC1

### Old behavior

[`TextFormatFlags.ModifyString`](https://docs.microsoft.com/dotnet/api/system.windows.forms.textformatflags) was available for use.

### New behavior

[`TextFormatFlags.ModifyString`](https://docs.microsoft.com/dotnet/api/system.windows.forms.textformatflags) is marked as obsolete, with a view to removal in future releases.

### Reason for change

Passing a string to [`TextRenderer.MeasureText()` method](https://docs.microsoft.com/dotnet/api/system.windows.forms.textrenderer.measuretext) with   [`TextFormatFlags.ModifyString`](https://docs.microsoft.com/dotnet/api/system.windows.forms.textformatflags) in some situation will alter the string, which breaks string immutability promise, and may lead to a fatal .NET runtime state corruption.

### Recommended action

Update code that relies on `TextFormatFlags.ModifyString`.

### Category

- [ ] Windows Forms

### Affected APIs

* [MeasureText(String, Font, Size, TextFormatFlags)](https://docs.microsoft.com/dotnet/api/system.windows.forms.textrenderer.measuretext#System_Windows_Forms_TextRenderer_MeasureText_System_String_System_Drawing_Font_System_Drawing_Size_System_Windows_Forms_TextFormatFlags_)
* [MeasureText(IDeviceContext, String, Font, Size, TextFormatFlags)](https://docs.microsoft.com/dotnet/api/system.windows.forms.textrenderer.measuretext#System_Windows_Forms_TextRenderer_MeasureText_System_Drawing_IDeviceContext_System_String_System_Drawing_Font_System_Drawing_Size_System_Windows_Forms_TextFormatFlags_)
* <https://docs.microsoft.com/dotnet/api/system.windows.forms.textformatflags>

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
Is there any behavior change here? Or it's just marked obsolete?

**Comment by RussKie** [comment]
No behaviour changes for the existing API.
