### ISSUE TITLE
Intrinsic type extensions are not visible from C# even though same namespace and file

### ISSUE THREAD

**Issue by jmagaram** [dotnet/docs#20800]
I can't get F# intrinsic extensions to visible from C# if they are in the same namespace AND file but a DIFFERENT module. I'm not sure the online documentation is correct. It says...

> Intrinsic type extensions must be defined in the same file and in the same namespace or module as the type they're extending. Any other definition will result in them being optional type extensions.

My test involves the code below which is all in the same file called `Contacts.fs`. This is .net core 3.1. This all compiles but the extension `FullName` is NOT visible from C#. A bare bones Visual Studio solution with this code is at [extension problem on github](https://github.com/jmagaram/IntrinsicExtensionsProblem). I'm not an F# expert so I might be missing something here. I wonder if these intrinsic extensions have to be in exactly the same module AND file AND namespace to be visible from C#.

    namespace Contacts

    module AddressBookTypes =

        type Person = { FirstName: string; LastName: string }

    module AddressBookFunctions =

        open AddressBookTypes

        let fullName (p: Person) = p.FirstName + " " + p.LastName

        type Person with
            member public me.FullName = me |> fullName

        // This works as expected
        let getFullName1 (p: Person) = p.FullName

    module SomeOtherModule =

        open AddressBookTypes
        open AddressBookFunctions

        // This works too but only if I also "open AddressBookFunctions"
        // Seems to behave like an extension method
        let getFullName2 (p: Person) = p.FullName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640cc89f-e2da-021c-daf3-68f6772ffabf
* Version Independent ID: 1df801b1-3a11-0aa5-44d7-78c5e2751393
* Content: [Type Extensions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/type-extensions)
* Content Source: [docs/fsharp/language-reference/type-extensions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/type-extensions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
This is by design. F# type extensions are not consumable from C#. You can write extension methods with the `[<Extension>]` attribute as the document described further on.

**Comment by jmagaram** [comment]
I don't think so. If I move the extension into the same module where type is defined then I can access it from C# without using any of the `[Extension]` stuff.

Also, the documentation for "Optional type extensions" says...

> An optional type extension is an extension that appears outside the original module, namespace, or assembly of the type being extended.

This conflicts with the definition of intrinsic because it says it is for "outside the original module" but intrinsics can also be defined outside the original module ("in the same namespace OR module").
