### ISSUE TITLE
Breaking change: New default TLS CipherSuites for .NET on Linux

### ISSUE THREAD

**Issue by bartonjs** [dotnet/docs#20842]
## New default TLS CipherSuites for .NET on Linux

.NET, on Linux, now respects the OpenSSL configuration for default ciphersuites when doing TLS/SSL via the `SslStream` class or higher level operations like HTTPS via the `HttpClient` class. When there is not an explicitly configured default .NET on Linux uses a very restricted list of permitted ciphersuites.

### Version introduced

.NET 5.0 RC1

### Old behavior

.NET did not respect system configuration for default ciphersuites. The default ciphersuite list for .NET on Linux was very permissive.

### New behavior

.NET on Linux respects the OpenSSL configuration for default ciphersuites when it is specified in openssl.cnf. When ciphersuites are not explicitly configured the only permitted ciphersuites are the TLS 1.3 ciphersuites and  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, and TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256. Since this fallback default does not include any ciphersuites compatible with TLS 1.0 or TLS 1.1, these older protocol versions are effectively disabled by default.

Supplying a `CipherSuitePolicy` value to `SslStream` for a specific session will still replace the configuration file content and/or .NET fallback default.

### Reason for change

Users running .NET on Linux requested that the default configuration for SslStream be changed to one that provided a high security rating from third party assessment tools.

### Recommended action

The new defaults are likely to work when communicating with modern clients or to modern servers.  If you need to expand the default ciphersuite list to accept legacy clients (or contact legacy servers), either specify a `CipherSuitePolicy` value or change the OpenSSL configuration file.  On many Linux distributions the OpenSSL configuration file is at `/etc/ssl/openssl.cnf`.

This sample openssl.cnf is a minimal file that is equivalent to the .NET 5.0 on Linux default ciphersuites policy. Rather than replacing the system file, you need to merge these concepts with the file present on your system.

```
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256
```

On the Red Hat Enterprise Linux, CentOS, and Fedora distributions .NET applications default to the ciphersuites permitted by the system-wide cryptographic policies. On these distributions use the crypto-policies configuration instead of openssl.cnf.

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [X] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs

Not detectable via API analysis

---
#### Issue metadata

* Issue type: breaking-change

**Comment by bartonjs** [comment]
cc: @wfurt @tmds

**Comment by wfurt** [comment]
LGTM. should we mention this is applicable only to Linux with OpenSSL 1.1.x and old distributions are not affected?

**Comment by tmds** [comment]
cc @omajid
