### ISSUE TITLE
Unclear information

### ISSUE THREAD

**Issue by WouterrV** [dotnet/docs#20843]
Link: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=2

Let's say you're a newb (this is in the tutorials section after all) and you stumble upon this explanation:
>The assignment on the MiddleName property is an initializer. It initializes the compiler-generated backing field for the middle name.

I feel like it's missing some information. What are backing fields, what is an initializer, what are auto-properties?

**Comment by BillWagner** [comment]
Thanks for writing this @WouterrV 

I've added it to our list to update for this article.

**Comment by tdykstra** [comment]
Closing, as this article was retired. The URL currently redirects to C# 7 What's New.
