### ISSUE TITLE
byte[] content = await response.Content.ReadAsByteArrayAsync();

### ISSUE THREAD

**Issue by KungaLed** [dotnet/docs#20841]
"ReadAsByteArrayAsync()"  does not accept parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [Cancel a list of tasks (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@KungaLed Are you targeting .NET 5.0?

**Comment by Youssef1313** [comment]
@IEvangelist The link for the API reference in the article isn't working for some reason. That could be the point of confusion.

**Comment by KungaLed** [comment]
Sorry for late reply. I am on asp dotnet core 3.1
