### ISSUE TITLE
Suggestion on page scrolling when entering focus mode

### ISSUE THREAD

**Issue by IzreelJames** [dotnet/docs#20847]
On the Hello world tutorial- part four: do more with strings, there's the last assigned task, regarding methods, to be completed by adding the following code into the text editor:  

__string sayHello = "Hello World!";_
_Console.WriteLine(sayHello);
sayHello = sayHello.Replace("Hello", "Greetings");
Console.WriteLine(sayHello);

Console.WriteLine(sayHello.ToUpper());
Console.WriteLine(sayHello.ToLower());__

However, when clicking the enter focus mode button, users are prevented from scrolling through text, back to the last paragraphs, to revisit the provided instructions regarding the task of applying methods.

Nevertheless, the inscription of the provided code onto a piece of paper before opening the text editor was my way of circumventing it.

My suggestion is to enable scrolling when the text editor is open for this task.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-au/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Ping @mimisasouvanh 

Where should I route this for your team?

**Comment by mimisasouvanh** [comment]
@BillWagner @gewarren I can't repro this issue. Could you clarify what is happening and what is supposed to happen?

**Comment by BillWagner** [comment]
@mimisasouvanh I can't reproduce it either. It works fine on my machine.

I'll close.
