### ISSUE TITLE
sdk-and-target-framework-change needs more clarification

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20867]
The documentation is clear about these points:

- For .NET 5.0, we need to use `Microsoft.NET.Sdk`.
- For pre-.NET 5.0, we need to use `Microsoft.NET.Sdk.WindowsDesktop`.

But isn't clear for the scenario when multiple TFMs are targeted. For example:

```xml
<TargetFrameworks>net5.0;netcoreapp3.1;net472</TargetFrameworks>
```

**Comment by BillWagner** [comment]
@adegeo Can you comment on this one?

**Comment by adegeo** [comment]
I removed the breaking change metadata. That issue type is for reporting a breaking change between versions, not general questions between versions 😄 Really this should be filed on the article that you discovered the discrepancy.

There is an email out internally to figure this out. We'll get back to you 😃

**Comment by Youssef1313** [comment]
@adegeo @BillWagner I think I found the answer.

https://github.com/dotnet/sdk/issues/13427

The warning was **incorrectly** generated for multi-targeted projects and this issue was fixed.
I would suggest to update the doc to clearly emphasize that this breaking change doesn't affect multi-targeting.

**Comment by adegeo** [comment]
@Youssef1313 update which doc?

**Comment by Youssef1313** [comment]
@adegeo https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#winforms-and-wpf-apps-use-microsoftnetsdk
The include markdown file in repo is: https://github.com/dotnet/docs/blob/master/includes/core-changes/windowsforms/5.0/sdk-and-target-framework-change.md

A small note similar to: "If multiple frameworks are targeted and one of them is prior to .NET 5.0, you don't need to take any actions." would make things more clear in my opinion.

**Comment by adegeo** [comment]
Since this warning was removed in this scenario, I think adding a note just adds confusion. The warning was created to get people out of targeting the Desktop SDK directly. The note made sense when the warning was going to be generated, but now it's not generated.

**Comment by Youssef1313** [comment]
Sometimes I visit the breaking changes docs without actually facing some error or warning, just to read. In that case, the note makes things clearer.

But your opinion is reasonable too, and it's more common that breaking changes docs visitors are looking for a solution to a warning/error they face. So I'll close.
