### ISSUE TITLE
NegotiateStream and SslStream will no longer fail on multiple Begin operations without End

### ISSUE THREAD

**Issue by wfurt** [dotnet/docs#20865]
### NegotiateStream and SslStream will no longer fail on multiple *Begin operations without *End
This is change in how we handle error cases on security streams.

### Version introduced
5.0 RC1

### Old behavior
In the past sequence of 
- BeginXx
- BeginXx

would throw NotSupportedException exception.
 
### New behavior
Since the API calls are now backed by Task based implementation, this is no longer the case. 

### Reason for change
Switching internal implementation from APM to Tasks improves performance and decreases code complexity. 

### Recommended action

none. It was always invalid to call multiple Begin* operations without End*.

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [x] Networking
- [ ] Printing
- [x] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs
[SslStream.BeginAuthenticateAsServer](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.beginauthenticateasserver?view=net-5.0)
[SslStream.BeginAuthenticateAsClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.beginauthenticateasclient?view=net-5.0)
[NegotiateStream.BeginAuthenticateAsServer](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.negotiatestream.beginauthenticateasserver?view=net-5.0
)
[NegotiateStream.BeginAuthenticateAsClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.negotiatestream.beginauthenticateasclient?view=net-5.0
)

---
#### Issue metadata

* Issue type: breaking-change

cc: @stephentoub

**Comment by stephentoub** [comment]
They still may throw an exception, they're just not guaranteed to. The streams don't support two read operations at the same time, or two write operations at the same time, so if you call BeginXx a second time before the first has completed, it should still throw, yes?

**Comment by wfurt** [comment]
yes. Calling ReadAsync twice in parallel (and that include Begin* pattern) will still throw NotSupportedException.
