### ISSUE TITLE
Incorrect statement about Java requiring type definitions

### ISSUE THREAD

**Issue by adamyakes** [dotnet/docs#20872]
It's beyond picky, but I noticed this statement under [Classes and Interfaces](https://docs.microsoft.com/en-us/dotnet/fsharp/tour#classes-and-interfaces):

    /// Unlike other languages such as C# or Java, a new type definition is not needed 

Java does not require a new type definition. You can either provide an anonymous interface implementation or, if it's a functional interface, use a lambda expression. The following is valid Java:

```java
class Main {
  interface HelloWorldProvider {
    String getHelloWorld();
  }
  static void printHelloWorld(HelloWorldProvider provider) {
    System.out.println(provider.getHelloWorld());
  }
  public static void main(String[] args) {
    printHelloWorld(new HelloWorldProvider() {
      @Override 
      public String getHelloWorld() {
        return "Hello, world!";
      }
    });
    printHelloWorld(() -> "Hello, world!");
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour of F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tour)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by tdykstra** [comment]
Thanks for pointing that out. The comment in question is no longer in the article, so I'm closing this issue.

**Comment by DominikJaniec** [comment]
> Thanks for pointing that out. The comment in question is no longer in the article, so I'm closing this issue.

as far as I can tell, this comment is still on this page, right before paragraph: https://learn.microsoft.com/en-us/dotnet/fsharp/tour#which-types-to-use
