### ISSUE TITLE
How can I use profiling API with NetCore SDK

### ISSUE THREAD

**Issue by ivo-stoilov** [dotnet/docs#20871]
Hello, I need to implement some interfaces supported by .NetCore 2.2 (and above), but I am unable to find an article that explains how exactly to use ProfilerAPI as a part of NetCore SDK. Many thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d991b449-600d-2135-0db4-4d62b8104be3
* Version Independent ID: 33d4c6ef-3808-d107-a3de-93df77995840
* Content: [ICorProfilerInfo10 Interface](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo10-interface)
* Content Source: [docs/framework/unmanaged-api/profiling/icorprofilerinfo10-interface.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/icorprofilerinfo10-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @davmason
* Microsoft Alias: **davmason**

**Comment by tdykstra** [comment]
@davmason Can you help with this question?

**Comment by davmason** [comment]
Hi @ivo-stoilov 

We have some docs over in the runtime repository: https://github.com/dotnet/runtime/tree/main/docs/design/coreclr/profiling

This one might be particularly interesting on how to get a profiler attached to the runtime: https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/profiling/Profiler%20Loading.md

For getting started building a profiler, the easiest way would be to grab one of the profiler samples from the samples repo and modify it to your needs: https://github.com/dotnet/samples/tree/main/core/profiling

**Comment by ivo-stoilov** [comment]
Hello @davmason, many thanks for the useful articles. My question is more liely related to

**Comment by davmason** [comment]
The coreclr headers are not shipped as part of the Windows SDK. You can find the latest profiler header at https://github.com/dotnet/runtime/blob/main/src/coreclr/pal/prebuilt/inc/corprof.h.

The headers besides corprof.h don't change much, so most people I talk to copy corprof.h in to their project and use the Windows SDK headers for the rest (e.g corhdr.h).

**Comment by ivo-stoilov** [comment]
Thanks @davmason, it is exactly what I did and now I have the confirmation that it is the right approach. The issue can be closed as resolved.

**Comment by davmason** [comment]
Thanks, feel free to file another issue if you have any more questions.
