### ISSUE TITLE
Document new EditorConfig code style settings

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#20884]
---
**Issue moved from MicrosoftDocs/visualstudio-docs#5817**
- Please respond to @cremor.

---

_From @cremor on Friday, September 4, 2020 6:04:58 AM_

Commit https://github.com/MicrosoftDocs/visualstudio-docs/commit/d5c01b3f3e3d7adc365a8ef78a1272da1df03407 added the following new EditorConfig settings to the example EditorConfig file on the [overview page](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019). Those settings should also be documented on the [Language conventions page](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019).

- [ ] file_header_template
- [ ] dotnet_style_operator_placement_when_wrapping
- [ ] dotnet_style_prefer_simplified_boolean_expressions
- [ ] dotnet_remove_unnecessary_suppression_exclusions
- [ ] csharp_style_prefer_not_pattern
- [ ] csharp_style_prefer_pattern_matching

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f19aa22-56d1-ff22-a410-e5e0b6a80e6d
* Version Independent ID: 012968d3-07d2-5c37-fa3d-e3561eff8681
* Content: [Code style language rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/language-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/language-rules.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/language-rules.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by cremor** [comment]
Related: MicrosoftDocs/visualstudio-docs#3641

**Comment by cremor** [comment]
@gewarren Except for MicrosoftDocs/visualstudio-docs#3641 those have all been documented, so this issue can be closed.
