### ISSUE TITLE
The tutorial is missing some of the create resource commands

### ISSUE THREAD

**Issue by jpjsm** [dotnet/docs#20880]
[Enter feedback here]
Before creating the ACR, the user needs to create the RG
`az group create --name explore-docker-aks-rg --location <location>`

Before creating the ACR, let the user know the name in the example won't work because it's been used. ACR names must be unique across all subscriptions.

Before getting the credentials from the AKS Cluster, the cluster needs to be created
`az aks create --resource-group explore-docker-aks-rg --name explore-docker-aks --node-count 2 --generate-ssh-keys --attach-acr exploredocker`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @jpjsm, thank you for your feedback.
