### ISSUE TITLE
Overly complex install page

### ISSUE THREAD

**Issue by tkstanczak** [dotnet/docs#20897]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/498913/94997304-22b41480-05a2-11eb-82cd-442a2957537b.png)

This used to be simple, now installing .NET Core on Ubuntu seems like a nightmare to learn about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @tkstanczak  - thank you very much for posting this concern. I see that you're calling attention to the fact that the article is 21 mins to read, and while I understand that it might seem like a nightmare - I can promise you it's actually really not. This article covers nine different versions of Ubuntu and all of their individual nuances. In addition to that, the article offers up scripted vs manual install. In reality, if you're to consume the article you'd typically only spend a few minutes on each section, relevant to the version you're targeting and the choice between scripted or manual. I'm closing this for now, if you feel as though it needs to be reopened - we can continue the dialog - thank you.
