### ISSUE TITLE
Features marked as Obsolete in .NET 5.0 with custom diagnostics

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/docs#20894]
## Features marked as Obsolete in .NET 5.0

For .NET 5.0, we've made it more viable to mark APIs as obsolete by extending [`ObsoleteAttribute`](https://docs.microsoft.com/dotnet/api/system.obsoleteattribute) to include optional `DiagnosticId` and `UrlFormat` properties. These properties are respected by the compiler to generate build warnings using a custom diagnostic and to include a URL link to a documentation page for learning more about the obsoletion. This behavior allows for obsoletion warning to be suppressed specifically and separately from one another using the custom diagnostic id values.

Using this improved obsoletion mechanism, .NET 5.0 marks several features as obsolete using custom diagnostics.

If build warnings or errors are encountered due to usage of these obsolete APIs, follow the specific guidance provided for the different diagnostics using the URL link provided on the warning. Warnings or errors for these obsoletions cannot be suppressed using the standard diagnostic id for obsolete types or members; the custom `SYSLIB####` diagnostic id values must be used instead.

### Version introduced

.NET 5.0

### Old behavior

These APIs could be referenced without any build warnings.

### New behavior

References to these APIs will produce build warnings with the corresponding diagnostics.

### Reason for change

These APIs were marked as obsolete for a different reasons.

| Diagnostic ID     | Description |
| :---------------- | :---------- |
|  __`SYSLIB0001`__ | The UTF-7 encoding is insecure and should not be used. Consider using UTF-8 instead. |
|  __`SYSLIB0002`__ | PrincipalPermissionAttribute is not honored by the runtime and must not be used. |
|  __`SYSLIB0003`__ | Code Access Security is not supported or honored by the runtime. |
|  __`SYSLIB0004`__ | The Constrained Execution Region (CER) feature is not supported. |
|  __`SYSLIB0005`__ | The Global Assembly Cache is not supported. |
|  __`SYSLIB0006`__ | Thread.Abort is not supported and throws PlatformNotSupportedException. |
|  __`SYSLIB0007`__ | The default implementation of this cryptography algorithm is not supported. |
|  __`SYSLIB0008`__ | The CreatePdbGenerator API is not supported and throws PlatformNotSupportedException. |
|  __`SYSLIB0009`__ | The AuthenticationManager Authenticate and PreAuthenticate methods are not supported and throw PlatformNotSupportedException. |
|  __`SYSLIB0010`__ | This Remoting API is not supported and throws PlatformNotSupportedException. |
|  __`SYSLIB0011`__ | `BinaryFormatter` serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for recommended alternatives. |
|  __`SYSLIB0012`__ | Assembly.CodeBase and Assembly.EscapedCodeBase are only included for .NET Framework compatibility. Use Assembly.Location instead. |

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [X] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs

* `SYSLIB0001` - The UTF-7 encoding is insecure and should not be used. Consider using UTF-8 instead.
    * [`System.Text.UTF7Encoding` (constructors)](https://docs.microsoft.com/dotnet/api/system.text.utf7encoding.-ctor)
    * [`System.Text.Encoding.UTF7`](https://docs.microsoft.com/dotnet/api/system.text.encoding.utf7)
* `SYSLIB0002` - PrincipalPermissionAttribute is not honored by the runtime and must not be used. This obsoletion produces a build **error**.
    * [`System.Security.Permissions.PrincipalPermissionAttribute` (constructor)](https://docs.microsoft.com/dotnet/api/system.security.permissions.principalpermissionattribute.-ctor)
* `SYSLIB0003` - Code Access Security is not supported or honored by the runtime.
    * Classes in the `System.Security.Permissions` namespace:
        * [`CodeAccessSecurityAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.codeaccesssecurityattribute)
        * [`DataProtectionPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.dataprotectionpermission)
        * [`DataProtectionPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.dataprotectionpermissionattribute)
        * [`EnvironmentPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.environmentpermission)
        * [`EnvironmentPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.environmentpermissionattribute)
        * [`FileDialogPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.filedialogpermission)
        * [`FileDialogPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.filedialogpermissionattribute)
        * [`FileIOPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.fileiopermission)
        * [`FileIOPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.fileiopermissionattribute)
        * [`GacIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.gacidentitypermission)
        * [`GacIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.gacidentitypermissionattribute)
        * [`HostProtectionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.hostprotectionattribute)
        * [`IsolatedStorageFilePermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.isolatedstoragefilepermission)
        * [`IsolatedStorageFilePermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.isolatedstoragefilepermissionattribute)
        * [`IsolatedStoragePermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.isolatedstoragepermission)
        * [`IsolatedStoragePermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.isolatedstoragepermissionattribute)
        * [`KeyContainerPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermission)
        * [`KeyContainerPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermissionattribute)
        * [`KeyContainerPermissionAccessEntry`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermissionaccessentry)
        * [`KeyContainerPermissionAccessEntryCollection`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermissionaccessentrycollection)
        * [`KeyContainerPermissionAccessEntryEnumerator`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermissionaccessentryenumerator)
        * [`MediaPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.mediapermission)
        * [`MediaPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.mediapermissionattribute)
        * [`PermissionSetAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.permissionsetattribute)
        * [`PrincipalPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.principalpermission)
        * [`PrincipalPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.principalpermissionattribute)
        * [`PublisherIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.publisheridentitypermission)
        * [`PublisherIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.publisheridentitypermissionattribute)
        * [`ReflectionPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.reflectionpermission)
        * [`ReflectionPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.reflectionpermissionattribute)
        * [`RegistryPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.registrypermission)
        * [`RegistryPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.registrypermissionattribute)
        * [`ResourcePermissionBase`](https://docs.microsoft.com/dotnet/api/system.security.permissions.resourcepermissionbase)
        * [`ResourcePermissionBaseEntry`](https://docs.microsoft.com/dotnet/api/system.security.permissions.resourcepermissionbaseentry)
        * [`SecurityAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.securityattribute)
        * [`SecurityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.securitypermission)
        * [`SecurityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.securitypermissionattribute)
        * [`SiteIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.siteidentitypermission)
        * [`SiteIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.siteidentitypermissionattribute)
        * [`StorePermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.storepermission)
        * [`StorePermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.storepermissionattribute)
        * [`StrongNameIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.strongnameidentitypermission)
        * [`StrongNameIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.strongnameidentitypermissionattribute)
        * [`StrongNamePublicKeyBlob`](https://docs.microsoft.com/dotnet/api/system.security.permissions.strongnamepublickeyblob)
        * [`TypeDescriptorPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.typedescriptorpermission)
        * [`TypeDescriptorPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.typedescriptorpermissionattribute)
        * [`UIPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.uipermission)
        * [`UIPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.uipermissionattribute)
        * [`UrlIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.urlidentitypermission)
        * [`UrlIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.urlidentitypermissionattribute)
        * [`WebBrowserPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.webbrowserpermission)
        * [`WebBrowserPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.webbrowserpermissionattribute)
        * [`ZoneIdentityPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.zoneidentitypermission)
        * [`ZoneIdentityPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.security.permissions.zoneidentitypermissionattribute)
    * Classes that derive from `CodeAccessSecurityAttribute`
        * [`System.Configuration.ConfigurationPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.configuration.configurationpermissionattribute)
        * [`System.Data.Common.DBDataPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.data.common.dbdatapermissionattribute)
        * [`System.Data.OracleClient.OraclePermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.data.oracleclient.oraclepermissionattribute)
        * [`System.Diagnostics.EventLogPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.diagnostics.eventlogpermissionattribute)
        * [`System.Diagnostics.PerformanceCounterPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.diagnostics.performancecounterpermissionattribute)
        * [`System.DirectoryServices.DirectoryServicesPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.directoryservices.directoryservicespermissionattribute)
        * [`System.Drawing.Printing.PrintingPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.drawing.printing.printingpermissionattribute)
        * [`System.Net.DnsPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.dnspermissionattribute)
        * [`System.Net.SocketPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.socketpermissionattribute)
        * [`System.Net.WebPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.webpermissionattribute)
        * [`System.Net.Mail.SmtpPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.mail.smtppermissionattribute)
        * [`System.Net.NetworkInformation.NetworkInformationPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.networkinformation.networkinformationpermissionattribute)
        * [`System.Net.PeerToPeer.PnrpPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.peertopeer.pnrppermissionattribute)
        * [`System.Net.PeerToPeer.Collaboration.PeerCollaborationPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.net.peertopeer.collaboration.peercollaborationpermissionattribute)
        * [`System.ServiceProcess.ServiceControllerPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.serviceprocess.servicecontrollerpermissionattribute)
        * [`System.Transactions.DistributedTransactionPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.transactions.distributedtransactionpermissionattribute)
        * [`System.Web.AspNetHostingPermissionAttribute`](https://docs.microsoft.com/dotnet/api/system.web.aspnethostingpermissionattribute)
    * Interfaces:
        * [`System.Security.Permissions.IUnrestrictedPermission`](https://docs.microsoft.com/dotnet/api/system.security.permissions.iunrestrictedpermission)
        * [`System.Security.IPermission`](https://docs.microsoft.com/dotnet/api/system.security.ipermission)
        * [`System.Security.IStackWalk`](https://docs.microsoft.com/dotnet/api/system.security.istackwalk)
        * [`System.Security.Policy.IIdentityPermissionFactory`](https://docs.microsoft.com/dotnet/api/system.security.policy.iidentitypermissionfactory)
    * Classes that implement `IStackWalk`
        * [`System.Security.PermissionSet`](https://docs.microsoft.com/dotnet/api/system.security.permissionset)
        * [`System.Security.NamedPermissionSet`](https://docs.microsoft.com/dotnet/api/system.security.namedpermissionset)
    * Classes that implement `IPermission`
        * [`System.Security.CodeAccessPermission`](https://docs.microsoft.com/dotnet/api/system.security.codeaccesspermission)
    * Classes that derive from `CodeAccessPermission`
        * [`System.Configuration.ConfigurationPermission`](https://docs.microsoft.com/dotnet/api/system.configuration.configurationpermission)
        * [`System.Data.Common.DBDataPermission`](https://docs.microsoft.com/dotnet/api/system.data.common.dbdatapermission)
        * [`System.Data.Odbc.OdbcPermission`](https://docs.microsoft.com/dotnet/api/system.data.odbc.odbcpermission)
        * [`System.Data.OleDb.OleDbPermission`](https://docs.microsoft.com/dotnet/api/system.data.oledb.oledbpermission)
        * [`System.Data.SqlClient.SqlClientPermission`](https://docs.microsoft.com/dotnet/api/system.data.sqlclient.sqlclientpermission)
        * [`System.Data.OracleClient.OraclePermission`](https://docs.microsoft.com/dotnet/api/system.data.oracleclient.oraclepermission)
        * [`System.Drawing.Printing.PrintingPermission`](https://docs.microsoft.com/dotnet/api/system.drawing.printing.printingpermission)
        * [`System.Net.DnsPermission`](https://docs.microsoft.com/dotnet/api/system.net.dnspermission)
        * [`System.Net.SocketPermission`](https://docs.microsoft.com/dotnet/api/system.net.socketpermission)
        * [`System.Net.WebPermission`](https://docs.microsoft.com/dotnet/api/system.net.webpermission)
        * [`System.Net.Mail.SmtpPermission`](https://docs.microsoft.com/dotnet/api/system.net.mail.smtppermission)
        * [`System.Net.NetworkInformation.NetworkInformationPermission`](https://docs.microsoft.com/dotnet/api/system.net.networkinformation.networkinformationpermission)
        * [`System.Net.PeerToPeer.PnrpPermission`](https://docs.microsoft.com/dotnet/api/system.net.peertopeer.pnrppermission)
        * [`System.Net.PeerToPeer.Collaboration.PeerCollaborationPermission`](https://docs.microsoft.com/dotnet/api/system.net.peertopeer.collaboration.peercollaborationpermission)
        * [`System.Transactions.DistributedTransactionPermission`](https://docs.microsoft.com/dotnet/api/system.transactions.distributedtransactionpermission)
        * [`System.Web.AspNetHostingPermission`](https://docs.microsoft.com/dotnet/api/system.web.aspnethostingpermission)
        * [`System.Xaml.Permissions.XamlLoadPermission`](https://docs.microsoft.com/dotnet/api/system.xaml.permissions.xamlloadpermission)
    * Classes that derive from `ResourcePermissionBase`
        * [`System.Diagnostics.EventLogPermission`](https://docs.microsoft.com/dotnet/api/system.diagnostics.eventlogpermission)
        * [`System.Diagnostics.PerformanceCounterPermission`](https://docs.microsoft.com/dotnet/api/system.diagnostics.performancecounterpermission)
        * [`System.DirectoryServices.DirectoryServicesPermission`](https://docs.microsoft.com/dotnet/api/system.directoryservices.directoryservicespermission)
        * [`System.ServiceProcess.ServiceControllerPermission`](https://docs.microsoft.com/dotnet/api/system.serviceprocess.servicecontrollerpermission)
    * Enums in the `System.Security.Permissions` namespace:
        * [`DataProtectionPermissionFlags`](https://docs.microsoft.com/dotnet/api/system.security.permissions.dataprotectionpermissionflags)
        * [`EnvironmentPermissionAccess`](https://docs.microsoft.com/dotnet/api/system.security.permissions.environmentpermissionaccess)
        * [`FileDialogPermissionAccess`](https://docs.microsoft.com/dotnet/api/system.security.permissions.filedialogpermissionaccess)
        * [`FileIOPermissionAccess`](https://docs.microsoft.com/dotnet/api/system.security.permissions.fileiopermissionaccess)
        * [`HostProtectionResource`](https://docs.microsoft.com/dotnet/api/system.security.permissions.hostprotectionresource)
        * [`IsolatedStorageContainment`](https://docs.microsoft.com/dotnet/api/system.security.permissions.isolatedstoragecontainment)
        * [`KeyContainerPermissionFlags`](https://docs.microsoft.com/dotnet/api/system.security.permissions.keycontainerpermissionflags)
        * [`MediaPermissionAudio`](https://docs.microsoft.com/dotnet/api/system.security.permissions.mediapermissionaudio)
        * [`MediaPermissionImage`](https://docs.microsoft.com/dotnet/api/system.security.permissions.mediapermissionimage)
        * [`MediaPermissionVideo`](https://docs.microsoft.com/dotnet/api/system.security.permissions.mediapermissionvideo)
        * [`PermissionState`](https://docs.microsoft.com/dotnet/api/system.security.permissions.permissionstate)
        * [`ReflectionPermissionFlag`](https://docs.microsoft.com/dotnet/api/system.security.permissions.reflectionpermissionflag)
        * [`RegistryPermissionAccess`](https://docs.microsoft.com/dotnet/api/system.security.permissions.registrypermissionaccess)
        * [`SecurityAction`](https://docs.microsoft.com/dotnet/api/system.security.permissions.securityaction)
        * [`SecurityPermissionFlag`](https://docs.microsoft.com/dotnet/api/system.security.permissions.securitypermissionflag)
        * [`StorePermissionFlags`](https://docs.microsoft.com/dotnet/api/system.security.permissions.storepermissionflags)
        * [`TypeDescriptorPermissionFlags`](https://docs.microsoft.com/dotnet/api/system.security.permissions.typedescriptorpermissionflags)
        * [`UIPermissionClipboard`](https://docs.microsoft.com/dotnet/api/system.security.permissions.uipermissionclipboard)
        * [`UIPermissionWindow`](https://docs.microsoft.com/dotnet/api/system.security.permissions.uipermissionwindow)
        * [`WebBrowserPermissionLevel`](https://docs.microsoft.com/dotnet/api/system.security.permissions.webbrowserpermissionlevel)
    * Classes/Members that depend on Code Access Security types:
        * [`System.AppDomain.PermissionSet`](https://docs.microsoft.com/dotnet/api/system.appdomain.permissionset)
        * [`System.Security.HostProtectionException`](https://docs.microsoft.com/dotnet/api/system.security.hostprotectionexception)
        * [`System.Security.Policy.FileCodeGroup`](https://docs.microsoft.com/dotnet/api/system.security.policy.filecodegroup)
        * [`System.Security.Policy.StrongName`](https://docs.microsoft.com/dotnet/api/system.security.policy.strongname)
        * [`System.Security.Policy.StrongNameMembershipCondition`](https://docs.microsoft.com/dotnet/api/system.security.policy.strongnamemembershipcondition)
        * [`System.Security.Policy.ApplicationTrust(PermissionSet, IEnumerable<StrongName>)`](https://docs.microsoft.com/en-us/dotnet/api/system.security.policy.applicationtrust.-ctor#System_Security_Policy_ApplicationTrust__ctor_System_Security_PermissionSet_System_Collections_Generic_IEnumerable_System_Security_Policy_StrongName__)
        * [`System.Security.Policy.ApplicationTrust.FullTrustAssemblies`](https://docs.microsoft.com/dotnet/api/system.security.policy.applicationtrust.fulltrustassemblies)
        * [`System.Security.Policy.GacInstalled`](https://docs.microsoft.com/dotnet/api/system.security.policy.gacinstalled)
        * [`System.Security.SecurityManager`](https://docs.microsoft.com/dotnet/api/system.security.securitymanager)
        * [`System.Security.Policy.PolicyStatement`](https://docs.microsoft.com/dotnet/api/system.security.policy.policystatement)
        * [`System.Security.Policy.PolicyLevel.AddNamedPermissionSet(NamedPermissionSet)`](https://docs.microsoft.com/dotnet/api/system.security.policy.policylevel.addnamedpermissionset)
        * [`System.Security.Policy.PolicyLevel.ChangeNamedPermissionSet(string, PermissionSet)`](https://docs.microsoft.com/dotnet/api/system.security.policy.policylevel.changenamedpermissionset)
        * [`System.Security.Policy.PolicyLevel.GetNamedPermissionSet(string)`](https://docs.microsoft.com/dotnet/api/system.security.policy.policylevel.getnamedpermissionset)
        * [`System.Security.Policy.PolicyLevel.RemoveNamedPermissionSet(NamedPermissionSet)`](https://docs.microsoft.com/dotnet/api/system.security.policy.policylevel.removenamedpermissionset)
        * [`System.Security.Policy.PolicyLevel.RemoveNamedPermissionSet(string)`](https://docs.microsoft.com/dotnet/api/system.security.policy.policylevel.removenamedpermissionset)
        * [`System.Security.Policy.Publisher`](https://docs.microsoft.com/dotnet/api/system.security.policy.publisher)
        * [`System.Security.Policy.Site`](https://docs.microsoft.com/dotnet/api/system.security.policy.site)
        * [`System.Security.Policy.Url`](https://docs.microsoft.com/dotnet/api/system.security.policy.url)
        * [`System.Security.Policy.Zone`](https://docs.microsoft.com/dotnet/api/system.security.policy.zone)
* `SYSLIB0004` - The Constrained Execution Region (CER) feature is not supported.
    * [`System.Runtime.ConstrainedExecution.PrePrepareMethodAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.constrainedexecution.prepreparemethodattribute)
    * [`System.Runtime.ConstrainedExecution.ReliabilityContractAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.constrainedexecution.reliabilitycontractattribute)
    * [`System.Runtime.ConstrainedExecution.Cer`](https://docs.microsoft.com/dotnet/api/system.runtime.constrainedexecution.cer)
    * [`System.Runtime.ConstrainedExecution.Consistency`](https://docs.microsoft.com/dotnet/api/system.runtime.constrainedexecution.consistency)
    * [`System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.executecodewithguaranteedcleanup)
    * [`System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.prepareconstrainedregions)
    * [`System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegionsNoOP`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.prepareconstrainedregionsnoop)
    * [`System.Runtime.CompilerServices.RuntimeHelpers.PrepareContractedDelegate`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.preparecontracteddelegate)
    * [`System.Runtime.CompilerServices.RuntimeHelpers.ProbeForSufficientStack`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.probeforsufficientstack)
* `SYSLIB0005` - The Global Assembly Cache is not supported.
    * [`System.Reflection.Assembly.GlobalAssemblyCache`](https://docs.microsoft.com/dotnet/api/system.reflection.assembly.globalassemblycache)
* `SYSLIB0006` - Thread.Abort is not supported and throws PlatformNotSupportedException.
    * [`System.Threading.Thread.Abort()`](https://docs.microsoft.com/dotnet/api/system.threading.thread.abort)
    * [`System.Threading.Thread.Abort(Object)`](https://docs.microsoft.com/dotnet/api/system.threading.thread.abort#System_Threading_Thread_Abort_System_Object_)
* `SYSLIB0007` - The default implementation of this cryptography algorithm is not supported.
    * [`System.Security.Cryptography.SymmetricAlgorithm.Create()`](https://docs.microsoft.com/dotnet/api/system.security.cryptography.symmetricalgorithm.create)
    * [`System.Security.Cryptography.AssymetricAlgorithm.Create()`](https://docs.microsoft.com/dotnet/api/system.security.cryptography.assymetricalgorithm.create)
    * [`System.Security.Cryptography.HMAC.Create()`](https://docs.microsoft.com/dotnet/api/system.security.cryptography.hmac.create)
    * [`System.Security.Cryptography.KeyedHashAlgorithm.Create()`](https://docs.microsoft.com/dotnet/api/system.security.cryptography.keyedhashalgorithm.create)
* `SYSLIB0008` - The CreatePdbGenerator API is not supported and throws PlatformNotSupportedException.
    * [`System.Runtime.CompilerServices.DebugInfoGenerator.CreatePdbGenerator`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.debuginfogenerator.createpdbgenerator)
* `SYSLIB0009` - The AuthenticationManager Authenticate and PreAuthenticate methods are not supported and throw PlatformNotSupportedException.
    * [`System.Net.AuthenticationManager.Authenticate`](https://docs.microsoft.com/dotnet/api/system.net.authenticationmanager.authenticate)
    * [`System.Net.AuthenticationManager.PreAuthenticate`](https://docs.microsoft.com/dotnet/api/system.net.authenticationmanager.preauthenticate)
* `SYSLIB0010` - This Remoting API is not supported and throws PlatformNotSupportedException.
    * [`System.MarshalByRefObject.GetLifetimeService`](https://docs.microsoft.com/dotnet/api/system.marshalbyrefobject.getlifetimeservice)
    * [`System.MarshalByRefObject.InitializeLifetimeService`](https://docs.microsoft.com/dotnet/api/system.marshalbyrefobject.initializelifetimeservice)
* `SYSLIB0011` - BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for recommended alternatives.
    * [`System.Runtime.Serialization.IFormatter.Deserialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iformatter.deserialize)
    * [`System.Runtime.Serialization.IFormatter.Serialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iformatter.serialize)
    * [`System.Runtime.Serialization.Formatters.Formatter.Deserialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.formatter.deserialize)
    * [`System.Runtime.Serialization.Formatters.Formatter.Serialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.formatter.serialize)
    * [`System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.deserialize)
    * [`System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.serialize)
* `SYSLIB0012` - Assembly.CodeBase and Assembly.EscapedCodeBase are only included for .NET Framework compatibility. Use Assembly.Location instead.
    * [`System.Reflection.Assembly.CodeBase`](https://docs.microsoft.com/dotnet/api/system.reflection.assembly.codebase)
    * [`System.Reflection.Assembly.EscapedCodeBase`](https://docs.microsoft.com/dotnet/api/system.reflection.assembly.escapedcodebase)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by jeffhandley** [comment]
This is the summary breaking change document for the obsoletions in .NET 5.0, but we still need to write documents for each of the `SYSLIB` obsoletions and get the `aka.ms` links wired up.

/cc @GrabYourPitchforks

**Comment by gewarren** [comment]
@jeffhandley @GrabYourPitchforks instead of having separate breaking change entries like I've done for CAS, GAC and remoting, how about we have this single breaking change entry, and then a page for each SYSLIB warning (that's not part of the breaking changes docs - more just a reference)? It seems repetitive to have an overarching breaking change article for SYSLIB deletions, separate BC articles for each SYSLIB obsoletion, and separate reference articles for each SYSLIB warning.

**Comment by gewarren** [comment]
Also, there's currently a [bug in the .NET API ref docs](https://dev.azure.com/ceapex/Engineering/_workitems/edit/322199) where some of the obsolete types don't show as being obsolete (e.g. https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.globalassemblycache?view=net-5.0). Hopefully that will be fixed soon!
