### ISSUE TITLE
https://s.bracbank.com/FlybUZLMH

### ISSUE THREAD

**Issue by 71873241** [dotnet/docs#20908]
**Help us make content visible**

**Describe the new article**

**Comment by 71873241** [comment]
BRAC Bank SME/Krishi Branch Sherpur 
User: unit9546
M/S Ajiron Mini Auto Rice Mill
Customer ID. 02714683
A/C Type. CURRENT PRAPTI-ALL
Currentcy. BDT
Account Number No. 6001202714683001
(BSM), BRAC Bank Limited 2009

**Comment by BillWagner** [comment]
closing and hiding as spam.
