### ISSUE TITLE
The "Create a test" section should follow the "best practices" article

### ISSUE THREAD

**Issue by Saborion** [dotnet/docs#20903]
The "Create a test" section should follow the guidelines specified in [Unit testing best practices](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices), in particular the naming convention and the practice of avoiding a Setup (constructor in the case of xUnit) method.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @Saborion - that is a fair observation, I can fix that. Thanks
