### ISSUE TITLE
Title:ABDULAJIJ|Product:GENERAL_CONSUMER

### ISSUE THREAD

**Issue by 71873241** [dotnet/docs#20907]
**Issue description**

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by 71873241** [comment]
(DBBL A/C No.- 50110194001021)
1. DBBL live Account NO. 017162543147 
Janata Bank A/C NO. CD-06891011007666

**Comment by 71873241** [comment]
https://www.jb.com.bd/about_us/search?cx=012892411656638723322%3Aiy-qc3dk67u&q=06891011007666

**Comment by 71873241** [comment]
https://s.bracbank.com/FlybUZLMH

**Comment by 71873241** [comment]
https://accountalarafahbank.wordpress.com

**Comment by 71873241** [comment]
https://maaziznakla.websites.co.in/update/welcome-to-ms-ajiron-mini-auto-rice-mill/486356

**Comment by 71873241** [comment]
https://docs.microsoft.com/en-us/users/ajironmini-bracbank/

**Comment by 71873241** [comment]
Device: https://www.bpdb.gov.bd/
(BPDB) A/C NO. F02
BOOK NO. K99
W/O. 1010
CONSUMER NO.71873241
VAT ID: 9011045817
DATE: 30.09.29
ID: 1.11676733 
RE.NAKLA Phone: 01755581379

**Comment by BillWagner** [comment]
closing and locking as spam
