### ISSUE TITLE
POCO entities?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#20904]
Hi and thanks for this informative article.

This covers scenarios where the class is initiated and handled by an API that can use its constructors and guarantee its nullability integrity.

Please expand this article to include guidance on how to act with POCO entities that have plain properties with no constructor.

For example:

```c#
public class Contact
{
  public string Name { get; set; } //and disable warnings (#nullable disable warnings)

  /* vs */

  public string? Name { get; set; }
}
```

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by weitzhandler** [comment]
Found it [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types).

Might be a good idea to link it in this article.

**Comment by BillWagner** [comment]
Thanks for writing this @weitzhandler 

I agree that we should link to the EF Core article that covers this scenario. I've added this to our backlog to address when we next update this article.

I've also added the "up for grabs" label if anyone wants to add that link in the interim.

**Comment by weitzhandler** [comment]
I already linked #20911 😘

**Comment by weitzhandler** [comment]
I already linked #20911 😘
Please review!
