### ISSUE TITLE
IdentityServer will be a paid product

### ISSUE THREAD

**Issue by YvonneArnoldus** [dotnet/docs#20913]
Hi,

Could you please note that IdentityServer will be a paid product as of the next version. Because that might people think about not using it. Even if it is in your guide lines.

If I had known this when I was looking for authentication in .Net I might have not used it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188e28ad-73ce-658d-1712-f7b5e3ce61cf
* Version Independent ID: 52119533-ce08-ae89-21d0-fe36a8e3748d
* Content: [IdentityServer for Cloud Native Apps](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/identity-server)
* Content Source: [docs/architecture/cloud-native/identity-server.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/identity-server.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by GrabYourPitchforks** [comment]
IMO it'd be more useful to state that the current free version of IS4 exits support at the end of 2022, at which point future versions of the product will go paid. This does not affect apps using .NET 2.1 / 3.1 / 5.0, which all exit support before that point anyway.

**Comment by erjain** [comment]
You can read through the [documentation](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio) on the many options available for developers.

**Comment by erjain** [comment]
The issue can be closed now.

**Comment by BillWagner** [comment]
Closed as completed.
