### ISSUE TITLE
links wrong?

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/docs#20912]
HI

so at the bottom where its says "Additional resources"

one of the links is for "HttpClientFactory source code in the dotnet/extensions GitHub repository"

follow the link it does not take you to any source code related to HttpClientFactory,
 aka i want to see HttpClientFactory.cs everything there is about polly extentions and not HttpClientFactory

Please show me where i can see HttpClientFactory code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Seabizkit , thank you for pointing it out. 

As part of the .NET 5 consolidation efforts, the code is moved here: https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Http
For now, we have updated the link with respect to .NET core 3.1.8 but in future it may get updated again. 

Hope this helps !
