### ISSUE TITLE
Seems like we missed porting docs for `CA2218` and `CA2224` to dotnet docs repo

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#20917]
@gewarren seems like we missed porting docs for `CA2218` and `CA2224` to dotnet docs repo. The pages still exist in VS docs repo, though these have been ported as analyzers. Likely I missed them in the initial work.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/4291#discussion_r499729766_

**Comment by mavasani** [comment]
@gewarren Let me know if you will have bandwidth for this, otherwise I can take it up. Thanks!

**Comment by gewarren** [comment]
I can do it, thanks Manish!
