### ISSUE TITLE
EditorConfig link is broken

### ISSUE THREAD

**Issue by collinkruger** [dotnet/docs#20941]
In the first paragraph of https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options, the EditorConfig word links to https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options.md which 404s.

I think the correct link most likely is https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c8357d-11a6-6f12-b044-5ff44df65d10
* Version Independent ID: 0c103fd7-5cc4-2726-40f8-d759419ae635
* Content: [.NET code style rule options - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options)
* Content Source: [docs/fundamentals/code-analysis/code-style-rule-options.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/code-style-rule-options.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@collinkruger Thanks for letting us know!
