### ISSUE TITLE
Overview doc for Testing section of Fundamentals TOC

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#20947]
The  Fundamentals TOC plan calls for a testing overview doc that covers unit testing, integration testing, and tools -- Live Test in VS, CLI, CI, GitHub Actions. Expand the scope of [this doc](https://docs.microsoft.com/en-us/dotnet/core/testing/), and change the TOC node name accordingly.

**Comment by IEvangelist** [comment]
@tdykstra  I feel as though this overview article already satisfies these requirements with the exception of missing links to GitHub actions with 
.NET unit testing capabilities. I'm curious, what should the TOC entry be updated to?

**Comment by tdykstra** [comment]
The doc that the overview toc node links to currently is only about unit testing, so the TOC section was named unit testing to fit with the doc's title, but the toc plan intended this section to have a broader scope, including, e.g., integration testing.   And the existing article needs to be updated for .NET 5.  It could also be updated to not use zone pivots.  Zone pivots are for scenarios where the reader knows before reading the doc what to choose, but in this case the doc is an introduction article so it shouldn't assume the reader already knows how to choose a testing framework ahead of time and should instead provide guidance on how to choose.
