### ISSUE TITLE
Model Builder GPU help page does not indicate that you need another extension

### ISSUE THREAD

**Issue by frogcrush** [dotnet/docs#20959]
This page tells you how to install the requirements for Model Builder but does not tell you that you need another Visual Studio extension (https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU) installed. 

Without this, you can't use the auto model builder with a GPU.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-gb/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @frogcrush 

Thank you for raising this issue. I see it in the second bullet point in the prerequisites. Could you please clarify where the confusion comes from?

![image](https://user-images.githubusercontent.com/46974588/95375379-86458700-08ad-11eb-8aec-4c1ba9a6551b.png)

**Comment by frogcrush** [comment]
I obviously can't read.
