### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arichards-unity** [dotnet/docs#20960]
[Enter feedback here]
Search for "returned valued" it should likely read "returned value"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @arichards-unity I've added this to our backlog, and add the "up for grabs" and "good first issue" labels in any community members want to fix it before we get to it.

When you see these, you can click the edit button (it looks like a pencil) and submit a quick PR to address it. That may be quicker for all of us.
