### ISSUE TITLE
Tutorial Source Code

### ISSUE THREAD

**Issue by sorryb** [dotnet/docs#20962]
Can we see the tutorial source code ? Especially for unfinished yaml Kubernetes resources .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes?source=docs#creating-the-aspnet-core-project-using-visual-studio-2019)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @sorryb, thank you for reaching out. 

Unfortunately, the actual source code for the `WebApi` project is not available or maintained under any public repository. The article only talks about the necessary steps to build an ASP.NET Core application with Docker support which can be further 
deployed to AKS/kubernetes. These steps are generic and can be referred as to build any such project. 

Having said that, there is an entire application [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) available for you to explore. It  has been developed following similar steps.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @sorryb, I am closing this issue as of now. If you want to explore more on this topic, you may want to check out below MS learn modules - 

[Hello World Microservice tutorial](https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/intro)
[Create and deploy a cloud-native ASP.NET Core microservice](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/)

Please feel free to reopen it, if you have any pending question. 

Thank you.
