### ISSUE TITLE
NuGet.org accepted licenses underspecified

### ISSUE THREAD

**Issue by boringcactus** [dotnet/docs#20963]
The documentation on the PackageLicenseExpression property says
> NuGet.org accepts only OSI or FSF approved licenses when using license type expression.

However, I tried to use the OSI-approved [zero-clause BSD license](https://opensource.org/licenses/0BSD), which is listed at the very top of [the SPDX version permalinked in that section of the docs](https://spdx.org/spdx-specification-21-web-version#h.luq9dgcle9mo), and it was rejected as unsupported. Evidently only a subset of OSI or FSF approved licenses are allowed by NuGet.org, in which case the documentation should say which ones are allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @rrelyea @nkolev92

**Comment by gewarren** [comment]
This issue was moved to NuGet/docs.microsoft.com-nuget#2274

**Comment by gewarren** [comment]
We are removing this file in our repo with #22277 . NuGet license info will be in the NuGet docs instead.
