### ISSUE TITLE
What's new for .NET 5

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#20977]
- [x] For SEO reasons, I would consider changing the title to **What's new in .NET 5** and move evolution to the introduction. While very accurate, I don't think most customers will be searching on evolution. Searching for **What's new in .NET 5** doesn't return this doc in the first couple of pages.

- [x] ~.NET 5 extends these characteristics, making incremental improvements:~

     Container size optimizations -> That's not an incremental improvement AFAIK. Can you provide a link to [this issue](https://github.com/dotnet/dotnet-docker/issues/1814#issuecomment-625294750) or otherwise provide more information?

- [x] **What .NET 5 is not** - consider **What's not included in .NET 5** - My guess is that will MT better and have better SEO
    Consider changing text to:  NET 5 isn't a **_complete_** replacement for .NET Framework. - After all, we want customers to migrate from .NET Framework to .NET 5, and for many it is a replacement.

- [x]  Web Forms replacement should be Blazor  ***or Razor Pages***
  There are no plans to port the following technologies from .NET Framework to .NET 5, but there are supported alternatives ~included in .NET 5~:
  Consider changing column heading from **Recommendation** to something like Alternative, or recommended replacement, recommended alternative, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8175dfa-c812-afef-c018-a5927995ef43
* Version Independent ID: 4fd72a98-c51f-cbd9-0578-d6448bab4749
* Content: [The evolution of .NET Core to .NET 5](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five)
* Content Source: [docs/core/dotnet-five.md](https://github.com/dotnet/docs/blob/master/docs/core/dotnet-five.md)
* Product: **dotnet-core**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Thank you for the feedback @Rick-Anderson - much appreciated.

**Comment by IEvangelist** [comment]
Hi @Rick-Anderson - curious about a few of your statements.

> Container size optimizations -> That's not an incremental improvement AFAIK

How is that **not** incremental improvement? Reducing the size of a container with every release is absolutely incremental improvement. I'm leaving this as is.

**Comment by Rick-Anderson** [comment]
@IEvangelist  thanks for accepting my other suggestions, as @BillWagner  stated, it's great work

> How is that not incremental improvement? Reducing the size of a container with every release is absolutely incremental improvement. I'm leaving this as is.

Unless I'm not understanding the container size changes, (which is very possible), the layering approach is new to 5.0 and not an incremental change.  With layering, 99+% of the bytes from pulling the ASP.NET Core image is eliminated and 36MB of the SDK. That's 100MB improvement.

Looping in @mthalman the expert on layering.

I also made another request, provide more information than  the single bullet item

* ***Container size optimizations***

**Comment by mthalman** [comment]
> Unless I'm not understanding the container size changes, (which is very possible), the layering approach is new to 5.0 and not an incremental change. With layering, 99+% of the bytes from pulling the ASP.NET Core image is eliminated and 36MB of the SDK. That's 100MB improvement.

The strategy of layer sharing is not something new to 5.0.  This had been done in prior releases.  We just applied it to all of the SDK container images for 5.0.  There are a variety of historical reasons why it hadn't been done pre-5.0.  I would consider this to be an incremental improvement.

**Comment by Rick-Anderson** [comment]
We still need more info.
> Container size optimizations

Doesn't provide enough information.

**Comment by Rick-Anderson** [comment]
@IEvangelist  please add a link to https://github.com/dotnet/dotnet-docker/issues/1814#issuecomment-625294750

* Container size optimizations

by itself doesn't give enough information. The comments in the link tell the story.
