### ISSUE TITLE
What are the exit codes for this program?

### ISSUE THREAD

**Issue by andykn** [dotnet/docs#20988]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b07b20b-5937-9784-082f-8655bad1acdd
* Version Independent ID: 22eda03b-36bf-e612-384f-af3a3d2725a6
* Content: [Installutil.exe (Installer Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/installutil-exe-installer-tool)
* Content Source: [docs/framework/tools/installutil-exe-installer-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/installutil-exe-installer-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
You might find this StackOverflow post helpful:  https://stackoverflow.com/questions/62648723/retrieving-exit-status-of-installutil-with-errorlevel

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
