### ISSUE TITLE
Breaking change notification: Remoting APIs are obsolete

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/docs#20994]
## Remoting APIs are obsolete

The APIs `MarshalByRefObject.GetLifetimeService` and `MarshalByRefObject.InitializeLifetimeService` are obsolete as warning as of .NET 5.0.

### Version introduced

.NET 5.0 RC1

### Old behavior

In .NET Framework 2.x - 4.x, the `GetLifetimeService` and `InitializeLifetimeService` methods would control the lifetime of instances involved with .NET remoting.

In .NET Core 2.x and .NET Core 3.x, the `GetLifetimeService` and `InitializeLifetimeService` methods always throw `PlatformNotSupportedException` at runtime.

### New behavior

In .NET 5.0+, the `MarshalByRefObject.GetLifetimeService` and `MarshalByRefObject.InitializeLifetimeService` methods continue to throw `PlatformNotSupportedException`. However, the methods are now also marked obsolete (as warning).

```cs
MemoryStream stream = new MemoryStream(); // MemoryStream, like all Stream instances, subclasses MarshalByRefObject
obj.InitializeLifetimeService(); // throws PlatformNotSupportedException; also produces warning SYSLIB0010
```

This is a compile-time only change. There is no runtime change from previous versions of .NET Core.

### Reason for change

[.NET remoting](https://docs.microsoft.com/previous-versions/dotnet/netframework-1.1/kwdt6w2k(v=vs.71)) is a legacy technology which allows instantiating an object in another process (potentially even on a different machine) and interacting with that object as if it were an ordinary in-process .NET object instance. The .NET remoting infrastructure only exists in .NET Framework 2.x - 4.x. .NET Core and .NET 5.0+ do not have support for .NET remoting, and the remoting APIs either do not exist or always throw exceptions on these runtimes.

To help steer developers away from these APIs, we are obsoleting select remoting-related APIs. These APIs may be removed entirely in a future version of .NET.

### Recommended action

Consider using WCF or HTTP-based REST services to communicate with objects in other applications or across machines. The document [.NET Framework technologies unavailable on .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#remoting) provides further guidance on choosing an alternative technology.

If you must continue calling the `GetLifetimeService` or `InitializeLifetimeService` APIs, you can suppress the `SYSLIB0010` warning in code, as shown below.

```cs
MarshalByRefObject obj = GetMarshalByRefObj();
#pragma warning disable SYSLIB0010 // disable the warning
obj.InitializeLifetimeService(); // will still throw PNSE
obj.GetLifetimeService(); // will still throw PNSE
#pragma warning restore SYSLIB0010 // re-enable the warning
```

The warning can also be suppressed within the .csproj. Doing so will disable the warning for all source files within the project.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
   <TargetFramework>net5.0</TargetFramework>
   <!-- NoWarn below will suppress SYSLIB0010 project-wide -->
   <NoWarn>$(NoWarn);SYSLIB0010</NoWarn>
  </PropertyGroup>
</Project>
```

> Suppressing `SYSLIB0010` disables only the `MarshalByRefObject.GetLifetimeService` and `MarshalByRefObject.InitializeLifetimeService` obsoletion warnings. It does not disable any other warnings. Additionally, suppressing the warning will not change the hardcoded runtime behavior of always throwing `PlatformNotSupportedException`.

### Category

- Core .NET libraries

### Affected APIs

The following APIs are now obsolete as warning but have no behavioral changes from previous versions of .NET Core:

- [x]  [`MarshalByRefObject.GetLifetimeService`](https://docs.microsoft.com/dotnet/api/system.marshalbyrefobject.getlifetimeservice) - 5.0 RC1

- [x]  [`MarshalByRefObject.InitializeLifetimeService`](https://docs.microsoft.com/dotnet/api/system.marshalbyrefobject.initializelifetimeservice) - 5.0 RC1

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
Should gRPC be a recommended alternative?
