### ISSUE TITLE
Breaking change notification: Global Assembly Cache-related APIs are obsolete

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/docs#20993]
## Global Assembly Cache-related APIs are obsolete

.NET Core and .NET 5+ eliminate the concept of the [Global Assembly Cache (GAC)](https://docs.microsoft.com/dotnet/framework/app-domains/gac) that was present in .NET Framework. As such, all .NET Core and .NET 5+ APIs which deal with the GAC either fail or perform no operation.

To help steer developers away from these APIs, we are obsoleting select GAC-related APIs. These APIs may be removed in a future version of .NET.

### Version introduced

.NET 5.0 RC1

### Old behavior

In .NET Framework 2.x - 4.x, the `Assembly.GlobalAssemblyCache` Boolean property would return _true_ if the queried assembly was loaded from the GAC, _false_ if the queried assembly was loaded from a different location on disk.

In .NET Core 2.x and .NET Core 3.x, the `Assembly.GlobalAssemblyCache` Boolean property is hardcoded always to return _false_, reflecting that the GAC does not exist in .NET Core.

```cs
Assembly asm = typeof(object).Assembly;
Console.WriteLine(asm.GlobalAssemblyCache); // prints 'True' on .NET Framework, 'False' on .NET Core
```

### New behavior

In .NET 5.0+, the `Assembly.GlobalAssemblyCache` Boolean property continues to be hardcoded always to return _false_. The property getter is now also marked obsolete to indicate to callers that they should stop calling the API.

```cs
Assembly asm = typeof(object).Assembly;
Console.WriteLine(asm.GlobalAssemblyCache); // prints 'False' on .NET 5.0+, also produces warning SYSLIB0005 at compile time
```

This is a compile-time only change. There is no runtime change from previous versions of .NET Core.

### Reason for change

The Global Assembly Cache (GAC) does not exist as a concept in .NET Core and .NET 5.0+. Libraries and applications should not use the old `Assembly.GlobalAssemblyCache` API to make determinations about runtime behavior. The library or application may not expect this property always to return _false_ on .NET Core or .NET 5.0+.

### Recommended action

If your application queries the `Assembly.GlobalAssemblyCache` property, consider removing the call to that property getter. If your application uses the returned value to choose between an "assembly in the GAC" vs. an "assembly not in the GAC" flow at runtime, reconsider whether the flow still makes sense for a .NET Core / .NET 5.0+ application.

If you must continue querying the `Assembly.GlobalAssemblyCache` property, you can suppress the `SYSLIB0005` warning in code, as shown below.

```cs
Assembly asm = typeof(object).Assembly;
#pragma warning disable SYSLIB0005 // disable the warning
Console.WriteLine(asm.GlobalAssemblyCache); // prints 'False' on .NET 5.0+
#pragma warning restore SYSLIB0005 // re-enable the warning
```

The warning can also be suppressed within the .csproj. Doing so will disable the warning for all source files within the project.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
   <TargetFramework>net5.0</TargetFramework>
   <!-- NoWarn below will suppress SYSLIB0005 project-wide -->
   <NoWarn>$(NoWarn);SYSLIB0005</NoWarn>
  </PropertyGroup>
</Project>
```

> Suppressing `SYSLIB0005` disables only the `Assembly.GlobalAssemblyCache` and obsoletion warning. It does not disable any other warnings.

### Category

- Core .NET libraries

### Affected APIs

The following APIs are now obsolete as warning but have no behavioral changes:

- [x] [`Assembly.GlobalAssemblyCache` property](https://docs.microsoft.com/dotnet/api/system.reflection.assembly.globalassemblycache) - 5.0 RC1

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@GrabYourPitchforks currently only one API is listed here. Do you plan to add more to this breaking change or create separate issues? If there are more to add, it might be best just to add check boxes to this issue instead.

**Comment by GrabYourPitchforks** [comment]
There's only one affected API right now. We might add extra APIs under this same warning code in a future release.
