### ISSUE TITLE
Review & revise .NET docs hub page "Create your application" web card

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#21004]
Review & revise .NET docs hub page "Create your application" web card, part of https://github.com/dotnet/docs/issues/20970.

**Comment by IEvangelist** [comment]
Might want to wait until https://github.com/dotnet/docs/pull/23229 is done

**Comment by scottaddie** [comment]
@IEvangelist Here's another issue that will need a new owner.

**Comment by IEvangelist** [comment]
I believe @Rick-Anderson should be, if not you.

**Comment by Rick-Anderson** [comment]
@wadepickett  hold all the cards
