### ISSUE TITLE
.NET Hub page: New design plus update for .NET 6

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#21005]
[.NET Hub page](https://docs.microsoft.com/en-us/dotnet/)

**Comment by scottaddie** [comment]
@IEvangelist Heads up that I'm unassigning myself. Who should this be assigned to?

**Comment by IEvangelist** [comment]
I believe @Rick-Anderson should be, if not you.

**Comment by Rick-Anderson** [comment]
@wadepickett  is the hub expert, assigning him.

**Comment by wadepickett** [comment]
Changing this to reflect just the .NET Hub pages, and creating a new ASP.NET Hub page issue on the aspnetcore.docs repo to track that.

Related to ASP.NET Hub pages issue: AspNetCore.Docs#22599

Reviewed details of what is needed with Bill Wagner.   This update request is aligned with the .NET 6 timeline and there are new HUB designs we will be using that are not ready at the moment. (So I will not be starting on this yet.)

I will be handling both the .NET and ASP.NET Hub pages for .NET 6 changes

For now I reviewed all links, verified the Hub page is working as is.  It is.

**Comment by IEvangelist** [comment]
Closed by #26869
