### ISSUE TITLE
Missing article in MSDN C# Programming Guide

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [dotnet/docs#21015]
**Issue description**
There was an article with the title "Object-Oriented Programming (C#)" that was in the C# [programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/), but it has disappeared. What happened to this article, and can it be brought back?

**Comment by BillWagner** [comment]
@ChukwuemezieChristopherAneke 

We reworked that article into [this tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming) It covers the same concepts, but focuses more on the scenarios for different object-oriented techniques.

I'll close this as an answered question.
