### ISSUE TITLE
Review & revise .NET docs hub page "Create your application" desktop card

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#21011]
Review & revise .NET docs hub page "Create your application" desktop card, part of #20970.

**Comment by tdykstra** [comment]
@IEvangelist #21010 and #21011 look like duplicates, and both were moved to Done in .NET Desktop (.NET 5 wave), should these issues be closed?

**Comment by IEvangelist** [comment]
> @IEvangelist #21010 and #21011 look like duplicates, and both were moved to Done in .NET Desktop (.NET 5 wave), should these issues be closed?

We should probably just close them both.
