### ISSUE TITLE
Remove project.json example from versions/index.md

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#2102]
There's a *project.json* example lingering in the *versions/index.md* topic + a small textual change to make post v1.0.0 release.

**Comment by bleroy** [comment]
OK, I'll check. I'm pretty sure I had removed all those samples, that didn't make much sense in that document in the first place.

**Comment by GuardRex** [comment]
You did :+1:

**Comment by bleroy** [comment]
Yes, I can confirm: those examples are already gone from my PR.

**Comment by bleroy** [comment]
:) So now I'm confused: what do you want me to do?

**Comment by GuardRex** [comment]
Nothing ... you got it. We just needed the `project.json` example out of there. I was going to do it, but your rewrite fixes this issue automatically.

**Comment by bleroy** [comment]
Cool. Thanks.
