### ISSUE TITLE
Microsoft Extensions hides content

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#21023]
For me it's difficult to find config, DI, logging, etc because they are hidden under Microsoft Extensions 
I think Microsoft Extensions  is meaningless to new folks. All the other top level TOC are descriptive.

![image](https://user-images.githubusercontent.com/3605364/95639171-2d9ff680-0a33-11eb-8254-d91c4e8c6aa3.png)

@tdykstra  is the TOC expert.

For example, filter by title on logging is even obscured:
![image](https://user-images.githubusercontent.com/3605364/95639463-3c3add80-0a34-11eb-8d27-daa0e940e3d5.png)

I think @tdykstra  knows how to fix this. The 3 extension articles are advanced and not what beginners are looking for. It hides https://docs.microsoft.com/en-us/dotnet/core/extensions/logging

The extensions/logging articles might be better found under https://docs.microsoft.com/en-us/dotnet/core/diagnostics/logging-tracing

So far, I can't find a google search a customer is likely to use that finds the extensions/logging docs.

**Comment by davidfowl** [comment]
Totally agree! It should be split out into individual topics logging, dependency injection, configuration, caching etc
