### ISSUE TITLE
TargetFramework change to net5.0 may break customer logic relying on the TargetFramework value

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#21024]
## TargetFramework changed from netcoreapp3.1 to net5.0
Any MSBuild logic a customer has that tries to parse or use the TargetFramework value may fail.

### Version introduced

.NET 5.0

### Old behavior
```xml
<TargetFramework>netcoreapp3.1</TargetFramework>
```

### New behavior
```xml
<TargetFramework>net5.0</TargetFramework>
```

### Reason for change
With the move to .net 5 both to simplify the TargetFramework value to the simple alias and allow some projects to include a TargetPlatform in the TargetFramework property, we've changed the formatting.

### Recommended action
**Existing project file**
```xml
<PropertyGroup Condition="$(TargetFramework.StartsWith('netcoreapp'))">
```
**Suggested change**
```xml
<PropertyGroup Condition="'$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)'))' == '.NETCoreApp'">
```

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [x] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
I'd add links the the following for more information:

- https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/
- https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

Also, there are a variety of patterns that may be parsing the TargetFramework incorrectly (StartsWith, Contains, etc).  So I'd mention that the existing project file and suggested changes are just examples.
