### ISSUE TITLE
Examples in C# Console App Only

### ISSUE THREAD

**Issue by shailendrabirthare** [dotnet/docs#21039]
[Enter feedback here]

I see all the examples in C# Console App. Can we not use Spark for .NET library in a Web API project and deploy it in Azure cloud?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started?tabs=windows)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by gewarren** [comment]
We're no longer updating the .NET for Apache Spark documentation, and have archived it to https://learn.microsoft.com/previous-versions/dotnet/spark/what-is-spark. As a result, we're closing all the active .NET for Apache Spark issues. I'm sorry we couldn't address your issue.
