### ISSUE TITLE
dotnet nuget push all packages requires source

### ISSUE THREAD

**Issue by timheuer** [dotnet/docs#21036]
The examples for pushing all package (`*.nupkg`) do not show a source parameter -- the dotent nuget push command requires a source when * is used according to errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@karann-msft When is the `--source` option required?

**Comment by nkolev92** [comment]
I think `https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push#options` is up to date. 

It's required when `defaultPushSource` is not specified in the config files.

https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section

**Comment by tdykstra** [comment]
@nkolev92 Thanks!
