### ISSUE TITLE
add net 5 additions

### ISSUE THREAD

**Issue by timrobertsusa** [dotnet/docs#21035]
please add net 5 additions-- and what is included in the images (manifest)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9643196-016b-a19b-d113-4fa134b592ab
* Version Independent ID: 67d4ecd1-70ad-67b1-3665-46e54f0a23c1
* Content: [Architecting container and microservice-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @timrobertsusa, thank you for reaching out. 

Could you please share some more details on what specific changes you want to see in this article ? 
Please note, the present content of this eBook supports .NET core 3.1 (LTS) where the official support available till Dec,2022. For more details, you can refer [.NET Core release lifecycle](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) And .NET 5 related changes would be available only after it goes in GA.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @timrobertsusa , `.NET Microservices: Architecture for Containerized .NET Applications` eBook is now updated to `.NET 5`. You may want to refer the latest edition.
