### ISSUE TITLE
Update sample for support of JSON serialization/deseriazation of quoted numbers

### ISSUE THREAD

**Issue by nathanpovo** [dotnet/docs#21033]
The [workaround](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#quoted-numbers) provided to serialize/deserialize quoted numbers should be updated.

The support for quoted numbers was discussed in https://github.com/dotnet/runtime/issues/30255 and a converter is no longer necessary as of pull requests https://github.com/dotnet/runtime/pull/39363, https://github.com/dotnet/runtime/pull/39716, and  https://github.com/dotnet/runtime/pull/41539.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for calling attention to this - we'll include it with the .NET 5.0 updates to the documentation.

**Comment by tdykstra** [comment]
Fixed by https://github.com/dotnet/docs/pull/21108
