### ISSUE TITLE
Provide example in documentation on how to correctly override behavior of Equals and GetHashCode on record type

### ISSUE THREAD

**Issue by aredfox** [dotnet/docs#21031]
Please consider reopening this, to add an example on how users can override the behavior of Equals and GetHashCode?
Just to be clear, for users, I don't find it clear enough in the documentation how it is used. Can a clear example be documented how to override GetHashCode, and Equals? Or how to override the behavior?

As this is what "normal" C# devs would try to do, and would expect to do so in every class/struct, I feel documentation around this should be more precise on how to override the behavior, or if it simply is not possible.
![image](https://user-images.githubusercontent.com/1333704/95662536-f8c99780-0b37-11eb-824d-ef71ba5b2890.png)

PS, consider including this [example/gist ](https://gist.github.com/ericsampson/84672e210cc3b8c6e6db12af01aa25de) - it's a very clear way of communicating an example for me.

This way I was able to complete my way though the IDE warnings better and make my own new implementation of for example a "ValueObject" that relies on the record base implementation and overrides the behavior only when a given set of properties is passed, thus only when I want my ValueObject not to take certain properties into account: https://gist.github.com/aredfox/7beaa0b3d8bd62ff1f0d2defdf9c2ac1

Without such help of the gist at https://gist.github.com/ericsampson/84672e210cc3b8c6e6db12af01aa25de I was lost in compiler warnings, and the documentation was good - but verbose and needed very clear reading. Thus Twitter & someone kind enough to make a gist helped me out here. But I feel many more will face this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn

**Comment by ericsampson** [comment]
I agree, that there should be a lot of user-facing documentation for the things defined here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#members-of-a-record-type

- what is `EqualityContract`, when/how to override it.
- how to "override" the synthesized `Equals` and `GetHashCode` methods
- notes on ^ re the implications of `sealed` records, inheriting from `Object` vs another record

**Comment by BillWagner** [comment]
Thanks both @aredfox @ericsampson 

I've added this to the list of updates for the .NET 5 / C# 9 release. I agree it's important to cover these areas in more detail. These should be covered by the work for #20591

**Comment by BillWagner** [comment]
Closing as I believe this was fixed in #21271

@aredfox Check [this article](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/equality-operators#record-types-equality) covers what you were looking for. If not, add another comment, and we'll make further updates.
