### ISSUE TITLE
Invalid example for System.Net.Dns in .NET Core 1.1 docs

### ISSUE THREAD

**Issue by CameronAavik** [dotnet/docs#2104]
I was looking to write an application which made use of sockets in .net core 1.1, so I firstly searched for "Sockets C#" and came across a nice example seen below:

https://msdn.microsoft.com/en-us/library/system.net.sockets.socket(v=vs.110).aspx#Examples

I tried using this and realised that the following line didn't work because no such method existed in .net core

`hostEntry = Dns.GetHostEntry(server);`

I then went to the .net core docs equivalent and saw the exact same example again

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=netcore-1.1#examples

I then looked up the specific .net core documentation on System.Net.Dns below

https://docs.microsoft.com/en-us/dotnet/api/system.net.dns?view=netcore-1.1

And the only example on this page uses a method that isn't supported by .net core 1.1. I don't know enough about System.Net.Dns to fix it myself otherwise I'd make a PR to fix this.

**Comment by CameronAavik** [comment]
Now I think about it, this issue should probably also expand to System.Net.Sockets too, since it's example isn't a valid .net core program either.

**Comment by mairaw** [comment]
Thanks @CameronAavik. We'll investigate.

**Comment by GuardRex** [comment]
Hello @CameronAavik ... thanks for opening this issue. I whipped up a quickie with `hostEntry = Dns.GetHostEntry(string.Empty);` and it came back ok for 2.0-preview1: `Hostname: DESKTOP-1A2B3C4`.

Over in ...

https://docs.microsoft.com/en-us/dotnet/api/system.net.dns?view=netcore-1.1

... I see what you mean. As you said, `Dns.GetHostByName` is obsolete ...

https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostbyname?view=netframework-4.7&viewFallbackFrom=netcore-1.1

My plan is to update the example for `Dns Class` to show `Dns.GetHostEntry`.

@CameronAavik Are you still having an issue with `Dns.GetHostEntry` generally?

**Comment by CameronAavik** [comment]
Cheers @GuardRex, I since fixed my issue anyways and found how to do what I wanted.

**Comment by GuardRex** [comment]
@CameronAavik Awesome! Thanks again for raising the issue. Let us know if you spot any other doc problems.
