### ISSUE TITLE
Possible mistake in access modifiers description

### ISSUE THREAD

**Issue by Maximus5** [dotnet/docs#21040]
> private protected: The type or member can be accessed only within its declaring assembly, by code in the same class or in a type that is derived from that class.

Looks like it should be **private internal**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Maximus5** [comment]
Definitely I could be wrong, because this strange **private protected** mentioned several types.
But it's really confusing, because the **internal** was intended to assembly visibility.
If **private protected** is correct, could it be stated in docs that it's not an error and intended?

**Comment by BillWagner** [comment]
@Maximus5 The articles are correct. After considerable debate, `private protected` was chosen for this type of access. I'm not sure how to make it more clear, as all the articles that mention this access do use the correct access modifer.

I'll close this as an answered question.
