### ISSUE TITLE
aka.ms URLs related to BinaryFormatter

### ISSUE THREAD

**Issue by svick** [dotnet/docs#21056]
The PR that introduced this article (https://github.com/dotnet/docs/pull/19445) says that it should serve as the target for https://aka.ms/binaryformatter, but that hasn't happened. I think this should be fixed.

Specifically:

* If you use `BinaryFormatter` in .Net 5, VS will point you to https://aka.ms/dotnet-warnings/SYSLIB0011, which redirects to https://github.com/dotnet/docs/issues/19601. That issue explains the warning, so I think that's correct.
* https://github.com/dotnet/docs/issues/19601 points to https://aka.ms/binaryformatter, which redirects to https://github.com/GrabYourPitchforks/docs/blob/bf_obsoletion_docs/docs/standard/serialization/resolving-binaryformatter-obsoletion-errors.md. I think that should be changed to redirect to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a9e65f-dc69-2d49-763a-3ef41bd055ae
* Version Independent ID: 52919538-8a37-e4fa-2483-607c220e7ea2
* Content: [BinaryFormatter security guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)
* Content Source: [docs/standard/serialization/binaryformatter-security-guide.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/binaryformatter-security-guide.md)
* Product: **dotnet**
* GitHub Login: @GrabYourPitchforks
* Microsoft Alias: **levib**

**Comment by gewarren** [comment]
@GrabYourPitchforks the ask here is to update https://aka.ms/binaryformatter to point to https://docs.microsoft.com/dotnet/standard/serialization/binaryformatter-security-guide. Can you do that if you agree?

**Comment by GrabYourPitchforks** [comment]
The redirect is now live.
