### ISSUE TITLE
Usage section missing from API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2105]
I have noticed that usage sections don't seem to be rendering in API reference.

For example, the source for `CompareInfo.LastIndexOf(string, string)` contains [`<block subset="none" type="usage">`](https://github.com/dotnet/docs/blob/ff5da6d/xml/System.Globalization/CompareInfo.xml#L2415-L2420), which is not shown on [its API reference page](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.compareinfo.lastindexof?view=netframework-4.7#System_Globalization_CompareInfo_LastIndexOf_System_String_System_String_).

[On MSDN](https://msdn.microsoft.com/en-us/library/w21y1fec(v=vs.110).aspx), this section seems to render as a "Notes to Callers" section.

**Comment by svick** [comment]
The same seems to apply to overrides sections too. For `DbDataAdapter`, the "Notes to Inheritors" is present [on MSDN](https://msdn.microsoft.com/en-us/library/system.data.common.dbdataadapter(v=vs.110).aspx) and [in source](https://github.com/dotnet/docs/blob/ff5da6d/xml/System.Data.Common/DbDataAdapter.xml#L39-L65), but not [on docs.ms](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdataadapter?view=netframework-4.7).

**Comment by rpetrusha** [comment]
@svick, thanks for opening this issue. 
In addition to "Notes to Callers" and "Notes to Inheritors", "Notes to Implementers" sections (for example, at [`IComparable<T>.CompareTo(T)`](https://msdn.microsoft.com/en-us/library/43hc6wht(v=vs.110).aspx) on MSDN are not rendering. 
We've opened two internal bugs, #963599 and #963655, to track this.

**Comment by BillWagner** [comment]
Both the internal bugs reference above are completed, so I'm closing this.
