### ISSUE TITLE
Missing redirections

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#21057]
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1

This link is used in the description of this [youtube](https://www.youtube.com/watch?v=xgxudnuWkPw0) video from dotNET channel. One of the comments is complaining that the link is broken. So a redirection is needed.

**Comment by BillWagner** [comment]
Thanks for noting this @Youssef1313 

I've just submitted #21059 to address this.
