### ISSUE TITLE
Deployment links is to 1.0 docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#21053]
Page: https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/deploy-applications

Link (at bottom): [.NET Framework Deployment Guide](https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms994336(v=msdn.10))

At the very least, there is a 2.0 section. I don't know the better place is after that.

**Comment by eriawan** [comment]
@gewarren 

I think this issue should be solved, because it's already fixed by this PR: https://github.com/MicrosoftDocs/SupportArticles-docs/pull/36

**Comment by gewarren** [comment]
Thank you @eriawan
