### ISSUE TITLE
Breaking change: New JsonSerializerDefaults.Web option leveraged by ASP.NET allows quoted numbers when deserializing JSON

### ISSUE THREAD

**Issue by layomia** [dotnet/docs#21067]
## Breaking change: New JsonSerializerDefaults.Web option leveraged by ASP.NET allows quoted numbers when deserializing JSON

In 5.0, we introduced a `JsonSerializerDefaults` enum along with a constructor on `JsonSerializerOptions` that takes this enum (https://github.com/dotnet/runtime/issues/34626). This allows the creation of a `JsonSerializerOptions` instance with predetermined options, depending on the scenario. `JsonSerializerDefaults.Web` specifies the following options:

`PropertyNamingPolicy` = `JsonNamingPolicy.CamelCase`
`PropertyNameCaseInsensitive` = `true`
`NumberHandling` = `JsonNumberHandling.AllowReadingFromString`

The number handling feature is new in .NET 5 (https://github.com/dotnet/runtime/issues/30255) and allows custom number handling, including allowing the serializer to read quoted numbers (i.e JSON strings), rather than throw `JsonException`. With `JsonSerializerDefaults.Web`, the serializer is permitted to read strings as numbers.

In 3.x, the default `JsonSerializerOptions` used by ASP.NET Core specified the camel case naming policy, and allowed case-insensitive property naming matching, but per the serializer's capabilities in 3.x, reading JSON strings as numbers was not allowed. In 5.0, ASP.NET has adopted the new `JsonSerializerDefaults.Web` as the default (de)serialization options. This means that all ASP.NET applications by default will now allow reading JSON strings as numbers.

Note that the new JSON extension methods on `HttpClient` and `HttpContent` exposed by `System.Net.Http.Json` (https://github.com/dotnet/runtime/issues/32937) also use the new `JsonSerializerDefaults.Web` options.

### Version introduced

5.0

### Old behavior

Quoted numbers in JSON payloads which were to map with number properties in object graphs on deserialization would cause `JsonException` to be thrown.

### New behavior

Quoted numbers in JSON payloads which are to map with number properties in object graphs on deserialization are valid. 

This is **not** the new behavior for the default stand-alone `JsonSerializer` or `JsonSerializerOptions`, but rather it is the default behavior specifically within ASP.NET Core apps, the `System.Net.Http.Json` package,  or when the user opts-in and chooses the `JsonSerializerDefaults.Web` option.

This behavior is making a scenario more permissive, specifically going from throwing `JsonException` to successfully coercing a number from a JSON string. This is technically not a breaking change. However, since this will affect many ASP.NET Core apps, it is a significant behavioral change which should be advertised.

### Reason for change

User feedback and requests for opt-in, more permissive number handling in `JsonSerializer` (https://github.com/dotnet/runtime/issues/30255) indicated that many JSON producers (e.g. services across the web) emit quoted numbers. Allowing reading quoted numbers helps .NET applications successfully parse these payloads by default in web contexts. This API is exposed via `JsonSerializerDefaults.Web` so that there is a handy way to specify the same options across different application layers e.g. client, server, shared. More detail here - https://github.com/dotnet/runtime/pull/42240#issuecomment-692829199.

### Recommended action

If this change is disruptive, e.g. the strict/default number handling in `JsonSerializer` is depended upon for validation, the previous behavior can be reenabled by setting the `JsonSerializeOptions.NumberHandling` option used by the application to `JsonNumberHandling.Strict`.

For ASP.NET Core MVC and web API applications, this can be configured in `Startup` using the following snippet:

```C#
services.AddControllers()
   .AddJsonOptions(options.NumberHandling = JsonNumberHandling.Strict);
```

### Category

- [x] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [x] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [x] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs

[`JsonSerializer.Deserialize`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.deserialize?view=netcore-3.1)
[`JsonSerializer.DeserializeAsync`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.deserializeasync?view=netcore-3.1)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by layomia** [comment]
FYI - @tdykstra, @pranavkm, @terrajobst

**Comment by tdykstra** [comment]
Yes, that's the right place for it.  And the [quoted numbers section of the Newtonsoft migration doc](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#quoted-numbers) would mention this and link to the 3.1-5.0 doc as well.

**Comment by ahsonkhan** [comment]
> Quoted numbers in JSON payloads which are to map with number properties in object graphs on deserialization are valid.

Please clarify that this is **not** the default stand-alone `JsonSerializer` API behavior, but rather it is the default behavior within aspnet apps and when the user chooses the `JsonSerializerDefaults.Web` option.

**Comment by gewarren** [comment]
@tdykstra Do you have any interest in documenting the serialization breaking changes?

**Comment by tdykstra** [comment]
I'm interested in reviewing them to make sure I'm aware of changes that affect the STJ docs. If we get a bunch of them and you'd like some assistance I can help out. I'd need a crash course in how to document breaking changes. 😄

**Comment by seanbecker15** [comment]
For anyone wondering how to (quickly) patch the problem this issue creates when transitioning from .net core 2.0+ to .net core 3.0+...

You can use the old newtonsoft json serializer by adding `services.AddControllers().AddNewtonsoftJson()` from the `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package.

**Comment by ahsonkhan** [comment]
What problem exactly would that workaround be for, @seanbecker15, that would require adding back newtonsoft?

If you want quoted numbers allowed while deserializing JSON, it will work be default with STJ within an ASP.NET app.
If you don't want quoted numbers allowed, the workaround is listed in the issue above, for STJ:
```C#
services.AddControllers()
   .AddJsonOptions(options.NumberHandling = JsonNumberHandling.Strict);
```

**Comment by seanbecker15** [comment]
@ahsonkhan My apologies for the confusion — I was referring to a few problems caused by migrating from .net core 2.0+ to 3.0+ that this issue happens to address.

For context, here are the problems I ran into when upgrading:
- Unable to deserialize quoted numbers from JSON
- Properties with annotation [JsonProperty(“item”)] no longer use “item”, but rather the name of the property

**Comment by ahsonkhan** [comment]
> Unable to deserialize quoted numbers from JSON

That shouldn't happen. Please file an issue in https://github.com/dotnet/runtime with your aspnet details, .net version and provide a minimal repro and someone will help you take a look.

> Properties with annotation [JsonProperty(“item”)] no longer use “item”, but rather the name of the property

That is expected since `JsonProperty` is a Newtonsoft.Json specific attribute. You need to use the attribute that System.Text.Json will understand:
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=net-5.0

This migration guide should be useful: 
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

For anything else, please file **new** issues in https://github.com/dotnet/runtime so the conversation is in the right place :)
