### ISSUE TITLE
Update samples to use netstandard and dotnet cli

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#211]
All samples right now use DNX (or in the case of libraries, use it for testing).  They should be updated to use netstandard and dotnet cli.

**Comment by blackdwarf** [comment]
@cartermp this is you dude. Go wild. :)

**Comment by mairaw** [comment]
Can we close this one @cartermp?

**Comment by cartermp** [comment]
Nope.  I'll create a PR.

**Comment by mairaw** [comment]
Is this still a work in progress @cartermp?

**Comment by mairaw** [comment]
@cartermp do we still have this issue?

**Comment by cartermp** [comment]
Not anymore, no.  We can close this.
