### ISSUE TITLE
using .net core 3.1 is working as well but no support listed in the page

### ISSUE THREAD

**Issue by AlterX76** [dotnet/docs#21100]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599cc3e1-7358-4b1e-6b04-6dff8c14ba22
* Version Independent ID: 11565e32-bc09-8503-491d-6d3181152449
* Content: [ICLRStrongName::StrongNameSignatureVerificationEx Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/iclrstrongname-strongnamesignatureverificationex-method)
* Content Source: [docs/framework/unmanaged-api/hosting/iclrstrongname-strongnamesignatureverificationex-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/hosting/iclrstrongname-strongnamesignatureverificationex-method.md)
* Product: **dotnet-framework**
* GitHub Login: @jeffschwMSFT
* Microsoft Alias: **jeffschw**

**Comment by tdykstra** [comment]
@jeffschwMSFT should the [Requirements](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/iclrstrongname-strongnamesignatureverificationex-method#requirements) section mention Core/5+?

**Comment by jeffschwMSFT** [comment]
I would not recommend adding it to the documentation without more fully understanding the scenario.  It would work, but not in a x-plat way and potentially not in all the ways it was originally intended.  If this functionality is necessary, I would recommend that we file it as a feature request for .NET Core.

**Comment by tdykstra** [comment]
> I would recommend that we file it as a feature request for .NET Core.

Which repo should I transfer this issue to?

**Comment by jeffschwMSFT** [comment]
I would recommend opening a new issue with the scenario of how this is used in dotnet/runtime.

**Comment by tdykstra** [comment]
@AlterX76 since I don't know the scenario, can you open an issue in [dotnet/runtime](https://github.com/dotnet/runtime/issues/new/choose)?

Closing this issue.
