### ISSUE TITLE
"Derived" section in API docs is no longer collapsed by default

### ISSUE THREAD

**Issue by reflectronic** [dotnet/docs#21109]
The doc page for each type has a small section which lists other types that derive from it. At some point in the past, this section would only show a handful of items by default, and the user would need to hit "Expand" to see the full list. This functionality regressed at some point, and it makes for some pretty hideous pages ([ever wanted to know every enum in .NET?](https://docs.microsoft.com/en-us/dotnet/api/system.enum?view=netcore-3.1)).

**Comment by gewarren** [comment]
Wow, that is quite a list. @mimisasouvanh is this a regression?

**Comment by gewarren** [comment]
I see what you mean in this [internet archive page](https://web.archive.org/web/20190313225252/https://docs.microsoft.com/en-us/dotnet/api/system.enum?view=netcore-2.1) from March 2019.

![image](https://user-images.githubusercontent.com/24882762/96154270-776d5e80-0ec3-11eb-9f0c-aebd63b0ab6f.png)

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4997
