### ISSUE TITLE
Pattern matching 'and' short-circuit?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#21126]
Hi,

Please clarify whether the `and` or `or` operators in the [Pattern Matching](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#pattern-matching-enhancements) section act as an _and_ or _and also_, _or_ or _or else_ operators respectively, thereby shortcircuiting on first negative value if any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good question @weitzhandler 

ping @333fred I read the spec and the referenced issues. I didn't see any statement about short-circuiting. That makes me assume they do not short circuit. Can you verify?

**Comment by weitzhandler** [comment]
> That makes me assume they do not short circuit. Can you verify?

😱

**Comment by 333fred** [comment]
That's actually a difficult question to answer, and I don't envy having to write this in a better way, but the short answer is that we specifically did _not_ specify the order of evaluation. The long answer is the  compiler is allowed to reorder checks as much as it wants to, with the only restriction being that the first pattern that matches, lexically, is the pattern that is chosen. Generally speaking, the implementation will stop considering a pattern as soon as possible. If any check fails, will immediately stop considering any pattern that includes that check. So for example if all patterns check whether a property is 1, and the first thing we check is that property and it isn't 1, no pattern matches. See the line at bottom this section of the C# 8 spec, and the additional comments at the bottom of the document: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md#positional-pattern

**Comment by weitzhandler** [comment]
Well, the way I see it then, is what it's even better than simple sorry circuit.
Though it might be a good idea to update the docs with this but of info.

**Comment by pkulikov** [comment]
The patterns reference on logical patterns:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns

has the note about the undefined order of evaluation (see the note block at the end of the referenced section).

Looks like this issue can be closed? @BillWagner @weitzhandler what do you think?
