### ISSUE TITLE
What is the default langversion for .NET Core 1.x projects?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#21129]
The information in the title is missing from the page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@IanKemp 

Those versions aren't listed because .NET Core 1.x is out of support.  See this page for more details: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

I'll close this.

**Comment by IanKemp** [comment]
@BillWagner My issue is more that every version of .NET and .NET Core, **except version 1.x**, is covered by that page. The omission of Core 1.x is therefore unusual as I would expect that page to be an exhaustive list.

Would it not be appropriate to add a note to the page regarding end of support for Core 1.x? Potentially linking to the document you referred to?
