### ISSUE TITLE
Try.net output encoding issue

### ISSUE THREAD

**Issue by miloszkukla** [dotnet/docs#21130]
It seems there is some problem with encoding of the output of try.net.

![image](https://user-images.githubusercontent.com/2670221/96273727-f2bc3680-0fcf-11eb-9a78-4083fbd84ff1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
This issue was moved to dotnet/try#889
