### ISSUE TITLE
Explain the issue with stacked usings and IAsyncDisposable

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/docs#21134]
[The last topic](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#stacked-usings) advises against using stacked `using`s when the resource is an `IAsyncDisposable`, saying that it could cause the `DisposeAsync` method to not be called, but does not explain how that happens or why, nor does it links to anywhere where that info can be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @andre-ss6 
Thank you so much for posting this issue. We really appreciate it. I'll take a look at adding more details on this in the near future.
