### ISSUE TITLE
':severity' suffix in option value specification is now optional 

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#21132]
With https://github.com/dotnet/roslyn/pull/48580, i.e. starting VS2019 16.9 P2, `:severity` suffix is optional. We should either edit the current `Severity` paragraph in this page to explicitly specify it is now optional OR completely move it to a `NOTE` in the section mentioning that it was mandatory before `VS2019 16.9`. I am also not sure if we want to add this content now or wait for VS2019 16.9 Preview2 and/or GA to release.

@gewarren There are two many unknowns for me here, so I am just filing this tracking issue instead of creating a PR to update the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f19aa22-56d1-ff22-a410-e5e0b6a80e6d
* Version Independent ID: 012968d3-07d2-5c37-fa3d-e3561eff8681
* Content: [Code style language rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/language-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/language-rules.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/language-rules.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Also adding @mikadumont, as it seems the `:severity` suffix style of severity configuration is confusing lot of users as that syntax is not understood by the compiler, hence the configured severity in such syntax is never respected on command line builds.

**Comment by gewarren** [comment]
@mavasani When is VS 2019 version 16.9 set to release?

**Comment by mavasani** [comment]
> When is VS 2019 version 16.9 set to release?

@vatsalyaagrawal?

**Comment by gewarren** [comment]
Looks like preview 2 was 12/8/20 and GA is 3/2/21.
