### ISSUE TITLE
gRPC in Docker Container

### ISSUE THREAD

**Issue by abethan** [dotnet/docs#21139]
Most of the developers are facing issues when exposing the gRPC server in a Docker container. I would appreciate if you could write a Tutorial on that. Thanks in advance for considering my request. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 270fc708-a721-0e61-d47a-fbd0c27a3ac6
* Version Independent ID: 3b4e49b6-0df1-f6e1-e66d-0655d1571701
* Content: [gRPC](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/grpc)
* Content Source: [docs/architecture/cloud-native/grpc.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/grpc.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
I think, this tutorial will make more sense when added in [ASP.NET gRPC docs](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1) instead of the architecture section. 
Thoughts @scottaddie @JamesNK ?

**Comment by nishanil** [comment]
@abethan In eShopOnContainers sample, we have implemented this scenario. You can refer this wiki for details: https://github.com/dotnet-architecture/eShopOnContainers/wiki/gRPC

**Comment by tdykstra** [comment]
>In eShopOnContainers sample, we have implemented this scenario. You can refer this wiki for details: https://github.com/dotnet-architecture/eShopOnContainers/wiki/gRPC 

@abethan Thanks for contacting us. We believe that your suggestion has has been addressed. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
