### ISSUE TITLE
Not clear that when creating a custom converter Utf8JsonReader should exit Read method positioned on EndArray/EndObject token and with correct depth

### ISSUE THREAD

**Issue by gmanvel** [dotnet/docs#21147]
It is worth mentioning that upon exiting Read method Utf8JsonReader's TokenType & CurrentDepth should follow some rules depending on TokenType/Depth of the reader upon entering the method & underlying json structure (object/array vs simple property)

E.g. given this json
```
{
   "property1":"value1",
   "property2":{
      "nestedLevel1":{
         "nestedLevel2":"nestedLevelValue2"
      }
   }
}
```
and the model to deserialize to

```
public class Model
{
   public string Property1 {get; set;}

   [JsonPropertyName("property2")
   [JsonConverter(typeof(NestedLevel2Converter))]
   public string NestedLevel2Property {get; set;}
}
```
And the converter itself

```
public sealed class NestedLevel2Converter: JsonConverter<string>
    {
        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
            // upon existing we should have reader.TokenType == JsonTokenType.EndObject
            // && reader.CurrentDepth == depth of the reader upon entering Read method
            // https://github.com/dotnet/runtime/blob/98fc7edd7fbfba0e0120dbd4533b1ad7c73cbb7d/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L439
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }
    }
```

As mentioned above, as per https://github.com/dotnet/runtime/blob/98fc7edd7fbfba0e0120dbd4533b1ad7c73cbb7d/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L439 when Read method exits Utf8JsonReader has to have specific state.
Documentation doesn't mention this, and it's not clear that this rule should be followed to avoid JsonException _read too much or not enough_ exception for this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#other-custom-converter-samples)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @steveharter
