### ISSUE TITLE
Socket Server samples - create/update guide using Task-based Asynchronous Pattern (TAP)

### ISSUE THREAD

**Issue by MaynardSi** [dotnet/docs#21146]
The example on this page is using the Asynchronous Programming Model (APM). I was wondering if a guide could be written using the newly-recommended Task-based Asynchronous Pattern (TAP) (https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9839abf8-561c-613b-c8d0-332894e20c43
* Version Independent ID: 37104b22-e94f-a564-013b-c05ab624c63d
* Content: [Using an Asynchronous Server Socket](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-an-asynchronous-server-socket)
* Content Source: [docs/framework/network-programming/using-an-asynchronous-server-socket.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-an-asynchronous-server-socket.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by antonfirsov** [comment]
Fixed by #30759.
