### ISSUE TITLE
Add Switch Expression

### ISSUE THREAD

**Issue by shibusavic** [dotnet/docs#21140]
Two cents: Adding a switch expression example to this page would help increase switch expression adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe86aaa-1ea3-2582-8bab-f46ba20862a3
* Version Independent ID: 88d7273c-c055-ae98-84ef-f06e98a1ff46
* Content: [Enums - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#enum-values-and-operations)
* Content Source: [spec/enums.md](https://github.com/dotnet/csharplang/blob/master/spec/enums.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the suggestion @shibusavic That's a really good idea.

I've added this to update as part of our .NET 5 wave of articles.

**Comment by BillWagner** [comment]
I'm going to close this.

A great enum example was added in #23623


This shouldn't be added in the language spec. Instead, the language reference is preferred as the text is more informative and less normative.
