### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Resolved817** [dotnet/docs#21163]
"conidering"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e80a45b-7084-c3c3-149a-d891dc8de9be
* Version Independent ID: 983d417d-b9d9-7b86-5e46-cc40cc3127c7
* Content: [Relational vs. NoSQL data](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/relational-vs-nosql-data)
* Content Source: [docs/architecture/cloud-native/relational-vs-nosql-data.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/relational-vs-nosql-data.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by Resolved817** [comment]
Pull request #21165 created for the above issue.

**Comment by sughosneo** [comment]
Hi @Resolved817 , thank you for pointing that out. PR has been merged. So closing this issue. 

Thank you.
