### ISSUE TITLE
Narcotics in Docs example

### ISSUE THREAD

**Issue by cronoxyd** [dotnet/docs#21167]
Maybe the method in the example for CS0206 shouldn't be called "MyMeth"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d3795-df85-8962-e082-4aebaa0cc05b
* Version Independent ID: 8b1a6eaf-b543-8c98-6618-5528e536a568
* Content: [Compiler Error CS0206](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0206)
* Content Source: [docs/csharp/misc/cs0206.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0206.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @cronoxyd 

I've just submitted a PR to address this.
