### ISSUE TITLE
Adhere property names to naming policies

### ISSUE THREAD

**Issue by JohanPetersson** [dotnet/docs#21162]
I think it would helpful to mention how to write property names and adhere to the naming policies. 

`writer.WritePropertyName(options.PropertyNamingPolicy.ConvertName(kvp.Key.ToString()));`

Your example is just writing the property name as-is:

`writer.WritePropertyName(kvp.Key.ToString());`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion - we'll update the sample code.

cc @steveharter
