### ISSUE TITLE
Clarifications about exposing "Any CPU" assemblies to 32-bit COM clients needed

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/docs#21173]
This page https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com explains how to expose a .NET Core assembly to COM. It looks very similar to how .NET Framework assemblies are exposed. However there's a major difference: https://github.com/dotnet/runtime/issues/32493

With .NET Framework "Any CPU" assembly can be consumed by both 32-bit and 64-bit clients. With .NET Core "Any CPU" assemblies are accompanied with 64-bit .comhost.dll and so they can only be consumed by 64-bit clients. This is a breaking change and totally unexpected. Would be nice to have it documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0842844-005f-5004-022d-fce7a82daff8
* Version Independent ID: 88ddeba8-3b31-95f4-26b2-4a12a7313b47
* Content: [Exposing .NET Core components to COM](https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com)
* Content Source: [docs/core/native-interop/expose-components-to-com.md](https://github.com/dotnet/docs/blob/master/docs/core/native-interop/expose-components-to-com.md)
* Product: **dotnet-core**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by tdykstra** [comment]
@Dmitry-Me Thanks for reporting that. @jkoritzinsky Please verify the wording of the note as added in #22531
