### ISSUE TITLE
a logical error

### ISSUE THREAD

**Issue by logicz** [dotnet/docs#21174]
In the first example of contrvariance maybe should be
iobj = istr;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e9ed9b-7aff-a0d8-4f79-f8db71ce2fb4
* Version Independent ID: e371bd2a-9840-8d4c-b10e-cb4b41289083
* Content: [in (Generic Modifier) - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-generic-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-generic-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/in-generic-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this question @logicz 

The article is correct for a contravariant interface (using the `in` modifier). Specifying `in` means that the type argument is restricted to arguments. Therefore you can substitute a derived type for a base type. Suppose you have a method `void M(object o)`. You can call it with a string: `M("this is the argument for the parameter o");`

Contravariance allows a more derived type to be substituted.

**Comment by logicz** [comment]
Thanks for your answer, I've thought a little bit more even before and find out I'm mistaken.
