### ISSUE TITLE
Header links useless

### ISSUE THREAD

**Issue by kitsu** [dotnet/docs#21188]
This consolidated page of breaking changes would be useful, but every same-text header on the page is assigned the same id.
This means all the header hyperlinks point to the first instance on the page.

Per HTML spec please make id attributes unique on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5971107-0c8c-13d3-b48a-96f9bf4ea6ea
* Version Independent ID: 802d3628-64eb-fb23-a258-af523b536bd2
* Content: [ASP.NET Core breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore)
* Content Source: [docs/core/compatibility/aspnetcore.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/aspnetcore.md)
* Product: **dotnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by gewarren** [comment]
I'm considering a proposal where each breaking change is its own article, which would resolve this issue.

**Comment by gewarren** [comment]
At least for the .NET 5 breaking changes that are listed on separate pages now, this is fixed.

I don't think it's high enough priority to go back and add anchors to all these links for the .NET Core 3.1 and earlier versions, so I'm going to close the issue.
