### ISSUE TITLE
Remoting namespace is available on .NET Core 3.x and .NET 5

### ISSUE THREAD

**Issue by tylerjamesmadsen** [dotnet/docs#21187]
The [Remoting section](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#remoting) indicates that Remoting is not supported in .NET Core and .NET 5, and that "we don't plan on adding support for it in the future." However, the [_System.Runtime.Remoting_ namespace](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.remoting?view=netcore-3.1) _is_ available in both. Are those statements in the "Remoting" section still accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e44818-fc25-7210-c430-7c87b84825eb
* Version Independent ID: 2f40ef4c-ea4b-ccb5-3b7f-9d02c3b7ab82
* Content: [.NET Framework technologies unavailable on .NET Core and .NET 5+](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable)
* Content Source: [docs/core/porting/net-framework-tech-unavailable.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/net-framework-tech-unavailable.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by blowdart** [comment]
Yes. Just because a namespace is present doesn't mean anything under it works, or that anything will be added to it.

Remoting will not come to .NET 5, or anything after it.
