### ISSUE TITLE
Cognitive Services Custom Speech Service example request

### ISSUE THREAD

**Issue by bryanjhogan** [dotnet/docs#2119]
Please provide an example in C# where I can upload an mp3 or wav file to cognitive services for translation or transcription.

**Comment by svick** [comment]
This issue belongs on [the Microsoft/azure-docs repo](https://github.com/Microsoft/azure-docs), not here.

I did find a short C# example [here](https://docs.microsoft.com/en-us/azure/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-use-endpoint), but it's very well hidden.

**Comment by bryanjhogan** [comment]
Thanks for the tip. 

It doesn't look like I can raise an issue on the Microsoft/azure-docs repo.

**Comment by svick** [comment]
> It doesn't look like I can raise an issue on the Microsoft/azure-docs repo.

You're right. Sorry, I did not notice that. I'm not sure what is the right way to submit issues about it then. Maybe write a comment on an existing related article on the Azure Docs site?

**Comment by mairaw** [comment]
@kriscider any suggestions on how @bryanjhogan can submit this kind of request?

**Comment by mairaw** [comment]
@kriscrider any suggestions on how @bryanjhogan can submit this kind of request?

**Comment by mairaw** [comment]
This really doesn't belong in our repo so I'm closing this issue. @kriscider please let @bryanjhogan know how he can submit this kind of request to the Azure docs team.

**Comment by mairaw** [comment]
Had the wrong alias before. Meant to ping @kriscrider.
