### ISSUE TITLE
Should it say workspace?

### ISSUE THREAD

**Issue by zewditu** [dotnet/docs#21199]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/36615490/97033364-158ea380-1518-11eb-8da6-897c05fb9dfa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ea4120-abc4-10d8-826b-5d8e8acd8727
* Version Independent ID: d323c49a-77bd-46c1-4ab3-a95555dfe5a9
* Content: [Model Builder Azure Training Resources - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/azure-training-concepts-model-builder#what-is-an-azure-machine-learning-workspace)
* Content Source: [docs/machine-learning/resources/azure-training-concepts-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/azure-training-concepts-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Good catch @zewditu! Would you be interested in making the change to "compute"?
