### ISSUE TITLE
Changes to Nullable Reference Type Annotations in .NET 6.0

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/docs#21202]
## Changes to Nullable Reference Type Annotations in .NET 6.0

_**This issue represents a work-in-progress. All changes to nullability annotations in the .NET Libraries will be aggregated into this issue throughout the course of .NET 6.0.**_

Starting in .NET Core 3.0, we have been applying nullability annotations to the .NET Libraries; .NET 5.0 reached 94% coverage across the APIs. From the outset of this effort, [we anticipated that mistakes would be made](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/api-guidelines/nullability.md#breaking-change-guidance) in these annotations and fixes would need to be made. In .NET 6.0, we are updating some annotations that have been previously applied.

Some of these changes are considered breaking changes because they could lead to new build-time warnings--code referencing these APIs will need to be updated when migrating to .NET 6.0. Other changes that are not considered breaking are also documented here as referencing code may benefit from removing operators or pragmas that become unnecessary.

### Old behavior

The affected APIs had incorrect nullable reference type annotations and build warnings were either absent or incorrect.

### New behavior

New build warnings will be produced and incorrect build warnings will no longer be produced for the affected APIs.

### Reason for change

Through feedback and further testing, the nullable annotations for the affected APIs were determined to be inaccurate. The updated annotations now correctly represent the nullability contracts for the APIs.

### Recommended action

Update code calling these APIs to reflect the revised nullability contracts.

### Category

- Core .NET libraries

### Affected APIs

_(Unchecked items in the list have not yet been documented)_

#### dotnet/runtime#42918 [Breaking]

- [x] [System.ComponentModel.ISite.Container](https://docs.microsoft.com/dotnet/api/system.componentmodel.isite.container)

#### dotnet/runtime#43717 [Non-Breaking]

- [x] [System.Xml.Linq.XContainer.Add(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xcontainer.add#System_Xml_Linq_XContainer_Add_System_Object___)
- [x] [System.Xml.Linq.XContainer.AddFirst(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xcontainer.addfirst#System_Xml_Linq_XContainer_AddFirst_System_Object___)
- [x] [System.Xml.Linq.XContainer.ReplaceNodes(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xcontainer.replacenodes#System_Xml_Linq_XContainer_ReplaceNodes_System_Object___)
- [x] [System.Xml.Linq.XDocument(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xdocument.-ctor#System_Xml_Linq_XDocument__ctor_System_Object___)
- [x] [System.Xml.Linq.XDocument(XDeclaration, Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xdocument.-ctor#System_Xml_Linq_XDocument__ctor_System_Xml_Linq_XDeclaration_System_Object___)
- [x] [System.Xml.Linq.XElement(XName, Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xelement.-ctor#System_Xml_Linq_XElement__ctor_System_Xml_Linq_XName_System_Object___)
- [x] [System.Xml.Linq.XElement.ReplaceAll(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xelement.replaceall#System_Xml_Linq_XElement_ReplaceAll_System_Object___)
- [x] [System.Xml.Linq.XElement.ReplaceAttributes(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xelement.replaceattributes#System_Xml_Linq_XElement_ReplaceAttributes_System_Object___)
- [x] [System.Xml.Linq.XNode.AddAfterSelf(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xnode.addafterself#System_Xml_Linq_XNode_AddAfterSelf_System_Object___)
- [x] [System.Xml.Linq.XNode.AddBeforeSelf(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xnode.addbeforeself#System_Xml_Linq_XNode_AddBeforeSelf_System_Object___)
- [x] [System.Xml.Linq.XNode.ReplaceWith(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xnode.replacewith#System_Xml_Linq_XNode_ReplaceWith_System_Object___)
- [x] [System.Xml.Linq.XStreamingElement(XName, Object)](https://docs.microsoft.com/dotnet/api/system.xml.linq.xstreamingelement.-ctor#System_Xml_Linq_XStreamingElement__ctor_System_Xml_Linq_XName_System_Object_)
- [x] [System.Xml.Linq.XStreamingElement(XName, Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xstreamingelement.-ctor#System_Xml_Linq_XStreamingElement__ctor_System_Xml_Linq_XName_System_Object___)
- [x] [System.Xml.Linq.XStreamingElement.Add(Object[])](https://docs.microsoft.com/dotnet/api/system.xml.linq.xstreamingelement.add#System_Xml_Linq_XStreamingElement_Add_System_Object___)

#### dotnet/runtime#44880 [Non-Breaking]

- [x] [System.Net.Http.HttpClient.PatchAsync](https://docs.microsoft.com/dotnet/api/system.net.http.httpclient.patchasync)
- [x] [System.Net.Http.HttpClient.PostAsync](https://docs.microsoft.com/dotnet/api/system.net.http.httpclient.postasync)
- [x] [System.Net.Http.HttpClient.PutAsync](https://docs.microsoft.com/dotnet/api/system.net.http.httpclient.putasync)

#### dotnet/runtime#44844 [Non-Breaking]

- [x] [System.Linq.Expressions.MethodCallExpression.Update](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.methodcallexpression.update?view=net-5.0#System_Linq_Expressions_MethodCallExpression_Update_System_Linq_Expressions_Expression_System_Collections_Generic_IEnumerable_System_Linq_Expressions_Expression__)
- [x] [System.Linq.Expressions.Expression\<TDelegate\>.Update](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.update?view=net-5.0#System_Linq_Expressions_Expression_1_Update_System_Linq_Expressions_Expression_System_Collections_Generic_IEnumerable_System_Linq_Expressions_ParameterExpression__)

#### dotnet/runtime#44938 [Breaking]

- [x] [System.Data.IDataRecord.GetBytes](https://docs.microsoft.com/en-us/dotnet/api/system.data.idatarecord.getbytes?view=net-5.0#System_Data_IDataRecord_GetBytes_System_Int32_System_Int64_System_Byte___System_Int32_System_Int32_)
- [x] [System.Data.IDataRecord.GetChars](https://docs.microsoft.com/en-us/dotnet/api/system.data.idatarecord.getchars?view=net-5.0)
- [x] [System.Data.DataRecord.GetBytes](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatarecord.getbytes?view=net-5.0#System_Data_Common_DbDataRecord_GetBytes_System_Int32_System_Int64_System_Byte___System_Int32_System_Int32_)
- [x] [System.Data.DataRecord.GetChars](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatarecord.getchars?view=net-5.0)

#### dotnet/runtime#47402 [Non-Breaking]

- [x] [HttpListenerContext.AcceptWebSocketAsync](https://github.com/dotnet/runtime/pull/47402)

#### dotnet/runtime#47598 [Breaking]

- [x] [`[NotNullWhen(true)]` added to hundreds of arguments](https://github.com/dotnet/runtime/pull/47598)
- [x] [`[NotNullWhen(true)]` added to a few arguments in System.collections missed in the original change](https://github.com/dotnet/runtime/pull/52164)
- [x] [`[NotNullWhen(true)]` added to more arguments in System.Reflection missed in the original change](https://github.com/dotnet/runtime/pull/52162)
- [x] [`[NotNullWhen(true)]` added to a few arguments in CoreLib missed in the original change](https://github.com/dotnet/runtime/pull/52167)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
@buyaa-n @eiriktsarpalis Please don't check the boxes in the issue description when you edit it to add an API. That's how I mark whether I've documented them or not. Thanks!

**Comment by gewarren** [comment]
I'm going to close this issue now. If there are any more nullable reference type annotation changes for .NET 6, please open a new issue.

**Comment by jeffhandley** [comment]
#25957 was filed for an annotation change to System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider. Adding the link here for future reference.
