### ISSUE TITLE
Under create a class library, step 1c, where is the "configure your new project page" and the "project name box"? Using visual studio 2017

### ISSUE THREAD

**Issue by jr010014** [dotnet/docs#21201]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Create a .NET Standard class library using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The tutorial is written for VS 2019, as indicated in the [Prerequisites section](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio#prerequisites). We don't have a version of the tutorial for Visual Studio 2017, but  there's a [Visual Studio Code version of the same tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code).

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
