### ISSUE TITLE
Preprocessor directives lacks `#nullable` hyper link and its relative pages

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/docs#21212]
This page lists many preprocessor directives. However, `#nullable` is an exception. This page doesn't list `#nullable` page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716913e5-dbbe-bdb0-909a-4d8c2dc7be97
* Version Independent ID: 501be68d-5ad0-18d9-8958-54215bb57fc0
* Content: [C# preprocessor directives](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @SunnieShine 

We should add an entry here for `#nullable`, and link to the language reference article on nullable reference types.

I've added this to our backlog, and added the `up-for-grabs` label to this issue.

**Comment by SunnieShine** [comment]
Thank you.

**Comment by SunnieShine** [comment]
@BillWagner I found that the page has been added. Should I close this issue? :)

**Comment by BillWagner** [comment]
@SunnieShine 

> Should I close this issue?

Yes, please.
