### ISSUE TITLE
Service Fabric is not mentioned as an option - in the guidance for choosing Azure Compute.

### ISSUE THREAD

**Issue by ndebrass** [dotnet/docs#21218]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45be6d71-575d-5d8d-bcdc-b6885ddbb487
* Version Independent ID: 7c37b77a-63fc-4fb4-ae32-02ac9c09e1c8
* Content: [Choosing Azure compute platforms for container-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications#feedback)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @ndebrass , thank you for reaching out. 

This has been discussed in details in - https://github.com/dotnet/docs/issues/15055

So I am closing this as duplicate.
