### ISSUE TITLE
Where is the convert wpf .net fw 4.8 to wpf .net core document?

### ISSUE THREAD

**Issue by henrikmbach** [dotnet/docs#21213]
Like the convert asp.net fw to asp.net core document, how about making "convert wpf .net fw 4.8 to wpf .net core" document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577db847-e424-a9dc-ee2d-f2c6ddb54600
* Version Independent ID: 5fa219d8-0c9c-c758-c1ee-17cefd75ca24
* Content: [Port from .NET Framework to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/#per-project-steps)
* Content Source: [docs/core/porting/index.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/index.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
@henrikmbach Is this what you're looking for? https://docs.microsoft.com/en-us/dotnet/desktop/wpf/migration/convert-project-from-net-framework?view=netdesktop-5.0

**Comment by henrikmbach** [comment]
Yes, that would work I guess, so add a link to this document then.
