### ISSUE TITLE
"Index from end operator ^" section - maybe mistake in the example code

### ISSUE THREAD

**Issue by adam-zborovszky** [dotnet/docs#21219]
Maybe I misunderstood, but seems the end operator is in a wrong place in the given example:

- wrong
Index toFirst = ^word.Length;
char first = word[toFirst];

- good (?)
Index toFirst = word.Length;
char first = word[^toFirst];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@adam-zborovszky what makes you think so?

The doc says:

> For a sequence of length `length`, `^n` points to the element with offset `length - n` from the start of a sequence.

and then (after the example)

> In expression `^e`, the result of `e` must be implicitly convertible to `int`

So, in case of

```csharp
Index toFirst = ^word.Length;
```

`toFirst` would point to the element with the index of `word.Length - word.Length`, that is `0`, or the first element.

Meanwhile, the following code

```csharp
Index toFirst = word.Length;
char first = word[^toFirst];
```

doesn't compile and produces the following error: `error CS0029: Cannot implicitly convert type 'System.Index' to 'int'`

In short, the `^` operator expects an integer operand.

**Comment by adam-zborovszky** [comment]
I got it. Thanks!

**Comment by BillWagner** [comment]
Thanks @pkulikov @adam-zborovszky 

I'll close as an answered question.
