### ISSUE TITLE
MacOS fails to install libomp

### ISSUE THREAD

**Issue by willsam100** [dotnet/docs#21225]
Runnning `brew update && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f5b1ac99a7fba27c19cee0bc4f036775c889b359/Formula/libomp.rb && brew link libomp --force` fails with the error:

Error: Calling Installation of libomp from a GitHub commit URL is disabled! Use 'brew extract libomp' to stable tap on GitHub instead.

Homebrew 2.5.7-2-gc8fcd05
Homebrew/homebrew-core (git revision cba702; last commit 2020-10-26)
Homebrew/homebrew-cask (git revision 8de20; last commit 2020-10-26)

MacOS: 10.15.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f39c5a-b353-4a50-9719-06074465e800
* Version Independent ID: 6e8ac4b9-43a0-84d7-35d2-b9f1bc88a4d9
* Content: [Install extra ML.NET dependencies - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies)
* Content Source: [docs/machine-learning/how-to-guides/install-extra-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-extra-dependencies.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @willsam100 

Thanks for raising this issue. Could you also provide which version of MacOS and Homebrew you're using to run these commands.

**Comment by frostythecodeman** [comment]
> Runnning `brew update && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f5b1ac99a7fba27c19cee0bc4f036775c889b359/Formula/libomp.rb && brew link libomp --force` fails with the error:
> 
> Error: Calling Installation of libomp from a GitHub commit URL is disabled! Use 'brew extract libomp' to stable tap on GitHub instead.
> 
> Homebrew 2.5.7-2-gc8fcd05
> Homebrew/homebrew-core (git revision cba702; last commit 2020-10-26)
> Homebrew/homebrew-cask (git revision 8de20; last commit 2020-10-26)
> 
> MacOS: 10.15.7
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 91f39c5a-b353-4a50-9719-06074465e800
> * Version Independent ID: 6e8ac4b9-43a0-84d7-35d2-b9f1bc88a4d9
> * Content: [Install extra ML.NET dependencies - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies)
> * Content Source: [docs/machine-learning/how-to-guides/install-extra-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-extra-dependencies.md)
> * Product: **dotnet-ml**
> * GitHub Login: @natke
> * Microsoft Alias: **nakersha**

Hi @willsam100 , did you ever resolve this issue? I am having the exact problem.

**Comment by luisquintanilla** [comment]
@frostythecodeman there's an issue open in the ML .NET Repo. Can you please upvote it and provide additional details about your system (OS version, etc)

https://github.com/dotnet/machinelearning/issues/5615

Thanks

**Comment by luisquintanilla** [comment]
@frostythecodeman ignore my previous comment :) I see you already posted on there.

**Comment by ksaur** [comment]
@frostythecodeman , as a work-around, you can do:
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/fb8323f2b170bd4ae97e1bac9bf3e2983af3fdb0/Formula/libomp.rb
brew install ./libomp.rb
```

See https://github.com/microsoft/hummingbird/pull/500
