### ISSUE TITLE
Records described as "immutable by default" when they are not

### ISSUE THREAD

**Issue by jbogard** [dotnet/docs#21224]
Only certain usages of the `record` syntax provide "immutable by default". However, it is possible (and quite easy) to create a mutable record type:

```csharp
public record Person
{
    public string LastName { get; set; }
    public string FirstName { get; set; }
}

var person = new Person { FirstName = "Jimmy", LastName = "Bogard" };
person.LastName = "Fallon";
```

This all compiles and runs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @jbogard 

As I add more tutorial content on records, more of the examples will reinforce your point. I'll update this in the same way before the release.
