### ISSUE TITLE
dotnet new page is missing blazorwasm settings

### ISSUE THREAD

**Issue by marin-bratanov** [dotnet/docs#21220]
There is a section about the `blazorserver` template, but none about the `blazorwasm` template. For example, the `--hosted` flag that generates the ASP.NET Core server for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by tdykstra** [comment]
This is now documented here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazorwasm

**Comment by marin-bratanov** [comment]
Thank you!
