### ISSUE TITLE
Add a note about string normalization before match it with @"\p{IsCombiningDiacriticalMarks}"

### ISSUE THREAD

**Issue by brud** [dotnet/docs#21237]
I think it would be a good idea to add a note about normalization the string to D form before matching it with `@"\p {IsCombiningDiacriticalMarks}"` - it could save a ton of time for newbies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! Can you provide more information about what you want added and where? I'm not too familiar with the article but I don't see any mention of normalizing strings and only a few references to `IsCombiningDiacriticalMarks` so I don't really understand the scenario too much.

Or, perhaps you can click the edit button on the article and submit a proposal directly?

Cheers!

**Comment by brud** [comment]
Hello, @adegeo 
This little code snippet shows what I'm mean https://dotnetfiddle.net/oeclH6

My English not so good - I'm afraid that my proposal can be messy, sorry about that :)

**Comment by adegeo** [comment]
Went back through this. This article doesn't really have a good place for this because we don't talk about `\p{IsCombiningDiacriticalMarks}` directly. Instead, I'm going to add a note where the check `\p` is talked about that mentions using Normalize to improve matching.
