### ISSUE TITLE
Async service initialization

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#21231]
Hi,

Please document what's the proper pattern to register a service that require asynchronous initialization, after it's resolved, but before it's actually provided.

---
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd55089-b683-2202-6641-c7b61a132f14
* Version Independent ID: cc5f00d0-fb50-1229-8fa2-e66b1f45b284
* Content: [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
* Content Source: [docs/core/extensions/dependency-injection.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/dependency-injection.md)
* Product: **dotnet-core**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Closing this, as it is out of scope and more a of product question (which has already been addressed).
