### ISSUE TITLE
Key Vault FlexVolume is deprecated

### ISSUE THREAD

**Issue by karoldeland** [dotnet/docs#21244]
In the page below, there's a reference to Key Vault FlexVolume. This project is deprecated. We should now look at https://github.com/Azure/secrets-store-csi-driver-provider-azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22af16e4-3f97-9d4f-d95b-57fe152493b5
* Version Independent ID: 1c2ac810-3d67-614e-de7d-a050949642a3
* Content: [Centralized configuration](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/centralized-configuration)
* Content Source: [docs/architecture/cloud-native/centralized-configuration.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/centralized-configuration.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @karoldeland, thank you for pointing it out. Will submit a PR to update the doc.

**Comment by sughosneo** [comment]
Hi @karoldeland  , just checking if you had a chance to look into this further. Thank you.

**Comment by karoldeland** [comment]
My bad. Just forgot. Added to my to do.
