### ISSUE TITLE
One AKS cluster by application?

### ISSUE THREAD

**Issue by karoldeland** [dotnet/docs#21243]
[Enter feedback here]
In the Container orchestration and clustering section, it's stated :
_The application will deploy separate AKS clusters for each microservice shown in the architecture diagram above_

Is it a good choice? IMHO, Kubernetes should be used to densify our infrastructure, not to create a cluster by application. 

May be it's a demo kind of concern?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7531d0c3-789a-ebb9-a77f-38a5b227d7c6
* Version Independent ID: f2ff1005-cadf-68c9-f825-9780de3e9e84
* Content: [Mapping eShopOnContainers to Azure Services](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/map-eshoponcontainers-azure-services)
* Content Source: [docs/architecture/cloud-native/map-eshoponcontainers-azure-services.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/map-eshoponcontainers-azure-services.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by karoldeland** [comment]
Actually, I think the text is misleading since only one AKS cluster is required...

**Comment by sughosneo** [comment]
Hi @karoldeland , thank you for reaching out.

Actually, it depends on the workload, which each microservice has to handle within your application.
This article talks about the possibility of optimum scalability to keep each microservice in a separate AKS cluster. Yes, that's possible and many production scenarios run on the multi-cluster model. In a multi-cluster model each microservice has it's own local resources. That gives many flexibilities over the period of time. For e.g : If you want to make any update one of the microservice environment that will not affect others. Also, this approach allows each individual service to scale independently according to its resource demands. But this approach is subjected to application design, architecture, workload and scalability like many other factors. You can always start with one AKS cluster and slowly move towards multi-cluster models as your application grows.

Hope this helps !

**Comment by karoldeland** [comment]
Honestly, it's not the feeling I got from the industry. Maybe it's true for Microsoft customers (since you won't pay for master nodes), but we tend to keep the number of cluster as low as possible. I don't think that targetting one cluster by app or even by microservice is a goal. It sounds more like an anti-pattern right now...

**Comment by nishanil** [comment]
@karoldeland Thanks for pointing it out. You're right. In this context, we deploy eShop only to a single AKS cluster. 
@sughosneo Let's fix that statement.
