### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by pchinnala** [dotnet/docs#21246]
[Enter feedback here]

The link to download the sample isn't working, gives me 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d763531-9d4a-d48a-2830-ce97b8dbbd60
* Version Independent ID: d8131781-1f1c-0baf-964b-47f0d54b8039
* Content: [Basic Serialization Technology Sample](https://docs.microsoft.com/en-us/dotnet/standard/serialization/basic-serialization-technology-sample)
* Content Source: [docs/standard/serialization/basic-serialization-technology-sample.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/basic-serialization-technology-sample.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, we'll investigate.

**Comment by tdykstra** [comment]
Sorry, but the article and sample no longer exist.  The article link now redirects to the [overview article](https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-and-soap-serialization). This part of the table of contents does still have other [examples](https://docs.microsoft.com/en-us/dotnet/standard/serialization/examples-of-xml-serialization).
