### ISSUE TITLE
variable naming

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#21256]
nothing [I could see] on how to name a variable (e.g. from alphabet [A-Za-z0-9._$] and must start with letter), i.e. syntax rules and recommendations. basic stuff missing methinks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6444d2e-78cc-2bdb-f950-9a3692bcabd0
* Version Independent ID: 5523f31c-db90-b73c-a5b0-ddcc9b10cab3
* Content: [Variables - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/variables)
* Content Source: [spec/variables.md](https://github.com/dotnet/csharplang/blob/master/spec/variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
You're probably looking for the [identifiers](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers) section?

**Comment by BillWagner** [comment]
Thanks @DickBaker @pkulikov 

The rules for any identifier (variable, class, etc) are in the identifiers section.

I'll close this as an answered question.
