### ISSUE TITLE
Directory.EnumerateFiles three-character paterns

### ISSUE THREAD

**Issue by nanangp** [dotnet/docs#21253]
**Issue description**

The doc currently mentions the following information for search patterns:
> If the specified extension is exactly three characters long, the method returns files with extensions that begin with the specified extension. For example, "*.xls" returns both "book.xls" and "book.xlsx".

Based on investigations in [this StackOverflow question](https://stackoverflow.com/q/64564664/5623232), there are a number of issues with this statement, depending on whether you're on Core or Framework.

- Core: The statement should not be applicable. The pattern matcher would match `*.xls` exactly as-is and would **not** return `.xlsx` files.
- Framework: The statement holds true for local dirs, but **not on remote dirs**, accessed either via *\\server\dir* or a *mapped drive* on Windows.

**Target framework**

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

**Comment by gewarren** [comment]
This regards https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles. I'll move it to the API docs repo.

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5082
