### ISSUE TITLE
Links to sample code references are missing.

### ISSUE THREAD

**Issue by laultman** [dotnet/docs#21255]
You specifically refer to samples containing necessary code but no links are provided.
...such as the classes in the sample code, like 'BasketService', 'CatalogService', 'OrderingService', etc
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @laultman, thank you for reaching out. 

The detailed code for the reference application `eShopOnContainers` can be found in [here](https://github.com/dotnet-architecture/eShopOnContainers)
You will be able to see all the services under the `src\Services` directory. 

Hope this helps !

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.

Thank you.
