### ISSUE TITLE
CUDA version is out of date

### ISSUE THREAD

**Issue by frogcrush** [dotnet/docs#21251]
Version 1.5.2 of ML.NET requires CUDA 10.1 with cuDNN 7.6.5 for that version in order to work now. 

This page is also out of date: https://github.com/dotnet/machinelearning/blob/master/docs/api-reference/tensorflow-usage.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @frogcrush 

Thanks for raising this issue. Does working with the older versions of these libraries throw an error or just warnings?

**Comment by frogcrush** [comment]
It throws errors and won't work with the older versions.

**Comment by luisquintanilla** [comment]
Thanks for that clarification.

**Comment by luisquintanilla** [comment]
Stale issue fixed by #23718 & dotnet/machinelearning#5594

Thanks @frogcrush
