### ISSUE TITLE
Clarify Windows only note

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/docs#21297]
This note should clarify that it refers to Windows only. Ideally, also add the same info for Linux/OSX:

"The string behavior of the file system, registry keys and values, and environment variables is best represented by StringComparison.OrdinalIgnoreCase."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dead2df6-1ec5-b55c-89aa-d05a7a75a0eb
* Version Independent ID: fe538551-dcfc-c244-3f16-864d3f6c2a6e
* Content: [Best Practices for Using Strings in .NET](https://docs.microsoft.com/en-gb/dotnet/standard/base-types/best-practices-strings)
* Content Source: [docs/standard/base-types/best-practices-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/best-practices-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I'm not sure the note is even worth having there. Considering there is a table below with guidance on which string compare to use in a specific scenario, the note seems pointless. I opt to remove the note.

Thoughts?

**Comment by KristianWedberg** [comment]
Yes, removing the note seems even better.
