### ISSUE TITLE
Could mention CER-related methods that are not obsolete in .NET 5

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#21319]
It might be useful to explicitly mention that the [RuntimeHelpers.PrepareDelegate](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.preparedelegate?view=net-5.0) and [RuntimeHelpers.PrepareMethod](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.runtimehelpers.preparemethod?view=net-5.0) methods are not obsolete in .NET 5 and do not trigger warning SYSLIB0004, even though they were intended to use with Constrained Execution Regions. I believe they no longer walk the static call graph, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6894baef-cb6d-5dfe-3fe2-ebcc27f23e52
* Version Independent ID: caf1ce30-aa2b-1e08-a4fc-8ff4a74e992b
* Content: [SYSLIB0004 warning - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/syslib0004)
* Content Source: [docs/core/compatibility/syslib0004.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/syslib0004.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jeffhandley Do you think the non-obsolete methods should be mentioned in this article?

**Comment by jeffhandley** [comment]
> @jeffhandley Do you think the non-obsolete methods should be mentioned in this article?

Yeah, I think there's merit in that idea as our blanket statement about CER could be misleading for those exceptions. Thanks for the suggestion, @KalleOlaviNiemitalo.
