### ISSUE TITLE
Use of WebRequest is no longer preferred

### ISSUE THREAD

**Issue by jeffputz** [dotnet/docs#21315]
I imagine that this section of documentation is outdated, as it's uncommon to use `WebRequest` compared to `HttpClient`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b6dcee-481a-ad51-951f-c49b8f55d104
* Version Independent ID: 61bbc288-072e-0d82-e82e-e059cea44bd9
* Content: [How to: Set Cache Policy for a Request](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-set-cache-policy-for-a-request)
* Content Source: [docs/framework/network-programming/how-to-set-cache-policy-for-a-request.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-set-cache-policy-for-a-request.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

Related to #13253
Related to #11759
