### ISSUE TITLE
False positive for CA1508

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/docs#21331]
```cs
if (lessonInfo.Settings.Hiding.EventTypesToHide.Count == 0 &&
    lessonInfo.Settings.Hiding.TeachersToHide.Count == 0)
{
    return true;
}
```
Where `TeachersToHide` and `EventTypesToHide` are both `List<long>`

![image](https://user-images.githubusercontent.com/6609929/98042060-90669100-1e2b-11eb-93c9-af4613bb9313.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44bae70d-365f-c01d-acae-7d7ae9c0ef03
* Version Independent ID: 1fd1a3b5-e990-2644-f12c-2f4a06e053c3
* Content: [CA1508: Avoid dead conditional code (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1508.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1508.md)
* Product: **dotnet**
* GitHub Login: @mavasani
* Microsoft Alias: **mavasani**

**Comment by Youssef1313** [comment]
This needs to be moved to dotnet/roslyn-analyzers repository.

**Comment by gewarren** [comment]
This issue was moved to dotnet/roslyn-analyzers#4408
