### ISSUE TITLE
NETSDK1073	The FrameworkReference 'Microsoft.NETCore.App' was not recognized

### ISSUE THREAD

**Issue by MoneefRaonah** [dotnet/docs#21330]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c33d61d-2a57-a6f9-d634-b4840c137ee4
* Version Independent ID: 87c828ac-4124-6915-e1e4-0cb1d7bbd518
* Content: [NETSDK1073: The FrameworkReference was not recognized - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1073?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1073)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1073.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/sdk-errors/netsdk1073.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @marcpopMSFT
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
@MoneefRaonah Can you provide more info about the documentation issue?
