### ISSUE TITLE
Typo in lambda discard documentation

### ISSUE THREAD

**Issue by JoeMarkov** [dotnet/docs#21349]
It says under Lambda discards

Beginning with C# 9.0, you can use discards to specify **two or more** input parameters of a lambda expression that aren't used in the **expression:

Should it not be one or more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#input-parameters-of-a-lambda-expression)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
The current wording is correct, please check the note at the end of the section. You can use it for one, but it wouldn't be discarded, as it would still be possible to use `_` in the lambdas body

**Comment by BillWagner** [comment]
Thanks for noting this @JoeMarkov 

The comment by @pkulikov is correct, as is this article. A single `_` is a valid identifier when used as a parameter to a method or lambda expression. The `_` can be used for two or more parameter names, which instructs the compiler to view it as a discard.

I'll close this.
