### ISSUE TITLE
I have no other way to reach the person to give my thanks about their writing style. 

### ISSUE THREAD

**Issue by george-tsiros** [dotnet/docs#21354]
Who wrote this page? It is such a joy to read it. I wish all documentation were like this. Thank you, thank you so much. I can't help myself reading even about features that i am confident i won't be needing. 

"The compiler does enforce the rule that readonly members don't modify state."

A thing of beauty.
Simple: every single word has a purpose. 
Straightforward: It's immediately understood what this sentence is about.
Assertive: it uses assertions instead of negations as much as possible without going too far and making it convoluted ("the compiler doesn't ignore the rule ..."
Definitive: The information about who does what is complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you very much. 🙇‍♂️ 

I'll close as kudos
