### ISSUE TITLE
setx may truncate env variables longer then 1024 characters, this may be not so difficult for PATH variable

### ISSUE THREAD

**Issue by twiernik** [dotnet/docs#21353]
Hello, step in which environment variables are set is not so ideal. In my case PATH was shortened to 1024 characters. Side effect of that is some paths were removed :( it seems that windowed editor works fine with combined path longer then 1024 chars.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1dc518-dfe4-b71a-ee04-e8520bbd2f67
* Version Independent ID: e04b082c-e52b-3ffb-c69d-10da5dc54528
* Content: [Get started with .NET for Apache Spark](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started?tabs=windows)
* Content Source: [docs/spark/tutorials/get-started.md](https://github.com/dotnet/docs/blob/master/docs/spark/tutorials/get-started.md)
* Product: **dotnet-spark**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by gewarren** [comment]
We're no longer updating the .NET for Apache Spark documentation, and have archived it to https://learn.microsoft.com/previous-versions/dotnet/spark/what-is-spark. As a result, we're closing all the active .NET for Apache Spark issues. I'm sorry we couldn't address your issue.
