### ISSUE TITLE
.NET 5 support .NET Standard 2.1 and earlier

### ISSUE THREAD

**Issue by OzBob** [dotnet/docs#21361]
Suggestion: include information from:

From: https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

@Immo says:
"We won’t be releasing a new version of .NET Standard, but .NET 5 and all future versions will continue to support .NET Standard 2.1 and earlier. "

Also, could the article be updated to include a reference to .Net Core 3.1 support for .NET Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
[This section](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#when-to-target-net50-vs-netstandard) already mentions that .NET 5 implements .NET Standard 2.1.

**Comment by OzBob** [comment]
thanks! @gewarren
