### ISSUE TITLE
JsonSerializer.Parse<DataTable> failed

### ISSUE THREAD

**Issue by xcaptain** [dotnet/docs#21366]
Convert an object into json string and then convert into DataTable is an easy way to generate `DataTable`, but this approach fails in `dotnet core 3 preview5`

I have created a working dotnet core 2 code snippet at [https://dotnetfiddle.net/cD6NFD](https://dotnetfiddle.net/cD6NFD)

dotnetfiddle doesn't support dotnet core 3 yet, so my dotnet core 3 code example see below:

```csharp
using System.Data;
using System.Text.Json.Serialization;

public class UserDetails
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
}

List<UserDetails> persons = new List<UserDetails>()
{
    new UserDetails() {Id="1001", Name="ABCD", City ="City1", Country="USA"},
    new UserDetails() {Id="1002", Name="PQRS", City ="City2", Country="INDIA"},
    new UserDetails() {Id="1003", Name="XYZZ", City ="City3", Country="CHINA"},
    new UserDetails() {Id="1004", Name="LMNO", City ="City4", Country="UK"},
};
var table = JsonSerializer.Parse<DataTable>(JsonSerializer.ToString(persons));
```

below are the error log:
```
CLR/System.Text.Json.JsonReaderException 'The JSON value from [System.Data.DataTable] could not be converted to System.Object.'
```

**Comment by MelbourneDeveloper** [comment]
> We recently published guidance against (de)serializing the DataSet and DataTable types from untrusted input. In keeping with JsonSerializer's emphasis on security, we'll throw a clear NotSupportedException for these types, similar to the behavior for System.Type.

@layomia is there no option to simply ignore unsafe types? If not, isn't that a bug?

**Comment by MelbourneDeveloper** [comment]
How do we hook in to the processor so that we can just ignore these types?

**Comment by XtremeOwnageDotCom** [comment]
To confirm, this is still indeed an issue.... .net 5's system.text.json still cannot handle a datatable.

**Comment by steveharter** [comment]
STJ will treat any unknown type that does not implement `IEnumerable` as a POCO, meaning all public properties will be (de)serialized and the default constructor called. For types where that is not compatible, you can configure a custom converter to throw.

Here's an example:
```cs
  class Program
  {
      static void Main(string[] args)
      {
          JsonSerializerOptions options = new();
          options.Converters.Add(new UnsupportedConverter<DataTable>());


          DataTable dt = JsonSerializer.Deserialize<DataTable>("{}", options); // throws NotSupportedException
      }
  }


  internal class UnsupportedConverter<T> : JsonConverter<T>
  {
      public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
      {
          throw new NotSupportedException($"{typeof(T)} does not support deserialization.");
      }

      public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
      {
          throw new NotSupportedException($"{typeof(T)} does not support serialization.");
      }
  }
```

**Comment by Seabizkit** [comment]
I quite disappointed... could someone give me the implementation for doing this.
like this is closed... but no work around nothing? .net8 has been release and we STILL do not have Table sterilize and desterilize?

its 2023, newtonsoft has this for like how long?

cant even find a DataTableJsonConverter : JsonConverter<DataTable>

which works.. quite sad

**Comment by Transis-Felipe** [comment]
Same here. 
It will not be included in .net9 ?

**Comment by XtremeOwnageDotCom** [comment]
Whew, this issue started in NET CORE 3.0, and has now reached .NET 9 !

**Comment by Jimex** [comment]
> Whew, this issue started in NET CORE 3.0, and has now reached .NET 9 !

Typical Microsoft style; if you look at the WinUI3 UI designer posts, you will see the worse.
