### ISSUE TITLE
Wrong Direction Adjective?

### ISSUE THREAD

**Issue by JediSQL** [dotnet/docs#21368]
In the "Minimum version" section near the top, should the first paragraph end with "... for that version from the **following** table."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed?redirectedfrom=MSDN&source=docs)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@JediSQL Thanks for pointing that out. Technically the "previous table" was correct, but I think that text was put in place before the table in the section itself was added, so it was confusing.

**Comment by JediSQL** [comment]
Thank you!
