### ISSUE TITLE
Array is missing implemented interfaces

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2136]
[The API reference page for `Array`](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netframework-4.7) lists its implemented interfaces as: `ICloneable`, `IList`, `IStructuralComparable` and `IStructuralEquatable`.

But that is not all, [as MSDN shows](https://msdn.microsoft.com/en-us/library/system.array(v=vs.110).aspx), `Array` also implements `ICollection` and `IEnumerable`.

I'm assuming that this is an issue with whatever tool is used to generate the XMLs and that a PR fixing this is not the right approach. If I'm mistaken about that, I can submit that PR.

**Comment by rpetrusha** [comment]
Thanks for discovering this issue, @svick. Yes, this is a general reflection issue that applies to additional types, so it can't be fixed with a PR. I haven't looked systematically, but it also applies to List<T> as well -- the same two interfaces are listed on MSDN but not on docs.microsoft.com. I've opened internal CSI bug #996154 to track this issue.

**Comment by dend** [comment]
This is by-design and reflects the .NET model where interface implementations are "collapsed". In this case, if one interface already implements another interface, only the one highest in the chain will be displayed as you only need it to implement both.

**Comment by svick** [comment]
@dend That rule doesn't seem to be followed universally. E.g. the implemented interfaces for [`List<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1) are collapsed only partially:

* `ICollection<T>`, `IEnumerable<T>` and `IList<T>` are all shown, when they could be collapsed to just `IList<T>`.
* `ICollection` and `IEnumerable` are not shown, presumably they are both collapsed into `IList`.

Personally, I think interfaces should not be collapsed. If I'm trying to find out whether a type implements a certain interface, I shouldn't have to go through all of its shown interfaces to find out whether one of them implies indirectly implementing it.

**Comment by mairaw** [comment]
@dend I'm reopening this since we wither collapse them all or we don't. My personal preference would also be to show them all.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/223
