### ISSUE TITLE
Sample in "Use dependency injection in .NET" does not seem to be working

### ISSUE THREAD

**Issue by KnightmareRIP** [dotnet/docs#21378]
I just went though the "Use Dependency Injection in .NET". I also created a console project and copied the code on the page. When I ran it, I got a different result than expected. All the GUID's displayed were all new. As if everything was treated as transient... even the one declare as a singleton.

I reviewed the code and based on what I've learned, the code looks good. So, I am not sure why the scope and singleton classes are treated as transient.

The code is exactly as it is here:

https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage

If anyone has any idea why it's not working as expected, please enlighten me.

Thanx in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-core**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @KnightmareRIP,

The GUIDs will be different with every single execution of this application. The `Guid.NewGuid()` is actually designed to do just that, create a new globally unique identifier. I just ran the code again, and got this:

```
Scope 1-Call 1 .GetRequiredService<OperationLogger>(): ITransientOperation [ c92a...Always different        ]
Scope 1-Call 1 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 5aed...Changes only with scope ]
Scope 1-Call 1 .GetRequiredService<OperationLogger>(): ISingletonOperation [ adc8...Always the same         ]
...
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): ITransientOperation [ ce7c...Always different        ]
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 5aed...Changes only with scope ]
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): ISingletonOperation [ adc8...Always the same         ]

Scope 2-Call 1 .GetRequiredService<OperationLogger>(): ITransientOperation [ 1588...Always different        ]
Scope 2-Call 1 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 376b...Changes only with scope ]
Scope 2-Call 1 .GetRequiredService<OperationLogger>(): ISingletonOperation [ adc8...Always the same         ]
...
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): ITransientOperation [ 9175...Always different        ]
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 376b...Changes only with scope ]
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): ISingletonOperation [ adc8...Always the same         ]
```

Each of the output lines represents an operation given a specific lifetime. Could you please share your output so that I could look through it, and verify the concern?

**Comment by KnightmareRIP** [comment]
This is what I get when I run my code. Notice that the Scoped and Singletons are always different. Do you have your project uploaded anywhere? I'd like to pull it and run it locally to see if I get the same results as you... or as mine. 

Scope 1-Call 1 .GetRequiredService<OperationLogger>(): ITransientOperation [ d763...Always different        ]
Scope 1-Call 1 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 53c7...Changes only with scope ]
Scope 1-Call 1 .GetRequiredService<OperationLogger>(): ISingletonOperation [ 1393...Always the same         ]
...
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): ITransientOperation [ 88fd...Always different        ]
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 4765...Changes only with scope ]
Scope 1-Call 2 .GetRequiredService<OperationLogger>(): ISingletonOperation [ 4a3e...Always the same         ]

Scope 2-Call 1 .GetRequiredService<OperationLogger>(): ITransientOperation [ 09a9...Always different        ]
Scope 2-Call 1 .GetRequiredService<OperationLogger>(): IScopedOperation    [ 4d15...Changes only with scope ]
Scope 2-Call 1 .GetRequiredService<OperationLogger>(): ISingletonOperation [ 60c7...Always the same         ]
...
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): ITransientOperation [ 79de...Always different        ]
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): IScopedOperation    [ e158...Changes only with scope ]
Scope 2-Call 2 .GetRequiredService<OperationLogger>(): ISingletonOperation [ 6d98...Always the same         ]

**Comment by KnightmareRIP** [comment]
I found out what I did wrong. Instead of...

        public string OperationId { get; } = NewGuid().ToString()[^4..];

I typed in...

        public string OperationId => NewGuid().ToString()[^4..];

I updated my code to use the first code above and it worked. Not sure why these two would behave differently.

**Comment by KnightmareRIP** [comment]
Boink! The coffee kicked in and I now understand why.

public string OperationId { get; } = NewGuid().ToString()[^4..];

This code assigns the GUID value once and is the same on each read while...

public string OperationId => NewGuid().ToString()[^4..];

Generates a new ID each time it is called.


Thanx again!

Martin
