### ISSUE TITLE
What Happs in an Async method image is using C#

### ISSUE THREAD

**Issue by shawnweisfeld** [dotnet/docs#21388]
What Happs in an Async method image is using C#, this is the VB programming guide. . . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a9a526-9135-db6b-f84b-ae52ab0876c4
* Version Independent ID: 550522d6-32ca-b8ba-7c37-5ad054102f0a
* Content: [Asynchronous Programming with Async and Await - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)
* Content Source: [docs/visual-basic/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/async/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by tdykstra** [comment]
Thanks for the comment. The code in that section is an image, not a code snippet, and we don’t have the resources to create a VB-specific version of it. cc @KathleenDollard for confirmation.
