### ISSUE TITLE
Permutations of a string using range indicators

### ISSUE THREAD

**Issue by hgeissler** [dotnet/docs#21384]
I found a very compact way to generate all permutations of a given string:  
```
    class Program
    {
        static void Main(string[] args)
        {
            myPerm("abcd", 0);
        }

        private static void myPerm(string str, int index)
        {
            if (index == str.Length)
            {
                Console.WriteLine(str);
            }

            for (int i = index; i < str.Length; i++)
            {

                char prefix = str[i];
                string suffix = str[0..i] + str[(i + 1)..];

                myPerm(prefix + suffix, index + 1);
            }
        }
    }
```
Maybe it can be used as a powerful example.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Here is the [sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHjAAlUwHY8BvPQm4zANmIBZCBZAQwEsoAKEgBgDaAXULswAcwDOASmq0quWssIB1MJ2ABTAIIAbPQAUtYALYRg7YJwD2UKT3HSAdABktUCcAAWhALx+hJiEAPxiklKC/KIghABE7ABGAMZxMIT8MgDc8jQAvni5dIyoLOqaugbGZhZWtvZ8mPyEUsBg6dzAhNxwWgAeckoKRcqcAGaEPD39/oGtYG4eXt6DKsNDa8okAJw889kjtAX4GypjNmCTnd3+3VC9fVk3ADwtbYuePk+IiN2rm4pNipkt5xIQAA5gLRjTh9W7zQScYQ5U5AgQtCBjGFwwIAEjiFAR/GcziReUJbUEU0Iv0wMhJwjycRRhzW5W0+iMJnMlmsdgc+IokOhsPJUkx2KZHXuM1pB1RRyKxzyQA===) of this example.

**Comment by hgeissler** [comment]
Very interesting. Thank you
