### ISSUE TITLE
Incorrect description of new keyword meaning

### ISSUE THREAD

**Issue by rahul-deshmukhpatil** [dotnet/docs#21381]
In the below sentence,

The new modifier can be used to explicitly indicate that the member isn't intended to be an override of the base member. 

the word "isn't" should be is as new is intended to show that it's overriding the  base class method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f703413-8141-ed2a-74b3-6eb59b1e3588
* Version Independent ID: 5ae737e7-6628-b7de-4293-e778db0fecbf
* Content: [new modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier)
* Content Source: [docs/csharp/language-reference/keywords/new-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/new-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @rahul-deshmukhpatil 

The article is correct. Adding `new` to a method doesn't *override* a method in the base class. Instead, it *hides* it. I'll close this as an answered question.
