### ISSUE TITLE
Method naming style

### ISSUE THREAD

**Issue by pi3k14** [dotnet/docs#21412]
It seems like default naming style for class methods is Pascal Case, it should be mentioned here https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#default-naming-styles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfcd87a-a475-5fcf-2344-2b3a706a4b6d
* Version Independent ID: 95aa3bbf-7621-2064-f9d0-55105d55ee7e
* Content: [Code style naming rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/naming-rules.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/naming-rules.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Hi! 

@pi3k14 I see it mentioned there. Unless I'm not understanding your request. 😄

**Comment by pi3k14** [comment]
> For classes, structs, enumerations, properties, and events with public, private, internal, protected, or protected_internal accessibility, the default naming style is Pascal case.

Where do you read method?

**Comment by adegeo** [comment]
I must have been looking at something else.. I'll fix this.
