### ISSUE TITLE
Add Examples about how to use -s|--solution-folder option

### ISSUE THREAD

**Issue by Leanwit** [dotnet/docs#21413]
I am working on automatizing some boilerplate tasks and I realized that there are no examples of how to use --solution-folder option in the example's section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@wli3 What would be a good example scenario for --solution-folder?  When I try to use it, it doesn't seem to have any effect.

**Comment by Leanwit** [comment]
Just in case, my scenario was wanting to create a project into an src folder, and create the solution folder to generate the same structure. So I used the following command to generate it:

- dotnet new classlib -n 'csharp-booking-01_base' -o 'csharp-booking-01_base/src' --framework netcoreapp3.1
- dotnet sln csharp.sln add csharp-booking-01_base/src/csharp-booking-01_base.csproj -s 'csharp-booking-01_base/src'

The final structure is:
csharp
	csharp.sln
	csharp-booking-01_base/ 
		src/
		        csharp-booking-01_base.csproj

where csharp-booking-01_base and src are solution folders. 
Hope this helps.

**Comment by wli3** [comment]
@tdykstra agree with @Leanwit that's what I use it for
