### ISSUE TITLE
Unable to resolve system.net.http dependency after migrating 4.7 to 4.8

### ISSUE THREAD

**Issue by TrishalaPatne** [dotnet/docs#21472]
[Enter feedback here]

Hello Team,
I am working on VSTO addin  application. I migrated my project from .netframework 4.7 to 4.8. I am getting error as "Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
---"

Can you please guide me how i can resolve this error?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338c00ae-f1e7-9b2c-0c96-5ced2f3e22d7
* Version Independent ID: 4777b23c-4c46-1aa9-50ab-43a11f0fcca9
* Content: [Runtime Changes for Migration from .NET Framework 4.7 to 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.7-4.8)
* Content Source: [docs/framework/migration-guide/runtime/4.7-4.8.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/runtime/4.7-4.8.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Hello! I'm going through some of our old issues, sorry for the delay. I don't think we can easily answer your question. If you discovered a fix for your problem, please let us know how we can update the documentation to help anyone else who runs into this issue.

Doing a few searches I found this https://social.msdn.microsoft.com/Forums/en-US/d3ba0707-e531-43a7-bc96-21578501a9d1/problem-of-systemnethttp-of-net-framework-48

Maybe using the `System.Net.Http` NuGet package would help? You may have better luck asking on a forum such as StackOverflow.

Sorry we can't be more help. I'm going to close the issue. 

Thanks.
