### ISSUE TITLE
"straight forward" should be replaced with "straightforward"

### ISSUE THREAD

**Issue by DanRosenfeld** [dotnet/docs#21474]
In the following sentence

_"Porting to .NET Core (or .NET Standard) from .NET Framework for many projects is relatively straight forward"_

"straight forward" should be replaced with "straightforward"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577db847-e424-a9dc-ee2d-f2c6ddb54600
* Version Independent ID: 5fa219d8-0c9c-c758-c1ee-17cefd75ca24
* Content: [Port from .NET Framework to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/)
* Content Source: [docs/core/porting/index.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/index.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Fixed in https://github.com/dotnet/docs/pull/21475
