### ISSUE TITLE
Element should be named "root" lower case

### ISSUE THREAD

**Issue by EFraim** [dotnet/docs#21486]
[Enter feedback here]
If you assemble a tree which will be serialized into JSON then the root element has to be in lower case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022e92cc-5f93-59dd-aee8-fb8cdc7a3ea0
* Version Independent ID: 503c13da-e77d-fcac-e545-6dbf0a9cf3d2
* Content: [Add elements, attributes, and nodes to an XML tree - LINQ to XML](https://docs.microsoft.com/en-us/dotnet/standard/linq/add-elements-attributes-nodes-xml-tree)
* Content Source: [docs/standard/linq/add-elements-attributes-nodes-xml-tree.md](https://github.com/dotnet/docs/blob/master/docs/standard/linq/add-elements-attributes-nodes-xml-tree.md)
* Product: **dotnet**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
@EFraim Hello. I don't understand what you mean exactly, this article is about XML objects, not JSON objects.

**Comment by EFraim** [comment]
@adegeo At least notionally the XElement and friends are used by the standard Json reader and writer factory.

**Comment by adegeo** [comment]
@efraim do you have an example of it failing? I've never heard of a lowercase requirement.
