### ISSUE TITLE
"Publish a single file app - Visual Studio" implies that self-contained is required

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#21489]
The "Publish a single file app - CLI" section shows how to publish a single-file app as either self-contained or framework-dependent. However the "Publish a single file app - Visual Studio" section explicitly orders you to select "Self-contained" when publishing, implying that this is mandatory for single-file output, which is obviously incorrect.

The "Publish a single file app - Visual Studio" section should be updated to show both options and clarify that single-file does not require self-contained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1932751-7c2b-ce92-936e-e97f8581d5fa
* Version Independent ID: de677d1f-386a-e4c3-fdd0-6806b3ef2c0e
* Content: [Single file application - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#feedback)
* Content Source: [docs/core/deploying/single-file.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/single-file.md)
* Product: **dotnet-core**
* GitHub Login: @LakshanF
* Microsoft Alias: **lakshanf**

**Comment by tdykstra** [comment]
@LakshanF Is self-contained required when publishing from VS?

**Comment by LakshanF** [comment]
@tdykstra, no both options (self-contained or framework-dependent) can be selected in VS as well. VS publish UI for framework-dependent does not show the singlefile option on the default settings but changing the target runtime away from portable would.

**Comment by tdykstra** [comment]
@IanKemp Thanks for reporting that, I'm fixing it in #22541
