### ISSUE TITLE
Fill data about how to install .NET 5 on Linux.

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/docs#21488]
There is no documentation for installing .NET 5 on Linux. Only .NET Core 3.1. Please fill the info. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@Anduin2017 This was fixed yesterday and published this morning. #21467
