### ISSUE TITLE
Correct schema hierarchy for configuration files

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2149]
For example: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/servicediscovery

Compare vs.100
![image](https://cloud.githubusercontent.com/assets/12971179/26170070/ec23d00c-3af4-11e7-8cd8-252d3f4a2750.png)

with vs.110 or docs
![image](https://cloud.githubusercontent.com/assets/12971179/26170080/f9260860-3af4-11e7-920d-c3df089ae7f1.png)

An example of a topic was fixed already: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/add-element-for-custom-2

**Comment by svick** [comment]
I don't think it's related to any recent migration, it's like that on [the oldest version I could find on MSDN](https://msdn.microsoft.com/en-us/library/ee816905(v=vs.100).aspx).

**Comment by mairaw** [comment]
What is related to migration (and not it's from the last one, but the one before this) is the schema hierarchy section. I'm really glad we're done with migrations. 😄 
Compare vs.100
![image](https://cloud.githubusercontent.com/assets/12971179/26170070/ec23d00c-3af4-11e7-8cd8-252d3f4a2750.png)

with vs.110 or docs
![image](https://cloud.githubusercontent.com/assets/12971179/26170080/f9260860-3af4-11e7-920d-c3df089ae7f1.png)

**Comment by GuardRex** [comment]
In the upcoming PR to reconstitute the netfx config docs, I'm trying a draft that uses \&nbsp; in order to get exactly that indented layout. We can see how that goes.

**Comment by mairaw** [comment]
I was trying to find this issue before filing #8125. So I changed this one a bit to focus on the schema hierarchy section while that one fixes the syntax block.

**Comment by nemrism** [comment]
These PRs should fix the issue for the whole configuration section pages
