### ISSUE TITLE
Please provide examples of both PEM file generation and PFX file Generation

### ISSUE THREAD

**Issue by LeeRuns** [dotnet/docs#21499]
[Enter feedback here]

In the documentation there are examples of how to generate the pfx files.  It is my understanding that these can be translated into PEM file.  Why would I want to generate two different file types.  I could just generate 1 pem file and trust it on both systems correct.  Then why not simplify the tutorial and just make a pem.  Seems like having two types obfuscates the goal of the document and software. Since .net is designed to be cross platform, then use the cross platform solution. We don't need a soup spoon, desert spoon, and tea spoon. Just a simple spoon ;)

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core 3.1
- [x] .NET Framework (0.5)
- [ ] .NET Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by adegeo** [comment]
@mkArtakMSFT I'm unsure why this was transferred here?

**Comment by LeeRuns** [comment]
bump

**Comment by IEvangelist** [comment]
Hi @adegeo - can we transfer this back?

**Comment by adegeo** [comment]
@LeeRuns Sorry for the runaround here! I think this got transferred by mistake and forgotten about. I don't think we need to transfer back unless work will be done. @Rick-Anderson or @scottaddie can you answer this question? I don't really want to as my experience level with certificates isn't too broad and I feel like I'll just misrepresent something

**Comment by LeeRuns** [comment]
> 
> 
> Hi @adegeo - can we transfer this back? - Also, what is ".NET Framework (0.5)"

sorry 5 not 0.5-> https://dotnet.microsoft.com/download/dotnet/5.0





> 
> 
> @LeeRuns Sorry for the runaround here! I think this got transferred by mistake and forgotten about. I don't think we need to transfer back unless work will be done. @Rick-Anderson or @scottaddie can you answer this question? I don't really want to as my experience level with certificates isn't too broad and I feel like I'll just misrepresent something

- they are both certificates. PEM is most common. Microsoft writes examples on how to generate a .pfx file if you running .net core on windows... Then an example on how to make a PEM file if you are running linux or mac.  To make a cross platform build system a developer need to make a PEM file on windows.  Please add a tutorial on how to do that.

**Comment by adegeo** [comment]
@LeeRuns Maybe something was updated between the time this issue was opened and now? I only see pfx in the article. Even on the mac/linux section that was linked to earlier:

![image](https://user-images.githubusercontent.com/67293991/108395028-34e9c480-71ca-11eb-9393-6a7f5721d5a8.png)

**Comment by adegeo** [comment]
I'm going to close this. The original issue indicates that two types are being used, pfx and pem, but I only see pfx being used. Unsure what can be done here.

Sorry for the confusion.

**Comment by gark-msft** [comment]
This is still relevant, there is not good docs on creating a .pem file using dotnet, although we can [create an x509 from pem](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.createfrompem?view=net-5.0).
