### ISSUE TITLE
Add how to make TLS 1.2 default on .NET 4.5

### ISSUE THREAD

**Issue by hepiet** [dotnet/docs#21491]
Hi All,

Could you please add how to make TLS 1.2 default on .net 4.5? 
This is not mentioned anywhere on our official documment. TLS 1.2 is supported on .net but it not a default protocol customers would need to opt-in to use it. The following code will make TLS 1.2 default.

**ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12**

Can we please add this in our docummentation so people are aware of that?

Thanks,
Helene.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-a-net-framework-version-earlier-than-47)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by adegeo** [comment]
@hepiet Hello. I hope I'm not misunderstanding you, but using `ServicePointManager.SecurityProtocol` would only set it for a specific app, not as a **default** for .NET.

The article says to use the registry keys to set the default: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-a-net-framework-version-earlier-than-47

**Comment by hepiet** [comment]
Hi @adegeo yes you are correct . For a specific app :)
and I know 4.5 is no longer supported  but some people still use it. 
I am just asking if we could include that in the docummentation if they need to specify the SSL/TLS version in the code.
As an example of what they should add.

This is mentioned in several non official blogs on the internet. Just thought might be a good idea.

**Comment by adegeo** [comment]
@karelz Do you have thoughts on this?

**Comment by karelz** [comment]
@hepiet why would you need the above?
To my best knowledge, if you set the 2 registry keys, TLS 1.2 will be allowed and if the other side supports it, it will be preferred. Is that not the case or am I missing something here?

Using hardcoded value of TLS 1.2 will prevent upgrades to newer protocols like TLS 1.3, when they are supported by the OS. I assume that is not a goal, right?

**Comment by adegeo** [comment]
@karelz That was my thinking too. If you prevent TLS 1.3 in the app then you're vulnerable. However, I thought in the other discussion thread it was pointed out that you can't add TLS 1.3 to .NET 4.5 anyway, you have to upgrade to a later .NET, so hardcoding in this case doesn't prevent TLS 1.3.

Either way though, this article is **best practices** and I would assume that it isn't a best practice to hardcode the TLS version but instead let the OS control it?

**Comment by hepiet** [comment]
I know this are best pratices but we also know many customers still use TLS 1.2 because it is a requirement for them. 
This easy fix mentioned on my ask is shared on many randoms blogs  over the Internet (not official ones) so after getting this feedback from some customers I thought why not ask the .net team to add this here?
This fix is a lot simpler than the one we have in our doc and maybe it would be useful for others who are facing the same problem. Even if people should migrate out of 4.5.

I just wanted to check if the doc could be improved or not. We are always told we should share feedback . If you think this was pointless it is fine.

**Comment by adegeo** [comment]
@hepiet I lost track of this. Thank you very much for sharing your suggestion! I think though we'll keep these docs as-is for now. Cheers!
