### ISSUE TITLE
Incorrect regular expression

### ISSUE THREAD

**Issue by ErikMattssonSR** [dotnet/docs#21501]
Incorrect regular expression on page?:
"add address="[a-z]+.blueyonderairlines.com$""  should be "add address="[a-z]+\\.blueyonderairlines\\.com$""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe57935-4ca2-546b-4a66-76b8ba8a3538
* Version Independent ID: 3c92fc90-58fa-92a6-8494-4b1bc87d858e
* Content: [Proxy Configuration](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration)
* Content Source: [docs/framework/network-programming/proxy-configuration.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/proxy-configuration.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
