### ISSUE TITLE
The SimpleEventListener example has a race?

### ISSUE THREAD

**Issue by j03wang** [dotnet/docs#21506]
The `SimpleEventListener` example doesn't appear to work for me. It seems like at construction, the `OnEventSourceCreated` method can get called prior to `_intervalSec` being assigned, which sets the `EventCounterIntervalSec` argument to 0 instead of the intended value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05179b70-8fe7-5b1a-ca2a-4ba0297f90c8
* Version Independent ID: 19d45d3b-026c-33e6-99b9-b50458f5bcac
* Content: [EventCounters in .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters)
* Content Source: [docs/core/diagnostics/event-counters.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/event-counters.md)
* Product: **dotnet-core**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by tdykstra** [comment]
@sywhang Can you help with this?

**Comment by sywhang** [comment]
@tdykstra Yes. I will follow up with a PR to address this some time today.
