### ISSUE TITLE
.NET 5.0 does not install on Linux Mint 20 if .NET 5.0-rc2 is present

### ISSUE THREAD

**Issue by Soup-64** [dotnet/docs#21509]
On Linux Mint 20 (may apply to any distro that uses apt), the .NET 5.0 SDK does not install if .NET 5.0-rc2 is present, as apt sees .NET 5.0-rc2 as a newer version than the release version of .NET 5.0. fixing this requires the rc version of .NET to be uninstalled before attempting to install .NET 5.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@rbhanda

**Comment by dagood** [comment]
@rbhanda @leecow @NikolaMilosavljevic @dleeapho 

The version order issue called out here for 5.0.0 preview vs. 5.0.0 is also a reason we can't put previews directly in the repos yet. (https://github.com/dotnet/runtime/issues/3324)

**Comment by Soup-64** [comment]
In the meantime, a note could be added to the install instructions to let users know to uninstall preview versions before updating.

**Comment by dleeapho** [comment]
> In the meantime, a note could be added to the install instructions to let users know to uninstall preview versions before updating.

@rbhanda are you on this?

**Comment by adegeo** [comment]
@dleeapho Doing this now for the official docs, not the repo-based docs.

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/pull/5639 to tackle this
