### ISSUE TITLE
NETSDK1005 is thrown for NuGet mismatched tooling.

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/docs#21504]
For example, if a developer uses an earlier NuGet tool to restore their packages & then a newer tool to build their project, they will run into NETSDK1005.

https://developercommunity.visualstudio.com/content/problem/1248649/error-netsdk1005-assets-file-projectassetsjson-doe.html

We should document that NuGet tooling, build tooling, etc should all be aligned to a minor version i.e. 5.8 -> 16.8 & more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d963a62-6144-7ac0-3c60-7ca63dd8da25
* Version Independent ID: d4a572b0-3a21-8d0d-5709-75e4708d7f6c
* Content: [NETSDK1005 and NETSDK1047: Asset file is missing target - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005)
* Content Source: [docs/core/tools/sdk-errors/netsdk1005.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/sdk-errors/netsdk1005.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @sfoslund
* Microsoft Alias: **tdykstra**

**Comment by mathi82** [comment]
I also had this error with nuget 5.8 and VS16.8.
In my case nuget was trying to retrieve packages for dependency projects (my own projects). 
Example: ProjA -> ProjB -> ProjC where A depends on B which depends on C. 
Before VS16.8, the solution for ProjA would build successfully without having to add ProjC (everything automatically resolved)
After the update, i had to add ProjC to the solution, then my build was successful.
