### ISSUE TITLE
Recommended approach to add a single whitespace

### ISSUE THREAD

**Issue by pekspro** [dotnet/docs#21513]
If I have this code in a Blazor component:

	<button>Alpha</button>
	<button>Beta</button>
	@if (true)
	{
	    <button>Gamma</button>
	}

This will be rendered ass output:

![image](https://user-images.githubusercontent.com/3163293/98924933-b2b87880-24d5-11eb-8e13-d3e7521b79bc.png)

Note that there is not whitespace between the last two buttons. The subject “Insignificant whitespace trimmed from components at compile time” in this document explains why this happen.

Adding `@preservewhitespace true` will solve this issue. But if I want to keep having whitespaces trimmed, is there any recommended approach to add a single whitespace between the buttons? The best idea I have is to change to this:

	<button>Alpha</button>
	<button>Beta</button>
	@if (true)
	{
	    @((MarkupString)" ")<button>Gamma</button>
	}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f68af3a-3848-48ef-c24b-cf33b880ca1b
* Version Independent ID: 580c061d-20e5-248c-a24f-7a48a684c7e3
* Content: [Breaking changes, version 3.1 to 5.0 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0)
* Content Source: [docs/core/compatibility/3.1-5.0.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/3.1-5.0.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by scottaddie** [comment]
@SteveSandersonMS Any suggestions?

**Comment by SteveSandersonMS** [comment]
`@((MarkupString)" ")` will work, but more basic HTML-native approaches would include `&nbsp;` or `<span> </span>`.

**Comment by scottaddie** [comment]
@guardrex Is there anything here to document over in the Blazor docs?

**Comment by scottaddie** [comment]
Added this detail to the docs1 in https://github.com/dotnet/AspNetCore.Docs/pull/20761
