### ISSUE TITLE
Language Version behaviour for solutions originally created in VS2017

### ISSUE THREAD

**Issue by paulhasell** [dotnet/docs#21514]
Hi, in 2017 it was (still is) possible to edit the language version of a project, which we did to take advantage of 'latest' features in some of our projects. Jump to VS2019 and it's no longer editable (or even viewable) and VS suggests it's going to be auto based on framework...but it's not. VS2017 stamped the csproj with 'latest' so they're now using C# 9.0 (after 16.8 applied) and have to be manually edited  as the suggested root default doesn't override the csproj. Would have been better to fix the editor in VS2019 to keep the edit of version but have a option for 'automatic (based on Framework version' that removes the tag from the csproj.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @paulhasell 

We need to update this article to account for this. You can:

- Edit the `*.csproj` file to remove the `<LangVersion>` element. Then, the project will follow the rules outlined in this article. (You can still right-click on the project file and select "edit" in Visual Studio).
- Edit the `*.csproj` file to specify an updated `<LangVersion>` value.

I've added this to our backlog to address as part of this release.
