### ISSUE TITLE
Incorrect Code sample: DefaultChallengeScheme Mismatch

### ISSUE THREAD

**Issue by Seeker9889** [dotnet/docs#21529]
At [Authenticate with an OpenID Connect or OAuth 2.0 Identity provider](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/#authenticate-with-an-openid-connect-or-oauth-20-identity-provider), the code sample says `options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;` but uses `AddOpenIdConnect`. I believe the DefaultChallengeScheme line should look like: `options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d926868f-5446-63c6-75c0-ba879879f4b5
* Version Independent ID: ff9b78ce-a923-e763-08d5-c31cbb6a1f0e
* Content: [Securing .NET Microservices and Web Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/)
* Content Source: [docs/architecture/microservices/secure-net-microservices-web-applications/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/secure-net-microservices-web-applications/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @mjrousos
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Seeker9889, thank you for reaching out. 

If you see the actual reference application [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs), you will notice that there are multiple authentication schemes have been defined in the middleware. But the actual authentication scheme gets defined by an `[Authorize]` attribute in different controllers.  For e.g : `[Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]` in [AccountController.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Controllers/AccountController.cs)
`OpenIdConnect` has been configured for the `SignInScheme` with `Cookie` but it also has `Bearer token` specific authentication for subsequent rest API calls.

You can use multiple authentication schemes together. For further reference you could also explore [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1)

Hope this helps !

**Comment by Seeker9889** [comment]
Yes, that definitely helps. Thank you
