### ISSUE TITLE
Scripted install section: .NET 5.0 isn't LTS

### ISSUE THREAD

**Issue by ryanbarlow1** [dotnet/docs#21524]
Hello, 

I hope you're doing well. In the Scripted install section of the "Install .NET on Ubuntu" page, it states "The script defaults to installing the latest SDK long term support (LTS) version, which is .NET 5.0. To install the current release, which may not be an (LTS) version, use the -c Current parameter." 

Isn't .NET 5.0 a Current release and .NET 6.0 a LTS? Just making sure the information here is correct.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
THANK YOU for spotting that. I'll get it fixed!
