### ISSUE TITLE
Dual IDisposable and IAsyncDisposable  Pattern

### ISSUE THREAD

**Issue by fuocor** [dotnet/docs#21534]
The approach for the dual IDisposable and IAsyncDisposable requires the use of nullable types to verify the current state. This results the cascading of null checks whenever accessing the variable. Would it not be cleaner to use Booleans or bit flags to represent the state of the synchronous and asynchronous implementations thereby saving all the additional checks otherwise required?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @fuocor - I had a conversation with @bartonjs about this, we both agreed that adding the `bool` would introduce added complexity rather than simplify it. We're going to leave this as is, but we appreciate you proposing the idea. Thanks again.
