### ISSUE TITLE
Formatting if expressions can have problems when applying the short syntax style.

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#21530]
Hello,

I believe I found a weakness in the rule:

`If either cond, e1 or e2 are longer, but not multi-line:`

```fsharp
if cond
then e1
else e2
```

if `e1` is also a `SynExpr.IfThenElse` it can lead to a compiler error.
Related Fantomas bug: https://github.com/fsprojects/fantomas/issues/1243

```fsharp
                        if f.IsProperty then
                            if f.IsInstanceMember then
                                if f.IsDispatchSlot then 9 else 1
                            else 8
                        elif f.IsMember then
                            if f.IsInstanceMember then
                                if f.IsDispatchSlot then 11 else 2
                            else 10
                        else 3
```

was transformed to

```fsharp
                if f.IsProperty
                then if f.IsInstanceMember then if f.IsDispatchSlot then 9 else 1 else 8
                elif f.IsMember
                then if f.IsInstanceMember then if f.IsDispatchSlot then 11 else 2 else 10
                else 3
```

On a personal note, I never was overly fond of the `longer, but not multi-line`, it leaves a lot of room for interpretation what "longer" is.
My proposal would be to remove the rule and add a further restriction to `If cond, e1 and e2 are short, simply write them on one line:`, that `e1` or `e2` cannot be an if/then/else itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, that is good feedback. I'd be happy to accept a PR that adjusts the guidance!
