### ISSUE TITLE
Clarify relationship between with { } expressions and record copy constructor/clone method

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/docs#21541]
Section explains in detail the copy constructor of records, the hidden compiler-generated clone method.  All good and fine.  However, it should also clearly identify 1) that the copy constructor/hidden clone method specifically support the use of with { } expression, and 2) that a record can be cloned without modifications using a syntax like `var clonedRecord=originalRecord with {};`.  It would also be helpful to reinforce the difference and similarities between the foregoing and code such as `var anotherReference=originalRecord;`  In both cases, they will compare as equal using the record's compiler-supplied equality support, but in the former case, you have two identical records, but in the second, you have two references to one and the same.  As it stands now, it is not entirely obvious how the developer can access the cloning functionality or what its purpose is.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Those are all good points @ClaudioFriederich 

I think those details should be in the tutorial I'm writing for records now, rather than in the "what's new" overview. I'll add them there.

**Comment by pkulikov** [comment]
@ClaudioFriederich @BillWagner as for 

>  1) that the copy constructor/hidden clone method specifically support the use of with { } expression

in some way it is covered in the [article about with expression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/with-expression)
