### ISSUE TITLE
Ranges are not just integral types

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/docs#21569]
The statement that ranges must be integral types is incorrect.  Although arguably a bad idea, this code, where the range is a range of floats, is completely valid:

    for x in 0.0 .. 0.5 .. 99.99 do printfn "%f" x

This works with or without a skip value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0880ed-6840-b0e9-ee73-f56a60b7a3e5
* Version Independent ID: a93b42e0-1fa3-ccdc-315c-268a86669383
* Content: [Loops: for...in Expression - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/loops-for-in-expression)
* Content Source: [docs/fsharp/language-reference/loops-for-in-expression.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/loops-for-in-expression.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, good find. Would you be interested in submitting a quick patch to better explain what all is possible?
