### ISSUE TITLE
#error version Tip Not Explicitly Clear

### ISSUE THREAD

**Issue by DDoyley** [dotnet/docs#21563]
The tip about using '#error version' to determine the C# language version should make it explicitly clear that IntelliSense will flag the directive and the project will not build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I see your point @DDoyley I'll add this to our backlog. 

I've set a lower priority because the `#error` pragma is documented to generate a compiler error.
