### ISSUE TITLE
Would like powershell version of code.

### ISSUE THREAD

**Issue by quickbasic22** [dotnet/docs#21579]
Would like powershell version of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@quickbasic22 

Can you provide a few examples of what would be helpful here? In general, the powershell examples would be very similar to any other LINQ data access. For that reason, we won't duplicate all the examples and code. Instead, we do want to provide enough context to make it clear how to use LINQ in powershell scripts.
