### ISSUE TITLE
List MemberNotNull(When) in “C# Reserved attributes: Nullable static analysis”

### ISSUE THREAD

**Issue by atifaziz** [dotnet/docs#21577]
`MemberNotNull` and `MemberNotNull` were mentioned in [Announcing .NET 5.0](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) by @richlander:

> We’ve also added new annotation types. It’s common for large classes to instantiate object members in helper methods called from a constructor. The C# compiler can’t follow the flow of calls to the object assignment. It will think that the member is null when exiting the constructor and will warn with `CS8618`. The [`MemberNotNull`](https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute) attribute resolves this problem. You apply the attribute to the helper method. The compiler will then see that you set this value and realize that the method is called from a constructor. [`MemberNotNullWhen`](https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.membernotnullwhenattribute) is similar.

but missing from the [revenant content in the documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @atifaziz 

I've added this to our list of updates as part of the .NET 5 wave.
