### ISSUE TITLE
Misspelled error

### ISSUE THREAD

**Issue by billsoff** [dotnet/docs#21572]
[在此处输入反馈]
"Returns true iff analysis..." f is more once typed.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c0c751c3-3928-0f99-b6fa-9c2044eeb51e
* Version Independent ID: a52ced43-e6f4-4a9d-f0ae-8525a70000d8
* Content: [DataFlowAnalysis.Succeeded Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.codeanalysis.dataflowanalysis.succeeded?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/DataFlowAnalysis.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/DataFlowAnalysis.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
I'm not sure whether it's intentional (means if and only if), or a typo.
