### ISSUE TITLE
Why Behavior changes when comparing strings on .NET 5+?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [dotnet/docs#21575]
Hello,

When you change default values of the structure of .Net in version 5+ that means you are breaking the backward-compatible of c# and .net framework.

It's like you change the default value of bool to 'true'.
Why you should do this way and say to developers change all of your codes?
Why Developers have to change all of the default values of bool to false manually?
for example:
I'm using this code:

`public bool Success {get;set;}`

the default value of the Success property is false because of the default value of boolean in c# from version 1.0.
so when you change the default value to true in CLR, you have to tell thousands of developers to change this value to false manually like this way:

`public bool Success {get;set;} = false;`

Do you know how many codes have to change?
Is this design structure true? I want to see the .Net5 project manager !!
So I want to know why Microsoft is going to change default values in NET5+?
You are just wasting our time in this breaking change and you don't know how many codes we have to change for this. how many bugs we have to fix for this breaking changes?

examples to check:

```
            string s = "Hello\r\nworld!";
            int idx = s.IndexOf("\n");
            Console.WriteLine(idx);
            //Outoput is -1 in .Net5+
            //Outoput is 6 in .Net3.1-
```
example 2:

```
            string s = "Hello\r\nworld!";
            int idx = s.IndexOf('\n');
            Console.WriteLine(idx);
            //Outoput is 6 in Both .Net5+ and .Net3.1-
```

check this blow link pls:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff20a875-d296-266f-8e5b-a3ab32db2491
* Version Independent ID: 1788f46c-cdad-9ea5-7bd7-62c959255fd5
* Content: [Behavior changes when comparing strings on .NET 5+](https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus)
* Content Source: [docs/standard/base-types/string-comparison-net-5-plus.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/string-comparison-net-5-plus.md)
* Product: **dotnet**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Greetings!

If you look at the **Revert back to NLS behaviors** section of the article, you'll see a link to [.NET globalization and ICU](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu) and there is a section that shows you how to force the app into the old behavior. If you force it to the old behavior you will always have the possibility of having different values on windows/linux/mac for the same code.

As stated in the article, the reason for the forced change was to unify behavior across all platforms. Before this change you would get different results on different platforms for `.IndexOf("\n")` for example. Now you will get the same value regardless of if someone is running on linux vs windows. The code for `.IndexOf(char)` vs `.IndexOf(string)` uses different logic as the `string` version needs to process and compare in a different way. `char` always uses the ordinal by default.

Prior to this change, you would get different values for Windows and Linux:

```csharp
string s = "Hello\r\nworld!";
int idx = s.IndexOf("\n");
Console.WriteLine(idx);

// '6' when running on .NET Framework (Windows)
// '6' when running on .NET Core 2.x - 3.x (Windows)
// '-1' when running on .NET Core 2.x - 3.x or .NET 5 (non-Windows)
// '-1' when running on .NET 5 (Windows)
```

When you use the proper comparison, you see the intended result:

```csharp
string s = "Hello\r\nworld!";
int idx = s.IndexOf("\n",  StringComparison.Ordinal);
Console.WriteLine(idx);

// '6' when running on .NET Framework (Windows)
// '6' when running on .NET Core 2.x - 3.x (Windows)
// '6' when running on .NET Core 2.x - 3.x or .NET 5 (non-Windows)
// '6' when running on .NET 5 (Windows)
```

This repo is just for the documentation and you can discuss design decisions with the product team on this subject in [this thread in the dotnet/runtime](https://github.com/dotnet/runtime/issues/43736#issuecomment-724284049) repository. 

Cheers!
