### ISSUE TITLE
Suggestion to remove "Improved overload resolution" section

### ISSUE THREAD

**Issue by mdemiy** [dotnet/docs#21584]
The "Improved overload resolution" scetion in [What's New in C# 6|https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6] contains the following sentence "The earlier compiler couldn't distinguish correctly between Task.Run(Action) and Task.Run(Func<Task>()). In previous versions". it should be considered as an issue of compiler not as a language feature.

**Comment by BillWagner** [comment]
Thanks for noting this @mdemiy 

I'll handle this as part of #19972

**Comment by BillWagner** [comment]
Fixed in #21892
