### ISSUE TITLE
.editorconfig Option Not Shown

### ISSUE THREAD

**Issue by stricq** [dotnet/docs#21580]
This option is available in the .editorconfig file, but this page does not explain how to use this option in that file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddd8eded-3cff-a84d-57a8-a61faddc2c08
* Version Independent ID: 2ab9a9ff-ab74-c9eb-21c6-9189f0803e98
* Content: [IDE0079: Remove unnecessary suppression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0079)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0079.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/ide0079.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@stricq Are you referring to the [dotnet_remove_unnecessary_suppression_exclusions option](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0079#dotnet_remove_unnecessary_suppression_exclusions)? It seems that it is documented, but the docs could make clearer that this is an option that you set in an editorconfig file.

cc @mavasani

**Comment by mavasani** [comment]
@stricq - The Tools/Options page for .NET code style options is on its path to deprecation. @jmarolf is working on a replacement editorconfig UX which will be shared for repo level and VS level code style options, which should allow you to view and/or change all editorconfig code styles. Tagging @mikadumont as well.

**Comment by gewarren** [comment]
Related to https://github.com/dotnet/docs/issues/24437.

**Comment by gewarren** [comment]
For this issue, I propose we add a short intro to setting options in the new Options H2 section of each rule. Wait until #29913, #29914, #29915 are merged.
