### ISSUE TITLE
Immersive reader mode not supported.

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [dotnet/docs#21583]
This page doesn't support immersive reader mode in the Microsoft Edge Chromium browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
moving to Microsoftdocs/feedback.

**Comment by BillWagner** [comment]
Closed and moved to MicrosoftDocs/feedback#3275
