### ISSUE TITLE
Eliminate references to MVU from description of MAUI

### ISSUE THREAD

**Issue by JeroMiya** [dotnet/docs#21585]
MVU is a specific pattern and architecture. A core part of the MVU architecture and pattern includes read-only state and a mechanism for updating it which includes messages or commands and state transformation functions. MAUI's architecture is many good things: Fluent, Reactive, One-way or Unidirectional Data Flow. However, it is not MVU as it is missing the entire U portion of the pattern - in other words the immutable state management portion of the pattern, which forms part of the core of the architecture. Continued references to "The MVU pattern" in documentation surrounding MAUI will continue to cause confusion and should just be replaced by references to the actual patterns used. I suggest keeping "Fluent", and "One-way Data Flow", maybe adding "Reactive" which would be more accurate descriptions of MAUI's architecture. In this page and all other official documentation, samples, and training materials, etc... for MAUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8175dfa-c812-afef-c018-a5927995ef43
* Version Independent ID: 4fd72a98-c51f-cbd9-0578-d6448bab4749
* Content: [What's new in .NET 5](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five)
* Content Source: [docs/core/dotnet-five.md](https://github.com/dotnet/docs/blob/master/docs/core/dotnet-five.md)
* Product: **dotnet-core**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @JeroMiya - thank you so much for posting this issue. I appreciate the concern and the call to action. The section that you're [referring to](https://docs.microsoft.com/dotnet/core/dotnet-five#model-view-update-pattern) states the following:

> ### Model-View-Update pattern
> Developers love modern development patterns. A fluent approach to UI development, inspired by "The Elm Architecture" is the model-view-update or MVU pattern. MVU promotes a one-way flow of data and state management, as well as a code-first development experience that rapidly updates the UI by applying only the changes necessary.
> 
> As an example, consider the following counter written in .NET MAUI using the MVU pattern:

While I understand your concern, it is true that this is inspired by "The Elm Architecture". We also already state that it is a fluent and one-way data flow approach, as you suggested. Furthermore, the `State<int>` object is `readonly` and its value is only ever updated based on an event, i.e.; the user clicking the button.

You mention that "a mechanism for updating it which includes messages or commands and state transformation functions", this is the event in which the user clicks the button, the state is then updated based on the receiving end of the event message.

Hey, @jamesmontemagno do you have any suggestions around rephrasing this - do you believe it is necessary?

**Comment by jamesmontemagno** [comment]
.NET MAUI is .NET 6, so shouldn't be here anyways. MVU section can be removed as it isn't a feature of .NET it is a feature of .NET MAUI

**Comment by JeroMiya** [comment]
> this is the event in which the user clicks the button, the state is then updated based on the receiving end of the event message.

This is the part that does not match the MVU pattern. In MVU, for the U portion there is an explicit mechanism for updating state beyond just setting the state directly from an event callback and triggering a view render. There are extra steps involved, which work as follows:

In MVU, application code in event callbacks from the UI may call a Dispatch function, which takes a Message as its argument. The Dispatch(Message) function calls an UpdateFunction(PreviousState, Message) with the message and the previous state, then takes the resulting NextState and passes it to a View function to complete the circle:

View Event callback calls Dispatch(Message)
Dispatch(Message) triggers a view update:
 - Call to UpdateFunction(PreviousState, Message) results in NewState
 - Call to ViewFunction(NewState) results in new immutable View object, which is then "rendered" (typically via diffing).

MAUI does not directly have the concept of either a Dispatch function or an UpdateFunction. It does contain a ViewFunction but it is not passed in NewState directly. Rather, individual components hold local state which is explicitly managed. Instead of triggering a state update by calling Dispatch(Message), the component's local state is set directly triggering the next ViewFunction. 

I'm not arguing against this, I'm only pointing out that MAUI is not MVU. MVU is a more formal pattern that can be layered on top of this architecture. It would be more accurate to say that MAUI is inspired by frameworks like React or Flutter or SwiftUI than Elm/MVU, in that state flows in one direction to a View function which is triggered whenever local component state changes. Further, like React/Flutter/SwiftUI it has the concept of stateful components, where each component holds its own state and has a mechanism for managing that state that is tied to view rendering. Finally, MAUI optionally supports a fluent or declarative C# approach to UI rendering, though XAML templates are supported as well.

**Comment by JeroMiya** [comment]
Note: the primary intent of the formalism of state updates and messages in MVU are as follows:
- The UpdateFunction(PreviousState, Message) -> NextState is a stateless pure function, and can very easily be unit tested.
- The ViewFunction(NextState) -> NextView is a stateless pure function, and can very easily be unit tested.
- State changes can be recorded in sequence and potentially played back for debugging purposes or for app functionality.

But it has the following drawbacks:
 - Overly verbose and high ceremony for small applications.
 - Performance impact from potentially redundant view tree diffing and rendering.
