### ISSUE TITLE
Code example for dotnet core library is wrong

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#21597]
---
**Issue moved from MicrosoftDocs/feedback#3245**
- Please respond to @zlidzen.

---

_From @zlidzen on Wednesday, November 4, 2020 1:01:14 PM_

**Is your feature request related to a problem? Please describe.**
Where : 
https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code#add-a-console-app-to-the-solution
In pp.3 'Open ShowCase/Program.cs and replace all of the code with the following code.'

What : 
Presented code example doesn't compile.

Why :
This method "void ResetConsole()" doesn't contain declaration or input parameter of "row".

**Describe the solution you'd like**
add input parameter in "void ResetConsole()" -> "void ResetConsole(int row)"
update call this method "ResetConsole();" -> "ResetConsole(row)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cbb75b-e0aa-13c6-c07d-65f0f0f68da2
* Version Independent ID: 06ecbd1e-dad7-fbac-9160-dfce34df4d2c
* Content: [Create a .NET class library using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code#add-a-console-app-to-the-solution)
* Content Source: [docs/core/tutorials/library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3245**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, November 4, 2020 1:01:16 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by tdykstra** [comment]
`ResetConsole` is defined within the `Main` method, so `row` is accessible in it.  Is it possible you placed an extra end curly brace before the `ResetConsole` declaration?
