### ISSUE TITLE
Please provide more examples for single line comment handling

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#21590]
The example shows this...
``` json
{
  "Date": "2019-08-01T00:00:00-07:00",
  "TemperatureCelsius": 25, // Fahrenheit 77
  "Summary": "Hot", /* Zharko */
}
```

What about these more common forms of comments?

``` json
{
  "Date": "2019-08-01T00:00:00-07:00",
  "TemperatureCelsius": 25, 
  // "TemperatureFahrenheit": 77,
  "Summary": "Hot", 
  /* "OddSummary": "Zharko" */
}
```
And then what if the json is minified into a single line? Does this feature depend on having CR+| LF in the json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#allow-comments-and-trailing-commas)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Comments can be on separate lines as shown in your example, and the /* ... */ format works in minified JSON.
