### ISSUE TITLE
Missing Most New C# 9.0 Keywords

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/docs#21603]
Entries for the keywords `and`, `init`, `not`, `or`, & `record` are missing.

---
#### Document Details
`
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @zacharylayne 

This is on our roadmap as we finish the reference material for C# 9.0.

I've added this to our ..NET 5 languages project.

**Comment by SunnieShine** [comment]
@BillWagner Excuse me.

Should docs be added keyword 'managed' and 'unmanaged' keyword into the keyword list page?

**Comment by BillWagner** [comment]
Thanks @SunnieShine 

I created #23729 to address this.
