### ISSUE TITLE
Mark as read feature needed

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [dotnet/docs#21600]
A feature "Mark as Read" is needed to separate read pages from unread. It will help us to mark read sections of documentation and start from the last endpoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc06ead-fe51-85db-1340-87f6473db769
* Version Independent ID: 4f2c312e-609c-a643-4af6-c12c6cf74738
* Content: [Indexers](https://docs.microsoft.com/en-us/dotnet/csharp/indexers)
* Content Source: [docs/csharp/indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/indexers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Closing and moving to MicrosoftDocs/feedback#3282
