### ISSUE TITLE
Code example for ordering with AsSequential() has no effect?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/docs#21602]
The following code in the docs

```
static void SequentialDemo()
        {
            var orders = GetOrders();

            // call to WithExecutionMode added by me
            var query = (from ord in orders.AsParallel().WithExecutionMode(ParallelExecutionMode.ForceParallelism)
                         orderby ord.CustomerID
                         select new
                         {
                             O = ord.CustomerID,
                             Details = ord.OrderID,
                             Date = ord.OrderDate,
                             Shipped = ord.ShippedDate
                         }).AsUnordered().AsSequential().Take(5);
            
           // Added by me to print the elements
            foreach (var item in query)
            {
                Console.WriteLine(item);
            }
        }
```
Has no difference when the call to `AsSequential` is omitted. Why is that the case? Furthermore, each time we run this, it the order is always different, never the same. I don't think this example is at all a good one. If we order by a second colum, say ord.OrderId, we can see that the same order is produced regardless if we have `AsSequential` in there or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de472a3-3017-e6e2-3b27-a62f8bd18959
* Version Independent ID: c7ddd569-d9b5-a59f-86a7-29ef8675540d
* Content: [How to: Combine Parallel and Sequential LINQ Queries](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-combine-parallel-and-sequential-linq-queries?redirectedfrom=MSDN)
* Content Source: [docs/standard/parallel-programming/how-to-combine-parallel-and-sequential-linq-queries.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-combine-parallel-and-sequential-linq-queries.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @SpiritBob - I found the bug, thank you for bringing this to my attention. It should have been `orderby ord.OrderID`. PR coming soon.

**Comment by SpiritBob** [comment]
@IEvangelist glad to be of service to the team! I'm still confused though as to why we are calling`AsSequential`? Omitting it doesn't change anything, and I've been reading this book that states that it should be used if we ever use parallelism and wish to see the correct order of items after we use `Take` on the query (granted the query itself has some ordering we wish to preserve).

Could you expand on that please?

**Comment by IEvangelist** [comment]
Since `AsSequential` converts the `ParallelQuery<T>` into an `IEnumerable<T>`, the `Take` operator is working against the sequential collection rather than the parallel version. Think of it like this, if you have a collection that is fed from multiple sources at the same time, there is no knowing which source an item comes from - but when it's converted into a single source, it's known. Does that make more sense, if so I'll update the doc to include more details like this?

**Comment by SpiritBob** [comment]
> Since `AsSequential` converts the `ParallelQuery<T>` into an `IEnumerable<T>`, the `Take` operator is working against the sequential collection rather than the parallel version. Think of it like this, if you have a collection that is fed from multiple sources at the same time, there is no knowing which source an item comes from - but when it's converted into a single source, it's known. Does that make more sense, if so I'll update the doc to include more details like this?

Yes, it does make sense, but it does not show this "issue" of `Take` sometimes producing incorrect results when used on a `ParallelQuery<T>`? The end result produced is the same regardless if we use `Take` on a `IEnumerable<T>` or a `ParallelQuery<T>` in the above example. That's the biggest confusion, which raises questions why we even need to call `AsSequential` in the first place, if it works without it with no hiccups. Does that make sense?

**Comment by IEvangelist** [comment]
There are many moving parts here, so I do see where you're coming from.

It seems like one of the issues is the usage of `Take` in this example, that was to simplify limit the number of printed results as an example. And there is actually a difference in the implementation of the two variants of `Take` in this context.

- [`ParallelQuery<TSource>.Take(this ParallelQuery<TSource> source, int count)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.parallelenumerable.take?view=net-5.0)
- [`IEnumerable<TSource>.Take(this IEnumerable<TSource> source, int count)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-5.0)

When used after the call to `AsSequential`, it is the latter of these two calls. They are different in that the first one comes from the parallel source. While the results appear to repeat the same behavior when multiple runs back to back, there is no guarantee of that order. But do not think about the ordering, that is probably a distraction. This exercise is to highlight that you can take a parallel source and convert it into a sequentially evaluated one instead.

@BillWagner do you have any additional insights you might be able to offer here?
