### ISSUE TITLE
OS X missing 'Big Sur' and 'M1' example with osx.10.16-arm64

### ISSUE THREAD

**Issue by fnatzke** [dotnet/docs#21619]
Be very helpful to show how an example of how to target 'Big Sur' and if desired the new 'M1' (ARM64) chip for performance:

osx.10.16-arm64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime Identifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@Anipik @wfurt I see both 10.16 and 11.0 were added -- which one or should both be documented here in the [macOS RIDs](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md#macos-rids) section?

**Comment by wfurt** [comment]
I think we should document 11.0. .NET 5.0 and newer will report that. 10.16 will stay as fall-back for older .NET versions.
