### ISSUE TITLE
How to add a json converter to deserialize a property with a specified derived class ?

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#21611]
---
**Issue moved from dotnet/docs.fr-fr#109**
- Please respond to @Anthony-Breneliere.

---

_From @Anthony-Breneliere on Wednesday, July 8, 2020 2:19:28 PM_

Hello,

I try to migrate from Newtonsoft.Json to System.Text.Json, and I fall on that classic use case:

I receved data to deserialize using a class that has properties that that need to be deserialized using a specific derived class.

In newtonsoft.json, I have that very simple converter:

```
    public class EquipementSharedConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (objectType == typeof(IMABaseModel.Transmitter))
                return serializer.Deserialize(reader, typeof(Transmitter));

            return serializer.Deserialize(reader, objectType);
        }

        public override bool CanConvert(Type objectType)
        {
            return new[] {  typeof(IMABaseModel.Transmitter)  }.Contains(objectType);
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {          throw new NotImplementedException();        }
    }
```

The property with type IMABaseModel.Transmitter is deserialized using the derived type Transmitter.

IMABaseModel.Transmitter is in a high level package that does not know the Transmitter type.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrer de Newtonsoft.Json vers System.Text.Json -.net](https://docs.microsoft.com/fr-fr/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The documentation we have available that is the closest to what you're looking for is probably the converter sample for polymorphic deserialization: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#support-polymorphic-deserialization

If that doesn't help, you're more likely to find a helpful answer on a support forum such as StackOverflow.com.
