### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by jgedri** [dotnet/docs#21629]
Is there a version of .Net Framework for Ubuntu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@jgedri Mono is an implementation of .NET Framework for Linux. However, we recommend all new code be written in .NET 5 as it's the latest version of .NET and is built for cross-platform use.
