### ISSUE TITLE
change => to >=

### ISSUE THREAD

**Issue by uskr** [dotnet/docs#21622]
I believe it is supposed to be >= and not =>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Extension Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@uskr Which code snippet are you referring to?

I see `=>` in two places:

1. `ints.OrderBy(g => g)`, which is correct (this is a lambda expression).
2. `static string FullName(this DomainEntity value) => $"{value.FirstName} {value.LastName}";`, which is also correct (this is a method bodied expression).

**Comment by adegeo** [comment]
Hello!

@Youssef1313 is correct. These are [lambda expressions](https://docs.microsoft.com/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-use-lambda-expressions-in-a-query).

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
