### ISSUE TITLE
Incorrect comment in Generic Interfaces code example

### ISSUE THREAD

**Issue by jhardin-impsec** [dotnet/docs#21641]
In this comment in a code example in *Generic Interfaces*:
>                //  Because we need to call this method, the SortedList
>                //  class is constrained on IEnumerable<T>

Shouldn't it be:
>                //  class is constrained on IComparable<T>
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0a00a9-fd5d-3aae-9788-d6b324f17599
* Version Independent ID: d54ecf19-fccb-3d6b-d990-81529acf44c3
* Content: [Generic Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-interfaces)
* Content Source: [docs/csharp/programming-guide/generics/generic-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/generic-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @jhardin-impsec I've opened #21675 to fix this.
