### ISSUE TITLE
Errors in my code I need to enter any number from my keyboard freely and get the area perimeter and diagonal... help

### ISSUE THREAD

**Issue by Fred97-cpu** [dotnet/docs#21652]
[ConsoleApp.txt](https://github.com/dotnet/docs/files/5567875/ConsoleApp.txt)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f87c3641-542e-5b39-543c-b2307b495cc9
* Version Independent ID: 9fff3e7d-4cad-ef6e-4b7f-32882cc8d8e8
* Content: [Expression expected - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30201)
* Content Source: [docs/visual-basic/misc/bc30201.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/misc/bc30201.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
This should be redirected to the [Visual Basic forum](https://docs.microsoft.com/answers/questions/208771/visual-basic-1.html) on Visual Basic.

Closing.
