### ISSUE TITLE
TFMs with non-Windows platforms are not available in .NET 5.0 SDK but mentioned in the doc

### ISSUE THREAD

**Issue by addabis** [dotnet/docs#21650]
This page goes into detail on how OS-specific TFMs work, but all non-Windows OS-specific TFMs are not available in .NET 5.0 SDK and I think got postponed to .NET 6.0. I guess some clarification of the current state of things should be present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@terrajobst Where can I find out more info about the current state of OS-specific TFMs?

**Comment by gewarren** [comment]
Based on [this](https://github.com/dotnet/designs/blob/b199c762ec9c09b5e5ee741f8b6ab9d1d087ab47/accepted/2021/net6.0-tfms/net6.0-tfms.md#design), I think you are correct.

**Comment by terrajobst** [comment]
Yep. But the good news is that makes the content easier to update for .NET 6 ☺
