### ISSUE TITLE
.NET Framework 5.0

### ISSUE THREAD

**Issue by ColbyRingeisen** [dotnet/docs#21662]
Can we get this page updated for .NET Framework 5.0 ASAP?  I would think that would've been on the To-do list BEFORE it was generally available...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ColbyRingeisen This page is specific to determining which versions of .NET *Framework* are installed. .NET 5.0 is not .NET Framework 5.0; it is the next version of .NET Core after 3.1. Version 4 was skipped so as not to confuse with .NET Framework versions.

**Comment by ColbyRingeisen** [comment]
Got it. Thanks!

IMHO, dropping "Core" from the name is just as confusing as skipping version 4.  It's still going to get confused with the actual framework for that reason.
