### ISSUE TITLE
Typo in MS doc

### ISSUE THREAD

**Issue by deniees** [dotnet/docs#21671]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/38551946/99780152-14af5880-2b3c-11eb-9436-3d28c5b94aed.png)
please fix the typo as strongly "typed"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cb1365-bb1f-b869-84db-8400ffb223d2
* Version Independent ID: 6c4e9725-7689-b6a0-777d-e76e7999c138
* Content: [Framework Libraries](https://docs.microsoft.com/en-us/dotnet/standard/framework-libraries)
* Content Source: [docs/standard/framework-libraries.md](https://github.com/dotnet/docs/blob/master/docs/standard/framework-libraries.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @richlander
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@deniees Would you like to submit a PR to fix this? See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
