### ISSUE TITLE
LinkGenerator doesn't match this rule

### ISSUE THREAD

**Issue by AleAntonellis** [dotnet/docs#21672]
This rule is very useful but I have some methods that wrap LinkGenerator's methods. These methods don't match the rule.

For example:
- LinkGenerator.GetUriByName, that return a string

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8d87c0-61af-3be4-553b-444974fdf329
* Version Independent ID: 4124e17c-6f49-c7b0-6481-620be6ee1168
* Content: [CA1055: URI return values should not be strings (code analysis) - .NET](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1055?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1055.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1055.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This issue was moved to dotnet/roslyn-analyzers#4450
