### ISSUE TITLE
"Switch expression" should call out what happens when none of the expressions match

### ISSUE THREAD

**Issue by davkean** [dotnet/docs#21695]
The docs on the top of switch expression don't call out what happens when none of the cases match and you don't have a fallback case "_".

In this case, it appears that this throws an InvalidOperationException (on .NET Framework), or a SwitchCaseException (.NET Core 3.0+).

Here's an example:

``` C#
3 switch { 4 => 5 }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd278c65-14fb-2c27-966d-6e14c74fbcaa
* Version Independent ID: e94a68f9-1a6c-a7e0-e1ee-4be1114bb8dc
* Content: [switch expression - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression?source=docs)
* Content Source: [docs/csharp/language-reference/operators/switch-expression.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/switch-expression.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @davkean I'll make sure we update it.
