### ISSUE TITLE
Incorrect name/value pair

### ISSUE THREAD

**Issue by jpiquot** [dotnet/docs#21692]
The correct value is : dotnet_diagnostic.CA2007.severity = none

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e1db77-7c83-f34e-8f12-1a55ac02c69a
* Version Independent ID: 78d8ae43-61be-01da-f8a7-42d73365a9e3
* Content: [CA2007: Do not directly await a Task (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2007.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2007.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@jpiquot I think the one you're mentioning does a different thing than the ones in the articles.

**Comment by gewarren** [comment]
I agree with @Youssef1313. You can set the severity on any code analysis rule, so it's not explicitly mentioned in each rule's reference page. Rule CA2007 has additional configurable options that are shown in the article. Would it help to add a note about how to suppress the warning from the rule? I imagine users that hit any code analysis error arrive directly at a specific rule's reference page, not at the overview page that describes how to suppress the warning.
