### ISSUE TITLE
Filter for excluding PRs matching titles

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#21698]
This has two user scenarios now. First, titles that are of the form "Confirm merge from repo_sync_working_branch". Second, any title that contains "publish". Third, to make the current rule for titles of the form "update <markdownfile>" should be configurable as well.

It's unclear if we want to make this a set of switches, or provide a general grammar like a regex.

**Comment by scottaddie** [comment]
Fixed in https://dev.azure.com/mseng/TechnicalContent/_git/dotnet-docs-tools/pullrequest/590297
