### ISSUE TITLE
Visual Basic code

### ISSUE THREAD

**Issue by GuidoVL3** [dotnet/docs#21700]
Nice documentation but where can I find the coding for VB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Create a .NET class library using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
There's a drop-down selector at the top of the page:
![image](https://user-images.githubusercontent.com/1569635/100011816-233d8000-2d87-11eb-914b-b78f80389516.png)

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
