### ISSUE TITLE
What should overloaded operators ==, !=, <, <=, >,>= return?

### ISSUE THREAD

**Issue by CLIRResearch** [dotnet/docs#21709]
The documentation should include the return type for comparison operators or a link to a reference.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91d85ae-8b37-e837-a031-144571362fbb
* Version Independent ID: 5ec5c397-c7c6-700c-bc36-a8dfb2396dad
* Content: [Operator overloading - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading)
* Content Source: [docs/csharp/language-reference/operators/operator-overloading.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/operator-overloading.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@CLIRResearch there are reference links in the table

**Comment by BillWagner** [comment]
Thanks for raising this concern @CLIRResearch   I am going to close this. As @pkulikov points out, the entries in the table link to each operator. If we added them to this page, we'd need to be complete for all types and all operators. That would make this page much more complicated.

If you still disagree, you can reopen the issue, and add more details on why you want this information on this page.
