### ISSUE TITLE
The nuance of working with the var keyword.

### ISSUE THREAD

**Issue by lutk** [dotnet/docs#21716]
Why is there no mention of the nuance of working with the var keyword in any document on this topic?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var
"When var is used with nullable reference types enabled, it always implies a nullable reference type even if the expression type isn't nullable."

In my opinion, this outweighs absolutely all the advantages of using nullable reference types and makes reading and refactoring a real hell.
Madness..

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Ссылочные типы, допускающие значение null](https://docs.microsoft.com/ru-ru/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
While I think it's reasonable to add this note to the article, I just want to note that the flow analysis is still smart enough and the state of the variable will be "not null" even if the type is deduced as nullable.

![image](https://user-images.githubusercontent.com/31348972/100523376-cbed4480-31b8-11eb-87eb-b2bffcd4e399.png)

So in most situations, you don't need to give much attention.

**Comment by BillWagner** [comment]
I agree we should add a note on this page. Adding this to our backlog, and adding the "up for grabs" label.
