### ISSUE TITLE
Breaking changes to XML parsers between .NET 4.5.1 and .NET 4.5.2 not outlined

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/docs#21710]
This page https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.0-4.8 does not mention the fact that XmlDocument, XmlReader and perhaps some other classes have a breaking change between 4.5.1 and 4.5.2 - the default XmlUrlResolver is no longer used by default as explained here https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlreader.create?view=netframework-4.7.2 (search for "4.5.2"). So XML parsing changes big time for certain scenarios. This is a breaking change which is not outlined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07873b5-0b45-90dd-fb98-035241a2bed7
* Version Independent ID: 35e4c4f6-fd40-de30-f82e-7a9566ffb90e
* Content: [Runtime Changes for Migration from .NET Framework 4.0 to 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.0-4.8)
* Content Source: [docs/framework/migration-guide/runtime/4.0-4.8.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/runtime/4.0-4.8.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PriyaPurkayastha Can you check if this is a breaking change that should be documented?

**Comment by PriyaPurkayastha** [comment]
I think it would be useful to document this breaking change. @tarekgh do you happen to have any context on this? This is from .NET Framework 4.5.2 timeframe.

**Comment by tarekgh** [comment]
@PriyaPurkayastha I believe this breaking change has been done with a config switch `EnableLegacyXmlSettings`. I recall this config switch was documented before but I cannot find it anymore. Somehow looks the old docs disappeared.

The change is done as a security fix. the change mainly was 

```
XmlTextreader:
- Change the default value of MaxCharactersFromEntities to 10 million 
- Change Xmlresolver to null 

XmlReader
- Change the initialization of XmlReaderSettings to set MaxCharactersFromEntities to 10 million and set XmlResolver to null. Note that XmlReaderSettings is used by all parser so this change will help the XmlReader case but it affect other scenarios.

```

Note, the `MaxCharactersFromEntities` is not affected by the config switch.
