### ISSUE TITLE
Inconsistency With Other Page for .Net Core 3.1 Supported Windows 10 Version

### ISSUE THREAD

**Issue by RaliVotron** [dotnet/docs#21717]
Hi,
The current page (https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31), in the Dependency section (tab for .Net Core 3.1), says that .Net Core 3.1 is compatible with Windows 10 Version 1609+.
However, in the other page specifically for .Net Core 3.1 (https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md), we see that it is compatible with Windows 10 Version 1607+.
You could update the page that is wrong.
Thank!
If you have a way to let me know directly that the correction was done (and what is the correct information), I would like to know what is the minimum Windows 10 version compatible with .Net Core 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for noting that. I'll fix this page. The guidance in the release notes is correct.
