### ISSUE TITLE
Document source generators

### ISSUE THREAD

**Issue by svick** [dotnet/docs#21712]
**Help us make content visible**

I have found a couple of articles on the .Net blog ([Introducing C# Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) and [New C# Source Generator Samples](https://devblogs.microsoft.com/dotnet/new-c-source-generator-samples/)) and also a couple of documents on the Roslyn repo ([Source Generators](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.md) and [Source Generators Cookbook](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md)). But I think source generators should be documented on docs.MS. Also, the blog posts are outdated, since they're talking about .Net 5 previews.

**Describe the new article**

Source generators are a major new feature of the C# compiler and so they should be properly documented.

I think they belong under [the Roslyn SDK](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/) section of the C# documentation.

The article could be based on the four articles mentioned previously.

cc: @cartermp

**Comment by gewarren** [comment]
cc @chsienki

**Comment by chsienki** [comment]
Thanks @svick, we're currently in the process of writing these up, we'll have some content on docs.ms coming soon.

**Comment by svick** [comment]
I'm going to close this, since [the article](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) exists now.
