### ISSUE TITLE
.NET Framework reference, Char Struct, Char values and interop:  Error "UTF-8 encoded"

### ISSUE THREAD

**Issue by b3bb** [dotnet/docs#2173]
see: https://docs.microsoft.com/en-us/dotnet/api/system.char?view=netframework-4.7#remarks

section "Char values and interop"

existing text: "When a managed Char type, which is represented as a Unicode UTF-8 encoded code unit, is passed to unmanaged code, the interop marshaler converts the character set to ANSI."

Char type represents a UTF-16 code unit. 

new / correct text: "When a managed Char type, which is represented as a Unicode UTF-16 encoded code unit, is passed to unmanaged code, the interop marshaler converts the character set to ANSI."

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @b3bb. I've created PR #2177  to address it.
