### ISSUE TITLE
Does EF Core 5.0 migration and JSON deserialization work with C#9.0 init-only setters?

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#21741]
Or do I still need private setters? Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @ajcvickers I don't know the answer, but we should update this article to reflect the EF Core product plan.

**Comment by tdykstra** [comment]
Yes to init-only setters -- see the second code example here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0#immutable-types-and-records

**Comment by ajcvickers** [comment]
@BillWagner Yes, I believe so. However, I don't think this is the right place reference EF Core.

**Comment by BillWagner** [comment]
@ajcvickers 
>  I don't think this is the right place reference EF Core.

I agree. Is there an article I should link to that would help customers looking for this?

**Comment by ajcvickers** [comment]
@BillWagner We don't have any page that covers which new features are supported or not. Typically new features are supported by default unless they involve fundamental changes to the language or CLR. @roji Do you think there is anything to doc here?

**Comment by roji** [comment]
@ajcvickers not really, I also don't see much value in documenting by new language features (unless there's something specific to say). I'm also not sure exactly what is being asked here in terms of EF Core 5.0 migration support for init-only setters, maybe @khteh can provide more detail.

**Comment by khteh** [comment]
I am referring to running `dotnet ef database update --context AppDbContext`. Would it work with read-only entities to define `init;` setters which I previously used `private set;` methods?

**Comment by roji** [comment]
@khteh if you're asking whether EF Core supports entity CLR types with init-only properties (regardless of `dotnet ef database update`), then the answer is - only to an extent. EF Core can materialize entities with init-only properties, but like all forms of immutable entity types, it's difficult to use change tracking to persist changes back to the database. Since you can't change the property, you must make a copy of the entity instance, but EF isn't aware that of that copy, and therefore can't detect your change. There are some ways around that, but the experience definitely isn't great.

I've opened https://github.com/dotnet/EntityFramework.Docs/issues/2931 to track adding some info in the EF docs on immutable/read-only entity types.

**Comment by roji** [comment]
@khteh I've just noticed you mentioned you were previously using `private set` methods; I'm not sure exactly how you're doing things, but it sounds like using `init` properties might work. For any further info, please post an actual code sample so we can see exactly what you're doing.

**Comment by khteh** [comment]
@roji I am aware of what you said about change tracking. I only use `private set;` on read-only properties which are set by the entity constructor. So, they are not immutable "entity" but mutable entities with some immutable properties. That's why my concern in my initial post about changing that to using `init;` Since you said EF Core can materialize entities with init-only properties, that addresses my concern. I will test it when Pomelo is officially released.

**Comment by roji** [comment]
@BillWagner @ajcvickers I think this issue can be closed, as we have  dotnet/EntityFramework.Docs#2931 to track better docs on the EF side?

**Comment by BillWagner** [comment]
closing per discussion.
