### ISSUE TITLE
CS0618 ERROR PLEASE RESOLVE IT.

### ISSUE THREAD

**Issue by RjArchitects** [dotnet/docs#21740]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0fc8bd-b6e8-4c3e-7bb1-877fac21e866
* Version Independent ID: 42f43c1e-556a-fca6-f057-4a4c45937840
* Content: [Compiler Warning (level 2) CS0618](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CS0618)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0618.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0618.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@RjArchitects Can you give more information on what you need changed here?

**Comment by RjArchitects** [comment]
unreal engine Datasmith 4.26. for 3dsmax is not installing... Windows installer package error.

**Comment by IEvangelist** [comment]
@RjArchitects is this a documentation issue, or an installer issue? In other words, did you follow some docs that instructed you to install something and then you encountered an error? If not, this is probably the wrong place to post this issue. Is there anyway you could provide more details, screenshots, error logs, links to relevant content, etc.?
