### ISSUE TITLE
Which GC flavour should be used for ASP.Net 5 running on kubernetes cluster?

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#21742]
I am still not clear after reading this content which GC flavour to use for my ASP.Net 5 application deployed and running on Kubernetes cluster. Should I bother to configure it or the default is good enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96231e21-39dd-96c1-8d9a-4155dfe19cec
* Version Independent ID: a47c1fd9-176e-f6b3-9d87-0b75f8048523
* Content: [Workstation vs. server garbage collection (GC)](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc)
* Content Source: [docs/standard/garbage-collection/workstation-server-gc.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/workstation-server-gc.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by davidfowl** [comment]
The default is good enough
