### ISSUE TITLE
Document choosing a package source in fsi

### ISSUE THREAD

**Issue by nbevans** [dotnet/docs#21745]
![image](https://user-images.githubusercontent.com/542188/100449260-82fb9a00-30ab-11eb-93ca-0debda9c96fa.png)

![image](https://user-images.githubusercontent.com/542188/100449334-a1619580-30ab-11eb-9cd0-49e98ca7266b.png)

Is there a way to tell it which package source to use?

**Comment by cartermp** [comment]
Doc is here: https://docs.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/

Needs a new section
