### ISSUE TITLE
Add example XML snippet

### ISSUE THREAD

**Issue by isurani** [dotnet/docs#21750]
In this type of pages, having an example input or output XML helps a great deal in quickly understanding it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d605f11-eaa8-8a0d-1727-8a6d5531d6ba
* Version Independent ID: 69554d83-fede-0a01-2549-d9b51503f781
* Content: [How to qualify XML element and XML attribute names](https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-qualify-xml-element-and-xml-attribute-names)
* Content Source: [docs/standard/serialization/how-to-qualify-xml-element-and-xml-attribute-names.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/how-to-qualify-xml-element-and-xml-attribute-names.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion -- we'll add examples the next time we update the article, or you're welcome to submit a PR if you have examples you'd like to contribute.

**Comment by tdykstra** [comment]
Thanks for the suggestion, but we don’t have the resources to invest in this area, so we are closing the issue. If we get more 👍 responses to the issue, we’ll reconsider.
