### ISSUE TITLE
Offer very detailed examples for library authors

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/docs#21759]
_(Directed here from https://github.com/dotnet/AspNetCore.Docs/issues/20799)_

I'm having a difficult time piecing together exactly how library authors should be leveraging the options pattern.

Ideally a whole section of examples where the options pattern is configured/leveraged from within `IServiceCollection` extension methods would really be helpful.

It would be nice to see every technique detailed, including individual and combinations of: 

 - How to leverage strongly typed configuration data while registering services
 - How to allow users to provide their own `Action<OptionsType>` on top of configuration obtained from the options pattern
 - How to establish a default `.Configure` for conventions based section binding
 - Any way to work with `IConfiguration` without requiring users to pass it in to extension methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Additional details from @atrauzzi, imported from his [Gist](https://gist.github.com/atrauzzi/a22105f946050e8f9d404525aa92c6c3):

```csharp
public class MyStronglyTypedOptions()
{
    public string FieldOne { get; set;}
    public string FieldTwo { get; set;}
    public IEnumerable<string> FieldThree { get; set;}
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddUsingMyExtensionMethod(/* ! */);
    }
}

public static class MyIServiceCollectionExtensions()
{
    public static IServiceCollection AddUsingMyExtensionMethod(this IServiceCollection services)
    {
        // note: The puzzle here is what's the best way to get the instance?
        MyStronglyTypedOptions myStronglyTypedOptions;
    
        services.AddSomeOtherService((thatServicesOptions) =>
        {
            thatServicesOptions.Something = $"{myStronglyTypedOptions.FieldOne}-{mystronglyTypedOptions.FieldTwo}";
        });
    
        return services;
    }
}
```

> The only way I can see `AddUsingMyExtensionMethod` being possible right now is to just outright take an instance of `MyStronglyTypedOptions`. But that then puts the burden on the caller to create it and doesn't leverage all the power of config and options.
>
> What would be nice is if there's some way to bind new services while making use of the options pattern. Somewhere between the last configuration for the container, and when .NET actually builds it for use.
>
> Unfortunately, the only way I could see that being helpful is if some kind of "get option early" functionality was available from `IServiceCollection`. Which could be considered outside of its scope, except that the config being obtained is strictly for the purpose of registering more services.

**Comment by atrauzzi** [comment]
@IEvangelist - Unfortunately I don't think one of my biggest questions was answered here, which is: How do I make use of values from options during service registration?

**Comment by IEvangelist** [comment]
> @IEvangelist David Pine FTE - Unfortunately I don't think two of my biggest questions was answered here, which are:

@atrauzzi -- I'm sorry to hear that. Let me see what I can do.

> * How do I make use of values from options during service registration?

The only way to do that is manually walking up to [the `IConfiguration` instance](https://docs.microsoft.com/dotnet/core/extensions/options-library-authors#iconfiguration-parameter), and asking for values. Ideally, these would be well known, defined clearly to avoid ambiguity, and discoverable. For example, if your service had an options class:

```csharp
namespace Alexander.Trauzzi.Service
{
    public class ConfigOptions
    {
        public bool IsExperimentalFeaturesOn { get; set; }
        public TimeSpan Timeout { get; set; }
    }
}
```

Then you're services that rely on these options:

```csharp
namespace Alexander.Trauzzi.Service
{
    public class SampleService
    {
        public SampleService(IOptions<ConfigOptions> options)
        {
            var isOn = options.Value.IsExperimentalFeaturesOn;
        }
    }
}
```

Internally, your registration code could require the `IConfiguration` and manually parse values:

```csharp
namespace Alexander.Trauzzi.Extensions
{
    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddTheServices(
            this IServiceCollection services, IConfiguration config)
        {
            var timeout = config["WellKnownKeyToTimeout"];
            if (timeout is { Length: > 0 } && TimeSpan.TryParse(timeout, out var timeoutSpan))
            {
                // Do something with the value...
            }
            return services;
        }
    }
}
```

> * How do I bind a configuration instance _and_ allow people to use an action to modify it?

This is the [`PostConfigure` functionality](https://docs.microsoft.com/dotnet/core/extensions/options-library-authors#post-configuration).

**Comment by atrauzzi** [comment]
No, I have non-services that I want to leverage strongly typed configuration for.  Many of these are directly as a result of how ASP.NET is architected, or in many cases, are parts of the application that must be configured prior to the DI container being populated.

I basically need a way to resolve the values - whatever they may be - _while configuring services_.

**Comment by atrauzzi** [comment]
I feel like accepting `IConfiguration` as a parameter is effectively an antipattern because it then means that I'm in a position to prescribe where that configuration comes from in the `IConfiguration` system.

Should I just accept an instance of my options type and leave it to the project calling my extension methods to figure out how to obtain it?

**Comment by davidfowl** [comment]
The `IConfiguration` overload would be a convenience. If you take an `IOptions<T>` then the consumer has lots of ways to choose from configuring it. We accept `IConfiguration` with a few APIs where we expect a specific schema that maps to our poco.

**Comment by atrauzzi** [comment]
So there's no way to ask `IOptions` for the value of an options as best it's known at the time of calling (aka: "thus far")?

I'm in a strange situation where I need values both when I'm registering services, as well as within services.  It seems like the options system is capable of handling the 2nd scenario.  But it seems there's no nice way to get values that are necessary prior to my service container even being built...

**Comment by davidfowl** [comment]
That's correct. There's no way to use options before the container is built.

**Comment by atrauzzi** [comment]
Are there any solutions around this?  A good example would be when I'm configuring `ActivitySource` for tracing which I add to DI as a singleton. It accepts two string values, one of which I'd like to be configurable from the environment.

In any .NET project, is there something akin to the options system which offers a nice strongly typed way to pull data from the environment, but prior to the whole application container being built?

**Comment by davidfowl** [comment]
The options system is built on the DI container and there's no clean way to get the options before the DI container is ready. The best you can do is read those string values from configuration. The other thing people tend to do is build another DI container but that has other problems.

**Comment by atrauzzi** [comment]
Indeed, maybe it's just simpler for those few values to pull them directly from the environment using more static-y .NET APIs?

**Comment by davidfowl** [comment]
2 options, let the caller, pass the IConfiguration. That's better than the static. Or do the static thing and I will look at you like this 😞

**Comment by atrauzzi** [comment]
I mean for values I need before the configuration system is booted/bootable...  I don't think I have a choice except to pull it from the environment, do I??

**Comment by davidfowl** [comment]
> I mean for values I need before the configuration system is booted/bootable... I don't think I have a choice except to pull it from the environment, do I??

Or accept IConfiguration and read it from there.
