### ISSUE TITLE
Can't  download patch for Windows 7 Enterprise SP1

### ISSUE THREAD

**Issue by elGuille-info** [dotnet/docs#21769]
The link to download KB2533623 doesn't goes to the file linked:
https://support.microsoft.com/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

I try the download link for:
 **Actualización para Windows 7 (KB2533623) 
Descargar Descargue ahora el paquete Windows6.1-KB2533623-x86.msu.**
(__Update for Windows 7 (KB2533623) 
Download Download the Windows6.1-KB2533623-x86.msu package now.__)

http://www.microsoft.com/downloads/es-es/details.aspx?familyid=c79c41b0-fbfb-4d61-b5d8-cadbe184b9fc&displaylang=es

http://www.microsoft.com/download/details.aspx?familyid=c79c41b0-fbfb-4d61-b5d8-cadbe184b9fc

In the English version say that the this download is no longer available, in the Spanish version simply shows a _commercial page_ :-)

How can I compile in Windows 7 Enterprise SP1?

I try using dotnet from the command line and from an application that runs on Windows 10.
The version of the application is compiled for x86 directrly (no AnyCPU set)

Thanks!
Guillermo
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@elGuille-info Hello. This is being tracked in another issue.

**Comment by adegeo** [comment]
Duplicate of #20459
