### ISSUE TITLE
Difference between '== null' and 'is (not) null' in LINQ

### ISSUE THREAD

**Issue by StevenLiekens** [dotnet/docs#21760]
Hi,

Are these expressions equivalent in LINQ, or does it depend on which LINQ provider is used?

``` csharp
// The tried and tested way
var query1 =
    from c in categories
    where c != null;

// C# 7 pattern matching
var query2 =
    from c in categories
    where !(c is null);

// C# 9 pattern matching
var query3 =
    from c in categories
    where c is not null;
```

Thanks!

/edit: `not null` was added in C# 9, not C# 8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 587562bd-a0f5-0fb5-e9c1-8e6e6e142f2a
* Version Independent ID: 9ed3467f-5274-5c22-fabb-f0ecc47eb5c2
* Content: [Handle null values in query expressions (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/handle-null-values-in-query-expressions)
* Content Source: [docs/csharp/linq/handle-null-values-in-query-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/handle-null-values-in-query-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @StevenLiekens 

This is an area we need to improve. The pattern matching syntax (and some other newer C# features) cannot be part of an expression tree. That means the `is` pattern matching operator cannot be used with a source that supports `IQueryable<T>`, only with a source that is `IEnumerable<T>`.  Here's your sample (slightly modified) and the compiler output in comments:

```csharp
using System.Linq;

var categories = args.AsQueryable();

// The tried and tested way
var query1 =
    from c in categories
    where c != null
    select c;

// C# 7 pattern matching
var query2 =
    from c in categories
    where !(c is null) // error CS8122: An expression tree may not contain an 'is' pattern-matching operator.
    select c;

// C# 8 pattern matching
var query3 =
    from c in categories
    where c is not null // error CS8122: An expression tree may not contain an 'is' pattern-matching operator.
    select c;
```

If you remove the `AsQueryable()` call, all three queries compile and execute as expected.

We should address this behavior by describing what C# syntax isn't allowed in expression trees, and link to that new article from articles like this one pertaining to `null` checks.

**Comment by StevenLiekens** [comment]
Thanks, that answers my question perfectly. I'll leave this open in case you want to use this issue for tracking documentation updates.

**Comment by zspitz** [comment]
I've suggested this in #11348.
