### ISSUE TITLE
In Similarity to WCF section “And as you'll see in chapter 5”. Where is actually chapter 5 in this document?

### ISSUE THREAD

**Issue by chanmmn** [dotnet/docs#21765]
In Similarity to WCF section “And as you'll see in chapter 5”. Where is actually chapter 5 in this document?

---
#### Document Details
URL: https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c10e8b4-f826-f898-fc5b-2ae25aeb54f3
* Version Independent ID: 4c245b0b-11cc-9055-7f03-98fbd52305c2
* Content: [Why we recommend gRPC for WCF developers - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc)
* Content Source: [docs/architecture/grpc-for-wcf-developers/why-grpc.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/why-grpc.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by tdykstra** [comment]
@shirhatti Can you answer this question?
