### ISSUE TITLE
None of these scenarios cover where a single WCF service was exposed via different bindings

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#21771]
It was awesome being able to expose a service using multiple different bindings, and that was very useful in more than one case. These guides (and the suggestion to migrate to gRPC) do not cover this scenario. 

Is it at least possible to have a single asp.net core app that exposes a service via a conventional WebAPI as well as for gRPC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8bf304a-23d9-3b04-e156-a6b4090e5b12
* Version Independent ID: f95dde62-3462-03f5-2ba3-c1a279fb7805
* Content: [Migrate a WCF solution to gRPC - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-wcf-to-grpc)
* Content Source: [docs/architecture/grpc-for-wcf-developers/migrate-wcf-to-grpc.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/migrate-wcf-to-grpc.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
