### ISSUE TITLE
Error in DefaultOperation.cs code

### ISSUE THREAD

**Issue by draco961** [dotnet/docs#21770]
There is something missing in DefaultOperation.cs
NewGuid().ToString()[^4..];

I guess it's :
Guid.NewGuid().ToString()[^4..];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @draco961 - thank you for posting this issue.

I see your concern, however; this is actually perfectly valid C#. It leverages the [`using static` directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static).

```csharp
using static System.Guid;
```

You'll see that in the sample source code as the first line, [see here](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage#add-default-implementation). I'm going to close this for now, if you have any other questions feel free to post another issue. If you'd like more clarification on this issue, feel free to ask.
