### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by curtca** [dotnet/docs#21776]
In the first code snippet with [Theory] (toward bottom of the page), there is a bunch of missing info. You cannot simply do the code replacement as suggested. _primeService is (now) an undefined variable. It looks like this is only one part of a larger change where _primeService is defined in the class constructor instead of in the test method itself. There is no mention of this larger change on the page, so following the steps verbatim leads to broken code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @curtca 

We'll take a look and make the necessary updates.
