### ISSUE TITLE
What are the TFM requirements for analyzers and source generators?

### ISSUE THREAD

**Issue by dferretti** [dotnet/docs#21787]
Could the TFM requirements for analyzers and source generators be added to the docs? I vaguely remember following this tutorial and a few others a long time ago - at the time netstandard2.0 was out and available but IIRC analyzers still needed to be written targeting netstandard1.3. That does seem to have changed but I don't know when exactly that was. Our analyzers have been updated to 2.0 and are still working now. 

Are there similar plans to eventually allow targeting net5? I have found a few hints that it is not currently supported scattered in various github issues but nothing in the docs - this is one example: https://github.com/dotnet/roslyn/issues/47512

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @dferretti We should add this.

Adding @sharwell who can help describe the correct requirements.

**Comment by sharwell** [comment]
Source generators must target netstandard2.0. Analyzers must target netstandard2.0 for Roslyn 3 (VS 2019), or netstandard1.3 for Roslyn 1 (VS 2015) or 2 (VS 2017).
