### ISSUE TITLE
Broken xmldoc URL

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/docs#21816]
```cmd
follow https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments
https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments -> 301
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments -> 404
```

**Comment by gewarren** [comment]
@xtqqczze Where is that link found?

https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments

**Comment by xtqqczze** [comment]
@gewarren The link was in PowerShell documentation:

https://github.com/PowerShell/PowerShell/blob/d47864d4d/docs/dev-process/coding-guidelines.md#commenting-conventions

We closed the PowerShell issue by retargeting to https://docs.microsoft.com/en-gb/dotnet/csharp/programming-guide/xmldoc/ in order to fix CI, which fails when a URL is deleted without a redirect.

**Comment by mletterle** [comment]
Oddly, we also have automated tests that hit at least one of the deleted redirects from #21789 that has started failing.... (specifically `docs/standard/assembly-format.md` in our case)

**Comment by mletterle** [comment]
Another url losing its redirect that we hit regularly: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias

**Comment by xtqqczze** [comment]
According to #21789, `/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments` had zero page views for in the last 90 days.

But [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell) has been making a request to this URL in every run of CI for years (since PowerShell/PowerShell#8471).

In my estimation PowerShell CI alone has made ~1000 requests to this URL in the last 90 days, so I don't see how the page view statistics are accurate.

**Comment by gewarren** [comment]
It seems that when markdown-link-check checks a URL, it doesn't result in a page view being recorded. This query shows that all the hits to xml-documentation-comments in the last 180 days have been in the last 2 days:

PageView 
| where StartDateTime > ago(180d)
| where Url endswith "/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments"
| summarize PageViews=dcount(PageViewId) by ContentId, bin(StartDateTime, 2d)

Results:

ContentId | StartDateTime | PageViews
-- | -- | --
1f0df4b5 | 2020-12-02T00:00:00Z | 22
1f0df4b5 | 2020-12-04T00:00:00Z | 9

So it seems to me that no-one has actually clicked that link in the Powershell docs in the last 180 days (except for in the last couple days after the CI broke), just the markdown-link-check tool. Do you have any thoughts on why the markdown-link-check hit isn't recorded as a page view?

**Comment by RDIL** [comment]
> @iSazonov @RDIL @TravisEz13 Do we know why markdown-link-check hit isn't recorded as a page view?

Is the page view counted server side?

**Comment by iSazonov** [comment]
I guess the page contains a counter and markdown-link-check downloads the page but does not execute a code in the page.

**Comment by RDIL** [comment]
Yeah it doesn't execute JavaScript

**Comment by gewarren** [comment]
I reinstated all the redirects, so this is fixed now.
