### ISSUE TITLE
First example on this page is misleading

### ISSUE THREAD

**Issue by DanPLC** [dotnet/docs#21812]
The first example on this page indicates that the following code:

`Dim length As Integer? = customers?.Length`

is the same as this code:

`Dim length As Integer`
`If customers IsNot Nothing Then`
`    length = customers.Length`
`End If`

That implies that length will not be set to a value if customers is Nothing.  That's not true.  "customers?.Length" is actually equal to Nothing if customers is Nothing.  For instance if you have the following code:

`Dim customers as customer = Nothing`
`Dim length as Integer?`
`length = 10`
`length = customers?.length`

length will be equal to Nothing after executing this code.  The example on this page makes it seem that length is not altered if customers is Nothing.  That would mean length would remain equal to 10 if customers is Nothing.  But in reality, length will be set to Nothing after executing the above code.

So the example on the page should be the following instead:

`Dim length As Integer`
`If customers IsNot Nothing Then`
`    length = customers.Length`
`Else`
`    length = Nothing`
`End If`

This represents what actually happens in the code.  If customers is NOT nothing, length gets set to customers.Length.  If customers is nothing, length gets set to Nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7427bc30-4d66-b234-4537-200d4419cc24
* Version Independent ID: 786cb51a-cd8d-95a7-a11c-c39245a01e9d
* Content: [Null-conditional Operators - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/null-conditional-operators)
* Content Source: [docs/visual-basic/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/null-conditional-operators.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
