### ISSUE TITLE
Unclear difference between partial class and just using a Sub

### ISSUE THREAD

**Issue by flagrange** [dotnet/docs#21825]
Hello,
Reading the page carefully, it still is not clear (to me) why one would use a partial class at all, rather than removing the word `partial` and doing the same.

Or what is the difference between the example given and:

`
         ' Provide a signature for the not-any-more partial method.

        Private Sub QuantityChanged() ' Without Partial

            MsgBox("Quantity was changed to " & Me.Quantity) ' The logic of the not-partial-sub right here rather than elsewhere.

        End Sub

    End Class
`
And everything else the same as in your example.

You say at the top 'they are commonly used to provide notification that something has been changed'. OK, nice, but it seems I do just the same with the non-partial class above.
So I still miss the point of partial classes here. 
Note: the code formatting seems very finnicky and problematic. Can't get this right - sorry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eca92d0-c691-54f2-c6fb-8c9ae631a5e2
* Version Independent ID: 2c56d217-9ca5-060b-c447-f16d04d45cbb
* Content: [Partial Methods - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/partial-methods)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/partial-methods.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/partial-methods.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
@flagrange 

Many of the wizards and templates create partial methods so that you can provide an implementation of the method in a separate file. That prevents the template from overwriting your changes. In practice, you would make the `Sub` in the same file as the other members of a class or module.
