### ISSUE TITLE
Versions do not match as the page indicates it does

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#21833]
This page implies that the version of the SDK will keep in pace with the version of the runtime (except adding the actual patch version of the SDK as two digits after the Runtime patch version.

For .Net Core 3.1 this is NOT the case.  The current version of 3.1 is 3.1.10.  According to this page, the SDK should be 3.1.1004 not what it actually is (3.1.404).

This page should be updated with a strong indicator that it does not apply to version 3.1 of .Net Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Core Runtime and SDK are versioned - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/versions/)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
The SDK version doesn't keep pace with the runtime version in the sense of using the same feature band number for a given runtime patch version number. SDK feature bands are independent of runtime patch number. This is illustrated in the "SDK feature change" row of the sample table, where the runtime stays the same at 2.2.1 but a new feature band 2.2.200 is released for the SDK.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
