### ISSUE TITLE
Missing supported macOS information

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/docs#21842]
The document is missing information about macOS Big Sur support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e
* Version Independent ID: 68d524f7-6cf1-2caa-56d5-f243952d1526
* Content: [Install .NET on macOS](https://docs.microsoft.com/en-us/dotnet/core/install/macos)
* Content Source: [docs/core/install/macos.md](https://github.com/dotnet/docs/blob/master/docs/core/install/macos.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@rbhanda When will we know that macOS 11 Big Sur is supported? I can update this article.

**Comment by rbhanda** [comment]
Hi @adegeo macOS 11 has been in support since October.
