### ISSUE TITLE
Suggest using Microsoft.CodeAnalysis.NetAnalyzers instead of Microsoft.CodeAnalysis.FxCopAnalyzers

### ISSUE THREAD

**Issue by meziantou** [dotnet/docs#21848]
The package `Microsoft.CodeAnalysis.FxCopAnalyzers` is deprecated. The article should recommend using `Microsoft.CodeAnalysis.NetAnalyzers` in the section "Enable code analyzers".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff20a875-d296-266f-8e5b-a3ab32db2491
* Version Independent ID: 1788f46c-cdad-9ea5-7bd7-62c959255fd5
* Content: [Behavior changes when comparing strings on .NET 5+](https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus#feedback)
* Content Source: [docs/standard/base-types/string-comparison-net-5-plus.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/string-comparison-net-5-plus.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
