### ISSUE TITLE
Samples show ApplicationException

### ISSUE THREAD

**Issue by Keboo** [dotnet/docs#21865]
The current sample has several instances where it throws `ApplicationException` however the current guidance on [ApplicationException](https://docs.microsoft.com/dotnet/api/system.applicationexception) is to avoid throwing `ApplicationException` directly.

> You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec519d-b37f-92e2-2526-ad80dfcd82a1
* Version Independent ID: 9576bafa-e207-448d-c947-508d574c7d4e
* Content: [How to: Hook Up a Delegate Using Reflection](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-hook-up-a-delegate-using-reflection)
* Content Source: [docs/framework/reflection-and-codedom/how-to-hook-up-a-delegate-using-reflection.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/how-to-hook-up-a-delegate-using-reflection.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. Yes, that is strange. It should be fixed. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
