### ISSUE TITLE
What format do I have to use in the .txt, for some reason it's not working properly

### ISSUE THREAD

**Issue by junioranheu** [dotnet/docs#21864]
What format do I have to use in the .txt? For some reason it's not working properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @junioranheu ,

Can you please provide more details on what's not working. Maybe paste the error you're getting.

To briefly provide an answer to your question, ML.NET works with various delimited characters. The default is tab-delimited files. For this tutorial, the file extension is `.txt`. However, the file is tab-delimited. You'll notice the [`LoadFromTextFile`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textloadersavercatalog.loadfromtextfile?view=ml-dotnet#Microsoft_ML_TextLoaderSaverCatalog_LoadFromTextFile__1_Microsoft_ML_DataOperationsCatalog_System_String_System_Char_System_Boolean_System_Boolean_System_Boolean_System_Boolean_) method is the one responsible for loading the data. For more information on loading data, you can also check out the [load data how-to guide](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net)

**Comment by junioranheu** [comment]
I used Excel in order to format the text and it worked like a charm

**Comment by luisquintanilla** [comment]
@junioranheu great to hear you got this working. Please feel free to raise any additional issues if you run into any.
