### ISSUE TITLE
<see> in C# Guide doesn't mention inner text, as shown in F# guide

### ISSUE THREAD

**Issue by kevinoid** [dotnet/docs#21885]
In [Document your code with XML comments](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#recommended-tags) in the F# Guide, `<see>` is documented as `<see cref="reference">text</see>` where "The *text* is the text shown in the link."

[`<see>` in the C# guide](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/see) does not document whether inner text is allowed or what behavior it implies.

Is `<see>` inner text permitted in both C# and F#?  (I tested that `<see>` inner text is preserved in the XML documentation file generated from C#.)  In either case, perhaps the C# Guide should be updated to mention it.

Thanks for considering,
Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @kevinoid 

This is a tricky one for us to cover well in the C# docs. The C# compiler respects any XML tags you use. As you say, it will preserve any tags and any text between opening and closing tags.

How those tags are processed when creating human readable documents is up to the tool: docfx, sandcastle, etc. We're working on a plan to provide more details for different document generating tools.

I'll add this to our backlog.

**Comment by kevinoid** [comment]
Sounds good to me.  Thanks @BillWagner!
