### ISSUE TITLE
Your C# 9.0 new features page is a difficult read, as were the original proposals pages. 

### ISSUE THREAD

**Issue by rightwayit** [dotnet/docs#21880]
Your C# 9.0 new features page is a difficult read, as were the original proposals pages. Really clever folk explain things one at a time with no jumps or surprise terms. They make things simple, as in KISS. Microsoft would never have allowed such terse and opaque writing in the past. Sort your lives out guys! :o)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's good feedback @rightwayit 

This article's purpose is to provide a brief overview of the features in C# 9. Other articles, some still in progress, provide more depth on each of the features.  We're tracking that progress [here](https://github.com/dotnet/docs/projects/106).  I'll close this, as duplicated by the tasks in that project.

**Comment by rightwayit** [comment]
If you need more detailed feedback on the pages, I will be delighted to provide it. Arguably, you should have asked for it mind you! :o). I reluctantly have to rebut your explanation - there is no way an "overview"  should be more opaque than the details - so maybe you meant something else, because an overview should, in all good reason, be an easier, friendlier, higher-level read than the details - shouldn't it (the answer I'm looking for is, "Yes. Of course")?

**Comment by rightwayit** [comment]
Hi Bill,


PS. Much respect. I have one of your "effective c#" books right here.


Best regards,


Graham

Graham Bennett (RightWay IT Limited) 07502 545702


[1510153075288_the-open-group-certified-togaf-9-certified.png]

________________________________
