### ISSUE TITLE
Interface member declarations may include any access modifier

### ISSUE THREAD

**Issue by aruncsp** [dotnet/docs#21918]
[Interface member declarations may include any access modifier.](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers#other-types)

Interface members cannot have any access modifiers specified because they are Public by default,  right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking this question @aruncsp 

Interface members are `public` by default. Beginning with C# 8, they may have access modifiers as detailed in the C# 8 proposal for [default interface members](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods#modifiers-in-interfaces).

I'll close this as by-design.
