### ISSUE TITLE
Example code seems duplicated for one option

### ISSUE THREAD

**Issue by mr-katsini** [dotnet/docs#21917]
Under https://docs.microsoft.com/en-us/dotnet/machine-learning/reference/ml-net-cli-reference#classification-options, each example is always `mlnet classification` for each of the Classification options listed instead of `mlnet regression` or `mlnet recommendation`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d546f09c-1e0f-b036-5c93-b0640934bcdd
* Version Independent ID: dcce0234-fb4b-9622-a930-80518e6f50a3
* Content: [ML.NET CLI Command Reference - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/reference/ml-net-cli-reference)
* Content Source: [docs/machine-learning/reference/ml-net-cli-reference.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/reference/ml-net-cli-reference.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @mr-katsini,

Thanks for raising this issue. The issue was resolved by #22145
