### ISSUE TITLE
Typos. 

### ISSUE THREAD

**Issue by mr-katsini** [dotnet/docs#21929]
There is a typo of `libomp` [Here](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies#microsoftmltimeseries-microsoftmlautoml)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f39c5a-b353-4a50-9719-06074465e800
* Version Independent ID: 6e8ac4b9-43a0-84d7-35d2-b9f1bc88a4d9
* Content: [Install extra ML.NET dependencies - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies)
* Content Source: [docs/machine-learning/how-to-guides/install-extra-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-extra-dependencies.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by LeoGaunt** [comment]
I have created a PR to fix this #21955
