### ISSUE TITLE
Regarding updated information for dotnet 5.

### ISSUE THREAD

**Issue by nabodhe** [dotnet/docs#21936]
Page looks pretty good. However this page does not contain latest information for dotnet 5.0

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework & Windows OS versions](https://docs.microsoft.com/en-gb/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The naming seems to have caused a bit of confusion, but .NET 5 is not the next version of .NET Framework after .NET Framework 4.8. It's really the next version of .NET Core. .NET Framework 4.8 is the last version of .NET Framework, as the page states, but it will continue to get monthly security updates.

**Comment by gewarren** [comment]
I'm going to close the issue. If you still think the article needs to be updated, let us know what you think is missing.
