### ISSUE TITLE
Arrays that contain reference types

### ISSUE THREAD

**Issue by matt-rule** [dotnet/docs#21941]
I Google searched for "arrays of nullable reference types c#" because there are some interesting design decisions in this area of .NET. I found [this very informative article](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) on the pitfalls of using nullable reference types. One of these pitfalls is arrays of non-nullable references. While the article is informative in general, there is only a paragraph of information about this particular topic and I feel like there could be more info because I'm currently working with these in my project and trying to work out what options there are.

My request isn't in the exact format you asked for, because I'm not asking for a whole article to be written on this. It would be nice to see a paragraph or two added to the existing article, discussing:

- Why arrays of non-nullable references are initialised to null.
- Why the compiler lets the programmer create an array of non-nullable references without a warning.
- What options you can take / recommended practices to avoid potential issues resulting from non-nullable references being set to null unexpectedly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 350756](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350756)

**Comment by BillWagner** [comment]
That's a great suggestion @matt-rule 

I'll answer what I can briefly here, and we'll add this article to our next set of updates on null safety. 

> - Why arrays of non-nullable references are initialized to null.
There isn't a good alternative. Perf is one reason: all those objects would need to be allocated. All those constructors would need to run. It would also require an accessible default constructor. 
> - Why the compiler lets the programmer create an array of non-nullable references without a warning.
Partially the first answer: there isn't a good way to fix that warning. 
> - What options you can take / recommended practices to avoid potential issues resulting from non-nullable references being set to null unexpectedly.
These are harder. The short version is to avoid the visibility of the array before objects in the array are allocated or initialized. 

I know those answers are incomplete. I hope that helps you get started while we address this with a new article.

**Comment by matt-rule** [comment]
Thank you very much Bill! I know this is off-topic but coincidentally yesterday I bought your book "More Effective C#" from Amazon. Looking forward to a good read!
