### ISSUE TITLE
TextWriterExtensions example is bogged

### ISSUE THREAD

**Issue by EmilianoElMariachi** [dotnet/docs#21940]
In the method

TextWriterExtensions.WriteWithColor(
            this TextWriter textWriter,
            string message,
            ConsoleColor? background,
            ConsoleColor? foreground)

background and foreground args are marked nullable but the methods GetBackgroundColorEscapeCode and  GetForegroundColorEscapeCode throw when null is provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daf7ff20-63e5-215c-047b-92d414eb314b
* Version Independent ID: 6bde6805-1867-ebfc-9773-a792b75318fe
* Content: [Console log formatting](https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter)
* Content Source: [docs/core/extensions/console-log-formatter.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/console-log-formatter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by EmilianoElMariachi** [comment]
Proposal fix:

```csharp
            var backgroundColor = background.HasValue ? GetBackgroundColorEscapeCode(background.Value) : null;
            var foregroundColor = foreground.HasValue ? GetForegroundColorEscapeCode(foreground.Value) : null;

            if (backgroundColor != null)
            {
                textWriter.Write(backgroundColor);
            }
            if (foregroundColor != null)
            {
                textWriter.Write(foregroundColor);
            }

            textWriter.WriteLine(message);

            if (foregroundColor != null)
            {
                textWriter.Write(DefaultForegroundColor);
            }
            if (backgroundColor != null)
            {
                textWriter.Write(DefaultBackgroundColor);
            }
```

**Comment by IEvangelist** [comment]
Hi @EmilianoElMariachi this is a great catch and observation. I would happily welcome you to create a pull request to fix this code - if you'd rather not, I'll take care of it. Please let me know. Thanks again

**Comment by EmilianoElMariachi** [comment]
Thank you, I'll try to make it during the day.

**Comment by EmilianoElMariachi** [comment]
One question (I know what conceptually is a pull request, but I never created one): is it mandatory for me to fork the repository ? Or are there any specific branch names allowed to push for that purpose?

**Comment by ol65** [comment]
if (logEntry.Exception is null)
            {
                //return;                                   // commented out, because I also want to log messages without extensions
            }
I have to comment out the return in the override write method.

**Comment by ol65** [comment]
public override void Write<TState>(
            in LogEntry<TState> logEntry,
            IExternalScopeProvider scopeProvider,
            TextWriter textWriter)
        {
            if (logEntry.Exception is null)
            {
                //return;                                   // commented out, because I also want to log messages without extensions
            }

            string message =
                logEntry.Formatter(
                    logEntry.State, logEntry.Exception);

            if (message == null)
            {
                return;
            }

            CustomLogicGoesHere(textWriter);
            textWriter.WriteLine(message);
        }

Sorry, to less information :)
