### ISSUE TITLE
add a good code example

### ISSUE THREAD

**Issue by waltiam** [dotnet/docs#21942]
That is a wonderful example of what **not to do** code ... can there be an equally wonderful example of what a good usage would looks like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd51b02-9292-c4a7-d72b-e370a4e3221f
* Version Independent ID: ce19799f-ba27-87df-8fdf-37a54c64de6e
* Content: [Resolve assembly loads](https://docs.microsoft.com/en-us/dotnet/standard/assembly/resolve-loads)
* Content Source: [docs/standard/assembly/resolve-loads.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/resolve-loads.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @waltiam - that is a good callout. I'll work on adding the bits that avoid the recursion called out in this article.
