### ISSUE TITLE
C# FAQ link is broken

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2195]
Customers are complaining that the link to C# FAQ is broken at https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/index

My question is, should we update the FwLink (or just the link) to go somewhere else? Or just remove that entry?

There is this link on the blogs site: https://blogs.msdn.microsoft.com/csharpfaq/ but it doesn't seem to be used recently.

**Comment by BillWagner** [comment]
That page clearly hasn't been used in quite a while.

There are a lot of possible locations:

- Issues on the [Roslyn Repo](http://github.com/dotnet/roslyn/issues)
- Issues on the [CSharpLang Repo](http://github.com/dotnet/csharplang/issues)
- The [Tour of C#](https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/) has a lot of introductory information.
- The [C# tag on StackOverflow](http://stackoverflow.com/questions/tagged/c%23)

We could add a FAQ page on docs, but I'd like to seed that with common questions that developers need answered. Any ideas on how to generate that?

Any of those could work.  @MadsTorgersen, what do you think?

**Comment by mairaw** [comment]
Closing this one. No longer applicable and temporary hidden link was permanently removed.
