### ISSUE TITLE
App confing, host config?

### ISSUE THREAD

**Issue by Slavuta851109** [dotnet/docs#21968]
Don't understand diff between app configuration and host configuration are these 2 different and can use different json files?
Is there priority?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9
* Version Independent ID: 22a12ff8-d2ff-a841-b9bb-e2fd1032bc04
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host)
* Content Source: [docs/core/extensions/generic-host.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/generic-host.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
They are separated by extension methods. The host configuration is specifically for the host itself, whereas the app is your app - if that helps to distinguish between the two?

The [host configuration](https://docs.microsoft.com/dotnet/core/extensions/generic-host#host-configuration) can use a *hostsettings.json* file, and exposes configuration of the `IHostEnvironment`. You can change things like base directory, env var prefixes, etc.

The [app configuration](https://docs.microsoft.com/dotnet/core/extensions/generic-host#app-configuration) is much more extensive. This is the primary concern of most applications, see [Configuration in .NET](https://docs.microsoft.com/dotnet/core/extensions/configuration).

> Is there priority?

They are a different set of configurations, however; host is configured first as it flows into the app config. Does that make sense?
