### ISSUE TITLE
This page is inconsistent with dotnet test -h

### ISSUE THREAD

**Issue by terryspitz** [dotnet/docs#21962]
Page says 
dotnet test <PROJECT | SOLUTION> [options]

dotnet test -h says:
Usage: dotnet test [options] <PROJECT | SOLUTION> [[--] <RunSettings arguments>...]]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
They both show the same syntax but formatted differently. Options may be entered before or after arguments on the command line, and they are generally shown after the arguments in the online documentation. The  `[[--] ...]]` part is covered as `[[--] <RunSettings arguments>]` in the documentation.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
