### ISSUE TITLE
Example code error in C# 9.0 Function Pointers

### ISSUE THREAD

**Issue by acaly** [dotnet/docs#21969]
In the second code block of the section "Allow instance methods":

```c#
static string toString(Instance i) = i.ToString();
```
should be 
```c#
static string toString(Instance i) => i.ToString();
```

and 
```c#
delgate*<Instance, string> f = &toString;
```
should be
```c#
delegate*<Instance, string> f = &toString;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6240d621-9b08-a9b9-ceed-5e4fd76a73a0
* Version Independent ID: 336fb56d-9797-e1e2-b623-a31a804cfecd
* Content: [Function pointers - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers)
* Content Source: [proposals/csharp-9.0/function-pointers.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/function-pointers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Do you want to open a Pull Request to fix those? The easiest way to do that is [to use the Edit button](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).
