### ISSUE TITLE
Thanks for helpful guide!

### ISSUE THREAD

**Issue by aeshkevari** [dotnet/docs#21972]
Hi,

Thank you for your clear and helpful guide about enabling Framework 3.5 from Win10 Control Panel.

Regards,
Ali

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install .NET Framework 3.5 on Windows 10, 8.1, 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for the compliments!
