### ISSUE TITLE
Must thread handles returned by ICorProfilerInfo::GetHandleFromThread be closed?

### ISSUE THREAD

**Issue by tzehetner** [dotnet/docs#21970]
The documentation should clarify, if thread handles returned by ICorProfilerInfo::GetHandleFromThread must / must not be closed by the caller.

I found a call to ICorProfilerInfo::GetHandleFromThread with the comment "don't close this clr managed handle!" in our code base, but couldn't verify, if this is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb6ca0-48d2-431d-87d2-0d961bb641de
* Version Independent ID: 3f6bfce5-4882-7523-4d4a-113f66a09fb1
* Content: [ICorProfilerInfo::GetHandleFromThread Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-gethandlefromthread-method)
* Content Source: [docs/framework/unmanaged-api/profiling/icorprofilerinfo-gethandlefromthread-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/profiling/icorprofilerinfo-gethandlefromthread-method.md)
* Product: **dotnet-framework**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by sywhang** [comment]
@davmason can you confirm that the handle returned from `GetHandleFromThread` shouldn't be closed?

**Comment by davmason** [comment]
The handle that is returned is owned by the runtime and you should definitely not close it.

**Comment by tzehetner** [comment]
Thanks!
