### ISSUE TITLE
overload both == and !=

### ISSUE THREAD

**Issue by bghaemi1379** [dotnet/docs#21986]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed7f074-cf34-7ccd-9ace-6c5d255cf287
* Version Independent ID: 92a50f72-a533-c08a-f106-d0c42129ea83
* Content: [Compiler Error CS0216](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0216)
* Content Source: [docs/csharp/misc/cs0216.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0216.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @bghaemi1379 

The example of `==` and `!=` is a more common code example for this situation.

I've added this to our backlog to address when we next update this article.

**Comment by BartoszKlonowski** [comment]
I would like to handle this.
@BillWagner Please assign me to this issue.

**Comment by BillWagner** [comment]
Thank you @BartoszKlonowski I've just assigned this to you. I'll watch for a PR.
