### ISSUE TITLE
For ubuntu 20.04 and above, dotnet can be very simply installed by '''sudo snap install dotnet-sdk'''. This is far simpler than any other method I think and it should be updated in the docs.

### ISSUE THREAD

**Issue by Ritvik-Sapra** [dotnet/docs#21988]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for the suggestion. There is a section that specifies Snap instructions. Are you saying that these are wrong?

**Comment by adegeo** [comment]
I just double checked the instructions for installing via Snap and they're correct. If there is something else you need please feel free to comment or reopen this issue. Cheers!

**Comment by Ritvik-Sapra** [comment]
Oh, I didn't see the Snap section. This was the first one that came in front. I checked them too and they are correct. I just thought if they are not added, I should suggest. Thanks for reviewing!

**Comment by adegeo** [comment]
Sure thing. I'm working on an update to these that pulls snap into it's own article and then links to it near the top. This hopefully will lessen the length of the article and make it easier to find things like this.
