### ISSUE TITLE
‌Broken link

### ISSUE THREAD

**Issue by seekasra** [dotnet/docs#21985]
**Issue description**

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework

The link to "contributing guideline" is broken. (the broken link: https://github.com/seekasra/core-docs.fa-IR/blob/master/CONTRIBUTING.md)

The link can be found on https://github.com/MicrosoftDocs/core-docs.fa-IR and other core-docs.*
<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
cc @JasonCard 

Can you speak to when the translations will be regenerated from the `en-us` source? The link is updated in the original text.

**Comment by JasonCard** [comment]
Hi @seekasra, please ignore the repo [https://github.com/MicrosoftDocs/core-docs.fa-IR](https://github.com/MicrosoftDocs/core-docs.fa-IR). It was created as test and not used. 
For .NET Core Docs content, please refer to [https://github.com/dotnet/docs](https://github.com/dotnet/docs). That contain is localized for example in [https://github.com/dotnet/docs.de-de](https://github.com/dotnet/docs.de-de) for German. However, please also note that this content is not localized into “Persian (Iran)” (fa-IR).
cc @BillWagner

**Comment by seekasra** [comment]
Thanks for the update. Do you agree on a contribution to create and improve docs.fa-IR? under dotnet repository?

**Comment by JasonCard** [comment]
Thank you again for your suggestion. We currently do not plan to localize into “Persian (Iran)", but will take this request into consideration for the future.

**Comment by seekasra** [comment]
Alright. Cheers.
