### ISSUE TITLE
Add the linux-musl-arm64 RID to the list

### ISSUE THREAD

**Issue by gingters** [dotnet/docs#21987]
I the documentation there is the `linux-musl-arm64` RID missing.

This is to be used if you build docker images for ARM64v8 and the minimalistic base images like
`mcr.microsoft.com/dotnet/runtime-deps:3.1-alpine-arm64v8`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime Identifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
I see it in the **Linux RIDs** section, in the **Portable** section of the list:

>`linux-musl-x64` (Lightweight distributions using musl like Alpine Linux)

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by adamburgess** [comment]
@tdykstra linux-musl-**arm**64 is not in the list.

It is available in the runtimes.json:

https://github.com/dotnet/runtime/blob/752d396519446c13c40738d1c3adfe7fef27a7fa/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L1495
