### ISSUE TITLE
Is it DownloadStringTaskAsync to address the demo when introduce the TAP.

### ISSUE THREAD

**Issue by kevinchengcz** [dotnet/docs#21982]
[Enter feedback here]
just wondering if the mentioned DownloadStringAsync in the artical should be DownloadStringTaskAsync for introduction on task-based asynchronous pattern? Kindly pls review and feedback. Thx a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabcc3ba-9033-c65f-8969-482a436d510b
* Version Independent ID: a74714e2-d059-e33f-a8c6-591d988ef2a4
* Content: [Consuming the Task-based Asynchronous Pattern](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern)
* Content Source: [docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
@kevinchengcz Thanks for pointing that out, you are correct. We'll fix it the next time we're updating the article, or you're welcome to submit a PR if you'd like to.
