### ISSUE TITLE
Figure 4-17 Annotation Inconsistent w/ Image

### ISSUE THREAD

**Issue by clarkbrent** [dotnet/docs#21981]
Hello,

I imagine this is probably just a small typo, but Figure 4-17's text annotation -- "One-to-one real-time asynchronous message communication" -- seems to be inconsistent with what Figure 4-17's image diagram and text show, "One-to-many communication".

Direct link to section:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture#push-and-real-time-communication-based-on-http

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: fbeadc16-d9e1-91cf-5da6-1d76fc800d3e
* Content: [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @clarkbrent , yes that's right. Good catch 👍 
Would you like to submit a PR to the [docs](https://github.com/dotnet/docs) repo ?
