### ISSUE TITLE
Breaking change doc for char deserialization incomplete

### ISSUE THREAD

**Issue by layomia** [dotnet/docs#21998]
The doc suggests that failure will only happen when a `char` is the root type to be deserialized, and that only one deserialization overload is affected. The failure will occur anywhere in the object graph and all deserialization overloads are affected. cc @tdykstra 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a95431a-352f-67d8-c1d4-0b059f7f4155
* Version Independent ID: b1e067fe-873e-5895-10da-1f2e8e3f610a
* Content: [Breaking change: Deserialize requires single-character string - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/deserializing-json-into-char-requires-single-character)
* Content Source: [docs/core/compatibility/serialization/5.0/deserializing-json-into-char-requires-single-character.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/serialization/5.0/deserializing-json-into-char-requires-single-character.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I based the doc on https://github.com/dotnet/docs/issues/20815. Not sure if I misunderstood it. @tdykstra do you want to take a stab at the updates required?
