### ISSUE TITLE
Error with newtonsoft.json reference with a mided core with xamarin solution

### ISSUE THREAD

**Issue by Gustavoaz** [dotnet/docs#2199]
Hey guys im trying to reference a core project (with newtonsoft.json) inside a portable xamarin project. but i get this error.
Exception while loading assemblies:
System.IO.FileNotFoundException: Could not load assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Perhaps it doesn't exist in the Mono for Android profile?
any ideia about what is happening?

**Comment by GuardRex** [comment]
@Gustavoaz Hello! This is the repo for issues with documentation. You can ask in the Xamarin forums at https://forums.xamarin.com/categories/cross-platform or get chat help at Xamarin Slack (self sign-up: https://xamarinchat.herokuapp.com/ ). There's a good general post for getting Xam support help here: http://xamarinhelp.com/how-to-get-support-from-xamarin/

**Comment by mairaw** [comment]
Oi @Gustavoaz!
 
I'm closing this issue since it's not related to the documentation. @GuardRex already provided some ways you can find help.

Adding @mhutch here in case she knows a better spot/person to ask this kind of question.

**Comment by mhutch** [comment]
Hi! Newtonsoft.Json (aka Json.NET) is not part of the BCL, it's a NuGet package you need to reference from your project.
