### ISSUE TITLE
Several links in the dotnet-help command are not working

### ISSUE THREAD

**Issue by livarcocc** [dotnet/docs#2200]
_From @mikkelbu on May 12, 2017 21:52_

## Steps to reproduce
* dotnet help store
* dotnet help vstest
* dotnet help restore
* dotnet help remove
* dotnet help list
* dotnet help help
* dotnet help add
* dotnet help complete
* dotnet help parse

## Expected  behavior
Each command opens up the relevant page on https://docs.microsoft.com/en-us/dotnet/articles/core/tools/

## Actual behavior
* dotnet help store => link (https://aka.ms/dotnet-store) opens the right link (https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-store), but there is not content
* dotnet help vstest => link (https://aka.ms/dotnet-vstest) is not forwarding to https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-vstest
* dotnet help restore => link (https://aka.ms/dotnet-restore) forwards to https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-pack and not to the restore command
* dotnet help remove => link (https://aka.ms/dotnet-remove) is not forwarding to either https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-remove-reference or https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-remove-package
* dotnet help list => link (https://aka.ms/dotnet-list) is not forwarding to https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-list-reference
* dotnet help help => link (https://aka.ms/dotnet-help) does not work (should probably point to https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet)
* dotnet help add => link (https://aka.ms/dotnet-add) is not forwarding to either https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-add-reference or https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-add-package
* dotnet help complete => opens cmd
* dotnet help parse => opens cmd

## Environment data
```
.NET Command Line Tools (2.0.0-preview2-006065)

Product Information:
 Version:            2.0.0-preview2-006065
 Commit SHA-1 hash:  7f50f322d5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\src\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview2-006065\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f
```

_Copied from original issue: dotnet/cli#6587_

**Comment by livarcocc** [comment]
@mairaw can you please take a look?

**Comment by livarcocc** [comment]
_From @mairaw on May 18, 2017 18:38_

Yes, I'll take care of this. Some we don't have the pages for it and I don't know whether we want to have those (for example, dotnet add), so we need to choose a target. For store, we need to finish our PR to add that new command to our docs.

**Comment by mairaw** [comment]
The links are now working although some are going to a temporary location for now. Thanks for reporting this @mikkelbu!

@livarcocc for the last two bullet points, I don't think those are documentation issues. You need to fix that on your side, no? Do we need to reopen the original issue or open a new one just for that?

**Comment by livarcocc** [comment]
For the last two bullets, they are not really customer facing commands. Complete is used for command line completion and parse is used to help us when making changes to our parser. I am fine with these two not having page for them. I don't think they should.

**Comment by mairaw** [comment]
I  agree. But should it open a new command window when you type help? I think it just shouldn't do anything.

**Comment by mairaw** [comment]
@livarcocc should I open an issue just for those two lines that are opening a cmd? shouldn't they just print help like the others?

**Comment by mairaw** [comment]
Keeping it open until we publish the dotnet store page. So the aka.ms link should be updated.

I'll follow up with @livarcocc offline to see what to do about the two last bullet points. I think it's a CLI bug that they're opening a new command window.

**Comment by mairaw** [comment]
issues with the cmd are being tracked at https://github.com/dotnet/cli/issues/7065

**Comment by mairaw** [comment]
With all the new commands pages published, aka.ms links were reviewed and this issue can be closed. Thanks for reporting this @mikkelbu!
