### ISSUE TITLE
See the list of tools in the natemcmaster/dotnet-tools GitHub repository.

### ISSUE THREAD

**Issue by woutervanranst** [dotnet/docs#22025]
FYI natemcmaster now works at AWS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET tools - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@woutervanranst Thanks for the reminder - we were leaving the link in until the search tool was released, and now that it's released we can remove this link.
