### ISSUE TITLE
Base class example in C#, derived class example in VB

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22039]
Moved issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5580](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5580), opened by @Bosch-Eli-Black

On this page, the code for the base class (`TypeA`) is written in C#, but the example for the derived class (`TypeB`) is in VB. This feels kind of odd.

Additional comments by Bosch-Eli-Black:

I suppose that ideally, each example would have both C# and VB variants, with the option for the user to choose which language he wants to view the samples in, as is done on some other pages :D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e8200c-6283-341c-28d6-889bc776b4de
* Version Independent ID: fd8cf98d-be1c-8265-a5c8-da1d17b29d1d
* Content: [CA2215: Dispose methods should call base class dispose (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2215)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2215.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2215.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@gewarren This was fixed in #23196. Can you close?
