### ISSUE TITLE
CA1062 giving false warning when nullables are enabled

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22031]
Moved issue from Visual Studio repo to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5866](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5866), opened by @DrGriff

Regarding [CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062)

This is giving me a false positive warning in an ASP.NET Core MVC application.  

This happens with **.Net Core 3.1** and with **.Net 5** (5.0.100-rc.1.20452.10) when using `<Nullable>enable</Nullable>`.

### In more detail....
My application uses the Azure ADFS Workplace sign-on, and has the latest FxCop and StyleCop Roslyn analzers (**as an aside**, am I right that we no longer need to add the NuGet package `Microsoft.CodeAnalysis.FxCopAnalyzers` with .Net 5?).

I have a method (in a different class) with the following signature:
```
public async Task<SomeResponse> DoSomethingAsync(IIdentity identity)
```
And in that method the following code:
```
string? adfsUpn = identity.Name;
```
However, I'm getting a **CA1062** warning (error in my case as I treat all warnings to errors) saying that:

> Error CA1062 In externally visible method [...], validate parameter 'identity' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.

However, if I put in a test to check for null, _e.g._
```
if (identity == null)
{
    .....
}
```
then I see that `identity` can not be null and that `identity == null` will always be false (as it should be with nullables set).

In addition to this, if I look in my Controller code (where this is called):
```
var response = await this.InstanceOfClass.DoSomethingAsync(this.User.Identity).ConfigureAwait(false);
```
then:

- when using `.NetCore 3.1`, intellisense informs me that `this.User` and `this.User.Identity` are both never not null
- when using `.Net 5`, intellisense informs me that ``this.User.Identity` may be null and that I can't pass a potentially null value to a method that doesn't allow nulls.

### Summary

1. CA1062 is giving me what looks like a false warning in my method (.Net Core 3.1 and .Net 5)
2. With .Net Core 3.1, the intellisense in the Controller tells me that the object I'm about to pass down is NOT null (which I think is correct)
3. With .Net 5, the intellisense in the Controller tells me that the object I'm about to pass down might be null (which I think is not correct)

Thank
---
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ee01ce-a46f-74b6-eccc-9c9f69c74adf
* Version Independent ID: c1d3f414-e493-d3a2-6b7c-729ff3fcc53b
* Content: [CA1062: Validate arguments of public methods (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1062.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1062.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by sharwell** [comment]
> then I see that identity can not be null and that identity == null will always be false (as it should be with nullables set)

Nullable reference types helps prevent callers from passing `null`, but does not guarantee it. Public APIs need to validate arguments even if Nullable Reference Types is enabled and the parameter is declared as non-nullable.

**Comment by gewarren** [comment]
@DrGriff I'm going to close this issue as answered (i.e. it's not a false positive).

For future reference, you can log issues against analyzers at https://github.com/dotnet/roslyn-analyzers.
