### ISSUE TITLE
Examples and explanation needed

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22037]
Moved this issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5755](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5755), opened by @HugoRoss

I think this whole rule needs some examples of how and why such ambiguities may occur and a good explanation why it contradicts everything that was preached the last 30 odd years. It was always the rule to convert to lower-case as there are more lower-case letters than upper-case ones and therefore some information might get lost when converting to upper-case.

Example: The German lower-case "ß" sign is converted to "SS" in all 8-bit codepages and one could not determine whether the word "MASSE" is the upper-case of "Maße" (dimensions) or "Masse" (ground/mass/matter), therefore to avoid such an ambiguity it was recommended to always convert to lower-case.

Please add some examples why in Unicode the opposite might happen and why converting to upper-case is no problem (e.g. if Unicode would define more upper-case letters than lower-case ones and it is guaranteed that every lower-case letter has an upper-case letter defined).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3894a92-71f2-1eb3-6384-54e0d034570a
* Version Independent ID: 06a39aec-f6d4-5ccb-152b-521e8af3c4bb
* Content: [CA1308: Normalize strings to uppercase (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1308)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1308.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1308.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@hugoross I found this info [here](https://gingter.org/2018/07/10/how-to-correctly-normalize-strings-and-how-to-compare-them-in-net/):

"The issue with lowercase normalization is, that there are, again, different cultures where this loses information or ends up in an incorrect representation of the original data. The most prominent example is the Turkish letter İ. This is a I with a dot. This corresponds to the normal i we know. The thing is that our I also gets converted to i when you normalize to lowercase. So, after normalization you can't tell if the original character was an İ or an I. Besides that, the Turkish culture also has an dotless i, which looks like ı and is the correct lowercase version of the Turkish I.

This is not only a problem with Turkish texts. There are also other examples for characters that can't be correctly converted back to their uppercase representation when you normalize to lowercase. One of them is the Greek Rho Symbol (U+03f1) ϱ which uses the Capital Greek Rho (U+03a1) Ρ for uppercase and the Small Greek Rho (U+03c1) ρ in lowercase."

Any updates we make here should probably go in https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings. I'll add a link there from the CA1308 article now.

**Comment by HugoRoss** [comment]
Thank you for these explanations.

Does this mean that the opposite is not the case anymore, that lower-case
letters like the German "ß" are converted to "SS" when upper-cased which
then would be lower-cased to "ss"?

**Comment by gewarren** [comment]
> Does this mean that the opposite is not the case anymore, that lower-case
letters like the German "ß" are converted to "SS" when upper-cased which
then would be lower-cased to "ss"?

It appears that the `ß` character does round-trip correctly.

```
string text = "straße";
string upper = text.ToUpperInvariant();
string lower = upper.ToLowerInvariant();

Console.WriteLine($"To upper: {upper}");
Console.WriteLine($"To lower: {lower}");
```

Output:

To upper: STRAßE
To lower: straße

**Comment by gewarren** [comment]
I did some more experimenting and found, at least with the Turkish İ and ı characters, that normalizing using either String.ToUpperInvariant() or String.ToLowerInvariant() is able to roundtrip correctly. I think problems can creep if you use String.ToUpper() and String.ToLower().

Now that this article (CA1308) is linked to https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings, which states the ToUpperInvariant() is the standard way to normalize case, I'm going to close this issue.

"ToUpperInvariant is the standard way to normalize case. Comparisons made using StringComparison.OrdinalIgnoreCase are behaviorally the composition of two calls: calling ToUpperInvariant on both string arguments, and doing a comparison using StringComparison.Ordinal."
