### ISSUE TITLE
CA1812: Avoid uninstantiated internal classes

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22038]
Moved issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5683](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5683), opened by @nirrave

In Basic there is no shared class and module, which promoted, is a bad idea for a friend class to specific use. So do some about, because suppressing the message does not work.

Additional comments by nirrave:

Replacing a friend class with a friend module, which is promoted and exposed outside the "everywhere", is a bad idea when it intended for specific use within a specific scope. Such as: Debugger Type Proxy class, helper class, class extensions or dependency property change methods, that are classes just to not exposed their methods outside their scope.

By the way,
Yesterday I got the VS 16.7 update and suddenly the CA1812 suppress is working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d34eee1-2619-6701-31e2-7d56cc690ebb
* Version Independent ID: 8a9b0c36-3000-7b71-c0f2-a5b01e54174f
* Content: [CA1812: Avoid uninstantiated internal classes (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1812.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1812.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nirrave I'm not sure what you're asking for here.

- Are you asking that rule CA1812 doesn't examine the classes you mentioned (e.g. debugger type proxy class and helper class)? - Or are you asking that the documentation specifically mention that it's safe to suppress a CA1812 warning on such classes?
- Or are you asking that (something) doesn't promote converting the class to a module in VB? If so, is CA1812 suggesting you convert to a module?
