### ISSUE TITLE
This rule must be suppressed when implementing IXmlSerializable

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22034]
Moved issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5797](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5797), opened by @viniciusvillas

The method `GetSchema` inherited from `IXmlSerializable` does not fit any of the described exceptions on the article (listed below). Nonetheless, it's impossible to adhere to these rules when implementing `System.Xml.Serialization.IXmlSerializable`, because the method *must* be implemented.

- The method performs a time-consuming operation. The method is perceivably slower than the time that is required to set or get the value of a field.
- The method performs a conversion. Accessing a field does not return a converted version of the data that it stores.
- The Get method has an observable side effect. Retrieving the value of a field does not produce any side effects.
- The order of execution is important. Setting the value of a field does not rely on the occurrence of other operations.
- Calling the method two times in succession creates different results.
- The method is static but returns an object that can be changed by the caller. Retrieving the value of a field does not allow the caller to change the data that is stored by the field.
- The method returns an array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a179bb9e-510b-27ca-0bd9-4cca0d253faf
* Version Independent ID: 0fa225dd-442f-0fd6-31ff-f14d8e8c8b22
* Content: [CA1024: Use properties where appropriate (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1024)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1024.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1024.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@viniciusvillas Could you log a bug at https://github.com/dotnet/roslyn-analyzers? See https://github.com/dotnet/docs/pull/22113#discussion_r546993267.
