### ISSUE TITLE
For VB Contract.ThrowIfNull does not supress CA1062

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22041]
Moved this issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/3860](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3860), opened by @paul1956

See issue **3860** for full discussion.

Original comments:

Adding a Code.Contract Precondition as the error/warning instructions say does not suppress CA1062
```VB
 Public Function ConvertInputRequest(RequestToConvert As ConvertRequest) as Boolean
    Contract.ThrowIfNull(RequestToConvert,$"{NameOf(RequestToConvert)} cannot be Nothing")
    Dim languages As String() = {RequestToConvert.GetSourceExtension, RequestToConvert.GetTargetExtension}
```
The following does work to suppress the warning.
```VB
If RequestToConvert Is Nothing Then
    Throw New ArgumentException
End If
```
Also the message says Null Vs. Nothing where other messages gives separate instructions for VB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ee01ce-a46f-74b6-eccc-9c9f69c74adf
* Version Independent ID: c1d3f414-e493-d3a2-6b7c-729ff3fcc53b
* Content: [CA1062: Validate arguments of public methods (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1062.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1062.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The CA1062 docs do not mention contracts anywhere, so I'm going to close this issue.
