### ISSUE TITLE
Advice on how to implement comparison operators for a type whose CompareTo is inconsistent with Equals

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#22044]
Moved issue to .NET
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/3728](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3728), opened by @peteroupc

For full discussion, see **3728**.

This page should include advice on how comparison operators should be implemented in the following circumstance.

- A custom number class (not from the base class library) represents a number by its significand and exponent.
- It overrides Object.Equals with a method that compares the significand and exponent for equality.
- It has a CompareTo method that does a numerical comparison of the two numbers, which is a non-total ordering that is inconsistent with Equals.
- It implements the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators to do comparisons that are consistent with CompareTo.

Should it implement the "==" and "!=" operators to be consistent with Equals or with CompareTo, or should it refrain from implementing those operators?

What if CompareTo instead does a total ordering of the two numbers (making it consistent with Equals)?  Can it implement the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators to do a numerical comparison rather than a total ordering, if a numerical comparison makes more sense?  If so, should the "==" and "!=" operators be implemented to be consistent with Equals, with a non-total comparison, or with a total ordering comparison, or not be implemented?

For the purpose of this issue, an example of the number class is found in my library's EDecimal class ([EDecimal.cs](https://github.com/peteroupc/Numbers/blob/master/Numbers/PeterO/Numbers/EDecimal.cs), [EDecimalExtra.cs](https://github.com/peteroupc/Numbers/blob/master/Numbers/PeterO/Numbers/EDecimalExtra.cs)), except that it doesn't implement the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators at the time of this writing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fdfc4f-e55f-9706-5d5e-b60b1ec9fb37
* Version Independent ID: 9584f8bb-0dbf-cb31-5499-f11541f0f9a4
* Content: [CA1036: Override methods on comparable types (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1036)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1036.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1036.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by svick** [comment]
Personally, I think that the guidance should be that `Equals` and `CompareTo` should be consistent. If you choose to make them inconsistent, then you're on your own and you need to decide yourself how to handle that. The documentation shouldn't help you with that.

**Comment by gewarren** [comment]
@svick I like that. I'm going to close this issue now.
