### ISSUE TITLE
String output from code example does not for right of the bat - code example needs to be corrected

### ISSUE THREAD

**Issue by m-kinchin** [dotnet/docs#22052]
Piece of code below cannot be executed in VSCode
```
printfn %"{name} in Pig Latin is: {newName}"
```
It does cause an error:
```
This expression was expected to have type
    'Quotations.Expr<'a>'    
but here has type
    'string'   
```
Problem can be solved like this:
```
printfn "%s in Pig Latin is: %s" name newName
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b07eeb2-d274-35da-78d4-b7d78c255590
* Version Independent ID: bf145620-7f23-eb4d-376d-f739562d9a79
* Content: [Get Started with F# in Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode)
* Content Source: [docs/fsharp/get-started/get-started-vscode.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-vscode.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks, this is just a typo. Should be quick to resolve
