### ISSUE TITLE
Document that "F" (and "FF", etc) removes the preceding period if it doesn't print anything

### ISSUE THREAD

**Issue by canton7** [dotnet/docs#22050]
Document that "F" (and "FF", etc) removes the preceding period if it doesn't print anything.

From the documentation:

```cs
DateTime date1 = new DateTime(2008, 8, 29, 19, 27, 15, 18);
CultureInfo ci = CultureInfo.InvariantCulture;

Console.WriteLine(date1.ToString("hh:mm:ss.F", ci));
// Displays 07:27:15
```

Indeed, there is [code which explicitly removes this decimal point](https://source.dot.net/#System.Private.CoreLib/DateTimeFormat.cs,530). 

Would it be worth documenting this behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
@canton7 Thanks for the suggestion, the article update is in PR #22498
