### ISSUE TITLE
Bash autocomplete doesn't work well

### ISSUE THREAD

**Issue by vessd** [dotnet/docs#22068]
The autocomplete script for bash needs to be refined.

At the very least, the 'completions' variable needs to be cleaned from the 'zr':
`completions="${completions//$'r'/}" `
and remove the '-f' option in the last line:
`complete -F _dotnet_bash_complete dotnet`

I understand, of course, that some teams may file as an argument, but not to everyone...

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Включение автодополнения клавишей TAB - .NET CLI](https://docs.microsoft.com/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Greetings! Thank you for the suggestion. I think at this time we'll leave it as it is. This issue will still be associated with the article though incase we wish to incorporate your suggestion at a future time. Thanks again!
