### ISSUE TITLE
how to SET the version of dotnet being used from the command line

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/docs#22078]
would be great if you could add how to SET the version of dotnet being used from the command line ? so for example if I wanted to use dotnet v3.x instead of dotnet v5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/install/remove-runtime-sdk-versions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
You can do this using a global.json config file. See [docs](https://docs.microsoft.com/dotnet/core/tools/global-json) for more information.

**Comment by adegeo** [comment]
I'm not sure I understand your question as it relates to uninstalling? There is a link in the first paragraph to [version selection](https://docs.microsoft.com/dotnet/core/versions/selection) when mentioning that removing versions may alter the default.
