### ISSUE TITLE
Link CA rule categories to overview pages

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#22087]
We should link mentions of CA rule categories to overview pages for that category.

For example, the category is mentioned in the table at the top of each reference article, such as [CA1000](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000). In addition, the category is often mentioned in the [Configure code to analyze](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000#configure-code-to-analyze) section. These mentions of the Design category should link to [Design rules overview](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/design-warnings).

**Comment by tstewart-writer** [comment]
I was looking for a good first issue and I thought this one looked fairly straightforward. I just wanted to make sure it is available.

**Comment by gewarren** [comment]
@tstewart-writer That would be great. Please make sure to use file-relative links instead of absolute links.

**Comment by tstewart-writer** [comment]
@gewarren No problem, I'll do that.

**Comment by tstewart-writer** [comment]
@gewarren Should I also link to the categories/subcategories for IDE rules? I initially assumed this issue was for all code analysis rules, both code quality and style. But rereading it makes me wonder if it should only cover CA rules.

**Comment by gewarren** [comment]
I would start with just CA rules.
