### ISSUE TITLE
PRMerger bot overwrites dotnet-bot

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22082]
See https://github.com/dotnet/docs/issues/22011 for example. When closing an issue, dotnet-bot is configured to automatically remove "Not triaged" label. But PRMerger adds it again.

This isn't a big or important issue, but reporting anyway.

**Comment by BillWagner** [comment]
Adding @adegeo @lamebrain

**Comment by adegeo** [comment]
Is PRMerger using some sort of ML to determine what labels should be added?

**Comment by gewarren** [comment]
It just happened on #22041 as well.

![image](https://user-images.githubusercontent.com/24882762/102676468-8df99580-4152-11eb-946b-b35759eedd82.png)

cc @meganbradley

**Comment by adegeo** [comment]
If I were to venture a guess, the PRMerger bot is receiving the closed event and simply applying the existing labels it detected on the PR (for what reason? I don't know). Our bot happens to remove the label between the time the PRMerger bot starts and ends, hence the Not Triaged label is added back.

**Comment by Youssef1313** [comment]
In #22158, I noticed it was only labeled after the comment https://github.com/dotnet/docs/issues/22158#issuecomment-751307388. I'm not sure why, but I'd guess it uses ML and was only able to label the issue after that comment.

**Comment by BillWagner** [comment]
I'll close this. First, @adegeo made some changes to our bot and that fixed many of the timing issues, and added a few other features. There's also an internal work item for the site engineering team on the PRMerger bot not always assigning areas correctly.
