### ISSUE TITLE
Use image tags from MCR instead of Docker Hub for .NET container images

### ISSUE THREAD

**Issue by dlepow** [dotnet/docs#22090]
This article includes tables listing .NET Framework container image tags hosted in Docker Hub, for example:

microsoft/dotnet-framework:4.x-windowsservercore
microsoft/aspnet:4.x-windowsservercore
microsoft/dotnet:2.0.0-runtime
microsoft/dotnet:2.0.0-runtime-nanoserver

We're developing content guidance to use only tags from Microsoft Container Registry for Microsoft container images referred to in Docs content, so please update with MCR references if possible. There's not a 1:1 correspondence of tags between MCR and Docker Hub, so please reach out to danlep if you have questions about MCR images. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38f8c6b-22ff-5374-496c-f27fbb6fd77e
* Version Independent ID: 478f1425-8549-54f8-a9fd-c537e054ce6c
* Content: [Deploy existing .NET apps as Windows containers](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/deploy-existing-net-apps-as-windows-containers)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/deploy-existing-net-apps-as-windows-containers.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/deploy-existing-net-apps-as-windows-containers.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @dlepow , thank you for the update.

There is an open PR #22104 already to update the content of this eBook to .Net 5.  
This PR also contains the respective changes related to the Microsoft Container Registry for the Microsoft Docker images. Here is specific [commit](https://github.com/dotnet/docs/pull/22104/files#diff-5242e6800e3a8032edda63921ebdcaae79a6d213d86f523e46cffe5b9c2d3895) for your reference. If you could review MCR specific information and share your feedback.

CC: @nishanil

**Comment by dlepow** [comment]
@sughosneo - Thanks for the context, the substitution of MCR images in the linked PR looks great and addresses my comment.
Closing.
