### ISSUE TITLE
Build or no Build

### ISSUE THREAD

**Issue by unitrix0** [dotnet/docs#22097]
Hello,

The option `--no-build` seems confusing to me. If I don't use it the command `dotnet pack` gives me error NU5026 because the project hasn't built yet. So it doesn't seem to build it automatically. And when I use `--no-build` it explicitly doesn't build the Project... 

So I have to build it myself anyway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@unitrix0 The behavior referred to in https://github.com/nuget/home/issues/6118 is documented in the article after the text that mentions the automatic build:

```
> [!NOTE]
> In some cases, the implicit build cannot be performed. This can occur when `GeneratePackageOnBuild` is set, to avoid a cyclic dependency between build and pack targets. The build can also fail if there is a locked file or other issue.
```

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by kwaazaar** [comment]
If you're going to enhance documentation, please also consider enhancing documentation for the DotNetCliTask in Azure Devops (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack). The build pipeline is probably where people start running into this issue.
