### ISSUE TITLE
Porting .NET MSDN docs to Core - Events

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#221]
We need to port the relevant content from MSDN that applies to .NET Core.

The events docs are still applicable to .NET Core. This is the starting point for events:
https://msdn.microsoft.com/en-us/library/edzehd2t(v=vs.110).aspx

**Comment by BillWagner** [comment]
There is a set of articles on Delegates and Events here: http://dotnet.github.io/docs/languages/csharp/delegates-events.html

I'm planning to look at the existing content, and see what's not already covered, and add that content under the existing section. I'll make one PR for the new topic page, and then flush it out with the ported content. Does that make sense? /cc @mairaw

**Comment by mairaw** [comment]
Sounds good @BillWagner!

**Comment by BillWagner** [comment]
I reviewed the ported content today.

Under https://github.com/dotnet/docs/tree/master/docs/csharp/programming-guide/delegates everything can be removed and re-directed to https://github.com/dotnet/docs/blob/master/docs/csharp/delegates-overview.md or one of the later articles.

Under https://github.com/dotnet/docs/tree/master/docs/csharp/programming-guide/events everything can be removed except for the How to: Use a dictionary to Store Event Instances topic (https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances.md)

This is blocked pending the global redirect feature. (The existing content to be removed should be redirected to the new content).

**Comment by mairaw** [comment]
Closing this one since porting was done. We need a larger project for handling the duplicated topics across the repo.
