### ISSUE TITLE
PDF of .NET "Regular Expression Language - Quick Reference" is Failing

### ISSUE THREAD

**Issue by vwheeler63** [dotnet/docs#22101]
Hi.  The PDF download of the quick reference failed today (20-Dec-2020) on several attempts just before 12:54 Mountain Standard Time.  The resulting download is corrupted and cannot be opened.

The download link is:
    https://download.microsoft.com/download/D/2/4/D240EBF6-A9BA-4E4F-A63F-AEB6DA0B921C/Regular%20expressions%20quick%20reference.pdf

Kind regards,
Vic Wheeler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I just tested and it's working for me. Please verify that it is still broken for you. I'm going to close the issue but feel free to respond.

**Comment by vwheeler63** [comment]
Hi!  Thank you for testing it.  I just tried re-downloading it and now Adobe Reader opens it successfully.  However, the .DOCX format shows that page 3 has a couple of sections in it that are missing from the PDF I just downloaded.  I mention it as it might be relevant.  Hope this helps.

**Comment by vwheeler63** [comment]
False alarm:  The last "section" is "To get ... Use Regex API..." in the PDF and that is also the last section in the .DOCX format, so I will assume that is simply how the content "flowed into" the columns.
