### ISSUE TITLE
Code syntax error 

### ISSUE THREAD

**Issue by chanmmn** [dotnet/docs#22103]
I try to edit but I cannot see the C# code.

using FileStream myStream = new FileStream("TestData.txt", FileMode.OpenOrCreate);

The using will create the syntax error I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee15f916-5406-85fa-b7fb-a9e69fcd3efb
* Version Independent ID: b6aae569-8a56-0a44-7b8e-e54491418baf
* Content: [Encrypting Data](https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data)
* Content Source: [docs/standard/security/encrypting-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/encrypting-data.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment]
If you're talking about the using statement syntax, this was a new feature in C# 8.0. See [using statement docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)

**Comment by chanmmn** [comment]
Are you saying .NET Framework 4.8 is not supporting C# 8.0? Can you confirm that? Can someone also helps to put this information on the page itself?

![using](https://user-images.githubusercontent.com/33271651/102841510-0a84c080-4440-11eb-96c4-4214623b6b17.PNG)

**Comment by Youssef1313** [comment]
@chanmmm The default language version for .NET Framework is C# 7.3, you can override that in your csproj file.

**Comment by chanmmn** [comment]
Yes, it can build after I added

  <PropertyGroup>
   <LangVersion>8.0</LangVersion>
 </PropertyGroup>

in csproj file. 
Thanks
