### ISSUE TITLE
CS1662: Cannot convert lambda expression

### ISSUE THREAD

**Issue by justin368** [dotnet/docs#22119]
`

    return from word in words.AsParallel()
        let reverse = new string(word.Reverse().ToArray())
        where word != reverse && wordsSet.Contains(reverse)
        select word;`

in Visual Studio 16.9.0 prev 2; .NET v4.8.04161 produces: 
`CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aeee012-d49e-e096-229c-44d38063b34f
* Version Independent ID: 86f4283b-fd68-22b5-c546-afe3c554d434
* Content: [Walkthrough: Creating a Dataflow Pipeline](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline)
* Content Source: [docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by svick** [comment]
When I copy code from the sample that contains that query, it compiles fine for me in VS 16.9 Preview 2 when targeting .Net Framework 4.8. Can you share all the code you're compiling? Do you get any other errors or warnings?

**Comment by justin368** [comment]
I apologize for the inconvenience but I forgot a 'Many' in the TransformManyBlock code.. no further issue/this should be closed.
