### ISSUE TITLE
Force trailing comma in collection initializer

### ISSUE THREAD

**Issue by jzabroski** [dotnet/docs#22120]
https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/formatting-rules.md

Does not mention options for having a trailing comma, as best as I can tell.

This is somewhat surprising to me, as forcing a trailing comma in collection initializers greatly aids in clean future diffs if people add to the diff.

[Edited to add doc details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729883e2-dbb0-4fd5-c122-42a337283b62
* Version Independent ID: ff0fdfd7-042b-4d76-5d52-7e5a1bc167b6
* Content: [Code style formatting rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/formatting-rules.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/formatting-rules.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
If such a a code style analyzer doesn't already exist, you can log an issue [here](https://github.com/dotnet/roslyn-analyzers/issues) to propose creating one.
