### ISSUE TITLE
OSS Library Multi-Target .NET 5 Guidance

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/docs#22123]
Is there any guidance as to whether to multi-target .NET 5.0 for libraries even when we're not using new API's when we're already multi-targeting .NET Standard or .NET Core? .NET Standard and .NET Core libs will work in .NET 5.0 so I'm inclined to think the only consideration would be that less informed users would more easily understand compatibility with .NET 5+ if you add a .NET 5.0 target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by tdykstra** [comment]
There is some multi-targeting guidance that may be helpful here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-5-and-net-standard

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
