### ISSUE TITLE
Image classification tutorial issue

### ISSUE THREAD

**Issue by outlookhazy** [dotnet/docs#22121]
The tutorial has users create a TSV parsing method that never gets used. 
mlContext.Data.LoadFromTextFile is called instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: ML.NET image classification model from TensorFlow - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @outlookhazy 

Thanks for raising this issue. We're looking into it.
