### ISSUE TITLE
Wrong example code and descriptions in "High-performance logging in .NET"

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/docs#22137]
The "High-performance logging in .NET" has two sections:

1. Define a logger message
2. Define logger message scope

Somehow the example code for "message scope" ended up in the first section (which caused quite the confusion for me because text and sample don't match). The following code snippets are affected:

> Each log message is an Action held in a static field created by LoggerMessage.Define. For example, the sample app creates a field to describe a log message for the processing of work items:
>
> ```c#
> private static Func<ILogger, DateTime, IDisposable> _processingWorkScope;
> ```

and:

> ```c#
> _processingWorkScope =
>     LoggerMessage.DefineScope<DateTime>(
>         "Processing work, started at: {DateTime}");
> ```

and:

> The Action is invoked through a strongly-typed extension method. The `FailedToProcessWorkItem` method logs a message every time a work item is being processed:
>
> ```c#
> public static IDisposable ProcessingWorkScope(
>     this ILogger logger, DateTime time) =>
>     _processingWorkScope(logger, time);
> ```

Also, at least the text from the third snippet doesn't match the example that follows later in the article:

> The `FailedToProcessWorkItem` method logs a message every time a work item is being processed:

Shouldn't this say (or something similar):

> The `FailedToProcessWorkItem` method logs a message every time **an exception happens while a work item was** being processed:

Also, the examples in the second section don't match their text either.

Should the field be called `_allQuotesDeletedScope` or `_processingWorkScope`:

> The sample app creates a field called `_allQuotesDeletedScope` (Internal/LoggerExtensions.cs):
>
> ```c#
> private static Func<ILogger, DateTime, IDisposable> _processingWorkScope;
> ```

`DateTime` or `int`:

> The sample app uses a message template that includes the number of deleted quotes (an `int` type):
>
> ```c#
> _processingWorkScope =
>     LoggerMessage.DefineScope<DateTime>(
>         "Processing work, started at: {DateTime}");
> ```

Here, text and example match - but they don't match the texts that came before (no mention of "deleted quotes"):

> The sample app takes in a DateTime for a custom time stamp to log and returns _processingWorkScope:
> 
> ```c#
> public static IDisposable ProcessingWorkScope(
>     this ILogger logger, DateTime time) =>
>     _processingWorkScope(logger, time);
> ```

The full example code that follows also again uses `ProcessingWorkScope` but mentions nothing about "deleted quotes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c051-c047-bbcd-5e25-ca6a722b51c3
* Version Independent ID: 3f5f1b6e-06ac-cc07-48cd-b8b957a4abbb
* Content: [High-performance logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging)
* Content Source: [docs/core/extensions/high-performance-logging.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/high-performance-logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi again @skrysmanski - thank you so much for this, it's much appreciated. I'll work on correcting this straight away.
