### ISSUE TITLE
Records don't fullfill any requirement of option classes

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/docs#22134]
The "Options pattern" description contains this part:

> Create the following `TransientFaultHandlingOptions` class:
> 
> ```c#
> public record TransientFaultHandlingOptions(
>     bool Enabled = false, TimeSpan AutoRetryDelay = default);
> ```
>
> An options class:
>
> * Must be non-abstract with a public parameterless constructor
> * Contain public read-write properties to bind (fields are not bound)

Both requirements are **not true** for the specified record example:

> Must be non-abstract with a public parameterless constructor

The `TransientFaultHandlingOptions` does *not* have a parameterless constructor.

> Contain public read-write properties to bind (fields are not bound)

The properties of `TransientFaultHandlingOptions` are read-only - or `init`-only (not read-write).

I haven't checked but I'm assuming that records are supported none the less. It's just that the description doesn't match the reality.

I'm guessing the following is true for the options pattern:
* It allows for either parameterless constructors *or* for constructors where *all* parameters have default values.
* Properties can be read-write or read-initonly (which, to my understanding, is the same when accessing the property through reflection).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @skrysmanski 
Thank you so much for posting this issue. We really appreciate it. You are correct, I'll update the docs accordingly.
