### ISSUE TITLE
dotnet-install.sh cannot get sdks after install

### ISSUE THREAD

**Issue by bryht** [dotnet/docs#22148]
`curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 3.1`

I try to use this script to install sdk in a docker image, it seems success
![image](https://user-images.githubusercontent.com/2418508/103080442-23bf7580-45d6-11eb-9fec-4f1dbc147182.png)

but when I use `dotnet --info`, it didn`t show sdks..
![image](https://user-images.githubusercontent.com/2418508/103080573-65502080-45d6-11eb-907e-daeff35724d5.png)

my docker image, `FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @bozturkMSFT

**Comment by bozturkMSFT** [comment]
Hi @bryht,
 According to the logs you shared, script is installing the SDK into `/root/.dotnet`. However, when you run `dotnet --info` you are running the executable located under `/usr/share/dotnet`.

 To access the SDK that you installed with the scripts, use `./root/.dotnet/dotnet --info` or manually add `/root/.dotnet` to your PATH.
 Let me know if this helps.

**Comment by bryht** [comment]
> Hi @bryht,
> According to the logs you shared, script is installing the SDK into `/root/.dotnet`. However, when you run `dotnet --info` you are running the executable located under `/usr/share/dotnet`.
> 
> To access the SDK that you installed with the scripts, use `./root/.dotnet/dotnet --info` or manually add `/root/.dotnet` to your PATH.
> Let me know if this helps.

it works, thank you.
