### ISSUE TITLE
Classes vs class fields

### ISSUE THREAD

**Issue by TysonMN** [dotnet/docs#22149]
> Record fields differ from classes in that they are automatically exposed as properties, and they are used in the creation and copying of records.

I think it is obvious that record fields and _classes_ are different.  Instead, I think the intention here is to contrast record fields with _class fields_.

If this is the intention, then I can create a PR to replace "classes" with "class fields".

**Comment by BillWagner** [comment]
Thanks for spotting this @TysonMN Yes, I'd appreciate a PR to fix this issue.
