### ISSUE TITLE
But what happened to my eggs, bacon, and toast?

### ISSUE THREAD

**Issue by HalHaynes** [dotnet/docs#22158]
In the original synchronous scenario, once our eggs, bacon, and toast had been announced, we actually had some eggs, bacon, and toast to enjoy. By the time we reach the end, we're executing async tasks that return eggs, bacon, and toast, and we announce the readiness of the eggs, bacon, and toast, but once our WhenAny loop is done we find that we've never *retrieved* the eggs, bacon, and toast from the tasks that supplied them. We've left them to sit there to get cold. How can we retrieve them and enjoy them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by HalHaynes** [comment]
Is this the answer? Enhance
```
                if (finishedTask == eggsTask)
                {
                    Console.WriteLine("eggs are ready");
                }
                else if (finishedTask == baconTask)
                {
                    Console.WriteLine("bacon is ready");
                }
                else if (finishedTask == toastTask)
                {
                    Console.WriteLine("toast is ready");
                }
 ```
as follows
```
                if (finishedTask == eggsTask)
                {
                    egg = await finishedTask;
                    Console.WriteLine("eggs are ready");
                }
                else if (finishedTask == baconTask)
                {
                    bacon = await finishedTask;
                    Console.WriteLine("bacon is ready");
                }
                else if (finishedTask == toastTask)
                {
                    toast = await finishedTask;
                    Console.WriteLine("toast is ready");
                }
 
```
? I think this is the answer implied several pages later, [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete). Is it that once a Task has completed, it can be `await`ed additional times, still resolving each time to the result already arrived at?

**Comment by BillWagner** [comment]
Thanks for writing this @HalHaynes 

Yes, your analysis is correct. The changes you make do retrieve the result (your food) from the completed task. We'll update the article to include this.

**Comment by BillWagner** [comment]
Closing as this has been fixed in earlier PRs.
