### ISSUE TITLE
EditorConfig Docs differs from VS2019 templates

### ISSUE THREAD

**Issue by kaylumah** [dotnet/docs#22161]
Hi,

Not sure if this is the right place to report / ask this question, so perhaps it is better suited as a discussion.
The default .editorconfig different from the one generated by Visual Studio as described here https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019
Not only the section descriptions and the amount of sections differ, but the settings in them and the amount of settings being set differ. The VS one covers *, cs, csx, vb and vbx files instead of only C# files. 

So I am really wondering 
- which template should I choose
- how do I update the template with new conventions, analysers etc come available
- which files should .NET target?

Personally I like the style from VS2019 better, with the enclosed # and perhaps I would expect links to the docs regarding sections on the docs. Especially since these are extensions of the editorconfig spec. 

Should there be a sync between the generated one in vs2019 and the one here in the docs? Which Is recommended to be used?

The update part might be hard, since every project can customise which rules to use etc as demonstrated by the samples by the linked runtime and roslyn samples.

Some guidance in this regard would be welcome

Thanks,
Max

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c8357d-11a6-6f12-b044-5ff44df65d10
* Version Independent ID: 0c103fd7-5cc4-2726-40f8-d759419ae635
* Content: [.NET code style rule options - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/code-style-rule-options.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/code-style-rule-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
> which template should I choose

The example file at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019#example-editorconfig-file should really just show the code style conventions for C# and Visual Basic, as that is the intention of that page. The VS page you linked to is geared more towards the general concept of an EditorConfig file, so I would use that template, especially if that's your preference.

> how do I update the template with new conventions, analysers etc come available

I guess you are asking if there's an automated way to update the .NET editorconfig file that's supplied by VS. I don't think that's possible, so you'd have to add the new conventions manually.

> which files should .NET target?

Do you mean which file extensions? It looks like the .csx and .vbx extensions are for [scripting files](https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/january/essential-net-csharp-scripting). If you're not using those file types, then I don't think you need to include them.

> Should there be a sync between the generated one in vs2019 and the one here in the docs?

Yes, I will update this one to match the VS template.

Tagging @Mikejo5000 in case he has further comments.

**Comment by maxhamulyak** [comment]
Thanks for the clarification!

> The VS page you linked to is geared more towards the general concept of an EditorConfig file, so I would use that template, especially if that's your preference.
> Yes, I will update this one to match the VS template.

This would mean that after you update it, it no longer matters right? :-) 

Regarding the file extensions it was mainly because the VS generated one also targets *, vb csx etc. 

Do you know if there is an easy way to discover new setting? Or some feed I can subscribe too? Because especially with the new analyser support I would love to used these more.

**Comment by maxhamulyak** [comment]
As an aside, vs2019 also has "plain" template which takes care of XML for example. 
Might be worth while to include that for *proj (csproj etc.) as well so the indentation in those files would be correct.

**Comment by gewarren** [comment]
> As an aside, vs2019 also has "plain" template which takes care of XML for example.
> Might be worth while to include that for *proj (csproj etc.) as well so the indentation in those files would be correct.

To make a suggestion for VS, [this is the best place](https://developercommunity2.visualstudio.com/report?entry=suggestion&space=8).

**Comment by gewarren** [comment]
> Do you know if there is an easy way to discover new setting? Or some feed I can subscribe too? Because especially with the new analyser support I would love to used these more.

@mavasani Can you answer that question?

**Comment by mavasani** [comment]
Tagging @mikadumont - I believe any new code style setting being added is documented with release notes. Additionally, all the supported code style options should also be documented at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/language-rules#net-style-rules

**Comment by kaylumah** [comment]
hi guys, any update on this?

**Comment by kaylumah** [comment]
Hi @gewarren thanks for taking care of this. I am however still not seeing it in VS2019 itself, after I have updated it. (Generated it today in blank solution), am I missing something to update templates there? :) Otherwise the to are still out of sync :)

**Comment by gewarren** [comment]
@kaylumah Can you clarify what you're not seeing in VS 2019? I updated the EditorConfig example in docs to match the one from the .NET editorconfig template in VS.

**Comment by kaylumah** [comment]
@gewarren when I start a blank solution in VisualStudio and choose add new item to add editorconfig (.NET) I still get the old template. Do I need to do something to update the templates in VS2019?

Your update does match the change made to the constant file in the templates 😊

**Comment by gewarren** [comment]
@mikadumont Is there a way to manually update editorconfig templates in VS 2019?
