### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by darkoverlordofdata** [dotnet/docs#22170]
[Enter feedback here]
```
Build FAILED.

/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fs(8,5): error FS1160: This token is reserved for future use [/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fsproj]
/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fs(8,62): error FS1141: Identifiers followed by '!' are reserved for future use [/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fsproj]
/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fs(8,5): error FS0010: Unexpected whitespace in expression [/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fsproj]
/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fs(8,66): error FS0514: End of file in string begun at or before here [/usr/home/darko/GitHub/FSNetCore/src/Library/Library.fsproj]
    0 Warning(s)
    4 Error(s)
---
```
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836d726d-1f95-51e7-c5c3-a7200adc5772
* Version Independent ID: 3e9e6e89-7017-7a7c-faea-4c0e76cef442
* Content: [Get started with F# with command-line tools](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line)
* Content Source: [docs/fsharp/get-started/get-started-command-line.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-command-line.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Are you using the .NET 5 SDK?

**Comment by darkoverlordofdata** [comment]
I finally figured it out. I was on an older version of the preview. I had to wait for a newer version to make it through the pipeline.
