### ISSUE TITLE
The specification needs a bit more detail on order.

### ISSUE THREAD

**Issue by hallambaker** [dotnet/docs#22179]
I really like this feature. But I need more details about the order in which module initialization takes place.

In particular, let us say I have a base library that is the same for every system and a separate platform specific library which overrides certain delegates in the base library.

This is a pattern that recurs frequently. I might have a catalog of encryption or compression or document parsing algorithms. Adding a new entry to the catalog can now be as easy as just linking to the new library.

Another thing I use is the ability to link in a 'debug' library to override the normal behavior in some cases. So instead of firing up on port 80, a test service fires up on a specified test port, instead of adding keys to the platform key store, they are put in a test container, instead of using random data initialized from a changing platform seed, this is fixed by the test number so the tests are deterministic. 

But I do need to know that if B has a project dependency on A then the ModuleInitializer for A will ALWAYS be called before B.

The easiest way to make this happen is if the spec mandates that behavior. It is the logical approach after all and almost certainly what would happen. But I cannot see a guarantee that this is the behavior so I will have to write code to enforce it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395f8758-bf0a-fb39-6849-c55d3d1a48d6
* Version Independent ID: 867c37b3-eeae-8817-5c0a-a2df3d86044e
* Content: [Module initializers - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers)
* Content Source: [proposals/csharp-9.0/module-initializers.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/module-initializers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @jcouv and @RikkiGibson to verify my thoughts below.

I think the combination of [the runtime spec](https://github.com/dotnet/runtime/blob/master/docs/design/specs/Ecma-335-Augments.md#module-initializer), the C# rules on static constructors, and the module initializer spec provide the behavior you are relying on here. 

Your specific question is:

> I do need to know that if B has a project dependency on A then the ModuleInitializer for A will ALWAYS be called before B.

I don't think this is guaranteed, but I'm not sure you need this guarantee from the description I read above. If B has a project dependency on A, that means some type in B depends on some type in A. What must be true is that the module initializers for B and A must complete before any static constructors in the respective projects are called, or any types in that project are accessed. For any type in B that depends on any type in A, the module initializers for both must have executed.

In addition, if the module initializer for B relies on a type in A, the module initializer for A must complete before the module initializer in B runs. 

Do you need a further guarantee for either of the scenarios you mention above?

**Comment by jcouv** [comment]
This is more of a runtime question. Aside from the runtime spec which Bill referenced (and which is linked from the C# feature spec), I don't have much to add :-/
