### ISSUE TITLE
Off by one

### ISSUE THREAD

**Issue by xanatos** [dotnet/docs#22173]
> The maximum index in any single dimension is 2,147,483,591 (0x7FFFFFC7) for byte arrays and arrays of single-byte structures, and 2,146,435,071 (0X7FEFFFFF) for other types.

This sentence is wrong. The maximum _size_ in any single dimension is... In C# an array of size 10 has indexes 0...9 (included), so the maximum index is the size - 1.

    var test = new byte[2147483591];

works (and has maximum index 2147483590)

    var test = new byte[2147483591 + 1];

throws `OutOfMemoryException`

The same happens for types with bigger size (and that use the other limit):

    var test = new float[2146435071];

works

    var test = new float[2146435071 + 1];

throws `OutOfMemoryException`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e093d16-79e3-e4eb-323f-4e4ef7fe677b
* Version Independent ID: f673a7d5-3db0-3bb2-5077-a3186871fc71
* Content: [&lt;gcAllowVeryLargeObjects&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@xanatos Thank you for logging this. I have a PR to fix it.
