### ISSUE TITLE
How to configure trace switches in ASP.NET Core apps?

### ISSUE THREAD

**Issue by sandersaares** [dotnet/docs#22171]
The page on trace switches says to use app.config/web.config. However, this file does not exist in ASP.NET Core and instead we have a completely differently structured appsettings.json by default.

So how is one meant to configure trace switches in ASP.NET Core apps? This is not understandable right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee189038-0fed-f04a-d340-9e37484290a8
* Version Independent ID: d44ec1ca-54fd-73cd-c994-f8debacb293b
* Content: [How to: Create, Initialize and Configure Trace Switches](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-initialize-and-configure-trace-switches)
* Content Source: [docs/framework/debug-trace-profile/how-to-create-initialize-and-configure-trace-switches.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/how-to-create-initialize-and-configure-trace-switches.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@sandersaares This article applies to .NET Framework and not .NET Core/5. For configuring logging in ASP.NET Core, see [this section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging). Also tagging @Rick-Anderson in case he has further comment.

**Comment by sandersaares** [comment]
The referenced article has no mention of TraceSwitch.

To restate the issue, TraceSwitch is a class that exists in both .NET Core and .NET Framework but the documentation is missing for how to use it in .NET Core.

**Comment by davidfowl** [comment]
Because System.Diagnostics.TraceSource isn't used in ASP.NET Core

**Comment by gewarren** [comment]
@sandersaares Here's an [open issue](https://github.com/dotnet/runtime/issues/23937) to make `TraceSource` work with .NET Core. I'm going to close this docs issue out since, presently, you cannot configure trace switches with .NET Core.
