### ISSUE TITLE
Hello ML.NET World doesn't specify NuGet requirements

### ISSUE THREAD

**Issue by EdmundoMartinez** [dotnet/docs#22184]
The Hello ML.NET World example doesn't mention that when using .Net Core the NuGet Microsoft.ML should be installed.
This would sound pretty basic, but having an example that works is very important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [What is ML.NET and how does it work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @EdmundoMartinez

Thanks for the feedback. This article is not intended for users to follow along like a how-to guide or tutorial. For a Hello World experience, you can see this sample (https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro) or the rest of the [tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis). We'll take a look at the article to see how we can improve it to avoid confusion.

**Comment by luisquintanilla** [comment]
Thanks for this issue @EdmundoMartinez 

Since this article is an overview / introduction to the framework and there are several tutorials for the various scenarios, there are no planned changes at the moment.
