### ISSUE TITLE
This page discusses TAP, but doesn't use the async keyword

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#22188]
That would seem to be important, as the return type does not dictate synchrony, only the presence or absence of the `async` modifier.  Suffixing a method name with "Async" that does not have that modifier is misinforming and confusing callers.

Async is recommended in the name because the keyword is not permitted in interface definitions, and it carries a significant shift for non async callers to potentially adapt to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40c0699-0e7c-e20d-98c1-76f0520ab9c2
* Version Independent ID: 0fc31902-0055-f9e8-a228-e7a0ce384e35
* Content: [Task-based Asynchronous Pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap)
* Content Source: [docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by fuzzykiller** [comment]
The `async` modifier is not part of a method’s interface. It does not indicate whether the call will complete asynchronously or not. Neither does the return type, of course. The return type, however, is what determines whether you can `await` or not.

The page is fine as is.

**Comment by BillWagner** [comment]
Thanks for noting this @StingyJack  and for the response @fuzzykiller


As has been discussed in other issues, the `async` keyword instructs the compiler to create the async state machine necessary to support `await` expressions in the body of the method. The presence or absence of the `async` keyword does not impact the API usage

Closing this as the article is correct.

**Comment by StingyJack** [comment]
This advice has [quietly changed over the years](https://github.com/dotnet/docs/issues/23834).
