### ISSUE TITLE
tooltip placement behavior wrong

### ISSUE THREAD

**Issue by AceLearnGit** [dotnet/docs#22189]
Hi,
I set a tooltip of a ctrl,and set tooltipservice.placement="bottom", as the doc says,  the tooltip should be place at bottom of target and align left with target, but i got wrong display , the tooltip align right with target. I test other placement,it seems left and right are opposite in my pc. More, it looks  correct in design window,but wrong if run my exe.  I run my exe in my friend's pc, his pc behave correct.
so, what's wrong with my pc or vs2017? how to fix that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88771909-3ed1-06b8-6650-cd16c8df2df2
* Version Independent ID: 2fac47b4-b474-b22a-1e77-54a1a2c13b58
* Content: [How to: Position a ToolTip - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-position-a-tooltip?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-position-a-tooltip.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/how-to-position-a-tooltip.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs-desktop#165
