### ISSUE TITLE
Analyzer Project template does not line up with the tutorial.

### ISSUE THREAD

**Issue by dennistouchet** [dotnet/docs#22183]
With a fresh install of Visual Studio Enterprise 2019 Version 16.8.3
on Windows 10 Pro Build 19042.630

When working through the tutorial, I am unable to get it to work after the initial analyzer setup. The test project, especially, looks nothing like what is shown in the tutorial. 

Example of template test method (note the asserts at the end, specifically):
![TestMethod](https://user-images.githubusercontent.com/1472116/103325745-04737e80-4a02-11eb-93e6-96f72ae49c72.PNG)

After looking through the source code I found this folder that is being used which is not in the template that was created for the project:
[https://github.com/dotnet/samples/tree/master/csharp/roslyn-sdk/Tutorials/MakeConst/MakeConst.Test/Helpers](MakeConst.Test/Helpers) so my next step will be to copy those over and keep trying.

Unfortunately, there is a `public readonly struct DiagnosticResults` that exists in the `CodeAnalysis.Testing` namespace which led to a lot of confusion on my end.

![DiagnosticResult](https://user-images.githubusercontent.com/1472116/103325898-c62a8f00-4a02-11eb-9d7c-7a67e4fec10e.PNG)

Getting a custom test to pass has been fruitless when trying to use that. (the metadata description for those methods/properties weren't clear to me.)

 My next step is to copy over those tutorial project helpers to continue on and report here with any progress.

**Update** 
Adding more details/notes/difference between the tutorial and the current template:

- The template also creates 5 projects compared to the tutorials 3 
    - The CodefixProvider is split into a new project and there is a Nuget package project
- The versions are all on core 2.0 which gives warnings about EoL. 
    - To update the .net core version on them requires a bit of tweaking and adjustments to fix the ambiguous reference errors. I found the simplest thing to do is move the CodefixProvider code back into Analyzer project and remove the code fix project, then remove that project reference from the VSIX project. From here you can update the .net core version without issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f49f32-eef3-635a-18c1-83900ed83356
* Version Independent ID: d282dd30-4560-1cfe-c801-25759216220d
* Content: [Get started with syntax analysis (Roslyn APIs)](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-analysis)
* Content Source: [docs/csharp/roslyn-sdk/get-started/syntax-analysis.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/get-started/syntax-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @dennistouchet

This article needs to be updated to match the current templates.
