### ISSUE TITLE
Dynamic Programming in Net Core

### ISSUE THREAD

**Issue by ajkimberley** [dotnet/docs#22181]
I can't seem to find a similar guide/article on Dynamic Programming in .Net Core. Does one exist? If so, it would be good to provide a link from this article to that one. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6179c09e-4a12-e0bc-a599-bbddad5bbc99
* Version Independent ID: d4baad38-e5e4-e247-9465-ed125804dc16
* Content: [Reflection in .NET](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/reflection)
* Content Source: [docs/framework/reflection-and-codedom/reflection.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/reflection.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
This is the only article I know about - https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext.
