### ISSUE TITLE
Miscellaneous page is missing an overview section/page

### ISSUE THREAD

**Issue by Evangelink** [dotnet/docs#22196]
Each sub-category of this page (except the miscellaneous) has an overview page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a396c1-9c21-75a9-70b5-799cafc941b5
* Version Independent ID: 6d91b560-c12f-6e6d-e92b-1babb27edb67
* Content: [Code style rules overview - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/)
* Content Source: [docs/fundamentals/code-analysis/style-rules/index.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Also, the subpages for Naming rules and Formatting rules should just be moved to their parent node in the TOC.

**Comment by BartoszKlonowski** [comment]
I can provide it with the overview page.
@gewarren @BillWagner Please assign me to this issue.

---

@gewarren Should the *Naming* and *Formatting* rules movement also be handled in this issue, or perhaps a separate issue should be created for that?

**Comment by gewarren** [comment]
Thank you @BartoszKlonowski . 

> Should the Naming and Formatting rules movement also be handled in this issue, or perhaps a separate issue should be created for that?

It can be handled through a separate issue if you prefer.
