### ISSUE TITLE
.NET install on Ubuntu 20.04

### ISSUE THREAD

**Issue by lxman** [dotnet/docs#22193]
I am not certain about the other distros or even about other versions of Ubuntu, but one of the steps listed in the install process is:

```wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb```

running this on Ubuntu server 20.04 ends up producing two files:

```packages-microsoft-prod.deb``` and ```packages-microsoft-products.deb.1```

The ```packages-microsoft-prod.deb``` ends up being the capture of the command line progress of the wget command. The actual ```.deb``` package that we need is the ```packages-microsoft-products.deb.1``` file. I see this as potentially confusing to some users.

It would be better to change the docs to use ```wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb``` instead. I suspect this is the same with the other linux flavors and versions in question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@lxman You should have a capital `-O` not a lowercase `-o` in that command.

**Comment by adegeo** [comment]
I believe this will solve your problem. I'm going to close this issue.
