### ISSUE TITLE
Hey，Don't making things more confusing.

### ISSUE THREAD

**Issue by HailstormShall** [dotnet/docs#22190]
You guys are just introducing more chaos than elegance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874ea00d-6ec4-55f4-f0e3-e818d21454c7
* Version Independent ID: 98072328-af31-5bc6-9ba4-1353328d5f10
* Content: [Expression-bodied members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'm closing this, as the article accurately reflects the language features.

@HailstormShall The [dotnet/csharplang](https://github.com/dotnet/csharplang) repository is where discussions on language features take place. This one has already been discussed, approved, and released, so it won't be changing. However, you can add your voice to ongoing discussions for the future.
