### ISSUE TITLE
code smell - invalid link

### ISSUE THREAD

**Issue by gundumon** [dotnet/docs#22191]
The code smell link - https://deviq.com/code-smells/ - returns 404 Not Found. The correct link is https://deviq.com/antipatterns/code-smells. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Youssef1313** [comment]
@ardalis, You probably missed a redirect on your website for this.

**Comment by Youssef1313** [comment]
I opened a PR to add redirect for this, we also should update the link here to avoid redirection.

**Comment by ardalis** [comment]
Thanks for the redirect fix on the site, @Youssef1313 ! I've created a PR to update the link to the new URL.
