### ISSUE TITLE
Refers to Mutex Constructor that does not exists in .Net 5.0

### ISSUE THREAD

**Issue by large** [dotnet/docs#22200]
Page refers to  Mutex(Boolean, String, Boolean, MutexSecurity), this constructor does not exists in .NET 5.0: 
https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=net-5.0#System_Threading_Mutex__ctor_System_Boolean_System_String_System_Boolean__System_Security_AccessControl_MutexSecurity_

All ACL connections on Mutex seems gone in .NET 5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0684ef38-4762-ef1d-c003-06342a4ad359
* Version Independent ID: b6ba60e9-a0c2-b778-58e3-8dda901e03ea
* Content: [Mutexes](https://docs.microsoft.com/en-us/dotnet/standard/threading/mutexes)
* Content Source: [docs/standard/threading/mutexes.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/mutexes.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
That constructor as well as GetAccessControl and SetAccessControl don't exist in any .NET Core versions.

**Comment by IEvangelist** [comment]
I'm curious @gewarren - are these APIs covered in any of your recent PNSE articles? If so, we should probably create an include file that can be added to all of the articles that refer to APIs that do throw PNSE.

**Comment by gewarren** [comment]
@IEvangelist In this case, the API was removed completely, so it's a bit different to the ones that throw PNSE.
