### ISSUE TITLE
Incomplete list of possible case endings

### ISSUE THREAD

**Issue by Bip901** [dotnet/docs#22209]
The linked document claims that 

> the syntax of the case statement requires that each case end with a `break`, `return`, or `goto`.

However, it's also possible to end a case with a `throw`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Bip901 

You're correct. `throw` would also be valid. We'll add this to our backlog to fix.

**Comment by BillWagner** [comment]
This was fixed in a previous PR. Closing.
