### ISSUE TITLE
byteArray does not exist

### ISSUE THREAD

**Issue by KaiDevrim** [dotnet/docs#22204]
[Enter feedback here]
There is no object called ByteArray. Instead change it to making a new variable of byte[] called byteArray. Many people will thinking that their is a keyword called byteArray and get confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a7ce223-b955-7f50-6b53-15585c68f02d
* Version Independent ID: 78e4d95a-3a97-ec74-ebf4-843bad4efa7a
* Content: [How to: Send data by using the WebRequest class](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-send-data-using-the-webrequest-class)
* Content Source: [docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
It is part of the full example below. Isn't that sufficient?

**Comment by tdykstra** [comment]
Closing due to no response.
