### ISSUE TITLE
شسي

### ISSUE THREAD

**Issue by tawfik93** [dotnet/docs#22225]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89966aa-b155-c98a-2391-47e01d468236
* Version Independent ID: de902eee-6f6b-3ccd-4dbf-1cc174daa806
* Content: [Troubleshooting 'This application could not be started'](https://docs.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=Update.exe&platform=0000&osver=6&isServer=0&shimver=4.0.30319.0)
* Content Source: [docs/framework/install/application-not-started.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/application-not-started.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
This appears to be spam. Please let us know if you have specific feedback about an article.
