### ISSUE TITLE
Misleading examples

### ISSUE THREAD

**Issue by tanveerbadar** [dotnet/docs#22226]
None of the WCF examples actually show streaming, which would be methods taking and returning Stream objects.

Were the authors actually familiar with WCF at all before birthing this travesty?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe81680b-19cb-100e-65e0-670d5186a555
* Version Independent ID: b60a0691-8c34-d1e7-b7bf-19ebeb7c1c98
* Content: [Migrate WCF duplex services to gRPC - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-duplex-services#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/migrate-duplex-services.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/migrate-duplex-services.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
