### ISSUE TITLE
Parallel.ForEach should not be used for IO bound tasks.

### ISSUE THREAD

**Issue by jvanlangen** [dotnet/docs#22232]
I think using Parallel.ForEach on things that uses IO, is not a good example. I would restrict it to CPU bound processing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25dcc671-50d5-032b-735c-2ac9b6a21338
* Version Independent ID: c70450e1-1006-7478-fcca-45c8bfbe2c09
* Content: [Write a simple parallel program using Parallel.ForEach](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @jvanlangen - I agree, the example should be CPU bound and not IO. I'm updating this to be an "up for grabs", feel free to create a pull request changing this and I'll happily review it. Otherwise, I'll try to get to it. Thanks again

**Comment by surenderssm** [comment]
@IEvangelist - I agree example given is misleading.
I would love to give it a shot to fix this. Let me know your views on the following proposals.
Objective : Showcase the power of Parallel.ForEach for CPU intensive operations.

Proposal : We pick up a CPU  intensive operation let's say crude way to Findout if given number is prime or not. We start with fix size collection of random integer. In scenario 1 we can iterate over a collection with Foreach and in scenario 2 we iterate with Parallel.Foreach. In the end we display total number of prime numbers and total time taken for both the cases.

Do let me know perspective or any other thoughts ?

**Comment by IEvangelist** [comment]
Hi @surenderssm - I like that idea, and look forward to a PR.

**Comment by surenderssm** [comment]
Thanks @IEvangelist - Will share the PR asap.
