### ISSUE TITLE
Improve dotnet_analyzer_diagnostic.category Documentation

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/docs#22248]
The official documentation does not mention `dotnet_analyzer_diagnostic.category-CodeQuality.severity` but it exists in Roslyn Analyzers here: https://github.com/dotnet/roslyn-analyzers/blob/master/.editorconfig#L185-L239. 

[This documentation](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file) mentions that there are categories for rules and mentions 'Performance' but fails to list the categories. 

Is there a list of categories we can see?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa74a3f7-feef-0ec8-aebe-48bd106523dc
* Version Independent ID: 36879d50-dcc5-3376-9404-d60379024c0e
* Content: [Configure code analysis rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#scope)
* Content Source: [docs/fundamentals/code-analysis/configuration-options.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/configuration-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Also tagging @gewarren and @mikadumont 

We ship CA code quality analyzers and IDE code style analyzers with .NET SDK, starting version 5.0
The rules shipping in these SDK have specific categories. We have editorconfig support and documentation to enable/disable rules based on categories (see [here](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#scope)). With .NET SDK 6.0, we will also have MSBuild support for category based configuration (see [here](https://github.com/dotnet/roslyn-analyzers/pull/4556))

We should add both these pieces of documentation:
1. Explicitly list the set of categories for CA and IDE rules shipping with the .NET SDK
2. Documentation for new MSBuild support for category based configuration.

**Comment by RehanSaeed** [comment]
The documentation should also list which version of Visual Studio you need to use the new severity setting.

**Comment by christopherpross** [comment]
well, are there updates here? I want to enable some categories, but I didn't know the name of them in the Editorconfig.
It would be nice, if this could be documented.

**Comment by gewarren** [comment]
Thanks for the ping. I'll try to make these updates this month (August).
