### ISSUE TITLE
Mistake in this page

### ISSUE THREAD

**Issue by lfr** [dotnet/docs#22245]
I think the second C# here is supposed to be F#:

> Some features of XML documentation in C# and other .NET languages are not supported in **`C# ⚠`**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8fbc01-942f-ac15-e06b-2e50c45e8183
* Version Independent ID: 788235a1-2b43-1607-b24b-57c0552fd890
* Content: [XML Documentation - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation)
* Content Source: [docs/fsharp/language-reference/xml-documentation.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/xml-documentation.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Fixed by https://github.com/dotnet/docs/pull/22256
