### ISSUE TITLE
Double sentence in documentation

### ISSUE THREAD

**Issue by perkops** [dotnet/docs#22268]
In the section "The common type system", before the image, there are two lines, which pretty much describe the same thing:

_The following illustration shows the relationship between value types and reference types in the CTS.

The following image shows value types and reference types in the CTS:_

I would presume, one of these sentences could be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f29f2c2-44b6-ee2d-3991-ec7a77709883
* Version Independent ID: 64b883fc-4bf5-f6f1-0935-e82b83cf2bdf
* Content: [Types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/)
* Content Source: [docs/csharp/programming-guide/types/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @perkops 

I've submitted PR #22270 to address this issue. When you spot these in the future, you can click the edit button on the article (it looks like a pencil) to submit a PR to make the update. That may streamline the process.

Thanks again!
