### ISSUE TITLE
Autorization

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/docs#22269]
Authorization on package sources is always an issue. You should describe here how it works. Especially in conjunction with Visual Studio. Eg: in VS the restore of packages from a custom Azure Devops artifact store works flawless, since I'm logged in in VS. When using dotnet restore, I get an authorization error. It seems to use the sources registered in VS, but not the credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@nkolev92 Should this issue be transferred to the NuGet docs repo?

**Comment by nkolev92** [comment]
It's a multi repo/product problem, but is a great starting point.
https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds has answers for some of the customers' questions, but not all.

**Comment by tdykstra** [comment]
We already link to https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds in our doc, can you recommend who might know the answers to what isn't covered there?

**Comment by nkolev92** [comment]
> can you recommend who might know the answers to what isn't covered there?

The NuGet team can answer them. 

There are different plugins for core and framework tools (ie, dotnet.exe vs nuget.exe & msbuild.exe). 

VS also uses a different extensibility mechanism, and all these extensibility plugins/tools are expected to do their own caching.

It's on the feed provider to ensure that the plugin they ship for nuget.exe, the plugin they ship for dotnet.exe, and the VS extensibility share a cache.

**Comment by tdykstra** [comment]
This issue was moved to NuGet/docs.microsoft.com-nuget#2279
