### ISSUE TITLE
Document ActivitySource API

### ISSUE THREAD

**Issue by cijothomas** [dotnet/docs#22261]
**Describe the new article**

DiagnosticSource package (5.0) added new capability to Activity API by aligning with OpenTelemetry. The key new feature is the `ActivitySource` class which allows to create Activity in a way compatible with the evolving industry standard for telemetry - OpenTelemetry. However, ActivitySource and its associated mechanisms are *not* documented in .NET docs pages.

Proposing to add an official document for this. 

I have the following doc in the OpenTelemetry repo. Its mostly generic, and can be used here. But we want to remove OpenTelemetry specific parts, and refine it and make it part of .NET docs page.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Api#instrumenting-a-libraryapplication-with-net-activity-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1696b3d8-50cc-f8a6-0373-9361660d6b8c
* Version Independent ID: 643aea84-41c2-d700-8177-3380fb932e6a
* Content: [Diagnostics tools overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/)
* Content Source: [docs/core/diagnostics/index.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by cijothomas** [comment]
@IEvangelist @shirhatti

**Comment by sywhang** [comment]
https://github.com/dotnet/docs/pull/22617 added this. It is public now: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing#activitysource
