### ISSUE TITLE
Where is the "Protocol-Specific WebResponse"?

### ISSUE THREAD

**Issue by spazmodius** [dotnet/docs#22272]
The code sample here does not do what the title says.  Should it at least cast to `HttpWebResponse`, or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60878ca-ff38-a605-2713-c82f4698cd53
* Version Independent ID: a4ba014d-1106-c9a7-dd9f-4f19ba691e60
* Content: [How to: Retrieve a Protocol-Specific WebResponse that Matches a WebRequest](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-retrieve-a-protocol-specific-webresponse-that-matches-a-webrequest)
* Content Source: [docs/framework/network-programming/how-to-retrieve-a-protocol-specific-webresponse-that-matches-a-webrequest.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-retrieve-a-protocol-specific-webresponse-that-matches-a-webrequest.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
Good point. Simple to fix -- see PR #22648.
Based off other samples e.g. in https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebresponse
