### ISSUE TITLE
The ContinuousIntegrationBuild csproj property is not documented

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#22280]
https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli is another place this should probably be mentioned.

References:
- https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds
- https://github.com/tmat/repository-info/blob/master/docs/Readme.md#continuousintegrationbuild (other csproj properties here too!)

ContinuousIntegrationBuild is required by [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer#what-is-nuget-package-explorer):

![image](https://user-images.githubusercontent.com/8040367/104077497-f682e200-51e7-11eb-99fb-1b6f1edb3638.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 45464](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45464)

**Comment by klemmchr** [comment]
There is also a [GitHub](ContinuousIntegrationBuild) repository by @clairernovotny that showcases the use of `ContinuousIntegrationBuild=true` alongside with source link. It's a bit absurd that a Microsoft employee needs to create their own private GitHub repository to document such an important flag. This should be documented somewhere in the Microsoft Docs.

**Comment by gewarren** [comment]
The mentioned repo is here: https://github.com/clairernovotny/DeterministicBuilds
