### ISSUE TITLE
Visual Basic: Constructor documentation is missing

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#2228]
# Visual Basic: Constructor documentation is missing

For some reason, Visual Basic constructor documentation was removed from MSDN builds, and as a result was not migrated to docs.microsoft.com.

## General

There needs to be comprehensive documentation for Visual Basic constructors. The archived content on MSDN can serve as the starting point for a constructor topic(s), although it needs reorganization and a better focus.

**Comment by tverweij** [comment]
The Visual Basic Language specification contains almost 4 full pages with constructor documentation (9.3).
