### ISSUE TITLE
Parameter not passed as explained.

### ISSUE THREAD

**Issue by mohafifi** [dotnet/docs#22286]
Under the title "**Add process method**", the call to ReadAsByteArrayAsync() has no parameters passed in, although the explanation next to it says:
"The CancellationToken instance is passed into the HttpClient.GetAsync(String, CancellationToken) **and HttpContent.ReadAsByteArrayAsync()** methods.".

The method call ReadAsByteArrayAsync() should match the explanation. I think you forgot to pass in the cancellation token.
It needs to be fixed under the "**Complete example**" as well.
Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [Cancel a list of tasks (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @mohafifi You are correct. This sample should call the overload that has a `CancellationToken` parameter.

I've added this to our backlog to address.
