### ISSUE TITLE
The description about multi-dimensional array type support for indices and ranges

### ISSUE THREAD

**Issue by Jimmy-Hu** [dotnet/docs#22287]
In the section **Type support for indices and ranges**, it mentions that `Array has more nuanced behavior. Single dimension arrays support both indices and ranges. Multi-dimensional arrays don't. The indexer for a multi-dimensional array has multiple parameters, not a single parameter.` In other words, it means `Multi-dimensional arrays support **neither** indices **nor** ranges, doesn't it? Does it indicate that something isn't work like :

```C#
var abc = new int[10, 20];
var a = abc[^1, ^1];
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @Jimmy-Hu You are correct. The `System.Index` type is not allowed for accessing elements of a multi-dimensional array.
