### ISSUE TITLE
Documentation for File.Replace is messed up

### ISSUE THREAD

**Issue by joshudson** [dotnet/docs#22288]
1) There's some discussion on documenting the call as atomic; however that never happened. It would appear that it is atomic on Windows, but never truly was on Unix. <A HREF="https://github.com/dotnet/runtime/issues/18034">Issue #18034</A> probably should not have been closed.

2) This fragment makes no sense:

<BLOCKQUOTE>
PlatformNotSupportedException

The operating system is Windows 98 Second Edition or earlier and the files system is not NTFS.
</BLOCKQUOTE>

In the hypothetical scenario that somebody backports .NET 5 to Windows 98, the filesystem won't be NTFS. Assuming this was inherited from the original .NET Framework 1.0, it still won't ever be NTFS. Is "and" supposed to be "or", or is this only supposed to work on NT derivatives?

**Target framework**

- [X ] .NET Core
- [X ] .NET Framework
- [ X] .NET Standard

**Comment by tdykstra** [comment]
I don't see this exception in the documentation for [File.Replace](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.replace?view=net-5.0#System_IO_File_Replace_System_String_System_String_System_String_). Is this still an issue?

**Comment by joshudson** [comment]
@tdykstra Nope. Somebody fixed it between then and now.
