### ISSUE TITLE
How to prevent VS to Default set new items to Compile?

### ISSUE THREAD

**Issue by johan-dahlgren** [dotnet/docs#22298]
How do I prevent Visual Studio to set new Items to Compile.
Have version 16.8.3 and every time I start a new project and add new items i got this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9399f094-7665-b8ae-90f2-a108b9e4ad27
* Version Independent ID: 7cf5b33e-29f8-343e-fa17-8ddaceb5ae8a
* Content: [NETSDK1022: Duplicate items were included. - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1022?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1022)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1022.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/sdk-errors/netsdk1022.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @marcpopMSFT
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@TerryGLee is there a doc that can help with this?

**Comment by ghogen** [comment]
@tdykstra Can we transfer this issue to the https://github.com/MicrosoftDocs/visualstudio-docs repo?

**Comment by tdykstra** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#6341
