### ISSUE TITLE
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression Erreur	BC30311	Impossible de convertir une valeur de type 'DataGridViewRow' en 'Guna2DataGridView'.	WindowsApp3__DALY_ISCANDER_Projet	C:\Program Files\SIG\2éme année 1ier sem\PROGRAMMATION AVANCÉE\WindowsApp3__DALY_ISCANDER_Projet\WindowsApp3__DALY_ISCANDER_Projet\RéceptionnsiteForm3.vb	71	Actif

### ISSUE THREAD

**Issue by daly-skander** [dotnet/docs#22299]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c901dade-0ce5-19a8-9bd4-fa01d3cab6fd
* Version Independent ID: 3907306c-792a-6f61-3e7c-69e5140255f7
* Content: [Value of type '&lt;type1&gt;' cannot be converted to '&lt;type2&gt;' - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30311)
* Content Source: [docs/visual-basic/misc/bc30311.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/misc/bc30311.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by tdykstra** [comment]
@daly-skander It isn't clear to me what the issue is about from the title. Can you please provide details explaining the scenario and what is missing or incorrect in the documentation?
