### ISSUE TITLE
Many implemented interfaces missing for some types

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2229]
The list of implemented interfaces for [`List<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netframework-4.7) currently looks like this:

![](https://cloud.githubusercontent.com/assets/287848/26369117/ffccaeea-3ff3-11e7-9303-8dc4700cdc90.png)

I.e. most of the interfaces are not shown at all, only commas are visible.

This happens for other types too, e.g. [`IList<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1?view=netframework-4.7).

Possibly related to https://github.com/dotnet/docs/issues/1878.

**Comment by mairaw** [comment]
Thanks @svick. I forgot to paste the bug number I've opened internally for us to track  this issue [#1004298](https://mseng.visualstudio.com/CSI/_workitems?id=1004298&_a=edit&triage=true)

**Comment by mairaw** [comment]
This issue has been fixed. Please verify @svick.

**Comment by svick** [comment]
Yeah, seems to be fixed, closing.
