### ISSUE TITLE
F# code formatting guidelines inconsistency: = on new line

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#22296]
See the F# code formatting guidelines, section [Place parameters on a new line for long definitions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#place-parameters-on-a-new-line-for-long-definitions). The final part of that section is:

> If the parameters are currified or there's an explicit return type annotation, it is preferable to place the `=` character on a new line:
> ```f#
> type C() =
>     member _.LongMethodWithLotsOfParameters
>         (
>             aVeryLongParam: AVeryLongTypeThatYouNeedToUse,
>             aSecondVeryLongParam: AVeryLongTypeThatYouNeedToUse,
>             aThirdVeryLongParam: AVeryLongTypeThatYouNeedToUse
>         ) : AReturnType =
>         // ... the body of the method
>     member _.LongMethodWithLotsOfCurrifiedParams
>         (aVeryLongParam: AVeryLongTypeThatYouNeedToUse)
>         (aSecondVeryLongParam: AVeryLongTypeThatYouNeedToUse)
>         (aThirdVeryLongParam: AVeryLongTypeThatYouNeedToUse)
>         =
>         // ... the body of the method
> ```

Note that in `LongMethodWithLotsOfParameters`, the `=` sign is *not* on a separate line, contrary to what the sentence at the top says.

This section was overhauled in #21690, but the inconsistency was present before that PR.

I don't know what needs changing; the sentence or the code.

/cc @cartermp @knocte

**Comment by cmeeren** [comment]
This may also be relevant for the code shown above the sentence:

```f#
module M =

    let longFunctionWithLotsOfParametersAndReturnType
        (aVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        (aSecondVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        (aThirdVeryLongParam: AVeryLongTypeThatYouNeedToUse)
        : ReturnType =
        // ... the body of the method follows
```

If the it's _sentence_ I quoted in the OP that is correct (as opposed to the code), then for consistency, perhaps the `=` should be on a separate line in this example, too.

**Comment by knocte** [comment]
> I don't know what needs changing; the sentence or the code.

Well, we had already long debates about the code so I don't think it needs changing. What simply happened is that in the recent commit that introduced vanity-avoidance guidelines (https://github.com/dotnet/docs/commit/eb6f7b1119e6754e97d04384b8b672cc7b4efe1b) we forgot to update the sentence to make it consistent with the new snippets.

So I guess this diff would do:

```
- If the parameters are currified or there's an explicit return type annotation, it is preferable to place the = character on a new line:
- If the parameters are currified, place the = character along with the return type (if any) on a new line instead of leaving it in the same line where the last parenthesis is closed.
```

Or something along those lines.

**Comment by knocte** [comment]
(edited diff above)
