### ISSUE TITLE
Document integrated terminal

### ISSUE THREAD

**Issue by chm-tm** [dotnet/docs#22295]
Recent versions introduced an [integrated developer terminal](https://devblogs.microsoft.com/visualstudio/say-hello-to-the-new-visual-studio-terminal/). This was first in preview mode, but is now fully enabled.

I discovered this just due to a mistyped keystroke (Ctrl-¨). I then needed some time to dig out the command to do that again.

AFAICS this nice feature is not yet documented. Apart from the reference, this page would be one place where I'd like to find out about integrated command prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs?source=docs)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@TerryGLee Can you help with this?

**Comment by TerryGLee** [comment]
@tdykstra I've added a work item to get this feature documented in the "Develop" section of the Visual Studio docs library at https://docs.microsoft.com/en-us/visualstudio/

**Comment by tdykstra** [comment]
Thanks for the suggestion, @chm-tm ! When the new documentation is published, we'll link to it from here.

**Comment by gewarren** [comment]
This is now documented at https://docs.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2019.
