### ISSUE TITLE
Errors on Tutorial: Automated visual inspection using transfer learning with the ML.NET Image Classification API

### ISSUE THREAD

**Issue by cecchettia** [dotnet/docs#22306]
[Enter feedback here]
This page is missing many parts of the code. 

Below the ImageData class, define the schema of your input data in a new class called ModelInput. 

<this is what copy produces, note NO class name>

{
    public byte[] Image { get; set; }
    
    public UInt32 LabelAsKey { get; set; }

    public string ImagePath { get; set; }

    public string Label { get; set; }
}

Now adding  "class ModelInput " would complete the code, but for those starting out, this would lead to confusion

In this section
"Load the data       Create data loading utility method"
Lots of the code is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8adaedc-37da-e381-a87e-6649bc6cb3c8
* Version Independent ID: 779340cf-274b-5af9-54f0-b9b90c54f143
* Content: [Tutorial: Automated visual inspection using transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning)
* Content Source: [docs/machine-learning/tutorials/image-classification-api-transfer-learning.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification-api-transfer-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @cecchettia 

Thanks for raising this issue. We're looking into it.
