### ISSUE TITLE
System.Management.Automation.Platform public members vary by platform, but the docs don't warn about that

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#22302]
**Issue description**

PowerShell SDK 7.0 documentation describes **Platform.SelectProductNameForDirectory** and **Platform.XDG_Type**, which do not exist on Windows.

* [Platform.SelectProductNameForDirectory(Platform+XDG_Type) Method (System.Management.Automation) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.platform.selectproductnamefordirectory?view=powershellsdk-7.0.0)
* [Platform.XDG_Type Enum (System.Management.Automation) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.platform.xdg_type?view=powershellsdk-7.0.0)

These members exist in `UNIX` builds of PowerShell 7.1 (and presumably 7.0), and in the reference assembly in <https://www.nuget.org/packages/System.Management.Automation/7.1.0>. They however do not exist in PowerShell 7.1 built for Windows. The documentation should warn about this difference or not describe those members at all.

The members are defined within `#if UNIX`: <https://github.com/PowerShell/PowerShell/blob/fa01333bfeef5dd7769143e2b4ec7ffdb70c62c8/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L222-L247>

The members were changed from `internal` to `public` in <https://github.com/PowerShell/PowerShell/pull/1721>.

I was directed to <https://github.com/dotnet/docs/> by <https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7123#issuecomment-758015909>. I don't see any **System.Management.Automation** documentation here though, so perhaps this isn't the correct repository either.

**Comment by gewarren** [comment]
@KalleOlaviNiemitalo Apologies for the runaround. This issue should have gone to https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet. Can you open it there, or do you want me to?

**Comment by KalleOlaviNiemitalo** [comment]
@gewarren I get a 404 error at <https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet>. Is it a private repo?

**Comment by gewarren** [comment]
> @gewarren I get a 404 error at https://github.com/MicrosoftDocs/powershell-docs-sdk-dotnet. Is it a private repo?

Ah, yes it is. Sorry. @sdwheeler how do you want to track this issue?

**Comment by sdwheeler** [comment]
@gewarren It is a private repo. Changes to the docs need to be made in the PowerShell source code. This issue needs to be copied to https://github.com/PowerShell/PowerShell/issues.

**Comment by KalleOlaviNiemitalo** [comment]
@sdwheeler If the preferred solution is to exclude those members from the docs, then can that be achieved by adding some attribute to the source code?

**Comment by sdwheeler** [comment]
@KalleOlaviNiemitalo The members should be documented, but, I agree, it should be called out that they only apply to non-Windows platforms.

The .NET API documentation for the PowerShell SDK is autogenerated from the source code. Documentation is in the source code behind triple-slash comments. So any changes to the docs must be made in the source code.

**Comment by adegeo** [comment]
@KalleOlaviNiemitalo It doesn't seem that I can transfer this issue. Can you please recreate it at https://github.com/PowerShell/PowerShell/issues

Thanks!
