### ISSUE TITLE
Missing info about automatic MicrosoftRootCertificateAuthority2011.cer certificate installation process

### ISSUE THREAD

**Issue by bairog** [dotnet/docs#22308]
[MicrosoftRootCertificateAuthority2011.cer](http://go.microsoft.com/fwlink/?linkid=747875&clcid=0x409) is required both for  .NET Core 2.1 offline installer and .NET Framework 4.8 offline installer.
To fully automate certificate installation process (e. g. inside software installers) Certificate Manager utility (**certmgr.exe**) can be used to add the certificate via **admin** command prompt (more info at [StackOverflow](https://stackoverflow.com/questions/47176239/a-certificate-chain-could-not-be-built-to-a-trusted-root-authority/60812129)):
> certmgr.exe /add MicrosoftRootCertificateAuthority2011.cer /s /r localMachine root

So my proposal are:
1. The Certificate Manager utility is [automatically installed with Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/certmgr-exe-certificate-manager-tool), but I suppose it would be handy to have a separate download link for this utility.
2. Some docs about automatic certificate installation process are needed. I think that info should be mentioned at .NET Core 2.1 [necessary dependency page](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore21#dependencies) and somewhere at .NET Framework 4.8 offline installer [download page](https://support.microsoft.com/en-us/help/4503548/microsoft-net-framework-4-8-offline-installer-for-windows).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#dependencies)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by bairog** [comment]
@adegeo I've opened a separate issue as you [adviced me](https://github.com/dotnet/docs/issues/20459#issuecomment-758161977)

**Comment by adegeo** [comment]
@bairog Do you happen to know what OS need this? Is it Win7/Win8? or just Win7?

**Comment by bairog** [comment]
@adegeo I've tested only .Net Framework 4.8 offline installer and only on **clean** Win7 SP1. Info about .Net Core 2.1 offline installer is provided by you. I didn't test Win 8 (our software don't have such OS requirement).
