### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jsmuise** [dotnet/docs#22313]
rename firstFinishedTask  to just finishedTask on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d15bb1b-5f7f-20f3-78c3-d2b5bce950ed
* Version Independent ID: 80bee493-257b-5c64-4f28-cfb4e9bae560
* Content: [Process asynchronous tasks as they complete](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete)
* Content Source: [docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jsmuise Can you add a link to  which article this refers to?

**Comment by Youssef1313** [comment]
@BillWagner I believe it's https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete

**Comment by LeoGaunt** [comment]
Added PR #22385 to fix this
