### ISSUE TITLE
Getting the error - PublishReadyToRun not supported for target platform

### ISSUE THREAD

**Issue by cjmakwana** [dotnet/docs#22311]
Hello,

I am using the right runtime identifier as documented in this page for .net 5. However, I am still getting the error below:

**Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.**

I tested the publishing using linux-x64, which is as documented. However still getting the same.

Please let me know if I am missing anything further.

Regards,
Chandresh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbd832f4-5725-cee3-2053-bc3fa032b9f1
* Version Independent ID: 77e73736-bfb3-4d38-2193-a61d51be6c8e
* Content: [ReadyToRun deployment overview - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run)
* Content Source: [docs/core/deploying/ready-to-run.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/ready-to-run.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @davidwrighton
* Microsoft Alias: **davidwr**

**Comment by maxima120** [comment]
same problem with .net 5.0.102 console app. trying to publish on linux-64.

works fine without `<PublishReadyToRun>true</PublishReadyToRun>`

dotnet --info:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

error:
```
Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.
```
![image](https://user-images.githubusercontent.com/10121753/105633285-004b4d00-5e58-11eb-8bfa-66bcf1dae603.png)

**Comment by tdykstra** [comment]
What is your SDK platform, and what OS version?

**Comment by maxima120** [comment]
Tom, I got same problem: https://github.com/dotnet/core/issues/5874
target: linux-64, .net sdk 5.0.2

**Comment by cjmakwana** [comment]
> What is your SDK platform, and what OS version?

Hi @tdykstra my target is linux-x64, and .NET SDK is 5.0.2

**Comment by tdykstra** [comment]
@maxima120 According to https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#cross-platformarchitecture-restrictions , publishing r2r for Linux on a Windows machine isn't supported.

@cjmakwana what distro and version are you running the SDK on?

**Comment by cjmakwana** [comment]
Hi @tdykstra sorry as I could not reply back in time. And thanks for sharing that link. I was trying to publish from Windows, which is not supported as per that link.
