### ISSUE TITLE
Add note about multiple loggers

### ISSUE THREAD

**Issue by meziantou** [dotnet/docs#22320]
VSTest allows to specify the "--logger" multiple times. It seems "dotnet test" allow it too. However the documentation is not clear about it. Maybe it could add the same note as the vstest doc: https://github.com/MicrosoftDocs/visualstudio-docs/pull/5482/files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion, @meziantou !
