### ISSUE TITLE
Document CS4009: "an entry point cannot be marked with the `async` modifier"

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#2232]
This should be a high-priority compiler message to document.

**Comment by mairaw** [comment]
And don't forget to remove the F1 keyword from here when you add this one: https://raw.githubusercontent.com/dotnet/docs/4023c5ec72055fee78863a43b60989e1eb34fb22/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md

**Comment by rpetrusha** [comment]
Thanks, @mairaw. I didn't realize the file existed.

**Comment by rpetrusha** [comment]
This has been published at [Compiler Error CS4009](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs4009).
