### ISSUE TITLE
Windows Server 2016?

### ISSUE THREAD

**Issue by clairestreb** [dotnet/docs#22354]
Why is Windows Server 2016 missing from this list?
According to this page (https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10) it says it is compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It's listed generically as Windows Server. The table indicates that 2012 R2 is the minimum version.

![image](https://user-images.githubusercontent.com/67293991/104790206-c12c4600-574b-11eb-910a-80016eba5005.png)

Please note too that you linked to a .NET Framework page. .NET 5/Core and .NET Framework are two different technologies.

I'm going to close this issue. Please feel free to reopen or comment. Cheers!
