### ISSUE TITLE
Guidance for long interface members

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#22368]
Hello,

I'm wondering what the style guide says about long abstract members in interfaces.
Consider the following example:
```fsharp
type IFoo =
    abstract Blah : foo : string -> bar : string -> baz : string -> int

type IFoo =
    abstract Bar : [<Path "bar">] bar : string * [<Path "baz">] baz : string -> Task<Foo>
```

At a certain point, this becomes long and unreadable.
Keeping vanity indentation in mind I would propose the following syntax:

```fsharp
type IFoo =
    abstract Blah : 
        foo : string -> 
        bar : string -> 
        baz : string -> 
        int

type IFoo =
    abstract Bar : 
        [<Path "bar">] bar : string 
        * [<Path "baz">] baz : string -> 
        Task<Foo>
```

What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
This does seem useful to suggest. What should the threshold be? Also worth mentioning in the guide that if your members get that long then maybe you need to consider redesigning them

**Comment by nojaf** [comment]
I've picked the max page width as threshold for the implementation in Fantomas.

**Comment by nojaf** [comment]
@dsyme I raise the original question somewhat here.
After it first popped up in https://github.com/fsprojects/fantomas/issues/1362.
I don't think much thought really went into it.
Looking back at this, stars at the start do really seem inconsistent with all the rest.

For [example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwANAHQCcL1rb70AXATwNIDFZYwBeRiBDxNMTAJbQwubACNEVMAGEqiUYgByiAO4oBg-QBtEAc2IsASogBm8xOhKW8sAwDd5aADImzlmyvuIjs5uNDTo%2BvoAVGBIVpgArgZMHADKABaYVAQAQmJYVGL4ACJiVGjCBejGehFg0Srw8SQAsojYsFQsAKp4mMaIaJaNLW0dLBwGfTUR0WLYBAYSYkwAkvYG8UglZWAVedVhtRCzeGtM8sTibmgy3AbTUWBip%2BgumIvwomKw6CnxBAQOud4Dc7g9BNFYgkkopYARxulMgRYSo0LD4akMlkUYgJlNDkdokxOgBxRBMVoiT4iFJYAh4NKwJhoFYeSyYJBUAAqpPJlI5okwtMw9MZTHBx128AA1tsAPIhApIcrE-ZgOHiH4SupgKiYKq4joAUSoVA6eDQeoNjEYrHYYCKXT40wAPmA5ehSLArLtVVUdXt-bNmAG-cYdUU1Fy5qRolxuAnE0nkynU2n09xIAAacBQPDk8RVPCoMAAbVzEFAtUgABI7cg0JA8kxsxXBLW3hsG2W2-oAAw5o5QNZIZgpMQAL2Qg6OABZe2AALptgC%2BM8rC9r9ZLTeYrerNc78W75aHAEZ1xFIM1MAAPDx5RBeKpMNL7o4ANj7C%2BX%2BjXbarK86zYbtIFuZx330Dt3mPEtTyOAAmS8oJSNoJGcH4AEEmCNdB4DlKwH09SCIjiAx8x-VdL0AqDgPYHdwIMEiIGgrs4IXCAAGZkPbFIiBIbJrA6RAAAVMhwcl5GYwRiWPSi-2ozc6NAxjpNY2C0Hg2pZx4li%2BOIRBBKsYSPFgLR5GgTB8zWFxYEszV0GkiBZMQeTBH-fQaPbZSGLuNTDxgk8OLAABWXSoH0gShJULoAQsqzEBsuyvh%2BJywDIijal-dzFIPbdG1Unj1KCocP3CyBIsM6LEEUSY8DwWF0AqJomA6NKMtcrKqIApT8qgQqlKPEqjgAdnKyqjOE1pZCk8KOrciAPMELyWJ8gq-KKgK2M04KAA5xv4qrjJUWEDFSub3kyiJssW3KgL6sCNsGwL2KHABOA6DMwqxzioWFsGwTA0pchawCWjc8pA3yIM2obXqOM8B2CirDsmlRUOwdCzsci7yM667us83qofWmHnu2ntzwvZHKu%2B36Max87gpBrqFJ6yH6NJpjYZenbzyQ5GRzsJgPR5FgAHVljfXGrv0G6wbu2iHoGg84b5hHuJpw7MLNeI8KKRBFkx37gaoOTWZy9n7pJqBm38tXKYRnTkZvW8VisLk0jsI08fSIFJfgV80tnb8Lduq2lZt3cWx5imtIiM8wpdu81isMRbzldg9VaqgjVvAgVHq74ceCkLQ4JtmiY50C7djjTHdqM8yuT29LDgKh4ADoPwpD0HwbAFaoDW229zr4bG7Glu246eB1HiGaqAIlZzmwYtwrPPvFe8h7sEScRFk9LgqEBphfq5KGx-hxv9uR6eO%2BaPexAPw1j9EE3yugLFLnkAB9LQxEDm%2BTeEdt5R1ruTeu8d9Bng%2Bi3HWeoWByioA%2BYQXdpbBV7mHBWIDVoPXAarXmDcIgISRkOa8d54GYEQcg54TA54LyXivNewUN5YP7oPLcUdd5JCfo%2BI%2BJ8z4XwgePYh1MyGUOoSgikj9n78LfrNZGn9xLQF%2Bn-ABQdgFV2tpzEeMdhFX2IQLMhrsABqgVch4X2GgtKu1y5y0JstYmOjo720IVAwQCFNbGLvBwPWKji4WPgFY9R6ChyYIrpbLRkdnH4KAg7dxEAELO28beIoTIyQ4XzoXPAxdrHhTLpoxx1dobc30erWoCEk7GJkY%2BbIZ1oDSmyHqBp5I8AehSBJU688S5DnmmwreuCo4qziW44KCFm5kM0FoZ%2BgkmDmTsOfdgBs07oGWMXTCeFppyCoMw3pl18b2MrkU7RKknoELjmMyeZCADSiBEAEHdp7OwawOm4CItOYKfSInhyiaAmJo8ylEP0AhG%2BKSfaYwZHkjBdjBDy3YU405ZNzmQLGbAsh44qhGB1sYeewtxaIBkM0BAHy9l40KRDE5JTXEXKHJxUhRxICYUWMYdAvj7AOXHCy0Q8QVBclgELZgKUelHC%2BYcyJxzomItKcikR%2BhOJiIZUy36WArhPh%2BMYLZ8hll5DWT8XZIr9nkoHgiqll9ykRE4kYhlD8eHvI8DgGQnxaqwByVUKZz92qGv6TgoeyszkjJpUcTiXiGUlF6DIIw4LnhpBSCwQVt5PVku9b8wZzi7D4UIo%2BFIrAjDUpRbS5JDLcIZveWlGAVADBWEgEajhw9HpIoDfmoNVSGW3PuQK1Y6Amn6k-om2WsKHEUslaawFCSwCcQmQyup%2BppTvLwDrWAetZ74GBDa-ej484F3wDkvVptzbfOwSm31Qz-W0XicFTiVyp2ZDRogMN0ACiYxVYgeAXRVk-ANtASY2di59oOQOo5Q6-lSrzbKwQnFQUMuzQUFRRKkB-r7rmRcM4mx4A4DkksIMVxAA)

**Comment by dsyme** [comment]
> Looking back at this, stars at the start do really seem inconsistent with all the rest.

Yes, I'd say this should be dealt with the same as `val` signatures, https://github.com/fsprojects/fantomas/issues/1955, with one indent from `abstract`

**Comment by nojaf** [comment]
Resolved by https://github.com/dotnet/docs/pull/27754
