### ISSUE TITLE
If Records aren't supported for IOptions, that should be called out in the documentation

### ISSUE THREAD

**Issue by ddrinka** [dotnet/docs#22361]
It looks like there was some waffling going on with #22210 and #22134.  It appears to me that records are still not actually supported for `IOptions<T>`, though the compiler no longer complains.  If those types are not supported, it would be great to include that note explicitly in the documentation, rather than lettings us deduce the answer as  #22134 attempts to do.

**Comment by BillWagner** [comment]
ping @IEvangelist

**Comment by IEvangelist** [comment]
Hi 👋 @ddrinka
Thank you so much for posting this issue. We really appreciate it. I'm open to updating this even more, but I did address these concerns in #22134 (please see changes) - they were just published this morning I believe on the site.

Records do not work since they do not have a [parameterless constructor](https://docs.microsoft.com/en-us/dotnet/core/extensions/options#options-class). Does that make sense?

**Comment by ddrinka** [comment]
Some of the confusion here is based around https://github.com/dotnet/extensions/pull/2169, where the parameterless constructor was historically part of the contract.  Now I'm able to pass a record into `IOptions<T>`, but it just can't initialize it.

Obviously this isn't the right repo for it, but it seems like a generic IOptionsFactory.CreateInstance that supports records should exist out of the box.

A lot of energy went into supporting records for System.Text.Json, so my anticipation was that the same capabilities would have been added here, which led to my surprise when the documentation included it in a sample which didn't work.  You're right that the sample is removed, but it might make sense to be explicit that records aren't yet supported.

**Comment by ddrinka** [comment]
I've opened https://github.com/dotnet/runtime/issues/46998 to request a change to the underlying lack of support.

**Comment by IEvangelist** [comment]
Hi @ddrinka - we're going to close this for now, until there is proper support for C# records with `IOptions<TOptions>`. Thank you
