### ISSUE TITLE
Possible additional WinForms breaking change for .NET 5.0 re WebBrowser control

### ISSUE THREAD

**Issue by rummelsworth** [dotnet/docs#22365]
If ---

- (a) the example code at [this MS Docs how-to page][wb2w] (.NET Framework 4.8 version only, no version available for .NET 5.0) is intended to show correct and supported usage of the WinForms WebBrowser control's DHTML interop API in .NET Framework 4.8, and

- (b) there were no related changes to the API contract and behavior of WebBrowser between .NET Framework 4.8 and .NET Core 3.1, then

--- the WinForms section of this breaking changes page (for .NET 5.0) should mention something about dotnet/winforms#4443.

If either (a) or (b) is an invalid assumption, then nevermind. Thanks.

[wb2w]: https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/implement-two-way-com-between-dhtml-and-client?view=netframeworkdesktop-4.8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f68af3a-3848-48ef-c24b-cf33b880ca1b
* Version Independent ID: 580c061d-20e5-248c-a24f-7a48a684c7e3
* Content: [Breaking changes in .NET 5.0 - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0)
* Content Source: [docs/core/compatibility/5.0.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/5.0.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@RussKie Should this be doc'd as a breaking change?

**Comment by RussKie** [comment]
Yes, I think we need to document it as a breaking change in 5.0. What's the best way to do this?

**Comment by gewarren** [comment]
@RussKie Can you create a [new issue from the breaking change template](https://github.com/dotnet/docs/issues/new?assignees=&labels=&template=dotnet-breaking-change.md&title=) and we'll link this issue to it? That way I have all the info to document it.

**Comment by RussKie** [comment]
https://github.com/dotnet/docs/issues/22423

**Comment by gewarren** [comment]
I'm closing this issue in favor of #22423, which is in the breaking change format.
