### ISSUE TITLE
Non-public property accessors Question

### ISSUE THREAD

**Issue by assilabdulrahim** [dotnet/docs#22369]
You are talking about Non-public property accessors
Where is the (Non-public property accessors) in your sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f52750-1f3a-3cba-9790-bf36a5ae30a5
* Version Independent ID: cf9fe1d5-1079-025c-73cb-668cc9cbd520
* Content: [How to use immutable types and non-public accessors with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-immutability.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-immutability.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
It's the "private set" and "private get" in the sample:

```
        [JsonInclude]
        public int TemperatureC { get; private set; }

        [JsonInclude]
        public string Summary { private get; set; }
```

(The above is a copy from the article)

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
