### ISSUE TITLE
Prevent OpenPublishing.Build from being required

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#22378]
I believe OpenPublishing.Build should only be required when changes to content are made, or other content specific bits. However, when a _.csproj_ for example changes - it is simply unnecessary to require it.

**Comment by Youssef1313** [comment]
OPB can generate a warning in the (uncommon) case when a csproj is referenced in markdown and it gets renamed/deleted.

See https://github.com/dotnet/docs/pull/22384 which has a warning:

> Invalid code snippet link: '../../../samples/snippets/core/tutorials/testing-with-cli/csharp/test/NewTypesTests/NewTypesTests.csproj'.

**Comment by IEvangelist** [comment]
This is currently based on a webhook, so it cannot be filtered on our end. Additionally, there is no reason to filter this out - as @Youssef1313 has proven above.
