### ISSUE TITLE
ebook dowload link points to the wrong version.

### ISSUE THREAD

**Issue by zappox** [dotnet/docs#22371]
The page mentions that there is an update v5 version but the download link still points to the 3.1 version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Youssef1313** [comment]
The change should be done in https://github.com/dotnet-architecture/eBooks/tree/master/current/microservices

Tagging @sughosneo who previously updated the eBook version.

**Comment by zappox** [comment]
still wrong version. 

The page https://docs.microsoft.com/en-us/dotnet/architecture/microservices/ mentions edition 5, while the link you provided and the download link still points to the 3.1 version

**Comment by zappox** [comment]
> The change should be done in https://github.com/dotnet-architecture/eBooks/tree/master/current/microservices
> 
> Tagging @sughosneo who previously updated the eBook version.

still wrong version.

The page https://docs.microsoft.com/en-us/dotnet/architecture/microservices/ mentions edition 5, while the link you provided and the download link still points to the 3.1 version

**Comment by Youssef1313** [comment]
@zappox Sorry if I confused you. What I meant is that there is no change to be done in dotnet/docs repository. The change should be done in dotnet-architecture/eBooks, and it will reflect the documentation automatically. So, I was tagging @sughosneo to fix the pdf in <https://github.com/dotnet-architecture/eBooks/tree/master/current/microservices>.

To be more clear, the link the docs is using is the same as the pdf relies in <https://github.com/dotnet-architecture/eBooks/tree/master/current/microservices>.

**Comment by zappox** [comment]
@Youssef1313 is there any other download link for the ebook meanwhile by any chance ?

**Comment by sughosneo** [comment]
Hi @zappox,  @Youssef1313,  thank you for pointing out the issue. 
We are in process of updating the PDF version of the `.NET Microservices` eBook to `.NET 5`. It should be available soon. Sorry for the inconvenience.

**Comment by sughosneo** [comment]
Hi @zappox , @Youssef1313 - you can download latest PDF by clicking in [here](https://dotnet.microsoft.com/download/e-book/microservices-architecture/pdf). Thank you.

**Comment by zappox** [comment]
Thank you @sughosneo ! was really looking forward to get my hands on this 👍

**Comment by sughosneo** [comment]
> Thank you @sughosneo ! was really looking forward to get my hands on this 👍

Great ! I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.
