### ISSUE TITLE
Constant and Literal Data Types (Visual Basic)

### ISSUE THREAD

**Issue by worldtraveler58** [dotnet/docs#22386]
Does not include LongLong data type
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253a0a34-7f04-76d1-fb6b-2fa0712778f7
* Version Independent ID: f136c7bc-5d7c-a984-90db-99badea1994a
* Content: [Constant and Literal Data Types - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types)
* Content Source: [docs/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
There is [no such data type in VB.NET](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBsQDdhJhxBLAMwE8AfASTAAcB7BGKAAgGUjY4wBYAKAAUBXYCjwBjBgGEU0RmO4M5DfoJHMBDALIAKAJSz5egCJ4wDAB4MAgowAy1AHYBzGw91yAorYAmK4N3deJUkA===). However, it exists for [VBA](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/longlong-data-type).

**Comment by BillWagner** [comment]
closing as won't fix. You should use the [BigInteger](https://docs.microsoft.com/dotnet/api/system.numerics.biginteger) for this purpose.

**Comment by worldtraveler58** [comment]
Bill,

 

Thanks for the response.  However, I think the various responders
misunderstood the issue.  The environment in question is Access VBA, not
Access or VB.NET.  In Access VBA the data type is LongLong, the equivalent
of Int64.  BigInteger is not recognized.  The page on docs.microsoft.com
that was the subject of my comment ("Constants and Literal Data Types
(Visual Basic)") does not show either data type.  It evidently has not been
updated since 2015.

 

Don Exner

**Comment by Youssef1313** [comment]
@worldtraveler58 The doc page you're referring to is for VB.NET. You were probably confused as the title didn't mention .NET?

@BillWagner Is updating titles to include .NET something you want to consider?

**Comment by worldtraveler58** [comment]
Youssef,

 

You’re right.  I found the page by googling  “Access VBA data types.”  I missed the fact that Google ignored the qualifier. Thanks again.

 

Don Exner
