### ISSUE TITLE
I did not understand this because you don't say what the lambda expression is good for

### ISSUE THREAD

**Issue by Zorph** [dotnet/docs#22389]
[Enter feedback here]
The first part of the explanation should be what the lambda expression is actually doing, this is missing. Something like they state on the W3Schools Java page on that: 
"A lambda expression is a short block of code which takes in parameters and returns a value."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @Zorph We'll get it addressed.
