### ISSUE TITLE
.net or asp.net?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#22387]
> IHttpClientFactory is available since .NET Core 2.1 however we recommend you to use the latest ASP.NET Core 3.1 packages from NuGet in your project. 

Does this intend to say ".NET Core 3.1" and not "ASP.NET Core 3.1"?  If not, should I continue to use 2.1 in my console apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f5aecf-ef1c-5a61-de24-894f4f9032c3
* Version Independent ID: 95c81932-26fd-4a24-3b6f-8dd5bde20026
* Content: [Implement HTTP call retries with exponential backoff with Polly](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @StingyJack, Thank you for reaching out. 

That statement primarily intended to focus on the .NET version. `.NET Core 2.1` still supported but it's recommended to move to `.NET Core 3.1` or `.NET 5`. For more details, you can check out the [.NET Core and .NET 5 release lifecycle](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

Hope this helps !

**Comment by sughosneo** [comment]
The changes for this issue have been merged already. So, closing this issue now.

Thank you.
