### ISSUE TITLE
Sample code technique doesn't protect against length extension attack explicitly. Only relies on the MAC algorithm's strength against such attack.

### ISSUE THREAD

**Issue by afpirimoglu** [dotnet/docs#22400]
In the sample code that does Authenticated Encryption with additional data, it would be more secure if the length of the full message was included as part of the message and of course included in the MAC generation. This would provide defense against length extension attacks. This way received message length can be checked against the length value included in the message, in addition to MAC check. Without such explicit check against message length, it is only relied on the MAC algorithm's strength against length extension or length tampering attacks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabad651-6fa2-432e-27ac-ea5c9d676c8f
* Version Independent ID: 812fd297-5940-111b-1ee8-a1c0440a65be
* Content: [CBC decryption vulnerability](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode)
* Content Source: [docs/standard/security/vulnerabilities-cbc-mode.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/vulnerabilities-cbc-mode.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @blowdart
* Microsoft Alias: **dapine**

**Comment by blowdart** [comment]
The point of a MAC construct is to be resilient to preimage attacks, including length extension attacks, thus we rely on that property to avoid unnecessarily duplication of work. 

If the underlying MAC is insecure, we've got bigger problems.
