### ISSUE TITLE
Code-Snippet of "Deserialize inferred types" does not work anymore

### ISSUE THREAD

**Issue by mhoerandner** [dotnet/docs#22401]
Since *dotnet5* your code-snippet of `ObjectToInferredTypesConverter`-class does not work in some cases. In the past I used this converter for type inference of untyped Json-elements, like in the following class:

```csharp
class MyObjectToSerialize
{
   public int AnyTypedProperty { get; set; }
   public object UntypedJsonProperty { get; set; }  // e.g. "UntypedJsonProperty":{"A":true,"B":42}
}
```

Now if I serialize an object, the `Write`-method of the `ObjectToInferredTypesConverter` is called for any `JsonElement`s. Therefore it is no longer possible to have no implementation (or just throw an exception as in your code-snippet) for the `Write`-method.

```csharp
 var bytes = JsonSerializer.SerializeToUtf8Bytes(myObject, myJsonSerializerOptions);
```

I understand that your example is only intended for the purpose of deserialization, but this also worked for the purpose of serialization quite fine in *dotnet core 3.1*. I think that serialization of `JsonElement`s in older `System.Text.Json`-implementations was done using the `ObjectDefaultConverter`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#deserialize-inferred-types-to-object-properties)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @steveharter @layomia

**Comment by mhoerandner** [comment]
> 
> 
> This behavior changed in this [PR diff](https://github.com/dotnet/runtime/pull/40914/files#diff-f0d0738433a89326a61b5f6e684fa4f7c37899a9841bb47bacc98ffdb002fb32R333-R336), please see the diff and review comment for more info. The new behavior is correct in that there is no reason why a user's custom converter implementation should not be called for both the read and write methods. The old behavior was a bug which needed to be fixed for various reasons detailed in the linked PR.
> 
> This is a breaking change which we need to communicate. A non-trivial number of folks might run into this, since the "Deserialize inferred types to object properties" feature is widely used in `Newtonsoft.Json`, and on by default.
> 
> Work to resolve this issue:
> 
>     * [ ]  Update the doc sample to call `JsonSerializer.Serialize(writer, objectToWrite, objectToWrite.GetType(), options)` , instead of throw `InvalidOperationException`. We may need different implementations for the doc pivots (3.1 vs 5.0) for backwards compat.
> 
>     * [ ]  Document the new behavior as a 5.0 breaking change for JSON. Essentially, `Write` methods for `typeof(object)` custom converters are called in 5.0, whereas they weren't in 3.x.
>       
>       * [ ]  We can consider adding this to the list of breaking changes in ["What's next for System.Text.Json"](https://devblogs.microsoft.com/dotnet/whats-next-for-system-text-json/#breaking-changes)?

@layomia Thak you for the detailed information. Now everything's clear. :)

**Comment by mhoerandner** [comment]
@layomia Thak you for the detailed information. Now everything's clear. :)
