### ISSUE TITLE
CharSet guidelines do not provide guidance on the DefaultCharSet module attribute

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#22403]
No mention is made of `[module: DefaultCharSet(CharSet.Unicode)]` as an alternative to explicitly specifying the charset on all DllImports and structs. Is it a valid or preferable alternative? Or recommended against, and why?

https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#dllimport-attribute-settings

Edit: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset is also missing any mention of this attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea501d3-d963-c5dc-342d-ee82c92d1850
* Version Independent ID: e58f3d16-8083-0efe-0057-e21dbebb262f
* Content: [Native interoperability best practices - .NET](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices)
* Content Source: [docs/standard/native-interop/best-practices.md](https://github.com/dotnet/docs/blob/master/docs/standard/native-interop/best-practices.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by tdykstra** [comment]
@jkoritzinsky Can you help with this question?
