### ISSUE TITLE
Properties of custom collections are not serialized with JSON serialization

### ISSUE THREAD

**Issue by christiannagel** [dotnet/docs#22402]
Using JSON serialization (`System.Text.Json`) of custom collections, it would help adding documentation that the state of collections in addition to the collection is not serialized (e.g. properties of the custom collection).

The documentation at https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-5-0 has this information:

> `System.Text.Json.JsonSerializer` supports a collection type for serialization if it:
> * Derives from `IEnumerable`.
> * Contains elements that are serializable.
>
> The serializer calls the `GetEnumerator()` method, and writes the elements.

Here, it would be helpful adding this information:

> Properties or fields of custom collections are not serialized.

Maybe this information should be added here as well (or only here):

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-5-0#custom-collections

This behavior is described here (along with a project showing this): https://github.com/dotnet/runtime/issues/46920

**Target framework**

- [5.0] .NET
- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a705da7-7165-2d5f-81d1-fdbef196786c
* Version Independent ID: 2f470a1c-8c81-2d26-3cad-92491229db15
* Content: [Supported collection types in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-supported-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-supported-collection-types.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
There's a request for more info in the runtime repo issue: https://github.com/dotnet/runtime/issues/46920#issuecomment-805099891
