### ISSUE TITLE
.NET Core *does* benefit from strong name signing

### ISSUE THREAD

**Issue by AArnott** [dotnet/docs#22412]
This sentence is false:

> For .NET Core, strong-named assemblies do not provide material benefits.

Strong naming assemblies provides assembly name collision resistance. For example two Utilities.dll assemblies that come from different vendors would cause a runtime failure because only one copy can be loaded if neither were strong-name signed. But if they _are_ strong name signed, .NET Core will load them both.

Inaccurate docs like this are causing the .NET community to heavily evangelize _not_ strong name signing libraries when instead they should be evangelizing the opposite, and to "check in the key pair" used to strong name sign in OSS repos so others can build their own version of the library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 699ed58e-fc10-d41e-ac08-fe8df776ab4f
* Version Independent ID: 19e0f0f3-1c3b-4214-76ff-05caec3806ca
* Content: [Strong-named assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named)
* Content Source: [docs/standard/assembly/strong-named.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/strong-named.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by dsplaisted** [comment]
Have you actually run in to a situation like this?  I don't think strong names would help much in the example you give, as the filename is still the same on disk.  The build system probably isn't going to handle it well, and only one of the files can be copied to the output folder.  So you would have to go through a bunch of hoops both in your build to put them in separate folders and then at runtime to load them correctly.

It doesn't seem to me like we should change this statement.

**Comment by IEvangelist** [comment]
Hi @AArnott - I believe that this wording was introduced by @jkotas. Jan do you have any thoughts on Aaron's issue posted here?

**Comment by jkotas** [comment]
>  But if they are strong name signed, .NET Core will load them both.

That is not correct. One of them will win, and the second one will be ignored if you use the standard .NET Core tooling and runtime behaviors; or you may also get an error at build time.

You can implement you custom loader that e.g. loads each assembly into its own separate load context, but then you are creating your own rules that are different from the standard behaviors.

**Comment by AArnott** [comment]
> Have you actually run in to a situation like this?

No. Thankfully people tend to give their assemblies fairly unique names.

> loads each assembly into its own separate load context

That's surprising that that would be required. I knew the steps @dsplaisted mentioned would likely be required (and work on .NET Framework) but I didn't realize that .NET Core's default load context didn't support it at all. 
Why does .NET Core consider two assembly names with differing strong name keys to be equivalent?

I just tested it and sure enough, if I replace an assembly with one with the same simple name but a different strong name public key, .NET Core loads and binds against it without complaining.

I'll close the issue as evidently the docs are correct, as much as this behavior amazes me. I guess I should have tested first.

**Comment by jkotas** [comment]
> Why does .NET Core consider two assembly names with differing strong name keys to be equivalent?

We saw strong naming creating many problems, and having diminishing value in .NET Core. We wanted problems with strong naming to go away in .NET Core. Ignoring strong names was a part of the plan to achieve that.

**Comment by mwwhited** [comment]
This really explains why undeclared breaking changes even on private and internal functions are causing errors throughout the platform.  The build system will only include the highest version number reference even if this version is not binary compatible with dependencies.  (Such problems as not being able to use .Net 6.0 logging assemblies when referencing .Net Core 3.1 compatible versions of WebJobs or Entity Framework.  If you try enjoy the random "Method not defined" exceptions at runtime.)

It would be nice to restore the side by side assembly versions out of the box versus having to control references though multi-target (especially when for all practical purposes ".Net Standard" is useless for versions after .Net 5)

**Comment by russellfoster** [comment]
Gonna add this explanation I found helpful:

https://github.com/dotnet/runtime/issues/81593#issuecomment-1418948008
