### ISSUE TITLE
Utf8JsonReader is obsolete

### ISSUE THREAD

**Issue by pappasa** [dotnet/docs#22427]
I try to write a custom converter, but I get the compile error:

error BC30668: 'Utf8JsonReader' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'.

The code is as follows:

   Private Class DataSetConverter
        Inherits JsonConverter(Of DataSet)

        Public Overrides Sub Write(writer As Utf8JsonWriter, value As DataSet, options As JsonSerializerOptions)
            Throw New NotImplementedException()
        End Sub

        Public Overrides Function Read(ByRef reader As Utf8JsonReader, typeToConvert As Type, options As JsonSerializerOptions) As DataSet
            Throw New NotImplementedException()
        End Function
    End Class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See the note about VB support near the top of the page at https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to

You can't use Utf8JsonReader in Visual Basic, and custom converters require use of the reader, so you can't write a custom converter in VB.

**Comment by NXTwoThou** [comment]
> See the note about VB support near the top of the page at https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to
> 
> You can't use Utf8JsonReader in Visual Basic, and custom converters require use of the reader, so you can't write a custom converter in VB.

What about C#?  I'm getting CS0619: 'System.Text.Json.Utf8JsonReader' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' with a C# ASP.NET v4.8 WebSite.

**Comment by NXTwoThou** [comment]
> @NXTwoThou have you tried setting the [`LangVersion` property in your project](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#edit-the-project-file) to 7.3 or newer?

ASP.NET 4.8 Framework Web Site(as mentioned).  There is no .csproj.

`
<compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CSharp.CSharpCodeProvider" compilerOptions="/langversion:7.3 /nowarn:IDE0058,IDE0059,IDE0060" />
`
in the web.config nets me a "Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, 3, 4, 5, or Default.  Also doing Default gives me the same error.

**Comment by eiriktsarpalis** [comment]
In that case, I would be inclined to say that using STJ in that context is an unsupported scenario.

**Comment by chacham2** [comment]
Just came across this. For anyone else wanting to read the note on VB, the note has been moved to it's own page:

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/visual-basic-support
