### ISSUE TITLE
Deprecate CA1714

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#22424]
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) has been deprecated and replaced by SDK analyzers or [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/).

[Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/) does not have CA1714. Does that mean it has been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f05521-3539-5f96-12b7-ad5a581fa5f3
* Version Independent ID: 2e05100f-adb9-16d3-ee64-44e43e04b0c8
* Content: [CA1714: Flags enums should have plural names (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1714)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1714.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1714.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
I don't think the rule deprecated. But it is included with a separate package `Text.Analyzers`.

**Comment by paulomorgado** [comment]
Yes! @mavasani confirmed that.
