### ISSUE TITLE
Deprecate CA1717

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#22425]
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) has been deprecated and replaced by SDK analyzers or [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/).

[Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/) does not have CA1717. Does that mean it has been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ca87eb-5fbd-30df-e39f-dff946116488
* Version Independent ID: 744ae413-5bc6-463c-6bdc-f952f952bf50
* Content: [CA1717: Only FlagsAttribute enums should have plural names (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1717)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1717.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1717.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #22424.

**Comment by gewarren** [comment]
@mavasani Does Text.Analyzers include CA1717?

**Comment by mavasani** [comment]
We can close this out similar to  #22424, the rule moved to a separate package.
