### ISSUE TITLE
Account declaration

### ISSUE THREAD

**Issue by AryehSamoka** [dotnet/docs#22422]
The following account declaration will throw an exception:
`var lineOfCredit = new LineOfCreditAccount("line of credit", 0, 2000);`
because of the next snippet code:
 `if (amount <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(amount), "Amount of deposit must be positive");
            }`
in the method `public void MakeDeposit(decimal amount, DateTime date, string note)` in the BankAccount class.

The problem begins when this method is being used in the constructor. This begins in the introduction to classes.
I quote: "The constructor should get one change so that it adds an initial transaction, rather than updating the balance directly. Since you already wrote the MakeDeposit method, call it from your constructor."

So more then 0 has to be given when "opening" a bank account or the equal sign has to be erased then amount of deposit has to be non negative or some extra code has to be implemented that on constructing the amount can be zero. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @AryehSamoka 

I'll have to walk through all the steps. I thought I had them in order to make a smooth transition from the starter code.

In the meantime, you can download the finished sample to work through the changes from the finished code.

**Comment by AryehSamoka** [comment]
Thank you very much.

‫בתאריך יום ד׳, 20 בינו׳ 2021 ב-17:05 מאת ‪Bill Wagner‬‏ <‪
notifications@github.com‬‏>:‬
