### ISSUE TITLE
https://aka.ms/sdkimplicititems redirects to renamed #default-compilation-includes

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#22431]
[Microsoft.NET.Sdk.DefaultItems.targets](https://github.com/dotnet/sdk/blob/ef14c79a16171496e2d972edd9a7874d596f624d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L287) references <https://aka.ms/sdkimplicititems>, which redirects to <https://docs.microsoft.com/dotnet/core/project-sdk/overview#default-compilation-includes>. That page still exists but the `default-compilation-includes` anchor does not. The heading "Default compilation includes" was replaced with "Default includes and excludes" in <https://github.com/dotnet/docs/pull/22140>, so the redirection should now be to <https://docs.microsoft.com/dotnet/core/project-sdk/overview#default-includes-and-excludes>.

Although [Explicit anchor links](https://docs.microsoft.com/en-us/contribute/how-to-write-links#explicit-anchor-links) describes a way to change the anchor of the heading back to `default-compilation-includes` while keeping the "Default includes and excludes" text, it advises against doing so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET project SDK overview](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-compilation-includes)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@KalleOlaviNiemitalo Thank you! I've just updated the aka.ms target URL and it seems to be working. Let me know if you find otherwise.

**Comment by KalleOlaviNiemitalo** [comment]
Thanks, it is fine now.
