### ISSUE TITLE
Abbreviated `when` clause unexplained

### ISSUE THREAD

**Issue by SetTrend** [dotnet/docs#22434]
Nice article.

However, there is a "race condition" in the text:

> In the preceding example, the `when` clause was omitted on the final case.

Up to that time in the article, the term _"`when` clause"_ neither occurs or is getting explained.

The previous section merely introduces a _"property pattern"_ and doesn't provide any relation between a _"property pattern"_ and a _"`when` clause"_, nor does it introduce the term _"`when` clause"_.

So, the above mentioned sentence leaves behind a buffled reader.
<br/>

I propose to introduce the term _"`when` clause"_ in the [introduction to "Add occupancy pricing"](https://docs.microsoft.com/dotnet/csharp/tutorials/pattern-matching#add-occupancy-pricing) and create a relation between a _"property pattern"_ and a _"`when` clause"_.

Something like this may be appropriate (I adorned my edit in italics):

> These rules can be implemented using the **property pattern** in the same switch expression. _A property pattern is a special case of `when` clause, comparing a property value to a particular (constant?) value._ The property pattern examines properties of the object once the type has been determined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc5c533-a9ca-cc70-af20-21308e819082
* Version Independent ID: ef6af5d2-b640-0feb-d9d3-7aae0ca92264
* Content: [Tutorial: Build algorithms with pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/pattern-matching)
* Content Source: [docs/csharp/tutorials/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @SetTrend 

I like your suggestion. I made a couple edits to match our style guide:

> These rules can be implemented using the *property pattern* in the same switch expression. A property pattern is a `when` clause that  compares a property value to a constant value. The property pattern examines properties of the object once the type has been determined.

I've added this to our backlog, and I've added the "up for grabs" label if you or someone else wants to create a PR before I make the updates.
