### ISSUE TITLE
Custom format equivalent for "o" date time specifier is incorrect

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/docs#22430]
Partway down the page there is a table that specifies the custom format string equivlent of some of the standard date formats. For the `"o"/"O"` format, it claims that the equivalent custom string is `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzz` (two z's) however this is incorrect. For DateTime the correct equivalent is `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK`. For DateTimeOffset the correct is  the same as for DateTime, but can also be equivalently written as `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzzz` (3 or more z's at the end).

This information is correctly stated [lower on the page in prose](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier), but the table remains incorrect.

Proof that the specified equivalent with two zz is wrong can be seen by running the following code with a non-UTC equivalent time zone:
```
var dt= DateTime.Now;
Console.WriteLine("Standard format:    {0:o}", dt);
Console.WriteLine("Claimed equivalent: {0:yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzz}", dt);
Console.WriteLine("Correct equivalent: {0:yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK}", dt);
```

The source code has a comment that clearly specifies the correct format for DateTime:

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L108-L108

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52741095-f1fd-71b8-15f8-b526480f0d83
* Version Independent ID: 12b2c626-2479-1090-83fd-583c6d600ed8
* Content: [Standard date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings?view=netframework-4.8)
* Content Source: [docs/standard/base-types/standard-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-date-and-time-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
@KevinCathcart Thanks for reporting this - it'll be fixed by #22496
