### ISSUE TITLE
Build time and run time mistaken?

### ISSUE THREAD

**Issue by SetTrend** [dotnet/docs#22435]
> **MSBuild properties**
> [...]
> They also overwrite any options you set in the [appname].runtimeconfig.json file at build time.

Shouldn't this rather read "[...] at **run** time."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa7bda7-581d-9654-c7c5-5ff0292ddfb3
* Version Independent ID: 7f32162e-ec95-0a16-7618-14b7a7c80cff
* Content: [Run-time config options - .NET](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/#msbuild-properties)
* Content Source: [docs/core/run-time-config/index.md](https://github.com/dotnet/docs/blob/master/docs/core/run-time-config/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@SetTrend I believe it's written correctly. At build time, any options in the [appname].runtimeconfig.json file will be updated to match the MSBuild properties for run-time configuration.

**Comment by SetTrend** [comment]
But according to the docs page, `[appname].runtimeconfig.json` doesn't exist before MSBuild is run. It's a generated run-time file, not a solution file. I suppose the corresponding solution file would rather be `runtimeconfig.template.json`.

**Comment by SetTrend** [comment]
Excellent! Thank you for taking the time to deal with this! 👍
