### ISSUE TITLE
Consider having some sort of notifier when files referenced by lines are modified

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22442]
Currently, there are *access-by-line.txt* files for code files that are referenced by line. But they don't add that much value IMO.

- It's not guaranteed they are up-to-date, and most likely they are currently not up-to-date.
- When files are modified, it's very likely that change author will miss checking the lines.

It would be great if there is a bot that posts a comment whenever a PR edits a file that's referenced by line. This will reduce the possibility of breaking articles.

The bot can rely on *access-by-line.txt* (in that case, a build validation will be needed to ensure these files are up-to-date), or find some other mechanism and completely delete these files.

**Comment by BillWagner** [comment]
We agree @Youssef1313 I'll move this to the correct repo to have this addressed by our site team.

**Comment by IEvangelist** [comment]
This issue was moved to MicrosoftDocs/feedback#3407
