### ISSUE TITLE
Add a paragraph for dependency injection scopes.

### ISSUE THREAD

**Issue by Genteure** [dotnet/docs#22448]
I think scope deserves it's own paragraph, explaining it's behaviors and features.
There are texts related to scope scattered in different locations, but no paragraph dedicated to scope itself.

What I think is important to have:

- Is scope nestable / hierarchical? What will happen if I call `provider.CreateScope().ServiceProvider.CreateScope()`? (Currently documented in [General `IDisposable` guidelines](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#general-idisposable-guidelines))
- Disposal of services in scope. ([Disposal of services](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposal-of-services))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Genteure 
Thank you so much for posting this issue. We really appreciate it.

I think you're asking
> Is scope nestable / hierarchical? What will happen if I call `provider.CreateScope().ServiceProvider.CreateScope()`

The answer is, yes, scopes can be nested.

Here is an updated version of the sample source:

```csharp
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace ConsoleDisposable.Example
{
    class Program
    {
        static Task Main(string[] args)
        {
            using IHost host = CreateHostBuilder(args).Build();

            int scopeCount = 0;
            NestedScoping(host.Services, ref scopeCount);
            Console.WriteLine();

            return host.RunAsync();
        }

        static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((_, services) =>
                    services.AddTransient<TransientDisposable>()
                            .AddScoped<ScopedDisposable>()
                            .AddSingleton<SingletonDisposable>());

        static void NestedScoping(IServiceProvider services, ref int scopeCount)
        {
            Console.WriteLine($"Nested scope #{++ scopeCount}...");
            if (scopeCount > 3)
            {
                return;
            }

            using IServiceScope serviceScope = services.CreateScope();
            IServiceProvider provider = serviceScope.ServiceProvider;

            _ = provider.GetRequiredService<TransientDisposable>();
            _ = provider.GetRequiredService<ScopedDisposable>();
            _ = provider.GetRequiredService<SingletonDisposable>();

            NestedScoping(provider, ref scopeCount);
        }
    }
}
```

I updated the disposables as well, adding an `_id` for traceability.

```csharp
using System;
using static System.Guid;

namespace ConsoleDisposable.Example
{
    public class ScopedDisposable : IDisposable
    {
        private readonly Guid _id = NewGuid();
        public void Dispose() => Console.WriteLine($"{_id} - {nameof(ScopedDisposable)}.Dispose()");
    }
}
```

```csharp
using System;
using static System.Guid;

namespace ConsoleDisposable.Example
{
    public class SingletonDisposable : IDisposable
    {
        private readonly Guid _id = NewGuid();

        public void Dispose() => Console.WriteLine($"{_id} - {nameof(SingletonDisposable)}.Dispose()");
    }
}
```

```csharp
using System;
using static System.Guid;

namespace ConsoleDisposable.Example
{
    public class TransientDisposable : IDisposable
    {
        private readonly Guid _id = NewGuid();

        public void Dispose() => Console.WriteLine($"{_id} - {nameof(TransientDisposable)}.Dispose()");
    }
}
```

When you run this, you'll get something similar to the following:

```
Nested scope #1...
Nested scope #2...
Nested scope #3...
Nested scope #4...
64312d0e-e459-40e2-921f-52005a06c550 - ScopedDisposable.Dispose()
6b142e64-82f0-460a-a4b6-bf540457df45 - TransientDisposable.Dispose()
04f65f3c-a6db-463a-b866-1b841f4e4671 - ScopedDisposable.Dispose()
05c26759-cce9-4887-98fd-aced06ea9cfe - TransientDisposable.Dispose()
690ebdd0-97b5-4309-987b-3e2bbcecd1a2 - ScopedDisposable.Dispose()
32e71e46-b2ec-437e-b01e-f84d89e9ab72 - TransientDisposable.Dispose()

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: .\source\repos\dotnetdocs\docs\core\extensions\snippets\configuration\console-di-disposable\bin\Debug\net5.0
c46a6f05-8f53-4e6e-9c7c-28547ed415b9 - SingletonDisposable.Dispose()

```

While this article you posted the issue on doesn't cover much on scoping with regard to DI, the overview has a section dedicated to it [here](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scoped), is that helpful?

Also, there is a full code example that exemplifies scoping [here](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposal-of-services). We decided to break the articles up a bit to isolate their concerns, instead of ending up with massive articles that span too much for consumers.

**Comment by Genteure** [comment]
I was thinking something similar to https://autofaccn.readthedocs.io/en/latest/lifetime/
Most other DI libraries have a section if not a page dedicated to scope and everything scope related.

While it shouldn't be a word count competition, some documents in regards to the usage of scope, specially in places that might be different from other DI libraries would really help.
It feels like the documents is too focus on ASP.NET Core, It's mostly focused on how to correctly setup services to use the scope created by ASP.NET Core than how to manage scope yourself.

My point from #22449 also applies here: Some link for how to use B with A in a harmonious, integrated way would really help, **after** someone understand how B works in standalone.
Though I understand why you might think otherwise.

Group docs related to scope together is more of a "wish" than "want".

---

To be honest I am thinking two steps forward, and this is a two questions in one issue, what I wanted to ask is indeed nested scope.
I'm going to test something before following up.

**Comment by Genteure** [comment]
I think there's a little misunderstanding.
It's not really "nested" or "hierarchical" scope, scope 1 is not the parent scope of scope 2.

Quote last item from [General IDisposable guidelines](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#general-idisposable-guidelines)

> - Use scopes to control the lifetimes of services. Scopes aren't hierarchical, and there's no special connection among scopes.

What I meant is something like [Instance Per Matching Lifetime Scope in Autofac](https://autofaccn.readthedocs.io/en/latest/lifetime/instance-scope.html#instance-per-matching-lifetime-scope)

My test code confirms that it indeed does not have special connection among scopes.
`IServiceProvider.CreateScope` calls `IServiceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope();`.

```cs
using System;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace DiTestWithxUnit
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var serviceCollection = new ServiceCollection();
            IServiceProvider root = serviceCollection.BuildServiceProvider();
            
            using var scope1 = root.CreateScope();
            IServiceProvider provider1 = scope1.ServiceProvider;

            using var scope2 = provider1.CreateScope();
            IServiceProvider provider2 = scope2.ServiceProvider;

            using var scope3 = provider2.CreateScope();
            IServiceProvider provider3 = scope3.ServiceProvider;

            var factory0 = root.GetRequiredService<IServiceScopeFactory>();
            var factory1 = provider1.GetRequiredService<IServiceScopeFactory>();
            var factory2 = provider2.GetRequiredService<IServiceScopeFactory>();
            var factory3 = provider3.GetRequiredService<IServiceScopeFactory>();

            Assert.Same(factory0, factory1);
            Assert.Same(factory0, factory2);
            Assert.Same(factory0, factory3);
        }
    }
}
```

```
> dotnet test

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 13 ms - DiTestWithxUnit.dll (net5.0)
```
