### ISSUE TITLE
directory and files c#

### ISSUE THREAD

**Issue by vigilvp** [dotnet/docs#22440]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25601a0f-eb3c-bf18-04d1-f371f5dc4341
* Version Independent ID: ce7a72d0-6156-f1f8-56ee-9774d93d6d3d
* Content: [How to iterate through a directory tree - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@vigilvp Can you add details to this issue? I'm not sure what you are looking for from this issue title.
