### ISSUE TITLE
csharp_style_prefer_not_pattern documentation isn't clear

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22450]
The example in the doc page:

```csharp
// csharp_style_prefer_not_pattern = true
var y = o is not C c;

// csharp_style_prefer_not_pattern = false
var y = !(o is C c);
```

To me, this implies that if I have set the option to `false`, it will **enforce** the usage of the second form and reports on the first form. However, this doesn't seem to match the implementation:

https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpUseNotPatternDiagnosticAnalyzer.cs#L59-L62

The implementation bails out completely if the option is false, that's just equivalent to disabling the rule.

I'm not sure whether this is an analyzer issue or doc issue.

cc: @mavasani

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8e3fbd2-8203-aade-79d5-34a982d21991
* Version Independent ID: 424ce7cb-e532-a2b0-e686-053c47e48942
* Content: [IDE0083: Use pattern matching ('not' operator) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0083)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0083.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/ide0083.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
@CyrusNajmabadi @sharwell to confirm the intent of the analyzer and the option.

**Comment by sharwell** [comment]
This is a documentation issue. The analyzer is similar to the braces analyzer: it can require one form but it cannot remove it.

**Comment by Youssef1313** [comment]
> This is a documentation issue. The analyzer is similar to the braces analyzer: it can require one form but it cannot remove it.

@sharwell Thanks for clarification. But wondering how this option to false is different than setting the severity to none? In other words, why the option exists if it just enables/disables the rule when there is an another way to do the same?

**Comment by sharwell** [comment]
The option sets the preferred style for other features that generate code automatically, even if the analyzer is disabled.

**Comment by Youssef1313** [comment]
@sharwell Makes sense. I believe the documentation should also mention that.
