### ISSUE TITLE
Thank you very much for a helpful tutorial!

### ISSUE THREAD

**Issue by tienle488** [dotnet/docs#22459]
Really appreciate the lesson.  Knowing F# a bit more now.  Thanks!!
Tien

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c617af-709b-11b6-a329-01f60be31791
* Version Independent ID: 8a0b178d-8ab7-fd3d-202a-cd63b9997bee
* Content: [Unit testing F# in .NET Core with dotnet test and NUnit - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-nunit)
* Content Source: [docs/core/testing/unit-testing-fsharp-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-fsharp-with-nunit.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @rprouse
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thank you @tienle488 We're glad it helped.

Closing as Kudos.

**Comment by tienle488** [comment]
👍

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
