### ISSUE TITLE
Add tip to solve: System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#22455]
@V4A001 created this in https://github.com/dotnet/AspNetCore.Docs/issues/21284

I cannot reach the exact product page where to post this to.

I received suddenly this error by using docker compose. 
`System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.`

I tried all solutions except the one on this page particular for docker compose. Why? Because I never had to and it worked for a couple of months out of the box.

Recreating the developer certificates did not work. So finally I deleted the docker-compose setup in the VS solution. I recreated it by add --> Container Orchestration Support. The running it in either debug and release mode worked again.

I see a lot of people struggling and why this is happening if fully unclear. Maybe you can post it on the right page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf20f50-2d15-1744-386d-1d05ff9931fb
* Version Independent ID: a3c5626b-bbf1-dae0-5cea-0e1135957258
* Content: [Visual Studio Tools for Docker on Windows](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/visual-studio-tools-for-docker)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/visual-studio-tools-for-docker.md](https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/visual-studio-tools-for-docker.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
The original question has been answered in https://github.com/dotnet/AspNetCore.Docs/issues/21284, we can close this issue here.

**Comment by erjain** [comment]
Thanks @Rick-Anderson, for sharing @V4A001's post. For Container Orchestration Support user's can visit: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes).
