### ISSUE TITLE
Subpages for `Naming` and `Formatting` rules should be moved to their parent node

### ISSUE THREAD

**Issue by BartoszKlonowski** [dotnet/docs#22457]
Also, the subpages for Naming rules and Formatting rules should just be moved to their parent node in the TOC.

_Originally posted by @gewarren in https://github.com/dotnet/docs/issues/22196#issuecomment-754086087_

---

@gewarren Please feel free to add more details (for example: what is meant by *parent node*).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a396c1-9c21-75a9-70b5-799cafc941b5
* Version Independent ID: 6d91b560-c12f-6e6d-e92b-1babb27edb67
* Content: [Code style rules overview - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/)
* Content Source: [docs/fundamentals/code-analysis/style-rules/index.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Unsure how to get the PRMerger bot to run and label these automatically after they've been opened.. 🤷‍♂️
