### ISSUE TITLE
Need to update documentation around "-debug" switch

### ISSUE THREAD

**Issue by andrewcrawley** [dotnet/docs#22460]
According to https://github.com/dotnet/runtime/issues/25550, there has been no difference between `-debug:pdbonly` and `-debug:full` since the switch to the Roslyn compilers in VS 2013.  It'd be nice to have the official docs updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3029908f-c2ff-3620-7d51-b9f6a3b768dc
* Version Independent ID: 0f310c2a-3dc6-54a4-5014-264d7f727f2f
* Content: [-debug (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/debug-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/debug-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/debug-compiler-option.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @andrewcrawley I've added this to our backlog to address.

When we update this, we should point out the version implications on the behavior of `pdbonly` and `full`.

**Comment by BillWagner** [comment]
Related to #6773
