### ISSUE TITLE
Had to make a number of adjustments in order for the tutorial to succeed as intended

### ISSUE THREAD

**Issue by tienle488** [dotnet/docs#22472]
I'd start with:
dotnet new sln -o unit-testing-using-mstest

cd unit-testing-using-mstest 

dotnet new classlib -o PrimeService

dotnet sln add ./PrimeService/PrimeService.csproj

Updated Class1.cs to PrimeService.cs with code change  per instructions.  Build Solution or Rebuild Solution successfully with Visual Studio 2019 for example.

dotnet new mstest -o PrimeService.Tests

dotnet add ./PrimeService.Tests/PrimeService.Tests.csproj reference ./PrimeService/PrimeService.csproj

dotnet sln add ./PrimeService.Tests/PrimeService.Tests.csproj

with VS 2019 renamed UnitTest1.cs to PrimeService_IsPrimeShould.cs and replace code  as instructed.
Build solution and get it succeed.

dotnet test
1st test will fail.
Update PrimeService.cs with code  per instruction.
Test now passes.

Add 2nd test  but have to include statement “**var _primeService = new PrimeService();**” before “var result = _primeService.IsPrime(value);”

Rebuild solution and rerun tests.  2nd test fails until PrimeService.cs’ if statement is updated from “if (candidate == 1)” to “**if (candidate < 2)**”.

Hope this helps someone as I struggled with the instructions.
Tien
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Thanks for reporting this error in the tutorial, @tienle488 ! The fix should be live later today or tomorrow.
