### ISSUE TITLE
Code in Example 2 is missing a $ special character meant for string interpolation

### ISSUE THREAD

**Issue by nccsbim071** [dotnet/docs#22473]
**Page**
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/instance-constructors
**Error Description**
Following code under Example 2 of above page is missing a $ special character meant for string interpolation. 
`Console.WriteLine("Name: {person.name}, Age: {person.age}");`
Above line should be following:
`Console.WriteLine($"Name: {person.name}, Age: {person.age}");`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbf6206-5332-f844-ba6a-66b58090f686
* Version Independent ID: 93775018-00ba-2c71-e9e8-da1792f35f9b
* Content: [Instance Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/instance-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/instance-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/instance-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @nccsbim071 

I've added it to our backlog to fix on our next update for this article.

I've also added the "up for grabs" label in case a community member wants to submit a fix before we update it.
