### ISSUE TITLE
[JsonSerializer] Provide doc showing that serialization attributes are honored when deserializing property/field via constructor parameter

### ISSUE THREAD

**Issue by GabeDeBacker** [dotnet/docs#22488]
I am trying to convert from NewtonSoft over to System.Text.Json and all went well until I hit this.

I have many classes like this (because the JSON I'm parsing isn't the best) where I want to "rename" the property in the JSON to something meaningful in the C# code. (This class is pretty much unmodified from the conversion):

```c#
    /// <summary>
    /// Incorporates the cloudiness of the weather.
    /// </summary>
    internal class Cloudiness
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cloudiness"/> class.
        /// </summary>
        /// <param name="all ">The percentage of cloud cover.</param>
        [JsonConstructor]
        public Cloudiness(double all)
        {
            this.Precentage = all;
        }

        /// <summary>
        /// Gets the percentage of cloud cover.
        /// </summary>
        [JsonPropertyName(name: "all")]
        public double Precentage { get; }
    }
```

Except this simple test fails:
```c#
var testString = JsonSerializer.Serialize(new Cloudiness(2));
var testModel = JsonSerializer.Deserialize<Cloudiness>(testString);
```
Each parameter in constructor 'Void .ctor(Double)' on type 'Cloudiness' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

Is there a way to have System.Text.Json map the constructor arguments according to the desired "rename" of the property via the JsonPropertyName attribute? (I really don't want to have to write a bunch of converters for this :()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f52750-1f3a-3cba-9790-bf36a5ae30a5
* Version Independent ID: cf9fe1d5-1079-025c-73cb-668cc9cbd520
* Content: [How to use immutable types and non-public accessors with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability)
* Content Source: [docs/standard/serialization/system-text-json-immutability.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-immutability.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by GabeDeBacker** [comment]
@layomia  - I'm not sure I agree about the documentation issue. I read that documentation multiple times. It does not mention anywhere that JsonPropertyName attribute can be used to effectively "rename" a constructor parameter lookup. I only discovered this through trial and error.

**Comment by ericstj** [comment]
If we do keep the behavior as is, then I think doc issue is the right thing.  We need to make this more clear how JsonPropertyName attribute interacts with the JsonConstructor feature and show some examples.

**Comment by layomia** [comment]
I think that we should keep the existing behavior as is and document it - we expect the property and ctor parameter names to match (case insensitive). This allows data to be round-trippable.

In the above example, it seems to me that the `double all` ctor param was renamed to accommodate a match between the serialized JSON payloads and the constructor arguments. We don't need to do this with `System.Text.Json`.

If after clear documentation, people still struggle with this specific behavior, then we can consider providing the fallback for compat with Newtonsoft.Json.
