### ISSUE TITLE
Incorrect description for dotnet nuget push --no-symbols

### ISSUE THREAD

**Issue by HavenDV** [dotnet/docs#22500]
Incorrect description:
```
-n|--no-symbols true

Doesn't push symbols (even if present).
```

`dotnet nuget push --help` returns different description:
```
Run dotnet nuget push src\**.nupkg --api-key *** --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
Specify --help for a list of available options and commands.

Usage: dotnet nuget push [arguments] [options]

Options:
  -h|--help                      Show help information
  -n|--no-symbols          If a symbols package exists, it will not be pushed to a symbols server.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Hello. This description is still accurate even if it doesn't use the same exact words.

Although, the `true` seems out of place according to the help.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
