### ISSUE TITLE
Finalizers example doesn't print the output as mentioned

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22513]
See https://github.com/dotnet/docs/pull/22485#discussion_r564061019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
The example prints output as mentioned when run on .NET Framework. Note that it should be run with debugger attached and the text is printed to debugger output window, **not** to the console. On .NET Core, finalizers are not called automatically on shutdown, so indeed that example won't work.

There's also another issue that discusses updates to this article: https://github.com/dotnet/docs/issues/17463
