### ISSUE TITLE
What's the default value?

### ISSUE THREAD

**Issue by swatt6400** [dotnet/docs#22528]
No mention of what the default behaviour is if this setting is omitted from the config file altogether.  Is it true or false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8d857c-3c4c-7c87-ce82-9912438300ca
* Version Independent ID: a0a606c4-0339-07d1-93b9-f7848a35baa7
* Content: [&lt;PreferComInsteadOfManagedRemoting&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/prefercominsteadofmanagedremoting-element)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/prefercominsteadofmanagedremoting-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/prefercominsteadofmanagedremoting-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
The table says that `false` is the default:

![image](https://user-images.githubusercontent.com/31348972/106016208-e3b54c00-60c7-11eb-85c8-7f4f40abdc52.png)

**Comment by gewarren** [comment]
@swatt6400 The default is specified, as @Youssef1313 pointed out, so I'm going to close this issue. Leave a comment if you still think something's missing.
