### ISSUE TITLE
Unable to find packages for dotnet after enabling the repo for centos7

### ISSUE THREAD

**Issue by github-anurag** [dotnet/docs#22526]
I was following the instructions on: https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos 
However even after adding the repo in centos7,  I don't see the .NET sdk available for download. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577ce9b2-5b48-4ed2-c309-a78880015dd2
* Version Independent ID: 26300783-8df5-56a1-4ab6-4b8511e37f51
* Content: [Install .NET on CentOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos)
* Content Source: [docs/core/install/linux-centos.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-centos.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. There is an issue opened in the .NET source repository tracking RHEL and CentOS: dotnet/core#5596 I don't know if they can help your issue or not though. You'll need to provide a lot more information like what commands you ran and the output of those commands. If they can't help you in that issue, I would open a new one in that same repository. Sorry I can't be more help.

I'm going close this issue.
