### ISSUE TITLE
Provide a sample using for the explanation

### ISSUE THREAD

**Issue by quangnx** [dotnet/docs#22525]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64013963-3eb9-ec55-6492-f2be438f172d
* Version Independent ID: b1cedece-a1c6-455f-ac5f-2cabd6a1ec18
* Content: [Trace Listeners](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/trace-listeners)
* Content Source: [docs/framework/debug-trace-profile/trace-listeners.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/trace-listeners.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hello. There are two links in the article:

- [How to: Create and Initialize Trace Listeners](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-and-initialize-trace-listeners)
- [How to: Use TraceSource and Filters with Trace Listeners](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-use-tracesource-and-filters-with-trace-listeners)

There are also some articles listed on the left-side TOC.

![image](https://user-images.githubusercontent.com/67293991/106036826-a54d6c00-608a-11eb-85e6-85f1af3c246b.png)

Hope this helps. I'm going to close this issue.

**Comment by quangnx** [comment]
thks
