### ISSUE TITLE
Confusion between bullet list and table

### ISSUE THREAD

**Issue by formsoverdata** [dotnet/docs#22523]
The bullet list states Microservices: Choose AKS or Azure Web Apps for Containers
But the table does not have a grey or blue tick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45be6d71-575d-5d8d-bcdc-b6885ddbb487
* Version Independent ID: 7c37b77a-63fc-4fb4-ae32-02ac9c09e1c8
* Content: [Choosing Azure compute platforms for container-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @formsoverdata , thank you for your feedback.
