### ISSUE TITLE
Incomplete example that only confuses the beginner

### ISSUE THREAD

**Issue by dancaugherty** [dotnet/docs#22539]
This page doesn't go far enough with the sample code. What would the next steps be after creating the Utilities class and its ShowConsoleAnimation() method? How would we invoke it within the main() block of the main program (to avoid any top level code)?

What a letdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb444ad7-d74e-3564-3b48-63bbbec2bccc
* Version Independent ID: b8c93c17-371b-b1d1-d606-513f56f6c22e
* Content: [Top-level statements - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/top-level-statements)
* Content Source: [docs/csharp/tutorials/exploration/top-level-statements.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/top-level-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @dancaugherty 

I've added this to our next sprint project.  In the meantime, you can look at the [finished sample code](https://github.com/dotnet/docs/tree/master/docs/csharp/tutorials/exploration/snippets/top-level-statements) to see the complete solution.
