### ISSUE TITLE
Code examples on the "Private Constructors (C# Programming Guide)" page are not visible

### ISSUE THREAD

**Issue by gglup** [dotnet/docs#22536]
It seems that the Snippet2 hasn't been closed properly in the following file:
https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/snippets/private-constructors/Program.cs#2
which makes the two code Examples invisible on the following page:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/private-constructors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aed1d9c-756b-5edc-5c2e-4c25af577ffd
* Version Independent ID: d6b5ce45-a2d6-279e-68fe-280c0774dbcb
* Content: [Private Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/private-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/private-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/private-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @gglup 

I've opened #22550 to address this issue.
