### ISSUE TITLE
Statements about the short-circuiting behavior of the null-conditional operator could be clearer

### ISSUE THREAD

**Issue by m-ringler** [dotnet/docs#22548]
Instead of just `A?.B?.C()`, it would be good to say that `A?.B.C()` will also not result in C() being called if `A` is null and that it is therefore different from `(A?.B).C()`. You should also state that this also holds when C() is an extension method and that `ExtensionClass.C(A?.B)` is thus different from `A?.B.C()`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @m-ringler Those are good points.

I've added that our our backlog to address.
