### ISSUE TITLE
Example in document is out of date with respect to "SimpleConsoleFormatterOptions.DisableColors"

### ISSUE THREAD

**Issue by richardthombs** [dotnet/docs#22558]
The code sample showing how to use `SimpleConsoleFormatterOptions` is incorrect as`SimpleConsoleFormatterOptions` does not have a `DisableColors` property.

Instead the `ColorBehavior` property should be used:

```c#
loggingBuilder.AddSimpleConsole(options =>
{
    options.ColorBehavior = LoggerColorBehavior.Disabled;
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8323edda-ffc6-2ccc-d1fe-a16899a61257
* Version Independent ID: 0b5a208c-38bf-3063-e8b5-b90ebf9258ca
* Content: [Breaking change: Obsolete properties on ConsoleLoggerOptions - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/obsolete-consoleloggeroptions-properties)
* Content Source: [docs/core/compatibility/core-libraries/5.0/obsolete-consoleloggeroptions-properties.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/core-libraries/5.0/obsolete-consoleloggeroptions-properties.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@richardthombs Thanks for reporting this!
