### ISSUE TITLE
ByRef is the default, not ByVal, when using Sub statements with parameters

### ISSUE THREAD

**Issue by R-Parker** [dotnet/docs#22566]
[Enter feedback here]

Hi Microsoft Docs team, I discovered an inaccuracy in the documentation article about `ByVal`, found at: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/byval.

The documentation states that "If no modifier is specified, ByVal is the default. ... Because it is the default, you do not have to explicitly specify the ByVal keyword in method signatures. It tends to produce noisy code and often leads to the non-default ByRef keyword being overlooked."

However, as my Excel VBA code below demonstrates, `ByRef `is the default value, not `ByVal`, when using parameters with `Sub `statements.

```
Sub firstSub()
    Dim varOne As Byte
    varOne = 1
    Debug.Print "Value of varOne: ", varOne
    Call secondSub(varOne)
    Debug.Print "Value of varOne is now: ", varOne
End Sub

Sub secondSub(varTwo As Byte)
    Debug.Print "Value of varTwo is: ", varTwo
    varTwo = 2
    Debug.Print "Value of varTwo is now: ", varTwo
End Sub

' Prints the following:
' Value of varOne:             1 
' Value of varTwo is:          1 
' Value of varTwo is now:      2 
' Value of varOne is now:      2 

' Now, showing difference when ByVal keyword is used:
Sub firstSub()
    Dim varOne As Byte
    varOne = 1
    Debug.Print "Value of varOne: ", varOne
    Call secondSub(varOne)
    Debug.Print "Value of varOne is now: ", varOne
End Sub

Sub secondSub(ByVal varTwo As Byte)
    Debug.Print "Value of varTwo is: ", varTwo
    varTwo = 2
    Debug.Print "Value of varTwo is now: ", varTwo
End Sub

' Prints the following:
' Value of varOne:             1 
' Value of varTwo is:          1 
' Value of varTwo is now:      2 
' Value of varOne is now:      1
```

Also, here's another source that confirms that ByRef is the default: https://bettersolutions.com/vba/macros/byval-or-byref.htm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3085184c-671d-92b5-b596-3af0a848b7c8
* Version Independent ID: 4b8973b8-47df-64cd-98ff-5b3ea17860cf
* Content: [ByVal - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/byval)
* Content Source: [docs/visual-basic/language-reference/modifiers/byval.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/byval.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
I don't know about VBA. However, this documentation is for VB.NET, not VBA. The information is correct for VB.NET.

**Comment by R-Parker** [comment]
Thank you, Youssef. I appreciate your response, and that makes sense that it could be different in .NET vs VBA. I found this page when searching “Excel VBA is ByRef or ByVal default<https://www.google.com/search?q=excel+vba+is+byval+or+byref+default>” and also “ByVal VBA<https://www.google.com/search?q=byval+vba>,” so I assumed that the reference pertained to VBA without even checking. Thank you for clarifying that for me.

Ryan Parker

**Comment by BillWagner** [comment]
closing per conversation.
