### ISSUE TITLE
Supported Releases Table missing entries?

### ISSUE THREAD

**Issue by AiDevAz** [dotnet/docs#22561]
Hi All

On the Supported Releases table, we have 3 times Windows 10 1607 listed, why?
But we are missing windows Server 2016 or Windows Server 2019.

https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#supported-releases

Regards Adrian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
