### ISSUE TITLE
Visual Studio integration

### ISSUE THREAD

**Issue by littlecreature** [dotnet/docs#22562]
I used this tutorial to extend visual studio 2019 so it shows my custom templates

[https://auth0.com/blog/create-dotnet-project-template/](https://auth0.com/blog/create-dotnet-project-template/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d0e779-2a93-d2b8-3fb0-8c88812a4fc7
* Version Independent ID: 2e4ef5da-1b4b-a1d7-7ec8-6169360bf315
* Content: [Create a template pack for dotnet new - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack)
* Content Source: [docs/core/tutorials/cli-templates-create-template-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-template-pack.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Glad it helped! I'll close this issue.
