### ISSUE TITLE
Readability improvement - "person 2"

### ISSUE THREAD

**Issue by chefchaouen** [dotnet/docs#22578]
First off let me say Microsoft documentation is extremely high quality and a pleasure to read. That being said, as shown in the yellow highlight below, "person 2" in the text portion could be changed to "person2" to match the actual variable name as written in the source code example below it. Thanks for all your tremendous work in making this fantastic documentation!

![image](https://user-images.githubusercontent.com/53887140/106355852-0781c780-633e-11eb-9dba-571a20f10e4d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433a56c8-1c93-32fb-eb1d-8395a9760c65
* Version Independent ID: e3f35410-f243-4309-1436-89ade7a34d19
* Content: [Objects - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/objects)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @chefchaouen. And thank you for the kind words on our docs in general.

I've opened a PR to address this issue.  In the future, when you find these small concerns, it may be quicker to submit a PR than an issue. Click the edit button (it looks like a pencil), and you can make the changes and we'll see exactly what needs to be fixed.

Thanks again.
