### ISSUE TITLE
Missing something...

### ISSUE THREAD

**Issue by sej69** [dotnet/docs#22588]
I've been around and around on this for about a week now.  When I do this in VS 2019 on Win10, it wants to compile for "Any CPU".  I'm assuming this is wrong and it should be to ARM (but that option does not exist).  I was able to create code on the PI and compile it through command line, but I don't get the code syntax checking there.  I also was able to get the C++ version working (and ARM is a compile target there), however, I'd prefer sticking with the main language I've been working in for 20 years...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d324d803-c39c-9d73-0fd7-5800406a2309
* Version Independent ID: 8a4a5b84-de72-fe16-e78c-d402699282b1
* Content: [Blink an LED](https://docs.microsoft.com/en-us/dotnet/iot/tutorials/blink-led)
* Content Source: [docs/iot/tutorials/blink-led.md](https://github.com/dotnet/docs/blob/master/docs/iot/tutorials/blink-led.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
"Any CPU" is correct. What are you experiencing, exactly?

**Comment by sej69** [comment]
It creates a .EXE file and if I try running that in the PI I get “cannot execute binary file: Exec format error”.

However, the native compiled versions of the app in PI don’t have the .exe extension and do run.

**Comment by Youssef1313** [comment]
@sej69 Have you followed [these instructions](https://docs.microsoft.com/en-us/dotnet/iot/deployment#deploying-a-self-contained-app)?

**Comment by sej69** [comment]
Yes, it works if I compile it by hand but then again, I know it’s compiling at the ARM target.  I would like this to work in my development environment vs coding on the PI.

**Comment by sej69** [comment]
I just tried this from the package manager console prompt and it did compile it correctly.  Do I have to compile through a console prompt or can I build / deploy through the VS 2019 “build” menu option?

**Comment by adegeo** [comment]
@sej69 

.NET automatically generates a native x64 executable based on your current OS. These executables (such as `appfile.exe`) invoke your `appfile.dll`. You can run this dll on other OS by calling `dotnet appfile.dll`.

You can publish to ARM and generate a native ARM Linux executable by using the `dotnet publish -r linux-arm` command from that the article @Youssef1313 linked to. You can do this from Windows, you don't need to be on the Pi to generate the executable.

**Comment by sej69** [comment]
So compiling this, I would need to do the dotnet publish -r linux-arm each time?  Or can I use the in visual studio menu option to “build”?  When I do that, I seem to not get an linux operational program?

**Comment by sej69** [comment]
Ok, thanks, I’ll try that later today.

**Comment by sej69** [comment]
Yeah, no screenshots came through…

**Comment by sej69** [comment]
Do I have to compile on Win10 then deploy or can I compile directly to Linux (PI) through my Win10 VS2019?  I did find an article that was a little dated that referred to setting up remote debugging.  It’s hard to know what’s current and not now a days…

**Comment by adegeo** [comment]
Yes, you can cross-compile, but you need to setup a debugger if you wanted to actually RUN/DEBUG in Visual Studio. The Target Runtime option in the publish window lets me select **linux-arm**. The build configurations of **Release(or Debug) | Any CPU** are the defaults. If you were to create a platform specific **build** config, it would appear in that drop down. They're just easy ways for you to have multiple **build** configurations based on mode (Debug or Release) and specific CPUs **IF** you wanted to.

If you don't have a custom **build** configuration settings. This is different from your publishing profiles you're configuring in the screenshots I provided. You don't really have to worry about **Any CPU**, it's fine the way it is.

I think your question is answered and I'm going to close this issue. If you want to target a different CPU though, the command line may be the easiest way to do that if Visual Studio doesn't provide you the options.

Cheers!
