### ISSUE TITLE
Managed code

### ISSUE THREAD

**Issue by SamZhangQingChuan** [dotnet/docs#22581]
I have a question about this line `C++ is the one exception to this rule, as it can also produce native, unmanaged binaries that run on Windows.`

Why `also`? Isn't C++ code always unmanaged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c021566-b09c-3a48-f14b-209526a428a1
* Version Independent ID: 0561b29e-2239-43bf-2a18-c5c0a2891fcd
* Content: [What is managed code?](https://docs.microsoft.com/en-us/dotnet/standard/managed-code)
* Content Source: [docs/standard/managed-code.md](https://github.com/dotnet/docs/blob/master/docs/standard/managed-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
Nope, C++ isn't always unmanaged. See <https://en.wikipedia.org/wiki/C%2B%2B/CLI>

**Comment by gewarren** [comment]
Here's another reference: https://docs.microsoft.com/en-us/cpp/dotnet/mixed-native-and-managed-assemblies?view=msvc-160. I'm going to close this issue as answered.
