### ISSUE TITLE
Please add note on record-class deconstruct here

### ISSUE THREAD

**Issue by deusaquilus** [dotnet/docs#22583]
Since this page is all about Deconstruct, there should at least be a note that with C# 9 record-classes come with a built-in deconstruct function. Probably add a short section on using that.

edit by @billwagner. Add blank line to unbold description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @deusaquilus 

I've added it to the list of items to address for C# 9.
