### ISSUE TITLE
Scripts not up-to-date

### ISSUE THREAD

**Issue by RanchoHam** [dotnet/docs#22589]
[The scripts listed here and presumably elsewhere are not current as they reference the dotnet-sdk-5.0.100-linux-x64.tar.gz and not the dotnet-sdk-5.0.102-linux-x64.tar.gz.

Furthermore, I was trying to install on an raspberry pi 4 machine so the architecture should have been arm64, i.e. dotnet-sdk-5.0.102-linux-arm64.tar.gz.

Since I started from the pages with scripts to install on Ubuntu 20.10, presumably those scripts are also similarly flawed.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Manually install .NET on Linux - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-scripted-manual.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for the feedback. Unfortunately it would take up too much room to detail every possible supported version/platform/architecture combination. The article does state (right before the first command):

> The archive file name may be different depending on what you downloaded.

What I'll do though is add a variable to the script which will hopefully make this more apparent.
