### ISSUE TITLE
Show implementation Example in service singleton class.

### ISSUE THREAD

**Issue by CodeChaser** [dotnet/docs#22596]
The document shows the initialization but does not follow through with an implementation showing the DI in play in a down stream service.  I did find an example, but from almost 2 years earlier in mid '19.  With ever growing 'subtle' changes in .Net happening all of the item, recent articles need to provide full complete  examples.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9
* Version Independent ID: 22a12ff8-d2ff-a841-b9bb-e2fd1032bc04
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host)
* Content Source: [docs/core/extensions/generic-host.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/generic-host.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @CodeChaser
Thank you so much for posting this issue. We really appreciate it.

I'm looking for a bit more clarification. You're looking for an example of a singleton service being consumed, where you expecting it in the Generic Host article? We have other articles that are specific to DI that do include those kinds of examples.

- [Dependency injection in .NET - Singleton](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#singleton)
- [Dependency injection tutorial - (Examples with singleton scoping)](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)

Does any of this help?

**Comment by CodeChaser** [comment]
Wow Thanks Dave for a Quick reply,

First let’s assume I am reasonable strong with overall DI usage.  As a baseline…

Env Background
=============
.Net 3.1 Core
VS2019

Current CodeBase
===============

public static async Task Main(string[] args)
        {

            // create service collection
            var services = new ServiceCollection();
            ConfigureServices(services);

            // create service provider
            var serviceProvider = services.BuildServiceProvider();

            // entry to run app
            await serviceProvider.GetService<Startup>().Run(args);
        }

        private static void ConfigureServices(IServiceCollection services)
        {

            // configure logging
            services.AddLogging(builder =>
            {
                builder.AddConsole();
                builder.AddDebug();
                builder.AddEventLog();
            });

            // build config
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false)
                .AddEnvironmentVariables()
                .Build();

            services.Configure<AppSettings>(configuration.GetSection("AppSettings"));
            services.Configure<ConnectionStrings>(configuration.GetSection("ConnectionStrings"));
    }


  *   Using a ConfigurationProvider pattern for the sake of discussion..
  *   DI IOptions<AppSettings> appSettings
  *   Allowing me to have direct access to my the appsettings.json in a strongly type way etc..  its clean


  *   My goal is to the do the same with “Task Main(string[] args)” , of course focus is on the args.
  *   My search for a (.Net Core Console App) DI for args led me to the page “.Net Generic Host”
  *   I am intrigued by the “.Net Generic Host” , but looks like I have to move away from the
     *   ConfigurationBuilder and move to the “IHostBuilder & the .ConfigureHostConfiguration(…  as shown below.. from the doc..)
  *   As I search for further details, to see a sample implementation, it does not exist yet in our dimension, jokingly of course..
     *   Forces me to bail…  as I got to much “agile task” focus to do R & D on this at this moment.
     *   I found one other but it is quickly getting verbose in code
        *   Using CommandLineParser in a way friendly to Dependency Injection (siderite.dev)<https://siderite.dev/blog/using-commandlineparser-in-way-friendly-to-depende/>
        *   commandlineparser/commandline: The best C# command line parser that brings standardized *nix getopt style, for .NET. Includes F# support (github.com)<https://github.com/commandlineparser/commandline>
  *   This to me is cool, but it is a little heavy for my implementation… but I might have to use it.
  *   I like what he did with the Options..

With all of this I was looking for some basic implementation of using Console Args with DI and Options…. I felt the doc page I commented on could use a little more details .. i.e. exposing an implementation like AppSettings, an an IOptions implementation and/or link .. since I have your attention.

static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureHostConfiguration(configHost =>
            {
                configHost.SetBasePath(Directory.GetCurrentDirectory());
                configHost.AddJsonFile("hostsettings.json", optional: true);
                configHost.AddEnvironmentVariables(prefix: "PREFIX_");
                configHost.AddCommandLine(args);
            });

Again thanks for reaching out…

Wishing you/family/friends all the health, safety n well being,

Tom Kelly
www.linkedin.com/in/thomas-f-kelly-jr-tampa<http://www.linkedin.com/in/thomas-f-kelly-jr-tampa>

MCT: Azure Developer

**Comment by CodeChaser** [comment]
Hi Dave,

                By typing up your email reply it got me to thinking during lunch here EST “Tampa”.   As stated that example article & associated github, is way to heavy as well in some ways “dated”…   No matter, I found this which may be giving me what I need to take command arguments to a DI level combined with your doc .
Cysharp/ConsoleAppFramework: Micro-framework for console applications to building CLI tools/Daemon/Batch for .NET Core, C#. (github.com)<https://github.com/Cysharp/ConsoleAppFramework#consoleappoptions>

Regards,
Tom

**Comment by CodeChaser** [comment]
Dave,  I forgot an important link..

Options pattern in .NET | Microsoft Docs<https://docs.microsoft.com/en-us/dotnet/core/extensions/options>

Between this, the ConsoleFrameworks and your doc I will try to piece together a simple IOptions<ComandLineArgs> DI .

Later,
Tom

**Comment by IEvangelist** [comment]
Hi again @CodeChaser - I'm playing catch up. The options pattern article is a great resource too, and now I have a better understanding of what you're trying to accomplish. Using the options pattern, you're able to rely on all sorts of configuration providers, whether it is from command line arguments, the file system, etc. See, https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration for more details - and please let me know if you need more help. Based on your replies, it sounds like you were able to figure everything out? If not, we can reopen this issue. Thanks again.

**Comment by CodeChaser** [comment]
Thanks for replying.  I resolved it weeks back, but really appreciate the follow up.  Tom...
