### ISSUE TITLE
Dead link in F# interactive documentation

### ISSUE THREAD

**Issue by pmbanka** [dotnet/docs#22594]
The link in "note" box https://docs.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/#referencing-packages-in-f-interactive is dead (leads to 404).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db36a87c-0928-52ce-38f3-1555e450cce1
* Version Independent ID: 400ddb93-a841-963b-58cc-21f506b13b61
* Content: [F# Interactive (dotnet) Reference](https://docs.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/#referencing-packages-in-f-interactive)
* Content Source: [docs/fsharp/tools/fsharp-interactive/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tools/fsharp-interactive/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
This seems to have fixed itself. The link is working for me. I'll close the issue, but if you still feel there's a problem, please leave a comment.

![image](https://user-images.githubusercontent.com/24882762/107300505-835ecc80-6a2e-11eb-955a-9ab893292535.png)
