### ISSUE TITLE
404 Links for dotnet add package and dotnet remove reference

### ISSUE THREAD

**Issue by scottsauber** [dotnet/docs#2259]
This page: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/ has a link to "add package" under Project modification commands

That "add package" link takes you here: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-add-package which 404's.  The URL looks consistent with the others... so I'm not sure what's going on.

The add package docs exist here: https://github.com/dotnet/docs/blob/d97a1501ad25b683cbb5d7fbd8bd1b137f7f4046/docs/core/tools/dotnet-add-package.md, so it almost seems like a deployment issue.

This same issue appears to be happening for the "remove reference" link as well, but the other dotnet cli command links work fine.

**Comment by svick** [comment]
I also currently [do not see the TOC on the left side](http://api.browsershots.org/png/original/7c/7c2384c483775c14fb036067d69c8e41.png), so it indeed seems like some kind of deployment issue to me.

**Comment by mairaw** [comment]
We have a major change being published this morning which is causing some of these issues and we are actively working on it to resolve them. But the URLs for me don't 404.

**Comment by mairaw** [comment]
I have updated all the aka.ms links to go to the new URLs (basically it's the same url without articles on them).  e.g. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package

redirection is in progress and I have a PR to try to fix the TOC issue in the new URLs.

**Comment by svick** [comment]
@mairaw I got 404 on https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-add-package at the time when I wrote my comment, but now it works fine for me.

**Comment by mairaw** [comment]
I'm starting to get some 404. Hopefully redirection will finish soon. I also have a build going that might temporarily fix the TOC issue but we need a permanent solution.

**Comment by mletterle** [comment]
Can confirm that I am seeing redirections going live, thanks!

**Comment by scottsauber** [comment]
Yep - works for me now too.  Closing this.  Thanks!
