### ISSUE TITLE
Code quality rule IDE0064 is listed as a style rule (language rule)

### ISSUE THREAD

**Issue by tstewart-writer** [dotnet/docs#22603]
**Issue description**

Code analysis rule [IDE0064](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0064) seems to be in the wrong section. The table at the top of the page says it is in the CodeQuality category, but it also puts it in the Language Rules subcategory of style rules. From the description of the rule it looks like a code quality issue because it deals with code reliability rather than clarity or style.

Edit:
As I looked through more of the style rules, I found additional rules which are listed under style rules, but whose doc pages list them as code quality rules.
These include:

- [IDE0051](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0051)
- [IDE0052](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0052)
- [IDE0076](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0076)
- [IDE0077](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0077)

**Target framework**

- [X] .NET Core
- [X] .NET Framework
- [X] .NET Standard

**Comment by Youssef1313** [comment]
It's listed as a style rule because it's an IDExxxx. See [code-style analysis](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/overview#code-style-analysis) which mentions:

> Code-style analysis ("IDExxxx") rules enable you to define and maintain consistent code style in your codebase.

While most IDExxxx rules are code-style rules, there are few exceptions.

This is most likely by-design.

But let's wait for @gewarren or @mavasani.

**Comment by mavasani** [comment]
Yes, @Youssef1313 is correct. We have considered porting IDE0064 to a CA code quality rule and probably have an issue somewhere for it. IDE0051 and IDE0052 are unnecessary code rules and many users see unnecessary code rules as style, also it might be a breaking change to replace these rules with a different CA id if they are already enforced on build by existing repos. I think we probably have to stick with current IDs and ensure correct categorization for new rules going forward.

**Comment by gewarren** [comment]
Thanks for the responses; I'm going to close the issue now.
