### ISSUE TITLE
Clarify what is meant by "os_version" in the troubleshooting apt-get section

### ISSUE THREAD

**Issue by gerryg80** [dotnet/docs#22619]
The page describes "{os_version}" as "This represents the Linux version you are on". There are no examples so we're left to guess. Linux is the kernel so that would mean the kernel version or possibly something like linux_amd64 vs linux_arm64.

It's actually looking for the _Ubuntu Version_ and specifically the numeric version such as 20.04 or 18.04 and not the name (e.g. 20.04 = "focal")

Referring to that as **Ubuntu Version** and listing explicit examples of the most recent numbered versions would clear that up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for this feedback! I'll get these updated. It's a bit hard to be clear as this content is shared across multiple distributions and versions.
