### ISSUE TITLE
The TAP example is missing the async keyword.

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#22626]
The presence of that keyword is what makes the function asynchronous for TAP, not the return type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e1e71b-7af7-9488-2cba-fdde9fb5d4be
* Version Independent ID: 5a1c3614-34ce-2eb1-9cc3-066320cfed0a
* Content: [Asynchronous programming patterns](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/)
* Content Source: [docs/standard/asynchronous-programming-patterns/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@StingyJack 

The article is correct. Any method that returns a `Task` (or other type that supports the pattern) can be awaited. In practice, most methods that return a `Task`-like type do have the `async` modifier, but it's not strictly necessary.

Closing as by-design.

**Comment by StingyJack** [comment]
@BillWagner  - from this page

> The async and await keywords in C# and the Async and Await operators in Visual Basic add language support for TAP

If you dont have the language support for TAP, because you did not use `async` or `await`, I dont see how you can have an awaitable or valid example of TAP without the `async` keyword. 

The point of issue for me is actually the conditions for naming the function with an "Async" suffix. Given the scenario of a non-async keyworded function that returns a Task, there is no need to name the function with an async suffix because the Task return types are handles to be completed later. If you have an async keyworded function, then adding the Async suffix makes sense because the return type in the method has different handling, and because the async keyword is not something that can be included in something like an interface definition.

[This](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model#BKMK_HowtoWriteanAsyncMethod)  is the advice that I've always seen on this topic and that contradicts this document.
![image](https://user-images.githubusercontent.com/15381181/106783621-7a7a8f00-6619-11eb-8319-023ac73a154b.png)

**Comment by IEvangelist** [comment]
Ah, I think I see the misinterpretation here. My advice is to always suffix methods that have a Task-like return type with "Async".
A non-exhaustive list, but methods returning any of these types for example would be suffixed with "Async":
- `Task`
- `Task<T>`
- `ValueTask`
- `ValueTask<T>`

And depending on the workload, there are [other Task-like types to consider](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/async-return-types).

**Comment by BillWagner** [comment]
Let's start with this statement (emphasis mine): 

> If you have an async keyworded function, then adding the Async suffix makes sense because the return type in the method has different handling, and because *the async keyword is not something that can be included in something like an interface definition*.

Consider [`IAsyncEnumerator`](https://docs.microsoft.com/dotnet/api/system.collections.generic.iasyncenumerator-1?view=net-5.0): 

```csharp
public interface IAsyncEnumerator<out T> : IAsyncDisposable
{
    T Current { get; }
    ValueTask<bool> MoveNextAsync();
    ValueTask  DisposeAsync();
}
```

Interfaces can and do contain methods that have the "Async" suffix.

To your point: 

> If you dont have the language support for TAP, because you did not use async or await, I dont see how you can have an awaitable or valid example of TAP without the async keyword.

This is true. But, the `async` and `await` keywords are for code that *calls* a method that returns a Task-like type. The sentence above the sample you want changed reads:  "The TAP counterpart of this method would expose the following single ReadAsync method."  *That's true!* And, it's why I've closed this. Any code that calls `MyTask.ReadAsync` can use the TAP, by adding the `async` modifier and `await` keywords in the body of that method.

I hope that helps.

**Comment by StingyJack** [comment]
Interfaces cant have the `async` keyword. The Async suffix in the interface definition tells the implementer that they should add the async keyword to the implementation. 

`async` and `await` are for the function that can be awaited, not the caller.  The caller isnt required to use them and can either wait on the task or "sync" it with `.GetAwaiter().GetRequest();`

**Comment by IEvangelist** [comment]
> Interfaces cant have the `async` keyword. The Async suffix in the interface definition tells the implementer that they should add the async keyword to the implementation.
> 
> `async` and `await` are for the function that can be awaited, not the caller. The caller isnt required to use them and can either wait on the task or "sync" it with `.GetAwaiter().GetRequest();`

Consider this example:

```csharp
public interface IAsyncDisposable
{
    ValueTask DisposeAsync();
}
```

An implementation may look like this:

```csharp
public class Example : IAsyncDisposable
{
    readonly Utf7JsonWriter _writer = new();

    public ValueTask DisposeAsync() => _writer.DisposeAsync();
}
```

The implementation doesn't need to use the `async` keyword, it is not always necessary, in fact when it's a single Task-like operation it can be omitted. The "Async" suffix has always been used to specify that a method returns a Task-like type.

**Comment by BillWagner** [comment]
The point of this is that the `async` modifier isn't part of the method signature. It's a modifier used by the compiler to create an "async" function. See [this example](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5lQDMmM6AwugN7Lq2bFQBs6AsgBQCUVNdvUA7JkYA6AGIAnAPYBbAEoBTAM4BXADYAXNuvHL5HfEl4BfHrSKYAHENaduhuiaRGgA) on sharplab.

The C# spec defines an [*awaitable* expression](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#awaitable-expressions) as follows:

> The task of an await expression is required to be ***awaitable***. An expression `t` is awaitable if one of the following holds:
>
> *  `t` is of compile time type `dynamic`
> *  `t` has an accessible instance or extension method called `GetAwaiter` with no parameters and no type parameters, and a return type `A` for which all of the following hold:
>    * `A` implements the interface `System.Runtime.CompilerServices.INotifyCompletion` (hereafter known as `INotifyCompletion` for brevity)
>    * `A` has an accessible, readable instance property `IsCompleted` of type `bool`
>    * `A` has an accessible instance method `GetResult` with no parameters and no type parameters.

Nowhere does the preceding mention the `async` modifier.

**Comment by StingyJack** [comment]
> The task of an await expression

An await expression requires the async keyword. It's a compiler error to do so without (and only a warning if using async without await).

**Comment by IEvangelist** [comment]
It is perfectly valid for the TAP example to be implemented in this way:

```csharp
public Task<int> ReadAsync(byte[] buffer, int offset, int count)
{
    return _reader.ReadAsync(buffer, offset, count);
}
```
or:
```csharp
public Task<int> ReadAsync(byte[] buffer, int offset, int count) =>
     _reader.ReadAsync(buffer, offset, count);
```

The `Task<int>` represents the async operation. It is awaitable, but it is also valid to use the `async` and `await` keywords.

```csharp
public async Task<int> ReadAsync(byte[] buffer, int offset, int count)
{
    var read = await  _reader.ReadAsync(buffer, offset, count);
   return read;
}
```

If you omit the keywords however, you actually save a bit of negligible micro-optimizations as some of the compiler async state machine bits are omitted as well...
