### ISSUE TITLE
Correction to description of `in` parameter modifier

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#22629]
The first paragraph states, "The in keyword causes arguments to be passed by reference. It makes the formal parameter an alias for the argument, which must be a variable."

Actually, it need not be a variable. For example, calls like the following are permitted for an `in` parameter of type `in int`:

M(123)
M(i + 1)
M(i * i)

Also, implicit conversion is permitted:

M(10U)   /* not an exact type match, so requires implicit conversion, which is done without error */

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @RexJaeschke 

I've added this to my TODO list for this sprint.

**Comment by RexJaeschke** [comment]
@BillWagner I'm rethinking my request. The text describes the `in` parameter and the explicit use of the `in` keyword, which is part of the method declaration and optionally in a call to that method. By the time the method gets called, what is being passed really *is* a variable reference, even if the argument specified in the call was an expression. **So, your text as written is correct!**

Presumably back at the method call site, when an expression like `123` or `i + 2` is seen, a temporary, unnamed variable of the appropriate type is created and initialized with the value of that expression, and that temporary variable is passed as an input argument. Now if the input parameter type is `long` and the expression passed is `int`, the temporary variable will have type `long` and the `int` value will be converted to `long` during the initialization.

Today, right now, I am working on the addition of input parameters to the Ecma C# spec (v7), and the one remaining task I have is to figure out **where and how** to describe this temporary variable creation and initialization. My current thinking is to do that somewhere in the method-invocation expression (or subordinate) section. That way, once a method with an input parameter gets called, it doesn't know (or care) if it was given an input argument directly, or whether it's receiving a compiler-generated input argument.

**Comment by BillWagner** [comment]
Thanks for the added context @RexJaeschke 

Closing with no action
