### ISSUE TITLE
.net spark cannot connect to sql server

### ISSUE THREAD

**Issue by bexstx** [dotnet/docs#22623]
my code

        static void Main(string[] args)
        {
            SparkSession spark = SparkSession
                .Builder()
                .AppName("Connect to SQL Server")
                .GetOrCreate();

                string connection_url1 = @"jdbc:sqlserver://127.0.0.1:1433;instanceName=WIN-TLDRK7EE98E\SQLEXPRESS;databaseName=Outsider;";
                //string connection_url2 = @"Server=WIN-TLDRK7EE98E\SQLEXPRESS;Database= Timeattend;Trusted_Connection=True";
                //string connection_url3 = "jdbc:sqlserver://127.0.0.1:1433;instanceName=SQLEXPRESS;databaseName=Outsider;";
                string dbtable = "IDCard";
                string user = "user";
                string password = "brownien_2020";

            DataFrame jdbcDF = spark.Read()
                    .Format("jdbc:")
                    .Option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
                    .Option("url", connection_url1)
                    .Option("dbtable", dbtable)
                    .Option("user", user)
                    .Option("password", password).Load();
                jdbcDF.Show();  // Displays the content of the SQL table as a DataFrame
        }
-------------------------------------------------------------------------

command line

spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-3-0_2.12-1.0.0.jar dotnet bin\Debug\netcoreapp3.1\SparkSQL.dll

------------------------------------------------------------------
error 

[2021-02-03T07:45:31.0891176Z] [WIN-TLDRK7EE98E] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'load' failed for class '7' when called with no arguments

[2021-02-03T07:45:31.0893505Z] [WIN-TLDRK7EE98E] [Error] [JvmBridge] java.lang.ClassNotFoundException: Failed to find data source: jdbc:. Please find packages at http://spark.apache.org/third-party-projects.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d129b502-f805-6f35-476d-06c8dfd9fda8
* Version Independent ID: 3cff26a5-7b9b-f917-e02a-413d59ffff40
* Content: [Connect .NET for Apache Spark to SQL Server](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/connect-to-sql-server)
* Content Source: [docs/spark/how-to-guides/connect-to-sql-server.md](https://github.com/dotnet/docs/blob/master/docs/spark/how-to-guides/connect-to-sql-server.md)
* Product: **dotnet-spark**
* GitHub Login: @Niharikadutta
* Microsoft Alias: **nidutta**

**Comment by adegeo** [comment]
Ping @Niharikadutta

**Comment by Niharikadutta** [comment]
@bexstx Apologies for the late response, I did not get notification for this. Were you able to resolve this? I see in your code:
```
DataFrame jdbcDF = spark.Read()
                .Format("jdbc:")
```
 can you remove the ':' at the end of jdbc and make it:
```
DataFrame jdbcDF = spark.Read()
                .Format("jdbc:")
```

**Comment by adegeo** [comment]
Closing due to lack of response.
