### ISSUE TITLE
Please update for coverlet.collector 3+ and NET5

### ISSUE THREAD

**Issue by shatl** [dotnet/docs#22638]
Please update instructions on how to use coverlet.collector v3+ and .NET 5.

using test project below with .NET 5 does not generate coverage in cobertura format

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Numbers\Numbers.csproj" />
  </ItemGroup>

</Project>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588a6d72-f70f-15f8-7505-5db491c8a8c6
* Version Independent ID: ab6ce421-f5e5-94f1-e707-32763b3a6a24
* Content: [Use code coverage for unit testing - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows)
* Content Source: [docs/core/testing/unit-testing-code-coverage.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-code-coverage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @shatl - thanks for posting this issue, and suggesting the upgrade. I'll make sure that happens soon, thanks again.
