### ISSUE TITLE
AnalysisLevel default to opt-in on pre NET 5 projects confusing

### ISSUE THREAD

**Issue by Bouke** [dotnet/docs#22635]
[EnableNETAnalyzers](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablenetanalyzers) specifies that to "enable .NET code analysis for projects that target earlier versions of .NET":

> Another way to enable .NET code analysis on projects that target .NET versions prior to .NET 5.0 is to set the AnalysisLevel property to latest.

Clicking on [AnalysisLevel](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysislevel) tells us that the default is:

> The default value is latest.

So what is it? Either the default is latest, and thus code analysis is enabled for projects targeting earlier versions of .NET _or_ the default is something else and thus code analysis is _not_ enabled for projects targeting earlier versions of .NET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#feedback)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I think that `AnalysisLevel` doesn't come into play at all unless you specifically add it to projects that target .NET Core 3.1 or earlier. But for .NET 5+ projects, the default is `latest`. @mavasani Can you confirm?

**Comment by DiskCrasher** [comment]
Furthermore, setting `AnalysisLevel` to "latest" doesn't appear to enable the analyzer in .NET Framework projects. I originally had this in my project file:

```
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
```

With only a few warnings being displayed. After I added:

`    <EnableNETAnalyzers>true</EnableNETAnalyzers>`

...there was a huge increase. The page needs to be updated to clarify.

**Comment by Youssef1313** [comment]
> Furthermore, setting `AnalysisLevel` to "latest" doesn't appear to enable the analyzer in .NET Framework projects. I originally had this in my project file:
> 
> ```
>     <AnalysisLevel>latest</AnalysisLevel>
>     <AnalysisMode>AllEnabledByDefault</AnalysisMode>
> ```
> 
> With only a few warnings being displayed. After I added:
> 
> ` <EnableNETAnalyzers>true</EnableNETAnalyzers>`
> 
> ...there was a huge increase. The page needs to be updated to clarify.

The doc page says:

> Another way to enable .NET code analysis on projects that target .NET versions prior to .NET 5.0 is to set the AnalysisLevel property to latest.

If that's not working, It *could* be a product bug, not a doc bug.

**Comment by Youssef1313** [comment]
> I think that `AnalysisLevel` doesn't come into play at all unless you specifically add it to projects that target .NET Core 3.1 or earlier. But for .NET 5+ projects, the default is `latest`. @mavasani Can you confirm?

That sounds correct.

https://github.com/dotnet/sdk/blob/2702c14c485d20f662800883ff7951235999beef/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L18-L22
