### ISSUE TITLE
SQL server sample dbs and code samples

### ISSUE THREAD

**Issue by roadkill42** [dotnet/docs#22644]
I am trying to get access to code examples and sample databases for Sql Server 2014. I cannot find what I am looking for. Any help or guidance will be appreciated. 
Thanks in advance,
RK42
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3caf351-18c6-5211-f2a2-bbdef5918629
* Version Independent ID: f13ef5fe-c17a-ecd1-2a2b-55b3b101da07
* Content: [.NET samples and tutorials](https://docs.microsoft.com/en-us/dotnet/samples-and-tutorials/)
* Content Source: [docs/samples-and-tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/samples-and-tutorials/index.md)
* Product: **dotnet**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@roadkill42 Here are some sample databases: https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks

**Comment by roadkill42** [comment]
Got them and thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
