### ISSUE TITLE
Add Undocumented API: System.ValueTask

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#2264]
# Add Undocumented API: System.ValueTask<TResult>

Comments are found in source at [System.Threading.Tasks.ValueTask.cs](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Threading.Tasks.Extensions/src/System/Threading/Tasks/ValueTask.cs). The XML doc file is [System.Threading.Tasks.ValueTask](https://github.com/dotnet/docs/blob/master/xml/System.Threading.Tasks/ValueTask%601.xml).

Notes:
- The Remarks section from source should be included in the Remarks section for the type.
- The Remarks section for the type should note that the use of the ValueTask<TResult> type is not supported by Visual Basic 2015, which does not support generalized async return types.

**Comment by BillWagner** [comment]
See the second bullet on the note above.  

I believe that the use of ValueTask won't work with the C# 6 compiler either (the version released with VS 2015).  

/cc @jaredpar to confirm.

**Comment by jaredpar** [comment]
@BillWagner is correct. 

Visual Basic (any version) does not support defining async methods using ValueTask.
