### ISSUE TITLE
This page is missing VB 16 and soon 16.9

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#22645]
[Enter feedback here]
It needs to track latest version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e781e2-125c-978e-6b24-72dfd6427218
* Version Independent ID: 0d6ac342-0d18-443f-bb4b-b6a2f02e93bb
* Content: [Select the Visual Basic language version - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/configure-language-version)
* Content Source: [docs/visual-basic/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/configure-language-version.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks @paul1956 

It looks like @Youssef1313 has already opened a PR to address this.
