### ISSUE TITLE
Consolidate "area" and "technology" labels

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#22653]
Now that we are using the org-wide bot, we have two sets of labels that have the same meaning:

- [:books: Area](https://github.com/dotnet/docs/labels?q=%3Abooks%3A) are duplicated by the [\*/prod](https://github.com/dotnet/docs/labels?q=prod) (There are a couple false positives in that search.
- [🗃️ technology](https://github.com/dotnet/docs/labels?q=%3Acard_file_box%3A+) and [:book: guide](https://github.com/dotnet/docs/labels?q=%3Abook%3A) are duplicated by the [\*/tech](https://github.com/dotnet/docs/labels?q=%3Abook%3A) labels. (many false positives in that search).

That duplication makes searching harder.

We should: 

- [x] Replace the ":books: - Area" labels with the corresponding "\*/prod" label.
- [x] Replace the ":card_file_box: - Technology" label with the corresponding "\*/tech" label.
- [x] Replace the ":book: - Guide" label with the corresponding "\*/tech" label.
- [x] Delete all ":books: - Area" labels.
- [x] Delete all ":card_file_box: - Technology" labels.
- [x] Delete all ":book: - Guide" labels.

**Comment by adegeo** [comment]
I'll port this to the desktop repo

**Comment by Youssef1313** [comment]
There was a contributing doc somewhere that explains labels used by the repository. That guide should also be updated after removing Area, Technology, and Guide label. I don't recall where is that doc page for now.

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

The label guide is [here](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/dotnet/labels-projects.md).

**Comment by BillWagner** [comment]
Pull request to update the contributor guide: MicrosoftDocs/Contribute#467

**Comment by BillWagner** [comment]
Contributor guide is updated. Closing as completed.
