### ISSUE TITLE
docker-compose.yml URL redirects to 404

### ISSUE THREAD

**Issue by ddncn** [dotnet/docs#22656]
Hello, in section SQL Server running as a container..., there's a link to docker-compose.yml file. It looks like the file got moved into a src directory, so now the link redirects to 404.

The link currently points to:
https://github.com/dotnet-architecture/eShopOnContainers/blob/main/docker-compose.yml

The new location is: 
https://github.com/dotnet-architecture/eShopOnContainers/blob/main/src/docker-compose.yml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50f6767-3560-f097-a3de-3d88ed02b5f5
* Version Independent ID: c986e70a-be0c-c375-ef5e-556fbd8629d6
* Content: [Use a database server running as a container](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/database-server-container)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/database-server-container.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/database-server-container.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @ddncn, Thank you for pointing it out. Good catch 👍 

Would you like to submit a PR on the [docs](https://github.com/dotnet/docs) repo ?
