### ISSUE TITLE
Vary SDK by condition

### ISSUE THREAD

**Issue by TysonMN** [dotnet/docs#22655]
I want to vary the SDK according to a condition.  When I build in Debug, I want to use `Microsoft.NET.Sdk.WindowsDesktop`.  When I build in Release, I want to use `Microsoft.NET.Sdk`.  However, I do not see any examples in the documentation that show how to do this.

Can such an example be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET project SDK overview](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
There is an example of part of this here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#project-files
You can specify the SDK by adding the `<sdk>` property:

```xml
<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  ...
</Project>
```

You'll have to dig into the MSBuild documentation, but I think you need use the Configuration setting with a condition. This way you can choose which SDK based on the condition: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2019

```xml
<Project>
  <Sdk Condition="'$(Configuration)'=='Debug'" Name="Microsoft.NET.Sdk" />
  ...
</Project>
```

**Comment by adegeo** [comment]
Also, please note that with .NET 5.0 as soon as you add `<UseWPF>` or `<UseWindowsForms>` you automatically get the Desktop SDK imported into your project, even if you just target `Microsoft.NET.Sdk`.

I believe this answers your question. Please feel free to reopen this if you need. Cheers!

**Comment by TysonMN** [comment]
> Also, please note that with .NET 5.0 as soon as you add `<UseWPF>` or `<UseWindowsForms>` you automatically get the Desktop SDK imported into your project, even if you just target `Microsoft.NET.Sdk`.

That is good to know.  That means a workaround is to always use `Sdk="Microsoft.NET.Sdk.WindowsDesktop"`.  When targeting `net5.0-window`, the logs output by the build include the line
```
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(376,5): warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.
```
but that line is not actually considered a build warning (even though it includes the "warning"), so I can keep using
```xml
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```

> You'll have to dig into the MSBuild documentation, but I think you need use the Configuration setting with a condition. This way you can choose which SDK based on the condition: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2019
> 
> ```
> <Project>
>   <Sdk Condition="'$(Configuration)'=='Debug'" Name="Microsoft.NET.Sdk" />
>   ...
> </Project>
> ```

That is not my understanding nor my experience.

First, the [`Sdk` element documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/sdk-element-msbuild) does not say that `Condition` is a possible attribute.  For contrast, consider the [`ItemGroup` element documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild), which does say that `Condition` is a possible attribute.

Second, my experience agrees with this documentation.  Given the following project file, I have the following build warnings.  You can try it for yourself by downloading [this ZIP](https://github.com/dotnet/docs/files/5948484/WpfApp1.zip).  In particular, the warnings are the same even after removing the `Condition` attributes on the two `Sdk` elements.  This is further evidence that the `Sdk` element does not support the `Condition` attribute.
```xml
<Project>

  <Sdk Name="Microsoft.NET.Sdk.WindowsDesktop" Condition="'$(Configuration)' == 'Debug'"/>
  <Sdk Name="Microsoft.NET.Sdk" Condition="'$(Configuration)' != 'Debug'"/>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
```

```
MSB4011	"C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk\Sdk.props (18,3)". This is most likely a build authoring error. This subsequent import will be ignored.
MSB4011	"C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk\Sdk.targets (14,3)". This is most likely a build authoring error. This subsequent import will be ignored.
```

**Comment by gewarren** [comment]
@dsplaisted Is it possible to reference a different SDK based on a condition?

**Comment by dsplaisted** [comment]
It's not possible to put a condition on an `Sdk` element.  However, you can achieve the same thing using `Import` elements with `Sdk` attributes:

```xml
<Project>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.WindowsDesktop" Condition="'$(Configuration)' == 'Debug'"/>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" Condition="'$(Configuration)' != 'Debug'"/>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.WindowsDesktop" Condition="'$(Configuration)' == 'Debug'"/>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" Condition="'$(Configuration)' != 'Debug'"/>

</Project>
```

Note that in this case you need separate import statements for `Sdk.props` and `Sdk.targets`.

**Comment by TysonMN** [comment]
Thanks @dsplaisted.  That works.  I had considered that approach, but never tried it.  Thanks for the clear example.

What are the chances that support for `Condition` can be added to `Sdk`?

If anyone is curious, I am conditionally selecting the SDK because I am conditionally selecting the target framework because the XAML designer works better when targeting .NET framework.  See [this issue](https://developercommunity.visualstudio.com/content/problem/1133390/design-time-data-in-datacontext-binding-not-displa.html).

**Comment by dsplaisted** [comment]
I doubt we will add `Condition` support to the `Sdk` element.

However, the issue where you need to use the WindowsDesktop SDK when targeting .NET Framework should be fixed in VS 16.9: https://github.com/dotnet/sdk/issues/15194

So you shouldn't need the conditions then.

**Comment by gewarren** [comment]
Thank you @dsplaisted!

I'm going to close the issue now, since I don't think it will be a common-enough scenario to warrant adding the example to the docs. Let me know if you think it should be added, though.

**Comment by TysonMN** [comment]
This is great. Thanks to both of you for being so helpful :)
