### ISSUE TITLE
No syntax highlighting for *with* keyword.

### ISSUE THREAD

**Issue by Issung** [dotnet/docs#22663]
**Issue description**
`with` keywords in the docs are not syntax highlighted like other keywords are, it should be highlitghted the same color as `if`, `switch`, `public`, `var`, etc, as it is in visual studio.

They keyword in docs:
![image](https://user-images.githubusercontent.com/22212465/106993092-10efb180-67ce-11eb-9b63-1019e52c9a9f.png)
Page: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/with-expression

The keyword in Visual Studio: 
![image](https://user-images.githubusercontent.com/22212465/106993121-21a02780-67ce-11eb-9d82-a96d28705852.png)

The request of this issue is that the syntax highlighting in the docs be made consistent with that of Visual Studio, for improved readability.

**Comment by BillWagner** [comment]
This issue was moved to MicrosoftDocs/feedback#3452

**Comment by IEvangelist** [comment]
Relies on https://github.com/DuncanmaMSFT/highlight.js/pull/34
