### ISSUE TITLE
For the mac, the :ro parameter on the volume for the certificate prevents this from working.

### ISSUE THREAD

**Issue by chaseoc** [dotnet/docs#22688]
For the mac, the :ro parameter on the volume for the certificate prevents this from working. I suggest removing this parameter for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129ac9c9-bab2-7ae0-75f8-cf3b7ad16a56
* Version Independent ID: 19debb34-1672-c5bc-395b-2ec523c25b8f
* Content: [Generate Self-Signed Certificates Overview - .NET](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide)
* Content Source: [docs/core/additional-tools/self-signed-certificates-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/self-signed-certificates-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @angee
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@plooploops Can you help with this issue?

**Comment by tdykstra** [comment]
@chaseoc Thanks for this feedback.  Where do you see `:ro` in the article?

**Comment by chaseoc** [comment]
@tdykstra Don't see it anymore so maybe it was removed or I was mistaken. Either way this should be resolved now.
