### ISSUE TITLE
How does this help me overload an operator?

### ISSUE THREAD

**Issue by francisco-chavez** [dotnet/docs#22697]
[Enter feedback here]

I'm looking to so some operator overloading, and there is nothing here that's of any help. Even the links were useless. When someone is looking to overload an operator they need two things. The list of which operators can be overloaded (that was provided). Examples on how to override the operators (those are missing).

edit by @billwagner to add blank line (formatting only)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91d85ae-8b37-e837-a031-144571362fbb
* Version Independent ID: 5ec5c397-c7c6-700c-bc36-a8dfb2396dad
* Content: [Operator overloading - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading)
* Content Source: [docs/csharp/language-reference/operators/operator-overloading.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/operator-overloading.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by alexschrod** [comment]
The big `Fraction` example with a bunch of operator overloading on the page didn't help? Combined with this pretty spot-on description of the mechanism above said example, I'm not sure what you feel is missing.

> Use the `operator` keyword to declare an operator. An operator declaration must satisfy the following rules:
> 
> - It includes both a `public` and a `static` modifier.
> - A unary operator has one input parameter. A binary operator has two input parameters. In each case, at least one parameter must have type `T` or `T?` where `T` is the type that contains the operator declaration.

**Comment by francisco-chavez** [comment]
That's not the page from which I submitted the issue. If you go up one level and click on Overview, that's the webpage that I submitted this from. It's also the webpage that kept showing up on my google searches. Also, the list of links that's under Operators and Expressions is so long, that the Operator Overloading link won't show up unless you scroll down the links panel on the left hand size of the screen. I should also mention, that the links panel has it's own scroll bar, so scrolling down the page will NOT scroll down the links panel, effectively hiding the link to Operator Overloading if you're more focused on the web page content than the Links panel.

There is a link in the web page content to the Operator Overloading page early on, but it's not very noticeable when it's inside a paragraph of text and there's this big table of the different operators that's going to grab the attention of anyone that give the page a quick look. On top of that, anyone that looking to overload a specific operator is going to click on that operator from the  operator list (well, table), which will take them to the web-page that gives them all the details on that operator. Out of the few operators that I checked, none of them had any mention of overloading the operator within their details page.

It was actually faster for me to just create a new C# project and make a few guesses to see which one worked, than it was for me to find the page with the examples for operator overloading.

**Comment by pkulikov** [comment]
> Out of the few operators that I checked, none of them had any mention of overloading the operator within their details page.

@francisco-chavez what operators have you checked? Typically, every operator page contains the **Operator overloading** section that should link *Operator overloading* article if that operator can be overloaded. I wonder which articles miss such a section or link.

**Comment by BillWagner** [comment]
Thanks for raising this @francisco-chavez 
Great discussion @alexschrod and @pkulikov 

Reading through the thread, I'll propose the following fixes:

- [ ] This page should link to the [Fraction example](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/operator-overloading), which does provide a complete example.
- [ ] This page should also recommend checking each operator page for the specific semantics and syntax rules that apply for overloading that operator. 

Those actions will provide links to the correct information for those who want to overload an operator. That's a better plan than adding specific information for each operator to this page, which will become too much content in one page to be useful.

**Comment by BillWagner** [comment]
Adding the "up for grabs" label, as the fix is well described.

**Comment by pkulikov** [comment]
@BillWagner what do you mean by "this page"? The page referenced by the issue already has the Fraction example.

**Comment by BillWagner** [comment]
Thanks @pkulikov I don't know how I lost that context.
Editing above comment.

**Comment by TheBlueSky** [comment]
I wanted to make this change but did not understand what part of the documentation should include what text.
Can someone give me the TL;DR? :)

**Comment by francisco-chavez** [comment]
There's a table of  Operators and Overloadability. A reasonable person might see a list of every operator listed out in the Operator Overloading page, and see that each of those operators is a link, and think, "Cool! I go straight to an example of how to overload the selected operator." 

I think the quick fix should be, un-link the operators in that table. Anyone that sees a link to the operator they are looking for inside a table of all the operators that's hosted on Operator Overloading page INSIDE the Overloadable Operations section is going to click on the link without reading the table's Overloadability section. A lot of those operators aren't overloadable, but some of the ones that can't be overloaded can be implemented/defined. The details on how to implement/define them tend to be on the Overloadability section. 

I honestly believe that removing the anchor tag from all of those 50+ operators should solve the problem. We don't need a 3 lines of text to tell us that an operator can't be overloaded. We need exactly 3 words: Yes, No, and Sort-of. We can have an additional paragraph afterwards with the details. Or, we can brake the table down into 3 tables based on how the Operator is overloaded, and place the sections on non-overloadable operators in areas with more appropriate headings than "Overloadable operators".

**Comment by pkulikov** [comment]
@francisco-chavez there are alternative ways to read the text. One can read the whole table and assume that links provide the background/context information about each operator, not specifically related to how to overload that operator. I guess both of us don't know how readers distributed between different ways of reading. So, we cannot make any changes on those guesses.

@TheBlueSky I think the biggest improvement would be to point to the `Fraction` example toward the top of the article after the table. Which table? This one: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading#overloadable-operators

**Comment by TheBlueSky** [comment]
I think @francisco-chavez has a point, but not sure the solution to remove the link.
On the other hand, adding a link after the table to the example might not make much difference if the assumption is correct that people might jump to the table assuming that it contains all the information they need.
What if we added "Overloadability" section to every operator page that contains the text in the table with a link to the `Fraction` example on this page?

**Comment by pkulikov** [comment]
@TheBlueSky 

> What if we added "Overloadability" section to every operator page that contains the text in the table with a link to the `Fraction` example on this page?

That's already the case. Every operator page contains the **Operator overloadability** section. Example:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators#operator-overloadability

Each such section contains the link to the following page:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading

That page explains how to overload an operator from very beginning.
