### ISSUE TITLE
Switched definition of  Abstraction and Encapsulation

### ISSUE THREAD

**Issue by Rashair** [dotnet/docs#22690]
I think that definition of **Abstraction** and **Encapsulation** is switched.
This
```
Abstraction  means hiding the unnecessary details from type consumers.
Encapsulation means that a group of related properties, methods, and other members are treated as a single unit or object.
```
should be this
```
Abstraction  means that a group of related properties, methods, and other members are treated as a single unit or object.
Encapsulation means hiding the unnecessary details from type consumers.
```
Similarly in the summary.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by stankevichea** [comment]
@Rashair is right

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @Rashair 

I've added to my plans for this month, while I'm working on other issues in this area.

See #22671 for related tasks.

**Comment by Rashair** [comment]
Summary was not fixed :/
