### ISSUE TITLE
Horrible error msg

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#22706]
That's a load of crap. All I want to do is compare two strings: int i = bindingListStockHeader.IndexOf(a => a.DisplayString == anItem.Text);

Nevermind. I'll untangle this rocket science eventually.

What a crappy technology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98316afd-4ee1-399d-aa1a-7897048ab5b4
* Version Independent ID: af4b9c9a-90f5-9097-033c-6ee367024091
* Content: [Compiler Error CS1660](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1660)
* Content Source: [docs/csharp/misc/cs1660.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs1660.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We'd like to help. This issue, as written, lacks enough information for us. Without more context of your code, we can't diagnose or fix the issue.
  
I suggest you edit the description of the bindingListStockHeader`, and include a bit more context on the relevant code.
  
You may also consider taking the opportunity to phrase your question differently for those of us that do want to help you succeed.
