### ISSUE TITLE
צריך לשפר את הממשק

### ISSUE THREAD

**Issue by rommilg** [dotnet/docs#22717]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @rprouse
* Microsoft Alias: **wiwagn**

**Comment by rommilg** [comment]
there is only two colors
red for fail
green for pass
you need one more
yellow for TODO

**Comment by rprouse** [comment]
@rommilg this is the .NET Docs repo, so not the correct place to file issues against NUnit or the .NET Test Adapter.

That said, general practice is to mark TODO tests with an ignore attribute with a reason it is being ignored. These will be reported differently.

```c#
[Test]
[Ignore("TODO: Complete work on this feature")]
public void TestFeature()
{
}
```

**Comment by BillWagner** [comment]
@rommilg @rprouse 

As mentioned above, this repo is responsible for .NET docs, not NUnit features. That said, I think your question has been answered.

Closing.
