### ISSUE TITLE
All links on the Migration Guidance page are broken: https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/migration-guidance

### ISSUE THREAD

**Issue by erwanh1112** [dotnet/docs#22718]
All links on this page are broken. They all point to https://docs.microsoft.com/en-us/previous-versions/appfabric/ff383417(v=azure.10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d3b2e5-1866-c0ca-a625-ebae749ab474
* Version Independent ID: 33c6691e-07cd-e76a-f9b7-08642d3a5724
* Content: [Migration Guidance](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/migration-guidance)
* Content Source: [docs/framework/windows-workflow-foundation/migration-guidance.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/migration-guidance.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wf**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@erwanh1112 Thanks for letting us know!
