### ISSUE TITLE
Solution could not found for 4.6.2 framework

### ISSUE THREAD

**Issue by thachi-thasnim** [dotnet/docs#22715]
[Enter feedback here]
Provided solution in the document is as below:

**Solution**
C#

Copy
using System;
using System.Net;

public class TestClass
{
    public void TestMethod()
    {
        // Let the operating system decide what TLS protocol version to use.
        // See https://docs.microsoft.com/dotnet/framework/network-programming/tls
    }
}

**Please suggest me a solution to avoid hardcoded SecurityProtocolType value in 4.6.2 .net framework.
As per my understanding SystemDefault required 4.7 or latest framework**

Currently using the below code and it is working properly.
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3
                                                                      |SecurityProtocolType.Tls
                                                                      |SecurityProtocolType.Tls11
                                                                      |SecurityProtocolType.Tls12;

Please guide me.

Thank you
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50eda890-9e85-8dd7-4fc9-23dabd999dc1
* Version Independent ID: b8e31c6e-231d-883b-24df-4517b782d17d
* Content: [CA5386: Avoid hardcoding SecurityProtocolType value (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5386)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca5386.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca5386.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dotpaul
* Microsoft Alias: **paulming**

**Comment by IEvangelist** [comment]
Hi 👋 @thachi-thasnim 
Thank you so much for posting this issue. We really appreciate it.

If you're on .NET 4.6.2, you'll have to suppress this warning. See [here](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5386#when-to-suppress-warnings) and [here](https://docs.microsoft.com/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2019#suppress-specific-warnings-for-visual-c-or-f). I'm going to close this for now, but if you still need help - we can reopen this issue.
