### ISSUE TITLE
Hmmm… can't reach this page

### ISSUE THREAD

**Issue by kumarmohe** [dotnet/docs#22722]
Hi,

The below link is not working. Getting "Hmmm… can't reach this page"

Comparison of JavaScript Frameworks
https://jsreport.io/the-ultimate-guide-to-javascript-frameworks/

Thanks,
Mohan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad8df5d-9295-d659-a561-ec9cabd5b61f
* Version Independent ID: 7ee71103-d997-140e-2d35-d9f2a3913e09
* Content: [Choose between traditional web apps and single page apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I found it archived in [WayBack Machine](https://web.archive.org/web/20200202122653/https://jsreport.io/the-ultimate-guide-to-javascript-frameworks/). Not sure whether the docs should use this link?

**Comment by IEvangelist** [comment]
Hi @kumarmohe - thanks for posting this issue. I think we could just replace the comparison link to another SPA reference.
