### ISSUE TITLE
# portfolio # Interactive tutorials

### ISSUE THREAD

**Issue by janavanhuynegem** [dotnet/docs#22724]
#portfolio definitieve versie

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f62e0f69-50c4-626a-0bd8-55e7a331278d
* Version Independent ID: 8cbbc2e0-cd46-a1dd-0371-33fe5576e2c9
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/nl-nl/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Translation: from Dutch to English: "final version"

@janavanhuynegem I'm not sure what your asking here. I'll need more information.

**Comment by janavanhuynegem** [comment]
I am wrong sorry

Op di 9 feb. 2021 16:02 schreef Bill Wagner <notifications@github.com>:

**Comment by BillWagner** [comment]
closing per originator comment.
