### ISSUE TITLE
System.Linq.Enumerable.FirstOrDefault and System.Linq.Enumerable.LastOrDefault not addressed

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#22728]
[Enter feedback here]
Need way to fix "OrDefault", the fixes shown are for the trivial case where fixing is easy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7efd80-b7c4-548f-0879-e7a057c6aa0c
* Version Independent ID: c0709596-3235-7bc6-20aa-4f99523347d2
* Content: [CA1826: Use property instead of Linq Enumerable method (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1826.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1826.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mavasani
* Microsoft Alias: **mavasani**

**Comment by marhja** [comment]
There is a [new option](https://github.com/dotnet/roslyn-analyzers/pull/4211) to turn off warnings for "OrDefault", but it would be nice if it were documented here.

**Comment by malopgrics** [comment]
https://github.com/dotnet/docs/issues/22728#issue-804099433

**Comment by Youssef1313** [comment]
@gewarren I think this can be closed as a duplicate of https://github.com/dotnet/docs/issues/29750 ?

**Comment by paul1956** [comment]
Agreed, I will close.
