### ISSUE TITLE
rhel 8 in Azure

### ISSUE THREAD

**Issue by freerider7777** [dotnet/docs#22721]
Error:

**sudo dnf install dotnet-sdk-5.0**

gives an error:

Last metadata expiration check: 2:44:52 ago on Mon 08 Feb 2021 10:06:03 AM UTC.
No match for argument: dotnet-sdk-5.0
Error: Unable to find a match: dotnet-sdk-5.0

 **yum list *dotnet***

gives an error:

Red Hat Enterprise Linux 8 for x86_64 - BaseOS - Extended Update Support from RHUI (RPMs)                                  0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'rhel-8-for-x86_64-baseos-eus-rhui-rpms':
  - Curl error (58): Problem with the local SSL certificate for https://rhui-2.microsoft.com/pulp/repos/content/eus/rhel8/rhui/8.2/x86_64/baseos/os/repodata/repomd.xml [could not load PEM client certificate, OpenSSL error error:0200100D:system library:fopen:Permission denied, (no key found, wrong pass phrase, or wrong file format?)]
  - Curl error (58): Problem with the local SSL certificate for https://rhui-1.microsoft.com/pulp/repos/content/eus/rhel8/rhui/8.2/x86_64/baseos/os/repodata/repomd.xml [could not load PEM client certificate, OpenSSL error error:0200100D:system library:fopen:Permission denied, (no key found, wrong pass phrase, or wrong file format?)]
  - Curl error (58): Problem with the local SSL certificate for https://rhui-3.microsoft.com/pulp/repos/content/eus/rhel8/rhui/8.2/x86_64/baseos/os/repodata/repomd.xml [could not load PEM client certificate, OpenSSL error error:0200100D:system library:fopen:Permission denied, (no key found, wrong pass phrase, or wrong file format?)]
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-baseos-eus-rhui-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577ce9b2-5b48-4ed2-c309-a78880015dd2
* Version Independent ID: 26300783-8df5-56a1-4ab6-4b8511e37f51
* Content: [Install .NET on CentOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos)
* Content Source: [docs/core/install/linux-centos.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-centos.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@freerider7777 I'm not sure what we can do for you here. It sounds more like you have some sort of problem with RHEL directly and/or the Azure machine. I would ask your question in a RHEL forum or Azure support ticket. I'm going to close this issue as I don't believe we can help. Sorry about that!
