### ISSUE TITLE
Identity server is no longer free - https://leastprivilege.com/2020/10/01/the-future-of-identityserver/

### ISSUE THREAD

**Issue by maulik-modi** [dotnet/docs#22720]
This new product will remain open source but will be offered with a dual license (RPL and commercial). The RPL (reciprocal public license) keeps Duende IdentityServer free if you are also doing free open source work. If you are using Duende IdentityServer in a commercial scenario, then a commercial license will be required. We offer a variety of ways to license Duende IdentityServer in an attempt to accommodate the different company sizes and usage models. Including an RPL license is important to us because it allows us to recognize and express our gratitude to the open source community and our contributors.

https://duendesoftware.com/products/identityserver#pricing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188e28ad-73ce-658d-1712-f7b5e3ce61cf
* Version Independent ID: 52119533-ce08-ae89-21d0-fe36a8e3748d
* Content: [IdentityServer for Cloud Native Apps](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/identity-server)
* Content Source: [docs/architecture/cloud-native/identity-server.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/identity-server.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @maulik-modi , thank you for reaching out. We already have an open issue on this topic. Here it is https://github.com/dotnet/docs/issues/20913 So closing this issue as duplicate.
