### ISSUE TITLE
Clarify the behavior of C# nameof expression with regard to fully qualified names

### ISSUE THREAD

**Issue by scharnyw** [dotnet/docs#22740]
Quote from the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof) on `C# nameof expression`:

> As the preceding example shows, in the case of a type and a namespace, the produced name is usually not fully qualified.

Is it possible to clarify what circumstances are considered "usual", and under what unusual circumstances will the output be fully qualified? Is the ambiguous language used here because the documentation writer is unsure of the exact behavior, or is the behavior not defined as part of the spec and subject to change in a later version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b82de3-3121-209c-6dc4-6267f726dcfe
* Version Independent ID: 7c19d7e6-f241-2f7e-9dad-737df8328663
* Content: [nameof expression - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof)
* Content Source: [docs/csharp/language-reference/operators/nameof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/nameof.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I personally never came across any scenario where `nameof` expression produces a fully qualified name.

**Comment by BillWagner** [comment]
Thanks for writing this @scharnyw 

And for the fix @Youssef1313 

The `nameof` expression won't ever return a fully qualified name.

**Comment by pkulikov** [comment]
@BillWagner @Youssef1313 as far as I understand, the `nameof` expression would return a fully qualified name for types and namespaces that are members of a global namespace. For example, `nameof(System)` is `System`, which is fully qualified.

That was discussed at the time of writing: https://github.com/dotnet/docs/pull/13364#discussion_r303050789

**Comment by BillWagner** [comment]
@pkulikov @Youssef1313 

> For example, `nameof(System)` is `System`, which is fully qualified.

Good point. I discussed this today, and the good news is (in that case) `System` is *also* a simple name.
Note that `nameof(System.Collections)` is `Collections`, which is the simple name.
