### ISSUE TITLE
Bash script error

### ISSUE THREAD

**Issue by jonilviv** [dotnet/docs#22766]
Hi,
Unfortunately bash script contains 2 errors. Both of them are same: wrong string format `{os-version}` and `{dotnet-package}`. There should be values `20.10` and `dotnet-sdk-5.0`. But now there are variables in Razor page, that should paste correct values.
Somebody forget to add `$` to variable? ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#apt-troubleshooting)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi 👋 @jonilviv
Thank you so much for posting this issue. We really appreciate it.

I'm not sure where you're seeing these errors, what script exactly? I'd welcome a pull request to fix the issue, if you're up for that? Please reference this issue when creating a pull request - to associate them. Thank you

**Comment by smholvoet** [comment]
<sup>Saw this issue was [up-for-grabs](https://github.com/dotnet/docs/labels/up-for-grabs) 🕵️</sup>

@jonilviv The `{...}` in the bash script are placeholders. You should replace them with the values that are applicable to your situation:

>There are two placeholders in the following set of commands.  
>  
>- **{dotnet-package}**: This represents the .NET package you're installing, such as aspnetcore-runtime-3.1. This is used in the following sudo apt-get >install command.  
>
>- **{os-version}**: This represents the distribution version you're on. This is used in the wget command below. The distribution version is the numerical value, such as 20.04 on Ubuntu or 10 on Debian.

Let's say you're using Ubuntu `20.04` and run into an issue with the `aspnetcore-runtime-3.1` package, the resulting bash script would be:

```bash
sudo apt-get install -y gpg
wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget https://packages.microsoft.com/config/ubuntu/20.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y aspnetcore-runtime-3.1
```

**Comment by jonilviv** [comment]
Yes, sorry - my mistake. There is no error. This issue should be closed.
