### ISSUE TITLE
.Net 5.0 Installation On Arch Linux

### ISSUE THREAD

**Issue by yuvarajvelmurugan** [dotnet/docs#22764]
I don't see installation support for arch linux like other linux distributions. Will arch linux distribution get any support soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux Distributions](https://docs.microsoft.com/en-us/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi 👋 @yuvarajvelmurugan 
Thank you so much for posting this issue. We really appreciate it.

Yes, .NET Core is supported on Arch Linux. While it is not explicitly called out in the docs, there are a few ways to install it.

All you need to do is enable snaps and install it through the snap store, our docs do call attention to manual [installs with Snaps](https://docs.microsoft.com/en-us/dotnet/core/install/linux#manual-installation).:
- https://snapcraft.io/install/dotnet-sdk/arch

Additional resources:
- https://wiki.archlinux.org/index.php/.NET_Core
