### ISSUE TITLE
Inconsistency between ActivitySource example and OpenTelemetry example

### ISSUE THREAD

**Issue by meastp** [dotnet/docs#22765]
Hi,

I'm trying to figure out how to store the (single) ActivitySource in my application, and I'm a bit confused by the inconsistency between the ActivitySource example and "best practices":

```csharp
internal static ActivitySource source = new ActivitySource("MyCompany.MyComponent.SourceName", "v1");
```
and best practices: 
> Create the ActivitySource once and store it in a static variable and use that instance as long as needed.

and the OpenTelemetry example:

```csharp
public class Program
{
    private static readonly ActivitySource MyActivitySource = new ActivitySource(
        "MyCompany.MyProduct.MyLibrary");

    public static void Main()
}
```

Why the difference in access modifiers (`internal static` vs `private static readonly`)?

If this is because the example only uses ActivitySource in the Main-function which is a purely artificial example, consider the example as the starting point for most beginners to ActivitySource/OpenTelemetry and change it to be consistent. Perhaps defining it to be `internal static` immediately would be best? (I'm not primarily a C# developer, som I actually don't know)

(I will submit this issue to opentelemetry-dotnet as well, depending on the outcome)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05233ce0-ba2f-6b67-c321-ce630c650968
* Version Independent ID: 18c7fa3f-5b50-1b53-68ba-4dbd9fd89396
* Content: [Distributed tracing - .NET](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)
* Content Source: [docs/core/diagnostics/distributed-tracing.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/distributed-tracing.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by sywhang** [comment]
@meastp Thanks for the feedback! The access modifiers don't make much difference in terms of any feature related to OpenTelemetry or ActivitySource. The difference would only occur if `source` / `MyActivitySource` is somehow referenced from a different class outside the class they're defined in. In that case you'd want to change your access modifier to be `internal` instead. 

I will change these snippets to be consistent, as the inconsistency can indeed be confusing. Thanks again for submitting this :)

**Comment by meastp** [comment]
@sywhang Thank you. I would add a note on when to use private vs internal, though, because developers with other primary languages than C# don't neccessarily know about the `internal` modifier.

Don't you agree that (other than toy examples), the modifier _should_ be `internal` instead of `private`? So I'd fix it by using internal consistently instead.
