### ISSUE TITLE
== Implementation in value objects

### ISSUE THREAD

**Issue by stap123** [dotnet/docs#22767]
I was hoping for some clarification about the example value object. What are the `EqualOperator` and `NotEqualOperator` used for in this example?

Would you override the == operator in each individual value object implementation or is there something missing from the snippet on this page?

There's a related discussion on SO [here](https://stackoverflow.com/questions/49195767/how-do-the-equaloperator-and-notequaloperator-methods-work-in-this-valu) if it's useful but an official clarification (and maybe update to the page) would be great?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by IEvangelist** [comment]
Hey, @nishanil do you have any thoughts on this issue?
