### ISSUE TITLE
"Associated of" to "Associated with"

### ISSUE THREAD

**Issue by DawMuld** [dotnet/docs#22806]
Members
The members of a class are either static members or instance members. Static members belong to classes, and instance members belong to objects (instances of classes).

The following list provides an overview of the kinds of members a class can contain.

Constants: **Constant values associated with the class**
Fields: **Variables that are associated of the class**
Methods: Actions that can be performed by the class
Properties: Actions associated with reading and writing named properties of the class

The definition of constants and the definition of fields are a bit confusing at first. Using "associated with" and "associated of" respectively can indicate a difference between those two members based on the prepositions used with 'to associate'. 
However, I could not find anything on the internet that explains the meaning of 'to associate of' so i guess this is a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs'](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#feedback)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Related to #22805 

This should be "associated with", not "associated of". Further, the distinction between instance and static fields should be mentioned.

**Comment by BenjaminMichaelis** [comment]
This was fixed by #23593 and can be closed
