### ISSUE TITLE
Difference between 'derived from class' and 'derived from type'

### ISSUE THREAD

**Issue by DawMuld** [dotnet/docs#22807]
Accessibility
Each member of a class has an associated accessibility, which controls the regions of program text that can access the member. There are six possible forms of accessibility. The access modifiers are summarized below.

public: Access isn't limited.
private: Access is limited to this class.
protected: Access is limited to this class or **classes derived from this class**.
internal: Access is limited to the current assembly (.exe or .dll).
protected internal: Access is limited to this class, **classes derived from this class**, or classes within the same assembly.
private protected: Access is limited to this class or **classes derived from this type** within the same assembly.

Can anyone confirm if ''derived from this type" should be interpreted as derived directly from this class, indicating that a class derived from a class derived from this class won't have access? 
I can't really figure out what the difference between 'derived from this class' and 'derived from this type' should define in this context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs'](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#feedback)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
A type in C# can be one of the following:

- Class
- Record (which is actually a class underneath the hood)
- Struct
- Anonymous type, etc.

The only types that can involve inheritance are classes and records. So in this specific context, both class and type mean the same thing.

**Comment by BillWagner** [comment]
Thanks for writing this one as well @DawMuld 

> Can anyone confirm if ''derived from this type" should be interpreted as derived directly from this class, indicating that a class derived from a class derived from this class won't have access?

"derived from this type" would mean any derived type, including a class derived from a class derived from this class. 

I think it would be best to keep using "type" instead of "class", because of records. This article does state that structs are sealed, so I think it's still clear.

**Comment by BillWagner** [comment]
Thanks for the note @SeanKilleen 

I did a review, and I agree.  Closing as resolved.
