### ISSUE TITLE
Cannot create environment variable for logging category with periods

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/docs#22817]
The [logging configuration](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging#configure-logging) often uses namespaces (or namespace like strings, separated by periods) as category keys.

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
````

The logging and [configuration docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#set-log-level-by-command-line-environment-variables-and-other-configuration) agree on creating environment variables for deep configuration structures.

```
Logging__LogLevel__Microsoft=Information
```

But, you can't use a period in a variable or environment variable name in any shell that I know of. It's not disallowed by the spec, apparently, but the various shells seem to avoid period in their implementations.

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02
https://tldp.org/LDP/abs/html/gotchas.html

```
# Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
bash: Logging__LogLevel__Microsoft.Hosting.Lifetime=Information: command not found
```

So, how do we do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346bbcf3-9f8e-b253-09fe-906195392783
* Version Independent ID: 0e787ac2-1108-1d94-d62f-ccffa93e06c3
* Content: [Logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging)
* Content Source: [docs/core/extensions/logging.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by adegeo** [comment]
@IEvangelist  @Rick-Anderson do you have an idea as to the answer? What does the environment variable system use to replace `.` when the setting contains a `.`?

**Comment by Rick-Anderson** [comment]
@serpent5 can probably figure it out.

**Comment by serpent5** [comment]
The environment variable provider doesn't give special treatment to a `.`: It only substitutes `__` for `:`. @Rick-Anderson and I looked into this before, but couldn't find a way to make this particular setup work. I can't see that anything has changed here, either.

**Comment by IEvangelist** [comment]
While this is a good question and fair observation to call attention to it, I do not believe it is a problem. Logging is the only example that I'm aware that has namespaces or various patterns like this within their configuration settings. And since it is logging, there is no real value in keeping it a secret, or securing it away in an environment variable - you know? I'd argue that is should remain in an _appsettings.json_ file.

**Comment by AnthonyMastrean** [comment]
@IEvangelist fair points... but, we're not supposed to use environment variables for secrets (and that's not the only reason they're used, see DOTNET_ENVIRONMENT and others) and we don't always have an easy way to override or provide an appsettings file (thinking some CI/CD scenarios where your "services" like linked containers syntax is limited).

**Comment by IEvangelist** [comment]
I was able to set an environment variable locally in my bash environment with this name (based on [this SO](https://unix.stackexchange.com/a/93533)), it just needed quotes around it:

```bash
env "Logging__LogLevel__Microsoft.Hosting.Lifetime=Information"
```

I confirmed that I see it in the env vars too.

**Comment by AnthonyMastrean** [comment]
Good find, thanks!

**Comment by Rick-Anderson** [comment]
Can you set it to 
```bash
env "Logging__LogLevel__Microsoft.Hosting.Lifetime=Error"
```
and verify it's working?

**Comment by IEvangelist** [comment]
> Can you set it to
> 
> ```shell
> env "Logging__LogLevel__Microsoft.Hosting.Lifetime=Error"
> ```
> 
> and verify it's working?
> Nice work @IEvangelist

I've been testing it a lot this morning, I'm updating the article to also include cross-plat env var setting with notes/link to the SE bits I stumbled upon. See proposed [changes here](https://github.com/dotnet/docs/pull/22915/files#diff-aef422955162b41a1c305e36c7f6e856fab15c0c6995cea89e14b7d7594ae757).

**Comment by johnwc** [comment]
I think this needs to be evaluated again, specifically for apps running in containers. We are not able to set an environment variable that contains a period for a container. So, we are not able to configure logging upon deployment. In our case we only want to turn on Informational logging for a specific library, so not to flood the logs.

**Comment by AlexandreBossard** [comment]
I've ran into exactly that this morning. We have a local development setup that overrides the appsettings through environment. It works with every variables but the log levels, which is quite ridiculous. While working with containers, you want to test your environment variables does not contain typos.
Would it be possible to translate the log levels '.' in '__' just like the ':' ?

**Comment by Storm-BE** [comment]
This might only be tangentially related, but I'm having problems as well overriding logging configuration for certain namespaces through 'Application settings' (=environment variables) on Azure App Service.

In Kudu, the App Service SCM, I can see periods in the variable names get replaced with single underscores, which causes these override rules to not match anything and be ignored completely.

**Comment by johnwc** [comment]
@IEvangelist your workaround you mentioned in your [comment](https://github.com/dotnet/docs/issues/22817#issuecomment-782110305) does not work for container deployments. This needs a code fix internally, so that periods are treated the same way as colons. Can this get looked at again?

**Comment by IEvangelist** [comment]
Hi @johnwc, I did a bit of digging. I'm curious does this help you?

- [[Question] Allowed characters in Linux environment variable names: Accepted SO answer](https://stackoverflow.com/a/2821183/2410379)
- [[Question] Allowed characters in Linux environment variable names: Explanation and example of setting env var in UNIX](https://stackoverflow.com/a/58734692/2410379)

Also, What exactly have you tried in terms of setting env var? Did you define them in the `ENV` of a _Dockerfile_, or what?

**Comment by johnwc** [comment]
K8 does not define environment variables in dockerfile. It generates the docker file based on automation, and it has no way of quoting values when creating the env variable. This issue needs to be handled on the .Net side of things, exactly how they currently handle the issue of colons in the name.

**Comment by mwhitney86** [comment]
I'm running into this same issue for container deployements. Any movement?

**Comment by LordMike** [comment]
See also https://github.com/dotnet/AspNetCore.Docs/issues/17378 - `systemd` also does not allow dots in env names.

**Comment by johnwc** [comment]
@IEvangelist this issue is not resolved, I reviewed your doc update and it did not cover anything about what everyone is stating does not work. And that is, using periods in environment variable names. Surrounding the entire `my.var.name=value` with quotes as you describe as a workaround only works in shell environments, and not with things like Kubernetes deployments.

@Rick-Anderson @IEvangelist can you please reopen this issue?

**Comment by IEvangelist** [comment]
Hi @johnwc, Thanks for the follow-up. If that is the case, I'm not sure if this is a docs issue, it might need to get transferred to the product team if you believe that they'll need to change how env vars are parsed. Let's ask @maryamariyan, she might know.

**Comment by pbstrein** [comment]
We are running into a similar issue. We are running into a kubernetes environment and there is no way to configure the LogLevel for anything within a subsystem (e.g. this does not work `Logging__LogLevel__System.Net.Http.HttpClient=Warning`.  Trying to change this value with `appsettings.json` requires a change that goes through the entire CICD pipeline, rather than a configuration change that can be done at runtime as needed for production debugging (i.e. temporarily changing the LogLevel of a service to get more information).

**Comment by rbgarcia** [comment]
We are also running into this issue.
Our existing deployment strategy relies on environment variables to change the logging levels which means relying `appsettings.json` would bring a lot more complexity into our solution. It really feels like environment variables should have a different strategy for parsing `.` so that we can safely setup logging levels for different categories.

**Comment by johnwc** [comment]
@IEvangelist it's been a few months now with no response from @maryamariyan or product team. How can we get better attention for this issue?
