### ISSUE TITLE
Multi-threading, async and .NET task framework implications need to be explained

### ISSUE THREAD

**Issue by daviburg** [dotnet/docs#22814]
It is easy to do this incorrectly in .NET with async, multi-threading and task framework use becoming almost universal, while the underlying single-threaded API have been around for 15+ years. These implication ought to be covered here in detail to avoid application security bugs.

- Don't use impersonation context with async code, use run impersonated instead
- Don't use impersonation context with background task code, ... run the task via run impersonated or pass impersonation token around?
- Creating a new thread or process while impersonated, the new process inherit the process user identity, which isn't changed, and I don't even know what a new thread will inherit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 942d6a98-e075-3a53-9394-ec2bd2ff0a8a
* Version Independent ID: 8e9da1ab-bb26-3211-185a-3667667d29d2
* Content: [Impersonating and Reverting](https://docs.microsoft.com/en-us/dotnet/standard/security/impersonating-and-reverting)
* Content Source: [docs/standard/security/impersonating-and-reverting.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/impersonating-and-reverting.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @daviburg
Thank you so much for posting this issue. We really appreciate it.

It sounds like you have experience in this area, and have details surrounding the additions you're recommending. Is this something you'd feel comfortable creating a pull request for, and we'd review it?

**Comment by daviburg** [comment]
I recently got the experience that one can do it wrong and cause a security issue. I am not however an authority on the subject who could say what's what. Someone from the .NET team should provide the expertize on how to do impersonation safely for TAP / async-await, TPL / task-based asynchronous programming, thread-pool and other multi-threading .NET patterns. I could actually learn from them to make sure we're fixing our usage correctly.
