### ISSUE TITLE
good

### ISSUE THREAD

**Issue by ishujain** [dotnet/docs#22829]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356f32d2-2574-9d48-a096-aef9fc21112d
* Version Independent ID: 49ae4e9d-cd57-917c-8795-71ad57858d5d
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/interpolated-strings)
* Content Source: [docs/csharp/tutorials/exploration/interpolated-strings.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the compliments @ishujain 
Closing as kudos.
