### ISSUE TITLE
Broken link: Comparison of JavaScript Frameworks

### ISSUE THREAD

**Issue by savbace** [dotnet/docs#22824]
The following link seems to be no longer valid:
* **Comparison of JavaScript Frameworks**
https://jsreport.io/the-ultimate-guide-to-javascript-frameworks/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad8df5d-9295-d659-a561-ec9cabd5b61f
* Version Independent ID: 7ee71103-d997-140e-2d35-d9f2a3913e09
* Content: [Choose between traditional web apps and single page apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This link has recently been removed from this page.

**Comment by savbace** [comment]
Duplicates #22722
