### ISSUE TITLE
Fields should not be named camelCase because it overlaps with local variable names

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dotnet/docs#22822]
Solution: To either prefix with a _fieldName or _PropertyName so that it matches the property name.

If you name a field in camel case, you have to fill in 3 details:
```
private int myVar;
public int MyProperty
{
get { return **myVar**; }
set { myVar = value; }
}
```
With the following convention, only two are required"
```
private int _MyProperty;
public int MyProperty
{
get { return _MyProperty; }
set { _MyProperty = value; }
}
 ```
Furthermore, if you end up having to change the name, you can do a simple search and replace and replace everywhere rather than having to be case sensitive and search twice. Also without at the minimum a underscore in front, a field could match the local variable (inside a method) with the same name.

Referring @MarkMichaelis to this as well as this is reflected in his naming conventions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df47593-8586-e54e-fb74-cf3a96262d40
* Version Independent ID: b464cd68-4713-c848-e9a7-30705d17e6f7
* Content: [Fields - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/fields.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/fields.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sharwell** [comment]
**camelCase** is the default naming convention in Visual Studio for both local variables and fields. `_camelCase` (with a leading underscore) is a commonly used alternative naming convention. No form of PascalCase would be considered a standard naming convention in .NET.

**Comment by BillWagner** [comment]
Thanks for starting this work @BenjaminMichaelis 

As others have noted, these changes don't conform to our coding guidelines.  In our docs, we intend to follow the [coding standards adopted by the .NET runtime team](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md). It's true that some of our older samples don't conform today, including this one. If you update this PR to match those guidelines, we'll review it again.
