### ISSUE TITLE
F# code formatting guidelines: Clarify indentation of arguments of piped functions

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#22834]
The F# code formatting guidelines, section [Formatting function parameter application](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application), contains the following example:

```f#
list1
|> List.iter
    (fun elem ->
        printfn $"%d{a + elem}")
```

Above, the parameter (the `(` to be specific) is indented 4 spaces relative to the start of the `|>` operator:

![image](https://user-images.githubusercontent.com/7766733/107873045-9b5fa180-6eaf-11eb-901b-038287b8064c.png)

However, consider how this looks for 2 spaces of indentation:

```f#
list1
|> List.iter
  (fun elem ->
    printfn $"%d{a + elem}")
```

IMHO this doesn't look great; the argument to `List.iter` looks deindented relative to `List.iter`.

Compare this with the style guide example given just above this one, with no pipeline:

```f#
List.iter
    (fun elem ->
        printfn $"%d{a + elem}")
    list1
```

This, of course, looks good with 2 spaces of indentation:

```f#
List.iter
  (fun elem ->
    printfn $"%d{a + elem}")
  list1
```

I propose that we specify how parameters to pipelined functions are indented, in a way that ensures it looks good also on 2 spaces (and possibly others, though the style guide only recommends 4 or 2 spaces, so think that should be the focus).

For example:

> For function application in a pipeline, the arguments should be indented relative to the function:
> ```f#
> // With 4 spaces indentation
> list1
> |> List.iter
>        someLongParam
>        anotherLongParam
>
> // With 2 spaces indentation
> list1
> |> List.iter
>      someLongParam
>      anotherLongParam
> ```

Or alternatively, closer to today's format in the 4-space case:

> For function application in a pipeline, the arguments should be indented 2 spaces relative to the function:
> ```f#
> list1
> |> List.iter
>      someLongParam
>      anotherLongParam
> ```

Or alternatively, preserving today's formatting in the 4-space case:

> For function application in a pipeline, the arguments should be indented relative to the pipe symbol, but always at least 1 space from the function:
> ```f#
> // With both 4 and 2 spaces indentation
> list1
> |> List.iter
>     someLongParam
>     anotherLongParam
> ```

I'm open to other suggestions. I can also create a PR once it's decided.

**Comment by cartermp** [comment]
I think I like your first suggestion the most. Indending relative to the function makes the most sense to be logically, since the first parameter to that function is the block that you're indenting. I'll accept a PR with the guidance in your first example.
