### ISSUE TITLE
EditorConfigFiles vs GlobalAnalyzerConfigFiles 

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22836]
In https://github.com/dotnet/roslyn-analyzers/pull/3538/files#diff-c60b9590bdd1233ac95b74385a74024dbdfa9cde59acc6ec97f222b2c1dcd3d4R336, there is a change from `GlobalAnalyzerConfigFiles` to `EditorConfigFiles`.

Was the option renamed at some point? Which option is supported in which version? Or both will work?

cc: @mavasani

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddb7b648-6f01-eaeb-1292-4baee5ae0666
* Version Independent ID: cb44b30a-3fcc-3384-3fcd-1ac2675bf470
* Content: [Configuration files for code analysis rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files)
* Content Source: [docs/fundamentals/code-analysis/configuration-files.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/configuration-files.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
@Youssef1313 Both property names should work. Please see https://github.com/dotnet/roslyn/blob/8637000fc35f01a453349147b71d5ecdae8d0bff/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L80-L90. We can consider updating roslyn-analyzers post build tool to use `GlobalAnalyzerConfigFiles` for clarity.

**Comment by Youssef1313** [comment]
@mavasani Thanks for clarification. Should both be documented?

**Comment by mavasani** [comment]
`GlobalAnalyzerConfigFiles` is the only one that should be used by end users. Editor config files are implicitly discovered by compiler/project system, so `EditorConfigFiles` is primarily an implementation detail.

**Comment by Youssef1313** [comment]
Thanks. I was confused by <https://github.com/dotnet/aspnetcore-tooling/pull/3087/files#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dcR42>.

Since the documentation is correct, I'll close.

Thanks again.
