### ISSUE TITLE
Select scenario screenshot is outdated

### ISSUE THREAD

**Issue by Alexei000** [dotnet/docs#22832]
The "Select a scenario" screenshot is outdated since now there are other available scenarios:

- Text classification
- Value prediction
- Image classification
- Recommendation
- Object detection

However, the article speaks about "Issue Classification".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7fff31d-9b11-e1f1-f4c1-d798a7d9b564
* Version Independent ID: 8c94de21-2cc2-fb08-314d-6a62af1f0421
* Content: [Tutorial: Classify health violations with Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/health-violation-classification-model-builder)
* Content Source: [docs/machine-learning/tutorials/health-violation-classification-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/health-violation-classification-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @Alexei000 

Thanks for pointing this out. We'll add this to our backlog.
