### ISSUE TITLE
Problem in the Code

### ISSUE THREAD

**Issue by dolev146** [dotnet/docs#22846]
[Whats up i tried making the code work in my pc and the file path when i run this line  
   dynamic rFile = new ReadOnlyFile(@"..\..\TextFile1.txt");
from the example make a problem when i go over the walkthrough
but when i changed it to have one more "..\ " it worked fine

    dynamic rFile = new ReadOnlyFile(@"..\..\..\TextFile1.txt");

 ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63fb701-91e9-5723-add6-33d2288431a3
* Version Independent ID: e9d33444-b5f7-96d4-9c33-dd29913349d5
* Content: [Walkthrough: Creating and Using Dynamic Objects (C# and Visual Basic)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects)
* Content Source: [docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @dolev146 

This needs to be updated to match where build outputs are written using the latest .NET SDK.
