### ISSUE TITLE
How do I change properties that must be set prior to starting and activity?

### ISSUE THREAD

**Issue by srulandhs** [dotnet/docs#22854]
This page recommends using `ActivitySource.StartActivity`. However, how do I go about changing properties such as IdFormat? These much be done before the activity is started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05233ce0-ba2f-6b67-c321-ce630c650968
* Version Independent ID: 18c7fa3f-5b50-1b53-68ba-4dbd9fd89396
* Content: [Distributed tracing - .NET](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)
* Content Source: [docs/core/diagnostics/distributed-tracing.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/distributed-tracing.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by noahfalk** [comment]
Does [this issue](https://github.com/dotnet/runtime/issues/43853) capture what you were looking for? The short answer is this was a missing capability for the StartActivity() API that we added in .NET 5 and we hope it has been fixed as part of our .NET 6 work.
