### ISSUE TITLE
Microsoft.DotNet.Analyzers.Compatibility is deprecated

### ISSUE THREAD

**Issue by PatricioVidal** [dotnet/docs#22856]
The NuGet package Microsoft.DotNet.Analyzers.Compatibility is deprecated as indicated [here]( https://github.com/dotnet/platform-compat#platform-compatibility-analyzer). It is confusing that there are instructions to add this deprecated package to your project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf0043f-baf5-d2ab-84a5-718f900c0e25
* Version Independent ID: c3fabde5-775f-63f9-6b22-425435e096d8
* Content: [.NET API analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer)
* Content Source: [docs/standard/analyzers/api-analyzer.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/api-analyzer.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-analyzers**
* GitHub Login: @OliaG
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
I'm curious, @OliaG are you familiar with this - should we update this?

**Comment by Youssef1313** [comment]
@IEvangelist Feels more appropriate to retire the article and redirect to the appropriate doc. That may be <https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer>?

**Comment by IEvangelist** [comment]
The plan, [delete this](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer) and redirect [to this](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer).
