### ISSUE TITLE
The page should use """ for the multiline strings

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#22866]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d124987-d837-b655-261e-e0871effcb7d
* Version Independent ID: 492a3233-0049-0678-1a4e-aed850e14bf4
* Content: [Grouping Constructs in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions)
* Content Source: [docs/standard/base-types/grouping-constructs-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/grouping-constructs-in-regular-expressions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @daveyostcom Can you be more specific? AFAIK the `"""` construct is a python thing?

**Comment by daveyostcom** [comment]
@adegeo Oh, right. Wishful thinking. (Java and Swift have """  multiline strings.) Still, the meat of what I was getting at was to show `IgnorePatternWhitespace` mode, which is so nice for readability.
```
    string pattern = @"
                      ^
                        [^<>]*
                        (
                          ( (?'Open'       < ) [^<>]* )+
                          ( (?'Close-Open' > ) [^<>]* )+
                        )*
                            (?(Open) (?!) )
                      $
                      ";
    string input = "<abc><mno<xyz>>";

    Match m = Regex.Match(input, pattern, RegexOptions.IgnorePatternWhitespace);
```

**Comment by adegeo** [comment]
I understand, thank you for the suggestion :) I think it would really bloat the page (which is already gigantic) if we were to do that. Also, you can't really copy/paste the string to a regex test app. It's my experience that the testing apps generally just let you put in a single line to test against some text. I don't think there is a big enough benefit to retro fit these pages with your suggestion.

Thanks though!

**Comment by daveyostcom** [comment]
Nevertheless the page should show `IgnorePatternWhitespace` mode.

My experience with regex testers is that they do take such expressions. IMO we all need to give ourselves a break and stop struggling with single line no space mode for complex expressions. We have more important things to do. So encouraging `IgnorePatternWhitespace` mode on the page would be a worthy public service.  😊

**Comment by adegeo** [comment]
Good point. In general, the regex pages do need quite a bit of clean up. I'll create a new issue where we can collectively gather feedback that should be applied to the whole area. This way we can capture this and if it becomes a priority, we can work on it, otherwise others can contribute as they have time.
