### ISSUE TITLE
Do not translate short names in dotnet new

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/docs#22872]
In the template argument table, the "short name" column should not be translated. I don't want to type `dotnet new réagir` on my french computer 😉 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by jeremyVignelles** [comment]
Same applies here to the section name : https://docs.microsoft.com/fr-fr/dotnet/core/tools/dotnet-new#angular-react

**Comment by Youssef1313** [comment]
@jeremyVignelles Yeah I agree this shouldn't be localized. Going to open a PR to fix this now.

**Comment by Youssef1313** [comment]
Opened https://github.com/dotnet/docs/pull/22874 to fix this.

**Comment by Youssef1313** [comment]
There is another issue in the localized version, the horizontal lines appears as `**`. @JasonCard Do you know where this should be fixed?

**Comment by JasonCard** [comment]
@Youssef1313 Thank you for letting me know about the ** issue. I've escalated this for further investigation.
