### ISSUE TITLE
Add C# 9 to "The history of C#" article

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#22885]
Add C# 9 to "The history of C#" article:

https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-version-history

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Should also have `ms.custom: updateeachrelease` metadata.
