### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#22887]
Would open a PR but don't know what was meant to say there

"The and will each run in a Docker container."

/cc @nishanil @IEvangelist 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/master/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by IEvangelist** [comment]
I believe it means to say "They will each run in a Docker container." @nishanil does that sound accurate?

**Comment by amolenk** [comment]
Added PR #22894 to fix this.
