### ISSUE TITLE
get error

### ISSUE THREAD

**Issue by freemanke** [dotnet/docs#22897]
[Enter feedback here]

I follow document and use dapr run the console app, get error like bellow:
== APP == Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.

== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

== APP ==    --- End of inner exception stack trace ---

== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

== APP ==    at ConsoleApp1.Program.Main(String[] args) in C:\Users\freeman\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 16

== APP ==    at ConsoleApp1.Program.<Main>(String[] args)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/master/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Just tried is on a clean 1.0 install and I'm not getting the error.

Can you share the output of `dapr -v` as well as the complete output when running the `dapr run --app-id DaprCounter dotnet run` command?

**Comment by freemanke** [comment]
Bellow is output in my laptop + visual studio 2019 (16.8.5)
----------------------------------------------------------------------------------------

freeman@KEXPRO MINGW64 ~/Projects/learning-dapr/src/DaprCounter
$ dotnet --version
5.0.200-preview.21079.7

freeman@KEXPRO MINGW64 ~/Projects/learning-dapr/src/DaprCounter
$ dapr --version
CLI version: 1.0.0
Runtime version: 1.0.0

freeman@KEXPRO MINGW64 ~/Projects/learning-dapr/src/DaprCounter
$ dapr run --app-id counter dotnet run
Starting Dapr with id counter. HTTP Port: 57509. gRPC Port: 57510
Checking if Dapr sidecar is listening on HTTP port 57509
time="2021-02-19T10:21:46.6906962+08:00" level=info msg="starting Dapr Runtime -- version 1.0.0 -- commit 6314733" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.6906962+08:00" level=info msg="log level set to: info" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.6906962+08:00" level=info msg="metrics server started on :57511/" app_id=counter instance=KEXPRO scope=dapr.metrics type=log ver=1.0.0
time="2021-02-19T10:21:46.6956642+08:00" level=info msg="standalone mode configured" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.6956642+08:00" level=info msg="app id: counter" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.6956642+08:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.8896639+08:00" level=info msg="local service entry announced: counter -> 10.0.23.174:57516" app_id=counter instance=KEXPRO scope=dapr.contrib type=log ver=1.0.0
time="2021-02-19T10:21:46.8896639+08:00" level=info msg="Initialized name resolution to standalone" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.8956666+08:00" level=info msg="component loaded. name: pubsub, type: pubsub.redis/" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.8956666+08:00" level=info msg="waiting for all outstanding components to be processed" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.901666+08:00" level=info msg="component loaded. name: statestore, type: state.redis/" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9026649+08:00" level=info msg="all outstanding components processed" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9026649+08:00" level=info msg="enabled gRPC tracing middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.grpc.api type=log ver=1.0.0
time="2021-02-19T10:21:46.9026649+08:00" level=info msg="enabled gRPC metrics middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.grpc.api type=log ver=1.0.0
time="2021-02-19T10:21:46.9026649+08:00" level=info msg="API gRPC server is running on port 57510" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="enabled metrics http middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.http type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="enabled tracing http middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.http type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="http server is running on port 57509" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="The request body size parameter is: 4" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="enabled gRPC tracing middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.grpc.internal type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="enabled gRPC metrics middleware" app_id=counter instance=KEXPRO scope=dapr.runtime.grpc.internal type=log ver=1.0.0
time="2021-02-19T10:21:46.9036691+08:00" level=info msg="internal gRPC server is running on port 57516" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9046655+08:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=counter instance=KEXPRO scope=dapr.runtime.actor type=log ver=1.0.0
time="2021-02-19T10:21:46.9046655+08:00" level=warning msg="failed to read from bindings: app channel not initialized " app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
time="2021-02-19T10:21:46.9046655+08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 209.00130000000001ms" app_id=counter instance=KEXPRO scope=dapr.runtime type=log ver=1.0.0
Checking if Dapr sidecar is listening on GRPC port 57510
Dapr sidecar is up and running.
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

== APP == Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.

== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.

== APP ==    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

== APP ==    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

== APP ==    at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

== APP ==    --- End of inner exception stack trace ---

== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

== APP ==    at DaprCounter.Program.Main(String[] args) in C:\Users\freeman\Projects\learning-dapr\src\DaprCounter\Program.cs:line 18

== APP ==    at DaprCounter.Program.<Main>(String[] args)

time="2021-02-19T10:22:05.0407729+08:00" level=info msg="placement tables updated, version: 0" app_id=counter instance=KEXPRO scope=dapr.runtime.actor.internal.placement type=log ver=1.0.0

**Comment by amolenk** [comment]
Hmm, the counter application uses gRPC to talk to the Dapr sidecar, but something in your configuration is preventing the counter app from making a gRPC call over HTTP/2.

- Can you confirm that the version of the Dapr.Client NuGet package is 1.0.0?
- The second log shows a slightly different error than the original one you posted, have you changed something?

**Comment by amolenk** [comment]
@rynowak Do you know what could trigger a `System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.` error when trying to save state using the Dapr .NET SDK?

**Comment by amolenk** [comment]
@freemanke Also, could it be that there's a proxy or something running on your system that intercepts local traffic?

**Comment by rynowak** [comment]
> could it be that there's a proxy or something running on your system that intercepts local traffic?

I think that error generally means that you're trying to do gRPC with HTTP/2 to an endpoint that only does HTTP 1.1. An HTTP 1.1 proxy would be one of the typical causes. 

@jamesnk might know more as the master of all things gRPC.

**Comment by JamesNK** [comment]
"Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled."

I've never seen this error before.

**Comment by freemanke** [comment]
@rynowak Thank you all, i found i have used a VPN service, closed that, everything works.
thank you all again, i will close this issue.
