### ISSUE TITLE
Obsolete hint from compiler CS0251

### ISSUE THREAD

**Issue by VioletTape** [dotnet/docs#22900]
Indexing an array with a negative index is valid now and serves as expected. 

The article should be extended by mentioning which frameworks allow or forbid such behavior. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d7723f-d2fe-8742-f9c4-837e19a06788
* Version Independent ID: 893b348d-c339-1d17-1aff-2228c216022a
* Content: [Compiler Warning (level 2) CS0251](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0251)
* Content Source: [docs/csharp/misc/cs0251.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0251.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @VioletTape 

I need more details on where you've seen a negative array index as valid. The language rules don't include that.
