### ISSUE TITLE
Awesome content

### ISSUE THREAD

**Issue by saurabhprasadsah** [dotnet/docs#22905]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1ba1c23-a9c1-ab6d-0bb1-546f2e5125db
* Version Independent ID: 8453e25f-f762-95bb-0b58-8b7471837038
* Content: [.NET docs: What's new for January 2021](https://docs.microsoft.com/en-us/dotnet/whats-new/2021-01)
* Content Source: [docs/whats-new/2021-01.md](https://github.com/dotnet/docs/blob/master/docs/whats-new/2021-01.md)
* Product: **dotnet**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Thanks! I'll close this issue.
