### ISSUE TITLE
"Deploying a self-contained app" no localhost cert for ssl, no dotnet installed

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/docs#22914]
Hi

I think this is useful but needs more...

What I cannot figure out... is for "Deploying a self-contained app"

This means that dotnet is probably **not installed,** which mean you cannot run such command **"dotnet dev-certs https -v"**.

Which mean you **cannot get ssl working locally**

now... what would be nice if they explain how you would get this working step by step, for dev and prod if they should be different.

"Deploying a self-contained app" try running with something like 
 **sudo  ASPNETCORE_URLS=https://*:5001 ./dotnetWebApp**

This will **not work as there is no localhost cert.** it suggests "dotnet dev-certs https -v" but dotnet is not installed.

 **sudo  ASPNETCORE_URLS=http://*:5000 ./dotnetWebApp** - this works

If you install dotnet what was the point of "Deploying a self-contained app".

Please help, with how you get local ssl when you have not installed dotnet.
 Reason its not installed as you have gone with "Deploying a self-contained app"

looking for how this is done on Raspberry OS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to Raspberry Pi](https://docs.microsoft.com/en-us/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/master/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by adegeo** [comment]
Hello!

Taking a stab at answering your qestion.

Self contained deployment is generally for production distribution where the SDK/Runtime isn't going to be available. The dev-certs are for testing and shouldn't be used for production. When you get your certificates created (either via dev-certs for testing or your real certs for production) I believe you would deploy them with the container.

You can find more information at https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-5.0
