### ISSUE TITLE
missing semi-colon on last code line

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#22923]
final C# statement needs closing semi-colon

hint: this is going to be the easiest refactoring you do today!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c51e06b-f665-e97c-0862-02a7c33402ad
* Version Independent ID: b204adb3-855a-db49-a25c-71df4daf5988
* Content: [How to deserialize an object using XmlSerializer](https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-deserialize-an-object)
* Content Source: [docs/standard/serialization/how-to-deserialize-an-object.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/how-to-deserialize-an-object.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@DickBaker Thanks for reporting that
