### ISSUE TITLE
Using is better guidance

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#22924]
wrap the FileStream in a using block as best practice (pref the old way not new-fangled keep-it-hanging variety!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c51e06b-f665-e97c-0862-02a7c33402ad
* Version Independent ID: b204adb3-855a-db49-a25c-71df4daf5988
* Content: [How to deserialize an object using XmlSerializer](https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-deserialize-an-object)
* Content Source: [docs/standard/serialization/how-to-deserialize-an-object.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/how-to-deserialize-an-object.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Opened #22925 to fix this and also #22923

**Comment by tdykstra** [comment]
@DickBaker Thanks for the suggestion.
