### ISSUE TITLE
Scoping of using

### ISSUE THREAD

**Issue by cnotoham** [dotnet/docs#22920]
It's not an issue but rather a question.
In the code example provided, if I rewrite it like this:

```c#
string manyLines=@"This is line one
This is line two
Here is line three
The penultimate line is line four
This is the final, fifth line.";

using var reader = new StringReader(manyLines);
ReadAndLog(reader);

public void ReadAndLog(StringReader reader)
{
    string? item;
    do {
        item = reader.ReadLine();
        Console.WriteLine(item);
    } while(item != null);
}
```
Will the object reader still be properly disposed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
Yes.

It's equivalent to
```c#
using (var reader = new StringReader(manyLines))
{
    ReadAndLog(reader);
}
```
as the scope isn't "longer".

**Comment by BillWagner** [comment]
Thanks for the question @cnotoham and the prompt answer @gfoidl 

I'll close this as an answered question.
