### ISSUE TITLE
Missing info about .NET 6 required dependencies on "Install .NET on Windows" page

### ISSUE THREAD

**Issue by bairog** [dotnet/docs#22921]
[.NET 6 preview 1](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/) is out and supports [same Windows versions as .NET 5](https://github.com/dotnet/core/blob/master/release-notes/6.0/6.0-supported-os.md).
So I suppose that [Install .NET on Windows](https://docs.microsoft.com/ru-ru/dotnet/core/install/windows?tabs=net50) page should be updated with information about .NET 6 required dependencies for **Windows 7/Vista/8.1/Server 2008 R2/Server 2012 R2**. 
They are the same as for .NET 5 or there are differences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
The Supported OS information on the dotnet github wiki is generally the source of truth. Considering .NET 5 is supported until a few months after .NET 6 is released, they generally should have the same requirements related to OS. The only thing that could possibly be different is if the dependencies change a bit with .NET 6, choosing a better library, or a new feature requires something. If a new OS version comes out close to the end of .NET 5, I could see that being excluded.
