### ISSUE TITLE
visual basic

### ISSUE THREAD

**Issue by Ishmael-Chepsoi** [dotnet/docs#22927]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf2af5b-a967-49c6-b817-42f89389f64e
* Version Independent ID: 6fc2b2ea-b999-d766-a94f-9e0cc1e32683
* Content: [Concatenation Operators - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/concatenation-operators)
* Content Source: [docs/visual-basic/language-reference/operators/concatenation-operators.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/concatenation-operators.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
@Ishmael-Chepsoi This issue doesn't have any information for us. Did you submit it by accident? 

If you have more details, let us know. Otherwise, this issue will auto close in two weeks.

**Comment by Ishmael-Chepsoi** [comment]
I would wish to know if I can add sub project on solution explorer project

**Comment by BillWagner** [comment]
Thanks @Ishmael-Chepsoi 

Yes, you can add projects.  Right-click on the Solution in Solution Explorer, and select "Add New Project". 

I'll close this as an answered question.

**Comment by Ishmael-Chepsoi** [comment]
Thank you
