### ISSUE TITLE
Description seems incorrect

### ISSUE THREAD

**Issue by baystar47** [dotnet/docs#22926]
The last portion of the document says

_the separators have no semantic impact_

But the whole purpose of the Digit separators is to improve the semantics without any technical impact.
So I believe the statement above is incorrect.
Can this be rectified?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91fb1bf8-c018-efac-2728-1e78c8be9f67
* Version Independent ID: 707d70b1-fe37-6755-1be2-e62d41da11df
* Content: [Digit separators - C# 7.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/digit-separators)
* Content Source: [proposals/csharp-7.0/digit-separators.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/digit-separators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The statement appears to be correct to me. The separators improves code readability (i.e Syntax), while the semantics remains the same.

Semantics is about "What the code *means*".

**Comment by BillWagner** [comment]
Thanks for raising the question @baystar47 

As pointed out, the article is correct. The presence or absence of any digit separators doesn't change the meaning or the value of the expression.

I'll close this as answered.
