### ISSUE TITLE
How to print enumerables

### ISSUE THREAD

**Issue by mattiasw2** [dotnet/docs#22939]
[Enter feedback here]
You have properly described how to override .ToString() and make your own. But what if you only want to change the printing of one field?

```
    public record File
    {
        public string FileName;
        public ImmutableList<Picture> Pictures;
    }
```

where Pictures is also a record. I would like to print the whole structure. A functional programming language like F# handles this, and even do not print the whole ImmutableList if it is too long unless you change some configuration parameters.

Currently the above will just print something like:

`File { FileName = C:\data\s.xlsx, Pictures = System.Collections.Immutable.ImmutableList`1[mattias1.Picture] }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e843f3dc-1f90-2f0d-c62b-1d85e56a67c9
* Version Independent ID: 1fa3238c-f500-a6ad-db41-1280eb4b6d78
* Content: [Use record types - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/records)
* Content Source: [docs/csharp/tutorials/exploration/records.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
As far as I know, there is no direct way to approach this. You'll need to override the whole ToString, or implement a source generator to do so.

**Comment by mattiasw2** [comment]
This is part of all functional languages, and the records is an enhancement on this. For example, for ocaml, you have

**Comment by BillWagner** [comment]
ping @MadsTorgersen Has this come up in the records design discussions?

**Comment by MadsTorgersen** [comment]
Given where C# and .NET were at, there was really only one right decision for what ToString() should do on a record. In .NET each type is responsible for declaring how it is written out, and for better or worse, .NET collections generally don't list their elements. 

The only reasonable default behavior for a type that prints out its members is to to recursively use the textual representation that those members' types have chosen. We can't start printing members differently that they would print themselves. We already made these decisions in anonymous types in C# 3, and records closely follow that behavior:

``` c#
using static System.Console;
using System.Collections.Immutable;

var list = ImmutableList.Create(new Picture(), new Picture(), new Picture());

var recordFile = new File { FileName = "Name", Pictures = list };
WriteLine(recordFile);

var anonymousFile = new { FileName = "Name", Pictures = list };
WriteLine(anonymousFile);

public record File
{
    public string FileName;
    public ImmutableList<Picture> Pictures;
}

public class Picture { }
```

We _did_ discuss various ways to override record behavior for individual members, especially around equality, but in the end we felt that this would easily become overkill, and that the ability to overwrite the whole method manually (e.g. `Equals` or `ToString`), while more course grained, would have to be adequate. It is possible that we would consider expanding in this area at some point, but it quickly leads to diminishing returns.

**Comment by mattiasw2** [comment]
Thank you @MadsTorgersen  for the explanation. The combination "NET collections generally don't list their elements" and that you cannot override ToString for ImmutableList since sealed is a bit strange, but I assume it is done for performance. Otherwise, I could have made my on ImmutableList. 

The solution I am going for now is to use Newtonsoft and Json as the generic ToString format. It also has the advantage the printed data can be read back into C#.
