### ISSUE TITLE
connecting to mongodb from .net core application using apache spark

### ISSUE THREAD

**Issue by sindujacse** [dotnet/docs#22937]
Hello Team,

Can you help me how to add mongo-spark-connector in .net core console application. i can see it can be added to build definition but im unable to do so. please note Im  creating apache spark project and wanted to save data to Mongo db using this connector. please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b5a4ec-2c01-4d65-7e3c-0eef2965f013
* Version Independent ID: 850ab95d-3274-60ab-16f1-3c7150a639dc
* Content: [Connect .NET for Apache Spark to MongoDB](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/connect-to-mongo-db)
* Content Source: [docs/spark/how-to-guides/connect-to-mongo-db.md](https://github.com/dotnet/docs/blob/master/docs/spark/how-to-guides/connect-to-mongo-db.md)
* Product: **dotnet-spark**
* GitHub Login: @Niharikadutta
* Microsoft Alias: **nidutta**

**Comment by adegeo** [comment]
Sending email to @Niharikadutta

**Comment by Niharikadutta** [comment]
Hi @sindujacse apologies for the late reply, are you still facing issues with this? Could you explain what you've tried and which step in the article are you having trouble with?

**Comment by gewarren** [comment]
We're no longer updating the .NET for Apache Spark documentation, and have archived it to https://learn.microsoft.com/previous-versions/dotnet/spark/what-is-spark. As a result, we're closing all the active .NET for Apache Spark issues. I'm sorry we couldn't address your issue.
