### ISSUE TITLE
add description about  checking ubuntu version in docs/core/install/linux-ubuntu.md

### ISSUE THREAD

**Issue by sharkAndshark** [dotnet/docs#22944]
**Issue description**

if  bash command about checking ubuntu  version added to docs/core/install/linux-ubuntu.md,will this doc become wordy or novice friendly ?
just a little advice
![image](https://user-images.githubusercontent.com/42399654/108739526-af6e6780-756f-11eb-87ad-9e322a3027a6.png)

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
5.0.102
```
</details>

**Comment by adegeo** [comment]
Thank you for opening this suggestion. At this point I'm not going to add it as it's generally easy to just search on the internet "how to find ubuntu version." If you feel like this would be a good addition, please open a PR to make this change.

Cheers!
