### ISSUE TITLE
How to use docker and kubernetes on Windows server 2016?

### ISSUE THREAD

**Issue by vibhu12345** [dotnet/docs#22946]
The instructions work on windows 10 but there are no instructions on how to move this solution to production (windows server 2016) and the irony is the heading of these pages is "grpc in production".  Docker Desktop is not supported on window server 2016 and windows container created by docker EE cannot be scheduled on kubernetes. There is no clear guide on how to move ahead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e29d7c-df16-2f4c-3899-ffc2ba67b166
* Version Independent ID: d0d62cdb-fbc6-f663-e473-51369d756877
* Content: [Kubernetes - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/kubernetes)
* Content Source: [docs/architecture/grpc-for-wcf-developers/kubernetes.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by nishanil** [comment]
@shirhatti Please suggest what will be the guidance here.

**Comment by tdykstra** [comment]
ping @shirhatti

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
