### ISSUE TITLE
Typo in paragraph

### ISSUE THREAD

**Issue by swieder** [dotnet/docs#22948]
[Enter feedback here]
Have a typo in the following paragraph, "or" should be "of":

There are many examples _**or**_ ARM templates available in the Azure Quickstart Templates project on GitHub. They can help accelerate creating a new template or modifying an existing one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09be1939-e2a5-241e-4114-8747b35f3d21
* Version Independent ID: 7d77200d-9764-cabc-d5c1-c4d2ba3c2fd1
* Content: [Infrastructure as code](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code)
* Content Source: [docs/architecture/cloud-native/infrastructure-as-code.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/infrastructure-as-code.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Sreenivas-Kalluru** [comment]
Hi @swieder, Thanks for the feedback.
We have raised PR against this.
