### ISSUE TITLE
Not able to use this feature even after updating to c# 9.0

### ISSUE THREAD

**Issue by tarun98601** [dotnet/docs#22949]
Hi,

I am trying to use this feature in an override method using covariant type.

eg : BaseClass

`protected internal virtual BaseType foo(){ }`

DerivedClass

`protected internal override DerivedType foo() { }`

Here `DerivedType` is inheriting from `BaseType`. Even after updating LangVersion to 9.0. I am still getting this error : 

`Target runtime doesn't support covariant return types in overrides.`

I am using this on dotnetcore version 3.1.7. Is there some other change I need to do in order to use this functionality ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea4bb80-6f2f-0c4c-c3c4-9e0ca8b010f3
* Version Independent ID: 9a33575e-c8b4-e2a6-410c-288a2c16dc95
* Content: [Covariant return types - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/covariant-returns)
* Content Source: [proposals/csharp-9.0/covariant-returns.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/covariant-returns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
C# 9.0 is "officially" supported starting with .NET 5.0. You'll need to target .NET 5.0 to use this feature.

I'm not sure if there are any workarounds to get this working in versions before .NET 5.0.

Consider trying adding the following code files to your project:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeFeature.cs

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PreserveBaseOverridesAttribute.cs

(Not completely sure if they'll work, but worth a try)

**Comment by BillWagner** [comment]
Thanks for writing this @tarun98601 

As pointed out, you'll need to target .NET 5 for this feature to work correctly. We don't recommend the workaround mentioned above. It might compile, but it will circumvent important compiler safeguards for this feature.

Closing as an answered question.
