### ISSUE TITLE
A concrete example of the usage could be added

### ISSUE THREAD

**Issue by Catacomba** [dotnet/docs#22955]
At first glance this seems to be the same as passing by value without the `in` keyword. To illustrate the difference, an example such as in the top comment of this post could be added. https://stackoverflow.com/questions/52820372/why-would-one-ever-use-the-in-parameter-modifier-in-c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Catacomba 
This is related to #21691

I'll address it this month as part of that work.
