### ISSUE TITLE
trustedSigners support in .NET 5.0+

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#22959]
In a conversation with @mmitche, he noted to me that trustedSigners is supported in .NET 5.0+
The docs should be updated to reflect that.

(I'm not sure about other options that're being mentioned as not supported in the article)

Related to https://github.com/dotnet/docs/issues/6496.

cc: @adegeo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The article says trustedSigners is ignored because "[NuGet doesn't yet support cross-platform verification](https://github.com/NuGet/Home/issues/7939) of trusted packages." The link goes to an issue that is still open.

@nkolev92 is the statement that trustedSigners is ignored out of date?

**Comment by tdykstra** [comment]
ping @nkolev92

**Comment by nkolev92** [comment]
Cross platform package signature verification support was added in the .NET 5.0.100 SDK.

Unfortunately the docs don't make that super clear.
https://devblogs.microsoft.com/nuget/getting-started-with-nuget-5-8/
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.8

**Comment by tdykstra** [comment]
Thanks!
