### ISSUE TITLE
Wrong link in Code quality rules/Usage rules section

### ISSUE THREAD

**Issue by NiJeTi** [dotnet/docs#22960]
### Detected broken link to rule CA2247 (it leads to CA2246 rule's page).
Path: Code quality rules / Usage rules / Overview

![image](https://user-images.githubusercontent.com/5685857/108877427-47bc2900-7610-11eb-9e4b-ca2b527827a6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b53b96-ca04-0484-4bc5-17f95b069d0f
* Version Independent ID: 9ff2438d-06e3-1c56-4e6c-ad1e25ba3317
* Content: [Usage rules (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/usage-warnings)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/usage-warnings.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/usage-warnings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@NiJeTi Thank you for letting us know.
