### ISSUE TITLE
Figure 3-4. Dapr integration in eShopOnDapr.

### ISSUE THREAD

**Issue by amlaminaar** [dotnet/docs#22962]
Refer. Figure 3-4 Dapr integration in eShopOnDapr

Secrets and Service Invocation is numbered as 4. Service Invocation should be 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5a1dc6-9f1a-e030-9881-44e13ac6d450
* Version Independent ID: 5808b993-1f47-7801-6c0c-1b5725cd9711
* Content: [Introduction to the eShopOnDapr reference application](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/reference-application)
* Content Source: [docs/architecture/dapr-for-net-developers/reference-application.md](https://github.com/dotnet/docs/blob/master/docs/architecture/dapr-for-net-developers/reference-application.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by Sreenivas-Kalluru** [comment]
Hi @amlaminaar , Thank you for your valuable feedback.
It was updated and current legend Looks Good!.

![image](https://user-images.githubusercontent.com/69580789/108906389-d9df2400-7646-11eb-9877-eee1a54cc5ee.png)

**Comment by sughosneo** [comment]
I am closing this issue as it has already been addressed. Please feel free to reopen it, if you have any further questions.

Thank you.
