### ISSUE TITLE
Keep Linux dependencies up-to-date in docs

### ISSUE THREAD

**Issue by mthalman** [dotnet/docs#22967]
### Summary

The Linux dependencies described by the docs are defined independently of what the product's actual dependencies are.  These should be guaranteed to be in sync such that if product dependencies are changed in any way, the docs will reflect that change.  Today this is a manual process but it can be improved through the work being done in https://github.com/dotnet/core/issues/5651.

### Goal

Doc maintainers can use automation to validate and/or automatically update the docs such that the Linux packages described in the docs match up with the official product dependencies for each platform.

Relevant content: https://docs.microsoft.com/dotnet/core/install/linux
cc @adegeo

**Comment by adegeo** [comment]
Just found this old issue. I'm not sure what to do with it... @mthalman Is there a specific ask? Use automation seems pretty generic since I don't really have an example of how to scan and get the dependencies or something?
