### ISSUE TITLE
Simplify by using the monadic null-conditional operator

### ISSUE THREAD

**Issue by excelosaurus** [dotnet/docs#22968]
Needs some dusting off :-)
We can now safely use the monadic null-conditional operator "?" to simplify the code.
See
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#thread-safe-delegate-invocation
and
https://stackoverflow.com/a/32421459/2754509

Code would go from this:

        public void Add(int x)
        {
            total += x;
            if (total >= threshold)
            {
                ThresholdReachedEventArgs args = new ThresholdReachedEventArgs();
                args.Threshold = threshold;
                args.TimeReached = DateTime.Now;
                OnThresholdReached(args);
            }
        }

        protected virtual void OnThresholdReached(ThresholdReachedEventArgs e)
        {
            EventHandler<ThresholdReachedEventArgs> handler = ThresholdReached;
            if (handler != null)
            {
                handler(this, e);
            }
        }

To something like this:

        public void Add(int x)
        {
            total += x;
            if (total >= threshold)
                ThresholdReached?.Invoke(this, new ThresholdReachedEventArgs { Threshold = threshold, TimeReached = DateTime.Now });
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89598b6d-6319-fc9e-d7b7-3335f40e9506
* Version Independent ID: e074b827-7416-3c43-7fde-0244c61bb35c
* Content: [How to: Raise and Consume Events](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events)
* Content Source: [docs/standard/events/how-to-raise-and-consume-events.md](https://github.com/dotnet/docs/blob/master/docs/standard/events/how-to-raise-and-consume-events.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @excelosaurus
Thank you so much for posting this issue. We really appreciate it.

Good catch, you're correct this could be simplified. We'd happily welcome a pull request if you'd be interested in submitting the code changes? I've labeled this issue as `up-for-grabs`.

**Comment by iamvighnesh** [comment]
> Hi 👋 @excelosaurus
> Thank you so much for posting this issue. We really appreciate it.
> 
> Good catch, you're correct this could be simplified. We'd happily welcome a pull request if you'd be interested in submitting the code changes? I've labeled this issue as `up-for-grabs`.

@excelosaurus, Apologies for going naive here as I am a newbie to this repository. Do I need to shout out if I am going to pick this up?

**Comment by excelosaurus** [comment]
@iamvighnesh, no problem, go ahead! I am myself not a C# expert. I would like Microsoft's documentation to always be up-to-date with the latest language features and best practices; it would help enormously. Code examples should have some expiry date after which they are flagged for revisiting by MVPs.

**Comment by IEvangelist** [comment]
Hi @iamvighnesh and @excelosaurus - I agree, an expiration date on code samples would be a great way of tracking code samples that are aging. If you were to create a PR, or start working in a branch - I'd encourage you to create a draft pull request that could reference this issue. That would then link the two for transparency, letting us know that you're working on it.
