### ISSUE TITLE
Beat Pulse is Deprecated

### ISSUE THREAD

**Issue by noakesey** [dotnet/docs#22998]
This pages refers the reader to the Beat Pulse project in GIthub .. this has been deprecated.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef21d90-e916-6c71-5f28-4c13fe26710c
* Version Independent ID: 8ea5a31b-611a-dd67-f13d-1c292364d4da
* Content: [Resiliency and high availability in microservices](https://docs.microsoft.com/en-gb/dotnet/architecture/microservices/architect-microservice-container-applications/resilient-high-availability-microservices)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/resilient-high-availability-microservices.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/resilient-high-availability-microservices.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @noakesey, thanks for pointing this out, the GitHub project reference is no more present on the page. The issue can be closed now.
