### ISSUE TITLE
Get DisplayString

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/docs#22994]
Is there any Method that will return the Displaystring that can be used when printing code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06894978-816b-8627-a55b-53a91a67fff5
* Version Independent ID: cd96cc90-edeb-50c7-e192-3232bd8ed22d
* Content: [Accessibility Enum (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.accessibility?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.CodeAnalysis.Accessibility)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=roslyn-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Accessibility.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Accessibility.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
I don't think I understand your question in the context of this article @LokiMidgard Can you give me a small example of what you want to accomplish?

**Comment by LokiMidgard** [comment]
Sorry I try to be more precise.

I'm trying to generate code for a proxy. I run over the member of `ITypeSymbol` and for each member I write a property to a stringbuilder.

```

Stringbuilder str;
ITypeSymbol original;
// Get the type...
// Writing the beinning of the class to str...
foreach(var property in original.GetMembers())
{
  var access = property.DeclaredAccessibility;
  str.AppendLine($"{access} {property.Type.GetDisplayName()} {property.Name} => // return the original value...");
}
// finish the class...

```
The variable `access` is of Type `Accessibility`. What I would need to write is `private`, `public`,  `private protected`, etc... keywords to get written to the string, not the ToString() of the enum. Of course that's a simple mapping that can be done with a switch expression. But I wondered if this functionality is already present in an helper function.

This also would have the advantage, if the accessibility enum would ever get expanded the generator would automaticly know how to handle the new accassebility.

**Comment by Youssef1313** [comment]
@LokiMidgard I think you want [SyntaxFacts.GetText](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.visualbasic.syntaxfacts.gettext?view=roslyn-dotnet#Microsoft_CodeAnalysis_VisualBasic_SyntaxFacts_GetText_Microsoft_CodeAnalysis_Accessibility_) API.

**Comment by LokiMidgard** [comment]
@Youssef1313 I Think that is exactly what I'm searching for.

Thank You :)
