### ISSUE TITLE
Mistake in code sample

### ISSUE THREAD

**Issue by ishimmings** [dotnet/docs#22991]
The return value for second, overriden PrintMember method is void and should be bool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aba70b5-ee1a-90fd-b3ed-3384cd9f6512
* Version Independent ID: ab712864-bbc0-e4f9-cb32-15e12cd82c65
* Content: [Records - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records)
* Content Source: [proposals/csharp-9.0/records.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
You're correct @ishimmings, I opened https://github.com/dotnet/csharplang/pull/4464 to fix that.

**Comment by BillWagner** [comment]
Thanks for pointing this out @ishimmings 

Thank you for submitting the PR @Youssef1313
