### ISSUE TITLE
Function applications with parenthesis and one multiline application

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#23004]
Hello,

In the section [Formatting constructors, static members, and member invocations](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-function-parameter-application) all examples seem to have multiple arguments. What happens is there is only a single long (multiline) argument wrapped in parenthesis?

```fsharp
let poemBuilder = StringBuilder()
poemBuilder.AppendLine("""
The last train is nearly due
The Underground is closing soon
And in the dark, deserted station
Restless in anticipation
A man waits in the shadows
""")

Option.traverse(
    create
    >> Result.setError [ invalidHeader "Content-Checksum" ]
)
```

does the 
```fsharp
functionName (
    arg // indented
)
```

shape remain? Or should it change to

```fsharp
functionName
    (arg) // indented
```

Next I have another related question: do the same rules for `constructors, static members and member invocations` also apply to regular functions that take a single tuple parameter?

```fsharp
let myFunction (a: int, b: string, c: int, d: bool) =
    ()

myFunction (
    478815516,
    "A very long string making all of this multi-line",
    1515,
    false
)
```

From a more technical point of view these are all just function calls (`SynExpr.App (someIdent, Paren(Tuple()))`).
So I would expect the same formatting, though the style guide does not really specify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Great question!

I generally think that the same shape should remain, and this should also apply to tupled arguments for a long tuple as a single arg. I'd happily accept a PR that clarifies this.

**Comment by cmeeren** [comment]
I need a clarification. In #23130, the changes refer to _tuple_ elements. But in the example above:

```f#
Option.traverse(
    create
    >> Result.setError [ invalidHeader "Content-Checksum" ]
)
```

Is that argument considered a tuple? It's parenthesized, sure, but is it covered by or relevant to the changes in #23130?
