### ISSUE TITLE
hay 

### ISSUE THREAD

**Issue by ABOOD0969** [dotnet/docs#23005]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 404a6b9d-5bb1-6fc6-fdb6-3ebd384ad4c9
* Version Independent ID: 04d041fc-a16f-67c4-6f54-59dec7c603cb
* Content: [Special Characters - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/)
* Content Source: [docs/csharp/language-reference/tokens/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by adegeo** [comment]
@ABOOD0969 It seems you may have opened this issue in error. Please add the relevant details about the issue you're having with the article. This issue will automatically close itself in 2 weeks if you don't respond. Cheers!
