### ISSUE TITLE
Code sample doesn't match templated code

### ISSUE THREAD

**Issue by davidgeoffreyjones** [dotnet/docs#23014]
In the section "Write the Code fix" the sample code line:
``` csharp
private const string title = "Make constant";
```
is no longer correct. It has been replaced with a reference to the resource file (`CodeFixResources.CodeFixTitle`), so the edit should be made in `CodeFixResources.resx`.

Also, two more code samples down in the document, the code should read:
```csharp
 // Register a code action that will invoke the fix.
 context.RegisterCodeFix(
     CodeAction.Create(
         title: CodeFixResources.CodeFixTitle,
         createChangedDocument: c => MakeConstAsync(context.Document, declaration, c),
         equivalenceKey: nameof(CodeFixResources.CodeFixTitle)),
     diagnostic);
```

Further, the unit test code is out of date. Current VS2019 sample code is async and uses fluent syntax.

First TestMethod code should be:
```csharp
//No diagnostics expected to show up
[DataTestMethod]
[DataRow("")]
public async Task WhenTestCodeIsValidNoDiagnosticIsTriggered(string testCode)
{
   await VerifyCS.VerifyAnalyzerAsync(testCode);
}
```

Second test method should be:
```csharp
//Diagnostic and CodeFix both triggered and checked for
[DataTestMethod]
[DataRow(LocalIntCouldBeConstant, LocalIntCouldBeConstantFixed, 10, 13)]
public async Task WhenDiagnosticIsRaisedFixUpdatesCode(
   string test,
   string fixTest,
   int line,
   int column)
{
   var expected = VerifyCS.Diagnostic(MakeConstAnalyzer.DiagnosticId)
      .WithSeverity(DiagnosticSeverity.Warning)
      .WithMessage(new LocalizableResourceString(nameof(MakeConst.Resources.AnalyzerMessageFormat), MakeConst.Resources.ResourceManager, typeof(MakeConst.Resources)).ToString())
      .WithLocation("/0/Test0.cs", line, column);

   await VerifyCS.VerifyAnalyzerAsync(test, expected);
   await VerifyCS.VerifyCodeFixAsync(test, expected, fixTest);
}
```

And one more code change that currently causes the unit tests to fail. The following is invalid:
```csharp
private const string MultipleInitializers = @"
using System;

namespace MakeConstTest
{
    class Program
    {
        static void Main(string[] args)
        {
            int i = 0, j = DateTime.Now.DayOfYear;
            Console.WriteLine(i, j);
        }
    }
}";
```
Specifically, `Console.WriteLine(i, j);` is a compiler error. It should be:
```csharp
            Console.WriteLine(i);
            Console.WriteLine(j);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @davidgeoffreyjones 

I've added it to the backlog for when we update this section.

**Comment by Youssef1313** [comment]
I'm working on this.
