### ISSUE TITLE
Incorrect syntax - TestPriority

### ISSUE THREAD

**Issue by WilliamMega** [dotnet/docs#23026]
Code:

string assemblyName = typeof(TestPriorityAttribute).AssemblyQualifiedName!;

Right:

string assemblyName = typeof(TestPriorityAttribute).AssemblyQualifiedName;

Remove the "!" Character?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17b1fbc-2e79-c453-ef83-2ffff1683d5c
* Version Independent ID: b82fafa9-47c1-1c5a-93a3-669782e915eb
* Content: [Order unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests)
* Content Source: [docs/core/testing/order-unit-tests.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/order-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment]
The `!` is there because the code is written in nullable-enabled context. See [null-forgiving operator](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/null-forgiving) for more information. While the code is correct, I think it should either be made clear it's written in nullable-enabled context, or disable nullable.

@IEvangelist Can you add the document details to the original issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17b1fbc-2e79-c453-ef83-2ffff1683d5c
* Version Independent ID: b82fafa9-47c1-1c5a-93a3-669782e915eb
* Content: [Order unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests)
* Content Source: [docs/core/testing/order-unit-tests.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/order-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by WilliamMega** [comment]
I get an error when I inform the "!" (Cancellation) in my project.

string assemblyName = typeof(TestPriorityAttribute).AssemblyQualifiedName!;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8370	Feature 'nullable reference types' is not available in C# 7.3. Please use language version 8.0 or greater.	Util	C:\Users\BSI93387\Source\Repos\bs2.credito.tst.automacao\src\Util\Config\Orderers.cs	37	Active

Even updating to version 8.0 the error persists (I am updating only the project).

**Comment by Youssef1313** [comment]
@WilliamMega You need to also enable nullable reference types feature after upgrading to C# 8.0. See [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) for more information.

**Comment by WilliamMega** [comment]
Perfeito e muito obrigado @Youssef1313.

I'm trying to order the execution of my tests and even using the code in the link below:

https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit

Here is an excerpt from my code, below:

namespace Bs2.Credito.Antecipacao.Empresa.Bff.Tests
{

    [Collection("DadosCliente")]
    [TestCaseOrderer("Util.Config.Orderers.PriorityOrderer", "Bs2.Credito.Antecipacao.Empresa.Bff.Tests")]
    public class TestObterDadosClienteTests : TestBase, IDisposable
    {

        [Fact(DisplayName = "DadosCliente 2"), TestPriority(2)]
        [Trait("Categoria", "Integration")]
        public async Task DadosCliente2_DeveRetornarSucesso()
        {
                     ........... 
        }

        [Fact(DisplayName = "DadosCliente 1"), TestPriority(1)]
        [Trait("Categoria", "Integration")]
        public async Task DadosCliente1_DeveRetornarSucesso()
        {
                     ........... 
        }
    }
}

But the ordering is not working properly, could you help me?

I emphasize that the execution is happening like this:

1) DadosCliente 2 - 01/03/2021 - 09:46:27

2) DadosCliente 1 - 01/03/2021 - 09:46:35

**Comment by Youssef1313** [comment]
I'm not sure. @IEvangelist Would you be able to assist here?

**Comment by Youssef1313** [comment]
Ok I just saw you have a separate issue for this (https://github.com/dotnet/docs/issues/23044). Should this one be closed?

**Comment by adegeo** [comment]
> The `!` is there because the code is written in nullable-enabled context. See [null-forgiving operator](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/null-forgiving) for more information. While the code is correct, I think it should either be made clear it's written in nullable-enabled context, or disable nullable.
> 
> ~IEvangelist Can you add the document details to the original issue?~

I updated the the item with the doc info, thanks. I'll bring this situation up for discussion.

**Comment by WilliamMega** [comment]
Resolved.

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <NullableContextOptions>enable</NullableContextOptions>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
