### ISSUE TITLE
The incorrect line of code is highlighted in the example.

### ISSUE THREAD

**Issue by BasPaap** [dotnet/docs#23023]
The article states: 

>Create an instance of a default implementation class by using a factory method on the base algorithm class, and refer to the base algorithm class. For example, see the highlighted line of code in the following example:

However, the highlighted line is:

    using FileStream myStream = new FileStream("TestData.txt", FileMode.OpenOrCreate);

Which does not refer to cryptography classes, and does not use a factory method to create an instance. Instead, I think the highlighted line should be

    using Aes aes = Aes.Create();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc59c0ef-fc24-730b-086a-683bb85fca7a
* Version Independent ID: 93212589-e9f6-4bf8-d547-559743e3eb5e
* Content: [.NET Cryptography Model](https://docs.microsoft.com/en-us/dotnet/standard/security/cryptography-model)
* Content Source: [docs/standard/security/cryptography-model.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/cryptography-model.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment]
This broke in https://github.com/dotnet/docs/pull/21043

**Comment by IEvangelist** [comment]
Hi 👋 @BasPaap
Thank you so much for posting this issue. We really appreciate it. I have a fix for this in https://github.com/dotnet/docs/pull/23025
