### ISSUE TITLE
[Feedback] The Linux installation documentation as well as the used system locations during the installations has succeeded at frustrating and confusing me.

### ISSUE THREAD

**Issue by MostHated** [dotnet/docs#23035]
Trying to follow the provided guides on installation from https://dotnet.microsoft.com, I now have SDK's in at least these places:

<details>
<summary>

```sh
/usr/share/dotnet/sdk
```

</summary>

![](https://i.imgur.com/IJ2N3gY.png)

</details>

<details>
<summary>

```sh
~/dotnet/sdk
```

</summary>

![](https://i.imgur.com/8P5iXJx.png)

</details>

<details>
<summary>

```sh
~/.dotnet/sdk
```

</summary>

![](https://i.imgur.com/HwWDA3P.png)

</details>

But when I do 

<details>
<summary>

```sh
dotnet new --list
```

</summary>

![](https://i.imgur.com/ovalVqp.png)

</details>

I get "The framework 'Microsoft.NETCore.App', version '6.0.0-preview.1.21102.12' was not found." with a link to https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0-preview.1.21102.12&arch=x64&rid=pop.20.10-x64, which I just installed, tried again, and got the same error.

It is quite fitting that it is called .Net, because you get trapped and tangled and can't figure out heads from tails.

Please pick *ONE* place to install things, this is so frustrating and confusing. Rider also can't figure out what in the world is going on, and I followed the official guides!

---
This has you set env variables..
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.1-linux-x64-binaries
 ($HOME/dotnet)
```sh
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

Which are different than the environment variables that this looks for (the dotnet-install script doesn't use that env variable at *all*), and if they are not found, it uses a different folder.
https://dot.net/v1/dotnet-install.sh 
($HOME/.dotnet)

```sh
614: get_user_install_path() {
615:     eval $invocation
616: 
617:     if [ ! -z "${DOTNET_INSTALL_DIR:-}" ]; then
618:         echo "$DOTNET_INSTALL_DIR"
619:     else
620:         echo "$HOME/.dotnet"
621:     fi
622:     return 0
623: }
```
Then this one does something different altogether in a different location:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2010-
(/usr/share/dotnet/sdk)

Things are spread all throughout the system and can't even be found by the 'dotnet' executable.

![](https://i.imgur.com/Ql2vRdG.png)

So.. how is one supposed to proceed here?
I now have a dotnet executable in:

~/.dotnet/dotnet
~/dotnet/dotnet 
/usr/share/dotnet/dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux Distributions](https://docs.microsoft.com/en-us/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hey there @MostHated sorry for the confusion. I'll start investigating this and see how we can make this all unified. On Windows the `~/.dotnet` folder is the data folder where things like global tools are installed, while the `Program Files/dotnet` folder is the place where the dotnet executable and `sdk` subdirectory are located.

**Comment by adegeo** [comment]
OK tested a bit. Installing via the package manager for Ubuntu 20.04 works out these folders, the default places dotnet searches for data:

| item | path |
| --- | --- |
|dotnet command |  `/usr/bin/dotnet` |
|dotnet install folder | `/usr/share/dotnet/` |
|dotnet data folder | `$HOME/.dotnet/` |

I'm going to mention this issue in the install scripts repo. It doesn't seem like the script should be using the `.dotnet` folder.

Regarding `$DOTNET_ROOT` the script shouldn't use this technically as it's used by the dotnet program itself (or apps you build with dotnet) to locate the installation path of dotnet if dotnet isn't installed to the normal path (`/usr/share/dotnet/`)

**Comment by adegeo** [comment]
As to why your .NET 6 install isn't getting picked up, I'm not sure. Did it start to work after you set the env variables?

```bash
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

What does `which dotnet` tell you? I'm guessing that you're having a problem due to installing via a package manager which created a `dotnet` command in the `/usr/bin` folder and then your path pointing to another version, and there being a conflict somewhere.

**Comment by MostHated** [comment]
What you mentioned sounds like that is probably the case. I was attempting to use a .Net plugin with Unreal Engine and kept having issues, and I want to say that somewhere there was a message that mentioned something about a version being different than expected. 

The very first steps I followed were the ones listed here to install via the package manager: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2010-
This was a few days ago, but I want to say it was the Rider IDE not being able to detect the SDK, which was when I went back to the site to see if missed something, which was what lead to additional attempts at things.

`$ which dotnet` comes back with `/usr/bin/dotnet`

Here is some additional information 

<details>
<summary>

`dotnet --info`

</summary>

```sh
~ » dotnet --info                                                                                                                                 mosthated@pop-os
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Runtime Environment:
 OS Name:     pop
 OS Version:  20.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

</details>

It also looks like I have 3 dotnet binaries between, the usr/share, ~/.dotnet and ~/dotnet:

<details>
<summary>

`find / -executable -type f -name "dotnet" -xdev -print 2>/dev/null`

</summary>

```sh
/usr/share/dotnet/dotnet
/home/mosthated/.dotnet/dotnet
/home/mosthated/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.6682.21/lib/ReSharperHost/linux-arm64/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.6682.21/lib/ReSharperHost/linux-x64/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.6682.21/lib/ReSharperHost/macos-x64/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.7148.23/lib/ReSharperHost/linux-arm64/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.7148.23/lib/ReSharperHost/linux-x64/dotnet/dotnet
/home/mosthated/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/203.7148.23/lib/ReSharperHost/macos-x64/dotnet/dotnet
/home/mosthated/Unity/Hub/Editor/2021.1.0b7/Editor/Data/NetCore/runtime-317-linux-x64/dotnet
/home/mosthated/Unity/Hub/Editor/2021.2.0a5/Editor/Data/NetCore/runtime-317-linux-x64/dotnet
/home/mosthated/Unity/Hub/Editor/2020.2.5f1/Editor/Data/NetCore/runtime-317-linux-x64/dotnet
/home/mosthated/Unity/Hub/Editor/2020.2.5f1/Editor/Data/NetCore/Sdk-2.2.107/dotnet
/home/mosthated/Unity/Hub/Editor/2021.1.0b8/Editor/Data/NetCore/runtime-317-linux-x64/dotnet
/home/mosthated/Unity/Hub/Editor/2020.1.6f1/Editor/Data/NetCore/Sdk-2.2.107/dotnet
/home/mosthated/Unity/Hub/Editor/2019.4.20f1/Editor/Data/NetCore/Sdk-2.2.107/dotnet

```

</details>

Lastly, I originally had:

```sh
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$PATH:$HOME/.dotnet"
```
but as I mentioned I was having issues with UnrealCLR and not being able to locate the SDK, so I decided to try changing that to:

```sh
export DOTNET_ROOT="$HOME/dotnet"
export PATH="$PATH:$HOME/dotnet"
```
This let UnrealCLR find the SDK and that seemed to be ok, but it crashes everytime I get to the actual runtime portion of it, but I am not sure if that part is related.

Having it set to that also shows:

<details>
<summary>~ » dotnet --list-runtimes  </summary>

```sh
                                                                                                                      mosthated@pop-os
Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

</details>

but `--list-sdks` still only has `5.0.103 [/usr/share/dotnet/sdk]`

What actually would the proper setup end up being, so that I can try and clean this up and get things working properly?

Thanks,
-MH

**Comment by adegeo** [comment]
Sorry for the delay, this sort of floated away from me.. 

In your current state, the `/usr/bin/dotnet` symlink is pointing to the `dotnet` command in the `/usr/share/dotnet/` folder. That is where you're going to be loading SDK/Runtimes from for normal `dotnet` operations. If something is trying to just run commands for .NET, it will resolve here. I would change your `DOTNET_ROOT` variable to point to that folder. Then install the .NET SDK (if using the script to install, set that as the install path). Then remove the other SDK/Runtimes.

**Comment by adegeo** [comment]
I'm going to close this issue, I don't think there is anything left to do here? I don't remember though 😁

**Comment by MostHated** [comment]
No worries, I don't remember either, and things have been fine on my end. :+1:
