### ISSUE TITLE
Not ordering my tests - https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit

### ISSUE THREAD

**Issue by WilliamMega** [dotnet/docs#23044]
I'm trying to order the execution of my tests and even using the code in the link below:

https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit

Here is an excerpt from my code, below:

```csharp
namespace Bs2.Credito.Antecipacao.Empresa.Bff.Tests
{

[Collection("DadosCliente")]
[TestCaseOrderer("Util.Config.Orderers.PriorityOrderer", "Bs2.Credito.Antecipacao.Empresa.Bff.Tests")]
public class TestObterDadosClienteTests : TestBase, IDisposable
{

    [Fact(DisplayName = "DadosCliente 2"), TestPriority(2)]
    [Trait("Categoria", "Integration")]
    public async Task DadosCliente2_DeveRetornarSucesso()
    {
                 ........... 
    }

    [Fact(DisplayName = "DadosCliente 1"), TestPriority(1)]
    [Trait("Categoria", "Integration")]
    public async Task DadosCliente1_DeveRetornarSucesso()
    {
                 ........... 
    }
}
}
```
But the ordering is not working properly, could you help me?

I emphasize that the execution is happening like this:

```
DadosCliente 2 - 01/03/2021 - 09:46:27

DadosCliente 1 - 01/03/2021 - 09:46:35
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17b1fbc-2e79-c453-ef83-2ffff1683d5c
* Version Independent ID: b82fafa9-47c1-1c5a-93a3-669782e915eb
* Content: [Order unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit)
* Content Source: [docs/core/testing/order-unit-tests.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/order-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by adegeo** [comment]
@WilliamMega Hello. It may be harder to see where the issue is without more code. One thing I noted that you may have missed is that there are some assembly-level attributes declared in the example, have you implemented these?

![image](https://user-images.githubusercontent.com/67293991/109528333-6afc3380-7a69-11eb-8673-76d1019bb7f4.png)

**Comment by WilliamMega** [comment]
The ordering I am trying to use is about "Test Priority (1)" and according to the code in the link (Code at the link: https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit) it is not necessary to implement some assembly level attributes.

- This code does not work (Code at the link: https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit):

namespace XUnit.Project.Orderers
{
    public class AlphabeticalOrderer : ITestCaseOrderer
    {
        public IEnumerable<TTestCase> OrderTestCases<TTestCase>(
            IEnumerable<TTestCase> testCases) where TTestCase : ITestCase =>
            testCases.OrderBy(testCase => testCase.TestMethod.Method.Name);
    }
}

- The code below works correctly, remembering that these codes are for executing the tests according to the test name (DisplayName).

namespace XUnit.Project.Orderers
    public class CustomTestCaseOrderer : ITestCaseOrderer
    {
        public IEnumerable<TTestCase> OrderTestCases<TTestCase>(IEnumerable<TTestCase> testCases)
            where TTestCase : ITestCase
        {
            return testCases.OrderByDescending(test => test.DisplayName);
        }
    }

**But I need it to be ordered via "TestPriority".**

:(

**- Here is the class "Orderers":**

using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;
using Xunit.Sdk;

namespace Util.Config.Orderers
{
    public class CustomTestCollectionOrderer : ITestCollectionOrderer
    {
        public IEnumerable<ITestCollection> OrderTestCollections(IEnumerable<ITestCollection> testCollections)
        {
            return testCollections.OrderByDescending(collection => collection.DisplayName);
        }
    }

    public class CustomTestCaseOrderer : ITestCaseOrderer
    {
        public IEnumerable<TTestCase> OrderTestCases<TTestCase>(IEnumerable<TTestCase> testCases)
            where TTestCase : ITestCase
        {
            return testCases.OrderByDescending(test => test.DisplayName);
        }
    }

    public class PriorityOrderer : ITestCaseOrderer
    {
        public IEnumerable<TTestCase> OrderTestCases<TTestCase>(
            IEnumerable<TTestCase> testCases) where TTestCase : ITestCase
        {
            string assemblyName = typeof(TestPriorityAttribute).AssemblyQualifiedName!;
            var sortedMethods = new SortedDictionary<int, List<TTestCase>>();
            foreach (TTestCase testCase in testCases)
            {
                int priority = testCase.TestMethod.Method
                    .GetCustomAttributes(assemblyName)
                    .FirstOrDefault()
                    ?.GetNamedArgument<int>(nameof(TestPriorityAttribute.Priority)) ?? 0;

                GetOrCreate(sortedMethods, priority).Add(testCase);
            }

            foreach (TTestCase testCase in
                sortedMethods.Keys.SelectMany(
                    priority => sortedMethods[priority].OrderBy(
                        testCase => testCase.TestMethod.Method.Name)))
            {
                yield return testCase;
            }
        }

        private static TValue GetOrCreate<TKey, TValue>(
            IDictionary<TKey, TValue> dictionary, TKey key)
            where TKey : struct
            where TValue : new() =>
            dictionary.TryGetValue(key, out TValue result)
                ? result
                : (dictionary[key] = new TValue());
    }
}

**Comment by adegeo** [comment]
@williammega the only reason I brought up the assembly attribute is that there is `CollectionBehavior` which disables the tests running in parallel and enables you to use an orderer. Do you have that assembly attribute declared?

**Comment by WilliamMega** [comment]
I use this configuration at the root of my project:

xunit.runner.json

{
  "parallelizeAssembly": false,
  "parallelizeTestCollections": false
}

Note: I need this to also generate a test report.

**Comment by adegeo** [comment]
The article lists https://github.com/dotnet/samples/tree/master/csharp/unit-testing as the source code, have you tried that to see if it works? I was just about to but my Visual Studio is crashing and I need to update. Maybe you can compare your code there?

**Comment by WilliamMega** [comment]
@adegeo 

I tried to use the article "https://github.com/dotnet/samples/tree/master/csharp/unit-testing" and even then ordering via TestPriority () doesn't work.

Very strange.

**Comment by adegeo** [comment]
Hrm.. I just tried the samples project and it all worked as expected for me. The only thing that stands out as a possible error is this code from your project:

```csharp
[Collection("DadosCliente")]
[TestCaseOrderer("Util.Config.Orderers.PriorityOrderer", "Bs2.Credito.Antecipacao.Empresa.Bff.Tests")]
public class TestObterDadosClienteTests : TestBase, IDisposable
```

The 2nd parameter on `TestCaseOrderer` attribute is supposed to be the assembly name defining the orderer. Did you perhaps use the namespace instead?

Also, I noticed that you're using `async` could it be that your tests are being called in order but finishing out of order because of the behavior of `async`? Try removing `async`.

If none of these suggestions fix your problem, you may need to visit StackOverflow and ask there, you'll get a lot more people looking at your question than just the few here.

**Comment by WilliamMega** [comment]
No second parameters changed to "[TestCaseOrderer (" Util.Config.Orderers.PriorityOrderer "," Util.Config ")]", but do not continue to sort.

About the "async" property, it is not being executed asynchronously due to the configuration in the "xunit.runner.json" file

Content:

{
  "parallelizeAssembly": false,
  "parallelizeTestCollections": false
}

Here is an image of my project.

Note: There is the "Util" project.

![image](https://user-images.githubusercontent.com/11398195/109691071-d0354f00-7b65-11eb-9200-37f2125ead6a.png)

Execution details:

Code:

![image](https://user-images.githubusercontent.com/11398195/109692318-23f46800-7b67-11eb-9080-5b516a1dfcaf.png)

Report:

![image](https://user-images.githubusercontent.com/11398195/109692344-2b1b7600-7b67-11eb-8142-5618ebd6ccbb.png)

About StackOverflow, they sent the link to solve the problem "https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests?pivots=xunit", so I am having problems with follow the link, so I'm asking for help.

**Comment by WilliamMega** [comment]
I'm changing the sequence (TestPriority) all the time in the class, to do some tests

**Comment by WilliamMega** [comment]
It worked like this:

[TestCaseOrderer ("Util.Config.Orderers.PriorityOrderer", "Util")]

Thank you very much @adegeo

**Comment by tactical-drone** [comment]
Ordering does not work at all. All example code provided by MS does not work. 

Seems to be intermittently jamming. When you debug the ordering customization code it becomes clear that xunit is broken.

This is for .net6.
