### ISSUE TITLE
Feedback - please add option for folks to check using PowerShell

### ISSUE THREAD

**Issue by kristianjaeger** [dotnet/docs#23048]
[Enter feedback here]
Feedback - please add option for folks to check using PowerShell

Example script:
```powershell
$releaseKey = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release

if ($releaseKey -ge 528040)
{
    Write-Host "4.8 or later";
    exit
}
if ($releaseKey -ge 461808)
{
    Write-Host "4.7.2";
    exit
}
if ($releaseKey -ge 461308)
{
    Write-Host "4.7.1";
    exit
}
if ($releaseKey -ge 460798)
{
    Write-Host "4.7";
    exit
}
if ($releaseKey -ge 394802)
{
    Write-Host "4.6.2";
    exit
}
if ($releaseKey -ge 394254)
{
    Write-Host "4.6.1";
    exit
}
if ($releaseKey -ge 393295)
{
    Write-Host "4.6";
    exit
}
if ($releaseKey -ge 379893)
{
    Write-Host "4.5.2";
    exit
}
if ($releaseKey -ge 378675)
{
    Write-Host "4.5.1";
    exit
}
if ($releaseKey -ge 378389)
{
    Write-Host "4.5";
    exit
}
else
{
    // This code should never execute. A non-null release key should mean
    // that 4.5 or later is installed.
    Write-Host "No 4.5 or later version detected"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Hello. The article has a powershell command documented in it [here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#use-powershell-to-check-for-a-minimum-version) If your suggestion is to improve that code with text output that tells you the version you're installing, we're not going to take that suggestion at this time. It's not really a priority to include that information at the moment. If things change, we can add it. Thank you for the suggestion though.

**Comment by kristianjaeger** [comment]
Yes, this was a suggestion to improve the PowerShell to show which version **is** installed.  Cheers.
