### ISSUE TITLE
Append text to an existing file, new StreamWriter missing 

### ISSUE THREAD

**Issue by Caio-Rezende** [dotnet/docs#23050]
using System.IO;
using System.Threading.Tasks;

class StreamWriterTwo
{
    public static async Task ExampleAsync()
    {
        using StreamWriter file = new **StreamWriter** ("WriteLines2.txt", append: true);
        await file.WriteLineAsync("Fourth line");
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fbd113-dbad-8aef-4e74-151b0b7189ff
* Version Independent ID: 1e02473f-562b-aa40-756e-1c147cf41041
* Content: [How to write to a text file - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-write-to-a-text-file)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
It's not missing. See https://github.com/dotnet/docs/issues/22810 for details. Also see discussion at https://github.com/dotnet/docs/pull/22870#discussion_r577873659.

**Comment by Caio-Rezende** [comment]
Clearly I was on older c# version on mu project.
