### ISSUE TITLE
Not precise paths at least for Ubuntu 20.04 (LTS)

### ISSUE THREAD

**Issue by yury-fedorov** [dotnet/docs#23063]
The paths and structure are not  precise at least for Ubuntu 20.04 (LTS).
dotnet is located there inside: /usr/share/dotnet/shared/ and /usr/share/dotnet/sdk/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/install/remove-runtime-sdk-versions.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for spotting this. I'll get it fixed.
