### ISSUE TITLE
Forum link is dead

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#23076]
The forum link points to the old MSDN forums, should now point to

https://docs.microsoft.com/en-us/answers/topics/dotnet-visual-basic.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085169bc-852c-e098-98d8-034ae0dcab43
* Version Independent ID: 443afec7-4f38-7d32-8248-211ea6625aec
* Content: [Additional resources for Visual Basic programmers - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/additional-resources)
* Content Source: [docs/visual-basic/getting-started/additional-resources.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/additional-resources.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
Opened #23077 to address this.

**Comment by BillWagner** [comment]
Thanks for pointing this out @karenpayneoregon
