### ISSUE TITLE
Still need Set

### ISSUE THREAD

**Issue by CH-MN** [dotnet/docs#23071]
Note on page states "Earlier Versions" of VB or VBA not using Set triggered this error.   It states that Set is no longer required in VB **.Net**, but the wording gives the impression that it is no longer an issue with newer versions of VB and VBA, but I was getting this error in Excel 2016 and the problem was that I was not using Set.  The note should be modified to make it more clear that it is still an issue in VBA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d661f3-f79b-5886-5fc9-5e9dc88886a7
* Version Independent ID: 85ed7310-c84b-0b76-c94c-5cbdd7cf86da
* Content: [Object variable or With block variable not set - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set)
* Content Source: [docs/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/error-messages/object-variable-or-with-block-variable-not-set.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
@CH-MN 

I'll close this, as the change you request doesn't apply to VB.NET.
