### ISSUE TITLE
Enhance --add-source documentation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23075]
It's not clear if the source specified in `--add-source` always take precedence of other sources defined in NuGet.config or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@wli3 can you answer this question?

**Comment by wli3** [comment]
the document from the command line help is accurate "Add an additional NuGet package source to use during installation."

It is in addition to default nuget feed search like nuget.confg

**Comment by Youssef1313** [comment]
@wli3 It's still a bit unclear to me whether there are any precedence.

For example:

My NuGet.config has a feed called "FeedA".
I passed "FeedB" to --add-source.

If the package exists on **both** feeds. Will it get resolved from "FeedB", or it's non-deterministic?

**Comment by wli3** [comment]
you could also have multiple feed in the same nuget.confg. unless it is a local feed, nuget would restore the package from the feed first responded.

**Comment by tdykstra** [comment]
Would this then be accurate:

Feeds are accessed in parallel, not sequentially in some order of precedence. If the same package and version is in multiple feeds, the fastest feed wins.

**Comment by wli3** [comment]
@nkolev92 to double check
that looks correct

**Comment by nkolev92** [comment]
Yeah, that's correct. You can link https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process that covers how installation works.
