### ISSUE TITLE
Out of date semantics of public methods.

### ISSUE THREAD

**Issue by geeknoid** [dotnet/docs#23085]
C# 9.0 changed the semantics of partial methods, this page needs to be updated accordingly. New semantics: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/extending-partial-methods.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450a248b-ab3f-ac3f-d3a5-b1e74b3355ba
* Version Independent ID: 5e05ac12-7d29-d144-a49a-e54765343c20
* Content: [Partial Classes and Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods#partial-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @geeknoid I've added this to the update list.

**Comment by BillWagner** [comment]
Fixed in #24764
