### ISSUE TITLE
Bug in lorem-ipsum.txt pipelines sample code

### ISSUE THREAD

**Issue by hjred** [dotnet/docs#23081]
Hello there,

the last code sample (or otherwise the runtime library) seems to contain a bug.
The code sample always runs into the InvalidDataException "Incomplete message." branch with Net 5.0 and System.IO.Pipelines 5.0.1.

TryParseMessage, or more precisely the Encoding.ASCII.GetString call does not slice the given Sequence. This leads to reader.AdvanceTo call not advancing at all. The readBuffer gets bigger and bigger with each loop, but a message is never sucessfully read, because the buffer never advances.

Encoding.ASCII.GetString does not state in its documentation, that the given Sequence is advanced or sliced. This seems to be a problem in the sample then.

Replacing the TryParseMessage method with the following one will run without generating the InvalidDataException:

    static bool TryParseMessage(ref ReadOnlySequence<byte> buffer, out string message)
    {
        bool success = (message = Encoding.ASCII.GetString(buffer)) is not null;

        if (success)
        {
            buffer = buffer.Slice(buffer.Length);
        }

        return success;
    }

Maybe not the prettiest solution, but it works :)

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5384a7-5e96-d977-7748-317a2c758f63
* Version Independent ID: 06e72212-a052-a351-0e0b-1b002ce214de
* Content: [I/O pipelines - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines)
* Content Source: [docs/standard/io/pipelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/pipelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@hjred I cannot reproduce the problem. It works fine.

**Comment by hjred** [comment]
Some additional info:

I am using a lorem-ipsum.txt with 1001 lines in it (the same text repeated over and over again until 1.001 lines are used.

When using the original code from the docs and running the executable via Visual Studio (with and without debugging) or cmd.exe the following happens:
1. The content of the file is printed over and over. When redirecting the output to a text file this file has more than 10.000 lines in it.
2. The last lines of the output are:

    `percipitur in. Sint eros scripta eum ea, usu at decore aperiam eleifend. Vel iriure consectetuer ut, ridens percipit
    ex qui, no utinam epicurei duo. Quo omnes numquam sententiae cu.System.IO.InvalidDataException: Incomplete message.
    at Program.ProcessMessagesAsync(PipeReader reader, PipeWriter writer) in C:\Users\hajo1\source\repos\PipelinesTest\PipelinesTest\Program.cs:line 79`
3. It is completely irrelevant if a Release or Debug build is used
4. If a Debug build is used, the Visual Studio Debugger does not catch the exception
5. Interestingly, when I use the git bash console and run the same executable, only 55 out of the 1.001 lines are displayed without any exception and it is irrelevant if the fix is applied or not

**Comment by hjred** [comment]
I tested again using only a single repetition and the original code. The exception and the duplication of the output are still happening.

See attached output.txt
[output.txt](https://github.com/dotnet/docs/files/6429415/output.txt)

I am still wondering where the three question marks are coming from ...

**Comment by Rick-Anderson** [comment]
No repo with 5K lines.

**Comment by hjred** [comment]
This is the full solution + project. Maybe you can try to repo with this
[PipelinesTest.zip](https://github.com/dotnet/docs/files/6436871/PipelinesTest.zip)

**Comment by Rick-Anderson** [comment]
@hjred  that runs with no errors

**Comment by hjred** [comment]
Hmm,  strange. So it then seems to only throw an exception that is not reported back to main ... For now I am out of ideas.

**Comment by Rick-Anderson** [comment]
Try it with .NET 6

**Comment by hjred** [comment]
Maybe when it is released. Because of external tooling for a third-party project I am forced to non-preview versions only.

**Comment by Rick-Anderson** [comment]
Do you see that problem on more than one machine? Why don't you test on windows sandbox?

**Comment by hjred** [comment]
So you mean repo on another machine or the tooling/third-party project on something like VirtualBox? I don't have access to another Windows machine, so could only test on this machine, apart from using a virtual machine

**Comment by Rick-Anderson** [comment]
Just run it on windows sandbox on your machine, that's a new/clean machine

**Comment by hjred** [comment]
Ok, activated Windows Sandbox, installed the .NET Desktop Runtime 5.0.5 inside the sandbox, executed the pre-build app from the host and got the same exception including duplicated output again.
Build the executable inside the sandbox by installing NET 5.0 SDK and executed -> same error with duplication.
Removed NET 5.0 completely, installed NET 6.0 SDK, changed project to net6.0, build again, still the same error and duplication of output.

**Comment by Rick-Anderson** [comment]
> executed the pre-build app from the host
What's that? Does the program you suppled work?

**Comment by hjred** [comment]
I tried the Pipeline Test code in the Sandbox
