### ISSUE TITLE
Out of date description of partial method requirements.

### ISSUE THREAD

**Issue by geeknoid** [dotnet/docs#23083]
C# 9.0 changed the semantics of partial methods, this page needs to be updated accordingly. New semantics: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/extending-partial-methods.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4eedbc9-36be-6c79-fcb4-d5fe6998e5b1
* Version Independent ID: 85bf7eb0-b476-94b6-e10a-d0f42fee407b
* Content: [partial method - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-method)
* Content Source: [docs/csharp/language-reference/keywords/partial-method.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/partial-method.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @geeknoid 

I've added it to our backlog to address.

**Comment by BillWagner** [comment]
This was fixed in #23435
