### ISSUE TITLE
Last example creates intermediate strings and should not be considered a good practice

### ISSUE THREAD

**Issue by i2van** [dotnet/docs#23105]
Last example creates intermediate strings and **should not** be considered a good practice. Code from article:

```csharp
string[] words = { "The", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog." };

var phrase = words.Aggregate((partialPhrase, word) =>$"{partialPhrase} {word}");
System.Console.WriteLine(phrase);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a5e33e-938d-b72d-b211-ab5245413af5
* Version Independent ID: db96afbb-50af-5dee-b7b3-97600161e737
* Content: [How to concatenate multiple strings (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings)
* Content Source: [docs/csharp/how-to/concatenate-multiple-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/concatenate-multiple-strings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
You are correct @i2van for hot paths, this technique does cause additional allocations.

In many scenarios, the perf hit is small, and the simplicity is worth the perf cost. 

We'll update this article to be more clear about the costs.

**Comment by i2van** [comment]
Could you pleas also add `string.Join` example as an alternative?
