### ISSUE TITLE
Clarify that "Deserialize Dictionary with non-string key" is not fully supported

### ISSUE THREAD

**Issue by craigbrown** [dotnet/docs#23108]
This page has:
- a subsection titled "Dictionary with non-string key", which says: 
>Both `Newtonsoft.Json` and `System.Text.Json` support collections of type `Dictionary<TKey, TValue>`.

- an entry in the table of differences which says that "Deserialize Dictionary with non-string key" is "supported" by System.Text.Json.

However, from what I understand, this is [only the case for primitive types](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-5-0#supported-key-types). If you use your own custom class as a dictionary key, a `System.NotSupportedException` will be thrown when you try to serialize it. This doesn't happen with Newtonsoft.Json. 

It would be good if this page could be clarified to make clear that this is the case. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#dictionary-with-non-string-key)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@craigbrown Thanks for reporting that - I'm fixing it.
