### ISSUE TITLE
Default branch will be renamed to main

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#23119]
On March 5th, 2021, we're going to rename the default branch in this repository to main. For more details, see [dotnet's earlier announcement](https://github.com/dotnet/announcements/issues/172).

**Comment by Youssef1313** [comment]
Note: the tool that pushes automated PRs for merging to live may need updates.

**Comment by gewarren** [comment]
The branch renaming is complete.

If you have a fork and/or local clone, here are the steps you need to take:

1. Navigate to your fork on GitHub, go to the Settings tab, then the Branches tab, and then under Default branch, click the pencil icon to rename the default branch to main.
2. If you have a local clone, run the following commands in Git Bash:

   ```
   git branch -m master main
   git fetch origin
   git branch -u origin/main main
   ```
