### ISSUE TITLE
Cannot use local gpu environment for old preview model builder image classification

### ISSUE THREAD

**Issue by philipbawn** [dotnet/docs#23111]
I have model builder 16.3.0.2056001 and ml.net model builder gpu support version 16.3.0.2056001, I installed cuda_10.0.130_411.31_win10.exe from nvidia and extracted cudnn64_7.dll from cudnn-10.0-windows10-x64-v7.6.4.38.zip from nvidia, placing it in C:\program files\nvidia gpu computing toolkit\cuda\v10.0\bin\ - yet my visual studio looks like this when I try to progress adding image classification to a project.
![image](https://user-images.githubusercontent.com/10352261/110003857-a9912880-7ccb-11eb-8896-53ad9c974b02.png)

The model builder would let me proceed with cpu only:
![image](https://user-images.githubusercontent.com/10352261/110003928-bca3f880-7ccb-11eb-8871-579f68c6a17e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @philipbawn 

Sorry to hear you ran into this issue. Since this is more of a product question instead of docs, I've opened an issue in the Model Builder repo. Please follow the discussion on there.

dotnet/machinelearning-modelbuilder#1308

Closing this issue for now.
