### ISSUE TITLE
https://www.github.com/travis-ci/travis.rb/tree/7e5e09f0ad82fb50a87da3517f9244740f117c78/lib%2Ftravis%2Ftools%2Fgithub.rb

### ISSUE THREAD

**Issue by codi0987** [dotnet/docs#23113]

**Comment by IEvangelist** [comment]
Hi @codi0987 - I see that you're creating some issues, however; I can't help but to assume that you're doing so in error. Are these intentional?

I closed #23115 and #23114, and was tempted to close this - but I figured I'd ask. Do you need help with something?

**Comment by BenjaminMichaelis** [comment]
Looks like spam of some sort and worthwhile closing. They have another false one in [grpc #698](https://github.com/grpc/grpc.io/issues/698) and also have already gotten an issue labeled by @BillWagner for [code-of-conduct](https://github.com/dotnet/docs/labels/code-of-conduct) on #22953
