### ISSUE TITLE
Interface for Hash​Algorithm

### ISSUE THREAD

**Issue by polewskm** [dotnet/docs#2311]
The documentation of `Hash​Algorithm` in the following target frameworks incorrectly mentions that it has an base interface of `ICryptoTransform` when this is not true:

* [netstandard-1.6]
* [netstandard-1.4]
* [netstandard-1.3]
* [netcore-1.1]
* [netcore-1.0]

If you browse the source for [HashAlgorithm.cs] you can find that the interface `ICryptoTransform` is only added for __.NET Standard 2.0__

I would attempt a PR to fix the documentation mistake but I do not know how to show different base interfaces for the combination of target frameworks.

[netstandard-1.6]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm?view=netstandard-1.6
[netstandard-1.4]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm?view=netstandard-1.4
[netstandard-1.3]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm?view=netstandard-1.3
[netcore-1.1]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm?view=netcore-1.1
[netcore-1.0]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm?view=netcore-1.0
[HashAlgorithm.cs]: https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @polewskm. The list of implemented interfaces is auto-generated using reflection. However, currently it does not take into account platform or version differences in interface implementation. We've opened an internal bug, #996154, to address this issue.

**Comment by mairaw** [comment]
@rpetrusha the internal bug referred here was about the list of interfaces not being complete, but I didn't see information about per version in that same bug. Perhaps you opened a different bug for this?

@dend are you aware of any bugs tracking this request?

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/222
