### ISSUE TITLE
Comprehensive list of warnings which can be suppressed by System.Diagnostics.CodeAnalysis.SuppressMessageAttribute

### ISSUE THREAD

**Issue by neeraj9** [dotnet/docs#23128]
I am not sure if this page is comprehensive and covers all the warnings which System.Diagnostics.CodeAnalysis.SuppressMessageAttribute can suppress. In addition, it will be great to cross reference to the source code which eventually checks for these errors and suppresses them. Connecting those dots will help anyone who is new to this can understand both the suppressions possible and look underneath and appreciate the implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04bb9351-ef8d-48a7-7fb7-6ff287c0340b
* Version Independent ID: 8ed5686f-1164-2d87-72f1-e9c8420dcf94
* Content: [Code quality rules overview - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/index.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by Youssef1313** [comment]
As far as I know, this applies to all diagnostics except compiler ones. You can write your own analyzer and be able to suppress it this way. You were probably confused by the wording in [API remarks](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute?view=net-5.0#remarks)?
