### ISSUE TITLE
Error of "The Common Language Infrastructure" href

### ISSUE THREAD

**Issue by a5932016** [dotnet/docs#23125]
In the page https://docs.microsoft.com/en-us/dotnet/standard/components.
I found that the URL of "The Common Language Infrastructure" on this page is wrong, and the URL has an extra h.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba03a7c-8cbe-7670-c2e9-9b692556361c
* Version Independent ID: d085d268-bff6-f355-80b4-01c1023a5914
* Content: [.NET architectural components](https://docs.microsoft.com/en-us/dotnet/standard/components)
* Content Source: [docs/standard/components.md](https://github.com/dotnet/docs/blob/master/docs/standard/components.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by sunilvijendra** [comment]
It is a small typo in the URL. Is this issue open?

**Comment by tdykstra** [comment]
> Is this issue open for me take up?

Yes

**Comment by sunilvijendra** [comment]
This PR - https://github.com/dotnet/docs/pull/23241 has fixed the URL issue. This can be closed!
