### ISSUE TITLE
Formatting is broken by the dollar sign in brackets.

### ISSUE THREAD

**Issue by simon-biber** [dotnet/docs#23131]
Where the markdown file says ```use an anchor ("$"): "[a-z]+\\.contoso\\.com$". ```

The rendering on docs.microsoft.com is broken:

![image](https://user-images.githubusercontent.com/6026882/110083383-8acf8680-7dde-11eb-90e1-e014b6676245.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6578b3-bbe7-91cd-942c-4383d9c89045
* Version Independent ID: 51b0a006-5125-31f8-0eaa-0ea7e96cf678
* Content: [&lt;bypasslist&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/bypasslist-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/bypasslist-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/bypasslist-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Youssef1313** [comment]
Thanks for reporting. I opened #23133 to address this.

I don't know why it renders this way, but put it in codefence to make sure it renders correctly.

**Comment by adegeo** [comment]
We discovered this was from the $ in the text. The site renderer is trying to transform that into mathematical equations.
