### ISSUE TITLE
Can it be used in query expression?

### ISSUE THREAD

**Issue by Merven96** [dotnet/docs#23134]
[Enter feedback here]
The title of this page(https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries) is ''_**add custom methods for LINQ queries**_''.
But in the examples, all custom methods can only be used by the normal way of function calling.
I want my methods for LINQ queries can be used in query expression. 
Is this currently supported? 
For example:    
(support I have already defined the extending function :
**public static T RandomElement<T>(this IEnumerable<T> source, Random random);**    )
Random rand = new Random();
var query = from elem in numbers randomChoose rand select elem;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9dc3a1f-945b-18b4-d962-467f7ca49d95
* Version Independent ID: 5cf4ba6d-9afc-77bd-0a70-4ffd8e9526c0
* Content: [How to add custom methods for LINQ queries (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Merven96 

Good question. In general, methods calls cannot be used in `IQueryable` based queries. The query provider provider would need to understand the semantics of the method and translate that method call into those semantics. For example, Entity Framework does understand the semantics of some string methods and can replace those method calls with the equivalent SQL comparisons.

I'll close this as an answered question.

**Comment by zspitz** [comment]
Related #13323.
