### ISSUE TITLE
[2.0] Missing coverage for "dotnet new --install"?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/docs#2315]
i cant seem to find the doco for `dotnet new --install` here https://docs.microsoft.com/en-nz/dotnet/core/tools/dotnet-new

**Comment by GuardRex** [comment]
IIRC It's an "undocumented feature" being previewed until 2.0. If that's correct, it will become part of the docs when 2.0 ships.

cc/ @mlorbetske (will know if I'm lying :grinning:)

**Comment by SimonCropp** [comment]
@GuardRex that may be the case. but you are making all your early adopters suffer by hiding such fundamental features. I would much prefer it was documented and marked as "preview" in the doco

**Comment by mlorbetske** [comment]
@GuardRex is correct. For 2.0, install, uninstall, etc are becoming part of the normal feature set. Previously we considered them to be "experimental" and incomplete (having to reset the whole instance to remove a template for instance). Now that the story is a bit better (no more ::* to install the latest version of a package, uninstall is a thing), we'll document install.

/cc @sayedihashimi

**Comment by sayedihashimi** [comment]
+1 to what @mlorbetske said

**Comment by GuardRex** [comment]
@sayedihashimi Is [How to create your own templates for dotnet new](https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/) still (mostly) valid? That's probably the best "documentation" we have at the moment.

**Comment by sayedihashimi** [comment]
@GuardRex yes.

@mairaw can we get a walkthru type of doc for How to create templates based on my [blog post](https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/)?

**Comment by mairaw** [comment]
The issue described here would be covered by the work being done for #2139. correct @GuardRex?

@sayedihashimi yes, we can. I'll open a new issue to track that work separately.

**Comment by GuardRex** [comment]
@mairaw It *should be* ... I'll **WIP** that PR right now so I can get this on there.

**Comment by GuardRex** [comment]
Is this the issue? ... We can track on this one if that's ok with you.

**Comment by GuardRex** [comment]
@mairaw Do you want this in the *core/tools* area or in the *core/tutorials* area?

Title: *Create your own templates for dotnet new*

**Comment by GuardRex** [comment]
Closing here and tracking updates for `dotnet new` on https://github.com/dotnet/docs/issues/2139.

We'll be tracking the new topic for templating on https://github.com/dotnet/docs/issues/2405.

Thanks again @SimonCropp!
