### ISSUE TITLE
Updated guidance

### ISSUE THREAD

**Issue by sathiathirumal** [dotnet/docs#23186]
Is there a more updated guidance for 2021? Specifically, is ACI recommended for any app model at all, or is it better to just go with AKS (our app model is more N-Tier app / microservices architecture)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45be6d71-575d-5d8d-bcdc-b6885ddbb487
* Version Independent ID: 7c37b77a-63fc-4fb4-ae32-02ac9c09e1c8
* Content: [Choosing Azure compute platforms for container-based applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/choosing-azure-compute-options-for-container-based-applications.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @sathiathirumal , thank you for your feedback. 

We had an internal discussion on this topic and could find that the content mention in the table seems to be right. 
But yes, it will be useful if there is more information in terms of choosing different services. And for that reason, we have included the link of [Choose an Azure compute service for your application](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree) in the additional resource section.  It will be helpful for you to decide on the right choice of Azure Compute service based on your requirement. 

Hope this helps !
