### ISSUE TITLE
vieclamphothongvietnam.net

### ISSUE THREAD

**Issue by vieclamphothongvietnam** [dotnet/docs#23198]
Tập Đoàn Điện Tử Bắc Ninh Bắc Giang Tuyển Dụng

> ![IMG_20210303_092049](https://user-images.githubusercontent.com/77167260/110215337-d3b93500-7edb-11eb-8f74-54f8ed7ddaa9.jpg)

[Việc Làm Bắc Ninh Bắc Giang](https://vieclamvietnammb.blogspot.com/2020/07/cong-ty-tnhh-bujeon-bac-ninh-tuyen-gap.html?m=1) **Help us make content visible**

**Describe the new article**

**Comment by vieclamphothongvietnam** [comment]
> Tập Đoàn Điện Tử Bắc Ninh Bắc Giang Tuyển Dụng
> 
> > ![IMG_20210303_092049](https://user-images.githubusercontent.com/77167260/110215337-d3b93500-7edb-11eb-8f74-54f8ed7ddaa9.jpg)
> 
> [Việc Làm Bắc Ninh Bắc Giang ](https://vieclamvietnammb.blogspot.com/2020/07/cong-ty-tnhh-bujeon-bac-ninh-tuyen-gap.html?m=1) **Giúp chúng tôi hiển thị nội dung**
> 
> **Mô tả bài viết mới**

Tập Đoàn Điện Tử Bắc Ninh Bắc Giang

**Comment by BenjaminMichaelis** [comment]
Spam, also in other repos like [here](https://github.com/semver/semver/issues/677), [here](https://github.com/jlord/sheetsee/issues/35), [here](https://github.com/hubwriter/open-reusables/pull/47), and [here](https://github.com/w3c/wai-policies-prototype/pull/398)

**Comment by BillWagner** [comment]
Closing as a code of conduct violation.
