### ISSUE TITLE
Link to spec is broken

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/docs#23190]
This link is broken: [C# Language Specification](https://docs.microsoft.com/en-us/_csharplang/spec/introduction.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@konrad-jamrozik Can you please check if it's now fixed? The link in the article now works for me. This could have something to do with the recent movement from master to main.

**Comment by BenjaminMichaelis** [comment]
Is this from the [docs site](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/) or from the [index md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/index.md) in this repo that you are finding this issue? Just to clarify, as for the docs site, it seems to be currently be working for myself.

**Comment by Youssef1313** [comment]
@BenjaminMichaelis Yep the site was fixed in https://github.com/dotnet/docs/pull/23194

**Comment by BillWagner** [comment]
Closing as fixed in #23194
