### ISSUE TITLE
Typo under "Tutorial: Create a .NET console application using Visual Studio" page

### ISSUE THREAD

**Issue by 21sparker** [dotnet/docs#23199]
Step 6 of the section "Create the app" has a small typo. Currently it says:

"6. In the Configure your new project dialog, enter HelloWorld in the Project name box. Then choose Create."

It should however say:

"6. In the Configure your new project dialog, enter HelloWorld in the Project name box. Then choose _Next_."

Next is the name of the button the user should click on that Dialog, as indicated by the accompanying screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Good catch @21sparker!
I opened #23200 to fix this.
