### ISSUE TITLE
Define "stacked usings"

### ISSUE THREAD

**Issue by JakubFojtik** [dotnet/docs#23202]
What exactly does *stacking* mean? I see 2 possibilities:

1. Constructing multiple objects and calling await afterwards
2. Mixing the implicit and explicit forms of the using statement

Alternatively, how acceptable would the following example be? It differs from the *nested* example by constructing objTwo before the awaits:

	using System;
	using System.Threading.Tasks;

	class ExampleOneProgram
	{
		static async Task Main()
		{
			var objOne = new ExampleAsyncDisposable();
			// Exception thrown on .ctor
			var objTwo = new ExampleAsyncDisposable();
			
			await using (objOne.ConfigureAwait(false))
			{
				// Interact with the objOne instance.

				await using (objTwo.ConfigureAwait(false))
				{
					// Interact with the objOne and/or objTwo instance(s).
				}
			}

			Console.ReadLine();
		}
	}

I believe that **2** is the correct answer, but I still don't see how and why would the implicit using's Dispose call be skipped when the *nesting* case manages to call the explicit one's properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @JakubFojtik
Thank you so much for posting this issue. We really appreciate it.

Stacking means having `await using` statements that are stacked like this:

```csharp
static async Task Main()
{
    var objOne = new ExampleAsyncDisposable();
    // Exception thrown on .ctor
    var objTwo = new AnotherAsyncDisposable();

    await using (objOne.ConfigureAwait(false)) // this is stacked atop, objTwo
    await using (objTwo.ConfigureAwait(false)) // this is at the bottom of the stack of two
    {
        // Only objOne has its DisposeAsync called.
    }

    Console.ReadLine();
}
```

In your case:
```csharp
var objOne = new ExampleAsyncDisposable();

// Exception thrown on .ctor
var objTwo = new ExampleAsyncDisposable();

await using (objOne.ConfigureAwait(false))
{
	// Interact with the objOne instance.
	await using (objTwo.ConfigureAwait(false))
	{
		// Interact with the objOne and/or objTwo instance(s).
	}
}
```

As soon as the call to `var objTwo = new ExampleAsyncDisposable();` is made an exception is thrown, the rest of the code doesn't even come into question at the point. I'm going to update this doc a bit to clarify where specifically "stacking" occurs.
