### ISSUE TITLE
Jitter recommendation is wrong

### ISSUE THREAD

**Issue by sander1095** [dotnet/docs#23225]
Hello.

The page recommends a jitter strategy and has a link to https://github.com/App-vNext/Polly/wiki/Retry-with-jitter for more information. The page contains the same example code as the docs, BUT at the bottom of the page it says the following:

> For production usage, we recommend one of the jitter algorithms offered in Polly.Contrib.WaitAndRetry.
> The Polly team originally recommended a widely-referenced jitter strategy described here. However, analysis of this strategy by community members suggested this strategy still exhibits elements of peaks/bunching (see fifth graph from top in that link), especially at the first retry.
> We now recommend a new strategy delivered in Polly.Contrib.WaitAndRetry. This provides an overall smoother distribution of jittered retry timings, as shown in the third-from-bottom graph in this link.
> For configuration, usage and deeper info, see Polly.Contrib.WaitAndRetry.

That is why I believe that the docs should be updated to recommend the library instead of the custom code microsoft provides. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f5aecf-ef1c-5a61-de24-894f4f9032c3
* Version Independent ID: 95c81932-26fd-4a24-3b6f-8dd5bde20026
* Content: [Implement HTTP call retries with exponential backoff with Polly](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @sander1095 , thank you for your valuable feedback 👍 

We have updated the doc with recommended Jitter Strategy as mentioned in [here](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter#more-complex-jitter)
