### ISSUE TITLE
Link Roslyn's breaking-changes document

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23223]
Consider adding a link for this document in <https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/breaking-changes.md>.

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn/pull/51070#discussion_r572306994_

**Comment by Youssef1313** [comment]
FYI @cston

**Comment by BillWagner** [comment]
@Youssef1313 Do you want to make the PR for this?  If not, I'll address it this afternoon.

**Comment by Youssef1313** [comment]
Sure. Opened #23230
