### ISSUE TITLE
CA1416 with WinUI 3 projects and multi-targeting

### ISSUE THREAD

**Issue by curia-damiano** [dotnet/docs#23226]
Hi,
I am porting an app from UWP to .NET 5 with WinUI 3.

Since Visual Studio 2019 16.9 (and also in 16.10 Preview 1) I get multiple warnings of this type:
warning CA1416: This call site is reachable on all platforms. 'XXX' is only supported on: 'Windows' 10.0.10240.0 and later.

The point is that I am compiling in multi-target for 
<TargetFrameworks>uap10.0.16299;net5.0-windows10.0.19041.0</TargetFrameworks>

So my app is not mean to be cross platform, and as I am already targeting Windows only, I think that this warning is not necessary.

Btw you can reach me to "damiano dot curia at microsoft dot com" in case you want to give a look at the project I am working on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8fbd7e-af44-859a-3967-b61bed6919a0
* Version Independent ID: e4517175-91cf-0fcd-d438-23e652f5022c
* Content: [CA1416: Validate platform compatibility (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1416.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1416.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @buyaa-n
* Microsoft Alias: **bunamnan**

**Comment by buyaa-n** [comment]
> The point is that I am compiling in multi-target for
uap10.0.16299;net5.0-windows10.0.19041.0

I think the warning is produced from `uap10.0.16299` target, not from `net5.0-windows10.0.19041.0`. 

In general, MSBuild supposed to evaluate the TFM and inject the required attributes to the project's AssemblyInfo.cs, i know that is working as expected for windows targets (in this case would add `[SupportedOSPlatform("windows10.0.19041.0")]` assembly attribute), not sure if it is doing the same for  `uap10.0.16299`, could you check the AssemblyInfo.cs generated for that target?

**Comment by curia-damiano** [comment]
Hi Jeff,
Thank you very much for your help.
As I am porting a big UWP app, I'm converting module by module and so I have disabled the automatic generation of AssemblyInfo.cs to preserve the existing ones, as the contain some custom attribute.

I have added to every existing AssemblyInfo.cs file the following:
#if WinUI
[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows10.0.19041.0")]
#endif

and it works!
Thank you very much for your quick help, I close the issue because it is solved now.

**Comment by jeffhandley** [comment]
Thanks for letting us know, @curia-damiano. Thanks for fielding this, @buyaa-n.
