### ISSUE TITLE
Unclear when telemetry opt out environment variable needs to be set

### ISSUE THREAD

**Issue by MikeCJohnsonUk** [dotnet/docs#23237]
The page describes the ability to opt out of telemetry by setting an environment variable but does not make clear when that variable needs to be set beyond the installation of the SDK. 
Does it need to be set prior to using the SDK?
Does it need to be set prior to running any app built with the SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c136055b-bb04-17b6-19b2-42d4610c1a70
* Version Independent ID: 50433ae5-4687-fe5f-75ab-a47e1a706777
* Content: [.NET SDK telemetry - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry)
* Content Source: [docs/core/tools/telemetry.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/telemetry.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@wli3 please confirm if these answers are correct:

> Does it need to be set prior to using the SDK?

The environment variable can be set at any time after SDK installation to stop telemetry from that point forward.

>Does it need to be set prior to running any app built with the SDK?

Apps built with the SDK don't send telemetry data. The only way running an app results in telemetry data being sent is when the command `dotnet run` is used.

**Comment by wli3** [comment]
There is telemetry sending during the installation. You need to set it before the installation to stop all telemetry.

**Comment by tdykstra** [comment]
>There is telemetry sending during the installation. You need to set it before the installation to stop all telemetry.

@MikeCJohnsonUk does that answer your question?

**Comment by MikeCJohnsonUk** [comment]
Thank you, yes that does answer my questions as to whether the telemetry was active 
a) for SDK installation
b) for build time use of the SDK
c) for applications built using of the SDK at application run-time

**Comment by tdykstra** [comment]
Questions answered, so I'm closing this issue.  Feel free to reopen if needed.
