### ISSUE TITLE
Page title, nav link don't match

### ISSUE THREAD

**Issue by mrmsbarnes** [dotnet/docs#23267]
This page
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/
has the title 
Classes and structs (C# programming guide)
but it is reach by the overview link for
Classes, Records, and Structs
I think the page title is wrong.  It should include 'Records'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac008aee-60cb-8c9f-ae74-a5c7126d0a82
* Version Independent ID: ed517628-4b5d-c881-84fa-b6fa25ca1e01
* Content: [Classes and Structs - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @mrmsbarnes 

We'll continue to update the guide as we add more information on new features.
