### ISSUE TITLE
Example contradicts the guidelines themselves in the guidelines page...

### ISSUE THREAD

**Issue by Carmageddon** [dotnet/docs#23282]
Guidelines correctly show when to use implicit:
`int var3 = Convert.ToInt32(Console.ReadLine());`

Then another example about operators ignores the very guidelines being preached:
`var dividend = Convert.ToInt32(Console.ReadLine());`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for submitting this @Carmageddon 

I've added it to our backlog to address when we next update this article.
