### ISSUE TITLE
[Issue Transfer] Using AzureServiceTokenProvider to authenticate with the Azure Libraries for .NET

### ISSUE THREAD

**Issue by jsquire** [dotnet/docs#23287]
Transferring issue from the Azure SDK Docs repository ([#961](https://github.com/Azure/azure-docs-sdk-dotnet/issues/961)),  as the source file has moved into this repository.  Please be aware that there is some additional discussion on the original issue that may prove useful.  

---
# Please be aware that @kamiyn is the author of original issue and should be mentioned on responses or inquiries.
---
I tried AzureServiceTokenProvider described in
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication
to authenticate with the Azure Libraries for .NET
and it works as shown below.

If this approach is appropriate, please add it at https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate.

```cs
var tenantId = "tenantId (or directory Id) of your Azure Active Directory";
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var token = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com", tenantId);
var tokenCredentials = new TokenCredentials(token);
var azure = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(new AzureCredentials(
        tokenCredentials,
        tokenCredentials,
        tenantId,
        AzureEnvironment.AzureGlobalCloud))
    .WithDefaultSubscription();
```

* Content: [Authenticate with the Azure libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet)
* Content Source: [https://github.com/dotnet/docs/blob/main/docs/azure/authentication.md](https://github.com/dotnet/docs/blob/main/docs/azure/authentication.md)

The referenced URL redirects to the following page:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c94623-dc72-785f-681f-90833548a2bd
* Version Independent ID: 063b6a7f-80f0-d6cf-9a64-b1a75a2ba0ce
* Content: [Understanding Authentication in the Azure libraries for .NET](https://docs.microsoft.com/en-us/dotnet/azure/authentication)
* Content Source: [docs/azure/authentication.md](https://github.com/dotnet/docs/blob/main/docs/azure/authentication.md)
* Product: **dotnet-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Transferring comment from the original issue.

---
## Please be aware that @AtOMiCNebula is the author of this comment and should be mentioned on responses or inquiries.
---

One suggestion for the code snippet: I think `AzureCredentials` needs two different tokens, not the same token twice.  One is a token for the `https://management.azure.com/` resource, and the other should be for `https://graph.windows.net/`.  I suspect that if the solution above works well for you, it's just not trying to use "both".

```csharp
string tenantId = "...";
AzureServiceTokenProvider tokenProvider = new AzureServiceTokenProvider();
IResourceManager resourceManager = ResourceManager
    .Authenticate(new AzureCredentials(
        new TokenCredentials(tokenProvider.GetAccessTokenAsync("https://management.azure.com/").Result),
        new TokenCredentials(tokenProvider.GetAccessTokenAsync("https://graph.windows.net/").Result),
        tenantId,
        AzureEnvironment.AzureGlobalCloud))
    .WithDefaultSubscription();
```

**Comment by CamSoper** [comment]
@alexwolfmsft is this still relevant? Otherwise we should close it.

**Comment by jsquire** [comment]
@CamSoper:  The AppAuthentication library and Fluent Management libraries have both reached end-of-life and are no longer supported or maintained.   I think this content is stale at this point and no longer desirable.

**Comment by scottaddie** [comment]
Closing for the reasons Jesse mentioned above. Customers should be using the Azure.Identity package for their Entra ID authN needs.
