### ISSUE TITLE
The link https://aka.ms/perfcollect is broken

### ISSUE THREAD

**Issue by chickenSandwich** [dotnet/docs#23296]
When the link (https://aka.ms/perfcollect) resolves it would appear that it is referring to the branch master, which does not exist anymore.  The new link should resolve to:
[https://raw.githubusercontent.com/microsoft/perfview/main/src/perfcollect/perfcollect](https://raw.githubusercontent.com/microsoft/perfview/main/src/perfcollect/perfcollect)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd230f8-907f-5f07-e3ab-7ad37fee3aa4
* Version Independent ID: ac6cc555-a033-766d-0597-bd9bda98820f
* Content: [Tracing .NET applications with PerfCollect.](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/trace-perfcollect-lttng)
* Content Source: [docs/core/diagnostics/trace-perfcollect-lttng.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/trace-perfcollect-lttng.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sywhang
* Microsoft Alias: **suwhang**

**Comment by Youssef1313** [comment]
Both links work for me

**Comment by chickenSandwich** [comment]
You are correct.  Perhaps it had to do with the incidents which were occurring yesterday with Github (https://www.githubstatus.com/history) .  I must have misinterpreted what was happening.  Thank-you @Youssef1313 .

**Comment by Youssef1313** [comment]
@gewarren While both links work, you may want to consider updating the link internally to main.

**Comment by gewarren** [comment]
I'm not seeing that link in the aka.ms tool, probably because I don't have permissions to change it. @sywhang Can you update the target URL to point to main?

**Comment by sywhang** [comment]
Unfortunately I'm not the owner of that link either (it's been there before I joined Microsoft). Let me try to find out who owns this link.

**Comment by sywhang** [comment]
The link should be fixed now.
