### ISSUE TITLE
console-teleprompt "sampleQuotes.txt" link "Page not found".

### ISSUE THREAD

**Issue by Liamdoult** [dotnet/docs#23291]
When attempting to access the "sampleQuotes.txt" file I get a 404 not found error. 

Assumed cause: Rename in branch from master -> main and GitHub not correctly redirecting for the *raw* file:

Current link in the doc:
https://github.com/dotnet/samples/raw/master/csharp/getting-started/console-teleprompter/sampleQuotes.txt

Updated branch path to the file:
https://github.com/dotnet/samples/raw/main/csharp/getting-started/console-teleprompter/sampleQuotes.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a28322-944d-73c3-177c-d9bec577c08b
* Version Independent ID: 15ce52df-1eb1-7743-8440-dbef3169487c
* Content: [Console Application](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-teleprompter)
* Content Source: [docs/csharp/tutorials/console-teleprompter.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/console-teleprompter.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out and submitting the fix @Liamdoult 

I'll review the PR shortly.
