### ISSUE TITLE
[system-text-json-converters-how-to.md] Sample code won't compile

### ISSUE THREAD

**Issue by albigi** [dotnet/docs#23290]
The following code provided as an example won't compile:

```
public class ObjectToInferredTypesConverter : JsonConverter<object>
    {
        public override object Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options) => reader.TokenType switch
            {
                JsonTokenType.True => true,
                JsonTokenType.False => false,
                JsonTokenType.Number when reader.TryGetInt64(out long l) => l,
                JsonTokenType.Number => reader.GetDouble(),
                JsonTokenType.String when reader.TryGetDateTime(out DateTime datetime) => datetime,
                JsonTokenType.String => reader.GetString(),
                _ => JsonDocument.ParseValue(ref reader).RootElement.Clone()
            };

        public override void Write(
            Utf8JsonWriter writer,
            object objectToWrite,
            JsonSerializerOptions options) =>
            JsonSerializer.Serialize(writer, objectToWrite, objectToWrite.GetType(), options);
    }
```

The above produces an error on the **switch** statement:
_Cannot find best common type for types {bool,DateTime,double,JsonElement,long,string?}_

The compiler error makes perfect sense to me and I believe an explicit cast should be set in the switch expression:

```
public override object Read(
			ref Utf8JsonReader reader,
			Type typeToConvert,
			JsonSerializerOptions options) => reader.TokenType switch
		{
			JsonTokenType.True => true as object,
			JsonTokenType.False => false as object,
			JsonTokenType.Number when reader.TryGetInt64(out long l) => l as object,
			JsonTokenType.Number => reader.GetDouble() as object,
			JsonTokenType.String when reader.TryGetDateTime(out DateTime datetime) => datetime as object,
			JsonTokenType.String => reader.GetString(),
			_ => JsonDocument.ParseValue(ref reader).RootElement.Clone() as object
		} ?? throw new JsonException();
```

Is there a more appropriate way to implement this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
@albigi What version of the compiler are you using?

I tried a similar code (not the exact same code, but the same idea), and I don't get errors:

```csharp
using System;

public class ObjectToInferredTypesConverter
{
    public object Read(int x) => x switch
    {
        0 => true,
        1 => "",
        _ => new DateTime()
    };
}
```

Can you add `#error version` to the top of your code file and paste the error message you get?

**Comment by adegeo** [comment]
Hmm... This sounds like a runtime error, not a compile error? Compiles fine for me.

**Comment by albigi** [comment]
@Youssef1313  thanks for the input.
I realized I actually went straight to the problem without properly detailing the context and omit a very important detail, nullability. I didn't realize this difference initially and I believe this distinction is quite subtle.

The code in the example above compiles fine, but raises a nullability warning in a nullable-enabled context. Due to our currently code quality checks, this will result in a failure on the CI pipeline.

To assert a non-null type is returned, in the example above I decided to throw but you might well return default or whatever:
~~~
return x switch
{
	0 => true,
	1 => "",
	2 => null,
	_ => new DateTime()
}  ?? default;
~~~
In this case, the compiler produces the error I mentioned: _error CS8506: No best type was found for the switch expression._

The proper way I eventually ended up managing this is ensuring non-nullability for every single option which makes sense but IMO conflicts with the "elegance" and tidiness of the switch statement.

Is there any better way to do this?

Anyway, since there's nothing wrong with the code in the example, this issue can be closed but I believe a note would still be nice to have and may save some time since the compiler error is not super easy to understand in this case.

Thanks!

**Comment by Youssef1313** [comment]
> To assert a non-null type is returned, in the example above I decided to throw **but you might well return default** or whatever:

The method returns `object`, if you returned `default` it will be null. I'm not sure how you're working the nullability warning this way?

You may want to throw - probably won't have any warnings/errors. If it does have warnings/errors, it would be helpful that you post a minimal complete code.
