### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by cafenroy** [dotnet/docs#23297]
This is an article about a Serialization technique that does not include the equivalent Deserialization technique.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179cc49a-a37d-155e-5ecf-deca4f219a5a
* Version Independent ID: 17511810-6572-ad88-6eaf-4f9bded720b7
* Content: [How to serialize properties of derived classes with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism)
* Content Source: [docs/standard/serialization/system-text-json-polymorphism.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-polymorphism.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Deserialization is not supported. See the note at the end of the article --

> For more information about polymorphic serialization, and for information about deserialization, see [How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-core-3-1#polymorphic-deserialization)."

 The link goes to an article that explains that a custom converter is required.

**Comment by cafenroy** [comment]
> Deserialization is not supported.

I did not click on "How to migrate from Newton..." because I am not migrating from Newtonsoft.

An article about Serialization that does not include the Deserialization technique is useless for most cases. It is a very specific scenario. This should go in a "blue rectangle".

**Comment by tdykstra** [comment]
Good points - I'll put the note about deserialization in an alert box and will change the link text.
