### ISSUE TITLE
Update documentation for explaining the effect of the item being used in dependency injection

### ISSUE THREAD

**Issue by ASP-WAF** [dotnet/docs#23307]
[Enter feedback here]
It would be nice to have documentation of how ServiceCollection is managing implementations that use the async interface

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @ASP-WAF
Thank you so much for posting this issue. We really appreciate it.

The `IAsyncDisposable` interface is not related to dependency injection, so updating this article wouldn't really make sense. I'm curious though, however; what effects are you referring to specifically? Are you talking about [Dependency injection guidelines: Disposal of services](https://docs.microsoft.com/dotnet/core/extensions/dependency-injection-guidelines#disposal-of-services)?

**Comment by ASP-WAF** [comment]
That is exactly what I am referring to, can one use the IAsyncDispose is preferred over the IDispose, the IAsyncDispose pattern seems to suggest that it doesn't as one needs to add both...  Have a look at the [sample](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)

**Comment by davidfowl** [comment]
The default implementation handles both cases actually

**Comment by ASP-WAF** [comment]
fantastic, perhaps mention it in the documentation
