### ISSUE TITLE
Doesn't answer my question about how to create the necessary folders for Microsoft's secret management

### ISSUE THREAD

**Issue by andresd24** [dotnet/docs#23309]
This doesn't solve my issue.  I don't need to programmatically create a folder.   I need to know how through the MAC terminal I can create the necessary folders for Microsoft's secret management:

~/.aspnet/https
~/.microsoft/usersecrets/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0529c5f6-c0b2-caa3-7640-9c4dacc24f5c
* Version Independent ID: 0301c34f-7440-ee22-ac8f-020c466f1a5d
* Content: [How to create a file or folder - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-create-a-file-or-folder)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-create-a-file-or-folder.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/file-system/how-to-create-a-file-or-folder.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@andresd24 Thanks for asking that question.

You should create those folders manually. [This article](https://docs.microsoft.com/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows#enable-secret-storage) should have more details for how to manage user secrets.

I'll close this as an answered question. Let us know if we can help in the future.

**Comment by andresd24** [comment]
thanks @BillWagner for this piece of knowledge. I ended finding a way to create these folders manually in my macOS terminal and was able to complete the process.  But know I have a doubt.  Will the fact that I created them manually will expose me somehow or I shouldn't worry about how they were create? Thanks again for your help.
