### ISSUE TITLE
Abstraction and Encapsulation Confusion.

### ISSUE THREAD

**Issue by UnicornSheep** [dotnet/docs#23308]
The definitions of Abstraction and Encapsulation at the top of the article are switched at the bottom of the article (summary section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @UnicornSheep.  The summary should have been updated in #22888, but was missed. I opened #23315 to address this.
