### ISSUE TITLE
Please include C# version numbers for all the operators in the operators section

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#23301]
---
**Issue moved from MicrosoftDocs/feedback#3513**
- Please respond to @FaridAhamat.

---

_From @FaridAhamat on Wednesday, February 24, 2021 1:52:18 PM_

**Is your feature request related to a problem? Please describe.**
Sometimes old applications break because I used newer C# syntax out of habit. Would be useful to know which version an operator was introduced. As C# language evolves faster, I think it's useful to know in a glance which version was an operator introduced, rather than read through the lengthy C# changelog.

**Describe the solution you'd like**
Put the C# version it was introduced right after the header text.

Example, in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast , the explanation is that the "is" operator is introduced from C# 7.0, but it's better to put it on the header next to the text "is operator" to allow for quick glance.

**Describe alternatives you've considered**
No other idea.

**Additional context**

edit by @billwagner to add Document Details block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This hasn't had any discussion since 2021.

The compiler error messages have been enhanced to provide more guidance on versions. If you are targeting an older version of C#, the error message indicates what version is required for any feature you try to access. That seems a better solution that adding cross reference or version information to all the docs pages.

Closing as not planned.
