### ISSUE TITLE
How do I inject DI ServiceProvider services into these classes?

### ISSUE THREAD

**Issue by Vinigas** [dotnet/docs#23303]
How do I inject DI ServiceProvider services into these classes? These classes in the example are not constructed by the ServiceProvider, therefore I cannot inject DI services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Vinigas
Thank you so much for posting this issue. We really appreciate it.

Could you please tell me exactly what classes you're asking about? Some of the classes in the article are intentionally not related to DI. If you tell me which ones specifically, I could probably help.

**Comment by Vinigas** [comment]
Either `ColorConsoleLogger` or `ColorConsoleLoggerProvider`. The point is that I want to inject `IOptionsMonitor<ColorConsoleLoggerOptions>` so that I could change behavior at realtime via changing options at `appsettings.json` .

**Comment by IEvangelist** [comment]
Hi @Vinigas - I have a PR that will close this issue, see #23695.

**Comment by Vinigas** [comment]
In `ColorConsoleLoggerProvider.cs`

As I see `config.OnChange lambda` and `CreateLogger method` can be invoked concurrently from different threads. Meaning that in this example `_currentConfig` is being read and written at the same time without monitor. Meaning that this example can result in thread collition in rare scenarios then configuration is changed at the same time as logger being created.

Am I wrong ?
