### ISSUE TITLE
This not working when class derived from enumeration is in composite key

### ISSUE THREAD

**Issue by vlapenkov** [dotnet/docs#23319]
```
public class FakeEntity: BaseEntity
    {
        public string Name { get; set; }

        public int ContractId { get; set; }
    }

public class FakeEntityLink
    {
        public FakeEntity FakeEntity { get; set; }
        public int FakeEntityId { get; set; }
        public int BillParamTypeEnumId { get; set; }

        public BillParamTypeEnum BillParamTypeEnum { get; private set; } = BillParamTypeEnum.PriceCategory;

        private FakeEntityLink() { }
        public FakeEntityLink(FakeEntity fakeEntity, BillParamTypeEnum billParamTypeEnum)
        {
            FakeEntity = fakeEntity;
            BillParamTypeEnum = billParamTypeEnum;
        }
    }

public class BillParamTypeEnum
        : Enumeration
    {
        public static BillParamTypeEnum PriceCategory => new BillParamTypeEnum(1,"PriceCategory ");
        public static BillParamTypeEnum VoltageTarifLevel => new BillParamTypeEnum(2, "VoltageTarifLevel ");
        public static BillParamTypeEnum Sign => new BillParamTypeEnum(3,"Sign ");
        public static BillParamTypeEnum VolumeCategory => new BillParamTypeEnum(4,"VolumeCategory");

        public BillParamTypeEnum(int id, string name)
            : base(id, name)
        {
        }
    }

//and in dbContext

     modelBuilder.Entity<FakeEntityLink>(entity => {
                entity.HasKey(c => new { c.FakeEntityId, c.BillParamTypeEnumId });
                entity.HasOne(link => link.FakeEntity).WithMany();
                entity.HasOne(link => link.BillParamTypeEnum).WithMany().HasForeignKey(p=>p.BillParamTypeEnumId);
                //  entity.Property(p => p.BillParamTypeEnum).HasConversion<int>();
            }
                );

// code in controller
var fe =_db.FakeEntities.Find(1);
            _db.FakeEntityLinks.Add(new FakeEntityLink(fe, BillParamTypeEnum.VoltageTarifLevel));
            _db.SaveChanges(); // throws SqlException: Cannot insert explicit value for identity column in table 'BillParamTypeEnum' when IDENTITY_INSERT is set to OFF.

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @vlapenkov, thank you for reaching out. 

Looking at the error message, it seems like that we are setting identity property for the Id column. 
Did you get a chance to see the implementation of [OrderingContextSeed.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/5e0f55cbd92842445747a50f35c467d972ba80f9/src/Services/Ordering/Ordering.API/Infrastructure/OrderingContextSeed.cs)
