### ISSUE TITLE
Suggested Correction

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/docs#23318]
[Enter feedback here]

### Suggested Correction
For .NET 5.0, the correct code to add to Startup.cs is: 

```
services.AddControllers()
.AddJsonOptions(options => options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.Strict);

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf1aba2-84d8-e9cc-a18f-94f708a5cb20
* Version Independent ID: bbf3e8ed-b0fb-c7c2-ab4a-dc273026ad2c
* Content: [Breaking change: ASP.NET Core apps allow deserializing quoted numbers - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/jsonserializer-allows-reading-numbers-as-strings)
* Content Source: [docs/core/compatibility/serialization/5.0/jsonserializer-allows-reading-numbers-as-strings.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/serialization/5.0/jsonserializer-allows-reading-numbers-as-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@WillBaldwin Thank you for notifying us!
