### ISSUE TITLE
The Update attribute's purpose is not documented anywhere

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#23310]
```
<PackageReference Update="NETStandard.Library" PrivateAssets="all" />
```
I have the above in some project files. What does the Update mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
These are documented in Visual Studio docs under MSBuild [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild?view=vs-2019#attributes-and-elements).

**Comment by StingyJack** [comment]
> MSBuild properties not attributes.

Where else am I going to expect to find out about the attribute but with the property it belongs to? Include is described here, but not Update. Not even a link to the page you cited is present for this property.

> If the documentation isn't clear or sufficient, please open an issue using this link

@Youssef1313 - What do you think this issue is for? 

If you really think it's appropriate to continue leaving gaps in documentation like there is now, then you can move this issue (but you shouldn't). How you choose to organize is not a customer responsibility.

**Comment by Youssef1313** [comment]
@StingyJack I think it makes sense to have at least a link to VS Docs. But as I'm not a Microsoft employee, I tagged @gewarren to decide what to do here.

**Comment by gewarren** [comment]
The VS page is specifically about the Item element, so I'll add a note to the .NET article about Update (it's used to update the metadata on specific package references that were originally included as part of a group).

**Comment by StingyJack** [comment]
That sounds like its some kind of floating version, which I do not want to have.
