### ISSUE TITLE
Why not newer than CUDA 10.0?

### ISSUE THREAD

**Issue by zleepy** [dotnet/docs#23312]
Why should i not install CUDA newer than v10.0? 10.0 does not support newer versions of VS 2019.
A newer version of CUDA 10 says it does support VS 2019, see: https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-microsoft-windows/index.html.

And even newer, CUDA 11.2.1 does also say it supports VS, see: https://docs.nvidia.com/cuda/archive/11.2.1/cuda-installation-guide-microsoft-windows/index.html

What is the reason this page explicit says that i should not install anything that Nvidia says is supported by newer versions of VS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @zsleepy

Thanks for your question. I've posted an issue in the ML.NET repo since this is not a documentation issue dotnet/machinelearning#5726

Closing this issue for now. Please follow the discussion on there.
