### ISSUE TITLE
csc -errorreport is documented in length but has no effect

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#23323]
This page contains a long description of the `ErrorReport` property or the `-errorreport` option. However, as far as I can tell, the `-errorreport` option has no effect on any public version of the Roslyn C# compiler. It may have had some effect on the older C# compiler that is installed with .NET Framework 4 and does not support C# 6.

* It was ignored in the initial commit: <https://github.com/dotnet/roslyn/blob/3611ed35610793e814c8aa25715aa582ec08a8b6/Src/Compilers/CSharp/Source/CommandLine/CommandLineParser.cs#L816-L817>
* It is still ignored in version-3.2.0: <https://github.com/dotnet/roslyn/blob/15b43b33901c88f68ef43f8314b5a2457716780d/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L1180-L1181>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db1080c-bbc9-5c15-dea7-cf3c5638ea00
* Version Independent ID: 6a993c1e-13a2-c354-5d3d-4e9d401781b9
* Content: [C# Compiler Options - advanced scenarios](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/advanced)
* Content Source: [docs/csharp/language-reference/compiler-options/advanced.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/advanced.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @jaredpar 

Should this option be removed?

**Comment by jaredpar** [comment]
Agree this is a deprecated option and it should be removed.
