### ISSUE TITLE
Post condition attributes act on output arguments, not input

### ISSUE THREAD

**Issue by magla42** [dotnet/docs#23327]
There are several instances of these summaries:

MaybeNullWhen: A non-nullable input argument may be null when the method returns the specified bool value.
NotNullWhen: A nullable input argument won't be null when the method returns the specified bool value.

I am fairly sure that should be **output** argument?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reaching out @magla42 

The article is correct.  Let's take `MaybeNullWhen` applied to `String.IsNullOrEmpty` as an example:

```csharp
bool IsNullOrEmpty([MaybeNullWhen(true) string? input);
```

The `string`, `input`, *Maybe Null When* the method `IsNullOrEmpty` returns `true`. These attributes affect the subsequent "may be null" analysis for the input argument.

I'll close this as answered. Let us know if you have further questions.

**Comment by magla42** [comment]
Ah, I see. What confused me is that they are also used for output arguments, like

`bool TryGetMessage(string key, [NotNullWhen(true)] out string? message)`

and the summary that explicitly says input seems to exclude that. Perhaps the summaries of `MaybeNulWhen` and `NotNullWhen` could say just _argument_ instead of _input argument_?

**Comment by BillWagner** [comment]
@magla42 Thanks for the additional clarification. I see your point. Reopening, and I'll fix that.
