### ISSUE TITLE
A few more words would help

### ISSUE THREAD

**Issue by iGanja** [dotnet/docs#23333]
static IHostBuilder CreateHostBuilder...
goooooes where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. @IEvangelist I think it's confusing as to where that method should be put. Everything else features a class.

Thanks again!
