### ISSUE TITLE
Default values - evolved types

### ISSUE THREAD

**Issue by macha-firstis** [dotnet/docs#23358]
Hi, 
I'd like to propose to additionally document the default values behavior of nullable types, maybe also for other value types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d7544-6f92-5582-9d28-7160a5bc916a
* Version Independent ID: 7e3f884a-94b6-ea27-70ea-060fe51f51c2
* Content: [Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/)
* Content Source: [docs/csharp/programming-guide/arrays/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/arrays/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @macha-firstis 

To answer, arrays are initialized with the default value for the type, which is the 0-bit pattern. That means all value types have the value of 0. All reference types (including non-nullable reference types) have the value `null`. Nullable value types are value types, so they have the 0-bit pattern. That means the `HasValue` property is `false`, and they can be considered `null`.

I've added the "up for grabs" label if any community member wants to update this article.

**Comment by BillWagner** [comment]
Fixed by #25005
