### ISSUE TITLE
Is ConfigureAwait needed in DisposeAsync implementation

### ISSUE THREAD

**Issue by katdti** [dotnet/docs#23359]
In your implementation of:

 ```
       public async ValueTask DisposeAsync()
        {
            await DisposeAsyncCore();

            Dispose(disposing: false);
            GC.SuppressFinalize(this);
        }
```

ConfigureAwait is not used. What are the recommendations? ConfigureAwait(true) or ConfigureAwait(false)?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @katdti 
Thank you so much for posting this issue. We really appreciate it.

`.ConfigureAwait` is used within `DisposeAsyncCore` -- in most of the examples. I do see one place where it isn't used. But yes, it should be used and should call it with `false`.
