### ISSUE TITLE
"must" is imprecise, reason should be provided

### ISSUE THREAD

**Issue by goyzhang** [dotnet/docs#23356]
> To implement multiple event properties in a class, the class **must** internally store and maintain the delegate defined for each event. A typical approach is to implement a delegate collection that is indexed by an event key.

Why must? If it IS a must, then the reason should be provided. If the reason is just to reduce backing fields to improve performance, then the "must" should be changed to "suggested", with a reason explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a5f33d-52b9-fd2a-ecd0-35582d462f2c
* Version Independent ID: 80c4a287-3ad7-6642-ed89-d63cc71e860b
* Content: [How to: Handle Multiple Events Using Event Properties](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-handle-multiple-events-using-event-properties)
* Content Source: [docs/standard/events/how-to-handle-multiple-events-using-event-properties.md](https://github.com/dotnet/docs/blob/main/docs/standard/events/how-to-handle-multiple-events-using-event-properties.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @goyzhang
Thank you so much for posting this issue. We really appreciate it.

What other approach are you referring to for this? I'm a bit confused by your statements, but happy to update this accordingly.

**Comment by goyzhang** [comment]
Hi @IEvangelist ,
My point is that the current description is **imprecise**. The **must** word is too strong.  It's better to change it to a suggestion like:

`To implement multiple event properties in a class, the class **should** internally store and maintain the delegate defined for each event. A typical approach is to implement a delegate collection that is indexed by an event key. That's because **[REASON]**`

Actually, before I read this page,  I always added multiple event properties without using an EventHandlerList. And It worked, so I wonder why I have to do this. As for the reason, I'm not an expert about this but I think I got my answer from Marc Gravell : https://stackoverflow.com/questions/11895971/what-are-the-advantages-of-adding-delegate-instances-to-component-events-eventh
You can refer to that.

**Comment by IEvangelist** [comment]
Yes, Mark brings up a great point. I'm fine with "should" instead of "must" but would prefer some additional context as to why. I'm going to label this as up-for-grabs, and I encourage you to contribute a proposal for improving this. Is that something you'd be open to try?

**Comment by IEvangelist** [comment]
Closed by #23414
