### ISSUE TITLE
also install 'ca-certificates' for Debian 10

### ISSUE THREAD

**Issue by mahald** [dotnet/docs#23362]
IT would make sense to add 'ca-certificates' to the apt-install for Debian 10. As Debian does not install this by default and then dotnet restore does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@rbhanda Can you comment on this?

**Comment by adegeo** [comment]
@rbhanda  pint

**Comment by adegeo** [comment]
Pinging directly in teams....

**Comment by rbhanda** [comment]
@leecow can you help here

**Comment by leecow** [comment]
Debian 10 has been end-of-life since 2022 so I don't think I'd make any changes.

**Comment by mahald** [comment]
Was opened 2 1/2 years ago. Has become irrelevant.
