### ISSUE TITLE
That is, any category not specified is set to the default value.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#23378]
In [Configure logging](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#configure-logging)

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",          /// What does this do?
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

In the preceding JSON, the Default category is logged for Information and higher.

Should we add:  That is, any category not specified is set to the default value.
Right now it's ambiguous and probably wrong because 
> the `Default` category 
looks like a literal category. It should be
... the default category ...
so default can be translated.

If you agree, feel free to assign to me and I'll update this.

cc @serpent5 @JonPSmith 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346bbcf3-9f8e-b253-09fe-906195392783
* Version Independent ID: 0e787ac2-1108-1d94-d62f-ccffa93e06c3
* Content: [Logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line)
* Content Source: [docs/core/extensions/logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
I'm not sure I agree, the actual key is `"Default"` and it's value is `"Information"`, while I understand you mean it's the _default value_. Some of the keys correspond to namespaces, but some are just parts of a namespace. I think it is fine as is.

The literal category is in fact `"Default"`, which is interpreted as default.

**Comment by Rick-Anderson** [comment]
What about just appending something close to

> That is, any category not specified is set to the value specified in the `Default` value.

That's the only change.
