### ISSUE TITLE
Page was poorly written

### ISSUE THREAD

**Issue by WindowStations** [dotnet/docs#23381]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1f8854-18aa-1ee3-f715-410e04cb7982
* Version Independent ID: 883a59bd-8b13-5c11-18c9-abfa94d44236
* Content: [Tlbexp.exe (Type Library Exporter)](https://docs.microsoft.com/en-us/dotnet/framework/tools/tlbexp-exe-type-library-exporter)
* Content Source: [docs/framework/tools/tlbexp-exe-type-library-exporter.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/tlbexp-exe-type-library-exporter.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Can you be more specific about what part of the article is poorly written?

**Comment by WindowStations** [comment]
Sounds like a partially deflective response, but I take the bait.    On the page it says with a link: "This tool is automatically installed with Visual Studio. To run the tool, use a command-line shell for developers."  That link takes me to a page that says that 2019 is now prerequisite, not an SDK as suggested here.  Why is there no documentation that it is not available in Visual studio anymore?   Where does it say an SDK is needed?  You see, there are fundamental problems with the style of writing and general laziness, that lead the reader on a wild goose chase.  I'm not alone on this.

**Comment by tdykstra** [comment]
Thanks for following up .  That text was recently changed, the original text was:

>To run the tool, use the Developer Command Prompt for Visual Studio (or the Visual Studio Command Prompt in Windows 7). For more information, see [Command Prompts](https://docs.microsoft.com/visualstudio/ide/reference/command-prompt-powershell?view=vs-2019.

The change wasn't meant to imply that you could run the tool at a command  prompt other than the VS Developer Command Prompt. We'll look into making the language clearer.

>Why is there no documentation that it is not available in Visual studio anymore?

The developer command prompt is still in Visual Studio, and you now have a PowerShell command prompt option that wasn't there before. In VS go to Tools >  Command Line > Developer Command Prompt and tlbexp is still available.

**Comment by tdykstra** [comment]
@WindowStations We've addressed the lack of clarity in these docs in  PR #23391 and [6497](https://github.com/MicrosoftDocs/visualstudio-docs/commit/89929acf718a856c997254f74f6942daa6464919#diff-503d5e950dc7e5e9b9eeacfdd49947d480413ffc60a153cb5bb462dffd48d916). Please let us know if additional changes would be helpful.
