### ISSUE TITLE
Code example on C# pointer types really helps in comprehending the topic quickly.

### ISSUE THREAD

**Issue by priyamtheone** [dotnet/docs#23387]
Earlier versions of MSDN containing this topic didn't have the code example, because of which it was hard to understand. The inclusion of the code example really helps in comprehending the matter way faster than the earlier versions. Code examples are truly friendly and helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb800363-8529-0848-459e-4dc05c2ba19a
* Version Independent ID: 8f36dd5e-f8e3-f446-f749-aa319f5a6660
* Content: [Pointer types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/pointer-types)
* Content Source: [docs/csharp/programming-guide/unsafe-code-pointers/pointer-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/unsafe-code-pointers/pointer-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @priyamtheone 

Closing as Kudos.
