### ISSUE TITLE
Text unclear about arrays implementing IEnumerable<T>

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/docs#23399]
The text under [Array overview
](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/#array-overview) pretends that arrays implement `IEnumerable<T>`; however, this only true for single-dimensional arrays (who in fact implement `IList<T>`).

The text should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d7544-6f92-5582-9d28-7160a5bc916a
* Version Independent ID: 7e3f884a-94b6-ea27-70ea-060fe51f51c2
* Content: [Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/#array-overview)
* Content Source: [docs/csharp/programming-guide/arrays/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/arrays/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by canton7** [comment]
Also discussed in #13010

**Comment by BillWagner** [comment]
Thanks for noting this @OJacot-Descombes and @canton7 

I've added this to our backlog to update. I've also added the "up for grabs" label if anyone wants to submit a PR.

**Comment by OJacot-Descombes** [comment]
Thanks for fixing this @BillWagner and @KellenCarl.
