### ISSUE TITLE
Assembly.Location now fails at build time

### ISSUE THREAD

**Issue by sebastienros** [dotnet/docs#23398]
The documentation states that `Assembly.Location Returns an empty string`.

However building an application with such code will now produce a compilation error:

```
/tmp/benchmarks-agent/benchmarks-server-1/tumn4iry.eki/benchmarks/src/Benchmarks/Program.cs(41,55): error IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'. [/tmp/benchmarks-agent/benchmarks-server-1/tumn4iry.eki/benchmarks/src/Benchmarks/Benchmarks.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/tumn4iry.eki/benchmarks/src/Benchmarks/Program.cs(44,57): error IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'. [/tmp/benchmarks-agent/benchmarks-server-1/tumn4iry.eki/benchmarks/src/Benchmarks/Benchmarks.csproj]
  Benchmarks -> /tmp/benchmarks-agent/benchmarks-server-1/tumn4iry.eki/benchmarks/src/Benchmarks/bin/Release/net6.0/linux-x64/Benchmarks.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
```

With this error, I am now in need of a compilation constant to use to conditionally use this code or not. If that one exists it would be beneficial to add it to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1932751-7c2b-ce92-936e-e97f8581d5fa
* Version Independent ID: de677d1f-386a-e4c3-fdd0-6806b3ef2c0e
* Content: [Single file application - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)
* Content Source: [docs/core/deploying/single-file.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/single-file.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @LakshanF
* Microsoft Alias: **lakshanf**

**Comment by tdykstra** [comment]
@LakshanF Can you help with this question?

**Comment by gewarren** [comment]
@jtschuster Do you know of a compilation constant to use here?

**Comment by tlakollo** [comment]
So the fact that the app is failing is just because WarnAsError is activated, IL3000 is a warning from the analyzer. Having said that, I don't think there is a compilation constant for handling it. Usually, the way to handle these warnings is to suppress the warning after handling the problem. 

```C#
[UnconditionalSuppressMessage("SingleFile", "IL3000:Avoid accessing Assembly file path when publishing as a single file", Justification = "Code handles when the assembly location is empty")]
private string MethodUsingAssemblyLocation(Assembly a)
{
    string assemblyLocation = a.Location;
    if (string.IsNullOrEmpty(assemblyLocation))
    {
        // Handle what will happen if the Location is empty
    }
    else
    {
    }
}
```
