### ISSUE TITLE
The documentation of yield is incomplete

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/docs#23409]
This page does not mention the use of the `yield` keyword inside async iterators (methods that return `IAsyncEnumerable<T>`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ee1728-8dda-5659-8a20-d1c62a1d2968
* Version Independent ID: 83f7821d-22ad-54eb-33c6-aed24c7e2f4d
* Content: [yield contextual keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield)
* Content Source: [docs/csharp/language-reference/keywords/yield.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/yield.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks again @theodorzoulias This was also an oversight, and I've added it to the next sprint.
