### ISSUE TITLE
Outdated line reference

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23404]
The number reference here appears to be outdated. Will file an issue and fix separately to keep this PR focused as it's already large.

_Originally posted by @Youssef1313 in https://github.com/dotnet/docs/pull/23132#r598063683_

**Comment by Youssef1313** [comment]
Also in https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/numbers-in-csharp-local.md

**Comment by BillWagner** [comment]
Thanks @Youssef1313 I'll watch for the PR.
