### ISSUE TITLE
Update doc to reflect that as of C# 9 partial methods can have accessibility modifiers and return types other than void

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/docs#23408]
In C# 9 all restrictions are removed from `partial` methods: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/extending-partial-methods

This needs to be reflected on this page.

I can update it if it's ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450a248b-ab3f-ac3f-d3a5-b1e74b3355ba
* Version Independent ID: 5e05ac12-7d29-d144-a49a-e54765343c20
* Content: [Partial Classes and Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@maxkoshevoi I believe you can open a PR to update that if you want.

**Comment by maxkoshevoi** [comment]
@Youssef1313 Does issue needs to be approved, before I can open a PR?

**Comment by Youssef1313** [comment]
While I'm not a Microsoft employee, I believe the team will want to have such an enhancement. But you can wait for @BillWagner or @IEvangelist to confirm.

**Comment by IEvangelist** [comment]
Hi @maxkoshevoi &and @Youssef1313)

Yes, this needs to be updated to correctly reflect the changes you called attention to. We would be thrilled to review a PR, and we appreciate it. Please reference this issue number in the PR, and note that I've updated this issue with the up-for-grabs label. Thank you.

**Comment by BillWagner** [comment]
See also #23083 and #23084 for more instances that need to be updated.

**Comment by tdykstra** [comment]
This will also address #20578
