### ISSUE TITLE
A zip file seems to be corrupt.

### ISSUE THREAD

**Issue by TThaan** [dotnet/docs#23406]
I could not open the dataset/zip file from 
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification/assets.zip.

The link 
https://github.com/dotnet/machinelearning-samples/releases/download/186179/Train_a_deep_learning_image_classification_model_with_ML_NET_and_TensorFlow.zip

on page
https://docs.microsoft.com/en-us/samples/dotnet/machinelearning-samples/mlnet-image-classification-transfer-learning/

worked for me.

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8adaedc-37da-e381-a87e-6649bc6cb3c8
* Version Independent ID: 779340cf-274b-5af9-54f0-b9b90c54f143
* Content: [Tutorial: Automated visual inspection using transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning)
* Content Source: [docs/machine-learning/tutorials/image-classification-api-transfer-learning.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/image-classification-api-transfer-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by Youssef1313** [comment]
The link from samples browser downloads the full sample, while the zip file in the article is intended to be the "assets.zip" only, and it works for me.

Can you elaborate more on the problem you're seeing with it?

**Comment by TThaan** [comment]
In the tutorial "Image Classification" in chapter "Prepare and Understand the data" I could actually download a zip file by right-clicking on the link in the line "1. Download the dataset and unzip." and then selecting "Save Link As". 
But that is not the real zip file including the data set. This link just leads to the page with the real download link. 
It was my misunderstanding, everything is ok on your side. Sorry for that.

**Comment by BillWagner** [comment]
Ping @luisquintanilla @briacht

**Comment by luisquintanilla** [comment]
Looking into it. Thanks @BillWagner

**Comment by luisquintanilla** [comment]
Thanks @TThaan for confirming it works. Closing this issue for now
