### ISSUE TITLE
The explanation in the section "Unacceptable pattern" is not correct.

### ISSUE THREAD

**Issue by fantaclaus** [dotnet/docs#23400]
The explanation of the section "Unacceptable pattern" is not clear and the comment in the code sample is not correct.

If an exception is thrown inside the `AnotherAsyncDisposable` constructor then **none** of the created objects would be properly disposed.

And it is not because of the "stacked usings" pattern itself. But because of the fact that the execution of the function will be terminated even before getting to the first `using`. So none of the constructed objects would be passed to `using` to be disposed.

Another acceptable pattern could look like this:

```cs
ExampleAsyncDisposable objOne;
AnotherAsyncDisposable objTwo;

await using ((objOne = new ExampleAsyncDisposable()).ConfigureAwait(false))
await using ((objTwo = new AnotherAsyncDisposable()).ConfigureAwait(false))
{
	// ...
}
```

But it looks ugly enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @fantaclaus 
Thank you so much for posting this issue. We really appreciate it.

There is a larger discussion right now with the broader that overlaps on this article a bit, I'll be sure to address this then.
