### ISSUE TITLE
Contradicting previously set rule for simplicity. Not sure if intended 🤷‍♂️

### ISSUE THREAD

**Issue by axcap** [dotnet/docs#23411]
The unit test in section [Validate private methods by unit testing public methods](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#validate-private-methods-by-unit-testing-public-methods) violates [Avoid magic strings](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-magic-strings) rule as **parser.ParseLogLine** does not fully disclose what will happen to the string under the hood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#feedback)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I think the code is fine here, the `" a "` passed in the test isn't something *special* in the production code. The example that uses `const string MAXIMUM_RESULT = "1001";` is different, here it appears that `"1001"` is something "special". It's a known number that production code is known to throw overflow exception if the result is `>= 1001` (i.e, > 1000).

**Comment by BillWagner** [comment]
Thanks for pointing this out @axcap 

I agree with @Youssef1313 's analysis here. There's nothing "magic" about the input. It's one possible input test case.

I'll close this, but if you feel strongly that this should change, you can add more details here.
