### ISSUE TITLE
The documentation of the iterators concept is incomplete

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/docs#23410]
This page does not mention that an iterator method can be a source of not only `IEnumerable<T>`s, but also of `IAsyncEnumerable<T>`s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ba3a4c-1796-84b8-4152-b9806483ce86
* Version Independent ID: bd878489-9a4c-6d99-6c4c-c56e0387012b
* Content: [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/iterators)
* Content Source: [docs/csharp/iterators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/iterators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @theodorzoulias 

I had missed this in planning my updates for `IAsyncEnumerables`. I've added it to the .NET 5 project, and our next sprint.
