### ISSUE TITLE
Records can have methods too

### ISSUE THREAD

**Issue by wldevries** [dotnet/docs#23417]
> Methods are declared in a class or struct by specifying:

or in records

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @wldevries 

We should update that for .NET 5.  I've added the "up for grabs" label and added it to our C# 9 project.

**Comment by Meligy** [comment]
Is this issue just about correcting this very sentence or what else is required to investigate / correct?
