### ISSUE TITLE
Proposal: Add explicit guidance regarding multiline expression of let bindings

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#23416]
I'd like to add a small section about what to do with multiline body expressions in let and member bindings.
Example:

```fsharp
let functionName x y = a
````

if `a` is long or multiline it should be placed on the next line with an indent.

```fsharp
let functionName x y = 
    a
```
regardless of what [SynExpr](http://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html) `a` ends up being.

Some examples I consider bad:
```fsharp
let a = """
foobar, long string
"""

let b = async {
    return () // not following the other CE samples
}

let c = {
    Name = "Bilbo"
    Age = 112
}

let d = while f do
    printfn "%A" x
```

From my (technical) point of view, the only a few `SynExpr` that can start right after the `=` sign and it strikes me as inconsistent to have these.
The only one I could find in the current guide is:
```fsharp
let rec sizeLambda acc = function
    | Abs(x, body) -> sizeLambda (succ acc) body
    | App(lam1, lam2) -> sizeLambda (sizeLambda acc lam1) lam2
    | Var v -> succ acc
```
As `MatchLambda` is only 1 of 63 SynExpr cases, this just seems like not worth having.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Seems like a reasonable thing to clarify in the guide.
