### ISSUE TITLE
Some code snippets are empty

### ISSUE THREAD

**Issue by SaSha-K1** [dotnet/docs#23420]
Some code snippets are empty in the [Add the final polish paragraph](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#add-the-final-polish) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix#update-your-analyzer-to-ignore-correct-declarations)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Thanks @SaSha-K1. I'll fix that.

@gewarren Do you know why there were no build warnings?

**Comment by gewarren** [comment]
> @gewarren Do you know why there were no build warnings?

No, that is strange. I'll investigate and open a bug if necessary.

**Comment by gewarren** [comment]
I logged internal bug https://dev.azure.com/ceapex/Engineering/_workitems/edit/397329.
