### ISSUE TITLE
why is it that the Microsoft team always give the most compex scenarios to explain stuff in the most complicated/bloated way. Why not choose the simple examples first!

### ISSUE THREAD

**Issue by deanveggy** [dotnet/docs#23436]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b95913-4dea-8160-0184-9aaf6c2c363e
* Version Independent ID: b779abdd-e97e-2fa5-87a9-76b859c38c7c
* Content: [How to: Return a Value from a Task](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-return-a-value-from-a-task)
* Content Source: [docs/standard/parallel-programming/how-to-return-a-value-from-a-task.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/how-to-return-a-value-from-a-task.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @deanveggy 

Thank you so much for posting this issue. We really appreciate it. I see what you're saying here, it does seem a bit complex and could be simplified.

I typically suggest never using the `.Result` property, instead you should be using the `await` keyword to get the result instead. I'll take a look at addressing this.

**Comment by deanveggy** [comment]
hi @IEvangelist thank's for that. sorry i was a bit over the top with the 'always' ..not quite true.  i have a c# Blazor project full of Async methods but a little frustrated debugging due to my lack of understanding of Tasks & Async etc    :-)

**Comment by IEvangelist** [comment]
No worries, trust me when I say that I understand - we've all been there. Happy to help, let me know if you need more assistance. Thank you
