### ISSUE TITLE
How to write C# analyzer code fix is inconsistent in its message in documentation and the example code

### ISSUE THREAD

**Issue by KevinSWork** [dotnet/docs#23433]
The documentation is out-of-sync with the example code.  The documentation states to make the AnalyzerMessageFormat:

Variable '{0}' can be made constant

When later issuing the diagnostic, the code is:

context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation()));

Note that no argument is passed to Diagnostic.Create to substitute for the {0} in the format string.

If I look at the example code in GitHub (https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/MakeConstAnalyzer.cs#ReportDiagnostic) the associated resource file in that project has the AnalyzerMessageFormat as:

can be made constant

I think the right approach is to change the example code's resource to actually take the variable name as an argument and update the Diagnostic.Create call to issue the diagnostic as:

context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation(), variable.Identifier));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix?source=docs)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Thanks @KevinSWork. I'll get that fixed.
