### ISSUE TITLE
Wrong description of inequalities with NaN results

### ISSUE THREAD

**Issue by foreverstupid** [dotnet/docs#23448]
[Enter feedback here]
Any comparision with `double.NaN` returns `false`. But this page says that inequalities between values and `double.NaN` returns `true`. That is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bf1c84-36bb-3d48-d632-5473070c5701
* Version Independent ID: dff2500c-c6d4-2cfd-5409-663feb6805e4
* Content: [CA2242: Test for NaN correctly (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2242)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2242.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2242.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by pkulikov** [comment]
Inequality with NaN returns true:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMADALABQBAjGWbhQJwAUFAdIQAQCEAvGwCYD26YABs4zAHIRxASgDcQA==

**Comment by foreverstupid** [comment]
> Inequality with NaN returns true:
> https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMADALABQBAjGWbhQJwAUFAdIQAQCEAvGwCYD26YABs4zAHIRxASgDcQA==

Well, I guess that was ambigous usage of `inequality` term. I thought that here `inequality` means something like the following:
```C#
double.NaN > 1.0     // true
```
Ok, then, I've misunderstood the point
