### ISSUE TITLE
The examples on this page do not document the 'using' statement at all!

### ISSUE THREAD

**Issue by JVD66** [dotnet/docs#23453]
The examples on the page:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement

do not document the 'using' statement, but rather multi-line string usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
Thank you for your feedback. Both of the examples do have the using statement in them, so how do they fail to illustrate the using statement?
