### ISSUE TITLE
Ignoring nulls doesn't seem to work during deserialization

### ISSUE THREAD

**Issue by lukos** [dotnet/docs#23450]
On this page, it only talks about ignoring null values when serializing. However, the property IgnoreNullValues clearing says: "Gets or sets a value that determines whether null values are ignored during serialization and **deserialization**."

The page should make it clear whether it is supposed to apply to deserialization and if not, the code comment should be updated.

This is on dotnet core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7aa3b68-ffe0-8bdf-b6f4-b99672086a92
* Version Independent ID: db1ef743-6f31-a509-4676-f22d4847792d
* Content: [How to ignore properties with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties)
* Content Source: [docs/standard/serialization/system-text-json-ignore-properties.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-ignore-properties.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that - I'm updating the API ref article.

**Comment by tdykstra** [comment]
My mistake, this option does work during deserialization. See https://github.com/dotnet/dotnet-api-docs/pull/5470#issuecomment-806306430

**Comment by lukos** [comment]
I think the confusion that I had was that I was deserializing a set of key/value pairs to a dictionary and it included the null values, which I didn't want. 

I don't really understand what ignoring null means during deserialization anyway unless your properties have default values, otherwise they will be null by default so there would be no difference between deserializing null onto null or just ignoring the value and it having its default value of null.

**Comment by tdykstra** [comment]
>unless your properties have default values
That's what it's used for

**Comment by AraHaan** [comment]
While it’s documented for if the json contains the field as null, or default. But what does it do when it’s simply not present because it’s optional? Discord’s api does this and if it does handle this then Remora.Discord could migrate some of it’s converters to using the attribute instead.
