### ISSUE TITLE
Please document more C# compiler properties

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#23456]
These are documented at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#allowunsafeblocks but not included in the "Compilation-related properties" section:

- AllowUnsafeBlocks
- CheckForOverflowUnderflow
- DefineConstants
- Nullable

Not seeing this documented anywhere yet:

- EmbedAllSources
- EmbedUntrackedSources
- RootNamespace
- AssemblyName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BillWagner** [comment]
Those options are all covered in the [CSC task reference for MS Build](https://docs.microsoft.com/en-us/visualstudio/msbuild/csc-task?view=vs-2019) Maybe a link to that is sufficient here?

**Comment by jnm2** [comment]
@BillWagner Sure, but the section already notes one common property and one obscure property. Shouldn't more common properties be noted, or the whole section be replaced with a link?

**Comment by BillWagner** [comment]
@jnm2 A few of us need to work together to get all the information in the best place, without duplication.

I'd like to learn how you landed on this page vs. C# the compiler options page or the MS Build section in the Visual Studio docs. That can help us find where to put the information and where to link to that one source.

**Comment by jnm2** [comment]
@BillWagner I searched for something similar to https://www.google.com/search?q=.net+core+new+msbuild+properties and this was the first result. I had a memory of a page that used to exist that explained all the csproj SDK properties that got added for .NET Core which was my previous go-to for this.

**Comment by gewarren** [comment]
It probably makes sense not to have any C# option properties on this page, but to include a section header and a link to the C# compiler options page.

**Comment by BillWagner** [comment]
@gewarren Do you think this can happen before .NET 6 ships? Or should we bump it directly into November?
