### ISSUE TITLE
Crap information.

### ISSUE THREAD

**Issue by Scatterblak** [dotnet/docs#23467]
Top of the page:

===========================

.NET formatting rules: Rules that apply to both C# and Visual Basic. The EditorConfig option names for these rules start with dotnet_ prefix.
C# formatting rules: Rules that are specific to C# language only. The EditorConfig option names for these rules start with csharp_ prefix.
===========================

...and then the entire page is nothing to c#. There are still some vb users out here that would like to be able to adjust some formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729883e2-dbb0-4fd5-c122-42a337283b62
* Version Independent ID: ff0fdfd7-042b-4d76-5d52-7e5a1bc167b6
* Content: [Code style formatting rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/formatting-rules.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/formatting-rules.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BillWagner** [comment]
@Scatterblak 

I can sense your frustration. We know there are locations where we need to improve the VB examples and descriptions. Thank you for bringing it to our attention.

In the meantime, you should read the .NET Foundation [code of conduct](https://dotnetfoundation.org/about/code-of-conduct) and consider editing your description above.

**Comment by gewarren** [comment]
@Scatterblak This seems like a feature request where you are requesting more formatting options that apply to Visual Basic. Is that correct?
