### ISSUE TITLE
Add Saml2Constants to System.​Identity​Model.​Tokens Namespace

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2346]
MIA ...

https://referencesource.microsoft.com/#System.IdentityModel/System/IdentityModel/Tokens/Saml2Constants.cs,77 from https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens?view=netframework-4.7

Update `ClassReference` member remarks of *xml/System.IdentityModel.Tokens/Saml2AuthenticationContext.xml*.

**Comment by GuardRex** [comment]
@mairaw This is unblocked now, but I won't have time to address by Monday night. I'll unassign it now.

**Comment by mairaw** [comment]
@guardrex I can't recall what this work was about.

**Comment by guardrex** [comment]
Me neither. :smile: ... other than what it says up there :point_up:, idk what this is about.

**Comment by mairaw** [comment]
Ok, now I think I managed to decode this message.
So this is about https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.saml2authenticationcontext.classreference?view=netframework-4.7#remarks, which points to the source code. Given that those values are from an internal class, they wouldn't show up in docs. So I'm just going to close this and leave as-is.
