### ISSUE TITLE
Mention that docker based actions only run on Ubuntu vms

### ISSUE THREAD

**Issue by xt0rted** [dotnet/docs#23479]
Docker based actions only work when your workflow runs on a Ubuntu/Linux vm, since Windows is heavily used for .net it'd be helpful to mention this caveat. I build, test, and package dozens of full framework applications using actions but they have to run on Windows while supporting things like linting and automation can run on Ubuntu or macOS.

[Actions documentation showing Docker support](https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c32d49db-bd6c-c5db-96c9-fe426191d6ca
* Version Independent ID: 491a0389-f24d-a398-4496-873461b6180d
* Content: [Tutorial: Create a GitHub Action with .NET](https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action)
* Content Source: [docs/devops/create-dotnet-github-action.md](https://github.com/dotnet/docs/blob/main/docs/devops/create-dotnet-github-action.md)
* Product: **dotnet**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @xt0rted
Thank you so much for posting this issue. We really appreciate it. That is a great callout, I will add that soon.
