### ISSUE TITLE
Properties should include auto property initializers

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#235]
@martinwoodward mentioned this when he built labs from the information here: https://github.com/martinwoodward/csharpworkshop/tree/master/004-Properties#exercises

I can update the article later this week.

**Comment by mairaw** [comment]
@BillWagner is this issue for [this article](https://github.com/dotnet/core-docs/blob/master/docs/csharp/properties.md) only or in general? The description doesn't give many details of what needs to be done here

**Comment by BillWagner** [comment]
Yes, it's [that article](https://github.com/dotnet/core-docs/blob/master/docs/csharp/properties.md)

What I need to add is an example that shows initializing a property. Something like:

```csharp
public class BlogPost
{
    public IList<Comment> Comments { get; } = new List<Comment>();
}
```

That would initialize the baking field for the Comments property.
