### ISSUE TITLE
*Minor - Discrepancy between code and comment

### ISSUE THREAD

**Issue by Slugsie** [dotnet/docs#23503]
The example code for 'Continue For' says 'between 5 and 7' in the comments, but the code checks for >= 5 and <= 8, so the comment should be 'between 5 and 8'
`

    ' If number is between 5 and 7, continue
    ' with the next iteration.
    If number >= 5 And number <= 8 Then
        Continue For
    End If
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755c1267-e41d-54dd-8a79-eed101810bab
* Version Independent ID: c1841ce4-97b3-6feb-0dc5-a26914ee35ff
* Content: [For Each...Next Statement - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/for-each-next-statement)
* Content Source: [docs/visual-basic/language-reference/statements/for-each-next-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/for-each-next-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

Thanks again!
