### ISSUE TITLE
ZipFile.ExtractToDirectory(string, string, bool) incorrectly states destination directory cannot exists

### ISSUE THREAD

**Issue by UpperAvenue** [dotnet/docs#23513]
**Issue description**

[ZipFile.ExtractToDirectory(string, string, bool) documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=net-5.0#System_IO_Compression_ZipFile_ExtractToDirectory_System_String_System_String_System_Boolean_)

Documentation states the destination directory specified must not exist, but that is not true if the *overwriteFiles* parameter is set to true.  This is incorrectly stated in the Parameter documentation the Exceptions documentation and the Remarks documentation.

(I have not verified the other parts of the documentation, only the part that says the destination directory must not exists.)

**Target framework**

.NET 5

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#5483
