### ISSUE TITLE
Couldn't print the article on both sides of paper.

### ISSUE THREAD

**Issue by IG020** [dotnet/docs#23527]
In printer options I selected "print on both sides of paper", but the article was still printed only on one side producing 7 pages instead of 4 pages.

Igor Gelin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576a6c40-a4ad-5922-a7d7-51e0f13baf61
* Version Independent ID: f2f1676b-0ba1-9601-37f5-2fd6aa63f682
* Content: [Collections and Data Structures](https://docs.microsoft.com/en-us/dotnet/standard/collections/)
* Content Source: [docs/standard/collections/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/collections/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Transferred to https://github.com/MicrosoftDocs/feedback/issues/3620
