### ISSUE TITLE
Is there any package upgrade command or notification for templates?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#23528]
Templates can be updated regularly, without blindly uninstalling and installing (would that even install the latest or would it re-use cached), is there another way to determine if there is a need to upgrade a template package and then run the upgrade?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cd27054-288a-cd42-1f1d-9a58ef2b3a40
* Version Independent ID: 85ef1737-d703-ea92-7adb-71dc8c78a854
* Content: [Install and manage SDK templates - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/templates)
* Content Source: [docs/core/install/templates.md](https://github.com/dotnet/docs/blob/main/docs/core/install/templates.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
When you use the template, there is a notification that there is an upgrade available along with the command to do the upgrade.

I believe this answers your question, I'll close this issue.
