### ISSUE TITLE
[WinForms] DataGridView-related API validate state and throw IOE

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#23529]
## Selected DataGridView-related API validate object state and throw `InvalidOperationException`.

Selected API now validate object state and throw `InvalidOperationException` where previously a `NullReferenceException` could be thrown, if APIs were invoked without being constructing with a valid `Owner`.
Throwing `InvalidOperationException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Old behavior

The listed API would throw `NullReferenceException` if invoked with `null` input arguments.

### New behavior

The listed API would throw `InvalidOperationException` if invoked without having a valid `Owner` property value (in addition to the existing exceptions).

### Reason for change

Throwing `InvalidOperationException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Recommended action

- Review and, if necessary, update the code to prevent constructing the affected types with `Owner` as `null`.

### Category

- Windows Forms

#### Affected APIs

* [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject)
    - [x]  [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.Bounds Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject.bounds), property `Owner`
    - [x]  [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.DefaultAction Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject.defaultaction), property `Owner`
    - [x]  [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.Name Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject.name), property `Owner`
    - [x]  [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.State Property](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject.state), property `Owner`
    - [x]  [DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.Navigate(AccessibleNavigation) Method](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridviewtopleftheadercell.datagridviewtopleftheadercellaccessibleobject.Navigate), property `Owner`

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
I'm going to close this issue now. If there are any more IOE changes for .NET 6, please open a new issue.
