### ISSUE TITLE
Jupyter/Binder URL is broken in "Introduction to C#" tutorials page

### ISSUE THREAD

**Issue by vmussa** [dotnet/docs#23539]
Hello, everyone.

Jupyter/Bind tutorial's URL is broken due to GitHub's change in branch naming convention, from "master" to "main". 

**Description** 
Current broken URL: https://mybinder.org/v2/gh/dotnet/try-samples/master?filepath=hello-csharp%2Fhello-world.ipynb

**Solution**
Actual functioning URL: https://mybinder.org/v2/gh/dotnet/try-samples/main?filepath=hello-csharp%2Fhello-world.ipynb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cdfbba-c2bd-f9b0-52a9-d82cc9b2dcf9
* Version Independent ID: 287733f4-7593-ba5e-f26c-531fde328319
* Content: [Introduction to C# - interactive tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @vmussa 

I see that @Youssef1313 has already submitted a fix. I'll review that and merge it today.
