### ISSUE TITLE
Suggestions: Show simplify usage of Tuple results in if clauses

### ISSUE THREAD

**Issue by Symbai** [dotnet/docs#23532]
Something I didn't know is that if a function returns a Tuple you don't need to store the result in an extra line/variable, if you want to check the result in an if-clause AND want to use a variable of the Tuple in BOTH if-cases. I believe for beginners it will be very useful to show this in the documentation.

Example of **non** tuple function and use case:

```C#
/*
 We can declare the 'remainder' value in the if-line and use the variable in both cases
 without needing to write an extra line to save the result before the if-clause
*/
if (Math.DivRem(12, 6, out int remainder) == 2) 
{
    Console.WriteLine($"True and remainder is: {remainder}");
}
else 
{
    Console.WriteLine($"False and remainder is: {remainder}");
}
```
Now this function has changed in .NET (Core) to return a Tuple and instead of writing this:

```C#
/*
 You cannot declare a Tuple in an if-line and without knowing the syntax,
 beginners will write something like this
*/
var (result, remainder) = Math.DivRem(12, 6);
if (result == 2)
{
    Console.WriteLine($"True and remainder is: {remainder}");
}
else 
{
    Console.WriteLine($"False and remainder is: {remainder}");
}
```
We can actually simplify by writing:
```C#
/*
 Like in first example with OUT parameter, we can save the extra line using a specific syntax
*/
if (Math.DivRem(12, 6) is { Quotient: 2, Remainder: var remainder })
{
    Console.WriteLine($"True and remainder is: {remainder}");
}
else 
{
    Console.WriteLine($"False and remainder is: {remainder}");
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e533179-50e7-813d-be49-e1248134dd10
* Version Independent ID: 1778e921-76f6-32d5-4509-7bd944a01e0d
* Content: [Tuple types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples)
* Content Source: [docs/csharp/language-reference/builtin-types/value-tuples.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Symbai is this divrem update in .NET 6? The current API docs don't have such a method.

**Comment by Symbai** [comment]
I believe it is, here is the corresponding issue: https://github.com/dotnet/runtime/issues/42156

**Comment by pkulikov** [comment]
@Symbai Yes, I see, the article can be updated with the section about tuples and pattern matching. 
@BillWagner is this reference article a proper place for such a section?

**Comment by BillWagner** [comment]
@Symbai @pkulikov 

This is an idiom we should document.  I can see other uses over time as more APIs return tuples, either in the .NET libraries, Nuget packages, or internal customer libraries.

It feels like this is more of a tutorial than a reference example though. That's my first thought, so I'm open to other views. What do both of you think?

**Comment by pkulikov** [comment]
@BillWagner I also think that it fits a tutorial more than a reference article.

**Comment by Symbai** [comment]
You may be right with your last paragraph @BillWagner but if you highlight an API and press F1 in VS this is what it opens in VS and I'm using this a lot when I have to look up how something is used. And because the topic contains "Use cases of Tuple" section it won't be too wrong to add a use case of a function returning a Tuple and how it can be used when calling this function. I mean it will be enough to show the IF one-liner only once without its being an exclusive section on its own.

For example modifying the [existing sample](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#use-cases-of-tuples):

```diff
var xs = new[] { 4, 7, 9 };
var limits = FindMinMax(xs);
Console.WriteLine($"Limits of [{string.Join(" ", xs)}] are {limits.min} and {limits.max}");
// Output:
// Limits of [4 7 9] are 4 and 9

var ys = new[] { -9, 0, 67, 100 };
var (minimum, maximum) = FindMinMax(ys);
Console.WriteLine($"Limits of [{string.Join(" ", ys)}] are {minimum} and {maximum}");
// Output:
// Limits of [-9 0 67 100] are -9 and 100

+ var ys = new[] { -9, 0, 67, 100 };
+ if (FindMinMax(ys) is { min: -9, max: var maximum })
+ {
+   Console.WriteLine($"Limits of [{string.Join(" ", ys)}] are {minimum} and {maximum}");
+ }
+ // Output:
+ // Limits of [-9 0 67 100] are -9 and 100

(int min, int max) FindMinMax(int[] input)
{
    if (input is null || input.Length == 0)
    {
        throw new ArgumentException("Cannot find minimum and maximum of a null or empty array.");
    }

    var min = int.MaxValue;
    var max = int.MinValue;
    foreach (var i in input)
    {
        if (i < min)
        {
            min = i;
        }
        if (i > max)
        {
            max = i;
        }
    }
    return (min, max);
}
```

You won't have to write a tutorial. It will be enough to demonstrate this syntax once somewhere for people to see this is also possible.

**Comment by BillWagner** [comment]
Thanks for the discussion. I'm open to either or both options as a fix.

I've added it to our list of issues to address.
