### ISSUE TITLE
Can't set reliableMessagingVersion in vs 2019 community edition.

### ISSUE THREAD

**Issue by PabloJomer** [dotnet/docs#23531]
reliableMessagingVersion can't be set in the 2019 version of visualstudio. When was it removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12300eca-40bd-35ad-8ba6-582084c62f22
* Version Independent ID: 4a4f2890-be60-8780-1fb9-8b28907925a2
* Content: [&lt;reliableSession&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/reliablesession)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/reliablesession.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/file-schema/wcf/reliablesession.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by adegeo** [comment]
@mconnew can you comment?

**Comment by mconnew** [comment]
@PabloJomer, I have installed the latest 2019 Community Edition and can't see a problem. What do you mean by can't be set?  
Are you trying to use the WCF Configuration Editor? The WCF Workload isn't installed by default which means you would be missing the config file right click menu option "Edit WCF Configuration".  
Or is the issue with the config XML schema not showing you options in intellisense? If so, is it not offering you the `<reliableSession>` element, or the `eliableMessagingVersion` attribute, or the list of possible values?  
Or is setting it in your config not being applied at runtime?

**Comment by PabloJomer** [comment]
The studio complains that the attribute does not exist. Also when building the application crashes on the same error.

`<?xml version="1.0"?>
<configuration>

  <appSettings>
    <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.7.2" />
    <httpRuntime targetFramework="4.7.2"/>
  </system.web>
  <system.serviceModel>
    <behaviors>
      <serviceBehaviors>
        <behavior>
          <serviceMetadata httpGetEnabled="true" httpsGetEnabled="true"/>
          <serviceDebug includeExceptionDetailInFaults="false"/>
        </behavior>
      </serviceBehaviors>
    </behaviors>
    <bindings>
        <wsHttpBinding>
            <binding name="VGBinding">
                <security mode="None" />
                <reliableSession
                    reliableMessagingVersion="WSReliableMessagingFebruary2005"
                    enabled="true"
                    ordered="true"
                    inactivityTimeout="00:03:00" />
            </binding>
        </wsHttpBinding>
    </bindings>
    <protocolMapping>
        <add binding="wsHttpBinding" bindingConfiguration="VGBinding" scheme="http" />
    </protocolMapping>    
    <serviceHostingEnvironment aspNetCompatibilityEnabled="true" multipleSiteBindingsEnabled="true" />
  </system.serviceModel>
  <system.webServer>
    <httpErrors errorMode="Detailed" />
    <modules runAllManagedModulesForAllRequests="true"/>
    <directoryBrowse enabled="false"/>
  </system.webServer>

</configuration>`

The error reported in the studio is "The reliableMessagingVersion attribute is not allowed."

Thanks in advance.

**Comment by mconnew** [comment]
The documentation you opened this issue against is for when creating a custom binding. The documentation you need is [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/wshttpbinding#syntax) and you can see that there is no reliableMessagingVersion attribute on the reliableSession element for WSHttpBinding. WSHttpBinding is like a recipe, it's a predefined set of protocol versions grouped together. The intention is to allow you to use the same simple recipe on the server and client and only worry about turning features on or off. The reliable sessions version that WSHttpBinding uses is WSReliableMessagingFebruary2005 so it looks like you can just not specify it. If you needed to use WSReliableMessaging11, then the WS2007HttpBinding would be better, but that uses different versions of other protocols (e.g. a different WS-SecureConversation version) so might cause you other problems depending on your scenario.  
If you do need to change the reliable sessions version to something else but keep everything else the same, you would need to create a custom binding and specify all the component parts that you are using.

**Comment by PabloJomer** [comment]
I see I did not realize that it could be different attributes on the same element for different parent elements. Thank you for directing me in the right direction. Where can I read more about default values for WS2007HttpBinding and WSHttpBinding?

Kind regards,
Pablo

**Comment by adegeo** [comment]
@PabloJomer I found https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/ws2007httpbinding and https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.ws2007httpbinding?view=netframework-4.8 via a web search. Hope that helps.
