### ISSUE TITLE
Path attribute on <inheritdoc/>

### ISSUE THREAD

**Issue by KrakenZ** [dotnet/docs#23533]
The ```path``` attribute is missing.

I only wanted to include the "returns" part of a inherited documentation.
Had to waste time looking up that ```path``` attribute exists, XPath expression is a thing, and had to learn how to actually do it.

Noting that ```path``` attribute is a XPath expression, with references/examples to what can be done in it would be great.

Here's the paths I use; could be used as examples I guess:
• Inherit only the ```returns``` tag: ```path="/returns"```
• Inherit all but ```remarks``` tags: ```path="//*[not(self::remarks)]"```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04441bbc-7e98-d6df-2c5a-20e816d79dc7
* Version Independent ID: ba155807-a2b0-8982-abe7-fac1e2b51a7d
* Content: [&lt;inheritdoc&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc)
* Content Source: [docs/csharp/programming-guide/xmldoc/inheritdoc.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/xmldoc/inheritdoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @KrakenZ 

I'll be updating this section shortly. I'll address this at that time.
