### ISSUE TITLE
Definition of Abstraction and Encapsulation are incorrect.

### ISSUE THREAD

**Issue by voxvanhieu** [dotnet/docs#23543]
I'm sure that "Encapsulation means that a group of related properties, methods, and other members are treated as a single unit or object." But It's confusing to define that "Encapsulation means hiding the unnecessary details from type consumers." Because "hiding the unnecessary details from type consumers" is right for abstraction also. The difference is Encapsulation hides details from accessing, Abstraction hides details for unnecessaries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/docs/pull/22888 and https://github.com/dotnet/docs/pull/23315.

**Comment by BillWagner** [comment]
I'll add this to our backlog. 

We've had several issues written for these definitions. It's clear they can be expressed better.

**Comment by davidbcoulson** [comment]
OK, we need to put this to rest quickly because anyone who is looking to learn C# for a job is going to fail their first interview question and then hate the language and then it will die and we will all be left with PHP or Ruby.   The actual literal definition of the word Encapsulation is 'the action of enclosing something in or as if in a capsule'.   That is about the same as making a single unit from other points of data.

Abstraction or Abstract is from a Latin word meaning "pulled away, detached,".  Think of a transmission on a car, you can see the shifter but you are not seeing the gears move in an automatic car. Think of this as an abstraction.  

Final point, if you do some Googling all the blogs and forums that discuss this, follow this documentation. The world sees  Encapsulation as things placed into a single unit of data and Abstraction as hiding things or only showing what we want to show. 

At this point changing these terms would be like telling the world the sky is no longer blue, it's green.

**Comment by BillWagner** [comment]
@davidbcoulson I agree that we need to address this quickly. (It was on my list for this week).

My concern with simply switching the definitions back again is that the verb "hide" applies to both encapsulation and abstraction. In your example above, you can think of an automatic transmission as encapsulating the gears and the mechanisms needed to change gear ratios. I like your statement here (grammar edits mine):

> Encapsulation ~~as~~ is things placed into a single unit of data and Abstraction ~~as~~ is hiding things or only showing what we want to show.

For our purposes here, I would focus on the following key points for this terms:

- *Abstraction* focuses on identifying the important components of a system. You'll use abstractions when you create classes to implement important behavior for your program.
- *Encapsulation* focuses on hiding the internal complexities of a system. You'll use encapsulation when you determine what the public interface for a class should contain.

Let me know if you want to update your PR along those lines. (If you do, note that the definitions are restated at the end of the article as well as the introduction.)

**Comment by davidbcoulson** [comment]
I would like to address the first sentence and the list. These were always referred to as "pillars" not "techniques" for me and that seems to be the theme else were. The happy medium, I would suggest calling them "principles".  Please let me know your thoughts. 

C# is an object-oriented programming language. The four basic principles of object-oriented programming are:

- Encapsulation - Ability to organize internal complexities of a system into single objects.
- Abstraction - Ability to access or restrict access to properties, methods, or members of something encapsulated.
- Inheritance - Ability to create new encapsulations based on existing encapsulations.
- Polymorphism - Ability to implement inherited properties or methods in different ways across multiple encapsulations.

**Comment by BillWagner** [comment]
@davidbcoulson I like it.  I'll make one edit:

>- Encapsulation - Ability to organize internal complexities of a system into single objects.
>- Abstraction - Ability to access or restrict access to properties, methods, or members of something encapsulated.
>- Inheritance - Ability to create new abstractions based on existing abstractions.
>- Polymorphism - Ability to implement inherited properties or methods in different ways across multiple abstractions.

My reason for replacing "encapsulation" with "abstraction" in the last two is this: A sub-class refines the abstraction of a base class. (A `car` is a more specific type of `vehicle`). 

If you make those updates to your PR, I'd appreciate it. It will be a major improvement. Thanks for the thoughtful discussion.

**Comment by voxvanhieu** [comment]
@BillWagner Thanks for the discussion. I like this definition. 
> * Encapsulation - Ability to organize internal complexities of a system into single objects.
> * Abstraction - Ability to access or restrict access to properties, methods, or members of something encapsulated.
> * Inheritance - Ability to create new abstractions based on existing abstractions.
> * Polymorphism - Ability to implement inherited properties or methods in different ways across multiple abstractions.

Please note that people are confusing about does OOP has abstraction.
Abstraction a.k.a Data abstraction is a step in system design. And Encapsulation, Inheritance, Polymorphism are three key techniques that OOP proposes to achieve Data abstraction. So, Abstraction is the bridge linking the business logic with software architectures.
Ref: [Abstraction is not a principle of Object-Oriented Programming](https://rebeja.eu/posts/abstraction-is-not-a-principle-of-object-oriented-programming/)

**Comment by davidbcoulson** [comment]
@BillWagner I have updated the PR. Thanks for working with me on this.
