### ISSUE TITLE
Can C# 9.0 be used with .NET Core 3.1 ?

### ISSUE THREAD

**Issue by pb-qs** [dotnet/docs#23547]
[Enter feedback here]

Can C# 9.0 be used with .NET Core 3.1 ?  And is it supported ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
You can use it, but it's not officially supported, and some features that depend on runtime support might not work.

**Comment by BillWagner** [comment]
@pb-qs Good question. As pointed out, that's not supported.

It is possible to edit your project file to use C# 9 with a project that targets .NET Core 3.1, but any number of features may not work as expected. 

I'm more curious as to what the blockers are moving from .NET Core 3.1 to .NET 5. That upgrade should be just a matter of changing the TFM. Can you explain why that's a concern?

**Comment by pb-qs** [comment]
Hi Bill, yes I was quite encouraged to see that I *could* get a lot of the C#9 to work targetting netcore 3.1, so my main question is it supported to do so?

As to why I can't just go to net 5.0, well the component I am writing is an Azure Function making use of Durable Functions.  Sadly not available until net 6.0 (c. Nov '21) according to the docs.

**Comment by BillWagner** [comment]
Ping @CamSoper for any assistance on .NET 5 in Azure Functions.

**Comment by CamSoper** [comment]
@pb-qs It's not super obvious, but .NET 5.0 can be used in Functions, either [by itself](https://docs.microsoft.com/azure/azure-functions/dotnet-isolated-process-guide) or in a [Docker container](https://docs.microsoft.com/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-csharp).

**Comment by BillWagner** [comment]
I'll close this as answered.

**Comment by pb-qs** [comment]
Hi  @CamSoper thanks for your reply.

Are you sure Durable Functions is supported on Azure Functions on .NET 5 ?

I read the following article:
https://techcommunity.microsoft.com/t5/apps-on-azure/net-on-azure-functions-roadmap/ba-p/2197916

If you search for the heading text: "Future of .NET on Azure Functions" you will see a diagram suggesting otherwise ?

thanks
Peter

**Comment by CamSoper** [comment]
@pb-qs I may stand corrected. I wasn't aware the Durable Functions extensions had such a limitation. Hey @anthonychu, can you please expand on this?

Thanks!

**Comment by anthonychu** [comment]
That's correct. If you want to use C# 9 or higher, you'll need to wait for Functions to support .NET 6. We should have a preview out in the summer.

**Comment by pb-qs** [comment]
Thanks for confirming Anthony!Qualitas Software | enquiries@QualitasSoftware.comFrom: Anthony Chu ***@***.***>Sent: Tuesday, 30 March 2021, 18:48To: dotnet/docsCc: Peter; MentionSubject: Re: [dotnet/docs] Can C# 9.0 be used with .NET Core 3.1 ? (#23547)
That's correct. If you want to use C# 9 or higher, you'll need to wait for Functions to support .NET 6. We should have a preview out in the summer.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dotnet/docs/issues/23547#issuecomment-810455384",
"url": "https://github.com/dotnet/docs/issues/23547#issuecomment-810455384",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pb-qs** [comment]
Hi - this issue was closed, without being resolved.   Can someone reopen please?

**Comment by Youssef1313** [comment]
> where I have to target .net core 3.1, so can I use C# 9.0 with that ?  Is that supported ?

You can do that, but as I mentioned earlier, it's not officially supported. Some features will work correctly, some other features won't work but can have some workarounds, and other features might not work completely. See https://github.com/dotnet/roslyn/discussions/47701 for some more information.

**Comment by BillWagner** [comment]
@pb-qs 

> this issue was closed, without being resolved. Can someone reopen please?

We closed it because the article is correct: C# 9 isn't supported on .NET 3.1. I'd raise this suggestion for the Azure Functions team, where hopefully enough customers ask for it to get that updated.
