### ISSUE TITLE
The XML doc section should move to language reference

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#23540]
This section is more of a reference section than a programming guide section.  So, it should move to the correct location.

As part of the move:

- [x] The overview section should be updated to include a typical workflow. It should also be more opinionated about its use.
- [x] The overview section may be one or two articles (Note that some articles are just link pointers, and the "recommended list" includes almost all tags. As such, it's not that helpful.:
  - [x] Typical `///` usage and recommended tags
  - [x] Typical processing of the source, and the resulting XML file
- [x] The reference could be updated along one of two organizations:
  - Tags based on type (class, member, namespace, etc)
  - Alphabetical tags, and where they can be applied.
  - Tags based on scenarios:
    - Tags that describe a type, or member
    - Tags to include code
    - Tags for references
    - Tags for inheriting docs

I think that last organization is the most useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306c4f25-192e-0980-c663-d829f38ef7c4
* Version Independent ID: 8918a37b-cbfa-33f1-21e2-6bf5ea3ccb54
* Content: [XML documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/)
* Content Source: [docs/csharp/programming-guide/xmldoc/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/xmldoc/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This area has a large number of issues that should be addressed as part of the edits to move the content:

- [Overview](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/)
  - #18659
- [Recommended tags](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)
  - #18730
- [`<example>`](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/example)
  - #17796
- [`<inheritdoc>`](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/inheritdoc)
  - #23533
  - #18236
- [`<see>`](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/see)
  - #21885
-  [`<seealso>`](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/seealso)
  - #18818 (Note: this likely applies to a number of articles in the reference section).

**Comment by BillWagner** [comment]
From reading all the issues referenced in the preceding comment, the following themes emerge:

- **Completing the reference tags**: Visual Studio intellisense has support for a number of XML / HTML tags in XML comments. The introduction to the reference should list those tags validated by the compiler, those supported by intellisense, and point out that other tags are ignored, but legal.
- **General organization**: There's a jumble of reference, recommended tags, how to create the XML file, how to process it. It's difficult for readers to address their scenarios quickly.
- **Examples based on language elements**: The examples are tied to the XML tag, not the language elements were those tags would be used.
- **Nuances on parsing**: `<` and `>` are valid XML, HTML, and C# (for generics). You can add CDATA sections to embed markdown in tags. These are all causes of annoyance for developers writing about their libraries. This theme could include attributes on tags, and XPath expressions for elements like `inheritdoc`.

Overall, these issues express a need for more and better examples showing how to add XML comments to libraries. I think the new organization should be:

- ***Overview***:  How to turn on XML file generation. What tags the compiler validates, and what tags are validated by Visual Studio intellisense. Finally, links to tools that generate docs from the XML (docfx, SandCastle, Doxygen). 
- ***Recommended tags***: This page details which tags are recommended, which is largely driven by what tags are displayed in intellisense, and what tags are most common. This will largely map to the recommended tags from the C# spec appendix.
- ***Examples***:  Examples should show how to write XML doc comments for:
  - *a class or struct*
  - *a class that inherits docs from a base*
  - *a class that inherits some docs from a base or interface*
  - *generic methods*
  - *generic classes*

It's important for the examples to show different attributes and elements for links and cross-references, inheriting doc comments, and including external doc files. The examples also must highlight rules for where any of the child tags can and can't be used.

I think each of the examples should be its own article, however that's something I'll decide based on how long the article is.

**Comment by gewarren** [comment]
Can you also update the link right under this heading? https://review.docs.microsoft.com/en-us/help/contribute-ref/contribute-ref-how-to-write-.net-docs?branch=master#xml-doc-tags

**Comment by BillWagner** [comment]
Fixed by #24705
