### ISSUE TITLE
Clarify how project-to-project references are handled

### ISSUE THREAD

**Issue by michielvoo** [dotnet/docs#23553]
The documentation states:

> Project-to-project references aren't packaged inside the project. Currently, you must have a package per project if you have project-to-project dependencies.

I think (but I am not sure) this phrase is not correct: "aren't packaged inside the project", because things cannot be packaged inside a project. Perhaps what is meant is "References from a project to another project aren't packaged inside the project's package"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the question, would this revised wording be clearer: 

> NuGet dependencies of the packed project are added to the *.nuspec* file, so they're properly resolved when the package is installed. If the packed project has references to other projects, the other projects are not included in the package. Currently, you must have a package per project if you have project-to-project dependencies

**Comment by michielvoo** [comment]
Yes, that removes the ambiguity imho.
