### ISSUE TITLE
IdentityServer is not an open-source anymore

### ISSUE THREAD

**Issue by BartoszKlonowski** [dotnet/docs#23551]
The creator of IdentityServer mentioned in his [blog](https://leastprivilege.com/2020/10/01/the-future-of-identityserver/):
> The current version (IdentityServer4 v4.x) will be the last version we work on as free open source. We will keep supporting IdentityServer4 until the end of life of .NET Core 3.1 in November 2022.

Also the license update mention in project [description](https://github.com/IdentityServer/IdentityServer4):
> As of Oct 1st 2020, we started a new company. All new feature work will happen in our new organization. The new Duende IdentityServer is available under both a FOSS (RPL) and a commercial license.

_Originally posted by @yaroslavvasko in https://github.com/dotnet/docs.pl-pl/issues/208#issuecomment-808428306_

Edit by @BillWagner to include document details block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188e28ad-73ce-658d-1712-f7b5e3ce61cf
* Version Independent ID: 52119533-ce08-ae89-21d0-fe36a8e3748d
* Content: [IdentityServer for Cloud Native Apps](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/identity-server)
* Content Source: [docs/architecture/cloud-native/identity-server.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/identity-server.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by BillWagner** [comment]
closing and reopening to apply labels.
