### ISSUE TITLE
Information about Microsoft Date format in System.Text.Json

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/docs#23566]
Should migration guide contain information about https://github.com/dotnet/runtime/issues/30776 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@domagojmedo Thanks for the suggestion.  Yes it should, and there's also issue #19760 associated with the article about [DateTime handling in System.Text.Json](https://docs.microsoft.com/dotnet/standard/datetime/system-text-json-support).
