### ISSUE TITLE
Event unsubscription

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/docs#23569]
Regarding this sample:

```
public static Task<string> DownloadStringAsync(Uri url)
 {
     var tcs = new TaskCompletionSource<string>();
     var wc = new WebClient();
     wc.DownloadStringCompleted += (s,e) =>
         {
             if (e.Error != null)
                tcs.TrySetException(e.Error);
             else if (e.Cancelled)
                tcs.TrySetCanceled();
             else
                tcs.TrySetResult(e.Result);
         };
     wc.DownloadStringAsync(url);
     return tcs.Task;
}
```

I'm concerned about the fact that the event handler is never unsubscribed from the event. I've seen this can cause problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3690f5e-7d05-118a-3f52-4f5ad92bf94d
* Version Independent ID: 25ae1988-eefb-c34a-cd6a-c134abba46e8
* Content: [Interop with Other Asynchronous Patterns and Types](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types#tasks-and-the-event-based-asynchronous-pattern-eap)
* Content Source: [docs/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types.md](https://github.com/dotnet/docs/blob/main/docs/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by adegeo** [comment]
Hello! I don't believe there should be a problem. The `wc` variable holding the event goes out of scope when the method returns and will be collected by the garbage collector.
