### ISSUE TITLE
Inconsistant brackets

### ISSUE THREAD

**Issue by esb7cp** [dotnet/docs#23574]
The brackets in the code snippets on this page are inconsistently on the same line as the statement when they should be on the new line. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d79f0472-2434-9724-979f-2d5eb281dd67
* Version Independent ID: 6c665c3e-93ac-cc9e-4d68-91e8cf285ed5
* Content: [throw - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/throw)
* Content Source: [docs/csharp/language-reference/keywords/throw.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/throw.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @esb7cp 

I've added this to our backlog, and I've added the "up for grabs" and "good first issue" labels.
