### ISSUE TITLE
IEqualityComparer<Person>

### ISSUE THREAD

**Issue by shao130** [dotnet/docs#23579]
Comparing Generic Collections
The following example illustrates the benefits of contravariance support in the IComparer<T> interface. The PersonComparer class implements the IComparer<Person> interface. However, you can reuse this class to compare a sequence of objects of the Employee type because Employee inherits Person.

**It implements IEqualityComparer<Person>, not IComparer<Person>.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d025b1f-4efd-1d30-b741-974d328c786c
* Version Independent ID: 0584ef75-a49a-2d11-0c8e-08c526a628fc
* Content: [Using Variance in Interfaces for Generic Collections (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-interfaces-for-generic-collections)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-interfaces-for-generic-collections.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/covariance-contravariance/using-variance-in-interfaces-for-generic-collections.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out. The sample code is correct, and the article should change to refer to the `IEqualityComparer<T>` interface.
