### ISSUE TITLE
Probing config element seems not working

### ISSUE THREAD

**Issue by azias** [dotnet/docs#23584]
I am trying to deal with Windows [Side-by-side Assemblies][1] system using manifest files in order to be able to place dlls in a subfolder while continuing to link to them (without using "runtime" loading of dependencies)

I have understood that I have to must use the [probing element][2] in the config file of the application. But is seems to be ignored, or I am doing wrong somewhere.

I describe below a full simple example of what I have done.

I have two sources file: `HelloWorld.cpp` that is the code of the dll and `main.cpp` for the main application.

## Base of the example

```cpp
#include <iostream>

__declspec(dllexport) void HelloWorld()
{
    std::cout << "Hello World!" << std::endl;
}
```

```cpp
__declspec(dllimport) void HelloWorld();

int main()
{
    HelloWorld();
    return 0;
}
```

Here are the commands to compile by hand:

```dos
cl /c /EHsc HelloWorld.cpp
link /dll HelloWorld.cpp
cl /c main.cpp
link main.obj HelloWorld.lib
main.exe
```

It outputs *Hello World!*: it works

Now I move the dll in a subfolder `bin`

```dos
mkdir bin
move HelloWorld.dll bin\HelloWorld.dll
main.exe
```

There is no output, but I did not expect it works.

## Implementing Side-by-side Assemblies using manifest files

Now, in order to implement the Windows Side-by-side Assemblies system, I add the 3 files below to obtain this folder structure:

```dos
.\main.exe
.\main.exe.manifest
.\main.exe.config
.\bin\HelloWorld.dll
.\bin\HelloWorld.dll.manifest
```

`main.exe.manifest`:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level='asInvoker' uiAccess='false' />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type='win32' name='HelloWorld.dll' version='1.2.3.4' processorArchitecture='amd64' />
    </dependentAssembly>
  </dependency>
</assembly>
```

`main.exe.config`:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<configuration>
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <probing privatePath="bin"/>
        </assemblyBinding>
    </runtime>
</configuration>  
```

`HelloWorld.dll.manifest`:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level='asInvoker' uiAccess='false' />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <assemblyIdentity name="HelloWorld.dll" version="1.2.3.4" processorArchitecture="amd64" type="win32"/>
  <file name="HelloWorld.dll"/>
</assembly>
```

```dos
mkdir bin
move HelloWorld.dll bin\HelloWorld.dll
main.exe
```

I get no output: I expect it works!

## Try to understand

I use sxstrace to undertstand what append:

```dos
sxstrace Trace -logfile:sxstrace.etl -nostop
main.exe
sxstrace Stoptrace
sxstrace Parse -logfile:sxstrace.etl -outfile:sxstrace.txt
```

The log is the following log:

```txt
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = fr-FR;fr;en-US;en
	ManifestPath = C:\Users\azias\Documents\dev\dll\main.exe.Manifest
	AssemblyDirectory = C:\Users\azias\Documents\dev\dll\
	Application Config File = C:\Users\azias\Documents\dev\dll\main.exe.Config
-----------------
INFO: Parsing Application Config File C:\Users\azias\Documents\dev\dll\main.exe.Config.
INFO: Parsing Manifest File C:\Users\azias\Documents\dev\dll\main.exe.Manifest.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: HelloWorld.dll,processorArchitecture="amd64",type="win32",version="1.2.3.4"
INFO: Resolving reference HelloWorld.dll,processorArchitecture="amd64",type="win32",version="1.2.3.4".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Users\azias\Documents\dev\dll\HelloWorld.dll.DLL.
				INFO: Attempt to probe manifest at C:\Users\azias\Documents\dev\dll\HelloWorld.dll.MANIFEST.
				INFO: Attempt to probe manifest at C:\Users\azias\Documents\dev\dll\HelloWorld.dll\HelloWorld.dll.DLL.
				INFO: Attempt to probe manifest at C:\Users\azias\Documents\dev\dll\HelloWorld.dll\HelloWorld.dll.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference HelloWorld.dll,processorArchitecture="amd64",type="win32",version="1.2.3.4".
ERROR: Activation Context generation failed.
End Activation Context Generation.
```

We can see that is has parsed `main.exe.config` but is not searching at all in the `bin` folder!

## My Question

So my question is: where I am wrong and how to make it works ?

Thank you

  [1]: https://docs.microsoft.com/en-us/windows/win32/sbscs/isolated-applications-and-side-by-side-assemblies-portal
  [2]: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/probing-element

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0891fa35-fdc7-612f-cbe4-dc4e4f2f771e
* Version Independent ID: 0feb2f7f-90eb-cb8e-ad88-c162e0267630
* Content: [&lt;probing&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/probing-element)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/probing-element.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/file-schema/runtime/probing-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@azias Sorry for the slow response. Thank for your the detailed information; your config file looks correct to me. Since we are not a support team, I would suggest asking your question at https://docs.microsoft.com/en-us/answers/topics/dotnet-runtime-framework.html.
