### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pun-Mengly** [dotnet/docs#23595]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba03ad71-413b-a1bf-c759-29a575887e72
* Version Independent ID: 6c2dac12-ba9a-4044-a93e-7cf759735f22
* Content: [Compiler Error CS1502](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1502)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1502.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1502.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Pun-Mengly Can you add any details to this issue? It's not clear what you're describing.
