### ISSUE TITLE
Side by side .NET versions per application level(This Sound Wrong)

### ISSUE THREAD

**Issue by BandaruNithin** [dotnet/docs#23591]
Multiple .NET frameworks versions can be installed in the same system like Version 3, 2.5, 4, 4.8 in windows right.
So, why will there be any issues?
If that is the case a lot of software in windows should have been breaking as many are build a lot of years back.

Can you clarify what do you meant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET 5 and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/main/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by tdykstra** [comment]
.NET Framework is a Windows component  -- you can run older 1.1, 2.0, and 3.0 applications when Control Panel says you have 3.5 because versions of .NET are backward compatible.
