### ISSUE TITLE
Local Kubernetes Web UI is not accessible and return REST API result

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#23604]
I followed the example from the link below:

https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes

When I entered the line below, which is from the doc above,

> az aks browse --resource-group exploredocker-aks-rg --name explore-docker-aks
> A browser window should open at http://127.0.0.1:8001 with a view similar to this one:
> 

It opens Azure AKS portal, instead of local UI.

When I open http://127.0.0.1:8001/ on the browser, it is like below, instead of UI.

![image](https://user-images.githubusercontent.com/2021414/113462509-24f41000-9419-11eb-996b-33a4c4b6233a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @PingPongSet , thank you for reaching out. 

If you are using the kubernetes version 1.19+, then AKS no longer supports the installation of the managed kube-dashboard addon. You can follow the instruction in [Kubernetes Web UI Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) to install the dashboard. And after successful installation, the dashboard should be available under either one of the url.

- http://127.0.0.1:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
- OR 
- http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

For more information, see the [Access the Kubernetes web dashboard in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @PingPongSet , just checking if you had a chance to look into this further. Thank you.
