### ISSUE TITLE
OKR: address x, y, and z

### ISSUE THREAD

**Issue by Marvinrr155q** [dotnet/docs#23611]
<--

GOAL:
Each team has a commitment around content performance

OBJECTIVES:

- Content developers continue to get familiar with the Content Perf report by identifying and updating articles
- Create a sustainable and repeatable process. Each M1 has a project for content performance and tracks
- Continue to use data and feedback from past quarters to influence updates to formulas and ranking 

RESULTS:

- Continue with 1 article per writer, per quarter
- % of page views to higher performing articles increases (targeted at 80% all up)

TRACKING:

- Use the [Azure DevOps template](https://dev.azure.com/mseng/TechnicalContent/_workitems/create/User%20Story) to create a tracking item
  - Required:
    - [ ] Includes tag "content-perf" and "FY21Q3"
    - [ ] Set M1 and M2 fields
    - [x] Area path. Set to your team's path as you see fit
- Writers add "ms.custom: contperfq3" to their updated articles to help with data reporting.

NOTE: For those teams that aren't currently using the [mseng TechnicalContent project](https://dev.azure.com/mseng/TechnicalContent), you'll still need to set up your items in it so we have an accurate inventory and ability to track.

-->

**Comment by BillWagner** [comment]
@Marvinrr155q 

It looks like this was opened in error. I'm going to close it. If there is a real issue, you can reopen it.
