### ISSUE TITLE
Install instructions for the dotnet-sdk on linux using snap lead to a non-working setup when using vscode

### ISSUE THREAD

**Issue by rhyek** [dotnet/docs#23612]
Install instructions for the dotnet-sdk on linux using snap need to take into consideration:

- https://github.com/OmniSharp/omnisharp-vscode/issues/4409
- https://github.com/dotnet/sdk/issues/10403
- https://github.com/OmniSharp/omnisharp-vscode/wiki/Configuring-Snap-installs-of-dotnet-sdk

I am on Ubuntu 20.10 and using the Omnisharp extension for vscode.

I had to uninstall the recommended snap alias and do `ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet` to get my development environment working and this is for an issue I hit a couple of minutes after deciding to try out donet core after a couple of years.

Not a good DX. Please update docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40005eb-f935-d50d-10ce-c1e0a47ea70e
* Version Independent ID: 91f4a9b7-09d0-f18e-af4a-c0af28a8948f
* Content: [Install .NET on Linux with Snap - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)
* Content Source: [docs/core/install/linux-snap.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-snap.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@rhyek Hey there! Thank you for reporting this. I'll see what I can do in the article to help work around that potential problem.
