### ISSUE TITLE
Mod operator (Visual Basic)

### ISSUE THREAD

**Issue by PLAAHemantha** [dotnet/docs#23620]
Dear All,
a - (b * Fix(a / b)) does not work correctly. Eg: a=58333.31, b=8333.33 result should be 0. But it is not. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e0d8d3-ed1e-7e9d-d0dc-3d577c286f60
* Version Independent ID: 6961eaa7-db11-5794-746e-42fb6e4a964b
* Content: [Mod Operator - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/mod-operator)
* Content Source: [docs/visual-basic/language-reference/operators/mod-operator.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/mod-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for noting this @PLAAHemantha 

Can you provide a more complete example?  I tried the following code, and the result is 0 for me:

```VisualBasic
Imports System

Module Program
    Sub Main(args As String())
        Dim a = 58333.31
        Dim b = 8333.33
        Dim result = a - (b * Fix(a / b))
        Console.WriteLine(result)
    End Sub
End Module
```

**Comment by PLAAHemantha** [comment]
Thanks for your reply,
Please use this code in VB6,

Dim a As Double, b As Double, result As Double
b = 8333.33
a = 58333.31

result = a - (b * Fix(a / b))

result is 8333.33; Why?

**Comment by BillWagner** [comment]
@PLAAHemantha These articles are for VB.NET.  See [here](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6.0-documentation) for VB 6 documentation. The [Mod operator](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa242823(v=vs.60)) for that version explains this behavior.

I'll close this as answered.

**Comment by PLAAHemantha** [comment]
Thanks
