### ISSUE TITLE
Providing configuration settings for configuration provider/source

### ISSUE THREAD

**Issue by reecebradley** [dotnet/docs#23628]
If you want to load a connection string to a real database, the comment in the article says:

"a secondary `ConfigurationBuilder` to supply the connection string from another configuration provider."

It would be nice to finish this out - so I would need to create a `ConfigurationBuilder` - ideally, pulling configuration values from the same sources like the default, e.g. command line, appsettings.json, env variables, etc. Should I do a configuration.Build() on the current configuration builder or really use a separate one? If a separate one, is there an easy way to tap into the default setup, i.e. use the [CreateDefaultBuilder](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#default-configuration)

The desire would be to put connectionString in same places the default ones would be. On a separate similar thread - AzureKeyVault configuration provider has a similar story, watched [Secretless apps with .NET and Azure Key Vault](https://channel9.msdn.com/Shows/On-NET/Secretless-apps-with-NET-and-Azure-Key-Vault). They just straight up used an ENV variable for the keyvault - which would cause heartburn to have one setting not be provided like the rest. In this blog post, [Add KeyVault to ASP.NET Core](https://medium.com/@dneimke/add-keyvault-to-an-asp-net-core-application-cab1012d2b60), he does this `var root = config.Build();`.

I guess I am looking for what would be an ideal approach. If I had to choose, I guess I would run `config.Build()` so as to not make a configuration builder to look for the same places. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1cda6a-30fa-91b9-793e-918666776c9f
* Version Independent ID: 4df737d8-1051-2ce1-1d61-58768046283b
* Content: [Implement a custom configuration provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-configuration-provider)
* Content Source: [docs/core/extensions/custom-configuration-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-configuration-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @reecebradley
Thank you so much for posting this issue. We really appreciate it. I'll try to address it soon.

**Comment by reecebradley** [comment]
Good work @IEvangelist 👍🏻

**Comment by IEvangelist** [comment]
> Good work @IEvangelist 👍🏻

Thanks, the article is live now with the updates - enjoy:
https://docs.microsoft.com/dotnet/core/extensions/custom-configuration-provider
