### ISSUE TITLE
Figure 1-2. SOA architecture. Incorrect diagram.

### ISSUE THREAD

**Issue by M01ls** [dotnet/docs#23638]
Figure 1-2. SOA architecture. Diagram is incorrect, service providers do not share persistent storage/relational database in the ESB pattern

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769db633-2483-c4f5-61f7-c56ca63cee05
* Version Independent ID: 315f36c3-3294-be2d-cc04-19e4d446c9c2
* Content: [The world is distributed](https://docs.microsoft.com/en-gb/dotnet/architecture/dapr-for-net-developers/the-world-is-distributed?source=docs)
* Content Source: [docs/architecture/dapr-for-net-developers/the-world-is-distributed.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/the-world-is-distributed.md)
* Product: **dotnet-architecture**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by robvet** [comment]
Thanks for suggestion. Will recommend removing database from diagram in upcoming v 1.1.

**Comment by erjain** [comment]
The document has been updated as per the suggestion. The issue can be closed now.
