### ISSUE TITLE
Ports are not available: listen tcp 0.0.0.0:52000: bind

### ISSUE THREAD

**Issue by larrywa** [dotnet/docs#23636]
Following step-by-step through getting started, when I try to run with F5 (Docker Compose) I get:

Error	DT1001	ERROR: for daprbackend  Cannot start service daprbackend: Ports are not available: listen tcp 0.0.0.0:52000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
If the error persists, try restarting Docker Desktop.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets

netstat does not show that this port is in use.

Ideas?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
If the port is not available, there should be another process that already uses the port. Did you try netstat with the `-q` flag? That will show you all the bound ports in addition to the connections and listening ports.

Also make sure there are no firewalls or other proxies blocking port access.

For this specific sample, you can try specifying a different port number in the Docker Compose file.

**Comment by amolenk** [comment]
Glad it worked out!

@nishanil Please close this issue.
