### ISSUE TITLE
Provide consistent handling of C# and VB compiler error/warning topics

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#2363]
# Provide consistent handling of C# and VB compiler error/warning topics

## General
Currently, there are several issues with C# and Visual Basic compiler error and warning message topics:

1. The topics are arbitrarily divided into two different directories. For C#, they are in a [language reference](https://github.com/dotnet/docs/tree/master/docs/csharp/language-reference/compiler-messages) subdirectory and a [miscellaneous](https://github.com/dotnet/docs/tree/master/docs/csharp/misc) directory. For Visual Basic, they are also in a [language reference subdirectory](https://github.com/dotnet/docs/tree/master/docs/visual-basic/language-reference/error-messages) and a [miscellaneous](https://github.com/dotnet/docs/tree/master/docs/visual-basic/misc) directory.
2. The TOC lists only the items in the language reference subdirectory. This means that, although all of the topics are published, they are not all easily accessible.
3. Most of the filenames of the Visual Basic error message topics consist of some variation of the error message text. This results in long filenames (and long TOC entries) that are difficult to parse and identify.
 
To address these issues, we should do the following:
1. Move all of a language's error message topics to a single directory, preferably the language reference subdirectory for [C#](https://github.com/dotnet/docs/tree/master/docs/csharp/language-reference/compiler-messages) and [Visual Basic](https://github.com/dotnet/docs/tree/master/docs/visual-basic/language-reference/error-messages).
2. Determine whether we need to define redirects for the moved files. (Possibly we won't need to, since the files in the miscellaneous directories are not easily discoverable.)
3. Make all compiler warning/error topics discoverable. Since there are too many of them for the TOC (there are currently 928 C# topics and 1,654 Visual Basic topics), index.md should list each of the compiler error/warning numbers.
4. Improve the discoverability of Visual Basic error topics in both GitHub and on docs.microsoft.com by renaming the files to have only the Visual Basic error/warning number rather than the message string. This also requires that we create redirects for the 203 existing files in the language reference directory.
 
//cc @billwagner @mairaw

**Comment by BillWagner** [comment]
I'll add one more recommendation:

I don't think we have all the warning and errors messages documented. I believe some of the most recent additions are not included.
