### ISSUE TITLE
Problem with code CS0144

### ISSUE THREAD

**Issue by andrija2304** [dotnet/docs#23642]
[I think you need to create a constructor. Try using lists and don't forget to type "using System.Collections.Generic;" at the beginning of your code. If you are using an array you need to declare the size of it in a constructor. For example:
class MyClass
    {
        AObject[] objects;
        int objectsNum;
        public Object(int projectsNum)
        {
            this.objectsNum = objectsNum;
            objects = new AObject[objectsNum]; //here you declare the size of the array//
        }
    }
And for lists:
class MyClass
    {
        List<AObject> objectList;
        public Object()
        {
            objectList = new List<AObject>();
        }
    }
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8831b6c2-8b55-3e22-b2f4-d6eed52e9ea0
* Version Independent ID: 5bf2b97e-b22a-4846-3423-34e3c68b5894
* Content: [Compiler Error CS0144](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0144?f1url=%3FappId%3Droslyn%26k%3Dk(CS0144))
* Content Source: [docs/csharp/misc/cs0144.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0144.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@andrija2304 It looks like you opened this issue with notes for your own learning.

Is there an issue for us to address here?
