### ISSUE TITLE
Question: is it safe to reuse JsonSerializerOptions across threads?

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#23644]
The article recommends reusing instances of JsonSerializerOptions to improve performance, but it doesn't say whether it's safe to do so across multiple threads (e.g. can I pass the same instance to multiple calls to [ReadFromJsonAsync()](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpcontentjsonextensions.readfromjsonasync?view=net-5.0) when making concurrent HTTP requests and processing the JSON response content?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279af375-abfa-e10e-046a-625cc14826be
* Version Independent ID: 1df274ad-ecf0-49e7-90c6-e6f05dce0788
* Content: [How to instantiate JsonSerializerOptions with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-configure-options?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-configure-options.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-configure-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @layomia

**Comment by layomia** [comment]
Yes it is safe to use the same instance across multiple threads. The metadata caches on the options instance a thread-safe, and the fact that the instance is immutable after the first (de)serialization helps us further.

**Comment by ericmutta** [comment]
Many thanks @layomia for the prompt clarification and @tdykstra for promptly updating the docs! :+1:
