### ISSUE TITLE
Can C# 9.0 be used with .NET Core 3.1 ? And is it supported ?

### ISSUE THREAD

**Issue by pb-qs** [dotnet/docs#23643]
[Enter feedback here]

Can C# 9.0 be used with .NET Core 3.1 ? And is it supported ?

I cant use .NET 5 as I rely on Azure Functions and Durable Functions, which are not supported in .NET 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
:wave: Hi @pb-qs 

C# 9 is not supported on .NET 3.1. You can configure it using the LangVersion element in your project file, but it is not supported.

Closing as an answered question.

**Comment by pb-qs** [comment]
Thanks!From: Bill Wagner ***@***.***>Sent: Tuesday, 6 April 2021, 15:52To: dotnet/docsCc: Peter; MentionSubject: Re: [dotnet/docs] Can C# 9.0 be used with .NET Core 3.1 ? And is it supported ? (#23643)

👋 Hi @pb-qs

C# 9 is not supported on .NET 3.1. You can configure it using the LangVersion element in your project file, but it is not supported.

Closing as an answered question.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/dotnet/docs/issues/23643#issuecomment-814185136",

"url": "https://github.com/dotnet/docs/issues/23643#issuecomment-814185136",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
