### ISSUE TITLE
Enhance snippets5000 to allow unit testing

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23640]
Currently the build only verifies that the code "compiles", it would be a good addition to *optionally* allow running a unit test project.

This could be done by having an optional *\*.sh* or *\*.cmd* file with a specific name, which contains `dotnet test` for example. This can be helpful in some samples to verify they doesn't break. For example, roslyn-sdk tutorial already has a unit test, but it's not run by the build.

The downside of doing this is, it may be needed by very very few samples. Not sure if it's worth doing so.

@adegeo @BillWagner @IEvangelist

**Comment by IEvangelist** [comment]
Hi 👋 @Youssef1313 
Thank you so much for posting this issue. We really appreciate it.

I'd argue that this is not needed, the work involved and added risk of potentially negatively impacting something else far outweighs the potential benefit. As you mentioned, most of the sample snippets do not have unit tests - in fact, I'm only aware of unit tests for the articles related to unit testing, other than that I do not believe that we have any other unit test code. I'll let the others chime in on this one, but my vote would be "no". Thank you though for thinking about this.

**Comment by BillWagner** [comment]
Great discussion. My view is more "not now" and "not for all snippets" than "no". 

First, as mentioned, I'd like to get to a point where we are building all the samples before we drive toward unit testing.

Second, most of the sample code is optimized for explaining a concept. In many cases that means the code is organized around small examples, where the output is printed to the console. Restructuring that kind of code will obscure the concepts we're trying to demonstrate. That seems counter productive.

That said, for larger samples, where we intend readers to download and run the samples, more unit testing would be valued. It would also demonstrate more professional developer practices. That has some merit, and hopefully could be done without obscuring the core concepts being demonstrated.

**Comment by IEvangelist** [comment]
We'd still like to do it, but we've never figured out a good way without radically changing the samples in ways that hurt the reader experience. For now, we'll close this, but we can always revisit it if we come up with a viable solution.
