### ISSUE TITLE
UDF failed to run

### ISSUE THREAD

**Issue by harishukla93** [dotnet/docs#23693]
I have followed the same syntax for UDF creation, but its failed on spark-submit. Throws bunch of stacktrace with error:

Caused by: org.apache.spark.api.python.PythonException: System.NullReferenceException: Object reference not set to an instance of an object.

Here is my spark-submit command:

spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin/Debug/net5.0/microsoft-spark-3-0_2.12-1.0.0.jar dotnet bin/Debug/net5.0/mySparkApp.dll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa17b96-900b-e157-153d-54635d864a76
* Version Independent ID: 66df9360-02ad-8c7f-9f97-d24efbfef8af
* Content: [Structured Streaming with .NET for Apache Spark tutorial](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/streaming)
* Content Source: [docs/spark/tutorials/streaming.md](https://github.com/dotnet/docs/blob/main/docs/spark/tutorials/streaming.md)
* Product: **dotnet-spark**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by adegeo** [comment]
Sending email to @mamccrea

**Comment by Niharikadutta** [comment]
Hi @harishukla93 , apologies for the late reply. Can you try setting the `DOTNET_ASSEMBLY_SEARCH_PATHS` env variable to the directory that has the DLLs for your UDF? Please refer to [this doc](https://github.com/dotnet/spark/blob/main/docs/deploy-worker-udf-binaries.md#1-environment-variables) for more details.

**Comment by harishukla93** [comment]
@Niharikadutta I got that resolved!! 

So, ultimately that was a fault in my DLLs which were not compatible. When I wrote this I was a newbee, but now I am familiar with dotnet and how it works with spark.

Thanks for your response and sorry for my stupid query.

**Comment by Niharikadutta** [comment]
Thanks for the update @harishukla93 , please feel free to close this issue if this problem no longer persists. Thanks for trying Spark .NET and feel free to reach out if you have any issues in the future.
