### ISSUE TITLE
Strict mode is not documented

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23709]
See [this tweet](https://twitter.com/jlaban/status/1380130130169843712). `<Features>strict</Features>` isn't documented anywhere.

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

Adding @davkean @jaredpar 

Should we document this, or is it meant as a work around while warning waves are in progress?

**Comment by BillWagner** [comment]
Per internal conversation with @davkean Strict mode has been replaced by [`AnalysisLevel`](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysislevel), which is documented.

Closing as no action needed.
