### ISSUE TITLE
Sample code missing user agent string, resulting in 403 forbidden 

### ISSUE THREAD

**Issue by jevdemon** [dotnet/docs#23707]
Code sample doesn't inc;lude a user agent string when instantiating the WebClient, resulting in 403 forbidden exception.
Change sample code to include a user agent such as:
`                content = await new WebClient {
                    Headers = new WebHeaderCollection {
                        "user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0"
                    }
                }.DownloadStringTaskAsync(address);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e64eba6-e183-dfd7-fc52-deaf8a717ed6
* Version Independent ID: f2135220-cdf6-a4bb-5f2a-9a5c0ac6fbdf
* Content: [How to: Create Pre-Computed Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-create-pre-computed-tasks)
* Content Source: [docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋🏽 @jevdemon
Thank you so much for posting this issue. We really appreciate it.

I'll work on it this sprint and report back my proposal for the code fix in a pull requet.
