### ISSUE TITLE
docker images does not show mcr.microsoft.com/dotnet/aspnet when following steps

### ISSUE THREAD

**Issue by AFDevMike** [dotnet/docs#23714]
[Enter feedback here]
I am learning Docker containerization and at the step: 
```
docker build -t counter-image -f Dockerfile .
```

> After this command finishes, run docker images to see a list of images installed:

I see 
> counter-image 

but do not see:
> mcr.microsoft.com/dotnet/aspnet         5.0 

as expected from the list of images in the doc.

I believe I followed all the steps accurately up to this point.

The following statement higher up
> The dotnet/core segment is the container repository

 leads me to question if `FROM mcr.microsoft.com/dotnet/aspnet:5.0` is accurate.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @AFDevMike
Thank you so much for posting this issue. We really appreciate it.

The last time I did this (when I updated the article to .NET 5) I ran through everything again to verify it was still correct/accurate, and it seemed good then. I'll try to recreate this and report back to you my findings.

**Comment by IEvangelist** [comment]
Hi 👋 @AFDevMike

I have not been able to reproduce this issue. Have you tried running through it again?

**Comment by AFDevMike** [comment]
Hi @IEvangelist ,

I am not in a position to duplicate this issue in a timely manner and so I would offer you can close this issue.   

Personally, after using all available documentation and specifically the "Next steps" link [Learn how to containerize an ASP.NET Core application.](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0), I successfully containerized a linux based HTML to Pdf solution to sun on azure.  😎
