### ISSUE TITLE
section IConfiguration parameter: useless call to Bind

### ISSUE THREAD

**Issue by fantaclaus** [dotnet/docs#23717]
There is a code sample in the section "IConfiguration parameter":

```cs
namedConfigurationSection.Bind(new LibraryOptions
{
    // Default library options are overridden
    // by bound configuration values.
});
```

The method Bind assigns values from `namedConfigurationSection` to the instance of newly created object of type LibraryOptions.

But the object is not used anywhere. So the call to Bind is useless.

What is the purpose of this code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @fantaclaus
Thank you so much for posting this issue. We really appreciate it.

The new of the `LibraryOptions` instance is used to bind to the named section of the `IConfiguration` section. When instantiated it may contain default values, the section from the config overwrites anything that was configured. When consumers ask for an `IOptions<LibraryOptions>` they'll get the instance that was bound with the calling `.Bind` function and all of the corresponding configured values. Does that make sense?

**Comment by fantaclaus** [comment]
It doesn't work this way. I've checked it out.

`Bind` just copies data from `namedConfigurationSection` to the object instance. It doesn't really *bind* anything (I have no clue why it is named so). You can see it in the [source code](https://source.dot.net/Microsoft.Extensions.Configuration.Binder/R/a9de1082cf7e70ca.html).

If you want to achieve the described behavior you need this code:

```cs
services.Configure<LibraryOptions>(namedConfigurationSection);
```

**Comment by IEvangelist** [comment]
Ah, after looking into this in more detail - and testing out your claims, I stand corrected. You're right, I'm updating this. Thank you
