### ISSUE TITLE
docker images does not show mcr.microsoft.com/dotnet/aspnet 

### ISSUE THREAD

**Issue by AFDevMike** [dotnet/docs#23715]
[Enter feedback here]
I am learning Docker containerization and at the step: 
```
docker build -t counter-image -f Dockerfile .
```

> After this command finishes, run docker images to see a list of images installed:

I see 
> counter-image 

but do not see:
> mcr.microsoft.com/dotnet/aspnet         5.0 

as expected from the list of images in the doc.

I believe I followed all the steps accurately up to this point.

The following statement higher up
> The dotnet/core segment is the container repository

 leads me to question if `FROM mcr.microsoft.com/dotnet/aspnet:5.0` is accurate.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Closing as this is a dup of #23714
