### ISSUE TITLE
Getting error attempting to follow tutorial with VS 2019

### ISSUE THREAD

**Issue by X3n0n3x** [dotnet/docs#23713]
I'm attempting to follow [this tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes) using Visual Studio 2019. From past tutorials, I'm inferring that the VS 2019 equivalent of the initial instruction in "[Create your application](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes#create-your-application)" is to create a new project, a C# Console Application for .Net Core, named "classes". Based on [advice I received in this thread](https://github.com/dotnet/docs/issues/23577), I chose .NET 5 instead of .NET 3.1
My understanding of the VS2019 equivalent for the next instructions regarding making the BankAccount.cs file are to right click "classes" in the right hand solution explorer, and Add a new item of type Visual C# Class.

Oddly, the first steps in the next section, "Define the bank account type" instruct me to create another instance of BankAccount.cs using a different method than before, resulting in 2 instances of BankAccount.cs (with the second one being listed as a "Miscellaneous" file by VS 2019 since it is not connected to the "classes" project).  However, I simply replicate the same code in both instances of BankAccount.cs just in case.

~~Everything seems fine up until the tutorial asks me to run the code in the "Open an account" section, where I am told there are build errors, and VS 2019 reports the following error:~~

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'initialBalance' of 'BankAccount.BankAccount(string, decimal)'	classes	C:\Users\Sean\source\repos\classes\classes\Program.cs	9	Active

```

~~I am guessing that what may be missing is some kind of reference in either Program.cs or BankAccount.cs to link to the other one? However I believe I have followed the tutorial up to this point, here is my code:~~

**UPDATE:** 
I think I noticed the mistake causing the error: in line 9 of Program.cs I misplaced the second quotation mark " . Fixing this resolved the error, although I am still curious about the instructions for creating a duplicate BankAccount.cs in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting these @X3n0n3x 

Either of the methods you describe above will work to create a class. We wrote this so that readers who were using VSCode could also follow this.

When you find these instructions, use whichever method is most natural for you. I'm glad you're progressing!

I'll close this as an answered question.

**Comment by X3n0n3x** [comment]
Ok, thanks for the clarification
