### ISSUE TITLE
This guide says that the `Portfolio` class be defined in both a proto file and in a c# assembly. 

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#23728]
Did I read that correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 325dd28c-3bed-f7ff-4f13-7c7c951250fd
* Version Independent ID: f9bef770-f952-169a-0dec-a25606d4207d
* Content: [Migrate a WCF request-reply service to gRPC - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-request-reply)
* Content Source: [docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775

**Comment by StingyJack** [comment]
It wasnt an ebook when I opened this issue.
