### ISSUE TITLE
Source code, logical steps and images relate too loosely to one another

### ISSUE THREAD

**Issue by evaapavel** [dotnet/docs#23724]
The article about asynchronous tasks is brilliant.

I'm still relating to https://github.com/dotnet/docs/issues/20485

I guess the text describes roughly 6 steps:
1. Synchronous version
2. Asynchronous version with "inline awaits" such as `Egg eggs = await FryEggsAsync(2);`
3. Asynchronous version with "sequential awaits" such as `Task<Egg> eggsTask = FryEggsAsync(2);  Egg eggs = await eggsTask;`
4. Asynchronous version with two awaits (bacon and eggs) moved to the end of the method
5. Asynchronous version with synchronous and asynchronous operations composed into one task
6. (Skipping the Exceptions section) Final asynchronous version with `Task finishedTask = await Task.WhenAny(breakfastTasks);`

According to my understanding, steps no. 1, 4, and 6 have visualization in images that are accompanying the article.

With certain effort, I was able to get source code for each step. Then I wanted to understand the images. I tried to match the times you mention in them.
The first image (step 1) states 30 minutes.
The second image (step 4) 20 minutes.
The third image (step 6) 15 minutes.

I've set a measure 1 minute in the picture to 1 second in the program.
You have 5 main tasks and 2 subtasks:
1. Coffee takes 0 seconds
2. Eggs take 6 secs
3. Bacon takes 6 secs
4. Toast (itself) takes 3 secs, but it has Butter and Jam subtasks
5. Juice takes 0 seconds
6. Butter takes 0 secs
7. Jam takes 0 secs

This does not match the minutage at all, so I tried to add some seconds to the "immediate tasks":
1. Coffee takes 3 seconds
2. Eggs take 6 secs
3. Bacon takes 6 secs
4. Toast (itself) takes 3 secs, but it has Butter and Jam subtasks, so 9 seconds in total
5. Juice takes 3 seconds
6. Butter takes 3 secs
7. Jam takes 3 secs

With these times, the synchronous version takes 27 seconds (which roughly matches the 30 minutes in the first image).
The final asynchronous version takes 15 seconds which corresponds to the third image with 15 minutes.

However, I'm not able to match the second image with 20 minutes. Starting from step 4, each asynchronous version of the sample program takes 15 seconds, not 20.

Could you please be more specific in the article regarding this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @evaapavel I'm glad you liked the overall article.

You're correct that the drawings don't exactly match the time for the code. Some of that is to keep the code easier to comprehend in this sample. Some is to avoid a sample that ran for 30 minutes doing very little useful work. 

We could invest the time to make these exactly match, or scale as you point out. I'd rather invest that time in the planned content to cover other aspects of async / await and Task-based programming. I think that would serve everyone better.

I'd like to close this without action, but before I do, I'd like to be sure the time discrepancy didn't negatively impact your understanding of the concepts. 

What are your thoughts?

**Comment by sssvt-foltyn** [comment]
OK, please, do close this.

I was just unhappy because I could not find a version of the source code (the "right" step in the article thoughts' workflow) that would get a result better than the synchronous version, but worse than the final asynchronous one. That's all.

Thank you for your response.

**Comment by evaapavel** [comment]
OK, please, do close this.

I was just unhappy because I could not find a version of the source code (the "right" step in the article thoughts' workflow) that would get a result better than the synchronous version, but worse than the final asynchronous one. That's all.

Thank you for your response.
