### ISSUE TITLE
Wrong difference to EF6

### ISSUE THREAD

**Issue by cjblomqvist** [dotnet/docs#23727]
In this section: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#main-differences-with-ef6s-complex-types

It says: 

> They can reference other entities (that is, they can act as the dependent side on relationships to other non-owned types).

Which is not correct, see https://github.com/dotnet/efcore/issues/24535

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
HI @cjblomqvist, thanks for this to our notice. We will review it soon.
