### ISSUE TITLE
"shape is not recognized shape" does not contain parameters

### ISSUE THREAD

**Issue by tonank** [dotnet/docs#23722]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/main/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @tonank 

I'm updating this article next week, and I'll address this as well.
