### ISSUE TITLE
Add instructions on how to reset the registry hive of the experimental VS instance

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23733]
Under the existing TIP:

```
> [!TIP]
> When you run your analyzer, you start a second copy of Visual Studio. This second copy uses a different registry hive to store settings. That enables you to differentiate the visual settings in the two copies of Visual Studio. You can pick a different theme for the experimental run of Visual Studio. In addition, don't roam your settings or login to your Visual Studio account using the experimental run of Visual Studio. That keeps the settings different.
```

There should be instructions on resetting the experimental VS instance.

From #Roslyn channel in Discord:

![image](https://user-images.githubusercontent.com/31348972/114218450-b4de1080-9969-11eb-91e5-7f34632389ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Youssef1313 

Do you want to create the fix? 

Also, you've been participating here so consistently, I can add you to a team with read permissions, which will allow us to assign issues to you that you've said you're taking on.

**Comment by Youssef1313** [comment]
> Do you want to create the fix?

Sure. Will open a PR shortly.

> Also, you've been participating here so consistently, I can add you to a team with read permissions, which will allow us to assign issues to you that you've said you're taking on.

I'm okay with that too. Thanks.

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

I've added you to the team, and assigned this to you.
