### ISSUE TITLE
Instructions that include "Run menu" are outdated

### ISSUE THREAD

**Issue by JorySmith** [dotnet/docs#23738]
I was not able to follow this instruction:

 'Start without debugging from the Run menu. If you're using a command line, type dotnet run in the directory where you've created your project.'

The Run menu doesn't exist in Visual Studio now so I don't know what to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - Introduction to C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @JorySmith I just created PR #23757 to fix this. The "Start without Debugging" items is now on the "Debug" menu.
