### ISSUE TITLE
Commentary mismatched with rule

### ISSUE THREAD

**Issue by madelson** [dotnet/docs#23732]
Current:

> ❌ DISALLOWED: Removing the virtual keyword from a member
> 
> While this often is not a breaking change because the C# compiler tends to emit callvirt Intermediate Language (IL) instructions to call non-virtual methods (callvirt performs a null check, while a normal call doesn't), this behavior is not invariable for several reasons:
> 
> C# is not the only language that .NET targets.
> 
> The C# compiler increasingly tries to optimize callvirt to a normal call whenever the target method is non-virtual and is probably not null (such as a method accessed through the ?. null propagation operator).
> 
> Making a method virtual means that the consumer code would often end up calling it non-virtually.
> 
> ❌ DISALLOWED: Adding the virtual keyword to a member
> 

Suggested:

> ❌ DISALLOWED: Removing the virtual keyword from a member
> 
> ❌ DISALLOWED: Adding the virtual keyword to a member
> While this often is not a breaking change because the C# compiler tends to emit callvirt Intermediate Language (IL) instructions to call non-virtual methods (callvirt performs a null check, while a normal call doesn't), this behavior is not invariable for several reasons:
> 
> C# is not the only language that .NET targets.
> 
> The C# compiler increasingly tries to optimize callvirt to a normal call whenever the target method is non-virtual and is probably not null (such as a method accessed through the ?. null propagation operator).
> 
> Making a method virtual means that the consumer code would often end up calling it non-virtually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b482b0-6dd1-42de-5389-5b0b47823402
* Version Independent ID: 79a4adc9-b2c9-68b7-669e-2bd8d2d44faf
* Content: [Types of breaking changes - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/)
* Content Source: [docs/core/compatibility/index.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BillWagner** [comment]
@gewarren @madelson I agree, this should change as recommended above.
