### ISSUE TITLE
Clarify that hexadecimal literals are assumed to be positive values.

### ISSUE THREAD

**Issue by Treit** [dotnet/docs#23736]
The documentation on numeric literals states the following:

> The type of an integer literal is determined by its suffix as follows:
  If the literal has no suffix, its type is the first of the following types in which its value can be represented: int, uint, long, ulong.

Now consider the literal `0x80000000`. This literal does not have a suffix and the bit pattern fits into a 32-bit integer so this documentation may imply to some readers that this will be treated as a signed integer. (In other languages, PowerShell for instance, this kind of literal is indeed interpreted to be the same as System.Int32.MinValue.)

In C# the apparent rule is that hexadecimal literals are always assumed to be positive values, meaning the positive value 0x80000000 must be interpreted as an unsigned int since it is too large to fit into a signed integer.

This doesn't seem to be clearly documented and it would be good to make this more explicit.

---#### Document Details⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.** ID: 3a22464d-b60c-36c0-e4e8-b209a33b0219* Version Independent ID: cb500323-82a3-09ea-0468-dd16c9e13675* Content: [Integral numeric types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types)* Content Source: [docs/csharp/language-reference/builtin-types/integral-numeric-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/integral-numeric-types.md)* Product: **dotnet-csharp*** Technology: **csharp-language-reference*** GitHub Login: @BillWagner* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
A note: *any* (decimal, hexadecimal, and binary) literal is assumed to be a positive value.

**Comment by BillWagner** [comment]
Thanks for noting this @Treit and thanks for the fix @pkulikov
