### ISSUE TITLE
using root user or remote debugging via SSH does not work

### ISSUE THREAD

**Issue by FrankPlawetzki** [dotnet/docs#23731]
The steps in this article did not work for me. 
Instead, it worked for me using the steps from this article: https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm
The steps mentioned also have the advantage of

- no  changes to SSH demon necessary
- no remote debugging using the root user necessary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e5dc95-a3a8-1cc6-049e-773e31449079
* Version Independent ID: 171f8840-fa9a-9174-2628-f3a9f6d0915e
* Content: [Debug .NET apps on Raspberry Pi](https://docs.microsoft.com/en-us/dotnet/iot/debugging?pivots=vscode)
* Content Source: [docs/iot/debugging.md](https://github.com/dotnet/docs/blob/main/docs/iot/debugging.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@FrankPlawetzki Thanks for the heads-up! It worked at the time that I wrote it, but it's possible something changed. I'll give it a once-over, especially given that the doc you link does remove a couple steps.
