### ISSUE TITLE
UWP and CS 8.0

### ISSUE THREAD

**Issue by keithnicholson** [dotnet/docs#23730]
Is there a way to clarify whether CS 8.0 can work with UWP projects?  I have tested it using the "Configure multiple projects" settings of this document.  Seems to work well.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @keithnicholson We'll look into it.

@adegeo Do you know what TFMs are allowed in UWP apps?

**Comment by adegeo** [comment]
According to the [TFM doc](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks), uap10.0 is the UWP TFM that targets .NET 5 and I would assume uses the same version of C# that .NET 5 does. But really we would need someone from the UWP doc team to answer that.

**Comment by adegeo** [comment]
@mcleanbyron Perhaps you can answer this question.

**Comment by mcleanbyron** [comment]
I'm following up with some engineers on the Windows developer platform team, and will reply back as soon as I can with some details.

**Comment by mcleanbyron** [comment]
Here's the info I received from some engineers in the Windows developer experience team:

* UWP supports .NET Standard 2 and C# 7.3 by default. You can use the <LangVersion> element in your project file to change to a later version of C# (as demonstrated in [Sergio's blog](https://sergiopedri.medium.com/enabling-and-using-c-9-features-on-older-and-unsupported-runtimes-ce384d8debb)), but there is no guarantee that all new language features will work properly. In particular, you should expect limitations when the newer language feature requires newer .NET runtime support.
* As for TFMs supported in UWP projects, UWP apps use [.NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native) and support .NET Standard 2; they do not support .NET 5. Apparently the 'uap10.0' TFM is an older moniker for earlier versions of .NET Native. Current UWP projects use the simpler 'uap' TFM (in the <TargetPlatformIdentifier> element in the project file).

I hope this helps.

**Comment by BillWagner** [comment]
@keithnicholson This has been a great discussion. Thanks for sparking it.

I like how Sergio points to both the potential benefits, and where the pitfalls are in this unsupported scenario. 

I'll close this as an answered question.
