### ISSUE TITLE
Apostrophes in VB example comments affecting syntax highlighting

### ISSUE THREAD

**Issue by b-cpu** [dotnet/docs#23753]
The apostrophes in the VB example code comments on this page appear to be throwing off the syntax highlighting colors (since VB uses apostrophe for comment)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33df7ee-9a59-acb5-e036-fa634d98d261
* Version Independent ID: b70e8969-67b3-76bf-225c-4a2435a988bf
* Content: [Structure Statement - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/structure-statement?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vb.Structure);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.7.2);k(DevLang-VB)%26rd%3Dtrue)
* Content Source: [docs/visual-basic/language-reference/statements/structure-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/structure-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
I think this was fixed in highlight.js (which docs site depends on): https://github.com/highlightjs/highlight.js/issues/2875. The fork used in the site (which I believe is developed in https://github.com/DuncanmaMSFT/highlight.js) doesn't include the fix.

**Comment by BillWagner** [comment]
Tagging @DuncanmaMSFT per previous comment.

**Comment by Youssef1313** [comment]
@BillWagner @gewarren This can be closed now. The highlighting was fixed.
