### ISSUE TITLE
Plurality error on page 21

### ISSUE THREAD

**Issue by Gregory-Alvord** [dotnet/docs#23763]
On page 21 in the xx section the sentence fragment "...implementing contracts and types objects as a way to implement data transfer" should be "...implementing contracts and typed objects to implement data transfer."  Changed "as a way to" to "to" as the MS grammar checker told me to. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b9072f-f49f-1997-8c2e-31ef1737581b
* Version Independent ID: 5575fc58-ade8-7771-1133-126ed03c8c2f
* Content: [Migrating Modern Desktop applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-desktop/migrate-modern-applications)
* Content Source: [docs/architecture/modernize-desktop/migrate-modern-applications.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modernize-desktop/migrate-modern-applications.md)
* Product: **dotnet-architecture**
* GitHub Login: @OliaG
* Microsoft Alias: **oliag**

**Comment by sughosneo** [comment]
Hi @Gregory-Alvord , thank you for reaching out. 
As proposed changes are already merged, I am closing this issue as of now. Please feel free to reopen it, if needed.
