### ISSUE TITLE
Missing Images on page 7

### ISSUE THREAD

**Issue by Gregory-Alvord** [dotnet/docs#23762]
On page 7 there are to image references that probably should be the images themselves. There reference a D: drive.

```
![](D:\source\dotnet-architecture\ebook-private-resources\modernize-desktop\content\media\why-modern-applications\desktop-to-modern.png)

![](D:\source\dotnet-architecture\ebook-private-resources\modernize-desktop\content\media\why-modern-applications\modern-to-desktop.png)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0a6b42-ef3e-ae99-aede-0d42b4219c36
* Version Independent ID: 20184cae-5444-6d9d-a1d4-5b150f8865a0
* Content: [Why modern desktop applications](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-desktop/why-modern-applications)
* Content Source: [docs/architecture/modernize-desktop/why-modern-applications.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modernize-desktop/why-modern-applications.md)
* Product: **dotnet-architecture**
* GitHub Login: @OliaG
* Microsoft Alias: **oliag**

**Comment by gewarren** [comment]
I see two images on page 7 of the PDF. Are these the images you're not seeing? Could you try to download the PDF again?

![image](https://user-images.githubusercontent.com/24882762/114475908-18f11680-9bae-11eb-8e31-df706aa1e966.png)

**Comment by Gregory-Alvord** [comment]
Yes there are two images. There is also a reference to a D: Drive image.

**Comment by Youssef1313** [comment]
@Gregory-Alvord I downloaded the PDF and I can see the images as @gewarren states. Would you be able to re-download and/or try another PDF reader (I tried on Edge):

![image](https://user-images.githubusercontent.com/31348972/123652634-bf9f9780-d82c-11eb-8232-4cecb72dcc19.png)
