### ISSUE TITLE
A doesn't implement IA that has property of type IB, despite implementing B which implements IB

### ISSUE THREAD

**Issue by cjblomqvist** [dotnet/docs#23770]
See code below which doesn't compile. From the docs I can't understand why, since B "is a" (implements) IB, which should satisfy IA? Or am I doing something completely wrong?

(I want to keep A/B as specific as possible, while still implementing IA/IB in order to pass it to a method that takes in IA)

See https://stackoverflow.com/q/67071040/856559 for cross-post.

```csharp
public interface IA {
    public string Field { get; set; }
    public IB B { get; set; }
}

public interface IB {
    public string OtherField { get; set; }
}

public class A : IA {
    public string Field { get; set; }
    public B B { get; set; }
}

public class B : IB {
    public string OtherField { get; set; }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e982a51-097f-688f-710c-1dfcf313da5e
* Version Independent ID: 8691f826-62cb-da0a-8460-a38aa2bc2a70
* Content: [Interfaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/)
* Content Source: [docs/csharp/programming-guide/interfaces/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/interfaces/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @cjblomqvist 

The replies on StackOverflow answer the question well: The method that implements a member of an interface must exactly match that member definition. Your example code doesn't. There is a conversion from `B` to `IB`, but it's not an identity conversion.

I'll close this as an answered question.

**Comment by cjblomqvist** [comment]
Cool! Thanks for taking the time to look at it!
