### ISSUE TITLE
i can't find any correlation between the coordinates obtained from the model and the actual stop sign of the example

### ISSUE THREAD

**Issue by MaxFranz** [dotnet/docs#23774]
hi,
I am trying to learn Objcet detection with ML.net
Unfortunately, but maybe it is my problem, I can't find any correlation between the coordinates obtained from the model...
"**Predicted Boxes:
Top: 89.453415, Left: 481.95343, Right: 724.8073, Bottom: 388.32385, Label: Stop-Sign, Score: 0.99539465**"
and the actual Stop signal in the example image.
Where do the axes start from? do the top, left , right, bottom coordinates of the output refer to the TOP,LEFT and BOTTOM,RIGHT corners of the bounding box? Obviously I have considered the actual size of the image, doing the proportion to get the real coordinates but still I don't find any correlation.

Thanks

Massimo Franceschelli

![test-image1](https://user-images.githubusercontent.com/16940984/114558145-aabe5980-9c6a-11eb-9897-cb5af0dd9bfd.jpeg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a4f3b7-a2a6-760a-534b-22788ba77b5c
* Version Independent ID: 1bee7901-164f-d9a7-9e7b-fd0ba55ad42e
* Content: [Tutorial: Detect objects in images with Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder)
* Content Source: [docs/machine-learning/tutorials/object-detection-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **brachtma**

**Comment by luisquintanilla** [comment]
Adding @JakeRadMSFT @LittleLittleCloud.

**Comment by luisquintanilla** [comment]
Hi @MaxFranz 

The coordinates are those of the bounding box. Images for object detection are normalized at a 800 (width) x 600 (height). Therefore, you need to scale these coordinates to your actual image size. Here's one way you could do it. 

In this sample `input-image` is the image you've provided in this issue. 

```csharp
var image = new Image.FromFile("input-image.jpeg")

var top = image.Height * 89 / 600
var bottom = image.Height * 388 / 600
var left = image.Width * 481 / 800
var right = image.Width * 724 / 800
var height = Math.Abs(bottom-top)
var width = Math.Abs(right-left)
```

I've hardcoded the dimensions you provided, but you can take those from the `Top`, `Bottom`, `Left`, `Right` bounding box properties. The `image.Height` and `image.Width` are the actual dimensions of the image. 

Hope this helps
