### ISSUE TITLE
`langword` attribute

### ISSUE THREAD

**Issue by yeremee** [dotnet/docs#23772]
Why is the `langword` attribute not described for the `see` element?

![2021-04-13_14-17-38](https://user-images.githubusercontent.com/25692333/114544721-ae9aad80-9c63-11eb-9319-0c5c03a27a72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
href should also be included.

**Comment by BillWagner** [comment]
Thanks for noting this @yeremee 

I see that @Youssef1313 has already created a PR to address it. Thanks there as well.
