### ISSUE TITLE
Typographical error - "subscribe" misspelt as "subcribe" in a diagram 

### ISSUE THREAD

**Issue by amanjeetsingh** [dotnet/docs#23785]
Change "subcribe" to "subscribe"

![image](https://user-images.githubusercontent.com/7122931/114676084-45db3000-9d4c-11eb-83ac-2470b160a993.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f400f15-ef79-b691-09b8-1b1e46a474d6
* Version Independent ID: 59361774-0b1c-83f9-70cd-03af85ab7ad8
* Content: [Dapr at 20,000 feet](https://docs.microsoft.com/en-gb/dotnet/architecture/dapr-for-net-developers/dapr-at-20000-feet)
* Content Source: [docs/architecture/dapr-for-net-developers/dapr-at-20000-feet.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/dapr-at-20000-feet.md)
* Product: **dotnet-architecture**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
@EdwinVW @amolenk Hey! Can you help update this please?

**Comment by EdwinVW** [comment]
@nishanil I'll create a fix a.s.a.p.
