### ISSUE TITLE
Support polymorphic deserialization without hand made deserialization

### ISSUE THREAD

**Issue by lanwin** [dotnet/docs#23786]
I guess what most people (like me) looking for when they loop up this doc part, is not how to "Support polymorphic deserialization" with hand made deserialization code, instead they assume to use the serializer. As I read the page I was pretty disappointed that this could only be done with custom deserialization code until I found this issue https://github.com/dotnet/runtime/issues/31051#issuecomment-537840364. So I would like to suggest to change the docs to reflect that, so others are not disappointed. 

What I would expect:
```csharp
            var clone = reader; // cause its a struct
			
            if (clone.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }

            clone.Read();
            if (clone.TokenType != JsonTokenType.PropertyName)
            {
                throw new JsonException();
            }

            string propertyName = clone.GetString();
            if (propertyName != "TypeDiscriminator")
            {
                throw new JsonException();
            }

            clone.Read();
            if (clone.TokenType != JsonTokenType.Number)
            {
                throw new JsonException();
            }

            TypeDiscriminator typeDiscriminator = (TypeDiscriminator)clone.GetInt32();
            return typeDiscriminator switch
            {
                TypeDiscriminator.Customer => JsonSerializer.Deserialize<Customer>(ref reader, options),
                TypeDiscriminator.Employee => JsonSerializer.Deserialize<Employee>(ref reader, options),
                _ => throw new JsonException()
            };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#support-polymorphic-deserialization)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@steveharter Should we change the sample converter code or offer this as an alternative?

**Comment by lanwin** [comment]
> @steveharter Should we change the sample converter code or offer this as an alternative?
> cc @layomia

From my point of view the rest of the document explains very well how to write converters with custom serialization code, so this example should be explain the best match for this scenario. -> change

**Comment by layomia** [comment]
I think @tdykstra's suggestion of making this an alternative approach makes sense since there's a downside (from https://github.com/dotnet/docs/pull/24132): 

> A disadvantage of this method is you can't pass in the original options instance that registers the converter to `Deserialize`. Doing so would cause an infinite loop, as explained in [Required properties].
