### ISSUE TITLE
Using HttpClient 

### ISSUE THREAD

**Issue by albertly** [dotnet/docs#23783]
https://docs.microsoft.com/en-us/dotnet/standard/async-in-depth
https://docs.microsoft.com/en-us/dotnet/standard/async-in-depth#deeper-dive-into-tasks-for-an-io-bound-operation
Deeper Dive into Tasks for an I/O-Bound Operation
In Code Snippet

 var client = new HttpClient();

However, according to the documentation about HttpClient **it is not correct usag**e:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. **Below is an example using HttpClient correctly**.
> 
> C#
> 
> public class GoodController : ApiController
> {
>     private static readonly HttpClient HttpClient;
> 
>     static GoodController()
>     {
>         HttpClient = new HttpClient();
>     }
> }

Did I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88cc5f21-0b4b-f33c-b7fc-96bb9c95ddcf
* Version Independent ID: 46697309-d4fd-1cd9-f8ff-e4577be08003
* Content: [Async in depth](https://docs.microsoft.com/en-us/dotnet/standard/async-in-depth#deeper-dive-into-tasks-for-an-io-bound-operation)
* Content Source: [docs/standard/async-in-depth.md](https://github.com/dotnet/docs/blob/main/docs/standard/async-in-depth.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi 👋 @albertly
Thank you so much for posting this issue. We really appreciate it.

> Did I miss something?

No, you did not miss something. You are correct, this article does go against the guidance for `HttpClient`, but this article is a bit dated and the sample source code could use a bit of clean up in that regard. If you're interested in updating this article and sample source code, I'd be happy to review it. I'm marking this issue as up-for-grabs - thanks again.
