### ISSUE TITLE
Allow inferred type constraints in where clause

### ISSUE THREAD

**Issue by seblaf1** [dotnet/docs#23781]
I think it would be great if the language would allow types definitions with multiple generics to support inferring just like methods do (_for example_: `DoSomething<T>(T instance)` can be called like so `DoSomething(myInstance);`, we don't have to be verbose and type `DoSomething<MyType>(myInstance)`).

Well, similarly, I would like inferring in the where clause for this particular case as well:
`StateHandler<TState, TResult> : StateHandler where TState : State<TResult> where TResult : class`

It would be nice to be able to specify a StateHandler simply by specifying TState, and have TResult inferred, such as we would write: `StateHandler<MyState>`, not `StateHandler<MyState, MyStateResult>`, which is redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74dfcde5-aa2b-1128-fa29-f198a6e437b7
* Version Independent ID: 59aeccf5-364c-77a8-88dc-cb529b76aebc
* Content: [where (generic type constraint) - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint)
* Content Source: [docs/csharp/language-reference/keywords/where-generic-type-constraint.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/where-generic-type-constraint.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This is better suited as a discussion in dotnet/csharplang repository. @BillWagner Can you move there?

**Comment by Youssef1313** [comment]
> It would be nice to be able to specify a `StateHandler` simply by specifying `TState`, and have `TResult` inferred, such as we would write: `StateHandler<MyState>`, not `StateHandler<MyState, MyStateResult>,` which is redundant.

What if there is two definitions for `StateHandler`? `StateHandler<TState, TResult>` and `StateHandler<TState>`.

**Comment by BillWagner** [comment]
Thanks @seblaf1 

As @Youssef1313 points out, this should be routed to [dotnet/csharplang](https://github.com/dotnet/csharplang).

I'll let you write the proposal, as it looks like this is related to #23780. I think you can capture the scenario you want to address more accurately than I can.
