### ISSUE TITLE
Generic type constraint new() should offer customization

### ISSUE THREAD

**Issue by seblaf1** [dotnet/docs#23780]
I think it would make lots of sense if C# would allow new() type constraints customization. It would not only allow developers to create instances of a class without specifying a provider function, it would also allow them to ensure a generic type is non-abstract, without having to provide default constructor.

By customization, I mean something such as new(int, int), new(CustomType, bool), ect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c4db08-089a-4022-f672-7951590e075d
* Version Independent ID: 197f1799-2fc6-6f82-ada7-eb3abdc2da50
* Content: [new constraint - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-constraint)
* Content Source: [docs/csharp/language-reference/keywords/new-constraint.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/new-constraint.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@seblaf1 This is a request for a new feature in the language. It should be added in [dotnet/csharplang](https://github.com/dotnet/csharplang)

I'll close this, because the docs accurately reflect the current product.
