### ISSUE TITLE
Typo in Top Level Statements tutorial

### ISSUE THREAD

**Issue by johnradke** [dotnet/docs#23792]
Under the "Respond with a random answer" section, it says "This array has 12 answers that are affirmative, six that are non-committal, and six that are negative" but the counts are actually 11, 5, and 5, respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2939b6-ad9e-4116-c805-8f19ed994c31
* Version Independent ID: ad23d124-a491-2b4f-3c51-0ed5d38d7eba
* Content: [Top-level statements - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements)
* Content Source: [docs/csharp/whats-new/tutorials/top-level-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/top-level-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @johnradke 

I see @pkulikov has already submitted a fix.  I'll review that and merge it shortly.

In the future, if you find these quick fixes, you can click the "edit" button (it looks like a pencil), and submit a PR with the fix. That may be quicker than describing where the typo is.

Thanks again.
