### ISSUE TITLE
Are the first two bullet points interchanged?

### ISSUE THREAD

**Issue by DeborahK** [dotnet/docs#23799]
The documentation says:
```
Encapsulation Ability to organize internal complexities of a system into single objects.
Abstraction Ability to access or restrict access to properties, methods, or members of something encapsulated.
```
Aren't these backwards? Seems that it should be:

`Abstraction` Ability to organize internal complexities of a system into single objects
`Encapsulation` Ability to access or restrict access to properties, methods, or members of something encapsulated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/object-oriented-programming)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/intro-to-csharp/object-oriented-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@DeborahK This has come up several times, with valid arguments on both sides:

See #23543, #23308, and #22690.

What I've learned is that these terms a re related, and many developers (probably including me) have a fuzzy definition of the terms.

If you can suggest better wording that would put this to rest, I'd be very grateful.

**Comment by DeborahK** [comment]
@BillWagner 

I liked your prior suggestion:
"For our purposes here, I would focus on the following key points for this terms:

Abstraction focuses on identifying the important components of a system. You'll use abstractions when you create classes to implement important behavior for your program.
Encapsulation focuses on hiding the internal complexities of a system. You'll use encapsulation when you determine what the public interface for a class should contain."

Numerous blog posts seem to repeat the same definitions. So I went back to books, such as "Object-Oriented Modeling and Design". In that book:

"Abstraction is the selective examination of certain aspects of a problem. The goal of abstraction is to isolate those aspects that are important for some purpose and suppress those aspects that are unimportant. Abstraction must always be for some purpose, because the purpose determines what is and is not important."

"Encapsulation (also information hiding) consists of separating the external aspects of an object, which are accessible to other objects, from the internal implementation details of the object, which are hidden from other objects."

How about something like this:

`Abstraction` Modeling the relevant attributes and interactions of entities as classes to define an abstract representation of a system.
`Encapsulation` Hiding the internal state and functionality of an object and only allowing access through a public set of functions.

A few notes:

- `relevant` is important in the Abstraction definition as it implies fitness for a purpose.
- Since `interface` is yet another thing, I suggest leaving out that word from this definition.

**Comment by BillWagner** [comment]
Thanks for the comments and thoughts @DeborahK 

I've opened #23817 to update these definitions.
