### ISSUE TITLE
Roslyn API docs aren't up-to-date

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23815]
It doesn't have version 3.8 and 3.9.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70df7db1-1817-8296-deab-28f9fd2221bb
* Version Independent ID: 588093eb-1ed5-da2e-0664-29b822b3de77
* Content: [SyntaxToken.RawKind Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxtoken.rawkind?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/SyntaxToken.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/SyntaxToken.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Youssef1313** [comment]
Strangely, these version exists in FrameworksIndex folder:

https://github.com/dotnet/roslyn-api-docs/tree/main/dotnet/xml/FrameworksIndex

**Comment by BillWagner** [comment]
Ping @jmarolf 

Versions 3.7.0, 3.8.0, and 3.9.0 are all built, but aren't live in the OPS system. Which should I make live?

**Comment by jmarolf** [comment]
3.9 at least should be made live. I would need to do a diff across the API versions but I see no reason that they all shouldn't be up

**Comment by BillWagner** [comment]
I updated the configuration in OPS. These versions are live now.

**Comment by Youssef1313** [comment]
Thanks @BillWagner. There is still one issue here, Version 3.7.0 is duplicated, and one of them seems to refer to 3.9.0:

![gif](https://user-images.githubusercontent.com/31348972/115104094-91612a00-9f56-11eb-91bb-5e134502f41a.gif)
