### ISSUE TITLE
Bar in Formatting try/with expressions

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#23813]
Hello,

In [Formatting try/with expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-trywith-expressions), nothing is really mentioned about the bar in the with clauses.
Should it always be there?

You could omit it in some scenarios like:
```fsharp
try
    foo()
with ex -> recover ()
```

The current sample in the guide also has the clause under the with keyword, should that always be the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Yeah, it's not necessary in the single case, which offhandedly I'd say is the most common case.

I guess since it's a pattern match and we do have the `|` in each case, we should be consistent here.
