### ISSUE TITLE
Guidance for long if condition

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#23825]
Hello, 

Are there any guidelines on what to do with long, multiline conditions in [Formatting if expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-if-expressions)?

Something like:
```fsharp
    if List.exists
        (function
        | CompExpr _ -> true
        | _ -> false)
        es then
        shortExpression ctx
    else
        expressionFitsOnRestOfLine shortExpression longExpression ctx
```

If nothing comes to mind I would propose something like:
```fsharp
if
    List.exists
        (function
        | CompExpr _ -> true
        | _ -> false)
        es 
then
    shortExpression ctx
else
    expressionFitsOnRestOfLine shortExpression longExpression ctx
```

Where `if` and `then` align and the expression has one indent.
This is the safest option you have in case the expression is any `try/with` or a `match` or any other horribly long construct.
Personally, I would avoid multiline expressions and go for an intermediate let binding.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by nojaf** [comment]
Some other nice examples from the wild:
```fsharp
            if
              // Don't support implicit [<ReflectedDefinition>] on generated members, except the implicit members
              // for 'let' bound functions in classes.
              (not v.IsCompilerGenerated || v.IsIncrClassGeneratedMember) &&

              (// Check the attributes on any enclosing module
               env.reflect ||
               // Check the attributes on the value
               HasFSharpAttribute g g.attrib_ReflectedDefinitionAttribute v.Attribs ||
               // Also check the enclosing type for members - for historical reasons, in the TAST member values
               // are stored in the entity that encloses the type, hence we will not have noticed the ReflectedDefinition
               // on the enclosing type at this point.
               HasFSharpAttribute g g.attrib_ReflectedDefinitionAttribute v.TopValDeclaringEntity.Attribs) then

                ()
```

```fsharp
        if sourceCode.EndsWith("\n")
               && not
                  <| formattedSourceCode.EndsWith(Environment.NewLine) then
                return formattedSourceCode + Environment.NewLine
            elif
                not <| sourceCode.EndsWith("\n")
                && formattedSourceCode.EndsWith(Environment.NewLine)
            then
                return formattedSourceCode.TrimEnd('\r', '\n')
            else
                return formattedSourceCode
```

```fsharp
if
    Uri.Compare
        (
            foo,
            bar,
            UriComponents.Host ||| UriComponents.Path,
            UriFormat.UriEscaped,
            StringComparison.CurrentCulture
        ) = 0
then
    ()
else
    ()
```

```fsharp
    if match! (node.Attribute(XName.Get "GSettingsSchemaDir"), String.IsNullOrWhiteSpace s) with
       | (null, false) ->
           node.Add(XAttribute(XName.Get "GSettingsSchemaDir", s))
           true
       | (a, false) ->
           a.Value <- s
           true
       | (null, true) -> false
       | (a, true) ->
           a.Remove()
           true
    then config.Save file
```

**Comment by cartermp** [comment]
I think what you propose is reasonable, although I would say that it should come with guidance that says something to the effect of:

"If you have a condition that is this long, first consider refactoring it into a separate function and calling that function instead"
