### ISSUE TITLE
The authors of this documentary confused “preorder” with “postorder”.

### ISSUE THREAD

**Issue by Wefersi** [dotnet/docs#23822]
[It appears that in the fifth paragraph of this article (How to iterate through a directory tree), that beginning with “When you manually walk a directory tree”, the authors of this documentary confused “preorder” with “postorder”. Clearly, in a directory tree, files correspond to information in it, while the organization by subfolders allows the information as a whole to be structured. At the directory tree, the files in each directory correspond to the tree’s root and the other hand, subdirectories to subtrees. Therefore, go through the folds in the preorder, according to the classic work of Computing, The Art of Computer Programming, Donald Knuth, Vol. 1 / Fundamental Algorithms, Sections 2.3.1 Traversing Binary Trees and 2.3.2 Binary Tree Representation of Trees, “Preorder traversal is: visit the root, traverse the left subtree, and finally traverse the right subtree” what IT IS JUST THE OPPOSITE to what was stated in that paragraph, i.e., “that the entire tree is traversed in the current folder before iterating in the files that are directly in the folder itself “. Analogously, we can say something similar concerning what the same paragraph stated for postorder.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25601a0f-eb3c-bf18-04d1-f371f5dc4341
* Version Independent ID: ce7a72d0-6156-f1f8-56ee-9774d93d6d3d
* Content: [How to iterate through a directory tree - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/file-system/how-to-iterate-through-a-directory-tree.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Wefersi 

I've added this to our backlog to address. I've also added the "up for grabs" label, if any contributors want to make an update in the interim.

**Comment by Wefersi** [comment]
Hi Wagner

After forwarding this material, I noticed that its title had the first word
without the initial letter “T”, omitted during the copy-paste process. So
you can correct that omission by replacing “he authors of this documentary
...” with “The authors of this documentary ... “.

Best Regards
Wellington F. Silva

Em seg., 19 de abr. de 2021 às 11:31, Bill Wagner ***@***.***>
escreveu:
