### ISSUE TITLE
Add recommendation about capitalization

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/docs#23835]
As far as i know in C#

1. classes should use an uppercase as the first letter (convention / expected: `MyAwesomeClass` and not expected `myAwesomeClass`) 
2. private fields should be lowercase (convention / expected: `private myField  `and not expected `private MyField`). 
3. Regarding private fields the [C# Coding Style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) recommends to use `_myPrivateField` while AFAIR other parts of the documentation recommend not to not use "_" at the start of a field or variable.

I propose that information about capitalization of fields is added to the page or linken to a ressource where this is explained.

I briefly searched for the conventions, rules regarding capitalization (use of uppercase and lowercase) but i did not find any recomendation 

- the [C# coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) makes no statement regarding capitalization of classes, properties or fields 
- the [dotnet standard design guideline on capitalization](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) is a general guideline for any language and therefore not specific for C#
- [code-analysis/style-rules/naming-rules](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules) contains an example for an ".editorconfig file contains a naming convention that specifies that public properties, methods, fields, events, and delegates must be capitalized".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df47593-8586-e54e-fb74-cf3a96262d40
* Version Independent ID: b464cd68-4713-c848-e9a7-30705d17e6f7
* Content: [Fields - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/fields.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/fields.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @surfmuggle 

I think the right location for this kind of information is to extend the [coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions) article.

The casing rules are in the runtime's style guide (referenced above). They use the terms "camelCase" and "PascalCase" to describe the capitalization rules. These should be defined in the C# coding conventions articles.
