### ISSUE TITLE
Autoreplaced ".NET Core" with ".NET 5" misunderstandings

### ISSUE THREAD

**Issue by sdudnic** [dotnet/docs#23838]
Replacing automatically ".NET Core" with ".NET 5" in the article gave some misunderstandings: 

> .NET 5 supports side-by-side installation of **different versions of the .NET 5** runtime on the same machine. This side-by-side installation allows multiple services on the same server, each of them on its **own version of .NET 5** (or .NET Core 2.1 or 3.1).

Consider renaming in different versions of ".NET Core" instead of ".NET 5"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET 5 and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/main/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tdykstra Do you want to take this one?

**Comment by tdykstra** [comment]
Will do.

**Comment by tdykstra** [comment]
Good point, and thanks for the suggestion, @sdudnic!

**Comment by sdudnic** [comment]
don't see any changes in the document page online...

**Comment by tdykstra** [comment]
Publication of PR changes to the live site isn't immediate, but it's there now.

**Comment by sdudnic** [comment]
sometimes is seem to be a complete mess for a novice starting leardning Core: 
**.NET Core** is also **.NET 5+** but also now just **.NET**, 
but **.NET _Framework_** does not mean the _Framework_ of _.NET_(that is .NET _Core_, and also _.NET 5_ or +)

Also we would say, **.NET Standard** would be the _.NET classical Framework_, but in fact is the API between all .NET frameworks.... uff...

**Comment by tdykstra** [comment]
>.NET Core is also .NET 5+ but also now just .NET,

Yes, it can be confusing. The rationale behind the naming is explained in the [.NET 5 what's new article](https://docs.microsoft.com/dotnet/core/dotnet-five):

> .NET 5.0 is the next major release of .NET Core following 3.1. We named this new release .NET 5.0 instead of .NET Core 4.0 for two reasons:
>
> * We skipped version numbers 4.x to avoid confusion with .NET Framework 4.x.
> * We dropped "Core" from the name to emphasize that this is the main implementation of .NET going forward. .NET 5.0 supports more types of apps and more platforms than .NET Core or .NET Framework.
>
> ASP.NET Core 5.0 is based on .NET 5.0 but retains the name "Core" to avoid confusing it with ASP.NET MVC 5.

In most of the current documentation we use the new naming, but in this one we're trying ".NET Core/5+" to see if it helps avoid the possibly more confusing comparison between ".NET vs. .NET Framework".  This article presents extra challenges because it's about comparing two [implementations of .NET](https://docs.microsoft.com/dotnet/standard/glossary#implementation-of-net), which is not necessary in most documentation aimed at people who are new to .NET.
