### ISSUE TITLE
There should be a note in the Naming Convention section explaining how this advice has changed from before

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#23834]
The original advice (and what many remember) is only available via the wayback machine. 
https://web.archive.org/web/20120819123954/http://msdn.microsoft.com/en-us/library/hh191443.aspx

> - Change the method signature in the following ways.
>   -   Mark the method with the Async or async modifier.
>    - Change the return type from Byte() to Task(Of Byte()) in Visual Basic or from byte[] to Task<byte[]> in C#.
>    - The task is a promise to provide a byte array when the asynchronous process is complete. For more information about async return types, see Async Return Types (C# and Visual Basic).
>    - By convention, add the suffix "Async" to the method name.

A note indicating the official guidance has changed would remove some of the additional confusion regarding this topic. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd97c63-2887-1891-fb08-9cd78659c2db
* Version Independent ID: 1ae4494a-ca0b-a1da-cdcf-522ef79e0fc5
* Content: [The Task Asynchronous Programming (TAP) model with async and await (C#)'](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model)
* Content Source: [docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hello again @StingyJack 

Can you explain where you think the guidance changed? The referenced article has the same information under "Naming Conventions".

**Comment by StingyJack** [comment]
No it doesnt. 

The original guidance (that I linked from the wayback - and have screenshotted in case someone tries to delete or alter it) says 

> By convention, **you add the suffix "Async" to the names of methods that have an Async or async modifier**.
> You can ignore the convention where an event, base class, or interface contract suggests a different name. For example, you shouldn’t rename common event handlers, such as button1_Click.

The current article says 
> By convention, **methods that return commonly awaitable types (for example, Task, Task<T>, ValueTask, ValueTask<T>) should have names that end with "Async**". Methods that start an asynchronous operation but do not return an awaitable type should not have names that end with "Async", but may start with "Begin", "Start", or some other verb to suggest this method does not return or throw the result of the operation.

> You can ignore the convention where an event, base class, or interface contract suggests a different name. For example, you shouldn't rename common event handlers, such as OnButtonClick.

Somewhere along the way that naming convention changed, I dont know when but it did so subtly enough that many missed it, including popular code analysis providers.  What I'm asking for just a note that states "the guidance was X and has been refined to Y",

**Comment by BillWagner** [comment]
Thanks for clarifying @StingyJack 

I'm closing this as by-design.

The changed text was deliberate and clarified earlier language.  See #11379 for details.  The new language differs from the old in two observable scenarios:

1. `async void` methods. Async void methods are discouraged except when necessary to conform to event handlers or other APIs. In those cases, you probably can't add the `Async` suffix anyway
1. Methods that don't require the `async` modifier (because they do not contain an `await`), but return a type that should be awaited. This was discussed at length in #22626. 

The new text is more correct. If code analysis providers have changed behavior because of this change, you should reach out to them.

**Comment by StingyJack** [comment]
Before it said "suffix Async when the `async` keyword was used", now it's "suffix Async when `Task` (etc) return types are used.

Changing the condition with which to apply the convention  isn't a clarification of the original text. I get that the new text is intended and by design. I'm not asking that be changed, just an addendum that acknowledges this guidance has been updated and how. Historical aspect is incredibly important when trying to understand code.
