### ISSUE TITLE
Syntax highlighting for VB.Net

### ISSUE THREAD

**Issue by Finemechanic** [dotnet/docs#23848]
Could anyone fix syntax highlighting for VB.Net? It apparently handles comments (with ' symbol) incorrectly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beec841-2fc0-e46f-b3da-9c921b22d427
* Version Independent ID: 988848ea-f798-3bec-aba0-a33e656ace82
* Content: [Collections - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/collections)
* Content Source: [docs/visual-basic/programming-guide/concepts/collections.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/concepts/collections.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
Pinging @DuncanmaMSFT

**Comment by IEvangelist** [comment]
Hi 👋 @Finemechanic
Thank you so much for posting this issue. We really appreciate it. I'll work on getting this addressed.

**Comment by Youssef1313** [comment]
@IEvangelist fwiw, I believe this is fixed in the upstream highlightjs library.

**Comment by IEvangelist** [comment]
> @IEvangelist David Pine FTE fwiw, I believe this is fixed in the upstream highlightjs library.

I'm well aware, thank you @Youssef1313.

**Comment by Youssef1313** [comment]
@BillWagner @IEvangelist @gewarren This can be closed now. The highlighting was fixed.
