### ISSUE TITLE
Add new SYSLIB warnings

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#23856]
Update this page based on https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md.

- [x] SYSLIB0003 - see https://github.com/dotnet/runtime/pull/57035/files
- [x] SYSLIB0013
- [x] SYSLIB0014
- [x] SYSLIB0015
- [x] SYSLIB0016
- [x] SYSLIB0017 - see https://github.com/dotnet/runtime/pull/50941/files
- [x] SYSLIB0018 - see https://github.com/dotnet/runtime/pull/50941/files
- [x] SYSLIB0019
- [x] SYSLIB0020
- [x] SYSLIB0021 - see https://github.com/dotnet/runtime/pull/52303/files
- [x] SYSLIB0022 - see https://github.com/dotnet/runtime/pull/52366/files
- [x] SYSLIB0023 - see https://github.com/dotnet/runtime/pull/52373/files
- [x] SYSLIB0024 - see https://github.com/dotnet/runtime/pull/52014/files
    * This PR also adds new obsoletion attributes using SYSLIB003 and SYSLIB0011
- [x] SYSLIB0025 - see https://github.com/dotnet/runtime/pull/50951/files
- [x] SYSLIB0026 - see https://github.com/dotnet/runtime/pull/53891/files
- [x] SYSLIB0027 - see https://github.com/dotnet/runtime/pull/54562/files
- [x] SYSLIB0028 - see https://github.com/dotnet/runtime/pull/54562/files
- [x] SYSLIB0029 - see https://github.com/dotnet/runtime/pull/54886/files
- [x] SYSLIB0030 - see https://github.com/dotnet/runtime/pull/54886/files
- [x] SYSLIB0031 - see https://github.com/dotnet/runtime/pull/55592/files
- [x] SYSLIB0032 - see https://github.com/dotnet/runtime/pull/56664/files
- [x] SYSLIB0033 - see https://github.com/dotnet/runtime/pull/57002/files
- [x] SYSLIB0034 - see https://github.com/dotnet/runtime/pull/57301/files
- [x] SYSLIB0035 - see https://github.com/dotnet/runtime/pull/57301/files
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48bcb45e-7c1e-8c8e-cf73-3a4afb71ec62
* Version Independent ID: c4971f9b-4496-dfa5-8c88-f09daff995b8
* Content: [Obsolete features in .NET 5+ - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/syslib-obsoletions)
* Content Source: [docs/core/compatibility/syslib-obsoletions.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/syslib-obsoletions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by jeffhandley** [comment]
@gewarren I want to confirm that you plan to review the `list-of-diagnostics.md` file and gather all of the new diagnostics from there to produce the breaking change document, and that (so long as we accumulate the diagnostics there) we do not need to submit separate issues for each new obsoletion. Is that correct?

If that's the case, would it still be helpful for us to link to this issue from each PR that introduces a diagnostic?

**Comment by gewarren** [comment]
@jeffhandley Yes, that's correct, and you don't need to submit separate issues. But I think it would be helpful to link to this issue from the PRs, as a sign that there's a new one to add to the breaking changes doc. Thanks!

**Comment by KalleOlaviNiemitalo** [comment]
The SYSLIB0027-SYSLIB0031 links aren't rendering correctly at <https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/obsolete-apis-with-custom-diagnostics>. Please use parentheses around the URI-references: for example. `[SYSLIB0027](../../../../fundamentals/syslib-diagnostics/syslib0027.md)` rather than `[SYSLIB0027][../../../../fundamentals/syslib-diagnostics/syslib0027.md]`.
