### ISSUE TITLE
About sample code variable style problem

### ISSUE THREAD

**Issue by jonny-xhl** [dotnet/docs#23868]
Is the style of the variable in the following code block in the documentation OK?
```csharp
public static void Main()
{
    Console.WriteLine ("\nReflection.MemberInfo");
    // Gets the Type and MemberInfo.
    Type MyType = Type.GetType("System.IO.File");
    MemberInfo[] Mymemberinfoarray = MyType.GetMembers();
    // Gets and displays the DeclaringType method.
    Console.WriteLine("\nThere are {0} members in {1}.",
        Mymemberinfoarray.Length, MyType.FullName);
    Console.WriteLine("{0}.", MyType.FullName);
    if (MyType.IsPublic)
    {
        Console.WriteLine("{0} is public.", MyType.FullName);
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c487065-f3f0-eb57-d456-a1f9a383c080
* Version Independent ID: 6c15d7e5-f53e-489d-3a88-06451d0dc692
* Content: [Viewing Type Information](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/viewing-type-information)
* Content Source: [docs/framework/reflection-and-codedom/viewing-type-information.md](https://github.com/dotnet/docs/blob/main/docs/framework/reflection-and-codedom/viewing-type-information.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
No they should be named better. The code for that whole article would need to be migrated and updated.
