### ISSUE TITLE
Search box incorrectly encodes special characters

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2386]
When I use the search box in the upper right corner to search for a phrase that contains special characters (including spaces), those special characters are showing encoded in the same search box on the search results page.

For example, when I search for "overloading equals()", I'm correctly sent to https://docs.microsoft.com/en-us/search/index?search=overloading+equals%28%29&scope=.NET, but the search box on that page now says "overloading+equals%28%29". This means I can't easily refine my search and try again if the results are not what I expected.

![](https://user-images.githubusercontent.com/287848/27011862-901182b6-4ec5-11e7-841e-5e786cfd1e6c.png)

![](https://user-images.githubusercontent.com/287848/27011863-9b480862-4ec5-11e7-9bfd-0ba57f6d7654.png)

**Comment by mairaw** [comment]
Thank you @svick. I've open an internal issue for us to track this [1016988](https://mseng.visualstudio.com/CSI/_workitems?id=1016988&fullScreen=false&_a=edit)

**Comment by BillWagner** [comment]
@svick I tried this today, and it appears to be fixed.  Can you verify and close if so.

**Comment by svick** [comment]
Yeah, this seems to be fixed, closing.
