### ISSUE TITLE
try-convert installation before upgrade-assistant

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [dotnet/docs#23873]
Hi,
I think upgrade-assistant tool can now automatically install try-convert and is no longer a pre-requisite. However the page mentions that try-convert be installed by running the required commands.

_This tool depends on try-convert. In order for the tool to run correctly, you must install the try-convert tool for converting project files to the new SDK style. If you already have try-convert installed, you may need to update it instead (since upgrade-assistant depends on version 0.7.212201 or later)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf49988-a3ca-a140-76f7-e5aff6ffb309
* Version Independent ID: bf952cc5-836b-90c5-5f80-83baa3b796dd
* Content: [Overview of the .NET Upgrade Assistant - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview)
* Content Source: [docs/core/porting/upgrade-assistant-overview.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for this feedback! I'll get it fixed.
