### ISSUE TITLE
Group clause section of the page

### ISSUE THREAD

**Issue by PostalMike** [dotnet/docs#23885]
[Enter feedback here]

Use the group clause to produce a sequence of groups organized by a key that you specify. The key can be any data type. For example, the following query creates a sequence of groups that contains one or more Country objects and whose key is a char value.

I get it -- you're taking the first letter of the name and grouping this way.  I have no idea of the context, why this would be done.  So that does enter confusion.

Perhaps it should be mentioned it's grouping on the first letter of each country's name?

Also, above this the term 'continuation' is mentioned -- I'd recommend not using a new term until the section that explains it in better detail.  Scrolling down 2-3 more topics, 'Continuation' is taken up and explained well.

FYI -- this is the first lineup on LINQ that I ever really got anything out of.

C#

Copy
var queryCountryGroups =
    from country in countries
    group country by country.Name[0];
For more information about grouping, see group clause.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888d4d4e-48ca-db9d-e36d-006f4aeeb83b
* Version Independent ID: ac336cb4-251f-51d1-c35e-cc3693677f41
* Content: [Query expression basics (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-expression-basics)
* Content Source: [docs/csharp/linq/query-expression-basics.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/query-expression-basics.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @PostalMike 

I'll add this to our backlog to clarify these statements. 

I've also added the "up for grabs" label, in case a community member wants to issue a PR in the interim.
