### ISSUE TITLE
CLI commands topics: Can these be improved?

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2388]
This started as a discussion with @mairaw on Slack pertaining to the CLI command docs.

* Dashes in command names are 😖 very confusing.
* Do our definitions of "arguments," "options," and "parameters" make sense in light of commonly-used definitions of these terms? (i.e., Should we organize the sections of these docs a bit differently?)

## Dashes in command names (e.g., "dotnet-restore" vs. "dotnet restore")

I was informed that this was done to follow the way that Git shows its commands, but dashes in commands aren't used anywhere: They aren't shown this way in topics outside of the command topics. They aren't described this way among devs in chat rooms. They don't appear this way in GH issue/PR discussions. *Most importantly*, they aren't used this way on the command line. The result of having dashes in the commands is only one thing imo: *confusing.* Is there support for removing the dashes from commands in the CLI command docs?

## "Arguments," "options," and "parameters" 

Conventional definitions AFAICT are:

* **Argument:** *Anything* after the command. I think it's fair to say that anything separated by a space after invoking the command is "an argument." I didn't think of this at the time I was discussing with @mairaw on Slack, but later it occurred to me that `public static void Main(string[] args)` means exactly this is the case. It's just a string array of whatever is fed into the app.
* **Option:** Modifies a command. Might be a "required option" or an "optional option." Often requires a parameter to supply additional information to the option.
* **Parameter:** Anything that provides information to a command or option.

Currently, we're doing this ...

* Name
* Synopsis
* Description
* Arguments (which are more explicitly "command parameters" AFAICT)
* Options (These are actually also "arguments," sometimes with parameters and sometimes without them. Since they're "arguments," it doesn't make much sense to show them under a 2nd level heading along side our "Arguments" section, which is also a 2nd level heading in the topics.)
* Examples

There are a few options (pardon the pun :grinning:) that would potentially improve things here:

### Bring "arguments" in line with current definitions by re-labeling them "Command parameters," which is probably what they really are.

* Name
* Synopsis
* Description
* Command parameters
* Options
* Examples

### Since "command parameters" and "options" are all arguments, they could all fall under the "Arguments" heading.

* Name
* Synopsis
* Description
* Arguments
  - Command parameters
  - Options
* Examples

### Since options are easily split into *required* and *optional* categories, they can be split out. This would be helpful to devs to know which ones are absolutely required versus those are are truly optional.

* Name
* Synopsis
* Description
* Arguments
  - Command parameters
  - Required options
  - Optional options
* Examples

### Examples

To show a few examples of how the last two scenarios would look, here's sample layout for `dotnet publish`:

* Arguments
   - Command parameters
      * `PROJECT`
   - Required options
      * None
   -  Optional options
      * `-c|--configuration <CONFIGURATION>`
      * `-f|--framework <FRAMEWORK>`
      * `-h|--help`
      * `--manifest <MANIFEST_FILE>`
      * `-o|--output <OUTPUT_DIRECTORY>`
      * `-r|--runtime <RUNTIME_IDENTIFIER>`
      * `--self-contained [<true|false>]`
      * `-v|--verbosity <LEVEL>`
      * `--version-suffix <VERSION_SUFFIX>`

For `dotnet store` ...

* Arguments
   - Command parameters
      * None
   - Required options
      * `-f|--framework <FRAMEWORK>`
      * `-m|--manifest <MANIFEST_FILE>`
      * `-r|--runtime <RUNTIME_IDENTIFIER>`
    - Optional options
      * `--framework-version <FRAMEWORK_VERSION>`
      * `-h|--help`
      * `-o|--output <OUTPUT_DIRECTORY>`
      * `--skip-optimization`
      * `--skip-symbols`
      * `-v|--verbosity <LEVEL>`
      * `--working-dir <INTERMEDIATE_WORKING_DIRECTORY>`

## Empty (or "None") sections shown

There's a tendency to not show a heading when no entries exist under it (i.e., the section heading is just left out of the topic); however, I think that's unhelpful in this case. I understand well the concept of "economy" in technical documentation, but anything can be taken too far, and I think this is one of those cases. If there are no command parameters, or no required options, or no optional options, nothing makes it more clear than going ahead and showing the section with the entry of "None." For example ...

* Arguments
  - Command parameters
    * Parameter1
    * Parameter2
  - Required options
    * None
  - Optional options
    * Option1
    * Option2

## Thoughts on changes?

I made one (probably) helpful change for the 2.0 round of updates to alphabetize the options. Are there opportunities here to make further improvements?

**Comment by bleroy** [comment]
What dashes in command-lines? Unless I'm missing something, there should never be anything like `dotnet-restore` in the documentation, unless you're explaining how commands are resolved and/or how to write a new one.

**Comment by GuardRex** [comment]
@bleroy See the topic title and  *Name* section of ...

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

... the dotnet commands table in ...

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet

... and the TOC ...

https://github.com/dotnet/docs/blob/master/docs/toc.md

It's not very common, but I still think it's painful to see them shown this way anywhere. @mairaw can explain further ... it had something to do with the way Git shows them. There's some method to the madness, but I find it confusing from a consumption perspective. I can't be the only one wondering why this dash is shown in these commands when it has no bearing on actually using them (i.e., one never types them with a dash; doing so results in a :boom:).

**Comment by bleroy** [comment]
Totally agree then. All these should be without dashes.

**Comment by mairaw** [comment]
I agree with you with the removal of the dashes. Let's do it. Z explained to me the rationale behind this when we were creating those. I think it had to do with how Git shows them but also because these originally were creating man pages for the commands, which is no longer the case AFAIK.

For "Arguments," "options," and "parameters":
- I think it should be consistent with the CLI interface
- I don't think we should change arguments to command parameters
- I'd avoid creating an empty header level since H3s don't render on the right nav
- Most CLI docs (AWS,docker, etc.) just have Options, but I'd be ok if we wanted to break it down into Optional and Required.
- I think azure cli incorrectly calls options as parameters IMO: https://docs.microsoft.com/en-us/cli/azure/billing/invoice. So maybe an opportunity to improve our CLI docs across the company. 

/cc @livarcocc

**Comment by GuardRex** [comment]
Cool, so thus far we're just thinking to ...
* Drop the dashes
* Split Options into *Required Options* and *Optional Options* where there are required options. It's only a few of them, but it should make it clearer what the dev must do to get the command to work in those cases.

I won't make changes until we've heard from [@]livarcocc and others. Then, these updates will go in on https://github.com/dotnet/docs/pull/2387 for 2.0. I'd like to make these changes on Friday (6/23) unless more time is needed for comment.

**Comment by mairaw** [comment]
I sent you an email about the plan for the 2.0 docs:
- We'll add the new topics for 2.0 in their final location now. I'll change my WIP PR for dotnet store.
- We'll add tabbed views on the current CLI commands when that feature is available 
- We'll add proper content version when that feature is available to us

We could also add a command node (with or without an article attached) in the TOC to say Commands reference.

**Comment by GuardRex** [comment]
> We'll add the new topics for 2.0 in their final location now.

I'll move the ones I'm working to a PR for `master`. (They all have the includes for "this is preview" on them and in their titles and H1s.)

> We could also add a command node 

Add the node to *docs/core/tools*? It's not a concern to place them down another level ... so deep in the TOC? (just curious/thinking aloud)

**Comment by omajid** [comment]
A couple of random comments:

> I was informed that this was done to follow the way that Git shows its commands

It is a historical thing in git. Early versions of git did have the dash in commands too. That is, both `git checkout` and `git-checkout` exited once.

> Currently, we're doing this ...
>    Name
>    Synopsis
>    Description
>    Arguments (which are more explicitly "command parameters" AFAICT)
>    Options 
>    Examples

These look very very similar to the standard set of sections used in man pages, aside from Arguments. In git, for example, these are also grouped under Options.

**Comment by mairaw** [comment]
We renamed the CLI commands to not have dashes. I suggest we file individual issues for other changes if there still inconsistencies. Thanks @guardrex!
