### ISSUE TITLE
`curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin` doesn't install dotnet5, but dotnet3.1 instead.

### ISSUE THREAD

**Issue by Vinigas** [dotnet/docs#23886]
`curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin` doesn't install dotnet5, but dotnet3.1 instead.

Meaning this tutorial is outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to Raspberry Pi](https://docs.microsoft.com/en-us/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
I apparently fixed this sometime previously.
