### ISSUE TITLE
--prerelease option only available from .NET 5 or later

### ISSUE THREAD

**Issue by PaulUpson** [dotnet/docs#23896]
Following the inclusion of the `--prerelease` option (#21495) the statement that the docs still apply to .NET Core 2.x SDK and later versions is false.

Took me a while understand why I couldn't find it on .NET Core 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that -- I'll add a note that this option is available starting with .NET 5 SDK.
