### ISSUE TITLE
Update for .NET 6 config changes

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#23904]
Related to https://github.com/dotnet/roslyn/issues/49250.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55
* Version Independent ID: 128f9903-971d-6a66-a2cb-9b12acbc55e7
* Content: [Code analysis in .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview)
* Content Source: [docs/fundamentals/code-analysis/overview.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Adding more context for this work:
1. We ended up implementing the changes as per https://github.com/dotnet/roslyn/issues/49250#issuecomment-736879786 in .NET 6
2. Valid values of `AnalysisMode` are now `none`, `default`, `minimum`, `recommended` and `all`. We support back compat by treating `AllEnabledByDefault` as `all` and `AllDisabledByDefault` as `none`
3. Valid values of `AnalysisLevel` can now be either simple values or compound values:
   1. Existing simple values as per https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysislevel (plus `6` and `6.0`)
   2. Compound values with a _prefix_ and _suffix_ parts separated by a `-`. Prefix part should have simple values as per previous bullet. Suffix values can have any of the `AnalysisMode` values. For example, `5.0-none`, `latest-all`, `6-minimum`, etc. The primary reason for supporting these compound values is to allow us to eventually deprecate `AnalysisMode` completely and have a single property `AnalysisLevel` whose values can represent the entire matrix of supported values.
4. We now also support category specific `AnalysisModeXXX` and `AnalysisLevelXXX` properties. For example, users can specify `AnalysisModeStyle`, `AnalysisLevelStyle`, `AnalysisModeDesign`, `AnalysisLevelDesign`, etc. for each category. `AnalysisModeXXX` and `AnalysisLevelXXX` properties default to the category agnostic `AnalysisMode` and `AnalysisLevel` property values.
5. For .NET 5, `AnalysisMode` and `AnalysisLevel` only affected CAxxxx rules. With the new feature work in .NET 6, these properties also affect the IDExxxx code style rules when [EnforceCodeStyleInBuild](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild) is true. We have a special category `Style` for these rules so `AnalysisModeStyle` and `AnalysisLevelStyle` can be set to bulk configure and enable/disable IDExxxx code style rules.

Suggest looking at following source files for implementation details:
1. https://github.com/dotnet/roslyn-analyzers/blob/main/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
2. https://github.com/dotnet/roslyn/blob/main/src/CodeStyle/Tools/Program.cs
3. https://github.com/dotnet/sdk/blob/c9afbfa5d23ecfc25ce67a61be0fd41be9e14b52/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L15-L46

**Comment by mavasani** [comment]
Tagging @Youssef1313 @jmarolf @mikadumont if any of you are interested in writing up this documentation.

**Comment by mavasani** [comment]
Also tagging @vatsalyaagrawal

**Comment by mavasani** [comment]
Another note: The features mentioned here are the ones that primarily drive the new code-analysis github action: https://github.com/dotnet/code-analysis#analysis-rules

**Comment by gewarren** [comment]
Related to #22248.
