### ISSUE TITLE
Roslyn API docs contains a duplicate version

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23902]
Thanks @BillWagner. There is still one issue here, Version 3.7.0 is duplicated, and one of them seems to refer to 3.9.0:

![gif](https://user-images.githubusercontent.com/31348972/115104094-91612a00-9f56-11eb-91bb-5e134502f41a.gif)

_Originally posted by @Youssef1313 in https://github.com/dotnet/docs/issues/23815#issuecomment-821775752_

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

I just made the update. I'll close this once I've verified that it's live.

**Comment by BillWagner** [comment]
Monikers are updated. This is now fixed.
