### ISSUE TITLE
date in provided code should be currentDate

### ISSUE THREAD

**Issue by JonRobertson** [dotnet/docs#23914]
The project at [https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio](url) declares the date variable as "currentDate", not "date". The code on this page should be corrected to use the same variable name (currentDate).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582
* Version Independent ID: aeb94c3f-50e0-eb84-e469-f6eb778bad62
* Content: [Debug a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@JonRobertson Thanks for reporting that.

@adegeo Do you want to take this as a follow-up to your OKR PR? It might be better to just change back from currentDate to date in the C# code; otherwise there are several screenshots that have to be redone also.

**Comment by adegeo** [comment]
I've finished the VSCode and Visual Studio versions. I need to get the MacOS screenshots though.
