### ISSUE TITLE
The block of code shows an error 代码块显示错误

### ISSUE THREAD

**Issue by KevinZonda** [dotnet/docs#23912]
代码块显示错误
应当显示为代码，但是显示为字符串

>The block of code shows an error
>It should appear as code, but as a string

```
:::code language="csharp" source="snippets/character-encoding-introduction/csharp/PrintStringChars.cs" id="SnippetPrintChars":::
```
![image](https://user-images.githubusercontent.com/33132228/113910196-752ff100-97d0-11eb-9fe9-b6548ee9e341.png)

其在英文文档工作正常

![image](https://user-images.githubusercontent.com/33132228/113910251-87aa2a80-97d0-11eb-9fb3-20ebd11344b9.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66
* Version Independent ID: d53a0764-9f27-16b3-c40a-9627dd1bcc0d
* Content: [.NET 中的 character 编码简介](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/character-encoding-introduction)
* Content Source: [docs/standard/base-types/character-encoding-introduction.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/character-encoding-introduction.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@KevinZonda thank you for reporting this.

@JasonCard It looks like the :::code moniker isn't rendering on translated pages. I checked chinese, german, and french. English is rendering correctly.

**Comment by JasonCard** [comment]
@KevinZonda @adegeo Thank you for reporting this issue and bringing it to my attention. I'll look into this and escalate as needed.

**Comment by adegeo** [comment]
@JasonCard I'll close this issue since it's on your side now.
