### ISSUE TITLE
A minor typing error in the text.

### ISSUE THREAD

**Issue by ruhelaanurag** [dotnet/docs#23923]
It looks like a typo to me in the line below, "will it" is to be replaced with "it will".

```Only if the C# compiler cannot match the method call to an original method on Derived ***will it*** try to match the call to an overridden method with the same name and compatible parameters```

new line should be:
```Only if the C# compiler cannot match the method call to an original method on Derived ***it will*** try to match the call to an overridden method with the same name and compatible parameters```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc0929c-f565-df82-43d0-0a1066b42ca3
* Version Independent ID: ab208ff8-7478-564f-9f24-5fdee99d1643
* Content: [Versioning with the Override and New Keywords - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/versioning-with-the-override-and-new-keywords.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @ruhelaanurag 

That sentence is grammatically correct, but is not the best wording. 

I've put this in our backlog to update when we update that topic. I've also added the "up for grabs" label if anyone wants to submit a fix in the interim.
