### ISSUE TITLE
Change ".NET Core CLI" to ".NET CLI" for dotnetcli identifier

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23925]
This is not specific to dotnet/docs. But opening here since issues in MicrosoftDocs/feedback usually get stale and also that @IEvangelist is looking currently into similar issues.

It looks like ".NET CLI" is now more natural than ".NET Core CLI" since the introduction of .NET 5.0:

![image](https://user-images.githubusercontent.com/31348972/115995219-b00c9400-a5da-11eb-97a5-ec58a9c2119d.png)

I have no idea whether this is related to `highlight.js` or is separate. Feel free to redirect to the appropriate team.

**Comment by IEvangelist** [comment]
I'm curious what @BillWagner @gewarren @tdykstra and @CamSoper think about labelling this as `.NET CLI` instead of `.NET Core CLI`. In fact, that is probably a product team question - @BethMassi what do you think?

**Comment by tdykstra** [comment]
We've been changing the docs to refer to .NET CLI, so changing the title on code boxes makes sense to me.

**Comment by BethMassi** [comment]
Correct. It's just ".NET CLI" starting with .NET 5.

**Comment by IEvangelist** [comment]
> Correct. It's just ".NET CLI" starting with .NET 5.

The docs platform team has no concept of versioning individual code snippets. It's an all or nothing kind of change. In other words, we cannot dynamically change the code snippet slug to deterministically toggle the label based on .NET 5 or not - the docs platform simply does not have support for that.

So we're good with changing it to ".NET CLI" for all previous version docs too? I just want to be sure, before I propose the changes.

**Comment by IEvangelist** [comment]
Private pull request into the docs platform here:
https://ceapex.visualstudio.com/Engineering/_git/docs-ui/pullrequest/191625

**Comment by Youssef1313** [comment]
Looks like the PR is merged:

![image](https://user-images.githubusercontent.com/31348972/116530687-98852200-a8de-11eb-8bdd-6256a8f1339d.png)

Thanks @IEvangelist for the very quick fix ❤️ 
Closing the issue.
