### ISSUE TITLE
Difference between Structure elements and Structure Members

### ISSUE THREAD

**Issue by sougata12** [dotnet/docs#23921]
[Enter feedback here]

In the MSDN documentation [((https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures-and-classes)](url) where they discuss similarities of classes and structures, the following is stated:

> Both have members, which can include constructors, methods, properties, fields, constants, enumerations, events, and event handlers. However, do not confuse these members with the declared elements of a structure.

Can someone please explain that for a structure in VB, what is the difference between an element of a structure and a member of a structure? The documentation quoted above says that we should not confuse them... and I am very much confused. The reason for my confusion is that in the page Declared Elements(https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/declared-elements/), they have mentioned literally everything that can be declared as "elements" - variables, constants, enumerations, classes, structures, modules, interfaces, procedures, procedure parameters, function returns, external procedure references, operators, properties, events, and delegates. So if everything is an element then what is a member?

I posted this question in StackOverflow but did not get an answer. I was advised to raise the issue here. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 949becea-bb41-232a-a1d9-32f1696a3a14
* Version Independent ID: c4113513-ea71-da4f-defc-00accdca6556
* Content: [Structures and Classes - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures-and-classes)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/structures-and-classes.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/data-types/structures-and-classes.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @sougata12 

I've checked with Kathleen, and that sentence just seems wrong to both of us. I opened #23938 to address this issue.

**Comment by KathleenDollard** [comment]
I wanted to apologize for the confusion this caused. There are differences in structures and classes primarily in when the contents are copied or used in place. However, I think this sentence fails to explain any of that, and that the remainder of that page does. 

Thank you again for bringing this to our attention. Docs have been updated to drop that sentence, and it will show up on the site as soon as it flows through the system.

**Comment by sougata12** [comment]
Thank you for updating the document @BillWagner and @KathleenDollard
