### ISSUE TITLE
Documentation doesn't mention deleting the Program.cs 

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/docs#23922]
`dotnet new console -n templatepack -o .`

The above will also create a `Program.cs` file that you don't mention deleting nor is it listed further down when you show contents of the working folder.

![image](https://user-images.githubusercontent.com/357219/115987488-7db16580-a5df-11eb-8893-238141efb07b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d0e779-2a93-d2b8-3fb0-8c88812a4fc7
* Version Independent ID: 2e4ef5da-1b4b-a1d7-7ec8-6169360bf315
* Content: [Create a template pack for dotnet new - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack)
* Content Source: [docs/core/tutorials/cli-templates-create-template-pack.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-template-pack.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi 👋 @StevenTCramer
Thank you so much for posting this issue. We really appreciate it. I've labeled this issue as up-for-grabs, and I'd be happy to review a pull request add the details about remove the _Program.cs_.
