### ISSUE TITLE
Add a summary at the beginning enumerating possible string comparisons

### ISSUE THREAD

**Issue by ClarkFrazier** [dotnet/docs#23932]
Add a summary at the beginning enumerating possible string comparisons.  Introducing additional comparison types in the middle or near the end results in a muddy and unclear document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ecfc18-477b-f792-4136-2feb46bbc5d3
* Version Independent ID: 82f53ae8-a9d4-dea9-5acd-6d9202a40882
* Content: [How to compare strings - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings)
* Content Source: [docs/csharp/how-to/compare-strings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/compare-strings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 230269](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230269)

**Comment by BillWagner** [comment]
Thanks for noting this @ClarkFrazier I've added it to our backlog to address when we next update this article.

**Comment by BillWagner** [comment]
Fixed in #40030
