### ISSUE TITLE
Typo on ErrorLog example

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/docs#23940]
Looks like there is a typo in the example for `ErrorLog`:
```xml
<ErrorLog>MyConfiguration.ruleset</ErrorLog>
```

I would expect something more like:
```xml
<ErrorLog>report.json</ErrorLog>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#errorlog)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good point @jairbubbles 

I've opened #23953 to fix this issue.
