### ISSUE TITLE
Not clear enough definitions make impression that LOH and 2nd Generation are the same things.

### ISSUE THREAD

**Issue by rustamhajiyev** [dotnet/docs#23944]
First of all, thank you for the article, it's quite informative.
Nevertheless, I find definitions like "Large objects are always allocated in generation 2." not clear enough. I think that the statements from the [Fundamentals of garbage collection | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap) article are more appropriate. 

> Newly allocated objects form a new generation of objects and are implicitly generation 0 collections. However, if they are large objects, they go on the large object heap (LOH), which is sometimes referred to as generation 3. Generation 3 is a physical generation that's logically collected as part of generation 2.

> Objects on the large object heap (which is sometimes referred to as generation 3) are also collected in generation 2.

Could you please align these articles and make the definitions clearer.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819bcbc3-b2f7-b1eb-2e45-0f19c8da797c
* Version Independent ID: ed840139-0331-77b1-5645-0cac6c16edcf
* Content: [Large object heap (LOH) on Windows](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap)
* Content Source: [docs/standard/garbage-collection/large-object-heap.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/large-object-heap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@rustamhajiyev Thank you for the feedback!

**Comment by rustamhajiyev** [comment]
Thanks a lot!
