### ISSUE TITLE
The statement is wrong

### ISSUE THREAD

**Issue by goyzhang** [dotnet/docs#23951]
`Binary compatible changes are also source compatible changes.`

There is no superset between binary and source compatible change.

Example:
```Csharp
    class Foo
    {
        public void Bar() { }
        public void Bar(int a) { } //Adding this method is binary compatible but becomes ambiguous for source
    }
//Client side:
      static void Main(string[] args)
      {
          Handle(new Foo().Bar);
      }
      static void Handle(Action<int> act) { }
      static void Handle(Action act) { }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7025d71b-df42-b8ad-3e31-20a480a5d652
* Version Independent ID: a05ae06d-91e1-d1f8-0194-e7830f5c880e
* Content: [Version and update considerations for C# developers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/version-update-considerations)
* Content Source: [docs/csharp/whats-new/version-update-considerations.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/version-update-considerations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good point @goyzhang 

I've assigned this to me for next month.
