### ISSUE TITLE
Updating local tool

### ISSUE THREAD

**Issue by Mahesh-MSFT** [dotnet/docs#23957]
Hi,

I am having trouble in using the updated tool in local development.

I have following code structure.
.
├── .config
├── My-local-tool
├── My-sample-app-that-uses-tool
├── My-another-app

As part of tool development, I'll frequently change code and test it using `My-sample-app-that-uses-tool`. Note process will be iterative.

I am following process as below for every code change in the tool.

1.  Run `dotnet pack` in `My-local-tool` folder.
2.  Run `dotnet tool uninstall <my-tool-name>` in the root folder.
3.  Run `dotnet new tool-manifest` in the root folder.
3.  Run `dotnet tool install --add-source ./My-local-tool/nupkg <my-tool-name>` in the root folder.
4.  Run `dotnet <my-tool-name>` in the folder My-sample-app-that-uses-tool

However, changes in my tool - like `hello world` to `hi world!` don't appear when used from My-sample-app-that-uses-tool.

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9eeaac3-a5c0-5739-1a3e-8b47c8b916f3
* Version Independent ID: 4fe6c87c-9fb5-33fb-7835-2e0b511dc5b3
* Content: [Tutorial: Install and use .NET local tools - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use)
* Content Source: [docs/core/tools/local-tools-how-to-use.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/local-tools-how-to-use.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
@Mahesh-MSFT Hi there. Can you investigate the `My-sample-app-that-uses-tool` and see if the tool is:

1. Cached there (is there a `.tool` folder or something?)
2. Is the app referencing some sort of hash of the tool that is regenerated?
3. What is in the `%userprofile%\.dotnet\tools` folder?

**Comment by Mahesh-MSFT** [comment]
thanks @adegeo . i managed to git rid of the problem by running `dotnet nuget locals all --clear`.
