### ISSUE TITLE
Deadlock on returning a non-async stream from SocketsHttpHandler.ConnectCallback

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/docs#23960]
Not sure if this is an issue in the code or the documentation.

**Issue description**

On returning a non-async-capable stream from SocketsHttpHandler.ConnectCallback, HttpClient deadlocked. I don't think a toy example will reproduce; it got through several requests before getting stuck. HttpClient assumes that whatever stream it gets is completely async-capable which is in fact true of NetworkStream but is not true of arbitrary streams. There is no indication in the documentation that a completely async-capable stream must be returned, and _it is surprising that it deadlocks_. Normally it's safe for an async I/O call to become sync; it's just slower. HttpClient has a different opinion.

While I haven't a reason* to run HttpClient through any of these, there are streams for which the only reasonable implementation of ReadAsync() just calls Read() and is synchronous and if you really need an async read you have to sacrifice another thread. Also, the default implementation of ReadAsync() in IO.Stream does indeed call Read().

*I needed to force HttpClient to be sync when it refused to be due to another bug elsewhere.

**Target framework**

- [x] .NET 5.0
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by adegeo** [comment]
If it's related to documentation, do you have the specific article that is misrepresenting how this should work? If it's a bug with .NET, this issue should probably be reported on https://github.com/dotnet/sdk/issues Would you like me to transfer the issue there?

**Comment by adegeo** [comment]
Ahh OK. I'll transfer this to the api docs repo.

**Comment by adegeo** [comment]
Well apparently I don't have rights to that repo 😢 @gewarren can you do it?

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#6740
