### ISSUE TITLE
Mistype in the PublicSign docs

### ISSUE THREAD

**Issue by 333fred** [dotnet/docs#23977]
The page says: "The PublicSign and PublicSign options are mutually exclusive." I believe it meant to say "The PublicSign and DelaySign options are mutually exclusive."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c990f37-3995-687b-b421-3346d2ff186f
* Version Independent ID: f3a67ca1-0a4a-cc52-3ffc-ff279fc4355d
* Content: [C# Compiler Options - security options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/security)
* Content Source: [docs/csharp/language-reference/compiler-options/security.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/security.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @333fred 

I see @Youssef1313 has already opened a PR to address this.
