### ISSUE TITLE
Where is WSL installation instructions?

### ISSUE THREAD

**Issue by nitrologic** [dotnet/docs#23979]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux Distributions](https://docs.microsoft.com/en-nz/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

WSL runs a linux kernel (in a VM based on your version), just use the instructions for the kernel. For example the Ubuntu WSL, use the normal install instructions that adds the MS package feed and installs through APT. 

Hope this answers your question. Let me know if there is anything else I can help you with.
