### ISSUE TITLE
improve nullability code sample

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#23981]
the doc sample code is currently
public static bool IsValid(Person? person)
{
    return person != null && !string.IsNullOrEmpty(person.Name);
}
but should [simplify] be
public static bool IsValid(Person? person)
{
    return !string.IsNullOrEmpty(person?.Name);
}
or even [better]
public static bool IsValid(Person? person) => !string.IsNullOrEmpty(person?.Name);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0471f98c-f5cd-00d2-a705-396682f73bcb
* Version Independent ID: a24b862d-c462-a040-8470-9771c74c4e6f
* Content: [! (null-forgiving) operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving)
* Content Source: [docs/csharp/language-reference/operators/null-forgiving.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/null-forgiving.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Opened #23982 to simplify the example
