### ISSUE TITLE
Expression unit 

### ISSUE THREAD

**Issue by Eubank777** [dotnet/docs#23984]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ffa86c-7505-ed3e-b8ec-a20a1ce9869f
* Version Independent ID: 0ffb7e92-4cce-736b-eefc-5086be635f9e
* Content: [Compiler Error CS1003](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1003?f1url=%3FappId%3Droslyn%26k%3Dk(CS1003))
* Content Source: [docs/csharp/misc/cs1003.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1003.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Eubank777 I'm not sure what you meant with the title of this issue. Can you add more details?
