### ISSUE TITLE
Typo 'surpress' in sidebar menu and page title

### ISSUE THREAD

**Issue by jnm2** [dotnet/docs#23987]
Couldn't find where to edit this.

![image](https://user-images.githubusercontent.com/8040367/116583819-bd7c9380-a8e4-11eb-834e-df6c1001b539.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5024fa30-1120-04be-76f7-3bf77a94cfa1
* Version Independent ID: 500270dc-2a10-f593-23da-a1baa6893c2a
* Content: [Surpress emitting localsinit flag - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/skip-localsinit)
* Content Source: [proposals/csharp-9.0/skip-localsinit.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/skip-localsinit.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Opened #23994 to fix this.
