### ISSUE TITLE
How to solve this problem? see 

### ISSUE THREAD

**Issue by MaMo77570** [dotnet/docs#24006]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c946d7-649b-44e4-49a9-543565904d18
* Version Independent ID: df4263c1-477a-3c32-9abe-3fcb850e6c1b
* Content: [Compiler Error CS1061](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1061.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Hi @MaMo77570
I've opened a PR to update the article. You can view the updated article [here](https://github.com/dotnet/docs/blob/55b000ea5082ce63998c65833524b72d3c285db3/docs/csharp/language-reference/compiler-messages/cs1061.md). It should be live in a few days after the PR gets merged.

Let me know if the updated article is still not clear.
Thanks.

**Comment by MaMo77570** [comment]
Ok , and thank you for your email.

**Comment by BillWagner** [comment]
Thanks for noting this @MaMo77570 And thanks for the fix @Youssef1313 

I'll review the changes and merge them shortly.
