### ISSUE TITLE
What about `short`/`Int16`?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24011]
So many other int types here but not an int16

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a41d02-3084-c31e-98ed-2bd786c7a301
* Version Independent ID: 31a20696-f326-63c3-77d1-f3cfc0aa589c
* Content: [Protobuf scalar data types - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by sughosneo** [comment]
Hi @StingyJack, thank you for reaching out. 

gRPC/Protobuf doesn't support 16-bits integer. For the list of supported scalar value types, please refer [Scalar Value Types - Protobuf Language Guide (proto3)](https://developers.google.com/protocol-buffers/docs/proto3#scalar) or  [Supported Scalar Value Types](https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-5.0#scalar-value-types)

**Comment by shirhatti** [comment]
To add to reply above, protobuf uses a variable length encoding for integers. Assuming your goal was to optimize the wire transmission, forcing a smaller width integer isn't needed.

**Comment by StingyJack** [comment]
This document describes the difference in type systems and offers suggestions for other primitive types but it does not cover short/int16.  

Data lost from a narrowing conversion is the concern. I don't always have control over  the existing model types. Best I can come up with is when the model property is a short and the incoming value is > short.MaxValue to throw an exception. Curious to hear about alternative approaches.

**Comment by shirhatti** [comment]
> Data lost from a narrowing conversion is the concern. I don't always have control over the existing model types. Best I can come up with is when the model property is a short and the incoming value is > short.MaxValue to throw an exception. Curious to hear about alternative approaches.

I was about to suggest something along those lines. @JamesNK anything to add?

**Comment by erjain** [comment]
Considering the original issue is answered and it's open for a very long, this can be closed now.

**Comment by StingyJack** [comment]
@erjain - This was opened to get the documentation updated to include the appropriate advice. Its not a support issue that can be resolved when a solution can be given.

**Comment by erjain** [comment]
Sure @StingyJack.

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
