### ISSUE TITLE
time zone offset, but not just time zone

### ISSUE THREAD

**Issue by spring1975** [dotnet/docs#24016]
Please don't reference a time zone _offset_ as simply a time zone.
"the following converters serialize and deserialize JSON that uses Unix epoch format with or without time zone (values such as /Date(1590863400000-0700)/ or /Date(1590863400000)/)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-core-3-1#specify-date-format)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@spring1975 Thanks for the suggestion, the update should be on the site tomorrow.
