### ISSUE TITLE
Is "finalization queue" actually a queue?

### ISSUE THREAD

**Issue by pedrobarbs** [dotnet/docs#24012]
I'm studying some aspects of C# language, and I stumble across a issue with the name "Finalization queue" when speaking about finalizers. As a I've researched when a class implements a finalizer, it goes straight to the finalization queue as it is instanciated. When the GC finds a object with a single reference which is a finalization root reference, this object will be moved to the fReacheble queue in order to be finalized. But it doesn't mean that the finalization queue is actually a pool instead of a queue? As it transfers objects to fReacheble queue in a non deterministic order?

Thanks in advance.

**Comment by BillWagner** [comment]
ping @Maoni0 

Can you answer the above question?

**Comment by Maoni0** [comment]
the non-deterministic-ness of finalization comes from the fact that GC decides when to clean up your object after it's eligible to be reclaimed therefore you don't know when your finalizer will be called. it's not related to how the finalization data structure is implemented. I have a blog entry that writes about the [internals](https://devblogs.microsoft.com/dotnet/finalization-implementation-details/) of finalization.

**Comment by BillWagner** [comment]
Thanks @Maoni0 

I'll close this as an answered question.

**Comment by pedrobarbs** [comment]
Thanks y'all! I apareciate those shared knowleges @Maoni0! Great article.
