### ISSUE TITLE
Wrong type definition for IDataView

### ISSUE THREAD

**Issue by lbosquett** [dotnet/docs#24029]
Hi, I think that the type definition here is wrong because IDataView is a interface

> ML.NET uses the **IDataView class** as a flexible, efficient way of describing numeric or text tabular data. IDataView can load 
either text files or in real time (for example, SQL database or log

Should be:

> ML.NET uses the **IDataView interface** as a flexible, efficient way of describing numeric or text tabular data. IDataView can 
load either text files or in real time (for example, SQL database or log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [Tutorial: Categorize support issues - multiclass classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Thanks @lbosquett for raising this issue and @Youssef1313 for putting in the PR.
