### ISSUE TITLE
Environment.NewLine Property example update

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dotnet/docs#24035]
In [Environment.NewLine Property](https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline), the example itself doesn't use string interpolation and I think could be updated to use that and would make the example become more clear and then also align with tutorials such as the [visual studio c# tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio). Happy to change it if the file is somewhere but I assume these are not on github.
@BillWagner @tdykstra

**Comment by tdykstra** [comment]
The code is on GitHub (locations shown below) and you can submit a PR, but (a) the current code has the advantage of requiring Environment.Newline to be spelled out only once for 3 line breaks and (b) changing only C# would make that snippet out of sync with the C++ and VB ones.

https://github.com/dotnet/dotnet-api-docs/blob/main/samples/snippets/csharp/VS_Snippets_CLR/Environment.NewLine/CS/newline.cs

https://github.com/dotnet/dotnet-api-docs/blob/main/samples/snippets/cpp/VS_Snippets_CLR/Environment.NewLine/CPP/newline.cpp

https://github.com/dotnet/dotnet-api-docs/blob/main/samples/snippets/visualbasic/VS_Snippets_CLR/Environment.NewLine/VB/newline.vb

**Comment by BenjaminMichaelis** [comment]
With that, is this a worthwhile change then?

**Comment by tdykstra** [comment]
I think it could be worthwhile but I would change it to one instance of NewLine, something like "line 1{NewLine}line2". That would require updating the intro text for the example, which you can find here - https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Environment.xml#L1611
