### ISSUE TITLE
Create an article that details `DOTNET_` prefixed env variables

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#24039]
Create an article detailing environment variables prefixed with `DOTNET_`, their possible values, and their meaning:

Non-test relates results based on this [grep.app search](https://grep.app/search?q=DOTNET_&case=true&filter[repo][0]=dotnet/runtime&filter[lang][0]=C%23).

- [PhysicalFileProvider](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs#L24)
- [HttpConnectionSettings](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionSettings.cs#L18)
- [GlobalizationMode](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.cs#L12)
- [GlobalizationMode.Windows](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Windows.cs#L13)
- [SockteAsyncEngine](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L25)
- [LocalAppContextSwitches](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/LocalAppContextSwitches.cs#L18)
- [Dbg](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Caching/src/System/Runtime/Caching/Dbg.cs#L14)
- [FileStreamHelpers](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.cs#L10)
- [DotNetReferenceAssembliesPathEnv](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyModel/src/Resolution/DotNetReferenceAssembliesPathResolver.cs#L10)
- [PathHelper](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/PathHelper.cs#L43)
- [RegexLWCGCompiler](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexLWCGCompiler.cs#L16)
- [PoolingAsyncValueTaskMethodBuilder](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilder.cs#L18)
- [DiagnosticsHandler / Settings](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L274) 
- [TlsOverPerCoreLockedStasksArrayPool<T>](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L331)

Inspired by https://github.com/dotnet/docs/pull/24040

**Comment by gewarren** [comment]
For .NET 6 preview 4, all .NET environment variables are prefixed with DOTNET_ (see https://github.com/dotnet/runtime/pull/50507). Is this issue to create a single reference for all of them? Or is it for a specific area? We already have a bunch scattered throughout the docs, e.g. https://docs.microsoft.com/en-us/dotnet/core/run-time-config/#environment-variables. (https://github.com/dotnet/docs/pull/23844 changes all of those to have the DOTNET_ prefix.)

**Comment by IEvangelist** [comment]
Yeah, I was thinking it would be nice to have a single article that brings them all into one place and details what they are and how they're used. I did not know that all of these are being transitioned over, I believe that strengthens the case for this article.

**Comment by IEvangelist** [comment]
Following back up on this @gewarren, do you think a single location would be best to document all of the possible well-known environment variables? I'm thinking we need like a .NET env var glossary, or something like that.

**Comment by gewarren** [comment]
We also have this article under .NET SDK: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables. Probably makes sense just to add to that one?
