### ISSUE TITLE
Record reference should include attribute target for positional records

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#24037]
Positional records can include the `field:` or `property:` attribute target on the primary constructor in order to apply attributes to the field or property generated from those parameters. (You can also apply the `parameter:` but that is the default).

In addition, this content should be linked from the following locations:

- Attributes that affect compilation, in the section on AttributeUsage
- JSON Serialization: One of the most common scenarios for using this will be applying JSON serialization attributes to the record's properties. Likely candidates would be the name, or the ignore attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by scottaddie** [comment]
[Shayne's tweet](https://twitter.com/spboyer/status/1389585778733469701?s=20) provided an example of using this with MongoDB. The team should consider updating the 5.0+ versions of the [web API MongoDB tutorial](https://docs.microsoft.com/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio) to show this feature off.

**Comment by Youssef1313** [comment]
@BillWagner I think the records reference should also include the ability of documenting the primary constructor through `/// <param name="ParamName"></param>`. Is it okay for this to be tracked in this issue or should I open a separate issue?

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

Let's address it as part of this issue.

**Comment by tdykstra** [comment]
>Which JSON sample makes the most sense for linking to the new content for this issue?

https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0#immutable-types-and-records
