### ISSUE TITLE
Roslyn API reference isn't showing any versions under versions selector

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#24044]
The version selector is disabled:

![image](https://user-images.githubusercontent.com/31348972/117066070-8f55e400-ad28-11eb-9e80-0dc5f8917f38.png)

cc @BillWagner

**Comment by BillWagner** [comment]
What URL are you looking at @Youssef1313 ?  The version selector shows for me on [this pate](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnosticdescriptor?view=roslyn-dotnet-3.9.0)



![image](https://user-images.githubusercontent.com/493969/117148741-8561ce80-ad84-11eb-9f19-a9cdcb0d146d.png)

**Comment by Youssef1313** [comment]
@BillWagner Looks like it's fixed now.
