### ISSUE TITLE
What to use instead?

### ISSUE THREAD

**Issue by AIZ-THerring** [dotnet/docs#24045]
If we shouldn't use BinaryFormatter to serialize/deserialize object graphs that implement ISerializable, what *should* we use?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a9e65f-dc69-2d49-763a-3ef41bd055ae
* Version Independent ID: 52919538-8a37-e4fa-2483-607c220e7ea2
* Content: [BinaryFormatter security guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)
* Content Source: [docs/standard/serialization/binaryformatter-security-guide.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/binaryformatter-security-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @GrabYourPitchforks
* Microsoft Alias: **levib**

**Comment by GrabYourPitchforks** [comment]
There's a section in that document labeled _Preferred alternatives_ that lists alternative inbox serializers.

**Comment by adegeo** [comment]
It looks like this question is answered. I'll close the issue. Please reopen it if you need more information.
