### ISSUE TITLE
[2.0] New content for templating: Create custom templates for dotnet new

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2405]
Title: *Create custom templates for dotnet new*
Area: *docs/core/tools*

Reference
* [How to create your own templates for dotnet new](https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/)
* [dotnet/templating Wiki](https://github.com/dotnet/templating/wiki)

**Comment by mairaw** [comment]
Should we call it create custom templates for dotnet new perhaps?

@sayedihashimi do we have data on search terms for the blog post? also, any preferences on whether you'd like to see this topic under [Tutorials](https://docs.microsoft.com/en-us/dotnet/core/tutorials/) or under [Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/)?

Thanks!

**Comment by GuardRex** [comment]
I was too folksy there. :smile: ... but I was following @sayedihashimi's lead.

Title updated.

**Comment by GuardRex** [comment]
@sayedihashimi ... We'll try a 1st draft for this under *core/tools* and make it a reference-style doc that links to your blog post (as opposed to making this a tutorial/walk-through). Later, there might be a *core/tutorials* topic closer to how to go with your blog post. For right now tho, we'll just link to you if that's ok.

**Comment by GuardRex** [comment]
This work has been moved to https://github.com/dotnet/docs/pull/2495.
