### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/docs#24067]
The sentence "The binding redirects are added to the output configuration (app.config) file when the app is compiled and override the assembly unification that might otherwise take place" should be broken into two sentences for clarity.

 The "..and override the assembly unification that might otherwise take place" is confusing and awkward at best.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [Enable or disable autogenerated binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
