### ISSUE TITLE
"Variable declaration can be inlined" even when used by multiple cases in a switch

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#24070]
I have code like the following:
```
Dictionary<string, (int start, int length)> pathSpans;
var ret = x.o switch {
    Expression expr => expr.ToString(TextualTree, out pathSpans, "C#"),
    MemberBinding mbind => mbind.ToString(TextualTree, out pathSpans, "C#"),
    ElementInit init => init.ToString(TextualTree, out pathSpans, "C#"),
    SwitchCase switchCase => switchCase.ToString(TextualTree, out pathSpans, "C#"),
    CatchBlock catchBlock => catchBlock.ToString(TextualTree, out pathSpans, "C#"),
    LabelTarget labelTarget => labelTarget.ToString(TextualTree, out pathSpans, "C#"),
    _ => throw new InvalidOperationException(),
};
```
The analyzer recommends inlining the variable in the first case of the `switch`:
```
var ret = x.o switch {
    Expression expr => expr.ToString(TextualTree, out var pathSpans, "C#"),
...
```
but if I do that, the variable isn't available to the other cases in the switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fce4950-f4e0-2383-264a-166a6a35b38f
* Version Independent ID: 3557b307-e917-b4a2-dec5-1bfdf70654c1
* Content: [IDE0018: Inline variable declaration - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0018)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0018.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0018.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BillWagner** [comment]
Thanks for writing this @zspitz 

If you accept that recommendation, you'd need to add the `var` declaration in the other switch arms as well:

```
Dictionary<string, (int start, int length)> pathSpans;
var ret = x.o switch {
    Expression expr => expr.ToString(TextualTree, out var pathSpans, "C#"),
    MemberBinding mbind => mbind.ToString(TextualTree, out var pathSpans, "C#"),
    ElementInit init => init.ToString(TextualTree, out var pathSpans, "C#"),
    SwitchCase switchCase => switchCase.ToString(TextualTree, out var pathSpans, "C#"),
    CatchBlock catchBlock => catchBlock.ToString(TextualTree, out var pathSpans, "C#"),
    LabelTarget labelTarget => labelTarget.ToString(TextualTree, out var pathSpans, "C#"),
    _ => throw new InvalidOperationException(),
};
```

I'll close this as an answered question.
