### ISSUE TITLE
Missing documentation for dotnet tool install --tool-manifest option and others

### ISSUE THREAD

**Issue by chull434** [dotnet/docs#24095]
Hi, 

The dotnet tool install documentation is missing --tool-manifest <PATH> option and other options.

dotnet tool install --help shows the full list of options, documentation for this cli command is missing some of the options such as --tool-manifest and a few others, dotnet tool update seems to have the full list of options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, I'm fixing it.
