### ISSUE TITLE
Unable to complete "Containerize an app with Docker" tutorial 

### ISSUE THREAD

**Issue by soren2013** [dotnet/docs#24091]
I was unable to build the docker image (docker build -t counter-image -f Dockerfile .) using the suggested Dockerfile content "FROM mcr.microsoft.com/dotnet/aspnet:5.0",

I received this error message: "failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed"

I discoved that I was able to build the image using "FROM mcr.microsoft.com/dotnet/runtime:5.0" instead. 

Tutorial should probably be updated so it works out of the box or the issue with the original Dockerfile content should be resolved.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @soren2013
Thank you so much for posting this issue. We really appreciate it.

I'll take a look at this right now and report back my findings.
