### ISSUE TITLE
A tiny typo in example code - Celsius

### ISSUE THREAD

**Issue by disouzam** [dotnet/docs#24107]
The variable tempInCelcius in the first code snippet should read tempInCelsius to comply with the name of temperature measurement unit. 

`string GetWeatherDisplay(double tempInCelcius) => tempInCelcius < 20.0 ? "Cold." : "Perfect!";

Console.WriteLine(GetWeatherDisplay(15));  // output: Cold.
Console.WriteLine(GetWeatherDisplay(27));  // output: Perfect!`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5379a49c-6a81-82a5-cca2-3ab71f432c5c
* Version Independent ID: 1a00e3ec-bec1-3030-9766-a788912bc3b9
* Content: [?: operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)
* Content Source: [docs/csharp/language-reference/operators/conditional-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/conditional-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @disouzam 

I see @pkulikov has already submitted a PR with a proposed fix.
