### ISSUE TITLE
This page is supposed to be for application dependencies but it only discusses nuget packages

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24103]
Project references, assembly references, framework references, user explicit project dependencies (and project build order) all should be covered by this document. (Or this document should be moved into the nuget docs.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f76f1f9-ebac-1b77-f735-52cdf5b973ed
* Version Independent ID: 3e3f4bb2-4329-527e-2edb-9eabdfa29313
* Content: [Manage dependencies in .NET - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dependencies)
* Content Source: [docs/core/tools/dependencies.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dependencies.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion, the doc title does seem to imply a broader scope than the actual content. Another option would be to clarify in the title, TOC, and intro text that this article is about package dependencies.
