### ISSUE TITLE
This page should have a link to the GH repo where the CLI is at

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24105]
which is https://github.com/dotnet/sdk.   

The product feedback link takes us to a dev comm space, which isnt at all useful for reporting defects, making PR's, etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion - this is a good idea.  I agree with @Youssef1313 that it's relevant to all the CLI docs.  We could leave this issue and associated PR #24106 as-is and create a new issue for the others, or broaden the scope of this issue and change the PR accordingly.
