### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by markachus** [dotnet/docs#24125]
"This makes it possible to define equality somewhat differently than for DateTimeOffset values" should read
"This makes it possible to define equality somewhat differently than for **DateTime** values"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42536391-9929-ac2b-eee1-b7f26f86ca4e
* Version Independent ID: 7077b965-0323-7de6-5326-104b2772445c
* Content: [Performing arithmetic operations with dates and times](https://docs.microsoft.com/en-us/dotnet/standard/datetime/performing-arithmetic-operations?source=docs)
* Content Source: [docs/standard/datetime/performing-arithmetic-operations.md](https://github.com/dotnet/docs/blob/main/docs/standard/datetime/performing-arithmetic-operations.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
Thanks for reporting that @markachus !
