### ISSUE TITLE
[Project] Add the Roslyn API reference to docs

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2412]
The Roslyn APIs (aka the .NET Compiler Platform SDK) should be on docs. 

See [this project](https://github.com/dotnet/docs/projects/10) for sub-tasks.

**Comment by svick** [comment]
Related issue on the Roslyn repo: https://github.com/dotnet/roslyn/issues/11557.

**Comment by BillWagner** [comment]
Somehow, I'm not surprised @svick wrote this some time ago.

**Comment by BillWagner** [comment]
The Roslyn APIs are now live on docs.

Thanks @dend and @meganbradley

**Comment by svick** [comment]
Awesome! Next step: fill out documentation for the many members that don't have it from XML comments. 😄 

Also, I can't find documentation for the `Microsoft.CodeAnalysis.ISymbol` interface. In fact, the whole [`Microsoft.CodeAnalysis` namespace](https://docs.microsoft.com/en-us/roslyn-dotnet-api/api/microsoft.codeanalysis) looks suspiciously empty. It seems the only type there is from the `Microsoft.CodeAnalysis.CSharp` assembly, but all types from the `Microsoft.CodeAnalysis` assembly are missing (at least for that namespace)

**Comment by mairaw** [comment]
We can open issues for Roslyn API docs at https://github.com/dotnet/roslyn-api-docs/issues

**Comment by svick** [comment]
@mairaw Didn't know about about that repo, thanks. Issue opened: https://github.com/dotnet/roslyn-api-docs/issues/18.

**Comment by mairaw** [comment]
@svick it's new. 😄 Thanks!
