### ISSUE TITLE
VB Example Messed up '

### ISSUE THREAD

**Issue by Zaptrix** [dotnet/docs#24120]
The Example VB Code has messed up apostrophes that cause the code to read incorrectly, some of the comments are colored as code and some of the code is colored as a comment. This can be fixed by having someone change the apostrophes to line up with the actual comments and keep the code in a more readable color coded format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec570c0-3c04-a8d1-9f13-1696f93080a3
* Version Independent ID: ce60c1cc-649a-5bef-28b2-ac34108d9483
* Content: [Like Operator - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/like-operator)
* Content Source: [docs/visual-basic/language-reference/operators/like-operator.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/like-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
This is a known issue in the highlighting library used across the docs site.

cc @IEvangelist

**Comment by Youssef1313** [comment]
@BillWagner @IEvangelist @gewarren This can be closed now. The highlighting was fixed.
