### ISSUE TITLE
JSON deserialization behavior regarding private/protected/internal set properties

### ISSUE THREAD

**Issue by fterrani** [dotnet/docs#24126]
The page mentions that
> Deserialization to immutable objects or read-only properties isn't supported.

This is of course a very useful information but I think it could use more precision.

The deserialization works even if the class only has a `private` parameterless constructor, so I was expecting that maybe a property with a `private`/`protected`/`internal set` accessor would be populated.

It seems however that it is not the case according to my (basic) tests: the only `set` accessor accessibility that allows a `public` property to be populated is "public" (no keyword, e.g. `{ get; set; }`). If the property has `private`/`protected`/`internal set`, it doesn't seem to be populated.

What's misleading here is that the text says "read-only properties" aren't supported, but I find it hard to consider that a `public` property with a `get` accessor and a `private`/`protected`/`internal set` accessor is read-only. What are you thoughts about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
thanks for pointing this out.  I'll change the wording to:

>Deserialization to immutable objects or properties that don't have public `set` accessors isn't supported.
