### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json Epoch DateTime/Offset example RegEx

### ISSUE THREAD

**Issue by cranml** [dotnet/docs#24195]
I'm probably missing something so forgive me if I am. I'm converting some legacy code and I have the following code sample for simplicity sake

     
```
   DateTime sampleDateTime = new DateTime(1969, 12, 31);
   DateTime s_epoch = new DateTime(1970, 1, 1, 0, 0, 0);
   long unixTimeTotalMilliseconds = Convert.ToInt64((sampleDateTime - s_epoch).TotalMilliseconds);

   //using the regex in the example on the page
   Regex s_regex = new Regex("^/Date\\(([^+-]+)\\)/$", RegexOptions.CultureInvariant);
   string formatted = FormattableString.Invariant($"/Date({unixTimeTotalMilliseconds})/");
   Match match = s_regex.Match(formatted);

   if(!match.Success ||
        !long.TryParse(match.Groups[1].Value, System.Globalization.NumberStyles.Integer, CultureInfo.InvariantCulture, out long convertedUnixTime))
    {
       throw new JsonException();
    }

```
I was wondering if my case is applicable to the example supplied or if I need to handle dates before 1970 (date of birth for example) a little differently (or if its a typo in the regex supplied on this page). The reason being the JsonException is always thrown for dates prior to 1970 in my code sample

Thanks for taking the time to read this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that bug in the sample code.  Try  this regex -- "^/Date\\(([+-]*\\d+)\\)/$"
