### ISSUE TITLE
TF_StringEncodedSize

### ISSUE THREAD

**Issue by MartinDavidWaller** [dotnet/docs#24198]
Hi,

I've worked through this example code and the code all compiles but I get the error:

System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'TF_StringEncodedSize' in DLL 'tensorflow'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

On the line:

ITrasnformer trainedModel = trainingPipeline.Fit(trainSet);

Any suggestions how to make this work would be appreciated.

Many thanks

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8adaedc-37da-e381-a87e-6649bc6cb3c8
* Version Independent ID: 779340cf-274b-5af9-54f0-b9b90c54f143
* Content: [Tutorial: Automated visual inspection using transfer learning - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning)
* Content Source: [docs/machine-learning/tutorials/image-classification-api-transfer-learning.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/image-classification-api-transfer-learning.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @MartinDavidWaller 

Sorry to hear you ran into issues. Can you try setting the `Microsoft.ML.Vision, SciSharp.TensorFlow.Redist` NuGet package version to 2.3.1.

**Comment by MartinDavidWaller** [comment]
Hi Luis,

 

Many thanks for the quick response to my problem.

 

Yes, that sorted it. I now have the code ‘being trained’!

 

I’ve been a developer all my working life but the Machine Learning is all new to me so I’m on a learning curve which is exciting!

 

Many thanks

 

Martin
