### ISSUE TITLE
Structs and records as indexer parameter type

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [dotnet/docs#24193]
**Help us make content visible**

I found the following guideline for [Indexed Property Design](https://github.com/dotnet/docs/blob/main/docs/standard/design-guidelines/property.md).

The guideline states the following: AVOID indexers with parameter types other than System.Int32, System.Int64, System.String, System.Object, or an enum.

So my question is what about structures and records? Should those types also be avoided or if not, should they be added to the list in the guideline?

**Comment by BillWagner** [comment]
ping @IEvangelist Do you know of any updates on this guidance?

**Comment by IEvangelist** [comment]
Hi @BillWagner - no, I'm **_not_** familiar with any updates to that guidance, and it feels as though it wouldn't make sense to include a `struct` or a `record` as an indexer. If you take a step back and think about it, these have value comparison semantics - great, but using them as a key on an indexer does what exactly? The indexer property is intended to be used to access a value, whereas using a `struct` or a `record` as the index seems as though you're using the value as the key. Using the canonical `Person` record, let's create an indexer. 

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

PeopleIndexer indexer = new();

Person david = new(7, "David", "Pine");
indexer[david.Id] = david;

Console.WriteLine(indexer[0]); // No one's home...
Console.WriteLine(indexer[7]);

indexer[david.Id] = david with { Id = 999, LastName = "Fowler" };
Console.WriteLine(indexer[999]);

public class PeopleIndexer
{
    readonly HashSet<Person> _people = new();

    public Person this[long id]
    {
        get => _people.FirstOrDefault(p => p.Id == id);
        set => _people.Add(value);
    }
}

public record Person(long Id, string FirstName, string LastName);
```

This would output ([sharplab.io link](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQB4wgOwCYR6oAOCA9sRAjAJ4mzYI7IA0MICcOAPgAIBMARgCwAKF4AGAAS9BAFgDcYyTMEA6ADIBLHAEclosQAUIFADYQAkvkxUpOghjsBeKTggB3ABQBKA8apkMhwpPCgANy08KVd3bwB2FikAIgARCKjkpOSjHQhkvzEHWwQAbTDIvDVLPABdGNCMvH9xQQBOL2KnMolavykAegGpADkyKWCIAHJkKQALMgBbCDVV5XbOm27S+L6Wrqpypuq6hoqoqQ8tGDmpAG8pGoa2l6SNKGQYEahlhuSAMTIHgsCGSUgAvgZZB0DmUXm09mJlABmGT8KQmcxWLZUMR3MRSQlSJBQPDBMw0KQACQ+cwAyhAYAAeEwIII4AB8UgA+pQsQ04r4WkSZKjWeypDctMhSmZggBzex1AlE/GiEUi+WMmJc3mmYgWNT/LRsmAAeQQqQgYCgcDMMC8xB1UmIJxiriihXVGsJyG1zl1fINKwAgng8F5wlAzHAIF6ReCxInDOJUUgAMZkBDRcXBLxynCKmpJWTSY2m77LEuCaTvT6VuMKIA=)):

```

Person { Id = 7, FirstName = David, LastName = Pine }
Person { Id = 999, FirstName = David, LastName = Fowler }
```

But if you're to use the record as the indexer, what is the value you're expecting? My argument is that it doesn't really make sense. I guess I'd have to see an example of what usage you'd reasonably expect a record or struct as the key to an indexer property, that would be really helpful. 

Do you have a valid use case for this @csaba-sagi-sonarsource? Happy to talk through it more and try to understand its validity.

**Comment by csaba-sagi-sonarsource** [comment]
HI @IEvangelist, thank you fir the quick answer and the nice example.

I created a simplified example with structs. It is similar to a use case I saw at my previous company while working with industrial equipment and communication protocols. Please take a look at the example and feel free to give me a feedback why such an indexer should or should not be used.

```
public class IndustrialDevice
{
    readonly HashSet<IndustrialComponents> components = new();

    public IndustrialComponents this[ComponentAddress address]
    {
        get => components.FirstOrDefault(p => p.Address.Equals(address));
        set => components.Add(value);
    }
}

public record IndustrialComponents(long Id, ComponentAddress Address);

public struct ComponentAddress
{
    public int AddressPart1 { get; set; }
    public int AddressPart2 { get; set; }

    public ComponentAddress(int addressPart1, int addressPart2)
    {
        AddressPart1 = addressPart1;
        AddressPart2 = addressPart2;
    }
} 
```

**Comment by IEvangelist** [comment]
Hi again @csaba-sagi-sonarsource - that's an interesting use case and it does feel valid. I'd probably suggest that the `struct` should be made `readonly`, but other than that - I'm not too worried about that as that key to an indexer. I'd be curious if there should be any guidance as to the size of the struct or record, or if that should matter. Here is a [sharplab.io with your code](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQB4wgOwCYR6oAOCA9sRAjAJ4mzYI7IA0MICcOAPgAIBMARgCwAKF4AGAAS9BAFgDcYyTMEA6ADIBLHAEclosQEl8cZDARaoAGwAiEAG5aAxhCk6CGKlIC8UnBAA7gAUAJQGYgDCZAC2xGQBODAAgnh4SMjIUgkQAPIBvv5BwYIsUoLhUbHxiSlpGVkwABZIEAByOm5+ASEAzGUAnJWGoiZ4ZhZW1tFxOUlZENaOuIU9JaXZAfkQww5QCFLNWtQ0HQV+i8s4UoFazVIA3lJGeIW9A2Wp6ShZfs2tZzcAF8IqIPJgqABtHLbAC6hUuDlwBnBXgQkP+EHanXhfyax1ogNBsgGwVRULWGwqsOGJLJ+Ah6LW/SkQxpxN6Mn4z1M5ksNnsTlcYgeYik4qkSCgeAS1hoUgAElBkE0AMoQGAAHjGE3502qcxgyAAfFIAPrOA21X5FELDMUS3icnV8qYzGq4I2HfHISHuw1fBpSaXfTKwh3i0WiCUxqQAcw1vlNFqtnuQagAYsdzLkEPYwFA4NYYMFiEmpMQ1IGfmoAKK6OA2ZDBEMNULDWMS5CJnzJy2za1VtLBPbWOA7AwxoFiacjJ2SiCWhCvF2TGz+63BawJOPPPBlDee6uZKTH5D28ScqUynByqR8uDOGBSQ9JM8iiMyTk6Z9ngAK+wwIIjzxhqChSLOMbzj+p71D8AHUNyTwJjA4Gzp+86vnUobNjBrbwYBGx4XBmQITA/ChJ+UaduK/6EYU+GkYRk40XRiEMSRyBkfwLHirOQJSGIQA==).

@BillWagner what do you think? Are there any other concerns that we're not considering here?

**Comment by Youssef1313** [comment]
From language perspective, there is nothing wrong with using anything as indexer parameter. However, I tend to agree with the guidelines that using anything other than a numeric type is usually a bad idea.

For your case, I feel it's more natural to  an `IDictionary<

**Comment by IEvangelist** [comment]
Hey @bartonjs - would you mind looking this issue over, as it is related to Design Guidelines? What should be the official suggestion for this sort of thing?

**Comment by bartonjs** [comment]
This rule did get modified in FDGv3:

> AVOID indexers with parameter types other than System.Int32,
System.Int64, System.String, System.Range, System.Index, or an
enum, except on dictionary-like types.

(5.2.1, Indexed Property Design, p. 161)

We obviously need a plan for getting the updated guidance in the docs pages (or removing / redirecting the docs pages to another location) -- the current ones seem to be mostly FDGv1 rules with their FDGv2 updates applied (there are sections of v2 guidance that don't appear at all).  Though the last time this got spun up (when FDGv3 was in final edits) it hit a pause with legal about making sure that ts are crossed and is are dotted with regards to the portions that require the "Reprinted by permission of Pearson Education, Inc." notice.

**Comment by IEvangelist** [comment]
Hi @bartonjs - I love the idea of putting together a plan for this. Do we have permission from Pearson Education to replicate this content, if not what does that look like and what is the timeline? Is the FDGv3 fully published and publicly available now? Happy to proceed as you deem necessary. Thank you

**Comment by bartonjs** [comment]
> Do we have permission from Pearson Education to replicate this content

Practically speaking? Yes (IANAL), but not in a manner that CELA likes, so no.

> if not what does that look like and what is the timeline

Don't really know, probably better dealt with over an internal channel.

> Is the FDGv3 fully published and publicly available now?

Yep.  https://www.informit.com/store/framework-design-guidelines-conventions-idioms-and-9780135896327 "and quality bookstores everywhere".

**Comment by IEvangelist** [comment]
We do not have permissions to update this content with information that is part of edition three. With that said, I'm going to close this and point you to https://www.informit.com/store/framework-design-guidelines-conventions-idioms-and-9780135896327.
