### ISSUE TITLE
Please provide Lambda examples

### ISSUE THREAD

**Issue by SDmorgan** [dotnet/docs#24196]
Please provide Lambda examples as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8fbdf8-317e-2c98-972e-180ff8b5a2b3
* Version Independent ID: 6389f1e8-d48b-3b16-bbc1-fe1711eb0177
* Content: [Perform inner joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-inner-joins)
* Content Source: [docs/csharp/linq/perform-inner-joins.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/perform-inner-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @SDmorgan 

Can you elaborate on what you mean by "lambda examples"? I'd like to understand more what you're looking for.
