### ISSUE TITLE
Redundant breaking changes page?

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#24213]
This page seems redundant with https://docs.microsoft.com/en-us/dotnet/core/compatibility/. If nothing else, we should at least link between them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba86da6-e986-f552-62ce-d6d164230ef1
* Version Independent ID: 171fb71c-ceea-ed03-c047-cc35e571f055
* Content: [Breaking changes and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes)
* Content Source: [docs/standard/library-guidance/breaking-changes.md](https://github.com/dotnet/docs/blob/main/docs/standard/library-guidance/breaking-changes.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
The library guidance breaking changes page should link to https://docs.microsoft.com/en-us/dotnet/core/compatibility/
