### ISSUE TITLE
Document valid values for AnalysisMode

### ISSUE THREAD

**Issue by stewartadam** [dotnet/docs#24211]
See discussion here: https://github.com/dotnet/roslyn/issues/49250#issuecomment-760416810

From @mavasani:
> They will eventually be documented here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode

[This docs](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/predefined-configurations) page references the presets bundled in `Microsoft.CodeAnalysis.NetAnalyzers`. If a user goes digging into that, they'll find editorconfig files with names like 'recommended', 'none', 'default', etc:
```
AnalysisLevelNaming_5_recommended.editorconfig
AnalysisLevelMaintainability_5_none.editorconfig
AnalysisLevelMaintainability_5_default.editorconfig
AnalysisLevelPerformance_5_all.editorconfig
AnalysisLevelDocumentation_5_recommended.editorconfig
AnalysisLevelInteroperability_5_none.editorconfig
AnalysisLevelUsage_5_recommended.editorconfig
AnalysisLevelSecurity_5_recommended.editorconfig
AnalysisLevelMaintainability_5_recommendedededitorconfig
AnalysisLevelUsage_5_minimum.editorconfig
AnalysisLevelDocumentation_5_default.editorconfig
AnalysisLevelSecurity_5_default.editorconfig
...
```

It's unclear how these relate to `AnalysisMode` settings documented [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enable-additional-rules) -- are these editorconfigs procedurally generated from the source code tags (and therefore ignored no matter the value of AnalysisMode)? [This code](https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/CodeStyle/Tools/Program.cs#L160) would seem to indicate so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Thanks @stewartadam. This is a duplicate for https://github.com/dotnet/docs/issues/23904. I plan to add this documentation soon.
