### ISSUE TITLE
should show an optional parameter = null

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#24225]
It would be good to include an example where the parameter is a reference type with default value of `null`. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @daveyostcom 

I see @Youssef1313 has already created a PR to address this.

**Comment by daveyostcom** [comment]
I think there needs to be an example showing `void foo(string s = null) { .. }` or the like, and there should be a discussion of the interaction between an optional argument and the `nullable` feature.
