### ISSUE TITLE
GetTargetFrameworkProperties and GetNearestTargetFramework have been removed

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#24228]
## GetTargetFrameworkProperties and GetNearestTargetFramework have been removed

The GetTargetFrameworkProperties target and GetNearestTargetFramework task have been removed from the .NET SDK

https://github.com/dotnet/sdk/issues/13519
https://github.com/dotnet/sdk/pull/15027/files
https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#targets-required-to-be-referenceable 

### Version introduced

.NET Core SDK 6.0.100-preview1

### Old behavior
GetTargetFrameworkProperties target and GetNearestTargetFramework task were not used but were still present.  Custom MSBuild logic could have taken a dependency on them.

### New behavior
This task and target have been removed.

### Reason for change
These were deprecated in MSBuild 15.5 and so are being removed in in .NET 6.

### Recommended action

Use GetTargetFrameworks instead.  See https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#targets-required-to-be-referenceable 

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [x] MSBuild
- [ ] Networking
- [ ] Printing
- [ ] Security
- [ ] Serialization
- [x] SDK
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs
"Not detectable via API analysis"

---
#### Issue metadata

* Issue type: breaking-change

**Comment by dsplaisted** [comment]
I've updated the description here.
