### ISSUE TITLE
#region identifier string not required.

### ISSUE THREAD

**Issue by BlaQQ** [dotnet/docs#24222]
Hello,

#region doesn't require an identifier string, but the page says it is required. Just below it is an #endregion description which doesn't say it's required when it, in fact, is.
Not a big deal, but it's an inaccuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1da80bd5-efb6-339b-8480-2da0310e5672
* Version Independent ID: 0b643ad9-8979-55fe-4c7d-08dccd89c21b
* Content: [#Region Directive - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/directives/region-directive)
* Content Source: [docs/visual-basic/language-reference/directives/region-directive.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/directives/region-directive.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
@BlaQQ It's required in the sense that the following is invalid:

```vb
#Region
#End Region
```

But I see your point, the article already puts `""` in the syntax, and it defines the identifier string as whatever is between the quotes, which is indeed not required.

**Comment by BillWagner** [comment]
Thanks for pointing this out @BlaQQ 

I see that @Youssef1313 have already opened a PR to address it.
