### ISSUE TITLE
Searching for RuntimeFrameworkVersion in the .NET docs yields no results

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#2423]
I was looking for info on the `RuntimeFrameworkVersion` MSBuild property, so I did a [search](https://docs.microsoft.com/en-us/search/index?search=RuntimeFrameworkVersion&scope=.NET) for RuntimeFrameworkVersion in the .NET docs, but got zero results. However, it turns out there is a [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) that talks about this property. Looks like the search results need to be fixed.

**Comment by GuardRex** [comment]
Can this be fixed by adding the term (perhaps other key terms as well) to the `keywords` metadata?

**Comment by mairaw** [comment]
There was a bug with search for the .NET content that was recently fixed. The link to your search now brings two results. 
Re. keywords metadata, I think that only Bing uses that and SEO guidelines for that are changing. I'll follow up on that with Khairun.
