### ISSUE TITLE
Edit link is broken

### ISSUE THREAD

**Issue by stewartadam** [dotnet/docs#24243]
The edit link opens https://github.com/dotnet/AspNetCore.Docs/edit/master/aspnetcore/fundamentals/http-requests.md?description=%0A%0A-------%0Acc%3A%20%40stevejgordon which is a 404 -- note it is using `master` as the branch, instead of `main` which is used upstream.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by adegeo** [comment]
@stewartadam It's working fine for me. Can you link to the source file you're working with that is giving you an incorrect edit link? It seems you reported the problem for one page and said the edit link doesn't work for another.

**Comment by stewartadam** [comment]
@adegeo sorry for the mismatch. The Edit button on [Implement HTTP call retries with exponential backoff with IHttpClientFactory and Polly policies
](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly) isn't working for me, nor is the one for [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#use-ihttpclientfactory-in-a-console-app](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)

**Comment by adegeo** [comment]
@stewartadam hmm. it's working for me ☹️ 

![edit-button](https://user-images.githubusercontent.com/67293991/118551764-e8ebe480-b712-11eb-9778-76345c9437cb.gif)

**Comment by stewartadam** [comment]
Hm, you're right - it worked fine in Incognito, after a bit of investigation I found it appears to be caused by the [SpineEdit](https://github.com/craigshoemaker/spineedit) extension I had installed to make PR creation easier. So we can close this as PEBKAC :)
