### ISSUE TITLE
Enhance optional parameters example

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#24249]
I think there needs to be an example showing `void foo(string s = null) { .. }` or the like, and there should be a discussion of the interaction between an optional argument and the `nullable` feature.

_Originally posted by @daveyostcom in https://github.com/dotnet/docs/issues/24225#issuecomment-841503967_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The following method:

```csharp
   public void ExampleMethod(int required, int optionalInt = default(int),
                             string description = "Optional Description")
   {
      Console.WriteLine("{0}: {1} + {2} = {3}", description, required,
                        optionalInt, required + optionalInt);
   }
```

Could be modified to:

```csharp
   public void ExampleMethod(int required, int optionalInt = default(int),
                             string? description = null)
   {
      if (description is null)
         Console.WriteLine("{0} + {1} = {2}", required,
                           optionalInt, required + optionalInt);
      else
         Console.WriteLine("{0}: {1} + {2} = {3}", description, required,
                           optionalInt, required + optionalInt);
   }

```

**Comment by BillWagner** [comment]
@Youssef1313 I like your idea here. I'd also add the `default` expression (updating the `default(int)` expression).
