### ISSUE TITLE
Call javascript from dotnet : link is broken

### ISSUE THREAD

**Issue by glihm** [dotnet/docs#24248]
**Issue description**

The links to the documentation for blazor interop calls seems to be broken:

1. [JS -> .NET](https://docs.microsoft.com/en-us/aspnet/core/blazor/js-interop/call-javascript-from-dotnet?view=aspnetcore-5.0)
2. [.NET -> JS](https://docs.microsoft.com/en-us/aspnet/core/blazor/js-interop/call-javascript-from-dotnet?view=aspnetcore-5.0)

**Target framework**

aspnetcore-5.0 documentation

**Comment by glihm** [comment]
I think I have found the new links to be redirected to:

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-5.0

**Comment by tdykstra** [comment]
Thanks for reporting this -- Which article has the broken links?
