### ISSUE TITLE
nameof for field of record

### ISSUE THREAD

**Issue by TysonMN** [dotnet/docs#24258]
> The `nameof` expression produces a string constant that matches the name in source for nearly any F# construct in source.

What about the field of a record?  Is it possible to use `nameof` with that construct?  Is so, could an example of this be added to this documentation?  (I can't figure out how to do this.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e313948-0ecb-7c3c-1e1f-3c56a3045a41
* Version Independent ID: 254fda6f-2502-c076-a63d-221f3474ceb0
* Content: [Nameof - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/nameof)
* Content Source: [docs/fsharp/language-reference/nameof.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/nameof.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment]
@cartermp Could you answer this question about record fields?

**Comment by cartermp** [comment]
It's possible to take the name of a record label with an instance of the record.

```fsharp
let f (r: R) =
	printf $"{nameof r.Label}"
```

But not unqualified, which is what I expect you're asking about.

**Comment by TysonMN** [comment]
I see.  I don't have an instance of the record in my use case.  Here is how I would write it.

```
nameof Unchecked.defaultof<MyRecord>.MyField
```

Can a section about record fields be added to documents?  It could include both our code examples.  I am willing to contribute a PR that makes this addition.

**Comment by cartermp** [comment]
It's not specific to records. F# doesn't allow resolving items that don't come from an instance unless they are static. A small section about that in the remarks could work.
