### ISSUE TITLE
Suggestion: document how to deserialize json or object into a a dynamic json object (JsonDocument)

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/docs#24251]
For example, given arbitrary object `obj`, I could deserialize into a "json-enabled" `JsonDocument` like this:

```
JsonDocument objJson = JsonDocument.Parse(JsonSerializer.SerializeToUtf8Bytes(obj));
```

or

```
JsonElement objJson = JsonSerializer.Deserialize<JsonElement>(JsonSerializer.SerializeToUtf8Bytes(obj));
```

I suggest to document how to achieve this scenario (maybe there is a better way than my examples above), as well as how to obtain the `JsonDocument` from a `json` string.

In other words, currently the documentation explains only the following deserialization scenario:
`json -> typed/custom POCO`
but I also want to see:
`json -> dynamic/json POCO`
`object -> dynamic/json POCO`

I see the `JsonDocument` is mentioned here:
[How to write custom serializers and deserializers with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/write-custom-serializer-deserializer)
but it is unclear this is where I have to look for it.

Related issue: 
- #24252 Suggestion: document how to work with non-read-only equivalent of JsonDocument 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#how-to-read-json-as-net-objects-deserialize)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
> but it is unclear this is where I have to look for it.

JsonDocument and JsonElement are also documented in the [Newtonsoft migration article](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#jsondocument-and-jsonelement-compared-to-jtoken-like-jobject-jarray)

When the related .NET 6 features are documented, you can look for them in the same two places -- [How to write custom serializers and deserializers](https://docs.microsoft.com/en-us/dotnet/standard/serialization/write-custom-serializer-deserializer) and the [Newtonsoft migration article](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#jsondocument-and-jsonelement-compared-to-jtoken-like-jobject-jarray).

**Comment by konrad-jamrozik** [comment]
@tdykstra thanks for the info! I would say "Newtonsoft migration guide" and "custom serializers and deserializers" are not unexpected, not discoverable locations for this piece of information. What I am looking for is not related to Newtonsoft (note I did not mention it in the description of the problem), and doesn't require customization of how the de/serialization is done; it is supposed to work out of the box, and appears to me to be a variation on the basic serialize/deserialize concept.

Thus, I would still suggest to make this article at least mention where to find that information.

**Comment by tdykstra** [comment]
Oh, I think I understand your point now -- the main how-to needs to link more prominently to the "custom serializers and deserializers" article, and probably the latter should have JsonDocument and JsonElement in the title.  And link more prominently to the Newtonsoft article from both of the other two.
