### ISSUE TITLE
Empty line highlighted

### ISSUE THREAD

**Issue by teraa** [dotnet/docs#24268]
At the end of the "How algorithms are implemented in .NET" section:

> For example, see the highlighted line of code in the following example:

the referenced code has highlighted empty line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc59c0ef-fc24-730b-086a-683bb85fca7a
* Version Independent ID: 93212589-e9f6-4bf8-d547-559743e3eb5e
* Content: [.NET cryptography model](https://docs.microsoft.com/en-us/dotnet/standard/security/cryptography-model)
* Content Source: [docs/standard/security/cryptography-model.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/cryptography-model.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @teraa
Thank you so much for posting this issue. We really appreciate it, I've put together a fix for this issue in #24269
