### ISSUE TITLE
IAsyncDisposable suggestion - code with multiple await keywords

### ISSUE THREAD

**Issue by divinebovine** [dotnet/docs#24261]
It _might_ be worthwhile to include an example of having multiple awaits in a single line of code, e.g.
`await using var transaction = await dbContext.Database.BeginTransactionAsync(token).ConfigureAwait(false);`

It wasn't immediately obvious that two awaits are necessary, but it does make sense. It might save people some time as they're getting used to `IAsyncDisposable`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @divinebovine 
Thank you so much for posting this issue. We really appreciate it, and I agree that this would be a great example use case to add. I'll work on getting that into the docs.
