### ISSUE TITLE
A Bit of Incorrect Information about Surrogate Pairs

### ISSUE THREAD

**Issue by dwcullop** [dotnet/docs#24262]
In [this paragraph](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction#surrogate-pairs), it states:
>The high surrogate code point is called "high" because it's used to calculate the higher-order 11 bits of the full 21-bit code point range. The low surrogate code point is used to calculate the lower-order 10 bits.  

However, there are only 20-bits because the surrogates can each only provide ten.  Of the 16 bits, the first 5 are always `11011` (which designate it as in the surrogate range), the next bit is 1 for the high surrogate code points and 0 for the low surrogate code points, and that only leaves 10 remaining bits for the actual data.

I couldn't figure out from where the numbers 21 or 11 came, so I [finally turned to Wikipedia](https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF), and they cleared things up (just a bit).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66
* Version Independent ID: d53a0764-9f27-16b3-c40a-9627dd1bcc0d
* Content: [Introduction to character encoding in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction)
* Content Source: [docs/standard/base-types/character-encoding-introduction.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/character-encoding-introduction.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by VZhelev** [comment]
The diagram in the paragraph shows the BMP range, but the end value (in the red rectangle in the picture) seems wrong.
Shouldn't it be U+FFFF?

![image](https://user-images.githubusercontent.com/30770182/120347070-9f9bb780-c304-11eb-89a5-c7afe8a76bdf.png)

**Comment by tdykstra** [comment]
Good points, @dwcullop and @VZhelev -- thanks for finding and reporting the errors.  I'll have them fixed shortly.
