### ISSUE TITLE
dev_langs metadata

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2426]
While updating one topic today, I saw that we have jsharp as a dev_lang metadata value and lots of topics on winforms for example are missing other dev_langs. We should update it to remove jsharp and add the appropriate ones. Maybe we can even set those at a global level?

**Comment by mairaw** [comment]
The effect of this in some topics such as [Mapping Algorithm Names to Cryptography Classes](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/map-algorithm-names-to-cryptography-classes) is that you get a dropdown with these languages:
![image](https://user-images.githubusercontent.com/12971179/27809715-05ef902a-6007-11e7-845c-af8db7481468.png)

**Comment by cartermp** [comment]
We're missing F# globally (though I'm not sure if there are any samples in F#).  jsharp should definitely get removed 😄

**Comment by mairaw** [comment]
We can add F# to the individual topics, but globally I wouldn't set F# except for the F# Guide.
