### ISSUE TITLE
Incorrect translation in Chinese simplified page

### ISSUE THREAD

**Issue by jmty0083** [dotnet/docs#24299]
EN: The expression sequence[^0] does throw an exception, just as sequence[sequence.Length] does.
CN: 表达式 sequence[^0] 不会引发异常，就像 sequence[sequence.Length] 一样。

The Chinese version page (https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/tutorials/ranges-indexes) has a totally opposite meaning, which is obviously incorrect. 

Removing character "不" will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6f7384-2a77-a8f2-63dc-c1b545aba2a9
* Version Independent ID: eec3706d-1448-9f80-a520-2989b59c1093
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/ranges-indexes)
* Content Source: [docs/csharp/whats-new/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonCard** [comment]
@jmty0083 Thank you for your feedback. I'm following up internally.

@Youssef1313 Thank you for checking. We no longer have loc repos, but I can follow up on localization issues internally, so please just @ mention me going forward. 
As I'm following up on this localization issue internally, I'll close this ticket for English repo.
