### ISSUE TITLE
useless

### ISSUE THREAD

**Issue by baquick** [dotnet/docs#24292]
Waste of Internet bandwidth.

Gives no useful direction on un-installing services.

Nothing works on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433b4c70-07c8-34c3-b567-22c80b71c5e2
* Version Independent ID: e3699917-899c-85fd-44f2-942b317cb8ff
* Content: [How to: Install and uninstall Windows services](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services)
* Content Source: [docs/framework/windows-services/how-to-install-and-uninstall-services.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-services/how-to-install-and-uninstall-services.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@baquick Thank you for letting us know and sorry to hear this didn't work for you. Did you try both installutil.exe and the PowerShell Remove-Service option? I saw a comment in another issue that the PowerShell option requires PowerShell version 6. Could you check your version of PowerShell using `$PSversionTable`?
