### ISSUE TITLE
Improve documentation of `volatile` keyword

### ISSUE THREAD

**Issue by kouvel** [dotnet/docs#24318]
Improve documentation of `volatile` keyword in `docs/csharp/language-reference/keywords/volatile.md` to clarify what it does and fix some inaccurate info.

-edit by @billwagner to add document block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d226514d-c7cb-0d1b-b9dc-fb791399dc47
* Version Independent ID: aa5d1078-7f89-98ce-7fdc-107c9ed3eebc
* Content: [volatile - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)
* Content Source: [docs/csharp/language-reference/keywords/volatile.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/volatile.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @BillWagner - should this have been closed from #24315?

**Comment by GrabYourPitchforks** [comment]
Thanks @kouvel for picking this up! I'm glad to see even more eyes on this. :)
