### ISSUE TITLE
Bug: Fix broken link in JsonDocument API doc, to point to this new article.

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/docs#24336]
@tdykstra  big thx for quick turnaround on https://github.com/dotnet/docs/pull/24291 !

I think you might want to link to this new article from:
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument?view=net-5.0#remarks

Note that the current link there gives 404: https://docs.microsoft.com/en-us/dotnet/standard/serialization/write-custom-serializer-deserializer

**Update**: I went ahead and made a PR: https://github.com/dotnet/dotnet-api-docs/pull/6759

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a13d38-4904-c068-c9eb-e43176ce5338
* Version Independent ID: c5dfa4d2-c77a-e752-dae7-0bfae5756b76
* Content: [How to use the JSON DOM, Utf8JsonReader, and Utf8JsonWriter in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter)
* Content Source: [docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
@tdykstra A redirection could be needed for the current 404 link.

**Comment by tdykstra** [comment]
@Youssef1313 Thanks, you're right we need a redirection, except it's already there, it just needs the redirect target URL to be fixed. 😄
