### ISSUE TITLE
some thing doesn't make sense

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/docs#24344]
i was reading the document and came across https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/interface-properties#sample-output.

![image](https://user-images.githubusercontent.com/18216790/119299791-4638e600-bc7d-11eb-9144-52657a59e713.png)

i don't understand what it is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e8e455c-1162-d046-ed70-22dfe96cbbad
* Version Independent ID: 9448a018-a06c-0ae5-049b-c4c424d1df9a
* Content: [Interface Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/interface-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/interface-properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/interface-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Looking at the sample output, I think it's supposed to be sample input to the application. But since that's not clear and since the sample output stands on its own, I have created a pull request to remove that line: https://github.com/dotnet/docs/pull/24348.

**Comment by BillWagner** [comment]
Thanks for reporting this @tnlthanzeel I will review @svick 's PR shortly.
