### ISSUE TITLE
Literal suffix is described as if it were a kind of cast

### ISSUE THREAD

**Issue by momochrome-t** [dotnet/docs#24345]
In this document, `25l` is treated as if it were a cast of `int` literal `25` to type `long` , but in fact it is a `long` literal, not a cast operation.

This is misleading and should be corrected so that it is clear that `25l` is a literal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c553bd2-148a-8715-99ee-ee6cb15f924a
* Version Independent ID: 44ea8d30-159c-6fb9-92e2-a9a33b5ac16b
* Content: [Compiler Warning (level 4) CS0078](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0078)
* Content Source: [docs/csharp/misc/cs0078.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0078.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Looking at the generated IL:

```il
    .method public hidebysig static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2052
        // Code size 9 (0x9)
        .maxstack 8

        IL_0000: ldc.i4.s 25
        IL_0002: conv.i8
        IL_0003: call void test::TestL(int64)
        IL_0008: ret
    } // end of method test::Main
```

This creates an Int32, then converts to Int64. But I agree this is a bit distractive.

**Comment by BillWagner** [comment]
Thanks for reporting this @momochrome-t and for providing the fix @Youssef1313 

I'll review the related PR shortly.
