### ISSUE TITLE
about numeric checking function

### ISSUE THREAD

**Issue by zerospaceeee** [dotnet/docs#24340]
why there is no such library function like isNumeric() or such thing? why do programmers need to do it all over again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e52e106-b266-73b5-7fe5-247399beeb24
* Version Independent ID: eb68a5cf-0474-2d65-eae2-9b42f03c411a
* Content: [How to determine whether a string represents a numeric value - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/how-to-determine-whether-a-string-represents-a-numeric-value)
* Content Source: [docs/csharp/programming-guide/strings/how-to-determine-whether-a-string-represents-a-numeric-value.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/how-to-determine-whether-a-string-represents-a-numeric-value.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
`int.TryParse(s, _)` (or `double.TryParse`)) would do the thing you want. Are there any problems you're having with this approach?

**Comment by zerospaceeee** [comment]
I know this approach, but this is a data converting function rather than a simple `is_a_number()` function. so I wonder why do we not have a built in function which directly checks if it is a number.
I think the approach that you mentioned is just a work around.

**Comment by BillWagner** [comment]
@zerospaceeee Thanks for the question. @Youssef1313 has provided the correct answer.

Closing as an answered question.
