### ISSUE TITLE
Incorrect Deconstruction Examples

### ISSUE THREAD

**Issue by mikewjohnson** [dotnet/docs#24353]
The first two examples in the `User-defined types` section are copy/pasted from earlier sections, but not updated to match the narrative of the new section. Examples should be updated with snippets from the "summary" example later in the section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fbaed1-06d8-16f0-70d1-97792daccfd5
* Version Independent ID: 830019b6-d46c-2867-9dbd-dd89a77dd7a4
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct)
* Content Source: [docs/csharp/fundamentals/functional/deconstruct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/deconstruct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @mikewjohnson and thanks for submitting the fix @Youssef1313 

I apologize for introducing this error. I thought I had caught all those while migrating the content.

I'll review the PR shortly.
