### ISSUE TITLE
Is IIS required for .net core application, why not just use kestrel? Can someone state pros vs cons of both please?

### ISSUE THREAD

**Issue by CSG-richard** [dotnet/docs#24368]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888b22d0-7261-c6fd-e4b3-07a4c1f66d06
* Version Independent ID: ddfcec03-a396-8851-49cd-629b9c7edc8a
* Content: [What OS to target with .NET containers](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/net-core-net-framework-containers/net-container-os-targets)
* Content Source: [docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/net-core-net-framework-containers/net-container-os-targets.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @CSG-richard, thank you for reaching out. 

No, you need to use the `kestrel` Web Server to host .NET Core/.NET 5 applications. To know more about the kestrel, you can refer [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=windows#kestrel)

Hope this helps !

**Comment by sughosneo** [comment]
Just to clarify the above statement further, it's not mandatory to use IIS to host the ASP.NET Core apps. You can use the Kestral web server as well.  For more details, please refer [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-5.0)

**Comment by sughosneo** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen, if needed. Thank you.
