### ISSUE TITLE
We need a way to determine if a file is actually as assembly without hitting GetAssemblyName

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/docs#24361]
GetAssemblyName OOMs in some cases most likely for native dlls (This is microsoft internal. I also see the same callstack in some external forums). 

We need a way to test whether a file is a .NET assembly before passing its path to GetAssemblyName or have GetAssemblyName handle this more gracefully (perhaps check the PE header). 

Are there known bugs in this space, alternatives that the page can be updated to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a3376a-0c7b-c6df-98e6-43ff2792f096
* Version Independent ID: f4510be4-b3de-f30a-67c8-96677409583d
* Content: [How to: Determine if a file is an assembly](https://docs.microsoft.com/en-us/dotnet/standard/assembly/identify)
* Content Source: [docs/standard/assembly/identify.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/identify.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @arkalyanms 
Thank you so much for posting this issue. We really appreciate it.

The [`GetAssemblyName` should work in most cases](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.getassemblyname?view=net-5.0#applies-to), what specific exception and stacktrace are you seeing - could you please share that?

**Comment by MSDN-WhiteKnight** [comment]
Try this with System.Reflection.Metadata nuget package:

        static bool IsAssembly(string path)
        {
            var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);

            using (var peReader = new PEReader(fs))
            {
                return peReader.HasMetadata;
            }
        }

It should only read PE header and unlikely to OOM, though i don't have large PE files to test.

**Comment by IEvangelist** [comment]
Hi again @arkalyan - did you get a chance to try out the recommendation from @MSDN-WhiteKnight ? This is really a product question, not a docs issue. If that suggestion doesn't work, we should either move this issue - or close this issue if it does.

**Comment by arkalyanms** [comment]
Thanks @MSDN-WhiteKnight and @IEvangelist. The PEReader route should work for me. Wouldn't it make sense for the official recommendation to be to check only the PE header if GetAssemblyName is known to have issues?

**Comment by MSDN-WhiteKnight** [comment]
If GetAssemblyName has issues with large assemblies, we'd need to prove this with a repro. For example, generate a large assembly with MetadataBuilder and try to pass the result to GetAssemblyName. But the MetadataBuilder could also OOM when trying to generate a large assembly, so it's not exactly easy.

However, i agree that we could consider updating this article with an additional way to check for managed assembly, using  PEReader.HasMetadata as i demostrated above. It also has advantage in that it does not use exceptions for logic (the exception is only thrown when the passed file is not a PE file at all). And it does not throw when assembly with the same identity is already loaded (on .NET Framework).

**Comment by IEvangelist** [comment]
Ah, I now have a better understanding of the concern. Before, I was admittedly a little confused. I'm going to mark this issue as `up-for-grabs`, and if either of you @arkalyanms or @MSDN-WhiteKnight feel inclined to propose a change to this article please tag me and reference this issue number. I'd happily review it -- thanks.
