### ISSUE TITLE
These instructions fail if you have a later version of IISExpress installed.

### ISSUE THREAD

**Issue by yowl** [dotnet/docs#24373]
If you also have VS2019 installed and hence a  later version of IISExpress , then these steps fail

![image](https://user-images.githubusercontent.com/2720041/119536361-9df35200-bd4e-11eb-96ed-fef75e474ca3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eea9da8-546f-74ac-34f4-f7a39bea1a1c
* Version Independent ID: 4e064376-f7a9-0de3-9315-2873f9c3df4c
* Content: [Azure tools for Visual Studio 2015](https://docs.microsoft.com/en-us/dotnet/azure/vs2015-install)
* Content Source: [docs/azure/vs2015-install.md](https://github.com/dotnet/docs/blob/main/docs/azure/vs2015-install.md)
* Product: **dotnet-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by scottaddie** [comment]
Closing, as this doc has been retired. Related to https://github.com/dotnet/docs/pull/25306.
