### ISSUE TITLE
What does <DefineConstants>$(DefineConstants);</DefineConstants>  do?

### ISSUE THREAD

**Issue by WillAutioItrax** [dotnet/docs#24370]
I found this
<DefineConstants>$(DefineConstants);</DefineConstants>
in a .csproj in a nuget and would like to know what it does. I expected to find the answer on this page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548e000-8190-b1bb-51fd-7e7b2d5bcb45
* Version Independent ID: 19f59267-c4c1-eb0e-7e48-45ffd6e2d9d1
* Content: [C# Compiler Options - language feature rules](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#defineconstants)
* Content Source: [docs/csharp/language-reference/compiler-options/language.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/language.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by WillAutioItrax** [comment]
Try again:
`<DefineConstants>$(DefineConstants);</DefineConstants>`

**Comment by Youssef1313** [comment]
I expect that `<DefineConstants>$(DefineConstants);</DefineConstants>` as-is should have no effect, it sets DefineConstants property to the value of `DefineConstants` followed by a semicolon. A trailing semicolon should probably have no effect, unless this workarounds some bug somewhere.

Did you find the snippet as-is? or you stripped something defined after the semi-colon?

**Comment by WillAutioItrax** [comment]
@Youssef1313 That is exactly how I found it. Your description of what it does makes sense. I thought maybe it does some other magic as there is a preprocessor statement:
`#if MONOANDROID10_0`
and I cannot find a Define for MONOANDROID10_0. I thought maybe the DefineConstants line was the answer...
Thanks for your reply.

**Comment by BillWagner** [comment]
Thanks for noting this @WillAutioItrax and for providing an answer @Youssef1313 

I'll close this as an answered question.

**Comment by BillWagner** [comment]
I should add for the future, the best place for general syntax on MSBuild properties is [here](https://docs.microsoft.com/visualstudio/msbuild/msbuild-properties?view=vs-2019) in the MSBuild docs.

**Comment by WillAutioItrax** [comment]
@BillWagner This started out as a comment about documentation that imo was missing from the docs page that I was on. I was not aware that it was a MSBuild issue. Had I known, then, I may have posted it in both places :- )
