### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cloewen8** [dotnet/docs#24380]
The first link to Infrastructure as Code is broken (https://docs.microsoft.com/en-us/azure/devops/learn/what-is-infrastructure-as-code).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09be1939-e2a5-241e-4114-8747b35f3d21
* Version Independent ID: 7d77200d-9764-cabc-d5c1-c4d2ba3c2fd1
* Content: [Infrastructure as code](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code)
* Content Source: [docs/architecture/cloud-native/infrastructure-as-code.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/infrastructure-as-code.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Youssef1313** [comment]
➡️ https://github.com/MicrosoftDocs/devops-resource-center/issues/47

(I would suggest to keep this open to do something in case the above issue wasn't fixed or to update the link to avoid double redirection in case it's fixed)

**Comment by gewarren** [comment]
This was fixed in https://github.com/dotnet/docs/pull/24650.
