### ISSUE TITLE
Trying to highlight code.

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#24407]
Trying to highlight code with my Super Simple Highlighter, an extension in my Chrome browser. Display really messesnter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@maryob77062 Can you please provide more details?

The docs site already highlights code (no need for extensions for that). See:

![image](https://user-images.githubusercontent.com/31348972/119615657-edde2180-bdff-11eb-80db-72d46a452602.png)

If there is a specific issue with an extension you're using, then I doubt there is a doc issue here.
