### ISSUE TITLE
Intro to C# Hello World!

### ISSUE THREAD

**Issue by Satellitel755** [dotnet/docs#24417]
[The exercises were very good at helping to understand and apply the concepts and commands for Writing output, searching for output, changing the output, and boolean responses.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8053bb96-cc40-8369-c07f-f9fd14060c1e
* Version Independent ID: 293260e2-f444-537b-0ba7-14d1fb6ebcf2
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/hello-world.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @Satellitel755 


Closing as kudos.
