### ISSUE TITLE
c# example is missing string[] customers for example #2

### ISSUE THREAD

**Issue by TXAE** [dotnet/docs#24422]
c# example is missing string[] customers for example #2
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651ba093-2cef-e0f6-be71-ffdf6551c2c4
* Version Independent ID: a4878d20-2a12-74ad-9fc0-9f589a44af35
* Content: [var - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var)
* Content Source: [docs/csharp/language-reference/keywords/var.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/var.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @TXAE 

I don't know that an additional example using an array is needed for greater understanding of `var`. 

I'll close, but if you feel strongly about adding an additional example, you can create a PR with that addition.
