### ISSUE TITLE
Table layout issue

### ISSUE THREAD

**Issue by bewillcott** [dotnet/docs#24420]
The "Serializable types" table layout along with the right-hand menu does not allow the viewing of more than the first column of the table.
Making the columns adjustable (width) would help.  But removing the right-hand menu would also help, to some extent.

Brad Willcott

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de3492d6-96b1-ee69-6c2d-a7c42f6da1a8
* Version Independent ID: eb7636b6-94dd-6f23-5993-b4df9088315f
* Content: [Binary serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization)
* Content Source: [docs/standard/serialization/binary-serialization.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/binary-serialization.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @ViktorHofer
* Microsoft Alias: **tdykstra**

**Comment by ViktorHofer** [comment]
What does Github Login mean in this context? 🤔

**Comment by bewillcott** [comment]
GitHub Login is not part of this issue.
GitHub is moving to two part authentication, though.

**Comment by ViktorHofer** [comment]
But why is my Github handle there?

**Comment by Youssef1313** [comment]
@ViktorHofer You're the article author per the metadata. This comes to your PR (https://github.com/dotnet/docs/pull/2841) few years ago.

**Comment by Youssef1313** [comment]
@bewillcott Are you viewing from a phone or a potentially small screen? This is how it looks on my screen:

![image](https://user-images.githubusercontent.com/31348972/119835932-9627df00-bf01-11eb-90a1-fa97ff0c883f.png)

**Comment by bewillcott** [comment]
Here is a screenshot - check the right-hand side of the screen:

![image](https://user-images.githubusercontent.com/57562137/122150542-7fd1cb00-ce90-11eb-9dcd-285246dec008.png)

**Comment by tdykstra** [comment]
I changed the table to allow line breaks in column 1. This will be on the live site tomorrow -- please verify that the table looks better.
