### ISSUE TITLE
package index page is not showing up in the top search results

### ISSUE THREAD

**Issue by elraikhm** [dotnet/docs#24436]
[Enter feedback here]
I work with the Azure SDK team and we received the following customer feedback. When searching for the list of packages, they are not finding the package list and go to the GitHub documentation instead
"Thinking about it, I think I’d blame Bing for that. When I search for “Azure management SDK”, the Git repo is the thing that shows up which sort of makes sense since it’d generally be the fresher content." 
Can we improve this page discoverability?
Consider queries such as:
azure client sdk libraries
Azure management SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57365270-0640-7e7d-2265-d740c194d05b
* Version Independent ID: 8d2d2671-869c-4848-4532-4aeae681e085
* Content: [Package index for Azure SDK for .NET](https://docs.microsoft.com/en-us/dotnet/azure/sdk/packages)
* Content Source: [docs/azure/sdk/packages.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/packages.md)
* Product: **dotnet-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@elraikhm Thanks for the feedback! I'll take a look and see if there are any SEO tricks we can do. 🙂
