### ISSUE TITLE
Code Analysis rule documentation should list all editorconfig names for a rule

### ISSUE THREAD

**Issue by Jehoel** [dotnet/docs#24437]
## <del>Old Issue description</del>

* <del>The documentation for CA1xxx rules do not state what their full `.editorconfig` rule names are.
  * <del>This makes it impossible to suppress or configure rules using `.editorconfig` [given that the Error List's Suppress and Configure menus are currently broken at-present](https://github.com/dotnet/roslyn/issues/45417) if you don't already know what the name is.
  * <del>Also, given that some rules (especially _code style_ rules) have both `IDE0000`-style names _and_ Editorconfig-standard names this makes things even more confusing.
  * <del>Additionally so when rules' names change between legacy FxCop, Roslyn-based, and NuGet-package-based releases.
* <del>Additionally, the generic example given in the documentation implies that every rule is under `dotnet_code_quality` **which is not true**, but it's used for every rule's documentation. For example, CA1054 is `dotnet_diagnostic.CA1054`, **not** `dotnet_code_quality.CA1054`. However I couldn't find any documentation for CA1054's full name - I found it out through trial-and-error.

### Ask 1: Please list all `.editorconfig` names for each rule (at the top of each page):

The documentation pages for both Code Analysis and Code Style do not clearly document **all** of the `.editorconfig` names for each rule.

Specifically, the problem I experienced is that each rule has **very different** names for setting a rule's options compared to setting a rule's severity or for suppressing it - which also differs from the name used for suppressing entire categories.

For example, for CA1000 (comments inline):

```
# If you want to disable CA1000 then you need this:
dotnet_diagnostic.CA1000.severity = none

# If you want to configure CA1000 then you need this:
dotnet_code_quality.CA1000.api_surface = private, intern

# If you want to suppress all rules in the same category then you need this:
dotnet_analyzer_diagnostic.category-Design.severity = none
```

For Code style it's even more inconsistent:

```
# If you want to disable IDE0058 then you need this:
dotnet_diagnostic.IDE0058.severity = none

# If you want to configure IDE0058 then you need this:
csharp_style_unused_value_expression_statement_preference = discard_variable

# ...but you can do this too:
csharp_style_unused_value_expression_statement_preference = discard_variable:none

# If you want to suppress all rules in the same category then you need this:
dotnet_analyzer_diagnostic.category-Style.severity = none
```

To clarify: I'm not complaining that the names are inconsistent (well, _I am_...), but I'm complaining that the documentation does not serve as a quick and easy reference to discover the other names of a rule.

So I'm asking for the info-table in every rule's documentation to show all 3 `.editorconfig` names (the specific rule's name, the name for when suppressing it or configuring its severity, and the name for when configuring its category's severity), as well as all available options in a succinct list.

So this:

![image](https://user-images.githubusercontent.com/1693078/119918803-f9c00580-bf1d-11eb-9e6e-48bbe50f9f9e.png)

Should be something like this:

![image](https://user-images.githubusercontent.com/1693078/119919024-663b0480-bf1e-11eb-98a3-f062b8504cf9.png)

## Ask 2: Include copypastable severity syntaxes in every rule page:

Given the most likely reason for visiting Code Analysis documentation is to figure out how to suppress a rule, I'd also like to see table rows containing copypastable suppression syntaxes, in all 3 formats:

* Preprocessor directive:
    * `#pragma warning disable CA1000 // Do not declare static members on generic types`
* Global Suppression File:
  *  `[assembly: SuppressMessage("Microsoft.Design","CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "Type")]`
* .editorconfig (single rule):
  *  `dotnet_diagnostic.CA1000.severity = none` (or `silent`)
* .editorconfig (entire rule category):
  *  `dotnet_analyzer_diagnostic.category-Design.severity = none` (or `silent`)

## Ask 3: Document the `.editorconfig` rule prefixes:

I would also like to see a page document why the rule name prefixes are different, and as they are different, what they represent. I'm asking because the names are not self-describing at all:
* `dotnet_diagnostic`
* `dotnet_analyzer_diagnostic`
* `dotnet_code_quality`

## Ask 4: The _Code quality rule configuration options_ page should also mention `severity`

The [_Code quality rule configuration options_](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/code-quality-rule-options) page should also have a section for configuring a rule's severity and/or how to suppress it, as I was under the mistaken belief that setting the `severity` uses the same syntax as setting an `OptionValue`.

**Comment by Youssef1313** [comment]
@Jehoel I believe that setting severity is done using `dotnet_diagnostic.ID.severity` for everything.

Can you be more specific about some page as an example that you think gives a wrong example or is missing some information?

**Comment by Jehoel** [comment]
@Youssef1313 

> Can you be more specific about some page as an example that you think gives a wrong example or is missing some information?

**All** of the CAxxxx pages give an example using `dotnet_code_quality` when for many (if not all? or many?) should be under `dotnet_diagnostic` instead.

**Comment by Youssef1313** [comment]
@Jehoel None of the pages suggests using `dotnet_code_quality.ID.severity`.

I see one disconnect here is that you think "severity" is applicable when a page says the word "option".

i.e, when the page says `dotnet_code_quality.OptionName = OptionValue`, it doesn't mean `dotnet_code_quality.severity`.

Regarding the code style names, for example the `csharp_prefer_simple_using_statement` you mentioned. It's documented in the IDE0063 page. So I don't quite understand why you think the following:

> As it is, I need to put this instead: (Notice how they have very different forms, a casual reader isn't going to know that they're both referring to the same rule unless someone adds a clarifying comment).

**Comment by Youssef1313** [comment]
Regarding the examples for `api_surface`, I believe the form mentioned in the docs is correct.

See for example this test:

https://github.com/dotnet/roslyn-analyzers/blob/0d8961a69316b92c263d2eb367f0d5fbdada5c69/src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs#L833-L848

If it's not working with you, then it may be a product issue/feedback rather than a  documentation issue.

**Comment by Jehoel** [comment]
> None of the pages suggests using `dotnet_code_quality.ID.severity`.  
> I see one disconnect here is that you think "severity" is applicable when a page says the word "option".

Yes, I concede you're correct.

... but there's nothing to suggest that `severity` **isn't** an option - or that it requires a totally different `.editorconfig` entry name.

> So I don't quite understand why you think...

Because using two completely different names to configure a rule and then to set its severity is inconsistent and completely non-obvious.

Regarding IDE0063 and `api_surface`, the issue isn't that those specific rules (CA1000 through CA1008) are under `dotnet_code_quality`, I stress that the documentation for those rules doesn't say that clearly enough, they use the same example lines that have "`CAXXXX`" which makes me think that _the entire line_ is a fictional or arbitrary example.

And while it's true the documentation page does say that IDE0063 has the name `csharp_prefer_simple_using_statement`, it **doesn't** tell me how I can set the rule's severity in `.editorconfig` - nor does it tell me if I should be using `dotnet_code_quality`, `dotnet_diagnostic`, or `dotnet_analyzer_diagnostic`. In order to find that out they all link to [this page](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings) which then gives a universal example that uses `dotnet_diagnostic` to set a rule's severity, but on my computer `dotnet_diagnostic` did not suppress the message, I needed to use `dotnet_analyzer_diagnostic` instead.

> If it's not working with you, then it may be a product issue/feedback rather than a documentation issue.

I maintain it's a documentation issue: there's no documentation for a given rule that states **all editorconfig names** for that rule.

**Comment by Youssef1313** [comment]
> but there's nothing to suggest that `severity` **isn't** an option

There is, but probably should be made more obvious. The rest of the article lists what options can be used. But noting that above may reduce confusion here.

---

> Because using two completely different names to configure a rule and then to set its severity is inconsistent and completely non-obvious.

The main issue here is that the compiler doesn't know anything about the code_style option names. All what the compiler knows is the rule id. This is the reason you have to use the rule id to set the severity. (You can use `option_name = value:severity`, but it works only in IDE since the compiler doesn't know about it, i.e, it doesn't work from command-line builds).

I believe @mavasani is working on enhancing things here in https://github.com/dotnet/roslyn/issues/52991.

Back to the docs, each IDExxxx page mentions the option names (if any) for this rule, it however, don't mention how to change the severity. Tagging @gewarren to consider adding a link to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings in all IDExxxx pages, as well as updating the same page to have some examples for IDExxxx (it's the same as CAxxxx, but just to make the reader know that the page is applicable to both IDE and CA analyzers)


---

> but on my computer dotnet_diagnostic did not suppress the message, I needed to use dotnet_analyzer_diagnostic instead.

`dotnet_diagnostic` is the correct form to suppress a particular rule of a given ID, while `dotnet_analyzer_diagnostic` is the correct form to bulk-suppress either all analyzers or a given category. So if you have used `dotnet_analyzer_diagnostic` to suppress a specific rule with specific id, then my guess it's a product issue rather than a doc issue.

**Comment by Jehoel** [comment]
BTW, @Youssef1313 Thank you for putting up with my opinionated documentation rants and stresses tonight (it's 1am now...) and working with me to to educate me on the right answer!

**Comment by Youssef1313** [comment]
Welcome @Jehoel 

So to summarize things that needs to be modified in docs:

- Update https://docs.microsoft.com/dotnet/fundamentals/code-analysis/code-quality-rule-options to early say that the option should be one of the listed below.
- Add a link to https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings in every rule doc page
- Update https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings to mention that it's applicable to IDExxxx, CAxxxx, and third-party analyzers as well.


Is there something else you would like to be addressed @Jehoel ?

**Comment by Jehoel** [comment]
@Youssef1313 I have rewritten my initial post so it now accurately describes the problems I experienced and how things could be made better for others in future.

-----------

> Update https://docs.microsoft.com/dotnet/fundamentals/code-analysis/code-quality-rule-options to early say that the option should be one of the listed below.

Yes, I've written that up as the 4th item [in my edited post](https://github.com/dotnet/docs/issues/24437#issue-904538140).

-----------

> Add a link to https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings in every rule doc page

That link already exists. What I'm asking for is for a copypastable snippet in every rule's page instead.

So instead of this:

> ## Suppress a warning
> There are various ways to suppress a code analysis warning, including disabling the rule for the project, using a preprocessor directive to disable it for a specific line of code, or by applying the [SuppressMessageAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute) attribute. For more information, see [How to suppress code analysis warnings](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/suppress-warnings).

It should be something like this (note how there are no placeholders, every identifier and reference to the current rule is specific and correct):

> ## Suppress a warning
> ### Using `#pragma`
> ```
>#pragma warning disable CA1000 // Do not declare static members on generic types
> ```
> ### Using `.editorconfig`
> ```
> [*.cs]
> # This suppresses this specific rule
> dotnet_diagnostic.CA1000.severity = none
> # This suppresses this rule's entire category
> dotnet_analyzer_diagnostic.category-Design.severity = none
> ```
> ### Using `[SuppressMessage]`
> ```
> // This suppresses the rule assembly-wide:
> [assembly: SuppressMessage("Usage", "CA1000:Do not declare static members on generic types", Justification = "TODO")]
> // This suppresses the rule on a single type:
> public class GenericType<T>
> {
>    [SuppressMessage("Usage", "CA1000:Do not declare static members on generic types", Justification = "TODO")]
>    public static void Foo() {}
> }
> ```
> For more information, see [How to suppress code analysis warnings](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/suppress-warnings).

-----------

> Update https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings to mention that it's applicable to IDExxxx, CAxxxx, and third-party analyzers as well.

Yes please.

**Comment by Youssef1313** [comment]
> That link already exists.

It doesn't exist in all pages, for example IDE0063. I expect this to be an issue for IDExxxx in general.

**Comment by Youssef1313** [comment]
> The [_Code quality rule configuration options_](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/code-quality-rule-options) page should also have a section for configuring a rule's severity and/or how to suppress it, as I was under the mistaken belief that setting the `severity` uses the same syntax as setting an `OptionValue`.

Note that the first paragraph of the page states this page isn't about setting severity, and links to another page.

> The *code quality* rules have additional configuration options, besides just [configuring their severity](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/configuration-options#severity-level). For example, each code quality analyzer can be configured to only apply to specific parts of your codebase. You specify these options by adding key-value pairs to the same [EditorConfig](https://editorconfig.org) file where you specify rule severities and general editor preferences.

**Comment by gewarren** [comment]
Asks 1, 2, and 4 have been addressed or will be when the linked PRs are merged. Part of ask 1 is separated out into #29916. Please open a separate issue for ask 3 if you still feel that is needed - although there isn't really much to say about each prefix except where it's used.
