### ISSUE TITLE
Problem with the Debug provider section text.

### ISSUE THREAD

**Issue by explorest** [dotnet/docs#24438]
Here is the problematic sentence: 
"The Debug provider writes log output by using the System.Diagnostics.Debug class. Calls to System.Diagnostics.Debug.WriteLine write to the Debug provider."

It sounds circular. 
The first sentence is telling us that the Debug provider uses the System.Diagnostics.Debug class. 
The second sentence is telling us that calling a Debug class's method (WriteLine) writes to the Debug provider. 

So which one is it. Debug provider using Debug class --- or Debug class writing to Debug provider ?
[P.S: I'm sure that answer must be simple --- but the text itself is logically circular , and confused me].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155ef66b-e8ad-be8b-74be-70a8a140d009
* Version Independent ID: a4125a45-d644-dd78-0d08-5f71eb24d494
* Content: [Logging providers in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging-providers#debug)
* Content Source: [docs/core/extensions/logging-providers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging-providers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @explorest 
Thank you so much for posting this issue. We really appreciate it. From the sounds of it, you're right. I'll investigate this a bit more, verify the source code and propose a fix to address this. Thanks again
