### ISSUE TITLE
Confusing install steps for linux

### ISSUE THREAD

**Issue by alexdresko** [dotnet/docs#24447]
We just had a _spirited_ conversation during our Friday afternoon beer meeting wherein two of us (myself included) didn't feel like it was our fault for clicking the wrong link to install .NET Core on linux  (specifically wsl2). 

The problem is we're impatient. We're trying to figure out how to install linux in a hurry, and we invariably land on [this page](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu). Unfortunately, we don't see the text that says, "For more information on installing .NET without a package manager, see one of the following articles:". Instead, because we're in a hurry, we see these links:

![image](https://user-images.githubusercontent.com/333022/120042496-32241a00-bfd8-11eb-829e-0ef7d64531d7.png)

And none of them provide the experience we're looking for. If we were good developers, we'd take our time and look for this information: 

![image](https://user-images.githubusercontent.com/333022/120042614-70b9d480-bfd8-11eb-8096-af73046f313b.png)

So, I'm creating this issue to see if you can prevent my friend and I from finding the wrong documentation every time.  It's happened multiple times, and apparently we don't learn our lessons quickly enough. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Greetings! Thank you for opening this issue. I feel like I'm missing out, not being included in beer friday! 😁 🍺 

If I understand what you're saying, it's that you're on WSL2, Ubuntu, and you open the article and that text of "Install the .NET SDK" pops out at you and you click it, not really seeing the paragraph above it.

Correct?

**Comment by alexdresko** [comment]
Correct. I wish I could blame it on the alcohol, but I've done this multiple times now. I don't drink so much that I'm inebriated every time I need to install .NET on WSL. :)

**Comment by adegeo** [comment]
OK, next week I'll look at getting something adjusted on this to help.
