### ISSUE TITLE
Microsoft Gift At Last

### ISSUE THREAD

**Issue by biryazilim** [dotnet/docs#24454]
[Thank you Very Much Microsoft, Enabling User With Native compiled Net 5 which CAN NOT BE DECOMPILED anyhow..]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1932751-7c2b-ce92-936e-e97f8581d5fa
* Version Independent ID: de677d1f-386a-e4c3-fdd0-6806b3ef2c0e
* Content: [Single file application - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)
* Content Source: [docs/core/deploying/single-file.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/single-file.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @LakshanF
* Microsoft Alias: **lakshanf**

**Comment by svick** [comment]
For the record, single-file executables don't prevent decompilation. You can use ILSpy (and possibly other tools) to decompile them.
