### ISSUE TITLE
The code examples in the namespace guide are all the same copied code

### ISSUE THREAD

**Issue by rafael-lua** [dotnet/docs#24456]
All the code snippets as examples for the namespace guide are the same repeated code in the whole explanation in the fundamentals section. Would be very good to have it corrected as it is used by new people learning the language or referencing the core concepts.

```csharp
//<Snippet1>
using System;
//</Snippet1>

namespace namespaces
{
    class Program
    {
        static void Main(string[] args)
        {
        //<Snippet22>
        System.Console.WriteLine("Hello World!");
        //</Snippet22>
        }
    }
}

//<Snippet6>
namespace SampleNamespace
{
    class SampleClass
    {
        public void SampleMethod()
        {
            System.Console.WriteLine(
                "SampleMethod inside SampleNamespace");
        }
    }
}
//</Snippet6>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176f6e77-fdd7-5f97-feb3-5376c85baa5a
* Version Independent ID: fc865789-6896-4cf5-7cdf-2080047563e4
* Content: [Organizing types in namespaces](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/namespaces)
* Content Source: [docs/csharp/fundamentals/types/namespaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @rafael-lua 

I plan on updating many of the articles in this section this month. I'll make sure to address this as part of those updates.
