### ISSUE TITLE
What is the point of the step 9?

### ISSUE THREAD

**Issue by paszesoft** [dotnet/docs#24462]
Not sure what is the purpose of the step 9:

> Select Errors in the margin at the bottom of the IDE window to open the Errors panel. Select the Build Output button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9a3cb6-677e-cf6f-9435-d4a5d772b28e
* Version Independent ID: 099ac29a-0b6e-a640-a32c-3714ee66b641
* Content: [Create a .NET class library using Visual Studio for Mac - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-mac)
* Content Source: [docs/core/tutorials/library-with-visual-studio-mac.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio-mac.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The purpose of step 9 is to make sure that you can see the build output in step 10.
