### ISSUE TITLE
Case sensitivity in NetCore.Docker.dll

### ISSUE THREAD

**Issue by aman-singh-parihar** [dotnet/docs#24466]
I got issue while running the container and it was due to the case sensitivity of the dll.
When I have built the project, Netcore.Docker.dll created, not NetCore.Docker.dll.
So the letter "c" should be lowercase in this line of code in the docker file.

ENTRYPOINT ["dotnet", "NetCore.Docker.dll"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment]
When you created the app, are you sure you ran `dotnet new console -o App -n NetCore.Docker`, not `dotnet new console -o App -n Netcore.Docker`?

**Comment by aman-singh-parihar** [comment]
> When you created the app, are you sure you ran `dotnet new console -o App -n NetCore.Docker`, not `dotnet new console -o App -n Netcore.Docker`?

Yes, you are right, I have checked my previous commands and its typo mistake.
Thanks.
