### ISSUE TITLE
Bad installation instructions page

### ISSUE THREAD

**Issue by LucaGabi** [dotnet/docs#24470]
[Enter feedback here]
How to actually install sdk 3.1 while navigating the links for ubuntu 18.04 ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu#1804-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! Does the [How to install other versions](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu#how-to-install-other-versions) section help? You would replace your package name in the commands listed for 18.04 with the appropriate package.

```
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0      <---- package name
```
You would instead use (on that specific line)
```
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-3.1
```
