### ISSUE TITLE
An Incorrect Typo on the Simplified Chinese Translation

### ISSUE THREAD

**Issue by gehongyan** [dotnet/docs#24485]
**Issue description**

The Simplified Chinese translation contains an incorrect typo on this page

> Simplified Chinese: [https://docs.microsoft.com/zh-cn/dotnet/visual-basic/whats-new/?source=docs#visual-basic-15](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/whats-new/?source=docs#:~:text=Visual%20Basic%2015-,%E5%85%83%E7%A5%96,-%E5%85%83%E7%BB%84%E6%98%AF)

**Tuples** means **元组**, but not **元祖**. **元祖** may mean **ancestor**. **元组** could refer to the data structure.

The related English version

> English: [https://docs.microsoft.com/en-us/dotnet/visual-basic/whats-new/?source=docs#visual-basic-15](https://docs.microsoft.com/en-us/dotnet/visual-basic/whats-new/?source=docs#:~:text=Visual%20Basic%2015-,Tuples,-Tuples%20are%20a)

**Comment by Youssef1313** [comment]
cc @JasonCard

**Comment by JasonCard** [comment]
Hello @gehongyan 
 
Thank you for your contribution!  Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding Microsoft team and will close this one.
 
Kind regards,
Microsoft DOCS Global Experience Team
