### ISSUE TITLE
Incorrect example for TreatWarningsAsErrors tag

### ISSUE THREAD

**Issue by kemaleq** [dotnet/docs#24488]
The example code for TreatWarningsAsErrors is:

`<TreatWarningsAsErrors></TreatWarningsAsErrors>`

This will not work since it turns out that the field is actually a boolean field, the check is done for the value inside not just the existence of the tag.

The example of a working code would be:

`<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this and creating the corresponding PR @kemaleq 

I'll review the PR shortly.
