### ISSUE TITLE
Missing "/" in Closing Tag for ValidateExecutableReferencesMatchSelfContained 

### ISSUE THREAD

**Issue by daalcant** [dotnet/docs#24487]
Missing "/" at the beginning of ValidateExecutableReferencesMatchSelfContained closing tag under Recommended Action section.

Currently shows
`<ValidateExecutableReferencesMatchSelfContained>false<ValidateExecutableReferencesMatchSelfContained>`

Should be
`<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69fc8742-edcf-b1d1-91bc-212ecdf5622f
* Version Independent ID: b168d63a-d3e7-1b6f-ec2b-24a97682809f
* Content: [Breaking change: Error generated when executable references executable - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/referencing-executable-generates-error)
* Content Source: [docs/core/compatibility/sdk/5.0/referencing-executable-generates-error.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/5.0/referencing-executable-generates-error.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you! This has been fixed.
