### ISSUE TITLE
chanchaichoochuay9033@gmail.com

### ISSUE THREAD

**Issue by Yoon455** [dotnet/docs#24490]
**Issue description**

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
@Yoon455 Did you open this by mistake? Is there more information you wanted to add here?
