### ISSUE TITLE
Says method must be static but instance method shown..

### ISSUE THREAD

**Issue by dazinator** [dotnet/docs#24496]
It says as a constraint that:

> Logging methods must be static, partial, and return void.

But the same page shows that you can use instance level method not just static methods so I am confused.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc4ecf0-19e4-54d3-c34e-b6eadb80262b
* Version Independent ID: decc74aa-a2d5-8727-f22b-3862bacde737
* Content: [Compile-time logging source generation](https://docs.microsoft.com/en-gb/dotnet/core/extensions/logger-message-generator)
* Content Source: [docs/core/extensions/logger-message-generator.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logger-message-generator.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @maryamariyan
* Microsoft Alias: **maariyan**

**Comment by gewarren** [comment]
@maryamariyan Can you clarify this?

**Comment by maryamariyan** [comment]
@dazinator thanks for the feedback.

It does not need to be static, but must be partial and return void. 

As explained lower down in the same docs page (shown below as a snippet), it would only need to be static if the logger method has an ILogger argument:

> In the preceding example, the logging method is static and the log level is specified in the attribute definition. When using the attribute in a static context, the ILogger instance is required as a parameter. You may choose to use the attribute in a non-static context as well. Consider the following example where the logging method is declared as an instance method. In this context, the logging method gets the logger by accessing an ILogger field in the containing class.
