### ISSUE TITLE
Document the ability to deserialize into JsonElement properties

### ISSUE THREAD

**Issue by ohadschn** [dotnet/docs#24501]
Somewhat related to overflow deserialization, we can also do this (using a similar example as the [overflow page](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-handle-overflow)):

```cs
public class WeatherForecast
{
    public DateTimeOffset Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string Summary { get; set; }
    public JsonElement DatesAvailable { get; set; }    // <= serialize generic JSON array
    public JsonElement SummaryWords { get; set; }  // <= serialize generic JSON element
}
```

```json
{
  "Date": "2019-08-01T00:00:00-07:00",
  "TemperatureCelsius": 25,
  "Summary": "Hot",
  "DatesAvailable": [
    "2019-08-01T00:00:00-07:00",
    "2019-08-02T00:00:00-07:00"
  ],
  "SummaryWords": {
    "Cool": "Stuff",
    "Windy": "Wind",
    "Humid": "Water"
  }
}
```

I couldn't find this capability documented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#how-to-read-json-as-net-objects-deserialize)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion! It does seem somewhat related to overflow JSON, so I'm putting it in that article.
