### ISSUE TITLE
docker build using instructions provided returns error 127

### ISSUE THREAD

**Issue by tristanbarcelon** [dotnet/docs#24504]
[Enter feedback here]

I created a Dockerfile intended as a .net core 3.1 runtime image with diagnostic tools so developers can use them. However, running docker build produces error 127.

```Dockerfile
#escape=\
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic AS build

WORKDIR /tools

# Install desired .NET CLI diagnostics tools
RUN dotnet tool install --tool-path /tools dotnet-trace
RUN dotnet tool install --tool-path /tools dotnet-counters
RUN dotnet tool install --tool-path /tools dotnet-dump
RUN dotnet tool install --tool-path /tools dotnet-gcdump
RUN dotnet tool install --tool-path /tools dotnet-stack
RUN dotnet tool install --tool-path /tools dotnet-sos

RUN wget -P /tools https://aka.ms/perfcollect \
    && chmod +x /tools/perfcollect \
    && /tools/perfcollect install

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS runtime

# Copy diagnostics tools
WORKDIR /tools
COPY --from=build /tools .
```
This is the error I get.

C:\powershell>docker build --pull --tag dotnet/core/runtime:3.1-with-diagnostic-tools --file netcore3.1diagnostics.Dockerfile .
[+] Building 0.9s (8/16)
 => [internal] load build definition from netcore3.1diagnostics.Dockerfile                                         0.0s
 => => transferring dockerfile: 820B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic                                   0.5s
 => [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-bionic                                      0.4s
 => [build 1/9] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic@sha256:3baef14dc2da7b7be785c760f5c4bd8003e9fa6a  0.0s
 => CANCELED [runtime 1/3] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic@sha256:12f8349504329272d8480eef3e  0.3s
 => => resolve mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic@sha256:12f8349504329272d8480eef3edb4923fae66f2d207  0.0s
 => => sha256:3026c1dc8908dea47e46a1789d4ffedc64dbb951d29a703f2bc26ac40b5b4e4d 0B / 16.55MB                        0.2s
 => => sha256:d2a18b3c58362dcff20c166d212192a57d65164679c34532665050e11864aa75 0B / 2.55MB                         0.2s
 => => sha256:cdb88c58d75ee589a7555ef29a9adbaacb3a910c7cb275d60b629644c7701486 6.38kB / 6.38kB                     0.0s
 => => sha256:70dd8499c23842e804a304f4236d7e61893d6b8b79843e4b0c78ebf7992d1659 0B / 31.29MB                        0.2s
 => => sha256:12f8349504329272d8480eef3edb4923fae66f2d20720c71c634326b563074b4 1.79kB / 1.79kB                     0.0s
 => CACHED [build 2/9] WORKDIR /tools                                                                              0.0s
 => ERROR [build 3/9] RUN dotnet tool install --tool-path /tools dotnet-trace                                      0.3s
 > [build 3/9] RUN dotnet tool install --tool-path /tools dotnet-trace:
#8 0.266 /bin/sh: 1: dotnet tool install --tool-path /tools dotnet-trace: not found
executor failed running [/bin/sh -c dotnet tool install --tool-path /tools dotnet-trace]: exit code: 127

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb469ec9-2273-52d7-059d-8288eb6d8db5
* Version Independent ID: d24b97d5-8931-408e-20e0-78c4787365c0
* Content: [Collect diagnostics in containers](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/diagnostics-in-containers)
* Content Source: [docs/core/diagnostics/diagnostics-in-containers.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/diagnostics-in-containers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by tristanbarcelon** [comment]
When running mcr.microsoft.com/dotnet/core/sdk:3.1-bionic interactively, the dotnet tool install command succeeds.

```cmd
C:\powershell>docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
root@1e192ef6ff56:/# dotnet tool install --tool-path /tools dotnet-trace
You can invoke the tool using the following command: dotnet-trace
Tool 'dotnet-trace' (version '5.0.221401') was successfully installed.
```

**Comment by adegeo** [comment]
@tristanbarcelon Sorry for the delay on this, it seems this slipped through the cracks. You may have better luck and a quicker response for these types of questions on StackOverflow.

Looking at the error it seems like the `dotnet` command is resolving incorrectly? Are you able to add something simple before the tool installs like `RUN dotnet --version`?
