### ISSUE TITLE
Github Link is not working

### ISSUE THREAD

**Issue by sarul84** [dotnet/docs#24507]
Github link given in the tutorial is not working, please update it with working link.

https://github.com/dotnet/docs/tree/main/docs/csharp/tutorials/intro-to-csharp/snippets/object-oriented-programming

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbffd459-5fa3-35b6-eb99-c0bc3b19f479
* Version Independent ID: 15aa3a87-9f24-e233-ee77-057953a66f6a
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/oop)
* Content Source: [docs/csharp/fundamentals/tutorials/oop.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/oop.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@sarul84 I believe the new link should be https://github.com/dotnet/docs/tree/main/docs/csharp/fundamentals/tutorials/snippets/object-oriented-programming.


@BillWagner When fixing this, it's worth noting that both `.ghal.rules.json` and `docfx.json` will need to update `intro-to-csharp` to reflect the new path.
