### ISSUE TITLE
Fix the code example formatting

### ISSUE THREAD

**Issue by Sanx78** [dotnet/docs#24515]
The formatting of the examples - especially commented lines - makes the examples almost impossible to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a9a526-9135-db6b-f84b-ae52ab0876c4
* Version Independent ID: 550522d6-32ca-b8ba-7c37-5ad054102f0a
* Content: [Asynchronous Programming with Async and Await - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)
* Content Source: [docs/visual-basic/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/concepts/async/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
@Sanx78 The commented lines is a known problem unfortunately. Is there something you think could be improved other than comments highlighting?

cc @IEvangelist

**Comment by BillWagner** [comment]
@mimisasouvanh Where should this be routed? It's primarily about the VB formatting in highlight.js.

**Comment by gewarren** [comment]
This has been fixed, as far as I can tell. Related issue: https://github.com/dotnet/dotnet-api-docs/issues/6777.
