### ISSUE TITLE
string from

### ISSUE THREAD

**Issue by josan84** [dotnet/docs#24526]
Hi,

Why is the 'from' variable highlighted in blue in this page, is it a keyword? I understand that it is a keywork in a LINQ context, but it seems a variable here...

Thanks
Jose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8b6ec6-3773-879a-00e9-4bf113b9f362
* Version Independent ID: 5c46289d-8473-623f-eb42-8bda01c30c63
* Content: [Observer Design Pattern](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern)
* Content Source: [docs/standard/events/observer-design-pattern.md](https://github.com/dotnet/docs/blob/main/docs/standard/events/observer-design-pattern.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment]
➡️ https://github.com/highlightjs/highlight.js/issues/3230

**Comment by IEvangelist** [comment]
Hi @josan84 - this is a known bug in the syntax highlighting. I'm going to close this as it is not being tracked here. Thank you
