### ISSUE TITLE
Some information is too hidden

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2452]
I was searching through docs.MS looking for detailed documentation about attributes in C# and couldn't find it. Eventually, I found out that the information I was looking for was in https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/, but I think that finding it required way too much effort:

* Using the top-right search box, [searching for "Attributes" returns 0 results](https://docs.microsoft.com/en-us/search/index?search=Attributes&scope=.NET) (!).
* From [the C# Guide article](https://docs.microsoft.com/en-us/dotnet/csharp/index), searching the TOC shows, among others, the .Net, VB and F# articles about attributes, but not the C# one.
* To navigate from the C# Guide to the Attributes article, I have to go through [C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/) (how is that different from "C# Guide"?) and [Programming Concepts (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/) (didn't the "C# programming guide" also contain some programming concepts? also how is this different from the "C# Concepts" section in the TOC under C# Guide?), which I think is too many steps and way too confusing.

**Comment by GuardRex** [comment]
Since it also pertains to search, we may as well cross-reference https://github.com/dotnet/docs/issues/2423. (I'm curious about the role of metadata keywords for internal search/filtering.)

**Comment by mairaw** [comment]
Issue `#1` is fixed
Issue `#2` is something that we asked for the team to improve filter. I'll see if I need to file a new request for that.
Issue `#3` is just due to how content was organized on msdn. We need to reorganize the content here now,

**Comment by mairaw** [comment]
I think this experience has improved with the changes we've been making to the site, so closing.

But please let us know if there's something else that should be improved @svick.

**Comment by mairaw** [comment]
Reopened by mistake.
