### ISSUE TITLE
Clicking the "Next" button skips the "Logging differences" section

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [dotnet/docs#24530]
[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: b07f091e-3e07-cb06-52a1-71e25c8cd15e
* Version Independent ID: 2af732c7-5539-5e33-e5e5-d0febd1e843f
* Content: [Routing differences between ASP.NET MVC and ASP.NET Core](https://docs.microsoft.com/da-dk/dotnet/architecture/porting-existing-aspnet-apps/routing-differences)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/routing-differences.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/routing-differences.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @BoSoeborgPetersen, thank you for the feedback. Closing this issue as the changes are merged already.
