### ISSUE TITLE
Socket Server sample uses old APM style instead of async

### ISSUE THREAD

**Issue by erikmartinessanches** [dotnet/docs#24537]
This example uses an old asynchronous programming model (APM) pattern that is no longer recommended and should be updated to the Task-based asynchronous pattern (TAP) that is recommended for new development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
Related to #21146
