### ISSUE TITLE
C Sharp

### ISSUE THREAD

**Issue by oluwafemi-coder** [dotnet/docs#24538]
static void Main()
    {
        // Declaration statement.
        int counter;

        // Assignment statement.
        counter = 1;

        // Error! This is an expression, not an expression statement.
        // counter + 1;

        // Declaration statements with initializers are functionally
        // equivalent to  declaration statement followed by assignment statement:
        int[] radii = { 15, 32, 108, 74, 9 }; // Declare and initialize an array.
        const double pi = 3.14159; // Declare and initialize  constant.

        // foreach statement block that contains multiple statements.
        foreach (int radius in radii)
        {
            // Declaration statement with initializer.
            double circumference = pi * (2 * radius);

            // Expression statement (method invocation). A single-line
            // statement can span multiple text lines because line breaks
            // are treated as white space, which is ignored by the compiler.
            System.Console.WriteLine("Radius of circle #{0} is {1}. Circumference = {2:N2}",
                                    counter, radius, circumference);

            // Expression statement (postfix increment).
            counter++;
        } // End of foreach statement block
    } // End of Main method body.
} // End of SimpleStatements class.
/*
   Output:
    Radius of circle #1 = 15. Circumference = 94.25
    Radius of circle #2 = 32. Circumference = 201.06
    Radius of circle #3 = 108. Circumference = 678.58
    Radius of circle #4 = 74. Circumference = 464.96
    Radius of circle #5 = 9. Circumference = 56.55
*/
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff0d7fd-3319-2d27-d89a-e92f6ce1285a
* Version Independent ID: b9a529ef-7ba1-6abf-55cf-c6e54935ae66
* Content: [Statements - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/statements)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/statements-expressions-operators/statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
:wave: @oluwafemi-coder 

Did you open this by accident? I'm not seeing any request to change the content.

Let us know if we should just close this.

**Comment by oluwafemi-coder** [comment]
Am sorry, I was have a little problem with my PC.

**Comment by BillWagner** [comment]
closing per customer comment.
