### ISSUE TITLE
Clicking the "Next" button leads back to "Routing differences"

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [dotnet/docs#24531]
[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: dc53c8d6-636b-c699-0ef9-50a754c7edb8
* Version Independent ID: a0cb942b-e04b-6621-9fbd-2875af862c5b
* Content: [Logging differences between ASP.NET MVC and ASP.NET Core](https://docs.microsoft.com/da-dk/dotnet/architecture/porting-existing-aspnet-apps/logging-differences)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/logging-differences.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/logging-differences.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @BoSoeborgPetersen, thank you for the feedback. Closing this issue as the changes are merged already.
