### ISSUE TITLE
Clicking the "Next" button skips the "More migration scenarios" section.

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [dotnet/docs#24534]
[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: e3399e2a-4993-96d4-cc3b-50be77d3bbcd
* Version Independent ID: 5cea2482-c0ef-a804-ab26-82acdac121e5
* Content: [Example migration of eShop to ASP.NET Core](https://docs.microsoft.com/da-dk/dotnet/architecture/porting-existing-aspnet-apps/example-migration-eshop)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/example-migration-eshop.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/example-migration-eshop.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @BoSoeborgPetersen, thank you for the feedback. Closing this issue as the changes are merged already.
