### ISSUE TITLE
NEW NEW

### ISSUE THREAD

**Issue by ArashAmini345** [dotnet/docs#24532]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a86375-5077-1031-4262-65c9ff1db985
* Version Independent ID: 06488d45-19ec-f12c-0cbb-82c9bf133bb0
* Content: [Compiler Error CS0029](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0029?f1url=%3FappId%3Droslyn%26k%3Dk(CS0029))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0029.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0029.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Can you add some description in the issue to be more clear about what this is about?
