### ISSUE TITLE
IOptionsMonitor in example doesn't update config in existing Loggers

### ISSUE THREAD

**Issue by hannahchan** [dotnet/docs#24533]
The current example for `ColorConsoleLoggerProvider` which uses`IOptionsMonitor<ColorConsoleLoggerConfiguration>` doesn't update the config for existing loggers that have already been instantiated and stored in `_loggers`. When the configuration changes, these loggers continue to reference the old `ColorConsoleLoggerConfiguration` instance and only the new instances take on the configuration change.

One suggestion to fix this is to update the following line in the constructor from;

```C#
_onChangeToken = config.OnChange(updatedConfig => _currentConfig = updatedConfig);
```

to;

```C#
_onChangeToken = config.OnChange(updatedConfig =>
{
    _currentConfig = updatedConfig;
    _loggers.Clear();
});
```

Other than that, I'm wondering if there are best practices that other developers like me should know about when implementing a custom logging provider. For example, how to make an async HTTP request to a logging backend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @hannahchan
Thank you so much for posting this issue. We really appreciate it.

You're absolutely right, this is a bug in the example code - I'll work on updating this article and report back when the fix is merged. Thanks again

**Comment by IEvangelist** [comment]
Hi again @hannahchan - what do you think about https://github.com/dotnet/docs/pull/24774?

**Comment by hannahchan** [comment]
> Hi again @hannahchan - what do you think about #24774?

Looks good to me. Awesome work! Thanks.
