### ISSUE TITLE
Missing section Conversion Keywords

### ISSUE THREAD

**Issue by JanRajnoha** [dotnet/docs#24540]
CType doc page missing section Conversion Keywords, which is in DirectCast and TryCast. It provides faster navigation between casting operators and summary about all casting operators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab1603f5-5c9e-3c0c-50aa-5efe3b5bb8e1
* Version Independent ID: 2a1c48e5-5fd4-0991-2948-b2b73bdec3de
* Content: [CType Function - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/functions/ctype-function)
* Content Source: [docs/visual-basic/language-reference/functions/ctype-function.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/functions/ctype-function.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for noting this @JanRajnoha 


I've added this to our backlog, and added the "up for grabs" label in case any community members want to address this.

**Comment by KevRitchie** [comment]
Hi @BillWagner, I'm happy to pick this one up and add the missing section.

**Comment by BillWagner** [comment]
Thanks @KevRitchie I'll watch for a PR.
