### ISSUE TITLE
The article Collectible Assemblies for Dynamic Type Generation should be migrated

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2454]
The MSDN article [Collectible Assemblies for Dynamic Type Generation](https://msdn.microsoft.com/en-us/library/dd554932(vs.100).aspx) exists only in an old, unmaintained version and so it has not been migrated to docs.MS.

It contains very specific information that is, AFAICT, not available elsewhere in the docs, so I think it should be migrated.

See also: https://github.com/dotnet/docs/pull/2444#issuecomment-309811321.

cc: @rpetrusha

**Comment by rpetrusha** [comment]
I'm going to schedule this with a July milestone.

cc: @svick
