### ISSUE TITLE
"Target frameworks in SDK-style projects" appears out of date for older versions of .NET Core

### ISSUE THREAD

**Issue by brnhensley** [dotnet/docs#24544]
With .NET 5.0 installed it doesn't appear I can use target frameworks older than `netcoreapp3.1`. I get an invalid parameter error when trying any of the older version listed as options.

```bash
$ dotnet new webapi -f netcoreapp3.0
Couldn't find an installed template that matches the input, searching online for one that does...
Error: Invalid parameter(s):
-f netcoreapp3.0
    'netcoreapp3.0' is not a valid value for -f (Framework).
```

`net5.0` and `netcoreapp3.1` work, but I get the same error for all of these:

```
netcoreapp1.0
netcoreapp1.1
netcoreapp2.0
netcoreapp2.1
netcoreapp2.2
netcoreapp3.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/main/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tdykstra** [comment]
@vlada-shubina To use `dotnet new` to create a project that targets an older unsupported version is there a template that you can install?

**Comment by vlada-shubina** [comment]
> @vlada-shubina To use `dotnet new` to create a project that targets an older unsupported version is there a template that you can install?

Yes, the web project templates are shipped in per SDK packages.

https://www.nuget.org/packages/Microsoft.DotNet.Web.ProjectTemplates.3.0/ - example package for netcoreapp3.0

It is possible to install it manually. For 2.1 user can also install .NET SDK 2.1 - then the netcoreapp2.1 TFM will be available.

**Comment by tdykstra** [comment]
@vlada-shubina Thanks!  I'm adding this information to the dotnet-new-sdk-templates article.

**Comment by tdykstra** [comment]
@brnhensley Thanks or reporting this -- the explanation will be in a different article -- https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates

**Comment by brnhensley** [comment]
Thanks for looking into this @tdykstra
