### ISSUE TITLE
Object have not been declared

### ISSUE THREAD

**Issue by khumara** [dotnet/docs#24551]
The project does not compile. 

![image](https://user-images.githubusercontent.com/9474900/121109739-fbf94e00-c7c0-11eb-8760-860ef39c08ba.png)

These objects: Cofffee, Egg, Bacon, Toast and Juice have not been declared.
What are the expectation of these classes to have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
There is a note in the article saying:

> The `Coffee`, `Egg`, `Bacon`, `Toast`, and `Juice` classes are empty. They are simply marker classes for the purpose of demonstration, contain no properties, and serve no other purpose.

**Comment by khumara** [comment]
I supposed we should figure it out ourselves to get the code running before making enhancing it with tasking.
