### ISSUE TITLE
Korean translation is incorrect in "Task asynchronous programming model"

### ISSUE THREAD

**Issue by dasg34** [dotnet/docs#24553]
`en-us`: A synchronous method returns when its work is complete (step 5), but an async method returns a task value when its work is suspended (steps 3 and 6).
`ko-kr`: 비동기 메서드는 작업이 완료될 때 반환되지만(5단계) 비동기 메서드는 작업이 일시 중단될 때 반환됩니다.

Since `synchronous` means '동기' and `async` means '비동기' in Korean, `ko-kr` should be

 - ~비~ 동기 메서드는 작업이 완료될 때 반환되지만(5단계) 비동기 메서드는 작업이 일시 중단될 때 반환됩니다.**(3~6단계)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd97c63-2887-1891-fb08-9cd78659c2db
* Version Independent ID: 1ae4494a-ca0b-a1da-cdcf-522ef79e0fc5
* Content: [The Task Asynchronous Programming (TAP) model with async and await (C#)'](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model)
* Content Source: [docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@JasonCard

**Comment by JasonCard** [comment]
Hello @dasg34 

Thank you for your contribution! Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding Microsoft team and will close this one.

Kind regards,
Microsoft DOCS Global Experience Team
