### ISSUE TITLE
Doesnt install latest version like it says it does

### ISSUE THREAD

**Issue by proskilly** [dotnet/docs#24557]
When running dotnet-install.sh it says in the documentation that it "This installs the latest version." but it looks like it has installed 3.1, when version 5 has been out for 6 months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to Raspberry Pi](https://docs.microsoft.com/en-us/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
'Twould appear the script changed to default to latest LTS instead of latest version. Thanks for the heads up!
