### ISSUE TITLE
no se como solucionarlo

### ISSUE THREAD

**Issue by liz730** [dotnet/docs#24560]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c718a6bd-75c6-13e1-36ae-7412668240a2
* Version Independent ID: d6f5fdf0-5b12-ef6d-b126-5ef28fdc8004
* Content: [Compiler Error CS0122](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0122?f1url=%3FappId%3Droslyn%26k%3Dk(CS0122))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0122.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0122.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@liz730 

You should be able to fix this by adding the `public` access modifier to the method you're trying to call. If that method isn't in your project, but is in a 3rd party library, you'll nee to consult their docs to see what API should be called instead.

Let us know if that helps.
