### ISSUE TITLE
Poor formatting and punctuation choices harm readability

### ISSUE THREAD

**Issue by jkendall327** [dotnet/docs#24577]
# Issues
This article suffers from poor readability. I ran the page's content through a [Flesch-Kincaid readability test ](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests) and got a score of 37, which is poor. This indicates sentences and paragraphs that are too long, especially for ESL readers. More specific points:

- Many of the paragraphs are too large. This makes them feel like 'walls of text' that it is easy to get lost in.
- The large number of hyperlinked type-names concentrated in close proximity are hard to parse.
- Some phrases are needlessly convoluted, such as the first two sentences of the second paragraph.
- I feel that the use of semicolons in the final paragraph is inappropriate and should be replaced by bulletpoints.

# Suggestions
I would like to restructure and rephrase the article's content to make it easier to read without affecting any of the information it contains. More specifically:

- Bulletpoints should be used to clearly list different types.
- Paragraphs should be split up for easier reading. In particular, tag sentences (like 'Generic collections are the best solution to strong typing.') would more effectively frame the following content if they were their own paragraph.

# Example rewrite of the first two paragraphs

Collection types represent ways to collect data, such as hash tables, queues, stacks, bags, dictionaries, and lists.

All collections are based on the ICollection interface. IList, IDictionary and their generic counterparts are both derived from the ICollection interface. 

In collections which use IList or ICollection,  every element contains only a value. Examples include:

- Array
- ArrayList
- List<T>
- Queue
- ConcurrentQueue<T>
- Stack, ConcurrentStack<T>
- LinkedList<T> 

For collections which use IDictionary, every element contains both a key and a value. Examples include:

- Hashtable
- SortedList
- Dictionary<TKey,TValue>
- SortedList<TKey,TValue>
- ConcurrentDictionary<TKey,TValue>

The KeyedCollection<TKey,TItem> class is unique because it is a list of values with keys embedded within the values. Therefore, it behaves like a list and like a dictionary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e986db-612f-2608-6949-26cd47881469
* Version Independent ID: 2e68de31-22ca-ac4c-cf85-4d452c9fbde0
* Content: [Commonly Used Collection Types](https://docs.microsoft.com/en-us/dotnet/standard/collections/commonly-used-collection-types#feedback)
* Content Source: [docs/standard/collections/commonly-used-collection-types.md](https://github.com/dotnet/docs/blob/main/docs/standard/collections/commonly-used-collection-types.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @jkendall327
Thank you so much for posting this issue. We really appreciate it. I love the approach you're suggesting and I'd love to review a PR. I've marked this issue as up-for-grabs, please feel free to work on it and reference this issue number in the PR. Thanks again
