### ISSUE TITLE
Fix badly converted links

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2459]
There are some links that were not correctly migrated. You can find them by searching qualifyHint.

Not all of them will appear as an issue in the build report because the first part of the link was correctly migrated, so we just have garbage showing up, such as in:
https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.op_greaterthan?view=netframework-4.7#System_Numerics_BigInteger_op_GreaterThan_System_Numerics_BigInteger_System_Numerics_BigInteger_

![image](https://user-images.githubusercontent.com/12971179/27370611-2d2dc228-5612-11e7-9458-9ba5d877b8f0.png)

**Comment by mairaw** [comment]
@JRAlexander I still see qualifyHint in links in the migrated content:
https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=qualifyHint&type=

So I think this issue should remain open until that is fixed.

**Comment by JRAlexander** [comment]
Yes, I couldn’t find any QualifyHint in my local repo so I thought it was finished. I was going to ask you for a sanity check earlier today. I now see I was in core only. Apologies! Thanks for reopening.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mairaw** [comment]
I think we're close to get this one finished. There are only 3 more files showing up with that qualifyHint string!

**Comment by JRAlexander** [comment]
Yup, working on it now!
