### ISSUE TITLE
Missing Link Information

### ISSUE THREAD

**Issue by green4don** [dotnet/docs#24617]
"For information on how to extract the asymmetric public key from the RSA object in a format that you can easily send to a third party, see Encrypting Data."

I can find no information about doing this on the referenced page. Still going through all the encryption pages, so perhaps it will be somewhere else.

Just FYI. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 478c9f53-b77b-5c74-8fb8-4ae75b236e58
* Version Independent ID: 26216ac9-8479-423a-3ca8-eb1315874d61
* Content: [Decrypting data](https://docs.microsoft.com/en-us/dotnet/standard/security/decrypting-data)
* Content Source: [docs/standard/security/decrypting-data.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/decrypting-data.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @green4don 
Thank you so much for posting this issue. We really appreciate it. I'll add that.
