### ISSUE TITLE
Inaccurate documentation for PackageReference tag

### ISSUE THREAD

**Issue by michaelkruglos** [dotnet/docs#2461]
# Inaccurate documentation for PackageReference tag

# General

[Version](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md#version) element of PackageReference is described as "respects the rules of the [NuGet versioning scheme](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges)", but in fact if you supply Version="1.0" the behavior is as though it's version="[1.0]" for NuGet, that is even if 1.1 is available, `dotnet restore` command will install `1.0`.

# Steps to reproduce
```bash
mkdir test
cd test
dotnet new console
$EDITOR test.csproj
# Add the following section to the file
# <ItemGroup>
#     <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.3" />
# </ItemGroup>

dotnet restore
grep -A3 Jwt obj/project.assets.json
# the output will indicate the version 5.1.3 is chosen even though there's version 5.1.4 of this library
```

**Comment by GuardRex** [comment]
@mairaw Is it ok if I drop this on the updates for https://github.com/dotnet/docs/issues/2139? There will be a delay for it to go live, but I see this as more of an "enhancement" than a "bug," since it's a clarification of which NuGet notation is followed as the default.

**Comment by GuardRex** [comment]
@michaelkruglos Thanks for reporting this. Let me see how/when this should go down, and I'll get right on it.

**Comment by mairaw** [comment]
IMHO these PRs are getting big and harder to review since we're all busy. No rush on getting this done but I prefer easy to review PRs. So it's better if it's not bundled with others.

**Comment by GuardRex** [comment]
@mairaw Sure ... let me know if you want this one stripped off. It was (IIRC) a one-line change to that topic.

**Comment by GuardRex** [comment]
This work has been moved to https://github.com/dotnet/docs/pull/2494.
