### ISSUE TITLE
Object Initializers with collection read-only property initialization

### ISSUE THREAD

**Issue by atifaziz** [dotnet/docs#24612]
The documentation and examples don't mention a useful case of the initialization syntax where an object has a property getter only for a collection. Suppose the following:

```c#
public class CatOwner
{
    public IList<Cat> Cats { get; } = new List<Cat>();
}
```

It's not possible to do the following since the property cannot be _assigned a new list_:

```c#
CatOwner owner = new CatOwner
{
    Cats = new List<Cat>
    {
        new Cat{ Name = "Sylvester", Age=8 },
        new Cat{ Name = "Whiskers", Age=2 },
        new Cat{ Name = "Sasha", Age=14 }
    }
};
```

However, new entries can be added to the property's collection using the initialization syntax by omitting the `new List<Cat>` bit:

```c#
CatOwner owner = new CatOwner
{
    Cats =
    {
        new Cat { Name = "Sylvester", Age = 8 },
        new Cat { Name = "Whiskers", Age = 2 },
        new Cat { Name = "Sasha", Age = 14 }
    }
};
```

This gets translated to:

```c#
CatOwner owner = new CatOwner();
owner.Cats.Add(new Cat { Name = "Sylvester", Age = 8 });
owner.Cats.Add(new Cat{ Name = "Whiskers", Age = 2 });
owner.Cats.Add(new Cat{ Name = "Sasha", Age = 14 });
```

Consider adding a section titled **Object Initializers with read-only collection property initialization** with the above example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efd6a6a-b52a-f6a2-d98b-f245b55115ff
* Version Independent ID: 95025282-20a0-ded8-c6d2-3b8ffff600c4
* Content: [Object and Collection Initializers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @atifaziz 

I like that suggestion, and I've added it to our list, and added the up for grabs label.

Would you like to submit a PR for this?  If so, I'll assign it to you. If not, we'll address it when we next update this article.

**Comment by atifaziz** [comment]
Thanks @BillWagner. You can assign it to me and I'll try and submit a PR.
