### ISSUE TITLE
Incorrect backslash on csc command line options reference list

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2462]
Moved from https://github.com/dotnet/docs.de-de/issues/25

@akoeplinger on 6/6/2017 ...

On https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/compiler-options/listed-alphabetically there are \ added in front of the command line args:

![26859193-5ca3add8-4b36-11e7-9651-392ca0153ae9](https://user-images.githubusercontent.com/1622880/27390230-64094520-5666-11e7-98dd-28e5836c725d.png)

The English version at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically doesn't have those.

**Comment by GuardRex** [comment]
@mairaw It looks like escaping is broken for the localized build. Do you want me to open on SiteHelp? ... or inline code these switches as a quick fix?

**Comment by GuardRex** [comment]
Something funky about their being part of links ...

> |\[/?](../../../csharp/language-reference/compiler-options/help-compiler-option.md)|Displays a usage message to stdout.|

**Comment by GuardRex** [comment]
More examples ...

* https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/compiler-options/listed-by-category
* https://docs.microsoft.com/de-de/visualstudio/profiling/how-to-instrument-a-dynamically-compiled-aspnet-web-application-and-collect-detailed-timing-data-with-the-profiler-by-using-the-command-line
* https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/compiler-options/debug-compiler-option

Opened internally: TFS#: 1023584

**Comment by GuardRex** [comment]
I was just informed by @Banani-Rath that the locale repos have the content that require the change, e.g., https://github.com/dotnet/docs.de-de

**Comment by mairaw** [comment]
Moving this to the backlog while engineering team tests builds that follow CommonMark spec and what that means to us.

**Comment by mairaw** [comment]
Internal bug was marked as resolved. It also seems that the Loc process stopped adding that backslash:
https://github.com/dotnet/docs.de-de/commit/5f080b0893b317dff099caeceb1139044dbd815a#diff-7765c5665346c4f101525e06c7ad5e79

I checked all pages and they all look good.
