### ISSUE TITLE
Regarding the Decimal Format Specifier (D)

### ISSUE THREAD

**Issue by Niranjan16-Ninja** [dotnet/docs#24636]
[Enter feedback here]

In number systems decimal digits represents the the numbers from (0 to 9) and also numbers with fractional digits (12.25). But in this document the Decimal Format Specifier (D) is supported only for `Int`  type values. Either the name needs to be changed or the double value should be supported by this format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#decimal-format-specifier-d)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by ssaran046** [comment]
Decimal number is a number that uses a decimal point followed by digits that show a value smaller than one.

Example: 45.6 (forty-five point six) is a decimal number.

So the name or supported value type should be changed.

**Comment by gewarren** [comment]
I see how this is confusing. I'm not sure how that name was chosen. But you can use the [fixed-point format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#fixed-point-format-specifier-f) for your purposes.

**Comment by adegeo** [comment]
There isn't anything we can do for this documentation issue. The docs are correct in the naming, even if the name is misleading. I doubt this would change as there are decades of books and websites using the same name that would be invalidated. Ouch!

Sorry 😿
