### ISSUE TITLE
System.Uri isn't documented as supported

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#24631]
See https://github.com/dotnet/roslyn-analyzers/issues/5133.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a705da7-7165-2d5f-81d1-fdbef196786c
* Version Independent ID: 2f470a1c-8c81-2d26-3cad-92491229db15
* Content: [Supported collection types in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-supported-collection-types.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-supported-collection-types.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Oh my bad! I understood it in a different way. So I think the request here is to add a new article (or extend the existing one) for all supported BCL types.

**Comment by tdykstra** [comment]
We considered an article like that but decided against it because the rule is simple -- supported if the type can be converted to and from string -- and to try to list all such types and keep the list updated seemed not worthwhile.

**Comment by Youssef1313** [comment]
Thanks!
