### ISSUE TITLE
Delete all WF and WCF samples

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#24648]
Related to #24281.

The download for the WF and WCF samples is no longer available - see https://www.microsoft.com/download/details.aspx?id=21459. (I did find a couple of GitHub repos that have the code for the samples - e.g. https://github.com/SebastiaanLubbers/WF_WCF_Samples.)

The articles for all of the samples exist at /previous-versions for .NET Framework 4 ([WF](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd483375(v=vs.100)) and [WCF](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd483346(v=vs.100)])). Some of these articles (those with <50 page views/month) were deleted from the dotnet/docs repos (see #7837 and #7895) a few years ago. Now it's time to delete and redirect the remaining ones since the download is no longer available.

**Comment by adegeo** [comment]
We should tag the commit prior to deletion, this way there is an easy-to-find record of them if they're needed in the future.

**Comment by gewarren** [comment]
Another option is to archive them anew. It would make the redirects easier too, because they'd keep the same file names.

**Comment by gewarren** [comment]
This has been completed.
