### ISSUE TITLE
Update the code sample for C# hello world, by using top level program and remove unnecessary boilerplate

### ISSUE THREAD

**Issue by fberasategui** [dotnet/docs#24642]
Which will make it much more beginner friendly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET console application using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. The current project template doesn't use top-level statements, but we expect to have one that does in .NET 6.

**Comment by tdykstra** [comment]
The use of top-level statements in the new-project template has turned out to be controversial, with a lot of negative feedback in places like issue https://github.com/dotnet/docs/issues/26313 . We updated these tutorials for .NET 6 to start with the new template but then show how to proceed by using non-top-level-statements code.

**Comment by MyChade** [comment]
While I appreciate the effort to make C# more beginner-friendly, hiding huge chunks of the language will confuse beginners more than showing them a class container. They might wonder, "where does `String[] args` come from? How do I `return` an error code? Why does everything work differently in here than in my other class files?"

The template change makes Program.cs work inconsistently from every other class file, and from standard C# convention. Inconsistency is the best way to confuse beginners. This should be revised.

(P.S. Not sure if this is the official place for comments regarding this change; the official doc page leads to a semi-unrelated GitHub issue for feedback. Apologies if this is in the wrong spot.)
