### ISSUE TITLE
Address broken rendering issues

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#2465]
Check for broken includes similar to https://github.com/dotnet/docs/pull/2464.

![capture](https://user-images.githubusercontent.com/1622880/27394185-e8e10cba-5670-11e7-9640-adba4dd95b76.PNG)

**Comment by svick** [comment]
[There seems to be quite a few of those.](https://www.google.cz/search?q=site:docs.microsoft.com/en-us/dotnet+"[!")

**Comment by GuardRex** [comment]
... and Halloween 🎃 is a little early this year! I see in some of your search results things like ...

* https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/filters-of-routing
* https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/namespacetable

**Comment by GuardRex** [comment]
Let's perhaps leave broken rendering as a general issue here (I'll change the title). I think I can make a pass soon ... it's just that I'm knee-deep in a doc refactor at the moment. @mairaw, do you want to make this `up-for-grabs` or assign elsewhere? I'm free soon (depending on how the conclusion of my doc refactor goes today on https://github.com/dotnet/docs/issues/2255).

**Comment by rpetrusha** [comment]
@GuardRex, are you planning to add additional commits to this PR to reflect other topics with rendering issues? Since I assume that's the case, I've added the WIP tag.
