### ISSUE TITLE
Read from a stream using Utf8JsonReader example is misleading

### ISSUE THREAD

**Issue by Gonkers** [dotnet/docs#24656]
[This example](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter#read-from-a-stream-using-utf8jsonreader) caused me quite quite a bit of confusion and headache.  I ended up filing a [false bug report](https://github.com/dotnet/runtime/issues/54096) because of an assumption I made based on the Utf8JsonReader example.

Would it be possible to update the example to use code similar to this so it's "more correct" and may cause less confusion in the future?
```c#
// Fill the buffer.
// For this snippet, we're assuming the stream is open and has data.
// If it might be closed or empty, check if the return value is 0.
var bytesRead = stream.Read(buffer);
var hasMoreBytesToRead = bytesRead == buffer.Length;
var reader = new Utf8JsonReader(buffer.AsSpan(0, bytesRead), isFinalBlock: !hasMoreBytesToRead, state: default);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a13d38-4904-c068-c9eb-e43176ce5338
* Version Independent ID: c5dfa4d2-c77a-e752-dae7-0bfae5756b76
* Content: [How to use the JSON DOM, Utf8JsonReader, and Utf8JsonWriter in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter)
* Content Source: [docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by layomia** [comment]
`bytesRead == buffer.Length` does not signify unequivocally that there's no more data left in the stream. In the doc example, it would indicate that we might have to grow the buffer (if `Utf8JsonReader.Read()` fails). We should only set `isFinalBlock` to true if the number of read bytes is zero, or if we expect the subsequent read to be zero bytes.

We could instead add a comment right before the initial reader instantiation:

```cs
// We set isFinalBlock to false since we expect more data in a subsequent read from the stream.
var reader = new Utf8JsonReader(buffer.AsSpan(0, bytesRead), isFinalBlock: false, state: default);
```
