### ISSUE TITLE
Are the `four ways a file is marked as generated` mentioned here the canonical list of ways generated files should be identified?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24657]
Because that list omits things like the `[GeneratedCode]` attribute. 

Also I can never seem to find such a canonical list and this has been the closest thing I can remember finding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Judging by the [compiler implementation](https://github.com/dotnet/roslyn/blob/47340e077cf9fbd6c51daaca7e07956393691b30/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs#L48-L115), it seems that these are all the four ways currently.

**Comment by StingyJack** [comment]
@Youssef1313  Dude that's an awesome find! Others and myself have looked for something like that a few times. I wouldn't have thought to check the compiler. Did you know about it already or was it something you found via web search for this topic?

**Comment by Youssef1313** [comment]
@StingyJack I searched through roslyn code.

fwiw, the attribute you referred to is respected by the analyzer driver. I'm not sure if it's worth opening a language proposal to respect it for nullable contexts too.

**Comment by 333fred** [comment]
> /cc @333fred Should I add the `GeneratedCode` attribute to this description?

I don't believe so. The compiler does not recognize it.

**Comment by BillWagner** [comment]
Closing after confirmation that the current article is correct.
