### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by DulcetTone** [dotnet/docs#24658]
The menu path described does not exist in VS Community 2017 on macOS, not even when altering the beginning of it to the Preferences panel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c8357d-11a6-6f12-b044-5ff44df65d10
* Version Independent ID: 0c103fd7-5cc4-2726-40f8-d759419ae635
* Content: [.NET code style rule options - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/code-style-rule-options.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/code-style-rule-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
I think this feature was added in Visual Studio 2019.
