### ISSUE TITLE
Add New Project not available for Blank Solution in VS 2019 latest version

### ISSUE THREAD

**Issue by sunilsreeshaila** [dotnet/docs#24662]
I Couldn't see Add -> New Project option under Blank Solution Project.
I'm using the latest version of Visual Studio 2019 Enterprise Edition -> Version 16.9.7
Please see the below screenshot reference.

![image](https://user-images.githubusercontent.com/16474694/121859284-25602f80-cd15-11eb-9606-a1fa3239d920.png)

Please check and fix the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Create a .NET class library using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
It doesn't look like you're right-clicking on the ClassLibraryProjects solution in Solution Explorer -- your screen should look like this:
![image](https://user-images.githubusercontent.com/1569635/121918144-9f2ef380-ccea-11eb-9126-eecdb2d1fb4c.png)

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
