### ISSUE TITLE
main

### ISSUE THREAD

**Issue by royalroy12** [dotnet/docs#24660]
**Issue description**

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
@royalroy12 

Was this issue accidentally opened in error? If not, can you add details on the issue?
