### ISSUE TITLE
Bug in Utf8JsonReader code example

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#24663]
https://github.com/dotnet/docs/pull/18326#issuecomment-860409226 by @jubba2001

>The sample "samples/snippets/core/system-text-json/csharp/Utf8ReaderPartialRead.cs" does not work correctly.
>The code will return an empty "Summary" value if its length is greater than the size of the buffer, for example:

 >```
>          var jsonString = @"{
>                ""Date"": ""2019-08-01T00:00:00-07:00"",
>                ""Temperature"": 25,
>                ""TemperatureRanges"": {
>                    ""Cold"": { ""High"": 20, ""Low"": -10 },
>                    ""Hot"": { ""High"": 60, ""Low"": 20 }
>                },
>                ""Summary"": ""A_1234567890_B_1234567890_C_1234567890_D_1234567890"",
>            }";
>```
>In this case, the example returning a value should be modified to look like this: 
 
>```
>           while (!reader.Read())
>           {
>                // Not enough of the JSON is in the buffer to complete a read.
>                GetMoreBytesFromStream(stream, ref buffer, ref span, ref reader);
>                //reader.Read();
>            }
>            Console.WriteLine($"Found property value: {reader.GetString()}");
>```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a13d38-4904-c068-c9eb-e43176ce5338
* Version Independent ID: c5dfa4d2-c77a-e752-dae7-0bfae5756b76
* Content: [How to use the JSON DOM, Utf8JsonReader, and Utf8JsonWriter in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter)
* Content Source: [docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@jubba2001 I'm unable to repro the error you're reporting.  When I change the buffer to 10 and the Summary value as you show it, the buffer is increased in size automatically until it's big enough at 80 bytes in size.

**Comment by jubba2001** [comment]
> @jubba2001 I'm unable to repro the error you're reporting. When I change the buffer to 10 and the Summary value as you show it, the buffer is increased in size automatically until it's big enough at 80 bytes in size.

I run the sample. It stops on 40 bytes buffer:


```
String in buffer is: {

String in buffer is:          "
String in buffer is: "Date": "2
String in buffer is: "2019-08-0
Increased buffer size to 20
String in buffer is: "2019-08-01T00:00:00
Increased buffer size to 40
String in buffer is: "2019-08-01T00:00:00-07:00",

String in buffer is: ,
                "Temperature": 25,

String in buffer is: ,
                "TemperatureRanges":
String in buffer is: {
                    "Cold": { "High":
String in buffer is:  20, "Low": -10 },

String in buffer is: ,
                    "Hot": { "High":
String in buffer is: 60, "Low": 20 }
                },

String in buffer is: ,
                "Summary": "A_1234567
Found property name: Summary
String in buffer is: ,
                "Summary": "A_1234567
String in buffer is: "A_1234567890_B_1234567890_C_1234567890_
Found property value:
```


According to the logic of the existing example, the buffer is doubled only **once**, in case of unsuccessful read: `if (!reader.Read()) { GetMoreBytesFromStream(...`

**Mistakenly**, it grew 2 times to 40 bytes when reading the property name, due to the loop `while (reader.TokenType != JsonTokenType.PropertyName || reader.GetString() != "Summary") ...`

In fact, the buffer must grow **every** time a Read fails, until it reaches a sufficient size, or the end of the stream. 

I suggest the following code for this example: 


```
using System;
using System.IO;
using System.Text.Json;

namespace SystemTextJsonSamples
{
    public class Utf8ReaderPartialRead
    {
        public static void Run()
        {
            var jsonString = @"{
                ""Date"": ""2019-08-01T00:00:00-07:00"",
                ""Temperature"": 25,
                ""TemperatureRanges"": {
                    ""Cold"": { ""High"": 20, ""Low"": -10 },
                    ""Hot"": { ""High"": 60, ""Low"": 20 }
                },
                ""Summary"": ""A_1234567890_B_1234567890_C_1234567890_D_1234567890""
            }";

            var bytes = System.Text.Encoding.UTF8.GetBytes(jsonString.Trim());
            var stream = new MemoryStream(bytes);

            var buffer = new byte[10];
            var span = new Span<byte>(buffer);

            // Fill the buffer
            var read = stream.Read(span);

            var reader = new Utf8JsonReader(span, false, state: default);
            Console.WriteLine($"String in buffer is: {System.Text.Encoding.UTF8.GetString(buffer)}");

            // Read stream
            while (TryReadEntireToken(stream, ref buffer, ref span, ref reader))
            {
                // Search for "Summary" property name
                if (reader.TokenType == JsonTokenType.PropertyName && reader.GetString() == "Summary")
                {
                    Console.WriteLine($"Found property name: {reader.GetString()}");

                    // Next token has to be property value
                    if (TryReadEntireToken(stream, ref buffer, ref span, ref reader))
                    {
                        System.Console.WriteLine($"Found property value: {reader.GetString()}");
                        break;
                    }

                }
            }
        }

        private static bool TryReadEntireToken(MemoryStream stream, ref byte[] buffer, ref Span<byte> span, ref Utf8JsonReader reader)
        {
            int read;

            while (!reader.Read())
            // While not enough of the JSON is in the buffer to complete a read.
            {
                if (reader.BytesConsumed < span.Length)
                {
                    ReadOnlySpan<byte> leftover = span.Slice((int)reader.BytesConsumed);

                    if (leftover.Length >= span.Length)
                    {
                        Array.Resize(ref buffer, buffer.Length * 2);
                        span = new Span<byte>(buffer);
                        Console.WriteLine($"Increased buffer size to {buffer.Length}");
                    }

                    leftover.CopyTo(span);

                    read = stream.Read(span.Slice(leftover.Length));
                }
                else
                {
                    read = stream.Read(span);
                }

                if (read == 0)
                    return false; //no more data in stream

                Console.WriteLine($"String in buffer is: {System.Text.Encoding.UTF8.GetString(buffer)}");
                reader = new Utf8JsonReader(span, false, reader.CurrentState);
            }
            return true;
        }
    }
}
```

**Comment by tdykstra** [comment]
>In fact, the buffer must grow every time a Read fails, until it reaches a sufficient size, or the end of the stream.

That is what the code does as it stands. Did you change anything in it other than the value of Summary and the starting buffer size? Or is it possible you are working with an old copy of the code?  When I change only those two things the buffer is increased to 20, 40, and finally 80. It looks like you're using different code, because I see in your output the results of a Console.WriteLine saying "Found property name" but the actual sample on the page at https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter#read-from-a-stream-using-utf8jsonreader doesn't have that.
