### ISSUE TITLE
Template Naming Discrepancies

### ISSUE THREAD

**Issue by thenumberis6** [dotnet/docs#24667]
[Enter feedback here]
There are multiple template choices and the template the tutorial advises does not give a result matching the tutorial.
Using the 'Unit Test Project" Template **does not** create the class file as shown in the tutorial.
Using the "MSTest Test Project" template **does** create the class file as shown in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET class library using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@thenumberis6 Thanks for reporting that! I'm fixing it now.
