### ISSUE TITLE
doc conflates GetType(TypeName), Type.GetType, and Object.GetType

### ISSUE THREAD

**Issue by MappingSteve** [dotnet/docs#24673]
The first part of the doc is correct - it discusses the *compile time* syntax "GetType(typename) ".

However, the doc is wrong, starting with "If you want to get the type object of an object variable, use the Type.GetType method.".

That sentence has two problems:
1. Should say "... use the Object.GetType method." This is not the same as Type.GetType, which has a different purpose.  
2. Despite having the same name, we are no longer talking about the "GetType Operator", which is the topic of this page. This sentence belongs at the very end of the section, maybe as part of "See Also". Must make it clear that we are now talking about something different!

----------
The section after that is also confused.

This part is correct (lead line and first bullet point):

    The GetType operator can be useful in the following circumstances:  

     *  You must access the metadata for a type at run time. ..."

HOWEVER, the second bullet point has NOTHING to do with the "GetType(TypeName)" operator.

    * You want to compare two object references to see if they refer to instances of the same type. ...

That is a use of "Object.GetType method", and belongs on page docs.microsoft.com/en-us/dotnet/api/system.object.gettype

If it is kept here, then again it should be part of "See Also" - to make it clear that we are no longer discussing "GetType operator".

Probably should have See Also link to both Type.GetType Method and Object.GetType Method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccc42f8-1dbf-ac46-950a-faa9bd2c1dd8
* Version Independent ID: 9d6fd9b3-c88a-05cd-443f-c30c33170585
* Content: [GetType Operator - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/gettype-operator)
* Content Source: [docs/visual-basic/language-reference/operators/gettype-operator.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/gettype-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
@MappingSteve 

Thank you for catching these issues! Looks like you are proposing three changes - two to the text and an addition to the See Also. 

Docs are OSS and we encourage contributions. If you'd like to see the fix in 2-3 days with you added as a contributor on the top of the page, click the edit/pencil icon on the page (upper left) to go to GitHub, click the edit icon again, make the changes in the text, and submit a PR. This seems like an easy way to walk through the process, and next time you find something, it will probably be easier to just show us the changes you think are needed. 

The 2-3 days is for us to review the PR and the site to rebuild - the same time it would take us to propagate it. 

I am not sure about the link for See Also,. @BillWagner can you tell us the right way to do the link redirect link?

**Comment by BillWagner** [comment]
@MappingSteve To add a link to an API, use the `<xref:` tag.  The tag for `Object.GetType` is:  `<xref:System.Object.GetType%2A?displayProperty=nameWithType>`.  The tag for `Type.GetType` is: `<xref:System.Type.GetType%2A?displayProperty=nameWithType>`
