### ISSUE TITLE
`dotnet sln add` documented default for --in-root and --solution-folder doesn't match functionality 

### ISSUE THREAD

**Issue by ZeroErrors** [dotnet/docs#24671]
The [current documentation](https://github.com/dotnet/docs/blob/0934b11277cd14a2da01ba7599dde8ad73545914/docs/core/tools/dotnet-sln.md#add) specifies on `--in-root`
> If you omit this option and `-s|--solution-folder`, the result is the same as specifying this option.

and on `-s|--solution-folder <PATH>` 
> If you omit this option and `--in-root`, the result is the same as specifying `--in-root`.

However the functionality currently derives the solution folder using a relative path between the solution file and the project path.
The code for that can be seen here:
https://github.com/dotnet/sdk/blob/b98be69023905d25b350ffddb2245a2b260351bc/src/Cli/dotnet/commands/dotnet-sln/add/Program.cs#L121-L126

For example if you run:
`dotnet new sln`
`dotnet new console --output src/todo-app`

- `dotnet sln add src/todo-app --in-root` will put the project in the root
- `dotnet sln add src/todo-app --solution-folder todo` will create a solution folder "todo"
- `dotnet sln add src/todo-app` will create a solution folder called "src"

Or perhaps this is not the intended functionality and and issue on https://github.com/dotnet/sdk needs to be created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#add)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@ZeroErrors Thanks for reporting this! I'm correcting the documentation now.
