### ISSUE TITLE
Update document with 'record' type

### ISSUE THREAD

**Issue by nick1941** [dotnet/docs#24681]
[Enter feedback here]

The "Types and Variables" section of this document needs to be updated to include the C# 9.0 'record' type.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [A Tour of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @nick1941 

I've added to the project for .NET 6 / C# 10. We'll make sure to get it updated by then.
