### ISSUE TITLE
Now that logger methods in nested classes are supported, SYSLIB1004 can be removed

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/docs#24683]
PR https://github.com/dotnet/runtime/pull/54180 added support log methods in classes that are nested under other class, structs or records.

Now that logger methods in nested classes are supported, `SYSLIB1004` docs page can be removed with it. 
Diagnostic `SYSLIB1004` only gets generated in preview 4 and 5 of .NET 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d616a74-3dd1-6357-dff3-df8a0937f422
* Version Independent ID: 155090c4-e88a-0ae8-fcbb-64bf16419122
* Content: [SYSLIB1004 error - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1004)
* Content Source: [docs/fundamentals/syslib-diagnostics/syslib1004.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/syslib1004.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I think we should keep the page and just note that it's for Preview 4/5 only?

**Comment by maryamariyan** [comment]
> I think we should keep the page and just note that it's for Preview 4/5 only? 

good idea.
