### ISSUE TITLE
The clean architecture solution template contradicts the documentation

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24694]
The core should not depend on the repository/database, but the class in core\service depends on the repo.

Anything cited as an example should at least be consistent with the doc, even if incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
"The core should not depend on the repository [implementation] or database" - correct

"but the class in core\service depends on the repo." - which class? Can you add a link?

"Anything cited as an example should at least be consistent with the doc, even if incorrect." Where is it inconsistent, and what part of the doc are you saying is incorrect, if any?

Thanks!

**Comment by ardalis** [comment]
Following up... if you mean this class:
https://github.com/ardalis/CleanArchitecture/blob/main/src/Clean.Architecture.Core/Services/ToDoItemSearchService.cs

It depends on an `IRepository<T>` interface, which is defined in the Core project. There's nothing wrong with depending on interfaces - that's what you're supposed to do when following SOLID principles and using DI appropriately.

**Comment by StingyJack** [comment]
I do mean that class, it declares an interface but actually depends on a concretion.  There may be others, but that was a big red flag and I stopped there.

Core should have the entity definitions and the majority of the critical business logic. The data "layer" depends on it for mostly the entity definitions. Core depending on the data layer at design or runtime is the wrong dependency direction, even with vanilla DI.

**Comment by ardalis** [comment]
In what way does it care about the concrete implementation of the abstraction? Obviously at runtime interfaces will be replaced with implementations, but you seem to be saying something more than that.

**Comment by StingyJack** [comment]
I'm saying nothing more than that. That class has a runtime dependency on the repository, which should be the wrong direction for a dependency (but I can find nothing regarding design vs runtime dependencies aside from the speculation or opinion of others). 

If that's OK to you, then the [ProjectController](https://github.com/ardalis/CleanArchitecture/blob/main/src/Clean.Architecture.Web/Controllers/ProjectController.cs) then seems out of place or contradictory with how its doing work that would be in the Core and not handling just the Http stuff and interacting with core. 

The project also has some SharedKernel thing which isnt mentioned anywhere in the docs page.  It feels like it has too much of its author's personal flavor to be cited as a clean example.  Is there not a better concrete example MSFT has available?

**Comment by ardalis** [comment]
Well in case you're unaware, the author of the book (which you're reading in the docs repo, but it's actually a standalone book) is also the author of the Clean Architecture template as well as the eShopOnWeb sample. So, there's a fair bit of consistency expected between these things, although the book and eShopOnWeb are "official" Microsoft guidance and the Clean Architecture template is a "community" resource.

I'd love to have a discussion with you some time about your concerns w/regard to runtime dependencies and the Dependency Inversion Principle. I think it would be an interesting conversation. I don't recall anyone raising issues about how the runtime call chain behaves in regard to this principle, only how compile time dependencies are structured. I even have a diagram demonstrating this in the book.

![image](https://user-images.githubusercontent.com/782127/122455923-ee8b5300-cf7a-11eb-86d1-8dab94d29606.png)

As for your concerns regarding the ProjectController, what do you see it doing that could or should be moved into Core? It fetches a project, translates it into an API model, and returns it. If you really wanted, you could put that into a service or MediatR handler, but personally I would keep the API model in the Web project, which means that any service that returns that model would need to live in the Web project. At that point you'd have something like the [CatalogViewModelService you'll find in eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Services/CatalogViewModelService.cs). If you prefer that approach, there's nothing wrong with using it. Or if you'd rather just have your controller use something like MediatR to dispatch commands and handle them elsewhere, [as I describe here](https://ardalis.com/moving-from-controllers-and-actions-to-endpoints-with-mediatr/), that's a common approach as well.

Hopefully it's clear that eShopOnWeb, a reference application, and Clean Architecture, a template, share the same set of design principles. Microsoft has other samples, including [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers), that demonstrate other architectural approaches (and which have [their own eBooks](https://aka.ms/microservicesebook) describing these approaches). There are others as well, including many smaller samples in the docs and on GitHub.

**Comment by StingyJack** [comment]
I'm going to give Uncle Bob's book a re-read over the next few days and re-read this to make sure I'm not way off base. 

> personally I would keep the API model in the Web project, which means that any service that returns that model would need to live in the Web project

I'm not sure I follow the "API Model" meaning, but having the Services in the Web project (WebApi or gRPC) seems correct. It seems more correct than having a separate Services library project and basically an empty Web API project that pretty much only handles the HTTP request/response and calls the services library to do the real work.  Why do you mix the two approaches in the cited example?  Thats what triggered the red flag for me.

Perhaps an example of what I'm seeing as more straight forward or "cleaner" would help to understand.   
 - Service is going to be either a WebApi or gRPC asp.net core project. Its going to have majority of the "business logic/rules" and or orchestration. For WebApi, the controllers do the HTTP stuff, and they hand off to classes in the `\Services` folder for the actual "work". For gRPC there arent any controllers, just the `\Services` folder.
 - Core has interfaces for exposed services, and interfaces for dal/repository classes, and most of the business entity classes (no EF here), and anything else that would need to be shared  (extension methods, etc).
 - Data has the data source specific data access code in it for interacting with the database for get/save operations. 
 - Not depicted is a Service Client project that uses either the proto files or nswag to auto generate clients for the service.
```
|--------------------|
| External Callers   |
|------------|-------|
             |
|--------|---V-------|
|        |           |
|   C  <-- Service   |
|   o    |           |
|   r    |--------|--|
|   e    |        V  |
|      <-- Data      |
|--------|------|----|
                |
|---------------V----|
| Database             |
|--------------------|

External callers can only contact the Service, never directly into Data
Both Service and Data can reference Core.
Core can reference nothing.
Service can reference Data.
Data cannot reference Service
Data only contacts the Db for its data
```
This keeps the dependencies the same at runtime as they are at design time.

**Comment by ardalis** [comment]
Your diagram is essentially the same as the project structure already in use by eShopOnWeb and my Clean Architecture template.

There's a Core project that references nothing (except perhaps a Shared Kernel but we'll leave that out for now).
There's an Infrastructure project (with Data as well as other Infrastructure concerns) that references Core.
There's a UI project (gRPC, Web API, whatever) that reference Core and leverages Infrastructure for implementations (only references to Infra should be from Program.cs when DI is configured).

Maybe the broad term 'service' is part of the problem here? Many apps have "domain services" and "infrastructure services" and "application services" in addition to Web APIs and gRPC "web services". And the thing that designates where such services go (they're just C# POCOs that are injected as needed) is primarily their abstraction level and dependencies.

Domain services live in the domain (Core) and can't have dependencies on infrastructure or UI concerns.
Infrastructure services live in infrastructure and *can* have dependencies on infrastructure types/concerns.
Application services may live in a separate project but often I put them in the UI project (example: https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/Web/Services/CatalogViewModelService.cs). They can reference UI types like ViewModels.

Let me know if that helps clarify my position as it relates to yours - I think we're more or less in agreement. Assuming that's the case, we can probably close this issue. Thanks!

**Comment by erjain** [comment]
Thanks, @ardalis. The issue can be closed now.
