### ISSUE TITLE
Refinements to source generators overview

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#24690]
#24644 created the overview for source generators. There are three unresolved enhancements for that article:

https://github.com/dotnet/docs/pull/24644#discussion_r651914410  - Explain the added NuGet packages, and reference `dotnet add reference`. 

https://github.com/dotnet/docs/pull/24644#discussion_r651268176 - Add source code for the finished project.

https://github.com/dotnet/docs/pull/24644#discussion_r651270348 - Add an explanation regarding the motivation for creating source generators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @BillWagner - I did a lot of work of this content recently, see #27594. I'm not sure if I covered any of the intended work from this issue or not. Happy to help though.
