### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by beolson** [dotnet/docs#24706]
Several links are broken - 

For example, when installing on 20.04, the instructions state:
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

But, it returns a 404.  

Looking around those directories, I am not finding any packages-microsoft-prod.deb file

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Maleven** [comment]
Me too, only the .deb files give 404, rest is fine.

**Comment by adegeo** [comment]
I'm going to transfer this to the .NET repo instead of the docs repo. Yes the docs tell you to do that, because you're supposed to. So I'm unsure why it's acting strangely. Thank you for reporting it.

**Comment by adegeo** [comment]
This is reported in the SDK repo, you can track it there. Hopefully they get it fixed soon!
