### ISSUE TITLE
HTTP 404 Not Found: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

### ISSUE THREAD

**Issue by MovaUA** [dotnet/docs#24711]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-10-)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by MovaUA** [comment]
😊 Thanks a lot for the reply!
✅ I do confirm the issue is resolved.
