### ISSUE TITLE
Deprecating `-p` for `--project` for `dotnet run`

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#24727]
This change is documented in [Spec for resolving '-p' in 'dotnet run' ](https://github.com/dotnet/designs/pull/229/files)

## Deprecate -p

`-p` will no longer be a valid abbreviation for `project`. In .NET 6, users will receive a warning. 

This warning will be from the CLI parser, so will not generally trigger WarningsAsErrors failures. However, if a wrapping MSBuild or CI process checks for the text "Warning" it will appear in that check. 

Also, if `--property`  is an option passed to the application being run, the ` -- ` syntax separator must be used.

### Version introduced

.NET Core 6.0 Preview 6

### Old behavior

* `-p` previously indicated `--project`.
* `--property` was not a valid option on `dotnet run` and was passed through to the underlying application, even if the `--` syntax separator was not used. 

### New behavior

* `-p` will retain this meaning for .NET 6, but will result in a warning that it is deprecated and to use the full `--project`. At some future point, we will remove the use of `-p` to indicate `--project`.
* `--property` is now a valid option on `dotnet run` and this option will not be passed through to the underlying application, unless the `--` syntax separator is used. 

### Reason for change

We are deprecating `-p` because of the close relationship `dotnet run` has with `dotnet build` and `dotnet publish`. This breaking change is the first step in aligning abbreviations for these commands. 

Embracing Xamarin/Maui results in a need to pass MSBuild properties to MSBuild during the build portion of `dotnet run`. We want the option specifying this to be the same for  `dotnet run`, `dotnet build` and `dotnet publish`. 

### Recommended action

If you encounter the new warning, please use `--project`. If you have a project argument that includes an `=` and use the `-p` abbreviation, it will be interpreted as `--property` and passed to MSBuild, so you will have to use `--project` to pass it to your application in all cases. 

If you have an application that has an option called `--property`, you will need to use the syntax separator to pass the the value to your application: 

```C#
dotnet run -- --property myPropertyValue
```

Please review any scripts that use `dotnet run` where you might overlook the warning if `-p` is used.  

If you have any scripts that are using “dotnet run” and process the output you could encounter a break.  `dotnet run` typically doesn’t output anything of its own if there are no errors, so you only get the output of the program that is being run.  If you have a script or other program wrapping “dotnet run” and parsing the output, the warning would be unexpected text and may cause a failure.

### Category

- [ ] ASP.NET Core
- [ ] C#
- [ ] Code analysis
- [ ] Core .NET libraries
- [ ] Cryptography
- [ ] Data
- [ ] Debugger
- [ ] Deployment
- [ ] Globalization
- [ ] Interop
- [ ] JIT
- [ ] LINQ
- [ ] Managed Extensibility Framework (MEF)
- [ ] MSBuild
- [ ] Networking
- [ ] Printing
- [x] SDK
- [ ] Security
- [ ] Serialization
- [ ] Visual Basic
- [ ] Windows Forms
- [ ] Windows Presentation Foundation (WPF)
- [ ] XML, XSLT

### Affected APIs

Not detectable via API analysis

---
#### Issue metadata

* Issue type: breaking-change

**Comment by kyle-rader** [comment]
I respect the desire for aligning the options of build, run, and publish. But as someone who types `dotnet run -p` all the time every day, removing `-p` instead of adding it to the others makes me a little sad.

**Comment by paulomorgado** [comment]
Is it possible to deprecate `-p` in favor of nothing?

**Comment by omarmciver** [comment]
I'm still using `-p` for project in .NET 8. Where is the original report / design spec that made the decision to reserve `-p` for property and relegate `--project` to longform? 🤪

From my personal experience, I use the project flag 10x more times than property when working `dotnet` command line. `property` is normally scripted (Dockerfile etc.) This might not be the majority opinion🤔, but that is what I'm looking to find out. 

For the past 2 years, every time I see `Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project`  I get shivers about how many more keystrokes per year that adds up to on a global scale. (The things you never think you'd be writing!) 😂 

Where do I go for the support to flip this on its head, reserve `-p` for project and let the `--property` suffer the longform.

Thank you.

**Comment by gewarren** [comment]
@omarmciver The spec is [Spec for resolving '-p' in 'dotnet run'](https://github.com/dotnet/designs/pull/229/files), but doesn't seem to exist in main, so I'm not sure what happened. @KathleenDollard?

Maybe you can start a discussion here: https://github.com/dotnet/designs/discussions
