### ISSUE TITLE
Update Azure SDK Identity docs to have consistent auth story across languages

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#24726]
The Java developer docs on Identity can be found at [Azure authentication with Java and Azure Identity](https://docs.microsoft.com/azure/developer/java/sdk/identity). We should have similar coverage (hopefully reusing the same Markdown files) across other languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e60190-3021-9c77-599d-ed7d554c8ebe
* Version Independent ID: e5351dfa-ad22-99c6-d203-774c1f00de81
* Content: [Understanding Authentication in the Azure libraries for .NET](https://docs.microsoft.com/en-us/dotnet/azure/sdk/authentication)
* Content Source: [docs/azure/sdk/authentication.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/authentication.md)
* Product: **dotnet-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Closing as no longer relevant, since @alexwolfmsft made a really great set of auth docs
