### ISSUE TITLE
What is the -Command

### ISSUE THREAD

**Issue by Manikese** [dotnet/docs#24728]
What does the -Command do and why does the first example use it and the second doesn't?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5154fa29-1cf7-a744-83b8-f4798e2b3a0e
* Version Independent ID: c6781eb9-a9f8-7fbb-838d-e9f654a5cfdf
* Content: [Using Windows PowerShell commands in a DockerFile to set up Windows Containers (Docker standard based)](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Manikese, thank you for reaching out.

`-Command` helps to execute the specific command as it gets mentioned as a parameter along with `Powershell`. It's used to explicitly mention that the "string" mentioned after it is a command parameter. You can either pass a single command or a script block as a parameter. For more details, refer [-Command](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-command)
