### ISSUE TITLE
packages-microsoft-prod.deb not found

### ISSUE THREAD

**Issue by ygrenzinger** [dotnet/docs#24720]
Hello,

I am trying to install dotnet on Ubuntu to use it with VS code Ionide plugin.
Sadly it doesn't work with snap.

I am trying to install the package :
wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
**gives**
--2021-06-17 15:53:36--  https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.81.215.193
Connecting to packages.microsoft.com (packages.microsoft.com)|13.81.215.193|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-17 15:53:37 ERROR 404: Not Found.

And

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0
**gives** 
E: Unable to locate package dotnet-sdk-5.0
E: Couldn't find any package by glob 'dotnet-sdk-5.0'
E: Couldn't find any package by regex 'dotnet-sdk-5.0'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by ygrenzinger** [comment]
Thanks a lot !
