### ISSUE TITLE
Does the asp.net core di guarantee that a null will never be injected?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#24742]
I dont see any statement to that effect. Its fine if it doesn't or cant make a guarantee.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd55089-b683-2202-6641-c7b61a132f14
* Version Independent ID: cc5f00d0-fb50-1229-8fa2-e66b1f45b284
* Content: [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
* Content Source: [docs/core/extensions/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @StingyJack - that is a fair question and valid observation. I'm not certain, but I would assume that anything is possible. It's probably not very likely - I'm going to tag a few friends who might be able to help answer this: @maryamariyan @eerhardt do either of you know the answer to this question?

**Comment by StingyJack** [comment]
@IEvangelist -  I think [this](http://stevetalkscode.co.uk/null-injection) would mean there isnt a guarantee, but there are probably legions of developers who assume otherwise and are skipping null checking constructor parameters. Some official blurb regarding this could help those people from having to investigate NullRefEx later in code.

**Comment by eerhardt** [comment]
No, it is not guaranteed that a `null` will never be injected into a DI container.

```C#
using Microsoft.Extensions.DependencyInjection;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            IServiceCollection c = new ServiceCollection();
            c.AddSingleton(typeof(IFoo), sp => (IFoo)null);
            var sp = c.BuildServiceProvider();

            Console.WriteLine(sp.GetService<IFoo>()?.ToString() ?? "<null>");
        }
    }

    interface IFoo { }
    class Foo : IFoo { }
}
```

**Comment by StingyJack** [comment]
@eerhardt - thanks,  Looking at the GetRequiredService(), it may be able to guarantee this, The presence of the ISupportRequiredService interface is kind of confusing. I cant find anything that implements it.
![image](https://user-images.githubusercontent.com/15381181/123115817-6390d980-d40e-11eb-9128-e5f7959a40af.png)

**Comment by IEvangelist** [comment]
This issue was addressed a long time ago, but was never closed. Closing now with https://github.com/dotnet/docs/issues/24742#issuecomment-865132466
