### ISSUE TITLE
Are some clarifications needed?

### ISSUE THREAD

**Issue by alecjames** [dotnet/docs#24746]
"The sample creates different color console entries per log level and event ID using the following configuration type:"

Should this read: The sample creates different color console entries per log level"?

I am unsure of the purpose of EventId.  In the example, a log event is logged when _config.EventId is zero (always in this example), or when _config.EventId matches eventId.Id from the incoming log request, otherwise the log is not processed.  I don't follow this, its like a filter that only logs specific eventId.id and ignores all others.  I think a comment is needed about the purpose of this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @alecjames - that is a good observation. The sample source should be updated to reflect changes to the color when the `EventId` changes.

**Comment by alecjames** [comment]
Hi @IEvangelist ,
Why would you have a logger that logs a single eventId?  Is eventId a category?  I read the docs and I think it identifies a specific log event.  Sorry if I'm missing something here.
