### ISSUE TITLE
How does this page demonstrate Shadows

### ISSUE THREAD

**Issue by axtens** [dotnet/docs#24750]
The Behavior and Example section do not demonstrate Shadows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8a3392-89cf-b8c4-e929-696fc7248270
* Version Independent ID: 59f49bd6-04d5-9da1-705b-8d691e6fe5c8
* Content: [Interface Statement - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/interface-statement)
* Content Source: [docs/visual-basic/language-reference/statements/interface-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/interface-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for noting this @axtens 

This page should link to [the overview of shadowing](https://docs.microsoft.com/dotnet/visual-basic/programming-guide/language-features/declared-elements/shadowing).

I've added this to our backlog, and added the "up for grabs" label for any community members interested in submitting a PR.
