### ISSUE TITLE
Source generators page should document persisting files to disk

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#24752]
I believe the page needs to mention `EmitCompilerGeneratedFiles` and `CompilerGeneratedFilesOutputPath`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@mikadumont  

Do you think this suggestion should be part of this article, or will it be in a different article in the overall plan?
