### ISSUE TITLE
Examples given don't work with .netstandard2.0

### ISSUE THREAD

**Issue by schmik** [dotnet/docs#24765]
As far as I can tell, the given example for ["Parameterless"](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#parameterless) won't work with a class lib targeting _.Net Standard 2.0_ -- which should be a viable target, as [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/) itself targets `netstandard2.0`? `IServiceCollection` has no method `.AddOptions<T>`

```
using Microsoft.Extensions.DependencyInjection;

namespace ExampleLibrary.Extensions.DependencyInjection
{
    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddMyLibraryService(
            this IServiceCollection services)
        {
            services.AddOptions<LibraryOptions>()
                .Configure(options =>
                {
                    // Specify default option values
                });

            // Register lib services here...
            // services.AddScoped<ILibraryService, DefaultLibraryService>();

            return services;
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @schmik - thank you for posting this issue. The `AddOptions` extension method exists with multiple target framework monikers (TFMs):

- `netcoreapp2.1` - .NET Core 2.1
- `netcoreapp3.0` - .NET Core 3.0
- `netcoreapp3.1` - .NET Core 3.1
- `net461` - .NET Framework 4.6.1
- `netstandard2.0` - .NET Standard 2.0
- `netstandard2.1` - .NET Standard 2.1
- `net5.0` - .NET 5.0
- `net6` - Previews 1 - 5

The API reference docs show the platforms where this is applicable (expand **Applies to**):
https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.addoptions

Also, see the NuGet package (version history and dependencies):
https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/

**Comment by schmik** [comment]
Sorry David, I am a little late.

If I visit the reference docs [https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.addoptions?view=dotnet-plat-ext-5.0&viewFallbackFrom=netstandard-2.0](https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.addoptions?view=dotnet-plat-ext-5.0&viewFallbackFrom=netstandard-2.0): there is this note _"The requested page is not available for .NET Standard 2.0. You have been redirected to the newest product version this page is available for."_

Accordingly, my VS refuses to convince the compiler to compile:

![Screenshot 2021-06-28 223836](https://user-images.githubusercontent.com/28360672/123702084-fe504480-d862-11eb-93cc-57d3c23a44b1.png)

I created a minimal csproj: [https://github.com/schmik/OptionsPatternsGuidanceParameterless/tree/master](https://github.com/schmik/OptionsPatternsGuidanceParameterless/tree/master)

**Comment by IEvangelist** [comment]
Hi again @schmik - I see the problem now. You're mixing up the namespace and the package (assembly) references. These names can be confusing and it is something that we should callout better in the docs. Many of the NuGet packages specific to fundamentals / extensions area contribute to the `Microsoft.Extensions.DependencyInjection` namespace.

> This extension method you're looking for is not in the `Microsoft.Extensions.DependencyInjection` package, but rather that namespace. [See this article](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.addoptions?view=dotnet-plat-ext-5.0). Notice the namespace and the assembly, you need to reference the `Microsoft.Extensions.Options` package, as it contributes to the `Microsoft.Extensions.DependencyInjection` namespace.
>
> &mdash; Pull request: https://github.com/schmik/OptionsPatternsGuidanceParameterless/pull/1

**Comment by schmik** [comment]
This is helpful, indeed. Thanks a lot!
