### ISSUE TITLE
.NET Framework TLS documentation does not match reality

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/docs#24771]
According to the [TLS best practices](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/tls.md) documentation:

- For applications that target .NET Framework 4.7 or later, the default will choose the best TLS algorithm.
- For applications that target .NET Framework 3.5 through 4.5.2, that are not WCF applications, one should configure `SchUseStrongCrypto` and `SystemDefaultTlsVersions` in the Windows Registry.

I've just spent a couple days investigating a production issue and on a clean installation of Windows Server 2019 v1809, running .NET Framework 4.7.2, an ASP.NET application out of the box will default to issuing client requests with TLS 1.0.

`SchUseStrongCrypto` seems to be still necessary on .NET Framework 4.7.2 in order for the ASP.NET application to be able to make requests that use TLS 1.2, and I would assume TLS 1.1 too. Once I set that in the registry and rebooted the server, the application started issuing `ClientHello` packets requesting TLS 1.2 rather than with TLS 1.0.

[Edited to add article metadata below]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment]
@karelz Could you take a look at this suggestion?

**Comment by karelz** [comment]
@yaakov-h can you please post a minimal repro? (HelloWorld style)
I didn't do the testing myself when we created the docs, but I am fairly sure that client APIs behave the way as described.
Or is it failing ONLY in ASP.NET app?

**Comment by yaakov-h** [comment]
I tried to knock together a quick repro on my home Win10 PC but it seemed to work as documented for both .NET Framework console app and ASP.NET app.

I'll dig into it again next week on Windows Server.

**Comment by yaakov-h** [comment]
ok, I figured it out.

Although the ASP.NET application is running on .NET Framework 4.7.2 and has a TFM set of 4.7.2, the `web.config` contained this:

```xml
<?xml version="1.0"?>
<configuration>
    <!-- snip -->

    <system.web>
        <compilation debug="true" targetFramework="4.5.1"/>
        <httpRuntime targetFramework="4.5.1" enableVersionHeader="false"/>

        <!-- snip -->
    </system.web>
    <!-- snip -->
</configuration>
```

This is already explicitly called out in the document, I hadn't noticed the one paragraph:

https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/tls.md#audit-your-code-and-make-code-changes
