### ISSUE TITLE
No discussion of JSONPath

### ISSUE THREAD

**Issue by MichaelBrooks-Informatyx** [dotnet/docs#24788]
This page supposedly compares the capabilities of Newtonsoft.Json (by which I assume we mean Newtownsoft's Json.Net product) and System.Text.Json, but it fails to make any mention of whether there is an equivalent of Newtownsoft's JSONPath capability, which is odd given that this is one of Newtonsoft's major features (see https://www.newtonsoft.com/json). 
If your comparison is only looking at the serialisation/deserialisation capabilities (which is only one of Newtonsoft's functional areas) and if this is because that's all that the Microsoft assembly can do at present, please say so up front so that those of us who need more advanced features will know to use Newtownsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
Related: https://github.com/dotnet/runtime/issues/45190.

**Comment by tdykstra** [comment]
@MichaelBrooks-Informatyx Thanks for pointing this out - I'm adding a "not supported" entry for JSON Path in the table of equivalent features. Meanwhile, note that in https://github.com/dotnet/runtime/issues/31068 there's a note about a port of the Newtonsoft.Json implementation to work with JsonDocument. .NET 6 preview implements a GetPath method on JsonNode, but querying ability isn't there yet.
