### ISSUE TITLE
OrderStartedDomainEvent  class missing userId argument

### ISSUE THREAD

**Issue by rdiazconcha** [dotnet/docs#24782]
[Enter feedback here]
In the Implement domain events code, the OrderStartedDomainEvent class constructor should include `string userId` as an argument, and in the block we should set the UserId property: `UserId = userId`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: e41af96d-f015-a8e0-4449-7a508d7bccc8
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @rdiazconcha , thank you for pointing it out. I have submitted a PR with the respective changes. Thank you.
