### ISSUE TITLE
Make it clear when the changes for csproj was introduced

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2479]
Topic: https://docs.microsoft.com/en-us/dotnet/core/tools/cli-msbuild-architecture

LiveFyre comment indicates that the topic doesn't make a good job of letting users know when the change happened and which version of VS/tooling they can get the "new" behavior.

**Comment by GuardRex** [comment]
@mairaw I'm rolling this in with the 2.0 updates. The PR is *imminent* ... final touches going down now. :watch:

**Comment by GuardRex** [comment]
This issue work has been moved to https://github.com/dotnet/docs/pull/2493.
