### ISSUE TITLE
Document testing source generators

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#24796]
Testing is *briefly* documented in the cookbook, but it should be documented in docs.microsoft.com for discoverability (and in a little bit more details than cookbook).

I'm not sure whether this should be part of this article, or if it should be a new article.

Note: if https://github.com/dotnet/roslyn-sdk/issues/873 is likely to be fixed soon, the docs should be using the template for the article.

cc @BillWagner @mikadumont @sharwell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @jmarolf for planning purposes.

**Comment by 333fred** [comment]
I think it should also be mentioned as part of https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview#get-started-with-source-generators that, beyond the simple scenario shown, testing is the recommended way of developing a source generator.
