### ISSUE TITLE
Update Automate model training with the ML.NET CLI

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#24826]
- Mention MBConfig
- Review for all other updated information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e480b5e-1c4e-be32-0389-fbaa3a0c1378
* Version Independent ID: c8a49f16-d0fd-cdcf-1886-73302ea3ee53
* Content: [Automate model training with the ML.NET CLI - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli)
* Content Source: [docs/machine-learning/automate-training-with-cli.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/automate-training-with-cli.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
I think the commands are up to date, can you just confirm these are the only supported scenarios. Also, the "Output assets generated" section might need a bit of an update and also mention mbconfig.

**Comment by luisquintanilla** [comment]
@LittleLittleCloud when training with the CLI, should we expect to see an MBConfig after training?

**Comment by LittleLittleCloud** [comment]
@luisquintanilla 
Yes, it should be in the same folder where project generated
