### ISSUE TITLE
how on earth is this meant to help me fix the issue

### ISSUE THREAD

**Issue by Alpha-404** [dotnet/docs#24865]
[Enter feedback here]

it just shows me how to make the error not fix it
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19167a3c-283f-e0c1-d1cb-3b773954779b
* Version Independent ID: 360140ec-e61d-3117-e7a7-92473887f7b6
* Content: [Compiler Error CS0236](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0236)
* Content Source: [docs/csharp/misc/cs0236.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0236.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
>  If you are trying to initialize a variable outside a method, consider performing the initialization inside the class constructor.

I'm going to open a PR updating the article to make it more clear.

**Comment by Youssef1313** [comment]
@Alpha-404 Is [this update](https://github.com/dotnet/docs/blob/c0ead6e1d672f44c96808d5f98c90a490540aa8a/docs/csharp/misc/cs0236.md) more clear?
