### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mcurko** [dotnet/docs#24860]
I tested all the examples you provided (NET5, newest VS), and didn't get any compilation warnings you described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0471f98c-f5cd-00d2-a705-396682f73bcb
* Version Independent ID: a24b862d-c462-a040-8470-9771c74c4e6f
* Content: [! (null-forgiving) operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving)
* Content Source: [docs/csharp/language-reference/operators/null-forgiving.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/null-forgiving.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@mcurko Can you check you have enabled nullable reference types? You need to do that both in the file containing `Person` class (the code in article already has `#nullable enable`), and also at the top of the test file and the file containing your main method.

Alternatively, you can do that in csproj or Directory.Build.props like the following:

```xml
<PropertyGroup>
  <Nullable>enable</Nullable>
</PropertyGroup>
```

I think the point of confusion here is that the article isn't super clear about that. Please confirm.

**Comment by Youssef1313** [comment]
I also encourage you to read [Tutorial: Express your design intent more clearly with nullable and non-nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types) if you haven't.
