### ISSUE TITLE
Add Undocumented APIs: System.​Reflection.​Metadata Namespace

### ISSUE THREAD

**Issue by tompratt-AQ** [dotnet/docs#2487]
Add missing documentation for the System.​Reflection.​Metadata Namespace

This namespace contains 216 classes.

Information will be pulled from the source code at:
https://github.com/dotnet/corefx/tree/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata

Note:
Missing information is marked by the string: "To be added."

@mairaw

**Comment by mairaw** [comment]
Closed via #2630
