### ISSUE TITLE
Please provide more information on using these tools on no-windows platforms

### ISSUE THREAD

**Issue by gravityFlower** [dotnet/docs#24877]
Please provide more information about using these tools on other platforms. Obviously i can't call ` Visual Studio Developer Command Prompt or Visual Studio Developer PowerShell`on Linux.
 How do i get them on Linux. Apparently i can install it via nuget. But the package (in this case Microsoft.NETCore.ILAsm) provides an .exe in the $Home/.nuget/packages/[...]/native folder. While at the same time there are packages like runtime.linux-x64.Microsoft.NETCore.ILAsm, which tell me not to use them, but apparently contain a real native executable.

- which of these tools are usable on other platforms than Windows?
- how do i install them? Do i use them as dotnet tools, do i add them to a project  (like i did)?
- how do i call them? Should i go to my nuget packages folder an call them from there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ba952e-6354-ec6b-c890-d7e22d75abd8
* Version Independent ID: ac591d0f-d67f-25a5-b100-aa48ec2d5d04
* Content: [Ilasm.exe (IL Assembler)](https://docs.microsoft.com/en-us/dotnet/framework/tools/ilasm-exe-il-assembler)
* Content Source: [docs/framework/tools/ilasm-exe-il-assembler.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/ilasm-exe-il-assembler.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@gravityFlower This article and the ones in the same section of the Table of Contents are all for .NET Framework, which is Windows-only. ".NET Framework" is at the top of the TOC (you have to scroll up the TOC to see it) and near the top of every page in the breadcrumbs -- "... .NET Framework / .NET Framework Tools". For .NET (Coe and 5, 6, and later) see the TOC section under the [Tools and diagnostics in .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/tools-and-productivity) article.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
