### ISSUE TITLE
Records (C# reference)|Nondestructive mutation – `Clone` calls *copy ctor*, not otherwise

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#24880]
From [Records (C# reference)/Nondestructive mutation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#nondestructive-mutation)

> To implement this feature, the compiler synthesizes a clone method and a copy constructor. The constructor takes an instance of the record to be copied and **calls the clone method**.

But in compiled code one can see exactly the opposite.

```csharp
public virtual Rec2 <Clone>$()
{
  return new Rec2(this);
}

protected Rec2(Rec2 original)
{
  Num = original.Num;
  Num2 = original.Num2;
  Num3 = original.Num3;
}
```

```csharp
public record Rec2 ()
{
  public int Num { get; init; }
  public int Num2 { get; init; }
  public int Num3 { get; init; }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#value-equality)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Uzivatel919 

I've added it to the next month's plan.
