### ISSUE TITLE
Records (C# reference)|Inheritance|`with` expressions in derived records – `Clone` does not use *covariant return type*

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#24881]
From [Records (C# reference)/Inheritance/`with` expressions in derived records](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#with-expressions-in-derived-records)

> Because the synthesized clone method uses a covariant return type, the result of a with expression has the same run-time type as the expression's operand.

This seems rendered as a lie.

##### Decompilation
```csharp
private void Test()
{
  DerivedRec dr = (DerivedRec)new DerivedRec().<Clone>$();
}

public override BaseRec <Clone>$()
{
  return new DerivedRec(this);
}
```

##### Definition
```csharp
class CovariantReturnType
{
    record BaseRec () { }
    record DerivedRec : BaseRec { }

    void Test ()
    {       
      var dr = new DerivedRec () with { };
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#value-equality)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This is being worked on currently in Roslyn. See https://github.com/dotnet/roslyn/pull/53404.

**Comment by Uzivatel919** [comment]
> This is being worked on currently in Roslyn. See [dotnet/roslyn#53404](https://github.com/dotnet/roslyn/pull/53404).

Ok, I see. Documentation antedates implementation. Not a big problem.

**Comment by Youssef1313** [comment]
@BillWagner Do you think it's worth specifying the compiler version which have this update when it gets merged?

**Comment by BillWagner** [comment]
@Youssef1313 @Uzivatel919 

As a fix, I think I'd prefer removing that implementation detail from the description of records. The important concept is that `with` expressions don't accidentally slice a record if the source argument has a compile time type that is a base class of the runtime type.
