### ISSUE TITLE
Document Pageable types returned in the Azure SDK for .NET packages

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#24888]
A new doc, with a title to be determined, should be created under the [Azure SDK for .NET](https://docs.microsoft.com/dotnet/azure/sdk/azure-sdk-for-dotnet) ToC node. The doc should:

- Use one of the Azure SDK Key Vault packages
- Replace [this content](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Response.md)
- Cover `IEnumerable<T>` vs. `IAsyncEnumerable<T>` in the context of the Azure SDK's responses
- Demonstrate using the [System.Linq.Async package](https://www.nuget.org/packages/System.Linq.Async) for LINQ operations with `AsyncPageable<T>`
- Not emphasize Reactive Extensions, but rather how to use the `System.Linq.Async` package with the Azure SDK for .NET

Please work with @pakrym for any engineering questions related to this doc.

**Comment by IEvangelist** [comment]
Additional consideration(s):

- Potential parity with the [existing Azure SDK for Java article](https://docs.microsoft.com/azure/developer/java/sdk/pagination) on the same subject
