### ISSUE TITLE
Object oriented programming|Object Initializers do not circumvent explicit constructor call

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#24882]
From [Object oriented programming/Object Initializers](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/#object-initializers)

> You can instantiate and initialize class or struct objects, and collections of objects, without explicitly calling their constructor.

Considering example like

```csharp
 var list = new List<int> { 3 };
```
it is obivous that constructor is explictly called by the `new` keyword. For reference see [new operator (C# reference)/Constructor invocation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#constructor-invocation)

Likely there should be something about ability to set properties without qualifying the access on the corresponding variable/instance of a type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb21e6e-7798-e557-be3f-f27ab9c93e05
* Version Independent ID: a526a9cc-938e-7528-b5b4-4879c5085152
* Content: [Classes, structs, and records](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/)
* Content Source: [docs/csharp/fundamentals/object-oriented/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Uzivatel919 

As you point out, that sentence was meant to explain that you don't need to explicitly add the `()` to the type. It's a misleading explanation that should be clarified.

I've added it to our backlog, and added the "up for grabs" label.

**Comment by Uzivatel919** [comment]
@BillWagner 

>You can instantiate and initialize class or struct objects, and collections of objects, without explicitly calling their constructor with an ending `()` after the type.

In fact `()` ending is called argument list_. Nonetheless this syntactic elision (as I believe) is not true benefit of object initializers and in fact is there just to allow the object initialization syntax to be more readable.

Imagine some class like
```csharp
public class SomeClass
{
  public SomeClass ( int id ) => Id = id;
  public int Id { get; }
  public string ArbitraryData { get; set; }  
}
```

It cannot be instantiated without constructor call since it has no parameter-less one.

```csharp
new SomeClass(default) // <--- It is error to omit explicit argument specification.
{ 
  ArbitraryData = default
}
```

Takin this sample further we can model in class like 

```csharp
public class SomeClass
{
  public SomeClass () => Id = 9966; // <-- Note the explicit value set.
  public int Id { get; }
  public string ArbitraryData { get; set; }
}
```

`new SomeClass { ArbitraryData = "Test" }.Id  // Output: 9966`

From this sample it is obvious that parameter-less constructor is called by the virtue behind the `new` keyword logic. Definitely does not relate to omitting empty _argument list_.

For exhausting reference see C# 5.0 language specification, chapter 7.6.10.2 Object initializers.

Object initializers can be employed in cases when model design is turned in a way to avoid setting default values in constructor when only some values are set up in some execution path while another ones are set in another path upon object creation.

Of course some (people) can prefer to instantiate object through initializers because it is their personal preference over constructors.

The same _babble_ can be found at [Docs/.NET/C# guide/Programming guide/Classes and structs/Object and Collection Initializers (C# Programming Guide)/Object initializers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers)

> Object initializers let you assign values to any accessible fields or properties of an object at creation time without having to invoke a constructor followed by lines of assignment statements. 

Appropriate is something like:

1. Docs/.NET/C# guide/Fundamentals/Object oriented programming/Object Initializers](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/#object-initializers) is appropriate

_Object initializers let you assign values to any accessible fields or properties of an object upon creation time using member initializer syntax_ Empty constructor argument list can be omitted._

2. [Docs/.NET/C# guide/Programming guide/Classes and structs/Object and Collection Initializers (C# Programming Guide)/Object initializers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers)

_Object initializers let you assign values to any accessible fields or properties of an object at creation time using member initializer syntax. Empty constructor argument list can be omitted._

**Comment by Uzivatel919** [comment]
To obtain even more of available sureness let inspect CIL.

```csharp
static class ObjectInitializerConstructorCallTests
{
  static void Test1 () { new WithEmptyCtor { }; }
  static void Test2 () { new WithoutEmptyCtor { }; }
  class WithEmptyCtor { public WithEmptyCtor () { } }
  class WithoutEmptyCtor { } 
}
```
```CIL
.method private hidebysig static 
void Test1 () cil managed 
{
	.maxstack 8
	IL_0000: newobj instance void ObjectInitializerConstructorCallTests/WithEmptyCtor::.ctor()
	IL_0005: pop
	IL_0006: ret
}

.method private hidebysig static 
void Test2 () cil managed 
{		
	.maxstack 8		
	IL_0000: newobj instance void ObjectInitializerConstructorCallTests/WithoutEmptyCtor::.ctor()
	IL_0005: pop		
	IL_0006: ret
}
```

One can see constructor on both operation sequences. See also [OpCodes.Newobj Field](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.newobj?view=net-5.0).
