### ISSUE TITLE
unexpected japanese translation

### ISSUE THREAD

**Issue by whistyun** [dotnet/docs#24939]
`en-US`: Lu
`ja-JP`: ルー語

"Lu" is a category identifier. I think it shouldn't be translated.

![image](https://user-images.githubusercontent.com/13712028/124046593-43d06580-da4d-11eb-81c3-c14540afe35a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd8ae60-9b02-3e9e-2318-982f563710c2
* Version Independent ID: d167e261-eb1b-967b-5a6f-cbc2207cd32d
* Content: [.NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expressions)
* Content Source: [docs/standard/base-types/regular-expressions.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expressions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

**Comment by whistyun** [comment]
@adegeo 
I 'm sorry. I mistake the tracking.
The correct URL and md file are as follows.

* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/character-classes-in-regular-expressions.md)

Should I cancel this issue and remake it?
