### ISSUE TITLE
PowerShell script to determine version

### ISSUE THREAD

**Issue by aut0pil0t** [dotnet/docs#24940]
Please provide a small PowerShell script to determine the .Net version on a Windows OS quickly. This is especially helpful when we need to check the version for Exchange Server installations and upgrades.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
@aut0pil0t Hi. There is a small powershell oneliner on the article at the [Use PowerShell to check for a minimum version](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#use-powershell-to-check-for-a-minimum-version) heading. Hopefully this helps. I'll close this issue.
