### ISSUE TITLE
I tried altering the language version but it is not working

### ISSUE THREAD

**Issue by InesBorgesCore** [dotnet/docs#24952]
I tried to alter the language version in the GUI in build > advanced > language version but the options appear disabled.
It gives me the same error as this [post](https://stackoverflow.com/questions/31868803/error-invalid-option-6-for-langversion-must-be-iso-1-iso-2-3-4-5-or-defa).
So I followed the docs and created a Directory.Build.props file and pasted this inside:

```
<Project>
 <PropertyGroup>
   <LangVersion>5</LangVersion>
 </PropertyGroup>
</Project>
```

It is still not working. Does anyone has a solution to this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#configure-multiple-projects)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reaching out @InesBorgesCore 

I'd need to see an example project to understand why this isn't working for you.  I just checked the option values, and I can set mine to C# 5 using that key.
