### ISSUE TITLE
Nested Types section is too opinionated and does reflect the full spectrum nested type usage

### ISSUE THREAD

**Issue by gpuchtel** [dotnet/docs#2497]
I'm opening an issue to discuss the overall tone and validity of the 'Nested Types' section. I've copied the section in its entirety to depict **_in-line_** comments and an example that further illustrates points of contention.

------------------------------------------------------------------

A nested type is a type defined within the scope of another type, which is called the enclosing type. A nested type has access to all members of its enclosing type. For example, it has access to private fields defined in the enclosing type and to protected fields defined in all ascendants of the enclosing type.

In general, nested types should be used sparingly. **_The term sparingly and this statement is very opinionated._** There are several reasons for this. Some developers are not fully familiar with the concept. 
These developers might, for example, have problems with the syntax of declaring variables of nested types. **_A (ensuing) developer’s familiarity with a concept or its syntax is not a reason to avoid a concept._** 

Nested types are also very tightly coupled with their enclosing types, and as such are not suited to be general-purpose types. **_Tight coupling is the primary reason for nested types; tight coupling by itself does not make a type ill-suited for general purpose. More importantly, being general-purpose is not necessarily compulsory when defining a type._**

Nested types are best suited for modeling implementation details of their enclosing types. The end user should rarely have to declare variables of a nested type and almost never should have to explicitly instantiate nested types. **_Again, this entire paragraph neglects the factory pattern – see ‘Account’ class in example._**

For example, the enumerator of a collection can be a nested type of that collection. Enumerators are usually instantiated by their enclosing type, and because many languages support the foreach statement, enumerator variables rarely have to be declared by the end user.

DO use nested types when the relationship between the nested type and its outer type is such that member accessibility semantics are desirable.

X DO NOT use public nested types as a logical grouping construct; use namespaces for this. **_Can you give an example of a ‘logical grouping construct’?_**

X AVOID publicly exposed nested types. The only exception to this is if variables of the nested type need to be declared only in rare scenarios such as subclassing or other advanced customization scenarios. Implementing the factory pattern is another exception.

X DO NOT use nested types if the type is likely to be referenced outside of the containing type. For example, an enum passed to a method defined on a class should not be defined as a nested type in the class. **_Less true if using factory pattern._**

X DO NOT use nested types if they need to be instantiated by client code. If a type has a public constructor, it should probably not be nested. This is debatable. If a type can be instantiated, that seems to indicate the type has a place in the framework on its own (you can create it, work with it, and destroy it without ever using the outer type), and thus should not be nested. Inner types should not be widely reused outside of the outer type without any relationship whatsoever to the outer type. **_Less true if using factory pattern._**

X DO NOT define a nested type as a member of an interface. Many languages do not support such a construct. **_Why is (other) language support relevant?_**

-----------------------------------------

In the example (below), nested types, when used in an factory class do not exhibit the concerns as outlined in this section. The syntax to declare variables of nested types is not complex:

```
        var savingsAccount = Bank.MakeSavingsAccount(100.0m);
        var interest = savingsAccount.CalculateInterest();
```

Coupling (in a rare case), is good in this context – it tightly associates the ‘Account’ with a ‘Bank’. As such, it does not conflict any other class named ‘Account’ because of the (outer) class ‘Bank’ acts like an adjective – it restricts the meaning of a noun (‘Account’). 

A user _could_ instantiate and an instance of ‘Account’ independently of the ‘Bank’ factory methods, although I too do not advocate this practice. Still, the example was written to exhibit this possibility; however, a better solution (from that shown below) would be to expose an ‘IAccount’ interface as follows:

```
        public interface IAccount
        {
            string Number;
            decimal CalculateInterest();
        }

        private abstract class Account : IAccount
        {
            public string Number => Guid.NewGuid().ToString();
            public abstract decimal CalculateInterest();

            protected decimal Balance { get; set; }
        }
```

In summary, I feel the tone of this section is very opinionated and it does not reflect the full spectrum in which nested types are used – the **Do**’s are not the primary reason to use nested types, and the **Do not**’s are not reflective of the factory pattern. 

Example:
------------------------------

```
using System;

namespace NestedTypesAndTheFactoryPattern
{
    public static class Bank
    {
        private const decimal SavingsInterest = 0.015m;
        private const decimal CheckingInterestRate = 0.005m;

        public abstract class Account
        {
            public string Number => Guid.NewGuid().ToString();
            public abstract decimal CalculateInterest();

            protected decimal Balance { get; set; }
        }

        private class SavingsAccount : Account
        {
            public SavingsAccount(decimal deposit)
            {
                Balance = deposit;
            }

            public override decimal CalculateInterest()
            {
                return Balance * SavingsInterest;
            }
        }

        private class CheckingAccount : Account
        {
            public CheckingAccount(decimal deposit)
            {
                Balance = deposit;
            }

            public override decimal CalculateInterest()
            {
                return Balance * CheckingInterestRate;
            }
        }
        
        public static Account MakeSavingsAccount(decimal deposit)
        {
            return new SavingsAccount(deposit);
        }

        public static Account MakeCheckingAccount(decimal deposit)
        {
            return new CheckingAccount(deposit);
        }
    }
}

```

**Comment by svick** [comment]
Just to make sure, are you aware that [the article you're talking about](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) is part of the Framework Design Guidelines and as such only applies to designing libraries and is intentionally opinionated, to make sure .Net libraries are consistent?

---

Responding to some of what you wrote:

> A (ensuing) developer’s familiarity with a concept or its syntax is not a reason to avoid a concept.

It is, if you're writing a library and want for that library to be widely used (which is what FDG are about).

> Can you give an example of a ‘logical grouping construct’?

In your `Bank` example, if all the subclasses of `Account` were public, then I think it would be an example of a "logical grouping construct".

> Why is (other) language support relevant?

If you're designing a library, it should ideally be usable from all .Net languages.

> The syntax to declare variables of nested types is not complex

It is, as soon as you stop using `var`, you have to write `Bank.Account`, `Account` is not enough.

> Coupling (in a rare case), is good in this context

[The FDG are meant to be violated in rare cases](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/): "There might be situations where good library design requires that you violate these design guidelines. Such cases should be rare, and it is important that you have a clear and compelling reason for your decision."

> As such, it does not conflict any other class named ‘Account’ because of the (outer) class ‘Bank’ acts like an adjective – it restricts the meaning of a noun (‘Account’).

That's what namespaces are for.

---

In general, I'm not convinced that your example is good design (I agree with FDG that `Account` should not be a nested type), so I don't see a reason to change the article.

**Comment by rpetrusha** [comment]
Also at issue here is that the design guidelines are [copyrighted material](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/) used with permission of Addison-Wesley.  Given that, @gpuchtel, if you'd like to express your disagreement with the design guidelines for nested types, the best way is to leave a comment in the [Nested Types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) topic on docs.microsoft.com.

**Comment by BillWagner** [comment]
@gpuchtel I'm going to close this, because of the copyright issues.

If you want to suggest alternative guidance, let's consider where those might go, and how to approach the topic.

**Comment by gpuchtel** [comment]
Hi Bill, thank you for taking your time to respond. 

 

I (now) understand the copyright issue and will direct my comments appropriately.
