### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by trs7v3** [dotnet/docs#24979]
In the introductory section, a typo occurs when referring to "Modern" NoSQL databases, written as "Moden"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e80a45b-7084-c3c3-149a-d891dc8de9be
* Version Independent ID: 983d417d-b9d9-7b86-5e46-cc40cc3127c7
* Content: [Relational vs. NoSQL data](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/relational-vs-nosql-data#feedback)
* Content Source: [docs/architecture/cloud-native/relational-vs-nosql-data.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/relational-vs-nosql-data.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by BillWagner** [comment]
Fixed in #24996
