### ISSUE TITLE
Declaring Global Objects instructions are incorrect. 

### ISSUE THREAD

**Issue by THERockyH** [dotnet/docs#24983]
There is a mistake in the instructions: 
**Declaring Global Objects**
_Add the following code to the Form's constructor._ 

You can't add that code to the constructor or none of the other methods will be able to see the declared variables. It has to be done as part of the Form1 declaration. So maybe... before the Form's constructor if that's what you wanted to say. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Creating a Cryptographic Application](https://docs.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @THERockyH
Thank you so much for posting this issue. We really appreciate it. I'm going to mark this as `up-for-grabs`, please feel free to update the article and reference this issue number -- and we'll happily review it.
