### ISSUE TITLE
Unconstrained type parameter annotations – badly defined substitution for `value type`

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#24981]
From [Unconstrained type parameter annotations/? annotation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/unconstrained-type-parameter-annotations#-annotation)

> If a type parameter T is substituted with a reference type, then T? represents a nullable instance of that reference type.

>If T is substituted with a value type, then T? represents an instance of T.

The latter is likely bad. I guess it should be “_If T is substituted with a value type, then T? represents **`Nullable<T>`**._”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b2a7f2-acb9-0efd-c72a-0ecb73881600
* Version Independent ID: 5ce2225a-3c71-4bab-f462-3301e9250156
* Content: [Unconstrained type parameter annotations - C# 9.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/unconstrained-type-parameter-annotations#default-constraint)
* Content Source: [proposals/csharp-9.0/unconstrained-type-parameter-annotations.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/unconstrained-type-parameter-annotations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The spec is indeed correct. If you run the following code:

```csharp
#nullable enable

using System;

Console.WriteLine(new C<int>().GetT().GetType().Name);

public class C<T>
{
    public T? GetT() => default;
}
```

It prints `Int32`. In the above example, `T` is substituted with a value type (`int`), and `GetT()` returns `T?`, which was indeed an `int`, not a `Nullable<int>`.

**Comment by Uzivatel919** [comment]
I see. 👍🏻
