### ISSUE TITLE
DateTime.Now in your first example

### ISSUE THREAD

**Issue by Robertofon** [dotnet/docs#24988]
Wouldn't you want to use DateTime.UtcNow instead of DateTime.Now in your first example. Just to steer people in the right thinking direction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346bbcf3-9f8e-b253-09fe-906195392783
* Version Independent ID: 0e787ac2-1108-1d94-d62f-ccffa93e06c3
* Content: [Logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line)
* Content Source: [docs/core/extensions/logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Robertofon 
Thank you so much for posting this issue. We really appreciate it.

We're not using `DateTime`, it's `DateTimeOffset`. This example is part of the .NET template, in other words the templates use `DateTimeOffset.Now`. Do you think we should try to change that?

**Comment by Naidile-P-N** [comment]
I think it's a better approach to use UTC (considering we would have applications hosted in different regions and in certain contexts, diagnostics would be easier).
Submitting a PR

**Comment by steveberdy** [comment]
Shouldn't this have been closed by #25002?

**Comment by Robertofon** [comment]
Finally: Well DateTimeOffset reeduces necessity to change it. In my life, I usually right away go for DateTime.UtcNow because I only ever convert it for display. Said that I have no need for DateTimeOffset. Thanks for changing
