### ISSUE TITLE
Docker image would not push to ACR with command provided

### ISSUE THREAD

**Issue by Swimburger** [dotnet/docs#24987]
The documentation suggests using the following command to build the docker image and push it to ACR:
```bash
az acr build -r <registry name> .
```
As you can see in the screenshot, the result is that pushing the image to ACR is skipped.
![image](https://user-images.githubusercontent.com/3382717/124424257-bdf63800-dd34-11eb-8ad5-7a052cc8bf15.png)

The image has to be pushed to ACR to complete the subsequent steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01da871e-271f-a56e-c0c8-69ae4e19ef29
* Version Independent ID: 582f6863-9999-6962-af30-03e497f485f8
* Content: [Deploy a Worker Service to Azure](https://docs.microsoft.com/en-us/dotnet/core/extensions/cloud-service?WT.mc_id=twitter-0000-docsmsft)
* Content Source: [docs/core/extensions/cloud-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/cloud-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @Swimburger - thank you so much for this, great catch. I'll update the article, unless you'd like to? Just let me know.

**Comment by Swimburger** [comment]
I would've like to, but you beat me to it 😅
Thank you for the quick resolution!

**Comment by IEvangelist** [comment]
LOL - no worries. Feel free to submit a PR directly next time with an explanation of the issue -- thanks again.
