### ISSUE TITLE
Feedback: remove static option naming

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/docs#24991]
The code in https://docs.microsoft.com/en-us/dotnet/core/extensions/options#options-validation shows a static naming of the options.
```csharp
public const string Settings = nameof(Settings);
```
This tempts configuration naming to be used hard in libraries, which could cause naming conflicts that can then again only be resolved with subsections.

My suggestion would be to remove the static name completely from the code and set the name from the configuration so that there can be no misunderstanding either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options#options-validation)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @BenjaminAbt - thank you for posting this concern. I see what you're saying, and I agree that it can lead to misuse and misunderstanding. I'll work to update these to help alleviate this concern. Thank you

**Comment by BenjaminAbt** [comment]
```cs
services.AddOptions<SettingsOptions>()
    .Bind(Configuration.GetSection(nameof(SettingsOptions)))
    .ValidateDataAnnotations();
```
would be a simple fix to avoid misusage.
Just get in touch if you want feedback or a suggestion, feel free to do so directly 👍

**Comment by IEvangelist** [comment]
That wouldn't work, `nameof(SettingsOptions)` would bind to a section "SettingsOptions" which doesn't exist. In this context, the named section is "Settings". But I do understand the concern and will address it. Thanks

**Comment by BenjaminAbt** [comment]
Yes, you are right. But I think you know what I was getting at :-)
