### ISSUE TITLE
Discontinued Tech

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docs#250]
We should consider documenting in more detail which technologies we don't plan on bringing to .NET Core and why. I've started a minimal version here:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#unsupported-technologies

**Comment by blackdwarf** [comment]
@terrajobst we definitely should. I'm asigning this to you since you have most context on these things.

**Comment by BillWagner** [comment]
Does that mean @terrajobst is the best person to ask if I've got questions on classes that aren't implement yet? (meaning not yet vs. not planned)

**Comment by blackdwarf** [comment]
@BillWagner yeah!

**Comment by terrajobst** [comment]
Yes, that's part of my job :smile:

@BillWagner, you can always just file an issue in CoreFX asking things to be ported.

**Comment by BillWagner** [comment]
@terrajobst do you want me to pick up this issue? I read through the content you referenced above, and with a few conversations I flush it out.

**Comment by blackdwarf** [comment]
@BillWagner @terrajobst I'm pretty sure this issue should be closed now that the binary and source compat have been communicated as future goals of .NET Core. Thoughts?

**Comment by BillWagner** [comment]
@blackdwarf @terrajobst Well, I'm still a bit confused on the roadmap, and especially how we get from where we are to where we want to end up. It also seems like many of our customers are similarly unsure what everything means.

**Comment by mairaw** [comment]
@terrajobst can you update that topic with the new plan for the API convergence? Then we can create the topic after that.

**Comment by mairaw** [comment]
@terrajobst can we work on this already?

**Comment by mairaw** [comment]
This is already part of the topic: https://docs.microsoft.com/en-us/dotnet/core/porting/libraries#net-framework-technologies-unavailable-on-net-core
