### ISSUE TITLE
Update the "General Options" section based on new compiler feature

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#25019]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#general-options contains the following as the third bullet item:

> Conflicting entries in two global AnalyzerConfig files: A compiler warning is reported and both entries are ignored.

With https://github.com/dotnet/roslyn/issues/48634, compiler now allows the global config files to specify `global_level = <%integral_value%>` for conflict resolution. Entries coming from two different global config files with same key but different values will be resolved without compiler warnings if the global configs have differing `global_level` values, the file with the higher value will get preference. Also note that `global_level` has different defaults based on the naming, see https://github.com/dotnet/roslyn/issues/48634 for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddb7b648-6f01-eaeb-1292-4baee5ae0666
* Version Independent ID: cb44b30a-3fcc-3384-3fcd-1ac2675bf470
* Content: [Configuration files for code analysis rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files)
* Content Source: [docs/fundamentals/code-analysis/configuration-files.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/configuration-files.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
@paulomorgado

**Comment by gewarren** [comment]
This was fixed by https://github.com/dotnet/docs/pull/25034.
