### ISSUE TITLE
Missing:  using Microsoft.Win32;

### ISSUE THREAD

**Issue by GarryLowther** [dotnet/docs#25017]
You are missing this directive at the top of your C# code samples:

using Microsoft.Win32;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by steveberdy** [comment]
The C# code in the article consists of snippets, not full C# scripts. In a full script, `using Microsoft.Win32;` would be included at the top, but since this is a snippet, the step that says "use the `RegistryKey.OpenBaseKey` and `RegistryKey.OpenSubKey` methods..." should be enough to indicate that the using directive is needed, as they are linked to the documentation for the `Microsoft.Win32` namespace.

**Comment by TriSysBusinessSoftware** [comment]
> use the RegistryKey.OpenBaseKey and RegistryKey.OpenSubKey methods..." should be enough to indicate that the using directive is needed, as they are linked to the documentation for the Microsoft.Win32 namespace.

We it wasn't for me, as I had to do an internet search to identify which namespace the RegistryKey belonged to. Time that I and other readers could save.

My suggestion is to help Microsoft to help us, your customers, by not assuming that we are all .NET experts.

**Comment by steveberdy** [comment]
That makes sense. I'll make that change.

**Comment by steveberdy** [comment]
@TriSysBusinessSoftware thank you for bringing up this issue.
