### ISSUE TITLE
convet string in to table

### ISSUE THREAD

**Issue by IBB185** [dotnet/docs#25021]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c946d7-649b-44e4-49a9-543565904d18
* Version Independent ID: df4263c1-477a-3c32-9abe-3fcb850e6c1b
* Content: [Compiler Error CS1061](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1061.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@IBB185 👋 Hi. I'm afraid this issue doesn't contain enough information for us to help. Can you add more details?
