### ISSUE TITLE
add some notes for New modifier (regarding case - the members in Base class have access level modifier private)

### ISSUE THREAD

**Issue by DSivtsov** [dotnet/docs#25035]
I propose to add some notes regarding case when in Base class the member have access level modifier - private. In this case the new keywords in Derived class doesn't needed because private automatically is hidden (versus cases when the members in Base class have access level - public or protected)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f703413-8141-ed2a-74b3-6eb59b1e3588
* Version Independent ID: 5ae737e7-6628-b7de-4293-e778db0fecbf
* Content: [new modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier?source=docs)
* Content Source: [docs/csharp/language-reference/keywords/new-modifier.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/new-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@DSivtsov 

That's a good suggestion. I've added it to our backlog, and added the "up for grabs" label if anyone wants to submit a pull request to add that note.
