### ISSUE TITLE
third bullet point seems incorrect :"you need to represent them with > or <."

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [dotnet/docs#25053]
The third bullet point seems incorrect :"you need to represent them with `> or <`."
I do use `< `and` >` characters, and they are reported as incorrect. 
Should they be encoded instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077ab322-a36b-082a-a203-bd6a4213b56c
* Version Independent ID: b0bce499-5b03-56ab-a636-8e09323373be
* Content: [Compiler Warning (level 1) CS1570](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1570)
* Content Source: [docs/csharp/misc/cs1570.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1570.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@michael-freidgeim-webjet Thanks for reporting this. Indeed this bullet point is incorrect, the intention was to use `&lt;` and `&gt;`, but markdown converts them to `<` and `>`. I opened https://github.com/dotnet/docs/pull/25056 to fix that.
