### ISSUE TITLE
Attributes for null-state static analysis | The sample

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25069]
From [Attributes for null-state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

```csharp
bool TryGetMessage(string key, out string message)
{
    message = "";
    return true;
}
```
> If the TryGetMessage method returns true, the value of message isn't null. If the return value is false, the value of message (and its null state) is null.

1. Sample does not contain any execution branch that demonstrates `false`/`null` result.
2. It is not truth at all.

Let model the sample in here.

```csharp
#nullable enable
static bool TryGetMessage ( string key, out string message )
{
  if ( key == string.Empty )
  {
    message = "";
    return true;
  }

  message = null; // Warning	CS8625	Cannot convert null literal to non-nullable reference type.
  return false;
}
#nullable disable
``` 
I did not find relevant specification or proposal but it seems natural that  `nullable annotation` of `out` parameter type denotes contract. Thus `null` cannot be assigned to `message`.

---

>(and its null state) is null.

The _null state_ has 2 options: `not null` and `maybe null`. `null` state does not exist.

---

>The rule for `key` can be expressed by the variable type: `key` should be a non-nullable reference type. The `message` parameter is more complex. It allows `null` as the argument, but guarantees, on success, that `out` argument isn't null. For these scenarios, you need a richer vocabulary to describe the expectations.

Missing `?` nullable annotation on `out string message` does not denote not `null` result on success. It denotes not `null` result no matter the return value if it even exists.

```csharp
#nullable enable
static bool IsDefault<T> ( T value , out string message )
where T : class
{
  if ( value is default(T) )
  {
    message = "Yes, sure!";
    return true;
  }

  message = "Sorry, no, it isn’t!";
  return false;
}
#nullable disable
```
---

> It allows `null` as the argument, but guarantees, on success, that `out` argument isn't null. 

Argument cannot be `null`. It is variable that is passed as `out` argument/parameter what has `null` value. One cannot simply code

```csharp
IsDefault (new object(), out string null);
// Error	CS1003	Syntax error, ',' expected
// Error	CS1525	Invalid expression term 'string'
```

It should be also clear what is **difference between** `argument` and `parameter`. Former resides at call site, latter in method signature.

---

>Once your code is _nullable aware_, those rules change. Reference types should never be the null value, and nullable reference types must be checked against null before being dereferenced.

It should be clear what is “_nullable aware_”? I guess it is `#nullable enable warnings`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks again @Uzivatel919 

There's a few things to consider here.

For the first set of comments, I should make the following changes:

The example should show something like this:

```csharp
string message;
bool success = TryGetMessage("token", out message); // Note that message is uninitialized here. It has the default value of `null`.
if (success)
{
    // The variable `message` is definitely assigned (the rules for an `out` parameter)
    // The variable `message` is *not-null*. (Rules for `NotNullWhen`)
} else
{
    // The variable `message` is definitely assigned (the rules for an `out` parameter)
    // The variable `message` is *maybe-null*. (Rules for `NotNullWhen`)
}
```

The second comment (re: message is "not null" because it lacks the `?`, and in a nullable context). This is to avoid breaking changes. Many APIs created before NRT would use the default value to definitely assign the variable when no better value was available. This is generally part of the `Try*` pattern. Rather than change all those APIs for minimal value, and introducing a potential breaking change, nullable analysis uses the additional attributes on many of these APIs.

For the third set of comments, yes, the argument can be an expression with the value `null`, see above example.

Finally, "nullable aware" should be replaced with "compiled in a nullable enabled context".

**Comment by Uzivatel919** [comment]
See also https://github.com/dotnet/docs/issues/25416 for _null state_ that does not exists.
