### ISSUE TITLE
Postconditions: MaybeNull and NotNull | `T?` can be used as return type

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25078]
From [Postconditions: MaybeNull and NotNull](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)

> You can't specify that the return value is `T?`. The method returns `null` when the sought item isn't found. Since you can't declare a `T?` return type, you add the `MaybeNull` annotation to the method return:

This is similar to #24980 – see https://github.com/dotnet/docs/issues/24980#issuecomment-873421206.

There should be likely something like _Since you should evade using T? in unconstrained methods …_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#summary)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding to the next sprint.

**Comment by Uzivatel919** [comment]
[Generic definitions and nullability](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#generic-definitions-and-nullability)

**Comment by Uzivatel919** [comment]
Behavior for `T?` substitution is described at [Unconstrained type parameter annotations|? annotation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/unconstrained-type-parameter-annotations#-annotation). Still even if `T?` for `value type` is substituted with `T`, it is possible to use `T?` as `parameter` or `return type`.
