### ISSUE TITLE
Top result for C# on Google is a page not in TOC

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2507]
Search results for [C# on Google](https://www.google.com/search?q=c%23) bring this page as its first result: https://docs.microsoft.com/en-us/dotnet/csharp/csharp

That page is not linked to the TOC, so we should remove it from the docset and redirect it to the [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/).

But I'm wondering if we should have an introductory sentence about C# on the C# Guide similar to what the top result page has or what the F# Guide page has. @BillWagner?

**Comment by mairaw** [comment]
I think it would be good to get this fixed soon @BillWagner.  The page should probably be redirected to https://docs.microsoft.com/en-us/dotnet/csharp. The only issue I see right now is that nowhere we state what C# is like we do in this page. So the paragraph from this topic could probably be the opening paragraph for the C# Guide. Thoughts?

**Comment by BillWagner** [comment]
@mairaw I have a PR for this #2986 
I goofed and neglected to reference this issue in the PR. I just updated it for that.
