### ISSUE TITLE
Attributes for null-state static analysis| Attributes meaning overview

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25071]
From [Attributes for null-state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

### Overview 

Attribute | Category | Meaning
-- | -- | --
AllowNull | Precondition | A non-nullable argument may be null.
DisallowNull | Precondition | A nullable argument should never be null.
MaybeNull | Postcondition | A non-nullable return value may be null.
NotNull | Postcondition | A nullable return value will never be null.
MaybeNullWhen | Conditional postcondition | A non-nullable argument may be null when the method returns the specified bool value.
NotNullWhen | Conditional postcondition | A nullable argument won't be null when the method returns the specified bool value.
NotNullIfNotNull | Conditional postcondition | A return value isn't null if the argument for the specified parameter isn't null.
MemberNotNull | Constructor helper methods | The listed member won't be null when the method returns.
MemberNotNullWhen | Constructor helper methods | The listed member won't be null when the method returns the specified bool value.
DoesNotReturn | Unreachable code | A method never returns. In other words, it always throws an exception.
DoesNotReturnIf | Unreachable code | This method never returns if the associated bool parameter has the specified value.

### Attribute usage

This table lists `attributes` that has slightly incomplete description in _Meaning_ column as corroborates [AttributeTargets Enum](https://docs.microsoft.com/en-us/dotnet/api/system.attributetargets?view=net-5.0) for each of them.

Attribute | AttributeTargets
-- | -- 
[`AllowNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.allownullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property`
[`DisallowNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.disallownullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property`
[`MaybeNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.maybenullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property` &#124; `ReturnValue`
[`NotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=net-5.0) |  `Field` &#124; `Parameter` &#124; `Property` &#124; `ReturnValue`
[`NotNullIfNotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullifnotnullattribute?view=net-5.0) | `Parameter` &#124; `Property` &#124; `ReturnValue`
[`MemberNotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute?view=net-5.0)  | `Method` &#124; `Property`
[`MemberNotNullWhen`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullwhenattribute?view=net-5.0) | `Method` &#124; `Property`
---

1. Using terminologically exact term `argument` (in impossible context) should be avoided. `Attribute` can be applied only to `parameter` (method signature) as one can sense ouf of `AttributeTargets.Parameter` value.  It is impossible to apply `attribute` on `argument` (calling site).
2. [`DoesNotReturnAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute?view=net-5.0) is not limited to always throwing methods.

```csharp
[DoesNotReturn]
public void BeReadingFromNetworkInterface ()
{
  while ( true )
  {
     // Never breaks and ends with application domain.
  }
}
```
The same applies to [DoesNotReturnIfAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnifattribute?view=net-5.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Uzivatel919 

For 1) 

> Using terminologically exact term argument (in impossible context) should be avoided. Attribute can be applied only to parameter (method signature) as one can sense ouf of AttributeTargets.Parameter value. It is impossible to apply attribute on argument (calling site).

I'll review the entire article more carefully when I update this, but in most of the uses above, *argument* is correct. While the attribute is applied to the parameter, the presence of the attribute affects the null state static analysis of the *argument* used when calling a method. This is true for the \*When attributes. 

On 2): Good point.

**Comment by Uzivatel919** [comment]
I noticed that incomplete `meaning` regard attribute target is repeated in each respective chapter and also in article [Summary](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#summary).
