### ISSUE TITLE
Missing "use"

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#25089]
The text for "Return Value and Exception Handling" states
"For returns a System.Threading.Tasks.ParallelLoopResult object when all threads have completed."

when it should say
"For returns use a System.Threading.Tasks.ParallelLoopResult object when all threads have completed."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629911c2-f9cc-7deb-df8e-3012d3e6afd0
* Version Independent ID: 1603adc7-b23f-ff8f-4c18-7c3f84fbcba8
* Content: [How to: Write a Simple Parallel.For Loop](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi again @DickBaker - If you're to create a PR for #25087, it might make since to address this minor typo as well. I've applied the up-for-grabs to this issue, and welcome you to propose the fix to the article through a pull request. I'd happily review it, just tag me and reference this issue number. Thank you.

**Comment by Naidile-P-N** [comment]
Since **For** is referred to as a keyword here, I think the statement is correct. @IEvangelist Please correct me otherwise!

**Comment by IEvangelist** [comment]
> Since **For** is referred to as a keyword here, I think the statement is correct. @IEvangelist Please correct me otherwise!

I would disagree, I think when referring to a specific method it's best to use an [Xref](https://docs.microsoft.com/contribute/how-to-write-links#xref-cross-reference-links) which correctly makes the word "For" a link to the method.

**Comment by Naidile-P-N** [comment]
> > Since **For** is referred to as a keyword here, I think the statement is correct. @IEvangelist Please correct me otherwise!
> 
> I would disagree, I think when referring to a specific method it's best to use an [Xref](https://docs.microsoft.com/contribute/how-to-write-links#xref-cross-reference-links) which correctly makes the word "For" a link to the method.

Sorry, my bad! For is actually a link in the doc.
