### ISSUE TITLE
Use normal string[] args

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#25087]
the first code example makes explicit call to obtain the command-line argument instead of using the normal Main params
 https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop#directory-size-example

happily the remaining code uses the familiar & standard approach [less brain cycles required!]

Would also be nice to use a local variable to hold that directory argument for arg[0] rather than repeated arg[1] stuff

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629911c2-f9cc-7deb-df8e-3012d3e6afd0
* Version Independent ID: 1603adc7-b23f-ff8f-4c18-7c3f84fbcba8
* Content: [How to: Write a Simple Parallel.For Loop](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @DickBaker - I agree that it is much easier to understand with `Main(string[] args)` than calling `Environment.GetCommandLineArgs()`. I've applied the `up-for-grabs` to this issue, and welcome you to propose the fix to the article through a pull request. I'd happily review it, just tag me and reference this issue number. Thank you.
