### ISSUE TITLE
Redirect C# tutorials page from msdn

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2508]
Search results for [C# on Google](https://www.google.com/search?q=c%23) bring this very old page from MSDN as its second result: https://msdn.microsoft.com/en-us/library/aa288436(v=vs.71).aspx

That page has around 30k page views per month. We should redirect that page to https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/ once we feel we have our basic C# tutorials covered in here. Might become a larger project.

/CC @BethMassi since we discussed this way back when 😄

**Comment by mairaw** [comment]
@BillWagner @LadyNaggaga apparently that content set is now retired and the page redirects to a download page. Should we redirect that page to quick starts already? I think it would be good to start getting that SEO juice the old page has.

@ghogen do you know when the vs.71 version was retired? Maria and I were looking at those tutorials online not long ago.

**Comment by BillWagner** [comment]
I'd like to redirect to the "Quick Starts":  https://docs.microsoft.com/dotnet/csharp/quick-starts

**Comment by mairaw** [comment]
I think so too. Let me file a request then.

**Comment by LadyNaggaga** [comment]
Do you have plan in place to migrate some of the more popular msdn tutorials to the quick start guide?

**Comment by mairaw** [comment]
@BillWagner was creating a project for adding new tutorials like for arrays and can comment on this. I wasn't aware this was going to be redirected now; otherwise, I'd have grabbed the BI data for those ahead of time. I'll try to grab some data still. But won't have time to do that this week.

**Comment by BillWagner** [comment]
@LadyNaggaga You'll start to see issues listed in the [quickstarts](https://github.com/dotnet/docs/projects/18) project, in the [samples](https://github.com/dotnet/docs/projects/20) project, and in the [tutorials](https://github.com/dotnet/docs/projects/19) project.

There's a bit of a branding update here as well:  Moving forward, to be consistent across all the docs libraries, "tutorials" will generally by larger programs that span multiple services. That's why you'll see more of the tutorials rebranded as "quick starts" or "samples".

**Comment by BillWagner** [comment]
Setting the priority to P2, as the top two results are the docs C# Guide, followed by the docs C# Programming guide. Not perfect, but much better.

**Comment by BillWagner** [comment]
Just tested with the same results as above. The C# Quickstarts still have low SEO on a C# search

**Comment by mairaw** [comment]
I think this could be closed @BillWagner. The top 3 results for C# on Google now go to Docs. You could add a link to the quickstarts from the second result (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/) and then maybe this will help bring C# quickstarts closer to the top results for just C#. 

Quickstarts is the top results for C# tutorials and 2nd for C# tutorial.
