### ISSUE TITLE
.NET 6 template changes for `dotnet new console`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#25085]
For .NET 6, in preview 7, the “dotnet new console” app and Visual Studio’s “File:New Project” template for console apps will use top level statements. 

We expect new developers to find this confusing if they are following an existing tutorial that shows the earlier Program.cs generated by those templates.

We need a new doc that helps these customers map from the tutorial text (using `static void Main()` in a `Program` class in a namespace) to the new output using top-level statements.

This new article will be linked from an aka.ms link that describes the changes.

**Comment by KathleenDollard** [comment]
This looks good and matches the goal. I'd add that multiple people will encounter this link. We might want a landing page that has a bit about what top level programs are and has a few links: 

* Creating your first program using top level programs
* Understanding top level programs
  * Compiler feature, no runtime changes
  * The class name is unspeakable (can't access from tests) although we are open to feedback on that
  * Multiple lines can be used (this has not been obvious to a couple people I have talked to, so making this easy)
  * If you add methods, they are local methods
  * Adding classes looks legal. I'm pretty sure they are nested in the unspeakable class for use by Main. Adding a namespace may change that. 
  * They (of course) have access to implicit usings and any global usings set for the project

This last set of things would be super confusing for a new user, but pretty essential for any current programmer. Some of this is demonstrated in the current tutorial https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements, but not laid out directly. That tutorial needs will not be best practice for C# 10 (implicit usings)

**Comment by BillWagner** [comment]
Thanks @KathleenDollard 

I think [this article](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements) covers a lot of your additional points.

I'd like to keep this new link destination a short article that explains how to build the mental map from top-level programs to traditional tutorial content. That will point to these two articles, and let people explore more when they are ready. But the first touch is to remove the confusion by having different code than you were expecting.
