### ISSUE TITLE
Linux dependencies links do not resolve to dependecy docs

### ISSUE THREAD

**Issue by leecow** [dotnet/docs#25086]
The distro-specific install pages include [.NET Core dependencies and requirements](https://docs.microsoft.com/en-us/dotnet/core/install/linux) which takes you to the top-level Linux install page but does not offer any information on dependencies or requirements. I think we were intending to include information similar to https://github.com/dotnet/core/blob/main/Documentation/linux-prereqs.md?

**Comment by adegeo** [comment]
@leecow The title for that link is out of date. They should read `Install .NET on Linux`. The dependencies for each distro are listed in the distro page. Do you think we need to adjust something? I'll open a PR to update the link titles.

**Comment by leecow** [comment]
Thanks, Andy. I see them now. The dependency list is most important when someone is doing a manual install using the tar.gz files. I see dependency content on https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install so think we're OK now.
