### ISSUE TITLE
Compiler Error Pages do not follow stylistic conventions

### ISSUE THREAD

**Issue by jack9761** [dotnet/docs#25097]
The format of compiler error pages does not follow the official [C# coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions). This only seems to be a problem on the line that directly causes the compiler error, which also has the comment about how to resolve the issue on the same line.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ca3560-3086-2819-9fec-dbead5bdc34b
* Version Independent ID: c3ff4ab4-e153-102b-84f3-7f8459c7b994
* Content: [Compiler Error CS0077](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0077?f1url=%3FappId%3Droslyn%26k%3Dk(CS0077))
* Content Source: [docs/csharp/misc/cs0077.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0077.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for noting this @jack9761 

I've added this to the backlog, and added the "up for grabs" label should any community member want to issue a PR in the meantime.
