### ISSUE TITLE
Additional point to Commenting conventions

### ISSUE THREAD

**Issue by pradeepradyumna** [dotnet/docs#25099]
Under **Commenting conventions** we can include one more point

- Ensure all publicly exposed members like Methods or Properties that marked using either `public`, `internal`, or `protected ` 
which you see are being called from outside the class or the assembly then have necessary XML comments providing appropriate descriptions about their presence so that it helps developers that are consuming these members at the client-side

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @pradeepradyumna It's a good suggestion

I've added to our list for the next update to this article. I've also added the "up for grabs" label in case anyone wants to submit a PR in the meantime.
