### ISSUE TITLE
Painless Upgrade to .NET 5

### ISSUE THREAD

**Issue by MACEL94** [dotnet/docs#25098]
Hi

i just followed along and everything worked with no problem, using only port 80 but targeting .net 5.
You can check the code here if you need it: https://github.com/MACEL94/DaprMultiContainer

I'd say you can update guidelines to .NET 5, or i can submit a pull request if you want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Hi @MACEL94! Thanks for the feedback.
PR would be highly appreciated 😊

**Comment by MACEL94** [comment]
Hi @amolenk 

It will be my first one so i'll try not to mess everything up :)

Consider it done!
