### ISSUE TITLE
Website version is shown as 1.0, PDF download is still Preview Edition

### ISSUE THREAD

**Issue by drchilds** [dotnet/docs#25109]
Issue is as stated in the title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8972f9e3-cbd7-1b87-93ec-61c576aa25ea
* Version Independent ID: 5e8613bd-c26d-53df-7ff9-eff7275e3384
* Content: [Dapr for .NET Developers](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/)
* Content Source: [docs/architecture/dapr-for-net-developers/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/index.md)
* Product: **dotnet-architecture**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @drchilds , could you please download the latest [PDF](https://aka.ms/dapr-ebook)? Thank you.
