### ISSUE TITLE
Configure CustomFormatter through 'appsettings.json'

### ISSUE THREAD

**Issue by Salazander** [dotnet/docs#25116]
The sample code shows how the built-in 'json' formatter can be configured through 'appsettings.json'.
What about the CustomFormatter? How does one go about configuring a custom formatter through 'appsettings.json'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daf7ff20-63e5-215c-047b-92d414eb314b
* Version Independent ID: 6bde6805-1867-ebfc-9773-a792b75318fe
* Content: [Console log formatting](https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter)
* Content Source: [docs/core/extensions/console-log-formatter.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/console-log-formatter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Salazander
Thank you so much for posting this issue. We really appreciate it. It should be the exact same way, except you have to configure the options through DI correctly. I could add an example to the doc if you'd like?

- [Set formatter with configuration](https://docs.microsoft.com/dotnet/core/extensions/console-log-formatter#set-formatter-with-configuration)
  - Add whatever new config values should be mapped
- [Implement custom formatter](https://docs.microsoft.com/dotnet/core/extensions/console-log-formatter#implement-a-custom-formatter)
  - Create the custom config object and derive from [`JsonConsoleFormatterOptions`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.console.jsonconsoleformatteroptions)
  - Call [`AddConsoleFormatter`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addconsoleformatter?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Logging_ConsoleLoggerExtensions_AddConsoleFormatter__2_Microsoft_Extensions_Logging_ILoggingBuilder_)

See, [Options pattern in .NET](https://docs.microsoft.com/dotnet/core/extensions/options) for more info.

**Comment by Salazander** [comment]
Thanks a lot @IEvangelist!
