### ISSUE TITLE
C# Visual Studio IDE

### ISSUE THREAD

**Issue by Bmandue** [dotnet/docs#25119]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c7d191-7c09-0bd8-32b2-527748c41882
* Version Independent ID: fefbef5d-bc47-9458-1ba5-86388d2c251a
* Content: [Compiler Error CS0117](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0117?f1url=%3FappId%3Droslyn%26k%3Dk(CS0117))
* Content Source: [docs/csharp/misc/cs0117.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0117.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@Bmandue Can you please add more information to the issue?

**Comment by Bmandue** [comment]
It was about a code for c# for reloading

**Comment by BillWagner** [comment]
I don't think reloading is relevant to this warning.

Closing.
