### ISSUE TITLE
Incorrect regex given for matching hrefs

### ISSUE THREAD

**Issue by arctangent** [dotnet/docs#25118]
The example regex is incorrect because it does not correctly match unquoted hrefs which immediately precede the opening anchor tag's closing bracket.

Reproduction:

Input: `<a href=foo.com>Hello world</a>`

Your regex matches:  `foo.com>Hello` (Group 1)

Suggested fix:

Amend the regex to the following: `string HRefPattern = @"href\s*=\s*(?:[""'](?<1>[^""']*)[""']|(?<1>[^>\s]+))";`

Note that I have substituted your `\S+` at the end of the regex with `[^>\s]+`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130f000e-0ec1-e248-f804-631d3bda2711
* Version Independent ID: 25a9e501-343e-2ef4-05bc-1abc92b3ea96
* Content: [Regular Expression Example: Scanning for HREFs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-example-scanning-for-hrefs)
* Content Source: [docs/standard/base-types/regular-expression-example-scanning-for-hrefs.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-example-scanning-for-hrefs.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for this suggestion, I'll get it fixed up.
