### ISSUE TITLE
No list of "workarounds" for this error even though workarounds are referenced in the error and this page.

### ISSUE THREAD

**Issue by davidfordaus** [dotnet/docs#25121]
Please provide links to appropriate workarounds for this error.  Do not make an API obsolete without provide links or direction on resolution.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b872cf4f-7dcc-07b7-1419-248e8d1351c6
* Version Independent ID: 7dc0d15f-b309-0755-1547-2ecc00876f26
* Content: [SYSLIB0009 warning - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0009)
* Content Source: [docs/fundamentals/syslib-diagnostics/syslib0009.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/syslib0009.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by steveberdy** [comment]
Hi @davidfordaus. One possible workaround would be to make your own class that inherits [`IAuthenticationModule`](https://docs.microsoft.com/en-us/dotnet/api/system.net.iauthenticationmodule?view=net-5.0). The [`AuthenticationManager`](https://docs.microsoft.com/en-us/dotnet/api/system.net.authenticationmanager?view=net-5.0) inherits from it, but usage of the interface does not appear to be obsoleted. If you implement `IAuthenticationModule`, you just have to implement [`Authenticate()`](https://docs.microsoft.com/en-us/dotnet/api/system.net.iauthenticationmodule.authenticate?view=net-5.0) and [`PreAuthenticate()`](https://docs.microsoft.com/en-us/dotnet/api/system.net.iauthenticationmodule.preauthenticate?view=net-5.0). If that helps, I could update the docs.
