### ISSUE TITLE
Searching Google about encrypring in C# results in a very outdated support.MS article

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2513]
As highlighted by [a reddit post](https://www.reddit.com/r/programming/comments/6jq62q/how_not_to_encrypt_a_file_courtesy_of_microsoft/djgcif2/), [searching Google for "how to encrypt data in C#"](https://www.google.com/search?q=how+to+encrypt+data+in+C%23) prominently shows [a very outdated and reportedly very bad support.microsoft.com article](https://support.microsoft.com/en-us/help/307010/how-to-encrypt-and-decrypt-a-file-by-using-visual-c) ([here is an article about how bad the support.MS article is, which did not even notice how outdated it is](https://medium.com/@bob_parks1/how-not-to-encrypt-a-file-courtesy-of-microsoft-bfadf2b0273d)). docs.MS also appears in the results, but is much less prominent.

Is there something that can be done about the outdated support.microsoft.com article, so that people are not misled into following it?

![](https://user-images.githubusercontent.com/287848/27586354-48ef2230-5b40-11e7-91b9-8524602c0cbd.png)

**Comment by cartermp** [comment]
cc @blowdart

**Comment by blowdart** [comment]
A deletion request went in two hours ago

**Comment by svick** [comment]
The support.MS article has been deleted. Now it should be only a matter of time until Google delists it, so I think this can be closed.
