### ISSUE TITLE
typo in ~DerivedClassWithFinalizer()

### ISSUE THREAD

**Issue by hagaigold** [dotnet/docs#25147]
`~DerivedClassWithFinalizer() => this.Dispose(true);`
this code I belive have a typo - it should call this.Dispose(**false**)

Ref to snippets-

https://github.com/dotnet/docs/blob/d36c36e135a5af1e224bd91f2b7b324c8de88d90/samples/snippets/csharp/VS_Snippets_CLR_System/system.idisposable/cs/derived2.cs#L6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implement a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@IEvangelist Can you take a look at this issue?

**Comment by IEvangelist** [comment]
There is already a PR that addresses this : #25122. Closing this as a duplicate.
