### ISSUE TITLE
Access to DerivedClass2

### ISSUE THREAD

**Issue by RobertGBryan** [dotnet/docs#25153]
"If Assembly1.cs contains an InternalsVisibleToAttribute that names Assembly2, the derived class DerivedClass1 will have access to private protected members declared in BaseClass."

As written, this does not make any sense, since DerivedClass1 already has access. Assembly2 contains DerivedClass2, so DerivedClass1 should be changed to DerivedClass2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5e6972-0f7a-8bb7-9f5a-0ba75909f9d8
* Version Independent ID: 618c0361-38a0-4d6f-f46a-881db2e4b399
* Content: [private protected - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected)
* Content Source: [docs/csharp/language-reference/keywords/private-protected.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/private-protected.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @RobertGBryan 

The article is correct as written.  The `private protected` access modifier means that the method is visible to derived classes in the same assembly.  The situation you're describing above applies to `protected internal`.  

The best way to remember it is this:

- `private protected` means *derived types* AND *in the same assembly*.
- `protected internal` means *derived types* OR *in the same assembly*.

I'll close this as an answered question.

**Comment by RobertGBryan** [comment]
Hi @BillWagner,
One of us appears to be a little confused. I sure hope its not me. 
So, first off, your analysis of private protected and protected internal is correct. But, that is not really relevant here. What is relevant is that the article says:
"If Assembly1.cs contains an InternalsVisibleToAttribute  that names Assembly2, the derived class DerivedClass1 will have access to private protected members declared in BaseClass. InternalsVisibleTo makes private protected members visible to derived classes in other assemblies."
If you look up the InternalsVisibleToAttribute link, it says:
"Specifies that types that are ordinarily visible only within the current assembly are visible to a specified assembly."

Again, DerivedClass1 already has access because it is both in the same assembly and it is a derived class. If you look at the code:
 // OK, accessed through the current derived class instance 
myValue = 5;

So, clearly DerivedClass1 clearly already has access. There is no reason to give it access with the InternalsVisibleToAttribute class. The only reason for specifying Assembly2 via the InternalsVisibleToAttribute class is so that DerivedClass2 will have access. Notice the code for DerivedClass2:
// Error CS0122, because myValue can only be// accessed by types in Assembly1// myValue = 10;

The reason for using the InternalsVisibleToAttribute class here is to fix the compilation error in DerivedClass2.
Also, notice that DerivedClass1 is not in Assembly2. It is in Assembly1. So, why would the documentation try to claim that naming Assembly2 gives access to DerivedClass1? DerivedClass2 is in Assembly2. So, clearly this is just a simple typo.
The documentation should say:
"If Assembly1.cs contains an InternalsVisibleToAttribute  that names Assembly2, the derived class DerivedClass2 will have access to private protected members declared in BaseClass. InternalsVisibleTo makes private protected members visible to derived classes in other assemblies."
I tried to explain this as simply as possible. If you still do not understand it, then please talk to either a senior software engineer or a manager.
Please reopen and / or escalate if you insist that it is still correct as written.
Sincerely yours,
Bob Bryan    On Thursday, July 15, 2021, 06:27:15 AM PDT, Bill Wagner ***@***.***> wrote:  
 
 


Closed #25153.

**Comment by BillWagner** [comment]
Thanks for clarifying @RobertGBryan I missed which sentence you were referring to.

Reopening.

**Comment by BillWagner** [comment]
@RobertGBryan I just opened #25169 to fix this. Thanks for re-engaging so that it's fixed.
