### ISSUE TITLE
Update for the note?!?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/docs#25167]
on the end of the article, part of the note states `On Windows NT 3.5 and later, and Windows Vista operating systems, the clock's resolution is approximately 10-15 milliseconds.`
Is this still accurate for .Net 5 running on MS official images?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2691d246-9d0a-5714-a3a3-19aabfb3c5cd
* Version Independent ID: 80f9e353-0de8-c715-233e-033e6dd3c375
* Content: [How to: Display Milliseconds in Date and Time Values](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-milliseconds-in-date-and-time-values)
* Content Source: [docs/standard/base-types/how-to-display-milliseconds-in-date-and-time-values.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/how-to-display-milliseconds-in-date-and-time-values.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. @tarekgh can you comment?

**Comment by tarekgh** [comment]
@Leonardo-Ferreira Vista is out of support so we can remove this note. do you want to submit a PR for that?

**Comment by tarekgh** [comment]
CC @mattjohnsonpint

**Comment by Leonardo-Ferreira** [comment]
Hi! my greatest concern is not how this item behaves for legacy OS, but how long is "the clock's resolution" for the new platforms. If you could provide the updated numbers for at least the images of LTS versions, such as `mcr.microsoft.com/dotnet/runtime:5.0` and `mcr.microsoft.com/dotnet/runtime:3.1`

**Comment by tarekgh** [comment]
Clock resolution for netcore 3.1 and 5.0 are same and not changed. We just call [GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime?redirectedfrom=MSDN) which states:

```
The GetSystemTimePreciseAsFileTime function retrieves the current system date and time with the highest possible level of precision (<1us). The retrieved information is in Coordinated Universal Time (UTC) format.
```

The catch is `GetSystemTimePreciseAsFileTime` is supported on Windows 8 and up. If running on previous OS versions, we call `GetSystemTimeAsFileTime` which has less resolution.

**Comment by Leonardo-Ferreira** [comment]
But its still 10-15ms resolution? what about for non-windows machines, like the official images I mentioned above?

**Comment by tarekgh** [comment]
> But its still 10-15ms resolution?

The only support Windows version we need to use `GetSystemTimeAsFileTime` on is Windows 7. I don't have the exact precision number of `GetSystemTimeAsFileTime` on Windows 7 but I expect would be from 1 to 15 ms.

> what about for non-windows machines, like the official images I mentioned above?

On non-Windows we usually call [clock_gettime](https://linux.die.net/man/3/clock_gettime). The clock resolution can be retrieved on such OS's by calling `clock_getres()`.
