### ISSUE TITLE
snap not working with rider

### ISSUE THREAD

**Issue by Steedalion** [dotnet/docs#25164]
See the final comment by Stachu here [https://stackoverflow.com/questions/43048629/netcore-project-loading-failed-in-jetbrains-rider-on-windows]

I have tried 5.0 and 3.1 of dontnet sdk but it does not work with it. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40005eb-f935-d50d-10ce-c1e0a47ea70e
* Version Independent ID: 91f4a9b7-09d0-f18e-af4a-c0af28a8948f
* Content: [Install .NET on Linux with Snap - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)
* Content Source: [docs/core/install/linux-snap.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-snap.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. I can't really comment on why Rider has issues with snap-installed .NET. You may want to ask JetBrains for support. 😦
