### ISSUE TITLE
Options Pattern Guidance for IConfiguration overload should mention required NuGet package

### ISSUE THREAD

**Issue by RayKoopa** [dotnet/docs#25172]
https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#iconfiguration-parameter

In my opinion, this section should mention that in order to call `services.Configure<LibraryOptions>(namedConfigurationSection)`, the package `Microsoft.Extensions.Options.ConfigurationExtensions` is required for the linked `IServiceCollection.Configure<T>(IConfiguration config)` overload.

While this is slightly visible [in the documentation for the overload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsconfigurationservicecollectionextensions.configure) due to the assembly name given at the top, I've missed it several times already when writing a .NET 5 library with `ServiceProviderExtensions` from scratch where I only added packages as needed.

Related:
- https://github.com/dotnet/AspNetCore.Docs/issues/18833
- https://stackoverflow.com/questions/61352682/error-cs1503-cannot-convert-from-microsoft-extensions-configuration-iconfigura

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 
Thank you so much for posting this issue. We really appreciate it. I'll update the article to make that more obvious.
