### ISSUE TITLE
Where is the sample app source code?

### ISSUE THREAD

**Issue by wdspider** [dotnet/docs#25175]
The third paragraph of this article refers to a sample app:
> The sample app demonstrates LoggerMessage features with a priority queue processing worker service. The app processes work items in priority order. As these operations occur, log messages are generated using the LoggerMessage pattern.

However, I cannot find a link to view the sample app's source code.  I was really hoping to review how the different pieces of the app mentioned within the article where actually put together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c051-c047-bbcd-5e25-ca6a722b51c3
* Version Independent ID: 3f5f1b6e-06ac-cc07-48cd-b8b957a4abbb
* Content: [High-performance logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging)
* Content Source: [docs/core/extensions/high-performance-logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/high-performance-logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by tdykstra** [comment]
Fixed by #25402
