### ISSUE TITLE
Typo in minor roll-forward example

### ISSUE THREAD

**Issue by hvdbrand** [dotnet/docs#25183]
"When run, version 5.0.* isn't installed, however, 5.1.0 is. Version 3.1.0 will be used." should have been When run, version 5.0.* isn't installed, however, 5.1.0 is. Version 5.1.0 will be used."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET version to use - .NET](https://docs.microsoft.com/en-us/dotnet/core/versions/selection)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/main/docs/core/versions/selection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
