### ISSUE TITLE
Link error : "Let's Learn .NET: F# On July 30, ..."

### ISSUE THREAD

**Issue by fffsharp** [dotnet/docs#25202]
The link that appears in the header section is broken.    
Could you please fix it to the correct link?  

![](https://pbs.twimg.com/media/E6elERqVIAASN5e?format=jpg&name=large)

**Comment by fffsharp** [comment]
The link is "https://docs.microsoft.com/en-us/events/learntv/lets-learn-net-fsharp-july-2021/", but correct link is "https://docs.microsoft.com/en-us/events/learntv/lets-learn-net-fsharp/".

> The link that appears in the header section is broken.
> Could you please fix it to the correct link?
> 
> ![](https://camo.githubusercontent.com/e1629ffd7b526b9b39493d016c3687f862c571def43130831fe863e21e4ca9e1/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4536656c45527156494141534e35653f666f726d61743d6a7067266e616d653d6c61726765)

**Comment by fffsharp** [comment]
The link is "https://docs.microsoft.com/en-us/events/learntv/lets-learn-net-fsharp-july-2021/", but correct link is "https://docs.microsoft.com/en-us/events/learntv/lets-learn-net-fsharp/".

**Comment by gewarren** [comment]
Example page that has the banner: https://docs.microsoft.com/en-us/dotnet/fsharp/

**Comment by gewarren** [comment]
@isabelamhoban Can you fix this please?

**Comment by isabelamhoban** [comment]
@gewarren Hello! The change has already been merged and shipped to the live site, so it should be corrected within the next few hours (by tomorrow morning at the latest!) Thanks for your patience.

**Comment by gewarren** [comment]
@isabelamhoban This still doesn't seem to be fixed.

**Comment by isabelamhoban** [comment]
@gewarren Hi - can you try again now? It looks like the link just went live for me

**Comment by gewarren** [comment]
> @gewarren Hi - can you try again now? It looks like the link just went live for me

Yes, thank you! Will close the issue now.
