### ISSUE TITLE
Document `OptimizeImplicitlyTriggeredBuild` property

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#25214]
This was added in https://github.com/dotnet/roslyn/pull/54143 for dev17 and enhanced in https://github.com/dotnet/roslyn/pull/54913.

> For builds which are indirectly triggered inside Visual Studio from commands such as from 'Run Tests' or 'Start Debugging', we implicitly skip analyzers and nullable analysis to speed up the build.
> We only do so by default when 'TreatWarningsAsErrors' is not 'true'. For the scenario where 'TreatWarningsAsErrors' is 'true', users can explicitly enable this functionality by setting 'OptimizeImplicitlyTriggeredBuild' to 'true'.	

cc @mavasani @gewarren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
We should also document compiler's nullable analysis being implicitly skipped for implicitly triggered builds: https://github.com/dotnet/roslyn/pull/54913
