### ISSUE TITLE
Recommendation to use WCF as an alternative to Remoting, when WCF is also removed from .NET 5

### ISSUE THREAD

**Issue by JasonJShuler** [dotnet/docs#25234]
WCF is suggested as an alternative to .NET Remoting, but WCF is removed from .NET 5. Shouldn't gRPC be the recommended replacement?

Also, isn't remoting used for Office interop? I haven't looked yet, but is Office interop still available with .NET 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cc0e71-91bb-defc-ca58-0023e4d3b276
* Version Independent ID: f2eb4ab4-72a4-ae0a-acf8-be39bb3f08f7
* Content: [Breaking change: Remoting APIs are obsolete - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/remoting-apis-obsolete)
* Content Source: [docs/core/compatibility/core-libraries/5.0/remoting-apis-obsolete.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/5.0/remoting-apis-obsolete.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jeffhandley Could you comment on this question/suggestion for alternatives to obsolete remoting APIs?

**Comment by jeffhandley** [comment]
@mconnew Would you mind weighing in here?

**Comment by mconnew** [comment]
@shirhatti, can you respond as to what our guidance should be?

**Comment by shirhatti** [comment]
![image](https://user-images.githubusercontent.com/4734691/127699311-e66ab725-4f0e-4b60-b1a6-fa70ab39505b.png)

**Comment by jeffhandley** [comment]
That's very useful, @shirhatti! Is there a canonical documentation page that includes this infographic somewhere?

@JasonJShuler Does this provide the guidance you needed?

**Comment by JasonJShuler** [comment]
@jeffhandley Thanks, I appreciate it!
I'm still not sure this addresses the documentation though - it recommends using WCF - which is largely removed - to replace remoting - which is also removed. If you are choosing "no" to modernize, would you not just continue using remoting?

**Comment by shirhatti** [comment]
Apologies I realize I pasted in the picture without my comments. Continue to use .NET remoting **OR** WCF (whatever your existing tech is) if you chose not to modernize. The recommendation section of this doc probably needs updating to capture that nuance.

I didn't have the source for the diagram handy, just the pre-rendered image 😅

@jeffhandley This is from a talk that Matt and I gave a while ago. There isn't a canonical doc page for this

**Comment by mconnew** [comment]
Even on .NET Framework .NET Remoting has been soft deprecated. There are some unsolvable security problems with it. The guidance is that it shouldn't be used unless the network it's being used in is secure. You can mitigate the security issues by requiring clients to be authenticated, but that's just blocking access to remoting with security and not making remoting itself safe. I would strong suggest moving off of remoting, even if you are staying on .NET Framework.

**Comment by mconnew** [comment]
@JasonJShuler, the client part of WCF is available in .NET Core/.NET and fully supported by Microsoft. Although not all features have been ported, we do continue to port more features over. As the diagram mentions, there is the open source CoreWCF. It really depends on what interop you need with other stacks, which programming model you are more comfortable with, whether you require everything to be 100% supported by Microsoft etc.

**Comment by JasonJShuler** [comment]
@mconnew ok, that clears it up for me, thanks!
