### ISSUE TITLE
Variant delegates in variant interfaces. Why are keywords needed?

### ISSUE THREAD

**Issue by NikVladi** [dotnet/docs#25233]
https://docs.microsoft.com/en-us/answers/questions/481118/variant-delegates-in-variant-interfaces-why-are-ke.html

I really ask you to answer my question as concretely as possible, because I'm just desperate, everyone on the forums behaves as if they understand everything, but everyone just wants to get rid of me, I just don't understand one point and ask the question.
The question arose about the need for keywords in variant delegates if their events are in variant interfaces. The question only concerns the in and out keywords for delegates.

Once we create an interface with the in keyword, we need a delegate with the out keyword, why? After all, delagate without the out keyword somehow has covariance, but only for methods, not delegate instances, which means I could have put the method on the event anyway, but not the delegate instance. But we cannot do this.

```
namespace ConsoleApp1
 {
     class Program
     {
         static void Main (string [] args)
         {
             //Step 1
             B MyMethodReturnB ()
             {
                 return new B ();
             }
    
             // Step 2
             MyClass <A> MyClassForA = new MyClass <A> ();
             MyClassForA.MyEvent + = MyMethodReturnB; // In MyClass <A> (), you can put data of type B using the MyMethodReturnB method and without the out keyword in the MyDelegateReturn delegate
    
             // Step 3
             MyDelegateReturn <B> MyDelegateReturnForB = new MyDelegateReturn <B> (MyMethodReturnB);
             //MyClassForA.MyEvent + = MyDelegateReturnForB; // But when we try to pass data of type B through a delegate variable without the out keyword, an error occurs, this is how variability works in delegates.
                                                            // Without the in and out keywords, one delegate cannot be assigned to another delegate
    
             // Step 4
             IMyInterface <B> IMyInterfaceForB = MyClassForA; // Through the IMyInterface <B> interface without the in keyword, you cannot put MyClass <A> (), but if IMyInterface <B> with the in keyword, then we can
    
             // Step 5
             // Once we create an interface with the in keyword, we need a delegate with the out keyword, why?
             // In the end, delagate without the out keyword somehow has covariance, but only for methods, not delegate instances, which means I could have put the method on the event anyway, but not the delegate instance. But we can't do this
         }
     }
    
     class A
     {
    
     }
    
     class B: A
     {
    
     }
    
     delegate T MyDelegateReturn </ * out * / T> (); // Everything works with the out keyword
    
     interface IMyInterface <in T>
     {
         event MyDelegateReturn <T> MyEvent; // Error due to delegate without out keyword
     }
    
     class MyClass <T>: IMyInterface <T>
     {
         public event MyDelegateReturn <T> MyEvent;
     }
 }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e34cc1a-4658-d7ce-741d-8d81c1701682
* Version Independent ID: 1fcbc3ff-e3f1-e0a7-7373-16ae150a0de8
* Content: [Variance in Delegates (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I understand wanting to know answers to these kinds of "why" questions, but be aware that they can be really hard to answer. Unless I'm someone who was there when the feature was designed (I'm not), or unless I have access to notes of those who were there (for C#, [those only exist starting in 2013](https://github.com/dotnet/csharplang/tree/main/meetings)), all I can do is make more or less informed speculations.

So, here are my speculations on why variance in delegates requires explicit `in` and `out` keywords:

1. Clarity and explicitness. Variance behaves very similarly with delegates and with interfaces, so you want the syntax to be the same for both. But for interfaces (and to a lesser degree for delegates), you want to be able to easily tell if they are variant, without having to scan the whole type, to understand how you can use the type.
2. Performance. Type checks and conversions take longer for variant types (and the disparity used to be even larger in the past). So in performance-critical code, you don't want to have a type that's variant, without you explicitly choosing that.

Considering that introducing variance is just a few characters and it's not something that you do very often, I think the above reasons are sufficient justification for this design.

**Comment by BillWagner** [comment]
@NikVladi The comments by @svick are a good explanation for your question.

I'll close this as answered.
