### ISSUE TITLE
Please elaborate syntax

### ISSUE THREAD

**Issue by LukeOwlclaw** [dotnet/docs#25259]
The documentation shows how to correctly suppress a warning for a single member in a class, e.g. for `F` in following code it would be ``Scope = "member", Target = "~F:N.C.F"``:

    namespace N
    {
        class C
        {
            public int F;
            public int G;
        }
        class D
        {
            public int H;
            public int I;
        }
    }

But what do we need need to write if we want to suppress all warnings in whole `N`? (Legacy format which causes ``IDE0077`` would be `Scope = "namespaceanddescendants", Target = "N"`)

How to suppress all warnings in class `D`?

Please note that also the [documentation about "Target"](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.target?redirectedfrom=MSDN&view=net-5.0#System_Diagnostics_CodeAnalysis_SuppressMessageAttribute_Target) does not explain the syntax and also [StackOverflow has no answer](https://stackoverflow.com/questions/48922211/visual-studio-globalsuppressions-cs-prefix-p-for-attribute-target-in-suppres).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e02c18e2-a05a-a2f3-adcd-1ee8bfeb09c5
* Version Independent ID: f2cfe625-100a-bfb4-35c6-3ae0e52aab15
* Content: [IDE0077: Avoid legacy format target in global 'SuppressMessageAttribute' - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0077)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0077.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0077.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I'm not sure if there's a way to suppress a warning throughout a namespace using the Roslyn format. @mavasani?

But you can suppress all warnings in a class like this:

```
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Scope = "type", Target = "~T:N.C")]
```

The ID format for `Target` is documented here: https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/documentation-comments#id-string-format. I'll find a place to add that to the code analysis docs.

**Comment by mavasani** [comment]
namespaceanddescendants is not legacy format, it is supported in Roslyn.

**Comment by gewarren** [comment]
This worked for me to suppress the warning throughout the namespace:

```
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Scope = "namespaceanddescendants", Target = "~N:N")]
```

**Comment by LukeOwlclaw** [comment]
Thanks, got it! @gewarren's sample works great but please not that ``~N:`` is a fixed string, the following "N" is the placeholder for your real namespace, e.g.

    [assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Scope = "namespaceanddescendants", Target = "~N:MyName.MyProject.MyFolder")]

**Comment by LukeOwlclaw** [comment]
One more related question: Considering the [one letter prefix for `"Target"`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#id-string-format):

| Character  | Description  |
| -------- | -------------- |
| E |	Event |
| M	| Method (including constructors, destructors, and operators)                                                                                                                           |
| N	| Namespace                                                                                                                                                                             |
| P	| Property (including indexers)                                                                                                                                                         |
| T	| Type (such as class, delegate, enum, interface, and struct)                                                                                                                           |
| !	| Error string; the rest of the string provides information about the error. For example, the documentation generator generates error information for links that cannot be resolved.    |

Can `"E"`, `"T"`, and `"!"` also become relevant for suppression messages?

**Comment by gewarren** [comment]
I would guess that `!` is not relevant for suppression messages, but `E` and `T` are.
