### ISSUE TITLE
Visual Basic article about arrays contains incorrect examples.

### ISSUE THREAD

**Issue by Shawn1874** [dotnet/docs#2526]
# Issue Title

Visual Basic article about arrays contains incorrect examples.

# General

Incorrect example code needs to be replaced.

## Issues with Existing Topics
The article can be found at the following link.
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/

**Within the section, Storing Values in an Array, the examples do not show arrays.**  The example shows the use of a Dictionary which is a .Net collection type.  That doesn't demonstrate the concept of storing values within arrays.  The preceding paragraph implies that the example will demonstrate storing to an array using index values to elements.  Instead, the example shows the use of the add member of a List.  That's not the same thing.

**Within the section, Creating an Array, the examples show how to create and initialize the List collection type which is not an array.**  New examples should be made that show arrays.

I recommend reviewing the article and ensuring that the examples are applicable to the topic.  The List and Dictionary types are Generics within the .Net library and I don't believe that they are the same things as arrays.

**Comment by svick** [comment]
I think what happened is that some snippets from [the Collection Initializers article](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/collection-initializers/index) got written to the `arrays` directory, from which the Arrays article reads its snippets.

I think the fix would be to move the collection initializer snippets to the `collection-initializers` directory, fix the Collection Initializers article and then put the correct snippets into the `arrays` directory (they can be copied from [the older version of this article on MSDN](https://msdn.microsoft.com/library/wak0wfyt(v=vs.100).aspx)).

@Shawn1874 Do you want to create the PR to fix all this, or should I do it?

**Comment by Shawn1874** [comment]
If you could go ahead and do it I would appreciate it.  I'm fairly new at contributing, and I've only recently started learning visual basic so I don't completely understand what you mean by a PR.  I think you mean pull request right?  Perhaps the related pull request I submitted can be rejected, and then you can fix all three examples under this issue.

**Comment by svick** [comment]
> I'm fairly new at contributing, and I've only recently started learning visual basic so I don't completely understand what you mean by a PR. I think you mean pull request right?

Yeah, sorry, I did mean Pull Request. Sometimes it's hard for me to realize others don't know everything I do. 😄

> Perhaps the related pull request I submitted can be rejected, and then you can fix all three examples under this issue.

I just created https://github.com/dotnet/docs/pull/2533. You can either close your PR yourself or wait until someone from Microsoft comes along and does it (I can't do it, because I'm a contributor just like you).
