### ISSUE TITLE
Question on nested using blocks

### ISSUE THREAD

**Issue by mrj001** [dotnet/docs#25284]
I'm curious about how nested using blocks are implemented.  A single using block is equivalent of a try/finally with a call to Dispose.  For multiple disposable objects, we can amalgamate them into a single try/finally.  Do using blocks do the same?
```
using (var a = new A())
using (var b = new B())
  DoSomething(a, b);
```
Is the above equivalent to this:
```
A a;
B b;
try
   {
      a = new A();
      b = new B();
      DoSomething(a, b);
   }
finally
   {
      a?.Dispose();
      b?.Dispose();
   }
```
or to this?
```
A a;
try
   {
      a = new A();
      try
      {
         b = new B();
         DoSomething(a, b);
      }
      finally
      {
         b?.Dispose();
      }
   }
finally
   {
      a?.Dispose();
   }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This uses nested try/finally blocks. See [SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGMoBssQaqBAczgFsIA7GVCADwAcllkBLAewoBoATEAagA+AAQBMARgCwAKCEBmAASj5AYXkh5ASQAiLZPTbIowXNIDe0+ZcUKhYgGyKALPICyACgCUFq+alX/igAM8m4AboTyUPIAvPIUEADuKp5efgGWQsFhEcAxcYnJHqnp/rYAnG5QAHQAKmwAyjAILBREnvJ88sC1DU0tbUUA3N6WAL4j8hNyTvI6egYQnhO+JfIwABYIbEnxSQBybDAapPS45FQQ3ACitOgQ9DDsFJ7DaWPS0uNSQA) for what the compiler generates.

**Comment by adegeo** [comment]
You might want to try https://github.com/dotnet/csharplang/discussions to discuss what goes on behind the scenes. These issues are really for reporting doc bugs or doc enhancements 😁 

My guess would be that since they're nested, they're each declaring scope, so it's probably your 2nd try/finally example. I'll close this as off topic 😄

**Comment by mrj001** [comment]
@adegeo,  I thought it might be considered an enhancement since the documentation did not answer my question.
@Youssef1313, thanks for the pointer to that tool.

**Comment by adegeo** [comment]
@mrj001 I see that now. 😄 I'll ping @BillWagner to see if he thinks this is a good question to answer via the docs.
