### ISSUE TITLE
Update required for VS 2019

### ISSUE THREAD

**Issue by GuidoSE** [dotnet/docs#25296]
All the information detailed here is not available or visible in VS2019. To add a service using a wsdl defintion you cannot performed this through Connected Services as the OpenAPI does not support the operation. 

As for Add Service Reference tool. this is buggy, sometimes it works other times it does not, currently not working VS 2019 Pro Version 16.10.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Add WCF Web Service Reference - .NET](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/main/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dasetser
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hello @GuidoSE VS2019 doesn't include WCF by default. You'll need to add it via the Visual Studio Installer:

![image](https://user-images.githubusercontent.com/67293991/126675279-bb4c0b62-e351-40be-a8c9-2077ba0ce54a.png)

That probably adds the support for Connected Services and the project templates. Hopefully that solves your problem.

**Comment by GuidoSE** [comment]
Thank you all for replying but I'll explain what I required and how VS solves it, 

The project I have created is a full .NET framework project hence when I want to create a Connected Service e.g. SOAP service I should use the Add | Service References... process. Connected Services is not supported here, it is only available for .NET Core and .NET standard project where you get the WCF Service Reference Provider Tool (this may require adding to your project).

I hope this gives my previous comments context, I have a better understanding now.

Kind regards

**Comment by adegeo** [comment]
You're correct. This tool doesn't work in .NET Framework. This documentation set is for .NET/Core but not .NET Framework. There is an alert that kind of indicates that, specifying that you get this tool when you create a .NET Core/Standard project:

![image](https://user-images.githubusercontent.com/67293991/126683827-b0e4774e-3f0a-4b8e-add8-dbe69e44ec3d.png)

The existing .NET Framework WCF documentation is available here: https://docs.microsoft.com/dotnet/framework/wcf/

----

Related to MicrosoftDocs/visualstudio-docs/#6736

**Comment by adegeo** [comment]
@dasetser Are you still maintaining this documentation? If so, this probably needs an update for VS 2019 (and VS 2020 when it comes out) For VS 2019 I believe the WCF workload is required. Also, the templates have all changed names and dropped the **Core** part.

**Comment by dasetser** [comment]
@HongGit Can you help get this documentation updated?
