### ISSUE TITLE
Doc references a sample app that is hard to find or not linked

### ISSUE THREAD

**Issue by mdfrenchman** [dotnet/docs#25314]
The doc references a sample app, but I can't find it anywhere. A link either inline or somewhere in a high level callout would be useful.

> The sample app creates a field called _processingWorkScope (Internal/LoggerExtensions.cs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c051-c047-bbcd-5e25-ca6a722b51c3
* Version Independent ID: 3f5f1b6e-06ac-cc07-48cd-b8b957a4abbb
* Content: [High-performance logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging)
* Content Source: [docs/core/extensions/high-performance-logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/high-performance-logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @mdfrenchman 
Thank you so much for posting this issue. We really appreciate it. I'll add the sample to our [Samples Browser](https://docs.microsoft.com/en-us/samples/browse/) experience, and then update this doc.
