### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by PinkDuck** [dotnet/docs#25311]
Re: "If the literal is suffixed by U or u, its type is the first of the following types in which its value can be represented: uint, ulong."

This bullet point should end "uint, int", as 'ulong' literal suffix is case-insensitive UL or LU, and U or u results in 32-bit integer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a22464d-b60c-36c0-e4e8-b209a33b0219
* Version Independent ID: cb500323-82a3-09ea-0468-dd16c9e13675
* Content: [Integral numeric types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types)
* Content Source: [docs/csharp/language-reference/builtin-types/integral-numeric-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/integral-numeric-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The documentation is correct. A literal with the suffix `u` or `U` is indeed `uint` or `ulong`, depending on the value.

The following code:

```csharp
public class C
{
    public void M()
    {
        var x = 1u;
        var y = 10000000000u;
    }
}
```

... in debug mode, generates the following IL:

```il
.class private auto ansi '<Module>'
{
} // end of class <Module>

.class public auto ansi beforefieldinit C
    extends [System.Private.CoreLib]System.Object
{
    // Methods
    .method public hidebysig 
        instance void M () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 14 (0xe)
        .maxstack 1
        .locals init (
            [0] uint32 x, // NOTE this line and the next line.
            [1] uint64 y
        )

        IL_0000: nop
        IL_0001: ldc.i4.1
        IL_0002: stloc.0
        IL_0003: ldc.i8 10000000000
        IL_000c: stloc.1
        IL_000d: ret
    } // end of method C::M

    .method public hidebysig specialname rtspecialname 
        instance void .ctor () cil managed 
    {
        // Method begins at RVA 0x206a
        // Code size 8 (0x8)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: call instance void [System.Private.CoreLib]System.Object::.ctor()
        IL_0006: nop
        IL_0007: ret
    } // end of method C::.ctor

} // end of class C
```

See also the quick info provided in Visual Studio:

![image](https://user-images.githubusercontent.com/31348972/126786826-13ade3fc-c499-46fe-9779-ec3eb20c17ea.png)

![image](https://user-images.githubusercontent.com/31348972/126786744-117da6ea-4375-4d33-8c01-dcc821c6264b.png)
