### ISSUE TITLE
Confusing description about SOH and LOH

### ISSUE THREAD

**Issue by blaze6950** [dotnet/docs#25313]
In the article, the SOH is described that has 3 generations: 0, 1, and 2. Also, there mentioned that in SOH contains objects that are strictly less than 85,000 bytes in size. If an object is greater than or equal to 85,000 bytes in size, it’s considered a large object and is stored in the LOH.

BUT!

Further in the article exist such paragraph:

>Small objects are always allocated in generation 0 and, depending on their lifetime, may be promoted to generation 1 or generation2. Large objects are always allocated in generation 2.

What does it mean? Why in this paragraph mentioned that `Large objects are always allocated in generation 2`? At the beginning of the article slightly different information. Could someone explain this confusing information, pls?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819bcbc3-b2f7-b1eb-2e45-0f19c8da797c
* Version Independent ID: ed840139-0331-77b1-5645-0cac6c16edcf
* Content: [Large object heap (LOH) on Windows](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap)
* Content Source: [docs/standard/garbage-collection/large-object-heap.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/large-object-heap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The garbage collector as a whole has 3 generations, even though only one of those generations applies to the LOH, and those generations form a logical view only:

> Generations provide a logical view of the GC heap. Physically, objects live in managed heap segments.

What I think this means is that physically, large objects are in a separate segment to generation 2 small objects. But they're collected at the same time, so the "logical view" of calling them generation 2 objects still applies. @Maoni0 please correct me if I'm wrong.

**Comment by Maoni0** [comment]
you are exactly right, @gewarren. this is what I said in the [relevant section in mem-doc](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#loh-large-object-heap) and is basically what you said.

**Comment by blaze6950** [comment]
Thank you for the response! Could you confirm that this drawing correctly describes the situation, pls?


![image](https://user-images.githubusercontent.com/32897401/126867571-28524f21-2803-4bea-b2d8-8b8973805f60.png)

**Comment by Maoni0** [comment]
I'm not sure what that's supposed to illustrate. the physical representation is illustrated [here](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#physical-representation-of-the-gc-heap)

**Comment by blaze6950** [comment]
Thank you for the useful links! Now my understanding is clear. My drawing just illustrates the logical separation of GC on generations and which generations in SOH & LOH. I didn't reflect the real order of generations in memory. This is just a simplification for describing that LOH is part of the 2d gen.
