### ISSUE TITLE
Clarify the behavior of Encoding.Default in netcore

### ISSUE THREAD

**Issue by tarekgh** [dotnet/docs#2531]
On Windows desktop framework, Encoding.Default always get the system active code page and create Encoding object matching that code page. on net core Encoding.Default always return UTF8 encoding. it has been decided UTF8 is the default encoding that can be used in net core which will work across different OS's (Windows, Linux, OSX)

https://github.com/dotnet/corefx/issues/21701

cc @rpetrusha

**Comment by svick** [comment]
Related: https://github.com/dotnet/docs/issues/1837. It probably makes sense to fix both issues at the same time.

**Comment by rpetrusha** [comment]
This should have been closed automatically when the associated PR was merged, but it wasn't. Closing now...
