### ISSUE TITLE
It doesn't work even if I follow the description

### ISSUE THREAD

**Issue by t13801206** [dotnet/docs#25336]
**Issue description**

There is a problem with [this page](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-value-precedence?view=netframeworkdesktop-4.8#dependency-properties-might-be-set-in-multiple-places).
>If you removed the local value of Red from that Button instance, then the style would have precedence and the button would obtain the Background value from the style. Within the style, triggers take precedence, **so the button will be blue if the mouse is over it**, and green otherwise.

I removed the local value of Red from that Button instance.
When I hover my mouse over the button, **the button doesn't turn blue**.
I think it's because the default style has been adapted.

```xml
<!--<Button Background="Red">-->
<Button> 
      <Button.Style>
        <Style TargetType="{x:Type Button}">
          <Setter Property="Background" Value="Green"/>
          <Style.Triggers>
            <Trigger Property="IsMouseOver" Value="True">
              <Setter Property="Background" Value="Blue" />
            </Trigger>
          </Style.Triggers>
        </Style>
      </Button.Style>
Click
    </Button>
```

You need to add this code between Style tag.

```xml
<Setter Property="Template">
    <Setter.Value>
        <ControlTemplate TargetType="{x:Type Button}">
            <Border Background="{TemplateBinding Background}">
                <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center" />
            </Border>
        </ControlTemplate>
    </Setter.Value>
</Setter>
```

Thank you.

**Target framework**

- [ ] .NET Core
- [x] .NET Framework (I tried with 4.7.2)
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>
 Version:   5.0.301
 Commit:    ef17233f86

 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

```console
<replace>
```
</details>

[Edited to add doc details.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6e8d59-9687-3d38-eb8c-8bfffe282505
* Version Independent ID: dc70ea0e-6353-986f-ad17-3ccc3226c690
* Content: [Dependency Property Value Precedence - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-value-precedence?view=netframeworkdesktop-4.8#dependency-properties-might-be-set-in-multiple-places)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/dependency-property-value-precedence.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/dependency-property-value-precedence.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@adegeo Can you transfer this issue to dotnet/desktop?

**Comment by adegeo** [comment]
I don't know why the desktop repo won't show up in the transfer dialog. I'm contacting github support to hopefully fix this.

**Comment by adegeo** [comment]
This issue was moved to dotnet/docs-desktop#1154
