### ISSUE TITLE
CLRCreateInstance on Linux

### ISSUE THREAD

**Issue by ivo-stoilov** [dotnet/docs#25356]
Hello,

I am trying to find a way to use this feature on Linux, please provide a working sample on how it can be achieved. Thanks in advance! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6b076e-e0c1-0105-8e2c-acdbf47b1c60
* Version Independent ID: f92d17a5-f192-b865-fec5-b075fd85c664
* Content: [CLRCreateInstance Function](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/clrcreateinstance-function)
* Content Source: [docs/framework/unmanaged-api/hosting/clrcreateinstance-function.md](https://github.com/dotnet/docs/blob/main/docs/framework/unmanaged-api/hosting/clrcreateinstance-function.md)
* Product: **dotnet-framework**
* GitHub Login: @jeffschwMSFT
* Microsoft Alias: **jeffschw**

**Comment by jeffschwMSFT** [comment]
These are the docs you are looking for.

https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting
https://github.com/dotnet/samples/tree/main/core/hosting

.NET Framework does not support Linux.

**Comment by ivo-stoilov** [comment]
Hello @jeffschwMSFT, thanks for the information provided. I am perfectly aware that .NET Framework does not support other platforms than Windows, but my intention is to gain knowledge on how can I use the corresponding API's on .NET Core on Linux.  More specifically I am interested in which headers and libraries I have to use, a minimal sample like the one for Windows would be a great starting point for me.

**Comment by jeffschwMSFT** [comment]
@ivo-stoilov do you have what you need with the links that I shared above?  The samples are cross platform and include details about the headers and libs required.

**Comment by ivo-stoilov** [comment]
@jeffschwMSFT, unfortunately not. The samples demonstrate some basics of the unmanaged API, namely how to host and call managed code, but nothing about that I am looking for.

Let me try to be more concrete, I need to use StrongNames APIs, currently, I am using them for Windows without any issues in the following way:

```
CComPtr<ICLRMetaHost> metaHost;
HRESULT hr = CLRCreateInstance(CLSID_CLRMetaHost, IID_ICLRMetaHost, &metaHost);
if (SUCCEEDED(hr))
{
	CComPtr<ICLRRuntimeInfo> runtimeInfo;
	hr = pMetaHost->GetRuntime(WSTR("v4.0.30319"), IID_ICLRRuntimeInfo, &runtimeInfo);
	if (SUCCEEDED(hr))
	{
		CComPtr<ICLRStrongName> strongName;
		hr = runtimeInfo->GetInterface(CLSID_CLRStrongName, IID_ICLRStrongName, &strongName);
		
		// Use ICLRStrongName interface...
	}
}
```

I suppose that the code can be used as it, but I am unable to find the right library to link with, there is nothing similar to **mscoree.lib** on Linux. Please advise.

**Comment by jeffschwMSFT** [comment]
We do not have an equivalent on .NET Core for the strong name apis.  What is the scenario that you are looking to enable?

cc @agocke

**Comment by ivo-stoilov** [comment]
I am using just one of the StronNames APIs, StrongNameTokenFromPublicKey. As far as I know, it has a deprecated global function variant that was used in the past.

**Comment by jeffschwMSFT** [comment]
What do you use the output from StrongNameTokenFromPublicKey to do?  Are you using in an app at runtime or is this a tool?

**Comment by ivo-stoilov** [comment]
I am unable to disclose all details, but generally, this function is used inside a CLR profiler for the purpose of type resolution at runtime. I am trying to migrate the existing functionality currently working for both .NET Framework and .NET Core to other platforms than Windows and I am blocked with this problem.

**Comment by jeffschwMSFT** [comment]
I would recommend moving most of the type resolution logic to managed code.  The same code can run on both .NET Framework and .NET Core.  The only difference would then be how to run the code from the native host.

**Comment by ivo-stoilov** [comment]
Hello @jeffschwMSFT, thanks for your suggestion, but I am afraid that it would not help. Profilers are native components, they interact with CLR via unmanaged API, using managed code, in this case, would be a kind of overkill. I have found that desired APIs are exported from the shared library **libdbgshim.so**. There is only one major issue, it is not loaded by default which requires some explicit action, options are: configure the dynamic loader (via LD_LIBRARY_PATH) with the directory path where the shared object resides or load it programmatically (via dlopen). In my opinion, the second option seems to be more appropriate in our case, but the main difficulty here is how to determine the path to the directory of the currently used runtime? That is what I am currently stuck with.

**Comment by ivo-stoilov** [comment]
Hello @jeffschwMSFT, did you have a chance to look at the problem raised with my last comment? Please, provide your comments on whether the approach that I am going to use is generally correct.

**Comment by jeffschwMSFT** [comment]
Adding @tommcdon for that library.  I am not aware of any public surface area exposed by dbgshim as such you are taking a dependency on an internal detail.

**Comment by tommcdon** [comment]
The [CLRCreateInstance](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/dlls/dbgshim/dbgshim.cpp#L1976) export on dbgshim is intended for attaining an [ICLRDebugging](https://docs.microsoft.com/dotnet/framework/unmanaged-api/debugging/iclrdebugging-interface) interface for debugging purposes.  Adding @davmason who might be able to provide guidance on accessing StrongName API's from profilers.

**Comment by davmason** [comment]
If you are trying to find out the directory of the runtime I have written some code in the profiler tests that do that: https://github.com/dotnet/runtime/blob/aff3362fd7743753b6e86a77d6f934e7a7185bc1/src/tests/profiler/native/metadatagetdispenser/metadatagetdispenser.cpp#L130-L250

Another idea is that StrongNameTokenFromPublicKey is still in coreclr, it's just not exported anymore. The [implementation](https://github.com/dotnet/runtime/blob/aff3362fd7743753b6e86a77d6f934e7a7185bc1/src/coreclr/md/runtime/strongnameinternal.cpp#L228-L333) doesn't look like that much code, it should be possible to duplicate the logic in your profiler

**Comment by ivo-stoilov** [comment]
Hello @davmason, sorry for this late reply. I will consider all options and come back with the selected approach, it could be of help to someone having the same issue.

**Comment by ivo-stoilov** [comment]
Hello @davmason, finally we have decided to go with a simplified version of the StrongNameTokenFromPublicKey function based on the original implementation existing in the CLR. As you mentioned the code is not that much (actually involves also a small SHA1 hasher and a few helpers) and now it works as expected. Many thanks to all of you!

**Comment by davmason** [comment]
Thanks for following up, I'm glad it worked.
