### ISSUE TITLE
VS 2022: Contract.Requires does nothing

### ISSUE THREAD

**Issue by Turochamp** [dotnet/docs#25355]
I'm experiencing that Contract.Requires does not do anything, even when condition clearly is false. This is similar to what's described here:
https://stackoverflow.com/questions/8300815/contract-requires-usage

Using Visual Studio 2022, building to net5.0/netstandard2.1 and have installed the [Code Contract](https://marketplace.visualstudio.com/items?itemName=RiSEResearchinSoftwareEngineering.CodeContractsforNET) component.

Is this supposed to work? If so is there a log, or similar, that can be used for diagnosis?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92c6e0f-2503-fe90-2b96-3b0c2054e8dc
* Version Independent ID: 5612b486-e780-7625-12fb-f5478f1be7de
* Content: [Code Contracts](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/code-contracts)
* Content Source: [docs/framework/debug-trace-profile/code-contracts.md](https://github.com/dotnet/docs/blob/main/docs/framework/debug-trace-profile/code-contracts.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Turochamp** [comment]
@SergeyTeplyakov
Do you have any insights on this question of mine?

https://github.com/microsoft/CodeContracts/graphs/contributors

**Comment by gewarren** [comment]
@tommcdon Could you help with this question?

**Comment by SergeyTeplyakov** [comment]
All the methods in `Contract` class are just annotations that should be analyzed by some other tools, like `ccrewrite` or `cccheck`. For instance, `ccrewrite` tool will open the assembly with `Contract.Requies` and other invocations and based on the settings will re-write the IL to do something (based on the settings as well). 

Usually, ccrewrite will change all the assertions to `if (!condition) {throw new ContractException("message")}`.

The thing is that the toolchain is no longer supported and afaik the last VS version that supported the contracts was VS2017.

Another thing to keep in mind: the tool chain never worked with .net core and as far as I know there are no teams that owns this product anymore so I would not expect any changes in the near future.

**Comment by Turochamp** [comment]
Thanks @SergeyTeplyakov!
That's too bad, I really like that style of coding. My further investigation though shows that the new [nullable-references](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) will solve the majority of my needs, which is references incorrectly being null.

Hi @gewarren @tommcdon, 
Regarding the docs, for me it was quite easy to miss a) that it only applies for .NET Framework (there is information to the side, but not the main text) and b) Code Contracts have been replaced with Roslyn Analysers, and/or C#8's Nullable Reference Types. So suggest updating it. Here is a [github link with relevant comments](https://github.com/dotnet/runtime/issues/23869).
