### ISSUE TITLE
MacOS and Linux uninstall instructions need updates for .NET 6

### ISSUE THREAD

**Issue by tillig** [dotnet/docs#25358]
The `dotnet-core-uninstall` tool, the easiest mechanism for removing SDKs or runtimes on MacOS and Linux, does not support .NET 6. The instructions that are there for MacOS...

```sh
version="1.0.1"
sudo rm -rf /usr/local/share/dotnet/sdk/$version
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.NETCore.App/$version
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.All/$version
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/$version
sudo rm -rf /usr/local/share/dotnet/host/fxr/$version
```

...don't actually work for later SDKs and runtimes because there isn't one folder per version in these locations anymore. You have to specifically delete a targeted version in these locations which may not all be the same value. Doing what the instructions say here for, say, .NET 6, is going to cause errors and be confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tillig** [comment]
Corrected the issue title/description. For some reason clicking MacOS on the selector on the page didn't show the MacOS instructions when I was reading the first time. Once I saw them and started following them, I noticed they don't actually work for later SDKs/runtimes.

**Comment by adegeo** [comment]
Hello. Sorry you're having an issue with uninstall. How did you install the 6.0 preview and where did you install it?

**Comment by tillig** [comment]
I was able to install it by going to [the .NET SDK download page for 6.0](https://dotnet.microsoft.com/download/dotnet/6.0) and getting the latest preview of .NET 6 for MacOS.

Once it's installed (alongside other SDKs and runtimes) my folders look like this:

```text
/usr/local/share/dotnet/
+-sdk/
  +-2.1.816/
  +-3.1.411/
  +-5.0.301/
  +-6.0.100-preview.6.21355.2/  
+-shared/
  +-Microsoft.NETCore.App/
    +-2.1.28/
    +-3.1.17/
    +-5.0.7/
    +-6.0.0-preview.6.21352.12/
  +-Microsoft.AspNetCore.All/
    +-2.1.28/
  +-Microsoft.AspNetCore.App/
    +-2.1.28/
    +-3.1.17/
    +-5.0.7/
    +-6.0.0-preview.6.21355.2/
+-host/
  +-fxr/
    +-2.1.28/
    +-3.1.17/
    +-5.0.7/
    +-6.0.0-preview.6.21352.12/
```

As you can see, if I followed the instructions to uninstall by setting a single version at the top, that wouldn't work. The SDK + runtimes + host versions don't actually all "line up" like that.

For versions _less than_ 6, the `dotnet-core-uninstall` tool handles figuring this all out. However, it doesn't support .NET 6 and the manual instructions don't work for later versions of .NET Core. I think you probably need to treat the SDK and runtime folders separately (maybe explain that in the docs?). I don't really even know what `host/fxr/` is so maybe that, too, should be explained.

**Comment by adegeo** [comment]
Ahh OK thank you for sharing that information. I'm going to leave this issue open and retitle it about upgrading the documentation for .NET 6. Regarding the uninstall tool, you'll need to ask in the github repo, though they don't seem too active :( Here is the repo: https://github.com/dotnet/cli-lab

**Comment by adegeo** [comment]
@leecow Do you know what the uninstall story is for .NET 6?

**Comment by tillig** [comment]
https://github.com/dotnet/cli-lab/issues/189
It appears they'll support .NET 6 closer to the GA, but in the meantime folks are just... stuck.

**Comment by leecow** [comment]
@KathleenDollard @marcpopMSFT as this tool is (I believe) owned by the SDK folks.

**Comment by marcpopMSFT** [comment]
@sfoslund for updating the uninstall tool to support 6.0

**Comment by sfoslund** [comment]
The uninstall tool has been updated to support 6.0 in the latest release, which can be found here: https://github.com/dotnet/cli-lab/releases/tag/1.3.245803
