### ISSUE TITLE
DetectPeriod method code should return the period value

### ISSUE THREAD

**Issue by or185014** [dotnet/docs#25363]
The code in the [Create the DetectPeriod method](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/phone-calls-anomaly-detection#create-the-detectperiod-method) section has a bug. The method `DetectPeriod` should have a return type of `int` and should return the period value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6266e1-f8e5-d303-7ddc-be2d6e47f831
* Version Independent ID: 2ae35df3-cf3a-ed1c-b466-a8be8a9729c3
* Content: [Tutorial: Detect anomalies in phone calls - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/phone-calls-anomaly-detection)
* Content Source: [docs/machine-learning/tutorials/phone-calls-anomaly-detection.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/phone-calls-anomaly-detection.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @or185014 

Thanks for pointing that out. We'll review the sample and make the changes to get this working.
