### ISSUE TITLE
Guidance on using Microsoft or System namespaces to hold my code

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#25368]
Should I ever consider putting my applications or libraries types, constants, or extension methods inside a namespace that starts with "Microsoft" or "System"?

If so, what are the scenarios and benefits of doing so?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0280f9-e122-a229-2caa-31038fa2420f
* Version Independent ID: 15793662-cb17-e8f9-23e8-373a593b7c87
* Content: [Using Namespaces - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/using-namespaces)
* Content Source: [docs/csharp/programming-guide/namespaces/using-namespaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/namespaces/using-namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
We already have guidance on this things:

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces

I think generally speaking, you'd never want to use either of them unless you're contributing to the runtime repos.

**Comment by StingyJack** [comment]
@IEvangelist  Thanks, that makes sense to me. I'm getting conflicting and confusing advice [from another docs page](https://github.com/dotnet/AspNetCore.Docs/issues/22862#issuecomment-890373741).  It took a few clarification requests,  but I finally was able to get to the root reason for the conflicting guidance.  There may be something you all want to work out internally, or at least make sure that page gets updated appropriately.
