### ISSUE TITLE
CA2227 - init-only violation fix does not remove warning from VS

### ISSUE THREAD

**Issue by Andy-DFN** [dotnet/docs#25371]
Hi there,

As per the document for rule CA2227:
https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2227

It states that to fix the violation that you can change your collections to init-only to fix the rule. However, I have made this change to a couple of my collections in the code and the warning is still present.

Is this an issue with the documentation? Or an issue in Visual Studio itself?

Kind Regards,
Andy White

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019358db-ee31-4b85-6592-f64f54650eac
* Version Independent ID: e177c090-6e1a-5e61-a130-4432f335e8a5
* Content: [CA2227: Collection properties should be read only (code analysis) - .NET](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2227)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2227.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2227.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
The documentation is correct. The rule was updated in https://github.com/dotnet/roslyn-analyzers/pull/4463. It's possible you're using a version that doesn't contain this fix. Can you try the [latest prerelease](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet)?

**Comment by Andy-DFN** [comment]
Hi there,

Thank you for your response.

I removed the roslyn nuget packages and switched to the .Net SDK code analyzers as with what is provided with .Net 5. This has removed the warning for CA227.
