### ISSUE TITLE
How to deserialize nested/deeply-nested Json using one class

### ISSUE THREAD

**Issue by jamjchai** [dotnet/docs#25388]
Instructions on how to deserialize nested Json would improve this article. Such as in one example already in the article under the heading, "How to read JSON as .NET objects (deserialize)", show how to get at High and Low Hot TemperatureRanges.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@jamjchai Thanks for the suggestion.  I'm adding links to the article that has that information.
