### ISSUE TITLE
Clarify Ubuntu 20.04 support

### ISSUE THREAD

**Issue by michac** [dotnet/docs#25382]
The table at the top of the page says 20.04 is supported and 20.10 is not, while the nav on the right and the content says 20.10 is supported and 20.04 is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for bringing this up. It looks like I marked the wrong header as not supported!

**Comment by alyssajotice** [comment]
> Thank you for bringing this up. It looks like I marked the wrong header as not supported!

@adegeo can you please clarify which is supported and which is not?

**Comment by adegeo** [comment]
@alyssajotice Hiya! We only support .NET on versions in Ubuntu's support policy. As of July, 20.10. We've corrected the article today but our publishing cycle is generally the morning of the next day.

**Comment by alyssajotice** [comment]
@adegeo, thank you for the clarification.

**Comment by adegeo** [comment]
@alyssajotice 
That said, .NET will probably still work just fine if you choose to run it on it. Obviously .NET 5 (which has been released for quite a while) will continue to run on Ubuntu 20.10, we just don't guarantee that .NET 6 will as we're not going to be testing it on an unsupported Ubuntu release.
