### ISSUE TITLE
Best practice of when to use module initializer vs. static constructor

### ISSUE THREAD

**Issue by onionhammer** [dotnet/docs#25394]
It would be great to have some guidance on when to use a static constructor and when to use a module initializer. It seems that assigning a variable in the initializer does not inform the nullability check that the value is set, so you would get a warning for the module initializer where you wouldn't with a static constructor, also you cannot assign readonly fields

![image](https://user-images.githubusercontent.com/969938/127506140-a5ad0f87-424e-443f-89f8-0f58b90527d5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3ed1c5-1f79-9234-beec-b5771c3fb3c0
* Version Independent ID: ac4f6361-70a7-fb43-101e-c12044f60896
* Content: [Static Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/static-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I'd say that module initializers are an advanced feature and that static constructors should be used most of the time for this kind of initialization.

That means that I think it's fine that the documentation for static constructors does not mention module initializers (though a link could be included in *See also*). But the documentation for module initializers (which currently doesn't exist, but should) could mention this.

**Comment by BillWagner** [comment]
I like @svick's suggestion.  

There is language reference documentation for the `ModuleInitialzer` attribute [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/general#moduleinitializer-attribute). That's where a link to static constructors should be added.

**Comment by svick** [comment]
@BillWagner The part I was missing was being able to find that documentation in the first place. When I search for "module initializer" [on Google](https://www.google.com/search?q=module+initializer+c%23), or [on Docs](https://docs.microsoft.com/en-us/search/?terms=module%20initializer&scope=.NET), I see the specification proposal, but not the section you linked to. But I'm not sure how to fix that SEO problem.

**Comment by BillWagner** [comment]
Per above comment, while fixing this we should add a `displayName` property to the referenced article for "ModuleInitializer", and look for ways to improve SEO for this article.
