### ISSUE TITLE
Task asynchronous programming model

### ISSUE THREAD

**Issue by karishmakarnwal11** [dotnet/docs#25393]
Loved the way the title has been explained. Examples and concepts were precise and particular that delivered the right content and deep knowledge with an improved understanding of the topic. Know much more about async and await keywords now. Excited to implement asynchronous programming in my next project. Great job! Very well-written article. Must read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd97c63-2887-1891-fb08-9cd78659c2db
* Version Independent ID: 1ae4494a-ca0b-a1da-cdcf-522ef79e0fc5
* Content: [The Task Asynchronous Programming (TAP) model with async and await (C#)'](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model)
* Content Source: [docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for leaving such detailed feedback @karishmakarnwal11 We appreciate it.

Closing as kudos.
