### ISSUE TITLE
Misleading statement in the Configuration Providers doc

### ISSUE THREAD

**Issue by a510** [dotnet/docs#25409]
Why the documentation says that 

> The JSON settings are overridden by settings in the Environment variables configuration provider and the Command-line configuration provider.

where we already removed all other configuration providers (or sources?) earlier in the code ?

``` csharp
configuration.Sources.Clear();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c11507-cd06-292f-53bc-3a7f14affd86
* Version Independent ID: 33eb4890-44e0-522b-b1c1-964fec385b6a
* Content: [Configuration providers in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers)
* Content Source: [docs/core/extensions/configuration-providers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration-providers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @a510, this information is a bit misleading - I agree. But it's still accurate. The code example clears out all the config providers, but there still is an order of precedence that is important to communicate. I'll clarify that a bit, thanks.
