### ISSUE TITLE
Unbulleted lists

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2540]
I think there are several cases in docs that are semantically lists (possibly nested lists), but shouldn't be displayed as normal Markdown lists (with bullets), so their appearance is maintained manually (often using a generous helping of `&nbsp;`s).

These include:

* See also sections at the end of articles.
* Directory listings (e.g. [here](https://github.com/GuardRex/docs-1/blob/ea66eb3ffe9186d1ecc66ffc2cba3bf54357cc74/docs/core/deploying/runtime-package-store.md)).
* WCF configuration elements hierarchy (e.g. [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/servicediscovery), currently not indented properly).

Would it be worth trying to come up with markdown for those?

I was thinking that this could be done by specifying a custom class for such a list. As far as I can tell, this can be done in DocFX flavored Markdown using `> [!div]`. So, for example, the WCF example would look like this:

```md
> [!div class="unbulleted-list"]
> * \<system.ServiceModel>
>   * \<behaviors>
>     * \<serviceBehaviors>
>       * \<behavior>
>         * \<serviceDiscovery>
```

With a custom style of (I don't know CSS, so this might not be the right way to do it):

```css
.unbulleted-list ul
{ 
    list-style-type: none;
    padding-left: 0;
}

.unbulleted-list ul ul
{ 
    padding-left: 1em;
}
```

This renders as:

![](https://user-images.githubusercontent.com/287848/27771867-cdc53a38-5f57-11e7-9d1e-25bc34720bea.png)

Would this be useful at all? Is the syntax acceptable? Or am I trying to solve a problem that does not exist?

cc: @GuardRex

**Comment by GuardRex** [comment]
> using a generous helping of `&nbsp;`s

Truly so! :+1: :smile: I think it looks sooooo much better rendered this way under certain circumstances (i.e., *not* in a code block ... yuck!). Yes, as you say, non-breaking spaces aren't the proper way to achieve this rendering. Ugh ... we *hacked it!* lol

> solve a problem that does not exist

IMHO, it's a problem in spots.

* See also sections at the end of articles.

   We have a plan: No bullets and no line spaces between *See also* links. [@]rpetrusha explained how to make it work by placing three spaces at the end of each line (each link). If the three spaces aren't there, the links pile up on the same line. I don't think this will require any changes.

* Directory listings

   *Yes, please. Not a code block, please.*

* WCF configuration elements hierarchy

   *Yes, please. Not a code block, please.* It matches the MSDN way. Looks nice imo.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/221
