### ISSUE TITLE
Attributes extend type annotations – bad definition, bad article name

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25419]
From [Attributes extend type annotations](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#attributes-extend-type-annotations)

>  Reference types should never be the null value, and nullable reference types must be checked against null before being dereferenced.

It is not true that `nullable annotated` `reference types` have to be checked before dereference. That is true only for those in `maybe null` state. 

“_…and nullable reference types must be checked against `null` when it is not know whether they are not `null` before being dereferenced._” or similar is more exact.

---

> The attributes that describe the semantics of your API are found in the article on Attributes that impact nullable analysis.

Article under link _Attributes that impact nullable analysis_ has slightly different title – [_Attributes for null-state static analysis_](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc516159-d7e1-46ba-7d31-538a0b811491
* Version Independent ID: 99552131-8839-7c22-fcdc-2baa7722e756
* Content: [Update your codebase to use nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#generic-definitions-and-nullability)
* Content Source: [docs/csharp/nullable-migration-strategies.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-migration-strategies.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Fixed in #26046
