### ISSUE TITLE
Not so much useful

### ISSUE THREAD

**Issue by proganis** [dotnet/docs#25414]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62af3ec3-7d59-7b4a-b9a1-413b8956bab7
* Version Independent ID: 31e0311a-8823-1d30-8f38-ac0c37ca07d9
* Content: [NETSDK1004: Assets file not found - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1004?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1004)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1004.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1004.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
What can we add that would make it more useful?
