### ISSUE TITLE
Should nullable warnings introduce breaking changes? – `?` annotation does not change signature

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25418]
From [Should nullable warnings introduce breaking changes?](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#should-nullable-warnings-introduce-breaking-changes)

> Do you want to consider modifying API signatures to more clearly communicate your design intent? A better API signature for the TryGetMessage method examined earlier could be:

>In many cases, changing API signatures can improve how they communicate null values.

>However, for public libraries, or libraries with large user bases, you may prefer not introducing any API signature changes.

#### Let dig into it
For instance, taken from [Inherited and overridden methods](https://docs.microsoft.com/en-us/dotnet/csharp/methods#inherited-and-overridden-methods)

> The method signature must be the same as that of the overridden method.

Sample

```c#
class Base
{
  protected virtual void NullableReferenceParameterInBase ( object? a ) { }
  protected virtual void ReferenceParameterBase ( object a ) { }
}

class Derived : Base
{
  protected override void NullableReferenceParameterInBase ( object a ) { }  
  protected override void ReferenceParameterBase ( object? a ) { }
}
```

compiles without any `error`. There’s only `warning` for `protected override void NullableReferenceParameterInBase ( object a ) { }` – `Warning CS8765 Nullability of type of parameter 'a' doesn't match overridden member (possibly because of nullability attributes).`.

See also https://github.com/dotnet/docs/issues/25211.

---

I guess correct term is not signature but declaration. On the other hand I can be wrong.

From [Method signatures](https://docs.microsoft.com/en-us/dotnet/csharp/methods#method-signatures)

> A return type of a method is not part of the signature of the method for the purposes of method overloading. However, it is part of the signature of the method when determining the compatibility between a delegate and the method that it points to.

Thus it seems not so unlikely that `reference type` `nullable annotation` becomes part of method signature for `null` state `static analysis`.

FMPOV `nullable annotation` does not change method signature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc516159-d7e1-46ba-7d31-538a0b811491
* Version Independent ID: 99552131-8839-7c22-fcdc-2baa7722e756
* Content: [Update your codebase to use nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#generic-definitions-and-nullability)
* Content Source: [docs/csharp/nullable-migration-strategies.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-migration-strategies.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
As I understand it, that section talks about changing "the `TryGetMessage` method examined earlier" from:

```c#
bool TryGetMessage(string key, out string message)
```

To:

```c#
string? TryGetMessage(string key);
```

This would be a breaking change.

But I think the article is not very clear that this is what it is talking about, so that could be improved.

**Comment by Uzivatel919** [comment]
@svick, good catch. I even did not considered `string? TryGetMessage(string key);` as I strongly exptected there is `bool TryGetMessage(string key, out string? message)` or bool TryGetMessage(string key, [NotNullWhen(true)] out string message)`.

Next sentence after sample is 

>The return value indicates success or failure, and carries the value if the value was found.

thus considering it wrong is right choice.
