### ISSUE TITLE
Update libraries to use nullable reference types and communicate nullable rules to callers – *null state* does not exists

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25416]
From [Update libraries to use nullable reference types and communicate nullable rules to callers](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies)

> If the `TryGetMessage` method returns `true`, the value of `message` isn't null. If the return value is `false`, the value of `message` (and its null state) is null.

Let focus on parenthesized phrase “_(and its null state)_”.

From [Nullable references and static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types#nullable-references-and-static-analysis)

> In a nullable enabled context, the compiler performs static analysis on variables of any reference type, both nullable and non-nullable. The compiler tracks the null state of each reference variable as either _not null_ or _maybe null_. 

Thus there is no _null state_ . Exist only `maybe null` and `not null`.

For another reference see https://github.com/dotnet/roslyn/issues/55110#issuecomment-886302535

>To fix this, we would probably have to introduce something like "definitely null" flow state in addition to the existing "maybe null" and "not null" flow states. 

I believe that “_(and its null state)_” is there by accident. That since whole paragraph states common expected situation regardless `nullable context` state (on, off, …).

The same wording can be found at [Attributes for null-state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#preconditions-allownull-and-disallownull).

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc516159-d7e1-46ba-7d31-538a0b811491
* Version Independent ID: 99552131-8839-7c22-fcdc-2baa7722e756
* Content: [Update your codebase to use nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#generic-definitions-and-nullability)
* Content Source: [docs/csharp/nullable-migration-strategies.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-migration-strategies.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Fixed in #26046
