### ISSUE TITLE
Warnings help discover original design intent – backhanded null states guarantees 

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25421]
From [Warnings help discover original design intent](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references#warnings-help-discover-original-design-intent)

> There's quite a bit going on in the preceding block of code. This application uses the [AutoMapper](https://automapper.org/) NuGet package to construct a news item from an `ISyndicationItem`. You've discovered that the news story items are constructed and the properties are set in that one statement. That means the design for the `NewsStoryViewModel` indicates that these properties should never have the `null` value. These properties should be **nonnullable reference types**. That best expresses the original design intent. In fact, any `NewsStoryViewModel` is correctly instantiated with non-null values. That makes the following initialization code a valid fix:

This paragraph is particularly weird:

1. Common practice is to validate input parameters all the time. No matter _Automapper_ takes its part in processing inputs from `RssFeedReader`/`ISyndicationItem` no code or textual description expresses guarantees about values stored in `ISyndicationItem`. Even if [RSS 2.0 `<title>` element](https://validator.w3.org/feed/docs/rss2.html) is `required`, it is not obvious why `ISyndicationItem.Title` must have value. Original design is in this case wrong.

2. If something **should** not have `null` value, it does not mean it **could not** have or **does not**. When it **should not**, it is likely `nullable annotated reference type` with some attributes further specifying `null state` circumstances. 

> That means the design for the `NewsStoryViewModel` indicates that these properties should never have the `null` value. These properties should be **nonnullable reference types**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313ec178-bb7c-e6be-0760-f7db427b464c
* Version Independent ID: ac631425-4ff7-850c-9fa7-127ff7a9ac06
* Content: [Upgrade to nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references)
* Content Source: [docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Fixed in #26046
