### ISSUE TITLE
Tutorial: Migrate existing code with nullable reference types – terminology

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25420]
From [Tutorial: Migrate existing code with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references)

>C# 8 introduces **nullable reference types**, which complement reference types the same way nullable value types complement value types. You declare a variable to be a **nullable reference type** by appending a `?` to the type. For example, `string?` represents a nullable `string`. You can use these new types to more clearly express your design intent: some variables _must always have a value_, others _may be missing a value_. Any existing variables of a reference type would be interpreted as a non-nullable reference type.

Every time I pass through some documentation on `nullable reference types` I hit some bewildering connotation:

1. Term `nullable reference type` appears more as some new feature of reference types than some terse technical name. FMPOV, `nullable reference type` is shorthand for `nullable annotated reference type` but throughout the documentation `nullable reference type` (exactly `nullable annotated reference type`) is presented as some new kind of type. 

> You can use these new types to more clearly express your design intent:

Further in article it is stated 

> These two properties cause `CS8618`, "Non-nullable property is uninitialized". That's clear enough: both `string` properties have the default value of `null` when a `NewsStoryViewModel` is constructed. 

It is obvious that even `non-nullable` (`annotated`) `reference type` can be of `null` value.

I have some doubts if such explanations/expositions can be ever healthy for .NET documentation.

2. Statement
> C# 8 introduces **nullable reference types**, which complement reference types the same way nullable value types complement value types. 

is rather questionable. In fact for `value type` it was impossible to be of `null` value before NVT. For `reference type` nothing changed regard its ability to be of `null` value when NRT were introduced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313ec178-bb7c-e6be-0760-f7db427b464c
* Version Independent ID: ac631425-4ff7-850c-9fa7-127ff7a9ac06
* Content: [Upgrade to nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references)
* Content Source: [docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Uzivatel919** [comment]
Ad) 1. Same introduction has [Tutorial: Express your design intent more clearly with nullable and non-nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types).

**Comment by BillWagner** [comment]
Fixed in #26046
