### ISSUE TITLE
Adding a summary table for Access Modifiers

### ISSUE THREAD

**Issue by DecimalTurn** [dotnet/docs#25424]
I was thinking it would be nice to have a summary table for [this article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers) to make it more visual. 
But before opening a pull request, I just wanted to make sure that I'm not the only one who thinks that and make sure there are no mistakes in the table.

Here's what I had in mind :

Caller's location   ↓ | public | protected | internal | protected internal | private | private protected
-- | -- | -- | -- | -- | -- | --
**<ins>Within the assembly</ins>** |   |   |   |   |   |  
Within the class | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
Non-derived class | ✔ | ❌ | ✔ | ✔ | ❌ | ❌
Derived class | ✔ | ✔ | ✔ | ✔ | ❌ | ✔
**<ins>In an external assembly</ins>** |   |   |   |   |   |  
Non-derived class | ✔ | ❌ | ❌ | ❌ | ❌ | ❌
Derived class | ✔ | ✔ | ❌ | ✔ | ❌ | ❌

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I like this suggestion @DecimalTurn I'll look for a PR.

I do have one suggestion that I think will make it visually more understandable: I'd rearrange the columns as follows:

Caller's location   ↓ | public | protected internal | protected | internal | private protected | private 
-- | -- | -- | -- | -- | -- | --
**<ins>Within the assembly</ins>** |   |   |   |   |   |  
Within the class     | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
Non-derived class | ✔ | ✔ | ✔ | ❌ | ❌ | ❌
Derived class         | ✔ | ✔ | ✔ | ✔ | ✔ | ❌
**<ins>In an external assembly</ins>** |   |   |   |   |   |  
Non-derived class | ✔ | ❌ | ❌ | ❌ | ❌ | ❌
Derived class         | ✔ | ✔ | ❌ | ✔ | ❌ | ❌
