### ISSUE TITLE
Correction for StringLibrary Class

### ISSUE THREAD

**Issue by asbscout** [dotnet/docs#25430]
There is an error in the code example for static StringLibrary Class.

The correct use of static StringLibrary Class is:

"...
            Console.WriteLine($"Input: {input} {"Begins with uppercase? ",30}: " +
                              $"{(StringLibrary.StartsWithUpper(input) ? "Yes" : "No")}{Environment.NewLine}");
..."

instead of:

"...
Console.WriteLine($"Input: {input} {"Begins with uppercase? ",30}: " +
                              $"{(input.StartsWithUpper() ? "Yes" : "No")}{Environment.NewLine}");
..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cbb75b-e0aa-13c6-c07d-65f0f0f68da2
* Version Independent ID: 06ecbd1e-dad7-fbac-9160-dfce34df4d2c
* Content: [Create a .NET class library using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code)
* Content Source: [docs/core/tutorials/library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@asbscout Thanks for reporting this -- the tutorial was missing an explanation that the method was created as an extension method. I'm adding that line from the Visual Studio version of the tutorial.
