### ISSUE TITLE
Describe how to remove or disable global imports

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#25436]
[This page](https://docs.microsoft.com/dotnet/core/tutorials/top-level-templates#use-the-new-program-style) lacks arguably two most important parts of the new "global usings" functionality, namely:
1. how to remove specific usings, and
2. how to disable the new functionality selectively (for a specific workload) or completely.

. . .

1. Remove specific usings

    A specific using can be removed via csproj/props:
    ```xml
      <ItemGroup>
        <Import Remove="System.Linq" />
      </ItemGroup>
    ```

2. Disable 

    * global using selectively:
    ```xml
      <PropertyGroup>
        <!-- Base .NET SDK -->
        <DisableImplicitNamespaceImports_DotNet>true</DisableImplicitNamespaceImports_DotNet>
    
        <!-- Web SDK -->
        <DisableImplicitNamespaceImports_Web>true</DisableImplicitNamespaceImports_Web>
    
        <!-- Worker SDK -->
        <DisableImplicitNamespaceImports_Worker>true</DisableImplicitNamespaceImports_Worker>
    
        <!-- Windows Forms -->
        <DisableImplicitNamespaceImports_WindowsForms>true</DisableImplicitNamespaceImports_WindowsForms>
    
        <!-- WPF -->
        <DisableImplicitNamespaceImports_WPF>true</DisableImplicitNamespaceImports_WPF>
      </PropertyGroup>
    ```
    
    * global usings completely:
    ```xml
      <PropertyGroup>
        <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
      </PropertyGroup>
    ```

As a bonus, here's how to add additional global usings:
```xml
  <ItemGroup>
    <Import Add="MyCompany.Super.CoolStuff" />
  </ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-new-program-style)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Related to #25485

**Comment by RussKie** [comment]
The whole thing is becoming out-dated with each passing day... It is going to get changed in https://github.com/dotnet/sdk/issues/19521.

**Comment by KalleOlaviNiemitalo** [comment]
Should document:

- the `ImplicitUsings` property in [MSBuild reference for .NET SDK projects](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props), where `DisableImplicitNamespaceImports` is currently documented
- the `Using` item type in [Common MSBuild project items](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022), where `Import` is currently documented
