### ISSUE TITLE
[Breaking change]: Windows Forms SDK support for implicit namespaces in C# projects

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#25438]
### Description

Related to https://github.com/dotnet/docs/issues/25066

Windows Forms SDK has enabled global usings in .NET 6.0 RC1 in line with the rest of .NET SDK with all guards and requirements outlined in https://github.com/dotnet/docs/issues/25066.

Implicit namespace will be enabled by default for C# projects targeting the `net6.0` TFM or higher and using `Microsoft.NET.Sdk`, `Microsoft.NET.Sdk.Web` or `Microsoft.NET.Sdk.Worker` SDK. A generated file containing the default namespaces will be included in the set of files passed to the compiler. Projects using a C# version less than 10 need to explicitly disable this feature.

There are three ways to control the namespaces that are included in the project:

1. Disable the feature completely by setting `<DisableImplicitNamespaceImports>` to `true` or `<DisableImplicitNamespaceImports_DotNet>` to `true` in the project file. Refer to https://github.com/dotnet/docs/issues/25066.
2. Disable a set of implicit namespaces added by the Windows Forms SDK by setting `<DisableImplicitNamespaceImports_WindowsForms>` to `true` in the project file.
3. Add or remove individual namespaces in the project file by modifying the `<Import>` item group in the project file. For example:

```xml
<ItemGroup>
  <Import Remove="System.Linq" />
  <Import Include="MyCool.Project" />
</ItemGroup>
```

These are the implicit namespaces added to projects using by the Windows Forms SDKs:

```
System
System.Collections.Generic
System.IO
System.Linq
System.Drawing
System.Windows.Forms
```

### Version

.NET 6 RC1

### Previous behavior

No implicit namespaces are added for applicable C# projects.

### New behavior

Implicit namespaces are added via global usings in a generated file in the obj directory. See how to control the list of included implicit namespaces above.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

These changes in the SDK are made to reduce the amount of boilerplate `using` statements that appear at the top of most C# projects.

### Recommended action

This feature will be enabled by default and for most users, no action will need to be taken. However, the introduction of this mechanism can cause type name conflicts with the namespaces listed above. In those cases, action need to be take to modify the list of implicit namespaces.

### Feature area

C#, Windows Forms

### Affected APIs

None.

**Comment by gewarren** [comment]
@RussKie Does it make sense to you to add this info to the existing article at https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/implicit-namespaces? Or create a new article under WinForms?

**Comment by RussKie** [comment]
I don't have a strong preference. If it makes sense and easier - let's add it to the existing article. Would be good to have a link from the Windows Forms area to the article though.
I expect WPF submitting a similar breaking change notification, as they have made similar changes too. /cc: @ryalanms

**Comment by gewarren** [comment]
@RussKie Why was this closed?

**Comment by RussKie** [comment]
Sorry, I thought I have posted a comment.


The whole feature is being re-designed, see https://github.com/dotnet/sdk/issues/19521. So the current description is no longer relevant.

**Comment by codeabuse** [comment]
Neither `<DisableImplicitNamespaceImports_WindowsForms>` nor `<Import Remove="xxx" />` option did not work for me.
net8.0-windows, the project needs to use both WPF and WinForms, but I'd like to keep ImplicitUsings since its a great feature in concept, allowing less clutter in file header sections. 

Instead, I was forced to disable Implicit Usings and stick with <Import Include=... /> for basicaly the same essentian namespaces except WinForms.
