### ISSUE TITLE
Please clarify servicing strategy for self-contained apps

### ISSUE THREAD

**Issue by fschmied** [dotnet/docs#25444]
The docs on the [self-contained deployment model](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) currently contain this passage:

> .NET Runtime (distributed with your app) can only be upgraded by releasing a new version of your app. However, .NET will update critical security patches as needed for the framework library in the machine that your app runs on. 

Could you please add some more details about this? What is the "framework library in the machine" in the case of a self-contained app? How does ".NET" update it? If there is no central runtime, in contrast to framework-dependent apps, what exactly will .NET update?

Also, this seems to contradict https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/ and https://github.com/dotnet/core/issues/1541#issuecomment-668259457, e.g.,:

> There is no change to apps that use the Self-Contained Deployment model, these apps are still responsible for keeping the runtime updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [Application publishing - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for pointing this out, I'll read through and see what I can clarify.

**Comment by haithamshahin333** [comment]
Hello team! Re-pinging on this - any clarifications on this @adegeo ? It would be good to get an understanding of how this works since as previously mentioned the self-contained deployment would bundle the runtime + libraries.

Thank you!

**Comment by adegeo** [comment]
Thank you for the reping @haithamshahin333 ! I've sent an email out to see if I can get it clarified.

**Comment by adegeo** [comment]
I was told to remove this clause as it's inaccurate. Sorry for the confusion.
