### ISSUE TITLE
Code has compile time error. 

### ISSUE THREAD

**Issue by hareshmasterly** [dotnet/docs#25489]
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using App.ScopedService;

using IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<ScopedBackgroundService>();
        services.AddScoped<IScopedProcessingService, DefaultScopedProcessingService>();
    })
    .Build();

This code can not compile. Can you please write correct syntax of the code? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca143da3-5c97-0dc0-9d99-ed477a8bce91
* Version Independent ID: 5a2fc6e8-a47b-c300-1ef0-e6ae89612d74
* Content: [Use scoped services within a BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/scoped-service)
* Content Source: [docs/core/extensions/scoped-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/scoped-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @hareshmasterly 
Thank you so much for posting this issue. We really appreciate it.

This code does, we have build steps in place to ensure that. The prerequisites explicitly call attention to the fact that the .NET 5 SDK is required. With .NET 5 you get C# 9, and with that [top-level programs](https://docs.microsoft.com/dotnet/csharp/whats-new/tutorials/top-level-statements). I'm going to close this. but if you're still have trouble try ensuring that you're using .NET 5.
