### ISSUE TITLE
Missing words in Regex​Options.​Ignore​Pattern​Whitespace

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2551]
[The documentation for `Regex​Options.​Ignore​Pattern​Whitespace`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions.ignorepatternwhitespace?view=netframework-4.7) says:

> Eliminates unescaped white space from the pattern and enables comments marked with #. However, this value does not affect or eliminate white space in , numeric , or tokens that mark the beginning of individual . For more information, see the "Ignore White Space" section of the Regular Expression Options topic.

The second sentence seems to be missing some words (possibly links?) and I'm not sure what they should be. [The 110 version on MSDN](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regexoptions(v=vs.110).aspx) has the same issue, while [the 100 version](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regexoptions(v=vs.100).aspx) contains much less text, so it doesn't help much:

> Eliminates unescaped white space from the pattern and enables comments marked with #. However, the IgnorePatternWhitespace value does not affect or eliminate white space in character classes.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @svick. This was a result of content loss during our previous migration that went unreported. I'll open a PR to correct it.
