### ISSUE TITLE
Clarify TFM target platforms

### ISSUE THREAD

**Issue by laurentkempe** [dotnet/docs#25525]
When `AssemblyInfo.cs` is not generated by having `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`, the following part of the documentation is misleading.

> The analyzer does not check target framework moniker (TFM) target platforms from MSBuild properties, such as \<TargetFramework> or \<TargetFrameworks>. If the TFM has a target platform, MSBuild injects a SupportedOSPlatform attribute with the targeted platform name in the AssemblyInfo.cs file, which is consumed by the analyzer. 

In that case, you need to specify by yourself in the `AssemblyInfo.cs` the `[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows7.0")]` attribute.

Distinguishing between the two cases would make the document clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8fbd7e-af44-859a-3967-b61bed6919a0
* Version Independent ID: e4517175-91cf-0fcd-d438-23e652f5022c
* Content: [CA1416: Validate platform compatibility (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416#tfm-target-platforms)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1416.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1416.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @buyaa-n
* Microsoft Alias: **bunamnan**

**Comment by buyaa-n** [comment]
@laurentkempe it is not clear to me what change you are suggesting, feel free to raise a PR with your suggestion

**Comment by laurentkempe** [comment]
In fact the not clarifies it @buyaa-n 👍🏼
