### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by vankraa** [dotnet/docs#25528]
[Enter feedback here]

in the description summary:

To obtain a UnmanagedMemoryAccessor object for a random access view to a memory-mapped **_fie._**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc02010-ec28-4e04-0881-7cd1d9d8b148
* Version Independent ID: c5261008-5deb-2af9-647f-f07ec56d9e47
* Content: [Memory-Mapped Files](https://docs.microsoft.com/en-us/dotnet/standard/io/memory-mapped-files)
* Content Source: [docs/standard/io/memory-mapped-files.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/memory-mapped-files.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
@vankraa Thanks for reporting that - I'm fixing it.
