### ISSUE TITLE
It sounds from the narrative (and common sense) that you meant to say "implement" for dependency inversion

### ISSUE THREAD

**Issue by gh-andre** [dotnet/docs#25521]
You may want to run this by the architect who provided this text, but it looks like in section _Dependency inversion_, they meant to say "implements" in highlighted areas.

![Screenshot 2021-08-08 at 16-46-36 Architectural principles](https://user-images.githubusercontent.com/7843659/128645329-e63f2067-197f-4801-8279-2a84156cce49.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829862b0-b51d-d4dd-d770-f875a588384f
* Version Independent ID: c5bc4d26-8f85-4544-3a4a-131554241eef
* Content: [Architectural principles](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles)
* Content Source: [docs/architecture/modern-web-apps-azure/architectural-principles.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/architectural-principles.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Implements would also be correct, but references it the intentional relationship I wanted to show with the diagram, as it demonstrates the dependency flow (and lack of references from Class A to Class B to Class C, in contrast to the other diagram shown in that chapter.
