### ISSUE TITLE
Incorrect instructions to debug tests in Visual Studio Code

### ISSUE THREAD

**Issue by coxantohi** [dotnet/docs#25530]
[Enter feedback here]
On the [Test a .NET class library using Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-code) page, [Debug tests](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-code#debug-tests) subsection it is indicated that a *Run All Tests* CodeLens adornment can be found and clicked. The paragraph starts with:
>If you're using Visual Studio Code as your IDE

First of all, I found that the following extension is required, ".NET Core Test Explorer".
Second of all, I found that two adornments are being shown: "Run All Tests" and "Debug All Tests", and that I should use the latter.

So I consider the content of the aforementioned page to inexact. Please amend it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6486ed3-e732-ece3-2ae1-fc0994c181ad
* Version Independent ID: 20e63789-5966-c622-df7c-3b30c31eeac8
* Content: [Test a .NET class library using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-code)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/testing-library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thank you for the suggestion. The tutorial has you use the CLI to run tests, which doesn't require an extension.  The extension you refer to is not provided by Microsoft. It is available to use if you prefer, but it's not appropriate for this tutorial. This tutorial is also intended to be helpful to developers who want to use the CLI for development. as explained in the [first tutorial in the series](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code):

> Project tasks, such as creating, compiling, and running a project are done by using the .NET CLI. You can follow this tutorial with a different code editor and run commands in a terminal if you prefer.

I'm closing this issue, but feel free to reopen if you want to continue the discussion.

**Comment by coxantohi** [comment]
Still, can you tell me if you could follow the instructions that say:
>  Instead of starting the *ShowCase* app project, open *StringLibraryTest/UnitTest1.cs*, and select **Run All Tests** between lines 7 and 8. If you're unable to find it, press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to open the command palette and enter **Reload Window**.
?

Because, my suggestions is also an asking for help: How can I see the *Run All Tests* adornment? Of course, I would like to reach the point when the
> Execution will stop at any breakpoint you've added to the test project or the underlying library code.

**Comment by tdykstra** [comment]
Here is what it looks like:
![image](https://user-images.githubusercontent.com/1569635/129100159-d4821faa-bda1-45aa-8d3f-f2c3c073b1a3.png)
Try closing and reopening VS Code, open the solution folder, and select the unit test project. If you don't see it and you have the test explorer extension installed, it may be interfering -- to run and debug tests you only need the C# extension. When asked about missing assets, be sure to respond Yes to load them.

**Comment by coxantohi** [comment]
Ok, I've managed to get to this point by installing the older 1.58.2 version. The code lens stayed visible after the auto update (to 1.59.0).

But still, for the execution to _stop at any breakpoint you've added_, I still think that the *Debug All Tests* lens should be clicked.

**Comment by tdykstra** [comment]
I agree, I'm reopening the issue and will make that change.
