### ISSUE TITLE
Amend given example for the .net version

### ISSUE THREAD

**Issue by coxantohi** [dotnet/docs#25549]
On the page [Tutorial: Publish a .NET console application using Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio), under the [Publish the app](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio#publish-the-app) section, in the image attached under step 7. the following location can be seen: 
bin\Release\net5.0\publish\. 
Also, under the [Inspect the files](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio#inspect-the-files) section the second step reads:
> In the project folder, expand _bin/Release/net5.0/publish_.

But the given example under the [Run the published app](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio#run-the-published-app) section gives the path
> C:\Projects\HelloWorld\bin\Release\netcoreapp3.1\publish\

which I find to be inconsistent with the above chosen version (.NET 5).

Can this be updated to C:\Projects\HelloWorld\bin\Release\net5.0\publish\ ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449b8ce2-80b3-9bfa-6d7f-3e8ac8a86e16
* Version Independent ID: 31264b07-1aeb-b3f0-1126-f25e578f6d50
* Content: [Publish a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/publishing-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@coxantohi  Thanks for reporting that - I'm fixing it.
