### ISSUE TITLE
IConfiguration parameter does not specify the type of the options

### ISSUE THREAD

**Issue by slabarque** [dotnet/docs#25546]
If I use the IConfiguration parameter to allow a user of my library to specify options coming from a configuration file section, how will that user know what the properties are they should specify? Would a typed IConfiguration&lt;TOptions&gt; not lead to better discoverability?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @slabarque
Thank you so much for posting this issue. We really appreciate it.

That's not a bad idea, but I do not believe that an `IConfiguration<TOptions>` exists, or at least not that I'm familiar with. But I do see that as being very useful. How would you imagine that working, in other words by simply expressing that an `IConfigration` corresponds to a `TOptions` instance what would the mechanics be under the hood?

**Comment by slabarque** [comment]
Hi @IEvangelist 
A generic IConfiguration<T> does indeed not exists. I do not know the internals enough to tell if it would actually make sense. It was the first thing that popped to mind that could improve type safety. My main concern was that the user of the library does not know the structure of the configuration that they should provide.

**Comment by IEvangelist** [comment]
I discussed this was @davidfowl this morning. While I understand the concern of a loosely typed configuration `IConfiguration` being concerning to consumers as the expected shape isn't known, authors would probably favor the `Action<TOptions>` overload instead:

https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#actiontoptions-parameter.

A new API of `IConfiguration<TOptions>` or even `IConfiguration<TSection>` would be nearly impossible to actual implement and would still have the same problems. When would you validate it, there are so many config providers and it's really a concern of the deserialization. I'm going to close this issue, but let me know if you have any more ideas. Thanks
