### ISSUE TITLE
Make sure you have installed the extension .NET Extension Pack in Visual Studio Code before typing the command '.NET Generate Assets for Build and Debug'

### ISSUE THREAD

**Issue by mohamedmehdigara** [dotnet/docs#25545]
Make sure you have installed the extension .NET Extension Pack in Visual Studio Code before typing the command '.NET Generate Assets for Build and Debug'

_Originally posted by @JoseMOrtizR in https://github.com/dotnet/docs/issues/6408#issuecomment-682156954_

After using the command an error message occured: Unable to generate assets to build and debug. Omnisharp server is not running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET console application using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
I'm guessing this issue may be irrelevant now. @tdykstra to confirm and close if necessary.

**Comment by tdykstra** [comment]
The tutorial doesn't call for the installation of .NET Extension Pack.
