### ISSUE TITLE
Memory<T> does not support stack allocated memory 2

### ISSUE THREAD

**Issue by RobertGBryan** [dotnet/docs#25551]
At the end of rule 2, this page says:

_The DisplayBufferToConsole method now works with virtually every buffer type imaginable: T[], storage allocated with stackalloc, and so on. You can even pass a String directly into it!_

There are two issues here:

1. `Memory<T>` can't be used with memory allocated on the stack. One link that talks about this, which appears to be the main source for this article, can be [seen here](https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6). This link says:

_`Memory<T>` cannot be backed by "transient" unmanaged memory; e.g., it is forbidden to back a `Memory<T>` with stackalloc._

You can also verify for yourself that the following code will not compile:

    Memory<int> mem = stackalloc int[10];

2. The 2nd issue is that a string can't be passed directly into DisplayBufferToConsole. If this is tried, then the C# compiler complains:

Error CS1503 Argument 1: cannot convert from 'string' to 'System.Memory<char>'

Maybe whoever wrote this intended to provide a converter to translate a string into a `Memory<T>` type. But, if so, it is not present.

I am using the latest version of VS 2019 Community - 16.10.4, which I recently upgraded to. I am also using .NET 6, preview 5 (or maybe preview 6 if it is included with the latest VS 2019 16.10.4 update).

In any case, I would recommend changing the text to read:

The DisplayBufferToConsole method now works for any type of memory allocated on the heap. `Memory<T>` can't be used with memory allocated on the stack with stackalloc. This is only supported with `Span<T>`.

The [`Memory<T>` Struct article](https://docs.microsoft.com/en-us/dotnet/api/system.memory-1) should also mention that `Memory<T>` can't be used on stack allocated memory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @GrabYourPitchforks 

Immediately before the paragraph that begins "The `DisplayBufferToConsole` method now works with virtually every buffer type imaginable..." is the following instruction:

>In fact, if we combine this rule and `Rule #1`, we can do even better and rewrite the method signature as follows:
>
> ```
> void DisplayBufferToConsole(ReadOnlySpan<char> buffer);
> ```

So the paragraph is commenting on `Span<T>` rather than `Memory<T>`. However, something is missing here -- I get compile errors when I follow this instruction, resulting in the following code:

```
using System;

class Example
{
    static void Main()
    {
        Memory<char> memory = new char[64];

        Console.Write("Enter a number: ");
        var value = Int32.Parse(Console.ReadLine());

        WriteInt32ToBuffer(value, memory);
        DisplayBufferToConsole(memory);
    }

    static void WriteInt32ToBuffer(int value, Memory<char> buffer)
    {
        var strValue = value.ToString();
        strValue.AsSpan().CopyTo(buffer.Slice(0, strValue.Length).Span);
    }

    static void DisplayBufferToConsole(ReadOnlySpan<char> buffer) =>
        Console.WriteLine($"Contents of the buffer: '{buffer}'");
}
```
* CS1503: Argument 1: cannot convert from 'System.Memory<char>' to 'System.ReadOnlySpan<char>'
* CS0029: Cannot implicitly convert type 'System.ReadOnlySpan<char>' to 'object'

**Comment by svick** [comment]
@tdykstra 

* `Memory` can't be directly converted to `Span`, you have to use the `.Span` property.
* `Span` can't be used in an interpolated string in .Net 5 and older. To make it work, you would have to add a call to `ToString()` (`$"Contents of the buffer: '{buffer.ToString()}'"`) or switch to `string.Concat` (`string.Concat("Contents of the buffer: '", buffer, "'")`) or upgrade to .Net 6 Preview.

I'm not sure what is the best way to change the doc because of this.

**Comment by RobertGBryan** [comment]
Looks like you are right about `Span<T>`. Guess I just missed the line using the `Span<T>` and assumed it was talking about `Memory<T>`.

Here is what I initially did to fix the compiler errors, which is similar to Tom Dykstra's approach:

    class Example
    {
        public static void TestMemoryAndSpan()
        {
           Memory<char> memory = new char[64];

           string s = "12345";
           // Console.Write("Enter a number: ");
           // var value = Int32.Parse(Console.ReadLine());
           var value = int.Parse(s);

           WriteInt32ToBuffer(value, memory);
           DisplayBufferToConsole(memory.Span); // Method is expecting a span object.
           DisplayBufferToConsole(s);
        }

       static void WriteInt32ToBuffer(int value, Memory<char> buffer)
       {
          var strValue = value.ToString();
          strValue.AsSpan().CopyTo(buffer.Slice(0, strValue.Length).Span);
       }

       static void DisplayBufferToConsole(ReadOnlySpan<char> buffer) =>
           Console.WriteLine($"Contents of the buffer: '{buffer.ToString()}'"); // Works if ToString method is used.
}

The output from the above test method is:

    Contents of the buffer: '12345                                                           '
    Contents of the buffer: '12345'

As can be seen, the Console.WriteLine method displays the full length of the Memory object and displays 59 blanks after the text is displayed. To fix this, the Memory object may be sliced, as follows:

    memory = memory.Slice(0, s.Length);

This now results in the same output as the string:

    Contents of the buffer: '12345'
    Contents of the buffer: '12345'

The first compile error is on the line:

    DisplayBufferToConsole(memory);

Since DisplayBufferToConsole expects a `ReadOnlySpan<char>` as the first argument, I simply passed the underlying `Span<T>` object that the `Memory<T>` class manages. Nice to see that a `Span<T>` may be passed for a `ReadOnlySpan<T>`.

The 2nd compilation error is due to the fact that Console.WriteLine in DisplayBufferToConsole is trying to interpret the `ReadOnlySpan<char>` as a string. I'm guessing at one time that this was anticipated behavior, but it is not supported today. It can be easily fixed by simply adding a ToString call at the end.

However, since ToString allocates on the heap and `Span<T>` as well as `Memory<T>` are designed to actually avoid needless allocations on the heap, you might not want to want to show an example in the documentation that allocates like this. If some developers see this, then they might start to question Microsoft's commitment to performance and efficiency with these types. The code example could be changed so that it does something else that does not allocate and does not use Console.WriteLine with a string.

Another way to fix the compilation errors is to change DisplayBufferToConsole's parameter from a `ReadOnlySpan<char>` to a `ReadOnlyMemory<char>`. The code for this is simply:

    static void DisplayBufferToConsole(ReadOnlyMemory<char> buffer) =>
        Console.WriteLine($"Contents of the buffer: '{buffer}'");

This actually works quite nicely, unless a string is passed in - which results in a compilation error. But, in the documentation for the [Console.WriteLine method](https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline), there is no overload that takes a `Memory<T>`. Is this officially supported, or just for internal use? If it is officially supported, then the Console.WriteLine documentation needs an overload for it, unless perhaps the Object overload is used for this.

It is interesting that Console.WriteLine takes a `ReadOnlyMemory<char>` object, but fails to take a `ReadOnlySpan<char>` object. This is the only case that I'm aware of where this is true. Usually, it is the other way around.

In any case, I think the best way to fix this is to simply extend Console.WriteLine to accept a `Span<T>` object. Since it already accepts a `Memory<T>` object, it should not be too much work to have it accept a `Span<T>` object. If there are any other cases within the CLR that accept a `Memory<T>`, but not a `Span<T>`, then someone should evaluate them to see if it would be reasonable to add a `Span<T>` overload. The reason for this is because if you have a `Span<T>` inside a method and need to call a method that takes a `Memory<T>`, but there is no `Span<T>` overload, then you are stuck. A `Span<T>` can't be converted to a `Memory<T>`, since that would violate the ref struct's restrictions. So, in cases like this, currently the only workaround that I see is to always use a `Memory<T>` if needing to call a method that only takes a `Memory<T>`.

Since a `Memory<T>` encapsulates a `Span<T>`, and offers a Span property, it would make these types easier to use if the compiler were to allow a `Memory<T>` to be passed as an argument to any parameter expecting a `Span<T>`. All the compiler would have to do is literally retrieve the Span property and pass that instead, so it should be quite simple to implement. The compiler already allows code to pass an array to a method expecting a `Memory<T>` or `Span<T>`. For example, this works:

    static void TestSpanAndMemory()
    {
        var buffer = new char[64];
        ... // Put something into buffer.
        DisplayBufferToConsole(buffer);
    }

    static void DisplayBufferToConsole(ReadOnlyMemory<char> memoryBuffer) =>
        Console.WriteLine($"Contents of the buffer: '{memoryBuffer}'");

If the method is overloaded with a Span<char>, then the compiler will generate an ambiguous error message. This can be resolved by casting the argument to the desired type. For example:

    static void TestSpanAndMemory()
    {
        ...
        // DisplayBufferToConsole(buffer); // Compiler error - ambiguous.
        DisplayBufferToConsole((Memory<char>)buffer);
        DisplayBufferToConsole((Span<char>)buffer);
    }

    static void DisplayBufferToConsole(ReadOnlyMemory<char> memoryBuffer) =>
        Console.WriteLine($"Contents of the buffer: '{memoryBuffer}'");

    static void DisplayBufferToConsole(ReadOnlySpan<char> spanBuffer) =>
        Console.WriteLine($"Contents of the buffer: '{spanBuffer.ToString()}'");

Returning to the compilation error when a string is passed to a method that is expecting a `ReadOnlyMemory<char>` parameter, there seems to be no good reason why this should not be allowed. There is no error if a string is passed into a method that requires a `ReadOnlySpan<char>`. So, why not allow a string to also be passed into a `ReadOnlyMemory<char>` parameter?

The [`Span<T>` struct](https://docs.microsoft.com/en-us/dotnet/api/system.span-1) has some nice examples. But, the [`Memory<T>` struct](https://docs.microsoft.com/en-us/dotnet/api/system.memory-1) has no examples and does not even mention that it can't be used to manage memory allocated on the stack with stackalloc. When first using a `Memory<T>` object, I tried to index it like this - memoryBuffer[0] = 1, which generated a compiler error. It was only after some time that I finally realized that this can only be done with the Span property. Only `Span<T>` currently supports indexing. So, this should be mentioned as well. 

In conclusion, the original issues that I initially thought were not accurate, are for the most part correct. So, if you want to close this issue based on that, then I have no objection. It would be nice if the following suggestions could be forwarded to their respective owners.

In summary, here are the recommended compiler / CLR changes that would make using Span<T> and Memory<T> easier:

1. The compiler should allow a `Memory<T>` to be passed as an argument to any method parameter expecting a `Span<T>`. Rationale - ease of use.
2. Add an overload for Console.Writeline to take a `Span<T>`. Console.WriteLine already has a `Memory<T>` overload. Investigate any other cases where a CLR method has an overload for `Memory<T>`, but not `Span<T>`. Rationale - ease of use and consistency of use with `Span<T>`.
3. Allow a string to be passed into a `ReadOnlyMemory<char>` parameter, much like a string is currently allowed to be passed into a `ReadOnlySpan<char>` parameter. Rationale - ease of use and consistency of use with `ReadOnlySpan<char>`.
4. Allow a `ReadOnlyMemory<char>` object to be created from a string, just like `ReadOnlySpan<char>`. Currently, a string's AsMemory method must be used to initialize a `ReadOnlyMemory<char>` object. Rationale - ease of use and consistency of use with `ReadOnlySpan<char>`.
5. Allow a `Memory<T>` object to use indexing operations that apply to the underlying `Span<T>` object so that explicit use of the Span property is no longer required to do indexing. Rationale - ease of use and consistency of use with `Span<T>`.

Recommended documentation upgrades:

1. Update `Memory<T>` struct documentation to add examples, show how indexing is done, and mention that `Memory<T>` can't be used to manage stack allocated memory.
2. Update Console.WriteLine documentation for the `Memory<T>` overload, unless the Object overload is used for this.
3. Avoid any examples that needlessly allocate like ToString. If necessary, rewrite the code example to do something else that does not allocate.
4. Update the documentation when any of the recommended compiler / CLR changes are made.

**Comment by svick** [comment]
@RobertGBryan 

> But, in the documentation for the [Console.WriteLine method](https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline), there is no overload that takes a `Memory<T>`. Is this officially supported, or just for internal use? If it is officially supported, then the Console.WriteLine documentation needs an overload for it, unless perhaps the Object overload is used for this.

That's exactly what is happening here: `Memory<T>` is boxed as an `object` (which causes an allocation) and `Console.WriteLine` calls `ToString()` on the `object`.

In general .Net doesn't have "for internal use only" APIs that you could call by accident. And since the documentation is autogenerated, it should always reflect all public APIs.

> It is interesting that Console.WriteLine takes a `ReadOnlyMemory<char>` object, but fails to take a `ReadOnlySpan<char>` object. This is the only case that I'm aware of where this is true. Usually, it is the other way around.

There is a proposal to add that overload: https://github.com/dotnet/runtime/issues/54529. But based on the discussion there, it doesn't look likely it's going to get added.

> In any case, I think the best way to fix this is to simply extend Console.WriteLine to accept a `Span<T>` object.

Even if that was the case, that wouldn't happen until .Net 6 or even .Net 7. In the meantime, I think the documentation should be correct at least for .Net 5.

> Since a `Memory<T>` encapsulates a `Span<T>`, and offers a Span property, it would make these types easier to use if the compiler were to allow a `Memory<T>` to be passed as an argument to any parameter expecting a `Span<T>`. All the compiler would have to do is literally retrieve the Span property and pass that instead, so it should be quite simple to implement.

Yes, it would be simple: just add an implicit conversion operator. The fact that that was not done makes me think it was intentional, but I don't know the reason.

> The compiler already allows code to pass an array to a method expecting a `Memory<T>` or `Span<T>`.

That works because there are implicit conversion operators [from an array to `Memory<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.memory-1.op_implicit?view=net-5.0&WT.mc_id=DOP-MVP-5002735#System_Memory_1_op_Implicit_T____System_Memory__0_) and [from an array to `Span<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.op_implicit?view=net-5.0&WT.mc_id=DOP-MVP-5002735#System_Span_1_op_Implicit_T____System_Span__0_).

> Returning to the compilation error when a string is passed to a method that is expecting a `ReadOnlyMemory<char>` parameter, there seems to be no good reason why this should not be allowed.

You can use [the `AsMemory()` extension method for that](https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.asmemory?view=net-5.0&WT.mc_id=DOP-MVP-5002735#System_MemoryExtensions_AsMemory_System_String_).

> When first using a `Memory<T>` object, I tried to index it like this - memoryBuffer[0] = 1, which generated a compiler error. It was only after some time that I finally realized that this can only be done with the Span property. Only `Span<T>` currently supports indexing. So, this should be mentioned as well.

I believe this is intentional. `Memory<T>` is quite complicated internally and so something like indexing it in a loop would have fairly bad performance. Retrieving the `Span` (once) and then indexing that (repeatedly) is what you're supposed to do. I agree this is worth mentioning somewhere in the documentation.

**Comment by tdykstra** [comment]
>In conclusion, the original issues that I initially thought were not accurate, are for the most part correct. So, if you want to close this issue based on that, then I have no objection. 

Closing this issue per that comment, but adding a "for more information, see ..." link to this issue in the article.
