### ISSUE TITLE
Overloading the comma operator

### ISSUE THREAD

**Issue by NikVladi** [dotnet/docs#25561]
Why are there no other operators, such as the comma? It cannot be overloaded, but it is not in the list of operators that cannot be overloaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91d85ae-8b37-e837-a031-144571362fbb
* Version Independent ID: 5ec5c397-c7c6-700c-bc36-a8dfb2396dad
* Content: [Operator overloading - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/operator-overloading#overloadable-operators)
* Content Source: [docs/csharp/language-reference/operators/operator-overloading.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/operator-overloading.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good question @NikVladi 

In C#, the `,` isn't defined as an operator. It's a punctuator.  You can see that in the latest standard on [Lexical analysis-operators and punctuators](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/lexical-structure.md#746-operators-and-punctuators).

I'll close this as an answered question.

**Comment by NikVladi** [comment]
Thank you!
