### ISSUE TITLE
Readonly Instance Members "hack"

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/docs#25622]
Something like this, is possible but shouldn't be allowed IMO
```
using System;
					
public class Program
{
	public static void Main()
	{
		Point a = new Point();
		a.FakeReadOnly(ref a);
	}
}

public struct Point
{
    public double X { get; set; }
    public double Y { get; set; }
	
	public readonly double FakeReadOnly(ref Point p) {
		p.X= this.X + 5;
		return this.X - p.X;
	}
}
```

I think this should be documented (or fixed)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221c58d8-4762-c228-92b5-14f44e2d4867
* Version Independent ID: 790ca059-c9c5-48e8-b50e-6e533549b974
* Content: [Readonly instance members - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members)
* Content Source: [proposals/csharp-8.0/readonly-instance-members.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/readonly-instance-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I don't see the problem with that code. Your code is basically the same thing as:

```c#
public class Program
{
	public static void Main()
	{
		Point a = new Point();
		Point.FakeReadOnly(a, ref a);
	}
}

public struct Point
{
	public double X { get; set; }
	public double Y { get; set; }
	
	public static double FakeReadOnly(in Point self, ref Point p) {
		p.X= self.X + 5;
		return self.X - p.X;
	}
}
```

Do you think this should be disallowed too?

**Comment by MithrilMan** [comment]
In _readonly instance members_ motivation section of the specification <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members#motivation> it's stated that the features is done to prevent a copy when using the struct as an `in` parameter

allowing this kind of code like in examples above, causes unintended side effects if the method is called when you pass the struct as `in` because the "readonly protection" doesn't protect this case, so I think it's worth at least a warning or a mention in the doc

**Comment by MithrilMan** [comment]
You are implicitly saying that an argument has a precedence over the signature modifier.
So an argument may defeat the modifier purpose.
If this is not worth a mention then I don't know what might deserve.

Personally I'd disallow the use of `ref`, on a readonly, when the ref argument is the same type of the Type declaring the readonly method.

I can't see why you should pass a `ref` on readonly methods instead of `in`

**Comment by BillWagner** [comment]
Thanks for bringing this up @MithrilMan 

I'm closing this, as the documentation is correct. The fact that an instance member is `readonly` does not mean the compiler verifies that the same instance isn't also used as an argument to a `ref` parameter.

If this is something you'd like to add to the language, the correct place to make that case is in the `dotnet/csharplang` repository.

That said, I agree with @svick 's analysis that this has a small chance of being approved.
