### ISSUE TITLE
Paragraph repeated

### ISSUE THREAD

**Issue by aniyanc** [dotnet/docs#25632]
Hi,

The last paragraph is repeated.
![migrate page repeat](https://user-images.githubusercontent.com/87487530/129400793-562664ee-70c8-4ad5-9d9a-0f186ace19be.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f5202f-97de-784f-b372-585b9d7b1c16
* Version Independent ID: 56b2050f-1cbd-3df5-b077-a765e47e4850
* Content: [Strategies for migrating incrementally](https://docs.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/incremental-migration-strategies)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/incremental-migration-strategies.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/incremental-migration-strategies.md)
* Product: **dotnet-architecture**

* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by ardalis** [comment]
Probably a merge issue. I'll submit a PR.
