### ISSUE TITLE
How to create an async configuration provider, e.g. CosmosDB?

### ISSUE THREAD

**Issue by mc0re** [dotnet/docs#25643]
The provided example for _EF Core_ provider uses synchronous interface. What about _async_ one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1cda6a-30fa-91b9-793e-918666776c9f
* Version Independent ID: 4df737d8-1051-2ce1-1d61-58768046283b
* Content: [Implement a custom configuration provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-configuration-provider)
* Content Source: [docs/core/extensions/custom-configuration-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-configuration-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @mc0re
Thank you so much for posting this issue. We really appreciate it.

Asynchronous configuration is not part of the API - and was of the intentional design consideration. Configurations are read at startup, and re-loaded if necessary in the background. In other words, if you need to rely on an async API - you're forced to do sync over async. And while it's not ideal, that is the only option. A majority of the configuration providers are I/O bound, but scoped to the local file system - Cosmos DB would be network I/O which is even less fortunate. My only advice is to be very careful with your async calls if that is what you choose to do.

I'm going to close this issue as it's not something that will likely be possible in the near future.

**Comment by mc0re** [comment]
Thanks for the answer. In the meantime, I chose this approach. For those interested in this...

Startup.cs
```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddDatabaseConfig();
}
```

ConfigurationReaderExtensions.cs
```csharp
    public static class ConfigurationReaderExtensions
    {
        public static IServiceCollection AddDatabaseConfig(this IServiceCollection services)
        {
            services.AddSingleton<IConfigurationReader, DatabaseCommunication>();

            services.AddOptions<EmailSenderOptions>()
                    .Configure<IConfigurationReader>((o, r) => r.ConfigureEmailOptions(o));

            return services;
        }
```

IConfigurationReader.cs
```csharp
    /// <summary>
    /// Read program configuration from an external source.
    /// </summary>
    public interface IConfigurationReader
    {
        /// <summary>
        /// Asynchronously read the config data.
        /// </summary>
        Task Initialize();


        /// <summary>
        /// Set up the given <see cref="EmailSenderOptions"/> instance.
        /// Used in the options pattern.
        /// To be called after <see cref="Initialize"/>.
        /// </summary>
        void ConfigureEmailOptions(EmailSenderOptions dest);
    }
```

DatabaseCommunication.cs
```csharp
    public class DatabaseCommunication : IConfigurationReader
    {
        #region Fields

        private readonly IMapper mMapper;

        private readonly AppSettings mSettings;

        private readonly ILogger<DatabaseCommunication> mLogger;

        private readonly CosmosClient mDbClient;

        private EmailSenderOptions mEmailOptions;

        #endregion


        #region Init and clean-up

        public DatabaseCommunication(AppSettings settings, ILogger<DatabaseCommunication> logger)
        {
            var mc = new MapperConfiguration(opt => opt.AddProfile<OptionsMappingProfile>());
            mMapper = mc.CreateMapper();
            mSettings = settings;
            mDbClient = new CosmosClient(settings.CosmosDbConnection);
            mLogger = logger;
        }

        #endregion


        #region API

        /// <inheritdoc/>
        void IConfigurationReader.ConfigureEmailOptions(EmailSenderOptions dest)
        {
            mMapper.Map(mEmailOptions, dest);
        }


        /// <inheritdoc/>
        async Task IConfigurationReader.Initialize()
        {
            if (mEmailOptions is null)
                mEmailOptions = await ReadEmailConfiguration();
        }

        #endregion
        ...
    }
```

Index.razor
```csharp
    protected override async Task OnInitializedAsync()
    {
        try
        {
            mStatusMessage = "Reading configuration";
            StateHasChanged();
            await ConfigReader.Initialize();
        ...
    }
```

The last part is not ideal, I know. But so far this is the best I could craft to be as close to .NET Core design as possible.
