### ISSUE TITLE
Incorrect info on struct member accessibility in Nested Types page

### ISSUE THREAD

**Issue by justcurious** [dotnet/docs#2564]
## Issue with Existing Topic

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/nested-types states:
> Regardless of whether the outer type is a class or a struct, nested types default to private, but can be made public, protected internal, protected, internal, or private

This implies that the following is supported:

```
public struct Me {
	protected class Test {	
	}
}
```

But since structs are implicitly sealed, the compiler gives the error: **The modifier 'protected' is not valid for this item**.

Same of course applies for _protected internal_.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @justcurious. We'll revise the topic to correct the inaccuracy.
