### ISSUE TITLE
root folder path?

### ISSUE THREAD

**Issue by Brad-FDI** [dotnet/docs#25661]
this fails for me because it is trying to create a root folder:
dotnet build --output /build_output

I had to do this:
dotnet build --output ./build_output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [.NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/index.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that!  I'm fixing it in #25707.
