### ISSUE TITLE
Add documentation for installing .NET on Debian 11 Bullseye

### ISSUE THREAD

**Issue by kroppt** [dotnet/docs#25669]
Currently, there is only documentation for up to Debian 10.

I tried to intuit the installation process for Debian 11, but it did not work. Either the APT source is different or it's not yet supported on the APT server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux Distributions](https://docs.microsoft.com/en-us/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Until it's officially supported, there isn't much I can do. This is the tracking issue: https://github.com/dotnet/core/issues/6529 I'll close this one as once they get traction on that issue, I'll update the docs. Cheers!
