### ISSUE TITLE
XML IntelliSense in Visual Basic

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2566]
We got the following LiveFyre comment for the topic [XML IntelliSense in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/xml/xml-intellisense):

This page should be removed. XML Intellisense did not work in Visual Studio 2015, and work to correct the problem was deferred. This very useful feature is still missing in Visual Studio 2017, and the fact that the document continues to claim it exists is very confusing.

The bug report is in the following Connect item: https://connect.microsoft.com/VisualStudio/feedback/details/1085407/intellisense-not-working-with-xml-to-schema.Edit

@AnthonyDGreen @Pilchie can you weigh on this one? Thanks!

**Comment by AnthonyDGreen** [comment]
Are we documenting older versions of the product on the docs.microsoft.com site? Should we doc the 2015 feature?

**Comment by mairaw** [comment]
@AnthonyDGreen sorry for missing your response earlier. The docs now cover multiple versions and we have versioning coming soon. Was this feature removed from VS 2017? If so, we can add something to that extent on the topic to say it's no longer supported.

**Comment by AnthonyDGreen** [comment]
It was in VS2008-2013. In VS2015 when we rewrote everything for Roslyn we cut it for time reasons and would like to add it back but it hasn't risen above the cut line.

**Comment by Pilchie** [comment]
To be clear - I've heard exactly one customer even notice this so far, so I don't see it rising above the cut line any time soon.

**Comment by mairaw** [comment]
Ok, I'll remove the page then since it's pre-VS 2015. Thanks for your input @AnthonyDGreen and @Pilchie.
