### ISSUE TITLE
Parameterless struct constructors

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#25676]
[Feature specification](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/parameterless-struct-constructors.md)

This would allow structs to declare field initializers and no-argument constructors.

See https://github.com/dotnet/docs/pull/24234#discussion_r632409776 for note on language reference.

**Comment by BillWagner** [comment]
This feature likely touches more articles than most, but those edits are likely smaller.

Major changes are needed on:

- [Language reference - struct types](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/struct)
- Programming guide - section on constructors](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/constructors)

- The entire C# docset should be searched for "constructor", "default constructor" and "parameterless constructor" to remove any restriction on struct types and parameterless constructors. In addition, the statements on the compiler generating a parameterless constructor should be checked.
-  The docset should also be searched for "initializer" and "field initialization" to update any rules on field initializers for struct types.
-  Pages for arrays should be checked for how arrays of struct types are initialized. These should be checked for accuracy in light of record structs and parameterless constructors.

**Comment by pkulikov** [comment]
@BillWagner is that fine if I update the language reference article on structs for this item?

**Comment by BillWagner** [comment]
@pkulikov 

> Is that fine if I update the language reference article on structs for this item?

Yes, please.

**Comment by pkulikov** [comment]
@BillWagner I'll continue with that and will check the [article about constructors](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/constructors) as the next step.

**Comment by pkulikov** [comment]
@BillWagner after #26310 is merged, we can say that almost all items from https://github.com/dotnet/docs/issues/25676#issuecomment-900594950 are done. EXCEPT, the two: (1) entire C# docset should be searched for "constructor" and (2) The docset should also be searched for "initializer". I've searched for those entries but capitulated when I saw the number of results. So, it's your call to decide if this item can be closed.

**Comment by BillWagner** [comment]
Thanks for all the details @pkulikov 

I just merged #26310.  I'll do a final search for constructor and initializer. 

My goal in that note was to find any instances where the docs said that a struct couldn't have either initializers or a parameterless constructor. If we don't have any, I'll close this.

**Comment by BillWagner** [comment]
After review for any remaining notes on the restrictions for a parameterless constructor in `struct` types, this is fixed.  

Fixed by the combination of #26037, #26271, #26282 and #26210.
