### ISSUE TITLE
Question. I'm still confused about the new style templates. 

### ISSUE THREAD

**Issue by scottgurvey** [dotnet/docs#25673]
[Enter feedback here]Question. I'm still confused about the new style templates using the top level statements.
If I was trying to use Serilog to write log information to a file, what would I do to replace the startup.cs entries and where would I put it?

The old code

```csharp
using Serilog;
using Serilog.Events;

public class Program
{
    public static int Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .CreateLogger();

        try
        {
            Log.Information("Starting web host");
            CreateHostBuilder(args).Build().Run();
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Host terminated unexpectedly");
            return 1;
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog() // <-- Add this line
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
}
```

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@IEvangelist This is a logging question - can you help?

**Comment by IEvangelist** [comment]
Hi 👋 @scottgurvey
Thank you so much for posting this issue. We really appreciate it.

I'm happy to help. The new style templates use top-level statements. They're functionally equivalent. So wherever you were plugging in `Serialog` before, you continue to do so. But these are templates we're talking about. For example, file new scenarios... there is no reason to update existing / functional apps to use top-level statements. Nonetheless, here is how you could do so:

```csharp
using Serilog;
using Serilog.Events;

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();

try
{
    Log.Information("Starting web host");
    CreateHostBuilder(args).Build().Run();
    return 0;
}
catch (Exception ex)
{
    Log.Fatal(ex, "Host terminated unexpectedly");
    return 1;
}
finally
{
    Log.CloseAndFlush();
}

static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .UseSerilog() // <-- Add this line
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

Please let me know if this is helpful, and we'll close this issue.

**Comment by scottgurvey** [comment]
Yes, this is a great help.

Thank you. I really appreciate it.

HSG

**Comment by IEvangelist** [comment]
I'm going to close this issue as I believe my response has helped the user. Feel free to open another issue if you need more help.

**Comment by scottgurvey** [comment]
That's fine and thank you. I've got it working. Somehow it seems I've gone back to the old style and I wish I could see how the new style works but this is fine and does the job. I suppose someday someone will generate some examples based on the Core 6 templates. Regards.On Aug 23, 2021 8:57 AM, David Pine ***@***.***> wrote:
I'm going to close this issue as I believe my response has helped the user. Feel free to open another issue if you need more help.
