### ISSUE TITLE
The docs.microsoft.com markdown parser produces different output then the github parser

### ISSUE THREAD

**Issue by TheManii** [dotnet/docs#2567]
# Issue 
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/langversion-compiler-option.md

has multiple commented out sections for future expansion, and the sections are correctly hidden when displayed on github, but one of the commented out sections are incorrectly displayed on docs.microsoft.com

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option

# Expected output
The commented out entries on doc.ms should only display the "..., 6, 7, latest" entries in the options table at the top of the page.

# Actual output
The commented out entries: "7.1, 7.2, 8" are displayed

# Assumed workarounds 
(I cannot directly test this myself without a sandbox on docs.ms to test on)
1. Remove some of the markdown syntax from the commented out code, the other code blocks do contain markdown syntax and still render correctly
2. Add enough whitespace so the docs.ms parser thinks it's not a part of the previous table
3. Remove the code comment and/or store it somewhere else

# Comments
Perhaps it's the pipe "|" character or the fact there is a markdown table causing it to be parsed differently. The other code blocks contain page links and anchors, and html styling, but only the first comment block (the one being rendered incorrectly) contains a markdown table.

**Comment by svick** [comment]
Based on my local testing with docfx, this fixes it: https://github.com/dotnet/docs/pull/2568.
