### ISSUE TITLE
Caller argument expression

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#25680]
[Feature proposal](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/caller-argument-expression.md)

This would aid in debugging and diagnostic scenarios. It would allow methods to capture the expression passed to a method for diagnostic purposes.

This should be updated in a few places:

- Where diagnostics are covered
- Attributes understood by the compiler.
- nameof expressions should point to this new feature.

**Comment by Youssef1313** [comment]
**Note:** The feature was implemented for Visual Basic as well (currently it's hidden under a feature flag). As soon as the feature flag gets removed, it should be documented for VB.

**Comment by Youssef1313** [comment]
VB feature flag is being removed in https://github.com/dotnet/roslyn/pull/55841
