### ISSUE TITLE
Version not correct

### ISSUE THREAD

**Issue by mdathora** [dotnet/docs#25719]
When following the instructions to create a installation script, I make the URL:
`https://dotnetcli.azureedge.net/dotnet/Sdk/Current/latest.version`

However, the result is `version 5.0.303`. According to the [download page](https://dotnet.microsoft.com/download/dotnet/5.0) this version does not exist... The latest version should be `5.0.400`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#examples)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @dotnet/install-scripts-maintainers

**Comment by bekir-ozturk** [comment]
Hi @mdathora,
 latest.version files are no longer used for downloading the SDK. Therefore, they are not being updated anymore.
 Can you point me to the instructions you were following?

To download the latest 5.0, you can use the link `https://aka.ms/dotnet/5.0/dotnet-sdk-win-x64.zip`. Depending on your system, you may want to replace `win-x64` in the end with your OS and architecture.
