### ISSUE TITLE
The title "Avoid accessing Assembly file path when publishing as a single file" is incorrect

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/docs#25728]
The title for this rule is incorrect; it appears to have been copied from IL3000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 568e0acd-e52d-d1f2-8cb3-e0621ca28cdb
* Version Independent ID: c6829f80-f049-946c-9284-e4af0b1df276
* Content: [IL3001: Avoid accessing Assembly file path when publishing as a single file (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/il3001)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/il3001.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/il3001.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @agocke
* Microsoft Alias: **angocke**

**Comment by tdykstra** [comment]
Actually the use of the same title for the two rules was deliberate -- see https://github.com/dotnet/roslyn-analyzers/pull/3921/files#r463809548
