### ISSUE TITLE
Version vs LangVersion

### ISSUE THREAD

**Issue by perjahn** [dotnet/docs#25747]
Is Version superseding LangVersion in some way? What happens when specifying both? Is it supported?

Please explain the difference between Version and LangVersion in csproj files, how they relate, how the are compatible, what combinations are possible, and what's not possible to combine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefc148c-0cfe-5a61-3268-676e410abaeb
* Version Independent ID: e63755c1-f406-e95a-829b-bb559abd83fe
* Content: [Breaking change: C# code in templates not supported by earlier versions - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/csharp-template-code)
* Content Source: [docs/core/compatibility/sdk/6.0/csharp-template-code.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/csharp-template-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@perjahn Can you point to the article where you learned about Version in the csproj file?

**Comment by perjahn** [comment]
Sorry, I might have misunderstood something. You can close this issue.
