### ISSUE TITLE
cannot snap-exec: cannot exec "/snap/dotnet-sdk/137/snap/command-chain/snapcraft-runner": permission denied

### ISSUE THREAD

**Issue by yooakim** [dotnet/docs#25757]
When I follow the instructions to install .NET DSK via Snap I get this error:

```
cannot snap-exec: cannot exec "/snap/dotnet-sdk/137/snap/command-chain/snapcraft-runner": permission denied
```

I'm on a newly installed Ubuntu:

```
~LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40005eb-f935-d50d-10ce-c1e0a47ea70e
* Version Independent ID: 91f4a9b7-09d0-f18e-af4a-c0af28a8948f
* Content: [Install .NET on Linux with Snap - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)
* Content Source: [docs/core/install/linux-snap.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-snap.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! Sorry you're having a problem. Did you install the snap package with the `--classic` parameter? If so, are one of the solutions mentioned here helpful? https://askubuntu.com/questions/930437/permission-denied-error-when-running-apps-installed-as-snap-packages-ubuntu-17

If none of that works, I can transfer this issue to the .NET SDK repo for help.

**Comment by yooakim** [comment]
Sorry, can't test this again right now as the machine I used not longer exists. So let's close this at this time. Sorry.
