### ISSUE TITLE
Wrong implementation of GetObjectData for VB

### ISSUE THREAD

**Issue by oahrens** [dotnet/docs#25753]
Instead of

    Private Sub GetObjectData(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        Implements ISerializable.GetObjectData
        If info Is Nothing Then
            Throw New System.ArgumentNullException("info")
            info.AddValue("name", FullName)
        End If
    End Sub

the implementation should be

    Private Sub GetObjectData(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        Implements ISerializable.GetObjectData
        If info Is Nothing Then
            Throw New System.ArgumentNullException("info")
        End If
        info.AddValue("name", FullName)
    End Sub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690b0523-b74b-ec96-6c50-0586cbb4c297
* Version Independent ID: e6d9ec13-2d5d-227b-1a12-5f322a31d0a9
* Content: [Serialization guidelines](https://docs.microsoft.com/en-us/dotnet/standard/serialization/serialization-guidelines)
* Content Source: [docs/standard/serialization/serialization-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/serialization-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that! I'm fixing it in #25770
