### ISSUE TITLE
Make it clear that the runtime options fix for System.Drawing.Common breaking change apply to Linux and MacOS

### ISSUE THREAD

**Issue by Webreaper** [dotnet/docs#25755]
The runtime options setting applies to both Linux and MacOS, so the docs should clarify that, e.g:

"_Alternatively, you can enable Unix/MacOS/etc support by setting the System.Drawing.EnableUnixSupport runtime configuration switch to true in the runtimeconfig.json file:_"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa60e1c-9c9a-ce16-2e47-c41857fc8c48
* Version Independent ID: c3b792d7-50ab-ff45-09bf-37a7550f0e09
* Content: [Breaking change: System.Drawing.Common only supported on Windows - .NET](https://docs.microsoft.com/en-gb/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)
* Content Source: [docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Webreaper** [comment]
Fixed by @terrajobst [here](https://github.com/dotnet/docs/pull/25759). 😁

**Comment by gewarren** [comment]
Fixed.
