### ISSUE TITLE
Mention the GenerateRuntimeConfigurationFiles project setting required for runtime config template files to work

### ISSUE THREAD

**Issue by Webreaper** [dotnet/docs#25756]
Mention that for SDK style projects, for the runtime settings template change to take effect, you need to add the following to the project:
```
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
```
Without that, the runtime `runtimeconfig.template.json` file will be copied to the output, but the settings won't be added to the `[appname].runtimeconfig.json` file by the build.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa7bda7-581d-9654-c7c5-5ff0292ddfb3
* Version Independent ID: 7f32162e-ec95-0a16-7618-14b7a7c80cff
* Content: [Runtime config options - .NET](https://docs.microsoft.com/en-gb/dotnet/core/run-time-config/)
* Content Source: [docs/core/run-time-config/index.md](https://github.com/dotnet/docs/blob/main/docs/core/run-time-config/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Webreaper** [comment]
Example here, if it's helpful: https://github.com/Webreaper/Damselfly/commit/c87318848e6b33ac1496234804e2bcd8ef76fd09

**Comment by gewarren** [comment]
@dsplaisted Is the `GenerateRuntimeConfigurationFiles` property necessary in this case?

**Comment by dsplaisted** [comment]
The property does need to be set to true, but it normally defaults to true if the project needs a runtimeconfig.json file, ie if the `OutputType` is `Exe`.

**Comment by Webreaper** [comment]
It's still worth mentioning though. My app is a blazor server, and uses the new SDK style project, and doesn't have an output type explicitly set in the project, so I had to manually add GenerateRuntimeConfigurationFiles to make it work (which is why I raised this issue). 

https://github.com/Webreaper/Damselfly/tree/master/Damselfly.Web
