### ISSUE TITLE
This page doesn't follow the naming convention for c#

### ISSUE THREAD

**Issue by PhotoAtomic** [dotnet/docs#25767]
This page doesn't folllow the convention stated here
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#camel-case

differently from what is reported at the top of the document
>The guidelines in this article are used by Microsoft to develop samples and documentation

due to a later addition to the guidelines occurred here https://github.com/dotnet/docs/commit/631c596d095e9c0815c838a5b8b8ec79c122dd5b

see https://github.com/dotnet/docs/issues/25754 as reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808a5ca6-e3c5-bed2-6bc7-8e0dbf965870
* Version Independent ID: 9a6c2aa5-f5cc-5caf-6592-3048e377440b
* Content: [private keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private)
* Content Source: [docs/csharp/language-reference/keywords/private.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/private.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @PhotoAtomic,
I've marked this issue as `up-for-grabs`, and we'd happily review a pull request to update these samples.
Thank you

**Comment by PhotoAtomic** [comment]
Sorry, after the signaling I've already done my own copy of the coding convention, not interested anymore in the consistency of this doc.

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
