### ISSUE TITLE
[Breaking change]: Microsoft.Extensions.Configuration binder will now bind single elements to an array 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/docs#25779]
### Description

Related to https://github.com/dotnet/runtime/pull/57204.

Added an app context switch in 6.0 for configuration binder. As of .NET 6.0 the configuration binder will bind single elements to an array unless setup otherwise via the `Microsoft.Extensions.Configuration.BindSingleElementsToArray` context switch.

#### More context:

This was originally requested as an API addition to BinderOptions, with details explained in issue https://github.com/dotnet/runtime/issues/57325#issuecomment-900508614, but we decided to go with the app context approach instead.

### Version

.NET 6 RC1

### Background and motivation

Previously with JSON Configuration Provider:
```json
{
   "tvshow": {
        "metadata": [
            {
               "name": "PrisonBreak"
            }
         ]
    }
}
```

would bind to below without any problem:
```cs
public class TvShow
{
  public Metadata[] Metadata { get; set; }
}

public class Metadata
{
  public string Name { get; set; }
}
```

However binding to this with an XML configuration provider given input below:
```xml
<TvShow>
  <Metadata>
    <Name>Prison Break</Name>
  </Metadata>
</TvShow>
```

would have no way of indicating that `TvShows` can contain multiple `Metadata` elements and that is bound to an array, so we fail to bind when a single element is provided as the key doesn't contain any `index` in the target array as the binder expects when binding to an array, and we return a `Metadata[]` with a `null` object.

### New behavior

To support binding to array elements for XML configuration provider, we changed the binder to account for a `key` without the `index` suffix when the child elements don't contain any index (a single element).

This is a breaking for other providers where this is not expected. Consider changing the original JSON from:

```json
{
   "tvshow": {
        "metadata": [
            {
               "name": "PrisonBreak"
            }
         ]
    }
}
```

so that `tvshows` is an object with a single `metadata`, this would bind even though json is not specifying an array:

```json
{
   "tvshow": {
        "metadata": {
            "name": "PrisonBreak"
          }
    }
```

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Partner request

### Recommended action

If the user wants to switch back to old behavior they could set the app context switch below:

```C#
AppContext.SetSwitch("Microsoft.Extensions.Configuration.BindSingleElementsToArray", false);
``` 

#### Risks:

This breaking change could impact perf a little bit but only if the flag is set to `true`.

### Feature area

C#

### Affected APIs

`ConfigurationBinder.Bind(..)`

https://apisof.net/catalog/8210dea9-7ecf-ca70-bb5a-9842c62effa4

**Comment by gewarren** [comment]
@maryamariyan I feel like we need a separate breaking change area for the docs called "extensions". Would that make sense to you?

**Comment by maryamariyan** [comment]
> @maryamariyan I feel like we need a separate breaking change area for the docs called "extensions". Would that make sense to you?

sure, a new `extensions` labe in dotnet/docs repo?

**Comment by gewarren** [comment]
> > @maryamariyan I feel like we need a separate breaking change area for the docs called "extensions". Would that make sense to you?
> 
> sure, a new `extensions` labe in dotnet/docs repo?

No, a category that would appear in the breaking change issue template and that appears in the TOC like this: https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/extensions/6.0/bind-single-elements-to-array?branch=pr-en-us-26031

**Comment by maryamariyan** [comment]
> No, a category that would appear in the breaking change issue template and that appears in the TOC like this: https://review.docs.microsoft.com/en-us/dotnet/core/compatibility/extensions/6.0/bind-single-elements-to-array?branch=pr-en-us-26031

sure sounds good to me
