### ISSUE TITLE
Baixei

### ISSUE THREAD

**Issue by Bartzdaddy** [dotnet/docs#25776]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2842ce-ee53-ec35-90c6-791a952dfc3b
* Version Independent ID: 79ec96d5-9c2c-1eaa-feb8-40b0afee6a30
* Content: [Check installed .NET versions on Windows, Linux, and macOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions)
* Content Source: [docs/core/install/how-to-detect-installed-versions.md](https://github.com/dotnet/docs/blob/main/docs/core/install/how-to-detect-installed-versions.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, it seems you've opened this documentation issue in error, or you forgot to provide the details to the problem. Let me know if you want me to close it.
