### ISSUE TITLE
Materials are ambiguously scattered across different sections

### ISSUE THREAD

**Issue by Andrej16** [dotnet/docs#25783]
For example [Query expression basics](https://docs.microsoft.com/ru-ru/dotnet/csharp/linq/query-expression-basics) and [Standard Query Operators Overview](https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-expression-basics). it would be nice to organize this in one section, making it easier to learn

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1113cc60-88ac-ece0-d67b-6411001e285c
* Version Independent ID: 5dfb251f-fbf4-19dd-7ef1-e7681201de0c
* Content: [Language-Integrated Query (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 124440](https://dev.azure.com/msft-skilling/Content/_workitems/edit/124440)

**Comment by BillWagner** [comment]
Thanks for writing this @Andrej16 

I agree, and this is planned for after the .NET 6 release.
