### ISSUE TITLE
Add some reference to  .net5 

### ISSUE THREAD

**Issue by NeilMacMullen** [dotnet/docs#25808]
It would be useful to update this page to include a reference to .net5 (and, in future .net6) since as it stands it looks like only .net core 3.1 is supported from the current text.  Adding ".net5" would also help the page appear in search results - I spent several hours searching for combinations of "net5", "vcxproj", "C++", "TargetFrameworkVersion" etc but never hit this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 590dc11f-354e-ded2-469f-605febf6b394
* Version Independent ID: 097bfdc7-9d3d-852f-eba3-e7ea2e0c4239
* Content: [Migrating C++/CLI projects to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli?source=docs)
* Content Source: [docs/core/porting/cpp-cli.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/cpp-cli.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mjrousos
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
I believe this was fixed in #28850
