### ISSUE TITLE
Update VS for Mac tutorial series for .NET 6 template changes

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#25835]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957bb4fd-92c9-47ac-da7a-778cea12f429
* Version Independent ID: dd9058df-2586-7b1c-d1cc-ae1b82f047ed
* Content: [Create a .NET console application using Visual Studio for Mac - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac)
* Content Source: [docs/core/tutorials/with-visual-studio-mac.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-mac.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by wadepickett** [comment]
@tdykstra, I'll take this one since you suggested it.  Thanks.  If I got that wrong feel free to set the assignment back to you.

**Comment by tdykstra** [comment]
You didn't get that wrong, you're welcome to take this, thanks.
