### ISSUE TITLE
visualstudio-docs/issues/6980 -- entity typos in header

### ISSUE THREAD

**Issue by WilliamAntonRohm** [dotnet/docs#25841]
Transferred from https://github.com/MicrosoftDocs/visualstudio-docs/issues/6980

There are two HTML entity typos in 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.tools.applications.serverdocument.solutionid?view=vsto-2017

https://user-images.githubusercontent.com/40815708/130006514-f7d9e71c-16ec-402d-9607-9e6f25212d3a.png

I don't seem to have perms to edit the file here, and my fork is baffled over main vs master.

**Comment by hyoshioka0128** [comment]
@WilliamAntonRohm - Thanks!
I'm poor English. Thank you for understanding what you intended.
