### ISSUE TITLE
Wrong code-block

### ISSUE THREAD

**Issue by TElbek** [dotnet/docs#25845]
[Enter feedback here]
There is something horribly wrong with the code-block below the text:
'Replace the existing Program contents with the following C# code:'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bac4b0-9ea8-9471-c1a8-88c8bdd7e733
* Version Independent ID: 976f3af2-4d3f-6d45-1e9e-b4c86edaed34
* Content: [Create a Queue Service](https://docs.microsoft.com/en-us/dotnet/core/extensions/queue-service)
* Content Source: [docs/core/extensions/queue-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/queue-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @TElbek
Thank you so much for posting this issue. We really appreciate it. There is nothing wrong with that code, it is perfectly valid C#. This is using [top-level statements](https://docs.microsoft.com/dotnet/csharp/whats-new/tutorials/top-level-statements).

**Comment by IEvangelist** [comment]
Hi @TElbek - I'm going to close this issue. If you still need help or find another issue, please feel free to open a new issue. Thanks
