### ISSUE TITLE
'How to search strings' has duplicate examples

### ISSUE THREAD

**Issue by laeccan** [dotnet/docs#25849]
For URL https://docs.microsoft.com/en-us/dotnet/csharp/how-to/search-strings,
the section "Does a string follow a pattern?" repeats the following lines 

\d{3} | matches exactly 3 digit characters
-- | --
- | matches the '-' character

Please remove the duplicate example rows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb75f6cf-6601-bd86-9529-55610829f907
* Version Independent ID: 356e606b-eacd-6aaf-ab11-30bf6a73e843
* Content: [How to search strings (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/search-strings)
* Content Source: [docs/csharp/how-to/search-strings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/search-strings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @laeccan 

I've opened #25857 to address this.

In the future, if you find issues like this, you may find it just as quick to open a PR to fix the issues as it is to report it. You can click the "edit" button (it looks like a pencil), make the edit in the web editor, and submit a PR.

thanks again, for helping us improve.
