### ISSUE TITLE
There such limit in OS depended library, why no RSAManaged, DSAManage in .net ?

### ISSUE THREAD

**Issue by John0King** [dotnet/docs#25850]
There are such limits in OS depended library, why there'r  no `RSAManaged`, `DSAManage` in .net ,  or simply switch to use the power of OpenSSL ?  Is that the reason of dotnet team obsessive on drop OS support (drop users and developers) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dba5d39-737f-cfa3-b1e4-c997e55312a8
* Version Independent ID: 95e31f6e-9a36-913e-6a02-7fb1606e5a52
* Content: [Cross-platform cryptography in .NET Core and .NET 5](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography)
* Content Source: [docs/standard/security/cross-platform-cryptography.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/cross-platform-cryptography.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Earthman100** [comment]
Theres no need for it, it is data host to data from all domains is its own standalone to all platforms.

**Comment by IEvangelist** [comment]
Hi 👋 @John0King 
Thank you so much for posting this issue. We really appreciate it.

I'm not sure I follow your question or comments. I'm going to add @blowdart who is far more qualified that I am to answer security related questions.

**Comment by blowdart** [comment]
What limits are we talking about here?

**Comment by John0King** [comment]
here  : 
[ecdsa](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#ecdsa)
[ecdsa-native-interop](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#ecdsa-native-interop)
[DSA]https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#dsa
[dsa-native-interop](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#dsa-native-interop)
[x509chain on MacOS](https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#x509chain)

**Comment by IEvangelist** [comment]
Hi again @John0King - I think this issue would be more appropriate in the dotnet/runtime repo as it's more like a product question/feedback. Not really related to docs, please correct me if I'm wrong? If you agree, I can move this issue.

**Comment by Earthman100** [comment]
I disagree as is on its own Framework as extension to .net scsi interopt controller to it's own codepage from it's version of namespace as made up by private api.. lOs is still in development as to new implementation methods of code iteration and exchange methods from call to caller with ppoppaoeppp being translated through sys.lib mount on mainthread to config utils with tmp base installer to exchange a tmp drive to mainthread for paging utils to pre post runtime environment from mainthread sys.path of utils built into frame as data later for post script after before after variation of on reload at codepage code error on translation to pre run before and after page exception to dom from runtime to allow exchange from frame utils to origin page while creating json file config file for virtual kernel of net dom net config utils to virtual dbus as command interface of debugger of browser to built in functions of kernel to negotiate codepage .baks globs for data passed storage of drm and net domain cookies to parcels from 3 separate temp mounts from each synched window I'd to machine guid from b.component stored regexer of built in paths to home dir in */Frame back to virtual dbus and a machine readable permeant meta generator to each synched if from hdd of 3d process user to 4d user on virtual dbus runtime of is envioron back to origin browser as base to binary base writer or setup of runtime exchange....lots to explain took a break on project for a month or so...kerbose would be my exchange to dsa as rsa exchange to browser service worker as of now there's no need as its iterating current browser to be exact to page while implementing it's own runtime code and codepage exchange to translated base setup then sending it back to browser before page translated events on page load to negotiate errors on code to code exchange from mainthread to mainthread of tmp mounted exchange of one mainthread copy on its own code from code parsed args of running codepage js

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Earthman100** [comment]
Runs .data incoming to and from *\Frame in a meta after creating a manifest file for the data in a json format where meta matches location and .bak of json writer data send and recieved by page source or domain double referenced from web domain socket to iana as browser service feature to setup of os.envioron one of two separate server hosts to live data as I will have to update for config loggers on tracers on page exception on load to a secure dma extension management module sub due base of a mixed subsystem to and from virtual dbus; as other would be env of Unix modified service under it's own code from server gateway to setup tools as User under virtual dbus to each window Id synched to each machineid at boot to is hdd dbus launch window as process launcher to user hdd not net dbus as net only function net window

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
