### ISSUE TITLE
How can "M" format to 12 in one context and December 17 in another context?!

### ISSUE THREAD

**Issue by plbowers** [dotnet/docs#25853]
You have "M" being a standard format going to "December 17".

You have "M" being a custom format going to "12"

How can you have the same format code go to 2 different values?!

I wanted to check if my month was the same in Power Automate so I used 

`equals(formatDate(<onedate>, 'M'), formatDate(<otherdate>, 'M'))`

I was assuming (as per documentation in custom formatting codes in the table [not the full documentation below]) that the 'M' would result in "6" for the date June 17, 2021. But what to my wondering eyes should appear but it formats as "June 17".

I see that if someone goes to the full documentation for "M" (and "m" presumably - another example of ambiguous codes) this ambiguity is mentioned, somewhat mitigating the poor design choice by clearly documenting it. However, I would strongly recommend that some kind of indicator be put in the table above as well as in the full documentation below. Often an experienced programmer is glancing through the table to get the appropriate formatting code and won't bother going to the full documentation. Some kind of asterisk in the table would be helpful to identify formatting codes that have this kind of potential for ambiguity.

Upon even further reading I see you do have a section entitled "Using single custom format specifiers" down at the very bottom that clearly documents exactly what is going to happen. I still maintain that the table which immediately follows the paragraph starting with the sentence "The following table describes the custom date and time format specifiers and displays a result string produced by each format specifier." should have an asterisk or some other indicator which, when clicked, takes you to a note at the bottom of the table pointing out the importance of prefixing with a `%` for disambiguation if used alone. Or simply add a sentence to that effect in the paragraph I mentioned above. At least then if you have read that far you will have read what is needed rather than assuming that someone coming to look at a format code will read all the way to the notes in the bottom to understand how to use it...

**Comment by plbowers** [comment]
Suggested sentence to be added before the sentence "For more information about using custom date and time format strings, see the Notes section":

If a single character custom format specifier from the list below is to be used it must be prefixed with a `%` to avoid being interpreted as a standard formatting code. (last 3 words should link to the appropriate page)

**Comment by BillWagner** [comment]
Thanks for noting this @plbowers 

Can you add a link to the article this refers to? It will help us address it.
