### ISSUE TITLE
How to consume Custom Vision Object Detection ONNX models

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#25863]
Create new how-to guide / tutorial that shows how to consume an Custom Vision Cognitive Services object detection ONNX model with ML.NET

**Comment by luisquintanilla** [comment]
Add note on how to use GPU when scoring ONNX models

**Comment by jwood803** [comment]
@luisquintanilla @gewarren I may double check this to make sure this is compatible with ML.NET 3, as well.
