### ISSUE TITLE
Documentation for IncrementalHash is missing

### ISSUE THREAD

**Issue by terrajobst** [dotnet/docs#2587]
It looks like the docs for [IncrementalHash](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-1.1&term=IncrementalHash) are all still just boilerplate. However, the type was already shipped in .NET Core 1.0.

**Comment by mairaw** [comment]
Yes, we don't have all .NET Core APIs documented yet. But the basic descriptions for this one should be coming soon.

**Comment by GSPP** [comment]
What is the purpose of this class in contrast to the existing APIs? When should this class be used? This is the question that I am researching right now. Maybe this should be documented.
