### ISSUE TITLE
Description of code doesn't match code shown in Contructors.md

### ISSUE THREAD

**Issue by justcurious** [dotnet/docs#2589]
## 2 Issues with an Existing Topic

**1) Bug:**

Above the second block of code in Constructor Syntax (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors#constructor-syntax) it says

> The expression body definition assigns the argument to the **Name** property.

But the code sets the argument to the **locationName** field:

`public Location(string name) => locationName = name;`

So either the description needs to change or the code edited to 
`public Location(string name) => Name = name;`

**2) Suggested clarification:** 

Under Static Contructors, I think it would benefit from including the word **static** since it won't initialize any instance fields at that time.

> If you don't provide a static constructor to initialize static fields, the C# compiler will supply a default static constructor that initializes **STATIC** fields to their default value as listed in the Default Values Table.

**Comment by svick** [comment]
Do you want to create a Pull Request that makes these changes? If you need any help with that, feel free to ask.

**Comment by rpetrusha** [comment]
@justcurious, the best alternative is to modify the description to replace the Name property with the locationName field. If you would like to open a PR, that would be good; if not, I'll be happy to do it.

**Comment by justcurious** [comment]
Sure, I'll give the pull request a go

**Comment by justcurious** [comment]
I've attempted a pull request - https://github.com/justcurious/docs/tree/justcurious-Issue2589. Having not issued a PR before I'm completely unsure how that went.  I attempted it through the github website.

If you spot any problems, or have advice for future PRs to your helpful repo, any feedback is warmly received.
