### ISSUE TITLE
How to realize the F1 shortcut of custom VisualStudio

### ISSUE THREAD

**Issue by hdefucom** [dotnet/docs#25893]
In VisualStudio, F1 can open MSDN official documents. 
I always thought it could not be customized.
Until I used DevExpress.
With the cursor in the DevExpress class, press F1 to open the DevExpress document.
 How do we achieve this? Attribute?

**Comment by hdefucom** [comment]
VisualStudio2019 has this function,
but VisualStudio2010 dotn't have this function

**Comment by BillWagner** [comment]
ping @ghogen 

Where should this issue be routed to?

**Comment by MSDN-WhiteKnight** [comment]
Isn't DevExpress just shipping their own VS Extension that does it? I don't think there's a feature to override F1 help specifically, but extensions could control pretty much any IDE behaviour. DevExpress has several extensions in marketplace, but i don't know which one exactly is responsible for F1 help. The feature is documented here: https://docs.devexpress.com/GeneralInformation/401814/open-devexpress-documentation-from-visual-studio , but there are no details on implementation.

**Comment by ghogen** [comment]
@hdefucom 
There is no officially supported way for customers to extend F1. However, the Visual Studio team might be interested in discussing scenarios like this for future product designs. I'd suggest entering an issue at [Dev Community](https://developercommunity.visualstudio.com/search?space=8)

**Comment by ghogen** [comment]
@BillWagner This is not actionable as a doc issue, so this can be closed here and tracked further if @hdefucom enters the issue as suggested. Thanks!
