### ISSUE TITLE
Juxtaposition Error in Insert[Before,After] Methods in XmlAttribute Collection Behavior Description

### ISSUE THREAD

**Issue by jkilfoil** [dotnet/docs#25915]
Are the insert position descriptions in this paragraph correct:

"These methods take, as a parameter, an existing node as a reference point to do the InsertBefore and InsertAfter. If you do not provide a reference node indicating where to insert the new node, the default for the InsertAfter method is to insert the new node at the beginning of the collection. The default position for the InsertBefore, if no reference node is provided, is at the end of the collection. . ."

One would think that the InsertAfter default insertion point would be at the _end_ of the collection and the InsertBefore default insert position would be at the _beginning_ of the collection.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2bf0dba-197e-3b54-b4b7-f20f5b10f503
* Version Independent ID: 6fead2b2-3d24-a90d-09ce-35cc5cc375c3
* Content: [Creating New Attributes for Elements in the DOM](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/creating-new-attributes-for-elements-in-the-dom)
* Content Source: [docs/standard/data/xml/creating-new-attributes-for-elements-in-the-dom.md](https://github.com/dotnet/docs/blob/main/docs/standard/data/xml/creating-new-attributes-for-elements-in-the-dom.md)
* Product: **dotnet-data**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I verified that the positioning information is actually correct as written, however, I don't think it applies to inserting attributes, meaning it doesn't seem that you can use `InsertBefore` and `InsertAfter` to insert attributes. I verified the positioning by inserting new nodes. To resolve this issue, I have a pull request that removes this paragraph from the article about inserting attributes.
