### ISSUE TITLE
Migration Guide --> Pre Migration --> Asses the portability of your project.  Should fix funny typo 'asses'.

### ISSUE THREAD

**Issue by joneal** [dotnet/docs#25918]
**Issue description**

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
Thanks for pointing this out @joneal 

I just opened a PR to fix this issue.
