### ISSUE TITLE
project file sample should make it clear you need to match an installed SDK version

### ISSUE THREAD

**Issue by Applesauce314** [dotnet/docs#25924]
step 4 of the document references creating a new project and provides the following
```
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.0.0" PrivateAssets="all" />
  </ItemGroup>
```
if you follow this example on a version that does not have the correct SDK, you get a CS8032 error.
this appears to be because the _generator project_ uses nuget to get the packages, the _build of the projects that reference_ the generator rely on the installed SDK to resolve the reference. This is not clear from any documentation I could find.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Applesauce314 We'll get this addressed.

Adding @mikadumont for visibility.
