### ISSUE TITLE
WarningsNotAsErrors Typo

### ISSUE THREAD

**Issue by Pinox** [dotnet/docs#25946]
The command should be -warnnotaserror  and not -warnaserror  in 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Pinox 

I've opened a PR to make the fix.  

In the future, if you find these types of issues, you may save some time by opening the PR yourself. Click the "edit" button (it looks like a pencil), and you can make the edits directly on GitHub and submit the PR.
