### ISSUE TITLE
conflicting/incomplete messaging about concept's output/behaviour

### ISSUE THREAD

**Issue by harshvchawla** [dotnet/docs#25941]
The 2nd paragraph of the example section says
> and generates an error when you assign to it.

however the example is showing an output (base class value is printed)

Should that be changed (or appended by something like "unless a base-class member can be accessed")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865bd72b-8d26-ec50-4fc0-e3754a00c00c
* Version Independent ID: 5607825a-87ff-1138-3743-0f1fd8408b16
* Content: [Restricting Accessor Accessibility - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @harshvchawla 

We'll get this addressed.
