### ISSUE TITLE
Breaking change to HttpClient - EmptyContent instead of null

### ISSUE THREAD

**Issue by gyphysics** [dotnet/docs#25953]
Please include breaking change to the response content of HttpClient described here:

https://nicolaiarocci.com/httpresponsemessage.content-is-non-nullable-in-net5/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f68af3a-3848-48ef-c24b-cf33b880ca1b
* Version Independent ID: 580c061d-20e5-248c-a24f-7a48a684c7e3
* Content: [Breaking changes in .NET 5 - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0)
* Content Source: [docs/core/compatibility/5.0.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/5.0.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gyphysics This is actually not a breaking change, at least in the way the .NET team defines breaking changes. Please see https://github.com/dotnet/runtime/pull/35910#issuecomment-912814054.
