### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by ranma42** [dotnet/docs#25964]
There is a typo in the table: "SequencePostion" instead of "SequencePosition" (repeated 4 times).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a7a159-0d11-531b-a444-cb154cd09967
* Version Independent ID: 73a2ecb2-17d6-4f36-4b59-5e3cf619edf1
* Content: [System.Buffers - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/buffers)
* Content Source: [docs/standard/io/buffers.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/buffers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by ranma42** [comment]
Isn't https://github.com/dotnet/docs/pull/25965 a valid PR for this?

**Comment by Rick-Anderson** [comment]
> Isn't #25965 a valid PR for this?

Looks like it. We're a bit slow reviewing PR's due to vacation and the .NET 6 push.

**Comment by ranma42** [comment]
No problem :) I was just afraid that your reply in https://github.com/dotnet/docs/issues/25964#issuecomment-913168487 meant that the PR was invalid or wrong in some way😅
