### ISSUE TITLE
preview for old code

### ISSUE THREAD

**Issue by ZACit** [dotnet/docs#25962]
[Is it possible to preview the old layout quickly with an action key command?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
If you want to see the old template, you can create a project that targets .NET 5 instead of .NET 6.

**Comment by tdykstra** [comment]
See #26313, where you can vote on the new template code.  Closing this issue in favor of that one.
