### ISSUE TITLE
ObjectDisposedException Class usage is not limited to IDisposable implementation

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25968]
**Issue description**

From [ObjectDisposedException Class|Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.objectdisposedexception?view=net-5.0#remarks)
> An [ObjectDisposedException](https://docs.microsoft.com/en-us/dotnet/api/system.objectdisposedexception?view=net-5.0) is thrown when you try to access a member of an object that implements the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=net-5.0) interface, and that object has been disposed.

From [IAsyncDisposable.DisposeAsync Method|Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable.disposeasync?view=net-5.0#remarks)
> Instance methods other than `DisposeAsync` can throw an [ObjectDisposedException Class](https://docs.microsoft.com/en-us/dotnet/api/system.objectdisposedexception?view=net-5.0) when resources are already disposed.

Thus ObjectDisposedException page have to denote also `IAsyncDisposable`.

**Comment by BillWagner** [comment]
Thanks for noting this @Uzivatel919 
I've added this to our backlog. and added the "up for grabs" label in case any community members want to submit a PR before we make the necessary updates.

**Comment by strobelt** [comment]
I created [PR 7282](https://github.com/dotnet/dotnet-api-docs/pull/7282) to fix this issue
