### ISSUE TITLE
IAsyncDisposable Interface | Remarks – bad link name (The Task asynchronous programming model in C#)

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#25967]
**Issue description**

> The async methods are used in conjunction with the `async` and `await` keywords in C# and Visual Basic. For more information, see [The Task asynchronous programming model in C# ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/) or [Asynchronous Programming with Async and Await (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/).

Link _The Task asynchronous programming model in C#_ links to article _Asynchronous programming with async and await_, at https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/, while _Task asynchronous programming model_ is at https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.

Its name is therefore _Asynchronous programming with async and await_.

**Comment by BillWagner** [comment]
Thanks for noting this @Uzivatel919 

There's no requirement for the link text to match either the title or the H1 of the target article.

I'll close this.
