### ISSUE TITLE
Not losing information but still using explicit

### ISSUE THREAD

**Issue by Alexees** [dotnet/docs#25977]
The page states that explicit conversions should be used when we loose information or throw an exception.
Since Digit uses byte as it's internal representation I don't see where we loose information here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aff7460-8328-4fb2-a857-40bce9a404e6
* Version Independent ID: 58b7e78e-ddd1-d102-f2e5-14e64a4d4ccd
* Content: [User-defined conversion operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators)
* Content Source: [docs/csharp/language-reference/operators/user-defined-conversion-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/user-defined-conversion-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Alexees according to the `Digit` constructor, when one tries to convert any `byte` value greater than 9 to `Digit`, an exception is thrown.

**Comment by Alexees** [comment]
@pkulikov You're absolutely right. Next time I double check, sorry for bothering.
