### ISSUE TITLE
How could I install preview release

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docs#25970]
Currently, I'm trying to install .NET 6 preview SDK, is there a way to install latest .NET preview release with command likes `apt-get install -y dotnet-sdk-5.0`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by svick** [comment]
It's not a single command, but you can follow [these instructions](https://github.com/dotnet/core/blob/main/release-notes/6.0/install-linux.md) to install .Net 6 SDK preview on any supported Linux distribution.

**Comment by WeihanLi** [comment]
Thanks @svick , and really hope for a single command to implement this.
