### ISSUE TITLE
Missed semicolon

### ISSUE THREAD

**Issue by dmytrostrembetskyi** [dotnet/docs#26006]
In this section, the semicolon is missed at the first line

```
object o  = "object"
dynamic d = "dynamic";

string s1 = o; // Fails at compile-time -- no conversion exists
string s2 = d; // Compiles and succeeds at run-time
int i     = d; // Compiles but fails at run-time -- no conversion exists
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be4c24e-9e92-6b75-2b8e-2cb6cb072b5b
* Version Independent ID: 450064c8-720e-3b90-18d6-7bd5f183857e
* Content: [Conversions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions)
* Content Source: [spec/conversions.md](https://github.com/dotnet/csharplang/blob/main/spec/conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @dmytrostrembetskyi 

I've fixed it in PRs in the Microsoft spec, and the ECMA draft standard.
