### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by MatrixArchitect** [dotnet/docs#26018]
The screenshots for creating an asp.net core project that uses the ASP.NET Core Identity schema are out of date over here:

https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/security-authentication-authorization

The visual studio options and workflow for creating projects and referencing/configuring ASP.NET Core Identity schema have changed.

I hope updating this page would save people some headaches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f409095-6911-fe60-5c0b-f53f85dbd237
* Version Independent ID: 665cca1b-d2fe-41f9-1247-17c9297e2f2d
* Content: [Security: authentication and authorization in ASP.NET Web Forms and Blazor](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/security-authentication-authorization)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/security-authentication-authorization.md](https://github.com/dotnet/docs/blob/main/docs/architecture/blazor-for-web-forms-developers/security-authentication-authorization.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @ardalis
* Microsoft Alias: **daroth**

**Comment by BillWagner** [comment]
Thanks @erjain 

I'll close this.
