### ISSUE TITLE
IMetaDataAssemblyImport::FindAssembliesByName description incorrect on summary page

### ISSUE THREAD

**Issue by Lexikos** [dotnet/docs#26022]
The summary page for this interface says
> FindAssembliesByName Method | Gets an array of **mdAssemblyRef tokens** for the assemblies with the specified name.

but it does not return tokens; it returns IMetadataAssemblyImport interface pointers (as `IUnknown *`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3c1a82f-2418-22fb-3d0e-78c7f84a8fd1
* Version Independent ID: 8f8ba09d-e154-7315-dae5-1524cefe9fc4
* Content: [IMetaDataAssemblyImport Interface](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataassemblyimport-interface)
* Content Source: [docs/framework/unmanaged-api/metadata/imetadataassemblyimport-interface.md](https://github.com/dotnet/docs/blob/main/docs/framework/unmanaged-api/metadata/imetadataassemblyimport-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Thanks @Lexikos!
