### ISSUE TITLE
[WinForms] API validate if the ListVIew is in virtual mode and throws an InvalidOperationException

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/docs#26021]
## Selected API validate if the ListVIew is in virtual mode and throws an InvalidOperationException.

Selected API validate if the `ListVIew` is in virtual mode and throws an `InvalidOperationException` where previously a `InvalidOperationException` could be thrown, if the APIs were invoked for the `ListView` in virtual mode and with the created `Handle`.
The new `InvalidOperationException` is more obvious to developers. In addition, it closes a workaround where the developer could add a `ListViewGroup` to the `ListView` before the `Handle` was created.

## Old behavior
The listed API would throw `InvalidOperationException` if invoked for `ListView` is in virtual mode and with the created `Handle`.
![image](https://user-images.githubusercontent.com/23376742/132668660-2a60dc34-5fc1-4ef4-81cb-9f3ae370dcf4.png)

## New behavior
The listed API would throw `InvalidOperationException` if invoked for `ListView` is in virtual mode.
![image](https://user-images.githubusercontent.com/23376742/132668735-06073772-d03d-4cbe-bb9d-d6cd3ff0695c.png)

## Reason for change
Remove the workaround that allowed a developer to add a `ListViewGroup` to a `ListView` in virtual mode. Make the `InvalidOperationException` more understandable for the developer.

## Recommended action
- Review and, if necessary, update the code to prevent the `ListViewGroup` from being added to the `ListView` in virtual mode in the listed API.
- If the code is handling `ArgumentNullException` replace (or supplement) it with handling `ArgumentNullException` with more friendly message.

## Category
- Windows Forms

## Version introduced: .NET 6.0 RC2 + 7.0 Preview1
Affected APIs
- [ListViewGroupCollection](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroupcollection)
    - [ ] [Add](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroupcollection.add) when the `ListView` is in virtual mode
    - [ ] [AddRange](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroupcollection.addrange) when the `ListView` is in virtual mode
    - [ ] [Insert](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroupcollection.insert) when the `ListView` is in virtual mode

**Comment by dreddy-work** [comment]
@carlossanlop, This change is for .NET 6.0.  what are the timelines to see the doc updated here? I see Pri3 label added automatically.

**Comment by gewarren** [comment]
@dreddy-work This is for RC 2, correct? I can write it up today so that it gets published by tomorrow morning. Is that okay? We usually publish early morning PST M-F.

**Comment by dreddy-work** [comment]
> @dreddy-work This is for RC 2, correct? I can write it up today so that it gets published by tomorrow morning. Is that okay? We usually publish early morning PST M-F.

Yes. RC2 works.
