### ISSUE TITLE
Instructions don't work in the new VS 2022 UI

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#26033]
> You can enable or disable code analysis by right-clicking on a project in Solution Explorer and selecting Properties > Code Analysis tab > Enable .NET analyzers.

Here is how the properties window look in VS 2022 as of Preview 3.1

![image](https://user-images.githubusercontent.com/31348972/132799749-f0fc7429-a8bb-49f8-aef0-c6fa4a3c1865.png)

Here is how it looks in VS 2019

![image](https://user-images.githubusercontent.com/31348972/132800530-49c5eaef-0d8d-4976-b827-47c1a47a21b9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55
* Version Independent ID: 128f9903-971d-6a66-a2cb-9b12acbc55e7
* Content: [Code analysis in .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview)
* Content Source: [docs/fundamentals/code-analysis/overview.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
cc @drewnoakes

**Comment by drewnoakes** [comment]
In preview 4 there is a new code analysis page, not seen in the VS2022 screenshot above.

It would be great to get the docs updated.
