### ISSUE TITLE
Dotnet build command options incorrect, or broken (-c, -a, etc)

### ISSUE THREAD

**Issue by npatellaoz** [dotnet/docs#26038]
`dotnet build` rejects command line options such as "-a/--arch" and "-c/--configuration". These are documented on the page for `dotnet build` I am not sure if it was broken or removed intentionally, since you can use /p: properties to configure them directly in MSBuild.

For example, if I pass `-a x64`:
```
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: -a
```

[BuildCommand.cs](https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-build/BuildCommand.cs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
@npatellaoz hello. This command switch requires .NET 6 Preview 7 or newer. I suspect you're running with an older SDK. I'm going to close this issue since I'm 99% sure that is the problem. I tested with .NET 5/2.1 and they failed with the error you specified. .NET 6 worked for me.
