### ISSUE TITLE
Confusion about the internal access modifier

### ISSUE THREAD

**Issue by jackytank** [dotnet/docs#26047]
[Enter feedback here]

When I created 2 .cs files, the first one have 1 internal class and 1 internal member field. As the doc said you can't create an object of an internal class from different .cs file but I still can instantiate the first class and access the internal member field 
![image](https://user-images.githubusercontent.com/52403567/132920034-ab0f516b-d6c4-4955-9a37-71fa8f900d5b.png)
![image](https://user-images.githubusercontent.com/52403567/132920070-6c9d1354-3876-4d16-969e-a8e8beb44f8f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac43c546-b79a-a4cb-6b59-7037334b83e0
* Version Independent ID: 4926fa62-f791-dc1a-7c09-7b268180d20e
* Content: [internal - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal)
* Content Source: [docs/csharp/language-reference/keywords/internal.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/internal.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the note @jackytank 

The article is correct. It states that code must be in the same *assembly* to access a type or member declared with `internal`. That's not the same *file*. All files compiled together in the same DLL are part of the same assembly.

Closing.
