### ISSUE TITLE
[Breaking change]: MSBuild 17 no longer supports calling GetType()

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#26048]
### Description

MSBuild 17 no longer supports calling the `GetType()` instance method within property functions. This allowed unpredictable code execution during evaluation and could cause Visual Studio hangs.

### Version

.NET SDK 6.0.100-rc1

### Previous behavior

`GetType()` calls in MSBuild property functions would execute sometimes causing unpredictable behavior in VS.

### New behavior

An error during project evaluation `The function "GetType" on type "System.String" is not available for execution as an MSBuild property function.`

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

This functionality was not documented and not commonly used. It caused performance and reliability issues with project loading, especially in Visual Studio.

The only known common use of this was in the [CBT](https://commonbuildtoolset.github.io/) system which has been deprecated.

### Recommended action

Replace any calls to `GetType()` with alternate MSBuild logic.

### Feature area

SDK

**Comment by gewarren** [comment]
We could possibly just link here (https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#assembly-info-generation-properties) and update that section, if necessary.
