### ISSUE TITLE
C# 8.0 snippet contains C# 9.0 language feature

### ISSUE THREAD

**Issue by no-stack-dub-sack** [dotnet/docs#26044]
The following snippet is found near the top of the page and is preceded by the quoted text:

> This method was originally written before C# 8.0 and nullable annotations:

```csharp
bool TryGetMessage(string key, out string message)
{
    if (_messageMap.ContainsKey(key))
        message = _messageMap[key];
    else
        message = null;
    return message is not null;
}
```
This is a bit misleading because its my understanding that the expression `message is not null` found on the last line [is a C# 9.0 feature](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#pattern-matching-enhancements), and previous to C# 9 would have had to be written as `return !(message is null)` or `return message != null`. This is not a huge deal but led to a few minutes of confusion and research before I was fully convinced that this was a small mistake.

Apologies in advance if I'm mistaken.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
good catch @no-stack-dub-sack 

I've just opened #26078 to fix this.
