### ISSUE TITLE
Compiler Warning (level 1) CS0465 – destructor is outdated term

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#26065]
Regard [Finalizers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors) is _destructor_ former naming.

> Finalizers (historically referred to as destructors) are used to perform any necessary final clean-up when a class instance is being collected by the garbage collector.

**Compiler Warning (level 1) CS0465**
> Do not override object.Finalize. Instead, provide a destructor.
> If such a class is used as a base class and if the deriving class defines a destructor, the destructor will override the base class Finalize method, not Finalize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93138196-598c-7726-1b74-4cb6e4b302a3
* Version Independent ID: 53f17a1d-75c8-7fe6-1b0c-7893ae6fc0c4
* Content: [Compiler Warning (level 1) CS0465](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0465?f1url=%3FappId%3Droslyn%26k%3Dk(CS0465))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0465.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0465.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Uzivatel919 

I've added this to our backlog to address when we next update this article.

I've also added the "up-for-grabs" label on this and similar issues. There are likely many occurrences of *destructor* when the current preferred term is *finalizer*. The ECMA committee made decided to prefer the term "finalizer" over "destructor" during the C# 5.0 edits. That version was formally adopted in December 2017. 

We'd appreciate any PRs that make updates to these terms.
