### ISSUE TITLE
To correct this error I suggest a third option

### ISSUE THREAD

**Issue by RobEin** [dotnet/docs#26066]
To correct this error I suggest a third option: 
var (a, b) = (3, 2);  // tuple deconstructing

https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#tuples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66fa4820-72ac-0426-dbd2-4b00287117b8
* Version Independent ID: 9fbbd37d-486e-6cec-8a2a-f19ac22482ff
* Content: [Compiler Error CS0819](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0819)
* Content Source: [docs/csharp/misc/cs0819.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0819.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @RobEin 

I've added this to our backlog, and added the "up for grabs" label to this issue.

**Comment by RobEin** [comment]
Maybe one more useful example or a curiosity where this multiple var declaration with tuple can be useful.

```
// no optimization
for (var i = 0; i < lst.Length; i++)


// optimization with hoisting
var length = lst.Length; 
for (var i = 0; i < length; i++)


// optimization with hoisting and encapsulation
for (var (i, length) = (0, lst.Length); i < length; i++)

```
