### ISSUE TITLE
Mention of .NET Core 3.1 on this page is not clear

### ISSUE THREAD

**Issue by dkhopade** [dotnet/docs#26060]
This page mostly talks about .NET Core 5.0, but the Mention of .NET Core 3.1 on this page is not clear. Please see the below screenshot.
<img width="1025" alt="Screen Shot 2021-09-11 at 12 40 01 PM" src="https://user-images.githubusercontent.com/10272355/132955071-c4a8cfa7-0129-4b59-9ddc-aa802864f223.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
@dkhopade Thanks for reporting this. That was a miss from our end. We will update it quickly. 
cc @sughosneo
