### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by eersonmez** [dotnet/docs#26076]
The page says "The null-forgiving operator, the ! character following the default expression tells the compiler that the preceding expression is not null."  This is not correct.  It says to go ahead and assign null to those properties on construction (despite the fact that they're non-nullable).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313ec178-bb7c-e6be-0760-f7db427b464c
* Version Independent ID: ac631425-4ff7-850c-9fa7-127ff7a9ac06
* Content: [Upgrade to nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/upgrade-to-nullable-references)
* Content Source: [docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @eersonmez 

I'm in the process of making updates in this area now. I'll add these updates to that task.

**Comment by BillWagner** [comment]
Fixed in #26046
