### ISSUE TITLE
Helpful explanation of Async and Await

### ISSUE THREAD

**Issue by gerard7890** [dotnet/docs#26075]
[Enter feedback here]
This was very helpful thanks. It made me really understand how this works. And gave me enough details to also experiment a bit more on my own. 
The only thing I would add is that the WhenAny() method doesn't break on an IsFaulted task. That might not be obvious to people unless they try that out or carefully read the documentation of WhenAny.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#final-version)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @gerard7890 

Closing as kudos.  (For this article, I'd rather not dive into the nuances of `WhenAny`, or other APIs used.)
