### ISSUE TITLE
Finalizers (C# Programming Guide) – note haziness 

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#26074]
From [Remarks](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors#remarks)

> Note
>Empty finalizers should not be used. When a class contains a finalizer, an entry is created in the Finalize queue. When the finalizer is called, the garbage collector is invoked to process the queue. An empty finalizer just causes a needless loss of performance.

Let examine sentence “_When the finalizer is called, the garbage collector is invoked to process the queue._”.

AFAIK, **GC** is what processes _finalize queue_, thus calls `object` _finalizer_. FMPOV there is no way _finalizer_ is called in way that would invoke **GC** action.

Right bellow note is stated
>The programmer has no control over when the finalizer is called; the garbage collector decides when to call it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Uzivatel919 

Those sentences should be reworded somewhat.

**Comment by shilpikundu16** [comment]
hey, I can work on this.
