### ISSUE TITLE
Example seems to be wrong `SampleImplementation<Button> button = new SampleImplementation<Button>();`

### ISSUE THREAD

**Issue by prashantchoudhary** [dotnet/docs#26092]
In the section,

`Classes that implement variant interfaces are invariant. For example, consider the following code.`

There is this example,
```
// The interface is covariant.
ICovariant<Button> ibutton = new SampleImplementation<Button>();
ICovariant<Object> iobj = ibutton;

// The class is invariant.
SampleImplementation<Button> button = new SampleImplementation<Button>();
// The following statement generates a compiler error
// because classes are invariant.
// SampleImplementation<Object> obj = button;

```

I believe this is a mistake and it should have been
```
SampleImplementation<object> button = new SampleImplementation<Button>();
```
As the original example has no variance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada3150a-24a0-a90c-f7aa-ea1ca47d7487
* Version Independent ID: 8cfde752-8d67-5975-00ed-649edce36733
* Content: [Creating Variant Generic Interfaces (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @prashantchoudhary 👋 

The original sample is correct. You can see for yourself in this [sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAAwCwAUEQIwUUD0dABACoAWApo7Au8gGYQAxpygBnRoID2ANwjIoEGAgB0FAJIBhGXIVKAPACFUCBJJgA+LsGOmYjALyMY7AO6MAyhDAAHADbs1H38wdiUIBCgzQxszcwAKAEoAbnUtWXlFBD0AeWAAK3ZBBEtI/IcrGJgU8nomNk4iLnFYdN0VCk8ggK6QsIiooxNYxmshu0dnN06/bpnehHDImGix+OTalg5GPklfX0kXWABzRlEFnnnGI9DecPZxCAlJHyh/ZEZeZElkDeBCiFQogahHujDkIhgrUyqnI038gTmoXOSxy+UKxUYkjKjlGtmqFEag1sjAA3gBfCiMKmMCjcXgCYSMTTaDL6STGRgAJXMFBJlOpnMYAHF2Ah3M9RaxjolqhTKIQPF4ZgjgkjFlFuYwQEy0jpMnpubz+VT8ABmLnC0XikIIKUwI6JY2kp3UxgMDwSp4Ydgw12u/AAdkY3oEqF8CDinPW5FdcrlFCAA=) gist.  I'll close this.

I do want to point out that your alternative is also correct though.

**Comment by prashantchoudhary** [comment]
Oh I realize my mistake now. As the suggested code was commented out I missed that.
