### ISSUE TITLE
Show imports for code snippets in the documentation

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#26108]
---
**Issue moved from MicrosoftDocs/feedback#3686**
- Please respond to @orjandh.

---

_From @orjandh on Monday, September 13, 2021 1:04:02 PM_

**Is your feature request related to a problem? Please describe.**
When using code snippets from, for example, the .Net core documentation, I often have to do some light detective work to find which packages the different classes comes from.

**Describe the solution you'd like**
I would like the information about which packages the different classes used in the code snippets to also be present on the documentation page.

**Describe alternatives you've considered**
One alternative could be to have a tab in the code snippet that shows the imports.
Another alternative can be to have hyperlinks to the class reference when you click or hover over them in the code snippet,

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3686**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Monday, September 13, 2021 1:04:03 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by tdykstra** [comment]
Which article does this refer to?
