### ISSUE TITLE
Add .Net on Debian 11 installation and support details

### ISSUE THREAD

**Issue by tylerkelly13** [dotnet/docs#26106]
Notice that this page needs to be updated to include the latest stable version of [Debian (11)](https://www.debian.org/releases/)

```
wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
```
returns a 200 HTTP response, indicating the package is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
There is an open PR for this 😄

**Comment by adegeo** [comment]
Fixed! Cheers.
