### ISSUE TITLE
Create project into existing solution?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#26113]
Hi,

Please include or link information on how to create new projects (from template) into an existing solution.

[Related](https://github.com/dotnet/docs/issues/26114)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Use `dotnet new` and then `dotnet sln add`. See the [dotnet sln examples](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#examples), especially the last example.

**Comment by weitzhandler** [comment]
Thank you!
