### ISSUE TITLE
How to add to solution a project from template?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#26114]
Hi,

Can you please expand the docs to include information on how to add a new project from a template into an existing solution?

[Related](https://github.com/dotnet/docs/issues/26113)

For example:

```
dotnet new unoapp-winui -o MyApp
```

The new project(s) template of above should be added to an existing solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See the [Examples section](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#examples), especially the last example.

**Comment by weitzhandler** [comment]
That answers my question.
Thank you
