### ISSUE TITLE
Assembly security considerations - should be moved to .NET Framework guide?

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [dotnet/docs#26116]
The Assembly security considerations article is in .NET Fundamentals, but it mentions mostly .NET Framework-only concepts: Code Access Security, evidences and strong-name signing. It also links to Windows-only SignTool docs. Should it be moved to .NET Framework section of docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27cb477-9596-5595-3d15-260e6a83b25d
* Version Independent ID: ebe60e74-87b8-f4b7-eb15-083b665ae93f
* Content: [Assembly security considerations](https://docs.microsoft.com/en-us/dotnet/standard/assembly/security-considerations)
* Content Source: [docs/standard/assembly/security-considerations.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/security-considerations.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by MSDN-WhiteKnight** [comment]
My concern is only that it's inconsistent, other .NET Framework-only articles are split to .NET Framework section, for example [Application domains](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/application-domains). If it was kept here on purpose, fine. The certificate signing part is probably relevent to .NET Core too, just the tool for signing is still Windows-only.

**Comment by IEvangelist** [comment]
The framework design guidelines content is protected content that we're not allowed to update. Closing this issue, as we cannot take action on it.
