### ISSUE TITLE
`override` keyword is not valid for interfaces

### ISSUE THREAD

**Issue by llRandom** [dotnet/docs#26115]
There's a section 'Overrides in interfaces' that provides the following code example:
```
interface IA
{
    void M() { Console.WriteLine("IA.M"); }
}
interface IB : IA
{
    override void IA.M() { Console.WriteLine("IB.M"); } // explicitly named
}
interface IC : IA
{
    override void M() { Console.WriteLine("IC.M"); } // implicitly named
}
```
It doesn't work because `override` keyword is not valid for interfaces. Compiler gives this error:
```
CS0106	The modifier 'override' is not valid for this item
```
 It only works without `override` keyword:
```
    interface IA
    {
        void M() { Console.WriteLine("IA.M"); }
    }
    interface IB : IA
    {
        void IA.M() { Console.WriteLine("IB.M"); } // explicitly named
    }
    interface IC : IA
    {
        void M() { Console.WriteLine("IC.M"); } // implicitly named
    }
```
The project is targeting .Net 5 and C# 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17012c83-0313-919b-eb8b-04fae8f4df4a
* Version Independent ID: 05252e5a-e53c-5ce5-84b3-671faad0549c
* Content: [Default interface methods - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods)
* Content Source: [proposals/csharp-8.0/default-interface-methods.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @jcouv @333fred 

How should this proposal be updated?

**Comment by 333fred** [comment]
@AlekseyTs

**Comment by AlekseyTs** [comment]
> How should this proposal be updated?

It shouldn't mention the ```override``` keyword. Interface members cannot be overridden, they can be implemented. A derived interface can implement a member from its base interface, the regular explicit implementation syntax should be used for that purpose.

**Comment by HermanEldering** [comment]
I ran into this today. This issue doesn't seem to get much attention, so while this is on the backlog perhaps it is good to at least add a note to this section that the information there is incorrect?
