### ISSUE TITLE
Operator precedence for x?.y seems to be listed wrong

### ISSUE THREAD

**Issue by initram** [dotnet/docs#26112]
Under the section "Operator precedence" the following are listed as having equal precedence: "x.y" and "x?.y"
Also none of them are listed as being right associative.

This would then mean that the following two lines should be semantically identical:

`var x = a.b?.c.d;`
`var x = (a.b?.c).d;`

This how ever is not how the language works! 
The first example will never try to access d on c if b is null. The final result will simply be null if b is null.
in the second example it will try to access d on the result of the expression in parentheses, even if b is null. (resulting in a null reference exception if b is null)

I am not sure exactly where in the precedence hierarchy "x?.y" belongs, but at least lower than primary expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @initram 

Ill add this to our backlog pending work currently in progress in the ECMA standards committee. The committee is evaluating two different strategies for the normative language in this feature:

- dotnet/csharpstandard#7
- dotnet/csharpstandard#251

Once one of those is merged, we'll update this article to match.

**Comment by pkulikov** [comment]
@initram @BillWagner there is some history about the precedence of the null-conditional operator (once it was moved away from the primary row but then returned back):
#18037
#18001 (that one contains a discussion about the operator precedence)

**Comment by gafter** [comment]
Your assertion that `var x = a.b?.c.d;` should mean the same thing as `var x = (a.b?.c).d;` only works if `a.b?.c` is a subexpression of the former.  But it isn't a subexpression of the former (even though it is a substring of the former).

**Comment by BillWagner** [comment]
Adding this to the sprint as I'm making other changes in the same file.

**Comment by BillWagner** [comment]
Already fixed in #34945.

Closing.
