### ISSUE TITLE
Update tutorial for changes to implicit usings in .NET 6 rc.1

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs#26146]
A few things have changed in rc.1 which impact this document, which was introduced as part of template changes originally made in preview.7:
- The default set of included usings in new console projects does not include `System.Net.Http.Json`
- Implicit usings are now opt-in rather than opt-out. The property to opt-in is `<ImplicitUsings>enable</ImplicitUsings>` which is added to new .NET 6 projects by default
- The namespaces can be controlled further via the `<Using>` item type in the .csproj file, e.g. to remove an implicitly included namespace you can add `<Using Remove="System.Net.Http" />`

FYI @KathleenDollard 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @BillWagner @adegeo

**Comment by adegeo** [comment]
@DamianEdwards I'm also seeing that `System.Threading.Tasks` is included.
