### ISSUE TITLE
integral type?

### ISSUE THREAD

**Issue by fit-to-git** [dotnet/docs#26154]
There seems to be a mistake in the following expression, "around an **integral** type". Shouldn't it be **integer**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sputier** [comment]
I guess the word **integral** has been favored here to avoid misleading indications: a C# beginner could easily understand that enumerations can be used to **only** wrap `integer` values. As the backing value of an enumeration can be of type `byte`, `short`, `ushort` and other non-decimal types (i.e. other integral types), the expression "around an integral type" looks good to me.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
