### ISSUE TITLE
Client side configuration of long polling does not work

### ISSUE THREAD

**Issue by oiBio** [dotnet/docs#26158]
Cant enable Long Polling with the provided work around in rc1.

when i insert the client side code i get an error: 

```
Uncaught (in promise) Error: Blazor has already started.
    at Object.Kn [as start] (blazor.server.js:1)
    at start (localhost/:59)
    at localhost/:62
```

full _Layout.cshtml of the starting template:
```

@using Microsoft.AspNetCore.Components.Web
@namespace BlazorApp3.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="BlazorApp3.styles.css" rel="stylesheet" />
    <component type="typeof(HeadOutlet)" render-mode="Server" />
</head>
<body>
    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    
    <script src="_framework/blazor.server.js"></script>
    <script>
        (function start() {
            Blazor.start({
                configureSignalR: builder => builder.withUrl('_blazor', 1 | 4) // WebSockets and LongPolling
            });
        })()
    </script>
</body>
</html>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f41f72-9607-cf69-ba74-a13b0ba7c287
* Version Independent ID: ef609510-d010-8cd5-fbd6-b056fd5f1744
* Content: [Breaking change: Blazor server: Disable LongPolling fallback transport - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TanayParikh** [comment]
Could you please add `autostart="false"` as an attribute to the server.js script. 

```js
<script src="_framework/blazor.{webassembly|server}.js" autostart="false"></script>
```

**Comment by oiBio** [comment]
Can confirm. 
with autostart="false" it works as expected

// leaving issue open, so docs can be fixed
