### ISSUE TITLE
.NET Core 2.1 is no longer supported.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#26160]
Needs some update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01848ba-0d62-c070-ee2a-9b43e3966985
* Version Independent ID: 0dadd1f3-1d08-37e1-2215-b8ea40b49c0c
* Content: [Migrate to ASP.NET Core 2.1](https://docs.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/migrate-aspnet-core-2-1)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/migrate-aspnet-core-2-1.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/migrate-aspnet-core-2-1.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by tdykstra** [comment]
@Rick-Anderson 

>Needs some update

What update does it need? This is a what's new for 2.1, so the content should still be accurate since 2.1 hasn't changed. Are you suggesting we retire the what's new docs for no-longer-supported versions, i.e., 2.0, 2.1, 2.2, and 3.0?

**Comment by Rick-Anderson** [comment]
I would at least remove it from the TOC
![image](https://user-images.githubusercontent.com/3605364/144912906-af5ad01f-c769-4d2d-9d8e-a9baf08674bb.png)

**Comment by ardalis** [comment]
It's true it's no longer supported and that will be updated in the revision coming imminently. However, it's still a reasonable incremental step for customers to take on the path to a supported version if they're coming from .NET Framework. As such, my intention is to leave the chapter but update the text and include some strong Note/Warning boxes indicating that the migration is meant to be an interim one only, as it is no longer a supported framework.

**Comment by ardalis** [comment]
Fixed in https://github.com/dotnet/docs/pull/27512

**Comment by ardalis** [comment]
This was merged into main - probably can be closed.
