### ISSUE TITLE
Async Suffix for method names

### ISSUE THREAD

**Issue by deisbel** [dotnet/docs#26167]
Hi, this article date from Feb 2019. I'm wondering if, two years later in 2021, using the Suffix Async for the methods returning a Task still makes sense. 

I mean, I think that in a Service or Repository class, for example, having all the methods returning Task<> is a little bit redundant using the suffix Async. 

What is your opinion about it today?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40c0699-0e7c-e20d-98c1-76f0520ab9c2
* Version Independent ID: 0fc31902-0055-f9e8-a228-e7a0ce384e35
* Content: [Task-based Asynchronous Pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap?redirectedfrom=MSDN)
* Content Source: [docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md](https://github.com/dotnet/docs/blob/main/docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@IEvangelist Do you want to weigh in on this?

**Comment by IEvangelist** [comment]
Thank you @gewarren, yes—I'd live to weigh in on this.

I believe that it is still relevant and will remain relevant for the foreseeable future. Part of establishing a convention is building a consistent experience. In .NET, most (if not all) of the runtime code that exposes async APIs (returning task-like types) uses the Async suffix. Despite being that this article hasn't updated in a bit, these naming conventions are still valid.

But here's the thing, you're not required to follow them. These are suggestions, guidelines, and patterns that have been established with good reason. If you choose to follow these conventions, your code will be more consistent with other .NET code.

**Comment by gewarren** [comment]
Thanks @IEvangelist. I'll close this issue now.
