### ISSUE TITLE
add [FromBody] tag to endpoint paramenters

### ISSUE THREAD

**Issue by antonio-schlappa-motioncx** [dotnet/docs#26173]
I think endpoint parameters should have [FromBody] tag to parse the data variable from messages

public async Task<ActionResult> CreateOrder(Order order)
should be:
public async Task<ActionResult> CreateOrder([FromBody] Order order)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d1c385-3546-7612-b8b1-4231681dca8a
* Version Independent ID: 497a2367-15d7-6be0-7974-1415e3402b08
* Content: [The Dapr publish & subscribe building block](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/publish-subscribe?source=docs)
* Content Source: [docs/architecture/dapr-for-net-developers/publish-subscribe.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/publish-subscribe.md)
* Product: **dotnet-architecture**
* GitHub Login: @EdwinVW
* Microsoft Alias: **nanil**

**Comment by EdwinVW** [comment]
Thanks for reading the book and noticing this @antonio-schlappa-motioncx !
The `[FromBody]` attribute is not necessary in this case. The default model-binding behavior will automatically match the JSON payload in the body with the `Order` parameter.

**Comment by antonio-schlappa-motioncx** [comment]
You're right, I tried again and it worked!
in a previous test without `[FromBody]`, I received the object with its default properties
![image](https://user-images.githubusercontent.com/81968651/133731399-9e036180-be02-40c5-8d9e-abbe79a3e8c5.png)

**Comment by antonio-schlappa-motioncx** [comment]
in a new project, the value is deserialized correctly regardless of whether you use `[FromBody]` or not

![image](https://user-images.githubusercontent.com/81968651/133732211-8597458d-3a77-4d4b-a730-65cb38a88d52.png)

![image](https://user-images.githubusercontent.com/81968651/133732243-be3e7c30-9538-4081-aaf5-ae4405a0424d.png)

**Comment by antonio-schlappa-motioncx** [comment]
Thanks for the help,
have a good day!
