### ISSUE TITLE
TreatWarningsAsErrors does not behave like /warnaserror

### ISSUE THREAD

**Issue by ohadschn** [dotnet/docs#26199]
The page implies that these are two syntax forms to do the same thing, when in fact they differ in at least 2 regards:
1. `/warnaserror` promotes ALL msbuild warnings to errors, whereas `TreatWarningsAsErrors` only affects compiler (`csc`) warnings 
2. `/warnaserror` generates output even in the face of errors, whereas `TreatWarningsAsErrors` does not

More details: https://stackoverflow.com/questions/54771043/treatwarningsaserrors-vs-warnaserror

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this. I've added it to our backlog to address.

**Comment by ohadschn** [comment]
@BillWagner thank you!

BTW while this is indeed a documentation issue where things currently stand, IMHO ideally msbuild would be modified so that they actually behave the same. 

I think it goes without saying that the `warnaserror` behavior regarding MSBuild warning promotion (namely - they are promoted) would be preferable - or even better, make msbuild warning promotion configurable.

As for output generation, I would personally opt for the `TreatWarningsAsErrors` behavior (namely, don't generate output on warnings promoted to errors).

**Comment by BillWagner** [comment]
@chsienki See previous comment.
