### ISSUE TITLE
👍

### ISSUE THREAD

**Issue by MohammadRoshani** [dotnet/docs#26191]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET version to use - .NET](https://docs.microsoft.com/en-us/dotnet/core/versions/selection)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/main/docs/core/versions/selection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! I'm assuming this issue is a "thank you" or "good job" or "like this article" so I'm going to close the issue. Thanks!
