### ISSUE TITLE
Platform invoke confusion

### ISSUE THREAD

**Issue by FrankAtHexagon** [dotnet/docs#26210]
The _Strings Used in Platform Invoke_ section says the following:
> Platform invoke copies string arguments, converting from the .NET Framework format (Unicode) to the platform unmanaged format.

However, the _String parameters_ section on the [Native interoperability best practices](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices) page says the following:
> When the CharSet is Unicode or the argument is explicitly marked as `[MarshalAs(UnmanagedType.LPWSTR)]` _and_ the string is passed by value (not `ref` or `out`), the string will be pinned and used directly by native code (rather than copied).

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25d350b8-a514-6c13-a091-0952a8fc0610
* Version Independent ID: 3ee9bbfd-2060-d97f-c2f1-12867899034a
* Content: [Default Marshaling for Strings](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings)
* Content Source: [docs/framework/interop/default-marshaling-for-strings.md](https://github.com/dotnet/docs/blob/main/docs/framework/interop/default-marshaling-for-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@jkoritzinsky Can you answer this one?

**Comment by jkoritzinsky** [comment]
The best practices document is the correct one in this case.

**Comment by FrankAtHexagon** [comment]
Thanks for getting back to me. On a related note, is the unmanaged code responsible for freeing the string's memory? I've looked through all of the documentation and haven't been able to find anything.

**Comment by jkoritzinsky** [comment]
No. Unmanaged code is only responsible for releasing the memory in the by-ref case if it assigns a new value. In that case, the native code needs to release the memory for the old value. Otherwise, the runtime owns the memory (and will release it after the call).

**Comment by FrankAtHexagon** [comment]
Great, thanks for answering. I wasn't able to find this documented anywhere, I would encourage it to be added somewhere.

**Comment by FrankAtHexagon** [comment]
Thank you for fixing this! 😄
