### ISSUE TITLE
Default thresholds for CA1506 Class Coupling

### ISSUE THREAD

**Issue by mradckeIRT** [dotnet/docs#26215]
It would be helpful to know what the default thresholds for this code metric are. We are using the custom thresholds

CA1506(Type): 80
CA1506(Method): 20

but would like to check back with the current defaults.

Best regards
MRA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6bc7ccb-aab7-7e71-f5c5-82cd8fbef17f
* Version Independent ID: b5a70070-37a7-68ee-3ef4-969c961f4486
* Content: [CA1506: Avoid excessive class coupling (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1506#feedback)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1506.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1506.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Do you know what the default thresholds for class coupling are?

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-analyzers/blob/e52a3f1c0b45684ddaa041f26a980fa451ea9001/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzer.cs#L266-L278
