### ISSUE TITLE
GitHub action agents support .NET natively

### ISSUE THREAD

**Issue by lbugnion** [dotnet/docs#26218]
The page at https://docs.microsoft.com/dotnet/devops/create-dotnet-github-action states

> Since .NET is not natively supported by GitHub Actions, the .NET app needs to be containerized. For more information, see Containerize a .NET app.

This is incorrect, currently [GitHub action agents running Ubuntu support .NET 2.1 through 5.0 natively](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md). I would recommend reworking this page to remove the Docker part (which adds unnecessary complexity to the sample), while precising that the Docker option is also possible for those who prefer it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c32d49db-bd6c-c5db-96c9-fe426191d6ca
* Version Independent ID: 491a0389-f24d-a398-4496-873461b6180d
* Content: [Tutorial: Create a GitHub Action with .NET](https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action)
* Content Source: [docs/devops/create-dotnet-github-action.md](https://github.com/dotnet/docs/blob/main/docs/devops/create-dotnet-github-action.md)
* Product: **dotnet**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @lbugnion - while the action environments do have support for .NET, their documentation about the available types of supported GitHub Actions are only Docker Containers, JavaScript, and Composites. See [About custom actions: Types of actions](https://docs.github.com/actions/creating-actions/about-custom-actions#types-of-actions). 

Were you able to prototype an .NET action that is actually runnable? If so, please share with me and I'll certainly make the changes. If you're unable to provide a working example, I'll try to do so myself - but it might be a little while before I have time.

**Comment by lbugnion** [comment]
Hi @IEvangelist 

Here's an example where you can run a .NET console application in the context of an action without containerizing it. In the example below, SimpleFile is a folder container a CSPROJ file. It's inspired from your example (you may recognize some parts of it). In this example I am using .NET to create/update a new MD file when there is a new PR. I omitted the code used to update the PR.

`name: SaveFile

on:
  pull_request:
    branches:
      - master
    paths:
    - 'test-actions/**'         # run on all changes to this dir
    - '!test-actions/output.md' # ignore this file

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd SimpleFile
          dotnet restore
          
      - name: Run SimpleFile
        run: |
          cd SimpleFile
          dotnet run -c Release

# Here would be code to update the PR`

**Comment by IEvangelist** [comment]
Ah, yes. This is the direction I assumed you were going.

The key difference between a single `jobs/step` that calls `run` and an official GitHub Action is the _action.yml_. This enables the action to be published to the GitHub Action marketplace, enables theming, descriptions, discoverability, formalized (and typed) inputs and outputs, etc. Simply calling a .NET app from `run` is not the same as what is capable with a containerized .NET app running as a GitHub Action.

Does that make sense? But to your point, it is probably worth adding content around custom .NET consoles apps being called from `run` - but there still is a difference.
