### ISSUE TITLE
Strong Naming SHA-256 with keys stored on HSM using KSP

### ISSUE THREAD

**Issue by daveroche-digi** [dotnet/docs#26236]
[We are looking to implement support for enhanced strong naming for SHA-256 with keys stored on HSM using MSFT KSP. Can you please confirm this is supported? If so, please advise where I can review instructions and/or documented. Thanks. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6d1037-56d7-f45b-fadf-16f2455c70d8
* Version Independent ID: 6c543a84-2b58-a769-e829-00e95688a4d2
* Content: [Enhanced strong naming](https://docs.microsoft.com/en-us/dotnet/standard/assembly/enhanced-strong-naming)
* Content Source: [docs/standard/assembly/enhanced-strong-naming.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/enhanced-strong-naming.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @daveroche-digi,

Sorry for the really long-delayed reply. I missed this and I've been working through older issues, and just now saw this. I'm honestly not sure, that is a good question. Let's ask @blowdart, he might know.

**Comment by blowdart** [comment]
Easy answer, although not the one you want - it's not supported.

StrongNames aren't a security boundary, for that you use authenticode signing, so we've not seen any need for hsm support.

Having said that if the hsm is exposing itself as a standard csp there's no reason it shouldn't work, a combination of -c and -i might do it.
