### ISSUE TITLE
The note at the top of this page is patently incorrect

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#26232]
> Versioning is done only on assemblies with strong names.

versioning and strong naming are different things.  All assemblies and programs are versioned even if one isnt set explicitly. Some are signed with a strong name key to reduce tampering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3041cbd3-6a5e-515c-f261-e228bae5783a
* Version Independent ID: 2e1387a8-577b-19bb-f445-d3007fde88fe
* Content: [Assembly versioning](https://docs.microsoft.com/en-us/dotnet/standard/assembly/versioning)
* Content Source: [docs/standard/assembly/versioning.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/versioning.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
You're absolutely right. Do you want to submit a PR to address this issue? Thank you @StingyJack

**Comment by StingyJack** [comment]
Done

**Comment by IEvangelist** [comment]
Closed by #26246
