### ISSUE TITLE
Resolution of DateTime.Now and UtcNow

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2623]
I think the documentation of resolution of `DateTime.Now` and `DateTime.UtcNow` could use some improvement.

Currently, [the docs for `DateTime.Now` say](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.now?view=netframework-4.7#remarks):

> The resolution of this property depends on the system timer, which is approximately 15 milliseconds on Windows systems.

[Docs for `DateTime.UtcNow`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.utcnow?view=netframework-4.7#remarks):

>  The resolution of this property depends on the system timer.  
>
> |System|Approximate Resolution|  
> |------------|----------------------------|  
> |Windows NT 3.5 and later|10 milliseconds|  
> |Windows 98|55 milliseconds|  

My thoughts:

* What Windows 98 or Windows NT 3.5 did does not matter anymore and should not be in the current version of docs.
* Do `Now` and `UtcNow` really have different resolution (15 ms vs. 10 ms)?
* The resolution of `Now` and `UtcNow` seems to be 0.5 ms on my Windows 10 machine.
* Documentation for Linux and macOS would be useful too.

**Comment by mairaw** [comment]
@karelz do you know who own System.DateTime?

**Comment by karelz** [comment]
I think it is part of System.Runtime - so @AlexGhiondea @joperezr should be able to help (BTW: see [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas))

**Comment by mairaw** [comment]
@AlexGhiondea @joperezr can you guys help with this one?

**Comment by joperezr** [comment]
@tarekgh who is more familiar with DateTime class, do you mind checking the questions above?

**Comment by tarekgh** [comment]
Looking at Windows documentation for the APIs we call to get the system time https://msdn.microsoft.com/en-us/library/windows/desktop/ms724397(v=vs.85).aspx is not mentioning the exact resolution. so, I think we don't need to specify specific numbers here as this may differ from one OS to another. Keeping the statement ```The resolution of this property depends on the system timer``` and we can add ```which depends on the underlying OS we are running on``` or something similar.

**Comment by svick** [comment]
Would giving at least a rough idea of what the resolution tends to be make sense? E.g.:

> The resolution of this property depends on the system timer, which depends on the underlying operating system. It tends to be between 0.5 ms and 15 ms.

**Comment by tarekgh** [comment]
what @svick mentioned looks reasonable to me.

**Comment by kirsan31** [comment]
@tarekgh @svick 

> The resolution of this property depends on the system timer, which depends on the underlying operating system. It tends to be between 0.5 ms and 15 ms

Is it still (.Net9) correct?

My test (Win11 24H2) shows that:
1. Resolution of `DateTime.Now` is something really more than 0.5 ms:
```cs
i = 0;
DateTime now = DateTime.Now;
while (i++ < 10)
    Console.WriteLine($"{DateTime.Now - now }");
``` 
result in:
```
00:00:00.0000037
00:00:00.0007558
00:00:00.0008027
00:00:00.0008387
00:00:00.0008711
00:00:00.0008940
00:00:00.0009496
00:00:00.0009866
00:00:00.0010154
00:00:00.0010376
```

2. Result is not depend on system timer resolution. It's same with or without `NtSetTimerResolution`, unlike `Thread.Sleep`, for example.

**Comment by tarekgh** [comment]
It is worth noting that `DateTime.Now` first retrieve the system time in UTC (like `DateTime.UtcNow`) then convert the result to the local time using the local time zone. Think about it in two stages. Retrieving the system time on Windows we call Windows API [GetSystemTimePreciseAsFileTime](https://github.com/dotnet/runtime/blob/c68a1becda28359186b181715c1f12d1e3e2bcb2/src/libraries/System.Private.CoreLib/src/System/DateTime.Windows.cs#L152C58-L152C88). If you look at the [GetSystemTimePreciseAsFileTime](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) doc, it says the following:

```
The GetSystemTimePreciseAsFileTime function retrieves the current system date and time with the highest possible level of precision (<1us). The retrieved information is in Coordinated Universal Time (UTC) format.
```

Then the resulting UTC time will get converted to local time which will depend on the machine speed and time zone settings on that machine. We manually convert to local time using TimeZoneInfo which calculates the time according to the current time shift from UTC considering DTS for that zone. I hope this helps explain the cost of retrieving the current time.

**Comment by kirsan31** [comment]
@tarekgh Thank you for the explanation!

> I hope this helps explain the cost of retrieving the current time.

But my point was about that docs must be updated.

[DateTime.UtcNow](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.utcnow?view=net-9.0#:~:text=The%20resolution%20of%20this%20property%20depends%20on%20the%20system%20timer%2C%20which%20depends%20on%20the%20underlying%20operating%20system.%20It%20tends%20to%20be%20between%200.5%20and%2015%20milliseconds.)

> The resolution of this property depends on the system timer, which depends on the underlying operating system. It tends to be between 0.5 and 15 milliseconds.

And [DateTime.Now](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.now?view=net-9.0#:~:text=The%20resolution%20of%20this%20property%20depends%20on%20the%20system%20timer%2C%20which%20depends%20on%20the%20underlying%20operating%20system.%20It%20tends%20to%20be%20between%200.5%20and%2015%20milliseconds.%20As%20a%20result%2C%20repeated%20calls%20to%20the%20Now%20property%20in%20a%20short%20time%20interval%2C%20such%20as%20in%20a%20loop%2C%20may%20return%20the%20same%20value.)

> The resolution of this property depends on the system timer, which depends on the underlying operating system. It tends to be between 0.5 and 15 milliseconds. As a result, repeated calls to the Now property in a short time interval, such as in a loop, may return the same value.

As you also pointed are no longer the true (ok, not true in most cases due to https://github.com/dotnet/runtime/issues/9014).

**Comment by tarekgh** [comment]
> But my point was about that docs must be updated.

Feel free to submit a PR suggesting any change. The change needs to be correct in generic cases.
