### ISSUE TITLE
Need Linux install instructions for .Net 6.0

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/docs#26237]
I tried installing via apt-get using `dotnet-sdk-6.0` but was told no package could be found. How do we install .Net 6.0 on Linux distros?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Xyncgas** [comment]
yeah I agree, even though you can build from source always, adding instructions everywhere actually educates more people by making the education widely available and open source's spirit is sharing and we are doing so sharing knowledge

**Comment by adegeo** [comment]
Prerelease versions aren't added to the package managers. You'll need to download use [dotnet script install](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) or a [manual install](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install). I'll look at clarifying this
