### ISSUE TITLE
Is 'inheritence' really the driving force behind this warning?

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/docs#26241]
It's not really clear _why_ inheritence has anything to do with returning a `List<T>` versus returning an `IList<T>`.

I'd say it was more to do with returning a mutable list, but that sounds like a different analysis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86af4d4-2416-70b7-290b-db06062f2dde
* Version Independent ID: 31e77ee3-ba63-fb91-f3a3-45ce3f4767b7
* Content: [CA1002: Do not expose generic lists (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1002)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1002.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1002.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
I think the rule is about making your API consumer life easier. For example, if you have a property of type `List<T>`, then you're restricting the API consumer to this exact type. Changing to to `IList<T>` allows them flexibility to assign whatever concrete type they have that implements `IList<T>`.

For the return type of a method, the rule doesn't make much sense to me unless the method is overridable, which will again allow the API consumer to implement it in a more flexible manner and return whatever concrete type they want that implements `IList<T>`.

*I could be wrong - so it's better to wait for an answer from the product team*

**Comment by Youssef1313** [comment]
There is a pending discussion at https://github.com/dotnet/roslyn-analyzers/issues/4508.

**Comment by gewarren** [comment]
Closing this in favor of dotnet/roslyn-analyzers#4508.
