### ISSUE TITLE
Clarify `COMPlus_DbgMiniDumpType` options 1 and 3

### ISSUE THREAD

**Issue by nils-a** [dotnet/docs#26257]
The section [Collect dumps on crash](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps#collect-dumps-on-crash) contains a table that describes the possible values of `COMPlus_DbgMiniDumpType`. However, the values `1` and `3` have the exact same description.

Could someone clarify what the difference is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ef6c57-5a31-d141-e0d1-15b51e860931
* Version Independent ID: fa042d69-62a2-f819-7bac-68051ad29e76
* Content: [Dumps - .NET](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps)
* Content Source: [docs/core/diagnostics/dumps.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dumps.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by gewarren** [comment]
@mikem8361 Is there a difference between `MiniDumpNormal` and `MiniDumpFilterTriage`?

**Comment by mikem8361** [comment]
>> @mikem8361 Is there a difference between MiniDumpNormal and MiniDumpFilterTriage?

There isn't a lot of difference in how much memory, etc. is collected, but MiniDumpFilterTriage removes the personal user info like some paths, passwords, etc.

**Comment by nils-a** [comment]
Thanks for clarifying this!
