### ISSUE TITLE
Document --ignore-failed-sources

### ISSUE THREAD

**Issue by woter1832** [dotnet/docs#26261]
As there is still a bug with `dotnet tool install` as documented [here](https://github.com/dotnet/sdk/issues/9555), it may be an idea to document the workaround.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET tools - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-tools.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
I'll see what I can do to improve this.
