### ISSUE TITLE
Need an example on how to do this with method syntax

### ISSUE THREAD

**Issue by alex47** [dotnet/docs#26265]
There is no example unfortunately on how to do left outer join LINQ with method syntax.

This documantation page says that every LINQ expression can be converted to method syntax, so it should be possible:
https://docs.microsoft.com/en-us/dotnet/csharp/linq/#:~:text=Any%20query%20that%20can%20be%20expressed%20by%20using%20query%20syntax%20can%20also%20be%20expressed%20by%20using%20method%20syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d433265d-15f4-bd2e-a3d1-8148a3968783
* Version Independent ID: 75d2c893-1d07-f836-62f1-e767edfcebac
* Content: [Perform left outer joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins)
* Content Source: [docs/csharp/linq/perform-left-outer-joins.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/perform-left-outer-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 198453](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198453)

**Comment by BillWagner** [comment]
Thanks @alex47 

That is a great suggestion. We'll add this when we next update this article.

**Comment by BillWagner** [comment]
Adding this to the current sprint, as I'll be updating this article.
