### ISSUE TITLE
Enumeration members are always public seems to be wrong in Access Modifiers

### ISSUE THREAD

**Issue by swardinfo** [dotnet/docs#26273]
**Issue description**

Access Modifiers (C# Programming Guide)

Apologies in advance if I'm reading this wrong.

The stated definition for the public access modifier is 'The type or member can be accessed by any other code in the same assembly or another assembly that references it.' 
Under 'Other types' it states 'Enumeration members are always public, and no access modifiers can be applied.'
                        
But if an enum is declared as private within a class then its members can only be accessed within that class, which means they are also effectively private, therefore 'Enumeration members are always public' seems to be wrong.
Maybe it should be replaced with something like 'Enumeration member's access level are always the same as that which is applied to the enumeration. and access modifiers cannot be applied to enumeration members.'

**Target framework**

- [X] .NET Core .NET 5.0
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

edit by @BillWagner : Add document details block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
The documentation is correct that enumeration members behave the same as public members of other types. But the definition of public is not quite right: a public member of a type is only as accessible as the type itself. So if anything were to change there, I think it's the definition of `public`.

**Comment by BillWagner** [comment]
thanks for opening this @swardinfo 

The comment by @svick is correct, and that's what should change.

I've added this to our backlog, and added the "up for grabs" label if anyone wants to submit a PR before we update this article.

**Comment by ankitwww** [comment]
Hi @BillWagner, I submitted a PR to improve the article. Hope this will serve the purpose.
