### ISSUE TITLE
No install instructions

### ISSUE THREAD

**Issue by rgamage** [dotnet/docs#26280]
A key part of instructions on using a tool would be how to install the tool.  Where to find it, how to get it installed.  I can't find it in the VS marketplace, searching in VS Extensions dialog brings nothing, and I can't find any instructions anywhere on how to get the extension into VS 2019.  How about adding some guidance for this?

When I try to add a service reference to my project, I get lots of options, but none are WCF related.

![image](https://user-images.githubusercontent.com/16804880/134956957-64c227ce-6053-4620-bdd2-1e40152014b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Add WCF Web Service Reference - .NET](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/main/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dasetser
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Related to #25296.
