### ISSUE TITLE
Still in proposed state?

### ISSUE THREAD

**Issue by jtillman** [dotnet/docs#26288]
Isn't Async Main function at least in prototype phase since we can use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7dbb1d-f7e7-b919-89cd-7df873294aee
* Version Independent ID: 3323483a-f4e9-0e42-1a3b-a51771b5b1c9
* Content: [Async main method - C# 7.1 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main)
* Content Source: [proposals/csharp-7.1/async-main.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.1/async-main.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the question @jtillman 

The `async Main` feature was delivered in C# 7.1. You can use it, as long as you're using 7.1 or later.  The term "proposals" in this section of docs refers to the fact that the [C# standard](https://github.com/dotnet/csharpstandard) committee is behind the language and compiler team. The ECMA committee is working to catch up, and will continue to update the standard document. 

I'll close this as an answered question.

**Comment by svick** [comment]
@BillWagner I believe this is referencing the task list at the start of the proposal document. Since I don't think they are useful, I have opened https://github.com/dotnet/csharplang/pull/5232 to delete them.
