### ISSUE TITLE
https://official-joke-api.appspot.com/jokes/programming/random is indeed already dead

### ISSUE THREAD

**Issue by rokonec** [dotnet/docs#26307]
The https://official-joke-api.appspot.com/jokes/programming/random is indeed already dead, as properly stated in  the Tip section.

Please consider to change it to working, ATM, url https://karljoke.herokuapp.com/jokes/programming/random.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @rokonec - thank you, you're correct. I added the `up-for-grabs` label on this, if you're interested in fixing this please feel free to create a pull request and reference this issue. Thanks

**Comment by IEvangelist** [comment]
Closed by #26308
