### ISSUE TITLE
Default value for <nullable>

### ISSUE THREAD

**Issue by mrlife** [dotnet/docs#26336]
It would be helpful to list the default value for the `<nullable>` option. I believe all the other options on this page have a default listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548e000-8190-b1bb-51fd-7e7b2d5bcb45
* Version Independent ID: 19f59267-c4c1-eb0e-7e48-45ffd6e2d9d1
* Content: [C# Compiler Options - language feature rules](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#nullable)
* Content Source: [docs/csharp/language-reference/compiler-options/language.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/language.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @mrlife 

The default is `disable`.

I've added this to our backlog, and added the "up for grabs" label to this issue.

**Comment by KevRitchie** [comment]
Hi @BillWagner, I've picked this up and added the extra detail required.  PR submitted for review.
