### ISSUE TITLE
[Breaking change]: Regex.CompileToAssembly is marked as Obsolete with diagnostic id SYSLIB0036

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/docs#26352]
### Description

The `Regex.CompileToAssembly` API has been marked as Obsolete. References to this API will now produce diagnostic ID `SYSLIB0036`.  See https://github.com/dotnet/runtime/pull/59734 for the change.

### Version

Other (please put exact version in description textbox)

### Previous behavior

**Version**: .NET 7 Preview 1

In all versions of .NET Core as well as .NET 5 and .NET 6, this API would threw `PlatformNotSupportedException`. In .NET Framework, this API allowed a regular expression instance to be compiled into an assembly.

### New behavior

References to this API will result in a build warning; the diagnostic ID reported is `SYSLIB0036`.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

This functionality will not be carried forward into .NET. Instead, .NET 7 is introducing a Regular Expression Source Generator that can be invoked using the `RegexGeneratorAttribute` feature.

### Recommended action

Use the `RegexGeneratorAttribute` feature, which invokes a regular expression source generator, allowing for compile-time production of an API specific to a regular expression pattern and its options.

### Feature area

Core .NET libraries

### Affected APIs

* [System.Text.RegularExpressions.Regex.CompileToAssembly](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex.compiletoassembly)

**Comment by gewarren** [comment]
@jeffhandley This is actually SYSLIB0036, not 0037, correct?

**Comment by jeffhandley** [comment]
Great catch, @gewarren. You're correct. I've updated the title and issue description to reflect that.
