### ISSUE TITLE
PipeReader.AdvanceTo(int,int) does not exist

### ISSUE THREAD

**Issue by JKamsker** [dotnet/docs#26365]
`reader.AdvanceTo(buffer.Start, buffer.End);` does not exist anymore. It only accepts `SequencePosition`. Can you please provide an updated version for the code?

I am using `    <PackageReference Include="System.IO.Pipelines" Version="5.0.1" />`

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5384a7-5e96-d977-7748-317a2c758f63
* Version Independent ID: 06e72212-a052-a351-0e0b-1b002ce214de
* Content: [I/O pipelines - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines)
* Content Source: [docs/standard/io/pipelines.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/pipelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by svick** [comment]
@JKamsker The docs are talking about <code>Pipe**Writer**.Advance(int)</code>, while your code is using <code>Pipe**Reader**</code>, which indeed does not have an `Advance(int)` or `AdvanceTo(int)` method.

**Comment by JKamsker** [comment]
@svick Oh, sorry for the confusion. 

But still, in the docs, they appearantly use `reader.AdvanceTo(int,int)` which does not exist.
![image](https://user-images.githubusercontent.com/11245306/137101468-4f75b5c9-7eb1-48fe-ae6e-6cde1b91754a.png)

**Comment by svick** [comment]
@JKamsker I'm not sure it's what you're looking for, but if you have a `ReadOnlySequence<byte> buffer`, you can do `buffer.GetPosition(someInt)` to get a `SequencePosition`.
