### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by aslan-im** [dotnet/docs#26382]
Link  "smart endpoints and dumb pipes": https://simplicable.com/new/smart-endpoints-and-dumb-pipes  is not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: fbeadc16-d9e1-91cf-5da6-1d76fc800d3e
* Content: [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by KevRitchie** [comment]
Hi @aslan-im, I've had a quick check of the doc and the link seems to be working.

Do you mean that the destination page is wrong or that the page should open in another tab or it's just generally not working for you?

**Comment by aslan-im** [comment]
HI @KevRitchie! The end source is not working.
![image](https://user-images.githubusercontent.com/7303058/136024086-6c01b8a9-d974-4b1c-9c1c-32d8448f92c2.png)

**Comment by KevRitchie** [comment]
This is what I'm seeing when I click the link:

![image](https://user-images.githubusercontent.com/65573253/136024416-29c491a8-cb31-4276-8570-eaaba24a5bc2.png)

I wonder if it's something to do with where it's being served up from and to?

**Comment by aslan-im** [comment]
@KevRitchie  yes, seems it is because of my location. Sorry. Issue can be closed.
