### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by antonywafula** [dotnet/docs#26384]
**Issue description**

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by BillWagner** [comment]
Hi 👋 @antonywafula 

I'm guessing this was opened in error. I'll close this. If you submitted the issue before adding details, you can edit the issue and reopen it.
