### ISSUE TITLE
Reason for separating the business logic and tests

### ISSUE THREAD

**Issue by qevers** [dotnet/docs#26395]
In this example you separate the business logic (NewTypes.csproj) from the test cases.

What is the reason for that separation?

The only thing that I could come up with is that it might be easier to identify all test projects in the pipeline when you want to run the tests. But running `dotnet test` on the solution will automatically run all test projects in the solution, ignoring the business logic projects.

There are some downsides to this separation, especially if you use the Visual Studio IDE:

- If you want to use these projects in a Visual Studio Solution, you'd have to put the solution file in the root folder, even though I feel that the solution is part of the source.
- Adding a project in your solution in Visual Studio (even if you right-click the solution folder called `test` or `src`) will add the project to the root folder, not the `test` or `src` folder. You need to manually move it on disk, including editing the `.sln` file, or removing and re-adding the project from/to the solution.
- I'm a big fan of keeping code closely together if you edit that code at the same time: if you change a project, you're very likely to also change the test code for that same project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b54562-9072-a864-be3d-44ed7965c798
* Version Independent ID: a69ec985-ed05-90dd-a686-dc956b0cf5df
* Content: [Organizing and testing projects with the .NET CLI - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#feedback)
* Content Source: [docs/core/tutorials/testing-with-cli.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/testing-with-cli.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @cartermp
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@cartermp You're listed as owner of this article -- is that still valid, and if so do you want to respond to this question?

**Comment by cartermp** [comment]
Heh, not at MSFT anymore, so probably best to remove my ownership 🙂 

In general, I think that this isn't _that_ big of a deal, since VS can support folder relationships as well. I don't think it's harmful to make things conform to a more flat structure (that VS will create by default), but most modern projects do place tests and application code in separate subdirectories and it's not a bad idea to suggest that either.
