### ISSUE TITLE
Possible Incorrect (not best practice) Return Object in Documentation

### ISSUE THREAD

**Issue by MaxB504** [dotnet/docs#26418]
Thank you for the very comprehensive tutorial on WCF to gRPC.  Is the below incorrect/confusing:

message GetAllRequest {
    string trader_id = 1;
}

message GetAllResponse {
    repeated Portfolio portfolios = 1;
}

service Portfolios {
    rpc Get(GetRequest) returns (**Portfolio**);
    rpc GetAll(GetAllRequest) returns (GetAllResponse);
}`

It was specified above this code that:
_The service could just return a Portfolio message directly, but again, this could affect backward compatibility in the future. It's a **good practice to define separate Request and Response messages for every method in a service**, even if many of them are the same right now. So declare a GetResponse message with a single Portfolio field._

with the code example:
`message GetRequest {
    string trader_id = 1;
    int32 portfolio_id = 2;
}

message GetResponse {
    Portfolio portfolio = 1;
}

service Portfolios {
    rpc Get(GetRequest) returns (**GetResponse**);
}`

I found it confusing that the previous code example for Get had a GetReponse object, and with the GetAll example the Get code has changed to have a Portfolio Response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 325dd28c-3bed-f7ff-4f13-7c7c951250fd
* Version Independent ID: f9bef770-f952-169a-0dec-a25606d4207d
* Content: [Migrate a WCF request-reply service to gRPC - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-request-reply)
* Content Source: [docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by mohamed-azhar** [comment]
```
service Portfolios {
rpc Get(GetRequest) returns (Portfolio); 
rpc GetAll(GetAllRequest) returns (GetAllResponse);
}
```

For the above code in the Get method, instead of **returns (Portfolio)**, it should be **returns (GetResponse)** i'm not wrong?
