### ISSUE TITLE
dotnet issue

### ISSUE THREAD

**Issue by sahilpatil9763** [dotnet/docs#26448]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b03a29-8bfe-7e83-05a4-c0f72d9cce41
* Version Independent ID: 0e4a3797-ed9f-fe49-ef0d-ce074a224896
* Content: [Compiler Warning (level 3) CS0169](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0169?f1url=%3FappId%3DDev10IDEF1%26l%3DEN-US%26k%3Dk(CS0169);k(TargetFrameworkMoniker-%2522.NETFRAMEWORK%252cVERSION%253dV4.0%2522)%26rd%3Dtrue)
* Content Source: [docs/csharp/misc/cs0169.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0169.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sahilpatil9763** [comment]
// compile with: /W:3  
using System;  
public class ClassX  
{  
   int i;   // CS0169, i is not used anywhere  
  
   public static void Main()  
   {  
   }  
}

**Comment by Youssef1313** [comment]
@sahilpatil9763 This is still lacking information. The code from the article that you pasted produces the warning, and the warning is correct. The field isn't used anywhere. So I'm not sure what's the ask here?

**Comment by sahilpatil9763** [comment]
// compile with: /W:3
using System;
public class ClassX
{
int i; // CS0169, i is not used anywhere

public static void Main()
{
}
}


This msg is occurring and I don't know how to fix it

**Comment by BillWagner** [comment]
@sahilpatil9763 There are two options to fix this error:

1. Use the variable in some expression.
2. Remove the variable declaration.

I hope that helps.

We should update this page with that information.
