### ISSUE TITLE
Whare are the meaning of each flag?

### ISSUE THREAD

**Issue by DavidotNet** [dotnet/docs#26444]
[Enter feedback here]
Please provide an explanation of the meaning of the output values of 1 and 0 for each flag.
I want to be certain of the meaning.  I am troubleshooting COM  "is not a valid Office Add-In."  It will not load in a 64 bit Office App. 

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+   Does this mean 64bit only or both 32 & 64bit?
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0 What do these BIT flags mean?
32BITPREF : 0   
Signed    : 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a097b4-e572-a4e2-6005-8997518d1c60
* Version Independent ID: bf7de8f5-8a49-0e07-1ed2-e98d66c77a5e
* Content: [CorFlags.exe (CorFlags Conversion Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/corflags-exe-corflags-conversion-tool)
* Content Source: [docs/framework/tools/corflags-exe-corflags-conversion-tool.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/corflags-exe-corflags-conversion-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@safern who can help with this request?

**Comment by tdykstra** [comment]
@agocke do you know who can help with this?

**Comment by agocke** [comment]
These flags are documented in section "II.25.3.3.1 Runtime flags" of the ECMA-335 specification.

**Comment by agocke** [comment]
Except for the PE flag, that is part of the PE format, which is documented at https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-image-only

**Comment by tdykstra** [comment]
@agocke Thanks! I'll update the article.
