### ISSUE TITLE
That was COOL !

### ISSUE THREAD

**Issue by mosaisdelba** [dotnet/docs#26460]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cdfbba-c2bd-f9b0-52a9-d82cc9b2dcf9
* Version Independent ID: 287733f4-7593-ba5e-f26c-531fde328319
* Content: [Introduction to C# - interactive tutorials](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @mosaisdelba  We appreciate the compliments.

I'll close this as kudos.
