### ISSUE TITLE
Reverting to the Old Style

### ISSUE THREAD

**Issue by Walluce** [dotnet/docs#26463]
Thanks for the "How to use the old version" guide, but is there a way this can be a Visual Studio setting? I would prefer for my team to use the old style.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See #26313, where you can vote on the new template code.  Closing this issue in favor of that one.
