### ISSUE TITLE
"Ref returns and ref locals" page has a bunch of junk at the top of the page

### ISSUE THREAD

**Issue by Daniel15** [dotnet/docs#2650]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns

See at the top of the page:
![](http://ss.dan.cx/2017/07/chrome_17-15.42.47.png)

@BillWagner @rpetrusha

**Comment by rpetrusha** [comment]
Thanks for letting us know, @Daniel15. I'll submit a PR to fix it.
