### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Frank-liuyanbing** [dotnet/docs#26508]
Please add the Chinese version, thank you very much.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 96d36ba2-c119-3871-c1a3-5b9312551273
* Version Independent ID: 7ad0bd5b-db85-7307-8bef-62aded4d0087
* Content: [Objects - create instances of types](https://docs.microsoft.com/zh-cn/dotnet/csharp/fundamentals/object-oriented/objects)
* Content Source: [docs/csharp/fundamentals/object-oriented/objects.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
Ping @kgliang

**Comment by Youssef1313** [comment]
@gewarren This is possibly already fixed? The article opens in Chinese.
