### ISSUE TITLE
Base class reference has error

### ISSUE THREAD

**Issue by bobishkindaguy** [dotnet/docs#26511]
There is an error which is preventing me from following the instructions completely.

The instructions say to rename the PortfolioService class like this:
public class PortfolioService : Portfolios.PortfoliosBase

But when I do that, there is a red squiggly line under the last part "PortfoliosBase" - and the error says that the type or namespace name doesn't exist in the namespace TraderSys.Portfolios.

So I started over, and checked that out before renaming it ---
In the sample gRPC service created by Visual Studio, I did a right-click on "GreeterBase" - then "Go to definition" -- and it takes me to the following entry in the file obj\debug\net5.0\protos\GreetGrpc.cs file (which is an autogenerated file):

public abstract partial class GreeterBase

Since the file is auto-generated, I decided to delete the obj folder in the VS-generated sample project and rebuild. The GreetGrpc file was indeed auto-generated, along with that line "public abstract partial class GreeterBase".

However, when I delete the obj folder after renaming the base class, the error recurs. So I checked the auto-generated file, and it also has the renamed base class, "PortfoliosBase". But the error still says there is no such class.

I have checked and re-checked my spelling, etc., and I'm sure I'm following the instructions here correctly. 

So, what must be done to have Visual Studio accept the renamed item:
public class PortfolioService : Portfolios.PortfoliosBase

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 935116ee-b70f-1a99-7c51-a47f1c085d52
* Version Independent ID: d1869bbd-632c-07a2-d06a-af347833a26e
* Content: [Create a new ASP.NET Core gRPC project - gRPC for WCF Developers](https://docs.microsoft.com/en-ca/dotnet/architecture/grpc-for-wcf-developers/create-project)
* Content Source: [docs/architecture/grpc-for-wcf-developers/create-project.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/create-project.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
