### ISSUE TITLE
Ocelot supports web sockets.  What functionality is missing?

### ISSUE THREAD

**Issue by bit7** [dotnet/docs#26544]
Ocelot supports web sockets.  What functionality is missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by VaishaliRaval** [comment]
Hey @bit7 , thank you for reaching out and reporting this.

As Ocelot is no longer maintained, we moved away from using it and we are currently using Envoy proxy for the redirections. Will be updating the content of docs for API Gateways accordingly.

I am closing this issue as of now, feel free to track the updation of docs in a similar issue https://github.com/dotnet/docs/issues/27445
