### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#26548]
Frankly this is so contrived! Having to create a project as .Net 5 then hand edit the project's target to be .Net 6 as the way to get a .Net 6 console app with the usual class etc is just bizarre.

This really should be an opt-in, just add a check box on the final page of the project create operation "Use new console style" or something and make that checkbox only visible for .Net 6 or later targets.

Defaulting to the minimal form this way suggest a rushed decision, just not thought through very well, why adding a checkbox for this was not the obvious choice is a mystery!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @KathleenDollard

**Comment by terrajobst** [comment]
My understanding is that we don't plan to make changes for 6.0 RTW. However, we're going to collect more user data as more and more people will move to .NET 6. Yes, we hear some strong feedback but to be frank, it's unclear whether it's a very loud minority or a problem for a large chunk of our user base. Right, the belief on our side is that the feedback is coming from a minority, hence no plan to make changes for RTM.

@KathleenDollard and/or @DamianEdwards should have the latest here.

**Comment by tdykstra** [comment]
See #26313, where you can vote on the new template code.  Closing this issue in favor of that one.
