### ISSUE TITLE
Investigate MSDN links that don't redirect to docs.microsoft.com

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2655]
Per https://github.com/dotnet/docs/pull/2634#discussion_r127855854 ...

Link https://msdn.microsoft.com/library/ms256124(v=vs.100).aspx was updated to https://msdn.microsoft.com/library/ms256124(v=vs.110).aspx based on a script load and the canonical URL on https://github.com/dotnet/docs/pull/2634, but these should redirect. This issue is opened to investigate.

**Comment by mairaw** [comment]
Another one I found today: https://msdn.microsoft.com/en-us/library/ms184658.aspx

**Comment by mairaw** [comment]
I'm closing this one. The XML reference content was only migrated to archive since we don't have resources to maintain that content.
