### ISSUE TITLE
Clarification On Nothing vs Null

### ISSUE THREAD

**Issue by pnp000** [dotnet/docs#26569]
[Enter feedback here]

It is not clear from the description that there is a subtle but important difference when working with Null and Nothing.

Whilst, a string assigned to Nothing is comparable to Null, a string assigned to Null is NOT comparable to Nothing.  This can cause many runtime issues if not properly coded for.   It renders the mathmatical truth that if a=b and b=c that a=c false.

Consider the code below:

Sub TestNothing()

        Dim out As String = Nothing

        Dim a As String = Nothing
        out = out & "a = Nothing" & vbCrLf

        Dim b As String = ""
        out = out & "b = " & Chr(34) & Chr(34) & vbCrLf

        If a = "" Then                                   'True. Nothing Is Null
            out = out & "a is null" & vbCrLf
        Else
            out = out & "a is not null" & vbCrLf
        End If

        If b = "" Then                                  'True as expected
            out = out & "b is null" & vbCrLf
        Else
            out = out & "b is not null" & vbCrLf
        End If

        If a Is Nothing Then                            'True as expected
            out = out & "a is nothing" & vbCrLf
        Else
            out = out & "a is not nothing" & vbCrLf
        End If

        If b Is Nothing Then                            'False.  Null IsNot Nothing
            out = out & "b is nothing" & vbCrLf
        Else
            out = out & "b is not nothing" & vbCrLf
        End If

        If a = b Then                                   'True. Nothing Is Null
            out = out & "a = b" & vbCrLf
        Else
            out = out & "a <> b" & vbCrLf
        End If

        If b = a Then                                   'True. Equals operator is commutative which is as expected but on the otherhand Odd because Null IsNot Nothing
            out = out & "b = a" & vbCrLf
        Else
            out = out & "b <> a" & vbCrLf
        End If

        MsgBox(out)

    End Sub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502309a5-a298-3ecc-2ff8-99faf674b5aa
* Version Independent ID: 36611596-bb82-4165-9621-634728529908
* Content: [Nothing keyword - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/nothing)
* Content Source: [docs/visual-basic/language-reference/nothing.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/nothing.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Adding the "up for grabs" label to this issue.

I prefer the text suggested by @KathleenDollard for this issue. It's a bit more complete.

**Comment by KevRitchie** [comment]
@BillWagner, happy to add the amended text, if still needed?
