### ISSUE TITLE
contradicting information on roslyn analyzers page

### ISSUE THREAD

**Issue by bniranjanbhat** [dotnet/docs#26565]
In Roslyn Analyzer documentation there are two contradicting sets of information which makes it tougher to understand:

Here are the two lines:
--cut--
You can **enable** .NET code analysis for SDK-style projects that target earlier versions of .NET by setting the EnableNETAnalyzers property to true.
--cut--

And

--cut-- 
This property applies specifically to the built-in analyzers in the .NET 5+ SDK. It should not be used when you install a NuGet code analysis package.
--cut--

The first set of instructions asks to use the property for .NET SDK < 5 while the second speaks on the contrary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablenetanalyzers)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
@bniranjanbhat Is the point of confusion is whether `EnableNETAnalyzers` works for versions earlier than .NET 5 or not?

I think the first paragraph is referring to the `TargetFramework`, which is different from the .NET SDK version. The following is how I'm interpreting this.

|.NET SDK version|TargetFramework|Description|
|----------------|------------|----------|
|5.0+|5.0+|Enabled by default.|
|5.0+|Earlier than 5.0|Disabled by default, can be enabled.|
|Earlier than 5.0|Any version|The property is not supported|

But @mavasani or @gewarren can confirm whether what I'm stating is correct.

**Comment by bniranjanbhat** [comment]
Hi @Youssef1313 
yes, that is the confusion. thanks
