### ISSUE TITLE
This page repeatedly suggests catching the type Exception and swallowing it

### ISSUE THREAD

**Issue by brunojMicrosoft** [dotnet/docs#26560]
[Enter feedback here]
Hi,

Due to the way the code samples are written, this page repeatedly suggests that swallowing exceptions of type Exception is a good practice.
Things may have changed recently, but I learned that catching exceptions such as SystemException or OutOfMemoryException (both derived from Exception) without rethrowing is a terrible practice.

It seems that the Microsoft documentation should demonstrate a proper approach, respecting best practices.

But maybe I missed something.

Thanks,
Bruno.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by poke** [comment]
@IEvangelist You can close this issue; I forgot to mention the magic words in the PR.

**Comment by IEvangelist** [comment]
Closed by #26612
