### ISSUE TITLE
C# Tutorial: Dispose Pattern

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#266]
Discuss ‘using’, Implementing the Dispose pattern, and the subtleties around finalizers and managing unmanaged resources.

Reference and point to the .NET Framework Design Guidelines.

**Comment by BillWagner** [comment]
Should this move out from the C# Tutorials section? 

This topic affects all languages, and applies everywhere .NET Standard applies. I think it should be covered under the net-standard area.

/cc @blackdwarf @richlander @cartermp @mairaw

**Comment by cartermp** [comment]
Agreed.  I'm happy to help with any F#-specific stuff (it's not much, `use` bindings have obvious scoping rules and use the same underlying mechanisms).
