### ISSUE TITLE
Update support for  2008 SP2

### ISSUE THREAD

**Issue by DuncanClay** [dotnet/docs#26661]
Support for 4.6.2 was recently added to Windows Server 2008 SP2, and so the list should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework & Windows OS versions - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
@jamshedd Can you comment on this?

**Comment by jamshedd** [comment]
> @jamshedd Can you comment on this?

Correct -  we should add 2008 SP2 to the section for 4.6.2.
