### ISSUE TITLE
Errors in how C# operators are tabulated.

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#26670]
There seem to be several errors on the way operators are listed:

![image](https://user-images.githubusercontent.com/12262952/138956909-4fe8c1c6-f565-480d-8f9c-963d7ddd40aa.png)

For example ++x is described as unary and is listed in that section "Unary". But x++ is described as as being unary yet is listed in the section "Primary".

In addition `delegate` is mentioned as being an operator yet I was told recently that it is not actually an operator.

There may be other errors too but these caught my eye recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Korporal 

Both of those statements are taken directly from the [standard text](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#1241-general)

The reason for the postfix operators being listed in "primary" and the prefix operators are listed in "unary" is to clarify the operator precedence.

The `delegate` keyword is an operator for a *delegate_creation_expression*.

I'll close this as by-design.
