### ISSUE TITLE
how to exec into

### ISSUE THREAD

**Issue by davidbIQ** [dotnet/docs#26718]
been looking for a bit for a kubectl exe -it xxx to get into this image, tried powershell & pwsh without luck, this wouldn't be a bad page to add that if if its known.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e29d7c-df16-2f4c-3899-ffc2ba67b166
* Version Independent ID: d0d62cdb-fbc6-f663-e473-51369d756877
* Content: [Kubernetes - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/kubernetes)
* Content Source: [docs/architecture/grpc-for-wcf-developers/kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by erjain** [comment]
The issue can be closed now.
