### ISSUE TITLE
Unspecified implicit enum conversion from literal 0X0

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/docs#26713]
[Enter feedback here]

There is nothing in the specification to indicate that the following code is well-formed:
```csharp
ConsoleColor black = 0X0;
```

I think it really supports any compile-time constant equal to 0:
```csharp
ConsoleColor black = DayOfWeek .Monday - DayOfWeek .Monday;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be4c24e-9e92-6b75-2b8e-2cb6cb072b5b
* Version Independent ID: 450064c8-720e-3b90-18d6-7bd5f183857e
* Content: [Conversions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#explicit-enumeration-conversions)
* Content Source: [spec/conversions.md](https://github.com/dotnet/csharplang/blob/main/spec/conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @yecril71pl 

This is covered in the standard in [11.2.4 Implicit enumeration conversions](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/conversions.md#1124-implicit-enumeration-conversions).

That clause specifies that the integer constant `0` is implicitly convertible to any `enum` type.

I'll close this as answered.

**Comment by yecril71pl** [comment]
> Hi @yecril71pl
> 
> This is covered in the standard in [11.2.4 Implicit enumeration conversions](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/conversions.md#1124-implicit-enumeration-conversions).
> 
> That clause specifies that the integer constant `0` is implicitly convertible to any `enum` type.
> 
> I'll close this as answered.

But the published text still says:

> An implicit enumeration conversion permits the decimal_integer_literal 0 to be converted to any enum_type
