### ISSUE TITLE
Need to change the Property as both readable and writeable  public decimal Balance { get; set;}

### ISSUE THREAD

**Issue by Mahadevan474** [dotnet/docs#26729]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fc632c-e0ea-9793-5dde-0d5938517d50
* Version Independent ID: 9907cf17-4c6f-e788-19e3-9272d2052467
* Content: [Classes and objects  - C# Fundamentals tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes)
* Content Source: [docs/csharp/fundamentals/tutorials/classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋 @Mahadevan474 

The code is correct, because the API shouldn't allow a direct change to the balance. The balance changes based on either a withdrawal or a deposit.

I'll close this as by-design.
