### ISSUE TITLE
Simplify entry point to .NET Standard/Sharing code

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#26728]
I did not find a docs link for "Sharing code .net framework .net core" and .NET Standard brought me here. 

Could we open this page with a simple "Use .NET Standard to share code between..." paragraph. 

If we can find the time, could we offload a ton of details from this page to sub pages and have this one just be how to use it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The main request was addressed, so I'll close this issue.
