### ISSUE TITLE
".NET Core SDK" --> ".NET SDK"?

### ISSUE THREAD

**Issue by dsyme** [dotnet/docs#26726]
Searching across this repository, the .NET docs have about 179 references to the ".NET Core SDK".  

In most cases I believe these should now be ".NET SDK" since that is the name used since .NET 5

**Comment by BillWagner** [comment]
Adding @tdykstra

**Comment by tdykstra** [comment]
In general that is correct.  I'll investigate.

**Comment by tdykstra** [comment]
In many cases the reference is to 3.1 or earlier, and so retention of "Core" was deliberate.   In #26753 I updated the instances where removing "Core" is feasible.
