### ISSUE TITLE
Static abstract interface members

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#26735]
Should [static abstract interface members](https://github.com/dotnet/csharplang/blob/main/proposals/static-abstracts-in-interfaces.md) be added to this page? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 10.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10)
* Content Source: [docs/csharp/whats-new/csharp-10.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-10.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@gewarren It's currently in preview:

https://github.com/dotnet/roslyn/blob/63ee0988fa3c84a47bbae01847257b95765135cc/src/Compilers/CSharp/Portable/Errors/MessageID.cs#L347-L351

If it would be documented, I don't think it should be for C# 10.

cc @AlekseyTs

**Comment by BillWagner** [comment]
I plan on adding it as a preview feature. Because it's in Preview, it's later on my C# 10 list than those features that aren't "preview" in C# 10. I'll note that it is in preview when I add information on it.

cc @MadsTorgersen
