### ISSUE TITLE
Warning	CS8632	The annotation for nullable reference types should only be used in code within a '#nullable' annotations context

### ISSUE THREAD

**Issue by JamalAPI** [dotnet/docs#26736]
Getting a warning on compile on Joke[]? jokes :

Warning	CS8632	The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.	WorkerService1	JokeService.cs	27	

// The API returns an array with a single entry.
                **Joke[]?** jokes = await _httpClient.GetFromJsonAsync<Joke[]>(
                    JokeApiUrl, _options);

also on **Joke?** joke = jokes?[0];

Removing the **?** corrected the issue per the VS fix it recommendation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
The linked source code that's part of this example does in fact have a nullable context:

https://github.com/dotnet/samples/blob/02542327173a035562ec7cc3580244d576ed38d9/core/workers/windows-service/App.WindowsService.csproj#L6

But I see that the steps do not include it, we should add that to make it more clear. I'll do that, thank you.
