### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by cschellenberger** [dotnet/docs#26745]
You can retrieve the data of an array by use an index.
You can retrieve the data of an array by `using` an index.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3885e9-4e4e-897c-0324-2e8f93d217b7
* Version Independent ID: f9014ce9-93c1-cda7-6286-c4226150fce4
* Content: [Single-Dimensional Arrays - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/single-dimensional-arrays)
* Content Source: [docs/csharp/programming-guide/arrays/single-dimensional-arrays.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/arrays/single-dimensional-arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @cschellenberger 

I've opened #26751 to address this issue.

In the future, when you find this types of errors, you may find it quicker to edit the file directly and create a PR. Just click the "pencil" icon at the top of page.

Thanks again for helping us improve.
