### ISSUE TITLE
How do I get the shutdown reason in .NET 5?

### ISSUE THREAD

**Issue by caisongjie** [dotnet/docs#26746]
Microsoft Q&A Link : 
https://docs.microsoft.com/en-us/answers/questions/610266/how-do-i-get-the-shutdown-reason-in-aspnet-core-5.html
In older versions of .NET Framework I could use `HostingEnvironment.ShutdownReason ` to retrieve `ApplicationShutdownReason `
But this no longer works in .NET 5 and now I can't figure out how to get the shutdown reason. 

old documentation link of `ApplicationShutDownReason `: 

https://docs.microsoft.com/en-us/dotnet/api/system.web.applicationshutdownreason?view=netframework-4.8
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577db847-e424-a9dc-ee2d-f2c6ddb54600
* Version Independent ID: 5fa219d8-0c9c-c758-c1ee-17cefd75ca24
* Content: [Port from .NET Framework to .NET 5 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/)
* Content Source: [docs/core/porting/index.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hello. I would ask on the ASP.NET -> Core migration article: https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-5.0

**Comment by adegeo** [comment]
I'm going to close this issue as you should ask in the ASP.NET Core repo.
