### ISSUE TITLE
Culture dependency constant interpolated-strings

### ISSUE THREAD

**Issue by Rubenisme** [dotnet/docs#26750]
The section on [constant interpolated-strings](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#constant-interpolated-strings) is now saying:

> The current culture may affect their string representation.

[But in the proposal ](https://github.com/dotnet/csharplang/issues/2951) [@333fred is saying](https://github.com/dotnet/csharplang/issues/2951#issuecomment-769244186):

> keep it simple and avoid any dependence on ... potential culture dependence.

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 10.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10)
* Content Source: [docs/csharp/whats-new/csharp-10.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-10.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The article says:

> The placeholder expressions can't be numeric constants because those constants are converted to strings at runtime. The current culture may affect their string representation.

So "The current culture may affect ..." part is an extension to the "why" placeholder expressions can't be numeric.

**Comment by Rubenisme** [comment]
Ahh, thanks for clarifying. I misread it.
