### ISSUE TITLE
pequeno desgaste

### ISSUE THREAD

**Issue by sartoriprado** [dotnet/docs#26759]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029ba69a-6673-836c-c69e-0105061904ea
* Version Independent ID: fc793abc-cd23-d6c5-2915-89ef59ca6d41
* Content: [IDE0060: Remove unused parameter - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0060.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0060.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I think the title translates as "slightly outdated".

**Comment by gewarren** [comment]
@sartoriprado What do you think should be improved in the article?
