### ISSUE TITLE
[Non-Breaking change in nullability]: XmlDocument.XmlResolver setter is now nullable

### ISSUE THREAD

**Issue by krwq** [dotnet/docs#26767]
### Description

XmlDocument.XmlResolver setter now accepts nullable reference.
Note that this is only a change in nullability and it's non-breaking.

```diff
public virtual System.Xml.XmlResolver XmlResolver { set { } }
public virtual System.Xml.XmlResolver? XmlResolver { set { } }
```

Changed between 5.0 and 6.0

related: https://github.com/dotnet/runtime/pull/45767

### Version

.NET 6 RC 1

### Previous behavior

XmlDocument.XmlResolver setter was annotated as not accepting null.

### New behavior

XmlDocument.XmlResolver setter now accepts null

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

previous annotation was incorrect.

### Recommended action

None.

### Feature area

XML, XSLT

### Affected APIs

System.Xml.XmlDocument.XmlResolver (setter)

**Comment by ericstj** [comment]
> Note that this is only a change in nullability and it's non-breaking.

If someone overrode this property in a derived type, they'd need to update to handle null, so in that sense it could be breaking.
