### ISSUE TITLE
[WinForms] API validate input parameters and throw ANE

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/docs#26763]
## Selected API validate input parameters and throw `ArgumentNullException`.

Selected API now validate input parameters and throw `ArgumentNullException` where previously a `NullReferenceException` could be thrown, if APIs were invoked with `null` input arguments.
Throwing `ArgumentException` is inline with the behaviours in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Version

.NET 6 RC 1

### Previous behavior

The listed API would throw `NullReferenceException` if invoked with `null` input arguments.

### New behavior

The listed API would throw `ArgumentNullException` if invoked with `null` input arguments.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Throwing `ArgumentNullException` is inline with the behaviors in .NET Runtime, and provides developers with a better debug experience clearly communicating which argument caused the exception.

### Recommended action

- Review and, if necessary, update the code to prevent passing `null` input arguments in the listed API.
- If the code is handling `NullReferenceException` replace (or supplement) it with handling `ArgumentNullException`.

### Feature area

Windows Forms

### Affected APIs

* [DataGridViewColumnStateChangedEvent](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcolumnstatechangedeventargs)
	- [x] [DataGridViewColumnStateChangedEvent(DataGridViewRow, DataGridViewElementStates) Constructor](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcolumnstatechangedeventargs.-ctor) when `dataGridViewColumn` is `null`

**Comment by RussKie** [comment]
❗ This is a binary breaking change, not a source breaking change,

**Comment by gewarren** [comment]
> ❗ This is a binary breaking change, not a source breaking change,

I updated the issue - thank you.
