### ISSUE TITLE
Update date/time article for .NET 6

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#26802]
Should we update this for .NET 6? For DateOnly, TimeOnly, and the improved time zone support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d2995c-cd29-3912-5d9c-9bfd76c7df5c
* Version Independent ID: 24332884-c808-ba59-5187-3d4b1670d269
* Content: [Dates, times, and time zones](https://docs.microsoft.com/en-us/dotnet/standard/datetime/)
* Content Source: [docs/standard/datetime/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/datetime/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 45531](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45531)

**Comment by RevealedFrom** [comment]
I think that should be more appropriate for a .NET BCL class or tutorial, not here. This tutorial should focus on setting up a .NET Core console app using VS Code.  The lowest common denominator of .NET classes should be used so as not to cloud up setting up for VS Code, unless .NET version differences require different treatment.

**Comment by adegeo** [comment]
Sure. I'll get on that.

**Comment by ericstj** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
@adegeo let me know if you need any help in that today or tomorrow. Otherwise I can help in January :-) 

You may use https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/ for more nfo.
