### ISSUE TITLE
Is a Single File Executable Required for a Windows Service?

### ISSUE THREAD

**Issue by sguidos** [dotnet/docs#26809]
The web page says "To create the .NET Worker Service app as a Windows Service, it will need to be published as a single file executable."  But when I do this, Assembly.Location does not return a value, as noted at https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=net-5.0#remarks

If I simply "build" the Worker Service project into a regular \bin folder, it appears that I can use the sc.exe command to install the resulting "normal" .exe as a Windows Service by specifying it in the "sc.exe binpath=" parameter.  At least my project is working on my development laptop so far....

So is it a *requirement" that you must publish the Windows Service as a Single File Executable, or only a suggestion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service#publish-the-app)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @sguidos,

It's a suggestion as it is cleaner, less dependent files lying around the file system. I'll update this wording in the article. Thank you
