### ISSUE TITLE
Folder .vscode and launch.json weren't created automatically

### ISSUE THREAD

**Issue by RevealedFrom** [dotnet/docs#26807]
Congratulations! This series is fantastic. Just what I wanted and needed.

I have a slightly different experience. From your **Enhance the app** section, suddenly a `.vscode` folder exists without explanation. 

The next lesson depends on the launch.json file. I had to create it manually by starting a new debug config. New users of VS Code might be lost.

Thanks once again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d7fd04-e358-9a83-aef2-bfcba1169699
* Version Independent ID: f5df932b-b092-2832-9c9a-61a9c43dcdb3
* Content: [Debug a .NET console application using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code?pivots=dotnet-5-0)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@RevealedFrom Thanks for reporting that - I'm adding an explanation that VS code asks about adding assets when you edit a .cs file for the first time in a folder, and when you answer yes, it creates the .vscode folder and launch.json.
