### ISSUE TITLE
"at runtime" v "run-time" v "runtime"

### ISSUE THREAD

**Issue by dsyme** [dotnet/docs#26812]
Regarding "runtime" v "run time" v "run-time", the current .NET docs are inconsistent

* 547 "run-time"
* 208 "at runtime" (thus largely ignoring the uses of .NET runtime etc. as a noun)
* 555 "run time"

**Comment by gewarren** [comment]
Style guide: https://styleguides.azurewebsites.net/Styleguide/Read?id=2719&topicid=31304

**Comment by dsyme** [comment]
OK! thanks. Pasting here for posterity, I think this can be closed.

> A runtime (noun) is an environment that is required to run programs that are not compiled to machine language. 
>
> Run time (noun) is the time during which an application is running.
>
> The adjective "run-time" describes something that is occurring or relevant at run time, as in "a run-time error."

I will have to bookmark this!

**Comment by gewarren** [comment]
If we have entries that say "at runtime" (which we do), I still think those should be fixed - since you wouldn't say "at compiletime". So I think it's worth keeping this issue open. I'll assign it to myself.
