### ISSUE TITLE
typeof(object).Assembly.FullName Give Different Results for Windows Service vs WinForms App

### ISSUE THREAD

**Issue by sguidos** [dotnet/docs#26810]
When I follow these instructions, but do a "regular" build instead of publishing a "single file executable" (for reasons I describe here - https://github.com/dotnet/docs/issues/26809) typeof(object).Assembly.FullName returns the System.Private.CoreLib.dll from the \bin folder.  But for a WinForms app, typeof(object).Assembly.FullName returns the GAC folder (e.g. C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Private.CoreLib.dll).  Why is this?

What I am trying to do is obtain the folder of my DotNet Core framework, which works in my WinForms app - is there a way to do this form within a Windows Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service#publish-the-app)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by MSDN-WhiteKnight** [comment]
>What I am trying to do is obtain the folder of my DotNet Core framework

RuntimeEnvironment.GetRuntimeDirectory (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeenvironment.getruntimedirectory?view=net-5.0) is a proper API for that. But if you Corelib is loaded from shared framework dir, that means your app literally runs on shared framework. If you run it via `dotnet` command it's an expected behaviour. Why do you think it should return something different?

**Comment by sguidos** [comment]
In my WinForms app, RuntimeEnvironment.GetRuntimeDirectory() returns the shared DotNet folder , in this case 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\'.  But in my dotNet 5 Windows Service

**Comment by MSDN-WhiteKnight** [comment]
Both RuntimeEnvironment.GetRuntimeDirectory and typeof(object).Assembly.Location should literally return the path to runtime the app is running on. It is shared framework for framework-dependent publish, or the application directory for self-contained.

>I'm really just trying to find the DotNet shared folder

You could hardcode `C:\Program Files\dotnet\shared\Microsoft.NETCore.App` path and lookup newest version folder under it. I don't think .NET is ever installed to different path. More correct way to compile code against framework assemblies is described here: https://github.com/dotnet/core/issues/2082#issuecomment-442713181

**Comment by IEvangelist** [comment]
Hi @sguidos,

To get the .NET Core root directory, you should rely on the well-known environment variables instead.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_root-dotnet_rootx86

I'm going to close this issue, as it's not really related to docs. Please let me know if there are any issues with the content.
