### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by GregoryMc** [dotnet/docs#26826]
This does not document the /username and /password parameters, so that you're not interactively prompted for them when installing a service to run as a specific user account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b07b20b-5937-9784-082f-8655bad1acdd
* Version Independent ID: 22eda03b-36bf-e612-384f-af3a3d2725a6
* Content: [Installutil.exe (Installer Tool) - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/tools/installutil-exe-installer-tool)
* Content Source: [docs/framework/tools/installutil-exe-installer-tool.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/installutil-exe-installer-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. The availability of these options depends on the installer in use, so I'm adding them as an example in the section that explains that some installers provide additional help text.
