### ISSUE TITLE
Internal classes registered in a IoC container should also be a reason to suppress

### ISSUE THREAD

**Issue by egil** [dotnet/docs#26832]
The article should also list the scenario where somebody has an internal class in a library they add to an `IServiceCollection` (IoC container) as a reason to suppress this rule.

E.g. a domain lib has an `interface IService` that an infrastructure lib implements in `internal class MyService`. The infrastructure lib includes an extension method `public static void AddInfraServices(this IServiceCollection services) => services.AddTrancient<IService, MyService>();` that allows users to register the `MyService` type in the IoC container without exposing it externally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d34eee1-2619-6701-31e2-7d56cc690ebb
* Version Independent ID: 8a9b0c36-3000-7b71-c0f2-a5b01e54174f
* Content: [CA1812: Avoid uninstantiated internal classes (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1812.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1812.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Evangelink @mavasani Should we add this to the article?

**Comment by Evangelink** [comment]
The comment makes sense, it's similar to the first bullet point (`The class is created through late-bound reflection methods such as...`).
