### ISSUE TITLE
Step 4 does not exist for my installation of Visual Studio.  Also, step 5 doesn't work because even though the create button is enabled, it does not function.

### ISSUE THREAD

**Issue by jedzielski** [dotnet/docs#26830]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957bb4fd-92c9-47ac-da7a-778cea12f429
* Version Independent ID: dd9058df-2586-7b1c-d1cc-ae1b82f047ed
* Content: [Create a .NET console application using Visual Studio for Mac - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac)
* Content Source: [docs/core/tutorials/with-visual-studio-mac.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-mac.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
What version of VS for Mac are you using?

**Comment by jedzielski** [comment]
Tom,
    The issue was resolved.  I had been doing “updates” to VS and it said it was current.  A complete delete and re-install fixed the issue.  John.

On Dec 2, 2021, at 5:24 PM, Tom Dykstra ***@***.******@***.***>> wrote:


EXTERNAL:




What version of VS for Mac are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fissues%2F26830%23issuecomment-985051006&data=04%7C01%7Cjdzielski%40stevens.edu%7C1bda8d2b2e514ee8975808d9b5e291a4%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637740806984810539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZwcszNmxibC5qCrMm5z%2BBNGytJ5M44zkdoEMUshIXLw%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWC2YAAUJ5JVDJ7AB4K4I5TUO7W3PANCNFSM5HM4GDAA&data=04%7C01%7Cjdzielski%40stevens.edu%7C1bda8d2b2e514ee8975808d9b5e291a4%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637740806984810539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qt02xErtvQZcDUn%2BPMAl9kbjV5qKEzhvq62AwpSTc1M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjdzielski%40stevens.edu%7C1bda8d2b2e514ee8975808d9b5e291a4%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637740806984820492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rVZRlK6932y0LNqiEJ3AZ7YNzsGhj%2FE8ehm%2FiI98U6w%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjdzielski%40stevens.edu%7C1bda8d2b2e514ee8975808d9b5e291a4%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637740806984820492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P%2BNXx4PlYqNHVoRIrPFIYwXnxzTDUvXCto2MNQpXAhQ%3D&reserved=0>.
