### ISSUE TITLE
Final version does not compile

### ISSUE THREAD

**Issue by ashleyo** [dotnet/docs#26833]
Very good, well-illustrated example whose shine is diminished by the fact that the final version does not compile! While it is no hardship to add the dummy Toast, etc, classes -- it would have been no hardship to add them to the example either! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reaching out @ashleyo 

Can you compare your final version with [the code in our repo](https://github.com/dotnet/docs/tree/main/docs/csharp/programming-guide/concepts/async/snippets/index/AsyncBreakfast-final). That version does build correctly.

That will help us find any discrepency.
