### ISSUE TITLE
[NewTopic] Learn Docker Basics with .NET Core

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#2683]
# [NewTopic] Learn Docker Basics with .NET Core
1. Table of Contents.
  .NET Core Guide -> Docker
2. Abstract
  Learn about Docker basic commands using .NET Core. This doc should be OS agnostic.
3. Outline
- [x] Introduction   
  - [x] .NET Core: easiest way to get started.
  - [x]  Briefly mention windows and linux. Link to [announcement](https://github.com/dotnet/announcements/issues/14) for more multi-arch info.
- [x] Installing Docker Client
      - [ ] Download Docker client (Either Windows, Linux, or Mac)
- [x] Essential Docker commands  
      - [ ] build
      - [ ] run
      - [ ] ps
      - [ ] stop
      - [ ] rm
      - [ ] rmi
- [x] Your first .NET Core Docker app
    - [x] Hello console app - Walkthrough of creating the .NET Core Hello World application to have something to Dockerize.
    - [x] Dockerize the Hello console app - Walkthrough of dockerizing the .NET Core Hello World application .
      - [x]  Inside a Dockerfile - Walkthrough of the simple Dockerfile.
      - [x] Create the Hello app Dockerfile 
      - [x] Build and run the Hello Docker app. 
- [x] Next Steps
    - [x] Debugging a container with Visual Studio Docker Tools
    - [x] Link to [aspnetcore DockerHub repo] or tutorial.

**Comment by mairaw** [comment]
@JRAlexander we're moving issues to either September or October/Quarter 4. Any idea when you'll get this one done? Thx!

**Comment by BillWagner** [comment]
@JRAlexander Rather than documenting all the Docker commands, I think we should list common commands, and link to the Docker documentation. https://docs.docker.com/

**Comment by JRAlexander** [comment]
@BillWagner Agree!

**Comment by JRAlexander** [comment]
@mairaw I am working on this concurrently with the Intro.
