### ISSUE TITLE
Update .NET Standard intro for .NET 5

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#2684]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

- [ ] Apply current guidance for terminology use
- [ ] PCLs are deprecated - remove PCL compatibility section
- [ ] Incorporate relevant information from What's new in .NET Standard 2.0 article and retire that article
- [ ] Incorporate relevant information from [.NET Standard in .NET 5 blog](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Instead of totally removing PCL info, we should link to information on how to port,

**Comment by mairaw** [comment]
@terrajobst what do you think? Should we remove the PCL compatibility from that topic now?

**Comment by mairaw** [comment]
@tdykstra do you remember what you meant by Apply current guidance for terminology use? I think this is no longer needed.

**Comment by tdykstra** [comment]
Setting priority to P1 as this is a high traffic doc.
