### ISSUE TITLE
CSC.EXE

### ISSUE THREAD

**Issue by bane53** [dotnet/docs#26844]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1ea586-7719-df69-7d8a-8a04cddb5543
* Version Independent ID: 691a6e9e-00ea-6210-c64a-659ba7930bec
* Content: [C# Compiler Options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/)
* Content Source: [docs/csharp/language-reference/compiler-options/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @bane53 👋 

Can you add more information on what you're looking for with this issue? Thanks.

**Comment by BillWagner** [comment]
Thanks for adding the details @bane53 

If you are learning C#, I'd focus on using the newer releases of .NET, and `dotnet build` rather than csc.exe. I'll close this, as we have numerous examples and articles on those newer tools.

**Comment by bane53** [comment]
Thank you for your response.
I would like to saw " we have numerous examples and articles on those newer
tools" it, PLS

**Comment by BillWagner** [comment]
@bane53 

I would start [here](https://docs.microsoft.com/dotnet/core/tools/). That describes the SDK tools, and will have links to examples.
