### ISSUE TITLE
Inconsistent use of casting int to real

### ISSUE THREAD

**Issue by rolerik** [dotnet/docs#26852]
The example for DatabaseLoader seems inconsistent to me.

Both Size and NumBed are INT in the database, and both are float in the model class.
But only NumBed is cast to REAL in the example.
> SELECT Size, CAST(NumBed as REAL) as NumBed, Price FROM House

 Is this a mistake in the documentation or something I am missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52d4fbe-df9c-f410-85b4-786b139e94d3
* Version Independent ID: ce6265fd-1d0b-4d58-c60d-178d512486b4
* Content: [Load data from files and other sources - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/load-data-ml-net.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/load-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @rolerik,

Good catch. Size should either have a cast since the schema is a float and it's represented as an int in the DB or represented as REAL in the DB like Price.
