### ISSUE TITLE
Error in a code example in the Iterators document

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/docs#26854]
There is an error in the code example under the text *"The compiler translates the first asynchronous sample into something similar to this construct:"*

Instead of `GetEnumerator` the correct is `GetAsyncEnumerator`, and instead of `MoveNext` the correct is `MoveNextAsync`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ba3a4c-1796-84b8-4152-b9806483ce86
* Version Independent ID: bd878489-9a4c-6d99-6c4c-c56e0387012b
* Content: [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/iterators)
* Content Source: [docs/csharp/iterators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/iterators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @theodorzoulias 

I've added it to our backlog to update when we next update this article. I've also added the "up for grabs" label for any community members that want to provide a PR before we make these updates.
