### ISSUE TITLE
dotnet publish command doesn't contain --source parameter

### ISSUE THREAD

**Issue by ISTAnsver** [dotnet/docs#26859]
Seems `--source` parameter is missed for `dotnet publish` command. It's possible to pass this parameter like in `dotnet restore` or `dotnet build`. This parameter is also missed in `dotnet publish -h` list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@ISTAnsver Thanks for reporting this -- I'm adding the option to the article.
