### ISSUE TITLE
Update .NET Architectural Components for .NET 5

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#2685]
https://docs.microsoft.com/en-us/dotnet/standard/components

The Introduction to .NET in the Fundamentals TOC introduces .NET 5 as the main implementation of .NET going forward and will only briefly mention other implementations of .NET. This article will be the link target for "more information" about other implementations of .NET.

**Comment by mairaw** [comment]
@BillWagner and I discussed and we think this one should be improved and cover more than just the different terminology.

**Comment by BillWagner** [comment]
I'd like to see this document cover:

1. The different implementation platforms for .NET Standard.
1. The relationship between those implementations.
1. How the architecture improves platform independence 
1. What .NET Standard really means.

**Comment by BethMassi** [comment]
@mairaw see slide 14 in this deck https://view.officeapps.live.com/op/view.aspx?src=https%3a%2f%2fsec.ch9.ms%2fsessions%2fc1f9c808-82bc-480a-a930-b340097f6cc1%2fbuild%2f2017%2fB8001.pptx

**Comment by cartermp** [comment]
@BillWagner That's basically the goal of this doc.  It's pretty impossible to make sense of .NET without something like this.  I initially wrote it because I got feedback about there being confusion about what .NET Standard is.  This is back when we were still calling it a "piece of paper", which I don't think stuck well with anyone.  We're now just saying that ".NET Standard = APIs everywhere", which is the right way to phrase it.  Changing ".NET Standard Library" to ".NET Standard" is mostly what we should do here, IMO.

**Comment by tdykstra** [comment]
#BethMassi That diagram leaves something to be desired.  The goal is to show the elements of a .NET implementation and .NET Standard and how they relate to each other, but the boxes in the top row of this diagram are app types/platforms, not .NET implementations or elements of one, such as BCLs, app frameworks, etc.  What I think would work better is something more like Immo's diagram but with a few more details and a little more accuracy about the not-perfect match between .NET Standard and the various BCLs.

**Comment by BillWagner** [comment]
@cartermp I agree with the .NET Standard Library => .NET Standard change.

The diagram update will also help. 

I'd also change the title "Architectural components" sounds like a catalog of the parts that make up .NET. This topic is more of an overview of the .NET ecosystem architecture. That's very useful.

**Comment by mairaw** [comment]
We're still waiting for the new diagram. Beth and co are still discussing this,
