### ISSUE TITLE
Typo” The C# 9.0 compiler is available starting with Visual Studio 2022 preview”

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#26856]
In https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records#prerequisites
It is said “ The C# 9.0 compiler is available starting with Visual Studio 2022 preview”.
Should it be c# 10.0 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294a082e-5584-008e-b83a-7f090d898cda
* Version Independent ID: d4a11dfa-2836-b423-63cd-c356e72e16a7
* Content: [Use record types - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records#prerequisites)
* Content Source: [docs/csharp/whats-new/tutorials/records.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @MNF 

I've opened a PR that addresses this issue.
