### ISSUE TITLE
Update docs for 6.0 on Fedora

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/docs#26868]
Would love to see release-day docs for Fedora! :heart: 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a30294-c9ae-4189-26d7-ee7db615c487
* Version Independent ID: 2e9467f4-8572-c8e4-6a10-69faf14ce46c
* Content: [Install .NET on Fedora - .NET](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-fedora)
* Content Source: [docs/core/install/linux-fedora.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Duplicate of #26889
