### ISSUE TITLE
ApplyButter method is not reflected in images.

### ISSUE THREAD

**Issue by Owenll66** [dotnet/docs#26860]
The method `void ApplyButter(Toast toast)` is mentioned in the code but is not reflected in images. The three images in this document only reflect the method `void ApplyJam(Toast toast)` but not `void ApplyButter(Toast toast)`.

![image](https://user-images.githubusercontent.com/37032357/140712313-9cd15964-1116-44d0-8ef8-0fce83416f0a.png)
![image](https://user-images.githubusercontent.com/37032357/140712384-629ec278-236c-4c22-9ff0-020a6f820df4.png)
![image](https://user-images.githubusercontent.com/37032357/140712431-02cdebab-e436-40f8-a03d-4cd35a0f86a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Closing without action. There haven't been any other notes to this effect.

The image blocks get larger and more cumbersome by adding additional detail. As they exist now, they do show the flow well.
