### ISSUE TITLE
Unclear code example

### ISSUE THREAD

**Issue by ion-storm-chaser** [dotnet/docs#26877]
There's no indication of where to initialize the DailyTemperature record via the private static example given, for a console application created for this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294a082e-5584-008e-b83a-7f090d898cda
* Version Independent ID: d4a11dfa-2836-b423-63cd-c356e72e16a7
* Content: [Use record types - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records)
* Content Source: [docs/csharp/whats-new/tutorials/records.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @ion-storm-chaser 

I'll update this tutorial in the next month.
