### ISSUE TITLE
Unable to install dotnet-sdk-6.0 using package manager instructions. 

### ISSUE THREAD

**Issue by kalluri-nb** [dotnet/docs#26879]
Using the below instructions to install dotnet sdk 6.0 on Ubuntu 21.10
``` bash
wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
```

Unable to install dotnet-sdk-6.0 using package manager instructions because the package is not found. 
`E: Unable to locate package dotnet-sdk-6.0`
`E: Couldn't find any package by glob 'dotnet-sdk-6.0'`
`E: Couldn't find any package by regex 'dotnet-sdk-6.0`'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by kalluri-nb** [comment]
Tried with the below command from the [github page](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md#2110-). Fails with 404
``` bash
wget https://packages.microsoft.com/config/ubuntu/21.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
```

**Comment by pkese** [comment]
Files haven't been uploaded to Microsoft's servers.  
There's `21.04`, but no `21.10`.

![image](https://user-images.githubusercontent.com/278492/140988543-69a479ae-9150-4a2a-8366-605b56f8f2f2.png)

**Comment by adegeo** [comment]
@rbhanda

**Comment by adegeo** [comment]
Do the commands to install `21.04` work? This may be the alternative until the packages are published via `21.10`

**Comment by leecow** [comment]
Yes, you can use the 21.04 instructions to install on 21.10.

**Comment by pkese** [comment]
Interestingly, the instructions worked after I manually removed `/etc/apt/sources.list.d/microsoft-prod.list`  
Previously it found an old version and running `sudo dpkg -i packages-microsoft-prod.deb` didn't overwrite the old file.  
(The old file was hanging there after upgrading from 20.04).

**Comment by kalluri-nb** [comment]
> Interestingly, the instructions worked after I manually removed `/etc/apt/sources.list.d/microsoft-prod.list` Previously it found an old version and running `sudo dpkg -i packages-microsoft-prod.deb` didn't overwrite the old file. (The old file was hanging there after upgrading from 20.04).

This worked for me. Am able to install sdk-6.0 from  https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb

**Comment by philomath-code** [comment]
21.10 is not working on Linux Mint 20.2. 
21.04 is working and just confirming since it has not been fixed as of now.
