### ISSUE TITLE
Please provide an expected timeline for availability of dotnet 6 on Fedora 

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [dotnet/docs#26889]
The page says: "Installing .NET 6 through the default package repositories is coming soon". Giving a link to the place this is tracked and/or providing an expected timeline (maybe based on previous versions of dotnet) can be helpful to users to plan: should they wait, or should they accept the cost of switching to non-fedora repos and then switching back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a30294-c9ae-4189-26d7-ee7db615c487
* Version Independent ID: 2e9467f4-8572-c8e4-6a10-69faf14ce46c
* Content: [Install .NET on Fedora - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora)
* Content Source: [docs/core/install/linux-fedora.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It's not up to us, it's actually published by the redhat team. I can't find the thread, but I think they said a few week to a month

/cc @omajid

**Comment by omajid** [comment]
Hi! This is something we (Fedora maintainers - which includes folks from Red Hat, Microsoft and other community members) are working on. It's hard to give a firm ETA, but I am hopeful it should be available in 2 weeks or so, unless we run into major issues.

**Comment by AlirezaHaghshenas** [comment]
@omajid Can you provide a link to where it is tracked?
In the past, I had problems with dotnet on Fedora as well and knowing where this is organized is helpful.
Thanks

**Comment by omajid** [comment]
Let's track that using: https://bugzilla.redhat.com/show_bug.cgi?id=2021763

**Comment by adegeo** [comment]
I'll update the doc with that link! Thanks @omajid

**Comment by omajid** [comment]
Copying from https://bugzilla.redhat.com/show_bug.cgi?id=2021763#c11:

> 
> I have built .NET 6 for all supported Fedora versions now.
> 
> Installing it should be a matter of `dnf install dotnet-sdk-6.0` when it's available.
>
> Rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2021-4df64a6e1a
>  This should be available in the next compose (hopefully later today?)
>
> Fedora 35: https://bodhi.fedoraproject.org/updates/FEDORA-2021-9f61773163
>  This is getting pushed to the updates-testing repository. Please see 
>  https://fedoraproject.org/wiki/How_to_test_updates#Steps_to_follow on
>  how to enable the updates-testing repository. Once it has been tested
>  (users provide positive karma or it reaches the 7 day waiting period),
>  it should become available in the main Fedora 35 repository.
>
> Fedora 34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-22cd8b68c0
>   This is getting pushed to the updates-testing repository. Please see 
>   https://fedoraproject.org/wiki/How_to_test_updates#Steps_to_follow on
>   how to enable the updates-testing repository. Once it has been tested
>  (users provide positive karma or it reaches the 7 day waiting period),
>  it should become available in the main Fedora 34 repository.
