### ISSUE TITLE
Source generation support in ASP.NET Core - Example code incorrect

### ISSUE THREAD

**Issue by IGx89** [dotnet/docs#26892]
```
services.AddControllers().AddJsonOptions(options => options.AddContext<MyJsonContext>());
```
is wrong (won't compile). It should instead be
```
services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.AddContext<MyJsonContext>());
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee53c3dc-df79-82ef-ce25-3233ff292c55
* Version Independent ID: 558903e9-8173-464e-ff8b-7744419ad7e4
* Content: [How to use source generation in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation?pivots=dotnet-6-0#source-generation-support-in-aspnet-core)
* Content Source: [docs/standard/serialization/system-text-json-source-generation.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-source-generation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@IGx89 Thanks for reporting that!  I'm fixing it in #26900
