### ISSUE TITLE
Guidance for polymorphic serialization and deserialization of objects of the same class

### ISSUE THREAD

**Issue by paolovalladolid** [dotnet/docs#26894]
[Enter feedback here]
In this article, you recommend that non-primitive properties of a class be declared as type object for polymorphic serialization:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism

However in the polymorphic deserialization article you have an an example class that has non-primitive properties that are class types instead of type object.

Let us say that I want to serialize a WeatherForecastAsObject and send it to another application.  Then I get another WeatherForecastAsObject back from the other application as JSON.  I want to deserialize it with my custom converter.  What do do I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)
* Content Source: [docs/standard/serialization/system-text-json-converters-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@layomia @steveharter can you help with this question?

**Comment by tdykstra** [comment]
The polymorphic deserialization strategy in the custom converters article relies on using the converter for both serialization and deserialization. It sets a discriminator field during serialization, which won't happen when you serialize as object.

But if you're serializing and deserializing a derived class and you know what the class is (the issue title refers to "objects of the same class"), you can serialize as object and round-trip the JSON back to the original derived class without a custom converter.

If this isn't your scenario, please provide some code examples that show what you're trying to do.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
