### ISSUE TITLE
Socket example shows anti-pattern of async usage

### ISSUE THREAD

**Issue by mgravell** [dotnet/docs#26911]
This is a confusing a bad way of demonstrating async, [and is it actively confusing users](https://stackoverflow.com/questions/69911260/c-sharp-asynchronous-client-socket-example)

IMO the page is actively harmful, and anyone basing code on this example (with the `WaitOne()` approach blocking the main thread, plus the async callbacks) is worse off than if they'd just use sync code. If the intent is to show async socket usage, frankly: rewriting this page with the `await` approach (relatively new) would be a huge improvement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e33dad-b973-a334-e6d2-203472cb9aca
* Version Independent ID: 8a42e2e8-6617-74e0-81fc-009df48fff82
* Content: [Asynchronous Client Socket Example - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-client-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-client-socket-example.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/asynchronous-client-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by BillWagner** [comment]
Thanks @mgravell for noting this.

We've got a number of outdated samples for async that need to be addressed. We'll be updating these over the next several months.

**Comment by antonfirsov** [comment]
This has been addressed by #30759.
