### ISSUE TITLE
[New Topic] Develop and Debug with Docker in Visual Studio

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#2692]
# [New Topic] Develop and Debug with Docker in Visual Studio

1. Table of Contents Location

   - TBD

2. Abstract
   Learn how to debug with Docker in Visual Studio.

3. Outline
    - [ ] Have Docker 4 windows installed
    - [ ] Screenshots of VS file new project.
    - [ ] Note that currently Adding Docker support only works if there are no Docker artifacts already in your project.

4. Reviewer Request
@erickson-doug

**Comment by mairaw** [comment]
@JRAlexander same with this one? Why is this one external? Is this going to the vs docs repo?

**Comment by mairaw** [comment]
Ping @JRAlexander

**Comment by JRAlexander** [comment]
@mairaw - Yes, It's external for us and really should be here only for tracking purposes.

**Comment by mairaw** [comment]
For which repo is this work @JRAlexander? VS? Should we file an issue there instead?

**Comment by JRAlexander** [comment]
Yes, probably so. Visual Studio is where it should be. I can file.

**Comment by mairaw** [comment]
Cool. Thanks @JRAlexander!

**Comment by JRAlexander** [comment]
Refiled in VS repo. https://github.com/MicrosoftDocs/visualstudio-docs/issues/688 Closing this issue.
