### ISSUE TITLE
[Scenario] Create a get started path with .NET Core

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2700]
This scenario will provide the first steps for someone new to .NET Core. It will assume no previous exposure to .NET, and will conclude with a working application. It should take most users less than 15 minutes to complete the scenario.

**Comment by tdykstra** [comment]
@BillWagner I assume this is adequately covered by the get-started tutorials; if not, please reoopen.
https://docs.microsoft.com/en-us/dotnet/core/get-started
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-create-console-app
https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos
