### ISSUE TITLE
Recommendation for .NET Version slightly confusing

### ISSUE THREAD

**Issue by Bownee** [dotnet/docs#27022]
Hello everybody

I hope this is the right place for my comment. On https://dotnet.microsoft.com/download/dotnet there's a slightly confusing text regarding the recommended version. The tooltip for .NET 5 says that it is the recommended version. But it seems that .NET 6 is recommended as well. This might be confusing for people starting with .NET.
The addition "We recommend using this release." on the .NET 5 tooltip can potentially just be removed.

<img width="494" alt="Confusing-Recommendation" src="https://user-images.githubusercontent.com/94079193/141190317-a3e32491-28ad-4697-9302-88b4722038f8.png">

**Comment by tdykstra** [comment]
@mairaw Where should this issue go?

**Comment by mairaw** [comment]
I've changed that already shortly after the release. Let me know if there’s still some confusion.
