### ISSUE TITLE
[Scenario] Moving projects to Docker

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2702]
This scenario will explain to developers how to migrate their existing projects to Docker containers.

**Comment by JRAlexander** [comment]
I think this is handled by https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images. @BillWagner, agree?

**Comment by BillWagner** [comment]
I think all the information is in the doc you reference. However, I don't think the information is structured to make it clear to a reader that it's got the information they seek.  I'd recommend adding a new introduction that introduces the scenario, and uses the phrase "lift and shift" to explain that the reader will learn how to take an existing application, migrate to docker and run it in a container. Along the way, you'll learn important concepts about working with docker. 

Thoughts @JRAlexander ?

**Comment by JRAlexander** [comment]
I agree. I think we could create a new doc that specifically addresses that scenario, but looks very similar to the current one.
