### ISSUE TITLE
Suggestions for alternative to FtpWebRequest. 

### ISSUE THREAD

**Issue by vip-ehowlett** [dotnet/docs#27028]
The warning suggests to use the HttpClient however, the documentation ( and name ) don't indicate that FTP is supported. It appears that WebClient does but the documentation on that page also suggests using HttpClient. In the case of FTP should WebClient be used or is there an FtpClient in-the-works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cef6c88-811c-4651-4e8f-87365a799dda
* Version Independent ID: 3d53a1d2-c6bf-7698-02ed-759679547f2b
* Content: [Breaking change: WebRequest, WebClient, and ServicePoint are obsolete - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated)
* Content Source: [docs/core/compatibility/networking/6.0/webrequest-deprecated.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/networking/6.0/webrequest-deprecated.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@aik-jahoda Can you answer this question?

**Comment by aik-jahoda** [comment]
@vip-ehowlett, unfortunately there is no FTP support in HttpClient. You should use 3rd party library of your choice to support FTP.

**Comment by vip-ehowlett** [comment]
For those whole stumble upon this, at the time of writing, these are 3rd party libraries that are available:

- https://github.com/robinrodricks/FluentFTP
- https://github.com/sparkeh9/CoreFTP (inactive for ~3 years)
- https://github.com/FubarDevelopment/netftp (inactive for ~5 years)
- https://github.com/tobias-tengler/Ftp.Net (inactive for ~ 2years)

Note: I haven't used any of these and am not promoting any of them. They are just what I've been able to find with a quick google search. As of writing it, it appears like FluentFTP is the best option.

**Comment by kbajpai** [comment]
Thanks. I have moved to FluentFTP, though I was using WinSCP earlier but that is not supported on Linux.
