### ISSUE TITLE
Add a note to creating a new compilation object after adding a source in source generators overview

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#27042]
See https://stackoverflow.com/questions/69853257/sourcegenerator-attribute-constructorarguments-is-empty.

From the OP on Discord:

![image](https://user-images.githubusercontent.com/31348972/141320506-1a7285d4-e649-4aa9-97f1-e9965b88239b.png)

This scenario is really **very very common** that I think should be noted, since this is the number 1 article in Google search results, where people will expect to find this kind of information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @mikadumont

**Comment by BillWagner** [comment]
I was going through the issues on this article. I'd like to address this by making a new tutorial with more of a real world scenario using attributes.
