### ISSUE TITLE
Emphasize that "using static" applies to enums.

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#27052]
I discovered by accident that we can use "using static" with enum types and thus be able to refer to enum members in code without needing to qualify them.

This isn't really very evident from the documentation so it would help to just mention this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7569e51d-92c7-294a-2d5f-e1ab3c35fdf8
* Version Independent ID: 86a1c11a-1d3c-902b-6cf3-5c004c59a856
* Content: [using directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)
* Content Source: [docs/csharp/language-reference/keywords/using-directive.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-directive.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That is a great suggestion @Korporal 

I'll add it to our list for updates to this article.

I've also added the "up for grabs" label if anyone wants to submit a PR in the meantime.
