### ISSUE TITLE
Typo in “ Warning! short description not initialized.”

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#27067]
In the example

public ProductDescription() // Warning! short description not initialized.

shortDescription Is a variable name and should be 1 word with capital D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c4bf74-8064-6c45-d5c8-2bbdb0113895
* Version Independent ID: 3250ed35-9410-87f6-ba3e-258c85fbc7f1
* Content: [Nullable reference types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types#nullable-references-and-static-analysis)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-reference-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @MNF 

I see that there's a PR already open to address this issue. I'll review those shortly.
