### ISSUE TITLE
NETSDK1148 errors being reported as NETSDK1152

### ISSUE THREAD

**Issue by haacked** [dotnet/docs#27064]
### Describe the bug

Running `dotnet publish` reports an error

>  error NETSDK1152: Found multiple publish output files with the same relative path

However that appears to actually be [error NETSDK1148](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output). I could find no reference to NETSDK1152

### To Reproduce

I don't have a minimal repro. I have a solution with multiple projects that use NPM modules. The relevant ones seem to be:

`<Project Sdk="Microsoft.NET.Sdk.Razor">`
`<Project Sdk="Microsoft.NET.Sdk.Web">`

As these two projects use NPM for managing client dependencies.

### Further technical details

- __OS__:  Ubuntu 20.04.3 LTS
- __dotnet__: version 6.0.100
- __CI__: GitHub Actions runner 2.284.0

**Comment by dsplaisted** [comment]
@tdykstra What I think happened here is that we originally added this error to the 6.0 branch of the SDK as NETSDK1148, and documented it as such.  However, we subsequently added more error messages to a 5.x branch, so when we merged those changes forward to 6.0 we had to change the DuplicatePublishOutputFiles error code to NETSDK1152 to make room for the errors from the 5.0 branch.  However, we never updated the docs with the new error codes.

Can you review all of the recently added (ie in 5.x or 6.x) error codes in the docs and make sure that they match the current error codes listed here? https://github.com/dotnet/sdk/blob/release/6.0.1xx/src/Tasks/Common/Resources/Strings.resx

**Comment by dsplaisted** [comment]
@haacked You would need to put that logic in `Directory.Build.targets`, so that it would update the `Content` items after they had been included.  If you put it in `Directory.Build.targets` then it is one of the first things evaluated, and there aren't any `Content` items to update then.

**Comment by dsplaisted** [comment]
Thanks for catching the NETSDK1174 issue @tdykstra.  I've filed https://github.com/dotnet/sdk/issues/22639
