### ISSUE TITLE
CancellationToken example is bogus

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/docs#27061]
The example on this page spawns a Task running on a background thread using Task.Run, and in response to the Enter key being pressed that Task triggers cancellation of another asynchronous Task using `CancellationTokenSource.Cancel()`.

However both Tasks are awaited using `Task.WhenAny`, and the Task that calls `CancellationTokenSource.Cancel()` exits once Enter is pressed, which causes the program to exist whether `CancellationTokenSource.Cancel()` is called or not.

What should happen is that both Tasks should be awaited using `Task.WhenAll`.

This whole page is not great documentation. Rather that make the reader wade through 12 pages of bloated example that doesn't even work correctly I think it would be better to just explain how CancellationTokens work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [Cancel a list of tasks (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Well noted @Neutrino-Sunset 

We are planning to update all our async samples in the next few cycles. I've added this to the list.

**Comment by IEvangelist** [comment]
Hi @Neutrino-Sunset,

I just ran the example source code, and it does cancel the downloads. The cancellation token flows through to the `ProcessUrlAsync` call, and from there to each respective Task-returning invocation; namely the `client.GetAsync` and the `response.Content.ReadAsByteArrayAsync`. Here is the sample output, where I press the <kbd>ENTER</kbd> key during exeuction:

```
Application started.
Press the ENTER key to cancel...

https://docs.microsoft.com                                      126,018
https://docs.microsoft.com/aspnet/core                           91,806
https://docs.microsoft.com/azure                                420,128

ENTER key pressed: cancelling downloads.

Application ending.

..\docs\csharp\programming-guide\concepts\async\snippets\cancel-tasks\cancel-tasks\bin\Debug\net5.0\cancel-tasks.exe (process 35608) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

Could you please be a bit more specific with what you believe is incorrect here? Did you try running the sample. The usage of `WhenAny` is essentially a race, and if the cancellation wins the race - the other async calls are cancelled from the signal call to `.Cancel`. Do you agree @BillWagner, or am I missing something here?

**Comment by Neutrino-Sunset** [comment]
If you comment out `s_cts.Cancel();` in the `cancelTask` method the application will still exit immediately when `Enter` is pressed because the application is awaiting on `WhenAny(new[] { cancelTask, sumPageSizesTask });`. Pressing `Enter` causes the `cancelTask` to complete, `WhenAny` is triggered and the application will then exit. The fact that the primary thread is awaiting on `ProcessUrlAsync` won't stop it from exiting when the Main method exits.
