### ISSUE TITLE
XML documentation tags: outdated information about Intellisense tooltips

### ISSUE THREAD

**Issue by mdro** [dotnet/docs#27060]
The section about the `<summary>` tag says "The text for the `<summary>` tag is the only source of information about the type in IntelliSense".
This is no longer correct, since some version of VS2019 the contents of `<remarks>` are also displayed in the tooltip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcb925f-ef72-9a64-3762-c0b4a96f9dc4
* Version Independent ID: d135d0a6-53d2-1567-0b1b-7aae5e07739f
* Content: [Recommended XML documentation tags for a class and its members](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#summary)
* Content Source: [docs/csharp/language-reference/xmldoc/recommended-tags.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/recommended-tags.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @mdro 

I've added this to our backlog to address when we next update this article. I've also added the "up for grabs" label if anyone wants to submit a PR in the meantime.

**Comment by gewarren** [comment]
I'm not seeing the remarks in the Tooltip. Can you share a screenshot?

**Comment by mdro** [comment]
> I'm not seeing the remarks in the Tooltip. Can you share a screenshot?

I'm getting some error while uploading, but it's simply summary, empty line, remarks in the box.
Note that it does not appear for the standard library or any of the handful of Nuget.org packages I checked. Presumably they don't include their remarks in the code or strip the xml file.
But it does work for our own code, even when consumed as packages from our private repo.

**Comment by gewarren** [comment]
I do see remarks in the IntelliSense XML files for the .NET library. So I'm not sure what's causing the remarks to display in your case.
