### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by vip-ehowlett** [dotnet/docs#27084]
With .Net 6 there is now a deprecation warning thrown when constructing a WebRequest. According to https://github.com/dotnet/docs/issues/27028 FTP is no longer officially supported and we should use 3rd party library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9294af6-b587-a35a-09b5-1605f626574e
* Version Independent ID: 5b00d11d-89c8-aee7-167b-592e28203b5a
* Content: [FTP - .NET - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/ftp)
* Content Source: [docs/framework/network-programming/ftp.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/ftp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment]
@vip-ehowlett This page is specific to .NET Framework, so FTP is still supported in this case. You won't get the SYSLIB0014 warning if your project targets .NET Framework.

**Comment by vip-ehowlett** [comment]
I suggest we put a little disclaimer in the doc for that, then, because this page is the first to pop up when you google ".net ftp".
