### ISSUE TITLE
'Avoid multiple asserts' is not good advice (and should be rewritten as Avoid multiple acts)

### ISSUE THREAD

**Issue by pauldendulk** [dotnet/docs#27099]
I am aware that this advice is repeated all over the internet but it is still not a good advice. 😄

The 'Bad' example is indeed bad but it is not because of the multiple asserts but because of the multiple acts

[Fact]
public void Add_EdgeCases_ThrowsArgumentExceptions()
{
    Assert.Throws<ArgumentException>(() => **stringCalculator.Add(null)**); // <-- Act 1 in bold
    Assert.Throws<ArgumentException>(() => **stringCalculator.Add("a")**); // < -- Act 2 in bold
}

Parameterized tests are mentioned as a solution, but parameters are typically only applied in the act of test. This can also be seen in the 'Good' example on the page. The 'input' parameter is only used in the act line.

The page mentions that with multiple asserts it does not 'give you the entire picture as to why your tests are failing', but the opposite is true. With multiple asserts you can test exactly what is wrong with your response. A first asserts can check for null, a second one can assert the item count, a third assert can check the content of the expected items. Such a failing test can tell you exactly what is wrong. The fact that the last assert is never called is not a problem at all, it would not make sense.

The general argument of the section is valuable and would still hold if it was rewritten as 'Avoid multiple acts'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-multiple-asserts)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi 👋 @pauldendulk
Thank you so much for posting this issue. We really appreciate it. If you're willing and able to propose changes to this content, I'd be happy to review. Just reference this issue in the PR, thank you.
