### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by SymboLinker** [dotnet/docs#27100]
> Ideally, you should **updated** your [...]

should become

> Ideally, you should **update** your [...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655dd674-cbb3-2a90-a49c-8eaad8ee4fc9
* Version Independent ID: 99c3d060-f719-4d71-7851-08818e440384
* Content: [Breaking change: Generate error for duplicate files in publish output - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output)
* Content Source: [docs/core/compatibility/sdk/6.0/duplicate-files-in-output.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/duplicate-files-in-output.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you @SymboLinker. This will be fixed by #27093.
