### ISSUE TITLE
Some thoughts about the "Source Generators" page

### ISSUE THREAD

**Issue by Muitsonz** [dotnet/docs#27119]
I followed the tutorial in the page to create a first source generator and finally understand how to use it. And I think the page doesn't explained well on some points.

1). In section "Get started with source generators", step 4 "Create a .NET standard library project that looks like this":
The generator library should be no higher than std2.0 as far as I learned later, I guess an extra note that reminds beginners can avoid some unnecessary errors when they create new library projects for generators.

2). The tutorial ends by "You will currently need to restart Visual Studio to see IntelliSense and get rid of errors with the early tooling experience.", ~~but I'm not so lucky. (in VS2022 17.0, with nuget packages CodeAnalysis.Analyzers v3.3.3 and CodeAnalysis.CSharp v4.0.1)~~
I finally solved the problem by adding project setting "EmitCompilerGeneratedFiles" and "CompilerGeneratedFilesOutputPath". Why aren't they introduced? I think it's also easier to debug if we can view generated files directly. Or maybe files were always saved on disks when you wrote the docs?
--edit
Well, restart did work for me now. I guess I left another solution open so the VS process didn't reload.
Anyway, what do think about explaining the project settings? I even didn't find anything about them in cookbook (https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for providing these thoughts @Muitsonz 

We'll be updating these and adding more over the next few sprints. I'll address your thoughts then.
