### ISSUE TITLE
Missing any mention of VC++ Redistributable libraries.

### ISSUE THREAD

**Issue by RobLSDev** [dotnet/docs#27129]
The MklImports.dll has a dependency on VC++ redistributable, and not all of our container images had that on them.  This should really be spelled out as a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f39c5a-b353-4a50-9719-06074465e800
* Version Independent ID: 6e8ac4b9-43a0-84d7-35d2-b9f1bc88a4d9
* Content: [Install extra ML.NET dependencies - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies)
* Content Source: [docs/machine-learning/how-to-guides/install-extra-dependencies.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/install-extra-dependencies.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by gewarren** [comment]
Closing due to age of issue.

**Comment by gewarren** [comment]
@RobLSDev I'm not sure, but since there was no traction in 2.5 years and things have likely changed since then, I closed the issue. Is this issue still relevant?
