### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jiangjinnan** [dotnet/docs#27121]
Background garbage collection is performed on one or more dedicated threads, depending on whether it's **background** or server GC, and applies only to generation 2 collections.

**background** =>**work station**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d109272-00cf-f922-d683-0e5c7b87fcd3
* Version Independent ID: 720ea779-a955-7fde-eb2e-efacc449aa0d
* Content: [Background garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/background-gc#feedback)
* Content Source: [docs/standard/garbage-collection/background-gc.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/background-gc.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks @jiangjinnan
