### ISSUE TITLE
[Scenario] Add tutorial to show how to consume .NET Standard libraries with .NET Framework projects, for example

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2712]
Developers that build libraries and applications that use the .NET Framework will take dependencies on libraries that are part of .NET Standard, or rely only on the .NET Standard. 

This tutorial will show how to add those libraries as dependencies, what it adds in csproj files, and what it means for build processes.

**Comment by sputier** [comment]
Alright, I'm in for this one !
