### ISSUE TITLE
Example for top level statements

### ISSUE THREAD

**Issue by biltongza** [dotnet/docs#27127]
Is there any plan for documentation that shows how this is best achieved using top level statements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @biltongza - I added this as part of a larger PR that is updating all these samples to .NET 6 and C# 10. This will be addressed there, thank you.

https://github.com/dotnet/docs/pull/27051
