### ISSUE TITLE
unit-testing-best-practices.sln does not compile with error CA2208 related to ArgumentException 

### ISSUE THREAD

**Issue by pauldendulk** [dotnet/docs#27133]
### Reproduce

Checkout the main branch and build with VS2020. The compile fails on this line:
```csharp
throw new ArgumentException(nameof(numbers));
```
With this error:
```console
Error	CA2208	Method Add passes parameter name 'numbers' as the message argument to a ArgumentException constructor. Replace this argument with a descriptive message and pass the parameter name in the correct position.	unit-testing-best-practices	.\docs\samples\snippets\core\testing\unit-testing-best-practices\csharp\unit-testing-best-practices\StringCalculator.cs	13	Active
```

### Cause

The root has a Directory.Build.props with this setting
```
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
```
This detects the `CA2208'. The name of the parameter is passed as the first parameter (the message) instead of the second.

The root also has an .editorconfig which has this setting to treat it as error:
```console
# CA2208: Instantiate argument exceptions correctly
dotnet_diagnostic.CA2208.severity = error
```

### Solution

A simple solution suggested by the ['how to fix'](https://docs.microsoft.com/nl-nl/dotnet/fundamentals/code-analysis/quality-rules/ca2208#how-to-fix-violations) is to use null for the message like this:

```csharp
throw new ArgumentException(null, nameof(numbers));
```

Although null is passed in the message of the ArgumentException object will be:
> Value does not fall within the expected range. (Parameter 'numbers')

**Comment by BillWagner** [comment]
Thanks for noting this and submitting the PR @pauldendulk 

We'll continue the discussion in the PR.
