### ISSUE TITLE
Records (C# reference)|Positional syntax for property definition – compiler action taken list is wrong

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27149]
> When you use the positional syntax for property definition, the compiler creates:
> - A public init-only auto-implemented property for each positional parameter provided in the record declaration.
>     - For record types and readonly record struct types: An init-only property can only be set in the constructor or by using a property initializer.
>    - For record struct types: A read-write property that can be set in a constructor, property initializer, or assignment after construction.
> - A primary constructor whose parameters match the positional parameters on the record declaration.
> - For record struct types, a parameterless constructor that sets each field to its default value.
> - A Deconstruct method with an out parameter for each positional parameter provided in the record declaration. This method is provided only if there are two or more positional parameters. The method deconstructs properties defined by using positional syntax; it ignores properties that are defined by using standard property syntax.

### # 1
> A public init-only auto-implemented property for each positional parameter provided in the record declaration.

That _init-only_ is there extra. See point 2 in original text.
### # 2
> For record types and readonly record struct types: An init-only property can only be set in the constructor or by using a property initializer.

`Init-only` property can be set in constructor or by property initializer in all cases not just on record. This should be reworded somehow. Likely just noting `init-only` choice for autogenerated properties.
### # 3
> For record struct types: A read-write property that can be set in a constructor, property initializer, or assignment after construction.

Again this is normal behavior of (R/W) property. Basically the same as # 2.
### # 4
> A primary constructor whose parameters match the positional parameters on the record declaration.

In contrast to # 5 why there are only noted parameters?
### # 5
> For record struct types, a parameterless constructor that sets each field to its default value.

A lie. Such ctor is not generated even for `non-record` `struct`.
### # 6
> This method is provided only if there are two or more positional parameters.

A lie. All `class`, `struct` and `readonly struct` `records` get generated `Deconstruct` method even for just 1 positional parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @Uzivatel919 

I'll add this to the next sprint to address.

One correct to your notes on # 5:  

> Such ctor (parameterless ctor) is not generated even for non-record struct.

This has changed for C# 10.  See the [Parameterless struct constructors](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-10.0/parameterless-struct-constructors#constructors) specification.

**Comment by Uzivatel919** [comment]
For a little, @BillWagner.

It is interesting feature, you pointer out but… I verified it and it works exactly as it is stated: “If the struct declaration does not contain any explicit instance constructors, and the struct has **field initializers**…”.

This .ctor is generated only for field initializers of struct.

Declaration

```csharp
internal struct ExampleStruct
{
  private int _int = 3;
  private string? _string;
  
  public ExampleStruct(int @int, string? @string)
  {
      _int = @int;
      _string = @string;
  }
}
```

Compilation (decompilation)
```csharp
internal struct ExampleStruct
{
  private int _int;

  private string? _string;

  public ExampleStruct(int @int, string? @string)
  {
    _int = 3; // See there initializer outfactoring.
    _int = @int;
    _string = @string;
  }
}
```

----

```csharp
internal struct ExampleStruct2
{
  private int _int = 3;
  private string? _string;
}
```
Decompilation
```csharp
internal struct ExampleStruct2
{
  private int _int;

  private string? _string;

  public ExampleStruct2()
  {
    _int = 3;
  }
}
```
---
```csharp
internal struct ExampleStruct3
{
  private int _int;
  private string? _string;
}
```
Decompilation
```csharp
internal struct ExampleStruct3
{
  private int _int;
  private string? _string;
}
```

**Comment by Uzivatel919** [comment]
@BillWagner, I hit interested statement in [C# 6.0 draft specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/structs#constructors)
> Unlike a class, a struct is not permitted to declare a parameterless instance constructor. Instead, every struct implicitly has a parameterless instance constructor which always returns the value that results from setting all value type fields to their default value and all reference type fields to null (Default constructors). 

Beside it can be more concise (`null` is `default(T)` for _T-reftypes_) it seems that actual compilation is treated as implementation detail.

```csharp
struct StructWithField
{
  private readonly int i;
  public StructWithField(int i) => this.i = i;
  public static StructWithField Default => new StructWithField(); 
  public static StructWithField Zero => new StructWithField(0);
}
```

• `Default` is just initialized by [_initobj_](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.initobj?view=net-6.0).
• `Zero` is constructed using [_newobj_](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.newobj?view=net-6.0).
