### ISSUE TITLE
.NET 6 console project template refactoring

### ISSUE THREAD

**Issue by Budsy** [dotnet/docs#27145]
In Visual Studio 2022 Current, using the new console project template gives a nice clean code arrangement in the Program.cs file. I have found that the VS refactoring tools don't work on the new local methods/functions. ...Unless I'm missing something. On a related note, do these local functions allow the XML  documenting features to work normally?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
@Budsy Can you explain what specific refactorings don't work that were previously working? This will then belong to dotnet/roslyn repository.

Regarding the local functions part, they currently don't allow doc comments. But might in the future. See https://github.com/dotnet/csharplang/issues/2110

**Comment by surfmuggle** [comment]
Partly off-topic
Was there a public discussion for changing the code created by the console template?
Can it still be accessed?
