### ISSUE TITLE
Nondestructive mutation – space for improvements on `with` with `record struct`

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27157]
> The compiler doesn't synthesize a copy constructor for record struct types. You can write one, but the compiler won't generate calls to it for with expressions. Instead, the compiler uses assignment.

I guess nobody can nick what exactly is _assginment_ in sentence “Instead, the compiler uses assignment.”. I am for something like _Compiler instead employs value type characteristics and assigns instance to new variable effectively making copy. Then values are assigned._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#nondestructive-mutation)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Uzivatel919 

I'm going to have to dive into the spec and some generated code to be sure, but you're version would imply that each member is assigned independently. I don't think that's required for a `struct` type. I think an implementation is allowed to blit copy the memory for the entire struct.

**Comment by Uzivatel919** [comment]
@BillWagner, I guess we’re missing each other but relevant specification is https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/structs#assignment.

Basically I was about to _underscore_ that `struct` is value type, thus gets copies on assignment.
