### ISSUE TITLE
Built-in formatting for display – reference types same as value types *print* result of `ToString` method call

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27158]
> For reference types, the type name of the object that the property refers to is displayed instead of the property value. In the following example, the array is a reference type, so System.String[] is displayed instead of the actual array element values:

`Person { FirstName = Nancy, LastName = Davolio, ChildNames = System.String[] }`

---

Above is complete nonsense. See C# interactive sample.

```csharp
> class ClassWithOveriddenToString
{
  public override string ToString() => "Hi, the type name is not available right now. But I’m an object definitely!";
}
> struct Struct { }
> record struct RecStru(ClassWithOveriddenToString obj, Struct val);
> { Write(new RecStru(new ClassWithOveriddenToString(), new Struct()).ToString()); }
"RecStru { obj = Hi, the type name is not available right now. But I’m an object definitely!, val = Submission#28+Struct }"
```
So statement from documentation is fairly far away from truth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#built-in-formatting-for-display)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Uzivatel919 

This should be updated to clarify that the output is from the implementation of `Object.ToString()` and doesn't apply to any type that overrides that method.

**Comment by Uzivatel919** [comment]
@BillWagner, output is produced by call to `ToString`. If there is no override it is taken `Object.Tostring` implementaiton. Otherwise override.
