### ISSUE TITLE
[Scenario] Deploying ASP.NET Core apps into Azure web apps

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2716]
This shows how to deploy ASP.NET Core apps (which run as console applications) int Azure as web apps.

Note:  This scenario is probably on the ASP.NET side but docs should add links to this.

/cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@tdykstra  should "deploy and ASP.NET Core app to Azure" go in docs.microsoft.com/aspnet or docs.microsoft.com/azure/ ? Should probably go in the Azure repo.

**Comment by tdykstra** [comment]
@Rick-Anderson /azure seems more appropriate

**Comment by mairaw** [comment]
@CamSoper would this be something you'd cover?

**Comment by CamSoper** [comment]
@mairaw Yes, please!

**Comment by mairaw** [comment]
Cool @CamSoper. How do you track work items in your world then? 😄 
Should we move this issue somewhere?

**Comment by CamSoper** [comment]
I will track it however you track it  I think I need an education.  😊

-- Cam

**Comment by tdykstra** [comment]
I would use an issue in the aspnet/Docs repo to track this as an ASP.NET Core topic, but since we would publish it on the Azure site we'd want something tracking it there too.  cc @SyntaxC4 @cephalin

**Comment by tdykstra** [comment]
In the aspnet/docs repo see https://github.com/aspnet/Docs/issues/2800

**Comment by CamSoper** [comment]
[VSTS User Story](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1109824)

**Comment by Rick-Anderson** [comment]
covered by https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs

**Comment by mairaw** [comment]
@CamSoper which sprint should this be moved to?

**Comment by CamSoper** [comment]
@mairaw This was done in 126.  Sorry, I marked VSTS complete but forgot to do it here.  I need to come up with a better system.  :(

**Comment by BillWagner** [comment]
Closed in aspnet/Docs#4728
