### ISSUE TITLE
The "Configure console apps" section doesn't actually say how to use the config

### ISSUE THREAD

**Issue by Daniel15** [dotnet/docs#27169]
Do I need to use `host.Services.GetRequiredService` to get the configuration service? The documentation doesn't explain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9
* Version Independent ID: 0d5de37c-8f89-b6a5-3132-2c5214196bfd
* Content: [Configuration in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration)
* Content Source: [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @Daniel15
Thank you so much for posting this issue. We really appreciate it. I'll add those details to this doc, as you're not the first to ask. This was initially intended to introduce the concepts and then the later docs on providers detailed exactly how those are done. But it's worth while to add at least a simple example here.

**Comment by Daniel15** [comment]
@IEvangelist Another question I had (that I forgot to ask) is why is this call needed?

```
await host.RunAsync();
```

My app seems to work fine and I can access the config even if I don't call that method.

**Comment by IEvangelist** [comment]
> @IEvangelist Another question I had (that I forgot to ask) is why is this call needed?
> 
> ```
> await host.RunAsync();
> ```
> 
> My app seems to work fine and I can access the config even if I don't call that method.

That runs the host, which enables DI, and all of the hosting life cycle hooks. See https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host

**Comment by Daniel15** [comment]
@IEvangelist  In these examples, why is the application code **before** the `host.RunAsync()` call though?

**Comment by IEvangelist** [comment]
I suppose it really depends on the application code. For example, when you register a worker service - it starts when you call `host.Run` or `host.RunAsync`. With console applications, it is a bit different. A lot of these docs that you're looking at are fundamentals to convey the concepts. What kinds of apps are you looking to build, I might be able to help direct to content where these concepts  are applied with more real-world use cases? The fundamentals here are intended to apply to all .NET workloads, and being that these are agnostic the code is a bit lacking. I'm happy to improve it, what would you like to see?

**Comment by Daniel15** [comment]
> What kinds of apps are you looking to build

I just want a basic console app where I want to use an appsettings.json file. Nothing special, no worker services. In that case it seems like I can just get the IConfiguration from the DI container and never actually call `host.RunAsync()`.

**Comment by IEvangelist** [comment]
@Daniel15 - Yeah, you don't need the host functionality. That's perfectly fine, I'm updating this content to include examples without the host. PR coming soon.
