### ISSUE TITLE
'Form1' is not a member of 'WindowsApp1'

### ISSUE THREAD

**Issue by vb4me** [dotnet/docs#27164]
In Visual Studio 2022, Visual Basic.

Create a new project > Next

Select - Windows Forms App (.NET Framework)
Visual Basic - Windows - Desktop > Next

Accept defaults and select Create

Select Start (Everything works)

Change the (Name) property of Form1 to Formx

Select Start 
(The popup says: There were build errors.  Would you like to continue and run the last successful build?
Select No
The Error list provides the Code BC30456 and the 
Description states: 'Form1' is not a member of 'WindowsApp1'

How do we fix that?

Thank you,
david@2taylors.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a323df-f91a-696c-9ae7-bee3eae96975
* Version Independent ID: 836a1e86-2999-d7d3-f336-e40e70f982e7
* Content: ['&lt;name&gt;' is not a member of '&lt;classname&gt;' - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30456?f1url=%3FappId%3Droslyn%26k%3Dk(BC30456))
* Content Source: [docs/visual-basic/misc/bc30456.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30456.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard
![Error VB 2022](https://user-images.githubusercontent.com/2505958/142510223-4ccc3f17-fb52-4214-9af6-feb1dc38791e.png)
**

**Comment by mohamed-azhar** [comment]
Hi @vb4me ,

You can try renaming Form reference of the generated class and build the project again. (check the below image)
![Screenshot 2021-11-20 014949](https://user-images.githubusercontent.com/17266828/142690080-88e67da4-a3c6-4cce-8802-b284183c31b1.png)

After renaming the reference from `From1` to `Formx`,  it builds perfectly.

**Comment by BillWagner** [comment]
Thanks @mohamed-azhar that''s the best suggestion.

I'll close this as an answered question.
