### ISSUE TITLE
 'WebRequest.Create(string)' is obsolete

### ISSUE THREAD

**Issue by kbajpai** [dotnet/docs#27167]
I get the following warning when I compile my code. Do we have an example of HttpClient to download file over FTP?

`warning SYSLIB0014: 'WebRequest.Create(string)' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f303232c-aabd-a4f5-2ca6-b26862fca16a
* Version Independent ID: e4b849e2-1ce0-271d-c2e2-1259038bd9cc
* Content: [How to: Download files with FTP - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-download-files-with-ftp)
* Content Source: [docs/framework/network-programming/how-to-download-files-with-ftp.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/how-to-download-files-with-ftp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment]
The recommended replacement for FTP in .NET 6 is to use a third-party library. See #27028.
