### ISSUE TITLE
PrintMembers formatting in derived records – senseless note

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27174]
>  Note
> In C# 10 and later, the compiler will synthesize PrintMembers when a base record has sealed the ToString method. You can also create your own implementation of PrintMembers.

Before C# 10 it is not possible to seal `ToString`. `PrintMembers` is created all the time. It is once told just fine some line above.

> In C# 10 and later, your implementation of ToString may include the sealed modifier, which prevents the compiler from synthesizing a ToString implementation for any derived records. Effectively, that means the ToString output won't include the runtime type information. 

Maybe author was about to note this new `ToString` sealing feature. This note is just intermix of some information.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#printmembers-formatting-in-derived-records)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This can be addressed in the next edit pass.
