### ISSUE TITLE
Equality in inheritance hierarchies – `GetHashCode` uses `EqualityComparer<T>.Default.GetHashCode(T)`

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27172]
>  The synthesized GetHashCode method uses the GetHashCode method from all properties and fields declared in the base type and the derived record type.

Synthesized `GetHashCode` uses `EqualityComparer<T>.GetHashCode(T)` not call to `GetHashCode` on particular data members.

```csharp
record Base(int I) { }
record Deriver(string S) : Base(0) { }

// Base
public override int GetHashCode()
{
  return EqualityComparer<Type>.Default.GetHashCode(EqualityContract) * -1521134295 + EqualityComparer<int>.Default.GetHashCode(I);
}

//Derived
public override int GetHashCode()
{
  return base.GetHashCode() * -1521134295 + EqualityComparer<string>.Default.GetHashCode(S);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#nondestructive-mutation)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This is one where we probably want to say less about the implementation. 

The important point for developers is that the implementation of `GetHashCode` will be generally good for values that are reasonably evenly distributed across the range of values for the properties. If, instead, many of the properties have values distributed across a narrow range of values (say from 1 to 100) developers may be able to provide a better `GetHashCode` with a better distribution of values.

**Comment by Uzivatel919** [comment]
👍🏻
