### ISSUE TITLE
Equality in inheritance hierarchies – `EqualityContract` property is not `sealed` for `sealed` `record`

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27171]
> If the record type is sealed, this property is sealed.

When `record` is `sealed`, `EqualityContract` is not `sealed`. Whole `type` is `sealed` thus all members are free of this burden.

```csharp
sealed record SealedRecord { }

// Decompilation

internal sealed record SealedRecord
{
  private Type EqualityContract { [CompilerGenerated] get { return typeof(SealedRecord); }}
  public override string ToString() { … }
  private bool PrintMembers(StringBuilder builder) { return false; }
  public override int GetHashCode() { return EqualityComparer<Type>.Default.GetHashCode(EqualityContract); }
  public bool Equals(SealedRecord? other) { return (object)this == other || ((object)other != null && EqualityContract == other!.EqualityContract); }
  private SealedRecord(SealedRecord original) { }
  public SealedRecord() { }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#equality-in-inheritance-hierarchies)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks. That should be clarified.
