### ISSUE TITLE
Nondestructive mutation – not all immutable members can be changes using `with` expression

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27177]
> Beginning with C# 10, you can use the with expression if you need to mutate immutable properties or fields of a structure-type instance. 

Immutable field cannot be subject to change. That is for sure. Immutable properties only if setter is specified. This narrows down to only option – `init-only` setter.

```csharp
// Immutable
struct WithField { public readonly int i = 3; }
struct WithProperty { public int I { get; } = 7; }
struct WithProperty_3 { public int I { get; init; } = 7; }

// Mutable
struct WithField_2 { public int i = 3; }
struct WithProperty_2 { public int I { get; set; } = 7; }

void Show()
{
  object x;
  // Error CS0191  A readonly field cannot be assigned to(except in a constructor or init - only setter of the type in which the field is defined or a variable initializer)
  x = new WithField() with { i = 5, };
  //  Error CS0200  Property or indexer 'WithProperty.I' cannot be assigned to -- it is read only	
  x = new WithProperty() with { I = 5, };
      
  x = new WithField_2() with { i = 3 }; // Ok
  x = new WithProperty_2() with { I = 3 }; // Ok
  x = new WithProperty_3() with { I = 3 }; // Ok
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#nondestructive-mutation)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The referenced sentence should change to:

> Beginning with C# 10, you can use the with expression if you need to make a copy that contains different values of immutable properties or fields of a structure-type instance.

**Comment by Uzivatel919** [comment]
@BillWagner, the mistake here is that `with` expression cannot change `readonly` fields and `readonly` properties. R/W properties are not _immutable_. Thus `with` expression can used only to _change_ **mutable** members with exception for properties with `init-only` setter that are considered _immutable_.
