### ISSUE TITLE
Avoid defensive copies – outdated example (in C# 10+ there are no _defensive copies_)

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27175]
In chapter **Avoid defensive copies** there is

> The Point3D structure is not a read-only struct. There are six different property access calls in the body of this method. On first examination, you may think these accesses are safe. After all, a get accessor shouldn't modify the state of the object. But there's no language rule that enforces that. It's only a common convention. Any type could implement a get accessor that modified the internal state.

```csharp
private static double CalculateDistance(in Point3D point1, in Point3D point2)
{
    double xDifference = point1.X - point2.X;
    double yDifference = point1.Y - point2.Y;
    double zDifference = point1.Z - point2.Z;

    return Math.Sqrt(xDifference * xDifference + yDifference * yDifference + zDifference * zDifference);
}
```
Next paragraph starts with note abote `readonly` modifier

> Without some language guarantee, the compiler must create a temporary copy of the argument before calling any member not marked with the readonly modifier. 

Because this example does not show exact implementation of `Point3D` chapter maybe could be enriched with [!NOTE] about C# 8+ autogenerated `readonly` modifiers for autoimplemented-property getters.

---

Excerpts from chapter **Declare readonly members for mutable structs**

> If you use auto-implemented properties, the compiler adds the readonly modifier to the get accessor for read-write properties.

> The compiler adds the readonly modifier to the auto-implemented property declarations for properties with only a get accessor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#avoid-defensive-copies)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54740](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54740)

**Comment by BillWagner** [comment]
This can be updated on the next edit pass.

**Comment by Uzivatel919** [comment]
I made some important edit to issue since I found out that sample from start is conceptual so it does not present each chapter model used for examples.
