### ISSUE TITLE
References to 2018 information

### ISSUE THREAD

**Issue by jhulbertpmn** [dotnet/docs#27170]
This content makes a couple references to preview functionality from 2018. Ex: "in preview in ACS as of early 2018)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f25d03-f983-be76-39a6-ffc0d60ef7c9
* Version Independent ID: 7b034dae-9106-87f6-dc37-b2855bca6336
* Content: [When to deploy Windows Containers to Azure Container Service (that is, Kubernetes)](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes#feedback)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by IEvangelist** [comment]
Hi @jhulbertpmn - thank you for posting this issue, much appreciated. We'll update this.

Hey @nishanil do you already have anyone working on this content that might be able to add this to their backlog?

**Comment by nishanil** [comment]
@IEvangelist @jhulbertpmn Done! Vaishali has updated the content. Closing this now.
