### ISSUE TITLE
Needs installation instructions

### ISSUE THREAD

**Issue by shgysk8zer0** [dotnet/docs#27185]
Per the instructions on **Add your desktop applications** I installed the Windows SDK just to obtain signtool.

> **2** Signtool.exe is available as part of the Windows SDK. Windows SDK can be downloaded from [here](https://go.microsoft.com/fwlink/?linkid=836916).

I then get a list of components to install, including including one implying it is for signing. It is not clear which of these components, if any, are required, as after installing there is no `signtool` available.

As I am using PWABuilder and have had the PWA for over a year now, I really have no need for this SDK and just need the signtool. I've already used it and successfully listed several apps on Google Play Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a4dbac-a145-e79f-121d-3d8df67552b1
* Version Independent ID: 9ea61916-a9db-f23e-4c43-edc06650483d
* Content: [SignTool.exe (Sign Tool) - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe)
* Content Source: [docs/framework/tools/signtool-exe.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/signtool-exe.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
I don't see **Add your desktop applications** in this article, and the article does state that the sign tool is automatically installed with Visual Studio and can be used from Developer Command Prompt for Visual Studio. Have you tried using it from the VS Developer Command Prompt?

**Comment by shgysk8zer0** [comment]
@tdykstra I don't and won't use VS. I'm not installing that on top of an entire SDK just to sign a file so that a web app I already built ran through PWABuilder can be listed on a store.

I just want signtool. That's it.

**Comment by tdykstra** [comment]
Does this work for you: https://stackoverflow.com/a/65339931/652224 ?
