### ISSUE TITLE
[Scenario] Secrets management

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2718]
.NET Core applications will need to manage secrets in several environments:

1. Development environments.
1. Testing environments.
1. On premise deployments.
1. Azure deployments.
1. Docker / container deployments.

This should provide pointers and guidance on how to manage deployments for each of these scenarios.

Note: Some of this guidance may exist for web applications.

**Comment by mairaw** [comment]
Perhaps we should move the topic https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio to here.

**Comment by BillWagner** [comment]
closing as this is covered in ASP.NET Core docs. (These will come together during the .NET 5 timeframe)
