### ISSUE TITLE
Declare immutable structs as readonly – readonly struct rules lack _init-only_ setter option

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27199]
> All properties must be read-only, including auto-implemented properties.

C# 9.0 init-only setter option is not mentioned here.

From [readonly struct](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#readonly-struct)
> All data members of a readonly struct must be read-only as follows:
> * Any field declaration must have the readonly modifier
> * Any property, including auto-implemented ones, must be read-only. In C# 9.0 and later, a property may have an init accessor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#declare-immutable-structs-as-readonly)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54747](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54747)

**Comment by BillWagner** [comment]
This should be updated for C# 10.0
