### ISSUE TITLE
Add more capabilities stage ends up in error

### ISSUE THREAD

**Issue by krchome** [dotnet/docs#27194]
[Enter feedback here]
The code samples work fine till the initial implementation. However it does not work as follows thereafter when trying to add more capabilities as follows
 ( as per documentation)
```
public bool AppendFormatted<T>(T t, string format) where T : IFormattable
{
    Console.WriteLine($"\tAppendFormatted (IFormattable version) called: {t} with format {{{format}}} is of type {typeof(T)},");
    if (!enabled) return false;

    builder.Append(t?.ToString(format, null));
    Console.WriteLine($"\tAppended the formatted object");
    return true;
}
```
and making the Main() method to log the interpolated strings 
```
logger.LogMessage(LogLevel.Error, $"Error Level. CurrentTime: {time}. The time doesn't use formatting.");
            logger.LogMessage(LogLevel.Error, $"Error Level. CurrentTime: {time:t}. This is an error. It will be printed.");
            logger.LogMessage(LogLevel.Trace, $"Trace Level. CurrentTime: {time:t}. This won't be printed.");

```
The application ends up in syntax error which on mouseover shows as attached:
![Error](https://user-images.githubusercontent.com/8474855/142720598-e58fd868-1668-4d5b-85b5-b0f9025d97f4.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99599c47-14ba-6e35-9b63-daa928f764bb
* Version Independent ID: e80a06db-bfbc-29f1-1cca-248460e523d3
* Content: [Explore string interpolation handlers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler#new-outline)
* Content Source: [docs/csharp/whats-new/tutorials/interpolated-string-handler.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/interpolated-string-handler.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This line needs to be shows in the final example: https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/snippets/interpolated-string-handler/Version_4_Examples.cs#L11

I've opened #27230 to address this.

**Comment by krchome** [comment]
After time initialization as suggested by @BillWagner I still have the second of the two errors which says that it expects a void return instead of boolean as in the screenshot attached
![ErrorNew](https://user-images.githubusercontent.com/8474855/142978763-74efa295-bb32-425c-abda-feb51aad4389.jpg)
