### ISSUE TITLE
Access Modifiers (C# Programming Guide) – strange supplement formulation

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27197]
> Private nested types aren't accessible from outside the containing type.

All `private` members are not accessible outside of containing _type_. Why to repeat this once again for _types_?

> Delegates behave like classes and structs.

Misleading. Delegate can take all modifiers when declared as _type member_, default is `private`; same as other _members_. Only when declared directly in _namespace_ `public` or `internal` is valid while default is same as for `class` or `struct`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 227653](https://dev.azure.com/msft-skilling/Content/_workitems/edit/227653)

**Comment by BillWagner** [comment]
related: #27196 

This should be updated using the same language as the standard.
