### ISSUE TITLE
Access Modifiers – confusing terminology (type, member)

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27196]
> * public: The type or member can be accessed by any other code in the same assembly or another assembly that references it. The accessibility level of public members of a type is controlled by the accessibility level of the type itself.
> * private: The type or member can be accessed only by code in the same class or struct.
> * protected: The type or member can be accessed only by code in the same class, or in a class that is derived from that class.
> * internal: The type or member can be accessed by any code in the same assembly, but not from another assembly.
> * protected internal: The type or member can be accessed by any code in the assembly in which it's declared, or from within a derived class in another assembly.
> * private protected: The type or member can be accessed only within its declaring assembly, by code in the same class or in a type that is derived from that class.

When `type` is declared nested in another `type` it is considered to be `member` thus these definitions are rather confusing. Moreover _top-level_ `type` is `member` of `namespace`.

Maybe chapter could note that `member` _is everything_ . Then discussing just `member` _rules_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 227654](https://dev.azure.com/msft-skilling/Content/_workitems/edit/227654)

**Comment by BillWagner** [comment]
Thanks @Uzivatel919 

This description should probably follow the description in the standard: [§8.5.2](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/basic-concepts.md#852-declared-accessibility)  Declared accessibility
