### ISSUE TITLE
LangVersion “latest” is not recommended.

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#27191]
It should be added to the description that LangVersion latest is not recommended, as it does not respect target framework limitations.
From 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults

> These projects now override the default behavior. You should edit the project file and remove that node. Then, your project will use the compiler version recommended for your target framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548e000-8190-b1bb-51fd-7e7b2d5bcb45
* Version Independent ID: 19f59267-c4c1-eb0e-7e48-45ffd6e2d9d1
* Content: [C# Compiler Options - language feature rules](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language)
* Content Source: [docs/csharp/language-reference/compiler-options/language.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/language.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 52106](https://dev.azure.com/msft-skilling/Content/_workitems/edit/52106)

**Comment by BillWagner** [comment]
That's a great point @MNF 

I've added this to our backlog for the next set of updates to this article.

**Comment by jnm2** [comment]
On making this recommendation more visible: https://github.com/dotnet/docs/issues/42400
