### ISSUE TITLE
Mention System.CommandLine somewhere

### ISSUE THREAD

**Issue by Daniel15** [dotnet/docs#27207]
This page should mention the `System.CommandLine` library, as most people will need command-line argument parsing at some point (there's only so far you can go with a string array)

https://github.com/dotnet/command-line-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ef4bd7-7012-8afd-721a-a4c31db20202
* Version Independent ID: d942d65a-87e4-1525-bd94-b005f1b7cbac
* Content: [Main() and command-line arguments](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/main-command-line)
* Content Source: [docs/csharp/fundamentals/program-structure/main-command-line.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/program-structure/main-command-line.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 230097](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230097)

**Comment by BillWagner** [comment]
I like this idea @Daniel15 

I've added it to the backlog.

/cc @jonsequitur @KathleenDollard
