### ISSUE TITLE
Optional use of in at call site – bad formulation

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27208]
> Omitting the in modifier at the call site informs the compiler that it's allowed to make a copy of the argument for any of the following reasons:
>
> * There exists an implicit conversion but not an identity conversion from the argument type to the parameter type.
> * The argument is an expression but doesn't have a known storage variable.
> * An overload exists that differs by the presence or absence of in. In that case, the by value overload is a better match.
>
>These rules are useful as you update existing code to use read-only reference arguments. Inside the called method, you can call any instance method that uses by-value parameters. In those instances, a copy of the in parameter is created.

Paragraph “_These rules are useful …_” likely was about to link just ability to omit `in` modifier at caller site since rules above are directly linked to caller site characteristic rather than `in` parameter at callee site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#optional-use-of-in-at-call-site)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54746](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54746)

**Comment by BillWagner** [comment]
update during the next edit pass.
