### ISSUE TITLE
[Feature] Add VB support and samples as appropriate

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2720]
.NET Core 2.0 adds support for VB developers.

We should update tutorials and samples, and add new samples that speak to VB developers.

**Comment by BillWagner** [comment]
@AnthonyDGreen If you have scenarios in mind that we should cover, let us know.

**Comment by mairaw** [comment]
@rpetrusha This is already in progress. Do you know if we have any more VB topics planned or updates we need to make? I'm guessing we should review where we mention csproj to use a generic project file term.

**Comment by rpetrusha** [comment]
.csproj files are a good place to start. Our major .NET Core getting started topics all have both Visual Basic and C# topics. I'll assign this to myself and review VB coverage during the next sprint.

**Comment by BillWagner** [comment]
closed after looking at PRs referenced above.
