### ISSUE TITLE
The out, ref, and in keywords – misworded statement

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27203]
> Add the in modifier to pass an argument by reference and declare your design intent to pass arguments by reference to avoid unnecessary copying. You don't intend to modify the object used as that argument.

I guess this statement was not about to repeat double _to pass (an) argument by reference_ and then directly address reader. 

It should be something like 

_Add the `in` modifier to pass an argument by reference and declare your design intent to preserve referenced object state._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#the-out-ref-and-in-keywords)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54745](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54745)

**Comment by BillWagner** [comment]
The language should be firmed up here.
