### ISSUE TITLE
Declare readonly members for mutable structs – props with init-only setter getter also get `IsReadOnlyAttribute`

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27201]
> If you use auto-implemented properties, the compiler adds the readonly modifier to the get accessor for read-write properties. The compiler adds the readonly modifier to the auto-implemented property declarations for properties with only a get accessor.

Properties with  _init-only_ setter are considered readonly/immutable. If they are autoimplemented, compiler generates _readonly modifier_. 

```csharp
 object Obj { get; init; }

.method /* 060000D7 */ private hidebysig specialname instance object get_Obj () cil managed 
{
	.custom instance void [System.Runtime]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = ( 01 00 00 00 )
	.custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 )
	// Method begins at RVA 0x35a0
	// Code size 7 (0x7)
	.maxstack 8

…
```

`System.Runtime.CompilerServices.IsReadOnlyAttribute` expresses `readonly` modifier.

Usually by _readonly property_ is meant property without any _setter_. So it is better to explicitly denote that autogenerated _RW-, readonly- and with init-only-setter_- properties get readonly modifier to _getter_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#declare-readonly-members-for-mutable-structs)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54742](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54742)

**Comment by BillWagner** [comment]
This should be updated for C# 10 enhancements.
