### ISSUE TITLE
Use ref readonly return statements – duplicity

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27202]
Sentences

> Notice that the readonly modifier must be part of the declaration of the variable. The reference to which it refers can't be modified. Attempts to do so result in a compile-time error.

are followed by new paragraph

> The readonly modifier is required on the declaration of originReference.

which is in turn followed by next paragraph starting with

> The compiler enforces that the caller can't modify the reference. . Attempts to assign the value directly generate a compile-time error.

It is duplicity actuating disturbance in comprehensive content of article.

I guess removing first quote and merging middle paragraph with next can be fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#use-ref-readonly-return-statements)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54743](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54743)

**Comment by BillWagner** [comment]
This should be updated in the next edit pass.
