### ISSUE TITLE
[Feature] Update the .NET Core CLI commands

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2721]
We will have updated options and commands for 2.0

These need to be updated.

**Comment by GuardRex** [comment]
@BillWagner @mairaw Work for this is on the following PR's:

https://github.com/dotnet/docs/pull/2480
https://github.com/dotnet/docs/pull/2496
https://github.com/dotnet/docs/pull/2495

Do u want me to add "Fixes" to any or all of those for this issue?

**Comment by mairaw** [comment]
@GuardRex I need to review what you've done so far and work from there. We'll be adding tabs to distinguish 1.x from 2.x where applicable
