### ISSUE TITLE
[Feature] Update topics that are using explicit dotnet restore

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2722]
Many (maybe all?) of our .NET Core tutorials tell users to explicitly run `dotnet restore`. That's no longer necessary. `dotnet restore` will be run implicitly on `dotnet build` or `dotnet run`.

All our tutorials and samples need to be updated to reflect this change.

Note that this will include the tutorials in the C# Guide, and the F# Guide.

**Comment by isaac2004** [comment]
@BillWagner @mairaw is the goal here to simply remove the reference to `dotnet restore` or add a note to every page (13 files total based on a search) that this is no longer required with .Net Core 2.0?

**Comment by BillWagner** [comment]
@isaac2004 I'd prefer adding a note. `dotnet restore` is still a valid command, and there are scenarios (like some CI builds) where doing an explicit restore makes sense.

**Comment by isaac2004** [comment]
@BillWagner How about adding to this to all the references?

**Note:** As of Dot Net Core 2.0, it is not necessary to run `dotnet restore` becase it is run implicitly as part of `dotnet build` or `dotnet run`. It is still a valid command in certain scenarios where doing an explicit restore makes sense. One example being [continuous integration builds in Visual Studio Team Services](https://www.visualstudio.com/team-services/support/build-deploy-asp-net-core-app-azure/).

**Comment by BillWagner** [comment]
@isaac2004 Perfect!

**Comment by isaac2004** [comment]
@BillWagner, sweet... expect a PR in about an hour

**Comment by mairaw** [comment]
Thanks @isaac2004.
 
We usually say "Starting with .NET Core 2.0," so it's future-proof. 
The other thing I wanted to do is to indicate the dotnet restore is optional in certain tutorials. For an example, see  PR #3170.

**Comment by isaac2004** [comment]
@mairaw should we be adding the note in this issue in ALL docs that reference dotnet restore (so updating the text in #3170)?

**Comment by mairaw** [comment]
I think we should look at the context. For the one in #3170, I think it's good as is since that step is really optional in that scenario. Don't think the extra note is necessary for a getting started topic because it might confuse customers that are just starting and not thinking about CI builds yet. I just updated that one now since it was saying 1.1 only instead of 1.x. Makes sense?

**Comment by isaac2004** [comment]
@mairaw yep sure does... I will see what I can do

**Comment by mairaw** [comment]
Thank you @isaac2004. Let us know if you have questions.  

One thing you can use if you're going to be using the same text for the note is to add it to an include file (https://github.com/dotnet/docs/tree/master/includes) and reference that file from the topics.

https://github.com/dotnet/docs/blob/master/styleguide/template.md#includes

**Comment by BillWagner** [comment]
Closing this as fixed in #3172
