### ISSUE TITLE
Use Struct to create a value object

### ISSUE THREAD

**Issue by OnofreJ** [dotnet/docs#27221]
Hi all, thanks for this content. However, could you give some opinion about use Structs with IEquatable<T> for example instead class to create a value object?

Thanks in advance,

Onofre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @OnofreJ, thanks for posting here. For more information, you can refer to the link: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/struct. I hope it helps.
