### ISSUE TITLE
What is the correct number of underscores to use for a prefix?

### ISSUE THREAD

**Issue by madelson** [dotnet/docs#27227]
In most areas, the prefixes show use a single underscore such as `DOTNET_`. However, under "The following commands test the custom prefix" the example shows a double underscore (`CustomPrefix__SecretKey`). Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c11507-cd06-292f-53bc-3a7f14affd86
* Version Independent ID: 33eb4890-44e0-522b-b1c1-964fec385b6a
* Content: [Configuration providers in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#environment-variable-configuration-provider)
* Content Source: [docs/core/extensions/configuration-providers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration-providers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gfoidl** [comment]
It's a differnece between _prefix_, and _hierarchy separation_.

The former uses the single underscore `_`. It's also used for [.NET runtime configuration settings](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/#environment-variables), as it's a _prefix_.

The latter uses by default the `:`, but this isn't available on all platforms, so as different approach one can use the double underscore `__`.
See a few paragraphs below in the docs, beginning with "Call AddEnvironmentVariables with a string to specify a prefix for environment variables:".

**Comment by madelson** [comment]
@gfoidl I think I understand the difference between those two; I just don't understand why the example with `CustomPrefix` uses double underscore. Does that make sense?

**Comment by gfoidl** [comment]
You mean the example from 
```
set CustomPrefix__SecretKey="Secret key with CustomPrefix_ environment"
set CustomPrefix__TransientFaultHandlingOptions__Enabled=true
set CustomPrefix__TransientFaultHandlingOptions__AutoRetryDelay=00:00:21
```
This should be single underscore `_` only.

**Comment by madelson** [comment]
@gfoidl yep that's the one that was confusing me. Seems like an easy fix.

**Comment by gfoidl** [comment]
Yep, do you want to send a PR to fix this?
