### ISSUE TITLE
Page should explain how it works

### ISSUE THREAD

**Issue by lukepuplett** [dotnet/docs#27236]
Hello, I'm trying to understand how to setup a new Macbook with a self-signed certificate, where my website is running in a container.

While on this journey I'm finding some things confusing. After coding in some form for 35 years now, when I find the going tough or confusing, I think it's okay to blame my tools and documentation.

These commands here are fishy. The first one specifies a file but the second one does not. How does the second one know which certificate to trust? Does the first one have side effects that aren't explicit or explained?

```
dotnet dev-certs https -ep $env:USERPROFILE\.aspnet\https\aspnetapp.pfx -p crypticpassword
dotnet dev-certs https --trust
```

So I turn to the build-in help documentation for that command. Alas, it says nothing that might explain the above, leaving me lost. There's an information gap here. It says "Trust the certificate ..." but which certificate?

I don't want to use commands that may have side-effects I am unaware of because I won't discover exactly what made something work, and I won't be able to automate the steps to setup the correct state in a different environment. 

```
Usage: dotnet dev-certs https [options]

Options:
  -ep|--export-path  Full path to the exported certificate
  -p|--password      Password to use when exporting the certificate with the private key into a pfx file or to encrypt the Pem exported key
  -np|--no-password  Explicitly request that you don't use a password for the key when exporting a certificate to a PEM format
  -c|--check         Check for the existence of the certificate but do not perform any action
  --clean            Cleans all HTTPS development certificates from the machine.
  -i|--import        Imports the provided HTTPS development certificate into the machine. All other HTTPS developer certificates will be cleared out
  --format           Export the certificate in the given format. Valid values are Pfx and Pem. Pfx is the default.
  -t|--trust         Trust the certificate on the current platform. When combined with the --check option, validates that the certificate is trusted.
  -v|--verbose       Display more debug information.
  -q|--quiet         Display warnings and errors only.
  -h|--help          Show help information
```

There's not even a description for what `dev-certs` does. But wait, there's another fishy command later in the page.

```
dotnet user-secrets remove "Kestrel:Certificates:Development:Password" -p aspnetapp\aspnetapp.csproj
dotnet dev-certs https --clean
```

Clean? What's it cleaning? We just created a file. Does it delete that file? Or was there a side effect when that original command was executed that now needs cleaning? Nothing is explained.

Next is the part where a user secret is setup. It seems to be writing a setting for Kestrel to read, but how does Kestrel know it needs to open that PFX file we just created?

Since when did documentation become a murder mystery.  I don't understand why Microsoft's documentation no longer explains how the tricks are done. Why aren't there links out to the documentation about the mechanisms being employed here?

I have similar feedback here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/7337

Thanks, Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129ac9c9-bab2-7ae0-75f8-cf3b7ad16a56
* Version Independent ID: 19debb34-1672-c5bc-395b-2ec523c25b8f
* Content: [Generate Self-Signed Certificates Overview - .NET](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide?source=docs)
* Content Source: [docs/core/additional-tools/self-signed-certificates-guide.md](https://github.com/dotnet/docs/blob/main/docs/core/additional-tools/self-signed-certificates-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @angee
* Microsoft Alias: **dotnetcontent**

**Comment by lukepuplett** [comment]
I must also point out that `dev-certs` seems to be undocumented. It gets a small note under **Additional tools**

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet

**Comment by lukepuplett** [comment]
Created discrete issue to cover lack of documentation under `dotnet` CLI.

https://github.com/dotnet/docs/issues/27237

**Comment by adegeo** [comment]
Just a note, `dev-certs` is referenced in the ASP.NET Core documentation: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide
