### ISSUE TITLE
[Feature] Revisit version numbers and code snippets showing TFMs

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2723]
Many of our samples and code snippets show Target Framework Monikers (TFMs). These need to be updated to the 2.0+ stream of libraries and frameworks.

For example: https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-with-xplat-cli

edit by mairaw: added example

**Comment by dotMorten** [comment]
.NET Core SDK is 2.1.101 by now
![image](https://user-images.githubusercontent.com/1378165/38062488-007df5c6-32a9-11e8-9fec-1eb2bccfdb62.png)

**Comment by mairaw** [comment]
We're aware of that @dotMorten. We're behind on finishing our backlog for 2.0 and we are also planning 2.1 content already, among other releases. This topic will get updated as part of this effort.

**Comment by dotMorten** [comment]
@mairaw Not trying to rush you :) Just wanted to make sure this one was handled as part of the issue (the issue is a little vague wrt which ones needs fixing).
