### ISSUE TITLE
Truly excellent documentation

### ISSUE THREAD

**Issue by JasonSanderEgan** [dotnet/docs#27234]
Hey there, apologies if this is not what feedback is meant for - but just wanted to say this was one of the best if not _the_ best pages of documentation I've read, in terms of how much my level of understanding of the topic changed from start to finish.

I was asked about asynchronous programming in C# the other day and after reading just this article I feel more than ready to start implementing `async` and `await` and playing around with them. Starting with the simple and real life example, then progressing from traditional synchronous code to well optimised asynchronous code, was excellently done.

High praise for whichever individual or team put this together - thanks again!

Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @JasonSanderEgan We appreciate it!  I'm glad this example resonated and helped understand async and await.

I'll close this as kudos.

Thanks again! 🎆
