### ISSUE TITLE
Explain access modifiers on auto-implement properties

### ISSUE THREAD

**Issue by JamesC01** [dotnet/docs#27248]
The page talks about auto-implement properties, but doesn't really explain why they'd be useful. I think it should show use of {get; private set;} to show a benefit of auto-implement properties over simple public fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb1d95e-a652-a965-f817-d49554a07388
* Version Independent ID: 05423053-63de-3e56-0929-2ae477d577df
* Content: [Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @JamesC01 

We're looking at doing significant work in the C# programming guide over the next six months. This is one of the areas where we want to improve.
