### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by westsiderz** [dotnet/docs#27241]
[Enter feedback here]
I ran the script and installed the runtime but if I run "dotnet" on Linux it says that the command is not found. Should I do anything additional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Manually install .NET on Linux - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. I bet the script didn't add `dotnet` to the path. You'll need to edit your terminal program and add the `dotnet` executable to your path variable. The [Manual Install](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install) section has that information. Can you follow those steps and see if it solves your problem?

**Comment by westsiderz** [comment]
Yeah, that way it worked. Thanks.
