### ISSUE TITLE
Missing entry for C#10

### ISSUE THREAD

**Issue by kilasuit** [dotnet/docs#27244]
Seems sensible to add an entry for C#10 to this doc so that it can be a simple single reference point
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
Also proposals link is missing in https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/index.md.

**Comment by BillWagner** [comment]
Thanks for noting this @kilasuit I've added it to our upcoming sprint.

It may make sense to retire this article, and replace its content with the article in the [csharplang repo](https://github.com/dotnet/csharplang/blob/main/Language-Version-History.md)
