### ISSUE TITLE
[Feature] Add guidance to use .NET Standard instead of PCL

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2724]
PCLs are less important now that .NET Standard 2.0 is coming.

We need to update our guidance to recommend .NET Standard - based libraries instead of creating PCLs.

**Comment by lextm** [comment]
I think this initiative should be carried out as soon as possible. 

Documentation on PCL, such as [this](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library) and [this](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/using-portable-class-library-with-model-view-view-model) should be marked as obsolete.

**Comment by mairaw** [comment]
This item is for more extensive revision of topics such as https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/

**Comment by BillWagner** [comment]
During the last releases, we've updated and moved much of this content.  In particular, the introduction to [.NET Standard](https://docs.microsoft.com/dotnet/standard/net-standard) highlights the new guidance.

Closing as completed.
