### ISSUE TITLE
typing error in debian dependency

### ISSUE THREAD

**Issue by opencsi-leon** [dotnet/docs#27255]
In the debian dependency i find an typing error.
The name of package 
     is not libgcc_s1
     but libgcc-s1

Please edit the guide.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. I'll get it fixed!
