### ISSUE TITLE
.editorconfig variations

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#27256]
this doc includes
"# Modifier preferences
dotnet_style_require_accessibility_modifiers = for_non_interface_members:silent
dotnet_style_readonly_field = true:suggestion"

whereas on my current v6 solution I have
"# Field preferences
dotnet_style_readonly_field = false"

I can understand that [my machine editing] may have changed true to false, but I am surprised to find line has moved from Modifier to Field. Anyway, my point is that the docs should always show the latest (i.e. .NET 6 today) vanilla defaults.

As an aside, it would be nice if the VS built-in editor could
a) highlight [bold/italic/colour] any changes of my settings from the [latest] defaults
b) reorder individual settings under "correct" default headings to standardise and make diffing easier
c) validate/flag any non-standard [or deprecated/duplicate] settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c8357d-11a6-6f12-b044-5ff44df65d10
* Version Independent ID: 0c103fd7-5cc4-2726-40f8-d759419ae635
* Content: [.NET code style rule options - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options)
* Content Source: [docs/fundamentals/code-analysis/code-style-rule-options.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/code-style-rule-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I just added a new .editorconfig file (.NET) to a .NET 6 project in Visual Studio 2022 and it matched what's in this article. I see that you generated your .editorconfig file from the Tools > Options dialog, and the file it generates is a little different. I'll update the article. Thanks!

@mikadumont Are you the best person to take a look at the feedback for the VS editor?

> As an aside, it would be nice if the VS built-in editor could
> a) highlight [bold/italic/colour] any changes of my settings from the [latest] defaults
> b) reorder individual settings under "correct" default headings to standardise and make diffing easier
> c) validate/flag any non-standard [or deprecated/duplicate] settings
