### ISSUE TITLE
PR reviews and issue response this week (Thanksgiving for USA team members)

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#27252]
This time of the year is holiday season for the .NET content team members in the United States. Many of the team members are taking vacation this week. PR reviewing/merging and issue response may be delayed during this period.

**Comment by BillWagner** [comment]
Thank you, everyone, for your patience while we enjoyed our holiday, and spending time with friends and family. Most people on the team will be returning early this week and resuming our regular schedule.

Closing this.
