### ISSUE TITLE
[Feature] Metapackages only apply to .NET Core 1.x

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2726]
The metapackages dependencies will only be used for .NET Core 1.x. Tutorials and samples and all guidance should be updated for the new .NET Standard dependencies instead of metapackages.

Capturing all the files the term "metapackage" currently resided in:

- .\docs\core\packages.md
- .\docs\core\toc.yml
- .\docs\core\deploying\index.md
- .\docs\core\porting\libraries.md
- .\docs\core\project-sdk\msbuild-props.md
- .\docs\core\tools\csproj.md
- .\docs\standard\frameworks.md
- .\docs\standard\glossary.md
- .\docs\standard\assembly\reference-assemblies.md

Metapackages:

- https://www.nuget.org/packages/Microsoft.NETCore.App
- https://www.nuget.org/packages/Microsoft.AspNETCore.App
- https://www.nuget.org/packages/Microsoft.AspNETCore.All
- https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility

**Comment by BillWagner** [comment]
Bumping priority to P0 since this has been delayed and re-scheduled a number of times.

**Comment by IEvangelist** [comment]
Capturing all the files this currently resided in:

- .\docs\core\packages.md
- .\docs\core\toc.yml
- .\docs\core\deploying\index.md
- .\docs\core\porting\libraries.md
- .\docs\core\project-sdk\msbuild-props.md
- .\docs\core\tools\csproj.md
- .\docs\standard\frameworks.md
- .\docs\standard\glossary.md
- \docs\standard\assembly\reference-assemblies.md
