### ISSUE TITLE
Clear or complete "TODO bookmarks" in this article

### ISSUE THREAD

**Issue by stanalek** [dotnet/docs#27266]
[Enter feedback here]
Hi Team, just a reminder to clear this TODO in the article under nameof_expression: (at least)

TODO: examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [Expressions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#nameof-expressions)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang/blob/main/spec/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @stanalek 

Work on the standard has moved to the dotnet/csharpstandard repo. (We've merged the Microsoft and ECMA versions of the standard for version 5, and the committee is workign on C# 6 now). This TODO item has been addressed here: https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#1273-interpolated-string-expressions

We have a couple more features to finish in C# 6, and then we'll switch which spec is published on docs.microsoft.com. 

I'll close this.
