### ISSUE TITLE
Trim self-contained deployments and executables - no support for Windows Desktop

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#27274]
The page must have a clear warning that trimming is not supported for the Windows Desktop apps (i.e. Windows Forms and/or WPF). It would be great to expand into reason why it is so.

There are multiple GitHub issues and user feedback that originate from the fact that trimming appears to have worked in .NET 5.0 release but was disabled for the WD apps in .NET 6.0 release. 
@agocke provided some insight in his tweet: https://twitter.com/andygocke/status/1455320377387732994. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a6f297-c659-3770-42d9-d277895b5d25
* Version Independent ID: 3061aedd-2264-90da-b244-b8ed7bf416fc
* Content: [Trim self-contained applications - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained)
* Content Source: [docs/core/deploying/trimming/trim-self-contained.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/trimming/trim-self-contained.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jamshedd
* Microsoft Alias: **jamshedd**

**Comment by IEvangelist** [comment]
Hey @adegeo,

Do you know what to do with this one? Should we transfer this issue to your `dotnet/desktop` repo?

**Comment by agocke** [comment]
Incompatibility with WPF and WinForms is noted on the "Trimming Incompatibilities" page, which is linked from that one https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities

That's in the first paragraph "Components that cause trimming problems"

Is there some other wording you would prefer?

**Comment by adegeo** [comment]
@RussKie ping

**Comment by RussKie** [comment]
Thank you for the feedback. I've re-read the page and I must admit I found it is difficult to spot the "Known trimming incompatibilities" link.

It would be great if
a)  [Known trimming incompatibilities](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities) as well as [Prepare .NET libraries for trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming) were present in the "See Also" section
b)  [Known trimming incompatibilities](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities) was formatted as a "Note", e.g. something like this:
![image](https://user-images.githubusercontent.com/4403806/145134179-5b4cff90-954e-46df-b9ab-8c3036906ae8.png)
