### ISSUE TITLE
[Feature] package resolution (1.x to 2.x dependencies)

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2727]
This topic will help developers that have invested in .NET Core 1.x update their projects and dependencies to the .NET Core / .NET Standard 2.x dependencies.

**Comment by mairaw** [comment]
I'm not sure if we still need this. @dsplaisted @KathleenDollard @richlander any thoughts on this?

**Comment by BillWagner** [comment]
@mairaw I'm closing this based on [this doc](https://docs.microsoft.com/en-us/dotnet/core/migration/) Re-open if you don't think that covers what's needed.

**Comment by mairaw** [comment]
That topic doesn't cover this subject but I'm not sure if we still need this. So I think it's fine to close it.
