### ISSUE TITLE
Possible confusion for the reader when changing the signatures from void to bool

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/docs#27272]
Great article, many thanks!  However, when following the instructions and changing the return type from `void` to `bool`, I get compilation (and code analysis) errors:
```
error CS8942: Interpolated string handler method 'LogInterpolatedStringHandler.AppendFormatted<DateTime>(DateTime, string)' has inconsistent return type. Expected to return 'void'.
error CS8942: Interpolated string handler method 'LogInterpolatedStringHandler.AppendFormatted<DateTime>(DateTime)' has inconsistent return type. Expected to return 'void'.
```

I realised that the instructions say to change the `Append` methods - but I don't think it was clear enough that it also applied to `AppendLiteral` as the context of that paragraph seemed focused on just `AppendFormatted` as we'd just added an overload to it.

I have just created a PR with this change and a few other minor changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99599c47-14ba-6e35-9b63-daa928f764bb
* Version Independent ID: e80a06db-bfbc-29f1-1cca-248460e523d3
* Content: [Explore string interpolation handlers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler)
* Content Source: [docs/csharp/whats-new/tutorials/interpolated-string-handler.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/interpolated-string-handler.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @SteveDunn

I'll review this article in the next sprint and address both this and #27271

**Comment by BillWagner** [comment]
As mentioned in the issue description, this has already been fixed by @SteveDunn
