### ISSUE TITLE
Nullability of `builder` when conditionally setting it

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/docs#27271]
The part where the page says we can have an `out bool isEnabled` should have address the null dereference errors that are now produced, e.g. the constructor could instead be:

```csharp

```
    public LogInterpolatedStringHandler(int literalLength, int formattedCount, Logger logger, LogLevel logLevel, out bool isEnabled)
    {
        isEnabled = enabled = logger.EnabledLevel >= logLevel;
        Console.WriteLine($"\tliteral length: {literalLength}, formattedCount: {formattedCount}");
        builder = isEnabled ? new StringBuilder(literalLength) : null;
    }
---

This also now means that the `enabled` field is no longer used.  And if that field is no longer used, then we can revert the signatures of the `Append*` methods from `bool` back to `void` and remove the checks for `enabled`.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99599c47-14ba-6e35-9b63-daa928f764bb
* Version Independent ID: e80a06db-bfbc-29f1-1cca-248460e523d3
* Content: [Explore string interpolation handlers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler)
* Content Source: [docs/csharp/whats-new/tutorials/interpolated-string-handler.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/interpolated-string-handler.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @SteveDunn 

I'll review this article in the next sprint and address both this and #27272
