### ISSUE TITLE
[Feature] .NET Framework compatibility

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2728]
This topic will address how to work with .NET standard and .NET core for the best compatibility with .NET Framework applications.

**Comment by mairaw** [comment]
@richlander @terrajobst do you still see this as a valid scenario?

**Comment by BillWagner** [comment]
Closing based on [this doc](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer)
