### ISSUE TITLE
Article "Development workflow for Docker apps" could use some proofreading

### ISSUE THREAD

**Issue by reinux** [dotnet/docs#27289]
Thanks for writing this article.

This is a rather complicated topic with a lot of moving parts, so the article could do with some proofreading to help reduce cognitive overhead. Even just improving punctuation would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: c8fefbe8-6f9b-209a-3563-2cb51384707c
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#feedback)
* Content Source: [docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @reinux, Thanks for the suggestions. We will try to improve our documentation in future releases. Meanwhile, it will be great if you can share some excerpts.

**Comment by erjain** [comment]
We are working on improvements to the microservices eBook and estimated the same in our dotnet-architecture projects. The issue can be closed.

**Comment by IEvangelist** [comment]
Closed per @erjain

**Comment by reinux** [comment]
Sorry I missed this, @erjain . Thanks and looking forward to the new docs!
