### ISSUE TITLE
[Feature] assembly loading in .NET Standard and .NET Core

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2729]
This topic will address how to manage assembly loading scenarios in .NET Standard and .NET Core libraries and applications.

----
>Added by @Thraka

Core 3.0 uses the Standard 2.0 [System.Reflection.MetadataLoadContext](https://www.nuget.org/packages/System.Reflection.MetadataLoadContext/) NuGet package to cover reflection-only assembly loading that .NET Framework had. This too should be covered

----
>Article proposal written by @MSDN-WhiteKnight 

.NET Framework had the reflection-only assembly load mode that allowed to inspect the contents of an assembly without loading it for execution. This mode is not supported in .NET Core. The replacement API is [MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.1), however, there's no information how to start using it. Searching for "c# MetadataLoadContext" only gives API reference and some unanswered StackOverflow questions. I suggest to create article similar to https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context that will cover MetadataLoadContext

## Suggested TOC location
Under https://docs.microsoft.com/en-us/dotnet/standard/assembly/

## Abstract
 The article will explain how to create the isolated MetadataLoadContext using fixed set of paths to resolve assemblies, load assembly into it and extract information about metdata (for example, attributes, defined types...)

## Outline
- Introduction: purpose of MetadataLoadContext, possible scenarios when it is useful
- Prerequisites
- Create MetadataAssemblyResolver for MetadataLoadContext
- Create MetadataLoadContext
- Example

My suggested code sample that can be used for this article: https://github.com/MSDN-WhiteKnight/CodeSamples/tree/master/MetadataLoadContextSample

**Comment by tebeco** [comment]
is there already existing doc on that or will it start from scratch ?

**Comment by svick** [comment]
[This document in the coreclr repo](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md) can probably be used as the base for this topic. Also, [the API reference for `AssemblyLoadContext`](https://docs.microsoft.com/en-gb/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-2.0) should be filled in too.

**Comment by Thraka** [comment]
I think this can be closed now.

**Comment by adegeo** [comment]
I think this can be closed now.
