### ISSUE TITLE
Release build configuration

### ISSUE THREAD

**Issue by JohnLeicht** [dotnet/docs#27296]
I dont have the VSCode Release build configuration. Where can I get it??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d7fd04-e358-9a83-aef2-bfcba1169699
* Version Independent ID: f5df932b-b092-2832-9c9a-61a9c43dcdb3
* Content: [Debug a .NET console application using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Release build configuration is available by default in your .NET console app -- do you get an error when you run the command shown in the tutorial -- `dotnet run --configuration Release` ?
