### ISSUE TITLE
ProjectReference and transitivity 

### ISSUE THREAD

**Issue by nkolev92** [dotnet/docs#27305]
**Issue description**

ProjectReference items work different in .NET (Core) world vs the standard csproj, .NET Framework world. 

In particular, the ProjectReference in .NET (Core) are transitive. 

For example, say you have:

Project 1 -> Project 2 -> Project 3.

In .NET Framework, Project 1 won't be able to consume Project 3 and code against it.

In .NET Core, Project 1 will be able to consume Project 3 and code against it. 

I might've missed, so if I did a pointer would be great, https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference. 

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#7401
