### ISSUE TITLE
Typo / old example 

### ISSUE THREAD

**Issue by zacharydub** [dotnet/docs#27300]
In the 'Designing abstract base classes and their derived classes' section, the derived classes are listed and then shown in the code below it. In the list the 'Triangle' class listed instead of 'Square' as per code example.
<img width="462" alt="Untitled" src="https://user-images.githubusercontent.com/67551775/143845615-195b8928-0914-4745-a50c-523c3d8f511a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d4fcf9-42c1-e015-798c-0c1519d77f41
* Version Independent ID: 75aee013-1123-1403-b2bc-cc8b68b56de8
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/inheritance)
* Content Source: [docs/csharp/fundamentals/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out for us @zacharydub 

We'll get it addressed shortly.

**Comment by BillWagner** [comment]
Closing as this was fixed in a prior edit cycle.
