### ISSUE TITLE
OperationCanceledException exception on CancellationTokenSource timeout

### ISSUE THREAD

**Issue by zbalkan** [dotnet/docs#27308]
The example code suggests utilizing `TaskCanceledException` but since it is cancelled by the `CancellationTokenSource`, the exception thrown is `OperationCanceledException`, looking at the [docs](https://referencesource.microsoft.com/#mscorlib/system/threading/CancellationToken.cs,466), and unfortunate personal experience.  

```cs
    try
    {
        s_cts.CancelAfter(3500);

        await SumPageSizesAsync();
    }
    catch (TaskCanceledException) // this should be either OperationCanceledException or just Exception depending on the context
    {
        Console.WriteLine("\nTasks cancelled: timed out.\n");
    }
    finally
    {
        s_cts.Dispose();
    }
```

Thanks to [this detailed StackOverflow response](https://stackoverflow.com/questions/34359129/operationcanceledexception-vs-taskcanceledexception-when-task-is-canceled/34359530#34359530
), the problem can be understood easily.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ddfd34-0838-951a-9c58-b9b02164e521
* Version Independent ID: 3293092a-40db-a784-8894-7588a752e148
* Content: [Cancel async tasks after a period of time (C#)'](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @zbalkan 

I've added it to the list of issues for this article.

I've also added the "up for grabs" label if someone wants to submit a fix before we make our next updates.
