### ISSUE TITLE
What's new in .NET Core 2.0

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2731]
We need a topic in the .NET Core guide that details what's new in the 2.0 release of .NET Core.

**Comment by mairaw** [comment]
PR was merged but leaving this issue open because there are still more work to be done on the what's new.

**Comment by rpetrusha** [comment]
This is published at [What's New in .NET Core 2.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/). Closing.
