### ISSUE TITLE
noted

### ISSUE THREAD

**Issue by wannurhadi** [dotnet/docs#27318]
[Masukkan maklum balas di sini]

---
#### Butiran Dokumen

⚠ *Jangan edit bahagian ini. Ia diperlukan untuk docs.microsoft.com ➟ Pemautan isu GitHub.*

* ID: c89966aa-b155-c98a-2391-47e01d468236
* Version Independent ID: de902eee-6f6b-3ccd-4dbf-1cc174daa806
* Content: [Troubleshooting 'This application could not be started' - .NET Framework](https://docs.microsoft.com/ms-my/dotnet/framework/install/application-not-started?version=(null)&processName=Squirrel.exe&platform=0009&osver=7&isServer=0&shimver=4.0.30319.0)
* Content Source: [docs/framework/install/application-not-started.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/application-not-started.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. It looks like this issue may have been opened in error. I'll close it. But if you have more to add to it, please feel free to reopen and clarify your question/concern.
