### ISSUE TITLE
Hello World example is missing System namespace

### ISSUE THREAD

**Issue by chriwong** [dotnet/docs#27328]
The **Hello world** example is failing because the `using System;` statement is gone.
```csharp
class Hello
{
    static void Main()
    {
        Console.WriteLine("Hello, World");
    }
}
```

The paragraph beneath the snippet even describes how the System namespace is being used, but the line of code is missing.
> The "Hello, World" program starts with a `using` directive that references the `System` namespace.

Running the Hello world example results in the following:
`program.cs(5,9): error CS0103: The name 'Console' does not exist in the current context`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [A Tour of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
Fixed in https://github.com/dotnet/docs/pull/27281 (will be published to site in 1-2 days)

**Comment by BillWagner** [comment]
Thanks for reporting this @chriwong 

As @MSDN-WhiteKnight notes, this has been fixed. The update should be live now.
