### ISSUE TITLE
Microbug: MSBuild reference for .NET SDK projects|Items|Using – link to _using directive_ links to using-directive#static-modifier

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#27332]
> For more information about aliased using directives and using static <type> directives, see using directive.

_using directive_ links to
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#static-modifier
insted of https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#using)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Probably there should be two separate links - the existing one for the static modifier and a separate link for aliased using directives that points here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#static-modifier.
