### ISSUE TITLE
Is there a runnable example for using the `TypeForwardedToAttribute` to implement type forward?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docs#27344]
Is there any example code for using the `TypeForwardedToAttribute`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f7fddd-7181-30c5-acb6-5dcdb007fa76
* Version Independent ID: 06112331-f980-d74a-5d76-c3b5916a99ba
* Content: [Type forwarding in the common language runtime](https://docs.microsoft.com/en-us/dotnet/standard/assembly/type-forwarding?redirectedfrom=MSDN)
* Content Source: [docs/standard/assembly/type-forwarding.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/type-forwarding.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
There isn't a code example, I'll draft one up and add it to the article.

**Comment by WeihanLi** [comment]
@IEvangelist thanks very much.
