### ISSUE TITLE
.Net 6 is missing in openSUSE, SLES and Alpine documentations

### ISSUE THREAD

**Issue by skriesch** [dotnet/docs#27346]
**Help us make content visible**

Debian, Ubuntu, RHEL and SLES are listed with Microsoft repositories with available .Net packages.
We have got also openSUSE users using .Net. Add your openSUSE repositories to the documentation, please.
You can do that also for Fedora for fairness. ;)

**Describe the new article**

	- openSUSE is a Desktop distribution for development.
	- openSUSE users want to work with .Net on openSUSE.
	- .Net should be open source and available for all desktop Linux distributions. If Microsoft wants to have happy .Net Developers as users, you should also add repositories for community distributions in the documentation. Development   environments are mostly used based on community distributions as openSUSE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016558a3-e021-04ce-e375-15b23f589ed9
* Version Independent ID: 89b6eb1c-2202-70ee-364d-fc2ede379e74
* Content: [Install .NET on openSUSE - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-opensuse)
* Content Source: [docs/core/install/linux-opensuse.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-opensuse.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@skriesch We have an article about installing .NET on openSUSE here: https://docs.microsoft.com/dotnet/core/install/linux-opensuse.

**Comment by skriesch** [comment]
I speak about the overview page, how to integrate Microsoft repositories into multiple Linux distributions:
https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software

**Comment by skriesch** [comment]
But you can also update the referenced openSUSE and SLES  pages with .Net 6. It seems, these are the single Linux distributions without the documentation update.

**Comment by gewarren** [comment]
@skriesch Can you open a separate issue here for the overview page you linked to? https://github.com/MicrosoftDocs/windowsserverdocs/issues

**Comment by skriesch** [comment]
The issue is created. I have also updated this topic.

**Comment by adegeo** [comment]
@skriesch Hi. I'm unsure what you're asking for in updates to these articles. The distribution pages for the distros you mentioned already describe installing .NET 6

**Comment by skriesch** [comment]
If I take a look to the openSUSE page in comparison to Fedora ( https://docs.microsoft.com/de-de/dotnet/core/install/linux-opensuse ) I can not see any reference to .Net 6 as a supported .Net. The highest supported version is .Net 5.

I want to reference this sentence:
Wenn sowohl eine Version von openSUSE als auch eine Version von .NET über ✔️ verfügen, wird diese Kombination aus Betriebssystem und .NET unterstützt.

Where is the ✔️ for .NET 6 on the documentation pages for openSUSE, SLES and Alpine? These documentations contain only .NET 5.0. It seems like .NET 6 would not be supported.

**Comment by adegeo** [comment]
@skriesch  Ahh I think the translation system isn't working correctly. The English pages have been updated for almost 2 months.

@JasonCard Any ideas as to why the German page is so out of date?

**Comment by gewarren** [comment]
@khoiph1 is our localization contact now.

**Comment by skriesch** [comment]
The translation system is working for RHEL, Fedora and Ubuntu, but not for SLES, openSUSE and Alpine? That sounds interesting...

**Comment by gewarren** [comment]
It looks like the page has been updated for de-de culture now, so I'm closing this issue.
