### ISSUE TITLE
The page tree structure does not match the category table

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/docs#27355]
The category table lists categories by their EditorConfig value. The page tree structure does not match this table and makes it a bit confusing.

* The 'Code quality rules' entry refers to individual rules under `Code style rules > Unnecessary code rules`, `Code style rules > Language rules > Modifier preferences` and `Code style rules > Miscellaneous rules`. They are not under `Code quality rules`.
* All sections under `Code quality rules` have a separate entry in the table, while the sections under `Code style rules` only have 1 joint entry named 'Style rules'.

Does it make sense to make the page tree structure match the table, or is there a reason for the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8a45df9-7c3c-2858-e0a8-e5327e68e7af
* Version Independent ID: 6fbcd123-c826-86a2-91f9-2fa61bd0268d
* Content: [Code analysis rule categories - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories)
* Content Source: [docs/fundamentals/code-analysis/categories.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/categories.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks for the feedback. The rule categories in the table aren't intended to match the tree structure - they're intended to match the available EditorConfig settings (as you noted). But I have made what I hope is an improvement in #27401 regarding the "code quality rules" category in the table. Let me know what you think.

**Comment by stijnherreman** [comment]
@gewarren the PR looks good to me 👍
