### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by JasonDWilson** [dotnet/docs#27356]
Is there a way to run the service in the Visual Studio?  I can run the exe from the console, but if I try to run it in the Visual Studio debugger, I get operation not supported:
![image](https://user-images.githubusercontent.com/57236874/144294714-1fc74d77-1851-4fe9-adce-c38b570b64bf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
That's interesting, I am able to debug on my machine. You should note that when running from Visual Studio, or outside the Windows Service context this will behave differently.

**Comment by JasonDWilson** [comment]
> That's interesting, I am able to debug on my machine. You should note that when running from Visual Studio, or outside the Windows Service context this will behave differently.

Found the issue.  When I copied this into my CSProj file, I was no longer able to debug
![image](https://user-images.githubusercontent.com/57236874/144649547-ea1d8f2c-3635-48d7-aa6c-9bd5ac40922e.png)

**Comment by IEvangelist** [comment]
Hi again @JasonDWilson - those values shouldn't impact your ability to debug the app. What version of Windows are you trying to debug from, what version of Visual Studio? Are you on a x64-bit machine? Are you trying to debug the published app, I have a lot of questions.

**Comment by JasonDWilson** [comment]
Thank David,  I debugging from Windows 10 Pro, Visual Studio 2022 (17.0.1) on a x64 machine.  I am trying to debug in Visual Studio.  Running the published app works fine.

Trying to add each line individually it is the line

<RuntimeIdentifier>win-x64</RuntimeIdentifier>

That causes the issue.

**Comment by IEvangelist** [comment]
Hey @eerhardt - would you know why this might cause issues when attempting to debug? See comments above.

**Comment by eerhardt** [comment]
> Hey @eerhardt - would you know why this might cause issues when attempting to debug? See comments above.

No, unfortunately I don't. Maybe @BillHiebert might?

**Comment by BillHiebert** [comment]
I assume Ctrl+F5 (run without debugging) works? @gregg-miskelly - have you seen the error mentioned in this issue while trying to attach?

**Comment by gregg-miskelly** [comment]
I believe the real problem is `<PublishSingleFile>true</PublishSingleFile>` and it is just that publishing a single file app without a runtime id doesn't do anything. My understand is that debugging single-file apps isn't supported for .NET 6 or earlier.

**Comment by eerhardt** [comment]
> My understand is that debugging single-file apps isn't supported for .NET 6 or earlier.

cc @vitek-karas @agocke

**Comment by vitek-karas** [comment]
Currently VS doesn't support debugging on single-file apps (the .NET 6 version of single-file that is). What is supported for single-file is SOS plugin and dump debugging. The live debugging support is being worked on.
