### ISSUE TITLE
Millisecond component of a DateTime value example uses nonlocalized decimal separator

### ISSUE THREAD

**Issue by rtzoeller** [dotnet/docs#27361]
It was pointed out to me in a code review for code based on this example that I was not using a localized decimal point, despite the date and time formats being localized.

I believe the millisecond component of a DateTime value example should use `NumberFormatInfo.CurrentInfo.NumberDecimalSeparator`, rather than assuming the separator is a period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2691d246-9d0a-5714-a3a3-19aabfb3c5cd
* Version Independent ID: 80f9e353-0de8-c715-233e-033e6dd3c375
* Content: [How to: Display Milliseconds in Date and Time Values](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-milliseconds-in-date-and-time-values)
* Content Source: [docs/standard/base-types/how-to-display-milliseconds-in-date-and-time-values.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/how-to-display-milliseconds-in-date-and-time-values.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! Are you saying that this section should use `NumberDecimalSeparator`?

![image](https://user-images.githubusercontent.com/67293991/144463817-8001a00c-111a-4fa8-a251-9f5cb4fd093a.png)

**Comment by rtzoeller** [comment]
@adegeo I believe that should as well as the sample code.

![image](https://user-images.githubusercontent.com/573497/144466353-ada6d90a-b12e-4281-a0bd-35d78c9be978.png)
