### ISSUE TITLE
Provide a reason why implicit typing should be avoided in loop variable in foreach loops

### ISSUE THREAD

**Issue by NagayamaToshiaki** [dotnet/docs#27367]
According to C# Coding Conventions, "Don't use implicit typing to determine the type of the loop variable in foreach loops."
But no clear reason is written here, so I don't know why we should use `foreach (char ch in laugh)` instead of `foreach (var ch in laugh)`.
You can find usually easily which type the `var` is, as Intellisense suggests like other `var`s.
```
Dictionary<Foo, Bar> X = new();
// Add some elements to X...
foreach(KeyValuePair<Foo, Bar> Y in X)
{
// Some Process here
}
```
Above might be difficult to guess, but that is what the C# implementation of `Dictionary` is, so not hard to remember.

Is this rule relevant to the note below it("Be careful not to accidentally change a type of an element of the iterable collection...")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking this @NagayamaToshiaki 

In your examples, and most instances using `foreach`, the type of elements in the collection isn't obvious.

This guidance follows from the general guidance on using `var` when the type of variable is obvious.

I'll leave this open and add the "up for grabs" label if any community member wants to update this before we make our next updates.

**Comment by paulomorgado** [comment]
I'm sorry @BillWagner, but, as stated, `var` should only be used with constants. And that's **wrong**.

How about LINQ and anonymous types?

```csharp
var list = new[] {
	new { FirstName = "Paulo", LastName = "Morgado" },
	new { FirstName = "Bill", LastName = "Wagner" },
};

var orderedList = list.OrderBy(i => i.LastName).ThenBy(i => i.FirstName);

foreach (var item in orderedList)
{
	Console.WriteLine(item.ToString());
}
```
