### ISSUE TITLE
C# guide tutorial

### ISSUE THREAD

**Issue by KatBed** [dotnet/docs#27369]
I recommend this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356f32d2-2574-9d48-a096-aef9fc21112d
* Version Independent ID: 49ae4e9d-cd57-917c-8795-71ad57858d5d
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/tutorials/exploration/interpolated-strings.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/exploration/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you very much @KatBed 

Closing this as kudos.
