### ISSUE TITLE
Confusing Paragraph because of extenuous 'Not'

### ISSUE THREAD

**Issue by TimO2221** [dotnet/docs#27391]
`The dotnet build command is equivalent to dotnet msbuild -restore. When you don't want to build the project and you have a specific target you want to run, use dotnet build or dotnet msbuild and specify the target.`

I believe 'not' does not belong in the sentence, 'When you don't want to build the project ...'. That sentence would be appropriate for the dotnet run command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9083568-6c58-1c1b-0062-10632e61a88d
* Version Independent ID: a1d47471-9482-9f69-f11e-3424e62383f6
* Content: [dotnet msbuild command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild)
* Content Source: [docs/core/tools/dotnet-msbuild.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-msbuild.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
It's not intuitive that you would use dotnet build when you don't want to run the build target, but the sentence is accurate.
