### ISSUE TITLE
C# Tutorial: Exception Practices

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#274]
Discuss how exceptions are the key method of communicating contract failures in .NET. In addition, this should discuss the Exception Filter language features added in C# 6.

**Comment by mairaw** [comment]
If we're going to have tutorials on this, then we should not port the content as in issue #222

**Comment by BillWagner** [comment]
@mairaw I missed that issue when I wrote this. I can close this one as a duplicate, and add a note on #222 that when its ported, it should be updated to discuss Exception Filters.

**Comment by BillWagner** [comment]
The PR for Issue #222 has been merged, and that issue has been closed.

We still need to update some of the exception content with a discussion of exception filters, including some examples. (That may be a duplicate of the "What's new in C# 6" topic though.)
