### ISSUE TITLE
Parantheses not consistent

### ISSUE THREAD

**Issue by doterik** [dotnet/docs#27406]
In the last example `FindNumber` I'm a little disturbed that one condition has parentheses and the other not.
```C#
while ((ctr >= 0) && numbers[ctr] >= target)
{
    returnVal = ref numbers[ctr];
    ctr--;
}
```
Either use, or not use, parantheses on both or neither.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6968c8f-19ab-f79f-021a-265108870371
* Version Independent ID: 6b4f1fec-b9d1-f501-1fcf-2c6f15209a29
* Content: [Ref return values and ref locals (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/ref-returns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/ref-returns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @doterik 

We should use the extra parentheses to be consistent with our coding styles.

I've added this to our backlog, and added the "up for grabs" label, in case someone wants to submit a PR before we make the change.
