### ISSUE TITLE
Sample doesn't compile.

### ISSUE THREAD

**Issue by woojamon** [dotnet/docs#27407]
In my case, the line 

```csharp
namespace {mainMethod.ContainingNamespace.ToDisplayString()}
```
actually generates as 

```csharp
namespace <global namespace>
```

and causes the console app not to compile.

My console app project is targeting .net6, if that matters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
This has been previously reported over at dotnet/roslyn: https://github.com/dotnet/roslyn/issues/57030, https://github.com/dotnet/roslyn/issues/58000.

**Comment by woojamon** [comment]
Thanks @svick ! 

To whom it may concern: I see there was a decision not to put any note in the doc about it.. As a victim of the issue, I would very much have appreciated at least some comment about it. Not just that, but when I'm learning about some cool new thing that Microsoft built for us and the Getting Started sample is broken, it immediately decreases my confidence in the new thing and increases disappointment in Microsoft. I don't want that for Microsoft or this cool new source generator stuff.

**Comment by BillWagner** [comment]
@woojamon We will get this updated to match the latest implementation.   This change to the SDK came in rather late in the cycle, and we haven't found addressed all the impacted locations. writing this issue helps us.

Adding @mikadumont as well.
