### ISSUE TITLE
Clarification may be needed

### ISSUE THREAD

**Issue by doterik** [dotnet/docs#27405]
For me the sentence _"In the example above, the local functions version has two fewer allocations than the lambda expression version."_ is a bit unclear.

I assume it refers to three examples above and one example below, or maybe only one above and one below.

Please, clarify or move the example so that the sentence is correct.

I may be completely wrong but if you are not native English speaking these things can make one doubt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 345703](https://dev.azure.com/msft-skilling/Content/_workitems/edit/345703)

**Comment by BillWagner** [comment]
Thanks for noting this @doterik 

I've added it to our backlog to address and clarify when we next update this article.
