### ISSUE TITLE
Please Donate _1 dollar to save the children , skylight Records produced by Chad sheda

### ISSUE THREAD

**Issue by ChadMichaelSheda** [dotnet/docs#27414]
**Help us make content visible**

**Describe the new article**

![1635924632995](https://user-images.githubusercontent.com/94402076/144880100-48b13365-b55d-46fa-81c4-72e5645a21b4.jpg)
![1635933221418](https://user-images.githubusercontent.com/94402076/144880131-8218b6e9-0f46-4a3c-a0cb-ab70d5e2d1bf.jpg)
![1635933771284](https://user-images.githubusercontent.com/94402076/144880169-b148c763-df86-4c94-a076-b27be1a3df4c.jpg)
![1635935962468](https://user-images.githubusercontent.com/94402076/144880204-bec48f29-fa87-4f69-9cee-f1dd38fdcc7f.jpg)
![IMG_20211109_083230_818](https://user-images.githubusercontent.com/94402076/144880297-81af06c7-f53e-4f94-ae5b-61a202cdb358.jpg)
#27397

**Comment by ChadMichaelSheda** [comment]
![IMG_20211029_005634_284](https://user-images.githubusercontent.com/94402076/144880755-49ab6607-e55f-4e26-a3b3-4af71c13a3c1.jpg) 
![IMG_20211029_060151234](https://user-images.githubusercontent.com/94402076/144881003-cf1c96b1-ad9c-4527-a3cc-6ed3ce3bd1c8.jpg)

**Comment by ChadMichaelSheda** [comment]
https://user-images.githubusercontent.com/94402076/144881105-2b81339d-98e6-4129-b721-d1f5b0940d8b.mp4

**Comment by ChadMichaelSheda** [comment]
![IMG_20211206_041707_109](https://user-images.githubusercontent.com/94402076/144881462-130d8603-c269-4f80-acee-787454e01dc4.jpg)
![IMG_20211130_193405_372](https://user-images.githubusercontent.com/94402076/144881487-e50dafb5-67ae-42f6-aecc-26ca733113f1.jpg)
![IMG_20211130_210624_520](https://user-images.githubusercontent.com/94402076/144881495-85978f45-7ad9-4282-b42b-31d27faaf788.jpg)
![IMG_20211129_235012_649](https://user-images.githubusercontent.com/94402076/144881520-149bc06a-263a-46a7-8460-83f2bda610f4.jpg)
![IMG_20211130_193405_372](https://user-images.githubusercontent.com/94402076/144881537-e1da058e-c7b2-4b0f-85c1-6c695c040b95.jpg)
![IMG_20211124_193527_268](https://user-images.githubusercontent.com/94402076/144881571-57e334d1-5d3c-4084-9f5b-e563c54c4108.jpg)
![IMG_20211124_040622_727](https://user-images.githubusercontent.com/94402076/144881595-33a43396-3d49-45f6-af83-2937dc31d5d9.jpg)

**Comment by BillWagner** [comment]
closed and locked as spam.
