### ISSUE TITLE
Cancelling Parallel.For(Each)

### ISSUE THREAD

**Issue by VladiStep** [dotnet/docs#27419]
Is it necessary to call `po.CancellationToken.ThrowIfCancellationRequested()` if it throws _(and then catches)_ the same `OperationCanceledException` anyway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad8b3ee-d780-0844-bc19-1f725df6fcc1
* Version Independent ID: c83570d1-5b88-06fa-b3ed-6ff984f7c310
* Content: [How to: Cancel a Parallel.For or ForEach Loop](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop)
* Content Source: [docs/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @VladiStep - thank you for posting this issue. This is code is intentional. It shows the reader what exception results from the invocation to `ThrowIfCancellationRequested`.

**Comment by VladiStep** [comment]
Okay, I got it.
I just think there should be some note about the fact that it would work without `ThrowIfCancellationRequested()`, because `For()`/`ForEach()` _already does_ that.
