### ISSUE TITLE
Ambiguous statements related to Tuple types are value types vs reference types

### ISSUE THREAD

**Issue by saravanansomu** [dotnet/docs#27428]
[Enter feedback here]
These two lines are ambiguous and misleading: 
Statement#1 Tuple types are value types
Statement#2 In section "Tuples vs System.Tuple", there is a statement: Tuple types are reference types.
It should be clearly indicating what kind of types are the Tuple types, and how are they kept in memory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e533179-50e7-813d-be49-e1248134dd10
* Version Independent ID: 1778e921-76f6-32d5-4509-7bd944a01e0d
* Content: [Tuple types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples)
* Content Source: [docs/csharp/language-reference/builtin-types/value-tuples.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @saravanansomu 

We should clarify that `System.Tuple` is a reference type, `System.ValueTuple` is a value type. The C# syntax for *tuples* compiles to instances of `System.ValueTuple`, which is a value type.

I've added this to our backlog, and added the "up for grabs" label if anyone wants to submit a PR before we make our next updates.

**Comment by saravanansomu** [comment]
It's perfect now. Thank you @BillWagner !
