### ISSUE TITLE
What's the precedence between and/or/not?

### ISSUE THREAD

**Issue by ahdung** [dotnet/docs#27433]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24835b78-fece-0f9c-8118-40e2151ebc12
* Version Independent ID: 75aa73d0-1bde-a20b-71e2-8e0939c5037c
* Content: [Pattern matching changes - C# 9.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/patterns3#pattern-combinators)
* Content Source: [proposals/csharp-9.0/patterns3.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/patterns3.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
This is the specification proposal for the feature, so it uses precise, but potentially confusing way of specifying that, the grammar:

```antlr
disjunctive_pattern
    : disjunctive_pattern 'or' conjunctive_pattern
    | conjunctive_pattern
    ;
conjunctive_pattern
    : conjunctive_pattern 'and' negated_pattern
    | negated_pattern
    ;
```

This grammar means that `and` has higher precedence than `or`.

If you don't need this level of precision, you should look at [the language reference instead](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns). It explains this in plain language:

> The `and` pattern combinator has higher precedence than `or`.

**Comment by BillWagner** [comment]
Hi @ahdung 

I agree with @svick that this is answered in the ANTLR grammar, and the language reference provides a text description.

I'll close this as an answered question. If you have further questions, please open a new issue.

**Comment by ahdung** [comment]
@svick First thank you for your response.

Before I asked the question, I read the full text carefully, including the two places you mentioned, but they only explained `and` and `or`, even your answers, that is interesting really, BUT WHAT ABOUT `not` MEN?

Precedence is a very important thing, I recommand you provide a FORM or TABLE to show it, like [this doc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence), not ANTLR, not plain language.

**Comment by pkulikov** [comment]
@ahdung what do you think of #27447? It mentions `not` and and highlights the precedence info by introducing the dedicated section for it.

**Comment by ahdung** [comment]
@pkulikov Thank you, much better, but I still suggest use list or table, more formal.

**Comment by pkulikov** [comment]
> @pkulikov Thank you, much better, but I still suggest use list or table, more formal.

yes, I've formatted it as a list. Thank you @ahdung
