### ISSUE TITLE
No help page for C# error CS7036

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/docs#27438]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS7036))
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 189693](https://dev.azure.com/msft-skilling/Content/_workitems/edit/189693)

**Comment by BillWagner** [comment]
related to #24002

**Comment by BillWagner** [comment]
This is the most undocumented error for `F1` queries.

The new page should consolidate errors for parameter / argument mismatch in method call access.
