### ISSUE TITLE
is has changed starting with C# 8

### ISSUE THREAD

**Issue by trivalik** [dotnet/docs#27448]
The first example seems wrong, since it works only in C# 9. The wrong example:
```
static bool IsFirstFridayOfOctober(DateTime date) =>
    date is { Month: 10, Day: <=7, DayOfWeek: DayOfWeek.Friday };
```
This works in C# 8.0, but does not do the function of IsFirstFridayOfOctober():
```
static bool IsFirstFridayOfOctober(DateTime date) =>
    date is { Month: 10, Day: 7, DayOfWeek: DayOfWeek.Friday };
```

As far as I understand does C# 7.0 only contains the matching to create a local variable, like:
```
static bool IsFirstFridayOfOctober(object date) {
    if(date is DateTime dateCasted) {
        //do something with "dateCasted"
    }
    return false:
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778dcff2-db62-27d5-c0a2-35460e0d72f8
* Version Independent ID: 14ddc828-0812-3c14-60cf-9109bf3b8f7b
* Content: [is operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is)
* Content Source: [docs/csharp/language-reference/operators/is.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/is.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
The example uses the relational pattern that is available starting with C# 9

**Comment by pkulikov** [comment]
But what makes it wrong?

**Comment by trivalik** [comment]
The sentence before starts with "Beginning with C# 7.0, ". So I would guess that the following example is working with this version, but it is not.

**Comment by pkulikov** [comment]
I see, then it becomes difficult :). The is operator supports pattern matching since C# 7, but since then every language version adds new patterns. So, either (1) the example should be in c# 7 or (2) we need to clarify that it uses the patterns added later. I like variant (2).

What do you think @trivalik ?

**Comment by BillWagner** [comment]
I'd prefer variant (2). We should optimize for the current version.

**Comment by trivalik** [comment]
I am fine with variant (2).
