### ISSUE TITLE
CS1503

### ISSUE THREAD

**Issue by RatalBad** [dotnet/docs#27460]
[Enter feedback here]
The groundCheck variable uses groundCheckRadius to evaluate whether the Player is on the surface
"playerIsGrounded = Physics2D.OverlapCircle(groundCheck.position, groundCheckRadius, ground);" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f98776d-66cc-91ad-697a-783f80914f9c
* Version Independent ID: 66121850-861c-9e37-27f0-811f80427d70
* Content: [Compiler Error CS1503](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503))
* Content Source: [docs/csharp/misc/cs1503.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@RatalBad 

I don't have enough context to understand what should change in the documentation. This may be a question that is better answered in our [Q & A forums](https://docs.microsoft.com/answers/products/). Can you provide more info on what the issue with our content is?
