### ISSUE TITLE
Message template should be compile time constant

### ISSUE THREAD

**Issue by LindaLawton** [dotnet/docs#27468]
There are some issues with the logging if you are trying to keep things to standard.  They are showing up as warnings in Rider currently.

The following logging method has two issues

- Message template should be compile time constant
- Log event messages should be fragments, not sentences 

      _logger.LogInformation($"{nameof(TimerHostedService)} is running.");

May I suggest that all logging in this sample should be fixed. Removing the period at the end of the sentence as well as removing the string interpolation of the message. As shown below

      _logger.LogInformation("{TimerHostedService} is running", nameof(TimerHostedService));

I am willing to put in a pull request if you like I just need to find out where the source for the doc is.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b247969-9dc8-e710-ca64-745596cc3082
* Version Independent ID: 483cf588-2b7b-73cd-f9f9-a231a9c8dd7f
* Content: [Implement the IHostedService interface](https://docs.microsoft.com/en-us/dotnet/core/extensions/timer-service)
* Content Source: [docs/core/extensions/timer-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/timer-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @LindaLawton, great observations! You're correct, and I would happily welcome a PR to review. Please reference this issue in the PR and feel free to tag me for review. Thanks

**Comment by IEvangelist** [comment]
Hi again @LindaLawton, I'm following on this. Do you think you'll have time to send over a PR for this?
