### ISSUE TITLE
Sudo command is missing in some of the example command

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [dotnet/docs#27489]
Sudo command missing ahead of some of the example commands, for examle under ubuntu 20 the very first block is missing sudo ahead of the wget .... command but subsequent commands have it.
This means a copy and paste will not work completely but the errors will be buried in a lot of text so users could easily miss this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @WhatFreshHellIsThis I looked at the examples and I'm not sure what the problem would be. WGET wouldn't require SUDO in a typical situation where you're downloading a file. When you open a terminal you generally go to your home directory which doesn't require SUDO to download files to.

Can you provide more information about what problem you encountered?

**Comment by WhatFreshHellIsThis** [comment]
Oops, sorry about that.

**Comment by adegeo** [comment]
No problem!
