### ISSUE TITLE
Need to specify that left shift is modulo number of bits in the left operand

### ISSUE THREAD

**Issue by mjess25** [dotnet/docs#27486]
Currently, this documentation doesn't specify what happens when you left shift a number more than the number of bits in the number, e.g., left shift a 64 bit long 66 times. I was surprised to learn that this doesn't just keep shifting in 0s from the right 66 times but rather has the same effect as shifting the number 2 times, i.e., if x is a 64 bit long then x << 66 == x<<2. The documentation should call that out.

BTW: This is also left out in the Microsoft C++ documentation but the C++ language standard actually requires that the shift is modulo number of bits in the left operand.

Regards,
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa
* Version Independent ID: 2410c828-0c66-9efe-ae87-9b07708aa731
* Content: [Bitwise and shift operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#feedback)
* Content Source: [docs/csharp/language-reference/operators/bitwise-and-shift-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@mjess25 documentation has the section about it with the example:
https://www.nu.nl/economie/6169300/meer-amerikaanse-sancties-tegen-gaspijpleiding-nord-stream-2.html

Or you're looking for something else?

**Comment by BillWagner** [comment]
Thanks for starting this conversation.

@mjess25 Can you let us know if the referenced article provides the information you sought?

**Comment by mjess25** [comment]
Hi Petr,
The link you sent me is a news article in Dutch, is that what you meant to send?
Regards,
Martin

**Comment by pkulikov** [comment]
@mjess25 No, that was my mistake, sorry. Please check the updated message:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators

**Comment by mjess25** [comment]
Ah, got it you’re right, it is described there.

Might be worth adding a forward reference from the shift section to the shift count section though, I think other developers than me also do the occasional lookup where you do an online search, hop to that specific section and read just that and then go back to the coding. I’m new to C# so I do that a lot as I’m learning. Just a suggestion.

Regards,
Martin

**Comment by pkulikov** [comment]
@mjess25 hm... there is a forward reference in the first sentence:
![image](https://user-images.githubusercontent.com/15279990/145724904-e8e6ae9b-60c9-4fe4-971f-819e7816e54f.png)

"...the number of bits is defined by its right-hand operand" is a link

**Comment by pkulikov** [comment]
@mjess25 and the last sentence in the section explicitly references that section again:
![image](https://user-images.githubusercontent.com/15279990/145724994-8129702d-efc1-4977-9cd6-b357aae403e4.png)

**Comment by pkulikov** [comment]
@mjess25 #27516 improves the article

**Comment by mjess25** [comment]
Thanks Petr, much appreciated!
