### ISSUE TITLE
Is `MyService(IOptions<MyService> options....` a valid scenario?

### ISSUE THREAD

**Issue by peteraritchie** [dotnet/docs#27497]
On the page, there is a code snippet like this:

```csharp
public class ExampleService
{
    public ExampleService(
        ILogger<ExampleService> logger,
        IOptions<ExampleService> options)
    {
        // omitted for brevity
    }
}
```
[Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options) seems to suggest that the generic parameter of `IOptions` would be a stand-alone class to hold public read/write properties bindable to some sort of configuration source.  My understanding is that that class would never be the class that would read the `IOptions<T>` properties.

So, I'm wondering if `IOptions<ExampleService>` is, in this example, a valid scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd55089-b683-2202-6641-c7b61a132f14
* Version Independent ID: cc5f00d0-fb50-1229-8fa2-e66b1f45b284
* Content: [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
* Content Source: [docs/core/extensions/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @peteraritchie, you're correct about this being invalid. I'm fixing this in #27499 - thanks for posting this issue.
