### ISSUE TITLE
+=

### ISSUE THREAD

**Issue by atajanovez** [dotnet/docs#27490]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23958040-e5a6-2d3b-4764-d5b0b4126cc4
* Version Independent ID: 91eb2a64-43b2-f128-9170-b263878a3421
* Content: [Compiler Error CS1525](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1525?f1url=%3FappId%3Droslyn%26k%3Dk(CS1525))
* Content Source: [docs/csharp/misc/cs1525.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1525.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @atajanovez Can you elaborate on this issue? It's unclear what updates would address your concerns.
