### ISSUE TITLE
Small Error in final Properties Example

### ISSUE THREAD

**Issue by richk1** [dotnet/docs#27501]
I believe you've got a small error in the final Properties code sample on the page; the one using INotifyPropertyChanged.
(referencing the 9/15/2021 dated version of this article)

Shouldn't this:
```
if (value != firstName) {
  PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(FirstName)));
}
firstName = value;
```
be this ?
```
if (value != firstName) {
  firstName = value;
  PropertyChanged?.Invoke(this,new PropertyChangedEventArgs(nameof(FirstName)));
} 
```
Thus, only setting the backing property value if the new value is different, and invoking the PropertyChanged handler AFTER setting the new value?

BTW - I appreciate the effort you folks are putting into this new set of C# documentation. I like it. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e614217-286d-2231-f0c7-d37e5a31b2d5
* Version Independent ID: 070d932f-bc38-a766-37cc-ec861e74be1c
* Content: [Properties](https://docs.microsoft.com/en-us/dotnet/csharp/properties)
* Content Source: [docs/csharp/properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @richk1 

I've opened a PR to address this issue.
