### ISSUE TITLE
Article: `Options pattern in .NET`; Section: `IValidateOptions for complex validation`; Bug in code example

### ISSUE THREAD

**Issue by arthuredgarov** [dotnet/docs#27504]
In the section [IValidateOptions for complex validation](https://docs.microsoft.com/en-us/dotnet/core/extensions/options#ivalidateoptions-for-complex-validation) there is the following code sample:
```csharp
class ValidateSettingsOptions : IValidateOptions<SettingsOptions>
{
    public SettingsOptions _settings { get; private set; }

    public ValidateSettingsOptions(IConfiguration config) =>
        _settings = config.GetSection(SettingsOptions.ConfigurationSectionName)
                          .Get<SettingsOptions>();

    public ValidateOptionsResult Validate(string name, SettingsOptions options)
    {
        string result = "";
        var rx = new Regex(@"^[a-zA-Z''-'\s]{1,40}$");
        Match match = rx.Match(options.SiteTitle);
        if (string.IsNullOrEmpty(match.Value))
        {
            result += $"{options.SiteTitle} doesn't match RegEx\n";
        }

        if (options.Scale < 0 || options.Scale > 1000)
        {
            result += $"{options.Scale} isn't within Range 0 - 1000\n";
        }

        if (_settings.Scale is 0 && _settings.VerbosityLevel <= _settings.Scale)
        {
            result += "VerbosityLevel must be > than Scale.";
        }

        return result != null
            ? ValidateOptionsResult.Fail(result)
            : ValidateOptionsResult.Success;
    }
}
```

The returned result depends on whether the `result` variable is `null`, but it can never be null in this code example, so the return value will be always `ValidateOptionsResult.Fail(result)` which makes it a bad code example.

There are two options to fix this:

1. Assign `result` variable `null` on initialization.
2. On the return statement, check if the `result` is an empty string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @arthuredgarov - thank you, I'll work on getting this updated.
