### ISSUE TITLE
Needs to be updated for .NET 6.0

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#27502]
This page does not use the new .Net 6 Program.cs style of coding.

I would like to suggest it be updated to show how to do this in .Net 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1cda6a-30fa-91b9-793e-918666776c9f
* Version Independent ID: 4df737d8-1051-2ce1-1d61-58768046283b
* Content: [Implement a custom configuration provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-configuration-provider)
* Content Source: [docs/core/extensions/custom-configuration-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-configuration-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
This is a good callout, thank you. I'll work on updating this next month.
