### ISSUE TITLE
Patterns (C# reference) minibugs

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27511]
### # 1

[Precedence and order of checking](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#precedence-and-order-of-checking) example

````csharp
static bool IsLetter(char c) => c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z');
````

is rather unfortunate since without parentheses meaning is the same. 

> The following list orders pattern combinators starting from the highest precedence to the lowest:
> - not
> - and
> - or

This can be also considered just syntax example of course.

---
### # 2
From [Discard pattern](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#discard-pattern)
> A discard pattern cannot be a pattern in an is expression or a switch statement. In those cases, to match any expression, use a var pattern with a discard: var _.

But [Recursive Pattern Matching|Detailed design|Patterns|Discard Pattern](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns#discard-pattern) denotes only `is` pattern

> A discard pattern may not be used as the pattern of an is_pattern_expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#declaration-and-type-patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Uzivatel919 as for the second point, the following code:
```csharp
double measurement = 0.0;
switch (measurement)
{
    case _:
        break;

    default:
        Console.WriteLine($"Measured value is {measurement}.");
        break;
}
```
generates an error `CS0103 The name '_' does not exist in the current context`.

You can do the following to make it compile:
```csharp
double measurement = 0.0;
const double _ = 4.0;
switch (measurement)
{
    case _:
        break;

    default:
        Console.WriteLine($"Measured value is {measurement}.");
        break;
}
```
But here it's the constant pattern, not the discard pattern. Also, this code generates the warning: `CS8512 The name '_' refers to the constant, not the discard pattern. Use 'var _' to discard the value, or '@_' to refer to a constant by that name.`. So, the compiler suggests to use `var _` to discard the value.

So, I assume the spec proposal is not complete.
/cc: @BillWagner

**Comment by pkulikov** [comment]
As for the first point, indeed, currently it's rather an example of how to use parentheses than of changing the precedence. The article is still correct as it doesn't claim that precedence is changed, but maybe another example would be better.

**Comment by Uzivatel919** [comment]
> So, I assume the spec proposal is not complete.

Yes, it seems so.

>  The article is still correct as it doesn't claim that precedence is changed, but maybe another example would be better.

Ok.

I am closing this since I expect proposals are not subject to redaction.
