### ISSUE TITLE
Should the Target Frameworks topic be moved to Core?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#2751]
Per @tdykstra ...

https://github.com/dotnet/docs/pull/2592#pullrequestreview-50960863

> question whether this is really a .NET Core doc rather than a .NET doc as it stands.

https://docs.microsoft.com/en-us/dotnet/standard/frameworks
*docs/standard/frameworks.md*

cc/ @mairaw @richlander

**Comment by mairaw** [comment]
I think it's in the right place. TFM is a more cross-platform concept and it applies to NuGet, creating .NET Standard libraries, etc. For that reason, I'm closing this one.
