### ISSUE TITLE
Is there any other case of unknown _target type_ than when using `var`?

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27515]
> If a target type of a conditional expression is unknown (for example, when you use the var keyword) or in C# 8.0 and earlier, the type of consequent and alternative must be the same or there must be an implicit conversion from one type to the other:

I am not 100 % sure if there is any other case when _target type of a conditional expression is unknown_ beside when using `var` for variable type.

If there is, fine. If not, I guess this better made clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5379a49c-6a81-82a5-cca2-3ab71f432c5c
* Version Independent ID: 1a00e3ec-bec1-3030-9766-a788912bc3b9
* Content: [?: operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)
* Content Source: [docs/csharp/language-reference/operators/conditional-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/conditional-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Uzivatel919 using a discard is another example:
```csharp
using System.Collections.Generic;

public static class Program
{ 
    public static void Main()
    {
        _ = true ? new List<int>() { 0, 1 } : new List<int> { 2, 3 };
        _ = true ? new List<int>() { 0, 1 } : new int[] { 2, 3 };
    }
}
```

The first line compiles. The second line reports `CS0173`: `Type of conditional expression cannot be determined because there is no implicit conversion between 'System.Collections.Generic.List<int>' and 'int[]'`

**Comment by Uzivatel919** [comment]
Aha, I did not consider evaluation with side effect usage.
