### ISSUE TITLE
Incorrect syntax for string indexing

### ISSUE THREAD

**Issue by bugjam** [dotnet/docs#27510]
The Strings page of the F# Language Guide describes the following syntax for string indexing in F#:
`str1[1]`

This syntax is rejected by FSharp Interactive:
_error FS0003: This value is not a function and cannot be applied._

Using the array indexing syntax instead produces the desired result:
`str1.[1]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752405db-4da8-6c06-f58b-22dcc9caa7a7
* Version Independent ID: 78362807-847f-b947-2c75-5036f7765b32
* Content: [Strings - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/strings)
* Content Source: [docs/fsharp/language-reference/strings.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/strings.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
[That is the new indexing syntax in F# 6.](https://devblogs.microsoft.com/dotnet/whats-new-in-fsharp-6/#making-f-simpler-to-learn-indexing-with-expridx) Maybe the article should add a note about that?
