### ISSUE TITLE
Learn about .NET on the https://docs.microsoft.com/en-gb/dotnet/core main page leads to 404

### ISSUE THREAD

**Issue by dr3adl0rd** [dotnet/docs#27528]
Just like in the title, the main page on github has some invalid links.
1. Learn about .NET
2. Learn about the .NET platform
3. Contact Microsoft Support

**Comment by mairaw** [comment]
@BillWagner @IEvangelist should we have a redirect in place for that path?

**Comment by mairaw** [comment]
@gewarren could this also be related to the split up of the redirection file?

https://github.com/gewarren/docs/blob/main/.openpublishing.redirection.core.json#L635

**Comment by gewarren** [comment]
This should be fixed by #27536.

**Comment by mairaw** [comment]
Thanks @gewarren. Closing since link no longer leads to 404.
