### ISSUE TITLE
Link shown for using trimmed/illink 404s

### ISSUE THREAD

**Issue by vcsjones** [dotnet/docs#27529]
### Description

When using `dotnet publish` on a trimmed .NET application, it displays an aka.ms URL, https://aka.ms/dotnet-illink, which as of writing 404s.

### Steps to reproduce

1. Create an empty .NET Console application.
2. Run `dotnet publish -c release /p:RuntimeIdentifier=win10-x64 /p:PublishSingleFile=true /p:SelfContained=true /p:PublishReadyToRun=true /p:PublishTrimmed=true`

In the output, you'll see a link along the lines:

> Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

This takes you to https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained, which currently 404s.

**Comment by mairaw** [comment]
Maybe the split up of the redirection file introduced some issues @gewarren?
I see the entry at https://github.com/gewarren/docs/blob/main/.openpublishing.redirection.core.json#L308, which is supposed to have this entry

**Comment by mairaw** [comment]
On the meantime, perhaps @agocke @richlander could update the aka link to the latest target URL?

**Comment by gewarren** [comment]
This should be fixed by #27536.

**Comment by mairaw** [comment]
Closing since aka is working again.

**Comment by vcsjones** [comment]
Yay! Thank you!
