### ISSUE TITLE
F# arrays - element access syntax

### ISSUE THREAD

**Issue by jcmrva** [dotnet/docs#27520]
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/arrays#access-elements

For this section, the text should be updated to match the code, maybe something like:

> You can access array elements by using brackets (`[` and `]`). The original dot syntax (`.[index]`) is still supported but no longer recommended as of F# 6.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cda87e0-998a-086f-f5ed-2290d7a97966
* Version Independent ID: 45152c64-0643-3c5a-93cb-a2f689170887
* Content: [Arrays in F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/arrays)
* Content Source: [docs/fsharp/language-reference/arrays.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/arrays.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for noting this @jcmrva 

I've added this to our backlog, and added the "up for grabs" label for any community members interested in submitting a PR.

**Comment by eriawan** [comment]
@BillWagner 
This issue should be closed by PR #27520 because that PR is the one that fixed the F# array element access syntax.

**Comment by BillWagner** [comment]
Fixed in #29468
