### ISSUE TITLE
ARM on Windows 10?

### ISSUE THREAD

**Issue by Dana-Prajea** [dotnet/docs#27533]
What about the ARM machines running Windows 10 and 11? Doesn't seem to be listed here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/main/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@TaraOverfield @adegeo Should we add ARM processors to this .NET Framework system requirements page?

**Comment by gewarren** [comment]
Related to #30542.

**Comment by gewarren** [comment]
Closing based on discussion here: https://github.com/dotnet/docs/pull/30619#discussion_r949665391.
