### ISSUE TITLE
The automatic translation is not working as expected

### ISSUE THREAD

**Issue by AdrianDamiao** [dotnet/docs#27530]
**Issue description**

There are some language type errors in the Brazilian Portuguese translation(as we can see in the image below) and the ~~ Edit ~~ option listed in the Contributor's Guide does not appear so I can edit the page. I did not found the Brazilian dotnet GitHub Repository so I am creating this issue here to inform the possible problem. At the following link you can access the broken page: 

#### https://docs.microsoft.com/pt-br/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed/

![microsoftError](https://user-images.githubusercontent.com/79238503/145877051-84266987-f118-4120-a62b-037b2a36b374.png)

**Comment by mairaw** [comment]
Tagging @khoiph1 to comment on this

**Comment by gewarren** [comment]
Ping @kgliang

**Comment by v-alje** [comment]
This issue appears to have been fixed:

![image](https://user-images.githubusercontent.com/4665434/227632448-c4ea2066-7617-4715-a3c5-3733e0b7e376.png)

![image](https://user-images.githubusercontent.com/4665434/227632730-a7e1c55a-a7c4-4338-979d-f1b16283408d.png)
