### ISSUE TITLE
How to interpret (pinned handle) the output of !gcroot command?

### ISSUE THREAD

**Issue by veruyandi** [dotnet/docs#27544]
[Enter feedback here]
How should i interpret when I see this in the output:
HandleTable:
    00007F6C98BB15F8 (pinned handle)

I have an example output here: 

0:000> !gcroot 000000322f1219b0
HandleTable:
    0000003344471ff8 (pinned handle)
    -> 00000032f9ae3968 System.Object[]
    -> 00000030f9ed2f00 System.Collections.ArrayList
    -> 00000031f9fccef8 System.Object[]
    -> 00000031f9f27d18 SBUtils.TElByteArrayManager
    -> 00000031f9f27d48 System.Collections.ArrayList
    -> 000000332df9a220 System.Object[]
    -> 000000322f121980 SBUtils.TElByteArrayInfo
    -> 000000322f1219b0 System.Byte[]

SBUtils come from a third party SecureBlackbox.dll. Does "Pinned handle" mean that it is due to a reference from unmanaged to managed object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2913d994-4c72-cc6e-0bd4-ba122ae21753
* Version Independent ID: 03f3761e-be31-bae9-6ac7-ad86db389212
* Content: [Debug a memory leak tutorial](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak)
* Content Source: [docs/core/diagnostics/debug-memory-leak.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/debug-memory-leak.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by gewarren** [comment]
> Does "Pinned handle" mean that it is due to a reference from unmanaged to managed object?

Yes, that it likely the case. See https://learn.microsoft.com/en-us/dotnet/framework/interop/copying-and-pinning.
