### ISSUE TITLE
[Breaking change]: IAsyncEnumerable API buffered result stopped working even when not using System.Text.Json

### ISSUE THREAD

**Issue by t00** [dotnet/docs#27542]
### Description

I am using buffered output from AutoMapper ToAsyncEnumerable with API configured to use Newtonsoft Json as JSON serializer. 

`context.Table.AsQueryable().ProjectTo<TableModel>(mapper.ConfigurationProvider).ToAsyncEnumerable()`

After upgrade to dotnet 6.0.100, the response from this API call is as follows:

`{"current":null}`

Since such behavior is not documented, I would assume this is a breaking change or a bug. I am using AutoMapper 9, running on Linux.

### Version

Other (please put exact version in description textbox)

### Previous behavior

Resulting JSON array was returned

### New behavior

`{"current":null}` is returned

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

There should be a method of streaming results without oboe.js.

### Recommended action

Bring back previous streaming behavior.

### Feature area

ASP.NET Core

**Comment by gewarren** [comment]
@eiriktsarpalis Do you know what might be causing this?

**Comment by eiriktsarpalis** [comment]
I'm not sure. A minimal reproduction would help here. @t00 have you filed an issue in dotnet/runtime?
