### ISSUE TITLE
Service Names MUST Match

### ISSUE THREAD

**Issue by elmorr** [dotnet/docs#27558]
[Enter feedback here]

The section on "Add custom event log functionality" on this page mentions customization of a log source name following the example on step4, but it does not tell you that this name has to match the "ServiceName" in the 'Designer' properties of the '*service*.cs' file in order for the log to be accepted and displayed by the Windows Event Viewer. If you follow the instructions and make a special name, your log NEVER appears.

I further note this help file did not mention the need to configure the "ServiceName" in the 'Designer' properties menu at all. Without doing so it is not possible to have your service show logs in the Windows Event Viewer with the correct name (and *custom log* entries written will not appear at all; you only get started/stopped/service manager default messages). Please add comments to this help file for both of these items to prevent users from being completely lost.

![image](https://user-images.githubusercontent.com/71360651/146048719-7d6e3469-26eb-4fc9-ab60-c41bea650597.png)
![image](https://user-images.githubusercontent.com/71360651/146048772-54e2ebc9-feb8-4a03-974e-4a7fca924a85.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Tutorial: Create a Windows service app - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Hi @elmorr. I ran through these instructions and it worked for me as-is. Your description seems to imply that you thought the instructions said to "make a special name" for the source. This is not the case - you should copy the code as written in the article for the MyNewService() constructor, that is, set the `EventLog.Source` property to "MySource".

> I further note this help file did not mention the need to configure the "ServiceName" in the 'Designer' properties menu at all.
This is shown in step 3 of the [Rename the service](https://docs.microsoft.com/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#rename-the-service) section.

**Comment by gewarren** [comment]
I'm going to close this issue. If you still feel that something is missing, please do comment.
