### ISSUE TITLE
IValidateOptions for complex validation will not compile

### ISSUE THREAD

**Issue by alvipeo** [dotnet/docs#27561]
This code in https://docs.microsoft.com/en-us/dotnet/core/extensions/options#ivalidateoptions-for-complex-validation will not compile:
```
public ValidateSettingsOptions(IConfiguration config) =>
        _settings = config.GetSection(SettingsOptions.ConfigurationSectionName)
                          .Get<SettingsOptions>();
```
with the error:
> IConfigurationSection does not contain a definition for 'Get'.

Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @alvipeo - this code does compile. It was compiled as part of #27051. If you're just copied code out of this and trying to paste it into your existing project, you're going to experience problems. It's better to read the docs, and understand all the moving parts first. You're probably just missing a `PackageReference` - see here:

https://github.com/dotnet/docs/blob/main/docs/core/extensions/snippets/configuration/console-json/console-json.csproj
