### ISSUE TITLE
C# Tutorial: Handling Null and ?? and ?. Operators

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#276]
This would cover the newer operators like ?? and ?. that work well when programming with reference types that may be null. I’m not sure I like the title yet.

**Comment by jfversluis** [comment]
Hi @BillWagner after the great PGI session I'd like to take a first shot at this. And this seems like a nice small one to get the hang of it. And it seems about time that this is picked up.. ;)

Ant pointers on this still being relevant and how to proceed?

**Comment by BillWagner** [comment]
Thanks for reaching out @jfversluis 

I apologize for the late response, I was enjoying the holidays. 🎄 🍾 

Let's start with an outline (either as a comment here, or as a WIP labelled PR.)  

I'd like readers to learn techniques for writing concise and clear code using ?? and ?. instead of a series of nested if / else statements.  Beyond that, I haven't worked through organizing the topic yet.

**Comment by jfversluis** [comment]
No problem @BillWagner ! As you should! And a happy new year to you 🎉 

I'll see what I can do! Thanks!

**Comment by sputier** [comment]
@jfversluis Have you started working on this one ? Do you need any help ?

**Comment by jfversluis** [comment]
Hi @sputier I'm so sorry, this totally got away from me! But maybe we could have a little chat on tips and best practices if you have some experience?

**Comment by sputier** [comment]
Hi @jfversluis ! Of course, if I can help you, I will ! For this first contribution, I would only suggest you to keep things simple : explain everything thinking a beginner could read and understand what you wrote :-) 

Feel free to ping me (here or on twitter : Same @) if you have any question. If I have the answer you need, I'll be glad to give it to you !

**Comment by jfversluis** [comment]
First idea for an outline below.

# Null coalescing and operator

## Introduction

### Null coalescing (??)

#### Sample

#### Remarks

### Null operator (?.)

#### Sample

#### Remarkts

## Conclusion

I don't think there is much more to it? Or am I missing anything?

**Comment by sputier** [comment]
@jfversluis If you don't omit comparing **if** syntax with each of these operators before introducing the samples, it think this outline will be a good start for the article. Feel free to update it if you notice anything that should be highlighted (language version ?). 

If you feel a bit insecure about what you wrote, you can create a WIP (work in progress) PR (i.e. labeled "[WIP] ...."), so the community may help you reviewing it.

**Comment by sputier** [comment]
@jfversluis If you don't omit comparing **if** syntax with each of these operators before introducing the samples, I think this outline will be a good start for the article. Feel free to update it if you notice anything that should be highlighted (language version ?). 

If you feel a bit insecure about what you wrote, you can create a WIP (work in progress) PR (i.e. labeled "[WIP] ...."), so the community may help you reviewing it.

**Comment by sputier** [comment]
Since @jfversluis droped the ball, I'm going to take over from him to tackle this issue 😄

**Comment by lucasnobredev** [comment]
Hi @BillWagner !

This issue still makes sense? I saw an article about [?? operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator) and another about [? reference types null operator](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/operators/null-conditional-operators). 

The idea is join both subjects or what?

**Comment by BillWagner** [comment]
@lucasnobredev It still makes sense.  

We cover those features well in the reference. However, we don't have tutorials, or How To articles on using `??`, `?.` and `?[]` to work with variables that may have the `null` value.
