### ISSUE TITLE
public virtual int Count { get; }

### ISSUE THREAD

**Issue by Lliuduanduan** [dotnet/docs#27602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89022fe7-b2e3-5fb5-4930-d6bc5284081a
* Version Independent ID: 6a4f3ec1-e2eb-e046-d840-1c442276b3fb
* Content: [virtual - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual)
* Content Source: [docs/csharp/language-reference/keywords/virtual.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/virtual.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @Lliuduanduan 

Can you add more information on what you'd like to see in this article? It's unclear to me what was should address.
