### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by leeeunyong** [dotnet/docs#27615]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2cb61f-1605-70ba-c5fb-cc4a9d9f2c8d
* Version Independent ID: 6eaec3e9-0ed9-f3ec-7516-032d57246715
* Content: [Compiler Error CS0103](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103?f1url=%3FappId%3Droslyn%26k%3Dk(CS0103))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0103.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0103.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋  @leeeunyong 

Can you elaborate on what you'd like to see here?
