### ISSUE TITLE
Is ??= thread safe?

### ISSUE THREAD

**Issue by ahdung** [dotnet/docs#27613]
Or atomicity?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 038ae35e-c5e9-e1a4-a6dd-afe379201245
* Version Independent ID: d73f3d5a-00d4-2e22-c120-8e8d6d101a54
* Content: [?? and ??= operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator)
* Content Source: [docs/csharp/language-reference/operators/null-coalescing-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/null-coalescing-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
The answer to both is nothing special for `??=`.
If you want to have thread safe and atomicity guaranteed, then use the `Interlocked`-methods.

> Is ??= thread safe?

No it's not. Why should it?
Look at the [generated code](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQhGAzAATZkDCZA3oWY2QA5QCWAbgIYAuMZEYACsYYHmQD6goQG4GTeY1IDho8QFkAFAEoyAXgB8k6WQD8pvWQB2MAO4qRYnXIIBfIA==), and you'll see what happens and that's not thread-safe.

> Or atomicity?

This depends on the type. 
For reference types the runtime guarantees atomicity, as references are always read / written atomicity (they are cpu word size, so atomic by construction).
For value types there may occur torn reads / torn writes, if the size of the value type is greater than the cpu word size.

**Comment by BillWagner** [comment]
Thanks for the answers @gfoidl 

I'll close this as an answered question.
