### ISSUE TITLE
Great Tutorial.

### ISSUE THREAD

**Issue by rickhenderson** [dotnet/docs#27619]
It's great to finally see some well-written tutorials on the .Net site. I'm an oldschool command line programmer so all these new bells and whistles are pretty crazy, but I love how this tutorial starts with VS Code, uses dotnet command line commands, and explains the topics well with a good flow.

Now I can learn all about Unit Tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cbb75b-e0aa-13c6-c07d-65f0f0f68da2
* Version Independent ID: 06ecbd1e-dad7-fbac-9160-dfce34df4d2c
* Content: [Create a .NET class library using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code?pivots=dotnet-6-0)
* Content Source: [docs/core/tutorials/library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
Thanks for the feedback @rickhenderson. I'll close this now.
