### ISSUE TITLE
The dotnet executable has been removed by a recent update from openSuse Linux Leap 15.3

### ISSUE THREAD

**Issue by n-t-roff** [dotnet/docs#27625]
Since a recent .net package update on openSuse Leap 15.3 the dotnet command has been removed. Who is the maintainer of these packages or where can this bug be submitted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016558a3-e021-04ce-e375-15b23f589ed9
* Version Independent ID: 89b6eb1c-2202-70ee-364d-fc2ede379e74
* Content: [Install .NET on openSUSE - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-opensuse#feedback)
* Content Source: [docs/core/install/linux-opensuse.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-opensuse.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by n-t-roff** [comment]
Just as a reminder--the `dotnet` command has been removed from the packages provided for openSuse Linux a month ago, so .net cannot be used on openSuse Linux anymore. Who does maintain these packages or where can a bug report be filed?

**Comment by adegeo** [comment]
Your best bet is to open a bug with the dotnet code repo: https://github.com/dotnet/sdk

**Comment by adegeo** [comment]
Would you like to open it, I could do it if you don't have the time. Just let me know.

**Comment by n-t-roff** [comment]
It would be great if you could do that. Thank you very much!

**Comment by n-t-roff** [comment]
Nevertheless it is not really a SDK issue. I'm sure it works fine on any other system and if I would compile from source (if possible). It is an issue of the specific openSuse package, someone just has forgotten to add the `dotnet` binary when updating the package. But openSuse is one of the two major commercial  Linux distros, so it may effect many production systems.
