### ISSUE TITLE
Severely out of date?

### ISSUE THREAD

**Issue by rstarkov** [dotnet/docs#27628]
This guide appears to be severely out of date. The built-in ConsoleLogger source has been much more useful.

At the very least, this guide needs to talk about how to make a properly configurable logging provider, by talking about `ProviderAlias` and `LoggerProviderOptions.RegisterProviderOptions`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @rstarkov - I do not believe it's fair to call this article "severely out of date", it was literally updated November of 2021, and is still accurate in every way.

Also, the article does include `LoggerProviderOptions.RegisterProviderOptions`. See the second code snippet in [this section](https://docs.microsoft.com/dotnet/core/extensions/custom-logging-provider#usage-and-registration-of-the-custom-logger).


The only thing that it doesn't include is the `ProviderAlias`, I'll add that.

**Comment by rstarkov** [comment]
Indeed. I don't know how I missed that... Thank you!

**Comment by IEvangelist** [comment]
Hi again @rstarkov, please see PR: https://github.com/dotnet/docs/pull/27723. This adds a few more bits to the example and includes the `ProviderAlias` as well as custom configuration overrides.
