### ISSUE TITLE
Inverse Spanish Inquisition for using directive

### ISSUE THREAD

**Issue by kaimikael** [dotnet/docs#27635]
“The using keyword has three major uses:
*     The using statement defines a scope at the end of which an object will be disposed.
*     The using directive creates an alias for a namespace or imports types defined in other namespaces.”

One does expect a third bullet point…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a731ad7b-0655-4bb3-2478-0cbb4d063f02
* Version Independent ID: 2ba9241c-0836-d05e-5ba1-ebc5498d2009
* Content: [using keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using)
* Content Source: [docs/csharp/language-reference/keywords/using.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @kaimikael 

I've opened a PR to fix this issue.
