### ISSUE TITLE
Code example has undesirable results in how it copies structure.

### ISSUE THREAD

**Issue by tchadwick** [dotnet/docs#27636]
This code flattens the source structure in the destination, it does not perform like a true copy operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d050f686-38eb-bb76-5747-9e138f4da679
* Version Independent ID: 93b69d5a-5df1-c0e1-930d-2f5ee1c1fe6e
* Content: [How to: Copy directories](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories)
* Content Source: [docs/standard/io/how-to-copy-directories.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/how-to-copy-directories.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@tchadwick Hello. I've run this code and it's working fine for me. can you share more information about your setup?

1. What OS are you using?
2. Did you change the code?
3. Which .NET version are you using?

**Comment by tchadwick** [comment]
Hey Andy/Steve,
Thank you for the response, I’m using Windows 10, I didn’t change the code, and .NET 6.  I think the issue is nested folders so:
1.Folder 1 (Source)
->2. Sub-Folder 1
->->3. Sub-SubFolder 2
Becomes:
1.Folder 1 (Destination)
->2. Sub-Folder1
->3. Sub-Folder2
At least, that’s what I’m seeing, are you seeing differently?
Thanks,
Trevor Chadwick

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by adegeo** [comment]
Hmm, it seems to all be working fine for me. I tested in .NET 6 with both the C# and VB.NET code. :(
