### ISSUE TITLE
Async operations using Variant Generic Interfaces

### ISSUE THREAD

**Issue by AlthalusDGr8** [dotnet/docs#27630]
Is there a way to create an async interface using Variant Generic Interfaces?

Am trying to build a generic async repo (not powered by ORM) and am trying to do something of the sort:

   /// <summary>
    /// This is the generic Entity Repository
    /// </summary>
    public interface IEntityRepo<out TDBEntity> where TDBEntity : IDbEntity
	{
		/// <summary>
		/// Return all entities
		/// </summary>
		/// <param name="cancellationToken"></param>
		/// <returns></returns>
		Task<IEnumerable<TDBEntity>> GetAllAsync(CancellationToken cancellationToken = default);
    }

public interface IUserAccountRepo <out TDBEntity> : IEntityRepo<out TDBEntity>
{
      Task<TDBEntity> GetAccountByEmailAsync(string emailAddress, CancellationToken cancellationToken = default))
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada3150a-24a0-a90c-f7aa-ea1ca47d7487
* Version Independent ID: 8cfde752-8d67-5975-00ed-649edce36733
* Content: [Creating Variant Generic Interfaces (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces?source=docs)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/covariance-contravariance/creating-variant-generic-interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋 @AlthalusDGr8 

Based on the sample code you've shown, yes, that would work.  As you work through your example, you can ask specific questions in our [Q & A forums](https://docs.microsoft.com/answers/topics/dotnet-csharp.html) on C#.

I'll close this as an answered question.

**Comment by svick** [comment]
@BillWagner It doesn't work, it produces errors like:

> CS1961 Invalid variance: The type parameter 'TDBEntity' must be invariantly valid on 'UserQuery.IEntityRepo\<TDBEntity>.GetAllAsync(CancellationToken)'. 'TDBEntity' is covariant.

@AlthalusDGr8 Under normal circumstances, no, you can't combine variance with `async` code.

If you really wanted to do it, you would need a covariant `ITask<T>` interface, e.g. [this one](https://github.com/jam40jeff/ITask).

**Comment by BillWagner** [comment]
Thanks for the corrections @svick I appreciate it.
