### ISSUE TITLE
Represent bitmasks as boolean fields, not repeated enums.

### ISSUE THREAD

**Issue by JasonPolisAdmin** [dotnet/docs#27638]
Repeated enums don't work with connectors using Change Data Capture.
Use a message type containing boolean fields, numbered incrementally (1,2,3,4...) rather than powers of 2 (1,2,4,8...).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad07b85-98a7-3c73-55bf-42006bdd84b2
* Version Independent ID: 6a5f8674-5f44-c0ad-2eb9-7db2e2d55bb6
* Content: [Protobuf enumerations - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-enums)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-enums.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/protobuf-enums.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by erjain** [comment]
Hi @JamesNK, what are your thoughts on this?

**Comment by JamesNK** [comment]
I don't have anything to add. I'm not familiar with "connectors using Change Data Capture".
