### ISSUE TITLE
High DPI support in Windows Forms page is incorrect for pre-4.7 applications

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/docs#2764]
# Issue Title

High DPI support in Windows Forms page is incorrect for pre-4.7 applications

## Issues with Existing Topics

If the issue is a simple typo or similar correction, you can just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.
[https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms) 
The topic doesn't cover the fact that the new application configuration section should only be used where the app is going to run on systems only with 4.7 or greater. If it runs on earlier frameworks a Configurationerror.sException: Unrecognized configuration section occurs because the earlier framework doesn't recognize the new section.

Also - the link to owner drawn [controls](https://docs.microsoft.com/en-us/dotnet/articles/framework/winforms/user-drawn controls) hasn't been migrated yet so results in a 404 confusing users.

**Comment by mairaw** [comment]
@merriemcgaw the link has been fixed back in May with PR #1928. I'll respond to the customer on the topic. We can make the updates to make it clearer that you get an exception in earlier versions of the framework, but the topic mentions .NET Framework 4.7 throughout, starting with the opening paragraph.

**Comment by BillWagner** [comment]
One other addition:  Where we have the *Important* note that this technique does not work on .NET 4.6 and earlier, we should link to docs that describe how to use the manifest for high-DPI display on earlier runtimes.
