### ISSUE TITLE
Clarify C# 9 / C# 10 differences

### ISSUE THREAD

**Issue by CalvinAllen** [dotnet/docs#27664]
The article starts out with a call to C# 9, but I found the switch to C# 10 features to be very easy to miss.  I made an original assumption that in C# 9, record / record class / record struct, were all introduced at the same time.  I also don't see clarification that a `record struct` is a "value type".  Since `record` is called out in the beginning as a "reference type", I began to assume that a `record struct` was as well.  In between the C# 9 and C# 10 section (mostly at the top, by the way), it's called out that a `record` uses "value equality" (while also mentioning "reference type" again), but it's never mentioned that a `record struct` ALSO uses value equality.  Maybe some of that assumes underlying knowledge of a `struct`, since its the same, but I think it would be good to call it out explicitly since `record class` called it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @CalvinAllen 

I've added this to the current sprint. 

From our offline conversation, the main concerns are to distinguish `record`, `record class` and `record struct`. C# 9 added `record` types (which are classes). C# 10 added `record struct` types, and allowed `record class` types to clarify that a `record` is a class type.
