### ISSUE TITLE
Unclear which syntax to use to list warnings

### ISSUE THREAD

**Issue by lmorvan** [dotnet/docs#27661]
On this page, we have a few examples: `<WarningsAsErrors>0219,0168</WarningsAsErrors>`, `<WarningsNotAsErrors>0219,0168</WarningsNotAsErrors>` and `<DisabledWarnings>number1, number2</DisabledWarnings>`.

They are only showing numbers, while some of the warnings displayed may be `NU...`, `CS...`, or even `MSB...`.

How are we supposed to list these warnings?
Is the syntax `<WarningsNotAsErrors>NU1603</WarningsNotAsErrors>` supposed to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great question @loicmorvan-ansys 

This should be clarified. The prefix `CS` is optional. Either `0219,0168` or `CS0219,CS0168` will work.

**Comment by KalleOlaviNiemitalo** [comment]
It's consistent with [#pragma warning](https://docs.microsoft.com/dotnet/csharp/language-reference/preprocessor-directives#pragma-warning), then.

**Comment by loicmorvan-ansys** [comment]
Does this mean that we can't finely control all warnings that are emitted when restoring/building/testing/executing a .csproj?

**Comment by loicmorvan-ansys** [comment]
I mean directly from the .csproj itself.

**Comment by henioStraszny** [comment]
I've tried to hide MSB4011 warninigs with following entry in csproj: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<DisabledWarnings>4011;MSB4011</DisabledWarnings>
		<NoWarn>4011;MSB4011</NoWarn>
        </PropertyGroup>
        ...
 </Project> 
```

This setting is not used and I still see warninigs.

If I run `dotnet build /nowarn:msb4011` warnings are hidden.
