### ISSUE TITLE
Forward slash missing on /norestart option

### ISSUE THREAD

**Issue by candritzky** [dotnet/docs#27662]
In section "Windows Installer": The /norestart option should have a leading forward slash. See bullet point list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
