### ISSUE TITLE
Document anonymous .ToString ()

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/docs#27685]
Please explain how anonymous types override [ToString ()](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b30ebe-b640-449b-3602-9891a55794db
* Version Independent ID: dd937177-98f0-a797-d49b-29332aae0614
* Content: [Anonymous Types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/anonymous-types)
* Content Source: [docs/csharp/fundamentals/types/anonymous-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/anonymous-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @yecril71pl 

I've added it to our backlog to address.
