### ISSUE TITLE
Step Thru a program

### ISSUE THREAD

**Issue by WhiskeyRomeoLima** [dotnet/docs#27699]
Step 5: After entering a name and pressing enter to respond to the name prompt, F11 does not move to the next line.  The console window expands on the use of F11 and the next F11 returns the console line to the original side.  The program is stuck on this line: var currentDate = DateTime.Now;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582
* Version Independent ID: aeb94c3f-50e0-eb84-e469-f6eb778bad62
* Content: [Debug a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
In the command prompt window make sure that you press Enter after entering the name as requested. You won't see the input that you type in while you're typing it, but it's picked up by the program, and the program can't advance until the Enter key is pressed.

**Comment by WhiskeyRomeoLima** [comment]
I did all that. The console would only keep reloading. So I had to kill the program. I had other configuration problems VS 2022. After fixing them, everything ran just fine. 

Bill Lucas
