### ISSUE TITLE
Button 'New' missing...

### ISSUE THREAD

**Issue by Luuk34** [dotnet/docs#27695]
" To create a new key file, choose **New** and enter its name in the Create Strong Name Key dialog box."
The button New is missing....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94526da-6739-ad3b-c0eb-48652e70a062
* Version Independent ID: 73c57596-00af-2739-b206-bcbea262fcbb
* Content: [How to: Sign an assembly with a strong name](https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name)
* Content Source: [docs/standard/assembly/sign-strong-name.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/sign-strong-name.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by ajtruckle** [comment]
But what about .NET8 projects? No facility is there now to create a sign key.
