### ISSUE TITLE
Stream should implement DisposeAsyncCore?

### ISSUE THREAD

**Issue by jamesivie** [dotnet/docs#27698]
This is all fine, but what do we do when implementing a Stream?  Stream implements IAsyncDisposable, but does *not* define the protected DisposeAsyncCore() member.  Perhaps y'all should follow your own advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
`Stream` and other related types within the runtime are far more elaborate and complex. It's not ideal to base guidance on such complexities. The .NET's `Stream` type relies on various [helpers and strategies](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Private.CoreLib/src/System/IO/Strategies). It's a different approach as it's more complex. Do you have a product suggestion or a question about the docs itself?

**Comment by jamesivie** [comment]
@IEvangelist I'm not asking about the implementations of Stream within the framework, I'm talking about my own implementation of Stream.  [Stream](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs) is abstract and does *not* rely on strategies or helpers, and follows the IDisposable pattern, but not this one.  The reason I ask is that Stream implementations are relatively common and there should be documentation *somewhere* that explains how to properly implement DisposeAsync in a Stream implementation, as this is something that can be *very* confusing and is easily done incorrectly (thus the guidance about implementing IDisposable in the Stream documentation).  Because of that complexity, documenting how to properly implement this for a new Stream type is *more* important than documenting how to properly implement this on your own base class.  Whether that's done here or in the [Stream documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.IO.Stream);k(DevLang-csharp)%26rd%3Dtrue&view=net-6.0), where it is conspicuously absent, it needs to happen.  Which of those it ends up in is ultimately a choice for y'all.

**Comment by IEvangelist** [comment]
Hi @jamesivie - you'd want to follow the pattern here, where you implement both `IDisposable` and `IAsyncDisposable`.

[Implement both dispose and async dispose patterns](https://docs.microsoft.com/dotnet/standard/garbage-collection/implementing-disposeasync#implement-both-dispose-and-async-dispose-patterns)
