### ISSUE TITLE
microsftsegéd.md

### ISSUE THREAD

**Issue by haaami01** [dotnet/docs#27694]
[Ide írja be a visszajelzését]

`Microsoft Alias`
---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Manually install .NET on Linux - .NET](https://docs.microsoft.com/hu-hu/dotnet/core/install/linux-scripted-manual#manual-install)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@haaami01 Can you provide more information about the specific problem with the documentation?
