### ISSUE TITLE
The description for "Accessibility" can have a few more details.

### ISSUE THREAD

**Issue by Anupam4git** [dotnet/docs#27701]
Under this section its mentioned that "The default accessibility is private." I think it can be further mentioned here that its internal for the Class members. Because for Class the default accessibility is "Internal". 
Kindly confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb21e6e-7798-e557-be3f-f27ab9c93e05
* Version Independent ID: a526a9cc-938e-7528-b5b4-4879c5085152
* Content: [Classes, structs, and records](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/)
* Content Source: [docs/csharp/fundamentals/object-oriented/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 297236](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297236)

**Comment by BillWagner** [comment]
Thank you for noting this @Anupam4git 

I've added it to our backlog to address when we next update this section.
