### ISSUE TITLE
AsyncDisposable guidance concerns

### ISSUE THREAD

**Issue by IgorMilavec** [dotnet/docs#27707]
What is the rationale of calling ```Dispose``` with ```disposing: false``` in the guidance document?
```csharp
public async ValueTask DisposeAsync()
{
    await DisposeAsyncCore().ConfigureAwait(false);

    Dispose(disposing: false);
#pragma warning disable CA1816 // Dispose methods should call SuppressFinalize
    GC.SuppressFinalize(this);
#pragma warning restore CA1816 // Dispose methods should call SuppressFinalize
}
```

I'm concerned with a scenario where a subclass developer overrides `Dispose(bool disposing)`, but forgets to override `DisposeAsyncCore()`. If they implements `Dispose(bool disposing)` according to the pattern, they will not release managed resources with `disposing: false`. In such a scenario we lose deterministic disposal.

```csharp
class MyExample : ExampleConjunctiveDisposableusing
{
    private readonly Stream stream;

    public MyExample(Stream stream) :
        base()
    {
        this.stream = stream ?? throw new ArgumentNullException(nameof(stream));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            this.stream.Dispose();
        }
    }

    // The developer forgot to override DisposeAsyncCore:
    //protected override async ValueTask DisposeAsyncCore()
    //{
    //    await base.DisposeAsyncCore().ConfigureAwait(false);
    //    await stream.DisposeAsync().ConfigureAwait(false);
    //}
}
```

Would it not be better to suggest calling `Dispose(disposing: true)` from `DisposeAsync()` in the guidelines? Worst case in this scenario is that the `DisposeAsync()` would block for some of the resources, but we would get deterministic disposal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
This is specifically addressed in the guidance as to why it's done this way:

> One primary difference in the async dispose pattern compared to the dispose pattern, is that the call from `DisposeAsync()` to the `Dispose(bool)` overload method is given `false` as an argument. When implementing the `IDisposable.Dispose()` method, however, `true` is passed instead. This helps ensure functional equivalence with the synchronous dispose pattern, and further ensures that finalizer code paths still get invoked. In other words, the `DisposeAsyncCore()` method will dispose of managed resources asynchronously, so you don't want to dispose of them synchronously as well. Therefore, call `Dispose(false)` instead of `Dispose(true)`.
