### ISSUE TITLE
Move Serialization docs from Framework to .NET Guide

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/docs#2770]
.NET Core 2.0 now support binary serialization! (with some subtle differences)

- [x] Cleanup and move serialization docs from  https://docs.microsoft.com/en-us/dotnet/framework/serialization/ to .NET Guide. (Maira)
- [x] Note the differences between .NET Core and Desktop/Mono (as the dev, I can do that).
- [x] Request redirection via Akamai (Maira)

edit: @mairaw formatted steps as subtasks and added Akamai redirection task

**Comment by mairaw** [comment]
I'll work on moving the docs and then you can add the differences.

**Comment by mairaw** [comment]
I'll request the redirection for these topics via Akamai (backend) instead of doing it manually.

**Comment by mairaw** [comment]
@ViktorHofer the docs move is done. You can proceed with your edits. Redirection will be applied as soon as the docs go live.

**Comment by mairaw** [comment]
Fixed by #2780 and #2841
