### ISSUE TITLE
this page is hard to understand. not well organized

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/docs#27706]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294a082e-5584-008e-b83a-7f090d898cda
* Version Independent ID: d4a11dfa-2836-b423-63cd-c356e72e16a7
* Content: [Use record types - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records)
* Content Source: [docs/csharp/whats-new/tutorials/records.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @tnlthanzeel 

I'm sorry this was hard to understand. Can you add a comment with some of the questions you had while reading? That additioanl detail will help us improve.

Thank you.
