### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by AndyLeung94** [dotnet/docs#27729]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/add
Operating System: windows
![image](https://user-images.githubusercontent.com/31531016/148030931-688de9f8-fc7f-45fb-8e88-7b6ba336bd6f.png)

**Comment by mairaw** [comment]
Thanks @AndyLeung94. I'll have a fix shortly. 

@buyaa-n this is a website issue, so it should stay in dotnet/core next time.

**Comment by buyaa-n** [comment]
> @buyaa-n this is a website issue, so it should stay in dotnet/core next time.

Got it, thanks @mairaw
