### ISSUE TITLE
Invalid code initializing pubsub handlers

### ISSUE THREAD

**Issue by scott-moxham** [dotnet/docs#27724]
app doesn't contain the methods `MapControllers()` or `MapSubscribeHandler`.
I think instead of
`var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.UseCloudEvents();
app.MapControllers();
app.MapSubscribeHandler();`

It should instead be
`var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.UseCloudEvents();
app.UseEndpoints( endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapSubscribeHandler();
});`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d1c385-3546-7612-b8b1-4231681dca8a
* Version Independent ID: 497a2367-15d7-6be0-7974-1415e3402b08
* Content: [The Dapr publish & subscribe building block](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/publish-subscribe)
* Content Source: [docs/architecture/dapr-for-net-developers/publish-subscribe.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/publish-subscribe.md)
* Product: **dotnet-architecture**
* GitHub Login: @EdwinVW
* Microsoft Alias: **nanil**

**Comment by EdwinVW** [comment]
In .NET 6, app does offer these extension-methods. See [sample code](https://github.com/EdwinVW/dapr-traffic-control/blob/main/src/FineCollectionService/Program.cs#L28).

**Comment by IEvangelist** [comment]
Hi @scott-moxham - @EdwinVW is correct. This content has been updated to .NET 6 as it's the latest long-term support (LTS) version. I'm going to close this as it's a non-issue.

**Comment by scott-moxham** [comment]
Thanks. My mistake, I'm still on .Net5.
