### ISSUE TITLE
CI with .NET SDK article looks outdated

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#27722]
Haven't fully read through it, but it references .NET Core 1.0.1. So it's too outdated. I also think it might make sense to move the article from `core/tools` to `devops`

cc @IEvangelist 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc010c2-97fa-cf36-689e-c328863397bf
* Version Independent ID: 5d3c5144-af16-1b28-fd84-1457c534037b
* Content: [Continuous Integration (CI) with .NET SDK and tools - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli)
* Content Source: [docs/core/tools/using-ci-with-cli.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/using-ci-with-cli.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. I agree that it might fit better under DevOps.
