### ISSUE TITLE
Init accessor page needs better explanation and examples.

### ISSUE THREAD

**Issue by simeyla** [dotnet/docs#27738]
I've been using C# for 20 years and found out about { init; } today.

This page needs better examples. It says `"An init-only setter assigns a value to the property or the indexer element only during object construction."` but there are no examples of actual object construction or even mention of why you would use it over `{ private set; }`.

What does it mean and why do I need it? I'm guessing it means that for `int Property { get; init; }` you are only allowed to set it during construction. And that you can't just come back later and set `obj.Property = 456` .

I can imagine for beginners this page would be VERY confusing. 
'During construction' may imply 'from the constructor' which I'm guessing is true, but then why not use 'private set'?

Adding something like the following to describe how `{ int Property { get; init; }` might work would make things much clearer.

```
// Allowed
var something = new Something { 
   Property = 123
}

// Allowed
Something() {
   this.Property = 123;
}

// Not allowed
something.Property = 456;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 816634c5-6e7d-3845-f9a3-1ce305fea838
* Version Independent ID: fc780319-a7fd-d9d1-1877-638ac05eb5f4
* Content: [init keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init)
* Content Source: [docs/csharp/language-reference/keywords/init.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/init.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 181302](https://dev.azure.com/msft-skilling/Content/_workitems/edit/181302)

**Comment by BillWagner** [comment]
Thanks for writing this @simeyla 

I've added this to our backlog to address when we next update this article.
