### ISSUE TITLE
Improvement of the virtual void Dispose(bool disposing) implementations - single source of thruth for IsDisposed

### ISSUE THREAD

**Issue by tmaierhofer** [dotnet/docs#27744]
I think the described implementation has a flaw:

Every class maintains it own state for redundant call detection and checks this on its own:

`private bool _disposedValue;`

And the `isDisposed` Information is hidden from the outside world.

```csharp
class DerivedClassWithFinalizer : BaseClassWithFinalizer
{
    // To detect redundant calls
    private bool _disposedValue;

    ~DerivedClassWithFinalizer() => this.Dispose(false);

    // Protected implementation of Dispose pattern.
    protected override void Dispose(bool disposing)
    {
        if (!_disposedValue)
        {
            if (disposing)
            {
                // TODO: dispose managed state (managed objects).
            }

            // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
            // TODO: set large fields to null.
            _disposedValue = true;
        }

        // Call the base class implementation.
        base.Dispose(disposing);
    }
}
```

From my point of view the base class should introduce a public property: 
`public IsDisposed{ get; private set; }` and give the derived class the possibility to check it.

This has two benefits:

* The `IsDisposed` property can be asserted in unit tests and you can introduce diagnostic code for sporadic bugs.
* The base class is the only class which has the responsibility to change it, means you have a proper way to assert if `base.Dispose(disposing)` is called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implement a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@IEvangelist Can you take a look?

**Comment by IEvangelist** [comment]
Hi @tmaierhofer,

Thank you for raising this issue, we really appreciate it.

> I think the described implementation has a flaw

I'm not sure I'm seeing the flaw, please help me understand.

> the `isDisposed` Information is hidden from the outside world

Did you mean to say the `disposing` parameter is hidden, or are you referring to the `_disposedValue` field?

> Every class maintains its own state for redundant call detection

You're making an assumption that every class maintains state about whether or not something is disposed. That assumption is inaccurate, while it's a recommendation it is not always followed.

I see that you're proposing that the base class has an `IsDisposed` property which is only assignable within the base class itself. And I agree that this _might_ help with unit testing and asserting proper calls to `base.Dispose`, but that's kind of beyond the scope of this article. This is a very well-established pattern, and your argument claims there's a flaw but that's not really true. It's an opinion that favors testability, which isn't a bad opinion - I'm just not sure it warrants changing the pattern holistically.

**Comment by sharwell** [comment]
I generally don't include a `_disposedValue` field (or property) at all. In many cases, idempotency of Dispose for public APIs can be provided without checking this field. For internal types, it's not always necessary to account for Dispose being called multiple times, and when it is necessary the earlier point often applies.

**Comment by bartonjs** [comment]
Using a `_disposed` field is in the sample to show "Dispose should work if called multiple times".  It's used sometimes in "real code" to save on work (e.g. if we're already disposed then don't bother cascade disposing, since they'll all no-op anyways), or to make a distinction between a not-yet (lazy) initialized state and a post-dispose state (which could both show some SafeHandle as being invalid).

Adding a public property implies there's an expectation that outside callers use that information, but that's not something we've seen be desired in practice.  (Even if there were a property, responsible tests would still want to check the functionality post-Dispose(), e.g. ObjectDisposedException... so a public property would actually increase the test burden, since it's "everything you already do" as well as "make sure the property says true now")

**Comment by tmaierhofer** [comment]
Thank you for Review. @IEvangelist - i refer to the _disposedValue field respectively a "IsDisposed" state. If the state is not stored at all like @sharwell proposed - which is totally perfect. Why is this not mentioned as a preferable alternative in the documentation? Why are the examples written in a way that some junior developer can come to the conclusion a _disposedValue is needed? 

If the state is needed, it should not be a private field, but a public property like IsDisposed {get; private set}.
It is also quite common that this property will be exposed in a lot of  implementations of the IDispoasble interface. Even a lot of .net framework classes expose it.

So from my point of view the documentation should mention that there is not only one "correct and clean" implementation and that the state tracking with a field is not mandatory. As i understood @sharwell it is most of the time not needed which is also my opinion. The documentation should mention that if it is needed a public property "IsDisposed" is the way to go, because of the reasons i have already mantioned.

**Comment by tmaierhofer** [comment]
@bartonjs - Thank yo for mentioning ObjectDisposedException. Intersting finding: The use of the "ObjectDisposedException" as precondition on calls to already disposed objects are also missing in the documentation. 

What is with objects that only expose the IDisposable interface itself - like a scope. You can call by definition the Dispose() method multiple times. How should some assert this?

**Comment by bartonjs** [comment]
> How would you design/assert this?

By having a test call Dispose multiple times and not observing anything untoward.  e.g. https://github.com/dotnet/runtime/blob/8fbf206d0e518b45ca855832e8bfb391afa85972/src/libraries/System.Security.Cryptography/tests/CryptoStream.cs#L207-L241 (a manual call to Dispose as well as an automatic one from the `using` statement).

**Comment by tmaierhofer** [comment]
@bartonjs - In fact you are asserting that Dispose() can be called multiple times and not that the object is really disposed. 
In the london school of TDD you receive probably Dispose() calls on members. 

The next thing is if you want to have  your public class interface with preconditions throwing ObjectDisposedException maintaining a IsDisposed state is mandantory - which goes in the opposite direction of the answer from @sharwell.

**Comment by IEvangelist** [comment]
Hi again @tmaierhofer 

> Why is this not mentioned as a preferable alternative in the documentation? Why are the examples written in a way that some junior developer can come to the conclusion a `_disposedValue` is needed?

Our documentation here follows the formal tooling suggestions. There are analyzers that generate various implementation details based on suggestions, this article strives to match those.

> It is also quite common that this property will be exposed in a lot of implementations of the `IDispoasble` interface. Even a lot of .net framework classes expose it.

I'm not seeing that, check out [this grep.app query](https://grep.app/search?q=public%20bool%20IsDisposed&filter[repo][0]=dotnet/runtime&filter[path][0]=src/libraries/), where only seven total non-test related references exist.

**Comment by tmaierhofer** [comment]
@IEvangelist - thank you for your Informations. 
Seems I had the wrong gut feeling about the amount of IsDisposed properties - shame on me for not checking it.

You gave @sharwell  a thumb up for not using _disposedValue at all.  You think this is the best way to do it, even when the documentation is different? You stated that the documentation follows the tooling suggestions like "resharper"? This is an important information for me, because I thought it is the other way around - so that you are providing a kind of "reference implementation".

**Comment by IEvangelist** [comment]
@tmaierhofer

There are certainly lots of opinions about how to handle this, lots of great examples of successful approaches. This content is based on a combination of both applied learnings and from the runtime team themselves. I'm going to close this, but if you have more questions or concerns, please continue to ask them. Thanks

**Comment by tmaierhofer** [comment]
@IEvangelist Thank you for your valuable input. I am fine with closing this issue right now. The important takeaways for me are:
* The authors are aware of other successful approaches and don't argue against them.
* The dotnet docs show not reference implementations but good common patterns
