### ISSUE TITLE
Missing explanation for RO member instead of constant for health check example

### ISSUE THREAD

**Issue by Eagle3386** [dotnet/docs#27747]
Besides missing some cleanup/refactoring towards .NET 6+ ("_Use the HealthChecks feature in your back-end ASP.NET microservices_" section states "_ASP.NET Core 3.1 Web API_", yet 2 paragraphs later also "_In .NET 6, with the built-in APIs_" & its example starts with `// Startup.cs from .NET 6 Web API sample`), the docs also might confuse people.

That's because the statement:
> It's important to keep your database queries efficient so that these operations are quick and don’t result in a higher utilization of resources.

follows right after a code snippet that instantiates a string member like this:
```csharp
private static readonly string DefaultTestQuery = "Select 1";
```
rather than declaring it as a constant like this:
```csharp
private const string DefaultTestQuery = "SELECT 1";
```

Please either add an explanation for why a read-only member ought to be preferred over a constant one - especially in the context of queries which shall execute as fast as possible - or change the declaration to represent a constant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98bdd99-d89d-8720-9018-25f73dcfdbd8
* Version Independent ID: 61a8ff5d-02ea-ec2b-2624-b8afa66f44d0
* Content: [Health monitoring](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/implement-resilient-applications/monitor-app-health.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Thank You for pointing this out. I have updated the version number and changed the variable to `const` in the attached PR.
