### ISSUE TITLE
Suggest to update multi-targeting guideline "AVOID multi-targeting ... if your source code is the same"

### ISSUE THREAD

**Issue by tsemer** [dotnet/docs#27769]
I'd like to offer a (seemingly common?) scenario where a suggested guideline is incorrect.

The full guideline text is:
> ❌ AVOID multi-targeting as well as targeting .NET Standard, if your source code is the same for all targets.

This guideline asserts that there is no added value for multi-targeting when source is the same. However, multi-targeting has additional implications for down-the-chain dependencies, and could cause breaking changes to consumers by forcing them to add/update NuGet packages or add binding redirects. In a large repo ecosystem that may be a considerable overhead.

The scenario I've encountered:

- A widely shared library is targeting .Net Framework (in my case, 4.72), and depends on the CLR library `System.ComponentModel.DataAnnotations`.
- My company would like to upgrade this library to target .Net Standard 2.0, so that its content can be (safely) used from new .Net Core / 5.0 / 6.0 applications.
  - Granted, it could alternatively be referenced as-is, but that is a riskier path which is not compile-safe and may fail at run-time.
- Running the portability analyzer discovers that the API surface is fully compatible, no code changes to be made.
- We follow the mentioned guideline since "code is the same", and re-target the library to .Net Standard 2.0, and drop the 4.72 target.
  - As a result, the dependency on the CLR's `System.ComponentModel.DataAnnotations` is replaced with a dependency on the package `System.ComponentModel.Annotations` (there is no other way to bring the underlying functionality to .Net Standard). Notice that they both contain the same namespace `System.ComponentModel.*Data*Annotations`, so even though a different assembly is referenced - there is no code change.

Observed results:
- One project depending on the upgraded library fails to compile because of assembly not found `System.ComponentModel.Annotations, Version=4.2.0.0`. I must admit, the reason for this is unclear to me.
- At runtime, a host of our .Net Framework services which depend (also transitively) on `System.ComponentModel.Annotations` encounter `FileLoadException`, failing to load `System.ComponentModel.Annotations, Version=4.2.0.0`.

Solutions:
1. A solution for compilation issues can be adding said package to dependent assemblies.
2. A solution for the runtime issues can be adding assembly binding redirects to the entry assemblies.
Both of these solutions require operations per consumer, so that qualifies as a "breaking change".

Two solutions I can come up with that ensure the library stays fully backward compatible with all consumers:

3. **Multi-target the library to `net472;netstandard2.0`** (against the recommended guideline).
4. Reference in the shared library an older package version of `System.ComponentModel.Annotations` which holds the exact same assembly version as the one in CLR 4.0, namely 4.2.0.0. For example, package version 4.4.0. For me this is not an option, since other dependencies force ">=5.0.0", which holds assembly version 4.2.1.0. Otherwise, I assume this could work but have no way to verify this at the moment.

Therefore, the only backward-compatible choice I can find is multi-targeting, which goes against the guidelines.

===

If you can find no flaw in my analysis, then in order to save others any unnecessary efforts I recommend to update the guideline. I'd be happy to think along on the best update, and I can think of 3 possible routes, depending on how common you think my scenario is for people reaching this page:
1. Add exception(s) to the current guideline, or split it to two guidelines based on scenario. Downside: This may become verbose / confusing.
2. Remove the guideline altogether. Downside: This may leave people unsure of when it is and isn't recommended.
3. Reverse the guideline to advise multi-targeting when attempting to preserve backward-compatibility. Downside: This may not fit all scenarios.

My own assumption is that a large amount of people searching for "multi-targeting" will be reaching this page with the scenario of upgrading an existing .Net Framework library to .Net Standard, since that is "the way forward". If you agree, then (3) may be a good choice.

Link to source:
https://github.com/dotnet/docs/blob/2ce4a5a6d6f9d90fd9efff0812ade29b3ac1a617/docs/standard/library-guidance/cross-platform-targeting.md?plain=1#L95

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/main/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by MSDN-WhiteKnight** [comment]
>Multi-target the library to net472;netstandard2.0 (against the recommended guideline).

If you are going to multi-target, you could also make the package reference conditional on .NET Standard only, as System.ComponentModel.DataAnnotations is inbox on .NET Framework. In this case your code would not be exactly the same on all platforms, although the difference is only in a single MSBuild item. So the guideline is not, strictly speaking, violated. We might want to clarify that multi-targeting is OK if there is a difference in build settings / dependencies, even if the code per se (in compilation units) is the same.

**Comment by tsemer** [comment]
@MSDN-WhiteKnight it is a possibility, but the only upside I can think to support it is that this solution would not, strictly speaking, violate the guidelines. The downsides are that the resulting csproj will be more complex, and the consistency between the framework target outputs will reduce. Assuming that under "best practices" we want to suggest solutions that result in clean, concise code and cohesive output, perhaps we should avoid suggesting that? Please correct if I am missing some benefit which makes this a desirable choice.
