### ISSUE TITLE
Error when following the Tutorial: Create an item template

### ISSUE THREAD

**Issue by rweritz** [dotnet/docs#27778]
When I follow the tutorial with dotnet version 6.0.100 and execute `dotnet new --install .\` I receive an error/output saying `No templates were found in the package D:\Code\dotnet-template-tutorial-part1\working\templates\extensions.`

Folder structure and `template.json`:
![image](https://user-images.githubusercontent.com/16781187/148642923-4fd476b8-3988-43a0-a13a-d053fd025fe8.png)

Terminal output:
![image](https://user-images.githubusercontent.com/16781187/148642908-50ffd08e-70a7-41c8-a0c8-424df50d7cc0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by awa5114** [comment]
What was the solution to this problem?

**Comment by adegeo** [comment]
@awa5114 Are you also having an issue?

**Comment by sharathgg5** [comment]
Facing same issue

**Comment by Vaccano** [comment]
It would be nice if there were additional output when this is the result.  

When I run `dotnet new --install ./` I clearly have a file in the the `.template.config` folder called `template.json`.  It would be helpful if it would say WHY it thinks there are no templates found.  (Where did it look?  Did it find any files?  What name was it expecting?  Was there a problem with the files it found?)  

Some kind of verbose option with this information would be fantastic!

**Comment by adegeo** [comment]
@Vaccano You'll need to file a request with the product team https://github.com/dotnet/sdk
