### ISSUE TITLE
Instructions do not work for .NET Core 5.0.4

### ISSUE THREAD

**Issue by skeeler** [dotnet/docs#27771]
I have .NET Core 5.0.4 runtimes (AspNet, NetCore, WindowsDesktopApp) installed and want to remove it. I have tried all of the guidance on this page, including using Windows App Uninstall, the dotnet-core-uninstall tool, and nothing works. 5.0.4 appears as installed when I run `dotnet --list-runtimes), but does not appear in the Windows app uninstall nor the dotnet-core-uninstall tool.

The guidance on this page should ideally be updated to reflect the instructions that will successfully remove .NET Core 5.0.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@skeeler Did you try using the .NET uninstall tool? https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows#net-uninstall-tool

**Comment by skeeler** [comment]
> @skeeler Did you try using the .NET uninstall tool? https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows#net-uninstall-tool

Yes, I tried the dotnet-core-uninstall tool, but it doesn't see 5.0.4 while `dotnet list` does display it. I'm trying to keep "3" and "6" and remove everything "5". See attacched screenshot
![screenshot](https://user-images.githubusercontent.com/755941/150616863-392f1af2-9bd2-471c-a79b-6a0c78d7fa74.png)
.

**Comment by adegeo** [comment]
I'm sorry for the delay @skeeler and for not fully reading your question where you said you did use the uninstall tool.

Can you output the results from `dotnet --info` it has more information about your environment. However, I feel like the uninstall tool is just not working well. I just tried it too and here are my outputs, which is missing .NET 6... The info doesn't seem to match. Looking at the uninstall tool repo, it seems the last update was at the beginning of Nov, which seems odd. I'll contact some folks to see if I can figure out what the prescribed path is.

**dotnet --info**
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**dotnet-core-uninstall list**
```

This tool cannot uninstall versions of the runtime or SDK that are 
    - SDKs installed using Visual Studio 2019 Update 3 or later.
    - SDKs and runtimes installed via zip/scripts.
    - Runtimes installed with SDKs (these should be removed by removing that SDK).
The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  5.0.405  x64    [Used by Visual Studio. Specify individually or use —-force to remove]
  3.1.416  x64

.NET Core Runtimes:

ASP.NET Core Runtimes:
  6.0.2  x86

.NET Core Runtime & Hosting Bundles:

```

**Comment by skeeler** [comment]
@adegeo here is the `dotnet --info` output:

    .NET SDK (reflecting any global.json):                                                             
     Version:   6.0.101                                                                                
     Commit:    ef49f6213a                                                                             
                                                                                                       
    Runtime Environment:                                                                               
     OS Name:     Windows                                                                              
     OS Version:  10.0.22000                                                                           
     OS Platform: Windows                                                                              
     RID:         win10-x64                                                                            
     Base Path:   C:\Program Files\dotnet\sdk\6.0.101\                                                 
                                                                                                       
    Host (useful for support):                                                                         
      Version: 6.0.1                                                                                   
      Commit:  3a25a7f1cc                                                                              
                                                                                                       
    .NET SDKs installed:                                                                               
      3.1.416 [C:\Program Files\dotnet\sdk]                                                            
      6.0.100 [C:\Program Files\dotnet\sdk]                                                            
      6.0.101 [C:\Program Files\dotnet\sdk]                                                            
                                                                                                       
    .NET runtimes installed:                                                                           
      Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
      Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]         
      Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
      Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]         
      Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]         
      Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]              
      Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]               
      Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]              
      Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]               
      Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]               
      Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 
      Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 
      Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 

    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download

**Comment by adegeo** [comment]
I'm going to close this because it's an issue for the product group to sort out. I created and linked to an issue over there ... almost 2 years ago :( hopefully it's gotten a bit better now.
