### ISSUE TITLE
The code is very outdated, used BeginInvoke instead of Task

### ISSUE THREAD

**Issue by YehudahA** [dotnet/docs#27782]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e33dad-b973-a334-e6d2-203472cb9aca
* Version Independent ID: 8a42e2e8-6617-74e0-81fc-009df48fff82
* Content: [Asynchronous Client Socket Example - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-client-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-client-socket-example.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/asynchronous-client-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by adegeo** [comment]
Hi! This was noted in another issue, I'll close this one as a duplicate.

**Comment by adegeo** [comment]
Duplicate of #26911
