### ISSUE TITLE
its awesome

### ISSUE THREAD

**Issue by saurabhprasadsah** [dotnet/docs#27788]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37ce5a16-aa17-7f0b-3a6f-aa00cb17949c
* Version Independent ID: d714c86e-bb00-a07d-eb7e-e3235acb1fb8
* Content: [Numbers in C# - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp?tutorial-step=7)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @saurabhprasadsah 

Closing as kudos.

**Comment by saurabhprasadsah** [comment]
okay @BillWagner
