### ISSUE TITLE
ShowPublicationInfo() method is missing "Console"  class for WriteLine method

### ISSUE THREAD

**Issue by smriti2901** [dotnet/docs#27793]
ShowPublicationInfo() method is missing "Console"  class for WriteLine method in code snippet to print Book Publication details.

Check below code snippet - 

 ```
public static void ShowPublicationInfo(Publication pub)
   {
       string pubDate = pub.GetPublicationDate();
       WriteLine($"{pub.Title}, " +
                 $"{(pubDate == "NYP" ? "Not Yet Published" : "published on " + pubDate):d} by {pub.Publisher}");
   }
```

Replace it with below code -

 ```
public static void ShowPublicationInfo(Publication pub)
   {
       string pubDate = pub.GetPublicationDate();
       Console.WriteLine($"{pub.Title}, " +
                 $"{(pubDate == "NYP" ? "Not Yet Published" : "published on " + pubDate):d} by {pub.Publisher}");
   }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d4fcf9-42c1-e015-798c-0c1519d77f41
* Version Independent ID: 75aee013-1123-1403-b2bc-cc8b68b56de8
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/inheritance)
* Content Source: [docs/csharp/fundamentals/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sputier** [comment]
The code sample includes a `using static System.Console;` statement, which allows using methods from the static `Console` class without using the qualified syntax. Therefore, it is legal to use this simplified call syntax for the `WriteLine` function.

However, every other samples in this page use the `Console.WriteLine` syntax. To improve consistency, it might be useful to change the `Write` and `WriteLine` calls to use the qualified syntax.

**Comment by BillWagner** [comment]
Hi :wave: @smriti2901 @sputier 

We've found several occurences where people miss the `static using` for examples when we show snippets of classes. When we show those, we've been using the class name. We should make the change @sputier recommends.

I've added the "up for grabs" label if anyone wants to make this change before we address it.

**Comment by sputier** [comment]
I'll create a PR in a few hours to fix this 👍
