### ISSUE TITLE
\w - "Matches any word character" - worthless!!

### ISSUE THREAD

**Issue by rsullyo** [dotnet/docs#27797]
I came to this page needing to know EXACTLY what \w means. The answer on this page? "matches any word character".  So not helpful!  Reading a few other websites helped me know that it should be equivalent to [A-Za-z0-9_].  Woah, and underscore too????
HHHHMMMMMM, I wonder if the .NET implementation of \w includes the underscore char???  Maybe this should be in the Microsoft documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gfoidl** [comment]
The page you read is the "Quick Reference". In the TOC on the left two sections below is "Character classes" which has [Word character: \w](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#word-character-w):

> `\w` matches any word character. A word character is a member of any of the Unicode categories listed in the following table.
> ...
> If ECMAScript-compliant behavior is specified, `\w` is equivalent to `[a-zA-Z_0-9]`. For information on ECMAScript regular expressions, see the "ECMAScript Matching Behavior" section in Regular Expression Options.

So the information is definitely there. The question is: if it's not obvious enough to find that info, do you have any idea how this can be improved?

**Comment by adegeo** [comment]
I think it would be quick and easy to just append something to the end of the description.
