### ISSUE TITLE
Typo in ECMA Standards doc

### ISSUE THREAD

**Issue by hfcook3** [dotnet/docs#27803]
Hey hey, the title in the ECMA Standards doc at docs/fundamentals/standards.md has a minor typo "tandards" instead of "standards". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa1a94b1-d1ef-e888-cdc0-57deff1cd1cc
* Version Independent ID: e515346f-0a4d-dcbf-66b9-01fac8d79391
* Content: [Ecma tandards for .NET - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/standards)
* Content Source: [docs/fundamentals/standards.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/standards.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for raising this @hfcook3 

I've opened a PR to address the issue.
