### ISSUE TITLE
mq4

### ISSUE THREAD

**Issue by Jay311031** [dotnet/docs#27811]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a152e46-0033-2d39-e870-7496167fd830
* Version Independent ID: 402fb037-a7f0-dfde-62c5-3d27bd84f369
* Content: [Compiler Error CS1931](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1931)
* Content Source: [docs/csharp/misc/cs1931.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1931.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋 @Jay311031 

Can you add details to this issue? Is there something we can help with?
