### ISSUE TITLE
Links to .NET standard specs are broken

### ISSUE THREAD

**Issue by zivkan** [dotnet/docs#27817]
The table that lists .NET standard versions and their compatibility with different runtimes makes the .NET Standard version number a link, for example pointing to https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md.

However, none of these links work, and the `dotnet/standard` repo was migrated and the master branch no longer contain a `docs` directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you @zivkan.
