### ISSUE TITLE
Update Runtime Directives (rd.xml) with new policies

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/docs#2781]
I believe there are new policies that can be fined inside a Runtime Directives file. E.g. BinaryFormatter for an Assembly/Type/...

@morganbr am I right? If yes, can you please update the docs with the new policies?

https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference

**Comment by morganbr** [comment]
The .NET Native 2.0 release will include a new BinaryFormatter directive, but it won't be released for a while longer. I'm not sure how coordination works for future releases like that.

**Comment by ViktorHofer** [comment]
ping @rpetrusha. opinions?

**Comment by morganbr** [comment]
The BinaryFormatter directive was released in October, so documenting it should be fine now.

**Comment by rpetrusha** [comment]
@ViktorHofer and @morganbr, yes, we should document it. I'll schedule some time for the next sprint, which begins next week. Is a spec or any other written description available?

**Comment by morganbr** [comment]
@rpetrusha, I don't think there's really anything written. The closest analogy is the Serialize directive, which enables reflection metadata used by reflection-based serializers, such as Json.NET. Like Json.NET, BinaryFormatter is reflection based, but using the BinaryFormatter directive enables the distinct set of reflection metadata that it requires: If a type has SerializableAttribute, then its fields' metadata get enabled (except for fields with NonSerializedAttribute) and the same behavior is applied recursively to the types of the fields. It also adds reflection for serialization callback methods.

**Comment by BillWagner** [comment]
Moving up to P1, as this has been re-scheduled several times.
