### ISSUE TITLE
JsonIgnoreCondition.WhenWritingNull is not work as my expect when Serialize a JsonDocument

### ISSUE THREAD

**Issue by bluetianx** [dotnet/docs#27824]
### Description

I Serialize a JsonDocument with setting JsonIgnoreCondition.WhenWritingNull ，but it not work,

SDK: net 6
OS: MacOS

### Reproduction Steps

This is my Demo Code

```C#
// See https://aka.ms/new-console-template for more information

using System.Text.Json;
using System.Text.Json.Serialization;


Person person = new Person();

var personJsonStr = System.Text.Json.JsonSerializer.Serialize(person);

Console.WriteLine(personJsonStr);

var jsonDocument = System.Text.Json.JsonSerializer.Deserialize<JsonDocument>(personJsonStr);

JsonSerializerOptions options = new JsonSerializerOptions()
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
};

var jsonStr = JsonSerializer.Serialize(jsonDocument, options);

Console.WriteLine(jsonStr);

public class Person
{
    public int Age { get; set; }
    
    public Address Address { get; set; }
}

public class Address
{
    public string Location { get; set; }
}
```

### Expected behavior

jsonStr does not contain null value,

### Actual behavior

jsonStr =>  "{\"Age\":0,\"Address\":null}"

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/runtime/issues/54184

**Comment by bluetianx** [comment]
ok，I understood

**Comment by layomia** [comment]
Re-opening so we can look into writing docs describing this behavior.

**Comment by reinux** [comment]
@layomia

> If JsonSerializer features are needed, please use a strongly typed target for serialization and deserialization.

To be honest, I don't know why I'm having trouble figuring this out, but for my sake, could you please elaborate or provide a one-line example?

**Comment by nelsontkq** [comment]
@reinux 

They're saying that you should use the type and not `JsonDocument` when you deserialize.

Instead of:
```csharp
var jsonDocument = JsonSerializer.Deserialize<JsonDocument>(str);
```
Do:
```csharp
var person = JsonSerializer.Deserialize<Person>(str);
```

For cases where you don't have the type at runtime
I haven't tested this but pretty sure if you pass the options to the `Serialize` method it will work:
```csharp
var options =  new JsonSerializerOptions
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
};
var jsonDocument = JsonSerializer.Deserialize<JsonDocument>(new object(), options);
```

**Comment by reinux** [comment]
Ahh got it, thanks!
