### ISSUE TITLE
seralize says it supports POCOs, this is not correct

### ISSUE THREAD

**Issue by pm100** [dotnet/docs#27826]
Serialize section lists support types, includes saying it supports POCOs (with surprisingly a link to wikipedia page). This is not so, it only supports objects that have setters and getters for its members. Plain public fields are not handled. Just spent a few happy hours trying to work out why this wasnt working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-6-0)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by IEvangelist** [comment]
Hi @pm100, I believe that the term POCO is in fact accurate. While WikiPedia is not always the best choice to link to, the term has been around for a very long time and within .NET it's been globally accepted as a term that is defined as an object which has properties with `get` and `set`.

Hey @tdykstra, I think for this one we should probably add POCO to the [.NET glossary](https://docs.microsoft.com/dotnet/standard/glossary) and make it official. We could then update all other references to the term's usage throughout docs, pointing to the new entry. Thoughts?

**Comment by tdykstra** [comment]
@IEvangelist Makes sense, please go ahead.

@pm100 Fields are supported -- there is an option and an attribute for that.  See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-6-0#include-fields
