### ISSUE TITLE
Wondering about the terminologies

### ISSUE THREAD

**Issue by leejoonhee-quriously** [dotnet/docs#27827]
[Enter feedback here]

Hello this is Marc.
I am really thank you this amazing doc.
But something is wondering.
As in described how important using word(fake, stub, mock), didn't use the world in example codes. 
But used 'result'. So I want to know about this meaning.
Because I am working on our company's test code guide sheet.
Thank you.
Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @leejoonhee-quriously, I'm not sure I follow your question. Are you asking why `result` for a variable name in a test is bad?

**Comment by leejoonhee-quriously** [comment]
@IEvangelist 
Thank you for your reply.
Not exactly same but almost. Let me explain it again. 
In this URL ( https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#lets-speak-the-same-language), explains and use 'mock', 'stub' variables in example code. And I figured it out that don't confuse 'mock' and 'stub'. Then I felt I should use these variables in test code. But in the Best Practice example code, don't have these variables.

I am just a Junior developer so please understand my lack
Thank you

**Comment by leejoonhee-quriously** [comment]
@IEvangelist I really thank you for your help. I understand what you are saying. Thank you again.
