### ISSUE TITLE
modernize completion for `bash`

### ISSUE THREAD

**Issue by gaelicWizard** [dotnet/docs#27828]
I would suggest a slightly more modern formulation for the completion:
```bash
function _dotnet_bash_complete()
{
  local cur="${COMP_WORDS[COMP_CWORD]}" IFS=$'\n'
  local candidates

  read -d '' -ra candidates < <(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)

  read -d '' -ra COMPREPLY < <(compgen -W "${candidates[*]:-}" -- "$cur")
}
```

This uses a more familiar convention to many programmable completion functions for _Bash_, is more idiomatic _Bash_, and avoids unexpected word-splitting by being explicit about it: use `read -ra` to populate the array parameter, with `IFS=$'\n'` and `-d ''`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#bash)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
