### ISSUE TITLE
Expand the table to make it obvious which netstandard is implement in .net5/6

### ISSUE THREAD

**Issue by kMutagene** [dotnet/docs#27833]
It kind of stays up for interpretation which versions are compatible/implemented in .NET5/6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by kMutagene** [comment]
@IEvangelist oh wow that is so much better, thanks!

**Comment by IEvangelist** [comment]
Ah, I actually overlooked this initially too @kMutagene - but this table is in fact accurate as is. If you read it a bit more closely, you'll see that beneath the table the bulleted list describes that each corresponding .NET implementation is the minimum version supported, so there is implicit support.

> The version number in each cell indicates the *minimum* version of the implementation you'll need in order to target that .NET Standard version.
