### ISSUE TITLE
Example not accepted by Visual Studio 2019

### ISSUE THREAD

**Issue by MichaelBrooks-Version1** [dotnet/docs#27831]
When I try updating my code in line with this example. Visual Studio highlights the subpet?. bit with the message "CS8072: An expression tree lambda may not contain a null propagating operator.". If LINQ does not allow this, why are you showing it in your example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d433265d-15f4-bd2e-a3d1-8148a3968783
* Version Independent ID: 75d2c893-1d07-f836-62f1-e767edfcebac
* Content: [Perform left outer joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins)
* Content Source: [docs/csharp/linq/perform-left-outer-joins.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/perform-left-outer-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @MichaelBrooks-Version1,

What version of C# and .NET are you using? This does work as it is valid, [see here for example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyUBuauxsgOgBkBLPAEc2VdmSSMU9HjABmGAPI4MMKACkIAgKIIAhgFsADgBsYACgCU1AN7V69+gAVVAZwh56+3QHM8OF/QAvPR4MADuTq7u9Nb0AGJ8UC4YAHIGMEH0AEQAsj5+Lllo0rrJafoZwVkAEjAAJsb4dVn0AL4iDpFJ0SpQUACemaERzt0esQlJqemZWQAqqgNFJWUzVQCCdQaFbR0Oo24eYAAWulDGEBgqQ+FdhzHxiasVswDCp+eXKss8pdMvVQA6jA+C4du07Psoh4zqZQjcRtCHpNnpVsutzjBQj8/uU0TUcLJZC0IaIqJ1nBh6MBYTBBsFhpEqbE8bMAEK0/rLBRhUJQTK9Aa7SH2SnUiCXAIM25illrbJsiUYQrFHl8gWLQakikwKlhY6ggDWrgRTIerKBBpcxqS3N5qkyJ1hXwy2qhVOAjRg+glHmliOZ9AtCq99Byvrt6uCgq1e1FuvoW1B9JCMoTcoB2QAIrpk5GHcEvL5/MKyZ0APTl+ivWC6a4YMIQejGUHKrgi6StgA8B3cAD56IYYBATGjGfxkj3oQPYkWCsUY8UnZ8rjBirT4W77BOMFOMAOh8rTTu9zPqZzisAlS5ivqja5L16fe5ikmXLHqB2AG5neiCHCqCmshQBA+iDkiAjgSOpgdp0cEOAAVpoHiHvQkGHgE0RDmM9AwP+ujGAEh5cGqDoCBgTbeAhsHwXBwGgfQLg4MAqGQVRXBZnIug4MYGAAJKyFoRgYP0lg0bRDguDAphgFSjKxNhhxcCi/xrkywZMSxuoAPxcKy2nafQADKGBQAI3hcEJhgiaWHayNAMC6Cc9BmD+/JfmhHj/oBVjkg4th+fBTAAJxmAAJFk1hfspTyqQA1FkIBFHAZAAKytFFXCUnirRZBYcZtNQrSfjQJB3O4NgdkQADMnAMCprKxN4uosIxLWFYFjC1UwDC/KiDzNRgrVSUNHXFWSpBMpVnU1XVQYzE17Uja142dLNvYeKR/KLaNy1jUAA).

**Comment by MichaelBrooks-Version1** [comment]
Thanks for replying David. OK, I'm using VS2019 against a .Net Framework 4.7.2 project, which I understand (and I'm quite willing to be corrected here) should mean that it's C# 7.3.

Regards,
Michael

**Comment by IEvangelist** [comment]
Hi again @MichaelBrooks-Version1,

Are you able to share the project with the minimal viable amount of code that reproduces this issue?

**Comment by MichaelBrooks-Version1** [comment]
@IEvangelist: Thanks David; let me come back to you on that - it's been a couple of weeks since I was looking at that project and I'm spinning plates here, so I'll need to get back in the zone on that one, but it does still need to be addressed, so I appreciate your help.

**Comment by svick** [comment]
The error message indicates that you're using LINQ over `IQueryable<T>`, not over `IEnumerable<T>`.

For example, the code as written compiles fine:

```c#
List<Person> people = new List<Person> { magnus, terry, charlotte, arlene };
List<Pet> pets = new List<Pet> { barley, boots, whiskers, bluemoon, daisy };

var query = from person in people
            join pet in pets on person equals pet.Owner into gj
            from subpet in gj.DefaultIfEmpty()
            select new { person.FirstName, PetName = subpet?.Name ?? String.Empty };
```

But if you change it to use `IQueryable<T>`, you get the reported error:

```c#
var query = from person in people.AsQueryable()
            join pet in pets on person equals pet.Owner into gj
            from subpet in gj.DefaultIfEmpty()
            select new { person.FirstName, PetName = subpet?.Name ?? String.Empty };
```

The same would happen if `people` was not a `List<T>`, but a database data source (like EF `DbSet<T>`).

Since joins are commonly used with databases, maybe this article shouldn't use the `?.` operator in the first place? Or if it does, maybe it should explain that the operator cannot be used for joins with databases?

**Comment by MichaelBrooks-Version1** [comment]
Thanks @svick - I think you have hit the nail on the head. I am indeed using this with a database query; I was not aware that database queries are not enumerable - I blindly assumed that all LINQ queries are equivalent. I'm sure that is obvious to anyone who is well versed in LINQ to SQL, but it is indeed confusing for those of us who do not know these nuances.
