### ISSUE TITLE
Does not install application as indicated in this tutorial

### ISSUE THREAD

**Issue by farazmohammed** [dotnet/docs#27846]
[Enter feedback here]
Almost same problem described in the post below in 2018 and no response yet.
What could we be doing wrong? the application is installed in profile\temp\data\... folder and 
https://social.msdn.microsoft.com/Forums/windows/en-US/74f22f0f-de44-47b2-9a88-42e82adb249e/how-to-publish-c-console-application-in-vs-2017?forum=winformssetup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449b8ce2-80b3-9bfa-6d7f-3e8ac8a86e16
* Version Independent ID: 31264b07-1aeb-b3f0-1126-f25e578f6d50
* Content: [Publish a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio?pivots=dotnet-6-0)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/publishing-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
It sounds like you're going beyond the scope of the tutorial -- in which step do the instructions not work as described? The tutorial doesn't publish to profile/temp/data, it publishes a console app to projectfolder/bin/Release/net6.0/publish. You can copy the contents of the publish folder somewhere else and run the app there. The console app doesn't need an install process.

**Comment by farazmohammed** [comment]
After publish, it creates a setup.exe and a folder "Application Files" which has a bunch of files with extension .deploy.
When a user executes the setup.exe, it displays a few screens indicating it is downloading and then runs the application - but the application is deployed in profile\temp\data\... folder.
My expectation when I ship a setup.exe to the user is that it will install the necessary files in a pre defined folder(just as msi installer used to do). 
This doesn't do that, what is the intent of this setup.exe that's created by publish?

**Comment by tdykstra** [comment]
In steps 5 and 6 in the Publish the app section it has you select the Folder target, and in step 7 it has you accept the default target of bin/Release/net6.0/publish. Are you making different choices in these steps of the tutorial?

**Comment by farazmohammed** [comment]
yes sir, I specify the location to publish the application(see screenshot), but all it does is create the setup.exe at that location.
The next screen "How will users install the application" and the path specified in "From a UNC path or file share" seems completely ignored by the process as nothing is created there.
When I install, its always installed in the Appdata\temp folder never to be seen again. If i run the setup.exe again, it installs it again - but I never get to see where it installed the file and doesn't see the local log file that I write in the application
Its beyond me why setup would install something in a temp folder - is this how this is supposed to run? When I run the setup.exe, I expect it to be installed at a certain(not temp) directory, and not to install it in temp and execute it each time.
![image](https://user-images.githubusercontent.com/59148503/149555456-6fd9a551-2867-4883-80dc-88d61b88ef87.png)

**Comment by farazmohammed** [comment]
This is still a console app, but not using the preceding example. Any reason why publishing for a different console app would be drastically different? It's still a console app and creates a .exe file that needs to be packaged into a setup.exe that will install all components into a defined folder?
IF this is not the way to publish, can you point me to a better way so it behaves as I expect it to?

**Comment by tdykstra** [comment]
What is in your .csproj file?

**Comment by farazmohammed** [comment]
its a .net 5 console app with entity framework and some nuget packages. what other way do you recommend to create an install file for customers

**Comment by tdykstra** [comment]
If it's a console app you should be able to copy the publish folder to the machine you want to run it on and run it there.  This tutorial doesn't create an install file. You might find help for that by submitting a question on StackOverflow.

**Comment by farazmohammed** [comment]
the publish feature is creating the setup.exe file, I think I need to understand what publish can and can't do, this was the first link that come up in searches for "how to publish console app using visual studio". Do you have a better msdn link that describes this.
I really loved the setup project and MSI installer that came with VS 2008. It is deprecated now but not sure what it is replaced by

**Comment by tdykstra** [comment]
The best documentation we have currently on deployment options is here: https://docs.microsoft.com/en-us/dotnet/core/deploying/
