### ISSUE TITLE
Disclose dotnet list package `--vulnerable` source

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#27848]
What is `--vulnerable` sourced from?

This is important to evaluate what this may list and catch, and what it will not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8400fd6a-d987-1056-283f-9364fbce3c86
* Version Independent ID: 3d4b052c-33fa-cc83-4df6-4a3341f12763
* Content: [dotnet list package command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package)
* Content Source: [docs/core/tools/dotnet-list-package.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-list-package.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@nkolev92  can you help with this question?

**Comment by nkolev92** [comment]
dotnet list package sources vulnerabilities from the configured sources, https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#vulnerabilities. 

At this point, nuget.org is the only known source that reports vulnerabilities and this doc contains a more detailed explanation https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/

**Comment by tdykstra** [comment]
Thanks @nkolev92 ! I'll update the article.
