### ISSUE TITLE
CA2254 404 Not Found

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#27857]
---
**Issue moved from MicrosoftDocs/feedback#3740**
- Please respond to @pcartwright81.

---

_From @pcartwright81 on Sunday, January 2, 2022 3:30:58 PM_

**Describe the bug**
CA2254 404 Not Found

**To Reproduce**
1. Have VS get a CA2254 message.
2. Click on CA2254

**Expected behavior**
Navigate to a page that works.

**Screenshots**
![image](https://user-images.githubusercontent.com/2352477/147880646-694c9447-e3fc-4296-99de-210f29bc4f28.png)
![image](https://user-images.githubusercontent.com/2352477/147880677-4ec7dae2-dc30-411d-867b-1789d8794f3a.png)

**Desktop (please complete the following information):**
All

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3740**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Sunday, January 2, 2022 3:30:59 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Youssef1313** [comment]
Also tracked in https://github.com/dotnet/docs/issues/23900
