### ISSUE TITLE
Code samples seem to be wrong

### ISSUE THREAD

**Issue by Jamminroot** [dotnet/docs#27863]
Code examples on the pages seem to be irrelevant to the contents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d03435-cc6c-1123-a86c-d5c3eacc24bd
* Version Independent ID: 460afd2b-383d-7b90-6804-4b900c3bc9b2
* Content: [Tutorial: Forecast bike rental demand - time series - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting)
* Content Source: [docs/machine-learning/tutorials/time-series-demand-forecasting.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/time-series-demand-forecasting.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @Jamminroot thanks for raising this issue. Updates have been made in #28516 and the changes should be reflected shortly.

**Comment by luisquintanilla** [comment]
Fixed by #28516
