### ISSUE TITLE
It is slightly difficult

### ISSUE THREAD

**Issue by Abduhakimbek** [dotnet/docs#27873]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495dca2a-dcd9-892f-21f0-e970589b543d
* Version Independent ID: 159fb3e3-66b4-6cdc-f921-4406447b98ca
* Content: [Delegates with Named vs. Anonymous Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods)
* Content Source: [docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this @Abduhakimbek 

I've added this to our list to address as we update this section.
