### ISSUE TITLE
SARIF version in C# compiler ErrorLog property

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#27872]
Please document how to specify the version of the SARIF format as part of the ErrorLog property used by the C# compiler. This feature was added in <https://github.com/dotnet/roslyn/pull/37148>.

```XML
<ErrorLog>log21.json,version=2.1</ErrorLog>
```

The compiler accepts either a comma or a semicolon as the separator between the file name and `version`, but its `--help` output uses a comma.

If the ErrorLog property is set in the `dotnet build` command line, then the comma (or semicolon) must be percent-encoded as in `dotnet build -p:ErrorLog=logcmd.json%2Cversion=2.1`, to prevent the `-p` option from treating `version` as the name of a separate property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#errorlog)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to my attention @KalleOlaviNiemitalo 

I've added it to our backlog to address when I next update this page.

**Comment by fdw** [comment]
It's actually still not in the documentation: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#errorlog

**Comment by KalleOlaviNiemitalo** [comment]
@fdw what do you mean?  At <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#errorlog>, there is text:

> You can specify the SARIF format using the `version` argument to the `ErrorLog` element: […]

**Comment by fdw** [comment]
Yes, but it doesn't describe the percent-encoding one needs to do to pass it on the CLI. I only found the solution thanks to your original ticket.
