### ISSUE TITLE
Documentation does not explain why assigning an array to an array gets CS0229

### ISSUE THREAD

**Issue by lvskiprof** [dotnet/docs#27889]
Your example does not explain why this code is getting a CS0229 error:

public class Card : MonoBehaviour
{
    public enum suit
	{
        CLUB,
        DIAMOND,
        HEART,
        SPADE
	};
    private Sprite[][] cardFaces = new Sprite[4][];    // Two dimensional matrix. 1st index is suit, 2nd is card type
    [SerializeField]
    static Sprite[] cardBacks;      // Array of card backs
    [SerializeField]
    private Sprite[] clubCardImages;
    [SerializeField]
    private Sprite[] diamondCardImages;
    [SerializeField]
    private Sprite[] heartCardImages;
    [SerializeField]
    private Sprite[] spadeCardImages;

    // Start is called before the first frame update
    void Start()
    {
		// Fill the cardFaces matrix with card sprite images.
		for (int i = CLUB; i <= SPADE; i++)
        {   // Loop through all the suits
            switch (i)
            {
                case CLUB:
					cardFaces[i] = clubCardImages; // CS0229
                    break;

                case DIAMOND:
                    cardFaces[i] = diamondCardImages; // CS0229
                    break;

                case HEART:
                    cardFaces[i] = heartCardImages; // CS0229
                    break;

                case SPADE:
                    cardFaces[i] = spadeCardImages; // CS0229
                    break;
            }   // switch()
        }   // For i
    }   // Start()
}    // class Card

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396c23ca-a799-032b-527b-d9362e44b514
* Version Independent ID: 884704df-8e4c-2dde-8c2d-96287f8d673d
* Content: [Compiler Error CS0229](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0229)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0229.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0229.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋 @lvskiprof 

I can't see what would cause the reported error in the sample you've posted. I tried to reproduce it, but I can't without the definition for `Sprite` and `MonoBehaviour`. (When I stub those out with empty definitions, the compiler doesn't produce an error.)

Can you add further details to help us find this?
