### ISSUE TITLE
Following the instructions gives me different results. 

### ISSUE THREAD

**Issue by jimmythecode** [dotnet/docs#27896]
1. Using `dotenv new console` doesn't create a file with the results that follow the article text: "... Open Program.cs. It should look like this:"
2. Following the instruction: "Create a new file using the File:New command. Name it BankAccount.cs. Add the following code to your BankAccount.cs file:" creates a file but not in the same directory. Where should we save it?
3. When pasting the code into `Program.cs` I get an error line under `BankAccount` in this line: `var account = new BankAccount("jimmy", 1000);`. The error reads: `CS0246	The type or namespace name 'BankAccount' could not be found (are you missing a using directive or an assembly reference?)`

These are trivial issues if you've some coding experience, but these are aimed at beginners so I would imagine are unusable for many new-starters

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - C# Fundamentals tutorial](https://docs.microsoft.com/en-gb/dotnet/csharp/fundamentals/tutorials/classes)
* Content Source: [docs/csharp/fundamentals/tutorials/classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @jimmythecode 

This tutorial needs to be updated for the changes added in C# 11. I've added it to the current sprint.
