### ISSUE TITLE
How is the logger resolved when the method does not provide it as shown in example

### ISSUE THREAD

**Issue by suryapratap** [dotnet/docs#27897]
[Enter feedback here]
```c#

public partial class LoggingSample
{
    private readonly ILogger _logger;

    public LoggingSample(ILogger logger)
    {
        _logger = logger;
    }

    [LoggerMessage(
        EventId = 20,
        Level = LogLevel.Critical,
        Message = "Value is {value:E}")]
    public static partial void UsingFormatSpecifier(
        ILogger logger, double value);

    [LoggerMessage(
        EventId = 9,
        Level = LogLevel.Trace,
        Message = "Fixed message",
        EventName = "CustomEventName")]
    public partial void LogWithCustomEventName();

    [LoggerMessage(
        EventId = 10,
        Message = "Welcome to {city} {province}!")]
    public partial void LogWithDynamicLogLevel(
        string city, LogLevel level, string province);

    public void TestLogging()
    {
        LogWithCustomEventName();

        LogWithDynamicLogLevel("Vancouver", LogLevel.Warning, "BC");
        LogWithDynamicLogLevel("Vancouver", LogLevel.Information, "BC");

        UsingFormatSpecifier(logger, 12345.6789);
    }
}


```

In the above sample shown   ```LogWithCustomEventName``` &  ```LogWithDynamicLogLevel``` partial methods do not take an ```ILogger``` parameter, so how is the logger resolved in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc4ecf0-19e4-54d3-c34e-b6eadb80262b
* Version Independent ID: decc74aa-a2d5-8727-f22b-3862bacde737
* Content: [Compile-time logging source generation](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator#log-method-anatomy)
* Content Source: [docs/core/extensions/logger-message-generator.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logger-message-generator.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @maryamariyan
* Microsoft Alias: **maariyan**

**Comment by gewarren** [comment]
@suryapratap Those two methods are instance methods. In this context, the logging methods get the logger by accessing the ILogger field in the containing class.
