### ISSUE TITLE
Add exception callbacks as releated pages

### ISSUE THREAD

**Issue by Suisse00** [dotnet/docs#27905]
Hi,

It may need some discussion about what pages may contain such link but; I think pages that talk about how to handle exception in C# (like the releated content page in this issue) should also link to pages like [AppDomain.FirstChanceException](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception?view=net-6.0) or [AppDomain.UnhandledException](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=net-6.0).
Maybe in the see also part.

Giving that trying to search for catch handler (or similar keywords) usually end up on the try-catch and nowhere close to those two callbacks, it may add a nice visibility to those two callbacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Suisse00 

That's a great suggestion. We'll add that.

I've added the "up for grabs" label as well, if anyone wants to submit a PR before we make that update.
