### ISSUE TITLE
Install instructions on many linux distros may need to be updated.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/docs#2790]
With the update from preview 2 to preview 3, the install instructions shown https://www.microsoft.com/net/core/preview#linuxdebian may not work on preview 3. The issue is when running dotnet new, the first time experience may not run because dotnet will not have write permissions to the folder where it is instructed to run. I tested this on Fedora and Debian and both of these failed to perform the first time experience. The fix may involve install dotnet somewhere in ~/ and linking the command from there. I would also recommend testing each of the commands above, accounting for changes in preview3.

**Comment by mairaw** [comment]
@leecow @richlander can you guys comment on this?

**Comment by leecow** [comment]
Thanks @jkotalik and @mairaw - We're talking through options now and will make updates to the instructions soon.

**Comment by jkotalik** [comment]
Here is a link to the issue on the CLI repo. https://github.com/dotnet/cli/issues/7203. The issue was taken offline after the initial discussion. This behavior was changed form preview2 to preview3.

**Comment by leecow** [comment]
Understood, thanks again!

**Comment by mairaw** [comment]
This issue is now outdated. Instructions are not under https://www.microsoft.com/net/learn/get-started/linuxdebian.
