### ISSUE TITLE
Missing: Breaking Change: Default console logger format set to JSON

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#27906]
https://github.com/dotnet/dotnet-docker/issues/3274 isn't listed here.
See https://github.com/dotnet/AspNetCore.Docs/issues/24687

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a07a4a03-5b9a-0360-7c78-14284b1cb029
* Version Independent ID: 0ea0a42e-2169-349b-e2e8-fb01ff4874ba
* Content: [Breaking changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0)
* Content Source: [docs/core/compatibility/6.0.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/6.0.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I'm not sure that we document docker image breaking changes here. It looks like they do that in their [release notes](https://github.com/dotnet/dotnet-docker/issues/3276). @PriyaPurkayastha can you confirm?

**Comment by PriyaPurkayastha** [comment]
> I'm not sure that we document docker image breaking changes here. It looks like they do that in their [release notes](https://github.com/dotnet/dotnet-docker/issues/3276). @PriyaPurkayastha can you confirm?

We don't have any principle as such for docker image breaking changes but it does appear that they track those as part of their release notes.

**Comment by gewarren** [comment]
Okay, I'm going to close this issue.
