### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by davepend** [dotnet/docs#27902]
The AsyncBreakfast namespace requires the following declarations to work:

```	class Coffee { };
	class Egg { };
	class Bacon { };
	class Toast { };
	class Juice { };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/?source=docs)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @davepend 

We'll take a look at this.  When I wrote the sample, I left those definitions out of the included code for brevity. There is a note explaining it. We'll update that.

**Comment by SeanKilleen** [comment]
I attempted this over in #29790. Feedback welcome!
