### ISSUE TITLE
NRT migration docs mention incorrect C# preprocessor directive

### ISSUE THREAD

**Issue by Tankzor** [dotnet/docs#27911]
Document mentions `#pragma nullable disable` in the section "Plan your migration" ( https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#plan-your-migration ), we tried this, doesn't work. Then realised this is probably an incorrect compiler directive and it should be `#nullable disable` ? (ref: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#nullable-context )

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc516159-d7e1-46ba-7d31-538a0b811491
* Version Independent ID: 99552131-8839-7c22-fcdc-2baa7722e756
* Content: [Update your codebase to use nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies)
* Content Source: [docs/csharp/nullable-migration-strategies.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-migration-strategies.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @Tankzor 

I've opened #27917 to address this issue.
