### ISSUE TITLE
b

### ISSUE THREAD

**Issue by mohamedy7** [dotnet/docs#27929]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f98776d-66cc-91ad-697a-783f80914f9c
* Version Independent ID: 66121850-861c-9e37-27f0-811f80427d70
* Content: [Compiler Error CS1503](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503))
* Content Source: [docs/csharp/misc/cs1503.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi :wave: @mohamedy7 

It looks like this issue was opened by mistake. I'll close it.
