### ISSUE TITLE
Warning level documentation is outdated

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#27927]
> Any value greater than 5 will be treated as 5. To make sure you always have all warnings if the compiler is updated with new warning levels, put an arbitrary large value (for example, 9999).

This is not correct. We have warning level 7 now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warninglevel)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I also think it might be possible for third-party analyzers to specify a specific warning level, so pretty much any value can have an effect, even if it's not common.

**Comment by BillWagner** [comment]
Thanks @Youssef1313 

I've added this to our list.

(I know I keep saying that in this area. I think I'll finally get time to spend on the compiler diagnostics over the next few months.)

**Comment by cremor** [comment]
The link on "additional warnings" should also be updated to point to the current version of the file.
