### ISSUE TITLE
404 when trying to install .NET 3.1 on Amazon Linux 2

### ISSUE THREAD

**Issue by imryano** [dotnet/docs#27931]
Hi there,

I'm attempting to install .NET 3.1 on an AWS Amazon Linux 2 machine (_yum -y install dotnet-sdk-3.1_), and am getting a 404 error while accessing the below:

packages.microsoft.com/rhel/7/prod/dotnet-runtime-deps-3.1.22-centos.7-x64.rpm 

Seems like this should be one of these:
packages.microsoft.com/rhel/7/prod/dotnet-runtime-deps-3.1.22-**rhel**.7-x64.rpm 
packages.microsoft.com/**centos**/7/prod/dotnet-runtime-deps-3.1.22-centos.7-x64.rpm 

I would assume the latter as I have added the below to my rpm:
https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

The same issue arises with the runtime, but I'm assuming they're both using the same dependency package.
I have worked around it by performing the following before installing the SDK:
_yum -y install https://packages.microsoft.com/centos/7/prod/dotnet-runtime-deps-3.1.22-centos.7-x64.rpm_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577ce9b2-5b48-4ed2-c309-a78880015dd2
* Version Independent ID: 26300783-8df5-56a1-4ab6-4b8511e37f51
* Content: [Install .NET on CentOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos)
* Content Source: [docs/core/install/linux-centos.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-centos.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Package manager installs are only supported for a small set of distros. I've not been told that Amazon Linux 2 is among them. You would need to use a manual install. This article is describing using CentOS so I'm not sure how you have some wires crossed with RHEL packages and CentOS repos etc 😁

**Comment by imryano** [comment]
The pair of commands that got me there was this:

yum -y install https://packages.microsoft.com/centos/7/prod/dotnet-runtime-deps-3.1.22-centos.7-x64.rpm
yum -y install dotnet-sdk-3.1

Sorry, my knowledge of Linux distros is limited, and the issue may just be caused by AMI2 (it seems like it lives somewhere in the middle of the two of them). 

Just wanted to make sure the dotnet-sdk-3.1 dependencies weren't the problem! Will close this off, thanks for checking it out.
