### ISSUE TITLE
Manual install has bad path

### ISSUE THREAD

**Issue by dvescovi1** [dotnet/docs#27937]
Under the manual install Bash commands the wrong DOTNET_ROOT path is given.
it shows:

`export  DOTNET_ROOT=$(pwd)/dotnet`

it should be:

`export  DOTNET_ROOT=$(pwd)/.dotnet`

as later on the Bash profile is modified to `$HOME/.dotnet`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Manually install .NET on Linux - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
