### ISSUE TITLE
Templates for GitHub Actions

### ISSUE THREAD

**Issue by rahul-kumar2** [dotnet/docs#27940]
[Documentation says we have templates feature available in GitHub action similar to what we have in azure DevOps template but I did not find any documentation where I can do this like Define reusable, parameterized building blocks for steps, jobs, or variables. Can any one comment on this ? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea049336-6c09-1791-a102-cede5fa3ebff
* Version Independent ID: 36ffb095-5a05-8516-ab25-1120b3c22979
* Content: [DevOps with .NET and GitHub Actions - Compare GitHub Actions with Azure Pipelines](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-vs-pipelines)
* Content Source: [docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md)
* Product: **dotnet-architecture**
* GitHub Login: @colindembovsky
* Microsoft Alias: **nanil**

**Comment by colindembovsky** [comment]
@rahul-kumar2 In GitHub Actions, templates are "starter templates" that give you some workflow yml based on a high-level analysis of the repo. For example, if there is a Dockerfile, then a template with steps to run `docker build` are suggested. If there is a `package.json` file, a workflow with steps to `npm install` and `npm build` are suggested.

The closest equivalents in GitHub Actions to Azure Pipeline Templates are [Reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) and [Composite Actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). Reusable Workflows are similar to Job Templates, while Composite Workflows are similar to Step Templates.

**Comment by IEvangelist** [comment]
Hi @rahul-kumar2,

Did @colindembovsky answer all your questions? If so, let's close this issue.

**Comment by rahul-kumar2** [comment]
Yes, we can close this although the documentation is a little confusing if we say we have exactly mirror image available in GitHub action but yes on the closest equivalent I agree.
![image](https://user-images.githubusercontent.com/85479631/151293131-30e6e08d-d977-4474-b55f-ba0be6171d19.png)
