### ISSUE TITLE
Pattern matching appears to be introduced in C= 9.0, not C#7.0

### ISSUE THREAD

**Issue by abdekker** [dotnet/docs#27951]
The document (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements) includes the line: "The switch statement supports pattern matching beginning with C# 7.0."

Using Visual Studio 2019 Professional and a C# .NET Framework console application. Targeted at .NET 4.7.2 (C# 7.3).

int age = 25;
Console.Write("  Your age is {0}...", age);
switch (age)
 {
     case < 17:
         Console.WriteLine("not old enough to drink alcohol");
         break;
}

The "case < 17:" line generates the error:
"CS8370 - Feature 'relational pattern' is not available in C# 7.3. Please use language version 9.0 or greater."

Either I have misunderstood something, or the article contains inaccurate information.

BTW, this developer thinks these patterns (<, <=, etc) are less readable in switch/case statements. Moreover, this breaks historical conformance with C/C++. I think they're not a great idea...

Thanks,
Alain

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d77f4b78-a6eb-a71c-318f-5059ce12cb6c
* Version Independent ID: 6aec8c74-40c9-ce6b-7554-d1e4b241f061
* Content: [Selection statements - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(switch_CSharpKeyword);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.5);k(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/statements/selection-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/selection-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @abdekker 

While the language reference generally assumes the latest version (currently C# 10), we should be more explicit with features like pattern matching. Pattern matching was first introduced in C# 7, and has been enhanced with new capabilities in each subsequent release. This page should cover all the capabilities in the current release, but should note when different capabilities are added.

**Comment by pkulikov** [comment]
> This page should cover all the capabilities in the current release, but should note when different capabilities are added

@BillWagner the referenced article contains (1) the link to the patterns overview page and (2) links to the used patterns. I think that's enough. Maybe worth to mention the language version in which used patterns have been introduced? What do you think?

**Comment by BillWagner** [comment]
@pkulikov 

> Maybe worth to mention the language version in which used patterns have been introduced?

Yes, that's exactly what I was thinking.

**Comment by abdekker** [comment]
When does the updated documentation get pushed out, BTW?

**Comment by BillWagner** [comment]
@abdekker We publish daily, with the build running overnight. By tomorrow morning (EST) it will be live.
