### ISSUE TITLE
Unnecessary complexity in code example introducing default interface methods

### ISSUE THREAD

**Issue by techfan101** [dotnet/docs#27979]
This page is supposed to provide a simple example using default interface methods.  The addition of asynchronous methods and tasks into that example introduces unnecessary complexity.  Neither of these concepts is required to demonstrate default interface methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8d9be-958f-d92a-77f5-c105fa307c93
* Version Independent ID: 0974453c-bf3d-37ed-a965-c4178f3be945
* Content: [Create mixin types using default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/mixins-with-default-interface-methods)
* Content Source: [docs/csharp/whats-new/tutorials/mixins-with-default-interface-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/mixins-with-default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @techfan101 

I understand your point on this, but I disagree. The `async` and `await` features have been part of the language and the framework for many years. I'd make the point that `async`, `await`, and `Task` are now part of the standard vocabulary for C#.

I'll close this without action.

**Comment by techfan101** [comment]
The page provided a feedback button. I saw a place where improvements were possible.  I shared the feedback.  It's as simple as that.  Given the summary dismissal of the feedback, I don't think I'll be in a hurry to do so in the future.

Since I've already spent time on this one, I'll clarify before moving on.

First, to the implication that I might not have kept pace with the language. I've been programming C# continuously since 2003 and enjoyed watching the language evolve over the years.  I've used asynchronous tasks in projects too numerous to mention.  I was writing multi-threaded code long before that.  I won't mention how long.  Let's just say dinosaurs still roamed the Earth :)

However, good code examples generally use as few types/methods/features as necessary to demonstrate a topic.  With this example, that is certainly not the case.  My feedback is not limited to the inclusion of tasks, I'd have the same concern with the inclusion of even older types like dictionaries or hash sets.  They are simply not necessary to demonstrate the concept.

That said, based on my own experience mentoring and managing new developers, I can assure you that a depressingly large number of them still struggle with the concepts of asynchronicity. If you need further evidence, simply search for the keywords `async`, `await`, and `Task`. You'll find countless web pages singularly claiming to provide an "easy" explanation of these concepts you and I apparently take for granted.

And, I'm moving on now.  Feel free to leave it as is, if that's what you truly believe to be best.  For my part, I'll feel sad for folks who are new to C# and struggling to learn it.  I remember back in 2003 when I was banging my head against a wall because of similar examples :)

**Comment by ewoutkramer** [comment]
If fully agree with @techfan101 - the fact that a piece of syntax has been in the language for a while is not a reason to use it in an example if it doesn’t add anything. And this is especially true if it is a feature of the language that is relatively complex like async.  Why not introduce a covariant generic param T to ILight to spice thing up a bit more?
