### ISSUE TITLE
Build a .NET web app using Docker and Azure Container Registry with GitHub Actions

### ISSUE THREAD

**Issue by rahul-kumar2** [dotnet/docs#27978]
[It would be great if you guys can share similar documentation for the Build and Push .net application with Docker and Azure container registry or in case any related document that you could share? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2552ac3c-ff71-39b0-87e8-088210bf01af
* Version Independent ID: 651ce55b-29d0-29be-cb94-cebbfd3fed17
* Content: [DevOps with .NET and GitHub Actions - Build a .NET Web App](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-build#feedback)
* Content Source: [docs/architecture/devops-for-aspnet-developers/actions-build.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/actions-build.md)
* Product: **dotnet-architecture**
* GitHub Login: @colindembovsky
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @rahul-kumar2, you can refer to the learning module [Deploy a cloud-native ASP.NET Core microservice with GitHub Actions ](https://docs.microsoft.com/en-us/learn/modules/microservices-devops-aspnet-core/ ). I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
