### ISSUE TITLE
Add a sample link of multiple templates within one Nuget package

### ISSUE THREAD

**Issue by LeaFrock** [dotnet/docs#27977]
I've packed a Nuget with my project similar to the following one of doc.

```
project_folder
│   MyDotnetTemplates.csproj
│
└───templates
    ├───mytemplate1
    │   │   console.cs
    │   │   readme.txt
    │   │
    │   └───.template.config
    │           template.json
    │
    └───mytemplate2
        │   otherfile.cs
        │
        └───.template.config
                template.json
```

But when I use `dotnet new` command, the CLI informs me of conflicted templates. Will it be better if there is a repo sample link here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/custom-templates.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
@LeaFrock good suggestion. I'm sure we can put the example templates in our samples repo.

What is your output exactly?

**Comment by LeaFrock** [comment]
> What is your output exactly?

It tells the following info,
```
Unable to resolve the template, the following installed templates are conflicting:

..... (Two templates included in my Nuget package)

The package xxx is not correct, uninstall it and report the issue to the package author.
```
I've solved this error after I made my two `template.json`s' `groupidentity` different. It's my fault that not familiar with how to use `dotnet\templating` correctly, but I think the doc here should give a sample and make both the `template.json` files clear.

**Comment by LeaFrock** [comment]
More information if @adegeo may require for.

The structure of my template package, which is the same as the doc,

![1643337697(1)](https://user-images.githubusercontent.com/20787265/151477979-e5049324-d7e0-42d2-a42a-de4e3b5c0b3f.png)

`template.json` for solution.
```json
{
    "groupIdentity": "xxx.Solution",
    "identity": "xxx.SolutionTemplate",
    "name": "xxx Template NewSolution",
    "shortName": "xxx-sln",
    "sourceName": "AppName",
}

```

For module,

```json
{
  "groupIdentity": "xxx.Module",
  "identity": "xxx.ModuleTemplate",
  "name": "xxx Template NewModule",
  "shortName": "xxx-mod",
  "sourceName": "ModName",
}
```

At the beginning, both of their `groupIdentity` were the same("XXX"), and CLI informed the error messages I mentioned above.
