### ISSUE TITLE
Single File Deployments are not Supported by IIS.

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/docs#27983]
I think it would be beneficial to note in the Docs that Single File Deployments are not supported by IIS.

This has tripped me up twice.  Not a big issue, but a footnote somewhere just so it is documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [Application publishing - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by luoyunchong** [comment]
in csproj File Add
```
  <PropertyGroup>
	<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
  </PropertyGroup>
```

**Comment by adegeo** [comment]
@luoyunchong @gregoryagu does `OutOfProcess` fix the deployment problem?

**Comment by gregoryagu** [comment]
@adegeo I tested by updated the Project to use the Out Of Process hosting model and the Single File option.  It did indeed run successfully on IIS.  However, it is worth noting that In Process is the default and, from what I have read, the currently recommended process model due to speed enhancements.  In any case, I am ok with closing this issue at this time.
