### ISSUE TITLE
<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />

### ISSUE THREAD

**Issue by rajnishc8** [dotnet/docs#27986]
Should it be
_`
 <PackageReference Include="Microsoft.Win32.Registry" Version="6.0.0" />
instead of
<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
`_
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bc889a-e3e1-65b3-f3c3-8597d30300db
* Version Independent ID: d70af595-d281-da13-a5d9-e7a8f369c59d
* Content: [Upgrade Windows Forms apps to .NET 6 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-winforms-framework)
* Content Source: [docs/core/porting/upgrade-assistant-winforms-framework.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-winforms-framework.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hi @rajnishc8 the 6.0.0 package is still in preview, 5.0.0 is the latest: https://www.nuget.org/packages/Microsoft.Win32.Registry/5.0.0
