### ISSUE TITLE
Unable to find sample code for High-performance logging in .NET

### ISSUE THREAD

**Issue by kimbaudi** [dotnet/docs#27990]
I am unable to find the sample app source code for the docs on [High-performance logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging). The doc claims that the code sample is available on GitHub, but I can't find it. I would like to see the sample code for `Worker.cs` and `WorkItem`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa00c051-c047-bbcd-5e25-ca6a722b51c3
* Version Independent ID: 3f5f1b6e-06ac-cc07-48cd-b8b957a4abbb
* Content: [High-performance logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging)
* Content Source: [docs/core/extensions/high-performance-logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/high-performance-logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @kimbaudi - you're correct that the article points to the incorrect location for the code samples. Here is the source code you're looking for:

https://github.com/dotnet/docs/tree/main/docs/core/extensions/snippets/configuration/worker-service-options

Bits from [_Worker.cs_](https://github.com/dotnet/docs/blob/main/docs/core/extensions/snippets/configuration/worker-service-options/Worker.cs):

```csharp
using WorkerServiceOptions.Example.Extensions;

namespace WorkerServiceOptions.Example;

public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;
    private readonly PriorityQueue _priorityQueue;

    public Worker(ILogger<Worker> logger, PriorityQueue priorityQueue) =>
        (_logger, _priorityQueue) = (logger, priorityQueue);

    protected override async Task ExecuteAsync(
        CancellationToken stoppingToken)
    {
        using IDisposable? scope = _logger.ProcessingWorkScope(DateTime.Now);
        while (!stoppingToken.IsCancellationRequested)
        {
            WorkItem? nextItem = _priorityQueue.ProcessNextHighestPriority();
            try
            {
                if (nextItem is not null)
                {
                    _logger.PriorityItemProcessed(nextItem);
                }
            }
            catch (Exception ex)
            {
                _logger.FailedToProcessWorkItem(ex);
            }

            await Task.Delay(1000, stoppingToken);
        }
    }
}
```

Bits from the [_WorkItem.cs_](https://github.com/dotnet/docs/blob/main/docs/core/extensions/snippets/configuration/worker-service-options/WorkItem.cs):

```csharp
namespace WorkerServiceOptions.Example;

public record WorkItem(
    string Name, Priority Priority, bool IsCompleted = false)
{
    public Guid Id { get; init; } = Guid.NewGuid();

    public WorkItem MarkAsComplete() =>
        this with { IsCompleted = true };

    public override string ToString() =>
        $"Priority-{Priority} ({Id}): '{Name}'";
}
```

I'll work on this next sprint, to update and fix the links.

**Comment by kimbaudi** [comment]
thank you for providing the location of the source!
