### ISSUE TITLE
TLS Code Audit link is self-referencing!

### ISSUE THREAD

**Issue by x509cert** [dotnet/docs#27995]
[Enter feedback here]
The line "The section Audit your code and make code changes covers auditing and updating your code." links back to this page - did you mean another page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment]
That line links to a section a little further down the page. This was intentional.
