### ISSUE TITLE
Update `is` for pattern matching with generics

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2799]
C# 7.1 adds [Pattern Matching with Generics](https://github.com/dotnet/csharplang/blob/master/proposals/generics-pattern-match.md). 

We need to update a few pages for this:

- [ ] `is` keyword
- [ ] `as` keyword
- [ ] Pattern Matching topic.

**Comment by BillWagner** [comment]
I read the pages listed above:

[Pattern Matching in C# 7](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
[as keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/as)
[is keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is)

I don't see any updates necessary. 

I propose closing this.  

/cc @mairaw @jcouv

**Comment by jcouv** [comment]
@gafter Could you review the existing documentation (linked above) on pattern matching in C# 7 and as/is, and advise whether further updates are necessary?

**Comment by BillWagner** [comment]
Closed based on conversation with @gafter
