### ISSUE TITLE
Subject of this page is unclear

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#28003]
The title of the page ("Dynamically specify predicate filters at runtime") suggests using or adding different `where` clauses at runtime. Neither of the subsections / examples of the page directly deal with this: the first subsection shows how to use `Contains` to filter against multiple values, while the second replaces the entire query.

Moreover, in theory, any part of a query could be dynamic by that measure -- `select`, `group by` etc.

I would suggest the original intent of the page is something more like [Querying based on runtime state](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries) -- how to have queries interact differently based on runtime state, which is far broader, and shows many more techniques.

In addition, I think that topic is more appropriately placed under the LINQ section (replacing this topic); and the page there should be devoted to the more limited topic of how to construct expression trees (using factory methods, or perhaps the Dynamic LINQ library).

ping @BillWagner @gewarren 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc236de-12ec-cb38-153f-377a4d1c3006
* Version Independent ID: f1701369-b459-35d3-51a2-c63f96cb3dda
* Content: [Dynamically specify predicate filters at run time (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/dynamically-specify-predicate-filters-at-runtime)
* Content Source: [docs/csharp/linq/dynamically-specify-predicate-filters-at-runtime.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/dynamically-specify-predicate-filters-at-runtime.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 238751](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238751)

**Comment by BillWagner** [comment]
Thanks @zspitz 

These are good ideas. 

For the moment, I'll set this in in the backlog. The area of LINQ and expressions is one we have on our list to update. To be fair, I'm not sure how quickly it will rise to the top of the list. There are a couple problem areas that need to be addressed first.

**Comment by zspitz** [comment]
@BillWagner Would it be too early to submit a PR for this? Can I contribute more generally to these areas (LINQ, expression trees)?

**Comment by zspitz** [comment]
Discussing this is a little complicated by the duplicate LINQ and expression tree sections of the documentation (#28027).

But I think the relevant pages should be structured as follows:

* LINQ
  * Filtering on multiple values, using `.Contains` ([the example here](https://docs.microsoft.com/en-us/dotnet/csharp/linq/dynamically-specify-predicate-filters-at-runtime#to-filter-by-using-the-contains-method))
    (It might also include other examples using multiple values in other parts of the query, such as in the `select`.)
  * Querying based on runtime state ([link](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries), discussing `Expression` factory-method-construction in the LINQ context)
* Expression trees
    * Constructing expression trees using the factory methods -- linking to [this](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries#construct-expression-trees-and-queries-using-factory-methods), but also providing examples of 
      1. manually constructing expression trees for other (non-LINQ) APIs that take expression trees (e.g. ASP.NET helpers), and
      2. creating compiled delegates purely at runtime (DLR, self-modifying programs such as the [Animal game](https://cseducators.stackexchange.com/a/6849)

**Comment by zspitz** [comment]
@BillWagner Is this a good plan for the short-term (long-term requires resolving #28027)?

**Comment by BillWagner** [comment]
@zspitz I like this plan. It does address many of the concerns.

Once you have a draft PR, mention me, and I'll take a look. (Generally draft PRs don't show up in the "review" queue on GitHub).
