### ISSUE TITLE
Some arguments are documented as switches but still require a value

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/docs#28007]
`--no-symbols` is documented as a switch, however it requires a value. This has been reported in 2017.
https://github.com/NuGet/Home/issues/4864

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/4326
