### ISSUE TITLE
Page should be under LINQ, instead of under expression trees

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#28008]
Broadly speaking, I think there are two primary use cases for expression trees:

* Using C# VB.NET code to control some API. Most prominently -- but not limited to -- LINQ.
* Creating compiled code from some arbitrary input, such as a DSL

In the context of querying, it makes sense to talk about constructing expression trees -- that's one of the ways in which we can query based on runtime state, by constructing varying expression trees at runtime.  But I would suggest this page should be replaced with some examples of:

1. additional APIs controlled by C#/VB.NET code via expression trees, and/or
2. a simple DSL which would show off compiling code from arbitrary structured input

Related #28003 

ping @BillWagner  @gewarren 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e7c92f-899d-506e-dced-ade9245fa231
* Version Independent ID: 0f232a4f-3c75-7736-7c70-c409d3cf5ab5
* Content: [Querying based on runtime state (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising both these issues @zspitz 

The same comment applies here: These are good ideas, and I want to look at them as we update our LINQ and expression tree content.
