### ISSUE TITLE
a minor error in the code

### ISSUE THREAD

**Issue by sq4cvh** [dotnet/docs#28004]
Service available by address (https://karljoke.herokuapp.com/jokes/programming/random), if it works :) returns not an array but a single JSON variable, while the example code contains a result cast to the array "Joke []? jokes = await _httpClient.GetFromJsonAsync <Joke []> (JokeApiUrl, _options); "
Such code does not work, I suggest changing the address of example variables to "https://karljoke.herokuapp.com/jokes/programming/ten", then the table is returned and the example code washes the first element from it and works, or change the code by replacing Joke [] on Joke and "Joke? joke = jokes? [0];" to "Joke? joke = jokes ?;"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @sq4cvh,

Thank you for bringing this to my attention. I will fix this next month.

**Comment by IEvangelist** [comment]
Hi @sq4cvh - I just verified, this does in fact return an array with a single element:

```json
[
    {
        "id":29,
        "type":"programming",
        "setup":"There are 10 types of people in this world...",
        "punchline":"Those who understand binary and those who don't"
    }
]
```

However, I know that it's not really a practical example. I was intended to show how everything works, I'll update this. Thanks
