### ISSUE TITLE
Category suppression does not work

### ISSUE THREAD

**Issue by jdvor** [dotnet/docs#28010]
Category suppression does not seem to work. `dotnet_analyzer_diagnostic.category-Documentation.severity = none` does nothing for suppression within `.editorconfig` while individual rule settings do work as expected.

```
$ dotnet --version
6.0.101
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8a45df9-7c3c-2858-e0a8-e5327e68e7af
* Version Independent ID: 6fbcd123-c826-86a2-91f9-2fa61bd0268d
* Content: [Code analysis rule categories - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories)
* Content Source: [docs/fundamentals/code-analysis/categories.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/categories.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Hmm, I can't get it work either on the same version. @Youssef1313 any ideas here? I can't get severity settings on individual rules to work either.

**Comment by Youssef1313** [comment]
@gewarren I can reproduce as well. Per the documentation, this scenario is supposed to work as far as I understand:

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#scope

> When you configure the severity level for multiple rules with a single entry, either for a *category* of rules or for *all* rules, the severity only applies to rules that are [enabled by default](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md). To enable rules that are disabled by default, you must either:
>
> - Add an explicit `dotnet_diagnostic.<rule ID>.severity = <severity>` configuration entry for each rule.
> - In .NET 6+, enable a category of rules by setting [\<AnalysisMode\<Category>>](../../core/project-sdk/msbuild-props.md#analysismodecategory) to `All`.
> - Enable *all* rules by setting [\<AnalysisMode>](../../core/project-sdk/msbuild-props.md#analysismode) to `All` or by setting [\<AnalysisLevel>](../../core/project-sdk/msbuild-props.md#analysislevel) to `latest-All`.

The documentation rule we have is CA1200 and it's enabled by default:

https://github.com/dotnet/roslyn-analyzers/blob/60eb13c44c366205e5a4dec195404477009c41de/src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif#L60

@mavasani Is this a product bug or something needs clarification in docs?

**Comment by jdvor** [comment]
In my case it  was caused by my expectation that everybody would use same category names for their analyzers which turns out not to be the case.
It is still possible there are minor bugs for individual rules, but I bet it would be just the case that their category name is simply different than the one you are expecting to be.

This setting worked for me at the end:
```
dotnet_analyzer_diagnostic.category-Documentation.severity = none
dotnet_analyzer_diagnostic.category-StyleCop.CSharp.DocumentationRules.severity = none
dotnet_diagnostic.CS1591.severity = none 
```
AnalysisMode = recommended

I would close this issue unless you feel there is really a bug.

**Comment by Youssef1313** [comment]
@jdvor Let's keep it open until we know the behavior for CA1200, which uses "Documentation" as the category, not "StyleCop.CSharp.DocumentationRules"

**Comment by mavasani** [comment]
> until we know the behavior for CA1200, which uses "Documentation" as the category, not "StyleCop.CSharp.DocumentationRules"

This is by design. CAxxxx rules do not have `StyleCop.` prefix in the category name, and all StyleCop rules have a `StyleCop.` prefix in their category name.

**Comment by Youssef1313** [comment]
@mavsani I meant that I used "Documentation" as category name but didn't work.

**Comment by jdvor** [comment]
> This is by design. CAxxxx rules do not have `StyleCop.` prefix in the category name, and all StyleCop rules have a `StyleCop.` prefix in their category name.

I think it would be more precise (less misleading) to say that analyzer's authors can choose whatever category name they see fit and there's no convention of what it should be. Yes, they tend to use **similar** names, but they are not **just** prefixed.

@Youssef1313 I think you should create separate issues for your case of CA1200, because this one emerged from just mine false expectation.

**Comment by Youssef1313** [comment]
Opened https://github.com/dotnet/roslyn-analyzers/issues/5852
