### ISSUE TITLE
Naming convention of private field is not followed

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#28014]
This pages shows the following code snippet:
  // public class:
public class Tricycle
{
    //code skipped

    // private field:
    private int wheels = 3;

   // code skipped
}

But  https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md and https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions  suggest to use underscore at the beginning such as:
private IWorkerQueue _workerQueue;

Regards,
Vaskaran

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the comment @Vaskaran 

Many of our samples pre-date adopting this convention in our repos. We're addressing that as we update each sample.

I've also added the "up for grabs" label if anyone wants to make the update before we fix this sample.
