### ISSUE TITLE
nint and nuint cannot be used as enum base type

### ISSUE THREAD

**Issue by sajagi** [dotnet/docs#28016]
Section [Miscellaneous](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/native-integers#miscellaneous) mentions the possibility of using nint and nuint types as enum base types:

> nint and nuint can be used as an enum base type.

However, this is not mentioned in C# ECMA specification nor is it supported even in the latest compiler (.NET 6, C# 10). Visual Studio 2022 also shows an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de63b2ae-2018-b52e-0cb4-d19ac77093c1
* Version Independent ID: 9805d223-c541-8a6b-f79f-3ae3dd71023f
* Content: [Native sized integers - C# 9.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/native-integers)
* Content Source: [proposals/csharp-9.0/native-integers.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/native-integers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ading @tannergooding

**Comment by tannergooding** [comment]
CC. @cston; this is supported at the IL level (by ECMA-335) and is something C# can support; but I believe the support never actually got added due to time constraints, etc.

**Comment by cston** [comment]
@sajagi, thanks for reporting this.

I've created a PR to update the documentation: https://github.com/dotnet/csharplang/pull/5709

**Comment by BillWagner** [comment]
closing as fixed in dotnet/csharplang#5709

**Comment by BillWagner** [comment]
> Is there a possibility of having nint and nuint as enum base types?

@ImmuneLion318 That's a question for the `dotnet/csharplang` [repo](https://github.com/dotnet/csharplant. That's where the language design team works on any new features in the language.  @tannergooding can point to any current discussions or proposals for this feature.
