### ISSUE TITLE
Provide a note on the dotnet install script documentation on how to persist dotnet tool on PATH across sessions

### ISSUE THREAD

**Issue by joperezr** [dotnet/docs#28023]
It was reported in https://github.com/dotnet/iot/issues/1783#issuecomment-1025786916 by @pelikhan that currently the documentation for the dotnet-install-scripts don't currently provide optional instructions on how to persist the dotnet tool application registration on the PATH across sessions. This is important in particular for systems with linux arm32 processors since using the dotnet-install scripts are pretty much the only way to install the sdk today, as there are no good options for using package managers on arm32. We have some instructions on how to do this in one of our dotnet/iot-specific docs page: https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md

```md
    1. To simplify path resolution, add a `DOTNET_ROOT` environment variable and add the *.dotnet* directory to `$PATH` with the following commands:

        
        echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
        echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc
        source ~/.bashrc
        
```

The suggestion that this issue is tracking would be to add some similar optional steps in the dotnet-install scripts docs as well, for folks that follow those instructions to know how to do this themselves if they need to.

cc: @CamSoper 

---
[Associated WorkItem - 50931](https://dev.azure.com/msft-skilling/Content/_workitems/edit/50931)

**Comment by adegeo** [comment]
This was fixed in #34234
