### ISSUE TITLE
Missing IDE0065 rule in expression level preferences page

### ISSUE THREAD

**Issue by PSafonov** [dotnet/docs#28045]
[Expression-level preferences page](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/expression-level-preferences.md) doesn't include the following C# rule:

- ['using' directive placement (IDE0065)](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0065.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d68df2e-df41-e39b-e34d-fedb3666ed62
* Version Independent ID: c33ae36b-9dd5-d4aa-102b-cd5aef205ec0
* Content: [Expression-level preferences - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/expression-level-preferences)
* Content Source: [docs/fundamentals/code-analysis/style-rules/expression-level-preferences.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/expression-level-preferences.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The rule is listed under the "using directive placement" section here: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/language-rules#c-style-rules. So I don't believe it should be listed on the expression-level preferences page. Let me know if you disagree.

**Comment by PSafonov** [comment]
@gewarren Ah... I see. ['using' directive placement (IDE0065)](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0065.md) description has misleading "Language rules (expression-level preferences)" subcategory, that's why I thought it should be under "expression-level preferences" section.

**Comment by gewarren** [comment]
Ah, that looks like a copy/paste error. I'll fix that. Thanks!
