### ISSUE TITLE
Update Azure Container Service to Azure Kubernetes Service

### ISSUE THREAD

**Issue by mohamedsaif** [dotnet/docs#28047]
[Enter feedback here]
References to the old name for AKS is confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f25d03-f983-be76-39a6-ffc0d60ef7c9
* Version Independent ID: 7b034dae-9106-87f6-dc37-b2855bca6336
* Content: [When to deploy Windows Containers to Azure Container Service (that is, Kubernetes)](https://docs.microsoft.com/en-us/dotnet/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes)
* Content Source: [docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modernize-with-azure-containers/modernize-existing-apps-to-cloud-optimized/when-to-deploy-windows-containers-to-azure-container-service-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **modernize-with-azure-containers**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by nishanil** [comment]
@mohamedsaif Thanks for pointing it out. We have modified the content. Closing the issue now.
