### ISSUE TITLE
Null-forgiven attribute decorator

### ISSUE THREAD

**Issue by dalbarracin** [dotnet/docs#28052]
Hi everyone,

Reading the documentation, which i found useful so far, give me more doubts than helps regarding the null-forgiven attribute.

```c#
public static bool IsValid([NotNullWhen(true)] Person? person) 
     => person is not null && person.Name is not null;
```

if someone read this contract, it becomes so hard to understand what's this method is intended to do:

> _Is valid NotNullWhen person?_

instead of:

> _Is valid "person"?_

Could that be possible in the near future to improve how to tell the compiler in design time when a nulleable type must be forgiven in such as cases. This attribute doesn't give quick information about why was implemented to an argument, just because a warning must be hidden, unless you read the documentation carefully.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0471f98c-f5cd-00d2-a705-396682f73bcb
* Version Independent ID: a24b862d-c462-a040-8470-9771c74c4e6f
* Content: [! (null-forgiving) operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving)
* Content Source: [docs/csharp/language-reference/operators/null-forgiving.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/null-forgiving.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @dalbarracin 

Thanks for reaching out.  In this instance, I try to read that code as "The argument for `person` is not-null when this method returns `true`." 

I don't think this structure is going to change. I'll tag @MadsTorgersen in case there are any plans on the horizon.

**Comment by BillWagner** [comment]
@dalbarracin 

I did discuss internally, and there isn't any open plans to change this behavior. 

I'll close this.  If you want to make a proposal, you can add a request in [dotnet/csharplang](https://github.com/dotnet/csharplang).
