### ISSUE TITLE
Does the next version of the developer pack include everything needed from the previous version?

### ISSUE THREAD

**Issue by mdell-seradex** [dotnet/docs#28058]
For instance, does the .NET Framework 4.8 Developer Pack include the needed files from the .NET Framework 4.7.2 Developer Pack and below, such that it allows you to target earlier versions of the .NET Framework?  i.e. the .NET Framework 4.8 Developer Pack supersedes the the .NET Framework 4.7.2 Developer Pack and below.

It does not seem clear to me.
For instance, this `When building an application from Visual Studio or using MSBuild from the command line, MSBuild may display error MSB3644, "The reference assemblies for framework "framework-version" were not found." To address the error, download the developer pack or the targeting pack for that version of .NET Framework.` indicates to me that 4.8 does not include 4.7, etc.
However, the image from the Visual Studio installer appears to indicate that it is not always true as the one highlighted portion states ".NET Framework 4 - 4.6 development tools", and 4.7.2 and 4.8 are not even listed.

I appreciate any clarity you can provide.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, The screenshot is out of date which is why you don't see those versions. I'll update the article wording and the screenshot. Thank you for reporting this.

**Comment by mdell-seradex** [comment]
I appreciate that the image was updated, but I was hoping that text would be added that specifically stated whether any version supersedes previous versions of the Developer Pack.
For instance, if the .NET Framework 4.8 Developer Pack is installed, then do we still have to install the .NET Framework 4.7.2 Developer Pack, the .NET Framework 4.7.1 Developer Pack, and the .NET Framework 4.7 Developer Pack to be able to build a project that targets 4.8, one that targets 4.7.2, another 4.7.1, and another 4.7?
You can carry that question down to all of the possible supported Framework versions to target.

I look forward to improved clarity on this, that is more that just the image that implies it may be possible.

Thank you

**Comment by mdell-seradex** [comment]
@adegeo, I appreciate that the image was updated, but I was hoping that text would be added that specifically stated whether any version supersedes previous versions of the Developer Pack.
For instance, if the .NET Framework 4.8 Developer Pack is installed, then do we still have to install the .NET Framework 4.7.2 Developer Pack, the .NET Framework 4.7.1 Developer Pack, and the .NET Framework 4.7 Developer Pack to be able to build a project that targets 4.8, one that targets 4.7.2, another 4.7.1, and another 4.7?
You can carry that question down to all of the possible supported Framework versions to target.

I look forward to improved clarity on this, that is more that just the image that implies it may be possible.
I appreciate any responses on this.

Thank you

**Comment by adegeo** [comment]
Hi @mdell-seradex I've opened another PR to add a statement about it.
