### ISSUE TITLE
Visual Studio 2022 can runs as a native 64 application on 64-bit system. This page isn't update.

### ISSUE THREAD

**Issue by mehmetolgundev** [dotnet/docs#28075]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa0cc9c-2160-7077-6764-70c12bec20e9
* Version Independent ID: 77b5942b-d96d-2839-2541-9a7c878e0bf6
* Content: [64-bit Applications - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/64-bit-apps#feedback)
* Content Source: [docs/framework/64-bit-apps.md](https://github.com/dotnet/docs/blob/main/docs/framework/64-bit-apps.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
