### ISSUE TITLE
Feature Comparison table has incorrect description for "Passwordless connections to cloud providers"

### ISSUE THREAD

**Issue by tulleuchen** [dotnet/docs#28082]
[Enter feedback here]
The row in the Feature Comparison table "Passwordless connections to cloud providers" Yes/No incorrectly entered. The "Yes" is appearing the the Description Column. 
![image](https://user-images.githubusercontent.com/45860725/152604915-83775a00-fd06-4b16-a603-169ef02bf27b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea049336-6c09-1791-a102-cede5fa3ebff
* Version Independent ID: 36ffb095-5a05-8516-ab25-1120b3c22979
* Content: [DevOps with .NET and GitHub Actions - Compare GitHub Actions with Azure Pipelines](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-vs-pipelines)
* Content Source: [docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md)
* Product: **dotnet-architecture**
* GitHub Login: @colindembovsky
* Microsoft Alias: **nanil**

**Comment by VaishaliRaval** [comment]
Hey @tulleuchen, thank you for reaching out. I have fixed this issue in the attached PRs.
