### ISSUE TITLE
Well if you have VS 2022 this page is useless 

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs#28089]
So I get an error with VS 2022. I use the link from the error message and go to this page.

So nothing described here is what you see in VS 2022.  

Between VS  2022 (so many problems with documentation) and Windows 11 (so many problems - most dissed product from MS online).  

Please show this to the MS Grinch
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [Enable or disable autogenerated binding redirects - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection?redirectedfrom=MSDN)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@sqlguy6212 What type of project did you have open in VS 2022? I don't see the "Auto-generate binding redirects" option for a WPF project that targets .NET 6, however I do see it for a .NET Framework 4.7.2 project. I believe this option only applies to .NET Framework projects for Windows desktop apps and web apps.

**Comment by gewarren** [comment]
It seems that [error MSB3276](https://github.com/dotnet/msbuild/blob/9c173296404f9c365cc524569766f16d7cfcf308/src/Tasks/Resources/xlf/Strings.xlf#L1361) links to this article, which may not be appropriate in all cases.

I've made some small updates to the article in #28089, for example, to clarify that the option can be disabled in the project file if the checkbox isn't present.

Related to #7650.
