### ISSUE TITLE
Possible improvement: user-defined type deconstructors with same arity

### ISSUE THREAD

**Issue by deep-outcome** [dotnet/docs#28091]
> Multiple Deconstruct methods having the same number of parameters are ambiguous. You must be careful to define Deconstruct methods with different numbers of parameters, or "arity". Deconstruct methods with the same number of parameters cannot be distinguished during overload resolution.

It is not needed to avoid same-arity deconstructors. This part can be uplifted to point out classic method call w/o compiler ability leverage although then `Deconstruct` does not differ from any other method with `out` parameters. That since (FMPOV) it is likely that in future, it will be possible to specify overload by variable **explicit type provision**.

```csharp
class SameArityDeconstructors
. {
.     public void Deconstruct ( out int i, out int y ) { i = 3; y = 8; }
.     public void Deconstruct ( out string s, out string z ) { s = "s"; z = "z"; }
. }
> new SameArityDeconstructors ().Deconstruct ( out int i, out int y );
> i
3
> y
8
```

It can be said also if type can have for instance 1 .dcnstr with arity of 2, then other with arity of 3, it is not so fine to have suddenly another methods, let name them `NotSupportedDeconstruc`, for resting 2 .dcnsrts with arity of 4.

#### Explicit type provision does solve nothing by now
```csharp
(string s, string z) = new SameArityDeconstructors ();
(1,24): error CS0121: The call is ambiguous between the following methods or properties: 'SameArityDeconstructors.Deconstruct(out int, out int)' and 'SameArityDeconstructors.Deconstruct(out string, out string)'
```
---

Also _arity_  can be considered fine, nice word. It does not have be enclosed in quotation marks.

Edit by @BillWagner: Move to language reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fbaed1-06d8-16f0-70d1-97792daccfd5
* Version Independent ID: 830019b6-d46c-2867-9dbd-dd89a77dd7a4
* Content: [C# Language reference](https://docs.microsoft.com/dotnet/csharp/language-reference/)
* Content Source: [https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 350758](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350758)

**Comment by BillWagner** [comment]
Your discussion on the specific details for deconstruction is correct @Uzivatel919 

However, I'm going to move this to a different section because this level of detail doesn't belong in the "Fundamentals" section. Rather it should be in the "language reference" section. (Interestingly, there isn't an article on deconstruction in the language reference).
