### ISSUE TITLE
Possible improvement: Tuple types (C# reference) – noting `ValueTuple` items count illimitability implementation

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#28098]
> You can define tuples with an arbitrary large number of elements:
> ```csharp
> var t = 
> (1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
> 11, 12, 13, 14, 15, 16, 17, 18,
> 19, 20, 21, 22, 23, 24, 25, 26);
> Console.WriteLine(t.Item26);  // output: 26 ```

Maybe this feature show deserves small note about how it is even possible – work with [`ValueTuple<T1,T2,T3,T4,T5,T6,T7,TRest> Struct`](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-8?view=net-6.0). See briefing bellow.

```csharp
public void Test ()
{
  var tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9);
  VisualSweety( tuple );
  BitterType ( tuple );
  
  //IL_0027: ldloc.0
  //IL_0028: ldfld !0 valuetype [System.Runtime]System.ValueTuple`8<int32, int32, int32, int32, int32, int32, int32, valuetype [System.Runtime]System.ValueTuple`2<int32, int32>>::Item1 /* 0A000010 */
  //IL_002d: stloc.1
  var a = tuple.Item1;
  
  //IL_002e: ldloc.0
  //IL_002f: ldfld !7 valuetype [System.Runtime]System.ValueTuple`8<int32, int32, int32, int32, int32, int32, int32, valuetype [System.Runtime]System.ValueTuple`2<int32, int32>>::Rest /* 0A000011 */
  //IL_0034: ldfld !1 valuetype [System.Runtime]System.ValueTuple`2<int32, int32>::Item2 /* 0A000012 */
  //IL_0039: stloc.2
  var i = tuple.Item9;
}

public void VisualSweety<A, B, C, D, E, F, G, H, I> ( (A, B, C, D, E, F, G, H, I) vt ) { }
public void BitterType<A, B, C, D, E, F, G, H, I> ( ValueTuple<A, B, C, D, E, F, G, ValueTuple<H, I>> vt ) { }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e533179-50e7-813d-be49-e1248134dd10
* Version Independent ID: 1778e921-76f6-32d5-4509-7bd944a01e0d
* Content: [Tuple types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples)
* Content Source: [docs/csharp/language-reference/builtin-types/value-tuples.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
You are correct in how this is implemented @Uzivatel919 

My opinion is that this level of detail belongs in the language specification, not here. 

I'll close this, but I'll keep watching if you want to add more detail as to why you think this should be added here.

**Comment by Uzivatel919** [comment]
Let agree with your opinion.
