### ISSUE TITLE
Tuple assignment and deconstruction not listing all deconstruction options

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#28099]
> You can also use the assignment operator = to deconstruct a tuple instance in separate variables. You can do that in one of the following ways:
> …

This list misses two more options that are stated on referenced [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct), respectively at [Tuples](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#tuples), while it impresses definitive enumeration.

It is 
> You can also use the var keyword individually with any or all of the variable declarations inside the parentheses.

and 

> Beginning in C# 10, you can mix variable declaration and assignment in a deconstruction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e533179-50e7-813d-be49-e1248134dd10
* Version Independent ID: 1778e921-76f6-32d5-4509-7bd944a01e0d
* Content: [Tuple types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuple-assignment-and-deconstruction)
* Content Source: [docs/csharp/language-reference/builtin-types/value-tuples.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good catch @Uzivatel919 

I've added for our next updates to this article.
