### ISSUE TITLE
Tutorial steps and sample code don't match up

### ISSUE THREAD

**Issue by PhasonMatrix** [dotnet/docs#28094]
After the tutorial text "1. First, create the GetAbsolutePath method at the bottom of the Program.cs file.", The following sample code is NOT of the GetAbsolutePath method, but of an unrelated section of code.

Similarly, after the text "2. Then, below the using statements, create fields to store the location of your assets.", the code sample does NOT show some fields, but another unrelated piece of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @PhasonMatrix thanks for raising this issue. Updates have been made in #28516 and the changes should be reflected shorty.

**Comment by luisquintanilla** [comment]
Fixed by #28516
