### ISSUE TITLE
Fix description for Enumerable.Take

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/docs#28095]
Description for `Enumerable.Take` states:

 > Accepts a [Range](https://docs.microsoft.com/en-us/dotnet/api/system.range) argument to simplify taking a slice of a sequence—for example, you can use source.Take(2..7) instead of source.Take(7).Skip(2).

is which incorrect and it should be:

... source.Take(2..7) instead of source **.Skip(2).Take(5)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef8e04b-d98b-326e-aec0-a4835eb2e69b
* Version Independent ID: d86ed862-d969-8cbd-ce57-031207400241
* Content: [What's new in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-6)
* Content Source: [docs/core/whats-new/dotnet-6.md](https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-6.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I tried it out with the following code. It's correct as written, and your variation is also correct. So I don't think anything needs to be changed here.

```
int[] numbers = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
foreach (var number in (numbers.Take(2..7)))
{
    Console.WriteLine(number);
}
Console.WriteLine();
foreach (var number in (numbers.Skip(2).Take(5)))
{
    Console.WriteLine(number);
}
Console.WriteLine();
foreach (var number in (numbers.Take(7).Skip(2)))
{
    Console.WriteLine(number);
}
```

**Comment by JosefPihrt** [comment]
@gewarren You are right.
