### ISSUE TITLE
Not only _record_ or `DictionaryEntry` beside any `ValueTuple` provides deconstructor

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#28090]
> C# doesn't offer built-in support for deconstructing non-tuple types other than the [record](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#record-types) and [DictionaryEntry](https://docs.microsoft.com/en-us/dotnet/api/system.collections.dictionaryentry.deconstruct) types.

At least there is [KeyValuePair<TKey,TValue>.Deconstruct(TKey, TValue) Method](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=net-6.0) in addition.

Also this fact is discussed in chapter [Extension method for system types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#extension-method-for-system-types).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fbaed1-06d8-16f0-70d1-97792daccfd5
* Version Independent ID: 830019b6-d46c-2867-9dbd-dd89a77dd7a4
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct)
* Content Source: [docs/csharp/fundamentals/functional/deconstruct.md](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct#user-defined-types)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 345702](https://dev.azure.com/msft-skilling/Content/_workitems/edit/345702)

**Comment by BillWagner** [comment]
Good catch @Uzivatel919 

The sentence should be removed. The important point for developers is:

- The compiler generates the necessary assignments to deconstruct all members from a tuple.
- The compiler synthesizes a `Deconstruct` method for positional `record` types. This `Deconstruct` method deconstructs all the properties declared using positional syntax.
