### ISSUE TITLE
ExecuteAsync never got called in custom implementation of  IHostedService after StartAsync() is called

### ISSUE THREAD

**Issue by wdzhang66** [dotnet/docs#28104]
In your example, DoWork is started in StartAsync(). It works fine. My question is why can‘t I put calling DoWork() in ExecuteAsync() like we can do if we exends from BackgroundService？I tried it and found ExecuteAsync() never got called.

    protected async Task ExecuteAsync(CancellationToken stoppingToken)
     {
         _logger.LogInformation("{Service} is running.", nameof(TimerHostedService));
         _timer = new Timer(DoWork, null, TimeSpan.Zero, TimeSpan.FromSeconds(5));
 
        return _completedTask;
     }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b247969-9dc8-e710-ca64-745596cc3082
* Version Independent ID: 483cf588-2b7b-73cd-f9f9-a231a9c8dd7f
* Content: [Implement the IHostedService interface](https://docs.microsoft.com/en-us/dotnet/core/extensions/timer-service)
* Content Source: [docs/core/extensions/timer-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/timer-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gfoidl** [comment]
Can you please show the whole class (not just _ExecuteAsync_ method)?
Is _ExecuteAsync_ called anywhere in your code?

**Comment by IEvangelist** [comment]
> In your example, DoWork is started in StartAsync(). It works fine. My question is why can‘t I put calling DoWork() in ExecuteAsync() like we can do if we exends from BackgroundService？I tried it and found ExecuteAsync() never got called.
> 
> ```csharp
> protected async Task ExecuteAsync(CancellationToken stoppingToken)
>  {
>      _logger.LogInformation("{Service} is running.", nameof(TimerHostedService));
>      _timer = new Timer(DoWork, null, TimeSpan.Zero, TimeSpan.FromSeconds(5));
> 
>     return _completedTask;
>  }
> ```

Hi @wdzhang66, thank you for posting this issue.

You are confusing [`IHostedService`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.ihostedservice) and `BackgroundService`. The `IHostedService` has two methods:

1. `StartAsync`
2. `StopAsync`

The [`BackgroundService`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.backgroundservice) is an `abstract class` that's also a framework-provided implementation of the `IHostedService`. It exposes the `ExecuteAsync`, but `IHostedService` does not. A custom implementation of the `IHostedService` that is not a `BackgroundService` will only ever have `StartAsync/StopAsync` methods called, as those are the only methods known by the runtime. However, if you extend the `BackgroundService` the `ExecuteAsync` is called since the framework knows about that method. Does that make sense?

**Comment by wdzhang66** [comment]
> wdzhang66



> 
Thanks for pointing out that the framework onlt knows about that method ExecuteAsync in BackgroundService, that explains why ExecuteAsync is not called in my implementation of IHostedService. I was just curious about the reason. In order to be called, I can just put the calling code in the StartAsync

**Comment by wdzhang66** [comment]
> > In your example, DoWork is started in StartAsync(). It works fine. My question is why can‘t I put calling DoWork() in ExecuteAsync() like we can do if we exends from BackgroundService？I tried it and found ExecuteAsync() never got called.
> > ```cs
> > protected async Task ExecuteAsync(CancellationToken stoppingToken)
> >  {
> >      _logger.LogInformation("{Service} is running.", nameof(TimerHostedService));
> >      _timer = new Timer(DoWork, null, TimeSpan.Zero, TimeSpan.FromSeconds(5));
> > 
> >     return _completedTask;
> >  }
> > ```
> 
> Hi @wdzhang66, thank you for posting this issue.
> 
> You are confusing [`IHostedService`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.ihostedservice) and `BackgroundService`. The `IHostedService` has two methods:
> 
> 1. `StartAsync`
> 2. `StopAsync`
> 
> The [`BackgroundService`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.backgroundservice) is an >`abstract class` that's also a framework-provided implementation of the `IHostedService`. It exposes the `ExecuteAsync`, but >`IHostedService` does not. A custom implementation of the `IHostedService` that is not a `BackgroundService` will only ever >have `StartAsync/StopAsync` methods called, as those are the only methods known by the runtime. However, if you extend >the `BackgroundService` the `ExecuteAsync` is called since the framework knows about that method. Does that make sense? >I'm going to close this as it's a non-issue. If you have more questions, please ask.

@IEvangelist Thanks for your explaination. I was just curious about the reason-which, as you pointed out ,the framework knows about `ExecuteAsync` in the `BackgroundService` (means at the same time only know about `StartAsync` and `StopAsync` in my implementation of the `IHostedService` ). Some more observation on `BackgroundService`, I noticed that the `ExecuteAsync`  can start even before the`StartAsync` finish. I can just put the calling code of   `ExecuteAsync` at the end of the `StartAsync` to get the time sequence I need(i.e. put init code in `StartAsync` and then start running logic in  `ExecuteAsync`).
