### ISSUE TITLE
Typo in CA1822

### ISSUE THREAD

**Issue by geologyrocks** [dotnet/docs#28108]
In the [Rule Description](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822#rule-description) paragraph there's a typo of emit (def: to radiate) where there should be omit (def: to exclude):

> "After you mark the methods as static, the compiler will emit nonvirtual call sites to these members. Emitting nonvirtual call sites will..."

Should read
> "After you mark the methods as static, the compiler will _omit_ nonvirtual call sites to these members. _Omitting_ nonvirtual call sites will..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2289e13-c2dd-ab47-7306-f67e618b4861
* Version Independent ID: 4458b59e-495d-6a5b-b479-fe69c5acf91e
* Content: [CA1822: Mark members as static (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1822.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1822.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by svick** [comment]
I think the text is correct as is. "Emit" here means something like "output" and is commonly used when describing producing IL (Intermediate Language), see for the example the System.Reflection.Emit namespace.

And the compiler does not omit the call site: if it did that, the method wouldn't be called. What the sentence is saying is that the call site produced by the compiler for the newly `static` method will be non-virtual.
