### ISSUE TITLE
How to construct a message with repeated field?

### ISSUE THREAD

**Issue by szmcdull** [dotnet/docs#28107]
[Enter feedback here]
How to construct a message with repeated field?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4613e1c-a501-fe42-c147-27d86b53cd42
* Version Independent ID: 32ad4204-56a0-d17d-1ff0-06a9cda0b7a3
* Content: [Repeated fields for lists and arrays - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-repeated)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-repeated.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/protobuf-repeated.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by erjain** [comment]
I am closing this issue as of now. Please feel free to reopen it, if needed.
