### ISSUE TITLE
CA1805 showing up as warning on .NET 6 project

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/docs#28106]
I appears that https://github.com/dotnet/roslyn-analyzers/pull/4353 switched CA1805 from "info" to "hidden" for .NET 5.

We have a .NET 6 project with `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`, and we're seeing CA1805 show up as warnings, not info or hidden. Is this expected?

Thanks 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035a543d-8333-1702-6a79-f7c791b84631
* Version Independent ID: c26352c7-948c-800e-5229-97c1b367ef65
* Content: [CA1805: Do not initialize unnecessarily (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1805)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1805.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1805.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @stephentoub
* Microsoft Alias: **stoub**

**Comment by stephentoub** [comment]
> Is this expected?

Yes.  "hidden" is the default value for the rule.  As per https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode, AllEnabledByDefault overrides that: "All rules are enabled as build warnings. You can selectively [opt out](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options) of individual rules to disable them."

**Comment by Bosch-Eli-Black** [comment]
Thanks, @stephentoub! 🙂

**Comment by Bosch-Eli-Black** [comment]
Just noticed that .NET 6 added two new warning levels: `Minimum` and `Recommended`. I think that should take care of the issue for us 🙂

Thanks again!
