### ISSUE TITLE
Figure and explanation mismatch

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#28119]
Here it is written: "WorkItem adds five members of its own. "
From the figure, it is obvious that it adds six members(ID, Title,jobLength,Description,Update(),and WorkItem() ). It may look obvious, but this minor correction can help a novice reader to avoid the confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa1d1b3c-640a-607f-ba63-dc957ed20a62
* Version Independent ID: 2183c2c7-5a9d-716e-34c3-b28d76a88b4c
* Content: [Inheritance](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/inheritance)
* Content Source: [docs/csharp/fundamentals/object-oriented/inheritance.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/inheritance.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Vaskaran 

I've opened #28126 to address this issue.
