### ISSUE TITLE
Simplify LINQ samples

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#28135]
This sample, and many of the other samples relying on the `Student` sample here, are needlessly complicated:

* Defining a protected `List<Student>` as the datasource for queries forces all the code samples to define an inheriting class, with a public method so the query can be run
* In spite of using the same base class, many of the samples have their own `Program` class with a `Main` method, only to show how to run the query.
* Some samples include instructions for creating a new console application using Visual Studio as part of the steps to reproduce the sample.

Since these samples don't have a project or solution file in any case, I propose the following:

* All the samples in this section should be included in a single project and folder
* The samples should show only the queries and necessary data classes; nothing else

I want to do this in order to be able to proceed with #28003.

ping @BillWagner 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f0fe50-ebf2-7fb8-6f51-2220ed9b65e6
* Version Independent ID: 19aad9f4-94cd-130b-2514-41de2ccff790
* Content: [Query a collection of objects (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-a-collection-of-objects)
* Content Source: [docs/csharp/linq/query-a-collection-of-objects.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/query-a-collection-of-objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the notes here @zspitz 

I like your proposal. Do you want me to assign this issue to you? If so, I'll watch for a PR.

**Comment by zspitz** [comment]
> Do you want me to assign this issue to you?

Yes, please.

**Comment by zspitz** [comment]
Having made an initial pass at this, I've come the conclusions described here: https://github.com/dotnet/docs/pull/28208#issuecomment-1037533765
