### ISSUE TITLE
project files list need to be updated in Docker topics

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs#2813]
In Visual Studio for Docker topic,
https://docs.microsoft.com/en-us/dotnet/core/docker/visual-studio-tools-for-docker

the list of added project files does not include this file:
docker-compose.ci.build.yml

In VS 2017 Update 3 Preview, the above file is present, and some of the other files mentioned are not added to the project.

**Comment by mairaw** [comment]
@JRAlexander can you look at this one? Thanks!

**Comment by JRAlexander** [comment]
Absolutely!

**Comment by JRAlexander** [comment]
This article is moving to the ASP.NET repo as part of the .NET Core 2.0 update. This issue will be resolved then.
