### ISSUE TITLE
Add documentation for and!/applicative computation expressions

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#28134]
F# 5 added support for applicative Computation Expressions via the `and!` syntax, and it should be documented here.

Useful Links:
* [preview announcement](https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-50#applicative-computation-expressions)
* [Language RFC](https://github.com/fsharp/fslang-design/blob/main/FSharp-5.0/FS-1063-support-letbang-andbang-for-applicative-functors.md)
* [Note from Don Syme about applicatives](https://github.com/dsyme/fsharp-presentations/blob/master/design-notes/rethinking-applicatives.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247c440d-b855-0df1-f2db-076cd3393a0b
* Version Independent ID: 1cbccd4d-1721-e14f-7546-8fa868c965b1
* Content: [Computation Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions)
* Content Source: [docs/fsharp/language-reference/computation-expressions.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/computation-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by mducharm** [comment]
Hello - I'm new to contributing, please let me know if there's anything I can improve.

**Comment by gewarren** [comment]
Fixed by #30447.
