### ISSUE TITLE
Deployment docs are broken because they are missing required concurrency attribute

### ISSUE THREAD

**Issue by jcamilli** [dotnet/docs#28144]
Thank you so much for the great article regarding GitHub Actions Deployment. It's the best I have seen so far as it adheres to the "build once, deploy many times" best practice.

A flaw though is that you have not mentioned concurrency and queuing which is a required for deployments. Allowing 2 concurrent deployments to the same environment would be a disaster. Another thing not mentioned is how to handle multiple pending and waiting deployments. These are the parts I am struggling with right now on my team. 

I am having trouble finding existing Github Actions best-practices that combines the build-once process with concurrency in deployment. If I have environments DEV and PROD and DEV has deployed commit 5, and PROD is waiting for approval to deploy commit 1, then there would be 5 workflow runs that have occurred and the first one is still waiting. Since concurrency is enabled, all the remaining 4 jobs will also be waiting for the prior jobs to complete. So in order to deploy commit 5 to PROD, you will have to go through each prior job and cancel them one by one. Alternatively, you can use the GitHub Actions cancel-in-progress concurrency property, but that introduces the problem of canceling prior jobs that I may yet want to deploy, before I even approve commit 5 for deployment to PROD. If a Job is waiting for approval, then cancel-in-progress cancels all prior jobs which is not the behavior I would expect. I would expect the cancellation to occur only after the approved job has started, not prior to approval.

Thank you so much.
Jared

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e60bfbe-2f6a-f21f-425b-f16275b9031b
* Version Independent ID: cd389cac-6016-fa61-f0f9-e466e35e0d17
* Content: [DevOps with .NET and GitHub Actions - Deploy a .NET Web App to Azure Web Apps](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-deploy)
* Content Source: [docs/architecture/devops-for-aspnet-developers/actions-deploy.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/actions-deploy.md)
* Product: **dotnet-architecture**
* GitHub Login: @colindembovsky
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @colindembovsky, can you suggest a resolution to this situation?

**Comment by jcamilli** [comment]
I was able to resolve this issue on my team by splitting my deployment into 2 jobs: 
1. Approval job where GH concurrency groups is not enabled. This job does nothing except for approve the subsequent job and allow it to proceed.
2. Subsequent job does the actual deployment. Concurrency groups is enabled on this job.

With the above mechanism, we work around the fact that GH considers a job that is waiting for a approval to be running. This "running" job will block all future jobs from running. With the jobs broken into 2 jobs, you do not have this problem because the 1 job does not have concurrency enabled and will not block future workflow runs.

**Comment by erjain** [comment]
This is great @jcamilli, Thanks for sharing the solution, it will surely help the community.
