### ISSUE TITLE
Are there cases where removing a parameter default value would be acceptable?

### ISSUE THREAD

**Issue by madelson** [dotnet/docs#28200]
RE:
> ❌ DISALLOWED: Changing the default value of a property, field, or parameter

Consider the following scenario:
```
public void Foo(int a = 1, int b = 2) { ... }
```

Let's say we want to add a new overload of `Foo` that also accepts `int c`. The following change should (in my understanding) be both binary-compatible and source-compatible:

```
public void Foo(int a, int b) => Foo(a, b, 3);
public void Foo(int a = 1, int b = 2, int c = 3) { ... }
```

(1) Would this be allowed in Microsoft's .NET libraries/runtime?
(2) If it is true that this change does not break either binary or source compatibility, could we add a note about that (I'm happy to file a PR) to this rule for the benefit of those who reference this document to understand breaking changes for .NET generally?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b482b0-6dd1-42de-5389-5b0b47823402
* Version Independent ID: 79a4adc9-b2c9-68b7-669e-2bd8d2d44faf
* Content: [Types of breaking changes - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/)
* Content Source: [docs/core/compatibility/index.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@stephentoub Could you answer this question or suggest someone that can?

**Comment by stephentoub** [comment]
cc: @terrajobst, @bartonjs

**Comment by bartonjs** [comment]
That change would be allowed, yes.  In a very technical sense it has removed a default from a parameter, but at the same time it didn't :smile:.

Relevant things from _Framework Design Guidelines, 3rd Edition_:

> ## 5.1 Member Overloading
> ...
> DO NOT change the default value for a parameter once it has been publicly released.
>
> DO move all default parameters to the new, longer overload when adding optional parameters to an existing method.

> #### D.11.17 Changing a Parameter from Optional to Required
> ...
> The .NET BCL team considers this an acceptable breaking change when done as part of “moving” default values to a new overload. Otherwise, it is an unacceptable breaking change.

So, the terminology used in the 3rd edition update for this pattern is "move" (vs remove).  But a clarifying sub-bullet wouldn't hurt.

**Comment by terrajobst** [comment]
@madelson

Another way to think about this: removing a default parameter is a source breaking change, not a runtime breaking change as the compiler has "burned" the default values into the call sites (the runtime has no notion of default values). By adding an overload with corresponding defaults you addressed the source breaking change which is why it's OK.
