### ISSUE TITLE
Missing half of the snipet code

### ISSUE THREAD

**Issue by felipeschneider88** [dotnet/docs#28203]
More than half of the code snippets are missing or incomplete. For example this one:
![image](https://user-images.githubusercontent.com/32371298/153333460-fe135c9b-8c76-4477-9533-a26832e37a48.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d03435-cc6c-1123-a86c-d5c3eacc24bd
* Version Independent ID: 460afd2b-383d-7b90-6804-4b900c3bc9b2
* Content: [Tutorial: Forecast bike rental demand - time series - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting)
* Content Source: [docs/machine-learning/tutorials/time-series-demand-forecasting.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/time-series-demand-forecasting.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @felipeschneider88  thanks for raising this issue. Updates have been made in #28516 and the changes should be reflected shorty.
