### ISSUE TITLE
On this page, where there is a NULL check on match? 

### ISSUE THREAD

**Issue by pingzhuang** [dotnet/docs#28215]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eede22c-dda8-85ec-d896-0a03b31a0116
* Version Independent ID: 5fa25041-c976-7751-07da-60aab9e97ae5
* Content: [Results - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/results)
* Content Source: [docs/fsharp/language-reference/results.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/results.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Hi :wave: @pingzhuang 

In F#, a `type` cannot be set to `null`, unless the `AllowNullLiteral` attribute is applied to that type. That means there's no need to check the result against null. The pattern matching expressions test each property of the type against null.

I'll close this as an answered question.
