### ISSUE TITLE
.NET 6 incorrect return of IndexOf

### ISSUE THREAD

**Issue by jonadv** [dotnet/docs#28218]
On [this](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api#behavioral-differences) page it sais:
 - In previous versions of .NET on Windows, the snippet prints 6.
 - In .NET 5 and later versions on Windows 19H1 and later versions, the snippet prints -1.

but when I run that code snippet, in a new .NET 6 project in Visual Studio 2022, it still returns 6! 

    string s = "Hello\r\nworld!";
    int idx = s.IndexOf("\n");
    Console.WriteLine(idx);

When we create a project with .NET 5, it does return -1. But with NET 6 (a version later then 5) it returns 6! What is going on?

![image](https://user-images.githubusercontent.com/10421216/153603332-d6957baa-ed34-4590-8825-491039e4b629.png)

Not sure if helpful:
![image](https://user-images.githubusercontent.com/10421216/153603507-11a0d28e-2731-44f0-9733-2a1073a1f62b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13ed30d9-9cee-e81a-9b94-702c37569d35
* Version Independent ID: 0fe8d49e-09ec-0164-7dd7-671299358deb
* Content: [Breaking change: Globalization APIs use ICU libraries on Windows - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api)
* Content Source: [docs/core/compatibility/globalization/5.0/icu-globalization-api.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/globalization/5.0/icu-globalization-api.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by safern** [comment]
In .NET 5 we introduced a change where we would use ICU as the globalization engine for .NET if we were running on Windows 19H1 or newer. That changed, cause to break the scenario described here, where `IndexOf("\n")` was returning `-1` when a string contained `\r\n`. Since this was a pretty impactful change for Windows strings (see more here: https://github.com/dotnet/runtime/issues/43736).

This was fixed by @tarekgh in .NET 6 on: https://github.com/dotnet/runtime/pull/57078

**Comment by tarekgh** [comment]
@safern is correct. 

I am closing this. Feel free to ask any questions if you have any.

**Comment by jonadv** [comment]
@tarekgh @safern 

Good to know something at the basics changed!!!... I wish I read that earlier, for example on the special page about the [differences in string behaviour as of .NET 5 **_PLUS_**](https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus). Please add the expected output with .NET 6. I spent days on this, thinking that such an article is surely correct.

"we would use ICU as the globalization engine for .NET if we were running on Windows 19H1 or newer"
- how can i actually check if my visual studio project is using ICU? I tried with the IndexOf method, as written in the example of above article. And checked local directories. As far as I understood I just have to assume ICU is used because the ICU dll files are just in the system32 folder and my version of windows is later then 19H1. Ofcourse there is the UseNls switch, but still often I'm not sure if I insterted that property in the correct place or if another config-somewhere is overwriting that. 

-" That changed, cause "  what changed exactly?  "if we were running on Windows 19H1 or newer" you mean automatically using ICU with a newer version of windows, or you still do that and "that changed, cause" refers to the general ICU to NLS change. Or you mean in .NET 6 we only changed how that IndexOf method worked and only with that linebreak.

**Comment by jonadv** [comment]
I have created a new issue for updating the docs https://github.com/dotnet/docs/issues/28248

**Comment by tarekgh** [comment]
> Please add the expected output with .NET 6. I spent days on this, thinking that such an article is surely correct.

Sorry about that. What we did in .NET 6.0 was the community ask to go back to the old behavior. We didn't try to document that as .NET 5.0 is going to be out of support soon. But I can see the document you pointed at https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus and understand how this can be confusing. 

>  How to properly check if running code is using ICU?

Please look at the solution in the comment https://github.com/dotnet/runtime/issues/62930#issuecomment-996384514

> what changed exactly? "if we were running on Windows 19H1 or newer" you mean automatically using ICU with a newer version of windows, or you still do that and "that changed, cause" refers to the general ICU to NLS change. Or you mean in .NET 6 we only changed how that IndexOf method worked and only with that linebreak.

In .NET 6.0 we have changed only the IndexOf behavior with the `\n`. Everything else should be same.

> I have created a new issue for updating the docs https://github.com/dotnet/docs/issues/28248

Thanks for doing that. Are you interested in submitting a PR to fix that?

**Comment by jonadv** [comment]
Hi @tarekgh 

Thank you for explaining. I have created these pull requests 
- https://github.com/dotnet/docs/pull/28250
- https://github.com/dotnet/docs/pull/28269

But please have a look at them and suggest any further changes, as I dont think my suggested changes cover it fully.
