### ISSUE TITLE
Misleading information

### ISSUE THREAD

**Issue by TheAxeManGa** [dotnet/docs#28217]
This page states:

“In .NET Core, the process for exposing your .NET objects to COM has been significantly streamlined in comparison to .NET Framework.”

Which is an absolute **LIE**. There was nothing easier on the planet than to check a couple of boxes in Visual Studio to expose your DLL to COM and have it create TLBs.

Can we expect better documentation or automation to expose the DLL to COM?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0842844-005f-5004-022d-fce7a82daff8
* Version Independent ID: 88ddeba8-3b31-95f4-26b2-4a12a7313b47
* Content: [Exposing .NET Core components to COM](https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com)
* Content Source: [docs/core/native-interop/expose-components-to-com.md](https://github.com/dotnet/docs/blob/main/docs/core/native-interop/expose-components-to-com.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by gewarren** [comment]
@TheAxeManGa I've opened a pull request to remove the verbiage that the process is more streamlined in .NET Core.

There's currently no tool for exporting .NET Core/.NET 5+ assemblies to TLBs, however it is being considered for a future release.
