### ISSUE TITLE
Undocumented breaking change since .NET Core 3.x: Formatting DateTime values with "zzz" 

### ISSUE THREAD

**Issue by Jehoel** [dotnet/docs#28225]
**Issue description**

Sometime around .NET Core 3.x, the behaviour of the `zzz` custom Date-and-Time formatting token changed but this was not/is not documented.

Previously - and in .NET Framework 4.x, using the `zzz` specifier to format a `DateTime` (not `DateTimeOffset`) would always result in the Local Computer clock's UTC offset, regardless of `DateTime.Kind`. This is the current documented behavior:

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#zzzSpecifier

> With [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) values, the "zzz" custom format specifier represents the signed offset of the local operating system's time zone from UTC, measured in hours and minutes. It doesn't reflect the value of an instance's [DateTime.Kind](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.kind) property. For this reason, the "zzz" format specifier is not recommended for use with [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) values.

However, in .NET Core 3.1 and later (including .NET 5, .NET 6, etc), the behaviour was changed to now start respecting `DateTime.Kind`.

Here's a screenshot showing identical programs demonstrating  the change between .NET Framework 4.8 (in Linqpad 5) and .NET 6 (in Linqpad 7):

```
DateTime dtUtc         = new DateTime( ticks: 637802866463298955, kind: DateTimeKind.Utc         );
DateTime dtUnspecified = new DateTime( ticks: 637802866463298955, kind: DateTimeKind.Unspecified );
DateTime dtLocal       = new DateTime( ticks: 637802866463298955, kind: DateTimeKind.Local       );

DateTime[] values = new[] { dtUtc, dtUnspecified, dtLocal };

foreach( DateTime v in values )
{
	v.ToString( "yyyy-MM-dd'T'HH':'mm':'sszzz" ).Dump( v.Kind.ToString() );
	v.ToString( "yyyy-MM-dd'T'HH':'mm':'ssK" ).Dump( v.Kind.ToString() );
}
```

![image](https://user-images.githubusercontent.com/1693078/153733085-3478271b-6d92-409b-8db6-aa948d997d06.png)

To my surprise, only a few people have noticed it so far: I've only seen this StackOverflow QA from 2020 talking about it: https://stackoverflow.com/questions/65004352/c-sharp-datetime-tostring-with-zzz-breaks-in-dotnet-framework-but-not-in-dotnet

The StackOverflow post also mentions that the text of the Visual Studio MDA for date+time formats is wrong too:

> 'A UTC DateTime is being converted to text in a format that is only correct for local times. This can happen when calling DateTime.ToString using the 'z' format specifier, which will include a local time zone offset in the output. In that case, either use the 'Z' format specifier, which designates a UTC time, or use the 'o' format string, which is the recommended way to persist a DateTime in text. 

...but I'm unsure where to file a bug for MDA help text.

Of note, the reknown [Jon Skeet chimed in](https://stackoverflow.com/a/65004441/159145):

> Note that .NET Core (and .NET 5.0) apparently doesn't behave as documented. While you could argue it's "fixed" in .NET Core, I'd suggest that **behaving in an undocumented way is a bug in itself**, and one that could make code migration harder than expected.

------------------

I was going to submit a quick PR, but as this involves documenting a breaking change I assume it means it's more complicated than adding a sentence of two buried in [that paragraph](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#zzzSpecifier)

**Target framework**

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by gewarren** [comment]
@tarekgh Do you know when this formatting change was introduced in .NET Core? Also, should I create a breaking change doc for it?

**Comment by tarekgh** [comment]
@gewarren 

The new behavior exists in all .NET Core versions (even existed in coreclr which shipped to support like .NET Native which existed even before .NET Core 1.0). The issue https://github.com/dotnet/runtime/issues/7923 is a good reference for the discussion around this. 

> Also, should I create a breaking change doc for it?

I think it would be enough if we added a section in https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#zzzSpecifier telling about the .NET Core behavior and possibly fix the comments on the sample code.
