### ISSUE TITLE
Source generation support in ASP.NET Core - does this really use the Source Generator?

### ISSUE THREAD

**Issue by bp74** [dotnet/docs#28222]
The sample shows this code:

```
[JsonSerializable(typeof(WeatherForecast[]))]
internal partial class MyJsonContext : JsonSerializerContext { }
```
```
services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.AddContext<MyJsonContext>());
```

I tried my best to debug it, but it's really hard. My understanding is that the source generator for "MyJsonContext" produces code which does not use the "PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase". On the other hand the "options.JsonSerializerOptions" in a WebApi project uses camel case as a default. Therefore the application would not use the serializer from the source generator, but falls back to the standard serialization.

It should work when you specify the PropertyNamingPolicy like this:

```
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(WeatherForecast[]))]
internal partial class MyJsonContext : JsonSerializerContext { }
```

Is there any way to know if the serializer from the source generator is actually used in a WebApi, other than doing performance tests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee53c3dc-df79-82ef-ce25-3233ff292c55
* Version Independent ID: 558903e9-8173-464e-ff8b-7744419ad7e4
* Content: [How to use source generation in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation?pivots=dotnet-6-0#source-generation-support-in-aspnet-core)
* Content Source: [docs/standard/serialization/system-text-json-source-generation.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-source-generation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by davhdavh** [comment]
You need to return IActionResult from your webapi, since it uses a different serializer if you return the object directly...
https://github.com/dotnet/aspnetcore/issues/39628
Or, you need to https://github.com/dotnet/aspnetcore/issues/38720#issuecomment-1017156458 do this to make it work in web.
IMHO it is total FUBAR at the moment

**Comment by bp74** [comment]
Looks like it was not tested at all :)

**Comment by bp74** [comment]
I used this workaround, it provides most insight if the SourceGenerator is used or not:

```
    [JsonSerializable(typeof(WeatherForecast))]
    internal partial class MyJsonContext : JsonSerializerContext { }
```
```
    class WeatherForecastJsonConverter : JsonConverter<WeatherForecast>
    {
        public override WeatherForecast Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            JsonSerializer.Deserialize<WeatherForecast>(ref reader, MyJsonContext.Default.WeatherForecast);

        public override void Write(Utf8JsonWriter writer, WeatherForecast value, JsonSerializerOptions options) =>
            JsonSerializer.Serialize(value, MyJsonContext.Default.WeatherForecast);
    }
```

And finally don't use AddContext but instead register the custom WeatherForecastJsonConverter
```    
            services
                .AddControllers()
                .AddJsonOptions(options =>
                {
                    // options.JsonSerializerOptions.AddContext<BettingSerializerContext>();
                    options.JsonSerializerOptions.Converters.Add(new WeatherForecastJsonConverter());
                });    
```

**Comment by tdykstra** [comment]
Thanks for contacting us. It looks like you found an answer to your question. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
