### ISSUE TITLE
Use the old program style: Add info on converting top-level statements to explicit entry point

### ISSUE THREAD

**Issue by tonysneed** [dotnet/docs#28223]
In the section, [Use the old program style](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-old-program-style-in-visual-studio), add information on how to convert an existing .NET 6 console or web app to use an explicit entry point instead of top-level statements. For example, in a .NET 6 console app you can simply replace the code in Program.cs with the following:

```csharp
namespace MyConsoleApp;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}
```

An example should also be included for adding an explicit entry point to a web app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# template changes in .NET 6 - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion, but this article is about creating new projects, and it already shows the old template code near the top of the article. Web app templates are covered in the ASP.NET Core documentation.

**Comment by tonysneed** [comment]
@tdykstra Is there another place in the docs which covers converting an existing .NET 6 console or web app to use an explicit entry point?

By way of background, the question came up for me with an integration tests that needed to reference more than one web project. Because `Program` now exists in the global namespace, it caused an ambiguous reference in the test project.

**Comment by adegeo** [comment]
@tdykstra this may be a missing scenario, approaching it from the point of view that @tonysneed is indicating. In general the requests have been from the context of "restore the old template" which the article covers. But the context here, I believe, is a missing scenario: "How do I specify an entry point for an app"

This would include:

- Remove the top-level statements from the code
- Create a namespace + class
- Add a static method named Main

**Comment by tdykstra** [comment]
That doesn't seem to fit the context of an article that is specifically about project creation using the template.  Maybe it would fit in https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#implicit-entry-point-method -- we could add "if you need an explicit entry point" text.  @BillWagner what do you think?
