### ISSUE TITLE
Method overloading issue with top-level statements

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#28231]
Consider the following code(I am using top-level statements): 
```cs
Console.WriteLine("Testing method overloading .");
Show(5);
Show();
static void Show(int a)
{
    Console.WriteLine("I am inside Show(int a) now.");
}
static void Show()
{
    Console.WriteLine("I am inside Show() now.");
}
...

It raises the following errors:
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'a' of 'Show(int)'
Error	CS0128	A local variable or function named 'Show' is already defined in this scope

But the following code works in older versions of C#:
```cs
namespace HelloWorld
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Testing method overloading.");   
      Show(5);
      Show();
    }
    static void Show(int a)
    {
      Console.WriteLine("I am inside Show(int a) now.");
    }
   static void Show()
    {
     Console.WriteLine("I am inside Show() now.");
    }
  }

}
```
 and it can generate the following output:
Testing method overloading.
I am inside Show(int a) now.
I am inside Show() now.

--Does it mean that top-level statements do not support method overloading in a context like this? Or, Have I missed something basic? Any thought will be appreciated.
Regards,
Vaskaran

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2939b6-ad9e-4116-c805-8f19ed994c31
* Version Independent ID: ad23d124-a491-2b4f-3c51-0ed5d38d7eba
* Content: [Top-level statements - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements)
* Content Source: [docs/csharp/whats-new/tutorials/top-level-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/top-level-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 194282](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194282)

**Comment by svick** [comment]
> Does it mean that top-level statements do not support method overloading in a context like this?

Yes, it does. That's because those are technically not methods, but local functions. So your first code would be the equivalent of the following, which also doesn't compile, with the same errors:

```c#
class Program
{
    static void Main()
    {
        Console.WriteLine("Testing method overloading .");
        Show(5);
        Show();
        static void Show(int a)
        {
            Console.WriteLine("I am inside Show(int a) now.");
        }
        static void Show()
        {
            Console.WriteLine("I am inside Show() now.");
        }
    }
}
```

If you want method overloading, you will have to use a class.

**Comment by Vaskaran** [comment]
> > Does it mean that top-level statements do not support method overloading in a context like this?
> 
> Yes, it does. That's because those are technically not methods, but local functions. So your first code would be the equivalent of the following, which also doesn't compile, with the same errors:
> 
> ```cs
> class Program
> {
>     static void Main()
>     {
>         Console.WriteLine("Testing method overloading .");
>         Show(5);
>         Show();
>         static void Show(int a)
>         {
>             Console.WriteLine("I am inside Show(int a) now.");
>         }
>         static void Show()
>         {
>             Console.WriteLine("I am inside Show() now.");
>         }
>     }
> }
> ```
> 
> If you want method overloading, you will have to use a class.

Thank you for the explanation. Just one more question:
I can see that .NET 5 can run the following code:

using System;

namespace Testing_Overloading
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Testing method overloading .");
            Show(5);
            Show();
        }
        static void Show(int a)
        {
            Console.WriteLine("I am inside Show(int a) now.");
        }

        static void Show()
        {
            Console.WriteLine("I am inside Show() now.");
        }

    }
}

If I want to use top-level statements(.NET 6), how should I write an equivalent code?

**Comment by BillWagner** [comment]
@Vaskaran There's discussion around [speakable names for top level statements](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-07-26.md#speakable-names-for-top-level-statements) that will provide this capability. I don't think it has shipped in a public preview yet. 

We'll add information on this scenario when it's finalized and has shipped. I'll keep this open until then.
