### ISSUE TITLE
No help whatsoever

### ISSUE THREAD

**Issue by Alan-Steadman** [dotnet/docs#28242]
As much use as a fart in a space suit.  Would be much more helpful if I could COPY the text of the error message from visual studio then search for it using GOOGLE to find a website that IS helpful (!= docs.microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8831b6c2-8b55-3e22-b2f4-d6eed52e9ea0
* Version Independent ID: 5bf2b97e-b22a-4846-3423-34e3c68b5894
* Content: [Compiler Error CS0144](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0144?f1url=%3FappId%3Droslyn%26k%3Dk(CS0144))
* Content Source: [docs/csharp/misc/cs0144.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0144.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @Alan-Steadman 

This article does need improvement. There are two common ways to address this error (all should be added to this article):

1. Change the type declaration so it's not abstract: Either remove the `abstract` keyword from the class declaration, or change the type from an `interface` to a `class`.
2. Create a type that's derived from the `abstract class` or that implements the `interface`. 

I've added this to our list to address, and added the "up for grabs" label if anyone wants to submit a PR before we get to this change.

**Comment by Alan-Steadman** [comment]
Hi Bill,

Thanks for your swift reply, and it is fantastic and utterly astounding that Microsoft are actually paying attention to and even going so far as responding to feedback.  This hasn't happened in the last 25 years that I've been an MS developer (vb.net now learning c#).  I am truly grateful.

Alan

**Comment by rafcon-dev** [comment]
@BillWagner I recon this issue should be closed as the changes have been added to the docs by SmallMistake, right?

**Comment by BillWagner** [comment]
Thanks @rafcon-dev 

Yes, this can be closed. It looks like the GitHub automation didn't close it due to the newline in the comment.
