### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by Alan-Steadman** [dotnet/docs#28244]
See page I'm sending feedback on.  Problem should be blindingly obvious.
CS0854
And PLEASE allow me to copy the error text from visual studio so I can GOOGLE IT FFS, instead of being directed to utterly sh!t microsoft docs pages, many of which don't even exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS0854))
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Alan-Steadman** [comment]
... I'm a noob trying to learn C# and docs.microsoft.com are a real drag on that process.

**Comment by adegeo** [comment]
Hello. How was the error presented to you? I would think it shows in the errors list and you can select the item and use CTRL+C to copy the text and paste it into a search engine.

@gewarren do we have a list of compiler errors "to be" documented?

**Comment by BillWagner** [comment]
@Alan-Steadman @adegeo 

There are a number of issues where people have landed on [this page](https://github.com/dotnet/docs/issues?utf8=%E2%9C%93&q=%2258a19505-ac46-c5c8-12cc-fe87b6aa18a7%22&in=body). The source for the page has a list of errors and warnings that [haven't been added.](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md?plain=1#L6-L736). (It's a lot). I'm working on a plan to provide articles that help with different "types" of errors and warnings. [This article](https://docs.microsoft.com/dotnet/csharp/nullable-warnings) is in the direction I think will work.

One other note @Alan-Steadman I understand your frustration trying to learn a new programming language. We are working to help, and to improve our docs. Your issues are valid, and we will address them. You may want to consider how you express those issues in a public forum.

**Comment by Alan-Steadman** [comment]
Thanks both.

The errors being presented as squiggly underlines as I'm typing.  Hovering them gives the additional info (description and error number) and a link to the page with no info on it.  The text in the popup isn't copyable, so I was hovering it in the background while retyping it into notepad in the foreground in order to copy paste the text into google (not bing).  However, I guess it would have then created an error item in the errors pane that I could copy from.

Apologies for the way I'd expressed the issues, I've never before experienced Microsoft addressing issues previously.   Until very recently whereby feedback is now on Github, the standard response for years and years was "closed cannot reproduce", "not enough info" and "we are closing this feedback system"

My most recent experience is this one.  Two years old, easy to reproduce.  Different team I'm sure.
https://github.com/microsoft/calculator/issues/226

**Comment by adegeo** [comment]
I guess I'll close this issue as there isn't anything we can do to address this specific instance. As noted, the undocumented issue codes are in progress, there are a lot of them, but they're getting documented as time goes on. If you see a reason for this issue to be reopened, please do so. Cheers!
