### ISSUE TITLE
Do we have to manually find transitive dependencies?

### ISSUE THREAD

**Issue by shelbyxu** [dotnet/docs#28254]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22484a57-f15f-8d0c-6f18-ccc96a5b7215
* Version Independent ID: 90ddffec-4bfd-d7ea-6923-567ea6683c47
* Content: [dotnet list reference command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-reference)
* Content Source: [docs/core/tools/dotnet-list-reference.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-list-reference.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
`dotnet list package` has an `--include-transitive` option, but `dotnet list reference` does not.
