### ISSUE TITLE
Using .. in DOS device path works in cmd.exe even though shouldn't according to documentation

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#28279]
---
**Issue moved from MicrosoftDocs/feedback#3752**
- Please respond to @Wallby.

---

_From @Wallby on Wednesday, February 16, 2022 6:18:15 PM_

**Describe the bug**
At https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats there is text.. "_DOS device paths are fully qualified by definition. Relative directory segments (. and ..) are not allowed._". However, in cmd.exe the following works..
```
\\.\..\UNC\..\UNC\Maarten-PC\c$\Windows\System32\..\notepad.exe
\\.\C:\Windows\..\Windows\notepad.exe
```

**To Reproduce**
See description

**Expected behavior**
Not sure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/file-path-formats.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3752**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, February 16, 2022 6:18:16 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Wallby** [comment]
E.g. `\\.\C:\Windows\.\notepad.exe` works too so both . and .. work in a DOS device path.

**Comment by adegeo** [comment]
Hi @Wallby your paths are still fully qualified. A relative path segement (`.\` and `..\` based on the concept of a current directory. As soon as you start with `\\` the `.\` and `..\` are just being used to go up/down the fully qualified path.

I'll clarify that paragraph to indicate it means you cannot start with a relative path segement.
