### ISSUE TITLE
Document AssemblyLoadContext changes for C++/CLI

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#28276]
https://github.com/dotnet/runtime/issues/56391 describes an issue that customers using C++/CLI may encounter when migrating from .NET Framework to .NET 5. This has come up in a few issues and would be good to have tracked in this document, since this is trying to be a one-stop shop for breaking changes.

The rationale for the change is captured in [this comment](https://github.com/dotnet/runtime/issues/56391#issuecomment-887853318) and can be used for motivation.

Additional discussion on this topic can be found [here](https://github.com/dotnet/runtime/issues/61105), and [this comment](https://github.com/dotnet/runtime/issues/61105#issuecomment-1040852501) links to a community-authored sample of the suggested resolution.

For a permanent solution, [this API proposal](https://github.com/dotnet/runtime/issues/62754) would be worth following.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b64784-415c-7d00-3c44-aa3de496a54f
* Version Independent ID: 3d9c2faa-a7d7-ee5f-6f3c-87da5782a5cb
* Content: [Breaking changes - .NET Framework to .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core)
* Content Source: [docs/core/compatibility/fx-core.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/fx-core.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@baronfel Would this be a better place to note the issue? https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli#known-issues

Also, it sounds like this problem will go away with .NET 7 based on https://github.com/dotnet/runtime/issues/61105#issuecomment-1073417993.

**Comment by baronfel** [comment]
Oh, that's great! So we'd need to note this for .net6.0 known-issues, but not .net7? I'm perfectly happy with that.
