### ISSUE TITLE
Incorrect information for System.Net.Dns

### ISSUE THREAD

**Issue by pedro-w** [dotnet/docs#2827]
# Incorrect information for System.Net.Dns

In several places in `docs/xml/System.Net/Dns.xml`, it mentions that passing an empty string for the host name will return the IPv4 address of the local host. Sometimes it mentions Windows Server 2003 as an exception, sometimes not. 

I believe this information is incorrect/outdated. On my Windows 10 system, .NET 4.6.2,  I always get IPv6 addresses as well as IPv4 addresses. I don't know what the situation is for other versions of Windows.

**Comment by mairaw** [comment]
@msatranjr can you take a look at this issue? Thanks.

**Comment by pedro-w** [comment]
Thanks for the swift response! These are some of the relevant locations; there may be more that I haven't come across.

https://github.com/dotnet/docs/blob/master/xml/System.Net/Dns.xml#L87
https://github.com/dotnet/docs/blob/master/xml/System.Net/Dns.xml#L396
https://github.com/dotnet/docs/blob/master/xml/System.Net/Dns.xml#L599
https://github.com/dotnet/docs/blob/master/xml/System.Net/Dns.xml#L942

**Comment by mairaw** [comment]
@stevewhims can you look at this issue? Thanks!

**Comment by stevewhims** [comment]
Yes, I'll take a look. :)
