### ISSUE TITLE
Installing dotnet 6 on Linux/Ubuntu/WSL2

### ISSUE THREAD

**Issue by sliderhouserules** [dotnet/docs#28271]
I'm installing dotnet 6 SDK on Linux/Ubuntu/WSL2 and getting the error 

> E: Unable to locate package dotnet-sdk-6.0.1
> E: Couldn't find any package by glob 'dotnet-sdk-6.0.1'
> E: Couldn't find any package by regex 'dotnet-sdk-6.0.1'

This is the default install of Linux on Ubuntu. How could I possibly have the wrong setup to install this with apt automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#apt-troubleshooting)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@sliderhouserules Hi there, sorry for the delay in getting back to you. I'm unsure why it's not working for you. Can you share more information? Please provide all the command you ran to import the package repo and then to install the package.
