### ISSUE TITLE
Add explanatory text from samples to associated article

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#28273]
See https://github.com/dotnet/docs/pull/28227#discussion_r807202146

@zspitz did a lot of awesome work on our LINQ samples. That PR added useful explanatory comments to the samples. Those comments aren't in the associated article, so they won't be localized for different regions.

We should add that text to the article where appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eacf9e34-5e7f-37f4-24ad-1dd66fbabb9f
* Version Independent ID: 8ffa29aa-af74-9f39-7e6c-04fd46538177
* Content: [Group results by contiguous keys (LINQ in C#)](https://review.docs.microsoft.com/en-us/dotnet/csharp/linq/group-results-by-contiguous-keys?branch=pr-en-us-28227)
* Content Source: [docs/csharp/linq/group-results-by-contiguous-keys.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/group-results-by-contiguous-keys.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BartoszKlonowski** [comment]
I can spend some time and deliver the PR sometime this week (10.30 - 11.05).
@BillWagner / @IEvangelist  Please assign me if it's possible, just so that I have it 🙏
