### ISSUE TITLE
dotnet-trace report command missing

### ISSUE THREAD

**Issue by IGx89** [dotnet/docs#28274]
This page mentions a `dotnet-trace report` command, but it appears to be missing in .NET 6. I've tried on both Windows and Linux and dotnet-trace reports that the `report` command doesn't exist

```
C:\Users\xxx>dotnet-trace --version
6.0.257301+27172ce4d05e8a3b0ffdefd65f073d40a1b1fe54

C:\Users\xxx>dotnet-trace report
Required command was not provided.
Unrecognized command or argument 'report'

Usage:
  dotnet-trace [options] [command]

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  collect                     Collects a diagnostic trace from a currently running process or launch a child process
                              and trace it. Append -- to the collect command to instruct the tool to run a command and
                              trace it immediately. When tracing a child process, the exit code of dotnet-trace shall
                              be that of the traced process unless the trace process encounters an error.
  ps                          Lists the dotnet processes that traces can be collected
  list-profiles               Lists pre-built tracing profiles with a description of what providers and filters are in
                              each profile
  convert <input-filename>    Converts traces to alternate formats for use with alternate trace analysis tools. Can
                              only convert from the nettrace format [default: default]

```

Did it get removed in .NET 6? If so it would be helpful to note in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57216dad-d87d-eeef-adc8-82bfe4251343
* Version Independent ID: 3e7ab61f-5a06-b92c-5c74-0fae43adb35e
* Content: [dotnet-trace diagnostic tool - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-report)
* Content Source: [docs/core/diagnostics/dotnet-trace.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dotnet-trace.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
