### ISSUE TITLE
Missing atomic delivery of current state with subscription

### ISSUE THREAD

**Issue by markusschaber** [dotnet/docs#28299]
There are some use cases where the observer needs to get the current state, as well as subscribe to changes.

As this are two independent calls to the provider, there's a race condition where, depending on the order of the calls, the observer may either miss notifications, or get notifications which are already outdated regarding the "current state" he fetched.

The observer pattern, as provided by the `[System.IObservable<T>](https://docs.microsoft.com/en-us/dotnet/api/system.iobservable-1)` class, does not provide a nice solution for this problem.

One solution is to provide an alternative `Subscribe()`-Method which returns a tuple containing both the current state and the `IDisposable` used to unsubscribe.

Maybe some hints to this or other solutions to that problem could be added to the article (or the "best practices" article next to it)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8b6ec6-3773-879a-00e9-4bf113b9f362
* Version Independent ID: 5c46289d-8473-623f-eb42-8bda01c30c63
* Content: [Observer Design Pattern](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern)
* Content Source: [docs/standard/events/observer-design-pattern.md](https://github.com/dotnet/docs/blob/main/docs/standard/events/observer-design-pattern.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by markusschaber** [comment]
Hmm. As the `IObserver<T>` actually stays the same, and the role of `IObservable<T>` is a minor one in the pattern, I'm not sure whether it really is an API change, or actually just about documenting an alternative way of offering the pattern. I'll ask in the https://gitter.im/dotnet/coreclr gitter channel whether this is worth a runtime issue.

**Comment by HaloFour** [comment]
I'd expect any state to be broadcast to the `IObserver<T>`, not returned from the `IObservable<T>`.  Most publishers have no concept of "current state", they are "cold" and don't start emitting values until the subscriber connects.  In the case of a "hot" publisher, which it sounds like you are working with, I would expect the publisher to emit the last signal to the observer on subscription.  If the publisher itself doesn't support that there should be a reactive operator that will buffer the last received signal and broadcast that to observers as they subscribe.  IMO making a change to flow signals outside of that would break the reactive streaming pattern.

**Comment by markusschaber** [comment]
Ok, I'm somehow convinced now that the current state should be returned via event to the `IObserver<T>`.
