### ISSUE TITLE
Documentation for half data type is missing

### ISSUE THREAD

**Issue by stonstad** [dotnet/docs#28308]
Documentation for half data type is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe245daf-f6b8-1100-3786-b15feefe137b
* Version Independent ID: c031bb57-cb5b-f953-4711-a0ed054dab3f
* Content: [Built-in types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types)
* Content Source: [docs/csharp/language-reference/builtin-types/built-in-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/built-in-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @tannergooding 

Are we planning to add a new keyword for the `System.Half` type?

**Comment by stonstad** [comment]
I didn’t realize half is not a new intrinsic type.   Never mind and thank you!

(https://devblogs.microsoft.com/dotnet/introducing-the-half-type/)
