### ISSUE TITLE
Reason for CA1727?

### ISSUE THREAD

**Issue by Rast1234** [dotnet/docs#28307]
Hello. I can't find any reason behind CA1727 rule. Can someone explain why the PascalCase is needed? In my scenario, structured logs go to JSON and it's fine to have keys named in camelCase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c38d31-bb12-cbd0-6016-aaae358acc17
* Version Independent ID: 8394f838-b534-a562-577b-6b30ebc7e1cf
* Content: [CA1727: Use PascalCase for named placeholders (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1727)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1727.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1727.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@maryamariyan Can you help with this question about why PascalCase is required?

**Comment by maryamariyan** [comment]
mainly as best practice (merely a recommendation) with structured logging we'd want to have arguments in the message template pascal case rather than camel case. seems like this is in accordance with serilog recommendations as well https://github.com/serilog/serilog/wiki/Writing-Log-Events

**Comment by maryamariyan** [comment]
closing as answered.
