### ISSUE TITLE
Do not recommend using Stringbuilder

### ISSUE THREAD

**Issue by Symbai** [dotnet/docs#28315]
I was browsing [this page](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#string-parameters) which strongly recommends to NOT use `StringBuilder`. Then few words later it says:

`For more information on string marshaling, see` [Default Marshaling for Strings](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings)

This is where I went because I wanted to see how I can change my code to NOT using `StringBuilder`. However it doesn't show alternatives to `StringBuilder` instead it also [recommends](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings#fixed-length-string-buffers) using `StringBuilder` while the best practices recommends NOT using `StringBuilder`. This is totally confusing.

I don't know 100% which one is correct but I assume that the `best practices` is. Because this is where the .NET runtime repo team always redirect people to. If that's true then this example here needs to get updated by following this best practices and showing an example which not uses `StringBuilder`. Especially because there is a link set on `best practices` to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25d350b8-a514-6c13-a091-0952a8fc0610
* Version Independent ID: 3ee9bbfd-2060-d97f-c2f1-12867899034a
* Content: [Default Marshaling for Strings - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings)
* Content Source: [docs/framework/interop/default-marshaling-for-strings.md](https://github.com/dotnet/docs/blob/main/docs/framework/interop/default-marshaling-for-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by Symbai** [comment]
Well now its just bouncing developers around the pages. I was more hoping that you also fix/update the example. Because right now it only says "avoid using stringbuilder" everywhere but the ONLY example on how to handle strings when marshalling uses (still) a Stringbuilder.

This is where I am asking myself what is the alternative? What is the correct way? What is the non-stringbuilder way I should use?

**Comment by gewarren** [comment]
@Symbai Do the alternative options in https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1838#how-to-fix-violations help?

**Comment by Symbai** [comment]
Yeah that seems to be good alternatives thank you. Maybe the documentation could link to these alternatives

**Comment by AaronRobinsonMSFT** [comment]
@gewarren I'm preparing a PR to address this concern.
