### ISSUE TITLE
Parameter type contravariance support

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#28319]
"In C#, covariance and contravariance enable implicit reference conversion for array types, delegate types, and generic type arguments."-- It is clear and no issue. I am curious about some simple code/methods. For example, the following code compiles and works fine(it supports the covariant return type):
```
public class Parent
{
    public int Flag;   
    public virtual Parent GetFlag(int flag)
    {
        this.Flag= flag;
        return this;
    }
}
public class Child : Parent
{
    public override Child GetFlag(int flag) // Ok 
    {
        this.Flag = flag * 2;
        return this;
    }
}
```
But the following one does not support in C# (contravariance-in method parameters):
```
public class Parent
{
    public int Flag;
    public Parent()
    {
        Flag = 5;
    }
    public virtual void ShowFlag(Child child)
    {
        // Some code
    }
}
public class Child : Parent
{
    public Child()
    {
        this.Flag = base.Flag * 10;
    }
    public override void ShowFlag(Parent parent) //compile-time error
    {
        //Some code
    }
}
```

I am curious to know:  Is this an intended behavior in a similar context?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72dc0c-5129-34c5-7ddb-49b1e38c0990
* Version Independent ID: 9bd5372c-c461-dbcd-1acc-6e03451b49c7
* Content: [Covariance and Contravariance (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/covariance-contravariance/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> Is this an intended behavior in a similar context?

Yes. Here is a discussion about adding the feature to C#, including several points explaining why it's unlikely to happen anytime soon: https://github.com/dotnet/csharplang/discussions/3562.
