### ISSUE TITLE
The “no curly braces ({ })” in the article is rather confusing 

### ISSUE THREAD

**Issue by chanmmn** [dotnet/docs#28318]
[Enter feedback here]

The “no curly braces ({ })” is the article in rather confusing because the two statements below also have no curly braces ({ }) but they do have implementation.

public Square(int n) => _side = n;

and

public override int GetArea() => _side * _side;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00e23c2-618d-0b84-8ea8-0b0b4de1101a
* Version Independent ID: 8c00f924-bf5a-a748-331d-3809321e5547
* Content: [abstract - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/abstract)
* Content Source: [docs/csharp/language-reference/keywords/abstract.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/abstract.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reaching out @chanmmn 

Those methods are examples of [expression bodied members](https://docs.microsoft.com/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members). They are a short-hand form of method definition for single statement or expression methods. We've been using them in docs to help familiarize developers with this syntax. 

We'll keep watching for more feedback, but we're not making changes away from that practice at this point. I'll close this.
