### ISSUE TITLE
misplaced info in language specification for "try-catch"

### ISSUE THREAD

**Issue by yilmazdurmaz** [dotnet/docs#28317]
the `exception_filter` have a `when` follow by an boolean expression such as "ex.Message.Contains("404")", so `'catch' exception_filter block` is logically incorrect and I believe it is just a misplaced info while documenting and should be `'catch' exception_specifier block` as it is `exception_specifier`'s job to identify the exception type.

````
specific_catch_clause
    : 'catch' exception_specifier exception_filter? block
    | 'catch' exception_filter block
    ;

exception_specifier
    : '(' type identifier? ')'
    ;

exception_filter
    : 'when' '(' boolean_expression ')'
    ;

````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72dc2fc6-3080-f562-c806-dbb3a8ef9cf2
* Version Independent ID: df0525a0-2e50-73e0-aae0-67b6377ae615
* Content: [Statements - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#1211-the-try-statement)
* Content Source: [standard/statements.md](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @yilmazdurmaz 

The grammar described is correct. The `'catch' exception_filter block` clause is required for the following construct:

```
try {
    // ... 
} catch when (someBooleanCondition)
{
   // ...
}
```

The preceding catches any exception when the filter condition is true.

I'll close this.

**Comment by yilmazdurmaz** [comment]
@BillWagner 
Honestly, I thought filters need an exception variable to handle it and I didn't aware of that use case.
Thanks for the example.
