### ISSUE TITLE
Docker image shouldnt depend on SDK but on runtime

### ISSUE THREAD

**Issue by jkone27** [dotnet/docs#28323]
i suppose in general in production environments, you wouldnt want to base all on SDK image, but on aspnetcore runtime image.

as the note already mentions, thought doesn't make "much" sense

```
The ASP.NET Core runtime image is used intentionally here, although the mcr.microsoft.com/dotnet/runtime:6.0 image could have been used.
```

ideally also the advantage of docker is behaving consistently with production, so that should just be the default image.

dotnet command shouldnt be given in example in the DOCKER container, but just binary invocation in entrypoint based on aspnet docker runtime img

```dockerfile
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0
## or FROM mcr.microsoft.com/dotnet/runtime:6.0
##...
ENTRYPOINT ["./MyAppBinary"]
```
vs, the current which seems wrong to me..

```dockerfile
FROM sdk
ENTRYPOINT ["dotnet", "./MyAppBinary"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @jkone27 - thank you for posting this issue, it's much appreciated. With that said, this article is very intentional. The .NET team has instructed us on how to recommend containerization of .NET apps. With that said, this is not going to change.
