### ISSUE TITLE
Suggestion: Docs markdown tutorial

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#2833]
Please add a link "markdown" on the docs page, preferably in the comments area, that links to a page where users can see the a list of all MD options available in the docs, as they're different than GitHub's.

**Comment by mairaw** [comment]
Hi @weitzhandler,

You mean, the custom Markdown extensions we use?
If so, we cover them here: https://github.com/dotnet/docs/blob/master/styleguide/template.md
It's linked from our contributing guide.

I hope this helps.

**Comment by weitzhandler** [comment]
@mairaw 
I meant those in the comments in the docs. I'm not even sure it's powered by docs itself, but for dev forums, this should allow some minimal MD for links etc.

Here's what I mean:

![image](https://user-images.githubusercontent.com/2716316/28956566-566e29e6-78f6-11e7-8c38-1130c012cfd9.png)

**Comment by mairaw** [comment]
I saw your test comment just now and then connected the dots. So that's a LiveFyre plug-in (from Adobe). It doesn't use Markdown for formatting. When you click on the pencil, you get a few formatting options:
![image](https://user-images.githubusercontent.com/12971179/28956970-87541540-78a4-11e7-869d-3c63199dafe7.png)

We usually just paste the links as-is with no formatting. 

Does that help? If so, please let me know if it's ok to close this issue.

**Comment by weitzhandler** [comment]
Yeah I saw that toolbox before opening the issue.

I did believe it's from LiveFyre.

But since docs is a developer oriented website, it's most natural to include all the GitHub/StackOverflow markdown features in the comments. At least links and the other basic ones like code etc.

I think it would be best if you guys could contact LiveFyre and request from them to integrate a comments formatter that supports MD.

You could close this issue as I believe is not directly related to this repo's code, though you should thrive to use a more developer-friendly comments-service, or convince LiveFyre to adopt or enable MD.

**Comment by mairaw** [comment]
docs.microsoft.com doesn't only contain developer docs, so our solutions need to work for developers and non-developers. You're welcome to leave feedback about the website here: https://aka.ms/sitefeedback

However, we're discussing ways on how to improve the comments section.  Stay tuned! 😉

**Comment by weitzhandler** [comment]
Thank you!
And it was a pleasant surprise to hear from you hear on the GH repo too!

Keep up the good work, cuz you're doing it best @mairaw...

**Comment by weitzhandler** [comment]
And BTW look like [I have been there](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/17883796-comments-markdown) a while ago, completely forgot about it.
And apparently the LiveFyre team don't seem to be very helpful for dev-oriented people...
