### ISSUE TITLE
Formatting - Indentation

### ISSUE THREAD

**Issue by aitc-h** [dotnet/docs#28335]
Minor formatting error in §7.3, in the note code.
Lines 7 and 8 should be indented one level further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1000593-e418-a4db-4679-5c57422c776e
* Version Independent ID: 13832745-4304-3f38-2b2e-c5cad65c60ed
* Content: [Basic concepts - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts)
* Content Source: [standard/basic-concepts.md](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/basic-concepts.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @aitc-h 

The current indent level matches other notes in lists. I agree it looks a bit different visually because that note fits on one line.

Because it is correct, I'm closing this.
