### ISSUE TITLE
Basic128Sha256 | Use Aes256 for message encryption ?

### ISSUE THREAD

**Issue by sotto** [dotnet/docs#28334]
According to this page, Basic128Sha256 uses Aes256 for message encryption; I guess this is a bug in the documentation and should mention Aes128?

<html><body>
defaultAlgorithm Attribute

Basic128Sha256 | Use Aes256 for message encryption, Sha256 for message digest and Rsa-oaep-mgf1p for key wrap.
-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217c59b2-7fb7-b608-c75e-d8aa6854f42a
* Version Independent ID: 0414a903-2877-4e5a-96ee-3bb21fc518b4
* Content: [&lt;security&gt; of &lt;customBinding&gt; - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/security-of-custombinding)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by gewarren** [comment]
@sotto Yes you're right, thank you for letting us know!
