### ISSUE TITLE
Link seems broken in SOS page

### ISSUE THREAD

**Issue by SamZhangQingChuan** [dotnet/docs#28336]
The link `https://go.microsoft.com/fwlink/?LinkID=67325` in the section `TraverseHeap [-xml] <filename>` redirects me to https://www.microsoft.com/en-us/download

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e01c075-7a07-5850-d462-706675b545f1
* Version Independent ID: 0dd6c661-01a1-592c-ea53-8427412ff8d0
* Content: [SOS.dll (SOS Debugging Extension) - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension)
* Content Source: [docs/framework/tools/sos-dll-sos-debugging-extension.md](https://github.com/dotnet/docs/blob/main/docs/framework/tools/sos-dll-sos-debugging-extension.md)
* Product: **dotnet-framework**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Sorry, but the CLR profiler download is no longer available. I'm removing the link from the article.
