### ISSUE TITLE
I Try  to read Mongodb,It's geterror。

### ISSUE THREAD

**Issue by robyle** [dotnet/docs#28366]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b5a4ec-2c01-4d65-7e3c-0eef2965f013
* Version Independent ID: 850ab95d-3274-60ab-16f1-3c7150a639dc
* Content: [Connect .NET for Apache Spark to MongoDB](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/connect-to-mongo-db)
* Content Source: [docs/spark/how-to-guides/connect-to-mongo-db.md](https://github.com/dotnet/docs/blob/main/docs/spark/how-to-guides/connect-to-mongo-db.md)
* Product: **dotnet-spark**
* GitHub Login: @Niharikadutta
* Microsoft Alias: **nidutta**

**Comment by gewarren** [comment]
Closing in favor of #28367.

**Comment by robyle** [comment]
> Closing in favor of #28367.

Why be closed ?!

**Comment by robyle** [comment]
any one can help me ? thinks~~..

**Comment by gewarren** [comment]
@robyle How is this issue different to #28367? It seems like a duplicate.
