### ISSUE TITLE
Adding a new reason for  error CS1007

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#28389]
V9 added `init` accessors, which can be used *instead* of `set` accessors. 

So, a property cannot have both a set accessor method and an init accessor method.

Check that this is also the case with indexers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee97a08e-b85a-7c8b-7287-7fee8888ec3d
* Version Independent ID: 70a22bbc-7b5a-5e0f-9db4-89f8933910bd
* Content: [Compiler Error CS1007](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1007?f1url=%3FappId%3Droslyn%26k%3Dk(CS1007))
* Content Source: [docs/csharp/misc/cs1007.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1007.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 310944](https://dev.azure.com/msft-skilling/Content/_workitems/edit/310944)

**Comment by BillWagner** [comment]
Thanks for finding this @RexJaeschke
