### ISSUE TITLE
Not really an issue - Spanish Version

### ISSUE THREAD

**Issue by NachoLed** [dotnet/docs#28388]
Hi!
There is some type of collaboration to translate this pages?
Im Learning and i like to help to translate this pages. 
Im from Argentina and one of the biggest problems of latam to acces this type of content is the lenguage

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - C# Fundamentals tutorial](https://docs.microsoft.com/es-mx/dotnet/csharp/fundamentals/tutorials/classes)
* Content Source: [docs/csharp/fundamentals/tutorials/classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @NachoLed 

I'm adding @khoiph1 and @juricgit to this thread. They work on localization and community contributors, respectively. They can help point you to how to get involved.

**Comment by khoiph1** [comment]
@NachoLed Thank you for your offer. We are looking into this missing translation. 
[FEEDBACK 563566](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/563566)

**Comment by khoiph1** [comment]
The page is localized.

**Comment by gewarren** [comment]
Closing as fixed. If you still believe something's missing, please leave a comment!
