### ISSUE TITLE
Shouldn't the anonymous record symbols, i.e. {| |}, be included on the F# Symbols page

### ISSUE THREAD

**Issue by KPMTGG** [dotnet/docs#28391]
Shouldn't the anonymous record symbols, i.e. {| |}, be included on the [F# Symbols page](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjR1aKK9Jj2AhXwTN8KHZNHBjEQFnoECAcQAQ&url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Ffsharp%2Flanguage-reference%2Fsymbol-and-operator-reference%2F&usg=AOvVaw0YyT1VuaQTAHQ-8qj3fSCK)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474586f3-428e-e787-e0ae-5b39331635cc
* Version Independent ID: 2499d6cc-0b9b-cce6-f8f8-a6e09964b444
* Content: [Copy and Update Record Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/copy-and-update-record-expressions#feedback)
* Content Source: [docs/fsharp/language-reference/copy-and-update-record-expressions.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/copy-and-update-record-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @ChrSteinert
* Microsoft Alias: **dotnetcontent**

**Comment by smoothdeveloper** [comment]
I am not clear, which section would be relevant, but maybe one section dedicated to records, should have `{}` and `{||}`, and maybe, there is a section for CE, which should also contain `{}`

**Comment by KPMTGG** [comment]
The page has [] for list and [||] for array.  Should it not also have the symbols for records and anonymous records?  I'm just learning F# and I refer to that page for any symbols.  So, when I could not find the anonymous records symbol it was confusing and I had to search google for it.  Shouldn't this page have ALL the symbols F# uses?

**Comment by BillWagner** [comment]
ping @KathleenDollard @dsyme for a recommendation.

**Comment by dsyme** [comment]
Yes they should, good suggestion.
