### ISSUE TITLE
Update finalizer section in c# spec

### ISSUE THREAD

**Issue by ShuiRuTian** [dotnet/docs#28397]
[Enter feedback here]
The description has been out of time.
Considered that this is the specification of C#, the mismatch of example code and real implementation might be pretty confusing.
1. "C# requires that finalizers be run at some time between the time an object is eligible and ***the time that the application exits***, but specifies neither a time constraint within that span, nor an order in which finalizers are run." This is not always true any more. Other page says something like ".NET 5 (including .NET Core) or a later version doesn't call finalizers when the application terminates"
2. The example code does not works, reference this issue https://github.com/dotnet/runtime/issues/65845

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1000593-e418-a4db-4679-5c57422c776e
* Version Independent ID: 13832745-4304-3f38-2b2e-c5cad65c60ed
* Content: [Basic concepts - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts)
* Content Source: [standard/basic-concepts.md](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/basic-concepts.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @ShuiRuTian 

The text I see in the English version follows. Are you quoting from a translation? I'm trying to understand how what you above (which was the previous text) is different than what I'm seeing live. 

From [§7.2 Application Termination](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#72-application-termination)

Whether or not finalizers ([§14.13](classes.md#1413-finalizers)) are run as part of application termination is implementation-specific.

> *Note*: The .NET Framework implementation makes every reasonable effort to call finalizers ([§14.13](classes.md#1413-finalizers)) for all of its objects that have not yet been garbage collected, unless such cleanup has been suppressed (by a call to the library method `GC.SuppressFinalize`, for example). *end note*

**Comment by ShuiRuTian** [comment]
Ooops, I have to say I missed [§7.2](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#72-application-termination). This section makes things pretty clear.

As for the quotes,
`C# requires that finalizers be run at some time between the time an object is eligible and the time that the application exits, but specifies neither a time constraint within that span, nor an order in which finalizers are run.` is copied from English text from [§7.9](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#79-automatic-memory-management). It should be in the third paragraph(omit five steps of memory management life cycle of an object)

And the example code that not works is also in the [§7.9](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#79-automatic-memory-management).

Sorry for not pointing out the spec section that I think need to be updated, just forgot :(

And thanks a lot for the quick, kind and detailed response!

**Comment by BillWagner** [comment]
Thank you @ShuiRuTian That helps.

I've opened dotnet/csharpstandard#467 to address this.
