### ISSUE TITLE
Improve documentation for CA2254

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#28400]
The analyzer rule is useful IMO, but there should be a code fix and improved [documentation](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254). This is way too little information:

![image](https://user-images.githubusercontent.com/1784452/155620672-d61c2ee5-22e6-4512-88bd-11f0849dc99c.png)

_Originally posted by @MisinformedDNA in https://github.com/dotnet/roslyn-analyzers/issues/5626#issuecomment-1050339150_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by SeanKilleen** [comment]
I took a shot at this in #29787; happy to receive feedback there.
