### ISSUE TITLE
Visual studio has incorrect link

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dotnet/docs#28409]
Not sure if this is the right repo for this, if it is not, I can move it, but when I click on this code hyperlink, it attempts to send me to https://bingdev.cloudapp.net/BingUrl.svc/Get?selectedText=Program%20does%20not%20contain%20a%20static%20%27Main%27%20method%20suitable%20for%20an%20entry%20point&mainLanguage=C%23&requestId=9e3285af-3396-4b27-b51f-7e10932ce5a4&errorCode=CS5001 which doesn't seem right so I wanted to see if that was a mistake. 
<img width="245" alt="image" src="https://user-images.githubusercontent.com/22186029/155800696-025c304e-c34e-4865-814f-c2c4fdc001b8.png">
As I think it should instead link to https://docs.microsoft.com/dotnet/csharp/misc/cs5001

**Comment by gewarren** [comment]
@BillWagner Do you know what the correct format for the compiler error links is?

**Comment by BenjaminMichaelis** [comment]
By add in do you mean modifying the image? Because this is just what happens if you take out the main in a project. All the other error codes work fine.
![Animation333](https://user-images.githubusercontent.com/22186029/156440302-2aff5c3d-8306-402a-9619-2670a9454c49.gif)
Also the format looks like it should be [msdn.mircrosoft.com/query/roslyn.query?appID-roslyn&k=k(cs5001)](https://msdn.microsoft.com/query/roslyn.query?appId=roslyn&k=k(cs5001)) for this error. Is there somewhere I should update this at?

**Comment by BillWagner** [comment]
Thansk @BenjaminMichaelis 

The format you show is correct. I was wondering if you had a Visual Studio add in that's changing the destination for the service. 

@CyrusNajmabadi knows more about that side of the F1 service.

**Comment by BenjaminMichaelis** [comment]
Just want to make sure this doesn't go completely stale so others don't run into this issue

**Comment by BillWagner** [comment]
Ping @CyrusNajmabadi @davkean  Any idea why this help string is redirecting?

**Comment by CyrusNajmabadi** [comment]
I don't think the ide is involved here. I imagine the compilers or individual languages determine their help urls.  Maybe @jaredpar knows?

**Comment by jaredpar** [comment]
I have no idea how this gets redirected in Visual Studio. @jasonmalinowski?

**Comment by BenjaminMichaelis** [comment]
Just to make sure that this was still an issue, just tried again on my freshly reinstalled computer with vs reinstalled as well of course and same issue still happens

**Comment by BenjaminMichaelis** [comment]
Looks like this issue has been resolved recently.
