### ISSUE TITLE
Unknown syntax: 'default!'

### ISSUE THREAD

**Issue by IGkougkousis** [dotnet/docs#28413]
What does the syntax `default!` do? I've never seen it anywhere else and after a lot of googling, this document is the only place that has it! I would really appreciate an explanation. I tested it with some local dotnet projects, and I can confirm that it is at least valid C# syntax. But I really have no idea what it does.

**edit** Example from the document

```c#
public record Person
{
    public string FirstName { get; init; } = default!;
    public string LastName { get; init; } = default!;
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
`default` is [the default literal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default?WT.mc_id=DOP-MVP-5002735#default-literal). In this case, it's short for `default(string)`, which is the same as `null`.

`!` is [the null-forgiving operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving?WT.mc_id=DOP-MVP-5002735), which silences warnings related to nullable reference types.

**Comment by IGkougkousis** [comment]
Alright, makes sense. Thanks
