### ISSUE TITLE
recursive definition/answer to error code

### ISSUE THREAD

**Issue by sksharonker** [dotnet/docs#28419]
[Enter feedback here]

the article would make a whole lot more sense if a quick example were given.. 
or if a quick... remember "this term means" of the pieces using DIFERENT keywords than the original. 
right now, I feel like the answer says "turn rock over to see other side" and the reverse side says the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d3abb4-7b20-ce1f-630c-b4d9765fb5b8
* Version Independent ID: ace21fe2-7476-fabe-ee48-bf89e34c05ca
* Content: [Reference to a non-shared member requires an object reference - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30469)
* Content Source: [docs/visual-basic/misc/bc30469.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30469.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention. We should add an example that makes the explanation more clear.

I've added this to our list, and added the "up for grabs" label for anyone that would like to submit a PR before we make the fix.
