### ISSUE TITLE
Add information about portable RIDs

### ISSUE THREAD

**Issue by weshaggard** [dotnet/docs#2843]
With .NET Core 2.0 we are moving towards using what we call portable RID's which are essentially RID's that aren't distro or version specific but instead contain assets that can work on lots of platforms. I think we need to refresh this document https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to add information on the portable RIDs (i.e. linux-x64, win-x86/x64, osx-x64, etc). 

cc @ericstj

**Comment by mairaw** [comment]
Should we also change examples where we show specific RIDs to use the portable ones? E.g. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

**Comment by weshaggard** [comment]
I think it is worth adding additional samples with the portable RIDs and the portable ones should be the primary example but the other RIDs should still have samples.

**Comment by yaakov-h** [comment]
Any news on this? The tooling is out, but the docs haven't been updated yet, which is plain confusing.

**Comment by mairaw** [comment]
Apologies on that @yaakov-h. This is coming soon.
