### ISSUE TITLE
[17.1] Parameter null checking

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#28443]
This adds the `!!` syntax for the compiler to add a null check on that parameter. See dotnet/csharplang#2145 and the [feature spec](https://github.com/dotnet/csharplang/blob/main/proposals/param-nullchecking.md)

**Comment by gfoidl** [comment]
> This adds the `??` syntax for the compiler to add a null check

It is `!!`.

(Will hide this comment after your update).

**Comment by BillWagner** [comment]
Thanks @gfoidl I don't know what I was thinking.

**Comment by gfoidl** [comment]
Now it's `11` instead of `!!`, please look again 😉

**Comment by BillWagner** [comment]
one of those days.....
