### ISSUE TITLE
Constraints not correct for instance-based logging

### ISSUE THREAD

**Issue by fsimonazzi** [dotnet/docs#28441]
Log method constraints indicate "Logging methods must be static, partial, and return void." but that's not the case for instance-based logging, documented in the same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc4ecf0-19e4-54d3-c34e-b6eadb80262b
* Version Independent ID: decc74aa-a2d5-8727-f22b-3862bacde737
* Content: [Compile-time logging source generation](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator)
* Content Source: [docs/core/extensions/logger-message-generator.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logger-message-generator.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @maryamariyan
* Microsoft Alias: **maariyan**

**Comment by gewarren** [comment]
Related to #24495.
