### ISSUE TITLE
In NET 6, Azure Function v4, foreach loop with Azure.AsyncPageable<TableEntity> seems to not work

### ISSUE THREAD

**Issue by nguyenlamlll** [dotnet/docs#28480]
I am using NET 6 and developing an Azure Function v4. I am querying against an Azure Table storage. 

I follow this sample's code block [here from line 48 to 57](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/tests/samples/Sample4_QueryEntitiesAsync.cs#L48-L57).
Also, in this section [Iterate over AsyncPageable with await foreach](https://docs.microsoft.com/en-us/dotnet/azure/sdk/pagination#iterate-over-asyncpageable-with-await-foreach), an example is also given about iterate over an AsyncPageable<T>

My code blocks are
```
using Azure.Data.Tables;

...

_scoresTableClient = tableServiceClient.GetTableClient(TableConstants.SCORES_TABLE);

...

var scoreEntities = _scoresTableClient.QueryAsync<TableEntity>($"UserId eq '{userId}'");
await foreach (var scoreEntity in scoreEntities)
{
    var score = ScoreEntity.MapToScoreModel(scoreEntity);
    result.Add(score);
}
```
I place breakpoint on the line `await foreach (var scoreEntity in scoreEntities)` and it seems that whenever the code tries to resolve `in scoreEntities`, it breaks and throws an error:

```
[2022-03-03T19:55:42.025Z] System.Private.CoreLib: Exception while executing function: MyFunction. Azure.Data.Tables: The requested operation is not implemented on the specified resource.
RequestId:b9e1373c-8002-0000-7438-2f1507000000
Time:2022-03-03T19:55:41.7788246Z
[2022-03-03T19:55:42.026Z] Status: 501 (Not Implemented)
[2022-03-03T19:55:42.026Z] ErrorCode: NotImplemented
[2022-03-03T19:55:42.027Z] 
[2022-03-03T19:55:42.027Z] Content:
[2022-03-03T19:55:42.028Z] {"odata.error":{"code":"NotImplemented","message":{"lang":"en-US","value":"The requested operation is not implemented on the specified resource.\nRequestId:b9e1373c-8002-0000-7438-2f1507000000\nTime:2022-03-03T19:55:41.7788246Z"}}}
[2022-03-03T19:55:42.029Z] 
[2022-03-03T19:55:42.029Z] Headers:
[2022-03-03T19:55:42.030Z] Cache-Control: no-cache
[2022-03-03T19:55:42.030Z] Transfer-Encoding: chunked
[2022-03-03T19:55:42.031Z] Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
[2022-03-03T19:55:42.032Z] x-ms-request-id: b9e1373c-8002-0000-7438-2f1507000000
[2022-03-03T19:55:42.033Z] x-ms-client-request-id: 8393106f-ce2e-4ad2-aae1-f0ec1c6462e1
[2022-03-03T19:55:42.033Z] x-ms-version: REDACTED
[2022-03-03T19:55:42.034Z] X-Content-Type-Options: REDACTED
[2022-03-03T19:55:42.035Z] Date: Thu, 03 Mar 2022 19:55:41 GMT
[2022-03-03T19:55:42.035Z] Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8 
[2022-03-03T19:55:42.036Z] .
```

The document is not consistent? How should I make this work?

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f574a41f-3a07-4cf5-911c-d05ce971abcb
* Version Independent ID: ead934d2-852a-027c-c46e-819ed6cd495c
* Content: [Pagination with the Azure SDK for .NET](https://docs.microsoft.com/en-us/dotnet/azure/sdk/pagination#use-systemlinqasync-with-asyncpageable)
* Content Source: [docs/azure/sdk/pagination.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/pagination.md)
* Product: **dotnet-azure**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @nguyenlamlll,

Thank you for posting this issue, we really appreciate it.

Are you able to tell us what version of `Azure.Data.Tables` you're using? I'm going to add a few others to this issue that are probably a bit more knowledgeable in this specific area.

/cc @scottaddie @CamSoper @christothes

**Comment by IEvangelist** [comment]
Tagging these kind folks again for help: @scottaddie @CamSoper @christothes

**Comment by nguyenlamlll** [comment]
From what I see, my project currently uses Azure.Data.Tables v12.4.0

**Comment by christothes** [comment]
Hi @nguyenlamlll - Do you have a full stack trace of the exception?

**Comment by nguyenlamlll** [comment]
@christothes Hi. Sorry for being late on this. Our project was on a tight deadline.
Somehow the problem went away! I try to make a separate test function like this. But it seems everything is working fine now. No more error like a month ago.

```
using System.Collections.Generic;
using System.Threading.Tasks;
using Azure.Data.Tables;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;

namespace MyNamespace
{
    public class TestFunctions
    {
        private readonly TableClient _scoresTableClient;

        public TestFunctions(TableServiceClient tableServiceClient)
        {
            _scoresTableClient = tableServiceClient.GetTableClient(TableConstants.SCORES_TABLE);
        }

        [FunctionName("TestFunction")]
        [OpenApiOperation(operationId: "TestFunction", tags: new[] { "test" })]
        public async Task<IActionResult> TestFunctionAsync(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test")] HttpRequest req)
        {
            string userId = req.Query["userId"];
            var scoreEntities = _scoresTableClient.QueryAsync<TableEntity>($"UserId eq '{userId}'");
            var result = new List<ScoreEntity>();
            await foreach (var scoreEntity in scoreEntities)
            {
                var score = ScoreEntity.MapToScoreModel(scoreEntity);
                result.Add(score);
            }
            return new OkObjectResult(result);
        }
    }
}
```

So I guess we can close this now?

**Comment by IEvangelist** [comment]
Awesome, thank you for the follow up @nguyenlamlll - we will close this. Let us know if you have any questions.
