### ISSUE TITLE
Async explained with a breakfast

### ISSUE THREAD

**Issue by svandenhoven** [dotnet/docs#28490]
Genuinely nice article and very beautifully written. Every understands the complexity of the domestic logistic of making breakfast. Nice to take this as metaphor and it made it so much easier to understand.

Sander
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @svandenhoven I'm glad you liked this.

Closing the issue as kudos.
