### ISSUE TITLE
2 public fields a and b C #

### ISSUE THREAD

**Issue by iuioiuoiuuiouoi** [dotnet/docs#28495]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df47593-8586-e54e-fb74-cf3a96262d40
* Version Independent ID: b464cd68-4713-c848-e9a7-30705d17e6f7
* Content: [Fields - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/fields.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/fields.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @iuioiuoiuuiouoi 

Can you add more details on what you're asking for here? It's unclear from the example.
