### ISSUE TITLE
Casting Error

### ISSUE THREAD

**Issue by NaveenTharak** [dotnet/docs#28508]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a86375-5077-1031-4262-65c9ff1db985
* Version Independent ID: 06488d45-19ec-f12c-0cbb-82c9bf133bb0
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0029.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0029.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @NaveenTharak 

Can you add more details on what your looking for here?
