### ISSUE TITLE
Missing variable declaration in creating a windows service walkthrough.

### ISSUE THREAD

**Issue by moar55** [dotnet/docs#2850]
In the doc found here https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md at the section for creating an `onTimer` event handler for the timer a non-declared variable `eventId` is passed to a function thus causing an error. Here is the part having this issue : 

```csharp
public void OnTimer(object sender, System.Timers.ElapsedEventArgs args)  
{  
    // TODO: Insert monitoring activities here.  
    eventLog1.WriteEntry("Monitoring the System", EventLogEntryType.Information, eventId++);  
}  

```

A solution would be simply decalre `eventId` variable and initalize with 0... 

edit: @mairaw fixed the link to the topic

**Comment by mairaw** [comment]
@moar55 thank you for your feedback. We'll have to investigate this issue.

**Comment by mairaw** [comment]
Marked as P1 since this topic has high traffic.

**Comment by moar55** [comment]
Anytime ! :smile:
