### ISSUE TITLE
Fix client configuration code sample

### ISSUE THREAD

**Issue by swedishkid** [dotnet/docs#28502]
Code snippet is wrong:
```
client = new ClientBuilder()
    .UseLocalhostClustering()
    .Configure<ClusterOptions>(options =>
    {
        options.ClusterId = "dev";
        options.ServiceId = "MyAwesomeService";
    })
    .ConfigureLogging(logging => logging.AddConsole())
var client = builder.Build();

await client.Connect();
```

Should be changed to

```
var builder = new ClientBuilder()
    .UseLocalhostClustering()
    .Configure<ClusterOptions>(options =>
    {
        options.ClusterId = "dev";
        options.ServiceId = "MyAwesomeService";
    })
    .ConfigureLogging(logging => logging.AddConsole());
var client = builder.Build();

await client.Connect();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2076bd-c825-ea94-df48-3d4ab4a5c328
* Version Independent ID: e49dfa62-c470-40b8-6b8d-1abb893364d3
* Content: [Local development configuration](https://docs.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/local-development-configuration)
* Content Source: [docs/orleans/host/configuration-guide/local-development-configuration.md](https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/local-development-configuration.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @swedishkid - I'm on it. See: #28515
