### ISSUE TITLE
Misspelled storage provider

### ISSUE THREAD

**Issue by miroslavp** [dotnet/docs#28511]
I believe the following statement is incorrect "A composite storage provider can be used with SharedStorageProvider.". I think that it should be ShardedStorageProvider instead. Although I've read somewhere that ShardedStorageProvider is no longer available which is sad because I badly needed a composite storage provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767d60a2-9aeb-7d33-64b7-8cf989175175
* Version Independent ID: f8b885af-c74c-8e87-d1f7-60845f28bb53
* Content: [Best practices in Orleans](https://docs.microsoft.com/en-us/dotnet/orleans/resources/best-practices)
* Content Source: [docs/orleans/resources/best-practices.md](https://github.com/dotnet/docs/blob/main/docs/orleans/resources/best-practices.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by benjaminpetit** [comment]
I don't think I ever saw a sharded/shared implementation of the storage provider... I think we should remove this from the documentation.

@miroslavp I think a sharded storage implementation should not be too hard to write. I would be happy to review it if you have time to develop something.

**Comment by miroslavp** [comment]
@benjaminpetit I think it was referencing this [https://docs.microsoft.com/en-us/dotnet/api/orleans.storage.shardedstorageprovider?view=orleans-1.0](https://docs.microsoft.com/en-us/dotnet/api/orleans.storage.shardedstorageprovider?view=orleans-1.0) . 
Is there anywhere I can see the source code of it?

**Comment by benjaminpetit** [comment]
Found it: https://github.com/dotnet/orleans/blob/v1.5.10/src/OrleansProviders/Storage/ShardedStorageProvider.cs
