### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by tmarcis1** [dotnet/docs#28521]
The .NET 6 Windows service does not work, at least when I built and deployed on my workstation.  (I also downloaded the .NET Samples version from https://github.com/dotnet/samples).  When (either is run), it produces an error like the following on service startup (which then abruptly stops):

System.InvalidOperationException: Unable to resolve service for type 'App.WindowsService.JokeService' while attempting to activate 'App.WindowsService.WindowsBackgroundService'.

After taking a sidetrip on .NET 6 dependency injection, I got it to work by adding the following line to Program.cs:

            .AddSingleton<JokeService>(new JokeService());

Not a terribly complex change, but disappointing that both the documented example and the downloaded sample don't work as described.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @tmarcis1 
Thank you so much for posting this issue. We really appreciate it.

There was a recent change that obviously missed the runtime bug that was introduced, this is fixed in https://github.com/dotnet/docs/pull/28522. Thank you
