### ISSUE TITLE
Suggestions to improve the native-sized integers proposal

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#28539]
Using this proposal, I’ve been writing a formal spec for this feature to add to the C# standard, and have the following comments:

## Comment 1: “Miscellaneous”

> `nint` and `nuint` cannot be used as an `enum` base type from C#.

> ```C#
> enum E : nint // error: byte, sbyte, short, ushort, int, uint, long, or ulong expected
> {
> }
>```
>
> Reads and writes are atomic for types `nint`, `nuint`, and `enum` with base type `nint` or `nuint`.

The final sentence contradicts the first; I suggest you strike the enum phrase at the end of the final one.

## Comment 2: “Miscellaneous”

> `typeof(nint)` is `typeof(IntPtr)`.

Presumably, the following is also true:

> `typeof(nuint)` is `typeof(UIntPtr)`.

## Comment 3: “Miscellaneous”

> `sizeof(nint)` is supported but requires compiling in an unsafe context (as does `sizeof(IntPtr)`). The value is not a compile-time constant. `sizeof(nint)` is implemented as `sizeof(IntPtr)` rather than `IntPtr.Size`.

Presumably, the following is also true:

> `sizeof(nuint)` is supported but requires compiling in an unsafe context (as does `sizeof(UIntPtr)`). The value is not a compile-time constant. `sizeof(nuint)` is implemented as `sizeof(UIntPtr)` rather than `UIntPtr.Size`.

## Comment 4: binary numeric promotions

The spec [says](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#11473-binary-numeric-promotions),

> Binary numeric promotion consists of applying the following rules, in the order they appear here:
> -   …
> -   Otherwise, if either operand is of type `ulong`, the other operand is converted to type `ulong`, or a binding-time error occurs if the other operand is of `type sbyte`, `short`, `int`, or `long`.
> -   Otherwise, if either operand is of type `long`, the other operand is converted to type `long`.
> -   Otherwise, if either operand is of type `uint` and the other operand is of type `sbyte`, `short`, or `int`, both operands are converted to type `long`.
> -   Otherwise, if either operand is of type `uint`, the other operand is converted to type `uint`.
> -   Otherwise, both operands are converted to type `int`.

How do `nint` and `nunint` fit in here?

## Comment 5: pointer arithmetic

I believe the following operators need to be added:

```csharp
T* operator +(T* x, nint y);
T* operator +(T* x, nuint y);
T* operator +(nint x, T* y);
T* operator +(nuint x, T* y);
T* operator –(T* x, nint y);
T* operator –(T* x, nuint y);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de63b2ae-2018-b52e-0cb4-d19ac77093c1
* Version Independent ID: 9805d223-c541-8a6b-f79f-3ae3dd71023f
* Content: [Native sized integers - C# 9.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/native-integers)
* Content Source: [proposals/csharp-9.0/native-integers.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/native-integers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by tannergooding** [comment]
This should be reviewed by someone from the language team, not me.

@cston is probably the correct person here.

**Comment by cston** [comment]
The changes recommended in comments 1-3 look correct.

I'll investigate comments 4 and 5.

**Comment by BillWagner** [comment]
assigning to @cston per discussion
