### ISSUE TITLE
[Project] Document compiler errors 

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#2854]
This is a meta-issue for public discussion of the .NET Core content project [Document compiler errors](https://github.com/dotnet/docs/projects/16) .

Comment below to suggest new content, or updates to existing content:

**Comment by wadepickett** [comment]
@rpetrusha, please update with Milestone if we are ready to commit to one.  Thanks.

**Comment by BillWagner** [comment]
Closing this issue as we are tracking this work in the associated project.
