### ISSUE TITLE
[Breaking change] .NET 7 with C++/CLI requires Visual Studio 2022 17.2 Preview 2

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/docs#28542]
### Description

**Starting in .NET 7 Preview 3, Visual Studio 2022 17.2 Preview 2+ must be used for C++/CLI projects.**

.NET 7 Preview 3 includes "Generic Math" APIs that use `static abstract` interface members on primitive types such as `System.Int32`; earlier versions of the C++/CLI compiler were incompatible with such members. Because those members are used on many primitive types, compilation errors will occur when targeting `net7.0` even if the Generic Math features are not used directly.

Beyond C++/CLI, it's also possible that the introduction of `static abstract` interface members on primitive `System` types will surface issues in other tools that are not forward-compatible with the usage of this new language construct. As was done with C++/CLI, any other tools impacted by this change will need to be updated to accommodate the usage of `static abstract` interface members. If needed on such issues, tool authors should file a [New Issue · dotnet/runtime](https://github.com/dotnet/runtime/issues/new?assignees=&labels=&template=04_blank_issue.md&title=) to request guidance.

Pull Request: [Moving "Generic Math" in box and making it no longer experimental by tannergooding · Pull Request #65731 · dotnet/runtime](https://github.com/dotnet/runtime/pull/65731)

### Version

.NET 7 Preview 3

### Previous behavior

Compiling .NET projects using C++/CLI would not result in errors related to members on primitive `System` types.

### New behavior

Compiling a .NET 7 Preview 3 `net7.0` project using C++/CLI in an earlier release of Visual Studio will result in many errors similar to this example:

```
error C2253: 'System.Int32.Parse': pure specifier or abstract override specifier only allowed on virtual function
```

There is no way to work around this compiler error as it's generated because of `static abstract` interface members on primitive `System` types. By upgrading to Visual Studio 2022 17.2 Preview 2+, the compilation errors will no longer occur.

Implicitly-implemented `static abstract` interface members can be invoked, but even with Visual Studio 2022 17.2 Preview 2+ C++/CLI does not support invoking explicitly-implemented `static abstract` interface members.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

.NET 7 Preview 3 includes the new API definitions for the "Generic Math" feature set. These APIs were [introduced in .NET 6 as a preview feature](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/), requiring an additional `System.Runtime.Experimental` package to be installed to gain access to the APIs. Those APIs are being included in-box with .NET 7 Preview 3 with further stabilization and refinement to come in later .NET 7 previews.

See [Developers can use Generic Math without enabling preview features · Issue #63548 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63548) for more information.

### Recommended action

Upgrade to Visual Studio 2022 17.2 Preview 2+ to continue using C++/CLI with .NET 7 Preview 3+. See [Visual Studio 2022 Preview Release Notes | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview) for more information and downloads.

### Feature area

Core .NET libraries

**Comment by DerekSMorin** [comment]
0


I'm trying to use:
Visual Studio = Version 17.3.0 Preview 1.1
And Microsoft.NET SDK 7.0.100-preview.4.22252.9 (x64)

I seem to be getting a similar error.  @gewarren?

I've been able to compile some csproj projects but for my vcxproj I am getting: 

6>C:\Development\Source\ApmUpdateDotNet7\framework\oqkern\shared\ManagedDateTime.cpp(31,4): error C2220: the following warning is treated as an error 6>C:\Development\Source\ApmUpdateDotNet7\framework\oqkern\shared\ManagedDateTime.cpp(31,4): warning C4679: 'Parse': could not import member 6>C:\Development\Source\ApmUpdateDotNet7\framework\oqkern\shared\ManagedDateTime.cpp(31,4): message : static virtual methods of interfaces are not supported and will be unavailable 6>C:\Development\Source\ApmUpdateDotNet7\framework\oqkern\shared\ManagedDateTime.cpp(31,4): message : This diagnostic occurred while importing type 'System::IParsable' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by tannergooding** [comment]
This is expected. C++/CLI changed what was a hard error into a warning. You likely have `/warnaserror` or similar enabled (as per `the following warning is treated as an error`) and so you'll need to disable `C2220`.

**Comment by DerekSMorin** [comment]
Thanks @tannergooding - I ended up having to disable 4679 and thanks to your help I managed to get things compiling.

![image](https://user-images.githubusercontent.com/7568856/173148246-481401f7-8050-482e-850d-e726a12f71f8.png)

**Comment by mo-russo** [comment]
Visual Studio = Version 17.5.3
Microsoft.NET SDK 7.0.202

I'm getting a bunch of of errors like this one when trying to compile my C++/CLI project with .NET 7:

```
error C2253: 'System::IParsable::Parse': pure specifier or abstract override specifier only allowed on virtual function
message : This diagnostic occurred while importing type 'System::IParsable ' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
message : This diagnostic occurred while importing type 'System::Int32 ' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Here's the line on which the error above occurs:
`var myList = gcnew List<MyObject^>();`

I read the post here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/cpluspluscli-compiler-version

I thought that using the latest VS2022 would fix this issue, but it didn't. And in my case, it's not warning considered as error type thing like @DerekSMorin so I can't disable any warning to make it compile.

Any advice?

**Comment by bouchraRekhadda** [comment]
Thanks @tannergooding for your explanation. 
Is there currently any workaround for those stuck on PlatformToolset `v142` that wan't to upgrade to .NET 8 quickly?

**Comment by tannergooding** [comment]
I am not aware of any workaround. C++/CLI required changes to support newer runtime features, such as `static virtuals on interfaces` and `default interface members`. These changes were only implemented on newer platform toolsets. Since these features are used on types such as `System.Int32`, which is used in every single C++/CLI application, there is no workaround except to update to the latest toolset
