### ISSUE TITLE
Allah Nawaz Castle

### ISSUE THREAD

**Issue by NAWABDERA1** [dotnet/docs#28545]
**Help us make content visible**

**Describe the new article**

**Comment by BillWagner** [comment]
closing as spam

**Comment by NAWABDERA1** [comment]
INSHA ALLAH I am pleased to invite your attention that Allah Nawaz Castle is my birthplace ![image](https://user-images.githubusercontent.com/9724587/157467200-64d3d91e-9a59-465c-99a8-3c3ea09c83a6.jpeg)
