### ISSUE TITLE
Default value for Nullable not as stated in the documentation

### ISSUE THREAD

**Issue by AMSoftwareNL** [dotnet/docs#28578]
The documentation status under for Nullable:
"The Nullable option lets you specify the nullable context. **The default value for this option is disable**."

This isn't true (anymore) with .NET6. By default this option is "enable".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548e000-8190-b1bb-51fd-7e7b2d5bcb45
* Version Independent ID: 19f59267-c4c1-eb0e-7e48-45ffd6e2d9d1
* Content: [C# Compiler Options - language feature rules](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language?source=docs#nullable)
* Content Source: [docs/csharp/language-reference/compiler-options/language.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/language.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BartoszKlonowski** [comment]
I would like to handle this @BillWagner.
Please assign this to me and I will deliver the PR within next week (14.03 - 20.03).

**Comment by BillWagner** [comment]
Thank you @BartoszKlonowski 

I've just assigned this to you.
