### ISSUE TITLE
msdn link causes exception

### ISSUE THREAD

**Issue by Joseph-McFadden** [dotnet/docs#28591]
The link provided "https://msdn.microsoft.com" results in exception "System.Net.Http.HttpRequestException".

No sure why this occurs, it just does.

Links to other https:// websites that do work are:
       "https://www.postman.com/"
        "https://www.microsoft.com/"
        "https://docs.microsoft.com/en-us/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc401403-0d5a-5b3a-dea1-faff511fedc1
* Version Independent ID: 7c6089e4-8e7f-4f4f-6ed2-b13e5f0ebaad
* Content: [Control Flow in Async Programs - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/control-flow-in-async-programs)
* Content Source: [docs/visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for nothing this @Joseph-McFadden 

The reason for the exception is that `msdn.microsoft.com` has been retired, in favor of `docs.microsoft.com`. Your browser will redirect, but this sample doesn't handle those.

I just submitted a PR to address this by changing the target URL.
