### ISSUE TITLE
Weird identation at section Parameterless constructors and field initializers of article Structure types

### ISSUE THREAD

**Issue by bottle2** [dotnet/docs#28594]
The second example of the section "Parameterless constructors and field initializers" in [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct) article "Structure types" of the Language reference has weird identation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this @bottle2 

I opened a PR to address this.
