### ISSUE TITLE
Duplicate example at section "How to identify a nullable value type" of article "Nullable value types"

### ISSUE THREAD

**Issue by bottle2** [dotnet/docs#28597]
The first and last example of the section "How to identify a nullable value type" of [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#how-to-identify-a-nullable-value-type) article "Nullable value types" are too similar, consider removing the last example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e65a97-5e33-ab78-cd40-b20c3219ca2f
* Version Independent ID: 1ae0aed9-e565-44ae-aebe-c55a0a02c2c5
* Content: [Nullable value types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-value-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/nullable-value-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BartoszKlonowski** [comment]
Indeed they both have the exact same workflow and present the same thing.
But in my opinion simply removing the last would cause some confusion as there is a reference to it above it. I believe the way to go would be to make a minor "refactor" of this section so it makes sense and reuse this example that is now duplicated.

@BillWagner Please assign me to this issue so I can handle it.

**Comment by BillWagner** [comment]
Thanks for raising this @bottle2 

Thanks as well @BartoszKlonowski I've assigned this to you.
