### ISSUE TITLE
Download as pdf removes some properties

### ISSUE THREAD

**Issue by denizhansoydas** [dotnet/docs#28604]
[Enter feedback here]
Downloading as pdf removes the colors in the codes and some other properties as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0e44dd-e0f2-9ace-006b-479a92fbf424
* Version Independent ID: 7811190e-6019-83d8-d504-c0b985368055
* Content: [Define types and their members - A tour of C#](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types#feedback)
* Content Source: [docs/csharp/tour-of-csharp/types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @jffriend to raise awareness.

Hi @denizhansoydas There's work on a new engine for this capability. I've made sure the team working on that sees this concern.

**Comment by BillWagner** [comment]
I just verified that this has been fixed.
