### ISSUE TITLE
Suggestion to make LINQ documentation better (in my opinion)

### ISSUE THREAD

**Issue by egkareem** [dotnet/docs#28606]
This is a suggestion not a problem!
For subjects such as LINQ it would help to put together a simple model of 3 related classes with test data so that the learner could test the queries you put and better understand the subject.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888d4d4e-48ca-db9d-e36d-006f4aeeb83b
* Version Independent ID: ac336cb4-251f-51d1-c35e-cc3693677f41
* Content: [Query expression basics (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-expression-basics)
* Content Source: [docs/csharp/linq/query-expression-basics.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/query-expression-basics.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 157259](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157259)

**Comment by BillWagner** [comment]
Thanks for adding this suggestion @egkareem 

That is on our roadmap, but it will likely be a while.
