### ISSUE TITLE
Article isn't clear on how to handle IAsyncDisposable without IDisposable

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docs#28630]
If I read the article right, it is OK to implement _only_ `IAsyncDisposable` without `IDisopsable` (also for non-sealed classes, the article could be clearer in that regard).

But the article does not show a _full_ example on how the async disposable pattern looks like when `IDisposable` is not implemented. The first full example shown (in [Implements the async dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern)) already has `IDisposable` implemented.
In fact, right thereafter the article then says:
> You may need to implement both the IDisposable and IAsyncDisposable

Yes, we already did that right in the example above.

I think the article should be a bit clearer on how to handle `IAsncDisposable` alone and include a full example for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @bitbonk, thank you for posting this issue. I agree with you that this article needs some work, and the points that you raise are valid. I'll work on addressing this.

**Comment by IEvangelist** [comment]
Related to #28630

**Comment by lg2de** [comment]
@IEvangelist, you agreed with @bitbonk that the article must explain the use of `IAsyncDisposable` alone.
But now you have closed this issue together with the PR which reports (only) a potential resource leak.
I still don't find an explanation for the correct implementation of `IAsyncDisposable` WITHOUT `IDisposable` in the article. I think this issue is still to be finished and should be reopened.

**Comment by bitbonk** [comment]
@IEvangelist I agree. Even with the new change, the article still reads that it is OK to _only_ implement `IAsyncDisposable` (without `IDisposable` and yet the article does now show how this is done.

There is a header for the async-only dispose pattern: [Implement the async dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern).
And there is a header for the sync+async dispose pattern: [mplement both dispose and async dispose patterns](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-both-dispose-and-async-dispose-patterns).

But _both_ examples implement `IAsyncDisposable` _and_ `IDisposable`. Both examples are almost the same.
Event weirder: The chapter _Implement both dispose and async dispose patterns_ begins with the text
> You may need to implement both the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) and [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable) interfaces

Which seems to convey that were are now introducing `IDisposable` to the mix, but we did that aready in the example right before that.

After reading the article now, we still don't now how to implement `IAsyncDisposable` only.

**Comment by CasperWSchmidt** [comment]
@IEvangelist that was a lousy way to close this issue. You agree that the article needs work but then gets away with just adding a simple warning box?

**Comment by IEvangelist** [comment]
Hey @bitbonk and @CasperWSchmidt, I've been having trouble with my "at mentions" not notifying me, I've since fixed that issue - but I did admittedly miss this. Sorry, please see #32040 and let me know what you think. Thank you for your patience.

**Comment by CasperWSchmidt** [comment]
@IEvangelist It's a bit harder to read the markup than seeing it live, but it looks good. When can we expect the changes to be live?

**Comment by IEvangelist** [comment]
> @IEvangelist It's a bit harder to read the markup than seeing it live, but it looks good. When can we expect the changes to be live?

Hi @CasperWSchmidt - it's live now: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern
