### ISSUE TITLE
Generic constraints and records

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#28646]
In "Generic constraints", you have

> There's no generic constraint that requires a type to be a record.

OK.

> Records satisfy either the class or struct constraint.

Not so! A record is a reference type while the `struct` constraint requires a value type. A record does satisfy a `class`, `class?`, or specific base "class" constraint.

> To make a constraint on a specific hierarchy of record types, put the constraint on the base record as you would a base class. 

OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
A record can be a class or a struct. If it's declared as `record` or `record class`, it satisfies `class` constraint. If it's declared as `record struct`, it satisfies the `struct` constraint.

I think that's what the documentation meant by "Records satisfy either the class or struct constraint". The *same* record doesn't satisfy both constraints for sure.
