### ISSUE TITLE
Adding support for records as type constraints

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#28647]
The table entries for `where T : class` and `where T : class?` should include records in the "allowed argument" types.

The table entry `where T : <base class name>?` needs to allow for base records as well as base classes. As such, it might be useful to also change the entry lead-in to `where T : <base class or base record name>?`.

-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on type parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
"record" in general can be a class or a struct. If the documentation will be updated to mention records, I think it should say *record classes* not just *records*.

**Comment by RexJaeschke** [comment]
I'm coming to this from a V9 point-of-view (I'm writing the spec for records for the V9 C# standard), when records are simply class-like types. But now you have alerted me to the fact that V10 added record structs as well, and rebranded V9 records as record classes, I agree that the on-line tutorial material should reflect the current product release and its terminology.

**Comment by BillWagner** [comment]
We should update this.

I want to keep this in the backlog until we resolve the spec discussion on if we consider `record` to modify either a `class` or a `struct` declaration, or introduce a type on its own.
