### ISSUE TITLE
hello everyone

### ISSUE THREAD

**Issue by maleekEngine** [dotnet/docs#28658]
how to get the data from objects that returned from class
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b30ebe-b640-449b-3602-9891a55794db
* Version Independent ID: dd937177-98f0-a797-d49b-29332aae0614
* Content: [Anonymous Types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/anonymous-types)
* Content Source: [docs/csharp/fundamentals/types/anonymous-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/anonymous-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @maleekEngine

This question is a bit vague, but I'll try to answer. When you create an anonymous type, you can get values from just like you would any other object.

```csharp
var anonymous = new
{
    Name = "David Pine",
    Age = 37
};

var str = $"{anonymous.Name} is {anonymous.Age} years old.";
System.Console.WriteLine(str);

// David Pine is 37 years old.
```

[Check out this Sharplab to run this code](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8BuEyABBDAPYwCeY5qAzsQLzEwCmA7gLABQA3r2JDiAOQhg2zYgCIAIhHxQMxAAqw20uIOEBBAOaSWAZgDsvAL4BuXr0Il6CEiwAk0vmUo069AHRiJ5sRQjO4U1LQMPvpsgVRsRIzkADYYPtLWPAACAIw+OQCcABQOyACUGbwA9JXE8orKauxBjKbEcQnEyalAA=). I'm going to close this issue, if you have another question - please open a new issue. If you have a follow up question, feel free to ask it here.
