### ISSUE TITLE
Not able to found the migration changes of eShopLegacyMVC in eShopModernizaing GitHub Repo. 

### ISSUE THREAD

**Issue by nitin27verma** [dotnet/docs#28651]
Hi,
The repo link which is given at the end of this page [eShopModernizing GitHub repository](https://github.com/dotnet-architecture/eShopModernizing) is not showing the migration changes that are discussed in the page for **eShopLegacyMVC**. 
I tried to found in different branches of eShopLegacyMVC/ eShopModernizedMVC as well but no luck. Can some one please share the **final repo link** of "**Migrated eShopLegacyMVC to ASP.NET Core** if available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3399e2a-4993-96d4-cc3b-50be77d3bbcd
* Version Independent ID: 5cea2482-c0ef-a804-ab26-82acdac121e5
* Content: [Example migration of eShop to ASP.NET Core](https://docs.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/example-migration-eshop)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/example-migration-eshop.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/example-migration-eshop.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

**Comment by ardalis** [comment]
Hi @nitin27verma - I'm not seeing the repo link at the bottom of that page. I've looked a couple of times but figure at this point better to just ask you for clarification. Can you put the link here or a screenshot? I'm trying to assist you in locating the final changes branch/repo/version you're looking for. Thanks.

**Comment by erjain** [comment]
Hi @nitin27verma, just checking if you had a chance to share the above details as mentioned by @ardalis.

**Comment by nishanil** [comment]
Closing this issue. Please reopen if you need further assistance.
