### ISSUE TITLE
.Net Deneyimi

### ISSUE THREAD

**Issue by omercangs** [dotnet/docs#28654]
[Geri bildiriminizi buraya girin]
Çok keyifli bir .Net deneyimiydi. C# dökümanlarını kurcalarken kendimi bu deneyim içinde buldum.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 8557d001-9b33-e5d6-5bef-3601d49927fe
* Version Independent ID: 34dcf0cc-d886-cdb3-0a0f-03203eae6d82
* Content: [Dallar ve döngüler - C# etkileşimli öğreticiye giriş](https://docs.microsoft.com/tr-tr/dotnet/csharp/tour-of-csharp/tutorials/branches-and-loops?tutorial-step=1)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the comments @omercangs 

I'll close this as kudos.
