### ISSUE TITLE
Extra note related to .NET Core Needed

### ISSUE THREAD

**Issue by UchiTesting** [dotnet/docs#28671]
Good Afternoon,

I am currently going through the documentation for globalization and I tried a few of the snippets.
As of now I use .NET 6 to try codes.
I had error messages regarding missing data for code page 737.

```
An unhandled exception of type 'System.NotSupportedException' occurred in System.Private.CoreLib.dll: 'No data is available for encoding 737. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'
```

Looking up for the problem had me end-up on that [CodePagesEncodingProvider Class @MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider?redirectedfrom=MSDN&view=net-6.0#remarks) page.
I had to install an extra NuGet package to make it work.

In CLI

`dotnet add package System.Text.Encoding.CodePages`

Then the code shall be updated as follows

```diff
using System;
using System.IO;
using System.Text;

public class Example
{
    public static void Main()
    {
        // Represent Greek uppercase characters in code page 737.
        char[] greekChars = { 'Α', 'Β', 'Γ', 'Δ', 'Ε', 'Ζ', 'Η', 'Θ',
                            'Ι', 'Κ', 'Λ', 'Μ', 'Ν', 'Ξ', 'Ο', 'Π',
                            'Ρ', 'Σ', 'Τ', 'Υ', 'Φ', 'Χ', 'Ψ', 'Ω' };

+        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        Encoding cp737 = Encoding.GetEncoding(737);
        int nBytes = cp737.GetByteCount(greekChars);
        byte[] bytes737 = new byte[nBytes];
        bytes737 = cp737.GetBytes(greekChars);
        // Write the bytes to a file.
        FileStream fs = new FileStream(@".\\CodePageBytes.dat", FileMode.Create);
        fs.Write(bytes737, 0, bytes737.Length);
        fs.Close();

        // Retrieve the byte data from the file.
        fs = new FileStream(@".\\CodePageBytes.dat", FileMode.Open);
        byte[] bytes1 = new byte[fs.Length];
        fs.Read(bytes1, 0, (int)fs.Length);
        fs.Close();

        // Restore the data on a system whose code page is 737.
        string data = cp737.GetString(bytes1);
        Console.WriteLine(data);
        Console.WriteLine();

        // Restore the data on a system whose code page is 1252.
        Encoding cp1252 = Encoding.GetEncoding(1252);
        data = cp1252.GetString(bytes1);
        Console.WriteLine(data);
    }
}
// The example displays the following output:
//       ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ
//       €‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’""•–—
```

Best Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cff6f0-361c-2963-9f9b-afb4fb0dfb62
* Version Independent ID: 608a6cdc-926c-fd78-79e5-8101cfcd61c5
* Content: [Globalization](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization)
* Content Source: [docs/core/extensions/globalization.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/globalization.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gregoryagu** [comment]
Was this sample updated?  I just ran into the same issue when running the sample code, and updated it to match what is in this issue and it then run correctly.
