### ISSUE TITLE
Wrong!

### ISSUE THREAD

**Issue by ChrisM-1231** [dotnet/docs#28680]
The command on Windows:  **dotnet new --uninstall .\**

Does NOT work!  You have to enter the ENTIRE and COMPLETE, FULL Path that contains the .template..config folder. DO NOT include  a trailing slash either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@ChrisM-1231 Hello, sorry this isn't working for you. I just went and verified with some other templates I have that the commands do work. Can you please give more information about what version of dotnet you're running, which sdk/runtimes are installed, and verify that your terminal was currently navigated to the folder where the _.template.config_ folder exists. Here is an example of myself running it successfully:

![image](https://user-images.githubusercontent.com/67293991/158639257-5a8d8852-e693-40ed-a2ae-a749f5456315.png)

**Comment by ChrisM-1231** [comment]
I have all the frameworks installed on this machine and all the dotNET Core stuff as well. I followed the directions on the page explicitly and double checked everything 3 times. What’s interesting is the same steps repeated a second time yielded different results. For example, I’m STILL not quite certain exactly HOW I was finally able to remove my test templates.

Chris Millensifer
Senior Software Developer
303-518-4402
***@***.******@***.***>
www.zolldata.com<http://www.zolldata.com/>

***@***.***
An Asahi Kasei Group Company

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized use or disclosure is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

***@***.***<https://events.bizzabo.com/367009>
