### ISSUE TITLE
"Configuring Nuget Behaviour" broken link

### ISSUE THREAD

**Issue by dutts** [dotnet/docs#28683]
**Issue description**

Some documentation pages contain links to [Configuring Nuget Behavior](https://github.com/dotnet/docs/blob/main/nuget/consume-packages/configuring-nuget-behavior) which gives a 404.

The following documentation pages contain this broken link:

https://github.com/dotnet/docs/blob/main/includes/cli-configfile.md
https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-push.md
https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-install.md
https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-trust.md
https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-restore.md

I am unable to locate `configuring-nuget-behavior.md` anywhere so cannot update the broken links.

**Comment by gewarren** [comment]
@dutts The links are only broken in the GitHub UI. If you're reading these files on docs.microsoft.com, they redirect correctly (e.g. [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push#description)).

However, if you'd like to update them to point to the [new target](https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior), that would be fantastic!

**Comment by dutts** [comment]
> However, if you'd like to update them to point to the [new target](https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior), that would be fantastic!

Will do that now, thanks.

**Comment by adegeo** [comment]
Hi @dutts Please see my comment here: https://github.com/dotnet/docs/pull/28794#issuecomment-1077765019

These links are correct and do work from the published site. I'll close this issue as I don't believe it is an actual problem. Cheers!

**Comment by gewarren** [comment]
Sorry, yes, I misunderstood. I thought the link targets were redirecting. We are required to omit the "docs.microsoft.com" part of URLs so that these links work in "air-gapped" environments. I guess it does break the experience in GitHub, which is unfortunate.

**Comment by dutts** [comment]
Ah apologies, I never realised that the documentation wasn’t meant to be used like that from the GitHub side, I always seem to end up there for some reason. No worries anyway.
