### ISSUE TITLE
Book PDF link doesn't load

### ISSUE THREAD

**Issue by boshamed** [dotnet/docs#28699]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 730c6504-d88d-b5bc-fcac-4d51ac6642bd
* Version Independent ID: b376273f-67dd-4a54-97c5-bcb49dc36932
* Content: [DevOps for ASP.NET Core Developers](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/)
* Content Source: [docs/architecture/devops-for-aspnet-developers/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/index.md)
* Product: **dotnet-architecture**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by erjain** [comment]
I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by nishanil** [comment]
I tested the links referenced on the mentioned page and it is working. May be an interim issue. Please reopen if you are still facing troubles.
