### ISSUE TITLE
Writing Console Apps: Overview and moving pieces

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#287]
Issue tracking new topic at http://dotnet.github.io/docs/core-concepts/console/overview.html

**Comment by blackdwarf** [comment]
Do we need this for build?

**Comment by cartermp** [comment]
It seems like this would be describing things like the shared runtime, shared framework, etc; which are higher-order bits than just console apps.

Perhaps there could be a pivot for creating self-contained console apps?  It sounds like that's not something necessary for //Build, though.

**Comment by BillWagner** [comment]
@mairaw @cartermp I propose we close this, as we've organized the topics discussed above in a different fashion. 

Can you vote with a :+1: or :-1: ?

**Comment by BillWagner** [comment]
Closing based on discussion.
