### ISSUE TITLE
cant get oem settings

### ISSUE THREAD

**Issue by jereytucker** [dotnet/docs#28702]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901ed659-bdf5-061c-cfbf-762932e234d5
* Version Independent ID: 36fe704a-6442-344c-3013-180f4ed89150
* Content: [See installed .NET Framework security updates and hotfixes - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Hi @jereytucker can you provide more information? I'm unsure what you mean by oem settings.
