### ISSUE TITLE
docs say bydefault but don't explain how to override default behaviour

### ISSUE THREAD

**Issue by drdamour** [dotnet/docs#28713]
>View types have the accessibility modifiers internal and sealed, by default

these docs should link to a way to override this default beahviour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcdf9d6-9421-26d6-ec13-c5f738853c0f
* Version Independent ID: 8148e6db-5c24-5e6e-f0d1-85bd3a93d7b1
* Content: [Breaking change: Razor: Compiler now produces a single assembly - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/razor-compiler-doesnt-produce-views-assembly)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/razor-compiler-doesnt-produce-views-assembly.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/razor-compiler-doesnt-produce-views-assembly.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Ping @captainsafia.

**Comment by captainsafia** [comment]
We don't support changing the modifiers on the generated code at the moment.
