### ISSUE TITLE
Typos found in Host Configuration section

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/docs#28711]
They look like typos, right?

![test](https://user-images.githubusercontent.com/50270635/158731545-63d95d75-1e1d-4372-8d5f-2022473c308f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9
* Version Independent ID: 22a12ff8-d2ff-a841-b9bb-e2fd1032bc04
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host)
* Content Source: [docs/core/extensions/generic-host.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/generic-host.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @pstricks-fans,

Thank you for posting this issue. In looking through this, it's not a typo. It's stating that the host configuration is available for consumption when consumers are calling `ConfigureAppConfiguration`.
