### ISSUE TITLE
.NET SDK version specification

### ISSUE THREAD

**Issue by Scensna** [dotnet/docs#28727]
Great docs, thanks a lot.

However, I have a small adjustment. Source generators doesn't work for me with version of .NET SDK 6.0.100 (msbuild 17.0). It works only with new update - .NET SDK 6.0.201 (msbuild 17.1). If possible and it is not a bug, please mention it on docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @jmarolf 

Is this a known issue?

**Comment by Youssef1313** [comment]
@Scensna Can you please define "how" it doesn't work? and what version of `Microsoft.CodeAnalysis` are you using? It's known that each version of `Microsoft.CodeAnalysis` requires a minimum version of .NET SDK.

So you probably was using a `Microsoft.CodeAnalysis` version that requires .NET SDK 6.0.201. In this case you need to do one of the following:

- Upgrade to newer .NET SDK (as you already did)
- Downgrade Microsoft.CodeAnalysis to an older version.

**Comment by Scensna** [comment]
@Youssef1313 That is possible, thanks. I missed this information somehow. I used version 3.3.3 of Microsoft.CodeAnalysis with .NET SDK 6.0.100.

The original problem was that the final dll file missed methods and variables from generated code (checked by dotpeek). But as you said, it was solved by upgrading .NET SDK to 6.0.201 and I just missed the information about version combination.

**Comment by Youssef1313** [comment]
@Scensna I think 3.3.3 should be compatible with any version of .NET 6.

@jmarolf got any idea what could have happened?
