### ISSUE TITLE
Runtimes not uninstlled

### ISSUE THREAD

**Issue by Fisseha-Estifanos** [dotnet/docs#28737]
It says removing SDK will also uninstall runtimes that came with that sdk. But all the runtimes are still not uninstalled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I can't find where this is stated. I'm not sure if my eyes are just glossing over it again and again. Can you please point it out?
