### ISSUE TITLE
I can't use WinRT Components.

### ISSUE THREAD

**Issue by Gavin-Williams** [dotnet/docs#28741]
I pretty much hate C++/WinRT, it hardly ever works, templates are broken, I can't just use runtime components the way I would think they should be used. Overly complicated and fragile.

I have a C# project (Blank WinUI), I have a Runtime Component (WinUI3) C++. 
* In the C# project, I've added a reference to the runtime component. 
* I've had to fiddle with Target OS to make it compatible.

But I have this error when I try to run the app...

> Error	NETSDK1130	WrapperNative.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130	Studio	C:\Program Files\dotnet\sdk\6.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1003	

When I look at the docs page mentioned in the error, it doesn't seem at all relevant to what I'm doing. It says 'Built-in support for consumption of [Windows runtime (WinRT)](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system) APIs in .NET is removed.' - OK, that's fine, nothing to do with me. I'm just trying to run my app that calls a runtime component. Presumably whatever you replaced it with has been integrated into your ecosystem by now.

So why doesn't it work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89386880-58e3-4b43-ca1b-35c853cf2960
* Version Independent ID: 01439b36-a838-bb3c-0843-1f7f35c05c4a
* Content: [Breaking change: Built-in support for WinRT is removed from .NET - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed)
* Content Source: [docs/core/compatibility/interop/5.0/built-in-support-for-winrt-removed.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/interop/5.0/built-in-support-for-winrt-removed.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
@Gavin-Williams Hello. Without seeing your project files, it's hard to triage why it's giving you this error. However, considering you're mostly working with WinUI, you may want to ask in there documentation or support forums. I don't know that we have a lot of experience here in this repository. 

If you look at the end of the support page, it says to check out https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance for more information. Looking there it says to target a windows-specific TFM, like this one:

```xml
<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
```

If that doesn't work, I would use the github feedback link on that specific page. The author of that article would probably be better suited to help you. Please let us know if that solves your issue or if you're going to move on there to ask for support.

Thanks and sorry I can't be of much help.

**Comment by adegeo** [comment]
For now, I'll close this issue as I don't think there is much we can do. If you feel it should be reopened, please feel free to do so!

**Comment by smourier** [comment]
FWIW, I had the same issue and to solve it, you just need to add the Microsoft.Windows.CsWinRT nuget package https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/ as a reference to the C# project.

IMHO, the documentation could be updated to reflect that as it's very far from being obvious.

**Comment by gewarren** [comment]
@tdykstra Should aka.ms/netsdk1130 be updated to point to https://docs.microsoft.com/dotnet/core/tools/sdk-errors/netsdk1130 instead?

**Comment by gewarren** [comment]
@angelazhangmsft Should we update the [NETSDK1130 doc](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1130) with guidance to add the https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/ package as a reference to the C# project?

**Comment by angelazhangmsft** [comment]
@gewarren sure, although I see it's already listed as guidance: 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/69016571/160712287-2f2fd0cb-b9da-468b-9fe4-d5ea5be89ce3.png">

There are 2 scenarios here:
1. Developers are trying to access Windows SDK APIs in .NET 5 or later. In this scenario, they shouldn't reference the CsWinRT package
2. Developers are trying to consume a 3rd party runtime component (defined in a winmd file) . In this scenario, they should add a reference to the CsWinRT package and refer to the [C#/WinRT docs](https://aka.ms/cswinrt) on how to generate the C# projection.

**Comment by gewarren** [comment]
Thanks @angelazhangmsft. Do you have permissions to update the aka.ms link for NETSDK1130? I don't.

**Comment by angelazhangmsft** [comment]
> Thanks @angelazhangmsft. Do you have permissions to update the aka.ms link for NETSDK1130? I don't.

Yes - updated the aka.ms link.

**Comment by gewarren** [comment]
Thanks @angelazhangmsft. I'm going to close this issue now.
