### ISSUE TITLE
Duplicate "use" in page "Xamarin Tutorial - Build your first iOS & Android app in C#"

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/docs#28759]
**Issue description**

In the first full sentence of this page you'll see the word "use" twice in a row:

"To debug with an Android device, you can either configure your Android device to connect to Visual Studio or **use use** an emulator."

**Comment by gewarren** [comment]
@mairaw Looks like this tutorial is on dotnet.microsoft.com. Could you fix this typo?

https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/devicesetup

**Comment by mairaw** [comment]
Thanks for pinging me @gewarren and @MSLukeWest for reporting the issue. I've opened a PR in our repo to fix this. It should go live soon.

**Comment by IEvangelist** [comment]
> Thanks for pinging me @gewarren and @MSLukeWest for reporting the issue. I've opened a PR in our repo to fix this. It should go live soon.

PR approved, thanks @mairaw
