### ISSUE TITLE
Ubuntu 20.10 install failure

### ISSUE THREAD

**Issue by markybry** [dotnet/docs#28750]
The install fails unless you remove the previous package manually as per this post.

https://github.com/dotnet/docs/issues/26879

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu#apt-troubleshooting)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Ubunutu 20.10 isn't supported with .NET 6. Is that what you were using? I'm unsure how to help you or how to improve the documentation.
