### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by alexandermorgan** [dotnet/docs#28767]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ccca52-98a8-d79c-035d-6cfa3d11352e
* Version Independent ID: e1bfe7d8-a428-5801-6f6a-bfc06110d362
* Content: [Remove elements, attributes, and nodes from an XML tree - LINQ to XML](https://docs.microsoft.com/en-us/dotnet/standard/linq/remove-elements-attributes-nodes-xml-tree)
* Content Source: [docs/standard/linq/remove-elements-attributes-nodes-xml-tree.md](https://github.com/dotnet/docs/blob/main/docs/standard/linq/remove-elements-attributes-nodes-xml-tree.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hello @alexandermorgan You'll need to add the `System.Xml.Linq` namespace to your code. I believe this is what you're missing. Everything to do with the linq XML content requires [that namespace](https://docs.microsoft.com/en-us/dotnet/standard/linq/linq-xml-classes-overview).
