### ISSUE TITLE
How to provide EventHub consumer group ?

### ISSUE THREAD

**Issue by kiranpradeep** [dotnet/docs#28773]
If I need to have mulitple consumers, I need to provide consumer group. Can that be add that to this sample?

Also this sample is using Kafka surface! To be honest, I was disappointed - or else the document be retitled as _Connect .NET for Apache Spark to Apache Kafka_. Is it possible to provide native [clean](https://github.com/Azure/azure-event-hubs-spark) EventHub sample without involving Kafka surface. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2625dc76-70f0-d481-2c90-2c65339f21bb
* Version Independent ID: 24e94c5c-006c-a8b6-bc92-15590ebc0c59
* Content: [Connect .NET for Apache Spark to Azure Event Hubs](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/connect-to-event-hub)
* Content Source: [docs/spark/how-to-guides/connect-to-event-hub.md](https://github.com/dotnet/docs/blob/main/docs/spark/how-to-guides/connect-to-event-hub.md)
* Product: **dotnet-spark**
* GitHub Login: @Niharikadutta
* Microsoft Alias: **nidutta**

**Comment by gewarren** [comment]
We're no longer updating the .NET for Apache Spark documentation and have archived it to https://learn.microsoft.com/previous-versions/dotnet/spark/what-is-spark. As a result, we're closing all the active .NET for Apache Spark issues. I'm sorry we couldn't address your issue.
