### ISSUE TITLE
Version binding for .NET Core 2.0

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2880]
We need to explain the .NET Core roll forward policy. Will .NET Core 1.0 and 1.1 apps run on .NET Core 2.0 when neither a 1.0 nor a 1.1 runtime is installed?

Background info: https://github.com/dotnet/designs/issues/3

Should probably be under https://docs.microsoft.com/en-us/dotnet/core/versions/

**Comment by mairaw** [comment]
@richlander who would be a good person to chat about this?

**Comment by BillWagner** [comment]
raising priority as this has been bumped several times.
