### ISSUE TITLE
Tenets and Description table misspelled Tenets as Tenants

### ISSUE THREAD

**Issue by kappa-mu** [dotnet/docs#28818]
Tenets and Description table misspelled Tenets as Tenants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03831099-3360-98e5-d35b-934a024f88e0
* Version Independent ID: 7bf71b44-4b61-9832-28c2-8f4881199829
* Content: [What is Cloud Native?](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/definition)
* Content Source: [docs/architecture/cloud-native/definition.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/definition.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @kappa-mu, Thanks for pointing it out, we will correct it.
