### ISSUE TITLE
F# Azure Table Storage sample is broken

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/docs#28828]
**Issue description**

The [F# Azure Table Storage sample](https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-on-azure/table-storage) is broken. The main culprit is this:

```fsharp
type Customer(firstName, lastName, email: string, phone: string) =
    interface ITableEntity with
        member this.ETag
            with get (): ETag = 
                raise (System.NotImplementedException())
            and set (v: ETag): unit = 
                raise (System.NotImplementedException())
        member this.PartitionKey
            with get (): string = 
                raise (System.NotImplementedException())
            and set (v: string): unit = 
                raise (System.NotImplementedException())
        member this.RowKey
            with get (): string = 
                raise (System.NotImplementedException())
            and set (v: string): unit = 
                raise (System.NotImplementedException())
        member this.Timestamp
            with get (): Nullable<DateTimeOffset> = 
                raise (System.NotImplementedException())
            and set (v: Nullable<DateTimeOffset>): unit = 
                raise (System.NotImplementedException())
    new() = Customer(null, null, null, null)
    member val Email = email with get, set
    member val PhoneNumber = phone with get, set
    member val PartitionKey = lastName with get, set
    member val RowKey = firstName with get, set
```

The member properties all return exceptions. I'm not sure if this code was accidentally added instead of the valid code or never tested, but if you copy this code and try it out, it'll pop as soon as you try to access e.g. PKey or RKey.

There's no direct equivalent C# sample but I looked for some on docs and found a few e.g. [here](https://docs.microsoft.com/en-us/azure/cosmos-db/table/create-table-dotnet?tabs=azure-portal%2Cvisual-studio) which uses a very different approach of using the `TableEntity` type instead of `ITableEntity` and mapping between that and a normal POCO (something that is common to do in F# too, with a record).

I've tried fixing the sample:

```fsharp
type Customer(firstName, lastName, email: string, phone: string) =

    interface ITableEntity with
        member val PartitionKey = lastName with get, set
        member val RowKey = firstName with get, set
        member val Timestamp = Nullable() with get, set
        member val ETag = ETag null with get, set

    new() = Customer(null, null, null, null)
    member val Email = email with get, set
    member val PhoneNumber = phone with get, set
```

but this code gives an error (at least, from Azurite):

```
Azure.RequestFailedException: An error occurred while processing this request.
RequestId:d0f242b0-c511-4bd8-84bf-d072debc64e1
Time:2022-03-28T11:21:44.798Z
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"An error occurred while processing this request.\nRequestId:d0f242b0-c511-4bd8-84bf-d072debc64e1\nTime:2022-03-28T11:21:44.798Z"}}}

Headers:
Server: Azurite-Table/3.16.0
x-ms-error-code: REDACTED
x-ms-request-id: d0f242b0-c511-4bd8-84bf-d072debc64e1
x-ms-version: REDACTED
Date: Mon, 28 Mar 2022 11:21:44 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8

   at Azure.Data.Tables.TableRestClient.InsertEntity(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.AddEntity[T](T entity, CancellationToken cancellationToken)
   at <StartupCode$FSI_0095>.$FSI_0095.main@()
Stopped due to error
```

Unfortunately there's no really clue here as to what the offending field is, and I'm not sure if this is an "I've not populated the ITableEntity correctly" vs "Azurite issue" vs something else.

If you use a normal `TableEntity` this works fine e.g.

```fsharp
let t = TableEntity (dict [ "PartitionKey", "Harp"; "RowKey", "Walter"; "Email", "Walter@contoso.com"; "PhoneNumber", "425-555-0101" ])
table.AddEntity t
```

Happy to submit a PR with the correct code fix, but without e.g. seeing a valid C# sample, it's hard to do that.

**Comment by isaacabraham** [comment]
I've also tried something as simple as the following but even this fails:

```fsharp
type Customer() =
    interface ITableEntity with
        member val PartitionKey = "" with get, set
        member val RowKey = "" with get, set
        member val Timestamp = Nullable() with get, set
        member val ETag = ETag() with get, set

let customer = Customer() :> ITableEntity
customer.PartitionKey <- "Harp"
customer.RowKey <- "Walter"

table.AddEntity customer |> ignore
```

**Comment by jsquire** [comment]
Hi @isaacabraham.   Thank you for your feedback.   You're correct - the sample definitely appears to be broken.   I can't speak to the history, but we'll reach out to the authors and work with them to get things fixed up.

> I'm really confused by this. We basically need to make a shadow member that is the same name as the interface member to get it to work.

The Tables library does not allow for explicit interface implementation during serialization; it expects `ITableEntity` to be implicitly implemented.  I can't speak to the history behind this decision, but I would certainly agree that this creates a poor F# developer experience.  There is an open feature request in the Azure SDK for .NET repository that would address this, [#26514](https://github.com/Azure/azure-sdk-for-net/issues/26514).   I'll link this issue there as an example.  It would be helpful if you're able to upvote.

**Comment by isaacabraham** [comment]
@jsquire great, thank you. I'd be happy to make a PR for this and show how to use it with records as well (which most F# developers will be familiar with).

@dsyme libraries like this would certainly benefit from implicit interface implementations -  especially if that was also applied into records, which I believe (with CLIMutable) would make for a relatively seamless experience whilst also sticking to what most F# developers prefer (records).

**Comment by jsquire** [comment]
> @jsquire great, thank you. I'd be happy to make a PR for this and show how to use it with records as well (which most F# developers will be familiar with).

If you're willing, that would be fantastic!   I'd be happy to shepherd that through approvals and ensure that it gets merged.
