### ISSUE TITLE
Access modifiers

### ISSUE THREAD

**Issue by onyangofred** [dotnet/docs#28831]
Great article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @onyangofred, I know that @BillWagner always appreciates positive feedback. Thank you for your kind words, I'm going to close this.

**Comment by onyangofred** [comment]
I definitely would recommend a quick read for anyone looking for a refresher course overview. Kindly go ahead and close this.
