### ISSUE TITLE
Where is the developerpack?

### ISSUE THREAD

**Issue by gggrax** [dotnet/docs#28841]
Hi, I was working on a Python program in Visual Studio 2022, but it had an error: install DeveloperPac .NETFramework  SDK/Targeting Pack from https://aka.ms/msbuil/developerpacks,  but I've looked around there and don't see how to download and install any developerpacks.  Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@ggrax I'm not totally sure how to help you. There are download links for the various developer packs in the article. These links take you to the appropriate developer pack/runtime download page:

![image](https://user-images.githubusercontent.com/67293991/160898651-a9c5190e-c5e2-4f69-9faa-7e52c0417a3a.png)

**Comment by gggrax** [comment]
Thanks Andy,  I was able to resolve it.  There was a bug in Visual Studio 2022 where it pointed to a version 4.0 of .NET which apparently doesn’t exist.  They put out a hotfix, and apparently corrected it.  Thanks a lot for your reply!

 

Greg
