### ISSUE TITLE
Null Testing

### ISSUE THREAD

**Issue by onyangofred** [dotnet/docs#28843]
Wow, 
This is such a great article. 
Simplifies the code readability 
a??=56;
//that would have been
if(a==null) a=56;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 038ae35e-c5e9-e1a4-a6dd-afe379201245
* Version Independent ID: d73f3d5a-00d4-2e22-c120-8e8d6d101a54
* Content: [?? and ??= operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator)
* Content Source: [docs/csharp/language-reference/operators/null-coalescing-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/null-coalescing-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @onyangofred 

I'll close this as "kudos"
