### ISSUE TITLE
Add Link to Community Toolkits documentation landing page from .NET Index

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#28852]
**Issue description**
We have a new landing home page for the .NET based Community Toolkits here: https://docs.microsoft.com/dotnet/communitytoolkit/

We'd like to get the link setup now from the landing page of the .NET index.

We'd suggest adding it underneath the link to the .NET Developer Community here:

https://github.com/dotnet/docs/blob/dbf0e0e5d1f39bfaa40f2adc4a11b6c36bf2ac7c/docs/index.yml#L79-L81

So, suggesting:

```
 - url: https://dotnet.microsoft.com/platform/community 
   itemType: whats-new 
   text: .NET developer community 
 - url: /communitytoolkit/
   itemType: overview
   text: Community Toolkits
```

We wanted to create an issue first in case there was a better suggestion on where to link this content on the index page. Thanks!

FYI @brminnick @Sergio0694

**Comment by gewarren** [comment]
FYI @davidbritch

**Comment by gewarren** [comment]
@michael-hawker I am fine with this change if you want to go ahead with a PR!

**Comment by michpara** [comment]
Is this issue still open and can I pick it up?

**Comment by michael-hawker** [comment]
Thanks @michpara for taking this on! I think I just didn't know where it needed to be added. So appreciate you taking the helm here. 🦙❤
