### ISSUE TITLE
Sample shows incorrect means of setting exit code

### ISSUE THREAD

**Issue by AArnott** [dotnet/docs#28868]
This page shows a `Task<int>` method returning an exit code that is then dropped instead of actually being used to set the exit code for the process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28554e6c-1983-ca7e-e9e0-200578729a28
* Version Independent ID: d8604fab-bf6f-e820-7db8-b22e3d724335
* Content: [How to handle termination in System.CommandLine](https://docs.microsoft.com/en-us/dotnet/standard/commandline/handle-termination)
* Content Source: [docs/standard/commandline/handle-termination.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/handle-termination.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for finding and reporting that, I'm fixing it.
