### ISSUE TITLE
Where are the .net6 local IntelliSense files?

### ISSUE THREAD

**Issue by ahdung** [dotnet/docs#28867]
No .net6 local IntelliSense files in this page:
[https://dotnet.microsoft.com/en-us/download/intellisense](https://dotnet.microsoft.com/en-us/download/intellisense)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b361b8e5-3b89-8e46-6356-ca420e468b69
* Version Independent ID: f66f7a1a-1ab7-dab7-696f-916950c4c518
* Content: [Install localized IntelliSense files - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense)
* Content Source: [docs/core/install/localized-intellisense.md](https://github.com/dotnet/docs/blob/main/docs/core/install/localized-intellisense.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by Flyoutwithme** [comment]
According to https://github.com/dotnet/docs/issues/27283. There is no localized IntelliSense anymore. But what's the cause? Can anyone explain it? 
Thanks.

**Comment by ahdung** [comment]
@Flyoutwithme So I already reported it? totally forgot, unbelievable.

**Comment by StratosBlue** [comment]
@ahdung 
I've write a tool to generate the Localized IntelliSense file. It's still has some problems now. Not all members can generate correctly. But it work.
I think you want a zh-cn Localized IntelliSense [dotnet-intellisense-6.0-zh-cn.zip](https://github.com/dotnet/docs/files/8422839/dotnet-intellisense-6.0-zh-cn.zip). You can try it. It's base on 6.0.3.
![图片](https://user-images.githubusercontent.com/20887303/161877881-7d1027fc-b73b-4d8f-bc4c-6f999a91491a.png)
![图片](https://user-images.githubusercontent.com/20887303/161877912-189dcbe8-839b-42a2-b083-696923be9182.png)
![图片](https://user-images.githubusercontent.com/20887303/161877969-05061ac2-d6ae-41e0-ad21-7fb4acf440f7.png)

**Comment by ahdung** [comment]
@StratosBlue Awesome! Thank you very much. And I'm curious where did your translated text come from, .net5.0?

**Comment by StratosBlue** [comment]
@ahdung 
No. Not translate or from .net5.0. It's from MS's Online document. The code is not friendly to read now. I will open source it's code when I cleaned it.

**Comment by StratosBlue** [comment]
the build tool:
https://github.com/stratosblue/intellisenselocalizer

the updated zh-cn Localized IntelliSense base on 6.0.4
[dotnet-intellisense-6.0.4-zh-cn.zip](https://github.com/dotnet/docs/files/8481966/dotnet-intellisense-6.0.4-zh-cn.zip)

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by ahdung** [comment]
@StratosBlue Chinese and english mixed, could you please fix it?
![微信截图_20220414090215](https://user-images.githubusercontent.com/12094247/163293849-95f5d708-d14e-4c8b-9fcf-b09cd39fff22.png)
![微信截图_20220414090343](https://user-images.githubusercontent.com/12094247/163293858-d663e1a9-0a85-4db3-80a7-2aa2c79fa101.png)

**Comment by StratosBlue** [comment]
@ahdung 
hahahahahaha
It's not a bug but a feature.
When I use it. I found some translate text at the ms online docs is low quality. So I remain origin content to compare it .
There is a Chinese only file. You can try it. And I will make it as a option in the generate tool later.
[dotnet-intellisense-6.0.4-zh-cn-single.zip](https://github.com/dotnet/docs/files/8485665/dotnet-intellisense-6.0.4-zh-cn-single.zip)

**Comment by ahdung** [comment]
@StratosBlue Great! Actually I did guess you're deliberate. mix is not bad, but have option is better.
