### ISSUE TITLE
Error CS0470

### ISSUE THREAD

**Issue by BurAndBY** [dotnet/docs#28860]
Error example please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e755f4f6-b578-d3c9-10b3-c917fe1f741a
* Version Independent ID: bff14002-14f0-9f7d-ad78-c4557dc00e61
* Content: [Compiler Error CS0470](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0470)
* Content Source: [docs/csharp/misc/cs0470.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0470.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@BurAndBY Can you add more details to what you're asking for here? This article does have an example that shows the error, and I want to make sure I address your concern properly.

Thanks.

**Comment by BurAndBY** [comment]
> @BurAndBY Can you add more details to what you're asking for here? This article does have an example that shows the error, and I want to make sure I address your concern properly.
> 
> Thanks.
> 

Yes, it does not have an error.

**Comment by BillWagner** [comment]
@BurAndBY I am still confused. I tried the exact sample shown on this page, and it produces the same compile error shown in the page, on the same line. What am I missing?

**Comment by BurAndBY** [comment]
> @BurAndBY I am still confused. I tried the exact sample shown on this page, and it produces the same compile error shown in the page, on the same line. What am I missing?

OK, a misunderstanding probably happened. I meant something like "error CS1520: Class, struct, or interface method must have a return type"
