### ISSUE TITLE
No info on how to get ICLRAssemblyIdentityManager

### ISSUE THREAD

**Issue by Alovchin91** [dotnet/docs#2886]
## Problem

When hosting CLR, one commonly used interface is [ICLRAssemblyIdentityManager Interface](../blob/306c608/docs/framework/unmanaged-api/hosting/iclrassemblyidentitymanager-interface.md). It is used to get assembly identity from a file, create *ICLRAssemblyReferenceList* instance that can be used by *IHostAssemblyManager* implementation and so on.

Once upon a time, a [GetCLRIdentityManager Function](../blob/306c608/docs/framework/unmanaged-api/hosting/getclridentitymanager-function.md) has been used to get an instance of this interface. Now, the function is marked as deprecated, and there is no information on what can be used instead.

One could think that [ICLRControl::GetCLRManager Method](../blob/306c608/docs/framework/unmanaged-api/hosting/iclrcontrol-getclrmanager-method.md) can be used to get an instance of ICLRAssemblyIdentityManager interface, as is the case with all the other CLR managers, but it's also not working as this method returns E_NOINTERFACE.

## Suggestion

Add explicit documentation on how it is supposed to get access to this interface.

If this interface is no longer supported or recommended, add an appropriate note and instructions on what is expected to be used in place of this interface.

**Comment by mairaw** [comment]
Thanks for filing the issue, @Alovchin91. @karelz who on your team could help with this question?

**Comment by karelz** [comment]
@joshfree @dnlharvey should be able to comment.

I took a look at the source code and it seems that `GetCLRIdentityManager` is the only function which returns the interface (`IID_ICLRAssemblyIdentityManager`). So you will likely need to keep using the deprecated API (one of the side-effects is that it doesn't work well with in-proc side-by-side AFAIR).

Why do you need the API? Can you replace the functionality with managed code? ... Our hosting APIs always felt somewhat bloated to me, I wonder if this is one was really necessary.

**Comment by BillWagner** [comment]
@Alovchin91 Can you provide us more info in response to Karel's question? It will help us understand what the right fix is.

**Comment by Alovchin91** [comment]
@karelz @BillWagner Sure.

The host implements [`IHostAssemblyManager`](../blob/306c608/docs/framework/unmanaged-api/hosting/ihostassemblymanager-interface.md) interface. The first use case for `ICLRAssemblyIdentityManager` is the [`IHostAssemblyManager::GetNonHostStoreAssemblies`](../blob/306c608/docs/framework/unmanaged-api/hosting/ihostassemblymanager-getnonhoststoreassemblies-method.md) method: the documentation states there is no way to get an [`ICLRAssemblyReferenceList`](../blob/306c608/docs/framework/unmanaged-api/hosting/iclrassemblyreferencelist-interface.md) interface pointer other than calling [`ICLRAssemblyIdentityManager::GetCLRAssemblyReferenceList`](../blob/306c608/docs/framework/unmanaged-api/hosting/iclrassemblyidentitymanager-getclrassemblyreferencelist-method.md) method. Although my particular host doesn't implement any custom behavior here, this is the first big flaw in the documentation.

The host also implements [`IHostAssemblyStore`](../blob/306c608/docs/framework/unmanaged-api/hosting/ihostassemblystore-interface.md) interface which is returned from [`IHostAssemblyManager::GetAssemblyStore`](../blob/306c608/docs/framework/unmanaged-api/hosting/ihostassemblymanager-getassemblystore-method.md) method call. Implementation is as following: the host has a list of known assemblies and their identities, and in the [`IHostAssemblyStore::ProvideAssembly`](../blob/306c608/docs/framework/unmanaged-api/hosting/ihostassemblystore-provideassembly-method.md) method implementation this list is being compared with the identity requested by CLR via [`pBindInfo->lpPostPolicyIdentity`](../blob/306c608/docs/framework/unmanaged-api/hosting/assemblybindinfo-structure.md) field.

To get the list of known assemblies' identities the host calls [`ICLRAssemblyIdentityManager::GetBindingIdentityFromFile`](../blob/306c608/docs/framework/unmanaged-api/hosting/iclrassemblyidentitymanager-getbindingidentityfromfile-method.md) method for each known file and maps it to the file path. When the CLR requests known identity, the host opens corresponding file and gives an `IStream` implementation back to the CLR.

Unfortunately, there is no way to replace these calls with managed code since the managed entry point (that is, an AppDomainManager for default domain) is loaded exactly the same way. The host knows the file where it is located, and it requests the identity from the file using `ICLRAssemblyIdentityManager` interface.
