### ISSUE TITLE
Incorrect default value information on "IDE0007 and IDE0008: 'var' preferences" page

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/docs#28862]
The documentation states that the default value for all three options is `true`, i.e. _prefer var_: 
- `csharp_style_var_for_built_in_types`
- `csharp_style_var_when_type_is_apparent`
- `csharp_style_var_elsewhere`

This is in fact incorrect. The actual default value for all three options is `false`, i.e. _prefer explicit type_.

See also https://github.com/dotnet/roslyn/issues/57359 for additional discussion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e99e36-a3b1-ac38-c66d-905d9be1fa01
* Version Independent ID: d035351b-536b-6f80-69ac-4d12527284c3
* Content: [IDE0007 and IDE0008: 'var' preferences - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you @ArturDorochowicz
