### ISSUE TITLE
using ExtensionMethods;

### ISSUE THREAD

**Issue by Luuk34** [dotnet/docs#28873]
[Enter feedback here]
`using ExtensionMethods;`  gives an error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ExtensionMethods' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApp17	C:\....\Program.cs	5	Active

- Target framework: .NET 6.0
- On this page is said that `using ExtensionMethods` is needed (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Extension Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @Luuk34,

Could you please share all of the code that you have? If the `namespace ExtensionMethods` exists, that should work. Is it possible that you didn't create it?

**Comment by Luuk34** [comment]
The problem was that I was having the wrong namespace where it should have been `ExtensionMethods`.
