### ISSUE TITLE
Bad guidance regarding global.json usage

### ISSUE THREAD

**Issue by MeikTranel** [dotnet/docs#28886]
The current version of this page reads like a general recommendation not to use global.json files. This is harmful imo. This may be due to the history of the global.json; once upon a sad time we were not able to set relaxation rules regarding enforcement, so someone who installed a patch to the specified version was prompted to install a lower version, which made the whole thing an annoyance.

With `rollForward` being available common sense has always been to pin down versions as much as possible.

I think there should be a strong recommendation to use global.json (just like every big dotnet codebase on github is doing already). Tooling has caught up (github actions reads them, azdo reads them) and i find no earthly reason why these files aren't automatically generated by dotnet new in clean workspaces - it is generally considered bad practice to leave implied dependencies dangling like this in CICD/DevOps circles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-json.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. #29060 mentions CI and eliminates the text saying that global.json is only for advanced scenarios.

**Comment by MeikTranel** [comment]
Much appreciated 👏
