### ISSUE TITLE
Runtime Identifier for Windows 11 is not updated

### ISSUE THREAD

**Issue by shreesharao** [dotnet/docs#28885]
Runtime Identifier for Windows 11 is not updated in the document. It is not clear how to publish self-contained applications targeting windows 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Runtime Identifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/main/docs/core/rid-catalog.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by shreesharao** [comment]
@tdykstra , I came to know that there's no specific RID for windows 11 when I asked SO folks - https://stackoverflow.com/questions/71763095/what-is-net-runtime-identifier-for-windows-11. But this is very confusing for those people like me who doesn't know windows 11 is no different than windows 10. Can we mention this in the RID catalog document - https://docs.microsoft.com/en-us/dotnet/core/rid-catalog.

**Comment by tdykstra** [comment]
Yes, I'll add a note to that effect, thanks for the suggestion.
