### ISSUE TITLE
Naming conventions were not followed

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#28896]
C# Coding convention( https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) suggests the following:
Use camel casing ("camelCasing") when naming private or internal fields, and prefix them with _. 

But this page does not follow this suggestion. Am I correct? 
And what about arrays? I do not see this for arrays too(https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
In the docs you linked these are local variables, not fields. So the naming is following the guidance.

To clarify:
```c#
public class Foo
{
    private string _thisIsAFieldOfTypeString;

    public string Bar()
    {
        string localVariableOfTypeString = _thisIsAFieldOfTypeString;
        return localVariableOfTypeString;
    }
}
```

**Comment by Vaskaran** [comment]
> In the docs you linked these are local variables, not fields. So the naming is following the guidance.
> 
> To clarify:
> 
> ```cs
> public class Foo
> {
>     private string _thisIsAFieldOfTypeString;
> 
>     public string Bar()
>     {
>         string localVariableOfTypeString = _thisIsAFieldOfTypeString;
>         return localVariableOfTypeString;
>     }
> }
> ```

Yes.You are correct.I missed this.

**Comment by gfoidl** [comment]
@Vaskaran so this issue is resolved?
Can you close it then please?
