### ISSUE TITLE
[Breaking change]: CentOS > Rocky 

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/docs#28915]
### Description

Last year, CentOS broke community trust and after getting acquired by IBM, changed its release model from being source compatible to RHEL, in order to create a free alternative to its subscription model, to something entirely different.

https://www.techradar.com/news/red-hat-makes-drastic-changes-to-centos-leaves-users-fuming

Rocky Linux has been created as an alternative, and version 8 is still well supported there. 

I strongly advice changing the support to Rocky, since this is showing sentiment and partnership with the community. 

Long overdue, to be honest.  

### Version

.NET 6

### Previous behavior

.NET was supported on the free version of RHEL

### New behavior

.NET is not supported anymore on the free version of RHEL

### Type of breaking change

- [x] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [x] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Rocky has an increasingly [high adoption rate and is official partner of Azure. 
](https://forums.rockylinux.org/t/community-update-june-2021/3260)

### Recommended action

Change the CentOS page to be supportive for Rocky Linux. 

### Feature area

SDK

### Affected APIs

All

**Comment by adegeo** [comment]
@gewarren @ShalokShalom This issue should be raised in the .NET repo itself, not the documentation repo. We just document what is supported/tested by the .NET team. If other distros needed to be officially supported, it needs to go through that team.

Please open a discussion at https://github.com/dotnet/sdk

I'm going to close this issue as there isn't anything to do here at the  moment.

_note, I removed the incompatible tags as these (and this issue template) are used for indicating API incompatibility changes that need to be documented_
