### ISSUE TITLE
Ref and Out links in "Know the Difference Between Passing a Struct and Passing a Class Reference to a Method"?

### ISSUE THREAD

**Issue by AndreasHassing** [dotnet/docs#2891]
# Ref and Out links in "Know the Difference Between Passing a Struct and Passing a Class Reference to a Method"

I think it would be nice to mention the `ref` and `out` keywords, as the article seems to implicitly claim that mutating a value type (such as structs) via function calls is impossible.

Not sure if it's just me.

Link to article and markdown:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method ([github](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method.md))

**Comment by BillWagner** [comment]
@AndreasHassing Thanks for pointing this out. I'm putting this in the backlog as I'm working on a project to do quite a bit of updates to the C# Guide. I'll make sure this gets addressed as part of that work.
