### ISSUE TITLE
[Suggestion] Add descriptions about the ordering of generic constraints

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/docs#28914]
Today C# has many generic constraints, but sometimes I'll miss the usages on the combinations of those constraints. I just know `new()` will be placed at the last position in the whole generic constraint list, such as `where T : [interfaces], new()`.

However, if the constraints are too many in the whole constraint list, I'll lost how the ordering of those constraints are, and which constraints cannot be combined to be used, especially `notnull`, `unmanaged`, `Enum`, `Delegate` and other single-word or keyword-styled constraints. Too complex... :(

I hope that the page will contain the specialized description about the ordering of all constraints, which can really help our C# users use the feature better and more convenient.

By the way, I know [this section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#1425-type-parameter-constraints) can help me use them, but the draft specification is currently based on C# 6 and its lower versions. Today C# contains more constraints such as:

* `unmanaged` (C# 7, allow using pointers on type argument)
* `Enum` (C# 7, allow type argument derived from `System.Enum`)
* `Delegate` (C# 7, allow type argument derived from `System.Delegate`)
* `notnull` (C# 8, disallow the type containing `null` value)
* `class?` (C# 8, limited the type argument being a nullable reference types)
* `BaseType?` (C# 8, allow the inheritance on nullable class types)
* `Interface?` (C# 8, allow the implementation on nullable interface types)
* `default` (C# 9, keep the default overridden on methods which contains `T?`-typed arguments)

So I hope somewhere in this page can describe about the ordering of all generic constraints. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on type parameters - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 229459](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229459)

**Comment by BillWagner** [comment]
That's a great suggestion @SunnieShine 

I've added this to our list to update this release.
