### ISSUE TITLE
UseAppHost changed in .NET 6.0

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/docs#28923]
On this page:

https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues

It says very clearly that the application host is disabled by default.  However, according to this page, that has changed:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/apphost-generated-for-macos

For consistency, the first page should be updated (describing both current and prior behavior) and then linked to the second one.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab295263-1911-add9-0388-4d43a2ffcf3f
* Version Independent ID: cff6c791-597a-ab01-6c91-3c8d24cccdaf
* Content: [Working with macOS Catalina Notarization - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues#apphost-is-disabled-by-default)
* Content Source: [docs/core/install/macos-notarization-issues.md](https://github.com/dotnet/docs/blob/main/docs/core/install/macos-notarization-issues.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I don't think this issue applies anymore since the article was updated for .NET 7
