### ISSUE TITLE
meaningless

### ISSUE THREAD

**Issue by stevecarnell** [dotnet/docs#28932]
[Enter feedback here]
meaningless gobbledegook

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bf6d84-78dc-0dd4-46d1-355ffdc9b9eb
* Version Independent ID: 9c02494e-91b8-2309-e010-a2a46ac2a4c0
* Content: [Compiler Error CS0501](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0501?f1url=%3FappId%3Droslyn%26k%3Dk(CS0501))
* Content Source: [docs/csharp/misc/cs0501.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0501.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @stevecarnell 

We should do a better job of linking to the definitions of the terms used in this article. I've added this issue to the backlog to address.

**Comment by stevecarnell** [comment]
Many thanks
