### ISSUE TITLE
link to offline installer goes to web-based installer

### ISSUE THREAD

**Issue by amaryeh** [dotnet/docs#28930]
and is therefore useless for cases where host is not allowed internet access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96aef419-de1f-a341-3f19-4ed99eb36412
* Version Independent ID: 40ddc3ce-a004-1a4c-37e1-1c45eaa8f35a
* Content: [Install .NET Framework 3.5 on Windows 11, 10, 8.1, 8 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows)
* Content Source: [docs/framework/install/dotnet-35-windows.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/dotnet-35-windows.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
Hmm it doesn't look like an offline installer is available at https://dotnet.microsoft.com/en-us/download/dotnet-framework/net35-sp1. @mairaw Is that intentional? If so, we should remove the https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows#download-the-offline-installer section from the article.

**Comment by mairaw** [comment]
Let me start a thread on this. We have similar issues on the website repo (e.g. https://github.com/dotnet/website/issues/4105)

I'd like confirmation that the link @adegeo found is correct and we're supposed to use it.

**Comment by adegeo** [comment]
I'm not sure where we should go with this. The downloaded file is 200+ mb and not 10mb or whatever the web installer is. It looks like the full installer to me. Did @amaryeh try the installer? Or was the file name throwing them off? (it had web in it at the time, I don't think it does anymore)

**Comment by gewarren** [comment]
It looks like it still has "web" in the name:

https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net35-sp1-web-installer

Also what happened to the dotnet/website repo @mairaw?
