### ISSUE TITLE
Conflicting advice about using finalizers to clear up unmanaged resources

### ISSUE THREAD

**Issue by wgibbons1** [dotnet/docs#28946]
My understanding is that if we use unmanaged resources, we must manually free them up or they will persist after application termination. If this is correct, then the advice to use finalizers to do this (first two quotes below) is wrong as we can't be sure they will run in Core (third quote below).

_"Even with this explicit control over resources, the **finalizer becomes a safeguard to clean up resources** if the call to the Dispose method fails."_
and
 _"However, **when your application encapsulates unmanaged resources**, such as windows, files, and network connections, **you should use finalizers to free those resources.** "_
conflict with
_"Because you can't call Finalize directly, and you can't guarantee the garbage collector calls all finalizers before exit, you must use Dispose or DisposeAsync to ensure resources are freed."_

The document feels slightly ambiguous regarding exactly what we should do to ensure unmanaged resources are freed up correctly. Seems as if there should be a standard pattern for Framework and another for Core.

The first quote doesn't seem right to me as I wouldn't call it a safeguard if it is not certain it will happen (in Core).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96eaef8-dcc9-4659-3f4e-be5a1c4c6b50
* Version Independent ID: d3da7981-542d-e906-5988-b80e403fa651
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/finalizers#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/finalizers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/finalizers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @wgibbons1 

Thanks for reaching out.  I'd like to clarify some points before we make any changes in this article.

> My understanding is that if we use unmanaged resources, we must manually free them up or they will persist after application termination. If this is correct, then the advice to use finalizers to do this (first two quotes below) is wrong as we can't be sure they will run in Core (third quote below).

That isn't correct. On the operating systems supported by .NET Core (and .NET 5 and newer), the operating system will free any unmanaged resources when the application exits. The purpose of a finalizer is to free any unmanaged resources *before* application exit, and only if those resources weren't freed by a `Dispose` method.

> The document feels slightly ambiguous regarding exactly what we should do to ensure unmanaged resources are freed up correctly. Seems as if there should be a standard pattern for Framework and another for Core.

The standard pattern should be the same. In any application, you should free any unmanaged resources by using a finalizer (or using `SafeHandle<T>` which creates the finalizer for you). That ensures your application is well behaved. The runtime can't guarantee finalizers are called when the application exits. (The OS may force quit any application, without giving it a chance to clean up.) The OS then takes over all cleanup.

In light of that, what changes would you recommend to improve the clarity here?

**Comment by wgibbons1** [comment]
Hi Bill,

Thanks for the reply.
In that case my message is irrelevant. I thought some unmanaged resources persisted after app termination but I was wrong.

The only thing that now comes to mind is this sentence:

> _Because you can't call Finalize directly, and you can't guarantee the garbage collector calls all finalizers before exit, you must use Dispose or DisposeAsync to ensure resources are freed._

This sentence says to me that if you don't call `Dispose()` then it will not be certain that resources will be freed. As an extension, readers who are not aware that the OS clears all resources on app termination will then be guessing that if a call to `Dispose()` is forgotten then the resources will remain allocated even after app termination.

To tackle both these issues I think it could be explained that no matter what happens in the app, the resources will be cleared on app termination by the OS, and that `Dispose()` only needs to be used to ensure resources are freed immediately. For example (just a suggestion to save your time but feel free to rewrite):

I also have a question about the preceding text in the paragraph:

> If you need to perform cleanup reliably when an application exits, register a handler for the [System.AppDomain.ProcessExit] event. That handler would ensure `IDisposable.Dispose()` or `IAsyncDisposable.DisposeAsync()` has been called for all objects that require cleanup before application exit.

If the OS cleans up automatically then why would we need to do this on app exit? Presumably you mean stuff the OS doesn't do which might be like resetting a config file (can't think of a better example)? If so then I think this needs to be mentioned too.

William

**Comment by BillWagner** [comment]
Thanks @wgibbons1 

I think most of the answers are in [this section](https://docs.microsoft.com/dotnet/standard/garbage-collection/unmanaged) of the docs. Let me know if those do answer these questions. If so, we'll make that link more prominent in this article.

Thanks.
