### ISSUE TITLE
Incorrect/confusing format string in new sample for interpolations with newlines?

### ISSUE THREAD

**Issue by julealgon** [dotnet/docs#28956]
Was reading up on the latest additions to allowing newlines in the C# components of interpolated strings, and noticed a very small issue that might cause some confusion (it confused me for a few seconds).

In the sample below, the message structure is as follows: 
- `The usage policy for {safetyScope} is >{text}>`

```csharp
string message = $"The usage policy for {safetyScore} is >{
    safetyScore switch
    {
        > 90 => "Unlimited usage",
        > 80 => "General usage, with daily safety check",
        > 70 => "Issues must be addressed within 1 week",
        > 50 => "Issues must be addressed within 1 day",
        _ => "Issues must be addressed before continued use",
    }
    }>";
```

However, I believe the intention was to have the second, dynamic text be inside `<...>` like this:
- `"The usage policy for {safetyScope} is <{text}>"`

For example:
- `"The usage policy for 95 is <Unlimited usage>"`

This confused me for a bit because the checks all rely on `<` comparisons to produce the values, so I wondered for a second if the text was related to that or not (it doesn't seem to be the case). It also threw me off because I thought for a second that "perhaps the `>` character before and after `{` here is being used to indicate we are using multiple lines inside the statement, as some sort of escape sequence?". It gives the impression that `>{` is a special combination for this particular scenario. Again, I don't think that's the case.

I'd suggest fixing that detail, but also considering not using `<` and `>` characters in the text to avoid unnecessary confusion with the actual comparisons being done in the expression.

Perhaps a cleaner, less confusing form on this example could be:
- `"The usage policy for {safetyScope} is: {text}"`

In short, I think the text used in the same is a bit too convoluted for it's intended purpose: showing how multiline statements work inside interpolations. A simpler text format would help with readability and understanding of the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good suggestion @julealgon 

I've opened a PR to address it.
