### ISSUE TITLE
I get an error when I paste the code into Class1.cs

### ISSUE THREAD

**Issue by apatinoo** [dotnet/docs#28959]
![image](https://user-images.githubusercontent.com/101580871/162476853-eb9d96b1-7549-4236-b5a0-dcc6e45cf48c.png)

Build started...
1>------ Build started: Project: StringLibrary, Configuration: Debug Any CPU ------
1>C:\Users\apatino\source\repos\ClassLibraryProjects\StringLibrary\Class1.cs(1,27,1,28): error CS1514: { expected
1>C:\Users\apatino\source\repos\ClassLibraryProjects\StringLibrary\Class1.cs(13,2,13,2): error CS1513: } expected
1>Done building project "StringLibrary.csproj" -- FAILED.
here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c
* Version Independent ID: 87d3afdd-d7d5-35d7-0718-63dadc4eab1d
* Content: [Create a .NET class library using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Make sure you're using the current version of Visual Studio 2022 and that when you created the project you selected .NET 6 as the target framework.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
