### ISSUE TITLE
anonymous functions? 

### ISSUE THREAD

**Issue by tcrabtree** [dotnet/docs#28969]
The title mentions anonymous functions, but all examples shown appear to use named methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495dca2a-dcd9-892f-21f0-e970589b543d
* Version Independent ID: 159fb3e3-66b4-6cdc-f921-4406447b98ca
* Content: [Delegates with Named vs. Anonymous Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods)
* Content Source: [docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/delegates-with-named-vs-anonymous-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 350759](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350759)

**Comment by BillWagner** [comment]
Thanks for reporting this @tcrabtree 

I've added it to our backlog for us to address.
