### ISSUE TITLE
Error "Only auto-implemented properties can have initializers" with record types

### ISSUE THREAD

**Issue by andriysavin** [dotnet/docs#28962]
The article says:

> If the generated auto-implemented property definition isn't what you want, you can define your own property of the same name. For example, you may want to change accessibility or mutability, **or provide an implementation for either the get or set accessor**. If you declare the property in your source, **you must initialize it from the positional parameter of the record**. 

However, when I try to implement a record with a property with a custom get/set I get compiler error: "CS8050	Only auto-implemented properties can have initializers". Here is the sample code:

```csharp
public readonly record struct PersonAge(int Value)
{
    private readonly int value;

    public int Value
    {
        get => value;
        init { this.value = @value; }
    } = Value;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(record_CSharpKeyword);k(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @andriysavin 

If you supply the backing field, your initialization needs to set the backing field, not the property:

```csharp
public readonly record struct PersonAge(int Value)
{
    private readonly int value = @Value;

    public int Value
    {
        get => value;
        init { this.value = @value; }
    }
}
```

I opened a PR to clarify that point.

**Comment by andriysavin** [comment]
@BillWagner Ah! Thanks!
