### ISSUE TITLE
Ensure same SDK version for dotnet build and pipeline

### ISSUE THREAD

**Issue by perclausen** [dotnet/docs#28968]
From top of the article:
_In general, you want to use the latest version of the SDK tools, so no global.json file is needed. In some advanced scenarios, you might want to control the version of the SDK tools, and this article explains how to do that._

Both ADO and GH requires pulling in e.g. .NET 6 SDK in the pipeline (YAML) which can be done either by specifying a version in the YAML or using `global.json`.

I'm currently not using `global.json` but considering it to have a one-stop-shop for controlling .NET SDK used.
Currently I have to make sure my pipeline YAML files (there is more than one) are in sync with my `Directory.build.props` file which is bound to go wrong at some point.

Believe an advice on a best practice would fit nicely in this article?

`Directory.build.props`
``` xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>LatestPatch</RollForward>
</PropertyGroup>
```

ADO pipeline
``` yaml
- task: UseDotNet@2
  displayName: 'Use .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: false
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-json.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion.  This article isn't the best place for specific guidance for ADO or GH, but #29060 eliminates the text saying that global.json is only for advanced scenarios.
