### ISSUE TITLE
Snap based install of .NET can lead to segmentation faults.

### ISSUE THREAD

**Issue by devhawk** [dotnet/docs#28983]
Source: https://github.com/dotnet/runtime/issues/51322#issuecomment-890306629 and https://github.com/dotnet/runtime/issues/3775#issuecomment-534263315 and https://github.com/dotnet/runtime/issues/3464

Also, according to [this comment](https://github.com/dotnet/runtime/issues/51322#issuecomment-894449076) Snap issues have been closed "to reflect current priorities."

Shouldn't this be reflected in the documentation? Why do the docs provide instructions on installation via snap when it isn't a "current priority" and it doesn't work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40005eb-f935-d50d-10ce-c1e0a47ea70e
* Version Independent ID: 91f4a9b7-09d0-f18e-af4a-c0af28a8948f
* Content: [Install .NET on Linux with Snap - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)
* Content Source: [docs/core/install/linux-snap.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-snap.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 45520](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45520)

**Comment by adegeo** [comment]
Thank you for letting me know. I'll prioritize getting a note added to the article.

**Comment by adegeo** [comment]
Note: Opened an internal discussion on this.

**Comment by adegeo** [comment]
At this point we're still waiting. I'm going to close this for now and when new info about snap becomes available, I'll reopen this.
