### ISSUE TITLE
Pls make it in easy way to understand the words use in this article to explain is make it comlex to understand 

### ISSUE THREAD

**Issue by G1urav** [dotnet/docs#28985]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83cd166c-9e60-e6b5-1985-5dd04d3261f2
* Version Independent ID: 45bf2f1f-a453-0e2e-c115-050c9d621cb3
* Content: [Implicitly typed local variables - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @G1urav 

Can you give us more details on which terms we should define in this article? I'd like to make sure we address this. Adding those details will help.

**Comment by timdams** [comment]
Perhaps the article could start with a short mention+link to the [c# type system article] (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/).   I can imagine junior developers more rapidly coming in contact with the keyword var,  before actually learning about how c# is a typed language.

Ps
In fact, as a non-native speaker, I can confirm that 'infer' is a very infrequently used word (compared to deduce or assume) , but quiet important to understand the mentioned article
