### ISSUE TITLE
[feedback] Newbies cannot easily understand how to upgrade a given NuGet package to the latest version

### ISSUE THREAD

**Issue by GwynethLlewelyn** [dotnet/docs#28997]
Hello there,

For newbies in the 'dotnet universe', such as myself, it's never obvious how to get `dotnet` to _upgrade_ NuGet packages. The confusion stems from the fact that `dotnet add package`, unlike what it _seems_ to imply — adding a _new_ package — actually _adds a package reference_ to the underlying configuration files. A side-effect of _changing_ a specific package's version during an upgrade (even if it's just to the 'latest' version) is, of course, that `dotnet` will pull the required package from the NuGet repository and correctly set up all information on the many resource/configuration files. _But this is not obvious for newbies_, coming from other development environments where `add` means adding a _new_ package, while `update`/`upgrade` will pull the latest version of an _existing_ package. (To make matters even more confusing to newbies, `dotnet nuget update` means something completely different: it updates _sources_, not _packages_, but at least those instructions are clear.)

While I'm not advocating for either solution — what feels 'best' or 'natural' is mostly a matter of personal taste — I think that at the very least a single sentence should be included, both on your page's documentation for the `dotnet` CLI, as well as on the help functionality for the binary itself; something simple like:

> To upgrade NuGet packages, simply type `dotnet add package` and omit the version number; `dotnet` will reconfigure your project to the latest version and pull the required package from the repository.

... or words to the effect.

Thank you in advance for considering this small change!

— Gwyn (a very newbie Linux/macOS developer)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion! I'm adding text that mentions the update function of this command in #29057

**Comment by GwynethLlewelyn** [comment]
Thanks so much! :)
