### ISSUE TITLE
associativity of lambda operator not mentioned

### ISSUE THREAD

**Issue by markshyn** [dotnet/docs#28998]
In the section of the C# language reference that discusses operator associativity, there is no explicit mention of the lambda operator.  I had to search long and hard before I finally found a Microsoft web page that explicitly stated that the lambda operator is right associative.

Mark S.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @markshyn We'll get this fixed.  The description you wrote includes the edit needed, so I'll add the "up for grabs" label for anyone that wants to contribute a fix before we make the c hange.
