### ISSUE TITLE
Request: Explanation for this rule please

### ISSUE THREAD

**Issue by davelobban** [dotnet/docs#28990]
Hi,
What is the rationale for this rule?

Code triggering this rule is 

```
if (!found)
        {
            _logger.LogWarning($"Clients count: {foo.Count}");
            _logger.LogWarning($"Clients : {String.Join(',', _clientProvider.GetClientInfo())}");
        }
```

I can't see why this is bad practice. Could someone explain what is bad practice here?

"Do not suppress a warning from this rule." suggests that this is a really bad approach but I would like to know why.

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@davelobban It's explained in this issue: https://github.com/dotnet/roslyn-analyzers/issues/5626#issuecomment-1033240500. We do have an [issue open](#28400) to improve the documentation too.

**Comment by skrabbe001** [comment]
Why do you close issued that aren't fixed, I just don't understand it.

**Comment by Youssef1313** [comment]
@skrabbe001 This is tracked by https://github.com/dotnet/docs/issues/28400, which is worked on in https://github.com/dotnet/docs/pull/29787.
