### ISSUE TITLE
Incorrectly encoded ellipsis in list of derived types

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2900]
[The list of derived types for `IEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=netframework-4.7#derived) looks like this:

![](https://user-images.githubusercontent.com/287848/29285258-344095a8-812e-11e7-8a57-219058271082.png)

Notice the "More\&#8230;" link, which is wrong (`&#8230;` is the HTML encoding for U+2026 HORIZONTAL ELLIPSIS). It seems the character was incorrectly encoded: the HTML is `More&amp;#8230;`, when it should be `More&#8230;`.

**Comment by mairaw** [comment]
Thanks @svick. I've noticed that recently and filed an internal bug already (#1055498)

**Comment by mairaw** [comment]
They have fixed this a few months ago and I missed it. Thanks for reporting @svick.
