### ISSUE TITLE
global.json documentation

### ISSUE THREAD

**Issue by nguerrera** [dotnet/docs#2902]
_From @jaredpar on July 17, 2017 21:19_

Where can I find documentation on global.json? This is the only public documentation I could find:

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

Unfortunately it doesn't answer the questions I have about the `sdk.versions` property. In particular:

- What are the matching rules? Say I put 1.0 but 2.0 is available. Will 2.0 be chosen or will an error occur?
- Can I put in version ranges?
- Is there globbing support? 

Also of interest is the version of the SDK that comes installed with Visual Studio. Does that version change on every update, preview, etc ... of VS? Worried about how updates to VS will interact with restrictions that I add in this file. 

_Copied from original issue: dotnet/sdk#1421_

edit by @mairaw: added info Docs below 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json reference](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by nguerrera** [comment]
_From @jaredpar on July 18, 2017 18:35_

CC @rainersigwald, @nguerrera, @dsplaisted

**Comment by nguerrera** [comment]
_From @livarcocc on July 18, 2017 23:40_

@mairaw can we work on documentation for this? We changed the policy in 2.0, it would be good to do an all up write up on this file.

**Comment by nguerrera** [comment]
_From @jaredpar on July 19, 2017 15:7_

@livarcocc can we get the details posted here while waiting for doc? Need to understand how this works before we can adopt in our repos.

**Comment by nguerrera** [comment]
_From @mairaw on August 12, 2017 7:21_

Sorry, I missed this mention earlier. Yes, we can improve the docs. Doc issues can be filed at https://github.com/dotnet/docs/issues. Can I have more info on what needs to be done @livarcocc @nguerrera? I don't know what the change was or the answer to @jaredpar's questions, unfortunately. Should we move this to our repo?

**Comment by nguerrera** [comment]
> What are the matching rules? Say I put 1.0 but 2.0 is available. Will 2.0 be chosen or will an error occur?

Prior to `dotnet 2.0`, the matching rule was that if no exact match was found, then latest would be used. https://github.com/dotnet/core-setup/issues/2334

In 2.0, the rules are described in this PR's description: https://github.com/dotnet/core-setup/pull/2621. However, in the desktop `msbuild`/VS case, the error cases listed there are actually currently fallbacks to the 1.1 SDK in the MSBuild folder due to the problem described in https://github.com/dotnet/sdk/issues/1470#issuecomment-322310484

> Can I put in version ranges?

No

> Is there globbing support?

No

> Also of interest is the version of the SDK that comes installed with Visual Studio. Does that version change on every update, preview, etc ... of VS? Worried about how updates to VS will interact with restrictions that I add in this file.

Yes, it does change.

**Comment by nguerrera** [comment]
Tagging @johnbeisner.

**Comment by mairaw** [comment]
I'm working on this right now. One behavior I've observed is that if I specify a patch version that is greater than the latest installed version, latest is used.

e.g. if I specify 2.1.4 and the latest version I have is 2.1.300-preview1-008174, latest is used (something like roll backward along patch). By design? 

/cc @KathleenDollard

**Comment by dsplaisted** [comment]
@mairaw That sounds like this issue: https://github.com/dotnet/core-setup/issues/3805

**Comment by mairaw** [comment]
That's correct @dsplaisted!

**Comment by mairaw** [comment]
I've read the info @nguerrera about the VS/MSBuild case and it's not super clear to me what happens when with the multiple possible combinations (VS versions earlier than 15.3 and later, SDK 1.1, SDK 2.0, etc.)

Can someone please summarize that please?
