### ISSUE TITLE
Visual Studio 2022 - errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/docs#29062]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022---errors/10012368)._

---
[severity:It's more difficult to complete my work]
Ther seems very little point in showing links to error details within Visual Studio if the link takes you to a 'Not Found' page or a 'Sorry, we don't have specifics on this C# error' page - eg CS1983.  This is just one example there have been several in the last few days.  This makes life very difficult when you are trying to get to grips with a new language and new concepts.  This particular error cropped up during the development of an Web API,

---
#### Feedback Bot on 4/13/2022, 09:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error)
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by vatsalyaagrawal** [comment]
@BillWagner FYI

**Comment by BillWagner** [comment]
closing and opening to run the label updates.

**Comment by BillWagner** [comment]
Fixed in #31182
