### ISSUE TITLE
Add list of .NET 7 TFMs

### ISSUE THREAD

**Issue by Doug-Murphy** [dotnet/docs#29069]
From the .NET 7 Preview 3 dev blog, the .NET 7 TFMs are now set. They should be added to the full list of TFMs.

https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-3/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/main/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
It seems the list of TFMs got smaller for Preview 4, so perhaps it's best not to update the article yet.

https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-4/#targeting-net-7

**Comment by richlander** [comment]
@terrajobst
