### ISSUE TITLE
Is it a recommended way to validate argument with ` _ = arg ?? throw new ArgumentNullException`?

### ISSUE THREAD

**Issue by yutao-huang** [dotnet/docs#29074]
Under the [A standalone discard](https://docs.microsoft.com/en-US/dotnet/csharp/fundamentals/functional/discards#a-standalone-discard) section, there is a piece of sample code using `_` and null coalescing operator to throw an `ArgumentNullException` when the argument is `null`:

```csharp
public static void Method(string arg)
{
    _ = arg ?? throw new ArgumentNullException(paramName: nameof(arg), message: "arg can't be null");

    // Do work with arg.
}
```

I am wondering if this is the recommended way to validate an argument. Some of my teammates have started using this pattern in our codebase. It's more concise for sure, but I think it hurts the readability. I personally feel this really doesn't read as naturally as:

```csharp
if (arg == null)
{
    throw new ArgumentNullException(paramName: nameof(arg), message: "arg can't be null");
}
```

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ace3d2c-a7f7-c667-5f50-b8d8f1dfc87a
* Version Independent ID: 6edd2f85-a04b-e9ad-2fc9-fc23dbfc5bba
* Content: [Discards - unassigned discardable variables](https://docs.microsoft.com/en-US/dotnet/csharp/fundamentals/functional/discards)
* Content Source: [docs/csharp/fundamentals/functional/discards.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I doubt you're going to get any kind of "official" answer about this, since it's about a subjective element of code style.

That being said, there are other new and coming options for parameter null validation.

In .Net 6, [you can use this](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-6.0#system-argumentnullexception-throwifnull(system-object-system-string)):

```c#
public static void Method(string arg)
{
    ArgumentNullException.ThrowIfNull(arg); // paramName is automatically inferred

    // Do work with arg.
}
```

And in .Net 7, [you'll be able to make the code even shorter](https://github.com/dotnet/csharplang/blob/main/proposals/param-nullchecking.md):

```c#
public static void Method(string arg!!)
{
    // Do work with arg.
}
```

**Comment by yutao-huang** [comment]
@svick - thanks for your response! I think that makes sense.

It's great to know those new options. I really like the .NET 6 one `ArgumentNullException.ThrowIfNull(arg)`. It's concise enough but at the same time also shows the intention very clearly.
