### ISSUE TITLE
"StringBuilder Append Evaluation Order" example violates CA1305

### ISSUE THREAD

**Issue by plioi** [dotnet/docs#29088]
"[Breaking change: New StringBuilder.Append overloads - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order) accurately describes a behavior change when interpolated strings in combination with `StringBuilder.Append`. It gives a simple example case and accurately shows what the compiler does with that example in the old vs new .NET version. However, it portrays this simple example as one that would work, and it does not. It violates CA1305 in either all or at least highly-common scenarios, making the combination of string interpolation and `Append` unusable in practice... odd since that combination is precisely the use case for the intentional behavior change. This leaves the reader confused.

The docs here portray the potential problem as a rare edge case. It portrays the workaround as "...not recommended, however, unless it's actually requried for compatibility" but appears to be required all the time.

Example code based on the document content, which violates CA1305 until you *do* apply the string cast workaround:

```cs
var a = "A";
var b = "B";
var builder = new StringBuilder();
builder.AppendLine($"{a}{b}");
```

Picture the user's experience as they encounter and try to troubleshoot this issue. This is the page people will arrive at when their seemingly innocuous code startlingly breaks, and the page essentially gaslights them, telling them that their code probably isn't breaking really and offers **no useful context for understanding why the "not recommended" workaround seems to be their only recourse in all circumstances**. It leaves the developer certain that they are misunderstanding the true context and are riskily applying a workaround blindly just to hide the error message.

Accurately or not, it leaves us wondering if this is a case of the compiler optimization designer losing sight of the goal and sticking us with a bug portrayed as a feature. Full context in this page could alleviate that concern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a86f9ccd-b7a1-aead-c355-34b7bc0f6173
* Version Independent ID: f835c171-990a-9852-c3cd-888f9b82cb91
* Content: [Breaking change: New StringBuilder.Append overloads - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order)
* Content Source: [docs/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@plioi There are other ways to avoid CA1305 without resorting to the string cast (which I believe is not recommended because it negates the performance improvements brought by the breaking change). For example, you can simply pass in the Culture you want to use:

```
var a = "A";
var b = "B";
var builder = new StringBuilder();
builder.AppendLine(CultureInfo.CurrentCulture, $"{a}{b}");
```

Also, CA1305 is disabled by default, so unless you specifically enable it, you're not going to see it as a suggestion/warning/error.

**Comment by plioi** [comment]
From the misleading document:

> Recommended action
... restore the previous behavior by adding a cast to (string) prior to the interpolated string.
