### ISSUE TITLE
.NET 4.0 seems to build fine in Visual Studio 2022

### ISSUE THREAD

**Issue by radalan** [dotnet/docs#29095]
There is an Important note on this page about Visual Studio 2022 no longer supporting .NET 4.0.  I have an application that targets that framework and was able to build it... is this note actually incorrect or is Visual Studio 2022 quietly building something that won't run on .NET 4.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
"Supported" vs "Working" are two different things :) It may work, but it isn't supported. The note is pointing out that VS2022 doesn't include the components for install. Perhaps some how you have them some other way or something is being upgraded behind the scenes. I'm not sure. If you look at the installer dialog for Visual studio, you can see 4.0 isn't included:


.NET 4.0 is no longer supported by Microsoft. So it's not supported by the latest releases of Visual Studio. If it happens to work, it happens to work. But if it doesn't work some other day, there is nothing we can do from our side to help you except tell you to install Visual Studio 2019.
