### ISSUE TITLE
Missing dot in F# indexed property documentation

### ISSUE THREAD

**Issue by binarycow** [dotnet/docs#29094]
Documentation says:

For example, if `o` is an object of the type that defines this property, the syntax `o[index]` is used to access the property. The syntax `o[index]` (with an extra `.`) may also be used and is required for language versions prior to F# 6.

The second reference of `o[index]` should be `o.[index]` (it's missing a dot.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47d926c-72f6-0a8e-140d-7a31cd8e17d3
* Version Independent ID: 5d587fbe-7771-c826-7a72-75f69d61bc55
* Content: [Indexed Properties - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties)
* Content Source: [docs/fsharp/language-reference/members/indexed-properties.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/members/indexed-properties.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by kroppt** [comment]
In addition, the statement in question is not necessary. Lower in the Remarks section is stated:

> Prior to F# 6, the syntax `expr.[idx]` was used for indexing. You can activate an optional informational warning (`/warnon:3566` or property `<WarnOn>3566</WarnOn>`) to report uses of the `expr.[idx]` notation.

Thus, removing the statement is also an option.

**Comment by BillWagner** [comment]
Thanks for noting this. I opened #29277 to address this issue.
