### ISSUE TITLE
.NET Standard implementation support matrix - define "1.0 tooling" and "2.0 tooling"

### ISSUE THREAD

**Issue by tmenier** [dotnet/docs#2909]
On https://docs.microsoft.com/en-us/dotnet/standard/net-standard under ".NET Implementation Support", 2 of the platforms read ".NET Framework (with 1.0 tooling)" and ".NET Framework (with 2.0 tooling)". Nowhere in the doc is there any indication of what is meant by "1.0 tooling" and "2.0 tooling". It seems deserving of a link or a footnote or _something_ defining what exactly that means.

**Comment by mairaw** [comment]
Hi @tmenier, I've created a PR to improve the definition. Let us know what you think!

**Comment by tmenier** [comment]
That looks perfect, thanks! (I would have done a PR myself but I honestly didn't know what it meant. Now I do, so I guess you could say it passes the ultimate litmus test. 😃)

**Comment by mairaw** [comment]
Great! I'm glad it helps. Appreciate the feedback @tmenier!
