### ISSUE TITLE
When did this come into effect?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#29118]
I'm pretty sure that I have used the following before

``` csharp
var myString = "something"; //definitely not a constant or literal like this. 
if (myString.Equals("somethingelse", StringComparison.OrdinalIgnoreCase)){
 ...
```
And did not have CS0176 get triggered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d605c28f-e8ec-29e5-0743-d8134c31ddca
* Version Independent ID: 38ff17e8-853e-7b99-e683-d33546fb1ac6
* Content: [Compiler Error CS0176](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0176?f1url=%3FappId%3Droslyn%26k%3Dk(CS0176))
* Content Source: [docs/csharp/misc/cs0176.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0176.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @StingyJack 

Can you add an example that does produce this error?  The code you show above compiles cleanly. (It calls the instance `Equals` method.)

This error has been part of the compiler since 1.0. An example would help me determine if it's now triggered in new locations.

**Comment by StingyJack** [comment]
@BillWagner  - I cant share the repo as its a corp/org private one, but I can share a screenshot and a copy of the code depicted. 
![image](https://user-images.githubusercontent.com/15381181/164273439-ac1954dc-63aa-4f50-87d1-31860609943b.png)



``` csharp
public class ReplicationConfig
{
	public ReplicationConfig(string sourceDashboardName, TargetDashboard[] targetDashboards)
	{
		SourceDashboardName = sourceDashboardName ?? throw new ArgumentNullException(nameof(sourceDashboardName));
		TargetDashboards = targetDashboards ?? throw new ArgumentNullException(nameof(targetDashboards));
	}

	public string SourceDashboardName { get; private set; }
	public TargetDashboard[] TargetDashboards { get; private set; }
}


private static JToken GetDashboard(GraphQLHttpClient graphQLClient, ReplicationConfig config)
{
	_ = graphQLClient ?? throw new ArgumentNullException(nameof(graphQLClient));
	_ = config ?? throw new ArgumentNullException(nameof(config));
	_ = config.SourceDashboardName ?? throw new ArgumentException($"{nameof(config.SourceDashboardName)} cannot be null");
	
	var gql = GetQueryForDashboards("Redacted");
	var gqr = new GraphQLHttpRequest(gql);
	var results = graphQLClient.SendQueryAsync<JObject>(gqr).GetAwaiter().GetResult();
	JToken dashboard = null;
	var entities = results.Data.SelectToken("actor.entitySearch.results.entities", true)
				   ?? throw new InvalidOperationException($"Search results not returned correctly for dashboards");

	foreach (var result in entities)
	{
		var resultName = result.SelectToken("name", true);
		if (config.SourceDashboardName.Equals(resultName, StringComparison.OrdinalIgnoreCase))
		{
			dashboard = result;
			break;
		}
	}

	return dashboard;
}
```

Let me know if I am missing something from the documentation page, or if I should open up a bug somewhere.

**Comment by StingyJack** [comment]
Nevermind. I see the problem is with `resultName` not being a string type.  Thanks for being a rubber duck.
