### ISSUE TITLE
Unclear reference to placeholder in .NET local tool documentation

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/docs#29122]
Regarding the line:

> 2. Replace `<name>` with the name you used to create the project

It's not clear what the placeholder `<name>` is referring to. That text does not exist anywhere else on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9eeaac3-a5c0-5739-1a3e-8b47c8b916f3
* Version Independent ID: 4fe6c87c-9fb5-33fb-7835-2e0b511dc5b3
* Content: [Tutorial: Install and use .NET local tools - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use)
* Content Source: [docs/core/tools/local-tools-how-to-use.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/local-tools-how-to-use.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for pointing that out. That step is a remnant from an earlier version of the tutorial series. I'm removing it in #29313 .
