### ISSUE TITLE
Execution count logging should be fixed

### ISSUE THREAD

**Issue by umutcankarakas** [dotnet/docs#29124]
I tried to apply all the steps and run but the count in logging didn't increase, then I found out that changing {{Count:#,0}} to {Count:#,0} solves the problem. Not a big deal but could be confusing for some people.

```
private void DoWork(object? state)
    {
        int count = Interlocked.Increment(ref _executionCount);

        _logger.LogInformation(
            "{Service} is working, execution count: {Count:#,0}", //it was {{Count:#,0}} before
            nameof(TimerHostedService),
            count);
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b247969-9dc8-e710-ca64-745596cc3082
* Version Independent ID: 483cf588-2b7b-73cd-f9f9-a231a9c8dd7f
* Content: [Implement the IHostedService interface](https://docs.microsoft.com/en-us/dotnet/core/extensions/timer-service)
* Content Source: [docs/core/extensions/timer-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/timer-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @umutcankarakas 
Thank you so much for posting this issue. We really appreciate it. I will work on fixing this issue right away.
