### ISSUE TITLE
No start page

### ISSUE THREAD

**Issue by jk404-bit** [dotnet/docs#29134]
No matter what I do, I cannot get to the first page, where I could find the "Start a new project" tab. Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Make sure you're using Visual Studio 2022, and when you open the app, the New project button is the last button on the right side of the start page. If you dismiss the start page, you can create a project by selecting the File menu, then New, then Project.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
