### ISSUE TITLE
Error in Code example

### ISSUE THREAD

**Issue by foolnidiot** [dotnet/docs#29136]
In the code below:

Expression<Func<string, bool>> expr = (startsWith, endsWith) switch
{
    ("" or null, "" or null) => x => true,
    (_, "" or null) => x => x.StartsWith(startsWith),
    ("" or null, _) => x => x.EndsWith(endsWith),
    (_, _) => x => x.StartsWith(startsWith) || x.EndsWith(endsWith)
};

var qry = companyNamesSource.Where(expr); <- Missing .Compile()

Also in  various part of Constructing an [Expression<TDelegate>]
Expression Static Class Methods is missing the Expression class 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e7c92f-899d-506e-dced-ade9245fa231
* Version Independent ID: 0f232a4f-3c75-7736-7c70-c409d3cf5ab5
* Content: [Querying based on runtime state (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this @foolnidiot 

All the samples in this article require the following `using` statements:

```csharp
using System.Linq.Expressions;
using static System.Linq.Expressions.Expression;
```

I've added this to our backlog, and added the "up for grabs" label, if anyone wants to contribute a PR before we get to make this change.
