### ISSUE TITLE
No clear guidance on Units of Measure

### ISSUE THREAD

**Issue by sonicbhoc** [dotnet/docs#29142]
There are no guidelines for units of measure. Due to this, the Fantomas team does not have guidance for formatting them, which leads to oddities such as those seen in fsprojects/fantomas#2207. Please add guidelines for formatting units of measure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by nojaf** [comment]
Please raise this issue over at https://github.com/fsharp/fslang-design#style-guide.

**Comment by BillWagner** [comment]
Adding @dsyme 

Should this be covered here, or in the [fslang](https://github.com/fsharp/fslang-design#style-guide) repo?

**Comment by dsyme** [comment]
We should address this in the style guide

**Comment by gewarren** [comment]
This was addressed by https://github.com/dotnet/docs/pull/29657.
