### ISSUE TITLE
Not compatible with VS 2022.

### ISSUE THREAD

**Issue by rsprinkle** [dotnet/docs#29145]
[Enter feedback here]

The page says the product is compatible with VS 2017 and later.  In fact it is ONLY compatible with 2017 and 2019.  There is no support for VS 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd8086b-9a95-38d5-160f-c12c653f954e
* Version Independent ID: 0f47d826-e3ef-8549-9d37-2e8afae29f46
* Content: [The .NET Portability Analyzer - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer)
* Content Source: [docs/standard/analyzers/portability-analyzer.md](https://github.com/dotnet/docs/blob/main/docs/standard/analyzers/portability-analyzer.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-analyzers**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @rsprinkle 
Thank you so much for posting this issue. We really appreciate it. See #29148
