### ISSUE TITLE
The Chinese version has an obvious error.

### ISSUE THREAD

**Issue by fbilo** [dotnet/docs#29162]
The screenshoot:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/19651809/164974648-3a69dd46-fffa-4dc3-b5df-e434938e7352.png">
The highlight "**x**" should be "**private**". This error is really misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17ee29ae-d0ae-9f8e-545d-15b72901be7d
* Version Independent ID: ca4b8d67-d015-e47d-01bf-06be8c938e4d
* Content: [protected keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected)
* Content Source: [docs/csharp/language-reference/keywords/protected.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/protected.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@khoiph1 Can you route this to the loc folks?

**Comment by gewarren** [comment]
Ping @kgliang
