### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by dalumedic** [dotnet/docs#29164]
[Re: https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage#add-default-implementation)

`public string OperationId { get; } = NewGuid().ToString()[^4..];`

Should be: 

`public string OperationId { get; } = Guid.NewGuid().ToString()[^4..];`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Thew first line of the sample code is:

```csharp
using static System.Guid;
```

This is perfectly valid. I'm going to close this, as the code is correct. Please let me know if you have any other questions or concerns.

**Comment by dalumedic** [comment]
> Thew first line of the sample code is:
> 
> ```cs
> using static System.Guid;
> ```
> 
> This is perfectly valid. I'm going to close this, as the code is correct. Please let me know if you have any other questions or concerns.

Yep, sorry, missed the static using.
