### ISSUE TITLE
Missing documentation for load_assembly_and_get_function_pointer

### ISSUE THREAD

**Issue by mgaeckler1964** [dotnet/docs#29168]
[Enter feedback here]

There is no useful documentation for load_assembly_and_get_function_pointer. So it is not possible to analyse potentional problems. Professional programmers need this, to present their users useful error messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET runtime host - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mjrousos
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
See https://github.com/dotnet/docs/issues/31796#issuecomment-1583188489
