### ISSUE TITLE
Tutorial for "Introduction to classes", problem with `this`

### ISSUE THREAD

**Issue by KZiemian** [dotnet/docs#29175]
I don't understand why in section [_Open a new account_](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes#open-a-new-account) we use keyword `this` in constructor
```
public BankAccount(string name, decimal initialBalance)
{
     this.Owner = name;
     this.Balance = initialBalance;
        
     this.Number = accountNumberSeed.ToString();
     accountNumberSeed++;
}
```
but in the section [_Open a new account_](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes#create-deposits-and-withdrawals) `this` vanish from constructor.
```
public BankAccount(string name, decimal initialBalance)
{
    Number = accountNumberSeed.ToString();
    accountNumberSeed++;

    Owner = name;
    MakeDeposit(initialBalance, DateTime.Now, "Initial balance");
}
```

I also want to ask, what is recommended style: using `this` keyword before names of properties and methods or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Classes and objects  - C# Fundamentals tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes)
* Content Source: [docs/csharp/fundamentals/tutorials/classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising these questions @KZiemian This helps us improve.

I'll answer the questions here, and then add the "up for grabs" label in addition to adding this to our backlog.

To answer your first question:

The `this` modifier is usually optional when you're accessing a member of the current class. The only time it is necessary is to disambiguate between a local variable and a member, as shown in the following:

```csharp
public class Point
{
    private int x;
    private int y;

    public Point(int x, int y)
    {
        // The left side is the member field, the right side is the parameter.
        this.x = x; 
        this.y = y;
    }
}
```

To answer the second question:  Most coding styles recommend not including the `this` modifier except where it is required (as above).

**Comment by raphaelavelar** [comment]
@BillWagner, can I change the first example to remove the `this`  modifier since it isn't necessary there?

**Comment by KZiemian** [comment]
Thank you for the answer. I want to point two minor issues that I have with this page and they probably don't deserve separated GitHub issues, I will post them here.

In [_Create deposits and withdrawals_](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes#create-deposits-and-withdrawals) in `try-and-catch` statement `try` is shown in blue and `catch` in black, this is true both on my Windows and on my GNU/Linux systems. I feel that this is not best syntax highlighting and both this words should be in the same color.

Second issue is in the same part of article [_Create deposits and withdrawals_](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/classes#create-deposits-and-withdrawals). Before code snippet of the second `try-and-catch` statement we can read "Add the following code at the end of your Main method:". If some beginner would do that code
```
try
{
    account.MakeWithdrawal(750, DateTime.Now, "Attempt to overdraw");
}
catch (InvalidOperationException e)
{
    Console.WriteLine("Exception caught trying to overdraw");
    Console.WriteLine(e.ToString());
}
```
would never run and he/she may be confused. This is because that is you write everything according to the page code before would be
```
try
{
    invalidAccount = new BankAccount("invalid", -55);
}
catch (ArgumentOutOfRangeException e)
{
    Console.WriteLine("Exception caught creating account with negative balance");
    Console.WriteLine(e.ToString());
    return;
}
```
and since exception is catched whole function is terminated by `return;`. At least I believe it being the reason, since in all similar languages that I know is how the `return` works.

**Comment by BillWagner** [comment]
Thanks for the additional information @KZiemian 

I'll update per those comments this month.
