### ISSUE TITLE
How to solve the issue of CS8805: Program using top-level statements must be an executable. VS 1053: The service did not respond to the start or control request in a timely fashion. 

### ISSUE THREAD

**Issue by lars-moe** [dotnet/docs#29174]
When the output type is set to "Windows application" or "Console application", the service can't be started and gives error "1053: The service did not respond to the start or control request in a timely fashion.". Digging behind that, I have found that it is due to Windows 10 (+ new Windows server versions) not allowing integration with the the UI (zero session) without the "Interactive Services Detection" service running - and that is not allowed in Windows 10. 

Trying to solve that, using output type "Class library" instead, results in build error "CS8805: Program using top-level statements must be an executable.". I have read som articles saying that this can be due to a double semi-colon somewhere, but I haven't found anything like that in the source files.

So - how do I create a Worker service which is functional on Windows 10 and new Windows servers? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae847f16-ff74-ab68-7163-f713b447430c
* Version Independent ID: ff379d26-0d85-6d74-67da-4a3cd260b04d
* Content: [Worker Services in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers)
* Content Source: [docs/core/extensions/workers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/workers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by BillWagner** [comment]
tagging @CyrusNajmabadi Is this related to the request for attributes on top level programs? Or is this a different issue?

**Comment by CyrusNajmabadi** [comment]
I have absolutely no idea :-)

**Comment by IEvangelist** [comment]
I'm going to close this issue as we are unable to recreate it, nor did the op provide us with a sample to reproduce.
