### ISSUE TITLE
Missing instructions on how to run the app from the commandline

### ISSUE THREAD

**Issue by pheirendt-jama** [dotnet/docs#29171]
Console apps are meant to be run from the commandline, but there are no instructions on how to run the app from the commandline. (The help currently only shows how to run the app from inside Visual Studio for Mac, which is not same as from the commandline.)
NOTE: If it is not possible to run the app from the commandline on Mac OSX, the help should say that or at least have link to more info.
Here is example from the help page for using Visual Studio Code. I think Visual Studio for Mac would be the same? 
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?pivots=dotnet-6-0#run-the-app
![image](https://user-images.githubusercontent.com/68336365/165130696-1ac7db73-251f-4860-9e58-4599f2a0dc1e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957bb4fd-92c9-47ac-da7a-778cea12f429
* Version Independent ID: dd9058df-2586-7b1c-d1cc-ae1b82f047ed
* Content: [Create a .NET console application using Visual Studio for Mac - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac)
* Content Source: [docs/core/tutorials/with-visual-studio-mac.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-mac.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Instructions are in the [Publish tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio-mac#run-the-published-app).
