### ISSUE TITLE
Remarks and Summary tags with Intellisense

### ISSUE THREAD

**Issue by sailro** [dotnet/docs#29186]
Hello,

Starting with Visual Studio `v16.6.5`, there is an option in `Text Editor > C# > Advanced > Editor Help`, called `Show remarks in Quick Info`. 

So perhaps the sentence _"The text for the summary tag is the only source of information about the type in IntelliSense, and is also displayed in the Object Browser window."_ in the `summary` section needs extra clarification.

Thank you and best regards!
S.L.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcb925f-ef72-9a64-3762-c0b4a96f9dc4
* Version Independent ID: d135d0a6-53d2-1567-0b1b-7aae5e07739f
* Content: [Recommended XML documentation tags for a class and its members](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#summary)
* Content Source: [docs/csharp/language-reference/xmldoc/recommended-tags.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/recommended-tags.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 215487](https://dev.azure.com/msft-skilling/Content/_workitems/edit/215487)

**Comment by BillWagner** [comment]
Thanks for raising this @sailro 

Adding @ghogen Is there an article in the VS docs I should link to for this feature?

**Comment by ghogen** [comment]
@TerryGLee @BillWagner @sailro 
The Quick Info doc is here:
https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2022#quick-info
However, it doesn't mention the option to display remarks. Terry G. Lee owns the article and could decide if it needs to be updated to add more information.

**Comment by BillWagner** [comment]
Two other possible targets from an internal discussions:

It might be that either or both of these two pages would be the best place to capture the info for the customer:
 
- [Options, Text Editor, C#, Advanced - Visual Studio (Windows) | Microsoft Docs](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-csharp-advanced)
- [C# IntelliSense - Visual Studio (Windows) | Microsoft Docs](https://docs.microsoft.com/visualstudio/ide/visual-csharp-intellisense)
