### ISSUE TITLE
Problem with first C# template change tutorial 

### ISSUE THREAD

**Issue by geoffsvs** [dotnet/docs#29180]
Console.WriteLine(args) results in "Hello World" in the console output rather than "String"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2939b6-ad9e-4116-c805-8f19ed994c31
* Version Independent ID: ad23d124-a491-2b4f-3c51-0ed5d38d7eba
* Content: [Top-level statements - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements)
* Content Source: [docs/csharp/whats-new/tutorials/top-level-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/top-level-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi 👋 @geoffsvs 

The current content is correct. You can see that in this [sharplab example](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBsCWyaoA6wwQIB2yANDCAnCeQCYgDUAPgAIBMADALABQnAIz9+bQQE4AFFAQBzZAEoA3EA=)

I'll close this.

**Comment by geoffsvs** [comment]
Thanks Bill. I “solved” the problem that prompted my note. I’m deeper into the tutorial now, and don’t understand how the animation code works (I always get the same result) and have tried stepping through the console program but that doesn’t seem to work. I don’t understand when running from the command line is preferable to running using the console.
The bottom line is that I need to find tutorials that help a beginner such as me – the content in the tutorial that prompted my original note assumes I am more knowledgeable that I actually am.
GS

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
