### ISSUE TITLE
Can you please provide some information or consideration for IIS configuration and IIS Application pool identities setup on Azure VM?

### ISSUE THREAD

**Issue by Anand-Moghe** [dotnet/docs#29196]
For ASP.Net web app installed on IIS, what are the steps to configure IIS Application pool identities after installing/migrating the IIS webserver on Azure Windows VM? 

E.g. Can we use AAD Managed Identities for IIS Application pool identities? If not then what is the recommendation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b85ef3ff-f175-c079-38f7-f8b3ae1bde77
* Version Independent ID: 282b1998-dd2e-e863-5712-b9b0826e4b0e
* Content: [Migrate an ASP.NET Web app to an Azure VM](https://docs.microsoft.com/en-us/dotnet/azure/migration/vm)
* Content Source: [docs/azure/migration/vm.md](https://github.com/dotnet/docs/blob/main/docs/azure/migration/vm.md)
* Product: **dotnet-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
I'll be honest, I don't know. My knowledge of IIS has fallen off pretty considerably in the .NET (Core) era. I'm not 100% sure, but last I knew you would need to sync your local AD domain with your AAD tenant.

@Rick-Anderson Do you know? Any ideas on who might?

**Comment by Anand-Moghe** [comment]
@CamSoper  You mean use Azure AD DS and sync on-prem AD server identities?
BTW, this is a major scenario on all migration of legacy and standard ASP.Net web app to IaaS.
So we should provide guidance on this important scenario. It will save lot of time for STU/CSU team while selling these solution.
