### ISSUE TITLE
Link https://aka.ms/microservices-video redirect to https://docs.microsoft.com/en-us/shows/

### ISSUE THREAD

**Issue by rodolforeinafigueroa** [dotnet/docs#29222]
In actions link are this bullet

* Watch the [introductory video on Channel 9](https://aka.ms/microservices-video)

But the link https://aka.ms/microservices-video redirect to https://docs.microsoft.com/en-us/shows/

Where do I find the video?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by gewarren** [comment]
@BillWagner Do you know which video this was supposed to link to? I don't have permissions to see the aka.ms link.

**Comment by BillWagner** [comment]
I don't have access either. This link is owned by @nishanil

**Comment by nishanil** [comment]
Thanks for pointing it out. I have fixed the redirection to the most recent Introduction Video on Microservices.

**Comment by rodolforeinafigueroa** [comment]
@nishanil @BillWagner @gewarren Thank's for the help.
