### ISSUE TITLE
using 

### ISSUE THREAD

**Issue by geoffsvs** [dotnet/docs#29226]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2939b6-ad9e-4116-c805-8f19ed994c31
* Version Independent ID: ad23d124-a491-2b4f-3c51-0ed5d38d7eba
* Content: [Top-level statements - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements)
* Content Source: [docs/csharp/whats-new/tutorials/top-level-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/top-level-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @geoffsvs 

Do you have questions here? Can you add more details?

**Comment by geoffsvs** [comment]
Thanks for your intent to help, Bill. I have decided not to continue with the particular tutorial that prompted my question - in order to get the animation to work it said that a using statement was required (I forget the full name but it ended with Tasks) however my program greyed that statement out saying it was not necessary. To make a long story short, I've started another suite of tutorials devoted to Visual Studio console programs. The plethora of options available via the Microsoft site is overwhelming and would benefit significantly if an overall map of what's available and their end uses was provided.
Hopefully my primitive objectives are not foiled by what I have selected .
Cheers
Gsvs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
