### ISSUE TITLE
imge

### ISSUE THREAD

**Issue by simikurtz** [dotnet/docs#29238]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f98776d-66cc-91ad-697a-783f80914f9c
* Version Independent ID: 66121850-861c-9e37-27f0-811f80427d70
* Content: [Compiler Error CS1503](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503))
* Content Source: [docs/csharp/misc/cs1503.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**
![image](https://user-images.githubusercontent.com/96599768/166151102-1322fd30-5da5-4b8f-927c-159a3076482f.png)
![צילום מסך 2022-05-01 174704](https://user-images.githubusercontent.com/96599768/166151130-79dc31be-4688-48b3-bcbd-73a924ddc96a.png)

**Comment by BillWagner** [comment]
Hi @simikurtz 

From the images, it looks like there's a mismatch in the types you're using.

I'll suggest asking a detailed question on the Microsoft [.NET Q A &](https://docs.microsoft.com/answers/products/dotnet) forums.

If you have specific questions about the article, can you add more detail here?
