### ISSUE TITLE
Error in Program.cs

### ISSUE THREAD

**Issue by CODevOp** [dotnet/docs#29237]
[Enter feedback here]

In the Program.cs file , the line where the method StartsWithUpper is called is incorrect.
Instead of input.StartsWithUpper() it shold read StringLibrary.StartsWithUpper(input)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cbb75b-e0aa-13c6-c07d-65f0f0f68da2
* Version Independent ID: 06ecbd1e-dad7-fbac-9160-dfce34df4d2c
* Content: [Create a .NET class library using Visual Studio Code - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code?pivots=dotnet-6-0)
* Content Source: [docs/core/tutorials/library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
At the end of step 4 under [Create a class library project](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code?pivots=dotnet-6-0#create-a-class-library-project), it explains that the code creates an extension method:

> `StartsWithUpper` is implemented as an [extension method](https://docs.microsoft.com/csharp/programming-guide/classes-and-structs/extension-methods.md) so that you can call it as if it were a member of the <xref:System.String> class.
