### ISSUE TITLE
The examples for `*?`, `+?` and `??` are the same for `*`, `+` and `?`

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#29239]
The examples for `*?`, `+?` and `??` are the same for `*`, `+` and `?` and I fail to understand the difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
There's a slight difference in the examples for `+` and `+?`, but I agree, these examples could be improved.

**Comment by paulomorgado** [comment]
These are some of the examples that show matches without showing where they come from.

For example:

|Quantifier|Description|Pattern|Matches|
|----------------|-----------------|-------------|-------------|
|`*`|Matches the previous element zero or more times.|`a.*c`|`"abcbc"` in `"abcbc"`|
|`*?`|Matches the previous element zero or more times, but as few times as possible.|`a.*?c`|`"abc"` in `"abcbc"`|

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. I'm going to back up the automated priority label to Pri3 and flag this for community contribution.

Thanks again!
