### ISSUE TITLE
Metrics instrumenttypes ObservableCounter and ObservableGauge thread safety?

### ISSUE THREAD

**Issue by gfoidl** [dotnet/docs#29260]
The instrumenttypes ObservableCounter and ObservableGauge have a callback delegate, that return the values. In the shown examples these values are read without any measure of thread safety, so will the visibility be given? 
Should they be read by `Interlocked.Read` / `Volatile.Read` instead?

For the event counters there's a section [about Concurrency](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters#concurrency) dealing with that issue. Does this apply for these instrumenttypes too?
If so, a similar section should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024acd-c2e8-291a-3007-7f09a1857690
* Version Independent ID: 02ec1bf2-d0fe-dac5-b2c1-45d607430b06
* Content: [Creating Metrics](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation#feedback)
* Content Source: [docs/core/diagnostics/metrics-instrumentation.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/metrics-instrumentation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by gewarren** [comment]
@noahfalk Could you help with this question?

**Comment by noahfalk** [comment]
@gfoidl - Sorry for late reply here, I see you asked the question months ago.
Its true that the callbacks will occur on a thread that is usually not synchronized with whatever code may be updating the values that are read. I agree that we should add more clarification in docs, similar to the EventCounters section you referenced.

Fwiw, all the samples that I noticed are already thread-safe as-is, but they are relying on some subtle details for that to be true and no attention is being called to the issue.
