### ISSUE TITLE
Refers to, but does not explain what an *interpolated expression* is/can be

### ISSUE THREAD

**Issue by selebi-pikwe** [dotnet/docs#29261]
Refers to, but does not explain what an _interpolated expression_ is/can be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a5a3d2-fec7-173f-7256-d97a45e25223
* Version Independent ID: 6e6faf37-877c-d455-53bb-968a02bcdc01
* Content: [$ - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/special-characters/interpolated)
* Content Source: [docs/visual-basic/language-reference/special-characters/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/special-characters/interpolated.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
We should take the definition from the [C# string interpolation page](https://docs.microsoft.com/dotnet/csharp/language-reference/tokens/interpolated#structure-of-an-interpolated-string):

> An *interpolated expression* is an expression that produces a result to be formatted in the resultant string.
