### ISSUE TITLE
Add info on how to consume .NET Standard 2.0 libraries from VS2015

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2927]
Need to add info about how to consume .NET Standard 2.0 libraries into the .NET Standard topic. You can do it with VS 2015 too if you have the latest NuGet client.

https://github.com/dotnet/announcements/issues/24

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by davidljung** [comment]
No mention of Windows 10?

**Comment by mairaw** [comment]
Not sure if I understand the question @davidljung. Why would we mention Windows 10 in this context?
