### ISSUE TITLE
Incorrect example for InlineIfLambda in page What's new in F# 6

### ISSUE THREAD

**Issue by MHHenriksen** [dotnet/docs#29295]
The example in https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6#inlineiflambda seems totally wrong: 

> For example, consider the following iterateTwice function to traverse an array:
> ```F#
>let inline iterateTwice ([<InlineIfLambda>] action) (array: 'T[]) =
>     for j = 0 to array.Length-1 do
>          action array[j]
>      for j = 0 to array.Length-1 do
>          action array[j]
> ```
> If the call site is:
> ```F#
> let arr = [| 1.. 100 |]
> let mutable sum = 0
> arr  |> iterateTwice (fun x ->
>     sum <- sum + x)
> ```
> Then after inlining and other optimizations, the code becomes:
> ```F#
> let arr = [| 1.. 100 |]
> let mutable sum = 0
> for j = 0 to array.Length-1 do
>     sum <- array[i] + x
> for j = 0 to array.Length-1 do
>     sum <- array[i] + x
> ```

Note the use of `array` instead of `arr`, replacing `sum` instead of `x` and `[i]` instead of `[j]`.

This is a fixed version (unless I missed something :P ):

```F#
let arr = [| 1.. 100 |]
let mutable sum = 0
for j = 0 to arr.Length-1 do
    sum <- sum + arr[j]
for j = 0 to arr.Length-1 do
    sum <- sum + arr[j]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2dea170-a8f4-90f6-e578-e406fb43fef1
* Version Independent ID: 885f9f09-d2ff-112c-6dda-9a31bccc0e8a
* Content: [What's new in F# 6 - F# Guide](https://docs.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6)
* Content Source: [docs/fsharp/whats-new/fsharp-6.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/whats-new/fsharp-6.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
@KathleenDollard @dsyme
