### ISSUE TITLE
SEO - add missing descriptions

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2930]
We need to divide and conquer and over time add the missing descriptions for SEO purposes.

Assigning to the current milestone, so we continuously work on this as a team.
[Missing Meta Description.xlsx](https://github.com/dotnet/docs/files/1230333/Missing.Meta.Description.xlsx)

Excel spreadsheet with missing descriptions attached.

**Comment by mairaw** [comment]
I think we could split the folders between the 4 of us:
@BillWagner - csharp
@rpetrusha - visual-basic
@mairaw - framework, fsharp and core
@JRAlexander - standard

Submit a few/week so we can make progress towards adding descriptions for all .NET topics.

**Comment by BillWagner** [comment]
@mairaw I think this is done now?  If you agree, we can close it.

**Comment by mairaw** [comment]
Unfortunately not @BillWagner. A lot of topics still don't have descriptions. Let me see if I can find updated data.

**Comment by mairaw** [comment]
I lowered the priority for now and the spreadsheet should still be pretty accurate. The global metadata changes wouldn't impact missing descriptions. These have to be individually written for each article.
