### ISSUE TITLE
Recovery via scm does not work

### ISSUE THREAD

**Issue by isam2k** [dotnet/docs#29308]
The recovery options outlined in this article do not work and - as far as I understand it - this will produce drastically different results depending on the version of .net being used.

The service itself is fine, but the recovery via scm does not work. If there was an uncaught exception in this example, then (in .net 5.0) this would result in a service that would be "running" but effectively dead (the main loop is exited but the host won't shut down).

In .net 6.0 now the default behaviour seems to be that [the host will stop if an uncaught exception occurs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/hosting-exception-handling). However, there's an issue here: The service will report "Service stopped successfully" and the scm will never restart it. I think this is because the service reports SERVICE_STOPPED and therefore the scm won't recognize it as a failure.

I have read from multiple sources that reset=0 in the recovery options results in the failure counter never going above 1, so the recovery options for second and subsequent failures in the article are never executed. I have not tested this myself though so I'm not 100% certain that this is the current behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @isam2k, thank you for posting this issue. Much appreciated. I'll take a look at this, try to recreate it and then report back.

**Comment by IEvangelist** [comment]
Hi again @isam2k, please see #29310 and let me know what you think.

**Comment by isam2k** [comment]
Hi @IEvangelist, thank you. Can confirm this approach works for me. I think there's an argument to be made that there should probably be a third behaviour option for uncaught exceptions which will call Environment.Exit() and set the exit code to the HResult value of the exception maybe but that might be going a bit too far. Thanks anyway for clearing this up.
