### ISSUE TITLE
Service is not working as expected.

### ISSUE THREAD

**Issue by vikasdinavahi** [dotnet/docs#29317]
[Enter feedback here]
I am using VS 2022 and .Net 5 and developed the app, I haven't looked at the samples project yet. Will take a look at it soon.
Overall it give good insights and nice ideas to extend further.
But I am facing below issues:
1) When control executes below Bolded line, console is ending the process, nothing happenes other thant a message in the console to close the app when I am in debug mode, if I run the exe as is, from the build then the app closes.
 private async ValueTask MonitorAsync()
    {
        while (!_cancellationToken.IsCancellationRequested)
        {
            **var keyStroke = Console.ReadKey();**
            if (keyStroke.Key == ConsoleKey.W)
            {
                // Enqueue a background work item
                await _taskQueue.QueueBackgroundWorkItemAsync(**BuildWorkItemAsync**);
            }
        }
    }

2) Some how I managed to send the ConsoleKeyInfo from Program.cs, it moves forward but I do not see "BuildWorkItemAsync" method getting executed.
Here is what I see:
![image](https://user-images.githubusercontent.com/18430180/167202109-ee2a7b17-0e37-4c29-8639-91acf5933f1d.png)

Not sure if I am missing anything.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bac4b0-9ea8-9471-c1a8-88c8bdd7e733
* Version Independent ID: 976f3af2-4d3f-6d45-1e9e-b4c86edaed34
* Content: [Create a Queue Service](https://docs.microsoft.com/en-us/dotnet/core/extensions/queue-service)
* Content Source: [docs/core/extensions/queue-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/queue-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @vikasdinavahi - the sample source code works as described in the article:

https://github.com/dotnet/samples/tree/main/core/workers/queue-service

If that exact code doesn't work, then we can continue to discuss it here. But if you made changes to it, or wrote your own bits - it's better for you to ask your questions on StackOverflow.

**Comment by IEvangelist** [comment]
Closing as we lack the required information needed to reproduce this issue or help the op.
