### ISSUE TITLE
Continuous integration and deployment - DevOps for ASP.NET Core Developers feedback

### ISSUE THREAD

**Issue by rafail-r** [dotnet/docs#29330]
screenshot about continuous integration is not accurate.
The checkbox is available only after checking "Override the YAML continuous integration trigger from here"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a1da14-56ef-2ff8-e038-bd1c1e4f975b
* Version Independent ID: 3d5a172c-88a5-c712-30c9-6a3fd51fa310
* Content: [Continuous integration and deployment - DevOps for ASP.NET Core Developers](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/cicd)
* Content Source: [docs/architecture/devops-for-aspnet-developers/cicd.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/cicd.md)
* Product: **dotnet-architecture**
* GitHub Login: @CamSoper
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 142254](https://dev.azure.com/msft-skilling/Content/_workitems/edit/142254)

**Comment by erjain** [comment]
Hi @CamSoper, any idea about the above issue?

**Comment by CamSoper** [comment]
@erjain I'mma be honest with you @erjain, I completely forgot I co-wrote this.

 I'll update it sometime soonish. No promises as to when, I'm swamped at the moment.
