### ISSUE TITLE
Automatic translation of "See Sharp" (as a phonetic hint) to French is erroneous

### ISSUE THREAD

**Issue by ojob** [dotnet/docs#29346]
Hello,
Reading this page in French translation, I read that:

> C# (pronounced "See Sharp")

is translated as follows:

> C# (prononcé « voir Sharp ») 

Said otherwise, the verb "see" is translated, which results in the phonetic hint to be lost.

**Proposal:** translate to "si charp", which any French reader should be able to understand and pronounce as intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [A tour of C# - Overview](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
tagging @khoiph1 for a translation issue.

**Comment by gewarren** [comment]
Ping @kgliang
