### ISSUE TITLE
FTP Upload sample code for .NET Framework uses C# 8

### ISSUE THREAD

**Issue by GnoZ** [dotnet/docs#29363]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a421182a-dac9-c619-b501-240dd2aafd7b
* Version Independent ID: 30940ebd-4501-8580-2efc-c6abf522fe93
* Content: [How to: Upload files with FTP - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-upload-files-with-ftp)
* Content Source: [docs/framework/network-programming/how-to-upload-files-with-ftp.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/how-to-upload-files-with-ftp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by IEvangelist** [comment]
Hi @GnoZ - is there an issue with this sample using C# 8? If not, let's close this.

**Comment by GnoZ** [comment]
Hi, C# 8 is not supported on Net Framework, only Net core 3.0 and above

BRES Clément
________________________________

**Comment by IEvangelist** [comment]
Hi @GnoZ - see https://github.com/dotnet/docs/pull/29448
