### ISSUE TITLE
CA1812 and new() constraint

### ISSUE THREAD

**Issue by znakeeye** [dotnet/docs#29362]
One way to silence `CA1812` is to have a method with a generic constraint like shown below. Currently, the documentation actually contains a _counter-example_ of this `new()` constraint, which is a bit confusing.

Perhaps add this example to the documentation? 

```c#
SilenceCA1812<MyClass>();

private static void SilenceCA1812<T>() where T : new()
{
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d34eee1-2619-6701-31e2-7d56cc690ebb
* Version Independent ID: 8a9b0c36-3000-7b71-c0f2-a5b01e54174f
* Content: [CA1812: Avoid uninstantiated internal classes (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1812.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1812.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
Hi @znakeeye - The example seems accurate. The `MyClass` is `internal`, and it is never directly instantiated. What am I missing?

**Comment by znakeeye** [comment]
The *example* is indeed accurate. But my example is also accurate. It uses the `new()` constraint  - with the opposite effect. The warning goes away. Lifehack!

The docs state this condition for CA1812:
*"The class is passed as a type parameter that has a new constraint"*

That is inaccurate, as ahown in my example above.

**Comment by gewarren** [comment]
I opened a PR to improve the clarity of the existing statement.
