### ISSUE TITLE
Packaging and deploying apps: Deploying applications overview

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#294]
Issue tracking new topic at http://dotnet.github.io/docs/deployment/overview.html

**Comment by kempb** [comment]
Due to product churn in this area, I'll be working on this post-//Build.

**Comment by rpetrusha** [comment]
This is documented in [.NET Core Application Deployment](https://www.github.com/dotnet/docs/tree/master/docs/core/deploying/index.md).
