### ISSUE TITLE
Wording in "When a class or struct is created"

### ISSUE THREAD

**Issue by Beechside** [dotnet/docs#29414]
You say: "When a class or struct is created" but I have a problem with the word "created".  The class is created when defined, just as a blueprint is created when it is drawn.  The class exists at that point with or without instantiation but that is not when a constructor is run.  Unless "created" has a very specific meaning, should you use "instantiated"?   

An Instance Constructor is run when a class is instantiated, unless there is something else in the chain of events that makes creation different from instantiation.

Best wishes,

Pete Morris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a58d4-1905-c664-04b6-fd68e617f8c9
* Version Independent ID: 36d0bf3a-29bf-5162-c700-142b03f9a16c
* Content: [Using Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
thanks for the suggestion @Beechside 

That would be better wording. I've added this to address when we next update this section.
