### ISSUE TITLE
Conserve Memory - wrong version introduced for environment variable?

### ISSUE THREAD

**Issue by vepkapis** [dotnet/docs#29429]
Greetings, 

Is there a mistake in table column "Version introduced" in "Conserver Memory" section of a document for second Environment variable "COMPlus_GCConserveMemory"?
It says that environment variable "COMPlus_GCConserveMemory" was introduced in .NET 6, but I think that COMPlus environment variables were introduced before in .NET Core versions of framework (like it is case for other sections and COMPlus Environment variables).

Main reason why I'm asking for this is can I use COMPlus_GCConserveMemory environment variable in .NET Core 3.1 or this is not a mistake and I can't use it.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95249f95-dd1e-c3e2-032a-2c91057c50d4
* Version Independent ID: 5363faee-3808-d011-d371-c48a95dcabf0
* Content: [Garbage collector config settings - .NET](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector)
* Content Source: [docs/core/runtime-config/garbage-collector.md](https://github.com/dotnet/docs/blob/main/docs/core/runtime-config/garbage-collector.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
That was an error from a misunderstanding on a PR comment. Thanks for catching it. It's been available since .NET Framework 4.8.
