### ISSUE TITLE
NRT (nullable reference types) documentation says they're turned off by default

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/docs#29426]
On https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types, it says this:

> Nullable reference types, the null static analysis warnings, and the [null-forgiving operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving) are optional language features. **All are turned off by default.**

It feels kind of strange to me to say that these features are turned off by default, because from .NET 6 onward, NRT's are enabled by default in all new projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c4bf74-8064-6c45-d5c8-2bbdb0113895
* Version Independent ID: 3250ed35-9410-87f6-ba3e-258c85fbc7f1
* Content: [Nullable reference types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-reference-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to my attention @Bosch-Eli-Black 

I've opened a PR to address this issue.

**Comment by Bosch-Eli-Black** [comment]
Thanks; looks great! 🙂
