### ISSUE TITLE
Breaking-up interpolated strings into pieces

### ISSUE THREAD

**Issue by kuzminrobin** [dotnet/docs#29440]
I failed to find on the page (and [this one](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) too) the answer to the following question.

If the interpolated string is very long and I want to break it up into multiple pieces (each having an interpolation expression), then does each part have to be prefixed with `$`?
Example: Original interpolated string `$"{a}{b}"`.
Which break-up is right, 
this `$"{a}" + "{b}"` or
this `$"{a}" + $"{b}"`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great question @kuzminrobin 

Currently, you'd need to add the `$` on both expressions: `$"{a}" + $"{b}"`.

However, starting with C# 11, you could use [raw string literals](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-11#raw-string-literals) to create an interpolated string expression that spans multiple lines. (That's a bit different than what you'd asked, but I think it would fit the scenario in practice).

I've added this to our backlog, and I've added the "up for grabs" label, if anyone wants to add a sample or two as I've described.
