### ISSUE TITLE
Add reference to ProduceReferenceAssembly

### ISSUE THREAD

**Issue by redwyre** [dotnet/docs#29445]
[Enter feedback here]
reference `ProduceReferenceAssembly` to make this discoverable from search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ca424e-247c-138d-1c41-9c2b116862df
* Version Independent ID: adc585dd-e215-4c70-f9a6-38a0e91e46da
* Content: [Breaking change: Write reference assemblies to IntermediateOutputPath - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj)
* Content Source: [docs/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@redwyre It looks like `ProduceReferenceAssembly` [defaults to true](https://github.com/dotnet/sdk/pull/12720) for projects that target .NET 5 and later, so most people wouldn't be setting it explicitly. But I'm interested in why you think people would be searching on it.

**Comment by gewarren** [comment]
@baronfel Do you think a reference to `ProduceReferenceAssembly` should be added, and if so, in what context?

**Comment by baronfel** [comment]
The option is already quite well documented in [the c# compiler options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#producereferenceassembly) so I'm inclined to say we shouldn't need to add anymore. I'm definitely amenable to changing that feeling based on @redwyre's context, though. The wording of this page might be changed to suggest that reference assemblies aren't _required_ to be generated from a given build? They're a performance optimization, after all.

**Comment by redwyre** [comment]
I enable `ProduceReferenceAssembly` because we ship them, and the new change broke the build, but `ProduceReferenceAssembly` is all I was setting in my csproj so there's nothing to link that you now need `ProduceReferenceAssemblyInOutDir` to get the same behaviour when you were relying on it. So just adding that to the page would make it discoverable for people like me that were wondering "why isn't `ProduceReferenceAssembly` working any more?"

**Comment by baronfel** [comment]
Proposed new verbiage for the `Old behavior` section:

> Old behavior
>
> Since reference assemblies were added, the .NET SDK has written reference assemblies to the ref directory in the OutDir directory of the compilation. In .NET 5, the [ProduceReferenceAssembly](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#producereferenceassembly) property was introduced and defaulted to true for .net5.0 and higher applications, so many applications began generating reference assemblies to this directory implicitly.

@redwyre you set this property to true explicitly, so I'm gathering that you're not targeting net5.0+ for these projects?

**Comment by redwyre** [comment]
The projects have been updated from .net core -> net5 -> net6, but I set it to true originally because I explicitly use the reference dlls as build outputs (which is why it's a breaking change).
