### ISSUE TITLE
typo on interface type name

### ISSUE THREAD

**Issue by BSeyfi** [dotnet/docs#29455]
In this [section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods#diamond-inheritance-and-classes-closed) , at the end of the code part, `Ia` should be replaced with `IA`.
thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17012c83-0313-919b-eb8b-04fae8f4df4a
* Version Independent ID: 05252e5a-e53c-5ce5-84b3-671faad0549c
* Content: [Default interface methods - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods)
* Content Source: [proposals/csharp-8.0/default-interface-methods.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
See https://github.com/dotnet/csharplang/pull/6124
