### ISSUE TITLE
Why is main async? It doesn't return a task. Sloppy work.

### ISSUE THREAD

**Issue by chrispetkau** [dotnet/docs#29452]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Can you clarify which example you're talking about and expand on what's wrong with it?

In this article, I only see `static void Main` and `static async Task Main`, which are both correct.

**Comment by chrispetkau** [comment]
The Task-returning method using async and await not needing a return statement is what I find confusing. I will need to read up on that some more. I suppose some note or link in the docs addressing this potential confusion might be useful.
