### ISSUE TITLE
RIDs for .NET 6 iOS and Android are missing

### ISSUE THREAD

**Issue by dotMorten** [dotnet/docs#29458]
It would be nice if you could add the RIDs for iOS and Android as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Runtime Identifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/main/docs/core/rid-catalog.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@wfurt should we add sections for iOS and Android?

**Comment by wfurt** [comment]
It would make sense to me since they are in the RID graph.

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtimeGroups.props
