### ISSUE TITLE
Static members of an `interface` can also be re-implemented

### ISSUE THREAD

**Issue by BSeyfi** [dotnet/docs#29471]
in this [section](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces):

> "To implement an interface member, the corresponding member of the implementing class <ins>**must**</ins> be public, <ins>**non-static**</ins>, and have the same name and signature as the interface member."

but I can implement an static member in an interface and re-implement it in a class.
**`public`**  is also **not mandatory.**

**Example:**
```csharp
   
    interface IZ
    {
        static private string _name = "";
        public static string Name(string name)
        {
            _name = name;
            return _name;
        }
    }

    class StaticReImp : IZ
    {
        private static string _name = "";
        public static string Name(string name)
        {
            _name = name + " <<<static member can be reimplement>>>";
            return _name;
        }
    }
```
I ran it successfully on C#10 - .NET 7.

thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fd340a-0f74-8602-28a1-9569296a5951
* Version Independent ID: 1f0a9a2b-6495-370d-620f-a6dabec7df3b
* Content: [Interfaces - define behavior for multiple types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces)
* Content Source: [docs/csharp/fundamentals/types/interfaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BSeyfi** [comment]
thanks @BillWagner 
but i think it is better to use the `new` keyword for defining a new member ( To be in consistency with non-static members)
(using  `new` for declaring `StaticReImp.Name`)
both your code and with `new` one have same result, but the version declared with `new` keyword is in more consistency with  non-static members, IMO.
```csharp
/*rest of your code*/
class StaticReImp : IZ
{
    //rest of members
    new public static string Name(string name)
    {
         //body
    }
}
//...//

**Comment by BillWagner** [comment]
> but i think it is better to use the `new` keyword for defining a new member ( To be in consistency with non-static members)
> (using `new` for declaring `StaticReImp.Name`)

@BSeyfi The `new` modifier isn't required when a derived class creates a static method with the same signature as a static method in the base class. The behavior for static methods in interfaces is consistent with that behavior. If you want to request a new language feature to require the `new` modifier, you should start a discussion for that on the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.
