### ISSUE TITLE
Frontend not daprized

### ISSUE THREAD

**Issue by ffrankozz** [dotnet/docs#29483]
[Enter feedback here]
Hi, I would like to ask a simple question about the application setup for the ecommerce app: I see that the frontend project is not daprized. Is there any particular reason for that?.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5a1dc6-9f1a-e030-9881-44e13ac6d450
* Version Independent ID: 5808b993-1f47-7801-6c0c-1b5725cd9711
* Content: [Introduction to the eShopOnDapr reference application](https://docs.microsoft.com/en-gb/dotnet/architecture/dapr-for-net-developers/reference-application)
* Content Source: [docs/architecture/dapr-for-net-developers/reference-application.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/reference-application.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Thanks @ffrankozz, for sharing your question. I believe it is just to reduce the complexity of the application.

Hi @amolenk, adding you to this thread. Need your thoughts on this.

**Comment by amolenk** [comment]
Hi,
This question was also asked over at the eShopOnDapr repo. For the full answer, see https://github.com/dotnet-architecture/eShopOnDapr/issues/96
