### ISSUE TITLE
Wrong information about CA1848

### ISSUE THREAD

**Issue by hasan-akgun-sveasolar** [dotnet/docs#29504]
CA1848 is giving an error instead of a warning after updating from .NET SDK v6.0.201 to v6.0.300. There is no info about this and it breaks the build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963ffcee-06de-68ab-d920-f92528f1cded
* Version Independent ID: c3a759df-f039-53ca-46d7-4c7621c1491e
* Content: [CA1848: Use the LoggerMessage delegates (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1848)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1848.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1848.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
According to https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md, CA1848 should be hidden by default. Is it set to generate a warning in your .editorconfig file, perhaps?

**Comment by hasan-akgun-sveasolar** [comment]
> According to https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md, CA1848 should be hidden by default. Is it set to generate a warning in your .editorconfig file, perhaps?

I have checked it but no, there is nothing regarding CA1848 on my `.editorconfig` file. Even if I have, it shouldn't behave differently within different patch versions.

**Comment by Youssef1313** [comment]
@hasan-akgun-sveasolar Did you set AnalysisMode or AnalysisLevel or something?


It would be best if you can create a minimal repro project.

**Comment by hasan-akgun-sveasolar** [comment]
> @hasan-akgun-sveasolar Did you set AnalysisMode or AnalysisLevel or something?
> 
> It would be best if you can create a minimal repro project.

I got the trouble maker, there is a setting in Directory.Build.props as this:

`<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`
