### ISSUE TITLE
https://packages.microsoft.com files not found

### ISSUE THREAD

**Issue by lizfrank** [dotnet/docs#29500]
The files located at https://packates.microsoft.com have been moved permanently.  Can this document be updated with the current location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by richlander** [comment]
Can you provide more information on what you are trying to do and the error you are seeing?

**Comment by lizfrank** [comment]
I'm trying to build an airflow docker container and install additional libraries with apt.  This is the error I get:

Get:10 http://deb.debian.org/debian buster-updates/main amd64 Packages [8796 B]
Reading package lists...
E: The repository 'https://packages.microsoft.com/debian/10/prod buster Release' does not have a Release file.

This is the output from curl when I try to list anything on that site:

curl -l https://packages.microsoft.com/config/ubuntu
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by richlander** [comment]
I tried these instructions. They seemed to work file: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204

Perhaps try `InRelease`.

**Comment by lizfrank** [comment]
I took another approach and removed the reference to microsoft from within the docker airflow container and it seems to be working now.  Thank you for looking into it from your side.

**Comment by adegeo** [comment]
This seems resolved by customer, I'm going to close it.
