### ISSUE TITLE
Context needed

### ISSUE THREAD

**Issue by MichaelBrooks-Informatyx** [dotnet/docs#29518]
[Enter feedback here]
What is an "Azure service client" and why would I need or want to register it? The expression "Azure service client" would imply to me a program/client (which I am developing) that consumes some service/API which in turn is hosted within Azure. As it stands, I see no need for any form of registration as such - the most that clients of services normally need to provide before being able to use the service is authentication. I can foresee certain specific services might require some form of registration, but this page appears to be approaching the topic as though it is a generic requirement.
If it's the case that I am misinterpreting the term "Azure service client", then I think that this term needs to be defined. Remember that many of us arrive on these pages directly either from links in other Microsoft pages or from Google search results - we haven't necessarily already read everything that the author might wish for us to have read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e2a2da-cb07-a454-dbfa-7349007812a2
* Version Independent ID: 2cbfee72-6851-6224-fd83-1819515926a9
* Content: [Dependency injection with the Azure SDK for .NET](https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection)
* Content Source: [docs/azure/sdk/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/dependency-injection.md)
* Product: **dotnet-azure**
* GitHub Login: @pakrym
* Microsoft Alias: **casoper**

**Comment by gewarren** [comment]
@IEvangelist or @CamSoper can you help with this one?
