### ISSUE TITLE
Example required

### ISSUE THREAD

**Issue by Waleed-Azam** [dotnet/docs#29536]
it could be improved a bit more, lack with information and I would say there is a need for an example too, it can help freshies in a much better way and could prove more helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af78d7ff-fc41-b781-6d86-608822a521b8
* Version Independent ID: aedd6ee0-5877-56fd-3f5d-fb66de46e316
* Content: [Equality operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators)
* Content Source: [docs/csharp/language-reference/operators/equality-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/equality-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @Waleed-Azam 

Can you provide more details on what examples you'd like to see? There are already several examples, and I want to make sure any additional samples provide the information you're looking for.

Thanks.
