### ISSUE TITLE
subgardening

### ISSUE THREAD

**Issue by s0fire** [dotnet/docs#29541]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89966aa-b155-c98a-2391-47e01d468236
* Version Independent ID: de902eee-6f6b-3ccd-4dbf-1cc174daa806
* Content: [Troubleshooting 'This application could not be started' - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=KMSUPD.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0)
* Content Source: [docs/framework/install/application-not-started.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/application-not-started.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tdykstra** [comment]
Please explain.

**Comment by ALROES** [comment]
/dotnet-install.sh -c Current --runtime aspnetcore
