### ISSUE TITLE
The syntax filter FullyQualifiedName\!~IntegrationTests seems incorrect

### ISSUE THREAD

**Issue by samidutt** [dotnet/docs#29560]
Hi,
I have used the below syntax in my git action :
**dotnet test --filter FullyQualifiedName\!~IntegrationTests**
and it was saying, **No test matches the given testcase filter `FullyQualifiedName\!~IntegrationTests`**. I tested the same in my local computer ad got the same result. Then I tried without '\' char and it successfully ran.  So, please consider my scenario and have a look into the above syntax. I think it should be **dotnet test --filter FullyQualifiedName!~IntegrationTests**

Thank You,
Samir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb70526f-d02c-2b6c-3d34-0f4cac5809f0
* Version Independent ID: e4443d71-7131-ae9b-447d-9ac0762a99fc
* Content: [Run selected unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest&source=docs)
* Content Source: [docs/core/testing/selective-unit-tests.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/selective-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @smadala
* Microsoft Alias: **dapine**

**Comment by tdykstra** [comment]
What OS are you running?

**Comment by samidutt** [comment]
> What OS are you running?

I have tested in my local computer, and this is windows OS. But in Git workflow, I am using ubuntu-latest.
