### ISSUE TITLE
Can not find "fsc.exe"

### ISSUE THREAD

**Issue by kenqcl** [dotnet/docs#29609]
Looking at the SDK directory "C:\Program Files\dotnet\sdk\6.0.203\FSharp"
There is only "fsc.dll", there is not "fsc.exe"

"dotnet fsc" is not a valid dotnet command as well

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c40365d-5626-9a4f-4de3-15d14c40af2b
* Version Independent ID: 8fecd942-bbd7-7e61-092d-084896250876
* Content: [Compiler Options - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options)
* Content Source: [docs/fsharp/language-reference/compiler-options.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/compiler-options.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by KathleenDollard** [comment]
In .NET (Core) you use `dotnet build` to build applications and include any compiler options in the .fsproj file. One of the reasons for this is that the .dll layout for the .NET runtime files is much more complicated which would result in very verbose and difficult to manage arguments. `dotnet build` just takes care of this,

Do you have a scenario where you need fsc or did you find this page confusing on this point?

`csc.exe` is also not present on the SDK path.

**Comment by BillWagner** [comment]
Thanks for noting this @kenqcl 

I've opened a PR to address this issue, recommending `dotnet build`.

**Comment by kenqcl** [comment]
Thanks. 
So, `dotnet build` is the best way to compile across platform, Windows, Linux, etc.
The document need to keep updated.

Maybe, `fsc`, `csc `can be added as dotnet command. like `dotnet fsi` for F# script.
I might want to just compile one file, or just to get the version of F#.

Thank you for looking into this.

**Comment by BillWagner** [comment]
@kenqcl This has been proposed here: dotnet/core#5473 You can join the discussion.
