### ISSUE TITLE
Missing important information about transactional grains

### ISSUE THREAD

**Issue by e-norm-repo** [dotnet/docs#29620]
Each grain that relies on transaction behavior also [needs to be reentrant](https://github.com/dotnet/orleans/issues/5644#issuecomment-502803583) for transactional behavior to work as expected.

It would be helpful to show this in the documentation.

Also, it would be very helpful with some documentation illustrating how to implement a transactional storage. It's mentioned in the documentation that an implementer [can use ITransactionalStateStorage<TState>](https://docs.microsoft.com/en-us/dotnet/orleans/grains/transactions#transactional-state-storage), but there is nothing in the documentation about how to do it, what constraints that applies, or sample given.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233761c6-cd47-3faf-9b8b-d6d074ef6837
* Version Independent ID: 34764110-226e-2ae3-5ea0-3c5895015ab5
* Content: [Transactions in Orleans](https://docs.microsoft.com/en-us/dotnet/orleans/grains/transactions)
* Content Source: [docs/orleans/grains/transactions.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/transactions.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 30919](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30919)

**Comment by IEvangelist** [comment]
Let's ask @ReubenBond to make sure this is correct, thoughts on this?

**Comment by IEvangelist** [comment]
Closed by #32227
