### ISSUE TITLE
Cannot find link to make a docs issue from the docs site

### ISSUE THREAD

**Issue by pbiggar** [dotnet/docs#29651]
I cannot find the link to report an issue from the docs site. Filing this in case the link got accidentally removed.

I've [successfully done this before](https://github.com/dotnet/docs/issues/27689), but I've now been looking at the page for 5 minutes and can't find how to report an issue.

For example, I go to https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0, and there's nothing in the header:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/181762/170688660-2f7a0619-0072-48ec-ab0a-379c2918a9c9.png">

Also checked the sidebar and the other two headers and the footer. I tried pressing "downvote". I tried logging in. I searched the page for "report" or "suggest" or "feedback" or "bug" or "issue". As you can imagine, I feel a little foolish even reporting this, as it must clearly be my error, but I cannot figure this out.

**Comment by svick** [comment]
This is a duplicate of https://github.com/MicrosoftDocs/feedback/issues/3674, where the response was:

> We disabled the Feedback button in some repos where we just couldn't handle the quantity of feedback. However, for the specific page you referenced, you can log an issue directly on GitHub: https://github.com/dotnet/dotnet-api-docs/issues.

**Comment by pbiggar** [comment]
Thanks, I'll follow up there!
