### ISSUE TITLE
How to set compiler options in VS2019.

### ISSUE THREAD

**Issue by Pharsat** [dotnet/docs#29658]
Who is supposed to do this in visual studio 2019? I mean, I need to setup this to a project to be compiled in a pipeline in ADO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc727a99-200d-d34b-a2db-72f336f6f326
* Version Independent ID: fa87a308-62df-2b4c-1685-2ff9372b5c46
* Content: [Compiler Error CS0433](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0433)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0433.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0433.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Pharsat 

I think this would is a better question for our [Q & A](https://docs.microsoft.com/answers/products/dotnet) site. This article describes a compiler error, which would be consistent across all build environments. For that reason, I'm sure how to help.
