### ISSUE TITLE
include command line instructions for tool install

### ISSUE THREAD

**Issue by daz10000** [dotnet/docs#29667]
Would be incredibly helpful to have the actual instructions for installing the tool here.  Apologies if I missed them

```
$ dotnet tool install -g mlnet
You can invoke the tool using the following command: mlnet
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e480b5e-1c4e-be32-0389-fbaa3a0c1378
* Version Independent ID: c8a49f16-d0fd-cdcf-1886-73302ea3ee53
* Content: [Automate model training with the ML.NET CLI - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli)
* Content Source: [docs/machine-learning/automate-training-with-cli.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/automate-training-with-cli.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @daz10000 

Thanks for that suggestion.

cc: @jwood803
