### ISSUE TITLE
Not C# Eroor in Future Bases 

### ISSUE THREAD

**Issue by Mohamad250809** [dotnet/docs#29662]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e69c8f-4fe8-0314-8ecc-946f0e94c5da
* Version Independent ID: e7632aaf-f5d4-62c1-0b81-e65639c617b0
* Content: [Compiler Warning (level 3) CS0642](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0642)
* Content Source: [docs/csharp/misc/cs0642.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0642.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Tiger250809 Did you have more information here? I'm not sure what could be addressed.
