### ISSUE TITLE
AppDomainSetup.ApplicationBase is readonly

### ISSUE THREAD

**Issue by JonathanCrossland** [dotnet/docs#29688]
[Enter feedback here]

AppDomainSetup.ApplicationBase is readonly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6c12f7-0727-ecb8-3d8a-322fb419cb8b
* Version Independent ID: ba1986bf-b966-b7bd-1fbe-4955f760d28b
* Content: [How to: Configure an Application Domain - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-configure-an-application-domain)
* Content Source: [docs/framework/app-domains/how-to-configure-an-application-domain.md](https://github.com/dotnet/docs/blob/main/docs/framework/app-domains/how-to-configure-an-application-domain.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
It's get-only in .NET 6, but [in .NET Framework, it's a read/write property](https://docs.microsoft.com/en-us/dotnet/api/system.appdomainsetup.applicationbase?view=netframework-4.8#system-appdomainsetup-applicationbase). Application domains are only supported in .NET Framework apps.
