### ISSUE TITLE
dotnet test --help output discrepancy with online documentation

### ISSUE THREAD

**Issue by ddprince-yaksa** [dotnet/docs#29680]
Hello, 

We recently found this page to find more about the behavior of "dotnet test" in a whole and were surprised to find there is more detail online than within the help output of the cli itself: 

![image](https://user-images.githubusercontent.com/57116058/171280873-56b3955e-2c88-458f-a7e0-1af2359904ef.png)

Is it intended or the help output is indeed missing details? 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-test.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
It's normal for the web-based documentation to have more detail than the CLI `--help` option. There is much more flexibility in Markdown and HTML for formatting and organizing data.
