### ISSUE TITLE
Request clarification on memory model and thread safety guarantees regarding read/write elimination/introduction

### ISSUE THREAD

**Issue by GeeLaw** [dotnet/docs#29696]
Citing dotnet/runtime#4329 and dotnet/runtime#14746:

> `ImmutableArray<T>` goes to great lengths to be thread-safe by [never dereferencing `this` more than once per public entrypoint](https://github.com/dotnet/corefx/blob/1dc118cc46f88e4889a23190b450d89e565967fd/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray%601.cs#L18-L33) (in dotnet/corefx#200 to fix bug dotnet/runtime#13908). Other `struct`s in the Framework do not take this care (such as `DateTime`, `Nullable<T>`, or `System.Int32`), despite [claiming to be thread-safe in MSDN documentation](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=net-6.0).
>
> The community [has been fascinated](http://stackoverflow.com/questions/30957211/what-advantage-is-there-to-storing-this-in-a-local-variable-in-a-struct-method/30957262) by the pattern in `ImmutableArray<T>` and brought up that it might make sense to spread it around more.

Personally, I also thought about this trick to make "thin" types thread-safe. However, my earlier research indicated otherwise, as explained in these two MSDN magazine articles:

- [The C# Memory Model in Theory and Practice -- MSDN Magazine -- December 2012](https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/december/csharp-the-csharp-memory-model-in-theory-and-practice)
- [The C# Memory Model in Theory and Practice, Part 2 -- MSDN Magazine -- January 2013](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2)

They claim

```csharp
public class ReadIntro {
  private Object _obj = new Object();
  void PrintObj() {
    Object obj = _obj;
    if (obj != null) {
      Console.WriteLine(obj.ToString());
    // May throw a NullReferenceException
    }
  }
  void Uninitialize() {
    _obj = null;
  }
}
```

that in the code above, running `readIntro.PrintObj()` and `readIntro.Uninitialize()` in parallel could result in `NullReferenceException` being thrown due to `readIntro.obj` being set to `null`.

It would be beneficial to know whether the current implementation in [dotnet/runtime](https://github.com/dotnet/runtime) uses "insider knowledge" that the current JIT compiler will not introduce reads for `ImmutableArray<T>` (i.e., the particular implementation is not thread-safe as far as the specification is concerned), or whether the specification has changed to ensure reads are not introduced. Could a documentation clarifying this issue be provided at [docs.microsoft.com](https://docs.microsoft.com/)?

**Comment by gewarren** [comment]
@stephentoub Could you help to answer this question?

> It would be beneficial to know whether the current implementation in [dotnet/runtime](https://github.com/dotnet/runtime) uses "insider knowledge" that the current JIT compiler will not introduce reads for ImmutableArray<T> (i.e., the particular implementation is not thread-safe as far as the specification is concerned), or whether the specification has changed to ensure reads are not introduced.

**Comment by stephentoub** [comment]
> the current JIT compiler will not introduce reads

Correct

https://github.com/dotnet/runtime/issues/63474 tracks more formally documenting .NET's memory model.  A draft of that is available at https://github.com/VSadov/runtime/blob/memModel/docs/design/coreclr/botr/memory-model.md.  And as it states: "Reads cannot be introduced.".

**Comment by gewarren** [comment]
Thanks @stephentoub! Since the documentation is tracked elsewhere, I'm going to close this issue.
