### ISSUE TITLE
Possible typo in terraform example ("test" -> "testrg")

### ISSUE THREAD

**Issue by ranhirem** [dotnet/docs#29702]
Referencing: https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code

In the Terraform example in figure 10-16, instead of naming the azurerm_resource_group "test" it seems like it should be called "testrg" ... in the next HCL block this is referred to as "testrg" (e.g., resource_group_name      = "${azurerm_resource_group.testrg.name}")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09be1939-e2a5-241e-4114-8747b35f3d21
* Version Independent ID: 7d77200d-9764-cabc-d5c1-c4d2ba3c2fd1
* Content: [Infrastructure as code](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code)
* Content Source: [docs/architecture/cloud-native/infrastructure-as-code.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/infrastructure-as-code.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Thanks for pointing it out @ranhirem. We will fix this.
