### ISSUE TITLE
Missing "using"

### ISSUE THREAD

**Issue by fergek** [dotnet/docs#29715]
If you take the first snippet of code, copy and paste, it won't compile. Needs to have added two "using"

```
using System;
using System.Threading.Tasks;
```

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Good catch @fergek, we will add the statements.

**Comment by amolenk** [comment]
Hi,
The sample is for .NET 6. If you follow the instructions closely those using statements shouldn’t be necessary because of the implicit usings feature of .NET 6.

**Comment by erjain** [comment]
Thanks @amolenk for the response, you are right. We can close this issue now.
