### ISSUE TITLE
Inconsistent translation(zh-cn)

### ISSUE THREAD

**Issue by zms9110750** [dotnet/docs#29728]
Local in "local functions" is translated as "本地"
Local in "local variables" is translated as "局部"
I don't know if it has any special meaning (for example, other languages call it this way).
If not, I hope they can unify into one word.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
Ping @kgliang

**Comment by v-alje** [comment]
CEINTL work item 806158 filed to the LOC team on this issue.

**Comment by BillWagner** [comment]
closing as an internal work item has been created
