### ISSUE TITLE
"Extern aliases" part of this page, looks weird

### ISSUE THREAD

**Issue by ali50m** [dotnet/docs#29729]
Please check the "Extern aliases" part of this page, looks weird.

#####################################
Extern aliases
... unchanged ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2564c791-6f6f-24f5-b983-c33a1c4fe9a4
* Version Independent ID: 4696fbfc-65b8-9654-f371-d05a449444f0
* Content: [File scoped namespaces - C# 10.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)
* Content Source: [proposals/csharp-10.0/file-scoped-namespaces.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/file-scoped-namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @ali50m 

Thanks for noting this. I agree it looks a bit different. However, for the purpose of the spec, this was important for reviewers to know that this feature won't affect this area of the standard.

I'm closing this without action.
