### ISSUE TITLE
Improper translation (zh-cn)

### ISSUE THREAD

**Issue by zms9110750** [dotnet/docs#29725]
Constructor is translated to "构造函数".
This word means "constructor function"
For CSharp, it should be translated into "构造方法"(construction method)
Or "构造器" (constructor)
This word appears in many pages and should be modified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a58d4-1905-c664-04b6-fd68e617f8c9
* Version Independent ID: 36d0bf3a-29bf-5162-c700-142b03f9a16c
* Content: [Using Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @khoiph1

**Comment by gewarren** [comment]
Ping @kgliang

**Comment by v-alje** [comment]
CEINTL work item 806160 filed to the LOC team on this issue.
