### ISSUE TITLE
--runtimeconfig option

### ISSUE THREAD

**Issue by pfusik** [dotnet/docs#29727]
> --runtimeconfig
> Path to a runtimeconfig.json file. A runtimeconfig.json file is a configuration file that contains run-time settings. For more information, see [.NET runtime configuration settings](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/#runtimeconfigjson).

Does this command accept a PATH argument? The above syntax doesn't show it. How do I use it? I can't make this command to with with .NET SDK 6.0.5 on Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by pfusik** [comment]
Same with tool help:

	C:\0\ci\git>dotnet -h
	Usage: dotnet [runtime-options] [path-to-application] [arguments]
	(...)
	--runtimeconfig                  Path to <application>.runtimeconfig.json file.

**Comment by tdykstra** [comment]
@baronfel is --runtimeconfig an obsolete option?

**Comment by tdykstra** [comment]
I see it in the code in those links but I can't get it to work (I'm using 6.0.400-preview.22301.10). I get an error message when I try to use it:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet---runtimeconfig does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
It accepts `--roll-forward` but then if I add `--runtimeconfig` after `--roll-forward` I get `... dotnet---roll-forward does not exist.`

**Comment by pfusik** [comment]
I figured out that `--runtimeconfig` does work for the `exec` command, e.g.

    dotnet exec --runtimeconfig foo.runtimeconfig.json foo.dll

**Comment by tdykstra** [comment]
Thanks, @pfusik and @baronfel, I'm updating the documentation in #30000.
