### ISSUE TITLE
Grammatic error in Any method description.

### ISSUE THREAD

**Issue by ashirafumiiro** [dotnet/docs#29730]
The short description for the [Any](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations#any) method is not grammatically correct. It is not easy to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da65be87-16ea-ebcb-e098-6dbf3579152f
* Version Independent ID: 045d5185-5b9c-effc-c542-75192e320d29
* Content: [Quantifier Operations (C#) - LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/quantifier-operations.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/quantifier-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @ashirafumiiro 

I've opened a PR to fix the introduction.

**Comment by ashirafumiiro** [comment]
@BillWagner, I have seen the source md file and the [Contains](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations#contains) method description has the same issue. The text appears to be static and I was hoping that it would require manual editing.

**Comment by GitHubPang** [comment]
@BillWagner The same sentence for Visual Basic is [here](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/quantifier-operations), by the way.
