### ISSUE TITLE
F# Documentation on namespaces and namespace syntax lacks some details

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/docs#2973]
*Originally reported in visualfsharp repo: https://github.com/Microsoft/visualfsharp/issues/3485.*

When I found out that a file can contain multiple namespaces (I have the policy of having one namespace per file) I [looked up the documentation](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/namespaces) and found a few key points missing:

* The syntax does not include the syntax for qualified modules, which can also declare a namespace (though this is explained later on, the subject is namespaces and the syntax should be complete)
* The main syntax bulb should show the full syntax, or show two variants (pre and post 4.1), my preference is to just show the new syntax in full and add a remark that the `rec` keyword is supported from F# 4.1.
* The introduction says that once you have a namespace declaration, the entire file will be in that namespace. This suggests that there can be only namespace declaration per file and raises the wrong assumptions for readers not going through the all sections: it is in fact only until the next namespace declaration (a remark can link to the section on nested namespaces).
* I wouldn't object, or in fact, welcome, a clear enumeration on the syntax peculiarities, right after the intro-line under Remarks, for instance:
    * Namespaces cannot be nested (link to section on nested namespaces)
    * Namespaces can be preceded by comments, but XML doc or simple documentation comments are allowed but ignored
    * Namespaces can be preceded by compiler directives
    * Namespaces can be recursive (link to that section)
    * Namespaces need not be unique, they can span multiple files or even projects
    * A qualified module declaration (i.e., implicit namespace) cannot have other namespace or module declarations at the top-level
    * A nested module cannot have an implicit namespace

I'd be happy to fix this myself (provided there's some consensus here). I'd just need a pointer to where I find this in the source (sorry, it'll be my first commit, a little new to that).

**Comment by abelbraaksma** [comment]
As per the comment by @cartermp over there, I'll try fix this myself by creating a PR for this.

**Comment by cartermp** [comment]
Sounds great @abelbraaksma.  Let me know if you need any help!

**Comment by BillWagner** [comment]
@abelbraaksma Do you still have plans to submit a PR on this? If not, we'll unassign and open it up for others to work on.

**Comment by abelbraaksma** [comment]
@BillWagner, I actually forgot about this. Thanks for the pointer. Yes, I can work on this, in a few weeks I've finished a big project and I should have more time on my hands. Of course, if meanwhile someone else wants to start on it, by all means, don't let me stop you ;).
