### ISSUE TITLE
Sleep(1)

### ISSUE THREAD

**Issue by titos-carrasco** [dotnet/docs#29737]
In Windows 10 a simple loop give me about 15ms for a 1 ms Sleep

```
while(true)
{
    long t1 = DateTimeOffset.Now.ToUnixTimeMilliseconds();
    Thread.Sleep(1);
    long t2 = DateTimeOffset.Now.ToUnixTimeMilliseconds();
    Console.WriteLine( t2 - t1);
}

```

But if I run a Linux VM in VirtualBox and (in parallel ) run again (in Windows 10) the code above,  I got about 1.5ms for 1ms Sleep

Why? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5fac3dd-99c3-b1a9-8719-4a06ee255370
* Version Independent ID: fb91dbeb-ac78-74d3-fd98-f2766bff40cc
* Content: [Pausing and interrupting threads](https://docs.microsoft.com/en-us/dotnet/standard/threading/pausing-and-resuming-threads)
* Content Source: [docs/standard/threading/pausing-and-resuming-threads.md](https://github.com/dotnet/docs/blob/main/docs/standard/threading/pausing-and-resuming-threads.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
First, your measurements are not accurate, it's more correct to use Stopwatch to measure short time intervals, rather then DateTimeOffset.Now. Second, minimum sleep time depends on the system clock resolution, set by [timeBeginPeriod](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) function in Windows. I think it is set by default to not so short interval, so it is expected that you could not sleep for less then 10 ms or so.

**Comment by titos-carrasco** [comment]
I know that, the question is other

If you run the code above you got about 15ms
if you run VirtualBox with ANY VM the code show about 1ms


![image](https://user-images.githubusercontent.com/4842986/172232518-89e7b141-4d4f-48f8-93d1-27bf9aa4b8a1.png)

![image](https://user-images.githubusercontent.com/4842986/172232559-5b0064d5-3fe5-4252-a4e4-36a443883eb6.png)

**Comment by MSDN-WhiteKnight** [comment]
I agree it's odd that virtual machine has higher resolution then host OS, but i guess it's not entirely impossible. Modern virtualization systems use hardware support, that is, the virtual system could interact with hardware interrupts, rather then just being "OS running inside OS". So in theory it could implement higher resolution without affecting host OS. The first step would be to author a proper benchmark using Stopwatch or Benchmark.NET to make sure the observed difference is not due to incorrect time measurement.

**Comment by titos-carrasco** [comment]
The Test.cs file is not running in a VM

Check this video:

https://user-images.githubusercontent.com/4842986/172397872-a8adc964-24f5-4047-b299-1b31e67d60e9.mp4

**Comment by MSDN-WhiteKnight** [comment]
So you meant when VM is running, the sleep timeout on host OS is decreased? This is expected based on what i wrote:

>minimum sleep time depends on the system clock resolution, set by [timeBeginPeriod](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) function in Windows

Probably VirtualBox sets timer interval to 1 ms when VM is running to make sure the virtualized OS can benefit from higher precision in case it needs it. Maybe there's a setting in VM parameters to control it. It is common that various software request higher precision: profilers and becnchmark runners - to improve time measurement, games - to render more frames per second. 

There's one way to confirm this: execute command `powercfg -energy duration 5` from admin cmd when VM is running. It will generate html report, that should mention VirtualBox as "application that requested higher timer precision" or something like that.

**Comment by titos-carrasco** [comment]
Thanks a lot

VBox change the timer interval ....

![image](https://user-images.githubusercontent.com/4842986/172450628-879fe806-31b4-40a5-aa93-1f875b4dbe3d.png)

Do you know how to do it in C# ? 

Im working in a little game engine and need 1ms resolution for a timer while sleeping to complete 1/fps

Saludos

**Comment by MSDN-WhiteKnight** [comment]
You can call timeBeginPeriod as in this example: https://stackoverflow.com/q/69127786/8674428

**Comment by titos-carrasco** [comment]
Muchas gracias, that's all
