### ISSUE TITLE
Replace/remove codeplex links

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2974]
CodePlex is being completely shut down in December. For more info, see https://aka.ms/codeplex-announcement.

We need to replace existing text and links that talk about codeplex:
https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=codeplex&type=

**Comment by doddag** [comment]
Hi Mairaw

I would like to contribute to this issue, and this would be 1st time i'm trying to contribute.

Do you have any advise for me?
Links / Text referring to CodePlex

**Comment by mairaw** [comment]
Hi @doddag, this is great! I see that you already submitted a PR. I'll go through it now and leave you feedback. Thank you so much!

**Comment by isaac2004** [comment]
@mairaw @doddag is this closed?

**Comment by mairaw** [comment]
No, @isaac2004. @doddag took care of a few hits only so this is still up-for-grabs.

**Comment by isaac2004** [comment]
@mairaw so what is worse, CodePlex or MSDN code? Some of this stuff is pretty ancient.

**Comment by mairaw** [comment]
Yes, we have ancient things everywhere. It's a lot of legacy content.

Here's what I would do since CodePlex is shutting down now. For projects that have a new destination on GitHub, I'd change the topics to point to the new destination. For others not moving to GitHub, we could keep linking to them and see what happens when archive comes up in December. 

For code, if we need to review that, I'd open a separate issue. This one is just to deal with CodePlex shutting down.

**Comment by ItsPugle** [comment]
Hey @mairaw,

Getting a lot of questions on this one! Got another one for you though: Is this still open, or is their someone actively working on this? I'm looking for a little documentation project so yeah :)

If you don't have an active contributor on this, do you want the links completely removed, or updated to a respective GitHub etc link?

**Comment by isaac2004** [comment]
@ItsPugle I have been working on this one, but could use the help!

**Comment by ItsPugle** [comment]
@isaac2004 - Sure! I've got lots of free time right now, so I can probably do quite a few. I'll get started on them as per https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=codeplex&type=

**Comment by ItsPugle** [comment]
I've gotten clogged up with some other stuff right now, so I can't help with this right right now, but I have faith that @isaac2004 can do it.

**Comment by isaac2004** [comment]
@ItsPugle I actually have a PR for it :)

**Comment by ItsPugle** [comment]
Oh lol @isaac2004! Good work 👍
