### ISSUE TITLE
Package name for consul is not updated with documentation

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/docs#29761]
Hi,

The reference to Orleans support for Consul, in the section [Microsoft Orleans Consul Utilities](https://docs.microsoft.com/en-us/dotnet/orleans/resources/nuget-packages#microsoft-orleans-consul-utilities), is not updated to the more recent package [Microsoft.Orleans.Clustering.Consul](https://www.nuget.org/packages/Microsoft.Orleans.Clustering.Consul/4.0.0-preview1)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c74d870-b916-db65-ebcb-9aa5192637be
* Version Independent ID: 6dbeba49-c940-ef67-ef98-ccbd7c0b958f
* Content: [Orleans NuGet packages](https://docs.microsoft.com/en-us/dotnet/orleans/resources/nuget-packages)
* Content Source: [docs/orleans/resources/nuget-packages.md](https://github.com/dotnet/docs/blob/main/docs/orleans/resources/nuget-packages.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Thank you for posting this issue @jan-johansson-mr, however; the package you referenced is still in preview. We try to only document stable versions, so as soon as version 4.0 of Orleans ships we will update this. I'm going to close this though for now, thanks again.
