### ISSUE TITLE
c# example in Visual Basic ?!

### ISSUE THREAD

**Issue by georgekeeling** [dotnet/docs#29774]
I have just followed this 'tutorial'. It's for C# not Visual Basic. Why is it here? No answer required thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET console application using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio?pivots=dotnet-6-0)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment]
There is a language selector at the top of the page where you can choose either C# or VB:

![image](https://user-images.githubusercontent.com/31348972/172843653-d94f5caa-29e0-44d9-9ff6-1a2dcb3d24be.png)

**Comment by georgekeeling** [comment]
Thanks
