### ISSUE TITLE
the quick brown fox 'jumps' not 'jumped'

### ISSUE THREAD

**Issue by pm100** [dotnet/docs#29793]
The classic all letters sentence is "the quick brown fox jumps over the lazy dog"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6f7384-2a77-a8f2-63dc-c1b545aba2a9
* Version Independent ID: eec3706d-1448-9f80-a520-2989b59c1093
* Content: [Explore ranges of data using indices and ranges](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/ranges-indexes)
* Content Source: [docs/csharp/whats-new/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by 20jasper** [comment]
Hey can I take this issue?

**Comment by BillWagner** [comment]
@20jasper 

> Hey can I take this issue?

Yes, please. I'll watch for a PR.
