### ISSUE TITLE
ERROR CODE CS1061

### ISSUE THREAD

**Issue by lelexander1** [dotnet/docs#29803]
I have the following error when creating a scaffold in my controllers -> MVC Controller with views using entity framework .

Additionally, the entity.frameworkCore.sqlserver changes to a more current version

Error CS1061 "KeyBuilder" does not contain a definition for "ForSqlServerIsClustered" or an accessible extension method "ForSqlServerIsClustered" that accepts a first argument of type "KeyBuilder" (are you missing a using directive or an assembly reference?) Models\NorthwindContext.cs

**Comment by BillWagner** [comment]
Hi @lelexander1 

These kinds of questions are best asked on our [Q & A site](https://docs.microsoft.com/answers/products/dotnet). The error you're receiving indicates that there's no matching method. The Q & A site will help you figure out why.
