### ISSUE TITLE
Runtime Callable Wrapper - link to same page

### ISSUE THREAD

**Issue by wf1-ddz** [dotnet/docs#29800]
There is a link just under the header "Marshalling selected interfaces" to "runtime callable wrapper" which points to the page you are already on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e12a8d-3503-db34-df9a-84ef6037e86d
* Version Independent ID: 964eee24-e711-8c41-b145-35948c20e774
* Content: [Runtime Callable Wrapper](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/runtime-callable-wrapper)
* Content Source: [docs/standard/native-interop/runtime-callable-wrapper.md](https://github.com/dotnet/docs/blob/main/docs/standard/native-interop/runtime-callable-wrapper.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by 20jasper** [comment]
Can I take this issue?

**Comment by gewarren** [comment]
> Can I take this issue?

Yes please go ahead if you are still interested!

**Comment by IEvangelist** [comment]
Yes, @agriffard - that makes sense to me. Thank you
