### ISSUE TITLE
missing dependencies for ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by viceice** [dotnet/docs#29819]
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies

The dependencies section is missing the required packages information for ubuntu 22.04 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @viceice there is a [dependencies section](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies) at the bottom of the article.

This information applies to all releases.

I'll close this issue as I believe it's resolved. Let me know if you think otherwise!

**Comment by viceice** [comment]
I know, but there are missing the packages for ubuntu 22.04. `libicu70` and `libssl3` are there required
