### ISSUE TITLE
can't find Worker Service template

### ISSUE THREAD

**Issue by koyuyesil** [dotnet/docs#29816]
i cant see project template
https://stackoverflow.com/questions/70460404/visual-studio-2022-worker-service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae847f16-ff74-ab68-7163-f713b447430c
* Version Independent ID: ff379d26-0d85-6d74-67da-4a3cd260b04d
* Content: [Worker Services in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers)
* Content Source: [docs/core/extensions/workers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/workers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Rick-Anderson** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/3605364/173724138-7ba03445-12d5-4c4b-83ac-6597264d02fc.png">

**Comment by koyuyesil** [comment]
worker service can complie without install aspnet workload. problem solved after install. now i can start new projects. thank you mr @Rick-Anderson
