### ISSUE TITLE
String.Split documentation

### ISSUE THREAD

**Issue by SteveWTF** [dotnet/docs#29825]
[Enter feedback here]
I wanted to know if the string array returned started at index 0 or 1. I assume it starts at 0 which is where all arrays in C# start but it would be nice if the documentation mentioned that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d35e73a-4e90-8bb8-6c66-18080c1733f7
* Version Independent ID: 018e2427-b1f2-9459-5e40-056bc706251d
* Content: [Divide strings using String.Split (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/parse-strings-using-split)
* Content Source: [docs/csharp/how-to/parse-strings-using-split.md](https://github.com/dotnet/docs/blob/main/docs/csharp/how-to/parse-strings-using-split.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 226915](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226915)

**Comment by GeeLaw** [comment]
This information is already encoded in the type information --- `T[]` means single-dimensional zero-based array of `T`. Arrays that are single-dimensional but not zero-based do not have speakable names in C#.
