### ISSUE TITLE
Improve string concatenation example

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet/docs#29822]
Per comments in the PR, adding this as a follow-up to #29785, which was merged to fix #29440.

While we've improved the string interpolation example, there were follow-up suggestions from @gewarren and @BillWagner which I'm capturing here.

On https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md:

* Utilize something more complex than Hello World to have a reason for there not to be one interpolated string.
* Perhaps include the preferred choice of single string interpolation to show an alternative 
* Language update to: 

> To combine multiple interpolated strings, add the `$` special character to each string literal.

[Edited to add doc details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @SeanKilleen 

I added the "up for grabs" label here. Did you want to submit PR? If so, I'll assign this to you.

**Comment by gewarren** [comment]
@mjh316 That is the million dollar question. I'm starting to think we should just remove the section on concatenating two interpolated strings since it doesn't seem to be very useful and the example might only lead to confusion.

**Comment by BillWagner** [comment]
> Interested on working on this, but any ideas on what reasons there could be not to have a single interpolated string? An initial thought was that perhaps in the case of adjacent expressions that would be clearer when separated, but I'm unable to think of such one.

When I was thinking this through, the only scenarios that came to me were calling multiple methods to compose different parts of the string. I like @gewarren 's suggestion for the fix:

> I'm starting to think we should just remove the section on concatenating two interpolated strings since it doesn't seem to be very useful and the example might only lead to confusion.

**Comment by gewarren** [comment]
I don't think this aspect needs an entire section as it has currently. How about we just add a sentence somewhere that states that if you concatenate two or more interpolated strings, each one must be prefixed with `$`?

Alternatively, sometimes we answer questions raised in issues just in the issue itself - without updating the doc. Which I think would also be acceptable in the case of #29440.
