### ISSUE TITLE
Declared value adds confusion

### ISSUE THREAD

**Issue by alexcrowdpharm** [dotnet/docs#29821]
The declared value in the example "This is not the null string" adds unnecessary confusion to the example. Recommend changing it to something simpler.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46225236-316d-bf2c-add4-6cea9b579ddc
* Version Independent ID: 528c02d9-3551-c7df-817e-ea50b2760f51
* Content: [Pattern matching overview - C# guide](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching)
* Content Source: [docs/csharp/fundamentals/functional/pattern-matching.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 229886](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229886)

**Comment by BillWagner** [comment]
Thanks for the feedback @alexcrowdpharm I'll keep this open to see if others agree.
