### ISSUE TITLE
Logging in .NET: Sample require Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#29839]
Google took me to [Create logs in Main](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#create-logs-in-main). I copy/pasted code into a console app and had lots of compile errors. I used edit in browser to navigate to the snippet so I could see what SDK was used, but this is an embedded snippet.

I think you should mention that `<Project Sdk="Microsoft.NET.Sdk.Web">` is required for many of these samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346bbcf3-9f8e-b253-09fe-906195392783
* Version Independent ID: 0e787ac2-1108-1d94-d62f-ccffa93e06c3
* Content: [Logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#create-logs-in-main)
* Content Source: [docs/core/extensions/logging.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by DimBor615** [comment]
This it's my own Personal Computer, not any Public  Microsoft servers
How do find the solution  to connect in Project
 Dimitry

**Comment by DimBor615** [comment]
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Globalization;
using DBFLoggIng;

namespace DBFLoggIng
{                   
    public partial class DBFLoggIngForm : Form
    {
        string ConString = (@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename="C:\Users\Dimitry\Documents\Log In.mdf";Integrated Security=True;Connect Timeout=30);

        SqlConnection Con;
        SqlCommand cmd = new SqlCommand();
        SqlDataReader Reader = null;  

        public DBFLoggIngForm()
        {
            InitializeComponent();
            SqlConnection Con;
            textBoxPassword.PasswordChar = '*';
            textBoxPassword.MaxLength = 15;
        }
        private void BtnSign_In_Click(object sender, EventArgs e)
        {
            try  
            {
           DBFLoggIng.Global.Disconnect();
           SqlConnection Con = new SqlConnection(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Dimitry\Documents\DBFLoggIng.mdf;Integrated Security=True;Connect Timeout=30");
           DBFLoggIng.Global.GUID = "c3b7a10b-4c47-4ffe-ad2f-90299da488e2";
           string Query = ("INSERT INTO [dbo].[DBFLoggIng] ([User Name],[Password]) VALUES (User_Name = '" + textBoxUser_Name.Text + "' Password = '" + textBoxPassword.Text + Con + "'");
      //   DBFLoggIng.Global.Connect("[dbo].[DBFLoggIng]", textBoxUser_Name + Text, textBoxPassword + Text, false);
           Con.Open();
           SqlCommand cmd = new SqlCommand(Query,Con);
           cmd.CommandText = Query.ToString();
           cmd.ExecuteNonQuery();
            if (Reader.Read())

            {
             this.Hide();
             DimBorFutures.MainForm dbf_f = new DimBorFutures.MainForm();
             dbf_f.ShowDialog();
             BringToFront();
            }
             MessageBox.Show("Invalid,User_Name or Password ");
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error during Connection : " + ex.Message);
                return;
            }
            Close();
        }
        private void BtnSign_Out_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}

**Comment by DimBor615** [comment]
You can see this it's Personal  Computer Why I can not Log In to My own Project

Any answers are welcome
 Dimitry
