### ISSUE TITLE
Document System.​Text.​Unicode Namespace

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#2983]
This includes the following files:

https://github.com/dotnet/docs/blob/master/xml/ns-System.Text.Unicode.xml 
https://github.com/dotnet/docs/blob/master/xml/System.Text.Unicode/UnicodeRange.xml
https://github.com/dotnet/docs/blob/master/xml/System.Text.Unicode/UnicodeRanges.xml

**Comment by karelz** [comment]
@krwq @tarekgh would you be the right owners? It seems related to `System.Text.Encoding`.

**Comment by karelz** [comment]
It seems to be new API in .NET Core 1.0. Not present on Desktop at all.
https://apisof.net/catalog/System.Text.Unicode

**Comment by tarekgh** [comment]
These are part of the library System.Text.Encodings.Web.dll. 

@KrzysztofCwalina why we chose the System.​Text.​Unicode namespace? is it because more generic types defined there?

**Comment by tarekgh** [comment]
@karelz what is the ask here? I think the issue is just tracking documenting these types. but in general @krwq and myself are the owners now :-) of course @KrzysztofCwalina can help with questions too.

**Comment by karelz** [comment]
The ask is to create documentation for the namespace -- currently we have none. @mairaw and her team can help to polish it, but they need content to start with from area experts (us) :).
Makes sense?

**Comment by karelz** [comment]
cc @danmosemsft

**Comment by tarekgh** [comment]
@mairaw let's know who is going to work on this issue from your side and we can arrange to give all needed information about this topic.

**Comment by mairaw** [comment]
@rpetrusha you usually own things under System.Text. Can you work with @tarekgh on this one?
