### ISSUE TITLE
the reported warning is not the correct one in the sample code for suppressing it

### ISSUE THREAD

**Issue by AngeloCresta** [dotnet/docs#29833]
it has to be SYSLIB0041 and not SYSLIB0001 as reported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd4ebc39-a1e1-ea04-97a9-e2e7d65b2477
* Version Independent ID: 2466dc04-ee40-d8af-0b31-7e78663a0205
* Content: [SYSLIB0041 warning - Rfc2898DeriveBytes constructors with default hash algorithm and iteration counts are obsolete - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0041)
* Content Source: [docs/fundamentals/syslib-diagnostics/syslib0041.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/syslib0041.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I'm actually going to reopen this and add ID-specific suppression text to each reference page. Thanks for letting us know this is confusing.
