### ISSUE TITLE
finalizers  on .Net Core

### ISSUE THREAD

**Issue by robertok77** [dotnet/docs#29844]
```
- .NET Framework: The output shows that the finalizers for the three classes are called automatically when the application terminates, in order from the most-derived to the least-derived.
- .NET 5 (including .NET Core) or a later version: There's no output, because this implementation of .NET doesn't call finalizers when the application terminates.

```

Basically, you can check by yourself and see that both .net framework and .net core returns the same result from finalizers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96eaef8-dcc9-4659-3f4e-be5a1c4c6b50
* Version Independent ID: d3da7981-542d-e906-5988-b80e403fa651
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/finalizers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/finalizers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/finalizers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @robertok77 

I'm not sure what you're asking in this issue. See dotnet/runtime#65845 and dotnet/runtime#9328 for more details on how the behavior is different on framework and core. 

This article is correct in describing what the language and runtime guarantees on Framework and .NET Core, and how they are different.

**Comment by robertok77** [comment]
Hi @BillWagner 

I run the code from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/finalizers
on rapid tool - LinqPad .Net 6. That is why I got the strange response from finalizers I wrote you. 
However on pure console app .net 6 the behaviour is according to documentation. 
I send info about explanation to Joseph Albahari.
