### ISSUE TITLE
Wording and timing. 

### ISSUE THREAD

**Issue by Dverp** [dotnet/docs#29888]
Great writing overall...  there is one sentence that might be misinterpreted. 
This opening sentence for explaining ARM... 
"ARM is an API provisioning engine that is built into Azure and exposed as an API service."
...reads as saying that ARM is an Azure feature for provisioning APIs and an API itself.   I suggest waiting at least a paragraph or two to mention API.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09be1939-e2a5-241e-4114-8747b35f3d21
* Version Independent ID: 7d77200d-9764-cabc-d5c1-c4d2ba3c2fd1
* Content: [Infrastructure as code](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/infrastructure-as-code)
* Content Source: [docs/architecture/cloud-native/infrastructure-as-code.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/infrastructure-as-code.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @Dverp, thanks for posting your query.  We highly encourage you if you want to propose the changes, we are happy to review and accept a PR on this.
