### ISSUE TITLE
Dotnet installer doesn't produce a usable `dotnet` CLI

### ISSUE THREAD

**Issue by connor4312** [dotnet/docs#29884]
My flow was this:

1. Install the C# extension for VS Code
2. See the prompt to download the .NET 6 installer. Download it, run it, reload VS Code
3. See the prompt again and notice there's no `dotnet` command on my CLI
4. Google and eventually find that I need to manually symbolically link dotnet into my PATH https://stackoverflow.com/a/56291338

This is a pretty poor experience. Nowhere on the page does it say I need to do this step when using the installer; when doing that I would expect everything to be set up for me. If this is not the case, it should be documented. The docs don't it even mention the `/usr/local/share/dotnet` path except in the section on ARM-based macs, which is not anything I care about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e
* Version Independent ID: 68d524f7-6cf1-2caa-56d5-f243952d1526
* Content: [Install .NET on macOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/macos)
* Content Source: [docs/core/install/macos.md](https://github.com/dotnet/docs/blob/main/docs/core/install/macos.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by connor4312** [comment]
Actually, it doesn't look like that dotnet binary is the SDK version. So I have no idea where the right binary is.

**Comment by dagood** [comment]
The reason this step isn't mentioned is that it shouldn't be necessary. Most likely, something about your system is making the built-in macOS utility `path_helper` not work in your terminal. See here for more details:

* https://github.com/dotnet/runtime/issues/3603
  * Tracks removing .NET's dependency on `path_helper`, because even though it's a built-in macOS utility, it's broken on a lot of people's systems.

**Comment by adegeo** [comment]
Considering this is the first time this has been reported to the docs, it must not be that widespread. I'll close this for now unless we determine that this is a high enough priority to work on. It seems that .NET 7 is going to move away from `path_help` I think...
