### ISSUE TITLE
"How to customize character encoding with System.Text.Json" has incorrect information about characters that are always escaped.

### ISSUE THREAD

**Issue by paleocomburo** [dotnet/docs#29892]
The paragraph "Encoder-specific block lists" says:

> Examples of encoder-specific blocked code points include '<' and '&' for the [HTML encoder](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.htmlencoder), '\\' for the [JSON encoder](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.javascriptencoder), and '%' for the [URL encoder](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.urlencoder). For example, the HTML encoder always escapes ampersands ('&'), even though the ampersand is in the BasicLatin range and all the encoders are initialized with BasicLatin by default.

But when I encode a string, using the JavaScriptEncoder, containing an ampersand (&), it also gets encoded. Suggesting that the Javascript encoder does more enconding than just the '\\' that is mentioned in the documentation above.

For example with this test program:
```
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Unicode;

namespace JsonEncoding
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var o = new LogObject { Value = "?param1=value1&param2=value2" };
            var jsonSerializerOptions = new JsonSerializerOptions
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                Encoder = JavaScriptEncoder.Create(UnicodeRanges.BasicLatin)
            };

            var message = JsonSerializer.Serialize(o, jsonSerializerOptions);
            Console.WriteLine(message);
        }
    }

    internal class LogObject
    {
        public string? Value { get; set; }
    }
}
```

I get the output:

> { "Value":"?param1=value1\u0026param2=value2"}

But since I'm using the JavaScriptEncoder, I would expect it only to escape a '\\' character as the documentation says, and not the ampersand (&) as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfcc376-0c18-5aab-f6b8-b2c6ef282acc
* Version Independent ID: 79bcd93d-81f8-5f02-3958-d364606265cd
* Content: [How to customize character encoding with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding)
* Content Source: [docs/standard/serialization/system-text-json-character-encoding.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-character-encoding.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
That text only offers "Examples of encoder-specific blocked code points", not a comprehensive list for each encoder. We don't publish a comprehensive list of blocked code points here because the blocked code points can change without notice.
