### ISSUE TITLE
it does not work on windows based containers

### ISSUE THREAD

**Issue by rifaterdemsahin** [dotnet/docs#29890]
it gets stuck
![image](https://user-images.githubusercontent.com/5270036/174031280-4f8297ea-d38d-4d58-8472-18dd6923f31c.png)

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
LABEL Description="IIS" Vendor="Microsoft" Version="10"
RUN powershell -Command Add-WindowsFeature Web-Server
CMD [ "ping", "localhost", "-t" ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5154fa29-1cf7-a744-83b8-f4798e2b3a0e
* Version Independent ID: c6781eb9-a9f8-7fbb-838d-e9f654a5cfdf
* Content: [Using Windows PowerShell commands in a DockerFile to set up Windows Containers (Docker standard based)](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @rifaterdemsahin, thanks for posting your query. I noticed that there is some issue with STEP 3 onwards, I tried replacing the commands with the below code line in dockerfile, which worked for me:

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
LABEL Description="IIS" Vendor="Microsoft" Version="10"
RUN powershell Get-WindowsFeature web-server
RUN powershell Install-windowsfeature web-server
RUN powershell add-windowsfeature web-asp-net45
```

Let me know if this works for you.
