### ISSUE TITLE
missing class in example

### ISSUE THREAD

**Issue by waanito** [dotnet/docs#29896]
[Enter feedback here] in the 3rd example
using StreamWriter file = new("WriteLines2.txt");

it should read
using StreamWriter file = new StreamWriter ("WriteLines2.txt");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fbd113-dbad-8aef-4e74-151b0b7189ff
* Version Independent ID: 1e02473f-562b-aa40-756e-1c147cf41041
* Content: [How to write to a text file - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-write-to-a-text-file)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi :wave: @waanito 

That samples is using the [target type new](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new) feature added in C# 9.

It's valid C#. I'll close this as by-design.
