### ISSUE TITLE
Missing CS0542 error in code sample

### ISSUE THREAD

**Issue by GitHubPang** [dotnet/docs#29899]
The last code sample in this page suggests that there would be a compiler error, but in reality, there's none (tested with .NET 6.0).
On the contrary, the error would appear if the class is named `get_Item`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4ba449-72fa-97ba-9816-e3e41af3f87e
* Version Independent ID: c8a4a2c4-7398-93c7-d171-4ddd5ddebccb
* Content: [Compiler Error CS0542](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0542)
* Content Source: [docs/csharp/misc/cs0542.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0542.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @GitHubPang 

I've opened a PR to remove that sample.
