### ISSUE TITLE
Introduction is written as if this should still happen.

### ISSUE THREAD

**Issue by racouster** [dotnet/docs#29902]
Introduction is written as if this should still happen. Obviously C#8 is old, but should it read like this is still to be implemented? Is it a historical document? The date on the page is this year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35ed60bc-02a4-34e4-a862-7a52158b51e2
* Version Independent ID: f39f3614-6433-be6f-3082-a2313f9a91ae
* Content: [Async streams - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/async-streams)
* Content Source: [proposals/csharp-8.0/async-streams.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-streams.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @racouster 

These are historical documents. We publish the feature specs while the ECMA committee works on updating the official C# standard.

That does cause some confusion while the committee catches up.

I'll close this as by-design.
