### ISSUE TITLE
Facing ErrorCS8983	A 'struct' with field initializers must include an explicitly declared constructor

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#29930]
Hi,
The following code was working fine in C#10:
```
Console.WriteLine("\n---3.P16---");
struct Codes
{
    // The following was allowed earlier in C# 10
    int _error1 = 1; 
}
```
But once I have updated to VS Version 17.2.3, I am getting errors:
Error	CS8983	A 'struct' with field initializers must include an explicitly declared constructor

Additional note:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct says that
"Beginning with C# 11, if you don't initialize all fields in a struct, the compiler adds code to the constructor that initializes those fields to the default value."
But the following code (Tested with C#7 in Visual Studio 17.2.3. And also with Visual Studio Preview.( Version 17.3.0 Preview 1.1)):
```
Console.WriteLine("\n---3.P21---");
//Point point1 = new Point();
Point point1 = new();
Console.WriteLine($"Point_1: {point1}");
struct Point
{
    int _xCoordinate = 1;
    int _yCoordinate;

    //public Point()
    //{
    //    _yCoordinate = 2;
    //}
    public override string ToString() => "(" + _xCoordinate + "," + _yCoordinate + ")";

}
```
produces the same error:
CS8983	A 'struct' with field initializers must include an explicitly declared constructor.

My understanding is that since the auto-default struct feature is available in Visual Studio 2022 version 17.3, this code should work in the preview version.
Have I missed any basic thing? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
This is a breaking change documented [here](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207#6)

**Comment by Vaskaran** [comment]
Thank you.
