### ISSUE TITLE
Escaped asterisks are not rendered correctly from Markdown

### ISSUE THREAD

**Issue by ddrinka** [dotnet/docs#2993]
Consider this documentation section which uses a number of asterisks: https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions

The author has attempted to escape some of them with backslashes (while some where left mistakenly unescaped).  Github renders these correctly, but the docs renderer does not.

**Comment by mairaw** [comment]
@kraigb can you look at this? It's probably due to GitHub using CommonMark spec and OPS not yet.
Should we move this to https://github.com/NuGet/docs.microsoft.com-nuget?

**Comment by kraigb** [comment]
Yes, move this to the issues on the NuGet docs repo.

**Comment by mairaw** [comment]
Done. Closing this one.
