### ISSUE TITLE
very good an powerful tools from Microsoft to debug trace and monitoring the distributed apps. thanks Microsoft

### ISSUE THREAD

**Issue by Ahmed1511** [dotnet/docs#29947]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1696b3d8-50cc-f8a6-0373-9361660d6b8c
* Version Independent ID: 643aea84-41c2-d700-8177-3380fb932e6a
* Content: [Diagnostics tools overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/)
* Content Source: [docs/core/diagnostics/index.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by gewarren** [comment]
Thank you @Ahmed1511!
