### ISSUE TITLE
Not all code discussed is provided

### ISSUE THREAD

**Issue by allyn-psyonix** [dotnet/docs#29954]
The documentation discusses a number of code blocks, some of which reference other code that is not described anywhere. I was unable to find it in the sample code referenced by the docs as well.

For example, `AddPolicyHandler` seems to be a critical method for the example but it is not explained anywhere on this page, nor does it exist at all in the example project.

I think these pages are really out of sync with the example project and should do a better job of explaining all relevant pieces on the page itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef44bb71-2ee5-bf25-bcd2-1f1eee8b2806
* Version Independent ID: 2c497f8a-2576-2c8e-8ebc-a9f8146c3630
* Content: [Implementing the Circuit Breaker pattern](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @allyn-psyonix, thanks for sharing the feedback. `AddPolicyHandler` extension method is called twice in `AddApplicationServices` method, method calls are chained to the `AddHttpMessageHandler` method call for the coupon service. For more information on resiliency, please refer to https://docs.microsoft.com/en-us/learn/modules/microservices-resiliency-aspnet-core/5-implement-polly-resiliency. Let me know if this helps you.

**Comment by erjain** [comment]
Hi @allyn-psyonix, it will be great if you can mention other sections also that you think they are outdated. We are working on the above-mentioned feedback to update the document with more information.

**Comment by erjain** [comment]
The issue can be closed now.
