### ISSUE TITLE
The "Standard numeric format strings" doc is out of date

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#29951]
From this conversation: https://github.com/dotnet/runtime/pull/71038#discussion_r902894078

This documentation is out of date: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#general-format-specifier-g  

Here's the doc:
https://github.com/dotnet/docs/blob/main/docs/standard/base-types/standard-numeric-format-strings.md

@tannergooding knows the correct values returned by the formatting options.

**Comment by eerhardt** [comment]
Closing in favor of https://github.com/dotnet/docs/issues/29952.
