### ISSUE TITLE
General format specifier (G) is incorrect for .NET 6

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs#29952]
The table on this page says:

> If the precision specifier is omitted or zero, the type of the number determines the default precision, as indicated in the following table.
...
> Single | 7 digits
> Double | 15 digits

But when I run the following code on .NET 6, I'm seeing 9 digits for Single and 17 digits for Double:

```C#
float f = 123456789f;
f.ToString("G")
```
prints
```
123456790
```

and

```C#
double d = 12345678912345678;
d.ToString("G")
```
prints
```
12345678912345678
```

cc @tannergooding 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#general-format-specifier-g)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by tannergooding** [comment]
This was changed back in .NET Core 3.0: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.0#floating-point-formatting-and-parsing-behavior-changed

etc

There's just a "lot" of documentation for formatting/parsing that is disconnected from the respective types or other primary pages and this is likely a place that was missed.
