### ISSUE TITLE
ComWrappers tutorial: `DemoNativeDynamicWrapper` class is not implemented.

### ISSUE THREAD

**Issue by obiwanjacobi** [dotnet/docs#29969]
Because the `DemoNativeDynamicWrapper` class is not implemented, the next code example does not make any sense. That code shows an interface's default implementation casting the `this` reference to the `DemoNativeDynamicWrapper` class and accessing a property member on that class instance. 

The sample would be clearer (and correct) if the `DemoNativeDynamicWrapper` class implementation would show these details.

https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers#dynamic-native-object-wrapper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1316676-9418-3418-d9fb-4114ff178700
* Version Independent ID: 50d9ac5f-ea31-0663-2ab4-993cd0d39ec0
* Content: [Using the ComWrappers API](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers)
* Content Source: [docs/standard/native-interop/tutorial-comwrappers.md](https://github.com/dotnet/docs/blob/main/docs/standard/native-interop/tutorial-comwrappers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @AaronRobinsonMSFT
* Microsoft Alias: **jekoritz**

**Comment by AaronRobinsonMSFT** [comment]
> All source code used in this tutorial is available in the [dotnet/samples repository](https://github.com/dotnet/samples/tree/main/core/interop/comwrappers/Tutorial).

This is implemented in the complete sample mentioned at the top of the tutorial.

See https://github.com/dotnet/samples/blob/bd069b00398865f1f639007932ea1ddaa1cd461c/core/interop/comwrappers/Tutorial/Program.cs#L386.
