### ISSUE TITLE
UWP support is .NET Native not framework

### ISSUE THREAD

**Issue by AdamBraden** [dotnet/docs#29965]
The assistant recently added support for migrating UWP apps. The details state:

.NET Framework UWP apps

however this is incorrect. UWP support is .NET Native, so it should say:

.NET Native UWP apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf49988-a3ca-a140-76f7-e5aff6ffb309
* Version Independent ID: bf952cc5-836b-90c5-5f80-83baa3b796dd
* Content: [Overview of the .NET Upgrade Assistant - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview)
* Content Source: [docs/core/porting/upgrade-assistant-overview.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

**Comment by bgursahani** [comment]
Please edit this ".NET Framework UWP apps" to ".NET Native UWP apps"
