### ISSUE TITLE
Possible resource leak when both IDisposable and IAsyncDisposable are implemented

### ISSUE THREAD

**Issue by fire-birdie** [dotnet/docs#29961]
If the type in the [Implement both dispose and async dispose patterns](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-both-dispose-and-async-dispose-patterns) example is disposed synchronously, and the type stored in `_asyncDisposableResource` doesn't implement `IDisposable`, it won't be disposed at all. Short of doing some horrible sync-over-async hack, I don't know how to work around this, which leads me to the conclusion that all types that implement `IAsyncDisposable` should also implement `IDisposable` or they risk putting their consumers in a very awkward situation. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Let's ask @bartonjs — he's usually the one I go to for questions like this.

**Comment by BillWagner** [comment]
@IEvangelist Let's work together on this. I bet that some of the tutorials I wrote for async streams don't implement both `IDisposable` and `IAsyncDisposable`.

**Comment by fire-birdie** [comment]
> > which leads me to the conclusion that all types that implement IAsyncDisposable should also implement IDisposable or they risk putting their consumers in a very awkward situation. Am I missing something?
> 
> You are correct. An average IAsyncDisposable type should also be IDisposable. Sealed types that have no notion of synchronous disposal are one major exception, and while guidelines don't support it "well, I don't wanna" is the next biggest exception.

Unfortunately, "I can't because one of the types I use doesn't" seems like it's going to be a big problem, made significantly worse by the two exceptions you've mentioned; the more types that make it into the wild without implementing both, the more we'll see further down the road. Much like async/await and `IDisposable` itself, this is very much a viral design choice.

IMHO, the documentation should strongly discourage implementing `IAsyncDisposable` without `IDisposable` unless there are extenuating circumstances. Given the opportunity, I'd go so far as to make `IAsyncDisposable` inherit from `IDisposable`, but I realise it's far too late for that.
