### ISSUE TITLE
Provide definition of "positional parameter" and "positional property".

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/docs#29977]
This page really needs a link to, or a section on, defining what is meant by "positional parameter" and "positional property".  These concepts seem to be introduced here with no context or explanation other than what can be derived through examination of the examples associated with the occurrences of these terms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(record_CSharpKeyword)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Loophole62ndFF 

I overlooked that. I thought I had provided those definitions. I've added this to the next sprint.
