### ISSUE TITLE
Must update "What's new in accessibility in .NET Framework" for .NET Framework 4.8.1

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/docs#29985]
WinForms made a lot of changes in 4.8.1 to support accessibility. WPF also made changes to the default interactions of Tooltips. I will have teams give me the descriptions of their changes in .md format. That effort is now in progress.

~Merrie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642b7f23-cc05-b8cb-5ec1-862fa6e62b8c
* Version Independent ID: 0d7236b7-8c64-7eb0-69c8-101c738f275a
* Content: [What's new in accessibility in .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility)
* Content Source: [docs/framework/whats-new/whats-new-in-accessibility.md](https://github.com/dotnet/docs/blob/main/docs/framework/whats-new/whats-new-in-accessibility.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Hi Merrie @merriemcgaw. Any update on the .md files you can provide to help with this issue?

**Comment by merriemcgaw** [comment]
Working on those this week and next. Waiting for WPF content too, but I should have it soon.

**Comment by merriemcgaw** [comment]
Note that I don't think we want to publish anything new until we ship the 4.8.1 GA installer on the download center. I am not certain when that will be. This fall I'd assume.
