### ISSUE TITLE
Code sample has incorrect settings

### ISSUE THREAD

**Issue by MongoCaleb** [dotnet/docs#29984]
Test1 sets Test3Called to true and Test3 sets Test1Called to true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17b1fbc-2e79-c453-ef83-2ffff1683d5c
* Version Independent ID: b82fafa9-47c1-1c5a-93a3-669782e915eb
* Content: [Order unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests)
* Content Source: [docs/core/testing/order-unit-tests.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/order-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Thank you for posting this issue @MongoCaleb, please see #30013
