### ISSUE TITLE
dotnet tool install --prerelease option is not documented

### ISSUE THREAD

**Issue by rnwood** [dotnet/docs#29992]
Here's the output for `dotnet tool install -h` for SDK version 6.0.300.

```
Description:
  Install global or local tool. Local tools are added to manifest and restored.

Usage:
  dotnet tool install [<PACKAGE_ID>] [options]

Arguments:
  <PACKAGE_ID>  The NuGet Package Id of the tool to install.

Options:
  -g, --global             Install the tool for the current user.
  --local                  Install the tool and add to the local tool manifest (default).
  --tool-path <PATH>       The directory where the tool will be installed. The directory will be created if it does not 
                           exist.
  --version <VERSION>      The version of the tool package to install.
  --configfile <FILE>      The NuGet configuration file to use.
  --tool-manifest <PATH>   Path to the manifest file.
  --add-source <SOURCE>    Add an additional NuGet package source to use during installation.
  --framework <FRAMEWORK>  The target framework to install the tool for.
  --prerelease             determining whether to include pre-release packages.
```

Notice the `--prerelease` option. This is not currently documented on the page linked to this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, I'm fixing it in #29998.
