### ISSUE TITLE
Clarification about the term-generic method

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#30008]
Hi,
First of all -it is NOT an error, but it can be a "good to have" info. The page nicely explains the generic methods saying:
Generic methods can appear on generic or nongeneric types. It is important to note that a method is not generic just because it belongs to a generic type, or even because it has formal parameters whose types are the generic parameters of the enclosing type. A method is generic only if it has its own list of type parameters. It also confirms this saying the following method (M) is not generic:
```
class Generic<T>
{
    T M(T arg)
    {
        T temp = arg;
        //...
        return temp;
    }
}
```
Now consider a simple non-generic concrete method in a non-generic class as follows:
```
class Sample
{
    void SomeMethod(){}
}
```
--Now, should we categorize the SomeMethod and M  same saying that both are non-generic methods? or, there is any "distinguishing" term for them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc82239-30f3-14d2-ed23-5c0b66bd370e
* Version Independent ID: 26fccd46-c489-1a05-2da2-dda3a8e5fac8
* Content: [Generics in .NET](https://docs.microsoft.com/en-us/dotnet/standard/generics/)
* Content Source: [docs/standard/generics/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/generics/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I hope this answers your question. I'll close this issue. Please feel free to respond!
