### ISSUE TITLE
Not clear what "annotations" and "warnings" values of Nullable property do

### ISSUE THREAD

**Issue by shtratos** [dotnet/docs#30009]
[Enter feedback here]

The current version says:
> The argument must be one of `enable`, `disable`, `warnings`, or `annotations`. The `enable` argument enables the nullable context. Specifying `disable` will disable the nullable context. When providing the `warnings` argument the nullable warning context is enabled. When specifying the `annotations` argument, the nullable annotation context is enabled.

`enable` and `disable` are more or less intuitively understandable.
OTOH, it is not at all clear to me as a developer what are "nullable warning context" and "nullable annotation context". 

Questions I'd like to see covered here:
- What are the consequences of using these options?
- How will the behaviour of the build and compiler change when using each of them?
- In what cases should they be used? What can I achieve with them?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548e000-8190-b1bb-51fd-7e7b2d5bcb45
* Version Independent ID: 19f59267-c4c1-eb0e-7e48-45ffd6e2d9d1
* Content: [C# Compiler Options - language feature rules](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#nullable)
* Content Source: [docs/csharp/language-reference/compiler-options/language.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/language.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 43588](https://dev.azure.com/msft-skilling/Content/_workitems/edit/43588)

**Comment by BillWagner** [comment]
Thanks for noting this @shtratos 

I think all your questions are answered [here](https://docs.microsoft.com/dotnet/csharp/nullable-references#nullable-contexts).

Let me know if that's correct. If so, we'll add a link to that section on this page to address this issue. If more details are needed, we'll add those details on the linked page.

**Comment by shtratos** [comment]
Thank you, Bill, this answers it perfectly. Please add a link.

**Comment by shtratos** [comment]
Yes, that's perfect! Thank you very much.

Mentioning this guide also would be helpful:
https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies
