### ISSUE TITLE
Partial methods and visibility is unclear

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#30017]
In this article and its [companion topic](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/partial-method), it appears as if the default for a partial method with no visibility modifier is `private`.

It is also suggested that by adding a visibility modifier like `public` to the partial declaration requires that an implementation is provided.

It's also suggested that the partial declaration and the implementation signatures must match.

This leads me to believe you can't have a declaration like:

```cs
partial void OnSomethingHappened();
```

and make the implementation protected like:
```cs
protected partial void OnSomethingHappened() { ... }
```

Clarifying how this works/doesn't work with an example or more prose in the bullets would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450a248b-ab3f-ac3f-d3a5-b1e74b3355ba
* Version Independent ID: 5e05ac12-7d29-d144-a49a-e54765343c20
* Content: [Partial Classes and Methods - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 229456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229456)

**Comment by BillWagner** [comment]
Thanks @michael-hawker 

I see two changes suggested above:

1. Clarify that adding any access modifier (`public`, `private`, etc) to a partial method declares *requires* that an implementation is provided. The default access is `private`, and if the modifier is omitted, an implementation is optional.  (The return type must be `void` if no access modifier is provided.
2. Add that the signature must match for all declarations. If not, it's a compiler error.

Let me know if I've missed any concerns in your description.

I'll add this to our backlog, and add the "up for grabs" label.

**Comment by michael-hawker** [comment]
@BillWagner yup, that's it, thanks! 🦙❤
