### ISSUE TITLE
What is the purpose of EntityConfigurationSource  class?

### ISSUE THREAD

**Issue by MithunChopda** [dotnet/docs#30036]
What is the purpose of EntityConfigurationSource class in this example? How would adding the Provider itself instead of Source be different in the Extension method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1cda6a-30fa-91b9-793e-918666776c9f
* Version Independent ID: 4df737d8-1051-2ce1-1d61-58768046283b
* Content: [Implement a custom configuration provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-configuration-provider)
* Content Source: [docs/core/extensions/custom-configuration-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-configuration-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @MithunChopda,

The configuration source is required as far as I can tell. The `IConfigurationSource.Build` returns the `IConfigurationProvider`. Does that make more sense now?

**Comment by IEvangelist** [comment]
I'm going to close this issue, as it's been addressed by https://github.com/dotnet/docs/issues/30036#issuecomment-1171559994
