### ISSUE TITLE
Sentence doesn't make sense

### ISSUE THREAD

**Issue by lloydjatkinson** [dotnet/docs#30032]
The following line in this page make zero sense to me. I've read it a few times and I just cannot understand what it's trying to explain.

> The .NET app in this tutorial relies on the .NET SDK as part of its functionality, as such, **the highlighted line relayers the .NET SDK anew with the build output.** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c32d49db-bd6c-c5db-96c9-fe426191d6ca
* Version Independent ID: 491a0389-f24d-a398-4496-873461b6180d
* Content: [Tutorial: Create a GitHub Action with .NET](https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action)
* Content Source: [docs/devops/create-dotnet-github-action.md](https://github.com/dotnet/docs/blob/main/docs/devops/create-dotnet-github-action.md)
* Product: **dotnet**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by svick** [comment]
I agree that the sentence is hard to understand.

I think it's trying to explain that the lines in question create a new set of Docker layers, independent from the previous ones. It starts from the scratch with the SDK image, and to it it adds the build output from the previous set of layers.
