### ISSUE TITLE
Orleans transactions

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/docs#30063]
**Help us make content visible**

**Describe the new article**

There is an upcoming added capability for [Orleans transactions](https://github.com/dotnet/orleans/pull/7805) that needs to be documented.

The location of the added content should be at [Orleans transactions documentation](https://docs.microsoft.com/en-us/dotnet/orleans/grains/transactions), both at ingress of transactions (because new configuration is made available) and then at a section of the *transaction client* itself (please review what is [written in the PR](https://github.com/dotnet/orleans/pull/7805) as a short example of what the paragraph can cover).

The outline would perhaps go like this

- At introduction, expand on transaction setup for client and silo
- At transaction client paragraph on the transaction client capabilities and what use cases it supports
- At transaction client paragraph also include some gotchas that the user need to be aware of with this new option (e.g., if not careful can make transactions deadlock)

I'll be available for both writing and reading of the article if you need my assistance.

Also note that this feature is not yet available in Orleans version 4.0.0-preview1, but is merged into the main branch of Orleans and will be available in a future release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233761c6-cd47-3faf-9b8b-d6d074ef6837
* Version Independent ID: 34764110-226e-2ae3-5ea0-3c5895015ab5
* Content: [Transactions in Orleans](https://docs.microsoft.com/en-us/dotnet/orleans/grains/transactions)
* Content Source: [docs/orleans/grains/transactions.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/transactions.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 30916](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30916)

**Comment by IEvangelist** [comment]
Closed by #32227
