### ISSUE TITLE
Document a few new SDK properties customers affecting Maui and xplat compilation

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#30076]
**Help us make content visible**

DisableTransitiveFrameworkReferenceDownloads 
Microsoft.Maui.Essentials 
EnableWindowsTargeting 
NETSDK1100

**Describe the new article**

@tdykstra, this PR makes three changes we want documentation on: https://github.com/dotnet/sdk/pull/25358

1. If a customer wants to build a windows application (WPF, Winforms) on a non-windows platform, they will get NETSDK1100 today. We've changed the behavior so that if they set `<EnableWindowsTargeting>true</EnableWindowsTargeting>`, this will enable them to get unblocked. This is because we don't automatically download targeting and runtime packs on platforms that aren't supported but with this flag, we now will when cross-targeting.
2. If a customer has a reference to a project that uses Maui essentials but haven't set `<UseMauiEssentials>true</UseMauiEssentials>`, then they will need to. We can't flow the maui essentially dependencies automatically without breaking other scenarios but setting this will make sure that the referencing project correctly pulls in the right known framework reference for maui essentialls.
3. We added DisableTransitiveFrameworkReferenceDownloads. Setting this to true will let customers avoid downloading extra runtime and targeting packs they didn't need. For some Maui windows scenarios, it was trying to download aspnet and windows desktop packages just in case they were needed later and this will disable that unless directly used.

**Comment by marcpopMSFT** [comment]
CC @dsplaisted  to review this when the documentation is ready.

**Comment by gewarren** [comment]
@marcpopMSFT @dsplaisted For `UseMauiEssentials`, it seems that the namespaces are no longer named "Maui.Essentials" - https://github.com/dotnet/maui/pull/5562#issuecomment-1079255633. Did/should the property name change too?

**Comment by dsplaisted** [comment]
> @marcpopMSFT @dsplaisted For `UseMauiEssentials`, it seems that the namespaces are no longer named "Maui.Essentials" - [dotnet/maui#5562 (comment)](https://github.com/dotnet/maui/pull/5562#issuecomment-1079255633). Did/should the property name change too?

@Redth @jonathanpeppers Can you comment on this?

**Comment by jonathanpeppers** [comment]
I've found `DisableTransitiveFrameworkReferenceDownloads` is needed sometimes.

Errors like this for an Android project:

```
Unable to find package Microsoft.WindowsDesktop.App.Runtime.win-x64 with version (= 7.0.0)
```

Which is probably caused by stable branding/feeds changing. This was noticied on the https://aka.ms/dotnetperfstatus pipelines that build MAUI projects and measure performance.

But then a customer wouldn't hit this? Just dogfooders, and internal pipelines?
