### ISSUE TITLE
Exposed HTML in BlockingCollection description on page

### ISSUE THREAD

**Issue by RedQuark** [dotnet/docs#30108]
`IProducerConsumerCollection&lt;T&gt;.`
should appear as
`IProducerConsumerCollection<T>.`

edit by @billwagner to add tracking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfef78b3-a48d-be0c-3ccd-a789e0e4eaef
* Version Independent ID: 0186f87a-b98e-8a05-d09f-be3de55928e2
* Content: [When to Use a Thread-Safe Collection](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection)
* Content Source: [docs/standard/collections/thread-safe/when-to-use-a-thread-safe-collection.md](https://github.com/dotnet/docs/blob/main/docs/standard/collections/thread-safe/when-to-use-a-thread-safe-collection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by RedQuark** [comment]
This is on page [https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection) under the "Recommended Content" heading.

**Comment by IEvangelist** [comment]
This has been fixed, thanks for bringing to our attention @RedQuark 💜
