### ISSUE TITLE
dotnet-format --check option is missing from this doc

### ISSUE THREAD

**Issue by TimothyMothra** [dotnet/docs#30102]
The `--check` option is missing from this doc.

Source: https://github.com/dotnet/format/blob/b24acb9d3a22996bd2354ebf890c38eb38e7c98c/CHANGELOG.md#50211103---2021-02-11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009c8a6b-f784-7111-8662-43b2da30b0ab
* Version Independent ID: 51e52bf4-61b8-6f7d-d947-8bcd71c7bd7d
* Content: [dotnet format command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-format)
* Content Source: [docs/core/tools/dotnet-format.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-format.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by JoeRobich** [comment]
@TimothyMothra That is understandable. These docs are for the dotnet CLI subcommands. The docs for the 5.x build are still available from our repo - https://github.com/dotnet/format/blob/release/5.x/docs/README.md

**Comment by TimothyMothra** [comment]
Thankyou. I think we can close this issue.
