### ISSUE TITLE
Github Actions: Add Note/Warning - for Full Path to the project DLL in docker

### ISSUE THREAD

**Issue by JBraunsmaJr** [dotnet/docs#30101]
**Page in question**
[Github Action Tutorial](https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action#the-dockerfile)

**Problematic Content**
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "/DotNet.GitHubAction.dll" ]
```

**Issue I ran into**
I built a service which uses the default docker template (the 'add docker support' feature). Seeing that I use the `runtime`, I didn't pay attention to the `entrypoint`!!
The template uses a relative path to the DLL using a `workdir` of `/app`. Inside the runner it sets the `workdir` to `/github/workspace`, something different. Thus, when the entrypoint executes it fails!

**Proposed Solution**
Add a highlight to
```dockerfile
ENTRYPOINT [ "dotnet", "/DotNet.GitHubAction.dll" ] # this line
```
Add a note, similar to the one explaining size differences between SDK and runtime but indicating that providing a **full path** to the DLL is required in order to work in the runner.

Additionally, I'd propose that the powers that be update the default docker template to use a full path. 

```dockerfile
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/myapplication.dll"] # a 5 character change here
```

Or to use the same approach as this example where the workdir isn't needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c32d49db-bd6c-c5db-96c9-fe426191d6ca
* Version Independent ID: 491a0389-f24d-a398-4496-873461b6180d
* Content: [Tutorial: Create a GitHub Action with .NET](https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action#the-dockerfile)
* Content Source: [docs/devops/create-dotnet-github-action.md](https://github.com/dotnet/docs/blob/main/docs/devops/create-dotnet-github-action.md)
* Product: **dotnet**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
This shouldn't be the case. The `COPY` directive, immediately preceding the `ENTRYPOINT` copies the build output into the `.` directory, which is the root. Making `/DotNet.GitHubAction.dll` correct. Not only has this been tested, but it's currently running in production right now, see:

https://github.com/dotnet/samples/blob/main/github-actions/DotNet.GitHubAction/Dockerfile

And the corresponding bot-generated output from this running:

https://github.com/dotnet/samples/blob/main/github-actions/DotNet.GitHubAction/CODE_METRICS.md

**Comment by JBraunsmaJr** [comment]
The problem isn't the doc content itself. The problem was I used the default docker template that gets inserted into a new project, or when you use "add docker support".

The default template uses the runtime which is all I needed. So when viewing the docker setup seen in the docs I completely overlooked the entry point/output location, which in the past never needed adjustment.  I got complacent. I'm sure I'm not alone.

All I am asking is if more emphasis could be put on that last section, a warning if you will about how the runner specifies a workdir which will break things if you don't follow the sample in the docs. 

After a few years using this template it's the first time the workdir mattered.

**Comment by IEvangelist** [comment]
> The problem isn't the doc content itself. The problem was I used the default docker template that gets inserted into a new project, or when you use "add docker support".
> 
> The default template uses the runtime which is all I needed. So when viewing the docker setup seen in the docs I completely overlooked the entry point/output location, which in the past never needed adjustment. I got complacent. I'm sure I'm not alone.
> 
> All I am asking is if more emphasis could be put on that last section, a warning if you will about how the runner specifies a workdir which will break things if you don't follow the sample in the docs.
> 
> After a few years using this template it's the first time the workdir mattered.

This additional context is very helpful, thank you for the clarification. I'll add more emphasis to the last section highlighting the concern. Thanks again.

**Comment by JBraunsmaJr** [comment]
I appreciate it! Thank you for your time.
