### ISSUE TITLE
No reference to IsCompleted in sample code

### ISSUE THREAD

**Issue by leotohill** [dotnet/docs#30115]
The article seems intended to demonstrate the use of the IsCompleted property of IAsyncResult, but it is not referenced. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0e4ecc-ad37-afc3-48c8-2e4ca49bbf19
* Version Independent ID: 5afc2822-8cdf-19e6-e978-b75b7b1ec95e
* Content: [Using an AsyncCallback Delegate to End an Asynchronous Operation](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/using-an-asynccallback-delegate-to-end-an-asynchronous-operation)
* Content Source: [docs/standard/asynchronous-programming-patterns/using-an-asynccallback-delegate-to-end-an-asynchronous-operation.md](https://github.com/dotnet/docs/blob/main/docs/standard/asynchronous-programming-patterns/using-an-asynccallback-delegate-to-end-an-asynchronous-operation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
The use of `IsCompleted` is demonstrated in the example in https://docs.microsoft.com/dotnet/standard/asynchronous-programming-patterns/polling-for-the-status-of-an-asynchronous-operation. This is mentioned in the article you referenced:

> Use the [IsCompleted](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncresult.iscompleted) property of the [IAsyncResult](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncresult) returned by the asynchronous operation's BeginOperationName method to determine whether the operation has completed. For an example that demonstrates this approach, see [Polling for the Status of an Asynchronous Operation](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/polling-for-the-status-of-an-asynchronous-operation).
