### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by sandeeparroju** [dotnet/docs#30138]
Interfaces doesn't contain any constructors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fd340a-0f74-8602-28a1-9569296a5951
* Version Independent ID: 1f0a9a2b-6495-370d-620f-a6dabec7df3b
* Content: [Interfaces - define behavior for multiple types](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces)
* Content Source: [docs/csharp/fundamentals/types/interfaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @sandeeparroju 

I looked at the content, and it states that interfaces may contain `static` constructors. That's a feature that was added in C# 8, with default interface members. The same paragraph states that instance constructors are not allowed.

The article is correct, so I'll close this without action. If I misunderstood the issue, reopen it and add more details for me.
