### ISSUE TITLE
consider adding link to System.Threading.Channels  in See also

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#30147]
Something like

* [System.Threading.Channels](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/) which can provide a more efficient locking mechanism for some problems.

I'd be happy to add that if it's helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edbf125-784e-14eb-5989-7f0334dc659b
* Version Independent ID: 8bca01b4-44f9-31fd-8616-fc8bed9275ef
* Content: [lock statement - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock)
* Content Source: [docs/csharp/language-reference/statements/lock.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/lock.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I like that idea @Rick-Anderson 

If you want to make the PR, I'll watch for it.
