### ISSUE TITLE
parser.Invoke/InvokeAsync doesn't exist, examples unclear

### ISSUE THREAD

**Issue by hawkerm** [dotnet/docs#30156]
The default example ends in `await rootCommand.InvokeAsync(args);` as the `Main` method in the original sample is `async`.

In the 'customize help for a single option or argument' section though it's unclear where the new code goes, it seems to imply that it should replace the above line since it references the `rootCommand` as input to the `CommandLineBuilder`.

However, the final line contains `parser.Invoke(args);` which is invalid. The `Parser` class in the latest beta release only has a `Parse` method.

This also doesn't show how to then return the proper `int` result back to the main method from this new invocation?

Overall:
- [ ] It's unclear what code to add/replace from the start example to get the full picture
- [ ] The code given is incorrect against the latest beta it says it's for as it doesn't compile
- [ ] The new code (assuming it was supposed to be replaced) doesn't show how to return the value again (it's also odd it's no longer `async`?)
  - [ ] The second example does show using an `parser.InvokeAsync`, but again that method doesn't exist.
- [ ] The changing of the header example down below pulls in another dependency and doesn't show how to do something more simple like just add a few lines of text or something else...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b05a5b-736e-0c49-edff-fd736bd969cb
* Version Independent ID: 7580e28c-776e-f479-54d7-adedd93f63a2
* Content: [How to customize help in System.CommandLine](https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help)
* Content Source: [docs/standard/commandline/customize-help.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/customize-help.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@hawkerm, Thanks for reporting these issues - I'm adding the missing instructions in #30276.
