### ISSUE TITLE
`dotnet install` exits non-zero upon successful installation

### ISSUE THREAD

**Issue by ncook-hxgn** [dotnet/docs#30158]
I used `dotnet install` to install the Azure Sign Tool as part of an Azure DevOps pipeline, as documented in their [WALKTHROUGH.md](https://github.com/vcsjones/AzureSignTool/blob/main/WALKTHROUGH.md).

`dotnet install` returned non-zero because the tool was (already) installed successfully.

```- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: Install AzureSignTool
```
yielded:
```
Starting: Install Azure SignTool
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.202.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
"C:\Program Files\dotnet\dotnet.exe" tool install --global azuresigntool --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources
Tool 'azuresigntool' is already installed.
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects : 
Finishing: Install Azure SignTool
```

It would be nice if `dotnet install` did not return non-zero when it has installed the tool successfully. That it does so prevents my Azure DevOps pipeline from being repeatable on a given self-hosted build agent, due to the build failing when run a second time during the installation of a tool to use during the build. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef
* Version Independent ID: 80822879-4c2e-1c28-ae04-1adb5e7e8a99
* Content: [dotnet tool install command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
* Content Source: [docs/core/tools/dotnet-tool-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by ncook-hxgn** [comment]
https://github.com/dotnet/sdk/issues/9043

**Comment by tdykstra** [comment]
Closing as this is a product, issue rather than a documentation issue and is documented in https://github.com/dotnet/sdk/issues/9043
