### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kaleesraja** [dotnet/docs#30178]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c718a6bd-75c6-13e1-36ae-7412668240a2
* Version Independent ID: d6f5fdf0-5b12-ef6d-b126-5ef28fdc8004
* Content: [Compiler Error CS0122](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0122)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0122.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0122.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @Kaleesraja 

Do you have a question about this content? There isn't enough information for me to take any action.
