### ISSUE TITLE
ValueTuple documentation should discuss serialization

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#3019]
# ValueTuple documentation should discuss serialization

## General

The documentation should be revised to note that:

- .NET Standard, including 2.0, does not define serialization support for ValueTuples.
- ValueTuples are not serialized in .NET Core 1.x or the .NET Framework 4.7 and earlier.

@ViktorHofer

**Comment by ViktorHofer** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple
