### ISSUE TITLE
Some typo in 4th example

### ISSUE THREAD

**Issue by Wallace92** [dotnet/docs#30218]
Hi,
in the 4th example I noticed that should be method1() instead of method3() to generate the CS0534.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d4fcf9-42c1-e015-798c-0c1519d77f41
* Version Independent ID: 75aee013-1123-1403-b2bc-cc8b68b56de8
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/inheritance)
* Content Source: [docs/csharp/fundamentals/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @Wallace92,

The compiler error [CS0534](https://docs.microsoft.com/dotnet/csharp/misc/cs0534) is accurate in the 4th sample. I do admit that it's a bit confusing that there is a method in `B` named `Method3`, but the compiler error is that the inheriting type isn't implementing an abstract member.

[See here: sharplab.io](https://sharplab.io/#v2:CYLg1APgAgzABAQwEYGcAuAnBBjNcoBMcAggLABQA3hXLfvMulrvgCxwCyApmgBYD2wAIwAKAJQBuCgF8KFWPiIAhOCBJwA9BrgBxLgDsuWNFxRwAwgGUADAFYYrAHQVq5OvTaceA4DHE06V3d3LTgAEX44FH4AW28AS30Ac2c3OllyaSA==)

I'm going to close this, as it is accurate as documented. Please correct me if I'm overlooking something and we'll reopen this issue. Thank you
