### ISSUE TITLE
Update linux docs to be simpler

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#30231]
There are two big things that are missing from the docs today:

- Here are the packages you need
- You really need to register the PMC feed

These points are getting lost (including in the troubleshooting section) with the immediate version-specific sections.

I'm writing this note to remember this feedback. I'm happy to make these changes.

**Comment by adegeo** [comment]
What is the PMC feed?

**Comment by adegeo** [comment]
Closing this as fixed as @richlander and I worked on rewriting the linux docs
