### ISSUE TITLE
BC30389 modifier Public

### ISSUE THREAD

**Issue by selebi-pikwe** [dotnet/docs#30235]
VS2019, VB. The page discusses possible problems with modifier of Private, but I am getting modifier Public as shown in the error message below, which does not make sense. Page does not help.

Error	BC30389	'M16VSimV3.modM16VSimulator.M16Address' is not accessible in this context because it is 'Public'.	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4253a1a0-903d-d6d3-efca-ca049e67a791
* Version Independent ID: 09ac6277-46d3-f932-4b4e-127305e0c169
* Content: ['&lt;method&gt;' is not accessible in this context because it is '&lt;modifier&gt;' - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30389?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(BC30389)%3Bk(TargetFrameworkMoniker-.NETFramework%252CVersion%253Dv4.7.2)%26rd%3Dtrue)
* Content Source: [docs/visual-basic/misc/bc30389.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30389.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment]
@selebi-pikwe I agree the page needs an update for the scenario you're encountering. To answer it, it's most likely that one of the containing symbols of your method is *not* public, so the method is not accessible even if it's declared public.

**Comment by selebi-pikwe** [comment]
Thank you, you hit the nail on the head. The page sent me off in completely the wrong direction.

**Comment by Youssef1313** [comment]
@BillWagner Do you want to reopen to track improving the documentation? I also opened a compiler issue to improve the error message https://github.com/dotnet/roslyn/issues/62790.
