### ISSUE TITLE
How to make a worker process exit succesfully?

### ISSUE THREAD

**Issue by catmanjan** [dotnet/docs#30236]
I created a worker process using the VS2022 template and the only change I made was I commented out the while loop below.

When running this, I would think the process would run, wait a second and then finish, but it just runs forever.

How do I make a BackgroundProcess that will actually finish?

I have asked this question a few times in various channels but have had no answer so here I am

```csharp
namespace WorkerService2
{
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            //while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae847f16-ff74-ab68-7163-f713b447430c
* Version Independent ID: ff379d26-0d85-6d74-67da-4a3cd260b04d
* Content: [Worker Services in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers)
* Content Source: [docs/core/extensions/workers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/workers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gfoidl** [comment]
> When running this, I would think the process would run, wait a second and then finish, but it just runs forever.

The worker itself is finished, as the `Task` returned from `ExecuteAsync` is completed once the method exits.
But the _host_ is still up and running. That's expected, as the template is "Worker service", and a service should run until stopped externally (via service control, etc.).

If you want to shutdown the host, change your code to 
```c#
public class Worker : BackgroundService
{
    private readonly IHostApplicationLifetime _hostApplicationLifetime;
    private readonly ILogger<Worker> _logger;

    public Worker(IHostApplicationLifetime hostApplicationLifetime, ILogger<Worker> logger)
    {
        _hostApplicationLifetime = hostApplicationLifetime;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        //while (!stoppingToken.IsCancellationRequested)
        {
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(1000, stoppingToken);
        }

        _hostApplicationLifetime.StopApplication();
    }
}
```
so use the `IHostApplicationLifetime .StopApplication`-method to indicate that you want to stop the app / host.

But be aware: as mentioned this is not the typical use-case for "services" like _BackgroundService_ which should run "forever" (i.e. until stopped / canceled via host).

**Comment by catmanjan** [comment]
Thanks I can confirm this does exactly what I need!

I am actually publishing my service as a cron triggered Azure WebJob (which must implement BackgroundService) - it is expected that this runs to completion or else it should be a continuous WebJob

It would be good to get this information added somewhere in the Azure WebJob doco because as written today it is not possible to deploy a triggered Azure WebJob that ends up in a "Completed" state - without the StopApplication call they finish executing and then idle until they are killed due to timeout
