### ISSUE TITLE
Please provide a working example and a description of all additional assets needed to make this work

### ISSUE THREAD

**Issue by mariongothier** [dotnet/docs#30242]
It would be really helpful if the code example on this page could just be copy pasted, resulting in running code. As is, it's not clear how to create the .db file, where it should be saved, what the tables and entries in it should look like, and also the id variable is not declared in code (what should its type and value be??). 

Also please always include the using statement, it is NOT always  obvious what it should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c03d8e-0706-c4bb-80bb-a4a36e36af23
* Version Independent ID: db9e319f-689a-f356-957e-23457bdcea7e
* Content: [Overview - Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli)
* Content Source: [docs/standard/data/sqlite/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/data/sqlite/index.md)
* Product: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by mohamed-azhar** [comment]
Looks like we need a downloadable starter code sample here which includes SQL scripts to create the database schema and add some data too.

Also, @mariongothier if you need better explanations for SQLite, please head to [Getting Started with EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=visual-studio) where a detailed explanation with code samples with GitHub links are provided.

**Comment by bricelam** [comment]
The full sample for this code snippet can be found here:

https://github.com/dotnet/docs/tree/main/samples/snippets/standard/data/sqlite/HelloWorldSample
