### ISSUE TITLE
Dapr supports DynamoDB as a state store but it is not found in the doc

### ISSUE THREAD

**Issue by yanxiaodi** [dotnet/docs#30246]
Hi there, I'm reading the doc of the state management of Dapr. I don't see DynamoDB in this section: https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/state-management#state-store-components. But I think it support DynamoDB?

Also these are missing as well:
* CockroachDB
* JetStream KV
* MySQL
* OCI Object Storage
* Oracle Database
* RethinkDB

It would be great if this page can be updated. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be98c390-3a32-085b-1529-a74bffefc76e
* Version Independent ID: 1f92eb1d-21da-4d0b-ad70-a28d168636a9
* Content: [The Dapr state management building block](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/state-management)
* Content Source: [docs/architecture/dapr-for-net-developers/state-management.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/state-management.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Hi @yanxiaodi,
Thanks for the report, I've created a PR to update the list.
