### ISSUE TITLE
Missing .NET 6.0 C# article CS8803 issue. Have zero ideas on where to find documentations to learn how to resolve this issue

### ISSUE THREAD

**Issue by tommai78101** [dotnet/docs#30249]
![image](https://user-images.githubusercontent.com/6444116/179379736-9b0fe3fd-e0de-4afa-9f55-07962b20c1e3.png)

Currently using the newest .NET 6.0 template changes, where in C# 11.0, you can used implicit usings and other changes.

https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates

However, with this error appearing, I don't have a clue as to where to find information on how to write proper C# 11.0 .NET 6.0 `Program.cs` code that doesn't throw this error. Trying to challenge myself only to write C# code that the newest .NET 6.0 template changes introduces in.

If there are other resource I missed out on, please point me to the right place. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8803))
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @tommai78101 

We do cover the rules that cause this error in the article on [top level statements](https://docs.microsoft.com/dotnet/csharp/fundamentals/program-structure/top-level-statements#namespaces-and-type-definitions)

Also, we are working on addressing the missing error and warning messages. We haven't gotten to this one yet.

**Comment by BillWagner** [comment]
Fixed in #31201
