### ISSUE TITLE
Doesn't provide an example of how to fix this error

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs#30273]
The example shows how the error arises, but doesn't show the code that fixes the error. I don't understand the explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38ff35c-9223-df13-6714-bccbf8f03ce3
* Version Independent ID: 21837aec-5c20-f647-17c8-e97aac29b137
* Content: [Compiler Error CS0759](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0759?f1url=%3FappId%3Droslyn%26k%3Dk(CS0759))
* Content Source: [docs/csharp/misc/cs0759.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0759.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @gfmoore 

A `partial` method may have two different declarations:

1. An empty declaration that declares the method will be implemented in another part:

```csharp
public partial class C
{
    public partial void M(); // No implementation
}
```

2. A declaration that includes the implementation:

```csharp
public partial class C
{
    public partial void M()
    {
        // Additional statements could fill this implementation.
    }
}
```

CS0759 indicates that your code doesn't have that 2nd version (the one with the implementation). Adding it will fix the error.

I've added the "up for grabs" label to this issue if any community members want to address it before we make the next set of updates.

**Comment by gfmoore** [comment]
Thankyou very much. I don't know how or why, but my problem arose in a dot net maui app where I accidentally used an int instead of a string in an [ObservableProperty] declaration. Once I assigned the correct type it all went away. I appreciate the additional info though. :)
