### ISSUE TITLE
Sample output does not show custom firstColumnText of --color option

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#30283]
The article shows how to customize the  System.CommandLine help for the --color option:

<https://github.com/dotnet/docs/blob/0a19cc3681583cb80295b88cd9d5014a1d73645d/docs/standard/commandline/snippets/customize-help/csharp/Program.cs#L97-L103>

After customization, the sample output includes:

<https://github.com/dotnet/docs/blob/0a19cc3681583cb80295b88cd9d5014a1d73645d/docs/standard/commandline/customize-help.md?plain=1#L84-L87>

This sample output shows the custom `secondColumnText` but not the custom `firstColumnText`. It should show that too, because the sample code did customize it.

Likewise in the ”Add or replace help sections” section of the article:

<https://github.com/dotnet/docs/blob/0a19cc3681583cb80295b88cd9d5014a1d73645d/docs/standard/commandline/customize-help.md?plain=1#L127-L130>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b05a5b-736e-0c49-edff-fd736bd969cb
* Version Independent ID: 7580e28c-776e-f479-54d7-adedd93f63a2
* Content: [How to customize help in System.CommandLine](https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help)
* Content Source: [docs/standard/commandline/customize-help.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/customize-help.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, I'm fixing it in #30293.
