### ISSUE TITLE
DAPR State store - Javascript SDK issue saving values always as string when use gRPC

### ISSUE THREAD

**Issue by zacutti** [dotnet/docs#30297]
With javascript SDK, If we use gRPC when save method is called, always values are persisted as string.
Then query filter does not work and also has others side efect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be98c390-3a32-085b-1529-a74bffefc76e
* Version Independent ID: 1f92eb1d-21da-4d0b-ad70-a28d168636a9
* Content: [The Dapr state management building block](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/state-management)
* Content Source: [docs/architecture/dapr-for-net-developers/state-management.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/state-management.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Hi @zacutti 
Because this is an issue with the JavaScript SDK, please report the issue in the Dapr JS SDK repository: https://github.com/dapr/js-sdk/issues

Thanks!

**Comment by nishanil** [comment]
Closing this issue.
