### ISSUE TITLE
Porting apps: Porting NuGet packages

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#303]
Issue tracking new topic at http://dotnet.github.io/docs/porting/nuget-packages.html

**Comment by ghogen** [comment]
critical for build
link to Nuget docs

**Comment by cartermp** [comment]
Although I was tracking an existing PR with #212, I think I'm going to break that up until multiple PRs and track with these issues.

Outline:

1. Prerequisites

   a. You've ported your library (or framework) successfully - link back to those (#302)
   b. Tools you need or may want

2. Using the .NET CLI toolchain to generate the NuGet package

   a. Commands
   b. What's generated
   c. Authoring a `.nuspec` file and creating a package with that

3. Using the NuGet command line

   a. Commands
   b. What's generated
   c. Authoring a `.nuspec` file

4. Advanced scenarios

   a. Point to NuGet docs - potentially specific pieces for certain scenarios?

I feel like there may be more content to place here, but I'm not quire sure.  @ericstj @terrajobst, what do you think?

**Comment by mairaw** [comment]
This is related to moving .NET Framework to .NET Core using NuGet.

**Comment by mairaw** [comment]
Closing this issue. We cover most of this already between us and NuGet docs. For specific scenarios that we're missing, better to open a new issue.
