### ISSUE TITLE
In C++ function pointers are rarely used and is unneeded.

### ISSUE THREAD

**Issue by jormundgand** [dotnet/docs#30318]
[Enter feedback here]
The focus on "C++" function pointer seems to miss the point about C++. The function pointer is a legacy from C and sees very little use in (modern at least) C++. C++ developers tend to use inheritance and lambdas, not function pointers to achieve something similar to what a delegate allows. I suggest the text is changed to use "C", when talking about function pointers. In C, only function pointers can (easily) be used to achieve something similar to delegates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e3cfc0-21d1-a453-94f2-52c86c926117
* Version Independent ID: f7628623-ae76-0688-4124-848b8c636168
* Content: [Delegates - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/)
* Content Source: [docs/csharp/programming-guide/delegates/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 357259](https://dev.azure.com/msft-skilling/Content/_workitems/edit/357259)

**Comment by BillWagner** [comment]
Thanks for the suggestion @jormundgand 

I've added this to our list to address when we next update this article.
