### ISSUE TITLE
.NET 6: Update Configuration to use new minimal host

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#30310]
Can we get this updated for the new host?

`var builder = WebApplication.CreateBuilder(args);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9
* Version Independent ID: 0d5de37c-8f89-b6a5-3132-2c5214196bfd
* Content: [Configuration in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration)
* Content Source: [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @Rick-Anderson, the new host is `WebApplication`. This is not part of the `Microsoft.NET.Sdk`. This isn't something that we're going to include here; as it is web-specific, however, we are considering adding `Host.CreateApplicationBuilder` from .NET 7. I'm going to close this for now as it is something that we're already aware of.
