### ISSUE TITLE
.Net 4 is missing

### ISSUE THREAD

**Issue by cadop** [dotnet/docs#30316]
I assume there is some reason that is obvious to regular users, but there is an explanation for .NET 7.x, 6.x, 5.x, and 3.x, but skips 4.x . 

### In the text:

[C# 11](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11) is supported only on .NET 7 and newer versions. [C# 10](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10) is supported only on .NET 6 and newer versions. [C# 9](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9) is supported only on .NET 5 and newer versions. [C# 8.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8) is supported only on .NET Core 3.x and newer versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
Very short version of the history of .NET.

It started as .NET, which evolved up to .NET 4.
Then started .NET Core, evolved up to .NET Core 3.1. After .NET Core 3.1 there was a desire to drop "Core" for moving on the future solely as .NET.

As there was already a .NET 4 this version couldn't be used again, so there was a jump forward to .NET 5.

For more infos please see [.NET Core is the Future of .NET](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/) and the linked posts.

**Comment by cadop** [comment]
I see. I'm not sure how to fix the phrasing, but I think the confusing part is `core`  vs `framework`. 

![image](https://user-images.githubusercontent.com/11399119/180786265-cf40d6d6-42b3-4778-b3ab-1d0060e6e6b3.png)

The heading says framework, and when I am building my project i need to set .net framework, so its hard to find information on this framework targeting pack because these links (referenced in the issue) keep showing up. 

![image](https://user-images.githubusercontent.com/11399119/180786408-8acdebd5-7f7a-4625-b635-9381a466cc58.png)

**Comment by BillWagner** [comment]
ping @richlander 

Do you have good wording to disambiguate between "target framework" and ".NET Framework"?

**Comment by richlander** [comment]
We don't. However, in that table, the column header could be simplified to just "Target" or "Target platform". Target frameworks always include a version, so the column technically isn't a target framework, but something more abstract. There is a name for that concept, too, but that's adding more complexity.
