### ISSUE TITLE
Add DisableTransitiveProjectReferences

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/docs#30341]
Recently i've found this property to have a use-case in which you don't want transitive dependencies to be visible to the compiler for your respective project. This also has synergy with directory.build.props files to do it in a global fashion for all .csprojs.

A typical solution might look like the following:

```
<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
```

and

```
      <Private>false</Private>
      <ExcludeAssets>all</ExcludeAssets>
```

This feature being searchable on .NET docs would be useful for those who prefer the "old non-SDK .csproj" behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by JonDouglas** [comment]
Related to #30340 because Rainer is a faster typer than I am.

**Comment by rainersigwald** [comment]
We did manage to have almost entirely distinct sets of info in the bug though! Closed my other one, here's the content

> The .NET SDK automatically "promotes" transitive references of a project (projects referenced by projects referenced by the project) to be direct references, which was a behavior of the old `project.json` from before .NET Core 1.0. This (sometimes surprising) behavior can be disabled by setting a property `DisableTransitiveProjectReferences`, but that isn't documented in the "SDK properties" page.
