### ISSUE TITLE
"record" variable marked as keyword in samples, making them unnecessarily hard to understand

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/docs#30357]
The syntax highlighting is making the example using a variable named "record" very confusing. It took me a while to realize that wasn't some mind bending new fancy switch statement, but just switching on the variable "record". And I've been coding C# for a decade.  Probably best to choose a different variable name to avoid confusing the syntax highlighter... these new features are hard enough to parse as is, without the added complication of incorrectly marking things as keywords that aren't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#list-patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@IEvangelist Is it possible to move C# highlighting on docs.microsoft.com to a new Roslyn-based tool, while keeping other languages using highlight.js?

**Comment by BillWagner** [comment]
@Youssef1313 The plan of record is to switch from highlight.js to [TextMate](https://macromates.com/manual/en/language_grammars). 

To fix this issue, we should just change the variable name from `record`. The current choice is likely confusing to many readers.
