### ISSUE TITLE
The Alpine instructions to install dotnet-sdk are incomplete

### ISSUE THREAD

**Issue by FilBot3** [dotnet/docs#30351]
Reading the documentation, and following it, it just lists a bunch of dependencies and no actual install like it does on Ubuntu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca
* Version Independent ID: f066a748-0a7d-7506-3b18-c422fef13293
* Content: [Install .NET on Alpine - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine)
* Content Source: [docs/core/install/linux-alpine.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @FilBot3 

The Install section calls this out. While Alpine is an officially supported distro by .NET, there is no package manager integration like other distros.

![image](https://user-images.githubusercontent.com/67293991/183312059-52b60d39-7200-4937-812d-f9002e9fcb2a.png)

I'm going to close this issue as I don't think there is anything to update in the docs. Please feel free to respond if there is something else I can do to the docs. Cheers!
