### ISSUE TITLE
Dangling reference to --roll-forward in documentation of DOTNET_ROLL_FORWARD

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#30360]
The [`DOTNET_ROLL_FORWARD`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_roll_forward) environment variable is documented like this:

> Determines roll forward behavior. For more information, see the `--roll-forward` option earlier in this article.

However, the earlier (or later) sections of the article do not mention the `--roll-forward` option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fab316-eb04-50f5-03c8-bf3004981d3e
* Version Independent ID: 0c8e3542-470a-fa11-0d27-061384c4c3ba
* Content: [.NET environment variables - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables)
* Content Source: [docs/core/tools/dotnet-environment-variables.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-environment-variables.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that! I'm fixing it in PR #30369
