### ISSUE TITLE
Pressing F11 maximises the console window, instead of stepping to the next statement

### ISSUE THREAD

**Issue by FlyingDutchman1965** [dotnet/docs#30362]
Hi there,

Just a little documentation issue, that might cause a beginner some confusion.

In the section on "Step through a program", at the point after the user has entered their the keyboard focus will still be on the console window. The immediate next tutorial instruction (step 5) is to press F11 to step to the next program statement, but this is sent to the console window which causes it to be maximised or restored.

There needs to be an instruction to switch the keyboard focus from the console window back to Visual Studio before pressing F11

Regards.

John.

---
[Associated WorkItem - 44861](https://dev.azure.com/msft-skilling/Content/_workitems/edit/44861)

**Comment by IEvangelist** [comment]
Hi @FlyingDutchman1965 - thanks for posting this issue. I'd love to help, but I need to know what article you're referring to? Could you please respond here with a link to the article and the section where you experienced this confusion? Thank you

**Comment by FlyingDutchman1965** [comment]
Hi David,

Apologies, but I thought that would have been automatically included with the issue request. URL to article is as follows:

Article: .NET Documentation -> Overview -> Tutorials -> Use Visual Studio -> Debug an App
Section: Step through a program

Debug a .NET console application using Visual Studio - .NET | Microsoft Docs



I could probably just as well have submitted a GitHub pull request with a suggested change, but live and learn!

Regards.

John.

Sent from Mail for Windows

**Comment by FlyingDutchman1965** [comment]
Try this:

[https://docs.microsoft.com/en-gb/dotnet/core/tutorials/debugging-with-visual-studio?pivots=dotnet-6-0](url)
