### ISSUE TITLE
IDExxxx rules missing documentation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#30361]
Rule ID | Missing Help Link | Title | Notes |
--------|-------------------|-------| ----- |
<strike>IDE0120</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0120> | Simplify LINQ expression |
<strike>IDE0130</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0130> | Namespace does not match folder structure |
<strike>IDE0200</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0200> | Remove unnecessary lambda expression |
<strike>IDE0210</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0210> | Convert to top-level statements |
<strike>IDE0211</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0211> | Convert to 'Program.Main' style program |
<strike>IDE0220</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0220> | Add explicit cast |
<strike>IDE0230</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0230> | Use UTF-8 string literal |
<strike>IDE0240</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0240> | Remove redundant nullable directive |
<strike>IDE0241</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0241> | Remove unnecessary nullable directive |
<strike>IDE0250</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0250> | Make struct 'readonly' |
<strike>IDE0251</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0251> | Make member 'readonly' |
<strike>IDE0260</strike> | <https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0260> | Use pattern matching |  |
<strike>IDE0270</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0270> | Use coalesce expression | Might be good to document it the same page as IDE0029 and IDE0030. |
<strike>IDE0280</strike> | <https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0280> | Use 'nameof' |
JSON001 |  | Invalid JSON pattern | |
JSON002 |  | Probable JSON string detected | |
RE0001 |  | Invalid regex pattern | |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a396c1-9c21-75a9-70b5-799cafc941b5
* Version Independent ID: 6d91b560-c12f-6e6d-e92b-1babb27edb67
* Content: [Code style rules overview - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/)
* Content Source: [docs/fundamentals/code-analysis/style-rules/index.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 30989](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30989)

**Comment by gewarren** [comment]
Thanks Youssef!

**Comment by Youssef1313** [comment]
> Should IDE0250 ([dotnet/roslyn#63668](https://github.com/dotnet/roslyn/pull/63668)) be added to this issue? I can't find documentation for that analyzer either.

Yes indeed. I edited the issue and added IDE0250.

**Comment by flobernd** [comment]
Is there anything I could check to find out the matching style configuration keys? Like for `IDE0220` there seems to be `dotnet_style_prefer_foreach_explicit_cast_in_source`.

**Comment by Youssef1313** [comment]
> As well, documentation for IDE2000, IDE2001, IDE2002, IDE2003 and IDE2004 is missing.

These are experimental and shouldn't be documented until https://github.com/dotnet/roslyn/issues/60539 is resolved.

**Comment by flobernd** [comment]
Ah I see. Thought they are not experimental anymore as they got explicitly promoted in the NET7 release blog post (at least IDE2000).

**Comment by Youssef1313** [comment]
@flobernd [This](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/) blog post? I haven't fully read it, but I can't see matches for IDE2000 via a quick search.

**Comment by flobernd** [comment]
My bad it was this post: https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/

But I misread (they mention IDE0200 and not IDE2000). Sorry for the confusion.

**Comment by gewarren** [comment]
> Is there anything I could check to find out the matching `.editorconfig` keys? Like for `IDE0220` there seems to be `dotnet_style_prefer_foreach_explicit_cast_in_source`.

You can check https://github.com/dotnet/roslyn/blob/2766d2815ff8c8ab8c9b073e254a05969e6ebb7b/src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs#L745-L1300.

**Comment by mavasani** [comment]
I also created https://github.com/dotnet/roslyn/issues/65757 on Roslyn side. Kindly update that story (and related tracking issue) if someone is working on the documentation PR for any of these rules. Ideally, we want to get into the habit of the developers who contribute the analyzer to take up contributing the docs PR, but let's see how far we can take that.

**Comment by KUTlime** [comment]
@Youssef1313 

Can you update the table in the issue description with IDE0270 & IDE0280?

**Comment by Youssef1313** [comment]
@KUTlime Updated, and added more that were missing too.

**Comment by gewarren** [comment]
For the remaining rules (JSON001, JSON002, RE001) it seems like these are IDE-only, so those probably belong with the Visual Studio docs at https://github.com/MicrosoftDocs/visualstudio-docs. Should I create an issue for those rules there? @Youssef1313 @Mikejo5000 @mavasani

**Comment by litoj** [comment]
There are still options missing. How do I disable _IDE0320_? using `dotnet_diagnostic.IDE0320.severity = none` in editorconfig does nothing and the entire Internet knows nothing about it. I want to disable suggestions for static anonymous functions but I can't because I cannot find a way to and there is no index of all lints to search through.

**Comment by gewarren** [comment]
> There are still options missing. How do I disable _IDE0320_? using `dotnet_diagnostic.IDE0320.severity = none` in editorconfig does nothing and the entire Internet knows nothing about it. I want to disable suggestions for static anonymous functions but I can't because I cannot find a way to and there is no index of all lints to search through.

The article was recently published: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0320#suppress-a-warning

Have you tried setting `csharp_prefer_static_anonymous_function = false`?

**Comment by litoj** [comment]
@gewarren not until now, but it sure works. Thank you.
