### ISSUE TITLE
incorrect dispaly of cref and href attributes.

### ISSUE THREAD

**Issue by albert-github** [dotnet/docs#30385]
There is a mention of in the overview of the recommended tags in the section [Generate links and references](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#generate-links-and-references) - These tags generate links to other documentation.
```
[<cref>](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#cref-attribute)
[<href>](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#href-attribute)
```
though this should in my opinion either be left out or be:
```
[cref](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#cref-attribute)
[href](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#href-attribute)
```
as `cref` and `href` are attributes en no tags

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcb925f-ef72-9a64-3762-c0b4a96f9dc4
* Version Independent ID: d135d0a6-53d2-1567-0b1b-7aae5e07739f
* Content: [Recommended XML documentation tags for a class and its members](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags)
* Content Source: [docs/csharp/language-reference/xmldoc/recommended-tags.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/recommended-tags.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good suggestion @albert-github 

We should remove the brackets from the `cref` and `href` attributes.
