### ISSUE TITLE
Can't Add gRPC Connected Service to .NET Standard Class Library Project

### ISSUE THREAD

**Issue by DeviantSpark** [dotnet/docs#30391]
In the section "Generate client code" it says to create a new .NET Standard library project and then use "Manage Connected Service" to add a gRPC service reference. When I try to add a service reference in VS 17.2.6 to this type of project I only get options for OpenAPI and WCF Web Service. How do I get the option for gRPC for this type of project? I only see the gRPC option with a .NET Core 3 project but I want to do it in a .NET Standard project like the article describes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 325dd28c-3bed-f7ff-4f13-7c7c951250fd
* Version Independent ID: f9bef770-f952-169a-0dec-a25606d4207d
* Content: [Migrate a WCF request-reply service to gRPC - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-request-reply)
* Content Source: [docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/migrate-request-reply.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by erjain** [comment]
We can close this issue now.
