### ISSUE TITLE
Does not cover ErrorHandling Guidance for Deserialization

### ISSUE THREAD

**Issue by ashishmundrajll** [dotnet/docs#30409]
[Enter feedback here]
If I have a json where some fields of an object have invalid values. E.g. 

class Person
{
      string Name
      int Age
}

and if I have json like {"name": "Ashish", "age": "a string value not a integer"} and if I want to Deserlize this to a Person object, as Age cannot be converted, I like the object to be Person.Name = Ashish, Person.Age = null or Person.Age = 0. How to achieve such a behaviour.

Please note that above is just a Psuedocode. Basic question is how to Deserialize a json and not ignore if some fields have error, but set those fields to default values or null values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ashishmundrajll You can set a default property value in the following way:

`public int Age { get; set; } = 0;`

Does that help?

**Comment by ashishmundrajll** [comment]
We created a CustomCosmosSerializer, something similar to https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs and then in the JsonSerializerSettings specified Error is Handled which defaults values if they have wrong values in Cosmos DB while getting them.
