### ISSUE TITLE
Doc|_|pvcrvzico.rogue 

### ISSUE THREAD

**Issue by plainEYA** [dotnet/docs#30413]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c9d0ef-c6b0-87f2-746d-6940b1377a54
* Version Independent ID: 575e8c7c-a170-a9d0-ee59-c42451cd1ac9
* Content: [Table of contents - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/readme)
* Content Source: [standard/README.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/README.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing as not relevant.
