### ISSUE TITLE
DEPOSIT/WITHDRAWL example is missing a minus sign

### ISSUE THREAD

**Issue by blixtor** [dotnet/docs#30411]
The following line
`[_, "FEE", var fee]               => decimal.Parse(fee),`
should read
`[_, "FEE", var fee]               => -decimal.Parse(fee),`

as fees are deducted from the balance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @blixtor 

I opened a PR to address this issue.
