### ISSUE TITLE
Discuss IDisposable and objects with global scope or long lifetimes

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#3043]
# Revised guidance on objects that implement IDisposable

## General
The "Using an object that implements IDisposable" section of the [IDisposable interface](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.7) and the [Using objects that implement IDisposable](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects) topics discuss IDisposable only in the context of objects whose lifetimes are confined to a single method. However, some disposable objects are either global or have lifetimes that are longer than a single method. The documentation provides no guidance about these. These two sections should be expanded to cover such disposable objects.
 
/cc @markmnl @terrajobst

**Comment by alfredmyers** [comment]
On the subject of "objects that have lifetimes that are longer than a single method", there are those:
1. Who are scoped to a single class.
2. Who's scope leaks beyond the class where it was created.

The first case can be mitigated using the [Dispose Pattern](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern)
The second one is a case of transfering of ownership. While the disposal of the instance should be taken care by the code on the receiving end, there's still need in the member where the IDisposable is instantiated for guaranteeing no leaks in case an exception is thrown between the instance's creation and transfering it to its new "owner".

**Comment by IEvangelist** [comment]
Fixed in #18266
