### ISSUE TITLE
Upgrade-Assistant installation instructions

### ISSUE THREAD

**Issue by Brain2000** [dotnet/docs#30442]
The instructions on this page are incorrect to install upgrade-assistant.
Instead, you must use:
`dotnet tool install -g --ignore-failed-sources upgrade-assistant`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf49988-a3ca-a140-76f7-e5aff6ffb309
* Version Independent ID: bf952cc5-836b-90c5-5f80-83baa3b796dd
* Content: [Overview of the .NET Upgrade Assistant - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview)
* Content Source: [docs/core/porting/upgrade-assistant-overview.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
Hi! You must have added other repositories to your nuget configuration, which is triggering the failure. However, the normal command will work for anyone who doesn't add repositories. Regardless, I'll add a note about this scenario.
