### ISSUE TITLE
Verbatim String Interpolation example Output is Wrong

### ISSUE THREAD

**Issue by lndexNull** [dotnet/docs#30441]
[Enter feedback here]
I've Read through the Verbatim String Interpolation and noticed, that the example Output was Wrong, because it included tabs that aren't in the actual output.

Example on the page:

// Output:
// Jupiter Hammon
//                     was an African American poet born in 1711.
// He was first published in 1761
//               at the age of 50.

What it should actually look like according to the code:

// Output:
// Jupiter Hammon
//     was an African American poet born in 1711.
// He was first published in 1761
// at the age of 50.

Edit: It doesn't show the proper spacing here, when i leave edit mode for some reason.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @lndexNull 

I created a PR to update the output.
