### ISSUE TITLE
About Paste command; and about the Ctrl + Alt + UpArrow/DownArrow shortcuts

### ISSUE THREAD

**Issue by khangquangtran** [dotnet/docs#30453]
In the Focus Mode, in the editor.

There is no Paste feature in the context menu when I right-click in the edit area. There is also no Paste command in the F1/Command palette. Because of both, I have to use Ctrl + V all the times. Please add the Paste feature.

The shortcuts <Ctrl + Alt + UpArrow> and <Ctrl + Alt + DownArrow> in the edit area do not work. Windows captures these shortcuts and flips the display instead. Please fix the functionality of these shortcuts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516a8fed-04ea-628c-d644-eb81dedecfe6
* Version Independent ID: 060c37e4-36e1-48b3-2435-cf858b14d860
* Content: [Data collections - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/list-collection)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/list-collection.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great point @khangquangtran 

We can't add that due to security restrictions in the browsers. But, there is a workaround: either using the hotkey (Ctrl+V, or Cmd+V) or using the context menu and selecting paste.

We should add that tip to the start of each tutorial.
