### ISSUE TITLE
Incorrect output value in example

### ISSUE THREAD

**Issue by syntaxartisan** [dotnet/docs#30469]
I think one of your examples has an incorrect answer. Would someone double check it?
For the example
a ^= 0b_1000_0000;
which executes the calculation
0b_1111_1000  XOR  0b_1000_0000
I believe the answer is 01111000 not 1111000
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa
* Version Independent ID: 2410c828-0c66-9efe-ae87-9b07708aa731
* Content: [Bitwise and shift operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators)
* Content Source: [docs/csharp/language-reference/operators/bitwise-and-shift-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Sharp :eye: @syntaxartisan 

The output is correct, but isn't obvious. The output doesn't include the leading zero:

`1111000`
vs.
`01111000`

We should note that in the comment on the output.

**Comment by pkulikov** [comment]
@syntaxartisan @BillWagner #30671 "fixes" the output by adding the necessary amount of leading zeros
