### ISSUE TITLE
Please add a note that this can be caused if you forget the ">" in a lambda

### ISSUE THREAD

**Issue by framlingham** [dotnet/docs#30468]
Could you please add a note that this can be caused if you forget the ">" in a lambda? It took me longer than I'm comfortable admitting to realize. For example `myList.Any(x = double.IsNaN(x))`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2cb61f-1605-70ba-c5fb-cc4a9d9f2c8d
* Version Independent ID: 6eaec3e9-0ed9-f3ec-7516-032d57246715
* Content: [Compiler Error CS0103](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0103.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0103.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @framlingham 

I've added it to the backlog for our next updates, and I've added the "up for grabs" label in case anyone wants to submit a PR before we get to the update.

**Comment by bergerb** [comment]
I would like to take a look at this one.  Thanks!  It is available?
