### ISSUE TITLE
Documentation page for Comparison<T> doesn't show return value information

### ISSUE THREAD

**Issue by MichaelSL** [dotnet/docs#3048]
# Documentation page for Comparison<T> doesn't show return value information

The documentation page doesn't contain the information that is present in [document](https://github.com/dotnet/docs/blob/master/xml/System/Comparison%601.xml) in this repository.

# General

Here is what i have in Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Several sections of what we have in the [document](https://github.com/dotnet/docs/blob/master/xml/System/Comparison%601.xml) are missing.

![image](https://user-images.githubusercontent.com/2205113/29999425-2e99a4ea-9048-11e7-8018-d0da2173bb63.png)

**Comment by BillWagner** [comment]
@MichaelSL Thanks for spotting this. It also affects other generic delegate types (like `Predicate<T>`. We've filed an internal bug to fix the API reference generation process.

**Comment by mairaw** [comment]
@MichaelSL this should be resolved now. Please verify.

**Comment by MichaelSL** [comment]
Looks OK now! I’m closing the issue.
