### ISSUE TITLE
Need to see the other half of DI

### ISSUE THREAD

**Issue by DavidEwan** [dotnet/docs#30488]
Maybe its just me - but I'm looking for the other half of DI. It sounds like I could do something like: 

var work = new Worker(); 

and magically the framework would inject the required service, but I dont see that anywhere in the examples. Maybe I'm reading over it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd55089-b683-2202-6641-c7b61a132f14
* Version Independent ID: cc5f00d0-fb50-1229-8fa2-e66b1f45b284
* Content: [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
* Content Source: [docs/core/extensions/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @DavidEwan - I'll update this a bit to add the additional context that you're asking for.
