### ISSUE TITLE
GetCancellationToken() is missing CancelationTokenSource information

### ISSUE THREAD

**Issue by Kaelum** [dotnet/docs#30494]
There is no discussion on the CancelationTokenSource, or how to Cancel the token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28554e6c-1983-ca7e-e9e0-200578729a28
* Version Independent ID: d8604fab-bf6f-e820-7db8-b22e3d724335
* Content: [How to handle termination in System.CommandLine](https://docs.microsoft.com/en-us/dotnet/standard/commandline/handle-termination)
* Content Source: [docs/standard/commandline/handle-termination.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/handle-termination.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
You can type <kbd>Ctrl</kbd>-<kbd>C</kbd> to trigger a cancellation.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
