### ISSUE TITLE
Exception Class

### ISSUE THREAD

**Issue by Ed2353** [dotnet/docs#30508]
The subject of exceptions is alot deeper then I would have thought- Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ccea38-3215-2399-9199-77aa3e901c29
* Version Independent ID: c91e5308-ebac-ea32-f565-5f14f286ee1c
* Content: [Exceptions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/exceptions)
* Content Source: [standard/exceptions.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/exceptions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the nice comment @Ed2353 

Closing as kudos.
