### ISSUE TITLE
wrong HttpClient guidelines for .NET Framework

### ISSUE THREAD

**Issue by diontools** [dotnet/docs#30511]
> In .NET Framework, create a new [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) each time you need to send a request.

I think this is wrong. .NET Framework also exhausts the socket.
It's dangerous guideline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f017a3e-7a32-392d-6021-17e738063a7a
* Version Independent ID: 873cb409-74a0-0cc8-7e95-05424f335f04
* Content: [HttpClient guidelines for .NET - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #30635.
