### ISSUE TITLE
I have followed the instructions exactly, but I get the error: "The type or namespace name 'ObjectDetection' could not be found"

### ISSUE THREAD

**Issue by jpayne0061** [dotnet/docs#30513]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by BillWagner** [comment]
ping @luisquintanilla

**Comment by jpayne0061** [comment]
Sorry, it appears I inadvertently opened this issue twice (was trying to edit the title): https://github.com/dotnet/docs/issues/30514#issuecomment-1207751903

The issue was resolved. 

Closing now
