### ISSUE TITLE
Q's re Ranges and Indexes Proposal

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#30512]
I'm transforming this proposal into a Draft PR for the C# Standard, and have several questions:

1. **Optional Members in `Index` and `Range`:** The proposal suggests that some members in these types are optional, such as `Range`'s `StartAt`, `EndAt`, and `All`. Which members are *required* for these types? Why not require all those provided by MS's implementation?

1. **Range indexer setter:** What if anything should we say about the implicit and explicit setter for a Range indexer? Certainly, one can define a setter for a user-defined type; however, it is not obvious as to what such a setter would do, especially since it must be used on the left-hand side of assignment taking a right-hand side of the same type as the index returns. In the case of type `BitArray` that would mean something like `ba1[range1] = ba2`, or perhaps `ba1[range1] = ba2[range2]`. As far as I can determine, the operations one might like to implement using such a setter are probably best implemented via a named method. In any event, for a compiler-generated Range indexer, attempting to use its setter results in the error message “CS0131 The left-hand side of an assignment must be a variable, property or indexer,” which suggests the generated indexer **has no setter**. If that is the case, we should say that, perhaps by stressing that the result of a Range indexer is *not* a variable, so as such, it can't be used on the lhs of an assignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges and indices - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @333fred @jcouv 

Where should I route this set of questions?

**Comment by 333fred** [comment]
1. The only one required is the constructor: we will fall back to it if any of the others are missing. As to why it was specified this way, I'm not certain, and unfortunately Andy (who implemented it) just went on leave for a few months.
2. I think we should say nothing about it, or at most say that no setter is synthesized if one does not exist. I think the rest of the rules should just fall out from this, as the error implies.

**Comment by RexJaeschke** [comment]
@BillWagner I'm good with these replies, so I'm closing-out this issue.
