### ISSUE TITLE
cmd.exe not found

### ISSUE THREAD

**Issue by SecuritasMachina** [dotnet/docs#30510]
running: docker run -it --rm --entrypoint "cmd.exe" counter-image
Yields: docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "cmd.exe": executable file not found in $PATH: unknown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
The error mentions OCI which is Linux. You're using the Windows, switch to the Linux tab instead.

**Windows**

![image](https://user-images.githubusercontent.com/7679720/183464828-88a26ca1-6cc2-481e-9ce2-9faa0732e43a.png)

**Linux**

![image](https://user-images.githubusercontent.com/7679720/183464918-07ddc55d-005e-443e-a981-3c37d7335ad7.png)

```docker
docker run -it --rm --entrypoint "bash" counter-image
```

**Comment by IEvangelist** [comment]
I'm going to close this, but we can reopen it if needed.
