### ISSUE TITLE
ObjectDetection namespace does not exist in the mentioned nuget packages

### ISSUE THREAD

**Issue by jpayne0061** [dotnet/docs#30514]
I have followed the instructions exactly, but I get the error: "The type or namespace name 'ObjectDetection' could not be found"

Here is a repo with the code up to this point in the tutorial (adding the namespaces): https://github.com/jpayne0061/ObjectDetection 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by MichaelDeutschCoding** [comment]
Hey, @jpayne0061, that namespace isn't meant to be found within any of those NuGet packages. It's something you create a bit later on in the tutorial. (I agree, it is confusing to start off right away by adding "usings" to namespaces that don't exist yet.) If you continue with the step-by-step, you'll create classes in directories with those namespaces, and that error will disappear 👍.

Just for reference: I did just try to code along with the whole tutorial from scratch, and can confirm that it all works properly -- no compile or runtime errors. (Though the ML still has some learning to do, based on the results I saw it output. 😏)

**Comment by MichaelDeutschCoding** [comment]
I will add one thing that could/should be improved: the default ".csproj" is created with nullable enabled, but the code in the project is not compliant with that, and produces (6) warnings.

I would suggest either explicitly telling users to remove the `<Nullable>enable</Nullable>` line if it exists in their csproj, adding default values to the properties that need them, or making them nullable.

**Comment by jpayne0061** [comment]
That was it, thank you!
