### ISSUE TITLE
.NET 5 still showing as supported 

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/docs#30531]
Additional content source: [docs/core/install/includes/versions-not-supported.md](https://github.com/dotnet/docs/blob/main/docs/core/install/includes/versions-not-supported.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a30294-c9ae-4189-26d7-ee7db615c487
* Version Independent ID: 2e9467f4-8572-c8e4-6a10-69faf14ce46c
* Content: [Install .NET on Fedora - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#supported-distributions)
* Content Source: [docs/core/install/linux-fedora.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by xtqqczze** [comment]
See also: #30314

**Comment by adegeo** [comment]
Duplicate of #30531
