### ISSUE TITLE
CommunityToolkit.Mvvm AlsoNotifyChangeForAttribute class

### ISSUE THREAD

**Issue by antoniohlopes** [dotnet/docs#30548]
### Description

Hi,
I'm using CommunityToolkit.Mvvm version 7.1.2 in MAUI project.
The "[AlsoNotifyChangeForAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.mvvm.componentmodel.alsonotifychangeforattribute)" cannot be found in version 8.0.0 after update NuGet project packages.
Regards
Antonio

### Version

Other (please put exact version in description textbox)

### Previous behavior

the project can be compiled.

### New behavior

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AlsoNotifyChangeFor' could not be found (are you missing a using directive or an assembly reference?)	SmartWedgePLCApp (net6.0-android), SmartWedgePLCApp (net6.0-windows10.0.19041.0)	C:\Users\anton\source\repos\DacksSmartWedgPLC\SmartWedgePLCApp\BaseController.cs	14	Active

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

stay updated

### Recommended action

do not update to CommunityToolkit.Mvvm version 8.0.0

### Feature area

C#

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/CommunityToolkit#129
