### ISSUE TITLE
Updates to .NET Core deployment topics for 2.0

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3059]
We have the following LiveFyre comments for the topic https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli:
- Process is slightly different for core 2.0. Is there a separate series of docs for core 2.0?
- Do you know how it is different? My self-contained app is having issues running, after publish, after upgrading to 2.0. Problems loading 'System.Net.Http.Native' or one of its dependencies. Probably one of its deps because it is in output directory.

@livarcocc @nguerrera what are the changes we need to consider when talking about deployment for 2.0?

/cc @rpetrusha

**Comment by rpetrusha** [comment]
The topic has been revised for 2.0 and 2.0 by #7468. Closing this issue.
