### ISSUE TITLE
What is needed for the Nuget portion of the TOC?

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#306]
Nuget topics seem to be very well documented on http://docs.nuget.org/. Ideally, we would just link over there and **not** copy content over. Now, do we need several docs (like it is currently planned in the TOC) or can we just have one document that would cover all of these + the interaction between Nuget and Core. 

/cc @mairaw @richlander @cartermp @ghogen

**Comment by cartermp** [comment]
I agree about not copying over docs.  Stuff that we'll cover is things like example usages of `dotnet pack` and explaining what was generated, with a link to NuGet docs for more advanced scenarios.

I think we can go with one doc for now.  #293 may warrant its own doc, but that's all I can think of.

**Comment by BillWagner** [comment]
I propose closing this as well. We do link to the NuGet docs, and we have written a topic to address #293

@mairaw @cartermp can you vote on that?
