### ISSUE TITLE
ValueObjects vs Records

### ISSUE THREAD

**Issue by konradbartecki-ss** [dotnet/docs#30608]
Comparison of how ValueObjects differ from C# records would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @konradbartecki-ss, thanks for sharing your feedback. I believe this page focuses on the implementation of value objects For more information on records, users can refer to the link: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/records#when-to-use-records. This will help the user to compare when to use records. Hope this helps.
