### ISSUE TITLE
I don' think ELLIPSIS(...) is a whitespace character

### ISSUE THREAD

**Issue by PO1970** [dotnet/docs#30614]
[Enter feedback here]

https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#whitespace-character-s 

https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#whitespace-character-s 

„\x85	          The ellipsis or NEXT LINE (NEL) character (…), \u0085.”

Okay, maybe the old NEXT LINE (https://www.compart.com/en/unicode/U+0085) can be considered whitespace but ellipsis (https://www.compart.com/en/unicode/U+2026) cannot.

Very confusing line: „The ellipsis **or** NEXT LINE (NEL) character **(…)**”
I don’t think NEXT LINE was ever called „ellipsis”.

If you agree, please correct that line like this:

„\x85	         The NEXT LINE (NEL) character, \u0085.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#whitespace-character-s)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I think the old windows code page used ... to visualize NUL. However, in the modern world this doesn't apply and is more confusing than not. I'll change it. Thanks!
