### ISSUE TITLE
In visual studio private variables have no _

### ISSUE THREAD

**Issue by andypoly** [dotnet/docs#30626]
You say here about using underscore on private and internal members (despite some dispute over the history of this).
Yet Visual Studio Community 2022 will not put an _ on private variables by default and converting an auto property to a full one with private member will simply use a lower case private variable as one would expect, but contrary to the tips here.

Is there a disconnect between Visual Studio team and the docs team here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 123086](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123086)

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/44699

**Comment by Youssef1313** [comment]
Tagging @CyrusNajmabadi @sharwell to consider if Roslyn can/should change the default naming styles to match conventions.

**Comment by andypoly** [comment]
hmm - yeah why would Microsoft's Visual Studio not have an option to enforce the naming convention they suggest for their language... without an editor config change...

**Comment by CyrusNajmabadi** [comment]
Dotnet naming in no way represents the naming for the industry. Last time we looked (admittedly a few years back), camel cased variables was the norm. It wasn't even close. Personally, I think dotnet naming is super silly and literally how against our guidance around unnecessary sigils on identifiers. So I find it unlikely we would change here for this niche audience. If you want this naming convention, just specify it.

**Comment by BillWagner** [comment]
This is an area we should look at more holistically.

In general, our docs follow the [dotnet/runtime coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md). We should update these articles to match that, and point liberally to the [editorconfig](https://docs.microsoft.com/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022) section of the Visual Studio docs to enable each team to enforce their preferences.

**Comment by CyrusNajmabadi** [comment]
Also, i have no issue with us shipping some sort of '.net naming' style that people could choose.  Or an easy way to add all the right naming styles to an existing editorconfig.

I would just push back on any sort of step that made this the default for everyone if they moved to a new version of VS.  This needs to be something people can opt-into, not something they're forced into that they need to opt-out of.

Thanks!

**Comment by amzwzw** [comment]
Haker
