### ISSUE TITLE
Describe how to add documentation/comments to global.json

### ISSUE THREAD

**Issue by binki** [dotnet/docs#30629]
`global.json` is a file which may have specific values set in it for some specific reason. However, it is JSON, a format which does not support inline comments.

Please provide an explanation for how one is expected to add documentation in their `global.json` or what convention one should use for placing documentation beside their `global.json` in a way that is discoverable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-json.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 47694](https://dev.azure.com/msft-skilling/Content/_workitems/edit/47694)

**Comment by tdykstra** [comment]
@baronfel Any suggestions?

**Comment by baronfel** [comment]
@binki while you are correct that Json isn't a format that natively supports comments, .NET tooling that makes use of the global.json file typically can parse these files. Newtonsoft.Json and System.Text.Json can also handle these files.  At this point we won't be making giant changes to this system (e.g. to another file format that supports comments) so you should use parsers and tools that understand comments or pre-process the files to strip comments out before processing.

**Comment by binki** [comment]
If this is the case, can the documentation be updated to clearly indicate this and provide an example of how a comment may be written?

I did end up finding this behavior through experimentation, but I would like to know I can rely on it by having it documented.

Thanks.

**Comment by tdykstra** [comment]
I'll add a note to the article.
