### ISSUE TITLE
Determine which .NET Framework versions are installed miss info about .NET 4.8.1 registry keys

### ISSUE THREAD

**Issue by bairog** [dotnet/docs#30620]
,NET Framework 4.8.1 [was released](https://devblogs.microsoft.com/dotnet/announcing-dotnet-framework-481) 2 days ago.
But docs page for [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) miss info about .NET 4.8.1 registry keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by bairog** [comment]
Also many people are curious how registry values look like (and how exactly runtime version distinction is working under the hood) when **both** .NET 4.8 SDK/Targeting pack **and** .NET 4.8.1 SDK/Targeting pack are installed (it is possible to check both checkboxes in VS Installer for latest VS 2022 17.3.0 REL – so one can choose between .NET 4.8 and .NET 4.8.1 in app creation dialog).

**Comment by gewarren** [comment]
There's an [open PR](#30619) that adds the DWORD value for 4.8.1, which is 533325.

@TaraOverfield Can you answer the question about registry values when both the 4.8 and 4.8.1 developer packs are installed?
