### ISSUE TITLE
Recommended use of a new HttpClient in net-framework - cause socket exhaustion

### ISSUE THREAD

**Issue by SDP190** [dotnet/docs#30635]
In the documentation in the paragraph under the title [**Pooled connections**](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines#pooled-connections) and further under [**Recommended use**](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines#recommended-use)
It appears as if for **dotnet Framework** disposing and using a new instance of `HttpClient` for every request is desirable, however this will cause many connections to get opened with "TIME_WAIT" stats (exhaust the available sockets), I've tested and verified this result with dotnet framework 4.5.2.

So, please clarify things and elaborate more why / what is it different between dotnet framework to Net5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f017a3e-7a32-392d-6021-17e738063a7a
* Version Independent ID: 873cb409-74a0-0cc8-7e95-05424f335f04
* Content: [HttpClient guidelines for .NET - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@SDP190 Much of this article was based on [this comment](https://github.com/dotnet/runtime/issues/68866#issuecomment-1119916486) and other information in that issue. Regarding .NET Framework, the comment says:

> in .NET Framework the connection pool was linked to ServicePointManager and HttpClient was implemented on top of HttpWebRequest. So disposing HttpClient did not impact connection management.

Perhaps @wfurt or @CarnaViire can weigh in here since they are the experts.

**Comment by SDP190** [comment]
Any update on this?

**Comment by SDP190** [comment]
Thanks to @gewarren and everyone involved
