### ISSUE TITLE
COMBINING Unicode categories and/or Unicode blocks?

### ISSUE THREAD

**Issue by PO1970** [dotnet/docs#30649]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
Not really a feedback, just a QUESTION about the   \p{...}   thingy:

https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#unicode-category-or-unicode-block-p 

The example at
https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#non-word-character-w 
i. e.

…[^\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Nd}\p{Pc}\p{Lm}]…

...makes me think that every single  \p{...}  compound requires its own \p at the beginning, i. e. it is NOT possible to combine Unicode categories and/or Unicode blocks this way:

…\p{LtLoNdLm}…

or

…\p{Lt|Lo|Nd|Lm}…

Confirm?

I mean I did try both via regex101.com and none of the above worked ... but there may be some other trick, which is not mentioned on the above page.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions

### Content source URL

https://github.com/dotnet/docs/blob/live/docs/standard/base-types/character-classes-in-regular-expressions.md

### Document Version Independent Id

95abea42-fa7f-3feb-ae38-049719ab938f

### Article author

@adegeo

### Metadata

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
I came across this issue while trying to investigate another. I know this is way late for a response but I had the same experience as you. I got them working in Visual Studio, but not in various online regex testing apps. I did find some info about unicode blocks that talked about requiring a unicode-friendly regex parse. I wonder if the online pages that test regex are all based on UTF-8 and just don't really handle those \P commands.

Regardless. I'm going to close this issue as I don't think there is anything to do in the docs about this, at the moment.
