### ISSUE TITLE
[Breaking change]: Windows Forms obsoletions diagnostics

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#30640]
### Description

The Windows Forms team has finally got around formally documenting obsoletions and other Windows Forms specific diagnostics. Those are now documented in https://github.com/dotnet/winforms/blob/main/docs/list-of-diagnostics.md.

May we please get these documented at the docs website similar to the https://docs.microsoft.com/dotnet/fundamentals/syslib-diagnostics/obsoletions-overview.

# .NET 7 Preview 1

## `WFDEV001` 

Possible messages: 
* Casting to/from IntPtr is unsafe, use `WParamInternal`.
* Casting to/from IntPtr is unsafe, use `LParamInternal`.
* Casting to/from IntPtr is unsafe, use `ResultInternal`.
 

### Previous behavior

The internal implementations of Windows Forms SDK have been updated to disallow direct use of [`Message.WParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.wparam) and [`Message.LParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.lparam) properties **within** the SDK implementations, to reduce the risk of cast and overflow exceptions associated with `IntPtr` on different platforms.

It is particularly dangerous to cast to/from `IntPtr` on 64 bit platforms as [implementation](https://source.dot.net/#System.Private.CoreLib/IntPtr.cs,103) of these casts uses [`checked`](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/checked) keyword. Doing so leads to intermittent numeric overflow exceptions. We've mitigated this historically by trying to first cast to long when casting out of IntPtr and first casting to int when casting into an `IntPtr`. That pattern, unfortunately, is difficult to audit and has negative performance implications, particularly on 32bit.

Using the new `nint`/`nuint` types allows casting to follow with the default project settings, which is unchecked. Casting works just like casting between other intrinsic types (`short`, `int`, `long`, etc.).

### New behavior

Projects using the DEBUG build of the Windows Forms SDK and referencing [`Message.WParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.wparam) and [`Message.LParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.lparam) properties will fail to compile.

### Type of breaking change

This diagnostics is only surfaced in DEBUG builds of Windows Forms SDK

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [x] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Enforce type safety while using the interop code.

### Recommended action

The Windows Forms SDK code must be updated to use the new internal properties, such as `WParamInternal`, `LParamInternal` or `ResultInternal` depending on the situation.

In consuming projects you can skip this obsoletion by adding the property `<NoWarn>$(NoWarn),WFDEV001</NoWarn>` to a property group in your project file (or adding the warning via the project properties pages).

### Affected APIs

[`Message.WParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.wparam) and [`Message.LParam`](https://docs.microsoft.com/dotnet/api/system.windows.forms.message.lparam)

# .NET 7 RC 1

## `WFDEV002` 

Any reference to [`System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.domainupdown.domainupdownaccessibleobject?view=windowsdesktop-6.0#definition) will result in a warning saying that this type is no longer used to provide accessible support for `System.Windows.Forms.DomainUpDown` controls. This warning will be promoted to an error in .NET 8, thus please replace this type with [AccessibleObject](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.accessibleobject?view=windowsdesktop-6.0) going forward. If the warning is suppressed, the code will continue to compile and run in .NET 7. This type had never been intended for public use.
 

### Previous behavior

No compile time warnings when referencing `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject` type.

### New behavior

Compile time warning when referencing `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject` type.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

All functionality of this class was moved to the base class.

### Recommended action

Update the code to not use `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject`. Use  [AccessibleObject](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.accessibleobject?view=windowsdesktop-6.0)  instead.

In consuming projects, you can suppress this obsoletion by adding the property `<NoWarn>$(NoWarn),WFDEV002</NoWarn>` to a property group in your project file (or adding the warning suppression via the project properties pages).

### Affected APIs

[DomainUpDown.DomainUpDownAccessibleObject Class](https://docs.microsoft.com/dotnet/api/system.windows.forms.domainupdown.domainupdownaccessibleobject)

## `WFDEV003` 

[`System.Windows.Forms.DomainUpDown.DomainItemAccessibleObject`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.domainupdown.domainitemaccessibleobject?view=windowsdesktop-6.0) is no longer used to provide accessible support for items in `System.Windows.Forms.DomainUpDown` controls.
 

### Previous behavior

Objects of this type were served to accessibility tools that were navigating DomainUpDown control hierarchy. This type was not exposed to user code directly and was documented as required for infrastructure support.

### New behavior

Instances of [AccessibleObject](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.accessibleobject?view=windowsdesktop-6.0) type representing items with DomainUpDown control will be returned to accessibility tools that are navigating control's hierarchy.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Base class provides all the required functionality to support hierarchy navigation.

### Recommended action

Remove invocations of public constructor for `System.Windows.Forms.DomainUpDown.DomainItemAccessibleObject` type. Use `System.Windows.Forms.AccessibleObject` instead.

In consuming projects, you can suppress this obsoletion by adding the property `<NoWarn>$(NoWarn),WFDEV003</NoWarn>` to a property group in your project file (or adding the warning via the project properties pages).

### Affected APIs

[DomainUpDown.DomainItemAccessibleObjectClass](https://docs.microsoft.com/dotnet/api/system.windows.forms.domainupdown.domainitemaccessibleobject)

### Feature area

Windows Forms

**Comment by vladimir-krestov** [comment]
1. **`WFDEV001`** - you missed `Message.Result` in the description. The rest looks good 👍 
2. **`WFDEV002`**:
     - _New behavior:_ 
     > `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject` is now obsolete, and the compiler will emit `WFDEV002` warning.

`System.Windows.Forms.DomainUpDown.CreateAccessibilityInstance()` still returns an instance of `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject` type while it raises a warning only for seamless reworking of applications using this to using new behavior. But now `DomainUpDownAccessibleObject` redirects all methods and properties to `System.Windows.Forms.UpDownBase.UpDownBaseAccessibleObject` type implementation.
@Tanya-Solyanik, please change it if we decide to remove `System.Windows.Forms.DomainUpDown.CreateAccessibilityInstance()`.

3. **`WFDEV003`**:
     - _Previous behavior:_ `DomainItemAccessibleObject` was used as a part of `DomainUpDown` accessibility tree inside "Items" list:
![image](https://user-images.githubusercontent.com/49272759/184405598-fac95f28-c388-4b58-936f-c03fbdfafd1e.png)
     - _New behavior:_ `DomainItemListAccessibleObject` is not used for building `DomainUpDown` accessibility tree anymore. See https://github.com/dotnet/winforms/issues/4207#issuecomment-941950437. So `DomainItemAccessibleObject` is not necessary anymore as well. 
     - _Recommended action:_ Update the code to not use `System.Windows.Forms.DomainUpDown.DomainItemAccessibleObject`, it can't be included in `DomainUpDown` accessibility tree anymore.

**Comment by Tanya-Solyanik** [comment]
@vladimir-krestov - what type is DomainItemAccessibleObject replaced with?

**Comment by vladimir-krestov** [comment]
> @vladimir-krestov - what type is DomainItemAccessibleObject replaced with?

Nothing, we don't use it at all and internal `DomainItemListAccessibleObject`. See decision in https://github.com/dotnet/winforms/issues/4207#issuecomment-941950437

**Comment by gewarren** [comment]
@adegeo @RussKie I think it makes sense to add the WFDEVXXX warning reference to the .NET Desktop Guide docs (https://docs.microsoft.com/en-us/dotnet/desktop/winforms/?view=netdesktop-6.0&preserve-view=true). What do you think? I will also document these as a breaking change in the usual place (https://docs.microsoft.com/en-us/dotnet/core/compatibility/7.0).

**Comment by RussKie** [comment]
Sounds great!
