### ISSUE TITLE
Page s contradiction Custom Excpetions

### ISSUE THREAD

**Issue by GBPhilip** [dotnet/docs#30644]
I am confused this page talks of 4 constructors for a custom exception the 4th being for serialization.
Bur this https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions only has 3.  What is the difference 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfeeac2f-fbeb-b4b5-ff02-fd48a28a2768
* Version Independent ID: 4d98bec1-a03a-4a9c-4108-cb847f9c18bd
* Content: [Creating and Throwing Exceptions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/creating-and-throwing-exceptions)
* Content Source: [docs/csharp/fundamentals/exceptions/creating-and-throwing-exceptions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/exceptions/creating-and-throwing-exceptions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for that update @GBPhilip 

This page should remove references to the Serialization constructor. That's no longer recommended.

I've added this to our backlog, and added the "up for grabs" label if anyone wants to update this article before we make our next set of updates.
