### ISSUE TITLE
Naming style for static members contradicts with the page "Names of Type Members"

### ISSUE THREAD

**Issue by fgimian** [dotnet/docs#30642]
This page suggests using a `s_` prefix for static members yet the [Names of Type Members](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members) docs specifically say:

> For example, do not use "g_" or "s_" to indicate static fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 123087](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123087)

**Comment by BillWagner** [comment]
This is an area we should look at more holistically.

In general, our docs follow the [dotnet/runtime coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md). We should update these articles to match that, and point liberally to the [editorconfig](https://docs.microsoft.com/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022) section of the Visual Studio docs to enable each team to enforce their preferences.

**Comment by fgimian** [comment]
> This is an area we should look at more holistically.
> 
> In general, our docs follow the [dotnet/runtime coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md). We should update these articles to match that, and point liberally to the [editorconfig](https://docs.microsoft.com/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022) section of the Visual Studio docs to enable each team to enforce their preferences.

Sounds good, thanks so much.  I think clarifying this consistently would be good.  Unfortunately some of these conventions also don't align with StyleCop defaults which makes it a little more confusing for someone who isn't as familiar withe language.

Kindest Regards
Fotis
