### ISSUE TITLE
SAUWUR r991eu][g]1=e=m=cbi. eke] ehououfo8

### ISSUE THREAD

**Issue by elvismunyikiiru** [dotnet/docs#30656]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301116d4-ff88-c411-e0e3-ba8b552fc6ee
* Version Independent ID: 586f81d7-d9df-95f7-d73f-7d7b6db198a5
* Content: [How to read from a text file - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-read-from-a-text-file)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-read-from-a-text-file.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/file-system/how-to-read-from-a-text-file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing and locking.
