### ISSUE TITLE
What about null/empty collections?

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/docs#30662]
Simply firing on `IReadOnlyList<T>` doesn't account for situations where the source object may be null or empty. Using nullable syntax like `collection?.FirstOrDefault()` accounts for both of these scenarios whereas forcing me to use an indexer would blow up in both of them.

This analyzer seems to need a bit more tweaking to be valid for scenarios like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7efd80-b7c4-548f-0879-e7a057c6aa0c
* Version Independent ID: c0709596-3235-7bc6-20aa-4f99523347d2
* Content: [CA1826: Use property instead of Linq Enumerable method (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1826.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1826.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mavasani
* Microsoft Alias: **mavasani**

**Comment by Youssef1313** [comment]
Looks like a product feedback rather than a documentation feedback.
@mavasani Can you move to roslyn-analyzers?

**Comment by Youssef1313** [comment]
@brandonh-msft I see two issues here:

1. You don't want warnings to fire on `...OrDefault` methods. There is an option already for that (`dotnet_code_quality.CA1826.exclude_ordefault_methods = true`). https://github.com/dotnet/docs/issues/29750 tracks adding documentation for it.
2. Firing on null access. I think the analyzer is correct in this case, but the codefix produces bad code.

![image](https://user-images.githubusercontent.com/31348972/184531571-6ca32864-03b2-4849-a253-1eeef690b34a.png)

It should be `x2?[0]`.

@brandonh-msft Does fixing the codefix resolve things for you?

**Comment by brandonh-msft** [comment]
yeah I think those 2 combined are good changes 👍🏻👍🏻

**Comment by Youssef1313** [comment]
I opened https://github.com/dotnet/roslyn-analyzers/issues/6348 to track fixing the codefix for null access.

@gewarren I think this can be closed now?
