### ISSUE TITLE
inscrutable message => Head scratching

### ISSUE THREAD

**Issue by xela-trawets** [dotnet/docs#30679]
CS0106 is (correctly) triggered by the following line in my dependency injection code

 private readonly `ILogger<FileScanBackgroundService>` Log { init; get; }

The message "The modifier 'modifier' is not valid for this item" is accurate but was unhelpful (to me) in this case.
 I read this docs page and wondered about the interface type, the specific interface, the dependency injection, interactions between modifiers and init etc; Completely missing the (simple) cause, which I leave to the reader...

I needed a hint. 
Perhaps as simple as "Check that the modifier that you are applying is valid for the language element it is applied too".

The fundamental issue (to me) was that this error is too broad.

Not a big problem, but puzzled me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2662c650-5bb7-3860-f803-42048194f880
* Version Independent ID: f3a26a17-4d0b-e6fc-dd54-28d91e4fa5ad
* Content: [Compiler Error CS0106](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0106?f1url=%3FappId%3Droslyn%26k%3Dk(CS0106))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0106.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0106.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by xela-trawets** [comment]
actual line was: 
 private readonly ILogger<FileScanBackgroundService> Log { init; get; }

**Comment by xela-trawets** [comment]
Duh
 private readonly `ILogger<FileScanBackgroundService>` Log { init; get; }

**Comment by BillWagner** [comment]
Thanks for noting this @xela-trawets 

I've added it to our backlog to address as we work on the compiler messages section.
