### ISSUE TITLE
Typo in Documentation at docs/samples/snippets/csharp/VS_Snippets_CLR/CryptoWalkThru/cs/Form1.cs in multiple lines

### ISSUE THREAD

**Issue by KamiKarsten** [dotnet/docs#30685]
There are 3 Typos in the [documentation ](https://github.com/dotnet/docs/blob/main/samples/snippets/csharp/VS_Snippets_CLR/CryptoWalkThru/cs/Form1.cs#:~:text=_decryptOpeFileDialog.InitialDirectory%20%3D%20EncrFolder%3B) at line 95, 96 and 98. There is a missing "n" in _decryptOpe**n**FileDialog 
![image](https://user-images.githubusercontent.com/51974674/184584147-a126e5cb-aa71-4f44-862e-225f64c1f123.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Create a Cryptographic Application](https://docs.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gewarren** [comment]
Thanks @KamiKarsten. It needs to be changed in this file too: https://github.com/dotnet/docs/blob/64b667801f6320adedbc654e98aebeb67a13c0f4/samples/snippets/csharp/VS_Snippets_CLR/CryptoWalkThru/cs/Form1.Designer.cs#L186
