### ISSUE TITLE
Installing SDK 6.0 on Ubuntu 22.04 installs the runtime only

### ISSUE THREAD

**Issue by Houuse** [dotnet/docs#30686]
[Enter feedback here]
output from `wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
`
`--2022-08-15 10:44:05--  https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 40.114.136.21
Connecting to packages.microsoft.com (packages.microsoft.com)|40.114.136.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3692 (3.6K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.d 100%[==================================>]   3.61K  --.-KB/s    in 0s      

2022-08-15 10:44:05 (1.40 GB/s) - ‘packages-microsoft-prod.deb’ saved [3692/3692]
`

output from `sudo dpkg -i packages-microsoft-prod.deb`
`(Reading database ... 204700 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu22.04.1) over (1.0-ubuntu22.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu22.04.1) ...`

output from `sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0`
`Hit:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Hit:2 http://apt.pop-os.org/proprietary jammy InRelease
Hit:3 http://apt.pop-os.org/release jammy InRelease
Hit:4 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:7 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dotnet-sdk-6.0 is already the newest version (6.0.400-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.`

output from `dotnet --info`
`global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by brunocasarotti** [comment]
I am facing the very same issue. Any workaround for that?

**Comment by Houuse** [comment]
https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install
worked for me

**Comment by adegeo** [comment]
This has been in transition to be included in the official Ubuntu feeds: https://github.com/dotnet/core/issues/7699

Docs update is in progress.
