### ISSUE TITLE
ASP.NET Core Runtime and .NET Runtime incorrectly stated in the instructions

### ISSUE THREAD

**Issue by agpldev** [dotnet/docs#30690]
The instructions on this page for the Runtimes does not look right. I think the "ASP.NET Core Runtime" and the ".NET Runtime" commands are reversed

Currently:
- ASP.NET Core Runtime => winget install Microsoft.DotNet.Runtime.6
- .NET Runtime => winget install Microsoft.DotNet.AspNetCore.6

Should be:
- ASP.NET Core Runtime => winget install Microsoft.DotNet.AspNetCore.6
- .NET Runtime => winget install Microsoft.DotNet.Runtime.6

![image](https://user-images.githubusercontent.com/64598903/184686391-1b537ac6-ece1-4d3c-8917-8fb84c88de5c.png)

Please review and correct accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60&source=docs)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
