### ISSUE TITLE
Just for fun changing a variable name

### ISSUE THREAD

**Issue by yoshionimusha** [dotnet/docs#30705]
[
i just thought it would be cool if instead of using the variable result, you used the variable quotient!!
the act of truncating when using int is actually the quotient. it is the amount of full times a number can be divided into another.

static void Divide(int x, int y, out int result, out int remainder)
{
    result = x / y;
    remainder = x % y;
}

public static void OutUsage()
{
    Divide(10, 3, out int res, out int rem);
    Console.WriteLine($"{res} {rem}");	// "3 1"
}
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [A tour of C# - The building blocks of C# programs](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tannergooding** [comment]
This is the term we use in the `DivRem` API that returns a `(T Quotient, T Remainder)` tuple. It helps disambiguate so I think the change is a net positive.
