### ISSUE TITLE
Missing information that duplicate keys from the same source is invalid

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#30709]
The documentation is missing the information that duplicate keys from the same provider are not allowed.

This will succeed:

```csharp
var configFile1 = Path.Combine(Environment.CurrentDirectory, "appsettings1.json");
File.WriteAllText(configFile1, "{\"setting\":\"value\"}");
var configFile2 = Path.Combine(Environment.CurrentDirectory, "appsettings2.json");
File.WriteAllText(configFile2, "{\"SETTING\":\"VALUE\"}");
var config = new ConfigurationBuilder()
    .AddJsonFile(configFile1)
    .AddJsonFile(configFile2)
    .Build();
```

And this:

```csharp
var section = config.GetSection("setting");
Console.WriteLine($@"Key: {section.Key}
Path: {section.Path}
Value: {section. Value}");
```

will output this:

```text
Key: setting
Path: setting
Value: VALUE
```

But this:

```csharp
var configFile = Path.Combine(Environment.CurrentDirectory, "appsettings.json");
File.WriteAllText(configFile, "{\"setting\":\"value\", \"SETTING\":\"VALUE\"}");
var config = new ConfigurationBuilder()
    .AddJsonFile(configFile)
    .Build();
```

will throw:

```text
An item with the same key has already been added. Key: SETTING

   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9
* Version Independent ID: 0d5de37c-8f89-b6a5-3132-2c5214196bfd
* Content: [Configuration - .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration)
* Content Source: [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by paulomorgado** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/26752

**Comment by IEvangelist** [comment]
Thank you, @paulomorgado!

I looked through the source for this. It seems like this only applies to the file configuration providers, JSON, XML, and INI. They will all throw the `FormatException` with a duplicate key message.

- [`JsonConfigurationFileParser` line number 103](https://github.com/dotnet/runtime/blob/080f708e7018f6c0529b6c875a44d84fc4d74419/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L103)
- [`XmlStreamConfigurationProvider` line numbers 384-399](https://github.com/dotnet/runtime/blob/080f708e7018f6c0529b6c875a44d84fc4d74419/src/libraries/Microsoft.Extensions.Configuration.Xml/src/XmlStreamConfigurationProvider.cs#L384-L399)
- [`IniStreamConfigurationProvider` line number 78](https://github.com/dotnet/runtime/blob/080f708e7018f6c0529b6c875a44d84fc4d74419/src/libraries/Microsoft.Extensions.Configuration.Ini/src/IniStreamConfigurationProvider.cs#L78)

I didn't see this error in any of the other providers as I believe it's impossible to occur. I added an alert under the file configuration provider section in https://github.com/dotnet/docs/pull/30712.
