### ISSUE TITLE
This code does not work

### ISSUE THREAD

**Issue by DHeydt** [dotnet/docs#30717]
I have copied the application however it does not work.

It appears to capture the navigation but fails when trying to send something back to the browser

The console displays...
Local address and port : [::1]:6767
Waiting for a connection...

I enter Localhost:6767 into my browser and get...

Waiting for a connection...
Tue, 16 Aug 2022 19:04:33 GMT: [::1]:1088
Waiting for a connection...

The browser sits with a spinner and just waits for a response.

Perhaps I misunderstood the code but it seems like it should write something back to the browser.

Also, not sure where the port 1088 comes from.

Any thoughts on how to fix this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

---
[Associated WorkItem - 44864](https://dev.azure.com/msft-skilling/Content/_workitems/edit/44864)

**Comment by IEvangelist** [comment]
This document doesn't mention the browser, as it's not involved. There are two applications, one is the server (listener) and one is the client. Create two console apps, run both of them and you'll find that this does work. The server will wake up and listen, and the client will connect to it. They'll both communicate back and forth.

I suppose that we should update this to make the creation of each app more explicit, thanks for calling attention to this.
