### ISSUE TITLE
Links on page don't seem to be working - Marshaling data with COM interop

### ISSUE THREAD

**Issue by pieandcakes** [dotnet/docs#3071]
# Issue Title
Links on page don't work - Link: https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-data-with-com-interop.md

## Issues with Existing Topics

The links in the page point back to msdn articles which don't exist.

**Comment by pieandcakes** [comment]
The "In this section" and below don't seem to be working.

**Comment by rpetrusha** [comment]
@pieandcakes, thanks for opening this issue. These topics are archived on MSDN, so links to them need to reference to exact archived version. We'll open a PR to fix the links so that they lead to the correct MSDN pages.

**Comment by mairaw** [comment]
The In This Section links should also be updated to reflect what exactly shows up in the section, So in some cases, the topics could either be removed or moved to the related sections
