### ISSUE TITLE
[Breaking change]: DataContractSerializer retains negative when reading "-0" as a float/double

### ISSUE THREAD

**Issue by StephenMolloy** [dotnet/docs#30722]
### Description

Going back to the NetFx days, DataContractSerializer (and DataContractJsonSerializer) have both had issues deserializing a negative float/double zero. The sign gets lost. Both serializers have always done the right thing when given "-0.0" as an input, but with an input of "-0", the sign gets lost. This is both inconsistent with the other behavior and a loss of information. And unfortunately "-0" is how these serializer write the data out during serialization.

The original report provides good detail. https://github.com/dotnet/runtime/issues/69019

This incorrect behavior has been in DCS/DCJS since at least 4.8, and probably long before then.

### Version

Other (please put exact version in description textbox)

### Previous behavior

The negative sign is lost when deserializing "-0" as a float or double.

### New behavior

The negative sign of the double is preserved.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

The old behavior is both inconsistent and a technical loss of data.

### Recommended action

No action recommended. If a user was affected by this bug, then they likely will welcome the change. Or have already worked around it in a way that is unlikely to be broken by this change.

### Feature area

Serialization

### Affected APIs

DataContractSerializer.ReadObject
DataContractJsonSerializer.ReadObject

**Comment by StephenMolloy** [comment]
The fix has been included in 7.0-rc1. Backporting to 6.0 is being considered.

**Comment by StephenMolloy** [comment]
@IEvangelist, @gewarren - This has also been ported back to 6.0 as well. (#75643) Should this be re-opened to track any 6.0 doc updates?

**Comment by gewarren** [comment]
Reopening to track updating the .NET 6 breaking changes.
