### ISSUE TITLE
Pipe basic usage example, method reader.AdvanceTo should be called with single parameter

### ISSUE THREAD

**Issue by obratim** [dotnet/docs#30733]
I don't think example "Pipe basic usage" is correct. I doubt in the implementation of method `ReadPipeAsync`. When the `reader.AdvanceTo` is called with two parameters, than in the next iteration the "observed" data will be returned again. In given implementation no data is marked as "consumed", and will be processed again and again with `TryReadLine` method. I think, here must be called method `reader.AdvanceTo` with one parameter, and only `buffer.End` must be specified, if I correctly understood the example's intention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5384a7-5e96-d977-7748-317a2c758f63
* Version Independent ID: 06e72212-a052-a351-0e0b-1b002ce214de
* Content: [I/O pipelines - .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines)
* Content Source: [docs/standard/io/pipelines.md](https://github.com/dotnet/docs/blob/main/docs/standard/io/pipelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Please provide a public sample on GitHub with the simplest possible project the reproduces your conjecture.

**Comment by obratim** [comment]
It is my bad, procedure `TryReadLine` from example gets `ref buffer` and changes it, so when later `reader.AdvanceTo(buffer.Start, buffer.End);` is called, it don't advances to start of the initial buffer.

I didn't do that when I tryed to write my code based on the example. Sorry.
