### ISSUE TITLE
Literary attribution needed

### ISSUE THREAD

**Issue by billwheaton1715** [dotnet/docs#30757]
The example for Verbatum String Literals in this uses a poetry snippet in it to demonstrate.
I am thinking that it is a copyright violation, though I adorethe fact that the page author has given a hat tip to the
literary arts, and I really appreciate that and encourage more of it in our craft.  

Here is the source of the reference,
The Eolian Harp
BY SAMUEL TAYLOR COLERIDGE
composed at clevedon, somersetshire
Found here:
https://www.poetryfoundation.org/poems/52301/the-eolian-harp

```My pensive Sara! thy soft cheek reclined
Thus on mine arm, most soothing sweet it is
To sit beside our Cot, our Cot o’ergrown
With white-flowered Jasmin, and the broad-leaved Myrtle...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
[Samuel Taylor Coleridge](https://en.wikipedia.org/wiki/Samuel_Taylor_Coleridge) died in 1834, so I don't see how it could be a copyright violation.

**Comment by BillWagner** [comment]
We should add a citation to that text in the comments. 

Thanks for pointing this out @billwheaton1715
