### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by jwerner77** [dotnet/docs#30763]
In the following paragraph it says:
_It's a bad programming style to change the state of the object by using the get accessor. For example, the following accessor produces the side effect of changing the state of the object every time that the _number field is accessed._
"the following accessor" refers to an example that is not there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322a60f9-0bd8-b432-653a-069c477a93fe
* Version Independent ID: dbc29edd-b142-f2d7-4824-dec9951f32c7
* Content: [Using Properties - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/using-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting that @jwerner77 

We removed that sample because we found that people were copying it, even though it's not recommended.
