### ISSUE TITLE
Incorrect upper limit for .NET Framework versions that can be run using 4.8

### ISSUE THREAD

**Issue by jalgaba** [dotnet/docs#30773]
https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10#net-framework-48

_.NET Framework 4.8 can be used to run applications built for the .NET Framework 4.0 through *4.7.2.*_

I think it should be

_.NET Framework 4.8 can be used to run applications built for the .NET Framework 4.0 through *4.8.*_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cef2db-41a9-f3e0-7387-98611e9d1158
* Version Independent ID: 2726f502-0742-4715-4fc3-18f882178429
* Content: [Install the .NET Framework on Windows 10 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10#additional-information)
* Content Source: [docs/framework/install/on-windows-10.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/on-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by marcelmedina** [comment]
Looking at this.
