### ISSUE TITLE
Do you have similar "re-train" example for binary classification?

### ISSUE THREAD

**Issue by philiplai** [dotnet/docs#30771]
I am trying to load a existing LightGbmBinary model (.zip) and retrain it with new data.  Just don't know how to make it work.  Any help will be greatly appriciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0366cc46-bc07-44fd-72d9-d37b40bd5eca
* Version Independent ID: 5c20d041-f946-d7c8-b0b5-7bee96e90282
* Content: [Re-train a model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/retrain-model-ml-net.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/retrain-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
LightGBM is not one of the supported algorithms that lets you incrementally retrain a model at this time. If that's something you'd be intererested in, I would encourage you to suggest it as a feature in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning/issues/new/choose) repo.
