### ISSUE TITLE
monkey image recognized as cat!

### ISSUE THREAD

**Issue by Getit567** [dotnet/docs#30780]
I input a monkey image then it outputs cat! How to increase accuracy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
ONNX is intended for inferencing using pretrained models and does not have the ability to train. There are a few options:

1. Try a different model. [ONNX Model repository](https://github.com/onnx/models#object-detection--image-segmentation-) has other models for tasks like object detection you may want to try.
2. Train your own model. Here are a few tutorials that may help you with that:
    a. [Model Builder Object Detection](https://docs.microsoft.com/dotnet/machine-learning/tutorials/object-detection-model-builder)
    b. [Model Builder Image Classification](https://docs.microsoft.com/dotnet/machine-learning/tutorials/image-classification-model-builder)
    c. [API Image Classification](https://docs.microsoft.com/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning)
