### ISSUE TITLE
Language or BCL data types #13976 - Type === Type

### ISSUE THREAD

**Issue by mcgolledge** [dotnet/docs#30800]
I missed the party, but the solution of using keywords when a type is required by the parser is inconsistent.

From a parsing perspective, a type name is always a type name, and a keyword is only sometimes a type name. Whenever a type name is needed in a .Net language, the type name will always work. But, if you are working in VB and C# "string" and "int" will only sometimes work. For a platform that is supposed to have consistent type usage across all languages, that is somewhat inconsistent.

They never asked the question, "Why do these keywords exist?"
I learned C# about 2001 having come from a C background, and I thought, oh, that's convenient, the language designers let me keep some of the type names I'm used to by defining them as aliases. If that was the only reason why these keywords exist, then this convention requires C# developers to use convenience items derived from a language many of them have never seen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2d591be-290e-62d1-e99a-a7d26af20ef8
* Version Independent ID: 7f85babc-6295-21dd-f194-dede663f9966
* Content: [C# identifier names](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names)
* Content Source: [docs/csharp/fundamentals/coding-style/identifier-names.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/identifier-names.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @mcgolledge 

Those are valid comments. However, the doc does accurately reflect the rules for the C# language. 

If you want to advocate for a change here, you can start a discussion in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repo. That's where the language designers work on proposed changes. This would be a large enough breaking changes that I'd doubt it would get much traction though.

**Comment by mcgolledge** [comment]
Thanks, but just to be clear, I was not advocating for a change to the language, I was advocating for a change to the convention referenced here, that effectively states C# keywords that are aliases for type names be used whenever a type name is needed that has such an alias.In any case, yeah, I doubt it gets much traction, but I wanted to throw it out there anyway.Thanks again,ChrisOn Aug 24, 2022 9:13 AM, Bill Wagner ***@***.***> wrote:
Hi @mcgolledge
Those are valid comments. However, the doc does accurately reflect the rules for the C# language.
If you want to advocate for a change here, you can start a discussion in the dotnet/csharplang repo. That's where the language designers work on proposed changes. This would be a large enough breaking changes that I'd doubt it would get much traction though.
