### ISSUE TITLE
TimeSpan.Parse behavior not aligned with MSDN documentation

### ISSUE THREAD

**Issue by zivkas** [dotnet/docs#3081]
## Issues with Existing Topics
TimeSpan.Parse has a bit of an odd behavior where if you do TimeSpan.Parse 23:00:00 you get 23 hours and if you do the same with 24:00:00 you get 24 **days**.
You can run this code:

        static void Main(string[] args)
        {
            TestTime("23:00:00");
            TestTime("24:00:00");
        }

        private static void TestTime(string timeSpanStr)
        {
            TimeSpan ts = TimeSpan.Parse(timeSpanStr);
            Console.WriteLine($"TimeSpan.Parse({timeSpanStr}) returns {ts.Days} Days and {ts.Hours} Hours");
        }

Here is the console output:
TimeSpan.Parse(23:00:00) returns 0 Days and 23 Hours
TimeSpan.Parse(24:00:00) returns 24 Days and 0 Hours

I opened this previous code issue: https://github.com/dotnet/corefx/issues/23845 but it was closed due to the behavior being as expected as there are heuristics at play.

Looking at the regex in the remarks section on MSDN: https://msdn.microsoft.com/en-us/library/se73z7b9(v=vs.110).aspx, 24:00:00 should not have been accepted as a valid input and it should have thrown a FormatException.

Can you please update the documentation to allow for a “d:hh:mm” input?

Thanks!

Ziv.

**Comment by mairaw** [comment]
@rpetrusha wanna take a look at this one?
