### ISSUE TITLE
IAsyncDisposable feedback

### ISSUE THREAD

**Issue by mxschmitt** [dotnet/docs#30836]
Its currently recommended to implement IDisposable as well when IAsyncDisposable is implemented.

Not always its possible to dispose objects sync, and only async e.g. with custom network protocol abstractions. So I suggest to reflect that in the docs to say that in cases were no sync dispose is available, IAsyncDisposable is enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @mxschmitt - you're not wrong, how would you propose phrasing that? Would you be interested in providing a PR to add that content?

**Comment by mxschmitt** [comment]
Hi @IEvangelist I created a draft here https://github.com/dotnet/docs/pull/30852, we can continue on the PR to improve the phrasing?
