### ISSUE TITLE
Argument WORKLOAD_ID looks wrong for the Repair command

### ISSUE THREAD

**Issue by Marusyk** [dotnet/docs#30837]
The doc says about **all** installed workloads

> The dotnet workload repair command reinstalls all installed workloads

but there is description of the `WORKLOAD_ID` argument - The workload ID of the workload to repair.
This argument doesn't work for the Repair command

![image](https://user-images.githubusercontent.com/9221694/186492610-623efaf7-7178-442a-9e45-6ebb8e30fafd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6867943c-0fae-a27d-e096-bc7f4cf6ecd1
* Version Independent ID: 8375c232-160b-215e-befa-6ae24f80ce76
* Content: [dotnet workload repair command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-repair)
* Content Source: [docs/core/tools/dotnet-workload-repair.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-workload-repair.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that - I'm removing the reference to that argument in #30838
