### ISSUE TITLE
Typo in section "Test the Release version of the library" step three (3)

### ISSUE THREAD

**Issue by pb-413** [dotnet/docs#30841]
In "[Test the Release version of the library](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?pivots=dotnet-6-0#test-the-release-version-of-the-library)" step three (3), I believe "Test Run > All Tests" ought to be "Test > Run All Tests"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET class library using Visual Studio - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?pivots=dotnet-6-0)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
Close/reopen to test labeler.

**Comment by tdykstra** [comment]
Thanks for reporting that, @pb-413
