### ISSUE TITLE
Wrong example for workload update command?

### ISSUE THREAD

**Issue by Marusyk** [dotnet/docs#30844]
The last code example shows the following

> dotnet workload update --download-to-cache ./workload-cache
> dotnet workload update --from-cache ./workload-cache

What is the `--download-to-cache` and `--from-cache`? They are not described in [Options](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-update#options)
and here
![image](https://user-images.githubusercontent.com/9221694/186519408-975bc28d-b4ca-497d-a626-996918556cec.png)

Should we document them or remove the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a897f7-e754-7555-6e38-598dc57675a4
* Version Independent ID: 9cac7161-c935-1696-a0e2-4e7f3973bf8e
* Content: [dotnet workload update command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-update)
* Content Source: [docs/core/tools/dotnet-workload-update.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-workload-update.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The example should be removed.
