### ISSUE TITLE
Documentation steps not working and no hopes of improvement and clarity on documentation ever become good

### ISSUE THREAD

**Issue by nareshnaidug5git** [dotnet/docs#30858]
What is this documentation ? All steps followed exactly mentioned in this article but still getting error and stuck. This is the reason people go for google search than your documentation :(

Severity	Code	Description	Project	File	Line	Suppression State
Error	DT1001	Service webapp has neither an image nor a build context specified. At least one must be provided.	docker-compose	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	201	

Also you mentioned docker-compose.yml is to be little tweaked. deleting everything from that and keep only port details you mean ?

If Microsoft is not doing documentation properly and make the dev community comfortable, everyone shift to other technologies that will curse you. Think seriously and do better job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @nareshnaidug5git, for reference you can refer to the source code present on github repo https://github.com/dotnet-architecture/explore-docker. We are reviewing the documentation and update it accordingly.

**Comment by erjain** [comment]
The PR has been merged to update the document, the issue can be closed now.

**Comment by IEvangelist** [comment]
Fixed by #31925
