### ISSUE TITLE
clarification needed for usage of System.SerializableAttribute

### ISSUE THREAD

**Issue by mm6502** [dotnet/docs#30850]
There are no serialization related attributes and no implementation of System.Runtime.Serialization.ISerializable interface in examples on this page.

Clarification is needed either in this article, or preferably in documentation for System.Runtime.Serialization, because documentation states following: 

for [ISerializable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=net-6.0):
> Any class that might be serialized must be marked with the [SerializableAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=net-6.0).

for [SerializableAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=net-6.0):
> Apply the [SerializableAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=net-6.0) attribute to a type to indicate that instances of this type can be serialized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-6-0)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by MSDN-WhiteKnight** [comment]
SerializableAttribute is used with binary serialization. It will be obsoleted in future .NET versions: https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md , so you don't need to wory about applying it on any of your types. The docs will be updated when the actuall type will be marked as obsolete.

**Comment by mm6502** [comment]
I have been writing software in c# for 20 years, so I kind of know this (still remember remoting...). 

The point is - it is not mentioned anywhere in the OLD serialization documentation (i.e. SerializationAttribute & ISerializable interface) nor in the NEW serialization documentation (i.e. System.Text.Json). When third party code checking tool (SonarQube in this case) report missing SerializationAttribute on a class (because it is meant to be serialized with System.Text.Json); I cannot file a problem pointing them to the documentation explaining the discrepancy in documentation (see the first post).

**Comment by MSDN-WhiteKnight** [comment]
>When third party code checking tool (SonarQube in this case) report missing SerializationAttribute on a class (because it is meant to be serialized with System.Text.Json); I cannot file a problem pointing them to the documentation explaining the discrepancy (see the first post).

You could just point to the design document i've linked. If SerializableAttribute is going to be obsoleted, it is already sufficient reason why code analysis tools should not report it as missing.

**Comment by mm6502** [comment]
Not an ideal solution, IMHO. 

The OLD documentation should be updated to reflect this (at least a link to mentioned document should be added). 

Think of new programmers learning c#. There is just no way they could get this right. They have no reason to look anywhere else than the official documentation. I did search for an answer before filing this issue, with no results. Who would think of searching "binaryformatter obsoletion" when the tool complains about SerializableAttribute and without a hint in the documentation? It does not help having [an article](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete) in "Breaking Changes" chapter, when there is no reason to look for it,

**Comment by gewarren** [comment]
Thanks @mm6502, this is good feedback.

**Comment by gewarren** [comment]
Related to https://github.com/dotnet/dotnet-api-docs/issues/935.
