### ISSUE TITLE
Confusing use of "default" for langversion

### ISSUE THREAD

**Issue by elezar42** [dotnet/docs#30860]
This document and [this one](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language) are both extremely confusing, because they use the term "default" to mean 2 different things for the langversion. There's the default that is used if no langversion is specified, and then there's a specific value named `default` that is a synonym for `latestmajor`. At least, I think that's how it's supposed to work. I'm making an educated guess here because it's not clearly documented. I understand that removing the value of `default` may not be an option because it would be a breaking change, but the document needs to be very clear about the difference between this value and the actual defaults that are used when no value is specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Your analysis is correct @elezar42 

I've added this to our backlog to address when we next update this article.

**Comment by luizhlelis** [comment]
Hello everyone!
Maybe I am mistaken, but I understood from the text that if no override is made, the compiler will use the latest language version compatible with your target framework. So, the `default that is used if no langversion is specified` and the `specific value named default that is a synonym for latestmajor` are exactly the same thing.

What are you expecting as a solution to this issue?

**Comment by elezar42** [comment]
@luizhlelis From my testing, using the specific value of `default` (or `latestmajor`) uses the latest version of the language supported by the compiler, without taking into account the target framework. So building a project that targets .NET 6 from the current version of VS2022 will use C# 10 if no LangVersion is specified, but will use C# 11 if LangVersion is set to `default` o `latestmajor`.
