### ISSUE TITLE
Please add requirements for 4.8.1

### ISSUE THREAD

**Issue by jasase** [dotnet/docs#30866]
This site does not list if an special requirements for the 4.8.1 release of .Net Framework are exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/main/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This will be addressed by #30619.
