### ISSUE TITLE
Main() inside Square class

### ISSUE THREAD

**Issue by StephenBBarr** [dotnet/docs#30872]
In the first code sample Main() is written inside the score of the Square class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adc020a-0a39-b4e2-902a-c0d776356b2e
* Version Independent ID: ff107003-885e-0876-bbaa-2fb25daa6369
* Content: [override modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/override#feedback)
* Content Source: [docs/csharp/language-reference/keywords/override.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/override.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @StephenBBarr 

Yes, the `Main` method is inside the `Square` class. That's legal.  

Are you recommending that we remove that?
