### ISSUE TITLE
Exception to rule in static constructor docs

### ISSUE THREAD

**Issue by MattLichter** [dotnet/docs#30876]
> "A static constructor runs before an instance constructor."

There is an important exception to this rule.  If a static initializer creates an instance of the class (e.g. to implement the Singleton pattern), the instance constructor will be invoked before the static constructor. There are two competing rules (initalizer before static constructor) and (static constructor before instance constructor), but it's impossible to satisfy both rules.

Test code
```
public class A
{
    public static void Main()
    {
        Debug.Log("A.Main");
        B.DoSomething();
    }
}

public class B
{
    private static B Instance = new B();
    private static int Foo = 42;

    static B()
    {
        Debug.Log("B Static Constructor");
        LoadStuff();
    }

    public B()
    {
        Debug.Log("B Instance Constructor");
        UseStuff();
    }

    public static void DoSomething()
    {
        Debug.Log("B.DoSomething");
    }

    private static void LoadStuff()
    {
        Debug.Log("B.LoadStuff");
    }

    private static void UseStuff()
    {
        Debug.Log("B.UseStuff");
    }
}
```

Log reveals "B Instance Constructor" before "B Static Constructor".  More importantly "B.UseStuff" is called *before* "B.LoadStuff", which has important ramifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3ed1c5-1f79-9234-beec-b5771c3fb3c0
* Version Independent ID: ac4f6361-70a7-fb43-101e-c12044f60896
* Content: [Static Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/static-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 291898](https://dev.azure.com/msft-skilling/Content/_workitems/edit/291898)

**Comment by BillWagner** [comment]
Thanks for raising this @MattLichter 

You are correct. The standard does allow this behavior, and our docs should make that clear.
