### ISSUE TITLE
Update (and correct) the existing `System.Text.Json` article on polymorphism

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#30879]
Update (and correct) the existing `System.Text.Json` article on polymorphism:
https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-polymorphism

For additional information and context, see https://gist.github.com/krwq/a24138195a47fc248039314e8708dc40

**Comment by gewarren** [comment]
@IEvangelist offered to take on this work, so assigning over to him.

**Comment by eiriktsarpalis** [comment]
For completeness, there's also the section on polymorphism in the Preview 5 announcement:

https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/#polymorphism

The STJ blog will more or less use the same content so we might want to use this one for reference.
