### ISSUE TITLE
Please mention the .Net version

### ISSUE THREAD

**Issue by taleleuma** [dotnet/docs#30887]
Please mention the .Net version applicable to this example. For sure, this example doesn't work using latest .Net Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @taleleuma, Thanks for posting here. The .NET version currently in use is .NET 6, can you share the exact issue you are getting with .NET 6?

**Comment by taleleuma** [comment]
> Hi @taleleuma, Thanks for posting here. The .NET version currently in use is .NET 6, can you share the exact issue you are getting with .NET 6?

With no mention of .Net version, I was trying the latest version of .Net Framework i.e. 4.8.x. The article is not applicable to .Net Framework as you have mentioned above. That's the point I am making. Article needs to mention about .Net 6.
.net 6 is not a part of ".net Framework"

**Comment by erjain** [comment]
Hi @taleleuma, thanks for the recommendation. The (index page)[https://learn.microsoft.com/en-us/dotnet/architecture/microservices/] mentions the .NET version. I believe the issue can be closed now.

**Comment by erjain** [comment]
The issue can be closed.
