### ISSUE TITLE
[Question] Misunderstands "code that is asynchronously waiting for a canceled task through use of language features continues to run"

### ISSUE THREAD

**Issue by anchurcn** [dotnet/docs#30896]
> Any code that is asynchronously waiting for a canceled task through use of language features ***continues to run*** but receives an [OperationCanceledException](https://docs.microsoft.com/en-us/dotnet/api/system.operationcanceledexception) or an exception derived from it.

I don't know what it means. 

I writes a demo to help me to understand but it only prints out "start".

```csharp
public async Task CanceledTask()
. {
.     throw new TaskCanceledException();
. }
> public async Task ExceptionTask()
. {
.     throw new InvalidOperationException(); 
. }
public async Task TestAsync()
. {
.     WriteLine("start");
.     await CanceledTask();
.     WriteLine("Canceled task completed");
.     await ExceptionTask();
.     WriteLine("Exception task completed");
. }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40c0699-0e7c-e20d-98c1-76f0520ab9c2
* Version Independent ID: 0fc31902-0055-f9e8-a228-e7a0ce384e35
* Content: [Task-based Asynchronous Pattern (TAP): Introduction and overview](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap)
* Content Source: [docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md](https://github.com/dotnet/docs/blob/main/docs/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
I think this is referring specifically to asynchronous (TAP) methods that accept a [CancellationToken](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-6.0). If there is a cancellation request and the TAP method ends the work and returns a task in the `Canceled` state, then the calling/awaiting code continues to run. Hopefully @BillWagner can explain further if needed.

**Comment by BillWagner** [comment]
Hi @anchurcn 

We should clarify this language. The phrase "receives an `OperationCancelledException` ..." isn't as clear as it should be. When code awaits a task in the `Canceled` state, that exception is *thrown*. the code awaiting the task must catch the exception, or it will propagate up the call stack.

**Comment by anchurcn** [comment]
@BillWagner 
By learning and practicing, I seems to be clear.
```csharp
public async Task TestAsync()
{
await Step1Async();
Step2();
}
```
Previous method is some magic of following.
So I guess the doc means we can continue to run Step2, so the exception on Step1 can be caught on Step2.
```csharp
public Task TestAsync()
{
return Step1Async().ContinueWith(Step2);
}
```
So we can write TAP code to do things like sync control flow.
Any code after Step1 is wrap to Step2 and put into ContinueWith() and on internal view it look like catch the exception on Step2.
```csharp
public async Task TestAsync()
{
try{
await Step1Async();
}catch(Exception e)
{
 }
Step2Internal();
}
```

**Comment by BillWagner** [comment]
that's close. You'd need to write the catch clause in `TestAsync` the way you have it above. If you don't include the try / catch blocks, The exception thrown when `Step1Async` is cancelled prevents `Step2Internal` from ever being called.

That's why you original example only printed "start"

**Comment by anchurcn** [comment]
Thanks for your help @BillWagner.
Because our docs are talking TAP on a higher level, does we need to use more accurate words on the docs?
