### ISSUE TITLE
[Breaking change]: RuntimeInformation.OSArchitecture return value under emulation

### ISSUE THREAD

**Issue by jkotas** [dotnet/docs#30894]
### Description

`RuntimeInformation.OSArchitecture` returned incorrect value under emulation.

### Version

.NET 7 Preview 6

### Previous behavior

`System.Runtime.InteropServices.RuntimeInformation.OSArchitecture` returned `Architecture.x64` in emulated processes on Windows Arm 64-bit and macOS Apple Silicon systems.

### New behavior

`System.Runtime.InteropServices.RuntimeInformation.OSArchitecture` returns `Architecture.Arm64` in emulated processes on Windows Arm 64-bit and macOS Apple Silicon systems.

### Type of breaking change

- [X] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

The previous behavior was incorrect.

### Recommended action

Code that expects the process architecture should be changed to call `System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture` instead.

### Feature area

Interop

### Affected APIs

System.Runtime.InteropServices.RuntimeInformation.OSArchitecture

**Comment by hamarb123** [comment]
@jkotas, I know this is the wrong issue, but I just wanted to say that https://github.com/dotnet/runtime/pull/52639 doesn't have a breaking change doc made or in the making afaik, but it is supposed to have one.

**Comment by jkotas** [comment]
> https://github.com/dotnet/runtime/pull/52639 doesn't have a breaking change doc made or in the making afaik, but it is supposed to have one.

It has `needs-breaking-change-doc-created` label. [Area owners](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) are expected to go over all PRs marked with this label and make sure that the breaking change docs are created.

@danmoseley Is there a dead-line for creating the breaking change docs?

**Comment by danmoseley** [comment]
I think @jeffhandley  will ask someone to chase them up for the release in a little bit, like last year.
