### ISSUE TITLE
.NET Framework 4.8.1

### ISSUE THREAD

**Issue by rtssrl** [dotnet/docs#30900]
No info about .NET Framework 4.8.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements - .NET Framework](https://docs.microsoft.com/en-US/dotnet/framework/get-started/system-requirements)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/main/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The details will be added by #30619.
