### ISSUE TITLE
Example raises S3925 warning

### ISSUE THREAD

**Issue by KurtP20** [dotnet/docs#30919]
Hi, I used the example code to define a custom `Exception` and the SonarAnalyzer.CSharp reports a [S3925](https://rules.sonarsource.com/csharp/RSPEC-3925) major warning. Could you please update the example so that it conforms to this rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041f6b4c-2b7e-5332-f24e-12af7a5b07aa
* Version Independent ID: e9c2287f-1c4e-ee07-a1ff-77a3f07ce1a4
* Content: [How to: Create User-Defined Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions?source=docs)
* Content Source: [docs/standard/exceptions/how-to-create-user-defined-exceptions.md](https://github.com/dotnet/docs/blob/main/docs/standard/exceptions/how-to-create-user-defined-exceptions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by svick** [comment]
I believe that rule is outdated, especially considering [the plans to deprecate everything related to binary serialization](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md). In particular:

> Any new `Exception`-derived types that are defined in a library which is not available to netstandard2.0 callers will not be annotated with `[Serializable]`.

**Comment by KurtP20** [comment]
Thanks! I contacted SonarSource and will happily supress the warning.
