### ISSUE TITLE
Does IHttpClientFactory control HttpClient instances ?

### ISSUE THREAD

**Issue by a510** [dotnet/docs#30920]
The documentation of the `IHttpClientFactory` seems self-contradictory when it says:
> ... and once the client is created, the factory no longer has control over it.

Meanwhile in [this page](https://docs.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#httpclient-lifetime-management) it says:
> ... IHttpClientFactory tracks and disposes resources used by HttpClient instances.

Am I missing something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a42e9c6-2624-e047-ed1c-03ec047b538a
* Version Independent ID: 3b1dd30f-82a8-2526-bd51-fb6401c52e81
* Content: [HttpClient guidelines for .NET - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/http/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/http/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
This is not a contradiction. These statements are both accurate:

- ... once the client is created, the factory no longer has control over it.
- ... `IHttpClientFactory` tracks and disposes resources used by `HttpClient` instances.

It is true, that a new `HttpClient` is created and returned, and when the consumer has it - the factory no longer has control over it. However, the resources used to create the `HttpClient` are tracked and disposed of automatically. Specifically, the `HttpMessageHandler`. @gewarren do you think we should clarify this somehow?
