### ISSUE TITLE
CA1851  doesn't seem to be a legitimate rule recognized by Visual Studio

### ISSUE THREAD

**Issue by sjd2021** [dotnet/docs#30936]
This page references a rule that doesn't seem to actually be recognized in Visual Studio. After copying the examples over, the rule isn't present by default nor when added to my working .editorconfig file using the format listed on the page (`dotnet_diagnostic.CA1851.severity = warning`) live or upon build. Is it possible that this page is presenting incorrect information or would the problem be with the Visual Studio product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc5942f-3f78-8def-7252-3d0a43a1d8e7
* Version Independent ID: 64af62bb-d001-75cb-aa40-21646c27144e
* Content: [CA1851: Possible multiple enumerations of 'IEnumerable' collection - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1851)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1851.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1851.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I was able to trigger the warning in a Visual Studio 2022 Preview project (it seems that the analyzer CA1851 did not ship with .NET 6, so you'll have to use a .NET 7 preview version). Here's the code that triggered the warning:

```csharp
List<int> input = new List<int>() { 1, 2, 3 };
IEnumerable<int> selection = input.Where<int>(input => input > 1);

var count = selection.Count();
foreach (var i in selection) { }
foreach (var i in selection) { }
```

**Comment by sjd2021** [comment]
@gewarren Thank you for the clarification and also for updating the documentation to reflect that. Also, I'm a fan of anyone who uses semi-colons properly. 😄

**Comment by sjd2021** [comment]
@gewarren Is there a way that I can add this rule to a .NET 6 project  (better yet, all .NET 6 projects in a solution) any sort of way? It seems like one that could be backwards compatible. I haven't imported any rules explicitly before.

**Comment by gewarren** [comment]
> @gewarren Is there a way that I can add this rule to a .NET 6 project (better yet, all .NET 6 projects in a solution) any sort of way? It seems like one that could be backwards compatible. I haven't imported any rules explicitly before.

I thought it might work if you set `AnalysisLevel` to `7` in your .NET 6 project file. But I just tried it and it didn't seem to work. @Youssef1313 Any ideas on how to use a .NET 7 analyzer in a .NET 6 project?

**Comment by Youssef1313** [comment]
It should work when using the analyzers from 7.x NuGet package.

**Comment by sjd2021** [comment]
@Youssef1313  Is it this one?

![image](https://user-images.githubusercontent.com/84007094/188047847-1f953e03-a9e5-4351-b216-d4354715e549.png)

I've added it, rebuilt, etc. to no avail just yet. I also tried setting AnalysisLevel to 7.0 in the csproj file

**Comment by Youssef1313** [comment]
@mavasani @Cosifne Any idea why CA1851 doesn't show up in Solution Explorer? (I checked both `Microsoft.CodeAnalysis.NetAnalyzers` and `Microsoft.CodeAnalysis.CSharp.NetAnalyzers`)

I also checked that the dll `Microsoft.CodeAnalysis.NetAnalyzers` for `preview1.22362.3` contains the abstract base class and `Microsoft.CodeAnalysis.CSharp.NetAnalyzers` contains the actual implementation with `DiagnosticAnalyzer` attribute

**Comment by Cosifne** [comment]
I don't know how Solution explorer works with the analyzer @jmarolf might be an expert in this area.
But for the original question @sjd2021 asked, I can use the analyzer in net6.0 project by adding the preview analyzer package from NuGet.

I am using VS 17.3.3. And you will need to setup this in the editorconfig
dotnet_diagnostic.CA1851.severity = suggestion (or whatever level you like)

**Comment by sjd2021** [comment]
@Cosifne  I was just showing the solution explorer view to show that I had pulled in the latest and couldn't see the squigglies inline nor an indication in that view that the rule was being leveraged. I already had that diagnostic line but specified as warning too. It just seems like nothing is picking it up. Also, I've upgraded to the latest version of VS to no avail :(

![image](https://user-images.githubusercontent.com/84007094/188296546-9ad204a2-58ce-49bf-9b2c-7a4c4e1c24b7.png)

![image](https://user-images.githubusercontent.com/84007094/188296580-92e741aa-4e52-40a6-80a0-a4e180bb08cc.png)

**Comment by Cosifne** [comment]
Hi @sjd2021 
Have you set the correct value in editorconfig?
Here is the code sample I used.
![image](https://user-images.githubusercontent.com/24360909/188702187-a8f12d7a-e94d-4ec8-ae8a-6f138f37fa84.png)
The project file (I just create it from template, and add the preview nuget packages)
![image](https://user-images.githubusercontent.com/24360909/188702316-aa3da64f-db3a-41ce-a9cd-2be679986988.png)
The editorconfig I added
<img width="551" alt="image" src="https://user-images.githubusercontent.com/24360909/188702482-4f6cd125-caed-4052-96be-ed4bdecd24f0.png">

**Comment by sjd2021** [comment]
![image](https://user-images.githubusercontent.com/84007094/188707920-7f95d353-51cf-4eb2-aac6-aa6efca49662.png) 

![image](https://user-images.githubusercontent.com/84007094/188722779-f6e49b06-af71-46f4-97d1-9e11782986b0.png)

@Cosifne can you spot any discrepancies?

**Comment by Cosifne** [comment]
Does the underlying yellow line give any hints? Also I can see CA1851 under the editorconflig UI
![image](https://user-images.githubusercontent.com/24360909/188729118-724957b2-10d9-4a44-af5b-c495c0aeb0ab.png)
Does that apply to you?
