### ISSUE TITLE
Verbatim interpolated strings are missing in the Interpolated Strings topic

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3094]
URL: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interpolated-strings

This was identified by a LiveFyre comment.

Spec contains the info about them: https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md#interpolated-string-literals

/cc @BillWagner

**Comment by mairaw** [comment]
I'd also add that the topic doesn't indicate when that feature was introduced. Should it?

**Comment by paulomorgado** [comment]
> I'd also add that the topic doesn't indicate when that feature was introduced. Should it?

Yes!

**Comment by paulomorgado** [comment]
There are character encoding issues in [this line](https://github.com/dotnet/docs/blob/03d1e3f0897713e25be7d7f893861a3eb4dac211/samples/snippets/csharp/language-reference/keywords/interpolated-strings2.cs#L65).

**Comment by mairaw** [comment]
I've fixed the character encoding issue @paulomorgado.
 
One more thing I think we should add to that topic is showing how you can format your output using interpolated strings. See this PR (#3210) and comment that prompted me to add this here: https://github.com/dotnet/docs.zh-cn/issues/39#issuecomment-331601900. Let me know if you'd prefer a separate issue for this @BillWagner.

**Comment by paulomorgado** [comment]
I think it's important to add interpolated verbatim strings to the article.
