### ISSUE TITLE
[Breaking change]: Socket.End methods no longer throw ObjectDisposedException

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/docs#30977]
### Description

Starting from .NET 7, `System.Net.Sockets.Socket.End*` methods (e.g. `EndSend`) throw `SocketException` instead of `ObjectDisposedExcption` if the socket is closed.

### Version

.NET 7 Preview 7

### Previous behavior

`System.Net.Sockets.Socket.End*` methods were throwing `ObjectDisposedException` for closed sockets.

### New behavior

`System.Net.Sockets.Socket.End*` methods throw `SocketException` with `SocketErrorCode` set to  `SocketError.OperationAborted`.

### Type of breaking change

- [X] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Starting with .NET 6.0, the legacy Socket APM (Begin/End) APIs are backed with Task based implementation as part of our effort to consolidate and simplify the Socket codebase. Unfortunately, it turned out that the 6.0 implementation was leaking [unobserved](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception?view=net-6.0) `SocketException`-s [even when used correctly](https://github.com/dotnet/runtime/issues/61411#issuecomment-968585218) (meaning that the user code makes sure that the End methods are always invoked, including the case when the socket is closed).

Changing the behavior was a simple a straightforward way to make sure that no unobserved exceptions are leaked in such cases.

### Recommended action

All code that expects (catches) `ObjectDisposedException` thrown from any of the `Socket.End*` methods should be changed to expect `SocketException` and refer to `SocketException.SocketErrorCode` to query the underlying reason.

Note: As mentioned earlier, APM code should *always* make sure that the corresponding End methods are invoked after the Begin methods, even if the socket is closed.

### Feature area

Networking

### Affected APIs

System.Net.Sockets.Socket.EndConnect
System.Net.Sockets.Socket.EndDisconnect
System.Net.Sockets.Socket.EndSend
System.Net.Sockets.Socket.EndSendFile
System.Net.Sockets.Socket.EndSendTo
System.Net.Sockets.Socket.EndReceive
System.Net.Sockets.Socket.EndAccept

**Comment by antonfirsov** [comment]
@gewarren I assume we should also file a PR to dotnet-api-docs, changing the [exception descriptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.endconnect?view=net-6.0#exceptions) ?

**Comment by gewarren** [comment]
> @gewarren I assume we should also file a PR to dotnet-api-docs, changing the [exception descriptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.endconnect?view=net-6.0#exceptions) ?

Yes, that would be great!
