### ISSUE TITLE
Probably incorrect configuration keys names in <System.Windows.Forms.ApplicationConfigurationSection> documentation

### ISSUE THREAD

**Issue by MykolaKovalchuk** [dotnet/docs#30986]
I believe there is errors in names of 2 settings on this page:
1. "AnchorLayout.DisableSinglePassControlScaling" should be "AnchorLayout.DisableHighDpiImprovements"
2. "MonthCalendar.DisableSinglePassControlScaling" should be "MonthCalendar.DisableHighDpiImprovements"

I base my opinion on source/disassembled code of System.Windows.Forms.DpiHelper.InitializeDpiHelperQuirks() for .Net 4.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7262cc-302b-ac30-7b91-2512d3ca944a
* Version Independent ID: e8808c6c-b980-e8a9-c588-232159961525
* Content: [Windows Forms Add Configuration Element - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element)
* Content Source: [docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@RussKie Can you confirm whether these settings should be updated?

**Comment by RussKie** [comment]
@dreddy-work are you able to help here?

**Comment by dreddy-work** [comment]
That is not correct. Both configuration switches are valid. @MykolaKovalchuk , if you are inspecting the source code, check in System.Windows.Forms.dll disassembly for its usage. It seems you are looking into System.Design.dll only.
