### ISSUE TITLE
Could common type system mention record type?

### ISSUE THREAD

**Issue by Owenll66** [dotnet/docs#30987]
Is worth mentioning the recently introduced [Record Type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record ) in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa10fddf-a6ff-0b70-dc4d-94d1f9ac0f57
* Version Independent ID: 402b82b0-5037-9117-50ef-e2c10c9705a6
* Content: [Common Type System](https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-system)
* Content Source: [docs/standard/base-types/common-type-system.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/common-type-system.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by svick** [comment]
I don't think record types should be mentioned here. Record types are a C#-specific concept and this article is meant to be about .Net types (i.e. what's actually present in metadata) and records don't exist at that level (the C# compiler compiles records into classes or structures).

**Comment by BillWagner** [comment]
Good question @Owenll66 

@svick 's comment is correct: You can think of `record` as *modifying* either a `class` or `struct` definition. By adding the `record` modifier, you instruct the compiler to add a number of methods to support value-based equality.

I'll close this as an answered question.
