### ISSUE TITLE
.NET 6 does not seem to be included in Ubuntu 22.04

### ISSUE THREAD

**Issue by droyad** [dotnet/docs#30988]
The message ".NET 6 is included in Ubuntu 22.04." is confusing. I did a fresh install of Ubuntu WSL and ran `dotnet` but it was not found. I still had to follow the instructions on the page to install it. Does "included" mean something other than installed by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry, that should read that it's included in the default apt feeds.
