### ISSUE TITLE
Does Win7 support single file deployment now?

### ISSUE THREAD

**Issue by lausannel** [dotnet/docs#31008]
**Issue description**
I'm using .NET 6 SDK 6.0.400 now.
I learned from the MS doc here https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli that "Single file deployment isn't compatible with Windows 7." and I tracked from the PRs to know it was added to the doc by this PR  #25408. I learned about that it was because some missing dll files.

However, I learned from another issue https://github.com/dotnet/runtime/issues/62453  @agocke that Single file deploymeny in Win7 was supported now.

Which one should I believe?

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

</details>

**Comment by lausannel** [comment]
I tested that on an old Windows 7, it worked well. But I'm not sure if every program will work well

**Comment by lausannel** [comment]
Could pls resolve this? @agocke, thanks very much

**Comment by gewarren** [comment]
Closing per request.
