### ISSUE TITLE
Field (minimumBalance) typo under MakeWithdrawal() in BankAccount Class

### ISSUE THREAD

**Issue by mtagelsir** [dotnet/docs#31006]
Hi,
 Under the MakeWithdrawal() method in the BankAccount type, 
the field name should be (_minimumBalance) not (minimumBalance):

```
 public void MakeWithdrawal(decimal amount, DateTime date, string note)
    {
        if (amount <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(amount), "Amount of withdrawal must be positive");
        }
        if (Balance - amount < minimumBalance)
        {
            throw new InvalidOperationException("Not sufficient funds for this withdrawal");
        }
        var withdrawal = new Transaction(-amount, date, note); // note the minus sign
        allTransactions.Add(withdrawal);
    }
```

(_minimumBalance) is the correct field name, while (minimumBalance) is a local variable/parameter defined in the constructor.

B.R.
Mo
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/oop)
* Content Source: [docs/csharp/fundamentals/tutorials/oop.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/oop.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @mtagelsir 

We'll address it this month.
