### ISSUE TITLE
Statement about specifying array size when declaring an array is incorrect

### ISSUE THREAD

**Issue by Treit** [dotnet/docs#31026]
[This page](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) says:

> If` you specify an array size, you have to initialize the elements one at a time.

```
var vowels3 = new string[5];
vowels3[0] = "a";
vowels3[1] = "e";
// And so on.
```

This is not correct. The following code is perfectly valid:

```
var vowels3 = new string[5] { "a", "e", "i", "o", "u" };
```

Edit by @BillWagner  Add document block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Treit 

That statement and example should be removed.

I've added this to our backlog to address when we next update this article.
