### ISSUE TITLE
Cannot add Debug and Trace logging to the ColorConsoleLogger

### ISSUE THREAD

**Issue by dnovatchev** [dotnet/docs#31025]
Based on this documentation article: https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider

I want to add Debug and Trace logging to this code, but have not been successful.

I changed `appsettings.json` to this:

```c#
{
    "Logging": {
        "ColorConsole": {
            "LogLevels": {
                "Trace": "Yellow",
                "Debug": "Blue",
                "Information": "DarkGreen",
                "Warning": "Cyan",
                "Error": "Red"
            }
        }
    }
}
```
 I changed `ColorConsoleLoggerConfiguration.cs` to this:
 
 ```c#
using Microsoft.Extensions.Logging;

public class ColorConsoleLoggerConfiguration
{
    public int EventId { get; set; }

    public Dictionary<LogLevel, ConsoleColor> LogLevels { get; set; } = new()
    {
        //[LogLevel.Information] = ConsoleColor.Green
        [LogLevel.Trace] = ConsoleColor.Magenta
    };
}
```

I added to Program.cs calls to logger.LogDebug() and logger,LogTrace() like in the following snippet:

```c#
var logger = host.Services.GetRequiredService<ILogger<Program>>();

logger.LogDebug(1, "Does this line get hit?");    // Not logged
logger.LogInformation(3, "Nothing to see here."); // Logs in ConsoleColor.DarkGreen
logger.LogWarning(5, "Warning... that was odd."); // Logs in ConsoleColor.DarkCyan
logger.LogError(7, "Oops, there was an error.");  // Logs in ConsoleColor.DarkRed
logger.LogTrace(5!, "== 120.");                   // Not logged
```

I even put breakpoints **everywhere**

Still the result is that the calls to LogDebug() and LogTrace() don't do anything and don't hit any breakpoint. :( 

**My question**: What shoulg I do to make logging at the levels of Debug and Trace work?

Thank you in advance for your help!

Dimitre Novatchev
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider - .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider#feedback)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by dnovatchev** [comment]
I have found a solution. 

The article will benefit from adding a more complete configuration.

I used:

```json
{
    "Logging": {
        "ColorConsole": {
          "LogLevels": {
            "Trace": "Yellow",
            "Debug": "DarkYellow",
            "Information": "DarkGreen",
            "Warning": "Cyan",
            "Error": "Red"
          },
          "LogLevel": {
            "Default": "Trace"
          }
        }
    }
}
```

**Comment by IEvangelist** [comment]
Hi @dnovatchev - thank you for posting this issue, much appreciated. I'll work on this soon and implement your suggestions for improvement. Thanks again
