### ISSUE TITLE
Chinese document on "How to: Pad a Number with Leading Zeros"

### ISSUE THREAD

**Issue by ITNoobb** [dotnet/docs#31034]
![image](https://user-images.githubusercontent.com/40918209/188797979-1903a70d-ad8a-4c03-ac50-f374aa95ac89.png)
Hi teams, above captue is chinese explanation for "To display the integer as a hexadecimal value", but now both statement is talking about "Decimal value". It makes people confuse, and I realized this mistake once I switch to English website, then I know the second one is talking about hexadecimal value, not decimal value, please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5f139b-5e94-9793-5cd1-048a395d026c
* Version Independent ID: 474649e3-7f9b-be7b-5e0c-58046c76ee24
* Content: [How to: Pad a Number with Leading Zeros](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-pad-a-number-with-leading-zeros)
* Content Source: [docs/standard/base-types/how-to-pad-a-number-with-leading-zeros.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/how-to-pad-a-number-with-leading-zeros.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @khoiph1 I see you mentioned on issues similar to this, is this something you can handle?

**Comment by adegeo** [comment]
@dankodima1 You should open a new issue. However, I don't understand what you're saying. The documentation for this "how to" is already short.

**Comment by v-alje** [comment]
This issue appears to be fixed: https://learn.microsoft.com/zh-cn/dotnet/standard/base-types/how-to-pad-a-number-with-leading-zeros 
![image](https://user-images.githubusercontent.com/4665434/227619681-53847af7-e31b-4ac1-91db-b4649956b68c.png)
