### ISSUE TITLE
no link for Reflection

### ISSUE THREAD

**Issue by birbilis** [dotnet/docs#31055]
at "Features" section, the "Reflection" doesn't have a link whereas all other features' items have one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad87897-30cc-e639-b91a-b3800269f7fe
* Version Independent ID: 9d3015b4-cba1-0956-9ec7-4154dbb74d93
* Content: [.NET (and .NET Core) - introduction and overview](https://docs.microsoft.com/en-us/dotnet/core/introduction)
* Content Source: [docs/core/introduction.md](https://github.com/dotnet/docs/blob/main/docs/core/introduction.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by MSDN-WhiteKnight** [comment]
There's no documentation about reflection on .NET/.NET Core currently (related: #29741). Should this link to .NET Framework reflection docs for now?
