### ISSUE TITLE
Label description for sample data incorrect

### ISSUE THREAD

**Issue by bradseay** [dotnet/docs#31052]
The description for the column in the dataset describing the different sentiments is incorrect.  If you open the linked file, you'll quickly see that the description is backwards:

Section: Example Datasets
Scenario: Classification
Example: Predict sentiment of website comments
Current Text: "0 when negative sentiment, 1 when positive"

Fix: "1 when negative sentiment, 0 when positive"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35b206b-87eb-cca0-8854-d1fcd6d8732f
* Version Independent ID: 11c11e7b-5c02-ee1a-e17d-f5cb4cafbab8
* Content: [What is Model Builder and how does it work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder)
* Content Source: [docs/machine-learning/automate-training-with-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/automate-training-with-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

---
[Associated WorkItem - 261100](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261100)

**Comment by gewarren** [comment]
Thanks @bradseay!
