### ISSUE TITLE
Duplicated content (System.CommandLine)

### ISSUE THREAD

**Issue by lonix1** [dotnet/docs#31080]
There is a copy-paste error on this page - the ["File system types"](https://docs.microsoft.com/en-us/dotnet/standard/commandline/model-binding#file-system-types) section's two code blocks are repeated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75416731-e081-9d04-e683-e0fba0d6b388
* Version Independent ID: 1eec00b7-55ba-34ce-225e-3549b9de4b25
* Content: [How to bind arguments to handlers in System.CommandLine](https://docs.microsoft.com/en-us/dotnet/standard/commandline/model-binding)
* Content Source: [docs/standard/commandline/model-binding.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/model-binding.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that - I'm fixing it in #31093
