### ISSUE TITLE
Mixed statements about namespace for extension methods

### ISSUE THREAD

**Issue by tomahg** [dotnet/docs#31084]
This document https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors
says: 

> DO NOT use the Microsoft.Extensions.DependencyInjection namespace for non-official Microsoft packages.

But this document https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0
says

> We recommended that apps follow the naming convention of creating extension methods in the [Microsoft.Extensions.DependencyInjection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection) namespace.

What is actually the Microsoft recommendation? Should we use Microsoft.Extensions.DependencyInjection for our own extension methods or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors - .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @tomahg - thank you for posting this issue. I'm going to bring this up to the team and I'll get back to you soon, thanks again.

**Comment by IEvangelist** [comment]
Hi again @tomahg - after talking with both teams, we've come to the conclusion that we're no longer recommending using any Microsoft-owned namespaces for authors. With that said, you'll find a PR where I propose removing this recommendation from the ASP.NET docs. https://github.com/dotnet/AspNetCore.Docs/pull/27018

**Comment by tomahg** [comment]
That quicker than expected! Thanks! 😄

**Comment by ggirard07** [comment]
Same issue still exists in [Tutorial: Use dependency injection in .NET - Register services for DI](https://github.com/dotnet/docs/blob/a05883d27092b2732b89c1d42e6fe3ddf113de92/docs/core/extensions/dependency-injection-usage.md?plain=1#L101C1-L104C130)
