### ISSUE TITLE
F# Compiler Options: incorrect information about <output-filename> for -a and --target

### ISSUE THREAD

**Issue by nightroman** [dotnet/docs#3108]
https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/compiler-options.md

    -a**<output-filename>**
    Generates a library and specifies its filename. This option is a short form of --target:library**<filename>**.

    --target:[exe | winexe | library | module ] <output-filename>
    Specifies the type and file name of the generated compiled code.
    ...

I think `<output-filename>` is either not supported or the docs should tell how to use it.

But it looks like

- `-a` is a simple switch;
- `--target` is a named parameter with one value, not two

and the output file name is specified by the provided option `-o|--out`.

The documentation refers to [/target (C# Compiler Options)](https://msdn.microsoft.com/library/6h25dztx.aspx).
This page does not tell anything about extra `<output-filename>`.

Simple tests show errors that `-a` does not expect a parameter:

    > fsc -a z.dll Q1.fs
    error FS2020: The assembly 'z.dll' is listed on the command line. Assemblies should be referenced using a command line flag such as '-r'.
    
    > fsc -a:z.dll Q1.fs
    error FS0243: Unrecognized option: '-a'

**Comment by mairaw** [comment]
@cartermp can you take a look at this issue?

**Comment by mairaw** [comment]
We're clearing up Quarter 4 issues @cartermp. Any idea when you can get this addressed?

**Comment by cartermp** [comment]
As per the usage `--target:library file1.fs`, usage should be `-a file1.fs`. I renamed "output-file" to "file" in the docs to clarify this.

**Comment by nightroman** [comment]
@cartermp Could you please give the final text?. In `-a file1.fs`, `file1.fs` has nothing to do with `-a` because `-a` is a switch, complete thing on its own. Or am I missing something?

**Comment by cartermp** [comment]
As per the [source code](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CompileOptions.fs#L1020) the `-a` switch is a shorthand form of `--target:library`, as per what the documentation currently says.

**Comment by nightroman** [comment]
The why my example in the very first post does not work per documentation and source code?

**Comment by cartermp** [comment]
Have you tried `-a file1.fs`?

**Comment by nightroman** [comment]
> Have you tried -a file1.fs?

Why? This command means:
- `-a` build class library
- from `file1.fs`

Are you saying it is the same as `--target file1.fs`?

The link to the source code shows that it is not the same as parameter `--target`, IMHO.

**Comment by nightroman** [comment]
Like I said the documentation should be

> `-a`
Tells to generate a class library.

This is how the compiler works in reality.

**Comment by nightroman** [comment]
I am probably wrong. The documentation about `--target` is updated and looks correct now (not `file`).
So yes `-a` is a shortcut of `--target:library`. But the `file` part should be removed from the help completely. `-a` is a switch, there is no `file` after it.

**Comment by nightroman** [comment]
This 

    -a**<filename>** | Generates a library and specifies its filename. This option is a short form of --target:library**<filename>**.

should be

    -a | Generates a library. This option is a short form of --target:library.

**Comment by nightroman** [comment]
And help about `--target` is not correct, too
 

    --target:[exe \| winexe \| library \| module ] <output-filename> | Specifies the type and file name of the generated compiled code. ...

It does specify *the type* but not *the type and file name*.

**Comment by mairaw** [comment]
Reopening so PR #9495 can close this.
