### ISSUE TITLE
mohammed

### ISSUE THREAD

**Issue by Mohammed-EL-Zehery** [dotnet/docs#31108]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96aef419-de1f-a341-3f19-4ed99eb36412
* Version Independent ID: 40ddc3ce-a004-1a4c-37e1-1c45eaa8f35a
* Content: [Install .NET Framework 3.5 on Windows 11, 10, 8.1, 8 - .NET Framework](https://docs.microsoft.com/en-gb/dotnet/framework/install/dotnet-35-windows)
* Content Source: [docs/framework/install/dotnet-35-windows.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/dotnet-35-windows.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Mohammed-EL-Zehery** [comment]
jjhh

**Comment by adegeo** [comment]
Hello! It looks like you opened this by mistake. I'll close it.
