### ISSUE TITLE
Add .Net 5.0 support details to our documentation

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#31101]
**Help us make content visible**
lifecycle, support, net5

**Describe the new article**
While .NET 5 went out of support in May, the .NET 5.0.2xx and 5.0.4xx SDKs within Visual Studio did not. This was done because .NET Core 3.1 is still in support in Visual Studio 16.9 and 16.11 and targeting 3.1 for development requires a .NET SDK.  Rather than try to pull in a different SDK or force customers to install an out of support SDK, we decided to continue supporting the .NET 5 SDK.

To enable this, we made .NET 5.0 optional within VS and configured the .NET 5 SDK to run using the .NET 6 runtime.  Because this configuration is specifically for Visual Studio, we are not making the stand-alone version of this SDK available. Customers needing to target 3.1 can use the 3.1.4xx SDK or a newer SDK that are both still in support. This has caused some confusion from customers who weren't sure if the .NET 5 SDK was still in support or not as well as customers looking for the stand-alone download (see https://github.com/dotnet/core/issues/7957). We need to update our existing documentation to make this policy clear.

5.0.2xx will go out of support when Visual Studio 16.9 does in October 2022 and 5.0.4xx will go out of support after 3.1 is no longer supported in December 2022.

**Documentation that needs updating**
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core
https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-core
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Existing documentation that mentions this policy**
https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle (see footnote 1)
https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/ (see the last paragraph before Useful Notes)

**Comment by marcpopMSFT** [comment]
CC @jamshedd @joeloff

**Comment by joeloff** [comment]
Thank you, this will be really helpful for enterprise customers

**Comment by jamshedd** [comment]
I agree with the need to add this clarification but don't think we should pollute the official lifecycle page with the details of this exception which will no longer be relevant in a couple of months. So I propose we make this a separate issue or doc page somewhere and link to it from the blog post and other places where we had the 5.0 EOS notifications.

**Comment by gewarren** [comment]
Can this issue be closed next month (in December)?

**Comment by jamshedd** [comment]
Yes.

**Comment by adegeo** [comment]
Should this be closed?

**Comment by gewarren** [comment]
Closing since the .NET 5.0.2xx and 5.0.4xx SDKs within Visual Studio are now out of support too.
