### ISSUE TITLE
Process for deploying a self-contained app on arm64 needs clarification

### ISSUE THREAD

**Issue by kenrachynski** [dotnet/docs#31113]
I was trying the tutorial at https://docs.microsoft.com/en-ca/dotnet/iot/tutorials/blink-led with my rpi4b running Raspberry Pi OS (64-bit). I built the project on a MacBook Pro 13" M1. So, arm64 in all cases.

When following the section on deploying a self-contained app, I used the `dotnet publish -r linux-arm` as mentioned. Copying the resultant binary to my pi and running it resulted in error message:
`-bash: ./BlinkTutorial: No such file or directory`

After consulting with others, I was informed of the existence of the `linux-arm64` tag. Using that allowed my program to run successfully.

So, some clarification on arm vs arm64 would be handy. I have no devices running a 32-bit rpios to verify that `linux-arm` works as described in the documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to Raspberry Pi](https://docs.microsoft.com/en-ca/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Timely! I just started updating all those docs this week.

Good callout on the 32-bit vs. 64-bit builds. I'll add some text this week.

Have a good weekend!
