### ISSUE TITLE
ProcessStartInfo.UseShellExecute documentation should note that on .NET Core default is *false*

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#3111]
@vanillajonathan commented on [Sat Sep 09 2017](https://github.com/dotnet/corefx/issues/23913)

The documentation for the `UseShellExecute` property in the `ProcessStartInfo` class states the following:

> Gets or sets a value indicating whether to use the operating system shell to start the process. Returns: true if the shell should be used when starting the process; false if the process should be created directly from the executable file. **The default is true**.

This seems to be inconsistent with the actual behavior.

```cs
using System;
using System.Diagnostics;

namespace Example
{
    class Program
    {
        static void Main(string[] args)
        {
            var info = new ProcessStartInfo()
            {
                // UseShellExecute = true,
            };

            Console.WriteLine($"UseShellExecute: {info.UseShellExecute}");
        }
    }
}
```

Which prints out:
> UseShellExecute: False

Reference:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Unix.cs#L41

---

@joshudson commented on [Sat Sep 09 2017](https://github.com/dotnet/corefx/issues/23913#issuecomment-328299270)

What OS?

---

@vanillajonathan commented on [Sat Sep 09 2017](https://github.com/dotnet/corefx/issues/23913#issuecomment-328304249)

Linux.

```
$ dotnet --version
2.0.0
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu Artful Aardvark (development branch)"
```

---

@danmosemsft commented on [Sat Sep 09 2017](https://github.com/dotnet/corefx/issues/23913#issuecomment-328311391)

We chose the opposite default for core. See https://github.com/dotnet/corefx/issues/18949
Docs need an issue in the docs repo probably.

**Comment by mairaw** [comment]
@danmosemsft so is the default false to all .NET Core implementations, right?

It also seems we should document that this API throws PlatformNotSupportedException for [UWP](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Uap.cs#L16). Correct? 

Also, I'm wondering how we can better track changes that have doc impact. Maybe the issues can have a special label or do we immediately open an issue here? By looking at [this](https://github.com/dotnet/corefx/issues/18949#issuecomment-302802961), it seems that only the wiki doc impact was considered.

**Comment by danmosemsft** [comment]
@mairaw yes default false on all .NET Core implementations. PNSE on UWP.

There are other limitations to document for UWP of course. A high level list is at : https://github.com/dotnet/corefx/wiki/UWP-Compat

This is a superset of the .NET Core list at https://github.com/dotnet/corefx/wiki/ApiCompat which I believe you and Paulo have discussed documenting.

**Comment by mairaw** [comment]
Thanks @danmosemsft! Yes, @pjanotti and I started discussing this but haven't finalized a plan yet.

**Comment by pjanotti** [comment]
@mairaw small aside: on Windows Nano it is possible to set this property to `true` but the Process.Start() will throw PNSE.
