### ISSUE TITLE
improvement of article about the  null-warnings

### ISSUE THREAD

**Issue by AliqQim** [dotnet/docs#31110]
Hi!

var c = new Container { States = { "Red", "Yellow", "Green" } };
it's unclear why the warning is raised here. some explanation would be useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 812f0144-80de-6b49-dded-97eeb7bc373d
* Version Independent ID: df58b52a-2532-8241-72cd-f40e9096037d
* Content: [Resolve nullable warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings)
* Content Source: [docs/csharp/language-reference/compiler-messages/nullable-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/nullable-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @AliqQim 

In this case, the warning is because the `Container`, `c` may have a null value for the `States` property. Assigning new states to a collection that might be null causes the warning.

I've added this to our backlog, and added the "help wanted" label to this issue.
