### ISSUE TITLE
dotnet publish does not have a --nologo option

### ISSUE THREAD

**Issue by richRubie** [dotnet/docs#31114]
The dot net publish command does not have a --nologo option.

When you run dotnet publish with this option you get the following message

MSBUILD : error MSB1001: Unknown switch.
Switch: --no-logo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by svick** [comment]
Based on the error message, it seems to me that you mistyped `--nologo` as `-no-logo` (with an extra dash). So I believe that the documentation about `--nologo` is correct.

**Comment by richRubie** [comment]
Oh... Sorry!

I feel a little stupid!
