### ISSUE TITLE
Geolocation issu

### ISSUE THREAD

**Issue by ng294** [dotnet/docs#31120]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f37a0b-3b5d-225f-a349-ee108ff4ec60
* Version Independent ID: 00909a12-d24a-f3f5-d246-8a5cb2431438
* Content: [Compiler Error CS0234](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0234?f1url=%3FappId%3Droslyn%26k%3Dk(CS0234))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0234.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0234.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @ng294 

Can you add detail regarding this question? I'm not sure how geolocation could apply to this warning.
