### ISSUE TITLE
How to download the starter code from the dotnet/samples GitHub repository.

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#31126]
How do I download the starter code from the dotnet/samples GitHub repository? I click on the link and it's not clear how to download the starter code. I can't figure it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddce3f5-395d-00d0-5101-62ae5c4f34e0
* Version Independent ID: 5513eda4-204d-28ed-f6cb-6123f670751e
* Content: [Tutorial: Build algorithms with pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/pattern-matching)
* Content Source: [docs/csharp/fundamentals/tutorials/pattern-matching.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @regal60740 

You can download the code by cloning the entire repo. That's not a great experience, because the repo has a large number of samples. 

I'll update the samples so they are visible in the Samples Browswer, which will make the experience much better.

**Comment by BillWagner** [comment]
[Associated WorkItem - 26235](https://dev.azure.com/msft-skilling/Sandbox/_workitems/edit/26235)

**Comment by BillWagner** [comment]
[Associated WorkItem - 26236](https://dev.azure.com/msft-skilling/Sandbox/_workitems/edit/26236)
