### ISSUE TITLE
Productcode and Upgradecode changing on each release of .net runtime

### ISSUE THREAD

**Issue by Saurbaum** [dotnet/docs#31138]
Normally we would include a runtime for an installer and only offer it up to the user if they require it. This may partly be a users choice because a feature they want to install doesn't require .net 6 so they wouldn't want the increased attack surface on their systems.

What I would do is check first to see if a version of the prerequisite is already installed.

When I tried to do this with runtime 6.0.7 it can successfully detect that with upgrade or product code in windows installer. A newer installation however changes both these installed properties so we can't detect a newer build than we have which means we attempt to install the older runtime which fails with the error.

The exe's for the runtimes are clearly doing some behind the scenes checks but it's not clear what those are. A programmatic way to check if a newer build of .net is installer is essential for users to write proper product installers and the current changing upgradecodes are preventing that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. This sounds more like feedback to the product team rather than feedback on this article? If so, please open your issue at https://github.com/dotnet/core/issues

I'm going to close this as I don't think there is anything to do in the docs at the moment. If I'm mistaken, please feel free to reopen and add more information.

**Comment by Saurbaum** [comment]
I agree there is a bug that I've raised against the installer but the article is lacking on how to detect the newer version programmatically.

Or are you suggesting that we attempt to search all directories on the machine and parse the paths looking for newer version numbers?

**Comment by Saurbaum** [comment]
> Hello. This sounds more like feedback to the product team rather than feedback on this article? If so, please open your issue at https://github.com/dotnet/core/issues
> 
> I'm going to close this as I don't think there is anything to do in the docs at the moment. If I'm mistaken, please feel free to reopen and add more information.

I'd love to know how to reopen it as you suggest as I believe there is still a hole in the documentation
