### ISSUE TITLE
I believe that "Test14" in the "note" section should really be "Test1".

### ISSUE THREAD

**Issue by SoundDev** [dotnet/docs#31139]
I believe that "Test14" in the "note" section should really be "Test1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17b1fbc-2e79-c453-ef83-2ffff1683d5c
* Version Independent ID: b82fafa9-47c1-1c5a-93a3-669782e915eb
* Content: [Order unit tests - .NET](https://docs.microsoft.com/en-us/dotnet/core/testing/order-unit-tests)
* Content Source: [docs/core/testing/order-unit-tests.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/order-unit-tests.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @SoundDev - thanks for posting this issue, however, the note is accurate as stated. It's calling attention to the fact that the ordering with MSTest will treat a test named `Test14` as being ordered before `Test2`. I'm going to close this as it's correct as is.
