### ISSUE TITLE
Totally unclear -Quality values

### ISSUE THREAD

**Issue by travnick** [dotnet/docs#31148]
It's totally unclear what would be the result of particular `-Quality` values.
- daily - clear, a raw develop daily snapshot,
- signed - something signed, but what?,
- validated - another something, though, validated,
- preview - quite clear,
- GA - huh?

The default value information is also missing.

In the user point of view it would like to choose a develop snapshot, preview/RC, release, LTS release from particular version channel like 2.0, 2.1, 3.1, 6.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 67032](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67032)

**Comment by tdykstra** [comment]
cc @bekir-ozturk

**Comment by bekir-ozturk** [comment]
@YuliiaKovalova @mmitche

**Comment by tdykstra** [comment]
ping @YuliiaKovalova @mmitche

**Comment by YuliiaKovalova** [comment]
@MichalPavlik , it's on you.

@tdykstra , sorry for the late response -the previous mention just slipped away from me.

**Comment by tdykstra** [comment]
ping @MichalPavlik
