### ISSUE TITLE
Bug in example code

### ISSUE THREAD

**Issue by SteveSmith16384** [dotnet/docs#31147]
"ipEndPoint" becomes "endPoint".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8918b064-85a6-4644-ecf7-aac48386c58d
* Version Independent ID: 7f7bab6f-3aa6-8755-a541-a6c3b0121f1c
* Content: [Use Sockets to send and receive data - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/sockets/socket-services?redirectedfrom=MSDN#create-a-socket-client)
* Content Source: [docs/fundamentals/networking/sockets/socket-services.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/sockets/socket-services.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Related to #31178

**Comment by IEvangelist** [comment]
Hi @SteveSmith16384 - thanks for posting this, I'm fixing this in #31197
