### ISSUE TITLE
Inconsistent naming for the IP EndPoint

### ISSUE THREAD

**Issue by jpridx** [dotnet/docs#31178]
The snippet included from IPEndpoint names the endpoint ipEndpoint, but the client and server code which follows each expect a variable named simply endPoint.

I would have edited, but it was not clear to me how to edit the included Program.cs files (or if that would have broken something else even if I did know how).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8918b064-85a6-4644-ecf7-aac48386c58d
* Version Independent ID: 7f7bab6f-3aa6-8755-a541-a6c3b0121f1c
* Content: [Use Sockets to send and receive data - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/sockets/socket-services)
* Content Source: [docs/fundamentals/networking/sockets/socket-services.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/sockets/socket-services.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @jpridx, thanks for posting this issue. You're correct, that the variable name is incorrect/inconsistent. I'll fix that.
