### ISSUE TITLE
Remaining incorrectly migrated enum field references

### ISSUE THREAD

**Issue by svick** [dotnet/docs#3118]
In https://github.com/dotnet/docs/issues/1932, I reported an issue where a reference that should be to an `enum` field was to the `enum` itself instead due to an incorrect migration. That was seemingly fixed, but it looks like not all instances of this issue were fixed. Specifically this line:

https://github.com/dotnet/docs/blob/ae49e14b9b5959f7b4a0aacdd1ccf7890afcdd09/xml/System/DateTime.xml#L7013

It says:

> the return value is a DateTime whose Kind property returns System.DateTimeKind.

But it should be (and is [on MSDN](https://msdn.microsoft.com/en-us/library/system.datetime.utcnow(v=vs.110).aspx)):

>    the return value is a DateTime whose Kind property returns DateTimeKind.Utc.

cc: @mairaw

**Comment by mairaw** [comment]
Internal bug opened to track this: [#1077940](https://mseng.visualstudio.com/CSI/_workitems?id=1077940&_a=edit&triage=true)

**Comment by mairaw** [comment]
@svick, @yishengjin1413 did a PR (#3371) to resolve a few more of these that I just merged. Hopefully, this takes care of the remaining of missing enum values. I've asked Terry to double check if we need to apply the same logic he did here on md files too, not only reference.

**Comment by BillWagner** [comment]
@svick can you give this a look and see if this has fixed the issue you opened?

**Comment by svick** [comment]
@BillWagner  The one case I found was already fixed in https://github.com/dotnet/docs/pull/3117 and I didn't notice any more cases since. After #3371 was merged, I was assuming this issue was waiting for "Terry to double check". I am fine with closing this.

**Comment by BillWagner** [comment]
Thanks @svick Closing now.
