### ISSUE TITLE
Incorrect Info About .NET Framework HttpClient Guidelines

### ISSUE THREAD

**Issue by DrHungrysaur** [dotnet/docs#31187]
Hello,

Based on first hand experience (.net Framework 4.5+) and this blog below, .NET Framework also has a socket exhaustion problem when using a new instance of HttpClient for every request as suggested by this documentation.

https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a42e9c6-2624-e047-ed1c-03ec047b538a
* Version Independent ID: 3b1dd30f-82a8-2526-bd51-fb6401c52e81
* Content: [HttpClient guidelines for .NET - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/http/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/http/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
Hi @DrHungrysaur, this article is related to .NET Core (now .NET), but not .NET Framework. .NET Framework has a different implementation, is that correct @gewarren?

**Comment by DrHungrysaur** [comment]
Hello, the article does make statements contrasting the use of HttpClient in Core with Framework.  Specifcally:

"In .NET Framework, create a new [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) each time you need to send a request."

Which I don't believe to be correct.  Since I ran into this problem in the past using HttpClient in Framework, I was looking for 'official' docs with guidelines to refer to a colleage and I ended up here.

**Comment by IEvangelist** [comment]
Related to https://github.com/dotnet/docs/issues/31208

**Comment by gewarren** [comment]
@wfurt @CarnaViire @dotnet/ncl Should we be recommending a static HttpClient instance for .NET Framework too? That's what the example in [this ASP.NET tutorial](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#create-the-console-application) shows. Will users then run into DNS change issues?

**Comment by CarnaViire** [comment]
Thanks everyone for pointing this out. That's right, the guidance is wrong and we should not recommend recreating HttpClient on .NET Framework. I will submit changes to the docs soon.

While it is true that, on .NET Framework, HttpClient is built on top of WebRequest and utilizes ServicePointManager, a new connection group is created inside ServicePointManager for each HttpClientHandler instance (see [source](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/Http/HttpClientHandler.cs#L389)) so the connections are not reused between handlers. That means, creating too many HttpClients on .NET Framework will end up with the same socket exhaustion problem as it does on .NET Core.

cc @wrurt
