### ISSUE TITLE
Is LightGbm retrainable now?

### ISSUE THREAD

**Issue by wil70** [dotnet/docs#31200]
[Enter feedback here]
Hello, I was wondering if LightGbm is retrainable now?
thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0366cc46-bc07-44fd-72d9-d37b40bd5eca
* Version Independent ID: 5c20d041-f946-d7c8-b0b5-7bee96e90282
* Content: [Re-train a model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/retrain-model-ml-net.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/retrain-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @wil70 

Thanks for the question. ML.NET does not support LightGBM model retraining at this time or at least not continued retraining as detailed in this guide. If this is something you'd like to see in ML.NET, I would encourage you to open an issue on the [dotnet/machinelearning](https://github.com/dotnet/machinelearning/issues) repo if you haven't already done so.
