### ISSUE TITLE
[dotnet CLI] Where restored tools are stored?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/docs#31215]
When I call `dotnet tool restore` where can I find restored tools? Especially interesting for local tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198e4c22-ac0b-61de-3ae1-221a73957843
* Version Independent ID: 0873ec7c-9134-138c-97dd-ef96ca31ef23
* Content: [dotnet tool restore command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore)
* Content Source: [docs/core/tools/dotnet-tool-restore.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-restore.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 67033](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67033)

**Comment by tdykstra** [comment]
@JL03-Yue Do you know the answer to this question?

**Comment by tdykstra** [comment]
ping @JL03-Yue

**Comment by baronfel** [comment]
There are three install mechanisms:

* global tools
* local tools
* local tools with a local path

Global tools are stored in $HOME/.dotnet/tools - there are executables generated here for each globally-installed tool (though the actual tool binaries are nested deep into the sibling `.store` directory).

Local tools are stored in the NuGet global directory, whatever you've set that to be. There are shim files in $HOME/.dotnet/toolResolverCache for each local tool that point to where the tool lives on-disk inside that location.

Local tools with explicit tool-paths are stored wherever you specified the `--tool-path` parameter to point to, and are stored in the same layout/format as global tools - an executable binary with the actual binaries in a sibling `.store` directory.
