### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DavidKlempfner** [dotnet/docs#31248]
"you don't need to keep to copies of your data transfer objects(DTOs) synchronized" - remove the second "to", ie. "keep to copies" should be "keep copies".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by erjain** [comment]
Hi @DavidKlempfner, Nice catch. @Jayaram18 thanks for the PR.

**Comment by ardalis** [comment]
I think originally the second "to" was meant to be "two".
