### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by DavidKlempfner** [dotnet/docs#31250]
"Razor Pages doesn't use attribute routing" - "doesn't" should be "don't".

"If your application includes a set of web APIs, which must be secured, these apis should ideally be configured" - "apis" should be "APIs".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d810dd0-a2ff-33ed-28f9-9a674e6f5581
* Version Independent ID: fd259c6e-8d7a-8148-019e-785095909bf7
* Content: [Developing ASP.NET Core MVC apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Jayaram18** [comment]
I would like to work on this issue.

**Comment by Niravprajapati1** [comment]
Can i fix this issue?
