### ISSUE TITLE
Should **System** namespaces be at the top/first?

### ISSUE THREAD

**Issue by mikeblakeuk** [dotnet/docs#31303]
Should **System** namespaces be at the top/first?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccc77394-30af-7736-a34c-997b1d5c33d0
* Version Independent ID: 07b6e8a2-b648-d30a-4696-09a3b2e3b3c1
* Content: [Namespaces - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces)
* Content Source: [standard/namespaces.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @mikeblakeuk 

There is no requirement for the order of `using` declarations. 

I'll close this as an answered question.
