### ISSUE TITLE
Links are to C#6 specifications

### ISSUE THREAD

**Issue by DaveInCaz** [dotnet/docs#31318]
The links in section https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods#c-language-specification go to a c#6 document which does not mention partial methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 450a248b-ab3f-ac3f-d3a5-b1e74b3355ba
* Version Independent ID: 5e05ac12-7d29-d144-a49a-e54765343c20
* Content: [Partial Classes and Methods - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 229455](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229455)

**Comment by BillWagner** [comment]
Hi @DaveInCaz 

The ECMA committee is working to update the standard. We're currently incorporating C# 7 into the draft standard.

That work continues, and we *will* catch up. We know we have quite a bit to do there.

I can add links to the feature specs for the partial method updates.
