### ISSUE TITLE
This code works with simple strings but it is not working with strings like "è" or characters with other Encodings

### ISSUE THREAD

**Issue by bastianonm** [dotnet/docs#31316]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 478c9f53-b77b-5c74-8fb8-4ae75b236e58
* Version Independent ID: 26216ac9-8479-423a-3ca8-eb1315874d61
* Content: [Decrypting data](https://learn.microsoft.com/en-us/dotnet/standard/security/decrypting-data)
* Content Source: [docs/standard/security/decrypting-data.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/decrypting-data.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 30938](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30938)

**Comment by IEvangelist** [comment]
Hi @bastianonm - thank you for posting this issue. There is an overload on both the `StreamWriter` and `StreamReader` that performs the actual I/O. You can specify the encoding there to handle different text encoding. I added this as a code comment to these examples and made a few minor updates. Thanks again.
