### ISSUE TITLE
Official documentation on docs.microsoft.com says that no WCF types exist in netcore

### ISSUE THREAD

**Issue by zhenlan** [dotnet/docs#3132]
@evil-shrike commented on [Fri Aug 25 2017](https://github.com/dotnet/wcf/issues/2235)

Docs (https://docs.microsoft.com) says that no any WCF exists in .net core!

> The requested page is not available for .NET Core 2.0. You have been redirected to a compatible version.

Just an example: https://docs.microsoft.com/ru-ru/dotnet/api/system.servicemodel.channelfactory?view=netframework-4.7&viewFallbackFrom=netcore-2.0

I understand that server-side WCF isn't implemented on netcore. But client types does exist in `System.ServiceModel.Primitives` packages. But the doc tells nothing about that.

**Comment by mairaw** [comment]
Thanks @zhenlan. I think this is related to a discussion I was having with @davidfowl and @terrajobst on adding OOBs and other APIs that come from NuGet packages.

We should discuss how we want to address these, @dend.

**Comment by zhenlan** [comment]
Thanks for following up @mairaw! Can you please clarify what you mean by "OOBs"? I just want to point out that although WCF lives in a separate repo [dotnet/wcf](https://github.com/dotnet/wcf) than [dotnet/corefx](https://github.com/dotnet/corefx), it is considered part of .NET Core (they are versioned the same way, released at the same time etc.).

**Comment by mairaw** [comment]
What we currently have in the docs is a result of the reflection of .NET Core reference assemblies that was given to us by @weshaggard, which is supposed to represent shared framework + corefx. If I look at the API Catalog for the API you posted above, that API is not listed as .NET Core 2.0 but as Platform Extensions.  

The other example was for https://github.com/dotnet/core-setup/tree/master/src/managed/Microsoft.Extensions.DependencyModel.

**Comment by zhenlan** [comment]
If API Catalog does not list WCF APIs as .NET Core 2.0, that's an error too. It's probably because of the same reason that WCF binaries were not provided to API Catalog.

@weshaggard can you please suggest/clarify?

**Comment by weshaggard** [comment]
Yes that is exactly correct @zhenlan while WCF can be considered part of .NET Core it does ship as an individual package and so it is an OOB in that sense. When I think of ".NET Core 2.0" I think of the shared framework and anything that is above that is an OOB that can support .NET Core 2.0. We should definitely try to figure out how to pull WCF into the documentation and APICatalog though. I'm not entirely sure who handles that though.

**Comment by mairaw** [comment]
I have a thread going about the DependencyModel API already, let me add you to that and we can try to sort this out.

**Comment by mairaw** [comment]
There's also the case brought up by @svick on issue #1849 which I just closed as dupe, which presents a similar scenario. So I'm changing this issue to be more generic than just WCF.
