### ISSUE TITLE
BinaryFormatter is insecure and should not be used

### ISSUE THREAD

**Issue by QingpingMeng** [dotnet/docs#31326]
[BinaryFormatter](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) is deprecated and should not be used in the official documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7bc5cfb-d247-62c8-2173-9403efe72b16
* Version Independent ID: 3fab702d-66a7-3338-6c61-f535b29d86a7
* Content: [Walkthrough: Persisting an Object using C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this @QingpingMeng 

We should check throughout our conceptual docs for uses of `BinaryFormatter` and remove them.
