### ISSUE TITLE
the C# versions in title and nav bar don`t match 

### ISSUE THREAD

**Issue by ali50m** [dotnet/docs#31336]
the C# versions in title and nav bar don`t match.

![image](https://user-images.githubusercontent.com/9393831/191653519-2a27a213-6a86-4520-a049-75e984b490b6.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85c9d0ef-c6b0-87f2-746d-6940b1377a54
* Version Independent ID: 575e8c7c-a170-a9d0-ee59-c42451cd1ac9
* Content: [Table of contents - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/readme)
* Content Source: [standard/README.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/README.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @ali50m 

I've opened a PR to address this issue.
