### ISSUE TITLE
Kero-u 

### ISSUE THREAD

**Issue by Kero-u** [dotnet/docs#31338]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# Keywords](https://learn.microsoft.com/en-gb/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Kero-u 

Did you discover an issue you wanted to report?
