### ISSUE TITLE
Outdated method to use .NET5 style template in VS2022

### ISSUE THREAD

**Issue by vedkothavade** [dotnet/docs#31340]
Checking "Do not use top level statements" in VS2022 when creating a new project can easily create a .NET5  style template without manually changing targets as currently described in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6 - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
This article was updated to show the new option in PR #31943
