### ISSUE TITLE
"Using Indexers - C# Programming Guide" should mention `ref returns`

### ISSUE THREAD

**Issue by TymurGubayev** [dotnet/docs#31360]
Following statement isn't quite correct.

>An indexer value is not classified as a variable; therefore, you cannot pass an indexer value as a [ref](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref) or [out](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier) parameter.

But you can pass an indexer value as a `ref`, if the indexer uses `ref return`, like this.

```c#
        private readonly int[] arr = new int[10];
        public ref int this[int index]
        {
            get
            {
                return ref arr[index];
            }
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5323b38b-8dc5-8f50-f5e7-b58ca0e88ad7
* Version Independent ID: 3d9a83cd-98e3-fc6e-727b-32c8e9228c69
* Content: [Using Indexers - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers)
* Content Source: [docs/csharp/programming-guide/indexers/using-indexers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/indexers/using-indexers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this. We'll get this updated.
