### ISSUE TITLE
Inconsistency between page content and code snippet

### ISSUE THREAD

**Issue by mijpeterson** [dotnet/docs#31377]
The content "Note that when a union pattern is covered by a guard, the guard applies to all of the patterns, not just the last one. For example, given the following code, the guard when **a > 12** applies to both A a and B a:" does not match the code snippet directly below, which actually uses the condition a > 41.

a > 12 should be updated to a > 41

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 623de492-3ccf-2284-2f76-9a7707ed14ad
* Version Independent ID: c73b2029-d5e9-0fb4-5afc-aba43e922d84
* Content: [Match expressions - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/match-expressions)
* Content Source: [docs/fsharp/language-reference/match-expressions.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/match-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for noting this @mijpeterson 

I've added this to our backlog, and added the "help wanted" label for public contributors. You're suggestion is the correct fix.

**Comment by jonathlan** [comment]
Hello!
First time in the hacktoberfest. If this is still open I'd like to give it a go.
