### ISSUE TITLE
Mention Docker multi-stage build feature

### ISSUE THREAD

**Issue by joshnoe** [dotnet/docs#31378]
Someone who's new to Docker might not know about multi-stage builds, and would find this Dockerfile confusing.

The Asp.Net Core dockerfile page links to the [Docker multi-stage build feature](https://docs.docker.com/engine/userguide/eng-image/multistage-build/). It would be helpful to include this link on this page as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 30937](https://dev.azure.com/msft-skilling/Content/_workitems/edit/30937)

**Comment by IEvangelist** [comment]
Good catch and callout, @joshnoe - thanks for posting this. I've updated the article to include these details and link.
