### ISSUE TITLE
is null on unconstrained generic types is not limited to C# 11

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/docs#31395]
[Enter feedback here]

The statement, "Beginning with C# 11, you can use is null on unconstrained generic types." is not correct.  It does in fact work in C# 10 (don't know about earlier versions).  For example:

bool TestNull<T>(T? test)=>test is null;

in C#10 yields false for TestNull(6) or TestNull("") but true if applied to an int? containing null or a string? containing null.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 778dcff2-db62-27d5-c0a2-35460e0d72f8
* Version Independent ID: 14ddc828-0812-3c14-60cf-9109bf3b8f7b
* Content: [is operator - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is)
* Content Source: [docs/csharp/language-reference/operators/is.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/is.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @ClaudioFriederich 

I've opened a PR to fix this issue.
