### ISSUE TITLE
Structure field initializers section is not correct

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/docs#31391]
[Enter feedback here]

The statement "If you don't write a public parameterless constructor, the compiler generates one. The compiler-generated parameterless constructor executes any field initializers, and produces the [default value](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values) for all other fields." in this topic is not correct.  The compiler-generated parameterless constructor does NOT execute field initializers - it produces the default value for all fields, and ignores the initializers.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#struct-initialization-and-default-values)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @ClaudioFriederich 

The current behavior is as follows:

- If a struct declares any field initializers, it *must* explicitly declare a constructor. That constructor need not be a parameterless constructor. If a struct declares a field initializer but no constructors, the compiler reports an error.
- Any explicitly declared constructor (with parameters, or parameterless) executes all field initializers for that struct.
- All fields without a field initializer or set in a constructor are set to the default value.

**Comment by luizhlelis** [comment]
Hello @BillWagner.
As you've already described the current behavior, I've just added your description removing the old one. Let me know if you're expecting something else.
Thank you 🙂
