### ISSUE TITLE
Docs list a `dotnet watch` option that isn't released yet

### ISSUE THREAD

**Issue by xt0rted** [dotnet/docs#31412]
The `--non-interactive` option was added to .net 7, but there's no indication of that on the page. I had to dig through the code and find the pr/issue that added it in to figure out why it wasn't working for me (using 6.0.401 of the sdk). The page does list .net core sdk 3.1+ but not all options work in all versions.

ref: https://github.com/dotnet/sdk/pull/23309
ref: https://github.com/dotnet/sdk/issues/23238

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16f49f1b-261c-8cd0-a024-32c2535d0a0f
* Version Independent ID: 218d2a4d-2ff3-8e4d-1f06-bbb3710878fe
* Content: [dotnet watch command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch)
* Content Source: [docs/core/tools/dotnet-watch.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-watch.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that -- I'm adding a note about availability to the option's comments.
