### ISSUE TITLE
While/Until is optional, not required

### ISSUE THREAD

**Issue by Chrizine** [dotnet/docs#31427]
It seems to be perfectly possible to make a loop just 
```
Do
    '  body
Loop
```
The syntax summary on this page does not account for this, and the text in the table stating that while is required unless until is provided and vice-versa seems incorrect.
Can be easily fixed by putting brackets around the whole condition in the syntax and adjusting the text for while and until to say that at most one of them can be provided. The condition is already stated to be optional in the table, so that is correct, it just needs to be reflected in the grammar and in the entries for the other keywords.
It might be nice to also make clear which of the keywords is implicitly used with the implicit condition when it is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9c687ff-abab-e1e2-bfde-11b8eb30273e
* Version Independent ID: ea281b2a-2bfe-6c8b-c5b7-a61b184bbd2e
* Content: [Do...Loop Statement - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/do-loop-statement)
* Content Source: [docs/visual-basic/language-reference/statements/do-loop-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/do-loop-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
That's a good note @Chrizine 

I've added it to our backlog to address. I've also added the help  wanted label if anyone wants to submit a PR to address this issue.
