### ISSUE TITLE
AddHandler with Lambda

### ISSUE THREAD

**Issue by Chrizine** [dotnet/docs#31428]
This page only explains adding handlers via addressof, but it seems also completely possible to give a lambda expression directly in the AddHandler statement instead of the addressof.
Please add this usage in the syntax and ideally also give an example and explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7771f230-ac9e-7310-e606-94bd9fc84f29
* Version Independent ID: 728dfc67-f3e9-64ea-8a91-c6d72c8cc54f
* Content: [AddHandler Statement - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/addhandler-statement)
* Content Source: [docs/visual-basic/language-reference/statements/addhandler-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/addhandler-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
That's a great suggestion @Chrizine 

I've added it to our backlog, and added the "help wanted" label to this issue.

**Comment by Chrizine** [comment]
Thank you!
As a possible example, the already existing one could be transformed to the lambda version like this:
```
Module M
    Sub TestEvents()
        Dim Obj As New Class1
        ' Associate an event handler with an event.
        AddHandler Obj.Ev_Event, Sub()
                ' Handle the event.
                MsgBox("EventHandler caught event.")
            End Sub
        ' Call the method to raise the event.
        Obj.CauseSomeEvent()
    End Sub
End Module

Public Class Class1
    ' Declare an event.
    Public Event Ev_Event()
    Sub CauseSomeEvent()
        ' Raise an event.
        RaiseEvent Ev_Event()
    End Sub
End Class
```
