### ISSUE TITLE
Implicit value parameter

### ISSUE THREAD

**Issue by Chrizine** [dotnet/docs#31429]
> In the Set statement, follow the Set keyword with a parameter list in parentheses. This parameter list must include at least a value parameter for the value passed by the calling code. The default name for this value parameter is Value, but you can use a different name if appropriate. The value parameter must have the same data type as the property itself.

This section is a bit unclear. It sounds like there must be a parameter specified for the value, but it also lists a default name. My understanding is that it is not strictly required to specify a parameter and the default value parameter will be implicit if none are provided. This could be made clearer here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6342723-a485-40ba-c2e6-fe687dd2bc5b
* Version Independent ID: 1d724086-8c9c-b0d7-1f9e-7c3a89f8fbe5
* Content: [How to: Create a Property - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-create-a-property)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/how-to-create-a-property.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/procedures/how-to-create-a-property.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
That's also a good suggestion @Chrizine 

I've added it to our backlog to address.
