### ISSUE TITLE
Where's `IComponent`

### ISSUE THREAD

**Issue by ShaunCurtis** [dotnet/docs#31426]
This content fails to differentiate between `IComponent` and `ComponentBase`.  Some of the content describes `ComponentBase` functionality, not **component** functionality.  

The UI render process will manage and "render" any object that implements `IComponent`.  There's no requirement to inherit `ComponentBase`.  `ComponentBase` is an implementation of `IComponent` provided with Blazor that provides functionality most programmers need in a component.  They can either use `ComponentBase` or write their own implementations.  

By default *Razor* files inherit from `ComponentBase`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60c195c0-99f6-64f5-66a3-4e69109dc8ee
* Version Independent ID: 24368808-4b90-f75a-e887-eb72a1c85f5b
* Content: [Build reusable UI components with Blazor](https://learn.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/components.md](https://github.com/dotnet/docs/blob/main/docs/architecture/blazor-for-web-forms-developers/components.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by erjain** [comment]
Hi @danroth27, what are your thoughts?

**Comment by danroth27** [comment]
It's certainly true that this chapter doesn't cover IComponent. I think that's intentional given that the most common way to implement components is using .razor files.

@ShaunCurtis Are there any particular passages of text that you see as inaccurate and should be generalized? Or are you just pointing out that this is a missing concept in the eBook?

**Comment by ShaunCurtis** [comment]
While there are passages where `ComponentBase` and Component are treated as synonymous, I think that this is a missing concept in the whole community.  This comment section at the top of the `ComponentBase` code is enlightening.  Few have probably ever read it, and even fewer taken the author up.  

```csharp
// Most of the developer-facing component lifecycle concepts are encapsulated in this
// base class. The core components rendering system doesn't know about them (it only knows
// about IComponent). This gives us flexibility to change the lifecycle concepts easily,
// or for developers to design their own lifecycles as different base classes.
```

I'm probably in a minority of one in not using `ComponentBase` as my core component.

**Comment by ShaunCurtis** [comment]
yes, and thanks.
