### ISSUE TITLE
link not functioning properly.

### ISSUE THREAD

**Issue by usavas** [dotnet/docs#31436]
[Enter feedback here]
on clicking on this page's link [assembly] on the .NET documentation page, it goes to a whole new page with only assembly and sub items present. It makes one get lost in the navigation. I think it is not functioning properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16139271-316c-00ac-059b-c6f9e7b64b1c
* Version Independent ID: 8ea0ef0d-54f6-122e-cb41-f9ca8ea918e0
* Content: [Assemblies in .NET](https://learn.microsoft.com/en-us/dotnet/standard/assembly/)
* Content Source: [docs/standard/assembly/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @usavas - could you please provide a screen capture and highlight the specific link in question.
