### ISSUE TITLE
Offer a link to where Microsoft stores its own project templates

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/docs#31438]
It would be nice to have a link to where in source control Microsoft stores all of the default `dotnet new` templates, as seen here:

![image](https://user-images.githubusercontent.com/115199/192654399-50ab3813-b437-4394-b537-cfb87ce804ec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097102bb-f6d9-c469-5556-ae1f16fdc4fe
* Version Independent ID: 77b25381-6e0f-949f-5f96-b83e9b61e9fc
* Content: [Create a project template for dotnet new - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template)
* Content Source: [docs/core/tutorials/cli-templates-create-project-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-project-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @atrauzzi - is this something that you'd expect the .NET docs to have, or the .NET CLI tool itself?

**Comment by atrauzzi** [comment]
Possibly both? The docs *for sure* because they're where I'd end up after a google search.

Putting it in the CLI would just be a _nice to have_.  But the docs first so that people can discover them and how they're maintained more easily.

**Comment by IEvangelist** [comment]
As for the docs, there is no way to know what templates a client might have installed. I assume we'd have to list them all then. Why is this repo important to you?

**Comment by atrauzzi** [comment]
You don't need to know what templates the user has installed.  I only am asking for the ones that Microsoft ships by default.  Anything outside of that isn't important.

I would like this so that I can be able to review how templates are managed and authored.  It's nice to have the official starter projects as a reference point when creating my own skeletons.
