### ISSUE TITLE
warnings instead of types

### ISSUE THREAD

**Issue by martinklusacek** [dotnet/docs#31442]
I was reading this page and wondering, should the first sentence say:

The purpose of nullable reference **warnings** is to minimize the chance that your application throws a [System.NullReferenceException](https://learn.microsoft.com/en-us/dotnet/api/system.nullreferenceexception) when run.

instead of:

The purpose of nullable reference **types** is to minimize the chance that your application throws a [System.NullReferenceException](https://learn.microsoft.com/en-us/dotnet/api/system.nullreferenceexception) when run.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 812f0144-80de-6b49-dded-97eeb7bc373d
* Version Independent ID: df58b52a-2532-8241-72cd-f40e9096037d
* Content: [Resolve nullable warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8604))
* Content Source: [docs/csharp/language-reference/compiler-messages/nullable-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/nullable-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @martinklusacek 

I've added it to our backlog, and I've added the "help wanted" label in case anyone wants to submit a PR before we make the change.
