### ISSUE TITLE
Direkt Link to latest versions.

### ISSUE THREAD

**Issue by foxtrottNB** [dotnet/docs#31458]
[Enter feedback here]
The Link https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/ will open C#10 not C#11. Let it open always the latest version.
The same is valid for  https://learn.microsoft.com/en-us/dotnet/core/whats-new/ which opens .NET Core 3.1 instead of .NET 6.0

BR
Ronny

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f94e527-6240-7b69-9d98-da8405790b1c
* Version Independent ID: a3d4d1bb-cfb0-3306-3ce7-5977fb199255
* Content: [What's new in C# 11 - C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11)
* Content Source: [docs/csharp/whats-new/csharp-11.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-11.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by foxtrottNB** [comment]
Or at least let it open an overview page with all versions please.

**Comment by BillWagner** [comment]
Thanks @foxtrottNB 

That's on my list for this month.
