### ISSUE TITLE
Observations in Enterprise Application Patterns using .NET Maui

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs#31462]
These are few of the obeservations while reading the book. 
1.  Introduction- MacOS is missing in platforms in the  Summary.
2. MVVM- In `the benefits of using the MVVM pattern` I have objection to point 3. In my experience the app UI can be redesigned without touching the view model and model code if it is written entirely in XAML or C#.
3. MVVM- In a .NET MAUI application, a view is typically a `Page`-derived. But in my opinion it should be ContentPage-derived.
4. DI- In line number 52 the word Autofac is used instead of Microsoft.Extensions.DependencyInjection.
5. DI- in line number 56 `The involves the container performing the following actions:` should be `This involves the container performing the following actions:`
6. Validation -Model-ViewModel-Model (MVVM)  should be Model-View-ViewModel (MVVM) in first line of second paragraph.
7. Authentication and Authorization- Shouldn't Access Code be saved in Secure Storage instead of Preferences. 
8. Accessing Remote Data- NewtonSoft can be replaced with System.Text..Json

I learn a lot from the book. Thanks to the author for his hard work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8286af12-fbed-6ba9-b33e-be1345421763
* Version Independent ID: 85388434-76a7-7a20-feec-fe27e5ca76b0
* Content: [Enterprise Application Patterns Using .NET MAUI](https://learn.microsoft.com/en-us/dotnet/architecture/maui/)
* Content Source: [docs/architecture/maui/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/maui/index.md)
* Product: **dotnet-architecture**
* GitHub Login: @michaelstonis
* Microsoft Alias: **nanil**

**Comment by IEvangelist** [comment]
Hi friends, this issue came through at a time when my Outlook rules were messed up and I wasn't getting these at mention/notification emails. I'm just now seeing this. /cc @davidbritch and @adegeo
