### ISSUE TITLE
Easy to get lost in this

### ISSUE THREAD

**Issue by gregowahoo** [dotnet/docs#31466]
Making breakfast toast this page does not flow very well. I'm lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @gregowahoo 

Can you add a bit more context on where you got lost? I'd like to improve the experience, but I need a bit more detail for that.

**Comment by BillWagner** [comment]
hi @gregowahoo 

The link is at the bottom of the issue descriptiion: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
