### ISSUE TITLE
Add information on how to install a template from a private NuGet Server

### ISSUE THREAD

**Issue by Vaccano** [dotnet/docs#31467]
The page lists 3 ways to install a Template that is packaged in a NuGet.

* From NuGet.org
* From a local file
* From a file system directory

But it is very common these days for teams to have a private NuGet repository (not on NuGet.org).  ProGet, Artifactory, and others products are commonly used to host NuGets that are not intended for public use.  

It would be helpful to add documentation on how to install a template that is hosted on private NuGet repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/custom-templates.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by Vaccano** [comment]
> I'll add it to the backlog

Happy to see it added to the backlog.  

> If you would like to contribute, you can submit a fix by editing the original article

I would happily contribute a solution if I knew it. I posted this issue because I don't know how to do it.

**Comment by adegeo** [comment]
Ahh 😁  this should be covered by the CLI reference: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install#options

**Comment by adegeo** [comment]
We're going to have to update these pages for .NET 7 as the whole command has been changed.

**Comment by Vaccano** [comment]
That page does indeed have it.  **`--nuget-source <SOURCE>`** is what I was looking for!  

I was about to suggest that a link be added to that page (from the page I was on), but when I double checked, it is there!  Sorry for wasting your time on this.  I thought I had searched thoroughly for this.  I will try to be more careful before opening an issue in the future.

Thank you for your help!

**Comment by adegeo** [comment]
No worries. I'm going to reopen the issue though, as I think it's good to document this in the list of "what you can do" in this article.
