### ISSUE TITLE
Duplicated Word

### ISSUE THREAD

**Issue by ccw-li** [dotnet/docs#31478]
Hi, in this [document](https://learn.microsoft.com/en-us/dotnet/core/introduction#compilation), there is a sentence:

> On Android, Linux, macOS, and Linux, JIT compilation is the default, and AOT is optional (for example, with [ReadyToRun](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run)).

In this sentence, the word "Linux" appears twice when enumerating operating systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad87897-30cc-e639-b91a-b3800269f7fe
* Version Independent ID: 9d3015b4-cba1-0956-9ec7-4154dbb74d93
* Content: [.NET (and .NET Core) - introduction and overview](https://learn.microsoft.com/en-us/dotnet/core/introduction)
* Content Source: [docs/core/introduction.md](https://github.com/dotnet/docs/blob/main/docs/core/introduction.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by ccw-li** [comment]
Hi, in this [document](https://learn.microsoft.com/en-us/dotnet/core/introduction#compilation), the problem still exists.

**Comment by gewarren** [comment]
> Hi, in this [document](https://learn.microsoft.com/en-us/dotnet/core/introduction#compilation), the problem still exists.

Can you check again? Our publishing happens nightly in the PST time zone, so I think the change hadn't been published yet when you looked.

**Comment by ccw-li** [comment]
> > Hi, in this [document](https://learn.microsoft.com/en-us/dotnet/core/introduction#compilation), the problem still exists.
> 
> Can you check again? Our publishing happens nightly in the PST time zone, so I think the change hadn't been published yet when you looked.

The problem is fixed. Thanks.
