### ISSUE TITLE
[Breaking change]: Improvement to handling of env prefixes containing __

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/docs#31490]
## Key changes:

* By comparing normalized prefixes to normalized keys, both the un-altered and colon-normalized prefixes match environment variables in either the __ or colon formats.
* There is a change of behaviour that some environment variables which theoretically didn't match the filter before may now match the filter, but I don't expect this to be an issue in practice (I very much doubt anyone configures variables with both a `:` and `__` prefix, and relies on the fact that these don't match)
* Existing behaviour is maintained, to avoid any potential issues such as https://github.com/dotnet/runtime/issues/61577 or any changes of behaviour with the special case connection string matching.

### Version

.NET 7 Preview 4

### Previous behavior

Some environment variables which theoretically didn't match the filter before may now match the filter

### New behavior

By comparing normalized prefixes to normalized keys, both the un-altered and colon-normalized prefixes match environment variables in either the __ or colon formats.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

Confusing environment variable configuration prefix behaviour was reintroduced in 6.0.2. (It worked on 6.0.0 and 6.0.1. Upgrading to 6.0.2 caused the break.) https://github.com/dotnet/runtime/pull/62819 was merged into 6.0.2 to revert a breaking change in 6.0.0, but the reversion caused a breaking change compared to 6.0.0/6.0.1, by reverting the (good) part of https://github.com/dotnet/runtime/pull/62819.

For reference, the [current configuration documentation is here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#environment-variables).

### Recommended action

```cs
Environment.SetEnvironmentVariable("MY_PREFIX__ConfigKey, "myFooValue");
var configuration = new ConfigurationBuilder()
    .AddEnvironmentVariables("MY_PREFIX__")
    .Build();

var loadedValue = configuration.GetValue<string?>("ConfigKey", null);

Assert.Equals("myFooValue", loadedValue); // FAILED in 6.0.2 as loadedConfig was null. The prefix of `MY_PREFIX:` can be specified instead now
```

### Feature area

C#, Core .NET libraries, Extensions

**Comment by maryamariyan** [comment]
When I was trying to create this issue the `.NET 7 Preview 4` option was not available so selected `.NET 7 Preview 5` from the drop down list.

**Comment by gewarren** [comment]
@maryamariyan Does this breaking change only affect Unix-based OSs? See my comment/code [here](https://github.com/dotnet/runtime/issues/65756#issuecomment-1275408547), which I would expect to return `True` on .NET 7 RC 2.

**Comment by dhedey** [comment]
Hi @gewarren apologies, I'm unable reply to you on https://github.com/dotnet/runtime/issues/65756 as the issue is closed, and I'm only a Contributor.

But yes, I'm surprised by this behaviour. The PR includes a test case `AddEnvironmentVariablesUsingPrefixWithDoubleUnderscores_Bind_PrefixMatches` ([see this line in github](https://github.com/dotnet/runtime/blob/550605cc93d9b903c4fbaf8f1f83e387d2f79dbe/src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/EnvironmentVariablesTest.cs#L266)) which is a test very similar to your example. I'm surprised the test passes while your example fails, unless the tests don't run on Windows in CI. The matching of normalized key against normalized prefix should also be OS-independent.

I don't have a Windows machine to test/verify on at present.

**Comment by gewarren** [comment]
Thanks @dhedey, I did get it to print `True` after updating my NuGet packages for the extensions to .NET 7 (forgot about that).
