### ISSUE TITLE
Need additional NuGet package  Microsoft.Extensions.Hosting.WebServices

### ISSUE THREAD

**Issue by PWSALLITC** [dotnet/docs#31500]
My title says it all...
Couldn't compile sample code until this package was installed.
Read quite a few articles until finding the answer...
Thank you for the sample very helpful otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae847f16-ff74-ab68-7163-f713b447430c
* Version Independent ID: ff379d26-0d85-6d74-67da-4a3cd260b04d
* Content: [Worker Services - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/workers)
* Content Source: [docs/core/extensions/workers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/workers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @PWSALLITC - The package name that you refer to in the title doesn't exist, here is a search for it on NuGet: https://www.nuget.org/packages?q=Microsoft.Extensions.Hosting.WebServices

The article explains that the project `Sdk` should be `"Microsoft.NET.Sdk.Worker` and then you'll have all the bits you need. What source code didn't compile, could you please share it here?

**Comment by PWSALLITC** [comment]
Sorry NuGet solution is named:
Microsoft.Extensions.Hosting.WindowsServices

But I think I see what I did …
I didn’t generate from CLI and used Visual Studio GUI.
I am using json not xml so this added to many switching of screens to translate.

So I am …
Removing Microsoft.Extensions.Hosting.WindowsServices
And retrying from scratch …

I think I see what I missed I didn’t copy this code to Program.cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using App.WorkerService;

using IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices((hostContext, services) =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();

This is the code that should have been replaced (It has my modified names)
>>IHost referencing “UseWindowsService”

using App.WindowsService;
using BMonService;
using Microsoft.Extensions.Logging.Configuration;
using Microsoft.Extensions.Logging.EventLog;

using IHost host = Host.CreateDefaultBuilder(args)
    .UseWindowsService(options =>
    {
        options.ServiceName = ".NET PID Service";
    })
    .ConfigureServices(services =>
    {
        LoggerProviderOptions.RegisterProviderOptions<
            EventLogSettings, EventLogLoggerProvider>(services);

        services.AddSingleton<PIDService>();
        services.AddHostedService<WindowsBackgroundService>();
    })
    .ConfigureLogging((context, logging) =>
    {
        // See: https://github.com/dotnet/runtime/issues/47303
        logging.AddConfiguration(
            context.Configuration.GetSection("Logging"));
    })
    .Build();

await host.RunAsync();
-Peter
CONFIDENTIALITY NOTICE
This e-mail transmission may contain confidential, proprietary, privileged or otherwise legally protected information that is intended only for the individual or entity named in this transmission. If you are not the intended recipient, you are not authorized to read, print, retain, copy or disseminate this transmission or any part of it or attachment to it.  If you have received this e-mail in error, please notify the sender immediately by e-mail and delete all copies of this e-mail transmission.

**Comment by IEvangelist** [comment]
Hi again @PWSALLITC - thanks for the clarification, much appreciated. I think I see the problem too, you're using the Windows service, which isn't discussed in the article you mention here. It has its own/dedicated article here: https://learn.microsoft.com/dotnet/core/extensions/windows-service

**Comment by PWSALLITC** [comment]
Stumbling and bumbling but getting there… learning on the way.

Confused on the GC enabling with heap values.  Guess since template is json need to set json settings…

Thank you and sorry to bug you needlessly.

-Peter
CONFIDENTIALITY NOTICE
This e-mail transmission may contain confidential, proprietary, privileged or otherwise legally protected information that is intended only for the individual or entity named in this transmission. If you are not the intended recipient, you are not authorized to read, print, retain, copy or disseminate this transmission or any part of it or attachment to it.  If you have received this e-mail in error, please notify the sender immediately by e-mail and delete all copies of this e-mail transmission.

**Comment by IEvangelist** [comment]
No worries whatsoever, always happy to help. I'll close this issue for now, but if you find something that needs an update, let's open a new issue and start from there. Thanks
