### ISSUE TITLE
"Finite Control" used without definition

### ISSUE THREAD

**Issue by tsmaster** [dotnet/docs#31526]
The document uses a phrase "finite control", which isn't defined. Does it refer to "finite state machines"? Or is "finite" here intended to mean "granular"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3f3464-63e0-a40f-c645-59fad8a38b9f
* Version Independent ID: 412ed2a6-36f3-382d-1e8c-979eb80c2c0a
* Content: [Asynchronous file access (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/using-async-for-file-access)
* Content Source: [docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @tsmaster 

Thanks for spotting this. It should be "fine control", not "finite control". I've created PR #31556 to address this issue.
