### ISSUE TITLE
Link correction

### ISSUE THREAD

**Issue by JoseVale-pt** [dotnet/docs#31596]
Where it says:
_[On your local machine](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp-local). After you've explored online, you can_
The link points to a complete different link that is supposed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8cdfbba-c2bd-f9b0-52a9-d82cc9b2dcf9
* Version Independent ID: 287733f4-7593-ba5e-f26c-531fde328319
* Content: [Introduction to C# - interactive tutorials](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 230268](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230268)

**Comment by BillWagner** [comment]
Hi @JoseVale-pt   The link goes to the first tutorial in this series that's written for local installation. That was our intent. Do you think it should go to the setup instructions instead? That's worth considering.

**Comment by JoseVale-pt** [comment]
Hi @BillWagner 
The complete text is about several enviroments that we can use to use for the tutorials
"
You can try these tutorials in **different environments**. The concepts you'll learn are the same. The difference is which experience you prefer:

[In your browser, on the docs platform](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world): This experience embeds a runnable C# code window in docs pages. You write and execute C# code in the browser.
[In the Microsoft Learn training experience](https://learn.microsoft.com/en-us/training/paths/csharp-first-steps/). This learning path contains several modules that teach the basics of C#.
[In Jupyter on Binder](https://mybinder.org/v2/gh/dotnet/try-samples/main?filepath=hello-csharp%2Fhello-world.ipynb). You can experiment with C# code in a Jupyter notebook on binder.
[On your local machine](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp-local). After you've explored online, you can [download](https://dotnet.microsoft.com/download) the .NET SDK and build programs on your machine.

Every other ones point to the proper environment the local one point direct to a topic about _"How to use integer and floating point numbers in C#"_ but should go at least to the download link "https://dotnet.microsoft.com/en-us/download" that you also point in the same paragraph or i think more sense go to [](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/local-environment) where is explained how to set local environment.

**Comment by BillWagner** [comment]
Thanks @JoseVale-pt 
That helps.
