### ISSUE TITLE
Add content for GetBulkSecretAsync

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/docs#31591]
it would seem helpful to add a sub-section on getting bulk secrets, thoughts? 💭

reference: 
- [GetBulkSecretAsync](https://github.com/dapr/dotnet-sdk/blob/01cdc89710c16712442474afea97693f22c5852b/src/Dapr.Client/DaprClient.cs#L851)
- [Accessing Dapr secrets building block using Dapr .NET SDK](https://laurentkempe.com/2021/04/06/accessing-dapr-secrets-building-block-using-dapr-dotnet-sdk/),
- https://github.com/dapr/dotnet-sdk/issues/510

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47087005-02f3-1fcc-f9b3-e4c29a2df428
* Version Independent ID: 01afb864-8260-f36b-fc51-19c88de8ee66
* Content: [The Dapr secrets management building block](https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/secrets-management)
* Content Source: [docs/architecture/dapr-for-net-developers/secrets-management.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/secrets-management.md)
* Product: **dotnet-architecture**
* GitHub Login: @EdwinVW
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @spottedmahn, thanks for the valuable feedback. I believe this will be great to add the sub-section on getting bulk secrets. Do you or anyone else wishes to work on this addition and share a PR on this, please let us know on this thread, and we can review your PR and merge it.

**Comment by erjain** [comment]
Hi @spottedmahn, just checking if you have picked this.

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
