### ISSUE TITLE
Inaccurate content - "Walkthrough: Embed types from managed assemblies in Visual Studio"

### ISSUE THREAD

**Issue by burque505** [dotnet/docs#31601]
What a disappointment - I found this page and thought 'Wow, a real walkthrough!" But the content isn't up to date for Visual Studio 2022, nor is it up to date for .NET 6.0.
1) "Select Signing on the left pane of the Properties screen, and then select the Sign the assembly check box. In the dropdown for Choose a strong name key file, select New." THERE IS NO SUCH DROPDOWN BOX.
2) "In the Create Strong Name Key dialog, under Key file name, type key.snk. Deselect the Protect my key file with a password check box, and then select OK." As there is no such dialog, this is pretty difficult.
3) "In Solution Explorer, expand the Properties folder and select the AssemblyInfo.cs or AssemblyInfo.vb file. In the code editor, add the following attribute to the file:" There is no AssemblyInfo.cs, and no information as to how to get the following information:
[[assembly: ImportedFromTypeLib("")]] _correctly_ into the .csproj file properly.

This article was purportedly written on 7/29/22 - not that old.
[IEvangelist](https://github.com/IEvangelist)
[tdykstra](https://github.com/tdykstra)
[BillWagner](https://github.com/BillWagner)
[TimShererWithAquent](https://github.com/TimShererWithAquent)
[gewarren](https://github.com/gewarren)
[Youssef1313](https://github.com/Youssef1313)
[lucasnobredev](https://github.com/lucasnobredev)
[v-thepet](https://github.com/v-thepet)

Perhaps one of the people above can provide some assistance. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16419eb7-66b4-751f-192a-a1f399942579
* Version Independent ID: 1364a74b-43ac-c3a7-4021-80e70cdd43db
* Content: [Walkthrough: Embed types from managed assemblies in Visual Studio](https://learn.microsoft.com/en-us/dotnet/standard/assembly/embed-types-visual-studio)
* Content Source: [docs/standard/assembly/embed-types-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/embed-types-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @burque505 - thanks for posting this issue, and bringing this to our attention. I put this on the backlog and will prioritize it accordingly, and work on addressing these concerns as soon as I'm able. Thanks again
