### ISSUE TITLE
Where can I find .editorconfig for C# Coding Conventions ?

### ISSUE THREAD

**Issue by vitaliizabolotnyi** [dotnet/docs#31613]

**Comment by Marusyk** [comment]
@vitaliizabolotnyi you may see these examples

- [runtime](https://github.com/dotnet/runtime/blob/main/.editorconfig)
- [asp.net](https://github.com/dotnet/aspnetcore/blob/main/.editorconfig)
- [entity framework](https://github.com/dotnet/efcore/blob/main/.editorconfig)

**Comment by gewarren** [comment]
Closing this now. Let us know if you need anything else.
