### ISSUE TITLE
Missing documentation for .Net Core 7.0 release canidates support

### ISSUE THREAD

**Issue by MatthijsPrent** [dotnet/docs#31644]
This page does not contain any information on the support of an .Net Standard library for the new .Net 7.0 release canidates. It would be nice if this can be added.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
We'll get this updated. .NET 7 supports .NET Standard 2.1 and earlier versions.

**Comment by gewarren** [comment]
This info has been added.
