### ISSUE TITLE
<wbr> tags showing up rendered page

### ISSUE THREAD

**Issue by encrypt0r** [dotnet/docs#3164]
I don't know if this has anything to do with #1904 or not, but when viewing some pages like [this](https://docs.microsoft.com/en-us/dotnet/api/system.windows.weakeventmanager?view=netframework-4.7#Constructors) or [that](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netframework-4.7#Methods), the <wbr> tags actually show up in the render of the references section. Which I don't think is the desirable outcome. 

For example:
`WeakEventManager` appears as `Weak<wbr>Event<wbr>Manager()`
`AddRange(IEnumerable<T>)` appears as `Add<wbr>Range(IEnumerable<T>)`

I have tested it on these browsers:
Chrome: Version 60
Firefox: Version 55
Edge: Version 40

**Comment by mairaw** [comment]
Thanks for bringing this up to our attention. Not sure if it's related or not. We usually call out the internal bug number when we mark an issue as external and we haven't done that in #1904 unfortunately. I'll open an issue for this immediately.

**Comment by mairaw** [comment]
Internal issue opened: [1081828](https://mseng.visualstudio.com/CSI/_workitems?id=1081828&_a=edit)

**Comment by dend** [comment]
@mairaw this should be resolved.

**Comment by mairaw** [comment]
Yes, it is @dend. Thanks! Closing this then.
