### ISSUE TITLE
error: NU1100: Unable to resolve 'System.CommandLine (>= 2.0.0-beta4.22272.1)' for 'net6.0'.

### ISSUE THREAD

**Issue by AndrewPascoCS** [dotnet/docs#31652]
When following this Tutorial in the section "**Installing System.CommandLine package**"

the following is the error results of running the command:
`C:\Users\me\GitHub\SCL>dotnet add package System.CommandLine --version 2.0.0-beta4.22272.1
  Determining projects to restore...
  Writing C:\Users\me\AppData\Local\Temp\tmp91D.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'System.CommandLine' into project 'C:\Users\me\GitHub\SCL\SCL.csproj'.
info : Restoring packages for C:\Users\PASCOA\GitHub\SCL\SCL.csproj...
error: NU1100: Unable to resolve 'System.CommandLine (>= 2.0.0-beta4.22272.1)' for 'net6.0'.
error: Package 'System.CommandLine' is incompatible with 'all' frameworks in project 'C:\Users\me\GitHub\SCL\SCL.csproj'.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7705dc41-7297-0807-7e9c-2e6548c26b84
* Version Independent ID: fa160b1d-66ed-8c5d-37cd-b7e02443e9f1
* Content: [Tutorial: Get started with System.CommandLine](https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial)
* Content Source: [docs/standard/commandline/get-started-tutorial.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/get-started-tutorial.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
>Package 'System.CommandLine' is incompatible with 'all' frameworks in project

What is in your .csproj file?

**Comment by AndrewPascoCS** [comment]
created using the previous step in the tutorial,

Create the app

Create a .NET 6 console app project named "scl".

  1.  Create a folder named scl for the project, and then open a command prompt in the new folder.

  2.  Run the following command:

dotnet new console --framework net6.0


contents of .csproj file

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>




Andrew Pasco
Security Consultant
CISO Security Operations|  Department of Customer Service
Tel: 0410 533 009    E-Mail: ***@***.******@***.***>
Mckell Building, 2-24 Rawson Pl, Sydney, NSW 2000

Please consider the environment before printing this email.

________________________________

**Comment by jonsequitur** [comment]
This can happen when the package isn't available in any of your package sources, maybe due to a setting in a local or user-level nuget.config.

If you run `dotnet nuget list source` in that directory, do you see nuget.org in the list?

**Comment by AndrewPascoCS** [comment]
PS C:\Users\xxxxxx\GitHub\TrustedInstaller> dotnet nuget list source
No sources found.

So I tried adding the --source nuget.org but still no success

PS C:\Users\xxxxxx\GitHub\TrustedInstaller> dotnet add package System.CommandLine --prerelease  --source nuget.org
  Determining projects to restore...
  Writing C:\Users\xxxxxx\AppData\Local\Temp\tmpE54A.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'System.CommandLine' into project 'C:\Users\xxxxxx\GitHub\TrustedInstaller\TrustedInstaller.csproj'.
error: There are no versions available for the package 'System.CommandLine'.

**Comment by AndrewPascoCS** [comment]
It appears there is a missing step if using VScode only which is to add the nuget sources:

could you consider updating the docs to help other hitting this issue in your getting started docs.

dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json

**Comment by tdykstra** [comment]
The NuGet source is there by default unless it is explicitly removed. I wrote an issue to make this solution clearer in the article that has troubleshooting info for the NU1100 error.
