### ISSUE TITLE
Documentation VB.NET Tuple Returns incorrect

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#3165]
Submitted pull request #3166

In the code snippers of the documentation for VB.NET about Tuples, I found a small _error_.

Snippet 3 outputs the original string that is being parsed, rather than the output. It should output the result, as it is also being outputted in snippet 1 (the "original" version, before using the new language features). Another minor thing : the variable name of the "to be parsed string" maybe should match the original version?

Code to be changed:

```VB.NET
    Private Sub MethodCallWithTuple()
        ' <Snippet3>
        Dim number As String = "123,456"
        Dim result = ParseInteger(number)
        Console.WriteLine($"{IIf(result.Success, $"Success: {number:N0}", "Failure")}")
        Console.ReadLine()
        '      Output: Success: 123,456
        ' </Snippet3>
    End Sub
```

Into:

```VB.NET
    Private Sub MethodCallWithTuple()
        ' <Snippet3>
        Dim numericString As String = "123,456"
        Dim result = ParseInteger(numericString)
        Console.WriteLine($"{IIf(result.Success, $"Success: {result.Number:N0}", "Failure")}")
        Console.ReadLine()
        '      Output: Success: 123,456
        ' </Snippet3>
    End Sub
```

Also : sample does not work when using a non-US culture. Maybe specify in Snippet 2 invariant culture info?

Code to be changed:

```VB.NET
' <Snippet2>
Imports System.Globalization

Public Module NumericLibrary
    Public Function ParseInteger(value As String) As (Success As Boolean, Number As Int32)
        Dim number As Integer
        Return (Int32.TryParse(value, NumberStyles.Any, Nothing, number), number)
    End Function
End Module
' </Snippet2>
```

Into:

```VB.NET
' <Snippet2>
Imports System.Globalization

Public Module NumericLibrary
    Public Function ParseInteger(value As String) As (Success As Boolean, Number As Int32)
        Dim number As Integer
        Return (Int32.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, number), number)
    End Function
End Module
' </Snippet2>
```

**Comment by svick** [comment]
Do you want to create a Pull Request with these changes?

**Comment by Styxxy** [comment]
Currently I cannot sign the CLA, as I first neet to be approved by my company's legal department (which can take a long time). For that, I had to make an issue ticket (because I don't want this "mistake" to be lost).

I'm sorry for the inconvenience.

**Comment by BillWagner** [comment]
@Styxxy thanks for submitting PR #3166 and starting the process for the CLA.  That PR was small enough that a CLA wasn't necessary. I've already reviewed and merged it.

**Comment by Styxxy** [comment]
@BillWagner Thanks! I opened the issue as I thought that I needed a CLA. But I initiated the process anywa for maybe future pull requests.
