### ISSUE TITLE
DI documentation outdated

### ISSUE THREAD

**Issue by winderickxeli** [dotnet/docs#31665]
Hi, This page seems to be outdated. I'm trying to find information regarding the default Dependency Injection Framework but VS2022 and .NET6 don't resolve `Microsoft.Extensions` as the example uses... According to [this git page](https://github.com/dotnet/extensions) the content should have been implemented in the .NET runtime. I expected to find more information regarding this on this page...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @winderickxeli - if you follow the tutorial, it works. There is a NuGet package reference that you're instructed to install, [`Microsoft.Extensions.Hosting`](https://www.nuget.org/packages/Microsoft.Extensions.Hosting). This package takes a dependency on the [`Extensions.DependencyInjection`](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection) NuGet package which contains all the necessary DI bits. I'm going to close this issue, but please feel free to reply if there is still a concern, or if I have overlooked something. Thank you.
