### ISSUE TITLE
C# Inicio

### ISSUE THREAD

**Issue by BarbaraTito** [dotnet/docs#31662]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 37ce5a16-aa17-7f0b-3a6f-aa00cb17949c
* Version Independent ID: d714c86e-bb00-a07d-eb7e-e3235acb1fb8
* Content: [Os números em C# – Tutorial de introdução ao C# Interativo](https://learn.microsoft.com/pt-br/dotnet/csharp/tour-of-csharp/tutorials/numbers-in-csharp)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/numbers-in-csharp.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@BarbaraTito Can you provide more details about the issue at hand?
