### ISSUE TITLE
"Pass a value type by reference" states changes aren't visible from caller even though they are

### ISSUE THREAD

**Issue by hduregger** [dotnet/docs#31691]
The description of
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#pass-a-value-type-by-reference
states that
"...those changes **aren't** visible from the caller."
in both cases, even though they are as shown in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8dd92fe-5053-1bc6-1c8f-cf9f88635cb5
* Version Independent ID: 7241f712-8d73-b5e0-37c0-5f05c92412c6
* Content: [Method Parameters - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters)
* Content Source: [docs/csharp/language-reference/keywords/method-parameters.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/method-parameters.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @hduregger 

I've opened a PR to address this issue.
