### ISSUE TITLE
.NET CLI Tab Completion - zsh not evaluating full expression

### ISSUE THREAD

**Issue by gsferreira** [dotnet/docs#31706]
Following the instructions for Tab Completion with Zsh, I realized that the suggestions aren't correct when I'm looking for suggestions inside a command. 

Example: `dotnet add p` suggests `pack` and `publish` instead of `package`.

After digging into it, I realized that the $words variables only capture the last word on the terminal instead of the complete expression.

To fix it, I have updated the snippet to:
```
# zsh parameter completion for the dotnet CLI

_dotnet_zsh_complete()
{
  local words
  read -Ac words
  local completions=("$(dotnet complete "$words")")

  reply=( "${(ps:\n:)completions}" )
}

compctl -K _dotnet_zsh_complete dotnet
```

I'm more than happy to open a PR if you agree with the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Related to #31575?

**Comment by adegeo** [comment]
I'm literally looking at this right now and testing it 😁

**Comment by adegeo** [comment]
@gsferreira Hmmmm that script isn't working for me. it still just displays directories.

**Comment by gsferreira** [comment]
That is odd. 
I have a video here showing it: https://youtu.be/hCsoOVGLCfY 

I will get you the versions I'm using later today.

**Comment by adegeo** [comment]
I think its my WSH instance getting `dotnet.exe` and `dotnet` confused. I'll load it up in a virtual machine and test. Thanks!

**Comment by adegeo** [comment]
Nope, still not working on an Ubuntu install.

I did find a script that DOES work:

```zsh
# zsh parameter completion for the dotnet CLI

_dotnet_zsh_complete() 
{
  local completions=("$(dotnet complete "$words")")

  # If the completion list is empty, just continue with filename selection
  if [ -z "$completions" ]
  then
    _arguments '*::arguments: _normal'
    return
  fi

  # This is not a variable assigment, don't remove spaces!
  _values = "${(ps:\n:)completions}"
}

compdef _dotnet_zsh_complete dotnet
```

**Comment by adegeo** [comment]
@gsferreira Can you verify on mac that the script I posted works?

**Comment by gsferreira** [comment]
In fact, I have an error loading Zsh config: `command not found: compdef`

Zsh Version: zsh 5.9 (arm-apple-darwin21.3.0)
