### ISSUE TITLE
Please include an example for the framework argument

### ISSUE THREAD

**Issue by ejsealms** [dotnet/docs#31748]
I need to specify my framework for my solution to build. 

Is it dotnet build <.sln> --framework 4.7.2?
Is it dotnet build <.sln> --framework net472?
Is it dotnet build <.sln> --framework 472?

Please update the page with an example so people like me don't waste so much time on this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@ejsealms Thanks for the suggestion. I'm adding examples in PR #31754.
