### ISSUE TITLE
Make Custom Templates topic sample consistent

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#3175]
The Custom Templates topic sample isn't consistent with the other templates in the `dotnet-template-samples` repo. Topic work tracked here by this issue. The templates repo work tracked by https://github.com/dotnet/dotnet-template-samples/issues/29.

@mairaw I'll work on this if it's ok with you. I can't really call this a mistake, since the sample wasn't intended to be part of the templates repo when I wrote the topic and built the sample; however, I feel a measure of responsibility to make it consistent.

https://docs.microsoft.com/dotnet/core/tools/custom-templates
*docs/core/tools/custom-templates.md*

**Comment by guardrex** [comment]
btw- This work is blocked by https://github.com/dotnet/dotnet-template-samples/issues/29, so I'll track on that and then solve this issue after the naming scheme is resolved there.

**Comment by mairaw** [comment]
Thanks @guardrex. You're way more familiar with that than I am so, of course, I welcome your contribution!

**Comment by mairaw** [comment]
It seems that the blocking issue is still open so moving to backlog.

**Comment by guardrex** [comment]
@mairaw I'll be free after the 18th. I'll TAL over there and probably offer to [@]sayedihashimi to make all of them consistent. Once they're stable over there, I'll mirror the sample over here with the changes.

**Comment by mairaw** [comment]
Not sure who's taking over that area. I saw today that he's moving to another team.

**Comment by guardrex** [comment]
Ah ... I see. I'll check in with them over there right after the contract ends and see if there's an opportunity for me to fix them up. I'll let you know how it turns out.

**Comment by guardrex** [comment]
@mairaw I was just looking over the templates in the [dotnet/dotnet-template-samples](https://github.com/dotnet/dotnet-template-samples) because I was about to ask over there if they need/want help with consistency.

WRT the topic over here, the following few entries *are* a bit more real-world than what they'll end up with over there (e.g., `MyProject.01.Sample.CSharp`). It just boils down for this topic to what is shown for ...

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "Catalina Garcia",
  "classifications": [ "Common", "Console" ],
  "identity": "GarciaSoftware.ConsoleTemplate.CSharp",
  "name": "Garcia Software Console Application",
  "shortName": "garciaconsole"
}
```
... and that's really probably ok over here.

The problem really seems to be consistency within their template sample set, especially the way this particular sample was just shoved in over there, plus some other consistency problems within the first 15 samples they have.

Perhaps it's best just to close this. I don't see any detriment to readers using *Ms. Catalina's example* here.

**Comment by tdykstra** [comment]
> Perhaps it's best just to close this. 

Closing.
