### ISSUE TITLE
Official PE specification should also be updated

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/docs#31768]
Since the .NET compiler is adding new PE Debug Directories definitions _and_ since they are directly/indirectly tied to Microsoft, it makes sense that the official PE specification found [here](https://msdn.microsoft.com/library/windows/desktop/ms680547(v=vs.85).aspx) should be updated to include the new Debug Directories defined at https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md.

**Comment by gewarren** [comment]
The spec in question is this one: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format. @stevewhims Where can/should I move this issue for Win32 docs?
