### ISSUE TITLE
Wrong result specified.

### ISSUE THREAD

**Issue by rjamesnw** [dotnet/docs#31775]
Where it says `Console.WriteLine(toLast - toFirst);  // output: 2` is wrong.  30-10 would be 20, so a "0" is missing. ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7745abe8-d86e-2aea-ac99-45d955498838
* Version Independent ID: 30ba9979-6699-eb10-a397-53e0ed2be6a9
* Content: [fixed statement - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/fixed#feedback)
* Content Source: [docs/csharp/language-reference/statements/fixed.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/fixed.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@rjamesnw the difference is between the pointers, not the values they point to. And that difference is the number of elements that fit into that memory range

**Comment by BillWagner** [comment]
Hi @rjamesnw 

The current article is correct, as @pkulikov points out. Is there something we should add to the text to make that more clear?

If you have suggestions, let us know.

**Comment by rjamesnw** [comment]
Sorry, didn't get the past notifications.  Why does subtracting two pointers equal 2?  That doesn't make any sense at all. I think some clarification is required there. If I convert the pointers to `long` the result is 8, but the pointers themselves are 2? That's not very intuitive.

**Comment by rjamesnw** [comment]
Sorry, just got the notifications.  I did a test in C++ and seems the same thing happens with a typed pointer. I guess it's been too long and just forgot lol, but yeah ok, nm then I guess, thanks. ;)
