### ISSUE TITLE
Ty

### ISSUE THREAD

**Issue by mervy93** [dotnet/docs#31803]
#31802 #28123 #31801 
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET console application using Visual Studio - .NET](https://learn.microsoft.com/en-au/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mervy93** [comment]
#31802

**Comment by tdykstra** [comment]
The linked issues are not related to this introductory tutorial for VS.
