### ISSUE TITLE
Why isn't "https://learn.microsoft.com/en-us/dotnet/standard/threading/threading-objects-and-features" maintained in "https://learn.microsoft.com/en-us/dotnet/core/introduction" catalog?

### ISSUE THREAD

**Issue by DaneSpiritGOD** [dotnet/docs#31800]
[Enter feedback here]

*Threading* is a very important topic of dotnet. Why isn't [this page](https://learn.microsoft.com/en-us/dotnet/standard/threading/threading-objects-and-features) included in [dotnet learn page](https://learn.microsoft.com/en-us/dotnet/core/introduction)?
I spent a lot of time on looking for this topic...
Will this be a plan to include it into root catalog of dotnet?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1782d18-fc41-cd33-39ed-813941fd9e73
* Version Independent ID: 356863d9-c1b2-8566-7d91-59a187607ca6
* Content: [Overview of synchronization primitives](https://learn.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives)
* Content Source: [docs/standard/threading/overview-of-synchronization-primitives.md](https://github.com/dotnet/docs/blob/main/docs/standard/threading/overview-of-synchronization-primitives.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
Seems okay to add a link from https://learn.microsoft.com/en-us/dotnet/core/introduction to https://learn.microsoft.com/en-us/dotnet/standard/threading/managed-threading-basics.

**Comment by DaneSpiritGOD** [comment]
I have received.

**Comment by DaneSpiritGOD** [comment]
I have received.
