### ISSUE TITLE
What is the purpose of CA2254?

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#31814]
The documentation page tells me it's desirable to maintain placeholders in log messages. I don't know what that means. My log is a list of message strings. There are no placeholders, just the final message to log. So where do these placeholders exist other than the source code? Please explain what all the buzz is about. To me this seems rather pointless.

Then, Visual Studio 2022 gives me that message on a code line like this:

    logger.LogError(ex, ex.GetRecursiveMessage());

I don't see how it even applies here or what I'm doing wrong or could change. Code fixes suggests me to add the `message:` parameter name but that seems unrelated to the warning/information.

Also, if parameters should be preserved in some obscure ways, why not use the string interpolation that is used in SQL commands with EF Core? It has some magic power to see behind such strings with embedded parameters like `$"where id = {id}"` and knows how to escape them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to https://github.com/dotnet/roslyn-analyzers/issues/5626.

**Comment by gavinBurtonStoreFeeder** [comment]
The original concept is this;
Suppose your logs look like this,

```
Could not find Foos for user Bob Bobson
Could not find Foos for user Alice Aliceworth
```

This is difficult to aggregate, 

CA2254 comes from practical experience - they're trying to save you time. It wants your messages to look like this;

```
Could not find Foos for user {firstName} {lastName}
Could not find Foos for user {firstName} {lastName}
```

So here, we see that there were two instances of not being able to find foos.

The reason they do this is that in microsoft's internal code, ILogger is a direct dependency, so they do a lot of manually formatting log messages with templates, string interpolation, etc. From their perspective, this warning makes 100% sense.

But if you are using ILogger as an implementaiton detail and have a different contract as a dependency, you won't necessarily understand what they're talking about

**Comment by gewarren** [comment]
I'm going to close the issue now. Please leave a comment if it's not resolved to your satisfaction. If you have feedback about the rule itself rather than the documentation, log a new issue at the dotnet/roslyn-analyzers repo.
