### ISSUE TITLE
Docs about "pattern-based usings" is incorrect

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/docs#31815]
The section about "pattern-based usings" is wrong. It states that pattern-based usings is a feature available for all types, but that's not the case according to:

* https://github.com/dotnet/roslyn/issues/40353
* https://github.com/dotnet/roslyn/blob/main/docs/features/enhanced-using.md

which say that pattern-based usings only work for ref structs and in async scenarios.

And here's a sharplab repro for the example used in the broken documentation: https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAOgCUBXGAFyjAFMCBJC6gJwHsAHAZWYDcoBjagGcA3AFgAUBPQAmbAEE2bCQG8J2dbgDMuPADZcAFmwBZaDGwAKAJRqNq8Rse4cF7hCbYPAXmwxqAd2wiIRYSJgFrGwcndXsYmIB6BOxBcghyahoKQVsYgF9c7ALo7AliqVlgwVDw6hVSkq1DbAARKEE2FkFqa2xlIrKJIA===

> error CS1674: 'Resource': type used in a using statement must be implicitly convertible to 'System.IDisposable'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc900853-b666-5815-9d69-e408af3e3900
* Version Independent ID: 77f3af83-d0ca-7d48-d06d-0f28f5f05a49
* Content: [Pattern based using and using declarations - C# 8.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using#pattern-based-using)
* Content Source: [proposals/csharp-8.0/using.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/using.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 32628](https://dev.azure.com/msft-skilling/Content/_workitems/edit/32628)

**Comment by BillWagner** [comment]
Thanks for noting this @rolfbjarne 

I've added it to our November sprint. I've also added the "help wanted" label, in case anyone wants to contribute a fix before I get to this.
