### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by kalatchev** [dotnet/docs#31938]
When string interpolation is used, such as 
```
Logger.LogError(ex, $"Error loading Sample with barcode '{rec.Key}' from Sync database.");
```
the rule shouldn't be fired.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by gfoidl** [comment]
Well, I think it should fire, as using string interpolation is against the goal of having structured data in the logs (also cf. https://messagetemplates.org).
So the given "Rule description" is correct and IMO clear.

Why do you think it shouldn't fire and what's the use case / motivation for not using (static) message templates?
