### ISSUE TITLE
Provide examples with method syntax

### ISSUE THREAD

**Issue by alex47** [dotnet/docs#31958]
The examples show how to do join with query syntax, but provides no examples with method syntax.
We use the method syntax exclusively everywhere in our projects and this would really benefit us and others who prefer the method syntax more.

There seems to be a similar example here: https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.join?view=net-6.0#system-linq-enumerable-join-4(system-collections-generic-ienumerable((-0))-system-collections-generic-ienumerable((-1))-system-func((-0-2))-system-func((-1-2))-system-func((-0-1-3)))

It would be great to also have it on this page as well.

Reference: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/query-syntax-and-method-syntax-in-linq

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8fbdf8-317e-2c98-972e-180ff8b5a2b3
* Version Independent ID: 6389f1e8-d48b-3b16-bbc1-fe1711eb0177
* Content: [Perform inner joins (LINQ in C#)](https://learn.microsoft.com/en-us/dotnet/csharp/linq/perform-inner-joins)
* Content Source: [docs/csharp/linq/perform-inner-joins.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/perform-inner-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a very good suggestion @alex47 

I've added it to our backlog to address.

I've also added the help wanted label, if any community contributor wants to add that sample.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this.

**Comment by BillWagner** [comment]
> I will work on this.

Thanks @BartoszKlonowski 

I've assigned it to you.
