### ISSUE TITLE
Misleading documentation regarding cross-platform framework-dependent publish

### ISSUE THREAD

**Issue by 414004738** [dotnet/docs#31964]
The documentation states the following:

> Publish an app **cross-platform** framework-dependent. A Linux 64-bit executable is created along with the dll file.
> `dotnet publish -r linux-x64 --self-contained false`

However, this command will not necessarily publish something that is **cross-platform**. It will not include the runtimes/\<RID\> folders and files that include platform-specific libraries and native assemblies that would be needed to run on platforms other than what is specified by the -r flag.

I think what this command is doing is a **platform-specific**, framework-dependent publish. It isn't only controlling the type of executable, but also controls which platform-specific dependencies are included.

Note that the document also claims:
> Apps published as framework-dependent are cross-platform

Which doesn't seem to always be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [Application publishing - .NET](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 50930](https://dev.azure.com/msft-skilling/Content/_workitems/edit/50930)

**Comment by adegeo** [comment]
Hello. Thank you for bringing this up, I'll update the documentation to make this clearer.
