### ISSUE TITLE
Missed content of .vscode folder

### ISSUE THREAD

**Issue by ivan-nosar** [dotnet/docs#31968]
I was trying to set up the basic.Net app and start debugging in VS Code and found an inconvenience in docs: It seems like a description of the `.vscode` folder content is missing here. It obviously must contain at least one file (`launch.json`) since the next page `Tutorial: Debug a .NET console application using Visual Studio Code` references it in a sentence: "Open _.vscode/launch.json._"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET console application using Visual Studio Code - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 57899](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57899)

**Comment by ivan-nosar** [comment]
After a small investigation, I found that the following content shall fit the basic requirements for debugging  of local console app:

- `.vscode/launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }
    ]
}
```

> **Note**: Please, don't forget to set up the `program` property properly

- `.vscode/tasks.json`:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "process",
            "command": "dotnet",
            "args": [ "msbuild" ],
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

Most likely there may be some better/newer solutions, this is only what I managed to find quickly

**Comment by tdykstra** [comment]
The tutorial mentions `.vscode`:

>The first time you edit a `.cs` file, Visual Studio Code prompts you to add the missing assets to build and debug your app. Select Yes, and Visual Studio Code creates a `.vscode` folder with `launch.json` and `tasks.json` files.

And it explains what to do if you don't get the prompt for missing assets:

> * Select **Run** > **Add Configuration** from the menu.
> * Select **.NET 5+ and .NET Core** at the **Select environment** prompt.
