### ISSUE TITLE
Linked from message in terminal to install .NET prerequisites. Not referenced in the page of how to do this Windows 11 22H1

### ISSUE THREAD

**Issue by hairagon** [dotnet/docs#31977]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#dependencies)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Can you give me more information? What link were you given? What are you trying to do? If you're trying to install .NET, this page should have all of the info you require.

**Comment by hairagon** [comment]
This is the 1st comment I have received on the issue. No request for further details was emailed to me hence no response.
Keep this closed as experience has shown that many links point to generic responses that lack the detail needed, some even referring to differing languages from that in the question.
In most cases they say what is wrong, and what should be done but with so little detail it requires more searches which often lead you in a circular route,

I would have thought that the feedback would have included details of what I was commenting on rather than being a generic input form.



Best Regards

Charles Cartmel

***@***.***

**Comment by gewarren** [comment]
Closing per OP's previous comment.
