### ISSUE TITLE
Add advise when to use NoWarn and when to refrain from it 

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/docs#31976]
Currently the section [NoWarn](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings?%3FranMID=24542&ranEAID=PqGoi0DnEyQ&ranSiteID=PqGoi0DnEyQ-7vxcqYgW96eeIFTkkF8CRw&epi=PqGoi0DnEyQ-7vxcqYgW96eeIFTkkF8CRw&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=(ir__19ndjvbomwkf63uje1vtclayi22xqvnxd2hez6ml00)(7593)(1243925)(PqGoi0DnEyQ-7vxcqYgW96eeIFTkkF8CRw)()&irclickid=_19ndjvbomwkf63uje1vtclayi22xqvnxd2hez6ml00#nowarn) has no advise or hints if and when this option should be used. 
A dev at our company was asked to remove the warnings. What was meant was to remove the underlying cause. But the change that was made was to add `<NoWarn>....</NoWarn>` to Foo.csproj:

```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>    
    <NoWarn>
       $(NoWarn);NU1701;CA1416;CS0108;CS8618;CS1998;CS8602;CS8600;CS8603;CS8601;CS8634;CS8629;CS8604;CS0169
    </NoWarn>
  </PropertyGroup>
```
Many warnings that are suppressed can be found at [Resolve nullable warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings)

I hope that adding an advise or guideline when and how to use `NoWarn` either to this page or a new page would be helpfull. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings?%3FranMID=24542&ranEAID=PqGoi0DnEyQ&ranSiteID=PqGoi0DnEyQ-c3Wg_cQFeBcNNtf60eMAcQ&epi=PqGoi0DnEyQ-c3Wg_cQFeBcNNtf60eMAcQ&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=(ir__19ndjvbomwkf63uje1vtclayi22xqvnx22hez6ml00)(7593)(1243925)(PqGoi0DnEyQ-c3Wg_cQFeBcNNtf60eMAcQ)()&irclickid=_19ndjvbomwkf63uje1vtclayi22xqvnx22hez6ml00)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by surfmuggle** [comment]
Many warnings that are supprassed above can be found at [Resolve nullable warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings)

**Comment by BillWagner** [comment]
That's a good suggestion @surfmuggle 

I've added it to our backlog, and added the "help wanted" label.

My personal thought is that `NoWarn` should indicate that you (the developer) are certain the warning is a false positive, and can't possibly be a possible runtime bug.
