### ISSUE TITLE
no more ConfigureServices

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#31981]
the "Configuring EF Core" text at https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps#configuring-ef-core makes explicit reference to ConfigureServices (i.e. the old Startup way of achieving ConfigureServices and Configure) whereas latest code condenses this  into the main code instead. Likewise the subsequent para again explicitly notes ConfigureServices [there are currently 5 refs to "ConfigureServices "]. Better if these docs are less [or more!] specific.

Incidentally the "a connection string defined in Configuration" text is also erroneous as that Configuration is not itself a string but a container and requires the GCS method call to lookup the stated DefaultConnection key to find the actual connectionstring. Again that old-style may have previously captured that container in a ctor but the docs here merely invent it as magic.

The simplistic "Eager=good, lazy=bad" guidance makes no mention of the "Cartesian Explosion" downside (cf. https://www.thinktecture.com/en/entity-framework-core/cartesian-explosion-problem-in-3-1/), nor the .AsSplitQuery() consideration. I accept this may be too deep for an intro doc, but it does mention the Dev vs Prod perf issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by erjain** [comment]
Adding @ardalis to this.

**Comment by ardalis** [comment]
Thanks for the feedback @DickBaker. I'm updating the content to be more clear. Note that nowhere did it say that `Configuration` was a string, so I'm not sure about that comment. Also Eager/Lazy are separate concerns from query splitting and cartesian explosion problems, correct? I agree it's probably worth a mention but not in any related fashion.
