### ISSUE TITLE
A

### ISSUE THREAD

**Issue by JOKRAX** [dotnet/docs#31988]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ learn.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2
* Version Independent ID: fdb655a4-cff4-6c67-7244-673760379663
* Content: [Get started with .NET](https://learn.microsoft.com/th-th/dotnet/core/get-started)
* Content Source: [docs/core/get-started.md](https://github.com/dotnet/docs/blob/main/docs/core/get-started.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. It looks like you didn't mean to open this issue. I'll close it. Please feel free to file an issue in the future if you have a problem.
