### ISSUE TITLE
docs about perf woefully ancient

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#31986]
in "EF Core or micro-ORM?" at https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps#ef-core-or-micro-orm the docs refer back to 2016 era which is a great dis-service to EF6. Shay wrote "Entity Framework Core 6.0 Preview 4: Performance Edition" well in  May 2016 at https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-4-performance-edition/, and EF team isteadily mproved since as per https://learn.microsoft.com/en-us/ef/core/performance/

Quoting old opinions has negligible relevance to today (or we'd all be still writing FORTRAN/COBOL)

Suggest you read & enjoy these quotes
•	1833 [Johann Wolfgang von [Goethe]](https://quotepark.com/quotes/1764978-johann-wolfgang-von-goethe-nothing-is-more-damaging-to-a-new-truth-than-an-ol/)
•	1990 [Edward Abbey](https://quotepark.com/quotes/1740661-edward-abbey-nothing-could-be-older-than-the-daily-news-nothin/)
•	1990 [Edward Abbey](https://quotepark.com/quotes/882823-edward-abbey-anarchism-is-founded-on-the-observation-that-since/)                       [for “rule” read “teach”]
•	1990 [Edward Abbey](https://quotepark.com/quotes/1055343-edward-abbey-better-a-cruel-truth-than-a-comfortable-delusion/)
•	2001 [Ursula K. Le Guin](https://quotefancy.com/quote/924817/Ursula-K-Le-Guin-I-d-rather-get-bad-news-from-an-honest-man-than-lies-from-a-flatterer)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Are you able to assign to me?

**Comment by erjain** [comment]
> Are you able to assign to me?

Sorry, Steve, I was not able to assign it to you. Maybe less privilege. Thanks for the PR.
