### ISSUE TITLE
Include via a.b.c strings is fragile

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#31982]
the "Fetching related data" rightly introduces "Items.Products" -style overload, but fails to comment that this is fragile and likely to be missed by refactoring (whereas the Function overload will be correctly handled).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by erjain** [comment]
Hi @DickBaker, thanks for your suggestion. This is mentioned here just for showing the alternate way to include navigation properties. Yeah, you may be right that during refactoring developers should be aware of such statements. I believe we are good to close this issue.

**Comment by IEvangelist** [comment]
Closed per @erjain
