### ISSUE TITLE
API reference should include packages for classes

### ISSUE THREAD

**Issue by svick** [dotnet/docs#320]
The API reference for a class includes its namespace and assembly, just like it does for .Net Framework on MSDN. But for .Net Core, the NuGet package is much more important than the assembly, but it's not shown.

This information can be found through https://packagesearch.azurewebsites.net/, but I think it should be included directly in the API reference.

Showing packages for namespaces would likely be more complicated (since there can be more than one), but I think it would be useful too.

**Comment by mairaw** [comment]
@dend we do have an internal feature request tracking this right?

**Comment by mairaw** [comment]
Internal tracking bug: [1039115](https://mseng.visualstudio.com/CSI/_workitems?id=1039115&_a=edit&triage=true)

**Comment by svick** [comment]
There is a proposed design on how to fix this: https://github.com/dotnet/designs/pull/25.

**Comment by BillWagner** [comment]
Closing. Moved to MicrosoftDocs/Feedback#439
