### ISSUE TITLE
Where do I look at these values(Garbage Collection ETW Events)

### ISSUE THREAD

**Issue by RenCisco** [dotnet/docs#32020]
i am debugging the  azure function program locally.
when i open Diagnostic Tools running more 40 minutes that will happen Frequent garbage collection (most of Generation 1GC and 
few 2GC).
my OS is .net 6 and windows 10.

so ,how can i solve this issue? thanks ! can you help me? 

![image](https://user-images.githubusercontent.com/21196303/197695619-f1f089b9-e3fe-411d-90c4-b8c504a9cc67.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e864e1e3-c8ed-a993-8e72-372e30f6610c
* Version Independent ID: eb24522a-de26-44e6-75fc-4a332fe45501
* Content: [Garbage Collection ETW Events - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events#gcstart_v1-event)
* Content Source: [docs/framework/performance/garbage-collection-etw-events.md](https://github.com/dotnet/docs/blob/main/docs/framework/performance/garbage-collection-etw-events.md)
* Product: **dotnet-framework**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@mangod9 Can you help with this question?

**Comment by mangod9** [comment]
@RenCisco, could you please clarify what you are looking to diagnose? Are you trying to find why gen1 and 2 GCs are happening within your function?
