### ISSUE TITLE
`LambdaExpression`/`Expression` really natural `System.Linq.Expressions.Expression<TDelegate>`?

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#32024]
> If you assign a lambda expression to [System.Linq.Expressions.LambdaExpression](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.lambdaexpression), or [System.Linq.Expressions.Expression](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression), and the lambda has a natural delegate type, the expression has a natural type of [System.Linq.Expressions.Expression<TDelegate>](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1), with the natural delegate type used as the argument for the type parameter:

Exactly phrase "_the expression has a natural type of System.Linq.Expressions.Expression<TDelegate>_" renders slightly improper.

```csharp
LambdaExpression parseExpr = (string s) => int.Parse(s);
Expression<Func<string, int>> x = (Expression<Func<string, int>>) parseExpr; // ok

var parseExprType = parseExpr.GetType();
var referalType = typeof(Expression<Func<string, int>>);

Debug.Assert(parseExprType.GetGenericArguments()[0] == referalType.GetGenericArguments()[0]); // ok
Debug.Assert(parseExprType == referalType); // fail
```

```csharp
Console.WriteLine(parseExprType.Name);
Console.WriteLine(referalType.Name);
```
```console
Expression1`1
Expression`1
```

Seems that expression is not truly `Expression<TDelegate>` but rather some `Expression1<TDelegate>`.

---

This is turn casts bleak light on 

```csharp
LambdaExpression parseExpr = (string s) => int.Parse(s); // Expression<Func<string, int>>
Expression parseExpr = (string s) => int.Parse(s)        // Expression<Func<string, int>>
```
`Expression<Func<string, int>>` != `Expression1<Func<string, int>>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#natural-type-of-a-lambda-expression)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
adding @cston 

This part of the article is based on my understanding of [natural function type](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/lambda-improvements.md#natural-function-type). What did I miss?

**Comment by svick** [comment]
[The type `Expression1<T>`](https://github.com/dotnet/runtime/blob/8ace754/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L384) is an internal implementation detail of the runtime and it inherits from `Expression<T>`. I think the language is not promising you that the runtime type will be exactly `Expression<T>`, only that that `parseExpr is Expression<Func<string, int>>` will be `true` (which you already verified by casting to it).

So I think the documentation is correct as is.

**Comment by bravequickcleverfibreyarn** [comment]
> is an internal implementation detail

Yes of course. Maybe it can be found confusing that `delegate` type is inferred in its public _visage_ while `Expression` gets some internal one and documentation can be sensed differently.

> So I think the documentation is correct as is.

Yes, of course it is just my personal expectation that it should be exact type not just kind of type. FMPOV this can be closed.

---

I briefly looked over internal `Expression0` and others and saw them [inheriting](https://github.com/dotnet/runtime/blob/8ace7540515483a9bd39a735323aa5a7632dc600/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L384) `Expression<TDelegate>` . Documentation for [`Expression<TDelegate>` Class](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1?view=net-6.0) shows it declared as `sealed`. 

I am not sure if this is intentional documentation hack or microbug.
