### ISSUE TITLE
nonsense

### ISSUE THREAD

**Issue by stevecarnell** [dotnet/docs#32021]
Why have links in visual studio that take you to this page.  Absolute nonsense.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS7036))
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @stevecarnell 

We know that there is a large backlog of compiler errors are warnings that we haven't covered properly. We're working on catching up on these.

The F1 service in Visual Studio routes to this page so we can track which errors and warnings customer are asking for the most. That helps us prioritize which pages are added first.

See #5410 for more details on our plans.

I'm going to close this, as it doesn't add more information on the specific error that brought you here. I do have internal analytics that track all visits to this page, so it won't be lost.
