### ISSUE TITLE
apt-get install dotnet6 does not install the SDK as the documentation states

### ISSUE THREAD

**Issue by joeskeen** [dotnet/docs#32033]
I am running Linux Mint:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
$ cat /etc/upstream-release/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu Jammy Jellyfish"
```

I'm following the instructions here: <https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu?source=recommendations#install-the-sdk>. The documentation states:
> To install the .NET SDK, run the following commands:
```bash
sudo apt-get update && \
  sudo apt-get install -y dotnet6
```
After running the commands I can run `dotnet --info`:
```
$ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
> .NET SDKs installed:
>  No SDKs were found.

Thus it appears that it only installs the dotnet runtime and not the SDK. I'm not sure if this is a docs issue, or an issue with the package. Regardless, I'm not sure how I would go about installing the SDK from the package manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu?source=recommendations)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @joeskeen it sounds like you have a mixup problem where the runtime is being installed from one source and the sdk from another (or vice versa)

I did a search on the dotnet product issues and found this: https://github.com/dotnet/core/issues/7699

I'll update https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup with some more information.

I'm going to close this issue as I'm pretty sure this is the source of your problem. Feel free to comment or reopen it if you're still stuck, but you probably want to ask in the product repo as you'll have more people to help you out.
