### ISSUE TITLE
[Docs] Update article about shutting down a silo

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32047]
An internal partner ran into this while upgrading their solution to be cross-platform: the shutting down article is out of date and refers to Console.CancelKeyPress event. Instead, we should be using IHostBuilder's `UseConsoleLifetime()` method to handle shutdown or `IHostBuilder.RunConsoleAsync()` to add the console lifetime, build the builder, and run the host.

https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/shutting-down-orleans

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 532956be-bed6-4c76-7eb8-8b45c5c8ba0e
* Version Independent ID: b6250c87-22a4-0c99-10d3-4efbdde23154
* Content: [Shut down Orleans silos](https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/shutting-down-orleans)
* Content Source: [docs/orleans/host/configuration-guide/shutting-down-orleans.md](https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/shutting-down-orleans.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 37739](https://dev.azure.com/msft-skilling/Content/_workitems/edit/37739)

**Comment by IEvangelist** [comment]
Fixed by #32108
