### ISSUE TITLE
"Caller argument expression" documentation still reads like a proposal rather than an implemented feature

### ISSUE THREAD

**Issue by CalebBellWebCE** [dotnet/docs#32042]
If I understand things correctly, this feature has been implemented in C#10.  However, there are some spots in this docs page that make it sound as if this is a tentative feature whose design is still in flux.  Some examples:
* The end of the "Detailed design" section says "If this language feature was implemented, the proposal could be updated to take advantage of this feature."  This sentence could probably be removed given that this language feature has now been implemented.
* I haven't used this feature yet, but the presence of the "Alternatives" section is confusing to me.  Are these ideas that were considered and ultimately rejected?  If so, it seems like they would be better to leave in the proposal discussion on GitHub rather than in the actual docs page.
* The page does not link to the actual CallerArgumentExpression attribute docs page: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute
* The page has (empty) "Unresolved questions" and "Design meetings" sections at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5d9ede5-d454-ad2c-9b49-30ccde7edaf3
* Version Independent ID: 0d087957-2ceb-554c-1b52-c20cbef1cacd
* Content: [Caller argument expression - C# 10.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/caller-argument-expression#feedback)
* Content Source: [proposals/csharp-10.0/caller-argument-expression.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/caller-argument-expression.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @CalebBellWebCE 

You're right that this article is the original feature spec for the caller argument expression feature that shipped in C# 10.0.


The [language reference](https://learn.microsoft.com/dotnet/csharp/language-reference/attributes/caller-information#argument-expressions) has been updated to include this feature.

The C# standards committee is catching up with the C# implementation. The committee is currently finalizing the official standard for C# 7.x.  While the committee catches up, we've been publishing these feature specs to provide the details on each feature now.

I'll close this, as the current plan is to continue updating the standard, and remove these feature specs once the standard has been updated.
