### ISSUE TITLE
Double await in WhenAny example

### ISSUE THREAD

**Issue by unsalersoz** [dotnet/docs#32069]
The example under the paragraph which starts with: "_Another option is to use [WhenAny](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenany), which returns a Task<Task> that completes when_"

The finished task awaited again before being removed.
"_await finishedTask_;"

On the example when all of them put together: "_After all those changes, the final version of the code looks like this:_":
It is correct in that example. Second await is **not** there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**
![Problem](https://user-images.githubusercontent.com/7429343/198560789-c05530e1-c2b0-4623-a8c1-d7867fff391d.png)

**Comment by IEvangelist** [comment]
Fixed by #32059

**Comment by minsouk** [comment]
I think Await finishedTask shouldn't be deleted. Await finishedTask was executed after receiving the already completed Task by Task.WhenAny. Therefore, waiting is not affected by execution time. Otherwise, exceptions that run asynchronously cannot be caught. Test the fire scenario.

**Comment by minsouk** [comment]
// check this code~


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwaitException
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;

    namespace AsyncBreakfast
    {
        // These classes are intentionally empty for the purpose of this example. They are simply marker classes for the purpose of demonstration, contain no properties, and serve no other purpose.
        internal class Bacon { }
        internal class Coffee { }
        internal class Egg { }
        internal class Juice { }
        internal class Toast { }

        class Program
        {
            static async Task Main(string[] args)
            {
                Coffee cup = PourCoffee();
                Console.WriteLine("coffee is ready");

                Stopwatch stopwatch = new Stopwatch(); //객체 선언
                stopwatch.Start(); // 시간측정 시작

                try
                {
                    var eggsTask = FryEggsAsync(2);
                    var baconTask = FryBaconAsync(3);
                    var toastTask = MakeToastWithButterAndJamAsync(0);

                    var breakfastTasks = new List<Task> { eggsTask, baconTask, toastTask };
                    while (breakfastTasks.Count > 0)
                    {
                        Task finishedTask = await Task.WhenAny(breakfastTasks);
                        if (finishedTask == eggsTask)
                        {
                            Console.WriteLine("eggs are ready");
                        }
                        else if (finishedTask == baconTask)
                        {
                            Console.WriteLine("bacon is ready");
                        }
                        else if (finishedTask == toastTask)
                        {
                            Console.WriteLine("toast is ready");
                        }
                        //await finishedTask;
                        breakfastTasks.Remove(finishedTask);
                    }

                    Juice oj = PourOJ();
                    Console.WriteLine("oj is ready");
                    Console.WriteLine("Breakfast is ready!");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($@"ex {ex.Message}");
                }
                finally
                {
                    stopwatch.Stop(); //시간측정 끝
                    Console.WriteLine($@"time : {stopwatch.ElapsedMilliseconds} ms");
                }
            }

            static async Task<Toast> MakeToastWithButterAndJamAsync(int number)
            {
               
               var  toast = await ToastBreadAsync(number);
                    ApplyButter(toast);
                    ApplyJam(toast);
                
                return toast; 
            }

            private static Juice PourOJ()
            {
                Console.WriteLine("Pouring orange juice");
                return new Juice();
            }

            private static void ApplyJam(Toast toast) =>
                Console.WriteLine("Putting jam on the toast");

            private static void ApplyButter(Toast toast) =>
                Console.WriteLine("Putting butter on the toast");

            private static async Task<Toast> ToastBreadAsync(int slices)
            {
                double s = 1 / slices;
                Console.WriteLine($@"슬라이스를 {s} 조각으로 나누었습니다. ");
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("Putting a slice of bread in the toaster");
                }

                await Task.Delay(3000);
                Console.WriteLine("Remove toast from toaster");
                return new Toast();
            }

            private static async Task<Bacon> FryBaconAsync(int slices)
            {
                Console.WriteLine($"putting {slices} slices of bacon in the pan");
                Console.WriteLine("cooking first side of bacon...");
                await Task.Delay(3000);
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("flipping a slice of bacon");
                }
                Console.WriteLine("cooking the second side of bacon...");
                await Task.Delay(3000);
                Console.WriteLine("Put bacon on plate");

                return new Bacon();
            }

            private static async Task<Egg> FryEggsAsync(int howMany)
            {
                Console.WriteLine("Warming the egg pan...");
                await Task.Delay(3000);
                Console.WriteLine($"cracking {howMany} eggs");
                Console.WriteLine("cooking the eggs ...");
                await Task.Delay(3000);
                Console.WriteLine("Put eggs on plate");

                return new Egg();
            }

            private static Coffee PourCoffee()
            {
                Console.WriteLine("Pouring coffee");
                return new Coffee();
            }
        }
    }
}

**Comment by minsouk** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwaitException
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;

    namespace AsyncBreakfast
    {
        // These classes are intentionally empty for the purpose of this example. They are simply marker classes for the purpose of demonstration, contain no properties, and serve no other purpose.
        internal class Bacon { }
        internal class Coffee { }
        internal class Egg { }
        internal class Juice { }
        internal class Toast { }

        class Program
        {
            static async Task Main(string[] args)
            {
                Coffee cup = PourCoffee();
                Console.WriteLine("coffee is ready");

                Stopwatch stopwatch = new Stopwatch(); //객체 선언
                stopwatch.Start(); // 시간측정 시작

                try
                {
                    var eggsTask = FryEggsAsync(2);
                    var baconTask = FryBaconAsync(3);
                    var toastTask = MakeToastWithButterAndJamAsync(0);

                    var breakfastTasks = new List<Task> { eggsTask, baconTask, toastTask };
                    while (breakfastTasks.Count > 0)
                    {
                        Task finishedTask = await Task.WhenAny(breakfastTasks);
                        if (finishedTask == eggsTask)
                        {
                            Console.WriteLine("eggs are ready");
                        }
                        else if (finishedTask == baconTask)
                        {
                            Console.WriteLine("bacon is ready");
                        }
                        else if (finishedTask == toastTask)
                        {
                            Console.WriteLine("toast is ready");
                        }
                        await finishedTask;
                        breakfastTasks.Remove(finishedTask);
                    }

                    Juice oj = PourOJ();
                    Console.WriteLine("oj is ready");
                    Console.WriteLine("Breakfast is ready!");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($@"ex {ex.Message}");
                }
                finally
                {
                    stopwatch.Stop(); //시간측정 끝
                    Console.WriteLine($@"time : {stopwatch.ElapsedMilliseconds} ms");
                }
            }

            static async Task<Toast> MakeToastWithButterAndJamAsync(int number)
            {
               
               var  toast = await ToastBreadAsync(number);
                    ApplyButter(toast);
                    ApplyJam(toast);
                
                return toast; 
            }

            private static Juice PourOJ()
            {
                Console.WriteLine("Pouring orange juice");
                return new Juice();
            }

            private static void ApplyJam(Toast toast) =>
                Console.WriteLine("Putting jam on the toast");

            private static void ApplyButter(Toast toast) =>
                Console.WriteLine("Putting butter on the toast");

            private static async Task<Toast> ToastBreadAsync(int slices)
            {
                double s = 1 / slices;
                Console.WriteLine($@"슬라이스를 {s} 조각으로 나누었습니다. ");
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("Putting a slice of bread in the toaster");
                }

                await Task.Delay(3000);
                Console.WriteLine("Remove toast from toaster");
                return new Toast();
            }

            private static async Task<Bacon> FryBaconAsync(int slices)
            {
                Console.WriteLine($"putting {slices} slices of bacon in the pan");
                Console.WriteLine("cooking first side of bacon...");
                await Task.Delay(3000);
                for (int slice = 0; slice < slices; slice++)
                {
                    Console.WriteLine("flipping a slice of bacon");
                }
                Console.WriteLine("cooking the second side of bacon...");
                await Task.Delay(3000);
                Console.WriteLine("Put bacon on plate");

                return new Bacon();
            }

            private static async Task<Egg> FryEggsAsync(int howMany)
            {
                Console.WriteLine("Warming the egg pan...");
                await Task.Delay(3000);
                Console.WriteLine($"cracking {howMany} eggs");
                Console.WriteLine("cooking the eggs ...");
                await Task.Delay(3000);
                Console.WriteLine("Put eggs on plate");

                return new Egg();
            }

            private static Coffee PourCoffee()
            {
                Console.WriteLine("Pouring coffee");
                return new Coffee();
            }
        }
    }
}
