### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by syntaxartisan** [dotnet/docs#32085]
I recommend updating the statement "the code block for the set accessor is executed when the property is assigned a new value" to remove the word "new". I interpret that to mean that the set accessor is only called if the value that's being provided is different than the value that the property currently contains. Of course that isn't true--the set accessor is called regardless of whether the value provided is a new value. It could just be semantics but that's how I interpret it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 322a60f9-0bd8-b432-653a-069c477a93fe
* Version Independent ID: dbc29edd-b142-f2d7-4824-dec9951f32c7
* Content: [Using Properties - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/using-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @syntaxartisan 

I've added this to our backlog, and added the "help-wanted" label to this issue.

**Comment by eli-entelis** [comment]
would like to help

**Comment by Viniciusap** [comment]
@eli-entelis Please, close this issue, it was merged.

**Comment by eli-entelis** [comment]
It doesn't seem I have permission. @syntaxartisan can you close this?

**Comment by Viniciusap** [comment]
Or @BillWagner could help us here too.

**Comment by BillWagner** [comment]
Thanks for the ping.

Closed as fixed in #32185
