### ISSUE TITLE
Bad command in docuementation

### ISSUE THREAD

**Issue by appliedcognetics** [dotnet/docs#32091]
this section  https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-the-sdk 

has the following code block 
sudo apt-get update && \
  sudo apt-get install -y dotnet6

I get  unable to locate package I think the name command should be :  sudo apt-get install -y dotnet-sdk-6.0  
and the   commands need to be run as stated later in the documentation

wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

or the user will get stuck

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@appliedcognetics Hello. If you're using 22.04, the package is available in the feed automatically without any extra configuration: https://packages.ubuntu.com/jammy/dotnet6
