### ISSUE TITLE
taking the "next step into hardware logic design".

### ISSUE THREAD

**Issue by Karl15** [dotnet/docs#32090]
This is exciting!  (FPGA)Chip design is key to (MS)Project Catapult and to chip design in general. Here we see the software side and as an old hardware designer I see this as a valuable step in chip design.

For far too long the hardware tools have been based on synthesis of hardware description rather than logical description.  It would be a lot like writing a program in MSIL rather than C# (for example).

I started with a simple source syntax and parser then used the Visual Studio IDE for build and debug.  I am pleased with the speed and simplicity of the result.

I will contribute to an opensource project, but I am not prepared to manage a project.

I repeat "this is exciting!"  Please keep up the good work and writing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5dba5b-eabc-8202-2854-6b1f4a7f971a
* Version Independent ID: 8b2e46f0-6d12-6ce9-944d-b883dcbe0808
* Content: [Using Delegates - C# Programming Guide](https://learn.microsoft.com/en-US/dotnet/csharp/programming-guide/delegates/using-delegates)
* Content Source: [docs/csharp/programming-guide/delegates/using-delegates.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/using-delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for your compliments.

Closing as kudos.
