### ISSUE TITLE
Consider adding usage examples for the `<include>` xml element

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#32118]
This is about the `<include>` section specifically: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#inheritdoc

There should be examples of how to structure the target xml file, as well as different ways of using the `file`, and `path` attributes, as well as the `@name` and `id`.

Unfortunately, I could not find any official documentation showing how to use this, and I had to resort to going deep into the google rabbit hole to find some examples from years ago. ☹️

The good news is that I am currently investigating this, so as soon as I have some working examples, I will share them here.

cc @gewarren

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcb925f-ef72-9a64-3762-c0b4a96f9dc4
* Version Independent ID: d135d0a6-53d2-1567-0b1b-7aae5e07739f
* Content: [Recommended XML documentation tags for a class and its members](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags)
* Content Source: [docs/csharp/language-reference/xmldoc/recommended-tags.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/recommended-tags.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 215486](https://dev.azure.com/msft-skilling/Content/_workitems/edit/215486)

**Comment by BillWagner** [comment]
I agree @carlossanlop

This is an area where our teams have created some great examples of using this in the product repos. Either the runtime, roslyn, or ASP.NET Core.

If I added pointers to those examples that already exist, would that be helpful? Or would it be better to create new (smaller) examples that demonstrate the feature in different scenarios?

**Comment by RussKie** [comment]
There's plenty of examples in the .NET Framework code, e.g. [this](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ToolStrip.cs,175).
