### ISSUE TITLE
[Breaking change]: Update Anchor Layout to support high DPI machines.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/docs#32145]
### Description

In .NET 8.0 Preview 1, Control anchor computations changed to support high dpi devices. Detailed documentation on changes is available here: https://github.com/dotnet/winforms/blob/main/docs/design/anchor-layout-changes-in-net80.md

### Version

.NET 8 Preview 1

### Previous behavior

Certain applications with SystemAware or PermonitorV2 aware mode and anchored controls were facing issues with layout on high dpi devices.

### New behavior

Applications with SystemAware or PermonitorV2 aware mode and anchored controls should have better layout when rendered on high dpi devices.

### Type of breaking change

- [X] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

We have been improving the user experience for WinForm on high Dpi monitors. This change is enabling the developers to use anchored layout for the applications on high dpi devices.

### Recommended action

If user wanted to opt-out of this new behavior, they could do so by setting `System.Windows.Forms.AnchorLayoutV2` to `false` in runtimeconfig.json file as defined [here](https://github.com/dotnet/winforms/blob/main/docs/WinformsRuntimeConfiguration.md)

### Feature area

Windows Forms

---
[Associated WorkItem - 60094](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60094)

**Comment by jnm2** [comment]
> If user wanted to opt-in to this new behavior, they could do so by setting `System.Windows.Forms.AnchorLayoutV2` to `true` in runtimeconfig.json file as defined [here](https://github.com/dotnet/winforms/blob/main/docs/WinformsRuntimeConfiguration.md)

Link is broken. Current link is: <https://github.com/dotnet/winforms/blob/main/docs/runtime-configuration.md>

**Comment by gewarren** [comment]
> > If user wanted to opt-in to this new behavior, they could do so by setting `System.Windows.Forms.AnchorLayoutV2` to `true` in runtimeconfig.json file as defined [here](https://github.com/dotnet/winforms/blob/main/docs/WinformsRuntimeConfiguration.md)
> 
> Link is broken. Current link is: https://github.com/dotnet/winforms/blob/main/docs/runtime-configuration.md

Thanks, I updated the description.
