### ISSUE TITLE
Update publishing topic to explain what each of the generated files does

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#3215]
The [.NET Core publishing](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio) topic should have some content/pointers on what each of the files generated on publish is for:

* HelloWorld.deps.json
* HelloWorld.dll
* HelloWorld.pdb (optional for deployment)
* HelloWorld.runtimeconfig.json

**Comment by mairaw** [comment]
Seems related to #2645

**Comment by mairaw** [comment]
@rpetrusha are you also going to cover #2645 as part of this?

**Comment by rpetrusha** [comment]
@mairaw, no, I wasn't planning to; I was just going to add a list of the generated files and what they're for to this tutorial. runtimeconfig.json probably merits a standalone topic.
