### ISSUE TITLE
Would love an example of how to change the type parameters to avoid the conflict.

### ISSUE THREAD

**Issue by XanNava** [dotnet/docs#32167]
I am facing this problem, but not sure what changing the type parameter to solve the problem looks like. I know an interface can be inherited multiple times, but can see the problem of if both generic parameters are the same type. Something like

where T1 : !T2

which isn't a thing but not sure how else you would do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9e78697-2ace-29a0-34ea-feabf04b63e9
* Version Independent ID: e75b4db8-70a8-839d-df0d-ea097f25b0f9
* Content: [Compiler Error CS0695](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0695)
* Content Source: [docs/csharp/misc/cs0695.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0695.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @XanNava 

I'd need to see your code to provide a full answer. Can you post a small snippet here?
