### ISSUE TITLE
insufficient online documentation of dotnet watch

### ISSUE THREAD

**Issue by TeeTeeHaa** [dotnet/docs#32174]
**Issue description**

In my opinion the official online documentation of `dotnet watch` at https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch is insufficient. This opinion is based on several hours of reading and searching and asking to make something work. I would have expected that the official documentation simply contained the information I needed.

Coming from a TypeScript background where `tsc --watch` automatically builds (but not restarts) a project I wanted `dotnet watch` to automatically  build **but not automatically restart** my C# console project. The missing piece of information was to use `dotnet watch build` instead of just `dotnet watch`. I received that missing piece of information after asking on Reddit. Unfortunately it is not included in the official documentation.

My first suggestion for improvement of the documentation is to mention that `dotnet watch` actually takes a child command, for example `dotnet watch run` or `dotnet watch build` or `dotnet watch test`. Later in the documentation this is implied with _"If the child command isn't specified, the default is run for dotnet run."_ but I think that information has to be a lot more prominent, for example right in the Synopsis:
```
dotnet watch [build|run|test|...] // <==
  [--list] 
  [--no-hot-reload] [--non-interactive]
  [--project <PROJECT>]
  [-q|--quiet] [-v|--verbose]
  [--version]
  [--] <forwarded arguments> 

dotnet watch -?|-h|--help
```

My second suggestion is to list all such child commands which actually do work and make sense in combination with `dotnet watch` (I have not tried them all).

My third suggestion is not to say at the very top _"Restarts or hot reloads the specified application when changes in the source code are detected."_ because that is only correct when using `dotnet watch run` (or its shortcut `dotnet watch`). When using `dotnet watch build` or `dotnet watch test` it does something very different, not including any restarts or hot reloads.

My fourth suggestion, which probably is the easiest one, is to extend the Examples section with examples for `dotnet watch build` and all other possible child commands.

**Target framework**

- [X] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16f49f1b-261c-8cd0-a024-32c2535d0a0f
* Version Independent ID: 218d2a4d-2ff3-8e4d-1f06-bbb3710878fe
* Content: [dotnet watch command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch)
* Content Source: [docs/core/tools/dotnet-watch.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-watch.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 46151](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46151)

**Comment by tdykstra** [comment]
@DamianEdwards Can any commands be used as child commands for `dotnet watch` other than `build`, `watch`, or `test`?

**Comment by DamianEdwards** [comment]
You can run any command that is dispatched via the `dotnet` executable, e.g. built-in CLI commands, global tools. That is, if you can run `dotnet [thing-to-run]` you can do `dotnet watch [thing-to-run]`. There is special behavior for some known commands, but you can ask it to run anything and it will do so when it detects file changes in the targeted project.

**Comment by tdykstra** [comment]
@TeeTeeHaa Thanks for pointing that out. I'm updating the article.

**Comment by TeeTeeHaa** [comment]
@tdykstra Thank you for your efforts. I had a look at the changes and they definitely are an improvement.
