### ISSUE TITLE
CLI scenarios-based docs

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#322]
Though these should be "scenario-focused for the CLI" I think they span concerns. Maybe we should have a new TOC place for them @cartermp @mairaw?
- [ ] Scenario-focused documentation
  - [ ] Build a Shared Framework App
  - [ ] Build a Standalone App, including targeting non-local RIDs
  - [ ] Build a library
  - [ ] Add & localize resources
  - [ ] Sign your app
  - [ ] Using CI with CLI

**Comment by cartermp** [comment]
Would these be only as it pertains to the CLI, or would it truly be about the scenarios?  Because building a library is a scenario, but the way you build stuff in VS differs from hand-wiring it up with the CLI, for example.

**Comment by blackdwarf** [comment]
@cartermp good question. It would be focused on the CLI, but my point was that it should maybe exist outside of the CLI TOC portion since it is pretty general.

**Comment by cartermp** [comment]
Hmmm, yeah that is pretty tricky.  Well I think what you proposed makes sense, at least for now.  We can always re-jigger it if need be down the road.

**Comment by BillWagner** [comment]
Closing this, as it was addressed in PR #391
