### ISSUE TITLE
Document `excluded_symbol_names` support for CA1305

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#32213]
Looks like support for `excluded_symbol_names` was added in https://github.com/dotnet/roslyn-analyzers/pull/5374 but was never documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee726c26-f355-a0d8-9d7d-63d770e2a23c
* Version Independent ID: f8c1f8a7-0dcb-7e6d-0eaf-8acf31a65c42
* Content: [CA1305: Specify IFormatProvider (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1305.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1305.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 57955](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57955)

**Comment by gewarren** [comment]
@Youssef1313 According to https://github.com/dotnet/docs/pull/30169#issuecomment-1182837804, I need to add `excluded_type_names_with_derived_types` as well for CA1305. Is that correct?

**Comment by Youssef1313** [comment]
@gewarren I think yes. It seems that both options work together (ie, both are supported, or none of them is supported)

They are both checked in this code path.

https://github.com/dotnet/roslyn-analyzers/blob/3168c39e4289303d568a65c11c4c322c1e9cfd89/src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs#L251-L252
