### ISSUE TITLE
Clarify whitespace handling for multi-line Raw String Literals

### ISSUE THREAD

**Issue by techfan101** [dotnet/docs#32215]
In the section entitled "Raw String Literals", please consider clarifying the documentation of whitespace handling for strings that span multiple lines.  In that section, the following sentence does not fully convey the behavior:

> In multi-line raw string literals, any whitespace to the left of the closing quotes is removed.

Specifically, it is unclear that this whitespace is also removed from the lines **prior** to the single line containing the closing quotes.  For example, something like the following might be clearer...

> In multi-line raw string literals, any whitespace to the left of the closing quotes is removed **from all lines in the string**.

Also, clarification of the handling of whitespace following the opening quotes would be helpful. While it is somewhat covered in the comments in the code snippet, adding an additional bullet point to the article text might be more helpful. 

Finally, while it is apparent (from the comments) that line breaks following the opening quotes are removed, it is unclear if all trailing whitespace (spaces, tabs, etc.) is also removed. Assuming it is removed, it is similarly unclear if this "trimming" behavior extends to subsequent lines of that same string.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/?source=docs)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 34450](https://dev.azure.com/msft-skilling/Content/_workitems/edit/34450)

**Comment by BillWagner** [comment]
Hi @techfan101 

One obvious fix is to link to the [specification](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/raw-string-literal). 

However, I'd rather not replicate the spec here. For that reason, this page may (probably should) miss some details. Of the items you mention above, which do you think are common? Which do you think are maybe less needed?

Thanks for the discussion.

**Comment by techfan101** [comment]
@BillWagner, thank you for taking the time to consider this request. I had not seen the specification.

While the specification is indeed helpful, I think it may be overkill for casual consumers of this feature :)

I don't suggest significantly altering the article. I think the level of detail already present comes very close to providing enough detail. There are only two minor clarifications that would be helpful.

Regarding the removal of leading whitespace, adding a few words to the end of the existing bullet point should suffice.

Regarding the removal of trailing whitespace, I think a single additional bullet point would suffice. Something like the following, where new text is bolded, should suffice for both:

> * In multi-line raw string literals, any whitespace to the left of the closing quotes is removed **from all lines in the string**.
> 
> * **In multi-line raw string literals, trailing whitespace on the initial line containing the opening quotes is removed.  Trailing whitespace on subsequent lines is not altered.**
> 

Given the importance of whitespace handling with regard to multi-line string literals, I think this small amount of extra clarification is appropriate.

That said, please fact-check me. I did have a bit of difficulty interpreting the specification. Hopefully, my suggested additions accurately summarize what it specifies.

Thanks again for your time.

**Comment by BillWagner** [comment]
Thanks @techfan101 

That helps a lot. I'll address it this month.
