### ISSUE TITLE
--interractive does not work on Mac

### ISSUE THREAD

**Issue by omatrot** [dotnet/docs#32223]
I'm trying to following command on my Mac:

> sudo dotnet workload install ios android --interractive

But it fails with the following error:

> Workload ID --interractive is not recognized.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbfaa61-ebac-d118-6dd1-152a53f37a91
* Version Independent ID: 55bbba16-ae98-5abc-cd42-1b677105fd29
* Content: [dotnet workload install command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install)
* Content Source: [docs/core/tools/dotnet-workload-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-workload-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 32650](https://dev.azure.com/msft-skilling/Content/_workitems/edit/32650)

**Comment by tdykstra** [comment]
There is only one "r" in "--interactive"

**Comment by omatrot** [comment]
Me and spelling...
