### ISSUE TITLE
There are multiple typos in f# signatures chapter

### ISSUE THREAD

**Issue by jittrfunc** [dotnet/docs#3232]
There were a few typos in f# signatures chapter. E.g. the type alias while declaring member functions within Type2 was different within the same type. A few other minor typos were also present. I have created a pull request #3231 for fixing the same. Please review the changes and pull in if satisfactory.

**Comment by mairaw** [comment]
Thanks for noticing that and fixing as well @jittrfunc. Since the PR was merged, I'm closing this one.
