### ISSUE TITLE
Conditional post-conditions last example use of nameof() is misleading or broken

### ISSUE THREAD

**Issue by TomasMalecek** [dotnet/docs#32323]
The last example in the "Conditional post-conditions: NotNullWhen, MaybeNullWhen, and NotNullIfNotNull" section is either very misleading, or more likely broken.

```
[return: NotNullIfNotNull(nameof(url))]
string? GetTopLevelDomainFromFullUrl(string? url)
```

The issue is that in `nameof(url)` the `url` is not the name of the single parameter of the `GetTopLevelDomainFromFullUrl` method. It should be and it would be nice if we could use it like that, but it simply does not work. There must be something else in the context named `url`, or the example does not compile at all.

In real use, I am forced to provide a string without `nameof()`:

```
[return: NotNullIfNotNull("url")]
string? GetTopLevelDomainFromFullUrl(string? url)
```

I suggest changing the example like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [Attributes interpreted by the C# compiler: Nullable static analysis](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 33080](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33080)

**Comment by pkulikov** [comment]
@TomasMalecek I believe this example works in c# 11 or later only

**Comment by BillWagner** [comment]
Thanks for noting this @TomasMalecek 

As @pkulikov points out, this compiles correctly in C# 11.

We should add that note. You can see the details [here](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/extended-nameof-scope)

**Comment by TomasMalecek** [comment]
@pkulikov @BillWagner Thanks for pointing me toward this feature of C# 11! Had not managed to see what's new in version 11 yet, but I managed to read through the new features now.

I agree that the example is valid C# 11 and that some note should be added to highlight the requirement for C# 11+.

The new feature [already works in SharpLab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQAYACCgRgDoARASwEMBzPCAZw1ZhejAMIRCMAIJ52AGwCevVrwDcAWABQmgNoUA7CBoA5CBiM5ZsgJIAzE2YuyAFDIC2MCDac4osgJR+ALqaDFQA/DQA4jAYACoQAA4AMjAAbjCyzBCu7Kx4AGJQ2fmOAKq+TqERPv6aAN6aNE10ejQ16hoAvkA)! 🎉
