### ISSUE TITLE
Behavior changed since?

### ISSUE THREAD

**Issue by nickalbrecht** [dotnet/docs#32327]
Both the "Old Behavior" paragraph and the "New Behavior" paragraph list .NET 6.0

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa60e1c-9c9a-ce16-2e47-c41857fc8c48
* Version Independent ID: c3b792d7-50ab-ff45-09bf-37a7550f0e09
* Content: [Breaking change: System.Drawing.Common only supported on Windows - .NET](https://learn.microsoft.com/en-ca/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)
* Content Source: [docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The behavior changed in .NET 6. The "old behavior" section states "_Prior to_ .NET 6...". I'll close this issue, but if you still think there's an error, please reopen.

**Comment by nickalbrecht** [comment]
The reason I presumed it was in error, is because I was directed there by a link on the `System.Drawing.Common 7.0.0` nuget package, which specifically states a change `Since .NET 7`, with a link to https://aka.ms/systemdrawingnonwindows for more information. However that link redirected to this help document which doesn't mention .NET 7 at all. So I'm not sure if there's actually a change relevant to .NET 7 or not?

I don't believe I can re-open issues.

**Comment by gewarren** [comment]
@nickalbrecht What happened in .NET 7 is that they removed the `EnableUnixSupport` configuration switch. There is a note in a purple box at the bottom of the page stating that the switch is only available in .NET 6. I wonder if that is why the package links there?

**Comment by nickalbrecht** [comment]
Possibly. I always just assumed that when documentation says "Only available in version X", is because that's when the change was made, and being accurate at the time it was noted, is not available in any _previous_ version. I never take it as a literal "Only in version X, not in any previous version nor any _future_ version".

I had specifically tried a Ctrl-F on the page before creating the issue, when I read the package description, to try and find an explanation of the .NET 7 disclaimer, but if that's the only relevant line `"This switch is only available in .NET 6."`, That's no more information than what the package  stated. So I'm not sure what having a "Go here for more information" adds 😅

Maybe worth explicitly mentioning the change in .NET 7 instead of implying it
