### ISSUE TITLE
unclear resolution/example

### ISSUE THREAD

**Issue by luntrick** [dotnet/docs#32339]
[Enter feedback here]
This page does not appear to provide clear resolution via the example

Does one assume the comment in the comment is designed to show how to correct the error?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1982705-65b6-fc10-f51c-43989fd20dca
* Version Independent ID: 04dea072-a176-b403-8550-ffde758c2f6f
* Content: [Compiler Warning (level 4) CS1591](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591?f1url=%3FappId%3Droslyn%26k%3Dk(CS1591))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1591.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1591.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @luntrick 

I agree that we can do better here. I've added this to our backlog to address.

In the meantime, there are two possible fixes here:

1. Add the `///` comments on every public type and member.
2. Turn off the compiler option to generate the documentation file.

**Comment by Viniciusap** [comment]
Hi! This is still open?

**Comment by Viniciusap** [comment]
@BillWagner this could be closed I think.

**Comment by IEvangelist** [comment]
Closed via https://github.com/dotnet/docs/pull/33007
