### ISSUE TITLE
boolean short circuit and out together cause unexpected error

### ISSUE THREAD

**Issue by DoDoBooM** [dotnet/docs#32335]
[Enter feedback here]
```
private void Foo(int l, int r)
{
    bool isLOk = IsOk(l);
    bool isROk = IsOk(r);

    MyStruct lMS;
    bool isLValueFound = isLOk && TryGetValue(out lMS, l);

    MyStruct rMS;
    bool isRValueFound = isROk && TryGetValue(out rMS, r);
    if (isLValueFound && isRValueFound)
    {
        int sum = lMS.value+ rMS.value;
    }
}
```

line "int sum = lMS.value+ rMS.value;" will cause CS0170. Using int instead of MyStruct, I'll get CS0165.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d589e97f-4686-ec54-f82a-f5e1341aab1f
* Version Independent ID: 2736fabb-a4e1-4786-650d-01afa0450e5f
* Content: [Compiler Error CS0170](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0170)
* Content Source: [docs/csharp/misc/cs0170.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0170.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @DoDoBooM 

Can you add the declaration of `IsOK` and `MyStruct` to this example? I'd like to see more context to diagnose exactly what's going on here.

Thanks.
