### ISSUE TITLE
Orleans migration guide should include database scripts

### ISSUE THREAD

**Issue by aL3891** [dotnet/docs#32356]
Please make a note to also upgrade the database tables used by orleans from the "Migrations" folders in the github repo:
https://github.com/dotnet/orleans/tree/main/src/AdoNet/Orleans.Clustering.AdoNet/Migrations
https://github.com/dotnet/orleans/tree/main/src/AdoNet/Orleans.Persistence.AdoNet/Migrations
https://github.com/dotnet/orleans/tree/main/src/AdoNet/Orleans.Reminders.AdoNet/Migrations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aab851b-48df-ff93-da26-dfb9230c07bd
* Version Independent ID: cfd3e88c-ff32-1250-bd69-f82ca5571725
* Content: [What's new in Orleans](https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans)
* Content Source: [docs/orleans/whats-new-in-orleans.md](https://github.com/dotnet/docs/blob/main/docs/orleans/whats-new-in-orleans.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 39164](https://dev.azure.com/msft-skilling/Content/_workitems/edit/39164)

**Comment by IEvangelist** [comment]
Fixed in https://github.com/dotnet/docs/pull/32358
