### ISSUE TITLE
ASP.NET Update Assistant is using .NET 5 and screenshots

### ISSUE THREAD

**Issue by SychevIgor** [dotnet/docs#32366]
Screenshot come from .net 5 and requires an update
![image](https://user-images.githubusercontent.com/578954/200765335-6528dc37-32bb-401e-99bf-1a3e75d5c084.png)
this link https://learn.microsoft.com/en-us/dotnet/core/porting/media/upgrade-assistant-aspnetmvc/initial-run.png
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55d57d2a-269e-1efe-a437-77655d075c00
* Version Independent ID: 2b7dd581-95e2-3985-b5d3-0a8899dbc97c
* Content: [Upgrade ASP.NET MVC apps to .NET 6 - .NET Core](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-aspnetmvc)
* Content Source: [docs/core/porting/upgrade-assistant-aspnetmvc.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-aspnetmvc.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

---
[Associated WorkItem - 70352](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70352)

**Comment by adegeo** [comment]
Rick took this one over and moved it to the ASP.NET area
