### ISSUE TITLE
need .net 7 intellisense

### ISSUE THREAD

**Issue by mq00fc** [dotnet/docs#32362]
need .net 7  intellisense

**Comment by BillWagner** [comment]
Ping @gewarren 

Will this already be in the pipeline? When should we have the .NET 7 intellisense avaiable?

**Comment by gewarren** [comment]
It should be available. What exactly are you seeing/requesting @mq00fc?

**Comment by mq00fc** [comment]
@gewarren  it's https://dotnet.microsoft.com/zh-cn/download/intellisense
No .net7 intellisense

**Comment by gewarren** [comment]
@mq00fc Unfortunately we're no longer producing localized IntelliSense files. I have a pull request to update the guidance here: https://github.com/dotnet/docs/pull/32488. @mairaw Should we add a similar note to dotnet.microsoft.com?
