### ISSUE TITLE
Inheritance hierarchy for some types is wrong

### ISSUE THREAD

**Issue by svick** [dotnet/docs#324]
When I look at [the `WinHttpHandler` class](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.http.winhttphandler) in API reference, the Inheritance section shows `Object` as its direct base class. But this is wrong, `WinHttpHandler` inherits from `HttpMessageHandler`. The Syntax section shows this correctly.

For other types, (e.g. [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.http.httpclient)), the Inheritance section seems to be correct.

**Comment by mairaw** [comment]
@chenkennt can you take a look?

**Comment by chenkennt** [comment]
Please look at the latest page:
https://docs.microsoft.com/en-us/dotnet/core/api/system.net.http.winhttphandler
Already showing the correct base class

**Comment by svick** [comment]
@chenkennt It shows the correct base class in *Declaration*, but *Inheritance Hierarchy* is still wrong:

![](http://imgur.com/VfxuTMX.png)

**Comment by mairaw** [comment]
@svick this one seems fixed. Would you agree?

**Comment by svick** [comment]
@mairaw Yeah, seems to be fixed, closing.
