### ISSUE TITLE
Create new topics for ref features in C# 7.2

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3241]
Bundling these features together because the explanation and the discussion will encompass all of them.  The related features are:

- [ref readonly parameters and returns](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md)
- readonly struct
- [stackalloc span](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md)
- ref extensions
- ref ternary (conditional operator)
- ref struct

Note: this issue will be updated with the other specs as I find updated references to them. 

Other background on the feature is [here](https://github.com/VSadov/csharplang/blob/RefSpanDesignChoices/proposals/RefReadonlySpanDesignChoices.md)

@VSadov is one lead for these features.

**Comment by BillWagner** [comment]
Updated specs can be found here:

https://github.com/dotnet/csharplang/tree/master/proposals/csharp-7.2
https://github.com/VSadov/csharplang/blob/RefSpanDesignChoices/proposals/RefReadonlySpanDesignChoices.md

**Comment by jcouv** [comment]
We did have some last minute changes on ref readonly from LDM:
1.	Declaring ref readonly parameters uses the `in` keyword.
2.	Calling such a method is allowed with `M(x)` syntax, but also `M(in x)`. This caller syntax can affect overload resolution if there was a conflict.
