### ISSUE TITLE
New compiler option: Strong name provider

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3242]
More details coming. This has not been merged to master yet.

**Comment by BillWagner** [comment]
@jcouv In updates on this option?

**Comment by jcouv** [comment]
It didn't make it into 15.5 (C# 7.2). We're about to merge into branch for 15.6 ([PR](https://github.com/dotnet/roslyn/pull/23061)).
Tagging @agocke

**Comment by jcouv** [comment]
I see that @agocke just merged the feature into the branch for 15.6.
As far as the feature, my understanding is that it allows signing on Linux (previously was only supported on Windows). Andy can expand.

**Comment by agocke** [comment]
Yup, that's the gist of it. It relies on new portable signing code that allows full signing to be done cross-platform. I'm closing this bug for now. The feature should ship in 15.6.

**Comment by agocke** [comment]
I didn't realize this was a docs bug -- I can't close it and I supposed you probably want to wait until the feature is actually shipped. 😄

**Comment by BillWagner** [comment]
@agocke Let's leave it open for now. I'll change the milestone to reflect when it ships.

Thanks for keeping me updated.

**Comment by agocke** [comment]
Unfortunately there was no speclet since this was just a compiler feature. The feature is that /keyfile should now work when building on CoreCLR. There's a bug on Mono that's being fixed right now, but it should work there too. /keycontainer is and always will be unsupported on CoreCLR.

**Comment by BillWagner** [comment]
Thanks @agocke 

I'll make sure to add it to the list of "What's new in C# 7.3".  Our docs never mentioned that it *didn't* work before on CoreCLR, so there's nothing that needs to get fixed. I will update the /keycontainer switch to point out that CoreCLR is not supported. (It's not mentioned there either.
