### ISSUE TITLE
update numeric literals topic for leading underscores

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3246]
non-decimal integer literals can now have leading underscores.

For example, `0x_ff` is valid in C# 7.2

/cc @gafter

**Comment by garg000dhruv** [comment]
7.2 shenanigans yet again! I can take this too once I'm done with #3240.

**Comment by BillWagner** [comment]
@garg000dhruv That would be great. I'm going to leave it unassigned until we get the first one done, in case someone else wants to jump in.

**Comment by garg000dhruv** [comment]
@BillWagner I can take this one now if you'd like.

**Comment by BillWagner** [comment]
It's yours.
