### ISSUE TITLE
Bad suggestion in "To correct this error"section

### ISSUE THREAD

**Issue by nielsreijers** [dotnet/docs#32494]
What an odd suggestion. I want to define a critical section in my async code, and this page suggests to simply move some code out of that critical section? In this specific case it make be correct, but in general this would be a very bad idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0d8ea-e583-dca6-c6e3-5f878b6ce82b
* Version Independent ID: 442399a7-4a80-6859-921b-4293ab4191b5
* Content: [Compiler Error CS1996](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1996?f1url=%3FappId%3Droslyn%26k%3Dk(CS1996))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1996.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1996.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @nielsreijers 

I'd need more details about what you're trying to accomplish to provide specific guidance. I don't know how easy it would be to make the critical section synchronous.

However, there really isn't a different solution. C# doesn't support `await` in a critical section. It won't compile.

I'll close this as answered.
