### ISSUE TITLE
Replace this content with the version in csharplang

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#32505]
There is a lot of duplicated content in [this page](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history) and the [version maintained](https://github.com/dotnet/csharplang/blob/main/Language-Version-History.md) in the `dotnet/csharplang` repository.

Should that version replace this one? 

If so, I'd want to capture a couple important points on this page. One is the text and link to the relationship between C# language features and the existence and behavior of some BCL types.

We should also come to a conclusion about where to provide links. This page links to the information about the features on docs. The page in the csharplang repo does that for older versions, but links to the feature speclets for many of the newer features. 

I propose that the links be replaced with links to the docs pages when I've created the content for each new or upcoming feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 36396](https://dev.azure.com/msft-skilling/Content/_workitems/edit/36396)

**Comment by BillWagner** [comment]
Adding the discussion label.

/cc @jcouv @333fred for their thoughts.

**Comment by 333fred** [comment]
I had honestly thought that the docs page _was_ generated from the csharplang page...

**Comment by BillWagner** [comment]
Result of discussion with the team:

- The version history here, and in dotnet/csharplang serve different purposes for different audiences. Therefore, even though there is some duplication, they shouldn't be combined.
- However, this article does need some edits:  Namely, the order should be from most recent to oldest. In addition, check links and route readers to the best introduction to the feature.
