### ISSUE TITLE
now released and out of preview

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#32518]
in first para intro and "Install the System.CommandLine package" at https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial#install-the-systemcommandline-package there are comments/instructions related to preview status, for example per the NuGet 7.0.0-rc.2.22472.3 on 11th Oct 2022. However the final 7.0.0 version was released on 7th Nov 2022, so all the "preview" tags should now be removed. Yeay!

STOP PRESS
Apologies, I had installed Microsoft.Extensions.Configuration.CommandLine (v7.0.0 shipped 7/11/22) and not the System.CommandLine (2.0.0-beta4.22272.1 released 2nd June 2022)

Given the more recent Microsoft.Extensions.Configuration.CommandLine package [presumably where MS is devoting effort] should the System.CommandLine not now be marked as obsolete, and docs refer potential implementors to the MECC package ??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7705dc41-7297-0807-7e9c-2e6548c26b84
* Version Independent ID: fa160b1d-66ed-8c5d-37cd-b7e02443e9f1
* Content: [Tutorial: Get started with System.CommandLine](https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial)
* Content Source: [docs/standard/commandline/get-started-tutorial.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/get-started-tutorial.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Microsoft.Extensions.Configuration.CommandLine is a [command line configuration provider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.commandline?view=dotnet-plat-ext-7.0). It's not the same thing as System.CommandLine. System.CommandLine is still in preview and is still actively under development.

**Comment by tdykstra** [comment]
Closing as an answered question.
