### ISSUE TITLE
Update VS Code tutorial series for .NET 7

### ISSUE THREAD

**Issue by mbjr24** [dotnet/docs#32522]
On step 6, on the 7.0 tab, make sure the command reflects 7.0 not 6.0 -> dotnet new console --framework net7.0
![Screenshot 2022-11-10 183754](https://user-images.githubusercontent.com/2839110/201228481-c31685b0-42e2-4d39-aebb-44299adea2d7.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET console application using Visual Studio Code - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?WT.mc_id=dotnet-35129-website)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@mbjr24 thanks for reporting this oversight. There were several more places that needed the same update, and they're getting fixed in PR #32540
