### ISSUE TITLE
sk

### ISSUE THREAD

**Issue by sksp7641** [dotnet/docs#32539]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bee75153-63a2-1307-62d9-414bde708588
* Version Independent ID: 8a3376de-8adf-42b3-99c5-e9e4bf17ebca
* Content: [IDE0062: Make local function static - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0062)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0062.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0062.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sksp7641 I don't see anything actionable in this issue. If you feel that we've closed it in error, please provide further information.
