### ISSUE TITLE
Visual Basic Interfaces

### ISSUE THREAD

**Issue by newyearsnight** [dotnet/docs#32542]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 452fa284-1197-faa8-c9e4-377a98c05ede
* Version Independent ID: bc9e24e7-1ffe-bab3-f99b-c4244d01195c
* Content: [Interfaces - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/interfaces/)
* Content Source: [docs/visual-basic/programming-guide/language-features/interfaces/index.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/interfaces/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Hi @newyearsnight 

Did you have a question or issue on this content? If so, can you elaborate?
