### ISSUE TITLE
How to install .Net 7 on Ubuntu 22.10?

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#32541]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
You'll have to use the Microsoft feed. You can use the [instructions for 22.04](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204-microsoft-package-feed) until the article is updated. I'm waiting on the official feeds to start working before I publish an update.

If you use the Microsoft feed, and then want to swap back to the Ubuntu feed when it becomes available, you'll have to clean the system by removing .NET and deprecating the feed priority. This is described in [Linux package Mix-up](https://learn.microsoft.com/en-Us/dotnet/core/install/linux-package-mixup#whats-going-on)

**Comment by khteh** [comment]
Why is there such a delay on Ubuntu?

**Comment by hagaygo** [comment]
Even 6.0.11 is not available yet on ubuntu's feed. (packages's name is 6.0.110 but shown as 6.0.10)

dotnet --info output 

```
Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

```

**Comment by khteh** [comment]
https://github.com/dotnet/installer/issues/15141

**Comment by ripplejb** [comment]
**.Net 7** on **Ubuntu 22.10** is not working if you install it using any package manager. However, manual installation works just fine. It is super easy. You only need to [download, unzip, and set the path](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install).
