### ISSUE TITLE
Update Orleans tutorial docs to use 7.0.0 nuget packages

### ISSUE THREAD

**Issue by baradgur** [dotnet/docs#32543]
Existing [Create a minimal Orleans application](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/tutorial-1.md) article uses old nuget packages.

Can the article be updated or are there any other plans for it?

I already figured out what to do to make this tutorial on a 7.0.0 nuget version, so I can probably submit a pr in case there are no objections. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3e0034-a134-6eab-477f-5c5668eb68a0
* Version Independent ID: b61f5003-091e-e698-982b-124316d7eba3
* Content: [Minimal Orleans app sample project](https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/tutorial-1)
* Content Source: [docs/orleans/tutorials-and-samples/tutorial-1.md](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/tutorial-1.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 39162](https://dev.azure.com/msft-skilling/Content/_workitems/edit/39162)

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8203
