### ISSUE TITLE
Orleans TOC and overview page use wrong localization of "Grain"

### ISSUE THREAD

**Issue by gfoidl** [dotnet/docs#32544]
"Grain" is translated with "Getreide" which means "crop".
Either use "Korn" which is the direct equivalent for grain in this context or stick to "Grain" as it's Orleans specific.

![grafik](https://user-images.githubusercontent.com/5755834/201475937-96ceca76-8635-4851-96c2-b3c4b8f7d0ad.png)

![grafik](https://user-images.githubusercontent.com/5755834/201475954-d0d12e95-e856-46c6-a736-e0457db65f94.png)

**Comment by v-alje** [comment]
CEINTL work item 806126 filed to the LOC team on this issue.
