### ISSUE TITLE
Disposal of Services

### ISSUE THREAD

**Issue by TorreyGarland** [dotnet/docs#32557]
What is the correct pattern for ensuring that all disposable assets registered for dependency injection are automatically disposed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cec3f9b-ac99-9196-f294-4b14f03bab30
* Version Independent ID: 9f52a735-5d76-d278-39ba-38d2f55daa5c
* Content: [Dependency Injection](https://learn.microsoft.com/en-us/dotnet/architecture/maui/dependency-injection)
* Content Source: [docs/architecture/maui/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/architecture/maui/dependency-injection.md)
* Product: **dotnet-architecture**
* GitHub Login: @michaelstonis
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @TorreyGarland, thanks for sharing your query here. For more details, you can refer to the link: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose. I hope it helps you.

**Comment by IEvangelist** [comment]
Closed per @erjain

**Comment by TorreyGarland** [comment]
My apologies, I should have clarified.  

How should disposable injected services be properly disposed at an application level on a Maui application upon application shutdown?

Using WPF, you could instantiate an instance of IHost, start IHost OnStartUp, and this dispose of all services on the OnExit event.
