### ISSUE TITLE
`StackLinkedListNode` is not valid with C# 11

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/docs#32559]
The given example about `StackLinkedListNode` is not compilable:
```csharp
ref struct StackLinkedListNode<T>
{
    T _value;
    ref StackLinkedListNode<T> _next;

    public T Value => _value;

    public bool HasNext => !Unsafe.IsNullRef(ref _next);

    public ref StackLinkedListNode<T> Next 
    {
        get
        {
            if (!HasNext)
            {
                throw new InvalidOperationException("No next node");
            }

            return ref _next;
        }
    }

    public StackLinkedListNode(T value)
    {
        this = default;
        _value = value;
    }

    public StackLinkedListNode(T value, ref StackLinkedListNode<T> next)
    {
        _value = value;
        _next = ref next;
    }
}
```

Produces the following errors:
```
error CS9050: A ref field cannot refer to a ref struct.
error CS0523: Struct member 'StackLinkedListNode<T>._next' of type 'StackLinkedListNode<T>' causes a cycle in the struct layout
error CS0306: The type 'StackLinkedListNode<T>' may not be used as a type argument
```

Here is an [interactive sample on sharplab.io](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0AlArgOwC4EsBbAU1QGEB7QgB3wBtiAnAZSYDd8BjYgZwG5YsRsQBmiHrkaZOuRM1wBDTgGsAMvmzLiAE3USAchW3EAPABUAfLADesRPcRnEAfTYK6mYgJgPEwsfJKahpauvgGRqaWLtjEAB643nYOIADMjogAau6eiAC8Fi5uHl6CPinpAEYUFHSIABIKPPrxsgWIAIQAqtg8CiKkAJLNmHR06KIAFP4xrQCUSeX2aX6icooq6po6eriGxuaFLQmIyfa2S76IAObEuGdXF1fPiPhikx2NzfMPL4hPfxeuAAFowKAB3RCxSGDbDFfDaADy1CYCgIFGwAFE4txqOjsJMAESGKGtKGRQkLX4vAC+ZUBKQA7KsxM5YglvH86ZduQ8VoFNiEduE9pFJk5ip45g8Ac8QeF8ohjCIFKNEtT7K4csRFZLSjz6RV1kEtqFdvtiOLEHqADQs42C7ZhCIHaLs3DSy6yq5akq67Wcl5ssl5e3uwP2bk0oA==).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f07688d7-c782-94e9-2d9b-a629bac907fe
* Version Independent ID: ba181366-cdc8-4859-689b-dc2011b9f601
* Content: [Low level struct improvements - C# 11.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/low-level-struct-improvements)
* Content Source: [proposals/csharp-11.0/low-level-struct-improvements.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/low-level-struct-improvements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 59231](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59231)

**Comment by BillWagner** [comment]
adding @jaredpar 

I think that example may  be part of the possible enhancements in this area. He'd know for sure.

**Comment by linkdotnet** [comment]
@BillWagner 

Yes, it basically comes from the "[low-level struct improvements](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/low-level-struct-improvements.md)" done in C# 11 where the same example is given.

**Comment by BillWagner** [comment]
Hi @linkdotnet 

Sorry, I framed my  question for @jaredpar badly. Some of the low-level struct improvements (`scoped` and `ref` fields) were delivered in C# 11. Additional proposed features in that spec didn't make the C# 11 timeframe, and may be delivered later. I think that some of the features that are not yet implemented are required for that example. Jared will know for sure.

**Comment by jaredpar** [comment]
Yes that example isn't valid with the shipped feature. It was a valid item in the original design, but as we cracked down on `ref` fields to `ref struct` it became invalid. That needs to be deleted from the speclet.

**Comment by linkdotnet** [comment]
> Yes that example isn't valid with the shipped feature. It was a valid item in the original design, but as we cracked down on `ref` fields to `ref struct` it became invalid. That needs to be deleted from the speclet.

Thanks for clarifying. A bit off topic: Is the feature planned for C# 12?
