### ISSUE TITLE
These snippets are great, but...

### ISSUE THREAD

**Issue by rhires** [dotnet/docs#32566]
Can you create or point to a full code example of the typed client (in particular) and full code examples of each of the 4 items mentioned? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use IHttpClientFactory to implement resilient HTTP requests](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests?source=recommendations)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @rhires, thanks for posting your query. Please refer to the link for more details on several ways IHttpClientFactory can be used in an app: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#consumption-patterns. I hope it helps.

**Comment by rhires** [comment]
I have seen these, and unfortunately they are also not complete and downloadable examples.

**Comment by erjain** [comment]
You can check the `BasketService.cs` or any other service class in the `Services` folder for the implementation of the Typed Client. Here is the link: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Services/BasketService.cs. For the rest of other implementations, you can refer to the link shared in the previous post: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#consumption-patterns.

**Comment by IEvangelist** [comment]
Closed per @erjain
