### ISSUE TITLE
Obsolete "migrating to the latest .NET" article (7, not 6)

### ISSUE THREAD

**Issue by sdudnic** [dotnet/docs#32562]
The following article is obsolete and incorrect.   
The latest stable .NET version is 7 at the day, not 6.0

Where is, by the way, the upgrade to .NET 7 article?
I wonder an upgrade from .NET 5

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4be3d705-f99c-3b33-c171-13610d65bdcf
* Version Independent ID: 13febf13-c177-c52e-9225-200af1daffd9
* Content: [Example of migrating to the latest .NET](https://learn.microsoft.com/en-us/dotnet/architecture/modernize-desktop/example-migration)
* Content Source: [docs/architecture/modernize-desktop/example-migration.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modernize-desktop/example-migration.md)
* Product: **dotnet-architecture**
* GitHub Login: @OliaG
* Microsoft Alias: **oliag**

**Comment by erjain** [comment]
HI @sdudnic, thanks for posting here. We are working on .NET 7 updates, which will be released soon.

**Comment by erjain** [comment]
Adding @ardalis, can you take care of this?

**Comment by ardalis** [comment]
Yes, on it.

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
