### ISSUE TITLE
but you can also use the syntax (int, string) Dictionary

### ISSUE THREAD

**Issue by xp44mm** [dotnet/docs#32560]
[Enter feedback here]

search exists:
but you can also use the syntax (int, string) Dictionary.

error FS0062

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ac13728-5d30-b101-62fd-28952f656390
* Version Independent ID: f1d87578-3086-a51e-1e0a-52ad24ad0d09
* Content: [Generics - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/)
* Content Source: [docs/fsharp/language-reference/generics/index.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/generics/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
adding @KathleenDollard @dsyme I'm not sure what the request is for this issue. Do you know, or should I ask for more details?

**Comment by dsyme** [comment]
The syntax ` (int, string) Dictionary` is deprecated and gives an error now in F#
