### ISSUE TITLE
The following code examples illustrate each of these scenarios.

### ISSUE THREAD

**Issue by xp44mm** [dotnet/docs#32574]
[Enter feedback here]

> The following code examples illustrate each of these scenarios.

The previous sentence should not be an item, it should be a normal paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85b50526-a200-3774-0f70-d1079d783d9c
* Version Independent ID: e6f2ac27-6633-b9f9-6739-f48aef5595ad
* Content: [Automatic Generalization - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/automatic-generalization)
* Content Source: [docs/fsharp/language-reference/generics/automatic-generalization.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/generics/automatic-generalization.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks @xp44mm 

I've opened a PR to fix this issue.  In the future, when you spot this small issues, you can click the edit button (it looks like a pencil) to edit the source and submit a PR for us. It may save time over describing the issue.
