### ISSUE TITLE
Explicit implementation of file-local interface

### ISSUE THREAD

**Issue by dev-in-disguise** [dotnet/docs#32581]
Is the following really correct?

>The type can't [explicitly implement](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) a file-local interface.

As far as I played around with C# 11 I can explicitly implement file-local interfaces and also use the explicit implementations within the file scope. The only thing which should not be possible is of course using the explicit implementations outside of the file. 

So wouldn't a rephrasing to something like this make sense?

>The type can also [explicitly implement](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) a file-local interface but explicit implementations can only be used within the file scope. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06889a3e-7f9d-1eae-2ab2-299601847410
* Version Independent ID: 16072d3f-4bbd-886b-3426-c16c3f51efbb
* Content: [file keyword - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/file)
* Content Source: [docs/csharp/language-reference/keywords/file.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for that observation @dev-in-disguise 

You are correct. I've added this to our backlog, and added the "help wanted" label if you want to submit the PR with your suggestion above.

**Comment by dev-in-disguise** [comment]
Thank you very much @BillWagner! I opened the PR right now and am looking forward to your feedback!
