### ISSUE TITLE
[orleans] Update Service Fabric hosting guidance

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32589]
**Issue description**

We need to update the guidance for hosting Orleans applications in Service Fabric. The current guidance [here](https://learn.microsoft.com/en-us/dotnet/orleans/deployment/service-fabric#example-configure-service-fabric-hosting) relies on a now-deprecated package. We now recommend that developers integrate with Service Fabric's `ICommunicationListener` interface using the .NET Generic Host like in this example: https://gist.github.com/ReubenBond/83a08cfdc77d6232f97ec531e377fdc4

**Target framework**

- [x] .NET 7.0

---
[Associated WorkItem - 44870](https://dev.azure.com/msft-skilling/Content/_workitems/edit/44870)

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8203
