### ISSUE TITLE
nameof expression with a method parameter inside an attribute works with C# versions before 11

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#32599]
The page says

> Beginning with C# 11, you can use a nameof expression with a method parameter inside an [attribute](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/) on a method or its parameter.

This is not 100% correct. A nameof expression with a method parameter inside an attribute even works with C# versions before 11 as long as you use a compiler that knows C# 11.

Reference: https://github.com/dotnet/roslyn/issues/65379#issuecomment-1314033808

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4b82de3-3121-209c-6dc4-6267f726dcfe
* Version Independent ID: 7c19d7e6-f241-2f7e-9dad-737df8328663
* Content: [nameof expression - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(nameof_CSharpKeyword)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/operators/nameof.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/nameof.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This feels like quite an edge case.

@jcouv @333fred  What do you think?

**Comment by cremor** [comment]
Yes, it is an edge case. It's the only feature that I know about that was later added to older C# versions. That's why I think it is important that this is documented.
Otherwise questions like the one in dotnet/roslyn#65379 arise where someone might think that the compiler is doing something that it shouldn't when the lang version of the project is below 11.

**Comment by jcouv** [comment]
That's correct (no LangVer check on this feature). But I don't think that affects the spec. 
LangVer checks are best-effort on the part of the compiler (we try to limit usage of feature to the compilation's LangVer, but that's not guaranteed).

**Comment by 333fred** [comment]
Yeah, I don't think this needs to be documented specifically. The feature _is_ tied to C# 11: an older compiler won't compile it, so you will get inconsistent errors if you attempt to use it and don't have everyone on a new SDK/version of VS. But Language Version is a best-effort-only analysis. As another example, `CallerArgumentExpressionAttribute` is in the same boat.

**Comment by cremor** [comment]
> The feature _is_ tied to C# 11: an older compiler won't compile it, so you will get inconsistent errors if you attempt to use it and don't have everyone on a new SDK/version of VS

Yeah, and I think that's a bit dangerous. Assuming a project targets a C# version before 11, devs who use the current version of VS might write code that works fine for them, but won't compile for other devs or on the build machine, right?

> As another example, `CallerArgumentExpressionAttribute` is in the same boat.

I think that's not completely comparable. That this attribute generates code _is_ a compiler feature (and not a language/syntax feature) in my opinion.
Although that might be even worse because then code will compile with older compilers but will have different code at runtime? :anguished:

**Comment by 333fred** [comment]
> That this attribute generates code is a compiler feature (and not a language/syntax feature) in my opinion.

No, it's a language feature. It's specified by the C# language as doing a specific thing, like all the caller info attributes.

> Yeah, and I think that's a bit dangerous.

Certainly. However, as we said, LangVersion checks are _best effort_. We cannot guarantee that they're perfect. We get the big cases, and the cases that don't require a significant amount of implementation work to check, but sometimes it would take significant amounts of implementation work to check. This is one of those cases.

**Comment by BillWagner** [comment]
I'm going to close this without action.

The behavior @cremor does reflect the current implementation. However, using C# 11 features with any BCL before .NET 7 isn't supported. There's no guarantee that the current behavior won't change. You shouldn't rely on it. 

Yes it's a bit dangerous. But, it would be more dangerous to lead developers to believe that the behavior is supported.
