### ISSUE TITLE
"Don't pass a nullable value type as an `in` argument."

### ISSUE THREAD

**Issue by carlreinke** [dotnet/docs#32594]
> Don't pass a nullable value type as an `in` argument. The Nullable<T> type isn't declared as a read-only struct.  That means the compiler must generate defensive copies for any nullable value type argument passed to a method using the `in` modifier on the parameter declaration.

I think this guidance is a bit too strong.  Roslyn (v3.2 and later) does not make defensive copies when [accessing some members of `Nullable<T>`](https://github.com/dotnet/roslyn/blob/v4.2.0/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L1731-L1733) even when targeting .NET Framework (where none of its members are `readonly`).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://learn.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#feedback)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/main/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54744](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54744)

**Comment by BillWagner** [comment]
That's a good observation @carlreinke 

This is an area that will get an update over the next few months. I'll address it then.
