### ISSUE TITLE
Rebuilding cache failed

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [dotnet/docs#32602]
Original message in French:
Erreur lors de la reconstruction du cache :
[packages-microsoft-com-prod|https://packages.microsoft.com/opensuse/15/prod/]
Aucune métadonnée valide trouvée à l'URL spécifiée
Historique :
 - File /var/tmp/TmpFile.Tb9MW0 doesn't contain public key data

Translation :
Rebuilding cache failed :
[packages-microsoft-com-prod|https://packages.microsoft.com/opensuse/15/prod/]
No valid metadata found at the specified URL
History :
 - File /var/tmp/TmpFile.Tb9MW0 doesn't contain public key data

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016558a3-e021-04ce-e375-15b23f589ed9
* Version Independent ID: 89b6eb1c-2202-70ee-364d-fc2ede379e74
* Content: [Install .NET on openSUSE - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-opensuse)
* Content Source: [docs/core/install/linux-opensuse.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-opensuse.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@ChrisBertrandIndus I'm not sure what you were trying to do, or at what step it failed, but I can navigate to https://packages.microsoft.com/opensuse/15/prod and see a directory listing. Perhaps the server was down? Can you provide more information?
