### ISSUE TITLE
Questions about the "using declarations" proposal

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#32629]
I’m writing the formal specification of using declarations for the Ecma C# Standard, and have some observations and questions.

### Example Won’t Compile

When I compile the first example (involving `class Resource`), I get the following error:

> CS1674: `Resource`: type used in a using statement must be implicitly convertible to 'System.IDisposable'

The same happens when I change `class` to `struct`. However, `ref struct` works (as expected)! 

I’m thinking that `class` and `struct` should work, no? If not, the use of “type” in the description of the context of a disposable pattern is misleading, as it suggests `class` and `struct`, and the example is wrong.

### Extension Methods

> This will allow developers to leverage `using` in a number of new scenarios:
> - …
> - Extension methods will allow developers to augment types in other assemblies to participate in `using` statements.

I understand that to mean that if `Resource` does *not* have a `Dispose` method, I can provide one by defining an extension method of that name with the correct signature. Is that the intent? In any event, I can’t get that to work. An example showing the intent here would be very useful.

### Two Choices Exist

> In the situation where a type can be implicitly converted to `IDisposable` and also fits the disposable pattern, then `IDisposable` will be preferred.

Can you give an example of how a situation can allow both ways, so that one is picked over the other?

### Async using declaration

The [proposal for this (separate) feature](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-using.md) is just a placeholder; there is *no* MS spec for `await using`!

It seems to me that this current proposal would be a good place to put that spec as well. As I see it, that not only involves spec’ing `await using`, it also requires the `IAsyncDisposable` interface and `DisposeAsync` method to be described in the context of `using` as well as in other places in which `IDisposable` and `Dispose` are currently covered. Who might I speak with re nailing down this topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc900853-b666-5815-9d69-e408af3e3900
* Version Independent ID: 77f3af83-d0ca-7d48-d06d-0f28f5f05a49
* Content: [Pattern based using and using declarations - C# 8.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using)
* Content Source: [proposals/csharp-8.0/using.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/using.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 43585](https://dev.azure.com/msft-skilling/Content/_workitems/edit/43585)

**Comment by gfoidl** [comment]
Aside from the points of @RexJaeschke maybe not the "draft proposals" should be in the docs, rather a "final document" about the language spec based on the status how it's actually implemented.
Or put more emphasis in that section that these are design documents that may not reflect the actual implemention. But what's the purpose of these then? So the final document would be better (though more work to maintain).

There are some issued opened recently, that wonder why code shown in proposals doesn't compile.

**Comment by BillWagner** [comment]
Adding @jcouv and @333fred to check my answers.

> pattern-based using

In the final implementation, the pattern-based-using *only* supports `ref struct` types. Other types (`struct`, `class`, `interface`, including `record` types) must implement `IDisposable`.

> Extension Methods

I don't think extension methods are considered, even for the pattern-based using for `ref struct` types. @jcouv to confirm.

> Two Choices Exist

This condition can't happen anymore. `ref struct` types can't implement interfaces. Other types can't use the pattern based using.

**Comment by gfoidl** [comment]
@BillWagner thanks for the statement! 
I absolutely understand this.

**Comment by 333fred** [comment]
@BillWagner is correct on all the points there. As to async using, it was primarily @chsienki doing the implementation, though it did cross over with some of @jcouv's work.

**Comment by RexJaeschke** [comment]
Thank you @BillWagner and @333fred. As there is no proposal for the async using feature, I've conducted some experiments (which all work for classes and non-ref structs). However, they do not work with ref structs, so I am looping in @chsienki as well.

Consider the following:

```csharp
ref struct ResourceAsyncRefStruct // ref struct not permitted to implement any interfaces
{
    public ValueTask DisposeAsync()
    {
        Console.WriteLine("ResourceAsyncRefStruct.DisposeAsync()");
        return new ValueTask();
    }
    public void Dispose()
    {
        Console.WriteLine("ResourceAsyncRefStruct.Dispose()");
    }
}
```

This type is intended to be a resource type that can be used both synchronously and asynchronously.

Here's how I'm trying to use it:

```csharp
    public static async ValueTask DisposeAsyncRefStruct()
    {
        {
/*X*/    await using ResourceAsyncRefStruct r41 = new ResourceAsyncRefStruct();
            {
                // statements
            }

            // make a sync call to Dispose, instead of an async call to DisposeAsync

/*Y*/    using ResourceAsyncRefStruct r25 = new ResourceAsyncRefStruct();
            {
                // statements
            }
        }
    }
```

In both the asynchronous case `X` and the synchronous case `Y`, I get CS4012: Parameters or locals of type ‘ResourceAsyncRefStruct’ cannot be declared in async methods or async lambda expressions.

Of course, if I remove the `async` method modifier, I can't use `await`.

It seems to me that while I can use a ref struct in a non-await using, I can't use one in an await using. Is that correct, or am I missing something?

**Comment by 333fred** [comment]
> It seems to me that while I can use a ref struct in a non-await using, I can't use one in an await using.

Correct. Ref structs cannot be moved to the heap in any way (including boxing or being a field of a type that can be boxed or on the heap), and the async lowering would move the local to a field of a display class.

**Comment by RexJaeschke** [comment]
Thanks @BillWagner. All my Q's have been answered, and I've completed my spec of both using declarations and async using (see [PR #672](https://github.com/dotnet/csharpstandard/pull/672).)
