### ISSUE TITLE
Consider more info on dates and related products

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#32625]
It would be awesome if this had release dates and maybe the corresponding version of .NET and Visual Studio. I had to go to [wikipedia.org for that info](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#Versions) and that page is not fully up to date (the other .NET 6 versions are missing as well as that C# 11 is released.

Also, just saying, this is an awesome article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 43584](https://dev.azure.com/msft-skilling/Content/_workitems/edit/43584)

**Comment by BillWagner** [comment]
I'm planning updates to this article next month. I'll handle these at the same time.
