### ISSUE TITLE
Explanation of use of var and variable names is generally a bad practice.

### ISSUE THREAD

**Issue by DanVioletSagmiller** [dotnet/docs#32633]
Your section on "Implicitly typed local variables" seems like a bad practice to recommend. You specifically call it out as **only the right side** of the assignment needs to be obvious. Then use variable names like var1 and var2. I cannot stress enough how terrible it would be to find lines of code in a function that says something like 

`SetupUser(var1, var2);`
// instead of -- 
`SetupUser(name, age);`

While calling out that right side is important, well named variables seem far more so. 

I.e. var name = "Bob Denver"; var age = 27; is very clear in its later use for what type it is and what it's purpose is. 

Regarding the use of "inputInt" in the following case, I appears to resemble Hungarian Notation, literally calling out the type. I would completely agree about that being a bad practice. It establishes a practice of writing code where your variable names don't "need" to make as much sense. However, I thought this practice died out over 20 years ago. Is this something you see commonly in the field that it needs specific call out?

BUT calling out this: "_Don't rely on the variable name to specify the type of the variable_." seems off.  I feel the name should make clear the nature of what is being held (assuming domain knowledge of the product.) If you can't tell the nature of what the variable holds by its name, why bother naming it at all? Even during my time at multiple teams in Microsoft, this was a common practice, and brought up in code reviews. I think just calling out not to use Hungarian notation or similar practices would be better than the example and text used to explain this part. Or better yet, just call out the variable names should clearly express the nature of the data it holds. I.e. var1 would be a terrible name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 123093](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123093)

**Comment by DanVioletSagmiller** [comment]
This also relates to the use of var in 
`var text = "abcdef";
foreach(var c in text)`

Again, if the nature of how the data is being used is not clearly expressed by the name, why name it? In any form of visual studio, you can literally just mouse over a variable to see what type VS or VSC thinks it is. But naming is far more important. Pulling c from text as a collection is obviously a character. Its use is usually where more of the complication comes from, than the initial use of var.

**Comment by BillWagner** [comment]
Those are good points @DanVioletSagmiller 

I've added them to address when we next update this article.
