### ISSUE TITLE
what is "Example1" supposed to mean?

### ISSUE THREAD

**Issue by benkoshy** [dotnet/docs#32630]
What is Example1 supposed to mean? It wasn't very clear to me: 

Perhaps the sample should be be small, and self contained, with clarifying details added?

![example 1](https://user-images.githubusercontent.com/15097447/202316299-a9600bc9-a02b-4d3e-a7be-e30f3bafdb68.png)

See it under the "Attributes" section:

> Beginning with C# 10, you can add attributes to a lambda expression and its parameters. The following example shows how to add attributes to a lambda expression:

rgds
Ben

(side note: Bill i am envious of your display photo. one day I hope to make it to the otherside of the world and stand on the very same bridge.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @benkoshy 

I'll get this one updated.

**Comment by BillWagner** [comment]
This was addressed in a prior PR.
