### ISSUE TITLE
[Orleans] Update Server Configuration guide

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32648]
**Issue description**

Doc: https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/server-configuration.md

Updates for Orleans 7.0

* `ISiloBuilder` is used via `IHostBuilder.UseOrleans(Action<ISiloBuilder>)` rather than `SiloHostBuilder` (replace `<xref:Orleans.Hosting.SiloHostBuilder>` in current doc)
* In `UseAzureStorageClustering`, we now use `options.ConfigureTableServiceClient(connectionString)` instead of `options.ConnectionString = connectionString`
* ApplicationParts configuration is no longer necessary: we should delete the entire section
* `ConfigureEndpoints` is no longer necessary in the simple case, since we set defaults (11111, 30000)
* `Configure<ClusterOption>` is no longer necessary in the simple case, since we set defaults (`ClusterId = ServiceId = "default"`)

cc @IEvangelist 

---
[Associated WorkItem - 39158](https://dev.azure.com/msft-skilling/Content/_workitems/edit/39158)

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8203
