### ISSUE TITLE
Error "The parameter is incorrect" when decrypt file 

### ISSUE THREAD

**Issue by TiagoPintoo** [dotnet/docs#32645]
I have included in my VB.NET project the System.Security.Cryptography to decript files, in my computer the functionality works OK but when I send the project to someone they are presented with the ERROR "The parameter is incorrect" and it shows the following Exception: 'System.Security.Cryptography.CryptographicException' in mscordlib.net
When the application try to decript the file in other computers it corrupted the file and it's unreadeble.
I don't know this is a error of my  code or if this is a bug.
So I'm looking for some guidance to solve this problem

![image](https://user-images.githubusercontent.com/118431775/202485870-e3005bbb-7e61-4d4f-a7c6-b088487aa6fe.png)

![image](https://user-images.githubusercontent.com/118431775/202485982-83c5eb57-f8d5-4dcb-9096-d0b5d41220e4.png)

![image](https://user-images.githubusercontent.com/118431775/202485034-a746c1b0-5e79-408c-a664-c23c5c00e427.png)

` Private Sub DecryptFile(ByVal inFile As String)

        ' Create instance of Aes for symmetric decryption of the data.
        Dim aes As Aes = Aes.Create()

        ' Create byte arrays to get the length of the encrypted key and IV.
        ' These values were stored as 4 bytes each at the beginning of the encrypted package.
        Dim LenK As Byte() = New Byte(4 - 1) {}
        Dim LenIV As Byte() = New Byte(4 - 1) {}

        ' Construct the file name for the decrypted file.
        Dim outFile As String = DecrFolder & (inFile.Substring(0, inFile.LastIndexOf(".")) & ".xlsx")
        ' Use FileStream objects to read the encrypted
        ' file (inFs) and save the decrypted file (outFs).
        Using inFs As New FileStream((EncrFile & inFile), FileMode.Open)

            inFs.Seek(0, SeekOrigin.Begin)
            inFs.Read(LenK, 0, 3)
            inFs.Seek(4, SeekOrigin.Begin)
            inFs.Read(LenIV, 0, 3)

            Dim lengthK As Integer = BitConverter.ToInt32(LenK, 0)
            Dim lengthIV As Integer = BitConverter.ToInt32(LenIV, 0)
            Dim startC As Integer = (lengthK + lengthIV + 8)
            Dim lenC As Integer = (CType(inFs.Length, Integer) - startC)
            Dim KeyEncrypted As Byte() = New Byte(lengthK - 1) {}
            Dim IV As Byte() = New Byte(lengthIV - 1) {}

            ' Extract the key and IV starting from index 8
            ' after the length values.
            inFs.Seek(8, SeekOrigin.Begin)
            inFs.Read(KeyEncrypted, 0, lengthK)
            inFs.Seek(8 + lengthK, SeekOrigin.Begin)
            inFs.Read(IV, 0, lengthIV)
            Directory.CreateDirectory(DecrFolder)

            ' User RSACryptoServiceProvider to decrypt the AES key
            Dim KeyDecrypted As Byte() = _rsa.Decrypt(KeyEncrypted, False)

            ' Decrypt the key.
            Dim transform As ICryptoTransform = aes.CreateDecryptor(KeyDecrypted, IV)

            ' Decrypt the cipher text from from the FileSteam of the encrypted
            ' file (inFs) into the FileStream for the decrypted file (outFs).
            Using outFs As New FileStream(outFile, FileMode.Create)
                Dim count As Integer = 0
                Dim offset As Integer = 0

                ' blockSizeBytes can be any arbitrary size.
                Dim blockSizeBytes As Integer = (aes.BlockSize / 8)
                Dim data As Byte() = New Byte(blockSizeBytes - 1) {}

                ' By decrypting a chunk a time, you can save memory and accommodate large files.
                ' Start at the beginning of the cipher text.
                inFs.Seek(startC, SeekOrigin.Begin)
                Using outStreamDecrypted As New CryptoStream(outFs, transform, CryptoStreamMode.Write)
                    Do
                        count = inFs.Read(data, 0, blockSizeBytes)
                        offset += count
                        outStreamDecrypted.Write(data, 0, count)
                    Loop Until (count = 0)

                    outStreamDecrypted.FlushFinalBlock()
                End Using
            End Using
        End Using
    End Sub`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Create a Cryptographic Application](https://learn.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 58984](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58984)

**Comment by gewarren** [comment]
@TiagoPintoo Which article is this in relation to?

**Comment by TiagoPintoo** [comment]
> @TiagoPintoo Which article is this in relation to?

The article is this one.
https://github.com/dotnet/docs/blob/main/docs/standard/security/walkthrough-creating-a-cryptographic-application.md

**Comment by IEvangelist** [comment]
I'm not able to recreate this issue. The exception that you shared is unrelated to anything in this article. The exception that is depicted here is the `OleDbException`. Are you able to provide any more details or the exact code that you're having problems with? I'm going to close this for now, but we can open it if you're able to provide the necessary details.
