### ISSUE TITLE
Motivation section

### ISSUE THREAD

**Issue by ekaraman89** [dotnet/docs#32642]
Hello friends
There is a error in code section of the motivation section.
Person class is root class and student class is inherit class. So student class has not a constructor. Must be constructor for student.

```cs
class Person
{
    public string FirstName { get; }
    public string MiddleName { get; }
    public string LastName { get; }

    public Person(string firstName, string lastName, string? middleName = null)
    {
        FirstName = firstName;
        LastName = lastName;
        MiddleName = middleName ?? string.Empty;
    }
}

class Student : Person
{
    public int ID { get; }
    public Student (int id, string firstName, string lastName, string? middleName = null)
        : base(firstName, lastName, middleName)
    {
        ID = id;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 491550b6-23f8-a48a-c6e5-f177151030ff
* Version Independent ID: 4037b376-e4f6-73cc-3dd1-abea0fc7db5b
* Content: [Required members - C# 11.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members)
* Content Source: [proposals/csharp-11.0/required-members.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/required-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this and providing the PR to fix it.

I'll close as fixed in dotnet/csharplang#6725
