### ISSUE TITLE
Most probable description missing

### ISSUE THREAD

**Issue by Thorium** [dotnet/docs#32646]
The document should state:

Check your NuGet version!
The command line NuGet.exe may not have updated with Visual Studio and .NET update!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d963a62-6144-7ac0-3c60-7ca63dd8da25
* Version Independent ID: d4a572b0-3a21-8d0d-5709-75e4708d7f6c
* Content: [NETSDK1005 and NETSDK1047: Asset file is missing target - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005)
* Content Source: [docs/core/tools/sdk-errors/netsdk1005.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1005.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @sfoslund
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 57897](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57897)

**Comment by tdykstra** [comment]
The first suggested action starts with:

>Make sure that you're using MSBuild version 16.8 or later and NuGet version 5.8 or later,

**Comment by tdykstra** [comment]
Closing as answered, feel free to reopen if more discussion is needed.
