### ISSUE TITLE
The dotnet pack command does apsolutely nothing

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#32644]
I execute the following set of commands to see what I am doing wrong.
```
Microsoft Windows [Version 10.0.22621.819]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj" -v diag

C:\Windows\System32>dotnet Pack -c RELEASE -o D:\NUGET --runtime win10-x64 "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj" -v diag

C:\Windows\System32>dotnet Pack -c RELEASE -o D:\NUGET "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj" -v diag

C:\Windows\System32>dotnet Pack "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj" -v diag

C:\Windows\System32>dotnet Pack "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj"

C:\Windows\System32>
```

I would assume that it generates the NuGet Package belonging to the project; it doesn't. It generates no messages and compiles no data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Hi @PeterPann23 You need to be in the same folder as your project. It looks like you opened an Administrator (not required) command prompt which puts you in the `C:\Windows\System32` folder. You need to navigate to the folder where your project is located.

**Comment by PeterPann23** [comment]
Hi Adegeo,

Thanks for the fast response, it doesn't matter where I execute it, it never works 
```

Microsoft Windows [Version 10.0.22621.819]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>packrelease.cmd

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj" -v diag

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDS.DataClient\Walter.Net.IDS.DataClient.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDPS.NamedPipes\Walter.Net.IDPS.NamedPipes.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDPS.Core\Walter.Net.IDPS.Core.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.IO.Windows\Walter.IO.Windows.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.IDS.Services\Walter.Net.IDS.Services.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "IDPS.UI.Shared\IDPS.UI.Shared.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack "IDPS.Wpf\IDPS.Wpf.csproj" -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "IDPS.Shared\IDPS.Shared.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>dotnet Pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "D:\Source\IDPS\NuGet-IDPS\IDPS.Shared\IDPS.Shared.csproj"

C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>rem dotnet pack -c RELEASE -o D:\NUGET --nologo -s --runtime win10-x64 "Walter.Net.FireWall.Windows\Walter.Net.FireWall.Windows.csproj"
C:\Users\User\source\Workspaces\IDPS_NuGet\NuGet-IDPS>
```
When I run the MS Build it does just fine
![image](https://user-images.githubusercontent.com/44400822/202624704-76c7c7ff-18c5-4d3f-8b5c-d0ad78961435.png)

dotnet msbuild -t:pack -property:Configuration=Release "IDPS.Shared\IDPS.Shared.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "IDPS.UI.Shared\IDPS.UI.Shared.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.Net.IDPS.BOM\Walter.Net.IDPS.BOM.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.Net.IDS.DataClient\Walter.Net.IDS.DataClient.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.Net.IDPS.NamedPipes\Walter.Net.IDPS.NamedPipes.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.Net.IDPS.Core\Walter.Net.IDPS.Core.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.IO.Windows\Walter.IO.Windows.csproj"
dotnet msbuild -t:pack -property:Configuration=Release "Walter.Net.IDS.Services\Walter.Net.IDS.Services.csproj"

only thing I am missing is that I can't target the runtime this way

**Comment by PeterPann23** [comment]
@adegeo 
I noticed the comment on the casing, that seems to fix it.... thanks
