### ISSUE TITLE
Chuck Norris database 404s

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#32655]
The Chuck Norris Database link 404s. Do we need to use a different API for this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46af0b96-2d12-9cac-2f8f-15eb49d0292d
* Version Independent ID: 33db41be-42f9-bb94-65fe-0cf7d1c64f12
* Content: [Use the IHttpClientFactory - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
* Content Source: [docs/core/extensions/httpclient-factory.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/httpclient-factory.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 39222](https://dev.azure.com/msft-skilling/Content/_workitems/edit/39222)

**Comment by IEvangelist** [comment]
> You don't find Chuck Norris. Chuck Norris finds you.
