### ISSUE TITLE
Page needs to be updated with .NET 7 install instructions for Red Hat

### ISSUE THREAD

**Issue by rkeithhill-keysight** [dotnet/docs#32663]
This page currently covers installing .NET 6 and earlier on Red Hat. It needs to be updated with instructions for installing .NET 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 197d466f-8967-78b1-b1fc-2c09367b0bec
* Version Independent ID: 2953e34e-d5e1-8d33-92a0-73a1d37cfb8e
* Content: [Install .NET on RHEL and CentOS Stream - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-rhel)
* Content Source: [docs/core/install/linux-rhel.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-rhel.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for filing this issue. This is being addressed in #32596
