### ISSUE TITLE
In fig 7.7 the domain layer references repository interfaces

### ISSUE THREAD

**Issue by kosletr** [dotnet/docs#32677]
[Enter feedback here]
In fig 7.7 the domain layer references repository interfaces/contracts. I thought that these should be referenced in application layer and using DI access the concrete implementations. Since the domain layer has no dependencies as it is a POCO, I would expect to be unaware of the repositories. I am bit confused. 

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 5a30bea5-326b-ea72-59ae-dfef1e190e4a
* Content: [Designing a DDD-oriented microservice](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @kosletr, thanks for posting here. This layer design should be independent for each microservice. It implements repository contracts/interfaces which will be used in DI. The Application layer depends on Domain and Infrastructure, and Infrastructure depends on Domain, but Domain doesn't depend on any layer.

You can also refer to the following link for more information:
https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice#the-domain-model-layer

**Comment by IEvangelist** [comment]
Closed per @erjain
