### ISSUE TITLE
"Options pattern - .NET" is not clear about when updated options are read

### ISSUE THREAD

**Issue by SEnglishSMP** [dotnet/docs#32672]
[Enter feedback here]

In section "Bind hierarchical configuration", the example code for `ConfigurationBinder.Bind` is immediately followed by the comment, "In the preceding code, changes to the JSON configuration file after the app has started are read."  Since the example code is specifically for _Program.cs_, the program has just started and there has hardly been any time for the JSON configuration file to be changed, so it's not clear what is meant by the comment.

The following example for `ConfigurationBinder.Get<T>` is also followed by the same comment.  In this case, the code is not set specifically in _Program.cs_, but it does start with `configuration.Build()` which presumably reads the configuration file.  Does the comment mean that in order to read changes to the configuration since the app started, one needs to rebuild the configuration?

My understanding is that the JSON file configuration provider will update the built configuration when it detects changes to the file.  If so, then perhaps it's not the call to `configuration.Build()` that needs to be repeated, but only the call to `ConfigurationBinder.Get<T>`.  Or is there some magic in `Bind()` and `Get<T>()` that will maintain a reference to the returned object and update it should the configuration change? Unfortunately, the comment doesn't make any of that clear.

The section then continues with the use of `.Configure<T>` to inject configuration into a DI container, providing both the code to use when configuring the DI container as well as class that takes an `IOptions<TransientFaultHandlingOptions>` in the constructor and assigns its `.Value` to a readonly field.  The example is followed by the comment, "In the preceding code, changes to the JSON configuration file after the app has started are ***not*** read. To read changes after the app has started, use IOptionsSnapshot."  In this case, what is the value of the `ExampleService` class taking an `IOptions<TransientFaultHandlingOptions>` class instead of simply taking `TransientFaultHandlingOptions`?

The documentation should clearly answer the following questions regarding how updated configuration values can be read:
1. What reads updated configuration values?
2. What calls must be repeated to get the updated values?
3. With dependency injection, what interfaces need to be used to get updated values?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/options#options-interfaces)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 39307](https://dev.azure.com/msft-skilling/Content/_workitems/edit/39307)

**Comment by IEvangelist** [comment]
Hi @SEnglishSMP - thank you for posting this issue, I'm working through updating this article to address these concerns. 

>  In this case, what is the value of the `ExampleService` class taking an `IOptions<TransientFaultHandlingOptions>` class instead of simply taking `TransientFaultHandlingOptions`?

The `IOptions<T>` interface is registered with DI, to allow injection of any generic options type. Larger apps will likely have several different config classes, it's better to wrap them this way.

**Comment by SEnglishSMP** [comment]
Your updates to the documentations clarify several things.  Thanks!

> > In this case, what is the value of the `ExampleService` class taking an `IOptions<TransientFaultHandlingOptions>` class instead of simply taking `TransientFaultHandlingOptions`?
> 
> The `IOptions<T>` interface is registered with DI, to allow injection of any generic options type. Larger apps will likely have several different config classes, it's better to wrap them this way.

Simple Injector [recommends against](https://docs.simpleinjector.org/en/latest/servicecollectionintegration.html#working-with-ioptions) using `IOptions<T>` in _application components_ for several reasons.  Your answer is something that would be generally true of library components that can be used in a variety of applications and even other library components, each of which may need to manipulate configuration data.  If one is writing library components, I can see how using `IOptions<T>` could be of benefit there.

`IOptions<T>` also provides validation of configuration. This is mostly useful when there's distributed configuration (and possibly the need for distributed validation).

I'm don't see how these features make any real difference for option classes used only in the application in which they are defined.  My take is that `IOptions<T>` is good for library components and their configuration but brings no benefit for components configured and used only in the application for which they are defined.  Am I missing something?
