### ISSUE TITLE
POCOs domain classes and anemic domain model

### ISSUE THREAD

**Issue by kosletr** [dotnet/docs#32678]
[Enter feedback here]
Following the link to POCO's definition we see that they should include only props/fields and no methods. In this article we see that domain model classes should be POCOs. Isn't that the definition of an anemic domain model?

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 5a30bea5-326b-ea72-59ae-dfef1e190e4a
* Content: [Designing a DDD-oriented microservice](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @kosletr, thanks for posting here, for more information on the anemic domain model please refer to the link: https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model. I hope it will answer your question.

**Comment by IEvangelist** [comment]
Closed per @erjain
