### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alejandrojulius** [dotnet/docs#32676]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b961381-6f1a-dcb8-fd9c-99d83cd7123c
* Version Independent ID: 7654ffd4-0487-6ccf-0cd9-14deb00fec62
* Content: [Compiler Error CS1536](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1536)
* Content Source: [docs/csharp/misc/cs1536.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1536.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @alejandrojulius 

Can you add some details on what help you need? If you can post a code sample, that would help.
