### ISSUE TITLE
C# 11 is still documented as a preview feature after its GA release.

### ISSUE THREAD

**Issue by pjmlp** [dotnet/docs#32689]
Although .NET 7 was released on the 8th November, the C#11 related documentation still documents the new features as preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 11 - C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11)
* Content Source: [docs/csharp/whats-new/csharp-11.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-11.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 41127](https://dev.azure.com/msft-skilling/Content/_workitems/edit/41127)

**Comment by BillWagner** [comment]
Thanks for pointing this out @pjmlp 

I've opened a PR to address this.
