### ISSUE TITLE
Confusing Wording on Paragraph 5

### ISSUE THREAD

**Issue by salinaspaul** [dotnet/docs#32697]
There is confusing wording in paragraph 5, just under Figure 2-4 - specifically in the third sentence ("Docker Hub is a public registry maintained by Docker...").

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaef5307-5012-1192-2491-c6f8957e080c
* Version Independent ID: 8c5224d8-56b6-4d05-067f-21423ba787b0
* Content: [Docker containers, images, and registries](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/container-docker-introduction/docker-containers-images-registries)
* Content Source: [docs/architecture/microservices/container-docker-introduction/docker-containers-images-registries.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/container-docker-introduction/docker-containers-images-registries.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Hi @salinaspaul, thanks for your feedback. Here the author is trying to say that Docker maintains a public registry via [Docker Hub]/hub.docker.com/). And along with the Docker trusted registries, Azure also provides registries for the collection of images and offers the Azure Container Registry. I hope this helps.

**Comment by IEvangelist** [comment]
Closed per @erjain
