### ISSUE TITLE
Fix supported version reference

### ISSUE THREAD

**Issue by Shane32** [dotnet/docs#32698]
> .NET Framework 3.5 supports apps built for .NET Framework 1.0 through 3.5.

Should read as: 2.0 through 3.5

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e45b2a9-2466-689a-7e73-0c224ca8e98f
* Version Independent ID: 00ab7825-3aeb-04c5-ebf6-6166712ce848
* Content: [Install .NET Framework on Windows 11 - .NET Framework](https://learn.microsoft.com/en-Us/dotnet/framework/install/on-windows-11)
* Content Source: [docs/framework/install/on-windows-11.md](https://github.com/dotnet/docs/blob/main/docs/framework/install/on-windows-11.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Shane32** [comment]
See also:
- https://learn.microsoft.com/en-us/dotnet/framework/install/run-net-framework-1-1-apps?source=recommendations

**Comment by adegeo** [comment]
Good catch, thanks!
