### ISSUE TITLE
Cross-platform cryptography page has not been updated in a while

### ISSUE THREAD

**Issue by alexrp** [dotnet/docs#32708]
It seems like this page is only up-to-date for .NET 5. Two things immediately stand out to me:

* AES GCM is supported on macOS via CryptoKit now, but this is not documented.
* ChaCha20-Poly1305 support is not mentioned at all.

There may well be other issues. Someone from the cryptography team should probably have a look.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dba5d39-737f-cfa3-b1e4-c997e55312a8
* Version Independent ID: 95e31f6e-9a36-913e-6a02-7fb1606e5a52
* Content: [Cross-platform cryptography in .NET Core and .NET 5](https://learn.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography)
* Content Source: [docs/standard/security/cross-platform-cryptography.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/cross-platform-cryptography.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by alexrp** [comment]
cc @vcsjones because I just noticed https://github.com/dotnet/runtime/issues/80122. Should we merge these two issues?

**Comment by vcsjones** [comment]
Probably. I am going to take a swing at fixing up this article near the end of .NET 8 previews. There are some substantial changes coming in later .NET 8 previews — so I wanted to get a better sense of what .NET 8 is going to look like before attempting to fix this article up, lest it become severely out of date again.

**Comment by IEvangelist** [comment]
Hi @vcsjones - I assigned this issue to you, happy to review it when you put together a PR. Thanks
