### ISSUE TITLE
CallerArgumentExpression might be after CancellationToken 

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/docs#32702]
[Enter feedback here]
I think the rule might also want to skip the following:

where the CallerArgumentExpression is last because I think that has lower priority than the cancellation token.

public static void ExampleMethod(int required, CancellationToken ct = default, [CallerArgumentExpression("required")] string requiredName = null!)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e335f6e5-7d90-bfab-f95d-ab8ef3ba41fc
* Version Independent ID: 6be20f15-e5eb-0778-5fbe-38326d8e8f00
* Content: [Named and Optional Arguments - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#optional-arguments)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 230096](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230096)

**Comment by BillWagner** [comment]
That's a good point @qsdfplkj 

I've added it to our backlog.
