### ISSUE TITLE
This example does not run successfully as coded because of the injected logger in the grain

### ISSUE THREAD

**Issue by eswann** [dotnet/docs#32710]
The HelloGrain logger needs a type parameter to successfully inject the logger.

It should be:
```
public class HelloGrain : Grain, IHello
{
    private readonly **ILogger<HelloGrain>** _logger;

    public HelloGrain(ILogger<HelloGrain> logger)
    {
        _logger = logger;
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3e0034-a134-6eab-477f-5c5668eb68a0
* Version Independent ID: b61f5003-091e-e698-982b-124316d7eba3
* Content: [Minimal Orleans app sample project](https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/tutorial-1)
* Content Source: [docs/orleans/tutorials-and-samples/tutorial-1.md](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/tutorial-1.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 43552](https://dev.azure.com/msft-skilling/Content/_workitems/edit/43552)

**Comment by IEvangelist** [comment]
Hi @eswann - in .NET you can downcast from one interface to another if there is a hierarchy. In this case, the generic type `ILogger<T>` inherits from `ILogger`, thus a given `ILogger<T>` can be assigned to `ILogger`. This is a perfectly valid C#.

See this [sharplab for a working example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8BuEyABFGAA4A2xAvMTAKYDuxAkhZQBQCUA3ALAAoIQFEAHhA4NOZKnyFCAAgEYAbMUUAWYuMlUGAHgAqAPk6sA4g0bIoAYyMBPcodPEEzhtyEBvIcQC2JxdWDHdPUNpwlwFBQI1lADoVAE5ODxCMRIA5SQZQ+UEAXwVBWAQGZAAzCDsGIIiMX39AlQAGYlywfLCfYgBzBgReYhLi0vLKmrq2Kxt7YNcTYhAGzOa4wKM2CrBiPsHh0aExpQAmNg4V2etKhc8DcpMN+MUAZgSOrp7aZYAidhUaIMP6xV4fco7Bh7A5DEZFKIAdliYyAA=), also, [see `ILogger<T>`.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger-1?view=dotnet-plat-ext-7.0)
