### ISSUE TITLE
Serialization guidelines do not reflect v7 changes

### ISSUE THREAD

**Issue by htxryan** [dotnet/docs#32723]
Serialization guidelines do not reflect v7 changes. For instance, the "Serializable" attribute is still mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad80183-a94c-1344-7289-40e97a964118
* Version Independent ID: e0e88587-aeeb-b95a-65b3-d62db40cf0b9
* Content: [Serialization and custom serializers](https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization)
* Content Source: [docs/orleans/host/configuration-guide/serialization.md](https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/serialization.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by gfoidl** [comment]
X-ref: https://github.com/dotnet/docs/issues/32736

**Comment by IEvangelist** [comment]
Closing as duplicate to #32736
