### ISSUE TITLE
Add documentation for BroadcastChannel in Orleans 7.0

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32735]
**Issue description**

Orleans 7.0 replaced SimpleMessageStream with a separate abstraction, BroadcastChannel.
We need TOC changes and a documentation section for BroadcastChannel.

For more information, see: https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans#replacement-of-simplemessagestreams-with-broadcastchannel

xref https://github.com/dotnet/docs/issues/32734

cc @IEvangelist @benjaminpetit 

---
[Associated WorkItem - 46071](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46071)

**Comment by ReubenBond** [comment]
NOTE: We should include advice on when to use BroadcastChannel and when to use Streams (incl MemoryStreams).
We should note that BroadcastChannel only supports implicit subscriptions.

**Comment by IEvangelist** [comment]
Related to https://github.com/dotnet/orleans/issues/8203

**Comment by feitzi** [comment]
An important part is missing in the documentation. What exactly is a ChannelId, especially the Key part? I opened a separate issue [Broadcast and ChannelId · Issue #8292 · dotnet/orleans (github.com)](https://github.com/dotnet/orleans/issues/8292)
