### ISSUE TITLE
Remove references to SimpleMessageStreams in Orleans.Streams docs

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32734]
**Issue description**

Orleans 7.0 removed SimpleMessageStreams and replaced it with a separate abstraction called BroadcastChannel.
For the Streams docs, we should replace usage of SimpleMessageStreams with MemoryStreams.

For more information, see: https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans#replacement-of-simplemessagestreams-with-broadcastchannel

Separately, we need to add documentation for BroadcastChannel.
Example doc referring to SimpleMessageStream: https://learn.microsoft.com/en-us/dotnet/orleans/streaming/streams-quick-start

cc @IEvangelist @bradygaster @benjaminpetit

---
[Associated WorkItem - 46073](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46073)

**Comment by IEvangelist** [comment]
Related to https://github.com/dotnet/orleans/issues/8203
