### ISSUE TITLE
Update Grain Persistence documentation for Orleans 7.0

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/docs#32737]
**Issue description**

Here are some notable changes which are needed for the Grain persistence docs (https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/)

* Providers now use a pluggable serialization system: https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans#grain-storage-serializers. This needs to be configured on the provider's options and defaults to using Newtonsoft.Json as the default serializer.
* The interface used to implement a grain storage provider has changed (GrainId, not GrainReference): https://learn.microsoft.com/en-us/dotnet/api/orleans.storage.igrainstorage?view=orleans-7.0

cc @benjaminpetit @IEvangelist @bradygaster 

---
[Associated WorkItem - 46072](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46072)

**Comment by benjaminpetit** [comment]
This page should also be updated with the new interface: https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/custom-grain-storage

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8203
