### ISSUE TITLE
"Running the app" needs to be updated for Orleans 7.0

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/docs#32746]
The page on https://learn.microsoft.com/en-us/dotnet/orleans/deployment/ reference configuration method that doesn't exist, even in 3.x

The samples should just use `UseLocalhostClustering()` instead.

---
[Associated WorkItem - 46076](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46076)

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8203
