### ISSUE TITLE
Generated files don't get called

### ISSUE THREAD

**Issue by jektvik** [dotnet/docs#32740]
It just doesn't work -> I don't know why.
Followed through all instructions and the generator implementation of HelloFrom doesn't execute. VisualStudio doesn't see the generated file anywhere. Rider is smart enough to find it somewhere deep in windows AppData.../Temp, but it doesn't run when executing the project.

Adding EmitCompilerGeneratedFiles doesn't create any new files.

Adding         <CompilerGeneratedFilesOutputPath>               Generated          </CompilerGeneratedFilesOutputPath> Creates an empty dir.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @KathleenDollard

**Comment by tomarks** [comment]
I have the same issue.

Windows 11
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.2

**Comment by macias** [comment]
Same story here, with JetBrains Rider. The compiler generates "auto-generated" code, I can see it, and all, but when running the application it is ignored -- so the call goes to empty partial method, which by the rules of the empty partial methods is not called.
