### ISSUE TITLE
Unclear what type of project that should be used for SourceGenerator

### ISSUE THREAD

**Issue by Piveo** [dotnet/docs#32753]
Hi, I'm a bit confused, step 4 says to create a library and then step 7 says "Edit the original console application project and add the following, replacing the project path with the one from the .NET Standard project you created above:". Which is the right one? Have tried with both library and .NET standard project without getting the result shown in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
@Piveo There are two projects:

- A console app (created in step 1)
    This can target any framework (in the article it's .NET 6), and this is the project that *consumes* the source generator.
- A class library (created in step 4)
   This **MUST** be `netstandard2.0`, and this is the source generator itself.

In step 7, you add a `ProjectReference` for the source generator project (netstandard2.0) to the console app. That way, the generator is run when you compile the console app.

**Comment by Youssef1313** [comment]
If you still can't achieve the expected result, please upload your solution (containing the two projects), and I'll take a look to see what is missing.
