### ISSUE TITLE
How to undo checking "do not use top level statements"

### ISSUE THREAD

**Issue by nick6502** [dotnet/docs#32759]
Must I delete my project and start over?  Is there a way to access this selection once I've passed the page where it appeared?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6+ - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment]
Hi @nick6502 

There is a refactoring available:  Right-click on the top level statements, and select "Convert to 'Program.Main' style program"

There is also a refactoring to convert from Program.Main style to top level statements, for those that prefer the alternative.

Closing as an answered question.
