### ISSUE TITLE
Error on documentation?

### ISSUE THREAD

**Issue by kwemou** [dotnet/docs#32754]
Dear all,
there is probably an error or unclarity concerning the orleans server configuration.
In the section below in comments 4 and 5. Please see my thought about what should be there.
Kind regards
Emeric

```csharp
.Configure<EndpointOptions>(options =>
{
    // 1 Port to use for Silo-to-Silo
    options.SiloPort = 11111;
    // 2 Port to use for the gateway
    options.GatewayPort = 30000;
    // 3 IP Address to advertise in the cluster
    options.AdvertisedIPAddress = IPAddress.Parse("172.16.0.42");
    // 4 The socket used for silo-to-silo will bind to this endpoint --> here it should be client to silo, not silo-to-silo?
    options.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Any, 40000);
    // 5 The socket used by the gateway will bind to this endpoint --> here it should be silo-to-silo?
    options.SiloListeningEndpoint = new IPEndPoint(IPAddress.Any, 50000);
})
```
okay

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c693bc1-0e57-d0cc-e635-a5b39650ff76
* Version Independent ID: c4efa180-e101-f723-2a36-73906469635f
* Content: [Server configuration](https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/server-configuration)
* Content Source: [docs/orleans/host/configuration-guide/server-configuration.md](https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/server-configuration.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 46075](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46075)

**Comment by IEvangelist** [comment]
Related to dotnet/orleans#8209
