### ISSUE TITLE
Alot (most?) hyperlinks point back to the same article

### ISSUE THREAD

**Issue by RasmusWesterlundh** [dotnet/docs#32764]
[Enter feedback here]

Alot of the hyperlinks all direct back to the same page. For example:

> See the [OpenTelemetry documentation](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) for more information about OpenTelemetry configuration options, in particular, alternative hosting options that are useful for ASP.NET applications.

> # Create an example application
> Prerequisites: [.NET Core 3.1 SDK](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) or a later version

> # View metrics in Grafana with OpenTelemetry and Prometheus
> ## Prerequisites
> [.NET Core 3.1 SDK](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) or a later version
> ## Overview
> [OpenTelemetry](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) is a vendor-neutral open-source project supported by the [Cloud Native Computing Foundation](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) that aims to standardize generating and collecting telemetry for cloud-native software. The built-in platform metric APIs are designed to be compatible with this standard to make integration straightforward for any .NET developers that wish to use it. At the time of writing, support for OpenTelemetry metrics is relatively new, but [Azure Monitor](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-overview) and many major APM vendors have endorsed it and have integration plans underway.
> 
> This example shows one of the integrations available now for OpenTelemetry metrics using the popular OSS [Prometheus](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) and [Grafana](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) projects. The metrics data will flow like this:
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f111f896-9278-9ca4-a5eb-0a448a7be40d
* Version Independent ID: 1cab703b-de5a-f0a2-bfa4-7c5df8d8423b
* Content: [Collect metrics - .NET](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection)
* Content Source: [docs/core/diagnostics/metrics-collection.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/metrics-collection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by adegeo** [comment]
I'm not sure where you copied that from, but the links look correct on the published site and in the source.
