### ISSUE TITLE
Create the "build your own environment" quick start

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3278]
This new topic follows the interactive quick starts. Readers will learn to install VS Code and .NET Core. They will validate the installation by creating a first console application.

**Comment by BillWagner** [comment]
I don't believe this should be a separate topic. The right action here is to point developers to the [Get started in 10 minutes](https://www.microsoft.com/net/core) on the .NET Core site when they are ready to move beyond the inline interactive tutorials.

That's the quickest, and simplest way to get started. It would then point them back to the later quick starts that they would run on their machine.

/cc @rowanmiller 

@rpetrusha Thoughts? Or is there a better page in docs for setting up your own environment?

**Comment by rowanmiller** [comment]
> I don't believe this should be a separate topic. The right action here is to point developers to the Get started in 10 minutes

That makes sense to me. We keep that up to date with every release, and do a bunch of dynamic stuff around OS detection etc.

**Comment by rpetrusha** [comment]
@BillWagner and @rowanmiller, I agree. The Get Started in 10 minutes page is quite good, and there's really no need for us to reinvent the wheel.
