### ISSUE TITLE
g

### ISSUE THREAD

**Issue by RatGaya** [dotnet/docs#32798]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 206b5eae-0d27-4afc-ac55-b3c1705096db
* Version Independent ID: f3763810-1049-afbe-f279-fa72ea36a99c
* Content: [Compiler Error CS0161](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0161?f1url=%3FappId%3Droslyn%26k%3Dk(CS0161))
* Content Source: [docs/csharp/misc/cs0161.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0161.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @RatGaya 

Was there more you wanted to add here? If so, can you edit the issue and add more details.
