### ISSUE TITLE
Can not download dotnet on rasppbery pi

### ISSUE THREAD

**Issue by ddimitrov9405** [dotnet/docs#32801]
Hello,

When I try to download dont with this command "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel Current" I get stuck on "dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100/dotnet-sdk-7.0.100-linux-arm.tar.gz". When I go to "https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100/dotnet-sdk-7.0.100-linux-arm.tar.gz" from windows PC in the same network it starts to download a file. Do you have any idea why it wouldn't be working on the pi?

I am using rasppbery pi 4, 4gb ram.  

Best regards,
Dimitar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to Raspberry Pi](https://learn.microsoft.com/en-us/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@ddimitrov9405 That's weird. So it can retrieve the install script from dot.net, but it errors out in the install script?

What happens if you try to `ping aka.ms` from the rpi?
