### ISSUE TITLE
[Breaking change]: Projects now automatically get a RuntimeIdentifier if they use Publish properties that require a RuntimeIdentifier.

### ISSUE THREAD

**Issue by nagilson** [dotnet/docs#32816]
### Description

As of .NET 7 RC-1, if a project specifies any of the following: 

- `SelfContained`
- `PublishAot`
- `PublishReadyToRun`
- `PublishSingleFile`
- `PublishSelfContained` ( In 7.0.200+)

The project will get a `RuntimeIdentifier` automatically. 
In 7.0.101+ this can be disabled by setting `<UseCurrentRuntimeIdentifier>false</UseCurrentRuntimeIdentifier>` in the project file. 

Old projects that circumvented this error; used `RuntimeIdentifiers` but no `RuntimeIdentifier`; used hard-coded paths without RIDs and projects that had these properties but used a build, instead of a publish, and accepted publish being in a broken state, may be affected. There are other potential nuances that may or may not break individual situations that we are unaware of. 

### Version

.NET 7

### Previous behavior

Previously, these projects would fail to publish with errors such as 

`
It is not supported to publish an application to a single-file without specifying a RuntimeIdentifier. 
Please either specify a RuntimeIdentifier or set PublishSingleFile to false.
`

OR 
`
 error NETSDK1031: It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier. You must either specify a RuntimeIdentifier or set SelfContained to false.
 `

But they could potentially build without a `RuntimeIdentifier` in some cases like `PublishSingleFile`, or with special `RuntimeIdentifiers` logic.

### New behavior

As of .NET 7 RC-1, if a project specifies any of the following: 

- `SelfContained`
- `PublishAot`
- `PublishReadyToRun`
- `PublishSingleFile`
- `PublishSelfContained` ( In 7.0.200+)

The project will get a `RuntimeIdentifier` automatically. 

This can cause build failures on projects like `CrossGen`, that rely on `RuntimeIdentifiers` but no `RuntimeIdentifier` as `RuntimeIdentifier` may affect the output path dinstictly from the `Identifiers`. It can also cause failures on AnyCPU projects that rely on `PublishSingleFile` but don't always give a `RuntimeIdentifier` when taking other actions, with failures such as: `The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core."... code 2147516546 (0x80008082)` 

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [X] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

The majority of .NET projects would previously fail to publish using these properties without `RuntimeIdentifier` set, and this reduces the need to add the RID manually every time you use the above properties. 

### Recommended action

None required if the project is not impacted.

If the project is impacted, this can be disabled with 
`<UseCurrentRuntimeIdentifier>false</UseCurrentRuntimeIdentifier>` latest versions of 7.0.100 RTM.

Setting `AppendRuntimeIdentifierToOutputPath` = `false` can fix breaks that relate to the output path changing. 
 
# 

* We are also waiting for this PR: https://github.com/dotnet/sdk/pull/29031 to potentially reduce the scope of the breaking change in 7.0.200 to only Publish. 

### Feature area

SDK

---
[Associated WorkItem - 45473](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45473)

**Comment by dsplaisted** [comment]
I'm not sure if we typically count it a breaking change if the previous behavior was that you would get a build error, and the new behavior includes building successfully.

**Comment by gewarren** [comment]
@PriyaPurkayastha Should this be considered a breaking change given that it _removes_ a build error?

**Comment by PriyaPurkayastha** [comment]
As per my interpretation of the description, while this change does help projects that previously failed to build when certain properties were used but this identifier wasn't set, there are other scenarios that were not failing earlier that could be impacted and the extent of those are not fully understood. As a result, a switch has been provided to revert back to previous behavior if this change breaks anyone. Hence it is deemed as a breaking change - not for the issue that it addresses but for the fallouts that it could cause.
