### ISSUE TITLE
Need link to c# comments, not doc comments

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#32817]
Search can't find  c# comments
Probably a SEO problem but I need a link for https://github.com/dotnet/AspNetCore.Docs/pull/27805/files

- https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/comments-in-code
- https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/
- 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74e905-523c-dae9-f741-af5e52785a9c
* Version Independent ID: c9b7c7a1-0584-b6e6-95cd-5276788fdda0
* Content: [Documentation comments - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments)
* Content Source: [standard/documentation-comments.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 45422](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45422)

**Comment by BillWagner** [comment]
Oddly enough, we don't have one.

I'll add a page under the reference section for comments.
