### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/docs#32823]
[Enter feedback here]
Missing update the version from net6.0 to net.70

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by theolivenbaum** [comment]
The section for 22.04 has the old version for the install command

**Comment by theolivenbaum** [comment]
The section for 22.04 has the old version for the install command

**Comment by adegeo** [comment]
There is a note that you may have missed. The Ubuntu feed fro 22.04 will not include .NET 7. Only the **Microsoft package feed** for 22.04 does have .NET 7.

![image](https://user-images.githubusercontent.com/67293991/206348039-b557ec69-db12-4b92-90a4-727533dd5eb8.png)

I checked and the MS feed 22.04 lists .NET 7.
