### ISSUE TITLE
Links to GitHub repository locations are broken

### ISSUE THREAD

**Issue by martin-pes** [dotnet/docs#32821]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: babf6e7d-18bc-3170-3e35-ec75a0373c55
* Version Independent ID: b21f264d-2795-d68f-4c97-8af273562de5
* Content: [Tutorial: Hello world](https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/overview-helloworld)
* Content Source: [docs/orleans/tutorials-and-samples/overview-helloworld.md](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/overview-helloworld.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 45419](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45419)

**Comment by IEvangelist** [comment]
Fixed by #32800, and related to #32799
