### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by thestugray** [dotnet/docs#32831]
Hey,

In the example code between old and new behavior on this page (https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/actionresult-statuscode), they are both identical. The new behavior should be 

```
// Generates a 200 OK response
public ActionResult<Model> Get()
{
    Response.StatusCode = StatusCodes.Status200OK;
    return new Model();
}
```

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 204588be-f452-4db7-db93-ed4ea5af6cd0
* Version Independent ID: 64b65b92-b86a-1741-2a38-c1119b7d2ed1
* Content: [Breaking change: ActionResult&lt;T&gt; sets StatusCode to 200 - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/actionresult-statuscode)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/actionresult-statuscode.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/actionresult-statuscode.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @serpent5
* Microsoft Alias: **gewarren**

**Comment by serpent5** [comment]
Hi @thestugray. Thanks for the feedback.

The code sample in the article is correct. The _comment_ changes between the two, but the code remains the same. The behavior has changed, in that the breaking change results in the explicit call to set `Response.StatusCode = StatusCodes.Status202Accepted` now being ignored.
