### ISSUE TITLE
From where is DefaultJsonSerialization coming?

### ISSUE THREAD

**Issue by DasCodeaffe** [dotnet/docs#32856]
What is DefaultJsonSerialization and why isn't "new JsonSerializerOptions(JsonSerializerDefaults.Web (or General))" used?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46af0b96-2d12-9cac-2f8f-15eb49d0292d
* Version Independent ID: 33db41be-42f9-bb94-65fe-0cf7d1c64f12
* Content: [Use the IHttpClientFactory - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
* Content Source: [docs/core/extensions/httpclient-factory.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/httpclient-factory.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 50837](https://dev.azure.com/msft-skilling/Content/_workitems/edit/50837)

**Comment by gewarren** [comment]
@dasCodeaffe Can you clarify where in the article this is used?

**Comment by DasCodeaffe** [comment]
> @DasCodeaffe Can you clarify where in the article this is used?

It's used multiple times on this page:
https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory
