### ISSUE TITLE
I think DiagnosticListener could be doumented better

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/docs#32865]
Thanks for documentation. It is very helpful but I think, it is not very clear about how to create a new `DiagnosticSource` instance and How we can only subscribe to that specific instance (It is a `DiagnosticListener` which implemented `IObservable<KeyValuePair<string,object>> ` so we can directly subscribe to an special observer) instead of subscribing to all diagnostic sources through static property `AllListeners` of `DiagnosticListener` class (As you know it is also an `IObservable<System.Diagnostics.DiagnosticListener>` so need an extra subscription  to an intermediate Observer (which implements `IObserver<DiagnosticListener>`)). So I think we can do the work more simpler there.
Also What about the DiagnosticSource in previous version which is subscribed to using DiagnosticName attribute ? Is that approach useful in new version of .Net or it is obsolete?! 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65f3736e-83fa-ed03-a964-e21d23f52663
* Version Independent ID: d6e9578b-62de-00ca-ffb0-81d4a3551bc5
* Content: [DiagnosticSource and DiagnosticListener](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnosticsource-diagnosticlistener)
* Content Source: [docs/core/diagnostics/diagnosticsource-diagnosticlistener.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/diagnosticsource-diagnosticlistener.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by tommcdon** [comment]
@davmason  @tarekgh  would one of y'all mind taking a look?

**Comment by adegeo** [comment]
Ping on @davmason @tarekgh

**Comment by tarekgh** [comment]
The doc https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md has some useful information. 

I am wondering, why using DiagnosticSource? I suggest looking at https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing to see the more updated ways to handle tracing in general.

**Comment by abdollahkahne** [comment]
Thanks for your guidelines.
I am just a learner and I am try everything I see in .Net and .Net documentation. If there is more usable tools over there I will use them by sure but I want to be familiar with all available options.  I do not close this issue but you could do it if it should.
Thanks again

**Comment by tarekgh** [comment]
If you are a new learner to the space, I suggest you avoid using DiagnosticSource and instead use ActivitySource. the distributed tracing link I pasted above it good to start from there.

**Comment by abdollahkahne** [comment]
Thank you. I do consider your recommendation and also I closed the issue.
