### ISSUE TITLE
Please document a policy for third party libraries in .NET Microsoft Docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#32861]
Context: https://twitter.com/runfaster2000/status/1599196714539560960

---
[Associated WorkItem - 46161](https://dev.azure.com/msft-skilling/Content/_workitems/edit/46161)

**Comment by MSDN-WhiteKnight** [comment]
What options are being considered for such policy? Is the intent that any library, open-source or commercial, could be linked in docs if it's useful in given context (like does something that standard libraries can't do)? Or would they need to meet some criteria on licenses/popularity/level of maintenance?
