### ISSUE TITLE
dotnet-trace missing link for macOS ARM version

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/docs#32875]
**Issue description**

The [dotnet-trace docs page](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace) only seems to include an install link for macOS x64 but not ARM64. Is there even a ARM version? If you can give me the link, I am happy to open a PR.

**Target framework**

.NET 7.0.0

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57216dad-d87d-eeef-adc8-82bfe4251343
* Version Independent ID: 3e7ab61f-5a06-b92c-5c74-0fae43adb35e
* Content: [dotnet-trace diagnostic tool - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace)
* Content Source: [docs/core/diagnostics/dotnet-trace.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dotnet-trace.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by tommcdon** [comment]
Hello @CollinAlpert!  This is tracked on https://github.com/dotnet/diagnostics/issues/3494

**Comment by CollinAlpert** [comment]
Great, thanks!
