### ISSUE TITLE
Need to add note about `System.Drawing.Common` being deprecated in Linux in .NET 7

### ISSUE THREAD

**Issue by udlose** [dotnet/docs#32878]
According to @svick  noted here (https://github.com/dotnet/runtime/issues/80148), the support for `System.Drawing.Common` has now been completely deprecated in .NET 7; thus, the `System.Drawing.EnableUnixSupport` setting in `runtimeconfig.template.json` is no longer valid.

The list of Breaking changes in .NET 7 does not include any information about the deprecation of Unix support for `System.Drawing.Common` or the deprecation of the `System.Drawing.EnableUnixSupport` config setting.  This info should be added to the list of Breaking Changes so that developers are aware of this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fda38618-d1fc-5b45-9a09-1a02643d99ae
* Version Independent ID: e59e516b-dd93-937d-f9a1-bce4b5eb3aa9
* Content: [Breaking changes in .NET 7 - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0)
* Content Source: [docs/core/compatibility/7.0.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/7.0.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@udlose This was technically a breaking change in .NET 6, not .NET 7, and as such is listed here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only. This article also contains a note that the switch to re-enable support was removed in .NET 7 (and I don't believe the removal of the switch is considered an additional breaking change).

**Comment by gewarren** [comment]
Related to #33653.
