### ISSUE TITLE
Add documentation for IDEXXXX

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#32876]
| Id | url | title |
| -- | -- | -- | 
| IDE0200 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0200 | Remove unnecessary lambda expression |
IDE0211 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0211 | Convert to 'Program.Main' style program
IDE0220 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0220 | Add explicit cast
IDE0250 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0250 | Make struct 'readonly'
IDE0260 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0260 | Use pattern matching
IDE0270 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0270 | Use coalesce expression
JSON002 |   | Probable JSON string detected
RE0001 |   | Invalid regex pattern

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/65769#issuecomment-1337237203 for IDE0270.

**Comment by KUTlime** [comment]
A duplicate with #30361.

**Comment by gewarren** [comment]
Closing in favor of https://github.com/dotnet/docs/issues/30361.
