### ISSUE TITLE
Surprising flow with Not Boolean?

### ISSUE THREAD

**Issue by vbjay** [dotnet/docs#32882]
```vb
Module Module1

    Sub Main()

        Dim cat = "The cat is in the hat"
        Dim msgs() As String = {Nothing, cat, "The other error", ""}



        For Each strMessage In msgs
            Dim hasCat = strMessage?.Contains(cat)


            Console.WriteLine($"{strMessage}:{strMessage?.Contains(cat)}: hasCat hasvalue:{hasCat.HasValue} and hascat value: {hasCat.GetValueOrDefault}")

            If Not strMessage?.Contains(cat) Then
                Console.WriteLine("Inside if original")

            End If

            If Not If(strMessage?.Contains(cat), False) Then
                Console.WriteLine("Inside if mod")

            End If


        Next
        Console.WriteLine("Press a key...")
        Console.Read()

    End Sub

End Module
```
It needs to be clear that ```if Not someStr?.Contains("some string")``` or any other value that evaluates as boolean? ( and has the value of nothing or HasValue=false) would actually run else block in if to prevent any confusion.  The evaluation follows the sql evaluation where null/nothing does not = another null/nothing.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7427bc30-4d66-b234-4537-200d4419cc24
* Version Independent ID: 786cb51a-cd8d-95a7-a11c-c39245a01e9d
* Content: [Null-conditional Operators - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/null-conditional-operators)
* Content Source: [docs/visual-basic/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/null-conditional-operators.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks @vbjay 

I've added this to our backlog for when we next update this article. I've also added the "help wanted" label. You've described what's needed with clarity, and community members could make this change.
