### ISSUE TITLE
Surprising flow with Not Boolean?

### ISSUE THREAD

**Issue by vbjay** [dotnet/docs#32883]
```vb
Module Module1

    Sub Main()

        Dim cat = "The cat is in the hat"
        Dim msgs() As String = {Nothing, cat, "The other error", ""}



        For Each strMessage In msgs
            Dim hasCat = strMessage?.Contains(cat)


            Console.WriteLine($"{strMessage}:{strMessage?.Contains(cat)}: hasCat hasvalue:{hasCat.HasValue} and hascat value: {hasCat.GetValueOrDefault}")

            If Not strMessage?.Contains(cat) Then
                Console.WriteLine("Inside if original")

            End If

            If Not If(strMessage?.Contains(cat), False) Then
                Console.WriteLine("Inside if mod")

            End If


        Next
        Console.WriteLine("Press a key...")
        Console.Read()

    End Sub

End Module
```
It needs to be clear that ```if Not someStr?.Contains("some string")``` or any other value that evaluates as boolean? ( and has the value of nothing or HasValue=false) would actually run else block in if to prevent any confusion.  The evaluation follows the sql evaluation where null/nothing does not = another null/nothing.  

Related to #32882

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2227593d-9c44-a7f9-0f7d-7b80af524301
* Version Independent ID: 92e9420d-a677-1472-423f-a5890f232284
* Content: [Not Operator - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/not-operator)
* Content Source: [docs/visual-basic/language-reference/operators/not-operator.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/not-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks @vbjay 

I've added this to our backlog for when we next update this article. I've also added the "help wanted" label. You've described what's needed with clarity, and community members could make this change.

**Comment by IEvangelist** [comment]
Closing as dup of https://github.com/dotnet/docs/issues/32882

**Comment by postmeback** [comment]
I am unable to find the given example on the page.Can someone guide me on this ?

I would like to contribute

**Comment by postmeback** [comment]
Hi @vbjay , can you give me the link, where you got the example. In the given link, the example is not present.

CC:  @BillWagner , @IEvangelist

**Comment by vbjay** [comment]
Read all comments on the issue.
