### ISSUE TITLE
Describe limitations of async serialization with System.Text.Json source generator

### ISSUE THREAD

**Issue by szpght** [dotnet/docs#32897]
Hi
According to [this and subsequent comments](https://github.com/dotnet/runtime/issues/75139#issuecomment-1238573075) use of `JsonSourceGenerationMode.Serialization` is unsupported in async mode and sync overloads of `JsonSerializer.Serialize` that accept `Stream` also count as async. It would be great if these limitations were described, so for example it would be obvious that ASP.NET Core response serialization doesn't take advantage of optimized code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee53c3dc-df79-82ef-ce25-3233ff292c55
* Version Independent ID: 558903e9-8173-464e-ff8b-7744419ad7e4
* Content: [How to use source generation in System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation)
* Content Source: [docs/standard/serialization/system-text-json/source-generation.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/source-generation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 67113](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67113)

**Comment by eiriktsarpalis** [comment]
> for example it would be obvious that ASP.NET Core response serialization doesn't take advantage of optimized code.

That's partly true. As of .NET 8 aspnetcore will in fact utilize the fast path (as a fallback to metadata mode) provided that the payload is small enough to support non-streaming serialization.
