### ISSUE TITLE
NETSDK1022: Duplicate items were included - setting for page items should be documented

### ISSUE THREAD

**Issue by nickkfwong** [dotnet/docs#32907]
Hi,
I am working on a WPF project and see this NETSDK1022 error for 'Page' Item as well.

Although VS2022 shows correct suggestion to set 'EnableDefaultPageItems' to false, this page should (probably) also list the usage of it.

Update:
Btw - I realized the property is being described here:
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#enabledefaultpageitems

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9399f094-7665-b8ae-90f2-a108b9e4ad27
* Version Independent ID: 7cf5b33e-29f8-343e-fa17-8ddaceb5ae8a
* Content: [NETSDK1022: Duplicate items were included. - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1022)
* Content Source: [docs/core/tools/sdk-errors/netsdk1022.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1022.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @marcpopMSFT
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for pointing that out - I'm updating the article.

**Comment by nickkfwong** [comment]
thank you!
