### ISSUE TITLE
Error in DirectCallWithNullOrEmpty()

### ISSUE THREAD

**Issue by VaclavBabka** [dotnet/docs#32902]
In section "**Add and run unit test methods**", step 1., C# code block, test method `DirectCallWithNullOrEmpty()`, line `bool result = StringLibrary.StartsWithUpper(word ?? string.Empty);` should be `bool result = StringLibrary.StartsWithUpper(word);` because with `?? string.Empty` the null value in `word` is never actually passed to the `StartsWithUpper` method. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Test a .NET class library using Visual Studio - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?tabs=csharp&pivots=dotnet-7-0)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 48603](https://dev.azure.com/msft-skilling/Content/_workitems/edit/48603)

**Comment by tdykstra** [comment]
@VaclavBabka thanks for reporting that, I'm fixing it.
