### ISSUE TITLE
\b used instead of \n in host.cpp 

### ISSUE THREAD

**Issue by tandasat** [dotnet/docs#3291]
In samples/core/hosting/host.cpp, `\b` is used instead of `\n` around line 168.
```
	else
	{
		printf("Runtime started\b");
	}
```
Because of this error, this and next output are displayed into one line unintentionally.

**Comment by mairaw** [comment]
Thanks for creating the issue and making the fix @tandasat. For small issues like this where you intend to make the fix, you can skip the issue creation step and just submit the fix in a PR!
