### ISSUE TITLE
offline / on-premise build compatibility non-existent

### ISSUE THREAD

**Issue by asaf400** [dotnet/docs#3293]
# Issue Title

In the current state, both the 'master' and 'live' branches are broken in respects to building the docs in HTML form, for later use in an offline on-premise enterprise network, for use of enterprise developers

My plan as a DevOps engineer in my enterprise was to build this docs repo, compress it and deploy it in my organization using a simple production web server like ngnix or httpd..

# General

I've installed docfx through chocolatey, cloned this repo, then used the following options (respectively):
docfx -t default --serve
docfx build -t common --serve
docfx serve _site
docfx serve -t default
docfx serve -t common

all options yield the same result, a broken website with the following problems:

- navbar (#navbar) is always showing (on-top) on PC even through browser is running (about 1280x1024)
  scaling down to mobile view in browser dev-tools, enables the botton to enable\disable the navbar, 
  which works, but only for mobile (button ineffective for PC)
  my workaround was to implement an node\element removal through js in main.js 

![navbar1](https://user-images.githubusercontent.com/14169006/31052377-6f5edf00-a68b-11e7-907f-340e9ff12d76.png)
![navbar2](https://user-images.githubusercontent.com/14169006/31052379-73071da2-a68b-11e7-8f49-657aea35f5ae.png)

- logo svg's on the index are scaled to 100% - SVG, which is HUGE
  this issue is specific only for the github code, and on https://docs.microsoft.com/en-us/dotnet/ the 
  scale is done in a different manner, one that makes SVG's and other image format behave better

![svg](https://user-images.githubusercontent.com/14169006/31052380-797857be-a68b-11e7-96ef-46652ebdcf7f.png)

  `Element.prototype.remove = function() {
    this.parentElement.removeChild(this);
}
NodeList.prototype.remove = HTMLCollection.prototype.remove = function() {
    for(var i = this.length - 1; i >= 0; i--) {
        if(this[i] && this[i].parentElement) {
            this[i].parentElement.removeChild(this[i]);
        }
    }
}
console.log("...");
var checkExist = setInterval(function() {
    console.log("....");
   if ($('#navbar')) {
      console.log("Exists!");
      clearInterval(checkExist);
	  document.getElementById("navbar").remove();
	  // var element = document.getElementById("navbar")
	  // element.outerHTML = "";
	  // delete element;
   }
}, 100); // check every 100ms`

- broken folder structure:
  when building the repo using commands mentioned above, the built site's folder tree is:
  ./_site/styles
  ./_site/images
  ./_site/core
  ./_site/csharp
  ./_site/<etc....>

  However when viewing the site with a browser, all the internal references are including 'dotnet' prefix:
  ./_site/dotnet/styles
  ./_site/dotnet/images
  ./_site/dotnet/core
  ./_site/dotnet/csharp
  ./_site/dotnet/<etc....>

  This breaks javascript, images and links, and require a manual move of all items under _site to _site/dotnet folder (note '/' is just used as a path symbol, not bound to windows '\' or linux '/' styles, docfx is used on windows 8.1, as screenshots suggest)

**Comment by mairaw** [comment]
HI @asaf400, I'll need to follow up on this one with the engineering team. I'm not sure if this scenario is supported at the moment.

**Comment by dend** [comment]
Thanks for the feedback! 

We don't currently support standalone offline builds by third-parties - while we rely on DocFX as the underlying engine that generates and renders documentation, we also implement a number of very specific extensions and configurations that rely on docs.microsoft.com infrastructure, that this docset depends on. Without those, the rendering will not be accurate.

**Comment by mairaw** [comment]
So I'll be closing this issue then @asaf400, given this is not a content issue per se. For feedback and requests. there's also the UserVoice site here and people can vote for what they want the most: https://aka.ms/sitefeedback

If you're on a Windows environment, we'll also be shipping the .NET offline books (hopefully soon) for Visual Studio 2017. Maybe that could be an option for you too? There are already a few of the books published like C#, F# and VB and we'll be adding .NET Core, .NET Framework and others next.

Thanks for your feedback!

**Comment by asaf400** [comment]
Okay thanks, hopefully my earlier comment would still help others which are looking to get the same end result, through this closed issue..

I hope you consider making this repo more portable and independent from the official hosting on Microsoft.com as the documentation of most other programming languages (go, Python, Ruby) are available for building in an html static format.
That has become a standard which also includes 3rd party modules ( Ruby gems, readthedocs python, etc..)

I'll try and post a feedback on this as well..
