### ISSUE TITLE
dotnet install command. 

### ISSUE THREAD

**Issue by JustJordanT** [dotnet/docs#32949]
From [this](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template) documentation page, `dotnet new install` does not seem to work on 6.0.111, But I noticed that the new format was able to work for me using the `dotnet new --install` stated in the docs [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install)

Current dotnet versions. System is MacOS
```
.NET SDKs:
Version      Status
----------------------------------------
6.0.111      Up to date.
6.0.202      Patch 6.0.203 is available.

Try out the newest .NET SDK features with .NET 7.0.100.

.NET Runtimes:
Name                          Version      Status
---------------------------------------------------------------------
Microsoft.NETCore.App         6.0.1        Patch 6.0.11 is available.
Microsoft.AspNetCore.App      6.0.4        Patch 6.0.11 is available.
Microsoft.NETCore.App         6.0.4        Patch 6.0.11 is available.
Microsoft.AspNetCore.App      6.0.11       Up to date.
Microsoft.NETCore.App         6.0.11       Up to date.

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097102bb-f6d9-c469-5556-ae1f16fdc4fe
* Version Independent ID: 77b25381-6e0f-949f-5f96-b83e9b61e9fc
* Content: [Create a project template for dotnet new - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template)
* Content Source: [docs/core/tutorials/cli-templates-create-project-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-project-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 52198](https://dev.azure.com/msft-skilling/Content/_workitems/edit/52198)

**Comment by adegeo** [comment]
If you upgrade your SDK to .NET 7 it will work. This article was mass-updated in a PR which changed the commands to the .NET 7 versions but didn't consider changing the article itself to be .NET 7.

Really the solution is to update this article to describe .NET 6 and .NET 7.
