### ISSUE TITLE
Download button links to wrong language

### ISSUE THREAD

**Issue by anishprasad01** [dotnet/docs#32946]
This is a small thing, but when I click the download link for .NET Core from the `en-us` page, it links to the `es-es` version of the page.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e
* Version Independent ID: 68d524f7-6cf1-2caa-56d5-f243952d1526
* Content: [Install .NET on macOS - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/macos)
* Content Source: [docs/core/install/macos.md](https://github.com/dotnet/docs/blob/main/docs/core/install/macos.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @anishprasad01

The links we use don't have a language slugs in them. The website itself usually detects your language in the browser and sends you to the appropriate language version of the page.

@gewarren do you know where the **anishprasad01** can file a problem with the site? I can't seem to find a link.

**Comment by gewarren** [comment]
I don't think it's a problem with dotnet.microsoft.com - I think it's more about the browser, as you noted. For me, the link ends up on the en-US site. But if you think there's a problem with dotnet.microsoft.com, let me know and I'll get this issue transferred.

**Comment by anishprasad01** [comment]
Just me then. Sorry for the alarm.
