### ISSUE TITLE
Different behaviour running the application as a Windows Service

### ISSUE THREAD

**Issue by Gix65** [dotnet/docs#32944]
Running the example inside a Windows Service the synchronization doesn't seem to work, here's the output: 

DownloadDocsMainPageAsync: About to start downloading.
Main: Launched downloading.

and that's it.
(the await operator has a different behaviour in this case)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07164632-3cf8-864e-cd1e-485b73ed95a0
* Version Independent ID: 67bfb75a-8dd8-ecf3-ce15-2a531833e8b5
* Content: [await operator - asynchronously wait for a task to complete ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await)
* Content Source: [docs/csharp/language-reference/operators/await.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/await.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Gix65 

Can you post a snippet from the service? I'm not sure what's causing the difference.

**Comment by Gix65** [comment]
Hi,

I just added the class























*    public static class AwaitOperator    {        public static async Task
Main()        {            Task<int> downloading =
DownloadDocsMainPageAsync();            Log.traceAlways($"{nameof(Main)}:
Launched downloading.", ref ReadMyParameters.parametri);            int
bytesLoaded = await downloading;
Log.traceAlways($"{nameof(Main)}: Downloaded {bytesLoaded} bytes.", ref
ReadMyParameters.parametri);        }        private static async Task<int>
DownloadDocsMainPageAsync()        {
Log.traceAlways($"{nameof(DownloadDocsMainPageAsync)}: About to start
downloading.", ref ReadMyParameters.parametri);            var client = new
HttpClient();            byte[] content = await
client.GetByteArrayAsync("https://docs.microsoft.com/en-us/
<https://docs.microsoft.com/en-us/>");
Log.traceAlways($"{nameof(DownloadDocsMainPageAsync)}: Finished
downloading.", ref ReadMyParameters.parametri);            return
content.Length;        }    }*

to my Windows service project (Log.traceAlways() simply writes a row in a
log file), added the call to Main() into the InitInstance() method:



*        public void InitInstance() {*

*-- some stuff*


*AwaitOperator.Main();*

*--some other stuff*
*}*

started the service and the result in the log file was only:

  002 09/12/2022 09:36:51.268  - *DownloadDocsMainPageAsync: About to start
downloading.*
  003 09/12/2022 09:36:51.289  - *Main: Launched downloading.*

It seems that the await operator doesn't "wait" at all.

Making the call elsewhere in the code gives the same result

Il giorno gio 8 dic 2022 alle ore 15:54 Bill Wagner <
***@***.***> ha scritto:

**Comment by BillWagner** [comment]
Thanks for adding that @Gix65 

In this instance, you need to make sure to wait (synchronously) for the Asynchronous work to finish.  Your `InitInstance` method should look like this:

```csharp
public void InitInstance()
{
    // *-- some stuff*
    AwaitOperator.Main().GetAwaiter().GetResult();
    // *--some other stuff*
}
```

You can read more about how this works [here](https://learn.microsoft.com/dotnet/csharp/fundamentals/program-structure/main-command-line#async-main-return-values)
