### ISSUE TITLE
Discussing When to use SPA vs Server-side site - Web crawlers

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/docs#32953]
[Enter feedback here]
This page should mention that SPA applications have severe deficiencies with search engine/web crawler support. Google struggles with React. Bing doesn't even try. If by some miracle your page does get indexed, it will be mired with "dings" for reflowing of content, page load speed, URL/canonicalization issues, and meta tag issues. If you are replacing an old site, SPAs add huge complexity to maintaining old or replaced URLs with redirects. 

Area of interest, I believe, is more a deciding factor for SPAs vs Server Side rendering. (Or a hybrid)

Are you:
Building a highly interactive, realtime, or social media oriented (content mostly provided by users) site? Use an SPA.
You sell a handful of niche products, customers seek you out because what you have is unique? Use an SPA.
Your interaction may just be a few simple forms or a shopping cart/checkout? Use a traditional app.
You sell thousands or millions of items, as a distributor or vendor, and in many cases the sales of those items aren't sold exclusively by you, use a traditional app.
Do you have many, complex data input forms? Use an SPA.
Does your site need a template/header/footer that can be shared across numerous other sites, or take advantage of application composition/virtual directories? Use a traditional or hybrid app.

Another thing to consider, how does the rest of your organization contribute content to the website? Are they skilled developers or talented artists or copy writers with little to no coding experience? SPA applications require more integrative effort across departments with different skill sets than a traditional app would have. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad8df5d-9295-d659-a561-ec9cabd5b61f
* Version Independent ID: 7ee71103-d997-140e-2d35-d9f2a3913e09
* Content: [Choose between traditional web apps and single page apps](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
I'll update this to note the SEO considerations.
