### ISSUE TITLE
example uses v3, but documentation uses v2. Also for examples, show how to list the packages and use that output to show the proper parameters to the delete function

### ISSUE THREAD

**Issue by ketchup201** [dotnet/docs#32964]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a91b44f-cab9-7657-9dd1-b913a8e021d0
* Version Independent ID: 0a6371bc-9f43-0bf9-7ec7-fc5d6331c2c8
* Content: [dotnet nuget delete command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-delete)
* Content Source: [docs/core/tools/dotnet-nuget-delete.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-delete.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 61956](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61956)

**Comment by tdykstra** [comment]
Please clarify what makes you think the documentation is for v2 -- at the top of the article, it states that it covers .NET 3.1 and later. The examples don't state what version they are for, so they should also be for 3.1 and later.
Also how would you list packages for deletion and which parameters do you think need to be included in the examples?

**Comment by ketchup201** [comment]
I'm happy to clarify. The --no-service-endpoint documentation says it will cause "api/v2/package" to not be appended. Yes the documentation for --source references api/v3. Does this flag also prevent "api/v3/package" from being appended?

If the code is going to quietly modify the URL its given, then I think the documentation should be more clear as to what it's inserting (for example, api/v3/package or api/v2/package), how (if possible) to prevent that insertion, and when to specify api/v2 vs api/v3. 

It's possible I'm misunderstanding the difference between api/v2/package and api/v3 (without the /package appended). If this is the case, a "refers to" or "see also" section that points me to the differences would be helpful, since I find the documentation as it is to be confusing.

**Comment by erdembayar** [comment]
@dotnet/nuget-team 
Sorry, more question from my side. In examples they're not passing source option, then does it delete package with given id+version from all sources it can access or only 1st one it finds? `dotnet nuget delete Microsoft.AspNetCore.Mvc 1.0`

**Comment by tdykstra** [comment]
ping @dotnet/nuget-team

**Comment by zivkan** [comment]
@tdykstra I can clarify that the question is about NuGet's HTTP protocol versions, not .NET (Core) versions. More than that, I'm not really sure because I don't remember a single question to the NuGet team about the `delete` command in the 4 years I've been in the team, and I haven't seen a similar question about `push`, which like `delete` talks to NuGet servers over HTTP.

I would hope that `--no-service-endpoint` is not needed when using a NuGet v3 feed, but I'm not sure without testing. Maybe the code makes it obvious, but some parts of NuGet has so many layers of abstraction that even reading the code is hard to determine actual behaviour.

On a side note, my gut feeling is that the examples provided for `--source` are not good, because nuget.org's V3 endpoint is https://api.nuget.org/v3/index.json. I don't think that https://www.nuget.org/api/v3 is a valid endpoint.

Sorry I can't answer all the questions, but I really need to focus on some deliverable work. I'll post a message in our team channel, to see if our person on weekly rotating support can investigate and give an answer.

**Comment by ketchup201** [comment]
Whatever the resolution is, I've learned a great deal from this thread, so **thank you to all the above** for looking into it! 

It sounds as if the documentation needs clarification.. 1) that the --no-service-endpoint performs no automatic appending, and 2) the code does some URL parsing and reassembling to come up with a different URL than what is passed in. 

It would be great if the documentation described what the code does (at a high level of course) to the incoming URL to convert it to the final URL that is used, or at least a few examples of a URL passed in vs the final URL used so we can get a feel for what the transformation is doing.

**Comment by zivkan** [comment]
I wonder if `--no-service-endpoint` is needed for V3 feeds at all. The source URL for V3 feeds (for nuget.org it's https://api.nuget.org/v3/index.json) is called the "service index", and this service index contains links to all the NuGet feed resources, including the publish URL. Customers don't need to know anything about it, it's just automatic between the client and server. If `--no-service-endpoint` is needed for V3 feeds, that's honestly awful UX. NuGet should be capable of seeing by convention it's a V3 feed, just like it does with restore, and avoid attempting V2 protocol conventions.

My guess is that `--no-service-endpoint` was designed for customers using custom NuGet feeds using the V2 protocol version, and their custom server was using a different URL convention to nuget.org's `api/v2/package`. Although, even then the URL customers should use is `https://www.nuget.org/api/v2`, not just `https://www.nuget.org/`

The docs using the example of `api/v3` is just wrong though. https://nuget.org/api/v3 is not, and as far as I know never has been, a valid NuGet endpoint.

**Comment by tdykstra** [comment]
@jeffkl 

> Should I just update the documentation to differentiate between the "source" as just a starting point and then the actual URL used is calculated from that and you should only need `--no-service-endpoint` for custom feed implementations?  

Yes, with the suggestion from @ketchup201 

>It would be great if the documentation described what the code does (at a high level of course) to the incoming URL to convert it to the final URL that is used, or at least a few examples of a URL passed in vs the final URL used so we can get a feel for what the transformation is doing.
