### ISSUE TITLE
possibly make #line fileName example more clear

### ISSUE THREAD

**Issue by twofingerrightclick** [dotnet/docs#32974]
It could be helpful to include the mentioned `partial-class.g.cs` in the example of  the `#line fileName` directive, to make it more clear that the indexes declared before the filename are in reference to the `output` file and not the file where the directive is written, as well as to show how the math works out. It was hard to understand for me where the indexes were coming from / why they were chosen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 716913e5-dbbe-bdb0-909a-4d8c2dc7be97
* Version Independent ID: 501be68d-5ad0-18d9-8958-54215bb57fc0
* Content: [C# preprocessor directives](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives)
* Content Source: [docs/csharp/language-reference/preprocessor-directives.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/preprocessor-directives.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 54553](https://dev.azure.com/msft-skilling/Content/_workitems/edit/54553)

**Comment by BillWagner** [comment]
Thanks @twofingerrightclick 

That's a good point. I'll address this after the holidays.
