### ISSUE TITLE
Why isn't the Half (floating point 16 bit) discussed here?

### ISSUE THREAD

**Issue by AngryKittyMeow** [dotnet/docs#32982]
[Enter feedback here]
Why doesn't this page talk about the new floating point half-type? The new floating point type called Half? It's a new Struct.  There's a new 16-bit floating point since .NET 5, right?  Or is it called a Binary16?  I've read about it being called both.  If this is a part of the .NET language then it should have been talked about in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b24345d9-7aec-14ad-8c3c-56410267849a
* Version Independent ID: f83555d8-9dac-5019-3345-bb0f03e1311d
* Content: [Floating-point numeric types - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types)
* Content Source: [docs/csharp/language-reference/builtin-types/floating-point-numeric-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/floating-point-numeric-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by AngryKittyMeow** [comment]
Thank you for taking the time to give me such a through explanation. I do appreciate it very much.

________________________________________

**Comment by BillWagner** [comment]
Thanks @svick for the description.

@AngryKittyMeow I'll close this as an answered question.
