### ISSUE TITLE
Missing --prerelease option

### ISSUE THREAD

**Issue by chrpeeters** [dotnet/docs#33048]
--prerelease option is not described in this page while you can find it with `dotnet tool update -h`
_--> determining whether to include pre-release packages._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8171f4-8466-98ed-acb8-49563b864d16
* Version Independent ID: a1b7af2d-e2ba-bc4b-4d35-a8edbaa1249f
* Content: [dotnet tool update command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-update)
* Content Source: [docs/core/tools/dotnet-tool-update.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-update.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 55447](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55447)

**Comment by tdykstra** [comment]
@chrpeeters Thanks for reporting that - I'm fixing it.
