### ISSUE TITLE
how to check that installation was successful? missing

### ISSUE THREAD

**Issue by niron1** [dotnet/docs#33047]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 55525](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55525)

**Comment by Viniciusap** [comment]
Hello @niron1!
Taking a look at the third paragraph, I saw the following text
"If you've already installed the SDK or Runtime, use the `dotnet --list-sdks` and `dotnet --list-runtimes` commands to see which versions are installed. "

Maybe `dotnet --info` also should work for the same purpose.

If this helps you, please, close the issue.
Thank you!

**Comment by niron1** [comment]
after the phrase "If you've already installed the SDK or Runtime," the eyes of an efficient reader who *never has installed the SDK nor the Runtime* will skip to next sentence and rightfully so. think of the person who is installing it for the first time, he didn't really care what people who installed it earlier needed to do. he just wants a quick copy/paste to see that it worked *after* having completed their first installation ever

**Comment by adegeo** [comment]
I think this is a valid suggestion. Really the beginning clause could just be removed:

> Use the `dotnet --list-sdks` and `dotnet --list-runtimes` commands to see which versions are installed. For more information, see [How to check that .NET is already installed](https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions).
