### ISSUE TITLE
Invalid link to dotnet test command in dotnet cli page

### ISSUE THREAD

**Issue by samibinsami** [dotnet/docs#33043]
**The document for [.NET CLI .net core 2.1](https://learn.microsoft.com/en-us/dotnet/core/tools/) refers to the list of commands for .net core 2.1. One of them is **test**. When we click on that, we see the documentation for .NET CLI .net core 3.1.

Expected behaviour: When the user click on hyperlink for **test** It should be navigated to **dotnet test** document page for .net core 2.1

Actual behaviour: When the user click on hyperlink for **test** It is navigated to the **dotnet test command** [document page for .net core 3.1](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test)

**

**Target framework**

- [ 2.1] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [.NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/index.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 55446](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55446)

**Comment by gewarren** [comment]
The linking document applies to .NET Core 2.1 *and later* versions, so it's not just for .NET Core 2.1. That said, I don't know why there's an "applies to" difference between the main tools page and the "dotnet test" page.

**Comment by tdykstra** [comment]
When 2.1 went out of support the CLI docs were updated to indicate they cover 3.1 and later, and this overview article was missed.   3.1 and 5 are now out of support, and at some point we will update all of the articles to cover .NET 6 SDK and later. For now I'll update this one to cover 3.1 and later.

**Comment by tdykstra** [comment]
@samibinsami Thanks for pointing out that inconsistency. I'm updating the overview page in PR #33052 to apply to 3.1 and later. The changes on this page only involve the addition of new commands.
