### ISSUE TITLE
Some typo error. Instead of Generic EventHandler; non-generic EventHandler mentioned at 3.a

### ISSUE THREAD

**Issue by siddiq-habib** [dotnet/docs#33057]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/36928138/207855295-99828163-e351-4e32-8b4c-44d781638158.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38e8321f-5516-e451-5429-750d49f0ebed
* Version Independent ID: 1fd093e9-f47c-ffdd-91e9-5039c3ccde61
* Content: [Publish events that conform to .NET Guidelines - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines)
* Content Source: [docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I don't think that's a typo. The code shows the non-generic `EventHandler` delegate, not the generic `EventHandler<TEventArgs>` (which is mentioned in step 3b.).

**Comment by IEvangelist** [comment]
I agree with @svick - closing this as a non-issue.
