### ISSUE TITLE
Remove MSDN Library from Markdown files

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3305]
We should no longer mention MSDN Library in our docs. 

This task is specifically targeted at removing those from the Markdown files:
https://github.com/dotnet/docs/search?l=Markdown&q=%22msdn+library%22&type=&utf8=%E2%9C%93

In most cases, the replacement should be Microsoft Docs, but this could vary depending on the context. Don't hesitate to ask any questions when in doubt.

This is a sub-task of #2037. 

/cc  @ItsPugle

**Comment by ItsPugle** [comment]
Cheers! I'll get cracking!

**Comment by ItsPugle** [comment]
First one and I'm already lost :(
https://github.com/dotnet/docs/blob/master/docs/framework/wcf/generating-data-type-classes-from-xml.md references/links to an MSDN RSS feed, and I can't find the same over at docs.microsoft.com. What should I do?

**Comment by ItsPugle** [comment]
And now [this one's](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/samples.md) confusing me. I can't find the respective docs for the sample queries over at docs.ms

#FixingLinksIsHellaHard

**Comment by mairaw** [comment]
No worries @ItsPugle. For 1st issue, let's replace that with the .NET Blog RSS Feed. The link is this: https://blogs.msdn.microsoft.com/dotnet/feed/. But then the classes that are generated are:
![image](https://user-images.githubusercontent.com/12971179/31112717-3a07c746-a7ca-11e7-9e25-d2c20eea831a.png)

I'll take a look at the second one now

**Comment by mairaw** [comment]
For the second one, let's just fix the text for now which is the focus of this issue.

So replace "Search the MSDN Library for specific issues." with "Search for specific issues on Microsoft Docs." for example.

**Comment by ItsPugle** [comment]
Would you be able to just double-check that I'm doing the right thing over at ItsPugle/docs?

**Comment by mairaw** [comment]
I looked at a few and they look great. I'll review them all once you push the PR. Thank you!
