### ISSUE TITLE
Usage with a private feed lacking any information on how to get this to work

### ISSUE THREAD

**Issue by james1301** [dotnet/docs#33054]
We are using our own private fee hosted on Azure Devops. There is no explanation on here about the credential problems you will have trying to do this. And having spent all morning looking I am still unsure how to get this resolved.

I have the feed installed in Visual Studio so why do I have all of these credential problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98f84e85-28e6-01a2-6b5b-da94774dd28e
* Version Independent ID: d73c54b2-2674-855b-ba75-00d71a268ea9
* Content: [dotnet new install - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install)
* Content Source: [docs/core/tools/dotnet-new-install.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-install.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
I did a quick web search and found this article in the azure devops documentation. Does it help? https://learn.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-setup?view=azure-devops

I spotted this specifically:

![image](https://user-images.githubusercontent.com/67293991/207946322-cab8b52e-711c-4b26-a837-8b3645096046.png)
