### ISSUE TITLE
How do we set type used in GrainStorage Read, Write etc.

### ISSUE THREAD

**Issue by kchalupa72** [dotnet/docs#33066]
In your examples you  have a method such as the ReadStateAsync Method in the FileGrainStorage class. 

` public Task ReadStateAsync<T>(
        string stateName,
        GrainId grainId,
        IGrainState<T> grainState)
    {
        throw new NotImplementedException();
    }`

Where do you set the type or declare it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 494f78b0-7801-5554-643c-bfda075ce7f4
* Version Independent ID: 5f0db119-a02e-55fc-ac0f-a04ad2cfc2a1
* Content: [Custom grain storage sample project](https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/custom-grain-storage)
* Content Source: [docs/orleans/tutorials-and-samples/custom-grain-storage.md](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/custom-grain-storage.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 55599](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55599)

**Comment by IEvangelist** [comment]
Hi @kchalupa72 - I'm not sure I follow the question. Are you asking about the generic-type parameter `T`, or the `FileGrainStorage` class itself?

If you're referring to the latter, see [Grain persistence](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/?pivots=orleans-7-0)
