### ISSUE TITLE
Missing corresponding Null-Conditional Operator document for C#

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#33064]
This page is the first result searching learn.microsoft.com for Null-Conditional Operator, it seems the only thing I can find in our official documentation for C# is the 6.0 release notes here: https://learn.microsoft.com/en-us/archive/msdn-magazine/2014/october/csharp-the-new-and-improved-csharp-6-0#null-conditional-operator

We should have a similar doc like this for the C# side of the docs as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7427bc30-4d66-b234-4537-200d4419cc24
* Version Independent ID: 786cb51a-cd8d-95a7-a11c-c39245a01e9d
* Content: [Null-conditional Operators - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/null-conditional-operators)
* Content Source: [docs/visual-basic/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/operators/null-conditional-operators.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by svick** [comment]
When I [google for "Null-Conditional Operator"](https://www.google.com/search?q=Null-Conditional+Operator), the first result is [*Member access operators and expressions - the dot, indexer, and invocation operators*](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators), which contains a section explaining the C# `?.` and `?[]` operators. Is that not enough?

**Comment by BillWagner** [comment]
This is covered, and recent changes make it more findable. The excerpt shown in the Google results show the `?.` operator.

It is difficult to raise SEO on the operator tokens, and it is something I regularly watch and try to improve.

I'll close this as it's covered.

**Comment by michael-hawker** [comment]
@svick @BillWagner if you use Bing:

![image](https://user-images.githubusercontent.com/24302614/208159622-0d7a4116-f1ed-41b6-9c9d-c34ace6c70a8.png)

It's the fourth result and not obvious that it's an article that I'm looking for, I didn't go into that at all.

Many operators are called out explicitly with symbols in the TOC and even in their corresponding name, like the null-forgiving one here:

![image](https://user-images.githubusercontent.com/24302614/208160103-92738697-a5ac-439d-a674-3c83abb12d17.png)

It'd be helpful for other operators to be split out to have their symbol/name in the TOC to make them easy to find at a glance.

This one doesn't have it and was a pain to find.

Even if you do a direct search on the docs site:

![image](https://user-images.githubusercontent.com/24302614/208160463-7433827b-83f2-4a31-963f-7cbeb3346d47.png)

It's the third result, but unless you read the description underneath the header, you may not realize it's the doc you're looking for, as again most operators/syntax have their own explicit doc pages.

**Comment by BillWagner** [comment]
That's great extra background @michael-hawker 

I'll re-open and add to the backlog for January.

**Comment by svick** [comment]
@BillWagner You haven't actually reopened this.
