### ISSUE TITLE
The page works if doing things manually

### ISSUE THREAD

**Issue by daniellopezgarcia** [dotnet/docs#33072]
Being able to publish from VS UI is great but it works as a 101. This needs to be doable across pipelines and cli/msbuild. If this is not supported, it should be, and if its already supported, this page should provide a link to it.
How to have a solution (.sln) file that contains some projects some of which need deploy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 449b8ce2-80b3-9bfa-6d7f-3e8ac8a86e16
* Version Independent ID: 31264b07-1aeb-b3f0-1126-f25e578f6d50
* Content: [Publish a .NET console application using Visual Studio - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/publishing-with-visual-studio.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion -- I'm adding links in the Additional resources section to our CLI and CLI/CI publish docs.
