### ISSUE TITLE
Comment is wrong in the example

### ISSUE THREAD

**Issue by Soran-M** [dotnet/docs#33077]
[Enter feedback here]
Hello,

The word create in the 2 comments below are incorrect. The delegate has been already created ahead of these two statements. What is done here is they are initialized.

        // Create the delegate object hiDel that references the method Hello.
        hiDel = Hello;

        // Create the delegate object byeDel that references the method Goodbye.
        byeDel = Goodbye;

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68b46f47-d79e-f970-3aa5-5145c243972c
* Version Independent ID: bf824660-4403-8c20-d376-ebf166a995f1
* Content: [How to combine delegates (Multicast Delegates) - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/how-to-combine-delegates-multicast-delegates)
* Content Source: [docs/csharp/programming-guide/delegates/how-to-combine-delegates-multicast-delegates.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/how-to-combine-delegates-multicast-delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
The comments are correct. The *variable* has been defined before, but the *object* is created here and only then is the variable initialized using that object.

Another way to see that is to replace the line with e.g. `hiDel = new CustomDel(Hello);`. This is equivalent to the shorter version, but more clearly shows that a `CustomDel` object is being created.

**Comment by BillWagner** [comment]
Based on the conversation, I've added this to the backlog as an enhancement, and added the "help wanted" label to the issue.

@svick 's suggestion would make the code and the explanation clearer. We'll make that change when we next update this article., or anyone can issue a PR and we'll merge it.

**Comment by BartoszKlonowski** [comment]
@BillWagner I would like to work on this - this is a minor change to made so I'll deliver the PR today.
