### ISSUE TITLE
서명되지않은 봉인된 문서 입니다. 제 문서였습니다 (This is an unsigned, sealed document)

### ISSUE THREAD

**Issue by soon2849** [dotnet/docs#33082]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f34e214-a0fe-1fb6-c17a-1a476adb5e3c
* Version Independent ID: 2a3636a8-7492-a6ea-b610-fe3a2d663d67
* Content: [DeclarationModifiers.IsSealed Property (Microsoft.CodeAnalysis.Editing)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.declarationmodifiers.issealed?view=roslyn-dotnet-4.3.0#microsoft-codeanalysis-editing-declarationmodifiers-issealed)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.Editing/DeclarationModifiers.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.Editing/DeclarationModifiers.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@soon2849 Can you provide more information about the issue with the document?
