### ISSUE TITLE
Typo: TaskFactory.ContinueWhenAll/Task.WhenAny should be TaskFactory.ContinueWhenAll/TaskFactory.ContinueWhenAny

### ISSUE THREAD

**Issue by dimabarbul** [dotnet/docs#33096]
*Original text*: The synchronous Task.Wait, Task.WaitAll, and Task.WaitAny methods accept time-out values, but the corresponding TaskFactory.ContinueWhenAll/Task.WhenAny and the previously mentioned Task.WhenAll/Task.WhenAny methods do not.
*Proposed text*:  The synchronous Task.Wait, Task.WaitAll, and Task.WaitAny methods accept time-out values, but the corresponding TaskFactory.ContinueWhenAll/**TaskFactory.ContinueWhenAny** and the previously mentioned Task.WhenAll/Task.WhenAny methods do not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cabcc3ba-9033-c65f-8969-482a436d510b
* Version Independent ID: a74714e2-d059-e33f-a8c6-591d988ef2a4
* Content: [Consuming the Task-based Asynchronous Pattern](https://learn.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern#taskdelay)
* Content Source: [docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md](https://github.com/dotnet/docs/blob/main/docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by DonaldOkwuone** [comment]
is this issue still open?
