### ISSUE TITLE
Incorrect libgdiplus install instructions

### ISSUE THREAD

**Issue by michaellockwood** [dotnet/docs#33101]
We followed the instructions on this page for working with an alpine image https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies

This worked fine for about a year however it looks like something has changed because now with the most basic dockerfile using these instructions gets a no such package error:

**Dockerfile**
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base

RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
```
**Error**
```bash
 > [3/3] RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/:                                                                                                                         
#6 0.175 fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
#6 0.689 ERROR: unable to select packages:
#6 0.737   libgdiplus (no such package):
#6 0.737     required by: world[libgdiplus]
```

Looking on https://pkgs.alpinelinux.org/packages?name=libgdiplus&branch=edge&repo=&arch=&maintainer= it seems like it has been moved to the `community` repository so changing the repository url now produces this error:

**Dockerfile**
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base

RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/community/
```

**Error**
```bash
 > [3/3] RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/community/:                                                                                                                       
#6 0.180 fetch https://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz                                                                                                                                
#6 0.838 ERROR: unable to select packages:                                                                                                                                                                              
#6 0.896   so:libtiff.so.6 (no such package):
#6 0.896     required by: libgdiplus-6.1-r2[so:libtiff.so.6]
```

I'm guessing this is more of an issue for the package maintainers but I thought it was worth flagging if this page needs updating with the correct repository URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca
* Version Independent ID: f066a748-0a7d-7506-3b18-c422fef13293
* Content: [Install .NET on Alpine - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies)
* Content Source: [docs/core/install/linux-alpine.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by ohuanasis** [comment]
Hey I'm having the same issue please fix the issue since it is blocking us from deploying in circle ci

**Comment by AshleyMedway** [comment]
Here's my workaround that is working

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base

RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
RUN apk add libtiffxx--repository https://dl-3.alpinelinux.org/alpine/edge/main/
RUN apk add tiff-dev--repository https://dl-3.alpinelinux.org/alpine/edge/main/
RUN apk add tiff--repository https://dl-3.alpinelinux.org/alpine/edge/main/
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/community/

**Comment by sstein-maestro** [comment]
I changed our project to pull from this url instead of "edge/testing" and it's building successfully:
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community

**Comment by michaellockwood** [comment]
> * Install .NET on Alpine - .NET

Thanks a lot, this worked for me. So I guess the documentation should be updated to use this URL instead

**Comment by svick** [comment]
I believe the right solution here is not installing `libgdiplus` in the first place. `libgdiplus` wasn't deemed to be of sufficient quality, so [starting with .Net 7, .Net does not use it](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). This should mean that there is no reason to install it anymore.

**Comment by jackalvrus** [comment]
This has started failing again for me when using http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/

My dockerfile contains:
```
RUN apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted
```

And the build reports the following error:
```
[15:27:16][Step 3/3] #9 [runtime  3/11] RUN apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted
[15:27:16][Step 3/3] #0 0.102 fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
[15:27:16][Step 3/3] #0 0.598 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
[15:27:16][Step 3/3] #0 0.906 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
[15:27:16][Step 3/3] #0 1.279 ERROR: unable to select packages:
[15:27:16][Step 3/3] #0 1.362   so:libtiff.so.6 (no such package):
[15:27:16][Step 3/3] #0 1.362     required by: libgdiplus-6.1-r2[so:libtiff.so.6]
[15:27:16][Step 3/3] #9 ERROR: process "/bin/sh -c apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted" did not complete successfully: exit code: 2
```

Any ideas?

**Comment by adrian121s** [comment]
> This has started failing again for me when using http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/
> 
> My dockerfile contains:
> 
> ```
> RUN apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted
> ```
> 
> And the build reports the following error:
> 
> ```
> [15:27:16][Step 3/3] #9 [runtime  3/11] RUN apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted
> [15:27:16][Step 3/3] #0 0.102 fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
> [15:27:16][Step 3/3] #0 0.598 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
> [15:27:16][Step 3/3] #0 0.906 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
> [15:27:16][Step 3/3] #0 1.279 ERROR: unable to select packages:
> [15:27:16][Step 3/3] #0 1.362   so:libtiff.so.6 (no such package):
> [15:27:16][Step 3/3] #0 1.362     required by: libgdiplus-6.1-r2[so:libtiff.so.6]
> [15:27:16][Step 3/3] #9 ERROR: process "/bin/sh -c apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted" did not complete successfully: exit code: 2
> ```
> 
> Any ideas?

Use the specific version for libgdiplus, v3.17 works for me, but v3.18 generates an error

```
RUN apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.17/community/ --allow-untrusted
```

**Comment by mizzPpY** [comment]
I still facing this issue despite libgdiplus is present in the community repository (https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/ ).

I'm building an image on top of **mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.16**, due to my project's huge dependency on System.Drawing.* so unable to switch to higher .NET version; hence I need to stick to .NET 3.1 and Alpine 3.16 is the "latest" I can get.

I also tried add from latest-stable repo but still getting the same output. Any help how to add libgdiplus for Alpine 3.16?

```
 > [base 3/3] RUN apk add --no-cache libgdiplus --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ --allow-untrusted:
#7 0.395 fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
#7 5.399 WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/: temporary error (try again later)
#7 5.399 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#7 10.40 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: temporary error (try again later)
#7 10.40 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#7 15.41 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: temporary error (try again later)
#7 15.41 ERROR: unable to select packages:
#7 15.41   libgdiplus (no such package):
#7 15.41     required by: world[libgdiplus]
```
