### ISSUE TITLE
Grain Placement Documentation

### ISSUE THREAD

**Issue by JCKortlang** [dotnet/docs#33119]
https://github.com/dotnet/docs/blob/main/docs/orleans/grains/grain-placement.md

--

Add a "Choosing a Placement Strategy" section to the above document that helps developers understand and evaluate which placement strategy they should choose.

Questions that came to mind:

1. Why does Orleans default to Random v.s. Activation-count-based placement?
2. Why not default to Activation-count-based placement?
3. Pros / Cons Risk of each strategy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ceea5435-b56c-9d1f-afbb-ec7371b78493
* Version Independent ID: 8769d3fe-dd2e-6096-d927-214d01c7428b
* Content: [Grain placement](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-placement)
* Content Source: [docs/orleans/grains/grain-placement.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/grain-placement.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 62375](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62375)

**Comment by IEvangelist** [comment]
@ReubenBond and @benjaminpetit do either of you have insights on this one?
