### ISSUE TITLE
It would be useful if this ebook was available as an .epub or something that would display properly on other e-readers.  PDFs

### ISSUE THREAD

**Issue by JonBoyerClassic** [dotnet/docs#33115]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

---
[Associated WorkItem - 59172](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59172)

**Comment by erjain** [comment]
Hi @JonBoyerClassic, unfortunately, we won't be able to provide an epub format right now, we have significantly fewer asks to generate a format other than pdf or especially for small screens. In case you want to read on smaller screens or convert to other formats, you can also check out the markdown files here: https://github.com/dotnet/docs/tree/main/docs/architecture. Thank you.

**Comment by erjain** [comment]
The issue can be closed now.
