### ISSUE TITLE
Add 'gnupg' to 'apt-get install' at https://www.microsoft.com/net/core#linuxdebian

### ISSUE THREAD

**Issue by mikeharder** [dotnet/docs#3311]
I recommend adding `gnupg` to the `apt-get install` step at at https://www.microsoft.com/net/core#linuxdebian.  Otherwise, the following command will fail if `gnupg` is not installed:

```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
```

**Comment by mairaw** [comment]
@mikeharder so would I change this `sudo apt-get install curl libunwind8 gettext apt-transport-https`
to
`sudo apt-get install curl libunwind8 gettext apt-transport-https gnupg`?

do you have access to https://github.com/dotnet/dotnet-core-website? That's the repo for the website.

/cc @leecow

**Comment by mikeharder** [comment]
@mairaw: Correct, assuming the instructions should install all required packages (as opposed to letting the user discover and install missing packages).  I do have access to https://github.com/dotnet/dotnet-core-website.  Would you like me to move the issue there?

**Comment by leecow** [comment]
Is the alternative to use wget on debian rather than curl?

**Comment by mairaw** [comment]
I think it's fine to leave this one here @mikeharder. But in the future, if you find issues with the site, it might be better to open issues and PRs there.

@leecow would be the guy to say if the instructions are supposed to install all required packages or not.

**Comment by mikeharder** [comment]
@leecow: The issue is the `gpg` command after `curl`:

```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
```

`/usr/bin/gpg` is part of the `gnupg` package (https://packages.debian.org/stretch/gnupg).  I'm not sure when this package is or is not installed by default in Debian, but I know it's not installed in the Debian docker images (https://hub.docker.com/_/debian/).  So if you try to follow the instructions at https://www.microsoft.com/net/core#linuxdebian in a Debian docker image, it fails because `gpg` is not installed.

**Comment by leecow** [comment]
Ah, understood. The base Debian 9 install does include gnupg so perhaps this is just a general note rather than part of the copy/paste prereq commands.

**Comment by mairaw** [comment]
Issue moved to [dotnet/dotnet-core-website #343](https://github.com/dotnet/dotnet-core-website/issues/343) via [**ZenHub**](https://www.zenhub.com/)
