### ISSUE TITLE
dotnet6-sdk / -runtime / dotnet7-sdk / -runtime not found

### ISSUE THREAD

**Issue by Thought** [dotnet/docs#33110]
Basic install of Alpine from the Windows Store.  1) Sudo isn't installed.  2) none of the dotnet packages are found.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca
* Version Independent ID: f066a748-0a7d-7506-3b18-c422fef13293
* Content: [Install .NET on Alpine - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine)
* Content Source: [docs/core/install/linux-alpine.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Which app are you installing? The only one I found in the Windows Store is unofficial Alpine WSL from which is hosted by https://github.com/agowa338/WSL-DistroLauncher-Alpine
