### ISSUE TITLE
dotnet-pack.md seems to be broken

### ISSUE THREAD

**Issue by avysk** [dotnet/docs#33124]
**Issue description**

`dotnet-pack.md` makes use of `!INCLUDE` which does not seem to be supported:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/130091/208842299-96ff17b5-bd04-4c04-90d1-221f121777fa.png">

Also all three links at the very bottom lead nowhere (GitHub's 404 page).

**Comment by gewarren** [comment]
Thanks - this must have been a temporary glitch as I don't see the issues anymore. Please comment if you are still seeing these issues.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#implicit-restore
