### ISSUE TITLE
Feedback section

### ISSUE THREAD

**Issue by zippy72** [dotnet/docs#33168]
The feedback section lists a GitHub issue that has been closed. It should be removed. The issue showed overwhelming support for rolling back this change, or at least making top-level statements optional, rather than the default, so maybe this should be addressed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6+ - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for your feedback. Top-level statements in the project template were made optional via a [checkbox in Visual Studio](https://learn.microsoft.com/dotnet/core/tutorials/top-level-templates#use-the-old-program-style-in-visual-studio) and an [option in `dotnet new`](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-old-program-style).
