### ISSUE TITLE
Is it possible to push `.snupkg` files with dotnet push?

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#33169]
Would like to see if it's possible to push .snupkg files to a server and use an API key for authentication.  If so, can you provide an example in these docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 61952](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61952)

**Comment by tdykstra** [comment]
@dotnet/nuget-team Can you help with this question?

**Comment by erdembayar** [comment]
> @dotnet/nuget-team Can you help with this question?

Could you please provide which server you're trying to use? Is it nuget.org or Azure Artifacts or 3rd party?
