### ISSUE TITLE
Typo: RegexGenerated 

### ISSUE THREAD

**Issue by ClickRick** [dotnet/docs#33176]
RegexGenerated -> GeneratedRegex
A link to the page describing the GeneratedRegexAttribute would also help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4eedbc9-36be-6c79-fcb4-d5fe6998e5b1
* Version Independent ID: 85bf7eb0-b476-94b6-e10a-d0f42fee407b
* Content: [partial method - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-method)
* Content Source: [docs/csharp/language-reference/keywords/partial-method.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/partial-method.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 58019](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58019)

**Comment by Niravprajapati1** [comment]
I want to work on this issue?

**Comment by IEvangelist** [comment]
Closed by https://github.com/dotnet/docs/pull/33196
