### ISSUE TITLE
Missing information on bitshifting

### ISSUE THREAD

**Issue by iSinner1** [dotnet/docs#33186]
If the bits are bitshifted by a number greater than 32, for example `(int)8 << 33`, it is equivalent to bitshifting once to the left.

When writing `(int)8 << 33`, what really happens is `(int)8 << 33 % 32`

This is not specified anywhere on the page.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa
* Version Independent ID: 2410c828-0c66-9efe-ae87-9b07708aa731
* Content: [Bitwise and shift operators - perform boolean (AND, NOT, OR, XOR) and shift operations on individual bits in integral types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#code-try-1)
* Content Source: [docs/csharp/language-reference/operators/bitwise-and-shift-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
> This is not specified anywhere on the page.

Except in section [Shift count of the shift operators](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators) later down that page.

> `int` or `uint`, the shift count is defined by the low-order five bits of the right-hand operand. That is, the shift count is computed from `count & 0x1F`

And the `& 0x1F <=> & 31` is the bit-hack for `% 32`.

For completeness, for long, ulong it's analogous.

**Comment by iSinner1** [comment]
You are absolutely correct, thanks for pointing this out. 

I will explain how my misunderstanding came to be, and maybe that will help improve the docs.

> Left-shift operator <<
> Right-shift operator >>

From reading these paragraphs i had the impression that this is all there is to it, and there is no disclaimer or a link in a close proximity to the info that's waaay down below.

I would suggest putting a note/disclaimer/link in that paragraph or somewhere in close proximity to the info you pointed out.

**Comment by gfoidl** [comment]
I can't follow. In 
![grafik](https://user-images.githubusercontent.com/5755834/209431801-7d383da6-ec73-41c8-af2c-e7c16a42abd9.png)
there's a link to that section (highlighted in yellow by me). Do you means some different place?

**Comment by iSinner1** [comment]
No, this is perfect, it somehow escaped me. It is phrased so banal that it would have never occurred to me that there are "tricks" to it.

When i read it, i thought, "what is there to read about how the count is defined, its a number okay, and it shifts the thing the number of times you define" and went on reading further. 

There is a phrase, "never underestimate the banality of evil", i guess this will be a lesson to me to never underestimate the banality of phrasing.

Sorry about bothering you, turns out its all my monkey brain at fault.

**Comment by gfoidl** [comment]
Na na, no problem. I got trapped by similar things several times too (reading too fast, can skip that section because I know it...in essence read it thorough to really know it 😉).
