### ISSUE TITLE
Compiled Regex Text Clarification

### ISSUE THREAD

**Issue by wildcatgerry** [dotnet/docs#33181]
Hi,
> These codes are then converted to MSIL. When a method is called, the JIT compiler executes the MSIL

In the above text, it is the JIT compiler that executes the MSIL? I thought it would be the CLR instead.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14698b87-a995-290f-bdd7-9c2d6867704c
* Version Independent ID: f199cd3f-8dce-ad4e-9712-3545e35557e7
* Content: [Best Practices for Regular Expressions in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices)
* Content Source: [docs/standard/base-types/best-practices.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/best-practices.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@wildcatgerry By "executes", I think the author means "converts to machine code".
