### ISSUE TITLE
Needs to be updated to current version of asp net core

### ISSUE THREAD

**Issue by LukasKubicek** [dotnet/docs#33188]
https://learn.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider

The section with configuring services is outdated and doesn't make sense in current asp.net core version. Please make it fit the latest asp.net core project templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 58693](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58693)

**Comment by LukasKubicek** [comment]
Has this been noticed?

**Comment by IEvangelist** [comment]
Hey there, @LukasKubicek - this content isn't specific to ASP.NET Core, instead it is .NET workload agnostic. If you're referring to minimal APIs then the registration code would look similar to this instead:

```csharp
var builder = WebApplication.CreateBuilder(args);

// Configure JSON logging to the console.
builder.Logging.ClearProviders()
    .AddColorConsoleLogger(configuration =>
    {
        // Replace warning value from appsettings.json of "Cyan"
        configuration.LogLevelToColorMap[LogLevel.Warning] = ConsoleColor.DarkCyan;
        // Replace warning value from appsettings.json of "Red"
        configuration.LogLevelToColorMap[LogLevel.Error] = ConsoleColor.DarkRed;
    }));

var app = builder.Build();

app.MapGet("/", () => "Hello custom logging console!");

app.Run();
```

For more information, see [Minimal APIs quick reference: Add logging providers](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#add-logging-providers). I'm going to close this for now. If you have any further questions, we can continue the discussion here. Thanks again for posting this.
