### ISSUE TITLE
Code style in a sample doesn't match the common C# style

### ISSUE THREAD

**Issue by abatishchev** [dotnet/docs#33194]
The article uses a bizarre syntax for attributes:

```csharp
[
    Theory,
    InlineData(-1), InlineData(0), InlineData(1)
]
public void IsPrime_ValuesLessThan2_ReturnFalse(int value) =>
    Assert.False(_primeService.IsPrime(value), $"{value} should not be prime");
```

While the commonly accepted style would be something like this:

```csharp
[Theory]
[InlineData(-1)]
[InlineData(0)]
[InlineData(1)]
public void IsPrime_ValuesLessThan2_ReturnFalse(int value) =>
    Assert.False(_primeService.IsPrime(value), $"{value} should not be prime");
```

of if you really want to combine the two attributes:

```csharp
[Theory, InlineData(-1), InlineData(0), InlineData(1)]
public void IsPrime_ValuesLessThan2_ReturnFalse(int value) =>
    Assert.False(_primeService.IsPrime(value), $"{value} should not be prime");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 588a6d72-f70f-15f8-7505-5db491c8a8c6
* Version Independent ID: ab6ce421-f5e5-94f1-e707-32763b3a6a24
* Content: [Use code coverage for unit testing - .NET](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows)
* Content Source: [docs/core/testing/unit-testing-code-coverage.md](https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-code-coverage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 57755](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57755)

**Comment by IEvangelist** [comment]
It's not bizarre, but perhaps it's something that you're unfamiliar with. There aren't any style guidelines on the preference for attribute usage that I'm aware of. This is a style preference of mine, as it avoids redundant opening `[` and closing `]`, and it makes it easier to read. This is the way I prefer to read these declarations. It's a theory, then the next line shows the three inline data args. When it's all on the same line it's harder to read in my opinion. And when they're all on their own line, it's too verbose. Again, this is preference. I'm going to close this issue as it is too subjective.

**Comment by svick** [comment]
I'm not aware of any style guides either, but I do think it's quite unusual to have the brackets on their own lines. What about changing the code to the following?

```c#
[Theory]
[InlineData(-1), InlineData(0), InlineData(1)]
```

It maintains the separation between `Theory` and `InlineData` and I think it looks more succinct (it has more `[]`, but fewer lines, which makes it somewhat subjective).

**Comment by IEvangelist** [comment]
I guess my concern is it really worth the effort. Is there anything wrong with the way it is now?

**Comment by abatishchev** [comment]
@IEvangelist hi David,

>It's not bizarre, but perhaps it's something that you're unfamiliar with.

As a C#/.NET engineer for more than 20 years I assure you I've seen many different styles of writing in C#.

> Again, this is preference. I'm going to close this issue as it is too subjective.

I agree this is subjective. But here's lies the problem:

> This is a style preference of mine.

Microsoft documentation is not a place for personal preferences. I hope you'll agee that it must use consistent and unified style, as well as easy to read and commonly accepted.

Here's a few excerpts from article [Attributes (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/):

```c#
[Conditional("DEBUG"), Conditional("TEST1")]
void TraceMethod()
{
    // ...
}

[DllImport("user32.dll")]
[DllImport("user32.dll", SetLastError=false, ExactSpelling=false)]
[DllImport("user32.dll", ExactSpelling=false, SetLastError=false)]
```

What makes me think that the proposal by @svick makes total sense and would fit the rest of the documentation/codebase.

```c#
[Theory]
[InlineData(-1), InlineData(0), InlineData(1)]
```

Otherwise, please provide few examples of other articles that use the style of your preference.

**Comment by IEvangelist** [comment]
I do like @svick suggestion better than the other suggestions. Since there isn't any guidance on this, consistency and readability are certainly the priority. The difference between what @svick is suggesting and where it started, is negligible. If you'd like to make the changes, please tag this issue number and me in the comments of your PR. Thank you.

**Comment by abatishchev** [comment]
Thank you, @IEvangelist, appreciate!
