### ISSUE TITLE
Offer MOBI and EPUB files

### ISSUE THREAD

**Issue by dzfweb** [dotnet/docs#3319]
A suggestion is to offer other options in adition to PDF-Only, for example MOBI and EPUB files.

I've make a test with the **.NET Microservices. Architecture for Containerized .NET Applications** ebook writing the correct summary and make it compatible with [gitbook](http://gitbook.com), so now it's possible to download the _mobi_ and _epub_ files to read in kindle or other eReader.

You can see the result i mentioned in:
https://github.com/dzfweb/microsoft-microservices-book

The proccess is very simple, just need to create the _summary.md_ files and import the github repository into gitbook, and let it work.

**Comment by BillWagner** [comment]
Thanks @dzfweb for sharing this and demonstrating the capability.  I'm starting an internal discussion with some other members of our team to get some other opinions.

We'll post back once we get some feedback.

**Comment by mairaw** [comment]
@dzfweb are you requesting that for the whole docs site or just for the ebooks?

/cc @dend @eisenbergeffect

**Comment by mairaw** [comment]
BTW, they've added links to MOBI and EPUB files for the microservices e-book here: https://www.microsoft.com/net/learn/architecture

**Comment by EisenbergEffect** [comment]
We're hoping to re-consider/re-work our entire offline content story for docs.microsoft.com. I'm not sure what the details of that will be yet and when it will happen, but we will be looking at not only PDF, but MOBI and ePub as part of that work. We'll also look into other tech like Gitbooks and Dash. Feel free to share anything you think would be compelling for offline docs experiences.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/220
