### ISSUE TITLE
Missing using on SHA256

### ISSUE THREAD

**Issue by dimabarbul** [dotnet/docs#33197]
Object created by `SHA256.Create()` implements IDisposable, so `using` should be used (in both code snippets):

```diff
         //Create a new instance of the SHA256 class to create
         //the hash value.
-        SHA256 shHash = SHA256.Create();
+        using SHA256 shHash = SHA256.Create();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbc6115f-5205-2a32-6d31-f628a8e4aa3b
* Version Independent ID: 91c61586-f647-5236-e886-fbda771d42e4
* Content: [Ensuring Data Integrity with Hash Codes](https://learn.microsoft.com/en-us/dotnet/standard/security/ensuring-data-integrity-with-hash-codes#generating-a-hash)
* Content Source: [docs/standard/security/ensuring-data-integrity-with-hash-codes.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/ensuring-data-integrity-with-hash-codes.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 57756](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57756)

**Comment by gfoidl** [comment]
Besides that, should the example be updated to use the (new) one-shot-hashes?
