### ISSUE TITLE
Typo: SHA1 should be SHA256

### ISSUE THREAD

**Issue by dimabarbul** [dotnet/docs#33195]
Under section `Generating a Hash` following text: 
*The managed hash classes can hash either an array of bytes or a managed stream object. The following example uses the **SHA1** hash algorithm to create a hash value for a string. The example uses the UnicodeEncoding class to convert the string into an array of bytes that are hashed by using the SHA256 class. The hash value is then displayed to the console.*
should say SHA256 instead of SHA1 (highlighted in bold) as the code snippet below uses SHA256.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbc6115f-5205-2a32-6d31-f628a8e4aa3b
* Version Independent ID: 91c61586-f647-5236-e886-fbda771d42e4
* Content: [Ensuring Data Integrity with Hash Codes](https://learn.microsoft.com/en-us/dotnet/standard/security/ensuring-data-integrity-with-hash-codes#generating-a-hash)
* Content Source: [docs/standard/security/ensuring-data-integrity-with-hash-codes.md](https://github.com/dotnet/docs/blob/main/docs/standard/security/ensuring-data-integrity-with-hash-codes.md)
* Product: **dotnet**
* Technology: **dotnet-security**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 57760](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57760)

**Comment by IEvangelist** [comment]
Fixed by #33254
