### ISSUE TITLE
Wrong code example

### ISSUE THREAD

**Issue by dimabarbul** [dotnet/docs#33203]
The code snippet after text "`Rule #4: If your method accepts a Memory<T> and returns a Task, you must not use the Memory<T> instance after the Task transitions to a terminal state.`" does not conform with the rule as it does not return `Task`. Also defensive copy is not required here, cause adhering to the rule allows us to use `Memory<T>` directly.

The example can be rewritten as follows:

```c#
static Task Log(ReadOnlyMemory<char> message)
{
    // Run in the background so that we don't block the main thread while performing IO.
    return Task.Run(() => {
        StreamWriter sw = File.AppendText(@".\input-numbers.dat");
        sw.WriteLine(message);
        sw.Flush();
    });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://learn.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 62398](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62398)

**Comment by Dbquity** [comment]
This buggy sample code for rule # 4 seems to have lingered since 2019 - see [#14111](https://github.com/dotnet/docs/issues/11411#issue-423298540).
It would really take a super useful piece of documentation from good to great to get this fixed :-)
