### ISSUE TITLE
Very clear explanation of Explicit Interface Implementation

### ISSUE THREAD

**Issue by s52** [dotnet/docs#33214]
This explains things really well. 

Specifically it is short (good), uses short words (good), uses short minimal samples (good), and tells me what Explicit Interface Implementation is in the very first sentence.

It's not easy to write documentation as good as this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Explicit Interface Implementation - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @s52 We appreciate it.

Closing as kudos.
