### ISSUE TITLE
The ""file" and "FILE" illustrates" example is bugged

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#33212]
The code example says equality, but does a starts with, not an equals.
```
 Console.WriteLine("(file == FILE) = {0}",
                       fileUrl.StartsWith("FILE", true, null));
```

Also nobody should be using `==` to compare strings. A large part of this document deals with explaining why string functions should use an overload with `StringComparison`. This example just confuses many of the same people coming to this page for best practices. Most of them dont read the text and just look at the examples, and I'm tired of having to argue with them about this stuff. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dead2df6-1ec5-b55c-89aa-d05a7a75a0eb
* Version Independent ID: fe538551-dcfc-c244-3f16-864d3f6c2a6e
* Content: [Best Practices for Comparing Strings in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings)
* Content Source: [docs/standard/base-types/best-practices-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/best-practices-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 56111](https://dev.azure.com/msft-skilling/Content/_workitems/edit/56111)

**Comment by StingyJack** [comment]
@adegeo - I dont mean to be a nitpick but the text preceding the example I cited now needs to be updated to use "bill" and "BILL" instead of "file" and "FILE"

**Comment by adegeo** [comment]
Ack! No, thank you for pointing that out. I thought I had changed it!
