### ISSUE TITLE
Challenge 

### ISSUE THREAD

**Issue by Jash286** [dotnet/docs#33229]
[Enter feedback here]
This section has a Challenge, so it would be great if the answers of our challenge code is auto verified, presently we need to verify the answers ourselves  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8557d001-9b33-e5d6-5bef-3601d49927fe
* Version Independent ID: 34dcf0cc-d886-cdb3-0a0f-03203eae6d82
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/branches-and-loops)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Jash286 

That's one of the features we're looking at for the future. It's a great suggestion, and it's being tracked internally.

I'll close this as the team implementing those enhancements already has this logged, using an internal board.
