### ISSUE TITLE
Consolidate globalization and localization topics

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#3322]
The Visual Studio docs have a section called Globalizing and Localizing Applications (https://docs.microsoft.com/en-us/visualstudio/ide/globalizing-and-localizing-applications), which is almost all .NET Framework-related stuff, and nothing specific to Visual Studio. It should be merged with .NET Globalization and Localization docs (https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/). The Visual Studio topics should then be removed to reduce duplication.

**Comment by gewarren** [comment]
@rpetrusha Mind if I take this one?

**Comment by rpetrusha** [comment]
Sorry that I didn't respond sooner, @gewarren. Be my guest. I'll try to review your revisions thoroughly early next week, since this is a good opportunity to make the topics more .NET Core-aware, if that's OK with you.

**Comment by BillWagner** [comment]
@gewarren Is there a PR for this issue that didn't get linked? If not, I'll move the milestone from Feb to March.

**Comment by gewarren** [comment]
This was fixed in #10507.
