### ISSUE TITLE
Further improve options explainer

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/docs#33224]
I really don't find the explanations on the different types of options helpful.

What is the difference between `IConfigureNamedOptions` and everything else?  Why in many scenarios do I have to implement both?

It's just not clicking for me.  Is there not some kind of chart or broader explanation that this page can offer to really nail down just what all the different options interfaces are doing and when you'd want to use them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 62378](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62378)

**Comment by IEvangelist** [comment]
Hi @atrauzzi - thank you for posting this issue. I really appreciate it. I'm looking at ways to improve this for you, is the primary concern differentiating between the following?

- `IConfigureOptions`
- `IConfigureNamedOptions`
- `IPostConfigureOptions`

**Comment by atrauzzi** [comment]
There's also `*Cache`, `*Factor`y, `*Initializer`. Maybe more?

Basically there are a lot of interfaces that can sometimes seem redundant. They all need explanations in relation to both the default behaviour as well as one another.
