### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by jeffdod** [dotnet/docs#33221]
It would be helpful to have code samples to demonstrate the concepts discussed on this page. You do reference the eShopOnContainers application, which is available on GitHub. However, the code referenced in this article does not seem to appear in that code repo. For example, I could find no implementation of MauiNavigationService there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62879007-ebc5-479b-5cc4-2e8e58d3f9d5
* Version Independent ID: d2f6ff37-1ab7-cc1b-4db9-f549d7499072
* Content: [Navigation](https://learn.microsoft.com/en-us/dotnet/architecture/maui/navigation)
* Content Source: [docs/architecture/maui/navigation.md](https://github.com/dotnet/docs/blob/main/docs/architecture/maui/navigation.md)
* Product: **dotnet-architecture**
* GitHub Login: @michaelstonis
* Microsoft Alias: **nanil**

---
[Associated WorkItem - 59171](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59171)

**Comment by erjain** [comment]
Hi @jeffdod, thanks for sharing your query. The sample code is placed in the following repo: https://github.com/dotnet-architecture/eshop-mobile-client. Here is the path for MauiNavigationService: https://github.com/dotnet-architecture/eshop-mobile-client/blob/main/eShopOnContainers/Services/Navigation/MauiNavigationService.cs. I hope this helps.

**Comment by jeffdod** [comment]
Thank you!Sent from my iPhoneOn Jan 4, 2023, at 2:37 AM, Tarun Jain ***@***.***> wrote:﻿
Hi @jeffdod, thanks for sharing your query. The sample code is placed in the following repo: https://github.com/dotnet-architecture/eshop-mobile-client. Here is the path for MauiNavigationService: https://github.com/dotnet-architecture/eshop-mobile-client/blob/main/eShopOnContainers/Services/Navigation/MauiNavigationService.cs. I hope this helps.

**Comment by erjain** [comment]
The issue can be closed now.
