### ISSUE TITLE
Contradiction between heading and text

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#33279]
In the section [Use the CLIEvent attribute to expose .NET events](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#use-the-clievent-attribute-to-expose-net-events), the heading seems to say that you _should_ use `CLIEvent`, but the text and code sample says to _not_ do that and instead use `DelegateEvent`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b185b377-3bc4-49fe-fcc2-63500cc9d29e
* Version Independent ID: 5bd70365-b75b-5439-eb86-6a22e4f05684
* Content: [F# component design guidelines](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#use-the-clievent-attribute-to-expose-net-events)
* Content Source: [docs/fsharp/style-guide/component-design-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/style-guide/component-design-guidelines.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by IEvangelist** [comment]
I agree with @agriffard on this, the attribute is used. Closing as a non-issue.
