### ISSUE TITLE
Obsolete so why create this doc?

### ISSUE THREAD

**Issue by rachmann** [dotnet/docs#33284]
This document was dated in 2021... You cannot call CreateDomain as an exception is generated as this is obsolete. Why are you creating this document when we can't even use it? It's obsolete!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32ee8b9a-5eef-5fd4-0a0a-6aa581a63b2b
* Version Independent ID: deff4693-eea8-4699-cbdd-0b0e67863563
* Content: [Application domains - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/app-domains/application-domains#application-domains-and-assemblies)
* Content Source: [docs/framework/app-domains/application-domains.md](https://github.com/dotnet/docs/blob/main/docs/framework/app-domains/application-domains.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by svick** [comment]
1. ApoDomains are obsolete on .Net 5+, but .Net Framework 4.8 is still supported and AppDomains work there. So while you probably shouldn't be writing new code that uses AppDomains, it makes sense that documentation about them still exists. 
2. The date is the date of the last major update, not the date when the article was first written.

**Comment by gewarren** [comment]
@svick is correct. Also, the displayed date of 2021 is the last time a (any) commit was made. The ms.date metadata in the article is actually back in 2017, and that represents the last major update.

**Comment by rachmann** [comment]
Of course. Makes sense.
