### ISSUE TITLE
Incorrect documentation for `OptimizeImplicitlyTriggeredBuild`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#33282]
> To turn off build optimization for implicitly triggered builds, set OptimizeImplicitlyTriggeredBuild to False.

Setting to false doesn't really turn off build optimization.

If `TreatWarningsAsErrors` isn't set to true, then `OptimizeImplicitlyTriggeredBuild` has no effect at all, and build optimization will be on regardless.

@mavasani I'm not sure if this is a Roslyn bug or documentation bug.

Relevant code:

https://github.com/dotnet/roslyn/blob/d71b443067e30dbd935a8cffdacda2ca7ba32e7f/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L92-L99

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by hamarb123** [comment]
I was experiencing this issue with my project. I want it to just run analyzers every time, but I don't want to have to use `TreatWarningsAsErrors` and force every warning to be an error by default. If the current behaviour is intentional, I'd like if we could have a new property that forces analyzers to run every time.

**Comment by Youssef1313** [comment]
@hamarb123 For your case, you can now set `OptimizeImplicitlyTriggeredBuild` to false starting with https://github.com/dotnet/roslyn/pull/66182 (not sure which version this will go)

**Comment by hamarb123** [comment]
Thank you!
