### ISSUE TITLE
CA1852 doesn't make sense for top-level statements

### ISSUE THREAD

**Issue by PClavier70** [dotnet/docs#33297]
### Description

with the addition/recent change to CA1852 it is flagging that the program class needs to be sealed but if we are using Top-Level Statements there is no program class. Thus we have to add a pragma ignore for this new warning.

### Version

.NET 7

### Previous behavior

no warning

### New behavior

warning

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [X] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

no idea

### Recommended action

either fix top level statement hidden classes to be sealed or not based on this rule or fix the rule to recognize top level statements.

### Feature area

C#, Code analysis

**Comment by gewarren** [comment]
@mavasani I think this should be transferred to the roslyn-analyzers repo. It looks like CA1852 is enabled with the "Recommended" rules for .NET 7.

**Comment by mavasani** [comment]
@Youssef1313 I think this was fixed recently, do you recall?

**Comment by mavasani** [comment]
Ah this is fixed with https://github.com/dotnet/roslyn-analyzers/pull/6278

**Comment by gewarren** [comment]
Thanks @mavasani. Can you edit the title of https://github.com/dotnet/roslyn-analyzers/issues/6141 to say CA1852 instead of CS1852 so it comes up in a search?
