### ISSUE TITLE
Ubuntu installation guide not mentioning the need for restart

### ISSUE THREAD

**Issue by do-m-en** [dotnet/docs#33294]
For me upgrading from .Net6 to .Net7 required a restart of the computer due to DOTNET_ROOT pointing to the wrong location but there is no note in the installation guide that would indicate that.

Such a note would have saved me quite some time as I've had to learn more about the workings of .NET runtime.

Running applications printed out: You must install or update .NET to run this application.
No mention where it's trying to find the runtime or a hint that DOTNET_ROOT can be used to specify the location manually.

It'd be nice to have a big note in the installation guide saying:

> If after installation dotnet command works but running an  application fails with: "You must install or update .NET to run this application."
> 
> Try running "dotnet <application_name>.dll" and if that works it's most likely that DOTNET_ROOT is pointing to the wrong location.
> 
> Running dotnet --info will most likely output:
> ...
> Environment variables:
>   DOTNET_ROOT  [<some_path>]
> ...
> 
> where <some_path> doesn't match the version installed or is pointing to a non-existing path.
> 
> This problem can usually be fixed by restarting the OS so that new settings take effect or by setting the variable for current session:
> export DOTNET_ROOT=<path_to_dotnet_runtime_root_dir>
> Where the default dir for .net7 is /usr/share/dotnet

But even "just restart the OS" would be better than nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 59268](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59268)

**Comment by adegeo** [comment]
Hello. I'm curious how you got into the state you did? Regardless of .NET 6 or .NET 7, DOTNET_ROOT should have pointed to the same location for both, so that the app can find both runtimes/sdks.

**Comment by do-m-en** [comment]
I remember having some issues with .net installation on Ubuntu 22.10. (on both of my machines)
  I don't remember the details but I managed to get this history from my server:

   36  sudo apt-get update &&   sudo apt-get install -y dotnet-sdk-6.0
   37  dotnet --version
   38  sudo apt install apt-transport-https 
   39  sudo apt update 
   40  sudo apt install dotnet-sdk-6.0 
   41  sudo apt install apt-transport-https 
   42  sudo apt update 
   43  sudo apt install dotnet-runtime-6.0 
   44  dotnet --version
   45  sudo apt remove dotnet*
   46  sudo apt remove aspnetcore*
   47  sudo rm /etc/apt/sources.list.d/microsoft-prod.list
   48  sudo apt update
   49  sudo apt install dotnet-sdk-6.0
   50  dotnet --version

   66  wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
   67  sudo dpkg -i packages-microsoft-prod.deb 
   68  sudo apt install apt-transport-https 
   69  sudo apt update 
   70  sudo apt install dotnet-sdk-6.0 
   71  sudo apt install apt-transport-https 
   72  sudo apt update 
   73  sudo apt install dotnet-runtime-6.0 
   74  sudo apt update
   75  sudo apt upgrade
   76  sudo apt autoremove
   77  dotnet --version
   78  sudo apt install aspnetcore-runtime-6.0=6.0.8-1 dotnet-apphost-pack-6.0=6.0.8-1 dotnet-host=6.0.8-1 dotnet-hostfxr-6.0=6.0.8-1 dotnet-runtime-6.0=6.0.8-1 dotnet-sdk-6.0=6.0.400-1 dotnet-targeting-pack-6.0=6.0.8-1
   79  dotnet --version

If I remember correctly I was able to run applications (from terminal and inside Rider).

Later a work colleague installed .net7 and kept .net6 on my server:
  754  sudo apt-get update &&   sudo apt-get install -y dotnet-sdk-7.0
  755  dotnet --list-sdks

And dotnet --info returns:
Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet/dotnet6-6.0.110]

So dotnet6 path is not the same as 7 which is located in /usr/share/dotnet which means that instead of running:
./ePoint.Scan.Analytics
I need to run:
DOTNET_ROOT=/usr/share/dotnet ./ePoint.Scan.Analytics

Which is not a real problem if you know about DOTNET_ROOT...

-------
On the other hand on my laptop I first deleted everything related to .net6 and then installed .net7 with the commands from the documentation page and DOTNET_ROOT in my case pointed to /usr/... location but there was nothing there anyway so it acted the same way as on the server.

And yes, on my laptop inside Ubuntu 22.04 and later migrated to 22.10 I've had issues installing .net5 and .net6 via microsoft documentation so it is possible that I've made some workarounds from one website or the other to get it going...
And it is possible that .net6 actually had the same "just restart" issue.

In all cases it boils down to: even if the path is in theory the same, in practice it for some reason wasn't and since DOTNET_ROOT is an environment override that is hard to find (and even harder to remember between updates) it'd be nice to have that documented.

I'll no longer need it as everyone in our team now knows about it... But it wouldn't surprise me if quite a few people who are vaccinated against computer restarts are writing ".netXYZ not working out of the box via Microsoft official installation instructions" because of such a triviality.

**Comment by do-m-en** [comment]
And yes... I admit that I'm a brat, spoiled by C++ and CMake so it rubs me the wrong way if a language is harder to use/works less out of the box then what I can do with those two.

So if you believe that this is not an issue and is something that anyone else using C# for more than 2 years should know about anyway you can just close this issue and don't mind me.

Thx

**Comment by adegeo** [comment]
I think you're running into the package mixup. You installed dotnet from both the Ubuntu package feed then later added the Microsoft package feed and installed it from there. That ends up with it being installed in two different locations, the `share` and the `lib` folder.

This article should explain that: https://learn.microsoft.com/dotnet/core/install/linux-package-mixup

**Comment by do-m-en** [comment]
Of the mixup I have no doubt... But the linked article states that

> When you try to use .NET on Linux, commands such as dotnet new and dotnet run may fail with a message related to a file not being found, such as fxr, libhostfxr.so, or FrameworkList.xml. 

Which didn't happen in my case (not even before .net7 installation...).

And even if it did, this article doesn't tell you to restart your computer in any of the "remove old packages, add microsoft repo, install new packages" bullets...
So I'd come up empty handed even if I found that article.

So it all once again boils down to: either you know .net runtime environment well enough to know about DOTNET_ROOT or you'll have to learn N things about it.

I'd prefer to have that hint inside the baked-in executable message but installation guide is the second best place.

But as said... Now I know so I no longer need it and since I don't mind C# having bad rep and there is no interest, I'll close this ticket.

**Comment by adegeo** [comment]
I'm reopening this because I think there is some value in detailing something about this. However, I don't think that "restart your computer" is the actual solution, it's refreshing your environment is, but like you said, `DOTNET_ROOT` is a key environment variable, so it should be talked about in the installation articles. I also think updating the troubleshooting article with some of the information you provided is valuable too.
