### ISSUE TITLE
Discard pattern note needs explanation

### ISSUE THREAD

**Issue by e2ibrobbins** [dotnet/docs#33298]
The following statement, found under the **Discard pattern** section either needs to be removed or needs to be explained since examples within the page clearly show the use of discards in `is` and `switch` statements without the use of `var`.

"A discard pattern can't be a pattern in an is expression or a switch statement. In those cases, to match any expression, use a [var pattern] with a discard: var _." (link omitted)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - Pattern matching using the is and switch expressions.](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 123094](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123094)

**Comment by BillWagner** [comment]
Thanks for mentioning this @e2ibrobbins 

I've added it to our backlog to address when we next update this content.

**Comment by BillWagner** [comment]
Doing in this sprint because I'm editing the same file for another issue.

**Comment by BillWagner** [comment]
The statement is correct, if misleading. The discard pattern can be used in a `switch` expression, but not a `switch` statement or an `is` pattern statement.
