### ISSUE TITLE
must declare the scale variable

### ISSUE THREAD

**Issue by masucci08** [dotnet/docs#33306]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0370ad-6492-44cd-d0f6-988be922a5c0
* Version Independent ID: 95f05873-f236-19fb-e01f-0b7b23623654
* Content: [Compiler Error CS1501](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1501?f1url=%3FappId%3Droslyn%26k%3Dk(CS1501))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1501.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1501.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @masucci08 

This looks like you've added notes for your own use in this issue. If there's an issue in this content that needs to be addressed, can you add a further comment?
