### ISSUE TITLE
Unable to get ConfigurePrimaryHttpMessageHandler working in .net 6

### ISSUE THREAD

**Issue by codebuzz** [dotnet/docs#33309]
I have added a typed `HttpClient` through services and configured a handler like the following code on docs:

```c#
services.AddHttpClient("Named.Client")
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        return new HttpClientHandler
        {
            AllowAutoRedirect = false,
            UseDefaultCredentials = true
        };
    });
```

However, the `HttpClient` injected into the class doesn't have these properties and isn't working properly. This is evident in the screen below:

![image](https://user-images.githubusercontent.com/96615337/210535225-94f5cc56-4fa5-4a5e-a5e6-07100e20c9d4.png)

Here `AllowAutoRedirect` is `true` which we seemingly set to `false` and the `HttpClient` isn't behaving as expected. Please check and let me know if I am missing something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46af0b96-2d12-9cac-2f8f-15eb49d0292d
* Version Independent ID: 33db41be-42f9-bb94-65fe-0cf7d1c64f12
* Content: [Use the IHttpClientFactory - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
* Content Source: [docs/core/extensions/httpclient-factory.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/httpclient-factory.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 57998](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57998)

**Comment by IEvangelist** [comment]
Hi @codebuzz - I just tried this and I'm not able to recreate the issue that you're seeing. Are you able to share your exact code, so that I might help debug it with you? As of now, I'm fairly confident that this is perhaps a user error as I'm seeing the correct properties in the handler when debugging it locally.

Here is my code for a project I just put together:

_configurehandler.csproj_:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ConfigureHttpHandler.Example</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
  </ItemGroup>
  
</Project>
```

_Todo.cs_:

```csharp
namespace Shared;

public record class Todo(
    int UserId,
    int Id,
    string Title,
    bool Completed);
```

_Program.cs_:

```csharp
using Shared;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ConfigureHttpHandler.Example;

using IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices((context, services) =>
    {
        const string name = "ConfigureHttpHandler.Example";
        services.AddHttpClient(
            name,
            client =>
            {
                // Set the base address of the named client.
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");

                // Add a user-agent default request header.
                client.DefaultRequestHeaders.UserAgent.ParseAdd("dotnet-docs");
            })
        .ConfigurePrimaryHttpMessageHandler(() =>
            {
                return new HttpClientHandler
                {
                    AllowAutoRedirect = false,
                    UseDefaultCredentials = true
                };
            });
        services.AddTransient<TodoService>();
    })
    .Build();

TodoService todoService =
    host.Services.GetRequiredService<TodoService>();

Todo[] todos = await todoService.GetUserTodosAsync(3);

ILogger logger =
    host.Services.GetRequiredService<ILogger<TodoService>>();

foreach (Todo? todo in todos)
{
    logger.LogInformation("Todo: {Details}", $"""
        Id: {todo?.Id} (Is completed: {todo?.Completed})
        Title: {todo?.Title}
        """);
}

await host.RunAsync();
```

_TodoService.cs_:

```csharp
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Shared;

namespace ConfigureHttpHandler.Example;

public sealed class TodoService
{
    private readonly IHttpClientFactory _httpClientFactory = null!;
    private readonly IConfiguration _configuration = null!;
    private readonly ILogger<TodoService> _logger = null!;

    public TodoService(
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration,
        ILogger<TodoService> logger) =>
        (_httpClientFactory, _configuration, _logger) =
            (httpClientFactory, configuration, logger);

    public async Task<Todo[]> GetUserTodosAsync(int userId)
    {
        // Create the client
        const string name = "ConfigureHttpHandler.Example";
        using HttpClient client = _httpClientFactory.CreateClient(name);

        try
        {
            // Make HTTP GET request
            // Parse JSON response deserialize into Todo type
            Todo[]? todos = await client.GetFromJsonAsync<Todo[]>(
                $"todos?userId={userId}",
                new JsonSerializerOptions(JsonSerializerDefaults.Web));

            return todos ?? Array.Empty<Todo>();
        }
        catch (Exception ex)
        {
            _logger.LogError("Error getting something fun to say: {Error}", ex);
        }

        return Array.Empty<Todo>();
    }
}
```

When debugging this, my break point in the `GetUserTodosAsync` looks like this:

![image](https://user-images.githubusercontent.com/7679720/210582359-7abd99f6-dc26-48b2-abce-7acdf42dfc42.png)

**Comment by codebuzz** [comment]
Thanks for looking into this @IEvangelist. I am unable to post code due to company policies, however i have figured out the issue. 

I was using the typed client like 

    services.AddHttpClient<MyService>().ConfigurePrimaryHttpMessageHandler....

It was fixed when i used 

    services.AddHttpClient<IMyService, MyService>().ConfigurePrimaryHttpMessageHandler.... 
and removed the separate registration of MyService. 

The takeaway here is that Http Client still gets injected but the configure handler method is never called if we register only the implementation.

**Comment by Ignignokt** [comment]
Thank you @codebuzz!  Using the generic method which specifies the interface in addition to the implementation fixed my problem.  Were you able to find a reason why this worked?  It feels like a bug to me.
