### ISSUE TITLE
Please add examples for setting verbosity on the CLI for dotnet build commands

### ISSUE THREAD

**Issue by TangoDeltaDelta** [dotnet/docs#33302]
Can there be examples for the verbosity (-v) option, please?  I've tried setting it to "q" and "quiet" and even "0" and it still spits out all of the build warnings, when I'd really like it to only output the errors (if there are any).

(We review and correct as many warnings as we can when we do updates and local builds so we see them and clean them up, but we use the CLI "dotnet build" for executing the tests and the whole log ends up getting stored, and keeping all the build warnings there just takes up significant extra space and makes reviewing the logs there more painful.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 57938](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57938)

**Comment by tdykstra** [comment]
Msbuild prints out warnings and errors at all verbosity levels. One thing you could try is running `dotnet build` twice, throwing away the output from the first run. If you only had warnings, the second run won't have to compile and so won't generate warnings. If there are errors the second run will recompile and you'll get all the warnings and errors.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by TangoDeltaDelta** [comment]
Actually, I did find a way to do it from Node without running the build twice (which probably would have cost some extra time) -- 

ex.execSync(`dotnet build "${testProjectPath}" -v q \/property :WarningLevel=0 -c ${configFile}`, { stdio: "inherit", timeout: 90000});

**Comment by tdykstra** [comment]
Thanks for reporting that - I'm adding a note about use of the WarningLevel property to the article.
