### ISSUE TITLE
ContainerImageName indeed allows the forward slash character too

### ISSUE THREAD

**Issue by lbruun** [dotnet/docs#33315]
The value for `<ContainerImageName>` seems to accept forward slashes in the name. Which it should. 

However, the doc says:

"Image names can only contain lowercase alphanumeric characters, periods, underscores, and dashes, and must start with a letter or number. Any other characters will result in an error being thrown."

(in the section about _ContainerImageName_)

The following works for me:

```xml
<ContainerImageName>foo/bar</ContainerImageName>
```

but according to the documentation should not be possible. I think the documentation is incorrect. From a Docker perspective it is correct that the `/` character is allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19c28091-b3ad-affb-6343-47d7fa066d55
* Version Independent ID: 401bc84b-9410-3583-91f6-88968654b588
* Content: [Containerize an app with dotnet publish - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container#containerimagetags)
* Content Source: [docs/core/docker/publish-as-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 58006](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58006)

**Comment by IEvangelist** [comment]
Let's verify this one with @baronfel to ensure that you're correct, if so I'll make the appropriate updates to the content. Thanks

**Comment by baronfel** [comment]
That's correct (and I opened https://github.com/dotnet/sdk-container-builds/pull/275 to fix similar errors on the in-repo docs). The caveat about allowed characters should refer to each _segment_ of an image name, and each of those segments can be joined by a `/` character.  Good catch, @lbruun!
