### ISSUE TITLE
Console DI Example does too many things

### ISSUE THREAD

**Issue by s52** [dotnet/docs#33313]
(Unconnected feedback - a general problem here is that clicking feedback goes to this page on the same tab, so you can no longer see the page you are sending feedback on. It would be better to open a new tab.)

This example appears to be doing too many things :-

- It shows how to use DI in a console application
- It explains Singleton, Scoped and Transient
- It does other things I don't understand

In addition :-

- It uses I think a substring of a GUID. Better to think of something better ?
- It uses DefaultImplemenation.cs to add OperationId and MUCH better to add to the interface files individually
- OperationLogger.cs would be MUCH better if it did not try to do everything

Whoever wrote this is clearly very competent, but good documentation, and I can remember the early days of Microsoft when documentation was truly terrible, means editing out all the clever stuff, and leaving something so simple that anyone could understand it, like me.

Remember, users looking at documentation will NOT understand the subject they are looking up. That is why they are looking it up. Make it as easy as possible for them to understand the subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 58190](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58190)

**Comment by 1944GPW** [comment]
I agree this example page is WAY too complicated and if some aspiring C# dev decided to ditch C# for Python afterwards, call me surprised.
