### ISSUE TITLE
Init-only example issues

### ISSUE THREAD

**Issue by e2ibrobbins** [dotnet/docs#33314]
The final example under **Init-only** implies that an error will be produced, but both lines shown are valid.  Either revise the example or revise the statement immediately above it.  Also recommend removing the VersionNinePoint2 namespace from that example since the namespace is not defined within the page and only confuses the example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e614217-286d-2231-f0c7-d37e5a31b2d5
* Version Independent ID: 070d932f-bc38-a766-37cc-ec861e74be1c
* Content: [Properties in C#](https://learn.microsoft.com/en-us/dotnet/csharp/properties#init-only)
* Content Source: [docs/csharp/properties.md](https://github.com/dotnet/docs/blob/main/docs/csharp/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @e2ibrobbins 

I can see where that sample is misleading. The note about the compiler error pertains to the following line of code that's commented out. We'll get that updated.

**Comment by BillWagner** [comment]
This was fixed in a previous PR.
