### ISSUE TITLE
Typo: "SetRequiredMembersAttribute" should be "SetsRequiredMembersAttribute"

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/docs#33335]
On https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members#setsrequiredmembersattribute

Where it is written:
SetsRequiredMembersAttribute
All constructors in a type with required members, or whose base type specifies required members, must have those members set by a consumer when that constructor is called. In order to exempt constructors from this requirement, a constructor can be attributed with **SetRequiredMembersAttribute**, which removes these requirements. The constructor body is not validated to ensure that it definitely sets the required members of the type.

Should be:
SetsRequiredMembersAttribute
All constructors in a type with required members, or whose base type specifies required members, must have those members set by a consumer when that constructor is called. In order to exempt constructors from this requirement, a constructor can be attributed with **SetsRequiredMembersAttribute**, which removes these requirements. The constructor body is not validated to ensure that it definitely sets the required members of the type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 491550b6-23f8-a48a-c6e5-f177151030ff
* Version Independent ID: 4037b376-e4f6-73cc-3dd1-abea0fc7db5b
* Content: [Required members - C# 11.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members)
* Content Source: [proposals/csharp-11.0/required-members.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/required-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by agriffard** [comment]
Fixed in https://github.com/dotnet/csharplang/commit/00993c98cecc3e431458a1a17f346db0cebb673f

**Comment by IEvangelist** [comment]
Perfect, thank you @agriffard - closing as already addressed.
