### ISSUE TITLE
Adding dotnet to PATH

### ISSUE THREAD

**Issue by jgedri** [dotnet/docs#33338]
I downloaded the zip file of dotnet 6 and want to know which folder(s) to add to the PATH. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry for the delay, this issue slipped through the cracks. You would add the folder you extracted the contents of the zip file to the path.
