### ISSUE TITLE
Missing capture group in table

### ISSUE THREAD

**Issue by joezearing** [dotnet/docs#33333]
I think that the table showing the capture groups in the named matched subexpressions section is incorrect.  https://learn.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions#named-matched-subexpressions

The table is missing the default named group Two which should be at Number 2.  

In the document:

Number | Name | Pattern
0 | 0 (default name) | ((?\<One\>abc)\d+)?(?\<Two\>xyz)(.\*)
1 | 1 (default name) | ((?\<One\>abc)\d+)
2 | 2 (default name) | (.\*)
3 | One | (?\<One\>abc)
4 | Two | (?\<Two\>xyz)

Should be:

Number | Name | Pattern
0 | 0 (default name) | ((?\<One\>abc)\d+)?(?\<Two\>xyz)(.\*)
1 | 1 (default name) | ((?\<One\>abc)\d+)
2 | 2 (default name) | (?\<Two\>xyz)
3 | 3 (default name) | (.\*)
4 | One | (?\<One\>abc)
5 | Two | (?\<Two\>xyz)

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d124987-d837-b655-261e-e0871effcb7d
* Version Independent ID: 492a3233-0049-0678-1a4e-aed850e14bf4
* Content: [Grouping Constructs in Regular Expressions](https://learn.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions)
* Content Source: [docs/standard/base-types/grouping-constructs-in-regular-expressions.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/grouping-constructs-in-regular-expressions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 82745](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82745)

**Comment by gewarren** [comment]
The example is actually correct as-is for .NET, because named groups come last. Online engines like regex101 do have a different ordering.

**Comment by joezearing** [comment]
I don't think the ordering was off, it was physically missing an entry for named group "Two".  Its possible that I don't understand how this works though.

**Comment by joezearing** [comment]
Nope, never mind.  This was my misunderstanding.  Thanks!
