### ISSUE TITLE
"Non-public property accessors" shows public properties in example?

### ISSUE THREAD

**Issue by tmjones212** [dotnet/docs#33330]
I can't get System.Text.Json to deserialize private properties, and the example here shows public properties... what am I missing?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f52750-1f3a-3cba-9790-bf36a5ae30a5
* Version Independent ID: cf9fe1d5-1079-025c-73cb-668cc9cbd520
* Content: [How to use immutable types and non-public accessors with System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/immutability?pivots=dotnet-6-0)
* Content Source: [docs/standard/serialization/system-text-json/immutability.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/immutability.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Private properties aren't supported - only non-public *accessors* (which are shown in the example). See https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-7.0#remarks.
