### ISSUE TITLE
The two last code sample are the same but the last one should be the fix

### ISSUE THREAD

**Issue by Fangh** [dotnet/docs#33334]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc727a99-200d-d34b-a2db-72f336f6f326
* Version Independent ID: fa87a308-62df-2b4c-1685-2ff9372b5c46
* Content: [Compiler Error CS0433](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0433?f1url=%3FappId%3Droslyn%26k%3Dk(CS0433))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0433.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0433.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Fangh 

The code is the same in both samples, but the switches are different.  

I'll keep this open in our backlog for our next update for this article.

**Comment by Youssef1313** [comment]
@BillWagner fwiw, I don't think it's common that someone compiles directly using csc, so the fix should probably be shown in another way (I guess that is `Aliases` attribute either on `PackageReference` or `ProjectReference`?)

**Comment by BartoszKlonowski** [comment]
I will handle that sometime this week. @BillWagner @Youssef1313 Please assign me so that I have it.
