### ISSUE TITLE
Ensure all TOCs are linked from hub page

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#33343]
TOCs shouldn't be orphaned - they should either be linked from the hub page or the L2 header.

Related to #33349.

---
[Associated WorkItem - 58288](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58288)

**Comment by BillWagner** [comment]
In general, I agree. 

I am concerned about [the TOC for compiler warnings and errors](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/). That's super long, which I'm slowly addressing. But, it's current format makes it unwieldy to include in the main C# TOC. 

What would be the plan for integrating these?

**Comment by gewarren** [comment]
> In general, I agree.
> 
> I am concerned about [the TOC for compiler warnings and errors](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/). That's super long, which I'm slowly addressing. But, it's current format makes it unwieldy to include in the main C# TOC.
> 
> What would be the plan for integrating these?

Can we link to it from the hub page?

**Comment by gewarren** [comment]
This has been fixed.
