### ISSUE TITLE
Update How to Convert String to Number

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3335]
Topic: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/how-to-determine-whether-a-string-represents-a-numeric-value

- [ ] Use nullable, or tuple output
- [ ] use out var
- [ ] link from Hello World and working with number quick starts
- [ ] redirection

**Comment by mairaw** [comment]
Related topic: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/how-to-convert-a-string-to-a-number

**Comment by lucasnobredev** [comment]
Hello @mairaw @BillWagner !

Can you explain better the last two options of the list?

**Comment by BillWagner** [comment]
for the 2nd to last item: 
- Add links from [this page](https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7)
- from [this page](https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp?tutorial-step=7)
- from [this page](https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local)
to this How To page.

For the last item, move this topic into the `docs/csharp/how-to` folder and provide a redirection record in `docfx.json` from its current location to the new location.
