### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by DavidKlempfner** [dotnet/docs#33389]
"In .NET Framework, use [IHttpClientFactory](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory) to manage your HttpClient instances."

I clicked on that link and selected .NET Framework 4.8.1 in the dropdown on the left, and it said "The requested page is not available for .NET Framework 4.8.1. You have been redirected to the newest product version this page is available for."

It looks like it's only available in .NET Platform Extensions 7.

I can't find any information on the internet about how to download .NET Platform Extensions 7 or how to access IHttpClientFactory in .NET framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a42e9c6-2624-e047-ed1c-03ec047b538a
* Version Independent ID: 3b1dd30f-82a8-2526-bd51-fb6401c52e81
* Content: [HttpClient guidelines for .NET - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/http/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/http/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
You need to reference the [Microsoft.Extensions.Http package](https://www.nuget.org/packages/Microsoft.Extensions.Http).

I understand that the Applies to information for IHttpClientFactory is confusing since it doesn't mention .NET Framework. I've logged #8405 to improve that.
