### ISSUE TITLE
Backtracking with nested optional quantifiers - code/description discrepancy

### ISSUE THREAD

**Issue by rocketOC** [dotnet/docs#33390]
This statement in "Backtracking with nested optional quantifiers" seems to contradict the times reported by the example. 

Quote:
> As the output from the example shows, the regular expression engine took significantly longer to find that an input string did not match the pattern as it did to identify a matching string.

Timed Code:

> //    Matched aaaaaa in 00:00:00.0007086
//    No match found in 00:00:00.0000829

I can see a significant and reproducible difference for longer strings, but not for "aaaaaa" and "aaaaa!".

https://learn.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#backtracking-with-nested-optional-quantifiers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce579cf-f3af-6050-895b-d00ae083c26b
* Version Independent ID: 89943c6e-1d5e-737d-cac8-ef87e8d42cf6
* Content: [Backtracking in .NET Regular Expressions](https://learn.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions)
* Content Source: [docs/standard/base-types/backtracking-in-regular-expressions.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/backtracking-in-regular-expressions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 143920](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143920)

**Comment by gewarren** [comment]
@rocketOC Thanks for pointing this out! Do you want to update the example?

**Comment by danmoseley** [comment]
@rocketOC ?
