### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by DavidKlempfner** [dotnet/docs#33391]
The title of this article does not clearly explain which .NET version this is for.
Is it for .NET Framework, .NET Core, or .NET 5 and above?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46af0b96-2d12-9cac-2f8f-15eb49d0292d
* Version Independent ID: 33db41be-42f9-bb94-65fe-0cf7d1c64f12
* Content: [Use the IHttpClientFactory - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
* Content Source: [docs/core/extensions/httpclient-factory.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/httpclient-factory.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @DavidKlempfner,

Thanks for posting this issue. The `IHttpClientFactory` type was introduced in .NET Core 2.1, and the two introduction paragraphs mention that, but you're correct that it's not necessarily obvious from the title.

With that info, what would you recommend for the title if we were to change it?

**Comment by DavidKlempfner** [comment]
Hi @IEvangelist, maybe something like:
_IHttpClientFactory with .NET Core 2.1+_

**Comment by IEvangelist** [comment]
After discussing this with the team, we're going to leave this as is. The opening paragraphs communicate the version it was introduced and the title says ".NET" which now is used to convey ".NET Core" and ".NET 5+". Thank you for this feedback though, I'm going to close this one for now. But if we get enough feedback like this, we'll revisit it then. Thank you.
