### ISSUE TITLE
Restore explanation and details to C# version history page

### ISSUE THREAD

**Issue by Trisped** [dotnet/docs#33401]
### Type of issue

Other (describe below)

### Description

Can we switch [this ](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history) back to having explanations of what changed in each version?  The links to the current documentation is helpful, but not everyone can upgrade to the latest version as quickly as it comes out.  Being able to look up and see an explanation of what was added makes it easier to learn the new features without also picking up the features which are not supported in the version you are using.

For example, if you are using C# 8, you don't want to accidently pick up features in C#10.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history

### Content source URL

https://github.com/dotnet/docs/blob/live/docs/csharp/whats-new/csharp-version-history.md

### Document Version Independent Id

575872e5-6273-f8f6-e3e2-2b911cd9d009

### Article author

@wiwagn

### Metadata

* 3d252158-0367-77c8-1816-dbc385c5c40b
* Service: **dotnet-csharp**
* Sub-service: **whats-new**

---
[Associated WorkItem - 355903](https://dev.azure.com/msft-skilling/Content/_workitems/edit/355903)

**Comment by BillWagner** [comment]
Hi @Trisped 

Can you help me understand what's missing? I made sure that the bullet lists for each version list the new features. What additional information was there that's missing now?

**Comment by Trisped** [comment]
Hi @BillWagner 

Sorry, looks like the link I wanted was https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8 which has been redirected to https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-80 .
The now gone page can be seen at https://web.archive.org/web/20220918222100/https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8 .

Can we get this page (and any older pages which have been taken down) restored?  I found the 8.0 page very helpful for understanding the new features found in C# 8.

Sorry again about the first link being incorrect.  I had not noticed that the page had been redirected, so I thought the information had been removed.

**Comment by BillWagner** [comment]
Thanks @Trisped 

That helps. I don't want to keep pages for each historical version indefinitely. That clutters the experience for readers. 

That said, I do want to make sure you can quickly find what features were added in which version. Can you suggest changes to this page (where we do list the entire history) that would help that?

**Comment by Trisped** [comment]
@BillWagner

Hmm, I don't know that putting all the details of how each new feature works into the history page will make sense.  I guess it could be done by adding it to the bottom of the page, but that would make the page rather large.

Is it possible to put the historical version pages in a folder inside the Whats new in C# folder?  Maybe after the C# 9.0 page?
![image](https://user-images.githubusercontent.com/20877262/212171547-e198bcb4-e690-4871-9647-4b82207dfab7.png)

**Comment by BillWagner** [comment]
Thanks @Trisped 

That moves toward having that one file with the historical information about every version. 

Here's the way I'm thinking about it now:

- Once a version is more than 3 years old, it's not really "new". Similarly, the older the version, the fewer developers are still using that version. 
- It's still important to help developers find what features are and aren't supported on the version they're using. More developers are 1 or 2 versions behind; fewer developers are 3 and 4 versions behind. Fewer still are more than 5 versions behind.
- To help developers that are on older versions, it's sufficient to list the features with a brief description. Complete information on what a feature doesn't isn't useful if you can't use it.

Based on that logic, I'd like to add any additional needed information on the current history page. I think that will provide a better experience for everyone.

What details do you find missing?

**Comment by Trisped** [comment]
@BillWagner

I agree that what the feature does is not useful if you can't use it, but the referenced pages list the features without calling out which version it was added in.  As a result, if I am using C# 6 and I want to use an interpolated verbatim string, I don't know that this was introduced in a later version from just the one line link in the history page or from the linked page:

> An interpolated verbatim string starts with the $ character followed by the @ character. You can use the $ and @ tokens in any order: both $@"..." and @$"..." are valid interpolated verbatim [string](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types)s. For more information about verbatim strings, see the string and [verbatim identifier](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim) articles.

Note: I think the first two sentences in the quote contradict.  Is $ always first, or can @ be first?

I agree, a brief description of what the feature is should be enough, and having the older C# limitations in the linked page would make it harder to read.  Most of the brief descriptions are not detailed enough to make it clear what the feature is that I cannot use (or can now use if I am upgrading versions).

I don't have a good solution to the issue.  We could make the new features on the history page collapsible, so you would only see it if you expanded the section for the feature you want to learn about, but it would not take up space on the page by default.  You could also move the old What's new pages to a blog, so they can be linked to.  I think as long as the search engines can find it, it should be ok.

**Comment by BillWagner** [comment]
Thanks again @Trisped 

I'm going to leave this in the backlog for now. I'm not sure the best way to address this either.

**Comment by BillWagner** [comment]
The best answer for this is to link to the Roslyn history page. That gives a feature-by-feature detail for each version of C#.
