### ISSUE TITLE
Update guidance to include ValidateDataAnnotations

### ISSUE THREAD

**Issue by MarkAtAgilliance** [dotnet/docs#33419]
[Enter feedback here]
One of the sections [in](https://learn.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#iconfiguration-parameter) recommend not using the AddOptions method.  We use AddOptions to automatically validate settings with data annotations i.e.

                       .AddOptions<LibraryOptions>()
                            .BindConfiguration("LibraryOptions")
                            .Configure(c =>
                            {
                               //override some values here if desired
                            })
                            .ValidateDataAnnotations()
                            .ValidateOnStart();

This causes startup errors for misconfigured settings which is exactly what we want.  Appreciate this is one-time snapshot of that instance.  Going with the recomendation bypasses validation at the earliest moment and we'd have to validate within every consuming DI of those settings - potentially leading to delayed recognition of those issues.

Can the guidance be updated to account for library writers that want to use ValidateDataAnnotations?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03494bb6-433a-5385-b664-7b830c37f9ce
* Version Independent ID: d0e9398d-50c6-01b8-a242-4edc8b27df31
* Content: [Options pattern guidance for .NET library authors - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#iconfiguration-parameter)
* Content Source: [docs/core/extensions/options-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 59283](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59283)

**Comment by IEvangelist** [comment]
Hi @MarkAtAgilliance,

Thank you for posting this issue, I'm adding some clarifying content and examples to this guide based on your feedback. One thing to note, is that this guidance doesn't say _not_ to use `AddOptions`, but rather advises of potential concerns when using it with `Bind`. Specifically, that it would be read-once. I'll make that more clear and add the validation example, with a `string` parameter suggestion.
