### ISSUE TITLE
Statement is not clear

### ISSUE THREAD

**Issue by Soran-M** [dotnet/docs#33417]
[Enter feedback here]
Under the Ref local section, this statement "The variable p is no longer an alias to the variable returned." is not clear, the way I understand it the code, p was never an alias.

Could you also clary the text, make it more clear, that follows this line of code?
ref Person p = ref contacts.GetContactInformation("Brandie", "Best");

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d50744-0c94-b7d6-2f6f-c9d7130aee92
* Version Independent ID: b9310adb-a7c4-274a-2390-0c40a4cb368e
* Content: [Declaration statements - var, ref local variables, and ref fields](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/declarations)
* Content Source: [docs/csharp/language-reference/statements/declarations.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/declarations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 59232](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59232)

**Comment by BillWagner** [comment]
Thanks for noting this @Soran-M 

I'm updating those articles now, and I'll address this in those edits.
