### ISSUE TITLE
Inconsistent instructions

### ISSUE THREAD

**Issue by uecasm** [dotnet/docs#33422]
https://github.com/dotnet/docs/blob/2dc115bf49c84db1a79747bec2ac66f8c56ceb52/docs/core/deploying/trimming/prepare-libraries-for-trimming.md?plain=1#L44

Set it to `trim` or set it to `link`?

The example further down suggests that `link` was intended, but it's unclear.  Also, other documentation says that `link` is the default, so it's also unclear why this would need to be explicitly mentioned here, if that was the correct one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3d1f980-933d-a2a8-1645-098c2a4bc2a2
* Version Independent ID: 80dc5a35-aee1-fa68-5a21-78c628e9ff41
* Content: [Prepare .NET libraries for trimming - .NET](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming)
* Content Source: [docs/core/deploying/trimming/prepare-libraries-for-trimming.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/trimming/prepare-libraries-for-trimming.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sbomer
* Microsoft Alias: **svbomer**

**Comment by jtschuster** [comment]
Thank you for the feedback! We've updated the documentation with the correct instructions, and it should be live later today.
