### ISSUE TITLE
How would I add a class to an existing csproj in VS Code?

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/docs#33467]
The article addresses adding C# projects to a solution. How would I add a new or existing cs file to an existing csproj?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3cbb75b-e0aa-13c6-c07d-65f0f0f68da2
* Version Independent ID: 06ecbd1e-dad7-fbac-9160-dfce34df4d2c
* Content: [Create a .NET class library using Visual Studio Code - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio-code)
* Content Source: [docs/core/tutorials/library-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 60168](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60168)

**Comment by tdykstra** [comment]
Create the file in the project folder (the one that has the .csproj), or copy the existing file you want to add into the project folder. You can create a folder structure under that project folder and add your files to lower level folders if you prefer.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
