### ISSUE TITLE
Add more detail on the runtime store location

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#3346]
`https://docs.microsoft.com/dotnet/core/deploying/runtime-store`
*docs/core/deploying/runtime-store.md*

@ArtemSyromiatnikov asks ...

> C:/Program Files/dotnet/store - packages installed with ASP.NET Core (Microsoft.AspNetCore.All metapackage)
>C:/Users/{User}/.dotnet/store/ - packages installed manually with "dotnet store" command
> 1. Does dotnet runtime look for packages in both these locations when resolving dependencies on application startup?
> 2. Does runtime try to find package in Runtime Store every time when the targeted package is not present in deployment?

The topic could use a hair more detail on these two locations.

As far as the app is concerned running on the host, there's just one runtime store and it is the one at the *Program Files/dotnet/store* location.

For the example shown in the topic, the `Moq`, `Castle.Core`, and `Newtonsoft.Json` folders (with the versions that the manifest calls for) **MUST BE** in the runtime store folder with all of those implicitly stored `All` metapackage packages. That is **THE** runtime store.

If one doesn't have one or more of the explicit runtime store packages there (such as `Moq`, `Castle.Core`, or the version of `Newtonsoft.Json` shown in the topic example) listed in the manifest packages published against ... :boom: :cry: ... it blows up at runtime because it can't find the packages.

Also note that "runtime package store" goes to :point_right: "runtime store" after the decision about what name to use. That should be updated.

**Comment by mairaw** [comment]
@DamianEdwards would you be the right person to sync on runtime store when we get to this issue?

**Comment by DamianEdwards** [comment]
We should hold off on any further documentation of the runtime store as ASP.NET Core itself is moving away from using it to delivery runtime assets, see https://github.com/aspnet/MetaPackages/issues/248
