### ISSUE TITLE
How would I add a new or existing cs file to an existing csproj in VS Code?

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/docs#33468]
If I use File | New on an existing csproj, a new class is added to the folder. However, it is not added to the csproj.  I see a number of articles on creating solutions and adding projects to solutions.  I have not found anything on adding a new or existing cs file to a csproj file.

**Comment by gewarren** [comment]
For "SDK-style" projects, you don't need to manually add code files to the project. See https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-includes-and-excludes.
