### ISSUE TITLE
Warning still appears when the event is only there because of an interface

### ISSUE THREAD

**Issue by rbwhitaker** [dotnet/docs#33495]
This warning makes sense in the normal case, but we're seeing it in a situation we might not have generally expected it.

Suppose you have this interface:

```cs
public interface IThing
{
    event Action? E;
}
```
Implemented by this class:
```cs
public class Thing : IThing
{
    public event Action? E;
}
```

Suppose there are many implementations of `IThing`, most of which make good use of the `E` event. And this one implementation never encounters a situation where it is needed. Perhaps it is an event about some bit of data changing, but where this implementation never changes that data. There would be no need to use the event, but the event is still required because `Thing` implements the `IThing` interface. The warning is misleading.

We'll likely just `#pragma warning disable` it, but that's kind of ugly. This seems like a situation where the event going unused is justified, because it doesn't compile otherwise.

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 951244ec-7b1c-d067-aba6-e5074b01fe19
* Version Independent ID: fcb87ea8-0040-004d-14a7-808afd939c30
* Content: [Compiler Warning (level 3) CS0067](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0067)
* Content Source: [docs/csharp/misc/cs0067.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0067.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The warning is correct here. It's mainly because the compiler generates a field for the event.

One way to suppress this warning is:

```csharp
using System;

public interface IThing
{
    event Action? E;
}

public class Thing : IThing
{
    public event Action? E { add { } remove { } }
}
```

**Comment by BillWagner** [comment]
Hi @rbwhitaker 

@Youssef1313 is correct. The warning is correct, and his suggestion on how to suppress it is correct.

I'll put this in our backlog to update when we next update this article. I'll also add the "help wanted" label if anyone wants to submit a PR for this.

**Comment by rbwhitaker** [comment]
Thanks @Youssef1313 and @BillWagner for the replies.

**Comment by BartoszKlonowski** [comment]
@BillWagner I would like to work on this - please assign me to this item so I won't forget about it.
