### ISSUE TITLE
Document .NET 8 SDK changes to NuGet signed package verification

### ISSUE THREAD

**Issue by dtivel** [dotnet/docs#33502]
Document changes to NuGet signed package verification in .NET 8 SDK.

Past PR for .NET 7 SDK: https://github.com/dotnet/docs/pull/32328

---
[Associated WorkItem - 90205](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90205)

**Comment by adegeo** [comment]
Hi @dtivel can you use the property issue template? You can use this link to copy/paste the content into THIS issue and just fill it out, no need to close this one and open a new one: https://github.com/dotnet/docs/issues/new?assignees=&labels=&template=docs-request.md&title=

**Comment by adegeo** [comment]
Whoops, I assumed this issue was a request, not a simple "track the work" issue. My bad 😁
