### ISSUE TITLE
loops and branches

### ISSUE THREAD

**Issue by Abashed99** [dotnet/docs#33510]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8557d001-9b33-e5d6-5bef-3601d49927fe
* Version Independent ID: 34dcf0cc-d886-cdb3-0a0f-03203eae6d82
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/branches-and-loops)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @Abashed99 

Closing as kudos.
