### ISSUE TITLE
Missing catch (TaskCanceledException)

### ISSUE THREAD

**Issue by ContentsMayVary** [dotnet/docs#33529]
The sample code for the `protected override async Task ExecuteAsync(CancellationToken stoppingToken)` method needs to add the following `catch` statement before the `catch (Exception ex)`:

catch (TaskCanceledException)
{
    // This is OK.
}

Otherwise when you stop the service in Service Manager, you'll see an error because `TaskCanceledException` is thrown when the service loop terminates.

(This might only apply to .NET 7, which is the only version I tested this with)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 62379](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62379)

**Comment by IEvangelist** [comment]
Hi there, @ContentsMayVary - did you see this section?

https://learn.microsoft.com/dotnet/core/extensions/windows-service#service-recovery-options-and-net-backgroundservice-instances

If the service manager is requesting shutdown, what would you propose to happen? Are you saying that with your tests, this causes it to crash?

**Comment by ContentsMayVary** [comment]
Normally when you stop a service from services.msc, it stops without error. However the sample code for this project causes the following message when you stop the service:
`"Windows could not stop <name of service> service on Local Computer. Error 1067: The process terminated unexpectedly">`

This does not seem correct, and the reason for it is that the service loop is terminated by a `TaskCanceledException` and the catch handler responds to this by calling `Environment.Exit(1);`

The solution  is to catch the expected `TaskCanceledException` and do nothing. The loop will be exited, and the service will stop without an error being reported.
