### ISSUE TITLE
Doesn't Apply to UWP Projects

### ISSUE THREAD

**Issue by KennethEvans** [dotnet/docs#33554]
You cannot find the compiler version from the .proj file for UWP. The article in general does not appear to apply for UWP.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 350757](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350757)

**Comment by BillWagner** [comment]
ping @adegeo

What would you recommend I add here?

**Comment by KennethEvans** [comment]
That it doesn't apply to UWP. You can't, for example, find the compiler version in the project file. Try it, and it should be clear that the article doesn't describe the UWP situation correctly.

**Comment by adegeo** [comment]
Maybe @hickeys can clarify?

**Comment by KennethEvans** [comment]
Actually I still haven't figured out how to find the compiler version for UWP - - why I was at this page. I'm experienced in Winforms but quite not UWP. I decided to skip UWP and try WinUI. It's not in that project file either. I am using new projects created in VS 2022 with the latest update.

**Comment by hickeys** [comment]
I don't know that I can be of very much help, but I'll give it a go anyway. @KennethEvans is correct that the compiler version is not included in the .csproj for a new UWP project. I also didn't see anything helpful in the appxmanifest. I believe that, when there is no version specified, it will use the default version. The default varies from machine to machine depending on which versions are installed.

**Comment by adegeo** [comment]
I don't know that this article would be the place to list the UWP C# version. Instead, it would be in the UWP docs, such as https://learn.microsoft.com/windows/uwp/updates-and-versions/choose-a-uwp-version
