### ISSUE TITLE
ECMA 335 link is broken

### ISSUE THREAD

**Issue by agr** [dotnet/docs#33575]
ECMA 335 link in the text responds with 404, please update with a working one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19439836-06e1-b407-04ae-444c395e1ecc
* Version Independent ID: 57e0f822-3287-3f29-530a-9aa1ccd1e862
* Content: [.NET assembly file format](https://learn.microsoft.com/en-us/dotnet/standard/assembly/file-format)
* Content Source: [docs/standard/assembly/file-format.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/file-format.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @richlander
* Microsoft Alias: **dapine**

**Comment by richlander** [comment]
Looks like the site as a whole is having trouble: https://www.ecma-international.org/

**Comment by richlander** [comment]
Site is back up and the link now works.
