### ISSUE TITLE
Guidance for equivalent functionality in Visual Studio 2022 needed

### ISSUE THREAD

**Issue by simeyla** [dotnet/docs#33573]
> The .NET Portability Analyzer is not supported in Visual Studio 2022.

There's no guidance for the equivalent feature for VS2022! 
Please add such information / link to feature page. It would be very helpful - especially since this page ranks very highly on search engines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdd8086b-9a95-38d5-160f-c12c653f954e
* Version Independent ID: 0f47d826-e3ef-8549-9d37-2e8afae29f46
* Content: [The .NET Portability Analyzer - .NET](https://learn.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer)
* Content Source: [docs/standard/analyzers/portability-analyzer.md](https://github.com/dotnet/docs/blob/main/docs/standard/analyzers/portability-analyzer.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-analyzers**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 60517](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60517)

**Comment by IEvangelist** [comment]
Thank you @simeyla for posting this issue, however, the article intentionally doesn't have equivalent instructions for Visual Studio 2022 as it isn't supported, see [How to use the .NET Portability Analyzer](https://learn.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer#how-to-use-the-net-portability-analyzer).

![image](https://user-images.githubusercontent.com/7679720/214370742-799db4e4-dcc0-4aa4-9970-ef74b9c45983.png)
