### ISSUE TITLE
Question: Firfox retrieve web page complete of .NET API browser service, but c# code webclient can't retrieve the complete page  with loss of data.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/docs#3364]
I try to get the contents from of .NET API  browser service using c# code for the following url:

            https://docs.microsoft.com/en-us/dotnet/api/?view=netstandard-2.0&term=System.Runtime.Serialization.DataContractSerializer
 
 The following code get the web page contents with the loss of the Api information:
 
			 WebClient client = new WebClient();
			string reply = client.DownloadString(url);
			Console.WriteLine(reply);
			
Even I used httpclient library and  curl but I can't get the API data.

Using Firfox/or Internet Explorer , I  can browse the contents without loss  and see the API information within the tags
 
		 <table class="api-search-results" .... />
 
What i missed in c# code  to get the complete page  with API information?
Is there REST API library to use .NET API Browser service?

**Comment by mairaw** [comment]
Hi @moh-hassan, I'm not sure if we have the API Browser set up as a service like that.

@dend @eisenbergeffect can one of you comment on this?

**Comment by EisenbergEffect** [comment]
We don't currently support API Browser as a service. It's definitely something we're considering along with other APIs for docs.microsoft.com. My feeling is that the API Browser and related functionality is a little to early to open up. It probably needs to evolve more and then we need to make sure we can scale, support, version, etc. any public API.

**Comment by mairaw** [comment]
Thanks for the feedback @EisenbergEffect. @moh-hassan given this is a general docs feedback, I'll close this issue and I suggest you file this suggestion at https://aka.ms/sitefeedback. Thanks again!

**Comment by moh-hassan** [comment]
Thanks for feedback
I suggested at https://aka.ms/sitefeedback
[support the .NET API Browser as a service and Provide REST API to access it](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/31843894-support-the-net-api-browser-as-a-service-and-p)
