### ISSUE TITLE
Awaiting on Finished task ? 

### ISSUE THREAD

**Issue by HarshalRajkotia** [dotnet/docs#33649]
Once we are getting the Finished task from Task list at line  

Task finishedTask = await Task.WhenAny(breakfastTasks);

what's the point of waiting on finished task when it's already completed at below lines ?

await finishedTask;
breakfastTasks.Remove(finishedTask);

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @HarshalRajkotia 

This is tracked in #33559

Closing as a duplicate.
