### ISSUE TITLE
need a clear sample for a small app

### ISSUE THREAD

**Issue by figuerres** [dotnet/docs#33656]
[Enter feedback here]
hi, i want to use ef core and the new minimal startup model...

i want to get the sql connection string to the ef but all the stuff i see is for asp.net or for the old style of startup.
what is the minal rout for this ?

i just want to have program.cs call a class and that class does work and returns.
i do not want to create 6 classes to do a lot of back and forth .... just to get the sql connection string passed to ef.

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4eb702a-d75f-f780-aef1-2e858e14258f
* Version Independent ID: 9a183e07-d5fd-1de9-796d-3bc77f07e033
* Content: [Use dependency injection - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage)
* Content Source: [docs/core/extensions/dependency-injection-usage.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-usage.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by mohamed-azhar** [comment]
Hi @figuerres ,

You can get the connection string from the Program.cs  pretty easily using the ```WebApplicationBuilder``` instance shown below.
The ```builder``` variable will be already available in the scaffolded project. Inside the builder, you'll get access to the ```ConfigurationManager``` which has a helper method which lets you extract the connection string from the ```appsettings.json``` file. Just make sure to define the connection string section in the appsettings.json file.

**Program.cs** file
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.GetConnectionString("Default");
```

**appsettings.json** file
```json
 "ConnectionStrings": {
    "Default": "Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;"
  },
```

**Comment by figuerres** [comment]
console app, no asp.net is involved.

to clarify:
a console app with .net core 6 and ef core.
minimal startup where program.cs has just a console.writeline and no main()

so many searches assume a web site and a startup.cs .....   lets get an example for the new minimal program.cs flavor!

**Comment by IEvangelist** [comment]
Hi @figuerres,

As @mohamed-azhar mentioned, the easiest way to get the connection string is through configuration. To avoid a web app approach, strictly using just a console app, you could use the `Microsoft.Extensions.Hosting` NuGet package:

```csharp
var builder = Host.CreateDefaultBuilder(args);
var connectionString = builder.Configuration.GetConnectionString("Default");
```

Like @mohamed-azhar said, this could be stored in a JSON file or environment variable (or any other configuration provider source):

```json
{
  "ConnectionStrings": {
    "Default": "Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;"
  }
}
```

Does this help, or are you looking for something else yet?

**Comment by IEvangelist** [comment]
Closing this issue as the op hasn't replied in weeks and we've provided resolution.
