### ISSUE TITLE
Documentation of the final state of interface default methods

### ISSUE THREAD

**Issue by vmelamed** [dotnet/docs#33651]
Can you please update this document with the final implementation of interface default methods? This looks pretty messy with all these open/closed issues, decisions (is it implemented?), etc. I cannot find a good document in the MS official documentation that describes the final state of this great feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17012c83-0313-919b-eb8b-04fae8f4df4a
* Version Independent ID: 05252e5a-e53c-5ce5-84b3-671faad0549c
* Content: [Default interface methods - C# 8.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods)
* Content Source: [proposals/csharp-8.0/default-interface-methods.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @vmelamed 

The ECMA committee is working to update the standard. We're working in the [dotnet/csharpstandard](https://github.com/dotnet/csharpstandard) repository. 

We know we have a lot of work to catch up on. We're working on the 7.3 standard now. We hope to finish that work soon. In the meantime, Rex is preparing draft PRs for Version 8 features, including this one.

We will continue to work on these, and we'll track our progress in the csharpstandard repo. I'll close this, as it's already being tracked there.
