### ISSUE TITLE
question about ' Sets the nullable annotation context and nullable warning context to enable.

### ISSUE THREAD

**Issue by pcreyssels** [dotnet/docs#33667]
in your document you write :
#nullable enable: **Sets the nullable annotation context and nullable warning context to enable.**
I don't understand  because "nullable annotation context" and "nullable warning context " are mutually exclusive
ant their properties are conflicting : for example 
- _Dereference warnings_ is enabled with _nullable warning context_
- _Dereference warnings_ is disabled with _nullable annotation context_
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 350753](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350753)

**Comment by BillWagner** [comment]
Hi @pcreyssels 

The `annotation` and `warning` context aren't mutually exclusive. You should think of these as two boolean values, one for type annotations, and one for warnings:

- `disable`: both disabled.
- `annotation`: nullable annotations are enabled, warnings aren't emitted.
- `warning`: nullable annotations are disabled, warnings are emitted.
- `enabled`: nullable annotations are enabled, warnings are emitted.

What did you read that made you think they are mutually exclusive?

**Comment by pcreyssels** [comment]
Hi bill and thanks
I now understandand better.

The confusing term (for me) used in article  is :
'nullable annotation context' 
Is 'annotation' term refer to use of attribute (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analyses) or refer  to use  '?' postfix operator to declare a reference variable to be nullable ? 

Thanks
Patrice 


Le 23 janv. 2023 à 15:08, à 15:08, Bill Wagner ***@***.***> a écrit:

**Comment by BillWagner** [comment]
Thanks for clarifying @pcreyssels 

In the first use, "annotations" should be defined to refer to the type annotation (`?`) and the nullable suppression operator (`!`).

I'll add the "help-wanted" label if anyone wants to submit a fix before we update this article.

**Comment by pcreyssels** [comment]
Many thanks Bill

Le 24 janv. 2023 à 15:51, à 15:51, Bill Wagner ***@***.***> a écrit:
