### ISSUE TITLE
Docs: Unclear #line formula

### ISSUE THREAD

**Issue by DreadLordMikey** [dotnet/docs#33666]
In the formula found on [Enhanced #line directives - C# 10](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/enhanced-line-directives#examples:~:text=M(l,1%2C%20c)), the following formula is provided:

>M(l, c) =
>
>l = d + 1 => <ins>(L.start.line + l – d – 1, L.start.character + max(c – character offset, 0))</ins> **l > d + 1 => (L.start.line + l – d – 1, c)**

Note, however, that immediately prior to `l > d + 1 => (L.start.line + l - d - 1, c)` (bolded) there is no intervening operator; the expression appears immediately after the expression that precedes it (underscored).

Is this correct? Can we get some clarification on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19676f37-72c5-ace5-f1e0-f2693c0ffe46
* Version Independent ID: ee32bc8f-4a21-dba1-5ab4-38852321190e
* Content: [Enhanced #line directives - C# 10.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/enhanced-line-directives#examples)
* Content Source: [proposals/csharp-10.0/enhanced-line-directives.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/enhanced-line-directives.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@cston 

Can you clarify here?

**Comment by cston** [comment]
The expression is intended as two separate cases, _l = d + 1_ and _l > d + 1_, although the formatting was not clear. Updated in https://github.com/dotnet/csharplang/pull/6903.
