### ISSUE TITLE
The section comparing the DAL and Repository pattern is ineffective without an example

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#33675]
https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design#the-difference-between-the-repository-pattern-and-the-legacy-data-access-class-dal-class-pattern

The repository pattern allows you to access data and is a layer in the application stack, thus it is a **data access layer**. 
The section kind of goes off topic explaining data access object (what is that exactly, and why is a Repository pattern implementing class not a DAO?) and a unit of work and is more or less hardlinking this concept to Entity Framework when it should just be using the more general and long standing concepts and terminology ("Transaction") and leaving the EF stuff to a footnote.

If a clear comparison example cannot be made between the two, the section should be removed from the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3000b84-336c-df28-05d2-de8b9d9708ee
* Version Independent ID: 5d327117-1420-8110-963b-822b6acdc976
* Content: [Designing the infrastructure persistence layer](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by jamesmontemagno** [comment]
@ardalis are you able to take a look at this?

**Comment by ardalis** [comment]
Yep, on it.

**Comment by ardalis** [comment]
> The repository pattern allows you to access data and is a layer in the application stack, thus it is a data access layer.

This is incorrect. The repository pattern is all about abstracting persistence logic from your domain model. It's a DDD pattern focused on keeping the domain model pure and not polluting it with low level infrastructure concerns. Repository adapters/implementations typically live in a separate infrastructure project, and these would indeed be part of what you might consider a data access layer. But the important part of the pattern is the abstraction in the domain model, not the adapters that implement it.

That aside, I do agree this paragraph is somewhat confusing. It appears to be trying to make the case that all repositories leverage a unit of work pattern (they don't) and that all standard Data Access Layer implementations do not (they certainly can). I think that needs addressed and I'll work on a PR here in a bit that and will reference this issue.

Thanks for your feedback, @StingyJack ! Feel free to comment on the PR once it's available.

**Comment by StingyJack** [comment]
If you are talking about layers of an application stack, it can look something like this.  Each of these is a separate project/assembly with the one above knowing only an abstraction about the one below. 

```
UI
Controller
Service
Data
```
with the DB being at the absolute bottom, but not part of the application code.   There is a layer that is used to access and interact with the underlying data and it is the Data Access Layer. This can be implemented in a number of ways; Repository Pattern, Data Access Objects, Code Generated CRUD, etc. and can be partitioned by access type (Get/Save) or by type of data (Employee, Customer, Order).  I've seen DAO that properly abstract and Repo that do not.  This amount of variation in the wild is why a good example is critical to ensuring the ideas you are trying to put forth are received properly.
