### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by jaenDeyPlaidne** [dotnet/docs#33671]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 516a8fed-04ea-628c-d644-eb81dedecfe6
* Version Independent ID: 060c37e4-36e1-48b3-2435-cf858b14d860
* Content: [Data collections - Introduction to C# interactive tutorial](https://learn.microsoft.com/en-au/dotnet/csharp/tour-of-csharp/tutorials/list-collection)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/list-collection.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @jaenDeyPlaidne 

Do you have further comments here? I'm going to close this, but if you have further comments, you can open a new issue, or add comments here and reopen the issue.

**Comment by jaenDeyPlaidne** [comment]
#22784
