### ISSUE TITLE
Is there any option to switch between old and new?

### ISSUE THREAD

**Issue by sing-ideas** [dotnet/docs#33670]
I noticed the option to adopt or not to adopt the Top level statemen. Is there a way to switch between the two scenarios? Or is it even possible to bring an option to switch?

              Up-vote this comment if you would like to be given a choice between top-level statements code and the code created in previous .NET versions.

_Originally posted by @tdykstra in https://github.com/dotnet/docs/issues/27420#issuecomment-987007543_
            

---
[Associated WorkItem - 60369](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60369)

**Comment by tdykstra** [comment]
See https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-old-program-style

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by sing-ideas** [comment]
Well, I saw that link earlier too, but my question is if I opted to check the box for a project, can I reverse the decision in that project? Is there any option to opt in/out after the project is created? Or is it a decision that can be taken only at the time of creating a new project?

**Comment by sing-ideas** [comment]
Well, I saw that link earlier too, but my question is if I opted to check the box for a project, can I reverse the decision in that project? Is there any option to opt in/out once the project is created? Or is it a decision that can be taken only at the time of creating a new project?

**Comment by BillWagner** [comment]
> Well, I saw that link earlier too, but my question is if I opted to check the box for a project, can I reverse the decision in that project? Is there any option to opt in/out once the project is created? Or is it a decision that can be taken only at the time of creating a new project?

Yes, you can change after creating a project. There's two refactorings in Visual Studio that convert from top-level statements to`Program.Main` and back.
