### ISSUE TITLE
Passing a new HttpClientHandler to base causes exception when using Handler with Dependency Injection

### ISSUE THREAD

**Issue by bradleypatton** [dotnet/docs#33679]
[Enter feedback here]

In the first code sample there is the following line

```
    public ClientSideRateLimitedHandler(RateLimiter limiter)
        : base(new HttpClientHandler()) => _rateLimiter = limiter;
```

In DI setup I'm creating a typed HttpClient like so 

```
    services.AddHttpClient<AuWebClient>(client =>
        client.DefaultRequestHeaders.Add("Accept", "application/json"))
        AddHttpMessageHandler(() => new ClientSideRateLimitedHandler(limiter));
```

Which causes the following exception when the client is first requested

InvalidOperationException: The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.

Removing the `new HttpClientHandler()` line removes the exception and the handler works as expected

```
    public ClientSideRateLimitedHandler(RateLimiter limiter) : base() => _rateLimiter = limiter;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d93e7ed8-ab2b-34ac-3a39-cbb7d8f4a879
* Version Independent ID: 597c7a5e-2dee-38e9-cf41-3b47e1580701
* Content: [Rate limiting an HTTP handler in .NET - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/http-ratelimiter)
* Content Source: [docs/core/extensions/http-ratelimiter.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/http-ratelimiter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 60361](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60361)

**Comment by IEvangelist** [comment]
Hi @bradleypatton,

Thanks for posting this issue.

This example doesn't use DI, instead, it shows a different approach. If you're to use DI, as you mentioned - that is awesome, but this doc and code example doesn't. Adding DI would add an additional concept that is beyond the scope of this article. I'm happy that you were able to get your code working though. I'm going to close this issue, but if you need anything else please let me know.

**Comment by bradleypatton** [comment]
I've been searching for an example using a DelegatingHandler with Dependency Injection since the recommended way to use a HttpClient in asp.net core is with a typed client. Sadly there are not many examples around. None of the other examples I have found of using a DelegatingHandler pass a new empty handler to the base so I'm curious why this works in this example. If I have time I will try that in a new project.
