### ISSUE TITLE
Error in the code of an example.

### ISSUE THREAD

**Issue by slimktari** [dotnet/docs#33677]
In the portion of code of the C class, there is a little problem. However, it is not related to the topic of the page.
The class is public while the init accessor is protected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 491550b6-23f8-a48a-c6e5-f177151030ff
* Version Independent ID: 4037b376-e4f6-73cc-3dd1-abea0fc7db5b
* Content: [Required members - C# 11.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members)
* Content Source: [proposals/csharp-11.0/required-members.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/required-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
tagging @333fred 

I believe that declaration is correct and intentional. The example for `C` shows what conditions cause the compiler to generate warnings.

**Comment by 333fred** [comment]
That is correct, it is intentionally bad code, demonstrating what will cause an error.

**Comment by BillWagner** [comment]
Thanks

I'll close as by-design.
