### ISSUE TITLE
AssemblyFlagsAttribute description unclear

### ISSUE THREAD

**Issue by uecasm** [dotnet/docs#33689]
https://github.com/dotnet/docs/blob/c164f4b1dcd7be3fd4a3dc21c71217888a03a68b/docs/csharp/language-reference/attributes/global.md?plain=1#L32

Where does this description of the attribute come from?  If you look at the docs for [`AssemblyFlagsAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyflagsattribute) and particularly for [`AssemblyNameFlags`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblynameflags), the documented flags don't appear to be even slightly related to that description.

(Note: there appear to be [other places](https://github.com/dotnet/docs/search?q=assemblyflagsattribute) in the docs that have similar descriptions for this attribute as well.)

Though perhaps this just means that the enumeration is missing some additional values?  The [docs for AL.exe](https://github.com/dotnet/docs/blob/782303efd0a479e95fec86f6b017918723a304d3/docs/framework/tools/al-exe-assembly-linker.md?plain=1#L54) suggest that there are actually more flags than are documented by the enumeration...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9061ed45-28b5-6162-ede2-48f028516e8e
* Version Independent ID: a48f27c2-0f05-3db0-b993-a70eb8217cc4
* Content: [Attributes interpreted by the C# compiler: Global attributes](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/global)
* Content Source: [docs/csharp/language-reference/attributes/global.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/global.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 289449](https://dev.azure.com/msft-skilling/Content/_workitems/edit/289449)

**Comment by BillWagner** [comment]
Thanks @uecasm 

We'll have to figure out which description is correct, and make these consistent.

adding @chsienki Do you know who I should tag to get these correct?
