### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [dotnet/docs#33702]
If I used the script to install, how do I uninstall?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 60739](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60739)

**Comment by tdykstra** [comment]
To uninstall, delete the files from the install directory, which is either the default location or the location specified via `--install-dir`.

cc @YuliiaKovalova

**Comment by A9G-Data-Droid** [comment]
It would be super slick if the script created an uninstall script, based on the install directory it used during installation. I believe it also modifies the PATH variable. There are multiple ways to do this on Linux. It would be nice to document how this was done, and again, provide a path to reversing all changes made to a system.

**Comment by adegeo** [comment]
Related to #30744

**Comment by tdykstra** [comment]
@dotnet/install-scripts-maintainers What needs to be done to uninstall, other than deleting the files that are copied into the install directory?

**Comment by MichalPavlik** [comment]
Hello, I believe the only thing is just removing files. Script sets environment variable, but it's just for the current process. I checked if the downloaded zip file stays on disk, but there is a line near end of the script that removes the file as well. That means, if the computer is for example restarted before script reaches the end, zip file could also be on the disk.
