### ISSUE TITLE
Not to helpful for VS for mac 2022

### ISSUE THREAD

**Issue by sepp00** [dotnet/docs#33713]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3988d4f-96e4-834a-aaad-0c5db795b4ae
* Version Independent ID: 9a2d4f2a-eda8-4618-6baf-4ad71357eff7
* Content: [NETSDK1045: The current .NET SDK does not support 'newer version' as a target. - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1045)
* Content Source: [docs/core/tools/sdk-errors/netsdk1045.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1045.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 60856](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60856)

**Comment by tdykstra** [comment]
What version of VS for Mac are you using, and what version of .NET are you trying to target?

**Comment by sepp00** [comment]
VS for Mac : 2022 17.4.3
TargetFramework: net6.0

I get this error message
Getting restore information for project /Users/steveepp/vpSVN_Versions2/mac (branch)/EviPad3/EviPad3/EviPad3.csproj
/usr/local/share/dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5) : error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.
Unable to create package spec for project. '/Users/steveepp/vpSVN_Versions2/mac (branch)/EviPad3/EviPad3/EviPad3.csproj'

**Comment by tdykstra** [comment]
What do you get when you run dotnet `--list-sdks`?

**Comment by sepp00** [comment]
***@***.*** android-sdk-macosx % dotnet --list-sdks

2.1.505 [/usr/local/share/dotnet/sdk]

2.1.700 [/usr/local/share/dotnet/sdk]

3.1.415 [/usr/local/share/dotnet/sdk]

3.1.416 [/usr/local/share/dotnet/sdk]

3.1.418 [/usr/local/share/dotnet/sdk]

3.1.419 [/usr/local/share/dotnet/sdk]

3.1.420 [/usr/local/share/dotnet/sdk]

3.1.424 [/usr/local/share/dotnet/sdk]

3.1.425 [/usr/local/share/dotnet/sdk]

3.1.426 [/usr/local/share/dotnet/sdk]

5.0.403 [/usr/local/share/dotnet/sdk]

5.0.404 [/usr/local/share/dotnet/sdk]

5.0.405 [/usr/local/share/dotnet/sdk]

5.0.407 [/usr/local/share/dotnet/sdk]

5.0.408 [/usr/local/share/dotnet/sdk]

6.0.402 [/usr/local/share/dotnet/sdk]

6.0.403 [/usr/local/share/dotnet/sdk]

6.0.404 [/usr/local/share/dotnet/sdk]

6.0.405 [/usr/local/share/dotnet/sdk]

7.0.100 [/usr/local/share/dotnet/sdk]

7.0.101 [/usr/local/share/dotnet/sdk]

7.0.102 [/usr/local/share/dotnet/sdk]

**Comment by tdykstra** [comment]
@jmatthiesen Can you help with this -- I believe VS for Mac 17.4.3 should support .NET 6, and .NET 6 SDK is installed, but @sepp00 is getting NETSDK1045 and it indicates 5.0 is the latest supported .NET version.

**Comment by sayedihashimi** [comment]
Let's see if @mrward can assist.

**Comment by mrward** [comment]
I would open the Solution Properties window (right click the solution in the Solution window and select Properties), select Build - General, and uncheck 'Build with MSBuild on Mono'.

This 'Build with MSBuild on Mono' option will be checked if there are any classic projects in the solution and this can cause problems since Mono does not support the later .NET SDKs.

VS Mac support for both dotnet msbuild and MSBuild on Mono. In order to do that it has some logic that may enable MSBuild on Mono for the entire solution and this can cause problems, such as the `error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0. ` error, since the .NET SDK version is downgraded when MSBuild on Mono is used.
