### ISSUE TITLE
The diagrams used to explain deadlocks in the Reentrancy section of the Microsoft Orleans docs are wrong

### ISSUE THREAD

**Issue by dggmez** [dotnet/docs#33724]
**Issue description**

In the Reentrancy section of the Microsoft Orleans documentation the same diagram is used for `Case 1: the calls do not deadlock` and `Case 2: the calls deadlock`:

https://learn.microsoft.com/en-us/dotnet/orleans/grains/reentrancy#case-1-the-calls-do-not-deadlock

https://learn.microsoft.com/en-us/dotnet/orleans/grains/reentrancy#case-2-the-calls-deadlock

**Target framework**

- .NET 7

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4ab7af-82bf-efd1-9742-ade3e84c0df4
* Version Independent ID: 92bb7973-a8c4-e948-6aa7-f40eecfeaafd
* Content: [Reentrancy](https://learn.microsoft.com/en-us/dotnet/orleans/grains/reentrancy#case-1-the-calls-do-not-deadlock)
* Content Source: [docs/orleans/grains/reentrancy.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/reentrancy.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 62386](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62386)

**Comment by ReubenBond** [comment]
It seems that the "do not deadlock" one should be this: https://github.com/dotnet/orleans-docs/blob/main/src/images/scheduling_6.png

**Comment by IEvangelist** [comment]
Fixed by #32830
