### ISSUE TITLE
We should be able to modify the default value that triggers that rule

### ISSUE THREAD

**Issue by lflender** [dotnet/docs#33737]
26 is too much

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1148f2d-f598-9a79-2036-aa8b302f8bd3
* Version Independent ID: b88d281d-59fd-353b-3548-ac5f9db0c49d
* Content: [CA1502: Avoid excessive complexity (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1502)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1502.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1502.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Could you move this to dotnet/roslyn-analyzers?

**Comment by mavasani** [comment]
This is already supported - I’ll try to update the docs.

**Comment by lflender** [comment]
@mavasani  Can you please share how to change that until the doc is updated? Is there a generic way to change thresholds of similar rules (e.g. CA1505)? Thank you

**Comment by mavasani** [comment]
@lflender Actually, it seems this documentation already exists at https://learn.microsoft.com/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2022#configuration. It was added in https://github.com/MicrosoftDocs/visualstudio-docs/commit/3a661cc011050dbd0702e6c768295023a1c6e069. @gewarren I think we should add a note to each of the 4 code metric rule doc pages: https://learn.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2022#net-code-quality-analyzers-code-metrics-rules to have a pointer to https://learn.microsoft.com/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2022#configuration

**Comment by lflender** [comment]
@mavasani Thank you. Indeed a link from the code metric rules would be nice. However it is super weird to have to add an additional txt file to consuming projects to change those thresholds. I will see if it can be done through a nuget along the editorconfig and nuget dependencies deployment... but it is expected to be configured in the .editorconfig, don't you think?

**Comment by mavasani** [comment]
Thanks @lflender - I filed https://github.com/dotnet/roslyn-analyzers/issues/6462 to track this feature request. Feel free to contribute a change if you are interested. You will need to add the enhancement here: https://github.com/dotnet/roslyn-analyzers/blob/9dd3c12b2244e67c0b9c7aa922ec4ac74d977f59/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzer.cs#L293-L297

**Comment by lflender** [comment]
Great, thanks again @mavasani

However the repo you linked is said to be deprecated from the nuget store
![image](https://user-images.githubusercontent.com/16304182/215470014-bf933462-16e4-42ba-9841-df7f4731d53d.png)

Not sure how that works or where is the Microsoft.CodeAnalysis.NetAnalyzers however. Can you please confirm that the fix should actually be done where you first linked?

**Comment by mavasani** [comment]
> Great, thanks again @mavasani
> 
> However the repo you linked is said to be deprecated from the nuget store ![image](https://user-images.githubusercontent.com/16304182/215470014-bf933462-16e4-42ba-9841-df7f4731d53d.png)
> 
> Not sure how that works or where is the Microsoft.CodeAnalysis.NetAnalyzers however. Can you please confirm that the fix should actually be done where you first linked?

@lflender All analyzers under `src\NetAnalyzers` in roslyn-analyzers repo ship inside `Microsoft.CodeAnalysis.NetAnalyzers` NuGet package. So the above linked source file is the right place for adding this feature.

**Comment by lflender** [comment]
Awesome, thanks again, I'll have a look

**Comment by lflender** [comment]
That's weird.

When I try to build I have the following errors:
`2>C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0.
2>Done building project "ReleaseNotesUtil.csproj" -- FAILED.
4>C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(127,5): error NETSDK1141: Unable to resolve the .NET SDK version as specified in the global.json located at C:\git\roslyn-analyzers\roslyn-analyzers\global.json.`

And when I remove the global.json file I have ther following errors:
`1>C:\git\roslyn-analyzers\roslyn-analyzers\Directory.Build.props(13,3): error : C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
1>C:\git\roslyn-analyzers\roslyn-analyzers\Directory.Build.props(13,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.`

I have 3 SDKs installed:
![image](https://user-images.githubusercontent.com/16304182/215503446-8764b0a3-cc32-4f37-9cb5-b1f9f056b925.png)

and the sources look fine:
![image](https://user-images.githubusercontent.com/16304182/215503562-af3f47bd-b2ab-4f4d-af06-d7716e96cd8b.png)

I tried to fix it and got to https://github.com/dotnet/arcade but I'm not authorized to download it through the provided link https://maestro-prod.westus2.cloudapp.azure.com/
![image](https://user-images.githubusercontent.com/16304182/215504208-3f4d0b9d-bfa2-4be4-9c21-b4a62308d8d7.png)

Any help appreciated!

**Comment by mavasani** [comment]
> That's weird.
> 
> When I try to build I have the following errors: `2>C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0. Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0. 2>Done building project "ReleaseNotesUtil.csproj" -- FAILED. 4>C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(127,5): error NETSDK1141: Unable to resolve the .NET SDK version as specified in the global.json located at C:\git\roslyn-analyzers\roslyn-analyzers\global.json.`
> 
> And when I remove the global.json file I have ther following errors: `1>C:\git\roslyn-analyzers\roslyn-analyzers\Directory.Build.props(13,3): error : C:\Program Files\dotnet\sdk\6.0.308\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json. 1>C:\git\roslyn-analyzers\roslyn-analyzers\Directory.Build.props(13,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.`
> 
> I have 3 SDKs installed: ![image](https://user-images.githubusercontent.com/16304182/215503446-8764b0a3-cc32-4f37-9cb5-b1f9f056b925.png)
> 
> and the sources look fine: ![image](https://user-images.githubusercontent.com/16304182/215503562-af3f47bd-b2ab-4f4d-af06-d7716e96cd8b.png)
> 
> I tried to fix it and got to https://github.com/dotnet/arcade but I'm not authorized to download it through the provided link https://maestro-prod.westus2.cloudapp.azure.com/ ![image](https://user-images.githubusercontent.com/16304182/215504208-3f4d0b9d-bfa2-4be4-9c21-b4a62308d8d7.png)
> 
> Any help appreciated!
> 
> EDIT: Actually I can't even load Microsoft.CodeAnalysis.Analyzers ![image](https://user-images.githubusercontent.com/16304182/215507994-968018e2-341e-4445-848d-555559a734f4.png)
> 
> ![image](https://user-images.githubusercontent.com/16304182/215508053-e2304ec1-f8a6-49c9-88c8-7f3f7cf1137a.png)
> 
> ![image](https://user-images.githubusercontent.com/16304182/215508163-48f606cd-98a2-4852-b17c-a3c2eaeaf764.png)
> 
> Looks like `MicrosoftCodeAnalysisVersion` is undefined

@Youssef1313 any idea?

**Comment by Youssef1313** [comment]
@lflender You shouldn't be removing `global.json`.

Can you downlaod [.NET 8 SDK](https://github.com/dotnet/installer#table) (which is the version required by [global.json](https://github.com/dotnet/roslyn-analyzers/blob/324147fb83389f082d6aabeeebea1e66c2ede04f/global.json#L3)) and see if it works?

---

> Looks like `MicrosoftCodeAnalysisVersion` is undefined

The property is defined. To narrow things down, make sure you don't make any changes on the latest `main` branch and you have the .NET 8 SDK.

**Comment by lflender** [comment]
Thank you @Youssef1313, I was actually looking for it but could not find an actual link.

Now it is complaining that MSBuild 17.4 is missing. I can't find it either. https://github.com/dotnet/msbuild/releases does not have any (pre)release after 17.2 :(

**Comment by Youssef1313** [comment]
@lflender Can you update Visual Studio to 17.4?

**Comment by gewarren** [comment]
This might be helpful too: https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs

**Comment by lflender** [comment]
I was stuck with an LTSC 17.2 version so I did not see further updates in my installer... Indeed everything's good with 17.4, thanks for the help

**Comment by lflender** [comment]
I tried a fix but for some reason I can't run any unit test in the solution. They all give the following error:

`    NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://api.nuget.org/v3/index.json.
    ---- System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I can reach the api.nuget.org endpoint just fine in my other solutions. I tried different fixes but without success for now.
Not sure I can afford to spend anymore time on that :/

**Comment by mavasani** [comment]
Can you try running unit tests with netcoreapp3.1 as the active project context instead of net472? Also try running from command line?

**Comment by Youssef1313** [comment]
Adding the following pkg ref to the unit tests project is also a possible workaround:

```xml
<PackageReference Include="Newtonsoft.Json" Version="9.0.0" NoWarn="NU1605;NU1603" />
```

**Comment by lflender** [comment]
Removing net472 from the target frameworks of the unit test projects does the trick, thanks
