### ISSUE TITLE
Dapr Asp.net core document is not explanatory. 

### ISSUE THREAD

**Issue by mrgopalakrishnan** [dotnet/docs#33735]
[Enter feedback here]
I followed the document to create Dapr based application. i'm not able to run the application successfully. i feel there are some more configurations missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by erjain** [comment]
Thanks for sharing the query here, we'll check it out and update you.

**Comment by erjain** [comment]
Hi @mrgopalakrishnan, I have tested the complete exercise and it is working fine for me, sharing the screenshot. Can you please share any further details of your issue, I mean at which step you are stuck, any logs will be helpful. Also, ensure dapr cli and runtime versions are the same. You can check dapr version using the command `dapr -v`. I hope you are following the installation instructions [Install Dapr into your local environment](https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started#install-dapr-into-your-local-environment). Thanks

**Comment by mrgopalakrishnan** [comment]
Hi @erjain ,
Thank you for the reply.  i think the issue is when i subscribe to a kafka topic which has key. Dapr is able to receive messages when there is no key written to the topic.

**Comment by erjain** [comment]
I'll be needing more information to help you, can you share at which step of the tutorial you are stuck, any logs will be helpful.

**Comment by erjain** [comment]
Hi @mrgopalakrishnan, Can you share more information on which step you are facing the issue in the tutorial?

**Comment by erjain** [comment]
Considering the original question is answered, we can close this issue now.
