### ISSUE TITLE
Why ValueTuple does not have a build in converter?

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/docs#33739]
Why ValueTuple does not have a build in converter? It is such a  common, basic and useful data type. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-core-3-1)
* Content Source: [docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@eiriktsarpalis Can you comment on this?

**Comment by eiriktsarpalis** [comment]
The elements on `ValueTuple` are fields, not properties. As such, you would need to enable the `JsonSerializerOptions.IncludeFields` flag to make serialization work for tuples. That being said, serializing tuples is not recommended, as it will produce JSON objects with the non-descript `Item1`, `Item2`, `Item3` property names. Consider using anonymous classes instead.

**Comment by RyanLiu99** [comment]
IMHO, non-descrip ItemX is fine.  And even better, just put Tuple items' value in an array like  https://github.com/neuecc/MessagePack-CSharp does.

Instead of 
```
 {
          "Item1": 1,
          "Item2": "I2"
 }
```
just serialize it to 

`[1, "I2"]. `

And if you have specific converters just for `ValueTuple<,,,>`, I don't think you need JsonSerializerOptions.IncludeFields. Or in other words, In the special purposed converter, it can force JsonSerializerOptions.IncludeFields to be true. 

There are so many build in converts, for bool, for Enum, for KeyValuePair, Char ... why dotNet not to have a build in converter for ValueTuple<,,,> while other Serializers do.

**Comment by eiriktsarpalis** [comment]
You might want to follow https://github.com/dotnet/runtime/issues/70352 tracking a similar request.
