### ISSUE TITLE
po

### ISSUE THREAD

**Issue by Kongpcmail** [dotnet/docs#33743]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 332d4357-1097-6085-f3c3-1d0aedc020fe
* Version Independent ID: 45ba6545-4d5b-000f-fd76-601cf936676e
* Content: [Interfaces - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces#176-interface-implementations)
* Content Source: [standard/interfaces.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/interfaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Kongpcmail 

It looks like this was opened by mistake. I'll close it. If there's more feedback, open a new issue, or add a new comment here.
