### ISSUE TITLE
Not for latest Orleans version

### ISSUE THREAD

**Issue by Expecho** [dotnet/docs#33745]
Seems like this is only applicable to the older Orleans , not v7. It isn't always clear in the docs and that makes it hard to navigate,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e987171-00a7-5cd4-8b0d-674e4e5415fb
* Version Independent ID: b75215a0-bb33-efe0-5eb4-8b0e1b35fa41
* Content: [Runtime monitoring and logs](https://learn.microsoft.com/en-us/dotnet/orleans/host/monitoring/)
* Content Source: [docs/orleans/host/monitoring/index.md](https://github.com/dotnet/docs/blob/main/docs/orleans/host/monitoring/index.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 62388](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62388)

**Comment by IEvangelist** [comment]
Hi @Expecho - you're correct. This needs to be updated and we'll make that a priority as soon as we are able. @bradygaster @ReubenBond
