### ISSUE TITLE
Orleans Streaming Overview: SMS is obsolete

### ISSUE THREAD

**Issue by jaredthirsk** [dotnet/docs#33749]
I'm pretty new to Orleans but my understanding is Simple Message Streams (SMS) is obsolete and gone as of Orleans 7.0 and replaced with BroadcastChannel.  This Overview mentions SMS twice, and BroadcastChannel zero times.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc887303-dda9-00ed-b6f0-a964b85b8a58
* Version Independent ID: 6fff91b1-2868-4364-ac0d-3d382c7b0538
* Content: [Streaming with Orleans](https://learn.microsoft.com/en-us/dotnet/orleans/streaming/)
* Content Source: [docs/orleans/streaming/index.md](https://github.com/dotnet/docs/blob/main/docs/orleans/streaming/index.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 89032](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89032)

**Comment by jaredthirsk** [comment]
@ReubenBond @IEvangelist @bradygaster

**Comment by IEvangelist** [comment]
Hi @jaredthirsk - you're correct. This needs to be updated, we'll work on fixing that soon. The quick start and other related content in this area use zones to differentiate between 7.0 and 3.x. The overview was missed in that edit pass.

**Comment by Rikarin** [comment]
This page also contains references of SMS for version 7.0
 https://learn.microsoft.com/en-us/dotnet/orleans/streaming/streams-programming-apis?pivots=orleans-7-0
