### ISSUE TITLE
System.Attribute.Match remarks and example are unclear

### ISSUE THREAD

**Issue by lambdageek** [dotnet/docs#3375]
The [remarks and example for `System.Attribute.Match(object)`](https://docs.microsoft.com/en-us/dotnet/api/system.attribute.match?view=netstandard-2.0#System_Attribute_Match_System_Object_) are very poor. 

I *think* what the example and remarks are suggesting is that `Match` may be used to equate two attributes that `System.Attribute.Equals(object)` would say aren't equal:  the `Match` method will return `true` on more pairs of attributes than `Equals` would. 

Issues:
1. That's really not what the remarks say.  The second paragraph is particularly confusing (more so because it seems to be suggesting an example but doesn't show any code and doesn't relate to the example that _is_ in the docs).

2. A good example would include `Equals` and `Match` implementations that sometimes return different values.

3. The example is confusing because `Equals` and `Match` have different implementations, but they in fact will always return the same value: either both `true` or both `false`.  It's not clear why the main loop in the example would choose to use `Match` over `Equals`.

4. The `Match` code is using poor coding style:  `if (expression) return true; else return false` is poor coding style - just replace it by `return expression;` (Likewise, `if (expr1) return true; else if (expr2) return true; else return false` is just `return (expr1 || expr2);`, and so forth.)  (This is, of course, subjective.  But it just adds to the confusion: why do `Equals` and `Match` implement the same calculation in two different ways?)

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @lambdageek. Both the documentation and the example could use improvement. 
The assumption here is that Equals should perform a standard test for reference or value equality, but Match should perform some custom comparison. The basic example is a good one, though it's unfortunate that the Equals and the Match methods perform identical comparisons, and the code is not at all efficient.

**Comment by lambdageek** [comment]
Thanks @rpetrusha 

> The assumption here is that Equals should perform a standard test for reference or value equality, but Match should perform some custom comparison. 

I wish this sentence _was_ the documentation. :+1:
