### ISSUE TITLE
SYSLIB1051 documentation is wrong

### ISSUE THREAD

**Issue by aelij** [dotnet/docs#33753]
This is the error I'm getting:

> SYSLIB1051	Runtime marshalling must be disabled in this project by applying the 'System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute' to the assembly to enable marshalling this type. The generated source will not handle marshalling of parameter 's'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9effd79-dc69-b250-965b-eb878b21a41b
* Version Independent ID: 3517eb7a-2f72-5941-d207-e2febee88306
* Content: [SYSLIB diagnostics for Microsoft.Interop.LibraryImportGenerator - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069)
* Content Source: [docs/fundamentals/syslib-diagnostics/syslib1050-1069.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/syslib1050-1069.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 82744](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82744)

**Comment by gewarren** [comment]
@elinor-fung It looks like there's a [bunch of different messages](https://github.com/dotnet/runtime/blob/1e1e86d34eee952c7c331bf002d928e0681942eb/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/GeneratorDiagnostics.cs#L62-L100) you can get for SYSLIB1051. Where is the "title" used, and should I be documenting these diagnostics differently on this page?

**Comment by elinor-fung** [comment]
I believe the title for diagnostics is only part the ID used when suppressing it in source and the (formatted) message is what is actually shown as the description. For the `*WithDetails` messages, it looks like we only include the detailed reason (in this case the runtime marshaling) a type is not supported, without the generic 'type is not supported by source-generated p/invokes' message.

@AaronRobinsonMSFT @jkoritzinsky maybe we should always have the generic issue in the message followed by the details?
