### ISSUE TITLE
is C# 10 for .Net-Framework possible

### ISSUE THREAD

**Issue by jk-ware** [dotnet/docs#33755]
[it is not finally clarified whether it is permissible to select a higher C# version than 7.3 for a .Net Framework project (e.g. C# 10).]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46e75de6-8d41-b986-5f95-67a1149c6d8c
* Version Independent ID: b75d77df-8629-28f8-bc46-b8bc1a4b8ab1
* Content: [Resolve errors related to language version and features](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/feature-version-errors?f1url=%3FappId%3Droslyn%26k%3Dk(CS8370))
* Content Source: [docs/csharp/language-reference/compiler-messages/feature-version-errors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/feature-version-errors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @jk-ware 

Using C# 10 with .NET Framework 4.8 isn't supported.  You can read more [here](https://learn.microsoft.com/dotnet/csharp/language-reference/configure-language-version).

I've opened a PR to add a link to that article.

**Comment by jk-ware** [comment]
Thank you Bill, for the straight answer!
