### ISSUE TITLE
XML examplecode

### ISSUE THREAD

**Issue by mijarena** [dotnet/docs#33754]
There should be a hint of how you can add example code written in XML so that it not will be parsed, as mentioned here "Although developers are free to create their own set of tags..."
Example: writing a class of parsing an XML file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74e905-523c-dae9-f741-af5e52785a9c
* Version Independent ID: c9b7c7a1-0584-b6e6-95cd-5276788fdda0
* Content: [Documentation comments - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments)
* Content Source: [standard/documentation-comments.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @mijarena 

There are examples in [this article](https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/examples).

We won't add these examples to the standard. However, upcoming changes will improve the navigation and make it easier to find the examples.

I'll close as not planned.

**Comment by mijarena** [comment]
That is not what I meant. Perhaps I didn' made myself clear enough.

I wrote an XML-File and a parser in LinqtoXML. Now I want to Document the code, so I need example XML inside my <example>-Tag.
I meant, how to mask XML inside an <example>-Tag. Is there a specific way or shall I just use: \<myxmltag\>.

I think, that how to mask should be part of the description, mayby I overread it, but I didn't found a hint about that.

**Comment by BillWagner** [comment]
Hi @mijarena 

Depending on what you want for the output, you'll pick one of two options:

1. If you want the *contents* of these elements in the output file as XML, just use `<myxmltag>`. 
2. If you want the final output to show the XML example, use a `CDATA` section in remarks so that the output contains formatted XML as an example.
