### ISSUE TITLE
`ISourceGenerator` will be deprecated and the article should be updated

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#33757]
`ISourceGenerator` interface is about to be deprecated soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @KathleenDollard

**Comment by Youssef1313** [comment]
`ISourceGenerator` related APIs were banned in https://github.com/dotnet/roslyn-analyzers/pull/6478
