### ISSUE TITLE
Where has command line arguments gone?

### ISSUE THREAD

**Issue by krisrajzlive** [dotnet/docs#33761]
Between, I searched everywhere and all over but still could not find command line arguments while running .net 6 console app in VS 2022?! Am I missing anything??

**Comment by gewarren** [comment]
@krisrajzlive Are you asking how to debug a console app with provided command-line arguments? If so, see https://learn.microsoft.com/en-us/visualstudio/debugger/debugging-preparation-console-projects?view=vs-2022#set-command-line-arguments.
