### ISSUE TITLE
No indication of the nodes required in the external file

### ISSUE THREAD

**Issue by sixeyes** [dotnet/docs#33768]
The page references an external file and shows how to link to it in the original file, but does not give an example of the root node and format required in the external file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf05d1a-3c6d-dc86-77ef-bd453f957a6c
* Version Independent ID: e40bd8c3-89af-b89b-2d3d-6f015d8704b7
* Content: [&lt;linkedConfiguration&gt; element - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/linkedconfiguration-element)
* Content Source: [docs/framework/configure-apps/file-schema/linkedconfiguration-element.md](https://github.com/dotnet/docs/blob/main/docs/framework/configure-apps/file-schema/linkedconfiguration-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@sixeyes I believe it's the same format as an app.config file. However, note that only the `<assemblyBinding>` information will be read from the linked file:

"The settings in included configuration files only affect loader binding policy and are used only by the loader. The included configuration files can have settings other than binding policies, but those settings don't have any effect."
