### ISSUE TITLE
Problems as Newbie to C#

### ISSUE THREAD

**Issue by Admiral-dk** [dotnet/docs#33795]
[I have tried to type this lesson into Visual Studio 2022.
Why - well to train the Brain to better remember the lessons. This is unfortunately rewarded with a - 
"CS5001 - Program does not contain a static 'Main' methode suitable for an entrypoint"
Have tried to copy paste all the posibillities shown under - "Main() and command-line arguments".
+ a number of other ideas - but to no solution that actually works :-( 
It would be nice if the otherwise great examples can run as is (some do) ]

edit by @BillWagner update article block based on comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 646641fc-f698-5633-5f6b-2eb5f0c03d7f
* Version Independent ID: c6e0d402-962e-4b6c-b1f4-4e91eb585692
* Content: [Create mixin types using default interface methods](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/mixins-with-default-interface-methods)
* Content Source: [docs/csharp/tutorials/mixins-with-default-interface-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/mixins-with-default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Admiral-dk 

I think I see what happened.  The first and second examples on this page are meant to be a single program. You'd need to type both of them to see the results.

Can you verify that I've found the right solution?

I'm glad you're using our material to learn C#. Thanks for reporting issues like this when you find them.

**Comment by Admiral-dk** [comment]
Hi Bill

Thank you for replying :-)
For one reasone or another I can't get back to yesterday from the links provided automaticly when I clicked the Feedback Button yesterday ...?
So I copied a line from Studio 2022 from what I was trying and got to the right place : 
[https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/mixins-with-default-interface-methods](url)
And as you can see - it is a lot more than two parts and most likely not what you are trying to help me with ....
None the less - if you have a pointer or two, to guide me towards a solution - I would be gratefull ;-)

Best wishes

Per                 aka Admiral_dk

**Comment by BillWagner** [comment]
Thanks @Admiral-dk 

That's a different article. I updated the document block to reflect that.
