### ISSUE TITLE
Remove out-of-date specification for C# language from Visual Studio install

### ISSUE THREAD

**Issue by gafter** [dotnet/docs#3381]
We are shipping an out-of-date specification for C# with Visual Studio. We should stop doing that and link to the online specification at https://github.com/dotnet/csharplang/blob/master/spec/README.md .

This is also tracked at https://github.com/dotnet/roslyn/issues/18515 and [tracked internally at 405168](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=405168&_a=edit). and [428131](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=428131&_a=edit).

**Comment by BillWagner** [comment]
@gafter We import that online spec here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/  

We're directly pulling in the master branch and the daily publish cycle will pull in any updates made to the csharplang repo.  I have a similar comment at [dotnet/roslyn#18515](/dotnet/roslyn/issues/18515)

**Comment by gafter** [comment]
@BillWagner Linking to that imported version makes a lot of sense.

**Comment by mairaw** [comment]
So is there any action item for us on the docs team here? Or should this be handled by the internal bug to have VS link to our new docs?

**Comment by mairaw** [comment]
Closing since this is being tracked internally and doesn't apply to docs.
