### ISSUE TITLE
Target-type new expressions missing here

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#33829]
Doesn't call out target-type new expression from C# 9: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

Would be nice to see articles updated and point to new language features as they're introduced. Generally have noticed this lacking in many cases. I generally only find information about the new languages features in the articles listing out the new language features and not the dedicated help topics that they extend/modify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdb964-4c04-d174-e879-e3a2d176809b
* Version Independent ID: 96df2e76-70b0-4873-4acc-d6bae51986b4
* Content: [new operator - Create and initialize a new instance of a type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator)
* Content Source: [docs/csharp/language-reference/operators/new-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/new-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 62109](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62109)

**Comment by BillWagner** [comment]
Thanks for pointing this out @michael-hawker 

In general, I have been updating the language reference to reflect the latest features. This one slipped by. I'll update it in the next sprint.

As you find other instances, create an issue so we fix those as well.

**Comment by BillWagner** [comment]
Closing as this was fixed in a preview PR.

**Comment by pkulikov** [comment]
@BillWagner @michael-hawker the article covers the target-typed new:
![image](https://user-images.githubusercontent.com/15279990/234694516-ec91a3bb-7b9a-4482-b89f-ef6a20a7b842.png)
