### ISSUE TITLE
A little mistake in code example.

### ISSUE THREAD

**Issue by AlejandroDePena** [dotnet/docs#33838]
[Enter feedback here]
You have a little bug in your code at the Tuple Use Case section (first snippet):

var min = int.MaxValue;
var max = int.MinValue; 

Min and max variable assignments are inverted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e533179-50e7-813d-be49-e1248134dd10
* Version Independent ID: 1778e921-76f6-32d5-4509-7bd944a01e0d
* Content: [Tuple types - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples)
* Content Source: [docs/csharp/language-reference/builtin-types/value-tuples.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @AlejandroDePena 

Thanks for reaching out.  The code sample is correct, but I can see where it's misleading.  I think the fix is to update it as follows:

```csharp
    // Initialize min to MaxValue so every value in the input 
    // is less than this initial value.
    var min = int.MaxValue;
    // Initialze max to MinValue so every value in the input
    // is greater than this initial value.
    var max = int.MinValue;
```

I've added this to our backlog and added the "Help Wanted" label if anyone wants to update it before we update this article.

**Comment by AlejandroDePena** [comment]
Yes, you are right Bill !!, I just look at this very quickly and misunderstood. 

I think the same as you, adding this comment avoids misleading.
