### ISSUE TITLE
Suggested code for "standard property syntax" is bad practice?

### ISSUE THREAD

**Issue by rawling** [dotnet/docs#33851]
The suggested code given for a "standard property syntax" record is:

    public record Person
    {
        public string FirstName { get; init; } = default!;
        public string LastName { get; init; } = default!;
    };

This feels like it's encouraging people to do something bad - create a class that you can happily just construct and, with no warning, will introduce `null`-valued non-nullable reference fields into your codebase.

(At first sight I thought it was being clever, that the `default!` would only be evaluated if no value was passed in an object initialiser, and that it would immediately throw a NRE because `default` is null, but apparently that's neither how `!` nor default property values work. [I'm also not the first person to be confused by this](https://github.com/dotnet/docs/issues/28413).)

Absent a null-checker warning for "you've not initialised these properties and by default they are illegal" at `new Person()` constructor sites, would it not be better either for the example to drop the default values and leave the `CS8618` warnings in to warn people or, at worst, to have legal but obviously default values in?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @rawling 

This should be updated to add the new `required` modifier. That would fix the loophole you're mentioning:

```csharp
public record Person
{
    public required string FirstName { get; init; } = default!;
    public required string LastName { get; init; } = default!;
};
```

Callers would be required to set a value for each property. Because `string` is non-nullable, that initial value couldn't be null.

**Comment by rawling** [comment]
Amazing, wasn't aware of that but it fills the gap nicely. Would the `= default!;` be necessary still or does `required` kill the warnings?

**Comment by BillWagner** [comment]
> Amazing, wasn't aware of that but it fills the gap nicely. Would the `= default!;` be necessary still or does `required` kill the warnings?

Yes, they can be removed.  Thanks. Better code would be:

```csharp
public record Person
{
    public required string FirstName { get; init; }
    public required string LastName { get; init; }
};
```
