### ISSUE TITLE
Last Language Design Team Link is broken

### ISSUE THREAD

**Issue by marwie** [dotnet/docs#33884]
It points to this url https://github.com/orgs/dotnet/teams/ldm which returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 184c9a5a-9ac4-895b-f388-1a96105cdfd6
* Version Independent ID: e9fe3f62-9cba-16cf-70c4-a9b77346932e
* Content: [C# language strategy](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/strategy)
* Content Source: [docs/csharp/tour-of-csharp/strategy.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/strategy.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 63432](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63432)

**Comment by BillWagner** [comment]
Thanks for reporting this @marwie 

We missed that. That page is only accessible for members of the dotnet GitHub org. I'll find an appropriate public link and update this.
