### ISSUE TITLE
Replace FwLinks with the actual target links

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3391]
This is a good issue for people who want to learn how to work on open-source projects.

Our content uses a lot of what we call FwLinks links. Current search brings 2,639 results for [FwLink](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=fwlink&type=) links.

The problem with those is that users have no clue to which site we're taking them if they hover the link with their mouse and also they can only be updated by employees. They were useful back in the day where we could only publish once every couple of weeks or sometimes even months. 

We should keep links to downloads intact though. 

For people interested in helping with this task, we'd break it down into much smaller issues (like 5-10 links per PR). 

Sub-issues:
- [x] Core and F# folders - #3423 
- [x] C# folder - #3424
- [x] Standard folder - #3425
- [ ] VB folder - #3426 
- [ ] Framework folder
- [ ] samples repo
- [ ] api repo

**Comment by svick** [comment]
2600 links sounds like way too many to do manually, especially at a rate of 10 links per PR. Wouldn't it make more sense to write a program that finds the links, accesses them to find out where they redirect and replaces them?

**Comment by xaviex** [comment]
@mairaw Working on this currently, When you say you want download links intact, does this mean that you want them to remain FWlinks? Also, are we considering download links anything at the download.microsoft domain or are we considering it anything that isn't a web page, such as http://example.com/testfile.exe?

**Comment by mairaw** [comment]
It's fine for folks more experienced or using automated scripts to do at a higher rate. 
Since we were targetting this one for new GitHub users, that's why I set the limit. Otherwise, it takes longer for us to review too.

Thank you for taking this on @xaviex. My suggestion is that even with a script, we break down the PRs by folder.
For example:
https://github.com/dotnet/docs/tree/master/docs/core
https://github.com/dotnet/docs/tree/master/docs/framework
etc.

For downloads, what I meant is for links that go to https://www.microsoft.com/en-us/download/details.aspx to be kept as FwLinks. I think that everything else can be changed to their regular links.

Let's start with the .md and .xml files (which is our API reference) and then we see if we wanna change the rest. 

Does that answer all your questions?

**Comment by xaviex** [comment]
This does answer a lot of them, and yea breaking down by folder will make things a bit easier on me too, any preference on starting folder? Also, What about any download.microsoft.com/download/ Links? Are we considering those downloads or just /en-us/download/details.aspx?

**Comment by xaviex** [comment]
@mariaw Also, As this is my first major push, are there any significant rules I should be following other than what is in the contributor guidelines?

**Comment by mairaw** [comment]
yes, let's keep those download.microsoft.com as FwLinks too. 

Start with the sub-folders within https://github.com/dotnet/docs/tree/master/docs. You can go in alphabetical order in there, so core, csharp, framework and so on. Would you like me to open sub-issues for these? 

No @xaviex. I think our contributor guidelines should contain all our rules. But I'm here to answer any questions you might have.

**Comment by xaviex** [comment]
If you could create those sub-issues that would be fantastic thank you!

**Comment by xaviex** [comment]
@mairaw Okay, I'm set up to do each folder, Do you want me to use issue numbers in commit summaries?

**Comment by xaviex** [comment]
@mairaw  I just realized that /core/ only has one location that actually needs to be changed, do we want that to be its own issue or no?

**Comment by mairaw** [comment]
@xaviex ok, let me create sub-issues. I'll create a combined one for core and fsharp then if it's just one. I'm guessing that both should have low numbers since they are newer content. 

You can add the Fixes notation in the PR only. No need to add the issue in the commit itself.

**Comment by xaviex** [comment]
@mairaw Will you add the sub-issues as checks inside this issue? Or should I watch out for them on the main issues page?

**Comment by mairaw** [comment]
I'm doing both @xaviex. So you can create PRs targetting a specific issue and resolve them. And I'll keep track of them here.

**Comment by mairaw** [comment]
I've opened 4 sub-issues so far. Let's see how they go. I might have to break down the framework folder in more parts since that folder will impact more than 1000+ files.

**Comment by xaviex** [comment]
@mairaw How do I go about making a pull request for the next issue before the current one is accepted?

**Comment by mairaw** [comment]
you need to work on different branches. just a sec

**Comment by xaviex** [comment]
My apologies on this.

**Comment by mairaw** [comment]
Never mind. I see that you closed the PR already. Do you want me to reopen that one or do you want to work on a branch different than master for your PR?

Here's my usual workflow:

To set up my local fork:
`git clone <fork url>`
`git remote add upstream https://github.com/dotnet/docs.git`

To start new work:
`git checkout master`
`git fetch upstream`
`git rebase upstream\master`
`git push`

`git checkout -b <working-branch-name>`

Then follow the usual commit, add, push, etc.

**Comment by pkulikov** [comment]
@mairaw csharp folder is cleaned and #3424 is closed, so the corresponding point might be checked in the checklist of this issue.

Meanwhile, #3425 (standard folder) should be reopened: I've found 58 entries with the PowerShell `@(Get-ChildItem -recurse | Select-String -pattern "fwlink").Count` call in **docs/standard** folder

**Comment by mairaw** [comment]
Thanks for your help on working through this issue @pkulikov. Done.

**Comment by pkulikov** [comment]
@mairaw it's time to check one more point in the issue message ✔️ - standard.

Let me take all the thanks you've given me for the work on this issue, square them up, and give them to you. That turned out to be a very good issue to work on: I've learnt the structure of the docs, which is definitely useful for improving them further (and navigating the website itself  😄 ), learnt the C# use-cases that I've never faced in my work and got better understanding of .NET. Also thank you for the reviews and feedback: they were also something to learn from.

**Comment by mairaw** [comment]
Woot woot! Done @pkulikov. Your help has been tremendous and I'm glad you're also having fun and learning in the process.

**Comment by ChrisMaddock** [comment]
I've been having a bit of fun scripting a solution to this. I'm working on the API repo - and initially targeting low-hanging fruit of fwlinks that forward directly to docs.microsoft.com anyway.

I'm doing one PR per-link for every link with 10 or more references - after which, I'll start submitting PRs of the rest all mixed together.

Hope that's helpful - I thought once the easy ones are out the way, then it will be easier to see what's left!

**Comment by eddynaka** [comment]
@mairaw i have one question: should we move all urls? or just Microsoft domain? For example:
https://github.com/dotnet/docs/blob/017fcebf974cb369ba8532f920dc3fc4ed0deed6/docs/framework/wcf/feature-details/web-services-protocols-interoperability-guide.md

We have the link: https://go.microsoft.com/fwlink/?LinkId=90372
Which redirects to this: http://www.rfc-editor.org/rfc/rfc2616.txt

Should we update?

Thanks!

**Comment by mairaw** [comment]
Yes, we've been updating those too.
