### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by yozsoy** [dotnet/docs#33918]
[Enter feedback here]

AnotherObject x = new AnotherObject();
x.Field3 = "zzz";
new {field1 = "xxx",field2 = "yyy", x}
What happens now? Why dont you add this info to this page? Where do i find this info otherwise?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b30ebe-b640-449b-3602-9891a55794db
* Version Independent ID: dd937177-98f0-a797-d49b-29332aae0614
* Content: [Anonymous Types](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/anonymous-types)
* Content Source: [docs/csharp/fundamentals/types/anonymous-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/anonymous-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @yozsoy 

In that example, the new anonymous type would have a field named `x` of type `AnotherObject`. 

We should add an example where one of the fields of an anonymous type is a user-defined type.

I've added this to our backlog, and added the "help-wanted" label, in case anyone wants to add an example before we update this article.

**Comment by BartoszKlonowski** [comment]
@BillWagner Let me work on this.
