### ISSUE TITLE
Update code snippet for IDE0032

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/docs#33927]
Hello there!

Perhaps, it's more consistent to make `Age` property `public` in both case in this example:
```
// dotnet_style_prefer_auto_properties = true
private int Age { get; } // <- CHANGE THE PROPERTY ACCESS MODIFIER TO PUBLIC

// dotnet_style_prefer_auto_properties = false
private int age;

public int Age
{
    get
    {
        return age;
    }
}
```  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63bccb20-3208-b4e5-dba5-41c3861f00a9
* Version Independent ID: cf4d5048-0b53-4617-c14a-9848edbe1844
* Content: [IDE0032: Use auto property - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0032)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0032.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0032.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks @MaximLipnin, you're right!
