### ISSUE TITLE
Issue with example in Namespaces module

### ISSUE THREAD

**Issue by mann-codes2014** [dotnet/docs#33923]
The text for the second example is giving glimpse that the following code example will show something different. But it's the same as the first one, just a different naming convention.
![image](https://user-images.githubusercontent.com/97145056/217579444-e86db81b-7677-4500-a10d-7da201ada0f7.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 176f6e77-fdd7-5f97-feb3-5376c85baa5a
* Version Independent ID: fc865789-6896-4cf5-7cdf-2080047563e4
* Content: [Organizing types in namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/namespaces)
* Content Source: [docs/csharp/fundamentals/types/namespaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I agree @mann-codes2014 

I've added this to our backlog, and added the "help wanted" label to this issue.

**Comment by mann-codes2014** [comment]
@BillWagner Shall I close this now?
