### ISSUE TITLE
Error correction

### ISSUE THREAD

**Issue by wh185058** [dotnet/docs#33920]
This states "The HKEY_LOCAL_MACHINE\SOFTWARE\[Wow6432Node\]Microsoft\.NETFramework\<VERSION>: SchUseStrongCrypto registry key has a value of type DWORD. A value of 1 causes your app to use strong cryptography. The strong cryptography uses more secure network protocols (TLS 1.2, TLS 1.1, and TLS 1.0) and blocks protocols that are not secure. "

My understanding is that this actually disables TLS 1.0 and forces the use of 1.1 and 1.2, since 1.0 has documented vunerabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
I believe you are right. The list of insecure TLS versions is growing. Isn't TLS 1.1 on that list as well now?
The list is defined by Windows, not by .NET. SO it may in theory different on different Windows versions.
It would be great if we can verify it is true - either by cross-checking Windows support matrix, or by running a small test. Then we could update the text.

That said, I don't mind if we remove TLS 1.0 from the list of examples right away without any testing ...

**Comment by wh185058** [comment]
In terms of testing, I will say when I have a client defaulting to TLS 1.0, I set this registry setting to get them to start using TLS 1.2 so they can talk w/our servers.
