### ISSUE TITLE
Azure Storage grain persistence doesn't reflect v7

### ISSUE THREAD

**Issue by michaelmcneilnet** [dotnet/docs#33931]
`options.UseJson = true;` does not exist in the v7 package. It looks as if we have to set `options.GrainStorageSerializer` now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd8de8c2-2a25-f82b-178c-2efed42937bd
* Version Independent ID: 9f5a11d1-ede8-f77b-0e01-faeb47059935
* Content: [Azure Storage grain persistence](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/azure-storage)
* Content Source: [docs/orleans/grains/grain-persistence/azure-storage.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/grain-persistence/azure-storage.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by ReubenBond** [comment]
Fixed in https://github.com/dotnet/docs/pull/33933
