### ISSUE TITLE
Turn some of the "Source generator cookbook" into official documentation

### ISSUE THREAD

**Issue by Eli-Black-Work** [dotnet/docs#33936]
On https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview, it says "The [Source Generators Cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md) goes over some of these examples with some recommended approaches to solving them."

I recently finished writing a source generator, and the Source Generators Cookbook was incredibly valuable 🙂

I'd like to ask that some of the Source Generators Cookbook be turned into official documentation on https://learn.microsoft.com/

In particular, I found these parts to be very helpful:
* [Use functionality from NuGet packages](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#use-functionality-from-nuget-packages)
* [Consume MSBuild properties and metadata](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#consume-msbuild-properties-and-metadata)
* [Issue Diagnostics](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#issue-diagnostics)

Thanks! 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @KathleenDollard 

This is the direction we're heading toward.
