### ISSUE TITLE
Sort message codes

### ISSUE THREAD

**Issue by Akaitatsu** [dotnet/docs#33946]
Please sort the CS#### codes at the beginning of the article. It will make finding a specific code much easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 812f0144-80de-6b49-dded-97eeb7bc373d
* Version Independent ID: df58b52a-2532-8241-72cd-f40e9096037d
* Content: [Resolve nullable warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings)
* Content Source: [docs/csharp/language-reference/compiler-messages/nullable-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/nullable-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good idea @Akaitatsu 

I've added this to our backlog, and added the "help wanted" label in case anyone wants to submit a PR before we get to this update.

**Comment by BartoszKlonowski** [comment]
Alright, let me sort them.
