### ISSUE TITLE
VB Strategy doc feedback

### ISSUE THREAD

**Issue by mrange** [dotnet/docs#33940]
Hello. 

When reading the VB strategy doc I felt something important missing.

I have no problems with VB being a more stable language than say C#.

However, I think it's important that VB can consume APIs from C# and F# especially for features that is expected to have a wide impact such as `required` members.

In addition; I have struggled in past with Unsafe APIs such as ImageSharp and VB. While not being critical to write unsafe code in VB IMHO (and possible this even a benefit for VB) I think consuming unsafe APIs makes sense even in VB.

So what I felt was missing from the strategy for VB was a goal to let VB consume most if not all of C# and F# APIs/ABIs.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58d6da49-a963-5f83-ccce-284cd3d5615b
* Version Independent ID: 0539139d-2c47-71e7-a2c4-bad405c7efbd
* Content: [Visual Basic language strategy - Visual Basic](https://learn.microsoft.com/en-gb/dotnet/visual-basic/getting-started/strategy)
* Content Source: [docs/visual-basic/getting-started/strategy.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/getting-started/strategy.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for the note and clarification @mrange 

Yes, you did interpret the "consumption only" approach correctly.

We are in the process of having these new articles translated into all the languages supported on the platform. If the translation doesn't capture the spirit correctly, let us know.
