### ISSUE TITLE
Azure Storage grain persistence - Show example of configuring JSON serializer for Orleans v7

### ISSUE THREAD

**Issue by michaelmcneilnet** [dotnet/docs#33943]
The API for `AddAzureBlobGrainStorage` is different in Orleans v7, and an example of how we now set JSON settings such as `TypeNameHandling` would be good.

I think we could do something like 

```cs
siloBuilder.Configure<OrleansJsonSerializerOptions>(options =>
{
    options.JsonSerializerSettings.TypeNameHandling = TypeNameHandling.Auto;
})
```

but I think that will have repercussions on JSON serialization across Orleans, rather than just for blob storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd8de8c2-2a25-f82b-178c-2efed42937bd
* Version Independent ID: 9f5a11d1-ede8-f77b-0e01-faeb47059935
* Content: [Azure Storage grain persistence](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-persistence/azure-storage)
* Content Source: [docs/orleans/grains/grain-persistence/azure-storage.md](https://github.com/dotnet/docs/blob/main/docs/orleans/grains/grain-persistence/azure-storage.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 149985](https://dev.azure.com/msft-skilling/Content/_workitems/edit/149985)

**Comment by ReubenBond** [comment]
Here is a potential solution to this. You can customize the options used by the grain storage serializer on a per-storage basis by registering a serializer using the storage name:

```csharp
services.AddSingletonNamedService<IGrainStorageSerializer>(
    "my-storage-name",
    (sp, key) =>
    {
        var options = new OrleansJsonSerializerOptions();
        options.JsonSerializerSettings.TypeNameHandling = TypeNameHandling.Auto;
        return new JsonGrainStorageSerializer(new OrleansJsonSerializer(Options.Create(options)));
    });
```

cc @benjaminpetit
