### ISSUE TITLE
Incomplete tutorial

### ISSUE THREAD

**Issue by superichmann** [dotnet/docs#33942]
The webpage explains how to save and load `dataPrepPipeline` and `trainedModel` but ends after their loading. I am trying to implement the code after they are loaded and actually use **BOTH** of the `dataPrepPipeline` and `trainedModel` to predict but I cannot find any resource explaining how to do that and encountering errors.

Perhaps you can extend this article so that it would explain how to actually predict with the `dataPrepPipeline` and `trainedModel` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 784daf15-838b-a41d-98f3-779ac307745f
* Version Independent ID: ddc8c98a-f8f8-f35b-0677-4c8f77c54236
* Content: [Save and load trained models - ML.NET](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @superichmann,

Thanks for raising this issue. Here is a guide on how to use your model to make predictions. 

https://learn.microsoft.com/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net

Let us know if you still run into issues.
