### ISSUE TITLE
Remove “experimental” suffix for EnforceCodeStyleInBuild functionality

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#33956]
Thanks! We also need to get the documentation updated for this, I’ll file a tracking issue on docs repo.

_Originally posted by @mavasani in https://github.com/dotnet/project-system/pull/8846#pullrequestreview-1292335843_

**Comment by mavasani** [comment]
@gewarren

**Comment by gewarren** [comment]
Related to #29003.
