### ISSUE TITLE
No runtime target mention

### ISSUE THREAD

**Issue by JustinAtSama** [dotnet/docs#33967]
I see no mention of what .Net version or Runtime target supports default interface implementation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e26a623c-ade0-8630-2447-c526cf8ac3aa
* Version Independent ID: cc560dac-f9d5-06b0-0851-1ba48e860582
* Content: [Safely update interfaces using default interface methods in C#](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions)
* Content Source: [docs/csharp/tutorials/default-interface-methods-versions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/default-interface-methods-versions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @JustinAtSama 

Default interface implementation was released in C# 8, and .NET Core 3.0. 

In general, the articles should mention the first available implementation when that is one of the last three releases (C# 9 - C#11 at this time). Do we need to extend that guideline? 

In general, I want to avoid describing every feature by version. That would make it difficult for developers learning C# as a new language now. However, I know there are reasons to note when features are newer. How far back do you think we should go? Why?
