### ISSUE TITLE
Equality check would be better clarified

### ISSUE THREAD

**Issue by macias** [dotnet/docs#33987]
[Enter feedback here]
Quotes:

> if they are of the same type and store the same values.

> the synthesized equality methods check all properties 

> The synthesized GetHashCode method uses the GetHashCode method from all properties and fields 

It would be really beneficial if this was straighten up and described what is really compared. Fields only? Fields and properties (what about case with backing field, do property and corresponding field are checked, in sense it would be double checked)? Please note property does not have to correspond to stored value, it could provide computed value on fly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record?source=recommendations)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good points @macias 

The discussion on equality should clarify that *fields* are compared. All fields are compared, including those that are compiler generated backing fields for auto-implemented properties. 

I've added this to our backlog, and added the "help-wanted" label if anyone wants to submit a PR before we make the next update.

**Comment by macias** [comment]
@BillWagner thank you. In my opinion phrase "all fields are used (including those that are compiler generated backing fields for auto-implemented properties) both for equality comparison and computing hash code" is clear, and sufficient. For a "safety" measure I would suggest putting this (or similar) statement only once, because as practice shows, when it is repeated it has tendency to change the wording.
