### ISSUE TITLE
IsNullOrWhiteSpace for null string

### ISSUE THREAD

**Issue by andreasbuykx** [dotnet/docs#33992]
This page has the following sentence:

> You apply attributes to inform the compiler that message is not-null if and only if IsNullOrWhiteSpace returns false. 

This statement to me appears not to be correct: if the string contains whitespace or is empty it is not null but the function will return true. Maybe what is meant is that message is 'guaranteed not-null', or 'not maybe-null'?

Kind regards,
Andreas 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @andreasbuykx 

The language here could be tightened up a bit.  We should state the following:

> When `IsNullOrWhitespace` returns `false`, the *null-state* of the string is *not-null*. When `IsNullOrWhitespace` returns `true`, the *null-state* isn't changed. 

I've added this to our backlog to fix, and added the "help wanted" label if anyone wants to submit a PR before we make the update.
