### ISSUE TITLE
dotnet-publish docs missleading

### ISSUE THREAD

**Issue by iksi4prs** [dotnet/docs#33993]
**Issue description**

Documentation of **publish** includes explanation of how to use -p with **PublishProfile** and **PublishProfileFullPath** 

**Target framework**

dotent 6

<details>
<summary><strong>dotnet --info output</strong></summary>
Version:   6.0.402
</details>

Despite what the docs say, these args don't work and are ignored.
My suggestion, if you think this is a bug in sdk/took that you think one day will be fixed,
(I doubt because there issues that are quite old)
at least add comment in docs, that says "despite what is said here in docs, there's a bug in the tool and these don't work.",
so people will know it doesn't work, and won't count on the docs, until it fixed.

These are docs:
https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

Issues related to docs:
https://github.com/dotnet/docs/issues/19677
https://github.com/dotnet/docs/pull/19685

Issues related to sdk:
https://github.com/dotnet/sdk/issues/12490
https://github.com/dotnet/sdk/issues/20931

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 63804](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63804)

**Comment by tdykstra** [comment]
@vijayrkn
We currently say this in the `dotnet publish` doc:

> You can also set publish-related properties by referring to a *.pubxml* file. For example:
>
> ```dotnetcli
> dotnet publish -p:PublishProfile=FolderProfile
> ```
>
> The preceding example uses the *FolderProfile.pubxml* file that is found in the *\<project_folder>/Properties/PublishProfiles* folder. If you specify a path and file extension when setting the `PublishProfile` property, they are ignored. MSBuild by default looks in the *Properties/PublishProfiles* folder and assumes the *pubxml* file extension. To specify the path and filename including extension, set the `PublishProfileFullPath` property instead of the `PublishProfile` property.

I can add this:

> In the *.pubxml* file:
>
> `PublishUrl` is used by Visual Studio to denote the Publish target.
> `PublishDir` is used by the CLI to denote the Publish target.
>
>If you want the scenario to work in all places, you can initialize both these properties to the same values in the *.pubxml* file. When [dotnet/sdk#20931](https://github.com/dotnet/sdk/issues/20931) is resolved only one of these properties will need to be set.

But there are apparently other outstanding issues or bugs -- what should we say about them in the `dotnet publish` article?

**Comment by vijayrkn** [comment]
> But there are apparently other outstanding issues or bugs -- what should we say about them in the `dotnet publish` article?

If both the Propeties are set, the scenario should work for the customer. I am not aware of any scenarios where setting both these won't work.

**Comment by tdykstra** [comment]
@iksi4prs Thanks for reporting this issue, and @vijayrkn thanks for your help!

**Comment by vchakravarthula** [comment]
This is still not working for me (I mean I dont see my solution published in output folder).

I'm using below command 

dotnet publish .\mysolution.csproj /p:PublishProfile=.\mysolution\Properties\PublishProfiles\FolderProfile.pubxml
Tried this too:
dotnet publish .\mysolution.csproj /p:PublishProfileFullPath=.\mysolution\Properties\PublishProfiles\FolderProfile.pubxml

but no luck.

Here's my .pubxml

<?xml version="1.0" encoding="utf-8"?>

<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PublishDir>..\output\publish\AzCleanupCore</PublishDir>
	<PublishUrl>..\output\publish\AzCleanupCore</PublishUrl>
  </PropertyGroup>
</Project>


What am I missing here ?

**Comment by vijayrkn** [comment]
> What am I missing here ?

When you pass the publishProfile property, it will always look for the profile under `Properties\PublishProfiles` folder. If you want to pass the full path, you can use this property instead `PublishProfileFullPath`: 

https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportPublishProfile.targets#L20

**Comment by vijayrkn** [comment]
Just saw that you mentioned  that you tried `PublishProfileFullPath` as well. Can you pass in the absolute path and see if it makes a difference?

If not, if you can pass `/bl` and share the binlog, I can take a look. Thanks

**Comment by vchakravarthula** [comment]
I tried passing in absolute path but still no luck.

for binlogs, do you mean we need to pass as below ?
dotnet publish .\mysolution.csproj /p:PublishProfileFullPath=.\mysolution\Properties\PublishProfiles\FolderProfile.pubxml /bl

I tried, but I dont see any logs

**Comment by vijayrkn** [comment]
The above example is still the relative path to the pubxml. I meant the full path starting from the root directory to see if it is an issue with how we compute the relative path. 

Regarding the binlog, it should have created a file in the directory where you ran the command. It may have sensitive data. Please make sure to clean it up before uploading them publicly or you can upload it to a private share and I can request access.

**Comment by vchakravarthula** [comment]
Thanks much @vijayrkn for helping me.

What I missed is dotnet.exe. (Just dotnet didnt work and may be not identified what to do with publish)
Instead of this
dotnet publish .\mysolution.csproj /p:PublishProfileFullPath=.\mysolution\Properties\PublishProfiles\FolderProfile.pubxm

I need to mention
dotnet.exe publish .\mysolution.csproj /p:PublishProfileFullPath=.\mysolution\Properties\PublishProfiles\FolderProfile.pubxm

We can close this thread here
