### ISSUE TITLE
Glossary link on Docker terminology page does not go anywhere

### ISSUE THREAD

**Issue by balachir** [dotnet/docs#3402]
I was reading through this page [Docker terminology](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-terminology)

The link to "glossary" in the first para does not go anywhere
For further definitions, see the extensive glossary provided by Docker .

**Comment by mairaw** [comment]
Thank you @balachir for reporting the issue. I've opened a PR to fix it.

**Comment by balachir** [comment]
Great, thanks for the quick response!
