### ISSUE TITLE
Update deployment of .NET for Spark to Databrick with Delta lake support

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/docs#34025]
Recently (Nov 2022) an attempt was made to deploy .NET for Spark to Databrick and errors were reported

[Running a job with ForeachBatch under Databricks](https://github.com/dotnet/spark/issues/1114)

It would be great to have a tutorial how to do the above task using the latest Delta nuget; [Microsoft.Spark.Extensions.Delta 2.1.1](https://www.nuget.org/packages/Microsoft.Spark.Extensions.Delta/2.1.1)  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d09d9935-2cc4-e579-dd1e-120569030ccd
* Version Independent ID: 3a4307d6-10e4-546e-9cf5-ad59b62ea8f1
* Content: [Deploy a .NET for Apache Spark application to Databricks](https://learn.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment)
* Content Source: [docs/spark/tutorials/databricks-deployment.md](https://github.com/dotnet/docs/blob/main/docs/spark/tutorials/databricks-deployment.md)
* Product: **dotnet-spark**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta* =>

**Comment by gewarren** [comment]
We're no longer updating the .NET for Apache Spark documentation, and have archived it to https://learn.microsoft.com/previous-versions/dotnet/spark/what-is-spark. As a result, we're closing all the active .NET for Apache Spark issues. I'm sorry we couldn't address your issue.
