### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by zippy72** [dotnet/docs#34027]
The message at the top of the page is the same as the one for NETSDK1080. If I'm right, the actual error is trying to tell me I'm missing a reference to something, rather than having a reference I don't need? It's very confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6280ced1-08b7-ca6d-31b6-03a3b35278ce
* Version Independent ID: 2eb5a7e4-5a0e-290e-ec8a-b7cec5257ab5
* Content: [NETSDK1082: There was no runtime pack available - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1082?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1082)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1082.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1082.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 64154](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64154)

**Comment by Rick-Anderson** [comment]
NETSDK1080 warns you that the PackageReference element for Microsoft.AspNetCore.App in your project file is not necessary

That's different than 1082.

**Comment by zippy72** [comment]
That was my point. The error message for 1080 was used as the headline on the page for 1082, making the page for 1082 confusing.

**Comment by tdykstra** [comment]
@zippy72 Thanks for reporting that error. The H1 heading from 1080 was accidentally copied to 1082.
