### ISSUE TITLE
Verbiage improvement

### ISSUE THREAD

**Issue by syntaxartisan** [dotnet/docs#34037]
Would it make more sense to replace "a method call made to the delegate" with "a method call assigned to the delegate"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5dba5b-eabc-8202-2854-6b1f4a7f971a
* Version Independent ID: 8b2e46f0-6d12-6ce9-944d-b883dcbe0808
* Content: [Using Delegates - C# Programming Guide](https://learn.microsoft.com/en-US/dotnet/csharp/programming-guide/delegates/using-delegates)
* Content Source: [docs/csharp/programming-guide/delegates/using-delegates.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/using-delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @syntaxartisan 

I think a better phrase would be "invoking the delegate". What do you think?

**Comment by syntaxartisan** [comment]
I'm not sure but I don't think that's right. I don't think that the delegate has been invoked yet because it needs to be passed to the method first. It's the calling method that will invoke the delegate. At least that's how I understand it.

**Comment by BillWagner** [comment]
It is correct that this is invoking the delegate. But, the problem is that this paragraph is defining what that means.  Let's try this rewrite instead:

> A delegate object is normally constructed by providing the name of the method the delegate will wrap, or with a [lambda expression](../../language-reference/operators/lambda-expressions.md). Once a delegate is instantiated in this manner it can be *invoked*. Invoking a delegate calls the method attached to the delegate instance. The parameters passed to the delegate by the caller are passed to the method, and the return value, if any, from the method is returned to the caller by the delegate. For example:

**Comment by syntaxartisan** [comment]
I think I understand what the original paragraph was trying to say now. I think what was confusing me was the statement "by the delegate to that method". I was expecting the explanation to include a description of how a callback situation would play out but callbacks hadn't been explained yet. So I wasn't sure which method the description was referring to.

I'm not sure which one I like better, the original or yours.
