### ISSUE TITLE
Vote ended

### ISSUE THREAD

**Issue by Hekkaryk** [dotnet/docs#34126]
Statement
> Add an up or down vote in [GitHub issue #27420](https://github.com/dotnet/docs/issues/27420) to let us know if you support the use of this feature in project templates.  

is defunct, linked discussion was closed and further votes are impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6+ - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 64145](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64145)

**Comment by tdykstra** [comment]
@Hekkaryk Thanks for reporting that. I'm removing that link.
