### ISSUE TITLE
Add apt preferences to prevent conflicts with ubuntu base directories (may apply to other distros using apt as well)

### ISSUE THREAD

**Issue by kitingChris** [dotnet/docs#34149]
Add a new preference file in /etc/apt/preferences.d/dotnet to prioritise packages from microsoft for dotnet and aspnet

```bash
sudo sh -c "cat > /etc/apt/preferences.d/dotnet <<'EOF'
Package: dotnet*
Pin: origin packages.microsoft.com
Pin-Priority: 1001
EOF"
sudo sh -c "cat > /etc/apt/preferences.d/aspnet <<'EOF'
Package: aspnet*
Pin: origin packages.microsoft.com
Pin-Priority: 1001
EOF"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @kitingChris this issue slipped through the cracks. Sorry about that. We did some major updates to the ubuntu article and the related troubleshooting article. I think this is well covered now. Thanks for the suggestion!

**Comment by ElanHasson** [comment]
The whole two repositories thing is confusing. If you're using the deb for the ubuntu installation from the microsoft feed, it should really create an apt.preferences file. If you follow the instructions on a fresh install you can't even get the sdk installed. Very frustrating.
