### ISSUE TITLE
set gcServer in asp.net MVC5 (non core)

### ISSUE THREAD

**Issue by omuleanu** [dotnet/docs#34159]
Does the code specified in this doc page apply to old ASP.net MVC 5 (non core) websites ?
I don't see anywhere `web.config` to be mentioned only `app.config`

I tried setting `<gcServer enabled="false" />` in `web.config` and it doesn't seem to be having any effect.

on asp.net core when I set it (in the csproj file) to false, my appPool goes from 200MB memory usage to 7MB.
on MVC5 with `<gcServer enabled="false" />` in web.config nothing changes.

There's others on SO that have asked the same, and nobody seems to know:
https://stackoverflow.com/questions/64093273/gcserver-enabled-false-not-working-on-asp-net-mvc-5
https://stackoverflow.com/questions/60450596/how-to-disable-server-gc-in-asp-net-framework-app-running-on-azure-app-service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95249f95-dd1e-c3e2-032a-2c91057c50d4
* Version Independent ID: 5363faee-3808-d011-d371-c48a95dcabf0
* Content: [Garbage collector config settings - .NET](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector)
* Content Source: [docs/core/runtime-config/garbage-collector.md](https://github.com/dotnet/docs/blob/main/docs/core/runtime-config/garbage-collector.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Rick-Anderson Do you know how to disable server garbage collection on ASP.NET MVC5 apps?

**Comment by Rick-Anderson** [comment]
use environment variables.

**Comment by omuleanu** [comment]
@Rick-Anderson 
DOTNET_gcServer = 0
to turn off server GC, is this correct ?
