### ISSUE TITLE
Update tutorial to use the new .NET Upgrade Assistant VS extension for incremental migration to ASP.NET Core

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#34164]
This tutorial is currently based on the .NET Upgrade Assistant CLI. It should instead use the new .NET Upgrade Assistant VS extension: https://devblogs.microsoft.com/dotnet/upgrade-assistant-now-in-visual-studio/.

This tutorial should also link to the ASP.NET Core migration docs: https://learn.microsoft.com/aspnet/core/migration/proper-to-2x

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55d57d2a-269e-1efe-a437-77655d075c00
* Version Independent ID: 2b7dd581-95e2-3985-b5d3-0a8899dbc97c
* Content: [Upgrade ASP.NET MVC apps to .NET 6 - .NET Core](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-aspnetmvc)
* Content Source: [docs/core/porting/upgrade-assistant-aspnetmvc.md](https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-aspnetmvc.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **dotnetcontent**

---
[Associated WorkItem - 72552](https://dev.azure.com/msft-skilling/Content/_workitems/edit/72552)

**Comment by Rick-Anderson** [comment]
@adegeo this is fairly high priority, let me know if I can help. cc @tdykstra

**Comment by Rick-Anderson** [comment]
@adegeo  either @tdykstra  or @Rick-Anderson will do this update.
