### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by jiazengcindy** [dotnet/docs#34175]
![image](https://user-images.githubusercontent.com/95729303/219999113-19cf24c8-0e6d-4aed-9a1c-cbb349d0da80.png)
![image](https://user-images.githubusercontent.com/95729303/219999160-6b65e678-a24f-44e8-9c90-c1f76cd3d3fe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 672e69a1-80bb-87cd-b3b8-bf104d8aa89e
* Version Independent ID: 1c66477a-2a97-4eff-1cd8-937f4e7880a0
* Content: [Compiler Error CS0120](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120?f1url=%3FappId%3Droslyn%26k%3Dk(CS0120))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0120.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0120.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @jiazengcindy 

I've opened a PR for this issue.

In the future, if you find other similar issues in these articles, you can submit a PR by clicking on the edit button (it looks like a pencil). That may save time compared to writing a detailed issue.
