### ISSUE TITLE
c#

### ISSUE THREAD

**Issue by bright401** [dotnet/docs#34181]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f114ca64-2134-9aea-ad5f-db480ff4e521
* Version Independent ID: b3b390b3-fdcc-afef-2b17-550c59804854
* Content: [Compiler Error CS1002](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1002?f1url=%3FappId%3Droslyn%26k%3Dk(CS1002))
* Content Source: [docs/csharp/misc/cs1002.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1002.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @bright401 

Did you have a question on this article?
