### ISSUE TITLE
using System.Object;  

### ISSUE THREAD

**Issue by halis1964** [dotnet/docs#34180]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83784b67-2f12-e677-8791-6e014986365c
* Version Independent ID: 75d03e34-ccd4-1f16-7f02-6e231c5896d3
* Content: [Compiler Error CS0138](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0138)
* Content Source: [docs/csharp/misc/cs0138.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0138.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @halis1964 

Did you have a question on this article?
