### ISSUE TITLE
EnableWindowsTargeting does not work well for building WinApps in linux

### ISSUE THREAD

**Issue by ali50m** [dotnet/docs#34197]
Hi Team,

I am trying to build and publish my WPF(.net7-windows) through the github action pipeline. After reading this blog, I find **EnableWindowsTargeting** can be used for build Windows App on a linux machine.

However, after publishing the app in **ubuntu-latest** runner and run it, I find there is a unwanted console output window after my app is lauching. It does not act like the building artifact from windows machine.

I also tried publish the app on ther linux machines and found the same behavior. The console output window is annoying.

You can also see this issue in this [blog](https://www.ruyut.com/2022/08/linux-publish-winform.html).

Please kindly let me know if there is any other properties need to combine with **EnableWindowsTargeting** for building a WPF app in linux, or it is a bug?

BTW, the windows runner for github action is really slow, and expensive, comparing to ubuntu runner. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b07d5584-04d1-9972-c2d6-ffaa3cf5512a
* Version Independent ID: 5aa55844-314a-2c33-4cdc-b9e1de62e029
* Content: [NETSDK1100: Set the `EnableWindowsTargeting` property to true - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1100)
* Content Source: [docs/core/tools/sdk-errors/netsdk1100.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1100.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 69434](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69434)

**Comment by abitzer** [comment]
I have the same issue on .NET 6.0.
It seems the PE Header of the executable "states:
- "User Interface" : "Windows console" rather than "Windows GUI"
- In addition the file information like e.g. File Version, Company Name, ... are missing

**Comment by marcpopMSFT** [comment]
Adding @dsplaisted who did that feature. I think the extra window comes from the apptype being winexe though I'm not sure why it would behave differently when built on windows versus linux.

**Comment by abitzer** [comment]
I think this could be a side effect of: https://github.com/dotnet/runtime/issues/3828

**Comment by dsplaisted** [comment]
> I think this could be a side effect of: [dotnet/runtime#3828](https://github.com/dotnet/runtime/issues/3828)

That's correct.  Currently `EnableWindowsTargeting` is more meant to allow you to check that your Windows-targeted code compiles correctly, so you can make changes on Mac OS or Linux and not have to worry as much about whether you've broken the Windows build.

For actually producing the app that will be shipped, you still should generally do that from a Windows OS.  Fixing https://github.com/dotnet/runtime/issues/3828 would be a good step, but even if we do that there might be other issues that prevent the output from a non-Windows build from being the same as when building on Windows.

**Comment by dsplaisted** [comment]
@tdykstra Per the discussion here, it would be good to update the [docs for EnableWindowsTargeting](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablewindowstargeting) to include something like this:

> NOTE: This property is currently recommended to allow development on non-Windows platforms.  The final application that is released should still be built on Windows.  When building on a non-Windows platform, the output may not be the same as when building on Windows.  In particular, the executable will not be marked as a Windows application (which means that it will always launch a console window) and won't have an icon embedded.

**Comment by alexrp** [comment]
Note that this needs to be revisited after:

* https://github.com/dotnet/runtime/pull/89303
* https://github.com/dotnet/sdk/pull/34394
