### ISSUE TITLE
Compiler error code has digits transposed

### ISSUE THREAD

**Issue by martincook3** [dotnet/docs#34237]
I believe that the reference to 
> CS0301, "The name '_' doesn't exist in the current context"

needs to be to [CS0103](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103?f1url=%3FappId%3Droslyn%26k%3Dk(CS0103)).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ace3d2c-a7f7-c667-5f50-b8d8f1dfc87a
* Version Independent ID: 6edd2f85-a04b-e9ad-2fc9-fc23dbfc5bba
* Content: [Discards - unassigned discardable variables](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards)
* Content Source: [docs/csharp/fundamentals/functional/discards.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @martincook3 

I've opened a PR to address this.

When you find grammar issues like this, you can click the edit button to open a PR. It looks like a pencil. That may be quicker than writing the issue.
