### ISSUE TITLE
Command dotnet new classlib - How to choose different target framework than the defaults

### ISSUE THREAD

**Issue by joramvanhaerens** [dotnet/docs#34239]
It is also possible to choose a different target framework than the defaults when using **dotnet new classlib**, but it's not mentioned in the documentation how.

Replace command parameter **--framework** with e.g. **--target-framework-override net462** to install Net Framework 4.6.2.

I believe you can find the official frameworks abbreviations listed [here](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#preprocessor-symbols).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 267c314a-e630-097f-edc6-d417be6db191
* Version Independent ID: af236ebe-5a79-fb2b-42a0-e5720ee732ae
* Content: [.NET default templates for dotnet new - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates)
* Content Source: [docs/core/tools/dotnet-new-sdk-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-sdk-templates.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 65743](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65743)

**Comment by tdykstra** [comment]
The `--target-framework-override` option is hidden pending a decision on whether to remove it. See https://github.com/dotnet/templating/issues/3261. You can accomplish the same purpose by editing the project file after project creation.
