### ISSUE TITLE
Doc page lists unsupported parameters: dotnet list packages does not actually support --format parameter.

### ISSUE THREAD

**Issue by jimleonardo** [dotnet/docs#34241]
Using dotnet cli 7.0.102 with the list command, the --format parameter listed on the page is not supported or there is some additional command not obvious from the docs that needs to be applied.

run this command: `dotnet list package --format json`

Result leads with these errors:

Unrecognized command or argument '--format'
Unrecognized command or argument 'json'

running `dotnet list --help` does not list the `--format` parameter, so I believe the doc page is out of date for this version. Doc says it's applicable to Core 3.1+

Logging a bug b/c I'm honestly not sure if this shouldn't be a bug report to the CLI instead.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8400fd6a-d987-1056-283f-9364fbce3c86
* Version Independent ID: 3d4b052c-33fa-cc83-4df6-4a3341f12763
* Content: [dotnet list package command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package)
* Content Source: [docs/core/tools/dotnet-list-package.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-list-package.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 65771](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65771)

**Comment by tdykstra** [comment]
@jimleonardo Thanks for reporting that. I'm adding notes explaining that these options (--format and --output-version) are available starting in SDK 7.0.200.
