### ISSUE TITLE
What's an 'MVID'?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#34256]
I was looking at the section of this page titled "Deterministic". I'm wondering what an MVID is as I'm not familiar with this. I assume it isn't Microvillus Inclusion Disease (what ever that is) and is in-fact a Module Version ID (something else I don't know about)? I think it would help fellow travellers to this page if this acronym was spelled out the first time it is used and better still linked to something that explains what it is. 

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35131307-8d1c-2800-e84a-6179d740982f
* Version Independent ID: 7599b464-9928-88bc-fec1-704ce691b344
* Content: [C# Compiler Options - code generation options](https://learn.microsoft.com/en-gb/dotnet/csharp/language-reference/compiler-options/code-generation)
* Content Source: [docs/csharp/language-reference/compiler-options/code-generation.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/code-generation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @martingbrown 

It is a "Module Version ID". It's a GUID that uniquely identifies the module and version. It's used as part of the tooling for reproducible builds: If the MVIDs match, the source and version match.

We'll add that to this doc.

I've also added the "help wanted" label in case someone wants to submit a PR before we make the change.

**Comment by BartoszKlonowski** [comment]
Let me add this to this page, please - I'll work on this.
