### ISSUE TITLE
Replace FwLinks with the actual target links - VB folder

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3426]
Sub-issue for folder https://github.com/dotnet/docs/tree/master/docs/visual-basic

**Comment by florinciubotariu** [comment]
Hello. Any ideas about how to modify the FwLinks for this file?
https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc2027

Thanks!

**Comment by KalleOlaviNiemitalo** [comment]
> Hello. Any ideas about how to modify the FwLinks for this file?
> https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc2027

I suspect the current Visual Basic compiler never emits error BC2027 and the page could be deleted. [The definition of `ERR_WatsonSendNotOptedIn` has been commented out](https://github.com/dotnet/roslyn/blob/958f2354c4d83dbb0e7723d0a8079a0dfbc33f25/src/Compilers/VisualBasic/Portable/Errors/Errors.vb#L55) and [the `/errorreport` option has no effect](https://github.com/dotnet/roslyn/blob/958f2354c4d83dbb0e7723d0a8079a0dfbc33f25/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L1015-L1020).

**Comment by mairaw** [comment]
Should we archive that page @KathleenDollard?

**Comment by Miguel09** [comment]
> Sub-issue for folder https://github.com/dotnet/docs/tree/master/docs/visual-basic
