### ISSUE TITLE
Great example of technical and best practice advice.  Much appreciated...

### ISSUE THREAD

**Issue by Beechside** [dotnet/docs#34276]
Just wanted to say thank you for the clarity on this page.  I was interested in whether resources could be defined outside a using block to minimise the text in the using statement.  Not only did you answer that question but you explained why it is not best practice.  Advice on best practice is invaluable and I thank you for that.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using statement - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the compliments @Beechside We appreciate it!

closing as kudos.
