### ISSUE TITLE
Duration of support

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#34273]
The article claims:

> .NET releases a new major version every November. Even-numbered releases, such as .NET 6 or .NET 8, are long-term supported (LTS). 

OK so far.

> Odd-numbered releases are supported until the next major release.

Not quite right. According to <https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#cadence>, odd-numbered (STS) major releases are supported for 18 months, i.e. 6 months past the next (LTS) major release.

> The latest release of .NET is .NET 6.

No, .NET 7 was already released.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4723eb4d-c4b9-f44c-7753-caa4a3c8cfdd
* Version Independent ID: 17270776-9bf5-fe60-f9a7-43311e5b4654
* Content: [How the .NET Runtime and SDK are versioned - .NET](https://learn.microsoft.com/en-us/dotnet/core/versions/)
* Content Source: [docs/core/versions/index.md](https://github.com/dotnet/docs/blob/main/docs/core/versions/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 66232](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66232)

**Comment by BillWagner** [comment]
Thanks for pointing these out. I'll update this coming month.
