### ISSUE TITLE
Hello World tutorial for Orleans should be updated for Orleans 7

### ISSUE THREAD

**Issue by dggmez** [dotnet/docs#34286]
**Issue description**

Hello World Tutorial for Microsoft Orleans is using an older Orleans version so it doens't work in Orleans 7:

https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/overview-helloworld

The README.md in the GitHub samples directory, however, seems to have the right information for Orleans 7:

https://github.com/dotnet/samples/tree/main/orleans/HelloWorld

**Target framework**

- .NET 7

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: babf6e7d-18bc-3170-3e35-ec75a0373c55
* Version Independent ID: b21f264d-2795-d68f-4c97-8af273562de5
* Content: [Tutorial: Hello world](https://learn.microsoft.com/en-us/dotnet/orleans/tutorials-and-samples/overview-helloworld)
* Content Source: [docs/orleans/tutorials-and-samples/overview-helloworld.md](https://github.com/dotnet/docs/blob/main/docs/orleans/tutorials-and-samples/overview-helloworld.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
This was actually already addressed...
