### ISSUE TITLE
Using old template

### ISSUE THREAD

**Issue by asudtelgte** [dotnet/docs#34297]
Flag for use program main doesn't appear in help and does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6+ - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 66522](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66522)

**Comment by tdykstra** [comment]
What version of the SDK are you using?
