### ISSUE TITLE
code c#

### ISSUE THREAD

**Issue by thaiduonghe88** [dotnet/docs#34307]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1138d70-1d83-a7e5-8549-72bf80dc5834
* Version Independent ID: 0811beda-ff7e-353a-aeb2-6bebe8947bcf
* Content: [Branches and loops - Introduction to C# tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/branches-and-loops-local?source=recommendations)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/branches-and-loops-local.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/branches-and-loops-local.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @thaiduonghe88 

Did you have a question on this article?
