### ISSUE TITLE
Reading configuration in worker class using the first method

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [dotnet/docs#34309]
[Enter feedback here]
I see that there are 2 methods to provide strict typing to the configuration. the first one is by configuring `ConfigureAppConfiguration` and the second by `ConfigureServices`. I am able to get configuration in my `Worker` class by using the second method. Using DI in my worker class fetches me the data. But the first method does nothing. How do I get the configuration when only using the first method?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 433988ea-fda9-aa83-f6ee-221a5521a422
* Version Independent ID: 00449cdc-b8fc-a9ff-3f20-0ef0994db354
* Content: [Options pattern - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/options)
* Content Source: [docs/core/extensions/options.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 90209](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90209)

**Comment by IEvangelist** [comment]
I'm not sure I fully understand what you're asking. Are you saying that you want to use a strongly typed settings class, that is resolved with `IOptions<TOptions>`, and you don't want to call `ConfigureServices` but rather `ConfigureAppConfiguration`?

**Comment by SayakMukhopadhyay** [comment]
Well, yes and no. I want a strongly typed settings class with `ConfigureAppConfiguration` but I am not necessarily asking for it to be resolved with `IOptions<TOptions>`. I am just asking how it would work in the first place if I only use `ConfigureAppConfiguration`.

**Comment by IEvangelist** [comment]
Binding to a strongly typed settings class within the `ConfigureAppConfiguration` is shown in this article, see the third code block down from [this heading](https://learn.microsoft.com/en-us/dotnet/core/extensions/options#bind-hierarchical-configuration).

```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using ConsoleJson.Example;

using IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration((hostingContext, configuration) =>
    {
        configuration.Sources.Clear();

        IHostEnvironment env = hostingContext.HostingEnvironment;

        configuration
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, true);

        IConfigurationRoot configurationRoot = configuration.Build();

        TransientFaultHandlingOptions options = new();
        configurationRoot.GetSection(nameof(TransientFaultHandlingOptions))
                         .Bind(options);

        Console.WriteLine($"TransientFaultHandlingOptions.Enabled={options.Enabled}");
        Console.WriteLine($"TransientFaultHandlingOptions.AutoRetryDelay={options.AutoRetryDelay}");
    })
    .Build();

// Application code should start here.

await host.RunAsync();
```

Does that not work for your scenario?

**Comment by SayakMukhopadhyay** [comment]
I have seen that code block, but how do I use the configuration in other classes like say in a `Worker` class. For eg. for the second method this code block is given
```csharp
using Microsoft.Extensions.Options;

namespace ConsoleJson.Example;

public sealed class ExampleService
{
    private readonly TransientFaultHandlingOptions _options;

    public ExampleService(IOptions<TransientFaultHandlingOptions> options) =>
        _options = options.Value;

    public void DisplayValues()
    {
        Console.WriteLine($"TransientFaultHandlingOptions.Enabled={_options.Enabled}");
        Console.WriteLine($"TransientFaultHandlingOptions.AutoRetryDelay={_options.AutoRetryDelay}");
    }
}
```

**Comment by IEvangelist** [comment]
Hi again @SayakMukhopadhyay,

To get the strongly-typed configuration options object into your worker class, use `ConfigureServices` or `builder.Services.Configure` approach. If you have something working, why are you trying the another approach?

**Comment by IEvangelist** [comment]
Closing this as a non-issue, the op has already identified a valid workaround which is the preferred way to achieve what they were trying to do anyway.
