### ISSUE TITLE
Enhance docs for new WPF APIs

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3433]
Check out the spec for detailed info on when to use the following APIs:
M:System.Windows.Diagnostics.VisualDiagnostics.DisableVisualTreeChanged
M:System.Windows.Diagnostics.VisualDiagnostics.EnableVisualTreeChanged

The spec includes a detailed discussion of when these methods (especially Enable...) can be called:  registry keys, app-context switches, environment variables, etc.   That should be included in the doc.

**Comment by JRAlexander** [comment]
These appear to have been updated with "This method is for diagnostic use only. Microsoft does not support the use of this method in a production application under any circumstances." Closing this as this new guidance is pretty clear. Please reopen should the need and priorities change.
