### ISSUE TITLE
Orleans: Azure App Service article updates

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#34334]
Orleans: Azure App Service article updates:

- Add an alert (note) about slots.
- Refer to @bradygaster sample code to see how to enable slots.
  - Bicep and app updates.
  -  1 vnet -> 2 subnets, 1 prod, and 1 staging
- Networking updates and details
  - Cluster (heterogeneous)
  - Windows known issues:
    > As of release x.x, different app service plan per heterogeneous silo, will need App Service team sign off

Contributes to https://github.com/dotnet/orleans/issues/8203, related to https://github.com/dotnet/samples/issues/5625#issuecomment-1384434160

---
[Associated WorkItem - 66880](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66880)

**Comment by bradygaster** [comment]
@IEvangelist feel free to ping me if you want me if you need anything or if i owe you a PR or anything.
