### ISSUE TITLE
fibonacci example

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#34333]
For the fibonacci example, I offer this:
```
let fib =
    (0, 1)
    |> Seq.unfold (fun state ->
        let cur, next = state
        if cur < 0 then  // overflow
            None
        else
            let next' = cur + next
            let state' = next, next'
            Some (cur, state') )
```
to replace this:
```
let fib =
    (1, 1) // Initial state
    |> Seq.unfold (fun state ->
        if (snd state > 1000) then
            None
        else
            Some(fst state + snd state, (snd state, fst state + snd state)))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67fae525-473a-3072-b024-6d91d0e033b9
* Version Independent ID: 6e162795-52bd-f9df-4105-6919c1c72c88
* Content: [Sequences - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences)
* Content Source: [docs/fsharp/language-reference/sequences.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/sequences.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by daveyostcom** [comment]
[F# Guide – Sequences](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences)

**Comment by Adi9235** [comment]
Hey @daveyostcom can I work on this issue?

**Comment by daveyostcom** [comment]
> Hey @daveyostcom can I work on this issue?

Anyone is free to submit a pull request.  🙂
