### ISSUE TITLE
Following the "Create a Windows Service installer" my installation failed

### ISSUE THREAD

**Issue by DiogenesBR** [dotnet/docs#34348]
I tried to follow the tutorial for creating a Windows Service Installer but it fails when executing I think it's because the `sc.exe create ".NET Joke Service"` command has to be run in a console as Administrator, but I'm not sure, the error message don't give details.

I Tried run the command ".\App.WindowsService.exe /Install" as administrator and worked fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e044209a-0802-07c0-7518-208967a3ef02
* Version Independent ID: 83c4d805-1394-90b7-6def-cf809c33ae22
* Content: [Create a Windows Service installer - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service-with-installer?source=docs)
* Content Source: [docs/core/extensions/windows-service-with-installer.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service-with-installer.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by diogenesdirkx** [comment]
![image](https://user-images.githubusercontent.com/16890195/222461232-f1de6d32-03ec-4087-8e3c-02f67030577f.png)

The error message in Portuguese

Should be something like: "There is a problem with this Windows Installer package. A program run as part of the installation did not exit as expected. Contact the support team or the package vendor."

**Comment by diogenesdirkx** [comment]
I'm Running on a Windows 10 and the program is in .Net 7
