### ISSUE TITLE
Doc Update needed

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/docs#34341]
4.8.1 section in [](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)[https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fframework%2Fmigration-guide%2Fversions-and-dependencies&data=05%7C01%7Calicial%40exchange.microsoft.com%7C92b2f68e71a94d8c39d508db1a2fa213%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638132564123980278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FoTHqf9MA%2F0goIzcpvXhmX4aVgMydNKljzh0XPrHrks%3D&reserved=0) needs update to include separated entries for win11 21H2 and 22H2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework & Windows OS versions - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Closing as fixed.
