### ISSUE TITLE
Code samples with IDisposable code sample not using "using" statement

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#3435]
I came across some doc page with code sample that uses IDisposable classes, but not using a "using" statement to cleanup resources. Isn't it better to also include "using" in code samples?

Example : https://github.com/styxxy/docs/blob/master/docs/framework/winforms/controls/user-drawn-controls.md
The Pen class is IDisposable in these samples (both C# and VB.NET).

Can I submit a PR for this?

**Comment by rpetrusha** [comment]
@Styxxy, yes, you can submit a PR.
