### ISSUE TITLE
Corrijan este error

### ISSUE THREAD

**Issue by DavidMarin11** [dotnet/docs#34384]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3c3004b-49f9-09d4-5bc2-0358e82949bf
* Version Independent ID: 278c9b16-9d05-91bf-8f7c-f9e9e603f04c
* Content: [Compiler Warning (level 1) CS1030](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1030?f1url=%3FappId%3Droslyn%26k%3Dk(CS1030))
* Content Source: [docs/csharp/misc/cs1030.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1030.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @DavidMarin11 

Did you have more details that you can add to this issue? Is there something in the article that we need to address?
