### ISSUE TITLE
What is the behaviour for "when_multiline"

### ISSUE THREAD

**Issue by mpgoodwin-wsa** [dotnet/docs#34408]
Is there a reason this page does not give an example for the "when_multiline" value?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c300ee48-d34d-af7a-abd0-4ffa283f8f60
* Version Independent ID: 782fcb19-08c6-7fae-804d-2c2b160d6068
* Content: [IDE0011: Add braces - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0011.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0011.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
It seems like we should add an example for `when_multiline`. Would you like to?
