### ISSUE TITLE
Upgrade TOC from .NET 5 to .NET 7

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#34400]
<img width="215" alt="image" src="https://user-images.githubusercontent.com/3605364/223213088-d48bd73a-d4cc-4e83-8ff4-33d9135e9b96.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET and .NET Framework for server apps](https://learn.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/main/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 70663](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70663)

**Comment by Rick-Anderson** [comment]
@gewarren  I can fix this if you tell me which `.yml` file to update.

**Comment by gewarren** [comment]
I think it should say "...between .NET and .NET Framework...". The file is at https://github.com/dotnet/docs/blob/main/docs/navigate/migration-guide/toc.yml.
