### ISSUE TITLE
Code sample incorrect - no removal example

### ISSUE THREAD

**Issue by jackp555** [dotnet/docs#34451]
Page talks about removals from the collection, but code sample has no removal in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8509dec-9d0f-1530-0d7a-a3ca9aa24c3e
* Version Independent ID: 1a5dfa73-b5cf-cff9-dec2-25e1868b2bd7
* Content: [Use foreach to remove items in a BlockingCollection](https://learn.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-use-foreach-to-remove)
* Content Source: [docs/standard/collections/thread-safe/how-to-use-foreach-to-remove.md](https://github.com/dotnet/docs/blob/main/docs/standard/collections/thread-safe/how-to-use-foreach-to-remove.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @jackp555,

Thank you for posting this issue, we really appreciate it.

The `BlockingCollection<T>` removes items when they're iterated over from the `*Take*` and the `GetConsumingEnumerable` APIs. This is correct. I'm closing this issue unless you have any other questions.
