### ISSUE TITLE
prefer SkiaSharp over ImageSharp as a suggested alternative

### ISSUE THREAD

**Issue by ghelyar** [dotnet/docs#34464]
ImageSharp has changed to a dual license including a commercial license in 3.x and is no longer a part of the .NET Foundation.

SkiaSharp seems like a safer alternative, given that Skia is BSD licensed and SkiaSharp is MIT licensed, and at least Xamarin and MAUI use SkiaSharp, as well as other things like Avalonia and Uno.

Maybe SkiaSharp should be listed above ImageSharp, or maybe the ImageSharp licensing should be called out more clearly on this page, so that people can more easily make an informed decision.

It doesn't seem like a 3rd party commercial library should be recommended over a free library (which is used by and possibly maintained by Microsoft, at least for the managed part), without making it very clear that ImageSharp is a commercial library. It's a bit "do as we say, not as we do".

It looks like ImageSharp was [removed in the past](https://github.com/dotnet/docs/pull/31509), and re-added [here](https://github.com/dotnet/dotnet-api-docs/pull/8790)

There is some past discussion [here](https://github.com/dotnet/dotnet-api-docs/pull/8577). I'm not trying to stir up drama or talk about ethics, just to make the information as clear as possible on the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa60e1c-9c9a-ce16-2e47-c41857fc8c48
* Version Independent ID: c3b792d7-50ab-ff45-09bf-37a7550f0e09
* Content: [Breaking change: System.Drawing.Common only supported on Windows - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)
* Content Source: [docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 132885](https://dev.azure.com/msft-skilling/Content/_workitems/edit/132885)

**Comment by gewarren** [comment]
@BillWagner Are you okay with reordering these:

![image](https://user-images.githubusercontent.com/24882762/225446306-8b3dd748-baa7-480a-af48-c6467eec26cf.png)

**Comment by gewarren** [comment]
Ping @BillWagner

**Comment by BillWagner** [comment]
Thanks for the ping @gewarren 

I like the reordering suggestion.

**Comment by BillWagner** [comment]
> I would also be in favor of qualification of ImageSharp as commercial, but I'm not sure we have a precedent for that.

@richlander and I wrote the policies [here](https://github.com/dotnet/docs/blob/main/styleguide/3rdPartyDependencies.md) Image Sharp should be referred to as a "tiered license"

**Comment by sharwell** [comment]
@BillWagner Thank you, that was _very_ helpful. I'm glad there is a category separate from dual license for this scenario.
