### ISSUE TITLE
[New Topic] Current state of development tools

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/docs#3446]
[Idea] A sheet which shows all the available compilers, runtimes and frameworks including the support for the different languages and platforms, including notation of the licenses, maintainers and blocking issues. 

[Edit] So, something like this: 

![screenshot_20171018_140341](https://user-images.githubusercontent.com/6344099/31717758-7ac1b2fc-b40d-11e7-849d-3450472aff7f.png)

I think this is important to get a simple overview.

**Comment by enricosada** [comment]
So, you pratically want the link to github projects for each component?

=> https://github.com/dotnet/core/blob/master/Documentation/core-repos.md

and https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

You can start navigate docs from the readme of https://github.com/dotnet/core

**Comment by ShalokShalom** [comment]
Ahm no. A table. A comparsion table. A sheet

**Comment by ShalokShalom** [comment]
![screenshot_20171018_132744](https://user-images.githubusercontent.com/6344099/31716479-4ae353f6-b408-11e7-99cb-351fb08deece.png)

**Comment by charlesroddie** [comment]
I think this is a good idea. Suggest putting an .md file similar to what you have a screenshot of on your own github where people can submit changes. Here it would require some group to approve it.

**Comment by hsorbo** [comment]
Its a good mixture of different stuff in that list. Perhaps it would be clearer if you further group them into Runtimes, Compilers, Frameworks etc?

**Comment by ShalokShalom** [comment]
> Perhaps it would be clearer if you further group them into Runtimes, Compilers, Frameworks etc?

Yes, exactly this is my plan. To be honest: I am fresh to this whole infrastructure, so my information is based on a lot of opinions and some kind of half official statements. 

This is why I hope for some contributions by deeply involved community members.

> Suggest putting an .md file similar to what you have a screenshot of on your own github where people can submit changes. Here it would require some group to approve it.

I like to get it on the official documentation anyway. Currently, this is a .ods and I can port it to something compatible. Is there a template for something?

**Comment by 21c-HK** [comment]
This would be incredibly helpful.

**Comment by BillWagner** [comment]
I'm waiting to assign this to a milestone for a couple reasons.  

First, this is a great discussion, and I want to coalesce around what information should be in this topic. 

Second, do you expect version information here as well? And, if so, to what detail (major version, minor version, build)?

**Comment by ShalokShalom** [comment]
Well, I think one fundamental question is, how we like to present this table. 

Of course is it nice to present the whole thing in a manner that is nice to maintain. 

Which is, why I left "current major issues" and such stuff out for now. 

To be honest: This is something very obviously in my sense, so I suggest two solutions: 

a) Current C#/VB/F# developers/maintainer care for this list and change mutable stuff. 
b) This list gets immutable. 

I also like to include a link to the current roadmap, communitys and so on. 
A full overview over the whole ecosystem.

**Comment by ShalokShalom** [comment]
@enricosada 

I do not see the whole range of available products in Github. 
To start with, since they are spread on several repos. 

I do not see the current state of these products on Github.

I also cant see, which of the other products are working well with this specific product. 
So, .NET Native is running usable on C#, while not yet on F#, yes?

How to see this on Github?

**Comment by mairaw** [comment]
@richlander any thoughts on this?

**Comment by ShalokShalom** [comment]
I will upload the file for now: 

[ComparsionSheetMSdevtools.pdf](https://github.com/dotnet/docs/files/1501926/ComparsionSheetMSdevtools.pdf)

**Comment by ShalokShalom** [comment]
Who feels responsible here?

**Comment by ShalokShalom** [comment]
See also this: https://stackify.com/net-ecosystem-demystified/

**Comment by ShalokShalom** [comment]
Why is it impossible to one of the largest companies in the world, to implement such a fundamental thing, while there is even an open source contribution which simply can get adopted?
