### ISSUE TITLE
Remove comments from examples where the interactive experience is enabled

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3447]
The [foreach reference page](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/foreach-in) has the interactive in-browser experience enabled.

It also shows the expected output in comments:

```csharp
int[] fibarray = new int[] { 0, 1, 1, 2, 3, 5, 8, 13 };
foreach (int element in fibarray)
{
    System.Console.WriteLine(element);
}
System.Console.WriteLine();
// Output:
// 0
// 1
// 1
// 2
// 3
// 5
// 8
// 13
```

We think we should remove the output from the comments. Do you agree? Vote thumbs up to remove, thumbs down to keep it.

**Comment by maggarwal** [comment]
👍

**Comment by jesta88** [comment]
👍

**Comment by BillWagner** [comment]
close as a duplicate of #4571
