### ISSUE TITLE
Code should be updated. 

### ISSUE THREAD

**Issue by SDmorgan** [dotnet/docs#34488]
[Enter feedback here]
before the "equals" on the join there is no matching property that equals the other property. You are equaling an object to a property.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d433265d-15f4-bd2e-a3d1-8148a3968783
* Version Independent ID: 75d2c893-1d07-f836-62f1-e767edfcebac
* Content: [Perform left outer joins (LINQ in C#)](https://learn.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins)
* Content Source: [docs/csharp/linq/perform-left-outer-joins.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/perform-left-outer-joins.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @SDmorgan 

The sample works correctly.  See [Sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRj1UwAJUCAWAbmLIoDoAZASygEdbc8AFAUzABnAPZRSAWwCGAcygRBpALykofAO4AKAEQBZGXMFaYpLQAk+cADbQ4WgJRd+Q0aWACwATyUr12gCruHkYmAIJwkuKGDrwCImIAxgAWkmCWwsBu3qqaWgDCyanpbsFaAOp8LIJRjrEuKZZ8qlm+WiGpjXwlphAAZj32XDHApABG9XxeytnaAELjQcZuYJ7RuPzDI8LpClMtM1vAhouBq+ukaomVANaxzTmll4I3QsFJ9UV8p3wb1nziW2JdjkZr9SDoAcElisasNwpVJj4cgARSTw4JSWTyVZ4AD0ONIuTAfEkmWAamEpEslUODDwrEEwAAPE44gA+UgABz4wg5DTuGjspAA3hJ9PJjssPMY3oUMnxjOMmgBfLj0pnrdlcw78wUisbtKWjA6CYwXa6xYwjX7/UTGOGCLwqvB4ABuKVI7AgAkmeFIftIPTAwnEnNqYjYoZ5DV9/oAVsII1rSInvgoXFznGI+J7JJYFFqGAB5NSqMDJqDACnSWMxv2B4OkQQQEZJiPVhhIvg9SQQSzAACSPQAouIOcAPALa42+A14sNslOhVP/aHMwwAGIsITAAByEXly/96z34j43ibLe+AH4GCez1er+QCJgGCOxx4p07uLgesIiZIklIDQ3TLF1yw9L0VjwJdcBXCgAE4NAAEi0IUXQ3LcGTvUhEBMEAjAAWgIABWJU0IYY99yVAY8CVZ1cCJeI/zgch0FIFlRA0CgyE3bc72MbjSCYSQsP3VZGOY1j2O+Ljn1IfjpMzUhi1LVYgA=)

The `Person` object is the same type as the `Owner` property on the `Pet` type. 

I'll close this as it does work correctly.
