### ISSUE TITLE
Make output pane on interactive experience larger/resizable

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/docs#3448]
At the moment the output pane when running the interactive C# script is about 4 lines:

![image](https://user-images.githubusercontent.com/1376924/31683147-701e4fae-b37c-11e7-8369-cb1e4febc03b.png)

This is way too little output in my opinion. The pane should be larger by default or even better be resizable.

**Comment by mairaw** [comment]
@EisenbergEffect can you take a look at this feedback for the interactive experience?

**Comment by EisenbergEffect** [comment]
@akoeplinger What browser are you using? There should at least be a scroll bar. I don't see it in your screenshot.

**Comment by akoeplinger** [comment]
@EisenbergEffect I'm using Chrome on OSX, the hidden scrollbar is normal there and expected.

**Comment by EisenbergEffect** [comment]
Ok. Just wanted to make sure there wasn't a CSS glitch that was causing an additional issue there. 

So, to dig into details. This is for the inline "Try It" experience, specifically (as opposed to interactive tutorials). Can you provide some more thoughts?

* If we just made the output panel larger, how large would be large enough?
* If we provided a resizer, would you expect that to expand the output down, increasing the entire sample size? or would you expect to resize it up, keeping a fixed size, but decreasing the amount of space for the code? Some other option?

**Comment by akoeplinger** [comment]
> This is for the inline "Try It" experience, specifically (as opposed to interactive tutorials).

Correct, it was based on https://twitter.com/akoeplinger/status/920358807544516614, should've mentioned that :smile:

> If we just made the output panel larger, how large would be large enough?

I think at least 3-4 more lines would be good.

> If we provided a resizer, would you expect that to expand the output down, increasing the entire sample size? or would you expect to resize it up, keeping a fixed size, but decreasing the amount of space for the code? Some other option?

I'd have expected to be able to pick and drag the line that separates code/output upwards, so output would get larger and code smaller. I'm not sure how it would work if the whole thing was resizable, I assume it'd break the page flow.

**Comment by EisenbergEffect** [comment]
Good feedback @akoeplinger. Thanks! I'll take this and see if we can iterate on the design a bit in the future.

Note: This is part of the One Microsoft documentation platform itself, not just .NET, so I have to balance the priority and design of this against a lot of other items we're working on. In other words, if you don't see us ship an update to the UI next week...it's not because we aren't listening 😄  We're just balancing priorities and needs across the company.

**Comment by BillWagner** [comment]
@EisenbergEffect As I've been looking at topics where the interactive experience would be a big improvement, I'm finding snippets that are between 10 - 15 lines long, and generate up to 10 lines of output. There are some outliers, but those samples could likely be shortened without loss of clarity.

**Comment by mairaw** [comment]
@EisenbergEffect do we have an internal bug/request tracking this issue already?

**Comment by EisenbergEffect** [comment]
Just pinged you on the feature.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2196
