### ISSUE TITLE
CANNOT OVERRIDE INHERITED MEMBER

### ISSUE THREAD

**Issue by byui-webster** [dotnet/docs#34511]
Hello, Dev.

Please, I am currently working on a c# project and I was getting these errors:

Compilation error (line 42, col 22): 'SimpleGoal.MarkCompleted()': cannot override inherited member 'Goal.MarkCompleted()' because it is not marked virtual, abstract, or override
Compilation error (line 90, col 22): 'ChecklistGoal.MarkCompleted()': cannot override inherited member 'Goal.MarkCompleted()' because it is not marked virtual, abstract, or override
Compilation error (line 167, col 23): 'GoalTracker.NegativeGoal.MarkCompleted()': cannot override inherited member 'Goal.MarkCompleted()' because it is not marked virtual, abstract, or override

Thank you in anticipation as you help me solve this problem.

Here is the code that I am working on:

using System;
using System.Collections.Generic;

// Base class for all goals
public class Goal
{
	// Private attributes
	private string name;
	private int points;
	private bool completed;
	// Constructor
	public Goal(string name, int points)
	{
		this.name = name;
		this.points = points;
		this.completed = false;
	}

	// Mark this goal as completed and return the points earned
	public int MarkCompleted()
	{
		completed = true;
		return points;
	}

	// Get a string description of this goal
	public virtual string GetDescription()
	{
		return name + " (" + points + " points) [" + (completed ? "X" : " ") + "]";
	}
}

// Subclass for simple goals that can be marked complete
public class SimpleGoal : Goal
{
	// Constructor
	public SimpleGoal(string name, int points) : base(name, points)
	{
	}

	// Override MarkCompleted method to simply call the parent implementation
	public override int MarkCompleted()
	{
		return base.MarkCompleted();
	}
}

// Subclass for eternal goals that are never complete but each recording earns points
public class EternalGoal : Goal
{
	// Private attributes
	private int pointsPerRecording;
	// Constructor
	public EternalGoal(string name, int pointsPerRecording) : base(name, 0)
	{
		this.pointsPerRecording = pointsPerRecording;
	}

	// Record this goal and return the total points earned
	public int RecordGoal()
	{
		int pointsEarned = base.MarkCompleted();
		pointsEarned += pointsPerRecording;
		return pointsEarned;
	}

	// Override GetDescription to show the total points earned so far
	public override string GetDescription()
	{
		return name + " (" + pointsPerRecording + " points per recording, " + base.GetDescription() + ": " + pointsPerRecording * Convert.ToInt32(completed) + ")";
	}
}

// Subclass for checklist goals that must be completed a certain number of times
public class ChecklistGoal : Goal
{
	// Private attributes
	private int pointsPerCompletion;
	private int targetCount;
	private int completedCount;
	// Constructor
	public ChecklistGoal(string name, int pointsPerCompletion, int targetCount) : base(name, 0)
	{
		this.pointsPerCompletion = pointsPerCompletion;
		this.targetCount = targetCount;
		this.completedCount = 0;
	}

	// Mark this goal as completed and return the points earned
	public override int MarkCompleted()
	{
		int pointsEarned = base.MarkCompleted();
		completedCount++;
		if (completedCount == targetCount)
		{
			pointsEarned += pointsPerCompletion * targetCount;
		}
		else
		{
			pointsEarned += pointsPerCompletion;
		}

		return pointsEarned;
	}

	// Override GetDescription to show the completion status
	public override string GetDescription()
	{
		return name + " (" + pointsPerCompletion + " points per completion, " + base.GetDescription() + ": Completed " + completedCount + "/" + targetCount + " times)";
	}
}

// Class for tracking the user's goals and score
public class GoalTracker
{
	// Private attributes
	private List<Goal> goals;
	private int score;
	// Constructor
	public GoalTracker()
	{
		goals = new List<Goal>();
		score = 0;
	}

	// Add a new goal to the list of goals
	public void AddGoal(Goal goal)
	{
		goals.Add(goal);
	}

	// Mark a goal as completed
	public class LargeGoal : Goal
	{
		private int progress;
		private int target;
		public LargeGoal(string name, int points, int target) : base(name, points)
		{
			this.target = target;
			this.progress = 0;
		}

		public void AddProgress(int amount)
		{
			this.progress += amount;
			if (this.progress >= this.target)
			{
				this.completed = true;
				this.points += 500;
			}
		}

		public override string GetDescription()
		{
			string status = this.completed ? "Completed" : "Incomplete";
			return this.name + ": " + status + ", Progress: " + this.progress + "/" + this.target;
		}
	}

	public class NegativeGoal : Goal
	{
		public NegativeGoal(string name, int points) : base(name, points)
		{
			this.points *= -1;
		}

		public override int MarkCompleted()
		{
			this.completed = true;
			return this.points;
		}

		public override string GetDescription()
		{
			return this.name + ": " + (this.completed ? "Completed" : "Incomplete") + ", " + this.points + " points";
		}
	}

	public class GoalTracker1
	{
		private List<Goal> goals;
		private int score;
		public GoalTracker1()
		{
			this.goals = new List<Goal>();
			this.score = 0;
		}

		public void AddGoal(Goal goal)
		{
			this.goals.Add(goal);
		}

		public void MarkGoalCompleted(string goalName)
		{
			foreach (Goal goal in this.goals)
			{
				if (goal.GetName() == goalName)
				{
					this.score += goal.MarkCompleted();
					return;
				}
			}
		}

		public void RecordGoal(string goalName)
		{
			foreach (Goal goal in this.goals)
			{
				if (goal.GetName() == goalName)
				{
					this.score += goal.RecordGoal();
					return;
				}
			}
		}

		public List<string> GetGoalList()
		{
			List<string> goalList = new List<string>();
			foreach (Goal goal in this.goals)
			{
				goalList.Add(goal.GetDescription());
			}

			return goalList;
		}

		public int GetScore()
		{
			return this.score;
		}

		public void SaveData(string fileName)
		{
			using (StreamWriter writer = new StreamWriter(fileName))
			{
				writer.WriteLine(this.score);
				foreach (Goal goal in this.goals)
				{
					writer.WriteLine(goal.Serialize());
				}
			}
		}

		public void LoadData(string fileName)
		{
			this.goals.Clear();
			using (StreamReader reader = new StreamReader(fileName))
			{
				this.score = int.Parse(reader.ReadLine());
				string line;
				while ((line = reader.ReadLine()) != null)
				{
					Goal goal = Goal.Deserialize(line);
					this.goals.Add(goal);
				}
			}
		}
	}
}

**Comment by gewarren** [comment]
@byui-webster StackOverflow or a similar Q&A site is a better place to ask for help. This repo is specifically for feedback related to .NET documentation.
