### ISSUE TITLE
what if you don't have the .csproj file, just the .dll file?

### ISSUE THREAD

**Issue by robidas** [dotnet/docs#34515]
I want to add a reference to an assembly, call it MyAssembly.DLL, but I don't have access to the source code. There should be a way to put the DLL file somewhere and reference it from your own project so that you can put a using statement into your c# code something like:
 
using MyAssembly;

You would need to make your own project aware of the where to find the DLL. You need to have something like 

dotnet add reference ".\MyDLLFolder\MyAssembly.DLL"

or something like that. 

Is there a way to do this?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76ab77c3-eba6-e947-8ffa-0fcda722f34b
* Version Independent ID: 48bbcb58-cfd1-b3d3-7a2a-319716541362
* Content: [dotnet add reference command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference)
* Content Source: [docs/core/tools/dotnet-add-reference.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-add-reference.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 72553](https://dev.azure.com/msft-skilling/Content/_workitems/edit/72553)

**Comment by svick** [comment]
This is not a common operation, so it's not exposed from the CLI. But you can do it by editing the csproj manually and adding something like:

```csproj
<ItemGroup>
  <Reference Include="MyAssembly">
    <HintPath>".\MyDLLFolder\MyAssembly.DLL</HintPath>
  </Reference>
</ItemGroup>
```
