### ISSUE TITLE
Page said to be updated for .NET 7, but shows same content as of .NET 6.

### ISSUE THREAD

**Issue by luizen** [dotnet/docs#34523]
Hi.
The wiki page says it, together with the Microservices Architecture eBook, have been updated to reflect v7.0 of .NET. However, in the changelogs there is only v6.0. Also, when downloading the e-book, it's the same as previous version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by ardalis** [comment]
Interesting. I wonder if one of my commits got missed. I'll check it out ASAP.

**Comment by luizen** [comment]
@ardalis the changelog page is also not updated :)
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Microservices-Architecture-eBook-changelog
