### ISSUE TITLE
Mistake in code on System.Random page.

### ISSUE THREAD

**Issue by artusvranken** [dotnet/docs#3454]
# Mistake in the code on the [System.Random page in the .NET Framework API reference](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.1#Examples)

In the first examples code block at the top of the page there is an example for generating 5 random byte values. The code says
`byte[] bytes = new byte[4];`
but it should be
`byte[] bytes = new byte[5];`

**Comment by rpetrusha** [comment]
Thanks, @artusvranken, for opening this issue.  I've opened PR #3458 to address it.
