### ISSUE TITLE
Add new deep learning scenarios

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#34557]
Add new deep learning tasks to this list:

- [ ] Text Classification
- [ ] Sentence Similarity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://learn.microsoft.com/en-us/dotnet/machine-learning/resources/tasks#multiclass-classification)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

---
[Associated WorkItem - 255772](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255772)

**Comment by tdykstra** [comment]
@luisquintanilla Milestones are [supposed to contain only PRs, not issues](https://learn.microsoft.com/en-us/contribute/dotnet/labels-projects#milestones) - can we remove this issue and #34484 from the July milestone?
