### ISSUE TITLE
Adding PowerShell samples in .NET API documentation

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#3455]
At one time, there was documentation regarding .NET APIs over in the old msdn.microsoft.com site. Some of the classes/properties/methods decorated with PowerShell samples demonstrating the use of .NET Framework objects by PowerShell. 

I am wondering if folks felt this would be useful? It would be simple enough to just add appropriate samples and I'd be happy to start the ball rolling.

edit by @mairaw: clean up template text

**Comment by mairaw** [comment]
Thanks @doctordns. I've posted this on Twitter to see what people think!

**Comment by zjalexander** [comment]
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088615-add-powershell-tab-and-examples-to-net-reference is one of the PowerShell Team's top-voted items :)

**Comment by lwsrbrts** [comment]
This. +1

**Comment by pchatham** [comment]
Yes +1 and voted on uservoice

**Comment by Rukas** [comment]
Yes +1

**Comment by BladeFireLight** [comment]
How many times do we have to ask for this before it happens?

**Comment by jmcook01** [comment]
Yes!

**Comment by mairaw** [comment]
@doctordns I think you have your answer. Thanks @zjalexander for spreading the word!

**Comment by megamorf** [comment]
+1

**Comment by Tiberriver256** [comment]
Would love this!

**Comment by doctordns** [comment]
What is amusing or sad - I added over 800 PowerShell samples to the MSDN library. But Microsoft decided to remove them all. :-(

**Comment by gerane** [comment]
+1

**Comment by mairaw** [comment]
I'd say is sad @doctordns. I'll see if that information lives anywhere in our internal databases and systems.

**Comment by itadder** [comment]
Plus +1

**Comment by kevinblumenfeld** [comment]
Plus +1.  Why is this not a thing yet?

**Comment by dezren39** [comment]
Yes

**Comment by Stephanevg** [comment]
+1

**Comment by Dineshppatil** [comment]
Yes

**Comment by dnp60** [comment]
My company could really use this. It's stopped us a few time from using the PowerShell.

**Comment by stevenjudd** [comment]
Yes, please.

**Comment by mairaw** [comment]
Ok, so here's what I was able to find @doctordns: 
[Thomas Lee PowerShell.xlsx](https://github.com/dotnet/docs/files/1401015/Thomas.Lee.PowerShell.xlsx)

This spreadsheet contains your contributions to the wiki over time. You'll see that some links still have the PowerShell example (e.g. https://msdn.microsoft.com/en-us/library/00101w8c(vs.85).aspx) while later .NET versions don't have that section displayed anymore.

The content from the body column can easily be pasted into an HTML file. Unfortunately, I can't paste html files here.

I hope that helps!

**Comment by MathieuBuisson** [comment]
+1

**Comment by DCAG** [comment]
+1

**Comment by mairaw** [comment]
Thanks everyone for your input. I'll be closing this discussion as I think we've had enough feedback that folks finding it valuable to add PowerShell examples to our documentation set. We'll be taking PRs from the community to help us do that. If you're interested in helping, please reach out. We can open individual issues for the enhancements we'll be making over time.
