### ISSUE TITLE
Reference to QueueBackgroundWorkItem(Func<CancellationToken,Task>)

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#34551]
There is a reference in this article to [QueueBackgroundWorkItem(Func<CancellationToken,Task>)](https://learn.microsoft.com/en-us/dotnet/api/system.web.hosting.hostingenvironment.queuebackgroundworkitem#system-web-hosting-hostingenvironment-queuebackgroundworkitem(system-func((system-threading-cancellationtoken-system-threading-tasks-task)))). It seems that this was not implemented in .Net Core and .Net 5+ and maybe there should be some mention of that either here or on the linked page, so that people like me don't spend time wondering why it's not showing up in IntelliSense.

I'm also curious why it wasn't ported over to .Net Core. Was there some issue with it? If so does it need a health warning?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86bac4b0-9ea8-9471-c1a8-88c8bdd7e733
* Version Independent ID: 976f3af2-4d3f-6d45-1e9e-b4c86edaed34
* Content: [Create a Queue Service - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/queue-service)
* Content Source: [docs/core/extensions/queue-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/queue-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by svick** [comment]
The relevant part of the article says:

> You may be familiar with the `QueueBackgroundWorkItem(Func<CancellationToken,Task>)` functionality from the `System.Web.Hosting` namespace. To model a service that is inspired by this functionality, ...

To me, that wording makes it fairly clear it's not something that's available in .Net 5+.

---

> I'm also curious why it wasn't ported over to .Net Core. 

[Basically no part of System.Web was ported.](https://learn.microsoft.com/en-us/dotnet/api/system.web?view=net-8.0) Why should this one be an exception?
