### ISSUE TITLE
"Advanced concepts" breadcrumb is broken

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#34604]
The breadcrumb 404s. Looks like you'll need to add an index page at the advanced-topics level or point the breadcrumb to this page instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8bc41f1-c2f4-3d82-d65b-e986735162bd
* Version Independent ID: 1b8ea375-81a3-caef-f51a-f08635c6610a
* Content: [Attributes and reflection](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/reflection-and-attributes/)
* Content Source: [docs/csharp/advanced-topics/reflection-and-attributes/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/advanced-topics/reflection-and-attributes/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @gewarren 

I'll fix that this week.
