### ISSUE TITLE
Need to initialise valuetype to default value?

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#34607]
Docs includes this code sample
async Task<int> GetTaskOfTResultAsync()
{
    int hours = 0;
    await Task.Delay(0);

    return hours;
}

however latest C# [runtime] will zero such [e.g. int hours;] allocation without need to explicitly write assignment to zero
assuming scalar is not nullable [NRT]
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae7e6702-76f9-4afa-ece2-577eb409bbca
* Version Independent ID: 7a94dd73-480e-287b-4000-851f410f4451
* Content: [The Task Asynchronous Programming (TAP) model with async and await'](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/task-asynchronous-programming-model)
* Content Source: [docs/csharp/asynchronous-programming/task-asynchronous-programming-model.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/task-asynchronous-programming-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @DickBaker 

Yes, the runtime does zero out memory. However, C#'s rules for definite assignment require that `hours` be assigned before it's read.  See [SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAVgNwFgBQWkDYEAcCuAPAJYB2ALgHxwDiAplVLgPIBmAKgEqMDOAVwA2VAIL8AnhQDGACgCUWAN5ZKVOAAsA9oIBO/DJigBOYgDoAIo2EBDSXJgKjOAOxbdBowF8gA==)

I'll close this.
