### ISSUE TITLE
How to register ServiceBus Sender with Microsoft.Extensions.Azure extensions

### ISSUE THREAD

**Issue by vlflorian** [dotnet/docs#34621]
Hi,

How should we use the DI extensions provided by Microsoft.Extensions.Azure to register a ServiceBusSender? 
It is possible to register a **ServiceBusClient** like so: 

```csharp
        builder.services.AddAzureClients(builder =>
        {
            builder.AddServiceBusClient(serviceBusConnectionString);
        });
```

and then inject a `IAzureClientFactory<ServiceBusClient> serviceBusClientFactory` or a `ServiceBusClient` directly into a class, but I see no such option or example anywhere on how to do the same for a ServiceBusSender. The only option I see is to inject the ServiceBusClient into my service and call `serviceBusClient.CreateSender(topicName)`, but that goes against the [best practices](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients), which tell us to also register the ServiceBusSender as a singleton. 

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0e2a2da-cb07-a454-dbfa-7349007812a2
* Version Independent ID: 2cbfee72-6851-6224-fd83-1819515926a9
* Content: [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection)
* Content Source: [docs/azure/sdk/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/dependency-injection.md)
* Product: **dotnet-azure**
* GitHub Login: @alexwolfmsft 
* Microsoft Alias: **alexwolf**

**Comment by fijsh** [comment]
I'm struggling with the same question.
