### ISSUE TITLE
Did I miss it?  Something missing from the image

### ISSUE THREAD

**Issue by nocodejim** [dotnet/docs#34625]
hey, i went through this page twice on a couple of different machines today and I ran into the exact problem on both of them.  So perhaps I made the exact same mistake 2 times or it is outdated/missing something.

**the docker image gives this error (in docker desktop and PS)**
PS C:\TMP\docker-working\App> docker run -it --rm counter-image
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'DotNet.Docker.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Here is my docker file that created the image**
`FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]`

**I confirmed SDK on my box**
PS C:\TMP\docker-working\App> dotnet --list-sdks
7.0.100 [C:\Program Files\dotnet\sdk]
7.0.104 [C:\Program Files\dotnet\sdk]

**And finally, here is my dir -r to show the files in the folder I was operating from**
[directorycontent.txt](https://github.com/dotnet/docs/files/10994981/directorycontent.txt)

I hope I covered everything

Thanks,

Jim

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 71043](https://dev.azure.com/msft-skilling/Content/_workitems/edit/71043)

**Comment by nocodejim** [comment]
Sorry, that yaml pasted like trash.
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]

**Comment by IEvangelist** [comment]
Hi @nocodejim - I just ran through this myself, and verified that the contents in the article are correct/accurate/functioning. As for what you've pasted, that appears to be correct also.

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]
```

What is the name of the _.dll_ that you have in your bin directory? If that isn't _DotNet.Docker.dll_ I'd expect the error you're seeing.

**Comment by nocodejim** [comment]
Hey, I really appreciate you hopping on this and trying it out!

Per my attachment - Dotnet.Docker.dll is all over the place but the most relevant entries are

    Directory: C:\TMP\docker-working\**App\bin\Release\net7.0**


Mode                 LastWriteTime         Length Name                                                                                                                                                                          
----                 -------------         ------ ----                                                                                                                                                                          
d-----         3/16/2023  10:23 AM                publish                                                                                                                                                                       
-a----         3/16/2023  10:23 AM            431 Dotnet.Docker.deps.json                                                                                                                                                       
-a----         3/16/2023  10:23 AM           6144 **Dotnet.Docker.dll**                                                                                                                                                             
-a----         3/16/2023  10:23 AM         154112 Dotnet.Docker.exe                                                                                                                                                             
-a----         3/16/2023  10:23 AM          10688 Dotnet.Docker.pdb                                                                                                                                                             
-a----         3/16/2023  10:23 AM            253 Dotnet.Docker.runtimeconfig.json                                                                                                                                              


    Directory: **C:\TMP\docker-working\App\bin\Release\net7.0\publish**


Mode                 LastWriteTime         Length Name                                                                                                                                                                          
----                 -------------         ------ ----                                                                                                                                                                          
-a----         3/16/2023  10:23 AM            431 Dotnet.Docker.deps.json                                                                                                                                                       
-a----         3/16/2023  10:23 AM           6144 **Dotnet.Docker.dll**                                                                                                                                                             
-a----         3/16/2023  10:23 AM         154112 Dotnet.Docker.exe                                                                                                                                                             
-a----         3/16/2023  10:23 AM          10688 Dotnet.Docker.pdb                                                                                                                                                             
-a----         3/16/2023  10:23 AM            253 Dotnet.Docker.runtimeconfig.json  

Here is the docker image files in this screenshot.
![Capture](https://user-images.githubusercontent.com/94468431/225934801-278217fc-3967-48d1-8cf1-0875d737f636.PNG)

I could ask a more competent developer to try it out and perhaps I missed a step in both instances.

If it looks like my data is correct and available, then maybe there is nothing wrong with the page.

If you can't think of anything obvious based on this info, let me know and I will close the issue.

Thanks,
Jim

**Comment by IEvangelist** [comment]
I'm going to close this issue as op-error.
