### ISSUE TITLE
Introduce Robust Programming in Delegate C# Programming Guide

### ISSUE THREAD

**Issue by echoix** [dotnet/docs#34636]
In the page How to declare, instantiate, and use a delegate - C# Programming Guide, there is a section named Robust Programming, but it isn't introduced and for a first time reader, it's difficult to understand what is "Robust Programming" that is being talked.

A sentence or two explaining the section that will be talked (what it does, or why following the following is important) would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b07199-b747-9596-1d38-3257f43b4833
* Version Independent ID: d162375c-ef5a-41c1-fe26-2e6394bf1df1
* Content: [How to declare, instantiate, and use a delegate - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate#robust-programming)
* Content Source: [docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/delegates/how-to-declare-instantiate-and-use-a-delegate.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 357258](https://dev.azure.com/msft-skilling/Content/_workitems/edit/357258)

**Comment by BillWagner** [comment]
Thanks for the comments @echoix 

I've added this to our backlog for our next update to this article

**Comment by echoix** [comment]
Later I saw that this pattern of "robust programming" was repeated other sections in the equivalent articles. It could be in the backlog too.
