### ISSUE TITLE
"Deploy Image to Azure Container Instances" does not show up when right clicking on Mac

### ISSUE THREAD

**Issue by rezarajabii** [dotnet/docs#34690]
On section "Deploy as container instance" with `vscode`, the `Deploy Image to Azure Container Instances` does not show up on the docker extension on vscode, 

---
<img width="282" alt="Screenshot 2023-03-22 at 15 28 16" src="https://user-images.githubusercontent.com/7240964/226935958-3b217094-f289-4c50-a2e6-861735f3ffc1.png">

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01da871e-271f-a56e-c0c8-69ae4e19ef29
* Version Independent ID: 582f6863-9999-6962-af30-03e497f485f8
* Content: [Deploy a Worker Service to Azure - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/cloud-service)
* Content Source: [docs/core/extensions/cloud-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/cloud-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 72810](https://dev.azure.com/msft-skilling/Content/_workitems/edit/72810)

**Comment by IEvangelist** [comment]
Hi @rezarajabii - thank you for posting this issue, I was unware of the change, but I did confirm that ACI support was removed, and instead they're now suggesting Azure Container Apps. See https://github.com/microsoft/vscode-docker/issues/3655. I'll work on updating this.
