### ISSUE TITLE
" The default location on Linux and macOS is /usr/local/share/dotnet"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [dotnet/docs#34703]
I suspect that this may vary by OS.  On Ubuntu 22.04 (installed in WSL), using dotnet from the MS 22.04 rather than the ubuntu repository, the default seems to be "/usr/share/dotnet".

I think that the default Ubuntu packages may set "DOTNET_ROOT=/usr/lib/dotnet", which is different again; I noticed that e.v. was set and was causing a problem when moving from Ubuntu 22.04 versions of .NET packages to MS' 22.04 versions.   

See also discussion at https://github.com/dotnet/core/issues/7699 and https://github.com/dotnet/runtime/issues/79237 .   The e.v. was set via dotnet.sh in /etc/profile.d; my guess is that it was when I installed something that used .NET a couple of months ago.  See especially https://github.com/dotnet/runtime/issues/79237#issuecomment-1344527435 , but for the purposes of the documentation here it'd be great to give enough information to locate it, maybe even as simple as "locate host/fxr".

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1fab316-eb04-50f5-03c8-bf3004981d3e
* Version Independent ID: 0c8e3542-470a-fa11-0d27-061384c4c3ba
* Content: [.NET environment variables - .NET CLI](https://learn.microsoft.com/en-gb/dotnet/core/tools/dotnet-environment-variables#net-sdk-and-cli-environment-variables)
* Content Source: [docs/core/tools/dotnet-environment-variables.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-environment-variables.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 81749](https://dev.azure.com/msft-skilling/Content/_workitems/edit/81749)

**Comment by tdykstra** [comment]
@SomeoneElseOSM Thanks for these suggestions.  I'm editing the description in the article to be more accurate and provide links to helpful resources.
