### ISSUE TITLE
Claim that TrimMode=full is the default in .NET 7 is not true for WASM.

### ISSUE THREAD

**Issue by ScarletKuro** [dotnet/docs#34714]
The documentation claims that the `full` is the default TrimMode in .NET 7, quote from the doc: `In .NET 7, <TrimMode>full</TrimMode> is the default`.
For WASM projects it's not true.
In fact, if you set `TrimMode`=`full` for WASM, it will break your application : https://github.com/dotnet/aspnetcore/issues/41252#issuecomment-1290905650

If you open the props: `C:\Program Files\dotnet\sdk\7.0.XXX\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.Current.props` you will that the default is `partial`.

This is a problem, because if someone will read the documentation and set `<TrimMode>full</TrimMode>` in his WASM project manually, thinking that it's the default, he will get a non working application.
Also, people might migrate from .NET6 to .NET7, the TrimMode options that were in .NET6 do not exist in .NET7 anymore, and by looking in documentation they will just set the full mode which also will lead to the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 811fc2ce-1f05-5be2-d033-7fce35e49525
* Version Independent ID: fca1c728-4716-8c28-89e1-02eb947bf602
* Content: [Trimming options - .NET](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options)
* Content Source: [docs/core/deploying/trimming/trimming-options.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/trimming/trimming-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @sbomer
* Microsoft Alias: **svbomer**

---
[Associated WorkItem - 143919](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143919)

**Comment by gewarren** [comment]
I think we just need to clarify [here](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#trimming-granularity) that `<TrimMode>partial</TrimMode>` is the default for console apps only. @agocke would you agree? We could also add a See also link to https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies.
