### ISSUE TITLE
String in C#

### ISSUE THREAD

**Issue by dersavage** [dotnet/docs#34725]
The tutorial is very well-done, congrats. My suggestions reflect only my personal preference. YMMV:

- The tutorial is short-ish. There is a lot more to strings. Increasing the tut length to thrice its current one would be best.
- Examples are fine but don't culminate into something meaningful. A larger project would be welcome.
- The challenge is too easy. 

Other than this, it is a great way to attract coders to adopt C#. Well done. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8053bb96-cc40-8369-c07f-f9fd14060c1e
* Version Independent ID: 293260e2-f444-537b-0ba7-14d1fb6ebcf2
* Content: [Hello World - Introduction to C# interactive C# tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/hello-world.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @dersavage 

Those are valid points. These introductory tutorials are designed for beginners, and are designed as a short overview.

I'll be working on the next set of tutorials called "Everyday C#" that will address all these concerns. The goal of the journey is to give people a short overview of the concepts developers use every day. Then, they can continue to learn more about those concepts, both in depth and breadth. 

I'll close this without action, as I'm already building the project and task list for those next set of tutorials.
