### ISSUE TITLE
Add documentation about launchSettings.json

### ISSUE THREAD

**Issue by KyleMit** [dotnet/docs#34726]
## **Help us make content visible**

I searched for "launchSettings.json" / "launchSettings Specification", but nothing wholistically covered the available options, properties, and settings.

For example, the `commandName` can be any of the following values: 

`"Executable"`, `"Project"`, `"IIS"`, `"IISExpress"`, `"DebugRoslynComponent"`, `"Docker"`, `"DockerCompose"` 

But I can't find any MS Docs Documentation that spells all that out (along with the other properties)

I do see the following articles - but each only covers launch settings within the scope of its own use case, and none link to the actual spec for launchsettings

* [launchSettings.json support](https://learn.microsoft.com/en-us/visualstudio/mac/launch-settings?view=vsmac-2022) (VS for Mac only)
* [Use multiple environments in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-7.0#lsj) (Focus on multiple envs)
* [Visual Studio Container Tools launch settings](https://learn.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2022) (Containers Only)
* [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#environment-variables-set-in-generated-launchsettingsjson) (Docker Only)
* [Configuration providers](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#environment-variables-set-in-launchsettingsjson) (Configuration Hierarchy Only)

## **Describe the new article**

The _unofficial_ json schema spec comes pretty close to documenting what's needed here

https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/launchsettings.json

Ideally, it would be the other way around, the spec would inform the schema definition, not the schema definition being the source of truth.

The doc could maybe live in Learn > .NET > Fundamentals > Configuration

### Table of Contents

* Profiles
  * commandName
  * commandLineArgs
  * executablePath
  * workingDirectory
  * launchBrowser
  * launchUrl
  * environmentVariables
  * applicationUrl
  * nativeDebugging
  * externalUrlConfiguration
  * use64Bit
  * ancmHostingModel
  * sqlDebugging
  * jsWebView2Debugging
  * leaveRunningOnClose
  * remoteDebugEnabled
  * remoteDebugMachine
  * authenticationMode
  * hotReloadEnabled
  * publishAllPorts
  * useSSL
  * sslPort
  * httpPort
  * dotnetRunMessages
  * inspectUri
  * targetProject
* IisSettings
  * windowsAuthentication
  * anonymousAuthentication
  * iisExpress
    * applicationUrl
    * sslPort
  * iis
    * applicationUrl
    * sslPort

**Comment by gewarren** [comment]
@IEvangelist Perhaps you're interested in taking this one?

**Comment by KyleMit** [comment]
@IEvangelist - how is this specific to Visual Studio?  It's also leveraged for VS Code as well, and other non-MS tools like Rider leverage launch settings files too.

**Comment by KyleMit** [comment]
oh thanks @IEvangelist - 100% my error - I was confusing `launch.json` in VS Code with `launchSettings.json`.  It might still be used by third party tooling, but was definitely confused about which part was getting consumed by VS Code

**Comment by IEvangelist** [comment]
Closing this as the op confirmed they were confusing it with _launch.json_ from VS Code.
