### ISSUE TITLE
Documentation on My has no links

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#34734]
This page is pretty useless. Why on earth aren't there links from it to pages describing Me, My.... in detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f52784-f9fa-b1e9-f123-3ef94f29aea5
* Version Independent ID: 608407bc-8615-7c6e-1771-b4340c06d6ce
* Content: [Me, My, MyBase, and MyClass - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/me-my-mybase-and-myclass?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vb.My)%3Bk(DevLang-VB)%26rd%3Dtrue)
* Content Source: [docs/visual-basic/programming-guide/program-structure/me-my-mybase-and-myclass.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/program-structure/me-my-mybase-and-myclass.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by LWChris** [comment]
Where would you want these links to go? This _is_ the page with detailed information to the keywords. In fact, the `Me` link on the [Keywords](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/keywords/) reference page takes to you this page, while `MyBase` and `MyClass` take you to the [Inheritance Basics](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/objects-and-classes/inheritance-basics), which is the only "See also" link.

Do you have any known page that should be linked to? Or are you missing any information (which?) that you assumed would be on a different page (which probably doesn't exist)?

**Comment by ptoye** [comment]
For example, https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/objects/my-settings-object.
There seems to be no way from the Me, MyBase ..... page to pages which give the details of the My.xxx objects. I agree that MyBase and MyClass probably don't need more information, so my comment was a bit harsh. But I was trying to find out what My.xxx object there are, and had reached a brick wall.

Sorry for the late response - for some reason I don't get notifications about messages here even for topics I've subscribed to.
