### ISSUE TITLE
Documentation wording

### ISSUE THREAD

**Issue by Arthur-Fedotiev** [dotnet/docs#34744]
"As a small example, consider an assembly that contains the following code:" - assumes that below will be found .exe/.dll code which is not the case, as in fact it is c# code.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [A tour of C# - Overview](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @Arthur-Fedotiev 

I've added it to our backlog to address when we next update this article.
