### ISSUE TITLE
Missing variable declaration

### ISSUE THREAD

**Issue by randz-argonillo** [dotnet/docs#34742]
Please check the code in this section https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/cancel-an-async-task-or-a-list-of-tasks#update-application-entry-point. The `sumPageSizesTask` variable was not declared and assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a312caf-8888-ac36-e01f-70c9f07c920d
* Version Independent ID: 49472388-9b27-78b4-aafa-6a6d82f96d24
* Content: [Cancel a list of tasks](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/asynchronous-programming/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @randz-argonillo We'll get this fixed.
