### ISSUE TITLE
Shift Operators should include information about defined behaviour for negative rhs

### ISSUE THREAD

**Issue by sewbacca** [dotnet/docs#34768]
[Enter feedback here]
Since I believe in C++ negative shifts (rhs operand) do nothing, but positives do.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa
* Version Independent ID: 2410c828-0c66-9efe-ae87-9b07708aa731
* Content: [Bitwise and shift operators - perform boolean (AND, NOT, OR, XOR) and shift operations on individual bits in integral types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators)
* Content Source: [docs/csharp/language-reference/operators/bitwise-and-shift-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @tannergooding for the specified behavior.

(I can observe what happens, but I couldn't find what behavior is guaranteed)

**Comment by tannergooding** [comment]
> Since I believe in C++ negative shifts (rhs operand) do nothing

C and C++ both leave this as strictly undefined behavior. Any two implementations can do different things as can the behavior on different architectures (e.g. x86 vs x64 vs Arm32 vs Arm64 vs RISC-V, etc)

Specifically in `8.8 Shift Operators` of the C++ language spec:
> The behavior is undefined if the right operand is negative, or greater than or equal to the length in bits of the promoted left operand.

and `6.5.7 Bitwise shift operators` of the C language spec:
> If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined.

----------------------

> ping @tannergooding for the specified behavior.

This is already documented under https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md#shift-count-of-the-shift-operators. It's possible the documentation could be reworded to make this even more explicit, but its already called out in the first paragraph of each of the shift operator sections (search for `shift count`).

The behavior is that C# explicitly masks the shift amount to within range. That is, for `int` and `uint` it `x << y` is effectively `x << (y & 0b0001_1111)` while for `long` and `ulong` it is effectively `x << (y & 0b0011_1111)`.

.NET itself has no such requirement and so `user-defined shift operators` "may" have their own behavior that differs from the C# language spec.

**Comment by pkulikov** [comment]
@BillWagner @tannergooding @sewbacca I think the current documentation already mentions the behavior for the negative `rhs` (or `count` as it's called in the article) by stating that right-hand side value can be of any `int` (which means that it might be negative). However, if you find it necessary, I can add the mention of it.

What do you think?

**Comment by tannergooding** [comment]
The docs could maybe be updated to explicitly call out negative values or include them in the sample (potentially even not using binary literals, so users can more readily understand the code samples).

But the existing docs do in general cover the fact that values are masked.
![image](https://user-images.githubusercontent.com/10487869/228627283-e0f6c3aa-5c31-4d41-82ed-38ebdc0630fb.png)

**Comment by pkulikov** [comment]
> include them in the sample (potentially even not using binary literals, so users can more readily understand the code samples)

I find it the best update.

**Comment by sewbacca** [comment]
I missed that! So basically the sign is ignored
Thanks for the responses.

**Comment by tannergooding** [comment]
Its not just the sign that's ignored. For `int` the lowest 5 bits are taken, so if you write `x << y`, C# will effectively emit `x << (y & 0x1F)`. Likewise for `long` the lowest 6 bits are taken, so you will effectively get `x << (y & 0x3F)`.

This means that for `int` you're effectively doing taking the `mod 32` of `y`. That is, `x << 32` is the same as `x << 0`. `x << 33` is the same as `x << 1`, etc. Likewise, `x << -1` is the same as `x << 31`, `x << -2` is the same as `x << -2`, etc.
