### ISSUE TITLE
imported architecture eBooks should have friendly names for all images

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3480]
The import process for eBooks often created a blank friendly name and alt-text for images.

This hurts accessibility and alternative rendering formats (phones, tablets)

Whenever a topic is updated, the friendly names should be added.

/cc @CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Can you give me an example on how to add those friendly name and alt-text for images?

**Comment by BillWagner** [comment]
The source for our contributor guide has an example: https://github.com/dotnet/docs/blob/master/styleguide/template.md#static-image-or-animated-gif

You need to add the alt text in the square brackets.

**Comment by mairaw** [comment]
Resolving this one. I coordinated a vendor task last year for this one to use friendly image names and add alt text across our docset, including the e-books.
