### ISSUE TITLE
Code example comment using incorrect int/long sizes

### ISSUE THREAD

**Issue by Jens-G** [dotnet/docs#34827]
> ```
> [System.Runtime.InteropServices.StructLayout(LayoutKind.Explicit)]
> struct TestExplicit
> {
>     [System.Runtime.InteropServices.FieldOffset(0)]
>     public long lg;
> 
>     [System.Runtime.InteropServices.FieldOffset(0)]
>     public int i1;
> 
>     [System.Runtime.InteropServices.FieldOffset(4)]
>     public int i2;
> 
>   // rest omitted
> }
> 
> ```
> 
> 
> The two integer fields, i1 and i2 combined, share the same memory locations as lg. 
> Either lg uses the first 4 bytes, or i1 uses the first 2 bytes and i2 uses the next 2 bytes.

The comment is incorrect. Correct would be:

 Either lg uses the first **8** bytes, or i1 uses the first **4** bytes and i2 uses the next **4** bytes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd0cbc4c-42cd-1abe-c04d-30ca9cf77c61
* Version Independent ID: 99041b24-3e05-43cd-299b-a73928c8133a
* Content: [How to create a C/C++ union by using attributes (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/reflection-and-attributes/how-to-create-a-c-cpp-union-by-using-attributes)
* Content Source: [docs/csharp/advanced-topics/reflection-and-attributes/how-to-create-a-c-cpp-union-by-using-attributes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/advanced-topics/reflection-and-attributes/how-to-create-a-c-cpp-union-by-using-attributes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Jens-G 

I opened a PR to fix this.
