### ISSUE TITLE
Different .NET Framework versions in this document

### ISSUE THREAD

**Issue by darshSWL** [dotnet/docs#34844]
The title of this document is ".NET Framework 4.5 Built-In Activity Library".
The first paragraph starts with ".NET Framework 4.6.1 includes a new activity library".

I don't understand why there is a difference between the mentionend .NET Framework versions. Is this intentional and if so, why?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65a1d7f2-98c5-29e3-31cc-e80c065feffb
* Version Independent ID: 256edadd-f7c9-d5e0-82ab-4fd6f351c6de
* Content: [.NET Framework 4.5 Built-In Activity Library - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/net-framework-4-5-built-in-activity-library)
* Content Source: [docs/framework/windows-workflow-foundation/net-framework-4-5-built-in-activity-library.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-workflow-foundation/net-framework-4-5-built-in-activity-library.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wf**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Thanks @darshSWL. That's because it was using a placeholder instead of the actual version. I've fixed it in #35099.
