### ISSUE TITLE
Register Microsoft Package Repository fails on Elementary OS

### ISSUE THREAD

**Issue by hollyschilling** [dotnet/docs#34852]
[Enter feedback here]

The first line of the script sets the variable `$repo_version`. Unfortunately, it gets the value of 7 when running on Elementary OS 7.0. The result is that the target URL for the next line is `https://packages.microsoft.com/config/ubuntu/7/packages-microsoft-prod.deb`, which returns a 404.

I don't know if the script can be adapted to detect that Elementary OS 7.0 is based upon Ubuntu 22.04, but a note in the code to help others might be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
While I appreciate the suggestion, that OS is outside the scope of our docs. If the .NET team decides to list it as a fully supported OS, we can come back and update things.

Side-note: Thanks for showing me that OS, I'm going to go play with it!

**Comment by hollyschilling** [comment]
I am not suggesting that there should be a scope or procedural changes, but a note on that web page to indicate that Ubuntu-based distros may have issues if they report the version number differently.
