### ISSUE TITLE
Clarify recommendation of async vs. task CE

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#34855]
In the linked docs ("What's new in F# 6"), in the section about the `task` CE, the document currently says:

> In general, you should consider using `task {…}` over `async {…}` in new code if you're interoperating with .NET libraries that use tasks, and if you don't rely on asynchronous code tailcalls or implicit cancellation token propagation.

In [Async programming in F#, section "Core concepts"](https://learn.microsoft.com/en-us/dotnet/fsharp/tutorials/async#core-concepts), it says:

> In general, you should use `async { }` programming in F# unless you frequently need to create or consume .NET tasks.

While there is certainly some agreement between the two statements (the condition about interoperating with .NET tasks), I get the impression that the former generally instructs to prefer `task`, while the latter instructs to prefer `async`. This impression comes across to me strongly enough that I find it confusing and chose to raise this issue.

If the recommendation to use `async` in "Async programming in F#" is correct, I suggest rephrasing the quoted sentence from "What's new in F# 6" to have the same sentiment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2dea170-a8f4-90f6-e578-e406fb43fef1
* Version Independent ID: 885f9f09-d2ff-112c-6dda-9a31bccc0e8a
* Content: [What's new in F# 6 - F# Guide](https://learn.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-6)
* Content Source: [docs/fsharp/whats-new/fsharp-6.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/whats-new/fsharp-6.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
ping @dsyme for recommendations on a proposed change.

**Comment by dsyme** [comment]
@cmeeren Note the F# 6 guidance says:

> ...consider using task {…} over async {…} in new code if 
>   1. you're interoperating with .NET libraries that use tasks, AND
>   2. you don't rely on asynchronous code tailcalls or implicit cancellation token propagation.

So I think that's saying that async is preferred in many "pure F#" coding situations.

**Comment by cmeeren** [comment]
Thanks! Note that with the updated phrasing (which seems identical between the two sources now), I still get the impression that it is generally preferable to use `task`.

For comparison, consider what happens if the phrasing is turned on its head:

> In general, you should consider using `async {…}` over `task {…}` in new code unless you're interoperating with .NET libraries that use tasks and don't rely on asynchronous code tailcalls or implicit cancellation token propagation.

It technically says the same thing with respect to "pure F#" vs. interop coding situations, but the impression is now that `async` is preferred.

This may just be me, though. Feel free to close if you consider this a non-issue.
