### ISSUE TITLE
^M at the end of the completion candidates (in a Bash execution environment)

### ISSUE THREAD

**Issue by per-ok** [dotnet/docs#34860]
Problem
Under Cygwin -- and other Windows shells, I expect -- the bash completion commands output a ^M (CR) at the end of the suggestions.

Suggested solution alternatives.
1 - "The easy way out" for the completion functionality: set IFS=$'\r\n'
2 - Since the source of the CR probably is dotnet.exe: change dotnet.exe to use only the shell's standard line separator. For Bash that would be LF.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [Enable tab completion - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. I'm sorry but I don't know what exactly you would like changed in this article. Can you elaborate?

**Comment by per-ok** [comment]
Yes, some elaboration is needed.

What I would like is that the `IFS` value in the [bash script](https://github.com/dotnet/docs/blob/main/docs/core/tools/enable-tab-autocomplete.md#bash) is changed to `IFS=$'\r\n'`. (This is what I have done.)

**The problem:** When using the currently suggested bash completion setup described, the bash completion mechanism outputs ^M at the end of completion candidates (at least in Cygwin's bash).
The problem appears when `dotnet.exe` is executed in a (Cygwin's) bash environment.  The program sends out CR + LF at the end of each printed line.  When the `IFS=$'\n'` it means that the CR (`$'\r'`) is not (supposed to be) interpreted as a token separator, and since it is the last character on the line it is included in each completion.  It then appears in the completion candidates as ^M.

**Comment by per-ok** [comment]
Yes, some elaboration is needed.

What I would like is that the `IFS` value in the [bash script](https://github.com/dotnet/docs/blob/main/docs/core/tools/enable-tab-autocomplete.md#bash) is changed to `IFS=$'\r\n'`. (This is what I have done.)

**The problem:** When using the currently suggested bash completion setup described, the bash completion mechanism outputs ^M at the end of completion candidates (at least in Cygwin's bash).
The problem appears when `dotnet.exe` is executed in a (Cygwin's) bash environment.  The program sends out CR + LF at the end of each printed line.  When the `IFS=$'\n'` it means that the CR (`$'\r'`) is not (supposed to be) interpreted as a token separator, and since it is the last character on the line it is included in each completion.  It then appears in the completion candidates as ^M.

**Comment by adegeo** [comment]
Reopened...

Hi @per-ok our automation system doesn't detect thumbs up so it was waiting for a physical response. I was alerted that this was closed and so I saw your thumbs up.
