### ISSUE TITLE
Document Snap packages as currently unmaintained

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#34873]
https://github.com/dotnet/sdk/issues/18249#issuecomment-1496464099

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 181168](https://dev.azure.com/msft-skilling/Content/_workitems/edit/181168)

**Comment by adegeo** [comment]
This was mostly fixed in the previous update, but I need to also update the notes about ARM installs that suggest using Snap. Those need an update.
