### ISSUE TITLE
Obsolete documentation

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/docs#34889]
It looks bad when I get my technique for uploading FTP files from a Microsoft site and then Visual studio tells me the technique is obsolete.

> Warning SYSLIB0014 'WebRequest.Create(string)' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a421182a-dac9-c619-b501-240dd2aafd7b
* Version Independent ID: 30940ebd-4501-8580-2efc-c6abf522fe93
* Content: [How to: Upload files with FTP - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/network-programming/how-to-upload-files-with-ftp)
* Content Source: [docs/framework/network-programming/how-to-upload-files-with-ftp.md](https://github.com/dotnet/docs/blob/main/docs/framework/network-programming/how-to-upload-files-with-ftp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment]
The note block at the beginning of the article states that FTP is no longer supported for .NET (Core). It's still supported for .NET Framework, and that's why the article hasn't been retired.

> This article is specific to projects that target .NET Framework. For projects that target .NET 6 and later versions, [FTP is no longer supported](https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated).
