### ISSUE TITLE
**Graphics** has no parameterless constructor. Graphics is built-in class. What am I going to do?

### ISSUE THREAD

**Issue by DGrothe-PhD** [dotnet/docs#34902]
[Enter feedback here]
CS1729 page is too general. What if the class that produces the error is one of **.NET's own classes**? So I cannot provide a parameterless constructor. I am trying to adjust the number of parameters in the call to the constructor, but what if the only way of doing so is by **guessing**? Going to the definition of "Graphics" didn't help either...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 482bd9d6-f2ca-2ea7-38ea-cba64e750248
* Version Independent ID: 2ad3c95a-d46b-40aa-97f9-58e4d4342074
* Content: [Compiler Error CS1729](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1729?f1url=%3FappId%3Droslyn%26k%3Dk(CS1729))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1729.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1729.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @DGrothe-PhD 

The compiler reference docs can't answer every possible instance of a mismatch in constructor parameters. 

For a specific question like this one, I'd check the [Q & A](https://learn.microsoft.com/answers/).  Tag the question with both C#, and the library for the `Graphics` class. If you add a snippet of your code, you should get a specific answer quickly.

I'll close this as not planned.
