### ISSUE TITLE
Examples of projects with unit tests do not work.

### ISSUE THREAD

**Issue by dkazbek** [dotnet/docs#3491]
Examples of unit testing of .NET Standard libraries do not work. I needed to reduce the target version from 2.0 to earlier (I replaced it with 1.0). In the test project, the target .NET Core 2.0 (<TargetFramework>netcoreapp2.0</TargetFramework>). Visual Studio v15.3.4.
Perhaps this is a problem on my part, but maybe it will prove useful to somebody.
https://github.com/dotnet/docs/tree/master/samples/core/getting-started/unit-testing-using-mstest

**Comment by BillWagner** [comment]
@dkazbek Can you run `dotnet --version` and put the output from that in a comment? That will help us diagnose the core issue and help correct it.

Thanks.

**Comment by dkazbek** [comment]
> PM> dotnet --version
> 2.0.0

**Comment by BillWagner** [comment]
@dkazbek Hmmm. It works on my machine with the same versions.  (I did a fresh pull, ran `dotnet test` and the tests all ran.)

Can you post your source online in a gist or somewhere so I can compare? I'd like to get to the bottom of what's not working.

/cc @kendrahavens

**Comment by dkazbek** [comment]
@BillWagner Apparently, the problem was on my side. Now when the project is created, the tests are connected normally and with the version .NET Standard 2.0. Perhaps somehow I updated the versions of frameworks or something else.
I apologize for the inconvenience.
