### ISSUE TITLE
Update Escaping documentation Outdated, Inconsistent And or Incorrect.

### ISSUE THREAD

**Issue by ECartman** [dotnet/docs#34929]
[docs](https://github.com/dotnet/docs)/[docs](https://github.com/dotnet/docs/tree/main/docs)/[standard](https://github.com/dotnet/docs/tree/main/docs/standard)/[base-types](https://github.com/dotnet/docs/tree/main/docs/standard/base-types)/composite-formatting.md
this document is OUTDATED  
we open a request with C#/ .net Folks. they advice that a change was made that change the underline way that Composite Formatting works (since 2019) 
[composite-formatting#escaping-braces](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#escaping-braces)
thence the hole [#escaping-braces](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#escaping-braces) Section is DEPRECATED for .NET Core 3.0 + but still Relevant for .Net Core < 3.0 & for All versions of .Net Framework. (including 4.8) 

Hence the document need to Fork. or state which versions That information is Relevant to.  or add a statement that it is longer applicable for  .NET Core 3.0+

see: 
https://github.com/dotnet/runtime/issues/28649
https://github.com/dotnet/runtime/issues/84533

.NET Core 3.0+
.NET Framework (Any) 

- [ X ] .NET Core
    -  .NET Core (3.0+)
- [ X ] .NET Framework
    -   .NET Framework (all versions? )  
- [ ] .NET Standard

### Reproduction Steps

C# Core 6.0: 
```
Console.WriteLine(string.Format("{{Greeting={0}, YourHex=0x{1:x}}}", "hola", 02123554));
Console.ReadLine();
```
Output:
`
 {Greeting=hola, YourHex=0x206722}
`
C# Framework: 

```
using System;
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(string.Format("{{Greeting={0}, YourHex=0x{1:x}}}", "hola", 02123554));
            Console.ReadLine();
        }
    }
```

Output: 
`
{Greeting=hola, YourHex=0xx}
`
as can be seen here. this is inconsistent with the Documented scenario ( [#escaping-braces](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#escaping-braces) ) 

</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b5f5c7-99f8-e112-a3f4-691548e8fc06
* Version Independent ID: e4b0d61c-a09b-3bf0-1696-1d4472272237
* Content: [Composite formatting](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting)
* Content Source: [docs/standard/base-types/composite-formatting.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/composite-formatting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 145033](https://dev.azure.com/msft-skilling/Content/_workitems/edit/145033)

**Comment by adegeo** [comment]
Hi @ECartman thank you for bringing this to our attention. We (the docs team) had implemented a breaking-change process later in the year after this change was introduced into .NET.

@gewarren As well as updating the doc here, should we also open a new breaking change item with the details so it can be back ported into the breaking change docs?

**Comment by adegeo** [comment]
@gewarren now that I think about it, I don't think this is a breaking change. If anyone had this format string in .NET Framework it would have displayed incorrectly. But now after someone ports their code to .NET, it suddenly works. So it's more of a bugfix than a breaking change.
