### ISSUE TITLE
What the heck is nuget feed and how/where to access it.

### ISSUE THREAD

**Issue by curelom** [dotnet/docs#34925]
The document says the issue can be found in the nuget feed and provides some code to put in there, but the document does not say where one could find the nuget feeds.  I haven't a clue where to find them

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6280ced1-08b7-ca6d-31b6-03a3b35278ce
* Version Independent ID: 2eb5a7e4-5a0e-290e-ec8a-b7cec5257ab5
* Content: [NETSDK1082: There was no runtime pack available - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1082?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1082)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1082.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1082.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
What are the values of <RuntimePack> and <RID> in your error message?
