### ISSUE TITLE
we should document how local tools search for a tool manifest

### ISSUE THREAD

**Issue by JL03-Yue** [dotnet/docs#34932]
For local tools to search a manifest, the search algorithm searches up the directory tree for `dotnet-tools.json` or a `.config` folder that contains a `dotnet-tools.json` file. 

If a tool-manifest cannot be found and the `--create-manifest-if-needed` option is set to false, the `CannotFindAManifestFile` error is thown out, as it says there isn't any tool manifest in the directory tree. 

If a tool-manifest cannot be found and the `--create-manifest-if-needed` option is set to true, the program create a manifest automatically. The --create-manifest-if-needed will use the following priority to choose the folder where the tool manifest goes:
            1. Walk up the directory tree searching for one that has a.git subfolder
            2. Walk up the directory tree searching for one that has a .sln/git file in it
            3. Use the current working directory

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET tools - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-tools.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 88396](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88396)

**Comment by tdykstra** [comment]
When will the `--create-manifest-if-needed` option be available -- in which .NET 8 preview? Only in the `dotnet tool install` command?

**Comment by JL03-Yue** [comment]
@tdykstra It was available in 8.0.1xx-preview4. Yes, currently it only appears in `dotnet tool install`.
