### ISSUE TITLE
Clarify usage of implicit typing for nested generic types / LINQ.

### ISSUE THREAD

**Issue by Moskoskos** [dotnet/docs#34940]
According to the coding conventions one should explicitly state the variable type, if the right hand statement doesn't make that clear.

> Don't use [var](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/declarations#implicitly-typed-local-variables) when the type is not apparent from the right side of the assignment.

In the "LINQ" section the quoted convention isn't followed. The reason why is explained in a similar [issue ](https://github.com/dotnet/docs/issues/33892) which is now closed. 
The reason for not declaring the type when dealing with nested generic types or LINQ is understandable. With that I think the reasons for it should come to the readers attention. Either a reference to this particular topic [here](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables), a short summary or what ever seems fit.

Currently it is perceived as a contradiction.

Hopefully I didn't overlook something.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 123091](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123091)

**Comment by BillWagner** [comment]
Thanks for the thoughtful analysis @Moskoskos 

This is a great suggestion, and I've added it to our backlog to address when we next update this article.

**Comment by BillWagner** [comment]
Adding as I'm updating this article in July.
