### ISSUE TITLE
SHA256 documentation is incorrect, lacks detail

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#3495]
# SHA256 documentation is incorrect, lacks detail

# General

The documentation for the first [SHA256](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256) class is incorrect or lacking in the detail needed to call the method.

## Issues with Existing Topics

- For the [SHA256](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256) class documentation, the statement in the Remarks section that "The only implementation of this class is SHA256Managed" is incorrect; there are three implementations, as the **Derived** section at the top of the page indicates.

- For the [SHA256.Create()](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.create?view=netframework-4.7.1#System_Security_Cryptography_SHA256_Create) method, the summary indicates that method creates a default implementation but doesn't indicate wheat that default implementation is.

- For the [SHA256.Create(String)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.create#System_Security_Cryptography_SHA256_Create_System_String_) method, the Parameters section indicates that the string is the name of the specific implementation of SHA256, but it doesn't list valid string values.

**Comment by sputier** [comment]
I start working on this issue right now.

**Comment by sputier** [comment]
@rpetrusha Regarding the first issue you mentioned, should I list the 3 implementations of SHA256 or do you prefer to have something simple, like "This is an abstract class which has 3 implementations".

**Comment by sputier** [comment]
@rpetrusha I just opened PR #3636 to fix this issue.
