### ISSUE TITLE
The article on `Object and Collection Initializers` should mention and explain benefits of `init` and `required`.

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/docs#35014]
I believe the article on [`Object and Collection Initializers`](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers) should mention the [`init` accessor](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init) as well as [`required` modifier](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required).

Specifically, it should be explained how these keywords enable advanced control over initializations, similar to [how this section on `Object Initializers with collection read-only property initialization`](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization) does.

In brief:

`init`: 
- like a ctor param, but also enabling usage of object initializers;
- another take: like a `set` accessor, but only during construction/init time, thus preventing mutability post-creation. 

`requried`: 
- like `init`, but also **must** be set in object initializer, thus preventing only partially constructed objects (and precludes usage in ctor unless `[SetsRequiredMembers]` is used).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0efd6a6a-b52a-f6a2-d98b-f245b55115ff
* Version Independent ID: 95025282-20a0-ded8-c6d2-3b8ffff600c4
* Content: [Object and Collection Initializers - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @konrad-jamrozik 

That's a great suggestion.  I've added it to our backlog for when we update this article. I've also added the "help wanted" label in case anyone wants to submit a PR in the interim.
