### ISSUE TITLE
404 error on software sources

### ISSUE THREAD

**Issue by stringdom** [dotnet/docs#35018]
Sources listed in this page contain wget commands to nonexistent URLs that return 404 errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 88857](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88857)

**Comment by adegeo** [comment]
@stringdom Can you be more specific as to the URL that was produced via running the script?

**Comment by adegeo** [comment]
While I appreciate the suggestion, that OS is outside the scope of our docs. If the .NET team decides to list it as a fully supported OS, we can come back and update things.

Side-note: Thanks for showing me that OS, I'm going to go play with it!
