### ISSUE TITLE
What does the word "restore" exactly mean?

### ISSUE THREAD

**Issue by namasikanam** [dotnet/docs#35016]
As a beginner, I want to know what the command `dotnet restore` does, but the answer seems to be "restoring the dependencies and tools of a project". It sounds like that the same word is used to explain itself, and I am still confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@namasikanam Thanks for the question - I'm expanding the command description in pull request #35027.
