### ISSUE TITLE
Both the error message and explanation have ambiguous wording.

### ISSUE THREAD

**Issue by KevinKilzer** [dotnet/docs#35024]
Is the reference to a buffer of fixed size (i.e., a well-known size), or to a buffer at an unchanging ("fixed") address? Some commas or hyphens might help, but it's just generally too terse of a statement with too many consecutive adjectives. The message says "fixed size buffers", but the explanation is for "fixed sized buffers" (addition of "d"). The suggestion that "fixed" refers to the address is reinforced later when describing the containing class: "The runtime is free to move the unfixed class around...".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 992ecf02-4b42-4704-8ee0-cadb3a2c5d99
* Version Independent ID: 22fb781a-a362-0dbd-d628-4349600c122e
* Content: [Compiler Error CS1666](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1666)
* Content Source: [docs/csharp/misc/cs1666.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1666.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@KevinKilzer from the example it looks like the error is about *fixed-size buffers*:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#fixed-size-buffers

**Comment by BillWagner** [comment]
Thanks for asking this question @KevinKilzer 

Thanks for the PR @pkulikov 

I'll review those shortly.
