### ISSUE TITLE
Incorrect method name in code sample

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/docs#35030]
In the following C# code:
```cs
int num = 0;
var enumerator = RunPagedQueryAsync(client, PagedIssueQuery, "docs").GetEnumeratorAsync();
try
{
    while (await enumerator.MoveNextAsync())
    {
        var issue = enumerator.Current;
        Console.WriteLine(issue);
        Console.WriteLine($"Received {++num} issues in total");
    }
} finally
{
    if (enumerator != null)
        await enumerator.DisposeAsync();
}
```
the following line does not compile:
```cs
var enumerator = RunPagedQueryAsync(client, PagedIssueQuery, "docs").GetEnumeratorAsync();
```
It should be:
```cs
var enumerator = RunPagedQueryAsync(client, PagedIssueQuery, "docs").GetAsyncEnumerator();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2d2f1e2-6b7f-d696-0e67-441c1f4bcfe9
* Version Independent ID: 0910174f-c065-5cb3-3c1a-7d44409903d2
* Content: [Generate and consume async streams](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/generate-consume-asynchronous-stream)
* Content Source: [docs/csharp/asynchronous-programming/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @StephenWeatherford 

And, thanks for the quick PR @pkulikov
