### ISSUE TITLE
Reserved parameter names

### ISSUE THREAD

**Issue by ABi-lab** [dotnet/docs#35078]
The name of parameters should not be "value" if the function is calling any variables from outside of it, such as

`var outterValue1 = "Hello";`
`var outterValue2 = "World";`
`void someFunction(string value)`
`{`
`  Console.WriteLine($"{outterValue1} {outterValue2}! {value}");`
`}`
`someFunction("hello world");`

because the compiler creates the variable "value", which contains the referenced outter variables, automatically, which later causes ambiguity (and in my case also unexpected behaviour). If you attempt to name the parameter as "value", Visual Studio will not warn you about this and will allow you to name the parameter like so.

![image](https://user-images.githubusercontent.com/16656614/233339080-b40f945f-25a6-47e3-a64d-ab5bee0ef196.png)

Here is the same code with the parameter renamed from "value1" to "value":
![image](https://user-images.githubusercontent.com/16656614/233340889-9e8b29da-07b9-4ea4-b523-7011e7b3c265.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0a70d19-0d23-f877-8860-df514cec3c40
* Version Independent ID: 942dbec3-a753-733f-c551-03d203e48969
* Content: [Local functions - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/local-functions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/local-functions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @ABi-lab 

I don't find an example in the article using `value`, or any similar word. Can you point to where the article should be changed?

**Comment by ABi-lab** [comment]
Not changed, I believe it should be pointed out / added.

Regards,

**Comment by BillWagner** [comment]
Thanks for the clarification @ABi-lab 

We should add a recommendation to avoid all reserved words in parameter names.

Also adding the "help wanted" label in case anyone wants to submit a PR before we update this article.

**Comment by BartoszKlonowski** [comment]
I'll be happy to work on that!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski I juast assigned this issue to you,
