### ISSUE TITLE
Updates to Linux docs related to supported OS/.NET versions

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#35085]
References:

- https://github.com/dotnet/core/issues/7998
- https://github.com/dotnet/core/pull/8386

CC: @Falco20019 @leecow @rbhanda 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux distributions - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 86273](https://dev.azure.com/msft-skilling/Content/_workitems/edit/86273)

**Comment by Falco20019** [comment]
Sorry, was out of office. I don't have access to the associated WorkItem.
