### ISSUE TITLE
sub main insufficient information to fix

### ISSUE THREAD

**Issue by hairagon** [dotnet/docs#35095]
[Enter feedback here]

Article tells me to enter name in startup object. that was done
Article tells me that Sub Main maybe in wrong position but does not say where it should be
Application built in VB in Vs 2022, suddenly failed compile with this error, but no fix or information 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5713fca-1a9c-be15-ff3c-b088c83284bd
* Version Independent ID: f1a01693-eea2-23ea-866d-8b245731042b
* Content: ['Sub Main' was not found in '&lt;name&gt;' - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/sub-main-was-not-found-in-name?f1url=%3FappId%3Droslyn%26k%3Dk(BC30420))
* Content Source: [docs/visual-basic/language-reference/error-messages/sub-main-was-not-found-in-name.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/error-messages/sub-main-was-not-found-in-name.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Hi @hairagon 

To get an answer to specific questions like this, I'd post the question with your sample code on the [Q & A](https://learn.microsoft.com/answers/tags/315/vb) site. That's the best way to get a specific answer about what's wrong.

Most of the general guidance is in the [linked article](https://learn.microsoft.com/dotnet/visual-basic/programming-guide/program-structure/main-procedure).

Closing as a product question, not a docs bug.
