### ISSUE TITLE
Blue box about implicit global usings should link to the product doc

### ISSUE THREAD

**Issue by pskirko-google** [dotnet/docs#35090]
There is a blue info box that tells users about the global implicit using statements for certain project types (the part that says 'The .NET 6 SDK also adds a set of implicit global using directives...')

However, that box doesn't link to the actual list of implicit using statements. This is frustrating because it leaves it mysterious as to which global using statements are implicitly added. 

Instead, please just add a link in that info box to the concrete list: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#implicit-using-directives

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7569e51d-92c7-294a-2d5f-e1ab3c35fdf8
* Version Independent ID: 86a1c11a-1d3c-902b-6cf3-5c004c59a856
* Content: [using directive - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)
* Content Source: [docs/csharp/language-reference/keywords/using-directive.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-directive.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @pskirko-google 

I've added this to our backlog, and added the "help wanted" label in case anyone wants to submit a PR before we get to it.
