### ISSUE TITLE
Request for updating `JsonSerializerOptions` reuse recommendation

### ISSUE THREAD

**Issue by MMaxwell66** [dotnet/docs#35101]
According to [this issue](https://github.com/dotnet/runtime/issues/40072) discussion & [this PR](https://github.com/dotnet/runtime/pull/64646), this is now some global cache mitigating this option reuse issue. Could you update the document? At least, the demonstration code there isn't applied anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 279af375-abfa-e10e-046a-625cc14826be
* Version Independent ID: 1df274ad-ecf0-49e7-90c6-e6f05dce0788
* Content: [How to instantiate JsonSerializerOptions with System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/configure-options?pivots=dotnet-7-0)
* Content Source: [docs/standard/serialization/system-text-json/configure-options.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/configure-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 91237](https://dev.azure.com/msft-skilling/Content/_workitems/edit/91237)

**Comment by gewarren** [comment]
Thanks for pointing this out @MMaxwell66! The changes will be live on Monday.
