### ISSUE TITLE
Breaking changes in non-API docs need versioning too

### ISSUE THREAD

**Issue by MV10** [dotnet/docs#35104]
I realize this would be a very large effort, but documentation pages should support versioning similar to the API docs. If that's unreasonable, breaking changes compared to _currently supported_ releases should be documented separately until the "old" way is no longer supported.

Many of us aren't interested in anything but LTS releases. I don't have the time to constantly chase intermediate release changes on my personal projects, and my corporate job prohibits the use of anything but LTS. While it's (sort of) great that MS is doing this rapid-release stuff, it can become a huge waste of time when the docs don't match <ins>supported</ins> products. It's safe to say that most of us appreciate that you're on top of the docs, I know how much of a struggle that is, but it needs to be handled differently.

Case in point:

[Create Windows Service Using BackgroundService](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service)

I guess the use of `AddWindowsService` references .NET 7 changes, or maybe the upcoming .NET 8 -- I wouldn't know because I'm only interested in .NET 6 (the current LTS release) which apparently uses `UseWindowsService` instead. You have _many_ closed issues complaining about that one, such as the closed #34552 describing this exact problem -- which was closed by someone who completely ignored the problem.

Note also the top of that article states ".NET 6.0 SDK or later" which is not true due to the changes mentioned above...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create Windows Service using BackgroundService - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 89422](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89422)

**Comment by gewarren** [comment]
@MV10 We do use versioning in some of our conceptual docs - for example https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation-modes?pivots=dotnet-6-0. I'm not sure if it makes sense to add it to the article you referenced - I'll let @IEvangelist decide. But for the issue you mentioned, it was closed by the original poster.

**Comment by MV10** [comment]
Fair point which I overlooked (obviously).

Still a problem to have docs that don't represent the LTS API, of course, and not just this page. Interesting about that other one you linked, I don't recall seeing that before. Hopefully it's easy to apply!
