### ISSUE TITLE
Error CS0012 - Incorrect explanation for MS VS 2022 - 

### ISSUE THREAD

**Issue by hannibalstgt** [dotnet/docs#35103]
When using Accord.Video.DirectShow; it is not possible to grab a SystemDrawing.Bitmap. that has been caught by Accord process !
What is the solution.
It is impossible to reference CoreCompat.System.Drawing.

![CS0012Error](https://user-images.githubusercontent.com/20060004/233833221-c13df96b-0705-4f94-9579-ce0bc201928a.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93089e43-ae03-83b8-de38-d28db5575aa0
* Version Independent ID: f74a2e43-14fb-7661-6245-56b1625a681a
* Content: [Compiler Error CS0012](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0012?f1url=%3FappId%3Droslyn%26k%3Dk(CS0012))
* Content Source: [docs/csharp/misc/cs0012.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0012.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @hannibalstgt

This is a specific question about the DirectShow library.

I'd open a question on our [Q & A site]*https://learn.microsoft.com/answers/tags/309/csharp), tagging C#. You should get a specific answer there more quickly.

Closing as a product support question
