### ISSUE TITLE
Dead link to ECMA specification 

### ISSUE THREAD

**Issue by JeremyGrosser** [dotnet/docs#35106]
The link to https://visualstudio.microsoft.com/license-terms/ecma-c-common-language-infrastructure-standards/ returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41cd795-9320-ab3c-b2d6-0184fc0985d2
* Version Independent ID: 93459fb6-e4db-8a74-79af-3bc3e606fcbb
* Content: [Common Language Runtime (CLR) overview - .NET](https://learn.microsoft.com/en-us/dotnet/standard/clr)
* Content Source: [docs/standard/clr.md](https://github.com/dotnet/docs/blob/main/docs/standard/clr.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BillWagner** [comment]
Thanks for reporting this @JeremyGrosser 

I've opened PR #35110 to fix it.
