### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by tf9999** [dotnet/docs#35109]
is the code wrong?   should it be:

app.MapGet("/shorten/{redirect}",

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a14cbeaa-a4a8-bb83-8395-3f890755492b
* Version Independent ID: 8c6c6fdc-2422-5fc1-64cd-fd90e51bd349
* Content: [Quickstart: Build your first Orleans app with ASP.NET Core](https://learn.microsoft.com/en-us/dotnet/orleans/quickstarts/build-your-first-orleans-app?source=recommendations&tabs=visual-studio)
* Content Source: [docs/orleans/quickstarts/build-your-first-orleans-app.md](https://github.com/dotnet/docs/blob/main/docs/orleans/quickstarts/build-your-first-orleans-app.md)
* Product: **dotnet-orleans**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by IEvangelist** [comment]
No, the code is correct as is. In ASP.NET Core, the `url` that is given here is passed as a query string. With your suggested way of doing it, it would be part of the route, which doesn't work with encoding a full URL.
