### ISSUE TITLE
Wrong framework version stated for System.Text.Json

### ISSUE THREAD

**Issue by V0ldek** [dotnet/docs#35113]
The docs state that `System.Text.Json` is available for ".NET Framework 4.7.2 and later" (section [How to get the library](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/overview#how-to-get-the-library)), but the NuGet package is specified as compatible with 4.6.1 and later (https://www.nuget.org/packages/System.Text.Json#supportedframeworks-body-tab). This is confusing as to whether the package is actually supported for 4.6.1/4.6.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afa0ecfe-59eb-506f-93c6-bd0883acdb84
* Version Independent ID: fd70dc81-79db-0183-af38-7b8059bbe050
* Content: [Serialize and deserialize JSON using C# - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/overview#how-to-get-the-library)
* Content Source: [docs/standard/serialization/system-text-json/overview.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tdykstra Do you know anything about this discrepancy?

**Comment by tdykstra** [comment]
4.7.2 is the version quoted to me when I wrote the article. My guess is NuGet is probably correct, but you could ask whoever is currently responsible for supporting STJ.

**Comment by eiriktsarpalis** [comment]
I think it should be, `net462` is the minimum supported TFM in the STJ NuGet package.
