### ISSUE TITLE
Correction on Event ID Listed

### ISSUE THREAD

**Issue by jstnrbchx** [dotnet/docs#35175]
[Enter feedback here]

You have two different events tagged with Event ID 33.  The Event GCTriggered should be event 35 instead of 33.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62f15aec-6700-35a2-096c-9f66fba304da
* Version Independent ID: b5423164-48c6-2d29-422a-6c51664467b5
* Content: [Garbage collection runtime events - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-garbage-collection-events?source=recommendations)
* Content Source: [docs/fundamentals/diagnostics/runtime-garbage-collection-events.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/diagnostics/runtime-garbage-collection-events.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Thanks @jstnrbchx
