### ISSUE TITLE
Add information about verifying the download file

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#35189]
The doc in dotnet/core#8420 is documenting how to verify the downloaded file on mac/linux/windows. These overview install docs should add similar information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET on Windows - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 87513](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87513)

**Comment by mairaw** [comment]
I'll ling to GH doc for now on the website, but let me know when this goes live and I can switch.
