### ISSUE TITLE
Getting "Late bound" warning even when the variable is declared.

### ISSUE THREAD

**Issue by SlideRuleWes** [dotnet/docs#35191]
In my case Visual Studio is raising this warning on the fourth line below even though the variable is declared. Based on the documentation, this should not happen.

        Dim xlApp As Microsoft.Office.Interop.Excel.Application
        Dim xlBook As Workbook
        Dim xlsheet As Worksheet

        xlsheet.Columns("B:C").NumberFormat = "@"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8707a00d-9032-fde4-530f-6359dac34c65
* Version Independent ID: a8e7a82d-26c4-e765-a139-4fac1d880b66
* Content: [Late bound resolution; runtime errors could occur - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/late-bound-resolution;-runtime-errors-could-occur?f1url=%3FappId%3Droslyn%26k%3Dk(BC42017))
* Content Source: [docs/visual-basic/language-reference/error-messages/late-bound-resolution;-runtime-errors-could-occur.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/error-messages/late-bound-resolution;-runtime-errors-could-occur.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KlausLoeffelmann** [comment]
Thanks for reporting this!
Could you provide a bit more context?

* Which version of Visual Studio are you using?
* What framework version does your project target?
* Can you upload a minimal repro project, so we could take a look at the sample with more context?

Thank you!

**Comment by SlideRuleWes** [comment]
I am using Visual Studio Community 2022 (64-bit) Version 17.5.5. 
I'm targeting .Net Framework 4.8.
My first try at a minimal project did not reproduce the error, but I will try again. Thank you!

**Comment by BillWagner** [comment]
Hi @SlideRuleWes 

Any luck on a smaller repo scenario? Thanks
