### ISSUE TITLE
Typo in lambda parameters documentation

### ISSUE THREAD

**Issue by devoctane80** [dotnet/docs#35206]
In this sentence:
> Or, you can use implicitly typed variables with var declarations to define the delegate type. The compile synthesizes the correct delegate type.

"The compile synthesizes" should be "The compiler synthesizes"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - Lambda expressions and anonymous functions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Adi9235** [comment]
Hi , Can i work on this issue?

**Comment by pkulikov** [comment]
@BillWagner this is fixed by #35264

**Comment by BillWagner** [comment]
Thanks for the catch @pkulikov 

Closing as fixed in referenced PR.
