### ISSUE TITLE
A possible mistake while suggesting the error  

### ISSUE THREAD

**Issue by MirwaisAkrami** [dotnet/docs#35219]
Hi,
I have this piece of code and I think it will return at least a value in any possible scenario

```
public Concept traverseConcepts(IList<Concept> concepts, Concept topmostConcept)
{
            ICollection<Conceptnoderelation> parentConcepts = topmostConcept.Conceptnode.ParentConceptnode;
            if(parentConcepts.Count() < 1) 
            {
                return topmostConcept;
            }

            foreach(Conceptnoderelation parentConcept in parentConcepts)
            {
                IEnumerable<Conceptnoderelation> nonSideconceptParentnodes = parentConcepts.Where(x => concepts.Any(y => y.ConceptnodeId == x.ConceptnodeId && !y.Issideconcept));
                if(nonSideconceptParentnodes.Count() == 0)
                {
                    return topmostConcept;
                }
                else
                {
                    return traverseConcepts(concepts, concepts.Where(x => x.ConceptnodeId == parentConcept.ConceptnodeId).FirstOrDefault());
                }
           }
}
```
But the vscode c# extension gives an error that not all paths return a value. can yo please check this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 206b5eae-0d27-4afc-ac55-b3c1705096db
* Version Independent ID: f3763810-1049-afbe-f279-fa72ea36a99c
* Content: [Compiler Error CS0161](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0161)
* Content Source: [docs/csharp/misc/cs0161.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0161.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @CyrusNajmabadi 

Should this issue be moved to the roslyn repo?

**Comment by CyrusNajmabadi** [comment]
I don't see any problem with the compiler giving an error here. It can't prove that the end of the method is not reachable, so it has to assume it is. And so it gives an error.

**Comment by CyrusNajmabadi** [comment]
An easy fix is to remove the if-statement entirely, then add `return topmostConcept;` after the foreach.

**Comment by BillWagner** [comment]
closing as by-design.
