### ISSUE TITLE
More than one instance of `IHttpClientFactory`?

### ISSUE THREAD

**Issue by vmelamed** [dotnet/docs#35247]
In certain scenarios, it is possible to end up with two different instances of `IHttpClientFactory` even so singleton per service provider. E.g. in two different code paths, we have something that can be minimized to `new ServiceCollection().AddHttpFactory().Build();` (I understand that this is not advisable!).

What might be the adverse effects of that anyway?

(Sorry, if this is not the correct forum for this question! Can please, forward it to the right place if necessary.)

Val

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46af0b96-2d12-9cac-2f8f-15eb49d0292d
* Version Independent ID: 33db41be-42f9-bb94-65fe-0cf7d1c64f12
* Content: [Use the IHttpClientFactory - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
* Content Source: [docs/core/extensions/httpclient-factory.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/httpclient-factory.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
An app should have a single `IServiceProvider` instance. If you manually create new ones, using

```cs
new ServiceCollection().AddHttpFactory().Build();
```

... that's your prerogative, but as you mentioned it's not advisable, nor are things going to work as designed. Instead, avoid having multiple service providers, and it's a non-issue. I'm going to close this as a non-docs issue. Also, I believe that the product team would likely say the same thing.
