### ISSUE TITLE
Very clear

### ISSUE THREAD

**Issue by alankdkd** [dotnet/docs#35258]
[Enter feedback here]
The content was very clear and informative.  The examples were simple which made them easy to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91094f7e-18ba-59d2-161c-8d354fff9d99
* Version Independent ID: 2139185a-2755-5ce3-e943-665065665e39
* Content: [Walkthrough: Writing Queries in C# (LINQ)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/walkthrough-writing-queries-linq.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the kind words @alankdkd. We appreciate it.

Closing as kudos.
