### ISSUE TITLE
Usage of *.pubxml properties with dotnet publish

### ISSUE THREAD

**Issue by MisterNobody123** [dotnet/docs#35276]
The documentation states that the following properties in _*.pubxml_ files are not honored by `dotnet publish`:
- `LastUsedBuildConfiguration`
- `Configuration`
- `Platform`
- `LastUsedPlatform`
- `TargetFramework`
- `TargetFrameworks`
- `RuntimeIdentifier`
- `RuntimeIdentifiers`

However, when I use the command with no options but a publish profile (`dotnet publish -p:PublishProfile=MyProfile`), it appears to me that at least `Configuration`, `TargetFramework` and `RuntimeIdentifier` are very well honored.

Is the documentation up-to-date in this regard? Unfortunately, I don't have the expertise to cross-check the code base of the utility.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by baronfel** [comment]
They are not fully honored - the timing is such that certain properties that are critical to the build process (especially some build output paths) are not honored. We in the CLI would need to implement a two-phase publish like VS does, where we first identify the Publish Profile to be used, and then use its properties as inputs to the 'real' publish call, before we could change this documentation. This is something I'd like to do for .NET 8 but it is not yet certain if we will be able to do this.
