### ISSUE TITLE
code example should not include 'Attribute' in the class name

### ISSUE THREAD

**Issue by LeftofZen** [dotnet/docs#35287]
code example should not include 'Attribute' in the class name. correct code:

`[assembly: AssemblyVersion("4.3.2.1")]`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3caeaa7-8d3c-eac3-2e49-5129a956c266
* Version Independent ID: 3839cfc8-188f-b57a-0726-f4c6fe0402fc
* Content: [CA1016: Mark assemblies with AssemblyVersionAttribute (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1016)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1016.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1016.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The code is correct as written. It's also okay to exclude "Attribute" from the end of the attribute's name. See the note block at the end of this section: https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/reflection-and-attributes/#using-attributes.
