### ISSUE TITLE
missing help for some source generator errors

### ISSUE THREAD

**Issue by danmoseley** [dotnet/docs#35297]
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1040-1049
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1070-1089

exist, but nothing for the Com interop source generator eg SYSLIB1090 nor the Config source generator eg SYSLIB1100

the live list of what the implementation has is 
https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md?plain=1#L210

@gewarren not sure whether this issue should be here or dotnet/docs, as presumably dev need to supply the text.

related https://github.com/dotnet/runtime/issues/85181

---
[Associated WorkItem - 89919](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89919)

**Comment by danmoseley** [comment]
as mentioned in linked issue, the product should link to `https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/<CODE>.md` and docs should either have a page for each or use redirection to a different page that groups several.

this issue tracks adding the content, which should be supplied by the owners of the COM Interop source generator (@jkoritzinsky ?) and he configuration source generator (@layomia )

**Comment by gewarren** [comment]
I've created really basic documents - it would be great if more info could be added.

https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1090-1099
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1100-1118

**Comment by danmoseley** [comment]
Cc @ericstj  as owner of the config generator in case there is more to add.
Otherwise maybe we can close.

**Comment by ericstj** [comment]
@dotnet/area-extensions-configuration for configuration - folks can improve the doc if they see opportunity.

I see we're missing the ones added for options validation @dotnet/area-extensions-options and some new ones added for JSON @dotnet/area-system-text-json 

https://github.com/dotnet/runtime/blob/bb3597aeaaeb87920b848e71a7b152a202e672bd/docs/project/list-of-diagnostics.md?plain=1#L238-L266

**Comment by danmoseley** [comment]
@jkoritzinsky do the interop ones look OK?

**Comment by tarekgh** [comment]
I have created a PR for options source gen https://github.com/dotnet/docs/pull/37681.

**Comment by tarekgh** [comment]
I have created the PR https://github.com/dotnet/docs/pull/37686 to address the Configuration and Options diagnostics.

**Comment by tarekgh** [comment]
https://github.com/dotnet/docs/pull/37686 is not completed. Thanks @gewarren for your review and feedback

**Comment by gewarren** [comment]
AFAICT, all SYSLIB diagnostics are now documented.
