### ISSUE TITLE
ImpliedUsings SDKs list incomplete

### ISSUE THREAD

**Issue by Szeraax** [dotnet/docs#35300]
ImpliedUsings are enabled by default on Azure Functions .net 6.0 Isolated mode which uses Microsoft.Azure.Functions.Worker and is not listed in the list starting in https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#implicit-using-directives

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET project SDK overview](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#implicit-using-directives)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Szeraax The Azure Functions project uses the Microsoft.NET.Sdk project SDK, so is already covered by the list:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```
