### ISSUE TITLE
wrong repo

### ISSUE THREAD

**Issue by Anouarayazidi** [dotnet/docs#35311]
[اكتب ملاحظاتك هنا] الهاتف لا يستجيب المطلوب ويقف عن عمل 

---
#### تفاصيل المستند الأصلي لتلك المشكلة 

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 10ca6c79-fa2b-762d-a205-5a2255621836
* Version Independent ID: 6d1b3aaf-1ba7-d066-fb81-da5da3694e7f
* Content: [Get started with Azure and .NET](https://learn.microsoft.com/ar-sa/dotnet/azure/intro)
* Content Source: [docs/azure/intro.md](https://github.com/dotnet/docs/blob/main/docs/azure/intro.md)
* Product: **dotnet-azure**
* GitHub Login: #34298 
![Screenshot_2023-05-11-17-21-33-638_lockscreen](https://github.com/dotnet/docs/assets/64561947/72f58b84-dc6c-4738-9766-862ef630cbc2)
@alexwolfmsft.com
* Microsoft Alias: **alexwolf**

**Comment by adegeo** [comment]
Hi @Anouarayazidi I think you asked your question in the wrong repo. Please report issues related to .NET MAUI in the https://github.com/dotnet/docs-maui repo.

Thanks.
