### ISSUE TITLE
<!--Handling click events--> 

### ISSUE THREAD

**Issue by Zorro58** [dotnet/docs#35335]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf84f7a-743b-867a-2ac5-2ab815f10c45
* Version Independent ID: 9b1d1a8a-5151-8e4d-2365-7c859e1bacd8
* Content: [Handling and Raising Events](https://learn.microsoft.com/en-us/dotnet/standard/events/)
* Content Source: [docs/standard/events/index.md](https://github.com/dotnet/docs/blob/main/docs/standard/events/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 91669](https://dev.azure.com/msft-skilling/Content/_workitems/edit/91669)

**Comment by IEvangelist** [comment]
Hi @Zorro58 - what seems to be the issue?

**Comment by IEvangelist** [comment]
Closing this as a non-issue.
