### ISSUE TITLE
Where are the CDXXXX analyzers as described in https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/index ?

### ISSUE THREAD

**Issue by gpetrou** [dotnet/docs#3540]
Perhaps I am missing something, but we are in the process of re-targeting our Desktop app from .NET 4.5 to 4.5.2 and according to https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5-4.5.2 there is a CD0129 analyzer associated with WPF changes. Where is this analyzer exactly? Looking through code analysis ruleset settings in Visual Studio there are no CDXXXX keys.
Are these analyzers somewhere else?
Do the existing docs describe where they are and how to use them?

**Comment by mairaw** [comment]
@rpetrusha @conniey can you look at this issue and provide some guidance to @gpetrou?
Do we have any topic that covers these analyzers? Thanks!

**Comment by conniey** [comment]
@twsouthwick Should we add documentation for .NET Compat Analyzers?

**Comment by gpetrou** [comment]
Apparently, there is https://blogs.msdn.microsoft.com/dotnet/2016/03/03/net-framework-compatibility-diagnostics/
Perhaps include this as part of the documentation or at least add a link to it?
Unless I missed it, but I don't see any mentions of the Microsoft.DotNet.FrameworkCompatibilityDiagnostics somewhere.
Is this an officially supported package? Seems to be outdated with regards to 4.7 and 4.7.1 releases.

**Comment by kingboyk** [comment]
In addition to Microsoft.DotNet.FrameworkCompatibilityDiagnostics being current only up to 4.6.2, it appears that it doesn't work in Visual Studio 2017: 

> CSC : error CD000D: .NET Framework Compatibility Diagnostics requires Visual Studio 2015 with Update 3 applied. Please ensure update is applied before using the diagnostics.

**Comment by netsrotr** [comment]
@kingboyk  same to me :-1:
