### ISSUE TITLE
Genericize language away from "docker"

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/docs#35424]
Might be worth saying "containerize" and referencing less user-hostile options like podman.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=linux)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 91670](https://dev.azure.com/msft-skilling/Content/_workitems/edit/91670)

**Comment by IEvangelist** [comment]
Hi @atrauzzi - thanks for posting this issue. I'm trying to understand what specifically you'd like to see updated here? The article does already say "containerize", but it's based on `Dockerfile` so it seems appropriate to callout Docker.

**Comment by atrauzzi** [comment]
I think the best thing would be to change to `Containerfile` just to ensure that the assets someone produces are always the most agnostic flavour.

**Comment by IEvangelist** [comment]
This is by-design. This content is intended to show readers how to create a .NET app with Docker, and it's part of the Docker table of contents.

![image](https://github.com/dotnet/docs/assets/7679720/dbad2351-d158-4a34-93ea-696fc215facb)

I'm going to close this issue, as it's by-design.
