### ISSUE TITLE
out of date syntax

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#35430]
> You can also use `.[]` to index strings in all versions. The new syntax is preferred.

Should be “use `[]` to index”

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 752405db-4da8-6c06-f58b-22dcc9caa7a7
* Version Independent ID: 78362807-847f-b947-2c75-5036f7765b32
* Content: [Strings - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/strings)
* Content Source: [docs/fsharp/language-reference/strings.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/strings.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by KathleenDollard** [comment]
@daveyostcom I'm not sure what change you'd like. We know that folks in newer F# versions will only use `s[]` but `s.[]` appears in older versions and older code. Would you just like it to be more clear how strong this preference is, or is there something else you are seeing.  The paragraph is:

>You can access individual characters in a string by using array-like syntax. The following examples use [] to index strings. This syntax was introduced in F# 6.0. You can also use .[] to index strings in all versions. The new syntax is preferred.

And thanks for helping make the F# docs better!
