### ISSUE TITLE
Linux AOT Compilation not supported.

### ISSUE THREAD

**Issue by ProIntegritate** [dotnet/docs#35445]
I tried compiling a .NET 7 test binary as Linux-X64 as target (which is said to be supported), but got an error message saying:
"Cross-OS native compilation is not supported."

![image](https://github.com/dotnet/docs/assets/54767353/3aecc1a0-147e-4f6b-adb5-522d8457ffaa)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63476200-2ede-1779-9cc9-1503efec1b36
* Version Independent ID: 54aa95cb-2d5b-85c9-6c34-1fc0348f7cb1
* Content: [Native AOT deployment overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7)
* Content Source: [docs/core/deploying/native-aot/index.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/native-aot/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @LakshanF
* Microsoft Alias: **lakshanf**

**Comment by gfoidl** [comment]
> as Linux-X64 as target (which is said to be supported)

That is supported. But only when the target-OS is the same as the build-OS. Thus you get

> Cross-OS native compilation is not supported.

The docs are correct, but there could be a note about cross-OS building to clarify this.

**Comment by ProIntegritate** [comment]
Ok. And yes a note would be good, also a description on how to achieve this on Linux would be good too. I tried the dotnet command just now on ubuntu and it seems like building is not supported.

Would be better with some official integration of AOT into Visual studio, editing xml configuration files in 2022 feel so 1990's. Feels more like this is some sort of half-documented hack than a real feature.

Anyway, closing this thread.
