### ISSUE TITLE
Ideal article to provide or link to full description of the target field's structure

### ISSUE THREAD

**Issue by StrawberryAnemone** [dotnet/docs#35452]
The few examples here are not enough to allow readers full control of this attribute when they have played around with it and suffered this error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da872c35-1bf3-47fe-f01c-6911aa38298c
* Version Independent ID: fb6a4515-bb56-abf6-e3f5-c3c15738a639
* Content: [IDE0076: Remove invalid global 'SuppressMessageAttribute' - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0076)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0076.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0076.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by steveharter** [comment]
Can you add detail - what APIs and examples are you referring to?
