### ISSUE TITLE
Token: 0x02000001 RID: 1

### ISSUE THREAD

**Issue by asdwffgtg** [dotnet/docs#35479]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: c0d37257-0a35-3a9b-8ee5-c58d00c45642
* Version Independent ID: e7cbf0be-e1da-993d-a9e9-20d1ac9beaed
* Content: [Syntax error (Visual Basic Error) - Visual Basic](https://learn.microsoft.com/ar-sa/dotnet/visual-basic/misc/bc30035)
* Content Source: [docs/visual-basic/misc/bc30035.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30035.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Hi @asdwffgtg 

Can you add more details on this issue? I looked at a translation of your comment, and I'm not sure what you're reporting to us.  Thanks.
