### ISSUE TITLE
Byte numeric promotion example should clarify that 44 is the overflow value of 300 - 256.

### ISSUE THREAD

**Issue by eacarlyle** [dotnet/docs#35485]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9963fd1-083f-1e8c-0656-b04281c64849
* Version Independent ID: 2536ab40-6d7c-1816-19d2-d2dc33991d73
* Content: [Arithmetic operators - C# reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/arithmetic-operators)
* Content Source: [docs/csharp/language-reference/operators/arithmetic-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/arithmetic-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good suggestion. 

I've added this to our backlog, and added the "help wanted" tag to this issue.
