### ISSUE TITLE
[Breaking change]: .NET SDK 8.0.100 will require Visual Studio and MSBuild version 17.7

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#35480]
### Description

Per the published support rules, we update the minimum VS/MSBuild version for each new major release with a one quarter delay. For the GA release, 8.0.100 will require 17.7 to be loaded but only support targeting 7.0 in that version. To target net8.0, customers will have to use 17.8 or newer.

https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules

### Version

.NET 8 RC 1

### Previous behavior

.NET 8.0.1xx-preview1 required 17.4. This was updated to 17.6 in preview4.

See https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/vs-msbuild-version

### New behavior

Starting in RC1, 8.0.1xx will require 17.7 MSBuild/VS versions.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

This is our standard support policy for the SDK as we can't support all prior versions of MSBuild/VS.

### Recommended action

Upgrade the version of Visual Studio being used.

### Feature area

SDK

---
[Associated WorkItem - 118227](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118227)

**Comment by gewarren** [comment]
This should go in the September project.
