### ISSUE TITLE
The specified link for dotnet distro in this page is not found

### ISSUE THREAD

**Issue by cjmakwana** [dotnet/docs#35494]
[Enter feedback here]
Hi,

The link https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb returns 404 (Not found).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by steveharter** [comment]
This is not a valid URI: `https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb` due to `$repo_version`. That will need to be a valid value, such as `23.04`.
