### ISSUE TITLE
Missing guidance on how to configure retry policies when using a static HttpClient

### ISSUE THREAD

**Issue by dimitriskad** [dotnet/docs#35495]
I really like the option to use a limited number of long-lived clients created like that:
```C#
var handler = new SocketsHttpHandler
{
    PooledConnectionLifetime = TimeSpan.FromMinutes(15) // Recreate every 15 minutes
};
var sharedClient = new HttpClient(handler);
```

For real world scenarios one needs to also apply one or more retry policies (e.g. using Polly), ideally without modifying the calling sites (e.g. by wrapping each call with a `retryPolicy.ExecuteAsync(() => _httpClient.GetAsync(url))`.

Based on some [obscure ](https://stackoverflow.com/a/71554659) [references ](https://github.com/App-vNext/Polly/issues/1072#issuecomment-1479067143) on the web, I believe the following should work as intended:
```C#
var retryPolicy = HttpPolicyExtensions
    .HandleTransientHttpError()
    .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));

var socketHandler = new SocketsHttpHandler { PooledConnectionLifetime = TimeSpan.FromMinutes(5) };
var pollyHandler = new PolicyHttpMessageHandler(retryPolicy);
pollyHandler.InnerHandler = socketHandler;

var httpClient = new HttpClient(pollyHandler);
```

I propose that an example on how to add a retry policy when using a static client is added on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a42e9c6-2624-e047-ed1c-03ec047b538a
* Version Independent ID: 3b1dd30f-82a8-2526-bd51-fb6401c52e81
* Content: [HttpClient guidelines for .NET - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines)
* Content Source: [docs/fundamentals/networking/http/httpclient-guidelines.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/networking/http/httpclient-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 143918](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143918)

**Comment by gewarren** [comment]
@dotnet/ncl Does the example for using a retry policy as noted in the issue description make sense to add to the HttpClient guidelines article?

**Comment by gewarren** [comment]
@CarnaViire Does the example for using a retry policy as noted in the issue description make sense to add to the HttpClient guidelines article?

**Comment by CarnaViire** [comment]
Yes, that looks reasonable 👍 let's add this

**Comment by gewarren** [comment]
@dimitriskad Do you want to update the article, or prefer me to?
