### ISSUE TITLE
What about UInt128?

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/docs#35519]
There was a question about UInt128 on StackOverflow:

https://stackoverflow.com/questions/76343478/what-suffix-should-i-use-to-define-uint128-in-f

Maybe the docs should explain that although the types Int128 and UInt128 exist in the BCL, and can even be used in F# by these names, there's no further support for it in F# in the form of literal suffixes or by the lower case types and functions int128 and uint128. At least I haven't found any sign of suffixes existing.

The following is still possible in F#, but probably only if implicit conversion is allowed.

```
let a: Int128 = 1L
let b: Int128 = 2L
let c = a + b
```
Use of `[<Literal>]` with these types seems to be impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3a3edd2-5887-40c7-4feb-0b0cd71f4b8a
* Version Independent ID: 031fc9cd-677b-25a5-f708-f2c2f991e61a
* Content: [Literals - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/literals)
* Content Source: [docs/fsharp/language-reference/literals.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/literals.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by KathleenDollard** [comment]
@vzarytovskii

**Comment by BillWagner** [comment]
Ping @vzarytovskii for thoughts. My recommendation is to close this.

**Comment by vzarytovskii** [comment]
Yeah, I'm also not sure we shouldn't include what doesn't exist, might confuse search engines.
