### ISSUE TITLE
Library support for older frameworks

### ISSUE THREAD

**Issue by joe-shapiro-biz** [dotnet/docs#35544]
[Enter feedback here]
Hi,

At https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support you write:

.NET 7 core libraries packages are supported for use in projects targeting .NET Framework 4.6.2 and later, .NET 6 and later, or .NET Standard 2.0 or later.

But I have been unable to get a Framework 4.8 app to reference a 7.0 class library…

25>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '..\ChauffeurProxyApi\ChauffeurProxyApi.csproj' targets 'net7.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.
25>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '..\StdServiceExchange\StdServiceExchange.csproj' targets 'net7.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.
25>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '..\StdUtilities\StdUtilities.csproj' targets 'net7.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.

What’s the trick?

Many thanks in advance.

-	Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 978b351f-d444-f560-a05b-84cd6a423247
* Version Independent ID: 489dace1-1b51-6e70-6d8c-809d35735b2f
* Content: [.NET 7 breaking change: Library support for older frameworks - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support)
* Content Source: [docs/core/compatibility/core-libraries/7.0/old-framework-support.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/7.0/old-framework-support.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by joe-shapiro-biz** [comment]
Likewise can't reference a .net 7 library from a .net standard 2.1 library

Project '..\n7\n7.csproj' targets 'net7.0'. It cannot be referenced by a project that targets '.NETStandard,Version=v2.1'.

**Comment by gewarren** [comment]
Perhaps you need to have something like this in the project you're trying to reference: https://github.com/dotnet/runtime/blob/9628be4b4b4b38924ae3d051ef2c99dddbece6c0/src/libraries/System.IO.Packaging/ref/System.IO.Packaging.csproj#L3
