### ISSUE TITLE
Consistency and localised language

### ISSUE THREAD

**Issue by sammie-p** [dotnet/docs#35550]
Some ranges are described with 'from' and 'to', while others are described with 'from' and 'through'. The 'through' preposition is not appropriate in this context outside of North American English and should be replaced with 'to'. The range descriptions should also be consistent throughout the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom date and time format strings](https://learn.microsoft.com/en-au/dotnet/standard/base-types/custom-date-and-time-format-strings)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by sammie-p** [comment]
Hi Steve,

It would be unchanged from what you’ve proposed. The preposition ‘through’ is used for movement or to describe a length, or a position or place relative to a noun (the month in your example), but it is not used to describe an inclusive range in number or time (except in American English).

Cambridge explains this in part here: https://dictionary.cambridge.org/grammar/british-grammar/across-over-or-through
Oxford here (point 5): https://www.oxfordlearnersdictionaries.com/definition/english/through_1

Hope this helps.

**Comment by Aykizderya** [comment]
> Bunu bildirdiğiniz için teşekkür ederiz. Merak ediyorum, "ayın daveti.." gibi bir şey nasıl tercüme edilebilir?
