### ISSUE TITLE
java programming 1

### ISSUE THREAD

**Issue by gongarnue** [dotnet/docs#35602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @gongarnue 

I'm not sure what you're looking for in this issue. Can you elaborate?

**Comment by postmeback** [comment]
This issue has been open and idle for last two weeks. Requesting the maintainers to take apt steps on it.
