### ISSUE TITLE
update pages where private protected should be mentioned

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3564]
Taken from [this comment](3478#issuecomment-339464151)

These pages should be reviewed to see if a discussion of `private protected` should be added: 

[event.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/event.md)
[constants.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/constants.md)
[fields.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/fields.md)
[index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/index.md)
[nested-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/nested-types.md)
[object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/object-oriented-programming.md)
[using-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
[using-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-properties.md)

[cs1527.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs1527.md)
[cs3003.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs3003.md)
[cs3001.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3001.md)
[cs3002.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3002.md)
[cs3004.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3004.md)
[cs3005.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3005.md)
[cs3008.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3008.md)

**Comment by sputier** [comment]
I'll take it as soon as #3478 is closed.

**Comment by sputier** [comment]
@BillWagner I just opened the PR #3571 to address this issue.

**Comment by sputier** [comment]
@BillWagner I had taken a closer look to the files listed above. The following pages only need to be updated to have a link to the `protected internal` modifier page : `private protected` is not involved in CLS compliance as members using this access modifier are not visible outside their declaring assembly.

[cs3001.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3001.md)
[cs3003.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs3003.md)
[cs3004.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3004.md)
[cs3005.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3005.md)
[cs3008.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs3008.md)

I think every page related to this issue have been updated as part of the associated PR. Should I remove the "[WIP]" tag in the PR title ?

**Comment by BillWagner** [comment]
@sputier Yes, let's remove the [WIP] in the title, and I'll give it a final review.
