### ISSUE TITLE
Missing information about how to add publish item

### ISSUE THREAD

**Issue by sadeghipour** [dotnet/docs#35683]
I just followed the instruction in order to make a installer but after below paragraph I found it not completed:
_"rom the Custom Actions window, select Install > Add Custom Action."_
below this step looking forward Publish Items from App.WindowsService (Active).
How we can find this file while we or system do not create it before!.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e044209a-0802-07c0-7518-208967a3ef02
* Version Independent ID: 83c4d805-1394-90b7-6def-cf809c33ae22
* Content: [Create a Windows Service installer - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service-with-installer)
* Content Source: [docs/core/extensions/windows-service-with-installer.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service-with-installer.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 98267](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98267)

**Comment by IEvangelist** [comment]
You must have missed the section that calls out that this tutorial is a continuation of a previous tutorial that creates the project in question. I'll make that clearer, thanks.

**Comment by IEvangelist** [comment]
Ah, ok! That is very helpful, I'll be sure to include this in the updates. Thank you.
