### ISSUE TITLE
[NewTopic] Add Allowed Chars to Namespace documentation

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/docs#3569]
# Issue Title

[In the namespace documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace), there is no reference to which characters are allowed/not-allowed.  I think it should be listed here or a link to them.

# General

I just created a new c# library with hyphens in the project name and it converted my namespace to underscores.  Hyphens are very trendy!

## Requests for new Topics

1. Tell us where this topic should go in the Table of Contents.

   - Here, on [the namespace documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace)

2. Write an abstract

   - Allowed chars are: ....
   - Not-allowed chars are: ....

whichever is easier to describe

**Comment by mairaw** [comment]
Thanks @spottedmahn for your feedback. We'll lool into this. This will apply to all identifiers not only namespaces. 

The spec covers some of this (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers) but not in the most friendly way.

**Comment by spottedmahn** [comment]
Thanks @BillWagner!
