### ISSUE TITLE
F1 on '#if' takes me here to 'if'. It may be helpful here to have a see-also '#if'.

### ISSUE THREAD

**Issue by neuronz** [dotnet/docs#35715]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d77f4b78-a6eb-a71c-318f-5059ce12cb6c
* Version Independent ID: 6aec8c74-40c9-ce6b-7554-d1e4b241f061
* Content: [if and switch statements - select a code path to execute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(if_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/statements/selection-statements.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/selection-statements.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 118037](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118037)

**Comment by BillWagner** [comment]
Hi @neuronz 

That's a reasonable idea.

One better solution is if we can route `F1` traffic for `#if` to the correct page.

Ping @CyrusNajmabadi for thoughts. Can Visual Studio use a different F1 code for `if` and `#if`? If so, I'll update the attribute page to use the new code.

**Comment by neuronz** [comment]
Ideally, yes, a much better solution.

There are others that are also in need of F1-routing. For example the ?. (Elvis) operator.

(F1-routing for the @code section of .razor files would also be nice)

**Comment by CyrusNajmabadi** [comment]
@neuronz prs welcome. This would otherwise likely stay in the backlog

**Comment by BillWagner** [comment]
I'll try for a `roslyn` PR to route the `#if` token to the correct page.
