### ISSUE TITLE
Document IsAotCompatible MSBuild property

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs#35722]
**Issue description**

https://github.com/dotnet/sdk/pull/31766 added support for a new MSBuild property to set in libraries: `<IsAotCompatible>true</IsAotCompatible>`. Setting this property defaults the following properties:

* IsTrimmable=true
* EnableTrimAnalyzer=true
* EnableSingleFileAnalyzer=true
* EnableAotAnalyzer=true

If a library wants to be "Native AOT compatible", it can set this one property to enable all the Roslyn analyzers to ensure the library is compatible.

We should add documentation for this property in our docs site. It is similar to `IsTrimmable`, but goes further for AOT. The only docs I could find for `IsTrimmable` is https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#enable-project-specific-trimming. Potentially we could document IsAotCompatible in the sibling section at https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/.

**Target framework**

- [x] .NET Core - only the v8.0+ .NET SDK respects this property
- [ ] .NET Framework
- [ ] .NET Standard

@DamianEdwards @IEvangelist @agocke 

---
[Associated WorkItem - 98749](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98749)

**Comment by voroninp** [comment]
When can library be trimmable but not AOT vompatible?

**Comment by eerhardt** [comment]
> When can library be trimmable but not AOT vompatible?

When it requires dynamically generated code. For example, when it uses IL Ref Emit. The library may only need trim analyzers, and not care about the Aot analyzers.

**Comment by michael-hawker** [comment]
Wanted to say I found it confusing the guidance for library authors on the `IsAotCompatible` flag was mixed in to the main article for app developers on AOT.

I think there should be a main separate page oriented towards library developers and enabling AOT in their  packages, that also goes through how to resolve those warnings; akin to this blog: https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/

This is a hard subject for folks to parse, and the main guidance being in an article geared to apps means it's going to get lost as it doesn't seem relevant at first glance as it's about apps. Even knowing the property to search for, the top two results don't seem relevant:

![Image](https://github.com/user-attachments/assets/9e6e6a53-f655-4b4c-b546-7009a55a2c11)

Seems like the blog and the following document are the higher hits when searching more broadly ".NET Library AOT compatibility": https://learn.microsoft.com/dotnet/core/deploying/native-aot/libraries (which has very little information)
