### ISSUE TITLE
Why didn't you use the .NET MAUI Blazor?

### ISSUE THREAD

**Issue by bob-byte** [dotnet/docs#35723]
Describe please why you didn't use .NET MAUI Blazor for creating eShopOnContainers app?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c03844a-7f69-9457-17c1-816de39dfb34
* Version Independent ID: c681d687-9207-3e88-bf77-ba3dcc012d43
* Content: [Introducing eShopOnContainers reference app](https://learn.microsoft.com/en-us/dotnet/architecture/cloud-native/introduce-eshoponcontainers-reference-app)
* Content Source: [docs/architecture/cloud-native/introduce-eshoponcontainers-reference-app.md](https://github.com/dotnet/docs/blob/main/docs/architecture/cloud-native/introduce-eshoponcontainers-reference-app.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
eShopOnContainers was created long before .NET MAUI and Blazor. We now have a newer sample https://github.com/dotnet/eshop which has both a .NET MAUI and Blazor Hybrid sample
