### ISSUE TITLE
Not Usable

### ISSUE THREAD

**Issue by gregowahoo** [dotnet/docs#35735]
I just want to quickly find examples.. I don't want to read the bible! Fxck, I can't find anything anymore!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#NFormatString)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by postmeback** [comment]
I understand the frustration, but being a bit more specific will help the maintainers to address the issue properly.

**Comment by adegeo** [comment]
Hi @gregowahoo sorry this article is frustrating you. What exactly would you like to see different? What are you searching for? More information helps us understand where we can improve the docs. I'm a little unsure about what examples you didn't find. 

Scanning through the article there are examples everywhere.

**Comment by gregowahoo** [comment]
Don't remember what page I was on but it seemed like I had to do a lot reading when all I wanted were a couple code examples. I'm gonna see if using the "Github Examples and Documentation" will help. Thanks, Ima Winer
