### ISSUE TITLE
 CDbl(txtPrice.Text) * CDbl(textQuantity.Text)                 

### ISSUE THREAD

**Issue by Luthando18** [dotnet/docs#35732]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27d8fdb1-ad10-a8ee-2e2c-5341cde25d7c
* Version Independent ID: 388af685-6d05-4b9e-d466-c3168afde288
* Content: [Expression is not a method - Visual Basic](https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30454?f1url=%3FappId%3Droslyn%26k%3Dk(BC30454))
* Content Source: [docs/visual-basic/misc/bc30454.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30454.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-diagnostics**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Hi @Luthando18 

Can you add more details here? I'm not sure what the question is.
