### ISSUE TITLE
CS8352 in VS2022 Error leads to nowhere

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [dotnet/docs#35750]
I have this code which results in the CS8352 error.
```cs
    public Span<char> WriteIntToSpan(int primitive)
    {
        if (primitive == 0)
        {
            _writer.Write('0');
        }
        int len = (int)Math.Ceiling(Math.Log10(primitive));
        Span<char> span = stackalloc char[len];

        for (int i = len - 1; i >= 0; i--)
        {
            var t = (char)('0' + (primitive % 10));
            span[i] = t;
            primitive /= 10;
        }
        return span;
    }
```
But clicking in VS on the error leads me to this page.
https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk%28CS8352%29

Expected would be an error page which explains what is going on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61
* Version Independent ID: 58a19505-ac46-c5c8-12cc-fe87b6aa18a7
* Content: [Sorry, we don't have specifics on this C# error](https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8352)&source=docs)
* Content Source: [docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @IXLLEGACYIXL 

This is an area where we've fallen behind, and I'm working to catch up by adding pages for the newer compiler error and warning codes.

The reason you're getting this error is the rule for the safe context of the result of a `stackalloc` statement.  See the language in the [standard](https://learn.microsoft.com/dotnet/csharp/language-reference/language-specification/structs#164127-stackalloc) for the rule.

I've added this to our backlog to address.

**Comment by OronDF343** [comment]
Also applies to CS9135

```
if (arrivalTime is < _minValidDate or > _maxValidDate)
{
}
```

`error CS9135: A constant value of type 'DateTime' is expected`

**Comment by BartoszKlonowski** [comment]
@BillWagner Can I jump in here to add the `CS8352` page, at least at it's initial state, or maybe it's already in progress by some members?
If it's OK with you for me to take it, please assign me to this.
