### ISSUE TITLE
Ubuntu packages do not install all listed dependencies

### ISSUE THREAD

**Issue by externl** [dotnet/docs#35754]
**Issue description**

The [documentation for .NET on Ubuntu](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies) page says that its dependencies are installed automatically.

> When you install with a package manager, these libraries are installed for you

https://github.com/dotnet/docs/blob/f3aaacf207f069785a72f0e807310e271d684930/docs/core/install/linux-ubuntu.md?plain=1#L242-L259

However, some of these packages are not installed for you - they are not listed as dependences in the apt package. Namely `libunwind8` and `liblttng-ust1`.

See https://github.com/dotnet/runtime/issues/87225#issuecomment-1581344121

I think [`/docs/core/install/linux-ubuntu.md`](https://github.com/dotnet/docs/blob/f3aaacf207f069785a72f0e807310e271d684930/docs/core/install/linux-ubuntu.md) should be updated to reflect the actual behavior that only some of these dependencies are installed automatically.

**Target framework**

- Ubuntu 22.04
- MS Repo
- dotnet-sdk-7.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Reflecting on this further, I'd be interested to know more about what specific Ubuntu version and release you're using? In general, just installing ubuntu XX.XX normal public release, I've not had missing dependencies.

**Comment by adegeo** [comment]
OK I just read up on that linked issue. I guess I'm a little confused. Is the MSQUIC library shipping with .NET and thus there's a dependency of .NET on it? Or is the library manually installed via nuget?

**Comment by adegeo** [comment]
Read some more, using your example docker file from the other issue and some other stuff I've come to the conclusion that this is shipped in .NET directly.

**Comment by externl** [comment]
@adegeo Maybe I didn't explain it well. As listed in the documentation `dotnet-sdk-7.0` has a list of dependencies that are supposed to be installed when you install the `dotnet-sdk-7.0` package.

> When you install with a package manager, these libraries are installed for you

However, this is not true. Some of the dependencies, such as `libunwind8` and  `liblttng-ust1` do not get installed. If you want their functionality you have to install them manually. They are not bundled with dotnet or in the ms container already. You can use apt to verify they are not installed after installing `dotnet-sdk-7.0`.

You can ignore the links I posted about `msquic`, they're just to show that another MS dev said these deps are not being installed. 

Hence I think the docs should be updated to say that not all of the list dependencies get installed as dependencies. 

Hope this clears things up.

**Comment by adegeo** [comment]
Thanks. I understand :D I just wasn't totally sure if these were actually dependencies of .NET or a .NET library separately shipped and thus not really a direct dependency of .NET.

I'll add those two libraries to the doc. Thanks again 😁 

@leecow fyi

**Comment by adegeo** [comment]
Ack actually, I see those two libraries listed. Though they say 22.X but they should probably be 22.X+?

**Comment by externl** [comment]
> I'll add those two libraries to the doc

There's probably more than just those two. They're already listed, it's just that they don't get installed automatically.

**Comment by adegeo** [comment]
I see what you're saying now.. My brain was kind of skipping over the "these are required" part of your issue and just focusing on the part about the 2 libraries you pointed out.

Regarding your point 2 above, you should bring that up to the runtime team. Also, the runtime team presented the dependency information to me just as "this is what .NET depends on." The linked issue in the runtime repo seems to indicate that there are some dependencies that are installed ?on demand?, when you use a feature of .NET, at least it seems so. If that's true, then perhaps if you don't install via APT those deps can't be installed on demand, and thus, the messaging of "these are required if you manually install" is true for .NET as a whole, regardless of if you use a specific API that uses a specific dependency.

If you look at the whole product, the dependency is required for everything to work. If you look at it from the app standpoint of "my app doesn't use API X so Y dependency is never required" isn't something we've documented. @leecow Should we list which dependencies are actually required and which are optional based on what feature of .NET you're going to use?

**Comment by leecow** [comment]
I think that rather than trying to create and maintain a documentation matrix, libs needed for out-of-the-box functionality (ie, libunwind and liblttng), they should either be added to runtime-deps or the sdk package - whichever is more appropriate. More input from @NikolaMilosavljevic needed here.

**Comment by adegeo** [comment]
Good though @leecow however, I think that discussion is more appropriate in the runtime repo, not the docs repo 😁
