### ISSUE TITLE
No mention of JsonObjectAttribute in differences table

### ISSUE THREAD

**Issue by simeyla** [dotnet/docs#35767]
This is a very extensive page, but with the notable absence of [JsonObject] which is the [Newtonsoft.Json.JsonObjectAttribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonObjectAttribute.htm) class.

Would be good to add this object and some of its properties to the compatibility / comparison table.

eg. for a single object you can specify

    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public class Person { ... }

This sort of sits halfway between `[JsonIgnore(JsonignoreCondition.WhenWritingNull)]` and `JsonOptions.DefaultIgnoreCondition`.

There are other similar properties on this attribute such as `MemberSerialization` and `ItemRequired` that apply to all properties.

At the very least (if my interpretation is correct - and it may not be 100%) should add something like:

> There is no equivalent of Newtonsoft.Json.JsonObjectAttribute which allows for default handling of null and required values to be scoped to a single object. With System.Text.Json you must apply either the global setting or use individual properties on every member.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0)
* Content Source: [docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 123280](https://dev.azure.com/msft-skilling/Content/_workitems/edit/123280)

**Comment by gewarren** [comment]
@eiriktsarpalis Should I update the article as suggested in this issue?

**Comment by eiriktsarpalis** [comment]
Yeah, I would think it's an accurate suggestion.
