### ISSUE TITLE
python

### ISSUE THREAD

**Issue by kukupus** [dotnet/docs#35764]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8053bb96-cc40-8369-c07f-f9fd14060c1e
* Version Independent ID: 293260e2-f444-537b-0ba7-14d1fb6ebcf2
* Content: [Hello World - C# 交互式教程简介](https://learn.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/hello-world.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Closing as this seems like a spam issue.
