### ISSUE TITLE
Edit pass on install-scripts

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#35766]
See conversation at https://github.com/dotnet/docs/pull/35752/files#r1226843449

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by IEvangelist** [comment]
Hey @tdykstra - should this have been closed as a result of https://github.com/dotnet/docs/pull/35752 too?

**Comment by tdykstra** [comment]
No, this was a result of 35752. We didn't do your list reformat suggestion using colons because other lists in the doc used the hyphen format and so the lists would have been inconsistent. I can use this issue to go through and make all lists use the colon format plus address any other style issues in the text.
