### ISSUE TITLE
Centos 8 Stream install instructions not working

### ISSUE THREAD

**Issue by saeg2k3** [dotnet/docs#35835]
The provided instructions are not working for Centos8 Stream fully updated to 2023/06/15

The command throws:
sudo dnf install dotnet-sdk-7.0
Last metadata expiration check: 0:03:33 ago on jue 15 jun 2023 09:12:35 CST.
No match for argument: dotnet-sdk-7.0

Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 197d466f-8967-78b1-b1fc-2c09367b0bec
* Version Independent ID: 2953e34e-d5e1-8d33-92a0-73a1d37cfb8e
* Content: [Install .NET on RHEL and CentOS Stream - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-rhel#supported-distributions)
* Content Source: [docs/core/install/linux-rhel.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-rhel.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @saeg2k3 it seems you're right. Looking around the package manager archive for CentOS Stream 8 I can't find the packages. I see them in the mirror for Stream 9 though.

Can you try using the centos8 Microsoft repository?

```
sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
sudo yum install dotnet-sdk-7.0
```

**Comment by saeg2k3** [comment]
> Thank you, the workaround worked.
