### ISSUE TITLE
What is the thread adjustment reason "Cooperative Blocking"?

### ISSUE THREAD

**Issue by zbrilhart** [dotnet/docs#35833]
**Describe the new article**
In a PerfView trace, the events view is showing numerous ThreadPoolWorkerThreadAdjustment events with reason being CooperativeBlocking. What does this reason mean? 

In .net framework there was a doc with all of the reasons but I don't see this for .NET Core.

https://learn.microsoft.com/en-us/dotnet/framework/performance/thread-pool-etw-events#threadpoolworkerthreadadjustmentadjustment

We need this info so we can help diagnose thread related issues. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d0a5476-11b4-1a6e-f474-9495aaf48703
* Version Independent ID: 86a92619-9dfa-b113-a920-f40482733462
* Content: [ThreadPool runtime events - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-thread-events)
* Content Source: [docs/fundamentals/diagnostics/runtime-thread-events.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/diagnostics/runtime-thread-events.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by kouvel** [comment]
It means the worker thread count was adjusted up or down due to a worker thread synchronizing waiting on a Task. Cooperative blocking and its config settings are described [here](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/threading#thread-injection-in-response-to-blocking-work-items), the event docs should be updated to include that reason.

**Comment by zbrilhart** [comment]
Thank you, I greatly appreciate the answer.

**Comment by kouvel** [comment]
Fixed by https://github.com/dotnet/docs/pull/37149
