### ISSUE TITLE
CS0436: Unclear what the output to the console is

### ISSUE THREAD

**Issue by aydjay** [dotnet/docs#35834]
The output of the second example isn't clear. I am assuming the output visible in the console is:

CS0436_b

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6493b5de-9d48-3a99-e213-06fdb121e067
* Version Independent ID: b320743f-f0ef-2174-df91-f0ddbb612e88
* Content: [Compiler Warning (level 2) CS0436](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0436)
* Content Source: [docs/csharp/misc/cs0436.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0436.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The correct output is "CS0436_b", as pointed out above.

Adding this to our backlog, and adding the "help-wanted" label.
