### ISSUE TITLE
what is <yourporject>.exe 

### ISSUE THREAD

**Issue by syedrashid47** [dotnet/docs#35852]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 433b4c70-07c8-34c3-b567-22c80b71c5e2
* Version Independent ID: e3699917-899c-85fd-44f2-942b317cb8ff
* Content: [How to: Install and uninstall Windows services - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services)
* Content Source: [docs/framework/windows-services/how-to-install-and-uninstall-services.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-services/how-to-install-and-uninstall-services.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by syedrashid47** [comment]
is it the setup.exe that is created after publiush
cause there is no other exe in my publish folder

**Comment by postmeback** [comment]
Complete beginner here ~ I think there should be only one .exe file.

**Comment by adegeo** [comment]
Hello. I just came across this issue and I'm sure it's too late, but after reading through the document it seems to be talking about your project's compiled executable. This tool isn't meant to replace an installer system like install shield or wix.

![image](https://github.com/dotnet/docs/assets/67293991/6aae732b-e84f-4e40-af2e-d61eaa348941)
