### ISSUE TITLE
Show the difference between the formats G and F

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#35854]
There is a somewhat convoluted description of the enum string formats G and F but no different example. It would certainly help a lot to see how the same code leads to different outputs for both formats. Think of this as writing unit tests. What would you test to make sure both implementations can have different outputs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7b9c332-da26-ff62-8669-5697d5b9aa56
* Version Independent ID: 0049d705-a8ca-a4b5-c51d-b4f88bdf27e3
* Content: [Enumeration format strings](https://learn.microsoft.com/en-us/dotnet/standard/base-types/enumeration-format-strings)
* Content Source: [docs/standard/base-types/enumeration-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/enumeration-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi there @ygoe - I started looking into this, and your question seems valid as the docs fail to highlight to difference in output. I'll update the doc to reflect to this.
