### ISSUE TITLE
Template team feedback 

### ISSUE THREAD

**Issue by bnhassin** [dotnet/docs#35867]
Update preview issue new by @bnhassin 
![IMG_20230619_000643](https://github.com/dotnet/docs/assets/1473765/f9e11622-db78-4de8-ba7e-ac85f3722a98)

[#35867](https://github.com/dotnet/docs/issues/35867)

**Comment by bnhassin** [comment]
> ![Screenshot_20230618-224438.png](https://aka.ms/dc/image?name=B8ee7d47ad4864fd3b9c86c37a30c012b638227219823855417_Screenshot_20230618-224438.png&tid=8ee7d47ad4864fd3b9c86c37a30c012b638227219823855417)
> 

![Screenshot_20230618-224438.png](https://github.com/dotnet/docs/assets/1473765/23d3410f-7656-4ab4-a097-070ceed0e9e0)

**Comment by bnhassin** [comment]
Expected outcome: a bug was added
Actual outcome: a ladybug appeared

**Comment by IEvangelist** [comment]
Hi @bnhassin - we don't have a bug report issue template, like .NET MAUI. Here is the list of our issue templates, I'm not exactly sure what the expected/actual outcome should be since there aren't any visuals added to this issue.

![image](https://github.com/dotnet/docs/assets/7679720/7bb702d0-657b-4df1-ae5d-643a52cdf2f5)

I think we should probably close this issue.

**Comment by bnhassin** [comment]
> ### Description
> 
> 
> **[Template team feedback issue #35867](https://github.com/dotnet/docs/issues/35867)**
> 
> Create 35867.md 
> https://github.com/bnhassin/maui.community/commit/2ca53b06d94d5fb903de4b824bc4df20bbb13024
> 
> ![Screenshot_20230620-005046](https://github.com/dotnet/maui/assets/1473765/425029fb-16b2-4d6d-9560-4928df18b06d)
> 
> [issues](https://github.com/bnhassin/maui.community/tree/main/.github/ISSUE_TEMPLATE/docs/issues)
> 
> ![IMG_20230620_015800](https://github.com/dotnet/maui/assets/1473765/db06e490-6841-4059-a75b-1e7133a8a217)
> 
> 
> [workflow runs](https://github.com/bnhassin/maui.community/actions/workflows/dotnet-desktop.yml)
> 
> ![Screenshot_20230620-010601](https://github.com/dotnet/maui/assets/1473765/feff1e68-6ed6-40a3-9271-7479451bdd18)
> 
> vscode.json
> 
> https://github.com/dotnet/maui/commit/79e0cf49811fbdbfd49931390c2db6cc00094e98
> 
> [docs/patch-1/README.md](https://github.com/dotnet/maui/blob/6ef6f39a0749d3892a2939b90fce026aff4e1855/docs/patch-1/README.md)
> 
> dotnet workload list
> 
> ### Steps to Reproduce
> 
> )
> 
> 
> 
> ### Link to public reproduction project repository
> 
> https://github.com/users/bnhassin/projects/1/
> 
> ### Version with bug
> 
> Unknown/Other
> 
> ### Last version that worked well
> 
> 6.0
> 
> ### Affected platforms
> 
> Android
> 
> ### Affected platform versions
> 
> Android 12
> 
> ### Did you find any workaround?
> 
> _No response_
> 
> ### Relevant log output
> 
> _No response_

**Comment by IEvangelist** [comment]
Hi @bnhassin - are you able to please explain what you're seeing here? I still have no idea what the issue actually is.

**Comment by Eilon** [comment]
@IEvangelist we have similar issues opened in the .NET MAUI repo too... not sure what they mean. I asked "Hi @bnhassin can you explain the actual issue? This seems like some AI-generated text that isn't specific to this repo"

**Comment by IEvangelist** [comment]
> @IEvangelist we have similar issues opened in the .NET MAUI repo too... not sure what they mean. I asked "Hi @bnhassin can you explain the actual issue? This seems like some AI-generated text that isn't specific to this repo"

@Eilon - In that case, I think maybe we should close these and monitor the op for suspicious activity?
