### ISSUE TITLE
How to pass multiple `--file` options to command line input params?

### ISSUE THREAD

**Issue by khteh** [dotnet/docs#35860]
[Enter feedback here]
A few options:

(1) `--file file1,file2,file3`
(2) `--file file1 --file file2 --file file3`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7705dc41-7297-0807-7e9c-2e6548c26b84
* Version Independent ID: fa160b1d-66ed-8c5d-37cd-b7e02443e9f1
* Content: [Tutorial: Get started with System.CommandLine](https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial)
* Content Source: [docs/standard/commandline/get-started-tutorial.md](https://github.com/dotnet/docs/blob/main/docs/standard/commandline/get-started-tutorial.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/commandline/define-commands#multiple-arguments
