### ISSUE TITLE
LibraryImport Out string parameter?

### ISSUE THREAD

**Issue by mfm-gwt** [dotnet/docs#35862]
I'm trying to figure out how to change something like RealGetWindowClass from DllImport to LibraryImport and not having much luck. Could we get some more details of this in the LibraryImport docs? StringBuilder is no longer supported but string, char[], and byte[] don't seem to work either.

[DllImport ( "user32.dll", SetLastError = true )]
internal static extern uint RealGetWindowClass ( nint hWnd, [Out] StringBuilder ptszClassName, uint cchClassNameMax );

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0b79232-1450-0aeb-b9d6-3a3c8234d148
* Version Independent ID: 572c0b50-a28d-d387-1e8c-4a271615a753
* Content: [P/Invoke source generation](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation)
* Content Source: [docs/standard/native-interop/pinvoke-source-generation.md](https://github.com/dotnet/docs/blob/main/docs/standard/native-interop/pinvoke-source-generation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by jkoritzinsky** [comment]
You should use `[Out] char[]` for this case like the following:

```csharp
[LibraryImport("user32.dll", EntryPoint = "RealGetWindowClassW", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
internal static partial uint RealGetWindowClass(nint hWnd, [Out] char[] ptszClassName, uint cchClassNameMax);
```

**Comment by mfm-gwt** [comment]
Thank you. Is there a convention for how to call it? This is what I'm doing currently. It works but probably isn't optimal.

```
   char [] buffer = new char [ 255 ];
   uint length = RealGetWindowClass ( windowId, buffer, (uint) buffer.Length );
   string? className = ( new System.String ( buffer ) )?.TrimEnd ( '\0' );
```

**Comment by jkoritzinsky** [comment]
That works, but this example below will be slightly more efficient:

```csharp
char [] buffer = new char [ 255 ];
uint length = RealGetWindowClass ( windowId, buffer, (uint) buffer.Length );
string className = new string ( buffer, 0, (int)length );
```
