### ISSUE TITLE
Incorrect code sample

### ISSUE THREAD

**Issue by abdekker** [dotnet/docs#35870]
Isn't that supposed to be "static int x = 0;"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d97db038-978f-fff3-4e68-110619dc86f2
* Version Independent ID: 3c933595-0ec1-2632-55c9-934af6e72f5d
* Content: [static modifier - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static)
* Content Source: [docs/csharp/language-reference/keywords/static.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/static.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
> Hi @IEvangelist: Ok, no problem. Thanks for checking it. My only comment is to note that "it gives the same output" is not the same as "it is correct or good code". My suggestion of setting x = 0 also gives the same output, BTW.
> 
> As an experienced developer, "static int x = y;" made me do a double-take! If you want to initialise x to 0, why not do it explicitly?

That's intentional, the idea is to clearly indicate that the order of static field assignments matters. Since `y` hasn't been assigned yet, its value is `0`. Otherwise, you're simply assigning to `0` and the point is lost.
