### ISSUE TITLE
See ADR here: https://github.com/microsoft/semantic-kernel/pull/1547 with details on the preferred directory structure.

### ISSUE THREAD

**Issue by Matthewdavies1984** [dotnet/docs#35889]
See ADR here: https://github.com/microsoft/semantic-kernel/pull/1547 with details on the preferred directory structure.

_Originally posted by @markwallace-microsoft in https://github.com/microsoft/semantic-kernel/issues/1571_

**Comment by gewarren** [comment]
@Matthewdavies1984 Where do you want this documented?
