### ISSUE TITLE
Couldn't find an installed template that matches the input, searching online for one that does...

### ISSUE THREAD

**Issue by zzzato** [dotnet/docs#35917]
[Enter feedback here]
Hi all.
I'm trying this tutorial but the command below returns error in subject:

dotnet new console --framework net7.0

I think that completing page as adding a SPECIFIC INSTRUCTIONS ABOUT WHAT WE NEED TO DOWNLOAD.
What's mean "template that match the input"? It refers a template NAME or template TYPE?
How I know the right key to download required template when error doens't give me it?

:-|

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Create a .NET console application using Visual Studio Code - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?pivots=dotnet-7-0)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 117609](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117609)

**Comment by tdykstra** [comment]
What output do you get from `dotnet --info` ?

**Comment by zzzato** [comment]
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\lavoro2023\vscode\FirstConsoleApplication>

**Comment by tdykstra** [comment]
The [tutorial prerequisites](https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?pivots=dotnet-7-0#prerequisites) indicate that you need to download the .NET 7 SDK. You have only 3.1 installed. The Prerequisites section includes a link to download the SDK.
