### ISSUE TITLE
bug: ubuntu 23.04 is not a lts version

### ISSUE THREAD

**Issue by nimrof** [dotnet/docs#35912]
Under 'Supported distributions'
it says ubuntu 23.04 is a lts version, but it is not

ref:
https://ubuntu.com/about/release-cycle

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [.NET and Ubuntu overview - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204-microsoft-package-feed)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this.
