### ISSUE TITLE
record documentation uses invalid code example

### ISSUE THREAD

**Issue by mathiasKaiser** [dotnet/docs#35918]
[Enter feedback here]
The code in the 2. last example is not compiling. (->  // showing moving accumulation of 5 days using range syntax)
data.Length is undefined (you mean data.Count ?)
and `data[start..(start + rangeSize)]` gives me "Argument 1: can not convert from System.Range to int)

using MS 2022 community and a new .net7 project with c#11

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 294a082e-5584-008e-b83a-7f090d898cda
* Version Independent ID: d4a11dfa-2836-b423-63cd-c356e72e16a7
* Content: [Use record types - C# tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records)
* Content Source: [docs/csharp/whats-new/tutorials/records.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/records.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mathiasKaiser** [comment]
nevermind. my data was `List<DailyTemperature> data = new ()`
ticked can be closed

**Comment by BillWagner** [comment]
closing per author.
