### ISSUE TITLE
Document new reportivts compiler switch

### ISSUE THREAD

**Issue by 333fred** [dotnet/docs#35921]
https://github.com/dotnet/roslyn/pull/68665 is adding a new compiler switch for producing additional information about `InternalsVisibleToAttribute` information it sees. This is controlled by `/reportivts`, `/reportivts+`, or `/reportivts-` (the first two turn it on, the last turns it off). It can also be turned on from msbuild with the `<ReportIVTs>true</ReportIVTs>` property. It makes the following changes to the output of both csc and vbc:

1. Inaccessible member diagnostics will have an additional piece of information indicating what assembly they came from, if they came from a different assembly than the one being compiled.
2. The compiler will print the assembly identity of the project being compiled (ie, assembly name and public key).
3. For every reference passed to the compiler, it will print;
    1. The assembly identity of the reference
    2. Whether the reference grants the current project IVT (simple true/false)
    3. What assemblies the reference grants IVT to (name and all public keys)

This additional information will not display live in VS, it will only occur when using the "Build Project" action, or `dotnet build`, or a manual `csc` invocation. An example of what this output would look like for a C# compilation:

```
/tmp/b.cs(2,23): error CS0122: 'A' is inaccessible due to its protection level
/tmp/b.cs(2,23): error CS9163: 'A' is defined in assembly 'N1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Printing 'InternalsVisibleToAttribute' information for the current compilation and all referenced assemblies.
Current assembly: 'B, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Assembly reference: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKey=00000000000000000400000000000000'
  Grants IVT to current assembly: False
  Grants IVTs to:
    Assembly name: 'PresentationCore'
    Public Keys:
      0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9
    Assembly name: 'PresentationFramework'
    Public Keys:
      0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9
    Assembly name: 'System'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'System.Core'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'System.Numerics'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'System.Reflection.Context'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'System.Runtime.WindowsRuntime'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'System.Runtime.WindowsRuntime.UI.Xaml'
    Public Keys:
      00000000000000000400000000000000
    Assembly name: 'WindowsBase'
    Public Keys:
      0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9

Assembly reference: 'N1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  Grants IVT to current assembly: False
  Grants IVTs to:
    Nothing
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1ea586-7719-df69-7d8a-8a04cddb5543
* Version Independent ID: 691a6e9e-00ea-6210-c64a-659ba7930bec
* Content: [C# Compiler Options](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/)
* Content Source: [docs/csharp/language-reference/compiler-options/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 118038](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118038)

**Comment by BillWagner** [comment]
This will be in VS 17.7
