### ISSUE TITLE
Absolutely wrong page!!!

### ISSUE THREAD

**Issue by petrmartinek2** [dotnet/docs#35951]
I am looking for how-to about creating exceptions in Visual Basic. Your system offers me C# which is absolutely useless for me!
Why don't your search engines take into consideration what I tell them? If I say "Visual Basic" why does it offer me "C#"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed065e03-3620-cd2a-66b7-706ce2f863d9
* Version Independent ID: fe5453a0-d849-a145-7260-036f769c208f
* Content: [How to create user-defined exceptions with localized exception messages](https://learn.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-localized-exception-messages)
* Content Source: [docs/standard/exceptions/how-to-create-localized-exception-messages.md](https://github.com/dotnet/docs/blob/main/docs/standard/exceptions/how-to-create-localized-exception-messages.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 118034](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118034)

**Comment by IEvangelist** [comment]
Hi @petrmartinek2 - thank you for posting this issue. The search engines brought you to the correct page, but you need to tell it which language you want. Open the page again:

https://learn.microsoft.com/dotnet/standard/exceptions/how-to-create-localized-exception-messages

Then select the C# drop down and select Visual Basic:

![image](https://github.com/dotnet/docs/assets/7679720/15ecce49-49d0-4850-afe8-272b1dd41af0)

**Comment by petrmartinek2** [comment]
Well, you can close this issue even though the article was in C# while I was looking for VB.NET. Which means it is not correct and it is absolutely wrong.

BTW. What do you think? How many people will see immediately the small C# link and because it does not do anything obvious they will understand that it changed the page from C# to VB?

The correct answer is: Nobody who is not familiar with the cryptically built web pages.

And the last question is why is GitHub answering my question placed on Microsoft's website?

Petr Martinek
Programmer and Data Analyst
