### ISSUE TITLE
Can't install dotnet 7 on ubuntu 22.04 using apt

### ISSUE THREAD

**Issue by sikora507** [dotnet/docs#35974]
Can't install dotnet 7 on ubuntu 22.04

after `sudo apt-get update` and `sudo apt install dotnet-sdk-7.0` i get
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  dotnet-sdk-7.0
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/96,5 MB of archives.
After this operation, 376 MB of additional disk space will be used.
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
Selecting previously unselected package dotnet-sdk-7.0.
(Reading database ... 248053 files and directories currently installed.)
Preparing to unpack .../dotnet-sdk-7.0_7.0.305-1_amd64.deb ...
Unpacking dotnet-sdk-7.0 (7.0.305-1) ...
Setting up dotnet-sdk-7.0 (7.0.305-1) ...
```
However when I run 
`dotnet --list-sdks`
I get
```
Command 'dotnet' not found, but can be installed with:
sudo snap install dotnet-sdk       # version 7.0.305, or
sudo apt  install dotnet-host      # version 6.0.119-0ubuntu1~22.04.1
sudo apt  install dotnet-host-7.0  # version 7.0.108-0ubuntu1~22.04.1
See 'snap info dotnet-sdk' for additional versions.
```
Also when I print the content of /usr/share/dotnet directory, I get:
`sdk  sdk-manifests  templates`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac16736-f225-12d0-2de2-efded54a505a
* Version Independent ID: 909b29bd-2729-3b59-beb5-20a7281344d0
* Content: [Install .NET on Ubuntu 22.04 - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204)
* Content Source: [docs/core/install/linux-ubuntu-2204.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2204.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi. Do you also have a ` /usr/lib64/dotnet` directory on your machine?

**Comment by sikora507** [comment]
Yeah I've installed and uninstalled .NET a few times already, used .NET from snap package before, but ran into some issues, then uninstalled, tried with apt, didn't work.
I managed to install it finally using provided install shell scripts. 
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
However it didn't add the .dotnet directory in my home folder to the PATH variable as it should. I had to do it myself (export in .bashrc) and it finally worked.
It was super hard and a lot of time wasted to install .NET on Ubuntu.

**Comment by adegeo** [comment]
Sorry for the frustration. Unfortunately with so many different ways of installing .NET, and not knowing if you installed the x86 or x64 runtime, it's easy to end up in a weird state where pieces are missing.

The PATH is noted on the installation article, but not the tool reference. I'll do some cross linking. https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#set-environment-variables-system-wide

**Comment by WhiteSymmetry** [comment]
sudo apt remove dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo apt remove aspnetcore*
sudo apt remove netstandard*
sudo apt remove dotnet-host*
sudo apt purge dotnet-sdk* dotnet-host* dotnet* aspnetcore* netstandard*
sudo rm -f /etc/apt/sources.list.d/mssql-release.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list
sudo rm /etc/apt/sources.list.d/microsoft-prod.list.save
sudo apt update
Install by App Center: .Net Core SDK, Stable 8.0.101 
there is no need for other installations!
(sudo snap install dotnet-sdk #Installed by App Center
sudo apt install dotnet-sdk-8.0 #Installed by App Center
sudo apt install dotnet-host-8.0 #Installed by .Net Core SDK)
dotnet workload update
source ~/.bashrc
dotnet sdk check
.NET SDKs:
Version      Status                     
----------------------------------------
8.0.100      Patch 8.0.101 is available.

dotnet --info
.NET SDK:
 Version:           8.0.100

 Workload version:  8.0.100-manifests.6c33ef20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/233/sdk/8.0.100/
 
 Host:
  Version:      8.0.0
  Architecture: x64

dotnet --list-sdks
8.0.100 [/snap/dotnet-sdk/233/sdk]
dotnet --version
8.0.100
