### ISSUE TITLE
REST client example shouldn't create instances of HttpClient per call

### ISSUE THREAD

**Issue by Daniel15** [dotnet/docs#3603]
The article at https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient is using the anti-pattern of creating a new instance of `HttpClient` per call. It should be using a shared instance. See the docs at https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.1:

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. 

The way I usually handle this is by adding a `HttpClient` singleton to the dependency injection container, and inject it into the constructor.

**Comment by BillWagner** [comment]
I am thinking about the best way to present this. I'm concerned about adding DI to an introductory tutorial. You are right that we need a better way to reuse the same client.

**Comment by Daniel15** [comment]
@BillWagner What if you just make it a static instance?
```
private static readonly HttpClient _client = new HttpClient()
```

**Comment by BillWagner** [comment]
@Daniel15 This sample is a reasonably simple one, so a static HttpClient is probably a good plan.

Do you want to make a PR for this? If not, I'll likely update it after the holidays.

**Comment by Daniel15** [comment]
I don't think I'll get time to send a PR any time soon, unfortunately :(

**Comment by BillWagner** [comment]
@Daniel15 I understand. It's on my list then.

**Comment by phenixita** [comment]
Can I start to do this?
I'd like to use this issue as my first contribution to this repo, too!

**Comment by mairaw** [comment]
Sure @phenixita!

**Comment by phenixita** [comment]
Ok thanks! I'll do it this weekend.
