### ISSUE TITLE
Conflicting information about gRPC hosted in IIS

### ISSUE THREAD

**Issue by ketchup201** [dotnet/docs#36057]
This page says that gRPC servers cannot be hosted in IIS due to lack of HTTPS/2 support. However, [this page says it is supported](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio).
Click the link and view the section entitled, **Server Options**.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8c957b4-4da9-2cda-b08e-ce78e5333768
* Version Independent ID: 2bf00fa5-70c1-b1a0-45c2-5a201f597066
* Content: [Self-hosted gRPC applications - gRPC for WCF developers](https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/self-hosted)
* Content Source: [docs/architecture/grpc-for-wcf-developers/self-hosted.md](https://github.com/dotnet/docs/blob/main/docs/architecture/grpc-for-wcf-developers/self-hosted.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
This page is out of date. Should be updated to reflect latest information in https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
