### ISSUE TITLE
ability to copy page as F# source would be good

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#36067]
It would be so cool to be able to copy a page like this in the form of F# source with the text as comments.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b69dfedf-d03a-1733-5c06-7b2000bad772
* Version Independent ID: 7c5955cd-60ba-12a6-8661-d9b9b7700cf1
* Content: [Anonymous Records - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/anonymous-records)
* Content Source: [docs/fsharp/language-reference/anonymous-records.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/anonymous-records.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Tagging @meganbradley @mimisasouvanh 

I don't know how easy this feature would be, or where we can route it.

**Comment by BillWagner** [comment]
This isn't on the platform team's roadmap.

**Comment by daveyostcom** [comment]
I should have said “as source code”, not mentioning a specific language.
