### ISSUE TITLE
Not good

### ISSUE THREAD

**Issue by krogers3** [dotnet/docs#36071]
[Enter feedback here]

what is the -0 in this command?
	Dotnet new console -o sample1
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2
* Version Independent ID: fdb655a4-cff4-6c67-7244-673760379663
* Content: [Get started with .NET](https://learn.microsoft.com/en-us/dotnet/core/get-started)
* Content Source: [docs/core/get-started.md](https://github.com/dotnet/docs/blob/main/docs/core/get-started.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
`-o` sets the output folder.

You can see a list of arguments by appending `-?` to the end of the sub command: `dotnet new -?` and you can see the command line argument documentation here: https://learn.microsoft.com/dotnet/core/tools/dotnet
