### ISSUE TITLE
it had a bug

### ISSUE THREAD

**Issue by mohammadsajadi94** [dotnet/docs#36074]
**I used this method, it had a bug
The code below does not work properly:**
Code:
```csharp
char[] charsToTrim = { '.', ' ', '_','-' };
string banner = " IR-0301800000000037159 . 5004 _ 8 ";
string result = banner.Trim(charsToTrim);
Console.WriteLine("Trimmed\n   {0}\nto\n   '{1}'", banner, result);
```

Output:
```
Trimmed
    IR-0301800000000037159 . 5004 _ 8
to
   'IR-0301800000000037159 . 5004 _ 8'
```

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd91d4c1-d713-b8f1-958f-3547a5150428
* Version Independent ID: 0a6a2496-ca04-fc7e-777f-8d2ef7bef1a6
* Content: [Trimming and Removing Characters from Strings in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/trimming)
* Content Source: [docs/standard/base-types/trimming.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/trimming.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @mohammadsajadi94 I believe your code worked fine. Trim removes the characters from the start and end of the string. Are you trying to remove those characters from anywhere in the string? You would want to use `.Replace` instead.

Please let me know if this helps. If it doesn't, please tell me what you expected to happen.

**Comment by mohammadsajadi94** [comment]
Hi
Andy
My problem is that in the example given in the tutorial
The example you gave
The middle of the string is also removed
So the example must be deleted
thank you

**Comment by adegeo** [comment]
Hi @mohammadsajadi94 since I've not heard back from you, I'll close this issue. Please feel free to reopen it and provide more information. What would help is the exact example you're having a problem with. Provide your code for that. Cheers!
