### ISSUE TITLE
Missing LINQ Generation Operations Examples

### ISSUE THREAD

**Issue by GarretWayne** [dotnet/docs#36085]
Dear Devs,

I've noticed that the documentation lacks examples for all relevant LINQ methods that would showcase its usage, capabilities and anything else necessary for understanding it fully.

I hope I could be helpful by submitting this report, and have a nice day! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f491277b-a7ef-aa21-b9f0-3bffd8f95e68
* Version Independent ID: 43e207ee-23f4-96da-bd3f-a03eec5ff37a
* Content: [Generation Operations (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/generation-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/generation-operations.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/generation-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 198459](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198459)

**Comment by BillWagner** [comment]
Adding to this sprint because I'm working in this area.
