### ISSUE TITLE
Typo in the number of the generation.

### ISSUE THREAD

**Issue by peterkovecses** [dotnet/docs#36088]
Hello, in the text below, I think it's not Gen 0, but Gen 2:

When is a large object collected?
In general, a GC occurs under one of the following three conditions:
- Allocation exceeds the generation 0 or large object threshold.

Best,
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 819bcbc3-b2f7-b1eb-2e45-0f19c8da797c
* Version Independent ID: ed840139-0331-77b1-5645-0cac6c16edcf
* Content: [Large object heap (LOH) on Windows](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap)
* Content Source: [docs/standard/garbage-collection/large-object-heap.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/large-object-heap.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I think it is correct as written. By "allocation exceeds...", I think that "user allocation exceeds..." is implied, and users can only allocate into generation 0 (and the LOH). I think it's also referring to any GC in "a GC occurs under 3 conditions", not necessarily a GC of a large object.

**Comment by peterkovecses** [comment]
@gewarren Thank you for your response. However, I would like to point out that the questioned sentence and your response seem to refer to a general garbage collection (GC) event, while the section's title specifically asks when a large object (LOH) is collected. If I'm not mistaken, the LOH collection is associated with Gen 2 garbage collection, not Gen 0. It would be helpful to clarify this in the documentation, as the current wording may lead to confusion regarding the relationship between LOH collection and the different generation garbage collections. I appreciate your attention to this matter.
