### ISSUE TITLE
Missing documentation for new IDE code style rule IDE0270

### ISSUE THREAD

**Issue by mavasani** [dotnet/docs#36082]
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0270 returns a 404 page not found. IDE0270 was first added in VS2022 17.5 release with https://github.com/dotnet/roslyn/pull/65371.

**Comment by mavasani** [comment]
Customer report: https://developercommunity.visualstudio.com/t/Compiler-error-for-IDE0270-after-upgradi/10301675

**Comment by gewarren** [comment]
This is covered by https://github.com/dotnet/docs/issues/30361.
