### ISSUE TITLE
Missing LINQ ToLookup Operation Example

### ISSUE THREAD

**Issue by GarretWayne** [dotnet/docs#36084]
Dear Devs,

I've noticed that the documentation lacks examples for a Grouping LINQ method.
The "`ToLookup`" method in particular is missing any example that would showcase its usage, capabilities and anything else necessary for understanding it fully.

I hope I could be helpful by submitting this report, and have a nice day! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbc7f45-8317-4842-bad6-f774a2b0542a
* Version Independent ID: 19d11523-c3c4-80c6-7707-3bad2e68d273
* Content: [Grouping Data (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/grouping-data)
* Content Source: [docs/csharp/programming-guide/concepts/linq/grouping-data.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/grouping-data.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 198452](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198452)

**Comment by BillWagner** [comment]
Adding this to the current sprint, as I'll be working in this area.
