### ISSUE TITLE
Missing LINQ Equality Operations Examples

### ISSUE THREAD

**Issue by GarretWayne** [dotnet/docs#36086]
Dear Devs,

I've noticed that this documentation lacks examples for all relevant LINQ methods that would showcase its usage, capabilities and anything else necessary for understanding it fully.

I hope I could be helpful by submitting this report, and have a nice day! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd26ba85-4da9-03cb-7046-1e9e100e174b
* Version Independent ID: 71de937d-d86f-acd9-65b4-e32e43646114
* Content: [Equality Operations (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/equality-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/equality-operations.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/equality-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 198458](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198458)

**Comment by BillWagner** [comment]
Adding this to the current sprint as I'll be working in this area.
