### ISSUE TITLE
Missing LINQ Converting Data Operations Examples

### ISSUE THREAD

**Issue by GarretWayne** [dotnet/docs#36090]
Dear Devs,

I've noticed that this documentation lacks examples for all relevant LINQ methods, that would showcase its usage, capabilities and anything else necessary for understanding it fully.

I hope I could be helpful by submitting this report, and have a nice day! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 547067ff-1368-4551-a2ed-8d7ea1b98781
* Version Independent ID: 130b1e00-89df-3980-5731-1c8c11db2418
* Content: [Converting Data Types (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/converting-data-types)
* Content Source: [docs/csharp/programming-guide/concepts/linq/converting-data-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/linq/converting-data-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 198456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198456)

**Comment by BillWagner** [comment]
Adding this because I'll be working in this area.
