### ISSUE TITLE
Missing Console Application reference sample/Instructions

### ISSUE THREAD

**Issue by tshaiman** [dotnet/docs#36118]
[Enter feedback here]
in the opening statement of the article it says : The Generic Host can be used with other types of .NET applications, such as Console apps."

but no sample or instructions on how to use that generic host on Console Applicaiton is provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9
* Version Independent ID: 22a12ff8-d2ff-a841-b9bb-e2fd1032bc04
* Content: [.NET Generic Host - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host)
* Content Source: [docs/core/extensions/generic-host.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/generic-host.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @tshaiman - The [Set up a host](https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host#set-up-a-host) section shows a sample Console app. It uses top level statements, and this console app just so happens to register a Worker service.

**Comment by tshaiman** [comment]
that is correct, i missed that as I thought the <service> is a worker type application not console type .
you may close this ticket
