### ISSUE TITLE
A minor warning error

### ISSUE THREAD

**Issue by codeAKstan** [dotnet/docs#36127]
Using the new program style of .Net, the Parse.(Console.ReadLine()) shows error
![Screenshot 2023-07-07 124915](https://github.com/dotnet/docs/assets/126232126/bfba3de9-9e82-4da0-80fb-816dbbf679b2)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6+ - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 124266](https://dev.azure.com/msft-skilling/Content/_workitems/edit/124266)

**Comment by tdykstra** [comment]
@codeAKstan The code you are referring to doesn't appear in the article.
