### ISSUE TITLE
dotnet-trace:  possible `--clreventlevel` values not documented

### ISSUE THREAD

**Issue by dtivel** [dotnet/docs#36129]
Possible values for the `--clreventlevel` option are not documented here.  I had to dig around to find https://learn.microsoft.com/en-us/dotnet/framework/performance/clr-etw-keywords-and-levels#etw-event-levels.  It would be helpful if this documentation directly listed possible values for the option or linked to that documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57216dad-d87d-eeef-adc8-82bfe4251343
* Version Independent ID: 3e7ab61f-5a06-b92c-5c74-0fae43adb35e
* Content: [dotnet-trace diagnostic tool - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-collect)
* Content Source: [docs/core/diagnostics/dotnet-trace.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dotnet-trace.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by Leonardo-Ferreira** [comment]
same issue here
