### ISSUE TITLE
Please include complete code(include thread id) instead of snippet

### ISSUE THREAD

**Issue by kirancobe** [dotnet/docs#36132]
[Enter feedback here]
Please include complete code(include thread id,main() method etc) instead of snippet below. This will make it easy to run and possibly understand . Make sure the code can be executed just by copying .
For this Snippet code :
private readonly HttpClient _httpClient = new HttpClient();

[HttpGet, Route("DotNetCount")]
public async Task<int> GetDotNetCount()
{
    // Suspends GetDotNetCount() to allow the caller (the web server)
    // to accept another request, rather than blocking on this one.
    var html = await _httpClient.GetStringAsync("https://dotnetfoundation.org");

    return Regex.Matches(html, @"\.NET").Count;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d885f1eb-2b37-693b-c91f-74b748c9424a
* Version Independent ID: 77bdee53-c2a0-e16f-c93a-3ca0afae0b93
* Content: [Asynchronous programming - C#](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-scenarios)
* Content Source: [docs/csharp/asynchronous-programming/async-scenarios.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/async-scenarios.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @kirancobe 

Our newer samples generally do include the full source, with a link to our samples repo. As we update older samples, we make sure to add them.

Adding this to our backlog for when we next update this article.

**Comment by Rick-Anderson** [comment]
@BillWagner  this might be a good issue to add the [code help wanted](https://github.com/dotnet/AspNetCore.Docs/labels/code%20help%20wanted) label like we've done. We've had good luck with getting help on those

**Comment by BartoszKlonowski** [comment]
@BillWagner I will handle that!
