### ISSUE TITLE
Where did the documentation for F# compiler error messages go to?

### ISSUE THREAD

**Issue by RonaldTM9999** [dotnet/docs#36149]
Hi all,

It seems that the F# resources linked in the compiler messages for errors are leading to an HTTP 404. I have one such instance while using Ionide where the linked resource https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-messages/fs1241, which doesn't seem to exist anymore. I assume that its inclusion implies it worked at some stage. I wanted to find out where the content was shifted to and whether there is documentation on the said shift.

For more context, you can read the related [issue ](https://github.com/ionide/ionide-vscode-fsharp/issues/1893).

**Comment by gewarren** [comment]
The links in the product are generated based on a pattern, so the fact that it exists doesn't mean there was ever a proper target. Is it okay to close this issue?

**Comment by RonaldTM9999** [comment]
Thank you for clarifying @gewarren which team is responsible for checking if the URL exists before presenting it to the user?
