### ISSUE TITLE
Selecting Language C++ - Examples shown in C#

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#3620]
# Issue Title
On page: https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=netframework-4.7.1#Applies_to Selecting Language C++ gives examples in C#.

# General

See the graphic - The language requested is C++, while the examples offered are shown in C#

[2017-11-06_15-52-16](https://user-images.githubusercontent.com/3630329/32450044-1d0b2db6-c30b-11e7-9ed4-890399ab447c.png)

I've had a look at the XML for this page but nothing jumps out.

**Comment by mairaw** [comment]
@eisenbergeffect @dend that page doesn't have a C++ sample. Did we change something in the site to display a different language when the language selected is not available? This might be confusing to readers.

**Comment by EisenbergEffect** [comment]
I think engineering may have made a change in this respect, probably to fix a bug in another area of the site. If the language that is selected isn't available, what would you expect to happen? I assume that right now it just falls back to the default language. I'll check with engineering to be sure. Just not displaying any code samples doesn't seem like the right option either. Should we display an inline message for every code sample explaining that it's not available in the selected language? Or a message at the top of the screen? Feedback welcome.

**Comment by doctordns** [comment]
Seems to me that the Languages pull-down should be populated only from the languages for which there ARE samples?

Also - There was a Pull Request on this page, adding a PowerShell sample, but this does not show up either?

**Comment by EisenbergEffect** [comment]
@doctordns I agree. This is a shortcoming in the way that the language dropdown is populated today. It's completely disconnected from what code samples actually exist on a given page ;( That's something I've wanted to fix for a long, long time but it has been continually pushed down the priority list relative to other fixes/features. I'm trying to raise the priority again in an upcoming sprint, since several engineering dependencies have been completed which would simplify this fix.

Today, the dropdown options are populated via configuration. It can be customized on a per-page basis to be more accurate. @mairaw Is it possible to make the metadata correction for this API? or is this all auto-generated and can't be addressed in that way?

**Comment by mairaw** [comment]
Ideally, it would behave like @doctordns describes. It would auto-populate based on what samples are available from a list of languages we provide to be filtered. This is to distinguish from code identifiers that would not be filtered. For example, XAML or XML would always be displayed and not be part of a filter.

Another option would be to show a message similar to what MSDN does if the language you selected doesn't have a sample. 

The PowerShell example is on this page actually: https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.supportsdaylightsavingtime?view=netframework-4.7.1
I need to manually configure certain pages to have the filter to show up. I'll do it for this one. But it's really cumbersome to have to manually add or remove languages from the filter for each API. We have more than 100k API pages.

**Comment by doctordns** [comment]
OK – first thanks for finding that that PowerShell Sample has gone up. Sadly, the sample is on the wrong page – and I am NOT sure how that happened! 😊

Two more things relating to this first sample (besides the fact that the sample is on the wrong page):

  1.  The Language selector does not affect whether or not the PS sample is shown. On the ‘supportsdaylightsavingtime’ page, the ‘ps’ sample is shown no matter what the language selector is set to. Now for an utter PowerShell bigot like myself, this is a good thing, but for normal users selecting C# or VB – and getting PowerShell just seems wrong.  Can someone point out what went wrong here? Did the markup not work properly. Or is there something deeper at work here?
  2.  On the rendered ‘daylightsavingtime’ page, the PowerShell code is show as ‘ps’ as opposed to ‘C#’, ‘VB’, or ‘C++’ (i.e. with letters in lower vs upper case). Should the ‘ps’ be ‘PS’, or should it be PowerShell’?  Given that PowerShell v6 is being called PWSH, I’d opt to use that name (instead of PS, ps, PowerShell, PSH, etc). Comments?

To be clear: I really want to get the model right for how PowerShell code is added to the MSDN library. I want the code to look good. To my way of thinking, I should be able to select language as: C#, VB, or PS and JUST see the relevant samples. And the languages pull down should only list those languages for which there are examples. If there are C++, or PWSH samples on the page, great, but if a page has, say. NO VB samples. Then the language pulldown should not be populated with VB.

I would also suggest the following:

  1.  The XML that contains the actual documentation (and which links to other files for the actual samples), be updated so that at the top of the XML, there is an element that specifies what languages this page has emples for. So,  at the start of the page (e.g. https://github.com/dotnet/docs/blob/master/xml/System/TimeZone.xml ) you could have:


<SamplesLanguages>
    <SampleLanguage>C#</SampleLanguage>
    <SampleLanguage>PWSH</SampleLanguage>
    <SampleLanguage>VB</SampleLanguage>
  </SampleLanguages>



  1.  That we have a contribution rule that says if you want to add language samples to a page, you have to include ALL samples. So if a page has 4 VB/C# samples, I’d need to add all four PWSH samples. That would be a guideline for acceptance rather than a rule that can be enforced in code.

Comments?

Thomas

**Comment by EisenbergEffect** [comment]
Quick update: We're working through some of the configuration to make some small improvements to this in the short-term. Beyond that, we've got some feature work planned to improve both the underlying code block functionality and the UI. So, we hope to make some larger improvements to this in the future. Thanks for all the feedback and for taking the time to work through the details.

**Comment by mairaw** [comment]
@doctordns There are a lot of improvements that need to happen, but the good news is that there's a team dedicated to make sure that happens.

The ps thing was an error. The correct way of referencing was code-powershell which I fixed with PR #3632. So now it will say PowerShell and not ps. I also tried to add the filter to that page. Not sure if it worked. (We can also fix to add the sample to the right page but then the filter has to be moved to the right page as well)

I'm also fixing the style guide with this PR: #3647

In terms of contribution rule, we cannot enforce that people will add all languages. I'd say C# is required and we try to at least have VB parity that either the contributor or our team will add. F# and PowerShell samples are community contributions. C++ is optional too.

**Comment by doctordns** [comment]
Just wondering if there was any progress on this?

**Comment by EisenbergEffect** [comment]
@doctordns From a publishing platform perspective, I can say that we understand the issues well and plan to address them. However, at the moment, we don't have the resources to do so. I have raised the priority in our backlog and hope that we can move this forward within a few sprints.

**Comment by doctordns** [comment]
I appreciate that resources are not infinite. This issue is something I can't fix (Only you guys can!). It is suboptimal that the language picker stuff is not automagic (just add any sample and it just works). But such is life.

I can wait till the fix, but as I plan to add more samples, the need for this fix is likely to grow. 

Of course, my inner PowerShell geek loves the idea that you see the PowerShell sample regardless. :-)

**Comment by mairaw** [comment]
@doctordns I've moved this issue to the engineering team repo:
https://github.com/MicrosoftDocs/feedback/issues/927

So closing this one.

**Comment by doctordns** [comment]
Thanks for the update.
I'd sure love to see this issue become resolved...
