### ISSUE TITLE
Fix Link to Sample Application in Microsoft Document

### ISSUE THREAD

**Issue by MohitGargMSFT** [dotnet/docs#3623]
Fix Link to Sample Application in Microsoft Document

Regarding this document - https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application  

in above document , in Create a Sample Application section
Link to LocBaml Tool Sample does not work 

edit by @mairaw: added docs info below 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by wadepickett** [comment]
@rpetrusha, please make sure this one gets assigned soon.

**Comment by mairaw** [comment]
I've asked @mohit14mar to file this one. I need to follow up with the product team to see if there's a good replacement for this. It could be https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc.

**Comment by manojsubramani** [comment]
Could it be this? https://github.com/Microsoft/WPF-Samples/tree/master/Getting%20Started/HelloWorld

**Comment by mairaw** [comment]
@SamBent @sachingo can you guys help us find where the LocBaml tool is now located or if it was deleted? Our old link http://go.microsoft.com/fwlink/?LinkID=160016 no longer works. 
My guess would be https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc.

**Comment by rabanti-github** [comment]
Hi
I found the original source code of the locbaml tool on github. However, I am not sure whether the author published these sources on behalf of Microsoft or “by accident”. I don’t want to get this person into trouble by pointing at him/her. Therefore, just search for “locbaml” in github and you find it.

Is there a license for the locbaml tool? The source files are only annotated with “Copyright (c) Microsoft Corporation.  All rights reserved.“ And no license information seems to be available.

**Comment by mairaw** [comment]
@rabanti-github if you're talking about the one I pointed earlier (https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc), that repo has an MIT license.

The one I could find on GitHub (https://github.com/JeremyDurnell/locbaml) doesn't seem official.

@SamBent can you confirm which link should we use to replace https://archive.msdn.microsoft.com/Project/Download/FileDownload.aspx?ProjectName=wpfsamples&DownloadId=9333? Does my suggestion to point to https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc sounds good?

**Comment by rabanti-github** [comment]
The unofficial project seems to be originating from Microsoft. I assume it was the old locBaml sample project mentioned (among others) in: [https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application). All described features in this tutorial seems to be implemented in this unofficial project. 

The other project seems however not to be a proper replacement. [https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc/LocApp](https://github.com/Microsoft/WPF-Samples/tree/master/Globalization%20and%20Localization/BAML%20Loc/LocApp) has almost no content when it comes to code. It is only a WPF window with two text blocks. Localization features are not even implemented there. Is it planned to update this project?

I am a little bit clueless at the moment.
* Project A is unofficial and seems to be the six year old sample project from Microsoft but with unclear legal status.
* Project B is official but seem not to resemble the purpose of a demonstration of localization or the use of the BamlLocalizer class / locBaml sample.

**Comment by mairaw** [comment]
I'm marking this one as blocked. @vatsan-madhavan could you help us figure out if we published or intend to publish this LocBaml tool sample? Please see issue history for more context. 

/cc @OliaG

**Comment by vatsan-madhavan** [comment]
Sorry for missing this thread for several days. 

Would you mind opening an issue for this at https://github.com/dotnet/wpf - asking for LocBaml to be published ?

**Comment by mairaw** [comment]
No worries @vatsan-madhavan. Issue filed: https://github.com/dotnet/wpf/issues/498
