### ISSUE TITLE
Update guidance for packaging 2 new subdiretories under dotnet/packs/ 

### ISSUE THREAD

**Issue by omajid** [dotnet/docs#36234]
With .NET 8 Preview 6, we have two new directories under the `dotnet/packs` directory:

dotnet/packs/Microsoft.AspNetCore.App.Runtime.${runtime_id}/${aspnetcore_runtime_version}
dotnet/packs/Microsoft.NETCore.App.Runtime.${runtime_id}/${runtime_version}

What's the recommendation for packaging these two directories?

Should they be part of `dotnet-targeting-pack` and `aspnetcore-targeting-pack`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce2ad2f-c2fb-b15a-fb97-75417a1b51e8
* Version Independent ID: 40eec307-4ff8-e68f-c8a7-ead32cccf776
* Content: [.NET distribution packaging](https://learn.microsoft.com/en-us/dotnet/core/distribution-packaging)
* Content Source: [docs/core/distribution-packaging.md](https://github.com/dotnet/docs/blob/main/docs/core/distribution-packaging.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tmds
* Microsoft Alias: **dotnetcontent**

**Comment by omajid** [comment]
cc @NikolaMilosavljevic @tdykstra @tmds

**Comment by tmds** [comment]
> What's the recommendation for packaging these two directories?

See https://github.com/dotnet/source-build/discussions/3535.

Please add your comments and feedback to that discussion.
