### ISSUE TITLE
Need for an example for some rules

### ISSUE THREAD

**Issue by lbosnjak** [dotnet/docs#36244]
First of all thank you for your effort to provide proposals for common coding standards.  
Especially the provided examples are very helpful.

For me the purpose of the following rule is comprehensible, but I don't know how this should be put into practice. So a short example would be helpful:
    Commenting conventions
        - Ensure all public members have the necessary XML comments providing appropriate descriptions about their behavior.

There are also other rules in the document where a short example would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [Common C# Coding Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising that issue @lbosnjak 

This page should link to the language reference article on [creating XML documentation](https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/). 

I'll add this to our backlog for our next update, and add the help wanted tag if anyone wants to submit a PR in the meantime.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!

As for the second part of the issue:
> There are also other rules in the document where a short example would be helpful.

I will go through the article in perhaps separate PR and provide some parts with missing examples.
