### ISSUE TITLE
Accessibility rules for record and record struct

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#36248]
There's no mention of the default or allowed accessibility for `record` or `record struct` or members of these types.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6d56158-da5c-4124-a105-db8af724f3af
* Version Independent ID: 51389ca5-2d35-b830-2b48-54293c880839
* Content: [Accessibility Levels - C# Reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels)
* Content Source: [docs/csharp/language-reference/keywords/accessibility-levels.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/accessibility-levels.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The `record` keyword is a modifier for either `class` or `struct`. (If both are omitted, `class` is assumed).

Therefore, the same access modifiers are allowed, and the default is `internal`. 

This should be added as a "note".  I've added it to our backlog for this article, and added the "help wanted" label.

**Comment by BartoszKlonowski** [comment]
@BillWagner I can work on this!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski 

I've assigned it to you.
