### ISSUE TITLE
String interpolation docs still recommend FormattableString.Invariant

### ISSUE THREAD

**Issue by Alex-Sob** [dotnet/docs#36256]
This page still recommends to use `FormattableString.Invariant`:
https://learn.microsoft.com/en-gb/dotnet/csharp/tutorials/string-interpolation

As Stephen pointed out in his [article](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/), new `string.Create` overload should be used for that.

It seems like [CA1305](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1305) documentation should be updated as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3c4c67-250d-50ac-35e7-b11a20d13ba0
* Version Independent ID: 2dab9569-8748-1325-d9b7-78c3f728deef
* Content: [String interpolation in C#](https://learn.microsoft.com/en-gb/dotnet/csharp/tutorials/string-interpolation)
* Content Source: [docs/csharp/tutorials/string-interpolation.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/string-interpolation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 132725](https://dev.azure.com/msft-skilling/Content/_workitems/edit/132725)

**Comment by BillWagner** [comment]
Thanks for noting this @Alex-Sob 

/cc @gewarren for the CA1305 comment.

**Comment by cremor** [comment]
@gewarren You've updated the [CA1305](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1305) documentation with #36285 but the example at the bottom of that page still uses `FormattableString.Invariant`.

**Comment by gewarren** [comment]
> @gewarren You've updated the [CA1305](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1305) documentation with #36285 but the example at the bottom of that page still uses `FormattableString.Invariant`.

Thanks I just updated it in #36371.

**Comment by pkulikov** [comment]
I would like to update the C# tutorial/reference article, unless someone is already on it. @gewarren ?

**Comment by gewarren** [comment]
> I would like to update the C# tutorial/reference article, unless someone is already on it. @gewarren ?

It's all yours @pkulikov.
