### ISSUE TITLE
What do you need to do when the serialising created space seperated keys

### ISSUE THREAD

**Issue by Tractorboy99** [dotnet/docs#36275]
I have a JSON file that has items defined with spaces
Field Name
File Date

It would be useful to have to documentation expanded to include the above type of things, as these are real world issues that are well worth documenting.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to)
* Content Source: [docs/standard/serialization/system-text-json/how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
Hi there @Tractorboy99 - it's not best practice, nor very common to include spaces in keys, but it is certainly possible. Simply use the `JsonPropertyName` attribute (which is covered in the content).

```cs
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

var obj = new ClassWithSpacesInName
{
    FieldName = "This does work",
	FileDate = DateTime.Now
};

var json = JsonSerializer.Serialize(obj);

Console.WriteLine(json);

public class ClassWithSpacesInName
{
	[JsonPropertyName("Field Name")]
	public string FieldName { get; set; }
	
	[JsonPropertyName("File Date")]
	public DateTime FileDate { get; set; }
}

// Outputs:
//   {"Field Name":"This does work","File Date":"2023-07-17T12:47:12.5618682+00:00"}
```

For more info, see [How to customize property names and values with System.Text.Json](https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-7-0).
