### ISSUE TITLE
list package --deprecated doesn't list all deprecated packages

### ISSUE THREAD

**Issue by jackliusr** [dotnet/docs#36273]
list package --deprecated doesn't list all deprecated packages. I used "list package --deprecated" to list all deprecated packages. however Microsoft.Extensions.Caching.Redis is not in the list.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8400fd6a-d987-1056-283f-9364fbce3c86
* Version Independent ID: 3d4b052c-33fa-cc83-4df6-4a3341f12763
* Content: [dotnet list package command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package)
* Content Source: [docs/core/tools/dotnet-list-package.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-list-package.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 125348](https://dev.azure.com/msft-skilling/Content/_workitems/edit/125348)

**Comment by tdykstra** [comment]
Which SDK version are you using?

**Comment by tdykstra** [comment]
Closing due to no response.
