### ISSUE TITLE
JsonConvert in VB i can't use

### ISSUE THREAD

**Issue by cmpm72** [dotnet/docs#36276]
I changed to Newtonsoft.Json. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58c7d198-f9f6-c29a-7ea4-fc0edf6c7ba5
* Version Independent ID: e66324f9-a420-564e-b077-40224a9ff473
* Content: [Visual Basic support for System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/visual-basic-support)
* Content Source: [docs/standard/serialization/system-text-json/visual-basic-support.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/visual-basic-support.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment]
`JsonConvert` is part of `Newtonsoft.Json`, not `System.Text.Json`.
