### ISSUE TITLE
Exception in pattern matching docs bears an incorrect message

### ISSUE THREAD

**Issue by jarroput** [dotnet/docs#36278]
The error message of the `InvalidOperationException` for this case: `(true, false, WaterLevel.High)` show the opposite of what is actually the case.

```
public void SetLowGate(bool open)
    {
        LowWaterGateOpen = (open, LowWaterGateOpen, CanalLockWaterLevel) switch
        {
            (false, _, _) => false,
            (true, _, WaterLevel.Low) => true,
            (true, false, WaterLevel.High) => throw new InvalidOperationException("Cannot open high gate when the water is low"),
            _ => throw new InvalidOperationException("Invalid internal state"),
        };
    }
```

Should be "Cannot open **low** gate when the water is **high**"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afb14275-1810-ff4d-783f-733e8ea3d858
* Version Independent ID: 071e85e4-6fc9-8aff-bbf5-778d5e499f88
* Content: [Use patterns in objects - C# tutorial](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/patterns-objects)
* Content Source: [docs/csharp/whats-new/tutorials/patterns-objects.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/patterns-objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing that out @jarroput 

I've added it to our backlog and added the "help wanted" label if anyone wants to submit a PR before we get to it.
