### ISSUE TITLE
it says open .vscode/launch.json - but gives no clue as to where the file is and how to do it!

### ISSUE THREAD

**Issue by walkerjian** [dotnet/docs#36270]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d7fd04-e358-9a83-aef2-bfcba1169699
* Version Independent ID: f5df932b-b092-2832-9c9a-61a9c43dcdb3
* Content: [Debug a .NET console application using Visual Studio Code - .NET](https://learn.microsoft.com/en-au/dotnet/core/tutorials/debugging-with-visual-studio-code)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Open a file by selecting menu option **File** > **Open File**. The *.vscode* folder is in the project folder.
