### ISSUE TITLE
.NET 8: Testing metrics with IMeterFactory 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#36287]
[Introduce DI friendly IMeter<T> for modern services ](https://github.com/dotnet/runtime/issues/77514)

@dpk83 @noahfalk @JamesNK is this the right place to document [IMeterFactory](https://source.dot.net/#System.Diagnostics.DiagnosticSource/System/Diagnostics/Metrics/IMeterFactory.cs,567b08ef6664a84e)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbacc590-317c-2ddb-1b5f-a3a39ff10cc7
* Version Independent ID: bdeccf7f-a105-68af-33a9-98991da6218d
* Content: [Metrics Overview](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics)
* Content Source: [docs/core/diagnostics/metrics.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/metrics.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

---
[Associated WorkItem - 242720](https://dev.azure.com/msft-skilling/Content/_workitems/edit/242720)

**Comment by noahfalk** [comment]
Yeah, I think this is a good place. I assume we'd put something on the Instrumentation page that shows all the other code examples of using Meter?

**Comment by IEvangelist** [comment]
No longer needed, see https://github.com/dotnet/docs/pull/40373#pullrequestreview-1990143866
