### ISSUE TITLE
.NET 8: write sample code using IMeterFactory 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#36335]
Rewrite the sample in [Creating Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation) to use `IMeterFactory`
The sample should use the updated style found in docs/core/diagnostics/snippets/Metrics/Program.cs and [Collect metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection)

See https://github.com/dotnet/runtime/issues/77514

Sample goes in docs/core/diagnostics/snippets

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61024acd-c2e8-291a-3007-7f09a1857690
* Version Independent ID: 02ec1bf2-d0fe-dac5-b2c1-45d607430b06
* Content: [Creating Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation)
* Content Source: [docs/core/diagnostics/metrics-instrumentation.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/metrics-instrumentation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by Rick-Anderson** [comment]
@julealgon would you be able to update this sample code to use `IMeterFactory`?

**Comment by sammychinedu2ky** [comment]
I'm interested

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson, the samples there are for console apps. the IMeterFactory is usually used for retrieving the Meter object from the service principle. Do you still want the service principle to be used in console apps?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, the samples there are for console apps. the IMeterFactory is usually used for retrieving the Meter object from the service principle. Do you still want the service principle to be used in console apps?

@noahfalk  can you outline what the new sample should be and review this issue?

**Comment by noahfalk** [comment]
[Creating metrics page](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation) was [modified](https://github.com/dotnet/docs/pull/36781) since this issue was first opened and it now does have a [sample that uses IMeterFactory](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation#get-a-meter-via-dependency-injection). 

If you think further changes to the page would be useful I'm open, let me know what changes you have in mind.
