### ISSUE TITLE
Range Operator Cheat Sheet

### ISSUE THREAD

**Issue by TheCakeMonster** [dotnet/docs#36338]
I find the syntax of the Range operator to be very difficult to remember, and thus very difficult to read. There are lots of permutations and I cannot find a very simple overview of the options available in the docs. This tutorial is good for learning, but not for referring to when trying to write the range syntax, or understand what is already written. It's too long and verbose and the various options are not called out clearly.

The syntax is so problematic that I often write a string manipulation feature using SubString and then have an analyzer complain at me for not using range, only to use the analyzer fix to do what it wants - thus making the code less readable, but getting what I intended in the first place. That process results in it taking a long time to make use of range.

If there is a range operator cheat sheet then it would be ideal to refer to it from this page. If there isn't then creating one and then linking it would be even better!

A cheat sheet would be all of the syntax in an easy to read table, and perhaps beneath an example of each syntax with the code and the expected result.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a92f2fd3-888f-340e-72dd-8a3338313783
* Version Independent ID: 67981ff3-5016-3147-b3c2-5bc16efe1416
* Content: [Explore ranges of data using indices and ranges](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes)
* Content Source: [docs/csharp/tutorials/ranges-indexes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/ranges-indexes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a great suggestion @TheCakeMonster 

I think the "cheat sheet" you want is [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#range-operator-).

Do you think the table in the linked section meets your needs? Or is more needed?

I'll tag this as an enhancement, and add the help-wanted tag on the assumption that this is the right link.

**Comment by IEvangelist** [comment]
This was the original PR: https://github.com/dotnet/docs/pull/31223

**Comment by TheCakeMonster** [comment]
@BillWagner Ah yes, thank you for the link, that's exactly what I have been looking for.

Perhaps what took me by surprise is that it forms part of a larger page titled the way it is, rather than on its own. That isn't somewhere I would have thought to look based upon the title of the page. I wonder how likely this page is to show up in search results when looking for help on the range operator; maybe that grouping of information makes more sense to those who know how the docs are structured, or have intimate knowledge of the language, than to others?

So the good news is that we have the information - and I have bookmarked the link so that I can find it again! Maybe we just need to add a link to it from the page in the fundamentals section on which this issue is based? I think that would be a valuable addition, perhaps in a further information/additional resources section.

Thanks for your help.

**Comment by TheCakeMonster** [comment]
Oh, and to answer your question more fully, yes I think the format in which the information is provided in that section is ideal. It shows exactly the type of table layout that makes it easy for me to understand and digest. I think that remains true even if someone is only scanning their eye across the page quickly, so it is great as a quick-reference guide.

The fact that there is also a code-based sample just below should also help those that find it easier to absorb information from code than from the written word.
