### ISSUE TITLE
Console JSON Serialization Options

### ISSUE THREAD

**Issue by rcollina** [dotnet/docs#36349]
Hello,
As far as I can tell there's no way to register custom serializers with the OOTB JSON Console Formatter. Is that correct?

Also, it doesn't seem there's a way to serialize Dictionary<string, object> instances - i.e. I'd like to output arbitrarily nested objects in stdout.

```
var data = new Dictionary<string, object>
{
    ["NestedObject"] = new Dictionary<string, object>
    {
        ["Now"] = DateTime.UtcNow
    }
};

logger.LogInformation("{Object}", data);
```

This is the output:

![image](https://github.com/dotnet/docs/assets/699839/8120965c-140f-4fc2-a8a0-b22b0f45c02f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: daf7ff20-63e5-215c-047b-92d414eb314b
* Version Independent ID: 6bde6805-1867-ebfc-9773-a792b75318fe
* Content: [Console log formatting - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter)
* Content Source: [docs/core/extensions/console-log-formatter.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/console-log-formatter.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 133306](https://dev.azure.com/msft-skilling/Content/_workitems/edit/133306)

**Comment by IEvangelist** [comment]
Hi @rcollina - there are some bits that you can configure when adding (caling [`AddJsonConsole`](https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addjsonconsole?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-consoleloggerextensions-addjsonconsole(microsoft-extensions-logging-iloggingbuilder-system-action((microsoft-extensions-logging-console-jsonconsoleformatteroptions))))).

There's an overload that accepts an [`Action<JsonConsoleFormatterOptions>`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.console.jsonconsoleformatteroptions?view=dotnet-plat-ext-7.0), and these options expose the [`JsonWriterOptions`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.console.jsonconsoleformatteroptions.jsonwriteroptions?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-console-jsonconsoleformatteroptions-jsonwriteroptions).

But I'm not sure if you're asking about writing your own custom one, or just configuring the existing one. You have the ability to do either.

**Comment by rcollina** [comment]
Hello @IEvangelist, thank you for your reply and sorry for not getting back to you sooner.

The current options have no means to inject custom converters (i.e. for complex data types such as Dictionaries) a la `JsonSerializerOptions`.

I guess the only way at the moment is to prevent what happens in attached screnshot is to implement a custom formatter that handles more data types.

**Comment by IEvangelist** [comment]
Yes, you're correct - the custom option feels appropriate in this situation. I'll close this issue, thank you.
