### ISSUE TITLE
Not helpful

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [dotnet/docs#36359]
[Enter feedback here]
Neither expands on what the error means or how to resolve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31e2520c-3b55-9bec-7f69-2075cb44b4d7
* Version Independent ID: 7cbccd18-eab8-ff49-b3e5-3e320f64cdc8
* Content: [Compiler Error CS0453](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0453)
* Content Source: [docs/csharp/misc/cs0453.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0453.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Lindsay-Mathieson 

This error indicates that the argument used for a type parameter isn't a non-nullable `struct` type when that constraint is used. 

To fix the error, you'll need to change the type argument to a type that satisfies the `struct` constraint.

[This article](https://learn.microsoft.com/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters) explains constraints in detail, and should be linked from this article.

I'll put this in our backlog to fix when we next update this article. I've also added the "help-wanted" label in case anyone wants to submit a PR before we update this article.

**Comment by Lindsay-Mathieson** [comment]
> [This article](https://learn.microsoft.com/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters) explains constraints in detail, and should be linked from this article.
> 
> I'll put this in our backlog to fix when we next update this article. I've also added the "help-wanted" label in case anyone wants to submit a PR before we update this article.

Thanks, that is quite helpful.

**Comment by BartoszKlonowski** [comment]
@BillWagner I'll work on this!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski I've assigned it to you. I'll watch for a PR.
