### ISSUE TITLE
Linking to ApiCompat notes for differences in behavior between .NET Framework and Core

### ISSUE THREAD

**Issue by kouvel** [dotnet/docs#3640]
There are several differences in behavior between .NET Framework and .NET Core that are documented here: https://github.com/dotnet/corefx/wiki/ApiCompat

It may be beneficial to link to that page from doc pages for affected APIs, or to fold that information into the official docs.

**Comment by mairaw** [comment]
Thanks for your feedback @kouvel. We plan to fold that info to the official docs.

/cc @pjanotti

**Comment by mairaw** [comment]
This should be kept open @kouvel. We need to add that information to our APIs.

**Comment by kouvel** [comment]
@danmosemsft, I'm not sure if you're the right person for this but do you know if the api-compat doc linked above is still applicable/valid? Is there more recent info that could be used for documenting differences in behavior / differences in APIs between runtimes?

**Comment by pjanotti** [comment]
The idea is to deflate the wiki and eventually have its content at https://github.com/dotnet/platform-compat (ideally as rules but if not possible to express as rules keep as wiki). However, these hasn't being a priority. 

One observations is that the tool should reflect status of current/latest release, so it won't be a good source for consultation about specific versions, this will be better handled via documentation.
