### ISSUE TITLE
Is DOTNET_gcSERVER available on .NET 5?

### ISSUE THREAD

**Issue by aueda** [dotnet/docs#36427]
Hi there,

Regards to the DOTNET_gcSERVER variable, the document says "For .NET 5 or later versions", but the table right below in the section "Workstation vs. server" says it was introduced in .NET 6 only.

From my understanding, this variable is not available in .NET 5. Is that correct?

Thank you,

Adriano

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95249f95-dd1e-c3e2-032a-2c91057c50d4
* Version Independent ID: 5363faee-3808-d011-d371-c48a95dcabf0
* Content: [Garbage collector config settings - .NET](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector?source=docs)
* Content Source: [docs/core/runtime-config/garbage-collector.md](https://github.com/dotnet/docs/blob/main/docs/core/runtime-config/garbage-collector.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Yes, .NET 6 introduced the "DOTNET_" prefix for environment variables. For .NET 5, use `COMPlus_gcServer`. I'll update the article to be less confusing.

**Comment by aueda** [comment]
Hey @gewarren,

Got it! Thanks for your reply!

Adriano
