### ISSUE TITLE
The claim that the Memory overloads are more performant than the byte[] overloads appears to be false

### ISSUE THREAD

**Issue by gavinBurtonStoreFeeder** [dotnet/docs#36438]
The implementation detail behind the Memory overloads delegates directly to the byte overload. As such, the performance of the memory overload will be the same or worse.

Do we have access to some benchmarks proving that one method is faster than the other?

The code in question is here;
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L310

Given that performance is the only justification given for calling AsMemory on a byte[] before using it with this method, I posit that the rule itself is invalid.

The caveat here is that I've only read one implementation and there may be some edge case - but if this is the true, then the rule needs to specify what this edge case is in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa190dde-c027-f326-252b-39df26dc94d4
* Version Independent ID: 2553bedd-3996-700c-7595-3321b830b5ea
* Content: [CA1835: Prefer the memory-based overloads of ReadAsync/WriteAsync methods in stream-based classes (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1835)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1835.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1835.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @carlossanlop
* Microsoft Alias: **calope**

**Comment by macrogreg** [comment]
This is still current, I am not sure that closing this was the right thing to do.
I re-filed this issue in the Roslyn-Analyzers repo, perhaps it finds better traction there (https://github.com/dotnet/roslyn-analyzers/issues/7328).
