### ISSUE TITLE
Code example in the Managed Threading Best Practices topic does not match text

### ISSUE THREAD

**Issue by alex-groshev** [dotnet/docs#3645]
Page: https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-best-practices

Chapter: Deadlocks

Text: 

> For example, the following code attempts to acquire a lock on the current instance.

C# Code:

`if (Monitor.TryEnter(lockObject, 300)) {  
    try {  
        // Place code protected by the Monitor here.  
    }  
    finally {  
        Monitor.Exit(this);  
    }  
}  
else {  
    // Code to execute if the attempt times out.  
} `

VB Code:

`If Monitor.TryEnter(lockObject, 300) Then  
Try  
        ' Place code protected by the Monitor here.  
    Finally  
        Monitor.Exit(Me)  
    End Try  
Else  
    ' Code to execute if the attempt times out.  
End If `

As you can see from above, the code attempts to acquire a lock on **lockObject** and NOT on the current instance. Either the code snippets have to be changed or text.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @alex-groshev. We'll address it sometime next week.
