### ISSUE TITLE
[Breaking change]: RuntimeInformation.RuntimeIdentifier returns platform for which the runtime was built

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/docs#36466]
### Description

`RuntimeInformation.RuntimeIdentifier` will return the platform for which the runtime was built, rather than a value computed at run time.

PR: https://github.com/dotnet/runtime/pull/89598
Related:
- https://github.com/dotnet/sdk/pull/34279
- https://learn.microsoft.com/dotnet/core/compatibility/deployment/8.0/rid-asset-list

### Version

.NET 8 RC 1

### Previous behavior

The value was a RID computed via OS files and/or APIs. This generally meant it was a version-specific and distro-specific RID. For example, when running an application on Windows 11, it would be `win10-x64` or on Ubuntu 20.04, it could be `ubuntu.20.04-x64`.

### New behavior

The value is the RID for which the runtime was built. This means that for portable builds of the runtime (all Microsoft-provided builds), it will be non-version-specific and non-distro-specific. For example, when on Windows 11, it would be `win-x64` or on Ubuntu 20.04, `linux-x64`. For non-portable builds (source-build), the build sets a build RID at that can have a version/distro and that value is the RID for the runtime will return.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [X] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

This is in line with a .NET 8 change to [RID-specific asset resolution](https://learn.microsoft.com/dotnet/core/compatibility/deployment/8.0/rid-asset-list) and the move away from a distro-aware runtime. `RuntimeInformation.RuntimeIdentifier` is an opaque value that should represent the platform on which the host/runtime considers itself to be running. In .NET 8, that corresponds to the platform for which the host/runtime is built, rather than a RID computed at run time.

### Recommended action

`RuntimeInformation.RuntimeIdentifier` is an opaque value and not intended to be parsed into its component parts. For the OS version of the actual machine an application is running on, `Environment.OSVersion` can be used. For a description, `RuntimeInformation.OSDescription` can be used. For a specific ID (distro) and corresponding version on Linux, users would have to read the [os-release](https://www.freedesktop.org/software/systemd/man/os-release.html) file.

### Feature area

Core .NET libraries

### Affected APIs

`RuntimeInformation.RuntimeIdentifier`

---
[Associated WorkItem - 156743](https://dev.azure.com/msft-skilling/Content/_workitems/edit/156743)

**Comment by RussKie** [comment]
Few typos:
![image](https://github.com/dotnet/docs/assets/4403806/3045b1ce-fadf-440a-bb7a-218155172093)

**Comment by elinor-fung** [comment]
Thanks. That last sentence there was also impressive - apparently I decided to stop being comprehensible in that section. Fixed.
