### ISSUE TITLE
Style Guide update suggestions

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#3649]
# Some suggested improvements to the Style Guide

# General
The dotnet/docs repo has a style guide which contains a document called _**Voice and tone guidelines**_  (docs/styleguide/voice-tone.md ).
This is a great document and I am so glad to see these kinds of things. I wish all IT sites were as focused on writing quality!  

With that said, I'd like to add two additional guidelines:

1. **Avoid split infinitives** - While to boldly go may sound good on TV, split infinitives can reduce the readability. So, to go boldly...

2. **Avoid future tense**. Two points here - first is that in some non-English the concept of future tense is not the same as English making the docs harder to read for those folks. Secondly, when using the future tense, the obvious question is when. So if I say 'Learning PowerShell will be good for you" - the obvious question is when will it be good? To avoid that, just "Learning PowerShell is good for you". 

Also, the final two paragraphs could better be placed under a further guideline: **What Is it - So What" which could read:

You are writing documentation for technical professionals. You can assume that your readers have technical knowledge and understand the specific vocabulary for programming and IT Pro related terms.
Object-Oriented Programming, Class, Object, Function, Method, Cmdlet, Parameter, etc are all terms you can assume your reader understands. 

Whenever you introduce a new concept to the reader, for example describing the .NET Composite Formatting System - you should define the concept and only then explain the benefits and describe the usage. So instead of telling the reader that the Composite Formatting system is very useful, explain what it is first. The term/subject/concept should be defined first then explained. You can also explain a term in passing. So if you wanted to note that the Close() method is idempotent you could say:

>The Close() method is idempotent, meaning that you can call it multiple times and the effect is the same as if you called it once.

## Issues with Existing Topics
There are topics that currently violate these rules - those can be picked up as and when. As readers here may know, I've picked up a number of these. But having these three points in the style guide make those changes easier (ie I can 'update to reflect style guide').  :-)

**Comment by mairaw** [comment]
Thanks @doctordns! @BillWagner to take a look at this issue too.

1. Split infinitive - it's interesting I couldn't find any recommendations regarding this on our internal style guides as well. 
2. Avoid future tense - that's Microsoft's recommendation anyway, so I'd be in favor of adding this. 

I think I prefer the 5th grade section name. Not sure if we need to add the IT Pro emphasis in there too. But I like the idea of enhancing the section when introducing new terms or concepts.

And yes, we're aware that existing topics don't always follow our style guide rules. We do have a label we use to open issues re. that: https://github.com/dotnet/docs/issues?q=is%3Aopen+is%3Aissue+label%3Aguidelines-adherence

We could also look into adding other tips from Microsoft style guide. However, our team is launching a global style guide for docs.microsoft.com that will include things like these (https://docs.microsoft.com/en-us/contribute/help-crr/help-content/style/style-get-started-quick-start) so we need to make sure we're not doubling our efforts here. Those guidelines were put together way before our org had something like that organized.

**Comment by doctordns** [comment]
The split infinitive is one of my things to avoid when writing.  But I think it a good guideline. And likewise future tense.

As to 5th-grade section - I think the point about writing to a 5th-grade level is parallel not necessarily superior so to some of the points after that heading. I would suggest instead we call it General Language Guidelines and include the point of focusing it on a 5th-grade audience. (As an aside, that paragraph should explain what 5th grade is for the non-US audience. ;-)).

Regarding those articles breaking the guidelines - I enjoy seeking out those articles and improving them. I consider it sport! :-)

The style guidelines would be easy to incorporate here. Or should those other guidelines be improved to take advantage of the work done here?

**Comment by BillWagner** [comment]
I've read through the thread, and I agree with @doctordns 's proposed changes, and @mairaw's thoughts. Let's schedule this.

**Comment by doctordns** [comment]
Thanks Bill. I'll get around to offering an update later this week.

ALso - the guidelines suggest a 5th grade reading level. Is that a bit too low? 5th grade is 12 years old. Are API docs really something a 12-year old would be able to understand. I'd be kind of tempted to bump it up a bit and go for 7th-9th grade level. 

What do you think?
