### ISSUE TITLE
VS Mac support in this article needed

### ISSUE THREAD

**Issue by nrushforth** [dotnet/docs#36499]
This article is good if you are using a windows laptop and Visual Studio, however it does not give a user the information required to build and deploy using a Mac. VSMac 2022 publish option does not support the same richness of options that a user of Visual Studio on windows receives.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 853c5e7f-a0b8-c6ba-8744-293407a12e86
* Version Independent ID: 3f79892b-de26-fb7a-77b1-ec02b8a7e566
* Content: [Deploy .NET apps to ARM single-board computers](https://learn.microsoft.com/en-us/dotnet/iot/deployment)
* Content Source: [docs/iot/deployment.md](https://github.com/dotnet/docs/blob/main/docs/iot/deployment.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
The article has platform-agnostic instructions in addition to the Windows/VS instructions. The `dotnet publish` command works on every platform.

I can clarify that the VS instruction assume Windows, though.

**Comment by CamSoper** [comment]
VS for Mac is no longer supported
