### ISSUE TITLE
Windows Server 2008 R2

### ISSUE THREAD

**Issue by ahmetSaidKeskin** [dotnet/docs#36520]
For Windows Server 2008 R2

instead of this line
sc.exe failure ".NET Joke Service" reset=0 actions=restart/60000/restart/60000/run/1000

this line did the job
sc.exe failure ".NET Joke Service" reset= 0 actions= restart/60000/restart/60000/run/1000

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create Windows Service using BackgroundService - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 230272](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230272)

**Comment by IEvangelist** [comment]
Hi @ahmetSaidKeskin, thanks for posting this issue. The difference in the commands is nominal, are you implying that the space after the `=` is required on Windows Service 2008 R2?

**Comment by ahmetSaidKeskin** [comment]
> Hi @ahmetSaidKeskin, thanks for posting this issue. The difference in the commands is nominal, are you implying that the space after the `=` is required on Windows Service 2008 R2?

Hi @IEvangelist, that is correct. I mean the space after the `=`.

**Comment by IEvangelist** [comment]
Hi again @ahmetSaidKeskin - is this true for all of the `sc.exe` commands? There are several places in the docs that refer to those.
