### ISSUE TITLE
"Notes to Callers" sections are displaying raw Markdown

### ISSUE THREAD

**Issue by chadunit** [dotnet/docs#3652]
Doc page:
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo?view=netframework-4.7.1

Github page:
https://github.com/dotnet/docs/blob/master/xml/System.Globalization/StringInfo.xml

Text displayed on page:

![image](https://user-images.githubusercontent.com/25489524/32666014-bd756f44-c5fb-11e7-8641-58e1258bd629.png)

**Comment by mairaw** [comment]
Thanks @chadunit for reporting this issue! I think Notes to Callers has recently being implemented in docs and I'll follow up with the engineering team to fix that. 

/cc @dend @adkinn

**Comment by mairaw** [comment]
I'm also wondering if this is just a migration issue where the includes should not have been used in the ECMAXML sections.

**Comment by adkinn** [comment]
I checked the templates and we are supporting markdown there. @mairaw I think you're right about the include files not being found.

/cc @dend @TianqiZhang

**Comment by mairaw** [comment]
The issue is not with includes only. The URLs are also using the wrong format @adkinn. 

/cc @dend @TianqiZhang

**Comment by chadunit** [comment]
FYI I've noticed this seems to be fairly common, see for example:

https://docs.microsoft.com/en-us/dotnet/api/system.string.trim?view=netframework-4.7.1
https://docs.microsoft.com/en-us/dotnet/api/system.string.compare?view=netframework-4.7.1

I guess there probably needs to be some generic systemic fix regarding the Notes to Callers section.

**Comment by mairaw** [comment]
Yes, @chadunit. It probably happens in all docs that have Notes to Callers (or most of them).

**Comment by adkinn** [comment]
@mairaw do you mean the URLs for the include files? Or are there examples where regular links are not working?

**Comment by mairaw** [comment]
@adkinn the example that @chadunit has posted above has both includes and regular links (see the link to the Unicode Standard, Version 8.0.0 link . AFAIK regular links should have the see href format and not a Markdown link format in the ECMAXML sections. So that's why I'm saying this is probably a migration issue. Includes should have been removed and links should have been migrated with the see href notation.

**Comment by mairaw** [comment]
This issue has been fixed.
