### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shanywambu5** [dotnet/docs#36546]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f126dcc5-a960-0b62-019a-d91b039fbad7
* Version Independent ID: d5e04fed-4c49-3737-d02e-34ad25efb790
* Content: [Compiler Error CS2015](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs2015?f1url=%3FappId%3Droslyn%26k%3Dk(CS2015))
* Content Source: [docs/csharp/misc/cs2015.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs2015.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LeaFrock** [comment]
What's the error you mean?

**Comment by BillWagner** [comment]
Hi @shanywambu5 

Can you provide more details here? Do you have a question about this error?
