### ISSUE TITLE
Introduce "code block"s and FS0588

### ISSUE THREAD

**Issue by Happypig375** [dotnet/docs#36542]
![image](https://github.com/dotnet/docs/assets/19922066/c61dcac9-98c2-4685-b2fc-0d3e63601007)

It isn't obvious how to fix this issue.

Existing wording:
> A let binding at the top level in a module or in a class type does not need to have a body expression, but at other scope levels, the body expression is required.

is different from what the error says. It also does not introduce the error by code to make it searchable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0305566-a1cb-6766-3c5f-f24ddc88329a
* Version Independent ID: 5be0c50b-6a84-addd-8699-8e99ee9d86f8
* Content: [let Bindings - F#](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/let-bindings)
* Content Source: [docs/fsharp/language-reference/functions/let-bindings.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/functions/let-bindings.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Hi @Happypig375 

The `let` binding isn't part of the `do` statement. Try this instead:

```fsharp
let x = 2
```

I'll close this as an answered question.

**Comment by Happypig375** [comment]
@BillWagner This isn't a question. The issue is about mismatch between error text and documentation text. The documentation should be updated using words from the error.
