### ISSUE TITLE
dotnet-dump analyze can take multiple commands

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#36648]
This update to the command line help wasn't also added to this doc, see https://github.com/dotnet/diagnostics/pull/3151

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a269a64-0a27-27d3-a509-47b9a0d114bf
* Version Independent ID: 49ff97ff-b39a-5ae8-e4b8-81a4f8eab50c
* Content: [dotnet-dump diagnostic tool - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump)
* Content Source: [docs/core/diagnostics/dotnet-dump.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/dotnet-dump.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by BartoszKlonowski** [comment]
@gewarren I will handle this!
