### ISSUE TITLE
Installing Multiple Versions of .NET Side-By-Side on Linux

### ISSUE THREAD

**Issue by bassem-mf** [dotnet/docs#36640]
The article says the following:

> The preceding install script approach allows installing different versions into separate locations so you can choose explicitly which one to use by which app.

But what most people will want is installing multiple versions of .NET in the same DOTNET_ROOT folder so the right version of .NET is picked automatically for them. And I believe this is possible if you download multiple archives and extract them to the same folder.

```
export DOTNET_ROOT=$HOME/.dotnet
mkdir -p "$DOTNET_ROOT"
tar zxf dotnet-sdk-6.0.413-linux-x64.tar.gz -C "$DOTNET_ROOT"
tar zxf dotnet-sdk-7.0.400-linux-x64.tar.gz -C "$DOTNET_ROOT"
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
```

I could not find the official way of installing multiple versions of .NET side-by-side on Linux anywhere on the Microsoft Learn website. And I believe this page is the best place to document the recommended procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Install .NET on Linux without using a package manager - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 181169](https://dev.azure.com/msft-skilling/Content/_workitems/edit/181169)

**Comment by adegeo** [comment]
Thanks for filing this issue. I've added to my workload.

**Comment by adegeo** [comment]
This slipped through, I thought I had fixed it but I guess I didn't. Adding to Dec

**Comment by adegeo** [comment]
Another thing to do in this PR in Dec is to unify the `~/.dotnet` location in linux/macos manual instructions
