### ISSUE TITLE
Default access

### ISSUE THREAD

**Issue by veroarriola** [dotnet/docs#36650]
[Enter feedback here]
What is the default access of method?
In general, it would be quite useful if you added a table with default access for each component, it is a lot faster to grasp the rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers - C# Programming Guide](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the observation @veroarriola 

We should add the defaults for all declarations:

`class`, `struct`, `interface` (including `record` types):  `internal`
all members (method, field, property, event and indexer): `private`

I've added this to our backlog for when we next update this article. I've also added the "help wanted" label for anyone that wants to submit a pull request before we make the updates.

**Comment by svick** [comment]
@BillWagner Don't forget that nested types default to `private`.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski 

I've assigned it to you. I'll watch for a PR.
