### ISSUE TITLE
Issues/questions I found myself contemplating while reading this post.

### ISSUE THREAD

**Issue by MindaugasPikelis** [dotnet/docs#36665]
1. In the section, Asynchronous exceptions, the tutorial tells us to replace some code in the `MakeToastWithButterAndJamAsync `method. This method after the suggested edit, should throw an exception on code execution. But for me, nothing is thrown. Maybe it's a settings issue I have, but please investigate if this truly does what you're saying it does.

2. Also, I found myself confused after reading a bit of this post, and of course, trying things in my code editor. What exactly does the `await` keyword do? Of course I found myself googling more and found another learn.microsoft post about the await operator, which explains the keyword in more detail, but I'd expect this information to be easily accessible while reading Asynchronous programming overview, wouldn't you?

3. Also, it would be nice if you could take this `MakeBreakfast` final example and explain each line of the output in respect to the code that was written, because right now after reading this post I am not 100% sure whether I understood the execution flow of the program. Your investigation of the flow would give that final push to absolute certainty.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c2a674-a335-4802-5c52-4a2af998cc7f
* Version Independent ID: 3001f6f2-b04b-5513-54a6-fedfccc94e51
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/)
* Content Source: [docs/csharp/asynchronous-programming/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Gavin-Williams** [comment]
@MindaugasPikelis 
Async / Await is like a time-division multi-tasking system that can automatically coordinate the execution of long-running code without blocking the calling thread. If you await a call, you are creating an execution branch that allows the awaited call to run at the same time as the calling code. The async method that contains the awaited call will immediately return to its own caller. And when the awaited call completes, the remainder of the calling method will run. There are also various variations that you can use to modify the behavior.

Take a look at the following code. I have an asynchronous method InitializeGraphics that must perform a number of long running tasks. It has to load some materials and load some models which both require disk access (so they are long-running). But I can't wait for this ElementRenderer to complete that work, I'm already running my game-loop somewhere else and performing updates and rendering for other elements. I can't just stop for 100ms. So I employ async / await to branch the execution at the calls to LoadMaterials and LoadModels. When LoadMaterials is reached, and awaited, the LoadMaterials method starts running, but InitializeGraphics stops running and returns immediately. So the rest of my application just keeps running, updating and rendering as normal.  When LoadMaterials completes, InitializeGraphics starts up again and continues executing, so then LoadMaterials will be called and awaited. Same thing happens, and then after that returns, the rest of InitializeGraphics will run, Finally setting the state to Ready, that's the signal that allows the Render call to actually run. So await has been used to coordinate long running tasks without blocking your application.

```cs
internal class ElementRenderer
{
    private State state;

    public ElementRenderer()
    {
        _ = InitializeGraphics();
    }

    async Task InitializeGraphics()
    {
        if (state != State.NotInitialized) return;

        state = State.Loading;
        await LoadMaterials();
        await LoadModels();
        AssignMaterialsToModels();
        state = State.Ready;
    }

    async Task LoadMaterials() { }

    async Task LoadModels() { }

    void AssignMaterialsToModels() { }

    public void Render() 
    {
        if (state == State.Ready)
        {
            // render element
        }
    }
}
```

**Comment by MindaugasPikelis** [comment]
@Gavin-Williams 
Thank you so much for the answer!
First of all, I haven't finished reading all of the async/await; concurrency; multithreading content that microsoft.learn has to offer, but after that I am sure it would be beneficial for me to read more examples/information on it. I have a book by Jon Skeet, which does have a chapter on asynchronicity, which I will read. And I have found some blogs about the topic as well by Microsoft MVPs. Maybe from your experience you could direct me to a source of knowledge I could sink my teeth in. I would greatly appreciate it! 

I have a couple of questions related to your answer:

1. You wrote: "If you await a call, you are creating an execution branch that allows the awaited call to run at the same time as the calling code"; As I understand, there is `I/O-bound code` & `CPU-bound code`. 

   Both of these binds are ideally handled asynchronously in a bit of a different way with respect to each other. To briefly 
   mention CPU-bound asynchronous handling - we mainly want to create a background thread, which will be lets say a "private 
   space" for our operation. This background thread is created using Task.Run(). And all of this is mainly used when we want to 
   alleviate the UI-thread from some work.

   I/O bound code is a bit different. Here I am a bit lost, and your sentence, which I mentioned in the beginning still kind of 
   obfuscates what is truly happening there. Is there no background threads being created for this process? How are we calling 
   the things that are being created then? Are there even things created?.. Maybe I am digging too deep here, but if you don't 
   want to explain this to me or this has been already explained somewhere, please let me know, this is bugging me quite a lot 
   haha.

NOTE: I've read [this](https://blog.stephencleary.com/2013/11/there-is-no-thread.html) blog, but still it's kind of convoluted.

2. Very nice example and explanation! I can see that you've opted to straight away call the tasks using await in `InitializeGraphics`. Would there be a major difference between your method and this one? 
       
        async Task InitializeGraphics()
        {
            if (state != State.NotInitialized) return;
            state = State.Loading;

            Task loadMaterialsTask = LoadMaterials();
            Task loadModelsTask = LoadModels();

            //maybe do something else here?

            await loadMaterialsTask;
            await loadModelsTask;

            AssignMaterialsToModels();

            state = State.Ready;
        }

**Comment by BillWagner** [comment]
Great comments @MindaugasPikelis  and @Gavin-Williams 

I'll keep this issue open, although I think the fixes are to incorporate these concepts into other articles in this section.

This article is meant to provide your first look at `async` and `await`. It should generate questions as you begin to understand what these concepts do and how they work.

Later articles in this section should (in time) answer all these questions. Furthermore, this article should include clear links for those readers that want to find that information next.

**Comment by MindaugasPikelis** [comment]
Alright! As I read more and more some questions start to be answered. I am sure I'll have to read through all of the docs again after I read them once haha.
Here is a [partial answer](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/task-asynchronous-programming-model#BKMK_Threads) to the first question I had for Gavin.

Feel free to close this issue 👍

**Comment by BillWagner** [comment]
Closed based on previous comment.
