### ISSUE TITLE
Document how Linux/macOS users can use signature validation to validate the install-scripts 

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#36671]
With https://github.com/dotnet/install-scripts/pull/373 the .NET Install-Scripts for bash now support signature validation. We should document how to do this, and where users can get the public key to validate against. We (Install-Scripts team) would love to help with this documentation, this is a tracking issue for us to help with that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by YarekTyshchenko** [comment]
None of the links work for downloading the sig: `https://dot.net/v1/dotnet-install.sig` or `https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sig`. Where is it?

**Comment by MichalPavlik** [comment]
@YarekTyshchenko, the insertion PR is not merged yet.
https://github.com/dotnet/website/pull/5498#issuecomment-1679378566

**Comment by tdykstra** [comment]
Fixed by #36841
