### ISSUE TITLE
Wrong condition in Linq for Query #7

### ISSUE THREAD

**Issue by wsrinivas** [dotnet/docs#36684]
[Enter feedback here]
I think it should be 
`num > 3 && num < 7`
 instead of 
`num < 3 || num > 7`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 527222c2-7532-7753-7ad5-01f0eeddec75
* Version Independent ID: 07d5d82d-a52e-9531-25ec-95e1db5f619c
* Content: [Write LINQ queries in C#](https://learn.microsoft.com/en-us/dotnet/csharp/linq/write-linq-queries)
* Content Source: [docs/csharp/linq/write-linq-queries.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/write-linq-queries.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 147694](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147694)

**Comment by BillWagner** [comment]
Thanks for noting this @wsrinivas 

This query, and the following syntax examples should all change to reflect that.

I've added this to our backlog, and added it to the current sprint. (I've got other edits to make in this section).
