### ISSUE TITLE
Aprender a programar em C#

### ISSUE THREAD

**Issue by Cassisilverston** [dotnet/docs#36685]
🚧 Desenvolvedor Back-end em formação 🚧 

- Obrigado pelo tutorial voltado para iniciantes. Consegui absorver mais sobre essa linguagem que escolhi aprender. Isso é o início de um longo trabalho que será concluído.

💯 Agradecimento 💯 

- Obrigado pelo estilo de aprendizado, por mais que não venha a ser algo profundo, pode-se aprender o básico.
- Tutorial no navegador auxilia muito para quem está começando.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 8053bb96-cc40-8369-c07f-f9fd14060c1e
* Version Independent ID: 293260e2-f444-537b-0ba7-14d1fb6ebcf2
* Content: [Tutorial interativo de C# Olá, Mundo – introdução ao C#](https://learn.microsoft.com/pt-br/dotnet/csharp/tour-of-csharp/tutorials/hello-world)
* Content Source: [docs/csharp/tour-of-csharp/tutorials/hello-world.yml](https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the kind words @Cassisilverston 

I'll close this as kudos.
