### ISSUE TITLE
Finalizer is not understood in this context

### ISSUE THREAD

**Issue by nagualdev** [dotnet/docs#36693]
[Enter feedback here]
Finalizer is not understood in this context, so please include a link to it.
thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a1763d-01e3-0e82-f482-861d54ecb13d
* Version Independent ID: 3fae0421-acf9-6522-1473-5e0f8627cb30
* Content: [Using Exceptions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/using-exceptions)
* Content Source: [docs/csharp/fundamentals/exceptions/using-exceptions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/exceptions/using-exceptions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 147693](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147693)

**Comment by BillWagner** [comment]
Thanks @nagualdev 

I opened a PR to link the text at the bottom of the article to the article on finalizers.
