### ISSUE TITLE
Add examples of no-op logging defaults 

### ISSUE THREAD

**Issue by Pepsi1x1** [dotnet/docs#36709]
Please expand the section with advice on using no-op logging defaults with examples of how this may be achieved. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb767be-972d-9086-a759-d051fb11d555
* Version Independent ID: 3c6a20c4-b69f-8a21-3603-16d18a257ff4
* Content: [Logging guidance for .NET library authors - .NET](https://learn.microsoft.com/en-gb/dotnet/core/extensions/logging-library-authors)
* Content Source: [docs/core/extensions/logging-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by roji** [comment]
@Pepsi1x1 that doesn't seem to be a concern of the library author, but rather of the user of the library. In other words, a user can pass a [NullLoggerProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.abstractions.nullloggerprovider?view=dotnet-plat-ext-6.0) instance to a library, but the library is oblivious of that and just treats it as another ILoggerFactory.

**Comment by Pepsi1x1** [comment]
@roji Thanks Shay, it wasn’t immediately clear that this section was referring to passing a null logger to a ctor. I may have parsed the docs incorrectly, but my immediate thought was the library author providing this as a default in the ctor when constructing the object for example providing an overload without the logger parameter. 

Additionally, while that’s true that it’s not a direct concern in terms of the code the library author may write to achieve an implementation. I can think of two possible scenarios a library author would be concerned with. 

Documenting the code, the author may wish to provide examples of this. 

Unit Testing, where the author may wish to implement tests making use of null loggers. 

I appreciate that for unit testing this is documented elsewhere, however a link to this documentation wouldn’t go amiss.

**Comment by IEvangelist** [comment]
I'm admittedly playing catch up here, been heads down on .NET Aspire docs lately. With that said, you're not the first to ask about this very topic, see my reply https://github.com/dotnet/docs/issues/36712#issuecomment-1999659459. I do think that maybe I should update this article to make that more obvious. Thank you @roji and @Pepsi1x1.
