### ISSUE TITLE
Linux container dockerfile

### ISSUE THREAD

**Issue by Gamecock** [dotnet/docs#36704]
There are some places in the document where linux instructions are given.  There is also one line in the dockerfile that needs to be changed.  

ENTRYPOINT ["./DotNet.Docker"]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows#create-the-dockerfile)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 230266](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230266)

**Comment by IEvangelist** [comment]
This is a fair callout. It's worth updating this doc to include both `ENTRYPOINT` options, and they're subtle differences. Thanks for posting this issue.
