### ISSUE TITLE
No mention that System.Text.Json, by default, will not deserialise a string to an enum value

### ISSUE THREAD

**Issue by marcoburato-ecutek** [dotnet/docs#36717]
The guide does not mention that Newtonsoft.Json allows deserialising a string to an enum value, but System.Text.Json does not (unless `JsonStringEnumConverter` is added to `JsonSerializerOptions.Converters`).

Example:

```csharp
var srcObj = new MyObj { Text = "Hello", Enum = MyEnum.Three };
var json1 = Newtonsoft.Json.JsonConvert.SerializeObject(srcObj);
var json2 = System.Text.Json.JsonSerializer.Serialize(srcObj);

Console.WriteLine("Newtonsoft.Json:  " + json1);
Console.WriteLine("System.Text.Json: " + json2);


const string srcJson = "{ \"Text\": \"Hello\", \"Enum\": \"Two\" }";
var obj1 = Newtonsoft.Json.JsonConvert.DeserializeObject<MyObj>(srcJson);
var obj2 = System.Text.Json.JsonSerializer.Deserialize<MyObj>(srcJson); //Throws JsonException


class MyObj
{
    public string Text { get; set; } = "";
    public MyEnum Enum { get; set; }
}

enum MyEnum
{
    One,
    Two,
    Three
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [Migrate from Newtonsoft.Json to System.Text.Json - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0#case-insensitive-deserialization)
* Content Source: [docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/migrate-from-newtonsoft.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 169357](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169357)

**Comment by gewarren** [comment]
Fixed by https://github.com/dotnet/docs/pull/37554.
