### ISSUE TITLE
[Breaking change]: System.DirectoryServices no longer references System.Security.Permissions

### ISSUE THREAD

**Issue by steveharter** [dotnet/docs#36724]
### Description

The `System.DirectoryServices` package no longer references the `System.Security.Permissions` package.

### Version

.NET 8 Preview 3

### Previous behavior

The `System.DirectoryServices` package referenced the `System.Security.Permissions` package.

### New behavior

The `System.DirectoryServices` package does not reference the `System.Security.Permissions` package.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [x] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

This avoids a dependency on `System.Drawing.Common` when `System.DirectoryServices` is referenced which is primarily an issue for non-Windows operating systems.

The dependency to `System.Drawing.Common` was caused by the following package dependencies:
System.DirectoryServices ->
System.Security.Permissions ->
System.Windows.Extensions ->
System.Drawing.Common.

### Recommended action

If the `System.DirectoryServices` package is referenced and a dependency is needed to `System.Security.Permissions` or any of its dependencies, which may include `System.Windows.Extensions` or `System.Drawing.Common` then ensure those packages are referenced directly or indirectly.

### Feature area

Other (please put exact area in description textbox)

**Comment by ericstj** [comment]
I marked this as "source incompatible" instead of "binary incompatible" because the problem will only be observed on a rebuild when referencing a new version of the package.  Existing binaries / builds will work.
