### ISSUE TITLE
PerformMonthEndTransactions method implementation for InterestEarningAccount class.

### ISSUE THREAD

**Issue by Jeraldheo** [dotnet/docs#36732]
Hello, thank you for all the help. Why is it that in the implementation of the method PerformMonthEndTransactions in the class InterestEarningAccount, we only apply interest when Balance >500m?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/oop)
* Content Source: [docs/csharp/fundamentals/tutorials/oop.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/oop.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Jeraldheo 

Throughout the sample, we made up the business rules. It's easy enough to change them and create different behavior. Go ahead and add your own ideas to your copy of the sample, and try to implement them.

I'll close this as an answered question
