### ISSUE TITLE
Typo in type typeparamref example

### ISSUE THREAD

**Issue by oldGlobula** [dotnet/docs#36737]
>/// &lt;param name=&quot;string&quot;&gt;query to execute&lt;/param&gt;
>    public List&lt;T&gt; FetchData&lt;T&gt;(string query)
Since the parameter name on the second line is `query`, not `string`, `name` attribute of `param` tag should be `query` too

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74e905-523c-dae9-f741-af5e52785a9c
* Version Independent ID: c9b7c7a1-0584-b6e6-95cd-5276788fdda0
* Content: [Documentation comments - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d52-resulting-xml)
* Content Source: [standard/documentation-comments.md](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing as fixed. (The fix published this morning, EDT).
