### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by Jithinrue** [dotnet/docs#36735]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af78d7ff-fc41-b781-6d86-608822a521b8
* Version Independent ID: aedd6ee0-5877-56fd-3f5d-fb66de46e316
* Content: [Equality operators - test if two objects are equal or not equal](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators)
* Content Source: [docs/csharp/language-reference/operators/equality-operators.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/equality-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Jithinrue 

I think this was opened in error. I'll close it.
