### ISSUE TITLE
InterestEarningAccount class requirements

### ISSUE THREAD

**Issue by Jeraldheo** [dotnet/docs#36731]
Hello, thank you so much for these tutorials they have helped me a lot. One of the requirements for the class InterestEarningAccount says that "An interest earning account: Will get a credit of 2% of the month-ending-balance.". But the implementation of the PerformMonthEndTransactions method gives a credit of 5%.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/oop)
* Content Source: [docs/csharp/fundamentals/tutorials/oop.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/oop.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BartoszKlonowski** [comment]
@BillWagner Let me handle that!
