### ISSUE TITLE
erroneous warning

### ISSUE THREAD

**Issue by AvatharBehemoth** [dotnet/docs#36743]
i made a global float. 
i assign it a value in a loop (update) in unity. i use an if condition in the loop to check (if a month has passed) it needs to be modified. 
I print (TextMeshProUGUI) the value of the float after the loop, since i want a value to appear regardless of whether its modified. 
Then i get a "warning CS0219 The variable 'currencyvalue' is assigned but its value is never used	
"
Again: it is used, just not in the loop (with the if condition) but in the following part of Update.
but this just means your compiler doesnt understand basic programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34fc8443-8e5e-2e87-6ee5-fbab61709e1e
* Version Independent ID: 41a54122-d4f3-c233-7e67-6ee521af4338
* Content: [Compiler Warning (level 3) CS0219](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0219?f1url=%3FappId%3Droslyn%26k%3Dk(CS0219))
* Content Source: [docs/csharp/misc/cs0219.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0219.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @AvatharBehemoth 

If you do think you've found a compiler bug, you can open an issue in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repository. You'll need to include the code sample that reproduces the error.

I'll close this, as it's not a docs issue.
