### ISSUE TITLE
Question: Why is CA1830 a performance improvement?

### ISSUE THREAD

**Issue by Houtamelo** [dotnet/docs#36765]
I assume the performance is different because on the documentation page of CA1830 we have the following section:

![image](https://github.com/dotnet/docs/assets/88971943/d1ae51b7-9ab3-4607-908e-29116bac1226)

Here's the example provided on that page:

```
using System.Text;

class C
{
    int _value;

    // Violation
    public void Log(StringBuilder destination)
    {
        destination.Append("Value: ").Append(_value.ToString()).AppendLine();
    }

    // Fixed
    public void Log(StringBuilder destination)
    {
        destination.Append("Value: ").Append(_value).AppendLine();
    }
}
```

All it does is removing the `int.ToString()` call, which results on calling `StringBuilder.Append(int)` instead of `StringBuilder.Append(string)`.

I decided to look at the source code of the int overload, found it on: https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs

Here's the overload:

```
public StringBuilder Append(int value)
 {
    Contract.Ensures(Contract.Result<StringBuilder>() != null);
    return Append(value.ToString(CultureInfo.CurrentCulture));
}
```

In the end all the overload does is call `int.ToString()`, which, from my understanding should have the same performance (and memory allocation) as directly calling `StringBuilder.Append(string)`.

I understand that removing the unnecessary `int.ToString()` call improves code readability.

My question is: Why is CA1830 a performance improvement? What am I missing?

Thanks for taking the time to read this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc8dc48e-ccad-d742-c1db-24bcfcb0308d
* Version Independent ID: 47237158-ad75-f8bc-55a7-b3ed5b0715b9
* Content: [CA1830: Prefer strongly-typed Append and Insert method overloads on StringBuilder (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1830)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1830.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1830.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @stephentoub
* Microsoft Alias: **stoub**

**Comment by stephentoub** [comment]
You linked to the .NET Framework implementation. The .NET Core implementation is here:
https://github.com/dotnet/runtime/blob/a429b0ca4fbb2ed7014815792f1cf1b5939eb567/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1036
It formats directly into the builder's buffer as long as it's big enough.

**Comment by Houtamelo** [comment]
> You linked to the .NET Framework implementation. The .NET Core implementation is here: https://github.com/dotnet/runtime/blob/a429b0ca4fbb2ed7014815792f1cf1b5939eb567/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1036 It formats directly into the builder's buffer as long as the buffer is big enough.

I see, thank you very much!
