### ISSUE TITLE
gwerg3w4rg

### ISSUE THREAD

**Issue by asdwffgtg** [dotnet/docs#36773]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcc1ba33-60dd-1e44-2498-eb76f0d964c1
* Version Independent ID: a1404161-c48b-564b-03ea-d4340fe28c53
* Content: [Compiler Error CS5001](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs5001?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CS5001)%26rd%3Dtrue)
* Content Source: [docs/csharp/misc/cs5001.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs5001.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing as spam
