### ISSUE TITLE
Fix xref links that were commented out during migration

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3682]
During migration from MSDN to docs.microsoft.com, some of the content had their xref link commented out and changed with text inside inline code.

We should remove those from the docs:
https://github.com/dotnet/docs/search?q=%21--zz&type=Code

Search currently shows 88 files with that issue. In some cases though, we won't be able to fix the issue until the API is onboarded to docs. e.g. System.IO.WindowsRuntimeStreamExtensions is a UWP API that is not on docs yet. 

For people interested in helping with this task, we'd break it down into smaller tasks (like 5-10 links per PR).

**Comment by RutgerM** [comment]
I'll help!

**Comment by BillWagner** [comment]
closing as done based on above referenced PRs

**Comment by mairaw** [comment]
There are still 23 results from my query above. I’ll try to wrap this up this quarter.
