### ISSUE TITLE
Property name?

### ISSUE THREAD

**Issue by fjallemark** [dotnet/docs#36840]
[Enter feedback here]
It would be nice if this error told me WHICH property or method that fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60c946d7-649b-44e4-49a9-543565904d18
* Version Independent ID: df4263c1-477a-3c32-9abe-3fcb850e6c1b
* Content: [Compiler Error CS1061](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1061.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @fjallemark 

The specific message does include the class name and the property name. I suggest posting a small sample on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site if you need help.

I'll close this as it's not a docs issue.
