### ISSUE TITLE
Order Object in the PubSub defaults to an empty object

### ISSUE THREAD

**Issue by mtrmmsoftware** [dotnet/docs#36842]
The page states you have to use the following code snippet: 
```
[Topic("pubsub", "newOrder")]
[HttpPost("/orders")]
public async Task<ActionResult> CreateOrder(Order order)
```
I have run this example and the object that is being received is always empty (all the properties at the default value).

If I use a middleware and try to seserialize the Request Body stream I get all the Properties filled with the expected values
kind of similar to the code in the repository: 
https://github.com/Azure-Samples/pubsub-dapr-csharp-servicebus
(Unfortunately I could not push my changes in the github because of authentication problems)

I find this way in the controller more elegant, is this an issue with Dapr or ASP.Net?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d1c385-3546-7612-b8b1-4231681dca8a
* Version Independent ID: 497a2367-15d7-6be0-7974-1415e3402b08
* Content: [The Dapr publish & subscribe building block](https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/publish-subscribe)
* Content Source: [docs/architecture/dapr-for-net-developers/publish-subscribe.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/publish-subscribe.md)
* Product: **dotnet-architecture**
* GitHub Login: @EdwinVW
* Microsoft Alias: **jamont**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
