### ISSUE TITLE
There is more than one option for: Pin: origin "<your-package-source>"

### ISSUE THREAD

**Issue by Lroca88** [dotnet/docs#36846]
[Enter feedback here]

I would need an example with multiple options as origin since the proposed command returns more than one origin:

![image](https://github.com/dotnet/docs/assets/5395468/11b3041a-0822-49f3-a167-475b56c90eda)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1287004d-fed0-7cf8-e9ac-c4529bd7e010
* Version Independent ID: 73ed52b3-4e26-9840-ae78-14983c6a07c5
* Content: [Troubleshoot .NET package mix ups on Linux - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#i-need-a-version-of-net-that-isnt-provided-by-my-linux-distribution)
* Content Source: [docs/core/install/linux-package-mixup.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-package-mixup.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**
* GitHub Login: @omajid
* Microsoft Alias: **dotnetcontent**

---
[Associated WorkItem - 181172](https://dev.azure.com/msft-skilling/Content/_workitems/edit/181172)

**Comment by gewarren** [comment]
FYI @adegeo

**Comment by omajid** [comment]
cc @mirespace

**Comment by mirespace** [comment]
Hi all,

I would add `grep updates` to the command, in the following way:

```
apt-cache policy '~ndotnet.*' | grep -v microsoft | grep '/ubuntu' | grep updates | cut -d"/" -f3 | sort -u
```

that should be ok, except when the package is released for the first time or a new Ubuntu series is launched (i.e., next 23.10 Mantic Minotaur):

```
root@Mrunning-lintian:~# apt-cache policy dotnet6
dotnet6:
  Installed: (none)
  Candidate: 6.0.121-0ubuntu1
  Version table:
     6.0.121-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu mantic/universe amd64 Packages
```
  in this case, the command you already have would work (and the one with `grep updates` will fail).

**Comment by Lroca88** [comment]
Great this works for me:
![image](https://github.com/dotnet/docs/assets/5395468/8014c67e-eff0-4bdd-b6a4-6c2b648cf0bb)
