### ISSUE TITLE
Multiple RID in csproj not accepted on Linux by MSBuild

### ISSUE THREAD

**Issue by vini-nu** [dotnet/docs#36853]
`<RuntimeIdentifier>linux-x64;win-x64;osx-x64</RuntimeIdentifier>`

[MSB4115] The "HasTrailingSlash" function only accepts a scalar value, but its argument "$(OutputPath)" evaluates to "bin\Debug/net8.0/linux-x64;win-x64;osx-x64/" which is not a scalar value. /run/host/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Microsoft.Common.CurrentVersion.targets at (156:17)

![image](https://github.com/dotnet/docs/assets/6695244/0cf1bd60-db77-414b-9e4f-0d5b062d5f4a)

Meanwhile documentation says: `Multiple RIDs can be defined as a semicolon-delimited list in the project file's [<RuntimeIdentifiers>](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifiers) element.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Runtime Identifier (RID) catalog](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/main/docs/core/rid-catalog.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@vini-nu You need to change the property name to `RuntimeIdentifiers` for multiple TFMs (note the "s" on the end).
