### ISSUE TITLE
provide guidance on updating C# language version

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3685]
There are multiple ways to update the language version for a project:

1. Project Properties page in the IDE
1. Use a language feature for a version higher than currently specified, and select the Code Fix.
1. Edit the CS Proj (probably limited to Core on non-Windows platforms)

Then, we can link to this new topic from all the locations that need it.  That list is growing, but it is currently the articles linked from the "What's new" pages for C# 7.1 and 7.2.

See [this comment](https://github.com/dotnet/docs/pull/3667#discussion_r150967450) for background

**Comment by BillWagner** [comment]
@ghogen Is this already covered in the Visual Studio doc set? (I looked and didn't see it)

**Comment by mairaw** [comment]
Maybe @gewarren can help with your question, @BillWagner

**Comment by BillWagner** [comment]
We have this documented [in the compiler options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option) section.

This can be closed.
