### ISSUE TITLE
Article does not describe how to deliberately accept a breaking change

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docs#36859]
While the article describes how to circumvent a breaking change it does not talk about how to deliberately accept a breaking change. When I work von V2 of the package I decide to make breaking changes. How do I pack the nuget package without errors once I made the required breaking changes. With `Microsoft.CodeAnalysis.PublicApiAnalyzers` I would have added the API to `PublicAPI.Unshipped.txt` how do I do the same thing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed723ea8-3645-7a48-3b30-858a6cbe976d
* Version Independent ID: c8d7765b-7332-b8e2-673d-77a32156294a
* Content: [Baseline Package Validator - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator)
* Content Source: [docs/fundamentals/package-validation/baseline-version-validator.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/package-validation/baseline-version-validator.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@ericstj Who can help with this question?

**Comment by bitbonk** [comment]
I did some more digging an I am _assuming_ the way to do this is to suppress particular errors using a _CompatibitySupression.xml_ file as explained [here](https://learn.microsoft.com/dotnet/fundamentals/package-validation/overview#suppress-compatibility-errors).

Once you have released v2, you delete that file and everything starts over again.

I still think it would be good if this article goes through the full cycle that includes releasing a next version that will include deliberate breaking changes.

**Comment by ericstj** [comment]
@bitbonk is correct - you can use suppression files.   @ViktorHofer should we update our docs to make the lifecylce of suppressions more clear?

**Comment by ViktorHofer** [comment]
Yes we should. Adding a lifecycle section makes sense.

**Comment by bitbonk** [comment]
@ViktorHofer I tried my best, see #36954.
