### ISSUE TITLE
Is there a editorconfig for prefer primary constructor

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docs#36855]
When we prefer using the file-scoped namespace, we could use `csharp_style_namespace_declarations=file_scoped`, then is there a config for the primary constructor?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1194e6-3116-6e70-9a36-f0a509c04f63
* Version Independent ID: a22d366b-380f-f701-6a01-2515433e1550
* Content: [Declare and use primary constructors in classes and structs](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors)
* Content Source: [docs/csharp/whats-new/tutorials/primary-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/primary-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @CyrusNajmabadi who might know the answer.

**Comment by CyrusNajmabadi** [comment]
Yes. Use: csharp_style_prefer_primary_constructors

**Comment by WeihanLi** [comment]
@CyrusNajmabadi , thanks very much, it helps
![image](https://github.com/dotnet/docs/assets/7604648/292033b1-80bf-4655-b6df-ec587b459542)
