### ISSUE TITLE
Assets\Scripts\TileGrid.cs(25,47): error CS1002: ; expected

### ISSUE THREAD

**Issue by Owez01** [dotnet/docs#36865]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f114ca64-2134-9aea-ad5f-db480ff4e521
* Version Independent ID: b3b390b3-fdcc-afef-2b17-550c59804854
* Content: [Compiler Error CS1002](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1002)
* Content Source: [docs/csharp/misc/cs1002.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1002.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @Owez01 

It looks like this was opened as a note for your use, not a docs issue.

I'll close this.
