### ISSUE TITLE
Tuple documentation mentions deconstructing declaration but not deconstructing assignment

### ISSUE THREAD

**Issue by vladd** [dotnet/docs#3690]
In both articles about tuples and tuple deconstruction at docs.microsoft.com (https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct, https://docs.microsoft.com/en-us/dotnet/csharp/tuples) all the examples about tuple deconstruction are indeed deconstruction declarations, there is no single example on deconstruction assignment. There is actually no mention that deconstruction is possible into existing variables, so the new users don't expect it to be possible.

I would also suggest including the canonical example from other languages with tuples: swap one-liner

    (a, b) = (b, a);

**Comment by BillWagner** [comment]
This is a great suggestion. The updates should also mention it's great for constructors in record-like types:

```csharp
public class Person
{
    public string LastName  { get; }
    public string FirstName { get; }

    public Person(string first, string last) => (FirstName, LastName) = (first, last);
}
```
