### ISSUE TITLE
cleaning up your mess.

### ISSUE THREAD

**Issue by AvatharBehemoth** [dotnet/docs#36929]
GameObject does not contain a definition for GetChild ...... 
Yeah it does. Sooo another unity "problem" which seems to be a C# "problem. a "problem" is a system level design or implementation bug. 

and no im not going to jump through hoops because youre the wrong department. Why cant you send this stuff through to the right department? Im already having to clean up someone elses mess. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60c946d7-649b-44e4-49a9-543565904d18
* Version Independent ID: df4263c1-477a-3c32-9abe-3fcb850e6c1b
* Content: [Compiler Error CS1061](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1061.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Based on [this page](https://docs.unity3d.com/ScriptReference/GameObject.html) The `GameObject` type doesn't have a `GetChild` method. That's why you're seeing this error.

Closing as not a docs issue.
