### ISSUE TITLE
Extend config extensions doc with binding source generator info 

### ISSUE THREAD

**Issue by layomia** [dotnet/docs#36939]
- https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-6/#configuration-binding-source-generator-improvements
- https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration
- https://github.com/dotnet/docs/blob/b8f805b78dc90ca6339d18d0d404a3fff9c01453/docs/core/extensions/configuration.md
- ASP.NET https://github.com/dotnet/AspNetCore.Docs/issues/30215

---
[Associated WorkItem - 317207](https://dev.azure.com/msft-skilling/Content/_workitems/edit/317207)

**Comment by layomia** [comment]
@jkotas in https://github.com/dotnet/runtime/issues/79527#issuecomment-1706986512.

Also, we should have this source generator documented at https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration. Once the documentation is available, please update [this link](https://github.com/dotnet/docs/pull/36769/files#diff-52a827bf00d533c0782b508c3d107a393c70e30d5d98ee891d2f70ad2e7892e5R35) to point to it.

**Comment by ericstj** [comment]
@IEvangelist @gewarren is it possible to prioritize this for .NET 9?  Seems we still don't have good conceptual docs for the Configuration source generator.

**Comment by IEvangelist** [comment]
Yes, I'll commit to making that happen for .NET 9 for sure. I've been buried with .NET Aspire docs work lately, and haven't had lots of time to work on .NET docs for a while now.
