### ISSUE TITLE
No SDKs were found.

### ISSUE THREAD

**Issue by AK51** [dotnet/docs#36955]
I have tried several times in my Ubuntu 22.04, still can not get the SDK. >_<

dotnet --info

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac16736-f225-12d0-2de2-efded54a505a
* Version Independent ID: 909b29bd-2729-3b59-beb5-20a7281344d0
* Content: [Install .NET on Ubuntu 22.04 - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204)
* Content Source: [docs/core/install/linux-ubuntu-2204.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2204.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by AK51** [comment]
That is what I did. Still cannot find the SDK.....
Thx
 
sudo apt-get install -y dotnet-sdk-7.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dotnet-sdk-7.0 is already the newest version (7.0.400-1).
The following packages were automatically installed and are no longer required:
  cuda-12-1 cuda-cccl-12-1 cuda-command-line-tools-12-1 cuda-compiler-12-1
  cuda-cudart-12-1 cuda-cudart-dev-12-1 cuda-cuobjdump-12-1 cuda-cupti-12-1
  cuda-cupti-dev-12-1 cuda-cuxxfilt-12-1 cuda-demo-suite-12-1
  cuda-documentation-12-1 cuda-driver-dev-12-1 cuda-gdb-12-1
  cuda-libraries-12-1 cuda-libraries-dev-12-1 cuda-nsight-12-1
  cuda-nsight-compute-12-1 cuda-nsight-systems-12-1 cuda-nvcc-12-1
  cuda-nvdisasm-12-1 cuda-nvml-dev-12-1 cuda-nvprof-12-1 cuda-nvprune-12-1
  cuda-nvrtc-12-1 cuda-nvrtc-dev-12-1 cuda-nvtx-12-1 cuda-nvvp-12-1
  cuda-opencl-12-1 cuda-opencl-dev-12-1 cuda-profiler-api-12-1
  cuda-runtime-12-1 cuda-sanitizer-12-1 cuda-toolkit-12-1
  cuda-toolkit-12-1-config-common cuda-tools-12-1 cuda-visual-tools-12-1
  gds-tools-12-1 gir1.2-rb-3.0 libcublas-12-1 libcublas-dev-12-1 libcufft-12-1
  libcufft-dev-12-1 libcufile-12-1 libcufile-dev-12-1 libcurand-12-1
  libcurand-dev-12-1 libcusolver-12-1 libcusolver-dev-12-1 libcusparse-12-1
  libcusparse-dev-12-1 libdmapsharing-3.0-2 libfuse2 liblirc-client0
  libnpp-12-1 libnpp-dev-12-1 libnvidia-common-530 libnvjitlink-12-1
  libnvjitlink-dev-12-1 libnvjpeg-12-1 libnvjpeg-dev-12-1 libnvvm-samples-12-1
  libsgutils2-2 linux-image-5.19.0-50-generic linux-modules-5.19.0-50-generic
  linux-modules-extra-5.19.0-50-generic nsight-compute-2023.1.1
  nsight-compute-2023.2.0 nsight-compute-2023.2.1 nsight-systems-2023.1.2
  python3-mako python3-markupsafe
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by AK51** [comment]
That is what I did. Still cannot find the SDK.....
Thx
 
sudo apt-get install -y dotnet-sdk-7.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dotnet-sdk-7.0 is already the newest version (7.0.400-1).
The following packages were automatically installed and are no longer required:
  cuda-12-1 cuda-cccl-12-1 cuda-command-line-tools-12-1 cuda-compiler-12-1
  cuda-cudart-12-1 cuda-cudart-dev-12-1 cuda-cuobjdump-12-1 cuda-cupti-12-1
  cuda-cupti-dev-12-1 cuda-cuxxfilt-12-1 cuda-demo-suite-12-1
  cuda-documentation-12-1 cuda-driver-dev-12-1 cuda-gdb-12-1
  cuda-libraries-12-1 cuda-libraries-dev-12-1 cuda-nsight-12-1
  cuda-nsight-compute-12-1 cuda-nsight-systems-12-1 cuda-nvcc-12-1
  cuda-nvdisasm-12-1 cuda-nvml-dev-12-1 cuda-nvprof-12-1 cuda-nvprune-12-1
  cuda-nvrtc-12-1 cuda-nvrtc-dev-12-1 cuda-nvtx-12-1 cuda-nvvp-12-1
  cuda-opencl-12-1 cuda-opencl-dev-12-1 cuda-profiler-api-12-1
  cuda-runtime-12-1 cuda-sanitizer-12-1 cuda-toolkit-12-1
  cuda-toolkit-12-1-config-common cuda-tools-12-1 cuda-visual-tools-12-1
  gds-tools-12-1 gir1.2-rb-3.0 libcublas-12-1 libcublas-dev-12-1 libcufft-12-1
  libcufft-dev-12-1 libcufile-12-1 libcufile-dev-12-1 libcurand-12-1
  libcurand-dev-12-1 libcusolver-12-1 libcusolver-dev-12-1 libcusparse-12-1
  libcusparse-dev-12-1 libdmapsharing-3.0-2 libfuse2 liblirc-client0
  libnpp-12-1 libnpp-dev-12-1 libnvidia-common-530 libnvjitlink-12-1
  libnvjitlink-dev-12-1 libnvjpeg-12-1 libnvjpeg-dev-12-1 libnvvm-samples-12-1
  libsgutils2-2 linux-image-5.19.0-50-generic linux-modules-5.19.0-50-generic
  linux-modules-extra-5.19.0-50-generic nsight-compute-2023.1.1
  nsight-compute-2023.2.0 nsight-compute-2023.2.1 nsight-systems-2023.1.2
  python3-mako python3-markupsafe
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

sudo apt install zlib1g

**Comment by AK51** [comment]
solved by following this link. Took me the whole night.... >_<
https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#solutions

**Comment by adegeo** [comment]
Hi @AK51 sorry that you had problems. Do you have an idea of how you got into this state? And how did you find the solution? What kind of search terms did you use that didn't lead you to the correct solution? What search terms found the solution?

Understanding the whole cycle of this problem may help me improve the documentation.
