### ISSUE TITLE
[Single-file deployment] How to exclude a dll file of a nuget package 

### ISSUE THREAD

**Issue by xiaoxstz** [dotnet/docs#36956]
**Issue description**

I want to publish my WPF application project to a single file. I have realized it.

However, my WPF is based on the MVVM Framework `Prism`, and I found ` Prism.DryIoc.Wpf.dll` , `Prism.dll` , and  `Prism.Wpf.dll` can not be embedded into the single file when I used the nuget package `Costura.Fody` for the single file packing, otherwise, the software cannot run and no exception can be caught.

The files are imported to the project by the Nuget package "Prism.DryIoc"

```XML
<PackageReference Include="Prism.DryIoc" Version="8.1.97" />
```

**How can I exclude ` Prism.dll` in the package "Prism.DryIoc"?**

According to [Single-file deployment](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file), I can use the configuration below to do it.

  ```XML
    <Reference Include="Prism">
      <HintPath>$(USERPROFILE)\.nuget\packages\prism.core\8.1.97\lib\net5.0\Prism.dll</HintPath>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Reference>
  ```

**But, it's not a comfortable way, because when the "Prism.DryIoc" updates or we change the .NET version, we need to change the configuration manually.** How to realize it in a better way? Just similar to the NuGet package `Costura.Fody` (exclude or include files by an XML file)?

**Target framework**

- [√] .NET Core： `.NET 7`
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by xiaoxstz** [comment]
I solved it with `Costura.Fody` 's solution.

You can put them into `ExcludeAssemblies` in the `FodyWeavers.xml` file

```xml
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
    <ExcludeAssemblies>
      Prism
      Prism.DryIoc.Wpf
      Prism.Wpf
    </ExcludeAssemblies>
    <IncludeRuntimeAssemblies/>
    <Unmanaged64Assemblies/>
  </Costura>
</Weavers>
```

**Comment by ahdung** [comment]
@xiaoxstz  It is still need a solution from offical, please reopen it.

**Comment by ahdung** [comment]
@xiaoxstz seems `Costura.Fody` can't hide `.deps.json` `.runtimeconfig.json` right?
