### ISSUE TITLE
Efficient scheduling clarification

### ISSUE THREAD

**Issue by jkonecki** [dotnet/docs#36963]
The section "Efficient Scheduling" contains the following claim:

_The runtime schedules execution of a large number of single-threaded grains across a custom thread pool with a thread per physical processor core._ 

I believe the above should say **logical** processor core, instead of physical, to take into account hyperthreading. Please clarify with Orleans team and update the docs if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03c92a61-dca1-a507-e434-4d2c95f468bd
* Version Independent ID: 228b228c-f72e-0dec-4345-ee8682bf50e1
* Content: [Orleans benefits - .NET](https://learn.microsoft.com/en-us/dotnet/orleans/benefits)
* Content Source: [docs/orleans/benefits.md](https://github.com/dotnet/docs/blob/main/docs/orleans/benefits.md)
* Product: **dotnet-orleans**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 156754](https://dev.azure.com/msft-skilling/Content/_workitems/edit/156754)

**Comment by ReubenBond** [comment]
We should change it, yep. It uses the .NET Thread Pool now, not a custom thread pool. Perhaps something like:

> The runtime schedules execution of a large number of single-threaded grains using the .NET Thread Pool, which is highly tuned for performance
