### ISSUE TITLE
C#12 spread operator for C#12 ValueTuple aliases?

### ISSUE THREAD

**Issue by tymoor** [dotnet/docs#36989]
Is there a way to implement the spread operator for the C#12 ValueTuple using statements?

```
using baseTuple = (T1, T2, T3)
using extendedTuple = (..baseTuple, T4, T5)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 12 - C# Guide - C#](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12)
* Content Source: [docs/csharp/whats-new/csharp-12.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-12.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @tymoor 

You can't use the spread operator to expand all members of a tuple. Collection expressions (including the spread operator) are designed to work seamlessly with collection types. In those scenarios, the elements of the collection are all the same type. That's not generally the case with tuples. 

I'll close as not a docs issue.
