### ISSUE TITLE
HUGGGG

### ISSUE THREAD

**Issue by shalinirajput2211** [dotnet/docs#37012]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87bbd41f-9bad-bb7b-f0c9-68af6b8f4e81
* Version Independent ID: a78ad137-41d1-c0c6-f410-f427e2256e97
* Content: [Indexers - C# Programming Guide - C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/)
* Content Source: [docs/csharp/programming-guide/indexers/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/indexers/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
closing.
