### ISSUE TITLE
ILoggingBuilder.AddConsole 's FormatterOptions.IncludeScopes false does not work

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#37026]
---
**Issue moved from MicrosoftDocs/feedback#3951**
- Please respond to @SudipShresthaCiena.

---

_From @SudipShresthaCiena on Friday, August 18, 2023 8:12:51 PM_

**To Reproduce**
1. In a .net core 7.0 Console App, I added console logging.
2. appsettings.json file
`
{
"Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "Console": {
      "LogLevel": {
        "Default": "Information"
      },
      "FormatterName": "consoleLogFormatter",
      "FormatterOptions": {
               "SingleLine": true,
                "IncludeScopes": false,
                "TimestampFormat": "HH:mm:ss ",
                "UseUtcTimestamp": true
      }
    }
}
`
3. Program.cs
`
using var loggerFactory = LoggerFactory.Create(loggingBuilder =>
{
    loggingBuilder.AddConfiguration(Configuration.GetSection("Logging"));
    loggingBuilder.AddConsole();
    
}
`
4. In the console, this is what I see:
`20:08:29 info: AppName.Class1Name[0] Some Message Here 1
20:08:33 info: AppName.Class2Name[0] Some Message Here 2
20:08:33 info: Program[0] Some Message Here 3

**Expected behavior**
I was expecting not to see "AppName.Class1Name[0]" etc.
I know the section is being read because UseUtcTimestamp, TimestampFormat, and SingleLine are working.

**Desktop:**
 - OS: Windows 10
 - Browser NA

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3951**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Friday, August 18, 2023 8:12:53 PM_

Thank you for opening an issue! One of our team members will get back to you with additional information.
  
If this is a product issue, please close this issue and contact the product's support instead. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

**Comment by gewarren** [comment]
@IEvangelist Can you take a look? Perhaps this needs to go to dotnet/runtime instead.

**Comment by IEvangelist** [comment]
Thank you @gewarren! Hi @SudipShresthaCiena, I see your code and understand what you're asking but that's not how scopes work. See: https://learn.microsoft.com/dotnet/core/extensions/logging?tabs=command-line#log-scopes

Does that make more sense after reading through that?

**Comment by gewarren** [comment]
I'm going to close this issue as resolved. Feel free to comment/reopen as necessary.
