### ISSUE TITLE
Example of implementing a custom logging provider doesn't match .NET 7

### ISSUE THREAD

**Issue by SetTrend** [dotnet/docs#37046]
Trying to reproduce the example from the page, I noticed that the following code snippet doesn't apply to .NET 7:

```c#
public static ILoggingBuilder AddColorConsoleLogger(this ILoggingBuilder builder)
  {
    builder.AddConfiguration();

    builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<ILoggerProvider, ColorConsoleLoggerProvider>());

    LoggerProviderOptions.RegisterProviderOptions<ColorConsoleLoggerConfiguration, ColorConsoleLoggerProvider>builder.Services);

    return builder;
  }
```

### Reasoning

1. There is no extension method adorning the `ILoggingBuilder` interface with a parameterless `AddConfiguration()` member:
   ![AddConfiguration](https://github.com/dotnet/docs/assets/9283914/0c155207-ee83-4407-bd17-ae473b453d84)
3. `builder.Services` doesn't provide a `TryAddEnumerable` method.
4. Where does `LoggerProviderOptions` all of a sudden come from?

In addition to these issues, the page is missing an explanation on how to retrieve the configured logging level when it may be defined in `Default` or the custom logger's dedicated configuration section (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/#configure-logging)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b609eb80-71e8-7a3c-4c4c-60cf9a315cfb
* Version Independent ID: e111baf5-04b7-c497-ce86-eb687e121751
* Content: [Implement a custom logging provider - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider)
* Content Source: [docs/core/extensions/custom-logging-provider.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/custom-logging-provider.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 169717](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169717)

**Comment by IEvangelist** [comment]
Hi there @SetTrend - The source code for this doc (and specifically the code in question) is located here:

https://github.com/dotnet/docs/blob/main/docs/core/extensions/snippets/configuration/console-custom-logging/Extensions/ColorConsoleLoggerExtensions.cs

This project is built using .NET 7, and the [`LoggerProviderOptions`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.configuration.loggerprovideroptions?view=dotnet-plat-ext-7.0) comes from the `Microsoft.Extensions.Logging.Configuration` namespace.

This is all detailed in the article, did you follow it fully or just parts of it? What specifically should be updated for the article? I'm happy to update it based on your feedback, just want to make sure I capture the correct updates.

**Comment by IEvangelist** [comment]
Closing this issue as the sample source code is built using .NET 7.
