### ISSUE TITLE
What is VSTO

### ISSUE THREAD

**Issue by NikoAri** [dotnet/docs#37050]
This page references VSTO, but what does VSTO stand for?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00a8d09f-b5fb-c16e-4034-34dfe29193dd
* Version Independent ID: 32751867-d8c6-04d2-ec62-909cbeb1bbf6
* Content: [Walkthrough: Office Programming - C#](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/interop/walkthrough-office-programming)
* Content Source: [docs/csharp/advanced-topics/interop/walkthrough-office-programming.md](https://github.com/dotnet/docs/blob/main/docs/csharp/advanced-topics/interop/walkthrough-office-programming.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good point @NikoAri 

VSTO is an abbreviation for "Visual Studio Tools for Office". 

I've added this to our backlog, and I've added the "help wanted" label in case anyone wants to submit a PR before we get to it.

**Comment by BartoszKlonowski** [comment]
I'll handle that!
