### ISSUE TITLE
"Async lambdas" sub-topic

### ISSUE THREAD

**Issue by josephedwardchang** [dotnet/docs#37100]
In Async lambdas sub-topic, there is async keywords in the examples there but there are no lambdas. The example there should be like:

```
async (n) => { await CallFunction(n); } 
```

or

```
// return a Task!
var wrapper = new Func<Task>(async () =>
{
    await SomethingAsync();
});
await wrapper.Invoke();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6b8daf7-c244-5d1c-e43b-7fe654f378e1
* Version Independent ID: 5142bc3b-2d71-b98e-190a-aa51f28f46e4
* Content: [Lambda expressions - Lambda expressions and anonymous functions - C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions)
* Content Source: [docs/csharp/language-reference/operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @josephedwardchang 

I'm going to close this because the second example in that section shows an `async` lambda. It's the statement lambda assigned to `button1.Click`:

```csharp
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        button1.Click += async (sender, e) =>
        {
            await ExampleMethodAsync();
            textBox1.Text += "\r\nControl returned to Click event handler.\n";
        };
    }

    private async Task ExampleMethodAsync()
    {
        // The following line simulates a task-returning asynchronous process.
        await Task.Delay(1000);
    }
}
```
