### ISSUE TITLE
The `Initialize Property` example initializes fields instead of properties. 

### ISSUE THREAD

**Issue by pkanavos** [dotnet/docs#37114]
The first paragraph in the `Initialize Property` section claims that the following snippet initializes properties, when it only declares and initializes fields.

> The following code initializes two readonly properties that are computed from primary constructor parameters:
```
public readonly struct Distance(double dx, double dy)
{
    public readonly double Magnitude = Math.Sqrt(dx * dx + dy * dy);
    public readonly double Direction = Math.Atan2(dy, dx);
}
```
 Both [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQGYACAJwFMIEB7GAGwE8SBnAFzIFcBjNkgESjsIMbhQAUtTsHoUSCAB5x5NabPmMAlAQDeBEgZLFyVWg2ZSZcgLIQA5jChtOCOQF4SttgAsAdAGUARzI2SQUSACp5cOQNSI1NAG59Q2NKajomFTU5QUpeKDoSDy8/AEE2EUxJRmVFJIIAXwIgA==) and the following snippet run with the .NET 8.0 RC1 SDK verify there are no properties  : 

```
public readonly struct Distance(double dx, double dy)
{
    public readonly double Magnitude = Math.Sqrt(dx * dx + dy * dy);
    public readonly double Direction = Math.Atan2(dy, dx);
}
var props = typeof(Distance).GetProperties();
Debug.Assert(props.Length == 0);
```

To actually create and initialize properties, `{get;}` should be used :

```
public readonly struct Distance(double dx, double dy)
{
    public double Magnitude { get; } = Math.Sqrt(dx * dx + dy * dy);
    public double Direction { get; }  = Math.Atan2(dy, dx);
};


var props = typeof(Distance).GetProperties();
Debug.Assert(props.Length > 0);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1194e6-3116-6e70-9a36-f0a509c04f63
* Version Independent ID: a22d366b-380f-f701-6a01-2515433e1550
* Content: [Declare and use primary constructors in classes and structs - C#](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors#create-mutable-state)
* Content Source: [docs/csharp/whats-new/tutorials/primary-constructors.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/primary-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @pkanavos 

There's a difference between your example and the code in the article.

Your example:

```csharp
public readonly struct Distance(double dx, double dy)
{
    public double Magnitude = Math.Sqrt(dx * dx + dy * dy);
    public double Direction = Math.Atan2(dy, dx);
}
```

The article:

```csharp
public readonly struct Distance(double dx, double dy)
{
    public double Magnitude => Math.Sqrt(dx * dx + dy * dy);
    public double Direction => Math.Atan2(dy, dx);
}
```

Note that the article using `=>` instead of `=`. 

The code in the article does use the primary constructor parameters to compute the property.

I'll close this as not an issue.
