### ISSUE TITLE
Missing header file locations for .NET Hosting in C++

### ISSUE THREAD

**Issue by Lunar2kPS** [dotnet/docs#37143]
I was following the [MSDN page on .NET Hosting](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting), and they linked to this [sample C++ app](https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp) to demonstrate hosting a .NET (C#) program from a native app (C++).

I noticed these three includes:
```cpp
#include <nethost.h>
#include <coreclr_delegates.h>
#include <hostfxr.h>
```

I found them available at the following 3 links:
- https://github.com/dotnet/runtime/blob/main/src/native/corehost/nethost/nethost.h
- https://github.com/dotnet/runtime/blob/main/src/native/corehost/coreclr_delegates.h
- https://github.com/dotnet/runtime/blob/main/src/native/corehost/hostfxr.h

Perhaps this can be included in the docs page, cause otherwise, I wouldn't be able to do anything with .NET hosting!
Thanks for your help :) I'm looking forward to scripting C# over my C++ codebase for the first time in a cross-platform app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Write a custom .NET runtime host - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mjrousos
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for the suggestion. I'm adding the file locations to the article.

**Comment by Lunar2kPS** [comment]
Awesome, thanks so much!

Also not sure if this is a silly question, but I wanna clarify, from those 3 GitHub links above (from the dotnet/runtime GitHub repo), do all of those work on any platform?

---

For more context with an example,

I'm writing a small (but cross-platform) 2D game engine with C++, OpenGL (GLFW + GLAD), and embedding C# scripting over it. I currently test/support:
- Windows 64bit
- MacOS Intel 64bit
- MacOS Arm (M1/M2) 64bit
- Linux Intel 64bit
- Raspberry Pi (Debian-based Linux, Arm) 64bit

I had to install .NET (tested with .NET 7) on each platform and copied the following 5 files from each installation on each platform into my C++ project:
- coreclr_delegates.h\*
- hostfxr.h\*
- nethost.h\*
- nethost.dll _(Windows)_ / libnethost.a _(MacOS & Linux)_
- nethost.lib _(Windows)_ / libnethost.dylib _(MacOS)_ / libnethost.so _(Linux)_

\* I tested these and they showed up as the exact same .h header files regardless of platform (makes sense I think, but just wanna make sure what's intended, since .NET hosting seems to have somewhat limited MSDN docs coverage!)

I [documented this workflow precisely here](https://github.com/Lunar2kPS/advanced-cpp/blob/main/libraries/nethosting/source.md), and am wondering if that's the intended workflow to get this .NET hosting working in a cross-platform way. ⚠️ Note for Linux, the snap .NET (dotnet) installation had an [error, which I described here](https://github.com/Lunar2kPS/advanced-cpp/blob/main/docs/Dotnet%20Installation.md). Not sure if that's known or not, hope I'm not going too off-topic -- if I am, feel free to redirect me :).

Thanks so much!

**Comment by tdykstra** [comment]
@mjrousos can you answer this question?
