### ISSUE TITLE
Important NuGet packages are not named or linked to

### ISSUE THREAD

**Issue by SuuperW** [dotnet/docs#37142]
This document mentions that we can use NuGet packages to enable support for newer language features on older frameworks. It should also give information about _which_ NuGet packages these are, or how to find them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d0be2e3-8f90-8843-f98c-aadba19bec6d
* Version Independent ID: 012620d5-fa79-cc15-341b-3da8e5748890
* Content: [The relationship between language features and library types - C#](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/relationships-between-language-and-library)
* Content Source: [docs/csharp/whats-new/relationships-between-language-and-library.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/relationships-between-language-and-library.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 161150](https://dev.azure.com/msft-skilling/Content/_workitems/edit/161150)

**Comment by BillWagner** [comment]
Thanks for noting this @SuuperW 

That entire paragraph should be rewritten. Mixing an older framework with a newer version of the language is not supported. This article should be updated to reflect that.
