### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by acareyyup** [dotnet/docs#37141]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6493b5de-9d48-3a99-e213-06fdb121e067
* Version Independent ID: b320743f-f0ef-2174-df91-f0ddbb612e88
* Content: [Compiler Warning (level 2) CS0436 - C#](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0436?f1url=%3FappId%3Droslyn%26k%3Dk(CS0436))
* Content Source: [docs/csharp/misc/cs0436.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0436.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @acareyyup 

The best way to get specific questions answered the [Q & A](https://learn.microsoft.com/en-us/answers/tags/309/csharp) site. Add the smallest example you can that reproduces the error, and folks will help.

I'll close this as not a docs issue.
