### ISSUE TITLE
VSCode does not recognize the SDK

### ISSUE THREAD

**Issue by wgrs** [dotnet/docs#37163]
I have installed the SDK multiple times and now reinstalled vscode multiple times and keep getting this error.

The .NET Core SDK cannot be located: Error running dotnet --info: Error: Command failed: dotnet --info
Aborted (core dumped)

Aborted (core dumped)
. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

**_Here is dotnet --info_**
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /snap/dotnet-sdk/221/sdk/7.0.401/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [/snap/dotnet-sdk/221/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/snap/dotnet-sdk/221/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/snap/dotnet-sdk/221/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/greg/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602
* Version Independent ID: 2be3647d-495b-c9f0-cf06-9a7bf687d3bb
* Content: [Install .NET on Linux without using a package manager - .NET](https://learn.microsoft.com/en-gb/dotnet/core/install/linux-scripted-manual#scripted-install)
* Content Source: [docs/core/install/linux-scripted-manual.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry for the delay in response. It looks like you're using Snap. A few years ago that was a supported way of installing .NET, but that is no longer the case. You'll need to install .NET either through the Ubuntu package manager or by manually extracting the binaries somewhere and registering it with your system.

Since this issue is a bit old, did you get it solved?

**Comment by wgrs** [comment]
I got help from someone on Discord who helped fix the issue. Took 2 hours

**Comment by wgrs** [comment]
The issue is now back - this time with dotnet tools - when installed, it too cannot see the SDK.

**Comment by adegeo** [comment]
Before Snap support was dropped, it was a known issue that .NET Tools are mostly incompatible with snap installs of .NET. You'll have to install .NET through the package manage or manually and then configuring environment variables and making sure VSCode can resolve .NET correctly.

You really have to get out of .NET + Snap if you're still using it. It's too volatile. Personally, I love snap and wish it worked better together.

If you have an issue with the C# DevKit, you can find information on sending feedback at https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq but if you say you're using Snap, they'll probably tell you to get out of that first :)

I'm going to close this issue as I don't think there's anything in the docs to change.
