### ISSUE TITLE
Confusing documentation to install .NET SDK on Linux 23.04

### ISSUE THREAD

**Issue by wgrs** [dotnet/docs#37176]
When you read this document on installing .Net SDK [https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2304](url)

its states that the command to install the 7.0 SDK is `sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-7.0`

However, when you run dotnet --info at the bash, it states
`sudo apt  install dotnet-host-7.0`

Neither work correctly for me.

So which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34568c80-c10f-6f50-f7f7-a0bf8eab1408
* Version Independent ID: c43f280d-ee30-6092-b48c-93b58eb1dea1
* Content: [Install .NET on Ubuntu 23.04 - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2304)
* Content Source: [docs/core/install/linux-ubuntu-2304.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2304.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@wgrs you must have something configured incorrectly with your feeds. I can see the package in Ubuntu's online feed for 23.04: https://packages.ubuntu.com/search?suite=lunar&searchon=names&keywords=dotnet-sdk-7.0
