### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by SuschNL** [dotnet/docs#37197]
When issuing the command `docker build -t counter-image .` you just get the following:

```
[+] Building 0.1s (2/2) FINISHED                                                                                                                                docker:default
 => [internal] load .dockerignore                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                           0.0s 
 => [internal] load build definition from Dockerfile                                                                                                                      0.0s 
 => => transferring dockerfile: 793B                                                                                                                                      0.0s 
ERROR: failed to solve: Internal: Internal: Internal: stream terminated by RST_STREAM with error code: INTERNAL_ERROR
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
The command that you provided isn't the command in the article. Here's the difference:

```diff
- docker build -t counter-image .
+ docker build -t counter-image -f Dockerfile .
```

You should be calling:

```
docker build -t counter-image -f Dockerfile .
```

Could you please try that instead and let me know if you're still seeing an issue?

**Comment by SuschNL** [comment]
No, that wasn't the issue. docker defaults to "Dockerfile" so adding that doesn't really change anything.

I created the file from the example by cutting/pasting into Visual Studio Code. It seems that somehow Visual Studio Code created a UTF-16 LE text file from this, but I was not able to tell anything was different. I don't know why simple cutting and pasting from the webpage to VS Code (especially from a "code" section) would not just create a standard UTF-8 text file. It seems docker hates UNICODE Dockerfile files and gives this strange ambiguous `INTERNAL_ERROR` to let you know.

Anyway, I have the problem solved. Not an issue with the instructions on the page as I originally thought (sorry!), but people need to watch out with cut/paste to VS Code and encoding formats!
