### ISSUE TITLE
CS7003: No example on how to correct the error

### ISSUE THREAD

**Issue by Dimonasdf** [dotnet/docs#37214]
There is no corrected example provided. Textual description of correction does not help.

I am getting this error when trying to declare a list of classes with generic parameters.
```csharp
private List<DataDictionary<, >> dataDictionaries;                   //CS7003
private List<DataDictionary<Tkey, TData>> dataDictionaries;          //CS0246
private List<DataDictionary> dataDictionaries;                       //CS0305
```

```csharp
public abstract class DataDictionary<TKey, TData> : SerializedScriptableObject where TData : UnityEngine.Object
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40f57d67-ff24-cd38-4427-d94470eb885a
* Version Independent ID: b38bb8e7-3dbc-f915-15d0-0cbe2676d49e
* Content: [Compiler Error CS7003 - C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs7003)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs7003.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs7003.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @sputier That would be a great fix.

I'll assign this to you, and watch for a PR.

**Comment by sputier** [comment]
@BillWagner Here it is ! I changed the initial code sample to match existing real-world types so it is simpler for users to understand the code
