### ISSUE TITLE
An example is provided that shows bad code but does not include how to fix it

### ISSUE THREAD

**Issue by clairestrebva** [dotnet/docs#37226]
When the developer receives a CS0230 error from Visual Studio, and they are taken to this page, the page only shows them another example of bad usage. Their code already has the bad usage. It would be helpful if the page showed good usage so they would know how to fix their code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 416d2cb6-250d-f20a-2351-39c7d31d0ac0
* Version Independent ID: 12889d33-75e4-b698-f020-3f63061f5768
* Content: [Compiler Error CS0230 - C#](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0230?f1url=%3FappId%3Droslyn%26k%3Dk(CS0230))
* Content Source: [docs/csharp/misc/cs0230.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0230.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @clairestrebva 

The commented out line of code shows how to fix this error. That should be highlighted more in the text.

I've added this to our backlog, and added the "help wanted" label if anyone wants to submit a PR before we update this page.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!
