### ISSUE TITLE
Start service: Access denied

### ISSUE THREAD

**Issue by Onman99** [dotnet/docs#37223]
The tutorial says, at one point, the service can now be started. However, when I try to start the service I get a message that the service cannot be started: "Error 5: Access denied". Apparently somehow I need to give access to the service. But how?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create Windows Service using BackgroundService - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service?pivots=dotnet-7-0)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

---
[Associated WorkItem - 162170](https://dev.azure.com/msft-skilling/Content/_workitems/edit/162170)

**Comment by IEvangelist** [comment]
Hi @Onman99 - I'll add a note about being an admin user on the machine.
