### ISSUE TITLE
Missing 'maui' as an option

### ISSUE THREAD

**Issue by PaulDSheriff** [dotnet/docs#37234]
You are missing 'maui' as an option.

'dotnet new maui' does work. Please update this page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new &lt;TEMPLATE&gt; - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 163718](https://dev.azure.com/msft-skilling/Content/_workitems/edit/163718)

**Comment by tdykstra** [comment]
The table only lists templates "that come pre-installed with the .NET SDK." `maui` is not in that group.

**Comment by IEvangelist** [comment]
@tdykstra can this one be closed?

**Comment by tdykstra** [comment]
Yes, the question was answered.
