### ISSUE TITLE
How to override the JsonPropertyName while serializing?

### ISSUE THREAD

**Issue by akshay-zz** [dotnet/docs#37236]
The doc talks about how we can change the name of the JSON property name. Also how we can create our own `PropertyNamingPolicy`. But how can we override the `JsonPropertyName` while serializing? Is there any way to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bee4ecb-7464-b321-937a-e6d4586556eb
* Version Independent ID: 27c18218-d28f-a524-b7e1-8262005b7026
* Content: [How to customize property names and values with System.Text.Json - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-7-0#customize-individual-property-names)
* Content Source: [docs/standard/serialization/system-text-json/customize-properties.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/customize-properties.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
What is the scenario? Couldn't you just remove or update the attribute?

**Comment by akshay-zz** [comment]
Yep, In actual property I could not change the property attribute. Looking for a way to simply override it. For my case, I want to have lowercase names instead of what we have kept in the attribute(came case) when I serialize the model.

**Comment by gewarren** [comment]
You can probably do that with a [custom contract](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts) that modifies JsonPropertyInfo.Get, although I haven't tested it out. @eiriktsarpalis is the expert in this area.

**Comment by eiriktsarpalis** [comment]
If you're simply looking to convert property names to uppercase you might be able to just configure the `JsonSerializerOptions.PropertyNamingPolicy` with a [`JsonNamingPolicy`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonnamingpolicy?view=net-7.0) that performs that conversion.

**Comment by akshay-zz** [comment]
@eiriktsarpalis This will not work as it will get overridden by JsonPropertyName. I have tried that not working. Also, it is mentioned in the [docs](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-7-0#use-a-custom-json-property-naming-policy) also.

> The JSON property naming policy:
> 
> Applies to serialization and deserialization.
> Is overridden by [JsonPropertyName] attributes. This is why the JSON property name Wind in the example is not upper case
