### ISSUE TITLE
instructions dont work

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/docs#37233]
this step does not work!

**docker build -t counter-image -f Dockerfile .**

[+] Building 1.8s (11/13)                                                                                            docker:desktop-linux
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 399B                                                                                                 0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                                                    1.5s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0                                                                 1.5s
 => [build-env 1/5] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:2dd6fa19392967b26d59228af0ec481c652b98346ced56a4db1c66416b4c947f    0.0s
 => [internal] load build context                                                                                                    0.0s
 => => transferring context: 6.75kB                                                                                                  0.0s
 => [stage-1 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:933ae169296fe093776749cc47fd60e0a6e85bde607651a3fc6cd97bb5bc1ce0   0.0s
 => CACHED [stage-1 2/3] WORKDIR /App                                                                                                0.0s
 => CACHED [build-env 2/5] WORKDIR /App                                                                                              0.0s
 => CACHED [build-env 3/5] COPY . ./                                                                                                 0.0s
 => ERROR [build-env 4/5] RUN dotnet restore                                                                                         0.2s
------
 > [build-env 4/5] RUN dotnet restore:
0.213 **MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.**
------
Dockerfile:7
--------------------
   5 |     COPY . ./
   6 |     # Restore as distinct layers
   7 | >>> RUN dotnet restore
   8 |     # Build and publish a release
   9 |     RUN dotnet publish -c Release -o out
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet restore" did not complete successfully: exit code: 1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @SogoGolf - based on the error that you reported, you have a solution and a project in the same directory. This tutorial doesn't use a solution, instead from the command line it walks you through creating a C# console project and adding a _Dockerfile_. Since you have a solution now too, the .NET CLI doesn't know which to build, the solution or the project - so it exits and instructs you to specify one.

- You could either follow the tutorial exactly, .NET CLI with no solution, or
- Delete the solution, or
- Update the Dockerfile to specify the project

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore ./DotNet.Docker.csproj
# Build and publish a release
RUN dotnet publish ./DotNet.Docker.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
```
