### ISSUE TITLE
Where is the "pack directory" and what files to add those xml snippets to?

### ISSUE THREAD

**Issue by jwdonahue** [dotnet/docs#37246]
This page isn't very clear and exactly what should be edited and where.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 932f4ea5-7c43-7227-7bf0-35de3d7afb13
* Version Independent ID: 4e78038b-455c-2cec-170b-2f077c7d4f23
* Content: [NETSDK1145: Targeting or apphost pack missing - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1145)
* Content Source: [docs/core/tools/sdk-errors/netsdk1145.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1145.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @wli3
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
The "pack directory" is provided in the error message. "Add to the project" means add to the project file (the `.csproj` file for the project).
