### ISSUE TITLE
"net4.8" appears to be a legal (or non error creating) TFM for sdk style project 

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#37255]
### Type of issue

Other (describe below)

### Description

A csproj with the contents below does not fail to compile, report an error, or a warning in Visual Studio or the dotnet command line. 

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>
</Project>
```

This page says that it should be `net48`, which makes it inconsistent with all the other TFM.  This is a bit confusing. What is correct? The observable program or the documentation?

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/frameworks

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/frameworks.md

### Document Version Independent Id

4352856b-5ccf-8e62-48b4-3151340cac56

### Article author

gewarren

**Comment by gewarren** [comment]
I think that either variation works.
