### ISSUE TITLE
Using "master" in documentation

### ISSUE THREAD

**Issue by JoshLozensky** [dotnet/docs#37256]
[Section D.3.5](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d35-exception) still contains code using the word "master". Per Microsoft guidance this language should be replaced, for anyone internal at Microsoft you can reach out to [InclusiveLang@microsoft.com](mailto:InclusiveLang@microsoft.com) for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74e905-523c-dae9-f741-af5e52785a9c
* Version Independent ID: c9b7c7a1-0584-b6e6-95cd-5276788fdda0
* Content: [Documentation comments - C# language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments)
* Content Source: [standard/documentation-comments.md](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/documentation-comments.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for filing this @JoshLozensky 

We'll get it fixed.

**Comment by BillWagner** [comment]
Fixed in dotnet/csharpstandard#958
