### ISSUE TITLE
filestream is namespace but it is used like a type

### ISSUE THREAD

**Issue by Gobapassfromhere** [dotnet/docs#37263]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0118?f1url=%3FappId%3Droslyn%26k%3Dk(CS0118)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0118.md

### Document Version Independent Id

b21f6d12-00c2-0d18-4885-32b6a774d55e

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @Gobapassfromhere 

Can you provide more details about what information you need here to resolve the issue?
