### ISSUE TITLE
 public async Task<int> AddFundAsync(Fund fund)  {      var response = await _http.PostAsync("api/orders", fund);     return response.ConteClient.Execute<int>();  }

### ISSUE THREAD

**Issue by ajazghouse** [dotnet/docs#37260]
### Type of issue

Code doesn't work

### Description

cc
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md

### Document Version Independent Id

66121850-861c-9e37-27f0-811f80427d70

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @ajazghouse 

Can you give us more details about what information would help you diagnose this error?
