### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by O409389** [dotnet/docs#37271]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
BC30001

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/statement-is-not-valid-in-a-namespace?f1url=%3FappId%3Droslyn%26k%3Dk(BC30001)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/error-messages/statement-is-not-valid-in-a-namespace.md

### Document Version Independent Id

abeb0b2c-04cb-4416-281e-9b247d2207af

### Article author

KathleenDollard

**Comment by BillWagner** [comment]
Hi @O409389 

Can you provide more details on what's missing in this page? What information would help you resolve the error you're experiencing?
