### ISSUE TITLE
Learn feedback control

### ISSUE THREAD

**Issue by BET3S** [dotnet/docs#37286]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/tools/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/tools/index.md

### Document Version Independent Id

8b6d240f-aca1-646b-d0a5-b9a783e2c3da

### Article author

gewarren

**Comment by BillWagner** [comment]
closing as spam
