### ISSUE TITLE
Testing issue for linux area

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#37305]
### Type of issue

Typo

### Description

nothing

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md

### Document Version Independent Id

1850602d-6b92-1449-c8bd-116e36fc0f26

### Article author

adegeo

**Comment by BillWagner** [comment]
Hey @adegeo 

I'm assuming you were testing and this should be closed.
