### ISSUE TITLE
Code sample in 'What's new in .NET 8' does not behave as described.

### ISSUE THREAD

**Issue by fekberg** [dotnet/docs#37329]
### Description

Following the sample code i ["What's new in .NET 8"](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#serialization) the deserialization does not work as expected, and the output is different.

The following only allows for `Company` to be set:

```
[JsonObjectCreationHandling(JsonObjectCreationHandling.Populate)]
class CustomerInfo
{
    public string Name { get; } = "Anonymous";
    public CompanyInfo Company { get; } = new() { Name = "N/A", PhoneNumber = "N/A" };
}
```

If I add `[JsonObjectCreationHandling(JsonObjectCreationHandling.Populate)]` to the `Name` property it will result in the following exception:

```
Unhandled exception. System.InvalidOperationException: Property 'Name' on type 'CustomerInfo' is marked with JsonObjectCreationHandling.Populate but it doesn't support populating. This can be either because the property type is immutable or it could use a custom converter.
```

On the other hand, if I wrap the name in a class, and use that as a container it works. As long as the built-in types (string etc) are not read-only.

### Reproduction Steps

Create a new console application with the code from the docs:

```
using System.Text.Json;

CustomerInfo customer =
    JsonSerializer.Deserialize<CustomerInfo>("""{"Name":"John Doe","Company":{"Name":"Contoso"}}""")!;

Console.WriteLine(JsonSerializer.Serialize(customer));

class CompanyInfo
{
    public required string Name { get; set; }
    public string? PhoneNumber { get; set; }
}

[JsonObjectCreationHandling(JsonObjectCreationHandling.Populate)]
class CustomerInfo
{
    // Both of these properties are read-only.
    public string Name { get; } = "Anonymous";
    public CompanyInfo Company { get; } = new() { Name = "N/A", PhoneNumber = "N/A" };
}
```

### Expected behavior

Output:

```
{"Name":"John Doe","Company":{"Name":"Contoso","PhoneNumber":null}}
```

### Actual behavior

Output:

```
{"Name":"Anonymous","Company":{"Name":"Contoso","PhoneNumber":"N/A"}}
```

Name is not set as it's read-only and a built-in type.

### Known Workarounds

Wrap the built-in type in a new class, and do not mark it as read-only in that container.

### Configuration

Tried on both Windows and macOS using 8.0.100-rc.1.23463.5

**Comment by fekberg** [comment]
Gotcha, that makes sense! Did have me scratch my head for a while though when running the samples in that article.

Thanks for the quick reply

**Comment by fekberg** [comment]
@eiriktsarpalis It might also be a good idea to mention that this does not work with records or classes that have a primary constructor. There has to be a parameterless constructor for the deserialization to work.

Or if there is a work-around other than having to introduce a parameterless constructor, that would be valuable to mention.

**Comment by eiriktsarpalis** [comment]
> does not work with records or classes that have a primary constructor.

Presumably you mean parameterized constructors? It should work as usual with the notable exception of constructor parameters -- the concept of population doesn't apply since they have to be deserialized _before_ the containing object gets instantiated. 

Maybe I'm misunderstanding what you're saying though. Could you share an example explaining how you are impacted?

**Comment by fekberg** [comment]
AFAIK it's referred to the primary constructor.

Here's an example:

```
using System.Text.Json.Serialization;
using System.Text.Json;

var singleUserJson = """{"Username":"Filip","PhoneNumbers":["123456"]}""";

var userFromJson = JsonSerializer.Deserialize<User>(singleUserJson);

Console.WriteLine(userFromJson.PhoneNumbers.First());

[JsonObjectCreationHandling(JsonObjectCreationHandling.Populate)]
record User(string Username)
{
    public List<string> PhoneNumbers { get; } = new();
}
```

The above will throw `Unhandled exception. System.InvalidOperationException: Sequence contains no elements`.

If you change the record to this definition:

```
record User
{
    public string Username { get; set; }
    public List<string> PhoneNumbers { get; } = new();
}
```

`PhoneNumbers` will be populated with the data from the json. The same applies if you introduce a parameterized constructor within the `record`/`class`

**Comment by eiriktsarpalis** [comment]
Thanks, this looks like a real bug. FWIW it's not specific to primary constructors or records, this fails too:

```C#
using System.Text.Json.Serialization;
using System.Text.Json;

var singleUserJson = """{"Username":"Filip","PhoneNumbers":["123456"]}""";
var userFromJson = JsonSerializer.Deserialize<User>(singleUserJson);
Console.WriteLine(userFromJson.PhoneNumbers.Count); // 0

public class User
{
    public User(string name)
        => Name = name;

    public string Name { get; }

    [JsonObjectCreationHandling(JsonObjectCreationHandling.Populate)]
    public List<string> PhoneNumbers { get; } = new();
}
```

**Comment by fekberg** [comment]
Noticed that too, even if you make the parameter optional. If there's no parameterless constructor it won't populate any read-only fields.

Glad I could be of help, and thank you for the discussion!
