### ISSUE TITLE
LFC

### ISSUE THREAD

**Issue by dh-orko** [dotnet/docs#37325]
### Type of issue

Outdated article

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5.md

### Document Version Independent Id

a6f40f48-c59f-2f2e-57ad-c124cd04ecb9

### Article author

gewarren

**Comment by gewarren** [comment]
@dh-orko What does LFC stand for? Is the issue just that the article is out of date?
