### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ZavyFIre** [dotnet/docs#37345]
### Type of issue

Typo

### Description

I need help with this

![New Project (7)](https://github.com/dotnet/docs/assets/130857990/a643fd6b-8714-495a-8e73-f378902a2ca9)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0201

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0201.md

### Document Version Independent Id

974db5f0-3fb9-df14-0bb7-e18ab0b15f5d

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @ZavyFIre 

The image you posted doesn't give enough context to answer your question. The quickest way for you to get an answer is to post a larger code sample with a question on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site.

Closing as not a docs issue.
