### ISSUE TITLE
Compiler Error CS1022

### ISSUE THREAD

**Issue by mahendravankam** [dotnet/docs#37353]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1022?f1url=%3FappId%3Droslyn%26k%3Dk(CS1022)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1022.md

### Document Version Independent Id

8b8c700f-3f8c-a24d-2848-a1a3736b9ba2

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @mahendravankam 

Do you have more information about what you need to fix this error?
