### ISSUE TITLE
[{ 	"resource": "/c:/Users/G12_G Iroc/Desktop/CsharpProjects/TestProject/Program.cs", 	"owner": "_generated_diagnostic_collection_name_#1", 	"code": { 		"value": "CS8600", 		"target": { 			"$mid": 1, 			"path": "/query/roslyn.query", 			"scheme": "https", 			"authority": "msdn.microsoft.com", 			"query": "appId=roslyn&k=k(CS8600)" 		} 	}, 	"severity": 4, 	"message": "Converting null literal or possible null value to non-nullable type.", 	"startLineNumber": 10, 	"startColumn": 25, 	"endLineNumber": 10, 	"endColumn": 29 }]

### ISSUE THREAD

**Issue by Leonyrose** [dotnet/docs#37351]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103?f1url=%3FappId%3Droslyn%26k%3Dk(CS0103)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0103.md

### Document Version Independent Id

6eaec3e9-0ed9-f3ec-7516-032d57246715

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @Leonyrose 

Based on the title, I think you'll find the answer [here](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference).

Closing as answered.
