### ISSUE TITLE
Need real-world samples for JSON source generator

### ISSUE THREAD

**Issue by piskov** [dotnet/docs#37363]
### Type of issue

Missing information

### Description

Web APIs have a lot of DTOs (data transfer objects) which are used in multiple ways in controllers (get, put, etc.).

All current examples across the web for JSON source gen have one simple class consisting of basic .net types (e. g. integers or bools) which is nowhere near of real-world usage.

Here are just a handful of questions:

1. Suppose I have dozens (or even hundreds) of DTOs in API. How one should add source gen for them? One context with dozens of attributes? Separate contexts? Should I have source gen for all DTOs or only some?

    It would be great to see an example with 2-3 DTOs, not a simple single `WeatherForecast`. And guidelines how to add source generation for the entire API with dozens (hundreds) of DTOs.

2. What to do with nested DTOs. E. g. `AddressDto` inside `PersonDto`. How to configure source gen for that case? What would happen if nested DTO doesn’t have source gen but a parent does? What would happen if parent DTO has source gen, but nested doesn’t?

3. How one should handle collections? Suppose I have GET / Orders and POST / Order. Should I have source gen both for `OrderDto` and `OrderDto[]`?

5. What types of collections should be marked for source generation? Suppose I have these 3 cases:
- nested `IReadOnlyCollection<AddressDto> Addresses` property inside `PersonDto`;
- some controller to GET addresses that returns `ActionResult<IEnumerable<AddressDto>>`;
- some controller to POST `AddressDto`.

Should I add to source gen all 3 cases? `IReadOnlyCollection<AddressDto>`, `IEnumerable<AddressDto>`, `AddressDto`? And as for `IReadOnlyCollection` and `IEnumerable` adding the latter to source gen is suffice?

6. What about controller action return type `Task<ActionResult<IEnumerable<OrderDto>>>` — what should be added in this case? What if actual variables that are returned inside the method are List, HashSet or arrays (but the controller return type is still ActionResult of IEnumerable)?

7. Is there any way to know if some edge-case is missed? E. g. `OrderDto` is added but `IEnumerable<OrderDto>` is not?

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/source-generation.md

### Document Version Independent Id

558903e9-8173-464e-ff8b-7744419ad7e4

### Article author

gewarren

**Comment by piskov** [comment]
Discussed in somewhat more detail and context of pain points [here](https://github.com/dotnet/docs/issues/37370)

**Comment by eiriktsarpalis** [comment]
Seems like a duplicate? Could you maybe close one of the two?

**Comment by piskov** [comment]
This was created through automated “feedback” button for specific article. The other one is more for general discussion of docs, pain points, api usage, etc.

**Comment by eiriktsarpalis** [comment]
Alright, I'm going to close this one since we've already started the discussion on the other.
