### ISSUE TITLE
ipad ios

### ISSUE THREAD

**Issue by hirwalaurent5** [dotnet/docs#37380]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
provider custoumer configuration 

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/index.md

### Document Version Independent Id

85cc290b-da6c-6973-b00a-a17548450e19

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @hirwalaurent5 

Did you have a question or concern on this article? Can you add more information, or close it if it's not an issue.
