### ISSUE TITLE
Add basic aspects to the "Native interoperability" article

### ISSUE THREAD

**Issue by amesgen** [dotnet/docs#3739]
In my opinion, the "[Native Interoperability](https://docs.microsoft.com/en-us/dotnet/standard/native-interop)" article is missing some information to get started using the native interop capabilities of .NET. I want to point out three aspects:

 - The first "Note" mentions the cross-platform support of DllImport, but in the following examples a specific file ending is used. Afaik, you can simply use the library name without a file ending and gain portability if your native lib has a consistent name. But this topic is not trivial, see dotnet/coreclr#14968 and referenced issues.
 - It not clear what is the search path for native libraries. There are some StackOverflow answers regarding the .NET Framework, and there is [this part of the Mono documentation](http://www.mono-project.com/docs/advanced/pinvoke/#library-handling), but it would be nice to have an "official" explanation what is the default and how to change it.
 - Another concern especially when using your own native libraries is packaging. What are common/recommended patterns (not) to bundle them, in particular whilst maintaining cross-platform operability?

Keep on making documentation great again!

**Comment by mairaw** [comment]
Thanks @condensedapple for your feedback. @karelz @stephentoub who would be good contacts to help us review the native interop topic? Thanks!

**Comment by karelz** [comment]
@shrah @janvorli @russellhadley do you have suggestions?
