### ISSUE TITLE
Alpine 3.18 is supported

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/docs#37396]
### Type of issue

Missing information

### Description

Alpine 3.18 includes long awaited DNS TCP fallback via libmusl 1.2.4 as noted here.
https://www.alpinelinux.org/posts/Alpine-3.18.0-released.html

Alpine 3.18 is supported in the .NET Docker repo: 
https://github.com/dotnet/dotnet-docker/tree/main/src/sdk/6.0/alpine3.18

The "Supported distributions" table should mention 3.18 but only mentions up to 3.17

![image](https://github.com/dotnet/docs/assets/94054/60599ac3-9c74-4b9b-a7a4-98d31b8a0ccd)

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#supported-distributions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md

### Document Version Independent Id

f066a748-0a7d-7506-3b18-c422fef13293

### Article author

adegeo

---
[Associated WorkItem - 169712](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169712)

**Comment by adegeo** [comment]
Thanks for reporting. I'll get this fixed
