### ISSUE TITLE
Incorrect syntax in feature spec, unclosed string literal

### ISSUE THREAD

**Issue by donaldgray** [dotnet/docs#37406]
### Type of issue

Code doesn't work

### Description

The code example under [`Target Type Only`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/utf8-string-literals#target-type-only) heading contains a string that isn't closed.

```cs
// Current example
ReadOnlySpan<byte> span = "Hello World; 

// Should be
ReadOnlySpan<byte> span = "Hello World"; 
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/utf8-string-literals

### Content source URL

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/utf8-string-literals.md

### Document Version Independent Id

0716d08d-b851-efe8-b963-69427ec0459d

### Article author

dotnet-bot

**Comment by BillWagner** [comment]
Hi @donaldgray 

Thanks for spotting this. I opened dotnet/csharplang#7590 to address it.
