### ISSUE TITLE
Incorrect list of extensions included in shared framework

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/docs#37405]
[Runtime libraries overview](https://github.com/dotnet/docs/blob/9acfdd0d8fa4e0f3ac8bb63220f548b1c61fb843/docs/standard/runtime-libraries-overview.md#extensions-to-the-runtime-libraries) states that of that from the extensions to the runtime libraries, `Microsoft.Extensions.Http` is included in the shared framework.

> For some target frameworks, including net6.0, these libraries are part of the shared framework and don't need to be installed separately.

To my understanding this is not universally true.

If we consider `.NET Runtime 6.0.22` (`Microsoft.NETCore.App`) being 'the .NET runtime', then it does not include any `Microsoft.Extensions.*` assemblies.
If we consider `ASP.NET Core Runtime 6.0.22` (`Microsoft.AspNetCore.App`) being 'the .NET runtime', then not only `Microsoft.Extensions.Http` is, but other mentioned extensions are as well part of the shared framework.

The note to `Microsoft.Extensions.Http` has been added in PR https://github.com/dotnet/docs/pull/29568, but it doesn't explain why the extension should be highlighted as being contained in the shared framework.

**Target framework**

- [x] .NET Core (6.0.22)
- [ ] .NET Framework
- [ ] .NET Standard

Probably not relevant:
<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cbdde85-09dd-c0c5-724c-50cee3c4da18
* Version Independent ID: 9a3e1a10-1b76-69ae-e3f5-2e030aceb351
* Content: [Runtime libraries overview - .NET](https://learn.microsoft.com/en-us/dotnet/standard/runtime-libraries-overview)
* Content Source: [docs/standard/runtime-libraries-overview.md](https://github.com/dotnet/docs/blob/main/docs/standard/runtime-libraries-overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 250212](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250212)

**Comment by gewarren** [comment]
Thanks @d5UtQvp8QQU9. I'm not sure why I added that note either 🤔.
