### ISSUE TITLE
Incorect default value for decimal type

### ISSUE THREAD

**Issue by PetSerAl** [dotnet/docs#3740]
[Default values table](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/default-values-table.md) topic show `0.0M` as default value for `decimal` type. For `decimal` type `0M` and `0.0M` have different binary representation and `0M` is actual default value for `decimal` type.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @PetSerAl. We'll update the documentation by December 1.
