### ISSUE TITLE
Unclear specification of the c# language version

### ISSUE THREAD

**Issue by xavdelec** [dotnet/docs#37417]
### Type of issue

Missing information

### Description

In the article, it is stated that C# 7.3 is the default version for .NET framework.

This is not true and depends on the Visual studio version.
For example, with Visual Studio 2019, default version of the C# language is 9.0,
as given by the csc tool:
```
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn> .\csc.exe /langversion:?
Supported language versions:
default
1
2
3
4
5
6
7.0
7.1
7.2
7.3
8.0
9.0 (default)
latestmajor
preview
latest
```
It would be nice to provide this precision.
Thanks

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version?source=docs

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md

### Document Version Independent Id

3f01c378-22e4-197c-a862-ab4a924506c7

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @xavdelec 

You're correct that with the newer versions of Visual Studio, the C# compiler *can* make use of newer C# syntax.

However, if your project targets the .NET Framework (the windows component), the compiler defaults to the LangVersion of 7.3.  You'd need to override the default value in your CSProj file to use any newer syntax. That's covered in the next section.

I'm closing this, as the article already covers those scenarios.
