### ISSUE TITLE
Replace student.LastName with student.FirstName

### ISSUE THREAD

**Issue by NichlasNielsen** [dotnet/docs#37435]
### Type of issue

Other (describe below)

### Description

In the last example given, shouldn't the grouping "FirstLetter" use student.FirstName instead of LastName? When the output is as follows:

/* Output:
    Name starts with A who scored more than 85
            Terry Adams
    Name starts with F who scored more than 85
            Fadi Fakhouri
            Hanying Feng
    Name starts with G who scored more than 85
            Cesar Garcia
            Hugo Garcia
    Name starts with G who scored less than 85
            Debra Garcia
    Name starts with M who scored more than 85
            Sven Mortensen
    Name starts with O who scored less than 85
            Claire O'Donnell
    Name starts with O who scored more than 85
            Svetlana Omelchenko
    Name starts with T who scored less than 85
            Lance Tucker
    Name starts with T who scored more than 85
            Michael Tucker
    Name starts with Z who scored more than 85
            Eugene Zabokritski
*/

Because, as we can see, the name Terry Adams does not start with A.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/group-query-results

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/group-query-results.md

### Document Version Independent Id

b5130725-9cfc-5424-53b6-a6b0860aa6fc

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @NichlasNielsen 

I'll leave this open as a potential enhancement to clarify the variable name `FirstLetter`. We should probably change it to `FirstLetterOfLastName`. 

The code works as explained, it is grouped by the last name, but the variable can lead to some confusion.

I've added this to our backlog, and added the "help wanted" label if someone wants to submit a PR before we make our next updates.
