### ISSUE TITLE
should also mention sealed

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#37453]
### Type of issue

Missing information

### Description

This doc page mentions "**derived**" but lacks a brief note of "**sealed**" to prevent [further] inheritance.
Also some "**access modifiers**" are explained but not sealed. [Order modifiers](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036) clearly shows preferred modifier order

If I design a _leaf_ class I find it convenient to state **sealed** access to avoid **CA1816** warnings
this doc page could include similar tip

Doc TOC certainly includes **abstract and sealed**, but ditto "**See also**" footer mentions [Accessibility Levels](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels) but imho should also point to [Abstract and Sealed Classes](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md

### Document Version Independent Id

76a389f6-b568-3568-6483-6df440f96f0c

### Article author

BillWagner

**Comment by BartoszKlonowski** [comment]
I will handle this, @BillWagner please assign me to this item if possible :pray:

**Comment by BillWagner** [comment]
> I will handle this, @BillWagner please assign me to this item if possible 🙏

Done. Thanks @BartoszKlonowski
