### ISSUE TITLE
program.cs

### ISSUE THREAD

**Issue by Karlocar** [dotnet/docs#37457]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs2001?f1url=%3FappId%3Droslyn%26k%3Dk(CS2001)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs2001.md

### Document Version Independent Id

be0bc1f4-5d5d-e813-704c-d73c5eeae58c

### Article author

BillWagner

**Comment by postmeback** [comment]
An elaborate description would be helpful

**Comment by BillWagner** [comment]
Hi @Karlocar 

Can you provide more details on your code and what you were hoping to find on this page?
