### ISSUE TITLE
Wrong hyperlink "DirectoryServices package no longer references System.Security.Permissions"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docs#37464]
### Type of issue

Other (describe below)

### Description

The "DirectoryServices package no longer references System.Security.Permissions" link points to the [ConfigurationManager package no longer references System.Security.Permissions](https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/configurationmanager-package) page even though it should point to the [DirectoryServices package no longer references System.Security.Permissions](https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/directoryservices-package) page.

The link was added in <https://github.com/dotnet/docs/pull/36787>.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/8.0.md

### Document Version Independent Id

1dc7a986-52e6-3a88-0163-4a869afc75d3

### Article author

gewarren

**Comment by BartoszKlonowski** [comment]
I think this issue is valid:
From what I see, the link is incorrectly copy-pasted from the `ConfigurationManager package no longer references System.Security.Permissions` above.
I will handle this!
