### ISSUE TITLE
vss assembly reference issue

### ISSUE THREAD

**Issue by RAHULKUMARREDDYKING** [dotnet/docs#37478]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Inkaar' could not be found (are you missing a using directive or an assembly reference?)	RelationshipManagementLib	D:\laptop code\RahulCodeSetup\RelationshipManagementLib\Accounting.cs	14	Active

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0246.md

### Document Version Independent Id

902901c2-f8b6-c58c-c2e8-f93aab2487c9

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @RAHULKUMARREDDYKING 

Can you provide more details on your project and what you information you needed to fix the error.
