### ISSUE TITLE
Add unit testing information

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/docs#37487]
### Type of issue

Missing information

### Description

Unit testing is extremely important for creating Source Generators and not showing how to unit test nor highly recommending it, leads to devs thinking they don't need them, which just leads to endless complaints. See https://github.com/dotnet/roslyn/issues/48083.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md

### Document Version Independent Id

f1ed9873-3e29-b4bd-2dbb-44dd9a05d790

### Article author

BillWagner

**Comment by BillWagner** [comment]
Tagging @KathleenDollard 

She's working on new material in this space.
