### ISSUE TITLE
Missing --sdk-version option in `dotnet workload install` docs

### ISSUE THREAD

**Issue by HavenDV** [dotnet/docs#37498]
### Type of issue

Outdated article

### Description

> Results vary by SDK version
The dotnet workload commands operate in the context of specific SDK versions. Suppose you have both .NET 6.0.100 SDK and .NET 6.0.200 SDK installed. The dotnet workload commands will give different results depending on which SDK version you select. This behavior applies to major and minor version and feature band differences, not to patch version differences. For example, .NET SDK 6.0.101 and 6.0.102 give the same results, whereas 6.0.100 and 6.0.200 give different results. You can specify the SDK version by using the [global.json file](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) or the --sdk-version option of the dotnet workload commands.

According to this paragraph, you can also specify `--sdk-version`, which is not reflected in the list of available options.
It is also important to indicate which version of dotnet this is available from (for example, to understand whether this can be used in [custom workload installation scripts like Tizen](https://github.com/Samsung/Tizen.NET/blob/v7.0.400/workload/scripts/workload-install.sh). they currently use global.json, which has its own problems)

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-workload-install.md

### Document Version Independent Id

55bbba16-ae98-5abc-cd42-1b677105fd29

### Article author

tdykstra

---
[Associated WorkItem - 173584](https://dev.azure.com/msft-skilling/Content/_workitems/edit/173584)

**Comment by tdykstra** [comment]
If you specify the SDK version using the option, the response is:

>The --sdk-version option is no longer supported for this command.

I will update the text in the `dotnet workload install` doc.
