### ISSUE TITLE
.NET Core Guide intro topic - Address customer feedback - low CSAT

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#3749]
# NET Core Guide intro - Address feedback - low CSAT
This topic: https://docs.microsoft.com/en-us/dotnet/core/
Requires investigation, customer satisfaction ratings in low 60's although improved somewhat from earlier in the year.

Some example feedback asks:  
- Localization requests for a Chinese translation. 
- Why use .NET Core and what for?

Please do look deeper beyond those two requests.

**Comment by mairaw** [comment]
Really hard to access current asks for this page given there's just two comments from the last 90 days. The Chinese version of this topic is already available, for example.

**Comment by mairaw** [comment]
@JRAlexander would you like to work on this one? Given that you'd come to this one with fresh eyes, it might be a good one for you to address.

**Comment by JRAlexander** [comment]
@mairaw - I can do that!

**Comment by tdykstra** [comment]
Per SkyRay, this article is currently at 93% with 30 ratings in the last month.
