### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by Smpse** [dotnet/docs#37509]
### Type of issue

Missing information

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#73-declarations

### Content source URL

https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/basic-concepts.md

### Document Version Independent Id

13832745-4304-3f38-2b2e-c5cad65c60ed

### Article author

dotnet-bot

**Comment by BillWagner** [comment]
Hi @Smpse 

Can you add more details about what you were looking for in this article?
