### ISSUE TITLE
This package has been deprecated as it is legacy and is no longer maintained.

### ISSUE THREAD

**Issue by guercheLE** [dotnet/docs#37504]
### Type of issue

Outdated article

### Description

[Enter feedback here]
At https://www.nuget.org/packages/MLNet it is said "This package has been deprecated as it is legacy and is no longer maintained.". What is that about?

### Page URL

https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/machine-learning/automate-training-with-cli.md

### Document Version Independent Id

c8a49f16-d0fd-cdcf-1886-73302ea3ee53

### Article author

luisquintanilla

**Comment by gewarren** [comment]
@luisquintanilla

**Comment by gewarren** [comment]
@guercheLE The correct package is https://www.nuget.org/packages/Microsoft.ML.
