### ISSUE TITLE
BC 30689

### ISSUE THREAD

**Issue by sudhakarreddy77** [dotnet/docs#37505]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30689?f1url=%3FappId%3Droslyn%26k%3Dk(BC30689)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30689.md

### Document Version Independent Id

31ac834f-0e06-7e86-4016-ec953de4a880

### Article author

KathleenDollard

**Comment by BillWagner** [comment]
Closing because there aren't any details.
