### ISSUE TITLE
asp.net problem

### ISSUE THREAD

**Issue by Shikha4554** [dotnet/docs#37507]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0102?f1url=%3FappId%3Droslyn%26k%3Dk(CS0102)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0102.md

### Document Version Independent Id

594c625e-c6da-38d1-ba16-cd4d9e3e9dcd

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @Shikha4554 

Can you add some details regarding what you we're looking for in this article?

Thanks
