### ISSUE TITLE
c6106

### ISSUE THREAD

**Issue by mvmshakkir** [dotnet/docs#37500]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0106?f1url=%3FappId%3Droslyn%26k%3Dk(CS0106)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0106.md

### Document Version Independent Id

f3a26a17-4d0b-e6fc-dd54-28d91e4fa5ad

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @mvmshakkir 

Can you add more details regarding what information you need from this page?
