### ISSUE TITLE
The example doesn't show the fix

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#37518]
### Type of issue

Missing information

### Description

The example shows code that won't compile because it's missing a partial declaration *without* an implementation. The article should also include the correction: Two separate class declarations, one with an implementation, and one without.

Supercedes internal work item [1894321](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1894321)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0759?f1url=%3FappId%3Droslyn%26k%3Dk(CS0759)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0759.md

### Document Version Independent Id

21837aec-5c20-f647-17c8-e97aac29b137

### Article author

BillWagner

**Comment by BartoszKlonowski** [comment]
I will gladly take it, @BillWagner!
