### ISSUE TITLE
Documentation tags in CSHTML

### ISSUE THREAD

**Issue by plykkegaard** [dotnet/docs#37513]
### Type of issue

Missing information

### Description

Hi

I wonder how I can insert comment tags in CSHTML file for XML Documentation to collect

In NET 7 C# MVC app you have a bunch of autogenerated CSHTML files which is included in the SancCastle HB output but how can I add a few comments to document these files?

Thanks /Peter

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/index.md

### Document Version Independent Id

707b352c-ea51-494c-d4f1-33e140ab9d17

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @plykkegaard 

There isn't a standard way to add XML docs to a razor page.

I would ask on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) to see if anyone in the community has determined a way to make this work.

I'll close this as not a docs issue.
