### ISSUE TITLE
Unit testing C# code in .NET Core using dotnet test - high PV low CSAT - root directory issue in samples

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#3762]
# Unit testing C# code in .NET Core - high PV low CSAT - root directory issue in samples
This topic: [Unit testing C# code in .NET Core using dotnet test and GitHub](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)

High page view topic but low ratings.  Requires further inspection.

Customer feedback recently points to sample issue that refers to wrong root directory.

**Comment by mairaw** [comment]
We'll take care of the sample issue this quarter but the bulk of the work for this, we'll need more time to think about it.

**Comment by mairaw** [comment]
I ended up looking at this today for other reasons as well. The customer feedback re. sample issue has been addressed months ago already.
