### ISSUE TITLE
We can simply the Worker SDK example for .NET 8 GA!

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#37630]
### Type of issue

Outdated article

### Description

For .NET 8, Web and Worker projects don't need the package mentioned [here](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#add-nuget-package) at all - we can condense this entire section down to just a note for Console projects if we want.

In addition, we can unify the output mentioned in [this section](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#publish-net-app) to de-emphasize the `/t:PublishContainer` path in favor of leaning on `-p PublishProfile=DefaultContainer` instead!

This is all because last week we merged Worker SDK support for publish profiles (and thus the built-in containerization) to the .NET 8 GA SDK.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
This work was already done.
