### ISSUE TITLE
Producing CompatibilitySuppression.xml

### ISSUE THREAD

**Issue by phatcher** [dotnet/docs#37649]
### Type of issue

Missing information

### Description

Might be worthwhile mentioning that you can also use `dotnet build /p:GenerateCompatibilitySuppressionFile=true` to produce the `CompatilibilitySuppression.xml` files, this has the advantage of ensure that the project is build correctly and works for the entire solution rather than a single assembly

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/package-validation/overview.md

### Document Version Independent Id

aec40896-e18d-a61d-2dbb-467556b24678

### Article author

dotnet-bot

---
[Associated WorkItem - 292103](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292103)

**Comment by gewarren** [comment]
Related to #36988.

**Comment by gewarren** [comment]
Related to #36235

**Comment by gewarren** [comment]
Thanks for the feedback. This info was actually added about a month after you logged this issue - see https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/diagnostic-ids#how-to-suppress.
