### ISSUE TITLE
Don't use whitespaces around brackets in collection expressions

### ISSUE THREAD

**Issue by xamir82** [dotnet/docs#37640]
On [this page](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions), the collection expressions in the code snippets have whitespaces around the brackets. This is an abomination. This style is not common is any language that uses brackets for array/collection initializations (e.g. JS, Python, etc.) and adds unnecessary noise to the code. It's also not what nearly any of [the code examples in proposal](https://github.com/dotnet/csharplang/issues/5354) looked like. Most notably, it's also inconsistent with [list patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#list-patterns) in C# itself, a sort of aesthetic symmetry between list patterns and collection expressions was always touted as one of the important things about this feature.

This is a mistake. Please do not use this style.

I could make a PR to fix this. Let me know if you're on board.

**Comment by gfoidl** [comment]
There's also the opposite side: https://github.com/dotnet/runtime/pull/93125#discussion_r1348851932

**Comment by xamir82** [comment]
@gfoidl I would say that's a very idiosyncratic preference, as I said, the style is universally "no space" in other languages who have a similar construct. And again, even in C#, list patterns don't use spaces around brackets either.

**Comment by gfoidl** [comment]
Just wanted to point to a different opinion (which reflects also my opinion).

JavaScript for instance doesn't have custom indexers, so that reference doesn't apply here if we consider the distinction to indexers as valid point.

Also one could argue that array initializers in C# of the form `int[] arr = { 1, 2, 3 };` has spaces around, so collection expressions (which "init" something) should have also spaces around.
List patterns don't "init" something, rather use it -- a bit more similar to indexers, so no spaces around is fine.

So what's an abomination for you, might be quite helpful for others.

In the end the use within .NET should be consistent (in either way), and everyone can choose the prefered style for their own projects.

**Comment by xamir82** [comment]
> JavaScript for instance doesn't have custom indexers, so that reference doesn't apply here if we consider the distinction to indexers as valid point.

I don't see how "custom indexers" is relevant here, JavaScript has the same `obj[...]` notation that custom indexers in C# would yield on the usage side of things. So the reference does very much apply. I don't think that's a valid point.

> Also one could argue that array initializers in C# of the form int[] arr = { 1, 2, 3 }; has spaces around, so collection expressions (which "init" something) should have also spaces around.

That's a non-sequitur IMO. The collection expression syntax is a different syntax, and its primary advantage over the existing syntaxes (e.g. the array init syntax) is its conciseness. There's no reason to take inspiration from the very syntax that collection expression are meant to replace.

Of course. you're totally free to use spaces around brackets if you like that formatting, this issue is just about the "official" style; and again, also considering the fact that the [dotnet/runtime](github.com/dotnet/runtime) codebase is now using the no space style as well, in addition to the other reasons that I provided, it makes sense to update the docs accordingly.

**Comment by CyrusNajmabadi** [comment]
FYI, the position of the C# team here is that list patterns and collection expressions do not have spaces around the brackets.

Similarly, slice patterns and spread elements *do* have whitespace.  So you would write out a list pattern like so:

```c#
if (x is [start, .. middle, end])
```

And you would create a collection like so:

```c#
x = [start, .. middle, end];
```

These are consistent, and are going to be what our tools use.  It would be preferred if any usages of collections from dotnet projects follows this style.

**Comment by CyrusNajmabadi** [comment]
I opened https://github.com/dotnet/docs/pull/37656 for this.  Thanks for the report.
