### ISSUE TITLE
runtimeconfig.json

### ISSUE THREAD

**Issue by Gigoloindo** [dotnet/docs#37653]
### Type of issue

Code doesn't work

### Description

```dockerfile
#37650 @bearerr
``` 

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/runtime-config/debugging-profiling

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/runtime-config/debugging-profiling.md

### Document Version Independent Id

76e55ec8-6340-e851-b4dd-e415a541d187

### Article author

runtimeconfig.json

**Comment by gewarren** [comment]
@Gigoloindo Can you provide more information about the code that doesn't work?
