### ISSUE TITLE
[Breaking change]: Remove network.protocol.name from http.server.request.duration

### ISSUE THREAD

**Issue by JamesNK** [dotnet/docs#37650]
### Description

.NET 8 GA removes the `network.protocol.name` attribute from `http.server.request.duration` metric.

Note that this metric was added during previews in the .NET 8 release cycle.

### Version

.NET 8 GA

### Previous behavior

The `network.protocol.name` attribute always had a value of `http` on the `http.server.request.duration` metric.

### New behavior

The `network.protocol.name` attribute isn't added to the `http.server.request.duration` metric.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [X] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

The `network.protocol.name` attribute has been removed because the value is always `http` and [the semantic conventions spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpserverrequestduration) only recommends specifying the attribute for non-http values.

Removing the unnecessary attribute simplifies the metric content.

### Recommended action

If you require the `network.protocol.name` metric then it could be re-added to the `http.server.request.duration` metric using enrichment.

Example ASP.NET Core middleware that re-adds the attribute:

```cs
app.Use(async (context, next) =>
{
    var tagsFeature = context.Features.Get<IHttpMetricsTagsFeature>();
    if (tagsFeature != null)
    {
        tagsFeature.Tags.Add(new KeyValuePair<string, object?>("network.protocol.name", "http"));
    }

    await next.Invoke();
});
```

See https://learn.microsoft.com/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0#enrich-the-aspnet-core-request-metric for more information.

### Feature area

ASP.NET Core

### Affected APIs

The `http.server.request.duration` metric on ASP.NET Core's `Microsoft.AspNetCore.Hosting` meter.

---
[Associated WorkItem - 177287](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177287)

**Comment by gewarren** [comment]
Since this is only a breaking change if you installed a preview version of .NET 8, it doesn't make sense to document it as a breaking change at this point. But I'll leave the issue open for a couple months in case customers run into it.
