### ISSUE TITLE
Issue Learn feedback control.

### ISSUE THREAD

**Issue by GmsDevOff** [dotnet/docs#37667]
### Type of issue

Typo

### Description

[Escribir comentarios aquí]

### Page URL

https://learn.microsoft.com/es-mx/dotnet/core/tools/dotnet-install-script?WT.mc_id=dotnet-35129-website

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md

### Document Version Independent Id

5bc7caa5-f1c2-d7d5-fe02-80c65cca9672

### Article author

tdykstra

**Comment by tdykstra** [comment]
Where in the article is the typo you're reporting?

**Comment by gewarren** [comment]
@tdykstra Maybe that some of the text isn't translated.

<img width="456" alt="image" src="https://github.com/dotnet/docs/assets/24882762/4e561cab-3899-4ee2-af1a-34ba292d029a">

**Comment by tdykstra** [comment]
@gewarren I assume you're correct. I'll close this issue, as this is a localization issue and is being addressed by internal work item:
https://ceapex.visualstudio.com/Engineering/_workitems/edit/921099
