### ISSUE TITLE
Add reference for runtime template config

### ISSUE THREAD

**Issue by 21a1ss3** [dotnet/docs#37666]
### Type of issue

Missing information

### Description

Hi,

Recently I've encountered a misreading issue (https://github.com/dotnet/runtime/issues/93745) with article with new file format. I suggest to add a reference to article mentioned by Eiric in my initial issue and might be at least one example

Best Regards,
Artem Matveev.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#flavors-of-garbage-collection

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/runtime-config/garbage-collector.md

### Document Version Independent Id

5363faee-3808-d011-d371-c48a95dcabf0

### Article author

gewarren

**Comment by gewarren** [comment]
Thanks - this is the same as https://github.com/dotnet/docs/issues/37205. I hope to address it next month.
