### ISSUE TITLE
[Breaking change]: Source Link is included in the .NET SDK

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#37674]
### Description

The [Source Link](https://github.com/dotnet/sourcelink) build tooling is included in the .NET SDK as of [.NET SDK 8.0.100-preview.4](https://github.com/dotnet/sdk/pull/31632), which enables packages and applications to embed information about the source control information of the built artifacts. As a side effect, by default commit information will be included in the InformationalVersion of build libraries and applications.

### Version

.NET 8 Preview 6

### Previous behavior

Prior to this change, the default `InformationalVersion `of a library or application would be the `Version` property.

### New behavior

After this change, the default `InformationalVersion` of a library or application would be the `Version` property as well as the `SourceRevisionId` property.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [x] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

Source Link enables very rich editor tooling, like go-to-definition support for non-local source files. We think this benefit is worth including by default for all artifacts.

### Recommended action

If your build process or code is not expecting Source Revision information in the InformationalVersion, you can disable this behavior by setting the `IncludeSourceRevisionInInformationalVersion` property to `false`.

### Feature area

SDK

---
[Associated WorkItem - 177280](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177280)

**Comment by rainersigwald** [comment]
@baronfel isn't this "source incompatible" rather than "behavior change"? Existing binaries don't change behavior but updating the SDK and rebuilding can change a version string.

**Comment by DalekBaldwin** [comment]
It would help to also document the `SuppressImplicitGitSourceLink` property. As it is now, in a repo with no mention of SourceLink, after you execute git commands that should leave up-to-dateness unchanged, net8.0 considers all projects to be marked for rebuilding.

**Comment by adurmus** [comment]
Imagine your CI/CD relies on Product Version. Suddenly whole CI/CD operations fail because the `ProductVersion` cannot be parsed anymore with `System.Version`. Well done.
