### ISSUE TITLE
 gcroot -all gives error

### ISSUE THREAD

**Issue by ozgurnevres** [dotnet/docs#37673]
### Type of issue

Code doesn't work

### Description

When I run  gcroot -all it gives following error:

Unrecognized command or argument '026785c00040'

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/debug-memory-leak.md

### Document Version Independent Id

03f3761e-be31-bae9-6ac7-ad86db389212

### Article author

tommcdon

**Comment by gewarren** [comment]
This is the same as issue #35077. Are you sure you're not using the .NET Framework version of the SOS debugging extension?

**Comment by saucecontrol** [comment]
The `-all` option was removed in https://github.com/dotnet/diagnostics/pull/3766

> We now always run !gcroot -all. It's fast enough we no longer need to limit root output.
