### ISSUE TITLE
 [HttpDelete]         [Route("DeleteUser")]          public string DeleteUser(int id)         {             Users users = userContext.Users.Where(x => x.ID == id).FirstOrDefault();             object user = null;             if (user != null)             {                 userContext.Users.Remove(user);                 userContext.SaveChanges();                 return "User deleted";             }             else             {                 return "No User found";             }                  }

### ISSUE THREAD

**Issue by eisajan** [dotnet/docs#37683]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md

### Document Version Independent Id

66121850-861c-9e37-27f0-811f80427d70

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @eisajan 

Can you add details about what you hoped to learn from this article?

If you're looking for help, the best route is to ask a question on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site.
