### ISSUE TITLE
Bad link in Asp .net core tutorial page.

### ISSUE THREAD

**Issue by LindaLawton** [dotnet/docs#3768]
The page `https://github.com/dotnet/docs/blob/master/docs/core/tutorials/aspnet-core.md` has a link  `[ASP.NET Core documentation](/aspnet/core/) `  Which results in a 404.

**Comment by sputier** [comment]
@LindaLawton This link points to a documentation page stored in the aspnet/Docs repository : https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md

The reason the link is relative is both docs (dotnet & aspnet) are hosted at https://docs.microsoft.com : 
* https://docs.microsoft.com/dotnet/
* https://docs.microsoft.com/aspnet/

**Comment by LindaLawton** [comment]
I guess i need to learn how to us this repo.   Thanks
