### ISSUE TITLE
Setting up the repository for Alternative Architectures (ARM64)

### ISSUE THREAD

**Issue by miho** [dotnet/docs#37692]
### Type of issue

Missing information

### Description

The documentation explains how to add the repository so that apt can find it. But it doesn't explain how we can make that work on ARM64 or any other architecture that is not AMD64. Apt can only find the AMD64 versions.  So, either it is an issue with the documentation or the repository only contains the AMD64 version, despite ARM64 being added to the sources.list. Either way, the documentation should go into further detail here.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md

### Document Version Independent Id

ab01f0aa-d1c0-df64-b0f9-ee211d45001f

### Article author

adegeo

**Comment by adegeo** [comment]
Hello, there is a note in the first few paragraphs of the article that state that only the packages for x64 arch are published and that **ARM**/64 isn't supported via the package manager.

![image](https://github.com/dotnet/docs/assets/67293991/03912e6e-1e6b-4f1d-bd3e-266697ff970c)
