### ISSUE TITLE
XNode.ReadFrom(XmlReader) Method. Error in sample code.

### ISSUE THREAD

**Issue by colgreen** [dotnet/docs#3769]
I used the sample C# code from here:

    https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xnode.readfrom

If you take the example XML file the sample is using and remove all of the whitespace (i.e. such that the XML content is all on one line but still logically the same XML structure), then the reader loop will skip every other element instead of reading all of the elements.

It's not uncommon for XML to have no whitespace when used in data transmission scenarios, and in fact it was such a scenario  where we noticed this problem.

The issue is that when an element is reached, ReadFrom() is called to read it into an XElement. The reader is then positioned on the next node to read and therefore the Read() in the while statement will skip that node. 

When there is whitespace that skipped node will generally be a whitespace node, but in unformatted XML it will be the next element node.

**Comment by mairaw** [comment]
Thanks for reporting this issue @colgreen. We'll investigate.

**Comment by mairaw** [comment]
@colgreen I have created the following PRs to fix this issue:
https://github.com/dotnet/samples/pull/118
https://github.com/dotnet/dotnet-api-docs/pull/260

**Comment by colgreen** [comment]
@mairaw Thanks. Yeh looks good.
