### ISSUE TITLE
Compiler Error CS0266

### ISSUE THREAD

**Issue by jibrilsano495** [dotnet/docs#37755]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
Compiler Error CS0266

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0029?f1url=%3FappId%3Droslyn%26k%3Dk(CS0029)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0029.md

### Document Version Independent Id

06488d45-19ec-f12c-0cbb-82c9bf133bb0

### Article author

BillWagner

**Comment by BillWagner** [comment]
hi @jibrilsano495 

The two errors you reference would indicate that you're trying to assign variables of two different types. Without more details, it's hard to make suggestions.

The best way to get this resolved is to post a specific question on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp).
