### ISSUE TITLE
Experimental attribute in assembly?

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#37766]
### Type of issue

Missing information

### Description

I do not see, either here or in the API page, a description on what this attribute does on an assembly.

Apologies if this is a dupe

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#alias-any-type

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-12.md

### Document Version Independent Id

587ed47f-f532-e018-9b0d-6ee76afd20e4

### Article author

BillWagner

**Comment by BillWagner** [comment]
Duplicate of #37765
