### ISSUE TITLE
Small issue in documentation

### ISSUE THREAD

**Issue by JonnyJalapeno** [dotnet/docs#37779]
### Type of issue

Typo

### Description

On the page there's excerpt:
```
// Initialize to null.
string message2 = null;
```

But it's not true, you need to add nullable operator ? after the string in order for compiler to no throw an error. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md

### Document Version Independent Id

3317fd4a-9cd3-57cd-66f7-abb271e302e8

### Article author

BillWagner

**Comment by BillWagner** [comment]
Thanks for mentioning this @JonnyJalapeno 

This sample hasn't been updated since we enabled NRT throughout our samples.

I've added this to our backlog, and added the "help wanted" label if anyone wants to submit a PR before we get to it.
