### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by Barderos1** [dotnet/docs#37787]
### Type of issue

Code doesn't work

### Description

[Escriba sus comentarios aquí]
…S’a ÄçÞE++‡d²4ä¸#|l#¹ýß
àYÏN<Àš”šxÕgbþÌÀ¾w]ðøæ¼b 6ó1¨ÊÂS¾	F?°pY$rRÚüßYQa†æÎ(£?ÄtÌB›Ùce"oé,Õ°	ët§EžÌŠeØ»¤ÁÏùÄ‘€y{B­
’ë'˜q=dwðpF¥pÙ‰¡TD
d;Ì&fÁf]Ì:‚›äÏ|sÍíV®ˆ™6Þ‰¸´s£‰ð¦„|hqnüJÕ=ñölôIý«ey4ìÓß3<[³VQ'…ÉâÁ]çœ¸™Ÿ3!ƒÒvÍjœ³Õ†hâoÇ
rÒ·ä&lþ¢Ö<k7™Î†…bÍ¦ëPM°¤ý·ÓGÊÐûV9ãïïåë¡]{Ù¢ßÌIÈF[ÍsÃ(;kCPÉ…tç«žÀŠÛý|$í¦ÌsÁš


### Page URL

https://learn.microsoft.com/es-es/dotnet/standard/base-types/character-encoding-introduction

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/character-encoding-introduction.md

### Document Version Independent Id

d53a0764-9f27-16b3-c40a-9627dd1bcc0d

### Article author

adegeo

**Comment by adegeo** [comment]
Hello, it looks like your issue description is garbled. Please edit the issue and let me know what isn't working in the article. Thanks!
