### ISSUE TITLE
reactredux doesn't seem to be supported and available

### ISSUE THREAD

**Issue by AYColumbia** [dotnet/docs#37781]
### Type of issue

Missing information

### Description

There's a section on **reactredux** but the template isn't actually listed nor available.  If the template is no longer available, then the section should be removed.  Thanks.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-sdk-templates.md

### Document Version Independent Id

af236ebe-5a79-fb2b-42a0-e5720ee732ae

### Article author

tdykstra

---
[Associated WorkItem - 180756](https://dev.azure.com/msft-skilling/Content/_workitems/edit/180756)

**Comment by tdykstra** [comment]
Thanks for pointing that out. I'm removing it from the docs, as it hasn't been available since .NET 6 SDK. You can, however, still use it if you install .NET 5 SDK.

**Comment by AYColumbia** [comment]
> Thanks for pointing that out. I'm removing it from the docs, as it hasn't been available since .NET 6 SDK. You can, however, still use it if you install .NET 5 SDK.

Great thanks.  Would you close this issue after the docs are updated please?  Thanks again.
