### ISSUE TITLE
Empty first line and wrong indention of first non-empty line in code blocks in System.Xml.Linq

### ISSUE THREAD

**Issue by mikkelbu** [dotnet/docs#3779]
Most of the code blocks under `System.Xml.Linq` start with an empty line which is then followed by a line which is indented with 16 spaces. This makes the resulting examples look somewhat strange. I propose to remove the empty line and the additional indentation from the second line.
See e.g. in https://github.com/dotnet/docs/blob/master/xml/System.Xml.Linq/XDeclaration.xml which contain code blocks such as
```csharp  
  
                XDocument doc = new XDocument(  
    new XDeclaration("1.0", "utf-8", "yes")
...
```
and
```xml  
  
                <?xml version="1.0" encoding="utf-8" standalone="yes"?>  
<!--This is a comment-->  
<Root>content</Root>  
```  
and 
```vb  
  
                Dim xd As XDeclaration = New XDeclaration("1.0", "utf-8", "yes")  
Console.WriteLine(xd.Version)  
Console.WriteLine(xd.Encoding)  
Console.WriteLine(xd.Standalone)  
  
```

**Comment by mairaw** [comment]
Thanks for your feedback @mikkelbu. I did notice this issue last week too while making some fixes. We'll fix it eventually.
