### ISSUE TITLE
API search results for immutable collections include raw [!INCLUDE[

### ISSUE THREAD

**Issue by svick** [dotnet/docs#3781]
When I [search for "immutabledictionary"](https://docs.microsoft.com/en-us/dotnet/api/?term=immutabledictionary), the result is:

![](https://user-images.githubusercontent.com/287848/33187931-d7d02434-d095-11e7-88a7-41779521beb6.png)

Especially notice how the description contains `[!INCLUDE[immutable_nuget_short](~/includes/immutable-nuget-short-md.md)]`.

I think there are two problems:

1. Code is not rendered properly. ``<see cref="T:System.Collections.Immutable.ImmutableDictionary`2" />`` should probably be rendered as `ImmutableDictionary<TKey, TValue>`, not as ``System.Collections.Immutable.ImmutableDictionary`2`` (since most people won't know what `` `2 `` means). And the `[!INCLUDE[` should be included.
2. The included note about NuGet package should not be part of the search results. I think that information is not useful when searching (but it's still useful to have it on the type page).

**Comment by mairaw** [comment]
Thanks @svick. We should not have includes as part of summaries.
