### ISSUE TITLE
Update Introduction to resilient app dev.

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#37834]
Update [Introduction to resilient app development](https://learn.microsoft.com/en-us/dotnet/core/resilience) content.

- [ ] Explain how enrichment happens: https://learn.microsoft.com/en-us/dotnet/core/resilience/?tabs=dotnet-cli#add-enrichment
- [ ] Add examples of each: https://learn.microsoft.com/en-us/dotnet/core/resilience/?tabs=dotnet-cli#resilience-pipeline-builder-extensions

---
[Associated WorkItem - 177626](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177626)

**Comment by martintmk** [comment]
Some additional notes:

- The `FailureResultContext` is gone.
- Would be good to actually include the enriched tag names.
