### ISSUE TITLE
DOTNET_SKIP_FIRST_TIME_EXPERIENCE was replaced by DOTNET_NOLOGO

### ISSUE THREAD

**Issue by am11** [dotnet/docs#37830]
[dotnet-environment-variables.md](https://github.com/dotnet/docs/blob/923b2a7dc5a9367fc8bf1067f16694416a12a9a8/docs/core/tools/dotnet-environment-variables.md) states the following:

> ### `DOTNET_SKIP_FIRST_TIME_EXPERIENCE`
>
> If `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` is set to `true`, the `NuGetFallbackFolder` won't be expanded to disk and a shorter welcome message and telemetry notice will be shown.

and

> ### `DOTNET_NOLOGO`
>
> Specifies whether .NET welcome and telemetry messages are displayed on the first run. Set to `true` to mute these messages (values `true`, `1`, or `yes` accepted) or set to `false` to allow them (values `false`, `0`, or `no` accepted). If not set, the default is `false` and the messages will be displayed on the first run. This flag does not affect telemetry (see `DOTNET_CLI_TELEMETRY_OPTOUT` for opting out of sending telemetry).

However, `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` was completely removed in https://github.com/dotnet/cli/pull/11029 (.NET Core 3.0) and `DOTNET_NOLOGO` was reintroduced as its replacement in .NET Core 3.1 to only suppress the FTUE message (https://github.com/dotnet/cli/pull/13275).

We should update the docs to reflect that `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` has no meaning in currently supported versions of .NET.

cc @ViktorHofer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1fab316-eb04-50f5-03c8-bf3004981d3e
* Version Independent ID: 0c8e3542-470a-fa11-0d27-061384c4c3ba
* Content: [.NET environment variables - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables)
* Content Source: [docs/core/tools/dotnet-environment-variables.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-environment-variables.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BartoszKlonowski** [comment]
@ViktorHofer Don't mind me asking, please, but are you about to launch a PR for this? Or is it available for me to take?

**Comment by ViktorHofer** [comment]
Feel free to send a PR. I'm not planning to work on this.
