### ISSUE TITLE
GetEncoder

### ISSUE THREAD

**Issue by EdwardLarrabee** [dotnet/docs#37858]
### Type of issue

Missing information

### Description

Various topics reference "GetEncoder", implying that it is .Net function. However, it is a code sample. Good luck finding this sample.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/?redirectedfrom=MSDN

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/index.md

### Document Version Independent Id

1a3b2f58-bd54-45af-2f58-1cfb205d0657

### Article author

KathleenDollard

**Comment by BillWagner** [comment]
None of the Visual Basic articles still include the "GetEncoder" sample.

Closing.
