### ISSUE TITLE
Clarify that `in` reference arguments are not boxed

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3786]
Responding to a customer question on [Reference semantics with value types](https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types)  

Are value types passed by reference boxed? They are not, and that should be clarified.  

The same clarification should be added for ref return as well.

**Comment by bbarry** [comment]
I don't understand how boxing has anything to do with parameters. Am I misunderstanding something? 

The documentation could be perhaps more clear on parameter passing conventions and exactly what `ref` does and maybe link to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/structs and better explain why `in` has a temporary variable that it gets copied to unless you have a `readonly struct` type.

**Comment by BillWagner** [comment]
@bbarry You are understanding correctly. Boxing doesn't apply.

I'd like to drill down more into this comment: 

> better explain why `in` has a temporary variable that it gets copied to unless you have a `readonly struct` type.

That sentence overstates when a temporary is needed. (It's only needed when you pass a ref by `in` *and* it's not a `readonly struct` type *and* the called method calls a member method of the struct type (which may change its internal state).

Did we mislead you?
Did we not explain it very well at all?

Once you clarify, I'll make updates.
