### ISSUE TITLE
documentation of publishing docker-image should not use obsolete ContainerImageName

### ISSUE THREAD

**Issue by TomasEkeli** [dotnet/docs#37866]
### Type of issue

Typo

### Description

[Enter feedback here]
The "ContainerImageName" -property is obsolete, and "ContainerRepository" should be used instead.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
Fixed by #39072
