### ISSUE TITLE
What to migrate to from BinaryFormatter

### ISSUE THREAD

**Issue by deastr** [dotnet/docs#37867]
### Type of issue

Missing information

### Description

The article dictates that we should migrate away from BinaryFormatter but it doesn't clarify what the alternatives are. For example, Redis clients accept binary data and BinaryFormatter could be used for this purpose. It'd be great addition to include what could be used instead.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/binaryformatter-disabled

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/serialization/8.0/binaryformatter-disabled.md

### Document Version Independent Id

5048d220-6e5c-3130-b1db-ead1efbf7c36

### Article author

gewarren

**Comment by gfoidl** [comment]
The article links to [Recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/binaryformatter-serialization-obsolete#recommended-action):

> Stop using [BinaryFormatter](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) in your code. Instead, consider using [JsonSerializer](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) or [XmlSerializer](https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer).

Though, that information could be displayed more prominently.

> Redis clients accept binary data

Maybe protobuf, MessagePack, etc. should be mentioned too? Especially for the "binary data" case.

**Comment by deastr** [comment]
> The article links to [Recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/binaryformatter-serialization-obsolete#recommended-action):
> 
> > Stop using [BinaryFormatter](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) in your code. Instead, consider using [JsonSerializer](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) or [XmlSerializer](https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer).
> 
> Though, that information could be displayed more prominently.
> 

The thing is that they are JSON or XML serializers they don't convert objects to binary data directly like BinaryFormatter. There's a [BinaryData](https://learn.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-7.0) class but I don't know if it's recommended.

**Comment by gewarren** [comment]
I will add a link to this article, which lists the alternatives: https://learn.microsoft.com/dotnet/standard/serialization/binaryformatter-security-guide#preferred-alternatives.
