### ISSUE TITLE
Reorder H2's: Move windows only to bottom

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#37880]
This PR is to prep for #37878 so the #37878 PR will be more productive. ie, the diff file won't be so massive with the moved sections. Happy to roll this into one PR if that's preferred.

Currently the H2's list Windows only incompatibilities. I propose changing the order to first show limitations on all platforms, then windows. I propose the following ordering:

#### Windows Forms

------------------------------

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/deploying/trimming/incompatibilities.md

### Document Version Independent Id

44a05400-ca81-d38e-1ce6-b54a9036621e

### Article author

agocke

**Comment by Rick-Anderson** [comment]
@mitchdenny  @eerhardt @brunolins16 @radical @vargaz please review this and #37878

**Comment by mitchdenny** [comment]
Where is the PR?
