### ISSUE TITLE
View example

### ISSUE THREAD

**Issue by gentiliPaolo** [dotnet/docs#37933]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/inheritance

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/inheritance.md

### Document Version Independent Id

2183c2c7-5a9d-716e-34c3-b28d76a88b4c

### Article author

BillWagner

**Comment by BillWagner** [comment]
Closing due to blank description.
