### ISSUE TITLE
Add "Configuration-binding source generator" to this doc

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#37981]
### Type of issue

Typo

### Description

[Configuration-binding source generator](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#configuration-binding-source-generator)

I need to link to that section in this repo and the asp.net core  repo and don't like linking to a WN doc. Folks in .NET 11 won't think to look in WN 8.

I'm happy to do the work if it's pretty much copy/paste.

Update the link in [Known trimming incompatibilities](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities)
see #37912

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md

### Document Version Independent Id

0d5de37c-8f89-b6a5-3132-2c5214196bfd

### Article author

IEvangelist

**Comment by Rick-Anderson** [comment]
Dup of https://github.com/dotnet/docs/issues/36939#issuecomment-1707641504

**Comment by Rick-Anderson** [comment]
@IEvangelist  @layomia  I think I should probably reopen this and get this part done this week rather than wait on #36939 which is more extensive.

**Comment by IEvangelist** [comment]
> @IEvangelist @layomia I think I should probably reopen this and get this part done this week rather than wait on #36939 which is more extensive.

Why not use this issue instead? #36939
