### ISSUE TITLE
Why does Transient work best for lightweight, stateless services?

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#37992]
### Type of issue

Other (describe below)

### Description

For [Transient](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection?source=docs#transient), the article states that:

> Transient lifetime services are created each time they're requested from the service container. This lifetime works best for lightweight, stateless services.

This leads users to think every stateless service should be transient even when they are part of a large chain of dependencies.

See https://github.com/DuendeSoftware/Duende.AccessTokenManagement/issues/51

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection?source=docs#transient

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection.md

### Document Version Independent Id

cc5f00d0-fb50-1229-8fa2-e66b1f45b284

### Article author

IEvangelist

**Comment by IEvangelist** [comment]
Sorry, @paulomorgado - I've been buried with .NET Aspire lately, see #40022.

**Comment by paulomorgado** [comment]
From @davidfowl's comment on https://github.com/DuendeSoftware/Duende.AccessTokenManagement/issues/51#issuecomment-1849696357

ASP.NET Core uses singletons by default for most things. We avoid per request allocations where possible. There are a few scoped services and objects created per request in a few places where customers need to inject their own scoped instances, but for the most part, it's singletons everywhere.

**Comment by davidfowl** [comment]
Transient is a safe default for most use cases (that don't require extreme performance). If you're trying to reduce allocations and optimize, then looking at moving more stateless services to singletons is a fine task. This is a more advanced doc (maybe under a performance considerations category). I wouldn't change the default guidance.

**Comment by paulomorgado** [comment]
I think everything should be clearly stated to avoid someone following the wrong advice.

If you're writing your own application, it's under your control to decide and correct.

If it's a library you're using, you are not in control. But it can negativelly impact your system. Imagine if someone registered a logger as transient?
