### ISSUE TITLE
#include <iostream>

### ISSUE THREAD

**Issue by shimiro** [dotnet/docs#38006]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1024?f1url=%3FappId%3Droslyn%26k%3Dk(CS1024)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1024.md

### Document Version Independent Id

f38287f8-ed77-2147-7935-a981be58dd15

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @shimiro 

`#include` is not a valid C# directive. 

In .NET, you add referenced assemblies in the project build file, and you import the namespaces with a `using` statement.

I'll close this as an answered question
