### ISSUE TITLE
can you fix the problem to convert int to string

### ISSUE THREAD

**Issue by ponpawe** [dotnet/docs#38002]
### Type of issue

Missing information

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1503.md

### Document Version Independent Id

66121850-861c-9e37-27f0-811f80427d70

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @ponpawe 

The best way to convert an `int` to a `string` is to call the `ToString()` method on the int type.

If that doesn't solve your issue, I'd post a small sample with a question to our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site.

I'll close this as an answered question.
