### ISSUE TITLE
It's not called MSIL, anymore, is it ?

### ISSUE THREAD

**Issue by entvex** [dotnet/docs#38005]
### Type of issue

Other (describe below)

### Description

Dear DotNet Team,
I may have found an issue with the docs.

In the article, it says

> The actual field names are valid MSIL identifiers, but not valid C# identifiers.

But I think MSIL is the old term for Common Intermediate Language (CIL). On Wikipedia, it is also referred to as [formerly called](https://en.wikipedia.org/wiki/Common_Intermediate_Language)

If you agree, I would be happy to provide a pull request changing it to 
"The actual field names are valid CIL identifiers, but not valid C# identifiers."

Sincerely
Entvex

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/primary-constructors.md

### Document Version Independent Id

a22d366b-380f-f701-6a01-2515433e1550

### Article author

BillWagner

**Comment by BillWagner** [comment]
Thanks for spotting and reporting this.

Yes. "CIL" is the better term. I'll assign this to you, and watch for a PR.

**Comment by entvex** [comment]
Here you go @BillWagner https://github.com/dotnet/docs/pull/38010

Sincerely
Entvex
