### ISSUE TITLE
The model for the report output version 1

### ISSUE THREAD

**Issue by Marusyk** [dotnet/docs#38022]
### Type of issue

Other (describe below)

### Description

> --output-version <VERSION>
> 
> Sets the report output version. Allowed value is 1. Defaults to 1. Requires the --format json option. When a new JSON version is available, the command will produce the new format by default. This option will let you specify that the command should produce an earlier format. Available starting in .NET SDK 7.0.200.

Can someone help me find the model for the report output version 1? Is it somewhere on the GutHub?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-list-package.md

### Document Version Independent Id

3d4b052c-33fa-cc83-4df6-4a3341f12763

### Article author

tdykstra

---
[Associated WorkItem - 183672](https://dev.azure.com/msft-skilling/Content/_workitems/edit/183672)

**Comment by tdykstra** [comment]
The answer is [here](https://github.com/dotnet/docs/pull/32855#issuecomment-1816798294).

**Comment by Marusyk** [comment]
@tdykstra thanks but
![image](https://github.com/dotnet/docs/assets/9221694/b8b35aac-5a13-4f0d-99d7-77ffa9fe92d4)
