### ISSUE TITLE
Another fix that often works when attempting to resolve cs0518

### ISSUE THREAD

**Issue by MatthewHessCygrp** [dotnet/docs#38028]
### Type of issue

Missing information

### Description

Unloading and reloading the project in Visual Studio solves this problem for me every time I get it. It might be good to mention this technique in the article.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0518?f1url=%3FappId%3Droslyn%26k%3Dk(CS0518)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0518.md

### Document Version Independent Id

1837c5b3-d5bb-7937-5a8d-b157df244424

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @MatthewHessCygrp 

I hesitate to add this to the docs. It works sometimes because Visual Studio has gotten in a bad state, and may not have correctly loaded all its components. 

I'm going to close this.
