### ISSUE TITLE
i cant fucking find it

### ISSUE THREAD

**Issue by martinbatrus27sthurmizdcom** [dotnet/docs#38030]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md

### Document Version Independent Id

1850602d-6b92-1449-c8bd-116e36fc0f26

### Article author

adegeo

**Comment by BillWagner** [comment]
closing as a CoC violation.
