### ISSUE TITLE
What's new in F# 6 is still the last update for F#.

### ISSUE THREAD

**Issue by pjmlp** [dotnet/docs#38050]
### Type of issue

Missing information

### Description

On the week .NET 8 is going to be released, there is still no documentation available for "What's new in F# 7", and most likely also "What's new in F# 8" won't be available, meanwhile [What's new in C# 12](https://learn.microsoft.com/en-gb/dotnet/csharp/whats-new/csharp-12) is already available.

This doesn't help with the public image that only C# matters.

### Page URL

https://learn.microsoft.com/en-gb/dotnet/fsharp/whats-new/fsharp-6

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/whats-new/fsharp-6.md

### Document Version Independent Id

885f9f09-d2ff-112c-6dda-9a31bccc0e8a

### Article author

cartermp

**Comment by BillWagner** [comment]
No longer relevant. There are articles through F# 9.
