### ISSUE TITLE
.Net 8.0 install is not installing latest SDK

### ISSUE THREAD

**Issue by wgrs** [dotnet/docs#38062]
### Type of issue

Outdated article

### Description

Running sudo apt-get install -y dotnet-sdk-8.0 is installing 8.0.100-rc.2.23502.1 [/usr/lib/dotnet/sdk]

### Page URL

https://learn.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu-2304

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2304.md

### Document Version Independent Id

c43f280d-ee30-6092-b48c-93b58eb1dea1

### Article author

adegeo

**Comment by adegeo** [comment]
Hello. It may take time for packages to show up in the distro feeds. If you're using the Microsoft feed, I've verified it is in the feed, you may just need to update your feed data.
