### ISSUE TITLE
New topic about API Analyzer

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3807]
Background info: https://blogs.msdn.microsoft.com/dotnet/2017/10/31/introducing-api-analyzer/

/cc @terrajobst

**Comment by rpetrusha** [comment]
@mairaw, I added a priority (P0), since I think that this topic is really important for porting. Feel free to change it if you disagree.

**Comment by terrajobst** [comment]
@OliaG, please work with @rpetrusha and @mairaw so this gets documented :-)

**Comment by mairaw** [comment]
That's fine @rpetrusha. Especially because we won't be able to document all API compat and PNSE exceptions soon, so telling people about the analyzer would help.

**Comment by mairaw** [comment]
@OliaG you're going to do this one right? Any idea when you'd like to address it? Then I can add the appropriate milestone.

**Comment by OliaG** [comment]
Yes, I'm on it. Will do it this week.
