### ISSUE TITLE
Add .Net 8 -> C# ??? version

### ISSUE THREAD

**Issue by jeroenhabets** [dotnet/docs#38077]
### Type of issue

Outdated article

### Description

Update table under Defaults by adding .Net 8
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md

### Document Version Independent Id

3f01c378-22e4-197c-a862-ab4a924506c7

### Article author

BillWagner

**Comment by BillWagner** [comment]
Thanks for pointing this out @jeroenhabets 

I opened #38255 to fix this.
