### ISSUE TITLE
dotnet binary showing the wrong version

### ISSUE THREAD

**Issue by mishra14** [dotnet/docs#3818]
_From @mishra14 on November 28, 2017 23:5_

## Steps to reproduce
1. download binary from [here](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.3-windows-x64-binaries)
2. run `dotnet --info`

## Expected  behavior
```
.NET Command Line Tools (2.0.3)
```

## Actual behavior
```
F:\validation\test> . "C:\Users\anmishr\Downloads\dotnet-runtime-2.0.3-win-x64\dotnet.exe" --info
.NET Command Line Tools (2.1.1)

Product Information:
 Version:            2.1.1
 Commit SHA-1 hash:  436d56176b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

I think the exe is picking up the same version on my machine irrespective of the `dotnet.exe` being executed.

_Copied from original issue: dotnet/cli#8126_

**Comment by mishra14** [comment]
cc @livarcocc

**Comment by mishra14** [comment]
_From @dasMulli on November 28, 2017 23:24_

Looks like [multi-level lookup](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md) discovering a globally installed SDK. Does it change when you set the environment variable `DOTNET_MULTILEVEL_LOOKUP` to `0`/`false`?

**Comment by mishra14** [comment]
@dasMulli  That was it. Thanks!
Is it documented? If so I might have missed it. Else it should be.

**Comment by mishra14** [comment]
_From @livarcocc on November 28, 2017 23:49_

I am not sure where you mean to document this. Do you mean docs.microsoft.com? If so, I would file an issue a dotnet/docs to add this there.

**Comment by mishra14** [comment]
Since this does not happen when i download binaries from the readme, we shouldn't need to add this to the repo readme. 
I think having a pointer on the docs page would be nice. I will move this issue there.

**Comment by mishra14** [comment]
Moving here based on recommendation from @livarcocc 

The core problem is that the downloads page should have a heads up for binary consumers that this may not work will you set `$env:DOTNET_MULTILEVEL_LOOKUP` to `$False` (powershell).

**Comment by mairaw** [comment]
@livarcocc 
when was this environment variable introduced? I'll add this to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?#environment-variables. PowerShell is just one way of setting the environment variable.

Do we also need an in-depth article on this multi-level lookup feature?

@mishra14 what you mean by downloads page? You mean on the dot.net site?

**Comment by livarcocc** [comment]
This was introduced in the 2.0 host at the request of the ASP.NET team.

cc @johnbeisner

**Comment by mairaw** [comment]
@livarcocc are we missing other env variables? I'm seeing a couple being used in the CLI repo that are not in the docs:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE
- DOTNET_INSTALL_DIR
- DOTNET_BUILD_SKIP_PACKAGING
- DOTNET_CLI_TELEMETRY_SESSIONID
- DOTNET_CLI_UI_LANGUAGE
- DOTNET_RUNTIME_ID

do I need to document these too?

anything else?

/cc @KathleenDollard

**Comment by steveharter** [comment]
Yes the `DOTNET_MULTILEVEL_LOOKUP` was added about a year ago for the 2.0 release - https://github.com/dotnet/core-setup/pull/1241

The multi-level feature is documented at https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md however that specific variable is not documented there.

**Comment by mairaw** [comment]
Thaks @steveharter. I'm adding the  DOTNET_MULTILEVEL_LOOKUP variable to the docs with PR #3822. 

And what about the other env variables that I listed [above](https://github.com/dotnet/docs/issues/3818#issuecomment-347732803)? Any of those should be documented?

/cc @mishra14 @johnbeisner

**Comment by KathleenDollard** [comment]
Let's not document those environment variables (https://github.com/dotnet/docs/issues/3818#issuecomment-347732803) since they are used internally
