### ISSUE TITLE
List of supported operating systems per .NET Standard version

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#3823]
A list of supported operating systems for .NET Standard 2.0 would be very useful.
Similar like this: 
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

Would be useful to know which OS and Server OS versions are supported.

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @wstaelens.

The .NET implementations that support particular implementations of the .NET Standard is found at https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

The basic problem with listing operating systems supported by the .NET Standard is that it involves a level of indirection; the .NET Standard is a formal specification of APIs that individual .NET implementations must support, and these individual implementations in turn target specific platforms. In other words, the .NET Standard itself does not target platforms; it's merely a standard that the implementations which do target platforms must support. Libraries that target a specific version of the .NET Standard are assured that the APIs supported by the standard are present on target .NET implementations. The basis for determining what version of the .NET Standard a library should target is not the target operating system, but the set of APIs desired and the .NET implementations from which the library will be called.

I'm going to close this issue. Please let us know, however, if you disagree.
