### ISSUE TITLE
TerminalLogger guidance has incorrect syntax

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#38259]
### Type of issue

Typo

### Description

The usage for `dotnet build` shows the syntax for Terminal Logger as ` [--tl [auto|on|off]]`, but it currently needs to be ` [--tl=[auto|on|off]]` - note the replacement of space with equals. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md

### Document Version Independent Id

5e495ddd-140e-de5c-a793-d4a9f88be51e

### Article author

tdykstra

---
[Associated WorkItem - 183673](https://dev.azure.com/msft-skilling/Content/_workitems/edit/183673)

**Comment by baronfel** [comment]
@tdykstra is there a good snippet-style substitution mechanism in these docs? The syntax for `--tl` and the documentation section for it can actually be applied to a large number of commands:

* build
* clean
* msbuild
* restore
* pack
* publish

and it would suck to have to keep these all aligned :)

**Comment by tdykstra** [comment]
> is there a good snippet-style substitution mechanism

You can use an [include file](https://review.learn.microsoft.com/en-us/help/platform/includes-best-practices?branch=main).
We already do that for some options -- see the first three options in https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md#options 

```
[!INCLUDE [arch](https://github.com/dotnet/docs/blob/main/includes/cli-arch.md)]
[!INCLUDE [configuration](https://github.com/dotnet/docs/blob/main/includes/cli-configuration.md)]
[!INCLUDE [disable-build-servers](https://github.com/dotnet/docs/blob/main/includes/cli-disable-build-servers.md)]
```

**Comment by baronfel** [comment]
Oh that's perfect - I might take a stab at that.

**Comment by JeroenOortwijn** [comment]
> ### Description
> The usage for `dotnet build` shows the syntax for Terminal Logger as ` [--tl [auto|on|off]]`, but it currently needs to be ` [--tl=[auto|on|off]]` - note the replacement of space with equals.

From my research in https://github.com/dotnet/sdk/issues/36921#issuecomment-1814170480, it has to be a `:`, not a `=`:
```
C:\Users\Jeroen\Downloads\Test>dotnet publish --tl:on
MSBuild version 17.8.3+195e7f5a3 for .NET
Restore complete (0,4s)
  Test succeeded (0,2s) → bin\Release\net8.0\publish\

Build succeeded in 0,8s

C:\Users\Jeroen\Downloads\Test>dotnet publish --tl=on
MSBuild version 17.8.3+195e7f5a3 for .NET
MSBUILD : error MSB1001: Unknown switch.
    Full command line: 'C:\Program Files\dotnet\sdk\8.0.100\MSBuild.dll -maxcpucount -verbosity:m -restore -target:Publish --property:_IsPublishing=true -property:Configuration=Release --tl=on -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\8.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\8.0.100\dotnet.dll'
  Switches appended by response files:
Switch: --tl=on

For switch syntax, type "MSBuild -help"
```
