### ISSUE TITLE
dotnet new list command is incorrect

### ISSUE THREAD

**Issue by rickhodder** [dotnet/docs#38261]
### Type of issue

Typo

### Description

There is a line that says the command to list templates is dotnet new list
it should be dotnet new --list

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-sdk-templates.md

### Document Version Independent Id

af236ebe-5a79-fb2b-42a0-e5720ee732ae

### Article author

tdykstra

**Comment by adegeo** [comment]
Hi @rickhodder 

The documentation is correct for .NET 7 and .NET 8. The `--list` parameter is for .NET 6. Unfortunately these docs aren't versioned to give you a view of .NET 6. I don't know that doing so is a high priority, considering .NET 6 will be out of support next Novemeber.

Ping @tdykstra to comment.

**Comment by tdykstra** [comment]
There is a note in the Description section of the [dotnet new list](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-list) command documentation explaining the change that happened with .NET 7.

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
