### ISSUE TITLE
Rule "CA1863 Cache a 'CompositeFormat' for repeated use in this formatting operation" is missing a documentation page

### ISSUE THREAD

**Issue by MathieuSevegny** [dotnet/docs#38266]
### Type of issue

Missing information

### Description

After migrating a project from .Net 6 to .Net 8, I started to see the new code quality rule "CA1863". I wanted to see how to fix it and what is the reason behind this new rule.

The shown warning : 
![image](https://github.com/dotnet/docs/assets/55141786/dde44abb-59db-4076-93d2-ecf39ac106da)

I clicked on the code to open the documentation page and it showed me an error (404 - Page not found). 

The given URL : https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1863

The given error : 
![image](https://github.com/dotnet/docs/assets/55141786/aa5985fd-cb32-4dcf-92dc-c9f54603872f)

I suspect that the page wasn't writing yet because .Net 8 just launched.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules

### Content source URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1863.md

### Document Version Independent Id

507d7a47-c1b0-f708-f1fe-1088927110f6

### Article author

gewarren

**Comment by gewarren** [comment]
I have a PR #38344 to add both CA1862 and CA1863 that just needs to be reviewed and published.
