### ISSUE TITLE
.NET 8 shown as removing support for macOS ≥ 11 and only supporting 10.15

### ISSUE THREAD

**Issue by Aldaviva** [dotnet/docs#38275]
### Type of issue

Typo

### Description

Hello,

In the [Supported releases](https://learn.microsoft.com/en-us/dotnet/core/install/macos?#supported-releases) section, this article claims that while .NET 6 and 7 support macOS ≥ 10.15, .NET 8 supports macOS 10.15 **only**, while 11, 12, and 13 are unsupported.

![image](https://github.com/dotnet/docs/assets/1417794/e30cbb4b-2b82-435b-9c35-d9a85198a310)

I think this is wrong because
1. it doesn't make sense to only support the older (2019) OS with the newest runtime
2. the [.NET 8 Supported OS Policy](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos) shows that "macOS 10.15+" is supported
3. a [previous commit](https://github.com/dotnet/docs/commit/2d05ee571583623f4669760d53e0588b52debfab#diff-96a024b4a6a59e7abfcbdbff178c7f75257d0d4cd9e283b207b44b5b9120e9d9L30-R35) to this article showed that macOS ≥ 10.15 was supported, but this was changed in a [subsequent commit](https://github.com/dotnet/docs/commit/784159c3b46db3cfea2b14ded883e25d6c2d1a84#diff-96a024b4a6a59e7abfcbdbff178c7f75257d0d4cd9e283b207b44b5b9120e9d9L32-R34)

I didn't see any explanation for this removal in the issue or pull request descriptions, but I also don't have access to view the associated Azure DevOps issue to see if there was a reason in there, so I may be missing some information here.

---

Separately, the newest macOS version is currently [14 (Sonoma)](https://en.wikipedia.org/wiki/MacOS_Sonoma) instead of 13 (Ventura), and should probably be added to this article.

Thanks!

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/macos#supported-releases

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/macos.md

### Document Version Independent Id

68d524f7-6cf1-2caa-56d5-f243952d1526

### Article author

adegeo

### Metadata

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Thank you for reporting this! The fixed version should be available soon.
