### ISSUE TITLE
EventLog name and source can not be set from appsettings.json

### ISSUE THREAD

**Issue by MikeCley** [dotnet/docs#38282]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
It is known closed bug https://github.com/dotnet/runtime/issues/47303
appsettings.json
`"Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      },
      "LogName": "D-574E-Reports.DataTransfer",
      "SourceName": "D-574E-Reports.DataTransfer.WorkerService"
    },
    "Console": {
      "IncludeScopes": true
    }
  },`

should be replaced with something like 

`builder.Logging.AddEventLog(eventLogSettings =>
{
    eventLogSettings.LogName = "D-574E";
    eventLogSettings.SourceName = "D-574E-Reports.DataTransfer";
});`

in windows service creation sequence.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service?pivots=dotnet-7-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md

### Document Version Independent Id

64d5cdf8-e50f-0c89-7f16-82645ba6383e

### Article author

@IEvangelist

### Metadata

* ID: ed148088-4550-2788-0756-390eab15e3f6 
* Product: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
This isn't an issue, I just confirmed that this works as expected and that the op either didn't follow the code provided or since it's a bit older hasn't tried recently... This works as expected, and the _Program.cs_ has what it needs:

```cs
using App.WindowsService;
using Microsoft.Extensions.Logging.Configuration;
using Microsoft.Extensions.Logging.EventLog;

HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);
builder.Services.AddWindowsService(options =>
{
    options.ServiceName = ".NET Joke Service";
});

LoggerProviderOptions.RegisterProviderOptions<
    EventLogSettings, EventLogLoggerProvider>(builder.Services);

builder.Services.AddSingleton<JokeService>();
builder.Services.AddHostedService<WindowsBackgroundService>();

IHost host = builder.Build();
host.Run();
```
