### ISSUE TITLE
Jammy feed doesn't include dotnet8 as documented

### ISSUE THREAD

**Issue by ricksanchez-abb** [dotnet/docs#38297]
### Type of issue

Typo

### Description

https://packages.ubuntu.com/jammy/allpackages doesn't list dotnet8, however this document https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204 indicates it is available.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2304

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2304.md

### Document Version Independent Id

c43f280d-ee30-6092-b48c-93b58eb1dea1

### Article author

adegeo

### Metadata

* ID: 34568c80-c10f-6f50-f7f7-a0bf8eab1408 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Thanks for reporting this. I thought it was supposed to be in there but I guess it's not. I'll remove it and then ask around if it's planned.

**Comment by adegeo** [comment]
Fixed by #38340
