### ISSUE TITLE
Some tables are too large and don't offer a way to scroll sideways and see data

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/docs#3831]
I tried with 4 different browsers, none of them would let me see the right side of the table located at https://docs.microsoft.com/en-us/dotnet/standard/collections/

![sad](https://user-images.githubusercontent.com/7574801/33399001-be189e08-d505-11e7-9a58-927a19bed716.JPG)

**Comment by mairaw** [comment]
Thanks for filing this issue. I can repro that @BrennanConroy. Let me see if I can change a few things in this topic to no longer have that problem. Otherwise, we might have to come up with a different layout for that data.

**Comment by mairaw** [comment]
@adkinn is there anything that can be done on the docs site as well to allow tables to scroll? 
If you look at GitHub preview, that table does have a scrollbar: https://github.com/dotnet/docs/blob/master/docs/standard/collections/index.md#choosing-a-collection
