### ISSUE TITLE
Installation location changed with .net8

### ISSUE THREAD

**Issue by Zigby** [dotnet/docs#38314]
### Type of issue

Typo

### Description

Documentation states that dotnet is install to the normal /usr/local/share/dotnet/ on arm based macs (which was true until .net8, but now installs to $HOME/dotnet), but also says that $HOME/dotnet should be added to path, but $HOME on mac is the /Users/{UserName} folder.
Seem to be an inconsistency here? Why the change of install location?
How to use dotnet 7 and and dotnet 8 at the same time when these are installed into different locations?

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/macos?source=docs

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/macos.md

### Document Version Independent Id

68d524f7-6cf1-2caa-56d5-f243952d1526

### Article author

@adegeo

### Metadata

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

---
[Associated WorkItem - 185529](https://dev.azure.com/msft-skilling/Content/_workitems/edit/185529)

**Comment by adegeo** [comment]
I'm not totally sure what's going on. I'll look into the docs, but as to if the pkg file changed its install location, that would be a product problem. My preview versions of .NET 8 installed to where the article says it should. But I've not upgraded yet. I'll upgrade and see what I run into.

Can you give me some more information?

- What does `dotnet --info` say?
- Can you run that command from the different directories you have dotnet and provide the output?
- What installer did you download?
- What macOS are you running and what CPU architecture are you running on?
