### ISSUE TITLE
Missing .net 8 packages in .net package list

### ISSUE THREAD

**Issue by Scorpoon** [dotnet/docs#38317]
### Type of issue

Missing information

### Description

Following .net 8 packages are missing under the "Install .NET" headline:

- 8.0 ASP.NET Core Runtime aspnetcore-runtime-8.0
- 8.0 .NET Runtime dotnet-runtime-8.0
- 8.0 .NET SDK dotnet-sdk-8.0

Here are the missing html table rows:
```
<tr>
<th scope="row">8.0</th>
<td>ASP.NET Core</td>
<td>Runtime</td>
<td><code>aspnetcore-runtime-8.0</code></td>
</tr>
<tr>
<th scope="row">8.0</th>
<td>.NET</td>
<td>Runtime</td>
<td><code>dotnet-runtime-8.0</code></td>
</tr>
<tr>
<th scope="row">8.0</th>
<td>.NET</td>
<td>SDK</td>
<td><code>dotnet-sdk-8.0</code></td>
</tr>
```

### Page URL

https://learn.microsoft.com/de-de/dotnet/core/install/linux-ubuntu

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Thank you for reporting this. I'm working on this article today to fix up some things, but it seems your issue is related to the translated article not updating with the latest information. I'm not totally sure what to do about that, so I'll ask around.

**Comment by adegeo** [comment]
Whoops, this was linked to the wrong PR. The translation system goes on a schedule, but I don't know what it is. It's probably once a week.
