### ISSUE TITLE
Platform version no longer optional

### ISSUE THREAD

**Issue by monty241** [dotnet/docs#38322]
### Type of issue

Missing information

### Description

Regarding:

> You can also specify an optional OS version at the end of an OS-specific TFM, for example, net6.0-ios15.0.

When publishing through NuGet, the version is no longer optional, otherwise a NU1012 occurs. See https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1012

Suggestion is to add some samples like net6-windows10.0.17763.0. Values are available for example on target framework 6 console app -> target os -> windows -> target os version.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/frameworks#os-version-in-tfms

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/frameworks.md

### Document Version Independent Id

4352856b-5ccf-8e62-48b4-3151340cac56

### Article author

@gewarren

### Metadata

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb 
* Product: **dotnet**
* Technology: **dotnet-standard**

**Comment by gewarren** [comment]
@monty241 While the target platform version is required by NuGet, it is still optional in project files. If it's not specified, it's added by the .NET SDK before being passed to NuGet ([the article states this too](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#os-version-in-tfms)). So I don't think there are any changes needed to this article.
