### ISSUE TITLE
Article is missing source code for Chunk class

### ISSUE THREAD

**Issue by mrkaarel** [dotnet/docs#38330]
### Type of issue

Missing information

### Description

Currently no source code for *Chunk* class is present in the article. It was there before but seems to be accidentally left out by changes of [commit 6d40b3d7](https://github.com/dotnet/docs/commit/6d40b3d7c54dcae3a7622dd8cc54868e69b088e6).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/group-results-by-contiguous-keys

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/group-results-by-contiguous-keys.md

### Document Version Independent Id

8ffa29aa-af74-9f39-7e6c-04fd46538177

### Article author

BillWagner

### Metadata

* ID: eacf9e34-5e7f-37f4-24ad-1dd66fbabb9f 
* Product: **dotnet-csharp**
* Technology: **csharp-linq**

---
[Associated WorkItem - 185306](https://dev.azure.com/msft-skilling/Content/_workitems/edit/185306)

**Comment by BillWagner** [comment]
Thanks @mrkaarel 

I just submitted a PR to address this.
