### ISSUE TITLE
documentation page for IDE0300 code-style rule is missing

### ISSUE THREAD

**Issue by jjanuszkiewicz** [dotnet/docs#38347]
### Type of issue

Missing information

### Description

The new IDE0300 rule has no documentation page - the URL opened by VS when clicking the rule is a 404: [https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300).

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/index.md

### Document Version Independent Id

6d91b560-c12f-6e6d-e92b-1babb27edb67

### Article author

gewarren

### Metadata

* ID: b0a396c1-9c21-75a9-70b5-799cafc941b5 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 189680](https://dev.azure.com/msft-skilling/Content/_workitems/edit/189680)

**Comment by gewarren** [comment]
PR that introduced the analyzer is here: https://github.com/dotnet/roslyn/pull/69118
