### ISSUE TITLE
Mention the breaking change introduced in ASP.NET Core 8 regarding minimal API endpoints with an `IFormFile` parameter

### ISSUE THREAD

**Issue by aradalvand** [dotnet/docs#38354]
### Type of issue

Missing information

### Description

https://github.com/dotnet/aspnetcore/pull/49233 introduced a breaking change that affected minimal API endpoints with an `IFormFile` or `IFormFileCollection` parameter — see [this](https://github.com/dotnet/aspnetcore/pull/49233#issuecomment-1816526681).

This should be [documented](https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0#aspnet-core) in the list of ASP.NET Core 8's breaking changes.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0#aspnet-core

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/8.0.md

### Document Version Independent Id

1dc7a986-52e6-3a88-0163-4a869afc75d3

### Article author

gewarren

### Metadata

* ID: 250b5b35-569a-c5fa-2bf8-9d951bc1bdb7 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@captainsafia Can you create a breaking change announcement for this if you agree?

**Comment by captainsafia** [comment]
Breaking change announcement: https://github.com/aspnet/Announcements/issues/509

**Comment by gewarren** [comment]
Documented here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/antiforgery-checks.
