### ISSUE TITLE
Seems impossible to create a disposable service not created by the service provider that take service provided by the service provider

### ISSUE THREAD

**Issue by MathieuGirard** [dotnet/docs#38357]
### Type of issue

Typo

### Description

[Enter feedback here]
See https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#services-not-created-by-the-service-container

Seem to be imposible:
Would need to be able to set a disposable from a lambda (not allowe by code validation) or dispose is not called..

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection-guidelines.md

### Document Version Independent Id

7fb2be80-cb54-27bf-4f93-423d8540429e

### Article author

IEvangelist

### Metadata

* ID: 8d1c8ef1-6a01-df24-34ad-570f88df9303 
* Product: **dotnet-fundamentals**

**Comment by MathieuGirard** [comment]
Ex:
builder.Services.Addsingleton<IDisposableSingleton>(c => new DisposableSingleton(c.GetRequiredService<RequiredService>()));
Wont be disposed as per documented. But to change to code to dispose at application exit we would need to infringe code validation (set a disposable variable afterward).

**Comment by MathieuGirard** [comment]
Work around:
DisposableSingleton? singleton = null;
builder.Services.Addsingleton(c =>singleton =  new DisposableSingleton(c.GetRequiredService()));
[...]
singleton?.Dispose();

n.b. in our use case because of a bug in the resource used we need to insure the new DisposableSingleton(c.GetRequiredService() is done in a perculiar way (in the correct conetxt and thread).

**Comment by IEvangelist** [comment]
This is something that might have changed, as the dependency injection bits have evolved over the years. It might no longer be possible, let's double check with @eerhardt as he might know.

Here's my app I just put together, starting the _*.csproj_:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

</Project>
```

Here's the `Program.cs`:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddSingleton(static provider =>
{
    var factory = provider.GetRequiredService<ILoggerFactory>();

    return new DisposableService(factory.CreateLogger<DisposableService>());
});

using var host = builder.Build();

// Get the service to ensure it's created.
_ = host.Services.GetRequiredService<DisposableService>();

host.Run();

public sealed class DisposableService : IDisposable
{
    private readonly ILogger<DisposableService> _logger;

    public DisposableService(ILogger<DisposableService> logger)
    {
        _logger = logger;
        _logger.LogInformation("I was created...");
    }

    void IDisposable.Dispose()
    {
        _logger.LogInformation("I was disposed of...");
    }
}
```

Console output:

```output
info: DisposableService[0]
      I was created...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\source\repos\ConsoleApp5\bin\Debug\net8.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: DisposableService[0]
      I was disposed of...
```

**Comment by IEvangelist** [comment]
Ah, this is specifically about the `object` API, not the one I just displayed, consider the following:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddSingleton(new DisposableService());

using var host = builder.Build();

// Get the service to ensure it's created.
_ = host.Services.GetRequiredService<DisposableService>();

host.Run();

public sealed class DisposableService : IDisposable
{
    public DisposableService()
    {
        Console.WriteLine("I was created...");
    }

    void IDisposable.Dispose()
    {
        Console.WriteLine("I was disposed of...");
    }
}
```

The output is:

```
I was created...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\source\repos\ConsoleApp5\bin\Debug\net8.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

> [!IMPORTANT]
> It is NOT disposed of.

I'm going to close this issue as the docs are correct, and it is possible.
