### ISSUE TITLE
Anonymous type accros assembly

### ISSUE THREAD

**Issue by oli-unreal** [dotnet/docs#38353]
### Description

I don't know if it is a bug or the [doc](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/anonymous-types)  that doesn't make it obvious. If I create 2 anonymous objects in 2 assemblies, the equals is always false, but the `obj1.ToString().Equals(obj2.ToString())` returns true.

After reading the doc multiple times, it may be the expected behaviour:

> If two or more anonymous object initializers in an assembly specify a sequence of properties that are in the same order and that have the same names and types, the compiler treats the objects as instances of the same type. They share the same compiler-generated type information.

And several paragraphs below:

> Because the [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals) and [GetHashCode](https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode) methods on anonymous types are defined in terms of the Equals and GetHashCode methods of the properties, two instances of the same anonymous type are equal only if all their properties are equal.

I think `the same anonymous type` should be more explicit especially when we are talking about comparison. It should at least said that it is required to be in the same assembly.

### Reproduction Steps

I created an anonymous object to post a JSON via PostAsJsonAsync and in the test assembly with Moq I wanted to intercept the call with the right object.

### Expected behavior

Anonymous objects should be equal if all their properties are equal regardless of the assembly it is created on.

### Actual behavior

Comparison requires to be on the same assembly.

### Regression?

No

### Known Workarounds

Use string to do the comparison...
`obj1.ToString().Equals(obj2.ToString())`

### Configuration

.Net 7, x64

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b30ebe-b640-449b-3602-9891a55794db
* Version Independent ID: dd937177-98f0-a797-d49b-29332aae0614
* Content: [Anonymous Types - C#](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/anonymous-types)
* Content Source: [docs/csharp/fundamentals/types/anonymous-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/anonymous-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The doc infers the behavior, but we should make it clear by stating that anonymous types have `internal` accessibility.

This would make it more clear that types with the same "shape" but defined in different assemblies aren't the same type. Therefore instances of those two types can't be equal to each other.

**Comment by svick** [comment]
> The doc infers the behavior, but we should make it clear by stating that anonymous types have `internal` accessibility.

Wouldn't that imply that anonymous types can be shared between assemblies using `InternalsVisibleTo`?
