### ISSUE TITLE
Update library guidance to ensure references to recommended TFMs is up to date with supported versions of .NET

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs#38407]
### Type of issue

Outdated article

### Description

Parts of this guidance refer to .NET 5.0 as an example minimum supported TFM to target libraries at, but .NET 5 is no longer supported. This should likely be updated to .NET 6.0

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#older-targets

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/library-guidance/cross-platform-targeting.md

### Document Version Independent Id

aff99d6b-9471-9277-160b-670ee8028b53

### Article author

JamesNK

### Metadata

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
This will be fixed by https://github.com/dotnet/docs/pull/38072. That PR is just waiting for a review so it can be merged.
