### ISSUE TITLE
Source Link should have more detailed information as it has unexpected consequences

### ISSUE THREAD

**Issue by ScarletKuro** [dotnet/docs#38404]
### Type of issue

Missing information

### Description

I want to mention this issues: https://github.com/dotnet/runtime/issues/95134, https://github.com/dotnet/sdk/issues/36885, https://github.com/dotnet/sdk/issues/34568, https://github.com/dotnet/sdk/issues/37158, https://github.com/dotnet/sdk/issues/37142, [stackoverflow](https://stackoverflow.com/questions/77050814/fileversioninfo-productversion-suddenly-contains-git-commit-hash)
As the issues show, the SourceLink adds commit hash to the product version. This might be unexpected because this wasn't included in .net 6 & 7.
For example my application extracts the product version and the commit hash wasn't expected, also we use product version for SCCM and the hash is also not desired.

My problem with the current documentation is that the SourceLink description is too vague, it doesn't say anything about the consequences, for example i did not know it includes commit hash to the product version. It also doesn't link to the sourcelink build properties, in my opinion `<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>` is hard to discover if you want everything to work as before.
Maybe it would make sense to add this information to the https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0 instead of the "What's new".

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-8.md

### Document Version Independent Id

b22cffcc-898f-a3cf-83f9-a3c7349a1b14

### Article author

gewarren

### Metadata

* ID: 9d8a154a-d129-7e5a-e2aa-8d1a720252c5 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 189675](https://dev.azure.com/msft-skilling/Content/_workitems/edit/189675)

**Comment by ScarletKuro** [comment]
Apparently there is this documentation https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link
But I don't understand why it's not listed in the overview https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0

**Comment by tpressley** [comment]
I feel like this should have been disabled by default. It had a lot of negative consequences in our system, including disabling our entire logging system because the version # was too long to insert into logs.

**Comment by ScarletKuro** [comment]
> Edit: I want to clarify our project files still target .NET 7.

Yes, if you target .net7 in TFM but build against net8 SDK, you still will be affected.

**Comment by gewarren** [comment]
@baronfel FYI

**Comment by WeihanLi** [comment]
> I feel like this should have been disabled by default

What about adding `<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>` for the target frameworks below .NET 8, then we would not break the project already using it for .NET 8 projects, though it's still a breaking-change

**Comment by thedarkfalcon** [comment]
Echoing everyone's comments here and in related threads, this is terrible behaviour to enable by default, especially when most .net8 documentation pages fail to mention it.
One of our newer projects is running .net8 which required .net8 to be installed on our Azure build agents, now to maintain functionality we now have to add <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>to hundreds (maybe even thousands) of csproj files.
Having this long version string breaks a lot of integrations with installer creators, deployment services, and artefact services. 
User experience for looking at these long version strings is also really bad, not that I think users should even be getting commit IDs etc told to them about the software they have. If MS really wanted to force this behaviour, it really shouldn't be in the version string property IMO.
