### ISSUE TITLE
`Microsoft.NET.Sdk.Web` include implicit using of `Microsoft.NET.Sdk`

### ISSUE THREAD

**Issue by vernou** [dotnet/docs#38414]
**Issue description**

For all SDKs, the directive **Implicit Using** include also the implicit namespace of `Microsoft.NET.Sdk`. But it's specify only for `Microsoft.NET.Sdk.WindowsDesktop` SDKs.

![image](https://github.com/dotnet/docs/assets/1659796/c6492af7-9e72-42c5-a2df-7643dd7af8ef)

I expect the documentation to be consistent, so all SDKs specify that include also implicit namespace of `Microsoft.NET.Sdk`.

---

I will be happy to help by making a pull request.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET project SDK overview](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#implicit-using-directives)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/overview.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@vernou Sorry for the slow reply. Please go ahead with a PR if you still can!

**Comment by vernou** [comment]
@gewarren No problem, I do the PR #40302.
