### ISSUE TITLE
Fedora 39 doesn't find dotnet-sdk-8.0 with dnf search

### ISSUE THREAD

**Issue by renepanke** [dotnet/docs#38419]
### Type of issue

Code doesn't work

### Description

Neither `dnf search dotnet-sdk-8.0`  nor ` sudo dnf dotnet-sdk-8.0 --refresh` will find the package. ` sudo dnf makecache` doesn't resolve the problem as well as deleting the yum cache.

#### Fedora version
Fedora release 39 (Thirty Nine)

#### dnf version
4.18.1
  Installed: dnf-0:4.18.1-2.fc39.noarch at Do 23 Nov 2023 19:02:50 GMT
  Built    : Fedora Project at Mi 15 Nov 2023 15:14:30 GMT

  Installed: rpm-0:4.19.0-1.fc39.x86_64 at Mi 01 Nov 2023 01:06:57 GMT
  Built    : Fedora Project at Di 19 Sep 2023 13:02:12 GMT

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-fedora

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md

### Document Version Independent Id

2e9467f4-8572-c8e4-6a10-69faf14ce46c

### Article author

adegeo

### Metadata

* ID: 38a30294-c9ae-4189-26d7-ee7db615c487 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
@omajid is 39 supposed to have .NET 8? If so, is there an ETA?

**Comment by adegeo** [comment]
I'll add a note that says that the package will take time to appear.
