### ISSUE TITLE
Fix .Net "dotnet/standard repository" link on .Net Standard 

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/docs#3841]
Maybe there is an error on "https://docs.microsoft.com/en-us/dotnet/standard/net-standard" on paragraph https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md#official-artifacts the link "dotnet/standard repository" should be "https://github.com/dotnet/standard" instead of "https://github.com/dotnet/corefx/tree/master/src" if you agree i can fix and PR.

**Comment by mairaw** [comment]
Yes, I agree @MarcoRossignoli! This was an overlook on my part when updating the content a few months ago. Thanks for reporting and volunteering to fix the issue.
