### ISSUE TITLE
Missed no

### ISSUE THREAD

**Issue by sungam3r** [dotnet/docs#38424]
### Type of issue

Typo

### Description

keys are longer skipped should be changed to keys are no longer skipped

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/dictionary-configuration-binding

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/extensions/8.0/dictionary-configuration-binding.md

### Document Version Independent Id

7a3ede34-6427-72ea-bfc7-32c9060968be

### Article author

gewarren

### Metadata

* ID: 12edaf74-9c6e-5ace-0c10-d99913cd640e 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
Fixed in #38424
