### ISSUE TITLE
Secret convo

### ISSUE THREAD

**Issue by Unkwonperson134** [dotnet/docs#38427]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md

### Document Version Independent Id

1850602d-6b92-1449-c8bd-116e36fc0f26

### Article author

adegeo

### Metadata

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Hello. It looks like you opened this issue in error. Is there something I can help you with regarding that article?
