### ISSUE TITLE
Confusing documentation of logical operators

### ISSUE THREAD

**Issue by huesla** [dotnet/docs#38432]
### Type of issue

Other (describe below)

### Description

I am not a native english speaker but the documentation of the logical & and | operators sound a bit confusing:

> The & operator evaluates both operands even if the left-hand operand evaluates to false, so that the operation result is false regardless of the value of the right-hand operand.

I just cannot wrap my head around this sentence.
This definition in other words says that in case the left operand is "false" the right operand is still evaluated **to make sure** the result is false even though the right operand is ignored (???).

Obviously this sentence does not make much sense.

I think the following would be more clear:
"The & operator evaluates both operands even if the left-hand operand evaluates to false, i.e. the operation result is false regardless of the value of the right-hand operand, but the right hand operand still gets evaluated."

Note that also the | operator has the same confusing sentence:
> The | operator evaluates both operands even if the left-hand operand evaluates to true, so that the operation result is true regardless of the value of the right-hand operand.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/boolean-logical-operators.md

### Document Version Independent Id

91eaa72e-c2fc-e0d3-ca11-994aadf02271

### Article author

pkulikov

### Metadata

* ID: 6d2d3240-ed65-94f2-335b-3ea483c51a5d 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by patr543a** [comment]
I do not see how you took regardless as meaning ignoring while still using it with it's meaning later

**Comment by huesla** [comment]
I see your point, "ignored" is not fully right, because the right operand _is_ evaluated -> so not ignored. The word "ignored" was rather related to the result, as the right operand plays no role in the result when the left is false.

But with this sentence I anyway only tried to point out what is confusing in the original sentence, which is the "so that".
For me this literally says "When left (operand) is false, the right one is also evaluated to make sure the result is false, even though the result is independent of the right in this case"

**Comment by patr543a** [comment]
Now i get it more clearly what you mean. I will agree your suggestion will make it more clear to avoid this confusion.

**Comment by huesla** [comment]
Maybe the documentation could also mention _why_ the logical `&` and `|` operators are non-short-circuiting, in contrast to the conditional logical `&&` and `||` operators, where "short-circuiting" is mentioned.
I'm not a C# guru but I guess it has historical reasons, regarding bitwise comparison coming from C/C++.

**Comment by pkulikov** [comment]
I would just omit the second half of a sentence:

> ...so that the operation result is false regardless of the value of the right-hand operand.

It doesn't look to add anything useful. The main point of the sentence is to say that the operator always evaluates both operands.

**Comment by pkulikov** [comment]
> This definition in other words says that in case the left operand is "false" the right operand is still evaluated **to make sure** the result is false even though the right operand is ignored (???).

I think the original intention was to say: "In case the left operand is `false`, the result of `&` is `false`. **However, even then**, the right operand is evaluated."

**Comment by huesla** [comment]
> "In case the left operand is false, the result of & is false. However, even then, the right operand is evaluated."

This would be more clear, I agree

**Comment by BillWagner** [comment]
> I think the original intention was to say: "In case the left operand is `false`, the result of `&` is `false`. **However, even then**, the right operand is evaluated."

I like this solution.  I'll add it to our backlog, and add the "help wanted" if anyone wants to submit a PR.

Thanks @huesla @patr543a @pkulikov for the conversation to bring us to a great proposal.
