### ISSUE TITLE
software developer

### ISSUE THREAD

**Issue by amrifaezeh** [dotnet/docs#38439]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0117?f1url=%3FappId%3Droslyn%26k%3Dk(CS0117)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0117.md

### Document Version Independent Id

fefbef5d-bc47-9458-1ba5-86388d2c251a

### Article author

BillWagner

### Metadata

* ID: b1c7d191-7c09-0bd8-32b2-527748c41882 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by amrifaezeh** [comment]
Assert.AreEqual(Page.CommonPage.GetNoResultsLinkedLibraryMessage("Controls"), Page.CommonPage.NoItemsFoundRecord("controls"), "Verify no results");

this code was working fine but now im getting error of CS0115

**Comment by patr543a** [comment]
> Assert.AreEqual(Page.CommonPage.GetNoResultsLinkedLibraryMessage("Controls"), Page.CommonPage.NoItemsFoundRecord("controls"), "Verify no results");
That does not appear to be a documentation issue. You also linked the wrong error page.

**Comment by BillWagner** [comment]
Hi @amrifaezeh 

I agree with @patr543a that this doesn't look like a docs issue. The best way to get an answer to your question is to post a small sample on the [Q & A](https://[learn.microsoft.com](https://learn.microsoft.com/answers/tags/309/csharp) site.

I'll close this as not a docs issue.
