### ISSUE TITLE
rakpk

### ISSUE THREAD

**Issue by rakcom** [dotnet/docs#38437]
### Type of issue

Missing information

### Description

[ป้อนคำติชมที่นี่]

### Page URL

https://learn.microsoft.com/th-th/dotnet/framework/install/on-windows-11#see-also

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/on-windows-11.md

### Document Version Independent Id

00ab7825-3aeb-04c5-ebf6-6166712ce848

### Article author

adegeo

### Metadata

* ID: 4e45b2a9-2466-689a-7e73-0c224ca8e98f 
* Product: **dotnet-framework**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Hello. It looks like you opened this issue in error. Is there something I can help you with regarding that article?
