### ISSUE TITLE
Compiler Error CS0006

### ISSUE THREAD

**Issue by OzSar** [dotnet/docs#38431]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0006?f1url=%3FappId%3Droslyn%26k%3Dk(CS0006)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0006.md

### Document Version Independent Id

e56762dc-fe98-8c01-8a62-be183b61ff83

### Article author

BillWagner

### Metadata

* ID: e8ba0096-b431-a7de-2701-91c4bd3d9a85 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @OzSar 

Can you add more details here on what we should add?
