### ISSUE TITLE
Repetition of a word in a row in a sentence.

### ISSUE THREAD

**Issue by Kamil-Zuki** [dotnet/docs#38440]
### Type of issue

Other (describe below)

### Description

The word "вложенный" is repeated in the sentence twice in a row

### Page URL

https://learn.microsoft.com/ru-ru/dotnet/architecture/porting-existing-aspnet-apps/comparing-razor-pages-aspnet-mvc

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/comparing-razor-pages-aspnet-mvc.md

### Document Version Independent Id

0bfdbbed-6f19-e5ad-e311-67b86d68185b

### Article author

ardalis

### Metadata

* ID: 22f395e6-5a79-c6fc-bd99-dc29b6ad4dc2 
* Product: **dotnet-architecture**

**Comment by IEvangelist** [comment]
Closing this issue, as it relates to an eBook that has since been archived. For more information, see:

- Issue: #38774
- Pull request: #38775
