### ISSUE TITLE
fffdd

### ISSUE THREAD

**Issue by mujrobucvu24** [dotnet/docs#38456]
### Type of issue

Code doesn't work

### Description

[Insira comentários aqui]

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/misc/cs0104

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0104.md

### Document Version Independent Id

93b0e176-f0c1-a7e1-5d1c-cd5db48f4245

### Article author

BillWagner

### Metadata

* ID: 96ab5385-7fd3-bd65-3410-f821eb2d325e 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @mujrobucvu24 

Can you add more details about what information you wanted to find in this article?
