### ISSUE TITLE
error CS5001

### ISSUE THREAD

**Issue by Nilo0906** [dotnet/docs#38454]
### Type of issue

Code doesn't work

### Description

error CS5001: O programa 'c:\Users\NVCS_\Documents\projetos
        c#\Estudos.1\estudos.1.exe' não contém um método 'Main'        static adequado para um ponto de entrada
PS C:\Users\NVCS_\Documents\projetos c#\estudos.1>

using System;
class Principal{
static void Main(){
    Console.Write("Olá Mundo...");
    }
}

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/misc/cs5001

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs5001.md

### Document Version Independent Id

a1404161-c48b-564b-03ea-d4340fe28c53

### Article author

BillWagner

### Metadata

* ID: dcc1ba33-60dd-1e44-2498-eb76f0d964c1 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @Nilo0906 

Can you add more details about what information you wanted to find in this article?
