### ISSUE TITLE
Ubuntu 22.04 feeds should include .NET 8 by end of year

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#38460]
### Type of issue

Outdated article

### Description

By the end of the year, the built in Ubuntu 22.04 feeds should include .NET 8.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2204.md

### Document Version Independent Id

909b29bd-2729-3b59-beb5-20a7281344d0

### Article author

adegeo

### Metadata

* ID: 5ac16736-f225-12d0-2de2-efded54a505a 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

---
[Associated WorkItem - 186854](https://dev.azure.com/msft-skilling/Content/_workitems/edit/186854)

**Comment by adegeo** [comment]
Still don't see the packages at https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=dotnet will try again in Jan

**Comment by adegeo** [comment]
Still not seeing packages. Closing until I'm told they're available.

**Comment by lahma** [comment]
Hi @adegeo , I was monitoring this issue as I'm also interested to see this in official 22.04 feed. Do you know any sources internal or external which one could monitor for the status. I guess Microsoft is delivering the packages so some Ubuntu queue?

**Comment by adegeo** [comment]
hi @lahma I'll ask around, but Canonical is in charge of it as they actually do the builds with whatever optimizations they want and then push to the feeds. They've done it for other releases, so it makes me think they just don't want to backport a new release to 22.x 😢

**Comment by alin256** [comment]
Why is this issue closed and the help page is not corrected???

**Comment by alin256** [comment]
@adegeo 

Here are specific details.

According to the installation instructions https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204 , one can simply `apt-get install` the .net distribution.

This does not work, because, as you say: “it’s in Canonical’s hands” and they did not include it.

Thus the page for 22.04 should be updated to something like the page for 20.04, where the first step is to add the Microsoft package repositories: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2004#add-the-microsoft-package-repository

**Comment by adegeo** [comment]
Yeah, I had a meeting on that yesterday or the day before as it can be confusing. The table at the top of the current article tells you which versions are available in which feed. The commands are the same except for version number. If we swap out the command for 7.0 then people file bugs saying WHERE'S 8?? so it just replaces one problem with another 😁 The reason 20.04 has that section is because it's the **only** way to use a package feed.

I'm in the middle of filing a new issue to track how we can change these to be a bit more clear, based on some meeting notes. I'll tag you if you're interested in discussing the details and coming up with some ideas.

**Comment by lahma** [comment]
Thank you for elaborating the situation. For us "outsiders" it's a bit hard to know why things are how they are and I personally don't enjoy re-configuring production servers with Microsoft feed as it invalidates old installations (NET 6.0 and NET 7.0) now that they were working as expected. Two feeds will cause conflicts and thus on official Ubuntu feed would be ideal - but it seems to be out of your hands.

**Comment by adegeo** [comment]
Yeah, it's very frustrating for sure, especially trying to communicate all that accurately and concisely. If it's too verbose no one reads anything and runs into problems.

**Comment by adegeo** [comment]
Issue created #39263

**Comment by lahma** [comment]
@adegeo it seems that .NET 8 has finally landed Ubuntu 22.04 LTS feed!

https://packages.ubuntu.com/search?keywords=dotnet-sdk-8.0
