### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by sbonyoni** [dotnet/docs#38471]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0117?f1url=%3FappId%3Droslyn%26k%3Dk(CS0117)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0117.md

### Document Version Independent Id

fefbef5d-bc47-9458-1ba5-86388d2c251a

### Article author

@BillWagner

### Metadata

* ID: b1c7d191-7c09-0bd8-32b2-527748c41882 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @sbonyoni 

Can you add more information on what you're looking for from this article?
