### ISSUE TITLE
Array creation code sections of new operator reference don't work

### ISSUE THREAD

**Issue by RieBi** [dotnet/docs#38475]
### Type of issue

Code doesn't work

### Description

The two code blocks under the **Array creation** section do not work. Trying to run them with the on-site **run** button results in a compile error. 

It is also stated in the first paragraph of the section that the **new** operator is used for creating an array instance, but there is no **new** operator in any of those code blocks.

The images show the issue
![Screenshot_7](https://github.com/dotnet/docs/assets/42877671/c35bee2a-59a2-4466-a4ba-fa66d763b61d)
![Screenshot_8](https://github.com/dotnet/docs/assets/42877671/de0e8620-f135-4430-9052-5a276337e9f3)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#code-try-3

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/new-operator.md

### Document Version Independent Id

96df2e76-70b0-4873-4acc-d6bae51986b4

### Article author

@BillWagner

### Metadata

* ID: c6bdb964-4c04-d174-e879-e3a2d176809b 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by BillWagner** [comment]
Thanks for pointing this out @RieBi 

Those two code blocks use the new [collection expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions) feature added in C# 12. The Try.NET infrastructure hasn't been updated to support that syntax. We'll get that fixed.
