### ISSUE TITLE
 issue type,

### ISSUE THREAD

**Issue by Protection4** [dotnet/docs#38521]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/run-net-framework-1-1-apps?source=recommendations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/run-net-framework-1-1-apps.md

### Document Version Independent Id

456e8771-1cfb-8775-47d9-ca0ea23b795d

### Article author

@adegeo

### Metadata

* ID: 9a97c8bd-53e6-c249-2429-2494ba576434 
* Product: **dotnet-framework**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Hello, you opened this issue but didn't add any information. Is there something I can help you with regarding that article?
