### ISSUE TITLE
Inconsistancy

### ISSUE THREAD

**Issue by cloud-print** [dotnet/docs#38523]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]

The article states that one the issues in the first piece of code can be rectified using the code in the second example. However, it is unclear how these two pieces of code relate to each other.

Below I have pasted the example code  

***Code example 1 ***

class Container
{
    public List<string>? States { get; set; }
}

internal void PossibleDereferenceNullExamples(string? message)
{
    Console.WriteLine(message.Length); // CS8602

    var c = new Container { States = { "Red", "Yellow", "Green" } }; // CS8670
}

***Code example 2 ***

void WriteMessageLength(string? message)
{
    if (message is not null)
    {
        Console.WriteLine(message.Length);
    }
}

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8603)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/nullable-warnings.md

### Document Version Independent Id

df58b52a-2532-8241-72cd-f40e9096037d

### Article author

@BillWagner

### Metadata

* ID: 812f0144-80de-6b49-dded-97eeb7bc373d 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Thanks for pointing this out. I'll fix it in our next sprint.
