### ISSUE TITLE
Incorrect generation

### ISSUE THREAD

**Issue by CooperLiumz** [dotnet/docs#38522]
### Type of issue

Typo

### Description

run dotnet pack only debug generated, no release generated
![dotnet222](https://github.com/dotnet/docs/assets/67528045/f69228a3-2a72-4668-b7aa-9b880151fd2f)
![Uploading dotnet111.png…]()

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-package

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-template-package.md

### Document Version Independent Id

1a94f1c8-0dd1-38a4-3c0c-db9c1ed0c1aa

### Article author

@adegeo

### Metadata

* ID: 8525c47c-370e-7b05-4160-360fe67b6734 
* Product: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Hello. If you wanted to generate the release version, you would want to use `dotnet pack -c Release`
