### ISSUE TITLE
VS2017 csproj NuGet reference question

### ISSUE THREAD

**Issue by unickq** [dotnet/docs#3853]
I have following project structure with 3 Nuget dependencies:
```xml
<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFrameworks>net45;net46</TargetFrameworks>
      ...
   </PropertyGroup>
   <ItemGroup>
      <PackageReference Include="NUnit" Version="3.9.0" />
      <PackageReference Include="Selenium.WebDriver" Version="3.7.0" />
      <PackageReference Include="SpecFlow.CustomPlugin" Version="2.2.1" />
   </ItemGroup>
</Project>
```
It's really cool that VS2017 allows creating NuGet packages out of the box.

But what can do if I want to include custom NuGet references and don't wanna include references I use now?

Old **packages.config** file:
```xml
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
   <metadata>
      ...
      <dependencies>
         <dependency id="SpecFlow" version="2.2.0" />
         <dependency id="NUnit" version="3.0.0" />
         <dependency id="Autofac" version="[3.3.0,3.5.2]" />
         <dependency id="Autofac.Configuration" version="[3.3.0]" />
         <dependency id="Selenium.WebDriver" version="3.0.0" />
      </dependencies>
   </metadata>
</package>
```
I this case I need to have **Autofac** with my lib but I don't need it to build my lib. 
Or I don't need **SpecFlow.CustomPlugin** with all dependencies in project which will use my lib but it needs have one to build itself.

I think there is a way to include NuSpec file path to new csproj but I think all csproj **PropertyGroup** fields won't be used.

Sorry if I created this issue in wrong repo. Posted it here because of [this doc](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)

**Comment by mairaw** [comment]
@unickq thanks for your question. @weshaggard @terrajobst @livarcocc who could help with this sort of question?

**Comment by unickq** [comment]
Anyone?

**Comment by mairaw** [comment]
@weshaggard @terrajobst @livarcocc pinging again

**Comment by livarcocc** [comment]
@rrelyea @rohit21agrawal

**Comment by rohit21agrawal** [comment]
If I am understanding the question correctly, it's about managing package dependency assets. Please refer to  https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by mairaw** [comment]
@unickq are you good with the answer? Does that help with your issue?

**Comment by unickq** [comment]
Yes, thanks.

Made something like 
```xml
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.9.0" />
    <PackageReference Include="Selenium.WebDriver" Version="3.8.0" />
    <PackageReference Include="SpecFlow.CustomPlugin" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SpecFlow" Version="2.2.1">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Autofac" Version="[3.5.2]">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Autofac" Version="[3.5.2]">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Autofac.Configuration" Version="[3.3.0]">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
```
