### ISSUE TITLE
Typo in "Keyed DI services" section

### ISSUE THREAD

**Issue by brnn8r** [dotnet/docs#38532]
### Type of issue

Typo

### Description

I believe the highlighted word **_your_** should be **_you_**.

"Keyed dependency injection (DI) services provides a means for registering and retrieving DI services using keys. By using keys, you can scope how **_your_** register and consume services. These are some of the new APIs:"

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-8.md

### Document Version Independent Id

b22cffcc-898f-a3cf-83f9-a3c7349a1b14

### Article author

@gewarren

### Metadata

* ID: 9d8a154a-d129-7e5a-e2aa-8d1a720252c5 
* Product: **dotnet-fundamentals**

**Comment by guteswetter** [comment]
As this is still open, I'll create a PR to fix this typo. There is another grammatical issue in the sentence before: 
_"Keyed dependency injection (DI) services **provides** a means for registering and retrieving DI services using keys."_ 

_provides_ should be _provide_
