### ISSUE TITLE
Language reference fowards to the `new` operator from the list of keywords - it should not do that.

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/docs#38541]
### Type of issue

Other (describe below)

### Description

In the C# Language Reference, the Keyword overview (in the category "Keywords")
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
lists the `new` keyword, but links it to the documentation of the new operator 
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator
(which is situated in the category "Operators and expressions")
rather than pointing either to the `new` (member modifier) keyword
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier
(which is situated in the category "keywords", slightly down),
or the `new` (type constraint) keyword
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-constraint
(which also is situated in the category "keywords", slightly further down),
OR - which i think should be the right thing - a __disambiguation__ page explaining (or at least listing) all three different meanings of the new keyword (maybe put that into the overview, directly?)

Background: i was trying to look up the meaning of the `new` modifier in the context of interfaces, but it was really hard to get there :-)
thanks

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/new-operator.md

### Document Version Independent Id

96df2e76-70b0-4873-4acc-d6bae51986b4

### Article author

@BillWagner

### Metadata

* ID: c6bdb964-4c04-d174-e879-e3a2d176809b 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by AdmiralSnyder** [comment]
I just noted that in each of the three `new` explanation articles, there's a sentence explaining the other meanings of `new` within the first section - it's not easy to spot, though, and requires reading rather than skimming. - and the other meanings should definitely be noted in the "see also" sections.

**Comment by BillWagner** [comment]
Thanks for the details here @AdmiralSnyder. I appreciate the detailed notes.

I think the best solutions is the disambiguation page. That page will also handle the F1 help from Visual Studio and VS Code, where the token is `new` without any context for which meaning of `new` was highlighted.

I'm adding this to our backlog, and adding the "help wanted" label if anyone wants to submit a PR before we make the changes.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will handle that!

**Comment by BartoszKlonowski** [comment]
Hello @BillWagner! Do we have any template (or an example) of a disambiguation page that should be followed? I'm having a hard time finding one in the codebase.

**Comment by BillWagner** [comment]
Hi @BartoszKlonowski 

The [`in` keyword](https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/in) is probably the best example of disambiguation. That page handles `F1` help from Visual Studio and VS Code / C# Dev kit.  There's likely more cleanup we can do on the navigation / TOC between these pages. But, it's a start and points in the direction we want to go.
