### ISSUE TITLE
Code snippet doesn't match surrounding text

### ISSUE THREAD

**Issue by fzs111** [dotnet/docs#38553]
### Type of issue

Other (describe below)

### Description

In the last code snippet on the page, the text says "using explicit typing", but it's the same code as the second to last snippet, still using `var`.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/write-linq-queries

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/write-linq-queries.md

### Document Version Independent Id

07d5d82d-a52e-9531-25ec-95e1db5f619c

### Article author

@BillWagner

### Metadata

* ID: 527222c2-7532-7753-7ad5-01f0eeddec75 
* Product: **dotnet-csharp**
* Technology: **csharp-linq**

**Comment by BillWagner** [comment]
I think this snuck in during a recent PR. 

I'd added it to our backlog, and added the "help wanted" label.

/cc @DickBaker As you're working on samples, you should make sure to check the text accompanying the sample for reasons certain constructs were chosen.
