### ISSUE TITLE
this application could not be started 

### ISSUE THREAD

**Issue by Christianbedia** [dotnet/docs#38566]
### Type of issue

Typo

### Description

[Tapez vos commentaires ici]

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/framework/install/repair

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/repair.md

### Document Version Independent Id

f2e94c72-459b-c8f1-7eec-73e7d4197f4d

### Article author

@adegeo

### Metadata

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485 
* Product: **dotnet-framework**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Hello, you opened this issue but didn't add any information. Is there something I can help you with regarding that article?
