### ISSUE TITLE
[NewTopic] C# compiler version history might have its own page

### ISSUE THREAD

**Issue by lextm** [dotnet/docs#3857]
There is already an article to cover [the history of C#](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history). However, the compiler itself should have a similar page.

This new article should cover,

* Compiler major releases and their characteristics.
* Compiler features such as multi-targeting, which are not yet covered in any existing article. 
* C# compilers from other vendors than Microsoft.

Instead of an outline, I have a draft as a blog post,

https://blog.lextudio.com/the-rough-history-of-the-so-many-c-compilers-f3a85500707c

Much critical information is missing right now in the post, such as compiler version numbers (the pattern is hard to capture), but it reveals what kind of things are not yet there in the C# documentation section, and hope there is a way to fill the gaps.

**Comment by BillWagner** [comment]
/cc @jcouv  

This is an interesting idea. I'd like to get product team thoughts here, both from the Roslyn team, and the Xamarin/Mono compiler team.

**Comment by jcouv** [comment]
I like it. 

Currently we only have language history in bullet format (https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md) and we've been tracking compiler features in a similar format (but only recently, at https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md).
The difficulty in my opinion would be filling in the blanks for compiler features...

**Comment by migueldeicaza** [comment]
A very brief history of Mono’s C# compiler is here: 

https://www.mono-project.com/docs/about-mono/languages/csharp/

**Comment by BillWagner** [comment]
Thanks for the discussion.  What should happen now is to update [the current history topic]()https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-version-history) and reconcile the Mono history and the C# Lang history docs with the current topic.  In the end, we should have one page (the current one) that includes the information for the Microsoft compiler and the Mono compiler.
