### ISSUE TITLE
"Ignore all read-only properties" is misleading (assuming there is no bug in code)

### ISSUE THREAD

**Issue by Audionysos** [dotnet/docs#38575]
### Type of issue

Other (describe below)

### Description

It's says
"A property is read-only if it contains a public getter but not a public setter. To ignore all read-only properties when serializing, set the [JsonSerializerOptions.IgnoreReadOnlyProperties](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.ignorereadonlyproperties#system-text-json-jsonserializeroptions-ignorereadonlyproperties) to true, as shown in the following example:"

If I simply modify the example to this:
```
public class WeatherForecastWithROProperty {
	public DateTimeOffset Date { get; set; }
	public int TemperatureCelsius { get; set; }
	public List<string> Summary2 {
		get {
			return new List<string>();
		}
	}
	public string Summary {
		get {
			return "string";
		}
	}
	public int WindSpeedReadOnly { get; private set; } = 35;
}
```

This is my output:
```
{
  "$id": "1",
  "Date": "0001-01-01T00:00:00+00:00",
  "TemperatureCelsius": 0,
  "Summary2": {
    "$id": "2",
    "$values": []
  }
}
```
So it doesn't "ignore all read-only properties" :(

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/ignore-properties

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/ignore-properties.md

### Document Version Independent Id

db1ef743-6f31-a509-4676-f22d4847792d

### Article author

@gewarren

### Metadata

* ID: b7aa3b68-ffe0-8bdf-b6f4-b99672086a92 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 206392](https://dev.azure.com/msft-skilling/Content/_workitems/edit/206392)

**Comment by gewarren** [comment]
@eiriktsarpalis Is there a rule that read-only *collection-type* properties are serialized even if `IgnoreReadOnlyProperties` is `true`?
