### ISSUE TITLE
Link to the implementation of `ValueObject` points to an archived repository

### ISSUE THREAD

**Issue by nathanpovo** [dotnet/docs#38580]
### Type of issue

Outdated article

### Description

The link to the implementation of `ValueObject` (found in the "Additional resources" section) sends to user to an archived repository.

The old link is https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/SeedWork/ValueObject.cs

It should be updated to https://github.com/dotnet/eShop/blob/main/src/Ordering.Domain/SeedWork/ValueObject.cs

The content of the class is the same (only the namespace is different) so it does not actually matter. However, a user will not know that until they manage to find the location of the `ValueObject` class in the new repo so it is better to send users directly to the new repo.

### Page URL

https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md

### Document Version Independent Id

cf912666-9ad3-1673-8f69-6bf52c034ef9

### Article author

@jamesmontemagno

### Metadata

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d 
* Product: **dotnet-architecture**
* Technology: **microservices**

**Comment by jamesmontemagno** [comment]
The current ebooks references the archived project. We are working on a new ebook that will reference the new eShop in the near future.
