### ISSUE TITLE
Update documentation for default Configuration in .NET 8 for dotnet publish and pack

### ISSUE THREAD

**Issue by joegoldman2** [dotnet/docs#38593]
## Issue description

The documentation for the `-c|--configuration` option in the dotnet publish and dotnet pack commands states that the default configuration for most projects is Debug. However, starting from .NET 8, the default configuration has been changed to Release.
The documentation should reflect that, starting from .NET 8, the default build configuration for most projects is Release, not Debug.

## Target framework

- [X] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#arguments)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by rextor92** [comment]
confirmed by https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-publish-config and https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-pack-config . I can take that, but not sure how to relay the info of .NET >= 8 vs .NET < 8. Should we include both somehow or just latest?

**Comment by gewarren** [comment]
@rextor92 We should show both (.NET 8+ and .NET 7-). Not sure if you or @tdykstra want to address this issue.

**Comment by tdykstra** [comment]
I can do it, unless @rextor92 would prefer to do it. In these docs we use text to say what is different in different SDK versions, like "Starting with the .NET 8 SDK, the default configuration is ..."

**Comment by rextor92** [comment]
You can have it @tdykstra, I'll take notes for future occasions. I will work on another issue I have instead 😄
