### ISSUE TITLE
How to contribute localization content

### ISSUE THREAD

**Issue by heavenwing** [dotnet/docs#386]
I plan to translate these documentations to other language (ex: Chinese), but I don't know how to do it?
And I found that core-docs using DocFx, however ASP.NET Core Docs using ReadTheDocs, also I need to know how to contribute localization content into docs.asp.net.

**Comment by mairaw** [comment]
Hi @heavenwing! Thanks for your interest in helping us localize the .NET Core and ASP.NET Core documentation. At the moment, we don't support localized content but we're working to support it. We can let you know when that's available so you can help us improve the localized content we'll provide.

/cc @blackdwarf @richlander

**Comment by Emeryao** [comment]
@mairaw please also let me know when it's available. :smile:

**Comment by SeayXu** [comment]
@mairaw I‘m translating the `docs/core/tools` part to **Chinese**,when translated I will submit to my GitHub, that I had forkd project’s  `zh-cn` branch.Can I submit PR and how?

**Comment by mairaw** [comment]
Thank you for your interest @Emeryao and @SeayXu. I can't wait to be able to have localized documentation for .NET on docs.microsoft.com. We'll provide the content localized and then you'll be able to submit improvements. We don't have the site ready to be able to accept PRs at this moment. @ericvt can probably say more about the localization plans.

**Comment by richlander** [comment]
It would be good if developers from other countries could translate individual documents ahead of the Microsoft-provided translation as opposed to solely providing improvements.

Naively, I'm guessing that this is mostly a question of coming up with the repo structure for localized docs and the webserver serving up those translations when appropriate. Is that right?

/cc @bradygaster

**Comment by lextm** [comment]
@richlander Developers from China have already started several initiatives ([like this one](http://home.cnblogs.com/u/dotNETCoreSG/)) to translate the materials, but without proper arrangements the quality and the accuracy cannot be guaranteed.

The earlier we see an almost finalized localization plan, the easier all efforts can be focused on the most important part.

**Comment by richlander** [comment]
@lextm makes sense. This is something we will finalize this summer. It's quite important, as you suggest.

**Comment by ericvt** [comment]
we are working on getting part of .NetCore documentation localized in several languages including Chinese. Once this is available on docs.microsoft.com, we will welcome edits & contributions as @mairaw mentioned.

**Comment by lextm** [comment]
Now I can see the localization repos at GitHub like [this one for Simplified Chinese](https://github.com/dotnet/docs.zh-cn/issues/2) Thanks for the efforts, guys.

**Comment by heavenwing** [comment]
Cool.

发送自我的 Windows 10 手机

发件人: Lex Li<mailto:notifications@github.com>
发送时间: 2016年11月24日 20:49
收件人: dotnet/docs<mailto:docs@noreply.github.com>
抄送: heavenwing<mailto:heavenwing@msn.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [dotnet/docs] How to contribute localization content (#386)


Now I can see the localization repos at GitHub like this one for Simplified Chinese<https://github.com/dotnet/docs.zh-cn/issues/2> Thanks for the efforts, guys.

―

**Comment by mairaw** [comment]
I'm closing this one now that we have the localized repos. There's a new issue in the Chinese docs repo asking for a contributing guide and that would be important to have:
https://github.com/dotnet/docs.zh-cn/issues/2

For example, customers are not supposed to fix the content on the localized repos, they should only fix translation issues.

/cc @ericvt @nokura @SonjaSaltzman

**Comment by miltoncamara** [comment]
@mairaw Can I contributing for pt-BR translation for new contents? As I can see some articles or contents does not exists in pt-BR language.

**Comment by ericvt** [comment]
thank you @miltoncamara . we working on our localization plan for .netcore. Pt-BR is in our scope for translation. If you are interested in reviewing the quality of the translation or give us feedback on that once it's done that would be fantastic. please let us know.
