### ISSUE TITLE
Suppress e.g., CA1861 for certain project types 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/docs#38633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suppress-eg-CA1861-for-certain-projec/10525308)._

---
After the upgrade to .NET 8 / VS 2022 17.8 a new message pops up: CA1861	Prefer 'static readonly' fields over constant array arguments if the called method is called repeatedly and is not mutating the passed array.

This is a useful diagnostic to have for production code, but it pops up a lot in my unit tests that verify whether some code produces the required list of things. I now have a choice to disable it completely, add an .editorconfig to all my unit test projects, or live with tons of blue squiggles in test code. I'll do the first, but that is obviously not why you introduced this analytics. But I can't see a way to disable the issue in a single .editorconfig file for all projects in the directory tree that satisfy a condition. Please provide such an optio

(this may be more of a suggestion, but for me all those new messages are a problem)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15464b9c-7a37-48d6-afb0-293896519a9c
* Version Independent ID: f213a799-22c9-e526-f0a0-b8cd0c824070
* Content: [CA1861: Avoid constant arrays as arguments (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1861)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1861.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1861.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @steveberdy
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 250216](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250216)

**Comment by mavasani** [comment]
See https://developercommunity.visualstudio.com/t/Suppress-eg-CA1861-for-certain-projec/10525308#T-N10530664 for the documentation enhancement suggestion from the customer
