### ISSUE TITLE
Region I Think not Working

### ISSUE THREAD

**Issue by MrBear53** [dotnet/docs#38648]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/directives/region-directive

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/directives/region-directive.md

### Document Version Independent Id

0b643ad9-8979-55fe-4c7d-08dccd89c21b

### Article author

@KathleenDollard

### Metadata

* ID: 1da80bd5-efb6-339b-8480-2da0310e5672 
* Product: **dotnet-visualbasic**

**Comment by BillWagner** [comment]
Missing details. This content is correct to me.
