### ISSUE TITLE
Compiler Error CS1929

### ISSUE THREAD

**Issue by mikaelketola2023** [dotnet/docs#38646]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1929?f1url=%3FappId%3Droslyn%26k%3Dk(CS1929)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1929.md

### Document Version Independent Id

f4ea0455-af69-3b15-06bc-77402d9817ef

### Article author

@BillWagner

### Metadata

* ID: 60bebc7c-eb8a-1a24-5d03-29b5450ee294 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @mikaelketola2023 

Can you add more information about what you expect here?
