### ISSUE TITLE
 ApplicationBuilder and DefaultBuilder are mixed up

### ISSUE THREAD

**Issue by yinhx3** [dotnet/docs#38650]
### Type of issue

Outdated article

### Description

[Enter feedback here]
The article talks about DefaultBuilder(use IHostBuilder and configureDelegate), but codes talk about ApplicationBuilder(use HostApplicationBuilder and builder.Configuration). Really confusing.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host#host-configuration

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/generic-host.md

### Document Version Independent Id

22a12ff8-d2ff-a841-b9bb-e2fd1032bc04

### Article author

@IEvangelist

### Metadata

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 190730](https://dev.azure.com/msft-skilling/Content/_workitems/edit/190730)

**Comment by IEvangelist** [comment]
Thanks for the feedback, and posting this issue. I agree we need to make this easier and separating things makes sense. Working on it now.
