### ISSUE TITLE
Incorrect information on Runtime Information

### ISSUE THREAD

**Issue by edespong** [dotnet/docs#38670]
### Type of issue

Other (describe below)

### Description

The article says that:

```
ASP.NET Core runtime
Runs ASP.NET Core apps. Includes the .NET runtime.
```

This does not seems to be correct. Installing the latest (8.0) ASP.NET Core runtime does not install the .NET Runtime (e.g. nothing is placed under dotnet\shared\Microsoft.NETCore.App), and my web application returns an error complaining that .NET runtime is missing. It is also indicated by the size of the installers: ASP.NET Core runtime installer is approx. 10Mb, and the standalone .NET Runtime 8.0.0 installer is 27Mb. If .NET Runtime is included in ASP.NET Core runtime, then how can it be 1/3 of the size.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#runtime-information

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md

### Document Version Independent Id

d11d0d14-8a03-50e4-5c00-9a4417ad4d0a

### Article author

@adegeo

### Metadata

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

---
[Associated WorkItem - 192422](https://dev.azure.com/msft-skilling/Content/_workitems/edit/192422)

**Comment by adegeo** [comment]
You're right. This information was true for .NET 7, but I guess it was changed in .NET 8. I'll bring this up to the team and then see what to do in the docs... 😿

**Comment by adegeo** [comment]
I looked a little more into this and it's the "Hosting Bundle" that includes both runtimes, there's a note on the download section. I'll update the docs to match:

![image](https://github.com/dotnet/docs/assets/67293991/de887493-2754-4330-87dd-0fbd0a62b7af)
