### ISSUE TITLE
how to connect database with our .net form window app

### ISSUE THREAD

**Issue by shashidharsrivastav** [dotnet/docs#38695]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md

### Document Version Independent Id

926db74c-be79-f7cd-a4e9-e156dafa6287

### Article author

@tdykstra

### Metadata

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5 
* Product: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
The issue title doesn't provide enough information for us to know how to respond. I'm closing the issue, as it doesn't appear to be related to the article it was raised on.
