### ISSUE TITLE
.NET Framework 3.5 offline installer not works without internet

### ISSUE THREAD

**Issue by MykhailoChabanEPAM** [dotnet/docs#38690]
### Type of issue

Other (describe below)

### Description

This article:
https://learn.microsoft.com/uk-ua/dotnet/framework/install/dotnet-35-windows#download-the-offline-installer
has .NET Framework 3.5 offline installer
It not works.
Trying setup .NET 3.5 framework on most recent Windows 11 machine without internet still shows popup, that to run .NET 3.5 installer Windows needs to download .NET 3.5 from internet before install, so int not works

### Page URL

https://learn.microsoft.com/uk-ua/dotnet/framework/install/dotnet-35-windows#download-the-offline-installer

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/dotnet-35-windows.md

### Document Version Independent Id

40ddc3ce-a004-1a4c-37e1-1c45eaa8f35a

### Article author

@adegeo

### Metadata

* ID: 96aef419-de1f-a341-3f19-4ed99eb36412 
* Product: **dotnet-framework**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Can you tell me what link exactly you're using before the download starts? How large is the file you downloaded? I wonder if there's a problem with regions or something.

**Download link**: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net35-sp1-web-installer
**File size**: 237 MB

However, this installer, for me, doesn't even run. I can open it in 7zip and navigate down and see all the individual download files though...

**Comment by MykhailoChabanEPAM** [comment]
My entry point, I started to download .NET is:
https://www.microsoft.com/en-us/download/details.aspx?id=21

On this page I go to "Install Instructions" part of page and go to link "NET Framework 3.5 full package"
http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe

File size: 197 MB (206 692 864 bytes)
MD5: d1b341c1bc8b96e4898450c9881b1425

**Comment by adegeo** [comment]
Hi @MykhailoChabanEPAM I don't see that link `https://www.microsoft.com/en-us/download/details.aspx?id=21` on this article page, so I'm not sure what I would fix in the article for this issue? Also, that link is for 3.5, this article links to 3.5 SP1 which is what you should use.

**Comment by adegeo** [comment]
Closing this until more information is provided. Sorry for the troubles you had!
