### ISSUE TITLE
ricardo

### ISSUE THREAD

**Issue by 2764ricardo** [dotnet/docs#38697]
### Type of issue

Typo

### Description

[Insira comentários aqui]

### Page URL

https://learn.microsoft.com/pt-br/dotnet/framework/install/repair?source=recommendations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/repair.md

### Document Version Independent Id

f2e94c72-459b-c8f1-7eec-73e7d4197f4d

### Article author

@adegeo

### Metadata

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485 
* Product: **dotnet-framework**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Leave this issue for me to test with
