### ISSUE TITLE
CS0577: Improve/correct error message and description

### ISSUE THREAD

**Issue by RexJaeschke** [dotnet/docs#38720]
### Type of issue

Missing information

### Description

The compiler message includes "lambda expression" but the explanation text does *not*; it should.

The compiler message and explanation text uses "destructor". That term was discontinued a long time ago; "finalizer" should be used instead in both.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0577

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0577.md

### Document Version Independent Id

22298e77-da67-5044-8ad4-46dfed7f394b

### Article author

@BillWagner

### Metadata

* ID: 0f4de96b-9f16-21eb-1e68-8fba07dd4fd9 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
For this issue, we should include the term "lambda expression" in the text.

The first paragraph should continue to use "destructor" for SEO reasons. That's the text generated by the compiler. The text in the article should explain that "destructor" is the deprecated term for "finalizer".

I've added this to our backlog and added the "help wanted" label.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski 

I've assigned it to you.
