### ISSUE TITLE
Array declaration Issue

### ISSUE THREAD

**Issue by alejandronpereira** [dotnet/docs#38769]
### Type of issue

Code doesn't work

### Description

Some code examples are not running because the array declaration is like this:

int[] numbers = [4, 7, 10];

And I think that they must be something like this:

int[] numbers = {4, 7, 10};

You can try running some of the examples and the issue will occur

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator#code-try-1

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-operator.md

### Document Version Independent Id

e8eab8da-72ba-991a-c011-a41d2ed9939d

### Article author

@BillWagner

### Metadata

* ID: a695fde2-da48-835f-423d-d34fb048d6ab 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by BillWagner** [comment]
Thanks for pointing this out @alejandronpereira 

Those samples use [collection expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions), a new C# 12 feature. Collection expressions aren't supported in the currently deployed Try.NET instance.

I'll revert these samples until we get the updated Try.NET installed on the Learn platform.
