### ISSUE TITLE
Confusion regarding IDE0020 and IDE0038

### ISSUE THREAD

**Issue by arphox** [dotnet/docs#38778]
### Type of issue

Missing information

### Description

Hi!

I'm trying to understand rule IDE0020 and IDE0038.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0020-ide0038

I don't understand why do we need two different rules for this, and I also can't make them work.

**My first question**: could you please give me a demonstration (combination of settings with a demo code) where **IDE0038** is reported? I can't create an example for that.

In the following cases, suppose this is given:
```
dotnet_diagnostic.IDE0020.severity = warning
dotnet_diagnostic.IDE0038.severity = warning
```

In my understanding, `csharp_style_pattern_matching_over_is_with_cast_check` should behave the following way:
- if I set it to `true`, it _enforces_ type casting like this: `if (o is int i) {...}`
- if I set it to `false`, it _enforces_ type casting like this: `if (o is int) {var i = (int)o; ... }`

And in my understanding, these two points are mutually exclusive, since you cannot enforce one without enforcing the opposite of the other.

And the following code example:
```cs
object obj = new();
if (obj is int)
{
    int num = (int)obj;
    Console.WriteLine(num);
}
```
Reports nothing if `csharp_style_pattern_matching_over_is_with_cast_check` is `false`, but reports a warning if it is `true`, as espected.

However, the following code example:
```cs
if (obj is int num)
{
    Console.WriteLine(num);
}
```
Reports nothing if `csharp_style_pattern_matching_over_is_with_cast_check` is `true` (which is expected), but reports **nothing** if it is `true`! **Is this a bug?**

Could you please explain how IDE0020 and IDE0038 relate together and the role of the `csharp_style_pattern_matching_over_is_with_cast_check` option? Because I don't understand it from the documentation and experimentation. Thank you!

Either I don't understand something and/or there are bugs on this.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0020-ide0038

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0020-ide0038.md

### Document Version Independent Id

5320b97e-56d6-3be0-51f7-87e1f5539af4

### Article author

@gewarren

### Metadata

* ID: d244c72f-21ed-1826-c885-c8ac460a46b0 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
Here is some code that triggers IDE0038 if the option is set to `true`:

```csharp
        object o = new();
        if (o is int) // IDE0038
        {
            if ((int)o == 1) { }
        }
```

Based on [this line of code](https://github.com/dotnet/roslyn/blob/1c88444212854f6b6be43d9901f6c3d541bdcafa/src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpIsAndCastCheckDiagnosticAnalyzer.cs#L68), the analyzer only seems to fire if the option's value is `true`. Setting the option to `false` likely disables the analyzer, but that style of code (is check with cast) would still be used in refactorings. I'll update the documentation.
