### ISSUE TITLE
Code example for IDE0002 is incomplete

### ISSUE THREAD

**Issue by ozsvart-karoly-nexius** [dotnet/docs#38771]
### Type of issue

Code doesn't work

### Description

Hi!

Check the example here:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0002#example

```cs
static void M1() { }
static void M2()
{
    // IDE0002: 'C.M1' can be simplified to 'M1'
    C.M1();

    // Fixed code
    M1();
}
```

It is not clear that the containing class is called `C`. It should be there.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0002

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0002.md

### Document Version Independent Id

92048a86-9b59-1539-9596-42f76d5e9733

### Article author

@gewarren

### Metadata

* ID: b2f6c0c8-284b-1a50-e3fe-7f58c022d22d 
* Product: **dotnet-fundamentals**

**Comment by BartoszKlonowski** [comment]
Yes, otherwise it would cause compilation error when directly copy-pasted.
Let me wrap these functions with the class...
