### ISSUE TITLE
dotnet publish -p ContainerImageTags='"1.2.3-alpha2;latest"' throws "MSB1006: Invalid property"

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/docs#38786]
### Type of issue

Code doesn't work

### Description

From https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-7-0, there is a code snippet, stating that docker build image tags can be set with e.g. `dotnet publish -p ContainerImageTags='"1.2.3-alpha2;latest"'`. However, this doesn't work and throws a MSB1006 error:

```log
MSBUILD : error MSB1006: Die Eigenschaft ist ungültig.
Schalter: latest'
```

MSBuild-Version 17.8.3+195e7f5a3 for .NET

Hint:
Specifying one tag works, specifying more than one tag gives the error.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-7-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

@IEvangelist

### Metadata

* ID: 19c28091-b3ad-affb-6343-47d7fa066d55 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**

**Comment by SeppPenner** [comment]
I assume that this is related to https://github.com/dotnet/docs/issues/38789#issuecomment-1860952562 (Where I tried to find use cases that work and some that don't).

**Comment by IEvangelist** [comment]
Same here as #38829, let's circle back around with @baronfel... I wonder if these are related issues.

**Comment by baronfel** [comment]
This is definitely an issue with passing semicolon-delimited values as a property via the existing MSBuild command line API. You have to escape the arguments differently for each shell. For example, on `bash` shell `-p ContainerImageTags='1.2.3-alpha2;latest'` should be the correct form of the arguments, but this doesn't work for Powershell.

One thing that should work consistently is taking advantage of the fact that MSBuild will use environment variable values for Properties if they exist. So you could do something like this and it should work too:

```bash
$ ContainerImageTags='1.2.3-alpha2;latest' dotnet publish ....
```

e.g. setting the environment variable for the scope of the command.

**Comment by SeppPenner** [comment]
> This is definitely an issue with passing semicolon-delimited values as a property via the existing MSBuild command line API. You have to escape the arguments differently for each shell. For example, on `bash` shell `-p ContainerImageTags='1.2.3-alpha2;latest'` should be the correct form of the arguments, but this doesn't work for Powershell.
> 
> One thing that should work consistently is taking advantage of the fact that MSBuild will use environment variable values for Properties if they exist. So you could do something like this and it should work too:
> 
> ```shell
> $ ContainerImageTags='1.2.3-alpha2;latest' dotnet publish ....
> ```
> 
> e.g. setting the environment variable for the scope of the command.

Thank you for the detailed information. In my case, it's bash (Well technically Gitlab CI bash). Thanks for the update in the docs as well.
