### ISSUE TITLE
[C# 12]: New Feature - `ref readonly` parameters (API documentation)

### ISSUE THREAD

**Issue by hamarb123** [dotnet/docs#38783]
### Visual Studio release

None

### Link to speclet

- [Speclet](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/ref-readonly-parameters.md)

### Link to Pull request

- [PR](https://github.com/dotnet/roslyn/pulls/nnnnn)

### New behavior

APIs which use `ref readonly` parameters are misleadingly shown with `ref` on the docs pages in .NET 8.0+
For example: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.asref?view=net-8.0#system-runtime-compilerservices-unsafe-asref-1(-0@)

### Areas affected

- [ ] **Add to What's new in C# 12**: Add links to updated docs in the What's new in C# 12 article.
- [ ] **Update language reference**: Detail the areas in the language reference that will be updated for this feature.
- [ ] **Update compiler messages**: Add new (or updated) pages for new compiler messages. Include related message.
- [ ] *Include in *Everyday C#* section**: Is this new feature included in Everyday C#?
- [ ] **Tutorials**: Are new tutorials required for this feature? If so, detail below

**Comment by hamarb123** [comment]
To be clear, not a clone of https://github.com/dotnet/docs/issues/36682 - this is about updating the API signatures to show `ref readonly`, not `ref` for `ref readonly` parameters.

**Comment by BillWagner** [comment]
Adding @gewarren 

Is there a work item to update mdoc to add the `readonly` modifier for those APIs that need it?

**Comment by gewarren** [comment]
> Is there a work item to update mdoc to add the `readonly` modifier for those APIs that need it?

I just created one: https://dev.azure.com/ceapex/Engineering/_workitems/edit/933095

**Comment by BillWagner** [comment]
I will close this, as the fix is to mdoc and it's being tracked there.
