### ISSUE TITLE
When building an image with -p parameters, the setting from the project file for the image name is ignored

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/docs#38789]
### Type of issue

Typo

### Description

MSBuild-Version 17.8.3+195e7f5a3 für .NET

When running `dotnet publish -p ContainerImageTags='"1.2.3"' -c Release /t:PublishContainer` on a project file with the following docker build specific entries in the project file

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>NU1803</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContainerImageName>test.server</ContainerImageName>
    <ContainerBaseImage>docker.io/sepppenner/aspnet:8.0</ContainerBaseImage>
</PropertyGroup>
```

this leads to a docker image with the following settings:

```log
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
<none>                         <none>    d5270677c0a7   10 minutes ago      1.59GB
```

If I understood correctly, `ContainerImageName` is replaced by `ContainerRepository` in Net8 (I use Net8 as base image), but neither of the settings seems to have an impact when tags are specified with the publish command via command line.

When just using `dotnet publish -c Release /t:PublishContainer`, the container image name is set properly with `ContainerImageName` as well as with `ContainerRepository`.
It seems that the tags are breaking the setting for the image name.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-7-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

@IEvangelist

### Metadata

* ID: 19c28091-b3ad-affb-6343-47d7fa066d55 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**

---
[Associated WorkItem - 193065](https://dev.azure.com/msft-skilling/Content/_workitems/edit/193065)

**Comment by IEvangelist** [comment]
I notice that your TFM is `net7.0` instead of `net8.0`. I'd recommend correcting that, but let's ask @baronfel if he knows.

**Comment by baronfel** [comment]
net7.0 works as well with the tech, that's all fine.

Do you have an https://aka.ms/binlog you can share? If you're using the NuGet package for the tools, what version are you using? And what version of the . NET SDK are you on?

**Comment by SeppPenner** [comment]
> I notice that your TFM is `net7.0` instead of `net8.0`. I'd recommend correcting that, but let's ask @baronfel if he knows.

7.0 should work as well (And I'm not yet done with the Blazor migration for net8.0).

**Comment by SeppPenner** [comment]
> net7.0 works as well with the tech, that's all fine.
> 
> Do you have an https://aka.ms/binlog you can share? If you're using the NuGet package for the tools, what version are you using? And what version of the . NET SDK are you on?

I created the binlog file and added it here https://github.com/SeppPenner/DockerBinLog.

```bash
dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.114 [C:\Program Files\dotnet\sdk]
7.0.404 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by IEvangelist** [comment]
I'm curious, @SeppPenner - could you try a name without a `"."` in between it? Don't that it's an issue, just working through the process of elimination.

**Comment by IEvangelist** [comment]
I cannot recreate this issue locally. I've been trying all morning, but I'm still going to update the corresponding doc to make it even more fail-safe.

**Comment by baronfel** [comment]
Ok I dug into the binlog a bit (thanks @SeppPenner!) and I see that the `ContainerImageTags` you provided are flowed through correctly into the `ParseContainerProperties` Task (where we validate their format), but no validated tags are returned from that Task. That implies that the tags failed validation in some way. I _suspect_ that the quotes are impacting the parsing here - the value being passed for `ContainerImageTags` is `'1.2.3'` (note the single-quotes) which I believe may be failing in a subtle way. Can you try passing the ContainerImageTags in another way that might sidestep shell-escaping constraints? A couple options:

* set `ContainerImageTags` directly in the project file
* set `ContainerImageTags` as an environment variable before building - in bash this would be `ContainerImageTags="1.2.3" dotnet publish ....`.

**Comment by SeppPenner** [comment]
> I'm curious, @SeppPenner - could you try a name without a `"."` in between it? Don't that it's an issue, just working through the process of elimination.
> 
> Also, when you run:
> 
> ```
> dotnet publish -c Release /t:PublishContainer
> ```
> 
> What is the name you get?

The name is `sepppenner/ivu.portal.server:latest` in this case.

E.g. see the following statement from the output as well (Even if its German 😄): `Das Image „ivu.portal.server“ mit den Tags „latest“ wird auf dem Basisimage „docker.io/sepppenner/aspnet:8.0“ erstellt.` --> `The image "ivu.portal.server" with the tags "latest" is created on the base image "docker.io/sepppenner/aspnet:8.0".`

![grafik](https://github.com/dotnet/docs/assets/9639361/74675033-5086-4928-833b-53f2a410e497)

**Comment by SeppPenner** [comment]
> I cannot recreate this issue locally. I've been trying all morning, but I'm still going to update the corresponding doc to make it even more fail-safe.

Ok, still thank you for your patience.

**Comment by IEvangelist** [comment]
> > I cannot recreate this issue locally. I've been trying all morning, but I'm still going to update the corresponding doc to make it even more fail-safe.
> 
> Ok, still thank you for your patience.

No worries—let's keep trying to figure this out. What is the exact `dotnet publish` command you're using? It seems like @baronfel thinks it might have something to do with the quotes around the tags? Did you try any variations of that?

**Comment by SeppPenner** [comment]
> set ContainerImageTags directly in the project file

1. `dotnet publish -c Release /t:PublishContainer` with `<ContainerImageTags>1.2.3</ContainerImageTags>` in the project ✅ --> Works:

```bash
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
ivu.portal.server              1.2.3     0ecb50d272f8   34 seconds ago      1.78GB
```

2. `dotnet publish -c Release /t:PublishContainer` with `<ContainerImageTags>"1.2.3"</ContainerImageTags>` in the project (Yes, strange syntax, but still) ⚠️ --> Doesn't work, but I guess is intended:

```bash
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
<none>                         <none>    41fbe41109ae   53 seconds ago      1.78GB
```

> set ContainerImageTags as an environment variable before building

`dotnet publish -c Release /t:PublishContainer` with `ContainerImageTags="1.2.3"` as environment variable ✅ --> Works:

```bash
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
ivu.portal.server              1.2.3     24195801f153   2 minutes ago       1.78GB
```


Some other tries:

1. `dotnet publish -p ContainerImageTags="1.2.3" -c Release /t:PublishContainer` ✅ --> Works:

```bash
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
ivu.portal.server              1.2.3     e1e61c85e810   31 seconds ago      1.78GB
```

2. `dotnet publish -p ContainerImageTags='1.2.3' -c Release /t:PublishContainer` ⚠️ --> Doesn't work (Maybe intended?)

```bash
REPOSITORY                     TAG       IMAGE ID       CREATED             SIZE
<none>                         <none>    4d9eba3b194d   56 seconds ago      1.78GB
```

--> It seems like this is statement is not correct (There is another issue with multiple tags anyway):

> When using ContainerImageTags, the tags are delimited by a ; character. If you're calling dotnet publish from the command line (as is the case with most CI/CD environments), you'll need to outer wrap the values in a single ' and inner wrap with double quotes ", for example (='"tag-1;tag-2"'). Consider the following dotnet publish command:

**Comment by SeppPenner** [comment]
> > > I cannot recreate this issue locally. I've been trying all morning, but I'm still going to update the corresponding doc to make it even more fail-safe.
> > 
> > 
> > Ok, still thank you for your patience.
> 
> No worries—let's keep trying to figure this out. What is the exact `dotnet publish` command you're using? It seems like @baronfel thinks it might have something to do with the quotes around the tags? Did you try any variations of that?

Yeah, I was already testing different things at the time you wrote this. I have tried several variants (Even with `ContainerImageTag` and `ContainerImageTags` and it seems that there is still something weird in how the tags are loaded / the statement in the docs is wrong regarding the double-quotation.

**Comment by SeppPenner** [comment]
Er, what exactly is the solution now? I mean, using the single quotes in combination with double quotes with tags (Using multiple tags, not just one tag) doesn't work (I have created a separate issue for that).

Using ...Tag="" is fine for my use case, though.

**Comment by SeppPenner** [comment]
@IEvangelist Would it be an idea to extend the section (See image below) so that it is more clear that you can use `dotnet publish -p ContainerImageTag="1.2.3-alpha2"` for single tags (e.g. a **Copy for command line section** for this as well)?

![grafik](https://github.com/dotnet/docs/assets/9639361/18704d70-96f4-448f-addb-0ded1700a507)


E.g like this:

To override the default, specify either of the following:
```xml
<PropertyGroup>
    <ContainerImageTag>1.2.3-alpha2</ContainerImageTag>
</PropertyGroup>
```

or use the command line for single tags:

```netcli
dotnet publish -p ContainerImageTag='1.2.3-alpha2"
```

To specify multiple tags, ...
