### ISSUE TITLE
[Breaking change]: .NET SDK 8.0.200 and newer will require 17.8 MSBuild and Visual Studio

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#38803]
### Description

Per prior guidance on the minimum VS version that an SDK will load in, 7.0.200 will be updated to require 17.4 or newer version of Visual Studio. The change has been merged into the SDK repo and should be in daily installable builds by end of the week. It will ship starting in the January preview of 7.0.200 and GA in February.

[.NET SDK, MSBuild, and Visual Studio versioning - .NET Core | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules)

See https://github.com/dotnet/docs/issues/33003 for the last time we did this and the documentation we created.

### Version

.NET 8 GA

### Previous behavior

8.0.100 will load into 17.7 when targeting 7.0 and lower runtime versions.

### New behavior

8.0.200 will require using Visual Studio/MSBuild 17.8 or newer

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

We do this to enable .NET SDK partners to have a reliable minimum version of Visual Studio that they can expect to work against. We always wait one quarter before updating the requirement.

### Recommended action

We do this to enable .NET SDK partners to have a reliable minimum version of Visual Studio that they can expect to work against. We always wait one quarter before updating the requirement.

### Feature area

SDK

### Affected APIs

If you need to use 8.0.200, upgrade your Visual Studio version. Alternatively, you can use a [global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to pin to an older 8.0.100 stand-alone SDK install.

---
[Associated WorkItem - 206394](https://dev.azure.com/msft-skilling/Content/_workitems/edit/206394)

**Comment by pwnkunwar** [comment]
![Uploading stockphoto (1).png…]()
hello
