### ISSUE TITLE
Using the `required` keyword is the sample is confusing

### ISSUE THREAD

**Issue by aelij** [dotnet/docs#38812]
### Type of issue

Other (describe below)

### Description

The code sample uses the `required` keyword:

https://github.com/dotnet/docs/blob/baa00bd0b3715e686afc52d56b082ebb3cae10e0/docs/core/extensions/snippets/configuration/console-json/SettingsOptions.cs#L9-L16

This keyword has no effect on the generator (or on `ValidateDataAnnotations` AFAIK), and so IMO is a bit confusing. I suggest removing it, or at least adding a tip indicating this.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/options-validation-generator

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-validation-generator.md

### Document Version Independent Id

0775474e-7773-d061-ed21-0a360c8466b1

### Article author

@tarekgh

### Metadata

* ID: 533f4fc6-bb7c-874d-6639-ea215af95ed3 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 194111](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194111)

**Comment by aelij** [comment]
Note this file is also referenced in https://learn.microsoft.com/en-us/dotnet/core/extensions/options

**Comment by BillWagner** [comment]
I'd suggest that both pages should link to the C# [`required`](https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/required) keyword. 

Briefly, the `required` keyword forces callers to set that property when constructing an object of that type.

**Comment by aelij** [comment]
@BillWagner But those classes are not instantiated in code but rather by the options runtime, which means `required` really doesn't do anything in this case. It makes the reader _think_ it would be used by the validator, which is unnecessarily confusing.

**Comment by IEvangelist** [comment]
> @BillWagner But those classes are not instantiated in code but rather by the options runtime, which means `required` really doesn't do anything in this case. It makes the reader _think_ it would be used by the validator, which is unnecessarily confusing.

The original thinking was that in the event that a consumer attempted to create an `IOptions<SettingsOptions>` instance using the `Options.Create<SettingsOptions>(...)` API, they'd be restricted (or `required`) to do the correct thing.

**Comment by aelij** [comment]
> The original thinking was that in the event that a consumer attempted to create an IOptions<SettingsOptions> instance using the Options.Create<SettingsOptions>(...) API, they'd be restricted (or required) to do the correct thing.

Fine, then please add a note that it does not affect validation.
