### ISSUE TITLE
Specifiying custom target ContainerRepository requires to do a login to dockerhub (CONTAINER1008)

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/docs#38829]
### Type of issue

Code doesn't work

### Description

I have a project file that looks like this:

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>NU1803</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContainerRepository>somecontainerrepo.de/test.server</ContainerRepository>
    <ContainerBaseImage>docker.io/sepppenner/aspnet:8.0</ContainerBaseImage>
    <ContainerRegistry>somecontainerrepo.de</ContainerRegistry>
</PropertyGroup>
```

and in my CI / CD pipeline, I do a docker login for `somecontainerrepo.de` (This is only a dummy of course) like this before I publish the container:

```yaml
- docker login ${DOCKER_REPOSITORY} -u service -p ${HARBOR_PASSWORD}
- dotnet publish -c Release --output publish/ -p ContainerImageTags="${VERSION}" /t:PublishContainer
```

If I understand https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md correctly, afterwards the login credentials should be set:

> The auths section of the config.json file is a key/value map between registry names and Base64-encoded username:password strings. In a 'default' Docker scenario, **running docker login <registry> -u <username> -p <password> will create new items in this map.**

However, in the CI / CD pipeline, I get an issue that the login for **docker.io** is not found:
`Microsoft.NET.Build.Containers.Credentials.CredentialRetrievalException: CONTAINER1008: Failed retrieving credentials for "docker.io": No matching auth specified for registry 'docker.io' in Docker config.` --> Why do I need to specify credentials for **docker.io** if I don't want to push to **docker.io**, but another (HTTPS-based) docker container repository (E.g. **somecontainerrepo.de**)?

Pulling the base image `docker.io/sepppenner/aspnet:8.0` should work without authentication either...

Or is the issue that I shouldn't specify **somecontainerrepo.de/test.server** as `ContainerRepository`, but only **test.server** as the `ContainerRegistry` already contains **somecontainerrepo.de**?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

@IEvangelist

### Metadata

* ID: 19c28091-b3ad-affb-6343-47d7fa066d55 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**

**Comment by IEvangelist** [comment]
Tagging @baronfel on this one, as he's the subject matter expert.

**Comment by baronfel** [comment]
Hey @SeppPenner - `ContainerRepository` in this case should only be the name portion of your image, so in the example you have above you'd use `<ContainerRepository>test.server</ContainerRepository>` instead. The domain name of the registry you want to push to will be the `ContainerRegistry` as you've correctly set.

Regarding the use of the different Docker Hub registry urls, the docs currently state the following:

```
When using Docker Hub as a base image registry (via ContainerBaseImage) or as the destination registry for pushing your images (via ContainerRegistry), you must use the one of the URLs that point to the registry portion of Docker Hub. This means one of the following domains must be used:

*     registry.hub.docker.com
*    registry-1.docker.io
```

This is out of date with the 8.0.100 .NET SDK - @tmds did some work here to make the tooling automatically use the correct domains when users point to `docker.io`. So we need to update that documentation to match.

Hope this helps!

**Comment by SeppPenner** [comment]
> Hey @SeppPenner - `ContainerRepository` in this case should only be the name portion of your image, so in the example you have above you'd use `<ContainerRepository>test.server</ContainerRepository>` instead. The domain name of the registry you want to push to will be the `ContainerRegistry` as you've correctly set.

Thank you, I will try that.

**Comment by SeppPenner** [comment]
> This is out of date with the 8.0.100 .NET SDK - @tmds did some work here to make the tooling automatically use the correct domains when users point to docker.io. So we need to update that documentation to match.

Would be great to update the docs here as this might confuse some people :D

**Comment by baronfel** [comment]
I put a PR out to the SDK Containers repo yesterday to do just that. Hopefully that should clear things up :)

**Comment by SeppPenner** [comment]
Strange... My project now looks like this:

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>NU1803</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContainerRepository>test.server</ContainerRepository>
    <ContainerBaseImage>docker.io/sepppenner/aspnet:8.0</ContainerBaseImage>
    <ContainerRegistry>somecontainerrepo.de</ContainerRegistry>
</PropertyGroup>
```

and I run the following command `dotnet publish -c Release --output publish/ -p ContainerImageTags="${VERSION}" /t:PublishContainer`. However, it still seems to fail with the same error:

```log
/usr/share/dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error MSB4018: The "CreateNewImage" task failed unexpectedly. [/builds/test/test-server/src/Test.Server/Test.Server.csproj]
/usr/share/dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error MSB4018: Microsoft.NET.Build.Containers.Credentials.CredentialRetrievalException: CONTAINER1008: Failed retrieving credentials for "docker.io": No matching auth specified for registry 'docker.io' in Docker config. [/builds/test/test-portal/src/Test.Server/Test.Server.csproj]
```

I mean, I use `docker.io/sepppenner/aspnet:8.0` as base image, of course. But just for pulling the base image, a docker login to docker.io shouldn't be required, I guess?

I try to update the base image to the latest version of Net8. Maybe that helps...

**Comment by tmds** [comment]
> I use docker.io/sepppenner/aspnet:8.0 as base image, of course. But just for pulling the base image, a docker login to docker.io shouldn't be required, I guess?

.NET tries to find the credentials only when receiving an `HttpStatusCode.Unauthorized` response:

https://github.com/dotnet/sdk/blob/e9d13cbe7e8c1d52ce276a8655f52a87e1017c46/src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs#L331C31-L331C53

Does it work when you provide credentials, either through `docker login` or using the [envvars](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md#authentication-via-environment-variables)?

**Comment by SeppPenner** [comment]
> > I use docker.io/sepppenner/aspnet:8.0 as base image, of course. But just for pulling the base image, a docker login to docker.io shouldn't be required, I guess?
> 
> .NET tries to find the credentials only when receiving an `HttpStatusCode.Unauthorized` response:
> 
> https://github.com/dotnet/sdk/blob/e9d13cbe7e8c1d52ce276a8655f52a87e1017c46/src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs#L331C31-L331C53
> 
> Does it work when you provide credentials, either through `docker login` or using the [envvars](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md#authentication-via-environment-variables)?

That works. But now I get another issue (Again):


With the following setup in the project:

```xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>NU1803</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ContainerRepository>/test/test.server</ContainerRepository>
    <ContainerBaseImage>docker.io/sepppenner/aspnet:8.0</ContainerBaseImage>
    <ContainerRegistry>somecontainerrepo.de</ContainerRegistry>
</PropertyGroup>
```

and the following commands (One login for our [harbor](https://goharbor.io/) repo, one for docker.io):

```yaml
- docker login ${HARBOR_REPOSITORY} -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD}
- docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
```

I get the following error now:

```log
/usr/share/dotnet/sdk/8.0.101/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error CONTAINER1013: Failed to push to the output registry: CONTAINER1001: Failed to upload blob using POST https://somecontainerrepo.de/v2/test/test.server/blobs/uploads/; received status code 'Forbidden'. [/builds/test/test.server/src/Test.Server.csproj]
```

Not sure if this is related to `<ContainerRepository>/test/test.server</ContainerRepository>` instead of `<ContainerRepository>test.server</ContainerRepository>`? --> The thing is that I need the `group` (Or whatever it's called) to work properly with harbor.
