### ISSUE TITLE
Review the allowed fast-path mode for dotnet8

### ISSUE THREAD

**Issue by jgarciadelanoceda** [dotnet/docs#38832]
### Type of issue

Outdated article

### Description

I was having an issue when NumberHandling in dotnet7, but I think that for dotNet8 is solved via the attribute JsonSourceGenerationOptions.

See the issue    #https://github.com/dotnet/runtime/issues/79511

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation-modes?pivots=dotnet-8-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/source-generation-modes.md

### Document Version Independent Id

84bae7b9-7b02-e65c-98c7-c7e1b5b0282e

### Article author

@gewarren

### Metadata

* ID: 3f9798ac-dcf2-87e2-db51-a8d69cd3590c 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@eiriktsarpalis Is the NumberHandling option now support for fast-path serialization?

**Comment by eiriktsarpalis** [comment]
While a `NumberHandling` option has been exposed on the `JsonSourceGenerationOptionsAttribute`, this merely governs the configuration of the generated `Default` context instance. It still is the case that fast-path isn't supported when custom number handling has been enabled.
