### ISSUE TITLE
Grammar: When an Ubuntu version falls out of support, .NET is no longer supported with that version.

### ISSUE THREAD

**Issue by burnchar** [dotnet/docs#38847]
### Type of issue

Typo

### Description

When **an** [Ubuntu version](https://wiki.ubuntu.com/Releases) falls out of support, .NET is no longer supported with that version.

s/an/a

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

@adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
HI @burnchar I was going through my backlog of missed items and found this one. I believe this is correct. The pronunciation starts with the sound "oo" as in "book" and not "yu". The official Ubuntu docs also use "an Ubuntu image" when talking about downloading.

Please feel free to respond and reopen if you don't agree.
