### ISSUE TITLE
i am facing this issues

### ISSUE THREAD

**Issue by Sushmitapoojar** [dotnet/docs#38860]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
please help

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0161?f1url=%3FappId%3Droslyn%26k%3Dk(CS0161)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0161.md

### Document Version Independent Id

f3763810-1049-afbe-f279-fa72ea36a99c

### Article author

@BillWagner

### Metadata

* ID: 206b5eae-0d27-4afc-ac55-b3c1705096db 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @Sushmitapoojar 


Did you need more information about this error? Generally, it means that you've declared a method with a non-void return type and you're method doesn't have an argument on the `return` statement. 

If you need more specific help, you should post a short sample on our [Q & A](https://learn.microsoft.com/en-us/answers/tags/309/csharp) site. Members of the community will help you work through specific problems.
