### ISSUE TITLE
Page implies the name of the generated method when using top-level statements is `Main`, but it's not,  according to another page.

### ISSUE THREAD

**Issue by joseville1001** [dotnet/docs#38866]
### Type of issue

Other (describe below)

### Description

The following are direct quotes from the docs page in question:

> The compiler synthesizes a Program class with a Main method and places all your top level statements in that Main method.

> The compiler generated class and Main method are declared in the global namespace.

These quotes imply that the name of the generated method is `Main`, but this is inconsistent with [another docs page](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#:~:text=The%20compiler%20generates%20a%20method%20to%20serve%20as%20the%20program%20entry%20point%20for%20a%20project%20with%20top%2Dlevel%20statements.%20The%20name%20of%20this%20method%20isn%27t%20actually%20Main%2C%20it%27s%20an%20implementation%20detail%20that%20your%20code%20can%27t%20reference%20directly.) which states

> The compiler generates a method to serve as the program entry point for a project with top-level statements. The name of this method isn't actually Main, it's an implementation detail that your code can't reference directly.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md

### Document Version Independent Id

926db74c-be79-f7cd-a4e9-e156dafa6287

### Article author

@tdykstra

### Metadata

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
cc @BillWagner
