### ISSUE TITLE
Problem in returning control to the UI

### ISSUE THREAD

**Issue by kamyarizadi** [dotnet/docs#38872]
### Type of issue

Code doesn't work

### Description

In the below code:
////////////////////////////////////////////////////////////////////////////////////////////////////////
static DamageResult CalculateDamageDone()
{
    return new DamageResult()
    {
        // Code omitted:
        //
        // Does an expensive calculation and returns
        // the result of that calculation.
    };
}

s_calculateButton.Clicked += async (o, e) =>
{
    // This line will yield control to the UI while CalculateDamageDone()
    // performs its work. The UI thread is free to perform other work.
    var damageResult = await Task.Run(() => CalculateDamageDone());
    DisplayDamage(damageResult);
};
/////////////////////////////////////////////////////////////////////////////////////
I think [await Task.Run(() => CalculateDamageDone());] does not free the UI thread because the event handler is run in the context of UI thread and the code is waiting by await command . So the UI thread is blocked until the new thread [ Task.Run(()] is finished.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-scenarios

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/async-scenarios.md

### Document Version Independent Id

77bdee53-c2a0-e16f-c93a-3ca0afae0b93

### Article author

@BillWagner

### Metadata

* ID: d885f1eb-2b37-693b-c91f-74b748c9424a 
* Product: **dotnet-csharp**
* Technology: **csharp-async**

**Comment by BillWagner** [comment]
Hi @kamyarizadi 

The code you reference works correctly. `Task.Run` starts a task on a background thread and returns the `Task`. The `await` expression returns control to the caller immediately. The remaining code in the method runs after the task has completed. 

I'll close this as by-design.
