### ISSUE TITLE
can't download .net8 on Ubuntu 22.04？

### ISSUE THREAD

**Issue by MengYuanHan** [dotnet/docs#38876]
### Type of issue

Typo

### Description

使用官方文档写的命令无法下载.net8

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-scripted-manual#scripted-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md

### Document Version Independent Id

2be3647d-495b-c9f0-cf06-9a7bf687d3bb

### Article author

@adegeo

### Metadata

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment]
Hello. It's working for me. Can you please share your terminal input and output?
