### ISSUE TITLE
Does dotnet restore support -p?

### ISSUE THREAD

**Issue by Tripletri** [dotnet/docs#38871]
### Type of issue

Missing information

### Description

Passing MsBuild parameters to `dotnet restore` is useful in some cases, but without documentation about this feature, it is unknown whether this is simply a lack of documentation or if it is a hacky way of using `dotnet restore`.

Also for people who do not know the details of how `dotnet restore` works, it is not obvious that parameters can be passed to MsBuild from `dotnet restore`.

For `dotnet build` it is explicitly specified that `-p` is supported and [section for MsBuild](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild) exists. `dotnet restore` also calls MsBuild and passes all switches to it, so I think a section for MsBuild should also exists in `dotnet restore` docs.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-restore.md

### Document Version Independent Id

0b993779-65a2-6092-4047-2fc2ec16170b

### Article author

@tdykstra

### Metadata

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 195494](https://dev.azure.com/msft-skilling/Content/_workitems/edit/195494)

**Comment by tdykstra** [comment]
cc @baronfel

**Comment by baronfel** [comment]
This is technically correct (properties will be passed through to the evaluation), though in general we recommend that a 'bare' Restore should restore as many dependencies of a project as possible - meaning don't try to be too fancy and do things like add `Condition`s to `PackageReferences` that are very bespoke. Restore works best when it can be run once and when all `RuntimeIdentifiers` of a project are known at evaluation time. This prevents re-Restores from happening in situations like `publish`ing for another architecture/RID.

**Comment by Tripletri** [comment]
Ok, this is possible, but do not fall into the idea that `resotre` should restore as many dependencies as possible for reuse in the future.

In my case, on the contrary, it is necessary to restore only the necessary dependencies. Without going into too much detail, I need to run `dotnet test` on a multi-target project (net6.0;net8.0) in a Docker container. So if I use `mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim` I can do a `restore` but can't run the `test` for net6.0 and if I use `mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim` I can't do a `restore` without `-p TargetFramework=net6.0`.

Thanks for the answer.
