### ISSUE TITLE
The requirement/prerequisites of .NET 6.0 SDK contradict the information about the use of `commandLineArgs` in launchSettings.json since .NET 7.0

### ISSUE THREAD

**Issue by eriawan** [dotnet/docs#38883]
### Type of issue

Outdated article

### Description

The requirement/prerequisites of .NET 6.0 SDK contradict the information about the use of `commandLineArgs` in launchSettings.json since .NET 7.0 Preview 1, and the Debug properties is only available saved in launchSettings.json since .NET 7.0 too.
For example:

## Suggestions

Also now since .NET 7.0 is not supported, we should state that we require at least .NET 6.0 SDK but we should recommend to use .NET 8.0 SDK for now to ensure that it is still relevant in 2024.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/commandline/get-started-tutorial.md

### Document Version Independent Id

fa160b1d-66ed-8c5d-37cd-b7e02443e9f1

### Article author

@tdykstra

### Metadata

* ID: 7705dc41-7297-0807-7e9c-2e6548c26b84 
* Product: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
Thank you for the suggestion. But the System.CommandLine articles have a disclaimer at the top of each article noting that the documentation is pre-release for version 2.0 beta 4, which is still the most current package version in NuGet. When the next version is made available the documentation will be updated.

cc @jonsequitur

**Comment by eriawan** [comment]
@tdykstra 

I see, thanks for your explanation about being in preview! Makes sense now.
