### ISSUE TITLE
Improper exception handling demonstration

### ISSUE THREAD

**Issue by jinek** [dotnet/docs#3888]
On this page https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.contentcontrol.contenttemplateselector?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Controls.ContentControl.ContentTemplateSelector);k(VS.XamlEditor);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7)%26rd%3Dtrue&view=netframework-4.7.1
There is an example with following code:
`catch
            {
                return null;
            }`
The behavior of this code does not match the expectations. For example, catched OutOfMemoryException or NullReferenceException do not mean we should provide empty Template. Better to rewrite that as
'catch(FormatException)
{
return null;
}'

**Comment by mairaw** [comment]
Thanks @jinek, that's a good suggestion. Do you wanna try to submit a PR for this? Otherwise, we can handle it.

**Comment by jinek** [comment]
Yes, would be great. Let me do this.

**Comment by jinek** [comment]
@mairaw May I also refactor it a little bit, like removing `Application.Current.MainWindow;` and adding numberTemplate and largeNumberTemplate properties instead.

Also what I see is code does not match the behavior description. There is nothing said about cases when "null" template will be used. As I see it is better to remove some null returns instead of DataTemplate. If we want to explain some exception handling technique it's better to rethrow the exception ( https://github.com/jinek/docs/blob/52d3ef051f577fe16347082413a89d1dbb19ac6a/samples/snippets/csharp/VS_Snippets_Wpf/ContentControlTemplateSelector/CSharp/Window1.xaml.cs ) or not to catch it at all as exception handling is out of the example subject:
![image](https://user-images.githubusercontent.com/10516222/34064352-50d9a582-e21e-11e7-81b7-0ea37fd6d07f.png)
In this way (picture demonstrated) reader can get information more easily as it shows twice less code.

**Comment by mairaw** [comment]
Feel free to refactor and will review your suggestions. Thanks @jinek!

**Comment by mabumann** [comment]
I propose that the class name is modified from NumderDataTemplateSelector to NumberDataTemplateSelector.

**Comment by mairaw** [comment]
Yes, @mabumann. @jinek is doing that already on the PR #4016. I just have a final question to him on that PR before we finish this issue.

**Comment by jinek** [comment]
I will make changes to VB also in a few days

**Comment by mairaw** [comment]
Thank you @jinek! I was going to tell you I was going to do the VB part today, but we can wait a few days if you wanna finish it. Either way works. Thanks so much!
