### ISSUE TITLE
.NET 8.0 sdk is not available in alpine 3.18.0's package manager

### ISSUE THREAD

**Issue by PiotrJustyna** [dotnet/docs#38904]
### Type of issue

Outdated article

### Description

.net 7 sdk is available, but not dotnet 8:

```bash
aab62cd926f8# apk search dotnet
dotnet-bash-completion-7.0.114-r0
dotnet-doc-7.0.114-r0
dotnet-host-7.0.14-r0
dotnet-zsh-completion-7.0.114-r0
dotnet6-apphost-pack-6.0.25-r0
dotnet6-artifacts-6.0.125-r0
dotnet6-build-6.0.125-r0
dotnet6-hostfxr-6.0.25-r0
dotnet6-runtime-6.0.25-r0
dotnet6-sdk-6.0.125-r0
dotnet6-stage0-6.0.116-r3
dotnet6-stage0-artifacts-6.0.116-r3
dotnet6-stage0-bootstrap-6.0.116-r3
dotnet6-targeting-pack-6.0.25-r0
dotnet6-templates-6.0.125-r0
dotnet7-apphost-pack-7.0.14-r0
dotnet7-artifacts-7.0.114-r0
dotnet7-build-7.0.114-r0
dotnet7-hostfxr-7.0.14-r0
dotnet7-runtime-7.0.14-r0
dotnet7-sdk-7.0.114-r0
dotnet7-stage0-7.0.105-r3
dotnet7-stage0-artifacts-7.0.105-r3
dotnet7-stage0-bootstrap-7.0.105-r3
dotnet7-targeting-pack-7.0.14-r0
dotnet7-templates-7.0.114-r0
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#install-net-7

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md

### Document Version Independent Id

f066a748-0a7d-7506-3b18-c422fef13293

### Article author

@adegeo

### Metadata

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by Salgat** [comment]
Just saw this, made a similar issue yesterday: https://github.com/dotnet/core/issues/8904#issuecomment-1879128612

**Comment by J0F3** [comment]
Same for Alpine 3.19

**Comment by adegeo** [comment]
Thanks. Correct, it's not available in the package manager. I'm updating the support table to reflect this.
