### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by codescafe** [dotnet/docs#38906]
### Type of issue

Typo

### Description

In Chinese, both "property" and "attribute" are commonly translated as "属性", To avoid confusion, we typically use "特性" to refer to "attribute" and “属性" to refer to "property".

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/features

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/features.md

### Document Version Independent Id

a9660605-7ea0-31c9-a19e-a9e6ff9fb8bf

### Article author

@BillWagner

### Metadata

* ID: ecc8ea36-913a-26ac-f85d-90ce5fbd2f7d 
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**

**Comment by BillWagner** [comment]
Thanks for pointing this out to us @codescafe 

Our localization team uses an internal Azure Dev Ops board, and I created a [new issue](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/935834) to track it.

I realize that link isn't published, but the correct folks are working on it.

Closing as transferred to the correct team.
