### ISSUE TITLE
Y/N Prompt?

### ISSUE THREAD

**Issue by jonathanlocke** [dotnet/docs#38926]
### Type of issue

Missing information

### Description

Is there a way to skip the y/n prompts?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-migrate

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-migrate.md

### Document Version Independent Id

ad0dfb99-7a86-f3a6-69c8-a18399b0c095

### Article author

@tdykstra

### Metadata

* ID: e78ee146-356e-ccf4-5f87-7726a1498943 
* Product: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
>This command is deprecated. The `dotnet migrate` command is no longer available starting with .NET Core 3.0 SDK. It can only migrate a Preview 2 .NET Core project to a 1.x .NET Core project, which is out of support.
