### ISSUE TITLE
Broken security link in Important note of documentation.

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#3893]
about this documentation page: 
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.unsafedeserialize?view=netframework-4.7.1#System_Runtime_Serialization_Formatters_Binary_BinaryFormatter_UnsafeDeserialize_System_IO_Stream_System_Runtime_Remoting_Messaging_HeaderHandler_

which is this github page:
https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Serialization.Formatters.Binary/BinaryFormatter.xml

There is this on the documentation page:

> Important
Calling this method with untrusted data is a security risk. Call this method only with trusted data. For more information, see Untrusted Data Security Risks.

but the link to **Untrusted Data Security Risks** is broken.
It links to http://curah.microsoft.com/57301 but does not exist anymore (curah.microsoft.com/...)

**Comment by mairaw** [comment]
Thanks @wstaelens. @Rick-Anderson are you familiar with this link? I've searched and found this link with your name on it: https://docs.com/rick-anderson-1/8710/untrusted-data-security-risks?   😄

**Comment by Rick-Anderson** [comment]
I would point to https://www.owasp.org/index.php/Data_Validation

**Comment by Rick-Anderson** [comment]
Here is the link to the original
https://docs.com/rick-anderson-1/8710/untrusted-data-security-risks

**Comment by Rick-Anderson** [comment]
BTW, the above link is only good for 2 more days
Important notice: We are retiring Docs.com on December 15, 2017, and all content will be deleted.

**Comment by mairaw** [comment]
I like your suggestion @Rick-Anderson. Thanks!

**Comment by mairaw** [comment]
The same link shows up in other files too: https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D330378&type=
