### ISSUE TITLE
System.IO.Path.AltDirectorySeparatorChar on Unix is not '\'

### ISSUE THREAD

**Issue by rmadsen-ks** [dotnet/docs#3894]
# System.IO.Path.AltDirectorySeparatorChar on Unix is not '\\'

System.IO.Path.AltDirectorySeparatorChar on Unix is not '\\', its actually '/' which is the same as System.IO.Path.DirectorySeparatorChar.

Tested on Linux 4.10.0-40-generic Ubuntu 17.04, with .NET Core v2.0.2.

**Edit:** Escaped '\\' in text otherwise they'd show up as ''.

**Comment by mairaw** [comment]
@JeremyKuhne, @pjanotti can you guys confirm the behavior? I'm not being able to get a Linux machine working quickly.

**Comment by pjanotti** [comment]
Hi @rmadsen-ks the `AltDirectorySeparatorChar` on Unix is intentionally matching `DirectorySeparatorChar`. Windows does support both '\\' and '/' but on Unix only '/' can be used as directory separator.

/cc @mairaw
