### ISSUE TITLE
ApiCompatValidateAssemblies docs don't mention how to specify the baseline assemblies

### ISSUE THREAD

**Issue by ericstj** [dotnet/docs#38962]
**Issue description**

I was reading the https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/assembly-validation document and see that it tells folks how to turn on the task, but not how to provide inputs.  It does mention:
> Validates that there are no breaking changes across versions.

I think it will get it's multi-targeting inputs from the project automatically, but it needs the author to tell it how to find the previous version to compare to.

I think the way to do this is to specify `ApiCompatContractAssembly` and do so in a way that's specific to each TargetFramework of the project.

It would be nice to see a sample for how someone might do this.

cc @ViktorHofer @gewarren 

---
[Associated WorkItem - 198657](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198657)

**Comment by Jacknann** [comment]
### 

> _**
![IMG_1470](https://github.com/dotnet/docs/assets/155493897/643e4d84-8372-434a-a9ff-
 #/9a5ea6a7f227)
**_
