### ISSUE TITLE
czcdad

### ISSUE THREAD

**Issue by YashCreativeBuffer** [dotnet/docs#38973]
### Type of issue

Outdated article

### Description

asdasd
sc
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8618)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/nullable-warnings.md

### Document Version Independent Id

df58b52a-2532-8241-72cd-f40e9096037d

### Article author

@BillWagner

### Metadata

* ID: 812f0144-80de-6b49-dded-97eeb7bc373d 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
closing as spam.
