### ISSUE TITLE
libgcc1 listed as universal dependency 

### ISSUE THREAD

**Issue by SRNissen** [dotnet/docs#38999]
### Type of issue

Other (describe below)

### Description

Under header **Dependencies**, `libgcc1` is not listed with a version, implying it is always required.

- If `libgcc1` is *not* always required, it should probably be corrected.
- If `libgcc1`  *is* always required -> Ubuntu no longer ships with `libgcc1`, replacing it with libgcc-s1, c.f.: https://review.opendev.org/c/openstack/openstack-ansible-galera_server/+/902383

Possibly related issues:

- https://github.com/dotnet/core/issues/5651
- https://github.com/dotnet/docs/issues/15537

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

@adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

---
[Associated WorkItem - 200663](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200663)

**Comment by leecow** [comment]
I'm all for making it correct. Cursory search shows that only Debian 10 still uses libgcc1. Everything else (Debian 11+, Ubuntu 20.04+) in on libgcc-s1
