### ISSUE TITLE
This is a breaking change for Linq to SQL

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/docs#38996]
### Type of issue

Code doesn't work

### Description

Got the new CA1862 "suggestion" on this statement:

```
// Note: _db is an ApplicationDbContext
var qry =
    from p in _db.Providers
    where p.ApplicationUser.NormalizedUserName == username.Normalize()
    select p.Id;

return await qry.FirstOrDefaultAsync();
```
I accepted the suggested edit, which gives me:
```
var qry =
    from p in _db.Providers
    where p.ApplicationUser.NormalizedUserName.Equals(username.Normalize(), StringComparison.InvariantCultureIgnoreCase)
    select p.Id;
```
This code gets a compiler warning complaining that `NormalizedUserName` may be null, so I modified the code so it will compile without warnings:
```
var qry =
    from p in _db.Providers
    where p.ApplicationUser.NormalizedUserName!.Equals(username.Normalize(), StringComparison.InvariantCultureIgnoreCase)
    select p.Id;
```
When I run this code, I get this exception:
> System.InvalidOperationException: The LINQ expression
> [deleted for brevity]
> .Where(p => p.Inner.NormalizedUserName.Equals(
>        value: __Normalize_0, 
>        comparisonType: InvariantCultureIgnoreCase))' could not be translated. Additional information: Translation of the 'string.Equals' overload with a 'StringComparison' parameter is not supported. See https://go.microsoft.com/fwlink/?linkid=2129535 for more information.

This code 

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1862

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1862.md

### Document Version Independent Id

d3475dfc-a868-51bb-78b5-827e94133c8f

### Article author

@gewarren

### Metadata

* ID: 619de39c-0be6-5d86-655b-6b6caf1b5b93 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 199059](https://dev.azure.com/msft-skilling/Content/_workitems/edit/199059)

**Comment by IndigoHealth** [comment]
Just FYI (totally off-topic for the purpose of this post), I investigated what `ApplicationUser.NormalizedUserName` is all about, and [this post](https://github.com/aspnet/Identity/issues/351) says it is the UPPER-CASE version of the username. That concept of "normalized" is different than the Unicode C normalization provided by the C# `string.Normalize()` function. The original code (the code that compared strings using the `==` syntax) worked because SQL Server does case-insensitive compares.

**Comment by gewarren** [comment]
@IndigoHealth I think this is a case where you'd just suppress the CA1862 rule.

The rules/code fixes don't and can't cater to every single case. However, they're designed to cater to a vast majority of cases, where there is real benefit and they're unlikely to cause a problem. If you feel strongly that the rule should exclude this scenario as part of its logic, you can file an issue at https://github.com/dotnet/roslyn-analyzers.

**Comment by IndigoHealth** [comment]
It would be kind of you to add a prominent note on the documentation page, after Rule Description, noting that this rule may want to be suppressed for LINQ to database scenarios because the generated database queries may not support the changed code.
