### ISSUE TITLE
Switch version of C#

### ISSUE THREAD

**Issue by pmattei** [dotnet/docs#38994]
### Type of issue

Typo

### Description

Could you please add a link to switch to another C# version.
Typically, I did not found the syntax for readonly struct of C# 7.3
Thanks

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md

### Document Version Independent Id

0960802e-80c3-cb56-cb8b-ab1f1b20fb4e

### Article author

@BillWagner

### Metadata

* ID: d9220116-e950-04cf-b6d5-70d15a084a22 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by BillWagner** [comment]
Hi @pmattei 

I'd like to drill deeper into what you want to find. 

We've resisted specifying the version of new C# features on each page of the language reference. That would add a lot of additional information for each page. In many cases, the additional info won't be helpful. We've noted when a feature is no more than 3 releases old.

You're comment seems to mention two different concepts: First, when the `readonly struct` feature was added. Second, how to  specific a language version for your application. Which are you looking for?

**Comment by pmattei** [comment]
Hi @BillWagner 

Thank you for your answer
My point is "what is the correct version in C# version X.Y?"
Taking the example code from the page we have:
``public double X { get; init; }``
I get the very clear error CS8370 which indicates that the "init" keyword is only available from 9.0 while I am in 7.3
I see that not putting this keyword works. 
But I wonder if my choice is the right way to do it.
If the keyword is useless (which I doubt) why would the documentation refer to it?
I don't know if something is missing.

Thanks

**Comment by BillWagner** [comment]
That does help clarify what we need to do.

This page should add links to the related language syntax used in the examples.

**Comment by BillWagner** [comment]
Fixed in #42020
