### ISSUE TITLE
Incorrectly assigned values of array at the time of declaration 

### ISSUE THREAD

**Issue by chintansuthar72** [dotnet/docs#38995]
### Type of issue

Typo

### Description

There are two typos on this page and both are of the same type. See screenshots below attached.

- Values of array assigned at the time of declaration should be in curly braces (`{}`). 
- Typo locations
   1. In the `Lambda expressions` section
    <img width="920" alt="image" src="https://github.com/dotnet/docs/assets/75067919/67d4d9e0-502e-460d-9d9b-350bd6f4c19d">

   2. In the `Query expressions` section
    <img width="919" alt="image" src="https://github.com/dotnet/docs/assets/75067919/e09fc8ea-ac51-4d7e-91d7-9622f70c4813">

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md

### Document Version Independent Id

9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb

### Article author

@BillWagner

### Metadata

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

---
[Associated WorkItem - 198658](https://dev.azure.com/msft-skilling/Content/_workitems/edit/198658)

**Comment by BartoszKlonowski** [comment]
Hello @chintansuthar72, thank you for reporting!
The issue you observe is not really a typo. The example you see uses the latest feature of C# known as [Collection expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions).
However, it turns out that the embedded editor for the code samples does not support that feature yet.
And this should be taken care of.

**Comment by BillWagner** [comment]
Thanks for reporting this @chintansuthar72 

As @BartoszKlonowski notes, this is using the new collection expressions syntax.

However, that isn't yet supported in the Try.NET experience on docs. It will be a while before the update is installed on the live site, so I'll update the samples
