### ISSUE TITLE
[Container Publishing] Add to docs about container changes for 8.0.200

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#39004]
### Type of issue

Missing information

### Description

There are a few changes coming down the pipe for containers in 8.0.200:

* The `PublishContainer` target is available for every project! This means no more need for the NuGet Package for most projects. The project must 
  * be publishable (IsPublishable = true) and
  * have the SDK container support enabled (EnableSdkContainerSupport=true). For Web and Worker projects this property is set by their MSBuild SDK. For other project types, the property can be set in the project file

* Improved ContainerBaseImage inference by the tools to optimize for size and security:
  * targeting `linux-musl-x64` or `linux-musl-arm64` Runtime Identifiers will automatically choose the `alpine` image variants to ensure your project runs
  * If the project uses `PublishAot=true` then the `nightly/runtime-deps` `jammy-chiseled-aot` variant of the base image for best size and security
  * If the project uses `InvariantGlobalization=false` then the `-extra` variants is used to ensure localization still works
  * We should point users towards https://github.com/dotnet/dotnet-docker/blob/main/documentation/sample-image-size-report.md to learn more about the image variants' sizes and characteristics.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#containerbaseimage

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/publish-as-container.md

### Document Version Independent Id

401bc84b-9410-3583-91f6-88968654b588

### Article author

@IEvangelist

### Metadata

* ID: 19c28091-b3ad-affb-6343-47d7fa066d55 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**

---
[Associated WorkItem - 232971](https://dev.azure.com/msft-skilling/Content/_workitems/edit/232971)

**Comment by IEvangelist** [comment]
Hey @baronfel - when are we expecting 8.0.200 to come through?

**Comment by baronfel** [comment]
It'll drop next month alongside the 17.9 release.

**Comment by IEvangelist** [comment]
This should be good to go now, right? @baronfel

**Comment by baronfel** [comment]
Go for it!
