### ISSUE TITLE
Sentence has two key words swapped

### ISSUE THREAD

**Issue by plblum** [dotnet/docs#39014]
### Type of issue

Typo

### Description

In the section for Delegates, the first sentence identifies IEnumerable for parameter then Object for Return, but reverses those two types in the second part.

For example, a delegate that has a parameter of type [IEnumerable](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerable) and a return type of [Object](https://learn.microsoft.com/en-us/dotnet/api/system.object) can represent a method that has a parameter of type [**Object**](https://learn.microsoft.com/en-us/dotnet/api/system.object) and a return value of type [**IEnumerable**](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerable).

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/common-type-system

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/common-type-system.md

### Document Version Independent Id

402b82b0-5037-9117-50ef-e2c10c9705a6

### Article author

@adegeo

### Metadata

* ID: fa10fddf-a6ff-0b70-dc4d-94d1f9ac0f57 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
This is correct as written. The delegate parameter can be more restrictive than the method parameter, and the method return type can be more restrictive than the delegate return type.
