### ISSUE TITLE
Links to sites controlled by third parties in DataTable documentation

### ISSUE THREAD

**Issue by Porges** [dotnet/docs#3905]
The DataTable documentation here: https://github.com/dotnet/docs/blob/master/xml/System.Data/DataTable.xml

Links to a site controlled by a third party: `http://www.csharp-examples.net/dataview-rowfilter/`

This seems a bit wrong? There's no guarantee the target has the correct content any more (or is not taken over, etc)

**Comment by mairaw** [comment]
Hi @Porges, yes, you're right. We typically cover this kind of content on our own docs instead of going to 3rd-party sites. Since the link still works, I'm putting this on the backlog.

**Comment by eriawan** [comment]
@mairaw 

Thanks for pointing me to this issue. 
Could I propose to create new article that contain FilterExpression samples and also update the existing link of the DataTable documentation?
