### ISSUE TITLE
Antgoolen 

### ISSUE THREAD

**Issue by Goughy1991** [dotnet/docs#39075]
### Type of issue

Missing information

### Description

[Enter feedback here]
System.Collections.IList

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/collections/selecting-a-collection-class

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/collections/selecting-a-collection-class.md

### Document Version Independent Id

da3b31b2-54bf-14c2-56d3-872d4c1c109c

### Article author

@IEvangelist

### Metadata

* ID: e84850a4-05a8-5bab-ea8c-80df1ed0133f 
* Product: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
Closing this as `IList` is not a class.
