### ISSUE TITLE
public class Object

### ISSUE THREAD

**Issue by Goughy1991** [dotnet/docs#39087]
**Issue description**

**Target framework**

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>
Laou👌l😂♂️😴💯👻

**Comment by Goughy1991** [comment]
https://github.com/dotnet/docs/issues/39087#issue-2075477561 w s system **for you to**

**Comment by BillWagner** [comment]
closing as spam.

**Comment by Goughy1991** [comment]
### `**l**`
