### ISSUE TITLE
Document that indexing into StringBuilder can be inefficient

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#3909]
Indexing by character into a StringBuilder can be very slow if it is large and "chunky" (built up by appends rather than a large initial capacity). This is because every character access walks the linked list of chunks to find the right buffer to index into. 

As you can see in https://github.com/dotnet/corefx/issues/25804 the performance can become terrible over say 50K characters. In such a case if you need to do repeated indexing better options might be making a string, or copying into a new, pre-sized StringBuilder (which will not be chunky).

I suggest adding a note to this topic for .NET Framework and .NET Core to mention this.

https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.chars?view=netframework-4.7.1

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @danmosemsft. In addition to the **StringBuilder.Chars[Int32]** property, the section on [iterating a StringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=netframework-4.7.1#Iterating) in the StringBuilder class documentation also needs revision.
I'll assign this to myself and work on the revision when I return from vacation.

**Comment by danmosemsft** [comment]
@rpetrusha did you mean to close this?

**Comment by rpetrusha** [comment]
No, I certainly didn't, @danmosemsft. I have no idea how I did that. Thanks for pointing it out.
