### ISSUE TITLE
Revert dotnet-install.sh script

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#39101]
### Type of issue

Missing information

### Description

I wanted a way to quickly and easily get .NET 8 SDK running on a fresh Ubuntu Server for some AOT testing. I saw that you provide an installation script so I tried it out. As normal user, and then as root with sudo. None give me a dotnet command in the console, and I'm not looking for a manual installation here. I don't know what this script did exactly. I want to revert it again. Sadly this information is missing here.

And actually I was looking for that script that properly sets up the package source so I will also get updates later and have the dotnet command available right away. I'll continue looking for that thing. Hope it's still somewhere around.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md

### Document Version Independent Id

5bc7caa5-f1c2-d7d5-fe02-80c65cca9672

### Article author

@tdykstra

### Metadata

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 199060](https://dev.azure.com/msft-skilling/Content/_workitems/edit/199060)

**Comment by tdykstra** [comment]
The **Purpose** section of the documentation article explains that this script is intended for CI scenarios:

>The intended use of the scripts is for Continuous Integration (CI) scenarios, where:
>
> * The SDK needs to be installed without user interaction and without admin rights.
>
>* The SDK installation doesn't need to persist across multiple CI runs.

For information about how to install .NET on Ubuntu, see https://learn.microsoft.com/dotnet/core/install/linux-ubuntu
