### ISSUE TITLE
Wrong Checksum for 

### ISSUE THREAD

**Issue by researchsecurity** [dotnet/docs#39111]
### Type of issue

Typo

### Description

https://download.visualstudio.microsoft.com/download/pr/3b11b408-68e1-4a8f-a0ad-55b21456c4f6/03819d38c79a9aa4fd806f8c7b64130d/dotnet-sdk-8.0.101-osx-x64.pkg holds the hash 1e0ba3f5e0695fd838e0a100d6293b8495185b1e2c788abe94b97d50efb24778  and is not listed on your documentation. The checksums are listed here https://dotnetcli.blob.core.windows.net/dotnet/checksums/8.0.1-sha.txt

e40b9fd4a5c814e1d44fb58a7a78284244f77797c0dd5a60a5dd478b4f3eddf8cf6b51b4b63aa3d4a24435bedaa5e6df944da19728732ae23ff645ed5caef2b5 dotnet-sdk-8.0.101-osx-x64.pkg
5c18dd1c0bb8199660dea5793eb2a568c63adbde492ca5080a8130e723a6260c6b9c6a055c299a3b8ba2497d6875959f86da8b9c9bf85e093bca2e08724d46a1 dotnet-sdk-8.0.101-osx-x64.tar.gz

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/macos?WT.mc_id=dotnet-35129-website#verify-downloaded-binaries

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/macos.md

### Document Version Independent Id

68d524f7-6cf1-2caa-56d5-f243952d1526

### Article author

@adegeo

### Metadata

* ID: 07a5fade-535f-2fad-c7b0-77bf9e28773e 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 200664](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200664)

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

**Comment by adegeo** [comment]
Hi @researchsecurity I looked into this and the doc is correct with the checksum. The example file used is `dotnet-sdk-8.0.100-linux-x64.tar.gz` which was released as part of the .NET 8.0.0 release. The example you posted is for the .NET 8.0.1 release. I don't think we need to update the checksum examples for every release of .NET, just the yearly major releases.

Thoughts on this?
