### ISSUE TITLE
ContainerArchiveOutputPath is missing

### ISSUE THREAD

**Issue by begerard** [dotnet/docs#39149]
### Type of issue

Missing information

### Description

The argument [ContainerArchiveOutputPath](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#publish-to-targz-archive) of "dotnet publish" from .Net8 is missing in the command documentation itself.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md

### Document Version Independent Id

9439897e-dcb3-bc2e-5cae-35c1ca2e0681

### Article author

@tdykstra

### Metadata

* ID: 211afdc7-c796-202d-239d-823f2a499dff 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 200461](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200461)

**Comment by tdykstra** [comment]
`ContainerArchiveOutputPath` is an MSBuild property, not a `dotnet publish` option or argument. The `dotnet publish` documentation does not document all of the MSBuild properties you can use with it.

@IEvangelist - `ContainerArchiveOutputPath` currently is documented only in the RC2 what's new -- it would be good to cover it somewhere in permanent documentation. Should it be documented in https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0 ?

**Comment by begerard** [comment]
If we are on modifying the [Containerize a .NET app with dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0) page I'd suggest to add a section just before [Clean up resources](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#clean-up-resources) about "using" it.

As a docker beginner it took me time to understand that: 
1. the publish command pushed the image directly inside the "Images" list in Docker Desktop (it is already described in the documentation as a "local registry", but nothing in Docker Desktop says that their Images page is this local registry)
2. I just have to "Run" the image to both create the container and run the published application (the [Configure container execution](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#configure-container-execution) is a bit unclear about what it does default, and that in fact the default will be enough to make a web app ready to serve its pages and APIs without any action on our part)
3. I can just click on the link displayed in the "Port(s)" column of the Containers page of docker desktop to open my web app (it handle the port default randomness)

This part may be considered out of scope and very specific to how Docker Desktop works today, but it would cover a gap between this tutorial and the Docker Desktop documentation.

In the end, for real world web app with only 1 executable project, the default configuration is good enough and it looks possible to have a beginner run its application in less time than the Docker Desktop installation takes. Maybe a simplified version of this tutorial (in a different page, or by using accordion blocs in this one to hide all the optional arguments) could help.
