### ISSUE TITLE
No description of "-a" option for "dotnet restore"

### ISSUE THREAD

**Issue by SRNissen** [dotnet/docs#39156]
### Type of issue

Missing information

### Description

On CLI, `dotnet --help restore` lists various options, including `-a`.

The `-a` option is not described in this documentation.

\---

Reason I checked in the first place:

As output by `dotnet --help`, "The target architecture" is reasonably explanatory but does not list what arguments `-a` will accept.

I hoped to learn from this page, or at least a link from the `-a` section to a different article that lists target architectures. Unfortunatly - well, there's no `-a` section.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-restore.md

### Document Version Independent Id

0b993779-65a2-6092-4047-2fc2ec16170b

### Article author

@tdykstra

### Metadata

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
@SRNissen Thanks for reporting that. It will be fixed soon, and until then you can find the same `-a|--arch` option description in `dotnet build`.

**Comment by SRNissen** [comment]
Always great to see it when you guys move fast on these, thank you very much.
