### ISSUE TITLE
What is the meaning of '&' in this string?

### ISSUE THREAD

**Issue by QueryCoordinator** [dotnet/docs#39150]
### Type of issue

Typo

### Description

[Enter feedback here]
Hello, please clarify the meaning of '&' in this string: "Cannot convert **&method** group to non-function pointer type." Is it used in the meaning of referencing to the address of the expression, or is it a typo?

Kind regards,
Anne H., CQ

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs8812?source=docs

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs8812.md

### Document Version Independent Id

34c7fd16-5237-c210-01c5-226751d62f15

### Article author

@BillWagner

### Metadata

* ID: b5d48d97-25f7-659f-ca4b-5e484bf39109 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by gfoidl** [comment]
It's the [Address-of operator &](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#address-of-operator-).

**Comment by QueryCoordinator** [comment]
Hi Günther,

just clarifying, should **&method** then be left in English in the translated pages? Or should there be a space after '**&**'?

Kind regards,
Anne, QC

**Comment by gfoidl** [comment]
Hm, good question if `method` should be translated here. I just checked the `de-at` version and there `Methodengruppe` seems fine too, I can't speak for other languages (expect English).

There shouldn't be a space after `&`, as the operator and the "target" belong together.

**Comment by BartoszKlonowski** [comment]
It would be good to add the explanation of `&` operator to that page (in See also, or just as an embedded link).
Let me handle that if it's OK for adding it.
CC: @gfoidl @BillWagner

**Comment by BillWagner** [comment]
Hi friends,

This a good conversation. I think there are two recommendations:

1. The message string should use a code fence, and capitalize "Method":

> Cannot convert `&Method` group to non-function pointer type.

2. We should add a brief explanation of `&` and link to the article on the [Address of](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/pointer-related-operators#address-of-operator-) operator.

I've added this to our backlog, and added the "help wanted" label

**Comment by QueryCoordinator** [comment]
Thank you all for clarifying this!
