### ISSUE TITLE
"Learn feedback control" template does not work

### ISSUE THREAD

**Issue by SRNissen** [dotnet/docs#39237]
### Type of issue

Code doesn't work

### Description

I came here from the feedback link on [dotnet test](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test) and none of the metadata fields are filled in.

You may respond "That happens automatically when you submit the issue" but in fact I *cannot* submit the issue without editing those fields because they are required fields.

### Page URL

NA

### Content source URL

NA

### Document Version Independent Id

NA

### Article author

NA

**Comment by BillWagner** [comment]
Thanks for reporting this @SRNissen 

I just submitted a fix for it.
