### ISSUE TITLE
Update .NET SDK and .NET CLI telemetry about collecting data for mobile and WebAssembly workloads

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/docs#39276]
In .NET8, with https://github.com/dotnet/runtime/pull/90208 we introduced telemetry for collecting data about mobile and WebAssembly workloads. 

This change should also be documented in https://github.com/dotnet/docs/blob/e234edcaae55e45e93fbb4931a7ae70f16789f6d/docs/core/tools/telemetry.md by updating adequate tables in `Data points` section. 

---
cc: @steveisok @vitek-karas @baronfel 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c136055b-bb04-17b6-19b2-42d4610c1a70
* Version Independent ID: 50433ae5-4687-fe5f-75ab-a47e1a706777
* Content: [.NET SDK and .NET CLI telemetry - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry)
* Content Source: [docs/core/tools/telemetry.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/telemetry.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 251070](https://dev.azure.com/msft-skilling/Content/_workitems/edit/251070)

**Comment by ivanpovazan** [comment]
I am not sure about setting the right labels, so please feel free to select the correct ones.

**Comment by timdeschryver** [comment]
Hey @tdykstra you addressed me to this issue. 

To be honest, I'm not exactly sure how to do this correctly. But, I tried my best with https://github.com/dotnet/docs/compare/main...timdeschryver:issue/39276?expand=1. 
I wanted to ask you if I can create a PR for these changes because I'm not entirely confident if these changes are what's expected for this issue.

I also suppose the additional property added in https://github.com/dotnet/runtime/pull/90950 needs to be documented.

**Comment by tdykstra** [comment]
@ivanpovazan @steveisok I'm not sure how to translate the code in https://github.com/dotnet/runtime/pull/90208 and https://github.com/dotnet/runtime/pull/90950 to the table in the doc. @timdeschryver made a proposed update that you can see [here](https://github.com/timdeschryver/dotnet-docs/blob/1030f7a587b377470680c1e17d4894b8c57ed4f4/docs/core/tools/telemetry.md?plain=1#L96-L109). Is this correct? If not, can you please update a couple of data points in the table to show us how to interpret the code? And likewise if any data points from https://github.com/dotnet/runtime/pull/90208 were missed in the proposed table changes.

**Comment by ivanpovazan** [comment]
Hello, I would suggest opening a PR so it would be easier to review the changes and comment/align with what has been introduced in: https://github.com/dotnet/runtime/pull/90208 and https://github.com/dotnet/runtime/pull/90950

**Comment by timdeschryver** [comment]
Sounds good!
I opened #40746 to track the changes, feedback is welcome.

**Comment by tdykstra** [comment]
@timdeschryver Thanks again for taking this on!
