### ISSUE TITLE
Community provided article on Threading (general)

### ISSUE THREAD

**Issue by andygonusa** [dotnet/docs#3928]
Hi all, attached please find an article submitted by a Spanish Latam community member, now an FTE in Microsoft. Originally it was published on a local section of the MSDN library and had very good PVs. It provides a good overall description of Threading. 

It has been reverse-machine-translated to provide a readable English version - if you think it has some merit and could find a place in the official documentation, please do let me know and we can work with the author to have it amended as necessary.

This also serves as a test, to see if it's efficient to use this process for such submissions/proposal.

thanks to let me know your thoughts
[Manejador-de-procesos-Los-Threads.zip](https://github.com/dotnet/docs/files/1555526/Manejador-de-procesos-Los-Threads.zip)

**Comment by mairaw** [comment]
Hi @andygonusa, perhaps we should schedule a meeting to talk about this process in general? @BillWagner and I just quickly glanced over the topic and it reads a lot like a blog post and not an article that would be part of docs.

**Comment by BillWagner** [comment]
Assigning P1 to this because the process for international PRs needs to be fixed.
