### ISSUE TITLE
[New article]: What is a Boolean-backed enum type

### ISSUE THREAD

**Issue by matteshe** [dotnet/docs#39294]
### Proposed topic or title

Boolean-backed enum type

### Location in table of Contents.

Enumeration types

### Reason for the article

In .net breaking changes you have an article about "Boolean-backed enum type support removed". As I would like to test the behavior in .net6 and .net8 I would to know, what a Boolean-backed enum type is. The is no documentation at all about this topic. An example for that would be really helpful.

### Article abstract

see reason

### Relevant searches

Boolean-backed enum type

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61b63f9e-8755-12e6-d993-3235be760eba
* Version Independent ID: cc2d4053-ba6c-de02-9c88-fca22796b660
* Content: [.NET 8 breaking change: Boolean-backed enum type support removed - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/bool-backed-enum)
* Content Source: [docs/core/compatibility/core-libraries/8.0/bool-backed-enum.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/8.0/bool-backed-enum.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Boolean-backed enum types aren't expressible in C#, VB, or F#, but if they were, it would look like @kwangholee3esi example.
