### ISSUE TITLE
C# Compiler Error CS1009 description should mention C#'s Unicode escape sequences 

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#39301]
---
**Issue moved from MicrosoftDocs/feedback#3980**
- Please respond to @RexJaeschke.

---

_From @RexJaeschke on Monday, January 22, 2024 9:38:01 PM_

**Describe the bug**

The C# Compiler Error CS1009 is raised by ill-formed C# Unicode escape sequences, but the error description does not mention that possibility, which may well prohibit the reader from understanding the error message.

The help text says

> An unexpected character follows a backslash (\) in a [string](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types#the-string-type). ...

It should also mention character literals as well as strings.

Consider the following C# expressions:

```csharp
'\u0061'   // OK; well formed
'\u061'     // CS1009; a lowercase \u-style Unicode escape sequence *must* have *exactly* 4 hex digits
'\x061'      // well formed as a hexadecimal escape sequence (not a Unicode one)
'\X061'     // CS1009; a hex escape sequence *must* start with \x *not* \X
'\U0061'   // CS1009; an uppercase \U-style Unicode escape sequence *must* have *exactly* 8 hex digits
'\U00000061'      // OK; well formed
```

---

Edit by @BillWagner  - Add Doc ID for search purposes

Version independent Document ID: 12bd8142-8234-f9ec-06b1-65f3099c9566

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3980**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Monday, January 22, 2024 9:38:04 PM_

Thank you for opening an issue! One of our team members will get back to you with additional information.
  
If this is a product issue, please close this issue and contact the product's support instead. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3980**
- Please respond to @RexJaeschke.

---

_From @RexJaeschke on Monday, January 22, 2024 10:16:36 PM_

One more thing to consider:

```csharp
string s1a = "\U0010FFFF";  // OK
string s1b = "\U00110000";  // (previous value + 1)  CS1009 unrecognized escape sequence
```

While the Unicode escape sequence in the second string *is* well formed, values above U+10FFFF are not supported.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3980**
- Please respond to @gewarren.

---

_From @gewarren on Monday, January 29, 2024 10:35:15 PM_

@BillWagner Not sure if this issue is with the docs or the error message itself.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3980**
- Please respond to @BillWagner.

---

_From @BillWagner on Monday, January 29, 2024 10:39:24 PM_

@gewarren 

Let's add it to the docs. The message can't cover those examples well. Are you going to move it to our repo?

**Comment by BartoszKlonowski** [comment]
@gewarren @BillWagner I will work on this!

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski 

I've assigned it to you.
