### ISSUE TITLE
SEO for related, but not necessarily exact terms

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#3934]
I had an interesting discussion with a member of the F# Software Foundation who was looking to get started with F# on .NET Core using a mac.  He typed the following into google:

* "fsharp dotnet core"
* "fsharp dotnet core new project"
* "fsharp macos"

What he was ultimately looking for was this article: https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line

The article contains the following relevant things:

* " This article covers how you can get started with using F# on .NET Core."
* " To begin, you must install the .NET Core SDK 1.0 or later. There is no need to uninstall a previous version of the .NET Core SDK, as it supports side-by-side installations."
* Mention of the `dotnet` commands, with examples, and "F#"
* "Starting with .NET Core 2.0, you don't have to run dotnet restore because it's run implicitly by all commands, such as dotnet build and dotnet run, that require a restore to occur. It's still a valid command in certain scenarios where doing an explicit restore makes sense, such as continuous integration builds in Visual Studio Team Services or in build systems that need to explicitly control the time at which the restore occurs."

And yet, this article was not in his Google search results.  I'm no expert in SEO, but I believe this article does a pretty good job about being discoverable.  What could be improved?  And what does this imply about other articles in the docs?

**Comment by mairaw** [comment]
For SEO, the most important things are file name, title, H1 and the first paragraph (1 or 2 sentences).

But I see the article in the search results for this one:
https://www.google.com/search?q=fsharp+dotnet+core+new+project - ranking 4

For fsharp macos, the page doesn't have any reference to macos, so it would be hard to be picked up by search engines. Maybe try adding the OS keywords in the introduction or title?

**Comment by cartermp** [comment]
@mairaw Would that also have something to do with you having viewed that article in the past? When I search in incognito mode, it's not on the front page.

**Comment by mairaw** [comment]
it's number #8 for me in incognito.
