### ISSUE TITLE
Outdated ebook download link

### ISSUE THREAD

**Issue by deathchurch** [dotnet/docs#39363]
### Type of issue

Outdated article

### Description

The link to download .NET Microservices: Architecture for Containerized .NET Applications goes to the v7 edition. The webpage says it has been updated to v8. Also the change log goes to a repository that is now archived and references an even older version of the book. Where can I download the latest version that is updated for .NET 8?

### Page URL

https://learn.microsoft.com/en-us/dotnet/architecture/microservices/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/index.md

### Document Version Independent Id

58c0d74e-2a5d-297e-4770-e8e44878b683

### Article author

@jamesmontemagno

### Metadata

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac 
* Service: **dotnet-architecture**
* Sub-service: **microservices**

**Comment by jamesmontemagno** [comment]
Correct, it is on .NET 7 today, we are working on a new and updated ebook based on the new eShop sample that replaces eShopOnContainers.
