### ISSUE TITLE
I do not understand.

### ISSUE THREAD

**Issue by johnghilg** [dotnet/docs#39361]
### Type of issue

Code doesn't work

### Description

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	BC2012	can't open 'C:\Users\Owner\source\repos\MyGame1\MyGame1\obj\Debug\MyGame1.exe' for writing: The requested operation cannot be performed on a file with a user-mapped section open.	MyGame1	C:\Users\Owner\source\repos\MyGame1\MyGame1\vbc	1	N/A	

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/bc2012?f1url=%3FappId%3Droslyn%26k%3Dk(BC2012)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/error-messages/bc2012.md

### Document Version Independent Id

6542139f-d572-285a-98b4-c8e118c5cc76

### Article author

@KathleenDollard

### Metadata

* ID: 6677f7e2-8e7b-8b15-a307-0363cf14f0c6 
* Service: **dotnet-visualbasic**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Hi @johnghilg 

We'd need more details on your code to understand this issue. 

I'm not sure if there's a documentation fix for this issue. A better way to get help on your code is to post a question on our [Q & A](https://learn.microsoft.com/answers/tags/315/vb) site.

**Comment by sharwell** [comment]
@BillWagner This might be the error that shows up if a user tries to build a VB project while a previous version of that code is still running
