### ISSUE TITLE
Base Interface is not defined and perhaps ill-defined.

### ISSUE THREAD

**Issue by crawfis** [dotnet/docs#39364]
### Type of issue

Missing information

### Description

[Enter feedback here]
The paragraph and the following that start with "An interface can inherit from one or more base interfaces" is not as clear as it could be. In particular, the concept of a "base" interface is not defined and one would typically remove this word, but then base is peppered throughout this section. I guess you call an interface with a default implementation a base interface. However this seems method specific and not interface specific.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/interface.md

### Document Version Independent Id

d931e899-d6f0-55ff-ab3a-dfff6e31f5a2

### Article author

@BillWagner

### Metadata

* ID: ef21cb62-9cbd-84c8-cfae-6dd1a421180b 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 289450](https://dev.azure.com/msft-skilling/Content/_workitems/edit/289450)

**Comment by BillWagner** [comment]
Thanks for pointing this out @crawfis We can improve this.

The [language specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces) also uses the term "inherits" for defining a base interface.

We should add language to define "base interface" something like this:

"An interface may declare one or more base interfaces. A class that implements that interface must implement all the members declared in the interface and its base interfaces. Note that any of the interface may include a default implementation of one or more of those members."

I've added this to our backlog, and added the "help wanted" label.

**Comment by crawfis** [comment]
Hmm. Sorry Bill, but that sounds even more confusing. Perhaps I am misunderstanding what is meant here. An example would help. Again I think you mean interface IB is derived from interface IA, so IA is a "base" interface for IB. To implement interface IB one must also implement interface IA. TI see the problem though; Declare seems wrong. Inherit seems wrong, etc.

**Comment by BillWagner** [comment]
I'm open to different language for the definition. That was my first pass. I also agree that an example would help.

I want to continue with the term "base interface", as that's what's used in the language specification. In general, I want to standardize on those terms, and define them well (including any needed examples). Then, as readers want more details, or more depth, they can turn to the specification. They'll already have the necessary vocabulary for the important terms.
