### ISSUE TITLE
https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb 404

### ISSUE THREAD

**Issue by Matthias-C** [dotnet/docs#39365]
### Type of issue

Typo

### Description

The provided Link 
 does not lead to anything usefull Error 404

https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

@adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
Hello, sorry it's not working for you. You'll need to provide me with more information. It looks like you might be copying that command directly? If so, it's part of the script listed there and you need to run the entire script.

If you did run the entire script and it still didn't work, please let me know the followingL

1. What version of Ubuntu are you using?
2. What does the first command in the script output?
3. What does `lsb_release -r -s` output?
4. What does `grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'` output?
