### ISSUE TITLE
init keyword needs some love on this page

### ISSUE THREAD

**Issue by crawfis** [dotnet/docs#39394]
### Type of issue

Missing information

### Description

[Enter feedback here]
The **_init_** keyword is mentioned here, but not defined. Nor are there any examples of its usage. At a minimum, the See Also section should include: [init (C# Reference)](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init)
Perhaps also a reference to: [Object Initializers with collection read-only property initialization](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/properties.md

### Document Version Independent Id

05423053-63de-3e56-0929-2ae477d577df

### Article author

@BillWagner

### Metadata

* ID: 8fb1d95e-a652-a965-f817-d49554a07388 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BartoszKlonowski** [comment]
Hello @crawfis!
In the [Properties overview](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#properties-overview) section of this page the `init` can be found described as:
> An [init](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init) property accessor is used to assign a new value only during object construction.

It's brief, but at the same time the `init` keyword is a link to the full page describing it in details.

Beside having `init` added to "See also" section (just like `get` `set` already is) I don't see any value in adding more description of this keyword in this page.
Do you think adding it to "See also" would be sufficient to close this issue?

**Comment by crawfis** [comment]
Yes. That is sufficient. I think I missed the link. Again, perhaps add the Object Initializers .. page to the Related Sections.

**Comment by BillWagner** [comment]
Good points. Let's add that link in the See also section as well.

Adding the "help wanted" tag, and adding it to our backlog.
