### ISSUE TITLE
dotnet-core-uninstall does not work for .NET 8

### ISSUE THREAD

**Issue by durandt** [dotnet/docs#39400]
### Type of issue

Outdated article

### Description

This article mentions that one may use the ".NET Uninstall Tool" to uninstall old runtimes and SDKs but the ".NET Uninstall Tool" hasn't been updated to support .NET 8:

```
$ ./dotnet-core-uninstall list

This tool cannot uninstall versions of the runtime or SDK that are installed using zip/scripts. The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  8.0.101  (arm64)  [Cannot uninstall version 8.0.0 and above]                                    
  8.0.100  (arm64)  [Cannot uninstall version 8.0.0 and above]                                    
  7.0.310  (arm64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]
  6.0.416  (arm64)                                                                                

.NET Core Runtimes:
  8.0.1   (arm64)  [Cannot uninstall version 8.0.0 and above]                                            
  8.0.0   (arm64)  [Cannot uninstall version 8.0.0 and above]                                            
  7.0.13  (arm64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  6.0.24  (arm64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
```
```
$ ./dotnet-core-uninstall remove --sdk 8.0.100
Uninstallation not allowed. This tool cannot uninstall .NET Core SDKs with version 8.0.0 or above.
```
```
$ ./dotnet-core-uninstall remove --runtime 8.0.100
The specified version is not found: "8.0.100".
```

Related:
https://github.com/dotnet/core/issues/1202

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md

### Document Version Independent Id

090b8fbd-39e6-b754-e1da-890b1123f2c4

### Article author

@adegeo

### Metadata

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 208204](https://dev.azure.com/msft-skilling/Content/_workitems/edit/208204)

**Comment by adegeo** [comment]
I'll ask around internally to see what the story is.

**Comment by quitelight** [comment]
any updates?

**Comment by adegeo** [comment]
@quitelight @durandt @the1schwartz Sorry for the delay here. I did ask around and was told it's owned by the SDK folks but it sometimes just really lags behind. I also noticed this https://github.com/dotnet/cli-lab/issues/279 which has a roadmap for releasing the next version. It's close, but there are some blockers currently.
