### ISSUE TITLE
Option --check-only isn't listed as an available option

### ISSUE THREAD

**Issue by gravity00** [dotnet/docs#39419]
### Type of issue

Missing information

### Description

Hello,

In the **Description** it is mentioned a `--check-only` options that exist but isn't listed in the **Options** section.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-update

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-update.md

### Document Version Independent Id

aa21de56-b0c8-0fc3-ec75-6f310ae0dec6

### Article author

@tdykstra

### Metadata

* ID: aae4b99c-452e-fd3d-4bb5-4d9961212fbd 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 209075](https://dev.azure.com/msft-skilling/Content/_workitems/edit/209075)

**Comment by tdykstra** [comment]
@gravity00 Thanks for reporting this oversight, I'm adding the option to the Options section now.
