### ISSUE TITLE
VB: private protected

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3943]
The next release of VB will add the `private protected` access modifier. This will be the Visual Basic 15.6 version.

The spec for the feature will parallel the spec for the C# language feature.

Note: There are syntax issues still to be resolved before this is ready to work on.

**Comment by mairaw** [comment]
Tagging @KathleenDollard to confirm if the syntax has been finalized.

**Comment by KathleenDollard** [comment]
Yes, it is now finalized. Sorry for the delay

**Comment by BillWagner** [comment]
@KathleenDollard Just to verify: We should go forward with the decision [posted in the VB LDM notes](https://github.com/dotnet/vblang/blob/127d7ad74b5ff1eab07c7b873625613ac6bd1f97/meetings/2018/vbldm-notes-2018.02.21.md#private-protected---discussion).

Is that correct?

**Comment by KathleenDollard** [comment]
Yes, and I apologize that I didn't get this message to you sooner. I wanted to make sure the VB MVPs didn't have a strong negative reaction yesterday. We are going forward with Private Protected.
________________________________
