### ISSUE TITLE
Orleans - Default Collection Age Limit is incorrect

### ISSUE THREAD

**Issue by michaelmcneilnet** [dotnet/docs#39451]
### Type of issue

Outdated article

### Description

The default collection age for Orleans is now 15 minutes. This page states it is 2 hours, which was the default in v3. There doesn't appear to be any version selector, so I assume this page is relevant to the latest version of Orleans.

@ReubenBond

### Page URL

https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/activation-garbage-collection

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/orleans/host/configuration-guide/activation-garbage-collection.md

### Document Version Independent Id

c78c9d33-f923-6ec5-d649-9a09630df68f

### Article author

@IEvangelist

### Metadata

* ID: 4734308a-e5ca-67e8-9090-f7118eb8289b 
* Service: **dotnet-orleans**

---
[Associated WorkItem - 209076](https://dev.azure.com/msft-skilling/Content/_workitems/edit/209076)

**Comment by ReubenBond** [comment]
Thank you for reporting, @michaelmcneilnet - you are correct.
