### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by u-m-i** [dotnet/docs#39490]
### Type of issue

Typo

### Description

In the next paragraph:

> Passing pointers between methods can cause undefined behavior.

The _behaviour_ word has a typo.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#pointer-types

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/unsafe-code.md

### Document Version Independent Id

650ea03e-9452-07a0-88df-052744ec198c

### Article author

@BillWagner

### Metadata

* ID: 0ddd5c42-7acd-84c8-e532-d746b916c17a 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by eduardojp26** [comment]
@dotnet-bot claim

**Comment by BartoszKlonowski** [comment]
Hello @u-m-i!
The `behavior` word is correct in American English, and is widely used across the documentation already. In fact, it's much much more wider used than the `behaviour` word.
In other words - it's not a typo and it's correct as written.

**Comment by u-m-i** [comment]
Hi @BartoszKlonowski,
A lot of thanks for explain it to me, apologies for the confusion.
