### ISSUE TITLE
C#  `in` by val tiebreaker

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3949]
In C# 7.2, these methods cause an ambiguity:

```csharp
static void M(S arg);
static void M(in S arg);
```

This will be fixed in the 7.3 timeframe.  The by value (1st in the example above) is better than the `in` reference version. This will not be a new article, but will require updates to [Reference semantics with value types](https://github.com/dotnet/docs/blob/master/docs/csharp/reference-semantics-with-value-types.md) and affect the corresponding VB topics.

This feature will be delivered as a bug fix to C# 7.2. That means a machine with an updated compiler will use the new behavior. However, a machine that has not been updated will have the old 7.2 behavior. 

The LDM notes and the feature spec will have details on this behavior.

Feature spec is: dotnet/csharplang#945

**Comment by jcouv** [comment]
I think this tie-breaker is only applicable to C#. VB doesn't know how to deal with `in`.
@OmarTawfik can confirm.

**Comment by OmarTawfik** [comment]
@jcouv Yes. Tie breaker is C# specific. VB sees `in` parameters as references, and can use them where safety isn't involved. For example, you can pass an `in` argument from VB by ref to a C# method, but you cannot override a base `in` method from a parent C# type.
This is the tie breaker PR: https://github.com/dotnet/roslyn/pull/23122
VB Examples here: https://github.com/OmarTawfik/roslyn/blob/master/src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/InAttributeModifierTests.vb

**Comment by BillWagner** [comment]
Updated title based on @jcouv and @OmarTawfik comments.

**Comment by BillWagner** [comment]
I'm going to expand the scope of this somewhat. Looking at the content, I believe a number of locations were missed when `in` was added as a modifier to method arguments. I'll update those to mention `in`, and update the language reference on `in` and `ref` to explain the tiebreaker rule (and note that the rule only applies as of 7.3. In 7.2 the method call is ambiguous.

**Comment by BillWagner** [comment]
PR #4534 does the background work to add discussion of the `in` modifier where previously the `out` and `ref` modifiers were discussed without mention of `in`.

The new tiebreaker rule will come in a separate PR.
