### ISSUE TITLE
Document how to do xplat profiling on .NET Core

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#395]
This from @brianrob

For .NET core, we have a cross-platform profiling story that takes advantage of platform specific tracing systems depending upon which operating system is being used.  For Windows, the profiling story is based on Event Tracing for Windows (ETW) and on Linux is based on perf_event and LTTng.  The goal is to be able to get at fundamental computing information (CPU, blocked time, memory, etc.) and CLR specific information (GC, JIT, threadpool, etc.) on all platforms.

For Windows:  Collection and analysis occurs via a tool called PerfView (you can search for it on Bing).
For Linux: Collection occurs via a script call PerfCollect, which is available at http://aka.ms/PerfCollect.  Just download it, and then look at the top comment header for instructions on how to use it.  The script generates a .trace.zip file which can then be pulled back to a Windows machine and analyzed using PerfView (we're most of the way there, but this step doesn't work just yet)  In the interim you can run ./perfcollect view <zipfile> and it will open in the native perf_event viewer.

**Comment by sebastienros** [comment]
This?
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md

**Comment by brianrob** [comment]
@sebastienros, the link you referenced is the up-to-date document on how to do profiling on Linux.

**Comment by mairaw** [comment]
@stephentoub @Petermarcu who can help with this subject?

**Comment by stephentoub** [comment]
> who can help with this subject?

@brianrob

**Comment by brianrob** [comment]
Yup, I'm the right person.  For Linux, the doc above is a good starting point.  For Windows, PerfView contains its own documentation, which describes how to use it.  Let me know what specifically you need and I can help.

**Comment by mairaw** [comment]
Thanks @brianrob. We were reviewing our backlog today. It's good that we have a starting point for now. When we start working on bringing those docs to the official site, I'll ping you again.

**Comment by IEvangelist** [comment]
I believe that this was resolved with the addition of the EventCounter content which covers cross platform perf profiling.
See #19635
