### ISSUE TITLE
Missing new blazor template added in .NET 8 (and maybe a few others?)

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#39503]
### Type of issue

Missing information

### Description

I noticed the article doesn't mention the new blazor template (I wanted to link to the article from https://github.com/dotnet/website-feedback/issues/32)

I think there are other templates that might be missing like aspire, etc.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md

### Document Version Independent Id

d80dfb96-bc86-a960-abec-255dd907d04d

### Article author

@tdykstra

### Metadata

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a 
* Service: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
> The built-in templates are in https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates, and the blazor template is there.
> 
> I tried `dotnet new aspire -h` and aspire doesn't appear to be a built-in template. cc @IEvangelist

What version of .NET do you have installed, and did you update to the latest VS 2022 preview version? I see it: 
![image](https://github.com/dotnet/docs/assets/7679720/d97e0bae-d1db-4f8f-9095-d587d499a8af)

**Comment by IEvangelist** [comment]
Hi @mairaw and @tdykstra,

> why do we have two different lists in two different pages?

I see value in having these lists in both places, but I'd encourage the use of an include to achieve this, as to avoid updating/maintaining multiple separate docs. The .NET Aspire workload is part of Visual Studio 2022 17.10.0 Preview 1.0, that's where I believe the templates are coming from. I wouldn't expect to see it listed in any of these articles yet, as it's not yet GA, nor part of any stable release, all still in preview.

**Comment by tdykstra** [comment]
I didn't realize we duplicated the template list in the `dotnet new <TEMPLATE>` doc.  I agree, an include file makes sense here. I'll implement one to address this issue.

**Comment by mairaw** [comment]
Makes sense! Yes, my machine might not be the best place to valid default templates 🙂

Perfect! I was thinking of the same strategy to avoid having to update the content twice. Thanks!
