### ISSUE TITLE
Broken formatting in DispatcherOperationStatus Enum

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#3957]
https://docs.microsoft.com/en-gb/dotnet/api/system.windows.threading.dispatcheroperationstatus?view=netframework-4.7.1

This page currently ends with the title: `XAML Text Usage`. Not quite sure what's meant to be there - MSDN appears to be the same.

https://msdn.microsoft.com/en-us/library/system.windows.threading.dispatcheroperationstatus(v=vs.110).aspx

**Comment by mairaw** [comment]
Thanks @ChrisMaddock. I think we should just remove this. Not sure what was the original intention either. @rpetrusha do you know? Previous versions also don't show this information. Might be an old issue with previous migrations.
