### ISSUE TITLE
C#: Allow `ref this` 

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3958]
There are two related features that will affect the same documents:

1. Allow `ref this` (where only `this ref` is allowed in 7.2) See dotnet/csharplang#1022
1. Relax ordering on `ref` and `partial` modifiers. See dotnet/csharplang#946

The first fixes a grammar issue with `ref`.  Extension methods whose first argument is a struct type currently have to write that argument as `ref this T`.  That looks clumsy and gives the wrong impression upon reading it.

This work would allow `this ref T` as the preferred syntax.

The second would relax the ordering constraint on `partial ref struct`. 

Neither would not introduce new articles, but would update the grammar for extension methods, argument modifiers, and ref value types.

**Comment by BillWagner** [comment]
Question for @jcouv Will either of these be targetting LangVersion=7.2 once they ship?

**Comment by jcouv** [comment]
Only the first one (order of `ref` and `this` modifiers in ref extensions) will target C# 7.2.
The second one (order of `ref` and `partial` in type declarations) would be tied to C# 7.3.

There is also the by-val vs. `in` [tiebreaker](https://github.com/dotnet/csharplang/issues/945) that will be targeting C# 7.2.

**Comment by BillWagner** [comment]
Thanks @jcouv The tiebreaker feature is issue #3949 for docs.

**Comment by BillWagner** [comment]
This is being done in a community PR dotnet/roslyn#23533

**Comment by BillWagner** [comment]
Changing the title as this did not make the 7.3 release

**Comment by BillWagner** [comment]
Closing pending acceptance of the feature.
