### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by MichaelNashCL** [dotnet/docs#39598]
### Type of issue

Typo

### Description

Doesn't reflect the list shown from the command "dotnet new list". i.e., apicontroller not listed here, react not part of cli list 

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md

### Document Version Independent Id

d80dfb96-bc86-a960-abec-255dd907d04d

### Article author

@tdykstra

### Metadata

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 214650](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214650)

**Comment by IEvangelist** [comment]
Hi @MichaelNashCL - some of those options that you're expecting are related to specific workloads being installed, I'm not sure they're expected.

**Comment by tdykstra** [comment]
Several templates were dropped in 8.0 and some were added or renamed. I'm going to add anything new to the table, pull out the ones that were dropped, and list the dropped ones in a separate table.
