### ISSUE TITLE
Dependencies don't install on latest Alpine

### ISSUE THREAD

**Issue by sjelisonI** [dotnet/docs#39629]
### Type of issue

Code doesn't work

### Description

For the latest Alpine 3.19, the listed instructions for installing dependencies no longer work:
apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib

Because apparently Alpine 3.19 now uses libssl3 instead of libssl1.1

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-alpine.md

### Document Version Independent Id

f066a748-0a7d-7506-3b18-c422fef13293

### Article author

@adegeo

### Metadata

* ID: b5e950a9-28c4-91f3-919b-d12f4e029fca 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 214923](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214923)

**Comment by adegeo** [comment]
Hi @sjelisonI I haven't updated the article for 3.19. I'll get to it soon. Thank you for the notification.

**Comment by adegeo** [comment]
@leecow Anything else I should do to the Alpine docs?

**Comment by leecow** [comment]
Nothing additional that I'm aware of.
