### ISSUE TITLE
Why is not there Japanese page?

### ISSUE THREAD

**Issue by OgawaTakasi** [dotnet/docs#39636]
### Type of issue

Missing information

### Description

Other sub pages and the parent page have Japanese translation version. But this page doesn't have it.

### Page URL

https://learn.microsoft.com/ja-jp/dotnet/azure/sdk/authentication/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/azure/sdk/authentication/index.md

### Document Version Independent Id

0a5ffb08-9da7-6113-89c3-1da0219c881e

### Article author

@alexwolfmsft

### Metadata

* ID: a1aa6e9f-0341-2089-70e6-c371fceeec00 
* Service: **dotnet-azure**

**Comment by scottaddie** [comment]
Thanks for reporting this issue. I've routed it internally to our content localization team.

**Comment by scottaddie** [comment]
Closing, as the page is now available in Japanese.
