### ISSUE TITLE
The sample codes in tutorial of "Primary constructors" mostly doesn't work due to compile error

### ISSUE THREAD

**Issue by eriawan** [dotnet/docs#39662]
### Type of issue

Code doesn't work

### Description

The sample codes in [C# tutorial of "Primary constructors"](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors) mostly doesn't work due to compile error.

For example, the sample code of this:

![image](https://github.com/dotnet/docs/assets/8773147/62502354-1c2e-4dbf-ad6a-bb08736fa7fb)

Both code samples using `readonly` keyword for properties that has only getter, and this is invalid, because we either use property for getter only without readonly, or we declare a field with readonly keyword. 

Some of the remaining code samples are also wrong, because they use readonly on properties that has getter only:

![image](https://github.com/dotnet/docs/assets/8773147/1223734a-3b79-431d-8ed6-b5f2c292d6e1)
 
and this:

![image](https://github.com/dotnet/docs/assets/8773147/e1dff68a-da36-456a-b8cf-41eea0aa84d1)

The errors are error compile, for example:

![image](https://github.com/dotnet/docs/assets/8773147/586b9171-2b1c-4094-8fbb-145fd161b5c2)

----

## Suggested fixes

Either remove readonly on the getter only properties, or we could use field, But I personally think that it should use properties without readonly keyword.

If it agreed, please assign to me and I will submit a PR to fix those problematic code samples in the tutorial of Primary contructors.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/primary-constructors.md

### Document Version Independent Id

a22d366b-380f-f701-6a01-2515433e1550

### Article author

@BillWagner

### Metadata

* ID: 3f1194e6-3116-6e70-9a36-f0a509c04f63 
* Service: **dotnet-csharp**
* Sub-service: **whats-new**

**Comment by BillWagner** [comment]
Hi @eriawan 

What version of .NET / C# are you using?  The source code used in this article is all here on GitHub: https://github.com/dotnet/docs/tree/main/docs/csharp/whats-new/tutorials/snippets/primary-constructors

One other item I see in your screenshot is that you've declared the `Distance` type as a `class`. The `readonly` modifier for a property is valid only in a `struct`, which is the code in the sample.

Those all build correctly with .NET 8, which includes C# 12. 

I'll close this as by-design.

**Comment by eriawan** [comment]
@BillWagner 

I see, thanks! Apologize that I'm not following that the code uses `struct` and therefore you can use readonly with getter  property.
