### ISSUE TITLE
API docs license

### ISSUE THREAD

**Issue by Thibaut** [dotnet/docs#397]
Hi

I'm looking to add .NET Core to [DevDocs](http://devdocs.io) (https://github.com/Thibaut/devdocs). However, it seems the [API docs](https://dotnet.github.io/api/index.html) are not generated from code at https://github.com/dotnet/corefx. Any idea where this content is coming from and what the license is?

Thanks

**Comment by mairaw** [comment]
You're right @Thibaut. They are not currently being generated from the source in corefx but they will be eventually. Currently, they're being generated from the IntelliSense files.
I don't know about the license. Maybe @richlander can comment on that.

**Comment by ALenfant** [comment]
Hello. These docs would be very interesting as a developer often on the go. Any news about the license?

**Comment by richlander** [comment]
Cool! We'd be interesting in having .NET docs showing up there.

Two major points:

- Some of the content is not open open source yet, as @mairaw says. This is purely point-in-time, a result of transitioning a closed engineering system from closed to open. This will be resolved this calendar year.
- We use CC-BY for docs and MIT for code. I'm guessing that those work for you since they are quite favorable/open.

How about we have a conversation on the best way to enable what you want to do -> rlander@ms.

**Comment by Thibaut** [comment]
Cool, thanks for following up.

I think I've got everything I need to get started. For the API docs it'd be great if you could make a static HTML version available to download. Otherwise I have to scrape the website directly, which takes longer.

I see that you've changed the license of the ASP.NET docs to CC BY which is also very cool. CC BY-NC was too restrictive for DevDocs.

I'll post here once the docs are up.

**Comment by mairaw** [comment]
@chenkennt do we have the HTML files for our API docs somewhere?

**Comment by chenkennt** [comment]
No, the only way is to get the html is to scrape the website.

**Comment by richlander** [comment]
@Thibaut We're definitely interested in helping you. Right now, we're working through getting our docs (API and conceptual) established. There are lots of improvement's we're asking the team to make on the doc tools. Once we get past all of that, we'd be happy to look at a better hand-off mechanism. For now, screen scraping is the best bet. Sorry about that, but it's really the best we can do for now.

Glad you like the licensing changes. I've been getting all our docs moved to CC-BY. We also had some other content than was CC-BY-NC that we got changed.

You can contact me offline if you want to discuss details: rlander@ms

**Comment by Thibaut** [comment]
Quick followup: I look into adding the .NET docs to DevDocs a little while ago but realized that without the API docs + with the guides being very much work-in-progress, the docset would probably not be that useful, and might cause support debt on my side (people wondering why the API docs are missing).

I'll wait for the API docs to be released under CC-BY before doing all the work.

**Comment by cmaneu** [comment]
There, From what I see here (https://github.com/dotnet/docs/blob/master/license.txt), the license has been updated, but this issue hasn't been updated.
@Thibaut is there sufficent for you to include .net documentation into DevDocs ?

**Comment by Thibaut** [comment]
@cmaneu see my comment above. The .NET API docs are currently [not part of this repo](https://github.com/dotnet/docs/tree/master/api). AFAICT they're unlicensed / subject to docs.microsoft.com's [terms of use](https://docs.microsoft.com/en-us/legal/termsofuse), which prohibit redistribution.

**Comment by richlander** [comment]
The API docs will be made open relatively soon, I expect in H1 2017. This is a strong goal of ours.

**Comment by mairaw** [comment]
We've open sourced our API docs earlier this month. 🎆

**Comment by Thibaut** [comment]
Thanks @mairaw and @richlander.

There's still a major blocker for me to add your docs to [DevDocs](http://devdocs.io/), in that I'd need a static version to scrape/convert into DevDocs format locally (https://docs.microsoft.com/en-us/dotnet/api/ doesn't work / isn't crawlable without JavaScript + the documentation is huge, so scraping the website isn't really an option), but this is unrelated to this GH issue, so I'll close it.

**Comment by sbrl** [comment]
@Thibaut is there another GH issue I can follow about that?
