### ISSUE TITLE
can anybody help me to corrct tthis code and run it.

### ISSUE THREAD

**Issue by rajdutt100** [dotnet/docs#39734]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
using System;
usingSystem.Collections.Generic;
usingSystem.Linq;
usingSystem.Web;
usingSystem.Web.UI;
usingSystem.Web.UI.WebControls;
public partial class Default3 : System.Web.UI.Page
{
protected void Page_Load(object sender, EventArgs e)
{
}
protected void Button1_Click(object sender, EventArgs e)
{
if (txtFirstNumber.Text != null &&txtSecondNumber.Text != null)
{
if ((Convert.ToDouble(txtFirstNumber.Text) / 13.7>= Convert.ToDouble(txtSecondNumber.Text)/20.55))
{
txtResult.Text = Convert.ToString((Convert.ToDouble(txtFirstNumber.Text) * Convert.ToDouble(TextBox1.Text)) / 13.7);
lblMessage.Text = "FINAL CBR VALUE IS" + txtResult.Text + "(calculated at 2.5 mm penetration)";
}
else
{
txtResult.Text = Convert.ToString(Convert.ToDouble(txtSecondNumber.Text) * Convert.ToDouble(TextBox1.Text) / 20.55);
// Response.Write("fail");
lblMessage.Text = "CBR VALUE IS " + txtResult.Text + " (calculated at 5.0 mm penetration)";
}
txtSecondNumber0.Text = Convert.ToString(Convert.ToDouble(txtFirstNumber.Text) * Convert.ToDouble(TextBox1.Text));
txtSecondNumber1.Text = Convert.ToString(Convert.ToDouble(txtSecondNumber.Text) * Convert.ToDouble(TextBox1.Text));
txtThirdNumber.Text = Convert.ToString(Convert.ToDouble(txtFirstNumber.Text) * Convert.ToDouble(TextBox1.Text) / 13.7);
txtFourthNumber.Text = Convert.ToString(Convert.ToDouble(txtSecondNumber.Text) * Convert.ToDouble(TextBox1.Text) / 20.55);
}
else
{
Response.Write("insert values");
}
}
protected void txtFirstNumber_TextChanged(object sender, EventArgs e)
{
}
protected void txtSecondNumber1_TextChanged(object sender, EventArgs e)
{
}
protected void Button2_Click(object sender, EventArgs e)
{
txtResult.Text = " " ;
txtSecondNumber0.Text = " ";
txtSecondNumber.Text = " ";
txtSecondNumber1.Text = " ";
txtThirdNumber.Text = " ";
txtFourthNumber.Text = " ";
txtFirstNumber.Text = " ";
}
protected void Button3_Click(object sender, EventArgs e)
{
//start
{
if (TextBox2.Text != null && TextBox3.Text != null && TextBox4.Text != null )
{
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox5.Text = Convert.ToString(108.57);
// clay 6mm unsoaked
}
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox5.Text = Convert.ToString(111.39);
//clay 12 mm unsoaked
} if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox5.Text = Convert.ToString(150);
//clay 6 mm soaked
}
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox5.Text = Convert.ToString(164.22);
//clay 12 soaked
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox5.Text = Convert.ToString(272.45);
//sand 6 unsoak
}
if ((Convert.ToDouble(TextBox2.Text) ==2) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox5.Text = Convert.ToString(375.02);
//sand 12 unso
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text)
== 2))
{
TextBox5.Text = Convert.ToString(273.47);
//SAND 6 SOAKED
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox5.Text = Convert.ToString(388.79);
//SAND 12 SOAK
}
else
{
}
}
else
{
Response.Write("insert values");
}
}
//end
}
protected void Button4_Click(object sender, EventArgs e)
{
TextBox7.Text = Convert.ToString(Convert.ToDouble(TextBox6.Text) * Convert.ToDouble(txtResult.Text) / 100);
}
protected void Button5_Click(object sender, EventArgs e)
{
//fstart
{
if (TextBox2.Text != null && TextBox3.Text != null && TextBox4.Text != null)
{
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0117) - 1.1668);
TextBox9.Text = Convert.ToString("Y = 0.0117x-1.1668");
// clay 6mm unsoaked
}
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * Convert.ToDouble(TextBox6.Text) * 0.2261) - (Convert.ToDouble(TextBox6.Text) * Convert.ToDouble(TextBox6.Text) * Convert.ToDouble(TextBox6.Text) * 0.0007) - (Convert.ToDouble(TextBox6.Text) * 23.798) + 832.81);
TextBox9.Text = Convert.ToString("Y = 0.0468x-4.6978SS");
//clay 12 mm unsoaked
} if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.002) - 0.2);
TextBox9.Text = Convert.ToString("Y = 0.002x-0.2 ");
//clay 6 mm soaked
}
if ((Convert.ToDouble(TextBox2.Text) == 1) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0117) - 1.1668);
TextBox9.Text = Convert.ToString("Y = 0.0078x-0.795");
//clay 12 soaked
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0006) - 0.0584);
TextBox9.Text = Convert.ToString("Y = 0.0006x-0.0584");
//sand 6 unsoak
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 1))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0117) - 1.1668);
TextBox9.Text = Convert.ToString("Y = 0.0013x-0.114");
//sand 12 unso
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 6) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0117) - 1.1668);
TextBox9.Text = Convert.ToString("Y = 0.0005x-1.0571");
//SAND 6 SOAKED
}
if ((Convert.ToDouble(TextBox2.Text) == 2) && (Convert.ToDouble(TextBox3.Text) == 12) && (Convert.ToDouble(TextBox4.Text) == 2))
{
TextBox8.Text = Convert.ToString((Convert.ToDouble(TextBox6.Text) * 0.0117) - 1.1668);
TextBox9.Text = Convert.ToString("Y = 0.0117x-0.0896");
//SAND 12 SOAK
}
else
{
}
}
else
{
Response.Write("insert values");
}
}
//end
}
protected void Button6_Click(object sender, EventArgs e)
{
}
}

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30689

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30689.md

### Document Version Independent Id

31ac834f-0e06-7e86-4016-ec953de4a880

### Article author

@KathleenDollard

### Metadata

* ID: 9a9758de-43d9-9080-e39f-0532d0c1d6ed 
* Service: **dotnet-visualbasic**
* Sub-service: **errors-warnings**

**Comment by AntonyNET** [comment]
Hi, what exactly dont work?

**Comment by rajdutt100** [comment]
Actually this program showing errors.

**Comment by rextor92** [comment]
This appears to be a .NET Framework Web Forms project. It is hard to answer the question as you've included partial class and the variables and UI elements are likely defined elsewhere in your code.

This repository is for issues with the dotnet documentation. A better way to get help on your code is to post a question on Microsoft's [Q & A](https://learn.microsoft.com/en-us/answers/tags/97/dotnet) site. 

+1 vote to close the issue
