### ISSUE TITLE
search for articles by contributor

### ISSUE THREAD

**Issue by collinstevens** [dotnet/docs#39763]
### Describe the issue or suggestion

Is there a way to search for articles on Microsoft Learn or dotnet docs specifically by the contributors of an article?

I'm referring to specifically contributors as its called out on an article here:

![image](https://github.com/dotnet/docs/assets/19230602/9e45fc46-95c3-4930-93fa-12a6046da6ab)

I tried some combinations to in the search bar and query params, but no such luck to search by contributor/contributors:

![image](https://github.com/dotnet/docs/assets/19230602/903f206a-e4fd-4511-8807-6452b502b48e)

I can do this just by looking through git as I have been, but it would be nice if there was an ability to do it natively in the platform. I tend to find articles I wouldn't have found at all before, but by following specific POI in my areas of interest, stuff pop up.

**Comment by gewarren** [comment]
I don't think this is possible unfortunately.

**Comment by collinstevens** [comment]
> I don't think this is possible unfortunately.

![image](https://github.com/dotnet/docs/assets/19230602/6a515a6a-147a-462b-9a13-557e6210a521)
![image](https://github.com/dotnet/docs/assets/19230602/58094cc9-cf4c-4b27-9d9b-b6c54d0d2a98)
:stare:

unfortunate
