### ISSUE TITLE
No Product or products data

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/docs#39779]
### Type of issue

Missing information

### Description

In the lesson Query Expression Basics [https://learn.microsoft.com/en-us/dotnet/csharp/linq/get-started/query-expression-basics](url) there is no data for Product or products.  Please provide the data and the expected output when query is run.  One file RefParameterModifier did create two products but I'm not sure if they are related to this lesson. 
 Thanks.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/get-started/query-expression-basics

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/get-started/query-expression-basics.md

### Document Version Independent Id

4fa6e86d-a790-6933-e0ee-a090e3133f0f

### Article author

@BillWagner

### Metadata

* ID: d9fdf663-0533-1971-d9e0-245f1cdc69d7 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BillWagner** [comment]
Fix in the same PR as #39780
