### ISSUE TITLE
.NET Publish articles not updated for changes from NETSDK1083

### ISSUE THREAD

**Issue by martincostello** [dotnet/docs#39788]
### Type of issue

Outdated article

### Description

A number of articles related to .NET publishing still use examples that use runtime identifiers that are not valid by default in the .NET 8+ SDK due to the changes made associated with [_.NET SDK uses a smaller RID graph_](https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph).

For example, [this property documentation](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifiers) uses `win10-x64` which is no longer accepted in .NET 8 by default as it should now be `win-x64`.

With .NET 6 and 7 going out of support this year, the documentation should be updated wherever relevant to give example values that work by default and don't need manual editing by the user.

Other examples include:

- [_Publish .NET apps with the .NET CLI_](https://learn.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#framework-dependent-executable)
- [_dotnet publish_](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#examples)

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md

### Document Version Independent Id

6741b1de-38a4-fbb1-d79d-acc47d549a2d

### Article author

@gewarren

### Metadata

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 226925](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226925)

**Comment by gewarren** [comment]
Thanks for the heads up @martincostello!
