### ISSUE TITLE
NU1100 

### ISSUE THREAD

**Issue by RAJESHASAITHAMBI** [dotnet/docs#39785]
### Type of issue

Missing information

### Description

[Enter feedback here]
![StatorTest - Microsoft Visual Studio 04-03-2024 12_44_03](https://github.com/dotnet/docs/assets/113448080/bca7ac90-987a-47ca-b5a3-3585943edd14)

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-list-source

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-list-source.md

### Document Version Independent Id

8b24f48d-1fe6-d930-5f08-c1da13322f7d

### Article author

@tdykstra

### Metadata

* ID: 0b6dfb81-af2e-2f4f-2316-3323539b6d35 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 226620](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226620)

**Comment by tdykstra** [comment]
Please add comments explaining what the issue is.
