### ISSUE TITLE
System.Span<T> struct code example of Arrays part does not match

### ISSUE THREAD

**Issue by prime167** [dotnet/docs#39784]
### Type of issue

Other (describe below)

### Description

In [Arrays part](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-span%7Bt%7D#arrays), description say double value of middle five elements of a 10-element integer array,but below code is whole array's sum

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-span%7Bt%7D#arrays

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/runtime-libraries/system-span{t}.md

### Document Version Independent Id

003de901-5f1a-7c88-faa1-c18c3553c091

### Article author

@gewarren

### Metadata

* ID: 7e0a1b3e-6c99-b144-cca0-e71dff3f1be5 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@prime167 Great catch! I really appreciate you opening the issue and adding the code to fix it.
