### ISSUE TITLE
The first "See also" link in the .NET Standard page does not exist anymore

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/docs#39796]
### Type of issue

Outdated article

### Description

The first link in the "See also" section at the bottom is:

[.NET Standard versions (source)](https://github.com/dotnet/standard/blob/v2.1.0/docs/versions.md)

It needs to either be removed or updated to point to an existing document.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md

### Document Version Independent Id

6819a4a7-7527-d8c7-e132-767f7344e00e

### Article author

@gewarren

### Metadata

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7 
* Service: **dotnet**
* Sub-service: **standard-library**

---
[Associated WorkItem - 250217](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250217)

**Comment by gewarren** [comment]
The link seems to work now, so I'll close this issue.
