### ISSUE TITLE
Need RID graph example

### ISSUE THREAD

**Issue by joelong01** [dotnet/docs#39790]
### Type of issue

Typo

### Description

[Enter feedback here]
why are earth wouldn't you give an example of the proper way to format the xml?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/8.0/rid-graph.md

### Document Version Independent Id

aead747e-5e37-d3e9-a992-0172da92c3ff

### Article author

@gewarren

### Metadata

* ID: a9e1a2a9-d8a7-78c9-c6c5-b3b4e88cd6b7 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@joelong01 Do you mean the XML to revert to the previous behavior?

**Comment by gewarren** [comment]
More feedback:

You don't actually explain what to do here, for people that don't already know what to do. You've said to use a portable RID-Graph, but I have no idea what that means. I don't know how to do it. And I don't know exactly what to type. Do I have to do something in the Project file? What do I type?
