### ISSUE TITLE
Issue running a container based on the Dockerfile in linux

### ISSUE THREAD

**Issue by fsharpcorner** [dotnet/docs#39811]
### Type of issue

Typo

### Description

In the tutorial https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows&pivots=dotnet-8-0 , if you use a linux based container image, the exe name is case sensitive. The dockerfile last step does not work for me.
The name of the dll should ne "dotnet*",  not "dotNet*".

current: ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]
Should be: ENTRYPOINT ["dotnet", "Dotnet.Docker.dll"]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows&pivots=dotnet-8-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md

### Document Version Independent Id

58d57b81-4ca6-6536-8788-f212402b41a7

### Article author

@IEvangelist

### Metadata

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa 
* Service: **dotnet-fundamentals**
* Sub-service: **dotnet-docker**

**Comment by fsharpcorner** [comment]
actually, I didn't name the project like you in the first place :)

**Comment by IEvangelist** [comment]
Hi @fsharpcorner - yes, I was going to call attention to that 😁:

![image](https://github.com/dotnet/docs/assets/7679720/8a2deb7a-4ec8-4dbb-803f-25a3d35fd785)

I'll close this, thank you.
