### ISSUE TITLE
Duplicated code source in constructors chapter

### ISSUE THREAD

**Issue by aaa913121** [dotnet/docs#39826]
### Type of issue

Typo

### Description

Hi, new to here.
I was reading this chapter and saw duplicated code source for two cases.
Their id are both `StaticExpression` in the markdown file, while there is a id `StaticCtor` in Program.cs that was not used in this page, might be the right one, I guess?

### Page URL

https://learn.microsoft.com/zh-tw/dotnet/csharp/programming-guide/classes-and-structs/constructors

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/constructors.md

### Document Version Independent Id

7f3cd611-9d80-4523-6ba5-17e1e9ab5c67

### Article author

@BillWagner

### Metadata

* ID: 754eaea9-3482-4a69-5b65-ebe4a5065597 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Thanks for noting this @aaa913121 

I just submitted a PR to address this.
