### ISSUE TITLE
Had an issue with when keyword while it with catch block

### ISSUE THREAD

**Issue by Irfan4hmd** [dotnet/docs#39860]
### Type of issue

Typo

### Description

[Enter feedback here]
Two catch blocks with same signatures (only if we use when keyword) are allowed in csharp which in my opinion should not be allowed .
for example : 
try{}
catch(ArgumentException) when (i<0){}
catch(ArgumentException) when (i<0){}
.....
this is allowed and executing the first catch block. While in some situations I might unknowingly write the same signature.
I hope you consider this and provide a detailed explanation on  why it is allowed.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/exception-handling-statements

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/exception-handling-statements.md

### Document Version Independent Id

70157b9c-983b-3916-ce95-99f265dfed6d

### Article author

@BillWagner

### Metadata

* ID: 9f85cb65-ded0-a342-4a86-04826af92da3 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Adding @jcouv and @333fred in case they have more details here.

This is the defined behavior.

The pertinent language in the specification is covered in [the `try` statement](https://learn.microsoft.com/dotnet/csharp/language-reference/language-specification/statements#1311-the-try-statement):

The first paragraph following the first *Note:* (emphasis mine):

> In order to locate a handler for an exception, `catch` clauses are examined in lexical order. If a `catch` clause specifies a **type but no exception filter**, it is a compile-time error for a later `catch` clause of the same `try` statement to specify a type that is the same as, or is derived from, that type.

I'll close this issue, as the documents match the spec and the behavior.

If you want to advocate for a change, you can open an issue in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository. I can see the possible benefits, but they may not be worth the cost of extra analysis at compile time.
