### ISSUE TITLE
Is .NET 8 support on Windows Server 2008 R2?

### ISSUE THREAD

**Issue by hzicong** [dotnet/docs#39874]
### Describe the issue or suggestion

Is .NET 8 support on Windows Server 2008 R2?

**Comment by gfoidl** [comment]
See [.NET 8 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md).

So, no it's not (officially) supported. You can try if the app runs or not, but if not then you know why.
