### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by Nelson200402** [dotnet/docs#39887]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]

### Page URL

https://learn.microsoft.com/es-es/dotnet/core/sdk

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/sdk.md

### Document Version Independent Id

c92f0188-38cb-c658-5f1b-e2a3ce2d34e9

### Article author

@gewarren

### Metadata

* ID: 47d5789d-4edb-3d22-9a8a-fdad704b8384 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
Empty issue - closing.
