### ISSUE TITLE
Parameter --allow-downgrade in dotnet tool install or dotnet tool update does not appear in the documentation.

### ISSUE THREAD

**Issue by ADD-Izan-Garcia** [dotnet/docs#39889]
### Type of issue

Missing information

### Description

I just discovered that you can use the parameter `--allow-downgrade` to prevent the warning:
`The requested version x.x.x.x is lower tan existing version x.x.x.x`
And successfully upgrade the version making a downgrade. 

This is not documented in https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install or neither https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-update

**Image adjunted:**

![image](https://github.com/dotnet/docs/assets/159129635/9e4792f9-e5fa-49ed-9d66-1a43333dcad4)

I want to know why this is not reflected in the docs. Could it be because they will stop supporting it in the future?

---

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-tool-install.md

### Document Version Independent Id

80822879-4c2e-1c28-ae04-1adb5e7e8a99

### Article author

@tdykstra

### Metadata

* ID: 7df78c19-0c6f-fe28-213c-b51dd73398ef 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 229460](https://dev.azure.com/msft-skilling/Content/_workitems/edit/229460)

**Comment by tdykstra** [comment]
@ADD-Izan-Garcia Thanks for reporting that, I'm adding the option to the documentation.
