### ISSUE TITLE
Run vs RunAsync for Generic Host

### ISSUE THREAD

**Issue by drmcclelland** [dotnet/docs#39893]
### Type of issue

Missing information

### Description

I see the following repeated step:

> Calls Run or RunAsync method on the host object.

I don't see a recommendation for whether we should use `Run` or `RunAsync` method on the host object...     documentation and code examples reference both, it would be helpful if there was a list of scenarios when one or the other is more appropriate.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host?tabs=appbuilder

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/generic-host.md

### Document Version Independent Id

22a12ff8-d2ff-a841-b9bb-e2fd1032bc04

### Article author

@IEvangelist

### Metadata

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9 
* Service: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
Yeah, we don't really have anything official. I tend to use the `RunAsync` API when there is already top-level `async` code, but I don't always follow that logic. The `Run` API actually calls the `RunAsync` API under the covers `host.RunAsync().GetAwaiter().GetResult()`.

For me, I personally cringe every time I see that, but it's really ok. What are you thinking?

**Comment by drmcclelland** [comment]
@IEvangelist I do see what you're saying, that `Run` is just calling `RunAsync().GetAwaiter().GetResult()`.  I think what I was hoping for is just some more consistency in the documentation to match up to the Worker template for noobs like me  :smile

I'll close this for now, since I have a better understanding thanks to your explanation.

**Comment by Arnab-Developer** [comment]
@IEvangelist if I use `app.Run()` that means the thread will be blocked. Now if I have minimal api method which is async, will that also be a thread blocking call?

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddTransient<IService, Service>();
var app = builder.Build();

app.MapGet("/{name}", async (string name, IService service, CancellationToken token) => 
    await service.GetMsgAsync(name, token)); // will it be a thread blocking call?

app.Run();
```

and what about the background service?

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHostedService<Service>();
var app = builder.Build();
app.Run();

public class Service : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken token)
    {
        _logger.LogInformation("Job executed");
        await DoWorkAsync(token); // will it be a thread blocking call?
    }
}
```

Should I use `await app.RunAsync()` in these cases?

**Comment by IEvangelist** [comment]
@Arnab-Developer 

This is a `Program`-level blocking call, regardless. When you use a background service, or register endpoints - it's all the same. They're handled independently from the top-level call, and whether or not it's async has no impact on the background services or endpoints.
