### ISSUE TITLE
No 'tools' subfolder under sdk root folder

### ISSUE THREAD

**Issue by dtsiktsiris** [dotnet/docs#39901]
### Type of issue

Outdated article

### Description

No 'tools' subfolder under sdk root folder
SDK version: 8.0.201

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md

### Document Version Independent Id

2be3647d-495b-c9f0-cf06-9a7bf687d3bb

### Article author

@adegeo

### Metadata

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
The tools directory is probably created if you install a dotnet tool. Did you get an error when exporting the path or something?

**Comment by dtsiktsiris** [comment]
Thought, that 'tools' folder should exist before installing a tool
