### ISSUE TITLE
Missing "a" in sentance makes it harder to read

### ISSUE THREAD

**Issue by PonchoPowers** [dotnet/docs#39917]
### Type of issue

Typo

### Description

"This looks like it's declaring a public field, which would appear to be bad object-oriented practice." should read "This looks like it's declaring a public field, which would appear to be a bad object-oriented practice." (Hence the missing "a".)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/event-pattern

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/event-pattern.md

### Document Version Independent Id

d2078536-1ee3-5b60-3872-f2635d245cc2

### Article author

@BillWagner

### Metadata

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Thanks for pointing this out @BonnieSoftware 

And thanks for volunteering to fix it @pojith I've assigned it to you.

**Comment by pojith** [comment]
can check pull request

**Comment by rextor92** [comment]
Fixed in #39985, can close

**Comment by Kissaki** [comment]
@BillWagner can you please close this ticket as done?
