### ISSUE TITLE
Add notes on tuple types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#39912]
### Type of issue

Missing information

### Description

A tuple whose members are all unmanaged types is an unmanaged type. That can be teased out of the knowledge that a tuple is a `struct` type, but it should be stated.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/unmanaged-types.md

### Document Version Independent Id

4a3622fb-7d09-78ec-ba38-b88001475018

### Article author

@BillWagner

### Metadata

* ID: 93e5d75f-07a3-e7ee-2842-ac754bdd2e41 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!
