### ISSUE TITLE
The event handler should be declared as nullable

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#39991]
### Type of issue

Outdated article

### Description

This sample was written pre-nullable reference types. It should be updated to handle NRT without warnings.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md

### Document Version Independent Id

1fd093e9-f47c-ffdd-91e9-5039c3ccde61

### Article author

@BillWagner

### Metadata

* ID: 38e8321f-5516-e451-5429-750d49f0ebed 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by rextor92** [comment]
I can update the sample if this is up for grabs
