### ISSUE TITLE
记录类型简介不可变性段的哈希表后面多了个国字

### ISSUE THREAD

**Issue by hb5cn** [dotnet/docs#39995]
### Type of issue

Typo

### Description

记录类型简介不可变性段的哈希表后面多了个国字

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/fundamentals/types/records

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/records.md

### Document Version Independent Id

8991024e-b64a-bc2a-9612-5649d89bda2b

### Article author

@BillWagner

### Metadata

* ID: 64271119-b153-2e7c-8f43-1fd1d4c1dbcb 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Thanks for pointing this out @hb5cn 

I opened an internal issue for our localization team to address this.

Closing, as it's tracked internally.
