### ISSUE TITLE
初めてのプログラム

### ISSUE THREAD

**Issue by MATSUDA-YUJI** [dotnet/docs#40015]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
 MessageBox.Show("姓名", "名前", MessageBoxButtons.OK, MessageBoxIcon.Information);
文字が有効ではない。何の文字が有効ではないのか？

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30037?f1url=%3FappId%3Droslyn%26k%3Dk(BC30037)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30037.md

### Document Version Independent Id

4a2e2b62-760f-6f44-3171-34b2df54ec8f

### Article author

@KathleenDollard

### Metadata

* ID: 3695131a-6e6b-0fac-c410-5e7fb8c422b9 
* Service: **dotnet-visualbasic**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
closing as a comment, not a doc bug
