### ISSUE TITLE
Compiler dose not fully support the code presented

### ISSUE THREAD

**Issue by cirmaciuadrian** [dotnet/docs#40018]
### Type of issue

Code doesn't work

### Description

Compiler from web-browser offered by you, dose not support to create a collection with "[ ]" syntax

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/nameof.md

### Document Version Independent Id

7c19d7e6-f241-2f7e-9dad-737df8328663

### Article author

@BillWagner

### Metadata

* ID: d4b82de3-3121-209c-6dc4-6267f726dcfe 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks @cirmaciuadrian 

I've opened a PR to fix this issue.
