### ISSUE TITLE
Tables in html format

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/docs#4001]
In the [style guide](https://github.com/dotnet/docs/blob/master/styleguide/template.md#tables) there is recommendation to use md-format for tables.

But there are some articles with tables in html-format.
For example:
[Strings](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/strings)

Is there any reason to use such format or will it be better to make a change?

---

I suppose html-tables could be a reason of weird render

![simg](https://user-images.githubusercontent.com/16510738/34279490-dc036752-e6b9-11e7-910c-12af2ccac89b.jpg)

and broken formatting

https://github.com/dotnet/docs/pull/3824

**Comment by mairaw** [comment]
Hi @FoggyFinder, I'm failing to find the html table in the Strings topic you linked to.

The only table I see is defined as such:
![image](https://user-images.githubusercontent.com/12971179/34280821-610901b4-e66f-11e7-8026-d83aa0cfba8b.png)

The Query Expressions topic could probably be changed to use Markdown with some HTML elements inside the cells, given it has code blocks and some rich elements like that that are trickier to represent on a traditional Markdown table.

**Comment by FoggyFinder** [comment]
>Hi @FoggyFinder, I'm failing to find the html table in the Strings topic you linked to.

Oh, sorry for that - really it was somewhere else. I found another one - [Attributes](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/attributes)

> The Query Expressions topic could probably be changed to use Markdown with some HTML elements inside the cells, given it has code blocks and some rich elements like that that are trickier to represent on a traditional Markdown table.

Great, thank you. Just wanted to clarify the moment.
