### ISSUE TITLE
Shouldn't Events.TokenValidated be Events.OnTokenValidated?

### ISSUE THREAD

**Issue by Mark-Good** [dotnet/docs#40021]
### Type of issue

Typo

### Description

I tried to implement the workaround in the [Recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events#recommended-action) section, but it would not compile.  I wonder if `Events.TokenValidated` be `Events.OnTokenValidated` instead?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events#recommended-action

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/8.0/securitytoken-events.md

### Document Version Independent Id

064108c4-238d-f459-29d0-cda789d1d619

### Article author

@serpent5

### Metadata

* ID: ee556bfa-702d-448b-32fe-144e43f02259 
* Service: **dotnet-fundamentals**

**Comment by serpent5** [comment]
> I wonder if Events.TokenValidated be Events.OnTokenValidated instead?

Yes, that's correct: it should be `OnTokenValidated`. Do you want to submit a PR to fix it?
