### ISSUE TITLE
Code example incorrect (Define logger message scope)

### ISSUE THREAD

**Issue by shawncal** [dotnet/docs#40035]
### Type of issue

Code doesn't work

### Description

Under the section "Define logger message scope", look at the code block following the statement "The scope wraps the logging extension calls in a using block:" 

The code sample doesn't have a using block, nor does it call the `ProcessingWorkScope` extension method created in the previous step. (I think it's just a copy/paste of the code block from the example under the prior header).

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/high-performance-logging.md

### Document Version Independent Id

3f5f1b6e-06ac-cc07-48cd-b8b957a4abbb

### Article author

@IEvangelist

### Metadata

* ID: aa00c051-c047-bbcd-5e25-ca6a722b51c3 
* Service: **dotnet-fundamentals**

**Comment by rextor92** [comment]
Good catch. I feel there are a couple of issues on this page related to the snippets and highlighting that I can track back to [this commit](https://github.com/dotnet/docs/commit/114b8f9e63ea6be3a2aa7ddfae18fc32d169e762#diff-757d56c99a006f335f185fe56d9f73bf81f76a8b6292620f35accff33401c06f). 

I will open a PR to resolve it.
