### ISSUE TITLE
RegexStringValidator is not available in .Net Core, but the "System.Text.RegularExpressions.Regex class" documentation does not specify that in the tip section. 

### ISSUE THREAD

**Issue by 88jonhan** [dotnet/docs#40048]
### Type of issue

Missing information

### Description

[Enter feedback here]
"Note

If you want to validate a string by determining whether it conforms to a particular pattern, you can use the [System.Configuration.RegexStringValidator](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.regexstringvalidator) class." but only in .NET Framework, not in Core

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-text-regularexpressions-regex

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/runtime-libraries/system-text-regularexpressions-regex.md

### Document Version Independent Id

d86ab84f-c511-96d7-830f-c6e20998f188

### Article author

@gewarren

### Metadata

* ID: 893cc853-8c8c-3f2d-e169-6661a13de16a 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 239900](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239900)

**Comment by gewarren** [comment]
@88jonhan You can use the [RegexStringValidator](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.regexstringvalidator) class in .NET Core versions. You just need to install this NuGet package: https://www.nuget.org/packages/System.Configuration.ConfigurationManager.
