### ISSUE TITLE
Add an example of top-level statements with command line arguments

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40064]
### Type of issue

Missing information

### Description

The top level statements examples should include one with command line arguments.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/main-command-line

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/program-structure/main-command-line.md

### Document Version Independent Id

d942d65a-87e4-1525-bd94-b005f1b7cbac

### Article author

@BillWagner

### Metadata

* ID: 06ef4bd7-7012-8afd-721a-a4c31db20202 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by timdeschryver** [comment]
I can pick this one up.

Do you got some more guidance on what is desired here, or is OK to just update the existing (https://github.com/dotnet/docs/commit/1fbba5d4c429ad7d7554e72e93c61cf3dd270e52) example?

I was thinking about adding some more info/examples, but I noticed that everything is already documented (including command line arguments) in the [referenced article for Top-level statements](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#args).

**Comment by BillWagner** [comment]
Hi @timdeschryver 

I think there's two things to add: show that top-level statements *can* use `args`, and *can* return a value. Then, I'd link to the referenced article on Top-level statements. That is enough so that readers won't assume top level statements can't access command line args or return a value.
