### ISSUE TITLE
Define "Assembly"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40066]
### Type of issue

Missing information

### Description

The term "assembly" is used in this article, but isn't defined.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/internal.md

### Document Version Independent Id

4926fa62-f791-dc1a-7c09-7b268180d20e

### Article author

@BillWagner

### Metadata

* ID: ac43c546-b79a-a4cb-6b59-7037334b83e0 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by bigboybamo** [comment]
Hi @BillWagner  What definition do you mean? I can see a link to assemblies definition in the article
<img width="452" alt="image" src="https://github.com/dotnet/docs/assets/60369677/36cb607c-fe0a-4666-995d-8165dc30e1d1">

**Comment by BillWagner** [comment]
Hi @bigboybamo 

First, that link should be made more prominent when the term "assembly" is first used. We should add an informal definition for an "assembly" as "An *assembly* an executable or dynamic link library (DLL) produced from compiling one or more source files."

**Comment by bigboybamo** [comment]
Hi @BillWagner 
I opened a Pull Request https://github.com/dotnet/docs/pull/40228

**Comment by BillWagner** [comment]
Fixed in #40228
