### ISSUE TITLE
Include index operator

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40071]
### Type of issue

Missing information

### Description

The index operator `[]` isn't mentioned in this article. It should be noted that accessing an indexer could also throw an exception, just like the member access operator (`.`).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-references.md

### Document Version Independent Id

11f314de-dd3a-362e-b2bb-d0a2133cfc7b

### Article author

@BillWagner

### Metadata

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d 
* Service: **dotnet-csharp**
* Sub-service: **null-safety**

**Comment by BartoszKlonowski** [comment]
@BillWagner Is this issue still valid? I'm looking at the very last section of that page, here:
https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#arrays
and I see it describes the possibility of an exception thrown by `[]` operator.
If I get this wrong, then if you could elaborate a bit and assign me that would be great!

**Comment by BillWagner** [comment]
Hi @BartoszKlonowski 

Yes, it's still valid. The paragraph at the end describes the "hole" in analysis for arrays of a reference type:

```csharp
string[] someNotes = new string[10];
Console.WriteLine(string[5].Length); // Array elements are null
```

What's missing is that a type with an indexer throws a NullReference Exception on `[]` just like on `.`:

```csharp
public class C
{
    public void M() {}
    public this[int i]
    { 
        get { /* ... */ }
        set { /* ... */}
    }
}

// elsewhere:

C c = default;
c.M(); // Null Reference Exception
c[4] = 24; // Null Reference Exception. Needs to be descxribed.
int j = c[4]; // Null Reference Exception
```

Does that make sense?

**Comment by BartoszKlonowski** [comment]
@BillWagner Yes, totally, thank you!
I will launch a PR with this addition.
