### ISSUE TITLE
Link to this article from all articles in this section

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40072]
### Type of issue

Missing information

### Description

The other articles in this section need to link to this one, specifically the section on where in the csproj to put the XML elements.

Otherwise, readers may not know how to set this in their builds.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/index.md

### Document Version Independent Id

691a6e9e-00ea-6210-c64a-659ba7930bec

### Article author

@BillWagner

### Metadata

* ID: 1e1ea586-7719-df69-7d8a-8a04cddb5543 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by timdeschryver** [comment]
🙋 I can take this one.
Just to be sure that I understand it correctly, every link on the page should have a "back-link" towards this page at the bottom.

For example, a "C# compiler options" link will be added to the "See also" (or "Related content") section:
![image](https://github.com/dotnet/docs/assets/28659384/f9b68459-8462-4a3a-ade1-be795799296b)
