### ISSUE TITLE
The release numbers for 4.7.2 are missing from "How To: Determine Which .NET Framework Versions Are Installed" 

### ISSUE THREAD

**Issue by Jaykul** [dotnet/docs#4008]
I would send a PR, but I don't actually know both numbers.

Now that .Net Framework 4.7.2 is out, the tables need to be updated.

**Comment by mairaw** [comment]
Hi @Jaykul, I'm not aware that 4.7.2 is out already and even if it was, it would be a preview release. @vivmishra can you confirm whether 4.7.2 preview has been released already?

We do tag and other topics with a special value (updateeachrelease) which indicates the set of topics that we need to review every time there's a new release. So we'll take care of these updates once 4.7.2 is out.

**Comment by Jaykul** [comment]
LOL. I should know better than to file bugs based on other people's information. Someone asked for an update to a script I have on StackOverflow and I just reacted. My bad.

**Comment by mairaw** [comment]
No worries. 😄 

And I just double checked again and we haven't shipped 4.7.2 yet.
