### ISSUE TITLE
Fix NUnit content

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs#40080]
### Describe the issue or suggestion

Imported from UUF:

> With <PackageReference Include="nunit" Version="4.0.1" /> the Assert.IsFalse statements are invalid. Either change them to Assert.That or ClassicAssert.IsFalse

---
[Associated WorkItem - 236526](https://dev.azure.com/msft-skilling/Content/_workitems/edit/236526)

**Comment by rextor92** [comment]
We have recently updated all our projects from NUnit 3.x -> 4.x
I can go over the entire repo to check where its used and convert the classic assert to constraints model.

**Comment by rextor92** [comment]
Okay, I'd actually need some help on how to tackle this. Let's take this page as an example: [Unit testing C# with NUnit and .NET Core](https://github.com/dotnet/docs/blob/main/docs/core/testing/unit-testing-with-nunit.md) - [preview](https://learn.microsoft.com/en-gb/dotnet/core/testing/unit-testing-with-nunit)

- The inline C# code is showing the `Assert.IsFalse` statement, as in NUnit3
- The reference under "Adding more features" correctly leads to [the in-repo samples](https://github.com/dotnet/docs/blob/main/samples/snippets/core/testing/unit-testing-using-nunit/csharp/PrimeService.Tests/PrimeService_IsPrimeShould.cs#L25) which have been properly updated by Terje a few months ago. This leads to contradicting code (the NUnit3 and NUnit4 approach on same page)
- Other links in the article lead to the [dotnet samples repo](https://github.com/dotnet/samples/blob/main/core/getting-started/unit-testing-using-nunit/PrimeService.Tests/PrimeService_IsPrimeShould.cs#L26) which contains the exact same code - but hasn't been updated in a while.

I am thinking of removing the inline code from the articles and referencing to the already updated code by Terje, but this leaves the dotnet/samples repo and the references to it. I can either update it as well, or remove / repoint the samples links to the local ones?

**Comment by rextor92** [comment]
Hey @BillWagner, sorry for the confusion with the PR in dotnet/samples, it relates to this issue but does not fix it entirely. 
There are a few more things to update in this repo that I expect to be done with today.
