### ISSUE TITLE
[Styles Enforcement] Stylecop / ReSharper settings

### ISSUE THREAD

**Issue by barbosatek** [dotnet/docs#4009]
Stylecop or ReSharper static analizer rules

Would be great if a ReSharper dotsettings file or stylecop rules are provided to enforce these standards. Maybe a section called Static Analyzers or something along those words

Enforcing standards and rules isn't an easy task, however tools like Stylecop and ReSharper have shown great success. While they come with great out of the box rules, it would be great if this repository provides the rules and settings files to enforce the standards it evangelizes and update those files as the standards change.

**Comment by BillWagner** [comment]
@barbosatek Are you looking for information on something like this [Analyzer NuGet package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)? Those enforce a variety of style and standardization practices.

**Comment by mairaw** [comment]
@barbosatek since we didn't hear back from you to be able to clarify exactly what you'd like to see, we'll be closing this issue. If you have more information on what you need, we can reopen this issue. Thanks!
