### ISSUE TITLE
404 on API search -- beforefieldinit

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#4015]
I get a 404 on the one link (if I click on it) that I see on this page: https://docs.microsoft.com/en-us/dotnet/api/?term=beforefieldinit

**Comment by mairaw** [comment]
There was a recent change to enum pages that is causing some issues. I’ll let them know that search is also affected. Thanks @richlander!

**Comment by richlander** [comment]
I saw some other enum pages that had this same problem. Great.

**Comment by mairaw** [comment]
They’ve deployed a fix that resolved the broken link issues. But search is still broken. I’m following up on that.

**Comment by mairaw** [comment]
This seems resolved now.
