### ISSUE TITLE
Incorrect order on default configuration sources

### ISSUE THREAD

**Issue by dozer75** [dotnet/docs#40162]
### Type of issue

Other (describe below)

### Description

The section [Alternative hosting approach](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration#alternative-hosting-approach) contains a list of default configuration order. This list is however wrong, the `appsettings.json` and `appsettings.Environment.json` should switch place, ref [code](https://github.com/dotnet/runtime/blob/6149ca07d2202c2d0d518e10568c0d0dd3473576/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L234).

The correct list is:
1. Command-line arguments using the [Command-line configuration provider](configuration-providers.md#command-line-configuration-provider).
2. Environment variables using the [Environment Variables configuration provider](configuration-providers.md#environment-variable-configuration-provider).
3. [App secrets](/aspnet/core/security/app-secrets) when the app runs in the `Development` environment.
4. *appsettings.*`Environment`*.json* using the [JSON configuration provider](configuration-providers.md#file-configuration-provider). For example, *appsettings*.***Production***.*json* and *appsettings*.***Development***.*json*.
5. *appsettings.json* using the [JSON configuration provider](configuration-providers.md#file-configuration-provider).
6. [ChainedConfigurationProvider](xref:Microsoft.Extensions.Configuration.ChainedConfigurationSource) : Adds an existing `IConfiguration` as a source.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md

### Document Version Independent Id

0d5de37c-8f89-b6a5-3132-2c5214196bfd

### Article author

@IEvangelist

### Metadata

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9 
* Service: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
Fixed by #39663

**Comment by aayjaychan** [comment]
Can this be reopened?  #39663 actually broke the documentation rather than fixing it.  Configuration sources added later to `IConfigurationBuilder` have higher priority, but in the documentation, sources listed first have higher priority.

Interestingly, the [order in ASP\.NET Core documentation remains correct](https://github.com/dotnet/AspNetCore.Docs/blob/7a5461c347c0a37e3c5d98df9310279a27e1bb18/aspnetcore/fundamentals/configuration/index.md?plain=1#L57).
