### ISSUE TITLE
Wrong pt-br translation

### ISSUE THREAD

**Issue by muriiloandrade** [dotnet/docs#40189]
### Type of issue

Typo

### Description

The english version of the error description goes as:
> Cannot convert null to 'type' because it is a non-nullable value type

While the pt-BR translation is:
> Não é possível converter o valor nulo em 'type' porque ele >**não**< é um tipo de valor não anulável

That highlighted "não" should not exist since its double negating the sentence wrongly. It should be:
> Não é possível converter o valor nulo em 'type' porque ele é um tipo de valor não anulável

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/misc/cs0037

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0037.md

### Document Version Independent Id

4d1f55d3-9f9a-ba38-d2c2-3f161719908b

### Article author

@BillWagner

### Metadata

* ID: 0162ff40-4ddd-1ed6-f80e-4888acf7e1b8 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Thanks for reporting this @muriiloandrade 

I've reported this to our localization team here (internal link): https://dev.azure.com/ceapex/CEINTL/_workitems/edit/957842

As I've transferred this to the correct team, I'll close the public issue.
