### ISSUE TITLE
Columns option doesn't take comma-separated list

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#40210]
### Type of issue

Other (describe below)

### Description

Verbatim from the feedback control:
>I believe there is a mistake on the page which states the --columns parameter can take mulitple comma separated values, but this is not true as it reports an error when more than a single column is stated

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-search

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-search.md

### Document Version Independent Id

09c2a9a5-bb6b-d3c0-45fb-94a0e50117c2

### Article author

@tdykstra

### Metadata

* ID: 0f1e2c41-5d54-15f3-795f-04553bcfbc82 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 239901](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239901)

**Comment by tdykstra** [comment]
@timdeschryver Would you like to take this CLI issue?

**Comment by timdeschryver** [comment]
Sounds good to me @tdykstra 👍
