### ISSUE TITLE
Obsolete attribute missing from list of attributes that control XML Serialization

### ISSUE THREAD

**Issue by alundporchsoftware** [dotnet/docs#40232]
### Type of issue

Missing information

### Description

The System.Obsolete attribute has prevented serialization of fields and properties being serialized by the XMLSerializer since .NET 3.5 (see https://weblogs.asp.net/psteele/xml-serialization-and-the-obsolete-attribute). As of .net core 6 and presumably 7 and 8, this is still true of the XMLSerializer class. 

I can't find this documented anywhere in the documentation for the XMLSerializer. This document seems like the logical place to mention the interaction with the Obsolete attribute. 

I want to propose the following change: https://github.com/alundporchsoftware/docs/commit/dd992f635e23a982992f7762d2c88688b2a28336

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/attributes-that-control-xml-serialization

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/attributes-that-control-xml-serialization.md

### Document Version Independent Id

f0e557a3-1410-671b-2143-098c79540a58

### Article author

@gewarren

### Metadata

* ID: ca62ea13-6c14-6e33-3406-4a29a5a6d225 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
Thanks @alundporchsoftware. I'm good with your change if you want to open a PR!

**Comment by twdkeule** [comment]
We have noticed another undocumented behaviour: the ObsoleteAttribute also makes the XMLSerializer ignore Xmlspecific attributes.

Deserializing this class throws an exception:
```
[Obsolete]
[XmlRoot("root")]
public class Message {...}
```

Deserializing this does not (notice the order of the attributes):
```
[XmlRoot("root")]
[Obsolete]
public class Message {...}
```
