### ISSUE TITLE
Broken formatting in Reflection guide

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4023]
https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names

On this page the table "Backus-Naur Form Grammar for Type Names" is rendering incorrectly. Here's what it previously looked like on msdn: https://msdn.microsoft.com/it-it/library/yfsftwz6(v=vs.110).aspx

**OLD**
![image](https://user-images.githubusercontent.com/4837132/34382422-acb33594-eb06-11e7-9495-0dd19dd90266.png)

**NEW**
![image](https://user-images.githubusercontent.com/4837132/34382431-bdb7bd10-eb06-11e7-85d7-687a3a129634.png)

**Comment by mairaw** [comment]
Thanks for letting us know @ChrisMaddock! We'll address it shortly. It's probably due to the use of pipes.

**Comment by BillWagner** [comment]
@terrajobst One solution would be to translate from BNF to ANTLR, and use the ANTLR grammar syntax highlighter. [See example from the C# grammar](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements)

Thoughts?

**Comment by terrajobst** [comment]
Like this? Yep, looks very readable to me. 👍 

```antlr
TypeSpec
	: ReferenceTypeSpec
	| SimpleTypeSpec
	;

ReferenceTypeSpec
	: SimpleTypeSpec '&'
	;

SimpleTypeSpec
	: PointerTypeSpec
	| ArrayTypeSpec
	| TypeName
	;

PointerTypeSpec
	: SimpleTypeSpec '*'
	;

ArrayTypeSpec
	: SimpleTypeSpec '[ReflectionDimension]'
	| SimpleTypeSpec '[ReflectionEmitDimension]'
	;

ReflectionDimension
	: '*'
	| ReflectionDimension ',' ReflectionDimension
	| NOTOKEN
	;

ReflectionEmitDimension
	: '*'
	| Number '..' Numero
	| Number '…'
	| ReflectionDimension ',' ReflectionDimension
	| NOTOKEN
	;

Number
	: [0-9]+
	;

TypeName
	: NamespaceTypeName
	| NamespaceTypeName ',' AssemblyNameSpec
	;

NamespaceTypeName
	: NestedTypeName
	| NamespaceSpec '.' NestedTypeName
	;

NestedTypeName
	: IDENTIFIER
	| NestedTypeName '+' IDENTIFIER
	;

NamespaceSpec
	: IDENTIFIER
	| NamespaceSpec '.' IDENTIFIER
	;

AssemblyNameSpec
	: IDENTIFIER
	| IDENTIFIER ',' AssemblyProperties
	;

AssemblyProperties
	: AssemblyProperty
	| AssemblyProperties ',' AssemblyProperty
	;

AssemblyProperty
	: AssemblyPropertyName '=' AssemblyPropertyValue
	;
```

**Comment by mairaw** [comment]
Hey @BillWagner, thanks for the offer. I'm not particularly attached to this issue, so feel free to take over if you'd like.
