### ISSUE TITLE
Document as an option -p:TestTfmsInParallel=false

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#40235]
### Type of issue

Other (describe below)

### Description

Starting in .NET 9 Preview 2, `dotnet test` runs tests for different TFMs in parallel by default. You can opt out of this behavior by setting the MSBuild property `TestTfmsInParallel` to `false`. See [Run tests in parallel](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview#run-tests-in-parallel). Update the dotnet test documentation to cover this new setting and make it discoverable.

Related to https://github.com/dotnet/sdk/issues/39470

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-test.md

### Document Version Independent Id

2878af44-8208-7bd8-46d4-3acda3e82ce0

### Article author

@tdykstra

### Metadata

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16 
* Service: **dotnet-fundamentals**

**Comment by MattParkerDev** [comment]
does this mean we can opt into Parallel test execution in .NET 8 with TestTfmsInParallel=true? or its only in .NET 9
