### ISSUE TITLE
NETSDK1083	The specified RuntimeIdentifier 'win10-x64' is not recognized.

### ISSUE THREAD

**Issue by CedricHensen** [dotnet/docs#40258]
### Type of issue

Code doesn't work

### Description

I get this error when i try to run a project i have looked and tried to fix it but non of the solutions i have tried worked. I dont know if this came when updated visual studio or im just doing something wrong. Im also using ASP.NET maker 2024 for this project.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1083?f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1083)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1083.md

### Document Version Independent Id

d8df6fae-fd1a-d051-7710-04bfbad32d2f

### Article author

@tdykstra

### Metadata

* ID: f3a467da-2c73-4bec-a2f2-e416abf6659d 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
This should be fixed by #40285.

**Comment by tdykstra** [comment]
> This should be fixed by #40285.

Closing
