### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ohchoongho** [dotnet/docs#40253]
### Type of issue

Typo

### Description

[여기에 피드백 입력]

### Page URL

https://learn.microsoft.com/ko-kr/dotnet/csharp/roslyn-sdk/work-with-syntax

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/work-with-syntax.md

### Document Version Independent Id

6a1490ae-78b2-d8ba-07f1-df1c22f7a830

### Article author

@BillWagner

### Metadata

* ID: 6af3ae43-b958-0576-168e-539936d2ba81 
* Service: **dotnet-csharp**
* Sub-service: **roslyn-sdk**

**Comment by BillWagner** [comment]
closing as a blank issue
