### ISSUE TITLE
Consider ways to make this page look less hard

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#40280]
### Type of issue

General feedback on page

### Description

This page seems very intimidating. I don't know if there are limitations that keep us from having separate pages here, which might help a bit. Mostly this content, especially install with VS jumps straight to information an expert needs (which TFM) and not what a beginner needs "You have what you need and this is how you adjust installed workloads if you need that"

Since most folks use VS, could we move that to the top and start with friendly language like "If you're using Visual Studio, hopefully you do not need anything on this page". OK, not that ;-)

Or put DevKit installation at the top with a nice simple walk-through. 

Installation seems a place to focus on a welcome, feel good, hand holding vibe. 

This page makes it look like it is hard to install .NET, and it came up high in SEO.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#install-with-visual-studio

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/windows.md

### Document Version Independent Id

d11d0d14-8a03-50e4-5c00-9a4417ad4d0a

### Article author

@adegeo

### Metadata

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 239918](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239918)

**Comment by adegeo** [comment]
Automation closed this because it was originally created empty.

**Comment by adegeo** [comment]
Great feedback. This page has been neglected for sure.
