### ISSUE TITLE
Bad docs. 

### ISSUE THREAD

**Issue by cevergara-apex** [dotnet/docs#40293]
### Type of issue

Other (describe below)

### Description

The code mentions that All, Any and Contains are used for boolean results, however the examples are using it as a filter. 

Also:
The last example says this in the comments "// Determine which market contains fruit names equal 'kiwi'"
but it's now what the example is about. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/quantifier-operations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/standard-query-operators/quantifier-operations.md

### Document Version Independent Id

045d5185-5b9c-effc-c542-75192e320d29

### Article author

@BillWagner

### Metadata

* ID: da65be87-16ea-ebcb-e098-6dbf3579152f 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BartoszKlonowski** [comment]
Hello @cevergara-apex!

Regarding

> The code mentions that All, Any and Contains are used for boolean results, however the examples are using it as a filter.

Well, examples are using them as a predicate. And while it sounds like I'm making a nitpick on a word, it does make the difference.
The [`where`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-clause) takes a condition that should return boolean for given data. And in all those examples such condition is a predicate indeed returning boolean for conditions met or not.

As for that comment in the last example: Yes, this definitely should be removed.

If you have any more concerns regarding the `All`, `Any`, `Contains` then feel free to ask or just drop a suggestion to be considered to be included in the page.
