### ISSUE TITLE
Variable name `alias` colored like a keyword

### ISSUE THREAD

**Issue by fterrani** [dotnet/docs#40304]
### Type of issue

Other (describe below)

### Description

In the example provided for reference variables, the name `alias` is colored like a keyword, probably due to syntax highlighting limitations. This makes the reading a bit confusing (e.g. I thought I had to type `alias` to create a reference to a variable at first).

Maybe using a different name (`aAlias`, `refToA`, `aliasOfA`...) would make it clearer?

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/declarations#reference-variables

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/declarations.md

### Document Version Independent Id

b9310adb-a7c4-274a-2390-0c40a4cb368e

### Article author

@BillWagner

### Metadata

* ID: 98d50744-0c94-b7d6-2f6f-c9d7130aee92 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
While this is a bug in the old syntax highlighting code (/cc @jffriend), it will be quicker to fix this by changing the variable name.

(The code works as written because `alias` isn't a C# keyword.)

**Comment by Rageking8** [comment]
This issue also extends to other contextual keywords. For instance, there are lots of variables named `value` in the docs.
