### ISSUE TITLE
Rename and MoveTo not working under Windows11

### ISSUE THREAD

**Issue by jerryelbow** [dotnet/docs#40319]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
I wrote a file renaming utility several years ago using VB.net. I have updated it with new features over the years and as new versions of Windows came out. A few months ago, I started getting "Access to the path 'pathname' is denied" errors on the line using the Rename command. This seems to be after an update on Windows 11 Home. Based on some advice here, I tried changing Rename o Move and MoveTo, both to no avail. What commands actually work to rename files under Windows 11? I have a similar issue with deleting files from a C# app I wrote. I've also tried changing permissions on the folders based on documentation I've seen here and elswehre but nothing seems to work.

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/drives-directories-files/how-to-rename-a-file

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-rename-a-file.md

### Document Version Independent Id

ef935b89-2a27-e760-c768-b85409f0b4d3

### Article author

@KathleenDollard

### Metadata

* ID: de22554d-f31b-bcea-5cbb-218e64729bb4 
* Service: **dotnet-visualbasic**

---
[Associated WorkItem - 259822](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259822)

**Comment by adegeo** [comment]
Hi @jerryelbow it depends on the place you're trying to write files. The example here in this article is indeed very old. Windows has locked down root boot drive access it seems. In explorer I can't event create a file at C:\ but I can create a directory. Saving files from browsing, even exporting an email in outlook, all fail at the root of C:\ but work fine in other places.

To test the API I ran this code, which worked fine. If I changed it to the root of C:\ it does indeed fail.

```vb
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
    Const newFileName = "C:\folder1\Test.txt"
    Const renameFileName = "C:\folder1\secondTest.txt"
    Const moveFileName = "C:\folder1\movedTest.txt"

    If My.Computer.FileSystem.FileExists(newFileName) Then My.Computer.FileSystem.DeleteFile(newFileName)
    If My.Computer.FileSystem.FileExists(renameFileName) Then My.Computer.FileSystem.DeleteFile(renameFileName)
    If My.Computer.FileSystem.FileExists(moveFileName) Then My.Computer.FileSystem.DeleteFile(moveFileName)

    Dim newFileWriter = My.Computer.FileSystem.OpenTextFileWriter(newFileName, False)
    newFileWriter.Write("Some content")
    newFileWriter.Close()
    newFileWriter.Dispose()

    My.Computer.FileSystem.RenameFile(newFileName, System.IO.Path.GetFileName(renameFileName))
    My.Computer.FileSystem.MoveFile(renameFileName, moveFileName)
End Sub
```

**Comment by jerryelbow** [comment]
Steve;

Thanks for the information. However, my file renaming utility is failing on files in subfolders folders like "V:\Media\CDs\Rock and Roll\Rolling Stones, The\Let It Bleed". I'm not trying to rename files in the root of C:\.

Jerry
________________________________

**Comment by jerryelbow** [comment]
Steve;

Thanks for trying. I never set any of my folders to be protected, much less all of them, under Win 11. The drives are all local, though some are external USB drives. The code works fine on Win 10 and worked fine under Win 11 until some update happened at some point. What fun!

Jerry Bell
________________________________

**Comment by adegeo** [comment]
@jerryelbow I totally get it. I would use the feedback hub in Windows to see if you can report it and get someone to look at it. Hopefully the regression is going to be fixed at some point if someone else has reported it, especially those in the Insiders program.
