### ISSUE TITLE
Wrong example for creating an array

### ISSUE THREAD

**Issue by Praxo** [dotnet/docs#40314]
### Type of issue

Code doesn't work

### Description

The example of creating a single-dimensional doesn't work :
```csharp
int[] array2 = [1, 2, 3, 4, 5, 6];
```
It works fine with curly brackets, but not square brackets 
```csharp
int[] array2 = {1, 2, 3, 4, 5, 6};
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/arrays

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/arrays.md

### Document Version Independent Id

38aea826-1f7b-049e-1b9e-d13eea138c44

### Article author

@BillWagner

### Metadata

* ID: be43453e-7757-f4db-6736-ba8be7ebc4d6 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @Praxo 

This is using a new C# 12 feature, [collection expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions). We want more people to see this feature and adopt it. That's why we added it to more of the samples.
