### ISSUE TITLE
Doc: clear an error comment on a solution example

### ISSUE THREAD

**Issue by amuza2** [dotnet/docs#40321]
### Type of issue

Other (describe below)

### Description

[Code improve]
In the third example when you solved the problem adding the static keyword you have to clear the error comment on the method was called on the Main method

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0120?f1url=%3FappId%3Droslyn%26k%3Dk(CS0120)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0120.md

### Document Version Independent Id

1c66477a-2a97-4eff-1cd8-937f4e7880a0

### Article author

@BillWagner

### Metadata

* ID: 672e69a1-80bb-87cd-b3b8-bf104d8aa89e 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Thanks for pointing this out @amuza2 

I've opened a PR to fix this issue.
