### ISSUE TITLE
[SerializableAttribute] still mentioned in the Exception doc despite the current obsoletion strategy

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/docs#40333]
### Context

https://learn.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-localized-exception-messages - mentions couple times marking the `Exception` with `SerializableAttribute`.

However based on the [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md) this should not be already done from net8 up (including multitargeted projects): https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#no-new-serializable-types-introduced-net-8

### Goal

The documentation doesn't recommend decorating new custom `Exception`s with `SerializableAttribute`

FYI @GrabYourPitchforks, @ladipro 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed065e03-3620-cd2a-66b7-706ce2f863d9
* Version Independent ID: fe5453a0-d849-a145-7260-036f769c208f
* Content: [How to create user-defined exceptions with localized exception messages - .NET](https://learn.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-localized-exception-messages)
* Content Source: [docs/standard/exceptions/how-to-create-localized-exception-messages.md](https://github.com/dotnet/docs/blob/main/docs/standard/exceptions/how-to-create-localized-exception-messages.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 286586](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286586)

**Comment by gewarren** [comment]
Also see https://github.com/dotnet/dotnet-api-docs/issues/9980#issuecomment-2246263904.
