### ISSUE TITLE
In the "String escape sequences" table, entry for backslash is incorrect

### ISSUE THREAD

**Issue by galahad2067** [dotnet/docs#40332]
### Type of issue

Typo

### Description

In the "String escape sequences" table, the escape sequence entry for backslash is listed as "\" (without the quotes).  It should be listed as "\\".

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md

### Document Version Independent Id

3317fd4a-9cd3-57cd-66f7-abb271e302e8

### Article author

@BillWagner

### Metadata

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Hi @galahad2067 

It looks correct to me.  (See screen shot).  What am I missing?

![image](https://github.com/dotnet/docs/assets/493969/6e013e48-fd68-40b8-ab19-ff6313d88eb7)
