### ISSUE TITLE
Default publish configuration may need updating in docs\core\tutorials\publishing-with-visual-studio-code.md

### ISSUE THREAD

**Issue by vadviktor** [dotnet/docs#40353]
### Describe the issue or suggestion

I'm using .NET v8.0.202, and the help of `dotnet publish --help` states:

```
-c, --configuration <CONFIGURATION>  The configuration to publish for. The default is 'Release' for NET 8.0 projects and
                                       above, but 'Debug' for older projects.
```

which should be true because when I don't specify the configuration, it creates the `Release` folder:

```
$ dotnet publish
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  CLI -> X:\src\route53-ddns-updater-dotnet\CLI\bin\Release\net8.0\CLI.dll
  CLI -> X:\src\route53-ddns-updater-dotnet\CLI\bin\Release\net8.0\publish\
```

Contrast to this, the documentation in `docs/core/tutorials/publishing-with-visual-studio-code.md` states: 
https://github.com/dotnet/docs/blob/0dd37de7264abac2c869eceb977fdba77edbaa23/docs/core/tutorials/publishing-with-visual-studio-code.md?plain=1#L31C4-L36C1

Because I am new to the .Net ecosystem and I am not sure if it is me or the docs who got something wrong, I point this out first rather than create a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6feb46a5-46de-a4ec-3549-3d4df790de03
* Version Independent ID: 5851a635-12ab-af94-2139-f217a63fd36a
* Content: [Publish a .NET console application using Visual Studio Code - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio-code?pivots=dotnet-8-0)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio-code.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/publishing-with-visual-studio-code.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment]
I think the tutorial is out of date. Thanks for logging the issue.

**Comment by tdykstra** [comment]
> I point this out first rather than create a PR.

@vadviktor If you would like to make a PR, it would be welcome.
