### ISSUE TITLE
Re-document `nullable` as a valid option for WarningsAsErrors

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/docs#40355]
### Describe the issue or suggestion

Passing `nullable` to `<WarningsAsErrors>` enables errors for the set of all nullability warnings.

Documentation was added in https://github.com/dotnet/docs/pull/17094, and seems to have been accidentally removed in https://github.com/dotnet/docs/pull/22797.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings - C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 255547](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255547)

**Comment by gewarren** [comment]
@BillWagner There was some data loss here. Maybe check the other files that were deleted in your PR to see if they had any updates while your PR was in progress, that may then have been lost?
