### ISSUE TITLE
Issue with Microsoft.Office.Interop.Word Library Bulleted Lists Conversion to HTML

### ISSUE THREAD

**Issue by Rotem-intel** [dotnet/docs#40367]
### Type of issue

Other (describe below)

### Description

When attempting to convert Word documents containing bulleted lists to HTML using the Microsoft.Office.Interop.Word library, the resulting HTML output exhibits several problems:

1. The conversion of bullet points to HTML is messy and inconsistent.
2. Instead of using standard HTML "ul" and "li" tags for bullet points, the conversion inserts various non-standard tags such as "margin" tags.
3. The messy HTML output causes compatibility issues with other tools and libraries when attempting to convert the HTML back to Word format - As result, extra indentations and spacings are sometimes added between bullets and before each bullet point, which disrupts the formatting integrity of the document.

I kindly request assistance in resolving this issue and achieving a cleaner conversion of bulleted lists from Word to HTML format using the Microsoft.Office.Interop.Word library. Ideally, the conversion process should generate HTML code that adheres to standard HTML list formatting using "ul" and "li" tags.

Thank you for your attention to this matter. I look forward to your prompt assistance in resolving this issue.

Best regards,
Rotem

![convert_to_HTML](https://github.com/dotnet/docs/assets/102519333/12d416c0-e05a-4b3a-9715-adae07b158e5)

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/native-interop/cominterop

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/native-interop/cominterop.md

### Document Version Independent Id

6d46d281-1345-f64a-d029-30f657a5e9c0

### Article author

@jkoritzinsky

### Metadata

* ID: 8570d17a-af20-fc3f-4357-1ffef57d0f44 
* Service: **dotnet-fundamentals**

**Comment by adamsitnik** [comment]
Hi @Rotem-intel 

The [README.md of this package](https://www.nuget.org/packages/Microsoft.Office.Interop.Word#readme-body-tab) says:

>  This is entirely unsupported 

So I am afraid the package is "as is" and it won't be fixed.

The best I can do is to point you to the link that allows you to contact the author:

![image](https://github.com/dotnet/docs/assets/6011991/2a37d580-64e2-47e3-88d5-e4afbf8bb824)
