### ISSUE TITLE
h

### ISSUE THREAD

**Issue by hazemdr454** [dotnet/docs#40365]
### Type of issue

Typo

### Description

[اكتب ملاحظاتك هنا]
issus

### Page URL

https://learn.microsoft.com/ar-sa/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md

### Document Version Independent Id

1850602d-6b92-1449-c8bd-116e36fc0f26

### Article author

@adegeo

### Metadata

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adamsitnik** [comment]
Hello @hazemdr454 !

Where exactly is the typo? I have searched this website for "issus" and was not able to find it.

**Comment by adegeo** [comment]
Closing due to lack of response.
