### ISSUE TITLE
Docker image non-root UID doesn't match 

### ISSUE THREAD

**Issue by stevo-knievo** [dotnet/docs#40363]
### Type of issue

Typo

### Description

The doc doesn't match the actual port. Which is 1654. Please see [PR #4715](https://github.com/dotnet/dotnet-docker/pull/4715)

**Current it says:**

> NET 8 adds an environment variable for the UID for the non-root user, which is 64198

**But it should say:**

> NET 8 adds an environment variable for the UID for the non-root user, which is 1654

Page:
https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/containers#non-root-user

Thank you!

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/containers#non-root-user

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-8/containers.md

### Document Version Independent Id

e9820016-a64e-4f99-0c32-67c150075fa7

### Article author

@gewarren

### Metadata

* ID: 0dbbb102-a5ba-7f0b-ca91-a4dc5bb6ebe1 
* Service: **dotnet-fundamentals**

**Comment by BartoszKlonowski** [comment]
@gewarren I will work on this.
