### ISSUE TITLE
warning CA1416: This call site is reachable on: 'iOS' 15.4 and later, 'maccatalyst' 15.4 and later.." 

### ISSUE THREAD

**Issue by ngocdat** [dotnet/docs#40381]
### Type of issue

Code doesn't work

### Description

var linkfolder = await FolderPicker.PickAsync(default);
nuget: communitytoolkit.maui
Warning	CA1416	This call site is reachable on: 'iOS' 11.0 and later, 'maccatalyst' 11.0 and later. 'FolderPicker.PickAsync(CancellationToken)' is only supported on: 'Android', 'iOS' 14.0 and later, 'maccatalyst' 14.0 and later, 'Tizen', 'Windows'.	EN_MAUI (net8.0-ios)	E:\c#\EN_MAUI\EN_MAUI\MainPage.xaml.cs	212	Active
 code works on android 5
code doen't work on android 11

### Page URL

https://learn.microsoft.com/vi-vn/dotnet/fundamentals/code-analysis/quality-rules/ca1416

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1416.md

### Document Version Independent Id

e4517175-91cf-0fcd-d438-23e652f5022c

### Article author

@buyaa-n

### Metadata

* ID: 6f8fbd7e-af44-859a-3967-b61bed6919a0 
* Service: **dotnet-fundamentals**

**Comment by buyaa-n** [comment]
> This call site is reachable on: 'iOS' 11.0 and later, 'maccatalyst' 11.0 and later.

This message suggests that your project targeting iOS 11.0

> 'FolderPicker.PickAsync(CancellationToken)' is only supported on: 'iOS' 14.0 and later, 'maccatalyst' 14.0 and later

This suggested that the API only available on iOS 14.0 or above, therefore you cannot use it within a call site that is reachable on iOS 11.0
