### ISSUE TITLE
[Breaking change]: krb5-libs / libgssapi-krb5-2 removed from all Docker images, but only Alpine mentioned in release notes

### ISSUE THREAD

**Issue by ggradnig** [dotnet/docs#40441]
### Description

In https://github.com/dotnet/dotnet-docker/issues/4844, the Kerberos installation (krb5-libs / libgssapi-krb5-2) was removed from **all** dotnet Docker images, however the release notes only state that they were removed from Alpine: https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/krb5-libs-package

libgssapi-krb5-2 is not installed in Debian or Ubuntu per default, therefore they are now missing in these images as well. To users of these images, this is a breaking change as libgssapi-krb5-2 now needs to be installed separately.

### Version

.NET 8 GA

### Previous behavior

Prior to https://github.com/dotnet/dotnet-docker/issues/4844, libgssapi-krb5-2 was installed in the Debian and Ubuntu images.

### New behavior

libgssapi-krb5-2 is now missing in the Debian and Ubuntu images, leading to an exception when initiating the Kerberos authentication.

![image](https://github.com/dotnet/docs/assets/6489928/cbad818a-95c2-4a12-a986-7ee29588f995)

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

To comply with the updated principles doc: https://github.com/dotnet/dotnet-docker/pull/4842

### Recommended action

Update the documentation and release notes to warn users about this breaking change.

### Feature area

Containers

**Comment by gewarren** [comment]
@richlander Can you comment on this?

**Comment by richlander** [comment]
This is correct. Sorry about that!

Relevant PR: https://github.com/dotnet/dotnet-docker/pull/4847

We made the Alpine change first and it (in part) informed the referenced strategy that led to the final changes. We intend for Kerberos to be a manually installed package going forward.

**Comment by richlander** [comment]
Want me to make a PR for that, @gewarren?

**Comment by gewarren** [comment]
That would be great @richlander, thanks.
