### ISSUE TITLE
PATH changes incorrect for dotnet-sdk-7.0.███-linux-arm64 on Debian 12

### ISSUE THREAD

**Issue by demonfiddler** [dotnet/docs#40475]
### Type of issue

Code doesn't work

### Description

The instructions:
```
$ export DOTNET_ROOT=$HOME/.dotnet
$ export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
```

appear to be incorrect for dotnet-sdk-7.0.███-linux-arm64. Running the scripted install
`$ sudo ./dotnet-install.sh --channel 7.0`
results in a directory /root/.dotnet but no /root/.dotnet/tools subdirectory

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md

### Document Version Independent Id

2be3647d-495b-c9f0-cf06-9a7bf687d3bb

### Article author

@adegeo

### Metadata

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

> [!NOTE]
> This content was automatically updated to _filter out profanity_. If you feel as though this was done in error, please [file an issue with the details](https://github.com/IEvangelist/profanity-filter/issues/new).

**Comment by adamsitnik** [comment]
Tagging @adegeo and @richlander to provide help.

**Comment by adegeo** [comment]
@demonfiddler It's possible the tools folder doesn't exist until you install a global tool, have you tried doing that? You can find a list of tools on NuGet: https://www.nuget.org/packages?packagetype=dotnettool

**Comment by demonfiddler** [comment]
Aha, @adegeo, that could very well be it! No, I hadn't tried installing any .Net tools as yet. Apologies for the false alarm if that's that cause.l
