### ISSUE TITLE
".NET regular expression source generators" - wrong code snippets in article for .NET 8

### ISSUE THREAD

**Issue by RedFlames** [dotnet/docs#40477]
### Type of issue

Other (describe below)

### Description

This article seems to be a bit of a mess, at least when reading the .NET 8 "pivot".

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators?pivots=dotnet-8-0#inside-the-source-generated-files
https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators?pivots=dotnet-7-0#inside-the-source-generated-files

In the section **Inside the source-generated files** of the article, it talks about two code examples.
> _"Consider the source generator output for one of the primary functions from the `(a|bc)d` expression:"_ 
 - in the .NET 8 version of the article, it shows generated code for `(abc|def)`
 - I think here the article doesn't have any prose specific to the example, and the `(abc|def)` example _would_ be fine too, if introduced as such? I'm unsure why there's these two differing source gen regexes being used
 > _"Even when backtracking is involved, the structure of the backtracking becomes part of the structure of the code, rather than relying on a stack to indicate where to jump next. For example, here's the code for the same generated matching function when the expression is `[ab]*[bc]`:"_
 - in the .NET 8 version of the article, it shows the generated code for `(abc|def)` **again**
> _"You can see the structure of the backtracking in the code, with a CharLoopBacktrack label emitted for where to backtrack to and a goto used to jump to that location when a subsequent portion of the regex fails."_
 - all of this only exists in the actual `[ab]*[bc]` source of course 🐈 

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-source-generators.md

### Document Version Independent Id

76b98e7b-6acc-cb43-da8e-475a8b4ed5a1

### Article author

@IEvangelist

### Metadata

* ID: 56298202-fa5d-363d-3c52-adbf5256b184 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 246760](https://dev.azure.com/msft-skilling/Content/_workitems/edit/246760)

**Comment by adamsitnik** [comment]
@stephentoub could you please help me find the right person to take a look?

**Comment by stephentoub** [comment]
> @stephentoub could you please help me find the right person to take a look?

Presumably @IEvangelist as its author?

**Comment by IEvangelist** [comment]
Sorry, I've been a bit distracted lately with .NET Aspire content. I'll get to this ASAP.
