### ISSUE TITLE
        var c = (Season)4;         Console.WriteLine(c);  // output: 4

### ISSUE THREAD

**Issue by auzxj** [dotnet/docs#40507]
### Type of issue

Typo

### Description

        var c = (Season)4;
        Console.WriteLine(c);  // output: 4

maybe?:
        var c = (int)4;
        Console.WriteLine(c);  // output: 4

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/enum

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/enum.md

### Document Version Independent Id

9d67fd2d-bfaa-7af4-a8d9-fd2a84aecd15

### Article author

@BillWagner

### Metadata

* ID: 248858d2-39c9-ff54-a396-5e7b4d79b640 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @auzxj 

The current sample is correct.  See this [Sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUH1AZgAIBTKCAW2IGVSBDAZwHso8BvPY72gBzACWUAOYwuPGlUqkwY3D2IBBCMCqxx3AOpDgMvAF88BEhmIBRCpQDCrAG4zGA1mYAe9SrwA2pDhuIZ0P055BQkGFihiemIAXlpw1gA6ZVVKKABuPwVUTABOAAoAEgAiAEkoXWEwek9iWxqIUmJmADNidnp9YgFGdvydAEpO4oH07gB6ceaVXhUQYnLK6tr6z0bmtpS1bt7A/BDQuvowYgAjWOJ8uiZWAcxMg9CcgtPRianmGbnaKT19w+49ROAGMLlcElABgAWB4A/x5fLAt7ESbTYCzUDEKF+Qy4fRAA===)

It's one of the legal conversions.
