### ISSUE TITLE
Weird formulation: "The use of the following data annotation attributes are used"

### ISSUE THREAD

**Issue by petterh** [dotnet/docs#40545]
### Type of issue

Typo

### Description

The title says it all. "The use of the following data annotation attributes are used" should be changed to

"The following data annotation attributes are used"

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/options-validation-generator

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-validation-generator.md

### Document Version Independent Id

0775474e-7773-d061-ed21-0a360c8466b1

### Article author

@tarekgh

### Metadata

* ID: 533f4fc6-bb7c-874d-6639-ea215af95ed3 
* Service: **dotnet-fundamentals**

**Comment by tarekgh** [comment]
Thanks @petterh. Are you interested to submit a PR to fix it?

**Comment by tarekgh** [comment]
Should be already fixed by https://github.com/dotnet/docs/pull/41097
