### ISSUE TITLE
centos 7 尝试了下安装.net8 没有成功，删除对应的目录后，发现其他版本也不能运行了

### ISSUE THREAD

**Issue by ziyouren** [dotnet/docs#40579]
### Type of issue

Code doesn't work

### Description

centos 7 尝试了下安卓.net8 没有成功，删除对应的目录后，发现其他版本也不能运行了。
一直报错
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-scripted-manual#scripted-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md

### Document Version Independent Id

2be3647d-495b-c9f0-cf06-9a7bf687d3bb

### Article author

@adegeo

### Metadata

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
Sorry, .NET 8 is not supported on CentOS 7.
