### ISSUE TITLE
Contradictory explanation of how `global.json` is searched for

### ISSUE THREAD

**Issue by paulloz** [dotnet/docs#40585]
### Describe the issue or suggestion

Hello 👋

The documentation page [Select the .NET version to use](https://github.com/dotnet/docs/blob/main/docs/core/versions/selection.md) currently states the following about how `global.json` is searched for.

> The CLI searches upward from the project directory for the first global.json it finds.
> [...]
> The .NET CLI searches for a global.json file iteratively navigating the path upward from the current working directory.

Both are contradictory, the search begins in the current working directory (it is correctly explained in the page dedicated to [global.json](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-json.md)).

Should I simply PR a correction for this? I was about to, but reading the contribution guide, I seemed to understand that it'd be better to open an issue first. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab345482-5752-6845-feee-52f0f06c620c
* Version Independent ID: 3613d4c0-be8e-c5a4-42f4-bec78ab99c75
* Content: [Select which .NET version to use - .NET](https://learn.microsoft.com/en-us/dotnet/core/versions/selection)
* Content Source: [docs/core/versions/selection.md](https://github.com/dotnet/docs/blob/main/docs/core/versions/selection.md)
* Service: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment]
@paulloz Yes, feel free to open a PR. Thanks!
