### ISSUE TITLE
Signature of Main() changes through the tutorial

### ISSUE THREAD

**Issue by sabuncumurat** [dotnet/docs#40591]
### Type of issue

Other (describe below)

### Description

When the tutorial first starts, under section titled _Install the System.CommandLine package_ the signature of Main() is as follows:

`static async Task<int> Main(string[] args)`

Under the section titled _Add a subcommand and options_ the same method's signature changes to:

`static int Main(string[] args)`

Under the section _Add subcommands and custom validation_ the signature then changes back to:

`static async Task<int> Main(string[] args)`

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/commandline/get-started-tutorial.md

### Document Version Independent Id

fa160b1d-66ed-8c5d-37cd-b7e02443e9f1

### Article author

@tdykstra

### Metadata

* ID: 7705dc41-7297-0807-7e9c-2e6548c26b84 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 248378](https://dev.azure.com/msft-skilling/Content/_workitems/edit/248378)

**Comment by tdykstra** [comment]
Thanks for reporting that.
