### ISSUE TITLE
Keywords should not be translated.

### ISSUE THREAD

**Issue by flyer-me** [dotnet/docs#40590]
### Type of issue

Typo

### Description

The C# keyword "virtual" should not be translated to "虚拟".

This could be ambiguous.

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/sealed

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/sealed.md

### Document Version Independent Id

2cc0bd61-62b3-f41f-d6a8-16ffdc049238

### Article author

@BillWagner

### Metadata

* ID: ab10c9fd-cbf8-6889-eadc-34ce1999a592 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @flyer-me 

Can you add a couple details to help me get this fixed?  Are there instances of "virtual" that should be code-fenced to prevent any translation? Or are there instances that are translated incorrectly? Or is it a combination of both?

Thanks.

**Comment by flyer-me** [comment]
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed
![无标题](https://github.com/dotnet/docs/assets/61903267/86d1d38a-3673-42ce-a28a-bed12c0a1d93)

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/sealed,
The 'virtual' in this language version of the document is a reference and points to 'virutal', but it itself is translated as '虚拟'(zh-cn),maybe that's not a perfect fit?

**Comment by BartoszKlonowski** [comment]
I wonder if "virtual" should be treated here as a keyword.
Original text says that elements can be "*declared as virtual*", not "*declared with `virtual` modifier*".
So "virtual" here, even though linking to `virtual` keyword, is adjective, describing that something (type) *can be* virtual (when using the `virtual` modifier).

**Comment by flyer-me** [comment]
The "adjective" helps me understand.
Thanks a lot.
