### ISSUE TITLE
Small mistake in example configuration file on docs for "creating project templates"

### ISSUE THREAD

**Issue by viker81** [dotnet/docs#40594]
### Describe the issue or suggestion

Hi, 

doc reference: https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template
doc section: create-the-template-config

While executing a tutorial on [creating project templates](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template#create-the-template-config) we ran into the issue that the example was not working. It seems that in the `template.json` definition a small mistake has occurred. We noticed that the sourceName has been set to "ExampleTemplate.AsyncProject". This causes that the command `dotnet new consoleasync -n <somename>` will not cause to rename the project. 

To make this work the sourceName tag should be updated on the page from value
``` json
"sourceName":"ExampleTemplate.AsyncProject",
```
To value
``` json
"sourceName":"consoleasync",
```

---
[Associated WorkItem - 248169](https://dev.azure.com/msft-skilling/Content/_workitems/edit/248169)

**Comment by tdykstra** [comment]
@adegeo
