### ISSUE TITLE
No docs for `--artifacts-path`

### ISSUE THREAD

**Issue by stilettk** [dotnet/docs#40615]
### Type of issue

Missing information

### Description

There is no information about the `--artifacts-path` flag

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build?source=recommendations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-build.md

### Document Version Independent Id

5e495ddd-140e-de5c-a793-d4a9f88be51e

### Article author

@tdykstra

### Metadata

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 248376](https://dev.azure.com/msft-skilling/Content/_workitems/edit/248376)

**Comment by tdykstra** [comment]
@timdeschryver Do you want this one?

**Comment by stilettk** [comment]
FYI `dotnet publish` is affected too

**Comment by timdeschryver** [comment]
@tdykstra sounds good to me.
