### ISSUE TITLE
Is .NET Framework supported on Windows Server 2019?

### ISSUE THREAD

**Issue by hickford** [dotnet/docs#40657]
### Type of issue

Missing information

### Description

Windows Server 2019 is missing from list at https://learn.microsoft.com/en-us/dotnet/framework/install/  

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/index.md

### Document Version Independent Id

8a3205d1-e9f3-401a-8f4a-b202c2f093f6

### Article author

@adegeo

### Metadata

* ID: 0b087d84-e393-0a8c-bd09-8e96d1651338 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

---
[Associated WorkItem - 250227](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250227)

**Comment by adegeo** [comment]
Looks like 2019 was overlooked! Adding to the next sprint
