### ISSUE TITLE
Error Failed to download .NET 8.0: .NET Acquisition Failed: Installation failed: Error: Command failed:

### ISSUE THREAD

**Issue by gabraelel** [dotnet/docs#40666]
### Type of issue

Code doesn't work MacOS version 10.12.6

### Description

[Enter feedback here]
.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.3/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/gxxxxxx/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.4~x64" -Version 8.0.4 -Verbose -Runtime dotnet -Architecture x64
/bin/sh: /Users/gxxxxxxx/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.3/dist/install scripts/dotnet-install.sh: Permission denied

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/repair

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/repair.md

### Document Version Independent Id

f2e94c72-459b-c8f1-7eec-73e7d4197f4d

### Article author

@adegeo

### Metadata

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

**Comment by adegeo** [comment]
Hi, it looks like you're having a problem with a VSCode extension. You should contact the group responsible for that extension. Looking at the page: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime it seems there is a support repo you can go to:

![image](https://github.com/dotnet/docs/assets/67293991/d356d96c-2fa8-47fc-b830-26e275f982a6)
