### ISSUE TITLE
Search string "library" not sufficient to bring up .NET 8.0 library template. 

### ISSUE THREAD

**Issue by torresmrpk** [dotnet/docs#40716]
### Type of issue

Missing information

### Description

Minor correction, the article states, "On the Add a new project page, enter library in the search box.", which does not bring up the correct library template to use. You have to enter "class library" in the search box in order for the correct .NET 8.0 library to appear as an option in the list. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/library-with-visual-studio.md

### Document Version Independent Id

87d3afdd-d7d5-35d7-0718-63dadc4eab1d

### Article author

@tdykstra

### Metadata

* ID: 8df4bc4b-88e1-a629-fcbd-6808b4f7308c 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
I am unable to repro this problem. When I enter "library" in the search box, the list includes the "Class Library" template.
