### ISSUE TITLE
Local Window

### ISSUE THREAD

**Issue by langpslee** [dotnet/docs#40723]
### Type of issue

Typo

### Description

This document had  mentioned a "Local window". Please show us how to make it happen. All other explainations are well presented.
Thanks .

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio.md

### Document Version Independent Id

aeb94c3f-50e0-eb84-e469-f6eb778bad62

### Article author

@tdykstra

### Metadata

* ID: 5bc3290a-6511-5ef4-68bc-c2a8424dd582 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
It's the "Locals" window (with an "s"), and it's the window at the bottom left of the screenshot under the [Use the Immediate window](https://learn.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio?pivots=dotnet-8-0#use-the-immediate-window) section heading. If you look at the heading of that window you'll see the title "Locals". It shows the values of local variables.

**Comment by langpslee** [comment]
Thank for your help
I will be more careful with spelling. Regards Anja thanks

Sent from my iPhone

On 03.05.2024, at 02:48, Tom Dykstra ***@***.***> wrote:

﻿

Closed #40723<https://github.com/dotnet/docs/issues/40723> as completed.
