### ISSUE TITLE
Backslash escape sequence doesn't show properly

### ISSUE THREAD

**Issue by Seb-stian** [dotnet/docs#40742]
### Type of issue

Typo

### Description

Although the backslash escape sequence seems to be correct in the content source (`\\\\`), there is only a single backslash in the [page](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#string-escape-sequences)'s HTML (`\`).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#string-escape-sequences

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md

### Document Version Independent Id

3317fd4a-9cd3-57cd-66f7-abb271e302e8

### Article author

@BillWagner

### Metadata

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
ping @meganbradley Can we get this fixed? The source is correct.
