### ISSUE TITLE
Menus should only show top level options on mobile

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4075]
https://docs.microsoft.com/en-gb/dotnet/csharp/

On the above page - the sidebar menu on the desktop site is hierarchical. 

On mobile however, all menu items are listed in a single list. That's hundreds of items on this page - which makes the menu pretty difficult to use. It would be great if just the current hierarchy level was shown on mobile.

This problem was seen on Chrome 63.0.3239.73 on iPhone, but I can reproduce in [Chrome's device simulator](https://developers.google.com/web/tools/chrome-devtools/device-mode/).

**Comment by mairaw** [comment]
Thanks for the feedback @ChrisMaddock. @adkinn @DuncanmaMSFT @eisenbergeffect any input into this issue?

**Comment by BillWagner** [comment]
This also affects how we handle the sub-TOCs. We discussed this briefly last week with @dend in our Friday meeting. There's likely some work on both the content and site engineering side here.

**Comment by EisenbergEffect** [comment]
@ChrisMaddock Thanks for the feedback!

The good news is that we already have a complete revamp of the ToC designed for mobile devices. It needs to go through a final design review still, but it's nearly ready for implementation.

@mairaw I've got this work as part of our FY18Q3 priorities. I'm not sure of the actual timeline just yet though. It's fighting against some other serious hi-pri work that's recently come up. Watch my weekly status update emails for news on progress.

**Comment by mairaw** [comment]
Cool! Thanks for the update @EisenbergEffect!

**Comment by mairaw** [comment]
Moved issue to https://github.com/MicrosoftDocs/feedback/issues/219
