### ISSUE TITLE
HII

### ISSUE THREAD

**Issue by HOSEINRJ** [dotnet/docs#40759]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/troubleshoot-blocked-installations-and-uninstallations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/troubleshoot-blocked-installations-and-uninstallations.md

### Document Version Independent Id

a171c012-8373-3d77-e4f2-7ea4f4662d7f

### Article author

@adegeo

### Metadata

* ID: 5d4a8c65-fe3a-8656-b7a1-641a2ae4cb30 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

**Comment by alandryz83** [comment]
Sent from my iPhoneOn May 4, 2024, at 4:53 PM, dotnet bot ***@***.***> wrote:﻿
Closed #40759 as completed.
