### ISSUE TITLE
The code example for foreach does not work

### ISSUE THREAD

**Issue by MarekDomas** [dotnet/docs#40755]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
The Code example of foreach statement with list of fibonaci numbers does not work.
The list need to be initialized differently : 
Instead of: `List<int> fibNumbers = [0, 1, 1, 2, 3, 5, 8, 13];`
It should be: `List<int> fibNumbers = new List<int> {0, 1, 1, 2, 3, 5, 8, 13};`

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements#code-try-6

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/iteration-statements.md

### Document Version Independent Id

8b6cb66c-8bef-fed0-1677-acee6bd3e052

### Article author

@BillWagner

### Metadata

* ID: 23685290-d092-48ee-f7d9-e2c2bdc86a18 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 252999](https://dev.azure.com/msft-skilling/Content/_workitems/edit/252999)

**Comment by BillWagner** [comment]
Hi @MarekDomas 

The code is correct. It's using the new C# 12 feature [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions).

I'll close this as by design.

**Comment by MarekDomas** [comment]
Yes, i know about this feature, but the built in code editor, does not compile the code.

**Comment by BillWagner** [comment]
Reopening this one. We should disable collection expressions here until Try.NET gets updated.
