### ISSUE TITLE
Unnecessary repetition of array items in example code

### ISSUE THREAD

**Issue by n7800** [dotnet/docs#40758]
### Type of issue

Typo

### Description

In the example code, the second and last items in the array are repeated (`\\127.0.0.1\c$\temp\test-file.txt`):
```csharp
string[] filenames = {
    @"c:\temp\test-file.txt",
    @"\\127.0.0.1\c$\temp\test-file.txt",
    @"\\LOCALHOST\c$\temp\test-file.txt",
    @"\\.\c:\temp\test-file.txt",
    @"\\?\c:\temp\test-file.txt",
    @"\\.\UNC\LOCALHOST\c$\temp\test-file.txt",
    @"\\127.0.0.1\c$\temp\test-file.txt" };
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/io/file-path-formats.md

### Document Version Independent Id

716a28dc-360e-2964-47f5-0ff18bb00b1c

### Article author

@adegeo

### Metadata

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Thank you for reporting this issue!
