### ISSUE TITLE
Order of execution needs to be specified

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40768]
### Type of issue

Missing information

### Description

This article should specify that object initializers are called *after* the constructors have run. That's true for required, init-only, properties, or read write properties.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer.md

### Document Version Independent Id

0ffb923c-a49c-ed59-abb6-9618aea5df61

### Article author

@BillWagner

### Metadata

* ID: d5121576-832f-dba0-f489-ba17c1891161 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by gabbersepp** [comment]
But isn't this already written in the article?
![image](https://github.com/dotnet/docs/assets/3234900/783f3169-69fa-4d3a-bac2-644ce9d07c72)

**Comment by BillWagner** [comment]
Hi @gabbersepp 

Yes, that's in place. It could maybe use a bit of emphasis now that `required` and `init` properties are part of the language.

**Comment by gabbersepp** [comment]
ok I understand @BillWagner 
I am wondering if creating another example which shows the order of execution by using some Console.WriteLine is sufficient?

**Comment by BillWagner** [comment]
@gabbersepp 

> I am wondering if creating another example which shows the order of execution by using some Console.WriteLine is sufficient?

That would be perfect.

**Comment by gabbersepp** [comment]
@BillWagner I added an example.

But I think that the documentation is not correct at this point:

![image](https://github.com/dotnet/docs/assets/3234900/fe1401bb-19b4-4aa8-8abf-55f79778edee)

The parameterless constructor is not required if for object creation a constructor value is passed. If so, the parameterless constructor can indeed be private:

![image](https://github.com/dotnet/docs/assets/3234900/3a12f2c7-547e-44ff-963f-db707340238d)

Should this be cleared out in the documentation or is that left as it is?
