### ISSUE TITLE
A better example for compile-time options validation source generation would be nice.

### ISSUE THREAD

**Issue by mrudat** [dotnet/docs#40760]
### Type of issue

Other (describe below)

### Description

The example emits warnings if you enable IsAotCompatible; given that part of the reason for wanting to allow compile-time source generation is to work towards enabling AOT compilation, it would be helpful if the example shows the Right Way to configure things to that end.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/options-validation-generator

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/options-validation-generator.md

### Document Version Independent Id

0775474e-7773-d061-ed21-0a360c8466b1

### Article author

@tarekgh

### Metadata

* ID: 533f4fc6-bb7c-874d-6639-ea215af95ed3 
* Service: **dotnet-fundamentals**

**Comment by mrudat** [comment]
```csharp
builder.Services
    .AddOptions<SettingsOptions>()
     // v-- IL2025 and IL3050 from this call to Bind when IsAotCompatible is enabled.
    .Bind(builder.Configuration.GetSection(SettingsOptions.ConfigurationSectionName)); 
```

**Comment by tarekgh** [comment]
The example is fine. We may need to add a note there, if anyone enabling AOT build will need to use the configuration source generator buy adding the following property to the csproj.

```Xml
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>	  
```

**Comment by tarekgh** [comment]
@mrudat are you interested to submit a PR to add the note to the doc?

**Comment by tarekgh** [comment]
I have submitted the PR https://github.com/dotnet/docs/pull/40770.
