### ISSUE TITLE
C# 中的 LINQ 查询文档中的代码有误

### ISSUE THREAD

**Issue by 1732358571** [dotnet/docs#40765]
### Type of issue

Code doesn't work

### Description

您好，我最近正在学习C#，刚刚在C#中文文档的LINQ查询中发现了一处代码的赋值好像有误。在附件中我会提供截图，截图中有标记。在此祝您生活愉快。
![Snipaste_2024-05-06_15-26-07](https://github.com/dotnet/docs/assets/43214036/cb4864f0-af62-4f6f-a59b-04dda26c48d5)
![Snipaste_2024-05-06_15-28-35](https://github.com/dotnet/docs/assets/43214036/7b1be76c-5382-4878-95c9-16693e01f3e8)

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/linq/get-started/introduction-to-linq-queries

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/get-started/introduction-to-linq-queries.md

### Document Version Independent Id

8621bb8c-76a9-9537-845f-f3947bf45a5f

### Article author

@BillWagner

**Comment by gewarren** [comment]
These examples use [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions), which are new in .NET 8.

**Comment by BillWagner** [comment]
Hi @1732358571 

As @gewarren points out, this examples uses a new C# 12 feature. It shipped with .NET 8. It's valid C# with the current version. I'll close this.
