### ISSUE TITLE
SystemColors is also affected

### ISSUE THREAD

**Issue by Rubidium37** [dotnet/docs#40766]
### Type of issue

Missing information

### Description

Landed here after an error encountered designing a Windows Forms `Form`.

Its was working properly up to VS 2019 and became broken with VS 2022.
The project targets NET FX 4.8 and does not include `System.Drawing.Common`, at least, not explicitely.

The source of the issue is a child component that exposes properties of type `Color`.
Their default values are fields of `SystemColors`, and VS blame both a `static readonly` field and a `DefaultValue` attribute that are exposing fields of such class.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md

### Document Version Independent Id

c3b792d7-50ab-ff45-09bf-37a7550f0e09

### Article author

@gewarren

### Metadata

* ID: 3fa60e1c-9c9a-ce16-2e47-c41857fc8c48 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Hi @Rubidium37

This page is detailing stuff for .NET 6+ projects that reference the library but are set to compile cross-platform, and not about .NET Framework (which isn't cross-platform). It sounds like you may have a problem with the designer serializer. You should use the **Help** > **Send Feedback** > **Report a problem...** menu option in Visual Studio. That will get you routed to the team responsible for VS and WinForms to try and get the issue resolved.

I'm going to close this issue as I don't believe there is anything to do here.
