### ISSUE TITLE
Confusing C# 13 example

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#40796]
### Describe the issue or suggestion

I find the example for implicit index example to be confusing: https://github.com/dotnet/docs/blob/6ae8f6122a9cc8c23d1e4e4d208e06d023123961/docs/csharp/whats-new/csharp-13.md#L47.

The primary issue is that I have to guess what `v` and `S` are. I realize that they are not important for the example, however, they are the first bits of code that I have to look at and parse. Also, is this code that one would ever write? Maybe this feature is just too niche to get this much fanfare?

I like these pattern matching examples: https://learn.microsoft.com/dotnet/csharp/fundamentals/functional/pattern-matching.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aac84693-3ecb-f53b-3841-eae6c5aeb653
* Version Independent ID: 51d7b1c3-f822-0c65-da31-47a3fcd22dd3
* Content: [What's new in C# 13 - C# Guide - C#](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13)
* Content Source: [docs/csharp/whats-new/csharp-13.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-13.md)
* Service: **dotnet-csharp**
* Sub-service: **whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 256379](https://dev.azure.com/msft-skilling/Content/_workitems/edit/256379)

**Comment by BillWagner** [comment]
I've got a PR that updates this file now. I'll update the example.
