### ISSUE TITLE
Note has mistake

### ISSUE THREAD

**Issue by PlanetEarthSoftware** [dotnet/docs#40837]
### Type of issue

Missing information

### Description

The Note below the escape sequences is wrong:

> For example, the verbatim string @"C:\files.txt" will appear in the watch window as "C:\files.txt".

The watch window actually shows "C:\\\\files.txt" with **two backslashes**. Shouldn't be putting the newbies wrong :o).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/strings/index.md

### Document Version Independent Id

3317fd4a-9cd3-57cd-66f7-abb271e302e8

### Article author

@BillWagner

### Metadata

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

---
[Associated WorkItem - 253573](https://dev.azure.com/msft-skilling/Content/_workitems/edit/253573)

**Comment by BillWagner** [comment]
Thanks for pointing this out @PlanetEarthSoftware 

I've opened a PR to address the issue.
