### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by OsvaldoRino** [dotnet/docs#40838]
### Type of issue

Typo

### Description

[Escribir comentarios aquí]

### Page URL

https://learn.microsoft.com/es-mx/dotnet/csharp/tour-of-csharp/tutorials/hello-world

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/tutorials/hello-world.yml

### Document Version Independent Id

293260e2-f444-537b-0ba7-14d1fb6ebcf2

### Article author

@BillWagner

### Metadata

* ID: 8053bb96-cc40-8369-c07f-f9fd14060c1e 
* Service: **dotnet-csharp**

**Comment by BillWagner** [comment]
closing as opened by mistake.
