### ISSUE TITLE
MICROSOFT VUSUAL

### ISSUE THREAD

**Issue by Cha3rawi3** [dotnet/docs#40842]
### Type of issue

Typo

### Description

[Tapez vos commentaires ici]

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/csharp/misc/cs5001?f1url=%3FappId%3DDev17IDEF1%26l%3DFR-FR%26k%3Dk(CS5001)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.2)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs5001.md

### Document Version Independent Id

a1404161-c48b-564b-03ea-d4340fe28c53

### Article author

@BillWagner

### Metadata

* ID: dcc1ba33-60dd-1e44-2498-eb76f0d964c1 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
closing as opened by mistake
