### ISSUE TITLE
This page should have a quick example of each form of `using`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#40868]
### Type of issue

Typo

### Description

Beginners who land on this page from F1 help may not know which form of `using` they meant. A quick example of each would be helpful.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using.md

### Document Version Independent Id

2ba9241c-0836-d05e-5ba1-ebc5498d2009

### Article author

@BillWagner

### Metadata

* ID: a731ad7b-0655-4bb3-2478-0cbb4d063f02 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by bigboybamo** [comment]
@BillWagner I'd like to work this. Should the examples be their own file? or I should just create them within the doc itself?

**Comment by BillWagner** [comment]
Hi @bigboybamo 

Thanks!  I'll assign this to you and watch for a PR. In general, we try to incorporate all code from external `*.cs` files. that way, we ensure that no small syntax errors sneak in later. Is that what you meant by "in their own file?" if so, yes.

Thanks again.

**Comment by bigboybamo** [comment]
Hi @BillWagner  I opened a Pull request #41020

**Comment by BartoszKlonowski** [comment]
@BillWagner Just kind FYI: this issue can be closed, as the closing PR was not linked properly (description says "fixes for #" instead of "fixes #").
