### ISSUE TITLE
"Spread operator" instead of "Spread element"

### ISSUE THREAD

**Issue by begerard** [dotnet/docs#40889]
### Type of issue

Typo

### Description

Following the recommended naming of this [blog post](https://devblogs.microsoft.com/dotnet/refactor-your-code-with-collection-expressions/#spread-%e2%9c%a8), the mention of **spread operator** across the _Collection expressions_ section should be rename in **spread element**.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-12.md

### Document Version Independent Id

587ed47f-f532-e018-9b0d-6ee76afd20e4

### Article author

@BillWagner

### Metadata

* ID: c36588d0-6bdf-1740-220c-10b20bb88730 
* Service: **dotnet-csharp**
* Sub-service: **whats-new**

**Comment by BillWagner** [comment]
closing, as I fixed this yesterday in #40877
