### ISSUE TITLE
[AI docs] Update wording in .NET AI Get Started Page

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#40886]
### Describe the issue or suggestion

https://review.learn.microsoft.com/en-us/dotnet/ai/get-started/dotnet-ai-overview?branch=new-conceptual-ai

The intro paragraph reads as:

> With .NET, you can use artificial intelligence (AI) to mimic human behavior and accomplish complex tasks in your applications—all using the tools, platforms, and services that are familiar to you.

Suggested edit:

> With .NET, you can use artificial intelligence (AI) to automate and accomplish complex tasks in your applications—all using the tools, platforms, and services that are familiar to you.

**Comment by alexwolfmsft** [comment]
Fixed in attached PR
