### ISSUE TITLE
Description for MSTEST0003 misses the word "not"

### ISSUE THREAD

**Issue by schibu007** [dotnet/docs#40955]
### Type of issue

Typo

### Description

Current text:
_"it should be a special method (finalizer, operator...)"_
Correct text:
_"it should **not** be a special method (finalizer, operator...)"_

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/testing/mstest-analyzers/usage-rules

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/testing/mstest-analyzers/usage-rules.md

### Document Version Independent Id

35667180-9786-e560-d03e-ceb5b9b5b579

### Article author

@Evangelink

### Metadata

* ID: ee04b7f7-f320-45fe-7564-2b66cdffa03b 
* Service: **dotnet-fundamentals**

**Comment by Evangelink** [comment]
Hi @schibu007,

Thank you for the bug report, I'll submit a fix tomorrow.
