### ISSUE TITLE
donnet 

### ISSUE THREAD

**Issue by giangkafood1** [dotnet/docs#40985]
### Type of issue

Typo

### Description

![image](https://github.com/dotnet/docs/assets/152671238/1150f7df-0acd-4c60-9ff3-c61d667ddf0e)

Details

.NET Framework 4.8 or a later update is already installed on this computer.
[](url)
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/introduction

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/introduction.md

### Document Version Independent Id

9d3015b4-cba1-0956-9ec7-4154dbb74d93

### Article author

@gewarren

### Metadata

* ID: 3ad87897-30cc-e639-b91a-b3800269f7fe 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@giangkafood1 Where is the typo exactly?
