### ISSUE TITLE
interpolationExpression definition - Missing definite article - "the"

### ISSUE THREAD

**Issue by kengorman** [dotnet/docs#41008]
### Type of issue

Other (describe below)

### Description

The second sentence of the interpolationExpression definition should, as it is currently phrased, contain the definite article "the" before the word **String**.

Currently: **String representation of null is String.Empty.**

One option: **The representation of null in the String class is String.Empty.**
Another option, but not as easy to read, using he singular possessive form of the noun class is: **The String class's representation of null is String.Empty.**

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md

### Document Version Independent Id

0410420b-3b12-6d96-40cf-56f22ac19a1d

### Article author

@pkulikov

### Metadata

* ID: d0665571-35b7-0841-5719-b69456b35cfb 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks for pointing that out @kengorman 

I'd probably re-write that sentence as follows:

"When the expression is `null`, the output is the empty string.

**Comment by kengorman** [comment]
Thanks Bill, I like your suggestion best.
