### ISSUE TITLE
In the section 'Immutability,' the Chinese translation of the chapter title 'Introduction to record types in C#' is incorrect.

### ISSUE THREAD

**Issue by yangzhanxi** [dotnet/docs#41011]
### Type of issue

Other (describe below)

### Description

For the sentence:
或者需要哈希代码在哈希表中国能保持不变

It should be corrected to:
或者需要哈希代码在哈希表中能保持不变

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/fundamentals/types/records

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/records.md

### Document Version Independent Id

8991024e-b64a-bc2a-9612-5649d89bda2b

### Article author

@BillWagner

### Metadata

* ID: 64271119-b153-2e7c-8f43-1fd1d4c1dbcb 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Thanks for noting this @yangzhanxi 

I filed an internal issue for our localization team to address.

Closing this as transferred to the internal system for localization issues.
