### ISSUE TITLE
dotnetSDK

### ISSUE THREAD

**Issue by JOTHEPASH** [dotnet/docs#41014]
### Type of issue

Thank you

### Description

Optimize the shadowsocks server on Linux

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?tabs=dotnet8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-install.md

### Document Version Independent Id

e7286112-86cf-8d6a-655b-ee851f396d15

### Article author

@adegeo

### Metadata

* ID: 72799d86-e122-1706-18a2-d0bfde699bfc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
Hello, this looks like product feedback. Please create an issue in the product repository: https://github.com/dotnet/sdk
