### ISSUE TITLE
Awkward translation of "Source Generators" page title to pt-BR.

### ISSUE THREAD

**Issue by matheusanmo** [dotnet/docs#41029]
### Type of issue

Other (describe below)

### Description

The [Source Generators](https://learn.microsoft.com/en-au/dotnet/csharp/roslyn-sdk/source-generators-overview) has a very awkward translation to (at least Brazilian) Portuguese.
In Portuguese _Source Code_ is translated as _Código-fonte_. Like in English, we shorten it by dropping a word and calling it either _Código_ or _Fonte_. Translating _Source Generators_ to _Geradores de Origem_ is very awkward because:
- There's no "_origem_" in "_Código-fonte_".
- _Origem_ is more akin to _origin_ then to _source_.
- In Brazilian technical literature _Código-fonte_ is shortened to either _código_ or _fonte_.
- If I would translate _Geradores de origem_ to English without context I'd go for _Origin Generators_. 

Here's some sources to back me up:
- The Wiktionary page for [_Origem_](https://en.wiktionary.org/wiki/origem) has a single translation to english: _origin_.
- The Wikipedia page for [_Código-fonte_](https://pt.wikipedia.org/wiki/C%C3%B3digo-fonte) says that _Código-fonte_ goes also by either _Código_ or _Fonte_.
- All technical books in Portuguese (that I've seen of course) translate _Source Code_ as per the Wikipedia page above.
- At the bottom of the pt-BR page for [_Source Generators_](https://learn.microsoft.com/pt-br/dotnet/csharp/roslyn-sdk/source-generators-overview) itself, the "Collaborate with us on GitHub" box has the word _Source_ translated to _Fonte_.

I believe every mention of _(Source|Code) Generators_ should be translated as _Geradores de (Código|Fonte)_.

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/roslyn-sdk/source-generators-overview

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md

### Document Version Independent Id

f1ed9873-3e29-b4bd-2dbb-44dd9a05d790

### Article author

@BillWagner

### Metadata

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682 
* Service: **dotnet-csharp**
* Sub-service: **roslyn-sdk**

**Comment by BillWagner** [comment]
Thanks for reporting this @matheusanmo 

I've opened an internal ticket for our localization team to address this. 

I'll close this issue, as it's being tracked internally.
