### ISSUE TITLE
Ubuntu 24.04 installation instructions have duplicated instructions for dependencies

### ISSUE THREAD

**Issue by klemmchr** [dotnet/docs#41036]
### Type of issue

Other (describe below)

### Description

For some reason this block here is duplicated, only for 24.04. Other versions are fine.
![image](https://github.com/dotnet/docs/assets/6552521/4c548cc4-7150-41fe-bee0-c170d5b8c91c)

I tried to find the issue and open a PR myself but the source looks fine to me.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?tabs=dotnet8&pivots=os-linux-ubuntu-2404

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-install.md

### Document Version Independent Id

e7286112-86cf-8d6a-655b-ee851f396d15

### Article author

@adegeo

### Metadata

* ID: 72799d86-e122-1706-18a2-d0bfde699bfc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 259529](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259529)

**Comment by adegeo** [comment]
Thanks, I'll take a look!
