### ISSUE TITLE
DFFX

### ISSUE THREAD

**Issue by huguesdev-HP** [dotnet/docs#41085]
### Type of issue

Typo

### Description

[Tapez vos commentaires ici]

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/using

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using.md

### Document Version Independent Id

2ba9241c-0836-d05e-5ba1-ebc5498d2009

### Article author

@BillWagner

### Metadata

* ID: a731ad7b-0655-4bb3-2478-0cbb4d063f02 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
closing as this was likely opened by mistake.
