### ISSUE TITLE
Why method assigns the parameter to refer to a different object aren't visible from the caller, when pass a value type by reference?

### ISSUE THREAD

**Issue by Unarimit** [dotnet/docs#41087]
### Type of issue

Typo

### Description

Does it mean such method as `void foo(ref int num)` is not reasonable? I can not got it.

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/method-parameters

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/method-parameters.md

### Document Version Independent Id

7241f712-8d73-b5e0-37c0-5f05c92412c6

### Article author

@BillWagner

### Metadata

* ID: b8dd92fe-5053-1bc6-1c8f-cf9f88635cb5 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 335968](https://dev.azure.com/msft-skilling/Content/_workitems/edit/335968)

**Comment by Unarimit** [comment]
this issue appear in this subheading https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#combinations-of-parameter-type-and-argument-mode

**Comment by BillWagner** [comment]
I'm moving this out to November.  As I tried to rewrite the bulleted lists, I think images will express these differences much better. I'm going to make some sketches and work with our art department and submit the PR next month.
