### ISSUE TITLE
Mistake In Regex Source Generated Files Example

### ISSUE THREAD

**Issue by RyanThomas73** [dotnet/docs#41176]
### Type of issue

Typo

### Description

There is a mistake in the description under the following section:
https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-source-generators.md#inside-the-source-generated-files

The last sentence of the description paragraph states: `Consider the source generator output for one of the primary functions from the (a|bc)d expression:`. But the `(a|bc)d` portion is incorrect and should be `abc|def` to match what the example source code below has been generated for.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/regular-expression-source-generators.md

### Document Version Independent Id

76b98e7b-6acc-cb43-da8e-475a8b4ed5a1

### Article author

@IEvangelist

### Metadata

* ID: 56298202-fa5d-363d-3c52-adbf5256b184 
* Service: **dotnet-fundamentals**

**Comment by IEvangelist** [comment]
Hi @RyanThomas73 - I marked this issue as `help wanted`. Is this something you'd be interested in attempting to fix?

**Comment by RyanThomas73** [comment]
@IEvangelist Sure. Just put up a quick PR for the fix.
