### ISSUE TITLE
c#

### ISSUE THREAD

**Issue by kakami12** [dotnet/docs#41185]
### Type of issue

Typo

### Description

[Insira comentários aqui]

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/fundamentals/program-structure/top-level-statements

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/program-structure/top-level-statements.md

### Document Version Independent Id

27a40713-4a2d-ca9f-8e9e-6f568ad8acdb

### Article author

@BillWagner

### Metadata

* ID: 843bd4d7-cbb2-fca7-d4d2-f3ef027c167e 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
closing as likely opened by mistake
