### ISSUE TITLE
Not clear usage recommendation of ArrayList

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4121]
At the **Remarks** section of the [ArrayList](https://docs.microsoft.com/en-us/dotnet/api/system.collections.arraylist?view=netcore-2.0) it is recommended 
>For a heterogeneous collection of objects, use the `List<Object>` (in C#) or `List(Of Object)` (in Visual Basic) type.

What do we mean here: 
- generic `List<T>` with `Object` type as parameter OR
- there is a mistake in recommendation and `ArrayList` should be recommended?

If the former takes place, we might recommend not to use `ArrayList` at all.

**Comment by svick** [comment]
> we might recommend not to use ArrayList at all.

That's how I understand the recommendation, that `ArrayList` should not be used. What makes you think the documentation is suggestion you should sometimes use `ArrayList`?

**Comment by pkulikov** [comment]
@svick the same **Remarks** section then says
>See the **Performance Considerations** section in the [List<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-2.0) reference topic for a discussion of the relative performance of these classes.

Then, the first paragraph of that section is
>**Performance Considerations**
In deciding whether to use the `List<T>` or `ArrayList` class, both of which have similar functionality, remember that the `List<T>` class performs better in most cases and is type safe. If a reference type is used for type `T` of the `List<T>` class, the behavior of the two classes is identical. However, if a value type is used for type `T`, you need to consider implementation and boxing issues.

That makes me think that *these classes* in the phrase
>...discussion of the relative performance of these classes.

refers to `List<T>` and `ArrayList`.

What might be done is
- directly recommend to use `List<T>` in the `ArrayList` reference topic because of the better or identical performance and type safety
- remove the first paragraph at the **Performance Considerations** section in the `List<T>` reference topic or move it lower. I would say that the third paragraph is the most important in that section.

**Comment by pjanotti** [comment]
Yes, if possible some kind of warning box on the top. It could link to the section with the detailed explanation but it will be nice to have it on the type and all its members.

**Comment by mairaw** [comment]
@pjanotti and do you think we should do this for all types listed in https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md?

**Comment by pjanotti** [comment]
Yes, @mairaw that will be great.

**Comment by BillWagner** [comment]
I'm closing this based on dotnet/dotnet-api-docs#672
