### ISSUE TITLE
Not expected references to .NET framework source code

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4122]
If we look, for example, at the **Remarks** section of the [generic List class](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netcore-2.0), we notice the following note:
>To view the .NET Framework source code for this type, see ...

However, please note that above-mentioned link is for .NET Core (`?view=netcore-2.0` in the URL). Thus, it's strange to see the link to the .NET framework source code instead of the link to .NET Core source code.

Is it possible to show different links based on view requested or rather all the links to .NET framework source code should be removed from API documentation (then there should be the doc section that contains the links to all possible source codes)?

@mairaw what do you think?

**Comment by mairaw** [comment]
Hi @pkulikov, thanks for your feedback. I thought we had removed those from the docs but it seems we missed them in the remarks. I'll remove them from everywhere.

We still don't have the ability to show different content based on the product, but we're working on that feature.

Our team is also working on a feature to point you to the source code from the API reference docs.

@dend @eisenbergeffect can you comment on the status of those feature requests? Thanks!

**Comment by EisenbergEffect** [comment]
The feature to link from the code block to the GitHub source is currently in process. We have a design but need to implement some things on the back-end that allow us to reliably make the link (and not accidentally product 404s for customers).

**Comment by pkulikov** [comment]
@mairaw thank you for such a complete answer. 

If those notes should be removed, I can do that as well. Is it fine?
So far, I've found [these files](https://github.com/dotnet/docs/search?utf8=%E2%9C%93&q=%22To+view+the+.NET+Framework+source+code+for+this+type%22&type=) to clean.

**Comment by mairaw** [comment]
Of course @pkulikov! Your contribution is super welcome. I appreciate it.
