### ISSUE TITLE
Module csharp-basic-formatting Try.NET functionality not working as expected

### ISSUE THREAD

**Issue by CamSoper** [dotnet/docs#41272]
Problem with this step: https://learn.microsoft.com/en-us/training/modules/csharp-basic-formatting/2-exercise-character-escape-sequences

From https://www.reddit.com/r/csharp/comments/1d5cuqw/comment/l6kuoeq/

> Hi Guys,
> 
> So I'm using Microsoft Learn and I'm on the "Formating output character using escape sequences". The excercise is telling me to type:
> 
> Console.WriteLine("Generating invoices for customer \"Contoso Corp\" ...\n");
> Console.WriteLine("Invoice: 1021\t\tComplete!");
> Console.WriteLine("Invoice: 1022\t\tComplete!");
> Console.WriteLine("\nOutput Directory:\t");
> 
> I typed:
> 
> ```
> Console.WriteLine("Generating invoices for customer \"Contoso Corp\" ...\n");
> Console.WriteLine("Invoice: 1021\t\tComplete!");
> Console.WriteLine("Invoice: 1022\t\tComplete!");
> Console.WriteLine("\nOutput Directory:\t");
> ```
>
> But it's just saying "No Output" as the result, instead of what it's supposed to say. I can't find the error.

Repro:

1. [Go to this step](https://learn.microsoft.com/en-us/training/modules/csharp-basic-formatting/2-exercise-character-escape-sequences) of the csharp-basic-formatting module
1. Jump down to the Format output using character escape sequences section
1. Copy the code block from step 2 into the editor (the part that writes "Generating invoices...")
1. Run the code. Observe the no output response.

Per Reddit thread, results in a HTTP 403 from the server

---
[Associated WorkItem - 261104](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261104)

**Comment by jkrejcha** [comment]
In particular, it looks like the sequence `..` causes the error regularly.

A simple test case
```cs
Console.WriteLine("..");
```

results in `No output`. Even just having it in a comment like so
```cs
// ..
Console.WriteLine("Hello world!");
```

leads to the same thing.

**Comment by CamSoper** [comment]
@jkrejcha Thanks for the additional info! That explains a few things. 

Internally in Microsoft we're in the process of hardening a lot of attack surfaces. It seems to me that there's a rule somewhere getting hung up on the `..` because it looks like someone's trying to do a directory traversal attack of some kind.

I'm in the process of getting the right eyes on this. Stay tuned! 🙂

**Comment by CamSoper** [comment]
The content has been modified and platform team has been notified about the issue. Since it's out of my hands now and in a private repo, I'm closing this issue.
