### ISSUE TITLE
misleading remarks for IEquatable<T>.Equals

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4129]
Under "Remarks" it says:

> When the Equals method is called and the other parameter represents a strongly-typed object of type T.

I think this was supposed to say:

> When the Equals method is called the other parameter represents a strongly-typed object of type T.

This may need more updates as well.

**Comment by rpetrusha** [comment]
@BillWagner, the intent of the bulleted item is to distinguish when IEquatable.Equals(T) is called, as opposed to Object.Equals(Object). So I think that the text is correct.

**Comment by rpetrusha** [comment]
This should have been closed when #4229 was merged. Closing....
