### ISSUE TITLE
Language version dropdown greyed out

### ISSUE THREAD

**Issue by Moszir** [dotnet/docs#41296]
### Type of issue

Missing information

### Description

The dropdown is greyed out.
Under the dropdown there is a link with the text "Why can't I select a different C# version?".
That link brings me to this page.
The page does not contain the answer to the above question.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md

### Document Version Independent Id

3f01c378-22e4-197c-a862-ab4a924506c7

### Article author

@BillWagner

### Metadata

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 350750](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350750)

**Comment by BillWagner** [comment]
Thanks @Moszir 

This is a bit misleading. I've added this issue to our backlog to address when we next update this article.
