### ISSUE TITLE
Omission in Top Level Statements demo documentation page

### ISSUE THREAD

**Issue by tlKMC** [dotnet/docs#41313]
### Type of issue

Missing information

### Description

https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/top-level-statements

This page has a very nice demo of using the Top Level Statements feature with C#.

1. Under the "Refactoring the code for the future" Section, there is a description of how to "clean the animation code". It use a for loop with an "animations" string which is not defined in this document:
foreach (string s in animations)
{
    Console.Write(s);
    await Task.Delay(50);
    Console.Write("\b\b\b");
}

 It probably should be something like:

string[] animations =
[
    "| -",
    "\b\b\b",
    "/ \\",
    "\b\b\b",
    "- |",
    "\b\b\b",
    "\\ /",
    "\b\b\b",
];

2. It may also be desirable to show how the completed function looks after making this substitution.

Thank you.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/top-level-statements

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tutorials/top-level-statements.md

### Document Version Independent Id

04ba77b9-7341-d664-161e-c48453248815

### Article author

@BillWagner

### Metadata

* ID: 08d9c309-83b7-2985-c760-374e2dfb3847 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Hi @tlKMC 

That's a good suggestion. I'll fix this when we next update this article. 

I've also added the "help wanted" label if anyone wants to submit a PR before we get to it.

**Comment by BartoszKlonowski** [comment]
I'll take that.

**Comment by BillWagner** [comment]
Thanks @BartoszKlonowski 

I've assigned it to you.
