### ISSUE TITLE
a

### ISSUE THREAD

**Issue by andrea091** [dotnet/docs#41311]
### Type of issue

Missing information

### Description

![Screenshot 2024-06-04 110334](https://github.com/dotnet/docs/assets/123313232/92069725-6c58-4b21-9629-87f63ce42f9f)

[Immetti qui i commenti]

### Page URL

https://learn.microsoft.com/it-it/dotnet/csharp/whats-new/tutorials/interpolated-string-handler

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/interpolated-string-handler.md

### Document Version Independent Id

e80a06db-bfbc-29f1-1cca-248460e523d3

### Article author

@BillWagner

### Metadata

* ID: 99599c47-14ba-6e35-9b63-daa928f764bb 
* Service: **dotnet-csharp**
* Sub-service: **whats-new**

**Comment by BillWagner** [comment]
Hi @andrea091 

Can you add more details on what we need to address on this page? Is the translation incorrect? 

Thank you.

**Comment by andrea091** [comment]
Hello,
I really don't remember where it was but there was this problem of
transaltion.


Il Gio 6 Giu 2024, 3:39 PM Bill Wagner ***@***.***> ha
scritto:

**Comment by BillWagner** [comment]
Moved to the internal system used by our localization team.

Closing as no work is needed on the original source.
