### ISSUE TITLE
Dead link on interop page

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/docs#4131]
First link here: (Interoperating with Unmanaged Code How-to Topics)
https://docs.microsoft.com/en-us/dotnet/framework/interop/index#comments-container

Is it possible to install a system, which reports, when somebody removes a page?
Why is it even possible, that a link get removed from somewhere without any checking if that one got linked somewhere else?

Thanks a lot

**Comment by pkulikov** [comment]
Apparently all links to msdn.microsoft.com are broken on the mentioned page. 
Those are:
- Interoperating with Unmanaged Code How-to Topics
- Design Considerations for Interoperation
- Interoperating Using Generic Types
- Advanced COM Interoperability

**Comment by mairaw** [comment]
I'll fix this page @ShalokShalom. Thanks for reporting. The content got restructured at some point but that page wasn't updated (see a previous version [here](https://msdn.microsoft.com/en-us/library/ccb68ce7-b0e9-4ffb-839d-03b1cd2c1258(vs.100))).

The In this section is supposed to only list what's in the TOC, so most of them should just be removed.

**Comment by ShalokShalom** [comment]
Thanks a lot 😄

**Comment by mairaw** [comment]
You're welcome!
