### ISSUE TITLE
Remove note that the dotnet-uninstall tool does not support .NET 8+.

### ISSUE THREAD

**Issue by jongalloway** [dotnet/docs#41331]
### Type of issue

Outdated article

### Description

The tracking issue indicates that the latest update of this tool does support .NET 8: https://github.com/dotnet/cli-lab/issues/279#issuecomment-2070904214

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md

### Document Version Independent Id

090b8fbd-39e6-b754-e1da-890b1123f2c4

### Article author

@adegeo

### Metadata

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 264463](https://dev.azure.com/msft-skilling/Content/_workitems/edit/264463)

**Comment by jongalloway** [comment]
cc @baronfel

**Comment by baronfel** [comment]
Thanks for catching this! Yeah, we've added support for 8. There are some mixed-architecture bigs we have to run down but for the most common user needs we're good to go.
