### ISSUE TITLE
FW link on WPF Community Feedback page leads to non-existent site

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#4133]
#fw link on WPF Community Feedback page leads to non-existent site

This document: https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/community-feedback.md

Issue:  Product Feedback Center link (http://go.microsoft.com/fwlink/?LinkId=99381) leads to a non-existent Connect site.   Determine if we have a better place for WPF product feedback and update the FW link with that if possible.

John Eddy at MS reported this issue since they received complaints to @MSDev.

**Comment by mairaw** [comment]
Wondering if we should keep that topic with the changes that we're planning for product and content feedback too. I'll follow up with the WPF team.
