### ISSUE TITLE
i wish reference project 

### ISSUE THREAD

**Issue by Nebucanetshar** [dotnet/docs#41349]
### Type of issue

Missing information

### Description

i wish referenced blazor project implemented package fluxor with grpc server but i've error list tell me " none exectution pack Microsoft.AspNetCore.App avaible with specified runtime "browser-wasm" 
someone can help me for thaht ? 

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/core/tools/sdk-errors/netsdk1082?f1url=%3FappId%3DDev16IDEF1%26l%3DFR-FR%26k%3Dk(NETSDK1082)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1082.md

### Document Version Independent Id

2eb5a7e4-5a0e-290e-ec8a-b7cec5257ab5

### Article author

@tdykstra

### Metadata

* ID: 6280ced1-08b7-ca6d-31b6-03a3b35278ce 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
@guardrex

**Comment by guardrex** [comment]
I'm *BACK!* I have time now that I'm waiting on reviews of PRs.

It's true that `Microsoft.AspNetCore.App` isn't available in a Blazor WebAssembly app (or client-side in a Blazor Web App); but beyond that, I'm not sure what this is about.

@Nebucanetshar ... Open an issue for the ASP.NET Core product unit at ...

https://github.com/dotnet/aspnetcore/issues

... but provide more information to them on what you're working on. It's best for them if you put up a minimal GitHub repro project that they can take a look at to see what type of app you have, what packages/libraries you're using, and how you have your code organized.

**Comment by tdykstra** [comment]
Closing, as it's been over a month without a response.
