### ISSUE TITLE
Wrong .NET listed for Server 2019

### ISSUE THREAD

**Issue by bobSerge** [dotnet/docs#41341]
### Type of issue

Typo

### Description

[Enter feedback here]
It lists a link to install .NET 4.8.1 for 2019 with link to installer, but 4.8.1 is supported only on Server 2022.  It should be 4.8 instead.  I have added too links below on .NET support for 2019 Server.

https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/on-server-2019

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/on-server-2019.md

### Document Version Independent Id

0bde7c8f-df1a-eb9c-1879-1401b63ef040

### Article author

@adegeo

### Metadata

* ID: a353245f-339b-60d2-d5c9-c8ac50b401fe 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

---
[Associated WorkItem - 264462](https://dev.azure.com/msft-skilling/Content/_workitems/edit/264462)

**Comment by adegeo** [comment]
Thanks for pointing that out. I'll get this fixed.
