### ISSUE TITLE
group clause page should explain that you can't use a custom equality comparer in query syntax

### ISSUE THREAD

**Issue by AakashM0** [dotnet/docs#41353]
### Type of issue

Missing information

### Description

The `group` clause page already correctly explains that this clause is translated into a call to the `GroupBy` method; but what it doesn't mention anywhere in its many useful examples is that *use of the `GroupBy` method is **required** if you want grouping to be done with a custom equality comparer* - this capability is not supported in query syntax.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/group-clause

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/group-clause.md

### Document Version Independent Id

a3aa9b7d-0cc1-778d-b01b-6bedcd80799b

### Article author

@BillWagner

### Metadata

* ID: 781a32e0-448c-2ca7-649f-5bf181302ec3 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks @AakashM0 
This is a great suggestion. I've aded it to our backlog for when we next update this page.
