### ISSUE TITLE
Vlagmen

### ISSUE THREAD

**Issue by vierlijner** [dotnet/docs#41350]
### Type of issue

Typo

### Description

Vlagmen should be Vlaggen (NL-dutch) as in the head translation from (https://learn.microsoft.com/nl-nl/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags)

### Page URL

https://learn.microsoft.com/nl-nl/dotnet/csharp/language-reference/builtin-types/enum

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/enum.md

### Document Version Independent Id

9d67fd2d-bfaa-7af4-a8d9-fd2a84aecd15

### Article author

@BillWagner

### Metadata

* ID: 248858d2-39c9-ff54-a396-5e7b4d79b640 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks for pointing this out @vierlijner 

I've opened a support issues on our internal system for the localization team. I'll close this as there's no futher action needed on the source content.
