### ISSUE TITLE
[Breaking change]: Deprecating Desktop Windows/macOS/Linux MonoVM Runtime Nuget Packages

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#41366]
### Description

The following desktop MonoVM runtime nuget packages are obsolete starting in .NET 9 Preview 7.
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.win-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.win-x86
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.linux-arm
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.linux-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.linux-arm64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.linux-musl-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.osx-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.osx-arm64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.LLVM.AOT.linux-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.LLVM.AOT.osx-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.LLVM.linux-arm64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.LLVM.linux-x64
 - https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.Mono.LLVM.osx-x64

These nuget packages could optionally be used during .NET SDK publish for self-contained applications via an undocumented SDK switch.  These desktop MonoVM runtime packages are not the default configuration for .NET publish scenarios.  .NET 9 Preview 6 is the last release of these packages.

### Version

.NET 9 Preview 7

### Previous behavior

During .NET SDK publish, these desktop MonoVM nuget runtime packages were available for self-contained applications using an undocumented SDK switch.

### New behavior

Starting in .NET 9 Preview 7, these desktop MonoVM nuget runtime packages are no longer available.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

There is no official .NET scenario that aligns with these desktop MonoVM runtime nuget packages. 

### Recommended action

If your application publish relies on these packages, we recommend staying on .NET 8 LTS while the application migrates to the default desktop runtime nuget packages.  Each of these platforms has a corresponding runtime nuget package.

### Feature area

Other (please put exact area in description textbox)

---
[Associated WorkItem - 292113](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292113)

**Comment by srxqds** [comment]
there are so many team embed mono with game engine.
I hope you keep the original plan. upload the mono desktop runtime package.
More people and teams will use and verify it

**Comment by jeffschwMSFT** [comment]
@srxqds can we schedule some time to talk?  I would love to hear details about how these packages are used and if our corresponding Microsoft.NETCore.App.Runtime.* would be a viable option.  

To connect, here is my linkedin profile: https://www.linkedin.com/in/jeff-schwartz-4ba91023/

**Comment by srxqds** [comment]
hi，@jeffschwMSFT, I am so sorry I have no linkedin account, I can describe here as detail as I can.
we have emebed mono in UnrealEngine, we use c# as game script develop, We have been using it for many years.
And according to my understanding, many teams actually use this solution.

**Comment by jeffschwMSFT** [comment]
A few follow-up questions.

For some platforms is monovm built and package (eg. consoles, etc.) locally?  This breaking change is does not change the lifecycle of monovm.
For scenarios where these packages are used, have the Microsoft.NETCore.App.Runtime.* been explored?  What gaps exist to move to these?

.NET 8 will continue to have support for these packages which aligns with our lifecycle: https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core.  So in the near term .NET 8 could continue to be a supported scenario.  We would be interested in hearing what a change to our default packages would look like.

**Comment by srxqds** [comment]
ok, but when you not shipping nuget packages, we are starting to worry that you may be no longer supported
and close test coverage for mono desktop runtime.

**Comment by jeffschwMSFT** [comment]
I understand the concern.  This breaking change does not impact monovm's support for its primary shipping scenarios - iOS, Android, WASM, etc.  Internally we use versions of these builds for validation, but we will no longer ship them for the reasons noted above.  
I hope that clarifies what is changing.

**Comment by srxqds** [comment]
ok, than you for reply.
