### ISSUE TITLE
The section on "return values" should explain expression bodied members

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#41393]
### Type of issue

Missing information

### Description

The text for return values discuss the `return` keyword, but the samples are mostly expression bodied members. Their should be an example with a statement body and a `return` statement. And, the text should explain that expression bodied members return the value returned by the expression.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/methods

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/methods.md

### Document Version Independent Id

6386f636-99b3-93c3-ca9e-0134f3e3be10

### Article author

@BillWagner

### Metadata

* ID: 158425f1-86b1-101a-9172-14c944867784 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by bigboybamo** [comment]
Hi @BillWagner, I'd like to pick this up

**Comment by BillWagner** [comment]
Hi @bigboybamo 

I've assigned it to you

**Comment by bigboybamo** [comment]
Hi @BillWagner I have opened a PR #41636
