### ISSUE TITLE
Create topic on multi-targeting

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4141]
We cover some of this on the following topic: https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks

We need to explain how it's done, what it means, implications, etc.

/cc @terrajobst

**Comment by terrajobst** [comment]
Yes, I think these docs are very important as it's likely becoming an advanced scenario that many people will have to use.

**Comment by BillWagner** [comment]
@terrajobst Any chance you can update the branch where you've started this or create the PR?

**Comment by mairaw** [comment]
The PR is here: https://github.com/dotnet/docs/pull/4709

**Comment by mairaw** [comment]
@terrajobst is your PR ready for final review? Or do you still need to some work?

**Comment by terrajobst** [comment]
No because I'm terrible at finishing things recently (or maybe ever? 🤪). I'll try to finish it this week.

**Comment by mairaw** [comment]
I know how it goes. No worries. 😄

**Comment by BillWagner** [comment]
Ping @terrajobst Any chance this happens by the end of this sprint?

**Comment by mairaw** [comment]
@terrajobst I'm moving this to our backlog.

**Comment by tdykstra** [comment]
> The PR is here: #4709

That PR was closed with this comment:

> This will be incorporated into the updates that are being proposed by #7833.

#7833 was merged
