### ISSUE TITLE
"using" - a verb or the directive?

### ISSUE THREAD

**Issue by QueryCoordinator** [dotnet/docs#41419]
### Type of issue

Other (describe below)

### Description

Hello,

please check if 'using' is unnecessarily marked as 'code' in this sentence: "In Blazor, you can register handlers for DOM UI events directly **using** directive attributes of the form @on{event}." as referring to 'using' directive? We think it should be a normal verb of the sentence in this case.

Kind regards,
Anne H., QC

### Page URL

https://learn.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/architecture/blazor-for-web-forms-developers/components.md

### Document Version Independent Id

24368808-4b90-f75a-e887-eb72a1c85f5b

### Article author

@danroth27

### Metadata

* ID: 60c195c0-99f6-64f5-66a3-4e69109dc8ee 
* Service: **dotnet-architecture**
* Sub-service: **blazor**

**Comment by BartoszKlonowski** [comment]
Yes, this is definitely a mistake. Also, when changing the language to other than English, the sentence doesn't really make sense having "using" marked as code.
I will fix that.
Thank you for taking the time to report, @QueryCoordinator!

**Comment by QueryCoordinator** [comment]
Thank you for your swift reply!

Kind regards,
Anne H., QC
