### ISSUE TITLE
CS2008:

### ISSUE THREAD

**Issue by Leosantos101** [dotnet/docs#41423]
### Type of issue

Typo

### Description

[Insira comentários aqui]

### Page URL

https://learn.microsoft.com/pt-br/dotnet/csharp/misc/cs2008

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs2008.md

### Document Version Independent Id

a76f41f1-1e79-2dcc-5ffd-5063cdb12f4d

### Article author

@BillWagner

### Metadata

* ID: b5f86dcb-f9a9-7911-5764-40940b76d4e5 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Hi @Leosantos101 

It looks like this was opened by mistake (there's no description to help us fix it). I'll close it, but if you want to reopen and add more information, we'll take a look.
