### ISSUE TITLE
LIAM

### ISSUE THREAD

**Issue by liam802** [dotnet/docs#41446]
### Type of issue

Typo

### Description

[Escriba sus comentarios aquí]
NYA

### Page URL

https://learn.microsoft.com/es-es/dotnet/framework/install/dotnet-35-windows

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/dotnet-35-windows.md

### Document Version Independent Id

40ddc3ce-a004-1a4c-37e1-1c45eaa8f35a

### Article author

@adegeo

### Metadata

* ID: 96aef419-de1f-a341-3f19-4ed99eb36412 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

**Comment by adegeo** [comment]
No information provided. Closing issue.
