### ISSUE TITLE
Install .NET Framework on Windows Server 2019

### ISSUE THREAD

**Issue by tangtc1981** [dotnet/docs#41464]
### Type of issue

Code doesn't work

### Description

Hi,

please help to confirm that .net framework 4.8.1 can be installed on windows server 2019 as mentioned in below url.

https://learn.microsoft.com/en-us/dotnet/framework/install/on-server-2019

i found that the latest installer still blocking this from installing in windows server 2019 and the server requirements also having note of out-of-support.

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/get-started/system-requirements.md

### Document Version Independent Id

2010bd32-59f6-823c-f193-27439e12798d

### Article author

@gewarren

### Metadata

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e 
* Service: **dotnet-framework**

---
[Associated WorkItem - 289272](https://dev.azure.com/msft-skilling/Content/_workitems/edit/289272)

**Comment by gewarren** [comment]
It only supports .NET Framework 4.8.
