### ISSUE TITLE
This page references documentation of outdated GitHub actions tool

### ISSUE THREAD

**Issue by dlidstrom** [dotnet/docs#41494]
### Type of issue

Typo

### Description

The dotnet/code-analysis GitHub action is outdated and no longer works with modern .NET. I tried it and it seems to want .NET Core 3.1.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md

### Document Version Independent Id

128f9903-971d-6a66-a2cb-9b12acbc55e7

### Article author

@gewarren

### Metadata

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 286588](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286588)

**Comment by gewarren** [comment]
@mavasani It looks like there haven't been any update to the dotnet/code-analysis repo in 3 years. Is the action still applicable?
