### ISSUE TITLE
Net Framework v4.0.30319

### ISSUE THREAD

**Issue by FranRuiQuin** [dotnet/docs#41497]
### Type of issue

Other (describe below)

### Description

[Escriba sus comentarios aquí]net framework v4.0.30319. Tengo problemas
![Captura de pantalla (96)](https://github.com/dotnet/docs/assets/69168837/f977c64a-001d-414a-8496-cdb712fc020b)

### Page URL

https://learn.microsoft.com/es-es/dotnet/core/porting/upgrade-assistant-install#install-the-visual-studio-extension

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/porting/upgrade-assistant-install.md

### Document Version Independent Id

af696b7d-2a60-7b0d-9318-bf7479974e2e

### Article author

@adegeo

### Metadata

* ID: ac41b6b8-dc98-b63c-c2c3-57c38ff5dcf5 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Sorry, this isn't a support forum. Please use Microsoft Q&A or some other forum for help. Looking briefly, it seems like you're missing a specific .NET Framework version. Contact Nero Vision for support. Thanks and sorry!
