### ISSUE TITLE
.Net Version 8.0

### ISSUE THREAD

**Issue by smehta-rms** [dotnet/docs#41490]
### Type of issue

Missing information

### Description

Please mention dotnet version 8.0 is in supported distribution or unsupported distribution

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-centos

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-centos.md

### Document Version Independent Id

26300783-8df5-56a1-4ab6-4b8511e37f51

### Article author

@adegeo

### Metadata

* ID: 577ce9b2-5b48-4ed2-c309-a78880015dd2 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
CentOS support from Red Hat ends this month, forever. So we'll be removing this page in a week or so. Because of that, .NET 8 wasn't released for CentOS. You'll have to upgrade to CentOS Stream, or manually install .NET 8 and try to get it to work, but without support, sorry.
