### ISSUE TITLE
Paragraph about avoiding overriding the same method in multiple derived interfaces is unclear

### ISSUE THREAD

**Issue by amfgold** [dotnet/docs#41491]
### Type of issue

Missing information

### Description

In the second to last paragraph of the article, it states: 

> "if both the IBlinkingLight and ITimerLight implemented an override of PowerStatus, the OverheadLight would need to provide a more specific override. Otherwise, the compiler can't pick between the implementations in the two derived interfaces."

But it is unclear how the compiler would be confused here. If the OverheadLight class doesn't provide a more specific override, then the ways to access the PowerStatus from an instance of the OverheadLight class would be to cast or convert it to either an ILight, an IBlinkingLight or an ITimerLight. In those cases, the compiler would know which implementation to pick. Is there another way an instance of OverheadLight could be used to access the PowerStatus that would cause a compiler error?

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/interface-implementation/mixins-with-default-interface-methods

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/advanced-topics/interface-implementation/mixins-with-default-interface-methods.md

### Document Version Independent Id

98229926-6c7a-3ad1-ab5c-86231253986c

### Article author

@BillWagner

### Metadata

* ID: 2c7899e8-3f01-41d2-137a-e334b73699a4 
* Service: **dotnet-csharp**
* Sub-service: **advanced-concepts**

---
[Associated WorkItem - 269279](https://dev.azure.com/msft-skilling/Content/_workitems/edit/269279)

**Comment by BillWagner** [comment]
Good question @amfgold 

I'll address this in the next month.
