### ISSUE TITLE
.NET Framework アプリケーションの実行時に "このアプリケーションを開始できませんでした" というエラーが表示される

### ISSUE THREAD

**Issue by kasa0218** [dotnet/docs#41523]
### Type of issue

Typo

### Description

.NET Framework アプリケーションの実行時に "このアプリケーションを開始できませんでした" というエラーが表示される
修復ツールをインストールしてもＮＧで

### Page URL

https://learn.microsoft.com/ja-jp/dotnet/framework/install/application-not-started?version=(null)&processName=clock_screensaver.scr&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/application-not-started.md

### Document Version Independent Id

de902eee-6f6b-3ccd-4dbf-1cc174daa806

### Article author

@adegeo

### Metadata

* ID: c89966aa-b155-c98a-2391-47e01d468236 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

**Comment by kasa0218** [comment]
ｗｈｙ　リカバリィ？

**Comment by adegeo** [comment]
Sorry @kasa0218 this isn't a support forum. I suggest you try to use Microsoft Q&A, StackOverflow, or ask help from the application vendor who created what you're trying to run. This forum is for support about the documentation itself.
