### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by 0ndrej** [dotnet/docs#41535]
### Type of issue

Code doesn't work

### Description

This example line of code cannot be compiled (VS2022, .NET6, Console Application):
Dim namedCust = New Customer With {.Name = "Terry Adams"}

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/objects-and-classes/object-initializers-named-and-anonymous-types

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/objects-and-classes/object-initializers-named-and-anonymous-types.md

### Document Version Independent Id

6e200f47-b758-968e-948b-a6d62170ec86

### Article author

@KathleenDollard

### Metadata

* ID: 76828301-3fcc-88cb-636a-a2e186b1cf06 
* Service: **dotnet-visualbasic**

**Comment by adegeo** [comment]
That code is demonstrating the syntax of an object initializer. It's not meant to compile because you don't have the required class type. It's showing the following syntax:

```
Dim namedCust  = New Customer With {.Name       = "Terry Adams"}
Dim <variable> = New <type>   With {.<property> = "Terry Adams"}
```

To compile it, you need a `Customer` type with a `Name` string property:

```vb
Public Class Customer

    Public Property Name As String

End Class
```
