### ISSUE TITLE
Update the examples in global.json article

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#41545]
### Type of issue

Typo

### Description

We now talk about .NET Core as .NET 5 and above, so it is confusing to may be confusing to see examples with 2.2 and 3.0. 

Also, an MVP question leads me to believe that we might want additional clarity on what latest patch and latest feature are.

IIRC, latest feature also gave you latest patch, etc. That was unclear in the Q&A I observed.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#examples

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/global-json.md

### Document Version Independent Id

6d80613f-42dc-35d7-aeff-3187a36dbbca

### Article author

@tdykstra

### Metadata

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 271691](https://dev.azure.com/msft-skilling/Content/_workitems/edit/271691)

**Comment by tdykstra** [comment]
> Also, an MVP question leads me to believe that we might want additional clarity on what latest patch and latest feature are.
> IIRC, latest feature also gave you latest patch, etc. That was unclear in the Q&A I observed.

I reviewed the article for clarity, and both text and examples look good to me. I'm open to suggestions. Maybe updating the version numbers is all it needs for improved clarity.

I don't know what Q&A you saw, but in the thread I see in the MVP DL, the person asking correctly understands what to expect but is not getting it and so he filed an Azure Pipelines bug for it.
