### ISSUE TITLE
Need to determine which .NET Core SDK has which C# version enabled

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4154]
We explain which C# version ships with which release of Visual Studio. @damtur raised this issue after a talk that he could not find that mapping for the versions that ship with .NET Core SDK versions. For example, which .NET SDK has C# 7.1? or 7.2? This make affect the dotnet CLI, as the compiler ships as a dotnet tool.

We need to make this more prominent if it is published. If not, we need to publish it more prominently.

/cc @richlander @jcouv @KathleenDollard

**Comment by jcouv** [comment]
Tagging @livarcocc for this

**Comment by BillWagner** [comment]
As a work around, you can add an error pragma to the source to print the version:

```csharp
#error version
```

This cause the compiler to print its version (the compiler software version, not the project LangVersion) to the console. It also causes the build to fail.

**Comment by dasMulli** [comment]
cross-linking https://github.com/dotnet/cli/issues/8042 which raised some other questions in the process:

* How do I know what things I have in my .NET Core SDK (NuGet, MSBuild etc., not relevant here)
* How do I know which Roslyn version number corresponds to which C# version <-- hard part
(https://github.com/dotnet/cli/issues/8042#issuecomment-356638924)

Same probably goes for F# since it now ships in-box.

**Comment by svick** [comment]
@dasMulli 

> How do I know which Roslyn version number corresponds to which C# version

This is documented in [the Roslyn repo wiki article *NuGet packages*](https://github.com/dotnet/roslyn/wiki/NuGet-packages#versioning). Though including that information somewhere in docs.MS is probably a good idea.

**Comment by BillWagner** [comment]
@KathleenDollard said: 

> Do we have a place in docs to put this?

I'd suggest either the .NET Core "What's new" page, or coordinating with the ongoing versioning work.

**Comment by richlander** [comment]
I think we need two things:

- An entry in "What's new".
- a decorder ring table that explains what's in each release. This can go in docs or in a repo. It is probably best put in dotnet/core in release notes. Yes?

**Comment by svick** [comment]
Putting together information from [*NuGet packages* on Roslyn wiki](https://github.com/dotnet/roslyn/wiki/NuGet-packages) (which maps Roslyn versions, C# versions and VS versions), [Releases on the cli repo](https://github.com/dotnet/cli/releases) (which maps .Net Core SDK versions and VS versions) and from my own attempts of running various versions of the .Net Core SDK, as far as I can tell, corresponding versions are:

|Roslyn|C#|VS|.Net Core SDK|
|---|---|---|---|
|1.x|6.0|2015||
|2.0|7.0|15.0|1.0.4|
|2.1|7.0|15.1||
|2.2|7.0|15.2||
|2.3|7.1|15.3|1.1.4|
|2.4|7.1|15.4|2.0.2|
|2.6|7.2|15.5|2.1.2|
|2.7|7.2|15.6|2.1.100|
|2.8|7.3|15.7|2.1.200|
|2.9|7.3|15.8||

**Comment by dasMulli** [comment]
In theory, it also bundles an F# compiler (and a version of NuGet but that's hardly relevant)

**Comment by BillWagner** [comment]
PR #6081 will fix this.

**Comment by BillWagner** [comment]
This was fixed in #6081

**Comment by colonelchlorine** [comment]
@BillWagner Not sure if #6081 solved the problem of this ticket. Having trouble finding the mapping of .NET Core <-> language version (C# in particular). svick's post above is the only thing I can find. Might be missing something?

Checked [DotNet Core Versions](https://docs.microsoft.com/en-us/dotnet/core/versions/) and don't see the language versions that line up.

**Comment by colonelchlorine** [comment]
Aha - bit tricky to find. Needed to go to the "Find more in .NET Core 2.1 downloads" or "download archives" from the Downloads page. The archive pages are full of useful info. Thanks @BillWagner
