### ISSUE TITLE
Docker content for .NET

### ISSUE THREAD

**Issue by rachelappel** [dotnet/docs#4155]
Moved to .NET Repo from ASPNET https://github.com/aspnet/Docs/issues/5096 

Team prefers a scenario based doc and does not want a copy and paste. Base on this doc instead https://blogs.msdn.microsoft.com/dotnet/2017/05/25/using-net-and-docker-together/

**Comment by mairaw** [comment]
@JRAlexander would you be the one doing this? and any idea of a milestone to set here?

**Comment by rachelappel** [comment]
@mairaw  John and I are working on it. With John out and just over a week, probably the next sprint is best.

**Comment by JRAlexander** [comment]
Yes, agreed!

**Comment by JRAlexander** [comment]
Closed based on feedback that this is covered by existing articles.
