### ISSUE TITLE
[C# 13]: New Feature - 

### ISSUE THREAD

**Issue by zoran666540** [dotnet/docs#41599]
### Visual Studio release

17.9p3

### Link to speclet

- [Speclet](https://github.com/dotnet/csharplang/blob/main/proposals/feature.md)

### Link to Pull request

- [PR](https://github.com/dotnet/roslyn/pulls/nnnnn)

### New behavior

![android kali screen](https://github.com/dotnet/docs/assets/60578676/4e85a4f5-fa3d-4c09-84ee-697a56c59f5c)

### Areas affected

- [X] **Add to What's new in C# 13**: Add links to updated docs in the What's new in C# 13 article.
- [X] **Update language reference**: Detail the areas in the language reference that will be updated for this feature.
- [X] **Update compiler messages**: Add new (or updated) pages for new compiler messages. Include related message.
- [X] *Include in *Everyday C#* section**: Is this new feature included in Everyday C#?
- [X] **Tutorials**: Are new tutorials required for this feature? If so, detail below

**Comment by BillWagner** [comment]
closing as spam
