### ISSUE TITLE
Repo Status

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/docs#41606]
### Type of issue

Missing information

### Description

[Enter feedback here]
In trying to complete this lesson it asks me to create a access token on GitHub.  The instructions say select repo:status.  According to GitHub repo:status does not exist, see image.  I tried just status and repo:status. Neither exists. 
![Access Token](https://github.com/dotnet/docs/assets/42590236/f2f47891-bb85-4376-9fc7-b95bb57fd30b)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/generate-consume-asynchronous-stream

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/generate-consume-asynchronous-stream.md

### Document Version Independent Id

0910174f-c065-5cb3-3c1a-7d44409903d2

### Article author

@BillWagner

### Metadata

* ID: e2d2f1e2-6b7f-d696-0e67-441c1f4bcfe9 
* Service: **dotnet-csharp**
* Sub-service: **async-task-programming**

**Comment by BillWagner** [comment]
hi @mthanson8333 

That text refers to the allowed scopes:

![image](https://github.com/dotnet/docs/assets/493969/57c2a461-a109-469c-a75d-32e6eba35e8d)


Not the name of the repo. I'll add this to our backlog to update it when we next update this article. I've also added the "help wanted" tag if anyone wants to submit a PR in the interim.

**Comment by adegeo** [comment]
@mthanson8333 The GitHub help has the information you need, how to get to the point where you're creating tokens: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token

**Comment by mthanson8333** [comment]
Thanks for the help.  I figured it out late last night.  I clicked on fine-grained tokens instead of classic tokens.  Sorry to have bothered you.
