### ISSUE TITLE
Install script site is down

### ISSUE THREAD

**Issue by MrKapocsDiligent** [dotnet/docs#41609]
### Type of issue

Outdated article

### Description

Site is down: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-install-script.md

### Document Version Independent Id

5bc7caa5-f1c2-d7d5-fe02-80c65cca9672

### Article author

@tdykstra

### Metadata

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
The site is working now.
