### ISSUE TITLE
error CS1674: 'Options': type used in a using statement mu  st be implicitly convertible to 'System.IDisposable'.

### ISSUE THREAD

**Issue by dudhatjanvi** [dotnet/docs#41607]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
using (Options options = new Option())  this new option object not consider in dt search std version 
it's showing error like this  : error CS1674: 'Options': type used in a using statement mu 
st be implicitly convertible to 'System.IDisposable'.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1674

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1674.md

### Document Version Independent Id

a692e362-ba9b-5163-b268-de1c90c77633

### Article author

@BillWagner

### Metadata

* ID: 91bc4df9-abde-65e4-366e-9fa61440f038 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Hi @dudhatjanvi 

To fix the error, the `Options` type must implement `IDisposable`:

```csharp
public class Options : IDisposable
{
}
```
