### ISSUE TITLE
[Project] Security and crypto review

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4161]
We need to review conceptual articles and API reference to make sure we have current guidelines re. security and cryptography.

MD5 and SHA1 shouldn't be used anymore -> SHA256 / 384 / 512

**Updates to conceptual docs (~50)**

- [ ] @mairaw to grab BI data to help with prioritization
- [ ] review topics to make sure they have accurate guidance

**API docs**
- [ ] add notes for MD5/SHA1/etc.

**Samples**
not removing samples from the APIs if they're useful. We'll just add notes to recommend other algorithms.

- [ ] Remove MD5/SHA1 -> SHA256/384/512 
- [ ] Remove RC2/DES/TripleDES/Rijndael -> AES
- [ ] SSL2,SSL3,TLS or SSLProtocols enum -> None ( it was Default before)
- [ ] RSA/DSA: exposed two Windows implementations (older RSA/DSACryptoServiceProvider, newer RSA/DSACNG) and other restrictions on key sizes and parameters. The base class is RSA/DSA.
- [ ] Remove RIPEMD160 -> SHA256
- [ ] Remove MacTripleDES -> HMAC SHA256
- [ ] Remove usage of the PrivateKey property

These are some raw notes to get this project started. We'll create individual issues as we go.

/cc @rpetrusha @bartonjs @AlexGhiondea @morganbr - please let me know if I missed anything or captured anything wrong

**Comment by tdykstra** [comment]
Closing, as Ron created a [Security review project](https://github.com/dotnet/docs/projects/33) and converted all of these tasks to issues in that project.
