### ISSUE TITLE
Dead link to ILLink documentation

### ISSUE THREAD

**Issue by cdefgah** [dotnet/docs#41624]
### Describe the issue or suggestion

On [the documentation page](https://learn.microsoft.com/en-us/dotnet/maui/ios/linking?view=net-maui-8.0&tabs=vs) there's a dead link to ILLink documentation: https://github.com/dotnet/linker/tree/main/docs

![image](https://github.com/dotnet/docs/assets/10169696/ed2a9c5b-aeef-4047-8221-39ad77176fd9)

**Comment by BartoszKlonowski** [comment]
Hello @cdefgah!
This issue you created should be made for different repo: [docs-maui](https://github.com/dotnet/docs-maui).
You can use the "Open a documentation issue" button on the bottom of that page and it will bring you to the right repo to report the issue.
CC: @davidbritch (just in case you would like help to move this issue 🙏)

**Comment by cdefgah** [comment]
Ok, I created issue in docs-maui: https://github.com/dotnet/docs-maui/issues/2381
