### ISSUE TITLE
Undefined acronym

### ISSUE THREAD

**Issue by markwaterman** [dotnet/docs#41635]
### Type of issue

Missing information

### Description

[Enter feedback here]
"TFM" is used throughout this article but isn't defined.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1#when-to-target-net80-vs-netstandard

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/net-standard.md

### Document Version Independent Id

6819a4a7-7527-d8c7-e132-767f7344e00e

### Article author

@gewarren

### Metadata

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7 
* Service: **dotnet**
* Sub-service: **standard-library**

**Comment by gewarren** [comment]
TFM = target framework moniker.

**Comment by samwherever** [comment]
[PR submitted here](https://github.com/dotnet/docs/pull/41692), hopefully this does the trick!
