### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by runceel** [dotnet/docs#41638]
### Type of issue

Missing information

### Description

The `binary analysis` link is 404 Not found.
> ## Analyze non-NuGet dependencies
> You may have a dependency that isn't a NuGet package, such as a DLL in the file system. You can determine the portability of that dependency by using the [binary analysis](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md) functionality of the [.NET Upgrade Assistant](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview).

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/porting/third-party-deps

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/porting/third-party-deps.md

### Document Version Independent Id

f238803f-7e31-e6b1-0d23-cebb0672de95

### Article author

@StephenBonikowsky

### Metadata

* ID: 1571bd84-84b9-ef24-f96f-304665e22bea 
* Service: **dotnet-fundamentals**

**Comment by BartoszKlonowski** [comment]
Hello @runceel!
Yes, this link is removed in the original repo, but I believe you could still use [.NET Upgrade Assistant](https://learn.microsoft.com/dotnet/core/porting/upgrade-assistant-overview#upgrade-with-the-cli-tooll).
Please check if this is what you need, in the meanwhile I will update the article.
Thank you for taking the time to report! 👍
