### ISSUE TITLE
Document the TimeProvider class

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#41650]
### Type of issue

Missing information

### Description

The `TimeProvider` class isn't talked about in all of the date/time related articles.

@tarekgh can you provide some brief context on the point of this class and where customers would use it?

#### Customer feedback

> Needs information on the TimeProvider class

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/datetime/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/datetime/index.md

### Document Version Independent Id

24332884-c808-ba59-5187-3d4b1670d269

### Article author

@adegeo

### Metadata

* ID: f2d2995c-cd29-3912-5d9c-9bfd76c7df5c 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 310710](https://dev.azure.com/msft-skilling/Content/_workitems/edit/310710)

**Comment by tarekgh** [comment]
@adegeo community members blogged about it like: 
- https://andrewlock.net/exploring-the-dotnet-8-preview-avoiding-flaky-tests-with-timeprovider-and-itimer/#what-s-the-problem-with-the-existing-apis- 
- https://blog.nimblepros.com/blogs/finally-an-abstraction-for-time-in-net/
- https://www.roundthecode.com/dotnet-tutorials/timeprovider-easier-mock-time-dotnet-8
- https://www.youtube.com/watch?v=3vRUdc1GA4k

We should write a conceptual doc though. I can help with that when I get the chance or if you are interested you may help writing it? Thanks!

**Comment by adegeo** [comment]
@tarekgh Thanks for the reply! I wouldn't be targeting getting written until maybe next quarter. Provided those posts/video have enough info in there, I could get a conceptual article written for sure. Thanks for the info!
