### ISSUE TITLE
Wrong example for JSON deserializing to JsonNode

### ISSUE THREAD

**Issue by cknaap** [dotnet/docs#41667]
### Type of issue

Code doesn't work

### Description

The second code example should show deserialization into JsonNode or JsonElement, but instead repeats the first code example, showing deserialization into a POCO.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/handle-overflow

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/handle-overflow.md

### Document Version Independent Id

b5adfacc-b5e4-2dec-84b0-5b2a91fdc3dc

### Article author

@gewarren

### Metadata

* ID: 26f7f7d7-22f5-a4e3-0505-68aa38b4fef6 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
This code example is correct, and different to the first example. It's the type of the *properties* that's different.

<img width="329" alt="image" src="https://github.com/user-attachments/assets/78b038fb-90d6-4c55-a81e-b068126e8690">
