### ISSUE TITLE
[Breaking change]: X509Certificate2, X509Certificate constructors and X509Certificate2Collection.Import are obsolete for binary and file content

### ISSUE THREAD

**Issue by vcsjones** [dotnet/docs#41662]
### Description

The constructors on `X509Certificate` and `X509Certificate2` that accept content as a `byte[]`, `ReadOnlySpan<byte>`, or a `string` file path have been marked obsolete.

The `Import` method and all overloads on `X509Certificate2Collection` have also been marked obsolete.

### Version

.NET 9 Preview 7

### Previous behavior

Developers could use those APIs without an obsolete warning.

### New behavior

Affected APIs will receive an obsolete compilation warning with SYSLIB0057.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

The affected APIs supported loading certificates in multiple formats. For example, `new X509Certificate2(data)` would load a certificate from a `byte[]` called data. This data could be one of any supported format, including X.509, PKCS7, or PKCS12/PFX.

While this was easy to use, it created issues where user-supplied data is passed with a different format than intended. This may allow loading PKCS12 where only X.509 content was intended to be loaded, or create interoperability issues from handling the data in different ways.

### Recommended action

Developers should use a different API to load certificate content, depending on the intended content type.

A new class called `X509CertificateLoader` can be used to load X.509 or PKCS12 content.

* If you are loading X.509 content, `X509CertificateLoader.LoadCertificate` and `X509CertificateLoader.LoadCertificateFromFile` can be used.
* If you are loading PKCS12 content, `X509CertificateLoader.LoadPkcs12`, `X509CertificateLoader.LoadPkcs12FromFile`, `X509CertificateLoader.LoadPkcs12Collection`, and `X509CertificateLoader.LoadPkcs12CollectionFromFile` can be used.
* If you are loading PKCS7 content, `SignedCms` from the `System.Security.Cryptography.Pkcs` package can be used to inspect certificates in PKCS7 content.

If you are uncertain about the content type you are loading, `X509Certificate2.GetCertContentType` can be used to determine the content type and call the appropriate API.

You may also suppress the obsoletion using `#pragma warning disable SYSLIB0057` and `#pragma warning restore SYSLIB0057` around the affected code to continue using the legacy certificate loading APIs.

The `Microsoft.Bcl.Cryptography` package supplies `X509CertificateLoader` for .NET Framework and .NET Standard.

### Feature area

Cryptography

### Affected APIs

Affected Doc IDs:

* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.Byte[])`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.ReadOnlySpan{System.Byte})`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.Byte[],System.Security.SecureString)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.Byte[],System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String,System.Security.SecureString)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String,System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.Byte[],System.Security.SecureString,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.Byte[],System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.ReadOnlySpan{System.Byte},System.ReadOnlySpan{System.Char},System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String,System.ReadOnlySpan{System.Char},System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String,System.Security.SecureString,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2.#ctor(System.String,System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`

-----

* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.Byte[])`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.Byte[],System.Security.SecureString)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.Byte[],System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String,System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String,System.Security.SecureString)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String,System.String)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.Byte[],System.Security.SecureString,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.Byte[],System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String,System.Security.SecureString,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate.#ctor(System.String,System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`

-----

* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.Byte[])`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.ReadOnlySpan{System.Byte})`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.ReadOnlySpan{System.Byte})`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.Byte[],System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.ReadOnlySpan{System.Byte},System.ReadOnlySpan{System.Char},System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.ReadOnlySpan{System.Byte},System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.String,System.ReadOnlySpan{System.Char},System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`
* `M:System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(System.String,System.String,System.Security.Cryptography.X509Certificates.X509KeyStorageFlags)`

-----

* `"M:System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(System.String)`

---
[Associated WorkItem - 292111](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292111)

**Comment by vcsjones** [comment]
The content and messaging of this should get sign-off from @bartonjs first.

**Comment by bartonjs** [comment]
I tweaked the message a little bit, LGTM.

**Comment by akoeplinger** [comment]
@bartonjs reading https://github.com/dotnet/runtime/issues/91763 it looks like the Authenticode pieces were cut, is the intention for those to keep using `X509Certificate2` ctor and suppress the warning?

Here's code from the SDK where we use this and I had to suppress:
https://github.com/dotnet/sdk/blob/70479edb89ef1820051e951c4977f5fdb153f8e1/src/Cli/dotnet/Installer/Windows/Security/Signature.cs#L32-L35

**Comment by akoeplinger** [comment]
Also there's quite a lot of code that uses the approach shown in https://stackoverflow.com/questions/72096812/loading-x509certificate2-from-pem-file-results-in-no-credentials-are-available/72101855#72101855 to export+import a cert to workaround some Windows issue, is that contuing to work with export+X509CertificateLoader.LoadCertificate ?

**Comment by bartonjs** [comment]
> reading https://github.com/dotnet/runtime/issues/91763 it looks like the Authenticode pieces were cut, is the intention for those to keep using X509Certificate2 ctor and suppress the warning?

More or less.  For anyone still using that ctor, but expecting a certain content type, the recommendation is to do something like

```C#
if (X509Certificate2.GetContentType(input) != X509ContentType.TheOneIExpect)
{
    throw new CryptographicException();
}

X509Certificate2 cert = new(input);
```

**Comment by bartonjs** [comment]
>  export+import a cert to workaround some Windows issue, is that contuing to work with export+X509CertificateLoader.LoadCertificate

Yeah, just now it's `X509CertificateLoader.LoadPkcs12(cert.Export(X509ContentType.Pkcs12, null))`

**Comment by akoeplinger** [comment]
Ok. It's a bit sad that we have to suppress the warning for the Authenticode case but so be it :)

**Comment by ScotMac** [comment]
> > export+import a cert to workaround some Windows issue, is that contuing to work with export+X509CertificateLoader.LoadCertificate
> 
> Yeah, just now it's `X509CertificateLoader.LoadPkcs12(cert.Export(X509ContentType.Pkcs12, null))`

@bartonjs HI Jeremy, i believe that question you quoted was in reference to PEM files. How do we get an x509Certificate2Collection for a PEM file with multiple certs/keys that has been read in and is now in a byte[]?

Thanks.

**Comment by bartonjs** [comment]
@ScotMac If you actually mean PEM when you say PEM, then that's [X509Certificate2Collection.ImportFroPem](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2collection.importfrompem?view=net-8.0), which is not being marked as obsolete.

If you meant PFX when you said PEM, that's X509CertificateLoader.LoadPkcs12Collection.

**Comment by bartonjs** [comment]
Oh, I slightly lied. The Collection ImportFromPem won't import private keys.  There's no API for loading multiple certificates and multiple private keys from PEM.  Only PFX supports multiple private keys.

**Comment by ScotMac** [comment]
Thanks Jeremy.

Yes, it appears that API will only read in public key certs. Is there no .NET API for reading at least one private key, and possibly multiple public key certs in a PEM file? Thus providing a way to read in the key/certs necessary to estabish an mTLS connection (including the validation of the server cert), without using MCS (cert stores).

**Comment by ScotMac** [comment]
And yes, i meant PEM. 

But thanks for that p12 load function, since we are currently using x509Certificate2Collection.Import() for p12, which appears to be obsoleted by this notice.

**Comment by ScotMac** [comment]
@bartonjs  Hi Jeremy, it appears that the replacement functions you suggested, LoadPkcs12 and LoadPkcs12Collection, are part of the nuget package Microsoft.Bcl.Cryptography. Are there any plans to make them "built-in" to .NET?

Also, Microsoft.Bcl.Cryptography original purpose was to add support in older .NET versions that didn't have the newer cryptography support. That is not the case here, where this is instead Core functionality for .NET that was obsoleted.

**Comment by vcsjones** [comment]
@ScotMac 

> Are there any plans to make them "built-in" to .NET?

They are built in to .NET 9. You don't need the package if you are targeting .NET 9+. Microsoft.Bcl.Cryptography is only needed if you want the API down level, which might make multi-targeting easier.

**Comment by sailro** [comment]
What is the recommended way of replacing the now obsolete `X509Certificate.CreateFromSignedFile` (able to **extract** a certificate from a **signed** dll/exe file).

Because `X509CertificateLoader.LoadCertificateFromFile` is doing a complete different stuff => loads a **single** certificate in pem/dem encoding.

**Comment by bdovaz** [comment]
> What is the recommended way of replacing the now obsolete `X509Certificate.CreateFromSignedFile` (able to **extract** a certificate from a **signed** dll/exe file).
> 
> Because `X509CertificateLoader.LoadCertificateFromFile` is doing a complete different stuff => loads a **single** certificate in pem/dem encoding.

Same problem here...

**Comment by vcsjones** [comment]
For extracting "Authenticode" things, the new cert loader does not currently handle that. You should

1. Use `GetCertContentType` to check the payload is actually authenticode.
2. Suppress the obsoletion and use the constructor.

This comment from the preview 7 release notes shows an example: https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/libraries.md#changes-to-x509-certificate-loading

But, essentially:

```C#
X509ContentType actualType = X509Certificate2.GetCertContentType(data);

if (actualType != X509ContentType.Authenticode)
{
    throw new CryptographicException();
}

#pragma warning disable SYSLIB0057
using X509Certificate2 cert = new X509Certificate2(data);
#pragma warning restore SYSLIB0057

// use cert
```

**Comment by bdovaz** [comment]
@vcsjones how is it possible that there isn't an alternative that doesn't involve making use of the deprecated API and adding a supress? 💩

**Comment by ScotMac** [comment]
> What is the recommended way of replacing the now obsolete `X509Certificate.CreateFromSignedFile` (able to **extract** a certificate from a **signed** dll/exe file).
> 
> Because `X509CertificateLoader.LoadCertificateFromFile` is doing a complete different stuff => loads a **single** certificate in pem/dem encoding.

Yes, exactly what we need. I way to load all the certificates in a particular cert store file, both for PEM and P12.

**Comment by bartonjs** [comment]
> how is it possible that there isn't an alternative that doesn't involve making use of the deprecated API and adding a suppress?

Mostly because we thought almost no one was using that particular aspect of the API.  That has proven incorrect.  (However, no one has yet asked for any of the other formats that we dropped).  It also turns out the feature is ~wrong~ "less good than it could be".  Authenticode isn't only a single signer (some/many/most/all Microsoft-signed libraries are signed twice, once with Windows XP compatibility, and once with more modern choices), but the API only returns one (and for the Microsoft-signed ones, it's the older one, probably not the one you want).

**Comment by ScotMac** [comment]
@bartonjs Sorry, if i wasn't clear. I meant separate files. ie, an API for loading multiple certs in a p12 file into a X509Certificate2Collection, and a separate API for loading multiple certs in a PEM file into a x509Certificate2collection.

**Comment by ScotMac** [comment]
OK, so for a PEM file, Jeremy's suggestion was X509Certificate2Collection.ImportFromPem(ReadOnlySpan<Char>). However, the problem with that API is that it will only load the public certs in the file (hence the fact that it doesn't take a password). From the doc page for it:

"PEM-encoded items with a CERTIFICATE PEM label will be imported. PEM items with other labels will be ignored."

However, it does give us half the work needed: the public key certs.

So then, can we use the following to get the private key (password protected) cert:

X509Certificate2.CreateFromEncryptedPemFile()

So, then a combination of the above two methods might solve my problem, for PEM encoded files, giving me the public certs and the private key cert.

**Comment by GeorgDangl** [comment]
The Azure App Service docs still mention to use the now deprecated method: https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code?tabs=linux / https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/configure-ssl-certificate-in-code.md?plain=1#L177

But I didn't find a way to raise an issue in the docs repository, so I hope someone here knows how to get in contact. I can't do a PR since I didn't find out yet how to load private certificates with the new approach😀

**Comment by gewarren** [comment]
> The Azure App Service docs still mention to use the now deprecated method: https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code?tabs=linux / https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/configure-ssl-certificate-in-code.md?plain=1#L177
> 
> But I didn't find a way to raise an issue in the docs repository, so I hope someone here knows how to get in contact. I can't do a PR since I didn't find out yet how to load private certificates with the new approach😀

@msangapu-msft It looks like you're the author on that article. There are three examples that use an obsolete contructor for X509Certificate2.

**Comment by jhudsoncedaron** [comment]
Got here looking up the error message; realized my caller _doesn't care what type the certificate is_; upstream told me to verify the message content with the public key of this certificate and passed me the certificate body as a byte array. If they passed me a PKCS7 or X509 format or even an unecrypted PFX it's all fine to me. Either the public key signed the message or it didn't.

**Comment by vcsjones** [comment]
> doesn't care what type the certificate is

In that case, the recommendation is:

> If you are uncertain about the content type you are loading, X509Certificate2.GetCertContentType can be used to determine the content type and call the appropriate API.

> unecrypted PFX it's all fine to me. Either the public key signed the message or it didn't.

The concern is specifically about PFX / PKCS12. Beware that blinding accepting a PFX can use massive amounts of computational resources and can keep a CPU spinning for several minutes.

**Comment by jhudsoncedaron** [comment]
Well, given the certificate is received directly from the authoritative source over https I don't have to worry about a DOS attack. (Which is also why wrong kind is irrelevant. Certificate chain won't be validated anyway because I already know it's the right cert. Expiration will be validated.)

**Comment by GeorgDangl** [comment]
For us, the issue was in loading a self-issued certificate from within Azure App Service by loading the certificate file from `/var/ssl/private` into a `byte[]` and then later using it in the app to for signing options.
We didn't revisit the issue since January, but I seem to remember that we didn't find a way to just load the certificate except disabling the warning `SYSLIB0057` in the code and use the deprecated `new X509Certificate2(byte[])` constructor. I think we could not figure out how to determine the type of certificate, and got runtime exceptions with all approaches we tried.

**Comment by jhudsoncedaron** [comment]
@GeorgDangl : So what type was it? I'm really curious what type the constructor can load but the factory does not have. Especially because I may well have to replace the constructor call with a decision ladder in the future.

**Comment by bartonjs** [comment]
A map from the deprecated constructor to other public API is included in the sample at https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/libraries.md#changes-to-x509-certificate-loading

If you want to be fully general, you'd remove the expected format parameter and just call X509Certificate2.GetCertContentType to drive the switch.

**Comment by jhudsoncedaron** [comment]
@vcsjones : Found the counter-example. A pfx file that was generated without certificate privacy can be parsed for public key only without a password; but X509CertificateLoader won't *do* it.

**Comment by bartonjs** [comment]
> but X509CertificateLoader won't do it

Sure it will.

X509CerficateLoader.LoadPkcs12.  If you don't want to load private keys, use a custom Pkcs12LoaderLimits and set IgnorePrivateKeys to true.  If you believe that the public cert data isn't encrypted (though it usually is), you can also set IgnoreEncryptedAuthSafes.  With both of those set to true you're probably limited to about 200ms of CPU spinning before it decides it couldn't find any certs (because they were encrypted) and then throws an exception.

Maybe you mean "but X509CertificateLoader.LoadCertificate" won't do it.  Sure.  The entire point is no method reads more than one file format (though they will read both PEM and DER encodings, as appropriate).  PKCS#12-PFX (from PKCS#12/IETF RFC 7292) is different than X.509 Certificate (from ITU-T.Rec X.509 or IETF RFC 5280), so LoadCertificate won't load it.  It loads only the "Certificate" file format.  Which, yeah, is unfortunately what people call the generic version.

The tools are all available to you to write a flexible loader.  We just have declared the old one obsolete and will never write another.

**Comment by jhudsoncedaron** [comment]
Ok; now that's specific enough I can file a bug referencing only that.

**Comment by stevendarby** [comment]
The obsolete message is on the empty constructor:
https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.-ctor?view=net-9.0#system-security-cryptography-x509certificates-x509certificate2-ctor

What is the Loader alternative for the empty constructor? Or should this constructor not really be obsolete? I don't really understand the message - what does it being immutable have to do with whether I can create one or not? Also, your own code has had to ignore the warning.
https://github.com/dotnet/runtime/blob/11702c4619a9086bbf50b22af56b6777351bd6b0/src/libraries/Microsoft.Bcl.Cryptography/tests/X509Certificates/CertificateCreation/PrivateKeyAssociationTests.cs#L59

**Comment by bartonjs** [comment]
The default constructor creates an X509Certificate2 instance that is functionally the same as a valid instance that has been disposed.  What's the scenario where you want to call it?

> what does it being immutable have to do with whether I can create one or not?

The only real use for the default constructor was to create an instance and then call one of the "Import" methods.  But those methods have always unconditionally thrown exceptions on .NET Core/.NET 5+.

The import methods mutate the current instance (change it from representing no certificate, or "some certificate", to "some other certificate").  Them not functioning mean that X509Certificate2 is immutable (except for being disposed).

> Also, your own code has had to ignore the warning.

Yep.  Those tests are specifically testing that someone calling that constructor (from before it was obsolete) get the desired exceptions for the methods they're testing... as opposed to a process crash or an undocumented exception.  If you have a scenario where you want to call the default constructor, you can suppress the warning, too.
