### ISSUE TITLE
"Constants in C# are best defined as static members"

### ISSUE THREAD

**Issue by kevinfoley** [dotnet/docs#41677]
### Type of issue

Other (describe below)

### Description

This article includes this Note:

> The #define directive cannot be used to declare constant values as is typically done in C and C++. Constants in C# are best defined as static members of a class or struct. If you have several such constants, consider creating a separate "Constants" class to hold them.

Shouldn't this say that constants in C# are best defined with the [`const`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/const) keyword? Using static members has different implications for the application, since static members are resolved at runtime and are not necessarily read-only. For primitive values, `const` in C# is much closer to the behavior of `#define` in C/C++, since both are resolved at compile time.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/preprocessor-directives.md

### Document Version Independent Id

501be68d-5ad0-18d9-8958-54215bb57fc0

### Article author

@BillWagner

### Metadata

* ID: 716913e5-dbbe-bdb0-909a-4d8c2dc7be97 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Good observation @kevinfoley 

This section should be rewritten to clarify the distinction between pre-processor constants and `const` field members.
