### ISSUE TITLE
"quotation mark"

### ISSUE THREAD

**Issue by gggustafson** [dotnet/docs#41687]
### Type of issue

Other (describe below)

### Description

In the discussion of &lt;param&gt;, the phrase 
<pre>
    Enclose the name in double quotation marks (&quot; &quot;).
</pre>
implies that 
<pre>
    &lt;param name=&quot; &quot;name&quot; &quot;&gt;description&lt;/param&gt;
</pre>

is acceptable. It is not!

The problem is that over the years, programmers' poor US English has referred to the quotation mark as &quot;double quotes&quot;. I have no doubt that the author of this page has succumbed to this poor practice. The problem exists in eight places in this document and in myriad other places throughout MS documentation.

I suggest that &quot;double quotation marks&quot; be replaced by &quot;quotation marks&quot; and that (&quot; &quot;) be replaced with (&quot;).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/recommended-tags.md

### Document Version Independent Id

d135d0a6-53d2-1567-0b1b-7aae5e07739f

### Article author

@BillWagner

### Metadata

* ID: 3bcb925f-ef72-9a64-3762-c0b4a96f9dc4 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
This is a reasonable suggestion @gggustafson 

I've added it to our backlog, and I've added the "help wanted" label in case someone wants to submit a PR before we next update this article.

**Comment by gggustafson** [comment]
I need to talk with you about the abrupt closing of the T and N record issue (Issue #41597). It appear to have been closed by Cyrus Najmabadi. Please advise.

**Comment by BillWagner** [comment]
@gggustafson 

> I need to talk with you about the abrupt closing of the T and N record issue (Issue #41597).

I did see that. Cyrus is a member of the compiler team. I tagged him to verify that the current behavior is correct. It is. I closed for that reason. The docs say what does happen: the XML tags are emitted only when doc comments exist.

Cyrus also provided several alternatives to get the information you needed.

I'm not sure what else you expect.

**Comment by gggustafson** [comment]
The issue was becoming whether or not the requirements were valid. The discussion had gone beyond the documentation and had become one of the appropriateness of the compiler XML output.

I guess my question is now "how do I report this incomplete compiler output?"

**Comment by CyrusNajmabadi** [comment]
> I guess my question is now "how do I report this incomplete compiler output?"

Your feedback was reported.  We assessed it and determined that the behavior was as expected and will not be changing.  Suitable solutions were provided so that you can accomplish your end goal with the doc output of the compiler. 

You view this as 'incomplete'.  Your view is valid.  :)
We view it as working as intended.  Our view is valid. :)

If you need help using the other technologies we listed as appropriate for your problem space, we're happy to assist.

**Comment by gggustafson** [comment]
I do not normally respond in this manner. However, your attitude and disrespect are hallmarks of an individual who is too sure of himself and does not recognize when he is speaking gibberish. 

I have been programming for more than 60 years. I was a member of the X3J9 Pascal Technical Committee. I have been programming in C# since 2005 and before that in C. I am an evangelist for Microsoft since I found that MS provides a well-constructed and elegant (Visual Studio) platform on which to develop software.

However, no matter how carefully MS builds its software (in this case, C# compiler) there is always the non-vanishing probability of error. Errors exist in two varieties: those that are caused by the implementers of a requirement; those that are caused by a failure in the requirements themselves. The former are programmer errors. The latter are architectural errors. Both may exist for a long time before discovery - even 25 years.

The failure to produce T and N records means that I am not able to use the compiler generated XML document as input to my HTML producing program. There does not appear to be anyway to get the compiler-known namespace. I have a version of the program that performs a lexical scan of the source code and extracts the needed data. But the only way that I can get the namespace is through the .CSPROJ file's RootNamespace. (The only way that I can get the Assembly is through the .CSPROJ file's AssemblyName.)

IMHO, the failure to supply T and N records (and some type of record for the assembly name) in the compiler-generated XML is a requirements failure. It seems that MS's intent was to encourage programmers to document their code. Yet MS is not providing the necessary data to fulfill that intent.

You casually state "You can use our APIs. We have many you can use here. Reflection. Roslyn. Etc" You fail to realize that I am providing the user with the ability to choose C# files that are in a project file. I cannot use reflection! I do not plan to compile the C# files! So what APIs? What I need are the specifics that you fail to mention.

Note the web page for DataTable:
<pre>
    **DataTable Class**

        Reference

    **Definition**
    
        Namespace:  System.Data 
        Assembly:  System.Data.Common.dll
        Source:  DataTable.cs
</pre>
This and countless other web pages begin the same way. Using my own lexical scanner, I can obtain:
<pre>
    **BoyerMoore Class**

    **Definition**

        Namespace: Utilities
</pre>
Must I use my own software and access the CSPROJ file for other data? Today, I must! 

You are non-responsive to a valid issue with the compiler-generated XML.

**Comment by CyrusNajmabadi** [comment]
> The failure to produce T and N records means that I am not able to use the compiler generated XML document as input to my HTML producing program. 

Correct.  As stated, that's expected as there is no intent for the compiler to provide xml document entries for items that do not have doc comments on them.

If you need that information, we have APIs that you can use instead to get it.  We are happy to help you with that information.  As before, we do not intend to change the behavior here around xml documentation.  If you would like to discuss this more, we're happy to help over at our discord channels: https://discord.com/invite/tGJvv88

**Comment by CyrusNajmabadi** [comment]
> You fail to realize that I am providing the user with the ability to choose C# files that are in a project file. I cannot use reflection! I do not plan to compile the C# files! So what APIs?

As mentioned, Roslyn has apis here that you can use to get at this information without reflection.  

> I cannot use reflection!

That's why i mentioned both.  One that would work if you had an available built artifact you could introspect at runtime.  The other if you didn't, and needed to access this information from source alone.  If you'd like to discuss Roslyn more and how it can be used to get the information you need, please come to the discord link above and we can help you.
