### ISSUE TITLE
Create breaking change notice for BigInteger size limit

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#41752]
Seems like an opportunity to link to a breaking change notice. We should ensure one gets created if there isn't one yet.

_Originally posted by @richlander in https://github.com/dotnet/docs/pull/41745#discussion_r1676690163_
            

---
[Associated WorkItem - 292106](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292106)

**Comment by richlander** [comment]
@tannergooding
