### ISSUE TITLE
Typo in parameter name of a method

### ISSUE THREAD

**Issue by AminForozan** [dotnet/docs#41750]
### Type of issue

Typo

### Description

In the last example provided by the article, there is a typo in line 49 of the code. When initializing the second parameter of **SomeMethod**, the parameter name should be **num** instead of **nm** (look at line 46 in param tag, where the parameter name is written as num).
![issue](https://github.com/user-attachments/assets/ddc2b8b0-eca5-493f-b961-cb7b028cdef3)
[This is a link to the code I'm discussing on GitHub](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/snippets/xmldoc/idstrings.cs)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/index.md

### Document Version Independent Id

707b352c-ea51-494c-d4f1-33e140ab9d17

### Article author

@BillWagner

### Metadata

* ID: 5b320175-c9fe-d92e-748a-8cd511e7c12d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by krishchvn** [comment]
Hey. I've added a pull request fixing the typo. Please let me know if any other changes are required as well.
Happy to contribute!
