### ISSUE TITLE
<see> xml doc topic doesn't mention the href attribute 

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4176]
The syntax on the topic only shows `<see cref="member"/>` but not the see href syntax:
`<see href="url">link text</see>`

edit: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by eduard-malakhov** [comment]
@mairaw Is there a standard or another technical document we can refer to to make sure that that syntax is/must be supported too? I've made a quick research and here's what I found:

-  [Doxygen documentation](https://www.stack.nl/~dimitri/doxygen/manual/xmlcmds.html) only mentions the `<see cref=""/>` syntax;
- [Sandcastle](http://ewsoftware.github.io/XMLCommentsGuide/html/983fed56-321c-4daf-af16-e3169b28ffcd.htm) does mention `<see href=""/>` as a means to support external links; besides that, Sandcastle also supports the following: `<see langword=""/>`;
- In my VS2017 version 15.5.2 autocompletion only offers one option for `<see ...` and it's `<see cref=""/>` (although `<see href=""/>` is processed and emitted in the XML as expected).

So, there's definitely more than one view on this and we might need some reference to determine which one is correct.

I guess, if we are positive that `<see href=""/>` must be described in the programming guide, we might also want to fix autocompletion if VS. Also, shall we consider `<see langword=""/>` for the guide too?

**Comment by mairaw** [comment]
Good points @eduard-malakhov! I'm not sure about the technical docs that show the ones that must be supported. The docs here seem to match the common options covered in the C# spec: https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#recommended-tags

Yes, if we add see href, we should also add see langword. VS IntelliSense does recognize those even though it doesn't offer them as an option when you're doing the /// commments.

@BillWagner @jcouv @gafter any thoughts on this?

**Comment by eduard-malakhov** [comment]
@mairaw regarding this
>  VS IntelliSense does recognize those even though it doesn't offer them as an option when you're doing the /// commments.

I can say that in my VS2017 IntelliSense reports no errors even on the following code.

````
using System;

namespace ConsoleApp4
{
    /// <summary>
    /// <see attribute=""/>
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
````

![untitled](https://user-images.githubusercontent.com/6697045/35373086-1a6bb90e-01ae-11e8-8b19-5d521f87b402.png)

And even generates a documentation file.

````
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ConsoleApp4</name>
    </assembly>
    <members>
        <member name="T:ConsoleApp4.Program">
            <summary>
            <see attribute=""/>
            </summary>
        </member>
    </members>
</doc>
````

Is it possible that IntelliSense does not validate documentation comments?

**Comment by mairaw** [comment]
There were also some discussions around having the same docs available for VB. @KathleenDollard we'll need to sync to understand what are the options supported by VB.

**Comment by jcouv** [comment]
From my experimentation, it looks like VS supports `langword` (it is offered as completion, it has its own completion list and it is displayed nicely in QuickInfo).
For `href`, there doesn't seem to be any support at the moment (C#/VB compilers or VS). If other tools support it, then we should file a request in Roslyn repo to support in IDE).

**Comment by KathleenDollard** [comment]
Do we know anything about how much usage Doxygen and Sandcastle each get? 

I am a bit hesitant to include a feature that will be ignored by some tools.

**Comment by BillWagner** [comment]
> Do we know anything about how much usage Doxygen and Sandcastle each get?

No, and I'm not sure how we could get reliable info on their usage.

**Comment by mairaw** [comment]
Moving this to the backlog until this is officially supported in VS. /cc @BillWagner

**Comment by mfaux** [comment]
fyi, [DocFX](https://dotnet.github.io/docfx/spec/triple_slash_comments_spec.html) also supports `<see href="">`.

For example,

```
/// See <see href="https://github.com/dotnet/docs/issues/4176">issue #4176</see>.
```

...renders as:

![image](https://user-images.githubusercontent.com/1324114/53492584-7c389100-3a99-11e9-8823-a6ef37f226af.png)

**Comment by michael-hawker** [comment]
@mairaw @BillWagner any updates on fixing the support for this or the documentation?

**Comment by jozefizso** [comment]
It would be great to make the support for `href` attribute in `<see href=""/>` tag official.

**Comment by sharwell** [comment]
`href` isn't an officially supported attribute, but many tools support it anyway.

**Comment by erichiller** [comment]
I too would very much like to see this incorporated. For reference for anyone else coming across this issue, here's the related issues https://github.com/dotnet/csharplang/issues/1764 and https://github.com/dotnet/roslyn/issues/25671

**Comment by BillWagner** [comment]
reopening to address as part of the XML doc cleanup
