### ISSUE TITLE
Backreference topic does not mention \k<n> format

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#4178]
In the [Backreference topic](https://docs.microsoft.com/en-us/dotnet/standard/base-types/backreference-constructs-in-regular-expressions) and also in the [parent section](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#backreference_constructs) it describes backreferences like `\1` and like `\k<name>` and `\k'name'`. However it does not make clear that `\k<n>`, like `\n`, where n is a digit, is equivalent to the nth named capturing group iff that does not have a numerical name.

For example this is true because `\k<1>` matches the first named capturing group, `dog`, which is implicitly also the first numbered capturing group, `\1`:
```
Regex.IsMatch("aa", @"(?<dog>\w)\k<1>")
```
However this throws an exception "reference to undefined group number 1", because the first capturing group has a numerical name 2, so it doesn't get treated also as `\1`:
```
Regex.IsMatch("aa", @"(?<2>\w)\k<1>")
```

The docs do say:

`Note that name can also be the string representation of a number. For example, the following example uses the regular expression (?<2>\w)\k<2> to find doubled word characters in a string.`

But this doesn't make clear that numbers can refer to non-numeric names, as in the example I gave above.

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
Good catch! Thanks Dan!

**Comment by rpetrusha** [comment]
This seems to apply not only to \k\<n>, but also to \n.
