### ISSUE TITLE
API reference for HttpResponseMessage.EnsureSuccessStatusCode should say which exception is thrown

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4181]
[The API reference for `HttpResponseMessage.EnsureSuccessStatusCode`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode) says that it "throws an exception", but it doesn't say what is the type of the thrown exception.

Considering that the whole reason the method exists is to throw the exception, I think not saying which exception it is is a significant omission.

**Comment by rpetrusha** [comment]
It is certainly a blatant omission, @svick. The method throws an HttpRequestException.
