### ISSUE TITLE
Left outer join in C#

### ISSUE THREAD

**Issue by TonyAtTrio** [dotnet/docs#41854]
### Type of issue

Code doesn't work

### Description

The C# example in "Perform left outer joins" should contain a call to `DefaultIfEmpty`
I changed the third line to 
`.SelectMany(joinedSet => joinedSet.subgroup.DefaultIfEmpty(), (student, department) => new`

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/join-operations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/standard-query-operators/join-operations.md

### Document Version Independent Id

95b5cc6b-9612-6380-5dd4-b2efaac40732

### Article author

@BillWagner

### Metadata

* ID: 2ebd6c45-3cfb-ba5f-5d78-4728a948b598 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BillWagner** [comment]
Thanks @TonyAtTrio 

I've added this to our backlog, and added the "help wanted" label.
