### ISSUE TITLE
Include shorthand notation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#41858]
### Type of issue

Missing information

### Description

This article should mention the new shorthand notation of `_. Length` for `(fun x -> x.Length)`

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/lambda-expressions-the-fun-keyword

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/functions/lambda-expressions-the-fun-keyword.md

### Document Version Independent Id

5f6b0ad3-3761-efc7-7f78-5f22334a24f1

### Article author

@KathleenDollard

### Metadata

* ID: f10ac896-9ce5-935b-4b0f-123bcc5d5b6f 
* Service: **dotnet-fsharp**

**Comment by BartoszKlonowski** [comment]
I will work on this!
@BillWagner Please assign me if possible 🙏
