### ISSUE TITLE
XML comments are not always ignored by the compiler

### ISSUE THREAD

**Issue by cmdoffing** [dotnet/docs#41853]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
"XML documentation comments, like all other comments, are ignored by the compiler,"
XML doc comments are not ignored by the compiler when generating comments.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/xml-documentation.md

### Document Version Independent Id

788235a1-2b43-1607-b24b-57c0552fd890

### Article author

@KathleenDollard

### Metadata

* ID: 1a8fbc01-942f-ac15-e06b-2e50c45e8183 
* Service: **dotnet-fsharp**

**Comment by BillWagner** [comment]
This sentence should be reworded and clarified.
