### ISSUE TITLE
checked arithmetic in F#

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#41859]
### Type of issue

Missing information

### Description

This article should mention how to do checked arithmetic in F#.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/arithmetic-operators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/symbol-and-operator-reference/arithmetic-operators.md

### Document Version Independent Id

7138ba47-5fc4-6be0-9c0b-4d2a056a27ee

### Article author

@KathleenDollard

### Metadata

* ID: 2399bd5b-4110-2548-0dd1-6c353d7110bd 
* Service: **dotnet-fsharp**

**Comment by shethaadit** [comment]
Hi @BillWagner, I will raise the PR soon.
