### ISSUE TITLE
Access modifiers for top-level types documentation

### ISSUE THREAD

**Issue by albertiniandrea** [dotnet/docs#41870]
### Type of issue

Missing information

### Description

Hello, the page contains the following statement:

> "Top-level types, which are not nested in other types, can only have `internal` or `public` accessibility."

But at the end of the page there is an second statement witch is confusing me:

> "The `file` access modifier is allowed only on top-level (non-nested) type declarations."

Does this means that the first statement should be: "Top-level types, which are not nested in other types, can only have `internal`, `public` or **`file`** accessibility."?

Thank you and best regards

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md

### Document Version Independent Id

76a389f6-b568-3568-6483-6df440f96f0c

### Article author

@BillWagner

### Metadata

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Thanks for noting this @albertiniandrea 

I've opened a PR to address this issue. top-level types are allowed to have `file` access.
