### ISSUE TITLE
[New article]: Documentation for Workload Sets feature

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#41881]
### Proposed topic or title

.NET SDK Workload Sets

### Location in table of contents.

Probably near https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload

### Reason for the article

This is a new version for .NET9 and .NET 8.0.4xx. It will be opt-in in 8.0.4xx and opt-out in .NET 9. The documentation for `dotnet workload update` and `dotnet workload install` should probably be updated as well (or instead?)

### Article abstract

https://github.com/dotnet/designs/pull/294/files
## What are Workload Sets

Workload sets creates a single version number that represents a group of .NET SDK workloads. This allows you to install a specific version and stay on that version for more reliability. It allows you to install a combination of workloads that ship at the same time and are known to work together.

## Using Workload Sets

Workload sets will be published to nuget.org with each release of the .NET SDK under the package ID `Microsoft.NET.Workloads.<feature band>`

There are three different ways to use workload sets.

### Using the latest available workload set

To use the latest workload set, run `dotnet workload config --update-mode workload-set`, and then run `dotnet workload update`.  This should install the latest workload set available on the configured feeds. You can later switch back to the old mode of installing the latest version of each individual workload by using `dotnet workload config --update-mode manifests`

### Installing a specific workload set

You can use the `--version` parameter of the `dotnet update` or `dotnet install` command to specify a workload set version to install.  For example, `dotnet workload update --version 8.300.0-preview.0.24219.1`.

After you do this, installing a workload with `dotnet workload install` should no longer automatically update to a newer workload set.  However, if you run `dotnet workload update`, this will install the latest available workload set, and "unpin" you (though the SDK will still remain in workload set mode).

### Using global.json

You can create a `global.json` file to specify the workload set version for a repo.  The format looks like this:

```json
{
  "sdk": {
    "workloadVersion": "8.300.0-preview.0.24219.1"
  }
}
```

With the current directory under that repo, you can run `dotnet workload restore` to install the workload set.

## Checking the workload set version

To see the current workload set version, run `dotnet workload --version`.  If a workload set is installed, you will see a version such as `8.0.300-preview.0.24217.2` or `8.0.401`.  If there is no workload set version, then you will see a version in the form of `<feature band>-manifests.<hash>`, such as `8.0.400-manifests.45f976f0`.

**Comment by BasetsanaNjody** [comment]
Can it be merged?

**Comment by gewarren** [comment]
@tdykstra Do you want to take this one?

**Comment by tdykstra** [comment]
Sure

**Comment by tdykstra** [comment]
>This is a new version for .NET9 and .NET 8.0.4xx. It will be opt-in in 8.0.4xx and opt-out in .NET 9.

@marcpopMSFT Questions:
* This is a new version of what
* How do you opt in in 8.0.4xx
* How do you opt out in .NET 9
