### ISSUE TITLE
A link to ASP.NET Configuration Settings topic is broken (/docs/framework/configure-apps/index.md)

### ISSUE THREAD

**Issue by eduard-malakhov** [dotnet/docs#4191]
There's a link labeled **ASP.NET Configuration Settings** in `docs/framework/configure-apps/index.md` that leads to a MSDN page http://msdn.microsoft.com/library/116608f3-c03d-4413-9fc7-978703e18b0f which is "not longer available".

I suggest that we find the equivalent page in docs and fix the reference accordingly.

**Comment by mairaw** [comment]
Thanks @eduard-malakhov. We have tons of MSDN links and FwLinks that need to be reviewed (see related issues #2037 and #3391). It's a lot of legacy content so it takes time to go through them all. 

Probably for this specific link, the best replacement would be this content that we migrated: https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/web/index.md

**Comment by pkulikov** [comment]
@mairaw that link to Web settings schema says (emphasis is added by me):
>Web settings specify CPU and execution-level ASP.NET settings that apply to process-wide behavior managed by the ASP.NET hosting layer. **These settings differ from application domain-type settings that are specified in the Web.config file of an ASP.NET application**.

At the same time the broken link is in the section about [application configuration files](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/#application-configuration-files). In the context of ASP.NET I'd expect that link first lead to description of application-level Web.config file (plus the root Web.config, maybe) and only then to Web settings schema (by the way, why is that file in this repo but not in ASP.NET documentation repo?)

I've managed to find [this section](https://msdn.microsoft.com/en-us/library/ms178684.aspx) on msdn. That might be a better fix.

However, maybe [ASP.NET documentation](https://docs.microsoft.com/en-us/aspnet/) contains a good description of ASP.NET configuration files? Do you know anybody who might know? I've found the following links so far:
- https://docs.microsoft.com/en-us/aspnet/web-forms/overview/moving-to-aspnet-20/configuration-and-instrumentation
- https://docs.microsoft.com/en-us/aspnet/web-forms/videos/how-do-i/how-do-i-create-and-use-a-custom-configuration-section-in-an-aspnet-configuration-file
- https://docs.microsoft.com/en-us/aspnet/web-forms/videos/net-4/core/aspnet-4-quick-hit-clean-webconfig-files

The first one looks to be the best candidate.

**Comment by mairaw** [comment]
We just switched to the older version of that topic for now @pkulikov. I think we need to create an issue to review the ASP.NET config section more extensively. /cc @csharpfritz
