### ISSUE TITLE
Clarify how to set Nullable warnings or Nullable annotations as the default.

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [dotnet/docs#41921]
### Type of issue

Missing information

### Description

The page describes 4 choices in your project.

First 2 can be set by <nullable>Enable/disable</nullable> setting in the project.
It’s not clear how to setup Nullable warnings as the default and Nullable annotations as the default.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/nullable-migration-strategies.md

### Document Version Independent Id

99552131-8839-7c22-fcdc-2baa7722e756

### Article author

@BillWagner

### Metadata

* ID: fc516159-d7e1-46ba-7d31-538a0b811491 
* Service: **dotnet-csharp**
* Sub-service: **null-safety**

**Comment by BillWagner** [comment]
Hi @michael-freidgeim-webjet 

Thanks for pointing this out.

This article should mention the `Nullable` setting in the project file, and link to the section in the [compiler options](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/language#nullable) for that option.

I've added this to our backlog, and added the "help wanted" label if someone wants to submit a PR before we make our next update.
