### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#41927]
### Type of issue

Outdated article

### Description

Much of the information in this section is older and outdated. The corresponding content in the [standard](https://learn.microsoft.com/en-us/dotnet/standard/events/) section is more recent.

These articles could be deleted and redirected to that location.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines.md

### Document Version Independent Id

1fd093e9-f47c-ffdd-91e9-5039c3ccde61

### Article author

@BillWagner

### Metadata

* ID: 38e8321f-5516-e451-5429-750d49f0ebed 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this, and deliver the PR today or tomorrow.
