### ISSUE TITLE
Recommended action section is inconsistent with rest of page

### ISSUE THREAD

**Issue by dougclutter** [dotnet/docs#41951]
### Type of issue

Missing information

### Description

Most of this article is consistent in describing the breaking change that a call to `AddRateLimiter` is now required.

However, in the **Recommended action** section, this consistency is lost.  Instead, it says:
Ensure that `UseRateLimiter` is called at application startup.

I believe the text should be:
Ensure that `AddRateLimiter` is called at application startup.

Also, in the **Affected APIs** section, there is only a reference to `UseRateLimiter`.  There should also be a reference to `AddRateLimiter`.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/addratelimiter-requirement

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/8.0/addratelimiter-requirement.md

### Document Version Independent Id

c75a5103-a87a-79bc-0cda-885797fafe6a

### Article author

@gewarren

### Metadata

* ID: cefdc832-1157-9152-abdd-4f7c611eb3bf 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 292105](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292105)

**Comment by gewarren** [comment]
Thanks for catching that @dougclutter! I have a PR to fix it.
