### ISSUE TITLE
Confusing "Attribute" example

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#41960]
### Describe the issue or suggestion

Types that end with "Attribute" have special meaning. We should only use that for actual attributes.

```csharp
public class WeatherForecastWithPropertyNameAttribute
{
    public DateTimeOffset Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string? Summary { get; set; }
    [JsonPropertyName("Wind")]
    public int WindSpeed { get; set; }
}
```

How about `WeatherForecastWithCustomPropertyName`?

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-8-0#customize-individual-property-names

@eiriktsarpalis

**Comment by BartoszKlonowski** [comment]
@richlander I will work on this!
