### ISSUE TITLE
"Analyzers" command documentation is not correct

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/docs#42036]
### Type of issue

Code doesn't work

### Description

The documentation for "Style" and "Analyzers" commands is pretty much the same (which is fishy) and in both cases it's redirecting to https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ to select rules with the `--diagnostics ` option.

However,  `dotnet format  style --diagnostics IDE0005 --severity info` will work correctly (useless usings will be removed) but `dotnet format  analyzers --diagnostics IDE0005 --severity info` will have no effect.
 
Also, when you run `dotnet format --help` it's more explicit as `analyzers` command description is "Run 3rd party analyzers and apply fixes. "

So my understanding is that for Code Style rules (IDExxxx) we should use the `style` command and the documentation should reflect that.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-format.md

### Document Version Independent Id

51e52bf4-61b8-6f7d-d947-8bcd71c7bd7d

### Article author

@tdykstra

### Metadata

* ID: 009c8a6b-f784-7111-8662-43b2da30b0ab 
* Service: **dotnet-fundamentals**

**Comment by tdykstra** [comment]
@jairbubbles would you be interested in submitting a pull request to address this issue?
