### ISSUE TITLE
System.IO.FileSystemInfo.LastWriteTimeUtc docs says nullable?

### ISSUE THREAD

**Issue by JeffWhitledge** [dotnet/docs#4207]
The docs for System.IO.FileSystemInfo.LastWriteTimeUtc and several other related properties says:

> This property value is null if the file system containing the file does not support this information.

However the data type of the properties are just DateTime, which does not admit a null value. Is this an error? What should the value be?

**Comment by mairaw** [comment]
@JeremyKuhne, @pjanotti can you guys comment on this one? Thanks!

**Comment by JeremyKuhne** [comment]
If the file doesn't exist or if the underlying file system doesn't support the desired time type it returns the earliest Windows file time, the beginning of 1601, which is `DateTimeOffset.FromFileTime(0)`. The only additional special behavior is for CreationTime on Unix platforms that don't support creation (or "birth") time. In those cases you get back the oldest time between the last status change / modified. The `stat` command format sequences of `%w` (birth), `%x` (last access), `%y` (modification) and `%z` (status change).  Note that MacOS supports birth time by default.
