### ISSUE TITLE
WPF intro page confuses with Microsoft Framework Assistant

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4208]
This [WPF intro](https://docs.microsoft.com/en-us/dotnet/framework/wpf/index) page confuses me with the note:
>The Mozilla Firefox browser disables the Microsoft Framework Assistant extension. See How to remove the .NET Framework Assistant for Firefox for information on how to remove the extension from Firefox.

I think that note is not necessary on the welcome WPF page. Moreover, related information is covered [here](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/firefox-add-ons-to-support-net-application-deployment), see the end of the article.

If  that's the case, I'd be happy to delete this note.

And one more question: that intro mentions 'Visual Studio 2015'. Should it be changed to 'Visual Studio' or 'Visual Studio 2015 and later'?

**Comment by mairaw** [comment]
Thanks @pkulikov for your feedback. Yes, that is indeed weird. We should remove that.

For the 2015 thing, I'd just cut it out the version. 

And I'd also remove the modern from there since now UWP is our "modern" option (see PR #4088)
