### ISSUE TITLE
Дублирования слова "логические" в начале статьи ЛОГИЧЕСКИЕ ОПЕРАТОРЫ

### ISSUE THREAD

**Issue by MansurKing** [dotnet/docs#42104]
### Type of issue

Typo

### Description

[Введите отзыв здесь]
Дублирования слова "логические" в начале статьи
![image](https://github.com/user-attachments/assets/e54fbfd9-6cb0-45ab-8be2-1295d67c1026)

### Page URL

https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/boolean-logical-operators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/boolean-logical-operators.md

### Document Version Independent Id

91eaa72e-c2fc-e0d3-ca11-994aadf02271

### Article author

@pkulikov

### Metadata

* ID: 6d2d3240-ed65-94f2-335b-3ea483c51a5d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks for reporting this @MansurKing 

I've submitted an internal request here: https://dev.azure.com/ceapex/CEINTL/_workitems/edit/990495

I'll close this as it's been routed to our localization team.
