### ISSUE TITLE
Clarity and consistency in .NET version references (.NET 5 vs .NET 6)

### ISSUE THREAD

**Issue by anishsharma21** [dotnet/docs#42102]
### Type of issue

Typo

### Description

The following content is an excerpt from the .NET Implementations article:
```
There are four .NET implementations that Microsoft supports:

- .NET 6 and later versions
- .NET Framework
- Mono
- UWP
```

All but one subheading in the article aligns with the structure laid out in the content above. Specifically, the first subheading states ".NET 5 and later versions" rather than ".NET 6 and later versions". I believe this is a typo.

Suggested change:
```
There are four .NET implementations that Microsoft supports:

- .NET 5 and later versions
- .NET Framework
- Mono
- UWP
```

Alternatively, since .NET 5 is the unified version, and .NET 6 is the LTS version, there might be a deliberate distinction being made here - if so, it could be clarified with a section explaining the difference like so: 
```
.NET 5 is the first unified version, and .NET 6 is the current LTS version
```
I hope this helps :)

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/implementations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/implementations.md

### Document Version Independent Id

0b9ceffa-ccd9-d338-9dbe-752ac93bb2ad

### Article author

@dotnet-bot

### Metadata

* ID: edc3ae50-d51a-ae5d-6c95-b32852c973a9 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
Related to https://github.com/dotnet/docs/issues/42750.
