### ISSUE TITLE
The partial definitions don't need to be on different files.

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#42116]
### Type of issue

Missing information

### Description

Reading the definition, looks like the partial definitions of a type need to be on the different files and they don't.

Why would someone want to do that, is another story.

I think something like this would be better:

> Partial type definitions allow for the definition of a class, struct, interface, or record to be split into multiple partial definitions that can be in different files on the same project.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-type

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/partial-type.md

### Document Version Independent Id

a8d43580-fc8d-b3bb-2f43-e62d5ed9640c

### Article author

@BillWagner

### Metadata

* ID: 636f7992-54b7-5ff1-bd2e-44ec75ab8b53 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 297243](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297243)

**Comment by BillWagner** [comment]
Thanks @paulomorgado 

I've opened #42123 to address this.
