### ISSUE TITLE
Template package instructions refer to "Debug" directory when they should say "Release."

### ISSUE THREAD

**Issue by stevensrmiller** [dotnet/docs#42117]
### Type of issue

Typo

### Description

Text reading, "This command builds the project and creates a NuGet package in the working\bin\Debug folder..." should say, "This command builds the project and creates a NuGet package in the working\bin\Release folder..."

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-package

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-template-package.md

### Document Version Independent Id

1a94f1c8-0dd1-38a4-3c0c-db9c1ed0c1aa

### Article author

@adegeo

### Metadata

* ID: 8525c47c-370e-7b05-4160-360fe67b6734 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Thanks for reporting this! I'll get it fixed.
