### ISSUE TITLE
Add very brief examples for disambiguation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#42122]
### Type of issue

Missing information

### Description

This page is the F1 target for the `ref` keyword. The `ref` keyword can be used in many contexts. This page provides links to each of those contexts.

It would help readers to have a very brief example of each in order to know which link is correct for their current usage.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/ref.md

### Document Version Independent Id

4f413bcc-90e7-d971-fe75-b4876124e75d

### Article author

@BillWagner

### Metadata

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by bigboybamo** [comment]
Hi @BillWagner 
Wouldn't it be possible to just reference the examples in the links? Since those are the accepted examples?
Or new examples should be created?

**Comment by BillWagner** [comment]
@bigboybamo 

It's fine to use the same examples as the linked articles. However, I want to see them displayed in this page. A reader should be able to pick the right page without guessing and clicking to all of the linked pages.

Thanks for asking.

**Comment by bigboybamo** [comment]
Hi @BillWagner 
I opened a PR #42178
