### ISSUE TITLE
Write "file" instead of "Datei"

### ISSUE THREAD

**Issue by fklann** [dotnet/docs#42182]
### Type of issue

Typo

### Description

In der Übersicht befindet sich das Zugriffslevel "Datei". 
Ist das richtig oder sollte dort "file" stehen?

In der Übersichtstabelle wird auch das Zugriffslevel "file" verwendet.

### Page URL

https://learn.microsoft.com/de-de/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md

### Document Version Independent Id

76a389f6-b568-3568-6483-6df440f96f0c

### Article author

@BillWagner

### Metadata

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by gfoidl** [comment]
This "Datei"
> ![grafik](https://github.com/user-attachments/assets/a412a5e4-d4bb-40bd-a4f3-7cd261711bfa)
should actually be `file` as that's the language keyword.

So here too much got translated 😉.

**Comment by fklann** [comment]
Thank you :)
