### ISSUE TITLE
Document issues, limitations, and workarounds for the C# interactive experience

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4219]
# Document issues, limitations, and workarounds for the C# interactive experience

# General

Because the new C# REPL is interactive and users are free to modify and extend existing examples in unexpected ways, we should provide some guidance about issues users are likely to encounter and how to handle them. We can then link to this topic from any topic that uses the REPL.

Some of the topics that we should cover (and I'm sure there are many more):

1. Namespaces that are automatically imported.
2. What to do if a namespace isn't automatically imported:
   - Add a `using` statement if the example includes one or more classes in their entirety.
   - Use a fully qualified name if the example consists only of a fragment.
3. The current culture of the REPL is CultureInfo.InvariantCulture.
   - This is expected to change.
   - Show how to change the current culture.
4. Unless the example defines a namespace with the `namespace` statement, the REPL assigns a namespace name. It is reflected in APIs like Type.FullName.
6. The current time zone is UTC.
5. Console.ReadLine is a NOP (as you would expect).

@BillWagner @mairaw

**Comment by BillWagner** [comment]
Tagging @LadyNaggaga for her thoughts.

**Comment by LadyNaggaga** [comment]
@rpetrusha

- do you have an example on docs for the topic no. 2.  In the latest version of [Try .NET](https://try.dot.net/docs) you can configures default usings to send when running source code.  Is what you are looking for or something else ?

-  CultureInfo.InvariantCulture is on the backlog right now.  But is something I am looking to add into the next sprint.

**Comment by BillWagner** [comment]
Does this issue description need revisiting as the C# REPL has matured and changed capabilities?
/cc @jonsequitur

**Comment by BillWagner** [comment]
Moving to the April sprint (and milestone).  This is best handled with the updated experience in trial now.
