### ISSUE TITLE
Spanish version typo

### ISSUE THREAD

**Issue by ppaner00** [dotnet/docs#42216]
### Type of issue

Typo

### Description

In the left side panel, "apara" is a typo for the preposition "para". It should be "Procedimiento para llamar a un procedimiento que no devuelve un valor" rather than "Procedimiento apara llamar a un procedimiento que no devuelve un valor".

### Page URL

https://learn.microsoft.com/es-es/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-call-a-procedure-that-does-not-return-a-value

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/programming-guide/language-features/procedures/how-to-call-a-procedure-that-does-not-return-a-value.md

### Document Version Independent Id

756c3045-d4c9-23d6-9758-392bcc2bbee1

### Article author

@KathleenDollard

### Metadata

* ID: 18b45328-0b0d-93c8-3962-aa033dd942c4 
* Service: **dotnet-visualbasic**

**Comment by empty-codes** [comment]
Hello, please is this issue open? I would like to work on it.

**Comment by BillWagner** [comment]
Moved to the internal localization system.
