### ISSUE TITLE
The "Other usages of []" section lacks the list pattern (e.g `arr is [1, 2, ..]`).

### ISSUE THREAD

**Issue by VladiStep** [dotnet/docs#42212]
### Type of issue

Missing information

### Description

The "list patterns" are not included in ["Other usages of []"](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#other-usages-of-).
For example this - `arr is [1, 2, ..]` (`arr` starts with 1, 2).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/member-access-operators.md

### Document Version Independent Id

682b8c86-e49a-1d6d-8562-c9f919082bdc

### Article author

@pkulikov

### Metadata

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks @VladiStep That should be added.
