### ISSUE TITLE
 Unexpected failure of the "ApplyCompressionNegotiation" task.

### ISSUE THREAD

**Issue by fabiohcnobre** [dotnet/docs#42294]
### Type of issue

Typo

### Description

Unexpected failure of the "ApplyCompressionNegotiation" task.
System.InvalidOperationException: Endpoints not found for related asset: C:\Users\fabio\source\repos\metanetsistemas\MetaNetBI.Web\bin\Debug\net8.0\wwwroot\_framework\blazor.boot.json em Microsoft.AspNetCore. StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute() at Microsoft.Build.BackEnd.TaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

### Page URL

https://learn.microsoft.com/pt-br/dotnet/core/whats-new/dotnet-9/overview

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-9/overview.md

### Document Version Independent Id

8d2ad2b9-278a-c82f-633c-a891aa3d43c5

### Article author

@gewarren

### Metadata

* ID: 224f3e97-263e-6669-a76a-12210d1febae 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@fabiohcnobre Can you supply some more details about the issue you're having with .NET?
