### ISSUE TITLE
chess board

### ISSUE THREAD

**Issue by AvHarutyunyan** [dotnet/docs#42296]
### Type of issue

Typo

### Description

[Введите отзыв здесь]

### Page URL

https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/operator-overloading

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/operator-overloading.md

### Document Version Independent Id

5ec5c397-c7c6-700c-bc36-a8dfb2396dad

### Article author

@BillWagner

### Metadata

* ID: f91d85ae-8b37-e837-a031-144571362fbb 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Can you add more details here?
