### ISSUE TITLE
Type and Deconstruction Simultaneously

### ISSUE THREAD

**Issue by zms9110750** [dotnet/docs#42307]
### Type of issue

Missing information

### Description

I found a usage method that did not appear in the document.
```csharp
public abstract record Result<T> : IDisposable
{
	public sealed record Ok(T Value) : Result<T>;

	//...

	public T GetValueOrDefault()
	{
		switch (this)
		{
			case Ok(T Value):
				return Value;
		}
		return default(T)!;
	}
//...
}
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md

### Document Version Independent Id

312e9c81-ee2a-1d84-64d7-bcaa71d7eab8

### Article author

@BillWagner

### Metadata

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @zms9110750 

Can you add an example where this is useful? I find the code interesting, but I'm not seeing a scenario where I'd use it in practice.

**Comment by zms9110750** [comment]
> 你好@zms9110750
> 
> 您能添加一个有用的例子吗？我发现代码很有趣，但我没有看到在实践中使用它的场景。

I just saw this grammar (here)[https://github.com/marinasundstrom/OptionAndResultConcept/blob/main/ResultAndOption/Result.cs]
I didn't realize this grammar until then, and the document didn't introduce it. So I think he should be supplemented.
I don't know the usage scenarios in practice, so I can't answer you.

**Comment by zms9110750** [comment]
If the positional pattern relies entirely on  Deconstruct, I think it would be better to directly change the title to  Deconstruct pattern.

**Comment by zms9110750** [comment]
@BillWagner hi?

**Comment by BillWagner** [comment]
Hi @zms9110750 

Thanks for tagging me in that comment. I missed the earlier once, and it looks like one of our bots didn't restore labels correctly on your last comment.

I see your point. I'm not going to change the name. We chose that to match the name used in the specification. However, I did add a callout on the importance of order.
