### ISSUE TITLE
Relaxed shift operator requirements of C# 11 not in Shift count of the shift operators

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42311]
### Type of issue

Outdated article

### Description

From https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#generic-math-support

> relaxed shift operator requirements: **C# 11 removes the requirement that the second operand must be an int or implicitly convertible to int**. This change allows types that implement generic math interfaces to be used in these locations.

From 

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators

> For the built-in shift operators <<, >>, and >>>, the type of the **right-hand operand must be int or a type that has a predefined implicit numeric conversion to int**.

_Shift count of the shift operators_ article is outdated.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#unsigned-right-shift-operator-

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/bitwise-and-shift-operators.md

### Document Version Independent Id

2410c828-0c66-9efe-ae87-9b07708aa731

### Article author

@pkulikov

### Metadata

* ID: 02b8f7c2-379e-7876-0d36-25b06a294baa 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks @bravequickcleverfibreyarn 

I had missed making this update when I added this feature. I've put it in our backlog to update. We'll make the fix in our next update on this article.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this one!
