### ISSUE TITLE
Mistake that static events are weak

### ISSUE THREAD

**Issue by jinek** [dotnet/docs#4235]
# Mistake that static events are weak

There is a mistake on this page: https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.commandmanager.requerysuggested?view=netframework-4.7.1
It says "Since this event is static, it will only hold onto the handler as a weak reference" that is mistake.
Static events has only one difference from instance events - they are static.

**Comment by svick** [comment]
It's not a mistake. `RequerySuggested` is not a simple `static` `event`, it has [custom implementation](http://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Input/Command/CommandManager.cs,39) that makes it a variant of weak event.

For example, consider this code:

```c#
class C
{
    public void Handler(object s, EventArgs e)
    {
        ((MainWindow)Application.Current.MainWindow).TextBlock.Text += "Event raised. ";
    }
}

private void WithoutGcButton_OnClick(object sender, RoutedEventArgs eventArgs)
{
    CommandManager.RequerySuggested += new C().Handler;

    CommandManager.InvalidateRequerySuggested();
}

private void WithGcButton_OnClick(object sender, RoutedEventArgs eventArgs)
{
    CommandManager.RequerySuggested += new C().Handler;

    GC.Collect();

    CommandManager.InvalidateRequerySuggested();
}
```

If I press the button whose `Click` event is wired to the `WithGcButton_OnClick` handler, no text is added to `TextBlock`, which indicates the event is indeed weak.

Though one way of reading the documentation would imply that *all* `static` `event`s are automatically weak. That's not true and so I think the documentation could be clarified.

**Comment by jinek** [comment]
Ok, so probably mention of "static" should be removed, otherwise reader can think that every static event has weak implementation.

"Since this event is static, it will only hold onto the handler as a weak reference"
can be changed for example to
"This event uses WeakEventManager and does not hold a strong reference to the subscriber"
