### ISSUE TITLE
.csproj options are below the fold

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/docs#42355]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
I found it confusing/surprising that I had to scroll to find how to set these options in the .csproj file, which is the only way I know to put them in force in Visual Studio. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md

### Document Version Independent Id

e57ac82b-307e-163b-8172-52644b3a6baa

### Article author

@BillWagner

### Metadata

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
@KathleenDollard 

Let's discuss this one.  The bullet list shows the csproj / msbuild syntax in **Bold**, with the csc syntax in `code font`. Is there a better presentation that highlights the csproj syntax?

**Comment by KathleenDollard** [comment]
There was some misreading on my part here. Yes, the values are there, explained in bold. 

I think it would be helpful to mention .csproj (and .vbproj where appropriate) or the project file syntax immediately below the list. Maybe it was just me, and the fact I read past `TreatWarningsAsErrors` (still having some vision issues), but I didn't register that those were the .csproj values.

**Comment by BillWagner** [comment]
I was wondering if that was it when I looked again. I'd used bold to highlight them, but that makes in not obvious that it's the name of the csproj key. I'll recommend putting both syntaxes in a code font, and adding anchors to each option section.

I'd consider a 3 column table as well:  name / function, csproj syntax, csc flag.

Adding to our backlog, and adding the help wanted tag.

**Comment by samwherever** [comment]
@BillWagner i can work on this - before i start, i wanted to ask if the csc flag for AnalysisLevel is just `-analysislevel`
