### ISSUE TITLE
sc1024 preprocessor directive expected

### ISSUE THREAD

**Issue by blisada** [dotnet/docs#42410]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
sc1024 preprocessor directive expected

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1024

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1024.md

### Document Version Independent Id

f38287f8-ed77-2147-7935-a981be58dd15

### Article author

@BillWagner

### Metadata

* ID: ff65be67-852d-a862-5f09-be4c720e005b 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Hi @blisada 

Do you have any additional details to share on this issue? I'm not sure what you're asking for.
