### ISSUE TITLE
Disabling 'missing xml' notification

### ISSUE THREAD

**Issue by CoolGoose** [dotnet/docs#4242]
I've initially opened [this ](https://github.com/aspnet/Docs/issues/5298) on the aspnet docs regarding the swagger integration.
The error itself is _Missing XML comment for publicly visible type or member_ and can easily be disabled with `<noWarn>1591</noWarn>` in csproj. 

My question is.
1. Where should i create a new doc ? Visual Basic has a listing with [Error Messages](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/) but I can't find anything like that for .NET core .
2. Any tips on how I should tackle the issue ? For me right now it's only because of the swagger integration, any other quick practical examples i could link to ?

**Comment by mairaw** [comment]
So right now we cover this here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings 

We are planning on having a topic that is a .NET Core SDK project reference which would cover the different elements of a project file which would include the `noWarn` as well. We're tracking that with issue #2642.

**Comment by CoolGoose** [comment]
hi @mairaw thanks for the quick reply. Should i wait until that's merged and see then if it has 1591 or is it a brach i can do a pull request ?

**Comment by mairaw** [comment]
@CoolGoose maybe we're talking about different things. The topic on #2642 would just cover the nowarn tag and how you disable warnings.

1591 is covered separately here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591

Is that the topic you're looking for?

**Comment by CoolGoose** [comment]
@mairaw #2642 is the one. Regarding https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591 maybe just have a notice telling people how to disable it once #2642 is ready ?
