### ISSUE TITLE
Can't run 'dotnet run' command out of the box

### ISSUE THREAD

**Issue by yupitomets** [dotnet/docs#4243]
# Issue Title

Can't run 'dotnet run' command out of the box

# General

I am trying to follow this tutorial. All previous steps were good, but "dotnet run" command give an error.

dotnet : It was not possible to find any compatible framework version
At line:1 char:1
+ dotnet run
+ 
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.0.5'.

**Comment by JRAlexander** [comment]
@yupitomets, which tutorial?

**Comment by mairaw** [comment]
@yupitomets since we haven't heard back from you, I'll be closing this issue. If you can provide more information about which tutorial you were following, we can reopen this issue and try to help you. Thanks.
