### ISSUE TITLE
First example missing usage example of passing a parameter by ref.

### ISSUE THREAD

**Issue by MaxMahem** [dotnet/docs#42499]
### Type of issue

Missing information

### Description

The first bullet says:
> In a method signature and in a method call, to pass an argument to a method [by reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#ref-parameter-modifier).

But the following example doesn't show passing a parameter by `ref`. The logic in the example is right and shows how a struct value will *not* change if passed by value, but an example showing how to pass a parameter by `ref` would probably be more helpful.

Perhaps adding a method like:
```cs
static void TakeStructByRef(ref TheStruct s)
{
    s.willIChange = "Changed";
}
```

Would be useful.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/ref.md

### Document Version Independent Id

4f413bcc-90e7-d971-fe75-b4876124e75d

### Article author

@BillWagner

### Metadata

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 320285](https://dev.azure.com/msft-skilling/Content/_workitems/edit/320285)

**Comment by BillWagner** [comment]
It looks like the wrong sample was included here. That sample is for a different article that explains the differences between by value and by reference.
