### ISSUE TITLE
Missing Hyperlink

### ISSUE THREAD

**Issue by S-Dhir** [dotnet/docs#42503]
### Type of issue

Missing information

### Description

[Enter feedback here]
The text here is written in a way that makes it seem like a hyperlink. Perhaps a link is missing?
![image](https://github.com/user-attachments/assets/dc70831b-c9f8-4c5b-878c-92ed67527ffb)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/extern.md

### Document Version Independent Id

36fe06a7-9727-f040-b6ea-5658c949605c

### Article author

@BillWagner

### Metadata

* ID: 86ea7f1e-1fc2-9168-e1af-cae0f40186dd 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Thanks for noting this @S-Dhir 

I've opened a PR to add the link.
