### ISSUE TITLE
Content maybe not correct

### ISSUE THREAD

**Issue by wenshisan** [dotnet/docs#42549]
### Type of issue

Typo

### Description

record 或 record class 声明引用类型。 class 关键字是可选项，但可以为读者提高清晰度。 record struct 声明值类型。
位置属性在 和 readonly record struct 中不可变。 它们在 中可变。
[在此处输入反馈]
record 或 record class 声明引用类型。 class 关键字是可选项，但可以为读者提高清晰度。 record struct 声明值类型。
位置属性在 和 readonly record struct 中不可变。 它们在???中可变。

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/record

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md

### Document Version Independent Id

de1f383b-ef20-4776-57a8-04edae892166

### Article author

@BillWagner

### Metadata

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @wenshisan 

It appears that source English has been translated incorrectly.

I've reported this to our localization team on their internal tracking system. Thank you for reporting it.

I'll close this issue as the original text is correct.
