### ISSUE TITLE
The docs should be clearer that on Linux a finally block will not fire if there is an uncaught exception

### ISSUE THREAD

**Issue by mjwills-k** [dotnet/docs#42565]
### Type of issue

Typo

### Description

"In almost all cases finally blocks are executed." downplays a potential risk in Linux.

https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/zwc8s4fz(v=vs.100)?redirectedfrom=MSDN is clearer in this regard:

"If the exception is not caught, execution of the finally block depends on whether the operating system chooses to trigger an exception unwind operation."

Repro:

https://dotnetfiddle.net/S3TXOq

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/exception-handling-statements#the-try-finally-statement

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/exception-handling-statements.md

### Document Version Independent Id

70157b9c-983b-3916-ce95-99f265dfed6d

### Article author

@BillWagner

### Metadata

* ID: 9f85cb65-ded0-a342-4a86-04826af92da3 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
I like that suggestion @mjwills-k 

I've added this to our backlog, and added the "help wanted" label if anyone wants to submit a PR before we update this article.

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!
