### ISSUE TITLE
Sample Data Source cannot be located

### ISSUE THREAD

**Issue by shaazanaam** [dotnet/docs#42599]
### Type of issue

Missing information

### Description

[Enter feedback here]
Cannot find the sample data set for the type STUDENT/ TEACHER/ DEPARTMENT
Here is the Link to the page https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/join-operations.

Eventhough the page does mention the following verbage right above the code snippet where  the type definition is presented
"The following examples in this article use the common data sources for this area:"

[https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/join-operations](url)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/join-operations

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/standard-query-operators/join-operations.md

### Document Version Independent Id

95b5cc6b-9612-6380-5dd4-b2efaac40732

### Article author

@BillWagner

### Metadata

* ID: 2ebd6c45-3cfb-ba5f-5d78-4728a948b598 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BartoszKlonowski** [comment]
@BillWagner I will handle that!
