### ISSUE TITLE
problems with instalatio SDK

### ISSUE THREAD

**Issue by maximiano55** [dotnet/docs#42596]
### Type of issue

Other (describe below)

### Description

I downloaded the .NET 8.0 SDK version (v8.0.401) - Windows x64 Installer!

Masw on the lines line when I put:
dotnet --info

always gives this error:
Host:
 Version: 8.0.8
 Architecture: x86
 Commit: 08338fcaa5
 RID: win-x86

**.NET SDKs installed:
 In the SDKs were found.**

.NET runtimes installed:
 Microsoft.AspNetCore.App 6.0.33 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.AspNetCore.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 6.0.19 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 6.0.33 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
 Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
 Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
 Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other Architectures Found:
 x64 [C:\Program Files\dotnet]
 registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
 Not set

global.json file:
 Not Found

Learn more:
 https://aka.ms/dotnet/info

And when I try to install the extensions on VS code always gives me this error:

Failed to restore NuGet packages for the solution.
[Escreva aqui os seus comentários]

### Page URL

https://learn.microsoft.com/pt-pt/dotnet/core/get-started

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/get-started.md

### Document Version Independent Id

fdb655a4-cff4-6c67-7244-673760379663

### Article author

@adegeo

### Metadata

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Hey @maximiano55 sorry this issue slipped through the cracks. I'm assuming you already got this fixed? It looks like you have both x64 and x86 versions of .NET installed, and the x86 version is being resolved first. See this for more information: https://learn.microsoft.com/pt-pt/dotnet/core/install/windows#no-net-sdk-was-found

I'm going to close this issue as I think it will solve your problem.
