### ISSUE TITLE
Probably unintended double negation

### ISSUE THREAD

**Issue by mattiasnordqvist** [dotnet/docs#42621]
### Type of issue

Typo

### Description

![image](https://github.com/user-attachments/assets/3dfe160e-99b1-4671-a31b-b35912f13899)
 Are these double negations intended?
 Should I _avoid_ to _not_ "... use overloads that don't explicitly or implicitly specify the string comparison rules for string operations"?

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/best-practices-strings.md

### Document Version Independent Id

fe538551-dcfc-c244-3f16-864d3f6c2a6e

### Article author

@adegeo

### Metadata

* ID: dead2df6-1ec5-b55c-89aa-d05a7a75a0eb 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
This one feels tough. I'm not totally sure for either side. Both ways would make sense to me, but if you were skimming the article you may be tripped up by a positive in the list of negatives. Each items also stands alone. I think it should remain as-is.

Some further thoughts:

You could merge both lists and introduce them appropriately:

- Do ...
- Do ..
- Do ..
- Do ..
- Don't ...
- Don't ...

However, their are a lot more **Do** than **Don't**, which may make it harder for the **Don't** to stand out, hence a paragraph break between the two lists.

If you wanted to open a pull request to adjust these, I'm fine with it, but I don't think this is a priority for us at the moment as I think it's clear enough. Thank you for the suggestion!
