### ISSUE TITLE
[Breaking change]: New TimeSpan.From overloads that take integers

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/docs#42631]
### Description

https://github.com/dotnet/runtime/pull/98633

### Version

.NET 9 RC 1

### Previous behavior

Before .NET 9 there was a version with one float parameter

### New behavior

Now the following F# code throws an overload error: `TimeSpan.FromMinutes(20)`

> error FS0041: A unique overload for method 'FromMinutes' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: intCandidates: - TimeSpan.FromMinutes(minutes: int64) : TimeSpan - TimeSpan.FromMinutes(minutes: int64, ?seconds: int64, ?milliseconds: int64, ?microseconds: int64) : TimeSpan - TimeSpan.FromMinutes(value: float) : TimeSpan

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries might encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [X] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code might require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries might behave differently at run time.

### Reason for change

https://github.com/dotnet/runtime/issues/93890

### Recommended action

Specify the compiler what type of argument is being used so that the appropriate overload is selected

### Feature area

Core .NET libraries

---
[Associated WorkItem - 314593](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314593)

**Comment by terrajobst** [comment]
@gewarren what tags do we need for documenting a known source breaking change?

**Comment by gewarren** [comment]
> @gewarren what tags do we need for documenting a known source breaking change?

This looks good. I'll write up a doc next week.
