### ISSUE TITLE
Assembly types created does not match expected type and trims FullName property.

### ISSUE THREAD

**Issue by xmione** [dotnet/docs#42661]
### Type of issue

Other (describe below)

### Description

It is finally great to have this class to be able to dynamically create and save the dll. My concern though is that the created type does not match the expected type when it has generic parameters. For example, it trims the FullName property to it's base type name and removes the generic parameters from it. To illustrate this, I've created a sample code that uses .net 9.0 preview 7 and nuget package Blazor.Tools.BlazorBundler version 3.1.2. 've created this link in .netfiddle and Github. Although you can't run it in .NetFiddle because it only supports up to .net 8, but you can run it using the Github Codespace I've created. Here are the links:

[.NetFilddle](https://dotnetfiddle.net/SsZFyo) 
[Github Code Repository](https://github.com/xmione/PersistedAssemblyBuilder.ConsoleApp)
[GitHub Codespace](https://ominous-carnival-wr9g6p7prq526wj.github.dev/)
```


// Used .net 9.0 Preview 7 framework for this and nuget package Blazor.Tools.Bundler version 3.1.2 (just updated)
using System;
using System.IO;
using System.Reflection;
using System.Reflection.Emit;
using Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models;
using Blazor.Tools.BlazorBundler.Extensions;
using Blazor.Tools.BlazorBundler.Interfaces;
using Blazor.Tools.BlazorBundler.Utilities.Exceptions;

public class Program
{
    public static void Main(string[] args)
    {
        DynamicallyCreateAssembly();
    }

    private static void DynamicallyCreateAssembly()
    {
        try 
        {
            var contextAssemblyName = "Blazor.Tools.BlazorBundler.Interfaces";
            var assemblyFileName = $"{contextAssemblyName}.dll";
            var version = "1.0.0.0";
            var iViewModelTypeName = $"{contextAssemblyName}.IViewModel`2";
            var tempPath = Path.GetTempPath();
            var dllFilePath = $"{tempPath}.{contextAssemblyName}.dll";
            var employeeTypeAssemblyName = "Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models";
            var employeeTypeName = $"{employeeTypeAssemblyName}.Employee";
            var iModelExtendedPropertiesTypeName = $"{contextAssemblyName}.IModelExtendedProperties";

            // Define the types for generic parameters
            Type modelType = typeof(Employee);
            Type modelExtendedPropertiesType = typeof(IModelExtendedProperties);

            // Create the assembly and module
            AssemblyName assemblyName = new AssemblyName(contextAssemblyName) { Version = new Version(version) };
            PersistedAssemblyBuilder assemblyBuilder = new PersistedAssemblyBuilder(assemblyName, typeof(object).Assembly);
            ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule(assemblyFileName);

            // Define the generic type
            TypeBuilder typeBuilder = moduleBuilder.DefineType(
                iViewModelTypeName,
                TypeAttributes.Public | TypeAttributes.Interface | TypeAttributes.Abstract,
                null
            );

            // Define the generic parameters (without earlier techniques that did not work)
            GenericTypeParameterBuilder[] genericParamBuilders = typeBuilder.DefineGenericParameters(
                $"{employeeTypeName}",
                $"{iModelExtendedPropertiesTypeName}"
            );

            // Create the type
            Type createdType = typeBuilder.CreateTypeInfo().AsType();

            // Save the assembly to disk
            assemblyBuilder.Save(dllFilePath);

            // Load the dll file assembly using dll path extension method 
            var assembly = Assembly.LoadFile(dllFilePath);
            Type loadedType = assembly.GetType(createdType.FullName ?? string.Empty) ?? throw new InvalidOperationException("Loaded type is null.");

            // Construct expected type definition
            var expectedType = typeof(IViewModel<Employee, IModelExtendedProperties>);

            // Compare full names
            string createdTypeFullName = createdType.FullName ?? string.Empty;
            string loadedTypeFullName = loadedType.FullName ?? string.Empty;
            Console.WriteLine($"Expected Full Name: {expectedType.FullName}");
            Console.WriteLine($"Created Full Name: {createdTypeFullName}");
            Console.WriteLine($"Loaded Full Name: {loadedTypeFullName}");

            loadedType.DisplayTypeDifferences(expectedType);

            // Check if they match
            bool match = createdTypeFullName == expectedType.FullName && loadedTypeFullName == expectedType.FullName;
            Console.WriteLine(match ? "The types match." : "The types do not match.");
        }
        catch (Exception ex) 
        {
            AppLogger.WriteInfo(ex.Message);
        }
        
    }
}


```
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-reflection-emit-persistedassemblybuilder

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/runtime-libraries/system-reflection-emit-persistedassemblybuilder.md

### Document Version Independent Id

205f36d2-e637-bae1-4ec6-984fc74c83c9

### Article author

@gewarren

### Metadata

* ID: 1c23ff20-338c-bff1-8c8b-e7b491016503 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@buyaa-n Can you take a look at this feedback?

**Comment by buyaa-n** [comment]
> I've created this link in Replit
> https://replit.com/join/mgufadlhrk-solomiosisante

@xmione please paste the sample code in the issue, that link is restricted

**Comment by xmione** [comment]
> > I've created this link in Replit
> > https://replit.com/join/mgufadlhrk-solomiosisante
> 
> @xmione please paste the sample code in the issue, that link is restricted, inaccessible

Hi! I just updated the post with the link to .NetFiddle and the code itself.

**Comment by buyaa-n** [comment]
Well apparently it is emitted what you wrote:
```cs
public interface IViewModel<Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models.Employee, Blazor.Tools.BlazorBundler.Interfaces.IModelExtendedProperties>
{
}
```
Except this is not how you create a generic type parameter, especially not for c#. I suggest you to learn: https://learn.microsoft.com/dotnet/fundamentals/reflection/how-to-define-a-generic-type-with-reflection-emit this doc is little outdated, the examples are written for .NET framework, though it should work pretty much after changing the `AssemblyBuilder` creation to `PersistedAssemblyBuilder`

> var iViewModelTypeName = $"{contextAssemblyName}.IViewModel`2";

No need to add `` `2`` to the generic type name

Closing as this is not a real issue or bug

**Comment by xmione** [comment]
> Well apparently it is emitted what you wrote:
> 
> ```cs
> public interface IViewModel<Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models.Employee, Blazor.Tools.BlazorBundler.Interfaces.IModelExtendedProperties>
> {
> }
> ```
> 
> Except this is not how you create a generic type parameter, especially not for c#. I suggest you to learn: https://learn.microsoft.com/dotnet/fundamentals/reflection/how-to-define-a-generic-type-with-reflection-emit this doc is little outdated, the examples are written for .NET framework, though it should work pretty much after changing the `AssemblyBuilder` creation to `PersistedAssemblyBuilder`
> 
> > var iViewModelTypeName = $"{contextAssemblyName}.IViewModel`2";
> 
> No need to add `` `2 `` to the generic type name
> 
> Closing as this is not a real issue or bug

Hi, Thanks for responding.
This is supposed to be the Expected type's Full Name: Blazor.Tools.BlazorBundler.Interfaces.IViewModel`2[[Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models.Employee, Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null],[Blazor.Tools.BlazorBundler.Interfaces.IModelExtendedProperties, Blazor.Tools.BlazorBundler.Interfaces, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null]]

But it truncated the type's Full Name to this: 
Blazor.Tools.BlazorBundler.Interfaces.IViewModel`2

**Comment by buyaa-n** [comment]
What I meant it the full name is incorrect because you are creating and using the generic type incorrectly

> var expectedType = typeof(IViewModel<Employee, IModelExtendedProperties>);

For example could you share the expected `IViewModel` type definition as in c#?

**Comment by xmione** [comment]
> What I meant is the full name looks incorrect because you are creating and using the generic type incorrectly
> 
> > var expectedType = typeof(IViewModel<Employee, IModelExtendedProperties>);
> 
> For example could you share the expected `IViewModel` type definition as in c#?

Hi @buyaa-n,

Thanks for your patience. I've just edited the post and added the base class and interface types.
I'm sorry it's kinda complex.

Thanks for helping anyways.

**Comment by buyaa-n** [comment]
Looks what you are trying to define is:
```cs
public interface IViewModel<TModel, TIModel> : IModelExtendedProperties
{
}
```
but what you defined now is:
```cs
public interface IViewModel<Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models.Employee, Blazor.Tools.BlazorBundler.Interfaces.IModelExtendedProperties>
{
}
```
Hope you are seeing what is wrong here, and further a type definition is not equivalent of getting a type instance with typeof operator, i.e generated `TypeBuilder` is not equivalent to `typeof(IViewModel<Employee, IModelExtendedProperties>);`

**Comment by xmione** [comment]
> string[] typeParamNames = {"TModel", "TIModel"};
>             GenericTypeParameterBuilder[] typeParams = typeBuilder.DefineGenericParameters(typeParamNames);
> 
>             GenericTypeParameterBuilder TModel = typeParams[0];
>             GenericTypeParameterBuilder TIModel = typeParams[1];
> 
>             // Apply constraints to the type parameters.
>             //
>             // A type that is substituted for the first parameter, TModel,
>             // must be a reference type and must have a parameterless
>             // constructor.
>             TModel.SetGenericParameterAttributes( GenericParameterAttributes.DefaultConstructorConstraint | GenericParameterAttributes.ReferenceTypeConstraint);
> 
>             // A type that is substituted for the second type
>             // parameter must implement IExampleA and IExampleB, and
>             // inherit from the trivial test class ExampleBase. The
>             // interface constraints are specified as an array
>             // containing the interface types.
>             TIModel.SetBaseTypeConstraint(baseType);
>             Type[] interfaceTypes = {modelExtendedPropertiesType};
>             TIModel.SetInterfaceConstraints(interfaceTypes);

Oh, you did not see this?

```
            string[] typeParamNames = {"TModel", "TIModel"};
            GenericTypeParameterBuilder[] typeParams = typeBuilder.DefineGenericParameters(typeParamNames);

            GenericTypeParameterBuilder TModel = typeParams[0];
            GenericTypeParameterBuilder TIModel = typeParams[1];

            // Apply constraints to the type parameters.
            //
            // A type that is substituted for the first parameter, TModel,
            // must be a reference type and must have a parameterless
            // constructor.
            TModel.SetGenericParameterAttributes( GenericParameterAttributes.DefaultConstructorConstraint | GenericParameterAttributes.ReferenceTypeConstraint);

            // A type that is substituted for the second type
            // parameter must implement IExampleA and IExampleB, and
            // inherit from the trivial test class ExampleBase. The
            // interface constraints are specified as an array
            // containing the interface types.
            TIModel.SetBaseTypeConstraint(baseType);
            Type[] interfaceTypes = {modelExtendedPropertiesType};
            TIModel.SetInterfaceConstraints(interfaceTypes);
 ```           
            As you can see, I followed the documentation in the link that you shared. That's how it says to make the generic parameters. It should be doing this according to the documentation:
```
public interface IViewModel<Blazor.Tools.BlazorBundler.Entities.SampleObjects.Models.Employee, Blazor.Tools.BlazorBundler.Interfaces.IModelExtendedProperties>
{
}
```
