### ISSUE TITLE
Suspected typo (from someone confused enough to be looking here)

### ISSUE THREAD

**Issue by OldSchoolNewWorld** [dotnet/docs#42677]
### Type of issue

Typo

### Description

In both VB "Sub SerializeObject(filename As String)" and c# "void SerializeObject(string filename)", a remark includes "returns Expanded objects instead.". You may have intended to have "ExpandedBook objects".
The same seems to apply to "DeserializeObject".

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/how-to-control-serialization-of-derived-classes

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/how-to-control-serialization-of-derived-classes.md

### Document Version Independent Id

7c90248b-c098-bf4a-9af9-4c9cda16b379

### Article author

@gewarren

### Metadata

* ID: 68112543-2118-eb1e-e6a6-b11a5b833073 
* Service: **dotnet-fundamentals**

**Comment by svi-net** [comment]
https://github.com/dotnet/docs/issues/42502#issue-2512106751

**Comment by Legend4it** [comment]
Can i work on this issue?? it's my first time to contribute in such project :)

**Comment by BillWagner** [comment]
@Legend4it Yes, we'd appreciate a PR. I'll watch for it.

**Comment by Legend4it** [comment]
A PR created:
https://github.com/dotnet/docs/pull/42718
