### ISSUE TITLE
Chinese translation of static class member initialization incorrect

### ISSUE THREAD

**Issue by klxiaoniu** [dotnet/docs#42680]
### Type of issue

Typo

### Description

In English:
Static members are initialized before the static member is accessed for the first time and before the **static** constructor, if there's one, is called.

Chinese doc:
在首次访问静态成员之前以及在调用构造函数（如果有）之前，会初始化静态成员。

Should be:
在首次访问静态成员之前以及在调用**静态**构造函数（如果有）之前，会初始化静态成员。

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members?redirectedfrom=MSDN

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md

### Document Version Independent Id

de2dac73-e810-dd42-f518-e50926b3747f

### Article author

@BillWagner

### Metadata

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

**Comment by BillWagner** [comment]
Hi @klxiaoniu 

I've opened a work item for this issue on our internal system for localization. Thank you for reporting it.

Because the source English text is correct, I'll close this issue.
