### ISSUE TITLE
dotnet-test.md and the definition of a unit test

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/docs#4269]
[dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md) says (emphasis/brackets mine):

> The dotnet test command is used to execute unit tests in a given project. **Unit tests are console application projects** [[that have dependencies on the unit test framework (for example, MSTest, NUnit, or xUnit) and the dotnet test runner for the unit testing framework. These are packaged as NuGet packages and are restored as ordinary dependencies for the project.]]

Isn't it easy to think that `dotnet-test.md` is trying to give a definition of a unit test? And of course, it would not serve as a good definition, otherwise there would be no such thing as a unit test outside of .Net.

Instead, shouldn't the above quoted say something like the following?

> The dotnet test command is used to execute unit tests in a given project. **dotnet test executes** console application projects that have dependencies on the unit test framework (for example, MSTest, NUnit, or xUnit) and the dotnet test runner for the unit testing framework. These are packaged as NuGet packages and are restored as ordinary dependencies for the project.

Then it is clear that what is given is implementation detail and not a definition of a unit test.

**Comment by mairaw** [comment]
Thanks for the feedback @matthew-a-thomas. We'll get that improved.
