### ISSUE TITLE
[Breaking change]: New security analyzers in WinForms prevent leaking of user data

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/docs#42724]
### Description

In .NET 9, new security analyzers have been introduced in WinForms to prevent the accidental leaking of user data through properties without properly configured CodeDOM serialization behavior. These analyzers enforce best practices by identifying properties that lack explicit serialization settings, such as `DesignerSerializationVisibility`, `DefaultValue`, or `ShouldSerialize[propertyName]` methods.

![Image](https://github.com/user-attachments/assets/d2652cd7-25a5-4a5a-9755-59e4d3a83e78)

**Impact:** By default, the analyzer produces an error, ensuring that developers are made aware of potential security and data leakage issues early in the development process. 

To accommodate specific use cases or suppress these errors, configuration changes can be made in the `.editorconfig` file.

![Image](https://github.com/user-attachments/assets/a5e03715-e96c-4f06-81fc-bbb29227f7de)

![Image](https://github.com/user-attachments/assets/c9c8722a-8739-480b-929f-34f76ded7f2e)

How to Address the Breaking Change:

* Review the properties flagged by the analyzer and configure appropriate serialization settings as needed.
* If necessary, adjust the analyzer’s behavior through `.editorconfig` to change its severity or suppress the error.

This change aims to enhance the security and maintainability of WinForms applications by enforcing proper serialization practices, thus reducing the risk of accidental data exposure.

### Version

.NET 9 RC 1

### Previous behavior

Previously, properties in WinForms controls and UserControls could be serialized by the designer without explicit configuration of their serialization behavior. This could have resulted in unintended data being included in the generated code or resource files, especially in Line-Of-Business (LOB) applications where sensitive or user-specific data could inadvertently be serialized.

For example, properties containing sensitive information, such as user data or internal configurations, could be written directly into the designer-generated .cs files or embedded within .resx files, creating a potential security risk. This behavior was particularly problematic in custom LOB UserControls, where it was easy to overlook the serialization of data that should not have been exposed.

### New behavior

With the introduction of this new WinForms security analyzer feature for property serialization in .NET 9, WinForms applications now enforce stricter control over the serialization of properties in controls and UserControls. By default, the analyzer produces an error if a property does not have its CodeDOM serialization behavior explicitly defined. This behavior applies unless the `.editorconfig` settings are adjusted to change the analyzer's severity or suppress the error.

**Key Changes:**

**Error Generation:** The analyzer identifies properties that are missing proper serialization configuration (`DesignerSerializationVisibility`, `DefaultValue`, or `ShouldSerialize<PropertyName>()`) and generates an error by default. This ensures that properties are not inadvertently serialized, preventing sensitive data from leaking into generated code or resource files.

**Mandatory Configuration:** Developers are now required to explicitly specify serialization settings for properties, making it clear how each property should behave in the designer environment.

**Configurable Behavior:** The severity of the analyzer’s feedback can be adjusted through `.editorconfig` settings, allowing developers to customize the enforcement level based on their specific needs or temporarily suppress the analyzer in controlled scenarios.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries might encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [x] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code might require source changes to compile successfully.
- [ ] **Behavioral change**: Existing binaries might behave differently at run time.

### Reason for change

**Enhanced Security:** By forcing explicit serialization definitions, the analyzer significantly reduces the risk of unintentional data exposure, particularly in LOB applications. This has happened in the past, and it was all the more necessary now in the context of the Binary Serializer removal, the reason being that everything, which we can prevent from being serialized by accident to being with, we will not cause any backwards compatibility and/or security issues around the binary serialization in resource files for types which don't have a dedicated type converter.

**Improved Code Clarity and Maintainability:** On top, this is and always was WinForms Best Practice but can now being enforced. We decided to emit errors for security reason, but with configuring via `.editorconfig` the original behavior can be restored without considerable effort. 

The feature ensures that serialization behavior is transparent and intentional, aiding in code reviews and future maintenance.

This new behavior improves overall application security and data integrity, aligning WinForms with modern best practices for handling property serialization.

### Recommended action

* Configure Properties in WinForms Apps or WinForms class library via one of the mentioned approaches.

* For a quick fix (not recommended), add an entry in the `.editorConfig` file (or add this file, if it doesn't exist yet) on Solution folder or project folder level, and add the following line:

```
[*.cs]

# WFO1000: A property should determine its property content serialization with the DesignerSerializationVisibilityAttribute, DefaultValueAttribute or the ShouldSerializeProperty method
dotnet_diagnostic.WFO1000.severity = silent
```

### Feature area

Windows Forms

### Affected APIs

No specific APIs are affected.

---
[Associated WorkItem - 317460](https://dev.azure.com/msft-skilling/Content/_workitems/edit/317460)

**Comment by DaveCousineau** [comment]
It would be nice if we could apply Hidden (or NotSerialized or whatever) globally somehow. I don't even use the VS designer.
