### ISSUE TITLE
App does not have to be publised before Docker image add

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42740]
### Type of issue

Missing information

### Description

From https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?view=vs-2022&tabs=windows&pivots=dotnet-8-0#publish-net-app

> Before adding the .NET app to the Docker image, first it must be published. It's best to have the container run the published version of the app. 

This could be true but it is not for Dockefile used.

```dockerfile
…
# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out
…
```

These lines take care of building/publishing.

If this would be the case, then lines were be 

```dockerfile
…
# Copy everything
COPY . ./
# Build runtime image
…
COPY --from=build-env App/bin/Release/net8.0/ .
…
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?view=vs-2022&tabs=windows&pivots=dotnet-8-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md

### Document Version Independent Id

58d57b81-4ca6-6536-8788-f212402b41a7

### Article author

@IEvangelist

### Metadata

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa 
* Service: **dotnet-fundamentals**
* Sub-service: **dotnet-docker**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+58d57b81-4ca6-6536-8788-f212402b41a7)

**Comment by IEvangelist** [comment]
Thank you for posting this issue @bravequickcleverfibreyarn

You're not wrong. It was intentionally explained this way so that the consumer understands that the app needs to be published. We explain it outside the context of the Dockerfile as it's good to know it's not specific to building the container image. But I do see your point, we could probably improve this experience. Would you be interested in providing a PR and I'll review it?

**Comment by bravequickcleverfibreyarn** [comment]
I'll try some in upcoming days.

**Comment by bravequickcleverfibreyarn** [comment]
Okay. I find a minute today. Please check with https://github.com/dotnet/docs/pull/42760.
