### ISSUE TITLE
Typo in the .NET Implementations article

### ISSUE THREAD

**Issue by magiudev** [dotnet/docs#42750]
### Type of issue

Typo

### Description

Before going into detail about the [.NET implementations](https://learn.microsoft.com/en-us/dotnet/fundamentals/implementations#net-5-and-later-versions), there is a list of implementations that will be elaborated on in the following text. However, the first item

<img width="545" alt="Screenshot 2024-09-29 at 1 47 46 PM" src="https://github.com/user-attachments/assets/108e2872-a00e-4f06-b6df-ec81099fc038">

Does not match the corresponding title

<img width="675" alt="Screenshot 2024-09-29 at 1 48 07 PM" src="https://github.com/user-attachments/assets/7c793ba5-f591-4c58-95b2-e98ba1898649">

### Page URL

https://learn.microsoft.com/en-us/dotnet/fundamentals/implementations#net-5-and-later-versions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/implementations.md

### Document Version Independent Id

0b9ceffa-ccd9-d338-9dbe-752ac93bb2ad

### Article author

@dotnet-bot

### Metadata

* ID: edc3ae50-d51a-ae5d-6c95-b32852c973a9 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+0b9ceffa-ccd9-d338-9dbe-752ac93bb2ad)

**Comment by Legend4it** [comment]
Is any one work on this issue??

**Comment by magiudev** [comment]
@Legend4it I created this [PR](https://github.com/dotnet/docs/pull/42751) as soon as I reported the issue
