### ISSUE TITLE
Typo in the Releases and support for .NET article

### ISSUE THREAD

**Issue by magiudev** [dotnet/docs#42753]
### Type of issue

Typo

### Description

In the article on Releases and Support for .NET, it is mentioned that the STS versions are supported for six months after the next major or minor release is shipped. However, immediately after that, it states that the support period changes to 18 months

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/releases-and-support#release-tracks

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/releases-and-support.md

### Document Version Independent Id

952bd631-1aa4-1f78-18c7-fd2b96f6c905

### Article author

@gewarren

### Metadata

* ID: 434f5be1-8006-bf3d-aaed-8b6ed6e9b43b 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+952bd631-1aa4-1f78-18c7-fd2b96f6c905)

**Comment by gewarren** [comment]
It's correct as written. 18 months of support, or 6 months after the *next* major release is released.
