### ISSUE TITLE
Variable name doesn't exist

### ISSUE THREAD

**Issue by craigs100** [dotnet/docs#42755]
### Type of issue

Typo

### Description

Section "Register the Microsoft package repository"

The "Tip" mentions "`$repo_version`" but it doesn't exist in the Bash code block above it, which is `"wget https://packages.microsoft.com/config/$ID/$VERSION_ID/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"`
It's unclear whether to replace $ID or $VERSION_ID or both.

I'm running Linux Mint 22.0 and so I need to replace something with 24.04 which is the Ubuntu version it's based on.

### Page URL

https://learn.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

@adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+1d732b15-9e64-633a-000c-ad96d9d3818a)

---
[Associated WorkItem - 323539](https://dev.azure.com/msft-skilling/Content/_workitems/edit/323539)

**Comment by adegeo** [comment]
Thank you for reporting this. I'll get it added to a sprint.
