### ISSUE TITLE
`Rune` is available from .NET Core 3.0 and not on .NET Framework

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42766]
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction#the-rune-type-as-a-scalar-value
> Beginning with .NET Core 3.0, the [System.Text.Rune](https://learn.microsoft.com/en-us/dotnet/api/system.text.rune) type represents a Unicode scalar value. Rune is not available in .NET Core 2.x or .NET Framework 4.x.

From https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction#example-count-char-rune-and-text-element-instances
> If you run this code in .NET Framework or .NET Core 3.1 or earlier, the text element count for the emoji shows 4. That is due to a bug in the StringInfo class that was fixed in .NET 5.

- Second quotation is flawed by fact that, AFAIK, `Rune` is available only to .NET from version Core 3.0. 
- First quotation suggest that earlier versions of Framework have `Rune` while only 4.x versions does not. Similar applies to ..NET Core prior 2.x.

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/character-encoding-introduction.md

### Document Version Independent Id

d53a0764-9f27-16b3-c40a-9627dd1bcc0d

### Article author

@adegeo

### Metadata

* ID: a6cf7421-fbd2-0ca0-7385-4df65531fd66 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+d53a0764-9f27-16b3-c40a-9627dd1bcc0d)

---
[Associated WorkItem - 323541](https://dev.azure.com/msft-skilling/Content/_workitems/edit/323541)

**Comment by bravequickcleverfibreyarn** [comment]
@adegeo,

> If you run this code in .NET Framework or .NET Core 3.1 or earlier, the text element count for the emoji shows `4`. That is due to a bug in the `StringInfo` class that was fixed in .NET 5.

Shouldn't have been this reworded like 

_"If you run this code on .NET Core 3.1 or earlier, the text element count for the emoji shows `4`. That is due to a bug in the `StringInfo` class that was fixed in .NET 5."_ ?

This useful annotation was removed completely.

**Comment by adegeo** [comment]
Hey there!

I made the call to remove it because those versions are long out of support. .NET 4 is still in support hence calling it out specifically. But that's also why I removed the reference to .NET Core 2.x and .NET Core 3.x also.

**Comment by bravequickcleverfibreyarn** [comment]
I do not see .NET 4 specifical callout.  I guess you mean previously called out. However, if documentation is part of product support, I acknowledge removal.
