### ISSUE TITLE
The example should have better variable names

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#42776]
### Type of issue

Other (describe below)

### Description

The variable names used in this example aren't very good. They should be changed.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1526

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1526.md

### Document Version Independent Id

951a0bb1-6e10-876a-a247-995d725e235c

### Article author

@BillWagner

### Metadata

* ID: 9f974a12-2f8b-6171-dd26-719caa1d78c7 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+951a0bb1-6e10-876a-a247-995d725e235c)

**Comment by bigboybamo** [comment]
Hi @BillWagner I created a PR for this. #42783
