### ISSUE TITLE
`ToFrozenDictionary(bool)` does not exist

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42780]
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/runtime#performance-focused-types

```csharp
private static readonly FrozenDictionary<string, bool> s_configurationData =
    LoadConfigurationData().ToFrozenDictionary(optimizeForReads: true);
```

As per [FrozenDictionary.ToFrozenDictionary Method](https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary.tofrozendictionary?view=net-8.0) there are 3 overloads of `ToFrozenDictionary`:
- `ToFrozenDictionary<TKey,TValue>(IEnumerable<KeyValuePair<TKey,TValue>>, IEqualityComparer<TKey>)`
- `ToFrozenDictionary<TSource,TKey,TElement>(IEnumerable<TSource>, Func<TSource,TKey>, Func<TSource,TElement>, IEqualityComparer<TKey>)`
- `ToFrozenDictionary<TSource,TKey>(IEnumerable<TSource>, Func<TSource,TKey>, IEqualityComparer<TKey>)`

None of them has `bool` parameter named `optimizeForReads`.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/runtime

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-8/runtime.md

### Document Version Independent Id

15cdd77f-e040-364f-035a-cecb0fac7cb6

### Article author

@gewarren

### Metadata

* ID: cf0836eb-9b39-9da3-0bf8-cf9cd982727d 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+15cdd77f-e040-364f-035a-cecb0fac7cb6)

---
[Associated WorkItem - 322615](https://dev.azure.com/msft-skilling/Content/_workitems/edit/322615)

**Comment by gewarren** [comment]
Thanks @bravequickcleverfibreyarn. Looks like this method was removed in https://github.com/dotnet/runtime/pull/87988.
