### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Cloud191219** [dotnet/docs#42811]
### Type of issue

Code doesn't work

### Description

[Nhập phản hồi vào đây]

### Page URL

https://learn.microsoft.com/vi-vn/dotnet/csharp/misc/cs2001

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs2001.md

### Document Version Independent Id

be0bc1f4-5d5d-e813-704c-d73c5eeae58c

### Article author

@BillWagner

### Metadata

* ID: 19118b55-2585-d38f-87b2-0f79cb984c07 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+be0bc1f4-5d5d-e813-704c-d73c5eeae58c)

**Comment by BillWagner** [comment]
Hi @Cloud191219 

Do you have any more details to add here?
