### ISSUE TITLE
When I am Runniing Project Product Global elemnet MS i am getting the error in Visual Studio

### ISSUE THREAD

**Issue by kesarisuhas** [dotnet/docs#42822]
### Type of issue

Code doesn't work

### Description

Getting error of Error (active)	CS1525 
![Untitled](https://github.com/user-attachments/assets/2bea09c5-f364-43eb-ab56-f0217a2a3a13)
Invalid expression term

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1525

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1525.md

### Document Version Independent Id

91eb2a64-43b2-f128-9170-b263878a3421

### Article author

@BillWagner

### Metadata

* ID: 23958040-e5a6-2d3b-4764-d5b0b4126cc4 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+91eb2a64-43b2-f128-9170-b263878a3421)

**Comment by BillWagner** [comment]
Hi @kesarisuhas 

It looks like you have a syntax error in your Razor file.

Is there more that you'd like to see from this article?
