### ISSUE TITLE
`JsonSerializer.DeserializeAsyncEnumerable` has no `topLevelValues` default

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42840]
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries#stream-multiple-json-documents

>  **By default**, the method attempts to stream elements that are contained in a top-level JSON array. You can toggle this behavior using the new topLevelValues flag:

I checked two existing overloads having `bool topLevelValues` parameter:
- [DeserializeAsyncEnumerable<TValue>(Stream, Boolean, JsonSerializerOptions, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserializeasyncenumerable?view=net-9.0#system-text-json-jsonserializer-deserializeasyncenumerable-1(system-io-stream-system-boolean-system-text-json-jsonserializeroptions-system-threading-cancellationtoken))
- [DeserializeAsyncEnumerable<TValue>(Stream, JsonTypeInfo<TValue>, Boolean, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserializeasyncenumerable?view=net-9.0#system-text-json-jsonserializer-deserializeasyncenumerable-1(system-io-stream-system-text-json-serialization-metadata-jsontypeinfo((-0))-system-boolean-system-threading-cancellationtoken))

both does not have **default** for it.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-9/libraries.md

### Document Version Independent Id

0c8c7059-86a1-e5df-32e6-fae6fdc5cae0

### Article author

@gewarren

### Metadata

* ID: 7c184200-3411-aa5b-ba3f-0b4a3ce0f589 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
There are overloads that don't have a `topLevelValues` parameter that pass `false` for that parameter to the overloads that do: https://github.com/dotnet/runtime/blob/9bfe7bf85373398682b3e9da1a6dede39924d04b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs#L428.
