### ISSUE TITLE
Warning page should be updated for pattern matching

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#42861]
### Type of issue

Outdated article

### Description

This article should show how to use `is` with pattern matching instead of `as`.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0077

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0077.md

### Document Version Independent Id

c3ff4ab4-e153-102b-84f3-7f8459c7b994

### Article author

@BillWagner

### Metadata

* ID: 12ca3560-3086-2819-9fec-dbead5bdc34b 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BartoszKlonowski** [comment]
@BillWagner I will work on this!
