### ISSUE TITLE
Where's output for workload sets mode switch?

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42863]
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/sdk#workload-history

```
> dotnet workload history
+----+-----------+---------------------+---------------+--------------------------------------------------+-----------------------------+
| Id |    Date   |       Command       |   Workloads   |                Global.json Version               |       Workload Version      |
+----+-----------+---------------------+---------------+--------------------------------------------------+-----------------------------+
|  1 |  1/1/0001 |  12:00:00 AM +00:00 |  InitialState |  android, ios, maccatalyst, maui-windows         |  9.0.100-manifests.6d3c8f5d |
|  2 |  9/4/2024 |  8:15:33 PM -05:00  |  install      |  android, aspire, ios, maccatalyst, maui-windows |  9.0.100-rc.1.24453.3       |
+----+-----------+---------------------+---------------+--------------------------------------------------+-----------------------------+
```

> Then, the dotnet workload install aspire --version 9.0.100-rc.1.24453.3 command was used to install the aspire workload and **switch to [workload sets mode](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets)**.

Neither command not output shows anything related to _workload sets switch_. Maybe I just missing something.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/sdk

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-9/sdk.md

### Document Version Independent Id

361d667b-3132-591f-690f-19bfa5745849

### Article author

@gewarren

### Metadata

* ID: 751d7e36-62cf-cdcc-fb0b-f6c3f8ca4869 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
From https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets#pin-the-install-command, when you use the `install` command with a `--version` option, the `install` command is pinned in workload-set update mode.

Also, from https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets#check-the-update-mode-and-version, if it's in manifests mode, "you see a version in the form of `<feature band>-manifests.<hash>`.".

<img width="177" alt="image" src="https://github.com/user-attachments/assets/77d671f9-575d-4050-b826-4504fd625e87">

**Comment by bravequickcleverfibreyarn** [comment]
Definitely. Also at https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/sdk#workload-sets

> In this example, the SDK installation is in 'manifest' mode, where updates are installed as they're available. To opt in to the new mode, **add a --version option** to a dotnet workload install or dotnet workload update command.
