### ISSUE TITLE
typo: mistaken negation in explanation

### ISSUE THREAD

**Issue by PieterOosterbroek** [dotnet/docs#42870]
### Type of issue

Typo

### Description

If I understand this right then
"Consider the following student and teacher arrays. The query matches items in each sequence by name to find those students who are**n't** also teachers:"
should be
"Consider the following student and teacher arrays. The query matches items in each sequence by name to find those students who are also teachers:"

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/set-operations?branch=main#union-and-unionby

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/standard-query-operators/set-operations.md

### Document Version Independent Id

77eff122-b9a5-2b1f-3a68-df302cb46194

### Article author

@BillWagner

### Metadata

* ID: fbdace9d-6fa0-0aec-25b4-df6f414001d7 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BillWagner** [comment]
Thanks for pointing this out @PieterOosterbroek 

I've opened a PR to fix this.  

In the future, if you find errors that are small in scope, you can open a PR by clicking the "edit" button on the top of the page (it looks like a pencil).  It can save us both a bit of time. It took me a bit to find the text you were referring to.
