### ISSUE TITLE
Some text in System.Threading.Timer is clipped

### ISSUE THREAD

**Issue by rigdern** [dotnet/docs#4297]
Relevant document: [System.Threading.Timer](https://github.com/dotnet/docs/blob/aca8d4895dad26cb95af2e3aad03bb7f549d0747/xml/System.Threading/Timer.xml)

I'm seeing text in "Tip" under the "Remarks" section being clipped. Here's a screen shot:

![image](https://user-images.githubusercontent.com/199935/35749289-f6873564-0805-11e8-9a83-5f8dfbb1eed7.png)

Adam Comella
Microsoft Corp.

**Comment by mairaw** [comment]
Thanks @rigdern for the feedback. @adkinn can you take a look at this issue? I can repro this if I resize my window a bit.

**Comment by mairaw** [comment]
Filed internal issue to track this: 1179401

**Comment by mairaw** [comment]
Team has fixed the issue. Thanks for reporting it @rigdern!
