### ISSUE TITLE
unity

### ISSUE THREAD

**Issue by Dineshdk2104** [dotnet/docs#43035]
### Type of issue

Typo

### Description

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0234	The type or namespace name 'LWRP' does not exist in the namespace 'UnityEditor.Rendering' (are you missing an assembly reference?)	Assembly-CSharp-Editor	C:\Dinesh\Unity_Project\CAR\Assets\ClearCoat\Editor\LitShaderGUI.cs	4		

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0619?f1url=%3FappId%3Droslyn%26k%3Dk(CS0619)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0619.md

### Document Version Independent Id

5a9ad5dd-d83e-4a76-1027-83e82365a077

### Article author

@BillWagner

### Metadata

* ID: ebcce64d-c781-6283-5763-1ed946cc8083 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by adegeo** [comment]
Sorry, you need to ask the Unity product about that error, or the maker of LitShader.
