### ISSUE TITLE
Wrong model file to load

### ISSUE THREAD

**Issue by aguacongas** [dotnet/docs#43075]
### Type of issue

Code doesn't work

### Description

```cs
builder.Services.AddPredictionEnginePool<ModelInput, ModelOutput>()
    .FromFile("SentimentAnalysis.zip");
```

The file should be *SentimentAnalysis.mlnet*

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/machine-learning/tutorials/sentiment-analysis-model-builder

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/sentiment-analysis-model-builder.md

### Document Version Independent Id

11857021-b820-ac38-307c-33f3f4a5065f

### Article author

@luisquintanilla

### Metadata

* ID: 6cdb113e-14a4-7e96-2998-9bc42ddf9d7d 
* Service: **dotnet-ml**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+11857021-b820-ac38-307c-33f3f4a5065f)

**Comment by adegeo** [comment]
Are you sure? I checked a bunch of the samples in https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/end-to-end-apps and they all use zip files that were generated by the trainers.

**Comment by aguacongas** [comment]
Yes I'm, using **Microsoft.ML"" verion **3.0.1** it should be *SentimentAnalysis.mlnet" now
