### ISSUE TITLE
IDENTITY

### ISSUE THREAD

**Issue by bhekane** [dotnet/docs#43091]
### Type of issue

Code doesn't work

### Description

 [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LOGIN(LOGGINMODELVIEW lOGGINMODELVIEW,BOKING bOKING)
        {

            string LOGGINCODE = Guid.NewGuid().ToString();
            bool client = db.MAN.Any(c => c.CLIENT_EMAILADDRESS == lOGGINMODELVIEW.EMAIL);
            if (client == false)
            {
                ViewBag.C = "Email is not valid";
                return View(lOGGINMODELVIEW);
            }

            CLIENT cLIENT = db.MAN.FirstOrDefault(model => model.CLIENT_EMAILADDRESS == lOGGINMODELVIEW.EMAIL);
            if (cLIENT == null)
            {
                ViewBag.C = "User not found.";
                return View(lOGGINMODELVIEW);
            }

            if (!cLIENT.CLIENT_ISVERIFIED == true)
            {
                ViewBag.C = "Email is not verified";
                return View(lOGGINMODELVIEW);
            }
            FormsAuthentication.SetAuthCookie(lOGGINMODELVIEW.EMAIL, lOGGINMODELVIEW.RememberMe);

            byte[] USERSALT = Convert.FromBase64String(cLIENT.CLIENT_CLIENTSALTING);
            byte[] bytePassword = Encoding.UTF8.GetBytes(lOGGINMODELVIEW.PASSWORD);
            byte[] passwordConversion = Cryptoservice.ComputeHMAC256(bytePassword, USERSALT);
            string ActualPassword = Convert.ToBase64String(passwordConversion);

            if (cLIENT.CLIENT_PASSWORD != ActualPassword)
            {
                EMAILCAUTION.SendLOGGINCODE(cLIENT.CLIENT_EMAILADDRESS, LOGGINCODE);
                ViewBag.C = "PASSWORD AND EMAIL DONOT MATCH TRY AGAIN!!!";
                ModelState.Clear();
                return View();
            }
            bool HAA = db.MAN.Any(c => c.CLIENT_EMAILADDRESS == lOGGINMODELVIEW.EMAIL);
            if (HAA == false && cLIENT.CLIENT_PASSWORD != ActualPassword)
            {
                ViewBag.FF = "YOU DON'T HAVE A REGISTERD ACCOUNT!!!";
                ModelState.Clear();
                return View();
            }

            ViewBag.EM = lOGGINMODELVIEW.EMAIL;
            ViewBag.B = Url.Content("~/images/success_bell-6776.mp3");
            ViewBag.mee = "LOGIN SUCCESSFULL!!!!";
            return RedirectToAction("Create", "BOKINGs");

        }

        Session["CLIENT_ID"] = cLIENT.CLIENT_ID;

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/assembly-references?f1url=%3FappId%3Droslyn%26k%3Dk(CS0012)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/assembly-references.md

### Document Version Independent Id

9dbb6834-202a-3e3b-e7e4-40ab7e85c2b6

### Article author

@BillWagner

### Metadata

* ID: 1dfdc2b3-0c7c-4607-32b3-0b5e8469579d 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+9dbb6834-202a-3e3b-e7e4-40ab7e85c2b6)

**Comment by BillWagner** [comment]
Hi @bhekane 

The error you're getting indicates that you need to add a reference to an additional assembly. From the source you posted, I don't know which assembly should be added.

For more help, I suggest posting a question with more details on our Q & A site.

I'll close this as it's not a docs issue.
