### ISSUE TITLE
[Breaking change]: 9.0.100 will require 17.11.0 or newer Visual Studio

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#43188]
### Description

Per https://learn.microsoft.com/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules, 9.0.100 requires 17.11 to target net8 and below and requires 17.12 and above to target net9.0.

This change was added for the final build.

https://github.com/dotnet/sdk/pull/43143

### Version

.NET 9 GA

### Previous behavior

We previously weren't blocking 9.0.100 on loading on earlier Visual Studio versions or warning when targeting net9.0 when using 17.11.

### New behavior

- 9.0.100 will not load in 17.10 or earlier Visual Studio
- Visual Studio 17.11 will no longer make net9.0 available in the project properties
- 9.0.100 will warn when targeting net9.0 and using 17.11
  - `NETSDK1223: Targeting .NET 9.0 or higher in Visual Studio 2022 17.11 is not supported.`

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries might encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code might require source changes to compile successfully.
- [x] **Behavioral change**: Existing binaries might behave differently at run time.

### Reason for change

This is a planned change

### Recommended action

Upgrade to use a newer Visual Studio version.

### Feature area

SDK

---
[Associated WorkItem - 340220](https://dev.azure.com/msft-skilling/Content/_workitems/edit/340220)

**Comment by vdanche** [comment]
Checked on VS 17.11.6 [35424.203.d17.11] with November update + 9.0.100,
 We can select the net9.0(Preview) tfm when creating project. **is it expected?**
![Image](https://github.com/user-attachments/assets/3c744e0a-e6d0-46e9-b462-3ab87881557b)
After the project is created successfully, in properties page. there is no net9.0 tfm as below
![Image](https://github.com/user-attachments/assets/d60110a7-cc8b-4b03-9acd-464353216ffc)
and build 9.0 project, below warning happens
![Image](https://github.com/user-attachments/assets/6eab295d-0b41-43fc-8626-1ee979945b87)
![Image](https://github.com/user-attachments/assets/23463d40-7a57-48f7-9f99-71050930625f)

**Comment by marcpopMSFT** [comment]
@vdanche the change I made will cause the 9 sdk to not load in 17.10 which is the error NETSDK1045. I added NETSDK1223 as well in that change. I also made it so the property pages won't show. So all of those are expected.

The change I made doesn't affect the new project experience. @phenning would control that. I don't remember what behavior we had with 8.0.1xx loaded into 17.7.

**Comment by phenning** [comment]
> NPD doesn't care about SDK version in this drop down - it only cares about the TFM. Are we saying the net9.0 is not supported under ANY VS Prior to 17.11?
> 
> When should this switch be made, do we want to drop the 17.10 now before the replacement LTS is released? Note we just need to upload some files and possibly reconfigure some fwlinks.

@vijayrkn , FYI

**Comment by phenning** [comment]
@marcpopMSFT Actually looking at that link https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules, is the rule here that net9.0 TFMs should only be available on 17.12 and later in NPD?
