### ISSUE TITLE
Add and Fix

### ISSUE THREAD

**Issue by Joj501** [dotnet/docs#43218]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-type

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/partial-type.md

### Document Version Independent Id

a8d43580-fc8d-b3bb-2f43-e62d5ed9640c

### Article author

@BillWagner

### Metadata

1. Duplicate of #43216 [*](

- [ ] url

) ID: 636f7992-54b7-5ff1-bd2e-44ec75ab8b53 

* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment]
Hi @Joj501 

Do you have more details to add here?
