### ISSUE TITLE
No funcionan los words ni los excel (Word and Excel interop don't work)

### ISSUE THREAD

**Issue by larrayoz146585** [dotnet/docs#43240]
### Type of issue

Typo

### Description

No hay manera de hacer funcionar el excel y el word el visual studio community 2022, ya tengo las referencias COM bien instaladas pero me aparecen errores como este: Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS1061	'Application' does not contain a definition for 'Visible' and no accessible extension method 'Visible' accepting a first argument of type 'Application' could be found (are you missing a using directive or an assembly reference?)	Dindaia	C:\Users\asier\Desktop\Dindaia fron acabado\DindaiaApp2Bulego\DindaiaApp2\Gestoria.cs	58	

### Page URL

https://learn.microsoft.com/es-es/dotnet/csharp/advanced-topics/interop/how-to-access-office-interop-objects

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/advanced-topics/interop/how-to-access-office-interop-objects.md

### Document Version Independent Id

abcc188f-96ba-c569-afc7-b5607f01c3ed

### Article author

@BillWagner

### Metadata

* ID: 6a1155e2-e1f0-772d-4877-c5724ea3d489 
* Service: **dotnet-csharp**
* Sub-service: **advanced-concepts**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+abcc188f-96ba-c569-afc7-b5607f01c3ed)

**Comment by BillWagner** [comment]
English translation:

> There is no way to make excel and word work in the visual studio community 2022, I already have the COM references well installed but I get errors like this: Severity Code Description Project File Line Suppression State
> Error (active) CS1061 'Application' does not contain a definition for 'Visible' and no accessible extension method 'Visible' accepting a first argument of type 'Application' could be found (are you missing a using directive or an assembly reference?)

When I updated these articles, I used the Enterprise version of Visual Studio. When we check this, we should work with the community edition.

**Comment by larrayoz146585** [comment]
Para arreglarlo tuve que desinstalar e instalar Microsoft 365
