### ISSUE TITLE
Hoew to create a new FILEGDB, and Dataset , Featuresclass by programetically

### ISSUE THREAD

**Issue by ranjithGIS** [dotnet/docs#43245]
### Type of issue

Typo

### Description

MapView doesnot contain a definition for both GetSelectedFeaturesAsync() and GetSelectedFeatures()

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0117?f1url=%3FappId%3Droslyn%26k%3Dk(CS0117)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0117.md

### Document Version Independent Id

fefbef5d-bc47-9458-1ba5-86388d2c251a

### Article author

@BillWagner

### Metadata

* ID: b1c7d191-7c09-0bd8-32b2-527748c41882 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Hi @ranjithGIS 

Do you have more information on this issue? What did you hope to find in this article that wasn't located?
