### ISSUE TITLE
This does not mention `using` statements for namespace import and how they are handled

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#43266]
### Type of issue

Missing information

### Description

> Within a namespace, you can declare zero or more of the following types:
> [class](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/class)
> [interface](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface)
> [struct](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct)
> [enum](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum)
> [delegate](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types#the-delegate-type)
> nested namespaces can be declared except in file scoped namespace declarations

This is missing information about how `using` statements are handled with this style of namespace declaration. Specifically how do we get behavior similar to when using statements are inside a conventional namespace block (as opposed to when using statements are declared outside of the namespace block)?

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/namespace.md

### Document Version Independent Id

0fa374d3-04b8-fd8a-65f4-cd69944e27bf

### Article author

@BillWagner

### Metadata

* ID: f74806f9-ada9-ab38-bc26-d54bfb789da7 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+0fa374d3-04b8-fd8a-65f4-cd69944e27bf)

**Comment by BillWagner** [comment]
Hi @StingyJack 

We'll add that. In the meantime, a file scoped `namespace` lowers to the equivalent `namespace` declaration with the closing bracket added at the end of the file. The meaning of any `using` declaration is the same:  If it's after the file scoped `namespace` declaration, it's inside the `namespace`, and the simple name is parsed appropriately. If it's before the file scoped `namespace` declaration, it's outside the `namespace`, and the `using` target is parsed from the global namespace.

I've added the "help wanted" label in case anyone wants to submit a PR before we make this update

**Comment by shethaadit** [comment]
Hi @BillWagner, I will work on this and submit the PR soon. :)
