### ISSUE TITLE
Where should the while loop placed?

### ISSUE THREAD

**Issue by peymanebrahimi** [dotnet/docs#43263]
### Type of issue

Other (describe below)

### Description

Shouldn't the while loop be inside the **backgroundService** Execute method to scopedService make sense?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/scoped-service

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/scoped-service.md

### Document Version Independent Id

5a2fc6e8-a47b-c300-1ef0-e6ae89612d74

### Article author

@IEvangelist

### Metadata

* ID: ca143da3-5c97-0dc0-9d99-ed477a8bce91 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+5a2fc6e8-a47b-c300-1ef0-e6ae89612d74)

**Comment by adegeo** [comment]
Hi @peymanebrahimi did you try running the code? I believe it's correct. It's also documented this way at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio

**Comment by peymanebrahimi** [comment]
Hi @adegeo It works fine.
but in the section of **Consuming a scoped service in a background task** it is trying to show How to get a new scoped service during the lifetime of the application. The _DoWork_ method of the background host class is running once. and the loop inside of the IScopedProcessingService is running multiple times as it is inside the while. and it only receives the only-one-time-created of scopedService like it is a singleton.

if we can get ride of the private methods it is like this:

```
public class ConsumeScopedServiceHostedService(IServiceProvider Services) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        using (var scope = Services.CreateScope())
        {
            var scopedProcessingService =
                scope.ServiceProvider.GetRequiredService<IScopedProcessingService>();

            await scopedProcessingService.DoWork(stoppingToken);
        }
    }
}

internal class ScopedProcessingService(AnyScopedDefinedService anyScopedDefinedService) : IScopedProcessingService
{
    public async Task DoWork(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            anyScopedDefinedService.ExecuteScoped(stoppingToken);// this will be provided once as there is no new scope creation
        }
    }
}
```

however I think we want something like this:

```
public class ConsumeScopedServiceHostedService(IServiceProvider Services) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            using (var scope = Services.CreateScope())
            {
                var scopedProcessingService =
                    scope.ServiceProvider.GetRequiredService<IScopedProcessingService>();

                await scopedProcessingService.DoWork(stoppingToken);
            }
        }        
    }
}

internal class ScopedProcessingService(AnyScopedDefinedService anyScopedDefinedService) : IScopedProcessingService
{
    public async Task DoWork(CancellationToken stoppingToken)
    {
        anyScopedDefinedService.ExecuteScoped(stoppingToken);// I am in new scope now.
    }
}
```

**Comment by IEvangelist** [comment]
Yes, this could use a fix to help clarify the correct usage. Thank you, I'll take care of this.
