### ISSUE TITLE
JsonSerializerOptions.AllowOutOfOrderMetadataProperties Property Is Not Available in .Net 8

### ISSUE THREAD

**Issue by Abdo-reda** [dotnet/docs#43299]
### Type of issue

Typo

### Description

# AllowOutOfOrderMetadataProperties Unavailable in dotNet 8
`AllowOutOfOrderMetadataProperties` in the `JsonSerializerOptions` is **not available in dotNet 8**. In fact, its only available in newer version of System.Text.Json (v9) for .Net 9. 

Please Update Documentation.

![Image](https://github.com/user-attachments/assets/b2e7da3a-6c81-4082-b5ec-8d4bb61e7887)
![Image](https://github.com/user-attachments/assets/48ee2cab-db0b-4d8d-8c89-393b2cd4b942)

* **Github Repo**
[.Net 9 SerializerOptionsClass](https://github.com/dotnet/runtime/blob/v9.0.0-rc.2.24473.5/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs)
[.Net 8.0.10 SerializerOptionsClass](https://github.com/dotnet/runtime/blob/v8.0.10/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs)

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-8-0#configure-polymorphism-with-the-contract-model

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/polymorphism.md

### Document Version Independent Id

17511810-6572-ad88-6eaf-4f9bded720b7

### Article author

@gewarren

### Metadata

* ID: 179cc49a-a37d-155e-5ecf-deca4f219a5a 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+17511810-6572-ad88-6eaf-4f9bded720b7)

**Comment by gewarren** [comment]
Thanks @Abdo-reda. I've removed the "zone pivots" at the top of this article. The AllowOutOfOrderMetadataProperties property is available on down-level versions via a NuGet package, so I think this article is fine as-is.

**Comment by Angelinsky7** [comment]
@gewarren sorry i finally found it in dotnet9, i misread the thread about dotnet8
