### ISSUE TITLE
Questionable sample of of throwing Exceptions

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4334]
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-explicitly-throw-exceptions

This page states: 

> It is good coding practice to add information to an exception that is re-thrown to provide more information when debugging.

The example code however, then _loses_ information with the exception it throws, by wrapping the existing FileNotFoundException inside another FileNotFoundException - which I believe would loose the FileName property, any other properties set by the system by default, and any localisation.

If the team agree, I'd be happy to contribute a new sample - but I could only write the C# version. Would also be good to work out a better sample to show this concept before writing it - any thoughts?

**Comment by BillWagner** [comment]
@ChrisMaddock Thanks for adding this.

/cc @terrajobst @weshaggard for their input

In my opinion, this topic needs quite a bit of updates:

The title is "How to: Explicitly throw exceptions".  The only example shows a re-throw, and as Chris mentions, it's not a good example of catching an exception, and then re-throwing a new exception with more information. This example re-throws the same type of exception, and has very little information.

We should show examples of these scenarios:
1. throwing an exception *outside of a catch*. Argument validation is often a good example here.
2. re-throwing after some resource cleanup using `throw`
3. throwing a new exception type with new information and an inner exception (something like the current example, but a better scenario).

Thoughts?

**Comment by weshaggard** [comment]
I agree that this topic should be cleaned up. I like your 3 scenarios @BillWagner.

**Comment by BillWagner** [comment]
@ChrisMaddock Do you want to submit a PR following the thoughts in my comment above? If that's more than you want to take on, we'll add it to our backlog.

**Comment by ChrisMaddock** [comment]
@BillWagner Not sure how soon I'll get round to it, but sounds like fun! 😄 Will see what I can do.

**Comment by ChrisMaddock** [comment]
@mairaw Would you mind unassigning me from this issue and putting it up-for-grabs. Sorry - I'm not sure this is the right one for me!

**Comment by mairaw** [comment]
No worries @ChrisMaddock!
