### ISSUE TITLE
System.Uri constructor exceptions formatting error

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#4349]
On the Uri constructor page, constructor (uri, string) and (uri, uri) there is a formatting issue. This happens for many different .NET versions.

Urls:
* https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.7.1#System_Uri__ctor_System_Uri_System_String_
* https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netframework-4.7.1#System_Uri__ctor_System_Uri_System_Uri_

Screenshot:
![thumbnail_image001](https://user-images.githubusercontent.com/1635825/36030963-7551ddf6-0da9-11e8-90e7-22c4655c88ae.jpg)

I'm not exactly sure how to fix this, otherwise I would've fixed it and created a PR ;-) . I created another PR for another type (#4348).

**Comment by mairaw** [comment]
Thanks @Styxxy. @rpetrusha will work with you on your PR to get this fixed.
