### ISSUE TITLE
System.Numerics needs clarification that points/vectors are treated as rows

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4356]
@geoeo in the #4345 PR has raised an issue that current documentation of [System.Numerics](https://docs.microsoft.com/en-us/dotnet/api/system.numerics?view=netcore-2.0) namespace doesn't say if an individual point/vector is treated as a row or as a column. 

That knowledge is essential when we want to chain two non-commutative transformations. Let's say two transformations are defined by matrices `M1` and `M2`. If a vector `v` is a row, then it's transformed by `v * M1 * M2`. If `v` is a column, then it's transformed by `M2 * M1 * v`. So to get combined transformation matrix, `M1 * M2` or `M2 * M1`, we need to know if vectors are rows or columns.

`System.Numerics` treats vectors as rows. I suggest to make the common remarks paragraph that might be placed to Matrix4x4, Matrix3x2, Vector[234] struct descriptions. 

@BillWagner if that sounds as a good plan, I'm willing to realize it. In meantime, we agreed with @geoeo that PR #4345 might be closed.

**Comment by rpetrusha** [comment]
This sounds like a good plan, @pkulikov. We'll close PR #4345.
