### ISSUE TITLE
Mentioned keyboard shortcut is incorrect

### ISSUE THREAD

**Issue by joellyons** [dotnet/docs#43577]
### Type of issue

Typo

### Description

The third bullet point under "Host shutdown" mentions using Ctrl+Z, but should say Ctrl+C:
"If the app is forcefully shut down using SIGKILL (or CTRL+Z)."

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host?tabs=appbuilder#host-shutdown

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/generic-host.md

### Document Version Independent Id

22a12ff8-d2ff-a841-b9bb-e2fd1032bc04

### Article author

@IEvangelist

### Metadata

* ID: d43ecd7c-307a-688e-d533-c1135bde65f9 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+22a12ff8-d2ff-a841-b9bb-e2fd1032bc04)

**Comment by joellyons** [comment]
Oh, I just realized I might be incorrect about this. I've never seen Ctrl+Z associated with SIGKILL (only SIGSTOP) and assumed this document meant Ctrl+C (SIGINT), but perhaps Ctrl+Z is appropriate in this case.

**Comment by adegeo** [comment]
I think you're correct in your corrected assumption. CTRL+C is specifically talked about in the next section.
