### ISSUE TITLE
Phone Hacked

### ISSUE THREAD

**Issue by IzzyDC** [dotnet/docs#43588]
### Type of issue

Other (describe below)

### Description

Hacker deleted my Apple ID and email to my phone.  Hacker stole data and information on my phone including cloned my phone number.  Hacker blocks certain calls to my phone and pretends to be people and company places I have called.  Had to create another Apple ID and passwords in accts that I can get into, but hacker keeps changing passwords.  Hacker is able to change things in my phone like from my settings page.  Hacker has also created a family grouping acct on my phone where he is sharing my phone service acct and information throughout his family.  My phone was updated to version 17 is now a version 16.7.10 can not get it to update again. 

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-locals.md

### Document Version Independent Id

a69419b1-6994-3310-6bde-d787b87db13f

### Article author

@karann-msft

### Metadata

* ID: a5725b81-7ebf-e9c5-51b7-f6d1cf5d5dc2 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+a69419b1-6994-3310-6bde-d787b87db13f)

**Comment by adegeo** [comment]
Contact Apple support.
