### ISSUE TITLE
Suggestions to improve style guide

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4358]
I think there are several minor improvements for the current [style guide](https://github.com/dotnet/docs/blob/master/styleguide/template.md):
- **Metadata** section can mention when **ms.date** should be or shouldn't be updated.
- **Links** section should describe how to reference [https://docs.microsoft.com/en-us/](https://docs.microsoft.com/en-us/) pages that don't belong to dotnet/docs repo. It's docs.microsoft specific feature, though.
- **Links to APIs** section. Examples of using \* after UID can be given in the same way as examples for System.String at the same section (raw file contains https links, not xref).
- **Code** section. The rendering of the list with parameters of `'[!code...]` construct is broken: only two levels instead of intended three.
- **Includes** section. The example is broken: no *sampleinclude.md* file in the repo. Also, what should be put between the square brackets at the `[!INCLUDE[what goes here?](relative link to the file)]` construct?
- At last, we can add the link to the [MIcrosoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/) or [Top 10 tips](https://docs.microsoft.com/en-us/style-guide/top-10-tips-style-voice) from there.

@BillWagner @mairaw @rpetrusha what do you think?

**Comment by mairaw** [comment]
Those are great suggestions @pkulikov. I wasn't even aware we published the Style guide publicly. 

Our team is also working on an [official contributor guide](https://docs.microsoft.com/en-us/contribute/), so that should replace our internal style guide, once we feel we have all the info we need there.

For the Links to other topics inside docs.microsoft.com not in this repo, we're still trying to define the actual behavior we want with the engineering team. For now, we're always removing docs.microsoft.com/locale from the URLs.

**Comment by pkulikov** [comment]
@mairaw thanks a lot for that link to the contributor guide!
It looks this issue might be closed as soon as README of this repo contains the link to that guide :).

**Comment by BillWagner** [comment]
@pkulikov I think you're right.  Would you like to submit a PR for that, or would you rather we update it?

**Comment by pkulikov** [comment]
@BillWagner I'm fine with making PR. Let's agree on the scope. I'm thinking, maybe, of too many changes as, to not confuse contributors, the local guides should be cleaned up as soon as the link to official one is published:
1. Add the link to the official contributor guide to the README file. That seems that @mairaw thinks that that guide is not yet complete. Even being not complete, the guide contains more useful information than the local guides.
1. The local [CONTRIBUTING file](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) should be reworked: delete general advice, only leave things specific to the dotnet/docs repo (folder structure, for example).
1. Most probably, [voice-tone.md](https://github.com/dotnet/docs/blob/master/styleguide/voice-tone.md) file might be deleted.
1. [Template file](https://github.com/dotnet/docs/blob/master/styleguide/template.md) should be radically shortened to become only the template, if necessary.

Intermediate plan:
1. Add link to the official guide to README.
1. Remove info that is at the official guide from the three files mentioned above.
1. Create separate issues to update those files with repo-specific info.

**Comment by mairaw** [comment]
Yes, I see some issues with that guide. 

For example, xref links are covered here (https://docs.microsoft.com/en-us/contribute/ops-crr/openpublishing/docs/partnerdocs/gfm?toc=%2Fcontribute%2FTOC.json&bc=%2Fcontribute%2Fbreadcrumb%2Ftoc.json#xref-links) and not in the links section. It has wrong guidance (wrong query param name) and it's incomplete (it doesn't cover the need for encoding). 
And why do we have two topics covering links in that guidance?

Supported languages is incomplete here (it doesn't list aspx): https://docs.microsoft.com/en-us/contribute/ops-crr/openpublishing/docs/partnerdocs/codesnippets?toc=%2Fcontribute%2FTOC.json&bc=%2Fcontribute%2Fbreadcrumb%2Ftoc.json#inline-code-blocks

I cannot find where metadata is explained. There's a link here (https://docs.microsoft.com/en-us/contribute/ops-crr/openpublishing/docs/partnerdocs/gfm?toc=%2Fcontribute%2FTOC.json&bc=%2Fcontribute%2Fbreadcrumb%2Ftoc.json#metadata) that leads to a 404 page.

**Comment by mairaw** [comment]
I know there are some folks working on that contributor guide right now, so we just need to make sure it covers everything we need before we shut down our side. /cc @wadepickett

**Comment by BillWagner** [comment]
Closing after moving to MicrosoftDocs/contribute#156
