### ISSUE TITLE
CacheDependency on CacheKeys needs a remark on non-existent keys

### ISSUE THREAD

**Issue by nandkishorenair** [dotnet/docs#4359]
# Missing remarks on cache keys
The CacheDependency [constructor ](https://docs.microsoft.com/en-us/dotnet/api/system.web.caching.cachedependency.-ctor?view=netframework-4.7.1#System_Web_Caching_CacheDependency__ctor_System_String___System_String___)needs to have a remark on CacheKeys, similar to the one for file names.

Basically, when creating the file dependency, the dependency can still “work” even if the file doesn’t exist. Eg, a file watcher is created and if a new file springs to life with that name, it will invalidate the cache item. 
A CacheKey dependency does not work the same way, since there is no “watcher” keeping an eye out for a new key to get inserted. So if it doesn’t exist at insert time, it’s considered an expired dependency. This needs to be mentioned in the remarks section.

File Path: docs/xml/System.Web.Caching/CacheDependency.xml

**Comment by nandkishorenair** [comment]
Adding the below to the remarks section for the constructor, after the remarks on FileDependency, should suffice:

_CacheKey dependency does not work the same way. If the CacheKey does not exist at the time of an insert, the insert will fail. Note that there is no exception thrown for this scenario._

**Comment by mairaw** [comment]
Thanks @nandkishorenair. @Rick-Anderson @scottaddie do you guys wanna take a look at this one?
