### ISSUE TITLE
WebClient should be replaced with HttpClient

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#43607]
### Type of issue

Outdated article

### Description

The code in this article is outdated. The `WebClient` class is deprecated, and should be replaced with `HttpClient`.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/async-expressions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/async-expressions.md

### Document Version Independent Id

ca52fed1-2956-1f51-e1c5-8a29e0a36679

### Article author

@KathleenDollard

### Metadata

* ID: 8bb27022-f56a-e122-7da0-9e00f52a8e73 
* Service: **dotnet-fsharp**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+ca52fed1-2956-1f51-e1c5-8a29e0a36679)

**Comment by bigboybamo** [comment]
Hi @BillWagner 

I created a PR for this here #43060 

I was unsure of what to do with section of **Asynchronous Primitives** though, since thats refrencing what has been removed.

Lemme know what you think
