### ISSUE TITLE
Cross-platform development section requires revision

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4364]
# Cross-platform development section requires revision

## Issues with Existing Topic

The [Developing for Multiple Platforms with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/) topic doesn't list .NET Standard as an option, and the [Portable Class Library](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library) topic doesn't note that PCLs are recommended for legacy development only, and that .NET Standard is recommended for new development.

**Comment by mairaw** [comment]
Duplicate of #2724
