### ISSUE TITLE
C# section Thread Pool Parameters and Return Values refers to VB concepts

### ISSUE THREAD

**Issue by user135711** [dotnet/docs#4367]
In the C# programming guide the subsection on [Thread Pool Parameters and Return Values](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-pooling#thread-pool-parameters-and-return-values) refers to `sub`'s and `ByVal` which is confusing. The objects in c# are passed analogously to VB ByVal so the method described by the entire topic is no different from the method described already by the[ Parameters and Return Values for MultiThreaded Procedures. ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/parameters-and-return-values-for-multithreaded-procedures). At the very least the section needs to be updated to use C# terminology.

**Comment by BillWagner** [comment]
I think the link above should be [this topic](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-pooling#thread-pool-parameters-and-return-values)  @user135711 Can you confirm that we have that right?

**Comment by user135711** [comment]
@BillWagner That's correct.
