### ISSUE TITLE
DOCS pages NET9 add new #help directive features

### ISSUE THREAD

**Issue by jkone27** [dotnet/docs#43704]
### Type of issue

Typo

### Description

the new #help features released in F# 9 provide advanced functionalities to provide help in REPL, would be great to document them and add them to this docs page:

https://learn.microsoft.com/en-us/dotnet/fsharp/whats-new/fsharp-9#extended-help-directive-in-fsi-to-show-documentation-in-the-repl

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/tools/fsharp-interactive/index.md

### Document Version Independent Id

400ddb93-a841-963b-58cc-21f506b13b61

### Article author

@KathleenDollard

### Metadata

* ID: db36a87c-0928-52ce-38f3-1555e450cce1 
* Service: **dotnet-fsharp**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+400ddb93-a841-963b-58cc-21f506b13b61)

**Comment by jkone27** [comment]
cc @dawedawe

**Comment by shethaadit** [comment]
Hi, I will raise PR on this soon.
