### ISSUE TITLE
Expected Output from Partial Classes Code Example is Incorrect

### ISSUE THREAD

**Issue by aragubas** [dotnet/docs#43711]
### Type of issue
Code doesn't work

### Description

The code example shown in the "Partial Classes" sections says that the expected output is:
```
// Employee is working.
// Employee is at lunch.
```

but the code above doesn't have any Console.WriteLine statements, which makes the expected output actually, nothing

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/partial-classes-and-methods.md

### Document Version Independent Id

5e05ac12-7d29-d144-a49a-e54765343c20

### Article author

@BillWagner

### Metadata

* ID: 450a248b-ab3f-ac3f-d3a5-b1e74b3355ba 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+5e05ac12-7d29-d144-a49a-e54765343c20)

**Comment by BillWagner** [comment]
Thanks for point this out. I added this to our backlog to update in our next cycle. I also added the "help wanted" label if someone wants to submit a PR that adds the necessary `Console.WriteLine` statements.

**Comment by shethaadit** [comment]
Hi @BillWagner, I will work on this and raise PR soon.
