### ISSUE TITLE
Can't run .NET 9 apps on Fedora due to "dotnet-runtime-9.0" package pointing at rc.2.24473.5

### ISSUE THREAD

**Issue by matthewteeter** [dotnet/docs#43722]
### Type of issue

Code doesn't work

### Description

The Fedora 41 package dotnet-runtime-9.0 still installs RC2. 

Error will look like the following:

App: /app/MyApp.dll
Architecture: arm64 or amd64
Framework 'Microsoft.NETCore.App', version '9.0.0' (arm64)

The following frameworks were found:
  9.0.0-rc.2.24473.5 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-fedora?tabs=dotnet9

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-fedora.md

### Document Version Independent Id

2e9467f4-8572-c8e4-6a10-69faf14ce46c

### Article author

@adegeo

### Metadata

* ID: 38a30294-c9ae-4189-26d7-ee7db615c487 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+2e9467f4-8572-c8e4-6a10-69faf14ce46c)

**Comment by adegeo** [comment]
Sorry for the delay in response. Redhat is responsible for Fedora and .NET on Fedora. Please content them. It's possible the package has already been upgraded by now.
