### ISSUE TITLE
The article reference `WebClient` while the sample has been updated to use `HttpClient`

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#43744]
### Type of issue

Typo

### Description

The sample displayed on this page was updated in #43626 

However, the text in the article still references `WebClient`.

The article text should be updated as well.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/async-expressions

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/async-expressions.md

### Document Version Independent Id

ca52fed1-2956-1f51-e1c5-8a29e0a36679

### Article author

@KathleenDollard

### Metadata

* ID: 8bb27022-f56a-e122-7da0-9e00f52a8e73 
* Service: **dotnet-fsharp**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+ca52fed1-2956-1f51-e1c5-8a29e0a36679)

**Comment by shethaadit** [comment]
Hi @BillWagner, I have raised the PR for updating the documentation. :)
