### ISSUE TITLE
./dotnet-install.sh --version latest installs .net 8

### ISSUE THREAD

**Issue by keremkambur** [dotnet/docs#43773]
### Type of issue

Typo

### Description

I had to use --version 9.0.100 to install latest SDK

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-scripted-manual.md

### Document Version Independent Id

2be3647d-495b-c9f0-cf06-9a7bf687d3bb

### Article author

@adegeo

### Metadata

* ID: 885585df-1c7c-c774-34e4-4b274a7c2602 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+2be3647d-495b-c9f0-cf06-9a7bf687d3bb)

**Comment by adegeo** [comment]
Hello. As specified in that article, **latest** means the latest long-term support (LTS) release, which is .NET 8.

**Comment by piju3** [comment]
@adegeo The article explicitly says latest installs the "latest release, which might not be an (LTS) version".

**Comment by adegeo** [comment]
Sorry, I explained that wrong. If you run without a parameter, it installs the latest LTS. If you use `--version latest` it installs the latest.
