### ISSUE TITLE
[C# 13]: New Feature -

### ISSUE THREAD

**Issue by Vin757** [dotnet/docs#43813]
### Visual Studio release

None

### Link to speclet

- [Speclet](https://github.com/dotnet/csharplang/blob/main/proposals/feature.md)

### Link to Pull request

- [PR](https://github.com/dotnet/roslyn/pulls/nnnnn)

### New behavior

C

### Areas affected

- [x] **Add to What's new in C# 13**: Add links to updated docs in the What's new in C# 13 article.
- [x] **Update language reference**: Detail the areas in the language reference that will be updated for this feature.
- [x] **Update compiler messages**: Add new (or updated) pages for new compiler messages. Include related message.
- [x] *Include in *Everyday C#* section**: Is this new feature included in Everyday C#?
- [ ] **Tutorials**: Are new tutorials required for this feature? If so, detail below

**Comment by BillWagner** [comment]
closing as span
