### ISSUE TITLE
Add information on sealing for signtool.exe page

### ISSUE THREAD

**Issue by viertaxa** [dotnet/docs#4386]
The page for [SignTool.exe])https://github.com/dotnet/docs/blob/master/docs/framework/tools/signtool-exe.md) is missing information for activities related to sealing a PE file.

Specifically, the following flags are missing:
/seal
/itos
/force
/nosealwarn

Additionally, the tool is missing online documentation for several other flags and workflows. As someone working on incorporating Authenticode at the moment, better documentation on this tool would be a tremendous help.

**Comment by mairaw** [comment]
Thanks @viertaxa. You're right, the topic is quite outdated. I'm trying to locate the owner of the tool to identify when the changes were made, so you can call out versions appropriately.

For now, I'd recommend that you use the command help for that.

**Comment by mairaw** [comment]
This is what I got from @deskin:

"The flags were for a feature that we ended up choosing to not ship or support. They're intentionally undocumented."

But we'll review the docs in the future to see what is missing like the remove command.

**Comment by mattifestation** [comment]
Interesting. In the mean time, there is some public info regarding sealing since Microsoft is choosing not to document it publicly currently. https://vcsjones.com/2016/12/30/authenticode-sealing/
