### ISSUE TITLE
We need a place for Visual Studio based samples

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#439]
Our current samples directory has been optimized for developers on any platform, and using the command line. Our current [readme.md ](https://github.com/dotnet/core-docs/blob/master/samples/README.md) for the samples directory mandates that these samples don't have any dependencies on VS. 

I'm starting to write VS based samples (see issue #401). I think I should make a new directory under the core-docs root called 'visual-studio-samples'.  In time, there will likely be a third directory for samples based on using VS code. At that time, we can add a vs-code-samples directory as well.

/cc @blackdwarf @mairaw

**Comment by blackdwarf** [comment]
@BillWagner agreed on VS. Not on VS Code however, since VS Code doesn't really have a project system *per se*, or at least not a salient one (@cartermp & @mairaw take note). It just means that it can be used with the CLI-based ones as easily.

**Comment by mairaw** [comment]
Yes, we definitely need to define our sample structure ASAP.

**Comment by BillWagner** [comment]
I think we can close this, based on our new CI build system.

@cartermp @mairaw Can you vote on this?
