### ISSUE TITLE
Not an issue but a hope

### ISSUE THREAD

**Issue by FlauzerOriginal** [dotnet/docs#43900]
### Type of issue

Other (describe below)

### Description

We have seen many improvements in C# across different objectives. Improving _readability_ is also a goal. I would like to suggest that in the next versions, the old **with** construct (from the Paleolithic era of VB6 ....) allowed writing comfortably:

With objectExpression
    [ statements ]
End With

> With A 
   .prop1 = 1 
   .prop2 = 2 
   .prop3 = 3 
End With

Nothing extraordinary, but very 'readable' and not 'annoying' with the millions of objects we have to deal with today. I don't know if you agree, but I would love to see it in future versions of C#. 
Thank you anyway.

### Page URL

https://learn.microsoft.com/it-it/dotnet/csharp/fundamentals/types/interfaces

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/interfaces.md

### Document Version Independent Id

1f0a9a2b-6495-370d-620f-a6dabec7df3b

### Article author

@BillWagner

### Metadata

* ID: d9fd340a-0f74-8602-28a1-9569296a5951 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+1f0a9a2b-6495-370d-620f-a6dabec7df3b)

**Comment by BillWagner** [comment]
Hi @FlauzerOriginal 

You should file this as an issue in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository. That's where the C# LDM handles new feature requests.  The README has information on how to raise a new feature for discussion.

As the docs do represent the current design, I'll close this.
