### ISSUE TITLE
Public Token Error

### ISSUE THREAD

**Issue by adedola12** [dotnet/docs#43956]
### Type of issue

Other (describe below)

### Description

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS1069	The type name 'StringContent' could not be found in the namespace 'System.Net.Http'. This type has been forwarded to assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	LittleHelper	C:\Users\PC\source\repos\LittleHelper\LittleHelper\ChatGPTService.cs	62		
Error (active)	CS1069	The type name 'HttpClient' could not be found in the namespace 'System.Net.Http'. This type has been forwarded to assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.	LittleHelper	C:\Users\PC\source\repos\LittleHelper\LittleHelper\ChatGPTService.cs	52		

i keep getting this across several nuggets when installed![Image](https://github.com/user-attachments/assets/caa534ca-f941-4205-a5a9-743cf5f7bd0d)

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/assembly-references?f1url=%3FappId%3Droslyn%26k%3Dk(CS1069)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/assembly-references.md

### Document Version Independent Id

9dbb6834-202a-3e3b-e7e4-40ab7e85c2b6

### Article author

@BillWagner

### Metadata

* ID: 1dfdc2b3-0c7c-4607-32b3-0b5e8469579d 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+9dbb6834-202a-3e3b-e7e4-40ab7e85c2b6)

**Comment by BillWagner** [comment]
Hi @adedola12 

[This section](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-messages/assembly-references?#type-forwarding) of the doc in question should help you address the error.

Is there more information you need from this article?
