### ISSUE TITLE
vitual studio 2022

### ISSUE THREAD

**Issue by 2003fatima** [dotnet/docs#43968]
### Type of issue

Other (describe below)

### Description

when i run the application and the code clearly fine no issues on it , It shows me an error message which is : #CS0009 Metadata file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.Linq.dll' could not be opened -- An attempt was made to move the file pointer before the beginning of the file.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0009?f1url=%3FappId%3Droslyn%26k%3Dk(CS0009)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0009.md

### Document Version Independent Id

4c545bcb-5065-cc5e-8cca-f230324868c1

### Article author

@BillWagner

### Metadata

* ID: 6b572018-5b41-6831-4569-5d89fcaa4eb3 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+4c545bcb-5065-cc5e-8cca-f230324868c1)

**Comment by BillWagner** [comment]
Hi @2003fatima 

This might be a file corruption issue. Otherwise, I suggest posting a full code sample on our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) section to get specific help on your sample.
