### ISSUE TITLE
Downloaded PDF handles multiline links incorrectly

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4399]
When I download PDF for docs, the PDF has incorrect rectangles for links that span two different lines. For example, consider this text from page 25 of the PDF:

![](https://user-images.githubusercontent.com/287848/36214951-0407b99e-11ab-11e8-882d-a24b3a629be8.png)

When I click on any non-link text in this paragraph (e.g. the word "frameworks"), it's treated as if I clicked on the WPF link. I suspect that whatever tool is used to produce the PDF makes the bounding rectangle of the link text clickable. But in cases like the WPF link above, that bounding rectangle is too big.

This also means that some links cannot be clicked at all, because the bounding rectangle for one link is inside the rectangle for another link. This issue doesn't seem to occur in the above example, but it does happen, in the following paragraph on the same page:

![](https://user-images.githubusercontent.com/287848/36215391-4939bc6e-11ac-11e8-97e2-59890c4fc7f1.png)

Here, the ".NET Core Guide" link cannot be clicked, because clicking anywhere in the paragprah leads to the "Choosing" article.

**Comment by mairaw** [comment]
Opened internal bug to track this: 1191597

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/216
