### ISSUE TITLE
USER ISSUE

### ISSUE THREAD

**Issue by fodibaj** [dotnet/docs#43999]
### Type of issue

Missing information

### Description

The name 'Users' does not exist in the current context

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1056?f1url=%3FappId%3Droslyn%26k%3Dk(CS1056)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1056.md

### Document Version Independent Id

dba2048b-63fc-f425-b789-2e20f745ec2a

### Article author

@BillWagner

### Metadata

* ID: ac9b7928-5f13-0cec-e087-6f3e247e3805 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+dba2048b-63fc-f425-b789-2e20f745ec2a)

**Comment by BillWagner** [comment]
Hi @fodibaj 

For specific questions on your code, you should post a code sample on our [Q & A](https://learn.microsoft.com/en-us/answers/tags/309/csharp) site.

I don't see any request for a documentation update here. I'll close this.
