### ISSUE TITLE
C# 13 Implicit index access example

### ISSUE THREAD

**Issue by tmds** [dotnet/docs#44001]
### Describe the issue or suggestion

The section on implicit index access (https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#implicit-index-access) shows some example code which doesn't include the `TimerRemaining` definition.

Then the text says:

> The preceding example creates an array that counts down from 9 to 0.

The example doesn't show that the array was already created by the `TimerRemaining` type (probably of length 10). It could be misunderstood that the object initializer shown in the example is instantiating the array.

It would be more clear if the `TimerRemaining` definition is included in the example.

cc @BillWagner

**Comment by BillWagner** [comment]
Thanks for the comment @tmds 

I'll add this to our backlog, and add the "help wanted" label, in case anyone wants to update the sample before we make an update.

**Comment by shethaadit** [comment]
Hi @BillWagner, I will raise the PR for this soon. :)
