### ISSUE TITLE
C# learning

### ISSUE THREAD

**Issue by deepakgupta311** [dotnet/docs#44005]
### Type of issue

Thank you

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/strategy

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/strategy.md

### Document Version Independent Id

e9fe3f62-9cba-16cf-70c4-a9b77346932e

### Article author

@BillWagner

### Metadata

* ID: 184c9a5a-9ac4-895b-f388-1a96105cdfd6 
* Service: **dotnet-csharp**
* Sub-service: **get-started**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+e9fe3f62-9cba-16cf-70c4-a9b77346932e)

**Comment by BillWagner** [comment]
Thank you for the comment @deepakgupta311 

Closing as kudos.
