### ISSUE TITLE
[Feature] Span<T>

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#4400]
# Span\<T\>
This topic will address how to work with Span<T> and related types. Span<T> is a new type we are adding to the platform to represent contiguous regions of arbitrary memory, with performance characteristics on par with T[]. Its APIs are similar to the array, but unlike arrays, it can point to either managed or native memory, or to memory allocated on the stack.

*Still Needed:*
 - [ ] Content Types
 - [ ] Table of Contents
 - [ ] Prioritization

**Comment by joshfree** [comment]
@ahsonkhan @GrabYourPitchforks

**Comment by JimBobSquarePants** [comment]
Current 2.0 Docs are picking up on the obsolete attribute which is causing confusion.

https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.0

**Comment by mairaw** [comment]
Thanks @JimBobSquarePants. This seems related to the following issues that we're tracking:
https://github.com/dotnet/docs/issues/1876
https://github.com/mono/api-doc-tools/issues/76

@weshaggard I see that the obsolete attribute was added with the addition of the .NET Core 2.1 reference assemblies. Is Span<T> really marked as obsolete in 2.1?

**Comment by JimBobSquarePants** [comment]
@mairaw See the below link for reasoning behind the obsolete attribute

https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#metadata-representation-or-ref-like-structs

**Comment by ahsonkhan** [comment]
cc @VSadov

**Comment by mairaw** [comment]
I've created a workaround PR to fix the obsolete attribute issue while the true fix is being worked out:
https://github.com/dotnet/dotnet-api-docs/pull/49

**Comment by OnurGumus** [comment]
@mairaw Obsolete attribute blocks the F# compiler for span.

**Comment by mairaw** [comment]
@cartermp can you look at this previous comment?

**Comment by cartermp** [comment]
It doesn't affect these docs. When we take a look at proper span support in the F# compiler that particular issue will be addressed.

**Comment by OnurGumus** [comment]
Perhaps this is not correct place to rant but there is a tendency to treat C#== .NET. It seems for BCL and runtime changes languages like F# is completely ignored or afterthought. Same things happened with .NET Native, ValueTuple, default interface implementations etc. I just wish things were more lang agnostic.

**Comment by ahsonkhan** [comment]
Should we re-open this issue given we still have APIs to document? For example [ReadOnlySpan](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?view=netcore-2.0)?

This PR covered a subset of the APIs: https://github.com/dotnet/dotnet-api-docs/pull/194

**Comment by rpetrusha** [comment]
No, we don't need to reopen the issue, @ahsonkhan. ReadOnlySpan will be documented shortly, after I finish a second round of updates to Span<T>.

**Comment by mairaw** [comment]
I was discussing about this item with @JRAlexander the other day and I think this item was to cover conceptual docs for Span<T> and friends. So we might need to reopen this.
