### ISSUE TITLE
Add information about recursion at f#

### ISSUE THREAD

**Issue by Denys-Bushulyak** [dotnet/docs#44021]
### Type of issue

Missing information

### Description

I would like to add this sentence if it’s relevant:

>The .NET runtime (CLR) supports tail call optimization, and F# takes advantage of this support to ensure tail-recursive calls are optimized, even when working in the broader .NET ecosystem.

### Page URL

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fsharp/language-reference/functions/index.md

### Document Version Independent Id

71e8487a-16d2-1b9e-9bbc-a48884196673

### Article author

@KathleenDollard

### Metadata

* ID: e16a9ad9-820d-c4cf-df83-d9c33a848d74 
* Service: **dotnet-fsharp**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+71e8487a-16d2-1b9e-9bbc-a48884196673)

**Comment by KathleenDollard** [comment]
@T-Gro Can you confirm this sentence.

@BillWagner It is not clear to me where this sentence is intended to go. At the end of the last para, first section?

**Comment by Denys-Bushulyak** [comment]
Thank you, @KathleenDollard, @T-Gro, and @BillWagner. I have reviewed my proposal after revisiting the page, and I believe the existing description of recursion is clear and complete, so it does not require any additional comments from me.
