### ISSUE TITLE
Resource leak (or at least a CA2000 warning) in RegistryKey example

### ISSUE THREAD

**Issue by paulirwin** [dotnet/docs#44083]
### Type of issue

Other (describe below)

### Description

The example code at this page results in a CA2000 code analysis warning when enabled, about the call to OpenBaseKey not being properly disposed. This possibly represents a resource leak, although I'm having trouble tracking that down definitively at source.dot.net due to the partial classes.

Instead of:
```c#
using (var ndpKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(subkey))
{
...
}
```

This resolves the warning:
```c#
using (var baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32))
using (var ndpKey = baseKey.OpenSubKey(subkey))
{
...
}
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#query-the-registry-using-code

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md

### Document Version Independent Id

a3790e8a-0654-851b-c991-ab7382025406

### Article author

@gewarren

### Metadata

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf 
* Service: **dotnet-framework**
* Sub-service: **app-compat**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+a3790e8a-0654-851b-c991-ab7382025406)

**Comment by shethaadit** [comment]
Hi @gewarren, I will work on this and raise PR soon. Could you please assign me the bug?
