### ISSUE TITLE
What is the point of the mdoc document?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4408]
[Building documentation with mdoc](https://docs.microsoft.com/en-us/dotnet/standard/mdoc/) says:

> mdoc is a documentation build system for managed reference documentation. By reflecting over your assemblies, mdoc creates the basic format of your managed reference documentation, which it supplements with authored content.

That's it, that's the whole document. I think on its own, this document is not useful at all, since it doesn't really explain anything. In fact, I think it's actively harmful: it takes up space in the TOC and in Google search results (<span>#</span>1 for "mdoc .net"), but doesn't provide any useful information. Because of that, I think it should be deleted. Do you agree?

The PR that created it (https://github.com/dotnet/docs/pull/3599) says that it's "stub for mdoc content". I don't understand why would that be useful. If more content is coming in the future, the article can be recreated then.

cc: @rpetrusha

**Comment by mairaw** [comment]
That was supposed to be finished right after the stub was created. @dend last I checked with you, you were going to work on this over the holidays. I agree with @svick that in its current state, it’s better to pull it off.

**Comment by dend** [comment]
There will be content by EOW @svick @mairaw

**Comment by mairaw** [comment]
Thanks @dend! I’ll assign this issue to you then.

**Comment by BillWagner** [comment]
Ping @dend Any updates here?
