### ISSUE TITLE
Remove xUnit support document of `GenerateTestingPlatformEntryPoint`

### ISSUE THREAD

**Issue by filzrev** [dotnet/docs#44090]
### Type of issue

Code doesn't work

### Description

> Setting the GenerateTestingPlatformEntryPoint property to false disables the automatic generation of the program entry point in an MSTest, NUnit, or xUnit test project.

There is `MSTest, NUnit, or xUnit test project.` statement.
But `GenerateTestingPlatformEntryPoint ` property is not supported by `xUnit`. And it's not works as described.

It is not be expected to be supported in the future. 
So the reference to `xUnit` should be deleted from `GenerateTestingPlatformEntryPoint` property document .

See : https://github.com/xunit/xunit/issues/3106

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generatetestingplatformentrypoint

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props.md

### Document Version Independent Id

6741b1de-38a4-fbb1-d79d-acc47d549a2d

### Article author

@gewarren

### Metadata

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+6741b1de-38a4-fbb1-d79d-acc47d549a2d)

**Comment by bradwilson** [comment]
To be clear, what @filzrev is referring to is xUnit.net v3, where all test projects are already stand-alone executables with entry points that we inject during build. As a result, we turn off `GenerateTestingPlatformEntryPoint` automatically in our NuGet package: https://github.com/xunit/xunit/blob/9853a4b92a41b0129c30a70cd040ea5213a016c6/src/xunit.v3.core/Package/build/xunit.v3.core.props#L9-L10

This mirrors behavior that we use to turn off entry point generation by VSTest: https://github.com/xunit/xunit/blob/9853a4b92a41b0129c30a70cd040ea5213a016c6/src/xunit.v3.core/Package/build/xunit.v3.core.props#L5-L6

-----

xUnit.net versions prior to v3 do not support Microsoft.Testing.Platform at this time. There is an issue opened by @MarcoRossignoli to add support, with an implementation to be provided by the VSTest team: https://github.com/xunit/visualstudio.xunit/issues/416

At this point in time, I have no insight as to whether this is being actively worked on and/or what the delivery date might be.
