### ISSUE TITLE
DES Sample uses Incorrect Class

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#4413]
# Issue Title

The sample for System.Security.Cryptography.DES uses TripleDES class not DES class

# General

Looking at the sample on https://docs.microsoft.com/en-gb/dotnet/api/system.security.cryptography.des?view=netframework-4.7.1 - this sample used the TripleDES class, not the DES class.

**Comment by mairaw** [comment]
Thanks @doctordns. Given that we're doing a security review project and DES should not be used (https://github.com/dotnet/docs/projects/33), I'll pull that sample out.

**Comment by doctordns** [comment]
Is MSFT taking out this class totally?

**Comment by mairaw** [comment]
Sounds good @doctordns. I was just going to say that I don't think it's worth adding a new sample if we're recommending folks not to use that algorithm anymore.
