### ISSUE TITLE
New Content: Topic on .NET Standard and its relationship to .NET Core

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#443]
We need topic that discusses .NET Standard, defines what it is, and clarifies its relationship to the desktop framework and .NET Core. Here is a very preliminary outline:

What is the .NET Standard?

.NET Standard and binary portability
- Why is binary portability is important?
- What limitations in binary portability does .NET Standard address?
- How does .NET Standard address binary portability? 

.NET Standard and the .NET Framework
- What is the relationship between .NET Standard and .NET Core
- What is the relationship between .NET Standard and the desktop .NET Framework

.NET Standard versioning
- How does .NET Standard versioning relate to .NET Core?
- How does .NET Standard versioning relate to the desktop .NET Framework?

What's in the .NET Standard?
- What contracts are included in the .NET Standard?

**Comment by IEvangelist** [comment]
This was always a good starting point from my perspective that seemed to help those visualize the concept driving **.NET Standard**.

![image](https://cloud.githubusercontent.com/assets/7679720/15368851/98b35fd2-1cf5-11e6-90d1-e5c44a623f74.png)

**Comment by mairaw** [comment]
Is this done @rpetrusha?

**Comment by cartermp** [comment]
This is covered a bit here: https://docs.microsoft.com/en-us/dotnet/articles/standard/components

There may be a need for a more low-level article.

**Comment by mairaw** [comment]
@rpetrusha is there more work here? I know we need to update that topic for enhancements and changes, but I'm wondering if the basics are already covered.

**Comment by rpetrusha** [comment]
@mairaw No, I think that the basics are already covered. I'll close this.
