### ISSUE TITLE
String concatenation with string.Join

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4433]
[The How-To on string concatenation](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings) doesn't mention [String.Join](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-4.7.1) method. One might say that it is not pure concatenation as we use separator, but the last paragraph uses LINQ to join string with space separator. Performance-wise Join uses StringBuilder inside. @BillWagner if you think the section should be updated with Join mention and examples, I'm willing to update it.

**Comment by BillWagner** [comment]
That is a great idea, @pkulikov I'd be happy to have you update the How-to so that it includes string.Join.

I've assigned this to you, and set it in the backlog milestone. @- mention me when you have a PR, and I'll review it.
