### ISSUE TITLE
Request for clarification on readonly struct

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4441]
From a livefyre comment on [this article](https://docs.microsoft.com/dotnet/csharp/reference-semantics-with-value-types).

I'm wondering, if my read-only struct contains a value type field, and that value type (struct) is NOT readonly, will in that case compiler still do defensive copies when I call methods on such fields (remember, the fields are forced to be readonly)? Is there any difference with this for primitive value type fields (int, float) and for "complex" structs? For example:

```csharp
readonly struct MyStruct
{
   private readonly int value;

   public MyStruct(int value)
   {
      this.value = value;
   }

   public override string ToString()
   {
       // Defensive copy?
       return value.ToString();
   }
}
```

**Comment by andriysavin** [comment]
Thanks for creating the issue. I also commented about that in another issue: https://github.com/dotnet/docs/issues/3907#issuecomment-366692500
