### ISSUE TITLE
Dead link in WIF WCF Docs

### ISSUE THREAD

**Issue by biltongza** [dotnet/docs#4461]
On https://github.com/dotnet/docs/blob/master/docs/framework/security/building-my-first-claims-aware-wcf-service.md, the last link in the doc, "To build your first claims-aware WCF service using WIF, see How To: Build Claims-Aware WCF Service Using WIF." is dead.

**Comment by BillWagner** [comment]
Thanks for pointing this out.  We've added it to the backlog. If you have thoughts on the correct link, do you want to submit a PR for this?

**Comment by mairaw** [comment]
Perhaps we should link to this topic instead:
https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-enable-wif-for-a-wcf-web-service-application

**Comment by rpetrusha** [comment]
That's probably the best option.
