### ISSUE TITLE
WIF docs out of date

### ISSUE THREAD

**Issue by biltongza** [dotnet/docs#4462]
The docs describing enabling WIF for a WCF service are out of date and don't actually describe what to do other than use a tool that can only be used in VS2012. https://github.com/dotnet/docs/blob/master/docs/framework/security/how-to-enable-wif-for-a-wcf-web-service-application.md

It would be great if the docs explained what the tool actually did or if the tool were updated to support newer versions of VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d06de2-187b-5f12-7602-9cdc4c6cfc2a
* Version Independent ID: 32272b16-0d95-991a-fd60-cb94d407dc8a
* Content: [How To: Enable WIF for a WCF Web Service Application](https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-enable-wif-for-a-wcf-web-service-application)
* Content Source: [docs/framework/security/how-to-enable-wif-for-a-wcf-web-service-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/how-to-enable-wif-for-a-wcf-web-service-application.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
