### ISSUE TITLE
Numbers tutorial should mention that double and decimal have no implicit conversions

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4466]
Taken from dotnet/try#53.

> I entered code on the Numbers Challenge page and the '*' between the two 'radius' variables was flagged by the error indicator. The message indicated that the operator was not valid between a double and a decimal. The variable was declared as double.

This challenge should be done using the double type.

**Comment by BillWagner** [comment]
Tagging @ga69russ to follow the conversation here.

**Comment by ga69russ** [comment]
I appreciate your help, Bill, but I had all variables declared as double and it still flagged the error. I have been working with C# with various self-studies and personal projects so I am aware of some the problems with implicit conversions.

 

Glenn

**Comment by svick** [comment]
@ga69russ In that case, I think we would have to see your code to figure out what went wrong. You said in the other issue that you don't have it anymore. Would you be willing to recreate it and see if you encounter the same issue?

**Comment by ga69russ** [comment]
Here is the code. It works fine now. However, there is an error flag under the period between Console.Writeline. I typed println at first and it was flagged so I corrected it to Writeline. On the previous coding I had corrected the types from decimal to double. I think the problem is that the corrections are not recognized by the error checker and it continues to flag error after they have been corrected.

 

Glenn Russell

**Comment by ga69russ** [comment]
Sorry, I forgot to include the code.

 

double radius = 2.50;

double c = radius * radius * Math.PI;

Console.WriteLine(c);

 

Glenn Russell

**Comment by BillWagner** [comment]
I may have figured it out.

If you didn't remove the code from the previous step, you would end up with something like this:

```csharp
double a = 1.0;
double b = 3.0;
Console.WriteLine(a / b);

decimal c = 1.0M;
decimal d = 3.0M;
Console.WriteLine(c / d);

double radius = 2.50;
c = radius * radius * Math.PI;
Console.WriteLine(c);
```

That would produce this error:

```txt
(10,5): error CS0266: Cannot implicitly convert type 'double' to 'decimal'. An explicit conversion exists (are you missing a cast?)
```

Does that look like what's happening?

**Comment by svick** [comment]
> However, there is an error flag under the period between Console.Writeline. I typed println at first and it was flagged so I corrected it to Writeline. 

Yeah, I can reproduce this in Edge (this is after running the code after fixing it):

![](https://user-images.githubusercontent.com/287848/36574160-948a250c-1844-11e8-9f38-f41ae3f31c03.png)

**Comment by ga69russ** [comment]
Yes and no. I had removed the previous sample before coding the challenge but when I corrected the types on the variables the flagging persisted.  I figured out what was happening when the flagging persisted on the example I sent your colleague. 

 

Glenn

**Comment by BillWagner** [comment]
Ping @LadyNaggaga is this an issue with the intellisense display?

**Comment by BillWagner** [comment]
After investigation, I'm going to close this, as it appears to be a duplicate of dotnet/try#41

@ga69russ If it shows up again, please reopen and include the code.

**Comment by ga69russ** [comment]
I’m sorry you are still seeing this. I no longer have interest in the subject. Go ahead and close it.

 

Glenn Russell
