### ISSUE TITLE
date of SQL Server data type don’t work System.Data.DbType. modify documents?

### ISSUE THREAD

**Issue by OdaShinsuke** [dotnet/docs#4474]
[Can’t set SqlParameter.DbType to Date](https://github.com/dotnet/corefx/issues/21279)

this problem not fixed.
https://github.com/dotnet/corefx/issues/21279#issuecomment-365087011
> Closing this as the bug was carried over from framework, and in framework it was not fixed for back compat reasons

modify two documents?
* https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings
* https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/date-and-time-data

**Comment by mairaw** [comment]
Adding @douglaslMS to take a look at this.
