### ISSUE TITLE
REPL Issue in Edge

### ISSUE THREAD

**Issue by CliffAgius** [dotnet/docs#4492]
Edge Browser the REPL styling on the page is causing an issue.

Using the EDGE Browser while completing the C# Getting started "Hello World!" with my son's Yr6 Class (10/11 year olds) the school laptops are locked to Edge for online security reasons.

The kids tried to enter the code but the REPL had the Line 1 in the Editor behind the Bar with the Run button so it could not be seen.

Got permission from the teacher and rebooted the computers into Teacher accounts and used Chrome and it worked fine.

**Comment by BillWagner** [comment]
ping @yunyunyunyun Is this an issue with the REPL engine?

**Comment by BillWagner** [comment]
@CliffAgius Do you know the screen resolution for this issue? That might be relevant here.

**Comment by CliffAgius** [comment]
@BillWagner Just heard back from the school the laptops are HP machines with a screen resolution of 1920 x 1080.

I must admit I didn't think to try changing the browser size it was just full screen (Not full screen like F11 mode).

However one question about the REPL could it not be made such that it can be made to pop out into another window so that the Editor and Output windows will the new window and thus give the user more space If they want it.

Here is a screen shot I got from the school yesterday when typing Console in the REPL and it show the issue.
![screenshot](https://user-images.githubusercontent.com/5613809/36727824-94a60f36-1bb6-11e8-996c-10f4f556b36b.png)

**Comment by mairaw** [comment]
Moved this issue to the more general site feedback repo: https://github.com/MicrosoftDocs/feedback/issues/215
