### ISSUE TITLE
REPL Clear Button

### ISSUE THREAD

**Issue by CliffAgius** [dotnet/docs#4493]
Completing the C# Getting started "Hello World!" with my son's Yr6 Class (10/11 year olds) and a suggestion from one of the kids was why is there no Clear button to empty the Editor window?

Suggest this would not be a big one to add, also from another child there is a way to copy the code from the code block using the Copy  button but no Paste button.  I told her she had to type the code which was met with groans...

**Comment by BillWagner** [comment]
ping @yunyunyunyun Is this an issue with the REPL engine?

**Comment by pkulikov** [comment]
@CliffAgius I agree it's strange that there is no Paste button or Paste option in the right-click menu. As an interim solution Ctrl+V keyboard shortcut might work to paste copied content.

**Comment by mairaw** [comment]
Moved the issue to the more general site feedback repo: https://github.com/MicrosoftDocs/feedback/issues/214
