### ISSUE TITLE
[Revision] Consolidate and revise Assemblies documentation

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4494]
# Consolidate and revise Assemblies documentation

In migrating documentation from MSDN to docs.microsoft.com, we've managed to create virtually identical documentation on assemblies in three separate sections of the documentation: for C#, for Visual Basic, and for the .NET Framework. However, aside from an **assembly** keyword that indicates that a program element such as an attribute applies to an assembly, language elements do not support assemblies. This triplication should be eliminated and the majority of the documentation placed in the .NET Guide section.

See also #6181: **Assemblies: Combine C# and VB sections into a single .NET Guide doc set**

### C# documentation

- The top-level C# [Assemblies and the Global Assembly Cache](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/) documentation and its children should be removed after any of its unique content has been incorporated into the .NET Standard docs.
- The URL for each deleted topic should be entered in the redirection file to redirect it to the version of the topic in the .NET docs.

### Visual Basic documentation

- The top-level Visual Basic [Assemblies and the Global Assembly Cache](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/assemblies-gac/) section and its children should be removed after all its unique content has been migrated to the .NET Framework docs.
- The URL for each deleted topic should be entered in the redirection file to redirect it to the version of the topic in the .NET docs.
- All the topics have Visual Basic equivalents that are completely or largely identical to the C# topics. They should be moved to the .NET Guide, with both VB and C# code examples appearing in the same topic.
- Since assemblies are used by both .NET Core and the .NET Framework, the documentation on assemblies should be located in the TOC in the .NET Guide.
We should decide whether to place this section in the .NET Standard guide (which would be my choice) or leave it in the .NET Guide.

### .NET Guide
There should be some consolidation of content and review of content in the [.NET Guide](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assemblies-in-the-common-language-runtime), since the content itself may be dated, and adding unique material from the C# and VB guides requires an overall review of the .NET documentation for consistency. Each topic in the .NET Guide should be reviewed to ensure that it is current and accurate and, if necessary, revised. 

The TOC should be revised to realect new content.

**Comment by mairaw** [comment]
@rpetrusha is this issue and #6181 the same?

**Comment by rpetrusha** [comment]
Yes, it is the same, @mairaw. Let's keep this issue open, and I'll close #6181.

**Comment by lucasnobredev** [comment]
@BillWagner about the closed PR, honestly, I didn't ask because it was really clear to me the location of new article and the issue seems to be ready. Actually, I already merged it before in #6181. 

You said that you're discussing about organization of articles. So this issue is really not ready to contribute? Please, share with community when you know how to proceed.

**Comment by BillWagner** [comment]
@lucasnobredev Thanks for understanding. We recognize that we need to do this better. It's a challenge now because we've only started thinking about what the journey to .NET 5 looks like. 

We'll continue to improve, and we appreciate everyone that is helping us get there.
