### ISSUE TITLE
 .NET Core Global Tools Part 1: Global tools overview, sdk commands, how to use it

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#4509]
This Part 1 of 3 topics will address the .NET Core Global Tools. .NET Core now has a new deployment and extensibility mechanism for tools. This new experience is very similar to and was inspired by NPM global tools.
Part 1: global tools overview, sdk commands, how to use it - This Topic
Part 2: how to create new global tools - #6016
Part 3: update extensibility topic - #6017

**Comment by richlander** [comment]
Here is some starter content: https://github.com/dotnet/core/tree/master/samples/dotnetsay

**Comment by mairaw** [comment]
Cool. I'm meeting with @KathleenDollard tomorrow to discuss this. 

It seems that we need to at least:
- document dotnet install
- update the [extensibility topic](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility) to cover global tools
- perhaps a new how-to or tutorial on creating and installing global tools?

Thoughts?

**Comment by KathleenDollard** [comment]
Maybe we need an hour :)

**Comment by dasMulli** [comment]
> perhaps a new how-to or tutorial on creating and installing global tools?

Since the topic of copy&pasting from blogs has come up on asp.net, happy to help/allow copying from https://dasmulli.blog/2018/01/23/exploring-global-net-core-tools/ ([the blog content is MIT already](https://github.com/dasMulli/dasmulli.github.io/blob/develop/LICENSE))

**Comment by mairaw** [comment]
Thanks for the offer @dasMulli. I'll take a look once I'm ready to move to part II which will cover the creation of global tools in a few days.

**Comment by mairaw** [comment]
Fixed with PR #5036
