### ISSUE TITLE
Improve the community experience for PRs and issues

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4510]
Our contributor guide has not kept up with any recent GitHub features. Also, other teams have adopted practices that we can use to improve. I propose making these updates:

1. The PR template recommends @- mentioning team members to review PRs. We can now use the "Request review" feature, which is easier for us to search on. We should update with that recommendation.
1. We can help our community tag the appropriate people by supplying a [guide to owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md) page following the example of the CoreFx team.

Open questions for the team:
- How detailed do we want to be on ownership? "Guide" level? Major sections below "Guide level"? 
- Do we include product team members in the list of potential reviewers?

**Comment by mairaw** [comment]
I wouldn't add product members as potential reviewers. I think we should ping them as needed.

I also think we should have the same templates between aspnet/docs and dotnet/docs. I like the fact that aspnet/docs has a shorter template since a lot of folks seem to ignore the template anyway.

For detailed, I think that Guide level and/or major sections make sense. It depends on the area. Languages could be Guide, others would depend.

**Comment by rpetrusha** [comment]
I agree with @mairaw that we shouldn't add product members as reviewers, nor is it necessary that community contributors do; we can either @ ping them or add them as reviewers on an ad hoc basis.

**Comment by Rick-Anderson** [comment]
For the ASP.NET Repo, we removed @- mentioning team members to review PRs  
Because typo PR's would come in with lots of dev mentions, PM mentions, too many mentions. We triage PR's quickly and we know who to mention. 
Removing that advice was a big improvement for us.

> I like the fact that aspnet/docs has a shorter template since a lot of folks seem to ignore the template anyway.

I would say 90% ignore it.

**Comment by mairaw** [comment]
@BillWagner should we close this issue? Since then, we've updated the PR template to be much shorter, which I like it a lot. And we've been maintaining the code owners file as needed.

**Comment by BillWagner** [comment]
@mairaw The only other recommendation is to publish the list of owners, if we wanted. Using the code owners feature, I don't think it's necessary.

Upvote to close. Downvote to add the "who owns what" file. 
/cc @rpetrusha @JRAlexander

**Comment by BillWagner** [comment]
Closing based on above votes and @mairaw 's comments.
