### ISSUE TITLE
Broken Interop links on docs.*

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#4514]
The following three links are broken:

Source: https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-behavior
Context: Marshaling of generic types is not supported. For more information see, Interoperating Using Generic Types.
Broken link: Interoperating Using Generic Types --> https://msdn.microsoft.com/library/26b88e03-085b-4b53-94ba-a5a9c709ce58

Source: https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-create-wrappers-manually
Context: As with the types imported with Tlbimp.exe, some require additional information, which you can add directly to your code. For details, see How to: Edit Interop Assemblies.
Broken link: How to: Edit Interop Assemblies --> https://msdn.microsoft.com/library/16aacb20-2269-42bf-a812-b6a7df17e277

Source: https://docs.microsoft.com/en-us/dotnet/framework/tools/tlbimp-exe-type-library-importer 
Context: publisher of the type library that you are importing with Tlbimp.exe. Note that you must sign a primary interop assembly with a strong name. For more information, see Primary Interop Assemblies.
Broken link: Primary Interop Assemblies --> https://msdn.microsoft.com/library/b977a8be-59a0-40a0-a806-b11ffba5c080

**Comment by mairaw** [comment]
Thanks @jeffschwMSFT. We're trying to clean up all these links over time.

@rpetrusha what do you think? It seems that the interop area had a bunch of content restructuring in the past. Should we change the links to point to the archive version or start removing these interop links?

**Comment by rpetrusha** [comment]
I think that we should point to the archive version, @mairaw. The interop documentation wasn't so much restructured as topics were removed wholesale in preparation for the migration to CAPS based purely on page views. The result is that the doc set was pared down far too much, and some essential topics were removed. I don't think that it's really possible to do interop successfully without the fuller doc set, and most of it is now archived.

**Comment by mairaw** [comment]
Ok @rpetrusha, thanks for sharing the history on those topics here. So let's adjust them to point to the archive version on msdn. Once they move to docs, we can decide to bring them back to live if we have time and demand for that.

**Comment by rpetrusha** [comment]
That sounds good, @mairaw. At some point, I'd really like to evaluate what we should bring back into the doc set and what we should leave archived.
