### ISSUE TITLE
[Feature] HttpClient Listener rewritten for performance

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#4541]
# HttpClient Listener rewritten for performance

For HttpClient, we built a new from-the-ground-up managed HttpClientHandler called SocketHttpHandler. As you can likely guess, it’s a C# implementation of HttpClient based on .NET sockets and Span<T>.

The biggest win of SocketHttpHandler is performance. It is a lot faster than the existing implementation. There are other benefits:

Elimination of platform dependencies on libcurl (for linux) and WinHTTP (for Windows) – simplifies both development, deployment and servicing
Consistent behavior across platforms and platform/dependency versions.
You can opt-in to using the SocketHTTPHandler in one the following ways with Preview 1:

Environment variable: COMPlus_UseManagedHttpClientHandler=true
AppContext: System.Net.Http.UseManagedHttpClientHandler=true

*Still Needed:*
 - [ ] Content Types
 - [ ] Table of Contents
 - [ ] Prioritization

 If you know someone who can provide feedback, use '@' to ask them to review.

**Comment by mairaw** [comment]
Let's just add this to the what's new topic: https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1
