### ISSUE TITLE
when keyword (at least as used with catch) could bear more details

### ISSUE THREAD

**Issue by Narvey** [dotnet/docs#4543]
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/when.md Doesn't give any sort of indication of the very important fact that "the When expression is evaluated before the callstack is unwound to the Catch block" ([source](https://stackoverflow.com/a/116424/1739000)). Now, yes, StackOverflow serves as the unofficial documentation for undocumented things in .NET, but it would still be nice to make the official documentation more complete when possible.

Another thing I'd like to see documented is what happens when an exception happens within a when clause? does the stack unwind to the current catch block and go through its instructions? does it skip the current catch and unwind to whatever catch block it can find further up? does it not unwind at all (that would be wacky)?

**Comment by BillWagner** [comment]
Thanks for writing this up @Narvey 

I've added to an upcoming sprint, and prioritzed it.
