### ISSUE TITLE
Horizontal scroll on narrow screens cuts off table content

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4554]
See image below:

![image](https://user-images.githubusercontent.com/4837132/36937732-bc653df6-1f0f-11e8-8735-81d31409cddc.png)

Seen on https://docs.microsoft.com/en-us/dotnet/standard/exceptions/ 

On a narrow screen, the main content panel has a slight horizontal scroll bar, but it doesn't scroll far enough to view all content, the ends of lines inside the table are still cut off.

My screen is 1280x1024, this was in Chrome 64.0.3282.186.

**Comment by rpetrusha** [comment]
Portions of the table also appear to be inaccurate and need careful review.

**Comment by BillWagner** [comment]
There are other issues with this table:

1. The second column is misleading.  Many of the exceptions listed have intervening base classes between the type in the 1st column and the type listed in the 2nd column.
1. The Example column may be too broad in recommending that some of the types not be used at all.

**Comment by mairaw** [comment]
@ChrisMaddock I've opened PR #6033 to remove the misleading column and added some line breaks to help with the table.

But we also have a tracking bug with the engineering team for tables in docs:
https://github.com/MicrosoftDocs/feedback/issues/336
