### ISSUE TITLE
Old screenshots for using .NET Core CLI with VSTS

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#4564]
https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli#visual-studio-team-services-vsts

The VSTS build definition screenshots and instructions are dated.

**Comment by mairaw** [comment]
We might just wanna link to some existing content from VSTS instead?
https://docs.microsoft.com/en-us/vsts/build-release/apps/aspnet/build-aspnet-core
https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/dotnet-core
https://www.visualstudio.com/team-services/support/build-deploy-asp-net-core-app-azure/

**Comment by mairaw** [comment]
Also, if we wanted to make the docs topics to show up in our own TOC and not just link to the content, I know there are options, I just never tried.
