### ISSUE TITLE
Instance methods from object shouldn't show on static classes

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4577]
API reference for static classes includes instance methods inherited from `object`. They technically do exist on those types (since static classes are actually abstract sealed classes that derive from `object`), but cannot be used in any reasonable way, so I think they shouldn't be shown in API reference.

For example, look at `Console`. Its [list of methods on docs.MS](https://docs.microsoft.com/en-us/dotnet/api/system.console?view=netframework-4.7.1#Methods) contains methods like `GetHashCode()` or `GetType()`:

![](https://user-images.githubusercontent.com/287848/37156823-715547d0-22e7-11e8-8a3a-55dd1e31ed7a.png)

Compare this with [MSDN](https://msdn.microsoft.com/en-us/library/system.console(v=vs.110).aspx#Anchor_3), where these methods are not shown:

![](https://user-images.githubusercontent.com/287848/37156923-b087473c-22e7-11e8-8e2c-7a2e1be31e17.png)

**Comment by mairaw** [comment]
We should open an internal bug for this @BillWagner. We had a similar bug before where we were showing static members as inherited members. This is related but slightly different.

Also @svick, now that our feedback for Docs moved to GitHub issues as well, we should start filing these kind of bugs that we usually flagged as external here before using the Feedback link from Docs (https://aka.ms/sitefeedback). That way the engineering team will be the ones triaging them and they will tag us if needed.

That way, we focus here on pure content issues and site issues go to the other repo. Makes sense? 
We can also move the issues as well if they're filed here.

**Comment by mairaw** [comment]
Opened internal bug #1203839. Marked as blocking @dend since behavior is correct on MSDN.

**Comment by svick** [comment]
@mairaw Understood. Feel free to move the issue if you want.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/213
