### ISSUE TITLE
dotnet nuget push docs query

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4585]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push

This page confused me a little. The docs had this synopsis:

```
dotnet nuget push [<ROOT>] [-s|--source] [-ss|--symbol-source] [-t|--timeout] [-k|--api-key] 
[-sk|--symbol-api-key] [-d|--disable-buffering] [-n|--no-symbols] [--force-english-output] ]
[-h|--help]
```

And then state for `ROOT`:
```
ROOT
Specify the path to the package and your API key to push the package to the server.
```

However all the examples pass the api key under the `-k` flag. I can't see how it could be passed additionally with the filepath in the ROOT parameter - is this a documentation error, or just an undocumented syntax instead?

**Comment by mairaw** [comment]
@karann-msft can you look at this question?

**Comment by karann-msft** [comment]
It is a documentation error. Root is the only required parameter. Let's update it to only say "specify the path to the package."
cc: @anangaur

**Comment by ChrisMaddock** [comment]
Thanks both - PR submitted!
