### ISSUE TITLE
How to: Implement Binding Validation is missing the VB sample

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4589]
Topic: https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-binding-validation 

A recent PR (#4584) made me realize that the sample being changed wasn't used anywhere. The C# version of that sample is present here: https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-binding-validation 

We should add a VB version that matches the C# version. The original sample seems to have moved here: https://github.com/Microsoft/WPF-Samples/tree/master/Data%20Binding/BindValidation

**Comment by eriawan** [comment]
@mairaw 

Pardon if this a little bit OOT, but the link on the docs page that points to WPF-Samples is using MS redirect url link (fwlink): http://go.microsoft.com/fwlink/?LinkID=159972

We should use direct docs link.

**Comment by mairaw** [comment]
Sorry for only noticing your comment now @eriawan. You're correct. We have issue #3391 covering this.

**Comment by Youssef1313** [comment]
@mairaw , This was fixed in #14341.

**Comment by mairaw** [comment]
Thanks @Youssef1313. Closing this one then.
