### ISSUE TITLE
how to write compatible applications

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/docs#459]
Hi,
  I'm looking for informations on how to write web applications and libraries that could be easily switched between .net core and .net framework.
  The problem I see that in this first period, until most the 3rd party libraries are compatible with .net core, could be possibile I have to add libraries that are not ready for core, so I can solve or moving all the application to .net framework or move the code to another web app using .net framework and sharing for example the data model already wrote, but at this point I need to be able to compile a lib both for core and .net fx, but I haven't found any documentation about this.

**Comment by cartermp** [comment]
@lucamorelli You can write .NET Core libraries which will run on .NET Framework.  There are two ways to do this: 

* Target the .NET Standard version which matches your targets - this is the preferred approach if you won't be using APIs unavailable in the .NET Standard
* Multitarget and use `#if` directives in your code for platform-specific APIs

[This article should help you out.](http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html)

**Comment by lucamorelli** [comment]
thanks for the link to the article. I changed the project.json of the library this way

  "frameworks": {
    "netstandard1.4": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
If I understand the situation using **netstandard1.4** I ensure the same api level of net461, and now runs both in the .net core app and .net framework 4.6.1
I have just only one problem: even running if I open the startup class of the .net core app in the vs editor I have errors with all the type used in the startup class but declared inside the library, saying that couldn't be found.
I suppose that the problem is that in the json I find


  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
and netcoreapp1.0 is paired to netstandard1.6.
How can I solve this?

**Comment by mairaw** [comment]
PR #2860  might address this since it will cover the new .NET Framework compatibility mode
