### ISSUE TITLE
Move F# samples from CodePlex

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4591]
I noticed that the article [Tutorial: Creating a Type Provider](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/creating-a-type-provider) says:

> For the full code, download the sample from the [F# 3.0 Sample Pack](https://fsharp3sample.codeplex.com) on the Codeplex website.

But CodePlex has been archived, so I think the sample code should be moved somewhere else, possibly to this repo or to [FSharp.TypeProviders.SDK/examples](https://github.com/fsprojects/FSharp.TypeProviders.SDK/tree/master/examples).

Note that the code is still available for download from CodePlex, but in a complicated and confusing way: the "F# 3.0 Type Provider Samples!" link doesn't work. You have to download the archive (FSharp3Sample.zip) and then find the source code archive inside that (sourceCode.zip) and then find the right sample inside that. I don't think that's an acceptable experience.

Related to *Replace/remove codeplex links* (https://github.com/dotnet/docs/issues/2974).

**Comment by mairaw** [comment]
@cartermp I remember we talked about this specific link recently but I can't remember the details. Can you comment here?

**Comment by mairaw** [comment]
Marking as external since this is about moving the sample code to a new place. @cartermp can you take a look at this request?

**Comment by cartermp** [comment]
@dsyme how do you feel about taking some of those samples and moving them to the TPSDK repo? Long-term we want to rewrite these anyways (they show older Type Providers that customers shouldn't be using anymore), but some of them could make it over.

Realistically, I don't think I'd get to this until after I clean up more of our getting started material.

**Comment by dsyme** [comment]
Hes, that sample should be moved to the TPSDK repo.  Keep this bug open so we can track updating the docs when it is done.  I can move it over.

**Comment by mairaw** [comment]
Sounds good. Thanks @dsyme.

**Comment by mairaw** [comment]
@dsyme has this ever been done?

**Comment by dsyme** [comment]
@mairaw Not yet. It's still on my todo list
