### ISSUE TITLE
update or extend docker tutorial for lighter weight docker images

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#462]
PR #425 shows how to create a basic service running in Docker.

We should add new content that also shows how to build a portable app, and a self-contained app using the lighter-weight Docker images (`core` and `core-deps`).

**Comment by kendrahavens** [comment]
Yes, I think it'd be a very good one to add in the scenario based guidance after the more general docs are landed on "Intro to .NET & Docker", ".NET Docker Images", and the "golden path" ASP.NET app in VS guidance.

**Comment by JRAlexander** [comment]
Yes, in fact, I think the current images article can be modified exactly in this way.

**Comment by JRAlexander** [comment]
This is covered in #2683. So we can close this.
