### ISSUE TITLE
Add documentation for -publicsign compiler switch

### ISSUE THREAD

**Issue by ericstj** [dotnet/docs#4625]
# Issue Title

The csc switch `-publicsign` is missing documentation.

# General

This switch is used to apply a public key without actually signing it, like `-delaysign` but unlike `-delaysign`, `-publicsign` sets a bit in the assembly file that tells the runtime that the file is actually signed.  
This switch was added with https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-by-category.md.

## Issues with Existing Topics

We should add the switch here: https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-by-category.md

## Requests for new Topics

1. Tell us where this topic should go in the Table of Contents.

   - Follow the same pattern as is used https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/delaysign-compiler-option.md.

2. Write an abstract

   - Cribbed from https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/delaysign-compiler-option.md

   > Sometimes called "fake sign" or "OSS sign" public signing is including
the public key in an output assembly and setting the "signed" flag, but
not actually signing the assembly with a private key. This is useful for
open source projects where people want to build assemblies which are
compatible with the released "fully signed" assemblies, but don't have
access to the private key used to sign the assemblies. Since almost no
consumers actually need to check if the assembly is fully signed, these
publicly built assemblies are useable in almost every scenario that the
fully signed one would be used in.

3. Fill in an outline

    - Copy `-delaysign` outline

4. Suggest reviewers

    - @agocke @nguerrera @DnlHarvey

**Comment by mairaw** [comment]
@ericstj does this apply to VB as well?

**Comment by chwarr** [comment]
Looks like VB support for public signing was added in commit https://github.com/dotnet/roslyn/commit/4aea4e0ed26dafb23152ad50c1620bb73d749635, and overall public sign work was tracked by the now-closed https://github.com/dotnet/roslyn/issues/6915
