### ISSUE TITLE
Dotnet new: documentation on template parameter defaults

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4626]
From @seancpeters on https://github.com/MicrosoftDocs/Docs/issues/67

When a parameter does not specify a default value, what occurs is not intuitive to authors or users. When this is the case, the "replaces" value is used as the default unless the parameter is marked as required. In most cases during template invocation, this will quietly do what would be expected, but not always. For example, for choice parameters when the default value (explicitly defined or from the "replaces" value) is not a valid choice, an "invalid parameter" error is reported both when attempting to invoke the template and when displaying help for the template.

I would be happy to work with the doc authors on fleshing out the details of this documentation (I'm a dev on dotnet new)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by JRAlexander** [comment]
@mairaw, Is this for 2.1?

**Comment by seancpeters** [comment]
This has been the behavior for quite a while, but the behavior hasn't ever been clearly spelled out. It would definitely be applicable to 2.1, and most older versions. But, the way that the problem was reported in older versions when invoking or displaying may be different in older versions.

**Comment by mairaw** [comment]
@seancpeters we've postponed this too many times. I'd love to get this done during this sprint but I need to understand this behavior better.

**Comment by seancpeters** [comment]
@mairaw - I'll post here with a more detailed explanation of how defaults work, hopefully either tonight or tomorrow. Then we can go through anything that's not clear, and you can re-work it (as necessary) for a user-facing doc.

Note that the original referenced post to https://github.com/MicrosoftDocs/Docs/issues/67 is no longer available, so we may have lost some context on the original discussion. But if this is just to document the behavior of default param values for templates, we should be fine without that thread.
