### ISSUE TITLE
[Feature] Windows Compatibility Pack Updates

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#4628]
# Windows Compatibility Pack Updates
Revise current Windows Compatibility Pack topic with updates in .NET Core 2.1. 

*Still Needed:*
- [x] Prioritization

**Comment by mairaw** [comment]
We already have a topic for this here: https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack

@terrajobst do you foresee any updates to that topic for the 2.1 timeframe? Should we add a few more details about how to use it, like the question from that customer about having to reference it from the consumer project too?

**Comment by mairaw** [comment]
@terrajobst should we also change the topic https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server to mention the Windows Compability pack?

**Comment by terrajobst** [comment]
> do you foresee any updates to that topic for the 2.1 timeframe? 

No major feature additions over what's already in it; the primary change is that the package will be marked as stable.

>  Should we add a few more details about how to use it, like the question from that customer about having to reference it from the consumer project too?

Yes, we probably should. How do you want me to handle this? Can I just give you bullet points and you wave your magic wand and turn it readable text? :-)

> should we also change the topic https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server to mention the Windows Compability pack?

Good call!
