### ISSUE TITLE
The Variable Names in samples is very bad

### ISSUE THREAD

**Issue by lindexi** [dotnet/docs#4633]
https://github.com/dotnet/docs/blob/3835a255541723fb0a2e57b5858ae33ab8dde55d/samples/snippets/csharp/VS_Snippets_Wpf/scrollchangedeventargsLayout/CSharp/Window1.xaml#L30

 I see the Variable Names is so bad in samples.

**Comment by BillWagner** [comment]
Thanks for pointing this out @lindexi 

We know we have a lot of these from legacy samples.

We've tagged this as an up-for-grabs issue, and whenever anyone in the community sees a sample that can be improved, they can file a PR to help us get to that point.

**Comment by lindexi** [comment]
@BillWagner Do you mean we are encouraged to modify it?

**Comment by lindexi** [comment]
@BillWagner Thx.
