### ISSUE TITLE
PathTooLongException information is inaccurate

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4637]
# PathTooLongException information is inaccurate

.NET Framework apps running on Windows 10 or later support long paths. Although this is documented for the [PathTooLongException](https://review.docs.microsoft.com/dotnet/api/system.io.pathtoolongexception) documentation, is it not noted in the documentation for the individual methods that throw the exception. For many or most of these, the documentation notes that the path limit is specified by `MAX_PATH` and that "on Windows-based platforms, paths must be less than 248 characters and file names must be less than 260 characters."

The documentation for each method that throws a PathTooLongException needs to be revisited and revised accordingly.

**Comment by mairaw** [comment]
Note to use includes for the text, if possible.

**Comment by BillWagner** [comment]
Moving to the current sprint since it is a high priority issue.

**Comment by rpetrusha** [comment]
I'll assign this to myself. I've been meaning to do it for a while.
