### ISSUE TITLE
Identify archived interop topics to migrate back to docs.microsoft.com

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4649]
# Identify archived interop topics to migrate back to docs.microsoft.com

Several years ago, as part of an attempt to reduce the number of topics before migrating to a new authoring and publishing platform, interop topics were removed from the documentation set purely on the basis of page views over a limited time frame. These topics are currently [archived on MSDN](https://msdn.microsoft.com/library/ms172270(v=vs.100).aspx) and are no longer being maintained. This was a poor criterion for evaluating the importance of a topic, and it leaves the current documentation set with huge gaps.

The purpose of this issue is to identify topics that should be migrated back into our current documentation set. (Proposed additions to the list are welcome.) Some of these topics that we should consider adding to the doc set include the following:

- [Using COM Types in Managed Code](https://msdn.microsoft.com/library/3y76b69k(v=vs.100).aspx)
- [Qualifying .NET Types for Interoperation](https://msdn.microsoft.com/library/7fcfby2t(v=vs.100).aspx)
- [Directional Attributes](https://msdn.microsoft.com/library/77e6taeh(v=vs.100).aspx)
- [Default Marshaling for Value Types](https://msdn.microsoft.com/library/0t2cwe11(v=vs.100).aspx)
   [Default Marshaling for Boolean Types](https://msdn.microsoft.com/library/t2t3725f(v=vs.100).aspx)    
   [Default Marshaling for Characters](https://msdn.microsoft.com/library/6tyybbf2(v=vs.100).aspx) 
   These can be combined into a single topic.
- [Default Marshaling for Classes](https://msdn.microsoft.com/library/s0968xy8(v=vs.100).aspx)
   [Default Marshaling for Delegates](https://msdn.microsoft.com/library/7esfatk4(v=vs.100).aspx)  
   These can be combined into a single topic.
- [Introducing the class interface](https://docs.microsoft.com/previous-versions/dotnet/netframework-4.0/4fcadw4a(v=vs.100)).
  See dotnet/dotnet-api-docs#2295

**Comment by rpetrusha** [comment]
Closing, since there's been no discussion, which suggests that the additional interop topics do not need to be migrated.

**Comment by NextTurn** [comment]
Many of the contents in the archived articles are not covered in the new .NET Guide. What do you think of this @jkoritzinsky ?
