### ISSUE TITLE
Possibly incorrect or confusing reference in System.ServiceModel.InstanceContextMode doc

### ISSUE THREAD

**Issue by ghogen** [dotnet/docs#4656]
Regarding

https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.instancecontextmode?view=netframework-4.7.1

On http://msdn.microsoft.com/en-us/library/system.servicemodel.instancecontextmode%28v=vs.110%29.aspx, the sentence "If the channel does not create a session this value behaves as if it were PerCall." does not make sense in the "PerCall" row.

(This is originally a customer issue filed via the Connect channel, in the internal database DEVDIV bug # 130168.)

**Comment by mairaw** [comment]
@zhenlan can you help with this bug? Should this say PerSession instead?

**Comment by zhenlan** [comment]
Indeed a bit confusing. @mconnew can you please confirm?

**Comment by mconnew** [comment]
This is what it should read:

Member name | Description
--- | ---
PerCall | A new InstanceContext object is created prior to and recycled subsequent to each call.
PerSession | A new InstanceContext object is created for each session. If the channel does not create a session this value behaves as if it were PerCall.
Single | Only one InstanceContext object is used for all incoming calls and is not recycled subsequent to the calls. If a service object does not exist, one is created.
