### ISSUE TITLE
Update Target frameworks topic 

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4657]
Topic: https://docs.microsoft.com/en-us/dotnet/standard/frameworks

There are a couple of different issues with this topic:
1 - it's missing a couple of TFMs such as new uap values or Xamarin
2 - It has misleading information about which TFMs are actually supported by .NET Core SDK vs. NuGet
3 - The .NET Core SDK doesn't support building projects with TFMs such as 'uap10.0'. The only way to achieve this is through @onovotny's project https://github.com/onovotny/MSBuildSdkExtras. This information should be added as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by weitzhandler** [comment]
What's the preprocessor directive that's defined with the `uap10.0.16299` moniker?

**Comment by weitzhandler** [comment]
Related: https://github.com/dotnet/docs/issues/18097.
