### ISSUE TITLE
Possible error in System.Diagnostics.ProcessWindowStyle docs

### ISSUE THREAD

**Issue by ghogen** [dotnet/docs#4659]
In these topics:
MSDN: https://msdn.microsoft.com/en-us/library/system.diagnostics.processwindowstyle(v=vs.110).aspx 
docs: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processwindowstyle?view=netframework-4.7.1

It says "To use ProcessWindowStyle.Hidden, the ProcessStartInfo.UseShellExecute property must be false." This is wrong. It should say that it must be true. 

more info [here](http://stackoverflow.com/questions/36833301/is-msdn-wrong-when-it-says-processwindowstyle-hidden-requires-useshellexecute-fa?noredirect=1#comment61239582_36833301)

Originally entered by a customer via the Connect channel, and available in the internal database DEVDIV # 215984

**Comment by mairaw** [comment]
Thanks @ghogen. A long time ago, I checked with @weshaggard regarding that bug and then forgot to work on it apparently. 😢 

This is what he had to say:

From a quick look at the [code](https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,2223), it does appear that we only ever use the Hidden enum value when ShellExecute is set to true. I would say you should remove the sentence from the Hidden member documentation.

As for stating that UseShellExecute must be set to true, I think it is worth mentioning on property page as it is more tightly coupled with the UseShellExecute property where the enum could potentially be used by other things beyond ProcessStartInfo, although probably will never be so I would be OK adding a note about it on both the enumeration and the property page.
