### ISSUE TITLE
Missing How-To: Installing .NET Core runtime on Raspbian (Raspberry Pi 3)

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/docs#4663]
@SuperJMN commented on [Wed Mar 14 2018](https://github.com/dotnet/core/issues/1348)

# Issue Title

Cannot find install instructions to install .NET Core runtime on Raspbian (Raspberry Pi 3)

# General

I haven't found in the whole site information about how to install the .NET Core (2.0) runtime in Raspbian. I have successfully followed the instructions off-site, concretely, in this post: https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/

Please, add information specific to Raspbian update it often, since this site should be the number one source for installing .NET Core on the supported platforms.

Thanks.

---

@Petermarcu commented on [Wed Mar 14 2018](https://github.com/dotnet/core/issues/1348#issuecomment-373047822)

Is this what you are looking for? https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by mairaw** [comment]
Thanks @Petermarcu. Is this an officially supported scenario now? I remember that in the past was more of an experimental thing, no?

@JRAlexander can you take a look at this issue? It seems to align with the other prerequisites topics that you now own.

**Comment by Petermarcu** [comment]
We're officially supporting ARM32 in .NET Core 2.1. Having instructions for the Raspberry Pi would be great for getting started with it. People will then likely use it in other places. We may also want to add instructions for using Docker on the Pi as well. @richlander

**Comment by JRAlexander** [comment]
@mairaw - Yes, I'll take a look. Also added to the .NET Core 2.1 backlog.

**Comment by MrJavaWolf** [comment]
Scott Hanselman have made a write up on how to install .Net Core 2.1 in Raspbian
At the end of the article he shows the magical commands to install .Net core 2.1 in Raspbian: 
https://www.hanselman.com/blog/BuildingRunningAndTestingNETCoreAndASPNETCore21InDockerOnARaspberryPiARM32.aspx

**Comment by SuperJMN** [comment]
Still missing instructions for the RPi3?
