### ISSUE TITLE
Document nested object initializers

### ISSUE THREAD

**Issue by svick** [dotnet/docs#4686]
[The *C# Programming Guide* article *Object and Collection Initializers*](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers) does not mention nested object initializers (e.g. ` new Person { Cat = { Name = "Fluffy" } }`) or nested collection initializers (e.g. `new Person { Cats = { new Cat() } }`. This syntax can be confusing, to the point that some people think it's a bug in the compiler (see https://github.com/dotnet/roslyn/issues/25508). Because of that, I think the article should explain it.

cc: @BillWagner

**Comment by BillWagner** [comment]
Thanks for pointing this out @svick 

It's in the backlog, so I can find it easily when there are other updates in that area.

**Comment by jmarkman** [comment]
I did WHAT
