### ISSUE TITLE
wpf browser app

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#4687]
https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/wpf-xaml-browser-applications-overview#comments-container

this information still talks about vs2010.
current version is vs2017. could use some updates...

**Comment by mairaw** [comment]
Thanks for your feedback @wstaelens. We probably have a lot of topics that haven't been reviewed for the latest versions of VS. I'll open a generic issue to cover that as well.

In regards to this particular topic, @SamBent are XBAPs still a supported scenario in newer versions of VS?

**Comment by SamBent** [comment]
XBAPs are supported in newer versions of .Net.

I’m pretty sure they’re supported in VS too, but you should check with the VS team to be sure.   @DoRon Motter<mailto:doronm@microsoft.com> ?
