### ISSUE TITLE
Create the content for ".NET Core Servicing"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#469]
This issue tracks the content for this topic: http://dotnet.github.io/docs/core-concepts/servicing.html

/cc @mairaw @blackdwarf for details on this topic.

**Comment by stevehoag** [comment]
@BillWagner Referenced topic no longer exists - close?

**Comment by BillWagner** [comment]
Yes, closing.

**Comment by mairaw** [comment]
Reopening this one since we still have a wrench topic (https://docs.microsoft.com/en-us/dotnet/articles/core/versions/servicing) linked to this issue that hasn't been written yet. Would have to decide what goes in here though.

**Comment by BillWagner** [comment]
See also #1397

**Comment by mairaw** [comment]
We cut this from the docset.
