### ISSUE TITLE
Default value not documented for XmlWriterSettings.DoNotEscapeUriAttributes

### ISSUE THREAD

**Issue by SwooshyCueb** [dotnet/docs#4696]
Apologies if this has already been fixed in the repo or in a pull request somewhere.

The default value for `XmlWriterSettings.DoNotEscapeUriAttributes` is not present in the documentation:  
https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwritersettings.donotescapeuriattributes?view=netframework-4.7.1

Additionally, it looks like there may be a typo or grammatical error in the property value description, which currently reads as follows:

> `true` if the XmlWriter do not escape URI attributes; otherwise, `false`.

I would imagine one simply needs to change "do" to "does" and add the default value, but I am not super familiar with all of the .NET documentation standards.

**Comment by mairaw** [comment]
Thanks for the feedback @SwooshyCueb. This has not been taken care yet.

Would you like to try to submit a PR for this? You're right that the sentence should say does instead of do.

**Comment by SwooshyCueb** [comment]
Sure thing, I'll submit one tomorrow once I've had a chance to poke at it and see what the default value is.

**Comment by mairaw** [comment]
Cool! These links might help:
https://referencesource.microsoft.com/#System.Xml/System/Xml/Core/XmlWriterSettings.cs,695
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Core/XmlWriterSettings.cs#L748
