### ISSUE TITLE
Search optimizations need to be improved for C# and VB compiler messages

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4698]
The docs pages for compiler errors and warnings are lower than they should be. Often, users include the message with the error code, which lowers the docs search in favor of other discussion sites.

We propose adding the message text to the title and the H1 for each message.

For example, the error message for [CS1513](https://docs.microsoft.com/dotnet/csharp/misc/cs1513) should include "} expected" which is part of the error message generated.

**Comment by mairaw** [comment]
I think we can choose to add that to either title or H1. I don't think we need in both places.

title metadata might be better since that's what users see in search results. I'd also add C# to the title, such as "C# compiler error CS1513 - } expected".

**Comment by johnjohn3883** [comment]
S

**Comment by johnjohn3883** [comment]
https://github.com/dotnet/docs/issues/4698#issuecomment-466734976

**Comment by mairaw** [comment]
Changing to doc enhancement since we need to make the changes to the content itself to improve the docs experience. Otherwise, it's considered an engineering task, which is not the case here.
