### ISSUE TITLE
[Revision] Consolidate LINQ to XML documentation

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4728]
# Consolidate and revise LINQ to XML documentation

There are separate LINQ to XML documentation sets for [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/linq-to-xml) and [Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/linq-to-xml). Most of these topics are language-independent. That is, the topic themselves are identical and present identical examples in the two languages. Where these topics don't document language-specific features or syntax, these topics should be consolidated into a single topic in either of two locations:

- As a separate conceptual topic in the .NET Standard documentation. This would require creating a new folder called docs/standard/linq.

- In the managed reference documentation. For example, the [XElement Class Overview (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/xelement-class-overview) and [XElement Class Overview (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/xelement-class-overview) are best added to the [XElement Class](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement?view=netframework-4.7.1#remarks) managed reference documentation.

Note that, although these language topics are duplicates of one another, they are not necessarily identical; that is, changes are likely to have been made independently in both documentation sets. 

//cc @mairaw

**Comment by Youssef1313** [comment]
@mairaw Is the work for this issue done with the merge of #16969?

**Comment by mairaw** [comment]
Yes, thanks for the reminder @Youssef1313.
