### ISSUE TITLE
What's New in Windows Communication Foundation *after* 4.5

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/docs#4732]
From what can be seen from the [Reference Source](https://github.com/Microsoft/referencesource), WCF has been receiving updates.
Anything worth mentioning on [What's New in Windows Communication Foundation --4.5--](https://docs.microsoft.com/en-us/dotnet/framework/wcf/whats-new)?

**Comment by mairaw** [comment]
Thaks @alfredmyers. Adding @zhenlan. I'm wondering if we remove that topic and actually just redirect it to our general what's new topic that covers all technologies and improvements (https://docs.microsoft.com/en-us/dotnet/framework/whats-new)?

**Comment by alfredmyers** [comment]
@mairaw : 

What would be really nice would be to use includes so the text for what's new in each version could be written only once and included in the [general](https://docs.microsoft.com/en-us/dotnet/framework/whats-new) and [WCF](https://docs.microsoft.com/en-us/dotnet/framework/wcf/whats-new)'s "What's New?" at the same time.

**Comment by zhenlan** [comment]
For many BCL level .NET components, it does not make sense for each of them to have a separate page of "what's new", so the all-inclusive .NET "what's new" page is necessary. WCF as a framework by itself, I see it can be useful for people who are interested in WCF technology, so I agree with @alfredmyers to keep the separate "what's new" page. This does bring in a maintenance problem. Not sure if there are better options other than "we have to remember to update this separate document in every release".

cc: @Lxiamail

**Comment by alfredmyers** [comment]
@zhenlan What about markdown includes?

**Comment by zhenlan** [comment]
It will be cool if we can include a section of a markdown in another markdown. Not sure if this works. @mairaw may know.

**Comment by mairaw** [comment]
Yes @zhenlan, it is supported. We can move the WCF text from the general what’s new into includes if that’s what you want. We do tag topics that we need to review for each release with a special value (updateeachrelease), so remembering to update shouldn’t be an issue. But if you’d like more content than what we do for the what’s new, we'd need help from your team. Makes sense?

**Comment by zhenlan** [comment]
Sounds great! Yes, we will help if we want more content.

What would be the next step to bring current WCF what'new doc update-to-date?
