### ISSUE TITLE
Wrongly duplicated text on What's new (WCF section)

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/docs#4740]
On https://github.com/dotnet/docs/edit/master/docs/framework/whats-new/index.md, lines 561-563...

> When this feature is enabled, a <xref:System.Runtime.Serialization.Json.DataContractJsonSerializer> object  uses the <xref:System.TimeZoneInfo> type instead of the <xref:System.TimeZone> type to deserialize date and time data. <xref:System.TimeZoneInfo> supports multiple adjustment rules, which makes it possible to work with historic time zone data;   <xref:System.TimeZone> does not.
>
> For more information on the <xref:System.TimeZoneInfo> structure and time zone adjustments, see [Time Zone Overview](../../../docs/standard/datetime/time-zone-overview.md).

... seem to have been duplicated from the previous item (lines 535-537) and doesn't correspond to the item being described starting at line 539:

> **Support for preserving a UTC time when serializing and deserializing with the XMLSerializer class**
Ordinarily, when the <xref:System.Xml.Serialization.XmlSerializer> class is used to serialize a UTC <xref:System.DateTime> value, it creates a serialized time string that preserves the date and time but assumes the time is local.  For example, if you instantiate a UTC date and time by calling the following code: 

If there's nothing else that should be in it's place I can go ahead and remove it.

**Comment by mairaw** [comment]
@rpetrusha can you look at this one?
