### ISSUE TITLE
Improve operators TOC for null-conditional operators

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4784]
The [operators overview page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/index) has the following comment:
>Comment not for this page, but for the menu on the left, below "C# Operators" ([] Operator, () Operator, . Operator, etc.) : the 2 operators ?. and ?[ are not shown. I spent 15 minutes to find them in the last chapter "Null-conditional Operators". That would be nice to add 2 pages "?. Operator" and "?[ Operator" (link them to Null-conditional Operators if you want).
>
>I've got another request about the Microsoft Help Viewer, I don't know where to post it. I have installed it and use it from Visual Studio 2017. In the index, every operator is there, except ?. and ?[. Moreover, there is no entry for the ? suffix of nullable types. That would be nice to add a "? suffix of nullable types" entry, which links to the "nullable types [C#]" page.

I think the first point is a good observation and easy to fix by updating TOC. I suggest to add two entries to the TOC: "?. Operator" and "?[ Operator" - at the same level as other operators. And keep "Null-conditional Operators" entry, as folks might not know the name of the operators. If that's fine, where in TOC to include those two operators? Any ordering there? I would put it next to "?: Operator" just because they all start with a question mark.

**Comment by mairaw** [comment]
What about just adding the two operators after the TOC title and even the topic title. Something like
"Null-conditional Operators (?. and ?[)"

That would bring up the operator in the filter. Thoughts @BillWagner? 

We should also add dev_langs to this topic to make the filter appear like this in metadata section:

```
dev_langs: 
  - "csharp"
  - "vb"
```

And for help viewer to work, we need to add the help viewer metadata similar to:

```
helpviewer_keywords: 
  - "null-conditional operators [C#]"
  - "null-conditional operators [Visual Basic]"
  - "?. operator [C#]"
etc.
```

and rebuild the books.

**Comment by pkulikov** [comment]
If we go this way:
>What about just adding the two operators after the TOC title and even the topic title. Something like
"Null-conditional Operators (?. and ?[)"

I suggest name "?. and ?[ null-conditional Operators":
- to be consistent with other TOC entries
- to make question marks 'catchier' for eyes when scanning TOC

**Comment by BillWagner** [comment]
/cc @MadsTorgersen  The draft C# 6.0 specification doesn't call out the `?.` or `?[` operators in the opening table on operators. I was thinking that whatever we do here should conform to the language spec, so I'd like your opinion.

I'd agree with "?. and ?[ null-conditional operators" (Or simply use "?. ?[ Operators" to be consistent with other entries. 

I'd also move it up in the TOC because the TOC (more or less) follows operator precedence. This entry should be just below the "." operator.

**Comment by MadsTorgersen** [comment]
The draft spec lists `x.y` and `a[x]` as primary expressions in its [operator overview table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#operators), which are mirrored by showing `.` and `[]` in your TOC.

Similarly, the spec would probably list `x?.y` and `a?[x]` as unary operators in the same table, and by analogy those should be listed as `?.` and `?[]` (note closing square bracket is included) in your TOC, in the vicinity of the other unary operators.

**Comment by MadsTorgersen** [comment]
Note that this is a small lie, since the null-conditional expressions gobble up any subsequent indexing and dotting, effectively inverting the precedence. But I think that's alright to gloss over in the TOC. :-)
