### ISSUE TITLE
Change VB, C# compiler switch in examples

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4785]
# Change VB, C# compiler switch in examples

The compiler documentation for both C# and Visual Basic uses the hyphen (`-`) to indicate compiler options when illustrating compiler syntax. All command line compiler examples in the MarkDown file in the repo were modified, as far as we know. 

However, compiler switches used in source code files (*.cs or *.vb files) remain to be changed.

See #4138, #4632

**Comment by BillWagner** [comment]
Thanks for contributing @deirdreemoran I'll take a look and review the PR in the next day or so.

**Comment by BillWagner** [comment]
PR #5930 updated all the samples in the dotnet/docs repo.  I'm leaving this issue open until we verify that none of the code in the dotnet/samples repo has similar comments.

@deirdreemoran If you want to check the [samples repo](https://github.com/dotnet/samples) let us know. Thanks for contributing.

**Comment by deirdreemoran** [comment]
I updated the samples repository with the same changes, PR [#131](https://github.com/dotnet/samples/pull/131).  Happy to help and please let me know if anything needs to be redone!

**Comment by BillWagner** [comment]
Thanks @deirdreemoran Either @rpetrusha or I will review this soon.

**Comment by mairaw** [comment]
Appreciate you're doing this @deirdreemoran. It was on my backlog as I saw these changes coming in and would move our topics to use the dotnet/samples version soon.
