### ISSUE TITLE
:warning: Repo freeze - Content split is underway

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4789]
The dotnet/docs repository is a huge repository and contains all the .NET conceptual articles, samples and API reference docs. There are several disadvantages to that including:
- repo size
- build times
- new features built for docs.microsoft.com require conceptual and reference content to be on different repos, including conceptual versioning, API content localization and replacing LiveFyre comments with GitHub issues.

By the end of the split, we'll have three repos:
- dotnet/docs will only have the conceptual content (same structure as today)
- a new repo for samples
- a new repo for .NET API content

We're accepting PRs at the moment but we won't be merging them until the split task is over. PRs that touch samples and API content should wait to be created in the new repos.

The contributions will be split into the three repos and we'll be making a one-time force update into the master and live branches of dotnet/docs to reduce the size of the repo. We'll have instruction on how to update your forks once the split is done and we'll start moving issues to the new repos as appropriate.

Please let us know if you have any questions or concerns in the meantime.

**Comment by pkulikov** [comment]
@mairaw how are [include files](https://github.com/dotnet/docs/tree/master/includes) treated by the split? Some of them are used both by conceptual content in MarkDown files and by API content in xml files.

**Comment by mairaw** [comment]
Initially, they're going to be duplicated. Each repo will have its own set of include files. With #4801 and probably a new backlog item to remove unused tokens after the split, we'll start cleaning up those.

**Comment by mairaw** [comment]
Split is almost finished and you might have noticed that I just did a one-time force push to both master and live branches on this repo.

I'll make a post detailing some of the consequences of the split and some of the options for you to update your fork.

We'll be updating contributing guide, readme files, etc. and cleaning up branches here in this repo as well in the coming days.

The content that was all here before now lives in the following places:
- github.com/dotnet/docs
- github.com/dotnet/samples
- github.com/dotnet/dotnet-api-docs

Thanks for your patience and understanding while we're going through these changes. But we can already see some of the benefits like 5-minute builds for simple PRs.
