### ISSUE TITLE
Update Migration guide to include runtime/retargeting changes for 4.7.2

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4795]
Topics to update:
- https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/
- Version selector: https://github.com/dotnet/docs/blob/master/includes/migration-guide/runtime/versionselector.md

Create new topics for the diff.

/cc @rpetrusha

**Comment by imba-tjd** [comment]
@mairaw versionselector doesn't work in any other language.
![qq 20180412161736](https://user-images.githubusercontent.com/24759802/38664739-0b120cbe-3e6d-11e8-96b4-272c25316b6d.png)

**Comment by mairaw** [comment]
Thank you for letting us know @imba-tjd. I'll create an internal issue to investigate that.

**Comment by mairaw** [comment]
Internal issue created: [1234884](https://mseng.visualstudio.com/CSI/_workitems/edit/1234884)

/cc @nokura
