### ISSUE TITLE
.NET Framework Installation Guide updates

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4796]
Topics to update:
- https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10
- https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-8-1
- https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-8
- https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-7
- https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers
- https://docs.microsoft.com/en-us/dotnet/framework/install/troubleshoot-blocked-installations-and-uninstallations

We should also change the link to download the framework to use the same button I used in the Windows 10 topic as a test. It seems to be working.

And the link to .NET Downloads should be changed from https://www.microsoft.com/net/download?utm_source=ms-docs&utm_medium=referral to https://www.microsoft.com/net/download/all?utm_source=ms-docs&utm_medium=referral, since the previous now is about .NET Core.
I'm going to work @rowanmiller to see if we can add an anchor to that page so we can link directly to the .NET Framework section.

/cc @rpetrusha

**Comment by rowanmiller** [comment]
The latest version of .NET Framework is still listed on the download page (under the "Run apps" toggle) - https://www.microsoft.com/net/download/Windows/run.

BTW we're going to make changes to the download page, as the current design has issues (e.g. the toggle to Run Apps to get .NET Framework is not obvious)

**Comment by mairaw** [comment]
I missed that @rowanmiller! But since we're specifically talking about a list of all versions when using that link, I think changing the link is good. I'll follow up with you offline re. the changes to the download page.

**Comment by rowanmiller** [comment]
Sounds good. You're input would be great to get to feed into fixing the design. Happy to do something to fix the issue for the meantime too.

**Comment by rowanmiller** [comment]
Actually... is this page useful https://www.microsoft.com/net/download/dotnet-framework-runtime. It's for capturing search traffic for end users wanting to download .NET Framework (and we have some in-product popups that send folks there to).
