### ISSUE TITLE
Replace simple tokens with their text

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4801]
# Replace simple tokens with their text

In numerous places in the documentation in the dotnet/docs repo, tokens are used to provide text that may change. At build time, the token's text is inserted into a topic. In many cases, however, tokens are used to insert simple static text that will not change. In these cases, the token offers no advantages, and the presence of the 
token (a file reference included in the documentation) is distracting and makes the topic difficult to read. 

Instances where the tokens are used should be replaced with their token text, and then the tokens should be deleted. Each PR can focus on replacing the text of one token and removing that token; checked items have been addressed in individual PRs. The tokens include:

- [x] tla2sharptla-visualb-md.md (token text: Visual Basic)
- [x] tla2sharptla-visualbnet-md.md (token text: Microsoft Visual Basic .NET)
- [x] tlasharptla-vba-md.md:Microsoft (token text: Visual Basic for Applications (VBA)) 
- [x] tlasharptla-visualb-md.md (token text: Microsoft Visual Basic)
- [x] tlasharptla-visualbnet-md.md (token text: Microsoft Visual Basic .NET))
- [x] tlasharptla-visualbscrpt-md.md (token text: Microsoft Visual Basic Scripting Edition (VBScript))
- [x] vb-current-short-md.md (token text: Visual Basic)
- [x] vbprvb-md.md (token text: Visual Basic) -- in the dotnet/docs repo
- [x] vbprvb-md.md (token text: Visual Basic) -- in the [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs) repo
- [x] csharp-current-short-md.md (token text: Visual C#)
- [x] csprcs-md.md (token text: Visual C#)
- [x] csprcsxpr-md.md (token text: Visual C# Express)
- [x] tla2sharptla-cshrp-md.md (token text: C#)
- [x] tla2sharptla-lhcshrp-md.md (token text: C#)
- [x] tlasharptla-cshrp-md.md (token text: C#)
- [x] tlasharptla-lhcshrp-md.md (token text: C#)
- [x] tlasharptla-vcshrp-md.md (token text: Microsoft Visual C#)
- [x] vs-current-short-md.md (token text: Visual Studio)
- [x] vsprvs-md.md (token text: Visual Studio)
- [x] tla2sharptla-avalonwinfx-md.md (token text:.NET Framework)
- [x] tla2sharptla-winfx-md.md (token text:.NET Framework)
- [x] tlasharptla-avalonwinfx-md.md (token text: Microsoft .NET Framework)
- [x] tlasharptla-netframewk-md.md (token text: Microsoft .NET Framework)
- [x] tlasharptla-titlewinfx-md.md (token text: .NET Framework)
- [x] tlasharptla-winfx-md.md (token text: Microsoft .NET Framework)
- [x] avalon1-md.md (token text: Windows Presentation Foundation (WPF))
- [x] tla2sharptla-mswin-md.md (token text: Windows)
- [x] tla2sharptla-win-md.md (token text: Windows)
- [x] tla2sharptla-winforms-md.md (token text: Windows Forms)
- [x] tla2sharptla-winformssharpinitcap-md.md (token text: Windows Forms)
- [x] tlasharptla-winsharpinitcap-md.md (token text: Microsoft Windows)
- [x] tlasharptla-workflow-md.md (token text: Windows Workflow Foundation)
- [x] tlasharptla-wpf-md.md (token text: Windows Presentation Foundation (WPF))
- [x] vsindigo-md.md (token text: Windows Communication Foundation (WCF))
- [x] wf-md.md (token text: Windows Workflow Foundation (WF))
- [x] wf2-md.md (token text: Windows Workflow Foundation)
- [x] ssnoversion-md.md (token text: SQL Server) 
- [x] crabout-md.md (token text: For more information about)
- [x] crdefault-md.md (token text: For more information, see)
- [x] crexample-md.md (token text: For an example of)
- [x] crlist-md.md (token text: For a list of) - only two uses
- [x] indigo1-md.md (token text: Windows Communication Foundation (WCF)) -- in the docs repo
- [x] indigo1-md.md (token text: Windows Communication Foundation (WCF)) -- in dotnet-api-docs 
- [x] indigo2-md.md (token text: WCF) -- in the dotnet/docs repo
- [x] indigo2-md.md (token text: WCF) -- in the dotnet/dotnet-api-docs repo 
- [x] null-md.md (token text: null) - only two uses

 The following are tokens that should be replaced by their token text and removed from the [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs) repo. (They have already been removed from the dotnet/docs repo.) A checkmark indicates that the item has already been removed.

- [x] ajax-current-ext-md.md (token text: Microsoft Ajax)
- [x] atlaslib-currrent-ext-md.md (token text: Microsoft Ajax Library)
- [x] cppwrt-md.md (token text: Visual C++ component extensions)
- [x] infocard1-md.md (token text: CardSpace)
- [x] net-2015-md.md (token text: .NET Framework 4.6)
- [x] net-client-v35-long-md.md (token text: .NET Framework Client Profile)
- [x] ofprexcel-md.md (token text: Microsoft Excel)
- [x] tla2sharptla-ado-md.md (token text: ADO)
- [x] tla2sharptla-aes-md.md (token text: AES)
- [x] tla2sharptla-ascii-md.md (token text: ASCII)
- [x] tla2sharptla-clrsharpinitcap-md.md (token text: CLR)
- [x] tla2sharptla-dib-md.md (token text: DIB)
- [x] tla2sharptla-guid-md.md (token text: GUID)
- [x] tla2sharptla-id-md.md (token text: ID)
- [x] tla2sharptla-jpegorg-md.md (token text: JPEG)
- [x] tla2sharptla-ms-md.md (token text: Microsoft)
- [x] tla2sharptla-rtf-md.md (token text: RTF)
- [x] tla2sharptla-whistler-md.md (token text: Windows XP)
- [x] tla2sharptla-whistler2-md.md (token text: Windows XP)
- [x] tla2sharptla-xamlsharpinitcap-md.md (token text: XAML)
- [x] tlasharptla-ado-md.md (token text: Microsoft ActiveX Data Objects (ADO))
- [x] tlasharptla-aes-md.md (token text: AES)
- [x] tlasharptla-ansi-md.md (token text: ANSI)
- [x] tlasharptla-bmpsharpinitcap-md.md (token text: Bitmap (BMP))
- [x] tlasharptla-dib-md.md (token text: device-independent bitmap (DIB))
- [x] tlasharptla-guid-md.md (token text: globally unique identifier (GUID))
- [x] tlasharptla-http-md.md (token text: HTTP)
- [x] tlasharptla-notepad-md.md (token text: Microsoft Notepad)
- [x] tlasharptla-oem-md.md (token text: OEM)
- [x] tlasharptla-titlewinfx-md.md (token text: .NET Framework)
- [x] tlasharptla-vba-md.md (token text: Microsoft Visual Basic for Applications (VBA))
- [x] tlasharptla-whistler-md.md (token text: Microsoft Windows XP)
- [x] tlasharptla-whistler2-md.md (token text: Microsoft Windows XP)
- [x] tlasharptla-winsharpinitcap-md.md (token text: Microsoft Windows)
- [x] tlasharptla-vstecmsbuild-md.md (token text: MSBuild)
- [x] tlasharptla-vwprvw-md.md (token text: Visual Web Developer)
- [x] tlasharptla-winxppro-md.md (token text: Windows XP Professional)

**Comment by pkulikov** [comment]
May I suggest more?
- crabout-md.md (token text: For more information about)
- crdefault-md.md (token text: For more information, see)
- crexample-md.md (token text: For an example of)
- crlist-md.md (token text: For a list of) - *only two uses*
- indigo1-md.md (token text: Windows Communication Foundation (WCF))
- indigo2-md.md (token text: WCF)
- null-md.md (token text: null) - *only two uses*

**Comment by rpetrusha** [comment]
Thanks, @pkulikov. Of course you can suggest more. I'd focused on product names (though I'd missed the WCF tokens that you listed).

**Comment by Mackiovello** [comment]
I'd be happy to take care of this one.

**Comment by rpetrusha** [comment]
Thanks, @Mackiovello. Since this is a fairly substantial amount of work, the best way to approach this is to submit a separate PR for each token.

**Comment by mairaw** [comment]
should we just check off when both repos have been updated @rpetrusha? or maybe track each entry for each repo?

**Comment by Mackiovello** [comment]
Created eight pull requests. Will continue once those are approved and merged.

**Comment by Mackiovello** [comment]
> null-md.md (token text: null) - only two uses

I don't find this one in the dotnet/docs repo

**Comment by Mackiovello** [comment]
I don't find these in this repo:
* tlasharptla-vba-md
* tlasharptla-titlewinfx-md
* tlasharptla-wpf-md

When we merge https://github.com/dotnet/docs/pull/5152, I think this repo is done.

**Comment by Mackiovello** [comment]
I can't find these:
* atlaslib-currrent-ext-md.md (token text: Microsoft Ajax Library)
* tla2sharptla-ms-md.md (token text: Microsoft)
* tlasharptla-ado-md.md (token text: Microsoft ActiveX Data Objects (ADO))
* tlasharptla-vstecmsbuild-md.md (token text: MSBuild)
* tlasharptla-vwprvw-md.md (token text: Visual Web Developer)
* tlasharptla-winxppro-md.md (token text: Windows XP Professional)

I've created pull requests for all the other tokens in the dotnet-api-docs repo. With this, I think this issue is done. Please review.

**Comment by Mackiovello** [comment]
@rpetrusha is there anything left for this issue?

**Comment by mairaw** [comment]
Can we close this issue @rpetrusha?

**Comment by rpetrusha** [comment]
Yes, we can, @mairaw.

**Comment by nokura** [comment]
As feedback from Loc team, this practice is caused a large amount of re-translating. $65K for https://github.com/dotnet/dotnet-api-docs. We are looking for a way to replace the tokens with values without sending to translators, but not find it yet.
