### ISSUE TITLE
Edit links are broken

### ISSUE THREAD

**Issue by poizan42** [dotnet/docs#4814]
The edit links on https://docs.microsoft.com/en-us/dotnet/api goes to https://github.com/dotnet/dotnet-api-docs/blob/master/xml/... instead of https://github.com/dotnet/docs/blob/master/xml/... - e.g. https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.write?view=netframework-4.7.1 has an Edit link to https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/NetworkStream.xml which just gives a 404 error.

**Comment by BillWagner** [comment]
Thanks for reporting this @poizan42   The current situation is because of the work for #4789 

I expect this will be fixed when that infrastructure work is done, which should be soon.  I'll check again once that work finishes to ensure it fixes it, and there are no other issues.

**Comment by mairaw** [comment]
This should be working now @poizan42. Thanks for your patience while we are reorganizing the content.
