### ISSUE TITLE
404 error on link to solution

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#4821]
@dreyses11 commented on [Thu Mar 29 2018](https://github.com/dotnet/docs.de-de/issues/74)

In docs.de-de/blob/live/docs/csharp/quick-starts/branches-and-loops-local.md is a link to an solution, but the solution doesn‘t exist (or is wrong linked), so you are recieving an 404 error, when you try to open the link and get to the solution.
![image](https://user-images.githubusercontent.com/33466028/38108179-4b9cd9b4-3394-11e8-85bd-69317cee230d.png)

**Comment by mairaw** [comment]
@dreyses11 Thanks for reporting this issue and apologies for the inconvenience. The current situation is because of the work for #4789.

We'll update the links to the correct samples once that's done. It should be fixed soon. Thanks!

**Comment by BillWagner** [comment]
@mairaw 

Yes, I should have it tonight or tomorrow morning.

**Comment by mairaw** [comment]
Cool. Thanks! I'm hoping we can be open for business by tomorrow.

**Comment by mairaw** [comment]
Reopening until all PRs are merged

**Comment by mairaw** [comment]
All PRs are merged now. Still need to fix the vb zip link and wanna do a pass to make sure we didn't miss any.

**Comment by mairaw** [comment]
I think this one can be closed now. Thanks @BillWagner!
