### ISSUE TITLE
Specifying neutral language in VS

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#4826]
Topic: https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-resource-files-for-desktop-apps#resource-files-in-visual-studio

In the section that describes specifying the neutral language, it is correct for non-.NET Core and .NET Standard projects. But for .NET Core and .NET Standard projects, the language drop-down is on the **Package** tab, not the **Application** tab.

**Comment by mairaw** [comment]
Hi @gewarren, as of right now, those topics are specific to .NET Framework. We'll need to move them out of the Framework path and rework all of those articles to see what's applicable to Core and Standard when it comes to resource files.
