### ISSUE TITLE
C# Quick Start to First App 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/docs#4828]
## Quick Start to First App 

The quick starts have been really popular. @BillWagner and I had a quick chat on  next steps.  What kind of apps can we teach someone to build in the browser?  We came up with a few ideas but ideas but, we would appreciate your input.  Please remember that users are coming from the[ C# quick starts ](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world) and have basic understanding of the following topics:
- Declaring and using variables
- Working with strings 
- Numbers in C#
- Branches and loops 
- Interpolated strings
- List and collections

**Comment by mairaw** [comment]
There was someone asking for a lesson on events in one of the comments @LadyNaggaga. I'll see if I can find where it was.

**Comment by jinek** [comment]
Project is not provided. What browser?)

**Comment by jinek** [comment]
What's about to count all digit symbols in a given string?

**Comment by sabarnett** [comment]
Build a calculator. Expand it to be a scientific calculator. Give it a programmer mode so calculating in hex and binary. Expand it to record the steps in your calculation. Allow it to unwind back through that history, undoing parts of the calculation. Allow it to store calculations. Introduce variables into the calculations that have to be entered when the calculation is replayed. Perhaps end up with something that is a full on programmable calculator.

**Comment by xyfoo** [comment]
An app that group list of grocery to a summary,  calculate the total price, and give discount if total exceed certain amount.

a, b, c, a, d, d, d -> 2 a, 1 b, 1 c,  3 d

**Comment by sonergonul** [comment]
Basic calculator can be nice. Small, easy to learn, easy to solve problems.

But thinking to build a "specific" app, I think it would be better to have interactive windows like [Khan Academy](https://www.khanacademy.org). First you watch the introduction video, then you interact with the same window to solve a specific problem after you learn it.

After that, small exercises would be nice. Such an examples can be found on [ProjectEuler](https://projecteuler.net), [Hackerrank ](https://www.hackerrank.com)etc. For example, reverse a string, seperate a sentences based on bucket size words, count vowels in a string.

![image](https://user-images.githubusercontent.com/1696649/38767681-b1180c44-3fee-11e8-9c51-ff2d040fcdc0.png)
