### ISSUE TITLE
Broken reference links in "Advanced (Windows Presentation Foundation)" guide

### ISSUE THREAD

**Issue by fragmer** [dotnet/docs#4830]
The majority of reference links in the [_Advanced (Windows Presentation Foundation)_ guide](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/) have been broken for some time.

For a specific example, reference links on [_Input (WPF)_ page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/input-wpf#reference) lead to missing URLs such as [`https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement):

![2018-03-30_12-07-40_chrome](https://user-images.githubusercontent.com/587809/38150247-d6de5a7e-3412-11e8-9c42-7e1842273411.png)

**Comment by mairaw** [comment]
We’re investigating this issue right now. It should be related to the work we’re doing for #4789

**Comment by mairaw** [comment]
We found the root cause, which was unrelated to the work being done for #4789, and the problem is now fixed. The issue only started this morning. Thanks for letting us know, @fragmer.
