### ISSUE TITLE
.NET Compiler SDK APIs: Create Namespace nodes

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4837]
@BillWagner commented on [Fri Jul 28 2017](https://github.com/dotnet/roslyn-api-docs/issues/15)

The Mdoc process does not create summary pages for namespaces. These must be created by hand.

The source for the .NET Compiler Platform SDK sources need these added for each namespace that is part of the .NET Compiler Platform SDK meta package.

**Comment by dend** [comment]
Today, `mdoc` will generate the namespace stubs, but will not put any information there because C# does not support handling namespace descriptions. At this time, namespace information can be introduced manually. We would need a compiler change to ensure that namespace comments can be supported.
