### ISSUE TITLE
VB: Modulus operator should be referred to as Remainder

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#4884]
See #4860 

The operator referred to as "modulus" performs a "remainder" operation. There are subtle differences, primarily with negative numbers.

As pointed out in the PR, the `Mod` operator name complicates this.  (Similarly `op_Modulus` in IL complicates the explanation as well.

**Comment by KathleenDollard** [comment]
For reference: [Eric Lippert explains modulus vs remainder](https://blogs.msdn.microsoft.com/ericlippert/2011/12/05/whats-the-difference-remainder-vs-modulus/) 

I believe the word "modulus" in common usage is remainder, and the conversations I found regarding it's use in the sense Eric uses it is all around congruence, and this is an arithmetic operator. 

Overall the VB page does a great job explaining what the operator does, with minimum use of the word modulus. I would leave the text as is, but add the note below. 

NOTE: There is a difference between "remainder" and "modulus" in mathematics, with different results for negative numbers. The MOD operator in Visual Basic, and the underlying op_Modulus IL instruction are remainder operations. The result of `-123 MOD 30` is 3 and `-123 MOD 4` is -30.

**Comment by aaronfranke** [comment]
@KathleenDollard I would use smaller numbers for a more clear example:

> The result of `7 MOD 3` is 1 and `-7 MOD 3` is -1 (as opposed to 2).

For reference, here's the new C# definition, adjusted\* for VB, with `%` replaced with `MOD`:

> The formula `a MOD b` will always return a value on the range `(-b, b)`, exclusive (it can never return `b` or `-b`), keeping the sign of the dividend. For integer division, the remainder operator satisfies the rule `a MOD b = a - (a / b) * b`.

>This is not to be confused with canonical modulus, which satisfies a similar rule but with floored division and returns values on the range `[0, b)`. VB does not have an operator for canonical modulus. However, the behavior is the same for positive dividends.

\* I don't know VB, so there may be syntax errors here...

**Comment by KathleenDollard** [comment]
Rem is a Visual Basic keyword for a comment. It is rarely used as the apostrophe is much more common. Rem follows the script/DOS meaning of the word. 

If there is a place that the functionality and docs still don't match on this, please let us know.
