### ISSUE TITLE
Broken links to string marshaling examples

### ISSUE THREAD

**Issue by Shawn1874** [dotnet/docs#4893]
Within this topic all of the links to examples are broken.  I needed to see an example of marshaling a string by reference.  Unfortunately the documentation is severely broken.  I tried several links, and it always results in a page no longer available error.

https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-strings.md

**Comment by pkulikov** [comment]
@Shawn1874 thank you for submitting the issue.

If you still need to see examples, try the following workaround before the docs are fixed. If you get the page with the message **This topic is no longer available**, there should be the drop-down *Other Versions* under the message. Select another version, let's say for Framework 4.

**Comment by mairaw** [comment]
Thanks @pkulikov. That's what I was going to say @Shawn1874. But I'll fix this page but there are many others like this and we're fixing them over time.
