### ISSUE TITLE
HttpClient remark is not applicable to .NET Core

### ISSUE THREAD

**Issue by karelz** [dotnet/docs#4900]
One [HttpClient Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-2.0#remarks) paragraph is specific to .NET Framework/Mono:

_By default, HttpWebRequest will be used to send requests to the server. This behavior can be modified by specifying a different channel in one of the constructor overloads taking a HttpMessageHandler instance as parameter. If features like authentication or caching are required, WebRequestHandler can be used to configure settings and the instance can be passed to the constructor. The returned handler can be passed to one of the constructor overloads taking a HttpMessageHandler parameter._

**Problems:**
1. `HttpWebRequest` is not default transport on .NET Core.
2. `WebRequestHandler` is available only on .NET Framework (not sure about Mono - docs say only .NET Framework).

**Solution:** Mark the section as specific to .NET Framework / Mono.

@mairaw thoughts/suggestions?

**Comment by mairaw** [comment]
Hi @karelz, sorry for the delay. What we've been doing is to call out in the text to which platform the comment is applicable.
