### ISSUE TITLE
Good, Better, Best Practices for Exceptions

### ISSUE THREAD

**Issue by Narvey** [dotnet/docs#4906]
The [Best Practices for Exceptions](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md) are good, but they could be better.

First, it should be explicitly called out to never use `throw ex;` to rethrow an exception. However, one of the the methods recommended (`throw;`) [can also mess up line numbers](https://weblogs.asp.net/fmarguerie/rethrowing-exceptions-and-preserving-the-full-call-stack-trace). I think it would be good to present the following options for rethrowing:
1. Wrap and throw the new exception (currently the second option presented).
2. For .NET 4.5 and later, use `ExceptionDispatchInfo.Capture(ex).Throw()`.

**Comment by svick** [comment]
Few more notes:

* It might make sense to use exception filters instead of rethrowing the exception.
* In .Net Core 2.0, you can write just `ExceptionDispatchInfo.Throw(ex)`.
