### ISSUE TITLE
Bug in hosting sample with unsigned type and loop

### ISSUE THREAD

**Issue by SamVanheer** [dotnet/docs#4909]
The hosting sample has a bug with the loop that locates the directory that contains the target app: https://github.com/dotnet/samples/blob/master/core/hosting/host.cpp#L63

`i` is a `size_t`, which is an unsigned integral type. The loop checks if `i >= 0`, but this condition can never be false. In the event that a path is passed that does not contain a backslash, it will attempt to read a possibly uninitialized memory location.

In addition, the `wcslen` call used to initialize `i` passes the address of the path array `- 1`, which depending on stack layout could be a garbage value, including `\0`. This could cause issues with the result.

**Comment by mjrousos** [comment]
I can take a look at this.
