### ISSUE TITLE
Learn C#: Parallel programming

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#491]
Issue tracking new topic at https://github.com/dotnet/core-docs/blob/master/docs/csharp/parallel.md

**Comment by BillWagner** [comment]
This has to be done with communication around the Task Parallel Library, and async, and await.

**Comment by GuardRex** [comment]
New loc: https://github.com/dotnet/docs/blob/master/docs/csharp/parallel.md

**Comment by mairaw** [comment]
not applicable anymore. remove the wrench topic: https://github.com/dotnet/docs/blob/master/docs/csharp/parallel.md
