### ISSUE TITLE
Network Programming Samples topic: All links are broken

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4931]
# Network Programming Samples topic: All links are broken

## Links are broken

All of the links to samples in the [Network Programming Samples](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/network-programming-samples) topic are broken.

All links are FWLinks that no longer work. To the extent that I've looked, the targets are archived on MSDN. For example, the first link in the .NET Programming Samples topic is:

`[Download Progress Indicator Technology Sample](http://go.microsoft.com/fwlink/?LinkID=179556)`

A target is available in the [.NET Framework 3.0 documentation](https://msdn.microsoft.com/en-us/library/t8w6294a(v=vs.85).aspx) set. 

## Where are the samples?

It appears, however, that samples were primarily accessible for MSDN as a CD-based product. The [How to: View and Download Samples](https://msdn.microsoft.com/en-us/library/ms180968(v=vs.85).aspx) topic notes that "These options are not available on the Web on MSDN." 

The samples appear to have been released as the [Microsoft .NET Framework SDK version 2.0 Samples Download](https://www.microsoft.com/en-us/download/confirmation.aspx?id=22181) and are available from the Download Center. (A caveat: I've only looked for a couple of the samples in the SDK samples.) 

See PR #4929, which identifies the problem of broken links.

## Addressing the broken links

Fixing the broken links requires more than finding a target that doesn't 404, since the target page isn't going to be very helpful in finding the sample. Addressing the issues with this topic requires the following:
- Determine whether the corresponding sample is available in the .NET Framework SDK version 2.0 Samples Download.
- If it is not, the item should be removed.
- If it is, the link should be changed to an acceptable target.
- The page should be modified to note that all samples are available in the .NET Framework SDK version 2.0 Samples Download, which was released for the .NET Framework 2.0 and may be dated.

// @carolinacmoravia

**Comment by isaac2004** [comment]
@rpetrusha @mairaw is there a thought of adding these samples (if found) into the samples repo?
