### ISSUE TITLE
Document System.Hashcode in .NET Core 2.1 API

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#4936]
https://docs.microsoft.com/en-gb/dotnet/api/system.hashcode?view=netcore-2.1

New API which is currently undocumented.

**Comment by mairaw** [comment]
Thanks for filing this @ChrisMaddock. 

Related notes: https://github.com/dotnet/corefx/issues/14354

@karelz do you know who owns this? And do you think it would be possible to get the dev team to help fill out the "To be added" segments [here](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/HashCode.xml) with some basic comments?

**Comment by karelz** [comment]
@morganbr was championing the change - he should be able to help / recommend others.

**Comment by morganbr** [comment]
I'm willing to help out. What do you need for this?

**Comment by mairaw** [comment]
Awesome @morganbr! The doc source for this is in this other repo:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/HashCode.xml

Basically, where you see a To be added string, we need to replace that with actual content (remarks are optional).

**Comment by ChrisMaddock** [comment]
@jcdickinson - Thank you!! 🎉

**Comment by jcdickinson** [comment]
Pleasure :)
