### ISSUE TITLE
How does EventSource relate to ETW

### ISSUE THREAD

**Issue by jsturtevant** [dotnet/docs#4954]
## Issues with Existing Topics

How does ETW relate to EventSource? I thought event source was a simpler way to create ETW events but it was pointed out [in this thread](https://github.com/Azure/diagnostics-eventflow/issues/199#issuecomment-382087171) the docs on [EventSource](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netframework-4.7) are miss leading and maybe it is not so straight forward? 

If there is a distinction and and they can be used in different ways, could there more detailed description and maybe sample code to help clarify?

**Comment by vancem** [comment]
I agree that EventSource can be improved.   

Logically EventSources talk to EventListeners.    Thus EventSources 'publish' or declare that they are the source for some information.      After an EventListener is created, it can either discover what EventSources already exist (EventSource.GetSources()., and/or get a callback when any new EventSource gets created (EventListener.OnEventSourceCreated).    Then the EventListener can subscribe to any EventSource it desires (EventListener.EnableEvents).  Once enabled EventListeners get callbacks when events happen (EventListener.OnEventWritten).

Logically the framework provides a EventListener listens to ETW commands and forwards them on to the appropriate EventSoruce.  Thus EventSources can be controlled by ETW commands and their events can end up in the ETW stream.    However this is only one place where EventSource events might end up (events go to ALL subscribers, whether they ben EventListeners or the built-in ETW listener.

Thus EventSource 'makes sense' without ETW.   Indeed .NET Core has EventSource on Linux machines that do NOT have ETW (which is a Windows operating system technology).    However Linux DOES have a logging system called LTTng, and on Linux the framework has a built-in EventListener that forwards to LTTng.    Very recently, the .NET Core runtime also supports something called 'EventPipe' that works on both Linux and Windows that again, has a built-in EventListener that forwards on EventSource events. 

Thus the 'right' way to think about EventSource is as one end of an EventSource-EventListener 'pair', and some of those EventListeners bridge to other logging systems (like ETW, LTTng, and EventPipe).

**Comment by jsturtevant** [comment]
Thanks for the clarification.

Is it fair to say that, if I have an `EventSource` and add an `EventListener` this listener only works in-process, but if I use `ETW` to listen to the `EventSource` then I can listen to those events out-of-process?

**Comment by vancem** [comment]
> Is it fair to say that, if I have an EventSource and add an EventListener this listener only works in-process, but if I use ETW to listen to the EventSource then I can listen to those events out-of-process?

In a word, yes.  

ETW is a machine wide logging system, and EventSource has a built-in listener that feeds EventSource events into this machine wide logging.   Typically people collect both the EventSource events and Kernel events (CPU, context switches, paging ...) to make a very detailed picture of what is going on.  

Note that nothing prevents other EventListener bridges to other logging systems.  Indeed on Linux ETW does not exist, but we have a bridge to LTTng (a Linux logging system), and we have built something called EventPipe, which you can think of as a '.NET Specific' version of LTTng/ETW (but EventPipe like EventListeners are only one process (but is INDEPENDENT of OS (thus it works on Linux/Windows equally well).
