### ISSUE TITLE
Bad examples under Remarks for SecurityElement.Escape

### ISSUE THREAD

**Issue by omajid** [dotnet/docs#4959]
The table under "Remarks" for [SecurityElement.Escape](https://docs.microsoft.com/en-us/dotnet/api/system.security.securityelement.escape?view=netcore-2.0#remarks) is showing examples that make no sense.

For example, it shows that escaping replaces `&` with `&`. That sounds entirely incorrectly. The source document of that page says it replaces `&` with `&amp;` which seems much more accurate. That's what should be displayed in the table, literally. Every example has the same issue in that table.

https://github.com/dotnet/dotnet-api-docs/blob/7cdadcaddd80317f3859c7cbf15b0cee6852c042/xml/System.Security/SecurityElement.xml#L571

**Comment by kasper3** [comment]
I think the correction would be to use grave accent character instead of double quote around those.

**Comment by mairaw** [comment]
Thanks @omajid. I see this is a migration issue since MSDN looks fine: https://msdn.microsoft.com/en-us/library/system.security.securityelement.escape(v=vs.110).aspx

Yeah, putting that inside backticks should fix the issue.

**Comment by omajid** [comment]
Thanks for the quick fix!
