### ISSUE TITLE
.NET Core / Standard API docs: Hyperlinks in <see> XML doc tag render incorrectly in VisualStudio IntelliSense tooltips

### ISSUE THREAD

**Issue by stakx** [dotnet/docs#4969]
(I am not sure I am posting in the correct repository&mdash;if not, please direct me to the right place.)

I've noticed an issue with .NET Core & .NET Standard API documentation. Hyperlinks end up being rendered incorrectly in Visual Studio IntelliSense tooltips.

I'll demonstrate this by example of the `<summary>` for the `System.FormatException` class.

### Documentation in the .NET Framework (correctly rendered)

This is what the IntelliSense tooltip for `System.FormatException` will look like when targeting the .NET Framework (4.x):

![netfx](https://user-images.githubusercontent.com/104481/39017073-9bca4ae0-4422-11e8-933a-c4a20b33e23f.png)

This is what the relevant part of the XML documentation file looks like (additional line breaks and indentation added by me):

```xml
<member name="T:System.FormatException">
  <summary>
    The exception that is thrown when the format of an argument is invalid, or when a
    composite format string is not well formed.
  </summary>
</member>
```

### Documentation for .NET Core and .NET Standard 2.x (incorrectly rendered)

And the same when targeting either .NET Core or .NET Standard 2:

![netcore_netstandard](https://user-images.githubusercontent.com/104481/39017147-c0b91f3e-4422-11e8-9264-3cc82bb61505.png)

And again, the relevant part of the XML documentation file (additional line breaks and indentation added by me):

```xml
<member name="T:System.FormatException">
  <summary>
    The exception that is thrown when the format of an argument is invalid, or when a
    <see cref="~/docs/standard/base-types/composite-formatting.md">composite format string</see>
    is not well formed.
  </summary>
</member>
```

VisualStudio IntelliSense does not render `<see cref="link">link text</see>` correctly. It'll display the `cref` instead of the text between the two tags.

However, using `<a href="link">link text</a>` instead *might* work properly.

**Comment by BillWagner** [comment]
@mairaw Should we move this to the [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback) repo?
