### ISSUE TITLE
Full type name in the xref-link is not displayed, though requested

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4974]
[Passing a URI to the Windows Runtime](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/passing-a-uri-to-the-windows-runtime) topic discusses `Windows.Foundation.Uri` and `System.Uri` types. While in the Markdown of the first paragraph both types are xref-ed in the following way:
>...the \<xref:Windows.Foundation.Uri?displayProperty=nameWithType\> class appears as \<xref:System.Uri?displayProperty=nameWithType\> in Intellisense

only `System.Uri` is displayed with a namespace, and `Windows.Foundation.Uri` as just `Uri`:

![image](https://user-images.githubusercontent.com/15279990/39032990-4584efa2-4470-11e8-83f6-7d161c8aa17e.png)

Note that the docs of `Windows.Foundation.Uri` are in the UWP doc repo.

**Comment by pkulikov** [comment]
@mairaw the issue seems to be fixed: at least xref-links are rendered as expected at the linked page. If that's true, this issue might be closed then.

**Comment by mairaw** [comment]
Thanks @pkulikov. I know the UWP team was working on a fix. I believe we also have a similar issue filed on MicrosoftDocs/feedback.
