### ISSUE TITLE
Document shared framework

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#5009]
Update 9-18-19:

* Find the right place in this repo for the shared framework doc.
* Ask `@natemcmaster` to copy paste his blog here. I'll do the conversion.
 
Update - [Deep-dive into .NET Core primitives, part 2: the shared framework](https://natemcmaster.com/blog/2018/08/29/netcore-primitives-2/) looks like it has all the info we need.

The following reference the `Microsoft.NETCore.App` "shared framework", but it's never defined:

* [dotnet command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore2x)
* [.NET Core versioning](https://docs.microsoft.com/en-us/dotnet/core/versions/)
* [.NET Core Daily Builds -- Servicing and future releases](https://github.com/dotnet/core/blob/master/daily-builds.md)
* Closed issue: [ASP.NET Core Shared Framework](https://github.com/aspnet/MetaPackages/issues/248) does a good job of explaining `ASP.NET Core Shared Framework`, Benefits of a shared framework, Version "train" locking, publishing
* Closed issue:Clarify Shared Framework resolution rules when using FDD #2942

[.NET Core distribution packaging](https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging) comes close, but that's the wrong place to explain the shared framework.

The following pages should be updated to use "shared framework" or at least consistent terminology.

* [.NET Core application deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/index)
* [Metapackages](https://docs.microsoft.com/en-us/dotnet/core/packages#metapackages) - Need to mention this is the shared framework.

`dotnet --info` lists .NET Core runtimes installed:
```
Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

[.NET Core application deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/index#framework-dependent-deployments-fdd) (FDD) relies on the presence of a shared system-wide version of .NET Core on the target system. 
Is that the shared framework?

[Packages, metapackages and frameworks](https://docs.microsoft.com/en-us/dotnet/core/packages) states:
Another set is new frameworks that can be thought of as "package-based frameworks", which establish a new model for defining frameworks. These package-based frameworks are entirely formed and defined as packages, forming a strong relationship between packages and frameworks.

How does that fit in? What is a package-based framework?

**Comment by mairaw** [comment]
Thanks @Rick-Anderson. @KathleenDollard can you help with this one? Do you see a good place to put such information?

**Comment by KathleenDollard** [comment]
@terrajobst

**Comment by terrajobst** [comment]
@richlander would know the details better

**Comment by Rick-Anderson** [comment]
I would:

* Add it to [.NET Core application deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/index)
* Update the other docs to be consistent 
* Cross link as appropriate

**Comment by Rick-Anderson** [comment]
I'll bet  @JRAlexander could knock this out in a couple hours.

**Comment by mairaw** [comment]
@Rick-Anderson can you help? 😄

**Comment by KathleenDollard** [comment]
Eeek. It looks like we are using "shared framework" and "framework dependent" pretty much as synonyms. Which is pretty confusing. 

@richlander can you weigh in on this (check the use of the two phrases in dotnet command page link above)

**Comment by Rick-Anderson** [comment]
@KathleenDollard @richlander  can we get this scheduled?
