### ISSUE TITLE
The section on Standard Query Operators should be updated to reflect new operators

### ISSUE THREAD

**Issue by tuespetre** [dotnet/docs#5013]
The section (including its subsections) to which I am referring:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/standard-query-operators-overview

The operators to which I am referring:

- [Append](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.append?view=netcore-2.0)
- [Prepend](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.prepend?view=netcore-2.0)
- [SkipLast](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.skiplast?view=netcore-2.0)
- [TakeLast](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.takelast?view=netcore-2.0)
- [ToHashSet](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset?view=netframework-4.7.2)

**Comment by BillWagner** [comment]
Thanks for pointing this out @tuespetre Yes, that's out of date.

What we should do is update these sections to move to the .NET Standard section. This content (or something very similar) is replicated in numerous places.
Then, we need to update that one (merged) document to refer to the ``System.Linq.Enumerable` API reference for the release-specific set of methods available in LINQ expressions.

That would keep the C# language guide covering those LINQ expressions that are mapped by language keywords.

**Comment by DanRigby** [comment]
Not sure if this needs it's own issue logged, but of the individual operator pages listed above, the following are completely devoid any human generated content and only contain the bare API definition:
* [Append](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.append?view=netcore-2.0)
* [Prepend](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.prepend?view=netcore-2.0)
* [SkipLast](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.skiplast?view=netcore-2.0)
* [TakeLast](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.takelast?view=netcore-2.0)
