### ISSUE TITLE
"Integrated Terminal" reference not found in VSCommunity 2017

### ISSUE THREAD

**Issue by penguino** [dotnet/docs#5070]
Under: 2. "Initialize a C# project:" the reference: "View > Integrated Terminal from the main menu." does not exist in this version of Visual Studio Community (2017, version 15.6.4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - C# Guide](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Service: **unspecified**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @penguino. That topic is about getting started with C# with Visual Studio Code, which is a different tool than Visual Studio. The following topic should work with your version:
https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio

**Comment by diegonzls** [comment]
I was following the tutorial today and in Visual Studio Code version 1.43.2 the label for "Integrated Terminal" only reads "Terminal".

![image](https://user-images.githubusercontent.com/773913/77758441-e15b0f00-702a-11ea-8987-2809f780456b.png)
