### ISSUE TITLE
Runtime changes with assemblies compiled against mixed Framework versions

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/docs#5075]
In the *Runtime changes* section, I read that if:
* the entry assembly is compiled for .NET Framework 4.0
* the installed runtime is .NET Framework 4.5

then the code will run in .NET Framework 4.0 *compatibility mode*.

Please clarify what would happen if the entry assembly loads an assembly compiled for .NET Framework 4.5.
Would it run in compatibility mode too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee6a407-16fe-6537-e587-99908c9a8248
* Version Independent ID: 920fcce6-df42-ff50-dae2-cd7110a8a2f3
* Content: [Application Compatibility in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/application-compatibility#runtime-changes)
* Content Source: [docs/framework/migration-guide/application-compatibility.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/application-compatibility.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@twsouthwick can you help address this question?

**Comment by twsouthwick** [comment]
If the entry assembly is compiled against .NET Framework 4.0,  compatibility mode is set to .NET Framework 4.0 and is applied to all assemblies. Thus, if it loads an assembly compiled against 4.5, then it will also get the 4.0 compatibility mode.

**Comment by paolofulgoni** [comment]
Thanks for the clarification!
Maybe the _"Runtime changes"_ section could be updated too. Something like _"The compatibility mode applies to all loaded assemblies, even those compiled against a different .NET Framework version"_ a the end of the chapter?

**Comment by twsouthwick** [comment]
Can you take a look at the PR I submitted and let me know if that clarifies it? If you still think your sentence would be helpful, can you point to where it would be best?

**Comment by paolofulgoni** [comment]
Now it's clear, thanks! 👍
