### ISSUE TITLE
Document how references get resolved with project.json

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/docs#509]
Using project.json is very different from the previous model of referencing assemblies. I found some useful documentation here (https://docs.nuget.org/consume/projectjson-dependency), but someone new to .NET Core may not think to look there when initially confronted with project.json in the .NET Core setting. This issue is to track some sort of documentation wherever the 'Getting Started' stuff is going.

/cc @blackdwarf

**Comment by mairaw** [comment]
I think this issue fits to what we were discussing the other day about dependency resolution, right @blackdwarf?

**Comment by blackdwarf** [comment]
@mairaw sorry, have no recollection of what we discussed?

**Comment by BillWagner** [comment]
We should determine what happens here with the new project model.

**Comment by mairaw** [comment]
@twsouthwick for sure, this is not a Getting Started topic. With the move to csproj, do you think we still need to cover this? And what aspects you'd like to cover that are not on the NuGet topic?

**Comment by twsouthwick** [comment]
I think we can close this now as the documentation seems to be pretty clear on how this occurs. I originally raised the issue while working with a customer who was having troubles with finding documentation and it seems a lot more discoverable with the latest updates.
