### ISSUE TITLE
Document .NET CLI Tab Completion

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#5094]
.NET CLI tab completion supported has been added to .NET Core 2.0 SDK, but we haven't documented it yet on docs.

Helpful link: https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md

Could be added to https://docs.microsoft.com/en-us/dotnet/core/tools/ or should this be a completely new topic?

/cc @KathleenDollard

**Comment by KathleenDollard** [comment]
This should be separate because it applies primarily to CLI verb/context that are not CLI tools.
