### ISSUE TITLE
Navigation problem .NET core document jump to .NET standard document

### ISSUE THREAD

**Issue by martinadhie** [dotnet/docs#5103]
Hi,

I'm browsing tru left (tree) navigation of .NET core document and suddenly jump to .NET standard document.
Referrer : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server?view=aspnetcore-2.1)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Service: **unspecified**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @martinadhie. @scottaddie @Rick-Anderson should you guys use the contextual TOC so customers don't jump out of your docset for that TOC entry?  

![image](https://user-images.githubusercontent.com/12971179/39487397-f033bea8-4d33-11e8-99f5-ba640bb4a58b.png)

Should we move this issue to the aspnet/docs repo?

**Comment by Rick-Anderson** [comment]
@tdykstra 	own's TOC. Tom?

**Comment by tdykstra** [comment]
Yes, this belongs in our repo for our ToC, I've created one there and you can close this one.  I haven't done contextual ToC links either, it's something I'll have to look into.

**Comment by mairaw** [comment]
Thanks @tdykstra! Closing the issue here then.
