### ISSUE TITLE
Confusing/insufficient documentation around 'await' of an 'async void' function

### ISSUE THREAD

**Issue by markbearden** [dotnet/docs#5109]
Isn't it confusing that this document says (quote, as of May 1 2018): "an async method that returns void can't be awaited."     That sounds like you can't compile "await foo();" for "async void foo() {}".  But not only CAN You do that, but the current Visual Studio casts a warning at you if you don't: "Because this call is not awaited, execution....Consider applying the 'await' operator to the result of the call".   As a related matter, it would be great if you would explain not only WHAT happens when an async void method is awaited (in explicit comparison to what happens if it is called without 'await') and also WHY the dev environment would recommend that you mark such a call with the "await" operator when "it is not awaited".  This is VERY confusing to square up with the current documentation...if you have any doubt, just Google the topic and browse the discussions on StackOverflow, etc.    In summary, an "async void" call "cannot be awaited" and "is not awaited", yet your development tools recommend as best practice marking an async void call as "await", and it compiles and...does exactly WHAT? (when your docs are seeming to say It "can't/won't" work, it is sure hard to know what to expect)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async Return Types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by markbearden** [comment]
This suggestion is based on a complete misunderstanding, so the issue should be closed.

**Comment by mairaw** [comment]
No worries @markbearden. Thanks for letting us know.
