### ISSUE TITLE
link to using DebuggerDisplayAttribute class is wrong

### ISSUE THREAD

**Issue by pcalin** [dotnet/docs#5119]
Link at end of document to  DebuggerDisplayAttribute sends us to old documentation outside the new docs.

Link should be changed to point to https://docs.microsoft.com/en-au/visualstudio/debugger/using-the-debuggerdisplay-attribute for better user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578c4de4-e598-2d81-794b-040b7781e10b
* Version Independent ID: beecaeee-f129-3b90-1439-c4703fdc3dcf
* Content: [DebuggerDisplayAttribute Class (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/DebuggerDisplayAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DebuggerDisplayAttribute.xml)
* Service: **unspecified**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by pkulikov** [comment]
@pcalin thank you for spotting the issue and providing the correct link.
