### ISSUE TITLE
Typo "and"

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#5127]
"true if **and** object was returned successfully; otherwise, false."

"and" should be "an", see also the TryTake method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 101178da-22b2-6550-0c1a-b4bf7001b427
* Version Independent ID: a6eb49f0-51cb-e31b-ba10-dbaa1942f6e4
* Content: [ConcurrentBag<T>.TryPeek(T) Method (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1.trypeek?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentBag`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentBag`1.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @ygoe. I've created a PR to fix this: https://github.com/dotnet/dotnet-api-docs/pull/126 

Also, for small edits like this, you can make the fix directly if you'd like. Each page has an Edit button that takes you right to the content source file. That process is explained here: https://docs.microsoft.com/en-us/contribute/
