### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by GeorgeKouk** [dotnet/docs#5146]
Please correct "disuccess " to "discusses", minor observation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05c2edb7-168e-ea7c-3f5a-3fdc226c68a3
* Version Independent ID: b8b5bd7f-14cd-ecd5-ecc3-a73bfcc28a99
* Content: [How to: Configure a Basic Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-configure-a-basic-wcf-client#feedback)
* Content Source: [docs/framework/wcf/how-to-configure-a-basic-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-configure-a-basic-wcf-client.md)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
Do you want to make the change yourself by creating a Pull Request? (If you do and don't know how, you can follow [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents). If you have any questions, feel free to ask.)

**Comment by GeorgeKouk** [comment]
Oops sorry did't know I could do that. Created a pull request, thanks for letting me know.
