### ISSUE TITLE
Eng

### ISSUE THREAD

**Issue by MohamedElsayedNassar** [dotnet/docs#5155]
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Collections interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/list-collection#step-7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/list-collection.yml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @MohamedElsayedNassar for your feedback!
