### ISSUE TITLE
clumsy coding in MS docs for EqualityComparer<T> Class

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#5158]
Original GH issue: https://github.com/MicrosoftDocs/feedback/issues/256

From @DickBaker

# Idea Title
The coding example is unwieldy and can be improved and simplified

## Issue Details
on page
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1?view=netframework-4.7.1
there is this ugly code
if (b1.Height == b2.Height && b1.Length == b2.Length
&& b1.Width == b2.Width)
{
return true;
}
else
{
return false;
}
whereas IMHO it should simply read
return (b1.Height == b2.Height && b1.Length == b2.Length
&& b1.Width == b2.Width)

however this was an improvement on the previous docs that also wrapped an else clause making that vintage code even worse.

**Comment by DickBaker** [comment]
@mairaw please apply similar polish to BoxSameVolume.Equals !
