### ISSUE TITLE
Note about DateTime.ToUniversalTime is incorrect

### ISSUE THREAD

**Issue by mj1856** [dotnet/docs#5172]
The note box on this page states that `TimeZone.ToUniversalTime` and `DateTime.ToUniversalTime` only use the current adjustment rule.  This is correct for `TimeZone`, but not for `DateTime`.

For `DateTime`, that *used* to be the case, but only on Windows XP systems.  Windows Vista and newer, as well as all .NET Core implementations, behave correctly.   The note should be updated to correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 165831e9-1356-2549-bc9c-4b3f3270e8b5
* Version Independent ID: 86102ae6-80c7-3414-dfe9-9e2f372e1338
* Content: [Converting times between time zones](https://docs.microsoft.com/en-us/dotnet/standard/datetime/converting-between-time-zones)
* Content Source: [docs/standard/datetime/converting-between-time-zones.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/converting-between-time-zones.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @mj1856! Would you like to provide the suggested revision? If so, you can find more information at the [docs contributor guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).

**Comment by daveabrock** [comment]
I can do this one...
