### ISSUE TITLE
The netsh http add sslcert seems to be wrong?

### ISSUE THREAD

**Issue by l3a0** [dotnet/docs#5173]
A lot of folks seem to have problems w/ this command. See: https://stackoverflow.com/questions/779228/the-parameter-is-incorrect-error-using-netsh-http-add-sslcert

This worked for me:

netsh http add sslcert ipport=0.0.0.0:8085 appid="{7BBE87B9-D98F-41D7-B726-FC5E1300ED28}" certhash=4da5af739d6745de4e38fea9574cdaa79032ea14

This failed with message "The parameter is incorrect.":

netsh http add sslcert ipport=0.0.0.0:8085 certhash=4da5af739d6745de4e38fea9574cdaa79032ea14 appid={7BBE87B9-D98F-41D7-B726-FC5E1300ED28}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a66361-c964-5a31-d284-0d752cfb4ec5
* Version Independent ID: 3e04cfca-df3e-199e-e51c-bfdff8c8de05
* Content: [How to: Configure a Port with an SSL Certificate](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate)
* Content Source: [docs/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate.md)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan @glennc can you look at this feedback for a WCF topic?

**Comment by ihateaccountslikethepest** [comment]
This is actually a syntax problem of cmd vs Powershell. Changing the command to 
`netsh http add sslcert ipport=0.0.0.0:8085 certhash=4da5af739d6745de4e38fea9574cdaa79032ea14 appid="{7BBE87B9-D98F-41D7-B726-FC5E1300ED28}"` will work in both terminals.

**Comment by BSCShawn** [comment]
@ihateaccountlikethepest - That command doesn't work ihate. Did you try the command before posting it?
