### ISSUE TITLE
Get exceptions

### ISSUE THREAD

**Issue by fredyadriano90** [dotnet/docs#5174]
I  had that put an extra if to check for AggregateException  type and later another if to check for ArgumentException type
public static void HandleExceptions()
		{
			byte[] bytes = new byte[5000];
			Random random = new Random();
			random.NextBytes(bytes);
			try
			{
				ProcessBytesInParallel(bytes);
			}
			catch (AggregateException ae)
			{
				// This is where you can choose which exceptions to handle.
				foreach (var ex in ae.InnerExceptions)
				{
					if (ex is AggregateException aeIn)
					{
						foreach (var item in aeIn.InnerExceptions)
						{
							if (item is ArgumentException)
								Console.WriteLine(item.Message);
							else
								throw item;
						}
					}
					else if (ex is ArgumentException)
						Console.WriteLine(ex.Message);
					else
						throw ex;
				}
			}

		}

		private static void ProcessBytesInParallel(byte[] data)
		{
			var exceptions = new ConcurrentQueue<Exception>();
			Parallel.ForEach(data, (d) =>
			{
				try
				{
					// Cause a few exceptions, but not too many.
					if (d < 0x3)
						throw new ArgumentException(String.Format("value is {0:x}. Elements must be greater than 0x3.", d));
					else
						Console.Write(d + " ");
				}
				catch (Exception e) { exceptions.Enqueue(e); }
				if (exceptions.Any()) throw new AggregateException(exceptions);
			});
		}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ef7804-93ba-c398-19c4-1df6a3c5b168
* Version Independent ID: 0e699280-a6da-d56f-d713-bfd48d74bd28
* Content: [How to: Handle Exceptions in Parallel Loops](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops)
* Content Source: [docs/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@fredyadriano90 thank you for spotting the issue. 

A better fix might be to use the [Flatten() method](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.flatten?view=netframework-4.7.1#System_AggregateException_Flatten) to bring all inner exceptions at the same level.

In general, the example still should be improved more. Consider this snippet from the code:
```csharp
foreach (var ex in ae.InnerExceptions)
{
    if (ex is ArgumentException)
        Console.WriteLine(ex.Message);
    else
        throw ex;
 }
```

What if the first `ex` in the loop is not the `ArgumentException`? Seems then, that we leave the loop by throwing and skip processing of remaining exceptions.

**Comment by fredyadriano90** [comment]
[pkulikov  ](https://github.com/pkulikov) thank you for the answer, the [Flatten() method](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.flatten?view=netframework-4.7.1#System_AggregateException_Flatten) work perfect to detect all the ArgumentException. I get the main idea.
