### ISSUE TITLE
Propagate completion?

### ISSUE THREAD

**Issue by ishepherd** [dotnet/docs#5177]
```
startWork.Completion.ContinueWith(delegate { completeWork.Complete(); });
```

Shouldn't we prefer to do:
```
startWork.LinkTo(completeWork, new DataflowLinkOptions { PropagateCompletion = true })
```
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2c4aa6-899b-7cf1-c2c1-cb362ee1243a
* Version Independent ID: d6a8cfcf-ccaa-320c-d039-e514e42c2a07
* Content: [How to: Cancel a Dataflow Block](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-cancel-a-dataflow-block)
* Content Source: [docs/standard/parallel-programming/how-to-cancel-a-dataflow-block.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-cancel-a-dataflow-block.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
@ishepherd I agree, so I have created a Pull Request that makes this change: https://github.com/dotnet/samples/pull/48.
