### ISSUE TITLE
Broken link: "INFO: Frequently Asked Questions About ODBC Connection Pooling. "

### ISSUE THREAD

**Issue by szalapski** [dotnet/docs#5178]
Can you fix the URL for "INFO: Frequently Asked Questions About ODBC Connection Pooling."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4636a7-c97a-23fc-bb00-84e4969b1c3d
* Version Independent ID: e31b67c2-7d30-9c35-d82a-0eaaba6c3b28
* Content: [OLE DB, ODBC, and Oracle Connection Pooling](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ole-db-odbc-and-oracle-connection-pooling)
* Content Source: [docs/framework/data/adonet/ole-db-odbc-and-oracle-connection-pooling.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ole-db-odbc-and-oracle-connection-pooling.md)
* Service: **unspecified**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@szalapski Unfortunately it seems that the target Knowledge Base article is no longer available. I have removed the sentence that contains the broken link. (The updated page will not be published immediately.) Thank you for bringing this to our attention.
