### ISSUE TITLE
Outdated note?

### ISSUE THREAD

**Issue by yclkvnc** [dotnet/docs#5179]
Isn't this note outdated? 
"You must close the NetworkStream when you are through sending and receiving data. Closing TcpClient does not release the NetworkStream."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe7d0846-14ff-cce4-2ce5-4df4ba9b5ee5
* Version Independent ID: c1cc7165-fee6-6af3-087b-36a337774399
* Content: [TcpClient.GetStream Method (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.getstream?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Sockets.TcpClient.GetStream);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.0);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/TcpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/TcpClient.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
Could you clarify? What makes you think the note is outdated?

**Comment by yclkvnc** [comment]
It looks like TCPClient.Close method disposes the NetworkStream :
https://referencesource.microsoft.com/#System/net/System/Net/Sockets/TCPClient.cs,d7b14dbe8a2a1aca

Also TcpClient.Close document states that "Calling this method will eventually result in the close of the associated Socket and will also close the associated NetworkStream that is used to send and receive data if one was created."
