### ISSUE TITLE
Is Delegate.EndInvoke really necessary?

### ISSUE THREAD

**Issue by zubetto** [dotnet/docs#5181]
In the chapter "_Handling a Blocking Operation with a Background Thread_" the method `FetchWeatherFromServer` is invoked in separate thread by means of `Delegate.BeginInvoke` method, but there is no `Delegate.EndInvoke` method in the presented code example. Is `Delegate.EndInvoke` really necessary (as stated in "_Calling Synchronous Methods Asynchronously_" https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/calling-synchronous-methods-asynchronously)? Are there any benefits of using `Delegate.BeginInvoke` rather than `ThreadPool.QueueUserWorkItem` in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eef73b1-737e-e895-f5b4-c8fece7a71b7
* Version Independent ID: 106aedc1-3c47-2256-7fec-8adaf861d3bc
* Content: [Threading Model](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/threading-model)
* Content Source: [docs/framework/wpf/advanced/threading-model.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/threading-model.md)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
We should probably add a doc that compares the different asynchronous programming models that .NET has adopted over the years.

**Comment by BenGood** [comment]
I'm sure a doc comparing different asynchronous models would be enlightening but is there a simple answer to the question "Is Delegate.EndInvoke really necessary?" the linked documents says it should always be called. Is the example on this page complete?
