### ISSUE TITLE
add reference to quick reference chart

### ISSUE THREAD

**Issue by jeubank12** [dotnet/docs#5184]
You need a link to this: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/classification-of-standard-query-operators-by-manner-of-execution
This page is nigh unreadable if you are just trying to find out if your linq method of choice is deferred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb13ca67-5f0f-194e-48a4-b89044b68eb0
* Version Independent ID: 8deba539-9e9e-38f0-517c-352e9dde0456
* Content: [Query Execution](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/query-execution)
* Content Source: [docs/framework/data/adonet/ef/language-reference/query-execution.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/language-reference/query-execution.md)
* Service: **unspecified**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@jeubank12 Thank you for the suggestion. I am adding the suggested link to the page.
