### ISSUE TITLE
Not very find-able

### ISSUE THREAD

**Issue by jeubank12** [dotnet/docs#5185]
I would hope this would show up in searches like 'linq deferred execution' or 'EF deferred execution' but it took a horrible sentence search instead of a keyword search to get this to show up in my results: 'list of linq methods and if they are deferred'  This is a great reference and should be linked to from https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/query-execution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea4cef3-02f2-b773-cc0b-91b6a4460c4f
* Version Independent ID: 907608d8-897b-7207-b28d-c7b863c7f48b
* Content: [Classification of Standard Query Operators by Manner of Execution (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/classification-of-standard-query-operators-by-manner-of-execution)
* Content Source: [docs/csharp/programming-guide/concepts/linq/classification-of-standard-query-operators-by-manner-of-execution.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/classification-of-standard-query-operators-by-manner-of-execution.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
Related: #5184 was fixed by #5186
