### ISSUE TITLE
documentation is really good

### ISSUE THREAD

**Issue by saineshwar** [dotnet/docs#5196]
documentation is really good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Classes (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you @saineshwar. We appreciate your comments!
