### ISSUE TITLE
Why */& 255/256?

### ISSUE THREAD

**Issue by he-dev** [dotnet/docs#5197]
Could you explain what these calculations are for?

```cs
     len = ioStream.ReadByte() * 256;
     ...
     ioStream.WriteByte((byte)(len / 256));
     ioStream.WriteByte((byte)(len & 255));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86675e7-4bfb-707d-fe36-c02da2023342
* Version Independent ID: ee821843-1cad-0455-f278-1194b88dd0b0
* Content: [How to: Use Named Pipes for Network Interprocess Communication](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-named-pipes-for-network-interprocess-communication)
* Content Source: [docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-use-named-pipes-for-network-interprocess-communication.md)
* Service: **unspecified**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
They are used to decode and encode a 16-bit integer into two bytes.

**Comment by BillWagner** [comment]
Thanks for answering the question @svick.

I'm going to close this @he-dev as resolved. If you have other concerns, you can reopen this issues.
