### ISSUE TITLE
Plans for CI for samples?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#5198]
I think that one of the significant advantages of having samples as proper .Net Core SDK projects is that CI can ensure that a PR doesn't break them. But, as far as I can tell, there is currently no CI set up for [the dotnet/samples repo](https://github.com/dotnet/samples).

Do you have plans to improve that?

(If this issue is better suited MicrosoftDocs/feedback, I can move it there.)

**Comment by svick** [comment]
The samples README has some mentions of the CI system:

> We will have a CI system in place to build these projects shortly.

> We are working toward having a CI system in place for all code.

Though I believe that "shortly" has been there for a long time (since before the dotnet/samples migration).

**Comment by pkulikov** [comment]
@svick that looks that it's WIP: dotnet/samples#36

**Comment by svick** [comment]
@pkulikov Nice!

**Comment by ChrisMaddock** [comment]
I've thought before that using the dotnet CLI it would be pretty easy to add csproj's to everywhere they would work straight off. That would then help tracking down broken/'against-convention' samples.

Would be a fun little script. 😄

**Comment by ChrisMaddock** [comment]
Aand, further down the line, it could help with automatically turning on runnable samples!

**Comment by mairaw** [comment]
Yes, @dend is looking into enabling the samples CI again. But we're all a bit overwhelmed with //Build starting this week. So, I'll restart the conversation again with him after the conference. The CI was only testing the samples folder before. We need to make sure we can test all projects as well.

**Comment by mairaw** [comment]
I'm going to close this issue @svick. The engineering team is working on that and it's not something we (the writing team) can control. If you wanna track this work, an issue at MicrosoftDocs/feedback would be more appropriate.
