### ISSUE TITLE
Remove mentions of old Windows versions (XP, 95, 98, 2000, NT, Millenium, etc.)

### ISSUE THREAD

**Issue by Mackiovello** [dotnet/docs#5199]
In https://github.com/dotnet/docs/issues/4801, @rpetrusha requested a review of if mentions of Windows XP are still applicable. I don't think that's within the scope of that issue, so I'm opening this instead.

If the mentions of Windows XP are applicable, they should stay, otherwise the text should be revised to use a more modern example.

**Comment by mairaw** [comment]
I agree that replacing the tokens and reviewing the text are two separate tasks. Thanks for filing this issue for us to track. There are probably other old versions mentioned in there like Windows NT or 2000 even.

**Comment by mairaw** [comment]
Changed the title of this issue to be broader than just XP.

**Comment by gewarren** [comment]
I think this issue is still applicable. Reopening.
