### ISSUE TITLE
Another instance of the specialized Stack<T> class is created?

### ISSUE THREAD

**Issue by narekb** [dotnet/docs#5202]
In the second to last paragraph: "As with the previous use of the Stack<T> class created by using the Order type, another instance of the specialized Stack<T> class is created". Because Customer is a reference-type, another specialized instance should *not* be created, and the previous one should be reused. 

Perhaps the word "not" was skipped within the phrase "another instance of the specialized Stack<T> class is created".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec8516f-17fd-47a3-9322-dfb43d0b3c6e
* Version Independent ID: ae0a7bcc-34d3-66e9-123c-c5461ddfec05
* Content: [Generics in the Run Time (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generics-in-the-run-time)
* Content Source: [docs/csharp/programming-guide/generics/generics-in-the-run-time.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/generics-in-the-run-time.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
The explanation is confusing, but I think it's correct. The instance it's talking about is the object returned by `new Stack<Customer>()`, not another specialized version of `Stack<T>`.

Though I question whether the whole article is necessary. Sharing "specialized versions" of a type for reference types is an important optimization, but it's still an implementation detail. I think it might deserve few paragraphs in some article, but not a whole article on its own.

**Comment by FMNSSun** [comment]
I think it's fairly clear. For value types "specialization" happens for every `T` that is a value type but there's only one "specialization" for all `T` that are reference types. In essence it creates a new type for each usage with a `T` of value type and a new type to be used by each usage with a `T` of reference type. There's no need for extra specialization for reference types because the in-memory representation of all references is the same regardless of the exact type. For value types this is different because they have different in-memory representation and thus it creates a specialized version for each.

**Comment by flcl42** [comment]
As for "Unlike with value types, another specialized version of the Stack<T> class is not created for the Order type." does it mean that if the generic class contains a public static field, this field will be shared across all generics made with reference type as generic argument, but will be different for classes with value type passed as generic parameter?

**Comment by svick** [comment]
@flcl42 No, it does not mean that. In such cases, there is separate storage for each generic argument. Most other parts of a type are shared, just not static fields.

You can see that for example by observing the output of [this code](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ7EAI5IOzoDe6WpOSAbDgCxYCyAhgJZQAUAlCWcWmX+QE5WAYQA8uAAwA+AHQAVAJ4AHAKYA5BgFsV7ANxd+gkaID2AIwBWKgMbBZi1Ru16DWAL7oPGNNjFypRK5wAMzkVJJYDupaKlgAvFjAyiomAGascuwyTir6aG5AA=).
