### ISSUE TITLE
Legacy code while .NET Core 2.0 is selected as the target framework

### ISSUE THREAD

**Issue by kiapanahi** [dotnet/docs#5203]
The code representing the class implemented interfaces still includes `IDisposable`; although according to `system.servicemodel.primitives 4.4.2` package this class only implements `ICommunicationObject`.
Is this a problem with the documentation or the implementation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a389d1b-6fb9-3172-179a-0809f747b51f
* Version Independent ID: b4d7a3af-476a-2f59-d0c6-2ac2a3e31cc2
* Content: [ClientBase<TChannel> Class (System.ServiceModel)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.clientbase-1?view=netcore-2.0#feedback)
* Content Source: [xml/System.ServiceModel/ClientBase`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel/ClientBase`1.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this issue @kiapanahi.
 
It seems to be the same issue as the one we're tracking at https://github.com/MicrosoftDocs/feedback/issues/222 where the wrong interfaces are being displayed.

So I'm closing this one.
