### ISSUE TITLE
Clarification?

### ISSUE THREAD

**Issue by Xenoprimate** [dotnet/docs#5206]
The following line has been in this documentation for a long time:

"This ensures that the most up-to-date value is present in the field at all times. "

But I believe this is misleading at best, and possibly just wrong; depending on exactly what `volatile` actually does:

* If all `volatile` does is annotate reads/writes with lfences and sfences, then there is no technical guarantee on 'freshness' (even if an sfence *happens* to imply a store-buffer-flush on x86); only reordering guarantees.

* If however `volatile` does actually imply the CLR/JIT will go further to try and propagate changes to all observers as fast as possible, and ensure that all reads are *always* going back to the cache-coherency subsystem, then I believe the line is *still* misleading as it gives a false sense of security: In truly concurrent scenarios the idea of 'the most up-to-date value' is mercurial at best, and as others have noted, the guarantee [definitely doesn't hold true](https://stackoverflow.com/questions/10631629/volatile-violates-its-main-job) in constructed scenarios.

Could we get some clarification (or even one day maybe an official C# memory model, like the JMM?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d226514d-c7cb-0d1b-b9dc-fb791399dc47
* Version Independent ID: aa5d1078-7f89-98ce-7fdc-107c9ed3eebc
* Content: [volatile (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)
* Content Source: [docs/csharp/language-reference/keywords/volatile.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/volatile.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This line is not in the C# specification, and should be removed:

> "This ensures that the most up-to-date value is present in the field at all times. "

It would be better to use this text from the [spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#volatile-fields)

> These restrictions ensure that all threads will observe volatile writes performed by any other thread in the order in which they were performed. A conforming implementation is not required to provide a single total ordering of volatile writes as seen from all threads of execution.
