### ISSUE TITLE
Sample is incomplete

### ISSUE THREAD

**Issue by InteXX** [dotnet/docs#5207]
Include a VB.NET sample, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745e854-3edd-3ae2-148c-2b93d287853d
* Version Independent ID: f5f63468-abd5-f8ad-8a06-07c0c6d986bc
* Content: [Duplex Services](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/duplex-services)
* Content Source: [docs/framework/wcf/feature-details/duplex-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/duplex-services.md)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@InteXX, VB code is present for all but a 3-line code block in the document. Did you notice the language selector on the right side of the page: 
![image](https://user-images.githubusercontent.com/10886961/39772914-52f9ca7e-52ab-11e8-92c7-a274e35669aa.png).

That said, we'll add the missing VB code that corresponds to the three-line C# code block.

**Comment by InteXX** [comment]
@rpetrusha 

Pardon me, you're correct.

I missed the new dropdown; I was looking for the old tabbed interface.
