### ISSUE TITLE
Incorrect signatures for span indexers

### ISSUE THREAD

**Issue by svick** [dotnet/docs#5208]
The signatures for indexers of `Span<T>` and `ReadOnlySpan<T>` don't show correctly in API reference.

[For `Span<T>`, it shows as:](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.item?view=netcore-2.0)

```c#
public T this[int index] { get; }
```

When it should be:

```c#
public ref T this[int index] { get; }
```

[For `ReadOnlySpan<T>`, it shows as:](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.item?view=netcore-2.0)

```c#
public T& this[int index] { get; }
```

When it should be:

```c#
public ref readonly T this[int index] { get; }
```

This seems to be caused by incorrect behavior of mdoc, so I have created and issue about this there: https://github.com/mono/api-doc-tools/issues/249. But I thought it might make sense to also track fixing the output here (if and when mdoc is fixed), which is why I created this issue.

**Comment by pkulikov** [comment]
The same remark is valid for the [`Span<T>.Enumerator.Current`](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.enumerator.current?view=netcore-2.1) property that [should be](https://github.com/dotnet/coreclr/blob/a8c1c328068518444775e7bb9211f07523c2f21b/src/mscorlib/shared/System/Span.cs#L135):
```csharp
public ref T Current { get; }
```

**Comment by mairaw** [comment]
Thanks for filing this tracking issue @svick and the corresponding issue for mdoc. The other interesting thing is that Property value is empty, when it usually shows the property type. @TianqiZhang can you take a look?

**Comment by BillWagner** [comment]
In a related issue, it seems that types declared as `ref struct` (like `Span<T>` are shown as `struct`.  That's an important distinction.

**Comment by BillWagner** [comment]
Moved to MicrosoftDocs/Feedback#5208
