### ISSUE TITLE
Span<T>.GetEnumerator: not correct display of the return value

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5209]
The ['Span<T>.GetEnumerator'](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.getenumerator?view=netcore-2.1) page has not correct **Returns** section:
![image](https://user-images.githubusercontent.com/15279990/39674542-c98a6676-514d-11e8-8220-6ee2bf5a9f88.png)

The corresponding xml block:
```xml
<ReturnValue>
   <ReturnType>System.Span&lt;T&gt;+Enumerator</ReturnType>
</ReturnValue>
```
Should it be dot instead of a plus?

**Comment by svick** [comment]
[Reflection](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoOAmFVAdhwG8clLCA2FAFkIA4AKASiQF4A+QgTmeABPAA4BTAPYAzZgGVhAQygAeLgDoAolAgBbUWHnBxYVqyzYAvkA===) and IL use `+` for nested classes. Though I have no idea what rules should `<ReturnValue>` follow (it already doesn't follow IL by not using ``Span`1``).

**Comment by mairaw** [comment]
@TianqiZhang @joelmartinez @dend @adkinn can you look at this issue? Not sure in which part of the process we're losing the nested class.

**Comment by mairaw** [comment]
Filed internal bug to track this work: #1253978

**Comment by mairaw** [comment]
This has been fixed but I have further questions for our engineering team on whether we can have the system interpret that API as a single link like the one displayed on the row after the return type:
![image](https://user-images.githubusercontent.com/12971179/39911956-f481018e-54b1-11e8-83ae-db4582ffe329.png)

**Comment by svick** [comment]
@mairaw 

> I have further questions for our engineering team on whether we can have the system interpret that API as a single link like the one displayed on the row after the return type

Is that actually desirable? Consider the case where have a type like `Foo<Bar>.Baz`. Wouldn't you want to have `Bar` as a separate link there?

The only such member I could find in dotnet-api-docs is [`RouteValueDictionary.GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.web.routing.routevaluedictionary.getenumerator?view=netframework-4.7.2):

![](https://user-images.githubusercontent.com/287848/39919103-e108bf5a-5512-11e8-895a-1d6c7c51e839.png)

**Comment by mairaw** [comment]
Interesting. That member is no longer showing the return value @svick. This seems like a bug. Do you want to submit a feedback issue via https://github.com/MicrosoftDocs/feedback?

I'd like to close this issue since the original bug has been fixed now. If you feel like the behavior should change, let's discuss it via a new issue on the feeedback repo.

**Comment by svick** [comment]
@mairaw Done: https://github.com/MicrosoftDocs/feedback/issues/529.
