### ISSUE TITLE
Binding Section 

### ISSUE THREAD

**Issue by mrady9280** [dotnet/docs#5216]
How can I configure the binding ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Service: **unspecified**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by Tarig0** [comment]
Do you mean the url or like the http, tcp, https binding types

**Comment by BillWagner** [comment]
@mrady9280 Does the above comment answer your question? (Can you upvote it if so).

**Comment by BillWagner** [comment]
@mrady9280 I'm going to close this as answered and resolved. If you're still having this problem, re-open the issue and let us know the latest details.

**Comment by flacidsnake** [comment]
Are all the binding possibilities available?
I'm getting System.PlatformNotSupportedException: 'TransportSecurityBindingElement.BuildChannelFactoryCore is not supported.' when trying to use SecurityBindingElement.CreateUserNameOverTransportBindingElement()
https://github.com/dotnet/wcf/issues/1257
