### ISSUE TITLE
Does DotNetStandard 2.0 support 4.6.1 or something later?

### ISSUE THREAD

**Issue by OzBob** [dotnet/docs#5217]
DotNetStandard doco in March 2017 ~~CROSSEDOUT~~ .NET Standard table from 1.5 supporting 4.6.2 to 4.6.1
https://github.com/dotnet/standard/commit/4788c7d4d348d96a942ddd3a50b7aeef33136e2e#diff-a0efca2faa45606b03f5b824d6213122

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Service: **unspecified**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Yes @OzBob, that's what the 1.x vs 2.0 SDK tries to show. But it has been in my to-do list to remove the 1.x line and just leave the latest information there, so I'll update this doc.
