### ISSUE TITLE
Non-threadsafe code in the example

### ISSUE THREAD

**Issue by zerkms** [dotnet/docs#5227]
https://msdn.microsoft.com/en-us/library/bb337971%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

In the `Interlocked.Exchange<T> Method (T, T)` article, which is intended to be a tool for lock-free programming the sample is non-threadsafe.

Access to `firstWidget` is not synchronised, so the application is not guaranteed to work the way it need to be.

I think a non-thread safe program is not the best way to demonstrate lock-free methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af6180bb-9ba2-71b6-ec3c-e52b3247f6bf
* Version Independent ID: 63d81ab1-09b0-b8e6-adaa-eaf6b300f4ef
* Content: [Interlocked.Exchange Method (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.exchange?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Threading/Interlocked.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Interlocked.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by zerkms** [comment]
I think it would be better to make up a complete new example.

**Comment by mikedn** [comment]
One example would be a single object pool
```C#
struct SingleObjectPool<T>
{
    private T _obj;
    public T TryAcquire() => Interlocked.Exchange(ref _obj, null);
    public void Release(T obj) => Interlocked.CompareExchange(ref _obj, obj, null);
}
```
or any variation around the idea of acquiring a unique resource. Examples that attempt to swap 2 resources are probably harder to come by and more likely to be erroneous like the MSDN example shows.
