### ISSUE TITLE
your work is done here

### ISSUE THREAD

**Issue by saulwiggin** [dotnet/docs#5230]
brilliant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36032d47-681c-e39e-331a-14f178d7e583
* Version Independent ID: 46c574db-a657-f2a9-9d0f-dfb9a83a124f
* Content: [Creating and Throwing Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions)
* Content Source: [docs/csharp/programming-guide/exceptions/creating-and-throwing-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/creating-and-throwing-exceptions.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the feedback @saulwiggin We appreciate it. 

Closing this issue.
