### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by RoswellMiller** [dotnet/docs#5231]
what's the verbose syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379f00ab-ebc1-50eb-6779-3a22ec41a80d
* Version Independent ID: 6f88dfb3-c9f9-3715-5121-83a1f22223b8
* Content: [Modules (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/modules)
* Content Source: [docs/fsharp/language-reference/modules.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/modules.md)
* Service: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by BillWagner** [comment]
The verbose syntax is [on a different page](https://docs.microsoft.com/dotnet/fsharp/language-reference/verbose-syntax).

**Comment by cartermp** [comment]
Verbose Syntax isn't mentioned in this article. Given that we want to steer people away from the syntax (aside from OCAML interop), I don't think we should add a link.
