### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by RoswellMiller** [dotnet/docs#5232]
What's the verbose syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121d0d1b-bb16-7b85-2529-297856a6e8ca
* Version Independent ID: 1795dd9d-a94b-3f47-a6d6-686fa9234a8c
* Content: [Namespaces (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/namespaces)
* Content Source: [docs/fsharp/language-reference/namespaces.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/namespaces.md)
* Service: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@RoswellMiller verbose syntax isn't mentioned in this article. [Verbose syntax](https://docs.microsoft.com/dotnet/fsharp/language-reference/verbose-syntax) is documented today. I'll close this out unless there is a specific issue in this article.
