### ISSUE TITLE
Broken links on PropertyInfo.GetValue Method

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#5236]
Some links on this page are in markdown - which is not rendering correctly. I assume they should be `<see>` links instead.

Reporting this instead of fixing as I'm not set up to do that right now - sorry!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd911afa-c74f-48a8-2b02-365ffe4c8fc7
* Version Independent ID: e67c98df-4339-0ec5-3700-2def4d21d496
* Content: [PropertyInfo.GetValue Method (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.getvalue?view=netframework-4.7.2#System_Reflection_PropertyInfo_GetValue_System_Object_)
* Content Source: [xml/System.Reflection/PropertyInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/PropertyInfo.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @ChrisMaddock, for pointing out the broken links. There's no need to apologize for not fixing them yourself. I'll open a PR to do it shortly.
