### ISSUE TITLE
Next steps button

### ISSUE THREAD

**Issue by TheBeachMaster** [dotnet/docs#5237]
At the end of this doc: there is (was) a button (aptly?) labelled *Next steps button*. Kindly rectify this.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis classification scenario](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Service: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@TheBeachMaster thank you for reporting the issue!

**Comment by TheBeachMaster** [comment]
@pkulikov  Awesome, close on merge #5238
