### ISSUE TITLE
Two Mistakes in the Documentation

### ISSUE THREAD

**Issue by mikebelluk** [dotnet/docs#5248]
Hi,

I spotted a couple of issues with the documentation..

1. You need to return the model in the Train method, e.g.

PredictionModel<TaxiTrip, TaxiTripFarePrediction> model = pipeline.Train<TaxiTrip, TaxiTripFarePrediction>();
await model.WriteAsync(ModelPath);

return model;

2. When running the example, I get the error "Source column 'fare_amount' not found". This can be fixed by changing TaxiTrip.cs from:

[Column(ordinal: "6", "Label")]
public float fare_amount;

..to..

[Column(ordinal: "6", name: "fare_amount")]
public float fare_amount;

I suspect though, that this should have been handled by the ColumnCopier line:
pipeline.Add(new ColumnCopier(("fare_amount", "Label")));

Mike

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to Predict New York Taxi Fares (Regression).](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by BillWagner** [comment]
Thanks for spotting this @mikebelluk 

This is fixed in #5245  You can see the code changes in dotnet/samples#57 Those changes should be published today or tomorrow.

I'm going to close this. But, if you don't think that fixes the problem, reopen this.
