### ISSUE TITLE
ServiceAuthorizationManager docs didn't get pulled through cleanly

### ISSUE THREAD

**Issue by biltongza** [dotnet/docs#5249]
https://github.com/dotnet/docs/blob/master/docs/framework/wcf/extending/how-to-create-a-custom-authorization-manager-for-a-service.md

Looks like there's a bunch of human-unfriendly stuff that I assume is parsed by something to make other pretty docs. Would be appreciated if this became more human readable :)

**Comment by BillWagner** [comment]
@biltongza That source becomes [this document](https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/how-to-create-a-custom-authorization-manager-for-a-service) through the docs build system.  

I'm going to close this, but if you have readability concerns on the published document, re-open and let us know what you're seeing.
