### ISSUE TITLE
Need a list of Available SDK Versions

### ISSUE THREAD

**Issue by laultman** [dotnet/docs#5250]
While the content is correct it is pretty much useless since it is so old. What is needed is a maintained list of SDK versions so that we can select the correct one. If it is not found on our machine it is ignored without any notice to the developer. If we get it wrong by even one character it is ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json reference](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Service: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @laultman for your feedback. I'm currently working on an updated version of that topic that I'm hoping to finish this week and you can provide feedback on that on PR #4704, if you'd like.

However, having a list of SDK versions doesn't seem like it's feasible. There can be so many. I think a better addition would be mentioning the new option for the dotnet command `--list-sdks` to help you see what you have installed in your machine already.

For example, this is what I get when I run this in one of my machines:
```
C:\>dotnet --list-sdks
1.0.0 [C:\Program Files\dotnet\sdk]
1.0.4 [C:\Program Files\dotnet\sdk]
1.1.0 [C:\Program Files\dotnet\sdk]
2.0.0 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.0.3 [C:\Program Files\dotnet\sdk]
2.1.2 [C:\Program Files\dotnet\sdk]
2.1.100 [C:\Program Files\dotnet\sdk]
2.1.102 [C:\Program Files\dotnet\sdk]
2.1.103 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
2.1.300-preview3-008443 [C:\Program Files\dotnet\sdk]
2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
```

/cc @KathleenDollard

**Comment by dasMulli** [comment]
I like to use https://github.com/dotnet/core/blob/master/release-notes/releases.json as my "source of trouth" esp. for download center links to the SDKs and checksums to update the [homebew cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/dotnet-sdk.rb).

@laultman does that help you? e.g. you could power a dropdown or a "get-latest" script from that file.

**Comment by mairaw** [comment]
@leecow would [releases.json](https://github.com/dotnet/core/blob/master/release-notes/releases.json) give me the main supported sdk version numbers? Or what does it mean for a version to be listed in that file?

The reason why I'm hesitant about this change @laultman is that not all versions are listed there and people can still install nightly builds, etc. and use this technique to pin down the sdk version. For example, if you look at the list of versions I pasted above for the ones I have on my machine, some of them are not on the releases.json file. For example, `1.0.0`, `1.1.0`, and `2.1.300-preview3-008443` are not in that file.

**Comment by laultman** [comment]
@mairaw @leecow I'll throw in my two cents.  I could easily see what was installed. Only one version. I'd spun up an new Azure VM and installed VS 2017. I did not have any global.json file at all in my projects.  VS was throwing a warning, offering that I should have a global.json with a hot link to the page you are responsible for.  I had no idea what the SDK's exact version should be nor did I know that it should be the one installed on my machine. All I has was the very old example from 1.0. That gave me enough to believe that the package label was probably not the version number I needed. After a couple hours searching Lee gave me the answer I needed - where to look. So maybe in your document you might point out to those on the bleeding edge who get the nightly builds to make sure they have the right one. "For what its worth."

**Comment by mairaw** [comment]
@laultman what kind of project it was? EF project? I'm just trying to understand the scenario where this is showing up and linking to our topic, in order to call out things explicitly.

@divega I see that you have a FWLink for that page. Can you explain the scenario where that link shows up? I'll follow up with an offline email too on some changes we need to make to that link.

**Comment by mairaw** [comment]
@divega has created an issue for the EF docs with some background info: https://github.com/aspnet/EntityFramework.Docs/issues/697

Can you confirm that the error message you were seeing is something like the following, @laultman?
`Startup project '{startupProject}' targets framework '.NETCoreApp' version '{targetFrameworkVersion}'. This version of the Entity Framework Core .NET Command-line Tools only supports version 2.0 or higher. For information on using older versions of the tools, see https://go.microsoft.com/fwlink/?linkid=871254`

Thanks!

**Comment by leecow** [comment]
@mairaw - the releases.json catalogs the latest official releases. Daily builds are not tracked.

**Comment by laultman** [comment]
@mairaw I am running VS ver. 15.8.0 Preview 1.1 on a VM (fresh install) I have a solution with 38 projects all in .NET Core 2.0. Some are .NETCoreStandard and some are .NETCoreApp. I am beginning the readiness upgrade to .NET Core 2.1 with the most current tooling. There is no EF in the solution. I upgraded all the projects in this branch to 2.1 where applicable. When the build runs in VS the Output windows has the following message along with all the other output verbiage:
"You are working with a preview version of the.NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452"
I did not have nor never have had a global.json file in my solution. Not sure if it buys me anything or not but the message seems to indicate that I need one. Hope this helps.

**Comment by mairaw** [comment]
Thank you for the extra information @laultman. It helps to track down the scenarios people are getting to this page. Since @leecow confirmed that the json file contains the latest official releases, I think we can add those.
