### ISSUE TITLE
How to know static members of the class

### ISSUE THREAD

**Issue by sateeshmachineni** [dotnet/docs#5252]
Earlier documentation used to say  whether a method is static or not,but these seems to be no longer the case.Any idea why ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18f2264-6230-68d2-98d2-4c3c7210c4a7
* Version Independent ID: 94faff8f-a332-cbfd-ddc4-7d2214ef7f01
* Content: [DriveInfo Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=netframework-4.7.1)
* Content Source: [xml/System.IO/DriveInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DriveInfo.xml)
* Service: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
ping @dend It looks like we regressed here. Should I move this to the MicrosoftDocs/Feedback repo.

**Comment by sateeshmachineni** [comment]
Guys ,any update on where i can see old documentation

**Comment by BillWagner** [comment]
@sateeshmachineni The old documentation is still on [msdn](https://msdn.microsoft.com/en-us/library/system.io.driveinfo%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

**Comment by BillWagner** [comment]
Moved to MicrosoftDocs/Feedback#469
