### ISSUE TITLE
:construction: Move inline F# samples to buildable projects

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#5253]
Noticed while reviewing #5239 and #5240 

The F# samples are often inline code rather than includes from buildable samples.

Where possible, we should move them to the [dotnet/samples](https://github.com/dotnet/samples) repository and use the include extension for the code. 

The benefits would be that the samples would be built by our (still being deployed) CI system on each new PR.

I'll suggest making an **fsharp** top level folder in samples, and adding the sample code there.

/cc @cartermp

**Comment by Potapy4** [comment]
@BillWagner I want to jump on to this issue, can you assign me? 😎
