### ISSUE TITLE
Are the Warnings expected?

### ISSUE THREAD

**Issue by helloguo** [dotnet/docs#5256]
Thanks for putting this great tutorial. I get some warnings when the pipeline processes. As mentioned in this tutorial "As the pipeline processes, it displays messages. You may see warnings, or processing messages". So are these Warnings expected?

The Warnings on my machine look like this:
Warning: Format error at (20,1)-(20,98): Illegal quoting
Warning: Format error at (197,1)-(197,21): Illegal quoting
Warning: Format error at (213,1)-(213,117): Illegal quoting
Warning: Format error at (323,1)-(323,17): Illegal quoting
Warning: Format error at (348,1)-(348,102): Illegal quoting
Warning: Format error at (845,1)-(845,101): Illegal quoting
Processed 1000 rows with 0 bad values and 6 format errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Service: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by BillWagner** [comment]
@helloguo Yes, those warnings and errors are expected. They show how the input classes process input that might be invalid. The docs mention that.

/cc @JRAlexander 

I'm going to close this because it is working correctly.
