### ISSUE TITLE
How to set IsByRef

### ISSUE THREAD

**Issue by NetMage** [dotnet/docs#5258]
It would be nice if how to set this is provided as the factory method doesn't seem to have an option to set this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3385de03-ce5c-e0dc-d414-5531fd11d48d
* Version Independent ID: 9b321768-471c-c0be-2b5d-ef9d882d0901
* Content: [ParameterExpression.IsByRef Property (System.Linq.Expressions)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.parameterexpression.isbyref?view=netframework-4.7.1#System_Linq_Expressions_ParameterExpression_IsByRef)
* Content Source: [xml/System.Linq.Expressions/ParameterExpression.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq.Expressions/ParameterExpression.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
You're right that it's not clear how that works.

I think that adding an example like the following with a short explanation might be sufficient:

```c#
var param = Expression.Parameter(typeof(int).MakeByRefType());
Console.WriteLine(param.Type); // System.Int32
Console.WriteLine(param.IsByRef); // True
```
