### ISSUE TITLE
IDataView missing from ML.NET API reference

### ISSUE THREAD

**Issue by svick** [dotnet/docs#5260]
I learned about the existence of the `Microsoft.ML.Runtime.Data.IDataView` interface (from the Microsoft.ML.Core assembly) and so I wanted to look at it in API reference, but [I didn't find it](https://docs.microsoft.com/en-us/dotnet/api/?term=%20IDataView).

I did find [the `IDataViewArrayConverter` type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.idataviewarrayconverter?view=ml-dotnet), which references `IDataView` from [its `Data` property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.idataviewarrayconverter.data?view=ml-dotnet#Microsoft_ML_Data_IDataViewArrayConverter_Data):

![](https://user-images.githubusercontent.com/287848/39831653-6d8ba748-53c5-11e8-85ef-5c8a4249784f.png)

I don't know if there are other types missing too, but it seems to me `IDataView` should be included in the API reference.

**Comment by BillWagner** [comment]
cc /@aditidugar @OliaG 

Any idea why the `IDataView` XML info is not part of the current NuGet package?

**Comment by mairaw** [comment]
@codemzs @danmosemsft can you comment on this one? Should we review the list of types?

Just a few types under Microsoft.ML.Runtime.* were chosen to be shown on the API reference docs. The others are being filtered out at https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/_filter.xml

**Comment by danmosemsft** [comment]
@codemzs @glebuk is this a type we are ready to expose publicly?

@svick, (nearly) all of the types in Microsoft.ML.Runtime.* are not yet "cleaned up" via API review, so we've chosen to not document them - yet! The documentation is currently verbatim from XML comments though, so you have the content in the code.

**Comment by glebuk** [comment]
I think we should expose IDV.  It is critical to use for those who want a flexible, high perf access to TLC. 
We do have some deep technical documentation about IDV and IDV type system that we can release.

**Comment by mairaw** [comment]
Thanks @glebuk. I’ll add that to the API docs. In regards to the deep technical docs, let’s discuss this with @JRAlexander upon his return.
