### ISSUE TITLE
.net standard and .net core

### ISSUE THREAD

**Issue by chivandikwa** [dotnet/docs#5267]
It would be great in this article to point out to readers here why the choice of a .net standard class library and not a .net core class library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852fcf8d-7873-c8cf-fd18-2b4b188003ef
* Version Independent ID: e3cec24b-80bf-fdfa-6f36-cf65d939f89d
* Content: [Building a complete .NET Core solution on Windows, using Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-windows-full-solution)
* Content Source: [docs/core/tutorials/using-on-windows-full-solution.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-windows-full-solution.md)
* Service: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
Thanks for pointing this out. The short answer is that relying on .NET Standard means the library can be used in more contexts: .NET Core, .NET Framework applications, Xamarin applications and so on.

**Comment by zhongyi91** [comment]
Following these steps, my test project cannot access the Thing class in the Library. It's only works if I use the .net core class library.
Did I missed something?
Thanks!
