### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by AntRemo** [dotnet/docs#5272]
Hi

I was wondering if this page is missing the API Reference documentation.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e881c120-c87c-b6a3-7082-7a194d55bf5a
* Version Independent ID: e9ff4cfe-f79d-0b9f-6875-0f7eab7770c5
* Content: [JSON Web Token Handler API Reference](https://docs.microsoft.com/en-us/dotnet/framework/security/json-web-token-handler-api-reference)
* Content Source: [docs/framework/security/json-web-token-handler-api-reference.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/json-web-token-handler-api-reference.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this issue @AntRemo. I’ve been trying to get an answer from the product team on what we need to regarding this page.

**Comment by infoberg** [comment]
still zero documentation after nearly 2 1/2 months?

**Comment by mairaw** [comment]
The plan is to actually remove that page @infoberg. I’m handling that today.

**Comment by CreativeHouseDotOrg** [comment]
Hi, we're currently building an App with JWT Bearer Tokens and the team and i got stuck with the Refresh Token Part... Any Documentation about this would be great. Thanks in advance.

**Comment by infoberg** [comment]
Save yourself some work and frustration and use jose-jwt instead...
