### ISSUE TITLE
Using HTML list tags

### ISSUE THREAD

**Issue by progalgo** [dotnet/docs#5275]
The algorithm in "Remarks" section should probably be ordered list instead of unordered list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5527c307-6079-70ab-211e-fa3360edf0b5
* Version Independent ID: cee9ff7e-3532-5aee-537f-fe4b85a6b529
* Content: [DataContext.CreateDatabase Method (System.Data.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.datacontext.createdatabase?view=netframework-4.7.2#System_Data_Linq_DataContext_CreateDatabase)
* Content Source: [xml/System.Data.Linq/DataContext.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Linq/DataContext.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@progalgo thanks for spotting and reporting the issue; the PR with the fix is about to be merged.
