### ISSUE TITLE
In-/out-faro reversed

### ISSUE THREAD

**Issue by sblom** [dotnet/docs#5276]
Your descriptions of in- and out-faros are reversed. https://en.wikipedia.org/wiki/Faro_shuffle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing out that mistake @sblom
