### ISSUE TITLE
new operator in paragraph as code.  Structs

### ISSUE THREAD

**Issue by TheBrooks** [dotnet/docs#5286]
Should the `new` operator in the text 'Struct constructors are invoked with the new operator' be marked up as code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 071b082e-a4aa-00af-1f03-9f6f7205c0bc
* Version Independent ID: cbd67b7f-8aae-2d43-a1dc-26a8b870389e
* Content: [C# structs - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/structs#feedback)
* Content Source: [docs/csharp/tour-of-csharp/structs.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/structs.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Yes, it should @TheBrooks. I'll fix that.
