### ISSUE TITLE
Advantages?

### ISSUE THREAD

**Issue by chivandikwa** [dotnet/docs#5288]
Interesting, I am however wondering why one would want  to do this as opposed to running the unit tests before publishing, then publishing if all is well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269a1ac1-62e0-bd9e-bdd8-f1762e6e62c6
* Version Independent ID: a820e026-7b54-9516-d4c8-0c07e078b6e0
* Content: [Test published output with dotnet vstest](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-published-output)
* Content Source: [docs/core/testing/unit-testing-published-output.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-published-output.md)
* Service: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by kendrahavens** [comment]
Yes, you can definitely run tests before publishing while you are still in your development cycle by using the ['dotnet test' command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x). This is just an additional option.
