### ISSUE TITLE
Add a note about kb2533623 for windows 7 users.

### ISSUE THREAD

**Issue by Ryzhehvost** [dotnet/docs#5290]
.NET Core need update https://support.microsoft.com/en-us/kb/2533623 to be installed on Windows 7, Vista and Server 2008. It was suggested here: https://github.com/dotnet/cli/issues/3907 and really help to resolve startup issues. I believe it is worth to be mentioned as a note on prerequisites page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Service: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Thanks for your feedback @Ryzhehvost! @Petermarcu @leecow we do mention KB 2999226 as a requirement for older versions but not KB 2533623? Can I go ahead and add this? 

@Ryzhehvost do you remember if there were any error messages displayed if you didn't have that KB installed?

**Comment by Ryzhehvost** [comment]
I don't met this issue myself, and the guy who had it told me he got
`Failed to load the dll from [?Z], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed
- Installing .NET Core prerequisites might help resolve this problem:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409`

**Comment by leecow** [comment]
That's an update we would prefer everyone have installed anyway so, I don't have any objections to adding it.

**Comment by mairaw** [comment]
Cool. Thanks for confirming @leecow!

**Comment by mairaw** [comment]
@leecow one more question. Should we change the code [here](https://github.com/dotnet/core-setup/blob/9a776be820ff4ae83476c7e9e97514ecd8f3ae1d/src/corehost/corehost.cpp#L267) to link to the [prerequisites page](https://docs.microsoft.com/dotnet/core/windows-prerequisites) instead of the Get started one? http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409 seems the wrong one to be pointing to when someone runs into that issue.

**Comment by pwen090** [comment]
We have installed the relevant KB but are still getting the error "Unable to load DLL 'api-ms-win-eventing-provider-l1-1-0.dll' or one of its dependencies: The specified module could not be found." for .NET Core 3.0 on Windows 7.

**Comment by narcis-pv** [comment]
@pwen090 Install  [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/download/details.aspx?id=52685).

**Comment by Sm1le291** [comment]
Hi everyone! Now we are deciding to move to Core 2.0 or never minor version. And I am not clearly understand one thing. I did not find in table compatability that Vista and Server 2008 SP2 support .net core 2 runtime. But below(on ms site) compatability table I can see that with patch kb2533623 it possible to run .Net core 2 on Vista SP2 and Server 2008. Is it right?
