### ISSUE TITLE
No return value mentioned

### ISSUE THREAD

**Issue by misha-fm** [dotnet/docs#5292]
The article says that ?. operator is "used to test for null before performing a member access (?.) or index (?[]) operation". But nowhere in the article it's explicitely said that it returns null value if the check isn't passed. Though on 'contents' page for operators it's stated explicitely: "null conditional member access. Returns null if the left-hand operand evaluates to null" (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49bd5a1a-9074-0d01-f6fc-5647f6c0fb2f
* Version Independent ID: f20891dd-86a4-ec9f-0162-fd87b85612c9
* Content: [Null-conditional Operators (C# and Visual Basic)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators)
* Content Source: [docs/csharp/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/null-conditional-operators.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@misha-fm that's a good remark. PR #5294 updates the topic based on your feedback. Thanks!
