### ISSUE TITLE
"dotnet new nunit" screenshot has a giant white line in the middle of screenshot

### ISSUE THREAD

**Issue by manish** [dotnet/docs#5293]
On the page **Create a custom template for dotnet new**

under [Create a project from the template](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#create-a-project-from-the-template)

the output of command

`dotnet new nunit`

![](https://docs.microsoft.com/en-us/dotnet/core/tutorials/media/create-custom-template/nunit2.png)

has a huge white line running through it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ccd42dc-0af2-1fa1-130a-61aff2d0770c
* Version Independent ID: 612b5eb7-23b9-68cd-a184-df9268ddb768
* Content: [Create a custom template for dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#create-a-project-from-the-template)
* Content Source: [docs/core/tutorials/create-custom-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/create-custom-template.md)
* Service: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @manish. I think that was done on purpose to shorten the screenshot. I'll need to double check to make sure.

**Comment by manish** [comment]
If it was supposed to ellipse-ize the screenshot, can we add some kind of jagged line in the middle to signify that? Just proposing ideas.

**Comment by mairaw** [comment]
Sure, we could also note that in the introductory sentence. I'll get back to you once I've verified.

**Comment by guardrex** [comment]
Yes, correct. It was done to shorten the height of the image. I may have used a straight line and not jagged because jagged doesn't match the style of the site. We have a few topics where images have that torn-paper edge look, and it seems very at-odds with the docs theme.

**Comment by Banner-Keith** [comment]
The purpose of the white line is not clear and looks pretty sloppy. I'm not sure how you should properly theme it, but this is not the answer.

**Comment by guardrex** [comment]
We also use ellipsis quite a bit. It could have is a "... continued ..." super-imposed on the image without the line.

**Comment by Thraka** [comment]
Should just get rid of the image. It doesn't add anything by being a picture and just complicates things. Simply use a code block with ** ... cut to save space ...** in the middle.

**Comment by guardrex** [comment]
... or even just don't show the output at all. This section can just end on ...

> The console shows that the project is created and that the project's packages are restored. After the command is run, the project is ready for use.
