### ISSUE TITLE
No content on removing items

### ISSUE THREAD

**Issue by javierdlg** [dotnet/docs#5296]
Seems like all the remarks are about adding or modifying data. What about when you remove content? Does it follow the same rules as adding? What happens when you remove and another tries to access? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d05753-640a-9bb9-d548-77bc9e82616d
* Version Independent ID: 72d44346-2d65-2e97-75a5-7d6f7f5012e6
* Content: [How to: Add and Remove Items from a ConcurrentDictionary](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-add-and-remove-items)
* Content Source: [docs/standard/collections/thread-safe/how-to-add-and-remove-items.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/how-to-add-and-remove-items.md)
* Service: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by IEvangelist** [comment]
Hi @javierdlg,
Added example usage of `TryRemove` and clean up doc. https://github.com/dotnet/docs/pull/18247
