### ISSUE TITLE
 I have not been able to find a definition of "CLR property" on the WWW. 

### ISSUE THREAD

**Issue by jotway** [dotnet/docs#5299]
"Windows Presentation Foundation (WPF) provides a set of services that can be used to extend the functionality of a common language runtime (CLR) property."  I have not been able to find a definition of "CLR property" on the WWW.  Are they the same as C# Properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059d0e32-64d0-95ee-d8a6-02a45eca1fdf
* Version Independent ID: 308d21cc-18c5-54c4-bc35-59060a627d5f
* Content: [Dependency properties overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dependency-properties-overview)
* Content Source: [docs/framework/wpf/advanced/dependency-properties-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/dependency-properties-overview.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for asking this question and raising the issue of what a CLR property is, @jotway. "CLR properties" is actually a misnomer. Properties are members of a .NET type, as defined by the Common Language Specification. Individual languages, such as C#, then provide a language-specific syntax for defining properties. 
We'll modify the topic to note that dependent properties extend .NET properties.
