### ISSUE TITLE
Wrong syntax for default member

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/docs#5301]
I believe the syntax given for default member is wrong. It should not be "default member", but simply "default". At least the example says so, and the example turned out to be the way to do it for the case I'm dealing with right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680c7c1b-10c0-0537-a52e-48214b55ca4c
* Version Independent ID: ec7268c9-a299-8a21-65c9-3da7dae8a45d
* Content: [Methods (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/methods)
* Content Source: [docs/fsharp/language-reference/members/methods.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/methods.md)
* Service: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by BentTranberg** [comment]
This is not the page I was on when I reported this error. I was on the Properties page.
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/properties

**Comment by mairaw** [comment]
@BentTranberg the system logged the issue on the methods page and that's where @cartermp fixed the issue. I don't see a syntax for default members in the Properties page though.

**Comment by BentTranberg** [comment]
Sorry, I was wrong, you're right. I found out why I thought what I thought. At least this lead me to a second error that I reported. Never so bad it isn't good for nothing ...

**Comment by mairaw** [comment]
No worries. Thanks for reporting these issues. I'm glad it's not an issue with our new feedback system.

Also, for simple fixes, you can also just hit the Edit button on the page and submit the fix suggestion if you know what needs to be changed.

**Comment by BentTranberg** [comment]
I did hit the Edit button earlier, but wasn't sure how to proceed from there, or whether I had access. I see now that there is a link titled "How to contribute", which I believe explains it, so I'll probably try out that next time. Thanks for the suggestion.
