### ISSUE TITLE
source code link missing

### ISSUE THREAD

**Issue by HasanAliKaraca** [dotnet/docs#5306]
How can i access the source code of this tool(WcfTestClient.exe)? Can someone update the doc with  source code link of the tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599983a3-8520-1f76-61c6-4b77ef804492
* Version Independent ID: 37629297-b13c-bd53-aeac-5646c6bdc06f
* Content: [WCF Test Client (WcfTestClient.exe)](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-test-client-wcftestclient-exe)
* Content Source: [docs/framework/wcf/wcf-test-client-wcftestclient-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/wcf-test-client-wcftestclient-exe.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
@HasanAliKaraca Thanks for pointing this out. 

The WCF Test client is installed with Visual Studio. I don't know if there is a separate download.

**Comment by rpetrusha** [comment]
@HasanAliKaraca, the source code for WCFTestClient.exe is not publicly available. I'll close this issue.
