### ISSUE TITLE
KeySize and Key

### ISSUE THREAD

**Issue by radu-v** [dotnet/docs#5307]
It should be noted, that changing the KeySize value will generate a new, random Key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce74cb2-9214-8ec0-d97d-badb6e8191b6
* Version Independent ID: a972c626-eb98-4f93-cd25-6b583e2a6f10
* Content: [AesCryptoServiceProvider.KeySize Property (System.Security.Cryptography)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aescryptoserviceprovider.keysize?view=netframework-4.7.1#System_Security_Cryptography_AesCryptoServiceProvider_KeySize)
* Content Source: [xml/System.Security.Cryptography/AesCryptoServiceProvider.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/AesCryptoServiceProvider.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by kapiljaveri** [comment]
Hello

Just submitted a PR for this.  Let me know if this looks good or if you'd like any changes.

Thanks!

**Comment by radu-v** [comment]
Looks good to me
