### ISSUE TITLE
Private constructor inherit

### ISSUE THREAD

**Issue by siva1254** [dotnet/docs#5317]
Can we inherit  private constructor class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aed1d9c-756b-5edc-5c2e-4c25af577ffd
* Version Independent ID: d6b5ce45-a2d6-279e-68fe-280c0774dbcb
* Content: [Private Constructors (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/private-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/private-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/private-constructors.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for asking the question, @siva1254. Constructors are not inherited by derived classes. For more information, see [Inheritance in C# and .NET](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance#background-what-is-inheritance).
