### ISSUE TITLE
.NET 3.5 SP1 Missing

### ISSUE THREAD

**Issue by JaredShaver** [dotnet/docs#5319]
Information on the System Requirements/supported platforms for .NET 3.5 SP1 is missing.  The Lifecycle FAQ—.NET Framework https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework says "For a list of supported operating systems for .NET Framework 3.5 SP1 refer to the .NET Framework system requirements." and links to https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Service: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by jbruns2015** [comment]
+1

**Comment by lindexi** [comment]
We can only install dotnet framework 4.6.2 to win7 but we can install dotnet framework 4.7.2 in win7 sp1.

**Comment by rpetrusha** [comment]
Thanks for your feedback, @JaredShaver. I apologize that it's taken so long to respond.

The System Requirements page is designed to provide information about .NET Framework 4.5 and later versions only. The [.NET Framework versions and dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies) article provides information about all previous .NET Framework versions.  We've opened #7977 to add a cross-reference to the versions and dependencies article from the system requirement article.
