### ISSUE TITLE
Broken link on AssemblyBuilderAccess Enumeration

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#5323]
https://msdn.microsoft.com/en-us/library/system.reflection.emit.assemblybuilderaccess(v=vs.110).aspx

The following link is broken:

The dynamic assembly can be unloaded and its memory reclaimed, subject to the restrictions described in Collectible Assemblies for Dynamic Type Generation.
--

(does not exist) https://msdn.microsoft.com/en-us/library/dd554932(v=vs.110).aspx

**Comment by mairaw** [comment]
Hi @jeffschwMSFT, given that we're moving all the API reference documentation to docs.microsoft.com and this link no longer exists in the current version at https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilderaccess?view=netframework-4.7.2, I'll be closing this issue as resolved. Final redirection should happen in the next couple of months.

On MSDN, you need to select a different version to see the topic in question:
![image](https://user-images.githubusercontent.com/12971179/39947794-10260eb8-5528-11e8-82ff-c89ce7a2f2db.png)
