### ISSUE TITLE
How do I find Release Notes for Microsoft's NuGet packages, such as this one?

### ISSUE THREAD

**Issue by JeremyMorton** [dotnet/docs#5326]
The NuGet package has a completely useless "Project URL" of https://dot.net which doesn't have any direct information on System.Threading.Tasks.Dataflow, nor what changed between 4.8.0 and 4.9.0-rc1. This is a problem with all of Microsoft's NuGet packages; they all point to the same super-general URL, that then has no clear way to find out anything about the package of interest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d88b09c-ae2f-e362-fd66-751a944def85
* Version Independent ID: 5066b7a6-cc2a-3507-9dcb-4eb7d2a355b9
* Content: [System.Threading.Tasks.Dataflow Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow?view=netcore-2.0)
* Content Source: [xml/ns-System.Threading.Tasks.Dataflow.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Threading.Tasks.Dataflow.xml)
* Service: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @JeremyMorton. We have plans to start adding some docs for selected NuGet packages in the future, but right now our docs are only focused on what ships on the platform (.NET Core, .NET Framework, etc.) and not on the NuGet packages.

@terrajobst @stephentoub do you know who owns that NuGet package? Are there any release notes for those? The release notes link on that package is https://go.microsoft.com/fwlink/?LinkID=799421, which doesn't seem appropriate.

**Comment by JeremyMorton** [comment]
Is there an easy way to find the source for this package in GitHub? (Assuming that it is in GitHub.)

**Comment by svick** [comment]
@JeremyMorton The source code for that package is at https://github.com/dotnet/corefx/tree/master/src/System.Threading.Tasks.Dataflow.

**Comment by svick** [comment]
Also see https://github.com/dotnet/corefx/issues/23570 for another issue about adding Release Notes to .Net NuGet packages.

**Comment by JRAlexander** [comment]
Closing as it appears resolved. If this isn't the case, please reopen. Thanks!
