### ISSUE TITLE
"Microsoft ML.NET" nuget package can not be found

### ISSUE THREAD

**Issue by GeXiaoguo** [dotnet/docs#5329]
# "Microsoft ML.NET" nuget package can not be found
The [tutorial example](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis) Mentioned installing "Microsoft ML.Net" nuget package. It can not be found on nuget.org. The correct package name is "Microsoft.ML" as mentioned [here](https://github.com/dotnet/machinelearning)

**Comment by mairaw** [comment]
Thanks for reporting this issue. We’ll get it fixed soon.
