### ISSUE TITLE
If domain events are sent out and handled by handlers, does that mean the savechanges operation will be blocked until all handler finish execution? 

### ISSUE THREAD

**Issue by yang-zhang-syd** [dotnet/docs#5331]
If domain events are sent out and handled by handlers, does that mean the savechanges operation will be blocked until all handler finish execution? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: fa6385e8-91ad-7949-382f-ca8e03f8201c
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Service: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CESARDELATORRE can you please comment on this and address it if needed? Thanks!

**Comment by ig16022** [comment]
I don't see a response to this question, and I think its an important question to answer. Additionally, even though there is an 'await' on await _mediator.DispatchDomainEventsAsync(this); 
within the context's SaveEntitiesAsync() method and the base.SaveChanges() will clearly wait for the domain event handlers to complete their work, I also see 
await _buyerRepository.UnitOfWork
                .SaveEntitiesAsync();
in the ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler (Handle() method), and it appears that the buyer will be saved immediately, not as part of a transaction with the Order. This goes against the idea of including Side Effects in an Aggregate's 'save' transaction.

**Comment by mvelosop** [comment]
Just for the record, this was answered on issue dotnet-architecture/eshoponcontainers#721 (it's a bug).

**Comment by mvelosop** [comment]
Closing this issue now, as duplicate of dotnet-architecture/eshoponcontainers#721 it's currently being addressed there.
