### ISSUE TITLE
"Download PDF" link is outdated

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#5336]
The "Download PDF" link that's fixed in the lower left corner points to an old version of the ebook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 9cc14513-c458-d615-9615-7003c614b7cd
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/#feedback)
* Content Source: [docs/standard/microservices-architecture/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/index.md)
* Service: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Hi @cmeeren, you mean compared to the one offered at https://www.microsoft.com/net/learn/architecture? If so, this is by design since the Download PDF button is a generic functionality of Docs and generated the content based on what's here on repo. So I can see that it contains the latest changes present here.

But I know that @CESARDELATORRE is planning to bring the changes in, so he can speak more of the timeline of when that is going to be ported over here.

**Comment by cmeeren** [comment]
Hi! I'm talking about the "Download PDF" at the lower left corner of [this page](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/#feedback). A colleague of mine ended up starting reading the previous version of the book because he that link, instead of the link just below the cover image at the top (which points to the new version of the ebook).

**Comment by mairaw** [comment]
But are you comparing that to the one available at https://www.microsoft.com/net/learn/architecture? Or are you comparing the content published on Docs vs. what's on the PDF? That Download PDF button is not aware of the new editions of the book at https://www.microsoft.com/net/learn/architecture. It's just the PDF representation of what's currently published on docs.microsoft.com.

**Comment by cmeeren** [comment]
I'm talking about these two links. The lower-left link points to the old eBook, whereas the in-text link points to the updated eBook.

![image](https://user-images.githubusercontent.com/7766733/40706063-ec73fef2-63ec-11e8-8e4e-77931d1bf529.png)

**Comment by mairaw** [comment]
Ok that confirms the information I was looking for @cmeeren. The Download PDF button is a functionality of the docs.microsoft.com and is not aware of different editions of the book available at http://aka.ms/microservicesebook. The articles on docs.microsoft.com haven't been updated with the contents from the 2nd edition of the book. Ideally, we'll move to a process where we have a single source for this content, so we don't have discrepancies between what you see on docs.microsoft.com and https://www.microsoft.com/net/learn/architecture.

**Comment by mairaw** [comment]
Given the e-book has been updated to 2.2, now both versions should match. We still don't have a single source but the team has been trying to make the updates quicker than before on both places.
