### ISSUE TITLE
More text needed on specification of URL parameter

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#5337]
The syntax of the URL parameter needs a bit of filling out: you give an remark: "The url parameter can be of the form C:\path\sample.chm or /folder/file.htm." The last example does not have a full folder path, but there is no explanation of where this file is to be found. Is the "folder" relative to the folder holding the program executable, or the root of the current (whatever that is) drive? And in the latter case, what happens when the program is installed on a machine with a different folder structure from the original,  which will be the normal case?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563145f3-8c83-17aa-d755-206881e9b10e
* Version Independent ID: 68e9e761-499a-9bf2-dc30-8d7b5df84a67
* Content: [Help.ShowHelp Method (System.Windows.Forms)](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.help.showhelp?view=netframework-4.7.1)
* Content Source: [xml/System.Windows.Forms/Help.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/Help.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the lack of clarity in the documentation, @ptoye. /folder/file.htm is a path from the root of the current drive, and the documentation needs to make that clear. We'll address this issue once we finish work on the related issue #4280.
.
