### ISSUE TITLE
Programmer

### ISSUE THREAD

**Issue by RoswellMiller** [dotnet/docs#5339]
The syntax given above refers to "type-definition-elements" and gives a good description of what is allowed in the list.  Is this not essentially the same as the "member-list" referred to in records and classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a067d5a-bb13-9991-c808-c7c49a00ca47
* Version Independent ID: 201272a0-3350-93f3-8965-4a745671c7e7
* Content: [Structures (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/structures)
* Content Source: [docs/fsharp/language-reference/structures.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/structures.md)
* Service: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Addressed in both the doc and the snippet.

https://github.com/dotnet/docs/pull/5341
https://github.com/dotnet/samples/pull/66
