### ISSUE TITLE
root folder pollution

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/docs#5342]
the root folder of a repository is a very important place to keep tidy, consider moving this to a .dotnet folder instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json reference](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#feedback)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Service: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc should I move this to one of the product repos?

**Comment by livarcocc** [comment]
Is this about moving the global.json file? You can move it, but we have no plans to move this file around at the moment. It would be a breaking change.

**Comment by mairaw** [comment]
Too many moves in one sentence. 😄 
I'm going to close this request then. @smoothdeveloper please open a request on dotnet/cli if there are other product requests you'd like to make.

**Comment by KathleenDollard** [comment]
Yes, if @smoothdeveloper thinks this important, it can be something we consider when we think about what a future global.json story should be
