### ISSUE TITLE
Incorrect name of NuGet package to seach for in package manager

### ISSUE THREAD

**Issue by RobDaPraia** [dotnet/docs#5343]
NuGet package, in package explorer, search for "Microsoft.ML" instead of "Microsoft ML.NET"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Service: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Thanks for your feedback @RobDaPraia. I have a PR open already to fix this issue.

**Comment by sudheervm** [comment]
PM> Install-Package Microsoft.ML
