### ISSUE TITLE
.NET Framework 4.7.2 sdk  download page issues

### ISSUE THREAD

**Issue by xLabel** [dotnet/docs#5345]
I am a  .net Chinese developer . When I downloaded the SDK(4.7.2 dev pack) package on the official website with  Chrome explorer, the page was redirected(http302) to download the language pack only, not the "really" dev pack.

download pages :
https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md
https://www.microsoft.com/net/download/thank-you/net472-developer-pack

**Comment by mairaw** [comment]
@preetikr @vivmishra can you check the links for the dev pack? Thanks!

**Comment by mairaw** [comment]
@xLabel can you confirm which of the links are you clicking on? The one for the 4.7.2 dev pack on the topic (http://go.microsoft.com/fwlink/?LinkId=863261) seems to be working fine.

**Comment by xLabel** [comment]
@mairaw 

i click this link address (http://go.microsoft.com/fwlink/?LinkId=863261) will be redirect to this
download address(https://download.microsoft.com/download/5/7/7/57703C9C-1027-4533-A69D-2393314A32D1/NDP472-DevPack-CHS.exe), this dev pack is about 13.45MB, only the lanageuage pack ? not the "really" dev pack

when i use fiddler simulation web browser to httpget the link address (http://go.microsoft.com/fwlink/?LinkId=863261), will be redirect to this
(https://download.microsoft.com/download/5/F/E/5FE505D0-E753-4F1A-B8D6-D9E73C0C28C7/NDP472-DevPack-ENU.exe), this pack about 90+MB

**Comment by xLabel** [comment]
@mairaw 
here is the http request header, "Accept-Language" is a key point.

User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9

**Comment by mairaw** [comment]
Thanks @xLabel. Our engineering team investigated the issue and managed to repro the problem. They're currently working on a fix. We'll let you know once the fix is in place. We appreciate for letting us know about this.

**Comment by xLabel** [comment]
@mairaw : )

**Comment by yhnbgfd** [comment]
@mairaw hi,  download link is wrong again, it has become download NDP472-DevPack-CHS.exe  and NDP472-KB4054530-x86-x64-AllOS-CHS.exe.
 .NET Framework 4.7.2  Offline Installer  :  Developer Pack &  Runtime

**Comment by rowanmiller** [comment]
@yhnbgfd I just pushed a change to https://www.microsoft.com/net/download/windows that should fix the issue for you. Can you confirm.

**Comment by yhnbgfd** [comment]
@rowanmiller All download links are now correct
