### ISSUE TITLE
Paths for data and model are incorrect

### ISSUE THREAD

**Issue by DaisyDave** [dotnet/docs#5346]
The paths for the data and model folders contain one too many '..\\'.

The documentation says create the data folder in the bin directory but the paths step out of the bin folder into the project folder. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to Predict New York Taxi Fares (Regression).](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Thank you for your feedback @DaisyDave. I'll get this addressed as part of other changes I'm making to the tutorials.

**Comment by BillWagner** [comment]
@mairaw When I was running these, I noticed that the number of ".." needed changed if you F5 from Visual Studio, or ran from the CLI using "dotnet run". We should make a note of that, even if the tutorial assumes Visual Studio.

**Comment by burstingninja** [comment]
they forgot to mention in the instructions to create a "Models" folder for the app to work

**Comment by mairaw** [comment]
I changed the tutorial/code to work with both VS and dotnet run now @BillWagner. And I changed the code as well to no longer need the Models folder @burstingninja.
