### ISSUE TITLE
MaxNumber?

### ISSUE THREAD

**Issue by johntempest** [dotnet/docs#5347]
When I run this workflow, the app asks me to "guess a number between 1 and 0". MaxNumber appears to be set as = 100 and entered into the dictionary entry inputs, but how does wfApp then retrieve the value of MaxNumber using inputs? I can't see anything in the first two parts of the tutorial where inputs is declared or any mechanism to set the value of MaxNumber.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe71b9e-5bc8-a8d8-05a3-8bdf7fe8170c
* Version Independent ID: 066b5c8d-81f5-a9e2-262d-98eaf7f81f80
* Content: [How to: Run a Workflow](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-run-a-workflow)
* Content Source: [docs/framework/windows-workflow-foundation/how-to-run-a-workflow.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/how-to-run-a-workflow.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @johntempest. We'd need to investigate this issue. So we're adding this to our backlog right now.

**Comment by hexalm** [comment]
Hey @johntempest There's actually no other mapping required--if you've defined MaxNumber as an "In" argument in the workflow, passing it in this line allows the workflow to access the variable:
`WorkflowApplication wfApp =
                new WorkflowApplication(new StateMachineNumberGuessWorkflow(), inputs);`

I suggest checking the spelling and type of the argument on the workflow activity you're using.
