### ISSUE TITLE
I translated the ML.NET tutorials' docs into Chinese version

### ISSUE THREAD

**Issue by Quorafind** [dotnet/docs#5348]
After the Microsoft build 2018, I was excited to read the ML.NET tutorials. And then I found that there has no Chinese version of it. So I did it. Here is the link of my translation. https://github.com/Quorafind/MLNET-CN. All in markdown. Hope it will help you. ML.NET is great ,and I want more normal Chinese developers can use it. LOL

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Service: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
I’ll follow up with the localization team on the plans for translating that content. We worked on the English content until the very last minute and we’re still making some adjustments. Thanks for translating it to other developers.

/cc @nokura

**Comment by mairaw** [comment]
@nokura when do you think the ML.NET topics will be available in Chinese? Thanks!

**Comment by mairaw** [comment]
Closing this one since those docs have now been published in Chinese as well @Quorafind.
