### ISSUE TITLE
Elaborate

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5350]
More elaboration please. Modifiers such as what? internal? public? protected? abstract? partial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00849c36-156c-6fcd-80f9-dfa038c80964
* Version Independent ID: b144221e-7f82-482a-7a3c-056c5557b673
* Content: [ClassDeclarationSyntax.Modifiers Property (Microsoft.CodeAnalysis.CSharp.Syntax)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.classdeclarationsyntax.modifiers?view=roslyn-dotnet#Microsoft_CodeAnalysis_CSharp_Syntax_ClassDeclarationSyntax_Modifiers)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ClassDeclarationSyntax.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ClassDeclarationSyntax.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by BillWagner** [comment]
@mwpowellhtx I'd like to get some more information about what you're trying to build.

Right now, the Roslyn API docs don't have the coverage I'd like for samples, examples, tutorials and conceptual content. That's an area I'll be working on in the next several months. I'm in the process of creating outlines and ideas for scenarios and concepts to cover. Any information you can add here, or on the other issues would help me plan the right topics that will help you learn the concepts and become more productive. Thanks in advance.

**Comment by mwpowellhtx** [comment]
@BillWagner Sorry for circling around a bit late. 

At the moment, I am working on a VSIX and some bits that will analyze a class, a build time only decoration attribute, and spit out some boilerplate code.

Specifically, I want to generate:

1. A partial class mirroring the target decorated class.
1. Several static operator overloads, namely for bitwise operators, complement, and, or, and exclusive or, which will basically just invoke named methods in the base class, but exposed via some **VERY** boilerplate code.

I'm working from a couple of illustrative open source examples at the moment. However, these will be my areas of focus, at the moment.

**Comment by BillWagner** [comment]
thanks @mwpowellhtx That helps.

**Comment by mwpowellhtx** [comment]
@BillWagner No problem. Good luck!
