### ISSUE TITLE
Elaborate please

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5352]
As in the Generic Type list? And then, in what level of depth? i.e. What happens for nested types, types within types?

i.e. class A<T, R> : B, IC<A<T>> {}

Along these lines. It can get pretty nested, at any rate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fcff29a-4e06-9352-846e-4e037abb8188
* Version Independent ID: fa5d387a-a37d-c412-21e6-bb0d31c14971
* Content: [ClassDeclarationSyntax.TypeParameterList Property (Microsoft.CodeAnalysis.CSharp.Syntax)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.classdeclarationsyntax.typeparameterlist?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ClassDeclarationSyntax.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ClassDeclarationSyntax.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by mairaw** [comment]
Closing this one since https://github.com/dotnet/roslyn/issues/27645 is tracking this work item.
