### ISSUE TITLE
Elaborate please

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5353]
How is it useful? How do I go from ClassDeclarationSyntax, for instance, and identify its Namespace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63110b74-3e57-a4c7-9ded-7f94c724cd75
* Version Independent ID: 5a2800f4-4790-5fb5-8034-06749ee171d3
* Content: [NamespaceDeclarationSyntax Class (Microsoft.CodeAnalysis.CSharp.Syntax)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.namespacedeclarationsyntax?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/NamespaceDeclarationSyntax.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/NamespaceDeclarationSyntax.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by svick** [comment]
The `Microsoft.CodeAnalysis.CSharp.Syntax` types form a *syntax tree*. If you have `ClassDeclarationSyntax` for a class that's in a namespace, its `Parent` will be a `NamespaceDeclarationSyntax`.

For example:

```c#
string code = @"
namespace Foo.Bar
{
    class C {}
}";

var unit = SyntaxFactory.ParseCompilationUnit(code);

var classDeclaration = unit.DescendantNodes().OfType<ClassDeclarationSyntax>().Single();

var namespaceDeclaration = (NamespaceDeclarationSyntax)classDeclaration.Parent;

Console.WriteLine(namespaceDeclaration.Name); // prints Foo.Bar
```

Though these types will only give you syntactic information. If you don't control the code you're processing, you're probably better off using `SemanticModel` to find the namespace of a class:

```c#
string code = @"
namespace Foo
{
    namespace Bar
    {
        class C {}
    }
}";

var tree = SyntaxFactory.ParseSyntaxTree(code);

var classDeclaration =
    tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().Single();

var namespaceDeclaration = (NamespaceDeclarationSyntax)classDeclaration.Parent;

Console.WriteLine(namespaceDeclaration.Name); // prints Bar

var compilation = CSharpCompilation.Create(null).AddSyntaxTrees(tree);

var semanticModel = compilation.GetSemanticModel(tree);

Console.WriteLine(
    semanticModel.GetDeclaredSymbol(classDeclaration).ContainingNamespace); // prints Foo.Bar
```

Though I'm not sure how much of this information belongs to the API reference.

**Comment by mwpowellhtx** [comment]
The whole point of the docs is to make is clear, or at least clearer, as to what's what. I'm providing this feedback, not looking for direct feedback here, per se, but rather to flesh out the docs themselves.

**Comment by mairaw** [comment]
Closing as this work item is being tracked at https://github.com/dotnet/roslyn/issues/27645
