### ISSUE TITLE
very useful

### ISSUE THREAD

**Issue by pablop45** [dotnet/docs#5355]
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Collections interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/list-collection.yml)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
We're glad you liked it! Thanks!
