### ISSUE TITLE
ports?

### ISSUE THREAD

**Issue by jyjohnson** [dotnet/docs#5360]
When using address="*" , does that include all ports or just 80?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874465ad-c7ea-f09b-4c2f-79d6f150a79b
* Version Independent ID: 108a137f-31d3-c3c2-2ff9-3cf128c3b8d9
* Content: [<add> Element for connectionManagement (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings.md)
* Service: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mairaw** [comment]
@davidsh @karelz would you know this?

**Comment by davidsh** [comment]
>When using address="*" , does that include all ports or just 80?

In this context, the "*" means ANY port that is used to make an HTTP/HTTPS connection.  Usually it is port 80 or 443.  But it could be anything that a dev passes into the HTTP APIs for doing a request.  I.e., non-default port values would be passed in like this: "http://www.contoso.com:81/path".

**Comment by anaki99** [comment]
Not working with DownloadFileAsync.

**Comment by karelz** [comment]
@anaki99 can you please be more specific? Do you have minimal repro showing what exactly doesn't work?

**Comment by michaelblyons** [comment]
I would really appreciate seeing the default values for when no rules exist:

- Is it `*`=>`2`, like the default for `<add>`s without a `maxconnection`?
- Is `localhost` treated the same as the rest of the network, unless there's an explicit rule?

I would also like to see an example that was not `http`/`https`, and another example that uses IP.

Thirdly, can we use wildcards (or CIDR) for hosts, schemas, or IPs?
