### ISSUE TITLE
Example of SharedConfig.xml

### ISSUE THREAD

**Issue by mitgiraffe** [dotnet/docs#5362]
While a reference to sharedConfig.xml is provided, there is nothing that indicates the required schema for that document.
A small example of what I have found to work is:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
	  <dependentAssembly>
		<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
	  </dependentAssembly>
	</assemblyBinding>
  </configuration>
</runtime>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bff372b-d797-731c-a2fa-5d4b072264f0
* Version Independent ID: 72507aa8-582a-c77d-fb63-f7ea75facded
* Content: [\<assemblyBinding> element for \<configuration>](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/assemblybinding-element-for-configuration)
* Content Source: [docs/framework/configure-apps/file-schema/assemblybinding-element-for-configuration.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/assemblybinding-element-for-configuration.md)
* Service: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mairaw** [comment]
Thanks for the feedback @mitgiraffe. We're adding to our backlog.
