### ISSUE TITLE
C# 7.0 vs 7.1

### ISSUE THREAD

**Issue by JD-Sp** [dotnet/docs#5366]
Maybe I'm just inexperienced, but it should probably be noted that you have to be running C# 7.1 for this in the pre-requisites. 

I'm running 7, on VS for Mac 7.5, and it gave me a compiler warning about having an asynchronous Main method. Makes sense, but was surprised when I saw the compiler error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to Predict New York Taxi Fares (Regression).](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Hi @JD-Sp, right now the tutorial is only focused on Visual Studio. So if we make the tutorial cross-plat, we should call out the right prerequisites. I assigned this issue to the author.

**Comment by BillWagner** [comment]
@JD-Sp Thanks for pointing this out. It will run on .NET Core 2 from the command line (that has C# 7.1 installed.)

**Comment by pkulikov** [comment]
@mairaw if I create .NET Core console app in Visual Studio (15.7) on Windows, the default C# version is 7.0 (I also have .NET Core 2 installed) 
@BillWagner when I create the .NET Core 2 console app from the command line, that also defaults to C# 7.0.

[Samples code](https://github.com/dotnet/samples/blob/master/machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj) has the language version specified explicitly, which is not default. 

So, it would be nice to specify in [console app creation section](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#create-a-console-application) that C# language version should be updated to C#7.1 at least.

**Comment by JD-Sp** [comment]
@pkulikov Same. I created a version using the CLI tools, and it defaulted to 7. 

I did just go into and manually target 7.1 in the .csproj file, and it works running from the command line. There were a few tweaks to the code to make it cross platform, but all in all i got a good result.

**Comment by mairaw** [comment]
I also noticed that our sample is set to netcoreapp2.1 which won't work with VS 15.6 AFAIK, which is the prereq version that we define on the topics. Should we bump up the VS version prereq or change TargetFramework of our sample in dotnet/samples to 2.0?

**Comment by BillWagner** [comment]
The target framework should change to 2.0. (I built it on my machine where I was doing some preview work at the same time.)

**Comment by mairaw** [comment]
Thanks @BillWagner. I'll make the change then.
