### ISSUE TITLE
XmlElement.InnerText should describe that it removes child nodes

### ISSUE THREAD

**Issue by krwq** [dotnet/docs#5369]
https://msdn.microsoft.com/en-us/library/system.xml.xmlelement.innertext(v=vs.110).aspx should include information that XmlElement.InnerText does remove children nodes when setting the property. Current behavior is slightly confusing as it diverges from msxml which does not remove nodes but .NET does that from at least 2.0 (not tested before)

Description should say something along the lines of “Setting InnerText will not preserve children nodes (the only child node after operation will be a text node set by the property)“

cc: @rpetrusha

**Comment by mairaw** [comment]
Thanks @krwq. We're moving all the MSDN content to docs: https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlelement.innertext. Whenever you see something wrong, feel free to click the Edit button and create a PR for it. I'm adding this work item to the next sprint.
