### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by michaelwatkins** [dotnet/docs#5370]
Thank you for the article.  A brief explanation of each point would be nice!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1da0e3-49e0-8437-5542-7a42682ed8ec
* Version Independent ID: 5e8ba39f-757e-d4cd-7b51-c140303b7283
* Content: [Static Class Design](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/static-class)
* Content Source: [docs/standard/design-guidelines/static-class.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/static-class.md)
* Service: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @michaelwatkins. Given that the content under [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/) is copyrighted, we can't really make edits to it, so I'm closing this issue. The content here is a subset of what's in the actual book, but the book also doesn't go into details of each point. Each point is very straightforward, but let us know if you have any questions about them.

/cc @KrzysztofCwalina
