### ISSUE TITLE
No OS version specified

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/docs#5373]
Does not say what OS versions these instructions apply to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de87ae1b-a8bc-8a30-17f5-411ef9a710e8
* Version Independent ID: af87a5b0-57b8-f3dc-6667-b3f201c0f0b8
* Content: [How to: Enable the Net.TCP Port Sharing Service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-enable-the-net-tcp-port-sharing-service)
* Content Source: [docs/framework/wcf/feature-details/how-to-enable-the-net-tcp-port-sharing-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-enable-the-net-tcp-port-sharing-service.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can you help with this question? Are there any OS requirements for this service?

**Comment by AndyWDev** [comment]
I just thought I would add some more to this.   It appears to me the method of enabling TCP Port Sharing is different on server operating systems than it is desktop clients.   In the server OS, I think the feature has to be installed.  On Windows 10, I believe it is enabled by default, not sure what is required to enable it on Windows 7.

**Comment by zhenlan** [comment]
@AndyWDev might be right, but I don't remember exactly off the top of my head. So basically we need to get answers to the two questions below for the [supported Windows (both client and server) SKUs](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet)

- Is TCP Port Sharing feature installed by default? 
- Is TCP Port Sharing feature enabled by default?

Add @Lxiamail to help.
