### ISSUE TITLE
This is a readonly property

### ISSUE THREAD

**Issue by sebagomez** [dotnet/docs#5377]
"Gets or sets a value that specifies whether to use a simple dictionary format." is not right, because you cannot set the property directly, I came along looking for exactly the way to set the property :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f5356-becf-3699-5d69-37e5002f772f
* Version Independent ID: 9a28ba7d-8da3-ae6c-e3c8-172fe0410673
* Content: [DataContractJsonSerializer.UseSimpleDictionaryFormat Property (System.Runtime.Serialization.Json)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.json.datacontractjsonserializer.usesimpledictionaryformat?view=netframework-4.7.1#System_Runtime_Serialization_Json_DataContractJsonSerializer_UseSimpleDictionaryFormat)
* Content Source: [xml/System.Runtime.Serialization.Json/DataContractJsonSerializer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.Serialization.Json/DataContractJsonSerializer.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @sebagomez. I've opened a PR to fix this.

Also, if you find other issues in the docs, you can still provide the feedback as you did. Or if you'd like, just click the Edit button on the topic and suggest the fix. For more information, see https://docs.microsoft.com/contribute.
