### ISSUE TITLE
Entity SQL rewrite... is it correct?

### ISSUE THREAD

**Issue by siennaA** [dotnet/docs#5378]
If I understood correctly,
T-SQL expression  " sal > all (select salary from employees)" be same as
Entity SQL expression "not exists(select 0 from employees as e where sal > e.salary)"

Shouldn't it be
"not exists(select 0 from employees as e where sal <= e.salary)" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5bcf3e-4c43-d740-818f-3c0584fe9b5a
* Version Independent ID: 57594c85-f414-8ec6-cadf-5865bf46e586
* Content: [Unsupported Expressions (Entity SQL)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/unsupported-expressions-entity-sql)
* Content Source: [docs/framework/data/adonet/ef/language-reference/unsupported-expressions-entity-sql.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/language-reference/unsupported-expressions-entity-sql.md)
* Service: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@douglaslMS can you look at this question?

**Comment by douglaslMS** [comment]
I’ve already forwarded the question to some of my contacts, and I’m hoping to get a response soon.

**Comment by divega** [comment]
@siennaA very good catch! Yes, the condition needs to be inverted for the equivalent of ALL to be correct.
