### ISSUE TITLE
Using ML.net for NLP/NLU 

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/docs#5388]
Hey all, 

What would need to be done to make ML.net do NLP/NLU? We use a python back-end for our current chatbot platform, looking to explore ML.net, because we use .net front-end.

My understanding of what needs to be done is:

Load in a dataset with 2 columns using TextLoader. 

SentenceToBeScored | Intent

Then use a TextFeaturizer to change intents into numeric vectors

Then train and predict. 

Is it that simple? Or am I missing something?

**Comment by mairaw** [comment]
Thanks @atotalnoob. Since this is a product question, I've moved it to https://github.com/dotnet/machinelearning/issues/161.
