### ISSUE TITLE
Move the remarks for asp.net

### ISSUE THREAD

**Issue by swageblock** [dotnet/docs#5389]
It is sort of silly to seperate the ASP.NET limit and the normal limit.  I recommend placing them together.
"The default value is 2." could read "The default connection limit is 10 for ASP.NET hosted applications and 2 for all others."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d78d86da-2cce-f02b-3fd8-2a9af20e1830
* Version Independent ID: bdc8c635-070d-e130-cffe-6c6b24f83aa0
* Content: [ServicePointManager.DefaultConnectionLimit Property (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?view=netframework-4.6.2)
* Content Source: [xml/System.Net/ServicePointManager.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/ServicePointManager.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @swageblock for your feedback. I think it makes sense. I'm adding this item as a community project.
