### ISSUE TITLE
Dealing with errors or failures in stages

### ISSUE THREAD

**Issue by lambdakris** [dotnet/docs#5392]
The guidance around error management and usage of exceptions, result types, option types, and domain types is a good attempt, however, I think it glosses over a key issue, which is how does one form elegant code when errors could happen in stages of computation?

This is particularly prevalent now-a-days when programs often have to call out to other programs (apis, etc), such that each call out of process could yield a result that can indicate failure or success (nevermind an actual exception, which can be propagated).

If the result indicates failure, then you record/log the progress of your computation and terminate or remediate. However, if the result indicates success, you proceed to the next out of process call, and you have to manage the failure/success branch again.

Without language support for early return, and without something like monadic error handling, programs like these typically end up as deeply nested conditional expressions (if/else).

Yes, I suppose it is true that inherently, it is a deeply nested decision tree, but that is not necessarily the friendliest way to represent it language wise, and the resulting code in C# or any language with early return can end up looking more elegant and less burdensome to write (since there is less logic to write), debug (since there is less logic to inspect/consider), and modify (since there is less logic to add or remove).

I also think that if this effort is a serious effort by the language designers and community to offer guidance, then more work needs to be done to address all the ideas developed in fsharpforfunandprofit.com, Domain Modeling Made Functional, FSharp Applied I, FSharp Applied II, and various other training materials out there by claryfing the relationship between those ideas and the ones presented here.

In particular, alot of time and thought and effort has gone into the development around ideas of monadic error handling within F# and if one seriously wants to provide an alternative or qualification to that approach, then one must put a comparable amount of time and thought and effort.

Of course, it goes without saying, but it is not enough to leave it at saying something like "each approach has it's merits" or "each approach is correct in certain situations". That sort of broad qualification leaves one no better off than if one were not to read the guidance at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402e43bd-76b8-a1c8-2c62-e14017f5ed1e
* Version Independent ID: 990e56cd-648d-45c4-30e0-b221874ec329
* Content: [F# coding conventions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions)
* Content Source: [docs/fsharp/style-guide/conventions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/conventions.md)
* Service: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@lambdakris Thanks for the feedback. I agree that there could be more work here in the realm of "how to beautify your error-tolerant code". For example, we suggest using active patterns to pull out useful information from exceptions, but there is no code sample. That could help. Regarding this:

> I also think that if this effort is a serious effort by the language designers and community to offer guidance, then more work needs to be done to address all the ideas developed in fsharpforfunandprofit.com, Domain Modeling Made Functional, FSharp Applied I, FSharp Applied II, and various other training materials out there by claryfing the relationship between those ideas and the ones presented here.
>
> In particular, alot of time and thought and effort has gone into the development around ideas of monadic error handling within F# and if one seriously wants to provide an alternative or qualification to that approach, then one must put a comparable amount of time and thought and effort.

Could you provide some concrete examples? I believe that this article is quite in line with other ideas, particularly in starting out with recommending that you try to represent error cases in your domain such that error handling is a part of regular program flow. Are there some other examples that you think may help in conveying that?

A lot of time has gone into this section. It's not as lengthy as a book or some of Scott's blog posts, but that's very intentional. Original versions of this section were _very_ lengthy, but the key pieces of guidance would get lost in the length. The major difference here is that we take the stance that exceptions _should_ be used in F#, which some people in the F# community disagree with due to them not being functional constructs. I believe we make a solid case for why they are preferable to various alternatives that people conjure up, such as catching and discarding exceptions just to wrap them into a monadic construct.

**Comment by lambdakris** [comment]
I'll work on coming up with more concrete examples of what I mean, but I should probably be sure that I am clear on a couple of things first though. 

To help distinguish between kinds of errors, I would like to borrow some of the terminology from [Domain Modeling Made Functional](https://pragprog.com/book/swdddf/domain-modeling-made-functional) by Scott Wlaschin:

- _Domain Errors_ - Errors to be expected as and dealt with as part of the business process (insufficient funds, out of stock, card declined, invalid inputs, etc)
- _Infrastructure Errors_ - Errors to be expected as part of the system architecture but not dealt with as part of the business process (timeouts, server unreachable/unavailable, etc) 
- _Panics_ - Unexpected errors that leave the system in an unknown state (out of memory, null reference, etc)

I think most developers would admit that Panics and Infrastructure Errors are reasonably dealt with by way of exceptions (the Domain Modeling book makes this point in Ch 10 page 193, 194, and I believe I've seen similar views expressed elsewhere). Where it gets interesting is in dealing with Domain Errors.

Now, what I read between the lines in the guidance is that there are two ways of implementing Domain Errors that are in competition. 

#### Method 1 - a Domain Success type and Domain Failure type wrapped in a Generic Result type

```
type SignupSuccess = UserSignupComplete
type SignupFailure =
    | InvalidUsernameOrPassword
    | UsernameTaken
type SignupResult = Result<SignupSuccess,SignupFailure>
```
...and there are Result combinators and perhaps even a Result CE

#### Method 2 - a Domain Result type with success and failure cases
```
type SignupResult = 
    | UserSignupComplete
    | InvalidUsernameOrPassword
    | UsernameTaken
```

The question then is, which of these two methods is preferred for expressing Domain Errors? The guidance seems to suggest that method 2 is to be preferred and seems to refer to method 1 as monadic error handling. Is this an accurate reading of the guidance so far? 

...or does the guidance have no problem with monadic error handling for Domain Errors and is only warning against the use of monadic error handling for Infrastructure Errors and Panics?

...or does the guidance have no problem with monadic error handling at all and is specifically warning against using strings as the failure case type in a Result type?

**Comment by cmeeren** [comment]
Sorry for off-topic:

> I realize that the elegance of the monadic code depends very much on a healthy lib with combinators and CE and that that is perhaps not quite there with neither Cvmd.ErrorHandling [...]

@lambdakris If you have any ideas, I'll more then gladly take suggestions or discussions at [cmeeren/Cvdm.ErrorHandling/issues](https://github.com/cmeeren/Cvdm.ErrorHandling/issues) :)

</off-topic>

**Comment by mairaw** [comment]
@cartermp can you define a milestone here (even if it's backlog) for this item if there's any action item for you?
