### ISSUE TITLE
Sample Needs updating!

### ISSUE THREAD

**Issue by gregnightingale** [dotnet/docs#5395]
Polly has updated to 6.0.1, now the sample is not working.  ExecutionKey is now OperationKey.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef44bb71-2ee5-bf25-bcd2-1f1eee8b2806
* Version Independent ID: e606a7f8-8097-3b01-b6e8-f6f7f2687ce0
* Content: [Implementing the Circuit Breaker pattern](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/implement-circuit-breaker-pattern)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/implement-circuit-breaker-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/implement-circuit-breaker-pattern.md)
* Service: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by CESARDELATORRE** [comment]
Thanks for the heads-up with Polly. We're already updating the reference application in what's related to Retries with exponential backoff and circuit-breakers ultimately based on Polly.
We're not only updating Polly's version but moving to the new HttpClientFactory available in .NET Core 2.1 RC. This update will be available in the DEV branch next week, probably.
Thanks for the heads-up! 👍

**Comment by mvelosop** [comment]
The update had already been done, but this issue was pending, closing it with upcoming PR.
