### ISSUE TITLE
This did not work for me.  No MaskedTextBox showed up on the window when I ran it. The code link didn't work either ("Hosting a Windows Forms Control in WPF Sample").

### ISSUE THREAD

**Issue by wade56** [dotnet/docs#5397]
This did not work for me.  No MaskedTextBox showed up on the window when I ran it. The code link didn't work either ("Hosting a Windows Forms Control in WPF Sample").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388cd25c-fa98-6cd6-7740-8bbc456b772f
* Version Independent ID: 194b7b3a-110d-93d7-4dad-419c7ad65f52
* Content: [Walkthrough: Hosting a Windows Forms Control in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf#prerequisites)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by wade56** [comment]
I got it to work by using the native Window_Loaded routine rather than the one listed in the example:

Private Sub Window_Loaded(ByVal sender As System.Object, ByVal e As System.Windows.RoutedEventArgs) Handles MyBase.Loaded

instead of:

Private Sub Window_Loaded(ByVal sender As Object, ByVal e As RoutedEventArgs)

**Comment by mairaw** [comment]
I've fixed the link target to go to the right sample. See if that helps.
