### ISSUE TITLE
C# tutorials - arrays

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#54]
Should teach the basic concepts of creating and using arrays in C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by matthewreily** [comment]
I'll take this one as well.  Please assign to me.  cc @BethMassi

**Comment by mairaw** [comment]
Done @matthewreily

**Comment by matthewreily** [comment]
Thanks!
