### ISSUE TITLE
Copy/paste errors in Single docs

### ISSUE THREAD

**Issue by davidmatson** [dotnet/docs#5401]
I think there are a couple of minor typos in the documentation for Single:
https://docs.microsoft.com/en-us/dotnet/api/system.single?view=netframework-4.7

The documentation for Double:
https://docs.microsoft.com/en-us/dotnet/api/system.double?view=netframework-4.7
Contains paragraph very similar to one on the Single side; I think the documentation for Single should be slightly different:

> Note that a loss of precision may result from converting a Single value to another numeric type. In the case of converting non-integral **Double** values, as the output from the example shows, the fractional component is lost when the Single value is either rounded (as in Visual Basic) or truncated (as in C#). For conversions to Decimal and Single values, the Double value may not have a precise representation in the target data type.

For example, I believe the **bolded** word should be Single instead of Double. Also I believe the other highlighted sentence should instead read something like:
> For conversions to Decimal values, the Single value may not have a precise representation as a Decimal value.

Note that converting from Single to Double cannot lose precision, at least if my exhaustive test ([Test Them All](https://randomascii.wordpress.com/2014/01/27/theres-only-four-billion-floatsso-test-them-all/)) was written correctly.

**Comment by davidmatson** [comment]
@rpetrusha (per our offline conversation)

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @davidmatson. We'll address it during this sprint.
