### ISSUE TITLE
Incorrect statement about round-tripping Single in Numeric Format Strings docs

### ISSUE THREAD

**Issue by davidmatson** [dotnet/docs#5402]
I believe there’s a bug in the documentation for [Standard Numeric Format Strings](
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)

Under “General Format Specifier,” it says:

> When used with a Single value, the "G9" format specifier ensures that the original Single value successfully round-trips. This is because Single is an IEEE 754-2008-compliant single-precision (binary32) floating point number that gives up to nine significant digits of precision. We recommend its use instead of the "R" format specifier, **since in some cases "R" fails to successfully round-trip single-precision floating point values**.

I believe the **bolded** statement above is incorrect. I tested on x64 and x32 targeting both .NET 4.5 and .NET 4.7, I think using the code below (takes around an hour to check all ~4 billion values), and it didn’t report any cases where round-tripping failed.

In the docs, I saw test code and an example value for a case where Double with "R" does not round-trip correctly, but not Single, and based on this exhaustive test ([Test Them All](https://randomascii.wordpress.com/2014/01/27/theres-only-four-billion-floatsso-test-them-all/)) I believe no such value exists.

```c#
using System;

public class TestSerializeFloat
{
    static void Main()
    {
        for (uint index = uint.MinValue; index < uint.MaxValue; ++index)
        {
            float value = BinaryCast(index);
            Test(value);
        }

        Test(BinaryCast(uint.MaxValue));

        Console.WriteLine("Done.");
    }

    static unsafe float BinaryCast(uint value)
    {
        void* untypedPointer = &value;
        float* castPointer = (float*)untypedPointer;
        return *castPointer;
    }

    static void Test(float value)
    {
        string serialized = value.ToString("r");
        float roundtripped = float.Parse(serialized);
        if (!value.Equals(roundtripped))
        {
            Console.WriteLine("{0:r} != {1:r}", value, roundtripped);
        }
    }
}
```

**Comment by davidmatson** [comment]
@rpetrusha (per offline conversation)

**Comment by rpetrusha** [comment]
Thanks, @davidmatson. We'll address this issue in the next sprint, which starts next week.
