### ISSUE TITLE
mapName is actually allowed to be null in MemoryMappedFile.CreateNew

### ISSUE THREAD

**Issue by poizan42** [dotnet/docs#5404]
The documentation claims that ArgumentNullException is thrown if mapName is null. This is not true, indeed an anonymous file mapping is successfully created if it is null.

The documentation should preferably actually urge people to use null for mapName if they don't need the name, because they can avoid issues with naming conflicts and potentiel security issues with other processes being able to access the mapping.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 40dc2818-066b-da81-2069-813f28560068
* Version Independent ID: d2d59923-4cff-bc69-26cf-26be49764e07
* Content: [MemoryMappedFile.CreateNew Method (System.IO.MemoryMappedFiles)](https://docs.microsoft.com/da-dk/dotnet/api/system.io.memorymappedfiles.memorymappedfile.createnew?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.IO.MemoryMappedFiles/MemoryMappedFile.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.MemoryMappedFiles/MemoryMappedFile.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @poizan42. The documentation is in fact incorrect, and calls to the CreateNew method do not throw an ArgumentNullException if mapName is null. We'll correct this documentation error during this sprint.
