### ISSUE TITLE
(The term "thread-local" is slightly inaccurate here, because in some cases two partitions may run on the same thread.)

### ISSUE THREAD

**Issue by thucnguyen77** [dotnet/docs#5412]
Can we change it to "partition-local"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f692f5c-4c13-8ba5-d7d8-30102655ade8
* Version Independent ID: 3c4b673c-7056-1a8a-56e9-035307c3b07c
* Content: [How to: Write a Parallel.ForEach Loop with Thread-Local Variables](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-parallel-foreach-loop-with-thread-local-variables)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-parallel-foreach-loop-with-thread-local-variables.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-write-a-parallel-foreach-loop-with-thread-local-variables.md)
* Service: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @thucnguyen77, We're scheduling this for the next sprint.

**Comment by yp0227** [comment]
Console.WriteLine(j + ":" + subtotal);

By adding this log I can see subtotal seems cross the threads, why it's marked as "thread-local"?
