### ISSUE TITLE
Remarks section: GetEmptyWebProxy

### ISSUE THREAD

**Issue by lostllama** [dotnet/docs#5413]
Following the link for this method to the class it belongs to, shows that the class is now obsolete. It seems this documentation is out of date.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcec156a-14b3-a8e6-9c3e-bc87fa39da4c
* Version Independent ID: d6bc60c4-6da0-e151-2b46-b6a14a118a50
* Content: [WebClient.Proxy Property (System.Net)](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webclient.proxy?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Net/WebClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/WebClient.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @lostllama, for pointing out that the documentation is in need of revision.  The warning message generated by the compiler for calls to the GlobalProxySelection.GetEmptyWebProxy method indicates that `null` should be assigned to the Proxy property. We'll update the documentation to reflect that.
