### ISSUE TITLE
Misleading information

### ISSUE THREAD

**Issue by TNwestpointtg** [dotnet/docs#5414]
The section highlighted in the attached should say in the left most column that the connection will occur regardless of if there is a valid security server present?

![microsoft info wrong](https://user-images.githubusercontent.com/38466058/40110632-65e124d6-58f8-11e8-8747-571ce0328c6a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b43aee8-d88f-ea0d-5f19-e8ea155d1b7a
* Version Independent ID: 1fcc3a93-690c-cdf1-5ff9-70406bf06e33
* Content: [Connection String Syntax](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax)
* Content Source: [docs/framework/data/adonet/connection-string-syntax.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-string-syntax.md)
* Service: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@TNwestpointtg Can I just clarify that you mean the rightmost column, and not the leftmost? And you believe it should say "server present" and not "certificate present?" I'll have to double-check on this.

**Comment by douglaslMS** [comment]
#in-progress

**Comment by TNwestpointtg** [comment]
Yes the right column. My understanding is everything even is the certificate is installed but invalid (wrong hostname) the trust server certificate option should mean the connection works. It might just need clearing up as the same statement for all examples is confusing

**Comment by douglaslMS** [comment]
@TNwestpointtg I'm talking to my ADO.NET product team contacts to confirm the precise language to use for this case, to make sure we get it right on the first try.

**Comment by douglaslMS** [comment]
Discussing the updates needed with the ADO.Net product team. Waiting to verify some details.

**Comment by douglaslMS** [comment]
@TNwestpointtg Thanks for bringing this issue to our attention. In fact, there was more than  one row in the table where the Result column needed to be fixed. I've just pushed those changes. You can compare the fixed version to the table here: [Using Encryption Without Validation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-encryption-without-validation?view=sql-server-2017).
