### ISSUE TITLE
 throw new System.ArgumentOutOfRangeException("index parameter is out of range.", e);

### ISSUE THREAD

**Issue by evilprince2009** [dotnet/docs#5415]
Whats the purpose of throw keyword here inside the catch block ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9740955a-7141-c540-ecd8-1d3762957797
* Version Independent ID: 2f0d458c-6545-125b-0308-4ffb1cdd0a46
* Content: [How to: Handle an Exception Using try-catch (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/how-to-handle-an-exception-using-try-catch)
* Content Source: [docs/csharp/programming-guide/exceptions/how-to-handle-an-exception-using-try-catch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/how-to-handle-an-exception-using-try-catch.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Mackiovello** [comment]
It's explained right below in the explanation:

> The catch block handles the IndexOutOfRangeException and throws the more appropriate ArgumentOutOfRangeException exception instead. In order to provide the caller with as much information as possible, consider specifying the original exception as the InnerException of the new exception.

**Comment by rpetrusha** [comment]
Closing, since the explanation given in the documentation is adequate. If you disagree, @evilprince2009. please respond in this issue.
