### ISSUE TITLE
Copyright character

### ISSUE THREAD

**Issue by redcurry** [dotnet/docs#5417]
It's also possible to use "&#x24b8;" for the copyright symbol, but it's a bit bigger than using "©" directly. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c7a458-13d5-2dcd-191f-d3ddf4e81d98
* Version Independent ID: 6209ba03-0cd9-35f7-341d-397c1cbbea82
* Content: [How to: Use Special Characters in XAML](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-use-special-characters-in-xaml)
* Content Source: [docs/framework/wpf/advanced/how-to-use-special-characters-in-xaml.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-use-special-characters-in-xaml.md)
* Service: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @svick for jumping in and helping with this question. I'll close this issue then.
