### ISSUE TITLE
Table missing

### ISSUE THREAD

**Issue by TanielianVB** [dotnet/docs#5419]
After this text there's no table: "The following table lists the valid names for keyword values within the ConnectionString."
The table exists in the old article: https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dbe2d02-339d-30f3-c267-cd5962abc4e4
* Version Independent ID: aa71bfe8-76a9-69d9-18d4-b5c22f7f8843
* Content: [SqlConnection.ConnectionString Property (System.Data.SqlClient)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.7.1#System_Data_SqlClient_SqlConnection_ConnectionString)
* Content Source: [xml/System.Data.SqlClient/SqlConnection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlConnection.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for bringing this to our attention @TanielianVB! I'll check with our engineering team on what might have happened during the content migration.

FYI @wh-alice @yishengjin1413

**Comment by mairaw** [comment]
Opened internal bug to track this: #1263173

**Comment by scsfdev** [comment]
2 months later, still no update on this documentation. 
I also wonder around to look for the table till I see TanielianVB comment and notice old page still have the table for the details explanation.

**Comment by mairaw** [comment]
@scsfdev I apologize this issue hasn't been fixed yet. We'll attempt to fix it this sprint. We're trying to evaluate whether there are other pages affected at the same time. It was an issue with the migration tool.
