### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by thetylerb** [dotnet/docs#5424]
Overall great stuff. I'd like to see an example for accessing attribute metadata via reflection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adab8285-18b5-04e4-1070-6edf45b5b5db
* Version Independent ID: 395b4146-4601-558d-c94d-4997879f74d5
* Content: [C# Attributes - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/attributes)
* Content Source: [docs/csharp/tour-of-csharp/attributes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/attributes.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for the compliment as well as the suggestion, @thetylerb. The topic could definitely use an example that shows how to access attributes using reflection. In the meantime, you can see examples that access custom attributes in the [MemberInfo.GetCustomAttributes method](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.getcustomattributes?view=netframework-4.7.2) documentation.

**Comment by sputier** [comment]
I take a look at this issue !
