### ISSUE TITLE
docs/docs/framework/tools/index.md  VSDownloads link is dead

### ISSUE THREAD

**Issue by bciesielski** [dotnet/docs#5430]
docs/docs/framework/tools/index.md

Visual Studio Downloads link is dead

**Comment by mairaw** [comment]
Hi @bciesielski, can you tell me where do you see that link?

**Comment by mairaw** [comment]
Never mind. @rpetrusha helped me find the broken link. I've opened a PR to fix this. Thanks for reporting!

**Comment by bciesielski** [comment]
Ok, no problem ! 👍
