### ISSUE TITLE
New content: tutorial on using C# Tuples

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#5432]
There are a lot of good uses for tuples and deconstruction that create more readable and concise code.  Consider:

1. constructors that assign multiple fields.
1. Assignment operators
1. Equality tests
1. GetHashCode implementations

There are likely others. This would show a few samples of the different techniques, and explain the pros and cons of each choice.

See [#5390 - comment](https://github.com/dotnet/docs/pull/5390#discussion_r188473443) for discussion, and the start of a sample.

**Comment by BillWagner** [comment]
/cc @rpetrusha for your thoughts.

I'm re-thinking this as a tutorial.  Looking at the list of use cases, I think a tutorial would be more of a grab-bag of tips. 

Instead, I think handling these use cases as part of #8206, making the "what's new" articles interactive with an "explore" article to try the features in different scenarios.

**Comment by rpetrusha** [comment]
I don't really see use cases as particularly good tutorial material, so I agree with your decision to not make them tutorials. I also think that they would benefit from interactivity. But I don't see them as related to what's new -- I think that they require separate branding. Often, Developers learning new features are typically concerned with the basics of the feature and at most a few practical applications, Following that, use cases expand the use of the feature into new areas. So this is clearly an advanced topic. It's also one that I think will be really valuable. Perhaps something like an **Applying** series (Applying tuples) that focuses on how tuples (or some other feature) can be used in practical ways in application development?

**Comment by BillWagner** [comment]
I really like that idea @rpetrusha I've added that to my notes on validating the updated C# Guide TOC.

In the short term, I'll add these into the "what's new" section.  

I can also see a future where older "what's new" content moves into an "applying" section.  (Just thinking out loud on that one).
