### ISSUE TITLE
Updating the book content for .net core 2.1

### ISSUE THREAD

**Issue by hemantsathe** [dotnet/docs#5437]
Please update the contents of the book for .net core 2.1 as there are many new additions on technology stack.

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 9cc14513-c458-d615-9615-7003c614b7cd
* Content: [.NET Microservices. Architecture for Containerized .NET Applications](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/)
* Content Source: [docs/standard/microservices-architecture/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/index.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out.  PR #5411 has the changes you want. We're reviewing it now.

**Comment by mairaw** [comment]
And I believe there are more content updates coming. @CESARDELATORRE please take a look.

**Comment by mairaw** [comment]
@CESARDELATORRE please close this once you're done with all the 2.1 updates.

**Comment by mvelosop** [comment]
The [pdf eBook](https://aka.ms/microservicesebook) update was just updated a few days ago, just starting the process of updating in docs.microsoft.com.
