### ISSUE TITLE
"Run" feature displays erroneous results!

### ISSUE THREAD

**Issue by dmackersie** [dotnet/docs#5440]
The "Run" feature is cool, but some of the results appear different than the expected results shown in the comments!
1. Leading spaces in the first line of output appear to be stripped, resulting in alignment issues.
2. Currency symbol isn't displayed correctly.
3. DateTime "d" format gets displayed as "MM/d/yyyy" instead of "M/d/yyyy" as I would expect for en-US.

Also, DateTime.Now doesn't retrieve the current Date unless I change the example some - looks like previous runs are being cached. Also, seems to be a different timezone, but that I guess I can understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e3beef-53d2-b35c-e183-08a1650d1dab
* Version Independent ID: 04976819-623e-2674-93b2-536395fd2732
* Content: [String.Format Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2#controlling-spacing)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by dmackersie** [comment]
Confirmed that the Run feature seems to be running in invariant culture. Adding the following lines of code to the start of the DateTime and Currency examples fixes those formatting issues:

```
using System.Globalization;
CultureInfo.CurrentCulture = new CultureInfo("en-US");
```

**Comment by rpetrusha** [comment]
Your're correct, @dmackersie, that the current culture for the sample environment is the invariant culture. Eventually, the current culture will be the defined by the culture reported by the user's browser, but the work to do that hasn't been completed.

//cc @LadyNaggaga

**Comment by rpetrusha** [comment]
Incidentally, @dmackersie, the C# examples now run in the context of the current culture. This change addresses some of the issues you reported, like unexpected date and time formatting and an incorrect currency symbol.

**Comment by pkulikov** [comment]
> 1. Leading spaces in the first line of output appear to be stripped, resulting in alignment issues.

This issue is also fixed.

**Comment by mairaw** [comment]
I'm closing this since this culture issue is being tracked by https://github.com/dotnet/try/issues/168.
