### ISSUE TITLE
Object by reference

### ISSUE THREAD

**Issue by MSABHelsing** [dotnet/docs#5443]
I am completely new to WCF and are looking into migrating some DCOM code. I am trying to understand the "The service returns an object by reference" example.

The intention in the example seems to be to create an instance of SessionBoundObject in the GetInstanceAddress method on the server side and send the address of that object back to the client. But it doesn't seem to do that. When sessionBoundObjectFactory.CreateChannel() is called on the client a new instance of SessionBoundObject is created each time.

Is the example wrong or is it just me misunderstanding how it is supposed to work? In either case I think the example is unclear what it is actually supposed to do.

In my case I basically need to port DCOM interfaces that looks like the following:

public interface IRemoteService  
{  
    IRemoteObject GetObjectByReference(uint id);  
}

where the IRemoteObject is instantiated on the server side differently depending on the value of the id parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b840d57e-38e2-e701-536e-5963fd9651b8
* Version Independent ID: cf8c443f-7673-d7ea-28a0-ae7db5b1bf65
* Content: [How to: Migrate Managed-Code DCOM to WCF](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-migrate-managed-code-dcom-to-wcf)
* Content Source: [docs/framework/interop/how-to-migrate-managed-code-dcom-to-wcf.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/how-to-migrate-managed-code-dcom-to-wcf.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@zhenlan can you or your team help with this question?

**Comment by zhenlan** [comment]
@mconnew can you help to clarify?

cc: @Lxiamail

**Comment by mconnew** [comment]
@reinfallt, I'm going to help the best I can but your question is lacking some details required to give you a full answer. The article is using an unusual way of basically returning a URL for the client to use to connect to the service. There are multiple ways you could achieve what you are looking for but it would depend on how you implement the call dispatch on the server side. When you call `IRemoteService.GetObjectByReference(id)`, you will get some information come back which will allow you to create a channel to the service and make calls to the object you want. The return type of that method you listed as IRemoteObject. If your remote objects are to be the actual service instances, you either need to have a common base class and use an IInstanceContextProvider to create an instance of the derived type based on some headers passed, or you will need a full ServiceHost for each type. If you are okay having a delegating proxy service, then you could read the incoming message header to obtain the information about which service instance you are using and retrieve the instance from some collection and make the calls through to the actual instance. This will require you to manage the lifetime yourself.  
There are a couple of ways to pass the information that is returned by `GetObjectByReference` through to the service call. In the example, an endpoint address is serialized and returned to the client. You could use an `EndpointAddressBuilder` and add an `AddressHeader` with this information, create the `EndpointAddress` and return an instance of `EndpointAddress10`. Then on the server side you can retrieve the extra address header and use whatever instantiating model you are using.  
You could also pass the information over using session context. For example, you can use NetTcpContextBinding, create a channel, get the `IContextManager` from the channel properties, disable the manager and add the information as context. You would then get this information from the ContextMessageProperty contained in the incoming message properties.  
Sorry the response is a bit vague, but I could write a whole series of blog post articles based on the question you asked using different instancing models for each article. I would need more information to give a more concrete recommendation.

**Comment by BillWagner** [comment]
@reinfallt Does the above answer help? Do you need more updates?

**Comment by reinfallt** [comment]
It definitely helps. I just haven't had time to look into it any further.
