### ISSUE TITLE
Move F# VS docs over to the Visual Studio documentation repo

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#5447]
The following articles:

* https://docs.microsoft.com/dotnet/fsharp/using-fsharp-in-visual-studio/visual-fsharp-development-environment-features
* https://docs.microsoft.com/dotnet/fsharp/using-fsharp-in-visual-studio/configuring-projects
* https://docs.microsoft.com/en-us/dotnet/fsharp/using-fsharp-in-visual-studio/targeting-older-versions-of-net

Are not really about F#, they are about F# support in VS. The last one should probably just be removed altogether.

Should these move to the VS docs?

**Comment by gewarren** [comment]
@mairaw @cartermp yes I think those 2 (or 3) should be moved to the VS docs. Do you agree Maira? I will create a task for myself if so.

**Comment by mairaw** [comment]
I'm fine with that. I think the last especially needs some work. So you might have to work with @cartermp to update that one.

**Comment by BillWagner** [comment]
We likely have similar concerns for VB.NET and C#.  We should be consistent in how we handle all three .NET managed languages.

**Comment by gewarren** [comment]
@BillWagner Do you mean similar concerns about .NET Framework 3.5 support, or about topics on VS tooling for the language living in the dotnet repo?

@terryglee also suggested that because F# is open source, the docs need to be on an open source repo. Thoughts?

**Comment by cartermp** [comment]
All three languages are OSS, so all documentation for them should be OSS as well. I thought the VS docs were OSS?

**Comment by gewarren** [comment]
The VS docs use the public-private repo system. The actual published content comes from the private repo. But it's all mirrored to the public repo. So I'm not sure if you consider that OSS.

**Comment by mairaw** [comment]
But that would mean you could not have any content covering OSS technologies in the VS docs, which seems wrong. C#, VB, .NET Core. and Roslyn, for example, are all open-source technologies covered in the VS docs too, no?

**Comment by gewarren** [comment]
Yes that is true Maira. So I think we are good here.

I'll look at moving these topics in the next sprint (138).

**Comment by mairaw** [comment]
We're currently in 136, so next one would be 137. So should I set this to 137 or 138?

**Comment by gewarren** [comment]
Sorry, that was confusing. It's for 138.

**Comment by BillWagner** [comment]
> Do you mean similar concerns about .NET Framework 3.5 support, or about topics on VS tooling for the language living in the dotnet repo?

There are "get started" topics xrefed for C# in the .NET Core guide that are heavily Visual Studio focused: 

https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio
https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio

And, xrefed for VB guide: 
https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-with-visual-studio
https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio

**Comment by gewarren** [comment]
Yes we may want to think through this more. Jeff Gao is driving an effort to move language-specific topics out of the VS docs now, and have more language-agnostic topics possibly using conceptual tabs.

**Comment by cartermp** [comment]
Where would the Visual Studio-tooling and also language-specific documentation live under this model? At least in the case of this issue, these articles are about F# tooling in Visual Studio.

**Comment by gewarren** [comment]
Topics have been ported in this PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/2459

**Comment by cartermp** [comment]
Thanks! I'll follow up with a PR to here that removes articles from this doc set and redirects to the VS docs.

**Comment by gewarren** [comment]
@cartermp Sounds good. You might also want to link to the VS F# docs from one or more of the dotnet F# docs.

**Comment by gewarren** [comment]
The VS PR is merged to master. The topics will be live in about an hour.

**Comment by cartermp** [comment]
Thanks! I'll kick off the relevant PRs here.
