### ISSUE TITLE
Integrate notebook for F#

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#5450]
It's awesome that F# is supported on Jupyter notebooks. It could be really beneficial to integrate that into the F# guide (maybe even create the whole guide as a notebook) in order to enable people to run the examples in the browser. 
This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/71

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963bfd29-ec31-ee78-ce44-56960ff0ff09
* Version Independent ID: 5a8d0fd9-c3ea-88c8-0437-7c3b8779271f
* Content: [F# Guide](https://docs.microsoft.com/en-us/dotnet/fsharp/)
* Content Source: [docs/fsharp/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/index.md)
* Service: **unspecified**
* Product: **dotnet-fsharp**
* GitHub Login: @jackfoxy
* Microsoft Alias: **phcart**

**Comment by mairaw** [comment]
Tagging @cartermp to take a look.

**Comment by svick** [comment]
Wouldn't it make more sense to add support for F# to Try.NET?

**Comment by mairaw** [comment]
Oh yes! Tagging @LadyNaggaga since she's driving that the Try.NET experience.

**Comment by cartermp** [comment]
Not sure if this repo is the appropriate place for the feature request, since there isn't anything we can do from a content perspective aside from mention F# on Azure Notebooks as another option to try F#. I can add that link here: https://docs.microsoft.com/en-us/dotnet/fsharp/#learning-f

**Comment by cartermp** [comment]
Yep, good to close.
