### ISSUE TITLE
Install a template from a MyGet feed?

### ISSUE THREAD

**Issue by dahlsailrunner** [dotnet/docs#5455]
I was wondering if it's possible to install a new template from a MyGet feed directly with something like "dotnet new -i MyTemplatePack -Source https://mygetfeed/index.json" or something like that.  

I can manually download the template and then install it from the file system, but was hoping to avoid the step.  

Thanks.  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/custom-templates.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@livarcocc @KathleenDollard can you comment on this?

**Comment by livarcocc** [comment]
I think the parameter name is `--nuget-source`.

**Comment by mairaw** [comment]
Ah, you're right @livarcocc. I haven't documented the 2.1.300 SDK options yet, so this is new in 2.1.
