### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by Juraj2** [dotnet/docs#5457]
In Supported .NET implementations sections I see .NET Standard 2.0 is supported by .NET Framework 4.6.1 or later. However on https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies the .NET 4.7.1 has comment that Support for .NET Standard 2.0 was added. Is there a typo in the document? Or do you mean a general support so that it is possible to run .NET Standard 2.0 on .NET 4.6.1 - but .NET Core 2.0 SDK needs to be installed though. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de130a75-fed2-0567-6e3d-07a384900eec
* Version Independent ID: a2993c26-93f8-7281-d6ca-5fcc899e95f3
* Content: [What's new in the .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp#feedback)
* Content Source: [docs/standard/whats-new/whats-new-in-dotnet-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/whats-new/whats-new-in-dotnet-standard.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
No, that's not a typo. .Net Framework 4.6.1 does support .Net Standard 2.0, but .Net Framework 4.7.1 improved that support. For more information, see https://github.com/dotnet/standard/issues/514.

**Comment by BillWagner** [comment]
As @svick has commented, this isn't a typo, and the docs are correct.  Closing this.

**Comment by mairaw** [comment]
I'm reopening this. I think we should add the work built-in to that topic as @terrajobst points out in the issue.

**Comment by terrajobst** [comment]
Agreed. The key is that with .NET Framework 4.7.1, the .NET Standard 2.0 support is built-into the framework.
