### ISSUE TITLE
specifying multiple files is documented wrong?

### ISSUE THREAD

**Issue by ArntWork** [dotnet/docs#5459]
Looking at this https://social.msdn.microsoft.com/Forums/vstudio/en-US/552e54a5-72f8-477a-85ca-98877b3e9144/sign-multiple-files?forum=vsx I can see where the confusion in that thread started:
"signtool [command] [options] [file_name | ...] "
Looking at the last bit, why is there a | after filename? It doesn't seem to make sense no matter what style of showing options you follow. [] means optional, ... might mean 'more than 1', so this says you have to put in a filename followed by a | more than once. Or | might mean 'or', which then means you have to put in a filename or '...'? (Also, why the [] around the filename? I don't think it is ever optional? Every single sample has one.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a4dbac-a145-e79f-121d-3d8df67552b1
* Version Independent ID: 9ea61916-a9db-f23e-4c43-edc06650483d
* Content: [SignTool.exe (Sign Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe)
* Content Source: [docs/framework/tools/signtool-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/signtool-exe.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for reporting this @ArntWork 

We've added this to our backlog, and we'll schedule it in one of our upcoming sprints.
