### ISSUE TITLE
Missing PowerShell example

### ISSUE THREAD

**Issue by cvollmann** [dotnet/docs#5460]
Please add a PowerShell example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433b4c70-07c8-34c3-b567-22c80b71c5e2
* Version Independent ID: e3699917-899c-85fd-44f2-942b317cb8ff
* Content: [How to: Install and Uninstall Services](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-install-and-uninstall-services)
* Content Source: [docs/framework/windows-services/how-to-install-and-uninstall-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/how-to-install-and-uninstall-services.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for reporting this @cvollmann 

We've added it to our backlog, and we'll add a Powershell sample as we update these docs.

I've also added the **up-for-grabs** label, and added it to our community project. We've had some community members with an interest in powershell add examples in this area.

**Comment by iBobb** [comment]
The PowerShell example doesn't work unless you have PowerShell 6
