### ISSUE TITLE
ArgumentException adding existing ServiceMetadataBehavior

### ISSUE THREAD

**Issue by jho1965us** [dotnet/docs#5461]
if the Find<ServiceMetadataBehavior>() call return a non-null value I get an ArgumentException in the line:
svcHost.Description.Behaviors.Add(smb);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf2e7c5-e1ff-bff3-1ab9-18b968b5860d
* Version Independent ID: 889e0c49-7c7a-e6f8-562a-4cc0be353bb7
* Content: [How to: Publish Metadata for a Service Using Code](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-publish-metadata-for-a-service-using-code)
* Content Source: [docs/framework/wcf/feature-details/how-to-publish-metadata-for-a-service-using-code.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-publish-metadata-for-a-service-using-code.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for reporting this @jho1965us 

I think everything through step 7 should be in the `if` class on the test of `if (smb == null)`, but I haven't verified that yet.
