### ISSUE TITLE
Interpolation quickstart

### ISSUE THREAD

**Issue by sheilabates157** [dotnet/docs#5462]
There's a pretty big jump between the previous quickstart and this quickstart. You've introduced concepts without explaining them - like "public". I honestly thought that I had missed some sections between the previous qs and this qs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c237cc-f595-dc78-f09a-fd1c688fe3e2
* Version Independent ID: 0d74beea-afdb-89d3-9d86-54cbdd37d977
* Content: [String interpolation interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/quick-starts/interpolated-strings.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/interpolated-strings.yml)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the feedback @sheilabates157 

I'll look at adding a new quickstart to fill those gaps, or rearranging them in a different order.

**Comment by pkulikov** [comment]
@sheilabates157 are there any other terms or concepts in the quickstart that are confusing? Are they blocking to go through the quickstart? Would a mere link to the language reference (for example, to [public keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/public)) be already helpful? Any answers can help to improve the topic and are much appreciated. 

@BillWagner there is the [Introduction to classes](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/introduction-to-classes) quickstart that might be helpful. However it's not interactive.

**Comment by sheilabates157** [comment]
Petr,
              A link would helpful.  Maybe the concept of custom data types and the properties is a little complex for me.  I will do some further research on my own.

Thanks,
Sheila

**Comment by BillWagner** [comment]
Closing this.

When I updated the Quickstarts and interactive tutorials, this moved into a different section.
