### ISSUE TITLE
ML.NET

### ISSUE THREAD

**Issue by Jahanaray** [dotnet/docs#5463]
thanks for ML.NET,
but this tutorial and documentation is really disappointing!!! We need better documentation ASAP!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@Jahanaray what disappoints you the most in the current documentation on ML.NET? Level of tutorials, its number and variety?

**Comment by mairaw** [comment]
Also, this product is on a very early preview state, so we're still building out the documentation for it. Let us know what you'd like to see more. 

/cc @aditidugar

**Comment by andreireiand** [comment]
Would be great to see some recursive neural networks examples. I'd phrase it a bit different than Jahanaray - not disappointment but work in progress ... and indeed multiple things missing:
1) Clear usage guidelines not only for one class / use-case but many
2) Clear project examples with real world applications for say, time series analysis
3) Emphasis on advantages of keep using ML.NET library and not jumping into a Matlab console ... 

You guys want a good DOCs example on a ML Library? Look at the Mathworks ML Docs:
https://uk.mathworks.com/solutions/machine-learning.html
https://uk.mathworks.com/discovery/deep-learning.html

thanks

**Comment by cissemy** [comment]
Hi,
Can you add image and text recognition, barcode scanning just like firebase ML kit ?

**Comment by JRAlexander** [comment]
Closing this as I believe its resolved. Please reopen if that is not the case. Thanks!
