### ISSUE TITLE
Example of hosting imperative code (code-only) via IIS (all configuration in Web.config only) needed.

### ISSUE THREAD

**Issue by IKoshelev** [dotnet/docs#5475]
I can't seem to find anywhere an example of hosting imperative code workflow as a WCF service in IIS (when service is configured and started via Web.config only). This is a major functionality, needed by my current team, that seems to be there, but we just can't launch our code. Can someone please provide a tutorial on it, or at least point me to a working example?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e78682c-42f2-0420-d37d-789bde9b2ebf
* Version Independent ID: 2f7468eb-caea-e628-d30c-5dadd853a0b1
* Content: [Hosting Workflows](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/hosting-workflows)
* Content Source: [docs/framework/windows-workflow-foundation/hosting-workflows.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/hosting-workflows.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by IKoshelev** [comment]
I've gathered information from different tutorials and made a minimalistic project demonstrating how to create a code-only windows workflow and host it as WCF service https://github.com/IKoshelev/worfkflow-codeonly-hosted-sample

**Comment by mairaw** [comment]
It seems you managed to get an example working, correct @IKoshelev?

**Comment by IKoshelev** [comment]
Yes, i've managed to get sample project working (link above) and later used the same way in my job project.

**Comment by mairaw** [comment]
Ok to close this @IKoshelev?

**Comment by IKoshelev** [comment]
I believe so. Hopefully, anyone looking for an example will find this issue or repo directly.
