### ISSUE TITLE
Erroneous accessor descriptions

### ISSUE THREAD

**Issue by GRXoft** [dotnet/docs#5483]
In the [Defining Your Own Attached Events as Routed Events](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/attached-events-overview#defining-your-own-attached-events-as-routed-events) section descriptions of both *Add\*Handler* and *Remove\*Handler* accessors are wrong. Namely, they state that the first parameter should identify the event, when really the first parameter should identify the object for which the handler is registered/unregistered. This is clearly visible in the subsequent code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e014c15-1f90-6e9e-a439-15183a118a8a
* Version Independent ID: 6a0e7d9e-b9b9-6993-24b3-1fc88eea8868
* Content: [Attached Events Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/attached-events-overview#defining-your-own-attached-events-as-routed-events)
* Content Source: [docs/framework/wpf/advanced/attached-events-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/attached-events-overview.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@sambent can you please take a look at this request?

**Comment by thomasclaudiushuber** [comment]
@mairaw: The request is correct, the docs are wrong. :) 

The docs want to describe the methods AddEventNameHandler and RemoveEventNameHandler that a developer should add to implement their own Routed Event. But the description for these two methods matches the methods AddHandler and RemoveHandler from UIElement that are given by the framework. I'll adjust it and send a PR.
