### ISSUE TITLE
MyEndpointBehavior()

### ISSUE THREAD

**Issue by Dijenek91** [dotnet/docs#5484]
Please explain and add additional information how to create our own EndpointBehavior.

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6133901-f087-25a1-77e6-ab37e2d1bcf6
* Version Independent ID: dcf239d3-4a85-00ed-b8ad-8f9a8e8ac983
* Content: [Configuring WCF Services in Code](https://docs.microsoft.com/en-us/dotnet/framework/wcf/configuring-wcf-services-in-code)
* Content Source: [docs/framework/wcf/configuring-wcf-services-in-code.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/configuring-wcf-services-in-code.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can you please comment on this request?

**Comment by zhenlan** [comment]
Add @Lxiamail to help.

**Comment by crowcoder** [comment]
@Dijenek91 did you ever get this worked out? Do you remember what you did? Thanks.

**Comment by crowcoder** [comment]
I got it to work with a different overload of AddServiceEndpoint()

var cd = new ContractDescription("IYourService");
var EndpointAddr = new EndpointAddress("https://blah, blah, etc");
var bhb = new BasicHttpBinding();
bhb.Security = new BasicHttpSecurity { Mode = BasicHttpSecurityMode.Transport };
ServiceEndpoint ep = new ServiceEndpoint(cd, new BasicHttpBinding(), EndpointAddr);
config.AddServiceEndpoint(typeof(IYourService), bhb, addr);

**Comment by yandoldonov** [comment]
still nothing on constructing an instance of IEndpointBehavior object which new MyEndpointBehavior() is supposed to be...???

**Comment by yandoldonov** [comment]
this might be helpful as a starting point
https://wcfpro.wordpress.com/2011/04/30/iendpointbehaviorhow-to-add-behavior-on-a-specific-endpoint/

https://wcfpro.wordpress.com/2011/03/29/iclientmessageinspector/
