### ISSUE TITLE
Document behavior when specified SDK version in global.json is not available

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs#5486]
What happens if the specified SDK version in global.json is not found? Will it use a newer version if available? Is it an error if the specified version is not found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json reference](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @danroth27. This is being addressed by PR #4704 that I hope to merge this week. Let me know if that doesn’t answer the question.

**Comment by KathleenDollard** [comment]
We now have docs for this in the global.json reference that I just reviewed. I think we should move it here.
