### ISSUE TITLE
I use the method mentioned in the example of this page  to check the connection status of a socket, but i does not behavior well. 

### ISSUE THREAD

**Issue by BiggerChina** [dotnet/docs#5489]
I use the method mentioned in the example of this page  to check the connection status of a socket on server side, but i does not behavior well. 

my test client was closed , but the server cannot found it.  

use the 

remoteSocket.Send(new byte[0],0,0) ;
always return 0, and no throw exception
and then I check the Connected Property , it is true.

but ,my client  app was closed!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a0dc24-03d1-aa57-f04d-177457350f6e
* Version Independent ID: 7d856cf8-3ef6-828d-01a3-ab45ceb06e76
* Content: [Socket.Connected Property (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.connected?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/Socket.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/Socket.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@karelz @davidsh any suggestions here? @BiggerChina do you have perhaps a small sample we could try to repro the issue you're seeing?

**Comment by karelz** [comment]
Repro would help. Also check that your client's close is delivered to the server (check Fiddler/Wireshark network traces).

**Comment by BiggerChina** [comment]
my client app is an console app , i connected to server,then send a message, and paused on console.readline();   then  i close it manually.

so it did not notice the server about its close.

**Comment by BiggerChina** [comment]
I just started learning socket  programming , may be i misunderstand the procedure of communication .

is there any method to find the closed socket in this close mode? 

many thanks!
