### ISSUE TITLE
No exception information

### ISSUE THREAD

**Issue by jinek** [dotnet/docs#5492]
At least ArgumentNullException will be thrown if null is passed as reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf82ac6-ac7b-8e3c-ff1f-d3c561df0296
* Version Independent ID: 948a5d42-3692-1fec-ef18-07e8d2f4ebb5
* Content: [VisualTreeHelper.GetParent(DependencyObject) Method (System.Windows.Media)](https://docs.microsoft.com/en-us/dotnet/api/System.Windows.Media.VisualTreeHelper.GetParent?view=netframework-4.7)
* Content Source: [xml/System.Windows.Media/VisualTreeHelper.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Media/VisualTreeHelper.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @jinek. The method throws two exceptions:
- An ArgumentNullException, if `reference` is `null`.
- InvalidOperationException, if `reference` is not a visual object.
We'll update the documentation to reflect this exception information.
