### ISSUE TITLE
TextLoader code line giving me exception

### ISSUE THREAD

**Issue by Sumeetgaara** [dotnet/docs#5502]
I followed this tutorial(Tutorial: Use ML.NET to Predict New York Taxi Fares (Regression)).I changed data from dataset,changed classes and their fields according to data and kept the same format(.csv).But when my code goes to Textloader code line from tutorial , it breaks with an exception.

Code line:
`pipeline.Add(new TextLoader<myclassname>(DataPath, useHeader: true, separator: ","));`
Exception message:
Type not implemented or supported.

I checked prerequisites and all are properly configured on my system.Anything else I need to check or am I missing something?any info on this would be great help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to Predict New York Taxi Fares (Regression).](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by jusso-dev** [comment]
Share what 'myclassname' looks like?

**Comment by jusso-dev** [comment]
I don't think intergers are supported, change your class types to floats

**Comment by aditidugar** [comment]
Hi @Sumeetgaara, @jusso-dev is correct. Integers are currently not supported, and so changing types to floats should solve your issue. Please let us know if you are still having trouble!

**Comment by Sumeetgaara** [comment]
Issue is gone now.Thanks guys.
