### ISSUE TITLE
It is not good to change the delimiter for PackageTags

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5505]
:-1: This was a bad idea. Why shift from *space delimited* to *semi-colon delimited*? Makes for more painful conversion from ``.nuspec`` to project driven packaging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@rohit21agrawal can you comment on this?

**Comment by mairaw** [comment]
@livarcocc @KathleenDollard any suggestions on who to ping on this feedback?

**Comment by rohit21agrawal** [comment]
when we moved certain properties to msbuild, we decided to use msbuild conventions as much as possible, without introducing our own. We realize it may confuse some people, but the existing delimiter for nuspec is still valid and the csproj based PackageTags will use the msbuild based delimiter - ```;```

**Comment by livarcocc** [comment]
I agree, the delimiter is expected and common place for folks using and used to msbuild. I believe this was the right call.

**Comment by mairaw** [comment]
Thanks @rohit21agrawal and @livarcocc. I'll close this issue then.
