### ISSUE TITLE
FAQ link is broken

### ISSUE THREAD

**Issue by daniel-zazula** [dotnet/docs#5512]
The link to the FAQ at the end of the article is broken and just takes you back to the same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06fd94b-aaba-d65f-1fc7-7131d6ff892f
* Version Independent ID: 3de244c3-d43b-be7a-bad3-b5e04a1c2fd8
* Content: [Compiling Apps with .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/index)
* Content Source: [docs/framework/net-native/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/index.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @daniel-zazula. It doesn't seem we have that link anymore. So I'll just going to remove it from the docs. /cc @rpetrusha
