### ISSUE TITLE
Missing info: sentence is not finished

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5513]
In the [section on what's new in ASP.NET in .NET Framework 4.6.2](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#aspnet-3) the first topic shows an example that creates the resource file with error messages:
>You can then create a resource file, DataAnnotation.Localization.fr.resx, whose key is the error message string and whose value is the localized error message. The file must be found in the App.LocalResources folder. For example, the following is the key and its value in a localized French (fr) language error message:

However, the paragraph after the table with the example content is definitely not complete:
>This file can then

**Comment by mairaw** [comment]
@rpetrusha to take a look. Could be a migration issue as well.

**Comment by rpetrusha** [comment]
Thanks for noticing the unfinished sentence, @pkulikov. Unfortunately, it's not a migration issue, @mairaw. I just never finished the sentence, and it doesn't really look to me like anything is clearly missing from the description. I'll open a PR to remove the sentence.
