### ISSUE TITLE
GenericUriParserOptions.Default has incorrect description

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#5514]
The current description for this enum field is just "The parser:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fa2aac-8a71-7d6e-b5a4-6b1fa559517a
* Version Independent ID: e704dd8f-fd25-c264-d015-de46a0f1ee95
* Content: [GenericUriParserOptions Enum (System)](https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields-)
* Content Source: [xml/System/GenericUriParserOptions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/GenericUriParserOptions.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **bobdel**

**Comment by mairaw** [comment]
It seems that we lost part of the description with the multiple migrations we had @ChrisMaddock.
I could find more info under https://msdn.microsoft.com/en-us/library/system.genericuriparseroptions(v=vs.100).aspx.

**Comment by rpetrusha** [comment]
In addition, it removes trailing dots, empty segments, and dots-only segments.

**Comment by mairaw** [comment]
Not sure if I follow your comment @rpetrusha. @Thraka would you like to work on this one?

**Comment by Thraka** [comment]
I'll take it.

**Comment by rpetrusha** [comment]
From the comments in [dotnet/corefx](https://github.com/dotnet/corefx/blob/f0ccd9742065ee2aa296448fe3dd38ef6ff77af9/src/System.Private.Uri/src/System/GenericUriParser.cs):

>          // A hierarchical URI, allows a userinfo, non empty Inet-based authority, path, query and fragment
> 
>         // The URI path gets agressively compressed means dots, slashes and backslashes are unescaped,
> 
>         // backslashesare converted, and then it compresses the path. It also removes trailing dots,
> 
>         // empty segments and dots-only segments
