### ISSUE TITLE
An example would help

### ISSUE THREAD

**Issue by TRegan3** [dotnet/docs#5516]
Examples of how to configure ADFS to configure claims as roles would be incredibly helpful here.  It is not intuitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1597a0b7-494d-0cca-bc54-e432719d2256
* Version Independent ID: 17d1429f-ff5d-8f13-bdbd-b8147808305b
* Content: [Claims Based Authorization Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/claims-based-authorization-using-wif)
* Content Source: [docs/framework/security/claims-based-authorization-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/claims-based-authorization-using-wif.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for requesting an example, @TRegan3. We've added it to our backlog, and we'll add an example as we update these docs. I've also added the up-for-grabs label, and added it to our [community project](https://github.com/dotnet/docs/projects/35).

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
