### ISSUE TITLE
Stray space in section title leads to unexpected section links

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#5518]
Describe the bug
On the API pages - the Enum fields section title has a stray space at the end. This was only noticed as it meant links to #fields do not work - the link must instead go to #fields-.
This is of course very minor - but hopefully a simple fix as well!
To Reproduce
Go to https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2
Click on the "link button" besides the "Fields" title
Scroll down to '....'
See error
Expected behavior
Created link should be https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields
Actual behavior
Created link is https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields-
Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 66.0.3359.181 (Official Build) (64-bit)

This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/385
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fa2aac-8a71-7d6e-b5a4-6b1fa559517a
* Version Independent ID: e704dd8f-fd25-c264-d015-de46a0f1ee95
* Content: [GenericUriParserOptions Enum (System)](https://docs.microsoft.com/en-us/dotnet/api/system.genericuriparseroptions?view=netframework-4.7.2#fields-)
* Content Source: [xml/System/GenericUriParserOptions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/GenericUriParserOptions.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **bobdel**

**Comment by mairaw** [comment]
The original place where the feedback was filed is the correct one. This is not a content issue,
