### ISSUE TITLE
Publication base class not Abstract?

### ISSUE THREAD

**Issue by MrEkShun** [dotnet/docs#5523]
I think there is some ambiguity in your explanations of abstract base classes. You list two different types of these template base classes: the Publication base class and the Shape base class. The former provides implementations for members while the latter does not, but what distinguishes these two types of abstract base classes is unclear in your explanations.

Perhaps it should be clearly stated that, while both are template base classes and are declared as abstract, they both serve very different purposes and that what distinguishes their purpose is not explicit in their declarations, but is implicit in how they are defined.

Sorry if I'm misunderstanding. At the very least, I know that I, who am new to this subject, am still a bit confused by the explanations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e813a38-d487-25dc-b70d-23fca9c47221
* Version Independent ID: 92fb3bd2-56a5-e060-8056-491aab145d26
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance#feedback)
* Content Source: [docs/csharp/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/inheritance.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for reaching out to us @MrEkShun 

I went through your comments, and I think we need to update this topic and explain the distinction between an abstract class with abstract members (like `Shape`) and an abstract class that doesn't have abstract members (like `Publication`).

The former is when related classes have the same functionality that is implemented very differently. The latter is when an abstract concept and behavior is shared among several concrete classes.

**Comment by MrEkShun** [comment]
Thanks so much for replying to my comments! I really appreciate the simple
distinction you just gave. It makes more sense now. :)
