### ISSUE TITLE
Would this be any different for a WPF usercontrol?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#5527]
Everything says "window" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388cd25c-fa98-6cd6-7740-8bbc456b772f
* Version Independent ID: 194b7b3a-110d-93d7-4dad-419c7ad65f52
* Content: [Walkthrough: Hosting a Windows Forms Control in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @StingyJack. We'll have to look into this. It's in our backlog for now.
