### ISSUE TITLE
Further Reading section is not clear.

### ISSUE THREAD

**Issue by Keboo** [dotnet/docs#5529]
The second bullet point in [Robust Programming](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features#robust-programming) contains "(see the Further Reading section)" section. However, where to find this section is not clear since this is the only place "Further Reading" occurs. I assume this should actually be pointed to the [Recommended Tags for Documentation Comments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments) section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71da79a-a782-7c7d-0091-e262c66b6fe4
* Version Independent ID: 1f662a67-3ade-26d7-c88a-aee7dd9f0320
* Content: [How to: Use the XML Documentation Features (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features#robust-programming)
* Content Source: [docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @Keboo.  I suspect that at some point the **Further Reading** section was renamed to the **See also** section. But the **Recommended Tags** topic is a better choice. We'll open a PR to make that change.
