### ISSUE TITLE
Consistency check

### ISSUE THREAD

**Issue by WilMead** [dotnet/docs#5532]
The parameter description provides the definition: 
The minimum number of non-alphanumeric characters (such as @, #, !, %, &, and so on) in the generated password.

The example obscures that definition with the comment: 
// Generate a new 12-character password with 1 non-alphanumeric character.
  string password = Membership.GeneratePassword(12, 1);

Adding the two words, "at least", to the comment ensures the sharing of consistent information regardless of where one looks.  Especially when including examples to provide clarity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4e7f91-d0bb-9c98-3c4d-c171be068c93
* Version Independent ID: cd0bb956-d55a-4bd8-0361-b9bf51e08a33
* Content: [Membership.GeneratePassword(Int32, Int32) Method (System.Web.Security)](https://docs.microsoft.com/en-us/dotnet/api/system.web.security.membership.generatepassword?view=netframework-4.7.2)
* Content Source: [xml/System.Web.Security/Membership.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.Security/Membership.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @WilMead. I've opened a PR to fix this.
