### ISSUE TITLE
Possible outdated content

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5541]
I think that [How to: Access a Collection Class with foreach](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-access-a-collection-class-with-foreach) is outdated and can be safely removed rather than fixed:
- The content doesn't match the title: most of all, it's an implementation example of the non-generic `IEnumerable` interface. The [IEnumerable page](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=netframework-4.7.2) itself has an implementation example.
- The `foreach` examples can be found in the [keyword topic](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in) or in the [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/iterators) topic (by the way, both non-generic and generic).

However, that topic contains the following lines:
>In C#, it is not necessary for a collection class to implement `IEnumerable` and `IEnumerator` to be compatible with `foreach`. If the class has the required `GetEnumerator`, `MoveNext`, `Reset`, and `Current` members, it will work with `foreach`.

Those lines should be moved to the [`foreach` keyword topic](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in).

So, I suggest:
- to remove [How to: Access a Collection Class with foreach](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-access-a-collection-class-with-foreach) topic and redirect it either to the [keyword topic](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in) or the [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/iterators) topic
- update the `foreach` keyword topic with the paragraph that `foreach` is compatible also with types that don't implement `IEnumerable` interface but follow a certain pattern. That remark would help folks to be less surprised when they see `foreach` used with `Span<T>` that doesn't implement the interface.

@BillWagner if it sounds as a good plan, I'll make a PR.

**Comment by rpetrusha** [comment]
I think it sounds like a good plan, @pkulikov. An especially good plan, since it also consolidates our doc set somewhat. Do you agree, @BillWagner.

**Comment by BillWagner** [comment]
Yes, I also agree.

On your bullet item:

> - to remove [How to: Access a Collection Class with foreach](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-access-a-collection-class-with-foreach) topic and redirect it either to the [keyword topic](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in) or the [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/iterators) topic

I think the `foreach` topic is a better destination choice.

**Comment by svick** [comment]
> If the class has the required `GetEnumerator`, `MoveNext`, `Reset`, and `Current` members, it will work with `foreach`.

Note that this is inaccurate. What you need is for the collection type to have `GetEnumerator` and for the type returned from `GetEnumerator` to have `MoveNext` and `Current`. `Reset` doesn't have any relationship with `foreach`.

[See an example in SharpLab here.](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMACAwgWAFADe+GJGKALBgLIAUAohhAJTGlF6mcZwD2UEAQwDGACww0wAqBgAeGGADtGTDAQwBfViU14d+dBjr52nFAGZDDAOIRgdBQFcAttAHA+NFQF4AfBkcANgEA3Ph6eAZ0RoRaZBaKwNgOUPwKib4YAAyhHKTmGABGPDwB1DyQAHIQMsCeGBlwAgEAzhA56kA==)

**Comment by pkulikov** [comment]
Cool! Then I'll aim to submit a PR this sprint.
@svick thank you for the note, that's correct. I've thought the same when copied the quote and wanted to check the specification before updating the `foreach` topic. 
I'll also add more examples of `foreach` usage (with `List<T>`, with iterator methods, with `Span<T>`), as examples with only arrays look a little bit boring.
