### ISSUE TITLE
Exception in the sentiment analysis tutorial

### ISSUE THREAD

**Issue by yblender** [dotnet/docs#5555]
I believe i have followed the tutorial correctly for sentiment analysis however,
When i run the following line 
`var model = pipeline.Train<SentimentData, SentimentPrediction>();`

with the previous lines:
```
 var pipeline = new LearningPipeline();
            var loader = new TextLoader<SentimentData>(_dataPath, useHeader: false, separator: "tab");
            pipeline.Add(loader);

            var featurizer = new TextFeaturizer("Features", "SentimentText");
            pipeline.Add(featurizer);

            var classifier = new FastTreeBinaryClassifier() { NumLeaves = 5, NumTrees = 5, MinDocumentsInLeafs = 2 };
            pipeline.Add(classifier);
```

I receive this error:

-		InnerException	{System.InvalidOperationException: Expected arguments in curly braces for 'column'

The following is my sentiment data file:
 ```
public class SentimentData
    {
        [Column(ordinal: "0")]
        public string SentimentText;
        [Column(ordinal: " 1", name: "Label")]
        public decimal Sentiment;
    }
    public class SentimentPrediction
    {
        [ColumnName("PredictedLabel")]
        public bool Sentiment;
    }
```

I have attached the full error.
[sentiment_analysis_full_error.txt](https://github.com/dotnet/docs/files/2031063/sentiment_analysis_full_error.txt)

**Comment by yblender** [comment]
@BillWagner Apologies, this seems to be working now. I'm not sure what i did wrong but when i did a direct copy and paste it works. (i typed it out the first time)

**Comment by BillWagner** [comment]
I'm glad it's working.  

Closing per above conversation.
