### ISSUE TITLE
How do you set up an sts issuer on local host?

### ISSUE THREAD

**Issue by TRegan3** [dotnet/docs#5558]
In your web.config screen shot you are pointing to a wsFederation sts that runs on the local host.  A walk-through on how to set that up would be extremely helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a82badfb-faa2-0a0b-4a55-59a52ebe9806
* Version Independent ID: 6a0dbfb2-a12f-3541-bca1-bf4fd68c4304
* Content: [WSFederation Authentication Module Overview](https://docs.microsoft.com/en-us/dotnet/framework/security/wsfederation-authentication-module-overview)
* Content Source: [docs/framework/security/wsfederation-authentication-module-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/wsfederation-authentication-module-overview.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@brentschmaltz can you please take a look at this request?

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
