### ISSUE TITLE
Thread-safety and single-initialisation of shared members.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#5563]
The documentation should clarify what happens if multiple threads reference a shared member defined like this:

```vb
Public Shared ReadOnly Instance As SomeClass = New SomeClass()
```

As I understand it (and this is what I want to be sure about), the run-time will ensure that `Instance` is initialised exactly once and that if SomeClass has no mutable members, then all access to `Instance` is thread-safe. Ideally, an example will be given showing a (thread-safe) implementation of singletons which is a very common use case for shared fields/properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7eed7e-92ba-239a-8162-591b666ad6ab
* Version Independent ID: 04d245fd-2a6a-725d-9b86-8e50998afdc3
* Content: [Shared (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/shared)
* Content Source: [docs/visual-basic/language-reference/modifiers/shared.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/shared.md)
* Service: **unspecified**
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@KathleenDollard can you comment on this issue and confirm the behavior? Thanks!

**Comment by mairaw** [comment]
Ping @KathleenDollard

**Comment by ericmutta** [comment]
So I tried writing code to test my theory (i.e: that the run-time will ensure `Instance` is initialised exactly once) and it appears to be exactly what happens. Try this code in a console project:

```vb
Imports System.Threading

Public Module Module1
  Public Class CSharedTest
    Public Shared Instance As New CSharedTest()

    Public Sub New()
      Console.WriteLine($"Constructor running from thread: {Thread.CurrentThread.Name}")
    End Sub

    Public Sub SayHello()
      Console.WriteLine($"{Thread.CurrentThread.Name} says hello!")
    End Sub
  End Class

  Public Sub Main()
    Dim threads = New List(Of Thread)
    Dim rnd = New Random()

    Dim ThreadCode As ThreadStart =
      Sub()
        Console.WriteLine($"{Thread.CurrentThread.Name} starting.")
        Thread.Sleep(TimeSpan.FromSeconds(rnd.Next(1, 3)))

        CSharedTest.Instance.SayHello()

        Console.WriteLine($"{Thread.CurrentThread.Name} exiting.")
      End Sub

    For n = 1 To 10
      threads.Add(New Thread(ThreadCode) With {.Name = $"Thread{n}"})
    Next

    Console.WriteLine($"Starting {threads.Count} threads.")
    For Each t In threads
      t.Start()
    Next

    Console.WriteLine($"Waiting for {threads.Count} threads.")
    For Each t In threads
      t.Join()
    Next

    Console.WriteLine($"Finished.")
    Console.ReadLine()
  End Sub
End Module
```

The code creates 10 threads and tries to ensure that they concurrently call ` CSharedTest.Instance.SayHello()`. No matter how many times you do it, the `CSharedTest.Instance` property defined as `Shared` is initialised by only one of the threads (the console output will say "Constructor running from ThreadX" just once).

It may be worth it to explicitly state this in the [Behaviour](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/shared#behavior) section of the current docs on the `Shared` keyword (I can do the PR if approved).

Before discovering that the run-time took care of thread-safe initialisation of shared members, I would write code like the following which handles locking manually and is so much more complex:

```vb
  Public Class CSharedTest2
    Private Shared ReadOnly mLockInstance As New Object

    Private Shared mInstance As CSharedTest2

    Public Shared ReadOnly Property Instance As CSharedTest2
      Get
        SyncLock mLockInstance
          If mInstance Is Nothing Then
            mInstance = New CSharedTest2()
          End If

          Return mInstance
        End SyncLock
      End Get
    End Property
  End Class
```

However, when you know that the run-time takes care of thread-safe initialisation, that entire class can be reduced to just three lines (which is a big win):

```vb
  Public Class CSharedTest2
    Public Shared ReadOnly Instance As New CSharedTest2()
  End Class
```

CC: @KathleenDollard.

**Comment by KathleenDollard** [comment]
I'd like to see this up front in the first paragraph as it is core to the purpose of `Shared`.

That paragraph is currently

> Specifies that one or more declared programming elements are associated with a class or structure at large, and not with a specific instance of the class or structure.

Which isn't even clear. Our docs are Open Source for a reason. This is low hanging fruit for someone that wants to contribute, they are really working to streamline the process and myself or @mairaw are happy to help. You can either propose something here for broad feedback and then add it, or change it in the docs (which I'd suggest for most changes).

**Comment by ericmutta** [comment]
> @KathleenDollard You can either propose something here for broad feedback and then add it, or change it in the docs (which I'd suggest for most changes).

OK, I will do a PR when I get a chance :+1:
