### ISSUE TITLE
exception in Create the dictionary of input parameters

### ISSUE THREAD

**Issue by sispor** [dotnet/docs#5567]
class Program in Main is exception to object Dictionary<string, object> inputs= new Dictionary<string, object>(). You can declared: var inpust= new Dictionary<string, object>();
for example:
        static void Main(string[] args)
        {
           var parameters = new Dictionary<string, object>();
            CommonClass cc = new CommonClass();
            parameters.Add("iRedLightDelay", cc.RedLightDelay);
            parameters.Add("iGreenLightDelay", cc.GreenLightDelay);
            parameters.Add("iYellowLightDelay",cc.YellowLightDelay);

            WorkflowInvoker.Invoke(new TrafficLight(), parameters);
            Console.ReadKey();
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3405f0f6-9b71-b26a-3b49-b8624e4adf07
* Version Independent ID: 3f17617b-3ea9-15a0-b33d-594c4d53200b
* Content: [Using WorkflowInvoker and WorkflowApplication](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/using-workflowinvoker-and-workflowapplication)
* Content Source: [docs/framework/windows-workflow-foundation/using-workflowinvoker-and-workflowapplication.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/using-workflowinvoker-and-workflowapplication.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Hi @sispor, is this comment related to the examples we show on that topic?

**Comment by mairaw** [comment]
Given the lack of response, I'm closing this bug, Feel free to reopen if you can share more details of where in the content you're seeing this.
