### ISSUE TITLE
Migrate new .NET Core Docker articles from dotnet-docker repo

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#5570]
There are several new .NET Core Docker articles in the dotnet-docker repo. They need to be edited and migrated to docs. 

Articles identified:

- [ ] [Develop .NET Core Applications in a Container](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-dev-in-container.md)
- [ ] [Running .NET Core Unit Tests with Docker](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-unit-testing.md)
- [ ] [Build .NET Core Self-Contained Applications with Docker](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-selfcontained.md)
- [ ] [Use .NET Core and Docker on ARM32 and Raspberry Pi](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-arm32.md)
- [ ] [Push .NET Core Docker Images to Azure Container Registry](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/push-image-to-acr.md)
- [ ] [Push .NET Core Docker Images to Docker Hub](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/push-image-to-dockerhub.md)

**Comment by Thraka** [comment]
Closing this as it's not a priority at this point in time.
