### ISSUE TITLE
Manifest file additions

### ISSUE THREAD

**Issue by fvanheeswijk** [dotnet/docs#5579]
It is written that you need to add the following:

<compatibility xmlns="urn:schemas-microsoft.comn:compatibility.v1">
  <application>
    
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
  </application>
</compatibility>

Should "urn:schemas-microsoft.comn:compatibility.v1" not be "urn:schemas-microsoft.com:compatibility.v1"? Notice comn -> com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd152f5c-fb08-0400-5aa5-d46afe1d0473
* Version Independent ID: fe01fb3e-73bc-f90a-8862-719a440aa128
* Content: [High DPI support in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms#feedback)
* Content Source: [docs/framework/winforms/high-dpi-support-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/high-dpi-support-in-windows-forms.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
For anyone reading this, note that the text of the above post contains XML that is hidden by GitHub formatting. It should read:

> It is written that you need to add the following:
> 
> ```xml
> <compatibility xmlns="urn:schemas-microsoft.comn:compatibility.v1">
>   <application>
>     
>     <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
>   </application>
> </compatibility>
> ```
> 
> Should "urn:schemas-microsoft.comn:compatibility.v1" not be "urn:schemas-microsoft.com:compatibility.v1"? Notice comn -> com.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @fvanheeswijk, and for responding with the formatted XML, @svick. "comn" is indeed incorrect. It's also an easy fix, so I'll open a PR to address this issue momentarily.
