### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by calrsom** [dotnet/docs#5587]
Just wanted to mention that the class `myReverserClass` should be `MyReverserClass` according to Microsoft C# naming conventions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e525923-e35e-dfc9-9fe5-3714e2fca2ec
* Version Independent ID: 76e29298-dd8d-4662-2e23-f879b51a99e2
* Content: [IComparer(Object, Object) Interface (System.Collections)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.icomparer?view=netframework-4.7.2)
* Content Source: [xml/System.Collections/IComparer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections/IComparer.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @calrsom! In addition to not using standard naming conventions, the example uses ArrayList to create a collection of String elements; the example should be modernized to use List<string>. 
We'll revise the example in the course of the current sprint.

**Comment by calrsom** [comment]
Could maybe use a list initializer as well.

**Comment by svick** [comment]
Does it even make sense to have an example for the non-generic `IComparer`? Shouldn't people be directed to `IComparer<T>` instead?
