### ISSUE TITLE
Be more specific

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5589]
You defined the problem with its own verbiage. I still do not have any idea what *trivia* is, never mind what *leading or trailing trivia* are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a50684b-8bea-4814-a1bd-4ef4b51dc407
* Version Independent ID: 346caa88-9b6d-7700-f32d-5adf356857e8
* Content: [SyntaxNodeExtensions.WithoutTrivia Method (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnodeextensions.withouttrivia?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/SyntaxNodeExtensions.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/SyntaxNodeExtensions.xml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by svick** [comment]
This is explained in [the general Roslyn documentation](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/work-with-syntax#syntax-trivia). I'm not sure the API reference has to explain all the terms it uses, especially for terms that are used as often within the Roslyn API as "trivia".

**Comment by mwpowellhtx** [comment]
@svick Then say as much on the [WithoutTrivia](http://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnodeextensions.withouttrivia) page. At the very least reference the link. I shouldn't have to go mining for reference material when the docs themselves are sparse.
