### ISSUE TITLE
Not the best example for the compiler warning

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5596]
The sample code for the [compiler warning CS0278](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0278) generates the mentioned warning. However, that code also generates the [compiler error CS1640](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1640). 

If there is a guideline that states that the sample code for warnings must compile, the sample code in the warning topic should be updated.

**Comment by svick** [comment]
Based on the description of the warning, I don't see how you could write code that produces the warning, but does not produce any errors.

**Comment by BillWagner** [comment]
After some experimentation, I'm confident @svick is correct: code that generates this warning will also generated an error.

Closing for that reason. 

/cc @MadsTorgersen to confirm our analysis.
