### ISSUE TITLE
Main method not recognized after async

### ISSUE THREAD

**Issue by jefraire** [dotnet/docs#5598]
The guide asks us to convert the Main method to an async type that returns a Task. This causes an issue with the execution of the console application. I receive error CS5001 Program does not contain a static 'Main' method suitable for an entry point. Removing the async designation allows the program to run, but prevents the use of the ML package as indicated by the guide.

**Comment by BillWagner** [comment]
Thanks for reporting this.  It's fixed in PR #5333 which should go live in the next day or two.

In the meantime, the fix is to update the language version from 7.0 to 7.1 (or newer).

Closing as it is fixed in #5333.
