### ISSUE TITLE
Confusing/wrong remarks section of SslStream.SslProtocol property

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#5601]
The remarks section of the property SslStream.SslProtocol is confusing or wrong.

1. It says that a security protocol can be passed to the constructor of the SslStream. But I see no constructor that takes such an argument.
2. It says that SslProtocols.Default is the default value. But the documentation of SslProtocols.Default explicitly states "Despite the name of this field, SslStream does not use it as a default except under special circumstances.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33872e47-b50c-0594-b58f-b6778becac5d
* Version Independent ID: 43f10566-772d-6751-860a-f94bd4d75734
* Content: [SslStream.SslProtocol Property (System.Net.Security)](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.sslprotocol?view=netframework-4.7.2#System_Net_Security_SslStream_SslProtocol)
* Content Source: [xml/System.Net.Security/SslStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslStream.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by cremor** [comment]
@dotnet/docs The current documentation is still the same as when I opened this issue, so the same problems remain. Please reopen.

**Comment by BillWagner** [comment]
Reopening and moving to dotnet-api-docs.

**Comment by BillWagner** [comment]
Issue moved to [dotnet/dotnet-api-docs #5280](https://github.com/dotnet/dotnet-api-docs/issues/5280) via [**ZenHub**](https://www.zenhub.com/)
