### ISSUE TITLE
this is good example for data processing, thanks

### ISSUE THREAD

**Issue by jsbwong** [dotnet/docs#5602]
this is good example for data processing, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f8edf9-aaf1-0ca9-ed64-93b69352cc2f
* Version Independent ID: c9597e50-2fce-d3a5-585d-045a9edf13ab
* Content: [How to: Read Characters from a String](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-read-characters-from-a-string)
* Content Source: [docs/standard/io/how-to-read-characters-from-a-string.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-read-characters-from-a-string.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
@jsbwong, Thank you for the feedback!
