### ISSUE TITLE
"this" is missing in examples

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/docs#5603]
In the examples at the top "this" is not defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78397d09-6174-74aa-6fe7-7aa7e87b44a6
* Version Independent ID: 3291294d-3965-0662-a2e0-410be6b69817
* Content: [Events (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/events)
* Content Source: [docs/fsharp/language-reference/members/events.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/events.md)
* Service: **unspecified**
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@BentTranberg Sorry, I'm not sure what you're referring to here. Is there a `this` in a code sample which will resulting in code that won't compile?

**Comment by BentTranberg** [comment]
Darn, my fault. Sorry for wasting your time. I am so indoctrinated with using "as this" for classes and "x." for members that I fooled myself into thinking that "as this" was missing from the class header when I saw "member this." in member definitions.

**Comment by mairaw** [comment]
So ok to close this issue @BentTranberg?
