### ISSUE TITLE
Add documentation on how referencing assets external to one's project is done in .NET Core

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#561]
As we released RC2 and a lot of people started picking it up, there were issues in the dotnet/cli repo (like dotnet/cli#3590 for example or dotnet/cli#3633 as well) where it shows our users are confused on how to add external code assets (like libraries or other projects) to their projects. More to the point, I think that there is some surprise about the fact that in .NET Core you don't really deal with DLLs from disk, but with NuGet packages and source projects. 

We cover the **how** of this in the golden path scenarios, but we don't cover the **why** of it anywhere, AFAIK. I think it would be useful to add this to some of our .NET Core overall docs here. 

/cc @richlander @mairaw

**Comment by EricZimmerman** [comment]
both links in the referenced issue 3590, are 404s.

**Comment by blackdwarf** [comment]
@EricZimmerman good point, updated the links in the referenced issue.

**Comment by mairaw** [comment]
@richlander do you think this is still useful?

**Comment by mairaw** [comment]
closing this one now.
