### ISSUE TITLE
Where are the ctors of the syntax itself documented?

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#5612]
i.e. ``new ConstructorDeclarationSyntax((CSharpSyntaxNode) green, (SyntaxNode) parent, (int) position)``. What is a ``green``? ``parent`` I assume is the ``ClassDeclarationSyntax``? I am defining this in the list of ``MemberDeclarationSyntax`` nodes, correct? ``position`` I take to mean simply the order in that list?

Just ***say so***. Improve the documentation here, please. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90032af-12a2-774b-4e45-b673ba4d5cd5
* Version Independent ID: 4f0b01d0-5b80-3df5-02d9-54737e4f5951
* Content: [ConstructorDeclarationSyntax Class (Microsoft.CodeAnalysis.CSharp.Syntax)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.constructordeclarationsyntax?view=roslyn-dotnet#methods)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ConstructorDeclarationSyntax.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp.Syntax/ConstructorDeclarationSyntax.xml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by mwpowellhtx** [comment]
I may be barking up the wrong tree with this particular area. Looking instead at the ``SyntaxFactory.ConstructorDeclaration(...)``.

**Comment by svick** [comment]
That constructor is internal and what `green` is is an implementation detail not exposed in the Roslyn API. (If you're curious, have a look at [this article from Eric Lippert](https://blogs.msdn.microsoft.com/ericlippert/2012/06/08/persistence-facades-and-roslyns-red-green-trees/).)

You already figured out that the way to create syntax node types is by using `SyntaxFactory`. This is certainly something that should be documented more prominently. I assume it would be mentioned in a type's Remarks section (once those are written). I also think that `SyntaxFactory` is important enough to warrant explanation in [the conceptual documentation for Roslyn](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/).

**Comment by mwpowellhtx** [comment]
@svick Yep, :+1:'s up and down that list of areas to focus on.
