### ISSUE TITLE
MakeCert.exe is deprecated

### ISSUE THREAD

**Issue by danjagnow** [dotnet/docs#5619]
The "Using Makecert.exe to Build a Certificate Chain" section refers to the MakeCert.exe tool.  According to https://msdn.microsoft.com/en-us/library/windows/desktop/aa386968(v=vs.85).aspx, MakeCert.exe is deprecated.  This document should probably be updated to reference the explanation of how to use the Powershell Cmdlet `New-SelfSignedCertificate`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a828d2-3306-b5cb-4006-6e362128db76
* Version Independent ID: 98c0ddd6-cfee-6bd3-5fa2-aad775586abf
* Content: [Working with Certificates](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/working-with-certificates)
* Content Source: [docs/framework/wcf/feature-details/working-with-certificates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/working-with-certificates.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can you or someone on your team help address this issue?

**Comment by zhenlan** [comment]
Add @Lxiamail to see if we want to put up a new doc using cmdlet.

**Comment by mairaw** [comment]
@Lxiamail this feedback keeps reoccurring. The two other duplicate requests are linked to this one.
On #6391, @ThangHuuVu suggested using New-SelfSignedCertificateEx.

**Comment by Lxiamail** [comment]
@bartonjs you are expert of certificate, can you advice the replacement of makecert.exe?

**Comment by bartonjs** [comment]
`New-SelfSignedCertificateEx` for PowerShell, or the CertificateRequest class in net472 / netcoreapp2.0.  Just depends on what you want to do.

**Comment by yujayee** [comment]
@bartonjs I just found `New-SelfSignedCertificateEx` was not supported on Linux and Mac OS, do you have any suggestions on cross-platform support of creating cert? Although we can also use CertificateRequest class, it seems a little more complex than using a simple command or existing tool for customers.
