### ISSUE TITLE
I have some suggestions on C# Documentation about Async Await

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#5622]
This issue is from @HyVong007 https://github.com/MicrosoftDocs/feedback/issues/231
I am learning C# Asynchronous Programming with Unity3D. I have read many times on your Documentation Website. And I think it will be very very easy to understand if you draw more visual Picture aka Info Graphic to help people understand !
Thank you so much for your helpful documentation !
Here is My Picture : https://drive.google.com/file/d/1KmNsjf5bQRVwdeqaIKobcdJQGPwP2FnN/view
The attached picture is my code in Unity3D to demo very basic of Async. If anything wrong please let me know. Thank ^_^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce15c3c-366d-a776-4cea-9e226e46c986
* Version Independent ID: 6b0d7389-56a5-f0d3-7f3a-e7f59c27df83
* Content: [async (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async)
* Content Source: [docs/csharp/language-reference/keywords/async.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/async.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @HyVong007  

We're collecting features and thoughts on our async / await docs. We do need to explain that story better.

**Comment by BillWagner** [comment]
Closing this based on the new index page for async / await.
