### ISSUE TITLE
Reason to exclude "trip_time_in_secs" ?

### ISSUE THREAD

**Issue by mnbuch** [dotnet/docs#5629]
Following is given:
"trip_time_in_secs: The amount of time the trip took. You won't know how long the trip takes until after it is completed. You exclude this column from the model."

Why? Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York Taxi Fares (Regression)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@mnbuch imagine yourself aimlessly wandering around New York. Suddenly, an Englishman stops you to ask for a favor. He is new in the city, has no dollars, only British pounds, and is now late for a date. He desperately needs a taxi drive and asks you for some dollars to pay for it.

You want to help him. But how much money to give? Out of your pocket, you get the regression calculator and ask some clarifying questions. You already know that he travels alone (*passenger_count*) and pays by cash (*payment_type*). So you ask the boy in a hurry how far he needs to go (*trip_distance*) and a couple more questions.

Now, if your regression calculator doesn't need the trip time (*trip_time_in_secs*) to calculate the trip fare, you can calculate the trip fare immediately and save the date of the poor foreigner. 

If the regression relies on the trip time to predict the fare, then one must wait for the trip to end to calculate the trip fare. But at the end of the trip you ask the taxi driver for the amount to pay, not the regression calculator.
