### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by boba8710** [dotnet/docs#5631]
Missing ( on line 32 of the symmetric encryption example

Correct line should probably be:
CryptoStreamMode.Write(); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee15f916-5406-85fa-b7fb-a9e69fcd3efb
* Version Independent ID: b6aae569-8a56-0a44-7b8e-e54491418baf
* Content: [Encrypting Data](https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data)
* Content Source: [docs/standard/security/encrypting-data.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/encrypting-data.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by akilram** [comment]
This isn't right, because `CryptoStreamMode` is an enum!

The program works just fine, and the sample is correct:
![screenshot from 2018-05-26 22 04 09](https://user-images.githubusercontent.com/4010305/40582116-f2c4af5e-6130-11e8-9b62-dc16d0068697.png)
