### ISSUE TITLE
There's a very specific case in here... 

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#5635]
... that an example would be beneficial. At least enough to contrast the difference between the MRE and MRES. 

Also, "wait times are expected to be very short" is too subjective. Is this < 1ms or < 30 seconds or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe76905-60c0-9fce-5e51-fdc6c7239a9d
* Version Independent ID: 1b993777-1e18-50f2-7c0d-b0c3ce004d24
* Content: [ManualResetEvent and ManualResetEventSlim](https://docs.microsoft.com/en-us/dotnet/standard/threading/manualresetevent-and-manualreseteventslim)
* Content Source: [docs/standard/threading/manualresetevent-and-manualreseteventslim.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/manualresetevent-and-manualreseteventslim.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
PR #10233 redirects the referenced article to the API reference page.

The question about wait times was addressed to the following paragraph:
> In the .NET Framework 4, you can use the `System.Threading.ManualResetEventSlim` class for better performance when wait times are expected to be very short, and when the event does not cross a process boundary.

The following pages are the candidates for update when fixing this issue:
- https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent
- https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualreseteventslim

**Comment by StingyJack** [comment]
Still looking for what "Very Short" means.

**Comment by BillWagner** [comment]
opening and moving to dotnet-api-docs

**Comment by BillWagner** [comment]
Issue moved to [dotnet/dotnet-api-docs #5281](https://github.com/dotnet/dotnet-api-docs/issues/5281) via [**ZenHub**](https://www.zenhub.com/)
