### ISSUE TITLE
Hey Ho ...

### ISSUE THREAD

**Issue by vanComma** [dotnet/docs#5637]
All this Microshaft© crap just fucks up my computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0e958e-d263-e88b-0f71-995d73439572
* Version Independent ID: 27cce18b-6fd8-5efa-e978-ba9bd5728225
* Content: [Install the .NET Framework on Windows Vista](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-vista?utm_source=getdotnet&utm_medium=referral)
* Content Source: [docs/framework/install/on-windows-vista.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/on-windows-vista.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by eriawan** [comment]
@mairaw 

Could we just close this trolling/spamming issue?

**Comment by BillWagner** [comment]
closing as spam.
