### ISSUE TITLE
Example for lastOrDefault garbled

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/docs#5639]
The first example for lastOrDefault, near first occurrence of the word on the page, doesn't look right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3514796-1d23-6213-51c8-a90e399a5afd
* Version Independent ID: 518ea6eb-b99d-deac-eca3-4a2be6b4baa9
* Content: [Query Expressions (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/query-expressions)
* Content Source: [docs/fsharp/language-reference/query-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/query-expressions.md)
* Service: **unspecified**
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by svick** [comment]
It seems the `<` character within `<pre><code>` tags is causing the issue and that HTML encoding it fixes it. I have opened a Pull Request that makes that change: https://github.com/dotnet/docs/pull/5642
