### ISSUE TITLE
Default column names

### ISSUE THREAD

**Issue by korzh** [dotnet/docs#5640]
From your IRIS classifier example, I guessed that the default column name for features is "Features" and for the label is "Label" and they can be changed using "LabelColumn" and "FeatureColumn" properties of the classifier class. Is it correct?
(it would be better to call the second one "FeaturesColumn" by the way)

Then I tried to change the column name for the output data structure. I used
```
        public class IrisPrediction {
            [ColumnName("PredictedIris")]
            public string PredictedIris;
        }
```

and then

```
            pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedIris" });
```

but it throws an exception saying "Column not found: PredictedIris" 
What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
@aditidugar can you take a look at this question? It's about the Iris tutorial.

**Comment by aditidugar** [comment]
@codemzs will be able to help you here!

**Comment by korzh** [comment]
@codemzs Thank you for so detailed explanation. Of course, I can totally work with the default names. 
I just thought that `PredictedLabelColumn` property actually makes the necessary configuring. 
Will look forward to the next updates which allow to configure the scorer as well.

**Comment by JRAlexander** [comment]
Thanks, @aditidugar, and @codemzs for the answers. I think we can close this.
