### ISSUE TITLE
Broken links to Custom RoutedCommand Sample

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/docs#5645]
The links to Custom RoutedCommand Sample are broken. (It's the same link, duplicated.) Last link in "Creating Custom Commands", and last link in "See Also".

And the second to last link in "See Also", titled "How to: Add a Command to a MenuItem", does not point to docs.microsoft.com. I don't know if this is something that should be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d209865-95c9-8491-df24-ec2e6e191cc0
* Version Independent ID: 969b5b02-1c6e-b4f9-27ba-b86cce526e4b
* Content: [Commanding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/commanding-overview)
* Content Source: [docs/framework/wpf/advanced/commanding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/commanding-overview.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @BentTranberg. I'll take a look at this topic and see if I can find where the sample was moved to. That link is probably fine going to MSDN. That topic got removed at some point from our docset.
