### ISSUE TITLE
Reflection-only context *can* execute code

### ISSUE THREAD

**Issue by AArnott** [dotnet/docs#5647]
This doc I believe incorrectly states that the reflection-only context cannot execute code. In fact, reflection itself can execute code, including when you query a member's custom attributes. Instances of attributes are returned. When those attributes are defined within that assembly, that requires that that attribute's constructor is executed, so in fact the reflection-only context is *not* a guarantee that code in the assembly will not execute. This is an important point so folks do not rely on it as a security boundary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8732511-e24f-2c9c-57c8-ce469c351e94
* Version Independent ID: 8806bdc9-6cf1-cbcb-0e47-f6edbdcfd59c
* Content: [Best Practices for Assembly Loading](https://docs.microsoft.com/en-us/dotnet/framework/deployment/best-practices-for-assembly-loading)
* Content Source: [docs/framework/deployment/best-practices-for-assembly-loading.md](https://github.com/dotnet/docs/blob/master/docs/framework/deployment/best-practices-for-assembly-loading.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
I can't reproduce what you're describing.

Given this code for a library:

```c#
using System;

[A]
class A : Attribute
{
    public A() => Console.WriteLine("Boom");
}
```

And this code for an application:

```c#
using System.Linq;
using System.Reflection;

class Program
{
    static void Main()
    {
        string path = …;
        var a = Assembly.ReflectionOnlyLoadFrom(path);
        var t = a.GetTypes().Single();
        t.GetCustomAttributes();
    }
}
```

I get:

```
Unhandled Exception: System.InvalidOperationException: It is illegal to reflect on the custom
attributes of a Type loaded via ReflectionOnlyGetType (see Assembly.ReflectionOnly) -- use 
CustomAttributeData instead.
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo element)
   at Program.Main() in C:\code\tmp\coreapp\Program.cs:line 11
```

**Comment by AArnott** [comment]
Hmmm... it's been a very long time since I actually interacted with this API. Maybe I remember wrong or maybe that was a behavior in .NET 2.0.

**Comment by AArnott** [comment]
Sorry for the trouble.

**Comment by mairaw** [comment]
Should we close this then @AArnott?

**Comment by AArnott** [comment]
Yes.
