### ISSUE TITLE
PascalCase or camelCase for public functions on modules

### ISSUE THREAD

**Issue by WallaceKelly** [dotnet/docs#5648]
Does this document answer the question about the naming convention for public functions on modules? Should those be PascalCase or camelCase?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Service: **unspecified**
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
I don't think it answers it directly, no. Module-bound public functions should be camelCase. [This section](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-camelcase-for-class-bound-expression-bound-and-pattern-bound-values-and-functions) technically covers it, but I don't think the example makes it clear. I can make a change.

**Comment by svick** [comment]
Doesn't [the *F# component design guidelines* article](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#guidelines-for-f-facing-libraries) cover that?

> let-bound values are often public when following traditional functional design patterns. However, generally use PascalCase when the identifier can be used from other .NET languages.

**Comment by cartermp** [comment]
@svick It does, but I don't think people would expect to go to that article to find this guidance. The first push for these sets of articles were to get the CDG and other writings synthesized and published. Various cleanup efforts need to happen now.
