### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by m1caell** [dotnet/docs#5653]
Very good article, rich in details and good examples. Congratulations!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you so much for your feedback @m1caell! We’re happy that you liked it.
