### ISSUE TITLE
Good tutorial

### ISSUE THREAD

**Issue by kacho39** [dotnet/docs#5654]
It is a good tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Hello World interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/hello-world.yml)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @kacho39! We appreciate it.
