### ISSUE TITLE
How did you select learner

### ISSUE THREAD

**Issue by Amit1150** [dotnet/docs#5655]
I've followed both tutorials, also https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows. I just wanted to know, how did you select learner, as Both Iris and sentiment-analysis are types of binary  classifier, so if possible please explain why you have selected FastTreeBinaryClassifier for sentiment-analysis and StochasticDualCoordinateAscentClassifier for Iris-data tutorial. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Adding @aditidugar and @asthana86 to help with this question.

**Comment by aditidugar** [comment]
Hey @Amit1150, thanks for your question! Actually, the Iris tutorial is a multi-class classification task, not a binary classification task since there are 3 different types of flowers that can be predicted. Hence, you must use a different learner.

Hope this helps!

**Comment by mairaw** [comment]
With that, I think we can close this issue. Thanks @aditidugar!
