### ISSUE TITLE
Unclear example code: Changing ChainPolicy after calling Build()

### ISSUE THREAD

**Issue by MaxTranced** [dotnet/docs#5657]
In the current example code
`ch.ChainPolicy.RevocationMode = X509RevocationMode.Online;`
is called after
`ch.Build (certificate);`
is called.

It is not clear if the change in `ChainPolicy` will have an effect on the validation or not. I assume that validation is done during the call to `Build()`, so I assume that any subsequent changes to `ChainPolicy` have no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0cd090-00b3-72b3-ab0f-4223aa850a08
* Version Independent ID: 7ee213d4-f96b-dcd6-cee7-4d416a0965c0
* Content: [X509Chain Class (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chain?view=netframework-4.7.1)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/X509Chain.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.X509Certificates/X509Chain.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@bartonjs can you help with this question?

**Comment by bartonjs** [comment]
I agree with the reporter.  Changing ChainPolicy after calling Build has no practical effect (other than it can change what the next call to Build does).

`X509RevocationMode.Online` is the default, so the easiest fix is probably just to remove that line.

**Comment by MaxTranced** [comment]
Or moving the line to before the call to Build() 🙂. Most examples for the members of this class need improving.

**Comment by mairaw** [comment]
I was going to remove the call but decided to just move it above the Build call given this sample was also used by the X509RevocationMode API.
PR to change that is here: https://github.com/dotnet/samples/pull/323
