### ISSUE TITLE
Where's the kubernetes/service fabric bit?

### ISSUE THREAD

**Issue by karunasoft** [dotnet/docs#5661]
Missing from figure 5-15 is the operationalising part of the story (e.g. kubernetes/service fabric)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: 0df5f0d7-a2b4-e9b3-9f34-d66cedf418a3
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow)
* Content Source: [docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @karunasoft,

This particular chapter is about the development process, so it won't include but a mention to Kubernetes and Service Fabric.

However, chapter 4 of the [e-book](https://aka.ms/microservicesebook) already includes a nice section on Kubernetes and Service Fabric.

That chapter is just about to be merged into section [Architecting Container- and Microservice-Based Applications](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/), but you can check the [e-book](https://aka.ms/microservicesebook) right away.

Closing the issue now, but will reopen if needed. Feel free to comment here.
