### ISSUE TITLE
Doc bug? Table seems cut off

### ISSUE THREAD

**Issue by bradygmsft** [dotnet/docs#5665]
The first table seems to be cut off, as it just says "A secure and..." and then nothing, in the description. Also noticed that the first table lacks the UdpBinding, so it looks like it may have been cut off in a previous update. Thanks for being awesome, docs.ms!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2387192f-264a-c1c0-ab59-ffa1d4f5bd53
* Version Independent ID: 79f2524b-bfb4-fd79-bbe7-46f7584c3a53
* Content: [System-Provided Bindings](https://docs.microsoft.com/en-us/dotnet/framework/wcf/system-provided-bindings#feedback)
* Content Source: [docs/framework/wcf/system-provided-bindings.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/system-provided-bindings.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @bradygaster. I've checked on our previous CMS system and it seems to be a migration issue. The last two lines look like the following in our old system:
![image](https://user-images.githubusercontent.com/12971179/40689625-dcc5cb74-6357-11e8-96e6-84262cc7e2c7.png)

I'll add this back later this week.

**Comment by bradygmsft** [comment]
sounds good! thanks @mairaw !
