### ISSUE TITLE
Enum field descriptions are not explanatory 

### ISSUE THREAD

**Issue by KentRollins** [dotnet/docs#5667]
Some of these enumeration values are not so obvious from the name.  FastPoint and FastLine could use some explanation.  Or a link to a page that does explain them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a22dae5-fb28-2090-b6a7-48750605f2ca
* Version Independent ID: 9301e06a-aa6c-20d7-914f-8e1aef1c5b08
* Content: [SeriesChartType Enum (System.Web.UI.DataVisualization.Charting)](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.datavisualization.charting.seriescharttype?view=netframework-4.7.1)
* Content Source: [xml/System.Web.UI.DataVisualization.Charting/SeriesChartType.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.UI.DataVisualization.Charting/SeriesChartType.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **mblythe**

**Comment by mairaw** [comment]
Thanks @KentRollins for the feedback. We could probably link to the chart types articles under https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/dd489233(v%3dvs.110) for more info for each chart type.
