### ISSUE TITLE
setup is incomplete for F#

### ISSUE THREAD

**Issue by gbsheble** [dotnet/docs#5669]
This document does not execute as stated when loaded into Visual Studio Community Version 15.7.2, seems that the setup is incomplete for F#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4051ae2-8154-5007-b633-dcd0d71f84fc
* Version Independent ID: fed62955-cf8b-55e7-b4d4-851cd85dc6d2
* Content: [Get started with F# in Visual Studio](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-visual-studio)
* Content Source: [docs/fsharp/get-started/get-started-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-visual-studio.md)
* Service: **unspecified**
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by mairaw** [comment]
@cartermp can you take a look at this issue?
