### ISSUE TITLE
Column copier is not working

### ISSUE THREAD

**Issue by Amit1150** [dotnet/docs#5671]
I followed the tutorial, and it's working. But while playing around I made changes in code e.g: changed `[Column(ordinal: "1", name: "Label")]` to `[Column(ordinal: "1")]` and then used `ColumnCopier` to copy that column to Label. like this `pipeline.Add(new ColumnCopier("Sentiment","Label"));`. But it's not working. It throws exception `Source column 'Label' not found`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by svick** [comment]
As far as I can tell, if you want to copy from `Sentiment` to `Label`, you need `new ColumnCopier(("Sentiment","Label"))`. Notice the double parentheses, which causes the creation of a tuple.

Does that work for you?

**Comment by mairaw** [comment]
Thanks @svick for jumping in and helping. I'll close this issue then.
