### ISSUE TITLE
Pay attention to RabbitMQ and AMQP 1.0

### ISSUE THREAD

**Issue by Necriis** [dotnet/docs#5672]
If you plan to use RabbitMQ rather than Service Bus in development, by interfacing with AMQP 1.0, pay attention to this :
The equivalent of Service Bus topics in RabbitMQ are Header Exchanges. But those are not compatible with the AMQP 1.0 plugin provided by RabbitMQ.
see https://github.com/rabbitmq/rabbitmq-amqp1.0#message-properties-annotations-headers-etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f590167-a388-94ac-e39b-463978a761b0
* Version Independent ID: 7f36b050-25b4-e998-26b7-bcf1ebc3d4aa
* Content: [Implementing an event bus with RabbitMQ for the development or test environment](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @Necriis. @CESARDELATORRE please take a look.

**Comment by wmeints** [comment]
I see you are not reusing connections when publishing events. The RabbitMQ documentation states that connections should be long-lived objects. Creating a connection has a lot of overhead attached to it. See also https://www.rabbitmq.com/dotnet-api-guide.html#connection-and-channel-lifspan

Also, make sure you enable automatic connection failure recovery. It will save you some major headaches. Details about it are listed in the documentation: https://www.rabbitmq.com/dotnet-api-guide.html#recovery

**Comment by mvelosop** [comment]
Hi @Necriis, thanks for the heads up!

There are no plans to change messaging to AMQP 1.0 en eShop, but toke note of this in the [backlog](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Backlog#other)

Thanks!

Closing this issue now but feel free to comment, will reopen if needed.
