### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JarkoDubbeldam** [dotnet/docs#5673]
There are two typos in the third codeblock. It should be `Northwind` instead of `Northwnd`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2448ac4-a6d0-e376-36fe-c6279fd606c8
* Version Independent ID: 50f1aa4e-8e0e-2bee-db10-9c65c11b4028
* Content: [How to: Connect to a Database](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-connect-to-a-database)
* Content Source: [docs/framework/data/adonet/sql/linq/how-to-connect-to-a-database.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/how-to-connect-to-a-database.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
#in-progress

**Comment by douglaslMS** [comment]
@mairaw Can you help me to locate the separate code snippet files in which these typos are found? I can't find them in the "docs" folder structure.

**Comment by BillWagner** [comment]
@douglaslMS Every code snippet whose path starts with "/samples" is in the [dotnet/samples](https://github.com/dotnet/samples) repo.
