### ISSUE TITLE
Odd sentence

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#5674]
The "Security considerations" section starts: "The types and members in the System.Xml namespace rely on the ." - this isn't a sentence. Something missing?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cddc6b-80bd-a114-0e2f-1ff9f1635e8d
* Version Independent ID: 9d91a158-8b73-163e-728b-7d60c6ad17fe
* Content: [System.Xml Namespace](https://docs.microsoft.com/en-gb/dotnet/api/system.xml?view=netframework-4.7.1)
* Content Source: [xml/ns-System.Xml.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Xml.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ptoye. At some point, the link dropped out. The link text was supposed to read ".NET Framework security system", which was intended to link to https://docs.microsoft.com/en-us/dotnet/standard/security/. I've opened a PR to restore the lost  text.
