### ISSUE TITLE
Example does not match documentation

### ISSUE THREAD

**Issue by ewest305** [dotnet/docs#5677]
In the following example, the reference to 'AuditedBankingTransaction' is not defined in the documentation. I would expect 'AuditedBankingTransaction' to appear as part of a class which it is not. 

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">  
  <s:Header>  
    <h:IsAudited xmlns:h="http://schemas.contoso.com/auditing/2005" xmlns="http://schemas.contoso.com/auditing/2005">false</h:IsAudited>  
    <h:operation xmlns:h="http://tempuri.org/" xmlns="http://tempuri.org/">Deposit</h:operation>  
  </s:Header>  
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">  
    <AuditedBankingTransaction xmlns="http://tempuri.org/">  
      <transactionData/>  
    </AuditedBankingTransaction>  
  </s:Body>  
</s:Envelope>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86fe2744-b972-4e68-b682-228fa25cd3b7
* Version Independent ID: c88e3bdc-a9df-c74b-d5d2-8b675b912811
* Content: [Using Message Contracts](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/using-message-contracts)
* Content Source: [docs/framework/wcf/feature-details/using-message-contracts.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/using-message-contracts.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can someone on your team look at this issue?

**Comment by zhenlan** [comment]
@jcondex any suggestion?

**Comment by mairaw** [comment]
@jcondex can you please take a look?

**Comment by zhenlan** [comment]
Add @Lxiamail
