### ISSUE TITLE
dotnet pack does not create project.assets.json when no referenced nuget packages

### ISSUE THREAD

**Issue by hansenfreddy** [dotnet/docs#5680]
# Problem

Running dotnet pack will give these error messages if no referenced nuget packages:

`C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018: The "GetProjectReferencesFromAssetsFileTask" task failed unexpectedly.
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018: System.InvalidOperationException: The assets file produced by restore does not exist. Try restoring the project again. The expected location of the assets file is C:\...
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at NuGet.Build.Tasks.Pack.GetProjectReferencesFromAssetsFileTask.Execute()
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()`

Seems to apply to only .net framework projects.
dotnet version: 2.1.201

## Reproduce
1. Create new class lib .net framework (I used 4.5 in my repro)
2. Run `dotnet pack`

## Workaround
Add a random nuget package (no need to reference it in code) with the new PackageReference for csproj (enable via Visual Studio Option or modify csproj manually)

**Comment by mairaw** [comment]
@hansenfreddy given that this is a product question, I've moved your feedback to https://github.com/dotnet/cli/issues/9385.
