### ISSUE TITLE
Typo in code samples

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#5681]
"represengting" appears on this page, and in other samples. Sorry - not set up to fix this myself right now!

https://github.com/dotnet/samples/search?utf8=%E2%9C%93&q=represengting+&type=

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71953a61-1074-48ff-7afd-9135975b28f2
* Version Independent ID: 2ba91f2f-bf41-7f7b-b0b3-64c4c0c932d9
* Content: [DateTime.TryParseExact Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tryparseexact?view=netframework-4.7.2#feedback)
* Content Source: [xml/System/DateTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/DateTime.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for the feedback @ChrisMaddock. I've opened a PR to fix this: https://github.com/dotnet/samples/pull/94
