### ISSUE TITLE
main compiler option

### ISSUE THREAD

**Issue by devcanute** [dotnet/docs#5691]
/main:class should instead be /main:namespace.class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5453dbc-08db-b9b2-5198-50bff608b5c8
* Version Independent ID: f182cda3-c40b-4216-6614-49da5eb0e3c8
* Content: [-main (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/main-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/main-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/main-compiler-option.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sputier** [comment]
I just created a PR to fix this issue 😉
