### ISSUE TITLE
Docker support for Node projects

### ISSUE THREAD

**Issue by dferretti-fig** [dotnet/docs#5696]
I have VS2017 15.7.2 installed with Node.js Development workload included. Is there a way to add docker support to those projects? There is no Add Docker Support option as far as I can see. 
I did poke around the old issues at https://github.com/Microsoft/nodejstools and it looks like Docker support was added at some point, but was it removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf20f50-2d15-1744-386d-1d05ff9931fb
* Version Independent ID: b07f881a-4b4e-9db5-9eb6-c83cf0fba6b2
* Content: [Using Visual Studio Tools for Docker (Visual Studio on Windows)](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker)
* Content Source: [docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md](https://github.com/dotnet/docs/blob/master/docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Hi @dferretti-fig. This repo is for content issues for .NET content which is what this topic is about. I'd suggest you ask that question on forums like StackOverflow or on the Visual Studio Developer Community site (https://developercommunity.visualstudio.com/spaces/8/index.html).
