### ISSUE TITLE
MSDN formatting: missing horizontal scroll

### ISSUE THREAD

**Issue by rangercej** [dotnet/docs#5701]
Some of the lines in this page are really rather long, and when the right-hand side-bar (Feedback, Edit, Share, change theme, etc) are displayed, it's not possible to see entire code snippets nor all descriptions in the attributes table as they scroll underneath the right-hand side-bar. There appears no way to hide the side-bar. Browser: Vivaldi, with vertical tab-bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217c59b2-7fb7-b608-c75e-d8aa6854f42a
* Version Independent ID: 0414a903-2877-4e5a-96ee-3bb21fc518b4
* Content: [\<security> of \<customBinding>](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/security-of-custombinding#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/security-of-custombinding.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Moved the issue to https://github.com/MicrosoftDocs/feedback/issues/406.
