### ISSUE TITLE
Failed adding Microsoft WCF Web Service Reference Provider to the project (.NET Core 2.1.300, VS2017 v15.8.0 Preview 1.1)

### ISSUE THREAD

**Issue by dmitry-pavlov** [dotnet/docs#5703]
I am still getting the error "**Failed adding Microsoft WCF Web Service Reference Provider to the project**" while trying to add WCF reference to https://webservice.nada.com/vehicles/secure/securelogin.asmx?WSDL 

Visual Studio Community 2017 - version 15.8.0 Preview 1.1

```
[31.05.2018 13:19:20.277] Adding Microsoft WCF Web Service Reference Provider to the project.
[31.05.2018 13:19:20.279] Importing web service metadata ...
[31.05.2018 13:19:20.401] Number of service endpoints found: 2
[31.05.2018 13:19:20.464] Scaffolding service reference code ...
[31.05.2018 13:19:25.183] Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.
[31.05.2018 13:19:25.216] Done.
[31.05.2018 13:19:25.234] Failed adding Microsoft WCF Web Service Reference Provider to the project.
```

Any thoughts how to fix / workaround this?

Related to #[2214](https://github.com/dotnet/wcf/issues/2214#issuecomment-393488704) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by dmitry-pavlov** [comment]
**Workaround**

As adding Microsoft WCF Web Service Reference using WSDL does not work for ASP.NET Core project you can add new .NET Standard class library project targeted to Standard 2.0 and add service reference to it:

- Right click on project
- Select `Add` -> `Connected Service`
- In `Connected Services` window select `Microsoft WCF Web Service Reference Provider` 
- Specify WSDL details as described [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) 
- Add new library reference to your ASP.NET Core web application (targeted to .NET Core 2.1)

**NOTE**: This (impossibility to add WCF service directly to ASP.NET Core project) should be explicitly mentioned in the [documentation](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide).

**Comment by mlacouture** [comment]
Hi @dmitry-pavlov!
Thank you for reporting this issue.  However, this site is for documentation issues.  The feedback section of the product documentation tells where to report [product issues](https://github.com/dotnet/wcf/issues/new).  Do you mind reporting this issue in the dotnet/wcf site and add details like the steps you followed for creating the ASP.NET project, the project's target framework and any other information you can provide that helps us narrow down the issue?
thank you very much
Miguel Lacouture

**Comment by mairaw** [comment]
I can move this issue to that repo @mlacouture. Is that ok?

**Comment by mlacouture** [comment]
Yes @mairaw , thank you!

**Comment by mairaw** [comment]
Issue moved to [dotnet/wcf #2914](https://github.com/dotnet/wcf/issues/2914) via [**ZenHub**](https://www.zenhub.com/)
