### ISSUE TITLE
Nullable types

### ISSUE THREAD

**Issue by TomProcureur** [dotnet/docs#5706]
This does not work with nullable types unless you change the code:

                DataColumn dc = table.Columns.Contains(p.Name) ? table.Columns[p.Name] : table.Columns.Add(p.Name, p.PropertyType);

with:

 DataColumn dc = table.Columns.Contains(p.Name) ? table.Columns[p.Name] : table.Columns.Add(p.Name, Nullable.GetUnderlyingType(p.PropertyType) ?? p.PropertyType);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd6b5c5-3266-0a2f-e535-d983fc0e5610
* Version Independent ID: 98956973-e9bc-c8a1-c356-1505d318a129
* Content: [How to: Implement CopyToDataTable<T> Where the Generic Type T Is Not a DataRow](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/implement-copytodatatable-where-type-not-a-datarow)
* Content Source: [docs/framework/data/adonet/implement-copytodatatable-where-type-not-a-datarow.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/implement-copytodatatable-where-type-not-a-datarow.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by pietervdheijden** [comment]
Great, this fixed my code! I'd suggest to modify the snippets on this page accordingly.
