### ISSUE TITLE
Latest stable .NET Core Application framework version inconsistent with .NET Blog

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#5708]
This page lists the latest stable version of .NET Core Application as 2.0. However, the .NET Blog [lists it as 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/).

This page does list `netcoreapp2.1` as a supported target framework version, just not a stable one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @breyed for the feedback. We still have a few changes we have to make throughout the docs for the 2.1 release (https://github.com/dotnet/docs/projects/34).

I've opened a PR to fix this: #5716
