### ISSUE TITLE
Mention 32 bit registry redirection on 64 bit WIndows

### ISSUE THREAD

**Issue by dmitryTsarevich** [dotnet/docs#5710]
To mention 32 bit applications on Windows 64 bit, .NET Framework version keys for 32 bit applications are located at HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\... subkey. May be helpful to add a note, since it looks crazy when you debug unit test for 32 bit installer on 64 bit WIndows, change .NET version in registry under Windows 64 and still get old value in unit test (because under the hood Windows registry access redirected to 32 bit part via WoW64).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_d)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
We'll need to investigate this @dmitryTsarevich. We're adding to our backlog.
