### ISSUE TITLE
Please help to eliminate confusion caused by "abstract" keyword

### ISSUE THREAD

**Issue by FrankHileman** [dotnet/docs#5711]
Recently I have noticed younger developers who have taken the "abstract" keyword to mean the same thing as "abstract" in computer science. The keyword, in retrospect, may have been a mistake, since it means unimplemented or incomplete, and has no correlation with the meaning of the word "abstract" in English. The real confusion comes when discussing abstraction levels. A data type is "more abstract" when it is higher in the inheritance hierarchy than another data type: it is "more abstract" because it is more of a generalization, which corresponds exactly to the traditional meaning of the word "abstract". Yet, I have encountered developers who believe a data type is "more abstract" if it has less implementation: an interface, or a base class with less members implemented. If you could do something to help mitigate this problem in the documentation, it would help people get back to the true meaning of the word "abstract" in technical discussions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c48990a-4edb-3e02-f7b7-36edb3eb91c5
* Version Independent ID: b93d07bb-44aa-04ef-4b60-0913cb9b1d2f
* Content: [Abstract and Sealed Classes and Class Members (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's an interesting point @FrankHileman. The best guidance I can take from this as I update our documentation is to be very clear about the meaning of the word abstract: To clearly differentiate the keyword `abstract` from the English word "abstract".

The keyword has exactly two meanings: An `abstract` type cannot be directly instantiated. An `abstract` method does not provide an implementation. Both meanings make sense in the context of the English word "abstract".  I think carefully applying the code style will help, as will discussing the concepts carefully.

I'll close this now. I think we are following the general guidance, and we will continue to do so. If you have specific examples that you think should change, re-open the issue and add notes here.
