### ISSUE TITLE
This document needs to be updated for .NET Core SDK 2.1

### ISSUE THREAD

**Issue by mltf** [dotnet/docs#5713]
I think this document needs to be updated for .NET Core SDK 2.1 which was released yesterday (2018.05.30)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @mltf, I think this document is still accurate even with the release of .NET Core 2.1 yesterday. There is no new version of .NET Standard. So I'll be closing this issue, but please let me know if I missed anything or if you have other questions.

**Comment by mltf** [comment]
The versioning is a bit confusing. 

Are you saying there is no .NET Standard 2.1? 

I was also reading up on it on https://github.com/dotnet/standard/issues/682 please let me know.

Thanks for the quick response.

**Comment by mairaw** [comment]
Yep, no new version of .NET Standard was released yet. The latest is still .NET Standard 2.0. I think that issue you linked to is a great place to ask questions regarding this since the devs and PMs working on the product monitor that repo.
