### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mqtwinter** [dotnet/docs#5714]
In the 2nd paragraph, the link to "language version selection" does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d38d8df-4919-e8c7-8126-e8c5c7300523
* Version Independent ID: b2284f21-547d-01f5-76a3-b531aab1a909
* Content: [What's new in C# 7.1](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#language-version-selection)
* Content Source: [docs/csharp/whats-new/csharp-7-1.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-1.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @mqtwinter. I've opened a PR to fix this: #5717
