### ISSUE TITLE
MakeCert examples

### ISSUE THREAD

**Issue by david-haemmerle** [dotnet/docs#5728]
MakeCert is deprecated. Please update this documentation and its examples to reflect that! Many thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416d3d78-0e61-097b-0bbe-c6cd331aa986
* Version Independent ID: 87242506-6036-9469-0166-0ae8890a96f8
* Content: [How to: Create Temporary Certificates for Use During Development](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development)
* Content Source: [docs/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-create-temporary-certificates-for-use-during-development.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This is related to #5619.

**Comment by mairaw** [comment]
I'll be closing to have just one work item related to this.

**Comment by mairaw** [comment]
Duplicate of #5619
