### ISSUE TITLE
Missing linux-musl-x64 RID

### ISSUE THREAD

**Issue by giggio** [dotnet/docs#5731]
As explained on the [.NET Alpine Sample](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile.alpine-x64-selfcontained, you can also use `linux-musl-x64` for Alpine as a runtime identifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Obrigada @giggio pelo feedback! I'm adding this update to the list of things we still need to do related to the 2.1 release: https://github.com/dotnet/docs/projects/34.

**Comment by tdykstra** [comment]
Fixed by #9008
