### ISSUE TITLE
Rephrase

### ISSUE THREAD

**Issue by thearunster** [dotnet/docs#5732]
The following sentence under LINQ and lambdas section can be rephrased for better clarity:

"Using Language-Integrated Query (LINQ) and lambda expressions is a great example of using productive features that you might later find you need to rewrite if the code becomes a significant impact on performance."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b87b64-6ecb-c03a-12a2-fac0d09e164e
* Version Independent ID: 8348b9cb-fe5f-cc9b-ae70-d2d61a10b530
* Content: [Writing Large, Responsive .NET Framework Apps](https://docs.microsoft.com/en-us/dotnet/framework/performance/writing-large-responsive-apps)
* Content Source: [docs/framework/performance/writing-large-responsive-apps.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/writing-large-responsive-apps.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sputier** [comment]
I just submitted a proposal for this issue 😄
