### ISSUE TITLE
Provide dotnet-install for .net core 2.1

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/docs#5736]
# Issue Title

The existing dotnet-install.* scripts appear to be out of date. 
Can you:
- update them for the latest release?
- provide documentation how to use the updated scripts?

Best regards

**Comment by JRAlexander** [comment]
@richlander, @leecow, can you answer this? Thanks!

**Comment by JRAlexander** [comment]
Hit close instead of comment.

**Comment by mairaw** [comment]
Actually, I need to work with @johnbeisner to update [that topic](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). When I was updating the SDK, I wasn't sure if there were changes for 2.1. 

/cc @KathleenDollard

**Comment by mmisztal1980** [comment]
I wanted to follow up on the issue, is there any activity in this area?

**Comment by KathleenDollard** [comment]
Looping in @johnbeisner

**Comment by mairaw** [comment]
@johnbeisner I'm out next week but can we work on this issue on the week of Aug-30?
