### ISSUE TITLE
Missing example?

### ISSUE THREAD

**Issue by TharosTheDragon** [dotnet/docs#5742]
First sentence in Data Conversion section: In the previous example, the button is red because its Background property is bound to a string property with the value "Red".

It's not at all clear what it means by the previous example and I don't see anything that contains the string "Red". I suspect the example it's referring to was modified or removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data Binding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview?view=netframework-4.7.2#data-conversion)
* Content Source: [docs/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-binding-overview.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks, @TharosTheDragon, we've added this to the backlog.
