### ISSUE TITLE
Property KeyData "gets the key data"?

### ISSUE THREAD

**Issue by bawkee** [dotnet/docs#5743]
Thanks to this documentation now I know that KeyData property provides me with data, something that I was unable to deduce based solely on the property name itself. Luckily someone from StackOverflow was kind enough to elaborate this beyond the plainly obvious fact that it is data: https://stackoverflow.com/a/318177/346577

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c2e0a3-d75f-f91c-a6ab-8f7e7202e190
* Version Independent ID: c9ba497d-48d5-426b-c1af-90af199613ca
* Content: [PreviewKeyDownEventArgs.KeyData Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.previewkeydowneventargs.keydata?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.PreviewKeyDownEventArgs.KeyData);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/PreviewKeyDownEventArgs.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/PreviewKeyDownEventArgs.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @bawkee. We've added this item to our backlog.
