### ISSUE TITLE
Alternative way of resizing the Height of the form

### ISSUE THREAD

**Issue by jonyeh** [dotnet/docs#5746]
Using the "this" Keyword  worked for me without having to create a new form:
this.Height = 760;
             

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7034cc03-e233-714b-5fc6-9562ced11d98
* Version Independent ID: c44e3792-805e-d883-7d31-fe5e54110255
* Content: [How to: Resize Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-resize-windows-forms)
* Content Source: [docs/framework/winforms/how-to-resize-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/how-to-resize-windows-forms.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @jonyeh. I think there are improvements that could be made to this topic (such as variables not following naming conventions, etc.)/ The use of the `this` keyword will depend on where you're accessing the Form object from. So yes, it does work if you're accessing the property from inside the class.
