### ISSUE TITLE
remark

### ISSUE THREAD

**Issue by conyg** [dotnet/docs#5750]
this will not work on this example:

```
public static T? GetValueOrNull<T>(this DbDataRecord reader, string columnName) where T : struct
{
	return reader[columnName] as T?;
}

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef3971f-1004-6aa5-9554-d8e2fcd6ac68
* Version Independent ID: e73efd1b-c26c-c1f0-6018-02f11261bb64
* Content: [using static Directive (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static)
* Content Source: [docs/csharp/language-reference/keywords/using-static.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-static.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hi @conyg 

the `using static` directive only imports static members for local scope that are **not** extension methods. It will however import those extension methods for use on the instance type they are defined for. 

I searched through the article for **extension** and found this:

>using static makes extension methods declared in the specified type available for extension method lookup. However, the names of the extension methods are not imported into scope for unqualified reference in code.
