### ISSUE TITLE
DangerousGetPinnableReference => GetPinnableReference

### ISSUE THREAD

**Issue by jskeet** [dotnet/docs#5767]
It looks like there was a late change to the method name used for the pattern - it's just `GetPinnableReference`, not `DangerousGetPinnableReference`. At least, that's what works for me, and it's the name in `Span&lt;T&gt;` in .NET Core 2.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0320fd-c7ac-200e-7e50-6b3ddcaa6a52
* Version Independent ID: 6ea1af7f-2251-f05f-4834-5a00e57fc5fb
* Content: [What's new in C# 7.3](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3)
* Content Source: [docs/csharp/whats-new/csharp-7-3.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-3.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jcouv I'm seeing the same change as of .NET 2.1 release. Can you confirm?

**Comment by jcouv** [comment]
That's correct. The name was simplified to `GetPinnableReference`.
I opened a [PR](https://github.com/dotnet/csharplang/pull/1605) to fix the speclet.
