### ISSUE TITLE
Extending existing Computation Expression Builders

### ISSUE THREAD

**Issue by ChrSteinert** [dotnet/docs#5769]
The page about F#'s [Computation Expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions) does currently not mention the possibilities of extending existing builders - a feature I was made aware of from [this issue](https://github.com/SaturnFramework/Saturn/issues/62) in Saturn talking about introducing new features to Saturn's `application` builder.

After some search I found [this presentation](https://panesofglass.github.io/computation-expressions/#/8/4) outlining the syntax of doing this.

I did not find this mentioned anywhere in the docs yet, but would gladly help creating this content.

**Comment by cartermp** [comment]
@ChrSteinert A new section in that article that does the equivalent of that slide should be sufficient, I'd think.

**Comment by ChrSteinert** [comment]
Thanks! I’ll prepare something.

________________________________
