### ISSUE TITLE
.NET Core support column

### ISSUE THREAD

**Issue by smmalis37** [dotnet/docs#5770]
It would would be nice to have another column listing which encodings are supported by .NET Core in addition to .NET Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e108a631-9747-7d6e-dc36-280b0591cd68
* Version Independent ID: f630aa07-55fd-5352-f0c3-bd2e263cd70b
* Content: [Encoding Class (System.Text)](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-2.0#feedback)
* Content Source: [xml/System.Text/Encoding.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text/Encoding.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks, @smmalis37, for your feedback. We'll address the issue of encoding support in our next sprint.

**Comment by rpetrusha** [comment]
Incidentally, @smmalis37, to see what encodings are available on .NET Core, you can call the [Encoding.GetEncodings](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings) method (.NET Core 2.0 and later). There is a description of supported encodings in the Platform Notes: .NET Core section of [Character Encoding in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding).
