### ISSUE TITLE
The "," Custom Specifier and a trailing static constant

### ISSUE THREAD

**Issue by megaskills** [dotnet/docs#5774]
It should be noted somewhere (as it's not obvious in the current markup) that you can append a static constant to the end of the "," Custom Specifier to further clarify the values expression after division. For example "#,##0,K" for thousands,  "#,##0,,M" for millions and "#,##0,,,B" for billions. Using an inline letter key for the scale can be handy data is displayed in columns and the header cell cannot be marked with a value indicating the scale similar to $(000's) or many other scale formats that are used in reporting. Example 1234567 "#,##0,K" displays 1,235K

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f543acea-d042-bbcf-5f83-de8b11644366
* Version Independent ID: 18c2ed9b-4015-109c-1ac2-b9b39ed19e8b
* Content: [Custom Numeric Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings)
* Content Source: [docs/standard/base-types/custom-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-numeric-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you so much for your feedback, @megaskills. You've identified a major shortcoming of the topic -- it doesn't discuss string literals (non-format characters) in the composite format string. We've scheduled work on this topic in the next sprint, which begins next week.

**Comment by megaskills** [comment]
Thanks Ron for the ultra prompt response, honestly I was not thinking I would hear from anybody, so thankyou.

By the way in most financial forms and reports I would use
“#,0,,,.000 B” or “#,0,,,.### B”

The 3 digit decimal places in accounting emphasizes the use of a scale. The scale could be K, M or B and the 3 decimal places simply calls out that the value has be scaled to the reader. (Also note the scaling commas come before the decimal places which is not that apparent in the current help article.)

If the header has room to show a scale as in “Revenue $(B)” then almost always I would use “#,0,,,.000” without the literal B, but if the header space was tight and could not fit a scale as in “Revenue $” I would chose to show the literal inline, and then I can dynamically reduce the decimal places based on the content value “#,0,,,.### B”. Because the B is inline, the reader does not need to see 3 decimals in every line.

This may be over kill for your help article, but it does demonstrate typical usage in finance teams of publicly listed corporations who prepare thousands of reports. The formatting of the numbers is critical as numbers often change scale between none, thousand (K), million (M), billion (B) in the same report.

Cheers
Peter

**Comment by rpetrusha** [comment]
Thanks, @megaskills. The financial examples are helpful. I'll try to use them as an example. I'll include you when the revision is ready for review so that you can take a look at it.
