### ISSUE TITLE
DocFX styling hides content

### ISSUE THREAD

**Issue by florinciubotariu** [dotnet/docs#5779]
The website that DocFX is serving is not showing the content correctly. 

For example, if I navigate to:

`http://localhost:8080/standard/choosing-core-framework-server.html`

the [following](https://imgur.com/a/zzIzbuJ) page is displayed.

If I delete the `<div>` that is having the `container` class, then the content is displayed correctly, as you can see [here](https://imgur.com/a/ytr2DbW).

**Comment by mairaw** [comment]
Thanks @florinciubotariu for your feedback. Given that this is not about the content, I've moved this issue to https://github.com/MicrosoftDocs/feedback/issues/415.
