### ISSUE TITLE
Clarify the ordering of items returned by `BlockingCollection<T>.GetConsumingEnumerable`

### ISSUE THREAD

**Issue by rigdern** [dotnet/docs#5780]
This doc and the API reference doc for `GetConsumingEnumerable` should clearly state how the order of the items returned by `GetConsumingEnumerable` is determined.

Currently, the API reference doc for `GetConsumingEnumerable` doesn't make any mention of this and this doc makes an ambiguous reference to this. This doc says: "There is no guarantee that the items are enumerated in the same order in which they are added by the producer threads."

Does that mean that `GetConsumingEnumerable` ignores the guarantees of `ConcurrentQueue` and `ConcurrentStack` and just returns items in some arbitrary order? Or is this sentence trying to say that `GetConsumingEnumerable` itself doesn't determine the order but instead the order is determined by the type of collection you use (e.g. `ConcurrentQueue`, `ConcurrentStack`)?

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8509dec-9d0f-1530-0d7a-a3ca9aa24c3e
* Version Independent ID: 1a5dfa73-b5cf-cff9-dec2-25e1868b2bd7
* Content: [How to: Use ForEach to Remove Items in a BlockingCollection](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-use-foreach-to-remove)
* Content Source: [docs/standard/collections/thread-safe/how-to-use-foreach-to-remove.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/how-to-use-foreach-to-remove.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@stephentoub can you help with these questions? We can make improvements to the docs if you think they are not clear.

**Comment by stephentoub** [comment]
> Or is this sentence trying to say that GetConsumingEnumerable itself doesn't determine the order but instead the order is determined by the type of collection you use (e.g. ConcurrentQueue, ConcurrentStack)?

Right.  The great thing about open source is that's easily verified :)
https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs#L1660-L1667

**Comment by JRAlexander** [comment]
Closing as it appears resolved. If this is not the case, then please reopen. Thanks!

**Comment by rigdern** [comment]
@JRAlexander, @mairaw can you reopen the issue? It looks like I don't have this capability.

We've figured out the answer to my question but I believe we should enhance the docs to better convey this information.

Adam Comella
Microsoft Corp.

**Comment by JRAlexander** [comment]
@rigdern, I just reopened.
