### ISSUE TITLE
Left menu and right menu taking too much space

### ISSUE THREAD

**Issue by rosdi** [dotnet/docs#5781]
Please allow us to toggle these left and right side bars... especially the right now... it is taking too much space...

Love the dark theme btw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b9c332-da26-ff62-8669-5697d5b9aa56
* Version Independent ID: 0049d705-a8ca-a4b5-c51d-b4f88bdf27e3
* Content: [Enumeration Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/enumeration-format-strings#feedback)
* Content Source: [docs/standard/base-types/enumeration-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/enumeration-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @rosdi. Since this is about the docs site experience, I've moved this issue to https://github.com/MicrosoftDocs/feedback/issues/414.

**Comment by AmmarTheTrainer** [comment]
yes its creating problem in reading the doc

**Comment by mairaw** [comment]
@AmmarTheTrainer please share your feedback on the active issue at https://github.com/MicrosoftDocs/feedback/issues/167. Thanks!
