### ISSUE TITLE
How to remove focus rectangle

### ISSUE THREAD

**Issue by programify** [dotnet/docs#5783]
If you simply want to remove the dotted focus rectangle, add Focusable="False" to &lt;Button&gt; or &lt;ContentControl&gt; elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e09d199-1d35-3c7a-1678-e6015c95b9ab
* Version Independent ID: 023c27dd-fd1c-f735-cc44-11e54a5106e6
* Content: [How to: Apply a FocusVisualStyle to a Control](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-apply-a-focusvisualstyle-to-a-control)
* Content Source: [docs/framework/wpf/advanced/how-to-apply-a-focusvisualstyle-to-a-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-apply-a-focusvisualstyle-to-a-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
That is a good suggestion @programify I've added this suggestion to our backlog.  Or, would you like to submit a PR for this change?
