### ISSUE TITLE
IF condition

### ISSUE THREAD

**Issue by BeJoNe** [dotnet/docs#5784]
If index &gt;= 5 And index &lt;= 8 Then....
please replace with "AndAlso" to bypass evaluating both expressions (binary AND-mode)
see https://stackoverflow.com/a/302067

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513d5fec-4fa8-511f-4472-0ef6f9582332
* Version Independent ID: 68efde66-3840-baf6-c25c-eaf18be9b11d
* Content: [For...Next Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/for-next-statement)
* Content Source: [docs/visual-basic/language-reference/statements/for-next-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/for-next-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for the suggested code optimization, @BeJoNe. I've opened PR #5787 to replace 'And' with "AndAlso'.
