### ISSUE TITLE
Example for Arraylist Add method and Arraylist AddRange method is same

### ISSUE THREAD

**Issue by bhasin123** [dotnet/docs#5785]
Example for Arraylist Add method and Arraylist AddRange method  is same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4617fa-8d54-5bac-cdc7-c35ee8c2ec56
* Version Independent ID: b6ce2cf7-fecd-09a2-2f1c-38598f49c98e
* Content: [ArrayList.Add(Object) Method (System.Collections)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.arraylist.add?view=netframework-4.7.2)
* Content Source: [xml/System.Collections/ArrayList.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections/ArrayList.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @bhasin123. Although the same example is used for both methods, it does illustrate calls to both the ArrayList.Add and ArrayList.AddRange methods. In addition, List<T> is the recommended alternative to the ArrayList class. In view of this, I'm going to close this issue; if you disagree, please feel free to respond. If you'd like to provide separate examples for the Add and AddRange methods, we'd welcome you're contribution.
