### ISSUE TITLE
An entry point cannot be marked with 'async' modifier

### ISSUE THREAD

**Issue by ithenash** [dotnet/docs#5786]
Main function in this example is incorrectly marked with 'async' modifier. Please make the corrections. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbd5007c-82e5-a0c1-2156-7df4bbbcc2da
* Version Independent ID: eba98e03-3cc2-bebe-3dcd-45eda9c9c378
* Content: [HttpClient Class (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **bobdel**

**Comment by BillWagner** [comment]
@ithenash Starting with C# 7.1, [async Main](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-7-1#async-main) is supported.

Closing this.

**Comment by mairaw** [comment]
@BillWagner the example in that page has no introduction, which is unusual. Maybe we should indicate you need C# 7.1 or higher for that code to compile?

**Comment by BillWagner** [comment]
That sounds like a good idea @mairaw 

I'd suggest linking to the anchor I referenced above.  I'll reopen and assign to me.

**Comment by BillWagner** [comment]
Fixed in dotnet/dotnet-api-docs#329
