### ISSUE TITLE
Can't consume existing .Net Framework WCF because it returns SOAP (MTOM)

### ISSUE THREAD

**Issue by acsteitz** [dotnet/docs#5790]
Used the tool to generate code.  Calling existing .Net Framework WCF endpoint and the call works but when trying to get the result I get an exception because the response is wrapped in a SOAP envelope.  I don't have control of the WCF endpoint so I cannot make changes there.  Any suggestions without using some of the hacks I have found online?  BTW, my main program is .Net Core 2.1 but the library I wrote to call the WCF is .Net Standard 2.0.

```
One or more errors occurred. (The content type multipart/related; type="application/xop+xml"; start="
&lt;http://tempuri.org/0&gt;"; boundary="uuid:53616ef9-df69-40d7-be67-3b954e4ce5af+id=255897";
start-info="text/xml" of the response message does not match the content type of the binding (text/xml; charset=utf-8).
If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 549 bytes of the response were: '
--uuid:53616ef9-df69-40d7-be67-3b954e4ce5af+id=255897 Content-ID:
    &lt;http://tempuri.org/0&gt;Content-Transfer-Encoding: 8bit Content-Type: application/xop+xml;charset=utf-8;type="text/xml"
        &lt;s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"&gt;
            &lt;s:Body&gt;
                &lt;Item xmlns="http://tempuri.org/"&gt;
                    &lt;ErrorMessage/&gt;
                    &lt;ExecutionSeconds&gt;0&lt;/ExecutionSeconds&gt;
                    &lt;ItemNo&gt;123456&lt;/ItemNo&gt;
                    &lt;Result&gt;true&lt;/Result&gt;
                &lt;/Item&gt;
            &lt;/s:Body&gt;
        &lt;/s:Envelope&gt;--uuid:53616ef9-df69-40d7-be67-3b954e4ce5af+id=255897-- '.)
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by mlacouture** [comment]
@acsteitz, can you open an issue at https://github.com/dotnet/wcf/issues/new as explained in the Feedback section of the doc?

**Comment by acsteitz** [comment]
Done
