### ISSUE TITLE
Link http://go.microsoft.com/fwlink/?LinkID=71255 is broken

### ISSUE THREAD

**Issue by pjanotti** [dotnet/docs#5791]
Not sure what is the correct location, same link is used in various others locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bcb7cc8-20a5-5816-dfdf-e9c7c69fe30c
* Version Independent ID: 28ef839c-641c-a6bf-b3e1-bcb650141763
* Content: [PackageRelationship Class (System.IO.Packaging)](https://docs.microsoft.com/en-us/dotnet/api/system.io.packaging.packagerelationship?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.IO.Packaging/PackageRelationship.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Packaging/PackageRelationship.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
As far as I can tell, the Open Packaging Conventions specification is part of [ECMA-376](https://www.ecma-international.org/publications/standards/Ecma-376.htm) and its latest version can be downloaded from https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fourth%20Edition,%20Part%202%20-%20Open%20Packaging%20Conventions.zip.

Unless there is a better link (ideally directly to the PDF file), I think that link could be used here.

**Comment by mairaw** [comment]
I just updated the link to point to https://www.ecma-international.org/publications/standards/Ecma-376.htm while we decided what needs to happen here.

**Comment by JRAlexander** [comment]
@mairaw, any updates on this? Thanks!
