### ISSUE TITLE
Banchmark of "Passing arguments by readonly reference"

### ISSUE THREAD

**Issue by ddobric** [dotnet/docs#5792]
I have tested performance of passing by reference when using [in] keyword. For tests I used BenchmarkDotNet. I used two methods AddByType and AddByRefType.
Expectation is that AddByRefType is faster, because structure value is passed by reference and no copy of bytes is performed.
I ran test on x64 machine. It means AddByType has to copy 24 bytes (3*double) and AddByRefType has to copy reference of 8 bytes.
Because of this difference I would expect higher performance of AddByRefType. Result shows that AddByRefType is slower. Notice mean value.

### The code:

```csharp
    MyStruct sStruct = new MyStruct() { X = 1.1, Y = 2.2 };

    [Benchmark]
    public void AddByType()
    {       
        add_by_type(sStruct);
    }

    [Benchmark]
    public void AddByRefType()
    {
        add_by_reftype(in sStruct);
    }

    public double add_by_type(MyStruct s)
    {
        return s.X + s.Y;
    }
    public double add_by_reftype(in MyStruct s)
    {
        return s.X + s.Y;
    }
```
### Results
```
BenchmarkTests.AddByType: Core(Runtime=Core)
Runtime = .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 0.2182 ns, StdErr = 0.0204 ns (9.34%); N = 92, StdDev = 0.1956 ns
Min = 0.0000 ns, Q1 = 0.0361 ns, Median = 0.1733 ns, Q3 = 0.3478 ns, Max = 0.8352 ns
IQR = 0.3117 ns, LowerFence = -0.4314 ns, UpperFence = 0.8153 ns
ConfidenceInterval = [0.1489 ns; 0.2875 ns] (CI 99.9%), Margin = 0.0693 ns (31.78% of Mean)
Skewness = 0.81, Kurtosis = 3.05, MValue = 3.93
-------------------- Histogram --------------------
[-0.002 ns ; 0.074 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 0.074 ns ; 0.178 ns) | @@@@@@@@@@@@@@@@@@
[ 0.178 ns ; 0.280 ns) | @@@@@@@@
[ 0.280 ns ; 0.355 ns) | @@@@@@@@@@@@@@@@@
[ 0.355 ns ; 0.444 ns) | @@@@@@@@
[ 0.444 ns ; 0.528 ns) | @@@
[ 0.528 ns ; 0.604 ns) | @@@@@
[ 0.604 ns ; 0.651 ns) |
[ 0.651 ns ; 0.727 ns) | @@
[ 0.727 ns ; 0.797 ns) |
[ 0.797 ns ; 0.873 ns) | @
---------------------------------------------------

BenchmarkTests.AddByRefType: Core(Runtime=Core)
Runtime = .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 0.2893 ns, StdErr = 0.0406 ns (14.04%); N = 98, StdDev = 0.4019 ns
Min = 0.0000 ns, Q1 = 0.0000 ns, Median = 0.0719 ns, Q3 = 0.5040 ns, Max = 1.3790 ns
IQR = 0.5040 ns, LowerFence = -0.7560 ns, UpperFence = 1.2600 ns
ConfidenceInterval = [0.1515 ns; 0.4271 ns] (CI 99.9%), Margin = 0.1378 ns (47.63% of Mean)
Skewness = 1.26, Kurtosis = 3.26, MValue = 2.54
-------------------- Histogram --------------------
[0.000 ns ; 0.152 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[0.152 ns ; 0.308 ns) | @@@@@@@@@@@
[0.308 ns ; 0.419 ns) | @
[0.419 ns ; 0.571 ns) | @@@@@@@
[0.571 ns ; 0.707 ns) | @@
[0.707 ns ; 0.894 ns) | @@@@@@@@
[0.894 ns ; 1.064 ns) | @@@
[1.064 ns ; 1.277 ns) | @@@@@@
[1.277 ns ; 1.455 ns) | @@@
---------------------------------------------------
```

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef84d483-1591-6ea4-83a7-fd3c2b1f081b
* Version Independent ID: 0b7f8ccd-a529-430d-416b-03480ea4883f
* Content: [Reference semantics with value types](https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types?view=netcore-2.1#ref-struct-type)
* Content Source: [docs/csharp/reference-semantics-with-value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/reference-semantics-with-value-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@ddobric what is the definition of `MyStruct`? Is it `readonly struct`?

[The ‘in’-modifier and the readonly structs in C#](https://blogs.msdn.microsoft.com/seteplia/2018/03/07/the-in-modifier-and-the-readonly-structs-in-c/) blogpost might be interesting to you. One of its conclusions is
> you should never pass a non-readonly struct as `in` parameter

**Comment by BillWagner** [comment]
@ddobric I used your benchmarks with three different definitions of `MyStruct`. The results illustrate the point @pkulikov makes in his comment.

First, I used this definition. The properties are implemented as methods, and (in theory), the getters could mutate the struct:

```csharp
public struct MyStruct
{
    public double X { get; set; }
    public double Y { get; set; }
    public double Z { get; set; }
}
```

That produces results similar to what you report above:

```console
       Method |      Mean |     Error |    StdDev |
------------- |----------:|----------:|----------:|
    AddByType | 0.3071 ns | 0.0428 ns | 0.0458 ns |
 AddByRefType | 1.5721 ns | 0.1044 ns | 0.1026 ns |
```

Next, I updated `MyStruct` to be a readonly struct:

```csharp
    public readonly struct MyStruct
    {
        public double X { get; }
        public double Y { get; }
        public double Z { get; }

        public MyStruct(double x, double y=0, double z=0) => (X, Y, Z) = (x, y, z);
    }
```

The version of `MyStruct` produces these results:

```console
       Method |      Mean |     Error |    StdDev |    Median |
------------- |----------:|----------:|----------:|----------:|
    AddByType | 0.3527 ns | 0.0430 ns | 0.0752 ns | 0.3070 ns |
 AddByRefType | 0.2939 ns | 0.0044 ns | 0.0039 ns | 0.2937 ns |
```

> For this benchmark test, the initialization of `sStruct` must change to `new MyStruct(1.1, 2.2);`

This version of `MyStruct`, where the compiler can verify that calling the get accessor cannot mutate the struct, shows that the by ref version is somewhat faster.

Finally, I changed `MyStruct` to contain public fields:

```csharp
    public struct MyStruct
    {
        public double X;
        public double Y;
        public double Z;
    }
```

That produces these results:

```console
       Method |      Mean |     Error |    StdDev |
------------- |----------:|----------:|----------:|
    AddByType | 0.3066 ns | 0.0132 ns | 0.0110 ns |
 AddByRefType | 0.3003 ns | 0.0095 ns | 0.0084 ns |
```

Note that these are similar to the `readonly` struct.

The interesting rule for defensive copies is in this line:

```csharp
return s.X + s.Y;
```

That will create 2 defensive copies: one to access `X` and one to access `Y`. 

We should explain this key facet to using the `in` modifier. (It's there, but not as prominent as it should be).

/cc @VSadov for review.
