### ISSUE TITLE
C# tutorials - structs

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#58]
Should cover the syntax and usage of structs in C#, including the differences between structs and classes.  Should provide guidance on when to use structs over classes (and vice/versa).

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BillWagner** [comment]
I’d recommend expanding the tutorial on structs to discuss the design guidelines on when to choose which.

**Comment by cartermp** [comment]
@BillWagner yep.  Done!
