### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by okarpov** [dotnet/docs#5800]
What order for the enumerated files? Are they ordered by Datetime or by Name or?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb986edc-b982-72fc-a747-f632e1753b37
* Version Independent ID: 61afaa43-8302-83d3-7cc4-da956574bceb
* Content: [Directory.EnumerateFiles Method (System.IO)](https://docs.microsoft.com/en-gb/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.7.1#System_IO_Directory_EnumerateFiles_System_String_System_String_System_IO_SearchOption_)
* Content Source: [xml/System.IO/Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Directory.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
The order of files is not guaranteed when you use this method. You could use the results of this method in a LINQ query to sort by name.

Closing as the order is not specified by the API, and the doc reflects that.
