### ISSUE TITLE
Should `VersionAdded` be used?

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/docs#5801]
This page says _"Always set the VersionAdded property"_.
But the doc of [VersionAdded](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.optionalfieldattribute.versionadded) says _"This property is unused and is reserved"_.
Please update the wrong one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9378f9b-e83c-4841-e532-6f62b7cfe9a5
* Version Independent ID: 6d88cc8f-d936-7d47-0c67-222abb6a2771
* Content: [Version tolerant serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/version-tolerant-serialization)
* Content Source: [docs/standard/serialization/version-tolerant-serialization.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/version-tolerant-serialization.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@paolofulgoni Thanks for bringing this up! 

CC @pjanotti @joperezr

I played around testing things and I can't seem to get `XmlSerializer`, `DataContractJsonSerializer`, or `BinaryFormatter` to use the `OptionalField` attribute at all. Is this something that really is fully deprecated? I also did a source search for `OptionalField` and didn't really find it used either.

Should https://docs.microsoft.com/en-us/dotnet/standard/serialization/version-tolerant-serialization be marked as applies to some older version of .NET only? It seems the serialization is pretty tolerant in its current state.

**Comment by pjanotti** [comment]
I don't know the exact history here but it should be up to the implementation of serializers if they are going to use the attribute or not. I see it being used at:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectInfo.cs#L638-646

the statement "it's important to set this property correctly to ensure that the type will be compatible with future serialization engines." seems correct, that said, it may not matter for most existing/modern serializers.

@ViktorHofer may know something about the history here.

**Comment by ViktorHofer** [comment]
Right, VersionAdded was introduced to be able to add fields to already serializable types and don't loose backcompat. If you add a field without the `OptionalFieldAttribute` the serialization engine will throw if that field is unexpected. I believe VersionAdded was introduced to indicate in which **version of the type** the field was added. I don't believe that we currently use the VersionAdded number, maybe there were plans to use it, but currently we don't (just speaking about BinaryFormatter -> System.Runtime.Serialization.Formatters).

**Comment by Thraka** [comment]
Ahh I think the `!_isSimpleAssembly` check is why I can't get it to throw no matter what I did.

**Comment by ViktorHofer** [comment]
Correct! :)
