### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by bp-brainiak** [dotnet/docs#5802]
there must add the C:\Windows\Microsoft.NET\Framework\v4.0.30319\SQL\en\SQL to the path 

cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df8da82-d4dc-9d98-dad2-aa44be3ca125
* Version Independent ID: 4e42da0c-d227-3e41-ad5e-e771c744e2c5
* Content: [How to: Create and Run a Long Running Workflow](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-create-and-run-a-long-running-workflow#feedback)
* Content Source: [docs/framework/windows-workflow-foundation/how-to-create-and-run-a-long-running-workflow.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/how-to-create-and-run-a-long-running-workflow.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Closing as this does not appear reproducible. Our path is at "C:\Windows\Microsoft.NET\Framework\v4.0.30319\SQL\en\"  . If this is not the case, then please reopen. Thanks!
