### ISSUE TITLE
 new TextLoader<TaxiTrip>(_datapath, useHeader: true, separator: ",") don't compile

### ISSUE THREAD

**Issue by GlauberCoder** [dotnet/docs#5810]
I believe that he should be replaced by:
new TextLoader(_datapath).CreateFrom&lt;TaxiTrip&gt;(useHeader: true, separator: ',')

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York Taxi Fares (Regression)](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare#prerequisites)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks,@GlauberCoder! We need to update this tutorial for version .2 which was just released.
