### ISSUE TITLE
System.InvalidOperationException: vendor_id is not alphanumeric.

### ISSUE THREAD

**Issue by GlauberCoder** [dotnet/docs#5811]
Getting this exceptions, Am I missing something?
Unhandled Exception: System.InvalidOperationException: vendor_id is not alphanumeric.
   at Microsoft.ML.Data.TextLoader.CreateFrom[TInput](Boolean useHeader, Char separator, Boolean allowQuotedStrings, Boolean supportSparse, Boolean trimWhitespace)
   at FinanceRegressionPredictor.Program.Train() in c:\users\glauber\source\repos\FinanceRegressionPredictor\FinanceRegressionPredictor\Program.cs:line 23
   at FinanceRegressionPredictor.Program.Main(String[] args) in c:\users\glauber\source\repos\FinanceRegressionPredictor\FinanceRegressionPredictor\Program.cs:line 18
   at FinanceRegressionPredictor.Program.&lt;Main&gt;(String[] args)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York Taxi Fares (Regression)](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare#prerequisites)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Oi @GlauberCoder! Is this your own code or did you find it somewhere else? It doesn't seem like the code from the tutorial.

**Comment by GlauberCoder** [comment]
Hello, the error came from my own code, but I'm just copying exactly the tutorial, it seem to be all the same to the given example except for a line in the data load that I had to change, because the given example does not compile anymore.

**Comment by mairaw** [comment]
Did you use our code from here?
https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/TaxiFarePrediction 

For product questions about ML.NET, you can also use the [dotnet/machinelearning](https://github.com/dotnet/machinelearning) repo.

**Comment by aditidugar** [comment]
hey @GlauberCoder and @mairaw thanks for your comments! We've just released v0.2 of the Microsoft.ML package a few hours ago and there are a couple of updates we will have to make to the tutorials here.

For now, check out [this samples repo](https://github.com/dotnet/machinelearning-samples) for the most up to date samples.

**Comment by GlauberCoder** [comment]
Thank you, I will try it.

**Comment by OliaG** [comment]
Fixed in the latest version

**Comment by mairaw** [comment]
I was also telling @aditidugar that we should improve that error message 😊
