### ISSUE TITLE
Provide link to MS Test documentation on the Unit testing C# with MSTest and .NET Core page.

### ISSUE THREAD

**Issue by lukkhacoder** [dotnet/docs#5812]
Add a link to MS Test documentation after or in the `Adding more features` section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest#adding-more-features)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That's a good suggestion @lukkhacoder. @gewarren @ghogen do you know where that content lives?

**Comment by gewarren** [comment]
Something like this page? https://docs.microsoft.com/en-us/visualstudio/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests

Or the API ref docs? https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting?view=mstest-net-1.3.2
