### ISSUE TITLE
add logging to the sample TestMethod

### ISSUE THREAD

**Issue by rajanikanthr** [dotnet/docs#5815]
adding logging would help as Console.WriteLine , Debug.WriteLine doesn't work
update: working fine in VS 2017 test output but not vs code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by binki** [comment]
This sounds like a VS Code bug rather than a documentation issue.
