### ISSUE TITLE
Catch exception thrown inside a child Task from parent

### ISSUE THREAD

**Issue by athanasiosem** [dotnet/docs#5816]
Please provide an example on how to catch an exception thrown by an async task.

e.g.

        public static Task Task1()
        {
            throw new OperationCanceledException();
        }

        private async void Main()
        {
            try
            {
                // Await the task.
                await Task1();
            }
            catch (Exception exc)
            {
                MessageBox.Show(exc.Message);
            }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by volkan-yazilim** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch#example-2
