### ISSUE TITLE
This still works

### ISSUE THREAD

**Issue by NeilMJohnson** [dotnet/docs#5818]
I just upgraded to a new development system, still using VS 2010 with very wide screens and all of my forms were screwing up and throwing split container errors.  Applying the above registry fix cleaned up the problem, thanks.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9b977f-c58f-1cd4-a146-5246723932ef
* Version Independent ID: b615485b-d573-7ba1-62db-be2ad27d0a48
* Content: [Automatic Scaling in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/automatic-scaling-in-windows-forms)
* Content Source: [docs/framework/winforms/automatic-scaling-in-windows-forms.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/automatic-scaling-in-windows-forms.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by todduk** [comment]
The article does not discuss registry changes.

**Comment by mairaw** [comment]
@todduk we have since removed the registry change. @OliaG can you comment on this issue? Should we close this or do we want to add some additional information to the topic?

**Comment by OliaG** [comment]
Registry change is not a suggested way of fixing that problem since the feature is not officially published to external users and supported. In the next release 15.8 we will have a solution for that issue in Visual Studio. Meanwhile it's up to you if you prefer to update the registry key, but we are not going to promote this solution in the docs.

**Comment by mairaw** [comment]
Thanks @OliaG. I'll close this one as by-design then. We can document the new feature then once it's out.
