### ISSUE TITLE
The suggest for C# return 

### ISSUE THREAD

**Issue by infinitylight** [dotnet/docs#5822]
Er,I think “The return statement terminates execution of the method in which it appears and returns control to the calling method.”change to"The return statement terminates execution of the method in which it appears and returns control to the statement that  calling method."will be better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf2e265-0377-a0a3-f2b3-bc4a8dcfdd40
* Version Independent ID: 9d0aeb19-1545-8a3b-3aa6-f0cb9f3b9006
* Content: [return (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/return)
* Content Source: [docs/csharp/language-reference/keywords/return.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/return.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JohnCOsborne** [comment]
Your proposed correction is redundant. The calling method is a statement.

**Comment by BillWagner** [comment]
@infinitylight Thanks for making this suggestion. However, the suggested addition does not add any clarity to the description of the `return` statement.

I'm closing this issue. If you disagree, you can reopen and add more information about your suggestion.
