### ISSUE TITLE
Cannot understand sentence - and why is it here?

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#5827]
The remark "This API supports the product infrastructure and is not intended to be used directly from your code."  is hard to understand. What is "the product infrastructure"? If uses shouldn't use the class, why is it even available?

And why is the sentence in this page? I would assume it refers to the entire class FolderNameEditor.FolderBrowser rather then just this enum.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04021153-472b-3f8a-3100-cf2eefeb9bca
* Version Independent ID: b0b61b3a-50fe-389f-e403-19aa27d573b9
* Content: [FolderNameEditor.FolderBrowserStyles Enum (System.Windows.Forms.Design)](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowserstyles?view=netframework-4.7.1)
* Content Source: [xml/System.Windows.Forms.Design/FolderNameEditor+FolderBrowserStyles.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/FolderNameEditor+FolderBrowserStyles.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for asking the question, @ptoye. The text means that, although a type or type member is publicly exposed, it is not intended for use other than by the .NET runtime or .NET class libraries; in other words, if you use it, you do so at your own risk. There are a number of reasons that types or their members are marked internal-only, including the need to access them from other assemblies and code changes between prerelease and release versions of .NET libraries. 

Your question about marking the FolderNameEditor.FolderBrowserStyles enumeration as internal-only but not marking either the FolderNameEditor.FolderBrowser class or the FolderNameEditor.FolderBrowser.Style property as internal-only is a good one. @SamBent, do you know whether the documentation is in error. That is, is [FolderNameEditor.FolderBrowserStyles](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowserstyles) actually for internal use only, or is either the [FolderNameEditor.FolderBrowser](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowser) class or the [FolderNameEditor.FolderBrowser.Style](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowser.style?view=netframework-4.7.1#System_Windows_Forms_Design_FolderNameEditor_FolderBrowser_Style) property intended for internal use only?

**Comment by SamBent** [comment]
That’s a question for WinForms (not WPF).

**Comment by rpetrusha** [comment]
Sorry, @SamBent. @merriemcgaw, do you know whether [FolderNameEditor.FolderBrowserStyles](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowserstyles) is actually for internal use only, or whether either the [FolderNameEditor.FolderBrowser](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowser) class or the [FolderNameEditor.FolderBrowser.Style](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.forms.design.foldernameeditor.folderbrowser.style) property is intended for internal use only?

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik do you know off the top of your head?

**Comment by ptoye** [comment]
Thanks all for the comments. As a mere .NET amateur I shall keep well away from this class!

**Comment by Tanya-Solyanik** [comment]
@ptoye  - consider using System.Windows.Forms.FolderBrowserDialog in a stand alone app

**Comment by ptoye** [comment]
Tanya - I tried using System.Windows.Forms.FolderBrowserDialog but it has a major design fault which I have logged at https://developercommunity.visualstudio.com/content/problem/266552/folderbroswerdialog-does-not-allow-arbitrary-start.html

That's why I was poking around for a better solution. Do you know of one?
