### ISSUE TITLE
Missing Single(x=>x.Prop == 123)

### ISSUE THREAD

**Issue by Lechus** [dotnet/docs#5828]
With Select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a44517-d9a2-454d-90f3-90d9553ff4be
* Version Independent ID: f31a6959-8212-a49f-eeb4-43936dbfbadb
* Content: [Data Transformations with LINQ (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/data-transformations-with-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Lechus I've looked over the source document you reference, and I need more detail about your issue. What do you think should be added to this article. Can you elaborate on what you mean here?

**Comment by BillWagner** [comment]
@Lechus I'm closing this due to the lack of a response. If you want to re-open with more information, we'll take another look.
