### ISSUE TITLE
Static Classes in C#

### ISSUE THREAD

**Issue by DJN1** [dotnet/docs#5833]
When I use a static class, how does it get loaded into memory. Because if it is not in memory it cannot be called. So basically my question is when does a static class get loaded into memory and when is it released from memory, in other words, what is the full life-cycle of a static class in C#?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f
* Version Independent ID: de2dac73-e810-dd42-f518-e50926b3747f
* Content: [Static Classes and Static Class Members (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@DJN1 When you say "when does a static class get loaded into memory?" do you mean the executable code for the class, or the static data members for the class?  

The code is loaded when the assembly containing it is loaded. The static data is initialized [following the same rules as static data in all classes](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors)

**Comment by DJN1** [comment]
What I mean is at what point in the execution of the code is memory allocated for the static classes, and when is that memory released again?

**Comment by BillWagner** [comment]
Thanks for the clarification @DJN1 

A static class can only contain static fields. The rules for allocating the memory follows the rules for static fields in **any** type, in the article I referenced in my earlier comment. Or, the C# language specification on [static constructors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#static-constructors) also contains that information.

Note that if a static class does not contain any static data members, memory doesn't need to be allocated.

This is covered in the docs, so closing.
