### ISSUE TITLE
poor

### ISSUE THREAD

**Issue by PinkoAgrawal** [dotnet/docs#5834]
Why I always think that Microsoft's documents useless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac4b6bb-c5d4-8ef9-7785-82d6f399e8c6
* Version Independent ID: 8848fa84-4853-175d-5408-9e2e3af33d0b
* Content: [How to: Create and Bind to an ObservableCollection](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection)
* Content Source: [docs/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
Why exactly do you find that article "poor" or "useless"?

**Comment by mairaw** [comment]
Hi @PinkoAgrawal! As @svick pointed out, please let us know what you didn't like about the article or what you were expecting to find.

**Comment by PinkoAgrawal** [comment]
@svick I was looking for OnPropertyChanged event as I was developing expandable listview. When I couldn't find that I commented so & this is not an isolated incident when I didn't get proper information.

**Comment by dclack** [comment]
This sample doesnt work. Has anyone been able to make it work? I am using VS 2017
