### ISSUE TITLE
_testdatapath field never used, should be used in Evaluate method

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/docs#5841]
The field _testdatapath is never used. Guessing you intended to use it instead of _datapath in this line of Evaluate, so that you're testing with a different dataset from what you trained with:
var testData = new TextLoader(_datapath).CreateFrom&lt;TaxiTrip&gt;(useHeader: true, separator: ',');

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@danvanderboom that's a good catch! Thanks for reporting it. The dotnet/samples#119 PR fixes the issue.
