### ISSUE TITLE
Unit Testing With NUnit incorrectly states that `dotnet new nunit` will generate a project

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/docs#5846]
The article about [unit testing with nunit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit) states that "[you can] create a new project using `dotnet new nunit`."

This [is not the case](https://github.com/nunit/dotnet-new-nunit/issues/11) though I suspect this is a bug in `dotnet-new-nunit`.

This is frustrating as a consumer following official documentation.

**Comment by halex2005** [comment]
It turns out, that it's a temporary regression, introduced in NUnit3.DotNetNew.Template v1.5.0 (item templates has been added). 
I'll investigate the issue and hopefully fix this soon.

**Comment by halex2005** [comment]
Do not need to change the docs.
https://github.com/nunit/dotnet-new-nunit/issues/11

Issue fixed in `NUnit3.DotNetNew.Template v1.5.1`. This issue can be closed.

**Comment by Phrohdoh** [comment]
Awesome! Thanks for the quick response and fix @halex2005!
