### ISSUE TITLE
"dotnet publish" is uninstalling package from application and then exiting saying it can't find the package it removed....

### ISSUE THREAD

**Issue by wengera** [dotnet/docs#5852]
So I am using asp.net core with Angular 4.2.5 and I run the following commands before publishing:
- dotnet restore
- dotnet build
- dotnet publish

When I run "dotnet publish" it runs for about a minute and then it removes "ngx-bootstrap" from my project and then it exits telling me it was "unable to find "ngx-bootstrap". I have no clue what to do as I have to reinstall ngx-bootstrap every single time it does this as my project won't run without it but when i try to publish the project it gets removed and the publish process fails because it can't find the package it removed.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @wengera, since this is a product question, I suggest you file a new issue at https://github.com/dotnet/cli/issues. If you find out after talking to the product team that our content needs improvement based on this particular scenario, please let us know and feel free to reopen this issue.
