### ISSUE TITLE
Memory allocated by this method

### ISSUE THREAD

**Issue by atykhyy** [dotnet/docs#5855]
To go by the reference source, ordinal string comparers (`StringComparer.Ordinal` and `StringComparer.OrdinalIgnoreCase`) use an external function to compute the hash code which probably doesn't allocate any memory. If that is true, please reflect this in the docs so that people won't go off rolling their own ordinal case-insensitive hash functions to avoid memory allocation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7148ce-34e0-1395-af44-17ea4e673353
* Version Independent ID: 794144d8-a796-cbe4-cab1-eca8588ff1f9
* Content: [StringComparer.GetHashCode Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.gethashcode?view=netframework-4.7.1#System_StringComparer_GetHashCode_System_String_)
* Content Source: [xml/System/StringComparer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/StringComparer.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
The first paragraph is also inaccurate: converting from `object` to `string` does have some performance cost, but it does not involve unboxing.
