### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by kunkliricsi** [dotnet/docs#5856]
Shouldn't the commented Z's F function write out "Z.F" and not "C.F" in the first example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab10c9fd-cbf8-6889-eadc-34ce1999a592
* Version Independent ID: 2cc0bd61-62b3-f41f-d6a8-16ffdc049238
* Content: [sealed (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed#feedback)
* Content Source: [docs/csharp/language-reference/keywords/sealed.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/sealed.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Yes, the output should be "Z.F" instead of "C.F", @kunkliricsi. Thanks for pointing this out. We'll open a PR to correct this error shortly.
