### ISSUE TITLE
SqlFunctionAttribute.FillRowMethodName documentation is useless

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#5860]
docs needs more substance and example is wrong 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cceb80-b770-1e77-e343-a3dde207f4a4
* Version Independent ID: 9ddafb2e-865c-af9d-fa8e-5e0ab6e18731
* Content: [SqlFunctionAttribute.FillRowMethodName Property (Microsoft.SqlServer.Server)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.server.sqlfunctionattribute.fillrowmethodname?view=netframework-4.7.2#Microsoft_SqlServer_Server_SqlFunctionAttribute_FillRowMethodName)
* Content Source: [xml/Microsoft.SqlServer.Server/SqlFunctionAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.SqlServer.Server/SqlFunctionAttribute.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@douglaslMS can you take a look at this feedback?

**Comment by douglaslMS** [comment]
@SidShetye Thanks for bringing this to our attention. I've opened a PR to remove the code snippet which is for a different property, and to improve the description of the method itself. As you may have learned elsewhere, FillRowMethodName is "the name of the method in the same class which will be used to fill a row of data in the table returned by the TVF."

**Comment by SidShetye** [comment]
@douglaslMS there are still many things missing in order to make it functional. For example, what is the function signature for such a fill-row method? How are the inputs and outputs setup? What about the types for the inputs, outputs (`Sql**` types or native CLR types) etc.

IMHO currently it reminds me of a joke, where a lost man asks a pedestrian "I'm lost. You know where I am?" to which the pedestrian responds "You are 6 feet in front of me". Technically correct but practically not useful :)

**Comment by douglaslMS** [comment]
@sid Your request goes beyond the scope of the present article, which merely holds the name of such a function. This attribute is used when you're using SQL Server's CLR Integration to code a table-valued function in C#. Here's the most relevant article that gives you a more complete picture, including the use of this property in the SqlFunctionAttribute, and including a sample "fill row" method: [CLR Table-Valued Functions](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-table-valued-functions?view=sql-server-2017).
