### ISSUE TITLE
Naming conventions for UI - user interface

### ISSUE THREAD

**Issue by xmedeko** [dotnet/docs#5861]
Should we use `Ui` or `UI` as the abbreviation of the user interface? E.g. `ExecuteOnUiThread` or ExecuteOnUIThread` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eba6b11-5703-355f-0e85-08ee7451120d
* Version Independent ID: 4691fbb3-7b6d-8c02-e372-315ca302e48e
* Content: [Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)
* Content Source: [docs/standard/design-guidelines/capitalization-conventions.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/capitalization-conventions.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
This is covered by the following section of the docs:

> A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier:
> `IOStream`

Such as this namespace we have in .NET: [System.Web.UI](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui?view=netframework-4.7.2)

**Comment by xmedeko** [comment]
Thanks for the explanation.

Just note: examples from the .NET are not valid always. The .NET naming has changed over the years. E.g. **Id** vs **ID**:
`System.Threading.Thread.GetDomainID`
vs.
`System.Threading.Thread.CurrentThread.ManagedThreadId`
etc.

**Comment by mairaw** [comment]
@terrajobst and @KrzysztofCwalina to confirm the right convention. I know that we haven't always been consistent.

**Comment by KrzysztofCwalina** [comment]
"UI" just like "IO", i.e. the guideline is: two letter initialisms have both letters upper cased.
