### ISSUE TITLE
Enumeration classes (type-safe) pattern gender example

### ISSUE THREAD

**Issue by jmlane** [dotnet/docs#5862]
Hello,

Please consider removing reference to gender as a "closed set of values" for your Enum use case examples. It does not seem necessary given there is already another example (size), and it reinforces binary concepts of gender that are harmful to non-binary and genderqueer people.

Thank you for the content!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your candid feedback @jmlane! I agree with you. 

Would you like to contribute with a PR for that content? Otherwise, we'll take care of that for you.

**Comment by mairaw** [comment]
@jmlane I've created a PR to fix this: https://github.com/dotnet/docs/pull/5883
