### ISSUE TITLE
The example could be clearer

### ISSUE THREAD

**Issue by richardrob24** [dotnet/docs#5863]
The myText object is never declared so I don't really know what it is and therefore what kind of objects I could expect to find a SetBinding method on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12773004-4c9d-28a5-0967-6affc5738f05
* Version Independent ID: efa91ca6-243f-157b-cb41-bd93cb4b1679
* Content: [BindingExpression Class (System.Windows.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.bindingexpression?view=netframework-4.6.2)
* Content Source: [xml/System.Windows.Data/BindingExpression.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Data/BindingExpression.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnet-bot**

**Comment by richardrob24** [comment]
I just read the preceding paragraph and now I'm slightly embarrassed.

**Comment by rpetrusha** [comment]
There's nothing to be embarrassed about, @richardrob24. Many of us look at the code without reading the surrounding text. The code should have made it clear what the type of myText is. It's part of a larger (actually, a much larger) example, so only a small code fragment was shown.  I've opened a PR to add a comment to the code that indicates myText is a TextBlock control.

**Comment by richardrob24** [comment]
Looks good! thank you!
