### ISSUE TITLE
Simple examples would really help

### ISSUE THREAD

**Issue by amp64** [dotnet/docs#5864]
A real-world example would be
new  AuthenticationHeaderValue("Bearer", "a34552bd34")
(the made up 2nd argument is a token in this case).
A list of what kinds of schemes are acceptable would be handy, especially the 1-argument constructor which remains a mystery to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a1d8403-fd66-753a-19fa-ced80c78bfe1
* Version Independent ID: 507bdd8b-0a2c-1d08-881a-361673ae4f22
* Content: [AuthenticationHeaderValue Constructor (System.Net.Http.Headers)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.authenticationheadervalue.-ctor?view=netframework-4.7.1#System_Net_Http_Headers_AuthenticationHeaderValue__ctor_System_String_System_String_)
* Content Source: [xml/System.Net.Http.Headers/AuthenticationHeaderValue.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http.Headers/AuthenticationHeaderValue.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@davidsh @karelz can you comment on this feedback?

**Comment by davidsh** [comment]
>A list of what kinds of schemes are acceptable would be handy, especially the 1-argument constructor which remains a mystery to me.

Any string is acceptable as long as it complies with the RFC for the Authentication related headers such as 'Authorization:' and 'Proxy-Authorization'.  

See: https://tools.ietf.org/html/rfc7235

These request headers are not processed by the .NET HTTP client stack itself.  They are simpled sent with the request.
