### ISSUE TITLE
Broken link: Key Spline Animation Sample

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#5871]
The "Key Spline Animation Sample" link in this page is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53404393-0b6a-ce81-88fb-eea3d9eb3761
* Version Independent ID: a4a7fa11-829a-0544-24da-4f3a576b619f
* Content: [Timeline Class (System.Windows.Media.Animation)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.timeline?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Media.Animation/Timeline.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Media.Animation/Timeline.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Obrigada @MarcioAB. I've fixed the target URL for http://go.microsoft.com/fwlink/?LinkID=160011.
