### ISSUE TITLE
ValueChanged  should be onValueChanged in this documentation example

### ISSUE THREAD

**Issue by Katie-Van** [dotnet/docs#5872]
In the example at [](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/defining-an-event-in-windows-forms-controls#feedback)

`protected virtual void OnValueChanged(EventArgs e) {  
      if (ValueChanged != null) {  
         ValueChanged(this, e);  
      }  
   } `

Should be

`   protected virtual void OnValueChanged(EventArgs e) {  
      if (onValueChanged != null) {  
         onValueChanged(this, e);  
      }  
   } `

I think so, anyways. Just trying to learn how to do events

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b362ea-2a1f-2e31-5686-6375abe4987c
* Version Independent ID: 1165de6f-5d3c-bf72-50ea-4b1e1a0861d4
* Content: [Defining an Event in Windows Forms Controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/defining-an-event-in-windows-forms-controls#feedback)
* Content Source: [docs/framework/winforms/controls/defining-an-event-in-windows-forms-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/defining-an-event-in-windows-forms-controls.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That is actually correct @Katie-Van. I recommend you read more about events at this section of the docs: https://docs.microsoft.com/en-us/dotnet/standard/events/.

So closing this. But let us know if find other issues as you're trying to learn!
