### ISSUE TITLE
Unable to Reference Person Class

### ISSUE THREAD

**Issue by markdcarringer** [dotnet/docs#5873]
My instinct was to create the Person class, then make a reference to it in the XAML. This approach does not work. Visual Studio tells you, incorrectly, that "the name Person does not exist in the namespace clr-namespace:One_SimpleBinding". (I named my project One_SimpleBinding instead of SDKSample, which makes no difference here.) And Visual Studio will not build the project. I am running VS2017 Enterprise version 15.3.0. 

There are two workarounds for this issue: 
1. Reference the Person class in the XAML first, then add Person to the project. 
2. Drop and re-add the Person class. 

It might be helpful to add a note about adding the Person class after referencing it in XAML. Trying to fix this issue is a frustrating use of an hour. I imagine the issue will be fixed at some point, but it seems to have been around for awhile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0dae4f2-252b-dad2-8355-cac20a09c315
* Version Independent ID: 695ac494-103c-8a6e-b2ea-e66efa7ebfce
* Content: [How to: Create a Simple Binding](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-create-a-simple-binding)
* Content Source: [docs/framework/wpf/data/how-to-create-a-simple-binding.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-create-a-simple-binding.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by natejgardner** [comment]
@mairaw it'd be great to get this point documented in the example. It's still fairly confusing not having the Person class included in the example, especially since just creating the Person class then referencing it, which is the intuitive thing, doesn't work.

**Comment by mairaw** [comment]
I'll reopen this then @natejgardner and add this to our backlog.

**Comment by natejgardner** [comment]
@mairaw @dotnet/docs, the current doc (both .net 4.x and 5 versions) still has this issue - I think it will help a lot for learning WPF to add some clarity here.

**Comment by mairaw** [comment]
@adegeo please take a look
