### ISSUE TITLE
Value Options

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/docs#5885]
Did F# 4.5 add Value Options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1e23a2-091b-38be-3bbe-b3b38aa06aa5
* Version Independent ID: 431e250a-3588-7741-dd43-8021d6c7ffa8
* Content: [Options (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/options)
* Content Source: [docs/fsharp/language-reference/options.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/options.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Yes, but F# 4.5 is not available yet. The type is in the latest NuGet package, but the language is not considered released yet.

**Comment by brettrowberry** [comment]
Got it. Thanks, Phillip!

**Comment by cartermp** [comment]
NP. This and the other [FSharp.Core changes](https://github.com/fsharp/fslang-design/tree/master/FSharp.Core-4.5.0.0) will be documented fairly soon (i.e., within a few weeks or so).
