### ISSUE TITLE
what kind Socket handler have?

### ISSUE THREAD

**Issue by tinhpbk** [dotnet/docs#5889]
// Get the socket that handles the client request.  
        Socket listener = (Socket) ar.AsyncState;  
        Socket handler = listener.EndAccept(ar);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mairaw** [comment]
@tinhpbk can you elaborate your question? We're not sure what the request is.

**Comment by karelz** [comment]
I don't understand it either. No reply in ~3 months, closing.

**Comment by FloteFuertes** [comment]
Hi just new to network programming how can I include authentication using this sample? 
I am having hard time figuring it out. I am using X509Certificate to Authenticate with AuthenticateAsServer.

 Thank you
