### ISSUE TITLE
Optimal Degree of Dataflow Block Parallelism

### ISSUE THREAD

**Issue by OwenTrokeBillard** [dotnet/docs#5890]
What is the optimal degree of parallelism? Specifically, are there any caveats to parallelizing blocks that perform short-running computations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b80f0bf-7d7d-af0e-da2a-0331579ff66a
* Version Independent ID: 9a42a7e3-311a-b837-39b9-bf4c7e52bfd9
* Content: [How to: Specify the Degree of Parallelism in a Dataflow Block](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block)
* Content Source: [docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-specify-the-degree-of-parallelism-in-a-dataflow-block.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Psypher9** [comment]
Guidance on this would be very helpful!
