### ISSUE TITLE
Link to LocBaml tool is dead.

### ISSUE THREAD

**Issue by lpnam0201** [dotnet/docs#5892]
Is there anyway to obtain LocBaml tool ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4baeeb7d-bba4-c8c5-6f54-97dc68a59aef
* Version Independent ID: d248598d-5657-1a8c-3f91-b37384243eff
* Content: [WPF Globalization and Localization Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-globalization-and-localization-overview#feedback)
* Content Source: [docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @lpnam0201. I'll close this as a duplicate of #3623 since it's basically the same link. So once we figure out where we should link to, we'll change both topics.

**Comment by mairaw** [comment]
Duplicate of #3623
