### ISSUE TITLE
API doc: not correct display of the implemented interfaces

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5893]
The [ColumnCopier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.columncopier?view=ml-dotnet) doc displays implemented interfaces the following way:
![image](https://user-images.githubusercontent.com/15279990/41201963-27300dbe-6cc2-11e8-9aae-33e20d39633c.png)

Note the difference:
- The code snippet shows that two interfaces are implemented: `Microsoft.ML.ILearningPipelineItem` and  `Microsoft.ML.Runtime.EntryPoints.CommonInputs.ITransformInput`
- The **Implements** section has two duplicate entries both referencing to the same page of the [ILearningPipelineItem](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.ilearningpipelineitem?view=ml-dotnet).

**Comment by svick** [comment]
[It looks correct in the XML:](https://github.com/dotnet/ml-api-docs/blob/1b1e26d/dotnet/xml/Microsoft.ML.Transforms/ColumnCopier.xml#L14-L21)

```xml
  <Interfaces>
    <Interface>
      <InterfaceName>Microsoft.ML.ILearningPipelineItem</InterfaceName>
    </Interface>
    <Interface>
      <InterfaceName>Microsoft.ML.Runtime.EntryPoints.CommonInputs+ITransformInput</InterfaceName>
    </Interface>
  </Interfaces>
```

I think there could be two things that are confusing the system:

1. `ITransformInput` doesn't seem to be in the part of ML.NET that's included in API reference.
2. `ITransformInput` is nested in the `CommonInputs` class.

**Comment by JRAlexander** [comment]
@GalOshri - any insight? Thanks!

**Comment by mairaw** [comment]
Seems like this would also be a question to @dend and @TianqiZhang given the ECMAXML has the right information.

**Comment by mairaw** [comment]
I found a similar page to that one above and I think this doesn't repro anymore? Although that class is no longer nested so not sure if this is the best repro.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.legacy.transforms.nooperation?view=ml-dotnet

![image](https://user-images.githubusercontent.com/12971179/49485789-02be3900-f7f1-11e8-84bd-9e52a6c4e382.png)

**Comment by mairaw** [comment]
I'm closing this one. If you find a new repro, please let us know @pkulikov!
