### ISSUE TITLE
great documentation 

### ISSUE THREAD

**Issue by austinHeisleyCook** [dotnet/docs#5894]
I love the detailed documentation about linq.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7857551e-2454-b536-e44d-fb6b14413d5e
* Version Independent ID: 2826bd18-b9ae-38b1-5004-9e575203dfeb
* Content: [Introduction to LINQ Queries (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/introduction-to-linq-queries)
* Content Source: [docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @austinHeisleyCook We're glad you appreciate it.
