### ISSUE TITLE
CCW in .NET Core

### ISSUE THREAD

**Issue by ztl8702** [dotnet/docs#5895]
Is it possible to create CCW/RCW in .NET Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ac4bb2-b2de-4a64-badb-8ac9727370de
* Version Independent ID: ecbed103-cbdf-f602-45ad-3843dea554e5
* Content: [How to: Create COM Wrappers](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-create-com-wrappers#see-also)
* Content Source: [docs/framework/interop/how-to-create-com-wrappers.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/how-to-create-com-wrappers.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by AaronRobinsonMSFT** [comment]
@ztl8702 This is something we are currently working on - however support will be limited to .NET Core 3.0 on Windows only. Feel free to follow dotnet/coreclr#18640.

**Comment by AaronRobinsonMSFT** [comment]
cc @jkoritzinsky @jeffschwMSFT - looks like some documentation is needed 😄
