### ISSUE TITLE
Is memory for structure allocated in heap if use new key ?

### ISSUE THREAD

**Issue by r-k-pathak** [dotnet/docs#5896]
In value types, a struct is a special item which is eligible to be initialized using the new keyword with the parametrized constructor.
so if we use new keyword then memory allocation for struct takes place in heap or stack ?.
I am asking this because if we declare the structure inside the class then we can not  initialize it  by accessing it through instance of class for ex. 
&lt;instance of the Class&gt;.&lt;structure Name&gt;  , instead we  have to use like &lt;ClassName&gt;.&lt;Structurame&gt;.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a2eef-19ac-f7a3-a512-df2729412a53
* Version Independent ID: 1f413a9f-7129-df5c-e8fa-13647cc1caeb
* Content: [Using Structs (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-structs)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-structs.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-structs.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by r-k-pathak** [comment]
Any answers for above query.

**Comment by BillWagner** [comment]
@r-k-pathak I'm closing this based on the explanation provided above, and the lack of response.

If you have more information, reopen and add clarification.
