### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Parusov** [dotnet/docs#5899]
http://schemas.microsoft.com/ws/2008/06/identity/claims/role does not work for me and result in "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1597a0b7-494d-0cca-bc54-e432719d2256
* Version Independent ID: 17d1429f-ff5d-8f13-bdbd-b8147808305b
* Content: [Claims Based Authorization Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/claims-based-authorization-using-wif#feedback)
* Content Source: [docs/framework/security/claims-based-authorization-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/claims-based-authorization-using-wif.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Parusov. @brentschmaltz I don't know about to do about these WIF topics that are using these URLs. Can you please advise?

**Comment by brentschmaltz** [comment]
@Parusov @mairaw we are putting those docs to bed. The new model uses asp.net CORE and sometimes KATANA (OWIN)

**Comment by mairaw** [comment]
I'll see when we can get archival of docs published here to https://docs.microsoft.com/en-us/previous-versions/dotnet/, given we don't have another version of these docs we can just redirect to.

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
