### ISSUE TITLE
Necessary Settings in lanuch.json to Make VS Code Debugger Work

### ISSUE THREAD

**Issue by charliegdev** [dotnet/docs#5901]
I'm not sure how this works on macOS, but at least on Windows 10, I need to change some settings in `launch.json` to make VS Code's debugger work.

Locate the configuration with `"name"` of `".NET Core Launch (console)"`. Change the `"program"` field's value to:

```
"program": "${workspaceFolder}/app/bin/Debug/netcoreapp2.1/app.dll",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Getting started with .NET Core on macOS](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos#dotnet-restore-note)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
Thanks for pointing this out @charliegdev 

I've added it to our next sprint. In the meantime, if you want to submit a PR for this, I'll review it and merge it.

**Comment by afreeland** [comment]
I noticed this as well and your change is exactly the same change needed on macOS, nice work!

**Comment by yguo** [comment]
I work on macOS, and need to change the launch.json in the folder `.vscode` 
```
"program": "${workspaceFolder}/app/bin/Debug/netcoreapp2.1/app.dll",
