### ISSUE TITLE
How about using newer language constructs?

### ISSUE THREAD

**Issue by tsahi** [dotnet/docs#5903]
How about using syntax like

    protected virtual void OnShapeChanged(MyEventArgs e)  
    {  
        ShapeChanged?.Invoke(this, e);  
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797ea358-4ed7-9152-dc7e-f4911ce58068
* Version Independent ID: e43c69e0-e4f5-a171-72e8-1f1f2f6b71e9
* Content: [How to: Implement Interface Events (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-implement-interface-events)
* Content Source: [docs/csharp/programming-guide/events/how-to-implement-interface-events.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-implement-interface-events.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I agree that using C# 6.0 features in that example makes sense. Do you want to make that change?

**Comment by BillWagner** [comment]
Thanks for pointing this out @tsahi 

As @svick mentioned, we should be using the newer features. Several of our older examples predate those features. If you'd like to submit a PR to make the change, I'll watch for it and merge it.

**Comment by tsahi** [comment]
Sure, I'll try to get to this in a day or two.
