### ISSUE TITLE
Create an item template creation tutorial

### ISSUE THREAD

**Issue by scottaddie** [dotnet/docs#5904]
My past couple of conference talks have demonstrated creation of item templates and installing them with the .NET Core CLI. The feedback has clearly indicated that customers aren't aware this can be done. We should create a tutorial that walks through creating an item template, installing it with `dotnet new`, and using it. The creation instructions should show examples of if statements, loops, and token replacement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET Core CLI - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
@scottaddie should we update this [topic](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template) for this?

**Comment by scottaddie** [comment]
@mairaw I propose we add a new section, called "Create a template from a file", to that doc.

**Comment by Thraka** [comment]
I think that a part 4 could be created that gets into advanced templates such as token replacement and input parameters.

**Comment by scottaddie** [comment]
I created this issue so long ago that I no longer remember. I do, however, think that your proposed part 4 would be a useful addition.
