### ISSUE TITLE
--version-suffix description is incorrect

### ISSUE THREAD

**Issue by seangwright** [dotnet/docs#5911]
The description is `Defines the version suffix for an asterisk (*) in the version field of the project file. The format follows NuGet's version guidelines.`.

Testing with the .NET CLI v2.1 I get errors like the following when including an (`*`) anywhere in my `<Version></Version>` element in my `.csproj`

`'*' is not a valid version string.`

I have tried the following in my `.csproj`

`<Version>1.0.0-*</Version>`
`<Version>1.0.0.*</Version>`
`<Version>*</Version><VersionPrefix>1.0.0</VersionPrefix>`

using the command `dotnet build .\PathTo.csproj --version-suffix abc` which works correctly if I only have `<VersionPrefix></VersionPrefix>` or if I do not have (`*`) in my `<Version></Version>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@livarcocc @KathleenDollard @dsplaisted can one of you help with this question? Should I simply change the description for all SDK versions to what we have in --help ("Defines the value for the $(VersionSuffix) property in the project")? Anything else we can say about that option?

**Comment by dsplaisted** [comment]
The simplest fix to the docs would be just to change it to what is in the command line help.

However, if we want to do better, here's the [actual logic](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultAssemblyInfo.targets) for how the Version is set:

```xml
  <PropertyGroup Condition=" '$(Version)' == '' ">
    <VersionPrefix Condition=" '$(VersionPrefix)' == '' ">1.0.0</VersionPrefix>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionPrefix)-$(VersionSuffix)</Version>
    <Version Condition=" '$(Version)' == '' ">$(VersionPrefix)</Version>
  </PropertyGroup>
```

So if the `Version` is not otherwise set, then `Version` will be set to the `VersionPrefix` combined with the `VersionSuffix`, separated by a dash.

**Comment by mairaw** [comment]
Thanks @dsplaisted. Also copying here another feedback I got for this option that was sitting on an internal backlog:

"--version-suffix <VERSION_SUFFIX> Defines the version suffix for an asterisk (*) in the version field of the project file. The format follows NuGet's version guidelines. That's not true, the asterisk isn't replaced. See https://github.com/dotnet/cli/issues/5681 The correct documentation should be: <VersionPrefix>1.0.0$(VersionSuffix)</VersionPrefix>"
