### ISSUE TITLE
Cant replicate expected results - seems to give only one result not as listed?

### ISSUE THREAD

**Issue by stevegiergiel** [dotnet/docs#5916]
The average score of Tucker Michael is 92.
Press any key to exit.

What have I done wrong please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 882a8aeb-491a-dc1a-6642-21d1d46cb989
* Version Independent ID: 2c8774e7-feec-bb26-89a8-ba92b8340a0c
* Content: [How to: Populate Object Collections from Multiple Sources (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I could reproduce this problem @stevegiergiel, so I don't think you've done nothing wrong. We'll investigate what's wrong. Thanks!

**Comment by mairaw** [comment]
@stevegiergiel I've created PR #5929 to fix this issue.
