### ISSUE TITLE
Confusing code in IDbCommand.Parameters doc

### ISSUE THREAD

**Issue by SupraBitKid** [dotnet/docs#5923]
It looks like there are two chunks of code in the example that add parameters to the collection:
1)    `command.Parameters.Add(paramArray);     `

2)   
```
for (int j=0; j<paramArray.Length; j++)
    {
        command.Parameters.Add(paramArray[j]) ;
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff628ea-391b-854b-af00-7933fd43b453
* Version Independent ID: 10ad07c4-d778-af19-fb68-cff8e0db3bc0
* Content: [IDbCommand.Parameters Property (System.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.data.idbcommand.parameters?view=netframework-4.7.2)
* Content Source: [xml/System.Data/IDbCommand.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/IDbCommand.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @SupraBitKid. Not only is there a duplicate attempt to populate the SqlParameterCollection, but the first call to the Add method throws an InvalidCastException. (The call should have been to the AddRange method.) We'll correct this code in the near future.
