### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by csrowell** [dotnet/docs#5939]
The "Customize your build" link is broken: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [Select the C# language version - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#visual-studio-quick-action)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That link shouldn’t have the .md extension. I’ll fix this.
