### ISSUE TITLE
dotnet sln CREATE ???

### ISSUE THREAD

**Issue by fmorriso** [dotnet/docs#5944]
2018-08-13:
Nowhere in here does it show how to create a .sln via the DotNet CLI. 

At the moment that I created a new angular project via the following (found elsewhere on the docs.microsoft.com web site):

dotnet new angular -o my-new-app

There will be NO .sln created, thus the need to retroactively go back to create one, hopefully via the dotnet sln command, but alas, that does not seem possible as of mid-June 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @fmorriso. To create a solution file, you need to use the [dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new) command:

```
dotnet new sln
```

I can add a note about this on the topic.

**Comment by fmorriso** [comment]
Seems odd to have to go back and use "new" for something that is "old", but hey, at least it's possible to accomplish what I need, no matter how strange and unnaturally out of sequence the process may seem.

**Comment by mairaw** [comment]
I understand what you’re saying. Maybe the way you can think about this is the following:

dotnet new is the command that creates files including solution files
dotnet sln is to manipulate an existing solution file

/cc @kathleendollard

**Comment by fmorriso** [comment]
How about adding something to the documentation that says something like this:
To create a project WITHIN a solution, perform the following steps IN THIS SEQUENCE:
1. Step 1
2. Step 2
3. etc.

**Comment by mairaw** [comment]
You don't think the information added was enough @fmorriso? The reference for the dotnet sln should be short and concise. I don't want to add an entire tutorial into these reference pages. 

One thing in my backlog is to convert this [tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos) into a more general, CLI tutorial. But you have the step-by-step there. I can add a link to this.

**Comment by TomasHubelbauer** [comment]
This is really unfortunate. `dotnet new sln` in an already existing project created using `dotnet new console` seems backwards to me, `dotnet sln create` would make a lot of sense, or even better, if you have just `dotnet new console` and then run `dotnet sln add project.csproj` or even better just `dotnet sln add` or `dotnet sln` it should figure out (or ask) to create the solution file (name based on the CSPROJ file if sole or on the directory name like `dotnet new`) and do it.

Right now it is a dance of

```
dotnet new console
dotnet new sln
dotnet sln whatever.sln add whatever.csproj # Why does this have to be so chatty?
```
