### ISSUE TITLE
why Indent by 3 space? 

### ISSUE THREAD

**Issue by longtth** [dotnet/docs#5950]
Why code sample has been indent by 3 space? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e087942b-4c61-ed3d-24e9-b4224ad31893
* Version Independent ID: acf0995d-5a49-f52c-e20b-f1d8c1b8d251
* Content: [XmlSerializer.Deserialize Method (System.Xml.Serialization)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer.deserialize?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Xml.Serialization.XmlSerializer.Deserialize)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Xml.Serialization/XmlSerializer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlSerializer.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I can't tell why because these content has changed hands over the years, so won't be able to track this down. But I'm adding this to our backlog as a community project for folks that are interested in contributing to our docs. It should be 4 spaces.
