### ISSUE TITLE
ValueObject.GetAtomicValues()

### ISSUE THREAD

**Issue by BjarkeMeier** [dotnet/docs#5952]
To make it even easier to create custom value object types the ValueObject base class could implement a reflection based GetAtomicValues method to remove the requirement of implementing it in derived classes. But that would of course be a trade between ease and performance. However it could allow optional override.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @BjarkeMeier, thanks for your feedback!

I think it'd be a nice addition, would you like to contribute a PR in the [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers/pulls/)?

**Comment by BjarkeMeier** [comment]
Hi @mvelosop , sure but it will probably be next month.

**Comment by sughosneo** [comment]
Hi @BjarkeMeier, The reference application `eShopOnContainers` has recently updated with 
the [ValueObject](https://github.com/dotnet-architecture/eShopOnContainers/commit/921de69418e3e980bea1bf69c2c72a2cf90b50e2) related changes. Even the document is also updated through this PR#20235

I am closing this issue as the method `GetAtomicValues()` has been renamed. So the entire scope of this discussion changes and it would be better to track further changes through a separate issue. 

If you have any questions or concerns, please feel free to reopen it.

Thank you.
