### ISSUE TITLE
SmartEnum on Nuget

### ISSUE THREAD

**Issue by ardalis** [dotnet/docs#5959]
Another additional resource: https://www.nuget.org/packages/Ardalis.SmartEnum/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CESARDELATORRE do you wanna add that link to the list of additional resources?

**Comment by mvelosop** [comment]
Added link in additional resources.
