### ISSUE TITLE
Branches and loops challenge.

### ISSUE THREAD

**Issue by douglastks52** [dotnet/docs#5966]
It would be really helpful if there were anything showing how the challenge on step 5 would look like completed. I failed several times and couldn't find the right way to do it anywhere on the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcf89b8-e845-5723-26c0-e9fcb4da60e6
* Version Independent ID: 85929067-8f01-e47e-c736-95edb6b50267
* Content: [Branches and loops interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/branches-and-loops?tutorial-step=6)
* Content Source: [docs/csharp/quick-starts/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by AriezRNG** [comment]
int sum = 0; //This will track the sum of every number divisible by 3.

for (int counter = 1; counter < 20; counter++) //Loop 20 times.
{
    if (counter%3 == 0) //If the remainder is 0, then it's divisible by 3.
    {
        Console.WriteLine($"{counter} is divisible by 3."); //Just to keep track of the numbers divisible by 3
        sum += counter; //The sum variable will add that number to its current value. Short form of (sum = sum+counter)
    }
}

Console.WriteLine($"The sum of every number divisible by 3 from 1 to 20 is {sum}"); //When the loop ends it shows the final number that variable sum has obtained.

I hope it helps you!

**Comment by mariochoquette** [comment]
no good

**Comment by BillWagner** [comment]
@mariochoquette I'll figure out why the correct answer isn't shown (it was originally).

In the meantime, [the correct code is on GitHub](https://github.com/dotnet/samples/blob/master/csharp/branches-quickstart/Program.cs#L46-L54) in our samples repo.

**Comment by mrbentarikau** [comment]
This 'equal to' "==" is never explained to QuickStarts users and might be a slight problem.
