### ISSUE TITLE
Is there a PrivateAssets flag?

### ISSUE THREAD

**Issue by Meberem** [dotnet/docs#5968]
Is there a way to configure the PrivateAssets attirbute that this command creates? I wanted to add https://github.com/ctaggart/SourceLink#all-source-files to a number of projects and making the PrivateAssets flag scriptable would be really handy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by pdylanross** [comment]
Seconding this, as this would be super handy to add code analysis into my workplace's nuget package project generator would save our devs a ton of time.

**Comment by dasMulli** [comment]
fyi: Another way to make changes to all projects at once is to use a `Directory.Build.props` / `.targets` file (see [Customize your build - Directory.Build.props and Directory.Build.targets](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#directorybuildprops-and-directorybuildtargets))

e.g. when you place a `Directory.Build.targets` file next to your .sln (or in the directory in which you want all projects to use it), it can add the configured package reference to all projects:
```xml
<Project>
  <ItemGroup>
    <PackageReference Include="SourceLink.Copy.PdbFiles" Version="2.8.3" PrivateAssets="All" /> 
  </ItemGroup>
</Project>
```

Requesting a new feature for `dotnet add package` is a NuGet/Home feature request (`dotnet nuget package add` / `NuGetCommand` would need to expose it).

**Comment by Meberem** [comment]
I did end up using `Directory.Build.targets` in a similar manner to how you have suggested. My brain was stuck in using the cli to sort out all my issues. I still think it would be a nice optional flag/argument to include/use. Thanks for your suggestion 👍

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc can you take a look at this feedback for the .NET Core CLI? Should it be filed under dotnet/cli or has anything changed to this command since then?

**Comment by livarcocc** [comment]
I don't think we have a way to do that really. But maybe move the issue to NuGet. Since this would apply during restore, I guess.

**Comment by mairaw** [comment]
Ok, thanks @livarcocc. Moved to https://github.com/NuGet/Home/issues/7755.
