### ISSUE TITLE
ChannelFactory<TChannel>.CreateChannel example doesn't have an example of this overload

### ISSUE THREAD

**Issue by andrewcarmichaelultimateins** [dotnet/docs#5971]
This page is about CreateChannel (string endpointConfigurationName), but the example shown only demonstrates CreateChannel()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c346bed0-6002-5771-db13-b6ee1bb90ad3
* Version Independent ID: fe72d0a3-116a-c523-064c-9814d3c2da57
* Content: [ChannelFactory&lt;TChannel&gt;.CreateChannel Method (System.ServiceModel)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channelfactory-1.createchannel?view=netframework-4.7.2#System_ServiceModel_ChannelFactory_1_CreateChannel_System_String_)
* Content Source: [xml/System.ServiceModel/ChannelFactory`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel/ChannelFactory`1.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback. The example indeed does not demonstrate a call to the overload that it documents. We've added this item to our backlog.

**Comment by baskar3078** [comment]
As per the System.ServiceModel.ChannelFactory class, these are the below methods.
    
public TChannel CreateChannel();        
public TChannel CreateChannel(EndpointAddress address);
public static TChannel CreateChannel(Binding binding, EndpointAddress endpointAddress);
public virtual TChannel CreateChannel(EndpointAddress address, Uri via);
public static TChannel CreateChannel(Binding binding, EndpointAddress endpointAddress, Uri via);

All the above are public methods and readily accessible. The below one is protected so would not be accessible readily.
protected static TChannel CreateChannel(string endpointConfigurationName);

**Comment by baskar3078** [comment]
We can do something like below. I am not sure how I can update the snippet and provide pull request.

class Program : ChannelFactory<IService1Channel>
 {
        static void Main(string[] args)
        {
            IService1Channel channel = CreateChannel("BasicHttpBinding_IService1");
            channel.Open();
           
            channel.Close();


        }
    }

**Comment by Kubik2000** [comment]
@baskar3078 @rpetrusha please check if it is ok I have created the PR
https://github.com/dotnet/samples/pull/599
https://github.com/dotnet/dotnet-api-docs/pull/1714

**Comment by baskar3078** [comment]
@Kubik2000 Thanks for creating the pull request.
