### ISSUE TITLE
Unhandled Exception: System.InvalidOperationException

### ISSUE THREAD

**Issue by GlauberCoder** [dotnet/docs#5972]
Unhandled Exception: System.InvalidOperationException: The following inputs are missing: Var_db99945c79dc461c88743f0f51f4507d
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
   at FinanceRegressionPredictor.Program.Train(String trainDataPath) in C:\Users\Glauber\source\repos\FinanceRegressionPredictor\FinanceRegressionPredictor\Program.cs:line 65
   at FinanceRegressionPredictor.Program.Main(String[] args) in C:\Users\Glauber\source\repos\FinanceRegressionPredictor\FinanceRegressionPredictor\Program.cs:line 22
   at FinanceRegressionPredictor.Program.&lt;Main&gt;(String[] args)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by GlauberCoder** [comment]
Desculpe ficou sem a mensagem. Estou tendo este erro ao executar meu código.

                        var pipeline = new LearningPipeline();
			var catecoricalFeatures = Features().Where(f => f.Categorical).Select(f => f.Feature);

			pipeline.Add(new Dictionarizer("Label"));
			pipeline.Add(new TextLoader(trainDataPath).CreateFrom<RateValues>(separator: '|', useHeader: true));
			pipeline.Add(new CategoricalOneHotVectorizer(catecoricalFeatures.ToArray()));
			pipeline.Add(new ColumnConcatenator("Features", Features().Select(f => f.Feature).ToArray()));
			pipeline.Add(new Microsoft.ML.Trainers.StochasticDualCoordinateAscentClassifier());
			pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

			var model = pipeline.Train<RateValues, RatesPrediction>();

			return model;

**Comment by mairaw** [comment]
E só pra confirmar, este é o codigo do artigo, correto @GlauberCoder?

**Comment by pkulikov** [comment]
@GlauberCoder shouldn't `TextLoader` step be the first in the pipeline, and only then `Dictionarizer`? Like that:
```csharp
pipeline.Add(new TextLoader(trainDataPath).CreateFrom<RateValues>(separator: '|', useHeader: true));
pipeline.Add(new Dictionarizer("Label"));
```

**Comment by GlauberCoder** [comment]
Maybe would be a good idea to improve that message.

**Comment by pkulikov** [comment]
@GlauberCoder that's true; please report it in [ML.NET repo](https://github.com/dotnet/machinelearning)

**Comment by mairaw** [comment]
Yes as @pkulikov said, let’s try to keep the feedback related for content here and product questions and feedback at dotnet/machinelearning. Obrigada!
