### ISSUE TITLE
In .NET Core, finalizers do not run when the program exits

### ISSUE THREAD

**Issue by jkotas** [dotnet/docs#5974]
&gt; Finalizers are also called when the program exits. 

This is not the case in .NET Core. https://github.com/dotnet/corefx/issues/5205 has the full details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks, @jkotas. This will require a review of both the C# and .NET documentation on finalizers. We'll schedule it for the upcoming sprint.
