### ISSUE TITLE
Can ToString() return a more human-friendly representation?

### ISSUE THREAD

**Issue by dwilches** [dotnet/docs#5979]
I'd like to recommend this method to return the MAC in the human-friendly format `AA:BB:CC:DD:EE:FF` instead of the current `AABBCCDDEEFF`. 

There are some alternatives people have invented to add the `:` in between the string returned by this method:
https://stackoverflow.com/questions/7384211/formatting-mac-address-in-c-sharp

But I wonder in which cases the current representation is more useful than the proposed one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef100f1-145b-7c48-8007-99fcd2791db7
* Version Independent ID: 86e3973f-1749-baf4-28a7-124b6b4ca77d
* Content: [PhysicalAddress.ToString Method (System.Net.NetworkInformation)](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.physicaladdress.tostring?view=netframework-4.7.1)
* Content Source: [xml/System.Net.NetworkInformation/PhysicalAddress.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.NetworkInformation/PhysicalAddress.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This is a product suggestion and not a content feedback. @karelz @davidsh is that an API you'd consider adding? Should I move this request to corefx?

**Comment by karelz** [comment]
It's already tracked in CoreFX: https://github.com/dotnet/corefx/issues/29740
