### ISSUE TITLE
Example Code is wrong

### ISSUE THREAD

**Issue by Angr1st** [dotnet/docs#5986]
I created a .net core console application and tried to compile the example code but it has a 3 compiler errors. First 'currentDomain.DefineDynamicAssembly()' does not exist anymore in .net core. Instead you have to use 'AssemblyBuilder.DefineDynamicAssembly'. For the second error 'myFieldBuilder.GetToken()' I haven't found a workaround. 
Lastly 'PermissionSetAttribute' does also not exist in .net core as all code is running in 'full thrust' mode all the time.
Please fix/correct the example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb69b18d-a46a-9aae-08ca-2de601677107
* Version Independent ID: a0247b07-8032-f06f-2d93-99d318ce2cad
* Content: [FieldBuilder Class (System.Reflection.Emit)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.fieldbuilder?view=netcore-2.1)
* Content Source: [xml/System.Reflection.Emit/FieldBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection.Emit/FieldBuilder.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this oiut, @Angr1st. We've addressed it in dotnet/samples#159 and dotnet/dotnet-api-docs#325.

**Comment by Angr1st** [comment]
Great thank you for fixing it 👍
