### ISSUE TITLE
F# Async Unit Testing

### ISSUE THREAD

**Issue by jon49** [dotnet/docs#5989]
In the documentation it doesn't say how to test F# asynchronously with MSTest. Since F# returns `Task<unit>` that doesn't work and when you raise it to plain `Task` it ignores the test. It would be nice to know this or to know if it is not possible.

    |> fun x -> Async.StartAsTask x :> Task // Doesn't work; is ignored by testing framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 803d9667-b438-449d-db9c-f381852f6bce
* Version Independent ID: 0078395d-d69e-c773-2f01-f20956391cb1
* Content: [Unit testing F# libraries in .NET Core using dotnet test and MSTest](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-mstest)
* Content Source: [docs/core/testing/unit-testing-fsharp-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-fsharp-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@cartermp Do you want to add this info to the unit test doc we have?

**Comment by mairaw** [comment]
Ping @cartermp

**Comment by jon49** [comment]
Sorry, I haven't kept up with this. I'll see if I can get an example up for you to look at. I'll shoot for this weekend.

**Comment by mairaw** [comment]
@cartermp do you want to add that sort of info to the docs? @jon49 have you managed to get an example up?

Thanks!

**Comment by mairaw** [comment]
@cartermp what should we do about this issue?

**Comment by xperiandri** [comment]
So what about the sample?

**Comment by MangelMaxime** [comment]
For anyone looking into this issue, here is a working snippet:

```fs
open System.Threading.Tasks

[<TestClass>]
type All () =

    [<TestMethod>]
    member _.AlwaysPass () : Task =
        task {
            Assert.IsFalse(false)
        }
```

The type annotation `: Task` is **important**  returning `Task<unit>` which is the default infer type will not work.

**Comment by xperiandri** [comment]
Viewing `Test Runner` output in the `Output` window allows to see all the issues with test discovery. I had such issues with `ClassInitialize` too
