### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jon80** [dotnet/docs#5992]
How about an example that I can work with, please?
I use Visual Studio 2010 [.NET Version 4.7.03056 SP1] where Windows 10 and my keyboard are already keeping me from being productive given other hardware related and touchpad related issues.

I hope to see a return on investment as I try to become more professional in my programming curriculum and all I read from the job market are layoffs and negative news unfortunately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 131b2f0d-3a66-82ec-c571-33344d8d1f95
* Version Independent ID: cea36613-ef24-b09c-5a71-fb543eafd125
* Content: [PaintEventArgs Class (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.painteventargs?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/PaintEventArgs.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/PaintEventArgs.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnet-bot**

**Comment by svick** [comment]
What exactly prevents you from working with the examples for that type?

Also, VS 2010 is a very old version. If you can, I suggest you to upgrade to VS 2017 (the Community version is free for individual developers).
