### ISSUE TITLE
Broken link "KeyFrame Animation Sample"

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#5995]
The link ... "For the complete sample, see KeyFrame Animation Sample" ... is broken.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f37151-1614-bde7-43dd-85033534adc0
* Version Independent ID: 5950f816-fb54-9c36-0785-3f1818d11a52
* Content: [How to: Animate a Double by Using Key Frames](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/how-to-animate-a-double-by-using-key-frames)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-animate-a-double-by-using-key-frames.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/how-to-animate-a-double-by-using-key-frames.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @MarcioAB. I've thought of initially linking to https://github.com/Microsoft/WPF-Samples/tree/master/Animation/KeyFrameAnimation, however it didn't match the sample we were showing on that page. I changed that to point to the sample we are using on that page.
