### ISSUE TITLE
Improve document for key method parameter

### ISSUE THREAD

**Issue by nicoleta-scrimint** [dotnet/docs#5998]
From the documentation of this method, I understand that the value will be changed for the specified key, if the existing value is equal to the "comparisonValue" method argument.

The documentation for the "key" method parameter is misleading from my point of view:
"The key whose value is compared with comparisonValue and possibly replaced."
because the key is not compared to the comparisonValue method argument and the key can never be replaced/changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cba7d34-0782-643e-d8e3-88efd6834c2a
* Version Independent ID: 10e03582-0975-4305-e650-839afcf82b24
* Content: [ConcurrentDictionary&lt;TKey,TValue&gt;.TryUpdate(TKey, TValue, TValue) Method (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.tryupdate?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@nicoleta-scrimint do you mean that the word *value* might be interpreted in two different ways here:
- as the value of the element that has a given key
- as the value of the key itself (in the sense of "value of a variable")?

**Comment by nicoleta-scrimint** [comment]
Thank you for the clarification!
