### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by KetoDuo** [dotnet/docs#5999]
App crashes every time I attempt to open

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485
* Version Independent ID: f2e94c72-459b-c8f1-7eec-73e7d4197f4d
* Content: [Repair the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/repair)
* Content Source: [docs/framework/install/repair.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/repair.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
What is the app that crashes, @KetoDuo? Are you still having difficulty with it? Can you provide any additional information, such as an error message?

**Comment by mairaw** [comment]
Closing due to the lack of response.
