### ISSUE TITLE
Formatting issues in remarks text

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6001]
There are some formatting issues in the content, section Remarks, on the paragraph that begins with “You can specify all the values or you can accept the default build number”. There seem to be characters missing, and part of the paragraph text is formatted as code when it is actually normal descriptive text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e365c47-e94b-14a7-2617-053090d2540f
* Version Independent ID: d3d54d1d-c6a6-8fe7-a219-d05bb6aa9f58
* Content: [AssemblyVersionAttribute Class (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyversionattribute?view=netframework-4.7.2)
* Content Source: [xml/System.Reflection/AssemblyVersionAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/AssemblyVersionAttribute.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
You're right @ite-klass. It's probably a migration issue where the asterisk needs to be escaped.

You can compare that with the original content from MSDN:
https://msdn.microsoft.com/en-us/library/system.reflection.assemblyversionattribute(v=vs.110).aspx#Remarks
