### ISSUE TITLE
Understanding terminology

### ISSUE THREAD

**Issue by ozy1ozy** [dotnet/docs#6002]
I have noticed a common problem with learning coding (I'm not a programmer). You start off by trying to explain a term without defining what you mean by the term. A case in question is the term 'type'. By not clarifying what you mean by 'type' you create a query in the students mind that has to be resolved before they can continue. It's a bit like languages. For instance, we learn about 'verbs' by describing what we mean by the term 'verb', we say it is a word that describes an action. We can therefore continue using the term 'verb' because we have defined what we mean when we say 'verb'.
In this section on 'type' you do not do this and you further compound the problem by using what would be considered a 'description' word as a noun, i.e. "C# is a strongly-typed language. Every variable and constant has a type, as does every expression that evaluates to a value" or "The information stored in a type can include the following:" 
What you are not doing, is first telling the reader what you mean by a 'type' is it a label (user-defined types)? A category of things having common characteristics? Or a proper noun? I find that this lack of clarity when words are used, impedes the learning process.
As a further comment regarding learning coding, I would say that the one common problem that all learning strategies have is that they use lots of text or example code to explain terminology, whereas a graphical representation of such things as methods, classes, constructors, types etc, would be easier to comprehend and relate to each other if they were shown as an illustration/diagram.
It is a bit like describing the term car as being used for transporting people from one point to another - the description does not define 'car' by what it is but by what it does, leaving the reader still clueless.
NB: you only have to look at the numerous explanations programmers give in StackOverflow for a term, to see that they all have different understandings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f29f2c2-44b6-ee2d-3991-ec7a77709883
* Version Independent ID: 64b883fc-4bf5-f6f1-0935-e82b83cf2bdf
* Content: [Types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/)
* Content Source: [docs/csharp/programming-guide/types/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by johnnyagerard** [comment]
"Type" is a shorthand for "data type".

In C#, there are five types of "type" :
-class
-struct
-interface
-enum
-delegate

**Comment by alper4** [comment]
The terms used on this page (built-in type, complex type, numeric type, custom type, etc) are highly incompatible with the terms used on Tour of C# > Types and Variables page (value type, reference type, integral type, simple type, etc)  at https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables
Could you please avoid terminology soup and streamline this content in sync with the Tour page?

**Comment by alper4** [comment]
The terms used on this page (built-in type, complex type, numeric type, custom type, etc) are highly incompatible with the terms used on Tour of C# > Types and Variables page (value type, reference type, integral type, simple type, etc) at https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables
Could you please avoid terminology soup and streamline this content in sync with the Tour page?

**Comment by johnnyagerard** [comment]
@alper4 Hi, you should open a new issue for your request because this one is closed.
