### ISSUE TITLE
Class not found. 

### ISSUE THREAD

**Issue by amitvermad** [dotnet/docs#6003]
Could not find ProfileOptimization class in visual studio 2015 .net framework 4.6. Please suggest what is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3e1c47-07c5-d73e-7856-8677f7f63b32
* Version Independent ID: 0e321570-46ef-7943-baf6-72abbf4d4102
* Content: [ProfileOptimization Class (System.Runtime)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.profileoptimization?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime/ProfileOptimization.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime/ProfileOptimization.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
The `ProfileOptimization` class was added in .Net Framework 4.5, so it should work fine in .Net Framework 4.6.

Some steps that could help:

1. Can you share the exact error your code is producing and also the relevant code?
2. Do you have `using System.Runtime;` at the top of your source file?
3. Are you sure the target framework of your project is .Net Framework 4.6? (You can see it when you right click on your project, select Properties and the go to the Application tab.)

**Comment by amitvermad** [comment]
Many thanks for your reply. It was mistake at my end. 
In app.config I manually change target version to 4.6, but in Project properties it was .Net Framework 4. 
I change it now and it is working.
