### ISSUE TITLE
Merge language-independence and language-independence-and-language-independent-components

### ISSUE THREAD

**Issue by svick** [dotnet/docs#6009]
The articles [language-independence](https://docs.microsoft.com/en-us/dotnet/standard/language-independence) and [language-independence-and-language-independent-components](https://docs.microsoft.com/en-us/dotnet/standard/language-independence-and-language-independent-components) are the same and should be merged.

It seems they were imported differently, so their Markdown is different (e.g. one uses code like `<xref:System.Byte>`, the other `[Byte](xref:System.Byte)`).

As for which one should be kept, I think it's a mix of the two, so it would take more work than just deleting one of them. That's because:

* language-independence is more up-to-date: it uses ".NET" instead of ".NET Framework", doesn't mention e.g. Visual COBOL.
* language-independence-and-language-independent-components uses snippets instead of code blocks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9b4b39-813f-ed23-3cb7-682766b3cfaa
* Version Independent ID: c3216a96-76a2-21aa-2072-0328725cd3cb
* Content: [Language independence and language-independent components](https://docs.microsoft.com/en-us/dotnet/standard/language-independence)
* Content Source: [docs/standard/language-independence.md](https://github.com/dotnet/docs/blob/master/docs/standard/language-independence.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Wow, I had no idea. Thanks for pointing this out, @svick. We'll schedule some time to consolidate the two topics during the next sprint.
