### ISSUE TITLE
Teaching C#

### ISSUE THREAD

**Issue by peternroth** [dotnet/docs#6014]
This is the greatest teaching advance in years! Well done!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcf89b8-e845-5723-26c0-e9fcb4da60e6
* Version Independent ID: 85929067-8f01-e47e-c736-95edb6b50267
* Content: [Branches and loops interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/branches-and-loops?tutorial-step=6)
* Content Source: [docs/csharp/quick-starts/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Awesome! We’re glad that you liked it @peternroth.

**Comment by LadyNaggaga** [comment]
@peternroth glad you found it useful!
