### ISSUE TITLE
.NET Core Global Tools  Part 3: Update extensibility topic

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#6017]
This Part 3 of 3 topics will address the .NET Core Global Tools. .NET Core now has a new deployment and extensibility mechanism for tools. This new experience is very similar to and was inspired by NPM global tools.
 Part 1: global tools overview, sdk commands, how to use it - #4509
 Part 2: how to create new global tools - #6016
 Part 3: update extensibility topic - This Topic

**Comment by Thraka** [comment]
I'm going to close this in favor of a new issue detailing the plan for global tools
