### ISSUE TITLE
Last snippet is error.

### ISSUE THREAD

**Issue by zhuangzhuang** [dotnet/docs#6021]
https://github.com/dotnet/samples/blob/master/csharp/roslyn-sdk/SemanticQuickStart/Program.cs must use Snippet13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68fa439-55b3-ff14-e2d1-2373615d978b
* Version Independent ID: 33c84a67-2ca2-fd1c-3739-60ad3df79f8e
* Content: [Get started with semantic analysis](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/semantic-analysis)
* Content Source: [docs/csharp/roslyn-sdk/get-started/semantic-analysis.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/get-started/semantic-analysis.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
You're right. Do you want to submit a Pull Request that makes that change? If you do and don't know how, you can follow [this guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents). If you have any questions, feel free to ask here.
