### ISSUE TITLE
Please update to lastest versions on tables etc.

### ISSUE THREAD

**Issue by jwettstrom** [dotnet/docs#6022]
The tables etc. are way outdated. Please update these along with the releases. MS Docs have become very confusing with lots of outdated documentation that no longer works or which works with what. If you want to have fast releases, the documentation has to keep up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by pkulikov** [comment]
@jwettstrom what table do you speak about?

If you concern about the *.NET implementation support* table, then
> the version number in each cell indicates the **minimum** version of the implementation you'll need in order to target that .NET Standard version.

@mairaw is it worth to update the table introductory sentence that it states that the platform versions in the table are *minimum* ones?

If  your concern is about the *PCL compatibility* table, I agree with you. The [PCL compatibility](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#pcl-compatibility) section doesn't mention .NET Standard 2.0. @mairaw should that section (and table if necessary) be updated?

**Comment by mairaw** [comment]
That information is after the table @pkulikov but it might be worth trying to add that before.

I don't think newer versions of the standard overlap with PCL profiles, so adding @terrajobst here to confirm.

Also, I've seen people expecting to see a .NET Standard 2.1 column when such a version doesn't exist yet.

@jwettstrom can you please clarify where do you think the topic is outdated? I'll make sure to update the date we're displaying since this topic has been recently reviewed.

**Comment by pkulikov** [comment]
@terrajobst thanks for replies.

>We should somehow make the term **minimum version** stand out more. 

True, as about once a month somebody misses the remark under the table and raises an issue.

> Since PCLs are deprecated, no profile was ever mapped to .NET Standard 2.0. However, a .NET Standard 2.0 project can reference any PCL profile that was mapped to a .NET Standard version.

@mairaw @terrajobst is that a good paragraph to add to the docs? To explicitly describe the situation with .NET Standard 2.0 and PCL.

**Comment by rocifier** [comment]
The table made no sense to me without the full explanation below. I think the confusing point is that the table is introduced as listing all supported platforms, which it doesn't do.
