### ISSUE TITLE
Converting a PCL project - Target .NET Platform Standard no longer exists

### ISSUE THREAD

**Issue by mrward** [dotnet/docs#6026]
https://docs.microsoft.com/en-us/dotnet/core/porting/libraries#converting-a-pcl-project

In older versions of Visual Studio there used to be a 'Target .NET Platform Standard' option to convert a PCL project to a .NET Standard project that used a project.json file (not an SDK style project). This option does no longer seems to exist in Visual Studio 2017 15.7.4 presumably because project.json has been deprecated. Now for a PCL project the project Properties page has some information:

.NETStandard is the recommended method for sharing code between applications targeting different platforms.

And a Learn More link is available. The Learn More link goes to:

http://go.microsoft.com/fwlink/?LinkId=850956

Which redirects to:

https://docs.microsoft.com/en-us/dotnet/standard/netstandard#comparison-to-portable-class-libraries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b87e122-0604-5691-8fb5-8ae088557def
* Version Independent ID: 22e94acd-178a-158f-13b3-287437da62b3
* Content: [Porting to .NET Core - Libraries](https://docs.microsoft.com/en-us/dotnet/core/porting/libraries#converting-a-pcl-project)
* Content Source: [docs/core/porting/libraries.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/libraries.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for bringing this to our attention @mrward. @terrajobst do you what's the current process to convert? This topic probably needs more updates besides this one called out by Matt.

**Comment by terrajobst** [comment]
@mairaw 

The conversion mechanism from PCL to .NET Standard was removed as the output uses a project system that doesn't have the right feature set. The approach to convert is the same as for any a project type now: you create a new .NET Standard project and copy & paste the existing source files. Alternatively, you can hand edit the project files like @jamesmontemagno did this in his awesome video:

https://www.youtube.com/watch?v=F0VWCmj2adw

**Comment by jamesmontemagno** [comment]
And: https://montemagno.com/how-to-convert-a-pcl-library-to-net-standard-and-keep-git-history/ :)
