### ISSUE TITLE
Developer Command Prompt had to be Run as Administrator to get service to successfully install...

### ISSUE THREAD

**Issue by darbvin** [dotnet/docs#6029]
The first time I attempted to install, I got a failure with no discernable explanation in the installLog.
The second time I attempted to install, I got a failure with this error in the installLog:
System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.

I ran the dev cmd prompt as administrator on the 3rd try, and it was successful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Walkthrough: Creating a Windows Service Application in the Component Designer](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@darbvin, the topic mentions that you have to run the console window as administrator:

![image](https://user-images.githubusercontent.com/10886961/41613648-0a789f98-73ab-11e8-8b79-b991ca03bb9b.png)
 
Was this guidance inadequate? Under the assumption that you overlooked the need to open the console window with elevated permissions, I'm going to close this issue. If that isn't the case and you disagree, please feel free to respond.
