### ISSUE TITLE
Does this tutorial create a 32-bit service?  

### ISSUE THREAD

**Issue by darbvin** [dotnet/docs#6031]
I see references that appear to be 32-bit ("DwWin32ExitCode" "advapi32.dll")... Being that windows and windows server are all 64-bit now, is there any reason to avoid 64-bit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Walkthrough: Creating a Windows Service Application in the Component Designer](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by MythreyaK** [comment]
To directly answer your question, yes, this does create a 32-bit service. You can create a 64-bit service by changing the project's properties. You can also safely change `advapi32.dll` to `advapi64.dll`. I personally don't see any reason to generate a 32-bit service when 64-bit can be as easily built. Perhaps someone from MSFT can enlighten us!
