### ISSUE TITLE
"succinct and expressive"

### ISSUE THREAD

**Issue by et1975** [dotnet/docs#6032]
I'd add "composable" to that list. Conversely, "composable, succinct and expressive" can be at odds with "interoperable". Interoperability is not by itself a virtue, it's just one of the quality attributes that one may or may not care about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63d2086-c15d-2434-8189-c2acaab237ca
* Version Independent ID: 08a7d210-bab0-fdd3-5629-34dcc79172e1
* Content: [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/)
* Content Source: [docs/fsharp/style-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@eiriktsarpalis it would be good to get your perspective on this as well.

The current document states that interoperability is a virtue. My purpose in writing this document is less about interoperability and more about making it clear that the boundaries of pieces of a system matter, and should be considered whenever writing F# code. I think that this is not at odds with "composable, succinct, and expressive".

As it stands, this paragraph could be interpreted in a way that discourages the use composability. @et1975 what do you think?

**Comment by et1975** [comment]
I'd love to see @swlaschin take as well.
