### ISSUE TITLE
Train should be async

### ISSUE THREAD

**Issue by objetitos** [dotnet/docs#6036]
public static PredictionModel&lt;SentimentData, SentimentPrediction&gt; Train()

should be

public static async Task&lt;PredictionModel&lt;SentimentData, SentimentPrediction&gt;&gt; Train()

Otherwise it can not contain an async call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
@objetitos good catch! thanks for reporting it.
