### ISSUE TITLE
64 bit?

### ISSUE THREAD

**Issue by mlawrenceConduent** [dotnet/docs#6041]
Are there 64 bit versions of these? When I change a solution to x64 projects which are of this "Class Library (Portable)" type give errors that they can't be compiled as 64 bits. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 831ea3a3-e545-138f-bd49-fab3420b0640
* Version Independent ID: 59ab76ed-0a71-2dcd-b288-f7daaab763a6
* Content: [Cross-Platform Development with the Portable Class Library](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library)
* Content Source: [docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md](https://github.com/dotnet/docs/blob/master/docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@mlawrenceConduent Apologies for the late response to this -- are you still looking for an answer to this question?
