### ISSUE TITLE
"switch 语句" 示例代码报错, 建议更换

### ISSUE THREAD

**Issue by gosali** [dotnet/docs#6043]
@hwhois commented on [Tue Jun 19 2018](https://github.com/dotnet/docs.zh-cn/issues/153)

"switch 语句" 示例代码 中
 Console.WriteLine($"{n}  arguments"); 在命令行编译时报错: error CS1056: 意外的字符“$”.
建议修改为:  Console.WriteLine(n + " arguments")

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 017f9566-a4df-e294-d6e8-da9252469ca9
* Version Independent ID: 6665f9d5-24bf-ac0d-62f5-d63ed53132ed
* Content: [C# 语句 - C# 语言介绍](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/statements#feedback)
* Content Source: [docs/csharp/tour-of-csharp/statements.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tour-of-csharp/statements.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@imba-tjd commented on [Tue Jun 19 2018](https://github.com/dotnet/docs.zh-cn/issues/153#issuecomment-398285222)

It is called [string interpolation](https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-6#string-interpolation).

---

@DavidPrio commented on [Tue Jun 19 2018](https://github.com/dotnet/docs.zh-cn/issues/153#issuecomment-398535447)

你好，@hwhois
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by mairaw** [comment]
@gosali please let us know what is the action item for the writing team from these bugs when moving them here.

/cc @Sara-Nicolini @nokura 

@BillWagner do you think we need to add any notes about the example using string interpolation in the switch statement?

**Comment by imba-tjd** [comment]
It seems that @hwhois is using .NET Framework 4.0 which not support for this feature. So this is on his side.
