### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by bacar** [dotnet/docs#6050]
Is the code sample correct?
It disposes of the CancellationTokenRegistration - which will unregister the callback - as soon as it finishes calling DownloadStringAsync(), which seems somewhat pointless!

    using (CancellationTokenRegistration ctr = token.Register(() => wc.CancelAsync()))
    {
        Console.WriteLine("Starting request\n");
        wc.DownloadStringAsync(new Uri("http://www.contoso.com"));
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda28b44-da10-0d43-f015-e73133b32039
* Version Independent ID: a33e2c50-463a-0180-002e-24d09f2aa54b
* Content: [How to: Register Callbacks for Cancellation Requests](https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-register-callbacks-for-cancellation-requests)
* Content Source: [docs/standard/threading/how-to-register-callbacks-for-cancellation-requests.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/how-to-register-callbacks-for-cancellation-requests.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by MV10** [comment]
It's correct. This isn't synchronous code you're looking at. The use of `Task.Run` means it'll execute on another thread, so while the download operation is running, the console will display the prompt to cancel, and as long as the download is still in progress the user can interrupt it. Once the download is completed, there isn't anything left to cancel, so you'd want to unregister it.

**Comment by bacar** [comment]
> This isn't synchronous code you're looking at

This is very much my point - the `DownloadStringAsync` is _not_ awaited so it’s possible - maybe even likely - that the download has not even begun, let alone completed, before the callback is unregistered.

**Comment by MV10** [comment]
Ah, good point!

**Comment by pkulikov** [comment]
@bacar that's right. `DownloadStringAsync` doesn't block the calling thread, so the token registration is disposed immediately after the download has started.

> This is very much my point - the `DownloadStringAsync` is _not_ awaited

This method is also confusing (I believe it's in .NET from pre-`async`/`await` times). You cannot await it because it returns `void`:
https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadstringasync?view=netcore-3.1

The one to `await` is [DownloadStringTaskAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadstringtaskasync?view=netcore-3.1)

@BillWagner @IEvangelist what would be a proper fix here?

**Comment by IEvangelist** [comment]
Hi friends,

I'd update the code to look like this:

```csharp
using System;
using System.Net;
using System.Threading;
using System.Threading.Tasks;

class CancelWithCallback
{
    static void Main()
    {
        using var cts = new CancellationTokenSource();
        var token = cts.Token;

        _ = Task.Run(async () =>
        {
            using var client = new WebClient();

            client.DownloadStringCompleted += (_, args) =>
            {
                if (args.Cancelled)
                {
                    Console.WriteLine("The download was canceled.");
                }
                else
                {
                    Console.WriteLine("The download has completed:\n");
                    Console.WriteLine($"{args.Result}\n\nPress any key.");
                }
            };

            if (!token.IsCancellationRequested)
            {
                using CancellationTokenRegistration ctr = token.Register(() => client.CancelAsync());

                Console.WriteLine("Starting request\n");
                await client.DownloadStringTaskAsync(new Uri("http://www.contoso.com"));
            }
        }, token);

        Console.WriteLine("Press 'c' to cancel.\n");
        char ch = Console.ReadKey().KeyChar;
        Console.WriteLine();
        if (ch == 'c')
        {
            cts.Cancel();
        }

        Console.WriteLine("Press any key to exit.");
        Console.ReadKey();
    }
}
```

Changes summarized:

- Use `DownloadStringTaskAsync`, thanks @pkulikov 👍🏼 
- Discard `Task t`
- Apply `using` to `CancellationTokenSource` and `WebClient` as both are `IDisposable`
- Make use of the `Task.Run(Func<Task>, CancelationToken)` overload, exposing `async` lambda
- Invert `if` logic to avoid negation flow
- Use string interpolation

**Comment by BillWagner** [comment]
I like this @IEvangelist Let's do it.
