### ISSUE TITLE
Interfaces with same property with another interface as a return type 

### ISSUE THREAD

**Issue by kp2017** [dotnet/docs#6052]
What is the solution for an interface that implements another interface and both have a property with the same name that returns another interface which is also inherited?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Explicit Interface Implementation (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Are you talking about something like the following code?

```c#
interface ICar
{
    IMotor Motor { get; }
}

interface IMotor {}

interface IElectricCar : ICar
{
    new IElectricMotor Motor { get; }
}

interface IElectricMotor : IMotor {}
```

In that case, I think a reasonable solution is to implement the more base interface explicitly and the more derived interface implicitly:

```c#
class Tesla : IElectricCar
{
    public IElectricMotor Motor { get; }
    
    IMotor ICar.Motor => Motor;
}
```

Though I'm not sure this is something that should be added to the article. Doesn't it explain the concepts sufficiently, so that you can figure a solution like this on your own?

**Comment by BillWagner** [comment]
@kp2017 I've reviewed your question, and the answer provided by @svick 

I agree that the article referenced does provide the information to implement both interfaces correctly.

I'm closing this. If you still have this issue, or we've misunderstood what you were asking, re-open the issue and add more information.
