### ISSUE TITLE
I am missing an example

### ISSUE THREAD

**Issue by R0binBl00d** [dotnet/docs#6053]
According to google, Left Outer Join should Result in :

// This code produces the following output:
//
// Arlene:

since a join includes the overlap of the two circles
a left join includes the overlap and the rest of A (as in the example)
and a left outer koin should show only the orphans of A, 
or A minus the inner join.

would be great if you could extend the examples with the "real" outer join 
(outside of the A-B overlap)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d433265d-15f4-bd2e-a3d1-8148a3968783
* Version Independent ID: 75d2c893-1d07-f836-62f1-e767edfcebac
* Content: [Perform left outer joins](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins)
* Content Source: [docs/csharp/linq/perform-left-outer-joins.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/perform-left-outer-joins.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@R0binBl00d Can you point to the google source that gives you different results?  

I ran the sample and got the results from the article.

**Comment by BillWagner** [comment]
@R0binBl00d I'm closing this as not reproducible. If you can point to a sample or other source, you can reopen it with more information.
