### ISSUE TITLE
Link to sample code is dead

### ISSUE THREAD

**Issue by amp64** [dotnet/docs#6056]
http://go.microsoft.com/fwlink/?LinkID=159998 points to an archive.msdn location that is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aeb422f-3ff5-245a-1936-46366cf38f7f
* Version Independent ID: 30a23909-737b-cd56-1239-7a2669266974
* Content: [Walkthrough: Hosting a Win32 Control in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for reporting the broken link, @amp64. We've opened PR #6058 to fix it.

**Comment by mairaw** [comment]
As a quick fix, I've replaced the FwLink to point to https://github.com/Microsoft/WPF-Samples/tree/master/Migration%20and%20Interoperability/WPFHostingWin32Control. I'll get to the PR soon.
