### ISSUE TITLE
FileStream not in using statement

### ISSUE THREAD

**Issue by tbrownio** [dotnet/docs#6063]
Is there a reason why the FileStream instance declaration in both examples is not wrapped in a using() statement? This deviates from other FileStream initialization examples in this section of the documentation and clarifying the reasoning behind this would be helpful to understand. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99c429ef-8912-ee30-d3bb-0a58551c68c7
* Version Independent ID: a65a0e5a-124b-8575-4725-a4c81bc6f8ab
* Content: [Composing Streams](https://docs.microsoft.com/en-us/dotnet/standard/io/composing-streams)
* Content Source: [docs/standard/io/composing-streams.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/composing-streams.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by drweb86-work** [comment]
Hello

That's because BinaryReader will close underlying stream by itself. However according to docs disposed items should not complain about subsequent dispose calls, so you can do this in both ways

Cheers.

**Comment by binki** [comment]
Even though readers will automatically close the `Stream` passed to them by default, the code examples for this documentation page are a bit haphazard with regard to ensuring that the `FileStream` objects are disposed. During refactoring, the developer might add lines between `var fs = new FileStream()` and `using (new StreamReader(fs)){}`. It would be better if the code were structured to avoid this possibility. For example, it would be acceptable to just write `using (new StreamReader(new FileStream(…))){…}` (though at this point one might wonder why you do not just recommend to use [`new StreamReader(FILE_PATH)`](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.8#System_IO_StreamReader__ctor_System_String_) or [`File.OpenText(FILE_PATH)`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.opentext?view=netframework-4.8)).

While, for many objects, calling `Dispose()` multiple times is acceptable, it is cleaner/nicer (and sometimes even required) to ensure that `Dispose()` is called exactly once. If it is called multiple times, that means that your object does not have well-defined lifetime ownership. If you insist on saving the `FileStream` to a variable, a way to do that would be to use the overload of `*Reader`’s constructor which accepts `leaveOpen`:

```csharp
const string FILE_NAME = "MyFile.txt";
public static void Mainx()
{
    FileStream openStream()
    {
        try
        {
            return new FileStream(FILE_NAME, FileMode.Open, FileAccess.Read, FileShare.Read);
        }
        catch (FileNotFoundException)
        {
            Console.WriteLine($"{FILE_NAME} does not exist.");
            return null;
        }
    }
    using (FileStream f = openStream())
    {
        if (f == null)
        {
            return;
        }
        // Create an instance of BinaryReader that can
        // read bytes from the FileStream.
        using (BinaryReader br = new BinaryReader(f, Encoding.UTF8, true))
        {
            byte input;
            // While not at the end of the file, read lines from the file.
            while (br.PeekChar() > -1)
            {
                input = br.ReadByte();
                Console.WriteLine(input);
            }
        }
    }
}
```

Or if you prefer to keep the race condition between `File.Exists()` and `new FileStream()`:

```csharp
const string FILE_NAME = "MyFile.txt";
public static void Mainx()
{
    if (!File.Exists(FILE_NAME))
    {
        Console.WriteLine($"{FILE_NAME} does not exist.");
        return;
    }
    using (FileStream f = new FileStream(FILE_NAME, FileMode.Open, FileAccess.Read, FileShare.Read))
    {
        // Create an instance of BinaryReader that can
        // read bytes from the FileStream.
        using (BinaryReader br = new BinaryReader(f, Encoding.UTF8, true))
        {
            byte input;
            // While not at the end of the file, read lines from the file.
            while (br.PeekChar() > -1)
            {
                input = br.ReadByte();
                Console.WriteLine(input);
            }
        }
    }
}
```

**Comment by binki** [comment]
@dotnet/docs this issue still hasn’t been fixed.

**Comment by binki** [comment]
@BillWagner ^
