### ISSUE TITLE
.NET Native should not be part of .NET Framework docs

### ISSUE THREAD

**Issue by rido-min** [dotnet/docs#6068]
.NET Native (as described) in this doc is a UWP tech only. This document can cause some confusion, specially the last sentence in the first paragraph:

>  *"..and that target the .NET Framework and Windows 10 to native code. "*

.NET Framework provides NGen and Ready2Run, both tools produce native images but there are important differences compared to UWP .Net Native.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06fd94b-aaba-d65f-1fc7-7131d6ff892f
* Version Independent ID: 3de244c3-d43b-be7a-bad3-b5e04a1c2fd8
* Content: [Compiling Apps with .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/)
* Content Source: [docs/framework/net-native/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by philcarbone** [comment]
uhhhhhh - Posted in June ;)

**Comment by mairaw** [comment]
@leecow who owns the .NET Native story? Should these docs simply be archived?

**Comment by leecow** [comment]
@jeffschwMSFT and @richlander - Who owns this story?

**Comment by gewarren** [comment]
@mcleanbyron or @jwmsft - These .NET Native docs seem to belong more in the UWP docs. They also need an edit pass to emphasize that .NET Native is for UWP and not for .NET Framework in general. What are your thoughts about the location of these docs? If you agree they should be moved, I could do an edit pass and create a PR in the windows-uwp-pr repo.

**Comment by gewarren** [comment]
This issue has been addressed.
