### ISSUE TITLE
sqlconnection is not available in .net core 2.1

### ISSUE THREAD

**Issue by leecow** [dotnet/docs#6069]
@DoubleCouponDay commented on [Sun Jun 17 2018](https://github.com/dotnet/core/issues/1699)

![image](https://user-images.githubusercontent.com/7555725/41513984-78cd40ae-72e6-11e8-962f-b7f612fc0a17.png)

![image](https://user-images.githubusercontent.com/7555725/41513987-807a22b8-72e6-11e8-980f-77c56a6fcc5c.png)

It is also missing when using the `system.data.sqlclient` namespace from nuget.
why is this?

---

@svick commented on [Sun Jun 17 2018](https://github.com/dotnet/core/issues/1699#issuecomment-397923446)

When I add a reference to the System.Data.SqlClient package, `SqlConnection` compiles for me on both .Net Core 2.0 and 2.1. Do you have an example (including .csproj) where it doesn't?

If the issue is only in the documentation, the it should be reported at [the dotnet/docs repo](https://github.com/dotnet/docs).

**Comment by mairaw** [comment]
We're actually removing that reference from the 2.0 docs as well. The support to document NuGet packages and appropriately show the supported platforms is coming on a later release of docs.microsoft.com.

**Comment by BillWagner** [comment]
@mairaw Is this fixed now?

**Comment by mairaw** [comment]
I missed this ping. Binaries are up-to-date and search shows sqlconnection for all releases of .NET Core as well .NET Platform Extensions. The ability to show the NuGet package is on the backlog and coming on a later release.
