### ISSUE TITLE
Second example demonstrates wrong thing

### ISSUE THREAD

**Issue by PeterWone** [dotnet/docs#6070]
The paragraph immediately before the second example states that the second example "uses a UdpClient to send UDP datagrams to the directed broadcast address 192.168.1.255, using port 11,000. The client sends the message string specified on the command line."

This is not true. The second example uses the Socket class directly to make a directed broadcast. It makes no mention of UdpClient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Using UDP Services](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mairaw** [comment]
Thank you for your feedback @PeterWone. We've added this issue to our backlog.

**Comment by DougSteiert** [comment]
This is still not fixed, despite being removed from Backlog.

**Comment by karelz** [comment]
@DougSteiert I see it fixed above the 2nd sample: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services
Here's the change from the PR: https://github.com/dotnet/docs/pull/8729/files#diff-2934d59f026fb408b6c3f7e13783b638R114

**Comment by PeterWone** [comment]
Add a sentence that explains _why_ the sudden switch from `UdpClient` to `Socket`. Is it just to show that UdpClient is a convenience wrapper, or is it because UdpClient doesn't expose the necessary flags, or just to show you can do it directly.

A silly question: how would you react to unsolicited PRs?

**Comment by mairaw** [comment]
We do welcome unsolicited PRs. We just encourage folks to file issues first before spending time on a large change though.

**Comment by PeterWone** [comment]
I was thinking in terms of worked examples. The docs team has the advantage of being able to ask the dev team about intention, which is why I think you are the only ones in a position to provide the _why_ and the intended patterns of use. In contrast to this, a bunch of worked examples prefaced with text explaining what is demonstrated is something that could be open sourced. For example,

Directed broadcast can be done using the Socket class
[Microsoft supplied example]

If you don't need to [special case] then UdpClient can make the code shorter and cleaner.
<community contribution needed quote issue #12345>
