### ISSUE TITLE
Error message in Exception when Open fails

### ISSUE THREAD

**Issue by ChuckGoehring** [dotnet/docs#6072]
Is this really your best effort:  "Unable to load the specified metadata resource" is all I get for an error message when Entity Client can't get data?  No InnerException, no details I can troubleshoot with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ceb0f6-dc32-0f86-69d2-8a2d70052c3e
* Version Independent ID: 4cab79b3-b240-e95c-835a-8b76b9979d42
* Content: [How to: Build an EntityConnection Connection String](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/how-to-build-an-entityconnection-connection-string)
* Content Source: [docs/framework/data/adonet/ef/how-to-build-an-entityconnection-connection-string.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/how-to-build-an-entityconnection-connection-string.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@ChuckGoehring It sounds like you may have intended to give Product Feedback (with the other link at the bottom of the article) and not documentation feedback. If that's not the case, how are you suggesting that we improve this article about building an EntityConnection connection string?

**Comment by douglaslMS** [comment]
@ChuckGoehring How are you suggesting that we improve this article about building an EntityConnection connection string?

**Comment by douglaslMS** [comment]
#please-close

**Comment by ChuckGoehring** [comment]
Yeah.  Docs are not the problem.

**Comment by douglaslMS** [comment]
@ChuckGoehring Don't hesitate to give Product Feedback (with the other link at the bottom of the article). We're all frustrated by unhelpful error messages!
