### ISSUE TITLE
Look & Feel 

### ISSUE THREAD

**Issue by MuraliManickam** [dotnet/docs#6078]
Hi Team, This documentation UI looks great! but add on the read mode kind of feature will help the user focus on the content clearly. It would be great if you remove the side navigation bar on both left & right on reading mode. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3850222-3c85-c851-006b-5236b41608d1
* Version Independent ID: a7734cb0-e62c-b9b5-961f-f757f8450967
* Content: [Hashtable and Dictionary Collection Types](https://docs.microsoft.com/en-us/dotnet/standard/collections/hashtable-and-dictionary-collection-types#feedback)
* Content Source: [docs/standard/collections/hashtable-and-dictionary-collection-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/hashtable-and-dictionary-collection-types.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @MuraliManickam! Given that this feedback is regarding the site and not the content itself, I've moved this issue to https://github.com/MicrosoftDocs/feedback/issues/449.
