### ISSUE TITLE
csproj: Docs on "link" attribute of "None" element?

### ISSUE THREAD

**Issue by nowherenearithaca** [dotnet/docs#6080]
After migrating a project.json to csproj, I'm trying to get the equivalent of "publishOptions" to work where I am using relative paths.  It seems related to the "link" attribute of the generated "None" element, but having a tough time tracking down how to use that.

btw - this is the generated element that does not seem to be working... and I think it's because of the relative paths (this is 1.1)

```
<None Update="..\wwwroot\**\*;..\foo1.config;..\;..\foo5.config;..\foo6.sh;">
  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
</None>

```
thanks!

**Comment by mairaw** [comment]
We don't have that yet @nowherenearithaca but they will come as part of the work we're planning for #2642.

**Comment by mairaw** [comment]
Duplicate of #2642
