### ISSUE TITLE
microservices.md inline code snippets missing

### ISSUE THREAD

**Issue by DavidBates** [dotnet/docs#6087]
# microservices.md inline code snippets missing

## Issues with Existing Topics

https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/microservices.md
I was trying to follow this today to set up a microservice but all of the code samples render as 
[!code-csharpTryParseExtension]
This makes it unable to follow as without the context of the code snippets you can't figure out what's going on. 

Thanks
David Bates

**Comment by pkulikov** [comment]
@DavidBates that .md file is the source that is processed and published on docs.microsoft.com. Please check the result page:
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices

It looks to contain all snippets in-place.

**Comment by mairaw** [comment]
Closing this issue since the content here on the repository is not meant to be the end product. It will have a lot of custom extensions that won't make sense for someone trying to read this here. This is the source for what shows up under https://docs.microsoft.com/en-us/dotnet/.
