### ISSUE TITLE
hmmm

### ISSUE THREAD

**Issue by megasuperlexa** [dotnet/docs#6094]
why would C# team spend time on such marginal things while the long anticipated features like record type get deferred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0320fd-c7ac-200e-7e50-6b3ddcaa6a52
* Version Independent ID: 6ea1af7f-2251-f05f-4834-5a00e57fc5fb
* Content: [What's new in C# 7.3](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3)
* Content Source: [docs/csharp/whats-new/csharp-7-3.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-3.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@megasuperlexa [records](https://github.com/dotnet/csharplang/blob/master/proposals/records.md) is still being planned.

Features like records affect more areas of syntax and semantics. It takes longer to make sure all the scenarios are considered and analyzed.
