### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#6095]
There's a typo in the "Example" section of this page:

> The following illustration shows the output of the cod example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9bcf7b-e10f-36ed-3cac-c19ca12b3155
* Version Independent ID: 0398755f-4e0d-abae-01b9-6bb839f135d4
* Content: [How to: Use Antialiasing with Text](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-use-antialiasing-with-text)
* Content Source: [docs/framework/winforms/advanced/how-to-use-antialiasing-with-text.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-use-antialiasing-with-text.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@ChrisMaddock thanks for the catch and reporting :).
