### ISSUE TITLE
Garbage collection, how much self tuning occurs?

### ISSUE THREAD

**Issue by ro-jo** [dotnet/docs#6097]
"The garbage collector is self-tuning and can work in a wide variety of scenarios. You can use a configuration file setting to set the type of garbage collection based on the characteristics of the workload"

You're saying it's self-tuning, immediately followed by 'set it yourself'.  Does an application without a setting for &lt;gcServer&gt; automatically switch between workstation and server modes as part of the self-tuning?  If so it means that performance should gradually reach its optimum level, but if not it could be a costly mistake to omit it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [Fundamentals of Garbage Collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for submitting your questions, @ro-jo.  

@maioni0, can you answer @ro-jo's questions? And do we need to provide some additional detail in the documentation about what self-tuning means and when adding or modifying the \<gcServer> and \<gcConcurrent> elements is appropriate?

**Comment by carehart** [comment]
@ro-jo asks a reasonable question but somehow no one ever responded to @rpetrusha's urging about it. @maioni0 or others?

**Comment by AlgorithmsAreCool** [comment]
@ro-jo 

IIUC,
Server GC is not the default and must be opted into. Once an application is started with either a Server or Workstation GC, it cannot be changed during the application's lifetime.

The self tuning aspects of the GC refer to collection timing and aggressiveness which enables the GC to deliver *good* performance across many types of workloads.

@rpetrusha I think you meant to call @Maoni0 instead of `@maioni0`

That being said, the doc could include a paragraph explaining that:
- Workstation GC favors making applications *feel* smoother by using smaller GC pauses and tries to keep overall memory usage lower. 
- Server GC favors making the application run as fast as possible overall even if that means keeping more memory and occasionally incurring longer GC pause times.

**Comment by Maoni0** [comment]
well, I dunno who @maioni0 is and not sure why they didn't respond. and I don't normally read the docs repo so the only way that I would know about an issue in this repo that requires my attention is if someone mentions @Maoni0.

@ro-jo 

> You're saying it's self-tuning, immediately followed by 'set it yourself'.

"self-tuning" and "set it yourself" refer to different things. 

"set if yourself" is referring to setting configs that do not require users to have GC internal knowledge. for example, the *kinds* of workloads  meaning "are you a process that tends to coexist with many other processes on the machine and does fairly irregular things(Workstation like workload), or a dominant/very active process that does fairly regular things (Server like workload)". it should be a simply decision on the users side.

self-tuning means for the kind of workload GC does not require you to tell it what GC mechanism to use, eg, you don't need to tell the GC things like "compact the heap when the free ratio is > X%" or "use this GC for young generation collections and this other one for old gen". 

does this help?

**Comment by rpetrusha** [comment]
Sorry about that, @Maoni0. I mistyped your GitHub alias.

**Comment by ro-jo** [comment]
Dear MSFT, thanks, you've been no help whatsoever.  Thanks for your lazy responses, you look as if you can't be bothered to type a sentence, so in future, please, just *don't* bother.  Spare me the ignominy.

In addition to the paradoxical sentence I highlighted, you answer with: "The self tuning aspects of the GC refer to collection timing and aggressiveness which enables the GC to deliver good performance across many types of workloads." right after implying you must choose the garbage collection based on your workload.  Congratulations.

@Maoni0, in short: no it doesn't help.  You too: "... configs that do not require users to have GC internal knowledge ... " and then " it should be a simply decision on the users [sic] side.". What?

Me: Server GC is slower to initialise and consumes more resources at startup. It improves performance of longer running, resource intensive processes.

The point of my question was to highlight a poorly worded explanation and that it would be useful if there was just one type of garbage collector that could switch to server or workstation mode as part of its self-tuning.  Apart from that, what interest do I have in self-tuning?  Can I control it? Is it a unique innovation in .Net, that no other OS or framework employs? Or is it just the way all high-level memory management systems work?  DON'T ANSWER! Thanks.

**Comment by manigandham** [comment]
@ro-jo 

The GC mode can't be changed after the application has started. It's used to categorize the workload on the machine. Generally it should be `Server` if it's the only program running and `Workstation` if it's running along with other programs. The application has no idea about this and relies on you to know where and how the program is deployed, that's why it's a setting that you must configure.

Once the basic workload type is configured, the GC can then use that as a guide and will optimize itself as the program runs to ensure collection keeps pace with allocation and pauses are as small as possible. These are the internal settings that the GC will "self-tune" but you can still override if you really need to.

Does that help?

**Comment by ro-jo** [comment]
Why do the most vacuous attempts at answers end with the rhetorical phrase 'does this/that help?' ?

I can raise issue in every statement of every such answer on this page. Here are a few, I haven't got time to waste on all of them:

" it should be Server if it's the only program running": that would be never.

" Workstation if it's running along with other programs": that would be always.

"The application has no idea about the environment and relies on you to tell the program how it's deployed": Yes, it (the non-sentient piece of programming) can procure 100% of such information, to reiterate, 100%.

"Once the basic workload type is set": no such thing.  Try to consider the marginal cases that fit somewhere in between big-data/long-running service and short-lived/cooperative applications.

To be honest, the only thing I was expecting to happen was somebody would have a look at the wording and change it.  It's waffle.  But no, you seem to think I've put my projects on hold for nine months waiting for you to tell me what gcServer means - and such wonderful answers they are.  Maybe after a few years you'll make a garbage collector that's able to self-tune properly in all scenarios without hard-coded parameters, and maybe you won't.  Maybe you'll decide there's no need to mention self-tuning at all, since it's useless information.  I'm taken aback by the absurdity that's ensued nine months after raising the point.

**Comment by manigandham** [comment]
The setting is rather clearly described in the existing documentation if you read past the single sentence you take issue with.

It comes down to how resource-intensive the GC should be, which is up to you to decide if you're running many other applications on the same server. There's obviously never only one process running on the entire machine but determining whether a server is being used for a single application or not is a rather straightforward part of app deployment.

I'm not sure how you expect the program to know these kinds of details automatically, and it's no different than how an OS provides CPU affinity and process priority for you to control resources. If you need a middle-ground then stick with Workstation, which is the default anyway.

Regardless, we can't read your mind and your responses show both confusion and disagreement as if you know better so I'm not sure what you were expecting. Your attitude is definitely not conducive to getting any help though. Good luck to you.

**Comment by ro-jo** [comment]
@manigandham It's almost as if you haven't read anything I've written.

Look at your answers and then the original question.

The only place I go for help is stackoverflow, so no big deal, it sticks to answering the question and context.

**Comment by AlgorithmsAreCool** [comment]
I regret commenting on this thread.

And for context, I don't work for Microsoft.

**Comment by ro-jo** [comment]
@rpetrusha thanks, I totally agree with you, my comments were unacceptable. Deleted the offending material, apologies all round to those I offended.

**Comment by rpetrusha** [comment]
Thank you, @ro-jo, for your response and apology. We look forward to your continuing interest in our documentation and participation in our GitHub repos.
