### ISSUE TITLE
1

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#6098]
@kakisoft commented on [Fri Jun 15 2018](https://github.com/dotnet/docs.ja-jp/issues/116)

ビハインドコードも併せて掲載頂けると幸いです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a1b56804-34b3-7133-437f-34f7ad919b72
* Version Independent ID: f0490a67-2a64-f2b0-a8c2-13dfe5a6a686
* Content: [Model-View-View Model を利用した汎用性のあるクラス ライブラリの使用](https://docs.microsoft.com/ja-jp/dotnet/standard/cross-platform/using-portable-class-library-with-model-view-view-model)
* Content Source: [docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

---

@gosali commented on [Mon Jun 18 2018](https://github.com/dotnet/docs.ja-jp/issues/116#issuecomment-398080750)

こんにちは、@Kakisoft 

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
Moving this one here, since the end user says they'd appreciate information about Code-Behind Model
best

**Comment by mairaw** [comment]
Given that this topic is about PCL and that we're not going to deprecate the PCL topics, I'm inclined to close this as won't fix. Thoughts @BillWagner @rpetrusha?

**Comment by rpetrusha** [comment]
You meant to say that we're going to deprecate the PCL topics, I think. I agree, @mairaw.

**Comment by mairaw** [comment]
Yep, that's what I meant. Fixed that now. So I'm closing this as won't fix.
