### ISSUE TITLE
I would like to see an example of simple binding on this help page

### ISSUE THREAD

**Issue by sllewellyn13** [dotnet/docs#6099]
if a value changed on a text control, how do I make a notification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 695fa324-6701-d549-57c4-20bb6135a692
* Version Independent ID: 929643b5-48ae-ca69-a8c8-0f1af0b09f5a
* Content: [Change Notification in Windows Forms Data Binding](https://docs.microsoft.com/en-us/dotnet/framework/winforms/change-notification-in-windows-forms-data-binding)
* Content Source: [docs/framework/winforms/change-notification-in-windows-forms-data-binding.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/change-notification-in-windows-forms-data-binding.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
@merriemcgaw, should a sample be created to help with this?
