### ISSUE TITLE
Tools section in doc needs love

### ISSUE THREAD

**Issue by patrickjamesbarry** [dotnet/docs#610]
I am pretty excited about how you can write your own tool, however I feel like the docs only scratch the service on helping a user get started.   Here are 2 tickets I have been posting my questions to, that you can use to help enrich what  you currently have: https://dotnet.github.io/docs/core-concepts/core-sdk/cli/extensibility.html

Some of it is covered in these pages and I must have overlooked or misunderstood it at the time. Other things are not even mentioned.

https://github.com/dotnet/cli/issues/3691#issuecomment-228412403
https://github.com/dotnet/cli/issues/3467#issuecomment-224993875

**Comment by mairaw** [comment]
Thanks @patrickjamesbarry. I'll take a look at the issues you've posted and see how we can improve that doc.

**Comment by BillWagner** [comment]
Closing this. It's covered here: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility
