### ISSUE TITLE
Unknown switch error when running example code

### ISSUE THREAD

**Issue by ragnarstolsmark** [dotnet/docs#6103]
Executing the line
dotnet run --project /projects/proj1/proj1.csproj
returns an error saying unknown switch. I think it should be corrected to:
dotnet run --project ./projects/proj1/proj1.csproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3f4227-cd9b-7b1c-7e1b-ffb3d42ae496
* Version Independent ID: 7e78f9f5-f77c-828d-ef76-8ef8593d5803
* Content: [dotnet run command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-run.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-run.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you @ragnarstolsmark for your feedback. We'll investigate this issue.
