### ISSUE TITLE
Sequence of steps to create a FormClosing  Event Handler

### ISSUE THREAD

**Issue by sbrunner78** [dotnet/docs#6104]
I need to create a form closing event handler - I do not know how to create one.
I know how to create a form load event handler, but I do not know how to create form closing event handler.
It would be great if you would add a brief amount of information to fill this information gap on implementation!    Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27c734f-63d9-9094-98a2-da569c542e8f
* Version Independent ID: 3ec6273d-925f-e83d-a72c-dff56ba265d0
* Content: [FormClosingEventHandler Delegate (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.formclosingeventhandler?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/FormClosingEventHandler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/FormClosingEventHandler.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Hi, @sbrunner78, check out [Handling and Raising Events](https://docs.microsoft.com/en-us/dotnet/standard/events/index?view=netframework-4.7.2). This should help you with this task.
