### ISSUE TITLE
Need Person class definition to complete example

### ISSUE THREAD

**Issue by bobrundle** [dotnet/docs#6106]
Without a definition of the Person class, the example is incomplete and does not work properly.  For example without a ToString() override in the Person class, the tab headers simply have the class name.  You need a Person class that looks something like this...

 public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HomeTown { get; set; }
        public override string ToString()
        {
            return LastName + ", " + FirstName;
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1a967e-bfe6-71ee-fa0c-8b2d9ad947f4
* Version Independent ID: 56eacf8e-6b7c-5d8f-efa8-022ff7b27ed3
* Content: [TabControl.ContentTemplateSelector Property (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tabcontrol.contenttemplateselector?view=netframework-4.7.2#examples)
* Content Source: [xml/System.Windows.Controls/TabControl.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/TabControl.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks, @bobrundle, for letting us know! I've added this to the next sprint to get resolved.

**Comment by JRAlexander** [comment]
I've merged this and the changes should be live in the next few days.
