### ISSUE TITLE
I don't see examples using Span<T>, but article insist I do

### ISSUE THREAD

**Issue by Atomosk** [dotnet/docs#6107]
&gt;In this article, you see examples using Span&lt;T&gt; for simplicity.
Probably should be link or something, maybe this one? https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef84d483-1591-6ea4-83a7-fd3c2b1f081b
* Version Independent ID: 0b7f8ccd-a529-430d-416b-03480ea4883f
* Content: [Reference semantics with value types](https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types)
* Content Source: [docs/csharp/reference-semantics-with-value-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/reference-semantics-with-value-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks, @Atomosk, for pointing this out! We've added it to our list to take care of.

**Comment by Thraka** [comment]
I think this is no longer valid.
