### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by brick20** [dotnet/docs#6110]
I've attempted this twice and each time when I restart my computer it will come back on without .NET Framework 3.5 installed properly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
@brick20, were you able to work through the troubleshooting steps at the bottom of the article?

**Comment by NiksNT** [comment]
Hello i need help. I don't know if i got a virus but that pop up is annoying me. And it keeps on opening ads on my main browser. I would like to know how to fix this. thanks!

**Comment by NiksNT** [comment]
And when i download that thing my Laptop restarts and the sceen is black. But when i take out the battery and put it back in everything works fine but the thing keeps poping up again.

**Comment by rpetrusha** [comment]
What are you trying to do, @NiksNT? And what is the popup?

**Comment by mairaw** [comment]
Is this the pop-up you're referring to?
![image](https://user-images.githubusercontent.com/12971179/42833670-994ace8a-89a9-11e8-9d3c-5ea7129f5269.png)

That means that you're trying (or tried) to install a software that requires .NET Framework.

**Comment by v-atian** [comment]
Any ideas about the dialog? I use the method to install .net freamwork 3.5 on Windows 10 RS5 Release.
![net35](https://user-images.githubusercontent.com/12235523/48823141-99302c00-ed14-11e8-9bf3-4b4ad5452922.png)

**Comment by mairaw** [comment]
@v-atian a couple of posts online suggest that you might need to use the DISM method when you get that error code. Have you tried that?

For more informaiton, see https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism.

**Comment by mairaw** [comment]
Closing this since we haven't heard back from the original author.
