### ISSUE TITLE
Remove estimated read times from docs.microsoft pages

### ISSUE THREAD

**Issue by edfallin** [dotnet/docs#6111]
The estimated read times for docs articles are all absurdly low.  The effect is either to make a reader feel like an idiot because they can't read 1,000-plus words in 3 minutes **(!)**, or to make the reader suspect that it's all marketing to keep TL;DR-type people at the site.  Both bad.<p>

Instead of making these times more realistic, I suggest they be dropped completely, or that a click-once, cookie-after setting be arranged to hide them for those of us who are driven to distraction by them.<p>

I'm not complaining particularly about the _3-D Graphics Overview_, though it is a clear example of a reading time that is far too small.  Rather, I'm saying that **_all_** docs sites have bad estimated times.<p>

BTW, I regret that there's no more sensible place to register this complaint than here, but every other online avenue I tried led nowhere.<p>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed648cc-8df9-5cb9-3745-7e8a2cd024b4
* Version Independent ID: 27e10d39-858f-2e7a-23d9-5d8a62faf9ee
* Content: [3-D Graphics Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/3-d-graphics-overview)
* Content Source: [docs/framework/wpf/graphics-multimedia/3-d-graphics-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/3-d-graphics-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@edfallin 

>BTW, I regret that there's no more sensible place to register this complaint than here, but every other online avenue I tried led nowhere.

It looks that the perfect place for this issue is the [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback/issues) GitHub repository.

**Comment by mairaw** [comment]
Thanks for your feedback @edfallin. For general site feedback, there's a link on the bottom of every page that takes you to the right repo. I've moved your issue to https://github.com/MicrosoftDocs/feedback/issues/457.

**Comment by edfallin** [comment]
I'm sorry to see this has been closed, but at any rate next time I'll know where to comment on overall topics.
