### ISSUE TITLE
Document that setting "bypassonlocal" undoes "scriptLocation"

### ISSUE THREAD

**Issue by HornetBlack** [dotnet/docs#6112]
This document doesn't document an important gotcha with setting the proxy settings.

https://blogs.msdn.microsoft.com/rickrain/2011/03/25/why-scriptlocation-may-not-work-when-pointing-to-a-proxy-script-file-in-your-application-config-file/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09aeb831-81e3-0216-4ef7-b4cb40105290
* Version Independent ID: 32c08202-f73f-5bff-9e68-451349f9eb74
* Content: [&lt;proxy&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/proxy-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @HornetBlack.  @davidsh, can you comment on this. Should the documentation note that you should not use **bypassonlocal** if you are setting a **scriptLocation**?

**Comment by davidsh** [comment]
>Should the documentation note that you should not use bypassonlocal if you are setting a scriptLocation?

Yes.  Using `scriptLocation` implies that all logic for mapping a destination URI to a proxy server is handled by the JavaScript method in the PAC file pointed to by `scriptLocation`.  That includes whether or not a proxy might be bypassed if the destination URI is considered as 'local'.
