### ISSUE TITLE
There are three (section) headlines without any content

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6118]
What’s the point of these without content? If information is missing here it should at least describe what is missing.
The headlines are:
* Compiling the Code
* Robust Programming
* .NET Framework Security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d1f4c0-e9a3-71b9-0bf1-ebefc8aeab94
* Version Independent ID: 86aa22d9-7e09-3226-aa7a-ff5d9c981d33
* Content: [How to: Group, Sort, and Filter Data in the DataGrid Control](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control#robust-programming)
* Content Source: [docs/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for bringing that to our attention @ite-klass. I'll remove those. They were probably part of an old template used by our old publishing system.
