### ISSUE TITLE
Programmeur analyste.

### ISSUE THREAD

**Issue by RicardoAMendoza** [dotnet/docs#6119]
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e813a38-d487-25dc-b70d-23fca9c47221
* Version Independent ID: 92fb3bd2-56a5-e060-8056-491aab145d26
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance)
* Content Source: [docs/csharp/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for the feedback, @RicardoAMendoza. I'm glad that you liked the topic!
