### ISSUE TITLE
Verbosity levels

### ISSUE THREAD

**Issue by TPucke** [dotnet/docs#6120]
Please add some more specific description of what the verbosity levels mean, or at least a link to somewhere that the details can be found.  

I got here trying to learn which levels I can use to get console output of my tests, and there are other useful things I'm sure that this would clear up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @TPucke. We've added this to our task list. 

We'll decide whether we add this content to the docs or if we just link to https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity#fields where a description of each value can be found, given this is a MSBuild concept. /cc @mikejo5000

**Comment by TPucke** [comment]
Thanks, that's useful.  I'm still not totally sure about my original question, which might be better asked elsewhere.  Looking for the console output from my tests, which I can't seem to find..  Can that be incorporated somehow?

**Comment by HeroMaxPower** [comment]
Hi TPucke try giving 
dotnet test --logger "console;verbosity=detailed"
a go, i was able to get my messages from the following asserts Assert.Inconclusive("Inc Message"), Assert.Fail("Fail Message") from the console output, which im guessing what you need. Microsoft needs to put an example of console verbosity to return messages that's specified in our code.

**Comment by danmosemsft** [comment]
Note that unlike MSBuild, you can't use contractions, so eg
-l "console;v=d"
does not work, it has to be eg
-l "console;verbosity=detailed"

**Comment by HeroMaxPower** [comment]
It would be nice if Microsoft would create an example on this page of the output using "console;verbosity=detailed" in regards to tests and all of the test state outcomes (Pass, Fail, Inconclusive... etc) that show in the console output. I spent a large amount of time trying to figure this out using the contractions with no success then tried with the long hand that danmosemsft described above it magically got what i was looking for. 

I would say from a automation testers perspective with this article they a looking for mostly examples of 

-runsettings combinations
-filter combinations
-verbosity examples
