### ISSUE TITLE
Issues in first Remarks section

### ISSUE THREAD

**Issue by chrisjbreisch** [dotnet/docs#6122]
The first Remarks section doesn't explicitly state which overloads of the Substring() methods are being discussed. That makes the paragraph rather confusing:

You call the Substring method to extract a substring from a string that begins at a specified character position and ends at the end of the string. ... To extract a substring that begins at a specified character position and ends before to the end of the string, call the Substring method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9b701f-ffc0-3935-8d0e-179ec32b8b6d
* Version Independent ID: 246dfe08-450e-711b-cd0a-a7603719c31f
* Content: [String.Substring Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.substring?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.String.Substring);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@chrisjbreisch Hi Chris! I'm working on this right now. Thanks for noticing this issue and reporting it!
