### ISSUE TITLE
Add a doc about DPI Awareness in Visual Studio 

### ISSUE THREAD

**Issue by OliaG** [dotnet/docs#6123]
We need to create documentation that: 

- Provides context about why this issue occurs.
- Showcases examples of what the issue might look like in real life.
- Explains how to resolve the issue (with either of the two current solutions outlined in the “Current Solution” section).
- Points out that the mode is only applicable for the duration of the session. Once the user restarts VS they will be back in DPI Aware Mode. 
- Is pointed to by this link: https://go.microsoft.com/fwlink/?linkid=875609, tool for editing fwlinks -http://aka.ms/fwlink.

All info and screenshots can be found in Disable DPI Awareness doc. Please ask for the access if you don't have it already. See the update from 6/20/18 at the end of the doc for the most recent solution.

**Comment by mairaw** [comment]
@OliaG would this be more appropriate for the VS docs then? /cc @gewarren

**Comment by mairaw** [comment]
Per @merriemcgaw's feedback, moving to the VS docs repo
