### ISSUE TITLE
VB example uses reserved words

### ISSUE THREAD

**Issue by ocdtrekkie** [dotnet/docs#6129]
I am guessing this is a "it's generated based on another language" type issue, but I found it baffling that [to] and [from] were defined as variables in the example here. A bit of investigation led to that it's a way to create variables which use reserved words which you generally cannot use for your own objects. Apparently you shouldn't do this unless you have to, and there's no real reason you have to here.

I'm not sure how often this occurs in .NET example docs, but I guess my concern would be that if the examples demonstrate bad behavior, people implementing code based on those examples may replicate it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3331b9f-b4df-b76e-fffd-8ff9d327faa2
* Version Independent ID: 74837a55-0389-7547-ee9d-8bd2a28e531d
* Content: [SmtpClient Class (System.Net.Mail)](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.Net.Mail/SmtpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Mail/SmtpClient.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **bobdel**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ocdtrekkie. Although the [use of reserved words in variable names is supported, it is not recommended](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/keywords-as-element-names-in-code). It is not widespread in our Visual Basic example code base, although it is most commonly encountered in legacy code.
We'll add this issue to the backlog, and also add it to  [Projects for .NET Community Contributors](https://github.com/dotnet/docs/projects/35).

**Comment by ocdtrekkie** [comment]
I could probably do a PR and look through some samples likely to also be affected (mail ones, specifically).

Is there guidance on how VB samples' variables should generally be named? I am of course used to the old school prefix style, strTo and strFrom, but they don't seem to be the trend here. I was thinking MailTo and MailFrom would be adequate, though camelCase might be the right way to go: The example already contains a mailSent variable, so mailTo and mailFrom may be good.

**Comment by rpetrusha** [comment]
The old str... and int... convention is no longer used, @ocdtrekkie. Camel casing is preferable, so mailTo and mailFrom are good. And thanks for being willing to help with this.

**Comment by ocdtrekkie** [comment]
Heh, I only found the one, since the code snippet is used in both pages. But I am tempted to convert some of the other C# mail samples to VB since I am sad about the lack of VB parity on mail sample code. ;)

**Comment by rpetrusha** [comment]
@ocdtrekkie, if you'd like to convert some of the C# mail samples to Visual Basic, we'd certainly welcome your contribution. There really should be parity between VB and C# in our managed reference documentation, so that would be a valuable contribution.
