### ISSUE TITLE
WaitAsync() overload documentation is inconsistent

### ISSUE THREAD

**Issue by Keboo** [dotnet/docs#6130]
Most of the SemaphoreSlim.WaitAsync methods indicate that they may throw an ObjectDisposedException if "The current instance has already been disposed." However the WaitAsync() and WaitAsync(TimeSpan, CancellationToken) overloads do not call this out. 

Examining the code from https://source.dot.net/#System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs,314 seems to indicate that all overloads of WaitAsync can throw the ObjectDisposedException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74a9f68-b637-ced3-c1b0-93701179da74
* Version Independent ID: cd4ed6ba-7d50-b448-0682-517ea576218d
* Content: [SemaphoreSlim.WaitAsync Method (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync?view=netcore-2.1#System_Threading_SemaphoreSlim_WaitAsync)
* Content Source: [xml/System.Threading/SemaphoreSlim.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/SemaphoreSlim.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @Keboo. All overloads of WaitAsync can in fact throw an ObjectDisposedException, as can each of the overloads of Wait. We've opened dotnet/dotnet-api-docs#310 to add the missing exception information.
