### ISSUE TITLE
BackgroundService class running in Docker linux container

### ISSUE THREAD

**Issue by johnabbott72** [dotnet/docs#6131]
I have an issue when running a BackgroundService in a Docker linux container.  Is there any way to achieve a graceful shutdown?  I am sending a docker container stop command and after a short pause the system shuts down without triggering a cancellation token.  I need to have notice so I can try to prevent my long running process from shutting down mid-process.  The UseShutdownTimeout also seems to have no effect.  Any advice on how to get the graceful shutdown process working with docker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by StefH** [comment]
Maybe acting on **System.Runtime.Loader.AssemblyLoadContext.Default.Unloading** can fix your issue?

``` c#
System.Runtime.Loader.AssemblyLoadContext.Default.Unloading += ctx =>
{
    Stop("AssemblyLoadContext.Default.Unloading");
};
```

For a example see : https://github.com/WireMock-Net/WireMock.Net-docker/blob/master/StandAlone.NETCoreApp/Program.cs#L24

**Comment by mvelosop** [comment]
Hi @johnabbott72, I'm pinging @eiximenis, he might have some insights on this subject.

**Comment by eiximenis** [comment]
Hi @johnabbott72 
Not sure if I understand your issue. I implemented a basic IHostedService using the instructions in https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice and it worked without problems:

![image](https://user-images.githubusercontent.com/5191049/53491980-04b63200-3a98-11e9-8c0e-ad70a7349ccf.png)

If you share your HostedService code maybe could try to repro the issue!

**Comment by mvelosop** [comment]
Thanks @eiximenis, 

If I understood it right, the key part here is starting the background tasks with a token from CancellationTokenSource, so processes can be signaled to terminate when the .Cancel() method is called from the BackgroundService.StopAsync().

And the BackgroundService.StopAsync() is called by the runtime, right?

**Comment by mvelosop** [comment]
@StefH, If I understood your code, it could be a way to call `BackgroundService.StopAsync()` upon app pool flushing on IIS, is that right?

**Comment by amirxnz** [comment]
I am getting this issue as well.
I have a hosted service that is reading messages from azure event hub, I run it in docker, however when i issue a docker stop, the stopasync does not get called and the cancellation token does not change to true.

@johnabbott72  have you found a fix for your issue? 
@eiximenis Can you share your example? The only one i found is a web host but that is not my scenraio.

What information should I share to help? Its .net 3, my worker is inheriting from BackgroundService. I can see that StartAsync gets called.

This is my Main.cs:

public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build() .Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                        .AddEnvironmentVariables().Build();
                })
                .ConfigureServices((hostContext, services) => { services.AddHostedService<Worker>();    });
       
    }


Thanks for any assistance!

**Comment by amirxnz** [comment]
@eiximenis Any chance for some direction? 

Many thanks!

**Comment by mvelosop** [comment]
Hi @johnabbott72, @amirxnz,

I created a very simple console app running the generic host with logging to trace the shutdown process in this repo: https://github.com/mvelosop/explore-hosted-services

The README in the repo should get you going.

You can explore shutting down the app from Windows and Docker.

In the sample I'm registering the services with:

```cs
services.AddSingleton<IHostedService, ServiceA>();
```

But `services.AddHostedService<Worker>()` should work as well.

Hope this helps.

**Comment by amirxnz** [comment]
@mvelosop thank you for your help,
So i have been working on this for the last couple of days, and now I'm actually thinking the problem may be caused by the visual studio docker run command? 

Did you do anything to adjust how that command is run? 

Thanks!

**Comment by mvelosop** [comment]
Hi @amirxnz,

Nope, well, actually I did it all from the command line, there's too much "magic" for me when running from VS.

There's one important detail to keep in mind if you're looking at logs. You have to make sure that logs are flushed on app shutdown, otherwise you might be loosing some events.

That's what the `finally` here is for:

```cs
try
{
    await builder.RunConsoleAsync();
}
finally
{
    Log.CloseAndFlush();
}
```

Hope this helps.

**Comment by amirxnz** [comment]
@mvelosop I guess that was my mistake because it makes no sense for visual studio to block the sigterm but apparently it does

**Comment by mvelosop** [comment]
Well, didn't now that either but it's good to know!

Glad you could solve this 😊
