### ISSUE TITLE
Is global.json preferred alternative to setting RuntimeFrameworkVersion?

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#6148]
If I have a few projects in the solution, e.g. unit/ integration tests additionally to main application,
will be better to add global.json Instead of set RuntimeFrameworkVersion to each project?
The idea from https://github.com/aspnet/Home/issues/3221#issuecomment-398777990
global.json to my Project with:

{
    "sdk": { "version": "2.1.300" }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a901ae9f-cc78-b5de-a031-b4671c7a85ac
* Version Independent ID: 89276cf0-167d-c108-f9d6-f5bfe1317851
* Content: [Self-contained deployment runtime roll forward](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection)
* Content Source: [docs/core/deploying/runtime-patch-selection.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/runtime-patch-selection.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
I think the new article that @BillWagner is working on is going to explain this in more detail. See PR #6060 

@KathleenDollard please correct me if I'm wrong but my understanding is that they're orthogonal to each other. With global.json you specify which SDK version you're going to be using and with \<RuntimeFrameworkVersion> you specify the minimum runtime patch version.

/cc @dsplaisted

**Comment by KathleenDollard** [comment]
@mairaw is correct. 

global.json does not affect the runtime framework in anyway. 

global.json is a mechanism for determining the CLI/SDK that is used (including the version of MSBuild) that is used to create your application.

**Comment by dsplaisted** [comment]
> with <RuntimeFrameworkVersion> you specify the minimum runtime patch version.

@mairaw It's not actually the minimum version, if you set this property it will use that specific version even if a later one is also available.

@MNF If you want to set the `RuntimeFrameworkVersion` for all of your projects, I'd suggest using a Directory.Build.targets file.  See here for more information: [Customize your build](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build)

**Comment by BillWagner** [comment]
@MNF It looks like your question has been answered. I'm closing this issue. If you have further questions, re-open it and let us know what more information you need.
