### ISSUE TITLE
ByVal with ReturnInteger type parameter

### ISSUE THREAD

**Issue by jmdurdin** [dotnet/docs#6152]
There is no mention of event functions that are implemented with a signature such as (ByVal arg as MSForms.ReturnInteger) or similar, when clearly the purpose is to return a value to the caller, despite using ByVal.  It would be helpful if the documentation addressed this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd82582c-13a1-e919-1817-e410de1d14f7
* Version Independent ID: 9631601d-27e5-8291-4e70-f6b586f06c89
* Content: [Passing Arguments by Value and by Reference (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/passing-arguments-by-value-and-by-reference)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/passing-arguments-by-value-and-by-reference.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/passing-arguments-by-value-and-by-reference.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jmdurdin. We added this to our backlog.
