### ISSUE TITLE
The link "Global.asax Syntax" is dead

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6155]
404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7485198-5969-5e09-e56c-ee668ad8c377
* Version Independent ID: 57e212ea-3ed8-eecc-f871-d742b78fef2c
* Content: [SessionStateModule.Start Event (System.Web.SessionState)](https://docs.microsoft.com/en-us/dotnet/api/system.web.sessionstate.sessionstatemodule.start?view=netframework-4.7.2)
* Content Source: [xml/System.Web.SessionState/SessionStateModule.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.SessionState/SessionStateModule.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
The link doesn't 404 for me. Maybe was just a glitch @ite-klass?

**Comment by ite-klass** [comment]
Verified it is working now 🤷‍♂️
