### ISSUE TITLE
F# Powertools?

### ISSUE THREAD

**Issue by davidn-sytelco** [dotnet/docs#6159]
I think the reference and link to the Visual F# Power Tools is incorrect, it doesn't seem relevant and is also quite outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6b61e5e-bbb2-259d-44c3-39f7e61042f9
* Version Independent ID: 0a5737cc-a340-d48b-090f-5cdec96f30c4
* Content: [Asynchronous Workflows (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/asynchronous-workflows#feedback)
* Content Source: [docs/fsharp/language-reference/asynchronous-workflows.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/asynchronous-workflows.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks for the report @davidn-sytelco, we'll get that removed.
