### ISSUE TITLE
Unclear remark about unsupported async APIs

### ISSUE THREAD

**Issue by svick** [dotnet/docs#6161]
The *Async* subsection of the section [*Unsupported scenarios and APIs*](https://docs.microsoft.com/en-us/dotnet/framework/net-native/migrating-your-windows-store-app-to-net-native#unsupported-scenarios-and-apis) of this article says:

> Threading logic in overloads of Task IAsync isn't supported. 

I have no idea what this means: What's "threading logic"? What does "overloads of Task IAsync" mean? What is IAsync in the first place?

I think this sentence should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf5fdf4-e2bc-8719-8163-1f6cfbab6d44
* Version Independent ID: baef07a5-5fb9-3059-4782-0356d65ebb3a
* Content: [Migrating Your Windows Store App to .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/migrating-your-windows-store-app-to-net-native)
* Content Source: [docs/framework/net-native/migrating-your-windows-store-app-to-net-native.md](https://github.com/dotnet/docs/blob/master/docs/framework/net-native/migrating-your-windows-store-app-to-net-native.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
@stephentoub, do you know what the sentence meant to say? Are there any limitations on async that are unique to .NET Native?

**Comment by stephentoub** [comment]
I have no idea what that sentence is meant to mean.

**Comment by rpetrusha** [comment]
Thanks, @svick, for opening the issue. And thanks, @stephentoub, for responding. I've opened a PR to remove the text.

**Comment by svick** [comment]
Is there someone from the .Net Native team who could know the answer who we could ask?

**Comment by rpetrusha** [comment]
@svick, I assumed that @stephentoub would know, which I think is the case. @ViktorHofer, is there anyone else who might know how async support in .NET Native differs from .NET Framework or .NET Core?

**Comment by ViktorHofer** [comment]
@joshfree might know someone
