### ISSUE TITLE
Fixed it myself :)

### ISSUE THREAD

**Issue by stevegiergiel** [dotnet/docs#6165]
After reporting this as a fault, and you guys 'fixing it', it still seemed to be failing to show more than 1 record for me. It may just be a configuration or environment thing, but for me changing the line 
where nameFields[2] == scoreFields[0]
to
where nameFields[2].TrimEnd() == scoreFields[0]
brings back the reported output.
 
By stepping through I eventually saw the trailing space (maybe end of line char even) resulting from the name.Split(',') - was it just me that saw that? Are you working on a different version of Split? or is the end of line character or trailing space thing not an issue on your systems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d009f3e-1b1d-4056-677d-4e2095be073c
* Version Independent ID: c4415933-e83d-ee62-23cf-dcb8513a3a42
* Content: [How to: Join Content from Dissimilar Files (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@stevegiergiel thanks for catching the fault in this topic as well. The #5929 fix has corrected the code in [another topic](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq)
