### ISSUE TITLE
I am unable to use DirectX3d in vb.net 2017

### ISSUE THREAD

**Issue by john02813** [dotnet/docs#6170]
I tried to do that "draw a Triangle" program in vb.net 2017 with DirectX 9 but unable to use directx3d.dll to go into reference section.  I can't run the program without a reference to the dll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8d9608-e477-faeb-a524-1c1f6ec4a4d6
* Version Independent ID: 5fa3bfa5-8107-d0aa-87b9-4ae688f7ce60
* Content: [How to: Reference COM Objects from Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/com-interop/how-to-reference-com-objects)
* Content Source: [docs/visual-basic/programming-guide/com-interop/how-to-reference-com-objects.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/com-interop/how-to-reference-com-objects.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
@john02813 If your main goal is to use DirectX with VB, you may find the [SharpDX](https://www.nuget.org/packages/SharpDX/4.1.0) NuGet package is a better path to choose. Can you try that and comment on your thoughts?

If that's not the end goal, can you add more details regarding what you are trying to accomplish?

**Comment by john02813** [comment]
I fixed it awhile ago.  I just had to run it in Version 2 of the .net  Also I removed the check mark when the error message pops up.  I am back using VB 6 now.  Thank you for the reply
