### ISSUE TITLE
Change "thread local" to partition local in Parallel.For, Parallel.ForEach

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6174]
# Change "thread local" to partition local in Parallel.For, Parallel.ForEach

The term "thread-local" is used in describing the operation of select Parallel.For and Parallel.ForEach overloads that partition data for asynchronous processing. Thread-local, however, isn't completely accurate, since multiple partitions may run on the same thread. A better alternative is "partition local". (Note that neither is fully accurate, though.)

For details, see PR #6132.

//cc @stephentoub

**Comment by mkwsofteng** [comment]
what does it means both are not fully accurate. Then how can we trust on if both are not trusty to use?
