### ISSUE TITLE
Threading: Eliminate duplication

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6180]

**Comment by rpetrusha** [comment]
# Threading:Eliminate duplication

There are separate sections for [C#](https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/concepts/threading/index) and [VB](https://docs.microsoft.com/en-us/dotnet/articles/visual-basic/programming-guide/concepts/threading/), even though neither section covers language features. Both should be merged into a single doc set in the .NET Guide.

**Comment by pkulikov** [comment]
@rpetrusha those two topics should be moved and integrated into the following .NET Guide part?
https://docs.microsoft.com/en-us/dotnet/standard/threading/

It's possible that that section in .NET Guide already covers some of the topics in the language sections. So, those might be even merely removed.

I would like to work on that.

**Comment by rpetrusha** [comment]
It would be wonderful if you would work on consolidating the content, @pkulikov. Yes, the .NET Guide at https://docs.microsoft.com/en-us/dotnet/standard/threading/ is the target. At least some of the content in the C# and VB sections is duplicated there, so some topics probably can be removed, while parts of others probably have to be copied-and-pasted into the appropriate locations in the .NET Guide. This is a classic problem of in this case triplication -- each doc set has taken on a life independent of the others.

**Comment by pkulikov** [comment]
OK, @rpetrusha please assign this issue to me, then. Probably, I'll create several PRs to move/remove all of the topics.

**Comment by rpetrusha** [comment]
I've assigned it to you, @pkulikov.

**Comment by rpetrusha** [comment]
One other thing that I neglected to mention, @pkulikov. Some of the content might best be moved to the API reference. For example, the [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-timers) and [VB](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/threading/thread-timers) Thread Timers topic should probably be merged into the System.Threading.Timer class documentation, since the focus of the topic is its example.

**Comment by pkulikov** [comment]
@rpetrusha I'm working right now on the timer topic :). Have had the same question: should all three existing topics be removed from the docs, as the API topic provides a good overview? The answer seems to be yes, as I reason from your message.

However, I'll make PR where it's still in the .NET Guide. Let's see how it would look like.

**Comment by rpetrusha** [comment]
After looking at your PR, @pkulikov, I think that the conceptual topic in the threading section still has a place. At least we've eliminated the topic count from three to one.

**Comment by pkulikov** [comment]
@rpetrusha the .NET Guide [says the following](https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool#using-the-thread-pool):
>Beginning with the .NET Framework 4, the easiest way to use the thread pool is to use the Task Parallel Library (TPL). By default, parallel library types like `Task` and `Task<TResult>` use thread pool threads to run tasks. You can also use the thread pool by calling `ThreadPool.QueueUserWorkItem` from managed code (or `CorQueueUserWorkItem` from unmanaged code) and passing a `WaitCallback` delegate representing the method that performs the task.

Given that tasks are recommended way to perform calculations at the background, I think the detailed explanation of how to use `ThreadPool.QueueUserWorkItem` can be removed from the conceptual docs. API reference docs should be enough.

So, I suggest to remove the following topic (as it shows the outdated way use thread pool):
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/how-to-use-a-thread-pool

with the redirect to one of the following topics:
- https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.queueuserworkitem
- https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool#using-the-thread-pool
- https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool#threadpool-examples

What do you think?

**Comment by pkulikov** [comment]
@rpetrusha I agree: will move the example to the API doc and then will remove the topic from the conceptual docs. Thank you.
