### ISSUE TITLE
Assemblies. Combine C# and VB sections into a single .NET Guide doc set

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6181]
There are separate [C#](https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/concepts/assemblies-gac/) and [VB](https://docs.microsoft.com/en-us/dotnet/articles/visual-basic/programming-guide/concepts/assemblies-gac/) sections on assemblies, even though neither language offers language support for assemblies. These sections should be combined into a single section in the .NET Guide.

**Comment by lucasnobredev** [comment]
Well, when we merge the PR #6404 , the next articles to unify are:

- Friend Assemblies
- How to: Load and Unload Assemblies
- How to: Determine If a File Is an Assembly

**PS: We should always remember to look for wrong links and update the assembly/index article.** 

About the other articles deleted from "See Also" section in PR, what we supposed to do?

- How to: Share an Assembly with Other Applications
- How to: Create and Use Assemblies Using the Command Line
- Walkthrough: Embedding Types from Managed Assemblies in Visual Studio
- Walkthrough: Embedding Type Information from Microsoft Office Assemblies in Visual Studio

**Comment by mairaw** [comment]
Hi @lucasnobredev, @rpetrusha will create a new PR to redirect those removed from the See also to the archive.

**Comment by lucasnobredev** [comment]
That's the list I'll keep updating to unify by each article that I change:

- ~~Friend Assemblies~~
- How to: Load and Unload Assemblies
- How to: Determine If a File Is an Assembly
- How to: Create Unsigned Friend Assemblies
- How to: Create Signed Friend Assemblies

**Comment by lucasnobredev** [comment]
@rpetrusha I'd like to continue it. May I?

**Comment by rpetrusha** [comment]
Certainly, @lucasnobredev. I should have added a note and a label to indicate that I was closing this as a duplicate of #6404 .

**Comment by rpetrusha** [comment]
Closing as a duplicate of #6404.
