### ISSUE TITLE
Update stackalloc for C# 7.2

### ISSUE THREAD

**Issue by svick** [dotnet/docs#6184]
It seems this article was updated for C# 7.3, so it mentions array initializer syntax, but it wasn't updated for C# 7.2. Specifically:

* It keeps saying that `stackalloc` is only usable in `unsafe` code, which is no longer true.
* It doesn't mention `Span<T>` at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58806b57-9e0d-9614-a7db-031f7d80e77f
* Version Independent ID: c8882fcc-0e12-654e-609b-57fba989d97e
* Content: [stackalloc (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/stackalloc)
* Content Source: [docs/csharp/language-reference/keywords/stackalloc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/stackalloc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That analysis looks correct to me @svick 

I've added this to our backlog. If you want to submit a PR, let me know and I'll assign this to you.

**Comment by MusorGaming** [comment]
The documentation also says nothing about whether it does or doesn't zero memory.
In theory or practice.
This is absolutely CRUCIAL to get right. Including the Span<T> and how that affects zeroing memory or not.

This is crazy, are people now supposed to deduce how language features work by random github discussions/posts?
