### ISSUE TITLE
Method Syntax For Linq Examples

### ISSUE THREAD

**Issue by j4adev** [dotnet/docs#6204]
For queries like this group by example it would be handy to have the linq method syntax version alongside the query syntax version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af60d154-0468-c450-ad3b-4f144ca6e693
* Version Independent ID: 646c3fab-389f-3a5e-4abe-86943fb85adc
* Content: [Perform a subquery on a grouping operation](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-a-subquery-on-a-grouping-operation)
* Content Source: [docs/csharp/linq/perform-a-subquery-on-a-grouping-operation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/perform-a-subquery-on-a-grouping-operation.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That's a great suggestion @j4adev. We're adding this to our backlog and to our community project.
