### ISSUE TITLE
$ missing in the example's innermost Console.WriteLine(...)

### ISSUE THREAD

**Issue by FloeleT** [dotnet/docs#6214]
There's a $ missing in the example's innermost Console.WriteLine(). The Output is not properly displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b8960-bd9b-6e47-0697-1ede60319dcc
* Version Independent ID: f2080e9b-3a61-ec89-eb34-b61aff1641fa
* Content: [Create a nested group](https://docs.microsoft.com/en-us/dotnet/csharp/linq/create-a-nested-group)
* Content Source: [docs/csharp/linq/create-a-nested-group.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/create-a-nested-group.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by d-dizhevsky** [comment]
Already fixed in PR https://github.com/dotnet/samples/pull/149

**Comment by d-dizhevsky** [comment]
@mariaw @BillWagner this can be closed, see ^^

**Comment by rpetrusha** [comment]
Thanks for letting us know, @d-dizhevsky.
