### ISSUE TITLE
Why are similar doc pages ("What is docker?") out of sync?

### ISSUE THREAD

**Issue by FOSSluds** [dotnet/docs#6215]
IMHO this page is (almost?) identical to https://docs.microsoft.com/en-us/dotnet/architecture/microservices/container-docker-introduction/docker-defined

Why are they out of sync? (last edited, the first image etc.)

I _think_ there should be the _same_ content.

URLs:
https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/what-is-docker

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/container-docker-introduction/docker-defined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a76e1d-cf4b-d04e-bdbe-b1ea6e9f8e7d
* Version Independent ID: eeaccb44-204b-3dc9-6678-7c41865c2486
* Content: [What is Docker?](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/what-is-docker)
* Content Source: [docs/architecture/containerized-lifecycle/what-is-docker.md](https://github.com/dotnet/docs/blob/master/docs/architecture/containerized-lifecycle/what-is-docker.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by BillWagner** [comment]
@CESARDELATORRE Do you have a long-term plan for this?

**Comment by CESARDELATORRE** [comment]
The reason is why these pages are part of different eBooks, but I agree that they should be synched.
I'll put this as a task for the upcoming updates.
Thanks for the heads-up! 👍

**Comment by mairaw** [comment]
@CESARDELATORRE @mvelosop was this ever done?

**Comment by mvelosop** [comment]
@mairaw, we just finished it in PR #10496 😉

Images weren't changed though, because the are different books.

However, the PR was merged a few minutes ago and it's not showing yet, I guess it's in some sort of pipeline, right?

Anyway, there's probably further syncing to be done from the DevOps e-book back to the Microservices e-book.

**Comment by mvelosop** [comment]
Closing this issue as both articles are pretty much the same, just image style and minor wording differences.
