### ISSUE TITLE
Possible inaccuracy

### ISSUE THREAD

**Issue by ippdr** [dotnet/docs#6216]
The documentation for the method with signature Parse(String, IFormatProvider) states 'This overload attempts to parse s by using the DateTimeStyles.AllowWhiteSpaces style.' Inspecting the code in DotNet471RS3 source zip in ndp\clr\src\BCL\system\datetime.cs line 1027 uses DateTimeStyles.None. Please verify and update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc16d7b-f485-3a8b-59c2-e8fb2ddf9e58
* Version Independent ID: 402f9a95-bdf2-d890-1b22-300d0599ed59
* Content: [DateTime.Parse Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=netframework-4.7.2#System_DateTime_Parse_System_String_System_IFormatProvider_)
* Content Source: [xml/System/DateTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/DateTime.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for pointing this out. We'll figure out the correct updates.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ippdr. Although DateTimeStyles.None is passed to the Parse(String, CultureInfo.DateTimeStyles) method, the documentation indicates that the value is ignored, and that the default behavior is DateTimeStyles.AllowWhiteSpaces, which cannot be overridden by a more restrictive value. So explicitly passing DateTimeStyles.None has no effect. I hope that this helps to answer your question.

Although this is confusing, I don't think that it has a documentation impact, so I'll close this issue. If you disagree, please feel free to respond.
