### ISSUE TITLE
Pooled login events are visible in trace

### ISSUE THREAD

**Issue by peteratvektis** [dotnet/docs#6217]
In the section 'Adding Connections' the second note states 'Login and logout events will not be raised on the server ' which seems incorrect to me. I can see these events in a SQL profiler trace and they are marked with EventSubClass '2 - Pooled'. The referenced page for the Audit Login Event Class states 'Events in this class are fired by new connections or by connections that are reused from a connection pool. ' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd54fdd3-4674-eea2-7382-bce7e9bd0536
* Version Independent ID: 9c9d64f5-7000-5901-5bc0-5345e767bd77
* Content: [SQL Server Connection Pooling (ADO.NET)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling)
* Content Source: [docs/framework/data/adonet/sql-server-connection-pooling.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql-server-connection-pooling.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@peteratvektis Thank you for bringing this to our attention. To fix the inconsistency that you identified, we revised the erroneous Note. I am going to close this issue as resolved, but let us know if you have any comments.

**Comment by douglaslMS** [comment]
@peteratvektis I realized that the updated page is not yet live at this moment (Thursday morning, 7/5/2018). It will be published later today.
