### ISSUE TITLE
Declaring Multiple Variables POTENTIAL ERROR

### ISSUE THREAD

**Issue by Guesswho3mar** [dotnet/docs#6224]
"If you declare more than one variable with one As
clause, you cannot supply an initializer for that group of variables.

You can specify different data types for different variables by using a separate As
clause for each variable you declare. Each variable takes the data type specified in the first As
clause encountered after its variablename part.

Dim a, b, c As Single, x, y As Double, i As Integer

' a, b, and c are all Single; x and y are both Double"

However earlier in the day while I was researching, the above statement contradicts proper syntax and format. (**FROM MY UNDERSTANDING** I could be wrong, im a newb and just asking for educational purposes.) So after investigating, i utilized MICROSOFT'S example in the code below.

Sub MultipleDeclarations()

Dim a, b, c As Single, x, y As Double, i As Integer

' a, b, and c are all Single; x and y are both Double

End Sub

Upon going into the Local file of the example code supplied above.

It shows that a, b, x are Variant Data types(SEE BELOW) due to the nature of how VB declares variables that aren't declared.

: a : Empty : Variant/Empty

: b : Empty : Variant/Empty

: c : 0 : Single

: x : Empty : Variant/Empty

: y : 0 : Double

: i : 0 : Integer

Please note
I tried to add OPTION EXPLICIT at the start off the code to see if it will give me difference results & it did not, I still got the same results using the code below:

Option Explicit

Sub MultipleDeclarations()

Dim a, b, c As Single, x, y As Double, i As Integer

' a, b, and c are all Single; x and y are both Double

End Sub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 397627ee-64a9-0693-19ad-c14aee59cca2
* Version Independent ID: 1e561f21-e881-9500-872c-877069f3e8fd
* Content: [Dim Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/dim-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/dim-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/dim-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @Guesswho3mar.  I'm not sure what you mean, however, by the local file of the example code, nor is it clear to me what has generated the output that you've included. VARIANT is a COM type, not a managed type,  

The following example shows that the documentation is correct:
```
Public Module Example
   Public Sub Main()
      Dim a, b, c As Single, x, y As Double, i As Integer  
      ShowVariableInfo(nameof(a), a)
      ShowVariableInfo(nameof(b), b)
      ShowVariableInfo(nameof(c), c)
      ShowVariableInfo(nameof(x), x)
      ShowVariableInfo(nameof(y), y)
      ShowVariableInfo(nameof(i), i)
    End Sub

   Private Sub ShowVariableInfo(str As String, obj As Object)
      Console.WriteLine(str)
      Console.WriteLine($"value = {obj}, type {obj.GetType().Name}")
      Console.WriteLine($"VarType function: {VarType(obj)}")
      Console.WriteLine($"TypeName function: {TypeName(obj)}")
      Console.WriteLine()
   End Sub
End Module
' Output:
'      a
'      value = 0, type Single
'      VarType function: Single
'      TypeName function: Single
'
'      b
'      value = 0, type Single
'      VarType function: Single
'      TypeName function: Single
'
'      c
'      value = 0, type Single
'      VarType function: Single
'      TypeName function: Single
'
'      x
'      value = 0, type Double
'      VarType function: Double
'      TypeName function: Double
'
'      y
'      value = 0, type Double
'      VarType function: Double
'      TypeName function: Double
'
'      i
'      value = 0, type Int32
'      VarType function: Integer
'      TypeName function: Integer
```
I'm going to close this issue. If you disagree or have additional information you'd like to add, however, please feel free to respond.
