### ISSUE TITLE
docker file in

### ISSUE THREAD

**Issue by DavidPrio** [dotnet/docs#6227]

**Comment by svick** [comment]
Did you create this issue by mistake, after creating https://github.com/dotnet/docs/issues/6226? If that's the case, this issue should be closed.

**Comment by mairaw** [comment]
Closing given there’s no feedback here @DavidPrio.

**Comment by DavidPrio** [comment]
Hi @svick and @mairaw Thakns for closing this. It seems I created it by mistake. Sorry for the inconvenience this may have caused.
