### ISSUE TITLE
Exceptions are not listed

### ISSUE THREAD

**Issue by rkudukoli** [dotnet/docs#6228]
The description lists the exceptions as 1. 2. 3. with no content in it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c085df-8b60-5535-ddde-8b2717e7366e
* Version Independent ID: 23dc562a-825a-81b8-9d8b-66692a26aedc
* Content: [ISymbol.MetadataName Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol.metadataname?view=roslyn-dotnet#Microsoft_CodeAnalysis_ISymbol_MetadataName)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/ISymbol.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/ISymbol.xml)
* GitHub Login: @dotnet-bot

**Comment by mairaw** [comment]
It seems that the site is not properly handling the content that is there:
https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/ISymbol.xml#L694

We need to confirm whether it's an issue with source (using accepted tags or not) or with the processor.

/cc @BillWagner @dend @TianqiZhang

**Comment by BillWagner** [comment]
The /// comments in the roslyn source are invalid.  Each `<item>` node should contain a child `<description>` node.

I created dotnet/roslyn#29018 to fix this.
