### ISSUE TITLE
need doc on migrating dnx unit test projects to dotnet unit test projects

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#623]
@cesarbs

**Comment by mairaw** [comment]
do we still need this @Rick-Anderson?

**Comment by Rick-Anderson** [comment]
@danroth27  @cesarbs  do we need doc on migrating dnx unit test projects to dotnet unit test projects

**Comment by danroth27** [comment]
At this point I believe this is low priority and is just going to get to less important. I think we should just close this one out.
