### ISSUE TITLE
Is Visual Studio 2010 required for conversion?

### ISSUE THREAD

**Issue by JohnC-NCR** [dotnet/docs#6230]
Why do you specifically mention the Project Compatibility dialog in Visual Studio 2010 as the means to upgrade a Visual Studio 2003 .Net project to the new MSBuild format?  Won't Visual Studio 2015 or 2017 do this as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca984c4-95a7-05f1-ba86-bf508046a28d
* Version Independent ID: 613ffd93-2871-dab2-53a8-11ed69b7f5b8
* Content: [Migrating from the .NET Framework 1.1](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/migrating-from-the-net-framework-1-1)
* Content Source: [docs/framework/migration-guide/migrating-from-the-net-framework-1-1.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/migrating-from-the-net-framework-1-1.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
This topic hasn't been updated in a long time, that's probably the reason. We'd have to test if newer versions of VS can still open projects build with VS 2003.

**Comment by andrepaulo** [comment]
Any update on that? I'm having the same challenge. To Migrate an VS 2003 1.1 FW to VS2017 at least 2.0 .net FW.. Thanks
