### ISSUE TITLE
$ - String interpolation

### ISSUE THREAD

**Issue by wendyscarlet** [dotnet/docs#6235]
In the example GroupBySingleProperty and GroupBySubstring the special character $ is missing in the Writeline sentence : 

Console.WriteLine("\t{student.LastName}, {student.FirstName}");

So the of the output of the code is:

Key: Adams
  {student.LastName}, {student.FirstName}
Key: Feng
  {student.LastName}, {student.FirstName}
Key: Garcia
  {student.LastName}, {student.FirstName}
  {student.LastName}, {student.FirstName}
  {student.LastName}, {student.FirstName}
Key: Mortensen
  {student.LastName}, {student.FirstName}
Key: O'Donnell
  {student.LastName}, {student.FirstName}
Key: Omelchenko
  {student.LastName}, {student.FirstName}
Key: Terry
  {student.LastName}, {student.FirstName}
Key: Tucker
  {student.LastName}, {student.FirstName}
  {student.LastName}, {student.FirstName}
Key: Zabokritski
  {student.LastName}, {student.FirstName}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae769054-b1de-d528-baab-ea2a275d2a72
* Version Independent ID: b5130725-9cfc-5424-53b6-a6b0860aa6fc
* Content: [Group query results](https://docs.microsoft.com/en-us/dotnet/csharp/linq/group-query-results)
* Content Source: [docs/csharp/linq/group-query-results.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/group-query-results.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @wendyscarlet. That topic was refreshed earlier today.
