### ISSUE TITLE
Unreliable examples given

### ISSUE THREAD

**Issue by liam-tuite** [dotnet/docs#6244]
According to Microsoft's documentation:

"Classes within the System.Drawing namespace are not supported for use within a Windows or ASP.NET service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions."

It would be nice to have examples of these image processing tasks but without relying on System.Drawing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f5c437-1843-39a7-4ed0-165250253b00
* Version Independent ID: 101e0c86-d419-ec11-4c3d-e324488db8a2
* Content: [How to: Crop and Scale Images](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-crop-and-scale-images)
* Content Source: [docs/framework/winforms/advanced/how-to-crop-and-scale-images.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-crop-and-scale-images.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This part of the documentation shows examples of WinForms apps that can use System.Drawing APIs. The System.Drawing namespace already points to https://docs.microsoft.com/en-us/windows/desktop/wic/-wic-about-windows-imaging-codec as an alternative option for that scenario. 

/cc @msatranjr @mcleblanc
