### ISSUE TITLE
Searching the F# Language Reference pulls up results for C# and VB as well

### ISSUE THREAD

**Issue by trosel** [dotnet/docs#6248]
Can we please get a search bar that can separate out the different languages for better searching?

Or maybe get different web pages entirely for each language's reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a34c541d-29fa-6497-c851-17a7d605edc1
* Version Independent ID: 90ab1d8a-0195-e8c2-0f8d-fea3c3539098
* Content: [F# Language Reference](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/#feedback)
* Content Source: [docs/fsharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by WildYorkies** [comment]
@cartermp Ah, I understand your point of view on this. For context, I had this thought when searching for negation in F#. I was trying to see if it's something like `!(myFunctionThatReturnsBool)` or `not myFunctionThatReturnsBool` etc.

When I searched, I only got VB results, even though you can see F# has a page on this.
![image](https://user-images.githubusercontent.com/1299322/42136073-fa2f9660-7d09-11e8-92d6-3196504deea7.png)

I think adding some method of saying "only search the F# section for this" could help. Might allow the searching to be more intensive as well so it could pick up the F# `not` result too?

**Comment by mairaw** [comment]
I think we should probably move this to https://github.com/MicrosoftDocs/feedback, no?

Unfortunately, if I wanna find content under a different section, I use Google, such as:
https://www.google.com/search?q=not+site%3Ahttps%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Ffsharp%2F

Now, separating the different Guides into completely different documentation sites would be a major task. We could investigate with @DuncanmaMSFT and team if we can have different scope searches for the different sub-folders here.

**Comment by mairaw** [comment]
I'm closing this feedback since we recently split up the different guides into their own section.
