### ISSUE TITLE
It's... uh.. Simple

### ISSUE THREAD

**Issue by CloudOS** [dotnet/docs#6252]
and it worked lol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3aa751-f468-0e8b-8d00-7b6f273c01dc
* Version Independent ID: 1dc42d66-6f89-b55b-ebd0-73232935194b
* Content: [How to: Group Windows Forms RadioButton Controls to Function as a Set](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-group-windows-forms-radiobutton-controls-to-function-as-a-set)
* Content Source: [docs/framework/winforms/controls/how-to-group-windows-forms-radiobutton-controls-to-function-as-a-set.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-group-windows-forms-radiobutton-controls-to-function-as-a-set.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
We're pleased that you found that the topic worked, @CloudOS.
