### ISSUE TITLE
Missing web link for "Object and collection initializers"

### ISSUE THREAD

**Issue by manoharreddyporeddy** [dotnet/docs#6254]
Under C# version 3.0
The "Object and collection initializers" does not have a link now.

Can we link it to below?
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@manoharreddyporeddy thanks for catching and reporting it.
