### ISSUE TITLE
Some examples would be nice

### ISSUE THREAD

**Issue by skst** [dotnet/docs#6255]
How does one use this new attached property? How does one implement and use an inherited property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 594fdea9-01c4-2431-97ff-28ba94979196
* Version Independent ID: 6b5c374f-f6f8-23cf-a910-a7b0f83e57b3
* Content: [How to: Register an Attached Property](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-register-an-attached-property?view=netframework-4.7.2)
* Content Source: [docs/framework/wpf/advanced/how-to-register-an-attached-property.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-register-an-attached-property.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the need for a code example, @skst. We've placed this issue in our backlog.
