### ISSUE TITLE
Sample Code in "LINQ to XML Overview" Should Contain Object Loading Step

### ISSUE THREAD

**Issue by kbridge** [dotnet/docs#6256]
The sample code:

```csharp
IEnumerable<string> partNos =  
from item in purchaseOrder.Descendants("Item")  
select (string) item.Attribute("PartNumber");  
```

should contain "How can I get the *purchaseOrder* object?" (by loading a XML file or something). For example:

```csharp
XElement purchaseOrder = XElement.Load("PurchaseOrder.xml");
IEnumerable<string> partNos =  
from item in purchaseOrder.Descendants("Item")  
select (string) item.Attribute("PartNumber");  
```

Otherwise I have to go through the documentation `Programming Guide (LINQ to XML) >> Creating XML Trees >> Parsing XML >> How to: Load XML from a File` (so deep) to find this. Not very friendly for lazy programmers like me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ee7ce-9675-7bbc-430d-5a28876a6d06
* Version Independent ID: f718ba40-50aa-0b5f-4ff2-73b3430b37f4
* Content: [LINQ to XML Overview (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/linq-to-xml-overview)
* Content Source: [docs/csharp/programming-guide/concepts/linq/linq-to-xml-overview.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/linq-to-xml-overview.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing out the difficulty of using this example, @kbridge. We've added it to our backlog.

**Comment by jmarkman** [comment]
Hi all, I'm looking through this issue and I think I'd like to work on it. I'm currently gathering some questions together in regards to this issue, however.
