### ISSUE TITLE
Update text to VS2017

### ISSUE THREAD

**Issue by R2D221** [dotnet/docs#6263]
The section Remote Data talks about how "No provider models for extending existing LINQ technologies, such as LINQ to SQL, to other types of data source are available in Visual Studio 2008."

But... Visual Studio 2008 is no longer supported, is it? It would seem more relevant if the article talked about Visual Studio 2015 or 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e90f0d3-79af-605e-6758-13afdeeaf26a
* Version Independent ID: c2bc3c44-98a4-2a1a-8ca2-e7bc573480da
* Content: [Enabling a Data Source for LINQ Querying1](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/enabling-a-data-source-for-linq-querying1)
* Content Source: [docs/csharp/programming-guide/concepts/linq/enabling-a-data-source-for-linq-querying1.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/enabling-a-data-source-for-linq-querying1.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by R2D221** [comment]
While this is a small issue on the grand scheme of things, I still think it should be fixed to reflect the current toolset Visual Studio offers.

**Comment by BillWagner** [comment]
@R2D221 Thanks for the comment.

I'll reopen and submit a quick PR for the fix.
