### ISSUE TITLE
Sentence is hard to understand

### ISSUE THREAD

**Issue by ike86** [dotnet/docs#6264]
The following sentence is quite hard to understand. Not sure what it even means.

> Operations in which the result is not dynamic include conversions from dynamic to another type, and constructor calls that include arguments of type dynamic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9885f16-24fc-c4ab-458c-fd38279b9898
* Version Independent ID: dc4040cc-3cec-75cd-73a9-2cb7d890c672
* Content: [Using Type dynamic (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic)
* Content Source: [docs/csharp/programming-guide/types/using-type-dynamic.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/using-type-dynamic.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
@ike86, thanks for your feedback. The previous sentence indicates that if an argument to a method or constructor is dynamic, the result is dynamic. This sentence lists the two exceptions to that rule.  We will revise the topic to clarify this.

**Comment by ike86** [comment]
Now I can understand it without explanation. Thanks!

**Comment by mairaw** [comment]
Great to hear!
