### ISSUE TITLE
In the variance section about output unsafe I think the last line needs to be corrected.

### ISSUE THREAD

**Issue by gosali** [dotnet/docs#6267]
@footstep002 commented on [Sun Jul 01 2018](https://github.com/dotnet/docs.ko-kr/issues/56)

Maybe I'm wrong but this
Xi is contravariant or invariant and Ai is input-safe.
needs to be changed to 'Ai is input-unsafe'.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2460f23d-9f92-866c-b814-920997233e6b
* Version Independent ID: 344fa873-bf0c-1c15-cac4-f262ad0162c8
* Content: [Interfaces](https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/language-specification/interfaces)
* Content Source: [spec/interfaces.md](https://github.com/dotnet/docs.ko-kr/blob/live/spec/interfaces.md)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@gosali @footstep002  The spec document is correct.  

This is a complicated area. When you pass a delegate argument to a method, a delegate that produces a value will be used as an input. Whereas when a delegate argument takes an input value, that value is output by the method where the delegate is used.
