### ISSUE TITLE
Constructor?

### ISSUE THREAD

**Issue by amp64** [dotnet/docs#6269]
How do you create one of these? There appears to be no constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a37b1cdf-f950-ea67-7a0e-6862ed8f7583
* Version Independent ID: 8641e577-e65f-74e5-f20a-532141e80bec
* Content: [ExceptionRoutedEventArgs Class (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.exceptionroutedeventargs?view=netframework-4.7.1)
* Content Source: [xml/System.Windows/ExceptionRoutedEventArgs.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/ExceptionRoutedEventArgs.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
There's no public constructor, @amp64; ILDasm shows that the constructor is internal. A ExceptionRoutedEventHandler instance is created by WPF and passed to an event, such as Image.ImageFailed. 
I'm going to close this issue. If you disagree, please feel free to respond.
