### ISSUE TITLE
Local docfx build is now much less useful

### ISSUE THREAD

**Issue by svick** [dotnet/docs#627]
Note: I realize this is not going to be high priority right now, so feel free to ignore this for the moment.

Until recently, running docfx locally on this repo created a full site pretty much equivalent to http://dotnet.github.io/, that was useful for checking pretty much anything about the documentation.

But now, presumably due to the move to docs.microsoft.com, running docfx produces just the bare article body, with no TOC or any other UI elements.

Out of curiosity, I also tried running `.openpublishing.build.ps1`, but that failed when accessing https://github.com/Microsoft/templates.docs.msft.

**Comment by mairaw** [comment]
That's really a coincidence. I had just sent an email to the team asking about this. I'll keep you up-to-date on what I find out. 
@chenkennt suggested that the community should continue to use docfx now. It worked for me up until yesterday. I'll give it a try in the morning again and see what I get.

**Comment by svick** [comment]
Thanks.

**Comment by pkulikov** [comment]
Are local builds still useful and being used? OpenPublishing.Build reports provide a good overview of any issues. Also, building only conceptual docs with PR in this repo seems to be faster than building all the docs locally. 

I have a feeling that the [Building the docs](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#building-the-docs) section can be removed. If not, should it be updated as the docs source is split in several repos?

/cc @mairaw @svick @BillWagner
