### ISSUE TITLE
Remove or replace catch blocks that handle ApplicationException

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6270]
# Remove or replace catch blocks that handle ApplicationException

See #4870 on the use of **Exception** in **catch** blocks.

The handling of **ApplicationException** is particularly widespread in legacy code (that is, examples written for .NET Framework 1.0, 1.1, and 2.0 that have not been revised subsequently). The problems are:
- Exception handling with **ApplicationException** may be used when no exception handling is needed. - Exception handling with **ApplicationException** is used instead of handling more specific exceptions. As a general rule, catching **ApplicationException** rather than more derived exceptions is not recommended.

To address the issue of incorrect exception handling:
1. Work in the dotnet/samples repo.
1. Find the line of code that handles **ApplicationException**.
1. Determine whether exception handling is needed at all. If not, simply delete the **try** statement and the **catch** block.
1. Identify the methods in the **try** block that are candidates for throwing an exception derived from **ApplicationException**, and replace that particular **catch** statement with one or more **catch** statements that handle the appropriate exception.

**Comment by rpetrusha** [comment]
The following are C# code examples that handle **ApplicationException**. In almost call cases, there is a parallel Visual Basic example in the corresponding *snippets/visualbasic* directory, and in some cases, there is a parallel C++ example in the corresponding *snippets/cpp* directory.

- [ ] snippets\csharp\VS_Snippets_CFX\CFX_CompensationExample\cs\Program.cs
- [ ] snippets\csharp\VS_Snippets_CFX\cfx_workflowapplicationexample\cs\program.cs
- [ ] snippets\csharp\VS_Snippets_CFX\wfs_compensationcancellation\cs\program.cs
- [ ] snippets\csharp\VS_Snippets_CLR\CodeTryCatchFinallyExample\CS\codetrycatchfinallyexample.cs
- [ ] snippets\csharp\VS_Snippets_CLR\conceptual.interlocked\cs\source2.cs
- [ ] snippets\csharp\VS_Snippets_CLR\HookUpDelegate\cs\source.cs


- [ ] snippets\csharp\VS_Snippets_CLR\PropertyInfo.SetValue\cs\Example.cs
- [ ] snippets\csharp\VS_Snippets_CLR_System\system.lazy`1.ctorfunc\cs\example.cs
- [ ] snippets\csharp\VS_Snippets_CLR_System\system.lazy`1.ctorfuncbool\cs\example.cs
- [ ] snippets\csharp\VS_Snippets_CLR_System\system.lazy`1.ctorfuncltsm\cs\example.cs
- [ ] snippets\csharp\VS_Snippets_CLR_System\system.Threading.ReaderWriterLock\CS\source.cs
- [ ] snippets\csharp\VS_Snippets_CodeAnalysis\fxcop.design.exceptionsshouldbepublic.ca1064\cs\ca1064 - exceptionsshouldbepublic.cs
- [ ] snippets\csharp\VS_Snippets_Data\DP EntityObject Concepts\CS\SalesObjects.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria custom feeds\cs\iupdatable.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria linq provider\cs\northwind.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind client\cs\customerorderscustom.xaml.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind client\cs\program.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind client\cs\source.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind service\astoriasnippetscs\sourcetest.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind service\astoriasnippetsvb\sourcevbtest.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria northwind service\cs\northwind2.svc.cs
- [ ] snippets\csharp\VS_Snippets_Misc\astoria reflection provider\cs\iupdatable.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifcustomtokenst\cs\passivests\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifcustomtokensts\cs\passivests\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifissuernameregistry\cs\passivests\app_code\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifrccustomtoken\cs\passivests\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifrcfederationforwebapps\cs\fpsts\app_code\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifrcfederationforwebapps\cs\ipsts1\app_code\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifrcfederationforwebapps\cs\ipsts2\app_code\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Misc\wifsigninmessage\cs\webapplication1\certificateutil.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\FileWebRequest_ReqBeginEnd\CS\filewebrequest_reqbeginend.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\NclCodeGroup\CS\sample.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\NCLWebClientUserAgent\CS\useragent.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\Socket_Sync_Send_Receive\CS\source.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\System.Runtime.Remoting.Channels.Ipc.IpcClientChannel\CS\client2.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\System.Runtime.Remoting.Channels.Ipc.IpcServerChannel\CS\server2.cs
- [ ] snippets\csharp\VS_Snippets_Remoting\TransactionScope\cs\ScopeWithSQL.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\toolwindowsearch\cs\testtoolwindowsearch_integrationtests\integrationtest library\utils.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterAddNew\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterAllowAdd\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterAllowDelete\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterAlternateBackColor\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterAppearance\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterCancelEdit\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterColor\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterCurrentItem\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterDataError\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VBPowerPacksDataRepeaterDeletingItems\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterDisableAddDelete\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterDisplayedCount\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterFirstDisplayed\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterHeaderVisible\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterHeaderVisibleChanged\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterIsCurrent\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterItemCloned\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterItemCount\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterItemHeader\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterItemIndex\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterItemsAdded\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterLayout\CS\NorthwindDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterRemoveAt\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterScroll\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterSearch\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterSelectionColorChanged\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterVirtualMode\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterVirtualProperty\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VbPowerPacksDataRepeaterWalkthrough\CS\northwndDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_VBCSharp\VSProDataOrcasEndEditOnAll\CS\NorthwindDataSet.Designer.cs
- [ ] snippets\csharp\VS_Snippets_Winforms\Classic DataGridColumnStyle.CheckValidDataSource Example\CS\source.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid1\csharp\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_autogencolumns\cs\datagrid_autogencolumns\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_cellselection\cs\datagrid_cellselection\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_checkboxcolumn\CS\adventureworkslt2008dataset1.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_columnsmanipulation\cs\datagrid_columnsmanipulation\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_comboboxcolumnsample2\CS\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_customcolumns\csharp\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\datagrid_frozencolumn\cs\adventureworkslt2008dataset.designer.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\GeometryDesigner\CSharp\Window1.xaml.cs
- [ ] snippets\csharp\VS_Snippets_Wpf\UIAAutomationID_snip\CSharp\FindByAutomationID.xaml.cs

**Comment by Mackiovello** [comment]
I'll take care of this once I've gotten feedback from https://github.com/dotnet/samples/pull/377 to make sure I'm doing it right.
