### ISSUE TITLE
PDF File

### ISSUE THREAD

**Issue by mfstanton** [dotnet/docs#6275]
PDF File at bottom of index is empty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e4a58f3-ed4f-7010-7270-a7dd22f5f644
* Version Independent ID: adecf697-56ae-f2d1-51a6-e00cc351aeff
* Content: [Getting Started with Graphics Programming](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/getting-started-with-graphics-programming)
* Content Source: [docs/framework/winforms/advanced/getting-started-with-graphics-programming.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/getting-started-with-graphics-programming.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
So you're saying that if you click on https://docs.microsoft.com/en-us/dotnet/opbuildpdf/framework/winforms/advanced/toc.pdf?branch=live, the PDF is empty for you?

**Comment by mfstanton** [comment]
Yes, it is zero length, PDF Squawks

**Comment by mairaw** [comment]
can you give more information about which browser you're using, etc.? I can't repro this issue:
![image](https://user-images.githubusercontent.com/12971179/42188000-00996d8e-7e07-11e8-908d-7b04c883b227.png)

**Comment by mfstanton** [comment]
IE 11  is what I am using I have had this problem in the past with other pages that have a PDF. The way it was explained to me was that the PDF was zero length because of a bug in the utility that creates the file.  I just click on the link at the bottom of the page and get the error.      
 
https://opdhsblobprod03.blob.core.windows.net/contents/9e91aaced6794685851e249147f1956e/575ef3b06ad248c487294f70c7109da5?sv=2015-04-05&sr=b&sig=XSMawGLJ5aGyzzne%2BZ%2FNq6YlsTmbZdwXxd1CuUJa55s%3D&st=2018-07-02T23%3A06%3A08Z&se=2018-07-03T23%3A16%3A08Z&sp=r
 
  Because the image of the file is empty
 
   https://docs.microsoft.com/en-us/windows/uwp/gaming/working-with-2d-graphics-in-your-directx-game

**Comment by mairaw** [comment]
I can't reproduce this issue either on IE or Chrome, on the .NET content where you posted this initially or any of the other links you posted. 

If you're still having issues, I'll ask you to open a new issue at the https://github.com/microsoftdocs/feedback repo. There, someone from the engineering team will be able to follow up with you.
