### ISSUE TITLE
this page doesn't provide any useful information

### ISSUE THREAD

**Issue by gregveres** [dotnet/docs#6284]
I came here looking to find out how to migrate a project from .Net 4.6 to .Net 4.7. The page starts off promising by saying that is what it is going to tell me. Then it takes a tangent, talking about migrating your project from an earlier version of Visual Studio but never seems to come back to get to the real point of how to migrate a project to a new version of .Net. If that information is in here, it is deeply hidden behind poor grammar or something. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a44e891-eec4-d737-b821-97806ffba8a7
* Version Independent ID: 2383164f-5a94-adc9-adaa-00af6c53d556
* Content: [Migration Guide to the .NET Framework 4.7, 4.6, and 4.5 ](https://docs.microsoft.com/en-ca/dotnet/framework/migration-guide/)
* Content Source: [docs/framework/migration-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by jsancho** [comment]
just like @gregveres I came here to find the appropriate procedure to upgrade a project from 4.6.1 to 4.7.1, since I've had some issues when trying it directly.
Even if the introduction in this document seems to be describing the scenario that I'm looking for, it does not seem to actually provide much that I can use.

**Comment by gregveres** [comment]
I eventually found this page:
https://docs.microsoft.com/en-ca/visualstudio/ide/how-to-target-a-version-of-the-dotnet-framework

it describes what to do, but I was at it for 3 hours last night and I am still at it this morning. I had to restart the process a few times after visual studio did some weird things. Now I am fighting a problem where deploying to azure isn't finding system.net.http for some reason. So some good documentation of how to upgrade the .net version of a project would definitely be worth while.

**Comment by jsancho** [comment]
Thanks for the info, I had done those steps manually but I've been finding issues with binding redirects.
There is also this tool https://marketplace.visualstudio.com/items?itemName=PavelSamokha.TargetFrameworkMigrator#qna

Which with a little patching https://github.com/VHQLabs/TargetFrameworkMigrator/issues/49 should be able to do the job in theory.
It seems to work on the surface, but I am having issues with binding redirects at runtime.

Thinking that it might just be easier to bite the bullet and recreate the projects from scratch and copy the files across.

We've had issues with the System.Net.Http dependency in the past when running our test integration project.
The solution for us was to specifically link to version 4.1.1.2 in the csproj. Not sure whether that might help in your situation.

**Comment by eltiare** [comment]
I came here looking for the same. Seems like a stub article.

**Comment by 105058031** [comment]
I concur with all the comments above. The article is named "Migration Guide", yet only the very point is missing, there's no guide on how to actually migrate! Classic Microsoft....

**Comment by ransagy** [comment]
Especially since the very large and problematic changes to System.* NuGet/Inboxed references and various targetting issues, One would expect this article will actually address the migration itself - Or any of it's referred links.

Is there no single official MS guide on how to PROPERLY migrate projects between major framework releases?
