### ISSUE TITLE
Example has invalid value warning

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6286]
In VS 15.7 the example code will lead to an invalid value warning/error for Enum constraint failure
for the `deliveryMethod` attribute, which has `network` as its value in the example, but should be `Network`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e8aae2-b92f-8913-8865-bc1abc549b90
* Version Independent ID: 1e331bd2-77d7-346f-3965-b09134cf8f83
* Content: [&lt;mailSettings&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/mailsettings-element-network-settings?view=netframework-4.7.2)
* Content Source: [docs/framework/configure-apps/file-schema/network/mailsettings-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/mailsettings-element-network-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by rpetrusha** [comment]
Thanks for bringing this to our attention, @ite-klass. @davidsh, can you confirm that the value of the `deliveryMethod` attribute should be `Network` rather than `network`?

**Comment by rpetrusha** [comment]
Thanks, @davidsh. I assume that the casing applies as well to SpecifiedPickupDirectory and PickupDirectoryFromIis, both of which are therefore also incorrect. I'll submit a PR to correct these shortly.
