### ISSUE TITLE
It may be not obvious why you are using an expression tree here.

### ISSUE THREAD

**Issue by psxvoid** [dotnet/docs#6288]
Does it make sense to add a brief explanation/example why you would use expression trees instead of the LINQ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e7c92f-899d-506e-dced-ade9245fa231
* Version Independent ID: 0f232a4f-3c75-7736-7c70-c409d3cf5ab5
* Content: [How to: Use Expression Trees to Build Dynamic Queries (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries)
* Content Source: [docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by zspitz** [comment]
Perhaps the sample should be re-implemented as a method that takes various parameters: a search string, and `bool?` to order by ascending, descending, or not at all.

**Comment by zspitz** [comment]
@dotnet/docs

To quote from the page:

> This code uses a fixed number of expressions in the predicate that is passed to the `Queryable.Where` method. However, you can write an application that combines a variable number of predicate expressions that depends on the user input. You can also vary the standard query operators that are called in the query, depending on the input from the user.

If the expressions are fixed, there is absolutely no reason to create a dynamic expression tree, and not use compiler-generated expression trees. It would be far more effective to show how a truly dynamic expression tree could be created, based on user input.
