### ISSUE TITLE
PowerShell 4.0 support

### ISSUE THREAD

**Issue by jawn** [dotnet/docs#6291]
The PowerShell example uses Get-ItemPropertyValue which is not supported in all PowerShell versions (e.g. 4.0)

The following code is backwards compatible:

$(Get-ItemProperty -Path "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full") | Select-Object Release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by J0rgeSerran0** [comment]
I think that you should to use a newer version.
I'm using the 5.1 version of PowerShell without troubles and it's working properly.
I will add a PowerShell script in my repo to get this information, and it's running ok.

**Comment by jawn** [comment]
Sure, I am using a newer version.

However, other people may want to follow the procedure and it's perfectly possible to have systems with .NET 4.5 or higher but without a PowerShell 5.0.

**Comment by J0rgeSerran0** [comment]
Well, that is a possibility, however my personal recommendation is to install PowerShell 5.x.

**Comment by sime3000** [comment]
Hello Microsoft.  I don't suspect that you know or care how much time people waste collectively following these instructions just to get a simple answer about a commonly installed component do you? (rhetorical question). Does the .NET team really hate users that much that they cant be bothered to provide a simple command line utility, or a single PowerShell command, or some reference in Programs and Features or something that doesn't require the arcane procedures in articles such as this. The year is almost 2019 - why continue to waste everyone's time like this?
