### ISSUE TITLE
Difference from 'dotnet build'

### ISSUE THREAD

**Issue by AndreiRinea** [dotnet/docs#6295]
When should we use 'dotnet msbuild' as opposed to 'dotnet build'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9083568-6c58-1c1b-0062-10632e61a88d
* Version Independent ID: a1d47471-9482-9f69-f11e-3424e62383f6
* Content: [dotnet msbuild command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild)
* Content Source: [docs/core/tools/dotnet-msbuild.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-msbuild.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by solidcloudio** [comment]
I ran into an issue where a build dependency loaded a Custom Assembly with a Custom Build Task in a .dll  This .dll depended on .net 4.0.  Using "dotnet build"  the build would fail to load System 4.0.0.

Using msbuild works, so I'd assume dotnet msbuild would work the same as MsBuild.

https://github.com/dotnet/standard/issues/328
https://github.com/Azure/azure-functions-vs-build-sdk/issues/160

Seems the MSBuild version used by dotnet build is "lightweight" or "scaled back" as it can't load external assemblies..

**Comment by verbaloid** [comment]
It is not clear whether "dotnet.exe msbuild" restores (downloads) dependencies like "dotnet.exe build" does?

**Comment by mairaw** [comment]
@livarcocc @KathleenDollard @dsplaisted what can we add to the dotnet msbuild topic to make it more clear the distinction between dotnet build and dotnet msbuild? My understanding is that dotnet msbuild gives you the same capabilities as MSBuild, but you can also pass MSBuild parameters to dotnet build as well, right? I think the topic would benefit from having more information about the difference between the two commands.

**Comment by dsplaisted** [comment]
`dotnet build` is basically the same as `dotnet msbuild -restore -target:Build`.

**Comment by verbaloid** [comment]
then what do both of them exist for?

**Comment by dsplaisted** [comment]
@verbaloid Most of the time if you want to build your project you want to run `dotnet build`.  If you have a specific target you want to run (without running the build target), you probably want to use `dotnet msbuild`.  Basically `dotnet build` is the common case, but `dotnet msbuild` gives you more control.

**Comment by verbaloid** [comment]
thank you - now it is much more clear - can someone also update both microsoft dotnet build and msbuild pages by this guidance

**Comment by dsplaisted** [comment]
`dotnet build` will always run the `Build` target.

So if you want to only run the `MyTarget` target, you should do `dotnet msbuild -target:MyTarget`.  You could also do `dotnet build -target:MyTarget`, but that would then run both `MyTarget` and the `Build` target.

**Comment by mairaw** [comment]
Gotcha! Thanks @dsplaisted.
