### ISSUE TITLE
Clarify 2-letter special guideline for "Id"

### ISSUE THREAD

**Issue by loosleef** [dotnet/docs#6296]
This is a very commonly asked question because perhaps legacy conventions recommended `ID` and would be helpful to clarify, even just adding an example in the Pascal/Camel/Not table.

From the current documentation, `id` & `Id` are recommended, but it is not clear when used as only part of an identifier, as was done with the `IOStream` example.

Please add a similar example how `Id` differs from `IO`.  I believe this has to do with one is an abbreviation and the other an acronym, but it would be nice to confirm for the community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eba6b11-5703-355f-0e85-08ee7451120d
* Version Independent ID: 4691fbb3-7b6d-8c02-e372-315ca302e48e
* Content: [Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)
* Content Source: [docs/standard/design-guidelines/capitalization-conventions.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/capitalization-conventions.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Reelix** [comment]
Id is context dependent  
  
Id (Short for identifier): Id  (IdStream)
Id (Short for Identity Document): ID (idStream)

**Comment by NikoAri** [comment]
Similarly, please clarify how should users shorthand Javascript? Is it:
JS or Js

**Comment by naristov** [comment]
Also, what about Database? 
Db or DB?

**Comment by ardalis** [comment]
@tdykstra Should this issue be related to the guide - ASP.NET Core web apps?
