### ISSUE TITLE
Where is the 3rd edition?

### ISSUE THREAD

**Issue by bobrundle** [dotnet/docs#6305]
Yes, the guidelines are great, but they are nearly a decade old.  Has software plateaued?  Has nothing changed in 10 years such that a 3rd edition is unnecessary?  I have a tattered old copy of the 2nd edition and every time I picked it up it feels like I need to be wearing those gloves that people use in the antique book vault.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6372c771-955d-d043-7774-fcd7ff20b05c
* Version Independent ID: 15347b19-b2bf-640b-9d3f-982b970f9936
* Content: [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/)
* Content Source: [docs/standard/design-guidelines/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/index.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CShepartd** [comment]
Agree. We need 3rd edition, specially for .Net Core (and ASP.NET Core)

**Comment by rpetrusha** [comment]
Thanks for your feedback, @bobrundle. This content, though, is reprinted with the permission of its publisher, Pearson Education. We have no control over whether there will be a third edition. Given that, I'm going to close this issue, since it doesn't directly impact our documentation set.
