### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by OliverRC** [dotnet/docs#6311]
We have compiled the source and are using it but not having Nuget references is quite a pain because the new project nuget packaging relies on package references for dependencies and not external assemblies. 

It seems pretty straightforward for you to ship Nuget packages so please can we get packages for HealthChecks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98bdd99-d89d-8720-9018-25f73dcfdbd8
* Version Independent ID: c02edf4f-eb03-f02a-c72d-510cc17c8c9e
* Content: [Health monitoring](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/monitor-app-health.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/monitor-app-health.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by lisberPontes** [comment]
Same opinion as OliverRC, why not shipping this lib as NuGet(s) package(s)?

Any roadmap/date planned for this library to be available as a NuGet ?

**Comment by tafs7** [comment]
As of *Oct 2018*, some of the content in this page is now out of date.

The Github repo linked at the beginning of the article is now deprecated, and the source has moved into the ASP.NET Diagnostics sub repo, and will be included in ASP.NET Core v2.2 when it releases by the end of 2018.

Please see this: https://github.com/aspnet/Diagnostics/tree/release/2.2/src

If you are insterested in Nuget packages and don't mind running pre-release software, you can get the pre-release version of the Nuget packages which have been renamed as *Microsoft.AspNetCore.Diagnostics.HealthChecks*, and is now found at https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.HealthChecks

**Comment by mairaw** [comment]
@CESARDELATORRE @mvelosop can you please take a look at this issue for the microservices e-book?

**Comment by mvelosop** [comment]
Hi @mairaw, this page has been updated in the upcoming PR.

Also added the comment on the 2.2 release, but don't suggest trying the NuGet package because it depends on 2.2 and eShopOnContainers hasn't been tested on 2.2.
