### ISSUE TITLE
Unclear differentiation between myApp.config copy property and auto-copy of App.config

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6312]
The two paragraphs do not make it clear what the intended workflow is.

If Visual Studio automatically copies a "source configuration file" to the output directory, then when should the config file property set to copy always or copy if newer? Is the "source configuration file" something different than the myApp.config file?

The paragraphs in question:

&gt;  When you develop in Visual Studio, place the source configuration file for your app in the project directory and set its Copy To Output Directory property to Copy always or Copy if newer. The name of the configuration file is the name of the app with a .config extension. For example, an app called myApp.exe should have a source configuration file called myApp.exe.config.
&gt; 
&gt; Visual Studio automatically copies the source configuration file to the directory where the compiled assembly is placed to create the output configuration file, which is deployed with the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39c5030-7cdb-a2b4-4abf-0451ab4d8de4
* Version Independent ID: 4aae87fd-84b4-4cbf-aeec-4da9a43f4396
* Content: [Configuring Apps by using Configuration Files](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/index)
* Content Source: [docs/framework/configure-apps/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by BillWagner** [comment]
The "source configuration file" is the same as the "myApp.config" file.

You can generally pick either "copy if newer" or "copy always".  The difference would be observed if you edit the destination file manually.
