### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by KSS-thompsona2** [dotnet/docs#6314]
I would like to find a row in a DataView via a composite key where one of the values is null.  For instance:
dataView.Sort = "NullableColumn1, NullableColumn2";
var found = dataView.Find(new object[]{1, null})).

Would I be correct in thinking that this is not possible?

When I try this I an ArgumentException is thrown: "Expecting 2 value(s) for the key being indexed, but received 1 value(s)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c790b40-d953-47bb-bb42-3f26d88693b9
* Version Independent ID: bb02d523-2d99-60cc-98ef-54e31ab98a21
* Content: [Finding Rows](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/finding-rows)
* Content Source: [docs/framework/data/adonet/dataset-datatable-dataview/finding-rows.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/dataset-datatable-dataview/finding-rows.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@KSS-thompsona2 Please test with DbNull.Value in place of "null" in the Find method, and let me know whether that works for you.

**Comment by douglaslMS** [comment]
@KSS-thompsona2 Have you had an opportunity to test the alternate argument we suggested?

**Comment by KSS-thompsona2** [comment]
Hey Douglas,

Using dataView.Find(new object[] { 1, DBNull.Value }); does indeed work.

Thank you,
Tony ;-)
