### ISSUE TITLE
type or namespace Xunit not found

### ISSUE THREAD

**Issue by jpeg729** [dotnet/docs#6317]
I'm running a fresh install of dotnet sdk 2.1.301 on ubuntu 18.04
I ran "dotnet new xunit" and got the test files described, however I am getting the error CS0246: The type or namespace name 'Xunit' could not be found (are you missing a using directive or an assembly reference?)

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b54562-9072-a864-be3d-44ed7965c798
* Version Independent ID: a69ec985-ed05-90dd-a686-dc956b0cf5df
* Content: [Organizing and testing projects with the .NET Core command line](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli)
* Content Source: [docs/core/tutorials/testing-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by jpeg729** [comment]
If I run "dotnet add package xUnit" in the root folder of my project, then it works.

**Comment by BillWagner** [comment]
I'm glad you found that answer @jpeg729 

I've added this to our backlog and added the up-for-grabs label. If you want to submit a PR for this, let me know and I'll assign it to you.

**Comment by garg000dhruv** [comment]
@BillWagner I ran into the same issue. I can fix it in the docs if it's still open.

**Comment by mairaw** [comment]
Still open @garg000dhruv. Feel free to submit a PR.

**Comment by BillWagner** [comment]
Moving into the current sprint.  

@garg000dhruv Will you have time to update PR #7296 or should we make those updates and merge the changes?

**Comment by garg000dhruv** [comment]
Sorry, completely konked out on this one. I'll try to finish it up in a couple of days.
