### ISSUE TITLE
錨點$問題

### ISSUE THREAD

**Issue by gosali** [dotnet/docs#6319]
@yuyueh commented on [Wed Jul 04 2018](https://github.com/dotnet/docs.zh-tw/issues/179)

錨點"$"說明中， "-333-333-" 中的結果不應該為"-333"。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [規則運算式語言 - 快速參考](https://docs.microsoft.com/zh-tw/dotnet/standard/base-types/regular-expression-language-quick-reference#atomic_zerowidth_assertions)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gosali** [comment]
Translation: In the anchor "$" description, the result in "-333-333-" should not be "-333".

**Comment by imba-tjd** [comment]
This one is also not a source issue...

**Comment by rpetrusha** [comment]
@nokura, this issue was moved from dotnet/docs.zh-tw#179, but this is a localization issue.

Closing here as Not Repro.
