### ISSUE TITLE
逸出字元"\S"問題詢問

### ISSUE THREAD

**Issue by gosali** [dotnet/docs#6320]
@yuyueh commented on [Wed Jul 04 2018](https://github.com/dotnet/docs.zh-tw/issues/178)

您好。本頁介紹中提到的逸出字元"\S"，最後"int _ctr"符合的結果應為" _"而非" "。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [規則運算式語言 - 快速參考](https://docs.microsoft.com/zh-tw/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gosali** [comment]
Translation: Hello. The escape character "\S" mentioned in the introduction to this page, and finally "int _ctr" should match the result "_" instead of " ".

**Comment by imba-tjd** [comment]
This is not a source. It has been fixed in zh-TW repository, but only not been released yet.

**Comment by rpetrusha** [comment]
This was a localization issue that's been fixed. Closing.
