### ISSUE TITLE
wrong variable used in sample code

### ISSUE THREAD

**Issue by markleebrian** [dotnet/docs#6321]
In section 'Inheritance and an "is a" relationship' the sample code repeats variable make from previous if statement, should be variable model in else if line:

        if (model == null)
           throw new ArgumentNullException("The model cannot be null.");
        else if (String.IsNullOrWhiteSpace(make))
           throw new ArgumentException("model cannot be an empty string or have space characters only.");
        Model = model;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e813a38-d487-25dc-b70d-23fca9c47221
* Version Independent ID: 92fb3bd2-56a5-e060-8056-491aab145d26
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance)
* Content Source: [docs/csharp/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you @markleebrian for your feedback and apologies for not getting to this sooner.

I'd typically ask if you'd like to open the pull request yourself, but I've done this now due to the delay:
https://github.com/dotnet/samples/pull/271
