### ISSUE TITLE
wrong folder

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6332]
Here is the current path where VsDevCmd.bat is located.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91bc630b-9e6d-3015-a110-f15311e6924f
* Version Independent ID: 658594e6-77cb-e41c-3307-bb0a4e6224e1
* Content: [How to: Set Environment Variables for the Visual Studio Command Line](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line)
* Content Source: [docs/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Isn't that the path that the documentation lists, @johnnyagerard? It provides two possible paths:

-  \Program Files\Microsoft Visual Studio\Version\Offering\Common7\Tools
- \Program Files (x86)\Microsoft Visual Studio\Version\Offering\Common7\Tools

Version here is 2017, and offering in your case is Community. So \Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools.

I'll close this issue. But if I've misunderstood or missed something, please feel free to respond.
