### ISSUE TITLE
Incorrect rendering of an escaped pipe character inside a code block on a table

### ISSUE THREAD

**Issue by HankiDesign** [dotnet/docs#6335]
In the [Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction#expressions) section, there's a table of C# operators with a rendering issue related to escaping the pipe character with a backslash.

<img width="687" alt="Incorrect pipe character rendering inside a table on Docs" src="https://user-images.githubusercontent.com/1816448/42350797-4b96487c-80b2-11e8-820b-c2808cd2ae49.png">

As seen on the above picture, pipe characters for the _Logical OR_ and _Conditional OR_ are escaped because they're inside a table. The same characters render correctly on GitHub as seen on the picture below:

<img width="894" alt="Correct pipe character rendering inside a table on GitHub" src="https://user-images.githubusercontent.com/1816448/42350890-bdcd6d62-80b2-11e8-87e8-5424c01135f6.png">

I assume that the problem occurs due to the escaped pipe characters residing inside a code block and Docs not supporting it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Given this is a general Docs issue, I moved this to https://github.com/MicrosoftDocs/feedback/issues/497.

**Comment by mairaw** [comment]
Reopening this so we can fix the spec article next sprint after we move our repo to Markdig.

**Comment by BillWagner** [comment]
Note that the PR is in the dotnet/csharplang repo.
