### ISSUE TITLE
Question about  the path property. 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/docs#6337]
Is the path to the documentation relative to the source file? Can the path use csproj or solution variables, something like $(SolutionDir)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d418e3-b648-587e-155d-843ffb48b025
* Version Independent ID: 606a07e0-da13-f58f-4e64-be634479a55d
* Content: [&lt;include&gt; (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/include)
* Content Source: [docs/csharp/programming-guide/xmldoc/include.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/include.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by garg000dhruv** [comment]
@BillWagner I can make the necessary change here.
