### ISSUE TITLE
remarks

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6343]
The override method ToString() could just return 'Name' instead of 'Name.ToString' as the name property is a string.
Furthermore, this line:
Console.WriteLine(person2.ToString());
could be written as:
Console.WriteLine(person2);
because the ToString method is called by the WriteLine method if I'm correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Classes (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for noticing the unnecessary calls to ToString, @johnnyagerard. I've opened PR dotnet/samples#188 to remove them.
