### ISSUE TITLE
Root returns uppercase in Windows 10

### ISSUE THREAD

**Issue by RobBittner** [dotnet/docs#6345]
Not sure if it does everywhere, but in Windows 10, root returns C:\, etc... not c:\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17ddac9d-69ae-e5fa-285b-e4a14fd33cec
* Version Independent ID: e6073fc8-fd8c-9f7e-f9eb-defe3a7a8a4f
* Content: [DirectoryInfo.Root Property (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.root?view=netframework-4.7.1)
* Content Source: [xml/System.IO/DirectoryInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DirectoryInfo.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @RobBittner. We'll investigate.

**Comment by Thraka** [comment]
Thanks for the feedback @RobBittner. I cannot seem to reproduce this. I tried using different framework versions and event .NET Core 2.1. I also checked Ubuntu and Windows 7 and nothing seems to return `C:`
