### ISSUE TITLE
Format string has to be 1 character

### ISSUE THREAD

**Issue by Narvey** [dotnet/docs#6349]
It doesn't really call it out here very well, but the format string is not like String.Format() strings in that it can only be 1 character. I'd recommend changing "The format parameter can contain..." to "The format parameter must be one of the predefined options..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43832d9-b268-29c0-6eda-bd7c22b73cb4
* Version Independent ID: 2dc3dbff-e8f4-c84c-dcb9-e99ff261495f
* Content: [Enum.ToString Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=netframework-4.7.1#System_Enum_ToString)
* Content Source: [xml/System/Enum.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Enum.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks, @Narvey. We've added this to the backlog.
