### ISSUE TITLE
Hyperlink to article on boxing / unboxing

### ISSUE THREAD

**Issue by zackasattackas** [dotnet/docs#6351]
Paragraph 4 of this article discusses how value types are boxed/unboxed when casting to a reference type. I thought it might be helpful to include a link to this article: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing. I had to reference it just to get a thorough explanation of what "boxing" meant, so I thought it might be helpful to other readers as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e73f528-b4e2-cc81-3f49-faa9fbd9b153
* Version Independent ID: 66f0cfec-c8f1-2411-84d5-9e8cb09d7ff5
* Content: [Choosing Between Class and Struct](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct)
* Content Source: [docs/standard/design-guidelines/choosing-between-class-and-struct.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/choosing-between-class-and-struct.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
@zackasattackas We added the "up-for-grabs" label.  We'll fix this, unless you want to submit a PR yourself.
