### ISSUE TITLE
Typographical error in an instruction

### ISSUE THREAD

**Issue by posfr** [dotnet/docs#6356]
I think that you should change the console command "dotnet run Hello World" to "dotnet run App Hello World".

The token App is missing before Hello World.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836d726d-1f95-51e7-c5c3-a7200adc5772
* Version Independent ID: 3e9e6e89-7017-7a7c-faea-4c0e76cef442
* Content: [Get started with F# with command-line tools](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line#dotnet-restore-note)
* Content Source: [docs/fsharp/get-started/get-started-command-line.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-command-line.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@posfr I'm not sure this should say `dotnet run App Hello World`. In the article, we prompt you to change directory into `/App`, then run from there. This is the directory where the console application lives. The output in the tutorial just lists `Hello` and `World` in it, not `App`. Does this make sense?

**Comment by posfr** [comment]
Hi Phillip,

Thank you for looking at this issue.

I’ve retested and you don’t need to change the documentation!

Interestingly, however, dotnet run App Hello World and dotnet run Hello World both actually work!!

The dotnet run part of both of these commands runs the project (App.fsproj) for the console application.  Everything after (dotnet run) is passed as an argument to the application – 3 arguments in the first version and two in the second.  (The documentation just has the two; so it’s fine.)

Apologies for any inconvenience.

Regards,
Franz

**Comment by cartermp** [comment]
No worries!
