### ISSUE TITLE
Example naming rule violation.

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6360]
jobLength and originalItemID properties should begin with a upper case letter right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b81800f-976a-b7a9-e202-5e34fd2c9c67
* Version Independent ID: 801d99f4-b1f5-3e42-ae4e-ba18200577f0
* Content: [Inheritance (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/inheritance)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/inheritance.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @johnnyagerard. The variable naming convention here is really a matter of choice. The members are protected, so from the viewpoint of consumers of the type rather than its inheritors, they're not a part of the type's public interface. They're only a part of the public interface for inheritors of the type. The Regex class, for instance, includes a number of [protected fields](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=netframework-4.7.2#fields) whose names use camel casing. 
I'm going to close this issue. If you disagree, however, please feel free to respond.

**Comment by Shah-Nisarg** [comment]
@rpetrusha I am a bit puzzled. The [documentation](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalizing-compound-words-and-common-terms) seems a bit vague when it says,

> DO use PascalCasing for all public member, type, and namespace names consisting of multiple words.
> DO use camelCasing for parameter names.

So I suppose it doesn't clarify the rule for protected members, but the table beneath shows that Identifiers of type Property follow Pascal case.

I am not sure I am reading the correct guidelines. Could you point me to the correct source? Or, should I raise an issue for the linked guidelines to be clarified?

**Comment by rpetrusha** [comment]
As the topic points out, @Shah-Nisarg. pascal casing is used for public elements; public elements are exposed to callers. (And properties almost always have a public getter and/or setter.) Camel casing is used for parameter names; parameter names (at least for public members) can be exposed through IntelliSense. The topic implies a strong preference for applying those conventions to all program elements, and not just public ones, and advises against usage of such things as underscores. But in the end, these are guidelines and recommendations intended to enhance readability and make developer intent clear from code style. Compilers don't enforce these naming conventions except in the case of illegal names.

In terms of opening an issue for the linked guidelines, all of the https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/* topics are republished with permission of Addison-Wesley. We are not authorized to make changes to that content.
