### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6362]
static``readonly

Is it a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df47593-8586-e54e-fb74-cf3a96262d40
* Version Independent ID: b464cd68-4713-c848-e9a7-30705d17e6f7
* Content: [Fields (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/fields.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/fields.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @johnnyagerard. It's a migration issue. I've corrected in in PR #6378.

Incidentally, you can open PRs to correct issues such as these yourself. Just click the Edit button at the top of the page immediately below the navigation bar on a docs.microsoft.com page. This will take you to the topic in GitHub. You can then edit the topic and open a pull request.
