### ISSUE TITLE
Doesn't work on Views

### ISSUE THREAD

**Issue by crtjr64** [dotnet/docs#6367]
I have a view and followed the documentation to the letter so I could have a more user friendly name to the POCO for the view, but I kept getting the table not found error. EF Core 2 Table Attribute doesn't permit explicit use of name in the parameter so for me, for Core 2, this doesn't work. I had to rename the class and its associations in the context to the same long name that's in the database before I was able to retrieve my data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bdbbe7c-ee43-549a-970b-5951b4fe3fab
* Version Independent ID: 97899a77-2b87-6100-2684-878371db45dd
* Content: [Attribute-Based Mapping](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/attribute-based-mapping)
* Content Source: [docs/framework/data/adonet/sql/linq/attribute-based-mapping.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/attribute-based-mapping.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@crtjr64 Are you saying that there's a section on this page that provides incorrect guidance? Which attribute did you use that did not have the results you intended?

**Comment by douglaslMS** [comment]
@crtjr64 Since we haven't heard from you to clarify your concern about this page of documentation, we're going to go ahead and close this issue.
