### ISSUE TITLE
end point error

### ISSUE THREAD

**Issue by rishu007** [dotnet/docs#6371]
I followed the step given I am not able to host the service reason because I am getting error "end point not specified"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8cbb16-05b1-a5f2-9031-1d7beb52efea
* Version Independent ID: 98092a9f-c19a-cca9-75d6-75b9c3d4cc0b
* Content: [How to: Host and Run a Basic Windows Communication Foundation Service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-host-and-run-a-basic-wcf-service)
* Content Source: [docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jepp** [comment]
The tutorial left out the step to edit these lines in app.config from
```
      <service name="GettingStartedLib.Service1">
        <host>
          <baseAddresses>
            <add baseAddress = "http://localhost:8733/Design_Time_Addresses/GettingStartedLib/Service1/" />
          </baseAddresses>
        </host>
        <!-- Service Endpoints -->
        <!-- Unless fully qualified, address is relative to base address supplied above -->
        <endpoint address="" binding="basicHttpBinding" contract="GettingStartedLib.IService1">

```
to
```
      <service name="GettingStartedLib.CalculatorService">
        <host>
          <baseAddresses>
            <add baseAddress = "http://localhost:8733/Design_Time_Addresses/GettingStartedLib/CalculatorService/" />
          </baseAddresses>
        </host>
        <!-- Service Endpoints -->
        <!-- Unless fully qualified, address is relative to base address supplied above -->
        <endpoint address="" binding="basicHttpBinding" contract="GettingStartedLib.ICalculator">

```

And this step:
`2. Open Internet Explorer and browse to the service's debug page at http://localhost:8000/GettingStarted/CalculatorService.
`

should say
`2. Open Internet Explorer and browse to the service's debug page at http://localhost:8733/Design_Time_Addresses/GettingStartedLib/CalculatorService/
`

**Comment by user135711** [comment]
Actually, you addresses differ, and their addresses differ from the endpoint URI needed for the next step. The final code silently changes to a third unseen uri used in the next step: http://localhost:8000/ServiceModelSamples/Service

**Comment by jepp** [comment]
There's a LOT that this tutorial leaves to be desired. I think it actually set me BACK on learning it. It also doesn't explain which of these things is which. And it also didn't really do much to mention the role of the app.config in design time with a WCF serrvice vs run time with something like their console apps. It really just needs to be rewritten from scratch.

**Comment by user135711** [comment]
@jepp Also a complete dowloadable working sample like in the other tutorials would save a lot of time.
