### ISSUE TITLE
Frameworks

### ISSUE THREAD

**Issue by Melissa517** [dotnet/docs#6374]
I am really getting tired of booting up my PC and seeing this popup all the dang time!  I wish it would stop and just leave me alone!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
What is the popup you're seeing, @Melissa517? You might want to take a look at [Troubleshooting blocked .NET Framework installations and uninstallations](https://docs.microsoft.com/en-us/dotnet/framework/install/troubleshoot-blocked-installations-and-uninstallations).

**Comment by mairaw** [comment]
Is this the pop-up you're referring to @Melissa517?
![image](https://user-images.githubusercontent.com/12971179/42833670-994ace8a-89a9-11e8-9d3c-5ea7129f5269.png)

That means that you're trying (or tried) to install a software that requires .NET Framework.

**Comment by rpetrusha** [comment]
Closing since there's been no response from @Melissa517.
