### ISSUE TITLE
Section: Style data with data templates - mistake?

### ISSUE THREAD

**Issue by teunvanhemert** [dotnet/docs#6376]
I wonder if there isn't a mistake in the final section 'Style data with data templates'
The data templates there seem unnecessary now, and are unused. I wonder if the example shouldn't be something like this:
```XML
<DataGrid.Columns>
  <DataGridTemplateColumn Header="ExpenseType" CellTemplate="{StaticResource TypeItemTemplate}" />
   <DataGridTemplateColumn Header="Amount" CellTemplate="{StaticResource AmountItemTemplate}" />
</DataGrid.Columns>
```
Instead of using the DataGridTextColumns. Aside from that it is a very nice tutorial.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/nl-nl/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @teunvanhemert. We're adding this to our backlog.
