### ISSUE TITLE
Link points to old document

### ISSUE THREAD

**Issue by Keboo** [dotnet/docs#6380]
In the opening paragraph there are two links, one for delegates (that is pointed at the new docs.microsoft.com) and one for expression tree (which is pointed at the old MSDN site). I believe the expression tree link should be pointed to the newer documentation here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567260f8-0f94-b48c-8344-0d9780ab4448
* Version Independent ID: 1bebe367-5b93-0b83-72f5-bdf31d65ef5d
* Content: [Lambda Expressions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
You're right. It should go to that page instead.
