### ISSUE TITLE
Expenselt (lowercase L) or ExpenseIt (uppercase i)

### ISSUE THREAD

**Issue by mattb5906** [dotnet/docs#6382]
Please use a better name or font that shows the difference between lower case L (l) and uppercase i (I). Thought it was an odd name for a project, but continued only to realise later that it was Expenseit not ExspenseLt.

https://i.imgur.com/yjw16sX.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @mattb5906 for your feedback. I can see how the name can be confusing to read. Given that this is an enhancement suggestion, I'm adding this to our backlog and to our community project list. PRs for this are welcome!
