### ISSUE TITLE
This removes all spaces, so words get tied together

### ISSUE THREAD

**Issue by samboustani** [dotnet/docs#6385]
Use @"[^\w\.,@-\\%\s]" to keep spaces (added \s)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200f0dfc-55da-8707-83cf-5604001f6f0d
* Version Independent ID: 1b150e03-87bd-6878-c1da-72d59be2e7eb
* Content: [How to: Strip Invalid Characters from a String](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-strip-invalid-characters-from-a-string)
* Content Source: [docs/standard/base-types/how-to-strip-invalid-characters-from-a-string.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-strip-invalid-characters-from-a-string.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for pointing this out @samboustani 
I've added it to our backlog.  In the meantime, would you like to submit a PR to update the sample?

**Comment by mattdreher** [comment]
It also strips characters with diacritic markings.
