### ISSUE TITLE
Exception handling?

### ISSUE THREAD

**Issue by bobsort** [dotnet/docs#6389]
in Calculate method, randomly throw exception or a deadlock or sleep for next 10 years. what happens main thread reach WaitHandle.WaitAll(doneEvents)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96a63b62-dd9b-aea0-87e8-2219dc37df69
* Version Independent ID: 364eb267-f008-89cf-4fb1-157fdf80fa15
* Content: [How to: Use a Thread Pool (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/how-to-use-a-thread-pool)
* Content Source: [docs/csharp/programming-guide/concepts/threading/how-to-use-a-thread-pool.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/threading/how-to-use-a-thread-pool.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
NOTE: the referenced page was removed by PR #6739 and redirects to the [ThreadPool.QueueUserWorkItem](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.queueuserworkitem?view=netframework-4.7.2) API page. The code example was also moved to that API page ([QueueUserWorkItem(WaitCallback, Object) example](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.queueuserworkitem?view=netframework-4.7.2#System_Threading_ThreadPool_QueueUserWorkItem_System_Threading_WaitCallback_System_Object_)). So, the original question stays actual.

**Comment by BillWagner** [comment]
Thanks for writing this @bobsort and adding the clarifying comments @pkulikov 

These are important questions that should be answered as part of this sample.

I've added this issue to our backlog, and to our project on async / parallel and related programming concepts.
