### ISSUE TITLE
dotnet cli command to search for nuget packages

### ISSUE THREAD

**Issue by nelsonmorais** [dotnet/docs#6393]
Is there a way to use the dotnet cli to search for nuget packages?
If not, what is the preferred way to use VSCode + Mac and search for nuget packages to be added to a project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Currently, there is no CLI command to search for NuGet packages. Adding @KathleenDollard and @livarcocc to comment on future plans for CLI in regards to that.

There are a few extensions for VS Code that provide NuGet package manager capabilities. I haven't personally used any to recommend one.

**Comment by nelsonmorais** [comment]
Thank you for the feedback. Looking forward for the feedback from @KathleenDollard or @livarcocc

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc can you please comment on this product request? If there are no plans to support this, I'd just close this doc feedback.

**Comment by Mizux** [comment]
Same issue as in https://github.com/dotnet/cli/issues/9859 which has been moved to https://github.com/NuGet/Home/issues/7217

**Comment by KathleenDollard** [comment]
Since this is already reported as a product request, can we close the issue here?

The CLI team is sad we can't offer this without NuGet, and they are busy with many things.

**Comment by Mizux** [comment]
> The CLI team is sad we can't offer this without NuGet, and they are busy with many things.

Not sure I follow you, `dotnet/cli` is already embedding a subset of nuget commands...
```
dotnet nuget delete
dotnet nuget locals
dotnet nuget push
```
src: https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x#cli-commands
or `dotnet nuget --help`

 I (we?) only ask for extending the support to add the missing ones.

**Comment by mairaw** [comment]
Yes, I think we should close this doc feedback. If this ever gets implemented by the CLI, we'll document it on docs. The tracking bug that seems to be open at the moment is https://github.com/NuGet/Home/issues/6060.

**Comment by mslot** [comment]
Maybe use this: https://www.nuget.org/packages/dotnet-search/?

**Comment by reecebradley** [comment]
IMHO: I would think this would be part of the CLI. Search/Add/Remove/Update nuget packages seems pretty basic.

**Comment by rkeithhill** [comment]
>  I would think this would be part of the CLI.  Search/Add/Remove/Update nuget packages seems pretty basic.

That's a bit +💯.  Every single other package manager I've used (npm, conan, apt, yum, winget, powershellget, pip, and even nuget.exe) provides a way to search for packages from the CLI.

**Comment by mattvasc-mcd** [comment]
> Maybe use this: https://www.nuget.org/packages/dotnet-search/?

This unfortunately will not cover the scenarios where someone is using private NuGet servers.

**Comment by mairaw** [comment]
@baronfel do you have any issue tracking a feature request like this?

**Comment by baronfel** [comment]
I don't, but it sounds awesome. Pinging @JonDouglas for visibility here - do you know of any tracking issues for this?

**Comment by JonDouglas** [comment]
https://github.com/NuGet/Home/issues/6060

It is on our list this year for https://devblogs.microsoft.com/nuget/nuget-season-of-giving/

https://github.com/NuGet/Home/labels/Category%3ASeasonOfGiving
