### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by kehlankrumme** [dotnet/docs#6399]
There is no reference of the System.Web.Http.Filters namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8dd569-a7d7-2f13-61ce-18c95def3b9e
* Version Independent ID: fbbad1ea-e130-15fe-0636-d893a99e91f2
* Content: [System.Web Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.web?view=netframework-4.6.2#feedback)
* Content Source: [xml/ns-System.Web.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Web.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@mairaw currently we have no plans to migrate it to API browser.

**Comment by mairaw** [comment]
Sounds good. Thanks @Rick-Anderson!
