### ISSUE TITLE
Collections link is incorrect

### ISSUE THREAD

**Issue by slolife** [dotnet/docs#6400]
Collections link in page content is incorrect and points to CPP/MFC collection page (https://docs.microsoft.com/en-us/cpp/mfc/collections) but the Collections link in the sidebar points to the .NET guidelines (https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections) which is correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5578140-d1c7-c440-a1c9-8cdd32857093
* Version Independent ID: b21245f5-0f1f-467c-14c7-f48255c919e0
* Content: [Usage Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/usage-guidelines)
* Content Source: [docs/standard/design-guidelines/usage-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @slolife! We'll get that fixed.
