### ISSUE TITLE
Missing command to add the missing assets to build and debug your app

### ISSUE THREAD

**Issue by jinhale** [dotnet/docs#6408]
There seems to be a missing command to add the missing assets to build and debug the app. Is VS Code limited in this way such that the only way to trigger it to create a default .vscode folder and associated files is to open the folder after creating the app in a terminal? It's just an annoyance to restart VS Code to get the prompt to show, and if an external terminal is required then that defeats some of the utility of having an integrated terminal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - C# Guide](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by kendrahavens** [comment]
Sure! There is a command you can use. We can update a doc to include these instructions:

1. Pressing "F1"
2. Typing ".NET Generate Assets for Build and Debug"
3. Selecting that option. 
![image](https://user-images.githubusercontent.com/8293542/42709682-236649b2-8696-11e8-9f4a-d12ec835fa0b.png)

Alternatively, if F1 doesn't work on your keyboard:
1.  You can open the Command Palette. (Ctrl + Shift + P or through the menu)
![image](https://user-images.githubusercontent.com/8293542/42709807-9dcd9214-8696-11e8-9917-6c39aba9061c.png)
2. Type ">" and ".NET Generate Assets for Build and Debug" and select.

**Comment by JoseMOrtizR** [comment]
Make sure you have installed the extension .NET Extension Pack in Visual Studio Code before typing the command '.NET Generate Assets for Build and Debug'

**Comment by umutlaguler** [comment]
You should have an extension about .NET after that you can see the .NET in command pallette. I added .NET Core Extension Pack and my problem solved

**Comment by winiciuscota** [comment]
is there any way to add assets to an existing configuration(without regenerating the configuration)? One might have multiple entry point projects

**Comment by kendrahavens** [comment]
Yes, this will require editing the launch and task files directly and listing multiple configurations. I recommend checking out the [compound launch configurations doc section](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations).
