### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EddieLotter** [dotnet/docs#6409]
The "NumericUpDown Custom Control with Theme and UI Automation Support Sample" link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd7d447-2d1a-9b5f-d124-bca7cd01f7ed
* Version Independent ID: 9e959d9e-0d99-61b0-db6b-3b84446834ab
* Content: [Control Authoring Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/control-authoring-overview)
* Content Source: [docs/framework/wpf/controls/control-authoring-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/control-authoring-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @EddieLotter. Most of the WPF samples were moved from the site that was shut down to https://github.com/Microsoft/WPF-Samples. However, I couldn't find this particular sample there. There's a version of the project at https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_Wpf/CustomControlNumericUpDownOneProject/CSharp, however we'd have to check if it matches the text. So moving this to our backlog.

**Comment by EddieLotter** [comment]
Thanks for looking into it @mairaw.
