### ISSUE TITLE
Jumps

### ISSUE THREAD

**Issue by CharlieHoffmann** [dotnet/docs#6412]
"The", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog." 
Jumps not jumped, but that's just my brain paying attention to that instead of actually learning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a5e33e-938d-b72d-b211-ab5245413af5
* Version Independent ID: db96afbb-50af-5dee-b7b3-97600161e737
* Content: [How to: Concatenate Multiple Strings (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings#feedback)
* Content Source: [docs/csharp/how-to/concatenate-multiple-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/concatenate-multiple-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CharlieHoffmann thanks for your feedback. Any feedback is valid! I've created a PR to fix this for this content: https://github.com/dotnet/samples/pull/170 

@BillWagner @rpetrusha this same sentence using past tense is used throughout our samples repo. Should we make this issue an up-for-grabs one?

**Comment by BillWagner** [comment]
> This same sentence using past tense is used throughout our samples repo. Should we make this issue an up-for-grabs one?

Yes, and done.

**Comment by sputier** [comment]
I "jumped" on this issue this morning :-)
