### ISSUE TITLE
 New-AzureRmADApplication link broken

### ISSUE THREAD

**Issue by srayan** [dotnet/docs#6420]
The link to  New-AzureRmADApplication is broken (404's out). Please update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523be1c3-4079-4f28-13ab-353b7a116c98
* Version Independent ID: 78a37644-6ecc-3752-38ee-4eb18819bc9b
* Content: [Using Azure Key Vault to protect secrets at production time](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/secure-net-microservices-web-applications/azure-key-vault-protects-secrets#feedback)
* Content Source: [docs/standard/microservices-architecture/secure-net-microservices-web-applications/azure-key-vault-protects-secrets.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/secure-net-microservices-web-applications/azure-key-vault-protects-secrets.md)
* Product: **dotnet**
* GitHub Login: @mjrousos
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @srayan. I've opened PR #6460 to fix this.
