### ISSUE TITLE
[Question] How to generate fragment part of the url for an overloaded member

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/docs#6421]
Hi,

I'm working on a tool that includes generation of links to **docs.microsoft.com** for particular symbols. I'm especially interested in overloaded members that are distinguished by the fragment part of the url.

Problem is that I don't know how generate the fragment part of the url.

Example:

for method `List<T>.BinarySearch(Int32, Int32, T, IComparer<T>)`

the fragment part is:

**System_Collections_Generic_List_1_BinarySearch_System_Int32_System_Int32__0_System_Collections_Generic_IComparer__0__**

I would like to know if there is open source code that is responsible for generation of fragments or if these rules are desribed somewhere.

**Comment by mairaw** [comment]
@dend @TianqiZhang are those generated by [DocFX](https://dotnet.github.io/docfx/)?

**Comment by mairaw** [comment]
Moved issue to https://github.com/MicrosoftDocs/feedback/issues/567
