### ISSUE TITLE
This pair of example apps did't work for me. 

### ISSUE THREAD

**Issue by MattBaker12** [dotnet/docs#6423]
I'm using studio 2017 professional.
The "Encoding.ASCII.GetBytes(args[0]);" failed as there were no args ? so I added a dummy argument to the command line input.
Then the listener just sits waiting for a message.
Now my network uses 192.168.50.x so I changed IP address in the sender app to suit.
Any ideas ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Using UDP Services](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by maharsh007** [comment]
Hi,
I am facing issue while using the example. The broadcast receiver is not receiving the message when the client and the server are in different network
