### ISSUE TITLE
List of permissible values missing

### ISSUE THREAD

**Issue by Toonshorty** [dotnet/docs#6426]
The documentation for site designs (https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#configure-regional-settings) links to this page for displaying a list of permissible values, but no values are shown in the documentation.

**Comment by mairaw** [comment]
Thank you @Toonshorty for your feedback. I moved the issue to the appropriate repo (https://github.com/SharePoint/sp-dev-docs/issues/2227) and we also made some configuration changes for new SharePoint bugs to go to the correct place.
