### ISSUE TITLE
Constructor example uses misleading language when describing assignment

### ISSUE THREAD

**Issue by binki** [dotnet/docs#6427]
At https://docs.microsoft.com/en-us/dotnet/standard/attributes/writing-custom-attributes#declaring-constructors , I see:

&gt; This public constructor takes a parameter and sets its value equal to a member variable.

The phrase “sets its value equal to” means that the value of “it” becomes the latter value. In this case, that sentence states that the value of the parameter has the value of the member variable assigned to it.

In fact, the opposite is happening. The parameter’s value is being assigned to the member variable. I think this language should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7645edc8-46ad-431f-4f91-e77ba3941f17
* Version Independent ID: ff721860-b8e8-3c3d-aefa-f1ec3e00fa69
* Content: [Writing Custom Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/writing-custom-attributes#declaring-constructors)
* Content Source: [docs/standard/attributes/writing-custom-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/writing-custom-attributes.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out this error, @binki. We've opened PR #6508 to address it.
