### ISSUE TITLE
Provide programmatic examples

### ISSUE THREAD

**Issue by jaxidian** [dotnet/docs#6429]
For this, and *all* web.config examples, I would like for a programmatic example to either be included or linked to. This has been a common problem for many years for me and others. This should not be difficult to find.

The reason for doing this is for environment configuration purposes. Here's an exmaple:

Imagine an application using this being deployed to Azure App Services with Deployment slots. I might have a staging deployment slot hosted at staging.example.com with the production version at www.example.com. In this case, I need the application to work in both slots but at different addresses. To accomplish this, I would have a "Slot Setting" specify the value of the audienceUri for each environment but I would need to programmatically register that value with WIF since that feature is not available to inject settings into other parts of the web.config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28e1d33-0477-8cbd-9f2d-ad03e8eb127f
* Version Independent ID: 31d6cedb-d37a-1694-3f9a-b23cf847d586
* Content: [&lt;audienceUris&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/audienceuris)
* Content Source: [docs/framework/configure-apps/file-schema/windows-identity-foundation/audienceuris.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/windows-identity-foundation/audienceuris.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @jaxidian. We've added your issue to our backlog and to our community contributors' project.
