### ISSUE TITLE
>>> documentation is incorrect

### ISSUE THREAD

**Issue by Ciantic** [dotnet/docs#6430]
"For signed types, the most significant bits are padded with ones. " is incorrect.

It should say something like "For signed types with negative values, the most significant bits are padded with ones.".

E.g. 32 &gt;&gt;&gt; 1 is not padded with 1 on the left, only the negative values are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6038fe-3689-5034-de9c-a153621c1c6f
* Version Independent ID: 2b63d07f-54d5-afc0-38b0-36ea80f1647d
* Content: [Bitwise Operators (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/bitwise-operators)
* Content Source: [docs/fsharp/language-reference/symbol-and-operator-reference/bitwise-operators.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/symbol-and-operator-reference/bitwise-operators.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by rpetrusha** [comment]
//cc @cartermp

**Comment by cartermp** [comment]
Link #6589 - Thanks @Ciantic
