### ISSUE TITLE
Proposed topic: Catching IO errors in .NET

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6431]
# Proposed topic: Catching IO errors in .NET

## General
In general, .NET wraps the IO error returned by the operating system in an Exception object, which it then throws. The problem is that an identical exception condition (a directory not found, for example) can be wrapped in one of several exception types (DirectoryNotFoundException, FileNotFoundException, and possibly IOException). (I'm not sure about IOException -- @JeremyKuhne, is this possible?) Our doc set doesn't provide any guidance on handling IO exceptions specifically. Nothing that developers should handle all of these exceptions, rather than just one, is extremely important.

## Requests for new Topics

1. thee topic should be found in the docs/standard/exceptions or docs/standard/io directory. My preference is for docs/standard.io.

2. See the General section for information on the article's contents. The article needs to stress that exceptions reflect error conditions returned by the operating system, so that identical error conditions can generate multiple exceptions.

## Cross-references

Any API that throws one of a class of exceptions can, in theory, throw any other exception in that calss. So an API that throws a FileNotFoundException can throw a DirectoryNotFoundException, for example. A link to this topic needs to be added to every API that can throw one of the exceptions in this set.

## More information

See dotnet/dotnet-api-docs#336

//cc @jpreese @JeremyKuhne

**Comment by JeremyKuhne** [comment]
IO exceptions include:

- `System.IO.FileNotFoundException`
- `System.IO.DirectoryNotFoundException`
- `System.IO.PathTooLongException`
- `System.IO.DriveNotFoundException`
- `System.IO.IOException` (base of all other System.IO exceptions and thrown directly for errors that don't match the derived types)
- `System.OperationCancelledException`
- `System.UnauthorizedAccessException`
- `System.ArgumentException` (thrown for invalid path chars up until .NET Core 2.1)
- `System.NotSupportedException` (thrown for invalid colons up until .NET Core)
- `System.Security.SecurityException` (limited trust only on .NET Framework)

For Argument/NotSupported see https://referencesource.microsoft.com/#mscorlib/system/security/permissions/fileiopermission.cs,1087

In general, when calling IO APIs you should catch all of these. `SecurityException` can be skipped if you aren't running in limited trust (full trust is the default).

For `IOException` exceptions it is effectively impossible to definitively say what input leads to what variant of that exception. The derived classes are picked based on what the OS provides us for an error, which is rarely documented. As a result, you should always expect to get any of these exceptions for just about any System.IO call.

In .NET Core 2.1 we've removed path correctness checks (notably for bad path characters, colons, etc.) as these checks were very specific to NTFS/FAT on Windows. The checks prevented accessing valid paths to mounted folders to other file systems, were extremely expensive, and duplicated what the file system drivers do. If a path is in a "bad" format it will now throw when actually used based **on what the OS tells us**.  That will often mean the base `IOException`, but can possibly be derived exceptions or even others listed, such as `UnauthorizedAccessException`.
