### ISSUE TITLE
use `<RuntimeIdentifier />` or `<PlatformTarget />`

### ISSUE THREAD

**Issue by John0King** [dotnet/docs#6437]
Sinc new  Sdk Can directly publish Self-Contained app now, when specify x64 or x86 , what should we use ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
@John0King, you create a separate deployment for each platform that you target. The target platforms are defined by a runtime identifier (RID) defined in the [.NET Core RID Catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog). If you want to target both 32-bit and 64-bit Windows platforms, for example, you'd have to create separate 32-bit and 64-bit Windows deployments.

I don't think that your question has a documentation impact, so I'm closing the issue. If you disagree, please let us know by responding.

**Comment by John0King** [comment]
@rpetrusha  I hope the doc can explain more about `<RuntimeIdentifier />` and `<PlatformTarget />`, 
AFIK, when I set  `<RuntimeIdentifier >win-x64 </RuntimeIdentifier>`  the assembly is target `x64`,
But when I set   `<RuntimeIdentifiers >win-x64;win-86 </RuntimeIdentifiers>`  the assembly is target `AnyCPU`
and when I **not** use `.net core` but use `net461`  and OutPutType is exe, the  assembly is target x86 by default.  but I want my app be x64 or AnyCpu ,  What should I use `<RuntimeIdentifier />` or `<PlatformTarget />`
