### ISSUE TITLE
TestCatch2()

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6442]
When sw is null, this line (in the finally block) will produce an unhandled exception :
sw.Close();

It happens when there is no c:\test directory.

Furthermore, if c:\test does exist but there is no c:\test\test.txt file, this file will be created anyway.
So I don't see why we would want to catch a FileNotFoundException.
I would suggest:
1. to replace the FileNotFoundException with DirectoryNotFoundException
2. to add in the finally block, this line of code to avoid the unhandled exception:
if (sw != null)
just before sw.Close();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b719792d-1f95-6743-743a-8906fe08e764
* Version Independent ID: f67c914a-a895-2fd4-5b5a-2f5bedde1f91
* Content: [Using Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/using-exceptions)
* Content Source: [docs/csharp/programming-guide/exceptions/using-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/using-exceptions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@johnnyagerard good catch. As for the second step suggested by you, it can be even shorter:

```csharp
sw?.Close();
```

In general, [using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) should be considered for the example.
