### ISSUE TITLE
Can we connect a Synchronous Socket Client to Asynchronous Socket Server?

### ISSUE THREAD

**Issue by imkaka** [dotnet/docs#6443]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87c349f-3592-3f62-315d-e85db695041b
* Version Independent ID: efce9f39-4ba4-a61d-4330-e60dcfaf99ca
* Content: [Using an Asynchronous Client Socket](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-an-asynchronous-client-socket)
* Content Source: [docs/framework/network-programming/using-an-asynchronous-client-socket.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-an-asynchronous-client-socket.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by mairaw** [comment]
@davidsh can you provide some insight into this?

**Comment by davidsh** [comment]
>@davidsh can you provide some insight into this?

I don't understand the question being asked here.  You can use either Synchronous based Socket APIs or Asynchronous ones to connect to a server. It doesn't matter how the server itself is implemented internally.

**Comment by rpetrusha** [comment]
Thanks, @davidsh. Closing...
