### ISSUE TITLE
What does "Seek a functional interface over a mutation-based implementation." mean?

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/docs#6449]
Can we add a link for this to show exactly what this concept means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63d2086-c15d-2434-8189-c2acaab237ca
* Version Independent ID: 08a7d210-bab0-fdd3-5629-34dcc79172e1
* Content: [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/)
* Content Source: [docs/fsharp/style-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
There's no link that I have on hand (as this isn't some idiom or anything), but I think it is a bit ambiguous as-worded. I made a change in #6450 - does that help?

**Comment by csharpfritz** [comment]
It helps...  for less savvy programmers, blocks of before and after code examples that demonstrate these guidelines would be very valuable

**Comment by cartermp** [comment]
Perhaps linking to the section in the conventions article that explains this in more detail would help?

https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions#performance

**Comment by csharpfritz** [comment]
Yep... that does help



Jeff

**Comment by cartermp** [comment]
Great, thanks. That second does contain an example of this phrase, in addition to other considerations (such as hiding some stuff behind a class).

**Comment by cartermp** [comment]
Link to section with code sample implemented here: #6450

Additionally, the ambiguity was cleared up in the text.
