### ISSUE TITLE
Development without restarting a docker container

### ISSUE THREAD

**Issue by roussakov** [dotnet/docs#6463]
Hi guys! This is a great resource overall. 
One thing is missing for me.
I want to provide a better development experience for my team using .net core and docker-compose.
Could you provide instructions for setup dotnet watch along with docker containers which won't require restart docker-compose stack each time the code has changed? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: 0df5f0d7-a2b4-e9b3-9f34-d66cedf418a3
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow)
* Content Source: [docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CESARDELATORRE @richlander can you comment on this request?

**Comment by CESARDELATORRE** [comment]
You could start only specific containers when using docker-compose, too.
Like: 
$ docker-compose up yourService
to start just yourService and all dependencies required by it.
So if yourService depends on a sql container, the above command would start both the containers.

**Comment by mvelosop** [comment]
Hi @roussakov,

I might be getting you wrong but, the way I see it, that could actually hinder your team's work, because every time you execute `docker-compose up` it's a several minutes wait (>15 min on eShopOnContainers).

I'm a compulsory Ctrl-S maniac so it just would do for me.

Am I missing something here?

Would a CI/CD pipeline that triggers on push to dev branch make more sense?

Hope this helps.

**Comment by CESARDELATORRE** [comment]
Docker-compose up takes 15 min just the first time you need to compile everything and create all the Docker images. If you just update a single image Docker-compose up takes just 2 minutes or so.
Another approach if you already chose Kubernetes is to use Azure Dev Spaces and deploy a single service to a cluster that already has the rest of the services deployed.

**Comment by mvelosop** [comment]
Closing this issue now, as there doesn't seem to be much to add, but feel free to comment.

Will reopen if needed.
