### ISSUE TITLE
Suggestion for improvement: TDD misunderstood

### ISSUE THREAD

**Issue by allanlykkechristensen** [dotnet/docs#6465]
You refer as TDD as writing a wrong test, running the test and then fixing the test. This is not TDD and it doesn't have any purpose.

As specified on https://en.wikipedia.org/wiki/Test-driven_development TDD show follow this pattern:

1. Add a test
2. Run all tests and see if the new test fails
3. Write the code
4. Run tests
5. Refactor code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Getting started with .NET Core on macOS](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by guardrex** [comment]
Thanks for commenting @allanlykkechristensen ... TDD isn't referred to in this topic. I fixed #6464 on #6466.

There's nothing wrong with writing a regression test first. I've caught myself a few times in tricky situations writing a bad test using this technique.
