### ISSUE TITLE
4.7.2, 4.7.3 and 4.8

### ISSUE THREAD

**Issue by jbruns2015** [dotnet/docs#6471]
When will this document updated to reflect these new releases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
That topic already contains 4.7.2 and the other two (4.7.3 and 4.8) don’t exist, at least for now.

**Comment by jbruns2015** [comment]
If you actually read the paragraph titled "Targeting and Running .NET Framework apps for version 4.5 and later" you will note missing 4.7.2

**Comment by mairaw** [comment]
Thanks @jbruns2015. We'll review this more carefully.
