### ISSUE TITLE
Terrible example; please revise

### ISSUE THREAD

**Issue by mgravell** [dotnet/docs#6472]
This example has 2 fundamental flaws:

1. the `lock` is unnecessary; since `PreDrawEvent` is declared as a private `event` (which may or may not be wise, but that's another matter), it already has thread-safety implemented by the compiler via the "field-like events" specification
2. the `lock` is invalid - it locks on a changing value (bad) that might be `null` (very bad)

Very bad code. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a96a00d-16c2-78da-1394-58e9db154d2f
* Version Independent ID: ce67b2fa-8c51-06f5-fe8c-ba98b697bc2c
* Content: [add (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/add)
* Content Source: [docs/csharp/language-reference/keywords/add.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/add.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @mgravell 

Your analysis is correct. This example needs to be updated.

**Comment by mr5z** [comment]
This would also throw an exception when you try to register to OnDraw if PreDrawEvent is still empty. An awful fix would be to initialize the PreDrawEvent with an empty delegate.
