### ISSUE TITLE
non-parallel is faster in this example...

### ISSUE THREAD

**Issue by rs38** [dotnet/docs#6474]
omitting .asParallel() is always much faster in my tests…??                     

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030c37a7-d371-aeae-bef7-1dd1f23f8cb0
* Version Independent ID: f966cb87-ae73-2f76-583a-f88583464752
* Content: [How to: Measure PLINQ Query Performance](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-measure-plinq-query-performance)
* Content Source: [docs/standard/parallel-programming/how-to-measure-plinq-query-performance.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-measure-plinq-query-performance.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rs38** [comment]
due to the very tiny operation "load" and much task synchronization.
I found this example on stackoverflow much better suited:

```
using System.Diagnostics;
Stopwatch sw = new Stopwatch();

int[] vals = Enumerable.Range(0, 200_000).ToArray();

sw.Start();
int[] x1 = vals.Where(IsValid).ToArray();
sw.Stop();
Console.WriteLine("Sequential Execution {0} milliseconds", sw.ElapsedMilliseconds);

sw.Restart();
int[] x2 = vals.AsParallel().Where(IsValid).ToArray();
sw.Stop();
Console.WriteLine("Parallel #1 Execution {0} milliseconds", sw.ElapsedMilliseconds);

sw.Restart();
int[] x3 = vals.AsParallel().Where(IsValid).ToArray();
sw.Stop();
Console.WriteLine("Parallel #2 Execution {0} milliseconds", sw.ElapsedMilliseconds);



static bool IsValid(int input)
{
    int result = 0;

    for (int i = 0; i < 5000; i++)
        result = input % 2;

    return result == 0;
}
```

**Comment by svick** [comment]
The code is also problematic, because it will include JIT time in the measurement and because it executes only once.

Would it make sense to use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) instead? And maybe make it more useful by comparing serial and parallel versions?
