### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Sleeplikelion** [dotnet/docs#6478]
Good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2cc16c-fcf9-41e6-a1e5-92dfc2869495
* Version Independent ID: 4421a02c-f819-1483-12c6-7dab4f289a46
* Content: [C# interactive tutorials - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/#string-interpolationinterpolated-stringsyml)
* Content Source: [docs/csharp/quick-starts/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/quick-starts/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank you for the positive feedback, @Sleeplikelion. We're happy that you liked the interactive tutorial.
