### ISSUE TITLE
Version attributes like VersionPrefix aren't documented

### ISSUE THREAD

**Issue by vbfox** [dotnet/docs#6479]
They are referenced in https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#common-top-level-properties without details but not documented here in the csproj format.

How the attributes interact & what other properties they auto-fill (assembly version, informational version, package version) would be nice to have here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
The pack target properties are covered in the NuGet docs now, so I'm closing this issue. Please open a new issue on https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target if you would still like to have this documented.
