### ISSUE TITLE
Document implicit package references

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/docs#6482]
The .NET Core SDK currently has a link in its warnings/errors which point to https://aka.ms/sdkimplicitrefs. This redirects to https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-implicit-package-refs.md. We should move this content into docs and polish it up.

Also, assuming we end up merging https://github.com/dotnet/sdk/pull/2394, we should also document `RuntimeFrameworkName` and its usage with ASP.NET Core 2.1 projects.
## Requests for new Topics

1. Tell us where this topic should go in the Table of Contents.

   - Some of this is already covered in https://docs.microsoft.com/en-us/dotnet/core/packages, but it might be good to have a dedicated doc under 'Migration'

2. Write an abstract

	> The .NET Core SDK will add package references to .NET Core and .NET Standard projects which are required to compile for and run on .NET Core. These package references are used as a way to distribute binaries required for the C# compiler and also for self-contained deployment. Generally speaking, these package references do not need to appear in a project file (\*.csproj). They are implied by using the TargetFramework and RuntimeFrameworkName properties. The version of these packages is inferred by the SDK based on the version of .NET Core targeted by the project.

3. Fill in an outline

    * How to implicit package reference work
	* Resolve warning NETSDK1023
	* Resolve warning NETSDK1071
	* Specifying a version for implicit package references
	* Disabling implicit package references

4. Suggest reviewers

    cc @dsplaisted @nguerrera

**Comment by mairaw** [comment]
Thanks @natemcmaster. The Packages, metapackages and frameworks topic has been on the list to be updated for a while now. It needs to be revised since we haven't updated it for 2.0+. Once we're ready to start on this, our team will sync with you on the direction this should take.
