### ISSUE TITLE
host example needlessly/confusingly duplicates service

### ISSUE THREAD

**Issue by jepp** [dotnet/docs#6484]
Hopefully someone else will benefit from this note. In this example, the given Main() used for the console host app is pointless. All of this code could be deleted except for the Console.WriteLine/ReadLine lines. This code creates a **second** service in addition to the first one shown in the previous pages of the tutorial. And it creates it on a different port. The earlier app.config defined one is on 8733 and this one is on 8000.

This is a good example of creating stuff in code instead of the app.config, but it's not in any way marked like that and only confuses people learning this. I was trying to switch the example from http to named pipes and I wound up getting "already in use" issues. Only now does it make sense as to why, since there were basically two servers on the same named pipe.

Edit: And to help anyone who might be getting confused by another aspect of this, by default when you have both the host and the lib in the same solution, running the host will ALSO cause VS to run a service host for the lib. This can be disabled in the project properties for the lib project, under WCF Options. Uncheck "Start WCF Service Host when debugging another project in the same solution." Once you do that, you get ONLY the service endpoint you create in the host.

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 0c8cbb16-05b1-a5f2-9031-1d7beb52efea
Version Independent ID: 98092a9f-c19a-cca9-75d6-75b9c3d4cc0b
Content: How to: Host and Run a Basic Windows Communication Foundation Service
Content Source: docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
Product: dotnet-framework
GitHub Login: @dotnet-bot
Microsoft Alias: dotnetcontent

**Comment by kookyabird** [comment]
This was extremely helpful for me and probably saved me a lot of time. I followed these examples to the letter and was very confused when my standalone "GettingStartedHost.exe" was not responding on the same URL as when I ran from VS. It's because VS was running the actual Lib service, and the Host app created the same service on another URI. This really needs to be changed.

**Comment by fredrikhaglund** [comment]
Partly agree. When you add a WCF Service Library, Visual Studio can host it for you when you debug by starting a service host. 

This is enabled or disabled in **Project Properties > WCF Options > Start WCF Service Host when debugging**. 

A real world service needs some sort of host so I think this step is relevant, possibly other types of hosting should be mentioned and linked in See also section.

**Comment by jepp** [comment]
Yes, if I was writing this again, I'd word it differently. I've learned a lot about WCF since then, but this tutorial wasn't the source of most of it.

**Comment by juandelacruz23** [comment]
So, in this issue the problem is that Visual Studio automatically created a development host for the Lib alongside with the Console app?
