### ISSUE TITLE
one use of value keyword missing

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#6487]
The contextual keyword "value" can be used in the set accessor of indexers too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e70b29-7da5-0604-0aa7-b13800a3cd9d
* Version Independent ID: 131d33af-fbc4-20e9-46bb-0a92e6254dbb
* Content: [value (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value)
* Content Source: [docs/csharp/language-reference/keywords/value.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/value.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by garg000dhruv** [comment]
I can take a look at this.
