### ISSUE TITLE
Assume Tutorials

### ISSUE THREAD

**Issue by Siri94** [dotnet/docs#6492]
It's a good explanation how to do with practicing code. 
First, traditionally, start "Hello World!" (not surprising) and then typing immediately! 
Second, Object-Oriented Programming(OOP) should be familiar with us. 
The tutorial simply mentions this concept using "string" type. 
Final, the assume is Microsoft skips trivial environment settings, installing a Visual Studio or Visual Compilers, thanks to the online compiler. (Is it a interpreter? I suspect it)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Hello World interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @Siri94. We're pleased that you liked the interactive tutorial. As far as I now, it's JIT-compiled, although @LadyNaggaga may correct me.
