### ISSUE TITLE
Remove reference to non-existent projects

### ISSUE THREAD

**Issue by stormwild** [dotnet/docs#6499]
Is there a way to remove reference to no longer existing projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
Hi, @stormwild - In the examples section [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#examples), check out the "**Remove a C# project from a solution**" example. That will remove a project from a solution.  Have a good day!
