### ISSUE TITLE
"Do not reference mscorlib.dll" as an option does not exist

### ISSUE THREAD

**Issue by mattcowen** [dotnet/docs#6500]
In VS2017, there is no option "do not reference mscorlib.dll" in the advanced dialog as described on this page - https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nostdlib-compiler-option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bdeb7a8-8d77-961f-ce9f-e755fdcf8613
* Version Independent ID: 5e7fcc43-1513-7bd3-50cf-87ae435ee062
* Content: [-nostdlib (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nostdlib-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/nostdlib-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/nostdlib-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks, @mattcowen. I've added clarification language to the article, as you can only set this option in Visual Studio 2015 and earlier versions. You can see the change in the PR link above.
