### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by wildbiotiger** [dotnet/docs#6501]
The "Thumb Drag Functionality Sample" link to http://go.microsoft.com/fwlink/?LinkID=160042 leads to a broken archive.msdn link. Is there a valid link to the sample somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb49bc6-864e-9627-5662-0780663218c0
* Version Independent ID: e0b37d1f-6c8e-7d68-6f30-952c33aa4126
* Content: [How to: Resize a Canvas by Using a Thumb](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-resize-a-canvas-by-using-a-thumb)
* Content Source: [docs/framework/wpf/controls/how-to-resize-a-canvas-by-using-a-thumb.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-resize-a-canvas-by-using-a-thumb.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this @wildbiotiger. I've fixed the target URL of that link to point to https://github.com/Microsoft/WPF-Samples/tree/master/Drag%20and%20Drop/DragDropThumbOps.
