### ISSUE TITLE
What should we set it to?

### ISSUE THREAD

**Issue by DavidThi808** [dotnet/docs#6506]
It would be helpful if you provided guidance as to when we should set this. What's optimum for different situations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31b15e3-dc34-d066-7c35-728f0d9ebf95
* Version Independent ID: bb9285fc-c821-9c28-cbda-dfe53a429b3d
* Content: [&lt;gcServer&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/gcserver-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/gcserver-element.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @DavidThi808. @Maoni0 do you see anything that we could add to that topic to make it more helpful?

**Comment by pkulikov** [comment]
@DavidThi808 is the following link useful?
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#workstation-and-server-garbage-collection

and its subsection:
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#comparing-workstation-and-server-garbage-collection

**Comment by Maoni0** [comment]
what @pkulikov said

**Comment by mairaw** [comment]
Ok thanks @pkulikov and @Maoni0. See if that would help @DavidThi808 and we could add links to the existing topic from the gcServer element for more info.

**Comment by DavidThi808** [comment]
You provide a lot of useful information if someone wants to learn all the nuances of the garbage collector. And that's good.

But what is not there is someone who wants a very quick answer. Granted, that answer may not fit any situation. But still, many people don't want to invest the time to learn all about this.

So maybe something at the top like "For most (not all!) cases, server mode is break-even for 2 - 4 threads and recommended for 4+ threads. For one thread leave it on the default.
