### ISSUE TITLE
ASP.NET Core 2.1 Hosting samples

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/docs#6509]
Hi
The provided link leads to a 404 github page. Please fix that.
Best
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 45b409c8-f64d-da19-a2ec-b91f21696a5b
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @ericbrunner. I've opened PR #6516 to fix this.
