### ISSUE TITLE
MVC Testing video link

### ISSUE THREAD

**Issue by aligneddev** [dotnet/docs#6511]
https://www.youtube.com/watch?v=wtOE-xmFJkw&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=5 is a good resource for Asp.Net Core 2.1. 
Javier C. Nelson pointed to https://github.com/aspnet/Identity/tree/master/test/Identity.FunctionalTests near the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ba44f-bfb6-e9bf-0bba-b91ee867340d
* Version Independent ID: e7beb014-243f-1569-fca0-0c59bf6f3c05
* Content: [Test ASP.NET Core MVC apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @ardalis, do you think it's OK to include this reference, considering it's a bit dated now?

**Comment by ardalis** [comment]
I don't know a better video reference off-hand. If it doesn't have to be video I'd probably just link here:
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0

**Comment by mvelosop** [comment]
Thanks @ardalis, that's great 😊

Will include both!
