### ISSUE TITLE
Value2 typo

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/docs#6512]
The COM Interop C# before example should assign Value, not Value2 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9885f16-24fc-c4ab-458c-fd38279b9898
* Version Independent ID: dc4040cc-3cec-75cd-73a9-2cb7d890c672
* Content: [Using Type dynamic (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic#dynamic-language-runtime)
* Content Source: [docs/csharp/programming-guide/types/using-type-dynamic.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/using-type-dynamic.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
As @mairaw points out, both the `Value` and `Value2` properties are valid. Closing this for that reason.
