### ISSUE TITLE
When will configBuilders be added to the schema as a valid app settings attribute?

### ISSUE THREAD

**Issue by GingerSnap-xx** [dotnet/docs#6521]
I'm trying to precompile an application for use with WebDeploy and it's throwing errors due to it not being part of the schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea24ffb0-1e4a-4c73-c566-18b67e3bd69c
* Version Independent ID: 1d1c4a41-9dfd-82f9-ed0c-993c45b16b25
* Content: [&lt;appSettings&gt; element for &lt;configuration&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration)
* Content Source: [docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md)
* Product: **dotnet-framework**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @GingerSnap-xx. @csharpfritz is this something you can help with?

**Comment by martingbrown** [comment]
I too am interested in how that works. If I have two builders (User Settings for local dev and Azure Key Vault for production) do I give them both separate names and specify them both in the configBuilders attribute? If I specify both what delimiter should I use? Does it matter what order they are specified in? Does that even work or do I need to use a different config file in production so I specify a different builder?
