### ISSUE TITLE
Update camelCase capitalization for username

### ISSUE THREAD

**Issue by rmunn** [dotnet/docs#6523]
The guidelines for capitalizing compound words and common terms state, "For the purpose of casing guidelines, treat a closed-form compound word as a single word. Use a current dictionary to determine if a compound word is written in closed form." However, this is not followed in the examples in the case of the word "username". The examples show it camelCased as userName, as if it were a two-word compound that would be written as "user name" or "user-name" in English. However, every dictionary I've found lists the word "username" as a closed-form compound word:

https://en.oxforddictionaries.com/definition/username
https://dictionary.cambridge.org/dictionary/english/username
http://www.dictionary.com/browse/username

Given that "username" has become a closed-form compound word in common English usage, following the camelCase guidelines' recommendation would mean camelCasing the word as "username" rather than "userName". I suggest that the examples should be updated for consistency with the guidelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eba6b11-5703-355f-0e85-08ee7451120d
* Version Independent ID: 4691fbb3-7b6d-8c02-e372-315ca302e48e
* Content: [Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)
* Content Source: [docs/standard/design-guidelines/capitalization-conventions.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/capitalization-conventions.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
re-opening because the fix was to modify content that is copyrighted by the original publisher and we don't have the rights to update it.

**Comment by JRAlexander** [comment]
Moved to 142 as author will not be available until then.

**Comment by mairaw** [comment]
Bceause this is copyrighted material, we can't edit it. So closing this,

**Comment by rmunn** [comment]
Wasn't it reprinted from a book by Krzysztof Cwalina and Brad Abrams, who were (still are?) Microsoft employees? I would have thought that therefore Microsoft held the copyright on this material, and could therefore modify it.

Oh well, if copyright issues prevent this doc bug from being fixed, that's too bad. Would it be possible to add a note to the end of the document without violating copyright?
