### ISSUE TITLE
The code in the table is not formatted correctly.

### ISSUE THREAD

**Issue by peterzeller** [dotnet/docs#6526]
The code in the table is not formatted correctly: it shows the triple backtick as normal text. On Github the table is rendered almost correctly but not on docs.microsoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc0f705-c74c-51ea-1ee7-ac62fc71392a
* Version Independent ID: ec09b74f-53a9-3d86-bf44-a7c0694cdafc
* Content: [Verbose Syntax (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/verbose-syntax)
* Content Source: [docs/fsharp/language-reference/verbose-syntax.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/verbose-syntax.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@mairaw do you know if it is possible to do something like this in a table with docfx?

```fsharp
let f x = x
```

Where `fsharp` is used to apply syntax coloring. That's what appears to be happening here, and it's failing to render correctly. Perhaps inline HTML is needed?

**Comment by mairaw** [comment]
I don't think so. You might have to use inline HTML.

See an example I was just working on right now:
https://github.com/dotnet/dotnet-api-docs/pull/370/commits/0a38d489df81732801763bf4314e8bea7b70cf31

It could be better to just use snippet references in cases like this as well.

**Comment by cartermp** [comment]
Gotcha. I'll try and take care of this this week.
