### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PaulCr125** [dotnet/docs#6527]
I'm getting a MemoryProtectionScope reference error. I'm referencing the namespaces listed and using .Net 4.6.1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e223a92-49ef-5bf0-9dab-13b7300fabd4
* Version Independent ID: bbac5ee9-27f0-cf07-5891-32a3e9a0341b
* Content: [How to: Use Data Protection](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection)
* Content Source: [docs/standard/security/how-to-use-data-protection.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-use-data-protection.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
@PaulCr125, is this happening when you're running the example code, or does it result from attempting to compile and execute your own code? Can you provide any additional information, such as the text of the error?

**Comment by mairaw** [comment]
Closing due to the lack of response.
