### ISSUE TITLE
Last example

### ISSUE THREAD

**Issue by johnnygerard** [dotnet/docs#6529]
It is said that:
"global::System.Console must be used to reference the System.Console class"
but I can replace this line:
global::System.Console.WriteLine(name + " " + test[name]);
by this line:
Console.WriteLine(name + " " + test[name]);
and it works fine.

We have access to the Console class because we are in the System Namespace.

There's something wrong here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9c78b1-4949-0bdb-43af-a9db6e5ebffa
* Version Independent ID: cfea46ac-3926-6274-b29e-4c48f1d3cd63
* Content: [How to: Use the Global Namespace Alias (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias)
* Content Source: [docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by johnnyagerard** [comment]
For this example to work, we could nest this System namespace in another namespace like this:
using colAlias = System.Collections;
namespace MyNamespace
{
    namespace System
    {
        class TestClass
        {
            static void Main()
            {
                // Searching the alias:
                colAlias::Hashtable test = new colAlias::Hashtable();

                // Add items to the table.
                test.Add("A", "1");
                test.Add("B", "2");
                test.Add("C", "3");

                foreach (string name in test.Keys)
                {
                    // Searching the global namespace:
                    global::System.Console.WriteLine(name + " " + test[name]);
                }
            }
        }
    }
}

In this case, if I remove "global::", I would get a compiler error.
This is not the case with the current code sample.

**Comment by svick** [comment]
Did you use the full example, including the `const int Console = 7;` line? Because with that, `Console.WriteLine(name + " " + test[name]);` does not work for me, as the article says.

**Comment by johnnyagerard** [comment]
Yes the example would work if we include two members named System and Console in the TestClass class.

Both the System namespace and the Console class would be hidden by those members.

**Comment by svick** [comment]
Sorry, I didn't realize you were talking about the *last* example, which does not include those members.

You're right that `global::System.` is not necessary there. Without that, I don't see the point of that example, so I think it can be removed.

**Comment by BillWagner** [comment]
the above analysis is correct.

I'm going to make a different recommendation: I think the last sample should stay, but the `global::System.Console.WriteLine` should be removed, as should the discussion of that in the preceding paragraph. The example and explanation of aliasing is still useful.

**Comment by svick** [comment]
@BillWagner 

> The example and explanation of aliasing is still useful.

Maybe, but I don't think it belongs to an article called "How to: Use the *Global* Namespace Alias". Though that could be easily fixed by changing that title.
