### ISSUE TITLE
Working example - with configuration from appsettings.json

### ISSUE THREAD

**Issue by haakoo** [dotnet/docs#6532]
It would be nice if there was an working example of how to use WCF from .Net core _the right way_. By that I mean using the recommended architecture from MS, loading configuration from `appsettings.json`, and ideally have the service reference in it's own .Net Standard project to isolate it from the rest of the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @haakoo for the feedback. @mlacouture any thoughts on this?

**Comment by JRAlexander** [comment]
@mlacouture any thoughts on this?

**Comment by mlacouture** [comment]
Hi @haakoo.  
let me make sure I understand your request:
1. Can you be more specific about what you mean by 'recommended architecture from MS'? do you mean the recommended solution for the problem you are trying to resolve?
2. Loading configuration from appsettings.json is something specific to ASP.NET, the .NET Core platform doesn't have support for appSettings currently.  Are you looking for some settings related to the web service you are adding a reference for?
3. What do you mean by having its service reference in it's own .NET Standard project? do you mean having a separate class library project to which you add the web service reference code and that is referenced by the ASP.NET project?

thank you!
Miguel Lacouture

**Comment by haakoo** [comment]
To quickly explain where I'm at; I'm converting an old (.Net 4.0) application (consuming and serving WCF-services) to .Net Core. I can't change the WCF-service I'm consuming, but I'm converting from WCF to WebApi where I can.

1. Basically the [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) example and _Architecting Modern Web Applications with ASP.NET Core and Azure_ e-book.

2. I thought the _appsettings.json_ and _ConfigurationBuilder_ were for .Net Core, and after trailing for I while I figured it was only for ASP.NET. Is this something that might end up in .Net Core? Would be handy with a built in Configuration-system and DI.

3. I'd like to abstract away the WCF-service-client into it's own library. The idea is that the WCF-service eventually will become WebApi, and that we would like to _"easily"_ sawp the WCF-client for a WebApi-client later.

Was that a bit clearer?

**Comment by haakoo** [comment]
I just tried a bit more, and by using the nuget-package [Microsoft.Extensions.Configuration.Json](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/) I could use:

```csharp
var builder = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json");

Configuration = builder.Build();
```

Now to figure out how to pass the loaded configuration to the generate WCF-client.

**Comment by mlacouture** [comment]
Good progress 👍 - the generated client provides a partial method you can implement for configuring the service endpoint bindings, the method signature looks like the following:

`static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials)`

**Comment by jmiller-bayshore** [comment]
@mlacouture, i just added a connected service reference to a .net core 2.0 library project and it didn't generate a ConfigureEndpoint method.  and the client class it did generate the constructor requires Binding and EndpointAddress parameters.  I cant seem to find these anywhere.  do you have any suggestions on where i should look to find information on this?

**Comment by mlacouture** [comment]
Hi @jmiller-bayshore, did you get any warnings when adding the web service reference? this may happen when the service metadata doesn't define a specific endpoint.  If you didn't get any errors, can you [open an issue in GitHub](https://github.com/dotnet/wcf/issues/new), and if possible can you also provide the service URL or wsdl file?

**Comment by jmiller-bayshore** [comment]
@mlacouture,
Initially i was getting the "System.ServiceMode.ServiceContactAttribute could not be found" which i found was a problem with my nuget settings not able to get to one of the packages.  After that i was able to get everything added and compiling, just not finding good references on using the code and it seems quite a bit different from how it used to work in previous .NET frameworks.  This thread seemed promising until i hit the block with the configure endpoint you had mentioned.  I can put a ticket on github with the service url

**Comment by haakoo** [comment]
I'm back at this now, and feeling a little stuck. I'd like to be able to send the configuration to the client using the constructor, including any credentials, certificates or more. The idea is to create a .Netstandard2.0 library which I then consume in a .Net Core app. The WCF service will be replaced in the not too distant future, and we'd like to abstract away WCF now. Later we'll just have to change the _ServiceClient_ without changing the main app / logic.

Something like this psudo code:

```csharp

// Build configuration and add to DI container

public class ServiceProxy : IServiceProxy
{
    private readonly IWcfService _wcfService;
    private readonly iWebApi _webApi;

    public ServicProxy(IConfiguration configuration)
    {
        // Get nesecarry information from configuration

        BasicHttpsBinding binding = new BasicHttpsBinding();
        EndpointAddress address = new EndpointAddress("");
        ClientCredentials cc = new ClientCredentials();
        
        _wcfService = new WcfServiceClient(binding, address, cc);


        var webApi = new WebApiClient("foo", "bar");
    }

    public string GetStatus()
    {
        return _wcfService.GetStatus();
    }

    public string GetListOfItems()
    {
        return _webApi.GetListOfItems();
    }

    ...
}
```
