### ISSUE TITLE
Conditional ref operator

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#6534]
Conditional ref operator (mentiond here: https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-72) is a C# 7.2 feature but it's not mentioned on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f86ebf5-b5c0-324a-43df-c17015729d01
* Version Independent ID: 8ce4ad4a-3dbd-42dc-bae3-230900097299
* Content: [What's new in C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#feedback)
* Content Source: [docs/csharp/whats-new/csharp-7-2.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-2.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @paulomorgado 

I've added it to the next sprint to address.
