### ISSUE TITLE
DataRowVersion description is misleading for Default

### ISSUE THREAD

**Issue by keenam** [dotnet/docs#6535]
DataRowVersion description indicates the Default version would yield Original value for a delete row. (`The default row version for a Deleted row is Original. `)

That's not the case. There's another link for DataRowVersion that correctly indicates Default for Delete Row (`Current`)  https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowversion?view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273bfebc-2647-21c3-a3be-d41cd32bf837
* Version Independent ID: e77ad9b3-4776-fab6-5287-c285b082abdd
* Content: [Row States and Row Versions](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/row-states-and-row-versions)
* Content Source: [docs/framework/data/adonet/dataset-datatable-dataview/row-states-and-row-versions.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/dataset-datatable-dataview/row-states-and-row-versions.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@BillWagner was this one closed by mistake?
