### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#6536]
`public D(int i) : B(i, out var j)`should be `public D(int i) : base(i, out var j)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0320fd-c7ac-200e-7e50-6b3ddcaa6a52
* Version Independent ID: 6ea1af7f-2251-f05f-4834-5a00e57fc5fb
* Content: [What's new in C# 7.3](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3)
* Content Source: [docs/csharp/whats-new/csharp-7-3.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-3.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing that out @paulomorgado I've submitted #6536 to fix this.

When you find issues like this that have an obvious fix, you can click the "edit" button and create the PR instead of writing the issue. In cases like this, it may save us both time. 🏎
