### ISSUE TITLE
Not allowed in Visual Basic for Applications 7.1

### ISSUE THREAD

**Issue by justinTM** [dotnet/docs#6539]
Hey there!

I'm getting syntax compile-time errors when using this operator (and the "+=" operator) in Visual Basic for Applications 7.1 (2012). Just a heads up because you might want to warn people about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9428c377-2798-2955-b41b-353bcf64c150
* Version Independent ID: 0e08839d-6f7d-ae82-293d-504b3802a93b
* Content: [&= Operator (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/and-assignment-operator#see-also)
* Content Source: [docs/visual-basic/language-reference/operators/and-assignment-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/and-assignment-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @justinTM. Unfortunately, https://docs.microsoft.com/dotnet/visual-basic documents Visual Basic .NET only, and not Visual Basic for Applications. Since differences between VBA and Visual Basic .NET are beyond the scope of the documentation, I'll close this issue.

**Comment by mairaw** [comment]
You can find the list of VBA operators at https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/operators.
