### ISSUE TITLE
Small feedback box on bottom right corner vanishes before you finish typing.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#6544]
When you open a documentation page, there's a small popup on the bottom right of the page which asks "Is this page helpful?". If you click YES, it says "thanks" then gives a link where you can give comments or suggestions. Pressing that link opens up a small comment box and if you start typing and keep going for a few seconds, it just vanishes (I think the timer that makes it vanish when you have nothing to say should be disabled when you start providing feedback, exactly the way it does if you said NO at the beginning).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195fe883-b65a-3e27-594a-66d05c1e60f6
* Version Independent ID: 311a6aa1-9d6c-7dbb-c026-19451ad0b383
* Content: [ReaderWriterLockSlim Class (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim?view=netstandard-2.0#remarks)
* Content Source: [xml/System.Threading/ReaderWriterLockSlim.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ReaderWriterLockSlim.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @ericmutta. I've moved your issue to https://github.com/MicrosoftDocs/feedback/issues/534, given this is a problem with the site functionality.

**Comment by ericmutta** [comment]
@mairaw many thanks for following up!
