### ISSUE TITLE
Documentation for ML.Net 0.3

### ISSUE THREAD

**Issue by astmehalthakor** [dotnet/docs#6546]
There may be a need to update the Documentation (Features available) of ML.Net 0.3. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@astmehalthakor, thanks for your feedback!, This is planned for the next sprint.

**Comment by Korenvais** [comment]
Hello,
I am currently working at Check Point and would like to know when the 'Anomaly detection' functionality will be available/release since It will be great for one the company's projects. Willing to do BETA test to get early release. Thanks & Regards

**Comment by JRAlexander** [comment]
@mairaw - Yes, this will be taken care of with https://github.com/dotnet/docs/pull/9156. Thanks for checking!
