### ISSUE TITLE
Don't use transparent backgrounds in images

### ISSUE THREAD

**Issue by StevenLiekens** [dotnet/docs#6547]
The diagrams are impossible to read in Dark mode because they contain black text and shapes on a transparent background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: fa6385e8-91ad-7949-382f-ca8e03f8201c
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @StevenLiekens. 
@CESARDELATORRE can we generate non-transparent versions of the images for the e-books? It does look bad on Dark mode indeed:

![image](https://user-images.githubusercontent.com/12971179/42971748-4535b390-8b62-11e8-9ba4-4f9f42438743.png)

**Comment by mairaw** [comment]
@CESARDELATORRE where we can get new images from? We need to make sure that the images for docs are generated with a background to not cause issues with dark theme. It has been a consistent feedback for the e-book on docs.

**Comment by StevenLiekens** [comment]
Suggestion: fix it with a style instead of replacing all the images.

```css
.theme_night img {
  background-color: white;
}
```

**Comment by mvelosop** [comment]
@mairaw, could you find out if it's possible to change the css?

I verified @StevenLiekens' solution and it would solve the issue:
![image](https://user-images.githubusercontent.com/7357806/45816967-2d5e2280-bcd5-11e8-82a4-7340b7cd5eb4.png)

**Comment by mairaw** [comment]
I haven't received a response yet. @adkinn @DuncanmaMSFT can you please take a look at this suggestion?

**Comment by mairaw** [comment]
@adkinn @DuncanmaMSFT new ping on this. I'd like to know if we can fix this on the engineering side instead of replacing all images.

**Comment by mairaw** [comment]
Also tagging @nishanil per @CESARDELATORRE's comment 
https://github.com/dotnet/docs/pull/8827#issuecomment-437480235

**Comment by mvelosop** [comment]
Another solution could be adding the style as html in the markdown, we should try first if the style added like this works: (haven't actually tried it)
```
<style>
    .theme_night img {
      background-color: white;
    }
</style>
```

**Comment by adkinn** [comment]
@mairaw unfortunately there is nothing currently available to help with this. You could work with @dend to get a new feature request submitted.

**Comment by mvelosop** [comment]
Thx @adkinn, it's a pity 🙁

@mairaw do you want to test including the above style in a page? If it works we'd have to update all the pages, but it's waaay easier and faster that updating all images 😓

**Comment by adkinn** [comment]
@mvelosop we also don't allow custom CSS like that, sorry :/

/cc @mairaw

**Comment by mvelosop** [comment]
Thanks for the info @adkinn.

Anyway I found the [ImageMagick](https://imagemagick.org) tool that can batch process all images to set a white background when transparent, so @mairaw let's just wait for the whole book to be merged and then I'll process all images into a single PR.

I'll leave the tested command here:

```bat
for %f in (media\*.png) do magick media\%f -background white -alpha remove media-fixed\%f
```

This creates a media-fixed folder with the new images.

**Comment by mairaw** [comment]
A coworker just referred the same tool to me @mvelosop:

> consider https://imagemagick.org/script/index.php to script something like convert in.png -alpha off out.png or convert in.png -background black -alpha remove -alpha off out.png

Sounds like a plan!

**Comment by mvelosop** [comment]
Great 😊
