### ISSUE TITLE
CatalogType is missing

### ISSUE THREAD

**Issue by samboustani** [dotnet/docs#6554]
CatalogBrand also missing.  Incomplete documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 376577d9-c559-9d5d-e263-ff9f0fb6ac27
* Version Independent ID: 29164c20-12a7-6bf2-a946-03ef2477d61b
* Content: [Creating a simple data-driven CRUD microservice](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/data-driven-crud-microservice.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @samboustani,

This section is not intended to be a documentation for the Catalog.Api microservice, but just a sample to showcase a simple CRUD pattern, so juts the details deemed important for that goal are documented.

Also, for that kind of detail (and for this simple case) there's probably no better documentation that source code 😉.

So I'm closing this issue, but feel free to comment. Will reopen if needed.
