### ISSUE TITLE
This is a fantastically useful article

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#6561]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 153e045b-c112-2680-df56-70270afbf1a9
* Version Independent ID: 4dc73bd5-260a-c40d-d972-b8ee23f6ec05
* Content: [Large Data and Streaming](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/large-data-and-streaming)
* Content Source: [docs/framework/wcf/feature-details/large-data-and-streaming.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/large-data-and-streaming.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks, @StingyJack, for the feedback! We've glad it helped you!
