### ISSUE TITLE
Optional types section missing part of example

### ISSUE THREAD

**Issue by turing-complet** [dotnet/docs#6562]
This section seems to end prematurely without providing example usage of option types. It ends with `let CustomerShippingZone (calculator: IShippingCalculator, customer: Customer) =`  which I assume would include the useful parts if it was continued. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour of F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tour)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks @turing-complet, it seems that the line ranges for including chunks of the sample code for the F# tour were offset a bit. This is addressed in #6588

**Comment by turing-complet** [comment]
Sounds good, I will close this then.
