### ISSUE TITLE
Button is a kind of Control

### ISSUE THREAD

**Issue by yanxiaodi** [dotnet/docs#6566]
"for example, the Button class is a kind of Control event". I think "event" should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b47b5f-7a8e-5f9b-10dd-ed409fa1b57a
* Version Independent ID: 60b5834c-41ba-37b8-5f35-74e890d7f92f
* Content: [Names of Classes, Structs, and Interfaces](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces)
* Content Source: [docs/standard/design-guidelines/names-of-classes-structs-and-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/names-of-classes-structs-and-interfaces.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @yanxiaodi. You are correct that the text should not describe Control as an event. Unfortunately, though, this is copyrighted material that we do not hold the copyright for, and as a result we can't change it. So unfortunately, I'll have to close this issue. Thank you again, though, for submitting your feedback.
