### ISSUE TITLE
Why are these repeated?

### ISSUE THREAD

**Issue by hagatorn** [dotnet/docs#6570]
&lt;requestCaching&gt; Element (Network Settings)	Specifies the modules used to request information from Internet hosts.
&lt;requestCaching&gt; Element (Network Settings)	Configures basic network options for the System.Net namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 489be477-8555-f4f3-06c2-c65419786c3a
* Version Independent ID: feff90fe-26a0-bf8b-3a87-260f5cd59611
* Content: [Network Settings Schema](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/index#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/network/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @hagatorn. The duplication is an unintentional one that has persisted for a long time in our documentation set. I've opened PR #6585 to eliminate the duplicate item and correct the description.
