### ISSUE TITLE
Arch. microservices figure 4-10: Inconsistent entity names

### ISSUE THREAD

**Issue by bartlannoeye** [dotnet/docs#6574]
Following entity names should be pluralized in the picture to be consistent with the rest of the entity names:

- Conferences Management > Country
- Orders and Registration > Reservation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29b58eb-8681-1a9b-93bb-431e3d7c68c8
* Version Independent ID: 3c121eca-c7e7-b0a6-3db0-c7ddbb14fb0a
* Content: [Identifying domain-model boundaries for each microservice](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/identify-microservice-domain-model-boundaries)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/identify-microservice-domain-model-boundaries.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/identify-microservice-domain-model-boundaries.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your suggestion @bartlannoeye. @CESARDELATORRE can you take a look at this request?

**Comment by mvelosop** [comment]
Will be included in the next PR.

**Comment by mvelosop** [comment]
Included in the PR waiting for the merge.
