### ISSUE TITLE
C# 1.2 is missing

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#6575]
C# 1.2 is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @paulomorgado. We'll look into this.

**Comment by paulomorgado** [comment]
https://stackoverflow.com/a/247623/402366
