### ISSUE TITLE
Feedback on String Interpolation

### ISSUE THREAD

**Issue by shehackspurple** [dotnet/docs#6582]
I had a friend run through all of this last night.  He said steps 4-7 for the String Interpolation were explained in a way that confused him, he found it hard to understand.

He also mentioned when introducing the "Trim" method, that the example seemed over complicated, and that parentheses character was introduced, but then not explained.  So he was unsure what it does.  

He suggested using a simpler or less-complicated example for Trim.

The said the rest of the entire tutorial was a pleasure, easy to follow and understand.  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2cc16c-fcf9-41e6-a1e5-92dfc2869495
* Version Independent ID: 4421a02c-f819-1483-12c6-7dab4f289a46
* Content: [C# interactive tutorials - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/#feedback)
* Content Source: [docs/csharp/quick-starts/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/quick-starts/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@shehackspurple are you talking about the [Hello C#](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world) quickstart?
- The [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings) quickstart has only five steps
- The `Trim` method is introduced at the [step 4](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=4) of the "Hello C#" quickstart

@BillWagner there is another issue with the "Hello C#" quickstart: the [step 3](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=3) discusses the `+` operator for string concatenation, but all code examples use string interpolation. Moreover, the string interpolation is presented at the [step 2](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=2) as alternative to using the `+` operator. So, the step 3 shouldn't mention the `+` operator in the concatenation context anymore.

**Comment by shehackspurple** [comment]
Yes, I am talking about that tutorial.  

Was that helpful feedback?

**Comment by pkulikov** [comment]
@shehackspurple thank you for the clarification. 

> He also mentioned when introducing the "Trim" method, that the example seemed over complicated, and that parentheses character was introduced, but then not explained.

As for the parentheses, I can imagine that the following code might be confusing:
```csharp
string trimmedGreeting = greeting.TrimStart();
Console.WriteLine($"[{trimmedGreeting}]");
```

While braces is the part of the C# syntax and mean string interpolation to a compiler, the square brackets are the part of the text to display; they are used to simplify display of leading and trailing white spaces. Or empty parentheses in the method call are confusing?

Your feedback is helpful, thank you. It turns out that the "Hello C#" quickstart should be make clearer.

**Comment by shehackspurple** [comment]
Hello all, it’s the “[“ character.  When someone is new, *everything* is new.  My friend was totally lost and thought he had missed something earlier in the tutorial.  Perhaps we should cut that part out until it’s explained what that character does?  Honestly, I’m a VB.net person and I am also just learning C# and I didn’t know what [ was for either.  :-D

Thank you for improving this so that all new learners have an easier time. 

Tanya Janca
@SheHacksPurple
http://devslop.co/
https://medium.com/@shehackspurple
https://www.slideshare.net/TanyaJanca
