### ISSUE TITLE
dotnet build does not generate *.runtimeconfig.json

### ISSUE THREAD

**Issue by newton3** [dotnet/docs#6583]
dotnet build does not generate *.runtimeconfig.json with both 2.0 and 2.1, the document is not quite right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Hi @newton3 I just checked and I see the file generated in the `\bin\Debug\netcoreapp2.1` output folder. Can you check your output folders?

**Comment by mairaw** [comment]
Given we haven't heard back from you @newton3 and we can't repro this, I'm closing this issue.
