### ISSUE TITLE
"Member Names" chart is incorrect for attributes on fields

### ISSUE THREAD

**Issue by wrummler** [dotnet/docs#6586]
The chart says (paraphrasing), "[if a] call occurs within [an] attribute constructor [then the] member name result [is] the name of the member to which the attribute is applied". Seems to imply that this might work for fields, but I've tested it, and it's true for attributes applied to properties, not for attributes applied to fields.

Relevant SO post: https://stackoverflow.com/q/35488646/402749

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6762d9-17f9-b4f2-e0ff-a919a0d861c0
* Version Independent ID: bc653d72-afa1-aa4c-e130-74bd181b53bd
* Content: [Caller Information (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information#MEMBERNAMES)
* Content Source: [docs/csharp/programming-guide/concepts/caller-information.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/caller-information.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for noting this @wrummler 

Adding that addition to the document would provide a more complete explanation. I've added this to the backlog.
