### ISSUE TITLE
State default values for Trainers' Properties.

### ISSUE THREAD

**Issue by hadjipantelis** [dotnet/docs#6590]
It would be very convenient if defaults values are clearly stated in the documentation (eg. `100` in the case of integer or `TRUE/FALSE` in the case of Boolean arguments). 

Thank you for all your work on this, it is a very impressive project!

Pantelis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16ede7f5-56c2-40ee-406a-c03f817c8e05
* Version Independent ID: 71daea4f-09c0-b264-5080-acc06d0993a7
* Content: [FastTreeRegressor.NumTrees Property (Microsoft.ML.Trainers)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttreeregressor.numtrees?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers/FastTreeRegressor.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers/FastTreeRegressor.xml)
* GitHub Login: @dotnet-bot

**Comment by mairaw** [comment]
Thanks for your suggestion @hadjipantelis. We'll take a look.

**Comment by mairaw** [comment]
Closing this since this API no longer exists. /cc @natke
