### ISSUE TITLE
New Topic: Creating localized exception messages

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#6598]
# New Topic: Creating localized exception messages

Our [Best practices for exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#include-a-localized-description-string-in-every-exception) article mentions creating localized exception messages, but it provides no guidance on how to do this. What's needed is a simple walkthrough that creates a custom exception, uses resources to store localized exception messages, and shows how to use satellite assemblies and [ResourceManager](https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager) to retrieve the appropriate exception message at runtime.

Related to #6576

**Comment by Youssef1313** [comment]
@rpetrusha , I've started writing the article, but not sure if I can write a good article suitable to be published. Can you please have a look at what I've so far ?
https://github.com/Youssef1313/test/blob/master/README.md
