### ISSUE TITLE
Extensions don't match in examples

### ISSUE THREAD

**Issue by user135711** [dotnet/docs#6599]
I believe the line `dlg.DefaultExt = ".text"; // Default file extension` should be `dlg.DefaultExt = ".txt"; // Default file extension`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc9312d-0333-286d-9d05-aaae6b98011d
* Version Independent ID: 5dd7b554-95f7-e86c-7338-2c8714a23df4
* Content: [Dialog Boxes Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/dialog-boxes-overview)
* Content Source: [docs/framework/wpf/app-development/dialog-boxes-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/dialog-boxes-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @user135711. Do you want to open a PR for this?

**Comment by user135711** [comment]
Sure, let me test it in an app first just to be sure.
