### ISSUE TITLE
question

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6604]
I don't understand the following sentence:
"If one of the floating-point types is double, the expression evaluates to double, or bool in relational or Boolean expressions."

How would an expression evaluates to bool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6f9e34-ee46-1de3-45ed-aa671aa7b098
* Version Independent ID: 31f63781-c0a6-0171-25e6-2ca3f0d004dc
* Content: [double keyword (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/double)
* Content Source: [docs/csharp/language-reference/keywords/double.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/double.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by johnnyagerard** [comment]
We're talking about comparison operators right ?
Like x < y  or x == y.
But not Boolean operators like x && y or x || y.

**Comment by rpetrusha** [comment]
Thanks for your question, @johnnyagerard. Yes, the relational expression is a comparison operation. The bitwise And and Or operators cannot be used with Double, and they're not relational operators in any case.  
The phrase "or bool in relational or Boolean expressions" is used twice in this document, and it could be made clearer. It also appears in the [float](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/float) documentation. I'll add it to an upcoming sprint.
