### ISSUE TITLE
Addins and extensibility is halfway on msdn and halfway on ms docs.

### ISSUE THREAD

**Issue by user135711** [dotnet/docs#6612]
The linked topics to msdn in the [add-ins](https://docs.microsoft.com/en-us/dotnet/framework/add-ins/index) topic should be moved to ms docs if they are still valid. 

I count the following links from ms docs:
http://msdn.microsoft.com/library/5d268dde-11df-4c4d-a022-f58d88bbc421
http://msdn.microsoft.com/library/bedcbcdf-5964-4215-b5f3-3299798b2b3f
http://msdn.microsoft.com/library/7afe7ec8-5158-4350-9119-5df0ecab8aa5
http://msdn.microsoft.com/library/7afe7ec8-5158-4350-9119-5df0ecab8aa5
http://msdn.microsoft.com/library/57a9c87e-394c-4fef-89f2-aa4223a2aeb5

These two topics aren't linked to but exist:
https://msdn.microsoft.com/en-us/library/bb892925(v=vs.100).aspx
https://msdn.microsoft.com/en-us/library/bb788288(v=vs.100).aspx
https://msdn.microsoft.com/en-us/library/bb384171(v=vs.100).aspx
and all the subtopics in pipeline development except for one walk through:
https://msdn.microsoft.com/en-us/library/bb384201(v=vs.100).aspx

---
The [pipeline developmnet](https://docs.microsoft.com/en-us/dotnet/framework/add-ins/pipeline-development) and walkthrough subtopics on ms docs are also full of msdn links.

**Comment by mairaw** [comment]
Thanks @user135711. The docs on MSDN are from a previous version and topics that aren't here were retired/removed at some point. We'd have to look to see if it makes sense to bring those back.

**Comment by user135711** [comment]
Yes, but they have interdependent links/concepts so I suspect some left
behind are still relevant even if not updated. I'll update this after
reading through them though.

**Comment by mairaw** [comment]
I'm closing this issue since that content was all moved to the archive. If there's any that you think it's still worth to have in our main docs site, please let us know and we can consider whether it's worth porting them or not @user135711.
