### ISSUE TITLE
Cannot find name and timeout attributes under basichttpbinding

### ISSUE THREAD

**Issue by rajkamal221283** [dotnet/docs#6613]
I am using .Net 4.5.1 and cannot see such attributes on the basichttpbinding as shown here
under
&lt;basicHttpBinding   
        name="shortTimeout"  
        timeout="00:00:00:01"   
     /&gt;  

These attributes can be visible only under binding tag/field  of basichttpbinding. 

&lt;basichttpbinding&gt;
&lt;binding name=??? /&gt;
&lt;/basichttpbinding&gt;

Can you please update the documentation. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a094cbcc-76d7-fd3d-eccf-d9793ad6eaa3
* Version Independent ID: d96b63cf-b13a-3ce7-0dd5-f0f4b3178977
* Content: [Configuring Bindings for Windows Communication Foundation Services](https://docs.microsoft.com/en-us/dotnet/framework/wcf/configuring-bindings-for-wcf-services)
* Content Source: [docs/framework/wcf/configuring-bindings-for-wcf-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/configuring-bindings-for-wcf-services.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by manojninganiya** [comment]
Hi please use like this syntax:

<configuration>
  <system.serviceModel>
    <bindings>
      <wsHttpBinding>
        <binding openTimeout="00:10:00" 
                 closeTimeout="00:10:00" 
                 sendTimeout="00:10:00" 
                 receiveTimeout="00:10:00">
        </binding>
      </wsHttpBinding>
    </bindings>
  </system.serviceModel>
</configuration>

**Comment by manojninganiya** [comment]
<configuration>
  <system.serviceModel>
    <bindings>
      <wsHttpBinding>
        <binding openTimeout="00:10:00" 
                 closeTimeout="00:10:00" 
                 sendTimeout="00:10:00" 
                 receiveTimeout="00:10:00">
        </binding>
      </wsHttpBinding>
    </bindings>
  </system.serviceModel>
</configuration>

**Comment by mairaw** [comment]
Tagging @HongGit
