### ISSUE TITLE
dotnet test doesn't respect DOTNET_UI_LANGUAGE env variable

### ISSUE THREAD

**Issue by karyaevsm** [dotnet/docs#6614]
See the subject.

```dotnet --info``` obeys the environment variable, but ```dotnet test``` doesn't.

**Steps to reproduce:**

$ export DOTNET_CLI_UI_LANGUAGE=en-US

$ echo $DOTNET_CLI_UI_LANGUAGE
en-US

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

$ dotnet test Auth.Test
**Сборка начата, подождите...
Попытка отменить сборку...
Попытка отменить сборку...
Попытка отменить сборку...
Попытка отменить сборку...**

**Comment by svick** [comment]
This isn't an issue with documentation, so dotnet/docs this is not the right repo for it. I think a good repo for this issue is [dotnet/cli](https://github.com/dotnet/cli). Can you close the issue here and reopen it there?

And when you, can you clarify whether the environment variable you're talking about is `DOTNET_UI_LANGUAGE` or `DOTNET_CLI_UI_LANGUAGE`? You seem to be using both.

**Comment by karyaevsm** [comment]
Uops, what a shame on me! (

Thank you for quick reply.

PS: Yes I've experimenting with setting both variables when the one from docs have not worked for me.
