### ISSUE TITLE
Comment in example violates content neutrality

### ISSUE THREAD

**Issue by jmlarch** [dotnet/docs#6615]
The following comment can be interpreted as taking sides on a hot-button issue: Retrieve Darwin's "Origin of the Species" from Gutenberg.org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcfe22a9-486f-f4d4-2611-94dc2b76e4d0
* Version Independent ID: 71ebda9d-6cb2-2927-d009-58d984bebce8
* Content: [How to: Use Parallel.Invoke to Execute Parallel Operations](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations?view=netframework-4.7.2)
* Content Source: [docs/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @jmlarch. We'll change this on a future revision of our docs.
