### ISSUE TITLE
Code split in multiple boxes

### ISSUE THREAD

**Issue by SheepRock** [dotnet/docs#6618]
Along all the article, code is splited in several boxes. For example, the image bellow shows one piece of code that is splited in 3 code boxes:

![image](https://user-images.githubusercontent.com/20205505/43078637-66e86d32-8e61-11e8-9bd6-c472bd922fcb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f6fd8f-6037-a178-b1eb-792dedabbbf7
* Version Independent ID: 01553bdb-d7e3-f134-3208-595e630f7e47
* Content: [Data Templating Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-templating-overview)
* Content Source: [docs/framework/wpf/data/data-templating-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-templating-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @SheepRock. This is a known issue that resulted from migration from our old authoring system to GitHub; see issue #2994. I've added the issue to our community contributors' project so that members of the community can address it. 
I'm going to close this issue as a duplicate.

**Comment by SheepRock** [comment]
@rpetrusha Thanks! I tried to correct the issue, but I didn't understood the sintax. This is the code:

```
 [!code-xaml[DataTemplatingIntro_snip#Resources](../../../../samples/snippets/csharp/VS_Snippets_Wpf/DataTemplatingIntro_snip/CSharp/Window1.xaml#resources)]  
[!code-xaml[DataTemplatingIntro_snip#UI1](../../../../samples/snippets/csharp/VS_Snippets_Wpf/DataTemplatingIntro_snip/CSharp/Window1.xaml#ui1)]  
[!code-xaml[DataTemplatingIntro_snip#UI2](../../../../samples/snippets/csharp/VS_Snippets_Wpf/DataTemplatingIntro_snip/CSharp/Window1.xaml#ui2)]  
```

The link didn't open, but I found [the file](https://github.com/dotnet/samples/blob/master/snippets/xaml/VS_Snippets_Wpf/DataTemplatingIntro/xaml/window1.xaml) In the file, I didn't understand how it's referenced by "#UI2" etc, as I didn't see any thing that resembles this tag. 

Also, How do I do to merge all three blocks in the same block? I read [this readme](https://github.com/dotnet/samples/blob/master/README.md) but it didn't help me.

**Comment by rpetrusha** [comment]
Thanks, @SheepRock, for responding. I'll respond to your questions somewhat later, in about five hours.
