### ISSUE TITLE
Create Tutorial on Azure EasyAuth

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#662]
Would be great to see a nice ASP.NET Core tutorial on this, in our Tutorials directory.

Info: https://azure.microsoft.com/en-us/documentation/videos/azure-websites-easy-authentication-and-authorization-with-chris-gillum/?cdn=disable

**Comment by mairaw** [comment]
Should this be here or on aspnet/Docs?

**Comment by mairaw** [comment]
@Rick-Anderson @tdykstra this seems to be something that would be covered in your docs. Should we open an issue on your repo?

**Comment by tdykstra** [comment]
@mairaw Seems a better fit for the Azure repo, which already has ASP.NET docs which will eventually need to be updated to ASP.NET Core.  Easy auth itself is not framework-specific.

cc @cephalin @rachelappel

**Comment by rachelappel** [comment]
@tdykstra @mairaw @richlander Yes, this should go in the Azure repo

**Comment by BillWagner** [comment]
@tdykstra @rachelappel  Do we now have something for this in the Azure repo? If so, let's close this.

**Comment by tdykstra** [comment]
What I said in the Dec 16, 2016 comment still applies -- better fit for the Azure repo ... Easy auth is not framework-specific.  

We have something like this on our backlog. We do have something now but it needs work.

cc/ @cephalin @ggailey777

**Comment by BillWagner** [comment]
Closing per @tdykstra
