### ISSUE TITLE
Do not use MailAddress.MailAddress(String) class constructor to check email address validity!

### ISSUE THREAD

**Issue by irigopou** [dotnet/docs#6620]
The MailAddress.MailAddress(String) class constructor throws no exception when the input string contains empty spaces!
This means that a string with empty spaces would be validated as a proper email address, if we were to use the technique suggested on the top of this article.
I have checked the above with .NET 4.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
@davidsh, can you comment on the use of the Mail.MailAddress.#ctor(String) to validate an email address? Do we need to remove mention of it from this regex topic, where it's presented as the preferred alternative to a regex?

**Comment by pkulikov** [comment]
To provide provide more context, I've tested the constructor under discussion with some inputs that contain white spaces and checked the resulting [MailAddress.Address property](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress.address?view=netframework-4.7.2).

The following list presents the results:
- "" (empty string) results in `ArgumentException` 
- " " (string that contains only white spaces) results in `FormatException`
- "jkt@gmail.com" (no white spaces) results in "jkt@gmail.com"
- " jkt@gmail.com" or "jkt@gmail.com " (white spaces at the start or at the end) results in "jkt@gmail.com" (no white spaces)
- "jkt@ gmail.com" (white space is directly after `@`) results in "jkt@gmail.com" (no white spaces)
- "jkt@g mail.com" (any not trailing white space after `@` except the above case) resuls in `FormatException`
- "jkt @gmail.com" (white space is in front of `@`) results in "jkt@gmail.com" (no white spaces)
- "j kt@gmail.com" (white space is before `@`, inside the username) results in "kt@gmail.com" (the part after a white space is taken as the mail address)

**Comment by davidsh** [comment]
We've gotten a lot of questions on this topic over the years.  The short answer is that the MailAddress constructor is never going to be up-to-date with manually using a regex.  Changing the parser inside the constructor to fix bugs will break some applications.  So, we have refrained from changing the behavior this class.

>Do we need to remove mention of it from this regex topic, where it's presented as the preferred alternative to a regex?

Yes, I would remove that language. Using a regex using the most recent RFC definitions would be the best choice.

**Comment by EliCDavis** [comment]
@svick I don't think many people attempt to write an email regex, as there's already provided documentation.

**Comment by pkulikov** [comment]
@EliCDavis, to my understanding, so far it was an example of how to use regex, rather than the attempt to create the regex that validates any email address. That regex should be improved as well: #5305
