### ISSUE TITLE
[operator overload] Please add a complete example and more informations

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#6626]
@TobiasSekan commented on [Sat Jul 21 2018](https://github.com/dotnet/docs.de-de/issues/91)

Hello, please add 
1. A complete example with all possible operators
2. Information about the opposite operators (e.g. `<<` need `>>` , `==` need `!=` )
3. `GetHashCode()` and `Equals(object a)` should be implement when compare operators are used
4. Links to important interfaces for operators `IComparable`, `IConvertible`, `IEquatable` `IFormattable` etc.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 247c7eb1-fb6c-8135-71c8-5f5e50fcb8ed
* Version Independent ID: 7a3a204e-445e-d434-8141-4ed5eb409213
* Content: [operator (C#-Referenz)](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/operator)
* Content Source: [docs/csharp/language-reference/keywords/operator.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/language-reference/keywords/operator.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hi team, the user is requesting more examples for the file.

Thanks!

**Comment by JRAlexander** [comment]
The [Anweisungen, Ausdrücke und Operatoren (C#-Programmierhandbuch)](https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/statements-expressions-operators/index) should give you the information you're looking for.
